### ISSUE TITLE
reST heading behaviour is out of conformance with specification

### ISSUE THREAD

**Issue by EnronEvolved** [jgm/pandoc#10004]
The issue can be reproduced online using `pandoc --from rst --to native --no-highlight` with the following example from the [reST specification](https://docutils.sourceforge.io/docs/ref/doctree.html#section):
``` rst
Title 1
=======
Paragraph 1.

Title 2
-------
Paragraph 2.

Title 3
=======
Paragraph 3.

Title 4
-------
Paragraph 4.
```

The spec provides a pseudo-XML illustrating the analogous parsed structure:

```
<document>
    <section ids="title-1" names="title 1">
        <title>
            Title 1
        <paragraph>
            Paragraph 1.
        <section ids="title-2" names="title 2">
            <title>
                Title 2
            <paragraph>
                Paragraph 2.
    <section ids="title-3" names="title 3">
        <title>
            Title 3
        <paragraph>
            Paragraph 3.
        <section ids="title-4" names="title 4">
            <title>
                Title 4
            <paragraph>
                Paragraph 4.
```

However, the pandoc output is flat:

```
[ Header
    1 ( "title-1" , [] , [] ) [ Str "Title" , Space , Str "1" ]
, Para [ Str "Paragraph" , Space , Str "1." ]
, Header
    2 ( "title-2" , [] , [] ) [ Str "Title" , Space , Str "2" ]
, Para [ Str "Paragraph" , Space , Str "2." ]
, Header
    1 ( "title-3" , [] , [] ) [ Str "Title" , Space , Str "3" ]
, Para [ Str "Paragraph" , Space , Str "3." ]
, Header
    2 ( "title-4" , [] , [] ) [ Str "Title" , Space , Str "4" ]
, Para [ Str "Paragraph" , Space , Str "4." ]
]
```

For this test, I used to online version of pandoc at https://pandoc.org/try, but for completeness sake the version that reproduces this problem locally for me (on Linux Mint 21.3) is pandoc 3.2.1 installed from the binary package provided on Github.

I don't think this is the intended behaviour, as the pandoc output ought to behave like the reST document tree.

**Comment by jgm** [comment]
Pandoc doesn't have containers for sections the way RST does.  But pandoc is correctly representing the structure (note the difference between Header 1 and Header 2).  If you use `-t html --section-divs`, you'll also get the non-flat structure you want:

```html
<section id="title-1" class="level1">
<h1>Title 1</h1>
<p>Paragraph 1.</p>
<section id="title-2" class="level2">
<h2>Title 2</h2>
<p>Paragraph 2.</p>
</section>
</section>
<section id="title-3" class="level1">
<h1>Title 3</h1>
<p>Paragraph 3.</p>
<section id="title-4" class="level2">
<h2>Title 4</h2>
<p>Paragraph 4.</p>
</section>
</section>
```
