### ISSUE TITLE
employ the already established `.unlisted` class in markdown also in the ePUB writer

### ISSUE THREAD

**Issue by vv01f** [jgm/pandoc#10028]
```
pandoc 3.1.2
Features: +server +lua
Scripting engine: Lua 5.4
```

As [described earlier](https://github.com/jgm/pandoc/issues/1762#issuecomment-662158284) in #1762 I'd like to create toc without including each heading and also not needing to handcraft each toc … `.unlisted` sounds still perfect, especially as they already are `.unnumbered` as well
also same behaviour in different writers would be nice, so e.g. epub and pdf output are not needing adjustments on the source.

https://github.com/jgm/pandoc/issues/1762#issuecomment-1350409762 said I should ask, so I do despite of the same request being raised before have been declined. 

also workaround with `toc-depth` is not working at all, as the toc still includes level3 while being limited to level1 :\

**Comment by jgm** [comment]
There are two tables of contents -- which are you asking about?
There is nax.xhtml, which is only added if you specify `--toc`.
And there is toc.ncx, which is always present and must be present in an EPUB.

**Comment by jgm** [comment]
We should presumably use `toTOCTree` from `Text.Pandoc.Chunks` in creating the nav.xhtml, and perhaps also toc.ncx.

**Comment by jgm** [comment]
OK, I've tried a couple of tests, and both `--toc-depth` and `.unlisted` class seem to work fine in the EPUB writer, for both nav.xhtml and toc.ncx, with pandoc 3.2.1.

Please give detailed instructions for reproducing the issue.

**Comment by jgm** [comment]
I see you're using an older version, so try upgrading to the latest.

**Comment by vv01f** [comment]
ok, that works in newer versions :)
