### ISSUE TITLE
`pandoc server` not emitting code highlighting

### ISSUE THREAD

**Issue by sjml** [jgm/pandoc#10046]
**Explain the problem.**
Pandoc server seems to be returning different rendered HTML than the standard command line. I'm only just starting to play with the server functionality, so it could be I'm doing something wrong. And if highlighting is simply not available from the server, that's fine, but [the documentation](https://github.com/jgm/pandoc/blob/master/doc/pandoc-server.md) seems to indicate it should work. 

Here's a simple invocation of the executable. 
```shell
$ printf '```python\ndef hello():\n  print(\"hello\")\n```' | pandoc --from "markdown" --to html

<div class="sourceCode" id="cb1"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> hello():</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">&quot;hello&quot;</span>)</span></code></pre></div>
```

But the same markdown text sent to the server as a request gives plain HTML. 
```shell
$ pandoc server &
[1] 45063
Starting server on port 3030...
$ curl --request POST \
  --url http://localhost:3030/ \
  --header 'Content-Type: application/json' \
  --data '{
  "text": "```python\ndef hello():\n  print(\"hello\")\n```",
  "from": "markdown",
  "to": "html"
}'

<pre class="python"><code>def hello():
  print(&quot;hello!&quot;)</code></pre>
```

**Pandoc version?**
```shell
$ pandoc --version
pandoc 3.2.1
Features: +server +lua
Scripting engine: Lua 5.4
```
Installed on macOS via Homebrew.

**Comment by jgm** [comment]
Try adding
```
highlight-style: "pygments"
```
It could be that the defaults for server are a bit different than the defaults for the CLI.

**Comment by sjml** [comment]
That did it! Thanks, @jgm. Are the server defaults documented anywhere?
