### ISSUE TITLE
How to Added the Text Align and Text Color added the HTML to DOCX convert

### ISSUE THREAD

**Issue by PerlDeveloperSurya** [jgm/pandoc#10059]
parsed content [<main><h1 style="text-align: right; color: blue">Centered Heading</h1><p horizontal-pos="center">This is a left-aligned paragraph.</p><p align="right">This is a right-aligned paragraph.</p><p align="justify">This is a justified paragraph. Justified text is aligned along the left and right margins, adding extra space between words as necessary.</p></main>] render the docx but alignment and color not reflect the DOCX.

**Comment by jgm** [comment]
Alignment and color are stylistic details that pandoc ignores.  Please read the first few paragraphs of the User's Guide.

**Comment by PerlDeveloperSurya** [comment]
feature he will be added the color and align

**Comment by iandol** [comment]
You could make a lua filter to read some html properties and convert them to docx styles?

**Comment by PerlDeveloperSurya** [comment]
Please given the some sample
