### ISSUE TITLE
Inconsistent heading levels with AsciiDoc output

### ISSUE THREAD

**Issue by jeffmelville** [jgm/pandoc#10062]
When converting fragments to AsciiDoc, heading levels are not converted consistently. It appears that the lowest level heading always gets converted to ``===`` in AsiiDoc.   See example below. In both examples, I would expect ``### third`` to convert to ``=== third``.  The issue occurs when exporting with ``nbconvert``, which executes ``pandoc`` on one Jupyter cell at a time.

Also see: https://github.com/jupyter/nbconvert/issues/1456

```
➜  ~ pandoc --version
pandoc 3.1.9
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/jmelville/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
➜  ~ echo -e '### third\n' | pandoc -t asciidoc
== third
➜  ~ echo -e '## second\n### third\n' | pandoc -t asciidoc
== second

=== third
```

**Pandoc version?**

3.1.9 on MacOS 
I also re-ran on 3.3 to confirm.

**Comment by jgm** [comment]
Asciidoc sections are not supposed to have gaps, e.g.
```
== one

==== four
```
If you try this you'll get a warning like
```
asciidoc: WARNING: my.adoc: line 3: section title out of sequence: expected level 3, got level 4
```

So, we normalize them before writing.  This is by design.

Note:  it seems that asciidoc (original) also required the first heading level to be `==`, but asciidoctor does not.  So we could perhaps change this behavior.

**Comment by jeffmelville** [comment]
Ah - I guess how I see it gets that way. There aren't gaps in the test vectors per se, but since ``nbconvert`` calls ``pandoc`` individually with each cell, it's possible for each call to pandoc to not have the right context.  Something like this:

**Cell 1** (Markdown):
```
## Some section title
```

** Cell 2** (Code):
```
IPython.display.display_image(image_bytes)
```

**Cell 3** (Markdown)
```
### Subsection Title

#### Sub-subsection Title
```

will get converted as

```
== Some section title

image::image_path.png[]

== Subsection Title       # <-  This is one level too low

=== Sub-subsection Title   # <- This is also one level too low, but correctly +1 from its parent in the cell
```

There another issue with ``nbconvert`` and AsciiDoc output (https://github.com/jupyter/nbconvert/pull/2152) but I'm working around that one within nbconvert. 

Its hard for me to figure out how to correctly use pandoc AsciiDoc output with Markdown fragments given the current behavior.  If I export the whole notebook as Markdown first, I can use pandoc to convert that to AsciiDoc but I lose some other information.

**Comment by jgm** [comment]
Due to changes in `makeSections`, pandoc no longer ensures "gaplessness" in the sections anyway.  Since asciidoc has changed in caring about the bottom level, I'm just going to remove that feature and have it use whatever level was in the original...
