### ISSUE TITLE
How to added custom table border XHTML to DOCX

### ISSUE THREAD

**Issue by PerlDeveloperSurya** [jgm/pandoc#10067]
<table class="tabletypeone">
								<colgroup>
									<col data-colname="col1" data-colnum="1" data-colalign="center" style="border-left: 0.5pt solid; border-right: 0.5pt solid; width: 70.05pt;"/>
									<col data-colname="col2" data-colnum="2" data-colalign="center" style="border-right: 0.5pt solid; width: 70.05pt;"/>
									<col data-colname="col3" data-colnum="3" data-colalign="center" style="border-right: 0.5pt solid; width: 70.00pt;"/>
									<col data-colname="col4" data-colnum="4" data-colalign="center" style="border-right: 0.5pt solid; width: 70.00pt;"/>
									<col data-colname="col5" data-colnum="5" data-colalign="center" style="border-right: 0.5pt solid; width: 70.05pt;"/>
								</colgroup>
								<tbody>
									<tr style="border-bottom: 0.5pt solid; border-top: 0.5pt solid;" border="border-bottom: 0.5pt solid"> 
										<td data-indexid="c0000-t0040" style="text-align: center; border-right: 0.5pt solid">
											<p type="paragraph" data-indexid="c0000-p0140">
												Test1
											</p>
										</td>
										<td data-indexid="c0000-t0045" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0145">
												Test2
											</p>
										</td>
										<td data-indexid="c0000-t0050" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0150">
												Test3
											</p>
										</td>
										<td data-indexid="c0000-t0055" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0155">
												Test4
											</p>
										</td>
										<td data-indexid="c0000-t0060" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0160">
												Test3
											</p>
										</td>
									</tr>
									<tr>
										<td data-indexid="c0000-t0065" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0165">rucksack</p>
										</td>
										<td data-indexid="c0000-t0070" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0170">pencil</p>
										</td>
										<td data-indexid="c0000-t0075" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0175">pen</p>
										</td>
										<td data-indexid="c0000-t0080" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0180">pencil case</p>
										</td>
										<td data-indexid="c0000-t0085" style="text-align: center;">
											<p type="paragraph" data-indexid="c0000-p0185">folder</p>
										</td>
									</tr>
								</tbody>
							</table>
						how to render the table custom border

**Comment by jgm** [comment]
You already put this question in Discussions. Please do not open an issue too.
