### ISSUE TITLE
In pandoc 3.3 html tables rendered from markdown don't look right

### ISSUE THREAD

**Issue by therealgenna** [jgm/pandoc#10073]
**Explain the problem.**
I am running `rmarkdown` within R. In the end it's calling `pandoc` to create html output. The command is like that:
```
PANDOC=<path>/env/bin/pandoc
$PANDOC +RTS -K512m -RTS \
  run.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash \
  --output run.html \
  --lua-filter $ENV/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua \
  --lua-filter $ENV/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua \
  --embed-resources --standalone --variable bs3=TRUE --section-divs \
  --table-of-contents --toc-depth 3 --variable toc_float=1 --variable toc_selectors=h1,h2,h3 --variable toc_collapsed=1 \
  --variable toc_smooth_scroll=1 --variable toc_print=1 \
  --template $ENV/lib/R/library/rmarkdown/rmd/h/default.html \
  --no-highlight --variable highlightjs=1 --variable theme=bootstrap \
  --css leftjustify.css \
  --mathjax --variable 'mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' \
  --include-in-header /tmp/RtmpnvLnyX/rmarkdown-str16204b65985cf3.html \
  --variable code_folding=hide --variable code_menu=1
```

I have two environments, an old one with pandoc 3.1.3 and a new one with 3.3. Both environments produce I believe a valid `.md` file with a table that looks like
```
Table: Original cell counts

|Sample | Freq|
|:------|----:|
|Leah1  | 2938|
|Leah3  | 5847|
|Leah4  | 5307|
|Leah6  | 5757|
|Leah7  | 5897|
|Leah8  | 5536|
|T1     | 8703|
|T2     | 9052|
```

However, the new pandoc (3.3) makes ugly html tables, e.g.:
![image](https://github.com/user-attachments/assets/d9b75099-93a1-4004-9e7f-ada5fd70296f)

While the older one is what I expect:
![image](https://github.com/user-attachments/assets/e404d215-7294-45b4-9c5d-2b0c0fda888f)

I've tracked the problem to the change in pandoc 3.2.1, I believe.
It got rid of header, odd, even classes on tr ([#9376](https://github.com/jgm/pandoc/issues/9376)) in version 3.2.1 (linked from https://pandoc.org/releases.html). **If I add these "classes" manually back to the final html, it then looks fine.**

Here on the left is new version, without "classes", and on the right it's my manual edits, adding "classes":
```
<table>                                                         <table>
<caption>Original cell counts</caption>                         <caption>Original cell counts</caption>
<thead>                                                         <thead>
<tr>                                                          | <tr class="header">
<th align="left">Sample</th>                                    <th align="left">Sample</th>
<th align="right">Freq</th>                                     <th align="right">Freq</th>
</tr>                                                           </tr>
</thead>                                                        </thead>
<tbody>                                                         <tbody>
<tr>                                                          | <tr class="odd">
<td align="left">Leah1</td>                                     <td align="left">Leah1</td>
<td align="right">2938</td>                                     <td align="right">2938</td>
</tr>                                                           </tr>
<tr>                                                          | <tr class="even">
<td align="left">Leah3</td>                                     <td align="left">Leah3</td>
<td align="right">5847</td>                                     <td align="right">5847</td>
</tr>                                                           </tr>
<tr>                                                          | <tr class="odd">
<td align="left">Leah4</td>                                     <td align="left">Leah4</td>
<td align="right">5307</td>                                     <td align="right">5307</td>
</tr>                                                           </tr>
...                                                             ...
```

Adding the classes back, as on the right, fixes the issue and the table looks good in the web browsers.

**Pandoc version?**
3.3 on Linux

**Comment by jgm** [comment]
I assume you're using some custom CSS?
In any case, you just need to change the CSS to conform to the new structure.  The classes we were adding weren't necessary, as new CSS selectors can be used to style the header and even/odd rows.
There is some information on this in the changelog.

**Comment by jgm** [comment]
PS. You may need to consult with RMarkdown maintainers, who will know more about how the CSS is applied; they will need to update things, probably, to work with the new pandoc defaults.

**Comment by therealgenna** [comment]
Thanks. Are you talking about the `leftjustify.css`? It's just to fully utilize the webpage space. Its full content is just
```
div.main-container {
  max-width: 100% !important;
}
```
I have the same issue if I don't use that CSS at all. I provide it in `.Rmd` file, which just gets verbatim into the `.md`.

But I guess your point still remains that RMarkdown maintainers need to do some fixes. I'll post there, thank you.

**Comment by therealgenna** [comment]
That has been fixed on the `rmarkdown` side: https://github.com/rstudio/rmarkdown/issues/2567

**Comment by bpj** [comment]
I see they "fixed" it by adding the classes back in with a filter rather than by changing their CSS to use child selectors. @jgm maybe the concepts involved in doing it with CSS are too challenging. I'm not sure I mean that Pandoc should add the classes back, but maybe an example of the kind of CSS needed[^1] should be added to the Pandoc manual.

[^1]: I'm not *quite* sure of what it should be yet myself but only because I haven't had time to look into it properly.

**Comment by jgm** [comment]
I believe something like this would work:
```
thead tr { /* styling that used to go on .header */ }
tbody tr:nth-child(2n) { /* styling that used to go on .even */ }
```
