### ISSUE TITLE
Pandoc Writer - JSON encoder not respecting array type

### ISSUE THREAD

**Issue by somonek** [jgm/pandoc#10079]
The issue is with the pandoc json encoder. If you have an empty object, which is supposed to become an array, but never gets any elements inserted, when encoded to json, the output is `{}` instead of `[]`.

`my-writer.lua` code:
```
function Writer(doc, opts)
    local shouldBeAnArray = {}
    setmetatable(shouldBeAnArray, { __isarray = true })

    return pandoc.json.encode(shouldBeAnArray)
end
```

cli command:
`pandoc my-doc.ext -t my-writer.lua`

Pandoc version:
```
pandoc 3.3
Features: +server +lua
Scripting engine: Lua 5.4
```

**Comment by tarleb** [comment]
Use `pandoc.List` to force a list:

```
% pandoc lua -e 'print(pandoc.json.encode({}))'
{}

% pandoc lua -e 'print(pandoc.json.encode(pandoc.List{}))'
[]
```

We could consider to check the `__isarray` field of the metatable. Are there JSON libraries that do this?

**Comment by bluebergscientific** [comment]
thanks @tarleb . Was not aware of `pandoc.List{}`. Exactly what I needed.
