### ISSUE TITLE
conversion to .tex breaks line about documentclass

### ISSUE THREAD

**Issue by nbehrnd** [jgm/pandoc#10072]
**Explain the problem.**

I write short markdown file (cf. attached zip archive, `example.md`) with a header like

```markdown
---
author: Pen Paperclip
title:  My new essay
date:   2024-08-08
----
```

After the conversion into LaTeX  by 

```bash
pandoc example.md -s -o test.tex
```

the newly written file breaks the initialization about the document class across two lines:

```latex
\documentclass[
]{article}
```

While this syntax is not wrong to compile a .pdf, I would prefer it were all on one line, i.e.

```latex
\documentclass[]{article}
```

to ease a subsequent programmatic edit of pandoc's output.  For instance,

```bash
sed -i 's/\documentclass.*/\documentclass[a4paper,draft]{scrartcl}/' test.tex
```

to quickly change in favor of the similar document type within the [KOMA class](https://ctan.org/pkg/koma-script) without need of a dedicated style sheet/filter file.

**Pandoc version?**

Pandoc version 3.3 as fetched from this project page as amd64.deb, running in Linux Debian 13/trixie.

[test_export.zip](https://github.com/user-attachments/files/16550771/test_export.zip)

**Comment by jgm** [comment]
You can easily get the behavior you desire by using a custom template.  See the manual on how to do this.  When you look at the default template, you'll see why it comes out the way it does.

**Comment by nbehrnd** [comment]
One has to get used to the design principle.  Indeed the manual, a run of `pandoc -D latex` and 
the answer by user DG' on [tex.stackexchange](https://tex.stackexchange.com/questions/573431/how-do-i-adapt-a-standard-latex-template-for-pandoc-in-a-docker-container-not) as a practical minimal working example paved the way.

The answer by him/her provides a really gentle and brief 101 about the creation of templates of LaTeX (and in general) departing from a document known to work.  While I think it would nicely complement the manual, I have no idea (yet) if this snippet could fit into the manual e.g., just prior to section "template syntax", or an other place of the documentation.

> Let's take this minimal latex document `mwe.tex`:
>
> ```latex
> \documentclass{article}
> \begin{document}
> Here is some text.
> \end{document}
> ```
> Now you can replace `Here is some text` [i.e., in file `mwe.tex`] with `$body$` and execute `echo "Here is some different text" | pandoc --template mwe.tex -s --to latex` and you will see, that `$body$` is replaced with the text.

With this material, the initial issue of this thread however is closed.
