### ISSUE TITLE
Leading tabs in code block are not retained in org reader with `-p`

### ISSUE THREAD

**Issue by minyez** [jgm/pandoc#10071]
**Explain the problem.**
I tried to convert an org-mode file to Markdown. When using pandoc with `-p` option to preserve the tabs in the Makefile source block, I found the leading tab is converted to single space while the other tabs remain unexpanded.

**Minimal example**
```shell
$ cat example.org
#+begin_src makefile
%.o: %.cpp
	$(CXX)	-o	$@	$<
#+end_src
```
There is a leading tab and tabs between entries in the directive. When converted to markdown with and without `-p`
```shell
$ pandoc -f org -t json -p example.org
{"pandoc-api-version":[1,23,1],"meta":{},"blocks":[{"t":"CodeBlock","c":[["",["makefile"],[]],"%.o: %.cpp\n $(CXX)\t-o\t$@\t$<\n"]}]}
$ pandoc -f org -t json example.org
{"pandoc-api-version":[1,23,1],"meta":{},"blocks":[{"t":"CodeBlock","c":[["",["makefile"],[]],"%.o: %.cpp\n    $(CXX)  -o  $@  $<\n"]}]}
```

On the other hand, the markdown reader seems fine (I don't know how to make markdown block within a code block correctly rendered, so I added a comma before backticks)
```shell
$ cat example.md
,```makefile
%.o: %.cpp
	$(CXX)	-o	$@	$<
,```
$ pandoc -f markdown -t json -p example.md
{"pandoc-api-version":[1,23,1],"meta":{},"blocks":[{"t":"CodeBlock","c":[["",["makefile"],[]],"%.o: %.cpp\n\t$(CXX)\t-o\t$@\t$<"]}]}
$ pandoc -f markdown -t json example.md
{"pandoc-api-version":[1,23,1],"meta":{},"blocks":[{"t":"CodeBlock","c":[["",["makefile"],[]],"%.o: %.cpp\n    $(CXX)  -o  $@  $<"]}]}
```

**Expected behavior**
```shell
$ pandoc -f org -t json -p example.org
{"pandoc-api-version":[1,23,1],"meta":{},"blocks":[{"t":"CodeBlock","c":[["",["makefile"],[]],"%.o: %.cpp\n\t$(CXX)\t-o\t$@\t$<\n"]}]}
```

**Pandoc version?**
pandoc is installed using homebrew on macOS Sonoma
```shell
$ pandoc --version
pandoc 3.3
Features: +server +lua
Scripting engine: Lua 5.4
```

**Comment by minyez** [comment]
Hi @tarleb as far as I know there is no org-export variable directly related to tab, but there is a variable called `org-src-preserve-indentation` to control how to handle code block indentation. When it is `nil`, the minimum leading whitespace characters (including tabs) are removed and the code lines are re-indented. When non-`nil`, the leading characters are preserved.

For the current example, I use org-export to do an org-to-org conversion. Emacs is run with `emacs -Q`. When `org-src-preserve-indentation` is `t`
```
#+begin_src makefile
%.o: %.cpp
	$(CXX)	-o	$@	$<
#+end_src
```
All tabs are retained. When `org-src-preserve-indentation` is `nil`
```
#+begin_src makefile
  %.o: %.cpp
          $(CXX)	-o	$@	$<
#+end_src
```
It replaces the leading tab with 8 white spaces, and add 2 spaces on both lines. The other tabs are preserved.

**Comment by tarleb** [comment]
Interesting, thanks. If I understand correctly, then setting `org-src-preserve-indentation` to a non-nil value is equivalent to adding the `-i` flag to all *src* blocks.

In principle, it should be enough to add the `-i` flag to the src block while also calling pandoc with the `-p` command line flag.

``` org
#+begin_src makefile -i
%.o: %.cpp
	$(CXX)	-o	$@	$<
#+end_src
```

However, it seems that the leading tab is currently lost and converted to a single space. I'm therefore re-adding the *bug* label.

**Comment by minyez** [comment]
I was never aware of the capability to add this kind of flag to src block. I tried just now but didn't find any difference when exporting it. Did I miss something?

```shell
$ cat example.org
#+begin_src makefile -i
%.o: %.cpp
	$(CXX)	-o	$@	$<
#+end_src
$ pandoc -f org -t json -p example.org
{"pandoc-api-version":[1,23,1],"meta":{},"blocks":[{"t":"CodeBlock","c":[["",["makefile"],[]],"%.o: %.cpp\n $(CXX)\t-o\t$@\t$<\n"]}]}
```

**Comment by tarleb** [comment]
Exactly, that's the bug, and it should be fixed now. Please try the next nightly built, which should become available in about 15 hours.

**Comment by minyez** [comment]
I will try then, thanks a lot for the quick fix! A remaining question is: is the `-i` flag the same as the one of pandoc CLI, i.e. `-i/--incremental`?

The reason I am asking is that there seems no way to retain `-i`-type source block flags when doing an org-to-org export, which is necessary using an [`ox-pandoc`](https://github.com/emacsorphanage/ox-pandoc) backend in Emacs. So I would prefer using a command line flag similar to `-i`-type flag for certain source block.

**Comment by tarleb** [comment]
The `-i` flag of the pandoc CLI and of orgmode *src* blocks are entirely separate.

**Comment by minyez** [comment]
Thanks for clarification, I understand now it is a orgmode src block flag rather than a pandoc one. I was only aware of head arguments starting with `:`. Could you please maybe share your knowledge of similar `-` flags, or direct me to some documentation? I searched the "16 Working with Source Code" section of org-mode manual, but found nothing relevant.

**Comment by tarleb** [comment]
E.g. https://orgmode.org/manual/Literal-Examples.html
But pandoc supports only a subset of those.
