### ISSUE TITLE
Reference to template breaks md to docx conversion

### ISSUE THREAD

**Issue by PlainMartin** [jgm/pandoc#10089]
[Pandoc version 3.3 / macOS]

In my projects, I am using a `default.yml` file that will create HTML documents, and it references a template:

~~~
to: html
template: template.htm
[other settings]
~~~

When I need to create _Word_ documents, I will load a second default file overriding only the `to` option:

~~~
to: docx
reference-doc: reference.docx
~~~

So: 

~~~
pandoc -in.md default.yml default_word.yml --output=out.docx
~~~

This worked fine for years, but now (I think since 3.3) I found that the reference to a template breaks the docx conversion. A docx file with an XML structure _will_ be created, but both Microsoft Word and other apps will refuse to open it with an unspecified error. Removing the `template` option resolves the issue.

I am confused. The manual says under [“Templates”](https://pandoc.org/MANUAL.html#templates) that “docx and pptx have no template”. Yet even when a template is referenced, something breaks.

Am I missing something here / doing something dumb, or is this a bug?

**Comment by jgm** [comment]
Yes.  Prior to 3.3, `--template` did nothing for docx output, but now it is possible to specify a template for docx (it must be an OpenXML document template, see our documentation).  That is why it is failing when you pass in your HTML template.

**Comment by PlainMartin** [comment]
@jgm  Sorry if I missed something, but what does “see our documentation” refer to? I would actually be interested in using this, but the Pandoc manual only has four references to OpenXML (regarding includes and raw_attribute), and I couldn't find a description or link in the 3.3 release notes (only a fixed list issue is mentioned in the Docx section). 

I would love to understand if templates (as shown by `pandoc -D docx`) replace or complement reference docs going forward, and if/how I can place style definitions in that template. I know my way around CSS + HTML workflows, but Open XML is a a bit intimidating. Thank you.

**Comment by jgm** [comment]
Templates complement reference docs.  Reference docs can be used to adjust styles, while templates can provide things like boilerplate content.

**Comment by jgm** [comment]
OpenXML is intimidating indeed.  You'll have to look up the documentation.  You can also look inside document.xml in pandoc-generated docx to get an idea for how it works.

**Comment by PlainMartin** [comment]
Thank you so much! This is (probably 😉) all the information I need to get started. I only need Word output sometimes, but being able to use includes here is actually great.
