### ISSUE TITLE
Sanitize \LaTeX macros in PDF outlines.

### ISSUE THREAD

**Issue by ascherer** [jgm/pandoc#10090]
Processing the attached MWE with `pandoc outlines.md -o outlines.pdf` produces a nice PDF document that looks OK in the text part. However, other than on the main page, the name “TeX Live” is crippled in the “PDF outlines” (aka “bookmarks”). It would be nice to have it translated to `TeX Live`, just as in HTML output from `pandoc outlines.md -s -o outlines.tex; pandoc outlines.tex -s -o outlines.html`.

[outlines.md](https://github.com/user-attachments/files/16623706/outlines.md)
[outlines.pdf](https://github.com/user-attachments/files/16623707/outlines.pdf)

**Comment by ascherer** [comment]
In the meantime I learned about `\texorpdfstring` in the output of `pandoc outlines.md -s -o outlines.tex`. Curiously enough, `\TeX` is left empty, but `\ ` gets translated to `~` in the _second_ argument, too. (Don'z know what PDF actually does with it.)

Is there any way to define a “PDF-safe” alternative for a (plain) TeX macro inside the `*.md` file?

As a workaround, I can fix the “PDF part” in `outlines.tex` and run `pdflatex outlines.tex` (twice).

**Comment by ascherer** [comment]
I wonder why [this line](https://github.com/jgm/pandoc/blob/47c360e0795a5f27e4906ea22fff388b779f270a/src/Text/Pandoc/Readers/LaTeX.hs#L473) got removed?

**Comment by jgm** [comment]
Simple demonstration of the issue:
```
$ pandoc -t latex
# \TeX
^D
\section{\texorpdfstring{\TeX}{}}\label{section}
```
desired output would be
```
\section{\texorpdfstring{\TeX}{TeX}}\label{section}
```
Of course, we could add special-case treatment of the `\TeX` macro in this context, but that's not a very general solution.  In general there's not much we can do about built-in macros like `\TeX` short of hard-coding special treatment.

**Comment by ascherer** [comment]
Indeed, and this can get [nasty as hell](https://github.com/ascherer/cweb/blob/master/cwebacromac.tex#L103).

**Comment by priiduonu** [comment]
Is it maybe possible to enclose TeX macros in control sequence command? Like so:

```
$ pandoc -t latex
# \csname TeX\endcsname\ output
^D
\section{\texorpdfstring{\csname TeX\endcsname~output}{TeX~output}}\label{tex-output}
```

**Comment by ascherer** [comment]
Indeed! Thanks for the solution to my initial problem.
[outlines.md](https://github.com/user-attachments/files/23764964/outlines.md)
[outlines.pdf](https://github.com/user-attachments/files/23764963/outlines.pdf)
