### ISSUE TITLE
Incorrent simple table parsing for RST->Markdown

### ISSUE THREAD

**Issue by HollyAssasin** [jgm/pandoc#10093]
Failes to correctly transform and parse tables with empty columns when converting from RST to Markdown.
Here is a test table made in RST:
```
.. table:: Test Table

   ================================== ==== =========== =============== ===== === =====
   Functions for tests                1    2Test       3Untested       4Alg  5   6Col
   ================================== ==== =========== =============== ===== === =====
   a                                  yes              yes
   b                                       yes
   c                                                                         yes yes
   d                                  yes
   e                                                   yes             yes
   ================================== ==== =========== =============== ===== === =====
```
Base command used for running:
`pandoc in.rst -f rst -t markdown+simple_tables+grid_tables -o out.md`
Running this results in a grid table that is incorrect:
If ran with `+simple_tables+grid_tables`
```
+---------------------+-----+-------+-----------+------+-----+------+
| Functions for tests | 1   | 2Test | 3Untested | 4Alg | 5   | 6Col |
+=====================+=====+=======+===========+======+=====+======+
| a b c d e           | yes | yes   | yes       | yes  | yes | yes  |
|                     |     |       |           |      |     |      |
|                     | yes |       | yes       |      |     |      |
+---------------------+-----+-------+-----------+------+-----+------+
```

If ran with `+simple_tables-grid_tables` results in a regular table, but also incorrect:
```
<table>
<caption>Test Table</caption>
<thead>
<tr>
<th>Functions for tests</th>
<th>1</th>
<th>2Test</th>
<th>3Untested</th>
<th>4Alg</th>
<th>5</th>
<th>6Col</th>
</tr>
</thead>
<tbody>
<tr>
<td><p>a b c d e</p></td>
<td><p>yes</p>
<p>yes</p></td>
<td><p>yes</p></td>
<td><p>yes</p>
<p>yes</p></td>
<td><p>yes</p></td>
<td><p>yes</p></td>
<td><p>yes</p></td>
</tr>
</tbody>
</table>
```

How the table looks like in Markdown:
<table>
<caption>Test Table</caption>
<thead>
<tr>
<th>Functions for tests</th>
<th>1</th>
<th>2Test</th>
<th>3Untested</th>
<th>4Alg</th>
<th>5</th>
<th>6Col</th>
</tr>
</thead>
<tbody>
<tr>
<td><p>a b c d e</p></td>
<td><p>yes</p>
<p>yes</p></td>
<td><p>yes</p></td>
<td><p>yes</p>
<p>yes</p></td>
<td><p>yes</p></td>
<td><p>yes</p></td>
<td><p>yes</p></td>
</tr>
</tbody>
</table>

How it looks like in RST:
![image](https://github.com/user-attachments/assets/ad49ed09-6632-4674-babe-c1924e5cee7c)

**Pandoc version**
Tested on latest version 3.3 on Windows.

**Comment by jgm** [comment]
Smaller test case:
```
========== ====
Function   1   
========== ====
a          yes 
b              
========== ====
```
It does depend on the empty cell; if that is filled then we get two rows.
