### ISSUE TITLE
(Re-)integrate fountain reader

### ISSUE THREAD

**Issue by iwelch** [jgm/pandoc#10097]
referring to <https://github.com/jgm/pandoc/issues/4228>, 

Unfortunately, jgm's pandoc's instructions from 4 years ago no longer work, as they rely on external tools that are themselves deprecated.

Moreover, fountain.io's own reference code basically died about 10 years ago.

fountain is a very small markup language, <https://fountain.io/syntax/>, with some script idiosyncrasies.  fountain is the (only) standard script markup language.  this is not affected by fountain.io's demise.

I think this means an exporter to fountain is not needed or useful (RIP).

An importer of fountain would be very useful.    If pandoc implemented fountain, it would probably become the standard implementation, too. 

with very limited features, It shouldn't be too hard, either, as the fountain markup format is far more modest than, say, markdown.  Only scene headings seem slightly more complex.[^printing]

Unhampered by cooperation with fountain.io's bugs, and with its very few features in the markup, and *deliberately* ignoring simultaneous dialog (as noted in the discussion), I would think that `fountain->html` (for view) and `fountain->pdf` (for print) would be great, with `fountain->word` appreciated, would be easy and straightforward.

I am even tempted to write a standalone `fountain->html` in perl (a language I know), probably a few hours for the basics is all that I would need.  My only hesitation is that I may inadvertently generate html format that pandoc can no longer understand.

[^printing]: this is a little more complex.  there is a 55-line/page standard in the industry [<https://screenwriting.io/what-is-standard-screenplay-format/>], plus page numbers; and this broke in fountain.io's own code, probably as macOS converged to iOS over the last 10 years, seriously hampering usefulness of all kinds of code downstream, such as `Marked 2`.

**Comment by jgm** [comment]
I just tried the lua filter from jgm/pandoc-fountain, and it seems to work fine with latest pandoc.  What is the problem you're having with it?
```
pandoc -f fountain.lua --css fountain.css --template fountain.html5 -o out.html
Steel, in the middle of a heated phone call:

STEEL
They’re coming out of the woodwork!
(pause)
No, everybody we’ve put away!
(pause)
Point Blank Sniper?

.SNIPER SCOPE POV

From what seems like only INCHES AWAY.  _Steel’s face FILLS the *Leupold Mark 4* scope_.
^D
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to '-' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
```
Here's what the result looks like:
<img width="670" alt="image" src="https://github.com/user-attachments/assets/85f9e374-d917-4baa-995a-4e1e8c331b04">

**Comment by iwelch** [comment]
The principal problem starts with the installation...
```
$ brew reinstall wkhtmltopdf
Warning: wkhtmltopdf has been deprecated because it is discontinued upstream! It will be disabled on 2024-12-17.
```

Could you add your fountain input file?  When I run it on my own simple sample, I don't get anything that looks halfway nice.  I tried `--standalone` conversion, but I can't manage somehow.  I used

```
Title: A Script
Author: An author
Contact: <pandoc@pandoc.como>


.INT. SOMETIMES, SOMEWHERE

! The camera sweeps over the audience.

SINGER:
La la

FRIEND:
I love pandoc.

SINGER:
Really?
```

I checked in Marked-2 that this was a reasonable input file.  then I used

`pandoc --standalone -f fountain.lua -css fountain.css --template fountain.html5 sample.fountain -o out.html`.

probably my lack of knowledge, but with the `wkhtmltopdf` about to disappear, too,....

**Comment by jgm** [comment]
This worked fine for me.  It gives you an HTML file.  I don't know what it's supposed to look like, but this is what it does look like:

<img width="506" alt="image" src="https://github.com/user-attachments/assets/abdbc7e3-38c2-447c-9b6d-15c6e9d26ccb">

What's the problem?

If you want a PDF,
```
pandoc -f fountain.lua --css fountain.css --template fountain.html5 sample.fountain -o out.pdf --pdf-engine=wkhtmltopdf
```

If you don't want to use wkhtmltopdf, try installing pagedjs-cli, and use
```
--pdf-engine=pagedjs-cli
```
(there are a number of other options, described in the manual).

**Comment by jgm** [comment]
`-css` has the same meaning as `-c ss`, i.e. `--css ss`, so it's not actually wrong; it's just not what you intended.

**Comment by jgm** [comment]
I'll modify the repo as suggested.

**Comment by iwelch** [comment]
I know about the `-css` interpretation, but I bet you that 99.999% of people who type this meant `--css`.  thus, for the common dual-dash options (I would emit a warning (not an error).  In fact, I would do this for each --[a-z]+ option that you list in `pandoc --help`.

if you wanted more intelligence, for stupid people like myself, you could add a basic check on what follows.  'ss' would have had to be a URL.  but this is not worth the programming effort.
