### ISSUE TITLE
Missing link: macro in AsciiDoc for uncommon URL protocols

### ISSUE THREAD

**Issue by Maneren** [jgm/pandoc#10105]
Hello.

**Explain the problem.**
Links in AsciiDoc can be specified in few different ways, most notably as bare autolinks (`https://google.com[Google]`) or using the link macro (`link:https://google.com[Google]`). Pandoc currently uses the autolink for all links that start with a protocol (specifically those that contain a `:`), however AsciiDoc only recognizes a handful of most common protocols as autolinks (like http, ftp, mailto, ...), requiring the `link:` prefix for the rest (like smb).

The quick and dirty solution would be to just remove the if check that prevents the output of `link:` when deemed unnecessary. The only effect of that I can think of is to remove a bit of visual clutter but without any functional impact (I am not AsciiDoc expert so I may be missing something here tho).

Other, more correct, solution would be to mirror the AsciiDoc's list of supported protocols and depending on that add `link:` only if neccessary.

**Pandoc version?**
3.3

**Comment by jgm** [comment]
Sounds good. What is asciidoc's list of supported protocols?  We can add that check.

**Comment by Maneren** [comment]
AsciiDoctor officially supports only http, https, ftp, irc and mailto protocols for [autolinks](https://docs.asciidoctor.org/asciidoc/latest/macros/autolinks). All other need `link:`

**Comment by Maneren** [comment]
Thanks a lot, your response speed to these is just incredible
