### ISSUE TITLE
Citeproc Man Page: Broken Links and Typos

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#10101]
Using pandoc-citeproc `0.17.0.1` (which ships with pandoc `3.3`) under MS Windows, I've generated the citeproc manual using the `--man` option, and converted it to HTML via pandoc.

I've found some problems in the **pandoc-citeproc** man page (which is dated 2019-11-19, and probably outdated) and wanted to fix them, but I couldn't find the source file to edit.

The [citeproc] repository does apparently contain the markdown source of the man page ([`citeproc.1.md`][citeproc.1.md]), but that document is _much shorter_ than the actual document I got by using the `--man` option. I tried to locate the source of this longer version, both on the [citeproc] repository as well as in pandoc repository, but couldn't find it.

Therefore, since I can't find where to submit changes, I'm listing here my fixes suggestions ... Since **pandoc-citeproc** ships as part of the pandoc package, and because the following suggestions pertain to the man page of the `pandoc-citeproc` executable, and not the library, I'm opening this Issue under the pandoc repository, instead of [citeproc].

> [!NOTE]
>
> Since the man page was last updated about five years ago (Nov. 2019), it might be worth revising its entire contents, to ensure that all information is still current to the latest pandoc-citeproc release.

> [!TIP]
>
> It would be really useful if the [`CONTRIBUTING.md`][CONTRIBUTING.md] document of the pandoc repository could provide detailed information on how to edit the citeproc man page (the long version, from the `--man` option), with a link to its source file.

## HTTP Links: Use HTTPS instead

All links use the `http://` protocol, and should be updated to `https://`.

## DESCRIPTION » Filter mode

In section "Filter mode" there's a typo (marked in bold below):

> Run without options, \[...\]. If the CSL style **species hanging indent**, the class `hanging-indent` will be added to this Div.

- Fix: species &rarr; specifies

## NOTES » General

> If you use a CSL-YAML or CSL-JSON database, or a CSL-YAML metadata section in your markdown document, follow the “Citation Style Language 1.0.1 Language Specification”

The current [CSL Specification] is version `1.0.2`; is there a specific reason why the citeproc man mentions version `1.0.1`, or is it just outdated?

The links provided in this section of the man page are obsolete and should be updated — I'll provide here each original link, immediately followed by its updated counterpart, in pairs:

- ORIGINAL: <http://citationstyles.org/downloads/specification.html>
- UPDATED: <https://docs.citationstyles.org/en/stable/specification.html>

- ORIGINAL: <http://citationstyles.org/downloads/specification.html#appendix-iii-types>
- UPDATED: <https://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types>

- ORIGINAL: <http://citationstyles.org/downloads/specification.html#appendix-iv-variables>
- UPDATED: <https://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables>

## SEE ALSO

In section "SEE ALSO" the link provided to citeproc is outdated, pointing to the old (now archived) repository:

> The pandoc-citeproc source code and all documentation may be downloaded from <http://github.com/jgm/pandoc-citeproc/>.

- ORIGINAL: <http://github.com/jgm/pandoc-citeproc/>
- UPDATED: <https://github.com/jgm/citeproc>

[citeproc.1.md]: https://github.com/jgm/citeproc/blob/master/man/citeproc.1.md
[citeproc]: https://github.com/jgm/citeproc/

[CSL Specification]: https://docs.citationstyles.org/

[CONTRIBUTING.md]: https://github.com/jgm/pandoc/blob/main/CONTRIBUTING.md

**Comment by tarleb** [comment]
> Since **pandoc-citeproc** ships as part of the pandoc package,

This is no longer true: Citeproc is compiled into pandoc since, I think, pandoc 2.11 or even earlier. The `pandoc-citeproc` binary is no longer shipped with pandoc. There's probably an old version from an old pandoc installation on your system.

**Comment by tajmone** [comment]
> This is no longer true: Citeproc is compiled into pandoc since, I think, pandoc 2.11 or even earlier. The `pandoc-citeproc` binary is no longer shipped with pandoc.

I didn't know that; although I was aware of the new pandoc options for citations I thought that the citeproc tool was still being bundled as a convenience tool for batch conversion between formats.

> There's probably an old version from an old pandoc installation on your system.

Indeed, most likely. When I update pandoc I just install the new version over the older one, so nothing gets deleted.

Ok, no harm done.
