### ISSUE TITLE
Add executablePath Parameter for Custom Pandoc Executable Location

### ISSUE THREAD

**Issue by kcodesgh** [jgm/pandoc#10116]
I would like to suggest adding a key called executablePath as shown below (or in a similar way you think is best):

```
pypandoc = pandoc(executablePath='/cache/pandoc_file')
pypandoc.convert_text(html_content, output_format, format='html', outputfile=tmpfile.name)
```
This would be similar to how Puppeteer allows specifying the Chrome executable path. It would enable us to set our own path externally. This feature would be particularly useful for those of us compiling with Nuitka, where we need to manually specify the path to the executable when the files are unpacked.

**Comment by jgm** [comment]
I believe this is an issue for pypandoc.  This is not the pypandoc repository.

**Comment by kcodesgh** [comment]
> pypandoc

Oh really then i'm gonna suggest it there, Thank you for the correction
