### ISSUE TITLE
Latest version has issues with MiKTeX images

### ISSUE THREAD

**Issue by gabemorris12** [jgm/pandoc#10125]
**Explain the problem.**
I am converting a jupyter notebook to a PDF via MiKTeX (uses the `xelatex` engine). Jupyter nbconvert will fail with the current implementation of pandoc (version 3.3) when using images in the notebook, and I am not sure which version breaks the conversion process, but I know that 3.1.9 will work.

**Reproduce the Problem**
Make a jupyter notebook file that includes some image. The markdown would look something like this:

```
![Image not found](my_image.png)
```

Convert the notebook to a pdf with `nbconvert` like this: 

```
jupyter nbconvert --to pdf my_notebook.ipynb
```

This will throw an xelatex error. You can convert the notebook to a latex file with nbconvert using the same command above but `--to latex` instead. In the latex file, you'll notice a line like this:

```
\pandocbounded{\includegraphics[keepaspectratio]{my_image.png}}
```

But in previous versions of pandoc, the \pandocbounded command/macro is not included. I'm not sure if it's pandoc that needs to be changed or nbconvert that needs to be changed, but I wanted to ask here first. In the meantime, I have a whole class that downloaded the latest version of pandoc. Is there a way to get the msi downloader for previous versions? Thanks!

**Pandoc version?**
3.3 fails and 3.1.9 will pass

**Comment by jgm** [comment]
The `\pandocbounded` macro is one we define ourselves in the default LaTeX template. If nbconvert is using its own template, it will need to be modified to include this definition from our current default template.

You could probably work around this in the mean time by just adding this to your document, in a separate block before the images appear:
```
\newcommand{\pandocbounded}[1]{#1}
```

**Comment by gabemorris12** [comment]
That would work, but I need to make it where students of mine don't even look at the latex. I'll probably do some sort of PR in nbconvert to add the appropriate contents in the header template, but for now, is there a way to get an msi installer from previous versions of pandoc?

Also, is there more pandoc commands that to account for? Is there a pandoc package in latex for me to do the \usepackage command?

**Comment by jgm** [comment]
All the msi installers are available at https://github.com/jgm/pandoc/releases

A latex package is worth considering, perhaps. But no, there isn't one. All the commands are defined in the default latex template. People who use custom templates should take care to update them when they switch to new releases of pandoc.  We try to indicate relevant changes in the changelogs, and there is also the repository jgm/pandoc-templates that just has one commit for each new release, so you can easily track changes.  Tools like nbconvert should presumably pin to a particular pandoc version or have multiple templates (applied conditionally on the pandoc version used).

**Comment by jgm** [comment]
I knew that the addition of `\pandocbounded` would be a painful change.
See #9660 for why it was necessary.

**Comment by jgm** [comment]
Note that the changelog explicitly says:

>     - If custom templates are used with the new LaTeX writer, they will have
>       to be updated to include the new `\pandocbounded` macro, or an error
>       will be raised because of the undefined macro.
 
Always a good idea to read this when switching to a new release.

**Comment by gabemorris12** [comment]
@jgm I've made an issue in nbconvert, but I have prepared my heart for complete inaction. I will be using the older versions for the foreseeable future! Also, I just now noticed the GitHub interface with previous releases. That link is hiding on the side there. Thanks for being reachable!
