### ISSUE TITLE
Fails to parse div inside table (markdown)

### ISSUE THREAD

**Issue by mohd-akram** [jgm/pandoc#10120]
**Explain the problem.**

The following markdown input:

```markdown
<table>
    <tr><td><div>
    </div></td></tr>
</table>
```

yields this error:

```
Div at line 2 column 13 unclosed at line 7 column 1, closing implicitly.
```

I've tried this on https://pandoc.org/try/

Per [CommonMark](https://spec.commonmark.org/dingus/?text=%3Ctable%3E%0A%20%20%20%20%3Ctr%3E%3Ctd%3E%3Cdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%3C%2Ftd%3E%3C%2Ftr%3E%0A%3C%2Ftable%3E%0A), the entire thing should be parsed as HTML.

**Pandoc version?**
3.3

**Comment by jgm** [comment]
If you want commonmark rules to be used, then use `-f commonmark` or `-f gfm`. Pandoc's markdown parser predates commonmark and doesn't always agree with it.

`-f markdown-native_divs` will also give you what you want.

**Comment by mohd-akram** [comment]
Thanks. I run into another issue when using `-f commonmark` (in another document) - "Could not convert TeX math". I can't find a way to disable TeX parsing, however.

**Comment by jgm** [comment]
That has nothing to do with `-f commonmark`.  The warning would be triggered by the writer you're using, not the parser.  (e.g. if you're producing docx, the tex math would need to be converted to the right format -- if it can't be, it will be left as it is)

**Comment by mohd-akram** [comment]
@jgm The issue does not seem to happen when using `-f markdown` and I don't fully get why. This is what I have:

```markdown
<math display="block">
  <semantics><mrow><mrow><mo lspace="0em" rspace="0.16666666666666666em">𝙼𝚊𝚝𝚑.𝚊𝚝𝚊𝚗</mo><mo stretchy="false">(</mo><mi>𝚡</mi><mo stretchy="false">)</mo></mrow><mo>=</mo><mo lspace="0em" rspace="0em">arctan</mo><mo stretchy="false">(</mo><mi>x</mi><mo stretchy="false">)</mo><mo>=</mo><mtext>the unique&nbsp;</mtext><mi>y</mi><mo>∊</mo><mrow><mo>[</mo><mrow><mo>−</mo><mfrac><mi>π</mi><mn>2</mn></mfrac><mo>,</mo><mfrac><mi>π</mi><mn>2</mn></mfrac></mrow><mo>]</mo></mrow><mtext>&nbsp;such that&nbsp;</mtext><mo lspace="0em" rspace="0em">tan</mo><mo stretchy="false">(</mo><mi>y</mi><mo stretchy="false">)</mo><mo>=</mo><mi>x</mi></mrow><annotation encoding="TeX">\mathtt{\operatorname{Math.atan}(x)} = \arctan(x) = \text{the unique } y \in \left[-\frac{\pi}{2}, \frac{\pi}{2}\right] \text{ such that } \tan(y) = x</annotation></semantics>
</math>
```

```lua
-- raw.lua
function RawBlock(raw)
  return
    raw.format:match 'html' and pandoc.read(raw.text, 'html').blocks or
    raw
end
```

```shell
$ pandoc --fail-if-warnings --lua-filter=raw.lua -f markdown -t man index.md
.PP
\ 𝙼𝚊𝚝𝚑.𝚊𝚝𝚊𝚗(𝚡)=arctan(x)=the unique\ y∊[−π2,π2]\ such that\ tan(y)=x =
(x) =  y  (y) = x
$ pandoc --fail-if-warnings --lua-filter=raw.lua -f commonmark -t man index.md
[WARNING] Could not convert TeX math {\operatorname{\mathtt{M}\mathtt{a}\mathtt{t}\mathtt{h}.\mathtt{a}\mathtt{t}\mathtt{a}\mathtt{n}}(\mathtt{x})} = \arctan(x) = \text{the unique~}y \in \left\lbrack {- \frac{\pi}{2},\frac{\pi}{2}} \right\rbrack\text{~such that~}\tan(y) = x, rendering as TeX
Failing because there were warnings.
```

**Comment by jgm** [comment]
You will see the answer if you compare `pandoc -f markdown -t native` and `pandoc -f commonmark -t native` on this input.  Only the latter gives you a single raw block (and thus triggers your filter). The warning is because pandoc is not able to convert this tex to the native eqn format used in man.
