### ISSUE TITLE
Add ROR and affiliation information to JATS

### ISSUE THREAD

**Issue by cthoyt** [jgm/pandoc#10138]
In https://github.com/openjournals/inara/pull/72, I added ROR support to JOSS and other Open Journals built on top of the Inara repo. However, it uses Pandoc to generate JATS, and I was suggested to consider upstreaming support for annotating affiliation information in JATS - mainly for adding structured identifiers for affiliations from ROR

I am happy to give this one a stab, but I am not familiar with the Pandoc codebase so it will have a bit of a learning curve.

Some places that are probably relevant:

- https://github.com/jgm/pandoc/blob/1393cda27d791bc716dd66012a5471318d1e06ad/data/templates/article.jats_publishing#L123

**Comment by estedeahora** [comment]
I don't understand what you would want to add. Currently pandoc provides support for generating an xml-jats that incorporates the ROR field. I recommend you look at [this link](https://pandoc.org/jats.html). In your metadata, within the 'affiliation' field you should have tables containing the ror of each organization. We currently use this possibility in the journal and never had problems with it.

> Some places that are probably relevant:
> * https://github.com/jgm/pandoc/blob/1393cda27d791bc716dd66012a5471318d1e06ad/data/templates/article.jats_publishing#L123

This line of code tells you that a “partial” will be used, which is another file containing a part of the template. The indicated template is this: https://github.com/jgm/pandoc/blob/main/data/templates/article.jats_publishing

**Comment by cthoyt** [comment]
Hi @estedeahora, thanks for the reply. Based on your response, I might have been mistaken and this information already finds its way nicely! I appreciate all of the groundwork put into pandoc and hope I can link you to the efforts for the Open Journals that are incorporating ROR when the other PR I mentioned gets merged. Cheers!
