### ISSUE TITLE
Change default pdf-engine for HTML from wkhtmltopdf to weasyprint

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#10142]
Discussed in https://github.com/jgm/pandoc/discussions/10132

It seems that wkhtmltopdf has been deprecated (the underlying engine is ancient).

We should change the default `--pdf-engine` for HTML to `pagedjs-cli` or `weasyprint`.
Consensus is that `weasyprint` is lighter weight and easier to install, so it's probably a better default.

Possible drawbacks: breaking existing workflows that rely on wkhtmltopdf.

**Comment by jgm** [comment]
I must say that `pagedjs-cli` gives *much* better results.

`weasyprint` with pandoc manual:
```
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: Cannot load default config file: No such file: (null)
WARNING: Ignored `text-rendering: optimizeLegibility` at 15:7, unknown property.
WARNING: Expected a media type, got '(max-width: 600px)'
WARNING: Invalid media type ' (max-width: 600px) ' the whole @media rule was ignored at 18:5.
WARNING: Ignored `overflow-x: auto` at 112:7, unknown property.
WARNING: Ignored `gap: min(4vw, 1.5em)` at 149:32, invalid value.
WARNING: Ignored `overflow-x: auto` at 150:28, unknown property.
WARNING: Ignored `user-select: none` at 187:32, unknown property.
WARNING: Anchor defined twice: 'footnotes'
```
and then it looks like this:
<img width="635" alt="Screenshot 2024-09-02 at 9 23 16 AM" src="https://github.com/user-attachments/assets/78e6ec2f-86c3-41fd-a9a4-c0cc58753aad">

pagejs-cli:
```
✔ Loaded
✔ Rendering 146 pages took 2537.7000000178814 milliseconds.
✔ Generated
✔ Processed
✔ Saved to /Users/jgm/src/pandoc/toPdfViaTempFile61952-1.pdf
```
and it looks just like it looks in the browser:
<img width="830" alt="Screenshot 2024-09-02 at 9 24 06 AM" src="https://github.com/user-attachments/assets/d4d010fd-b3d9-4b3f-b2c6-593d1afd6cac">

**Comment by jgm** [comment]
Maybe I'd rather stay with wkhtmltopdf than default to weasyprint, which seems to ignore the font size...

**Comment by bpj** [comment]
The problem with staying with wkhtmltopdf is that package managers will eventually stop providing packages for it. WeasyPrint output may leave something to be desired if you have not-so low demands,[^1] but it is maintained, it is widely provided by package managers so relatively easy to install, it is relatively lightweight, and those who have higher demands can always use an alternative.
