### ISSUE TITLE
HTML reader should ignore everything outside of main element, if present

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#10140]
I can't think of too many occasions when you'd actually want to convert the HTML navigation menu, header, or footer to another format.

This would yield much cleaner conversions.

**Comment by jgm** [comment]
A less drastic change would be to have pandoc put `nav`, `main`, `header`, and `footer` in special divs with identifiable attributes, so they could be deleted selectively by filters.

**Comment by jgm** [comment]
@tarleb @mb21 curious about your thoughts on this.

**Comment by jgm** [comment]
Note the following tests in our HTML reader test suite:
```hs
          , test htmlNativeDivs "<main role=X> becomes <div role=X>" $ "<main role=foobar>hello</main>" =?>
            doc (divWith ("", [], [("role", "foobar")]) (plain (text "hello")))
          , test htmlNativeDivs "<main> has attributes preserved" $ "<main id=foo class=bar data-baz=qux>hello</main>" =?>
            doc (divWith ("foo", ["bar"], [("role", "main"), ("baz", "qux")]) (plain (text "hello")))
          , test htmlNativeDivs "<main> closes <p>" $ "<p>hello<main>main content</main>" =?>
            doc (para (text "hello") <> divWith ("", [], [("role", "main")]) (plain (text "main content")))
          , test htmlNativeDivs "<main> followed by text" $ "<main>main content</main>non-main content" =?>
            doc (divWith ("", [], [("role", "main")]) (plain (text "main content")) <> plain (text "non-main content"))
 ```
These would change.

**Comment by jgm** [comment]
Also, currently we parse `<head>` for metadata information. We wouldn't want to stop doing that.

**Comment by jgm** [comment]
We also pay attention to `lang` tags on containers, including `<body>`.

**Comment by jgm** [comment]
If we do this, I think the best implementation would be:

- put main in a div with a distinguished attribute
- after parsing, use `query` to extract this div if present, and only return its contents if so

**Comment by mb21** [comment]
Yes, I cannot readily think of anything speaking against the change. [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main):

> A document mustn't have more than one `<main>` element that doesn't have the `hidden` attribute specified.

I would assume that pretty much all websites adhere to that (but haven't checked).

**Comment by bpj** [comment]
_Mustn't_ is rather strong language, so they probably deserve what they get if they break that prohibition. At least you can tell users that when they complain...

**Comment by jgm** [comment]
It would be easy to code this in a way that would include content from any number of `main` elements (though there should only be one).  The issue is whether it would be bad to ignore things outside of a `main` element.  (Of course, with documents that don't have a `main` element, we'd just convert the whole thing.)

**Comment by tarleb** [comment]
+1 from me, too. I can't imagine any situation where that's *not* what people want.

**Comment by rafmartom** [comment]
I don't know why you introduce features that step out from the actual purpose of your tool.
I am pre-parsing .html with other tools but using `pandoc` for other kinds of parsing. This strange behaviour it is really making me introduce a bunch of unecessary code just as a exception for circumventing this unexpected behaviour of your program.
It may be my use case, but that is just my opinion. Stepping out of what the program should do just for a minor convenience is something that may cause unexpected behaviour in bigger systems.
Been your program an amazing peace of engineering, you should expect the users to be able to pre-parse any .html tags if they want to use them or not , or introduce a `pandoc-filter` . But hardcoding this is limiting your program capabilities for no reason, just expecting the user to get such a minor convenience.
