### ISSUE TITLE
docx deleted comments can fall outside deletion nodes

### ISSUE THREAD

**Issue by steinbro** [jgm/pandoc#10157]
[comment_deleted.docx](https://github.com/user-attachments/files/16899378/comment_deleted.docx) is a minimal Word document with tracked changes, where Word considers the comment as deleted (if you accept all changes, the comment disappears). However, the pandoc output does not reflect that the comment is deleted. This quirk may have been observed in #9833 but is a separate issue.

Inspecting the Word markup, the problem might be that the `commentRangeEnd` occurs inside a `del`, while the corresponding `commentRangeStart` is outside:
```
			<commentRangeStart w:id="1" />
			<del w:id="2" w:author="Daniel Steinbrook" w:date="2024-09-05T11:45:00Z" w16du:dateUtc="2024-09-05T15:45:00Z">
				<r w:rsidDel="008F2532">
					<delText>
						Here is a second bulet
					</delText>
				</r>
				<commentRangeEnd w:id="1" />
				<r w:rsidDel="008F2532">
					<rPr>
						<rStyle w:val="CommentReference" />
					</rPr>
					<commentReference w:id="1" />
				</r>
			</del>
```
The pandoc AST actually does mirror this structure:
```
[ BulletedList
    [ Para
        [ Span ("comment-start", ...) [ ... ]
        , Span ("deletion", ...)
            [  ...
            , Span ("comment-end", ...) [ ... ]
            ]
        ]
    ]
]
```
This arose as a problem because I am using a simple (Python) filter that attempts to remove deleted comments from a pandoc AST by removing `deletion` nodes and their children:
```
    if isinstance(elem, panflute.Span) and "deletion" in elem.classes:
        return []
```
But this fails to remove the above comment, because the comment text falls outside of the deletion node.

Is this something that should be fixed in pandoc? Or, alternatively, is there a better filter I should be using to identify this as a deleted comment, that would more closely match Word's semantics?

Using pandoc 3.3 on macOS Sonoma 14.6.1.

**Comment by jgm** [comment]
The comments and change-tracking features were all implemented by @jkr and I don't have detailed knowledge of them. But, looking at the XML in the docx, I see this structure (removing styles for clarity):
```xml
    <w:p>
      <w:commentRangeStart w:id="1"/>
      <w:del w:id="2" w:author="Daniel Steinbrook" w:date="2024-09-05T11:45:00Z" w16du:dateUtc="2024-09-05T15:45:00Z">
        <w:r w:rsidDel="008F2532">
          <w:delText>Here is a second bulet
          </w:delText>
        </w:r>
        <w:commentRangeEnd w:id="1"/>
        <w:r w:rsidDel="008F2532">
          <w:commentReference w:id="1"/>
        </w:r>
      </w:del>
    </w:p>
```

**Comment by jgm** [comment]
So, you can see that pandoc is accurately reflecting the bonkers structure found in the Word file, where the comment starts outside a deleted section and ends inside it.

Note also that pandoc stores the comment id:

```haskell
    , [ Para
          [ Span
              ( ""
              , [ "comment-start" ]
              , [ ( "id" , "1" )
                , ( "author" , "Daniel Steinbrook" )
                , ( "date" , "2024-09-05T11:44:00Z" )
                ]
              )
              [ Str "This"
              , Space
              , Str "comment"
              , Space
              , Str "is"
              , Space
              , Str "on"
              , Space
              , Str "the"
              , Space
              , Str "second"
              , Space
              , Str "bullet."
              ]
          , Span
              ( ""
              , [ "deletion" ]
              , [ ( "author" , "Daniel Steinbrook" )
                , ( "date" , "2024-09-05T11:45:00Z" )
                ]
              )
              [ Str "Here"
              , Space
              , Str "is"
              , Space
              , Str "a"
              , Space
              , Str "second"
              , Space
              , Str "bulet"
              , Span ( "" , [ "comment-end" ] , [ ( "id" , "1" ) ] ) []
              ]
          , Span
              ( ""
              , [ "paragraph-deletion" ]
              , [ ( "author" , "Daniel Steinbrook" )
                , ( "date" , "2024-09-05T11:45:00Z" )
                ]
              )
              []
          ]
      ]
```

So, I suppose your filter could:

- check to see if there are any comment start or comment end spans inside the deleted part
- if there are, then delete every other comment start/end with the same id in the document

**Comment by steinbro** [comment]
Thanks for the recommendation. I did some further experimentation ([another sample docx](https://github.com/user-attachments/files/16901624/comment_deleted_2.docx)), and the Word behavior is pretty counterintuitive:
1. If a comment starts outside a deletion but ends in a deletion, it will be deleted when changes are accepted.
2. If a comment starts in a deletion but ends outside a deletion, it is *not* deleted when changes are accepted.

To match this behavior, the filter would need to do the opposite of what it does now (delete comments that start in a deletion and preserve comments that don't). For each comment that starts in a deletion, it would need to determine if the comment also ends in the deletion. If it doesn't, it would need to return that comment so as to promote that comment outside of the deleted node. That sounds doable but complicated. Is there a simpler way?

At any rate, I suppose this isn't strictly a bug in pandoc. BTW, how do you get the pretty-printed Haskell-syntax document AST out of pandoc?

**Comment by jgm** [comment]
> BTW, how do you get the pretty-printed Haskell-syntax document AST out of pandoc?

`pandoc -t native`

Should we close this issue, then?
