### ISSUE TITLE
parsing issue with tex

### ISSUE THREAD

**Issue by ultronozm** [jgm/pandoc#10160]
To reproduce the issue, use pandoc (e.g., via https://pandoc.org/try/) to convert the following tex file to html:

```latex
\documentclass{article}

\begin{document}

\begin{equation}
  [0,1)
\end{equation}

\begin{table}[h]
\end{table}

\end{document}
```

This yields the error:

```
unexpected end of input
expecting \end{equation}
```

I've checked that the half open/closed paren/bracket as well as the "[h]" argument for the table environment are necessary (the error goes away if these features are omitted), but have not tried further variations.  A work-around is to use "\left[ ... \right)".

**Comment by jgm** [comment]
This is because we're trying to skip bracketed options -- which these environments shouldn't have.  Easy to fix.
