### ISSUE TITLE
Docx to latex conversion includes spurious symbols in \mathbb

### ISSUE THREAD

**Issue by nidrissi** [jgm/pandoc#10198]
When converting a docx file to latex, the equations containing "blackboard bold" characters will sometimes mess up the formatting. For example, here is a very simple docx file: [x.docx](https://github.com/user-attachments/files/17055581/x.docx) that only contains this equation:

![image](https://github.com/user-attachments/assets/edd0eb60-d568-42bc-87e3-6af144ebb3d8)

When converting to latex with `pandoc --from docx --to latex`, this produces:

    Let \(x\mathbb{\in N}.\)

The `\in` is included in `\mathbb`, which messes the spacing up. I've also seen it happen with arrows and other symbols.

I tried this on my desktop with pandoc 3.3, and on https://pandoc.org/try/ with pandoc 3.4. The issue appeared both times.

**Comment by jgm** [comment]
Here is the XML for the equation in x.docx:
```xml
      <m:oMath>
        <m:r>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:eastAsiaTheme="minorEastAsia" w:hAnsi="Cambria Math"/>
          </w:rPr>
          <m:t>x
          </m:t>
        </m:r>
        <m:r>
          <m:rPr>
            <m:scr m:val="double-struck"/>
          </m:rPr>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:eastAsiaTheme="minorEastAsia" w:hAnsi="Cambria Math"/>
          </w:rPr>
          <m:t>∈N
          </m:t>
        </m:r>
        <m:r>
          <w:rPr>
            <w:rFonts w:ascii="Cambria Math" w:eastAsiaTheme="minorEastAsia" w:hAnsi="Cambria Math"/>
          </w:rPr>
          <m:t>.
          </m:t>
        </m:r>
      </m:oMath>
 ```
You can see that both the ∈ and the N are inside a run styled "double struck."  So, sorry!  Pandoc is converting this correctly, given what is in the docx.

**Comment by jgm** [comment]
My guess is that Word doesn't have a double-struck glyph for epsilon, so it appears correct.
