### ISSUE TITLE
Is the code path inserting KaTeX loading scripts dead?

### ISSUE THREAD

**Issue by sgraf812** [jgm/pandoc#10209]
Apologies if this issue is too vague to act on. However, I was trying to coerce `hakyll` into calling out to `pandoc` in such a way that it formats math with KaTeX.

`hakyll` uses `writeHtml5String` to write out HTML (the call is [here](https://github.com/jaspervdj/hakyll/blob/c28f6002f03e8e2dbc2a37642639c47cd596701d/lib/Hakyll/Web/Pandoc.hs#L89)), and I tried to set `writerHTMLMathMethod = KaTeX defaultKaTeXURL` so that it would load KaTeX on my blog.
However, it does not seem to actually write out the necessary HTML. I was hoping that this code path here would do it:

https://github.com/jgm/pandoc/blob/f3fff87b2c5987c360bab425f5a7187cfb8342d9/src/Text/Pandoc/Writers/HTML.hs#L316-L353

But as far as I can tell, no such scripts end up in the generated HTML. Note that the code probably sets the `math` field, but I wasn't able to figure out whether or how that field influences the HTML body returned by `writeHtml5String`. 

I would appreciate if someone could give this a quick look, perhaps answering "Nah, the code path is not dead; you are just using the API wrong". 

If you want, I could also try and invest time in a standalone reproducer.

**Comment by jgm** [comment]
In the default template you'll find a `$math$` variable. The content gets put there. If you are using a template without `$math$`, it won't appear.

**Comment by sgraf812** [comment]
Alright, thanks! It's a bit awkward to access this variable without specifying a template, but that's life.

I'll just keep pasting the content of `$math$` manually as described here: https://github.com/jaspervdj/hakyll/issues/1006
