### ISSUE TITLE
docx-custom-reference made as a 2007 

### ISSUE THREAD

**Issue by awelormro** [jgm/pandoc#10218]
When I run the default command `pandoc -o custom-reference.docx --print-default-data-file reference.docx` to create a custom docx reference, it produces a pandoc 2007 version, I can see that because when I open it in Libreoffice it gives me the option to save it as a newer office version or ODT. Is this an error during my installation, download or similar?

**Pandoc version?**
What version of pandoc are you using, on what OS? (If it's not the latest release, please try with the latest release before reporting the issue.)

Pandoc 3.4 via binary running on Arch Linux

**Comment by jgm** [comment]
I assume you're seeing this?
<img width="571" alt="image" src="https://github.com/user-attachments/assets/a1fcaa6c-bcc2-4017-a99b-e1c3a6423f99">

That's just offering to save the document in LibreOffice's own format rather than as docx.  You don't want that if you want to use this to produce docx.
