### ISSUE TITLE
Raw html blocks being stripped from markdown starting with Pandoc 3.2

### ISSUE THREAD

**Issue by gtritchie** [jgm/pandoc#10213]
**Explain the problem.**

Pandoc removes raw html blocks (`{=html}`) from markdown starting with v3.2. Wondering if this was an intentional change / side-effect of https://github.com/jgm/pandoc/issues/9677?

## Previous behaviour (pandoc 3.1.11 used in this test)

````bash
$ pandoc -f markdown -t markdown
```{=html}
Hello <i>World</i>.
```
^D
```{=html}
Hello <i>World</i>.
```
````
The raw html block was preserved.

## Current behaviour (pandoc 3.4)

````bash
$ pandoc -f markdown -t markdown
```{=html}
Hello <i>World</i>.
```
^D
Hello <i>World</i>.
````
The raw html block was removed, leaving the bare html.

## Workaround

Using `-raw_html` on output seems to fix this particular quirk, but will have other side effects if the markdown contains actual raw HTML (i.e. not wrapped in the raw block).

````bash
$ pandoc -f markdown -t markdown-raw_html
```{=html}
Hello <i>World</i>.
```
Some <b>inline</b>HTML.
^D
```{=html}
Hello <i>World</i>.
```
Some `<b>`{=html}inline`</b>`{=html}html.
````

**Pandoc version?**
Change started with 3.2.

**Comment by jgm** [comment]
From the changelog for 3.2:

> Markdown writer:
> Don’t use raw_attribute syntax for raw blocks, unless there is no other option (see [#9677](https://github.com/jgm/pandoc/issues/9677)). Macros in a raw_attribute block don’t get interpreted when it is read again by pandoc’s markdown reader.

So yes, intentional.

Disabling `raw_html` (and keeping `raw_attribute` enabled as it is by default) will cause all raw HTML to be rendered using a raw attribute, as you've seen.

Note: in the pandoc AST, there is *no difference* between a raw block specified using the raw attribute and one that is just bare HTML, so we can't preserve this distinction in the source when writing markdown.

I think this can be closed?

**Comment by gtritchie** [comment]
>  in the pandoc AST, there is no difference between a raw block specified using the raw attribute and one that is just bare HTML

Ah, ok. Makes sense.

> I think this can be closed?

Yup, I'll close. I just wanted to capture this to check that it was intentional and in case anyone else bumps into it.

Thanks for quick response!
