### ISSUE TITLE
Parsing error on argument to LaTeX \vskip

### ISSUE THREAD

**Issue by logological** [jgm/pandoc#10212]
Pandoc's LaTeX parser doesn't seem to understand `\vskip`.  It chokes as soon as it gets to the length argument, regardless whether it's positive or negative, bare or surrounded by braces.  Here's a minimal example:

```
\documentclass{article}
\begin{document}
\vskip-1.5em foo
\end{document}
```

And here's the command-line output:

```
$ pandoc --to=docx test.tex > test.docx
Error at "test.tex" (line 3, column 7):
unexpected -
\vskip-1.5em foo
      ^
```

Again, line 3 could have been written as `\vskip1.5em`, `\vskip{-1.5em}`, etc.; Pandoc will emit a similar error regardless.

The problem occurs with Pandoc 3.4 (using [try pandoc](https://pandoc.org/try)) and with Pandoc 3.3 on openSUSE Tumbleweed.

**Comment by jgm** [comment]
Looks like we are just missing `em` as a possible unit for dimension arguments -- as well as `ex` and `px`!
