### ISSUE TITLE
Misleading "YAML parse exception"

### ISSUE THREAD

**Issue by adamjrice** [jgm/pandoc#10231]
**Explain the problem.**
I have a markdown doc that I want to convert to a Reveal.js presentation.

I set it up with a minimal YAML block at the top, so the first dozen or so lines of the document look like this:

```` markdown
% My awesome presentation
% Adam Rice

# My awesome presentation

::: notes

Some notes

:::

---
## Let's get into it
````

Here's the error I was getting:

```
YAML parse exception at line 3, column 2,
while scanning a block scalar:
did not find expected comment or line break
```

After some trial and error, I discovered that the real parsing problem is on the penultimate line above: the `---` is not separated from the `## Let's get into it` line by a blank line.

**Pandoc version?**
3.4, on MacOS

**Comment by jgm** [comment]
Pandoc is not an AI.  The last two lines of your document are the beginning of a valid YAML metadata section (which can occur anywhere in the document).  Pandoc assumes that's what you're going for and warns you accordingly.

**Comment by adamjrice** [comment]
Got it, thanks. I had been under the misimpression that YAML sections had to be at the top.

**Comment by olberger** [comment]
For those who'd stumble on this issue, but without a clear understanding of what the issue was, here's a reference doc explaining the `---| separator: https://pandoc.org/MANUAL.html#extension-yaml_metadata_block

Hth,

**Comment by peterkaminski** [comment]
Thank you, @olberger - I stumbled upon this issue 19 hours after your post! I'm using pandoc 3.6.1 on macOS.

Here's the relevant paragraph from the doc you referenced:

> A YAML metadata block is a valid YAML object, delimited by a line of three hyphens (---) at the top and a line of three hyphens (---) or three dots (...) at the bottom. The initial line --- must not be followed by a blank line. A YAML metadata block may occur anywhere in the document, but if it is not at the beginning, it must be preceded by a blank line.

My error was similar to but slightly different from the one received by [adamjrice](https://github.com/adamjrice). My error was:

> YAML parse exception at line 3, column 1,
> while scanning an alias:
> did not find expected alphabetic or numeric character

A somewhat confusing thing is that pandoc says the exception is at line 3, whereas the actual `---` line was at line 79 in the input.

In my code, I have to handle arbitrary incoming Markdown, so workarounds I'm considering include:

- if there's a line with three hyphens and no blank line after it, add a blank line after it (it's good practice to separate different block types with blank lines anyway)
- convert a line with three hyphens to asterisks or underscores (valid representations for <hr>)
- convert a line with three hyphens to four hyphens (Markdown doesn't care if there are more than three hyphens)

Each of these would break the YAML metadata block syntax that pandoc is looking for.

**Comment by adamjrice** [comment]
@peterkaminski those all sound like good practices for avoiding the `---` conflict.

**Comment by jgm** [comment]
I've added some information to localize the error, e.g.
```
Error parsing YAML metadata at (line 4, column 1):
YAML parse exception at line 1, column 9:
mapping values are not allowed in this context
```
Still a tiny bit confusing; you have to realize that the line 1, column 9 refers to the contents of the YAML section; but I think most people will get it.  (In principle this could be improved but it would require a bit of tedious unpacking of types; this is what I could do quickly.)

**Comment by olberger** [comment]
How about making it clear that there's probably a misunderstanding on the usage of a separator as a horizontal line vs a YAML metadata header, as an additional hint for regular humans ?

**Comment by kesarams1** [comment]
@adamjrice Thank you for saving my time and report, that helped me to understand where the problem is!

**Comment by amitr526** [comment]
Turns out I my ADO markdown with diagrams were too exotic for pandoc, so I have solved this by running presteps like this:   

```
git ls-files "*.md" | xargs prettier --config .prettierrc --write
git ls-files "*.md" | xargs markdownlint-cli2 --config .markdownlint-cli2.jsonc --fix
```
## .prettierc
```
{
  "proseWrap": "always",
  "printWidth": 80
}
```

## .markdownlint-cli2.jsonc
``` 
{
  "globs": ["**/*.md"],

  "ignores": [
    "node_modules/**",
    "dist/**",
    "build/**",
    "**/*.generated.md"
  ],

  "config": {
    "default": true,

    // Prettier handles wrapping
    "MD013": false,

    // Architecture docs often have multiple sections
    "MD025": false,

    // Allow anchors or comments before headings
    "MD041": false,

    // Allow HTML for anchors, details, diagrams
    "MD033": false,

    // Allow direct URLs
    "MD034": false,

    // Often used for quick section headers
    "MD036": false,

    // Mixed heading styles common in imported docs
    "MD003": false,

    // Diagrams often break list spacing rules
    "MD032": false
  }
}
```
