### ISSUE TITLE
`test/docx/normalize.docx` contains invalid xml

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#10242]
**Explain the problem.**

https://github.com/jgm/pandoc/blob/main/test/docx/normalize.docx contains invalid XML.

**How fix**

Replace `<w:i/ >` with `<w:i/>` in `word/document.xml`.

**Pandoc version?**

N/A

**Comment by StephanMeijer** [comment]
@jgm Can you please instruct me how to zip back a `.docx` after unzipping? My prior method stopped working :)

**Comment by jgm** [comment]
I just use zip.  You just need to be careful about the directories.

For example:
```
% unzip -d my my.docx
% cd my
% # change stuff
% zip -r ../my.docx *
```

Actually, nowadays I just open the docx with emacs and edit it there; this handles all the zipping/unzipping behind the scenes.

**Comment by jgm** [comment]
Make sure you haven't introduced any new files inside the directory?

**Comment by jgm** [comment]
sorry, typo in that commit.
