### ISSUE TITLE
Pandoc Sandbox and Embedded Data URIs for Images

### ISSUE THREAD

**Issue by cmason3** [jgm/pandoc#10249]
I am currently using Pandoc 3.4 to convert from HTML to DocX. Within the HTML document I am using Data URIs to embed images within my HTML, but these aren't appearing within the converted DocX. I realised I needed to include the `--standalone` and `--embed-resources` options, but it still wasn't working and this was because I am using the Sandbox and I was getting the following error:

```
[WARNING] Could not fetch resource data:image/png;base64,iVBORw0KGgoAAAAN...
```

Is there anyway to tell the Sandbox to allow embedded Data URIs? I understand the need to limit fetching random external URLs and this would require Network I/O, but how come an embedded Data URI triggers the Sandbox unless it is actually written to disk between the different conversion stages?

**Comment by jgm** [comment]
Thanks for the suggestion.
