### ISSUE TITLE
Make `beamerarticle` easier to use

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#10250]
I was able to get `beamerarticle` to work by:

- specifying the `beamer` writer
- specifying the `beamerarticle` variable
- forcing the documentclass to `article`
- forcing the template to the default latex template (since otherwise we get things like `setbeamertemplate` that aren't defined)

This needs, at least, better documentation (see #7874), and probably something should be done to make these things happen automatically.

```
pandoc test/s5.native -Vbeamerarticle -Vdocumentclass=article -o s5.pdf -t beamer --template data/templates/default.latex
```

 _Originally posted by @jgm in [2a6268d](https://github.com/jgm/pandoc/commit/2a6268de67b883cd814358111d764d330f100d9b#commitcomment-147441535)_

Beamer manual says:

"The article mode of a presentation is created by specifying article or book or some other class as the document class instead of beamer and by then loading the package beamerarticle.
The package beamerarticle defines virtually all of beamer’s commands in a way that is sensible for the article mode. Also, overlay specifications can be given to commands like \textbf or \item once beamerarticle has been loaded. Note that, except for \item, these overlay specifications also work: by writing \section{Name} you will suppress this section command in the article version. For the exact effects overlay specifications have in article mode, please see the descriptions of the commands to which you wish to apply them."

So, when you use beamerarticle (a) the documentclass should be article, not beamer, and (b) you should still have the code emitted by the beamer writer, e.g. \begin{frame}....

**Comment by samcarter** [comment]
Is `beamerarticle` really use full with pandoc? The main use-case of using it in latex is that the user can leave in all the beamer-code (e.g. `\begin{frame}`) and still be able to compile the document body with another class. 

... but if pandoc is used with another class, it wouldn't produce anything beamer specific for which one would need the beamerarticle package, would it?

**Comment by jgm** [comment]
@samcarter good point.
This was added in cde1f008134c854e241e3ff9c4d352a84e64356e
in response to a request from @cagix -- maybe @cagix can comment ?
