### ISSUE TITLE
Table overlaps footer with page number

### ISSUE THREAD

**Issue by tneunhoeffer** [jgm/pandoc#1026]
When I create a PDF document with Pandoc 1.12.0.2 together with miktex 2.8, it might happen that a table does not switch to the next page but overlaps the footer area and the page number. Attached, you find an example picture, the markdown source, the used latex template and the command line settings used for Pandoc.

Are there any settings to avoid such situations?

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Markdown source:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Ein paar Formatierungsbeispiele - Hauptueberschrift
==================================================

Unterkapitel - Level 2
----------------------

#### Unterkapitel - Level 4

Ein neuer Absatz

wird mit einer Leerzeile eingeleitet.

> Ein eingerueckter Absatz
> mit einem Groeßer-Zeichen (">")
  
> > Ein noch weiter eingerueckter Absatz mit
> >   zwei Groesser-Zeichen ("> >")
	
So schreibt man __fett__ und _kursiv_, hoch^gestellt^ und tief~gestellt~.

Eine Liste mit \* vor jedem Item

*   eins
*   zwei
    *   Sub-listen, vier Zeichen eingerueckt
	*   Den Text daher auch am besten 4, 8 bzw. 12 Zeichen einruecken
	
	    Ein weiterer Absatz zu obigem Absatz
		analog eingerueckt
	
	*   Noch ein Level 2 Item
*   drei

1.  Nummerierte Listen
1.  mit Ziffern
    1.  Ebenso
	1.  staffelbar
	    *   und mit einer
		*   unummerierten Liste kombiniert
1.	Noch ein Hauptpunkt

	
Und wieder normal weiter

### Tabellen

Linksbundig       Rechtsbundig     zentriert
------------     -------------    -----------
abhaengig        davon            ob
Strichlinie      rechts           links
oder auf         beiden           Seiten
ueber die        Ueberschrift     hinausgeht
usw              usf

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
The latex template
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

\documentclass[$if(fontsize)$$fontsize$,$endif$$if(lang)$$lang$,$endif$$if(papersize)$$papersize$,$endif$]{$documentclass$}

$if(tables)$
\usepackage{longtable}
$endif$

\begin{document}
$body$
\end{document}

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
A bat script to create the PDF
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

@echo off

if "%1"=="" GOTO USAGE
if "%2"=="" GOTO USAGE

set PDFLATEX=W:\tools\Dokumentation\miktex\2.8\miktex\bin\pdflatex.exe

call pandoc.exe ^
	--variable=documentclass:scrartcl ^
	--variable=fontsize:12pt ^
	--variable=geometry:paper=a4paper,left=3cm,right=2cm,top=2.5cm,bottom=2.5cm ^
	--template template.latex ^
	--latex-engine %PDFLATEX% ^
	-o %2 ^
	%1
	
if %ERRORLEVEL%==0 echo "%1" successfully converted to "%2"
if ERRORLEVEL 1 echo ERROR in converting "%1"
GOTO END
	
:USAGE
echo.
echo USAGE: %0 markdown-file pdf-file
echo.
echo Converts the "markdown-file" to "pdf-file"
:END

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
![pagenumberintable](https://f.cloud.github.com/assets/5717744/1361729/2ae44a82-380c-11e3-8541-a677496cd801.png)

**Comment by jgm** [comment]
See #2889 - this seems to be a longtable bug, there's a fix at the link given in that issue.
