### ISSUE TITLE
When generating html from md with --embed-resources --standalone, CSS styles from --css are not included correctly when loading from remote url, works fine with local file

### ISSUE THREAD

**Issue by Rudokhvist** [jgm/pandoc#10261]
**Explain the problem.**
I'm trying to generate --standalone --embed-resources .html from .md with custom style specified with --css. It works fine when I use css from a file on local filesystem, but don't work  when I specify a https url to the very same file.

**Steps to reproduce**
- Download archive with sample files:
[MRE.zip](https://github.com/user-attachments/files/17266679/MRE.zip)
- make shell script example.sh executable and run it. It will generate two html files, with css loaded from remote url (result1.html) and with css from local file (downloaded fro the same remote url) (result2.html). 
- You can now compare those files, and see that result1.html don't show any of the embedded styles.

**Pandoc version?**
I'm using latest stable version of pandoc, 3.4, on Windows 10. I also tried latest nightly build with same result.

**Misc**
This issue may be connected to https://github.com/jgm/pandoc/issues/7635, https://github.com/jgm/pandoc/issues/7367 and https://github.com/jgm/pandoc/issues/3423, but only affects remote urls and results are more dramatic, causing styles to not affect resulting document.

**Comment by jgm** [comment]
So with the remote --css, we get a `<link href="data:text/plain...>` with the contents of the CSS file encoded, while with local --css, we get a proper `<style>` tag.

**Comment by jgm** [comment]
Ah I see, it's because it is being served with a `text/plain` mime type, not `text/css`.

**Comment by jgm** [comment]
I will add an alternative check for rel="stylesheet".

**Comment by Rudokhvist** [comment]
Thank you for the fast fix! I will check it when Nightly will build.

**Comment by Rudokhvist** [comment]
Tested with artifact from https://github.com/jgm/pandoc/actions/runs/11195907421, works like a charm, thank you again!
