### ISSUE TITLE
Error `Undefined control sequence` when converting markdown to PDF

### ISSUE THREAD

**Issue by yilas** [jgm/pandoc#10277]
Hello 👋🏻 

ℹ️  I have just opened an issue to [mermaid-filter](https://github.com/raghur/mermaid-filter) (issue [134](https://github.com/raghur/mermaid-filter/issues/134)) but it might actually be a `pandoc` issue rather than a `mermaid-filter` one. Just in case, I'm posting the same issue here as well.

## The issue

When trying to convert a markdown file with Mermaid content to PDF using the `mermaid-filter` project, I encountered the following error :
```
Error producing PDF.
! Undefined control sequence.
<argument> „den éischte Kontakt'' (\(\color 
                                               {red}{\textsf {formell}}\))
l.64 ...uxe9ischte-kontakt-colorredtextsfformell}}
```

It seems that the problem is related to the following part of the markdown file :
```
($\color{red}{\textsf{formell}}$)
```
When I remove that section, the PDF is generated correctly.

## Example of problematic file
Here is the markdown file that produces the error (`test.md`) :

```markdown
# Dialog

## „den éischte Kontakt” ($\color{red}{\textsf{formell}}$)
```

And here is a modified version that works (`test_ok.md`) :

```markdown
# Dialog

## „den éischte Kontakt”
```

### Step to reproduce

1. Create a markdown file (test.md)
1. Run the following command
    ```bash
    pandoc -F mermaid-filter -o output.pdf test.md
    ```
1. Observe the error

    ```bash
    Error producing PDF.
    ! Undefined control sequence.
    <argument> „den éischte Kontakt'' (\(\color 
                                                   {red}{\textsf {formell}}\))
    l.64 ...uxe9ischte-kontakt-colorredtextsfformell}}
    ```

### Environnement
* Operating system
```bash
cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
```

* Pandoc version
```bash
$ pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/codespace/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

* mermaid-filter version
```bash
$ npm view mermaid-filter version
1.4.7
```

### Expected behavior
The file should be converted to PDF without errors.

**Comment by bpj** [comment]
You need to have the math inside the argument to the `\color` command, not the other way around. Note that the `$math$` syntax can't be used for arbitrary raw LaTeX commands; I suspect you want the raw markup syntax: see my answer to #10278.
