### ISSUE TITLE
Error parsing reStructuredText hyperlink inside directive

### ISSUE THREAD

**Issue by cmorve-te** [jgm/pandoc#10281]
The indented hyperlink reference in https://github.com/llvm/llvm-project/blob/36a0d442eb4d2f1e0782bc2a1b1715fc7631faec/clang-tools-extra/docs/clang-tidy/checks/modernize/pass-by-value.rst?plain=1#L153, inside a "seealso" directive, is not corrected parsed by pandoc 3.5

```
# /pandoc-3.5/bin/pandoc /pass-by-value.rst -f rst -t html5 > /pass-by-value_pandoc.html
[WARNING] Reference not found for 'want speed? pass by value' at /pass-by-value.rst_chunk line 3 column 87
```

if the document is changed to remove the spaces before the `..`, it works correctly
```
-  .. _Want Speed? Pass by Value: https://web.archive.org/web/20140205194657/http://cpp-next.com/archive/2009/08/want-speed-pass-by-value/
+.. _Want Speed? Pass by Value: https://web.archive.org/web/20140205194657/http://cpp-next.com/archive/2009/08/want-speed-pass-by-value/
```

"seealso" is a sphinx directive, but if replaced with "note" rst2html parses everything correctly (without a need to remove the spaces before the `..`):
```
$ rst2html pass-by-value.rst > pass-by-value.html
$ grep -F 'Want Speed? Pass by Value' pass-by-value.html 
<p class="last">For more information about the pass-by-value idiom, read: <a class="reference external" href="https://web.archive.org/web/20140205194657/http://cpp-next.com/archive/2009/08/want-speed-pass-by-value/">Want Speed? Pass by Value</a>.</p>
```

**Comment by jgm** [comment]
Question:  is this definition scoped to the indented context?
Or can you link to `` `Want Speed? Pass by Value`_. `` elsewhere in the document?

**Comment by cmorve-te** [comment]
According to rst2html they are not scoped:
- You can link from elsewhere
- If you add another definition with the same name in global scope, or even inside another directive, it errors complaining about the duplicate
