### ISSUE TITLE
TOML support for front matter

### ISSUE THREAD

**Issue by chicks-net** [jgm/pandoc#10295]
**Describe your proposed improvement and the problem it solves.**

Hugo supports TOML for [front matter](https://gohugo.io/content-management/front-matter/).  It would be nice if pandoc could also process these files.  This came up in https://github.com/Zettlr/Zettlr/discussions/5288#discussioncomment-10926154 so I thought I'd start a conversation over here.  I understand that pandoc does support YAML front matter from #851.

**Describe alternatives you've considered.**

I could switch my site over to YAML front matter, but TOML is much more human-friendly imho and I'm happy to stick with it for projects i control. I don't need pandoc to process it in the near term.  I can keep doing what I'm doing with hugo for the plannable future.  But pandoc is used by many other projects (such as Zettlr mentioned above) and it would be nice to have it be more compatible with hugo sites so that the same content could be used without reprocessing by both communities.

**Comment by tarleb** [comment]
Thanks for the report. This has been discussed in #2425, see there for a workaround.
