### ISSUE TITLE
typst 0.12 two column layout changes

### ISSUE THREAD

**Issue by jarnowic** [jgm/pandoc#10294]
See https://github.com/typst/typst/issues/5215 for background.

I'm about to propose two pulls to fix the issue, but I don't know if that may be premature; in any event, an expert's opinion is surely welcome.

**Comment by jgm** [comment]
My question would just be whether `#set page(columns: 2)` works only on typst 0.12 or also on earlier versions.  Currently 0.11 is our official target...I haven't even looked at the 0.12 changelog yet.

**Comment by jarnowic** [comment]
> My question would just be whether `#set page(columns: 2)` works only on typst 0.12 or also on earlier versions. Currently 0.11 is our official target...I haven't even looked at the 0.12 changelog yet.

let me check...

**Comment by jarnowic** [comment]
> > My question would just be whether `#set page(columns: 2)` works only on typst 0.12 or also on earlier versions. Currently 0.11 is our official target...I haven't even looked at the 0.12 changelog yet.
> 
> let me check...

Update: one parameter (`scope`) of the `place` function is not yet properly documented, and it does not work in typst 0.11; therefore, it is better not merging any change until 0.12 becomes stable (it's still rc 2).

I'll be doing tests in the 0.12.rc series and keep on reporting.

Cheers!

**Comment by jarnowic** [comment]
I have confirmation (in the original thread) that this 

> > > My question would just be whether `#set page(columns: 2)` works only on typst 0.12 or also on earlier versions. Currently 0.11 is our official target...I haven't even looked at the 0.12 changelog yet.
> > 
> > 
> > let me check...
> 
> Update: one parameter (`scope`) of the `place` function is not yet properly documented, and it does not work in typst 0.11; therefore, it is better not merging any change until 0.12 becomes stable (it's still rc 2).
> 
> I'll be doing tests in the 0.12.rc series and keep on reporting.
> 
> Cheers!

I have confirmation (in the typst thread) that this change is upcoming with 0.12; so there is no need to make any change on the pandoc code thus far.

**Comment by jarnowic** [comment]
Typsty 0.12 was released today. I am updating my patches for the templates to accomodate to the new layout commands, awaiting for release for upcoming Pandoc 3.5 series.
