### ISSUE TITLE
Typst + Citeproc typographic bug due to citeproc wrapping lines

### ISSUE THREAD

**Issue by thjbdvlt** [jgm/pandoc#10293]
Hello! I am using Pandoc with Typst as the `--pdf-engine` and I use `--citeproc` because i prefer to manage my bibliography in JSON.
I encounter a bug when i use citeproc and set margins in my Typst template. I have a bibliography entry that look like this in the output:

![20241015-223909](https://github.com/user-attachments/assets/2d75864b-c1a6-48aa-ba08-783df6248168)

The problem seems to be the line wrapping done by citeproc/pandoc, because if I set `-o` to `out.typ`, here is what i get for the entry:

```typst
] <ref-burger2002>
#block[
#smallcaps[Burger];, Rodolphe, #smallcaps[Cadiot];, Olivier,
#emph[Welche. On est pas des indiens c’est dommage];, Dernière Bande,
1999.

] <ref-burger1999>
#block[
#smallcaps[Cadiot];, Olivier, #emph[L’Art poétic’];, Paris, P.O.L, 1988.
```

The `1999.` part must not be on a new line. If I remove this linebreak and then recompile this `.typ` file with `typst compile`, the problem disappear. So I think the problem comes from citeproc/pandoc managing linebreaks. Here is the expected `.typ` output:

```typst
] <ref-burger2002>
#block[
#smallcaps[Burger];, Rodolphe, #smallcaps[Cadiot];, Olivier,
#emph[Welche. On est pas des indiens c’est dommage];, Dernière Bande, 1999.

] <ref-burger1999>
#block[
#smallcaps[Cadiot];, Olivier, #emph[L’Art poétic’];, Paris, P.O.L, 1988.
```

**Comment by jgm** [comment]
You can use `--wrap=none` or `--wrap=preserve` to avoid this.
But perhaps we can make the typst writer smarter about wrapping things that might start lists.

**Comment by thjbdvlt** [comment]
Thank's! And sorry that i did not find this by myself! I mark this as a close issue, because it's not an issue at all.
