### ISSUE TITLE
citeproc and docx output: Number the items in the bibliography

### ISSUE THREAD

**Issue by terris-peer** [jgm/pandoc#10326]
**Describe your proposed improvement and the problem it solves.**

I would like the items in the bibliography created by citeproc to be numbered. 

The programmer who works on this issue can pick the solution they like better or choose a new one:
1. citeproc numbers them
2. citeproc adds a Word style to each item. The style can be customized by providing a reference doc.

**Describe alternatives you've considered.**

Open the docx file and number the bibliography items manually.

**Comment by njbart** [comment]
What about trying one of the 5000+ [numeric CSL styles](https://www.zotero.org/styles/?format=numeric)?

**Comment by jgm** [comment]
You could create a Lua filter that puts the bibliography entries into an ordered list.
