### ISSUE TITLE
pandoc-citeproc rejects BibTex file that worked in the past

### ISSUE THREAD

**Issue by dtjohnso** [jgm/pandoc#1034]
I have three BibTex files that I regularly use for my citations in my writing. Since the 1.12 upgrade, pandoc fails when I include my file logos-resources.bib [available here](https://gist.github.com/dtjohnso/7103731)

For example, when I run this:

   pandoc --smart -o 00-MarkdownOutput.html 07-America-18th-century-part 2.markdown --bibliography C:\Users\Duncan\Dropbox\logos-resources.bib

I get this error message whenever my input file includes a citation.

```
pandoc-citeproc: "stdin" (line 39, column 5):
unexpected "b"
expecting "c", "C", "p", "P", "s" or "S"
pandoc: Error running filter pandoc-citeproc
[Finished in 0.1s with exit code 83]
```

My other BibTex files don't cause any issues, and logos-resources.bib used to work in the past.

Any idea why this file generates this error? Is my source file invalid, or is this a pandoc-citeproc bug?

Thanks!

**Comment by dspinellis** [comment]
I got the same error message with a title containing `\&`. I fixed it by changing it into `and`.
