### ISSUE TITLE
Inconsistent vertical spacing/distance between pdfengines

### ISSUE THREAD

**Issue by Disonantemus** [jgm/pandoc#10371]
**Explain the problem.**

Testing 3 popular **pdfengines** supported by _pandoc_, I did notice, that there are big differences between how is managed the vertical space (distance), specially between title and next text, this is specially awful in _typst_. Maybe is related to templates.

Image made from screenshots of the PDFs generated by _pandoc_ made at fullscreen in _zathura_ (width mode), joined in gimp.

![pdfengines compared](https://i.ibb.co/f0PLpt2/pandoc-pdfengines.png)

From the image:

- _pdflatex_ has the **same** vertical space between title and different kind of texts (regular text, list, comments).
- _typst & pdfroff_ both has a **longer** vertical space between title and comment, near double or more than regular distance.
- _typst_ has **very small** vertical space between title and any text, a lot smaller than _pdflatex & pdfroff;_ this seems to me unnatural and forces to edit md file and use an `&nbsp;` bellow every title. This is clear because both pdflatex and typst has almost same font size, but distances are very different.

Commands to create PDFs:

~~~ocaml
$ pandoc a.md --pdf-engine pdflatex -o pdflatex.pdf
$ pandoc a.md --pdf-engine typst -o typst.pdf
$ pandoc a.md --pdf-engine pdfroff -o pdfroff.pdf
~~~

Sample file:

~~~ocaml
$ cat a.md
# Title

regular text

# Title

1. list item
1. list item

# Title

> comment
~~~

**Pandoc version?**
Latest release
~~~ocaml
$ pandoc --version | head -3
pandoc 3.5
Features: +server +lua
Scripting engine: Lua 5.4

$ pdflatex --version | head -2
pdfTeX 3.141592653-2.6-1.40.26 (TeX Live 2024/Arch Linux)
kpathsea version 6.4.0

$ typst --version
typst 0.12.0 (737895d7)

$ groff --version | head -1
GNU groff version 1.23.0
~~~

---

~~~ocmal
distro: Arch Linux x86_64
kernel: 6.6.52-1-lts
shell: bash 5.2.37
term: tmux
~~~

**Comment by jgm** [comment]
I don't consider this a bug, really.  Pandoc tries to produce fairly idiomatic output in these formats, and these pdf engines produce different output.  (If you want *really* different output, try `weasyprint`!)  It's not a goal of the project for these to look the same.

**Comment by Disonantemus** [comment]
Not the same, it's obvious that different _pdfengines_ use different fonts and sizes, but it seems clear to me, that **typst** has an _unusual small distance_ between Title and regular text (or List).

There's something that I can _change_ in templates or somewhere else to adjust that?

For **pdflatex** it's ok this:
~~~ocaml
# Title

regular text
~~~

But in **typst** I need to add a "\\" to have something similar:

~~~ocaml
# Title
\
regular text
~~~

I really love **typst**, because is 100x smaller I got almost the same quality as **pdflatex**, I also like **groff**, but is a little bit rough.

**Comment by iandol** [comment]
> There's something that I can _change_ in templates or somewhere else to adjust that?

Yes, you can fully edit the Typst template to your hearts desire. Export default.typst and then add the Typst set and show rules to tweak your layout -- or use Pandoc's `header-includes` to inject code from metadata into the template without needing to edit it. You can use the online editor to play in realtime with the layout:

https://typst.app/project/rMRTsaf85SDvafLW1wZlQA

**Comment by alerque** [comment]
> I don't consider this a bug, really. Pandoc tries to produce fairly idiomatic output in these formats, and these pdf engines produce different output. (If you want _really_ different output, try `weasyprint`!) It's not a goal of the project for these to look the same.

I fully agree here, Pandoc **should NOT** try to normalize the look of the output across different formats, even where drastic differences exist in the default choices of various typesetting engines. The default output should be as generic idiomatic semantic content as the target format allows for.

Of course each user and project is welcome to build on that and include style choices for specific output formats in the conversion process, but the *default* should be to let the typesetter use its defaults.

**Comment by alerque** [comment]
I happened to be working no something else and wanted to compare some default spacing choices between PDF engines. Here is the Pandoc manual rendered with a few different engines on the same papersize at the same zoom level with straight engine defaults:

![image](https://github.com/user-attachments/assets/d6a0e41e-63a3-46e7-9430-0eaa65b7b211)

The SILE engine on the top left is not merged to Pandoc yet but maintained in my fork (see #6088). Otherwise this is straight defaults from Pandoc 3.5 and out of the box settings for each engine. Generated with:

```zsh
for engine in sile typst lualatex xelatex weasyprint pdfroff; do
	pandoc --print-default-data-file=MANUAL.txt |
		pandoc -V papersize:a4 -t pdf --pdf-engine=$engine -o MANUAL-$engine.pdf
done
```
