### ISSUE TITLE
Plus signs are not properly escaped in AsciiDoc

### ISSUE THREAD

**Issue by gavinwahl** [jgm/pandoc#10385]
Pairs of  plus signs are used to indicate an ["Inline Passthrough"](https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/) in asciidoc.

```
$ pandoc --version
pandoc 3.1.3
$ echo 'I use [Notedpad++](http://example.com/) to write C++' | pandoc -f markdown -t asciidoc
````
Current output:
```
I use http://example.com/[Notedpad++] to write C++
````

Correct output:
```
I use http://example.com/[Notedpad{plus}{plus}] to write C{plus}{plus}
````
Here is how asciidoc renders the current incorrect output:
![image](https://github.com/user-attachments/assets/b5d5f234-730c-4a9f-b9f6-276e39c0327d)

Here is how it should look:

![image](https://github.com/user-attachments/assets/925abd98-03c5-4f61-bfca-19e89920bd71)

(renderings done with the editor at https://asciidoc.org/)

As far as I can tell the escaping needs to be done for Text and [inline] Code AST nodes. CodeBlock must not be escaped.

I tried to write a lua filter to do this:
```

function Str (str)
  str.text = str.text:gsub('+', '{plus}')
  return str
end

-- this is an inline code. Standalone code blocks don't need escaping
function Code (code)
  code.text = code.text:gsub('+', '{plus}')
  return code
end
````

However, pandoc [correctly] escapes the `{` with a backslash so you get literal `{plus}` in the output.

**Comment by silby** [comment]
It looks like from the docs that a literal `+` in asciidoc might as well always be emitted as `{plus}`, is that accurate?

**Comment by gavinwahl** [comment]
I think so, except CodeBlock.

**Comment by jgm** [comment]
I am fixing this.  But note: you can emit an 'asciidoc' RawInline in the filter to avoid escaping.
