### ISSUE TITLE
Extra Blank Line Between List Items When Converting LaTeX to Markdown

### ISSUE THREAD

**Issue by tsunyinlam** [jgm/pandoc#10396]
When converting a LaTeX file containing a simple `itemize` environment to Markdown using Pandoc 3.5 on macOS, extra blank lines are introduced between list items. Given the following LaTeX input:

```latex
\begin{itemize}
    \item a
    \item b
\end{itemize}
``` 

and command `pandoc test.tex -o test.md` I get 

```
-   a

-   b
```

I expected to get the following instead.

```
-    a
-    b
```

**Comment by jgm** [comment]
LaTeX doesn't distinguish between "tight" and "loose" lists, so we make it loose.
