### ISSUE TITLE
markdown -> typst loses indentation for ordered lists

### ISSUE THREAD

**Issue by nc-x** [jgm/pandoc#10409]
**Explain the problem.**

markdown -> typst loses indentation for ordered lists, whereas it works fine for unordered lists

the command I am using is: `pandoc -f commonmark_x -t typst --toc --toc-depth=6 --number-sections --wrap=none --standalone <file>.md -o <file>.typ`, (i just copied the arguments from another project of mine so some may be useless for a typst output)

## Example 1:

This markdown
```md
1. abc
2. def
  1. acx
  2. xyz
```
gets compiled to the following typst
```typst
+ abc
+ def
+ acx
+ xyz
```

whereas it should be:
```typst
+ abc
+ def
  + acx
  + xyz
```

## Example 2:

This markdown
```md
1. abc
2. def
  - acx
  - xyz
```
gets compiled to the following typst
```typst
+ abc
+ def

- acx
- xyz
```

whereas it should be:
```typst
+ abc
+ def
  - acx
  - xyz
```

## Example 3:

This markdown
```md
1. abc
  - 123
  - 456
2. def
  - 123
  - 456
```
gets compiled to the following typst
```typst

+ abc

- 123
- 456

#block[
#set enum(numbering: "1.", start: 2)
+ def
]

- 123
- 456
```

whereas it should be:
```typst
+ abc
  - 123
  - 456

#block[
#set enum(numbering: "1.", start: 2)
+ def
  - 123
  - 456
]
```

Or simply:
```typst
+ abc
  - 123
  - 456

+ def
  - 123
  - 456
```

**Pandoc version?**

```
$ pandoc -v
pandoc.exe 3.5
Features: +server +lua
Scripting engine: Lua 5.4
```

**Comment by jgm** [comment]
Your sublist is not indented far enough.  It must be indented to match the beginning of the content.  Pandoc uses the same rule here as commonmark.

So, this, for example:
```
1. abc
2. def
   - acx
   - xyz
```

GFM should agree with pandoc here (since it's based on commonmark).  Testing:

1. abc
2. def
  - acx
  - xyz
