### ISSUE TITLE
EPUB cover image paths are not URL-encoded (causing spaces in filename to break cover images)

### ISSUE THREAD

**Issue by TangentFoxy** [jgm/pandoc#10404]
**Explain the problem.**

`pandoc --from markdown --to epub "file name.md" -o "file name.epub" --toc=true --epub-cover-image="cover image.jpg"`

The resultant EPUB has spaces in the cover image file name and the URLs used within the EPUB do not URL-encode these spaces, causing validation errors.

Strangely, when I use an image file with no spaces, which passes validation, the cover image still doesn't appear in Google Play Books. (And yes, I did see that I need to include the image in the metadata as `cover-image`. That is in-place.)

**Pandoc version?**

Pandoc 3.5 on Windows 10.

**Comment by bpj** [comment]
So change to `file-name.ext` with hyphens.

There is an old rule: never use whitespace/capitals/non-ASCII in file/folder names (or anywhere else in the file system!) Microsoft habitually breaks that rule and has thought their users to do likewise, with some cross-platform projects like LibreOffice doing it too. Doesn't make it a good idea. The most obvious advantage is that you don't need to quote names/paths in the shell, but there are others as you have found.

**Comment by jgm** [comment]
Pandoc should not break, though, when someone uses a filename with spaces.
So this is  a legitimate bug report.

**Comment by jgm** [comment]
Interestingly, though, the epubcheck warning is triggered by the image file itself, not by the URIs referring to it.  Even when I change the spaces in these to `%20`, I still get the warning:
```
WARNING(PKG-010): my.epub/EPUB/media/La Lune.jpg(-1,-1): Filename contains spaces, therefore URI escaping is necessary. Consider removing spaces from filename.
```
So, escaping the spaces in the URIs won't make the warning go away.  We could just change the spaces to `_` and modify the filename, I suppose.

**Comment by TangentFoxy** [comment]
I was getting different errors + that warning.

Here's a minimal test case: [test case.zip](https://github.com/user-attachments/files/17882579/test.case.zip)

And I was using an online version of EPUBCheck to validate at https://www.bookery.app/epub_validation/ebooks/e39a2bb4-923d-43a1-85ee-5a7937603a27

In case that page expires, here's a screenshot of its output:
![image](https://github.com/user-attachments/assets/7b20806e-7068-4d5d-8f18-11680fc4db0c)

**Comment by jgm** [comment]
Interesting. Maybe my version of epubcheck is old.
