### ISSUE TITLE
Textile rendering, text converted to html with del tag

### ISSUE THREAD

**Issue by dbojan** [jgm/pandoc#10414]
**Explain the problem.**
When converting from textile to html, pandoc adds `del` html tag

input: 
strike through.textile, content:

`from 30.-100. text, inside - after dash`

output html:

`<p>from 30.<del>100. text, inside</del> after dash</p>`

expected output would be without `del` tag.

command line:
pandoc.exe "strike through.textile" -o "strike through.html" 

**Pandoc version?**
3.5, windows 10

Thanks.

**Comment by dbojan** [comment]
textile [Insertions and deletions](https://textile-lang.com/doc/insertions-and-deletions)

**Comment by jgm** [comment]
Experimenting, it seems that the opening `-` in a deletion must be preceded by whitespace or opening punctuation (e.g. `(`) and followed by non-whitespace, and the closing `-` must be followed by whitespace or closing punctuation.  (End or beginning of line counts as whitespace here.)
