### ISSUE TITLE
use SOURCE_DATE_EPOCH for more timestamps

### ISSUE THREAD

**Issue by bmwiedemann** [jgm/pandoc#10423]
**Describe your proposed improvement and the problem it solves.**
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds) 
I found that our `conky` package varies in its man page because pandoc embeds the current `{{ date }}` and `{{ copyright_year }}`:
https://github.com/brndnmtthws/conky/blob/a0ee703ee27b476c2bf4e02d6392c1f4d9c51764/doc/man.md.j2#L278 and line 3

https://github.com/jgm/pandoc/commit/5d71276eca already uses `SOURCE_DATE_EPOCH` for some timestamps, but maybe other calls of `getCurrentTime` have to be patched in a similar way.

**Describe alternatives you've considered.**

We could use sed to drop the macros before pandoc runs, but that feels like a dirty hack.

**Comment by jgm** [comment]
The template you link to is not a part of pandoc, and it is not even a template in pandoc's template format.  So something else than pandoc must be filling in these variables in your build process (Jinja2, presumably).  Thus I don't think this has anything to do with pandoc.  Am I missing something?

**Comment by bmwiedemann** [comment]
Ah, you are right. These values come from conky's `doc/render.py`

Sorry for the confusion and thank you.
=> closing
