### ISSUE TITLE
[Feature Request] allow simple markdown tables such as pipe_tables also observe column widths

### ISSUE THREAD

**Issue by terefang** [jgm/pandoc#10427]
**Describe your proposed improvement and the problem it solves.**

today all simple tables such as `pipe_tables` have column width set to `ColWidthDefault` -- see https://github.com/jgm/pandoc/blob/5f4c4ae22395db3d2365e550d2b1c5d516b9e3de/src/Text/Pandoc/Readers/Markdown.hs#L1337

for such a pipe table:

```
| Difficulty	| Range	       | D	 | DC	| TN  | TX	| TY  | TZ  |
|:--------------|:-------------|:---:|:---:|:---:|:---:|:---:|:---:|
| Automatic	    | Self/Touch	| 0 | 0	| 0	 | 0  | 0 | 0 |
| Trivial	    | Reach	        | 1	| 1	| 5	 | 4  | 3 | 3 |
| Easy	        | Near/Close	| 2	| 2	| 10 | 8  | 6 | 5 |
| Moderate	    | Medium	    | 4	| 3	| 15 | 12 | 9 | 8 |
| Difficult	    | Far	        | 6	| 4	| 20 | 16 | 12 | 10 |
| Hard	        | Long	        | 8	| 5	| 25 | 20 | 15 | 13 |
| Heroic	    | Extreme	    | 10| 6	| 30 | 24 | 18 | 15 |
| Legendary	    | Horizon	    | 12| 7	| 35 | 28 | 21 | 18 |
| Epic	        | *	            | 14| 8	| 40 | 32 | 24 | 20 |

```

this may cause output formats to distribute the table cells evenly on a row.

would it be possible to parse the separator line `|:--------------|:-------------|:---:|:---:|:---:|:---:|:---:|:---:|`, and use the number of dashes as an indicator of percentage of column-width ?

in the above case that would calculate to:  `14+13+3+3+3+3+3+3 = 45` so each "width" would be multiplied by `(100/45)` to form the percentages – resulting in  `31%, 29%, 7% 7% 7% 7% 7% 7%`.

**Describe alternatives you've considered.**

it is not possible to correct this with a lua filter since the original separator line is no longer available in later stages.

i have also considered maintaining widths outside the table in the attributes of a fence like:

```
::: {widths="29%,29%,7%,7%,7%,7%,7%"}

| Difficulty	| Range	       | D	 | DC	| TN  | TX	| TY  | TZ  |
|:--------------|:-------------|:---:|:---:|:---:|:---:|:---:|:---:|
| Automatic	    | Self/Touch	| 0 | 0	| 0	 | 0  | 0 | 0 |
| Trivial	    | Reach	        | 1	| 1	| 5	 | 4  | 3 | 3 |
| Easy	        | Near/Close	| 2	| 2	| 10 | 8  | 6 | 5 |
| Moderate	    | Medium	    | 4	| 3	| 15 | 12 | 9 | 8 |
| Difficult	    | Far	        | 6	| 4	| 20 | 16 | 12 | 10 |
| Hard	        | Long	        | 8	| 5	| 25 | 20 | 15 | 13 |
| Heroic	    | Extreme	    | 10| 6	| 30 | 24 | 18 | 15 |
| Legendary	    | Horizon	    | 12| 7	| 35 | 28 | 21 | 18 |
| Epic	        | *	            | 14| 8	| 40 | 32 | 24 | 20 |

:::
```

and massaging the ast via lua-filter, but that seems rather counter-intuitive and duplicate work

**Comment by jgm** [comment]
As documented:  if any of the table lines exceed the standard column width (see `--columns`), then pipe tables will have relative widths computed based on the separator lines.  So, to enable this feature you just need to make one of your table lines longer than the column width, which you can easily do without affecting the contents of cells just by adding spaces.

Thus, the feature is already there.  We wouldn't want to change the default behavior, though, because in most formats this produces better output.

**Comment by terefang** [comment]
ok ... while it works i am very unhappy with the option since it both affect wrapped text and tables at the same time.

so if i set `--columns=10` to force all my tables to have percentages, what would it do to wrapped text ?

i would be more comfortable to have an option like `--force-table-widths`.

**Comment by jgm** [comment]
Don't set `--columns`.  Just add extra space to one of the cells of your table so that the line is longer than the setting (or default setting) of `--columns`.

**Comment by terefang** [comment]
the default in the docs says 72. so for very terse tables you want me to create something like this:

```
|Pip(s)|Die Code| CP |
|:---:|:---:|:---:|
|  1 |   +1  |  1                                                                                                                                |
|  2 |   +2  |  3 |
```

**Comment by terefang** [comment]
maybe as explaination – i am exporting to typst with some lua filters and the layout has a variable number of columns (1-3).

setting `--columns` to a very small value is the only way to get percentage widths for terse tables in on multi-column pages.

**Comment by jgm** [comment]
It is not the only way; you can insert spaces as noted above.

Note also that if you use multiline or grid tables, you will always get the column widths. So, you could switch to those formats.

**Comment by terefang** [comment]
wouldnt it be better in relation to https://github.com/jgm/pandoc/issues/10111 to have a option ?

**Comment by jgm** [comment]
The idea of an option with three settings (smart/auto/none) is a good one, I think.  I am not sure what my final view on it would be, but feel free to submit an issue requesting this.

**Comment by bpj** [comment]
@terefang this filter of mine, freshly documented, can help with this issue, since column widths (and alignments) set by a filter are preserved/used by writers.

https://github.com/bpj/pandoc-table-columns

**Comment by terefang** [comment]
> @terefang this filter of mine, freshly documented, can help with this issue, since column widths (and alignments) set by a filter are preserved/used by writers.

i have also though about a similar solution, but i consider my proposal is the more generic solution which puts less burden on the document-author keeping to the principles of markdown.
