### ISSUE TITLE
pandoc 3.6 still asks for definitions.typst even though it was removed

### ISSUE THREAD

**Issue by hgvhgv** [jgm/pandoc#10454]
Trying to use typst with pandoc 3.6 and getting a missing definitions.typst error:
```
% pandoc -d typst -t typst input.md -o output.pdf
Could not find data file templates/definitions.typst
```
I create a blank definitions.typst file in my templates directory and the command works. Per the release notes (https://github.com/jgm/pandoc/discussions/10442), definitions.typst was removed.

**Pandoc version?**
pandoc 3.6
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/hgv/.local/share/pandoc
Installed via Homebrew 4.4.11-10-g95d2377
On 13.6.3

**Comment by jgm** [comment]
I'm guessing you're using a custom default.typst in your templates directory that still refers to definitions.typst?  If so, you need to update it.

**Comment by hgvhgv** [comment]
Thank you, yes, should have looked there. Sorry for the bother!
