### ISSUE TITLE
`csquotes:true` should wrap block quotes in `displayquote` environments

### ISSUE THREAD

**Issue by putzwasser** [jgm/pandoc#10456]
**Explain the problem.**

Pandoc has support for `csquotes: true` to make use of the `csquotes` package. The latex package provides the `displayquote` environment.

```md
---
title: "Your Document"
format:
  pdf:
    keep-tex: true
csquotes: true
---

> This is a block quote.
```

Running

```bash
pandoc -f markdown -t latex test.md
```

Yields this result

```latex
\begin{quote}
This is a block quote.
\end{quote}
```

I would have expected that pandoc would use `csquote`'s `displayquote` environment for block quotes.

**Pandoc version?**
pandoc -v
pandoc 3.1.11.1
Features: +server +lua
Scripting engine: Lua 5.4

**Comment by jgm** [comment]
Is it the case that by default (without further customizations in the preamble), `displayquote` will behave just like `quote`?  If so, we could consider this.
