### ISSUE TITLE
--pdf-engine=wkhtmltopdf always fails in pandoc 3.6

### ISSUE THREAD

**Issue by Choonholic** [jgm/pandoc#10468]
**To do:**
Convert markdown document to PDF applied style.css

**Prerequisites**
Pandoc 3.6
wkhtmltopdf 0.12.6

**Reproducing:**
```
pandoc source.md -f markdown -o dest.pdf --pdf-engine=wkhtmltopdf
```
**Symptoms:**
Pandoc 3.5 worked perfectly.

But, Pandoc 3.6 always failed from 1st step like below.

```
Error: Failed loading page file://toPC54C.source (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1, due to unknown error.
Error producing PDF.`
```

Unfortunately, `--load-error-handling ignore` did not help.

Thanks.

**Comment by jgm** [comment]
That error message comes from wkhtmltopdf, not pandoc.
If you want to pass `--load-error-handling ignore` to wkhtmltopdf, you'll have to use this option in pandoc:
```
--pdf-engine-opt=--load-error-handling --pdf-engine-opt=ignore
```

**Comment by jgm** [comment]
If it works with pandoc 3.5 (I assume you have tested recently with same wkhtmltopdf version), then perhaps the culprit is this item in the changelog:
```
    + Use `.source` extension, not `.html`, in `toPdfViaTempFile` (#10314).

```

**Comment by Choonholic** [comment]
Yes, pandoc 3.5 worked perfectly with the same configuration.
I will review the changelog and report the result.

Thanks.

However, passing `--pdf-engine-opt` parameters did not help.

**Comment by Choonholic** [comment]
When I use wkhtmltopdf separately, it works as expected. (Pandoc 3.6)

```
pandoc -f markdown -o out.html -c style.css --embed-resources --standalone source.md
wkhtmltopdf --enable-local-file-access out.html out.pdf
```

I absolutely agree the changes by #10314 are the reason of the symptoms.

Tnanks.
