### ISSUE TITLE
The variable toc-title do not effect the docx output

### ISSUE THREAD

**Issue by Gowa2017** [jgm/pandoc#10474]
Source markdown file:

```
# heading 1

## heading 2

content
```

I use command to gen office word:

```sh
pandoc -f gfm -t docx -o out.docx -V toc-title="目录" --toc
```

But the output file's Toc title is also **Table of contents**， not "目录"。

So, how can I change the toc title.

> title of table of contents (works only with EPUB, HTML, revealjs, opendocument, odt, docx, pptx, beamer, LaTeX). Note that in docx and pptx a custom toc-title will be picked up from metadata, but cannot be set as a variable. 

Fixed.

**Comment by fault-segment** [comment]
@Gowa2017 hello，how to apply the  content change of toc title？
这个具体要怎么搞？

**Comment by rnwst** [comment]
@fault-segment -- as per the [documentation](https://pandoc.org/MANUAL.html#variables-set-automatically) quoted by Gowa2017 above,

> Note that in docx and pptx a custom `toc-title` will be picked up from metadata, but cannot be set as a variable.

Therefore, you need to set the `toc-title` in the frontmatter of your document:
```markdown
---
title: My title
toc-title: My custom TOC title
---

Document content.
```
