### ISSUE TITLE
Integrate Slidev and Marp output formats

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [jgm/pandoc#10483]
Both [Slidev](https://sli.dev) and [Marp](https://marp.app) are modern markdown-based JS slide generators. Slidev uses Vue.js, Marp uses Marpit and is based on CommonMark.
They can be used as alternatives to the RevealJS output format.

**Comment by jgm** [comment]
My understanding is that they use markdown source (just like pandoc when converting md -> reveal.js).

Since we already have a markdown writer, why would we need anything special for these?

And why would a pandoc user need to use either, since pandoc already does a good job generating HTML slide shows from markdown source?

**Comment by BinaryQuantumSoul** [comment]
Yes there are not many things to implement, as it's mainly some Markdown format conversions (Like the existing CommonMark for example) piped with the existing marp/slidev tools. Well users can use those because they don't generate the same slides than revealjs would, each has its own features so more choices for the users. Having a single thing that does all instead is of having to use different tools is a better workflow basically

**Comment by yhatt** [comment]
I am the author of [Marp](https://marp.app) mentioned here, but I'm somewhat skeptical of this suggestion to Pandoc.

As far as I understand, HTML + JavaScript slideshows supported by Pandoc, including reveal.js, work by converting Markdown to HTML, and (mostly simply) adding `<script>` tags, which allow the browser to load client-side JavaScript for displaying slides with features such as pagination and presenter tools.

Marp can similarly render slides in the browser by using [its core](https://github.com/marp-team/marp-core) (https://github.com/orgs/marp-team/discussions/480). However, this core does **not** provide the functionality for displaying presentations, such as pagination or presenter tools. This is clearly different design from the HTML slideshow frameworks supported by Pandoc.

Marp provides a tool for outputting its own HTML slideshow ([Marp CLI](https://github.com/marp-team/marp-cli), powered by [Bespoke.js](https://github.com/bespokejs/bespoke)), but it is built for server-side JavaScript runtime such as [Node.js](https://nodejs.org/). Adding this to Pandoc would increase dependency on tools by the different language, and potentially leading to greater complexity.

The same applies to Slidev. Slidev relies on the build process entirely with a server-side JS ([Vite](https://vite.dev/)), to [transpile Vue.js components](https://sli.dev/guide/component) and incorporates many presentation features. IMO generating its output is not as straightforward as that of Marp and already supported HTML slideshows by Pandoc.
