### ISSUE TITLE
Markdown to LaTeX keeps hashtags in empty sections

### ISSUE THREAD

**Issue by gian-didom** [jgm/pandoc#10487]
**Explain the problem.**
When running the following command:
`pandoc --read markdown --write latex --output "test.pdf" "test.md"`

With the `test.md` file looking like:

```md
# Table of Contents
### 0. Introduction
----
### Part I: Theory
```

The output PDF is:
<img width="250" alt="image" src="https://github.com/user-attachments/assets/8b7a79ca-20d9-4bbe-869e-1a538c5dae21" />

If I add some content instead of the `----`, such as:

```md
# Table of Contents
### 0. Introduction
This is an introduction.
----
### Part I: Theory
```

I get this:

<img width="264" alt="image" src="https://github.com/user-attachments/assets/3f8ed37d-95f7-4513-a6e8-245c2fd18ada" />

If I remove the `----`, I get something reasonable:

```md
# Table of Contents
### 0. Introduction
This is an introduction.
### Part I: Theory
```

<img width="239" alt="image" src="https://github.com/user-attachments/assets/26a86dbf-fb44-4fa8-9cc6-ace877a941ce" />

**Pandoc version?**
```
pandoc -v
pandoc 3.6
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/myUser/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

on MacOS 15

**Comment by silby** [comment]
The `----` is getting interpreted as a [Setext-style heading](https://pandoc.org/MANUAL.html#setext-style-headings) when it is immediately below a line of text. If you want it to be interpreted as a horizontal rule, put a blank line before it.
