### ISSUE TITLE
AsciiDoc ID attribute: Invalid syntax used when output contains list items

### ISSUE THREAD

**Issue by sorairolake** [jgm/pandoc#10503]
**Explain the problem.**

First, use `pandoc` to convert the [legal code of CC BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode.en) from HTML to AsciiDoc:

```sh
curl "https://creativecommons.org/licenses/by/4.0/legalcode.en" | pandoc -f html -t asciidoc > CC-BY-4.0.adoc
```

Next, use `asciidoctor` and `pandoc` to convert this from AsciiDoc to Pandoc's Markdown

```sh
asciidoctor -b docbook5 -o - CC-BY-4.0.adoc | pandoc -f docbook -t markdown
```

When I ran the above, I got the following error from `pandoc`:

```text
Invalid XML:
ParseError {errorContexts = ["open tag","'>'"], errorMessage = "Failed reading: satisfy", errorPosition = 328:32 (16062)}
```

Lines 328 to 330 of DocBook 5 generated by `asciidoctor` are as follows:

```xml
<simpara><anchor xml:id="s2a3" xreflabel="Term . The term of this Public License is specified in
Section <link xl:href="#s6a">6(a)</link> ."/><emphasis role="strong">Term</emphasis> . The term of this Public License is specified in
Section <link xl:href="#s6a">6(a)</link> .</simpara>
```

The corresponding AsciiDoc file generated by `pandoc -f html -t asciidoc` is:

```adoc
.. [#s2a3]#*Term* . The term of this Public License is specified in
Section link:#s6a[6(a)] .#
```

According to the [AsciiDoc Language Documentation](https://docs.asciidoctor.org/asciidoc/latest/attributes/id/#on-a-list-item), you can assign an ID to an inline element using the shorthand syntax or the inline anchor syntax. However, looking at the examples in the documentation, I think it might be possible to not use the shorthand syntax for list items, a table cells and inline images.

Therefore, I think that in these cases it is necessary to output the inline anchor syntax instead of the shorthand syntax.

```adoc
.. [[s2a3]]*Term* . The term of this Public License is specified in
Section link:#s6a[6(a)] .
```

When I run `asciidoctor -b docbook5 -o - CC-BY-4.0.adoc | pandoc -f docbook -t markdown` using the inline anchor syntax above, no errors occurred and the following Pandoc's Markdown was output:

```md
a.  []{#s2a3}**Term** . The term of this Public License is specified in
    Section [6(a)](#s6a) .
```

**Pandoc version?**

```sh
$ pandoc -v
pandoc 3.1.11.1
Features: +server +lua
Scripting engine: Lua 5.4
```

Also checked on <https://pandoc.org/try/>.

**Comment by jgm** [comment]
This parse error comes from xml-conduit, the XML parsing library we use.
I believe the error indicates invalid XML in the asciidoctor output.  Note that the asciidoctor output includes unescaped `<` characters in the attribute value, which I believe is invalid XML: see https://www.w3.org/TR/xml/#syntax

``
xreflabel="Term . The term of this Public License is specified in
Section <link xl:href="#s6a">6(a)</link> ."
```

So, I believe this is  really a bug in asciidoctor's docbook renderer.  The `<` characters here should be escaped as `&lt;`.
