### ISSUE TITLE
Using pandoc to produce reveal.js slides

### ISSUE THREAD

**Issue by jaydixit** [jgm/pandoc#1051]
https://github.com/jgm/pandoc/wiki/Using-pandoc-to-produce-reveal.js-slides

When using pandoc to produce reveal.js slides from markdown source, is there a way to specify per-slide background images, a la 

``` html
<section data-background="http://example.com/image.png">
<h2>This slide will have a full-size background image.</h2>
</section>
```

**Comment by sjackman** [comment]
With `data-background`, is there a way to specify the opacity of the image?
Related to https://github.com/hakimel/reveal.js/issues/1279 and https://github.com/hakimel/reveal.js/issues/1973

**Comment by mberasategi** [comment]
How about other attributes for slides with no header? To clarify, I am trying to vertically center certain slides _only_, which can be done by adding the `center` class to the slide. For slides with a header in Markdown, `## My title {.center}` is working well, but how about if I have a "text only" slide?

Apparently reveal.js allows to [add a certain class to the section element](https://github.com/hakimel/reveal.js/issues/1262#issuecomment-269866545) using `<!-- .slide: class="center" -->` after each `---` for each slide. This is not rendering correctly through pandoc, though.

**Comment by jgm** [comment]
You can use an empty header with attribute

    # {.class}

**Comment by mberasategi** [comment]
Neat, thanks!
