### ISSUE TITLE
pandoc not added to path on windows

### ISSUE THREAD

**Issue by ibell** [jgm/pandoc#1054]
As it says in the title, on windows, when I run the installer, pandoc folder is not added to the path.  For me, it is installed in C:\Users\Belli\AppData\Local\Pandoc .  The only way I could figure out the installation path was to go to start menu and figure out the path to the local documentation HTML file

**Comment by jgm** [comment]
I'm closing this since #1403 seems to be the same issue.

**Comment by tjbarbour** [comment]
Just in case someone else has the same issue as me, my issue was actually a corrupted PATH.  Some other program (not pandoc) had accidentally inserted an extra quote ( " ) in the Path, rendering the following entries (including pandoc) ignored.

**Comment by shumeA** [comment]
What i have to do I'm using window 10 and it say's 'pandoc' is not recognized as an internal or external command, operable program or batch file?

**Comment by Opdoop** [comment]
@shumeA I have the same issue. Just restart computer solved the problem.

**Comment by SeaDude** [comment]
@shumeA , 

**I had to:**
1. Uninstall pandoc
2. Then check the box saying `Install for all users on this machine` to get my instance to working. 

**This is after I:**
1. Verified that install was initially successful
2. Pandoc was in my `PATH` variable
3. And I tried running `pandoc -h` from a new terminal (as administrator)...
4. ...after a fresh restart.
