### ISSUE TITLE
Template variable conditions

### ISSUE THREAD

**Issue by nightmarebadger** [jgm/pandoc#1057]
It seems that currently all we can do is simply test if the variable is non-null, in other words, we do this:

```
$if(variable)$
something
```

I have looked through the templates and asked around on IRC, but haven't found a way to do an "if variable equals value", or something like

```
$if(variable==value)$
something
```

Is there a reason why this isn't supported? It could be very useful for me because I'm trying to make a multi-language template, and would need to change some of the data, the footer etc. according to the language. For only 2 languages you can get away with using Booleans, but what about when you want to use more?

Having a metadata for each language you want to support seems kinda stupid and is error prone, as something like

```
$if(english)$
Hello!
$endif$

$if(german)$
Hallo!
$endif$
```

Can write both "Hello!" and "Hallo!" when the user inputs both variables as True. 

If this has already been talked about, or has even been implemented and I just missed it I apologise, but if it hasen't I'd like to know if there's a reason why this isn't supported or you just haven't found the time to get to it yet. Because it sure seems reasonable and useful to have this functionality :).

**Comment by infoxiao** [comment]
oh wow just encountered this. quite surprising! would be good to add to documentation
