### ISSUE TITLE
Add option to put reference links after the paragraph that includes the citation in markdown output

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#107]
<pre>
Currently, markdown output always puts reference links (for both urls and footnotes) at the end of the document. The suggestion is to provide an option to put them instead after the paragraph that includes the citation.

Actually, that isn't quite right. The suggestion is to put the reference links into the document as early as possible, given where the citation occurs in the document. 

See this discussion thread:

http://groups.google.com/group/pandoc-discuss/browse_thread/thread/c60827fcd32fb492/15def96daa775213

Google Code Info:
Issue #: 261
Author: dsan...@gmail.com
Created On: 2010-10-20T18:01:48.000Z
Closed On: 
</pre>

**Comment by link2xt** [comment]
Looks like `--reference-location=block` implements this behaviour for Markdown writer:
```
$ pandoc -f muse -t markdown --reference-location=block
First paragraph[1].

Second paragraph[2].

[1] First footnote

[2] Second footnote
^D
First paragraph[^1].

[^1]: First footnote

Second paragraph[^2].

[^2]: Second footnote
```

@jgm 
Should this bug be closed? Alternatively, we can convert it into feature request to add this feature to more lightweight markup writers.

**Comment by link2xt** [comment]
Code search shows that `writerReferenceLocation` field of `WriterOptions` is honored only by Markdown writer.

**Comment by jgm** [comment]
Yes, this is closed by the `--reference-location` option.
We could discuss implementing this in other formats, but this issue is about markdown, so it's done!
