### ISSUE TITLE
horizontal rule in plain text formatted as markdown

### ISSUE THREAD

**Issue by landlord11** [jgm/pandoc#1095]
Hi, when specifying a horizontal rule in markdown, for example:

```
test

* * * * * * * *
```

and then converting to plain text (pandoc -f markdown -t plain --columns 80 test.txt), you always get:

```
test

* * * * *
```

Can the rule be formatted (using, presumably, some other character sequence) to match the width specified by --columns?

Thanks!
Brian

**Comment by link2xt** [comment]
Looks like it is already fixed:
```
$ pandoc -f markdown -t plain --columns 80 test.txt
test

--------------------------------------------------------------------------------
```
