### ISSUE TITLE
static build of pandoc?

### ISSUE THREAD

**Issue by dubiousjim** [jgm/pandoc#11]
Hi John, does your build system easily permit one to make a completely static build of pandoc? Currently I use this build invocation: http://aur.archlinux.org/packages/pandoc/pandoc/PKGBUILD (ignore the metadata, all that's important here is the build() function). And I think that does eliminate any dependencies on ghc or haskell libraries. Running `ldd pandoc` gives:
    linux-vdso.so.1 =>  (0x...)
    libz.so.1 => /usr/lib/libz.so.1 (0x...)
    librt.so.1 => /lib/librt.so.1 (0x...)
    libutil.so.1 => /lib/libutil.so.1 (0x...)
    libdl.so.2 => /lib/libdl.so.2 (0x...)
    libgmp.so.10 => /usr/lib/libgmp.so.10 (0x...)
    libm.so.6 => /lib/libm.so.6 (0x...)
    libc.so.6 => /lib/libc.so.6 (0x...)
    libpthread.so.0 => /lib/libpthread.so.0 (0x...)
    /lib/ld-linux-x86-64.so.2 (0x...)

But I need to build pandoc on my linux system (which has ghc and all the necessary libs) and deploy it on an unattended mac server, where it's too much work to get the necessary build chain set up and keep it maintained. If it's not too hard to make a fully static build of pandoc, that might be the easiest solution.

**Comment by msabramo** [comment]
I wonder if a lot of folks who want a static build for Linux could also address their problem by using a Docker container with pandoc -- e.g.: https://registry.hub.docker.com/u/jagregory/pandoc/

That said, I'm trying to build a static binary for Mac OS X.

**Comment by jtprince** [comment]
On arch (3.18.6-1-ARCH), the following build process worked for me (using purpleidea and jgm's suggestions):

```bash
sudo pacman -S cabal-install
 export PATH="$HOME/.cabal/bin:$PATH"
cabal install pandoc -fembed_data_files --force-reinstalls hsb2hs
```

The pandoc-static AUR package install appears to still be broken as reported up above.  Next, I will try doing that install with ~/.cabal/bin in my $PATH.

**Comment by petrelharp** [comment]
Clarification: what libraries should the resulting binary be linked to?  I thought the answer was "none", but no matter which way I do it, I always get ones linked to libgmp, libc, etcetera.

**Comment by kaushalmodi** [comment]
@jgm Can you please reconsider providing static binaries for Linux with each release?

At my work, I do not have admin rights on my Linux machine (RHEL 6.6) and I cannot install `cabal` locally or have the admin install it as no one codes in Haskell at work.

Recently, @koalaman, author of another awesome Haskell project [ShellCheck][1], added auto-building of static Linux executables in [this commit][2]. Could that possibly be reused to generate static binaries for `pandoc` too?

Thanks.

[1]: https://github.com/koalaman/shellcheck
[2]: https://github.com/koalaman/shellcheck/commit/21f5bf01ebfde23a428c0a154e05d2468a11a00c

**Comment by jgm** [comment]
+++ Kaushal Modi [Jul 10 17 08:16 ]:
>   [1]@jgm Can you please reconsider providing static binaries for Linux
>   with each release?

I've already got a procedure set up for producing completely
static linux binaries. We'll have them starting with the
next release.

I could have this built with continuous integration, but
I've hesitated because in addition to being static, the builds
use -shared-objects to minimize the executable size, and
they take forever.  Maybe it will be faster with the new
version of ghc.

>   At my work, I do not have admin rights on my Linux machine (RHEL 6.6)
>   and I cannot install cabal locally or have the admin install it as no
>   one codes in Haskell at work.
>
>   Recently, [2]@koalaman, author of another awesome Haskell project
>   [3]ShellCheck, added auto-building of static Linux executables in
>   [4]this commit. Could that possibly be reused to generate static
>   binaries for pandoc too?

**Comment by kaushalmodi** [comment]
> I've already got a procedure set up for producing completely
static linux binaries. We'll have them starting with the
next release.

That's great! Thank you.

> I could have this built with continuous integration, but
I've hesitated because in addition to being static, the builds
use -shared-objects to minimize the executable size, and
they take forever.  Maybe it will be faster with the new
version of ghc.

I believe you can configure CI to execute only for releases (on when a commit is [tagged][1]) and not for each commit. 

[1]: https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

**Comment by jgm** [comment]
+++ Kaushal Modi [Jul 10 17 17:50 ]:
>   I believe you can configure CI to execute only for releases (on when a
>   commit is [1]tagged) and not for each commit.

Yes.  In any case I'll be releasing static binaries with
each release.

**Comment by scrutinizer11** [comment]
Hello,
I'd like to chime in asking how's it going now? Have you successfully kept up building static **pandoc**? I endured constant fails and errors trying to compile it from the source on my Mac (true it runs a very old macOS so I'm not sure whether _that_ is the culprit) and gave up. The procedure is too tedious and multi-layered for what I need it which is to compile another executable, I don't plan to use **pandoc** extensively on its own. I'm looking for static builds and so far have downloaded following the provided link to _Rstudio_ builds.

**Comment by jgm** [comment]
We can produce a completely static executable on linux (and that's what you'll find on our Releases page).  However, as I understand things, it is not possible on macos; there will be a dependency on dynamic system libraries.
