### ISSUE TITLE
Conversion to ConTeXt tables from Markdown with NaturalTables

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#1100]
Recently [discussed](http://www.ntg.nl/pipermail/ntg-context/2013/075905.html) in ConTeXt mailing list if Pandoc could pass tables from markdown to ConTeXt using Natural tables, aka [TABLE](http://wiki.contextgarden.net/TABLE).

This way could easy the use of t-filter module developed by Aditya [https://github.com/adityam/] and avoid long long lines in tables.

Thanks in advance,

@adityam: cc you

**Comment by jgm** [comment]
Closing in favor of #2102
