### ISSUE TITLE
Clickable citations

### ISSUE THREAD

**Issue by nh2** [jgm/pandoc#1117]
I'm experimenting with citations as explained in entry 24 in [the demos page](http://johnmacfarlane.net/pandoc/demos.html).

```
pandoc -s -S --biblio biblio.bib --csl ieee.csl CITATIONS -o example.pdf
```

This gives me text like `Reference [1] says blah.`

Is it possible to make the `[1]` a clickable hyperlink when generating PDFs, in the same way that footnotes are clickable hyperlinks?

---

Fast way to reproduce:

```bash
wget http://johnmacfarlane.net/pandoc/demo/CITATIONS
wget http://johnmacfarlane.net/pandoc/demo/ieee.csl
wget http://johnmacfarlane.net/pandoc/demo/biblio.bib
pandoc -s -S --biblio biblio.bib --csl ieee.csl CITATIONS -o example.pdf
```

**Comment by pprw** [comment]
:+1:  I'm supporting this feature request.

I wrote papers with LaTeX; thanks to the hyperref package my references are clickables in the pdf LaTeX output. This is a very essential feature for me and I'm not happy to see it disappear when I export my papers to html with pandoc.

This feature should work like the footnote one. In fact, it is the way it works the LaTeX and hyperref package: with the authoryear style, hyperref transform every year into a link which gets you to the reference in the ending bibliography.

(this way : [Author [2000](#2000)]




Bibliography
<a name="2000">Author (2000), title, publisher, ...</a>

**Comment by jgm** [comment]
I have no doubt about the usefulness of this feature.  The problem is
a technical one.  pandoc-citeproc (whose code I mostly inherited
from citeproc-hs) returns a fully formatted citation that might cite
several sources, and the individual sources are not separated out,
so there's no way to link each source to its bibliography entry.
So, I wholeheartedly support this feature request, but it will require
some pretty significant modifications to pandoc-citeproc, which is
unfortunately not an easy code base to work with.

+++ pprw [Feb 15 15 03:57 ]:

**Comment by pprw** [comment]
Thanks for the quick answer. I understand this could be hard to be implemented. Unfortunately I don't have the skills to help and can only say "good luck". I hope to see the feature in the future; I believe it would really be a key feature for scholars who want to convert papers to html to allow others to read them on tablets, smartphones, ...

**Comment by jgm** [comment]
I have just pushed a change to pandoc-citeproc that gives you clickable years (which link to the corresponding bibliography entry) in author-year citation formats.  Note that this does not yet work with numerical citation styles.

**Comment by jgm** [comment]
OK, now they work with numerical styles too.

**Comment by jgm** [comment]
To be more precise, they work for normal references with numerical styles.  They still don't give you a link for this form:

    @doe99 says blah.

when rendered as

    Reference [1] says blah.

It should be possible to fix this.

**Comment by jgm** [comment]
OK, these work now, with latest pandoc-citeproc master.

**Comment by nh2** [comment]
Thanks, this is very useful. I'll try it on my next document!

**Comment by arve0** [comment]
Does this work for any CSL style? I'm using the [american medical association](https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl) style, and the syntax `[@statistisk_sentralbyra_folkemengde_2015]` with pandoc-citeproc v. 0.7.0.1 (installed today through cabal).

Latex output gives me: `\textsuperscript{\hyperref[ref-statistiskux5fsentralbyraux5ffolkemengdeux5f2015]{1}}`

And PDF:

![skjermbilde 2015-05-21 kl 17 39 03](https://cloud.githubusercontent.com/assets/4810521/7752536/51b19366-ffe0-11e4-8a8a-454023a3f842.png)

I have `\usepackage[unicode=true]{hyperref}` in my template, and links for figures works ok.
