### ISSUE TITLE
allow parsing of raw latex environments in HTML source

### ISSUE THREAD

**Issue by sowiso** [jgm/pandoc#1126]
Currently, the amsmath environments like \begin{align}  \end{align) are ignored (parsed as text) when the source is html+tex_math_dollars+tex_math_single_backslash. 
It would be nice if these were parsed as well.

**Comment by sowiso** [comment]
```
<p>Have a look at the environment hereunder</p>
\begin{aligned}x= 3 \\ y = 4 \end{aligned}
```

![image](https://user-images.githubusercontent.com/1487955/44589024-a5f5c000-a7b7-11e8-8bf7-43f58e807338.png)

**Comment by jgm** [comment]
If you put this inside $$..$$, it will be recognized as math.

**Comment by sowiso** [comment]
Hi John,

Yes, you're right, it works with the $$. The problem is that LaTeX does not accept it within the math mode. So `$$\begin{eqnarray}x= 3 \\ y = 4 \end{eqnarray}$$` does not work when compiling LaTeX, I think because both the $$ and the \begin{eqnarray} trigger math mode.
Therefore, the LaTeX output becomes unusable for creating a pdf.

**Comment by jgm** [comment]
One possible suggestion would be to try to recognize raw latex bits in the HTML document, and parse these as `RawBlock "tex"`.  These bits would then be passed through to latex and hence useable for creating a PDF.

This is definitely possible, in principle. I'd suggest making this behavior sensitive to the `raw_tex` flag so it can be turned on and off independently of `tex_math_dollars`.
