### ISSUE TITLE
Improve error messages about `pandoc --to pdf`

### ISSUE THREAD

**Issue by Toxaris** [jgm/pandoc#1155]
Pandoc can produce pdfs, but there is no pdf writer. Instead, in order to produce pdfs, you have to use the latex writer with an output file name that ends in `.pdf`. I understand the technical reasons for this behavior. Unfortunately, the user interface is not perfect if people accidently use a `--to pdf` flag:

```
`>echo hello | pandoc --to pdf
pandoc: Unknown writer: pdf

> echo hello | pandoc --to pdf -o hello.pdf
pandoc: cannot produce pdf output with pdf writer
```

The first error message suggests that pandoc cannot produce pdfs, and the second error message suggests that there is a pdf writer, but it is broken. Both error messages fail to help users achieve their goal, presumably to create a pdf with pandoc.

I see two options for how to improve the behavior:
1. These error messages could explain how to produce a pdf. Approximately:
   
   ```
   Unknown writer: pdf.
   To create a pdf with pandoc, use the latex writer and an output file name:
   pandoc --to latex -o filename.pdf
   ```
2. These invocations could try to produce a pdf, essentially "faking" a pdf writer. The first invocation would have to fail because there's no output file name:
   
   ```
   `>echo hello | pandoc --to pdf
   pandoc: Specify output file name for pdf with -o filename.pdf
   ```
   
   The second invocation would have the same as `pandoc --to latex -o hello.pdf`.

**Comment by mariussoutier** [comment]
I guess this got lost somewhere, because right now the error message is pretty confusing: `cannot produce pdf output from pdf`

**Comment by jgm** [comment]
@mariusoutier What are you doing to get that message, and what version of pandoc are you using?

**Comment by mariussoutier** [comment]
`pandoc --from markdown --to pdf --output gs.pdf` produces the confusing error message. `pandoc --from markdown --output gs.pdf` works as expected.

**Comment by jgm** [comment]
OK, I see.  This makes sense if you understand what's going on internally -- pandoc generates latex, html, or ms and converts that to a pdf -- but I agree it's confusing.
