### ISSUE TITLE
Citations with question mark not recognized

### ISSUE THREAD

**Issue by liob** [jgm/pandoc#1161]
Pandoc appears to have issues with citation keys containing question marks. This is actually a problem since Zotero exports keys containing question marks if no date is given.

citation_test.md:

```
Pandoc Citation Test
====================

Citations with questionmarks in their biblatex key do not work [@you_dont_see_me_????].

Without questionmark it works just fine [@now_you_do].
```

bibliography.bib:

```
@ARTICLE{you_dont_see_me_????,
  author = {No One},
  title = {You Don't See Me},
}

@ARTICLE{now_you_do,
  author = {No One},
  title = {You See Me},
}
```

```
pandoc --bibliography=bibliography.bib citation_test.md

pandoc-citeproc: reference you_dont_see_me_ not found
```

<h1 id="pandoc-citation-test">Pandoc Citation Test</h1>

<p>Citations with questionmarks in their biblatex key do not work <span class="citation">(<span class="citeproc-not-found" data-reference-id="you_dont_see_me_"><strong>???</strong></span>?)</span>.</p>

<p>Without questionmark it works just fine <span class="citation">(One)</span>.</p>

<div class="references">
<p>One, No. “You See Me.”</p>
</div>

**Comment by tarleb** [comment]
Should this be fixed in pandoc?  If yes, the way to go would probably be to change `citeKey` in `Text.Pandoc.Parsing` in a way that allows keys to end with escaped punctuation characters.

**Comment by jgm** [comment]
I'm not keen on treating `@foo?` differently from `@foo\?`  in the way I think you're suggesting.  Backslash escapes should have a single meaning, and this would give them  another meaning:  namely, "count this as part of the citation key and not as a regular question mark."

Perhaps we could introduce an alternative syntax for author-in-text citations, e.g. `[@@foo]` == `@foo` but `[@@foo?]` is possible.  But I'm not sure it's so important to support keys ending in arbitrary punctuation.
