### ISSUE TITLE
Modify CSS files to account for moved multimedia content when converting to EPUB

### ISSUE THREAD

**Issue by cgodefroy** [jgm/pandoc#1170]
When you add files other than images (such as video or audio) in a mdown document to convert to ePub, pandoc is as of yet unable to recognize them and add them to the final epub. Of course, there's no syntax for video or audio in Markdown...

This can probably scripted in a Makefile. I do already script the "add files" portion of the process, by adding a simple zip -r of my audio files to the epub.

I can also extract the content.opf from the epub and correct the manifest by adding manually all these files. And add the updated content.opf in a similar way.

But this lacks elegance.

Yes, I'm talking about another option that could be added to the command line to submit an xml file of files to be added to the manifest that Pandoc would be able to understand and process.

I totally lack the hs skills to do it myself... Otherwise I'd be sending a pull request.

**Comment by fedelibre** [comment]
indeed it seems fixed.. why is this issue still open?
