### ISSUE TITLE
Converting to markdown does not support webtex option.

### ISSUE THREAD

**Issue by shalecraig** [jgm/pandoc#1177]
I'd love to use webtex in building markdown from my LaTeX, but it looks like the option isn't there.

Specifically, I'd use webtex to generate images of LaTeX math, which is what it's used for in the html version.

Something I'd like to use:
`$ pandoc -s notes.tex --webtex -S -o notes.md`

What I've been using:
```
$ pandoc -s notes.tex --webtex -S -o notes.html && \
  pandoc -s notes.html -S -o notes.md && \
  rm notes.html
```

This seems like it works the way I want it to, but it's not optimal. What do you think about this feature?

**Comment by memeplex** [comment]
This would be very useful to convert markdown to markdown replacing latex with images, because currently github, gitlab and bitbucket ban markdown from their wikis. Support for math in wikis is a very popular demand.

**Comment by memeplex** [comment]
Thanks! Nevertheless, for people using older versions of pandoc, here is a filter to achieve the same using codecogs:

```
def codecogs(key, value, format, meta):
    if key == 'Math':
        inline = value[0]['t'] == 'InlineMath'
        latex = '\\inline ' + value[1] if inline else value[1]
        url = 'http://latex.codecogs.com/gif.latex?' + quote(latex)
        if format.startswith('markdown'):
            return RawInline('markdown', '![](%s)' % url)
        elif format == 'html':
            return RawInline('html', '<img src="%s"></img>' % url)
```
