### ISSUE TITLE
Highlight Lines (hl_lines)

### ISSUE THREAD

**Issue by anderflash** [jgm/pandoc#1183]
Is this fenced_code_block feature supported by Pandoc? If yes, how can I do?
It's a great feature for tutorials, to show what code is modified between tutorials. Or to teach step-by-step, incrementing new code over old one.
I tried to put `hl_lines`, but it doesn't work.
Thanks.

**Comment by mb21** [comment]
If this is still an issue, it should be raised at https://github.com/jgm/skylighting/
