### ISSUE TITLE
Fallback to data-dir for URL options.

### ISSUE THREAD

**Issue by dashed** [jgm/pandoc#1191]
If an option has option for `URL`, it'd be nice if pandoc somehow includes `--data-dir` in its 'path' for searching the appropriate file if it's not available 'locally'.

Unsure if pandoc seems to be doing this. But, I find this to be potentially useful for options such as `--css` and `--mathjax`.  So the following would search via `~/.pandoc/`:

`pandoc --css=style.css --mathjax=js/mathjax.min.js -t html5 file.md`

**Comment by ickc** [comment]
:+1:

I think pandoc should embed the CSS if it found the "URL" in data-dir. I think the current behavior is to link to it which will be useless if it is local (and not used locally).

I think there's a need for data-dir to do more than currently did. As shown in #3127 and #3138 (indirectly related).

**Comment by jgm** [comment]
+++ ickc [Oct 02 16 14:51 ]:
>   👍
>
>   I think pandoc should embed the CSS if it found the "URL" in data-dir.
>   I think the current behavior is to link to it which will be useless if
>   it is local (and not used locally).

You can always use --self-contained if you're not going to
provide the CSS on the server.

**Comment by ickc** [comment]
You're right. I forgot about it. This gives me an idea on another way to write template fragments. Thanks!

**Comment by tarleb** [comment]
Pandoc 2.0 introduced the `--resource-path` option which allows to control the search path, which is more fine-grained than checking the data-dir. Also, always checking the data-dir could turn into security issue.
