### ISSUE TITLE
PDF: temp directory not being removed in Windows

### ISSUE THREAD

**Issue by timtylin** [jgm/pandoc#1192]
The PDF builder currently creates a temporary directory to render a pdf from LaTeX source, then uses ByteString.Lazy.readFile to pipe the file back to the main executable for output IO. This creates process ownership of the compiled pdf file until the end of the main IO thread.

However, the PDF builder also attempt to remove the temp directory upon exit. This will fail in Windows, as it does not allow removal of a file that is currently owned by a process. Therefore, using the PDF builder in Windows will always result in a leftover temporary directory that needs to be manually removed.

Current ideas to fix this:
- Read-out the whole file first using strict ByteString, remove the temp directory, then create another lazy ByteString on top of the strict one to pipe it back to `main`.
- _TBD_

This issue is current as of c3a2fc643cad7a5d75e0c576aa029a7ec51b8eed

**Comment by Arty2** [comment]
The same issue persists in version 1.15.0.6 on Windows 10.
Anything I could do to help debug?

**Comment by jgm** [comment]
Can you give a test case that might enable us to reproduce the problem?  As simple as possible, with the exact input and commands used.

**Comment by Arty2** [comment]
Unfortunately, I cannot replicate it every time, but here is the command used:

`pandoc -s -S -from markdown_mmd+yaml_metadata_block -o "myfile.pdf" "myfile.md" --latex-engine=xelatex --template=handout.tex`

The input file doesn't seem important; I've also replicated it using empty files.
The directory left behind is empty, and is named like so: `tex2pdf.7644`

An important factor that may be contributing to this issue, is that the working directory lies **inside Dropbox**. It is possible that Dropbox locks the directory for a split second and pandoc is not allowed to delete it. Perhaps it should check a second time?

**Comment by jgm** [comment]
+++ Heracles Papatheodorou [Aug 16 15 07:23 ]:
>   Unfortunately, I cannot replicate it every time, but here is the
>   command used:
>
>   pandoc -s -S -from markdown_mmd+yaml_metadata_block -o "myfile.pdf"
>   "myfile.md" --latex-engine=xelatex --template=handout.tex
>
>   The input file doesn't seem important; I've also replicated it using
>   empty files.
>   The directory left behind is empty, and is named like so: tex2pdf.7644
>
>   An important factor that may be contributing to this issue, is that the
>   working directory lies inside Dropbox. It is possible that Dropbox
>   locks the directory for a split second and pandoc is not allowed to
>   delete it. Perhaps it should check a second time?

So, you can't replicate it outside of Dropbox?

**Comment by Arty2** [comment]
That is correct. I’m sorry for not being more clear in my first post.

**Comment by jgm** [comment]
I'm just using a standard function from the temporary
library, `withTempDirectory`.  It's this that deletes the
directory after use.

The definition of `withTempDirectory` is:

```
withTempDirectory :: (MonadMask m, MonadIO m) =>
                     FilePath -- ^ Temp directory to create the directory in
                  -> String   -- ^ Directory name template. See 'openTempFile'.
                  -> (FilePath -> m a) -- ^ Callback that can use the directory
                  -> m a
withTempDirectory targetDir template =
  Exception.bracket
    (liftIO (createTempDirectory targetDir template))
    (liftIO . ignoringIOErrors . removeDirectoryRecursive)

ignoringIOErrors :: MonadCatch m => m () -> m ()
ignoringIOErrors ioe =
  ioe `Exception.catch` (\e -> const (return ()) (e :: IOError))
```

So, one thing we could try would be modifying
`src/Text/Pandoc/Shared.hs` as follows:
instead of using `withTempDirectory`, use a variant constructed
from the above ingredients, perhaps inserting a delay or retry?
That seems messy, though.

I had to remind myself why we no longer use `withSystemTempDirectory`
on Windows.  Here's the original commit that changed that:
26fefa040a7046bbe00e3caf2597f33e65af5986.

We could improve things slightly by using `withSystemTempDirectory`
when the result of `getTemporaryDirectory` does not contain
tildes.  (That should be the case if your username is short.)

+++ Heracles Papatheodorou [Aug 16 15 07:32 ]:

**Comment by dvanclev** [comment]
Having the same problem (in Dropbox).

**Comment by tolot27** [comment]
I run into this situation some time pandoc fails to compile to build pdf.

**Comment by mb21** [comment]
From https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/PDF.hs#L103;

      -- With context and latex, we create a temp directory within
      -- the working directory, since pdflatex sometimes tries to
      -- use tools like epstopdf.pl, which are restricted if run
      -- on files outside the working directory.

If your working dir is synced with dropbox or similar, yes, you might run into a race condition where dropbox restores the files after pandoc deleted them. You could always write a wrapper script that calls `pdflatex` in another directory.

**Comment by jgm** [comment]
Thinking again about this, I think we should try to get a better fix.  It's a really common thing to want to run pandoc in a dropbox or other synced directory.

It seems there are two issues, one involving Windows path names (https://github.com/jgm/pandoc/commit/26fefa040a7046bbe00e3caf2597f33e65af5986) and the other involving tools like epstopdf.pl (see your comment above).

The first could be worked around, at least with short usernames, in the way described above:

> We could improve things slightly by using withSystemTempDirectory when the result of getTemporaryDirectory does not contain tildes. 

Another possibility would be a command-line option.

**Comment by jgm** [comment]
For the epstopdf.pl issue see cd51983afe08697d627ecb091d42e40d897470b9

**Comment by jgm** [comment]
From https://tex.stackexchange.com/questions/252284/epstopdf-and-graphicspath-with-pdflatex:

>  Absolute directories are forbidden (unless listed in TEXMFOUTPUT) in the default restricted shell escape mode.

Looks like it might suffice to set TEXMFOUTPUT to the temp directory.  But we need a test case that includes an eps file.
