### ISSUE TITLE
Suport of TABLE (natural tables) in $raw_tex extension

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#1222]
Hi,

Can you provide the [TABLE](http://wiki.contextgarden.net/TABLE) syntax in raw_tex extension:

```
\placetable{Caption}
{\bTABLE
\bTR \bTD One \eTD \bTD two \eTD \eTR
\bTR \bTD One \eTD \bTD two \eTD \eTR
\eTABLE}
```

**Comment by mb21** [comment]
The example actually works now with `pandoc -f markdown -t context`.
