### ISSUE TITLE
DocBook: admonition-like environments

### ISSUE THREAD

**Issue by oncletom** [jgm/pandoc#1234]
Hello,

Docbook has a handy way to create text blocks. The current way Pandoc translates them makes it very difficult to recover them through XML post-processing.
# Text Flow
## Asciidoc

``` adoc
Regular paragraph.

[TIP]
====
.Title of my tip
A paragraph inside a tip.
====

Another regular paragraph.
```
## DocBook

``` docbook
<simpara>Regular paragraph.</simpara>
<tip>
  <formalpara>
    <title>Title of my tip</title>
    <para>A paragraph inside a tip.</para>
  </formalpara>
</tip>
<simpara>Another regular paragraph.</simpara>
```
## OpenDocument (from pandoc)

``` opendocument
<text:p text:style-name="Text_20_body">Regular paragraph.</text:p>

<text:p text:style-name="P11"><text:span text:style-name="T279">Tip</text:span></text:p>
<text:p text:style-name="P11"><text:span text:style-name="T282">Title of my tip</text:span>.<text:line-break/>A paragraph inside a tip.</text:p>

<text:p text:style-name="Text_20_body">Another regular paragraph.</text:p>
```
# Ideal solution

``` opendocument
<text:p text:style-name="Text_20_body">Regular paragraph.</text:p>

<text:h text:style-name="ADMONITION11 ADMONITITION-TIP">Title of my tip</text:h>
<text:p text:style-name="ADMONITION11 ADMONITITION-TIP">A paragraph inside a tip.</text:p>

<text:p text:style-name="Text_20_body">Another regular paragraph.</text:p>
```

Something like that.

How feasible is it? It would help a lot for the code blocks as well, as they share a very similar logic (which is going to be a next issue).

Thanks very much :-)

**Comment by mb21** [comment]
Is this about how the docbook `<tip>` element is parsed? With current pandoc, it's parsed as a blockquote, which seems as good as we can do with our simplistic document model. Thus closing this issue. Please clarify if this is still an issue.

**Comment by jgm** [comment]
Actually, now that we have native Divs, we could parse tip as a div with an attribute.

Compare the way we now handle admonitions in RST.  So I think we should reopen this and revisit the handling of these environments in both the docbook reader and the docbook writer.

**Comment by vinipsmaker** [comment]
Is there an associated issue to how PDF/ePUB/other formats consume these translated-to-classed-div blocks?
