### ISSUE TITLE
Latex: Ordered list/enumerate FAILS with "missing \item"

### ISSUE THREAD

**Issue by eins78** [jgm/pandoc#1264]
I've had tons of problems with this in the past. All the existing issues I found (also on the mailing list) are about template mismatches etc.
Now it happened again, with a freshly installed `pandoc 1.12.3`, `MacTex` and a very minimal example.
Is this a bug or am I doing something completely wrong?

Input: `test.md`

``` markdown
# title

1. foo
2. bar
```

Command:
`pandoc -i test.md -f markdown -s -o test.pdf`

Error:

```
pandoc: Error producing PDF from TeX source.
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.56   f
```

This is the relevant generated `tex` source:

``` tex
\begin{enumerate}[<+->]
\def\labelenumi{\arabic{enumi}.}
\itemsep1pt\parskip0pt\parsep0pt
\item
  foo
\item
  bar
\end{enumerate}
```

It does compile if i remove the argument after enumerate:

``` tex
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\itemsep1pt\parskip0pt\parsep0pt
\item
  foo
\item
  bar
\end{enumerate}
```

**Comment by lalthomas** [comment]
@eins78  Thanks ..you just saved me :+1:
