### ISSUE TITLE
theme variable, when used with revealjs, causes the web browser to freeze (at least on Firefox)

### ISSUE THREAD

**Issue by zackp30** [jgm/pandoc#1276]
When using `-V theme=solarized` with the revealjs writer, the browser seems to freeze.
This was, however, fixed by utilizing `--css ./reveal.js/css/theme/solarized`.

**Comment by GreenZapdos** [comment]
This bug is fixed at https://github.com/jgm/pandoc-templates/pull/77

**Comment by devurandom** [comment]
This should be fixed by 066b307b63fdf4d92a769f13f9df97aa47b11644 and 260f7876a2059c702164ee5b3e9787515cbd95dd (in the tree already).

Your theme-path modification is still missing, though unrelated.

**Comment by zackp30** [comment]
I no longer use reveal.js (I use deckjs with my own template). But I'll close this as it does seem to be fixed! Thanks!
