### ISSUE TITLE
Support for anchors

### ISSUE THREAD

**Issue by bgamari** [jgm/pandoc#1299]
It would be nice if the document AST would have some way of representing anchor points. This would enable features like #1117 and hyperlinked section, table, and figure references (proposed in #813).

**Comment by marijnh** [comment]
What does an empty span element with an identifier look like? Using two backticks followed by `{#identifier}` doesn't parse. Or are you talking about an html `<span>`?

After moving from AsciiDoc to Pandoc, almost everything is great, but the inability to succinctly insert anchors at any position (I'm currently writing `<a name="foo"></a>` a lot) does really cause problems. It's verbose, and since Pandoc doesn't know these are identifiers, I can't link them just by saying `[foo]`, for example.

**Comment by jgm** [comment]
Use `<span id="foo"></span>`, and it will be parsed into a
native pandoc Span element.  So far there is no non-HTML
syntax for this.  It would be better, I agree, if there
were, and there are various alternatives.  One that I like,
and am considering for CommonMark, is overloading empty
reference link definitions:

```
[foo]:

Some text here.

See [the text above][foo].
```



+++ Marijn Haverbeke [Sep 08 15 05:16 ]:

**Comment by neopaf** [comment]
we also want this

**Comment by mb21** [comment]
You can already reference all elements that have attributes (by giving them an id) and there's a discussion to [add attributes to all elements](https://github.com/jgm/pandoc/issues/684).

Meanwhile, pandoc's markdown got its native span syntax, for an empty one:

    []{#myid}

**Comment by Pzixel** [comment]
@mb21 could you be in more details pls? I'm trying to convert markdown to rst, and anchors should be translated into `:ref:` attributes. This is my test page (with syntax you proposed):

```md

- [feeAmountTickSpacing(uint24 fee)][]{#IUniswapV3Factory-feeAmountTickSpacing-uint24-}

# Function `feeAmountTickSpacing(uint24 fee) → int24` {#IUniswapV3Factory-feeAmountTickSpacing-uint24-}

A fee amount can never be removed, so this value should be hard coded or cached in the calling context
```

But it gets rendered into

```rst
-  [feeAmountTickSpacing(uint24
   fee)][]{#IUniswapV3Factory-feeAmountTickSpacing-uint24-}
.. _IUniswapV3Factory-feeAmountTickSpacing-uint24-:

Function ``feeAmountTickSpacing(uint24 fee) → int24``
=====================================================

A fee amount can never be removed, so this value should be hard coded or
cached in the calling context
```

Which is invalid syntax.

**Comment by tarleb** [comment]
@Pzixel if you found a bug, please open a new issue. Questions are best send to the pandoc-discuss mailing list. Commenting on old issues is generally frowned upon, as it will notify everybody who participated in this issue.
