### ISSUE TITLE
--chapters option doesn't get triggered when documentclass is set via yaml

### ISSUE THREAD

**Issue by ivoanjo** [jgm/pandoc#1301]
The --chapters option can be triggered by using `pandoc -V documentclass=memoir` or `pandoc -V documentclass=book`. But the same behavior is not achievable if the `documentclass` is set via a yaml block.

While it could be argued that yaml metadata should be treated differently, I believe this should be considered a bug. I have some generic scripts to generate pdf from md, and having this in the yaml block would really help avoiding grepping to discover if chapters should be user or not.

(In fact, I started used memoir before knowing that `--chapters` existed by using `\chapter{}` instead, and only afterwards discovered the option and that it wasn't triggered because I was setting `documentclass` via yaml, as I always do.)

```

---
documentclass: memoir

---

# This should be a chapter!

Hello, world!
```

**Comment by mb21** [comment]
This seems to be resolved?

    ~ pandoc --top-level-division=chapter -t latex
    ---
    documentclass: memoir
    ---

    # This should be a chapter!
    ^D

    \hypertarget{this-should-be-a-chapter}{%
    \chapter{This should be a chapter!}\label{this-should-be-a-chapter}}
