### ISSUE TITLE
[Request] couple aliases for highliting fenced code

### ISSUE THREAD

**Issue by vovkkk** [jgm/pandoc#1318]
In order to support GitHub Markdown, Pandoc should recognize c++ as cpp, and objective-c as objectivec.

Examples:
- c++
  
  ``` c++
  #define default_value 10
  using namespace std;
  ```
- cpp
  
  ``` cpp
  #define default_value 10
  using namespace std;
  ```
- objective-c
  
  ``` objective-c
  //  faceAwarenessClipping
  #import "AppDelegate.h"
  ```
- objectivec
  
  ``` objectivec
  //  faceAwarenessClipping
  #import "AppDelegate.h"
  ```

[plain](https://gist.githubusercontent.com/vovkkk/f30db14f23531a8a6a92/raw/98d5ee8fd18cb59600a4f774d54ae6500604a6a2/c.md)

**Comment by arthurlogilab** [comment]
Hi, I'm trying to get jinja highlighting for the following ReST code converted to latex (then to PDF) : 

```

.. code-block:: jinja

  {% for user in users %}
    - name : user
  {% endfor %}
```

replacing jinja by djangotemplate show a bit more color. 

Any reason why, if pygments is used, this is not supported ? 

Should I file a new issue ?

**Comment by tarleb** [comment]
Pandoc uses [highlighting kate](https://github.com/jgm/highlighting-kate) for syntax highlighting. Pygments isn't used by default. Both highlighters use different language keywords, which is why `jinja` won't work.

If you need your highlighting to be done by Pygments, you might want to look at [pandoc-with-pygments](https://github.com/esc/pandoc-with-pygments) and similar projects.

**Comment by arthurlogilab** [comment]
@tarleb thanks for the answer. The documentation probably could be updated then : http://pandoc.org/README.html says pygments is the default highlighter. Do you think it would work with --highlight-style=pygments ? 

Requested jinja templating on kate and will take a look at pandoc-with-pygments

**Comment by tarleb** [comment]
Whoops, I'm probably wrong, then. Last time I checked it used hightlighting kate, but this might have changed without me noting.

**Comment by jgm** [comment]
+++ Arthur Lutz [May 22 15 08:28 ]:
>   [1]@tarleb thanks for the answer. The documentation probably could be
>   updated then : [2]http://pandoc.org/README.html says pygments is the
>   default highlighter. Do you think it would work with
>   --highlight-style=pygments ?

Pandoc always uses highlighting-kate, never pygments.
`--highlight-style` selects the color scheme.  One of
highlighting-kate's color schemes is called `pygments`,
because it imitates pygments' default color scheme.  (And
that's the default.)

**Comment by arthurlogilab** [comment]
@jgm thanks for the clarification. Maybe the documentation could include this information ? And a word of warning about code-block names that are not the same between pygments and kate.
