### ISSUE TITLE
Document conversion fails over NFS mounted drive using RStudio knit function

### ISSUE THREAD

**Issue by kdaily** [jgm/pandoc#1326]
When knitting from RStudio (0.98.738) on files residing on an NFS-mounted drive, the first time is successful. All subsequent attempts to knit fail as below. If all files are moved to a local directory, knitting is sucessful every time.

```
output file: report.knit.md
```

```
/usr/lib/rstudio/bin/pandoc/pandoc report.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output report.html --filter /usr/lib/rstudio/bin/pandoc/pandoc-citeproc --section-divs --smart --self-contained --template /usr/lib64/R/library/rmarkdown/rmd/h/default.html --variable jquery:/usr/lib64/R/library/rmarkdown/rmd/h/jquery-1.10.2 --variable bootstrap:/usr/lib64/R/library/rmarkdown/rmd/h/bootstrap-3.0.3 --variable theme:/usr/lib64/R/library/rmarkdown/rmd/h/bootstrap-3.0.3/css/bootstrap.min.css --no-highlight --variable highlightjs=/usr/lib64/R/library/rmarkdown/rmd/h/highlight --mathjax --variable mathjax-url:https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML 
```

```
pandoc: report.html: hClose: does not exist (Host is down)
Error: pandoc document conversion failed
Execution halted
```

**Comment by stroobandt** [comment]
I ran into the same error using `pandoc` **without Rstudio** on a remote drive.
Generating the PDF locally works.
The error reminds me of a [clock skew error](https://stackoverflow.com/questions/3824500/compiling-c-on-remote-linux-machine-clock-skew-detected-warning).
Using `touch *` did not resolve the problem though.

**Comment by stroobandt** [comment]
Both the input and output file are in the same remote folder.
A solution were for `pandoc` to generate the output in some fail safe local temporary directory (e.g. /tmp) and then copy the output file to the final remote destination directory on the network drive.

This `pandoc` bug should be reopened. I frequently run into it and apart from being obscure, it is pretty annoying.

**Comment by stroobandt** [comment]
For the sake of completeness, I have to state that I am running `pandoc` from a `makefile` in the same remote CIFS directory. Here is a simplified copy of the original `makefile`:
```
SHELL := /bin/bash
NAME := $(basename $(wildcard *.md))

all: $(NAME).pdf

$(NAME).pdf: $(NAME).md
	pandoc --smart --output=$@ --template="$$HOME/texmf/pandoc.templates/letter.tex" $<
	xdg-open $@
```

I resolved my issue by letting `pandoc` generate its PDF output in `/tmp`, before moving it back to the remote folder which contains the input file and the `makefile`:
```
SHELL := /bin/bash
NAME := $(basename $(wildcard *.md))

all: $(NAME).pdf

$(NAME).pdf: $(NAME).md
	pandoc --smart --output="/tmp/$@" --template="$$HOME/texmf/pandoc.templates/letter.tex" $<
	mv "/tmp/$@" $@
	xdg-open $@
```
I hope this helps others who occasionally need to run `pandoc` in a remote folder.

**Comment by stroobandt** [comment]
jgm/pandoc#1326

**Comment by jgm** [comment]
I can reopen this, but I'm really not sure what to do about it.
It sounds more like a problem/limitation with cifs than a problem with pandoc itself.
A workaround might be creating the output file in /tmp and copying it, as you suggest.  But (a) this creates unnecessary complexity for people not on cifs, and (b) on Windows we don't have this kind of reliably available temp directory.

**Comment by MBarrows20** [comment]
Still experiencing this issue as of today. Any word on fixing this soon?

**Comment by agusmba** [comment]
(Just my 2c)

As jgm said, it sounds more like a problem with the filesystem itself.

Even microsoft applications do not deal with these things completely, I just lost a few hours of scratching my head with a weirdly malfunctioning import from excel to project, and it was all due to the excel file being on a remote mapped location (as soon as I copied it to my local disk it all worked).

So I wouldn't pin my hopes on this being solved within pandoc
