### ISSUE TITLE
readerLatex produces error on \caption optional argument

### ISSUE THREAD

**Issue by aspnes** [jgm/pandoc#1335]
LaTeX allows `\caption` to have an optional short title, e.g.

``` latex
\caption[Short caption]{This caption is too long to fit in the list of figures}
```

The LaTeX reader doesn't like this.  The fix is trivial, add `skipopts *>` to the relevant line in `Readers/LaTeX.hs`:

```
diff --git a/src/Text/Pandoc/Readers/LaTeX.hs b/src/Text/Pandoc/Readers/LaTeX.hs
index c3c0ba4..6b59589 100644
--- a/src/Text/Pandoc/Readers/LaTeX.hs
+++ b/src/Text/Pandoc/Readers/LaTeX.hs
@@ -305,7 +305,7 @@ blockCommands = M.fromList $
   , ("item", skipopts *> loose_item)
   , ("documentclass", skipopts *> braced *> preamble)
   , ("centerline", (para . trimInlines) <$> (skipopts *> tok))
-  , ("caption", tok >>= setCaption)
+  , ("caption", skipopts *> tok >>= setCaption)
   , ("PandocStartInclude", startInclude)
   , ("PandocEndInclude", endInclude)
   , ("bibliography", mempty <$ (skipopts *> braced >>=
```

**Comment by katrinleinweber** [comment]
@aspnes Do I understand correctly, that there is no way to define a short figure caption for the list of figures in Markdown syntax and transfer it into LaTeX? I'm looking for a way to having figure caption and legend in the figure environment together, but displaying only the caption in a list of figures.

**Comment by aspnes** [comment]
From what I remember neither pandoc's Markdown syntax nor its internal data structure supports short captions.  So adding these would require bigger changes than I proposed above.

**Comment by katrinleinweber** [comment]
OK, thanks for confirming. I'll convert the MD figures into LaTeX then. There's [a set-up](https://github.com/katrinleinweber/scientific-markdown/blob/master/makefile) that passes the commands through :-)
