### ISSUE TITLE
Nested lists don't work in markdown

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#137]
<b>What steps will reproduce the problem?</b>
1. Create a document with a nested list in markdown:
{{{
- a
  - should be nested 
- but it's not
  }}}
- Convert it to any format, I checked html and mediawiki

<b>What is the expected output? What do you see instead?</b>

The output is not a nested list. The nested element appears at the same 
level as the other elements.

<b>What version of the product are you using? On what operating system?</b>

1.4 on windows.

Google Code Info:
Issue #: 229
Author: paul.chi...@gmail.com
Created On: 2010-04-01T15:19:28.000Z
Closed On: 2010-04-01T22:46:16.000Z

**Comment by mhbrown** [comment]
I was just struggling with nested lists a bit and upon Googling, came across this resolved issue and the comment I liked above from @jgm was the answer for me.

I think https://guides.github.com/features/mastering-markdown/ should be updated to say indentation should be 4 spaces or a tab.

Also, the examples for nested lists use 2 spaces in the [Lists example](https://guides.github.com/features/mastering-markdown/#examples), but the Lists section on the page shows 3 spaces. These should both probably use 4 spaces to further clarify.

Thanks!
-Martin

**Comment by jgm** [comment]
@mhbrown - yes, absolutely.  The advice in the "mastering markdown" page you link to is very bad.  The only safe advice that will work reliably across all Markdown implementations is to use a 4-space indent.  A 2-space indent 

See <http://johnmacfarlane.net/babelmark2/?normalize=1&text=+-+a%0A+++-+b%0A+++++-+c%0A+++++++-+d%0A> for an illustration.

The situation is even worse for ordered lists: <http://johnmacfarlane.net/babelmark2/?normalize=1&text=+1.+a%0A+++2.+b%0A+++++3.+c%0A+++++++4.+d%0A>.  Only one implementation (not the one GitHub uses) consistently honors a 2-space indent.

Please give feedback to GitHub to change their misleading guide.
