### ISSUE TITLE
Large width tables

### ISSUE THREAD

**Issue by YOUR1** [jgm/pandoc#1373]
Hi;

Some how our users seems to create rather long tables. 

Example table:
<table class="wikitable" style="max-width:300px;width:300px;" width="300px">
<tbody><tr>
<td>Wat</td>
<td>Doel</td>
<td>Omschrijving
</td></tr>
<tr>
<td>Beleidsstukken</td>
<td>kaderstellend</td>
<td>vertaling van Fontys strategie en beleid naar IT-beleid
</td></tr>
<tr>
<td>Fontys architectuur</td>
<td>kaderstellend</td>
<td>Concreet beoordelingskader om toe te passen bij nieuwe initiatieven
</td></tr>
<tr>
<td>Project Start Architectuur</td>
<td>Ondersteuning besluitvorming en kaderstellend</td>
<td>Impactanalyse en richtlijnen meegeven aan het project
</td></tr>
<tr>
<td>Projectportfolio</td>
<td>Ondersteuning besluitvorming</td>
<td>Overzicht van onderhanden projecten evt gewogen op business value, risico en kosten om de impact op resources te zien en (her)prioritering uit af te leiden
</td></tr>
<tr>
<td>PID / Busines case</td>
<td>Ondersteuning besluitvorming</td>
<td>Helder weergeven van doelstelling en business case in hoofdlijnen
</td></tr>
<tr>
<td>Architectuursite</td>
<td>Informerend</td>
<td>Delen van architectuurkaders, good practices, adviezen, besluitvorming. Overzicht van Fontys architectuur, bedrijfsfuncties, procesen  etc. Overzicht van de applicaties die de Fontys infrastructuur raken om hergebruik te bevorderen en impact op applicatielandschap te beoordelen bij wijzingen
</td></tr></tbody></table>

PDF Outcome:
![screen shot 2014-06-25 at 17 22 10](https://cloud.githubusercontent.com/assets/3681016/3387314/d89990bc-fc7c-11e3-9477-66da916efa80.png)

It seems the reader is ignoring the width="" and/or style="" properties.

**Comment by jgm** [comment]
Sorry, `<cols>` is the only way.
