### ISSUE TITLE
Pass \newcommand etc to MathJax?

### ISSUE THREAD

**Issue by dubiousjim** [jgm/pandoc#1393]
Feature request: When writing to HTML with --mathjax, perhaps any `\newcommand`s or `\renewcommand`s should be passed directly to MathJax, inside a block like:

```
<div style="display:none" class="math">\( <definitions go here> \)</div>
```

MathJax can expand all the macro definitions Pandoc does (and more), and moreover can do so without triggering the issues discussed in [issue 1390](https://github.com/jgm/pandoc/issues/1390). (Though this would not be a complete solution to those issues, only one for HTML/MathJax output.)

**Comment by rkingsbury** [comment]
I suspect this is the same issue, but I'm not positive....

I'm processing a Markdown document containing inline math to .pdf and .docx. If I only include symbols, e.g.

```
$$\alpha$$
```

Then I get the proper output in both formats. However, if I include any kind of LaTex/MathJax directive, e.g.:

```
$$1\over\alpha$$
```

Then the equation is passed as regular text to the .docx, but still renders properly in the .pdf output. 

What can be done to get consistent output here?

**Comment by jgm** [comment]
The problem is `\over`.  this is a TeX primitive, and
the texmath library (which really focuses on LaTeX math)
doesn't understand it.  Try using

    $$\frac{1}{\alpha}$$

which is the recommended LaTeX equivalent.

+++ Ryan S. Kingsbury [Aug 21 15 13:24 ]:

**Comment by rkingsbury** [comment]
Thanks @jgm! That seems to have sorted out the problem with .docx export. Now I'm looking at the .odt export, though, and I'm still having problems.

Keeping with your example, if I export this markdown:
```
 $$\frac{1}{\alpha}$$
```
to .odt, the output  is:
```
$$ \frac{1}{\alpha} \qquad (1)$$
```
Where is the \qquad coming from?

**Comment by jgm** [comment]
I'm not sure what is happening with your ODT.  Pandoc creates an ODT with the following code for the formula:

    <math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><mfrac><mn>1</\
mn><mi>α</mi></mfrac></math>

This is mathml.  It may be that different word processors have different ways of rendering this.  In your case, it looks as if the word processor added a formula number, separated from the formula by a space, and rendered the whole thing as raw LaTeX.  But the quad wasn't added by pandoc.

I note the changelog entry from pandoc 1.12.3:

  * ODT writer:  Use mathml for proper rendering of formulas.
    Note:  LibreOffice's support for this seems a bit buggy.  But
    it should be better than what we had before.

**Comment by jgm** [comment]
I think this issue can now be closed.  Pandoc can now do macro expansion with `\let`, `\def`, `\newenvironment`, `\renewenvironment`, `\newcommand`, etc.
