### ISSUE TITLE
Wrong Path variable after .msi Installation (Windows 7)

### ISSUE THREAD

**Issue by jpdus** [jgm/pandoc#1403]
The installation routine for pandoc-1.12.4.2-1-windows.msi added "C:\Users\jp\AppData\Local\Pandoc\" to Path instead of "C:\Users\jp\AppData\Local\Pandoc" - I needed to remove the trailing backslash manually to get it working.

Windows 7, 64bit

**Comment by bencaldwell** [comment]
I can confirm that this bug exists for pandoc 1.13.2 on Windows x64.

After installation the *user* path variable has *C:\Users\bencaldwell\AppData\Local\Pandoc\* appended (with the backslash). My pandoc install didn't work, even after restarting the PC.

When I remove the trailing backslash to give a path variable with *C:\Users\bencaldwell\AppData\Local\Pandoc* pandoc starts working.

**Comment by jgm** [comment]
@bencaldwell, if you add the backslash back, does pandoc stop working?

@sheremetyev - is there any way to revise the script so that the trailing backslash is not added?

**Comment by writage** [comment]
@jgm - this can be done by assigning APPLICATIONFOLDER to another property and removing trailing slash in a "custom action".

But I’m not sure the problem is in slash — trailing slash is valid, even required in some cases(e.g. “C:\”). We need a way to reproduce the problem reliably before fixing it, I think.

**Comment by bencaldwell** [comment]
@jgm when I add the backslash back in to the path pandoc continues to work, even after restart.

**Comment by yaciben** [comment]
Hi all,
Had the same issue on Windows 8.1: pandoc not starting in windows cmd and powershell.
How I soved this: Restarted Windows then opened the Environment variables box (Advanced Settings), checked that the pandoc path is properly set (it contains also a trailing backslash), clicked OK without making any change.
HTH.

**Comment by jgm** [comment]
Does this help?
https://support.microsoft.com/en-us/kb/104011
@sheremetyev 
IS there a way to get the wix-produced msi to broadcast a WM_SETTINGCHANGE message to all windows in the system?

**Comment by writage** [comment]
This one, I think: http://wixtoolset.org/documentation/manual/v3/customactions/wixsettingchange.html

**Comment by jgm** [comment]
I believe this is resolved now.  If not, please re-open.

**Comment by DiwakaranD** [comment]
i cant able to open "Notepad" and also  "start task manager" in windows 7,  so please help me.
