### ISSUE TITLE
expose a way to see what variables appear in a pandoc template

### ISSUE THREAD

**Issue by cartazio** [jgm/pandoc#1404]
I've a few tools i'd like to be able to build on top of pandoc, and as part of that I want to provide a little bit of baked in declarative experience for template composition. To do so requires knowing what the variables are for template splices (along with perhaps some additional info about how the splice appears) so that templates can be composed in a somewhat intelligent way!

currently in [Text.Pandoc.Templates](http://hackage.haskell.org/package/pandoc-1.12.4.2/docs/Text-Pandoc-Templates.html) theres

``` haskell

compileTemplate :: Text -> Either String Template
```

I'd propose adding something like roughly

``` haskell

compileTemplateWithDeps :: Text -> Either String (Template,TemplateDeps)

type TemplateDeps =  [String]
-- the variables that appeared in the template!
```

though perhaps a richer type for `TemplateDeps` is in order.

this might not be quite the right approach, but proposing it as a strawman.

NB: i could totally hack out a 3rd party emulation of this, but i'm not sure how stable that would be! (though it'd be a reasonable choice to take)

**Comment by mb21** [comment]
This belongs to https://github.com/jgm/doctemplates/...

**Comment by jgm** [comment]
I agree, the relevant code has been moved to doctemplates.
If this feature is still wanted, it should be implemented there.
