### ISSUE TITLE
Better document how Pandoc checks for csquotes in LaTeX template

### ISSUE THREAD

**Issue by dubiousjim** [jgm/pandoc#1406]
This is a low-priority recommendation for a documentation tweak. Currently the Pandoc docs say, under the heading [Smart punctuation](http://johnmacfarlane.net/pandoc/README.html#smart-punctuation):

> Note: if your LaTeX template uses the csquotes package, pandoc will detect automatically this and use \enquote{...} for quoted text.

It looks like Pandoc is just detecting the presence of something like `\usepackage{csquotes}` in the template (or just its preamble?). That is not the same as the template *using* `csquotes`. For example, if I have this in my template:

    \iffalse
    \usepackage{csquotes}
    \fi

Pandoc will still output quotations in the `csquotes` style. So perhaps the docs should read instead: "...if `\usepackage{csquotes}` is in your template's preamble...". If the user wants to include that package only conditionally, they're on their own.

**Comment by adunning** [comment]
I made an attempt to improve this in #2445.
