### ISSUE TITLE
Groff man reader

### ISSUE THREAD

**Issue by djmattyg007** [jgm/pandoc#1484]
Is there a reason why pandoc doesn't support conversions from groff manpages to other formats? What would be involved in building a parser?

**Comment by saper** [comment]
That under "manpage" people mean usual two different formats: one the older man(7) macro set, which is pretty "raw" and suitable for the output format (as supported by pandoc) and the newer mdoc(7) macro set, which is more structure and should be easier to implement as the input format.

**Comment by svnpenn** [comment]
@jgm groff is pretty awful at converting to HTML. Notably, tables get converted to images:

http://unix.stackexchange.com/q/320826/howto-show-tables-in-man-pages-converted-to-html

**Comment by Yanpas** [comment]
I'm interested in this feature. Particularly for https://github.com/Yanpas/mandocset project (generating [dash](https://kapeli.com/dash) documentation). Maybe I will open PR in the nearest future. Are parser-combinators allowed in this project (e. g. Parsec as a dependency)?

**Comment by mb21** [comment]
@Yanpas yes, parsec is already a dependency.

P.S. https://github.com/jgm/pandoc/pull/3994/files together with https://github.com/jgm/pandoc/pull/4002 might be a good template for a pull request.
