### ISSUE TITLE
Dumb punctuation option for text output

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#1517]
I much prefer to have my markdown output from smart formats like html, docx have dumb punctuation, so my editing can be consistent with the document (I never input smart quotes or ellipses when writing in plain text, for example). I always use something like the following script for markdown output

``` .hs
dumbDownChar :: Char -> String
dumbDownChar '\160' = " "
dumbDownChar '\8211' = "--"
dumbDownChar '\8212' = "---"
dumbDownChar '\8230' = "..."
dumbDownChar '\8216' = "'"
dumbDownChar '\8217' = "'"
dumbDownChar '\8220' = "\""
dumbDownChar '\8221' = "\""
dumbDownChar c = [c]

dumbDown :: Inline -> [Inline]
dumbDown (Str cs) = [Str $ concatMap dumbDownChar cs]
dumbDown (Quoted SingleQuote ils) = [Str "'"] ++ ils ++ [Str "'"]
dumbDown (Quoted DoubleQuote ils) = [Str "\""] ++ ils ++ [Str "\""]
dumbDown il = [il]
```

I know from the mailing list that this is something that comes up for others. Any possibility of this becoming a writer option (not necessarily for 1.13)?

**Comment by brendan-r** [comment]
I just came here to take a look at doing exactly this --- I think it's an excellent idea for a feature!

**Comment by jgm** [comment]
This is fixed now in HEAD.  You can do `pandoc -f markdown-smart -t markdown+smart` and it will dumb down the punctuation.  Indeed, `-f markdown -t markdown` will do the same thing (because of defaults).
