### ISSUE TITLE
pandoc-1.12.4.2 install error

### ISSUE THREAD

**Issue by denisshevchenko** [jgm/pandoc#1526]
Hi!

I try to install `pandoc-1.12.4.2`, but I get this error:

```
$ cabal install pandoc
Resolving dependencies...
[1 of 1] Compiling Main...

Couldn't match expected type ‘TestFlags’
            with actual type ‘UserHooks’
In the expression: flags
In the third argument of ‘test’, namely
  ‘flags
     {testOptions = toPathTemplate (buildDir lbi) : testOptions flags}’
```

What can I do? My system is:

```
OS X 10.9.4
cabal-install 1.21.0.0
ghc 7.8.2
```

**Comment by jessicah** [comment]
Will this be backported to 1.12.4? I have Cabal 1.22, and am running into a similar issue due to breakage in the Cabal API.

    ~> cabal install 'pandoc<1.13'
    Couldn't match expected type 'LocalBuildInfo'
    with actual type 'TestFlags'

I need Cabal 1.22 for the new relocatable build features that resolve an issue installing pandoc on Haiku. Currently, pandoc-1.13.x does not build on Haiku, hence trying to use pandoc-1.12.x.

**Comment by jgm** [comment]
Sorry, no.  In general I don't have time to maintain more than one branch.

+++ Jessica Hamilton [Jan 10 15 20:45 ]:

**Comment by jessicah** [comment]
Ah that's a shame as the patch applies cleanly =/

**Comment by mpickering** [comment]
Building from source is not too tricky if you want to try that?

**Comment by jessicah** [comment]
Yes, that's what I did, with applying the patch. If I do a pull request, would that help to get an updated point release?

**Comment by jgm** [comment]
Why can't you build 1.13?

+++ Jessica Hamilton [Jan 11 15 09:55 ]:

**Comment by jessicah** [comment]
With 1.13 I get the following error:

    [28 of 69] Compiling Text.Pandoc.Readers.Haddock ( src/Text/Pandoc/Readers/Haddock.hs, dist/build/Text/Pandoc/Readers/Haddock.dyn_o )
    Bad interface file: /boot/system/non-packaged/lib/Data/Attoparsec/ByteString/Chr8.dyn_hi
        Something is amiss; requested module  haddock-library-1.1.1:Data.Attoparsec.ByteString.Char8 differs from name found in the interface file attoparsec-0.12.1.2:Data.Attoparsec.ByteString.Char8

Both haddock-library-1.1.1 and attoparsec-0.12.1.2 get built from the single invocation of `cabal install pandoc`. I am building with dynamic executables and shared libraries enabled; and vanilla libraries/static linking disabled.

**Comment by jgm** [comment]
Can you report this to haddock maintainers?

+++ Jessica Hamilton [Jan 11 15 12:47 ]:

**Comment by jgm** [comment]
Take a look at

https://hackage.haskell.org/package/haddock-library-1.1.1/haddock-library.cabal

You'll see they're doing something a bit odd with attoparsec, packaging
their own vendored version:

```
  hs-source-dirs:       src, vendor/attoparsec-0.12.1.1
  ghc-options:          -funbox-strict-fields -Wall -fwarn-tabs -O2

  exposed-modules:
    Documentation.Haddock.Parser
    Documentation.Haddock.Types
    Documentation.Haddock.Doc

  other-modules:
    Data.Attoparsec
    Data.Attoparsec.ByteString
    Data.Attoparsec.ByteString.Buffer
    Data.Attoparsec.ByteString.Char8
    Data.Attoparsec.ByteString.FastSet
    Data.Attoparsec.ByteString.Internal
    Data.Attoparsec.Combinator
    Data.Attoparsec.Internal
    Data.Attoparsec.Internal.Fhthagn
    Data.Attoparsec.Internal.Types
    Data.Attoparsec.Number
    Documentation.Haddock.Parser.Util
    Documentation.Haddock.Utf8
```

You'd better ask the Haddock or haddock-library maintainers why this is done,
as I think it's the root of your problem.


+++ Jessica Hamilton [Jan 11 15 12:47 ]:

**Comment by jessicah** [comment]
Thanks for looking into that. For reference, I've opened https://github.com/haskell/haddock/issues/364  with the Haddock people.
