### ISSUE TITLE
Should LineBreaks be included in normalizeSpaces?

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#1530]
I encountered some weird headers that started and ended with a LineBreak. Would there ever be any reason to keep these at the beginning or end of a set of Inlines we're normalizing? Or should we trim them off as well? (My take is that it seems like visual formatting and should be dropped, but I guess that someone might have some reason.) 

At the moment I just have a trimLinebreaks function that I apply on top of normalizeSpaces.

**Comment by jgm** [comment]
With a bit of rewriting I can get rid of this crufty old function altogether.
Mostly it's now unnecessary.
