### ISSUE TITLE
Error with citeproc when using local bib file

### ISSUE THREAD

**Issue by dfalster** [jgm/pandoc#1548]
Hi, Wonderful to see a new release of pandoc. I just tried it ([pandoc 1.13.0.1](https://github.com/jgm/pandoc/releases/tag/1.13.0.1)) and encountered a problem when using a bibliography. The problem can be reproduced with your demo files, see demo 24 from the [pandoc demo page](http://johnmacfarlane.net/pandoc/demos.html):

```
pandoc -s -S --biblio biblio.bib --csl chicago-author-date.csl CITATIONS -o example24a.html
pandoc-citeproc: could not load the locale file
pandoc: Error running filter pandoc-citeproc
```

Seems to be problem locating the bib file, because removing the bib file removes the error, although the citations are then missing. And yes, the file `biblio.bib` is present. (I first encountered problem with another project which compiled fine before update).

**Comment by bwilliges** [comment]
Hello, I have just downloaded Pandov v 1.13.2 for Windows and get the same issue.
~~~
pandoc-citeproc: could not load the locale file
pandoc: Error running filter pandoc-citeproc
~~~
Pandoc v 1.13.1 for Windows works just fine.

**Comment by jgm** [comment]
Thanks for this.  I assume you used the package from our github releases
site?  There may be a glitch in our build procedure.

+++ bwilliges [Jan 12 15 01:56 ]:

**Comment by bwilliges** [comment]
Thanks for answering that quickly, I didn't expected that:) 

Yes, I used the packages from the github releases site.
