### ISSUE TITLE
Poor handling of nested italics

### ISSUE THREAD

**Issue by exergasia** [jgm/pandoc#1552]
```
$ echo '<em>Foo <em>bar</em></em> baz' | pandoc -f html -t markdown | pandoc -f markdown -t html
<p><em>Foo </em>bar** baz</p>
```

It's questionable what the Right Thing to do in this case is. In traditional publishing, italics within italics are rendered in roman, but HTML's default presentation ignores that and doesn't distinguish between italics and italics within italics (i.e., being clever and toggling between italic and roman wouldn't roundtrip). Whatever the Right Thing to do is, it definitely isn't to scatter stars in the output.

**Comment by link2xt** [comment]
Related issue: #1282

**Comment by mb21** [comment]
Closing in favour of #1282

**Comment by jgm** [comment]
Eventually when we can move over to commonmark, this won't be an issue.
