### ISSUE TITLE
Convert comments in docx reader

### ISSUE THREAD

**Issue by mfenner** [jgm/pandoc#1561]
Comments in docx documents are related to track changes (insertions, deletions), and it would be nice to also convert them in the docx reader. My suggestion would be to use the `<mark>` tag for the highlighted text, and to put the comment itself into the title attribute, e.g.

``` html
Here is some <mark title="This is a comment">highlighted</mark> text.
```

**Comment by fmatheus** [comment]
In markdown it could be converted to footnotes with author and date if possible.

**Comment by jgm** [comment]
Looks like we have comment support now, see test/docx/comments.native

@jkr can you confirm that this issue can now be closed?

**Comment by jkr** [comment]
Yep -- closing. They don't convert as footnotes, but instead as spans denoting the beginning and the end of the commented text. The comment itself is enclosed within the first span. So you could write a filter mapping to a footnote from that.

Note a certain misfit here: comments and footnotes are both sets of blocks, while a span is a set of inlines. So we (intentionally) lose some block structure. 

If we ever added a native comment element to pandoc, it would be nice to have it be isomorphic to note (ie  embed blocks in an inline). But the lack of a nice markdown representation seems a limiting factor.
