### ISSUE TITLE
--self-contained does not respect --data-dir

### ISSUE THREAD

**Issue by jmcphers** [jgm/pandoc#1572]
> --self-contained [...] Scripts, images, and stylesheets at absolute URLs will be downloaded; those at relative URLs will be sought first relative to the working directory, then relative to the user data directory (see --data-dir), and finally relative to pandoc’s default data directory.

The docs state that self-contained resources are resolved against `--data-dir`, but this behavior doesn't appear to work in current builds (or perhaps I'm misunderstanding the feature?): 

Repro:
1. Create a file `/tmp/bar.js`
2. Create a file `temp.md` somewhere, with `<script src="bar.js" />`
3. `pandoc --to html --from markdown temp.md --self-contained --data-dir /tmp`

Result:

```
pandoc: Could not fetch bar.js
bar.js: openBinaryFile: does not exist (No such file or directory)
```

**Comment by jmakeig** [comment]
If I use a `<link rel="stylesheet">` the `@href` will correctly (in my opinion) resolve relative to the path of the _template_, i.e. in the `data-dir`, not the working directory of the input file. However, with `<script src="">` in my template, I have to use an absolute path.  I’m using pandoc 1.19.2.1 on macOS 10.12.6.

```bash
pandoc \
  --from=commonmark \
  --to=html5 \
  --self-contained \
  --template="hierarchical/template.html" \
  --section-divs \
  --output="$1.html" \
  --verbose \
  "$1.md"
```
