### ISSUE TITLE
There's no way to attach a CSS class to a table

### ISSUE THREAD

**Issue by malcook** [jgm/pandoc#1579]
There's no way to attach a CSS class to a table. I can do this to a heading by writing:

```
### Heading Title {.some-style}
```

but the curly-brace syntax doesn't work with tables. 

(statement of issue lifted verbatim from http://third-bit.com/2013/06/13/problems-with-pandoc.html)

**Comment by jgm** [comment]
This would be addressed by the proposal in #1024, adding Attr to Table.
Closing in favor of that issue.
