### ISSUE TITLE
Image Format conversion (Juicy Pixels) fails with in-the-wild gifs

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#1582]
The following

```
pandoc "http://grantland.com/features/predicting-nfl-unpredictable-carson-palmer-philip-rivers-eli-manning/" -o out.pdf
```

fails with

```
pandoc: Unable to convert image `/var/folders/hl/w1zpk3t52l77d_nf0rv17hc00000gp/T/tex2pdf.68131/0b0fd1be11d0eb72a8c5c9c28b431dd768a8bbb9.gif'
pandoc: Unable to convert image `/var/folders/hl/w1zpk3t52l77d_nf0rv17hc00000gp/T/tex2pdf.68131/260177ae0d6ffedc2a95aca96ae9fe760bbfeab1.gif'
! LaTeX Error: Something's wrong--perhaps a missing \item.

[...]
```

There seem to be a couple of gif images in the page that JuicyPixels can't convert. Pulling down to a docx, and extracting images (why can't we `--extract-media` from a web page) shows that one of the two problematic images is the following: http://commonmeasure.org/~jkr/rId98.gif

```
Prelude> import Codec.Picture
Prelude Codec.Picture> Left msg <- readImage "rId98.gif" 
Prelude Codec.Picture> putStrLn msg
Cannot load file
Jpeg Invalid marker used
PNG Invalid PNG file, signature broken
Bitmap Invalid Bitmap magic identifier
GIF Unrecognized gif block 32
HDR Invalid radiance file signature
Tiff Invalid endian tag value

Prelude Codec.Picture> 
```

If we convert the problematic gif to a gif with ImageMagick, JuicyPixels reads it fine.

**Comment by dmjio** [comment]
I am running a web server and am seeing this issue. I think it has to do with the `vector` package, which aeson (in my case) relies upon.

```
./Data/Vector/Generic.hs:249 ((!)): index out of bounds (0,0)
```

**Comment by jgm** [comment]
Can you say more about what kind of requests trigger it?  Are they pages
with images?  What format are you converting from/to?  What kind of
images?

**Comment by dmjio** [comment]
It's a web server that delivers JSON. Each request only has a json body. I apologize, but this doesn't involve pandoc at all actually.  It looks like it's to do with aeson which depends on vector which depends on array.

![screen shot 2015-03-30 at 10 08 26 pm](https://cloud.githubusercontent.com/assets/875324/6911685/871a2e30-d729-11e4-88ec-84f193145d33.png)
