### ISSUE TITLE
piped yaml metadata (\@) gets escaped

### ISSUE THREAD

**Issue by maybegeek** [jgm/pandoc#1596]
Hi there,

reading in some markdown with yaml in a piped block does not leave the input unescaped as otherwise stated in the documentation:

_The pipe character (|) can be used to begin an indented block that will be interpreted literally, without need for escaping._
- pandoc -f markdown+yaml_metadata_block, or
- pandoc -f markdown

``` yaml
header-includes: |
  \makeatletter
  \newif\if@mainmatter \@mainmattertrue
  \newcommand*\frontmatter{\clearpage\@mainmatterfalse\pagenumbering{roman}}
  \newcommand*\mainmatter{\clearpage\@mainmattertrue\pagenumbering{arabic}}
  \newcommand*\backmatter{\clearpage\@mainmatterfalse}

  \makeatother
```

give the following output in latex

``` latex
\makeatletter
\newif\if@mainmatter @mainmattertrue
\newcommand*\frontmatter{\clearpage\@mainmatterfalse\pagenumbering{roman}}
\newcommand*\mainmatter{\clearpage\@mainmattertrue\pagenumbering{arabic}}
\newcommand*\backmatter{\clearpage\@mainmatterfalse}

\makeatother
```

**\@mainmattertrue** looses its backslash **\** and gets **@mainmattertrue**

How can I let this unescaped?

thanks,
christoph

**Comment by Konfekt** [comment]
> A simple solution would be to have the parser treat a YAML field header-includes specially, as a plain string -- since nobody would want this parsed as markdown.
> That seems a bit ad hoc, though, so it's also worth considering (see the mailing list discussion) whether there should be some way to mark a field as a plain string.

Has this been ultimately rejected in the mailing list discussion, or would it not still be sensible to expect that the value of header-includes does not need escaping?

**Comment by jgm** [comment]
The current recommendation is to use a raw attribute:
````
header-includes: |
   ``` {=latex}
   put your raw latex here
  ```
````

**Comment by jgm** [comment]
Note also that if you use a defaults file (see `--defaults`) you can specify `header-includes` under `variables`, and there's no need to escape there.  Since this is really not "metadata" but an instruction for generating output, it fits better in a defaults file than in metadata.

**Comment by Konfekt** [comment]
Dear @jgm, Thank you very much for the prompt response.
