### ISSUE TITLE
LaTeX Reader skips an unknown command.

### ISSUE THREAD

**Issue by Wikiwide** [jgm/pandoc#1598]
It is said in User's Guide that LaTeX reader does pass through untranslatable LaTeX commands, even if -R is not specified. I do not see it in reality. An example is converting X\underline{Y}Z from tex to docx.

Haskell-coders, please, read line 368, https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/LaTeX.hs and explain what is happening.

**Comment by jgm** [comment]
Actually the user's guide is correct.  LaTeX commands are passed through to the pandoc AST by the reader.  But the docx writer will omit raw LaTeX it finds in the AST.
