### ISSUE TITLE
list item beginning with hash (#) becomes first-level header

### ISSUE THREAD

**Issue by harriott** [jgm/pandoc#1599]
A minor snag with a list that starts with a hash (in this case hex color codes). Here's a `mwe.md` (`pandoc --toc --toc-depth=4 -f markdown_strict mwe.md -o mwe.pdf`):

```
#### eg a 4th level header
- `#ebd45c` - 1st list item
- previous list item includes a code span
- #f5e384 - 3rd list item
- previous item gets level 1 header formatting, and inclusion as such in toc and bookmarks
- `#f9eba4` - 5th list item
```

![hash-in-list](https://cloud.githubusercontent.com/assets/6985117/4132250/6cf58bc2-334f-11e4-8938-004b690de0c0.jpg)
Obviously, the work-around is to use code spans...

**Comment by jgm** [comment]
I think we should make this change (it is also consistent with CommonMark), and require the space after `#`.  Note that this might break existing documents.

**Comment by jgm** [comment]
This has been fixed already.
