### ISSUE TITLE
TOC looses formatting from list items in ePub

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#1611]
The following tite gets properly formatted in body text, but it looses it in the table of contents:

```
# `type` and _emphasis_
```

Could you fix it?

Many thanks for your help.

**Comment by jgm** [comment]
stringify was added in commit a7daf29eafbfc5cee6f398369ef645d1e1ebd24c
It replaced an earlier function that used the plain writer.
I'm not sure why we stripped formatting; there must be some reason for it, and I'd be reluctant to make changes here without understanding what they were.

**Comment by ousia** [comment]
> I'm not sure why we stripped formatting; there must be some reason for it, and I'd be reluctant to make changes here without understanding what they were.

@jgm, I don’t know why formatting wasn’t included in the TOC. I can only guess.

Was formatting stripped from the TOC? I mean, would it be possible that it wasn’t simply added for the sake of simplicity?

Maybe none thought that headings needed formatting within the title text.

**Comment by jgm** [comment]
We use the same function, to produce the headings for `toc.ncx` and `nav.xhtml`. The former is not HTML, so we can't use HTML tags for styling. I think this is why I used `plainify` there.  It should be easy to fix things so that formatting is preserved in `nav.xhtml`.

**Comment by jgm** [comment]
Closed by commit 2581f97620b36b14ee5560a747f57298a8640c84
