### ISSUE TITLE
Support for custom .cls files

### ISSUE THREAD

**Issue by afuhrtrumpet** [jgm/pandoc#1615]
I want to use a custom class file (http://www.latextemplates.com/template/memo in this case) and Pandoc doesn't seem to be able to recognize the .cls file in my directory despite pdflatex being able to. The document simply converts without the memo header.

**Comment by linamnt** [comment]
Sorry to bring this back up 6yrs later, but I am misunderstanding what the solution is based on the previous two comments. How would I change the call to `pdflatex` within Pandoc? 

RIght now, I install my `.cls` files in my texmf tree, but I'm not sure how to make use of TEXINPUT or BSTINPUT in my call to Pandoc when making pdfs?
