### ISSUE TITLE
-t revealjs: no speaker notes and no content on horizontal slides if --slide-level=2

### ISSUE THREAD

**Issue by karland** [jgm/pandoc#1618]
@jgm pandoc is great. Thanks a lot.

I like to use `pandoc` to generate slides with `reveal.js`. I would like to generate horizontal (level 1) and vertical (level 2) slides, which means  `--slide-level=2`. However pandoc eats up all content and speaker notes from level 1 slides. If I set `--slide-level=1`, I do not get vertical slides any longer. 

I know, that this is the described behavior according to the manual, but I do not understand why? Is there any chance or way around it. Many thanks.

**Comment by devurandom** [comment]
I would still consider it to be a bug, if pandoc silently removes the body below the level-1 header for reveal.js. And if beamer output behaves the same, I would argue that it is just as broken. If I write content, I want it to appear in the output. Period.

A quick test shows that:
```md
# L1

Text L1

## L2

Text L2
```

generates:
```latex
\begin{document}

\section{L1}\label{l1}

Text L1

\begin{frame}{L2}

Text L2

\end{frame}

\end{document}
```

If you would output instead:
```latex
\begin{document}

\section{L1}\label{l1}

\begin{frame}{L1}

Text L1

\end{frame}

\begin{frame}{L2}

Text L2

\end{frame}

\end{document}
```

that would be a graceful fallback, respecting the user's wish to have some text for L1.

This would also allow you to output proper reveal.js-spirited 2D-decks as explained by @karland. Thus I suggest to reopen this issue.

**Comment by azrdev** [comment]
@jgm @karland -- while I understand the reason *content* is avoided on the header-slides, I think *speaker notes* should still be possible, which were also covered by this report.
