### ISSUE TITLE
feature request: html output, div around line block

### ISSUE THREAD

**Issue by uvtc** [jgm/pandoc#1623]
I'd like for the html output of line blocks to have a div around them so that I can style them.

That is, I'd like this:

```
| this
| that
```

to produce html like `<div class="line-block">this<br/>that</div>`, rather than `<p>this<br/>that</p>`.

Currently, to get something similar I need to do:

```
<div class="line-block">

| this
| that

</div>
```

(newlines required) but, of course, that still keeps the `<p>`'s around the line block.

**Comment by mb21** [comment]
We have a LineBlock element now, but the HTML writer doesn't emit a special class:

```
$ pandoc
| this
| that


<div style="white-space: pre-line;">this
that</div>
```

**Comment by uvtc** [comment]
Can I now style the lineblock from my css without adding any special html to my source file?

**Comment by mb21** [comment]
@jgm was this closed in error?

**Comment by jgm** [comment]
Okay.  
@uvtc did you want to override the `style="white-space: pre-line"` or add additional styling?
In the latter case there's also the option of keeping the style and adding the class.  This would mean we don't depend on special CSS definitions in the template, and documents processed using old templates don't break.  Not sure what is best here...

**Comment by uvtc** [comment]
I wanted to add additional styling (for example, a thick border-left) --- otherwise, line blocks tend to blend in and look suspiciously like regular paragraphs.

**Comment by mb21** [comment]
Speaking as a web dev, personally, I was never really comfortable with the style attribute...

**Comment by jgm** [comment]
I'd be okay with using a div with class and adding CSS to the templates.
We'd need a small change in the HTML writer, plus changes to the styles in

default.html5
default.html4
default.epub2
default.epub3
default.revealjs
default.s5
default.slideous
default.slidy
