### ISSUE TITLE
percentage character with lstinline for pandoc --listings -t latex

### ISSUE THREAD

**Issue by MichaelKofler** [jgm/pandoc#1629]
using pandoc --listings -t latex

``a % b``

is translated to 

`\lstinline!a % b!`

However, this only works it `\lstinline` is _not_ within another LaTeX structure. (See sec. 5.2 / page 48 in http://texdoc.net/texmf-dist/doc/latex/listings/listings.pdf.) I.e. 

`*`a % b`*`

gets you incorrect LaTeX code. In such cases, you can get around the problem using this markdown code:

`*`a \% b`*`

This is fine if you only need to make a LaTeX version, but not good if you need HTML _and_ LaTeX. I just did a 1000 pages book using pandoc + LaTeX and I stumbled over many cases where this caused problems.
## Solution

I believe there is a universal solution to this problem which could be incorporated into pandoc quite easily: 
- always quote the `%` character within `\lstinline`
- put \lstinline within a LaTeX command which does nothing

Thus, `\lstinline` work always, no matter whether it is used in plain text or within any other LaTeX command.

I.e. the following markdown code

```
bla bla `a % b`

*bla bla `a % b`*
```

should be translated to this LaTeX code:

```
\newcommand{\within}[1]{#1}

bla bla \within{\lstinline!a \% b!}

\emph{bla bla \within{\lstinline!a \% b!}}
```

**Comment by bubifengyun** [comment]
It seems that it is still a problem now. except pay attention to latex itself, Anyone has a good suggestion?  Thank you.

**Comment by bubifengyun** [comment]
I think the solution they provided is not as good to use. If you work in math paper, just like that https://github.com/jgm/pandoc/issues/4713 

how to insert `$` in lstinline code. Today I find that it cannot insert one `#`. xelatex will pdf to `##`

**Comment by blaggacao** [comment]
I still get this error on:
```
l.336 \passthrough{\lstinline!*.drawio!}
```
```shell
Error producing PDF.
! Undefined control sequence.
l.336 \passthrough


```

**Comment by bubifengyun** [comment]
> re: [#1629 (comment)](https://github.com/jgm/pandoc/issues/1629#issuecomment-55725983)
> 
> I still get this error on:
> 
> ```
> l.336 \passthrough{\lstinline!*.drawio!}
> ```
> 
> ```shell
> Error producing PDF.
> ! Undefined control sequence.
> l.336 \passthrough
> ```

you should define `\passthrough`in your latex file. like this,

```latex
\newcommand{\passthrough}[1]{#1}
```

**Comment by blaggacao** [comment]
@bubifengyun Thanks for your suggestions, it's actually there in the default latex shipping with pandoc, so that doesn't _seem_ to be the issue, here. It looks like the error message isn't particularly useful, in this case. Maybe it's reset on new pages?
