### ISSUE TITLE
remove style="..." from html tags

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#163]
<pre>
Consider removing, if possible, the `style=".."` and `align=".."` that appear in tables and deleted 
(ie ~~this_is_strikethrough~~) text. The user should be able to choose his own thought CSS.

Google Code Info:
Issue #: 200
Author: m3fi...@gmail.com
Created On: 2010-01-08T11:11:34.000Z
Closed On: 
</pre>

**Comment by DaveEveritt** [comment]
If this issue is closed, at least point to how these inline styles (which take priority over any other stylesheet) can be removed, so it becomes possible to use a separate stylesheet. Clean inline-style-free markup is the ideal.

**Comment by jgm** [comment]
Post process with sed or awk or something more geared towards modifying HTML?

**Comment by DaveEveritt** [comment]
Yes that would post-fix it, but:

1. that's another step when I'm continually regenerating the same document, possibly with  multiple tables;
2. translating from one plain-text format to another ideally needs to be as free as possible form any style, especially for HTML where users will use their own stylesheets;
3. the Pandoc inline styles seems to narrow the table columns badly when tables tend to arrange themselves quite nicely without any style.

Is there any reason for retaining the inline table styles in HTML?

**Comment by jgm** [comment]
+++ David Everitt [Sep 17 16 01:32 ]:
>   Yes that would post-fix it, but:
>    1. that's another step when I'm continually regenerating the same
>       document, possibly with multiple tables;
>    2. translating from one plain-text format to another ideally needs to
>       be as free as possible form any style, especially for HTML where
>       users will use their own stylesheets;
>    3. the Pandoc inline styles seems to narrow the table columns badly
>       when tables tend to arrange themselves quite nicely without any
>       style.
>
>   Is there any reason for retaining the inline table styles in HTML?

Pandoc's table format has a way of specifying column
alignments.  That is the only place we use the styles.
We could replace these, I suppose, with something like
a class (centered|right-aligned|left-aligned), and add
CSS to the default template that applies alignments to
these classes.  But often pandoc is used to generate
HTML fragments, and we try to make these work, as much
as possible, without external stylesheets.  It's also hard
to see a reason why one would want to override the default
here.  If you want centered columns, for example, pandoc
lets you specify that in the source document.

The column widths are given on col tags (not inline styles).
Please see the manual about how these are determined.
Except for simple tables, they are based on the relative
widths of the columns in your source document, so you can
adjust them to your liking.  (Note that many of the formats
pandoc supports require column widths; they don't calculate
these automatically like browsers do.  And even in formats
like HTML where column widths can be calculated
automatically, very often authors want more control.)
