### ISSUE TITLE
Ñ crashes pandoc

### ISSUE THREAD

**Issue by lselzer** [jgm/pandoc#1634]
On windows this crashes pandoc using templates.

`test.md`:
```
Ñ
```

`pandoc test.md -t sample.lua -f markdown`

Produces the following error

`pandoc: Cannot decode byte '\xc3': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream`

Lowercase ñ doesn't trigger this. `test.md` is `UTF-8`

**Comment by jgm** [comment]
See #2101 -- I'm not sure why this issue was closed, because it never was resolved.
