### ISSUE TITLE
Backslash not escaped for LaTeX output

### ISSUE THREAD

**Issue by jbee** [jgm/pandoc#1637]
The following example occuring in inline text (markdown) has not been escaped in resulting tex file causing pdflatex to fail as `\n` is understood as control sequence.

```
  text (_\n_ more text)
```

**Comment by jdhao** [comment]
I have also met the same issue. If we do not properly escape the backslash, strange errors may occur. Mostly, the error message will be something like `undefined control sequence`. The solution is to use `pandoc -f markdown-raw_tex` as suggested by @neongreen. Or just use double backslash or wrap the text in inline code blocks.

A similar issue  #2790 is also reported.
