### ISSUE TITLE
Strange pdf output when writing `"avg"` in spanish

### ISSUE THREAD

**Issue by cganterh** [jgm/pandoc#1648]
I'm including some code in a spanish text and it seems that LaTeX combines (hyphenates?) the "a" letter when I write `"avg"`. I don't know if this is an expected behaviour in LaTeX, but it is totally not expected in markdown. So I think it's a bug.

This is a very short version of my text:

```

---
lang: spanish
...

`"avg"`

`"a`

\verb|"a|
```

And here is an image of the output:

![sin nombre](https://cloud.githubusercontent.com/assets/5922460/4428354/484276f8-45cb-11e4-8693-1f07eee931b1.png)

As you can see when I use `\verb| |` it works as espected.

**Comment by artemisart** [comment]
Forcing shorthands=off breaks spacing for french, couldn't that be an option ?
