### ISSUE TITLE
Doing something of LaTeX commands when generating HTML

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#165]
<pre>
I use Pandoc to generate both LaTeX and HTML. One
troublesome thing with this is that if one has
literal LaTeX commands in the markdown these just
vanish if one tries to generate HTML from the same
markdown. It would be much better if they were
turned into HTML spans with the LaTeX command name
as a class and the argument(s) as content.  Then
one could still make the text make sense, and do
something sensible with those spans, including
setting them to display: none, *if* that's the
sensible thing to do!  Thus

    \foo{bar}

would be HTML-ified as 

    &lt;span class="foo"&gt;bar&lt;/span&gt;

and

    \foo{bar}{baz}{biz}

would become

    &lt;span class="foo"&gt;
      &lt;span class="arg1"&gt;bar&lt;/span&gt;
      &lt;span class="arg2"&gt;baz&lt;/span&gt;
      &lt;span class="arg3"&gt;biz&lt;/span&gt;
    &lt;/span&gt;

which would increase once chances of making something
sensible of them with CSS.

Needless to say \begin{foo} and \end{foo} should be special
and become &lt;div class="foo"&gt; and &lt;/div&gt; respectively (and 
arguments to the environment becoming additional classes).

As long as ones LaTeX commands are relatively
simple -- and I at least mostly use them for font
changes and the like -- this would be much better
than getting nothing!  Clearly it wouldn't make
much sense to generate HTML from markdown which
contains a lot of *complicated* LaTeX anyway.
However it might be a good idea to have a command
line switch with a filename as an optional
argument: if the switch is present LaTeX commands
will be turned into HTML spans and if the filename
is present it contains a list of LaTeX commands
which will just be deleted, alternatively ones
which will be turned into HTML spans.

Google Code Info:
Issue #: 198
Author: bpjonsson
Created On: 2010-01-07T16:48:50.000Z
Closed On: 
</pre>

**Comment by mb21** [comment]
This seems mostly implemented now. Closing in favour of more specific issues, if remaining.

**Comment by bpj** [comment]
Hey @mb21 not so fast!  What about `-f latex+styles` `\myWhackyCommand{foo}` ---> `[foo]{custom-style="myWhackyCommand"}` at least when there is just one argument?  Is there a more specific issue for that?  Feel free to list some of those issues then!

**Comment by mb21** [comment]
@bpj sounds like [Custom styles for ODT (and maybe LaTeX and RST) writers](https://github.com/jgm/pandoc/issues/2106)?
