### ISSUE TITLE
[Debugging Options] For converting to PDF: improve debugging options

### ISSUE THREAD

**Issue by pdfkungfoo** [jgm/pandoc#1653]
When converting to PDF, `pandoc` should allow (via a commandline switch such as `--pdfdebug` or similar) to preserve (or dump) the intermediate LaTeX code somewhere on the harddisk and issue a message where the *.tex (and maybe other log and auxiliary files from `{pdf,lua,xe}latex` runs) may be found.

**Comment by KurtPfeifle** [comment]
Great! Thanks a lot, John.
