### ISSUE TITLE
Support for smart punctuation in org reader

### ISSUE THREAD

**Issue by bosmacs** [jgm/pandoc#1665]
Current versions of org-mode support exporting with smart punctuation (smart quotes and M-dashes, at least), but the current Reader does not support this feature. I'd like to see the org reader support exporting with smart punctuation as an option, the same way the Markdown reader does. 

To that end, I've already done some work in implementing this [here](https://github.com/bosmacs/pandoc/commit/4a02ed77f7bc17f51d7e605735c71c3d38243684), but I could use some feedback. In particular, I don't like duplicating the `singleQuoted` and `doubleQuoted` functions from the Markdown reader, and the instancing of `HasQuoteContext` for `OrgParserState` seems unnecessarily redundant -- but I remain a Haskell novice so I'm not sure how to improve it.

**Comment by bosmacs** [comment]
I finally spent a little more time on this and got the two problem test cases above working, you can see my latest work here: https://github.com/bosmacs/pandoc/commit/005224467fde4f8229dda4f3959a480fa60bfa0a 

Please let me know what you think.

**Comment by jgm** [comment]
Great.  @tarleb, @mpickering, do you think this is ready to merge?

**Comment by mpickering** [comment]
LGTM, I would wait for @tarleb to comment as I'm not sure when `updateLastForbiddenCharPos` should be invoked but this does match up with a fix I tried to do several months ago.

**Comment by tarleb** [comment]
Looks great!  If it's okay with travis, it's definitely okay with me. @bosmacs: I admire your persistence, coming back to a problem after six month and finishing the job is quite exceptional.
