### ISSUE TITLE
Add `\-` command for a non-breaking hyphen

### ISSUE THREAD

**Issue by lemzwerg** [jgm/pandoc#1686]
Inserting U+2011 for a non-breaking hyphen is error-prone, since the visual difference to a normal hyphen in most editors is small.  I thus suggest to add the command `\-` to insert this character.

**Comment by ikcalB** [comment]
Would you PLEASE reconsider implementing a non-breaking hyphen?
It may well be an Extension that has to be enabled manually - this should lead to minimal confusion.

Best regards from Austria!

**Comment by tolot27** [comment]
There is a latex package [extdash](https://www.ctan.org/pkg/extdash) which provides long version and shortcuts for various breaking and non-breaking hyphens. Maybe the shortcuts could be adapted for pandoc. At least the LaTeX reader would benefit from parsing the extdash syntax.
