### ISSUE TITLE
[Feature Request] speaker notes output in dzslides and revealjs

### ISSUE THREAD

**Issue by maybegeek** [jgm/pandoc#1693]
Hi there,

could we please unify speaker notes handling for revealjs an dzslides:

* in revealjs we have `<div class="notes">`
* in dzslides we had `<details>` and should use `<div role="note">`

a unified solution would be for addressing both output formats:

* `<div class="notes" role="note">`

Could we get another `case` in HTML.hs for dzslides, thus outputting the `<div class="notes" role="note">`, an extension or such?

best regards.

**Comment by ivan-m** [comment]
As part of this, the template for dzslides needs to be updated for speaker notes to work (I tried manually adding them).

**Comment by jgm** [comment]
@ivan-m, I just pushed an update for the dzslides `template.html`.

**Comment by jgm** [comment]
@maybegeek I made the change you suggested for dzslides.
Does everything work now?  Can the issue be closed?

**Comment by ivan-m** [comment]
dzslides should use `<div role="note">` instead of the current `<div class="notes">` (note in particular the lack of a plural).

**Comment by maybegeek** [comment]
@jgm Thank you for implementing this. Sorry for the late response, end of semester ...

The implementation let people write their markdown with `<div class="notes" role="note">` and later on they can decide if they want to have `-t dzslides` or `-t revealjs`.

@ivan-m we need both, the class-attribute and the role-attribute, else we would need to fork and maintain revealjs and dzslides templates and js-function, and probably would need users to adjust to one way of making notes.

@jgm I could close this, but would wait if above discussion is settled?

In addition, we have old examples (http://pandoc.org/demo/example9/producing-slide-shows-with-pandoc.html) where speaker notes is only for revealjs and we would need to update that.

furthermore, we need a javascript for showing and hiding again our notes. I have to look if my modifications fit somehow.

best regards

**Comment by ivan-m** [comment]
@maybegeek when Pandoc [converts the representation](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/HTML.hs#L461) to DZSlides-style HTML, then it should convert it to `<div role="note">`.

**Comment by maybegeek** [comment]
@ivan-m I now see your perspective. I thought it would be a pragmatic and small change to build upon pandocs handling for `<div class="notes">` that we could easily add a role-attribute `role="note"`, more specifically, that the user has to add this on their own. Then only the convert to dzslides would need to let this output happen, which means outputting the div-block and letting the role="note" as it is.

this would need adjustments on the user side for he should put `<div class="notes" role="note">` in his markdown agnostic of `-t revealjs` or `-t dzslides` (output would be the same with the untouched role-attribute). my view.

if we want the user to only add `<div class="notes">` and outputting `<div class="notes">` in revealjs and `<div role="note">` in dzslides we would need this handled differently, true. This would make markdown notes more readable, on the other hand it is already html code that has to be added from the user to markdown and would only cloud the syntax for dzslides.

I'm undecided.

best regards

**Comment by ivan-m** [comment]
Actually, this only requires that line I linked to to be changed.  So users only need to use `<div class="notes">` in their Markdown.

As an alternative (in case anyone is looking), I use [this filter](https://github.com/ivan-m/CanFP-Parsing/blob/master/notify.hs) to turn a definition list with a key of `Notes` into the appropriate note type.

**Comment by jgm** [comment]
I think we need ONE consistent way of entering speaker notes
that works in every format.  Currently that's
`<div class="notes">my notes</div>`.

The writer should automatically convert this to what's
needed in the particular output format.  If it's not doing
this properly for dzslides, please tell me what the output
should be and I'll implement it.

**Comment by maybegeek** [comment]
Dear @jgm 

for `-t dzslides` we need `<div role="note">my notes</div>` as output

(other html attributes, like `<div class="notes" data-foo="bar">` should remain in the output as well and produce `<div role="note" data-foo="bar">my notes</div>` for hackability).

thanks again!
