### ISSUE TITLE
pandoc to latex forces line rewrap (does not respect linebreaks)

### ISSUE THREAD

**Issue by aswolf** [jgm/pandoc#1701]
It appears that when pandoc is used to convert from a markdown file to latex, it does not respect the line breaks in the markdown file. Rather than maintaining the line definitions, it automatically rewraps each paragraph such that each line is less than 80 characters.

For many latex users, this is totally undesirable behavior. Writing with one sentence per line is common practice as it simplifies output from diff'ing files and is better for version controlled tex files. 

Is it possible to change the behavior so that it respects the lines as defined in the original markdown file? This would afford a huge advantage to latex users, allowing them to write initial drafts in markdown, which is much quicker, and then converting to latex for further work. If this isn't the desired default behavior for other reasons, is it possible to add an optional flag?

Thanks so much!

**Comment by msprev** [comment]
+1 for a Softbreak element. I use pandoc to manipulate markdown (reading markdown, transforming ast, writing markdown). This is handy for doing operations on elements (moving/changing lists/sections/etc). The main problem I run into is that it destroys the soft linebreaks along the way.

**Comment by jgm** [comment]
I'm working on this now in the softbreak branch.
