### ISSUE TITLE
ICML output file "not a valid indesign interchange document"

### ISSUE THREAD

**Issue by alololox** [jgm/pandoc#1707]
Attempting to write from an epub to ICML with the following command:

> pandoc  -s text.epub -o text.icml

and I get the following error when attempting to place in to a new InDesign document:

> "This is not a valid indesign interchange document"

**Comment by tribpapers** [comment]
Not sure if this is helpful but you could create a text file that uses the HTML compatible tags with Microsoft Word (doc) files. For example you can use tags: `h1, h2, h3, h4, h5, h6, p, blockquote` as paragraph styles and a few other inline styles like `em, strong` ... then you can run `-f html -t icml` and despite the fact you are still using a .txt file it preserves those styles.
