### ISSUE TITLE
Images not present in Docx

### ISSUE THREAD

**Issue by archonic** [jgm/pandoc#1717]
I'm using the [pandoc-ruby](https://github.com/alphabetum/pandoc-ruby) gem to serve a converted HTML to DOCX file with a ruby on rails app. In the rails console, I can convert the HTML to DOCX and images are present. Doing the exact same thing with the app just writes the alt text of the images into the document without the image. Both processes are in the same environment and both make use of the same pandoc ruby wrapper gem.

I wish I could explain more but that's the sum of it. The same exact process using the server (thin) has images vanish and just the alt text shows in it's place.

Any ideas what could cause this?

**Comment by joshco** [comment]
I see this as well, and like @archonic says, a non-standard port makes the difference.  Im developing a rails app, in docker, using port 53000, which has the problem.  If I have the IMG src pointed to a server on the net (port 80 http or 443 ssl) the image loads in docx.  However, when the src url is pointed at my dev server, they do not load in docx.   
Setting up a reverse webproxy docker container to answer on port 80 and internally forward to 53000 fixes the problem.
go figure
