### ISSUE TITLE
Unused footnotes are not warnings or errors

### ISSUE THREAD

**Issue by gwern** [jgm/pandoc#1718]
This is the flipside of #375, which is something I only just realized by accident could happen: when you define a footnote ID, and then you forget to use it, this is not flagged in any way. Example:

```
$ cat test.page 
This is a test file[^footnote-1].

[^footnote-1]: This is a used footnote. No problem here.
[^footnote-2]: This is an unused footnote. This should be an error.
$ pandoc test.page 
<p>This is a test file<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>.</p>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>This is a used footnote. No problem here.<a href="#fnref1">↩</a></p></li>
</ol>
</div>
```

There are no warning messages or oddities in the generated HTML.

As with the other footnote bug report, my reasoning is that such a footnote makes no sense, cannot be intended by the author, and should be flagged in some way, particularly as it's a difficult-to-detect problem in large complex documents.

(As to how I discovered it: I was adding 2 papers on errors in math software to [an essay of mine](http://www.gwern.net/The%20Existential%20Risk%20of%20Mathematical%20Error) and wasn't sure where to put one of them, when I noticed 2 footnotes on the same topic, and figured that I could add the paper wherever those footnotes were being called... except the footnotes weren't being called anywhere. Oops. My lint script and Pandoc hadn't caught them because the 2 footnotes had different IDs, but the problem was they weren't being _used_ anywhere, not that there was too many of them. And my omission dated back to the very first version of that essay in early 2012; in total, this has affected >20k page-views.)

**Comment by jgm** [comment]
Now that we have a good system for warnings, it should be a simple matter to add this.

**Comment by jgm** [comment]
On second look, not so simple.  But still probably a good feature.
Also for link references.

Best approach is probably to add some detail to `stateNotes` in `ParserState` (though this would affect some RST and Textile writers too).

For each note, we could store in state:

- its source position (for messages that arise in parsing the note later, and for the envisioned message about unused notes)
- its contents
- a boolean flag, defaulting to False, that gets set to True when the note is used.

Alternatively, we could store lists of used notes and references.
