### ISSUE TITLE
Broken links for the citation examples

### ISSUE THREAD

**Issue by ogrisel** [jgm/pandoc#1723]
The links in for the citations demos are broken on the web page:

http://johnmacfarlane.net/pandoc/demos.html

For instance the following linked page is not found:

http://johnmacfarlane.net/pandoc/demo/example24a.html

**Comment by hftf** [comment]
This is still an issue.

**Comment by jgm** [comment]
Thanks!  I revised the build procedure, so hopefully this
won't happen again without my noticing.


+++ Ophir Lifshitz [Mar 16 15 18:55 ]:
