### ISSUE TITLE
list of listings

### ISSUE THREAD

**Issue by Bengt** [jgm/pandoc#1728]
I just missed to option to add a list of listing to the LaTeX/PDF document. While pandoc supports passing variables to activate the list of figures and the list of tables (see #1407), there is no equivalent for the list of listings (expected: `pandoc --variable lol`). Since Pandoc's LaTeX writer already knows about lstlistings `--listings`, it would be nice to have a command line option that triggers a list of listing in the corresponding template. I think it would be fine, to have the lol following the toc/lot/lof, but I guess there is no guideline to be found which supports that.

As a workaround, one can put the list before any other content:

```
\lstlistoflistings

# Introduction
```

**Comment by matthiasbeyer** [comment]
@Bengt How did you get list of listings in your output? I have `\lstlistoflistings` in my template source, though it doesn't list my listings.

Do I have to use some special markup for this? Also: How to include captions for my source code listings? I cannot find documentation about this!

**Comment by Bengt** [comment]
@matthiasbeyer I tried modifying the template as you did and it worked, but ultimately I used the workaround I posted. I preferred not to change the template, because I wanted to be able to update the it to upstream changes without needing port my changes to newer versions.

Make sure to [properly specify your template](http://pandoc.org/README.html#templates). If the problem persists, please file an issue for it.

I believe captions of source code listing are not supported by pandoc at the moment and a workaround is to use literal latex listings. - But please double check that. If you think the documentation should be improved, please file an issue describing the imperfection.

**Comment by matthiasbeyer** [comment]
@Bengt My list of listings is not generated at all.

What is the markup you use for captions? I assume my listings do not show up in the LOL because they have no captions.

**Comment by matthiasbeyer** [comment]
The trick was to do like someone said in https://github.com/jgm/pandoc/issues/673:

```
~~~{#mypython .python .numberLines caption="Foo"}
```

**Comment by jgm** [comment]
I think including raw tex via something like `--include-before-body=FILENAME` is the way to go here; it doesn't require changes to a template and it gets you what you need.
