### ISSUE TITLE
Syntax for header *columns* in tables

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#174]
<pre>
I lack the possibility to get a *column* of `&lt;th&gt;` cells (respectively how
other output formats mark header cells) in a table; it's of course usually
the leftmost column which needs to be so treated, but the proposed syntax
will allow any column(s) to be designated as header column(s).

The suggested syntax is to substitute equals for dashes in the 'column
format' row of dashes.  Given the input (silly example)

Family   Kid 1  Kid 2  Kid 3  Status
=======  ------ ------ ------ =======
Duck     Huey   Dewey  Louie  Old
Simpson  Bart   Lisa   Maggie New
Griffin  Chris  Meg    Stewie Ripoff

This will make the cells of the leftmost and rightmost columns be output as
header cells.  A more typical use would be with only the leftmost column as
a header column and the top left cell empty: 

         Kid 1  Kid 2  Kid 3 
=======  ------ ------ ------
Duck     Huey   Dewey  Louie 
Simpson  Bart   Lisa   Maggie
Griffin  Chris  Meg    Stewie

Table: Cartoon families with three kids

Of course it should work just as well with the new syntax with no header *row*:

=======  ------ ------ ------
Duck     Huey   Dewey  Louie 
Simpson  Bart   Lisa   Maggie
Griffin  Chris  Meg    Stewie
=======  ------ ------ ------

Google Code Info:
Issue #: 184
Author: bpjonsson
Created On: 2009-12-11T10:56:15.000Z
Closed On: 
</pre>

**Comment by mb21** [comment]
Closing in favour of https://github.com/jgm/pandoc/issues/1024
