### ISSUE TITLE
Bulletpoints from docx source are ignored

### ISSUE THREAD

**Issue by gordjw** [jgm/pandoc#1750]
pandoc 1.13.1 - Compiled portable on Ubuntu 14.04

As per the title, bulletpoints in a docx source file are lost on conversion to markdown and HTML (only those two formats tried so far). 
Bulletpoints in markdown source files are converted successfully into docx.

In case it matters, I did compile pandoc into a portable binary on a different VM, but they're both Ubuntu 14.04.

**Comment by jgm** [comment]
This seems to have been fixed a while back!
Closing.
