### ISSUE TITLE
[Feature Request] Support for deck.js

### ISSUE THREAD

**Issue by rgaiacs** [jgm/pandoc#1753]
[deck.js](http://imakewebthings.com/deck.js/) is another Javascript solution for slides like reveal.js.

How much difficult will be for someone that never program in Haskell (me) to hack Pandoc's reveal.js writer?

**Comment by mb21** [comment]
Latest commit of [deck.js on github](https://github.com/imakewebthings/deck.js) is from May 4, 2016. Thus closing this issue.
