### ISSUE TITLE
org-mode ignores LaTeX fragments

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#1764]
org-mode can handle http://orgmode.org/manual/LaTeX-fragments.html

Pandoc is able to handle the dollar syntax, but not the

```
\begin{equation}
   x=\sqrt{b}
\end{equation}
```

format.

e.g. I tried with

```
\begin{equation}
A^{-1} \approx \left(
\begin{array}{ccc}
  -.667 & -1.333 & 1 \\
  -.667 & 3.667  & -2 \\
  1     & -2     & 1
\end{array} \right)
\; \; {\rm and} \; \; \kappa_{\infty} (A) = 158.33
\end{equation}
```

workaround is to use two dollars when starting and closing the block.

**Comment by sjackman** [comment]
I want to use `\begin{align*}`, don't need equation numbering, and I'm rendering to PDF and HTML with MathJax. `\begin{align*}…\end{align*}` works when rendering to PDF and is ignored when rendering to HTML. `$$ \begin{align*}…\end{align*} $$` works when rendering to HTML, but when rendering to PDF gives the error `Package amsmath Error: Erroneous nesting of equation structures;`.

So, `\begin{align*}…\end{align*}` works for PDF but not HTML, and `$$ \begin{align*}…\end{align*} $$` works for HTML but not PDF. Any suggestions how I can use `\begin{align*}` with both PDF and HTML?

**Comment by mpickering** [comment]
Try using `\begin{aligned}`

**Comment by sjackman** [comment]
So simple! Thanks, Matthew.

**Comment by tarleb** [comment]
After giving it more thought and re-reading the [org-mode documentation](http://orgmode.org/manual/LaTeX-fragments.html), I believe that it is best not change this in the org reader.  LaTeX fragments should be parsed as just that.

The lua filtering system should make it easy to parse raw LaTeX blocks via the LaTeX reader if required:

``` lua
function RawBlock (elem)
  if elem.format == "latex" then
    local res = pandoc.read(elem.text, "latex")
    return pandoc.Div(res.blocks, pandoc.Attr())
  else
    return elem
  end
end
```
