### ISSUE TITLE
localization of toc-title and "figure" not working

### ISSUE THREAD

**Issue by nylki** [jgm/pandoc#1765]
Although I have set `mainlang=german` (or ngerman), the table of contents still renders as _Contents_ instead of _Inhaltsverzeichnis_
Same for figures (_figure_ instead of _Abbildung_)
I am using xelatex as latex engine. Is there anything I am missing?
Can I overwrite the strings in the template if it doesn't work natively?

thanks! :)

**Comment by vladipus** [comment]
I still don't get it. How should Contents and Figures be localized when using `--latex-engine=xelatex` ?

**Comment by jgm** [comment]
@vladipus try setting `lang: fr-FR` or whatever language you want (use the standard codes) in your document's metadata.  Pandoc has switched over to using standard language codes since this issue was last commented.

**Comment by nylki** [comment]
@vladipus In addition to @jgm, you would set the `lang` via `-V`, for example:
`pandoc --latex-engine=lualatex yourfile.md -o yourfile.pdf -V lang=de`

**Comment by vladipus** [comment]
Seems like this thingy is also mandatory for Cyrillics to work: https://github.com/jgm/pandoc-templates/pull/198
