### ISSUE TITLE
Provide a way to turn off `--smart` in LaTeX reader?

### ISSUE THREAD

**Issue by rjturner** [jgm/pandoc#1775]
I have a large LaTeX project and I am using pandoc to convert it to Markdown for future maintenance in Markdown, thus I don't want any difficult-to-type special characters like true em-dashes, elipses, and curly quotes; I just want `---` for em-dash, `...` for ellipses, and `"`/`'` for quotes.

It appears impossible to generate "non-smart" Markdown output from LaTeX (a carefully reading of the Users Guide for `--smart` and `--no-latex-ligatures` would suggest that this is an enhancement request, not a bug report, though I am not certain on this).

Take the em-dash, e.g. "`A---B`". I get:

```
$ echo "A---B" | pandoc -f latex -t markdown
A—B # that's a true em-dash, &#x2014;
```

This is what I expect, at least with some combination of `--smart` and `--no-tex-ligatures` (or "`--no-smart`"?):

```
$ echo "A---B" | pandoc -f latex -t markdown
A---B
```

I think this is reasonable, given:

```
$ echo "A---B" | pandoc -f latex -t latex
A---B

$ echo "A---B" | pandoc -f markdown -t markdown
A---B

$ echo "A---B" | pandoc -f markdown -t latex
A---B
```

**Comment by automatthew** [comment]
I believe this is related:

```latex
He said, ``In US English, prose, dialogue paragraphs preceding those which
continue a speaker's dialogue do not have closing quotation marks.

``It seems Pandoc does not handle this situation correctly.''

Really, I asked?
```

    pandoc -f latex smart.tex -t markdown -o smart.md

```markdown
He said, \`\`In US English, prose, dialogue paragraphs preceding those
which continue a speaker’s dialogue do not have closing quotation marks.

“It seems Pandoc does not handle this situation correctly.”

Really, I asked?
```

This is a blocker for using Pandoc to treat .tex as the master format to produce both ebooks and PDFs for print.  I'm thrilled with Pandoc in every other area.

**Comment by automatthew** [comment]
And then I remembered I hadn't upgraded recently.

With pandoc 1.19.1_1

```markdown
He said, “In US English, prose, dialogue paragraphs preceding those
which continue a speaker’s dialogue do not have closing quotation marks.

“It seems Pandoc does not handle this situation correctly.”

Really, I asked?
```

**Comment by jgm** [comment]
This is done in HEAD.  you can do `-f markdown-smart`
