### ISSUE TITLE
wrong file split in ePub

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#1776]
I use pandoc-1.12.3.3 and I found a bug (or an unimplemented feature) in the ePub generation.

The following source generates an ePub file that doesn’t split first-level titles:

```
<div class="frontmatter">
# Foreword

# Introduction
</div>

<div class="bodymatter">
# Chapter One

# Chapter Two

# Chapter Three
</div>

<div class="backmatter">
# Conclusions

# References
</div>
```

When wrapped in divisions, first-level titles shouldn’t be split in different chapters.

But top-level divisions should be spilt each in one file inside the ePub file.

Could you confirm this issue in latest pandoc?

**Comment by jgm** [comment]
Just tried this again, and got one big file (no splitting), which is more what I expected, and seems fine.
