### ISSUE TITLE
Pass flags/options to latex-engine

### ISSUE THREAD

**Issue by Dashed** [jgm/pandoc#1779]
Something like: `--latex-engine-opts='-shell-escape'`

Useful for https://github.com/jgm/pandoc/issues/969.

**Comment by squisher** [comment]
Seems like this should have been closed with #969, BUT --latex-engine-opt adds the option AFTER the input filename. pdflatex does not accept -shell-escape that way, it has to be before the input file.

Current pdflatex invocation:

    pdflatex "-halt-on-error" "-interaction" "nonstopmode" foo.tex "-shell-escape"

It would work if called like this:

    pdflatex "-halt-on-error" "-interaction" "nonstopmode" -shell-escape foo.tex
