### ISSUE TITLE
[Feature Req] YAML for `--latex-engine`

### ISSUE THREAD

**Issue by radioactiveasparagus** [jgm/pandoc#1780]
Hi, as part of converting a document from markdown to pdf eg.

```
pandoc source.md -o pdf.pdf
```

we need to add `--latex-engine=lualatex` for instance to get lualatex

Can we have a YAML metadata for the same thing, like it is with other commands

```

---
title: title
latex-engine: lualatex
...
```

**Comment by sumitsahrawat** [comment]
Would a dotfile in the current directory work?

**Comment by mb21** [comment]
Closing in favour of https://github.com/jgm/pandoc/issues/4627
