### ISSUE TITLE
EOF in Markdown files should be interpreted as a paragraph break

### ISSUE THREAD

**Issue by elmimmo** [jgm/pandoc#1782]
When Pandoc is provided multiple input markdown files like so:

```
pandoc section1.md section2.md
```

Pandoc will consider the last line of **section1.md** and the first line of **section2.md** as being a single paragraph, if **section1.md** does not end with a blank line.

I cannot imagine when someone would like to split a work right in the middle of a paragraph. On the contrary, I can imagine everybody assuming that the last character of a document is the last character of the text block it belongs to.

If Pandoc is merely concatenating the files and only then process the result, it should be adding a blank line after any input markdown file that does not end with a newline and only then concatenate it (or simply add a blank line between any two input markdown document irrespective of what their last character is, as even if they do end with a blank line, extra ones would produce no difference in how that markdown text has to be interpreted).

**Comment by mgansler** [comment]
What about having an option for this behavior? `--double-newlines` or something?

**Comment by jgm** [comment]
It's overkill to have an option when a user could just
insert another file containing a newline in the list of arguments.

+++ mgansler [Nov 17 15 11:05 ]:

**Comment by pkess** [comment]
Hi all,

i went over this issue as well. Isn't it possible, that pandoc outputs a warning on stderr or something when an input file does not end with a newline?
