### ISSUE TITLE
Text.Pandoc.Pretty: excessive CPU and memory usage

### ISSUE THREAD

**Issue by t-8ch** [jgm/pandoc#1785]
The file found under https://gist.github.com/t-8ch/76d21fc1321880f48eb6 triggers excessive resource consumption when converting from html to markdown/plain.
Converting to native format is reasonably fast (0.5 seconds), but plain takes over 5 gigs of RAM and several minutes to convert.

Happens with 704cfc1e3c2 (latest master as of now)

Command to reproduce `$ pandoc -f html -t plain bad.html`

**Comment by jgm** [comment]
The profiling report suggests that the problem is entirely in Text.Pandoc.Pretty.
