### ISSUE TITLE
XWiki Writer

### ISSUE THREAD

**Issue by mpickering** [jgm/pandoc#1800]
The syntax can be see [here](http://platform.xwiki.org/xwiki/bin/view/Main/XWikiSyntax).

**Comment by saigkill** [comment]
Is it possible to integrate it into any next release? That would be really great :-)

**Comment by PonderingGrower** [comment]
+1

**Comment by azarbayejani** [comment]
+1

**Comment by rkumarp** [comment]
+1

**Comment by HS-157** [comment]
+1

**Comment by mb21** [comment]
pull requests welcome :) [this pull](https://github.com/jgm/pandoc/pull/3489/commits) is a good template...

**Comment by marcbowes** [comment]
👍

**Comment by ksmoran** [comment]
+1 !

**Comment by mb21** [comment]
It doesn't help to "plus one"... what we need here is a pull request... if you have time it's not that hard... if you don't know haskell, http://learnyouahaskell.com/chapters is a good start.

**Comment by dchenbecker** [comment]
Starting work on it now. Might have a first draft for review next week.

**Comment by dchenbecker** [comment]
Started a PR with a (very) rough cut. I've tested locally and it seems to do what I want, but I need to work on unit tests and better support for various formatting options. I'm brand new to XWiki, so if someone who has more experience with XWiki could provide feedback on where I can better handle things, it would be appreciated.

**Comment by geofflangenderfer** [comment]
@dchenbecker how hard do you think it would be to write a xwiki -> markdown parser?
