### ISSUE TITLE
[Feature Request] Support for Org Mode external links

### ISSUE THREAD

**Issue by rgaiacs** [jgm/pandoc#1823]
## Summary

[Org Mode supports many types of external links](http://orgmode.org/manual/External-links.html#External-links), e.g. `[[file:foobar.png]]`. When use some of this type of external links, Pandoc raises a warning.

## How to Reproduce

~~~
$ ls
plot.png  sample.org
$ cat sample.org 
[[file:plot.png]]
$ pandoc -f org -t odt -o sample.odt sample.org
pandoc: Could not find image `file:plot.png', skipping...
$ pandoc -f org -t docx -o sample.docx sample.org
pandoc: Could not find image `file:plot.png', skipping...
~~~

## Current Behavior

Pandoc preserves the link and doesn't "parse" it.

## Expect Behavior

Pandoc "parses" the link.

## Solution Suggest

Change `src/Text/Pandoc/Readers/Org.hs` to remove `file:` from the links.

**Comment by tarleb** [comment]
This seems to be the same issue as #2227. Fixed via #3067.
