### ISSUE TITLE
Option to preserve attributes of recognized tags when converting from HTML to ePub

### ISSUE THREAD

**Issue by danmichaelson** [jgm/pandoc#1828]
If I convert from Markdown to ePub but embed some HTML in the markdown, e.g.

```
<p class="left">Some text</p>
```

then Pandoc preserves the class attribute.

But if I convert from HTML to ePub, Pandoc transforms this to

```
<p>Some text</p>
```

If I add the `-R` option to the HTML input module, Pandoc leaves tags like `<div>` and `<span>` untouched (and doesn't disturb their attributes), but it still strips attributes from "recognized" tags like `<p>`. It seems logical to add an option to leave those tags untouched too – otherwise I'm left using Markdown as my input format when my input is actually pure HTML, which is counterintuitive (and forces me to do things like preprocess my HTML to strip out the `<html>` and `<body>` tags).

Being able to add attributes such as class (or any other attribute) to HTML elements is an important part of producing an ePub with a CSS stylesheet.

**Comment by ikus060** [comment]
Sorry to bring this old ticket back. I'm using pandoc 1.15.0.6. This feature doesn't seams to be supported yet. Looking at the 'Para' structure, it doesn't support attributes. Any reason not support it ?

I will need to preprocess the HTML file to convert `<p>` into `<div>`. just to keep `class="somwething"`...

**Comment by technocrat** [comment]
@ikus060 attributes aren't in 1.15.1, either. Speaking Haskell, Para is of type Inline. Inline does have 

    Span Attr [Inline]    -- ^ Generic inline container with attributes

so my guess is that you might be able to move

   <p class="left">Some text</p>

to some construct that drops the enclosing html tags (relying on markdown to recognize it as Para and to enclose **Some Text** with 

    <span style="left">Some Text</span>

to accomplish the same thing at the expense of 6 more keystrokes.

**Comment by jgm** [comment]
+++ Richard Careaga [Oct 27 15 18:12 ]:
>   Speaking Haskell, Para
>   is of type Inline.

No, Para is of type Block.  A Para block contains a list of Inlines.

**Comment by ikus060** [comment]
This is my point why is para doesn't have Attr? From my point of view, it doesn't make any sense. In any word processor you may set a style to a paragraph!Anyway, I manage to fix this issue by preprocessing the file, replacing all <p> by <div>. Then I've create a filter to mimic the behaviors I want.

**Comment by s-nt-s** [comment]
Hi

I have the same problem with `pandoc 1.19.2.1`. I need to preserve my `class` attributes from my html when pandoc convert it in epub. At the moment I'm loosing the `class` attribute in a `ol` tag.

is it possible?

**Comment by mb21** [comment]
@s-nt-s no, not at the moment.
