### ISSUE TITLE
Please mention Perl filter framework Pandoc::Filter

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#1829]
Hi,

Similar to the Python and PHP implementations mentioned in Pandoc documentation, there is also a Perl implementation of the Pandoc filter processing: <https://metacpan.org/pod/Pandoc::Filter>.

I suggest you add that to the documentation of Pandoc.

**Comment by jgm** [comment]
This is now mentioned in the "Scripting with pandoc" document.
I'll add to README too.
