### ISSUE TITLE
filter failure emits wrong error message

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#1830]
When I make a typo in my Perl-based Pandoc filter, causing it to fail with an error if executed directly, that is wrongly treated by Pandoc as a "not found in path" error.

**Comment by jgm** [comment]
The sort of error I get (with random garbage in the perl script) is
```
pandoc: Error in $: not enough input
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/App.hs:453:42 in pandoc-2.0-FN1dPFBLRQIWh1Rn4JHGc:Text.Pandoc.App
```
which is also not very useful.

**Comment by jgm** [comment]
Ah, my mistake.  I thought I'd typed random garbage, but apparently it was a valid perl program.  (perl my.pl ran without errors!)

When I rewrote it as a program with a typo, I got:
```
syntax error at ./my.pl line 1, near "oeu;"
Execution of ./my.pl aborted due to compilation errors.
Error running filter ./my.pl
Filter returned error status 255
```
So I think this bug is fixed now.
