### ISSUE TITLE
ImageSize: size of jpeg cannot be determined

### ISSUE THREAD

**Issue by xaxam** [jgm/pandoc#1834]
The attached image raises an "Data.Binary.Get.runGet at position 158: demandInput: not enough bytes” exception in the docx writer (but not on the Latex >> PDF route) and results in corrupt docx output.

This issue is difficult to identify when you have a very long document and need to produce docx. Maybe a problem with the respective Haskell Library? Anyway, a better error message indicating the image that causes the problem would help a lot.

![problem](https://cloud.githubusercontent.com/assets/1647612/5521967/fbb12cb2-89ae-11e4-9cc3-7b6377b0ee62.jpg)

**Comment by jgm** [comment]
Reopening this.  The previous fix gave us a warning rather than a run-time error, but we still aren't extracting the size from this image, and it would be good to investigate that further (assuming that this is a valid jpeg).
