### ISSUE TITLE
Windows Server HTTPS

### ISSUE THREAD

**Issue by ytechie** [jgm/pandoc#1836]
I was having trouble converting some documents to docx, and I narrowed it down to a problem with HTTPS failing silently.

Here is the easiest way to repo:

`pandoc -o test.md https://bing.com`

In my case, I was actually converting a .HTML file to docx, and the docx had references to HTTPS images which caused it to fail. Converting the references to http fixed it.

This works fine on my Windows client machine, and I confirmed it works on a colleagues machine as well. It fails on multiple Windows Server editions.

**Comment by jgm** [comment]
How did you install pandoc?  From the binary package?
Note that there's an https cabal flag that needs to be set for https support to be enabled.  It may have been disabled when your windows binary was built, perhaps because some needed libraries weren't available...

**Comment by mszep** [comment]
I don't know if this is the same error, but on Ubuntu 14.04, with pandoc 1.13.2, I get

```
$ pandoc -o test.md https://bing.com
pandoc: FailedConnectionException2 "bing.com" 443 True <socket: 3>: hPutBuf: resource vanished (Broken pipe)
$ pandoc -o test.md https://github.com
$
```

Could it be something specific to bing?

**Comment by ytechie** [comment]
I had tried extracting the EXE from the MSI, and I also tried using the MSI to install. Here is the exact download link: http://github.com/jgm/pandoc/releases/download/1.13.1/pandoc-1.13.1-windows.msi

**Comment by ytechie** [comment]
I also tried 1.13.2, still crashes. It shows an error now, but I don't think it contains anything useful:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pandoc.exe
  Application Version:	0.0.0.0
  Application Timestamp:	54952c48
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.17415
  Fault Module Timestamp:	54504ade
  Exception Code:	40010006
  Exception Offset:	00014598
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	5598
  Additional Information 2:	559843d0285961079b8de2a186a341cc
  Additional Information 3:	3489
  Additional Information 4:	34893bfa5f7beba4fdb4429bfe1f287b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by ytechie** [comment]
Just tried version 1.14.0.1, now it says "pandoc: no store"

**Comment by jgm** [comment]
This worked fine for me with 1.14.1.
