### ISSUE TITLE
readMediaWiki doesn't handle parse errors

### ISSUE THREAD

**Issue by criticalskeptic** [jgm/pandoc#1848]
In `Text.Pandoc.Readers.MediaWiki` the only exposed function is `readMediaWiki`:

    readMediaWiki :: ReaderOptions
                  -> String
                  -> Pandoc
    readMediaWiki opts s =
    {- ... implementation here ... -}
           "source" (s ++ "\n") of
              Left err'    -> error $ "\nError:\n" ++ show err'
              Right result -> result

I'm currently parsing a Wikipedia XML dump, converting each to a Pandoc as an interim step With over 10 million articles to process, many of them are flawed. For example this is the proper format for a wikitable: `{|class=&quot;wikitable&quot;`, however one of the articles uses `{|class=wikitable`. This throws a runtime error:

     Error:
     "source" (line 55, column 9):
     unexpected "w"
     expecting "\""

(Side note, being a 10GB bzip finding the source of the error wasn't as simple as I had expected!)

I've tried taking the Wiki reader into a separate .hs file to make my own modifications, but to no avail. One of the imports `Text.Pandoc.Parsing` is not an exposed module so the following types are unavailable:
* `HasReaderOptions`
* `HasHeaderMap`
* `HasIdentifierList`

I suppose I could download the source, make the modifications I need and then compiling myself. I'm fairly new to Haskell and I'm working in a Cabal Sandbox (on Windows no less). So far compiling my own binaries into a sandbox has proved... a challenge.

Any of the following would be greatly appreciated:
* A patch that causes the parser to skip a section in case of a pattern match error
* Expose additional functions inside `Text.Pandoc.Readers.MediaWiki` so that we can do custom parsing using the library
* Re-expose the `Text.Pandoc.Parsing` module so that we can make our own variations
* A patch with `readMediaWikiEither` that returns an `Either ParseError Pandoc` (or even `readMediaWikiMaybe` with a `Maybe Pandoc`)

Alternatively, any thoughts ideas or suggestions for how to solve my issue would be great.

**Comment by criticalskeptic** [comment]
Thanks for the quick reply over the holidays!

I'll give that a try today and let you know how it goes.

**Comment by criticalskeptic** [comment]
Just tested on the first 1000 entries in the xml dump and it worked great.

FYI - pandoc-errortype is missing the templates in data/templates

    setup.exe: data/templates/default.html: does not exist
    Local\Temp\pkgConf-pandoc-1.135280.3
    -1.13.3...
    Preprocessing executable 'pandoc' for pandoc-1.13.3...

I took the templates from the master branch and it installed fine.

**Comment by jgm** [comment]
When you clone the repository you need to do

     git submodule update --init

to bring in the templates and other data files.

**Comment by jgm** [comment]
Closing, since @mpickering's changes are now merged in.
