### ISSUE TITLE
{\textwidth} in latex tabular causes table rendering failure

### ISSUE THREAD

**Issue by dsoto** [jgm/pandoc#1850]
Similar to issue #1180 

Example:
```
\documentclass{article}
\begin{document}

\begin{tabular}{p{20mm}p{20mm}p{20mm}}
foo & bar & baz \\
foo & bar & baz
\end{tabular}

\begin{tabular}{1.0\textwidth}{p{20mm}p{20mm}p{20mm}}
foo & bar & baz \\
foo & bar & baz
\end{tabular}

\end{document}
```
Output:
```
> pandoc -t markdown tabular.tex 
  ----- ----- -----
  foo   bar   baz
  foo   bar   baz
  ----- ----- -----

<span>1.0</span><span>p<span>20mm</span>p<span>20mm</span>p<span>20mm</span></span>
foo & bar & baz\
foo & bar & baz
```

**Comment by jgm** [comment]
Are you sure this is valid LaTeX?  I tried pdflatex on it and it raised
an error on l. 9, "illegal character in array arg."  I think tabular
just takes one argument (plus an optional pos argument in square brackets).

+++ Daniel Soto [Dec 31 14 17:36 ]:

**Comment by dsoto** [comment]
Sorry for the oversight.  The second environment should be {tabular*} which also takes a width parameter.
