### ISSUE TITLE
A writer for GELLMU

### ISSUE THREAD

**Issue by mardukbp** [jgm/pandoc#1851]
I would like to bring [GELLMU](http://www.albany.edu/~hammond/gellmu/) to the attention of fellow pandoc users as well as the pandoc developers. It seems to be a little-known framework for translating LaTeX documents to web formats and, judging by the examples, it does so quite well. I think it would be a nice addition to pandoc.

Quoting the manual:

> It evolved from earlier thought about delineation of a coherent subset of LaTeX commands with the property that if a LaTeX document used only those commands then it could be translated with full reliability to other formats including HTML so that documents could be prepared both for print and for the web from a single source.

**Comment by tarleb** [comment]
I just stumbled on this old issue and had a look at GELLMU. I like the idea of writing HTML with LaTeX syntax.

It seems that the project is no longer actively developed, and the download page even states

> There has not been a carefully tested release of GELLMU software since July 2007.

Based on this, I'm afraid that this is out of scope.
