### ISSUE TITLE
Task list (e.g. for GSOC)

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#1852]
Here is a list of projects that could be done in pandoc:
1.  Use `Text` instead of `String` throughout. This would involve API changes and extensive (but not too difficult) changes to
   - pandoc-types
   - pandoc
   - texmath
   - highlighting-kate
   - pandoc-citeproc
   
   Also worth considering whether it would help to use my custom text-based parser combinators from cheapskate (perhaps with some amplifications) instead of the slower parsec.
2.  <del>Add a Lines (or LineBlock) Block element, and modify readers, writers, and associated code.  Currently we just use a Para with LineBreaks. This is non-ideal, especially when converting _into_ formats allowing  line blocks. (See #1623)</del>
3.  Create a flexible system for labeling objects (images, tables, code) and referring back by number and/or link. Or, more minimally:  handle `\label` and `\ref` better when parsing LaTeX.  (See #813, #165)
4.  Automatic identifiers for images and tables in HTML output. (#208)  Must take care not to break existing documents relying on automatic identifiers for headers. (See also #1806.)
5.  Syntax and (block or inline?) element for anchors (see #1299, #1621, also http://talk.commonmark.org/t/turning-empty-link-definitions-into-anchors/893).
6.  <del>Allow attributes on links, images?  (WIP #1806)</del>
7.  <del>Add a Softbreak inline element to allow preservation of the orginal text's line breaking (#1701).</del> (in progress)
8.  Create a pure Haskell library to parse [commonmark](http://spec.commonmark.org), using the parsing strategy from the commonmark reference implementations (commonmark.js and cmark).  Make it extensible, and use it to add a new pandoc reader for commonmark.
9.  ~~Add a writer for groff ms format for a lightweight route to PDF (#1839).  [Note:  this is done in a branch, `groff_ms`, but it's not merged]~~
10.  Add a ConTeXt reader (#1423) -- should be possible to modify the LaTeX reader.
11.  Add a plain TeX writer (#1541).
12.  Make Format an enumerated type (#547).
13.  ~~Add a GNU `eqn` writer (and reader?) to texmath?~~
14.  pandoc-citeproc needs lots of attention.  The (inherited) code base is overly complex and very hard to understand in places.  It would be great if someone else were to get familiar with it, so more bugs could be fixed.
15.  Writer for the new native Kindle ebook format K8 (#1865).
16.  Find bugs from the tracker and fix them!

**Comment by mpickering** [comment]
If anyone is looking at this task list and has any questions then feel free to message me on IRC or by email.
