### ISSUE TITLE
[epub writer] - support media with no file extension

### ISSUE THREAD

**Issue by danmichaelson** [jgm/pandoc#1855]
When converting from Markdown to ePub:

If the Markdown references a web-hosted image, video, or audio URL that has no file extension (e.g. by absolute URL), Pandoc sets the mime type for the asset in content.opf to "application/octet".

Pandoc should preserve the mime type as returned by the web server so that these assets can still work. This kind of thing is common with media hosted on content delivery networks (the filename is some hash, with no extension). Web browsers (and epub) only care about the mime type, not the file extension.

**Comment by jgm** [comment]
Pandoc uses its `fetchItem` function to retrieve these things, and it
returns the mime type as well as the contents.  I see that the epub
reader is currently just ignoring the mime type, but that should be
easy enough to fix.

+++ Dan Michaelson [Jan 04 15 16:13 ]:

**Comment by danmichaelson** [comment]
Thanks, this would be great

**Comment by jgm** [comment]
It's more difficult than I'd thought at first -- the writer
was designed before fetchItem returned mime types, and
everything will need to be reorganized.  So, it definitely
should be done, but might not be quick.
