### ISSUE TITLE
[html reader] certain tables not parsed as tables

### ISSUE THREAD

**Issue by tkruse** [jgm/pandoc#1859]
Using pandoc 1.13.2:

```
  <table>
    <tr>
      <th>Type</th>
      <th>Notes</th>
    </tr>
  </table>
```

yields in ascciidoc:

```
Type
Notes
```

should yield a table-

Also encountered this problem:
```
  <table>
    <tbody>
    <tr>
      <th>Type</th>
      <th>Notes</th>
    </tr>
    <tr align="center">
      <td>x</td>
      <td>y</td>
    </tr>
    </tbody>
  </table>
```

did not yield table in ascciidoc, removing tbody tab helped.

Might be related to: https://github.com/jgm/pandoc/issues/1371

**Comment by mb21** [comment]
Pull #1885 fixes both cases in the original post.

However, concerning the case in @tkruse's additional comment: I don't know how pandoc should deal with a row that contains both `th`s and `td`s. Probably not at all since it's not representable in pandoc's data model. Alternatively, we could parse `th`s on subsequent rows as if they were `td`s.

**Comment by tkruse** [comment]
I don't know about pandocs data model, but in general table design, it does make sense sometimes to provide headers cells and normal cells in the same row, mostly if the leftmost column contains headers.

I think only 2 alternatives are viable: to error out, or to consider ```th```s as ```td```s. Whichever would be least surprising given how pandoc else handles incompatible datamodels.

**Comment by jgm** [comment]
Consider `th`s as `td`s would be the best approach -- generally pandoc tries to do something within the limitations of its data model, rather than erroring out.

+++ Thibault Kruse [Jan 17 15 10:14 ]:

**Comment by mb21** [comment]
okay, I pushed to #1885. Now we parse basically any combination of opening, closing, non-opening, non-closing combination of `thead` and `tbody` tags. The first complete row of `th`s will always be the headers, subsequent `th`s will be treated as `td`s.

**Comment by tkruse** [comment]
sounds good, thx for the effort.
