### ISSUE TITLE
[asciidoc writer] html code style writes bad asciidoc block

### ISSUE THREAD

**Issue by tkruse** [jgm/pandoc#1861]
Using pandoc 1.13.2:

HTML
```
<html lang="en">
<body>
<PRE class="badcode">No</PRE>
</body>
</html>
```

yields asciidoc:
```
code,badcode-- code,badcode
No
--
```

Note I am not sure what actually should happen with the 'badcode' class here, but this does not come out right.

**Comment by mnencia** [comment]
It happens the same from other sources

Markdown:

    ``` sh
    ls -l
    ```
Asciidoc:

    code,sh----------- code,sh
    ls -l
    -----------
