### ISSUE TITLE
ePub: Invalid HTML in title_page.xhtml

### ISSUE THREAD

**Issue by danmichaelson** [jgm/pandoc#1863]
I get this `title_page.xhtml` in my Pandoc-generated .epub:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
    <head>
      <meta charset="utf-8" />
      <meta name="generator" content="pandoc" />
      <title></title>
      <link rel="stylesheet" type="text/css" href="stylesheet.css" />
    </head>
    <body>
    <section epub:type="titlepage">
      <h1 class="main">Sports Complex, Galaxy Toyama / Odwawara Gymnasium</h1>
      <h2 class="">Greg Lynn</h2>
      <h2 class="">Canadian Centre for Architecture</h2>
      <p class="publisher">Canadian Centre for Architecture</p>
      <p class="rights"><ol start="3" type="a">
    <li>2014 CCA</li>
    </ol></p>
    </section>
    </body>
    </html>

From this metadata.yml block:

    ---
    title:
    - type: main
      text: Sports Complex, Galaxy Toyama / Odwawara Gymnasium
    creator:
    - role: editor
      text: Greg Lynn
    - role: author
      text: Canadian Centre for Architecture
    publisher: Canadian Centre for Architecture
    identifier:
    - scheme: ISBN-13
      text: urn:ISBN:978-1-927071-12-0
    rights: (c) 2014 CCA
    abstract: Greg Lynn and Japanese Architect Shoei Yoh discuss Yoh&#39;s Galaxy Toyama and Odawara Gymnasium projects from late 1980&#39;s. This is part of the CCA multi-year research project Archaeology of the Digital, investigating the development and use of computers in architecture.
    ...

This produces the following validation error in an .epub validator, due to the `<ol>` nested within a `<p>` toward the end.

>ERROR: yoh.epub/title_page.xhtml(16,44): element "ol" not allowed here; expected the element end-tag, text or element "a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "command", "datalist", "del", "dfn", "em", "embed", "epub:switch", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "map", "mark", "meter", "ns1:math", "ns2:svg", "object", "output", "progress", "q", "ruby", "s", "samp", "script", "select", "small", "span", "strong", "sub", "sup", "textarea", "time", "u", "var", "video" or "wbr" (with xmlns:ns1="http://www.w3.org/1998/Math/MathML" xmlns:ns2="http://www.w3.org/2000/svg")

This is Pandoc 1.13.2.

**Comment by danmichaelson** [comment]
Fixed it by changing "(c)" to "Copyright" in the .yml. I guess Pandoc is interpreting this as a Markdown list. Should Pandoc be parsing Markdown here?

**Comment by jgm** [comment]
Yes, we do mean to be parsing Markdown there.  You might want something
formatted in rights.

By the way, a recent template update (in the default epub templates)
changes the p tag to a div, which would have avoided the error (though
the interpretation of `(c)` would still not be what was intended.)

You can use a backslash escape:

    \(c) 2005

+++ Dan Michaelson [Jan 08 15 09:57 ]:

**Comment by danmichaelson** [comment]
Thanks very much.
