### ISSUE TITLE
Block macro in latex causes parse failure

### ISSUE THREAD

**Issue by mpickering** [jgm/pandoc#1866]
Reproduced from https://groups.google.com/d/msgid/pandoc-discuss/90cb9924-0ed1-441a-8ef2-f2e3928a165c%40googlegroups.com

-----

So this is what happens.. the macro parsing is all ok. The problem comes when \FIG is parsed. \FIG is replaced with the following..

```
{
  \begin{figure}[h!]
    \centering
    \includegraphics[width=0.5\columnwidth,angle=0]{test.jpg}
    \caption{Test caption}
    \label{fig:test.jpg}
  \end{figure}
}
```

The next line now fails

```
parseFromString inlines transformed
```

The next step is into `grouped inline` which matches the first `{`. Little does this function know, what is inside this block is actually a block level element.

Next `inline` tries to match `\begin{figure}` but all paths fail so the parse fails. Pre pandoc 1.13.3 (ie any released version of pandoc) the `parseFromString` function succeeded even if it didn't consume all the input (it just silently threw it away). Now in HEAD, it fails if not all the input is consumed.

**Comment by mpickering** [comment]
Two things need doing.

- [ ] Fix this issue
- [ ] Improve error messages when code latex macros are expanded

**Comment by jgm** [comment]
Related to #1390.

**Comment by mpickering** [comment]
I've been thinking, would the following approach be sufficient?

1) Parse `\newcommand' as normal
2) Attempt to parse the body of the macro with the `inline` parser. If this succeeds then we mark the macro as `Inline`. 
3) If 2) fails, attempt to parse the body with the `block` parser. If this succeeds then we mark the macro as `Block. 
4) If both fail then the body would not produce valid LaTeX when expanded so we can fail with hopefully a better error message at that point.
5) When parsing, add a new clause to the `block` parser which checks for `Block` macros.

Thoughts?

**Comment by lierdakil** [comment]
Soooo... I fiddled around with it a bit, and I've got myself lierdakil@b5e857c, which solves problems mentioned in this issue and issues mentioning this, without breaking anything (to my knowledge, that is, but apparently latex tests are non-exhaustive). I am, however, not entirely sure if it solves *all* associated problems. However, even cases mixing block- and inline-level macros are parsed reasonably well (notice the extra span here -- it's due to #1390):

```latex
\newcommand{\ch}[1]{\chapter{#1}}
\newcommand{\ita}[1]{\emph{#1}}

\ch{Test}\ita{hello}
```

```haskell
[Header 1 ("test",[],[]) [Str "Test"]
,Para [Span ("",[],[]) [Emph [Str "hello"]]]]
```

Comments are welcome.

**Comment by mpickering** [comment]
> I am, however, not entirely sure if it solves all associated problems.

Can you explain further?

**Comment by lierdakil** [comment]
@mpickering 
Well, I'm not familiar enough with LaTeX Reader code to claim that it will work for every case out there. I think it *should* work, given that it does perform reasonably well with issues at hand. But it does introduce extra curly braces in block-level macro expansions (again, due to #1390). Parser seems to ignore those, but I'm not 100% sure it always will (or, for that matter, should), and I'm not sure it's safe to remove them entirely.

**Comment by mpickering** [comment]
Can you describe how your fix works as well? It seem to be different from what I suggested. (Not saying it is worse but I don't understand at the moment!)

**Comment by lierdakil** [comment]
I'll try.

The idea here is to bypass this error by dealing with block-level macro expansions before it even comes to parsing inlines.

To do that, I added macro expansion code to `blockCommand`, which works pretty much exactly like inline macro expansions, but parses expanded macros as block-level elements, which will eventually (through `grouped block`) recurse back into `blockCommand`, if expansion is not an environment or `\newcommand`. Here, it's either a block-level command (one of those defined in `blockCommands`), another macro to be expanded, or neither.

If it is block-level command, macro expansion code is not executed (thanks to Haskell's laziness).
If it's a macro to be expanded (defined previously with `\newcommand`), then we go on another recursion loop.
If it's neither, then macro expansion fails with `mzero` and subsequently whole branch fails.

If whole `blockCommands` branch fails, parser will try to parse block as `paragraph`, which will eventually get to `inlineCommand`, if there are any commands left there at all.

Sorry if it sounds convoluted, it's past midnight here and I've had one too many mugs of coffee. Basic idea is simple: expand block-level macros when parsing blocks, and leave the rest for when parsing inlines.

**Comment by lierdakil** [comment]
Now that I described it, I think that both inline and block macro expansions could be optimized a bit by skipping branches that we know will fail, but I probably should leave it for later.

**Comment by lierdakil** [comment]
Disregard my last comment. Sure, it could be optimized a little, but I'd prefer to leave it as-is in case TeXMath behavior regarding #1390 changes, since current implementation is more general.

**Comment by jgm** [comment]
@lierdakil can this issue be closed now that the patch is merged?

**Comment by lierdakil** [comment]
@jgm, I believe so, yes.
