### ISSUE TITLE
The format markdown_mmd is unknown of my server

### ISSUE THREAD

**Issue by n1c01a5** [jgm/pandoc#1867]
When I run ```pandoc --from=markdown_mmd -S -o test.pdf test```,I have this error: pandoc: ```Unknown reader: markdown_mmd``` of my server whereas it works localy.

The format ```markdown``` works both of them.

**Comment by mpickering** [comment]
What version of pandoc are you using locally and on your server?

**Comment by n1c01a5** [comment]
I use 1.13 locally and 1.9 in my server. I update to 1.13 in my server and it's works.

Thx
