### ISSUE TITLE
markdown → html: tabbed code does not nest well in quote

### ISSUE THREAD

**Issue by yn-** [jgm/pandoc#1868]
In markdown to html translation, it is expected that

    ><tab>some code

is understood as code in quote. However, it is only quoted, but not as code.

#### What works?
`>` followed by 5 spaces.

#### What does not work?
`>` followed by `<tab>`
`>` followed by `<space><tab>`
`>` followed by 4 spaces

#### How to reproduce?
Create a single-line file `a.md` with the described content.
Translate it with `pandoc -s -o a.html a.md`.
```
pandoc 1.13.2
Compiled with texmath 0.8.0.1, highlighting-kate 0.5.11.1.
```

**Comment by mpickering** [comment]
Note that I would not expect `<space><tab>` to work as it would only expand to 3 spaces with the default tabstop. 

Here are the precise parsing rules.

1. A blockquote is a `>` optionally followed by a `<space>`
2. A codeblock is indented by 4 spaces (or surrounded by `)
3. Tabs are expanded to the next tabstop (ie multiple of 4 by default)

This explains your results:

1. `><tab>code` - `<tab>` is expanded to 3 spaces which is not enough anyway.
2. `><space><tab>` - this is also only 3 spaces
3. `><4space>` - The first space is consumed by the `>` so there are only 3 spaces before the code.

I'm not sure if this is right. It is much clearer to use fenced code blocks imo anyway.

**Comment by yn-** [comment]
But then the space become mandatory?

For the tab, I wish it could be treated as its own.

(Thanks for the quick reply.)

**Comment by mpickering** [comment]
The tab behaves as if it would in an editor. When the blockquote marker is followed by an element which is whitespace dependent (ie codeblocks) then it is mandatory yes.

Personally I would write something like this.. is there a reason you prefer indented codeblocks?

```
> `code`
```

**Comment by yn-** [comment]
I have read the code and understand how it works.  I think it was the default tab expansion that was unexpected.  Nevertheless, I am happy with the tab-preserving option now (-p).

If you don't mind, I can close the issue.
