### ISSUE TITLE
 pandoc/tests/writer.html contains invalid XML

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#1869]
@mpickering, as warned in #1864 pandoc/tests/writer.html contains invalid XML.

There are two issues:

1. Identifiers must be unique (three elemens contain `id="bar"`).

2. Elements should be closed or self-closed (`<hr/>` instead of `<hr>`).

I hope it helps.

**Comment by jgm** [comment]
I don't think this is a problem.  We need the output to include `<hr>`,
because that's part of a test of raw HTML pass-through, and this is
valid HTML.  Same goes for the repeated IDs -- raw HTML gets passed
through.  "Fixing" this would just mean we aren't testing certain
things.

Is there some reason why `writer.html` should be valid XML?

+++ Pablo Rodríguez [Jan 11 15 05:07 ]:

**Comment by ousia** [comment]
> I don't think this is a problem. We need the output to include `<hr>`, because that's part of a test of raw HTML pass-through, and this is valid HTML.

AFAIK, this isn’t valid XHTML (or this is what the [W3C Validator](http://validator.w3.org/) says).

> Same goes for the repeated IDs -- raw HTML gets passed through. "Fixing" this would just mean we aren't testing certain things.

Well, I guess that makes invalid HTML.

> Is there some reason why `writer.html` should be valid XML?

I was trying to parse the HTML directly with ConTeXt ([Dealing with XML in ConTeXt MkIV](http://www.pragma-ade.com/general/manuals/xml-mkiv.pdf)). But it must be valid XML.

**Comment by jgm** [comment]
+++ Pablo Rodríguez [Jan 11 15 13:34 ]:
>> I don't think this is a problem. We need the output to include `<hr>`, because that's part of a test of raw HTML pass-through, and this is valid HTML.
>
>AFAIK, this isn’t valid XHTML (or this is what the [W3C Validator](http://validator.w3.org/) says).

No, it isn't.  But Markdown allows you to pass through arbitrary HTML,
and it's fine as HTML.

>> Same goes for the repeated IDs -- raw HTML gets passed through. "Fixing" this would just mean we aren't testing certain things.
>
>Well, I guess that makes invalid HTML.

Yes - garbage in, garbage out.  The raw HTML feature of Markdown means
we can't guarantee that pandoc will produce valid HTML.

>I was trying to parse the HTML directly with ConTeXt ([Dealing with XML in ConTeXt MkIV](http://www.pragma-ade.com/general/manuals/xml-mkiv.pdf)). But it must be valid XML.

Pandoc will produce valid XHTML as long as you don't use raw HTML in the
source.

**Comment by ousia** [comment]
> Pandoc will produce valid XHTML as long as you don't use raw HTML in the source.

@jgm, sorry for the misunderstanding.

pandoc generates valid XHTML and of course pandoc should not correct raw code. That wasn’t the issue.

Would you be interested in a pull request that corrects the raw XHTML in `writer.markdown`?
