### ISSUE TITLE
Textile to HTML removes attributes

### ISSUE THREAD

**Issue by webPapaya** [jgm/pandoc#1875]
Pandoc removes all attributes when converting Textile to HTML. According to the Reference([Textile Reference - Section 4](http://redcloth.org/hobix.com/textile/)) attributes html attributes are supported by textile. 

```
p{font-size:0.8em}. *TxStyle* is a documentation project of Textile for "Textpattern CMS":http://textpattern.com.
```

becomes 

```html
<p>
  <strong>TxStyle</strong> is a documentation project of Textile for <a href="http://textpattern.com">Textpattern CMS</a>.
</p>
```
[Demo](http://johnmacfarlane.net/pandoc/try/?text=p%7Bfont-size%3A0.8em%7D.+*TxStyle*+is+a+documentation+project+of+Textile+for+%22Textpattern+CMS%22%3Ahttp%3A%2F%2Ftextpattern.com.&from=textile&to=html)

Other attributes also get truncated:
http://johnmacfarlane.net/pandoc/try/?text=p(example1).+An+example&from=textile&to=html

**Comment by jgm** [comment]
Pandoc's document model doesn't have a place for attributes
on paragraphs.  So there's not much we can do about this at
the moment.  All of pandoc's conversions are limited by
the need to pass through the underlying document model,
which is less expressive than many of the formats supported.
So, conversions from formats more expressive than Markdown
are usually going to be lossy.

**Comment by ousia** [comment]
@jgm, as a workaround, for those elements that don’t allow attributes (yet?), I have the following proposal.

How about wrapping those elements around divs or spans?

**Comment by jgm** [comment]
It could be done.  It might lead to very cluttered output, and would
require manual changes in CSS to work properly. So I'm not sure if this
is what people who use pandoc to convert from textile would want.
Maybe they can comment here.

+++ Pablo Rodríguez [Jan 14 15 07:06 ]:

**Comment by ousia** [comment]
@jgm, it is a cumbersome workaround, I agree.

Do you have any plans to implement attributes for all (block and inline) elements?
