### ISSUE TITLE
Org reader ignoring header attributes

### ISSUE THREAD

**Issue by edavis** [jgm/pandoc#1877]
Hello all,

I've noticed that header attributes in Org don't get recognized as such. It treats them as part of the header text:

```bash
$ pandoc -f org -t native
* Hello World {#custom .class key=value}
^D
[Header 1 ("",[],[]) [Str "Hello",Space,Str "World",Space,Str "{#custom",Space,Str ".class",Space,Str "key=value}"]]
```

Markdown works fine:

```bash
$ pandoc -f markdown -t native
# Hello World {#custom .class key=value}
^D
[Header 1 ("custom",["class"],[("key","value")]) [Str "Hello",Space,Str "World"]]
```

This is with pandoc 1.13.2.

Not sure if this is by design or maybe there's another syntax for header attributes in Org. But, if possible, I'd love to see Markdown style header attributes added to the Org reader.

Thanks!

**Comment by tarleb** [comment]
Markdown and Org are completely different formats. Mixing them would probably not be a good idea.

Pandoc tries to mimic Emacs' behavior when parsing Org mode. It is currently missing some features (e.g. automatic headlines IDs) but adds others (like citations).  The idiomatic way to add header attributes would probably be to parse `:PREFERENCE:` sections:

```
* Hello World
  :PREFERENCES:
  :id: custom
  :class: my-class
  :key: value
  END
```

The pandoc org parser currently ignores those blocks.  I hope someone gets around to implement the missing code in the not-too-distant future. It is still on my todo list.

**Comment by edavis** [comment]
Ah, that makes sense. Not a show-stopper or anything for me, just something I ran across.

Thanks.

**Comment by fommil** [comment]
would this allow adding attributes to the `section` in reveal.js? One thing in particular I'd love to be able to do is set the `data-background="./some/image.jpg"` which allows setting the background on a per-slide basis.

**Comment by tarleb** [comment]
Yes, property drawers would most likely help with that. I haven't thought this through yet, but I expect this to require some bigger changes to the reader.  I'd need approximately one weekend of coding, not sure when I have the time for this.  Help would be very welcome.

**Comment by fommil** [comment]
heh, sadly all my weekends are booked out on ensime for about as far as I can possibly see ahead

**Comment by tarleb** [comment]
Just keep it in mind if you ever feel the sudden urge to do some haskell coding :wink:
