### ISSUE TITLE
Consecutive inline footnotes

### ISSUE THREAD

**Issue by anntzer** [jgm/pandoc#1878]
Pandoc seems to choke on consecutive inline footnotes:
```
$ echo 'foo^[bar]^[baz]' | pandoc -t latex
foo\textsuperscript{{[}bar{]}}{[}baz{]}
```
Of course there's an ambiguity there, but I'd like to believe that the "multiple footnote" interpretation is more likely to be the correct one in practice.

**Comment by ousia** [comment]
@anntzer, why not `foo^[bar] ^[baz]`?

LaTeX might have a way to handle multiple footnotes (I guess).

But in other document formats,

> foo¹²

should be read as footnote twelve.

> foo¹ ²

would be the first and second footnotes.

What am I missing from your explanation?

**Comment by jgm** [comment]
You could use a unicode thin space U+2009 between the two footnotes.

**Comment by jgm** [comment]
Sorry, my mistake.  A unicode thin space till gives you a superscript.

**Comment by anntzer** [comment]
@ousia has a fair point there.  I would still prefer if it was supported but I can do without.

**Comment by ousia** [comment]
@jgm, even a zero-width space gives superscript.

@anntzer, I cannot recall whether a footnotes package in LaTeX that could handle that. If not, your consecutive footnotes are misleading.

BTW, using long footnotes does what you want:

```
footnote[^bar][^baz]

[^bar]: footnote

[^baz]: consecutive footnote
```

**Comment by anntzer** [comment]
`footmisc` has a `multiple` option, which will handle this, inserting a superscript comma.
