### ISSUE TITLE
Not all float literals are parsed correctly for code highlighting

### ISSUE THREAD

**Issue by johguenther** [jgm/pandoc#1879]
Some float constants in code blocks are rendered partly in red when syntax highlighting is used with pandoc 1.13.2, because not all float literals are detected as such. For example, the following markdown

    fails:

    ~~~cpp
    0.1f
    1.0f
    -0.1f
    -1.0F
    -1.0L
    ~~~

    works:

    ~~~cpp
    1e3
    0.f
    1.F
    ~~~

is [translated to the following LaTeX](http://johnmacfarlane.net/pandoc/try/?text=fails%3A%0A%0A~~~cpp%0A0.1f%0A1.0f%0A-0.1f%0A-1.0F%0A-1.0L%0A~~~%0A%0Aworks%3A%0A%0A~~~cpp%0A1e3%0A0.f%0A1.F%0A~~~&from=markdown&to=latex) (where it is easy to see that not all floats are entirely wrapped in `\FloatTok{}`):

    fails:

    \begin{Shaded}
    \begin{Highlighting}[]
    \FloatTok{0.}\ErrorTok{1f}
    \FloatTok{1.}\ErrorTok{0f}
    \FloatTok{-0.}\ErrorTok{1f}
    \FloatTok{-1.}\ErrorTok{0F}
    \FloatTok{-1.}\DecValTok{0L}
    \end{Highlighting}
    \end{Shaded}

    works:

    \begin{Shaded}
    \begin{Highlighting}[]
    \FloatTok{1e3}
    \FloatTok{0.f}
    \FloatTok{1.F}
    \end{Highlighting}
    \end{Shaded}

Expected output is

    ...
    \begin{Highlighting}[]
    \FloatTok{0.1f}
    \FloatTok{1.0f}
    \FloatTok{-0.1f}
    \FloatTok{-1.0F}
    \FloatTok{-1.0L}
    \end{Highlighting}
    ...

**Comment by jgm** [comment]
This is really an issue in jgm/highlighting-kate, but for convenience
you can leave this here.

The kate highlighting definition for CPP contains

```
        <RegExpr attribute="Float" context="#stay" String="[\+\-]?([0-9]+[Ee][\+\-]?[0-9]+|([0-9]+\.|\.[0-9]+|[0-9]+\.[0-9]+)([Ee][\+\-]?[0-9]+)?)[FfLl]?"
        />
```

This is converted to what should be an equivalent regex in the generated Haskell module:

```
compileRegex True
"[\\+\\-]?([0-9]+[Ee][\\+\\-]?[0-9]+|([0-9]+\\.|\\.[0-9]+|[0-9]+\\.[0-9]+)([Ee][\\+\\-]?[0-9]+)?)[FfLl]?"
```

As far as I can see, this looks like it should match your floats.  So further investigation will be needed.


+++ Johannes Günther [Jan 14 15 02:10 ]:

**Comment by jgm** [comment]
I'm moving this over to https://github.com/jgm/highlighting-kate/issues/57
You should star that issue.
