### ISSUE TITLE
Add support for links to TOC and pandoc_title_block

### ISSUE THREAD

**Issue by Crazyjavahacking** [jgm/pandoc#1880]
It will be very useful especially for large documents to be able to make a link to TOC or pandoc_title_block (using similar syntax to {#...}).

Then I could make a link to very top of the document.

**Comment by jgm** [comment]
The default template puts the table of contents in

    <div id="TOC">
    ...
    </div>

So you can link to it with `#TOC`.  If you want other anchors in the
header, you can define them in a default template.

**Comment by Crazyjavahacking** [comment]
John, thanks for your response.

From the html template we can also directly link to author, title, header, etc.
