### ISSUE TITLE
HTML reader doesn't recognise table alignments

### ISSUE THREAD

**Issue by mpickering** [jgm/pandoc#1881]
See [here](https://groups.google.com/d/msgid/pandoc-discuss/d35eb586-e8ab-4a33-94d5-d9f68c1da8bc%40googlegroups.com?utm_medium=email&utm_source=footer) for more details

**Comment by jgm** [comment]
Indeed, the HTML reader just imposes default alignment on all columns.  Some better heuristics are no doubt possible.
