### ISSUE TITLE
citation-abbreviations fails?

### ISSUE THREAD

**Issue by plantarum** [jgm/pandoc#1883]
I can't seem to get citations to work using citations-abbreviations. A minimal working example *without* citation-abbreviations (a minimum non-working example follows):

Working Example
==============

input.md:

~~~~ 
---
bibliography: /home/tws/scratch/combined.bib
---

Lots of interesting debate on this topic [e.g., @jost_2008].

# References
~~~~

combined.bib:

~~~~
@String{mol_ecol = "Mol. Ecol."}
@article {jost_2008,
  author =       {Jost, Lou},
  title =        {{GST} and its relatives do not measure differentiation},
  journal =      mol_ecol,
  volume =       17,
  number =       18,
  publisher =    {Blackwell Publishing Ltd},
  issn =         {1365-294X},
  url =          {http://dx.doi.org/10.1111/j.1365-294X.2008.03887.x},
  doi =          {10.1111/j.1365-294X.2008.03887.x},
  pages =        {4015--4026},
  keywords =     {differentiation, diversity, GST, heterozygosity, mutation
                  rate, partition},
  year =         2008,
}
~~~~

Processed successfully with:

~~~~
pandoc input.md --output input.pdf --filter pandoc-citeproc 
~~~~

This produces a nice pdf with the references properly inserted.

Non-working example
=================

If instead I try this:

input.md
~~~~
---
bibliography: /home/tws/scratch/test.bib
citation-abbreviations: /home/tws/scratch/test-ab.bib
---

Lots of interesting debate on this topic [e.g., @jost_2008].

# References
~~~~

test.bib:

~~~~
@article {jost_2008,
  author =       {Jost, Lou},
  title =        {{GST} and its relatives do not measure differentiation},
  journal =      mol_ecol,
  volume =       17,
  number =       18,
  publisher =    {Blackwell Publishing Ltd},
  issn =         {1365-294X},
  url =          {http://dx.doi.org/10.1111/j.1365-294X.2008.03887.x},
  doi =          {10.1111/j.1365-294X.2008.03887.x},
  pages =        {4015--4026},
  keywords =     {differentiation, diversity, GST, heterozygosity, mutation
                  rate, partition},
  year =         2008,
}
~~~~

test-ab.bib:

~~~~
@String{mol_ecol = "Mol. Ecol."}
~~~~

and processed with:

~~~~
pandoc input.md --output input.pdf --filter pandoc-citeproc 
~~~~

I get the following error:

> pandoc-citeproc: Failed reading: satisfy
> pandoc: Error running filter pandoc-citeproc

Is this a bug, or am I doing something wrong?

**Comment by jgm** [comment]
See
https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md

under citation-abbreviations.  The file needs to be in a special JSON
format.

**Comment by plantarum** [comment]
I see. But it looks like I can provide multiple files to the bibliography: setting? That might work instead.

**Comment by mpickering** [comment]
Yes, you can provide multiple bibliography files.

**Comment by plantarum** [comment]
I tried this:

~~~~
---
bibliography:
    - /home/tws/texmf/bibtex/bib/ab.bib
    - /home/tws/texmf/bibtex/bib/ty2.bib
---

Lots of interesting debate on this topic [e.g., @jost_2008].

# References
~~~~

But the strings in ab.bib (i.e., `@String{mol_ecol = "Mol. Ecol."}`) aren't inserted in the citation that is produced. Instead of presenting the journal title as `Mol. Ecol.`, it shows up as `mol_ecol`, with the e rendered as a subscript. What syntax should I be using to get the strings interpreted by bibtex in the processing? Or does pandoc use its own processing here?

Thanks for your patience.

Tyler

**Comment by jgm** [comment]
Pandoc does its own processing, including conversion from bibtex format.

As you can see from your original working example, `@String{..}` is supported.  However, the processing is done on a per-file basis, so a `@String{..}` in one bibtex file won't affect processing in another.

You could always concatenate your files before passing them to pandoc, couldn't you?

**Comment by plantarum** [comment]
Yes, in that case it's easy enough to wrap the call to pandoc up with cat-ing the bibs in a script. I wanted to see if it was necessary before doing so.

I'm very optimistic that pandoc (with knitr) will let me switch to markdown from latex now. Thanks for your help!
