### ISSUE TITLE
Convert Footnotes failed in html to docx

### ISSUE THREAD

**Issue by acgtyrant** [jgm/pandoc#1889]
the exact command line used: `pandoc -o 1.docx 1.html`

the exact input used:

	<ol style="list-style-type: decimal">
	<li>xv6<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>.</li>
	</ol>
	<div class="footnotes">
	<hr />
	<ol>
	<li id="fn1"><p>http://pdos.csail.mit.edu/6.828/2014/index.html<a href="#fnref1">↩</a></p></li>
	</ol>
	</div>

the output received:

![deepinscreenshot20150119113452](https://cloud.githubusercontent.com/assets/3921062/5795644/6b45d506-9fcf-11e4-9ce8-b9d36ec7175f.png)

**Comment by jgm** [comment]
There is no standard syntax for footnotes in HTML.  There are lots of different ad hoc ways of marking up footnotes, including the one you give below.  But as there's no standard, pandoc doesn't try to guess what is a footnote in HTML.

**Comment by acgtyrant** [comment]
Thank you for your hand working!
