### ISSUE TITLE
Support for reveal.js v3.0.0

### ISSUE THREAD

**Issue by eddie-dunn** [jgm/pandoc#1891]
Markdown presentations generated with pandoc don't seem to work with the latest release of reveal.js. With reveal.js `v2.6.2` it was enough to add a `reveal.js` symlink to the directory containing the html file generated by pandoc. With reveal.js `v3.0.0` this no longer works.

Support would be appreciated.

**Comment by jgm** [comment]
See https://github.com/jgm/pandoc-templates/pull/78
This simple change to your revealjs template should help.  But other changes may also be needed.

**Comment by jgm** [comment]
Or, you could simply generate the minified versions of revealjs css and js.

**Comment by eddie-dunn** [comment]
Yeah, I symlinked `reveal.min.css -> reveal.css` and `reveal.min.js -> reveal.js`, within their respective directories, and it worked, thanks.

**Comment by sordina** [comment]
This seems to be more of an issue when you attempt to use the --self-contained capabilities as the minified versions no longer exist in source control. I'd suggest simply not referencing the minified versions at all since it doesn't impact performance that much.

**Comment by jgm** [comment]
I've already merged a change to the default reveal.js template
in pandoc-templates that refers to the non-minified versions.

+++ Lyndon Maydwell [Jan 21 15 19:30 ]:

**Comment by sordina** [comment]
My mistake, I thought I'd checked but I was looking at the older version.

Thanks jgm!

**Comment by rotnicki** [comment]
So what exactly should I do (step by step) to make pandoc generate correct version of html file in order to work with the latest version of reveal.js? Unfortunately I do not understand the above hints.

**Comment by phillipadsmith** [comment]
@rotnicki --
Steps that work for me:

* touch slides.md (put your markdown here)
* bower init (you'll need bower for this; fill in the options)
* bower install reveal.js --save 
* ln -s bower_components/reveal.js reveal.js
* cd reveal.js
* npm install . (installing reveal's grunt dependencies; you'll need npm for this)
* grunt (you'll need grunt for this; minifies the js and the css)
* cd ..
* pandoc -t revealjs -s slides.md -o index.html

Only issue now is that theme support doesn't seem to be working (link to CSS file is not updated).

Phillip.

**Comment by KurtPfeifle** [comment]
On Tue, Feb 17, 2015 at 2:38 AM, Phillip Smith <notifications@github.com>
wrote:

> @rotnicki <https://github.com/rotnicki> --
> Steps that work for me:
>
>    - touch slides.md (put your markdown here)
>    - bower init (you'll need bower for this; fill in the options)
>    - bower install reveal.js --save
>    - ln -s bower_components/reveal.js reveal.js
>
>
Before your post, I didn't know what "bower" is. Now, after googling a bit,
I hope I can get it to work without this extra dependency.

My goal is to check out the current HEAD source of reveal.js from Git
(plus, maybe a "stable" branch -- even a pre-3.0 one) and make this work
"as-is" (with the option to symlink-switch between 2.x and 3.0 if required).

If I succeed, I'll post it here. (If anyone has done so already, please let
us know and help me save some time and effort...)


>
>    - cd reveal.js
>    - npm install . (installing reveal's grunt dependencies; you'll need
>    npm for this)
>    - grunt (you'll need grunt for this; minifies the js and the css)
>    - cd ..
>    - pandoc -t revealjs -s slides.md -o index.html
>
> Only issue now is that theme support doesn't seem to be working (link to
> CSS file is not updated).
>
> Phillip.
>

**Comment by Rufflewind** [comment]
The way I made it work was to obtain [reveal.js directly from GitHub](https://github.com/hakimel/reveal.js) and then use the provided Gruntfile to generate all the minified code.  Specifically, make sure [node.js](http://nodejs.org) installed and then run the following commands within the `reveal.js` directory:

```sh
npm install --python=python2
npm install grunt-cli
node_modules/grunt-cli/bin/grunt --force
```

There is still another unrelated problem however: `Reveal.initialize` no longer accepts `theme` as an argument so the correct way is to set the stylesheet directly (line 28 of the template):

```html
<link rel="stylesheet" href="$revealjs-url$/css/theme/$if(theme)$$theme$$else$simple$endif$.css" id="theme">
```

As a side-note: the default theme of reveal.js is "black" so you could also change "simple" to "black" if you want to conform to their artistic taste :P

**Comment by KurtPfeifle** [comment]
Thanks, Rufflewind, for your added hints.

However, I want to avoid adding all of

   1. npm
   2. python
   3. grunt
   4. node

to the mix of

   1. materially installed requirements and pre-requisites
   2. mentally learned pre-knowhow

before I can settle on my existing Markdown+Pandoc (+a little reveal.js)
knowledge assets in order to produce slides...

There sure must be a way.

**Comment by jgm** [comment]
Have you been following the changes to  the default revealjs
template in jgm/pandoc-templates?

We now default to the "black" theme, and the theme is set
in the stylesheet.

Also we link to non-minified js and css files, so you
can use a freshly cloned reveal.js repository, with no
need to generate the minified files.


+++ Rufflewind [Feb 17 15 15:33 ]:

**Comment by Rufflewind** [comment]
> However, I want to avoid adding all of

**Comment by Rufflewind** [comment]
> Have you been following the changes to  the default revealjs template in jgm/pandoc-templates?

I saw the change towards unminified files but not the other one.  My comment was regarding the latest on Hackage, not HEAD.

**Comment by xverges** [comment]
@KurtPfeifle Not sure if i'm misunderstanding your question, but the simple solution is to save locally the [updated template from pull request 78](https://raw.githubusercontent.com/EoinTravers/pandoc-templates/8fd90a51ffcebb8ca024377ed6feff1be21ff715/default.revealjs) and call pandoc with the additional param `--template=wherever_you_saved\default.revealjs`

**Comment by phillipadsmith** [comment]
@xverges That doesn't seem to work, oddly. 

I've saved https://raw.githubusercontent.com/EoinTravers/pandoc-templates/8fd90a51ffcebb8ca024377ed6feff1be21ff715/default.revealjs into the presentation directory and then ran `pandoc --template=default.revealjs -t revealjs -s slides.md -V theme=black -o index.html` and the resulting file is not using the right CSS link.

Thoughts?

**Comment by phillipadsmith** [comment]
Hmmm... I've also tried just replacing the template directly (/usr/local/Cellar/pandoc/1.13.1/share/x86_64-osx-ghc-7.8.3/pandoc-1.13.1/data/templates/default.revealjs) and the -V theme=black doesn't seem to do anything.

**Comment by phillipadsmith** [comment]
Using https://github.com/jgm/pandoc-templates/blob/master/default.revealjs does work however.

**Comment by jgm** [comment]
I'm calling this issue fixed.  If there are further reveal.js issues, besides what has already been fixed in the template, please open a new issue.
