### ISSUE TITLE
How to remove title anchor when converting docx to markdown?

### ISSUE THREAD

**Issue by yyexplore01** [jgm/pandoc#1893]
I would like to convert a word file to markdown ,  but the there's always `<span id="bookmark111" class="anchor"><span id="bookmark112" class="anchor"><span id="_Toc407035152" class="anchor"><span id="_Toc409603710" class="anchor"></span></span></span></span>`  for the tiles in output MD file

how to remove the `<span> ...` ?

**Comment by jgm** [comment]
You could remove all spans using a simple pandoc filter.

Using the python pandocfilters package,

``` python
#!/usr/bin/env python

"""
despan.py
Pandoc filter to convert all regular text to uppercase.
Code, link URLs, etc. are not affected.
"""

from pandocfilters import toJSONFilter, Str

def despan(key, value, format, meta):
  if key == 'Span':
    return []

if __name__ == "__main__":
  toJSONFilter(despan)
```

```
chmod +x despan.py
pandoc --filter ./despan.py [rest of the arguments as usual]
```

+++ yyexplore01 [Jan 20 15 22:23 ]:

**Comment by yyexplore01** [comment]
ok, I see, thanks!
