### ISSUE TITLE
Which packages do I need on Ubuntu?

### ISSUE THREAD

**Issue by zloy531** [jgm/pandoc#1894]
Hi! i try to start use pandoc? but after install from standart repository:
`pandoc x.md -o x.pdf`
`pandoc: Error producing PDF from TeX source.
! Font T1/cmr/m/n/10=ecrm1000 at 10.0pt not loadable: Metric (TFM) file not fou
nd.
<to be read again> 
                   relax 
l.100 \fontencoding\encodingdefault\selectfont
`
I have already installed texlive-latex-base, texlive-latex-base and texlive-latex-extra. What I need else?

**Comment by r-gaia-cs** [comment]
Hi zloy531,

> Hi! i try to start use pandoc? but after install from standart repository:
> `pandoc x.md -o x.pdf`
> `pandoc: Error producing PDF from TeX source.
> ! Font T1/cmr/m/n/10=ecrm1000 at 10.0pt not loadable: Metric (TFM) file not fou
> nd.
> <to be read again> 
>                    relax 
> l.100 \fontencoding\encodingdefault\selectfont
> `
> I have already installed texlive-latex-base, texlive-latex-base and texlive-latex-extra. What I need else?

From http://tex.stackexchange.com/a/116377

    you need to install texlive-fonts-recommended

Cheers,
Raniere
