### ISSUE TITLE
Windows: Could not fetch... and encoding problems using slidy

### ISSUE THREAD

**Issue by KaiHufenbach** [jgm/pandoc#1896]
Hi,

I am trying to use pandoc on Windows 7, latest version 1.13.2,

Used the following MarkDown for testing purposes. I also attached pictures of outputs. 
The following is recognizable:
- Special chars seem to break, using slidy
- Using slidy with --self-contained is not even possible due to download problems (tested link in browser, works, also deactivated windows firewall)

```
% Test

# Test
öäü

# Test
öäü


# Test 


<!-- 

Breaks with:
pandoc.exe: Could not fetch http://www.w3.org/Talks/Tools/Slidy2/styles\../graph
ics/nofold-dim.gif
StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("
    pandoc test.md -o test_slidy.html -t slidy --self-contained --smart 

Does not provide any slides, also breaks special Characters:
    pandoc test.md -o test_slidy.html -t slidy --smart 

Works!
    pandoc test.md -o test.html -t html --self-contained --smart 
-->
```

![test_slidy html](https://cloud.githubusercontent.com/assets/959063/5867043/b186750a-a297-11e4-992e-10f0fed15ce5.png)
![test html](https://cloud.githubusercontent.com/assets/959063/5867053/ca781104-a297-11e4-8481-6ee8d81afac9.png)

**Comment by mpickering** [comment]
For #2 you might need to set your browser encoding to UTF-8.

I suspect that your problem is that the slidy utl is protocol agnostic. (ie starts with `//`) This means that the same url can be used for http or https but fails to render locally. You can try adding a protocol and then it might work correctly.

**Comment by KaiHufenbach** [comment]
Inserted exactly this URL to Internet Explorer: http://www.w3.org/Talks/Tools/Slidy2/styles\../graph
ics/nofold-dim.gif
 
Which works perfectly. Sorry, but I could not follow exactly what you mean. In my *.md there is no other URL.

I checked the *_slidy.html which looks like:

```
<div id="test" class="slide section level1">
<h1>Test</h1>
<p>öäü</p>
</div>
<div id="test-1" class="slide section level1">
<h1>Test</h1>
<p>öäü</p>
</div>
<div id="test-2" class="slide section level1">
<h1>Test</h1>
<!-- 


Breaks with:
pandoc.exe: Could not fetch http://www.w3.org/Talks/Tools/Slidy2/styles\../graph
ics/nofold-dim.gif
StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("
    pandoc test.md -o test_slidy.html -t slidy --self-contained --smart 

Does not provide any slides, also breaks special Characters:
    pandoc test.md -o test_slidy.html -t slidy --smart 

Works!
    pandoc test.md -o test.html -t html --self-contained --smart 
-->
</div>

```

**Comment by jgm** [comment]
This is now fixed, it seems.
