### ISSUE TITLE
Specify identifier for tables?

### ISSUE THREAD

**Issue by fps-vogel** [jgm/pandoc#1898]
Is there a way in pandoc's markdown to reproduce `<table id="foo">`? As in kramdown,

```
{:.foo}
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

**Comment by jgm** [comment]
No, not at the moment. However, you can put the whole table inside

```
<div id="foo">

...table...

</div>
```

and that should allow you to style the table with CSS.

**Comment by fps-vogel** [comment]
That's exactly what I needed, thanks!
