### ISSUE TITLE
pandoc: Could not find data file templates/default.latex

### ISSUE THREAD

**Issue by n1c01a5** [jgm/pandoc#1899]
I have installed pandoc with cabal in ~/.cabal and I do link with binaries: ```ln ~/.cabla/bin/pandoc /usr/bin/pandoc``` but I have this error when I compile a doc:
```
pandoc: Could not find data file templates/default.latex
```

Thx for advance

**Comment by jgm** [comment]
If you want the binary to be relocatable, you should install with
the `embed_data_files` flag:

    cabal install -fembed_data_files pandoc

+++ Wagner Nicolas [Jan 24 15 10:06 ]:

**Comment by n1c01a5** [comment]
Thx it works.
