### ISSUE TITLE
Markdown to PDF: Header following an Image does not render as a Header

### ISSUE THREAD

**Issue by michael-okeefe** [jgm/pandoc#1904]
**Platform/Version**: Mac OS X using Pandoc 1.13.2.

**Preconditions**: A file `junk.md` and any valid PNG image called `junk.png` in some directory.

`junk.md`

~~~
![](junk.png)\

# Hello
~~~

Note: in the file above, there is not trailing space after `![](junk.png)\` and thus it is technically incorrect (to escape figure drawing, we're supposed to end with a nonbreaking space according to the [user guide](http://johnmacfarlane.net/pandoc/README.html#images)). That said, `![](junk.png)\` without the trailing space appears to work in other cases but fails for the case of a header following the image and maybe difficult to catch as a bug (this happened to me due to editor settings to remove trailing whitespace and took a bit to track down).

**Action**: rendered the above with `pandoc --out junk.pdf junk.md`

**Expected**: A valid PDF with an image (no figure) followed by a header.

**Actual Result**: The header `# Hello` is not being recognized as a header and, instead, is dropped into the PDF output as a literal `# Hello` in fixed width font.

The result of the command `pandoc --out junk.tex junk.md` is:

~~~
\includegraphics{junk.png}\\ \# Hello
~~~

**Speculation**: issue with an edge case in parsing?

**Work around**: If a blank space is placed after the `\`, then rendering happens correctly.

~~~
![](junk.png)\ 

# Hello
~~~

**Comment by mpickering** [comment]
I speculate without much investigation:

Markdown requires a blank line between block elements. By using the `\` you are escaping one newline so there is only one newline between the blocks (instead of two).

**Comment by michael-okeefe** [comment]
Thank you, I've confirmed that if you place two lines after the `![](junk.png)\` (no trailing space) that it does render correctly:

~~~
![](junk.png)\


# Hello
~~~

Thanks!
