### ISSUE TITLE
apostrophe being misinterpreted as open quote

### ISSUE THREAD

**Issue by scaramouche1** [jgm/pandoc#1909]
Pandoc interprets the following input wrongly

    The value of the $x$'s and the systems' condition.

by interpreting that "s and the systems" is in between single quotes, thus rendering the following:

    The value of the x`s and the systems' condition.

The problem has to do with the character before the apostrophe not being a letter, as the problem does not happen with this other phrase:

    Do's and don'ts.

Is there a simple fix for this problem?

**Comment by mpickering** [comment]
Looks like this specific case could be fixed very easily but the more general story looks like it requires a bit more thought.

**Comment by jgm** [comment]
It's very difficult to distinguish apostrophes from single
quotes with perfect accuracy.  We already have quite a few
heuristics, so it may just be a matter of adding another one
for this kind of case.

+++ Matthew Pickering [Jan 29 15 06:49 ]:

**Comment by timtylin** [comment]
If only NLP was easy to do :)

**Comment by lierdakil** [comment]
Sorry about multiple commits, I kept messing up some logic or other. #2092 should work for this particular case with little drawback.
