### ISSUE TITLE
Change parseFromString in Org reader to match semantics of version in Text.Pandoc.Parsing

### ISSUE THREAD

**Issue by mpickering** [jgm/pandoc#1910]

**Comment by jgm** [comment]
@mpickering, this is a bit cryptic.  Is there still something that needs to be fixed?  What needs changing exactly?

**Comment by mpickering** [comment]
In the Org reader there is a different version of "parseFromString" which
does some extra book keeping but succeeds even if not all of the input is
consumed. I suggest it is changed to match the semantics of the version in
Shared.

**Comment by jgm** [comment]
+++ Matthew Pickering [Mar 29 15 01:27 ]:
>In the Org reader there is a different version of "parseFromString" which
>does some extra book keeping but succeeds even if not all of the input is
>consumed. I suggest it is changed to match the semantics of the version in
>Shared.

By this you mean that it should fail if not all of the input is consumed?

**Comment by mpickering** [comment]
Exactly.

**Comment by jgm** [comment]
I believe it already does this, since it just calls `parseFromString` from `Text.Pandoc.Parsing`:
``` haskell
-- The version Text.Pandoc.Parsing cannot be used, as we need additional parts  
-- of the state saved and restored.                                             
parseFromString :: OrgParser a -> String -> OrgParser a
parseFromString parser str' = do
  oldLastPreCharPos <- orgStateLastPreCharPos <$> getState
  updateState $ \s -> s{ orgStateLastPreCharPos = Nothing }
  result <- P.parseFromString parser str'
  updateState $ \s -> s{ orgStateLastPreCharPos = oldLastPreCharPos }
  return result
```

**Comment by jgm** [comment]
So, can this issue be closed?

**Comment by mpickering** [comment]
Yes, my mistake.
