### ISSUE TITLE
Error running filter pandoc-citeproc with ~/library.bib

### ISSUE THREAD

**Issue by orschiro** [jgm/pandoc#1916]
Dear @jgm,

Many thanks for pandoc. I just donated for one of the best tools for the Linux destop!

I have one question. Why can't a bibliography not be referenced using `~/` in the path?

YAML front matter:
```
bibliography: ~/library.bib
```

Output:
```
❯ pandoc -S -o draft.docx --filter pandoc-citeproc draft.mmd
pandoc-citeproc: Could not find ~/library.bib
pandoc: Error running filter pandoc-citeproc
```

Thankfully,

Robert

**Comment by mpickering** [comment]
Does `/home/<user>/` work correctly?

**Comment by orschiro** [comment]
Yes, `/home/<user>/` works. However, this limits the portability of a created document.

**Comment by jgm** [comment]
The `~` character is interpreted by the shell.  Since we're opening the file directly from pandoc, without going via the shell, it doesn't have its usual shell meaning (just as `*` or `?` wouldn't).

I suppose we could grab the HOME environment variable and manually replace a leading `~`, however.  This might be worth doing.

**Comment by orschiro** [comment]
> I suppose we could grab the HOME environment variable and manually replace a leading `~`, however.  This might be worth doing.

Thanks for considering this! It would definitely increase the portability of the documents to different user systems.

**Comment by jgm** [comment]
+++ Robert Orzanna [Feb 05 15 06:25 ]:
>> I suppose we could grab the HOME environment variable and manually replace a leading `~`, however.  This might be worth doing.
>
>Thanks for considering this! It would definitely increase the portability of the documents to different user systems.

I think there's a decent argument against it, though:  not all shells
expand `~` to $HOME (and Windows doesn't).  So, portability
considerations suggest we shouldn't.

**Comment by orschiro** [comment]
> I think there's a decent argument against it, though:  not all shells
expand `~` to $HOME (and Windows doesn't).  So, portability
considerations suggest we shouldn't.

This is valid point. I haven't thought about Windows systems. Thanks for mentioning...

**Comment by jgm** [comment]
Okay, I'm going to leave this as is for the reason I gave.
