### ISSUE TITLE
Underlying hyperlinks .mmd to .docx

### ISSUE THREAD

**Issue by orschiro** [jgm/pandoc#1918]
Dear all, 

I am using the following command to convert my `.mmd` file written in [Scrivener](http://www.literatureandlatte.com/scrivener.php) to a `.docx`:

```
pandoc -S -o draft.docx --filter pandoc-citeproc draft.mmd
```

The link written in Scrivener looks as follows and is correctly underlined:

![image](https://cloud.githubusercontent.com/assets/170947/6000031/dab78434-aad8-11e4-86e9-c84656bfbd8f.png)

On conversion, however, hyperlinks are not underlined in the resulting `.docx`. Can pandoc support the user here with a flag or should all correct hyperlinking already be done in the markdown file?

In that case I would have to write:

```
[http://www.un.org/en/development/desa/news/population/world-urbanization-prospects-2014.html](http://www.un.org/en/development/desa/news/population/world-urbanization-prospects-2014.html)
```

This, however, is not possible in Scrivener. I appreciate your response. I am just trying to understand whether the issue is to be looked from the editor side (Scrivener) or whether there is potential for pandoc to assist the user here. 

Thanks!

Robert

**Comment by jgm** [comment]
Is your URL in your mmd source inside `<...>` (that's an official Markdown autolink).  Or is it "bare"?  If the latter, you can turn on the `autolink_bare_uris` extension:

    pandoc -f markdown+autolink_bare_uris

or just slap `<` and `>` around the URL in your source.

**Comment by orschiro** [comment]
> Or is it "bare"?  If the latter, you can turn on the `autolink_bare_uris` extension:

Yes it is bare. 

> pandoc -f markdown+autolink_bare_uris

Thanks for the solution!
