### ISSUE TITLE
Infinite loop converting textile table containing cells with multiple lines

### ISSUE THREAD

**Issue by kopf** [jgm/pandoc#1919]
Example textile:

````
|  | Lorem-DB (PosgresSql) | Lorem-DB (Lorem) |
| Ein Schema, darin alle Lorem | Pro:
- Verwaltung
- Ev. effiziente Wartung (Datenmenge klein)
- Einfachere Sicherung/Versionierung der Daten aller Lorem
Con:
- Single-Point-of-Failure
- Db bzw. Lorem Struktur ist gleich für alle
- Lorem teuer in der Entwicklung | Pro:
- Einfachere Lorem/Lorem der Daten aller Tenants
- Verwaltung
- Kosten? 
Con:
- Single-Point-of-Failure
- Db bzw. Lorem Struktur ist gleich für alle
- Bei Lorem/Lorem alle andere Lorem-Jobs sind blockiert 
- Lorem teuer in der Entwicklung |
| Eine Lorem pro Lorem | Pro:
- Die Daten der Lorem sind getrennt
- Die Möglichkeit für unterschiedliche DB bzw. Lorem Struktur
- Bei korrupter Lorem is nur ein Lorem ist betroffen
- Einfachere Lorem/Lorem der Daten eines Lorem
Cons:
- Verwaltung?
- Teuer als eines Schema-alle Lorem?|Pro:
- Die Daten der Lorem sind getrennt
- Die Möglichkeit für unterschiedliche Lorem bzw. Lorem Struktur
- Bei Korrupter Lorem, nur ein Lorem ist betroffen
- Einfachere Lorem/Lorem der Daten eines Lorem
Cons:
- Verwaltung?
- Teuer als eine Schema mit allen Lorem?
- JK: Potentielle Lock Contention auf Lorem?|
````

How it looks in redmine:

![](http://ahye.zzzz.io/s/1gpiyAh5.png)

If you save this textile content as `test.textile` and execute `pandoc -f textile -t html test.textile`, CPU usage reaches 100% and the process doesn't exit (I gave up after about 5 minutes).

**Comment by jgm** [comment]
Almost surely the same issue as in #1911.

**Comment by jgm** [comment]
It's definitely an issue with the textile reader, not the html writer.

**Comment by kopf** [comment]
Hi John,

thanks for your impressively quick solution to this.

If I need this fix as soon as possible, what should I do - clone the repo and build the package myself, or do you expect to be releasing a new version within the next day or two?

**Comment by mpickering** [comment]
I recommend you clone the repo and build pandoc yourself. There are some more instructions in CONTRIBUTING.md.

**Comment by mpickering** [comment]
I recommend you build pandoc yourself. There are some more instructions in CONTRIBUTING.md which are important if you also require templates.

**Comment by kopf** [comment]
OK!

Many thanks.
