### ISSUE TITLE
citeproc not reading PMID, PMCID when using csl to format bibliography

### ISSUE THREAD

**Issue by jjw25** [jgm/pandoc#1923]
Investigators writing NIH grants must include PubMed Central ID's (PMCID) in bibliography. I downloaded a csl file, entitled "national-library-of-medicine-grant-proposals.csl" from http://editor.citationstyles.org/about/ that inserts PMCID for each reference, or the PubMed ID (PMID) when no PMCID is available. My bib file has PMCID and PMID data, but citeproc does not process these values. There are no PMCID's or PMID's in formatted bibliography. I edited csl file, replacing PMCID with DOI, and I can then get DOI in reference. So it looks like citeproc cannot parse PMCID's or PMID's from bib file. I am using pandoc.exe 1.13.2.

**Comment by jgm** [comment]
Correct, not currently supported.

I've just pushed a patch to pandoc-citeproc that supports pmcid and pmid fields in bibtex.  (I'm assuming that these are the names of the bibtex fields - is that correct?)

It would be helpful if you could provide a complete test case with all files needed.  (E.g. link to a zip archive with the bib, csl, and md files.)

**Comment by jjw25** [comment]
Thank you for the prompt reply.

1. pmcid and pmid fields are correct.

2. Here is a link to a test md document, a small bib file, and a csl file
that can be used for testing:

https://github.com/jjw25/citation-files

**Comment by JMLuther** [comment]
For anyone that come across this thread- don't put any url links into your grant or it will be rejected. 
the CSL macro for PMCID extraction needs to be updated (this part is beyond me, but looking) to accept text including one of the following:
N/A (not applicable)
PMC Journal In Process
In process at NIHMS
