### ISSUE TITLE
Support for advanced table formatting

### ISSUE THREAD

**Issue by mbacou** [jgm/pandoc#1930]
reposted from [RMarkdown repo](https://github.com/rstudio/rmarkdown/issues/371)

Hi,
I've been experimenting with Makodo's on-line collaborative markdown editor at https://www.madoko.net/editor.html. It's a very nice implementation/extension of Pandoc with live HTML preview. One thing I'm particularly impressed with is the parsing of complex markdown tables to HTML and TeX (see below). This would be a great extension to Pandoc/RMarkdown. Just a suggestion.

```
# a complex table with merged cells, column/row separators, and custom alignments and widths
|----------------|------------|----------------|------------|
| Segment        | Population | Segment        | Population |
|:-{width=20%}---|-----------:+:-{with=20%}---:|-----------:|
| CNTR.TH.PH     | 923,492    | NRTH.TH.PH     | 2,198,223  |
| CNTR.TH.PL     | 2,001,686  | NRTH.TH.PL     | 138,309    |
| CNTR.TL.PL     | 850,356    | NRTH.TL.PH     | 195,273    |
|----------------|------------| NRTH.TL.PL     | 2,349,917  |
| EAST.TH.PH     | 3,441,242  | ---------------|------------|
| EAST.TH.PL     | 952,325    | SOUTH.TH.PH    | 415,732    |
| EAST.TL.PH     | 1,048,295  | SOUTH.TH.PL    | 463,008    |
| EAST.TL.PL     | 2,709,099  | SOUTH.TL.PH    | 228,653    |
| HGLD.TH.PH     | 1,892,037  | SOUTH.TL.PL    | 1,297,129  |
| HGLD.TH.PL     | 723,501    |----------------|------------|
| HGLD.TL.PL     | 5,258,683  | WEST.TH.PL     | 1,449,491  |
| LAKE.TH.PH     | 6,987,650  | WEST.TL.PH     | 499,738    |
| LAKE.TL.PH     | 2,876,231  | WEST.TL.PL     | 1,814,871  |
| LAKE.TL.PL     | 1,889,034  | WEST.TH.PH     | 688,224    |
|----------------|------------|----------------|------------|
| Tanzania, 2012 | 43,292,199                             |||
|----------------|------------|----------------|------------|
```

Rendered in HTML:

![image](https://cloud.githubusercontent.com/assets/260325/6103243/e9c65856-b00f-11e4-936b-7a0e49ebc395.png)

Rendered in TeX:

![image](https://cloud.githubusercontent.com/assets/260325/6103936/e42b37b6-b016-11e4-8141-6e3d803db68a.png)

Makodo's reference manual is at:
http://research.microsoft.com/en-us/um/people/daan/madoko/doc/reference.html

**Comment by silky** [comment]
sad times

it would be nice if this existed

just imagine the world of possibilities if one could actually merge columns in pandoc ...

**Comment by jgm** [comment]
Agreed, adding colspan support should be a priority.  But it's not particularly easy.  I think that the proposed syntax for colspans in pipe tables, namely
```
| column a | column b |
| merged column       ||
```
is sensible indeed.  But there's an issue for this already, #1024.  I'll close this to avoid dups.
