### ISSUE TITLE
the open XML document cannot be opened because there are problems with the contents or the file name might contain invalid characters 

### ISSUE THREAD

**Issue by cheezedigital** [jgm/pandoc#1935]
ruby on rails application using version 3.2.19. os x operating system and microsoft word for mac 2011 version 14.4.7 and I keep getting this error when trying to click on the created document:

open xml file cannot be opened because there are problems with the contents or the file name might contain invalid characters (for example, \ /)

**Comment by jgm** [comment]
pandoc version?

+++ JV [Feb 10 15 11:46 ]:

**Comment by cheezedigital** [comment]
no pandoc version, though I assumed (assumption is not healthy) after days of searching the phds at google, the thread I'm on here is on to something; I think.

**Comment by jgm** [comment]
You haven't said enough for us to help.  We would need instructions about how to reproduce the problem.  We'd need to know what version of pandoc you're using, what command line options pandoc is being called with, and with what input.

**Comment by cheezedigital** [comment]
yea, then my apologies, as I don't think this rails application is using pandoc.
