### ISSUE TITLE
Q: Is there a feature to remove "pollutants" from HTML to Markdown

### ISSUE THREAD

**Issue by joallard** [jgm/pandoc#1936]
I exported a Doc document (hate those) in HTML, to get some Markdown. But surprise, all the "pollution" from Word ends up in the Markdown, giving HTML-Markdown soup. Is there a way to not get any of that HTML in the final Markdown?

**Comment by mpickering** [comment]
Try

`pandoc -f html -t markdown-raw_html`

**Comment by jgm** [comment]
Try

    pandoc -t markdown-raw_html

You might also get better results exporting to docx, then using pandoc directly on the docx.

By the way:  questions like this should be asked on pandoc-discuss, not submitted to the issue tracker.  This is for bug reports.

+++ Jonathan Allard [Feb 10 15 12:25 ]:

**Comment by joallard** [comment]
Yup, that works. 

> By the way:  questions like this should be asked on pandoc-discuss, not submitted to the issue tracker.  This is for bug reports.

Sorry about that John. Maybe we can count this as an issue against the documentation? ;)
