### ISSUE TITLE
Cannot decode byte '\xa8' error with self-contained and ico link included in header

### ISSUE THREAD

**Issue by jrowen** [jgm/pandoc#1940]
I'm trying to include a shortcut icon link within the header of a html output but am running into the error below.  It works without the `--self-contained` parameter.
```
pandoc: Cannot decode byte '\xa8': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
```
Here is the `md` file
```
# Untitled

# Test

Some text here.
```
here are the contents of the `header.html` file
```
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
```
and here is the `pandoc` command
```
pandoc test.md --to html --self-contained --include-in-header header.html 
```

**Comment by jgm** [comment]
The problem is here in `Text.Pandoc.SelfContained`:

``` haskell
convertTag media sourceURL t@(TagOpen "link" as) =
  case fromAttrib "href" t of
       []  -> return t
       src -> do
           (raw, mime) <- getRaw media sourceURL (fromAttrib "type" t) src
           let enc = "data:" ++ mime ++ "," ++ escapeURIString isOk (toString raw)
           return $ TagOpen "link" (("href",enc) : [(x,y) | (x,y) <- as, x /= "href"])
```

The `escapeURIString isOk (toString raw)` assumes that `raw` is UTF-8 encoded text; in this case, it's an image file.  We could switch to using base64 encoding here.
