### ISSUE TITLE
normalize flag killed epub build process

### ISSUE THREAD

**Issue by OlafRadicke** [jgm/pandoc#1942]
Hi!

my environment:
* Fedora 20
* on i686 (as 32bit)
* pandoc 1.12.3.3

Issue:

I have a markdown with 3700 LoC. If I do this command:

> pandoc -o ./myBook.epub -t epub -f markdown --normalize ./myBook.md

than pandoc is running some time an aborted with the return:

> Killed

and I get no new epub file.

cu

Olaf (from germany/augsburg)

**Comment by ousia** [comment]
Hi @OlafRadicke,

I have also Fedora 20 running on a 32bit processor. But I have pandoc-1.13.2 installed.

This is an statically linked version, from https://copr.fedoraproject.org/coprs/petersen/pandoc/ (I guess we both should upgrade to Fedora 21 :smiley:).

That could help. BTW, just out of curiosity: what is “3700 LoC"?

Just in case it helps.

**Comment by nkalvi** [comment]
@OlafRadicke Does it work without the *normalize* flag? Could you please post a sample section (similar to those in your case) that benefits from using the flag? I can then run some tests in a couple of different settings. It looks like, for ePubs, the flag will be helpful in *pre* and *code* sections in eliminating repeated spaces; not much otherwise.

> **--normalize**
Normalize the document after reading: merge adjacent Str or Emph elements, for example, and remove repeated Spaces.

**Comment by OlafRadicke** [comment]
@ousia 
“3700 LoC" means: "line of code"

Peterson yum repo doesn't work with me:  
>   Error: Package: pandoc-pdf-1.12.3.3-2.fc20.i686 (@updates)
>           Requires: pandoc = 1.12.3.3
>          Removing: pandoc-1.12.3.3-2.fc20.i686 (@updates)
>             pandoc = 1.12.3.3-2.fc20
>        Updated By: pandoc-1.13.2-1.fc20.i686 (petersen-pandoc)
>           pandoc = 1.13.2-1.fc20
>      Available: pandoc-1.11.1-6.fc20.i686 (fedora)
>         pandoc = 1.11.1-6.fc20

**Comment by OlafRadicke** [comment]
@nkalvi 

Example: http://the-independent-friend.de/wh/normalize-example-case.tar.gz
after download and extracting please do command: 
> make epubnormalize

cu

Olaf

**Comment by jgm** [comment]
`--normalize` was rewritten for efficiency in 1.13.  Please upgrade to
the latest version of pandoc and let us know if you still have the problem.
If you can't upgrade, perhaps you could link to the problematic source
and we could try it.

+++ Olaf Radicke [Feb 15 15 01:00 ]:

**Comment by nkalvi** [comment]
@OlafRadicke Thanks for the example. It worked fine on Mac with Pandoc 1.13.2.

When comparing both normalized and simple output on the particular example, only Chapter 3 had a difference (multiple spaces), but the resulting ePubs were similar visually.

**Comment by jgm** [comment]
Succeeds in about 1 second on pandoc 1.13.2.  This bug report can be closed.

+++ Olaf Radicke [Feb 15 15 06:03 ]:

**Comment by ousia** [comment]
@OlafRadicke,

your document compiles fine with version 1.13.2.

AfaIk, you need to remove `pandoc-pdf` which is a metapackage to download all `texlive` dependencies to use pandoc with LaTeX.

I guess removing `pandoc-pdf` won’t remove any `texlive` package. Sorry, but I don’t have any of them installed. At worst, you could install them again later.

**Comment by OlafRadicke** [comment]
I've installed pandoc 1.13.2 and tried again. Now it is running.  Thank you for help. The ticket can be closed now.

**Comment by ousia** [comment]
> I've installed pandoc 1.13.2 and tried again. Now it is running. Thank you for help. The ticket can be closed now.

@OlafRadicke, you’re welcome. I’m afraid that only you (as the creator) or @jgm can close it. Click on _Close issue_ (it will be _Close and comment_ if you write something).

**Comment by OlafRadicke** [comment]
Issue obsolete with new version.
