### ISSUE TITLE
Problem with quotes in separate lines

### ISSUE THREAD

**Issue by bkolada** [jgm/pandoc#1944]
Hi, 
I found a problem with parsing a quotes. Pandoc merge some lines of quotes into one and I think it shouldn't.

    > First line
    > Second line

Will produce one line `First line Second line` but should produce

> First line
> Second line 

I know that in some examples these lines should be merged into one but mostly it shouldn't.

**Comment by jgm** [comment]
Please say more clearly what format you're writing to, and what you take the expected output to be.

Newlines in Markdown are treated as "soft breaks" by default, so yes,

    > First
    > second

will turn into this HTML:

    <blockquote>
    <p>First second</p>
    </blockquote>

This is semantically equivalent to:

    <blockquote>
    <p>First
    second</p>
    </blockquote>

If you want newlines to be treated as hard breaks, use

    pandoc -f markdown+hard_line_breaks



+++ Bart Kolada [Feb 15 15 06:06 ]:

**Comment by bkolada** [comment]
Yeah, it is what I wanted, treating newlines as a hard line breaks. It looks like there is solution for that so thanks for help and issue is ready to close.
