### ISSUE TITLE
Inter-file references in multiple-file books

### ISSUE THREAD

**Issue by danmbox** [jgm/pandoc#1945]
This is an extremely common use case. There are many ebooks published on github, consisting of multiple .md files. Links (as in the example below) to a different .md file are broken in the final output:

`Next section: [Summary](summary.md)`

Yes, I know pandoc concatenates files in the beginning (which is silly), and this probably needs to be solved with a filter. But it is a very common problem, and specific solutions should be provided in the documentation, if not in the pandoc options.

**Comment by nkalvi** [comment]
Not a proper solution, but could be an easy workaround: 

- replace the file links (with this kind of pointers) with internal links.
- To the referenced files, prepend an empty span element with the file name as id

So using your example:
```
Next section: [Summary](#summary.md)

The first line in summary.md:
<span id="summary.md"></span>
```

**Comment by mpickering** [comment]
This is how the EPUB reader handles links to files.

**Comment by danmbox** [comment]
I would write a a filter to replace .md links with .html links

**Comment by mb21** [comment]
Closing this as out-of-scope, sorry.
