### ISSUE TITLE
Using \section for beamer output

### ISSUE THREAD

**Issue by tindzk** [jgm/pandoc#1952]
Certain beamer templates like [mtheme](https://github.com/matze/mtheme) advocate the use of ``\section{...}`` to group slides. It should be possible to control whether ``#`` indicates a frame or a section. If I understand correctly, ``#`` used to denote a section, but this was changed in recent versions (see also https://github.com/jgm/pandoc/issues/994). Using the raw LaTeX command in the markdown file seems to wrap a frame around it, which in turn leads to a compilation error.

**Comment by jgm** [comment]
See the documentation on slide shows in the README.

The first level of header to contain content directly under it (and not
merely group other headers) is the slide level.  Headers above this
will be sections.

So, for example:
```
# Section

## Slide

foo

## Slide two

bar

# Section two

## Slide three

baz
```

**Comment by tindzk** [comment]
Thanks. I just had to set ``--slide-level=2``.
