### ISSUE TITLE
Problem parsing paragraph with only a number follow by dot

### ISSUE THREAD

**Issue by r-gaia-cs** [jgm/pandoc#1955]
## Steps To Reproduce

~~~
$ pandoc -t html <<EOF
-   First number:

    1.
EOF
~~~

## Actual Results

~~~
<ul>
<li><p>First number:</p>
<ol style="list-style-type: decimal">
<li></li>
</ol></li>
</ul>
~~~

## Expected Results

~~~
<ul>
<li><p>First number:</p>
<p>1.</p>
</li>
</ul>
~~~

## Additional Information

A more small example is

~~~
$ pandoc -t html <<EOF
1.
EOF
~~~

that result in 

~~~
<ol style="list-style-type: decimal">
<li></li>
</ol>
~~~

instead of

~~~
<p>1.</p>
~~~

## Environment Information

~~~
$ pandoc --version | head -n 1
pandoc 1.13.3
~~~

This isn't the last version but I can upgrade if needed.

**Comment by jgm** [comment]
Pandoc's behavior is correct. What you have here is an empty ordered list item.
Of course, Markdown is vague about whether empty list items are allowed, and implementations differ:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.%0A
But pandoc has made the decision to allow them, so this is not a bug.

+++ Raniere Silva [Feb 18 15 11:08 ]:

**Comment by r-gaia-cs** [comment]
@jgm There is a workaround to this behavior of Pandoc?

**Comment by jgm** [comment]
You could backslash-escape the period.

+++ Raniere Silva [Feb 18 15 17:05 ]:

**Comment by r-gaia-cs** [comment]
@jgm Thanks for the tip. I'm closing this issue for now.

~~~
$ pandoc -t html <<EOF
1\.
EOF
<p>1.</p>
~~~
