### ISSUE TITLE
docx reader does not support subscript or superscript

### ISSUE THREAD

**Issue by harvinders** [jgm/pandoc#1957]
It would be nice if docx reader provide this support.

**Comment by mpickering** [comment]
Please can you provide a file which shows your problem.

**Comment by jkr** [comment]
@harvinders : it does support them -- or at least it supports their specified form. So if you have some subscripts or superscripts that aren't coming through, there's either been a format change, or you're doing something unusual. Either way, we'd be *very* interested in seeing the file.

**Comment by harvinders** [comment]
Sorry, I should have investigated a little before shooting the mail. I just
thought the feature is not there yet. Now, I have written four scenarios
bellow for both superscript and subscript

Please consider the following markdown
m^2^
m^`2`^
`m`^2^
`m`^`2`^

When it is converted to docx, it is displayed properly. Everyone of them.
However when I regenerate the md from docx the following is generated.

m^2^\
m`2`\
`m`^2^\
`m``2`

So anytime, superscript is within in `` it is not handled properly.
I tested for subscript and the result was same.


harvinder

**Comment by jkr** [comment]
Issue confirmed. Thanks for the report. The bug was fixed with 55d2ce751a8fefc3e07aa5d703ca77dd2df2c8c7.
