### ISSUE TITLE
Specify template in YAML

### ISSUE THREAD

**Issue by davepwsmith** [jgm/pandoc#1958]
I can't seem to specify the template in the YAML metadata, as I can for example with the bibliography and CSL style. This would be very useful, as I could then basically customize my pandoc command for each file, without having to remember which arguments to use for specific projects. Am I doing something wrong (template: paper) or is this simply not possible?

**Comment by nkalvi** [comment]
It is not possible in pandoc 'directly' as far as I know (I'm quite new to pandoc).

But **R markdown** (which uses pandoc) seems to have what you want:

http://rmarkdown.rstudio.com/html_document_format.html

>### Custom Templates
You can also replace the underlying pandoc template using the template option:
>
>
```
---
title: "Habits"
output:
  html_document:
    template: quarterly_report.html
---
```
Consult the documentation on pandoc templates for additional details on templates. You can also study the default HTML template as an example.

**Comment by davepwsmith** [comment]
Interesting, but that would add a completely unnecessary piece of software to a workflow that already has its quirks, and so probably isn't desirable. I have no need for the statistical features of R, and so would prefer to stick with using pandoc directly.

**Comment by jgm** [comment]
Template variables aren't well suited for things like path names, because (recall) everything is interpreted as Markdown.

However, YAML fields ending with `_` are ignored and contain any kind of content.

So, you could do this:  in your documents, use the YAML metadata field `template_` to specify the template:

```
---
title: My title
template_:  my_fancy_template.html
...
```

Then, extract this using sed in your pandoc command line:


```
pandoc --template=$(sed -ne '/^template_:/{s/^template_: *//p;q}' $SOURCE) $SOURCE -s
```

where `$SOURCE` is the filename.  You could automate this
with a small wrapper script or Makefile.

**Comment by michaelstepner** [comment]
@jgm, I had the same question as @davepwsmith.  Thanks for providing a solution!

I wanted to make the command more flexible by having it automatically detect whether there is a "template_" YAML field.  The following command only adds a `--template` option to pandoc if it finds the YAML field in the source file:

```
pandoc $(sed -n 's/^template_:[ ][ ]*\(.*\)/\1/p' $SOURCE | sed 's/^\(..*\)$/template=\1/') $SOURCE -s
```

I then integrated this into my Sublime Text build system (after fighting with escape characters for a while).  For anyone interested, my ST3 build system is:
```
{
    "shell_cmd": "pandoc \\$(sed -n 's/^template_:[ ][ ]*\\(.*\\)/\\1/p' \"$file\" | sed 's/^\\(..*\\)\\$/--template=\\1/') --filter pandoc-citeproc -o \"${file_path}/${file_base_name}.pdf\" \"$file\" && open -a Preview \"${file_path}/${file_base_name}.pdf\"",
    "selector": "text.html.markdown",
    "path": "/usr/texbin:$PATH"
}
```

This will convert a Markdown file to PDF, using a custom template file if *and only if* one is specified using a "template_" YAML field.

**Comment by jtkiley** [comment]
I agree with this idea, and it would be a huge quality of life improvement for me. As it stands, I end up having to create a Makefile for individual documents or copy/paste the template path (when I only ever use a handful of templates). If I could specify the template in YAML (like I can bibs and CSLs, both of which have the same path issue), it would make many things I do (e.g., academic papers, recommendation letters, envelopes, instructions, course materials) much easier.

I appreciate the workaround, and I'll try to figure out an equivalent to that ST3 build in Atom, but it would still be nice to see this built in normally.

**Comment by jgm** [comment]
OK, I'll reopen this for further consideration.  But since the source document might be used to generate content in different formats, at the very least this would need to be parameterized on the output format as it is in RMarkdown.  See also #2139.

**Comment by uliska** [comment]
> at the very least this would need to be parameterized on the output format 

Would it be an option to make this decision depend on whether the given template has an extension?

So

```yaml
---
template: my-letter.latex
---
```
would look for `my-letter.latex`
while

```yaml
---
template: my-letter
---
```
would look for a template with a file extension matching the output format?

(I'm commenting on this because I found this issue looking for exactly this functionlatily (so this comment is a `+1` too)).

**Comment by mb21** [comment]
Closing in favour of https://github.com/jgm/pandoc/issues/4627.
