### ISSUE TITLE
markdown reader, latex and the -R flag

### ISSUE THREAD

**Issue by puterleat** [jgm/pandoc#1961]
The docs for the -R flag state:

    -R, --parse-raw
    Parse untranslatable HTML codes and LaTeX environments as raw HTML or LaTeX, instead of ignoring them. Affects only HTML and LaTeX input. ...

However it's valid for pandoc markdown to contain latex commands. Is it possible for the markdown reader to also honour the -R flag, to enable latex to be printed into the rst output?

**Comment by jgm** [comment]
The `-R` flag only affects parsing.  As you note, pandoc
markdown with default extensions already allows raw LaTeX,
and this gets into the parse tree.  You don't need `-R` for
that.

However, the RST writer doesn't pass through raw LaTeX
inlines.  (It does pass through raw LaTeX environments
using `.. raw:`.)  If there's a way to handle LaTeX
inlines in RST, we could add that.


+++ puterleat [Feb 19 15 16:13 ]:

**Comment by puterleat** [comment]
> On 20 Feb 2015, at 02:29, John MacFarlane <notifications@github.com> wrote:
> 
> The `-R` flag only affects parsing. As you note, pandoc
> markdown with default extensions already allows raw LaTeX,
> and this gets into the parse tree. You don't need `-R` for
> that.
> 
> However, the RST writer doesn't pass through raw LaTeX
> inlines. (It does pass through raw LaTeX environments
> using `.. raw:`.) If there's a way to handle LaTeX
> inlines in RST, we could add that.
> 

I see… Would the equivalent of `.. raw:` be to add them as ``inline literal`` ?

**Comment by jgm** [comment]
+++ puterleat [Feb 20 15 01:10 ]:
>   I see… Would the equivalent of `.. raw:` be to add them as ``inline
>   literal`` ?

I don't know.  If you find the answer, please link to part
of the docutils documentation.

**Comment by puterleat** [comment]
> I don't know. If you find the answer, please link to part
> of the docutils documentation.

On checking, it should actually use the ‘raw' role, so something like :raw:`\mylatexcommand{foo}`

http://docutils.sourceforge.net/docs/ref/rst/roles.html#raw <http://docutils.sourceforge.net/docs/ref/rst/roles.html#raw>

It also recommends to subclass the role, so you might add this to the document:

.. role:: raw-latex(raw)
   :format: latex
And then inline use would be  :raw-latex:`\mylatexcommand{foo}`
