### ISSUE TITLE
Feature Request: :PROPERTIES: drawer for Org-mode writer

### ISSUE THREAD

**Issue by gnusosa** [jgm/pandoc#1962]
I'm new to Pandoc and Haskell, but reading through the source code of [Text-Pandoc-Writers-Org](http://hackage.haskell.org/package/pandoc-1.13.2/docs/src/Text-Pandoc-Writers-Org.html#writeOrg), I don't seem to find the drawer converter function. Am I missing something in the documentation?

**Comment by gnusosa** [comment]
Ok, so reading more on this, it seems that there isn't any Block or Inline element tied together with org-syntax drawer type.

**Comment by mpickering** [comment]
@tarleb, what do you think?

**Comment by gnusosa** [comment]
I think I can write it. What I don't know is what `Block` or `Inline` element that we can use from the `Pandoc` data type that we can use for drawers.

**Comment by jgm** [comment]
What can drawers contain?  (inlines? blocks?)

What kind of attributes need to be attached to them?

A pandoc Div or Span element might be your best choice.
But it also depends on how they need to be rendered.

+++ Carlos Sosa [Feb 20 15 13:21 ]:

**Comment by tarleb** [comment]
When I wrote the comment in #1877, I planed on stuffing that info into Divs.  Though I didn't put much thought into it yet.

**Comment by tarleb** [comment]
@jgm: Drawer contain nothing but key-value pairs.

**Comment by tarleb** [comment]
I answered too fast: Drawers can contains blocks *and* key-value pairs.  I only thought about key-value pairs, as that's what they are usually used for (and too hide boring data, which  shouldn't be exported).

**Comment by gnusosa** [comment]
Yeah, I think a `Div` with the first attribute of `attrs` contains `Drawer`, after that the second element in `attrs` can be the opening and closing drawer tag, in this case `:PROPERTIES: :END:`, after that the kvs where we decor the key with `:key:`. In the end, we add the `[Block]` elements. I will try to write it later in the week.

**Comment by gnusosa** [comment]
The pull-request for this is https://github.com/jgm/pandoc/pull/1984

**Comment by wmhorne** [comment]
This is likely not the best place to inquire about such a question, as this is closed, but it does relate to the topic at hand. How does one include a property in a pandoc conversion from org to *? Is that with an "#+OPTIONS: d:t" within the org file, or an added element within the pandoc command line interface?

Can't find information anywhere else. May post to group if this proves to be an inappropriate place for an inquiry.
