### ISSUE TITLE
allow .class #id and :lang special attributes in each element

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#1966]
I know that this would be not easy to implement. But I think this is also an essential feature.

We need three special attributes in pandoc’s internal document model:

* Classes.
* Identifiers.
* Languages (special syntax pending in #895).

Unless my request is totally wrong, please leave it open, so that interested people can comment here.

**Comment by in3rsha** [comment]
I also think this feature would be very useful. I have no expertise, but I do have a practical example...

== A practical example ==

I think the ArchLinux wiki is a truly excellent service for anyone interested in learning Linux. I think the effectiveness of their tutorials are furthered by the intelligent use of inline notes within the text, such as warnings and tips.

Example: https://wiki.archlinux.org/index.php/Beginners%27_guide

Pandoc markdown is clearly a perfect fit for constructing technical documents. However, there is no seamless way to insert notes in to a technical document whilst writing.

<p class"">This works, but it's not sexy.</p>

I think inserting notes within technical writing is an effective technique, and if this can be encouraged with a syntax that allows for it in markdown, then that would be marvelous.

**Comment by ousia** [comment]
I have just realized that this issue is a duplicate of a much older issue (#684).

Closing the issue myself.
