### ISSUE TITLE
yaml_metadata_block not parsing nested author info correctly; returns 'true' instead of data.

### ISSUE THREAD

**Issue by cossatot** [jgm/pandoc#1969]
I'm using Pandoc 1.13.2 on Yosemite, and when I try to add author affiliation to the yaml block at the top of a markdown file, I'm not getting the correct output.  The author metadata is simply returned as a boolean `true` value.

For example, processing the following `test.md`: 
```
---
title: 'This is the title'
author: 
- name: Richard Styron
  affiliation: Earth Analysis

date: 23 February 2015
abstract: "short"

---

# Introduction

This is the intro.
```

with `pandoc -r markdown+yaml_metadata_block -s -S -o test.tex test.md`

gives me `\author{true}`.

Similarly with converting to html:
`<h2 class="author">true</h2>`

I've tried copying and pasting the examples from the Pandoc homepage, changing up the command line options a bit, and always get the same result.

If I just use:
```
author: Richard Styron
``` 
it works out just fine, but I'd like to add affiliation, etc.

Thanks!

**Comment by jgm** [comment]
From the README:

```
Note: The `author` variable in the default templates expects a simple list or
string.  To use the structured authors in the example, you would need a
custom template.  For example:

    $for(author)$
    $if(author.name)$
    $author.name$$if(author.affiliation)$ ($author.affiliation$)$endif$
    $else$
    $author$
    $endif$
    $endfor$

```

**Comment by cossatot** [comment]
Ah, I see.  Thanks.
