### ISSUE TITLE
<section> elements not generated for some 2nd-level headings in revealjs output

### ISSUE THREAD

**Issue by yfyf** [jgm/pandoc#1970]
Hi, 

given these two files:

```
$ cat good.md 
# Introduction

## Hi

<div class="notes">
First chapter note
</div>

# Some chapter
```
```
$ cat bad.md 
# Introduction

## Hi

<div class="notes">
First chapter note
</div>


# Some chapter

<div class="notes">
Second chapter note
</div>
```

Using `good.md`, pandoc correctly generates separate slides (i.e. `<section>` tags) for the headings `Introduction` and `Hi`, while using `bad.md` it doesn't. Note that `bad.md` only differs by an appended `<div>` with speaker notes.

Here's the commands / output:
```
$ pandoc -s -t revealjs good.md
[...]
<body>
  <div class="reveal">
    <div class="slides">


<section><section id="introduction" class="titleslide slide level1"><h1>Introduction</h1></section><section id="hi" class="slide level2">
<h1>Hi</h1>
<aside class="notes">
Bap
</aside>
</section></section>
<section><section id="some-chapter" class="titleslide slide level1"><h1>Some chapter</h1></section></section>
    </div>
  </div>
```
and
```
$ pandoc -s -t revealjs bad.md
[...]
<body>
  <div class="reveal">
    <div class="slides">


<section id="introduction" class="slide level1">
<h1>Introduction</h1>
<h2 id="hi">Hi</h2>
<aside class="notes">
First chapter note
</aside>
</section>
<section id="some-chapter" class="slide level1">
<h1>Some chapter</h1>
<aside class="notes">
Second chapter note
</aside>
</section>
    </div>
  </div>
```

The files with full HTML output are here:
https://gist.github.com/yfyf/91af1abb98ca55ce0127

The version of pandoc used:

```
$ pandoc --version
pandoc 1.12.4.2
```

Let me know if I can help you with any other details.

**Comment by yfyf** [comment]
Note that this issue does not seem to be related to speaker note divs at all, I can reproduce it in many ways. Unfortunately, I don't have a "canonical" way to reproduce this, since I don't really understand when exactly does this bug occur.

**Comment by mpickering** [comment]
I can reproduce this but can't immediately see what is going on.

**Comment by yfyf** [comment]
Here's an even smaller example:

```
$ cat bad2.md 
# Introduction

# Hi

Lets talk.


# Overview

## Foo-heading
```

This generates `Overview` and `Foo-heading` on the same slide.

```
$ pandoc -s -t revealjs bad2.md
[..]
<section id="introduction" class="slide level1">
<h1>Introduction</h1>
</section>
<section id="hi" class="slide level1">
<h1>Hi</h1>
<p>Lets talk.</p>
</section>
<section id="overview" class="slide level1">
<h1>Overview</h1>
<h2 id="foo-heading">Foo-heading</h2>
</section>
```

Removing the (body) text from the slide `Hi` fixes the problem.

**Comment by jgm** [comment]
+++ Ignas Vyšniauskas [Feb 24 15 07:33 ]:
>Here's an even smaller example:
>
>```
>$ cat bad2.md
># Introduction
>
># Hi
>
>Lets talk.
>
>
># Overview
>
>## Foo-heading
>```
>
>This generates `Overview` and `Foo-heading` on the same slide.


The explanation of this is simple.

Here you have non-section content directly under the level-1 header,
so the "slide level" is 1. (See the README for the explanation of
the system and this terminology.)

When slide level is 1, a level-2 header will generate a subhead
on the same slide, rather than a new slide.

If you take out "Let's talk", slide level becomes 2, and now level-2
headers generate slides.

Your original case is the same:  here you have speaker notes directly
under a level-1 header, which makes the "slide level" 1.

See the README under slide shows, and see if that clears things up
for you.

**Comment by yfyf** [comment]
@jgm thanks for the explanation, I skimmed through the documentation, but initially didn't realize slide-level is dynamically determined by the (lack of) content. Closing the issue.
