### ISSUE TITLE
Download error!

### ISSUE THREAD

**Issue by imcaffrey** [jgm/pandoc#1972]
When I downloaded the release for Windows,My windows8 tells me that it's not a valid program.

What could I do?
thanks

**Comment by jgm** [comment]
Sorry, I have no idea.  I haven't seen this issue before, and I've
installed on Windows 8.  You might post to the pandoc-discuss mailing
list to see if anyone has any suggestions.  (I'm not a Windows user.)

+++ SCaffrey [Feb 25 15 00:31 ]:

**Comment by imcaffrey** [comment]
thanks ,BTW how do I access the `pandoc-discuss mailing
list `?

**Comment by nkalvi** [comment]
Try https://groups.google.com/forum/#!forum/pandoc-discuss

**Comment by nkalvi** [comment]
Also, I just installed 1.13.2 on Windows 8.1 without any issues. Do you have any more details f.ex. from Event Viewer? Please post it to the discussion group ...
