### ISSUE TITLE
Documentation of \newcommand shows replaced value, not example

### ISSUE THREAD

**Issue by JensErat** [jgm/pandoc#1973]
In the documentation on [`\newcommand`](http://johnmacfarlane.net/pandoc/README.html#latex-macros), the example is executed and replaced by the macro's value instead of printed:

    \newcommand{\tuple}[1]{\langle #1 \rangle}
    $\tuple{a, b, c}$

Displayed is: ${a, b, c}$.

It seems, the author expected `\newcommand` not to work within code sections, but it actually does.

**Comment by nkalvi** [comment]
You may want to freshen http://johnmacfarlane.net/pandoc/README.html after the fix.

**Comment by jgm** [comment]
I'll regenerate when we have the next release.  Doing it now would
bring some option documentation out of sync with the released version.

+++ nkalvi [Feb 25 15 17:14 ]:

**Comment by nkalvi** [comment]
You're right; apologies for not being precise - I meant just the http://johnmacfarlane.net/pandoc/README.html#latex-macros section. This is how it looks now:

![latex macros](https://cloud.githubusercontent.com/assets/2199312/6388483/6a997b42-bd68-11e4-9e08-ca25f38f3d73.png)

**Comment by jgm** [comment]
Yes - I just refreshed it.
