### ISSUE TITLE
Anchor with id tag inside heading, HTML to PDF conversion fails

### ISSUE THREAD

**Issue by jlento** [jgm/pandoc#1975]
Simple test (pandoc 1.13.2):

~~~~
echo '<h1><a id="1"></a>Head 1</h1>' | pandoc -s -f html -o anchor.pdf
~~~~

gives

~~~~
! Argument of \@sect has an extra }.
<inserted text> 
                \par 
l.52 ...fstring{\hyperdef{}{1}{}{}Head 1}{Head 1}}

pandoc: Error producing PDF from TeX source
~~~~

Any ideas how to make it work without editing the HTML source?

**Comment by mpickering** [comment]
I think this is #1886

**Comment by jlento** [comment]
Wrote an ugly filter that removes the anchor altogether, and puts the id tag inside h1 element:

~~~~
import Text.Pandoc.JSON

main = toJSONFilter filter
  where filter (Header l ("",hClasses,hKeyVals) ((Span (sId,_,_) []):ins)) =
          Header l (sId,hClasses,hKeyVals) ins
        filter x = x
~~~~

Now

~~~~
echo '<h1><a id="1"></a>Head 1</h1>' | pandoc -f html -t html --filter ./filter
~~~~

gives

~~~~
<h1 id="1">Head 1</h1>
~~~~

and also the conversion to PDF works. This filter only works when the Span (anchor) element is the first Inline element of the Header without an id tag (which happens to be the case in the docs I need to convert).

**Comment by jgm** [comment]
Yes, this is a dup of #1886.  Closing this one.
