### ISSUE TITLE
textual citations don't work with org mode reader

### ISSUE THREAD

**Issue by minkkinen** [jgm/pandoc#1978]
When converting from org and using citations, normal citations with angular brackets work, but in-text citations without brackets don't work. Could this feature be easily implemented in the org reader?

**Comment by tarleb** [comment]
Could you give an example of the citation method you'd like to use?

**Comment by minkkinen** [comment]
For example: @smith1997 [p. 23] writes that Pandoc is a great tool. I think it's referred to as textualCite in the Markdown reader, but I'm not familiar with Haskell so I'm not sure.

**Comment by jgm** [comment]
Are these supposed to work in org mode?  Does org mode support this kind
of citation format?  Can you link to documentation?

**Comment by minkkinen** [comment]
No, org mode doesn't provide any citation syntax out of the box so they don't work in org mode. However, the basic Pandoc citation formats are included in the org reader, which is great because you can use org and CSL bibliographies. So this is not a bug in Pandoc, it's more like a feature that could be even better.

**Comment by treitmaier** [comment]
I agree with @minkkinen. Compared to Markdown, org-mode provides many more features for structuring, rearranging and editing text and tables.  However, nothing compares to how pandoc handles citations and bibliography.  See for instance the following three blog posts that use org-mode for writing/editing academic papers/notebooks and pandoc for converting these to HTML, LaTeX/PDF, and Word:

[Keeping a lab notebook with org-mode & pandoc](http://erikclarke.net/2014/10/21/keeping-a-lab-notebook-with-org-mode-git-papers-and-pandoc-part-ii/) 
[Org-mode & Pandoc](http://www.rousette.org.uk/blog/archives/org-mode-and-pandoc/) 
[Org-mode to docx with bibliographies](http://kitchingroup.cheme.cmu.edu/blog/2015/06/11/ox-pandoc-org-mode-+-org-ref-to-docx-with-bibliographies/)

Expanding the org-mode reader to support in-text citations such as

    @Doe1997 argues that org-mode and pandoc are awesome tools.

would be a fantastic feature.

**Comment by tarleb** [comment]
There still isn't an official citation syntax for org-mode.  The [org-ref package](https://github.com/jkitchin/org-ref) uses special `[[cite:author]]` commands, while this [semi-official tutorial](http://orgmode.org/worg/org-tutorials/org-latex-export.html#orgheadline50) suggest `epub` or `cite` as markers for citation links.  Markdown-like syntax isn't supported in Emacs Org-Mode.

The Org reader isn't using the citations command-line switch yet, it should. Enabling all, the current syntax, special `cite`-links as well as textual citations seem like a sensible way of handling this.
