### ISSUE TITLE
--extract-media for docx reader not working

### ISSUE THREAD

**Issue by harvinders** [jgm/pandoc#1979]
I am trying to do a round trip with md->docx->md so that I can get feedback in doc and store back the modified version in md before generating epub, docx and pdf etc.

While I am able to generate the docx with images, I am not able to get them back into the md using the --extract-media flag. Folloing is tha command that I am using to get images from the docx. ~~Also attached is the docx~~ (seems docx is not allowed to be uploaded) and the md files. I am using version 1.13.1 on windows 8.1

```
pandoc -N -s -S --atx-headers --extract-media=img -t markdown -f docx with-image.docx -o regen_with-image.md
```

original md

```
Go to NuGetPackage Manger -> Package Sources -> Press plus ![](images/plus.png) button   
![Options](images/Nuget-options.png)  
```

Regenerated md (`regen_with-image.md`)

```
Go to NuGetPackage Manger -\> Package Sources -\> Press plus button
```

**Comment by bpj** [comment]
Since a docx file is actually a zip archive with a funny extension you can just make a copy of the .docx file and change the extension to .zip and open it with your favorite decompression utility. Somewhere in there there is a media folder, albeit with inscrutable file names. There possibly is an xml file mapping those names to the original names but it's easier to just inspect the file contents.

**Comment by nkalvi** [comment]
You may want to look at https://chrome.google.com/webstore/detail/ooxml-tools/bjmmjfdegplhkefakjkccocjanekbapn?hl=en also.

I find it very useful.

**Comment by nkalvi** [comment]
Results were good in my short test with Pandoc 1.13.2 under Windows 8.1. As you can see 
- image files are renamed
- captions are not retained in round trip  
*not sure whether retaining image-names could be a feature request*

but the end result (visually) looks correct in docx.
I would hesitate to use round-trips to maintain the doc though.

----

Original - portion from testsuite.txt:
```
# Images

From "Voyage dans la Lune" by Georges Melies (1902):

![lalune][]

   [lalune]: lalune.jpg "Voyage dans la Lune"

Here is a movie ![movie](movie.jpg) icon.
```

1. Output docx  
 ```
pandoc testsuite.txt -o win-t1.docx
```
2. Output md with media  
    ```
pandoc win-t1.docx --extract-media=win-t2 -o win-t2.txt
  
 tree /f win-t2
        \WIN-T2
        └───media
                rId22.jpg
                rId23.jpg
    ```
###### win-t2.txt
    ```
Images
======

From "Voyage dans la Lune" by Georges Melies (1902):

![](win-t2/media/rId22.jpg)

lalune

Here is a movie ![](win-t2/media/rId23.jpg) icon.
    ```
3. Output docx from regen-md  
    ```
pandoc win-t2.txt -o win-t2.docx
    ```  
  
    ![win-t2 docx](https://cloud.githubusercontent.com/assets/2199312/6468008/1d8c3790-c1a0-11e4-850f-9a075dcbdd4a.png)

**Comment by mpickering** [comment]
@hdevalence Please can you provide the original image and so we can try to reproduce this.

Thanks @nkalvi for your testing.

**Comment by hdevalence** [comment]
Hey, I think you meant @harvinders -- sorry for the mixup!

**Comment by nkalvi** [comment]
@harvinders Is it possible upload the files to a file sharing service and share the link? If you're uploading Word files, you may want to clear any personal data under privacy options in Word.

**Comment by harvinders** [comment]
Here we go.

**Comment by nkalvi** [comment]
@harvinders It looks fine (with the side effects I mentioned earlier) with Pandoc **1.13.2** on Windows 
```
D:\pandoc_1979>pandoc -N -s -S --atx-headers --extract-media=img -t markdown -f docx with-image.docx -o regen_with-image.md
pandoc: extracting img\media\rId21.png
pandoc: extracting img\media\rId22.png
```
###### regen_with-image.md:
```
Go to NuGetPackage Manger -\> Package Sources -\> Press plus
![](img/media/rId21.png) button\
![](img/media/rId22.png)
```

```
D:\pandoc_1979>pandoc regen_with-image.md -o from-regen-md.docx
```
When viewed in word:
![regen-docx](https://cloud.githubusercontent.com/assets/2199312/6483562/7eb67dbe-c240-11e4-8f84-3a5f1e81198a.png)

I'm not sure whether it is an issue with 1.13.1.

**Comment by harvinders** [comment]
Yes, I can confirm that it is working in 1.13.2

**Comment by 5hadawan** [comment]
doesn't work with version 1.19.2.1
