### ISSUE TITLE
Don't number headings in latex

### ISSUE THREAD

**Issue by jakobgager** [jgm/pandoc#1981]
Following the [user guide](http://johnmacfarlane.net/pandoc/README.html#options-affecting-specific-writers), one can use `-N` to enable heading numbers, as by default, sections are not numbered. However, the later statement is somehow not really reproducible for conversions to latex. The sections are converted to `\section`, `\subsection`, etc. (compare [here](http://johnmacfarlane.net/pandoc/try/?text=%23+Heading+1%0A%23%23+Heading+2&from=markdown&to=latex)) instead of `\*section` and so on. Thus, the `-N` option is nice for HTML but somehow unnecessary for latex.

Is there an option to get not numbered section headings in LaTeX?

**Comment by timtylin** [comment]
.This option works in conjunction with the template. Without the option, the latex template adds `\numsecdepth{0}` to suppress section numbering. The `*` syntax is reserved to implement the `.nonumber` sect tribute, since it has the correct granularity for that attribute.

**Comment by jakobgager** [comment]
Thanks, I got it.
