### ISSUE TITLE
MediaWiki links to other wiki pages have spaces not underscores

### ISSUE THREAD

**Issue by peterjc** [jgm/pandoc#1982]
e.g. Using pandoc 1.13.2,

```
$ echo "Internal link to [[Main Page]], also [[Main Page|different text]] works. Also [http://example.org external sites] possible." | pandoc -f mediawiki -t rst
Internal link to `Main Page <Main Page>`__, also `different
text <Main Page>`__ works. Also `external sites <http://example.org>`__
possible.
```

I was expecting to get the links with underscores in them, not spaces, as per MediaWiki URL conventions (I am interested in migrating content from MediaWiki to an alternative markup and therefore wish to preserve the old public facing URLs):

```
$ echo "Internal link to [[Main Page]], also [[Main Page|different text]] works. Also [http://example.org external sites] possible." | pandoc -f mediawiki -t rst
Internal link to `Main Page <Main_Page>`__, also `different
text <Main_Page>`__ works. Also `external sites <http://example.org>`__
possible.
```

**Comment by mpickering** [comment]
Seems like this would be the best thing to do with internal links. It seems like there might be slightly more complicated escaping rules which would be good to implement as well?

**Comment by peterjc** [comment]
Quoting http://www.mediawiki.org/wiki/Manual:ImportImages.php which focused on files:

*Note: The "canonical database form" ... is obtained from the file name by capitalizing the first letter, replacing all spaces with underscores, and then replacing multiple consecutive underscores with one underscore.*

Quoting http://www.mediawiki.org/wiki/Manual:Title.php

*In the article name spaces and underscores are treated as equivalent and each is converted to the other in the appropriate context (underscore in URL and database keys, spaces in plain text). "Extended" characters in the 0x80..0xFF range are allowed in all places, and are valid characters. They are encoded in URLs. Extended characters are not urlencoded when used as text or database keys. Other characters may be ASCII letters, digits, hyphen, comma, period, apostrophe, parentheses and colon. No other ASCII characters are allowed, and will be deleted if found (they will probably cause a browser to misinterpret the URL).*
