### ISSUE TITLE
Highlight changes of a wdiff of Markdown like --track-changes=all for DOCX (Feature request)

### ISSUE THREAD

**Issue by sjackman** [jgm/pandoc#1985]
I am rendering Markdown to PDF. I have two versions of the document in Markdown. I'd like to generate a PDF that highlights the changes from version 1 to version 2, similar to `--track-changes=all` of the DOCX reader. One path to implementation would be to feed as input to Pandoc a wdiff of the two documents, and replace `[-deleted-]` with `<del>deleted</del>` and `{+inserted+}` with `<ins>inserted</ins>`. Is this feature best implemented within Pandoc, or as a script upstream of Pandoc?

**Comment by jgm** [comment]
I would say, as a script.

+++ Shaun Jackman [Mar 02 15 13:16 ]:
