### ISSUE TITLE
List indenting is too picky?

### ISSUE THREAD

**Issue by alinush** [jgm/pandoc#1990]
Hi, I switched from Markdown to Pandoc 1.13.2 and my lists are not being indented properly anymore.

With Pandoc, this happens:

    alinush@xpad [/tmp] $ cat lol.md 
     - Level 1
       + Level 2 (indent me pls!)
    alinush@xpad [/tmp] $ pandoc -f markdown -t html lol.md 
    <ul>
    <li>Level 1</li>
    <li>Level 2 (indent me pls!)</li>
    </ul>

With Markdown , I would get this, as expected:

    alinush@xpad [/tmp] $ cat lol.md 
     - Level 1
       + Level 2 (indent me pls!)
    alinush@xpad [/tmp] $ markdown lol.md 
    <ul>
    <li>Level 1
    <ul>
    <li>Level 2 (indent me pls!)</li>
    </ul></li>
    </ul>

If I add another space after the `+` sign, Pandoc will indent correctly, but that shouldn't be necessary it seems. I'm assuming backwards compatibility is desired.

Any chance you can fix this?

**Comment by nkalvi** [comment]
http://johnmacfarlane.net/pandoc/README.html#lists
>List items may include other lists. In this case the preceding blank line is optional. The nested list must be indented four spaces or one tab:

**Comment by timtylin** [comment]
This is one of the distinctive ways that Pandoc differs from most implementations. [Obligatory link to Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=+-+Level+1%0A+++%2B+Level+2+(indent+me+pls!)%0A)

For a rationale behind this behavior, see item number 10 in the [motivations behind CommonMark](http://spec.commonmark.org/0.18/#why-is-a-spec-needed-). It's worth noting that the [original Markdown specs](http://daringfireball.net/projects/markdown/syntax#list) doesn't explicitly give an example of list-inside-lists but seem to imply a 4-space rule.

**Comment by jgm** [comment]
+++ Tim T.Y. Lin [Mar 04 15 13:23 ]:
>This is one of the distinctive ways that Pandoc differs from most implementations. [Obligatory link to Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=+-+Level+1%0A+++%2B+Level+2+(indent+me+pls!)%0A)
>
>For a rationale behind this behavior, see item number 10 in the [motivations behind CommonMark](http://spec.commonmark.org/0.18/#why-is-a-spec-needed-). It's worth noting that the [original Markdown specs](http://daringfireball.net/projects/markdown/syntax#list) doesn't explicitly give an example of list-inside-lists but seem to imply a 4-space rule.

Note also that CommonMark does not use the 4-space rule, and uses a
different rule that would make your list work.

Anyway, bottom line is, if you want your lists to be maximally portable
across Markdown implementations, use the 4-space rule.

**Comment by alinush** [comment]
I see! Thank you all for the help!

My 2 cents: It's hard for the user to visually inspect that he has 4*k spaces in a k-level sublist. Thus, if it doesn't make parsing harder, it would be more user-friendly to have this limitation removed.

**Comment by jgm** [comment]
+++ Alin Tomescu [Mar 05 15 12:28 ]:
>   I see! Thank you all for the help!
>
>   My 2 cents: It's hard for the user to visually inspect that he has 4*k
>   spaces in a k-level sublist. Thus, if it doesn't make parsing harder,
>   it would be more user-friendly to have this limitation removed.

If it changes, it will change in the direction of CommonMark.

But I think this issue can be closed.

**Comment by bpj** [comment]
It is not so hard to see if you use a fixed-width font, which you need
anyway for tables, and set your editor's tab width to four columns.
Aditionally a good editor can show you what column you are on in its status
bar or equivalent thereof.
Den 5 mar 2015 21:28 skrev "Alin Tomescu" <notifications@github.com>:
