### ISSUE TITLE
Docx problems with UTF8 invisible characters - resulting file is corrupted

### ISSUE THREAD

**Issue by davepwsmith** [jgm/pandoc#1992]
When trying to convert to .docx, the resulting file produces an error on word for mac 2011. The converter only chokes on files that contain UTF8 'FORM FEED (FF)' (U+000C) character.

![screen shot 2015-03-05 at 09 46 57](https://cloud.githubusercontent.com/assets/1024707/6502569/992ae400-c31c-11e4-9a9e-bdc8f8242ed2.png)

**Comment by nkalvi** [comment]
If possible could you please post the file? I have different Word versions and OOXML validator etc.; so I may be able to get more details. BTW, have tried viewing it in https://chrome.google.com/webstore/detail/ooxml-tools/bjmmjfdegplhkefakjkccocjanekbapn?hl=en?

**Comment by davepwsmith** [comment]
Ugh I tracked this down to random unicode invisible character. Now I just need to work out why it keeps getting put there. Sorry!

**Comment by jgm** [comment]
Those error messages from Word give no really useful information.
My suggestion would be to start paring away parts of the
document to see if you can isolate (as tightly as possible)
the part or aspect that is causing a problem.  Then give us
a minimal test case, with Markdown source, any needed
images, and the exact command line you used.

**Comment by jgm** [comment]
+++ David Smith [Mar 05 15 04:31 ]:
>   Ugh I tracked this down to random unicode invisible character. Now I
>   just need to work out why it keeps getting put there. Sorry!

Is it in an ordered list?  What version of pandoc are you using?

**Comment by jgm** [comment]
Can you clarify?  Is the FF character part of your source document, or are you suggesting that it is being inserted by pandoc?  What version of pandoc are you using?

**Comment by davepwsmith** [comment]
The guity .md can literally just be the mentioned character -- http://www.fileformat.info/info/unicode/char/000c/index.htm -- using the latest released binary version of pandoc (mac) and the command:

    pandoc -f markdown -t docx -s -S --filter=pandoc-citeproc markdown_exports/vatest.md -o vatest.docx

**Comment by nkalvi** [comment]
A bit more detailed error message with a markdown with form feed char converted to docx:

> Error on line 18 at column 48: xmlParseCharRef: invalid xmlChar value 12

**Comment by nkalvi** [comment]
@jgm Would it be 'proper' to strip the invalid ones in docx output?

http://www.w3.org/TR/REC-xml/#syntax
>Character Range
>
>[2]   	Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */

**Comment by jgm** [comment]
+++ nkalvi [Mar 06 15 11:22 ]:
>@jgm Would it be 'proper' to strip the invalid ones in docx output?

Yes, that's probably the thing to do.
