### ISSUE TITLE
Reveal.js breaks with v3.0.0

### ISSUE THREAD

**Issue by mirageglobe** [jgm/pandoc#1994]
Hi there,

1) when updated to reveal.js v.3.0.0 . The slideshow generated comes up strange. Identified the problem...
generated html file points to "reveal.js/css/reveal.min.css". In version 3.0.0 min.css file doesnt exist anymore.

![screen shot 2015-03-05 at 19 06 01](https://cloud.githubusercontent.com/assets/577792/6512296/b667cbf2-c36a-11e4-8076-4152d2d199c2.png)

2) when pointing to new "reveal.js/css/reveal.css". layout is skewed to top.

* update: point 2 layout is skewed is fine. found that both reveal.js/js/reveal.min.js and reveal.js/css/reveal.min.css no longer exists.

**Comment by mirageglobe** [comment]
Just a note.. the minified versions can be found : http://www.jsdelivr.com/#!reveal.js
but not in github repo...

from https://github.com/hakimel/reveal.js/releases ...
Other updates:
Minified files (reveal.min.js and reveal.min.css) are no longer tracked in the repo

**Comment by mpickering** [comment]
Is this the same as #1891 ?

**Comment by jgm** [comment]
Yes, this is a dup of #1891.
Using the latest reveal.js template from
https://github.com/jgm/pandoc-templates/blob/master/default.revealjs
should fix things.
