### ISSUE TITLE
ePub pop-up footnotes break in iBooks

### ISSUE THREAD

**Issue by anthonynelzin** [jgm/pandoc#1995]
When reading an ePub book generated by Pandoc with iBooks for iOS, popup footnotes won't open. Here's why. Pandoc writes the footnotes as:

	<a href="#fn1" class="footnoteRef" id="fnref1" epub:type="noteref"><sup>1</sup></a>

When the `<sup>` tag is inside the `<a>` tag, popup footnotes break (for that matter, if any tag is inside the `<a>` tag, the footnote won't work). This is a fairly well documented problem -- here on Github, on the Adobe InDesign forums, or [on Liz Castro's website](http://www.pigsgourdsandwikis.com/2012/05/creating-pop-up-footnotes-in-epub-3-and.html) for example. In order for the footnote to properly work in iBooks, the markup should be :

	<sup><a href="#fn1" class="footnoteRef" id="fnref1" epub:type="noteref">1</a></sup>

Another tweak would go a long way in improving the reliability and legibility of Pandoc-generated ePubs: allowing the user to specify if the footnotes block should be visible (`<section class="footnotes">`, good for books designed to be distributed on many plateforms) or not (`<aside class="footnotes">`, good for books designed to be distributed on the iBooks Store only, or for the iBooks version of the book, as iBooks hides asides by defaults).

Hope it helps!

**Comment by mpickering** [comment]
So you suggest it would be best to extract any tags which are inside links to outside the link? This is not just specific to `sup`?

**Comment by anthonynelzin** [comment]
I've seen it happen with spans, for example. Adobe also told me that “Formatting in footnote text is not supported in pop up footnotes. This is a limitation of iBooks”: putting a `<b>` or an `<i>` or anything else in the `<a>` tag break the footnote.

**Comment by nkalvi** [comment]
Did some quick tests with iBooks on Mac and iPad. Interestingly enough popup footnotes work as expected on iBooks on Mac. Formatting seems to 'break' them in iOS version; I'm wondering whether it will be fixed in future versions (since it works on Mac).

BTW, when output with epub3 option, 'footnotes' section is created (it can be hidden in CSS, as show below). I'm wondering whether style can be used instead of hard-coding *superscript* for footnote references, at least for epubs.

Following seems to work fine in iBooks on Mac and iOS.

Manually removed *\<sup\>* tag:
```
<p>Footnotes</p>
<p>Extension: footnotes</p>
<p>Pandoc’s markdown allows footnotes, using the following syntax:</p>
<p>Here is a footnote reference,
<a class="footnoteRef" epub:type="noteref" href="#fn1" id="fnref1">1</a> 
and another.<a class="footnoteRef" epub:type="noteref" href="#fn2" id="fnref2">2</a></p>
...
<section class="footnotes">
<hr/>
<ol>
<li epub:type="footnote" id="fn1"><p>Here is the footnote.<a href="#fnref1">↩</a></p></li>
```

CSS:
```
.footnoteRef {
    vertical-align:super;
    font-size:smaller;
}
.footnotes {
	display: none;}
```

![pandoc_footnote_modified](https://cloud.githubusercontent.com/assets/2199312/6527081/b89c8d92-c3e5-11e4-80a6-0ee916fe626e.PNG)

**Comment by ousia** [comment]
@anthonynelzin, if you want to remove footnotes, [this filter](https://gist.github.com/mpickering/0fce7cf3124fee8b38a1) may help you.

**Comment by anthonynelzin** [comment]
>  Interestingly enough popup footnotes work as expected on iBooks on Mac

Yep.

> I'm wondering whether it will be fixed in future versions (since it works on Mac)

Seems like it's been there for years. I only catched it recently because I switched to Pandoc to generate my ePubs. Knowing Apple, I wouldn't hold my breath.

>  I'm wondering whether style can be used instead of hard-coding superscript for footnote references, at least for epubs.

It's what I was doing before: it works in iBooks and some versions of the Kindle rendering engine. For the other engines, a little bit of styling goes a long way. Your solution wouldn't be the ugliest one.

@ousia: that could come in handy, thanks!

**Comment by jgm** [comment]
I just realized that pandoc used to put the a inside the sup.  This was changed in
commit b4441c940dc76d1a64636ef88287b38306ebccb4 in order to
make it easier to style the sup.  The thing to do is
probably to change back and put a class on the sup instead,
though this may break some existing styling.


+++ Anthony Nelzin [Mar 09 15 09:29 ]:

**Comment by nkalvi** [comment]
Would it be complicated to leave out `<sup>` altogether and just use styling?

https://code.google.com/p/epub-samples/source/browse/trunk/30/georgia-pls-ssml/EPUB/css/epub.css?r=109
>a[epub|type='noteref'], a[epub\:type='noteref'] { vertical-align: super; }

**Comment by nkalvi** [comment]
Also, if making any EPUB 3 related changes, would it be appropriate to use `<aside>` for footnotes?

http://www.idpf.org/accessibility/guidelines/content/semantics/epub-type.php
> Marking an aside element as a footnote is appropriate, for example, but marking a section as a footnote not so much.

**Comment by anthonynelzin** [comment]
> Also, if making any EPUB 3 related changes, would it be appropriate to use <aside> for footnotes?

It wouldn't be a bad idea: iBooks automatically hides `<aside class="footnotes">`, as it uses popover footnotes; other reading engines would show the same aside, allowing the user to read inline footnotes.

**Comment by Porges** [comment]
I'm incidentally addressing the `<aside>` thing in #4491, since Amazon and Apple both recommend it.
