### ISSUE TITLE
Parsing Latex document with parameters to \lstinline cause parse error

### ISSUE THREAD

**Issue by smarr** [jgm/pandoc#1997]
Hi:
Playing around a little with Pandoc and some Latex documents, I noticed the following issue, with feels like a bug, but might just be generally missing support for \lstinline arguments.

Trying to parse the following Latex document cause the error given below.

```latex
\documentclass{article}
\usepackage{listings}
\begin{document}
main text main \lstinline[basicstyle=\ttfamily]!foobar!.
\end{document}
```

Error:

```
Error at "input" (line 4, column 57):
unexpected "\n"
expecting "["
main text main \lstinline[basicstyle=\ttfamily]!foobar!.
```

The expected result would be that all arguments to \lstinline are parsed correctly.

**Comment by mpickering** [comment]
It looks like [this](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/LaTeX.hs#L511) line needs to be changed to ignore arguments.
