### ISSUE TITLE
correctly handle empty lines in tex blocks

### ISSUE THREAD

**Issue by daurnimator** [jgm/pandoc#2001]
Continuting from mailing list thread: https://groups.google.com/forum/#!msg/pandoc-discuss/4S-MHd1fvNs/cpsyFP5-2oYJ

I was trying to parse https://github.com/wahern/cqueues/blob/master/doc/cqueues.tex and got an error:
```
unexpected '\n' 
%\vspace*{20pt} 
```

**Comment by daurnimator** [comment]
thanks!

**Comment by nashjc** [comment]
I've had a similar issue in a LaTeX file for a novel. I use a custom command 

\newcommand{\I}[1]{{\it#1\rm}}

to allow \I{ } to make some text italic.

I've found that 

\I{ - here's some italic 

new paragraph }

gives the error. 

Moreover, if I put
\I{ - here's some italic }

\I{new paragraph }

I get some missing text. But putting a space after the bracket

\I{ - here's some italic }

\I{ new paragraph }
works.

I've a modest tex file I can provide if needed. 

J Nash
