### ISSUE TITLE
Option to keep intermediate tex?

### ISSUE THREAD

**Issue by jeetsukumaran** [jgm/pandoc#2004]
RMarkdown provides for the option to retain the intermediate TeX source when going from Markdown to PDF via LaTeX (http://rmarkdown.rstudio.com/pdf_document_format.html).

Is there such an option available when running `pandoc` natively, either through some metadata specification or command-line flag?

**Comment by jgm** [comment]
+++ Jeet Sukumaran [Mar 10 15 16:27 ]:
>   RMarkdown provides for the option to retain the intermediate TeX source
>   when going from Markdown to PDF via LaTeX
>   ([1]http://rmarkdown.rstudio.com/pdf_document_format.html).
>
>   Is there such an option available when running pandoc natively, either
>   through some metadata specification or command-line flag?

No.  I've always figured that people who know enough to make use of this will also know how to set up a Makefile to generate tex using pandoc and process it with pdflatex.

**Comment by timtylin** [comment]
You can always get the same effect by just calling `pandoc` twice, you just have to change the output filename extension from pdf to tex the second time

**Comment by jeetsukumaran** [comment]
Thanks.

I am trying to write a Pandoc equivalent of [UseLatex](https://github.com/kmorel/UseLATEX): a CMake module that makes using Pandoc to generate documents very, very, easy.  

Sometimes, it is required to have the document rendered as a PDF (for review) but also as TeX (for submission, which also requires the PDF).

I have set up two rules, one to render the PDF and one to generate the TeX. This achieves what is needed. But it means that any time any of the inputs change, I have to go back and edit the PDF rule as well as the TeX. Doable, but not very elegant! Alternatively, I could put things in a loop, and create the rules programmatically, and this, too, would work. But I was hoping that a simple '--keep-tex' flag or would avoid the need for either duplication and complexity.

**Comment by jeetsukumaran** [comment]
So this was the solution that I came up with in lieu of the "`--keep-tex`" flag:

   https://github.com/jeetsukumaran/cmake-pandocology#generating-both-a-pdf-and-the-tex-and-creating-an-archive-bundle-for-submission

Basically, the TeX gets created as a primary output, and then a post-processing instruction is added to generate the PDF. There probably are lots of kinks to work out with getting all the dependency links sorted out, especially the second-order dependencies.

**Comment by tippetts** [comment]
Is it possible to re-open this issue to keep intermediate tex for the beamer format?

Unless I'm missing something, currently the output to a *.tex file with beamer format only outputs the frames. It would be very useful to output everything (including the filled-in preamble) to make a complete tex file that pdflatex can compile.

**Comment by jgm** [comment]
+++ tippetts [Feb 03 16 14:38 ]:
>   Is it possible to re-open this issue to keep intermediate tex for the
>   beamer format?
>
>   Unless I'm missing something, currently the output to a *.tex file with
>   beamer format only outputs the frames. It would be very useful to
>   output everything (including the filled-in preamble) to make a complete
>   tex file that pdflatex can compile.

You're probably missing the -s option.

**Comment by bisraelsen** [comment]
Is this option still available? I can't see it in the help file, and get an error when trying to use it. Has it changed names?

**Comment by jgm** [comment]
Yes, -s is available.  From the manual page:

    General writer options
       -s, --standalone
              Produce output with an appropriate header and  footer  (e.g.   a
              standalone HTML, LaTeX, TEI, or RTF file, not a fragment).  This
              option is set automatically for pdf, epub, epub3, fb2, docx, and
              odt output.

+++ Brett [Dec 02 16 15:16 ]:

**Comment by bisraelsen** [comment]
So there isn't the possibility of keeping intermediate .tex files when going from .md to .pdf  beamer slides?

**Comment by jgm** [comment]
No, unless you do it manually (have pandoc produce .tex,
then use a Makefile or latexmk or something to go from
that to pdf).

You might look at the --verbose option, which at least
allows you to inspect the intermediate tex.

+++ Brett [Dec 02 16 15:30 ]:
