### ISSUE TITLE
Convertion of equation with {\textup d} to docx not working

### ISSUE THREAD

**Issue by BlackEdder** [jgm/pandoc#2010]
I often use {\textup d} to indicate a differential within equations. This works when converting to pdf, but not when converting to docx. In docx I then just get the full/orginal equation (i.e. $${\textup d}$$) instead of a proper equation.

Without the {\textup } it works like normal.

**Comment by lierdakil** [comment]
`\textup` is not really a math mode command, so it's not really valid LaTeX to use it in math environment. Consider maybe using `\operatorname`. You can also use `\newcommand` to shorten this, e.g.
```latex
\newcommand{\d}{\operatorname d}

$$ \frac{\d x}{\d t} = v_x $$
```
which also works with Markdown input.

**Comment by mpickering** [comment]
Please reopen if you have any more questions but I don't think this is a bug.
