### ISSUE TITLE
Remove html links from man pages (feature request)

### ISSUE THREAD

**Issue by MarkWieczorek** [jgm/pandoc#2011]
I am using a single markdown file to create both unix man pages and html documentation. In the "see also" section, I provide html links to related routines, which works great, but in the man page, these links are explicitly written out, which is not very useful. For example, in the man page, this would appear as

related-routine (related-routine.html)

I have looked through the documentation and have not found a way to remove these links, so I am asking if this might be able to be added as a new feature (with a flag like -nolinks).

**Comment by jgm** [comment]
You can easily do this with a filter.  See the documentation
on filters ("Scripting with pandoc" and filters in the
README).  If you have questions, please ask on
pandoc-discuss.

+++ Mark Wieczorek [Mar 16 15 13:32 ]:

**Comment by MarkWieczorek** [comment]
Thanks. 

It appears that there is not a brew install for this package: would it be possible to add this?

Also, it is not 100% clear to me where I should install these files. It might be useful to put this in the documentation.

**Comment by jgm** [comment]
I think homebrew's policy is not to add a brew formula for something that can be installed with a language-specific package manager (e.g. gem or in this case cabal).

So you'll need to install haskell-platform (I'd use the official installer rather than homebrew for this) and then `cabal install pandoc-types`.

"these files" = which files?

**Comment by mpickering** [comment]
If you need help writing the filter then please post to the mailing list. Some more examples can be found [here](https://github.com/jgm/pandoc/wiki/Pandoc-Filters).
