### ISSUE TITLE
formulas in asciidoc have extra dollars

### ISSUE THREAD

**Issue by andreabedini** [jgm/pandoc#2018]
The conversion from LaTeX to Asciidoc of `$\sqrt{a + b}$` should be `latexmath:[\sqrt{a + b}]`rather than `latexmath:[$\sqrt{a + b}$]`

**Comment by mpickering** [comment]
Is there a way to distinguish between inline math and display math with
Asciidoc?

**Comment by andreabedini** [comment]
with Asciidoctor [there is](http://asciidoctor.org/docs/user-manual/#stem-in). You can do `stem:[sqrt(4) = 2]` (or `latexmath:[\sqrt{4} = 2]` if you use LaTeX syntax) for inlines and
```
[stem] 
++++ 
sqrt(4) = 2
++++
```
for blocks. I have a patch I am testing that implements this behaviour.

**Comment by lierdakil** [comment]
Um. Could I point out, that AsciiDoc user guide [gives examples][1] with `$` signs? @andreabedini, where did you get that there shouldn't be any?

[1]: http://asciidoc.org/userguide.html#X78

**Comment by andreabedini** [comment]
oh, my bad, I must be doing something wrong with asciidoctor then, sorry
