### ISSUE TITLE
pandoc hangs when using divs in tables

### ISSUE THREAD

**Issue by sowirepo** [jgm/pandoc#2020]
When the following html snippet is repeated often in a text, pandoc becomes extremely slow, probably due to an exponential slowdown.

pandoc version pandoc 1.12.2.1

command: pandoc -f html+tex_math_dollars+tex_math_single_backslash --parse-raw  -t latex -s tmp/table.html

```<table>
   <tr>
      <td></td>
      <td>
         <div>
            <ol class="lower-alpha">
               <li>$\;\;\;\;\; a^{r+s}$</li>
               <li>$\;\;\;\;\; a^{r-s}$</li>
               <li>$\;\;\;\;\; a^{r\cdot s}$</li>
               <li>$\;\;\;\;\; a^{\frac{r}{s}}$</li>
               <li>$\;\;\;\;\; a^r\cdot b^r$</li>
               <li>$\;\;\;\;\; \frac{a^r}{b^r}$</li>
            </ol>
         </div>
      </td>
      <td><span></span></td>
      <td>
         <div></div>
      <td>
   </tr>
</table>```

**Comment by mpickering** [comment]
Can you please try again with the latest version?

**Comment by lierdakil** [comment]
Couldn't really reproduce with master (aka 1.13.3). Sure, it takes a couple seconds to parse several thousands of such tables, but removing divs doesn't make a huge difference.

**Comment by sowirepo** [comment]
Hi, Yes, my apologies, I just updated to the newest version 1.13.2 and the problem no longer exists.
Thanks.
