### ISSUE TITLE
preserve hyphenation settings in docx output

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#2021]
Some docx document settings (i. e. autoHyphenation) are stored in the settings.xml of an docx archive. Unfortunately, pandoc does not respect these settings (stored in a custom reference.docx), at least not the hyphenation settings.

It would be great if the docx writer would preserve/transfer these settings (see below for a more or less complete list) to the newly generated docx like it does for the margins, page size, page orientation, etc.

```xml
<w:autoHyphenation />
<w:consecutiveHyphenLimit w:val="2"/>
<w:hyphenationZone w:val="284"/>
<w:doNotHyphenateCaps/>
```

**Comment by lierdakil** [comment]
We use dist archive for settings.xml, because Word sometimes adds references to footnotes or endnotes we don't have. Copying over settings that you mention should be relatively easy however. I'll see what I can do.

**Comment by tolot27** [comment]
It works as expected. Great! Thanks!
