### ISSUE TITLE
package ‘pandoc’ is not available (as a binary package for R version 3.1.3)

### ISSUE THREAD

**Issue by rwillis** [jgm/pandoc#2024]
I looked through the comments almost to the end and did not see any questions that lined up with mine. I am an R newbie, but am really excited about using pandoc in conjunction with pander to make some excellent HTML tables. I tried to load the pandoc package in R Studio... I even downloaded it manually and tried to load it that way. The error message that pops up makes it sound like my new version of R is incompatible with the package. 

Here is my install code and the error: 

    > install.packages("pandoc")
    Installing package into ‘C:/Users/rwillis/Documents/R/win-library/3.1’
    (as ‘lib’ is unspecified)
    Warning in install.packages :
    package ‘pandoc’ is not available (as a binary package for R version 3.1.3)

Please help me! I'm sure it is an easy fix, but the error message just is not intuitive to me.

-Beck

**Comment by jgm** [comment]
Sorry, I don't know anything about the R package.  You should report
this to whoever it is who packages that, and close this.  If you want
to put something on the pandoc-discuss list, someone there might be
able to help you.

+++ Beck Willis [Mar 24 15 17:29 ]:

**Comment by michelk** [comment]
Hi Beck,
`pandoc` is not a R package.

You could install `pander` with

```R
 R> install.packages('pander')
```

`pandoc` you have to install separately for your [system](http://johnmacfarlane.net/pandoc/installing.html).

**Comment by rwillis** [comment]
Oh wow... that explains a lot. Sorry to bother you. I will start bugging the "pander" package folks. Take care!
