### ISSUE TITLE
thin space is not converted to corresponding unicode character by some writers

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#2025]
At least the docx writer does not convert the thin space `\,` into the corresponding U+202F character. Rather than the backslash is removed und just the comma is printed.

The same applies to the latex writer (with/without `--parse-raw`) and probably other writers, too.

**Comment by tolot27** [comment]
Sorry, forgot the pandoc version used: 1.13.2 and latest dev from today.

**Comment by tolot27** [comment]
If the extension "all_symbols_escapable" is deactived (`-f markdown-all_symbols_escapable`) it works for latex/pdf documents but not with docx. Then, even the non-breaking space is removed.

**Comment by nkalvi** [comment]
@tolot27 Could you give an example doc?

I tested quickly with non-breaking space with `\ ` (i.e. backslash escaped space) in text and it converts to `~` in latex and to the correct char in Word.

As for `\,`, using it in math context seems to work (an example will help me understand the context). 

I'm not familiar with LaTex that much so, I looked at: http://en.m.wikipedia.org/wiki/Thin_space and http://texblog.org/2014/04/09/whitespace-in-math-mode/

**Comment by tolot27** [comment]
The following markdown fully works with latex output only if `-f markdown-all_symbols_escapable` is used:

```markdown
Non-breaking space between foo\ bar and non-breaking thin space between bar\,foot.
```

Converting this line with `-f markdown-all_symbols_escapable` to docx, removes the space and comma:

```
Non-breaking space between foobar and non-breaking thin space between barfoot.
```

Converting it to docx without the `-f` parameter correctly produces the non-breaking space but does not produce the U+202F character. Instead the comma is printed.

```
Non-breaking space between foo bar and non-breaking thin space between bar,foot.
```

Okay that was just the repetition of the above report, but now fully reproducible. Dos it helps?

**Comment by nkalvi** [comment]
Thanks. 

I don't know whether this will help - enclosing in `$ $`
```
Non-breaking space between foo\ bar and non-breaking thin space between bar$\,$foot.
```
and outputting docx without -f markdown-all_symbols_escapable looks like this in Word (cannot see U+202F being output though):

![thin space](https://cloud.githubusercontent.com/assets/2199312/6824040/9db61730-d2c4-11e4-8790-0080945e9361.png)


Document XML inside docx:
```
    <w:body>
        <w:p>
            <w:pPr>
                <w:pStyle w:val="FirstParagraph" />
            </w:pPr>
            <w:r>
                <w:t xml:space="preserve">Non-breaking space between foo</w:t>
            </w:r>
            <w:r>
                <w:t xml:space="preserve">bar and non-breaking thin space between bar</w:t>
            </w:r>
            <m:oMath>
                <m:r>
                    <m:rPr>
                        <m:sty m:val="p" />
                    </m:rPr>
                    <m:t></m:t>
                </m:r>
            </m:oMath>
            <w:r>
                <w:t xml:space="preserve">foot.</w:t>
            </w:r>
        </w:p>
        <w:sectPr />
    </w:body>
```

**Comment by tolot27** [comment]
Thanks for this workaround. But now I have to type two more symbols and the readability is reduced and complexity in output dokument is increased (math environments). Also, I expect further problems with output formats which do not support math, but support unicode.

I would really like to see a fix for this bug.

**Comment by mpickering** [comment]
I don't see how this is a bug. If you turn off the "all symbols escapable"
extension then \, is parsed as a raw latex command which is just passed
through when rendering latex. I think your best bet is to write a filter
which replaces the latex command \, with the unicode character you want if
the output format isn't latex.

We can help you write this filter if you think this is a good option.

**Comment by lierdakil** [comment]
Technically, this is not a bug. `\,` is not technically valid Markdown at all:

>Markdown provides backslash escapes for the following characters:
>
>\\   backslash
>\`   backtick
>\*   asterisk
>\_   underscore
>\{}  curly braces
>\[]  square brackets
>\()  parentheses
>\#   hash mark
>\+   plus sign
>\-   minus sign (hyphen)
>\.   dot
>\!   exclamation mark

Extension all_symbols_escapable allows to apply backslash escapes to any symbol (as in CommonMark), and it takes precedence over embedded LaTeX parser (which is passed through only to LaTeX writer).

So, in short, no, this is not how you make a thin space in Markdown. You should probably try to input thin space as unicode character. Make a reasonable shortcut for that in your favorite editor. If this is not compelling for you, you can, of course, write a filter. It shouldn't be very hard to do.

**Comment by lierdakil** [comment]
Something along these lines would work, I reckon.

```haskell
import Text.Pandoc.JSON
import Data.List (isPrefixOf)

main :: IO ()
main = toJSONFilter go

go :: Maybe Format -> Inline -> Inline
go (Just (Format f)) (RawInline (Format "tex") "\\,") | not $ "latex" `isPrefixOf` f = Str "\x202F"
go _ x = x
```

**Comment by tolot27** [comment]
Okay, thanks for clarification and the sample filter code. Inserting the raw unicode non-breaking thin space charachter in the text is not an issue. It is more or less that it can't be distinguished from a normal space. But you are right, that's an issue for the text editor.

Even if `\,` is not valid markdown/CommonMark syntax, I still wonder why the Latex Writer supports so much more functionality compared to other writers. Even if `--parse-raw` is not used, the thin space is converted correctly. To achive the same behaviour for other output formats, one has to create a filter. That is a bit confusing for me.

**Comment by jgm** [comment]
+++ Mathias Walter [Mar 25 15 04:42 ]:
>The following markdown fully works with latex output only if `-f markdown-all_symbols_escapable` is used:
>
>```markdown
>Non-breaking space between foo\ bar and non-breaking thin space between bar\,foot.
>```
>
>Converting this line with `-f markdown-all_symbols_escapable` to docx, removes the space and comma:

That's because the `\,` is parsed as raw tex, and thus omitted in non-tex output formats.

`\,` in Markdown is never parsed as a thin space.  In latex it works (after disabling escaping for the comma) only because raw latex is passed through.

In short: I don't see a bug here.  If you're writing Markdown and want a thin space, just insert a unicode thin space character.

**Comment by tolot27** [comment]
Because it is not a bug and is not supported by markdown, I'll close this issue.

**Comment by rriemann** [comment]
Just for future reference:

I use Kile as an editor that highlights some non-printable utf8 characters like protected spaces. My keyboard (neo layout) allows me to enter utf8 directly. pandoc converts those characters to their latex equivalent. Everything works fine.

I suggest to enter the utf8 character directly in the source markdown.
