### ISSUE TITLE
Table not shown in odt-file

### ISSUE THREAD

**Issue by AugustH** [jgm/pandoc#2027]
The following short example shows both tables in the pdf-file but ignores the second one in the odt-file.

```
This is a table

------ ------ 
 some   data 
------ ------ 

Another table, but some blanks 

*   a list
    and an indented table

    ------ ------ 
     some   data 
    ------ ------ 

* We are done.
```

Command line:

```
pandoc bug.md -o bug.pdf
pandoc bug.md -o bug.odt
```

I am using pandoc 1.13.2 on gentoo linux.

**Comment by jgm** [comment]
Hm, according to [the spec](http://docs.oasis-open.org/office/v1.2/cs01/OpenDocument-v1.2-cs01-part1.html#__RefHeading__1415580_253892949), a table isn't allowed in a list-item.

```
The <table:table> element is usable within the following elements: <chart:chart> 11.1, <draw:frame> 10.4.2, <draw:text-box> 10.4.3, <office:spreadsheet> 3.7, <office:text> 3.4, <style:footer> 16.11, <style:footer-left> 16.13, <style:header> 16.10, <style:header-left> 16.12, <table:covered-table-cell> 9.1.5, <table:dde-link> 14.6.4, <table:table-cell> 9.1.4, <text:deletion> 5.5.4, <text:index-body> 8.2.2, <text:index-title> 8.2.3, <text:note-body> 6.3.4 and <text:section> 5.4.
```

Given that restriction, I'm not sure we can do much about this issue.

**Comment by AugustH** [comment]
But "don't display" is also not really an option -- an error message would be nice.

And Libreoffice allows tables within lists:

Write a list like

1. one
2. two X
3. three

position the cursor after the X press Enter, Backspace and select menu: table / insert table. That gives a table within the numbered list.

**Comment by jgm** [comment]
+++ AugustH [Dec 14 15 00:38 ]:
>   But "don't display" is also not really an option -- an error message
>   would be nice.
>
>   And Libreoffice allows tables within lists:
>
>   Write a list like
>    1. one
>    2. two X
>    3. three
>
>   position the cursor after the X press Enter, Backspace and select menu:
>   table / insert table. That gives a table within the numbered list.

When I tried this, I got a table that was actually not
inside the list item.  The list item closed, then the table
began.  (Verified by looking at the xml.)  The table was
not indented to fit inside the list item.  Do you see
something different?

**Comment by AugustH** [comment]
ok - but the list goes "around" the table: it is still one list, if you but the cursor past the "one" and press enter you get a new entry. And the 4. which is past the table is incremented to 5. -- so i would call this a table within the list. Although i must admit that the indentation may be wrong.

Whatever -- if it is not displayed there should be  a message for the user. I understand that pandoc doesn't have all possible types of formatting  (and can't have for all the output formats), but i expect to get either an error or all the text.

**Comment by jgm** [comment]
This is basically the same issue as #3430.
Since there's more information over there, I'm closing this issue in favor of that one.
