### ISSUE TITLE
HTML to EPUB: MathML becomes TeX

### ISSUE THREAD

**Issue by guaraqe** [jgm/pandoc#2028]
When converting HTML that contains MathML to ePub, the output is unexpected. Some part of the equations stay in MathML and another part gets translated to TeX, even when the option --mathml is given. Sometimes parts of the equation are repeated.

I was not able to understand the factors that make the equation to be translated or not. Both inline and block MathML get transformed. The version of pandoc is 1.13.2, with texmath 0.8.0.1.

I uploaded an example here: https://github.com/guaraqe/error

**Comment by jgm** [comment]
Note that `-t epub` (or just using an `.epub` extension for the output
file) will give you EPUB v2 by default.  EPUB v2 does not support
MathML.  So, the following is done:  where possible, pandoc tries
to render the formulas with ordinary HTML and unicode characters.
When it fails, it falls back to displaying the raw LaTeX.  This is
what you're seeing.

If you want MathML to be used in the EPUB, then you must specify
`-t epub3`, which gives EPUB v3 semantics.  You'll find that if you
do

    pandoc -t epub3 --mathml test.html -o test.epub

you'll get all the equations in MathML.

If instead you want them all in TeX, you could use the `--mathjax` option.

+++ guaraqe [Mar 26 15 21:57 ]:

**Comment by guaraqe** [comment]
I had tested already with this flag, and also with the flag -R that was suggested in another issue. The output is the same yet.

**Comment by nkalvi** [comment]
@guaraqe could you please let us know how you're viewing the resulting ePub with epub3 option?

Here's how it looks in iBooks on Mac and iPad with  `pandoc -t epub3 test.html -o test3.epub`:

HTML file in Safari and ePub in iBooks 1.1.1 on Mac:
![error comapre](https://cloud.githubusercontent.com/assets/2199312/6867689/d45822a0-d45a-11e4-885a-e1be91d89ce3.png)

Same ePub on iPad with iOS 8.2:
![mathml epub on ipad](https://cloud.githubusercontent.com/assets/2199312/6867715/1ddf9598-d45b-11e4-9b6d-5c5a2f6e262f.PNG)

**Comment by nkalvi** [comment]
BTW, the same ePub looks like this when Sigil 0.8.4 on my Mac (I don't it supports ePub3):

![sigil preview of error](https://cloud.githubusercontent.com/assets/2199312/6867812/1be0b06e-d45c-11e4-97e2-37ed54023a88.png)

**Comment by guaraqe** [comment]
OK, I think I understood what is happening. I was viewing them both with a Kobo and FBReader, and the results are the same as the last image. I was looking at the source code also of ch001.xhtml and there was the TeX formulas, but now I see they are contained inside <annotation></annotation> and these readers probably don't know what do with it. So the problem is about the readers and not pandoc. Thanks and sorry for the incovenience.

**Comment by nkalvi** [comment]
@guaraqe You're welcome. I'm not sure how helpful/accurate this is, but you may want take a look:

http://epubtest.org/compare/
