### ISSUE TITLE
Citations not rendered consistently

### ISSUE THREAD

**Issue by houshuang** [jgm/pandoc#2029]
I have a bit of a weird issue, where citations sometimes contain the first names (in-text APA citations) and sometimes not, seemingly based on the context. Here is an example, the text:

> Some theorists have offered more fine-grained descriptions of learning models, such as peer tutoring [@roscoe2004influence], case-based learning [@hutchings1993using]  or self explanation [@chi1989learning].  Such “molecules of instruction” reveal some productive patterns, and appear to be well positioned as elements of a higher level design, yet there remains a need for theoretically guided assembly of broader instructional designs.

Results in the output (Notice the `M. T. Chi`):

> Some theorists have offered more fine-grained descriptions of learning models, such as peer tutoring (Roscoe & Chi, 2004), case-based learning (Hutchings, 1993) or self explanation (M. T. Chi & Bassok, 1989). Such “molecules of instruction” reveal some productive patterns, and appear to be well positioned as elements of a higher level design, yet there remains a need for theoretically guided assembly of broader instructional designs.

However, an even smaller example:

> This is fun [@chi1989learning]

Using exactly the same bibliography file and CSL, results in the correct:

> This is fun (Chi & Bassok, 1989)

In my full paper, I have a number of these cases, some disappeared when I tried to make a minimal example. The bibliography used in both examples is [attached](https://gist.github.com/houshuang/842d144631061511f053).

Desired outcome: Citations should be rendered consistently, regardless of the text around them, and using APA, in-text APA citations should never include first names or initials.

**Comment by houshuang** [comment]
Confirmed that this has not changed in current head.

**Comment by nkalvi** [comment]
@houshuang Isn't it because the author (Chi) is mentioned slightly differently?

```
@article{chi1989learning,
	Author = {Chi, Michelene TH and Bassok, Miriam},
```
and here as
```
@inproceedings{roscoe2004influence,
	Author = {Roscoe, Rod D and Chi, M},
```

Changing the second reference to *Chi, Michelene TH* results in

><p>Some theorists have offered more fine-grained descriptions of learning models, such as peer tutoring <span class="citation">(Roscoe and Chi 2004)</span>, case-based learning <span class="citation">(Hutchings 1993)</span> or self explanation <span class="citation">(Chi and Bassok 1989)</span>. Such “molecules of instruction” reveal some productive patterns, and appear to be well positioned as elements of a higher level design, yet there remains a need for theoretically guided assembly of broader instructional designs.</p>
<div class="references">
<p>Chi, Michelene TH, and Miriam Bassok. 1989. “Learning from Examples via Self-Explanations.” <em>Knowing, Learning, and Instruction: Essays in Honor of Robert Glaser</em>, 251–82.</p>
<p>Hutchings, Pat. 1993. <em>Using Cases to Improve College Teaching: A Guide to More Reflective Practice</em>. Amer Assn for Higher Education.</p>
<p>Roscoe, Rod D, and Michelene TH Chi. 2004. “The Influence of the Tutee in Learning by Peer Tutoring.” In <em>Proceedings the 26th Annual Meeting of the Cognitive Science Society</em>, 1179–84.</p>
</div>

**Comment by houshuang** [comment]
Ah, so you are saying this is Pandoc's way of distinguishing between two authors with the same last name (that are actually the same author, but due to how the data is stored)? That makes a lot of sense, but means I'll have to spend a bunch of time cleaning up my large Bibtex file, since there is a lot of inconsistencies from Google Scholar imports etc...

**Comment by nkalvi** [comment]
I don't think it is specific to Pandoc though, since there can be authors who have the same last name.

**Comment by houshuang** [comment]
Would love if there was at least an option to output these kind of naming collisions. Currently I like how it prints out citations that were not found in the bibliography file, making it easy for me to check if I have misspelt something, or forgot to add a citation, rather than searching through the file for ???s. If it could similarly output names of authors that share the same last name, I could quickly check if they are supposed to or not.

**Comment by nkalvi** [comment]
@houshuang I've never used this, but have you looked at this one?

http://jabref.sourceforge.net

**Comment by nickbart1980** [comment]
A very common problem – see https://www.zotero.org/support/kb/given_name_disambiguation – and not a pandoc issue at all.

**Comment by houshuang** [comment]
Yes, I use BibDesk, and in the past I have gone through and cleaned up
references. I understand this is not a Pandoc issue, but this makes me want
to develop a markdown linter for academic documents, to catch this and
similar errors. Anyway thank you for the explanations. Perhaps this should
be included somewhere as a note in the documentation on Pandoc/Citeproc
("Note that if bibtex records are not consistent..."), since others might
come across the same "surprising" results as me.

Thanks again, just submitted my comprehensive exam in Markdown using
Pandoc, with 140 citations. Couldn't imagine doing it any other way:)

On Fri, Mar 27, 2015 at 11:00 AM, nickbart1980 <notifications@github.com>
wrote:

> A very common problem – see
> https://www.zotero.org/support/kb/given_name_disambiguation – and not a
> pandoc issue at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgm/pandoc/issues/2029#issuecomment-86964991>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by nkalvi** [comment]
Congratulations! 

Pandoc is very powerful indeed:

>By default, `pandoc-citeproc` will use a Chicago author-date format for
citations and references.  To use another style, you will need to specify
a [CSL] 1.0 style file in the `csl` metadata field.  A primer on creating and
modifying CSL styles can be found at
<http://citationstyles.org/downloads/primer.html>.  A repository of CSL styles
can be found at <https://github.com/citation-style-language/styles>.  See also
<http://zotero.org/styles> for easy browsing.

As @nickbart1980 pointed out, one can create style file per https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step
>Changing Disambiguation
>
>CSL offers multiple methods to disambiguate cites or names. For example, a style might normally render only the family name (e.g., ”(Doe 1999, Doe 2002)”). If the authors are Jane Doe and Thomas Doe, these names can be disambiguated by adding initials or the full given names (e.g., ”(J. Doe 1999, T. Doe 2002)”).
>
>Disambiguation methods are selected on the citation element. For example, to disable given name disambiguation, delete the disambiguate-add-givenname attribute, e.g. change
>
```
<citation disambiguate-add-givenname="true">
  ...
</citation>
to
>
<citation>
  ...
</citation>
```

**Comment by houshuang** [comment]
OK, so a work-around would be to modify the apa stylesheet to not ambiguate
author names... However, I am still fascinated by the idea of a linter,
which could warn about this, but also a lot of smaller issues, like no
space between text and parenthesis, two periods after each other, using ()
instead of [] for a citation, etc. Maybe something I'll play with.

Thanks again, I learnt a lot.

On Fri, Mar 27, 2015 at 11:43 AM, nkalvi <notifications@github.com> wrote:

> Congratulations!
>
> Pandoc is very powerful indeed:
>
> By default, pandoc-citeproc will use a Chicago author-date format for
> citations and references. To use another style, you will need to specify
> a [CSL] 1.0 style file in the csl metadata field. A primer on creating and
> modifying CSL styles can be found at
> http://citationstyles.org/downloads/primer.html. A repository of CSL
> styles
> can be found at https://github.com/citation-style-language/styles. See
> also
> http://zotero.org/styles for easy browsing.
>
> As @nickbart1980 <https://github.com/nickbart1980> pointed out, one can
> create style file per
> https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step
>
> Changing Disambiguation
>
> CSL offers multiple methods to disambiguate cites or names. For example, a
> style might normally render only the family name (e.g., ”(Doe 1999, Doe
> 2002)”). If the authors are Jane Doe and Thomas Doe, these names can be
> disambiguated by adding initials or the full given names (e.g., ”(J. Doe
> 1999, T. Doe 2002)”).
>
> Disambiguation methods are selected on the citation element. For example,
> to disable given name disambiguation, delete the disambiguate-add-givenname
> attribute, e.g. change
>
> <citation disambiguate-add-givenname="true">
>   ...
> </citation>
> to
>
> <citation>
>   ...
> </citation>
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgm/pandoc/issues/2029#issuecomment-86979986>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by naught101** [comment]
This doesn't help when you have two papers with different authors with the same last name (in which case the initials will always show. Does anyone know if there is an easy way to modify the APA stylesheet so that it doesn't do this? The citations can almost always be worked out from the bibliography anyway, and most journals I know wouldn't accept these citations.

**Comment by njbart** [comment]
Again: not a pandoc (or pandoc-citeproc) issue at all. 

Besides, what you propose (“can almost always be worked out”) runs foul of sound bibliographic principles, and sweeping claims about “most journals” are irrelevant as long as you do not point out specific discrepancies between a published style guide and the corresponding CSL style file.

**Comment by monicaycli** [comment]
Although as @njbart said this is not a pandoc-citeproc problem, but this issue thread is what helped me find the solution so I thought I would share it here for other people's benefits.

Upon reading CSL's documentation, I found that there are many ways to define author/citation disambiguation. http://docs.citationstyles.org/en/1.0.1/specification.html#disambiguation

@naught101's problem should be solved by specifying `givenname-disambiguation-rule="by-cite"` in the `citation` block of a given CSL file.
