### ISSUE TITLE
DocX: figure and figure caption are separated at page boundaries

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#2031]
If a figure is placed at the end of a page, its caption is moved/placed at the next page. See https://groups.google.com/d/topic/pandoc-discuss/DKEuJl242sE/discussion for a more detailed explanation.

Proposol: either asign a new format style (i.e. 'image') which has the 'Keep with next' paragraph option set by default and is adjustable in any way (i. e. center align) or write the following XML node `w:pPr` to the image paragraph during docx creation:

```xml
		<w:p>
			<w:pPr>
				<w:keepNext />
				<w:jc w:val="center" />
			</w:pPr>
			<w:r>
				...
```

**Comment by lierdakil** [comment]
#2035 should work, but it feels a little bit clunky, since figures with empty captions need special handling. If you have any suggestions, please leave a comment there.

**Comment by jgm** [comment]
Closing this, as the patch has been merged.
