### ISSUE TITLE
reference.docx corrupt

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#2032]
Opening `data/reference.docx` gives the warning "One or more footnotes referenced in this document are missing or corrupt."  This must be due to a fairly recent change in `data/reference.docx` -- perhaps 1cb601d2885df09fe07533006c06d8a603c3020d or ba59e5447ffe8d15dd7fee69a7aa03706ce3c49b.

First step is to track down which commit introduced the problem.

**Comment by nkalvi** [comment]
@jgm I'm wondering whether reference to footnotes in **word/settings.xml**

```
    <w:footnotePr>
        <w:footnote w:id="-1" />
        <w:footnote w:id="0" />
    </w:footnotePr>
```

is the cause. To remedy, something like the following can be added to **word/footnotes.xml** (which is now empty):

```
<?xml version="1.0" encoding="UTF-8"?>
<w:footnotes
    xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
    xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    xmlns:o="urn:schemas-microsoft-com:office:office"
    xmlns:v="urn:schemas-microsoft-com:vml"
    xmlns:w10="urn:schemas-microsoft-com:office:word"
    xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"
    xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
    <w:footnote w:type="separator" w:id="-1">
        <w:p w:rsidR="00AC05CC" w:rsidRDefault="00AC05CC" w:rsidP="0051672D">
            <w:r>
                <w:separator/>
            </w:r>
        </w:p>
    </w:footnote>
    <w:footnote w:type="continuationSeparator" w:id="0">
        <w:p w:rsidR="00AC05CC" w:rsidRDefault="00AC05CC" w:rsidP="0051672D">
            <w:r>
                <w:continuationSeparator/>
            </w:r>
        </w:p>
    </w:footnote>
</w:footnotes>
```

When I tested with this addition, the error was gone (of course separator etc. need to be set to the desired values.)

**Comment by nkalvi** [comment]
Though not relevant, I'm wondering whether **word/_rels/footnotes.xml.rels** is necessary (removing it does not seem to break anything).

**Comment by lierdakil** [comment]
This is due to ba59e5447ffe8d15dd7fee69a7aa03706ce3c49b. It's not exactly a bug per se. Docx Writer inserts default footnotes into resulting docx, like so:

```haskell
defaultFootnotes = [ mknode "w:footnote"
                     [("w:type", "separator"), ("w:id", "-1")] $
                     [ mknode "w:p" [] $
                       [mknode "w:r" [] $
                        [ mknode "w:separator" [] ()]]]
                   , mknode "w:footnote"
                     [("w:type", "continuationSeparator"), ("w:id", "0")] $
                     [ mknode "w:p" [] $
                       [ mknode "w:r" [] $
                         [ mknode "w:continuationSeparator" [] ()]]]]
```

Furthermore, Docx Writer seems to ignore contents of word/footnotes.xml from reference.docx, so this does not affect resulting docx at all.

However, it may be a good idea to make reference.docx mirror `defaultFootnotes`, for the sake of consistency and whatnot.

**Comment by lierdakil** [comment]
PR #2034 should fix this. Tested with Word 2013.
