### ISSUE TITLE
Docx: separate format style for tables

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#2033]
Because the compact style in docx files is used not only by compact lists, but also for table cells, it is not possible to give tables their own look.

Hence, I propose a different style which is only applied to tables.

**Comment by lierdakil** [comment]
That's going to be a little hard. Consider for example the case when there is a compact list inside a table cell. Pandoc uses `Plain` AST element for table cells, same as for compact list items. How to differentiate between them?

**Comment by tolot27** [comment]
Currently, I know nearly nothing about the implementation side in pandoc and why it represents two different syntactic and symantic elements as the same AST element. Is this intentional or just caused by code evolution?

From the users point of view I guess that having a compact list inside a table is much less frequent than having simple tables and compact lists outside of tables. Hence the benefit of a "plain table style" would outweight the rare cases of compact lists inside tables.

But indeed, in inconsistency would be introduced at the same time.

**Comment by tolot27** [comment]
As far as I can see, pandoc allows lists inside tables only for grid tables and the extension `grid_tables` is enabled by default. But to recognize this lists inside a table cell and format them in writers correctly, it have to be distinguishable from plain cells, already.

**Comment by lierdakil** [comment]
Pandoc's AST does not make any distinction between different table
definition methods offered by Markdown, since it does not make sense for
most supported formats anyway (think html->docx for example). Hence, table
is just a table. And table cells are block-level elements, `Plain` being
the simplest.
Docx also does not offer a distinction between table cells and general
paragraphs, so I'm really not sure how to implement what you're asking for
in an unambiguous way...

2015-03-29 20:48 GMT+03:00 Mathias Walter <notifications@github.com>:

**Comment by tolot27** [comment]
You are right in that way that in Word there is no predefined style for tables. But there are themes available for tables and you can create a custom style with style type 'table' and can define first, last, even, odd rows, etc.
There is no reason against just defining a table style (based on standard paragraph style) and apply it to the whole table. If a table cell contains a list, it can be formatted as compact or an additional style 'List in Table Cell' can be applied to it.

BTW: There are some predefined styles for (un-)numbered lists. Personally, I would use those styles for the different kind of lists pandoc can generate, rather than the compact style.

**Comment by lierdakil** [comment]
Lists in Word are... weird, let's leave it at that for now. It would be a *very* non-trivial thing to use list styles on lists, as unintuitive as it might sound. I might tackle this later, but not for a while most likely.

As for tables, I could probably hack together a solution for most-used case, i.e. plain text in cells, but it will probably be hacky as hell, so I'm not sure it is *the* right thing to do. It *is* possible to do with a filter though (yes, yes, I know, answer to every other request seems to be "use a filter", but that's kind of how it is...)

**Comment by jgm** [comment]
See also #774 which is more general.

**Comment by gepcel** [comment]
This will be very useful.

I recently used pandoc to generate some docx format reports. When set `indent: true`, the contents of table were also indented. Couldn't find a way to un-indent table contents only.

Anyone working on this?

**Comment by ociule** [comment]
This can be closed, IMO, as pandoc 2.2.1 uses the "Table" table style from the reference-doc now.
