### ISSUE TITLE
--epub-stylesheet and --css

### ISSUE THREAD

**Issue by r-gaia-cs** [jgm/pandoc#2040]
Why `--epub-stylesheet` and `--css` instead of only `--css`?

At `data/templates/default.html5` and `data/templates/default.epub3` we have

~~~
$for(css)$
  <link rel="stylesheet" href="$css$">
$endfor$
~~~

but

~~~
$ pandoc -t epub -o sample.epub --css=style1.css --css=style2.css sample.md
$ unzip -l sample.epub                                                     
Archive:  sample.epub
  Length      Date    Time    Name
---------  ---------- -----   ----
       20  2015-03-29 15:13   mimetype
      246  2015-03-29 15:13   META-INF/container.xml
      160  2015-03-29 15:13   META-INF/com.apple.ibooks.display-options.xml
      439  2015-03-29 15:13   stylesheet.css
      639  2015-03-29 15:13   title_page.xhtml
     1115  2015-03-29 15:13   content.opf
      721  2015-03-29 15:13   toc.ncx
      758  2015-03-29 15:13   nav.xhtml
      697  2015-03-29 15:13   ch001.xhtml
---------                     -------
     4795                     9 files
$ unzip -c sample.epub stylesheet.css                                      
Archive:  sample.epub
  inflating: stylesheet.css          
/* This defines styles and classes used in the book */
body { margin: 5%; text-align: justify; font-size: medium; }
code { font-family: monospace; }
h1 { text-align: left; }
h2 { text-align: left; }
h3 { text-align: left; }
h4 { text-align: left; }
h5 { text-align: left; }
h6 { text-align: left; }
h1.title { }
h2.author { }
h3.date { }
ol.toc { padding: 0; margin-left: 1em; }
ol.toc li { list-style-type: none; margin: 0; padding: 0; }
$ unzip -c sample.epub ch001.xhtml                                         
Archive:  sample.epub
  inflating: ch001.xhtml             
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title>Foo</title>
  <link rel="stylesheet" type="text/css" href="stylesheet.css" />
  <link rel="stylesheet" type="text/css" href="style1.css" />
  <link rel="stylesheet" type="text/css" href="style2.css" />
</head>
<body>
<div id="foo" class="section level1 unnumbered">
<h1>Foo</h1>
<p>Some text.</p>
</div>
</body>
</html>
~~~

I.e. EPUB writer accepts `--css` and the CSS are present at the HTML file but it isn't available at the EPUB file. My suggestion is make `--epub-stylesheet` a alias for `--css` and change EPUB writer for add all css into the EPUB file.

**Comment by jgm** [comment]
Note:  there may be a couple of extra complexities, since currently
we're only including *one* stylesheet in the epub.  We'd have to modify
the code to copy over all the stylesheets linked by `--css`.  And,
since e.g. you might have `--css foo/bar.css --css baz/bar.css`, we
might need to rename the stylesheets, which would require modifying
the links in the templates.  (Though I suppose I'd be okay with just
ignoring the, admittedly unlikely, possibility of such conflicts.)

**Comment by jgm** [comment]
I changed my mind about this.  `--css` and `--epub-stylesheet` have sufficiently different semantics that I don't think we should collapse them.

**Comment by earthbound19** [comment]
Suprise! They're collapsed! I guess? It's what pandoc says to me now :)

**Comment by mb21** [comment]
Hm.. could we not make `--css` take a file as well?

Or alternatively, just introduce a template variable `stylesheet`, which the EPUB reader could make use of, and add this to the HTML template:

     <style>
      $stylesheet$
    </style>

From an end-user perspective, it really doesn't make much sense that the option is different for EPUB and HTML.

**Comment by jgm** [comment]
`--epub-stylesheet` has been removed and deprecated.  Now you use `--css`.

**Comment by mb21** [comment]
Oh wow, I think I just somehow got a GitHub notification on your comment from May 2015. Nothing has changed here in the last few days. Disregard my comment...
