### ISSUE TITLE
More Sphinx ReST extensions

### ISSUE THREAD

**Issue by nwf** [jgm/pandoc#2043]
Greetings!

We have a large corpus of documents written in Sphinx-flavored ReST and we'd like to process them with pandoc.  In addition to the concerns already recorded in #223, we make heavy use of its :ref: and :doc: roles and _-prefixed anchor directives which AFAICT Pandoc does not support.

Would these be easy to add?  I am familiar with Haskell but not with pandoc's internals.

Thanks!
--nwf;

**Comment by jgm** [comment]
Questions like this (as opposed to bug reports) should go to the
pandoc-discuss mailing list, where many more people will see them.
Specific enhancement requests can go here, but it's good to hammer out
the details on the mailing list first.
