### ISSUE TITLE
No optical version of MinionPro

### ISSUE THREAD

**Issue by Jmuccigr** [jgm/pandoc#2046]
I don't have the optical version of MinionPro and I think this is causing pandoc to throw out this error:

````Font T1/MinionPro-OsF/m/n/17.28=MinionPro-Subh-osf-t1 at 17.28pt not loadable````

If that's right, where in the default.latex file is the font being set exactly, so I can unset it (assuming I'm understanding all this correctly)?

Thanks.

**Comment by jgm** [comment]
MinionPro isn't in any of the default templates.  Are you sure you're
using the default template, and not a custom one (might be in
`~/.pandoc/templates`)?

+++ John Muccigrosso [Mar 30 15 09:11 ]:

**Comment by Jmuccigr** [comment]
That was it. I had an earlier problem and hadn't undone my changes. Sorry for the trouble. Thanks.
