### ISSUE TITLE
Double quote being misinterpreted

### ISSUE THREAD

**Issue by abudden** [jgm/pandoc#2049]
I think this is closely related to #1909, but this is an instance of the double-quote being misinterpreted and the single-quote being interpreted correctly.  If the double-quote comes after a number, it is not bound to the number.  The specific markdown in question was written as a unit specification (6 feet and 6 inches):

    ... 6'6").

This was rendered as 6&rsquo;6&ldquo;) instead of 6&rsquo;6&rdquo;).  If I put a space between the double-quote and the close-bracket I get 6&rsquo;6" ).

I haven't found a way of getting it to render this correctly apart from using two single quotes.

**Comment by jgm** [comment]
>    ... 6'6").
>
>This was rendered as 6&rsquo;6&ldquo;) instead of 6&rsquo;6&rdquo;).

Of course, right curly quotes aren't typographically correct either (http://practicaltypography.com/foot-and-inch-marks.html); what is wanted here is a straight quote.  You can force the straight quotes in a variety of ways, including tex math (`$6'6"$`) and using entities.

**Comment by bpj** [comment]
I'd say this isn't a bug. Ordinary quoted text may legitimately end with a digit and it's questionable whether pandoc should try to ‘guess’ in such cases. It might be hard to come up with a working heuristic/algorithm. Besides one should to be typographically correct use `&#x2032;` PRIME for feet/minutes and `&#x2033;` DOUBLE PRIME for inches/seconds. I realize there might be a font coverage issue though.

**Comment by abudden** [comment]
Okay, I can see that sounds reasonable.  It seems to render ordinary quoted text ending in a digit correctly, so I'll close this bug.
