### ISSUE TITLE
create new point-release for latest change / can't build 1.13.2 on Wheezy

### ISSUE THREAD

**Issue by jniggemann** [jgm/pandoc#2050]
Hi all,

it's impossible to build pandoc since yesterday, at least on Debian stable. This became clear in a [discussion on pandoc-discuss](https://groups.google.com/d/topic/pandoc-discuss/lnMHhp8Z_5k/discussion), where Ivan Miljenovic and I found out that **the version of cabal-install currently available in Debian stable** (Wheezy at the time of writing) **doesn't apply manual version dependency bumps from Hackage, subsequently leading to build errors.**

In this case, the dependencies on blaze-html and blaze-markdown got manually bumped on March, 31, but the tar.gz available from Hackage doesn't reflect these manual bumps.

**Comment by mpickering** [comment]
Why don't you use the old version of cabal install to install a newer version of cabal-install? For example,

```
cabal install cabal-install
```

**Comment by jniggemann** [comment]
My own error has long since been resolved and my own systems are insignificant for this issue anyway.
I opened this isse to raise awareness that manually bumping a version's dependency on Hackage breaks the build for all users of Debian stable that do not use the latest cabal-install, but the one from the Debian stable repos.

I imagine that for lots of users, pandoc is the first (and often only) contact they make with Haskell and as such, lots of them won't know that they need to update to the latest cabal-install before they can successfully build pandoc.

IMHO there are 2 ways to fix this issue:
Either create new point-releases when manually bumping (but then again, there's no need to manually bump), or add "update to cabal-install >= x.x.x to build pandoc from source" to the documentation.

**Comment by jgm** [comment]
I have updated the installation instructions on the website,
and in INSTALL.  I hope this fixes things sufficiently.

**Comment by jniggemann** [comment]
This does not work, steps to reproduce (using a shell provisioning script in vagrant):
* take a up-to-date vanilla Wheezy VM
* `sudo apt-get install haskell-platform`
* `cabal update && cabal install hsb2hs && cabal install cabal-install`
* `/myuser/.cabal/bin/cabal update && /myuser/.cabal/bin/cabal install --flags="embed_data_files" pandoc`

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: pandoc-1.13.2 (user goal)
trying: network-2.6.0.2/installed-b5c... (dependency of pandoc-1.13.2)
trying: scientific-0.3.3.8 (dependency of pandoc-1.13.2)
rejecting: scientific-0.3.3.8:+bytestring-builder (conflict: network =>
bytestring==0.9.2.1/installed-4ad..., scientific-0.3.3.8:bytestring-builder =>
bytestring>=0.10 && <0.11)
rejecting: scientific-0.3.3.8:-bytestring-builder (manual flag can only be
changed explicitly)
Backjump limit reached (change with --max-backjumps).
```

No luck increasing `--max-backjumps`, even when set to 5000 the error persists.

**Comment by jgm** [comment]
This looks like a different problem, not obviously related
to the bumped dependencies.  (Does it make any difference if
you manually replace pandoc.cabal with the modified version
on Hackage?)

+++ Jan [Apr 02 15 11:50 ]:

**Comment by jniggemann** [comment]
I agree, I don't think this has to do with the bumped deps either.
Adding `--reorder-goals` makes the error go away and replaces it with:
```
cabal: The following packages are likely to be broken by the reinstalls:
Cabal-1.22.2.0
regex-posix-0.95.1
regex-compat-0.95.1
Use --force-reinstalls if you want to install anyway.
```

> Does it make any difference if you
>manually replace pandoc.cabal with the modified version on Hackage

I'm not sure I understand, can you please explain / rephrase?

**Comment by ivan-m** [comment]
I think @jgm means to:

* `cabal unpack pandoc`
* `cd pandoc-1.13.2`
* Download the current version of the [cabal file from Hackage](http://hackage.haskell.org/package/pandoc-1.13.2/pandoc.cabal) and save it over the current `pandoc.cabal`.
* `cabal install --flags="embed_data_files" pandoc`

**Comment by jgm** [comment]
I started up a clean VM with a debian wheezy minimal install.

    $ sudo aptitude install haskell-platform
    $ cabal update
    $ cabal install pandoc

So far, so good. It's still compiling things, so I don't
know yet whether it will work, but cabal didn't complain
that there wasn't a viable install path.  And I didn't even
reinstall cabal-install -- I'm using the super-old version
that comes with wheezy's haskell-platform.

So, I'm wondering whether your initial diagnosis -- the
claim that pandoc can't be installed on wheezy with
haskell-platform -- is correct?  Might there be something
else about your setup that is interfering?  (Did you
install anything else prior to pandoc?)

**Comment by jgm** [comment]
+++ John MacFarlane [Apr 02 15 17:06 ]:

>So far, so good. It's still compiling things, so I don't
>know yet whether it will work, but cabal didn't complain
>that there wasn't a viable install path.

OK, it failed at the same point your reported.

One thought:  after you `cabal install cabal-install`, the
new `cabal` executable will be in `~/.cabal/bin`.  So
you should explicitly do

    ~/.cabal/bin/cabal update && ~/.cabal/bin/cabal install

If you just use `cabal` it will still be using the version
in `/usr/bin`.

**Comment by jgm** [comment]
I can confirm that I was able to complete the install using the new cabal.  So, to summarize what worked for me on a clean wheezy machine:

    sudo apt-get update
    sudo apt-get install haskell-platform
    cabal update
    cabal install cabal-install
    export PATH=~/.cabal/bin:$PATH
    cabal update
    cabal install pandoc

**Comment by jgm** [comment]
@jniggemann - I see from your earlier comment that you *did* specify the path to the locally installed `cabal`.  So I'm not sure why it worked for me but not for you.  I didn't use `embed_data_files`, but it's hard to imagine that this made the difference.

**Comment by jniggemann** [comment]
Strange enough the very same set of commands turn out to be unsuccessful on puppetlabs/debian-7.8-32-nocm. I'll try this on some other base images and then report back.

**Comment by jniggemann** [comment]
No luck with another image (chef/debian-7.4-i386) either, the error remains the same.
While this may entirely be attributed to the fact that I'm quite new to vagrant, automated provisioning and all this, I have a strong feeling that there's something else going on.
To be sure, I re-tested on a 64bit machine, too, but with the same outcome...
Any more ideas?

**Comment by jgm** [comment]
I am trying now with chef/debian-7.4-i386, and I got the same error you
did.  It is not really pandoc specific; it has to do with the
'scientific' package, one of pandoc's dependencies.  scientific depends
on bytestring 0.10.*, but the version of unix that comes with ghc
is compiled against an older version of bytestring.

The solution I found is to do:

    ~/.cabal/bin/cabal install unix hsb2hs pandoc -fembed_data_files

Not finished yet, but so far it is working.

I think it might be wise for us to bump the lower bound on unix in
pandoc.cabal.

+++ Jan [Apr 03 15 14:46 ]:

**Comment by jgm** [comment]
Spoke too soon.  That didn't work.  I think we might have better luck
trying to put an upper bound on scientific and aeson, which depends
on scientific.  Will try that next.

**Comment by jgm** [comment]
I note the following in aeson's [changelog](https://github.com/bos/aeson/blob/master/changelog.md):

0.7.1.0

Major compiler and library compatibility changes: we have dropped support for GHC older than 7.4, text older than 1.1, and bytestring older than 0.10.4.0. Supporting the older versions had become increasingly difficult, to the point where it was no longer worth it.

I think it's going to be difficult for pandoc to continue to support GHC 7.4 if aeson doesn't.

The odd thing, though, is that pandoc master continues to build on ghc 7.4.2 on travis:
https://travis-ci.org/jgm/pandoc/jobs/56991786#L3100

**Comment by jniggemann** [comment]
@jgm Thank you for caring and taking the time to analyze this. I don't think that this is too bad, since Debian Jessie is due to be released quite soon, possibly even this month and it'll have a ghc 7.6: https://tracker.debian.org/pkg/ghc

**Comment by jgm** [comment]
+++ Jan [Apr 05 15 08:32 ]:
>@jgm Thank you for caring and taking the time to analyze this. I don't think that this is too bad, since Debian Jessie is due to be released quite soon, possibly even this month and it'll have a ghc 7.6: https://tracker.debian.org/pkg/ghc

OK, then I won't worry much more about it.  I think once this happens,
we can safely forget about GHC 7.4.

**Comment by jniggemann** [comment]
I verified that pandoc can be built on a current version of Debian Jessie using only

```
sudo apt-get update
sudo apt-get install haskell-platform
cabal update
cabal install pandoc
```

**Comment by drufat** [comment]
I also ran into this problem on archlinux. Trying 

    pacman -Syu
    pacman -S ghc cabal-install
    cabal update
    cabal install pandoc

fails with the exact same error described above.

**Comment by jniggemann** [comment]
@drufat Update to a more recent version of ghc, that should solve the issue. I never used arch, but google found https://www.archlinux.org/packages/extra/i686/ghc/

**Comment by drufat** [comment]
@jniggemann  the version of ghc that I am using is version 7.10.1. Is that not recent enough?

**Comment by jniggemann** [comment]
@drufat Sorry, I thought you were using an older version. You ghc and cabal versions are recent enough... Do you really see this:
```
Linking /tmp/pandoc-1.13.2-8861/pandoc-1.13.2/dist/setup/setup ...
Configuring pandoc-1.13.2...
setup: At least the following dependencies are missing:
blaze-html >=0.5 && <0.8 && ==0.8.0.2,
blaze-markup >=0.5.1 && <0.7 && ==0.7.0.2
cabal: Error: some packages failed to install: pandoc-1.13.2 failed during the configure step. The exception was: Exit Failure 1
```

**Comment by drufat** [comment]
@jniggemann The exact error that I am getting is as follows:

    > cabal install pandoc
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    trying: pandoc-1.13.2 (user goal)
    trying: base-4.8.0.0/installed-1b6... (dependency of pandoc-1.13.2)
    next goal: haddock-library (dependency of pandoc-1.13.2)
    rejecting: haddock-library-1.2.0 (conflict: pandoc => haddock-library>=1.1 &&
    <1.2)
    rejecting: haddock-library-1.1.1, 1.1.0 (conflict:
    base==4.8.0.0/installed-1b6..., haddock-library => base>=4.3 && <4.8)
    rejecting: haddock-library-1.0.1, 1.0.0 (conflict: pandoc =>
    haddock-library>=1.1 && <1.2)
    Backjump limit reached (change with --max-backjumps).

**Comment by jniggemann** [comment]
@drufat This is a different error, you're not experiencing the same error I had. Please ask on the google group pandoc-discuss or open a new issue.

**Comment by jgm** [comment]
1.13.2 won't build with ghc 7.10.1.

The development version (master on github) will build:

    git clone https://github.com/jgm/pandoc
    cd pandoc
    git submodule update --init
    cabal update
    cabal install

Note, however, that master has some bugs which need to be fixed
before a new release.  If we can't fix these relatively quickly,
we will consider creating a point release that at least allows
things to build.
