### ISSUE TITLE
Document correspondance between pandoc command line options and YAML metadata fields

### ISSUE THREAD

**Issue by eliemichel** [jgm/pandoc#2052]
I couldn't find more information about `yaml_metadata_block` than the one in http://pandoc.org/README.html

More specifically, is there a way to set all `pandoc` command line options though YAML metadata? Such that `--latex-engine=xelatex` or `--number-sections`?

**Comment by jgm** [comment]
+++ Elie Michel [Apr 05 15 00:41 ]:
>I couldn't find more information about `yaml_metadata_block` than the one in http://pandoc.org/README.html
>
>More specifically, is there a way to set all `pandoc` command line options though YAML metadata? Such that `--latex-engine=xelatex` or `--number-sections`?

No.  YAML metadata just affects metadata, and these options don't set metadata.
