### ISSUE TITLE
More editors

### ISSUE THREAD

**Issue by fulldecent** [jgm/pandoc#2058]
Are there any other editors using pandoc that work like Texts but are free?

**Comment by jgm** [comment]
You should ask this question on the pandoc-discuss mailing list, where I'm sure people will answer it.  This tracker is for bug reports and enhancement requests, and is watched by many fewer people.

**Comment by lierdakil** [comment]
Not that I'm aware of. There is [a thread in pandoc-discuss](https://groups.google.com/forum/#!topic/pandoc-discuss/WTq_L2RSHDk), that talks about something like that, but so far we haven't seen the code or anything.

There are decent free (as in freedom) Markdown editors with no direct Pandoc integration though. And then there's [UberWriter](http://uberwriter.wolfvollprecht.de/), which uses pandoc, but is a little wierd IMO, and is kind of Ubuntu-specific.

Asking on pandoc-discuss can get you more answers. Or you could consult [AlternativeTo](http://alternativeto.net/software/texts/?license=free).

**Comment by fulldecent** [comment]
Excellent, thank you, discussing there
