### ISSUE TITLE
Please make a release with new dependencies

### ISSUE THREAD

**Issue by k-bx** [jgm/pandoc#2060]
I'm specifically waiting for uppering filepath to `<1.5` instead of `<1.4`. Thank you!

**Comment by k-bx** [comment]
By release, I mean hackage release

**Comment by jgm** [comment]
We're working on a new release, but some bugs need to be fixed first.
In the mean time, I've bumped the version bound for filepath on Hackage
for pandoc 1.13.2.

+++ Kostiantyn Rybnikov [Apr 09 15 01:14 ]:

**Comment by k-bx** [comment]
Thanks!
