### ISSUE TITLE
Included PDFs are not visible in DOCX output

### ISSUE THREAD

**Issue by claczny** [jgm/pandoc#2061]
Hi,

first of all, let me thank you for this great tool!

I am writing a manuscript mostly in MarkDown, augmented with some LaTeX code. As part of this, I use the `pdfpages` package to include some PDFs into the manuscript. This works great for `.tex` and `.pdf`output but sadly *not* for `.docx` output.

Is there any special option that has to be passed to pandoc in order to embed the PDF pages also into the `.docx` output? Even an implicit conversion to a series of images representing the individual pages would be fine with me.

Looking forward to your clarification.

Best,

Cedric

**Comment by jgm** [comment]
Pandoc's latex parser only handles standard latex + a few common
packages, so not pdfpages.

When you're targeting tex or pdf, the pdfpages commands are just passed
through verbatim -- that's why it works in those formats.

We could manage inclusion of whole PDFs (for which you could also just
use `\includegraphics`.  But there's no hope of handling `\includepdf`
with all its options (page ranges etc.) -- that would require embedding
a lot of PDF processing capability into pandoc.

**Comment by claczny** [comment]
Thanks for your quick and informative reply.

I tried to use `\includegraphics` but in its 'vanilla' form it only displays the first page of mutipage PDFs. Also, it was not well aligned on the page, as opposed to using `\includepdf` which displays really nicely.

I tried two alternatives basically involving loops (http://www.latex-community.org/forum/viewtopic.php?f=5&t=2185 and http://tex.stackexchange.com/questions/91440/how-to-include-multiple-pages-in-latex) to display multiple pages with `\includegraphics` but they did not work for me either. Probably that is because of the same reason as you highlighted, i.e., a lot of PDF processing would be required.

Probably not, but I am still asking for completeness: Is there another format that could actually make use of the included multipage PDF? Or is there an alternative approach that you could suggest to this problem?

Thanks again for your clarifications.

Best,

Cedric

**Comment by timtylin** [comment]
an alternative that might work: use a separate latex document in `standalone` documentclass to generate the `\includepdf` output as a single pdf image, then include that with `\includegraphics` in your main document.

**Comment by lierdakil** [comment]
Sadly, LaTeX support in pandoc is very limited. If you're somewhat familiar
with haskell/perl/python/php/nodejs, you can probably write a filter to
achieve desired behavior. If not, converting your pdf to series of images
and using \includegraphics for every page is a painful, but viable option
(filter could do this automatically)

2015-04-10 9:00 GMT+03:00 Tim T.Y. Lin <notifications@github.com>:

**Comment by timtylin** [comment]
> If not, converting your pdf to series of images and using \includegraphics for every page is a painful, but viable option

I actually think it's pretty cool that postscript can compose like this!

You don't even need a filter though, if you're already using a build script. Just pre-compile the standalone PDF and include that as image. In fact, this kind of refactoring probably leads to a cleaner build.

**Comment by claczny** [comment]
@timtylin Would that also work for multipage PDFs? As far as I understood, `\includegraphics` always  displays one image at a time. One would then need some kind of loop. My first attempts using a loop did not work though, which may be simply because I did something wrong. But the outputs were created and no errors were thrown.

**Comment by tolot27** [comment]
As far as I know, there is no way to include native PDF in docx, neither manually nor via pandoc. You can only convert it to images and include these.

**Comment by mb21** [comment]
To convert the PDF you can e.g. do the following:

``` sh
brew install imagemagick
convert -units PixelsPerInch -density 600 fig.pdf fig.png
```
