### ISSUE TITLE
EPS mistaken for TGA image

### ISSUE THREAD

**Issue by Huulivoide** [jgm/pandoc#2067]
For some reason Pandoc detects the linked eps file as tga file
and complains about invallid tga data, thus failing to compile the
document.

Files: [test.pan][1], [eps-mistaken-for-tga.eps][2]
Command: pandoc -o test.pdf test.pan

Expected result: pdf file with a image in it
Actual result: Pandoc fails with error message "pandoc: No data detected in TGA file"

[1]: https://www.dropbox.com/s/i2rlc7xyisxq331/eps-test.pan?dl=0
[2]: https://www.dropbox.com/s/1hr8ws2ilfqvzpc/eps-mistaken-for-tga.eps?dl=0

**Comment by nkalvi** [comment]
I may be wrong, but it looks like Pandoc will try to convert embedded images to png if they are not jpg, png or pdf. The error seems to be coming from the library (JuicyPixels) used for conversion - TGA was the last format it tried to interpret the file as. With some other eps files I got the following message:
```
Cannot load file
Jpeg Invalid marker used
PNG Invalid PNG file, signature broken
Bitmap Invalid Bitmap magic identifier
GIF Invalid Gif signature : %!PS-A
HDR Invalid radiance file signature
Tiff Invalid endian tag value
TGA demandInput: not enough bytes
```

I'm not sure whether converting these eps files to png or even pdf (using f.ex. epstopdf) is a feasible alternative in your case. 

LaTex & Pandoc experts may be able suggest more alternatives.

**Comment by Huulivoide** [comment]
I have used a dozen of esp files and after failing the conversion pandoc just simply
passes them on directly with the 'Cannot load file....' message, but everything works
and I have beautiful graphics that scale well and my documents stay ridiculously small
in file size, despite being heavy on the graphics.

I had to include this particular file in my document with direct LaTeX commands.
Not a big deal, but this bug is really most intriguing, what exactly makes the image
library think this is a TGA image.

**Comment by mpickering** [comment]
Is the error exactly as nkalvi suggests?

**Comment by nkalvi** [comment]
https://github.com/Twinside/Juicy.Pixels/blob/master/src/Codec/Picture.hs
```
-- | If you want to decode an image in a bytestring without even thinking
-- in term of format or whatever, this is the function to use. It will try
-- to decode in each known format and if one decoding succeeds, it will return
-- the decoded image in it's own colorspace.
decodeImage :: B.ByteString -> Either String DynamicImage
decodeImage str = eitherLoad str [("Jpeg", decodeJpeg)
                                 ,("PNG", decodePng)
                                 ,("Bitmap", decodeBitmap)
                                 ,("GIF", decodeGif)
                                 ,("HDR", decodeHDR)
                                 ,("Tiff", decodeTiff)
                                 ,("TGA", decodeTga)
                                 ]
```

https://github.com/Twinside/Juicy.Pixels/blob/master/src/Codec/Picture/Tga.hs
```
  case imageType of
    ImageTypeNoData _ -> fail "No data detected in TGA file"
```
if you have time :smile:

**Comment by Huulivoide** [comment]
@mpickering:
With this particular file the error is "pandoc: No data detected in TGA file".
But with all other of my esps pandoc warns about not being able to
load the file, with an error message like in @nkalvi's first post.

**Comment by jgm** [comment]
@nkalvi has the correct diagnosis of what is happening and why.
I think the best solution is to change the error message so it's less misleading.  I'm working on that now.

**Comment by jiucenglou** [comment]
Pandoc v2.1.3 still produces the warnings when .eps graphics is used. The .pdf generated works fine though.

```
[WARNING] Could not convert image '.\tex2pdf.8984/1584dee44acc53dcdff0a35199b4ba7a7aae4c17.ps': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : %!PS-A
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
```

**Comment by jgm** [comment]
Hm, EPS should work.  Can you upload the image file
so we can test?

**Comment by mb21** [comment]
@jlmuir `.ps` is PostScript, convert it to `.eps` (encapsulated postscript) first.

**Comment by jiucenglou** [comment]
Sample files are zipped and attached as mega link https://mega.nz/#!UlQ1QSpa!4kgE2l5dLUSsXjhJnPmzud8nHx0PHjz3qviQHB5Edsg because I could not upload it with GitHub... Could you help to check ? Many thanks !

The command to run is "mp MWE.md" with the following shell function definition.
```
mp ()
{
    mdname=$1;
    mdname=$(basename "$mdname");
    name_noext="${mdname%.*}";
    docx_name="${name_noext}.docx";
    tex_name="${name_noext}.tex";
    pdf_name="${name_noext}.pdf";
    pandoc ${mdname} --mathml --filter=pandoc-crossref --filter=pandoc-citeproc -s -o ${docx_name};
    pandoc ${mdname} --mathml --filter=pandoc-crossref --filter=pandoc-citeproc -s -o ${tex_name} --pdf-engine=xelatex;
    pandoc ${mdname} --mathml --filter=pandoc-crossref --filter=pandoc-citeproc -s -o ${pdf_name} --pdf-engine=xelatex
}

```

**Comment by jgm** [comment]
I see what is happening here.  Pandoc is assigning the
mime type application/postscript, and then assigning
the ps extension based on that mime type.

We can fix this by using the alias application/eps for
eps files.

**Comment by jgm** [comment]
OK, I've fixed the issue.

**Comment by jiucenglou** [comment]
Thanks for your efforts ! I will test when the new version containing the fix is released.
