### ISSUE TITLE
Feature request: Fetch bibliography files from URI

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#2073]
At least for input files and CSL style files, absolute URIs may be given instead of file names, to let pandoc fetch the content from a server. This does not seem to be implemented for bibliography database files (.bib, .json, .yaml, .mods, …) yet, but maybe it could be added?

**Comment by timtylin** [comment]
It's technically quite easy to do, and I've been looking into it. There's two non-trivial missing pieces though:

1. We need to decide on a suitable caching strategy (or more specifically, a cache invalidation strategy) for fetched resources, and where to put them. Alternatively, there could be zero caching and the resources would be fetched every time the conversion is called. Is that acceptable? Some bib databases could get *quite big*. I couldn't decide on a absolutely winning approach yet.

2. Currently `citeproc` determines the database format by looking at the file extension. However, URIs don't necessarily have a file extension, so some alternative method needs to be devised to determine the database format.

**Comment by nickbart1980** [comment]
Thank you. Valid points. As to 2., I’d yet have to come across a remote biblio database file that does not have the proper extension, so I’d tend to see this as less of a problem. As to 1., for me personally, zero caching would be acceptable, but there might of course be other use cases. But then again, remote input files aren’t cached either, AFAIK.

**Comment by mb21** [comment]
I guess this should go to https://github.com/jgm/pandoc-citeproc ?
