### ISSUE TITLE
Handling of image filenames that contain dots

### ISSUE THREAD

**Issue by phreeza** [jgm/pandoc#2074]
When generating a pdf, trying to include an image file that contains dots which are not file extension separators (eg raster_190.09.png) fails with LaTeX complaining of an unknown file extension.

When writing latex, this can be avoided by placing the filename without the extension in curly brackets like so: {raster_190.09}.png which does not work from pandoc because the {} get escaped.

The simplest solution to this would be to always wrap the filenames in unescaped brackets, I think there is no case where this does any harm.

**Comment by jgm** [comment]
+++ Thomas McColgan [Apr 12 15 04:00 ]:

>The simplest solution to this would be to always wrap the filenames in unescaped brackets, I think there is no case where this does any harm.

Great idea, I'll do that.

**Comment by jgm** [comment]
On second look, I think a better solution may be just adding

    \include{grffile}

to the default template.

**Comment by phreeza** [comment]
Ah I did not know about that package, fantastic! Seems to work, I agree that is an even nicer solution.

**Comment by jgm** [comment]
@phreeza I tried what you suggest above and [it didn't seem to work](https://github.com/jgm/pandoc/issues/5848#issuecomment-547205395). Have I misunderstood?

**Comment by jgm** [comment]
Ah, see https://github.com/ho-tex/oberdiek/issues/73#issuecomment-539059311
This may be due to a recent change in the latex kernel
