### ISSUE TITLE
Documentation: external YAML files for citations not documented as supported

### ISSUE THREAD

**Issue by david-antliff-imgtec** [jgm/pandoc#2076]
As verified in #1960, external YAML files are supported via both the --bibliography option and via inline YAML "bibliography: " when --filter pandoc-citeproc is specified, provided the YAML file is correctly formatted, however this is not documented as a supported format at http://johnmacfarlane.net/pandoc/README.html in the citations extension section.

**Comment by nickbart1980** [comment]
Pull request created: https://github.com/jgm/pandoc/pull/2078.
I’d also suggest replacing `biblio.bib` in the second and third examples of http://johnmacfarlane.net/pandoc/demos.html, “24. Markdown citations” by `biblio.json` and `biblio.yaml` and adding these files, so users can see examples of these file formats.
Also, for consistency I think that CSL YAML files used as biblio files (as opposed to being used as input files, but then these would be text files with a metadata section anyway) should not be required to start with `references`, see https://github.com/jgm/pandoc-citeproc/issues/124.

**Comment by jgm** [comment]
+++ nickbart1980 [Apr 13 15 03:49 ]:
>I’d also suggest replacing `biblio.bib` in the second and third examples of http://johnmacfarlane.net/pandoc/demos.html, “24. Markdown citations” by `biblio.json` and `biblio.yaml` and adding these files, so users can see examples of these file formats.

I'll do this.
