### ISSUE TITLE
SPARing with PanDoc

### ISSUE THREAD

**Issue by HughP** [jgm/pandoc#2084]
I noticed the issue about TEI #2047 and the excitement towards some of the semantic features of TEI.
I am wondering if anyone in the pandoc community has played around with [SPAR](http://sempublishing.sourceforge.net/). It is a semantic ontology for describing publications (including academic publications). I would be most interested in knowing if anyone has done any work on bibliography citations; perhaps pandoc --> FaBiO.

**Comment by jgm** [comment]
Better to ask questions like this on pandoc-discuss -- this tracker is for specific bug reports and enhancement requests.  You'll get more response on pandoc-discuss, so I'm closing this here.
