### ISSUE TITLE
Code and div

### ISSUE THREAD

**Issue by r-gaia-cs** [jgm/pandoc#2085]
I notice a change at the output to HTML for code blocks
from version 1.13.1 to 1.14:

    $ pandoc-1.13.1 <<EOF
    ~~~{.python}      
    foo
    ~~~
    EOF
    <pre class="sourceCode python"><code class="sourceCode python">foo</code></pre>
    $ pandoc-1.14 <<EOF       
    ~~~{.python}      
    foo               
    ~~~
    EOF
    <div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">foo</code></pre></div>

First, I want to check that this change is by design and not a bug.

Second, I would like to know why the `div` only has `sourceCode` as class.

**Comment by lierdakil** [comment]
See https://github.com/jgm/highlighting-kate/pull/65 for background.

**Comment by r-gaia-cs** [comment]
@lierdakil Thanks for the info.
