### ISSUE TITLE
Fix escaping of special chars in markdown writer

### ISSUE THREAD

**Issue by mike-ward** [jgm/pandoc#2086]
I use pandoc to reformat markdown files so they are wrapped and formatted.

Autolinks like:

    <{{site.data.members.coach-email}}>

when processed with

    pandoc -f markdown_strict -t markdown_strict -o test.md test.md

result in

    \<{{site.data.members.coach-email}}\>

Later when I reformat the file again with the same command, I get

    \\\<{{site.data.members.coach-email}}\>

Pandoc continues to add `\\` each time I run it on the reformatted file.

**Comment by jgm** [comment]
+++ Mike Ward [Apr 15 15 07:01 ]:
>I use pandoc to reformat markdown files so they are wrapped and formatted.
>
>Autolinks like:
>
>    <{{site.data.members.coach-email}}>

That's not parsed as an autolink, because the contents are not an
absolute URL or email address.  Presumably this is a template.  Pandoc
can't be expected to guess that the template variable will be filled
with an absolute URL or email address.

So, I don't see a bug here.

**Comment by mike-ward** [comment]
Why does it put a backslash in front of the pointy brackets then? If it doesn't recognize the structure, shouldn't it just leave it alone?

**Comment by jgm** [comment]
+++ Mike Ward [Apr 15 15 09:06 ]:
>Why does it put a backslash in front of the pointy brackets then? If it doesn't recognize the structure, shouldn't it just leave it alone?

Because `<` is a special character in Markdown, so it needs to be escaped.

Otherwise you could get weird results.  For example, suppose you're
converting the following HTML to Markdown:

    &lt;a&gt;

This first gets converted internally to a string inline in pandoc:

    Str "<a>"

and when this is written out to Markdown, we need to escape the `<` or we'll get an HTML tag rather than the literal string `<a>`, which is what was wanted.

    \<a\>

**Comment by mike-ward** [comment]
If I were converting from HTML to Markdown, I would agree with this. 

I suspect the part of Pandoc that is producing Markdown does not know the source was Markdown. That's how I would write it. It would also explain why running the output back through Pandoc continues to add backslashes. 

I'm not trying to be snarky here. I really like Pandoc. And frankly, the problem is easy enough for me to avoid by using the `[title](link)` syntax. I was just perplexed by all the backslashes showing up in the output.

Thanks for attention in this matter.

**Comment by lierdakil** [comment]
That's interesting.

```
echo '<{{site.data.members.coach-email}}>' | pandoc -f markdown_strict -t markdown_strict |  pandoc -f markdown_strict -t markdown_strict
```

gets me 

```
\\\<{{site.data.members.coach-email}}\>
```

And

```
echo '<{{site.data.members.coach-email}}>' | pandoc -f markdown -t markdown_strict |  pandoc -f markdown -t markdown_strict
```

only

```
\<{{site.data.members.coach-email}}\>
```

Seems like `markdown_strict` parses `\<` verbatim, not as escaped `<`. There might be a genuine bug here.

**Comment by lierdakil** [comment]
Yes, yes it does:
```
echo '\<' | pandoc -f markdown_strict -t native
[Para [Str "\\<"]]
            ^^^
```
Not sure about Markdown grammar details, but either reader should read `\<` as escaped character, or writer should not escape `<` in its output.

**Comment by jgm** [comment]
+++ Mike Ward [Apr 15 15 09:36 ]:
>   If I were converting from HTML to Markdown, I would agree with this.
>
>   I suspect the part of Pandoc that is producing Markdown does not know
>   the source was Markdown. That's how I would write it.

Even if it knew the source was Markdown, the escapes would
still be needed.  Remember, everything goes through an
intermediate representation of the document.  And a `Str "<"`
could have come from Markdown `<` or from `\<`.  The writer
sees only the parsed content, not the original source.

**Comment by jgm** [comment]
+++ Nikolay Yakimov [Apr 15 15 09:48 ]:
>   Yes, yes it does:
>echo '\<' | pandoc -f markdown_strict -t native
>[Para [Str "\\<"]]
>            ^^^
>
>   Not sure about Markdown grammar details, but either reader should read
>   \< as escaped character, or writer should not escape < in its output.

markdown_strict is an odd case.  It follows Gruber's syntax
description (and Markdown.pl), which does not allow `<` to
be backslash-escaped!  Instead, it requires using an entity
if you want to type a literal `<`.

So, the reader is correct.  The writer, though, should
be changed to escape only the characters Gruber specifies
when the `all_symbols_escapable` extension is not turned
on (and, in this case, `&lt;` should be used for a literal
`<`.)

**Comment by donkndetphone** [comment]
I'am experiencing a similar very issue using `pandoc 2.2.3.2 `

both
`echo 'UNDER_SCORE' | pandoc -f markdown -t markdown`
and
`echo 'UNDER\_SCORE' | pandoc -f markdown -t markdown`

lead to the same result:
`UNDER\_SCORE `

the `all_symbols_escapable` extension doesn't change that, if I enable it for reader only, writer only or for both, I always get the backslash in front of the underscore.

**Comment by jgm** [comment]
@donkndetphone see #6296 which is fixed in master

**Comment by AlmogBaku** [comment]
lua filter for that

```lua
-- fix a problem with <> in codeblocks
function CodeBlock(block)
  block.text = block.text:gsub("<", "&lt;")
  block.text = block.text:gsub(">", "&gt;")
  return block
end

```
