### ISSUE TITLE
the docs for definition lists is not clear about the required indentation

### ISSUE THREAD

**Issue by imz** [jgm/pandoc#2087]
I read <http://pandoc.org/README.html#definition-lists> and didn't understand that the first letter of the definition must be at position 5, so that there are three spaces and a single `:` (or `~`) somehow distributed in the first 4 position in the line.

I've just figured this out experimentally.

If this is an intended feature, I suggest to write about it in the documentation.

This won't work (unexpectedly!):

    term 1
    : definition
    
    term 2
     : defintion
    
    term 3
    :  definition

**Comment by jgm** [comment]
I checked how PHP Markdown Extra does this, and in fact it doesn't require the indentation of the first line.  So I'm going to just drop this requirement.
