### ISSUE TITLE
Surprisingly, line endings vary by OS..

### ISSUE THREAD

**Issue by pombreda** [jgm/pandoc#2097]
When I run Pandoc on the same text on Linux and Windows, the Windows output will have CR/LF and the Linux one will have LF line endings. This is rather annoying, I would expect either to:
- always have an LF output on all OS, 
- be able to select and force a line ending with a command line option,
- have the original line ending of the input file preserved and not damaged to CRLF.

**Comment by jgm** [comment]
I expect that many Windows users prefer the current behavior.  But it would be interesting to find out.  I suggest that you raise this as a discussion item on pandoc-discuss, and once you get some feedback there, it may be appropriate to move to a more determinate suggestion on this tracker.

It would also be helpful to know what version of pandoc you are using, and what ouput format(s) you are noticing this in.

**Comment by pombreda** [comment]
@jgm I will post on the list... being a multi-OS developer, anything that *changes* the line endings of an input file is a source of annoyance. But the thing that is the most annoying is to have a behavior that varies on each OS... giving inconsistent results. I use the prebuilt binaries you provide for 1.13.2 . Most of the conversions are from _anything_ to plain . I use pandoc to decruft any markup to plain text.

**Comment by erichiller** [comment]
@pombreda it took me ages to figures the simplest of things -- line endings. I am in agreement with you, it would be nice to have the ability to have uniformity in line endings across systems. I am currently running everything through `dos2unix` but I wish that wasn't required.

**Comment by legends2k** [comment]
I agree that allowing the user to override the default EOL character would be a useful option.

**Comment by tajmone** [comment]
I've made a formal feature request: #3663.

**Comment by tajmone** [comment]
I have a question:

I'm writing a custom tool to normalize all EOLs to `LF`. It will convert all `CRLF` occurences to `LF`. I've also implemented conversion of `CR` to  `LF`, to be on the safe line (`CR` is often mentioned as Mac-style EOL) — but if this last operation is not needed I could omit it and gain some speed in my toolchain.

Are there any real chances that in some OSs' pandoc will use `CR` as EOL character? (I'm not aware of all the  OSs' pandoc runs in)

**Comment by jgm** [comment]
+++ Tristano Ajmone [May 14 17 02:27 ]:
>   I have a question:
>
>   I'm writing a custom tool to normalize all EOLs to LF. It will convert
>   all CRLF occurences to LF. I've also implemented conversion of CR to
>   LF, to be on the safe line (CR is often mentioned as Mac-style EOL) —
>   but if this last operation is not needed I could omit it and gain some
>   speed in my toolchain.
>
>   Are there any real chances that in some OSs' pandoc will use CR as EOL
>   character? (I'm not aware of all the OSs' pandoc runs in)

It won't do this on any OS that pandoc runs in, as far as
I'm aware.

**Comment by pombredanne** [comment]
it is unlikely to happen these days... MacOS 9.x-only text files are something that I never in many years

**Comment by Drezil** [comment]
I implemented a flag to force the line-endings in output in a PR:
https://github.com/jgm/pandoc/pull/3680
