### ISSUE TITLE
Bug in 1.13. breaking backwards compatibility by new definition list format

### ISSUE THREAD

**Issue by bwl21** [jgm/pandoc#2098]
According to the discussion in https://groups.google.com/forum/#!msg/pandoc-discuss/WHVf8CmLEX0/dOsx2AsGRQsJ

It seems to me that there is a bug here, introduced by the
switch to the new definition list format (and not mitigated
by the compact_definition_lists extension). Simpler example:

```
hi
:    - there
```

should give you the same result as

```
hi

:   - there
```

I hereby confirm that with pandoc 1.11 the result is the same, while with 1.13 it is not. The first bullet list gets broken in 1.13.2

`pandoc_1.13.2 x.md -o x_out_1.13.2.md` yields

```
hi
:   - there

should give you the same result as

hi

:   -   there



```

**Comment by jgm** [comment]
To see the real problem, you need to convert to HTML.  In the
first case, the body is not being parsed as a list. This is related
to your earlier case, in which a sublist inside a definition was
not being parsed as a list.

The difference in spacing is something we would expect, given
the documented changes in definition list behavior.

+++ Bernhard Weichel [Apr 20 15 08:29 ]:

**Comment by bwl21** [comment]
The problem also occurs when converting to HTML.

output of 1.13.2
```html
<dl>
<dt>hi</dt>
<dd>- there
</dd>
</dl>
<p>should give you the same result as</p>
<dl>
<dt>hi</dt>
<dd><ul>
<li>there</li>
</ul>
</dd>
</dl>
```

output of 1.11

```html
<dl>
<dt>hi</dt>
<dd><ul>
<li>there</li>
</ul>
</dd>
</dl>
<p>should give you the same result as</p>
<dl>
<dt>hi</dt>
<dd><ul>
<li>there</li>
</ul>
</dd>
</dl>

```
