### ISSUE TITLE
Producing output with the style Stanford Encyclopedia of Philosophy

### ISSUE THREAD

**Issue by ehud** [jgm/pandoc#21]
Hi John,

The SEP has a set of requirements about the HTML formatting of entries. I am not sure how much work it would take to format HTML output from pandoc to suit this style (seems it should be minimal). Still, it would be nice to know if someone already went this route, and what's involved. 

Cheers
Ehud

**Comment by spinstein** [comment]
@ehud Any choice you had got this job done? Thank you!
