### ISSUE TITLE
ConTeXt writer: \starttable is deprecated

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#2102]
Note that the `\starttable` command is deprecated:

http://wiki.contextgarden.net/Tables_Overview

The preferred way of typesetting tables is to use "natural tables":
- http://wiki.contextgarden.net/TABLE
- http://www.pragma-ade.com/general/manuals/enattab.pdf

**Comment by ousia** [comment]
I would say that extreme tables (http://www.pragma-ade.com/general/manuals/xtables-mkiv.pdf) are a better option.

Their syntax is easier and clearer to implement, I would say.

**Comment by DaveJarvis** [comment]
Agreed. The documentation for xtables notes, "it is some two times faster than the natural tables mechanism, and in most cases can be used instead."

**Comment by adunning** [comment]
Duplicate of #1100.

**Comment by jgm** [comment]
Closing #1100 in favor of this.
From #1100:

> Recently [discussed](http://www.ntg.nl/pipermail/ntg-context/2013/075905.html) in ConTeXt mailing list if Pandoc could pass tables from markdown to ConTeXt using Natural tables, aka [TABLE](http://wiki.contextgarden.net/TABLE).

> This way could easy the use of t-filter module developed by Aditya [https://github.com/adityam/] and avoid long long lines in tables.
