### ISSUE TITLE
Support AccesSlide for HTML presentations

### ISSUE THREAD

**Issue by ldidry** [jgm/pandoc#2107]
AccessSlide is quite like Reveal.js, but its target is _accessible_ slideshows, for disabled people.

Accessibility is often forgotten, and having pandoc handling such a tool would be a great help for making the web a better place for disabled people.

Code: https://github.com/access42/AccesSlide  
Demo: http://accesslide.net/

**Comment by jgm** [comment]
It looks as if the actual HTML layout is the same as for reveal.js.
Have you tried `pandoc -t revealjs --template (your custom access slide template here)`?

**Comment by jgm** [comment]
I suspect the above will work, so I'm closing this.
If I'm wrong, feel free to reopen.
