### ISSUE TITLE
man writer does not respect <br> tag.

### ISSUE THREAD

**Issue by weakish** [jgm/pandoc#2109]
Given this markdown input:

```markdown
foo<br>
bar
```

Output:

```
foo bar
```

Expected:

```
foo
.PD 0
.P
.PD
bar
```

pandoc 1.12.2.1

**Comment by nkalvi** [comment]
Could you try with just a `\` at the end of the line instead of `<br>`? 
It will then treated as a *linebreak* and give the desired output.

**Comment by weakish** [comment]
> Could you try with just a \ at the end of the line instead of <br>? 

@nkalvi  Both `\` + `\n`  and two or more spaces will produces linebreaks.

But html writer respects `<br>`, so I think man writer should also respect it.

**Comment by nkalvi** [comment]
If the input is treated as markdown, then HTML is parsed (processing and passing thorough as raw when appropriate) not rendered. Your example will work as expected by adding -f HTML.

**Comment by nkalvi** [comment]
I think I misunderstood your comment - you didn't mean it should be interpreted by the *markdown reader*, but passed through and rendered by the *man writer*. You may already know the following:

>The raw HTML is passed through unchanged in HTML, S5, Slidy, Slideous, DZSlides, EPUB, Markdown, and Textile output, and suppressed in other formats.

I'm not sure of merits/demerits of enabling the *man writer* to interpret HTML.

**Comment by jgm** [comment]
As @nkalvi says, raw HTML is only passed through to HTML-based formats.  So, this isn't a bug.
