### ISSUE TITLE
External listings

### ISSUE THREAD

**Issue by KOLANICH** [jgm/pandoc#2116]
Allow external listings in latex, for example

``` latex
\lstinputlisting{"file.js"}
```

pandoc should open the files and read their contents, if the target format doesn't support linking or if external listings are not enabled and then process as usual listing. If it supports, it should link existing files, if corresponding CLI argument is set.
In the case of HTML it is possible to highlight using JS.

**Comment by bpj** [comment]
If you are only targeting LaTeX you can simply use the LaTeX command in
your markdown document.

If you are targeting multiple formats it shouldn't be too difficult to
write a filter which takes a codeblock with a 'flag' class and the path to
a file as text and replaces the text with the contents of the file at that
path:

````````markdown
````{.include}
path/to/some.JSON
````
````````
Den 26 apr 2015 21:34 skrev "KOLANICH" <notifications@github.com>:

**Comment by bbolker** [comment]
+1 ...

**Comment by Qinka** [comment]
+1

**Comment by jgm** [comment]
We'll be able to handle this kind of thing better with architectural changes now under way in the typeclass branch (pandoc 2.0).

**Comment by Paladnix** [comment]
How to use the feature in my markdown syntax if I want pandoc to render code from file.
