### ISSUE TITLE
LaTex reader: Parse error with macros that require parameters when expanded

### ISSUE THREAD

**Issue by nkalvi** [jgm/pandoc#2118]
In Pandoc's LaTex reader, a macro which expands to something that requires parameter(s), is expected to be defined with the required parameters. Failure to do so will result in parse error. LaTex doesn't seem to have this requirement. 

Example:

``` latex
\documentclass{article}
\usepackage{graphicx} 
\begin{document}
\thispagestyle{empty}
% Following will work fine in LaTex, but will fail with parse error in Pandoc 
% since a parameter is expected (msg: unexpected "}" expecting "[", "{", "\\", "=" or digit)
\newcommand{\inclgraph}{\includegraphics[width=0.8\textwidth]}
\begin{figure}[ht]
  \centering
  \inclgraph{setminus.png}
  \caption{Set subtraction}
  \label{fig:setminus}
\end{figure}
\end{document}
```

While parsing, `\inclgraph` is expanded to `{\\includegraphics[width=0.8]}` first.
Then when `{\includegraphics[width=0.8]}` is parsed, it expects a parameter before `}`.

**Comment by lierdakil** [comment]
Probably related to #1390

**Comment by nkalvi** [comment]
Yes it does look like it.
Since #1390 is 'major' issue, why not specify it as a requirement for Pandoc's LaTex macro handling until a solution is found (though it'll be a slight deviation from LaTex's macro expansion)?
