### ISSUE TITLE
Beamer: Allow marking some slides as fragile

### ISSUE THREAD

**Issue by guiniol** [jgm/pandoc#2119]
Hello,

I hope this isn't a duplicate, but following #385, it would be nice if we could specify some slides as [fragile]. In particular, slides using the minted environment need fragile slides, so that it currently cannot be used inside markdown files.

I tried using a filter, but AFACT filters are applied on the AST so that I cannot modify the tex output directly.

Is there a quick workaround that I might have missed? Even if it's a compile flag to make every slide fragile.

Cheers,

-- 
Guillaume

**Comment by guiniol** [comment]
Thanks a lot!

**Comment by forflo** [comment]
As a workaround, you could use the following hack:


`# fooslide`
`## foo subtitle`
` ``` `
` ``` `
`- foo`
`- bar`
`begin{tabular} ... \end{tabular}`

This works because whenever you include a ` ``` `-Block under a `#`-tag, pandoc generates a `\begin{frame}[fragile]` instead of the regular `\begin{frame}`

**Comment by mb21** [comment]
@forflo you don't need a workaround any more:

    # Fragile slide {.fragile}
