### ISSUE TITLE
html reader - markdown writer <br> conversion

### ISSUE THREAD

**Issue by apaeffgen** [jgm/pandoc#2126]
Converting in pandoc 1.13.2 on MacOS 10.9.5 a simple html file with only a  linebreak-tag produces a visible charter: \

It does not matter, if this is a valid or not valid html. An attached source html is just for testing purposes:

![bildschirmabgriff_01](https://cloud.githubusercontent.com/assets/426561/7444611/a0727032-f18b-11e4-87bf-dec386f6686b.png)

**Comment by apaeffgen** [comment]
Writing the linebreak-tag with a / or without does not matter. The shown html is just a backwards conversion from pandoc. Just writing a simple line break-tag shows the above behavior

**Comment by nkalvi** [comment]
@apaeffgen Pardon me if I misunderstood, but isn't it the expected output in this?
```
echo '<br>' | pandoc -f html -t markdown
\
```

http://pandoc.org/README.html#paragraphs
>A backslash followed by a newline is also a hard line break.

**Comment by lierdakil** [comment]
Try `-f/-t markdown_strict/markdown_github`. Pandoc Markdown uses `\` as a hard linebreak character, as @nkalvi pointed out. You can also selectively disable this extension by using `-f/-t markdown-escaped_line_breaks`

**Comment by apaeffgen** [comment]
-w markdown_strict
All your above comments are right. Yes, i did not look carefully. My mistake.
