### ISSUE TITLE
Docx writer: Block quotation not indicated in footnote

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2128]
Block quotations within footnotes work in HTML, LaTeX, etc., but are not preserved when writing to a .docx file.

Example (using Pandoc 1.13.2.1):

``` shell
$ pandoc -o foot.docx << EOT
Footnoted text.[^1]

[^1]: Footnote.

    > Quotation inside footnote.
EOT
```

In the resulting file, the 'Footnote Text' style is applied to the block quotation. I can manually apply the 'Block Quote' style to the paragraph in Word.

**Comment by lierdakil** [comment]
Word's style model is quite restrictive, so we can't have something styled as *both* footnote and blockquote. It should be possible to force "inner" style to take precedence, but I'm not really sure it's a brilliant idea, since basically footnotes usually have smaller text, and that would be ignored by "inner" style.
Another option would be to add a bunch of additional custom styles, like "Block Quote in Footnote" etc, but I'm not too keen on this either, since that seems overly complex.

**Comment by adunning** [comment]
Looking in `footnotes.xml` for the resulting file, Pandoc 2.0.6 generates the following XML:

```xml
<w:footnote w:id="1"><w:p w14:paraId="43C08C7C" w14:textId="77777777" w:rsidR="00F84EA0" w:rsidRDefault="009D023E"><w:pPr><w:pStyle w:val="FootnoteText"/></w:pPr><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteRef/></w:r><w:r><w:t xml:space="preserve"> Footnote.</w:t></w:r></w:p><w:p w14:paraId="4CDA4BB6" w14:textId="77777777" w:rsidR="00F84EA0" w:rsidRDefault="009D023E"><w:pPr><w:pStyle w:val="FootnoteText"/></w:pPr><w:r><w:t>Quotation inside footnote.</w:t></w:r></w:p></w:footnote>
```

Modifying the style of the quotation within Word changes it to this:

```xml
<w:footnote w:id="1"><w:p w14:paraId="2CAE241C" w14:textId="77777777" w:rsidR="00A31F05" w:rsidRDefault="00487A26"><w:pPr><w:pStyle w:val="FootnoteText"/></w:pPr><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteRef/></w:r><w:r><w:t xml:space="preserve"> Footnote.</w:t></w:r></w:p><w:p w14:paraId="2FAC1200" w14:textId="63C3C8A1" w:rsidR="00A31F05" w:rsidRDefault="006029E5" w:rsidP="00B44105"><w:pPr><w:pStyle w:val="BlockText"/></w:pPr><w:r w:rsidRPr="006029E5"><w:t xml:space="preserve">Quotation </w:t></w:r><w:bookmarkStart w:id="0" w:name="_GoBack"/><w:bookmarkEnd w:id="0"/><w:r w:rsidRPr="006029E5"><w:t>inside footnote.</w:t></w:r></w:p></w:footnote>
```

It seems, then, that one can merely use `<w:pPr><w:pStyle w:val="BlockText"/></w:pPr>` with the relevant paragraph.

**Comment by adunning** [comment]
Actually, it seems that the `FootnoteText` style does not need to be added to the block quotation within the footnote.
