### ISSUE TITLE
Error when <svg> tags exist in css file and --self-contained specified

### ISSUE THREAD

**Issue by jrowen** [jgm/pandoc#2129]
The command I'm using is
```
pandoc.exe test.md -s -c test.css -o test.html --self-contained
```
the test.md file contains
```
# Test
```
and the test.css file contains
```
.bk-logo {
  position: relative;
  display: block;
  background-repeat: no-repeat;
  &.grey {
    filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale"); /* Firefox 10+, Firefox on Android */
    filter: gray; /* IE6-9 */
    -webkit-filter: grayscale(100%); /* Chrome 19+, Safari 6+, Safari 6+ iOS */
  }
}
```
This results in an error
```
pandoc.exe: Could not fetch .\data:image/svg+xml;utf8,<svg ... </svg>: openBinaryFile: invalid argument (Invalid argument)
```
In this case, I believe we don't want pandoc to base64 encode the text between the `svg` tags.

**Comment by nkalvi** [comment]
@jrowen 
I'm wondering whether using `--include-in-header=test.css` (after surrounding the content in `<style>` tag) would be a workaround in your case; i.e. instead of using --self-contained.

I do agree that this should not be treated as file to encode.

**Comment by jgm** [comment]
Note that the fix I just pushed might not work with your "css," which I believe is SASS, not CSS.  But at least pandoc now behaves better with data: uris in CSS.

**Comment by jrowen** [comment]
Thank you--once again the quick response is really appreciated. Sorry if I may have abused terminology a bit in my effort to create a reproducible example.  FYI, [here](https://github.com/bokeh/rbokeh/issues/64) is a summary of where the error originated.
