### ISSUE TITLE
CR is not read as whitespace

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2132]
Under Pandoc 1.13.2.1 on OS X 10.10.3, I am finding that CR is not converted to a space. For instance, running `pandoc http://cassian.memphis.edu/history/jmblythe/3370/MerchantSaint12th.htm`, the output will include strings such as 'reduplicatethe' and 'commercialuse'.

Similarly, if one has a text file with the following contents:

```
This is a test
sentence.
```

The result is `<p>This is a test sentence.</p>` if it is saved with LF or CRLF, but `<p>This is a testsentence.</p>` if it is saved with CR.

**Comment by jgm** [comment]
`tabFilter` is supposed to handle CR line breaks.
The problem is that Haskell's `getContents` seems to strip out the CRs before it even gets to our code.

**Comment by jgm** [comment]
Never mind - it's not `getContents`, but the wrapped version I have in `Text.Pandoc.UTF8`. This should be an easy fix.

**Comment by jgm** [comment]
Problem was introduced by c7f4333f83b7441ad9a3a43c798b8f029670ffa3, which was probably intended to make sure newlines were normalized when templates were loaded.

**Comment by adunning** [comment]
That's quite interesting. Thanks for taking care of it!
