### ISSUE TITLE
markdown_strict+fenced_code_blocks

### ISSUE THREAD

**Issue by mike-ward** [jgm/pandoc#2135]
Given:

    Test
    
    ```
    code block

    testing 123
    ```

and the options:

    pandoc -f markdown_strict+fenced_code_blocks -t markdown_strict+fenced_code_blocks

I get:

    Test

    \`\`\` code block
    
    testing 123 \`\`\`

Changing the text to:

    Test
    
    ~~~
    code block

    testing 123
    ~~~

yields:

    Test

        code block

        testing 123

Which may or may not be correct depending on the how `fenced_code_blocks` is used for output.

version 1.13.2

**Comment by lierdakil** [comment]
I could demystify first case -- backtick code blocks are controlled by
`backtick_code_blocks`, not `fenced_code_blocks`. @jgm should probably
update docs on that.

As for the second one, in a nutshell, writer prefers indented code blocks,
so if no code block attributes are specified, it will write code block as
indented code block. If there are attributes, however, it will choose
either fenced or backtick format (if both are enabled, it prefers backticks)

2015-05-06 1:29 GMT+03:00 Mike Ward <notifications@github.com>:

**Comment by mike-ward** [comment]
Makes sense. Thanks.
