### ISSUE TITLE
rtf writer: outermost \rtf1 environment missing

### ISSUE THREAD

**Issue by jlrn7** [jgm/pandoc#2140]
Hello! 

I've been doing some tests with pandoc and a series of document formats, and I found that the rtf writer perhaps has a bug: it fails to write out the outermost {\rtf1 } environment required to conform to the specification. This way, rtf readers (MSWord and LOWriter) fail to parse pandoc's output as valid rtf. The output file is easily fixed by addding this extra environment.

Any tiny input file may work as a mwe.

Checked with pandoc 1.13.2 for Windows 7/32&64.

Cheers,

**Comment by jgm** [comment]
Are you using the `-s` option, to produce a standalone
document rather than a fragment?

+++ jlrn7 [May 07 15 12:12 ]:

**Comment by jlrn7** [comment]
I see... 

Well, I thought that the rtf writer behaved somewhat like the odt, docx, epub or epub3 writers, producing standalone output by default; but now I see that the documentation implies otherwise. While for other document formats (markdown, dokuwiki, even HTML or LaTeX) I see the advantage of producing document fragments, it strikes me as odd to have fragments of rtf output, as they are relatively hard to merge into larger documents. Is this decision perhaps determined by the fact that the standalone formats are in practice zipped bundles of files?

You may close this issue. My apologies for the confusion.

**Comment by jgm** [comment]
+++ jlrn7 [May 07 15 14:36 ]:
>   I see...
>
>   Well, I thought that the rtf writer behaved somewhat like the odt,
>   docx, epub or epub3 writers, producing standalone output by default;
>   but now I see that the documentation implies otherwise. While for other
>   document formats (markdown, dokuwiki, even HTML or LaTeX) I see the
>   advantage of producing document fragments, it strikes me as odd to have
>   fragments of rtf output, as they are relatively hard to merge into
>   larger documents. Is this decision perhaps determined by the fact that
>   the standalone formats are in practice zipped bundles of files?

Yes, we generate fragments by default for all textual
formats.  For binary formats, fragments don't make sense.
