### ISSUE TITLE
bug in YAML field with multiple authors?

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#2142]
From the following source:

``` md
---
title: The Title
subtitle: The Subtitle
author: The Author
author: John Doe
author: Jane Doe
...
```

I get the following HTML output with pandoc-1.13.2:

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <meta name="author" content="Jane Doe" />
  <title>The Title</title>
  <style type="text/css">code{white-space: pre;}</style>
</head>
<body>
<div id="header">
<h1 class="title">The Title</h1>
<h1 class="subtitle">The Subtitle</h1>
<h2 class="author">Jane Doe</h2>
</div>

</body>
</html>

```

At least with HTML output, pandoc-1.13.2 only includes the last author.

I think this is a bug.

BTW, would it be possible to have a `<meta name="subtitle" content="$subtitle-meta$" />` for subtitles? If accepted, I would open a proper issue at `pandoc-templates`.

**Comment by lierdakil** [comment]
Pandoc expects `author` field to be YAML array in case of multiple authors, and does *not* expect multiple `author` fields (I'm not even sure it's allowed by YAML spec). If you want to include multiple authors, use YAML array syntax, i.e.
```markdown
---
author:
    - Mary Sue
    - Gary Stu
...
```

**Comment by jgm** [comment]
Correct. Not a bug.

**Comment by ousia** [comment]
@lierdakil, @jgm, sorry, I didn’t know that an array was the way to indicate multiple authors.
