### ISSUE TITLE
how to install pandoc on win7 64?

### ISSUE THREAD

**Issue by cpyman** [jgm/pandoc#2145]
I can't find pandoc.exe for windows anywhere.

Can anyone tell me?

**Comment by nkalvi** [comment]
https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-windows.msi

Found under
https://github.com/jgm/pandoc/releases

**Comment by jgm** [comment]
http://pandoc.org/installing.html

Note:  this tracker is for bug reports, not questions.
Please direct questions to the pandoc-discuss google group.
