### ISSUE TITLE
\label{} in figure caption fails to render figure

### ISSUE THREAD

**Issue by hadim** [jgm/pandoc#2150]
The following markdown (from 70df1b572bc6859a50f43f00850bec16bff354c7 pandoc build):

```markdown
![Some caption here \label{my-label}](figures/test.png)
```

will produce a pdf without figure but raw markdown instead.

In 1.13.2 the same markdown will generate the figure correctly.

The bug disapears if you don't use  \label{my-label}.

**Comment by jgm** [comment]
Minimal case
```
![\a](b)
```

**Comment by jgm** [comment]
Also affects links:
```
[\a](b)
```

**Comment by jgm** [comment]
My guess is that this was introduced by e9d7504bea5add902f95806a2dbac0248899777d

**Comment by hadim** [comment]
Very nice ! Thank you @jgm.
