### ISSUE TITLE
language setting for ODT

### ISSUE THREAD

**Issue by imz** [jgm/pandoc#2151]
I tried to make the resulting document have Russian as its language set, but this didn't give the result:

    -v lang=ru

I see this because the spellchecker in LibreOffice4.2 underlines all words.

Also the value from reference.odt doesn't seem to be inherited, because when I open my reference.odt in LibreOffice4.2, the words are not underlined, so I must have Russian set as the language.

* * *

pandoc 1.13.2.1

**Comment by imz** [comment]
Actually, appending `-v lang=ru` to the command in my case made pandoc silently wxit without producing any new output (`.odt`)!

My complete command:

    	pandoc -s $^ -o $@  --smart

works, but:

    	pandoc -s $^ -o $@  --smart -v lang=ru

silently produces nothing.

**Comment by imz** [comment]
An `strace`-trace for it shows nothing special:

    [pid 28840] execve("/home/imz/.cabal/bin/pandoc", ["pandoc", "-s", "task-report.md", "-o", "task-report.odt", "--smart", "-v", "lang=ru"], [/* 87 vars */]) = 0
    [pid 28840] access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1/tls/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1/tls/x86_64", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1/tls/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1/tls", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1/x86_64", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-1.13.2.1", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19/tls/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19/tls/x86_64", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19/tls/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19/tls", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19/x86_64", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/HTTP-4000.2.19", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3/tls/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3/tls/x86_64", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3/tls/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3/tls", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3/x86_64", 0x7fff188a2dd0) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] stat("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/JuicyPixels-3.2.3", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/SHA-1.6.4.1/tls/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)


skipping

    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/hashable-1.2.3.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/highlighting-kate-0.5.14/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/hourglass-0.2.9/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/hslua-0.3.13/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/http-client-0.4.11.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/http-client-tls-0.2.2/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/http-types-0.8.6/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/integer-gmp-0.5.0.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/lifted-base-0.2.3.6/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/mime-types-0.1.0.5/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/mmorph-1.0.4/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/monad-control-1.0.0.4/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/mtl-2.2.1/ghc-7.6.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/nats-1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/network-2.6.0.2/ghc-7.6.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/network-uri-2.6.0.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/old-locale-1.0.0.5/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/old-time-1.1.0.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pandoc-types-1.12.4.2/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/parsec-3.1.8/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/pem-0.2.2/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/pretty-1.1.1.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/lib/primitive-0.5.0.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/process-1.1.0.2/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/publicsuffixlist-0.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/random-1.1/ghc-7.6.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/regex-base-0.93.2/ghc-7.6.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/regex-pcre-builtin-0.94.4.8.8.35/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/resourcet-1.1.4.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/scientific-0.3.3.7/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/securemem-0.1.7/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/semigroups-0.16.2.2/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/socks-0.5.4/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/stm-2.4.4/ghc-7.6.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/streaming-commons-0.1.10.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/syb-0.4.4/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/tagsoup-0.13.3/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/template-haskell-2.8.0.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/temporary-1.2.0.3/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/texmath-0.8.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/text-1.2.0.4/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/time-1.4.0.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/tls-1.2.17/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/transformers-0.4.2.0/ghc-7.6.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/transformers-base-0.4.4/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/transformers-compat-0.4.0.4/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/unix-2.6.0.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/unordered-containers-0.2.5.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/lib/utf8-string-0.3.7/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/lib/vector-0.10.0.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/void-0.7/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/x509-1.5.0.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/x509-store-1.5.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/x509-system-1.5.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/x509-validation-1.5.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/xml-1.3.14/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/yaml-0.8.10.1/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/home/imz/.cabal/lib/x86_64-linux-ghc-7.6.1/zip-archive-0.2.3.7/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib64/ghc-7.6.1/lib/zlib-0.5.4.0/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    [pid 28840] open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib/locale/ru_RU.UTF-8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    [pid 28840] open("/usr/lib/locale/ru_RU.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 3
    [pid 28840] open("/usr/lib64/gconv/gconv-modules.cache", O_RDONLY) = 3
    [pid 28840] +++ exited with 0 +++
    --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=28840, si_status=0, si_utime=0, si_stime=1} ---

**Comment by jgm** [comment]
The one-letter option equivalent to `--variable` is `-V`, not `-v`.
So that explains that part.

**Comment by imz** [comment]
Sorry for this stupid mistake! I'll check again now.

**Comment by ousia** [comment]
@imz, i think your issue (or a similar one) is described in #1667.

**Comment by imz** [comment]
@ousia True, exactly the same issue, as I understood my issue. I only didn't know for sure about the existence of the corresponding YAML attribute.

(Closing as a duplicate.)
