### ISSUE TITLE
Update the "Authors" chapter in `README.md`

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2153]
The "Authors" chapter towards the end of `REAME.md` starts with this line:

> © 2006-2013...

This should probably be updated before the next release. More importantly, I do not see quite a few names mentioned as contributors which need to be (unless all these persons indicated that they do not *want* to be named...).

**Comment by jgm** [comment]
+++ Kurt Pfeifle [May 14 15 12:06 ]:
>   The "Authors" chapter towards the end of REAME.md starts with this
>   line:
>
>     © 2006-2013...
>
>   This should probably be updated before the next release. More
>   importantly, I do not see quite a few names mentioned as contributors
>   which need to be (unless all these persons indicated that they do not
>   want to be named...).

I generated a list of names from the repository.  If anyone
is still missing, let me know.
