### ISSUE TITLE
FR: support Confluence XHTML-like storage format

### ISSUE THREAD

**Issue by imz** [jgm/pandoc#2155]
Confluence has an XHTML-like [storage format](https://confluence.atlassian.com/display/DOC/Confluence+Storage+Format). It can be accessed through the [Confluence Source Editor](https://marketplace.atlassian.com/plugins/com.atlassian.confluence.plugins.editor.confluence-source-editor).

pandoc could support writing (and perhaps reading) it.

(Confluence also makes some uses of a wiki-like format, but that's not so interesting for a tool like pandoc because it's not the format in which Confluence can store and edit existing pages--only insert new stuff. But slightly interesting, too. E.g., writing and reading tables in their format for conversion.)

**Comment by HughP** [comment]
How often do you use the "XHTML-like storage format"? I use confluence daily as an end-user and content creator (as apposed to someone like a sys-admin). I create templates and a variety of structures in Confluence. I have never been able to use the source editor reliably. Others on my team have unsuccessfully tried too. So, our milage might be due to our implementation of Confluence. I am wondering, do you use the source editor for other things already? (I generally agree that this would be a great way to move content into Confluence via pandoc.)

**Comment by imz** [comment]
@HughP I haven't yet used the "XHTML-like storage format". I have been writing a document in markdown, then doing a pandoc conversion to markdown (with `--smart` and to possibly clean up other things), and then inserted it in Confluence with the menu option "Insert..." > "insert mardown or markup".

In this process, I have an unpleasant  tweak: I've inserted a TOC in Confluence near the beginning of the text, so I have to pay attention to leave the TOC after pasting my new markdown revision (actually, I paste my new markdown revision after it, not touching the very head of the document). 

(Another unpleasant thing in this workflow is that I have to first select and delete the old text in Confluence, before pasting the new one.)

If pandoc could output the Confluence XHTML-like, then I would arrange for the TOC to be inserted automatically into the source code which I would paste into Confluence.

I wonder whether using the Source Editor even for such a simple task as replacing the old text with a new revision would be unreliable, as in your experience... Anyway, it's a pity that it's unreliable.

(Generally, there are other imaginable uses of pandoc, if it were able to do the two-direction conversion to/from the Confluence XHTML-like source code; but I don't mention them in this comment because it's not the topic of the question.)

**Comment by jgm** [comment]
As far as I can see, this is XHTML with a few small additions for things that pandoc doesn't natively support anyway (big text, task lists, etc.).  Pandoc's html reader and writer should give you decent results already.  For better results I'd recommend adding an xslt transform.  I don't think there's strong enough reason to add a new reader or writer just for this.
