### ISSUE TITLE
Please relax restrictions on zlib and QuickCheck

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#2156]
Pandoc's Cabal file excludes the latest versions from several dependencies: http://packdeps.haskellers.com/feed?needle=exact%3Apandoc. At least the restrictions on `zlib` and `QuickCheck` are unnecessary. We've removed them in NixOS, https://github.com/peti/nixpkgs/commit/7e15d181c758731ecad3cfb91304768dc61f683a, and the build works just fine.

**Comment by jgm** [comment]
I plan to release 1.14 pretty soon -- it can use the newest versions of
everything.

+++ Peter Simons [May 16 15 05:37 ]:
