### ISSUE TITLE
reveal.js conversion 

### ISSUE THREAD

**Issue by zazazack** [jgm/pandoc#2157]
I've given it my best shot, but I can't seem to get from mdown to reveal.js without a significant amount of post conversion fiddling. Given that html, docx, etc. work like magic, I'm thinking there's an issue. Unfortunately, I'm a little new to this game, so I'm at a loss for what to try next to get this working. Here's the command I'm running:

```sh
pandoc -t revealjs -f markdown_mmd -s -V revealjs-url=http://lab.hakim.se/reveal-js test.md -o test.html
```

I get a working reveal.js slideshow, except for the nested slides based on heading levels. 

As you can see from the command I'm running, I had to modify the reveal.js url, otherwise, I would get a working .html file, but no reveal.js "slideshowiness".

**Comment by jgm** [comment]
Can you post `test.md` or a simplified version that illustrates the issue you're having?

**Comment by zazazack** [comment]
Yes.


Here's the raw markdown (links to files below):

```markdown
title: test reveal.js slideshow  
author: author's name  
date: May 18, 2015  

# 1st slide 

- this is the first list item
- this is the second list item

## 1st nested slide

- if I understood the user guide / man page correctly, a level 2 header should be nested, but this one isn't. 

# 2nd slide

- this should be a second level 1 slide 
```
------ 

link to test.md:  
<https://www.dropbox.com/s/leg2274uvyoofzm/test.md?dl=0>

test.html was generated with the following command:

```sh
pandoc -t revealjs -f markdown_mmd -s -V revealjs-url=http://lab.hakim.se/reveal-js test.md -o test.html
```

link to test.html:  
<https://www.dropbox.com/s/94l3z3xlvt676gs/test.html?dl=0>

test2.html was generated with the following command:

```sh
pandoc -t revealjs -V theme=black -s test.md -o test2.html
```

link to test2.html:  
<https://www.dropbox.com/s/4arisktjsk32kjd/test2.html?dl=0>

**Comment by jgm** [comment]
Did you read <http://pandoc.org/README.html#structuring-the-slide-show>?

In your case slide level = 1, since you have textual content right under a level-1 header.  So the level 2 header just creates a subhead on a slide.

If I understand what you're aiming for, you want slide level = 2, so you need to avoid putting content under a level 1 header.  You'll get a 2D slide show with level 1 headers the horizontal dimension.

**Comment by jgm** [comment]
PS.  Because of changes in reveal.js, you should use the new reveal.js template (in the jgm/pandoc-templates repository).

**Comment by zazazack** [comment]
Yes, I see now. I misunderstood the instructions and was able to get it working. If I now understand correctly, pandoc cannot generate a 2D reveal.js slideshow if *any* slide above the slide-level contains content? I noted that even when I used the `--slide-level` command to override the default behavior, pandoc strips the content from slides above the slide level.

### Command used

```sh
pandoc -t revealjs -f markdown_mmd --slide-level=2 --standalone -V revealjs-url=http://lab.hakim.se/reveal-js --css=http://lab.hakim.se/reveal-js/css/theme/solarized.css --css=http://lab.hakim.se/reveal-js/css/print/paper.css test3.md -o test3.html
```
### Revised Markdown Text (Test3.md)

```markdown
title: test reveal.js slideshow
author: author’s name
date: May 18, 2015

# 1st Header Slide
## 1st Slide Level Slide
level 2 is the “slide level”. Because the 1st Header Slide has no content, this slide is nested.
```

### Working 2D reveal.js slideshow
<https://db.tt/tLLJLHtP>

I'll update the template accordingly. Thanks!

**Comment by vick08** [comment]
But why this restriction? Reveal allows me to mix regular slides with the nested ones, so why Pandoc doesn't?

**Comment by jgm** [comment]
+++ Victor Tsaran [Jun 29 15 08:48 ]:
>   But why this restriction? Reveal allows me to mix regular slides with
>   the nested ones, so why Pandoc doesn't?

Pandoc has a method of carving content into slides
(described in the User's Guide) that works the same for all
slide formats, so you can use the same source for reveal.js
and beamer.  That is what motivated the present system,
though I'm open to a better way, as long as it works
uniformly with all formats.

**Comment by tonytonov** [comment]
The issue is also being referenced here: http://stackoverflow.com/questions/30988306/level-1-and-level-2-slides-in-reveal-js-using-pandoc/31778080
