### ISSUE TITLE
org-mode Tags showing up in titles and hiding content

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#2160]
As originally reported here: https://groups.google.com/d/msg/pandoc-discuss/Xi5FHWstao4/QVewcCFTIUoJ

I'm using pandoc to generate a revealjs presentation and I am using org-mode Tags, similar to this

http://sachachua.com/blog/2008/01/tagging-in-org-plus-bonus-code-for-timeclocks-and-tags/

```
 * Personal                                     :PERSONAL:
 ** TODO Buy milk                               :@ERRANDS:
 ** TODO Call Mom                               :@PHONE:
 ** TODO Send letters                           :@ERRANDS:
 * Work                                         :WORK:
 ** TODO Call John about report                 :@PHONE:JOHN:
 ** TODO Prepare for presentation on Monday
 ** TODO Call Mary about the presentation       :@PHONE:URGENT:MARY:
```

(actually I'm giving a joint talk and we're only using two tags, to indicate who is speaking in each section).

But when exported to revealjs, the Tags are showing up in the title of the slide.

In fact, if a title element has a :TAG: in it, the titles get rendered as text elements in revealjs and the content of the sections is ignored.

**Comment by tarleb** [comment]
Hi Sam, thanks for the report. I'll take a look.

**Comment by fommil** [comment]
I can give you access to my private repo if you need an example. It's only private until we give the talk, then it'll be public.

**Comment by tarleb** [comment]
Thanks, but since you provided some good examples, I don't think this will be necessary.

**Comment by tarleb** [comment]
Tag recognition wasn't implemented yet, partly because the default Org-Mode behavior is to just export the tags anyway (the other reason being that I forgot about it).  One will need a switch to turn tag exports on and off, which is its own can of worms.  I very unsure about the best way to proceed here.

Anyway, your issue seems urgent, so you might have some use for my [ad-hoc implementation]( https://github.com/tarleb/pandoc/tree/org-header-tags) of :TAG: recognition.  The tags are silently ignored, which seems to be adequate in your specific case.

A proper implementation should follow, but it may take a while.

**Comment by fommil** [comment]
thanks for looking at it! Actually as workaround we can just not use tags.

**Comment by tarleb** [comment]
I guess that works, too :smile:.  Saves you some compiling.

It would be interesting to know if more Pandoc users hit this limitation. Maybe *always hide tags* turns out to be the right behavior here.

**Comment by fommil** [comment]
Yeah, unless you can do something (eg styling)with  the tags they don't do anything.

**Comment by jgm** [comment]
But if you just strip them out entirely, so they don't appear in the
AST, then you can't do anything with them using filters.

Would it make sense to make them into empty Span elements?

Then they wouldn't appear by default, but they'd still be detectable
by filters.


+++ Sam Halliday [May 20 15 11:15 ]:

**Comment by tarleb** [comment]
Sounds good to me.  Do you have any preferences for the attributes on those Spans (i.e. any specific class name I should use)?

**Comment by jgm** [comment]
+++ Albert Krewinkel [May 20 15 12:36 ]:
>Sounds good to me.  Do you have any preferences for the attributes on those Spans (i.e. any specific class name I should use)?

The Spans are rendered with span elements in HTML, so you might want to
use something that is going to be valid in HTML.

Best bet might be data attributes:
http://www.w3schools.com/tags/att_global_data.asp

**Comment by michelk** [comment]
It would  also be fantastic, if headers with a `noexport` tag would be excluded. The tag could be [customized](http://orgmode.org/manual/Export-settings.html) with `EXCLUDE_TAGS`; by default this is `:noexport:`.

**Comment by tarleb** [comment]
@michelk: Done, although customization of is not possible yet.

**Comment by fommil** [comment]
@tarleb sweet, thanks for both these fixes! Is there a branch that we can use which has both?

**Comment by tarleb** [comment]
I combined them here: <https://github.com/tarleb/pandoc/tree/org-recent-fixes>

**Comment by fommil** [comment]
@rorygraves we'll use this branch of pandoc, I'll update our README. @tarleb thanks so much! Feel free to delete the branch in a couple of weeks as I'm sure you'll be merging all this to upstream master and I haven't got any other talks for a while :smile:

**Comment by tarleb** [comment]
@fommil: You're very welcome, thank you for helping to improve the reader! It's always nice to know that somebody actually cares about this stuff.

**Comment by fommil** [comment]
@tarleb I write my talks with pandoc/org-mode these days, e.g. http://fommil.github.io/scalax14/#/

**Comment by fommil** [comment]
@tarleb from a fresh cabal/ghc I'm getting this when building your branch:

```
cabal install
Resolving dependencies...
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Failed to install cmark-0.3.2
Build log ( /home/fommil/.cabal/logs/cmark-0.3.2.log ):
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Preprocessing library cmark-0.3.2...
[1 of 1] Compiling CMark            ( dist/build/CMark.hs, dist/build/CMark.o )

CMark.hsc:61:11: Not in scope: `TF.withCStringLen'

CMark.hsc:72:5:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:79:3: Not in scope: `TF.withCStringLen'

CMark.hsc:85:12:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:324:22:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)
cabal: Error: some packages failed to install:
cmark-0.3.2 failed during the building phase. The exception was:
ExitFailure 1
pandoc-1.14 depends on cmark-0.3.2 which failed to install.
```

**Comment by tarleb** [comment]
Huh, that's strange.  Totally at a loss here, sorry. I'm doing most of
my Pandoc hacking in a VM, no problems there.

This is what I use, it's pretty basic:
[vagrant-pandoc-dev](https://github.com/tarleb/vagrant-pandoc-dev)

If all else fails, I could clean-up the above project, making it simpler
to use.  Depending on you OS, you'd have to mount your docs dir into the
vm and run pandoc from there.  Far from optimal, but the best I can come
up with right now.

**Comment by fommil** [comment]
looks like an upstream problem in the "cmark" library, maybe a version thing?

**Comment by fommil** [comment]
https://github.com/jgm/cmark/issues/40

**Comment by tarleb** [comment]
My guess is that there is a `text` version < 1.0.0.0 installed on your computer, but cmark requires `text >= 1.0.0.0` to be installed.  So it appears you are correct that this is a missing dependency bug.  It should probably be filed against the cmark's [haskell bindings](https://github.com/jgm/cmark-hs).

**Comment by tarleb** [comment]
It might be possible to fix this issue by running

```
cabal install text-1.2.1.0 --force-reinstalls
```

Maybe the `cabal sandbox` would come in handy here.

The other (and much more radical) solution would be to delete both your `~/.cabal` and `~/.ghc` directories, hence removing all Haskell settings and packages.

**Comment by fommil** [comment]
even when I get `cmark` to install, pandoc fails to compile. Looks like the text version is in conflict. cabal's transient version tracking confuses me, I'm going to wait until upstream fix this.

**Comment by fommil** [comment]
@tarleb ok, so now I've nuked all the `libghc-*` on my system, and cleared out `~/.cabal` and `~/.ghc`.

I can do a `cabal install pandoc` but doing a `cabal install` inside your branch is giving me this:

```
Resolving dependencies...
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Failed to install cmark-0.3.2
Build log ( /home/fommil/.cabal/logs/cmark-0.3.2.log ):
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Preprocessing library cmark-0.3.2...
[1 of 1] Compiling CMark            ( dist/build/CMark.hs, dist/build/CMark.o )

CMark.hsc:61:11: Not in scope: `TF.withCStringLen'

CMark.hsc:72:5:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:79:3: Not in scope: `TF.withCStringLen'

CMark.hsc:85:12:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:324:22:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)
cabal: Error: some packages failed to install:
cmark-0.3.2 failed during the building phase. The exception was:
ExitFailure 1
pandoc-1.14 depends on cmark-0.3.2 which failed to install.
```

It looks like your branch has a dependency inconsistency on it.

**Comment by fommil** [comment]
not just your branch, it is happening on pandoc master.

**Comment by michelk** [comment]
Great, thanks @tarleb .
