### ISSUE TITLE
epub numeric document endnote links broken

### ISSUE THREAD

**Issue by danomatika** [jgm/pandoc#2163]
Using: pandoc 1.13.2.1

When using a numeric bibliography style, specifically ieee-with-url.csl, the epub reference links are broken since the bibliography is in a separate chapter: the last .xhtml file. Footnote/endnote styles such as chicago-note-bibliography.csl work fine since the references are within the same chapter .xhtml.

It seems as though pandoc is treating all citation references, at least with this .csl, as chapter endnotes instead of book endnotes.

I'm getting this:

    <a href="#ref-JohnDoe2013">

when I need this:

    <a href="ch010.xhtml#ref-JohnDoe2013">

I'm currently able to fix this by opening the generated epub, adding the last chapter filename before all reference links, then updating the original zip/epub. Of course, this would break custom chapter footnote/endnotes but I'm not using any so it's OK for now. I assume that the bibliography is in the last chapter.

Here's my workaround, adapated from my Makefile:

~~~~
unzip -uq MyBook.epub -d epub_tmp
cd epub_tmp
LAST_CHAPTER=`ls ch*.xhtml | tail -n 1`
echo "LAST_CHAPTER = $LAST_CHAPTER"
sed -i.bak "s/#ref/$LAST_CHAPTER#ref/g" ch*.xhtml
zip -q0 ../MyBook.epub ch*.xhtml
cd ../
rm -rf epub_tmp
~~~~

**Comment by jgm** [comment]
Could you give a simple example that suffices to reproduce the problem?

I'm surprised by this, because pandoc's epub writer has code to
recognize fragment links and rewrite them appropriately.

This may have something to do with #1887.

**Comment by danomatika** [comment]
I created a small example project that demos #2161, #2162, & #2163: https://github.com/danomatika/pandoc-test

To build epub and print out generated #refs links:

    make
    make check-refs

The output I get is:

~~~~
# #ref's should be preceeded by the last chapter .xhtml
unzip -c text.epub ch*.xhtml | grep "#ref"
<p>123456 <span class="citation" data-cites="Hutchinson-2013-swimming"><a href="#ref-Hutchinson-2013-swimming">1</a></span></p>
<p>abcdefg <span class="citation" data-cites="Monchaux-2011-simulation"><a href="#ref-Monchaux-2011-simulation">2</a></span></p>
~~~~

**Comment by jgm** [comment]
What I'm seeing is that the links are turning into e.g.

    href="ch005.xhtml#ref-Hutchinson-2013-swimming"

but there is no ch005.xhtml (because of #2162).

So fixing #2162 should fix this, too.

**Comment by danomatika** [comment]
Ok cool. So this was basically fixed in the current dev version. I just wanted to double check based on what I was seeing. Looks like 1.4 will fix a number of things for me!
