### ISSUE TITLE
[Feature request] DocBook 5 support

### ISSUE THREAD

**Issue by and3k** [jgm/pandoc#2164]
This would be nice. I guess it shouldn’t be very much effort, because DocBook 4.5 and 5 are very similar.

Thanks! :)

Bela

**Comment by and3k** [comment]
PS: my temporary workaround is to use `xsltproc` and the `db4-upgrade.xsl` stylesheet included in DocBook 5

**Comment by jgm** [comment]
Are you talking about input (reader) or output (writer)?

Can you give a summary of the changes from 4.5 to 5 that would affect pandoc?

**Comment by and3k** [comment]
I’m talking about the writer. The reader probably doesn’t care if it’s 4.5 or 5, because they are so similar.

For sure a DocBook 5 template would be needed, because the header is different.

Additionally it should only be minor tweaks, like renaming tags or attributes (`ulink` to `link`, `id` to `xml:id`, …)

A list of all the changes: http://docbook.org/tdg5/en/html/ch01.html#introduction-whats-new

**Comment by adeluccar** [comment]
Input would be cool too. I use pandoc to go from docbook4.5 to epub atm.

**Comment by IvoBCD** [comment]
Had a stab at adding docbook5 writer support; see pull requests
https://github.com/jgm/pandoc/pull/2890 and https://github.com/jgm/pandoc-templates/pull/197

**Comment by jgm** [comment]
Closing since we now have the writer support.
