### ISSUE TITLE
Does pandoc support Lisp in code blocks?

### ISSUE THREAD

**Issue by omero72** [jgm/pandoc#2168]
Hello

I'm making a markdown document about Lisp so I use Lisp code blocks. I've noticed pandoc doesn't seem to support Lisp inside code blocks.

 Here is the sample `sample.lisp`:
  
 ``` {#mycode .Lisp .numberLines}
 ;;;; sample.lisp
 (defun sample (x)
 (format t "~A" x))
 ```
And here's how I tried to make it into my target (epub) file:

$ pandoc lisp-sample.txt -f markdown -t epub -s -o lisp-sample.epub --indented-code-classes=CLASS

The resulting epub is at: http://i.hizliresim.com/kkWvmm.png (includes some Python code block for some checks)
 
I've changed the .Lisp to .lisp, .LISP, .CL, i.e. to various abbreviations to see if it would work but it didn't. Maybe I'm missing something obvious; I'm a beginner in the markdown thing. The question is does pandoc support Lisp in code blocks? If it doesn't, how to make it support Lisp? Thanks.

**Comment by michaelt** [comment]
omero72, in highlighting-kate, there is "commonlisp" https://github.com/jgm/highlighting-kate/blob/master/xml/commonlisp.xml , which seems to work as in github:

    Some Common Lisp:
     
    ```commonlisp
    (+ 1 1)
    ```
    Some Haskell:

    ```haskell
    main = putChar 'a'
    ```

This yields:  

Some Common Lisp:
     
```commonlisp
(+ 1 1)
```

Some Haskell:

```haskell
main = putChar 'a'
```

**Comment by jgm** [comment]
The list of language names is here:
https://github.com/jgm/highlighting-kate
As you can see, there's commonlisp and scheme, but not lisp.

I should add an option to pandoc that prints these.

**Comment by omero72** [comment]
Oh yes, when I put it as "commonlisp" it worked. Actually I googled "pandoc code block language lisp"  to find the list of exact words for the code block languages, but the first 5 or 10 results didn't seem to contain even the word "lisp" so I thought pandoc didn't support lisp. Now it's ok.

No my text will use only the basic lisp, it will be a step-by-step tutorial about implementing some basic things like running a web server and doing database queries using lisp. 

Thanks!
