### ISSUE TITLE
There should be no new line after equation block in tex document

### ISSUE THREAD

**Issue by iarkhanhelsky** [jgm/pandoc#2171]
Assuming following code part in `md` file :

```
Some equation here
\begin{equation}
x = y
\end{equation}
where $x$ is something important
```

In `tex` file I should get same result without any new line after equation block. Because it's breaking identation rules used in latex. And no, `\noindent`[ #894] is not a solution, because it ridiculous.

**Comment by nick-ulle** [comment]
Even worse:
```{latex}
The formula
\begin{math}
x = y
\end{math}
should be inline.
```
This gets output as 3 paragraphs. The `math` environment is equivalent to `\(` or `$` in Latex documents.

It seems like Pandoc has a general problem with handling new lines when translating Markdown to Latex. If I recall correctly, this is a limitation of the current Pandoc AST, so it can't be fixed using a filter. Perhaps an attribute could be added to `Block` elements?

**Comment by jgm** [comment]
Generally pandoc treats any LaTeX environment it doesn't
know as a raw LaTeX block.  There are a few cases, like this, where
that isn't appropriate, and we can special-case them.

I'd never seen the "math" environment used, but it will be
trivial to treat this like `\(..\)`.

+++ Nick Ulle [Jan 28 16 18:25 ]:

**Comment by METhOphetamine** [comment]
This is still an issue when converting from org to latex (or pdf via latex). It should be considered a bug because emacs org mode does not do that.

I'm on version 3.1.11.1 but I'm guessing this isn't suddenly fixed in the git version, considering markdown had it fixed 9 years ago.
