### ISSUE TITLE
No syntax highlighting for converting Markdown to EPUB

### ISSUE THREAD

**Issue by meoow** [jgm/pandoc#2172]
I want to convert markdown to EPUB. I see pandoc converts and splits the original text to multiple chunks of xhtml when converting to EPUB. The problem is, in the epub file, the css in `<head>` for syntax highlighting appears in the first piece of xhtml files only, neither stylesheet.css nor other individual xhtml embeds this highlighting code, which leads to the highlighting being lost in the final epub.   
I can't find a option that can save highlighting css separately when converting markdown to html, thus I can pass the css file to `--epub-stylesheet` when converting to EPUB.

**Comment by jgm** [comment]
What version of pandoc are you using?  This sounds like a problem
that has been solved for a long time.  Try the latest released version
and let us know whether you still have the problem.

**Comment by meoow** [comment]
The workaround for now, is converting markdown to html first, then using a html parsing library to extract those highlighting css into a separate file, then converting markdown to epub again, then unzip the ebup file, then append the extracted css to the stylesheet.css within epub, then repack those files to a epub using zip.

**Comment by meoow** [comment]
@jgm Really? OK, It seems my version from the distro's repository does have slightly out-dated version, but I'll download the latest one and give it a try.

**Comment by meoow** [comment]
@jgm Negative. I tried **pandoc 1.13.2 for OS X**, it still has the same issue, or should I grab the master branch and compile the it myself?

**Comment by jgm** [comment]
Odd.  I just tried with pandoc 1.13.2 on OSX and could not reproduce what you reported.

I used the command `pandoc -o 2172.epub` with this input:

    % My title
    % Me
    
    # Chapter one
    
    ``` haskell
    x >>= y
    ```
    
    # Chapter two
    
    ``` ruby
    def f
      return 3
    end
    ```

I got the highlighting CSS in both ch001.xhtml and ch002.xhtml in the epub container.  Do you get different results with this test?  Are you sure you're not running an older version that might be installed on your system?

+++ Leon [May 25 15 20:20 ]:
>@jgm Negative. I tried **pandoc 1.13.2 for OS X**, it still has the same issue, or should I grab the master branch and compile the it myself?

**Comment by meoow** [comment]
@jgm Problem solved, it was my epub reader doesn't handle the highlighting well. I changed to using Calibre, and the highlighting showed up.  
Thanks for your help.
