### ISSUE TITLE
revealjs and --css parameter not compatible

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#2176]
currently, using the `--css` option with the revealjs output option is producing invalid output because it will overrite the inclusion of the default `simple.css` stylesheet and will omit the `id="theme"` attribute.

I recommend that the `--css` flag should append CSS files into the load list, not replace the existing.

**Comment by jgm** [comment]
This has already been fixed.

**Comment by fommil** [comment]
fantastic! I'm really looking forward to compiling the latest master of pandoc to get these fixes.
