### ISSUE TITLE
support revealjs v3.x

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#2177]
I was just rebuilding an old talk with the latest version of revealjs and I noticed that the revealjs output doesn't work anymore if the v3.x versions of revealjs are used.

For what its worth, revealjs v2.6.2 still works.

**Comment by zackp30** [comment]
"doesn't work" isn't very specific, is there any console errors?

**Comment by fommil** [comment]
@zackp30 pandoc produces an HTML file. The format of the file is simply not compatible with the latest version of the revealjs framework and doesn't render correctly in the browser.

**Comment by jgm** [comment]
There are changes in the current dev version (soon to be released as 1.14) that make pandoc work with 3.x.

This is why it's a good idea to search closed issues before reporting new ones. This would have revealed:
https://github.com/jgm/pandoc/issues/1994
https://github.com/jgm/pandoc/issues/1891
https://github.com/jgm/pandoc/issues/1949

+++ Sam Halliday [May 24 15 08:47 ]:
>I was just rebuilding an old talk with the latest version of revealjs and I noticed that the revealjs output doesn't work anymore if the v3.x versions of revealjs are used.
>
>For what its worth, revealjs v2.6.2 still works.

**Comment by fommil** [comment]
Cool thanks
