### ISSUE TITLE
Underscore followed by space in raw TeX

### ISSUE THREAD

**Issue by kirelagin** [jgm/pandoc#2180]
The following:

~~~~latex
\begin{code}
a a_ = 10
\end{code}
~~~~

gets converted by `pandoc t.pd -f markdown -t latex` into:

~~~~latex
\textbackslash{}begin\{code\} a a\_ = 10 \textbackslash{}end\{code\}
~~~~

The behaviour is triggered by the underscore followed by space and is definitely unexpected. I’d expect it to detect the LaTeX environment and treat the whole block as raw TeX.

**Comment by jgm** [comment]
Pandoc has no way of knowing that your `code` environment is
a verbatim environment (which changes the normal LaTeX
meaning of `_`).  So it stumbles trying to parse the `_`
as LaTeX.  I'm not sure what can be done about this short
of mind-reading, since `code` isn't a standard environment.

**Comment by kirelagin** [comment]
Ok, now I see the problem :confused:.

I’d expect Pandoc not to even try to parse LaTeX. I’d expect it to just copy-paste everything starting with `\begin{…}` up to a paragraph ending with `\end{…}`. That doesn’t sound half as cool as parsing LaTeX, but should work reasonably well.

**Comment by jgm** [comment]
The Markdown reader defers to the LaTeX reader to parse raw LaTeX
sections.  (Note, you can have nested environments and things like
that, so it's nontrivial.)

+++ Kirill Elagin [May 27 15 01:01 ]:

**Comment by kirelagin** [comment]
Right, there is probably no easy way out of this situation…
