### ISSUE TITLE
nested list converting to PDF

### ISSUE THREAD

**Issue by rbn920** [jgm/pandoc#2181]
I have a list nested two deep. Conversion to html formats fine but does not. Each list is indented with a tab.
ie.
* Level 1
    * Level 2
        * Level 3

But when converted to pdf level 3 retains the markdown character (*, -, +, etc)

**Comment by jgm** [comment]
LaTeX chooses which bullet to use based on the nesting level.  For the third level it uses `*`.
There are undoubtedly ways to customize this; you might ask on the tex stack exchange.  (You'd need to add something to your latex template or include in the header using `-H`.)

**Comment by rbn920** [comment]
Ahh, that was stupid of me. Thank you sir.
