### ISSUE TITLE
feature request: org-mode HTML container class

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#2182]
As discussed on the mailing list https://groups.google.com/d/msg/pandoc-discuss/C_XPFqMevHE/0_z-gHSvnDMJ it would be great if the following properties in an `org-mode` section resulted in the section having `myclass` as a container.

```
  :PROPERTIES: 
  :HTML_CONTAINER_CLASS: myclass 
  :END: 
```

**Comment by tarleb** [comment]
Dealing with property drawers is still on my todo. It's not a trivial problem, header-parsing would have to be altered significantly for this to work.

The best workaround I can offer is based on org blocks:

```
#+BEGIN_MYCLASS
* Content goes here
#+END_MYCLASS
```

Converted to HTML, this gives

```
<div class="myclass">
<h1>Content goes here</h1>
</div>
```

It's clunky and I hope to get the drawer stuff done  [Real Soon Now™](http://en.wiktionary.org/wiki/RSN).

**Comment by fommil** [comment]
that kind of workaround would work well for me! It's really just so I can have a section in my revealjs talks where the text is smaller (because it's a big list of contributor names and doesn't fit into one slide).

**Comment by tarleb** [comment]
Blocks named `COMMENT`, `HTML`, `LATEX`, `ASCII`, `EXAMPLE`, `QUOTE`, `VERSE`, and `SRC` have special meaning, everything else is free to use.

**Comment by fommil** [comment]
oh wow, that works with current pandoc! I'm surprised nobody pointed this out in the mailing list :smile:

OK, I'll close this in favour of your "real fix".
