### ISSUE TITLE
Make "download page" link to latest release

### ISSUE THREAD

**Issue by wcaleb** [jgm/pandoc#2186]
On the [installation instructions page](http://pandoc.org/installing.html), "download page" links to: 

https://github.com/jgm/pandoc/releases

Github also provides a way to link to the latest release, whatever it is.

https://github.com/jgm/pandoc/releases/latest

For people looking for the binaries, I think the second link is better, as one can easily scroll to the bottom of the page and grab the files.

**Comment by jgm** [comment]
Good suggestion, done.
