### ISSUE TITLE
Getting an error "pandoc: Could not find data file reference.docx" on a fresh Windows install

### ISSUE THREAD

**Issue by fnicollet** [jgm/pandoc#2187]
Hello,

I just installed the msi from the official link:
https://github.com/jgm/pandoc/releases

Pandoc was automatically added to my path, pandoc --version returns pandoc 1.14. I am running Windows 8 64 bits.

I tried this command line:
```pandoc -s -o result_pandoc.docx result.html```

So, trying to convert an HTML webpage (result.html) into a DOCX. I get the error:
```pandoc: Could not find data file reference.docx```

I can't find any "reference.docx" in my installation. From what I found online, you can create it with this command line:
```pandoc myfile.txt -o reference.docx```

But I get the same error. I tried creating an empty docx document, saving it next to my HTML file and running:
```pandoc -s -o result_pandoc.docx --reference-docx=reference.docx result.html```

But I still get the same error message.

What am I supposed to do to get html->docx running on Windows?

Thanks,
Fabien

**Comment by nkalvi** [comment]
@fnicollet You're right - I'm also getting the same error on a fresh install of v. 1.14 under Windows.
i.e. the following works with Pandoc 1.14 under OS X, but fails under Windows:
`pandoc --print-default-data-file reference.docx`

@jgm or @lierdakil may be able resolve it quickly.

But if you don't want to wait you could 'compile' reference.docx by downloading the source from https://github.com/jgm/pandoc/tree/master/data/docx.
Please let me know if you need more detailed instructions.

**Comment by jgm** [comment]
Sure enough, it's a problem with the package.
I hope to release a fixed package shortly.

**Comment by fnicollet** [comment]
Thanks both for your very quick input. When I discovered the project this morning I was like wow, "last release 5 hours ago"! I should have been more careful haha

I'll try with the 1.13.2 version in the meantime, no rush

Fabien

**Comment by fnicollet** [comment]
Just tried with version 1.13.2 and I got a result straight away, thanks @nkalvi for the direct link :)

**Comment by jgm** [comment]
@lierdakil this has to do with the changes generating the reference.odt and reference.docx files.

When pandoc is compiled with the `embed_data_files` flag, `hsb2hs` is used by cabal at the configure stage to build `Text.Pandoc.Data`.  However, at this stage the reference files have not yet been built!

Kludgy fix for windows installer builder is to run cabal install twice.  But I'd love to have a more robust solution, as this might bite us again in the future.

**Comment by jgm** [comment]
Still not fixed.

**Comment by dunn** [comment]
I'm having trouble building 1.14.0.1 on Mac OS.  It fails right at the end, with `setup: data/templates/default.html: does not exist`

Full logs (failure occurs in `04.cabal`): https://gist.github.com/dunn/44370cb79d9d29abf805#file-04-cabal

**Comment by jgm** [comment]
Are you building the source extracted from the tarball, or did
you get it from git?

If git, did you do `git submodule update`?  (See INSTALL).

**Comment by dunn** [comment]
Yep, that was the problem.  1.14.0.1 wasn't on Hackage, so I used the source tarball from here, forgetting about submodules.
