### ISSUE TITLE
"Line block" , not an independent element in the html output.

### ISSUE THREAD

**Issue by m-ichael** [jgm/pandoc#2188]
"Line block" (case exposure limited to html output below)

Applying in the in pandoc source ` | ` as a start of line, followed by a `<space>`  then the text of the line, repeating this for several lines shows up in the html output as a `<p></p>` , a paragraph with linebreaks inserted. The result is ...as only distinction the possibility to add line breaks to a single paragraph, no formatting can be applied since the element is paragraph, not a standalone "line  block" element.

Since in html "line block" syntax in source is not translated into a proper independent element, it cannot be formatted using css. The would be element needs that, mostly to stand out from paragraph text, since in the pandoc user guide itself is hinted to use it for adresses, poems, semantic elements that are not hurt by standing out from the regular textflow: title-section-subsection-paragraph-LINE QUOTE-another paragraph-and on...
User work-around: do not use 'line block' but obtain desired effect by inserting something as below in source text:

~~~~
> This is a blockquote with a linebreak\
   And a second line of the blockquote and break\
   And a third line.\
   mail complaints at <botmetkas@gmail.com>\
   or phone with any remarks at +287 78 8792490
~~~~~
Above would adopt the formatting of block quote and stand out. If line quote was to be given it's proper element, it could be made to adhere blockquote style and be customized on top of that. The pandoc engine should - this is the suggestion of the "issue" - provide for that ideally.

> This is a blockquote with a linebreak
   And a second line of the blockquote and break
   And a third line.
   mail complaints at <botmetkas@gmail.com>
   or phone with any remarks at +287 78 8792490

Using the line quote element as it is now translated  the result would look like below:

| This is a blockquote with a linebreak
| And a second line of the blockquote and break
| And a third line.
| mail complaints at <botmetkas@gmail.com>
| or phone with any remarks at +287 78 8792490

Not very helpful as output html.

The hack for the user: start sentence at start of every line, and end every sentence with a linebreak. This will do as such, the user can decide on the end of lines, and obtain the formatting of block quotes. Block quotes are a single independently formattable element.

To the developers: give line quotes it's proper element, identity so it can be formatted independently.

Systemic: above has to do with not deciding on a finite body of semantics, then for every semantic element point to a syntax element, that is formattable independently.  This is an error that touches the low level of text as a tool to process into human structured skelletons, and is done by the aid of a machine. The author stands central in the transmission, since he is now not only the content provider but the editor and publisher in one. In analog speach: the meta and data en more then one level each are now his responsibility. 

That is one of the ideas that Pandoc promotes implicitly: man over machine to man communication, adaptable to specific needs and specific end user categories. It should do so by detailing finitly semantic sets suitable for most uses, human readers, different author needs. In the analog publishing world this is mostly solved implicitly by separating author-editor-publisher tasks. 

Pandoc needs to do so as well for the middle man it caters to: the author-editor-publisher.
First there is the choice of what are the elements within general semantics of communication to humans that apply and should be made available in Pandoc,  then there should be an element of pandoc syntax that comes closest to express the (semantic or meta) texture in the output, and ideally how can the publisher(author-editor) style these elements to a coherent style over the long run, so as to give the body of work from a paper, a book, a career a fluid and recognizable style.  To his end users and readers incorporating the needed selection of semantic elements, maybe having different semantics for communication with collaborators, students, public intellectualism versus note-taking, teaching and on, this should be transparent. ...Or not, it can be no more convenient to an end user(a student, a collaborator) disposing over a pandoc engine, the semantics adhered to and template and added style sheets, to be remitted the source code. There is no more convenient way to annotate, search, search and replace, as much tools for the author to human readers as the programmer of computer code, and diff whole project directories then using source text versus anything else: pdf and html and epub are output formats for narrating, not for scanning. Ad git and one has collaboration that exceeds the workability of the next contender(wiki engines).   

The key is semantic rules, in a finite body, different sets of, detail and document them, provide clear element of syntax for every semantics rule.  Asciidoc comes closest to provide this as a markup language, ...only it's semantics are limited, hardwired to specific use.

Example in case: an author needs to distinguish between quotes of all sorts and body text. Question: is a "line quote" a quote or body text, if it is a quote of sorts, how can it cohere to quotes in general, be formatted specifically as an element, ... and can a quote be used to express something as a standout for contact information, if so, would it need a different syntactic element to express itself, or would it be acceptable to consider a line quote as a semantic work-around.  These are semantics questions, in latex terms this would mean a new or not command and to build a framework one would use a style.
As to be noticed, publishers provide their own stylesheets, templates and citation formats.

In Pandoc these addresses are not attended systemically, resulting in the hacking of templates, adding css stylesheets without the needed coherent explanation of a systemic approach. Pandoc is inherently more complicated, since the ambition is "write once, then output "anything".  The reality is that output formats have their own requirements, making matters exponentially more complicated. Are the semantic elements provided for in all of the output formats envisioned, where must the syntax for every element be adjusted?

So now in the early note a specific problem was pointed at. It is not a bug, not an issue, processing goes well, but it shows the systemic flaws of Pandoc that can be addressed and make Pandoc a long-term artificial intelligence tool.  Google comes closest in visionary oversight, and ...budget, but it has corrupted from early stages into corrupting into proprietary and short-term profit engineering, thus hampering the birth of artificial intelligence. Back to grep, diff, pandoc and the unix kernel to get a grasp on the future.  

m.

**Comment by jgm** [comment]
I agree that there should be a LineBlock element in the AST.
This is in the plans for a later version, but because it requires
a change to pandoc-types, and to all readers and writers, it's
a bit involved.

**Comment by m-ichael** [comment]
Tnks for the fast reply,

Beyond,

In the mid-term,

Maybe could there be a descriptive set up of all the
elements(semantics) the pandoc engine recognizes and provides, and
processes accordingly in all of it's writers that is complete and well
structured.
It might require the acceptance that "pandoc! #pdf" and "pandoc! #html" are
very different animals, ...but do predictably what they promise if the
author knows what he wants to obtain.
The less cluttered source code as compared to latex and one source for
all output formats would pertain, ...only confusion as in no precise
obstructions and complexity of how to give these instructions to the
engine would be interchanged, from alchemy to chemistry.
This would be a first.
Independently from how the elements processed by the pandoc engine 
syntactically need to be called, and how and where they can be
styled and formatted.
Wikimedia, Plos, Springer, Elsevier, all went there and came all up
inferior if the author-editor-publisher in one(this can comprise more
then a single individual but would represent one stage between the
user of pandoc, the machine processing and the output utility), can be
empowered, and the text format as source, the most appropriate tool to
scan and search and diff can be pushed to where it belongs: universal
language: between the bits and syllables of machine and man.

Suggestion: leave room for one or two semantic elements that can be
syntactically defined and then styled at wish by the 
user(the author-editor-publisher) of pandoc 
so any probable needs are attended.

Sincerely think, and that is more then a hunch, Pandoc and the chain of
workflows it attends could be part of a better artificial intelligence
model, so "germline editing" of pandoc engine is a gimmick that can have
a very long life-line.

Regards for the Pandoc effort,

**Comment by jgm** [comment]
+++ m-ichael [May 28 15 09:40 ]:
>Maybe could there be a descriptive set up of all the
>elements(semantics) the pandoc engine recognizes and provides, and
>processes accordingly in all of it's writers that is complete and well
>structured.

There is:

https://hackage.haskell.org/package/pandoc-types-1.12.4.2/docs/Text-Pandoc-Definition.html

>Suggestion: leave room for one or two semantic elements that can be
>syntactically defined and then styled at wish by the
>user(the author-editor-publisher) of pandoc
>so any probable needs are attended.

We have native Div and Span elements for that, and filters.

**Comment by m-ichael** [comment]
Will look into that, 

Thnks,

**Comment by m-ichael** [comment]
## Indeed, div and span allows some customization. 

~~~
<div class="panorama"><img alt="img name" src="karanfil.jpg"></img><div>This is the caption test.</div></div>
~~~

in the source code would according to css class instructions give an image that say spans the whole body width ...in html output.
It would also be *not* included in the pdf output, only the caption would survive.

## Second:

~~~
<span style="font-variant:small-caps;">this string will be outputted in smallcaps regardless of the output being html or pdf</span>
~~~

...would be output correctly in pdf and html alike.
Is there a suggestion how to write the first example differently to have the pandoc engine output the image in pdf, or is this a matter of tweaking the template.latex instructions.

The question of course is irrelevant when one fully understands Haskell and the Pandoc library, there must be an easy explanation: the 'div' probably not converted to latex rightly or not at all, or the latex template applied not processing the image for some reason, latex does not throw an error though.  Which in itself can have many reasons also. 
Is it the Pandoc engine that acts as the impediment?
