### ISSUE TITLE
Biblatex + \fullcite not properly handled by pandoc when reading LaTeX file

### ISSUE THREAD

**Issue by edgimar** [jgm/pandoc#2193]
A simple example exhibiting the problem is to try to convert the LaTeX file in [this stack-exchange answer](http://tex.stackexchange.com/a/2922/3888) to something else (e.g. odt).  Compare the result with the output of processing the tex file with pdflatex.

Specific steps to reproduce the issue are;

1. Create a file called `x.tex` containing the following content:
    ```latex
\documentclass{article}
\usepackage{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{abc,
  author = {John Doe},
  year = {1970},
  title = {Article Title},
  journaltitle = {Journal Name},
  volume = {1},
  number = {2},
  pages = {13--17},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
xxxxxxxxxxxxxxxxxxxxxxx
\fullcite{abc}.

yyyyyyyyyyyyyyyyyyyyyyy
\printbibliography
\end{document}
```

2. run the following sequence of commands to generate `x.pdf`:
    ```bash
pdflatex x.tex
biber x
pdflatex x.tex
```

3. compare the content in `x.pdf` with the output of running the following:
    ```bash
pandoc --bibliography=x.bib -o out.docx x.tex
```

First, you will note that step 3 fails, because of another issue w/ pandoc not being able to handle a `\begin{filecontents}` in the preamble.  To temporarily work around this issue, you can either move the `filecontents` environment to the body of the document, or just remove it altogether from the tex file.

I am using pandoc 1.12.4.2.

**Comment by jgm** [comment]
Closing in favor of #2335
