### ISSUE TITLE
commitBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by voigt** [jgm/pandoc#2195]
Hey,

fiddling around with [python and pypandoc](https://github.com/bebraw/pypandoc/issues/56#issue-82595286) I experienced issues with the following:

**Command**
```
pandoc --from=markdown --to=html demo.md
<p>pandoc: <stdout>: commitBuffer: invalid argument (invalid character)
```
**demo.md**
```
&#55357;
```

**Version:**Pandoc `1.14.0.1`

I assume its some kind of encoding issue but have no idea how to fix this?

**Comment by nkalvi** [comment]
@voigt Is the char in your example a valid one? It fails validation at https://validator.w3.org/#validate_by_input

**Comment by voigt** [comment]
@nkalvi Can't tell u exactly what char it is. I think assume it's an emojii!

**Comment by nkalvi** [comment]
@voigt I'm not sure. But please take a look at http://stackoverflow.com/questions/13165408/decode-55357-to-real-character. It looks like it may need to be converted from UTF-16 to UTF-8 first.

**Comment by nkalvi** [comment]
@voigt http://www.fileformat.info/info/unicode/char/1F631/index.htm
