### ISSUE TITLE
Custom header classes instead apply to containing <div> in Epub output

### ISSUE THREAD

**Issue by evilsoup** [jgm/pandoc#2198]
As in title. I'm using Pandoc 1.14.0.1 on Windows 8.

```markdown
%Test Document
%evilsoup

#Example header {.customclass}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua.
```

If you run  the above through `pandoc -S test.mkd -o test.epub` and have a look at `ch001.xhtml`, you'll see:

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title>Example header</title>
  <link rel="stylesheet" type="text/css" href="stylesheet.css" />
</head>
<body>
<div id="example-header" class="section level1 customclass">
<h1>Example header</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
</body>
</html>
```

As you can see, the class for the `<div>` has been just had the `customclass` added to its automatically-generated class. To clarify, I want this:

```xhtml
<div id="example-header" class="section level1">
<h1 class="customclass">Example header</h1>
```

...and I'm actually getting this:

```xhtml
<div id="example-header" class="section level1 customclass">
<h1>Example header</h1>
```

**Comment by ousia** [comment]
@evilsoup, this behavior seems to be the default in version 1.13.2 too.

I haven’t found any way to disable this default (`--section-divs`).

Just in case it might help, you can format a title such as:

``` html
<div id="example-header" class="section level1 customclass">
<h1>Example header</h1>
```

with the following CSS code:

``` css
.customclass > h1 {
    font-size: 200%;
    font-weight: normal;
    font-style: italic;
}
```

BTW, if sections aren’t contained in divisions, your title would read.

``` html
<h1 id="example-header" class="section level1 customclass">Example header</h1>
```

**Comment by jgm** [comment]
+++ evilsoup [May 31 15 08:04 ]:
>As in title. I'm using Pandoc 1.14.0.1 on Windows 8.
>
>```markdown
>%Test Document
>%evilsoup
>
>#Example header {.customclass}
>
>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
>incididunt ut labore et dolore magna aliqua.
>```
>
>If you run  the above through `pandoc -S test.mkd -o test.epub` and have a look at `ch001.xhtml`, you'll see:
>
>```xhtml
><?xml version="1.0" encoding="UTF-8"?>
><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
><html xmlns="http://www.w3.org/1999/xhtml">
><head>
>  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
>  <meta http-equiv="Content-Style-Type" content="text/css" />
>  <meta name="generator" content="pandoc" />
>  <title>Example header</title>
>  <link rel="stylesheet" type="text/css" href="stylesheet.css" />
></head>
><body>
><div id="example-header" class="section level1 customclass">
><h1>Example header</h1>
><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
></div>
></body>
></html>
>```
>
>As you can see, the class for the `<div>` has been just had the `customclass` added to its automatically-generated class. To clarify, I want this:
>
>```xhtml
><div id="example-header" class="section level1">
><h1 class="customclass">Example header</h1>
>```
>
>...and I'm actually getting this:
>
>```xhtml
><div id="example-header" class="section level1 customclass">
><h1>Example header</h1>

`--section-divs` is automatically selected for EPUB output; this puts
all the attributes that would go on the header on the containing div.

I don't think this is really constraining at all; you can just add a CSS
rule for

    div.customclass h1

instead of

    h1.customclass

**Comment by evilsoup** [comment]
Thanks to both of you @ousia @jgm for pointing out ways to deal with this using CSS.

This behaviour doesn't seem to be well-documented in the Pandoc User Guide to me -- nowhere does it state that the epub writer uses `--section-divs` by default, and that seems like it should be stated in the `--section-divs` definition and also probably the 'Header identifiers in HTML, LaTeX, and ConTeXt' section.

However, since this is intended behaviour and not at all the problem I thought it was, I'm perfectly happy to see this issue closed.

**Comment by ousia** [comment]
> However, since this is intended behaviour and not at all the problem I thought it was, I'm perfectly happy to see this issue closed.

@evilsoup, you can close the issue yourself.

Only the reporter, the project owner or a collaborator can close issues (I’m none of these :smile:).
