### ISSUE TITLE
version mismatch in Hackage

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#2199]
@jgm, https://github.com/jgm/pandoc/releases/latest points to 1.14.0.1 as the latest release, but https://hackage.haskell.org/package/pandoc lists version 1.14.0.2 as the latest version.

Shouldn’t be the version number corrected in Hackage?

Many thanks for your excellent software.

**Comment by jgm** [comment]
Hackage is correct.   I put out a very minor point release,
just bumping some upper dependency bounds, on Michael Snoyman's
request.  I didn't update the github site or pandoc.org.

+++ Pablo Rodríguez [May 31 15 09:06 ]:

**Comment by ousia** [comment]
> Hackage is correct. I put out a very minor point release, just bumping some upper dependency bounds, on Michael Snoyman's request. I didn't update the github site or pandoc.org.

@jgm, does it happen again with version 1.14.0.3? (Although the [link](https://github.com/jgm/pandoc/releases/tag/1.14.0.3) isn’t available.)

**Comment by jgm** [comment]
Should be up to date now.

+++ Pablo Rodríguez [Jun 01 15 07:00 ]:

**Comment by jgm** [comment]
Note:  I don't upload binary packages for fixes like this,
which really only have to do with dependencies.

**Comment by ousia** [comment]
@jgm, now I understand that Hackage has information on version updates first  and also that you don’t release package binaries with no actual code being changed.
