### ISSUE TITLE
Div, Span, customization

### ISSUE THREAD

**Issue by m-ichael** [jgm/pandoc#2204]
## Indeed, div and span allows some customization on the user side. 

~~~
<div class="panorama"><img alt="img name" src="karanfil.jpg"></img><div>This is the caption test.</div></div>
~~~

in the source code would according to css class instructions give an image that say spans the figure to the whole body width ...in html output.
It would also be *not* included in the pdf output, only the caption would survive.

## Second:

~~~
<span style="font-variant:small-caps;">this string will be outputted in smallcaps regardless of the output being html or pdf</span>
~~~

...would be output correctly in pdf and html alike.
Is there a suggestion how to write the first example differently to have the pandoc engine output the image in pdf, or is this a matter of tweaking the template.latex instructions.

The question of course is irrelevant when one fully understands Haskell and the Pandoc library, there must be an easy explanation: the 'div' probably not converted to latex rightly or not at all, or the latex template applied not processing the image for some reason, latex does not throw an error though.  
Which in itself can have many reasons also. 
Is it the Pandoc engine that acts as the impediment?

**Comment by jgm** [comment]
By default, Div doesn't do anything in LaTeX (unless the Div has an id,
in which case a label is added).

Span doesn't do anything in LaTeX either, but pandoc parses `<span
style="font-variant:small-caps;">` as a SmallCaps element,
not a Span.

You can use filters to add desired behavior for specially
marked Div and Span elements in LaTeX.
