### ISSUE TITLE
commonmark format not parsing syntax extensions

### ISSUE THREAD

**Issue by mavenaut** [jgm/pandoc#2212]
I have not exhaustively tested all permutations of syntax extensions against the `commonmark` format but it seems the format is not parsing extensions. Below are two examples of extensions that are sensible use cases and do not generate the expected output.

Using the `mre.md` file
~~~
% The meta title
% The meta author
% The meta date

# The Title
~~~
Executing
~~~
pandoc -f markdown_strict+pandoc_title_block+auto_identifiers -s -t html5 mre.md
~~~
produces
~~~
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <meta name="author" content="The meta author">
  <title>The meta title</title>
  <style type="text/css">code{white-space: pre;}</style>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<header>
<h1 class="title">The meta title</h1>
<h2 class="author">The meta author</h2>
<h3 class="date">The meta date</h3>
</header>
<h1 id="the-title">The Title</h1>
</body>
</html>
~~~
Executing
~~~
pandoc -f commonmark+pandoc_title_block+auto_identifiers -s -t html5 mre.md
~~~
produces
~~~
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<p>% The meta title % The meta author % The meta date</p>
<h1>The Title</h1>
</body>
</html>
~~~

**Comment by jgm** [comment]
The other Markdown formats are all handled by pandoc's
Markdown reader.  CommonMark is handled by a wrapper around
libcmark.  So extensions, for the most part, aren't
supported, though the `hard_line_breaks` extension does
work.

+++ mavenaut [Jun 05 15 22:39 ]:

**Comment by van-de-bugger** [comment]
> CommonMark ... extensions, for the most part, aren't supported ...

Pandoc should print error message "extension xxx is not supported" when user specify option `--read=commonmark+xxx`.

Current behavior (pandoc accepts option but silently ignores all the extensions) is *very* confusing. Today I spent time to understand that few extensions do not work, prepared a test case, was ready to submit a bug… and found this one.
