### ISSUE TITLE
Markdown to Dokuwiki - Syntax Highlighting

### ISSUE THREAD

**Issue by TimKaechele** [jgm/pandoc#2213]
The Markdown to Dokuwiki converts the wrong syntax highlighting code.

Given a markdown input like this.

    ```c
      printf("hello world");
    ```

The dokuwiki output should be this
```
<code c>
  printf("hello world");
</code>
```

but Pandoc converts the given input to this
```
<source lang="c">  printf("hello world");</source>
```

I used `bash version 3.2.57(1)-release (x86_64-apple-darwin14)` while executing this command

```
pandoc bug_report.md -o bug_report.txt -t dokuwiki
```

I use this Pandoc installation

```
pandoc 1.14.0.1
Compiled with texmath 0.8.2, highlighting-kate 0.6.
```

My DokuWiki installation is up to date. 
I am relatively new to DokuWiki, as well as to Pandoc, so maybe I am missing an option, but DokuWiki doesn't understand the Pandoc generated code and displays it like this

![bildschirmfoto 2015-06-06 um 11 14 57](https://cloud.githubusercontent.com/assets/3810945/8019169/bcefdd06-0c40-11e5-9650-46e3e3a11ccf.png)

**Comment by mpickering** [comment]
Here is the relevant code https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/DokuWiki.hs#L166

It seems like it uses `<source>` If it recognises one of the languages and `<code>` if there is no language specified or it does not recognise it.

@claremacrae do you know the reason for this?

**Comment by claremacrae** [comment]
Thanks for copying me in on this. Yes, it's definitely a bug.

I've looked at the current tests, and the only references to `<code>` are in `pandoc/tests/writer.dokuwiki`, and none of them show use of a language name.

There definitely would have been a test, had I considered this case - so apologies, but I believe I just never got as far as implementing it.

I started the implementation as a copy of one of the earlier wiki formats supported by pandoc - so the list of languages (and behaviour) is almost certainly just a hangover from the original code.

Please could someone change it to use `<code>` when a language is given?

In case it helps, this page documents the dokuwiki syntax highlighting: https://www.dokuwiki.org/wiki:syntax#syntax_highlighting

It says that any languages supported by the [GeSHi - Generic Syntax Highlighter](http://qbnz.com/highlighter/) are supported.

**Comment by jgm** [comment]
Tell me if this fix is producing the right output.
