### ISSUE TITLE
Default reference.docx file no long overridden by data-dir

### ISSUE THREAD

**Issue by jkitzes** [jgm/pandoc#2220]
Noticed on OS X Mavericks and Yosemite, Homebrew installation. It appears that somewhere between 1.14 and 1.14.04 (possibly in 1.14.0.1?), a `reference.docx` file placed in the data-dir no longer overrides the default file automatically, although it can still be specified explicitly.

On 1.14.0.4 with `reference.docx` in `~/.pandoc`,

`pandoc -o test.docx test.md`

produces `test.docx` output that does not use the `reference.docx` style, but

`pandoc --reference-docx=$HOME/.pandoc/reference.docx -o test.docx test.md`

works as expected.

With 1.14, both produce the same expected output, using `reference.docx` (although output file has errors, as Release Notes describe).

**Comment by jgm** [comment]
Yes, I realize now that this would have changed with 1.14.
We no longer store reference.docx in the data directory;
instead, we store its individual components and zip them
together on the fly. I think that, for backwards
compatibility, I should set things up so that it looks
for reference.docx before looking for the component files.
This should be pretty straightforward.

+++ Justin Kitzes [Jun 10 15 09:56 ]:

**Comment by jkitzes** [comment]
Thanks, that would be great. In the future, will there be a new preferred method of customizing the docx styles that involves working with the unzipped component files themselves? Or will creating the single `reference.docx` remain the method of customization, even if pandoc treats the default file(s) differently internally?

**Comment by mendelkranz** [comment]
Sorry to jump in, I'm a little confused. I just updated to 1.14 and for some reason many features of the reference.docx aren't coming through. Headers and such work however block quotes aren't rendering and footnotes are appearing as numbers not superscript. 
Is there a different way I should be setting the style of docs now? Or is something else wrong?

**Comment by jgm** [comment]
This should be fixed in 1.14.1.
