### ISSUE TITLE
Binary downloads missing?

### ISSUE THREAD

**Issue by gmp26** [jgm/pandoc#2222]
I'm probably looking in the wrong place :)

The user guide says 'There is a package installer at pandoc’s download page' for both windows and MacOSX, but I only see links to source code downloads there now. I'm looking at
https://github.com/jgm/pandoc/releases/latest

**Comment by jgm** [comment]
I haven't built the binary package yet for the latest
version, but you can find one for version 1.14.0.1.

+++ Mike Pearson [Jun 11 15 06:39 ]:

**Comment by jgm** [comment]
I've added a note to the release page that explains this.
I probably won't build binary packages til the next release (which should be fairly soon).
