### ISSUE TITLE
org-mode: erroneous `file:` prepended to URLs from :results section

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#2227]
When I compile the following project (run the script with the same name as the file, with a dot at the beginning)

https://github.com/ensime/ensime.github.io/tree/master/talks/scaladays15

All the images produced from the ditaa sections have a `file:` prepended to their URL. I had to manually remove this for the slides to work when hosted http://ensime.github.io/talks/scaladays15/

@tarleb

**Comment by tarleb** [comment]
How the org-reader handles links is far from optimal.  One problem is that, in principle, links have to be parsed twice if custom link types are used.  The current link parsing method is broken and requires a complete redesign.  See also #1812 .

**Comment by tarleb** [comment]
Fixed by #3067.

**Comment by fommil** [comment]
nice, I've got a talk coming up so looking forward to this. I should set arch to use the git version of pandoc.

**Comment by fommil** [comment]
damn, it doesn't have `pandoc-git` as an option
