### ISSUE TITLE
Add include, substitution and admonition support reST markup

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#223]
<pre>

Hi!

It would be nice if Pandoc would have support for full reST markup which is
more powerful than e.g. markdown, and with the present suite of 'writers'
it would allow converting input to many output formats.

Sincerely,
Gour

Google Code Info:
Issue #: 130
Author: ggd...@gmail.com
Created On: 2009-02-21T09:48:14.000Z
Closed On: 
</pre>

**Comment by chiffa** [comment]
I would suggest that `..include::` is a critical part of the ReStructuredText and the reason I am working with it.

**Comment by timofurrer** [comment]
What's the state on the `.. include::`` directive?

**Comment by jgm** [comment]
`.. include::` is not yet implemented.

Currently this would require adding a `handleIncludes` function like in the LaTeX reader, and modifying pandoc.hs to run this on the input before passing it to the (pure) LaTeX reader.  This is pretty ugly, though.  A cleaner solution would require #2930, which would allow pure readers to be run with IO (processing includes) or without it.

**Comment by jgm** [comment]
include is now implemented in the `typeclass` branch, which will eventually become pandoc 2.0.

It shouldn't be too hard to implement admonition and substitution as well.

**Comment by jgm** [comment]
We've got admonitions now.

**Comment by jgm** [comment]
And we've had substitutions for a long time. I think this issue can now finally be closed!

**Comment by mcepl** [comment]
> include is now implemented in the typeclass branch, which will eventually become pandoc 2.0.

There is no ``typeclass`` branch in the current repo. Where can I find ``.. include::`` honoring code for testing?

**Comment by mb21** [comment]
I think the typeclass branch has been merged into current master...

**Comment by mcepl** [comment]
And does the release ``1.19.2.1`` contain it as well or do I have to build from the git checkout?

**Comment by iandol** [comment]
You can try the nightly build: https://github.com/pandoc-extras/pandoc-nightly

**Comment by Gim6626** [comment]
Got pandoc v1.19.2.4, no "include" support. Since which version it was added?

**Comment by mb21** [comment]
Just get the newest pandoc from https://github.com/jgm/pandoc/releases

**Comment by saurabhnanda** [comment]
Two question regarding the `include` directive:

- Is is possible to include a function that resolves relative paths, else the directlve becomes brittle when (a) you're processing multiple RST documents from a deeply nested directory tree, or (b) moving files around.
- is it possible to use the `include` directive to include external **code snippets** such that pandoc recognizes them as code snippets and parses / renders them accordingly?
