### ISSUE TITLE
[rst] correct image link doesn't work with pandoc

### ISSUE THREAD

**Issue by mcepl** [jgm/pandoc#2231]
When having this rst document:
```rst
So, looking at interesting presentation on `Wordpress APIs`_, I have hit
on this slide:

.. image:: http://2.bp.blogspot.com/_de4d8QAtRzI/TI-Tb7Kx6TI/AAAAAAAAAtM/-NdAIWRCcAA/s400/atompub-depression.png
    :scale: 66%
    :align: center
    :target: http://2.bp.blogspot.com/_de4d8QAtRzI/TI-Tb7Kx6TI/AAAAAAAAAtM/-NdAIWRCcAA/s1600/atompub-depression.png

.. _`Wordpress APIs`: http://www.slideshare.net/josephscott/wordpress-apis
```
I get with `rst2html` perfect HTML which [works](http://mcepl.fedorapeople.org/tmp/atompub-depression-rst2html.html), but `pandoc` generates broken HTML which [doesn't show the image](http://mcepl.fedorapeople.org/tmp/atompub-depression-pandoc.html).

According to [the spec](http://docutils.sourceforge.net/docs/ref/rst/directives.html#image) I think that my syntax is correct.

What's the problem?

@wzpan , I think you may be interested in this bug. It breaks your https://github.com/wzpan/hexo-renderer-pandoc/issues/new as well.

**Comment by jgm** [comment]
What version of pandoc are you using?  I just tried with 1.14.0.4 and it worked fine.

**Comment by mcepl** [comment]
> What version of pandoc are you using? I just tried with 1.14.0.4 and it worked fine.

pandoc-1.12.3.1-1.el7.x86_64
