### ISSUE TITLE
Label with "space" for the document-internal reference is handled inconsistently, and cannot be linked/searched successfully.

### ISSUE THREAD

**Issue by zephyrus00jp** [jgm/pandoc#2233]
Label with "space" for the document-internal reference is handled inconsistently, and cannot be linked/searched successfully.

Thank you for making the great tool available.

I have noticed a problem with pandoc.
    
Label with "space" for the document-internal reference is handled inconsistently, and cannot be linked/searched successfully.

> %20 vs "-"

Where such a label is referenced as the "#labelwithspace", the space
is quoted as "%20".  Fine.

 However, where it is defined as the id part of H1, H2, H3,  ... header 
the space character is replaced with "-".

>    E.g.
>    "#System%20Build%20Procedures" vs "system-build-procedures" (as id)

Hence they will never match. Thus we can't use the document-internal
reference effectively if we have a space character in the label.

I have a short example that exhibits the problem, and seeing is
believing and easier to understand.

Here is the conversion input and output that exhibits the problem.
Conversion is done by "Try pandoc!" web page.

Partial Input

     ==== begin quote ====
     ___
     ## System Construction (Cygwin/Linux shared use)
     ___
    
     * [1. System Build Procedures](#System Build Procedures)
     * [2. Build for Debugging](#Build for Debugging)
     * [3. Build Details](#Build Details)
     * [4. Makefile Settings](#makefile-settings)
     
     ___
     
     ### 1. System Build Procedures
     
     ==== end quote ====

AFTER 	conversion to HTML using
pandoc (pandoc 1.12.4.2 locally)
AND "Try pandoc!" page,
I get the following output and the problem.

Please note that the href="..." contains "%20" for quoting whitespace.
But the id defined for the first header, "1. System Build Procedures"
is "system-build-procedures" as opposed to "#System%20Build%20Procedures".
So searching for "#System%20Build%20Procedures" in this document never find the match
because "%20" is NOT "-".

     ==== begin quote ====
     
     <hr />
     <h2 id="system-construction-cygwinlinux-shared-use">System Construction (Cygwin/Linux shared use)</h2>
     <hr />
     <ul>
     <li><a href="#System%20Build%20Procedures">1. System Build Procedures</a></li>
     <li><a href="#Build%20for%20Debugging">2. Build for Debugging</a></li>
     <li><a href="#Build%20Details">3. Build Details</a></li>
     <li><a href="#makefile-settings">4. Makefile Settings</a></li>
     </ul>
     <hr />
     <h3 id="system-build-procedures">1. System Build Procedures</h3>
     
    
     ==== end quote ====

Incidentally, the internal reference to "4. Makefile Settings" works. 
This is because the label in this case is "makefile-settings", and there is no space character and
quotation does not happen. So we can jump to "4. Makefile Settings".

I hope this bug report makes the tool more robust and useful.

TIA

**Comment by jgm** [comment]
I don't think this is a bug.  There's a procedure for
converting header titles into IDs (and this, as you note,
replaces spaces with hyphens).

However, when someone specifies an ID explicitly, as in
your links, we shouldn't be transforming them to something
else.

In your case there are some simple solutions.

You could just write:

    System Build Procedures](#System-Build-Procedures)

Or you could take advantage of `implicit_header_references`
(see the manual) and write

    [1. System Build Procedures]

which will automatically create a link to the section
with the same name.  (If you don't want the `1.`, however,
you'll need to use the first approach.)

**Comment by zephyrus00jp** [comment]
Hi,

Thank you for your quick response, and
thank you for making this tool publicly available.

On 2015/06/16 2:30, John MacFarlane wrote:
> I don't think this is a bug. There's a procedure for
> converting header titles into IDs (and this, as you note,
> replaces spaces with hyphens).

Please let me explain how we found out about this feature.
Then you will see why we thought this was a bug.

Actually, the problem was found during a translation of Japanese 
document that used MD to expand it into HTML.
We translated the document into English.

Japanese language does not use "space" to separate syntactic entities.
We just write them next to each other.

So　I am making up an example here.
The following is a translation of "1. System Build Procedures".

[1. システムのビルド方法](#システムのビルド方法)

Please note that there is no space in the ID part.
So we did not hit this "%20" vs "-" issue at all in our Japanese 
documentation.

We asked a translation agency to translate the MD document into English.
They did a good job of translating the sentences and also
handled MD to the point that I could run the resulting English MD 
documents and obtain reasonably good English documents to begin 
proof-reading.

Except:

When I click on the link to in-document references, it did not work.
So I started to investigate thinking that the translation agency screwed 
up MD syntax or something.
(Handling formatter syntax is difficult during translation, and
I have had issues with NRFOFF/TROFF, TeX, XML documents before during
translation work.)

Then I realized there does not seem to be any problem in MD syntax at 
all. The translation agency meticulously handled MD constructs.
So what is the problem?
So I began comparing HTML output when I noticed the problem.
The issue arises because the English translation of the above MD 
construct became as follows.

[1. System Build Procedures](#System Build Procedures)

Yeah, right. Now there are spaces in the ID part, and the rest is as I 
described in the original "bug" report.

I have a few options.

(a) Tell the translation agency to put in "-" as you suggest, but
this is an added burden both on the translation agency (who may not have 
a clue on the intricacies of MD) and on us, who needs to check
the resulting MD document carefully anyway.

(b) Tell the Japanese authors of MD documents that, in the future, they 
ought to use "ASCII" only IDs without spaces for MD constructs like this.
But this makes the document very ugly IMHO :-(

I thought that if pandoc can handle the "space" substitution uniformly
wither by using "-" or "%20", we are better off.

That is why one of my colleagues and I thought this was a bug.

>
> However, when someone specifies an ID explicitly, as in
> your links, we shouldn't be transforming them to something
> else.
>
> In your case there are some simple solutions.
>
> You could just write:
>
> System Build Procedures](#System-Build-Procedures)

Of course.
Unless pandoc handles space as we wanted, this may be the only 
alternative. But this makes the document pretty ugly in Japanese 
documents. As long as the result is correct, we can live with it.

> Or you could take advantage of `implicit_header_references`
> (see the manual) and write
>
> [1. System Build Procedures]
>
> which will automatically create a link to the section
> with the same name. (If you don't want the `1.`, however,
> you'll need to use the first approach.)
>

Some of the documents explicitly avoided the use of "1." and so
that is why the use of user-supplied ID.

I hope now you understand why some users may think this "feature" is a bug.

TIA

**Comment by jgm** [comment]
I understand why, for this particular purpose, you'd like it
if pandoc did a space-to-hyphen transformation on links
beginning with `#`.  But I can guarantee you that there are
a bunch of other people who would not be happy if we did
that -- they write a space because they want a space.

**Comment by zephyrus00jp** [comment]
Thank you for the comment.

> I understand why, for this particular purpose, you'd like it if pandoc did a space-to-hyphen 
> transformation on links beginning with `#`. But I can guarantee you that there are a bunch of other 
> people who would not be happy if we did that -- they write a space because they want a space.

Of course. Although I don't understand the background of why people want space there intenttioanlly, I certainly understand the change of behavior of pandoc will break such documents.

I will tell my Japanese authors to use prosaic IDs without spaces such as "H-A-10", "H-A-20", etc.
in the future so that things will not break during translation. (Prosaic IDs like above won't get translated by mistake.)

Thank you again.

**Comment by mpickering** [comment]
Another option would be to write a filter which performs these
normalisation steps you are describing. Examples can be found here -
http://pandoc.org/scripting.html and on the wiki.
