### ISSUE TITLE
[-Smith2000] is rendered as (???) in MLA csls

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#2234]
I'm using pandoc 1.14 and note that when I switch from `apa.csl` to 
`modern-language-association.csl` citations such as "[-Smith2000abc]" 
are rendered as (???) in the resulting HTML. 

For MLA, nothing should be rendered in these instances. I do note that 
page numbers work: "Williams [-@Williams1976kvc, p. 9] continued" -> 
"Williams (9) continued" . 

You might ask, why not just write "Smith2000abc"? Then, when I use a 
note system nothing would show. (Also, sometimes I use the authors first 
name.) 

Test is in [email](https://groups.google.com/forum/#!msg/pandoc-discuss/2_UVF2if0VQ/wy9-GB13UsEJ).

**Comment by jgm** [comment]
Closing in favor of jgm/pandoc-citeproc#56
