### ISSUE TITLE
Superscripts/Subscripts markdown extension syntactic markers appear literally in plain text

### ISSUE THREAD

**Issue by dabd** [jgm/pandoc#2237]
Converting a markdown document with a superscript to plain text shows the symbols in the resulting document.
Ex: 16^th^ of June appears as 16^th^ of June.  
I believe it would be nicer to suppress the ^?  On the other hand it might cause problems converting back from plain text...

**Comment by jgm** [comment]
+++ dabd [Jun 16 15 02:28 ]:
>   Converting a markdown document with a superscript to plain text shows
>   the symbols in the resulting document.
>   Ex: 16^th^ of June appears as 16^th^ of June.
>   I believe it would be nicer to suppress the ^? On the other hand it
>   might cause problems converting back from plain text...

We don't convert back, so yes, I agree, they should probably
be suppressed. (Same with super.)
