### ISSUE TITLE
Image - figure specs

### ISSUE THREAD

**Issue by m-ichael** [jgm/pandoc#2240]
Figures - images, theoretical remark, no examples, 

In Latex there is minute control over the size and positioning of images. Latex goes about this by defining image kinds(environments): non-exhaustively: \marginfigure , \figure , \figure* ...and then allows for "options" to exacly define sizes, height and width, caption and title specs, from fonts to flow.
Html defines an image container, an image, a float, a caption thus allowing to "box" every image element within the page and leave the formatting of every tag to css.

To use Pandoc to convert to html the solution is to use raw html and as a second step to define the element within css.
To run Pandoc on the same source to output pdf, of course the raw html is lost as an instruction when Pandoc writes to pdf in a second step of processing.

Images or figures and how they are handled do not allow for distinction in the source as to size and position on the page. Minimally there should be allowance for full page size, margin, and text - column as in latex when outputting to pdf. Basically Pandoc should have code for margin, text column(body in html) and full-width. 
At the same time having the source being parsed to different tags into the html output, tags that then can be formatted in css. This should permit not to loose out on the promise of one source format to be written to more then one output format.

How to go about this cleanly, that of course is the matter, then there is more then html and pdf to consider, though epub seems like a complacent output format.
The necessity though is evident, any sophisticated document needs positioning and sizing of images, figures, elements as compared to text.  Text can be finegrained by Pandoc to the level of fonts, the positioning can be done within the templates, for figures-images there is only definition so the formatting of that definition in the appropriate place, the template concerned is restricted to one single choice for now.   

Did i miss something, like putting the image into a footer to position an image, like using verbatim, define it as full width in the templates and putting an image inside?

**Comment by jgm** [comment]
Please post this instead on pandoc-discuss (googlegroups).
That is the place for open-ended discussion of pandoc
features and extensions, and your message will be seen
by many more people.
