### ISSUE TITLE
pandoc ignores <w:smartTag> when converting docx

### ISSUE THREAD

**Issue by yanxyz** [jgm/pandoc#2242]
My docx have such content:

```
static void Main() {...}
```

After converting it to markdown,  the result does not have the word "Main". Then I unpack this file and look into the document.xml:

``` xml
    <w:p w:rsidR="00E438A8" w:rsidRDefault="00E438A8" w:rsidP="00E438A8">
      <w:pPr>
        <w:pStyle w:val="Code" /></w:pPr>
      <w:r>
        <w:t xml:space="preserve">static void </w:t>
      </w:r>
      <w:smartTag w:uri="urn:schemas-microsoft-com:office:smarttags" w:element="place">
        <w:r>
          <w:t>Main</w:t>
        </w:r>
      </w:smartTag>
      <w:r>
        <w:t>() {...}</w:t>
      </w:r>
    </w:p>
```

If there is no <w:smartTag> then result is ok. 

I put a test file on [google drive](https://drive.google.com/file/d/0B1ztZOBwb6ZdbG9kdTlpZHF1Z28/view?usp=sharing)

**Comment by jgm** [comment]
@jkr - would it be easy and safe to respond to `smartTag` by just moving inside and parsing whatever is there?

**Comment by jkr** [comment]
Yep, I think so. Let me do a bit more reading up on the tag (it's even
more undocumented than most) and make sure, but that seems to make sense.
