### ISSUE TITLE
Error with symbol n° on latex

### ISSUE THREAD

**Issue by edusantana** [jgm/pandoc#2245]
Hi, 

When I was converting a text with portuguese, there was a text:

`como exemplo da lei de cotas n° 8213/91`

With Latex I got an error about this symbol:

```
! Package inputenc Error: Unicode char \u8:° not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.562 ...mpresas, como exemplo da lei de cotas n°
                                                   8213/91 para
```

I suggest replace the symbol `°` with `\textsuperscript{o}` with latex output.

Replacing it with `º` works too.

**Comment by jgm** [comment]
Try with `--latex-engine=xelatex`.

**Comment by u-fischer** [comment]
Load the textcomp package. This here works fine in latex

~~~~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\begin{document}
  como exemplo da lei de cotas n° 8213/91 para 
\end{document}
~~~~~~

(it maps ° to \textdegree, but it would be easy to change this
definition)
