### ISSUE TITLE
-f markdown-markdown_in_html_blocks doesn't work as expected

### ISSUE THREAD

**Issue by nkalvi** [jgm/pandoc#2246]
F.ex. 

`echo '<div>*testing*</div>' | pandoc -f markdown-markdown_in_html_blocks`
produces
```
<div>
<p><em>testing</em></div></p>
```
instead of
`<div>*testing*</div>`

**Comment by jgm** [comment]
You also need to disable `native_divs` if you want it to
work with div tags.

+++ nkalvi [Jun 26 15 14:55 ]:

**Comment by nkalvi** [comment]
Thanks @jgm. 

 `native_divs`'s indirect effect when turning the `markdown_in_html_blocks` option off wasn't quite apparent from
>#### Extension: `native_divs` ####
>
>Use native pandoc `Div` blocks for content inside `<div>` tags.
For the most part this should give the same output as
`markdown_in_html_blocks`, but it makes it easier to write pandoc
filters to manipulate groups of blocks.

I can now see that one needs to turn off `native_spans` also when relevant.

Including a note about this in the documentation may be helpful to new users.

**Comment by nkalvi** [comment]
BTW, did you notice the strange output in the first post?
>`<div>
<p><em>testing</em></div></p>`

**Comment by jgm** [comment]
+++ nkalvi [Jun 26 15 16:22 ]:
>   BTW, did you notice the strange output in the first post?
>
>     <div>
>     <p><em>testing</em></div></p>

No, sorry, I didn't.  That looks wrong.  This needs more
investigation.
