### ISSUE TITLE
Support for nested slides in Reveal.js is broken

### ISSUE THREAD

**Issue by vick08** [jgm/pandoc#2248]
Seems like nested slides will break if the following format is used:

# morning

## breakfast

- drink green smoothie
- have some coffee

# afternoon

- skip food, I am on a diet

# evening

## dinner

- eat pizza
- follow up with some wine
- or vice versa

In other words, if a level-1 slide is introduced amidst the nested ones.

**Comment by KurtPfeifle** [comment]
It's documented: level 1 slides cannot have any "content", only headlines:

> *"Headers above the slide level in the hierarchy create "title slides," which just contain the section title and help to break the slide show into sections*"

**Comment by vick08** [comment]
Agree, however, this is not how Reveal.js works. There you can intermix level-1 slides with content with other level-1 slides that include nested ones.
Should this issue be a feature request then?

**Comment by jgm** [comment]
Please see #2157 and the comments there.
Pandoc doesn't prevent you from getting a 2D reveal.js slide show; you just have to do it differently.

**Comment by KurtPfeifle** [comment]
> *"Agree, however, this is not how Reveal.js works."*

However, this is how ***Pandoc*** works when generating Reveal.js.

If this is not good enough for you, then you'll have to resort into editing your generate RevealJS-HTML manually to add more bells and whistles.

Pandoc is pretty excellent in what it supports in the various output formats. However, probably ***none*** of each output format will support ***all*** features of that specific format...
