### ISSUE TITLE
More docx corruption

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#2249]
With current master, I'm getting corrupted docx when I try to use a modified reference.docx.
(Modification consists of changing the font in Normal.)
We need to determine if this is a regression, and if so where it came in.

**Comment by jgm** [comment]
Replacing settings.xml with a version from a working docx fixed the corruption.
So, I conjecture that this may have something to do with #2037/6ba37909fee80c9ee910644c25dbca1561056ccd

**Comment by jgm** [comment]
However, reverting that commit did not help.

**Comment by jgm** [comment]
Confirmed that the problem does not exist with 1.14.0.1.

**Comment by nkalvi** [comment]
@jgm, could you please post the corrupted reference.docx somewhere - I'd like to take a look at it.

**Comment by jgm** [comment]
I have figured out how to fix this.  It's due to my most recent docx commit.

**Comment by nkalvi** [comment]
Very good!
