### ISSUE TITLE
markdown_github omits YAML metadata

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2251]
GitHub [supports YAML metadata](https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents), but this is omitted by Pandoc 1.14.0.4; I would expect this to be included when using the standalone option. The following returns only a blank line:

```shell
$ pandoc -t markdown_github -sS << EOT
> ---
> title: Test
> ...
> 
> EOT
```

**Comment by jgm** [comment]
The YAML metadata didn't seem to work when I tried it in the pandoc wiki sandbox...

**Comment by adunning** [comment]
I think that it is supported only for independent files ([example](https://github.com/adunning/early-lives-charlemagne/blob/master/einhard-handout.md)), and only when hyphens are used to close the block.

**Comment by jgm** [comment]
Since it doesn't work in all contexts, I think it's best to leave it out of the `markdown_github` package, though you can always to `-t markdown_github+yaml_metadata_block`.  (Note that this uses `...` to close the metadata.  Life's too short to keep up with all the variations.  Use sed.)
