### ISSUE TITLE
Maruku markdown output support

### ISSUE THREAD

**Issue by ony** [jgm/pandoc#2253]
See [Maruku's Markdown syntax](https://github.com/bhollis/maruku/blob/master/docs/markdown_syntax.md). Though I can use github version it still requires some later post-editing.
So it will be good to see this among others formats for writing.

P.S. Since this is kind of templating format that supports inline HTML I don't think it is reasonable to implement reader (at least at this moment).

**Comment by jgm** [comment]
What, specifically, doesn't work in Maruku with existing markdown output?

**Comment by jgm** [comment]
Perhaps we could come up with a list of the extensions it supports, using existing extensions?
https://hackage.haskell.org/package/pandoc-1.14.1/docs/src/Text-Pandoc-Options.html#githubMarkdownExtensions

**Comment by ony** [comment]
Hmm `markdown_strict` produce what I need (transform github to maruku markdown).

**Comment by jgm** [comment]
You should either close this issue, or, if you want pandoc to have a `markdown_maruku` output format, come up with a comprehensive list of the extensions it supports (using the list in the README or the Options file I linked to).
