### ISSUE TITLE
Hard line break adds blank space in odt

### ISSUE THREAD

**Issue by mchladek** [jgm/pandoc#2254]
When converting from markdown to odt using the command `pandoc -f markdown -t odt -o foo.odt bar.md` in pandoc 1.14.04 (and 1.14.1), any hard line breaks in the markdown source are written in odt as a carriage return plus a space. This means there will be a space at the beginning of the second line when there shouldn't be.

Input used:
```markdown
Hard break using backslash escape:

This is line one.\
This is line two.

Hard break using two spaces at end of line:

This is line one.  
This is line two.
```
Output given:

    Hard break using backslash escape:
    
    This is line one.
     This is line two.
    
    Hard break using two spaces at end of line:
    
    This is line one.
     This is line two.

Output expected:

    Hard break using backslash escape:
    
    This is line one.
    This is line two.
    
    Hard break using two spaces at end of line:
    
    This is line one.
    This is line two.

I've tracked down the reason this happens. The OpenDocument writer generates the following from the input:

```xml
<text:p text:style-name="Text_20_body">Hard break using backslash
escape:</text:p>
<text:p text:style-name="Text_20_body">This is line
one.<text:line-break />
This is line two.</text:p>
<text:p text:style-name="Text_20_body">Hard break using two spaces at
end of line:</text:p>
<text:p text:style-name="Text_20_body">This is line
one.<text:line-break />
This is line two.</text:p>
```
The ODT writer then parses the carriage return after `<text:line-break />` as a space, so the ODT document generated from the input looks like this:

```xml
<text:p text:style-name="Text_20_body">Hard break using backslash escape:</text:p>
<text:p text:style-name="Text_20_body">This is line one.<text:line-break/> This is line two.</text:p>
<text:p text:style-name="Text_20_body">Hard break using two spaces at end of line:</text:p>
<text:p text:style-name="Text_20_body">This is line one.<text:line-break/> This is line two.</text:p>
```
The space between `<text:line-break/>` and `This is line two.` is the reason for the added space at the beginning of the line. In the `OpenDocument.hs` writer, the line break is written using:

```haskell
 | LineBreak <- ils = return $ selfClosingTag "text:line-break" [] <> cr
```
Removing `<> cr` fixes the issue. Didn't make a pull request because I'm not sure if this will break anything else the OpenDocument writer is used for or if it breaks the OpenDocument standard.

**Comment by jgm** [comment]
Go ahead and submit a PR for this.  (`tests/writer.opendocument` may also need changing.)
