### ISSUE TITLE
[documentation improvement] List of all Markdown extensions enabled by default

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2256]
It would be nice to have a list of all Markdown extensions which are enabled for Pandoc's Markdown by default.

The manpage for `pandoc_markdown` lists the extensions which are enabled for `markdown_{github,phpextra,mmd,strict}`. It should give a similar list for Pandoc's Markdown.

Also, it should list (at one place, comprehensively) all potential extensions which are *disabled* by default in Pandoc's Markdown, and which need the use of explicit `+extension_name` for activation.

**Comment by jgm** [comment]
+++ Kurt Pfeifle [Jul 01 15 12:45 ]:
>   It would be nice to have a list of all Markdown extensions which are
>   enabled for Pandoc's Markdown by default.
>
>   The manpage for pandoc_markdown lists the extensions which are enabled
>   for markdown_{github,phpextra,mmd,strict}. It should give a similar
>   list for Pandoc's Markdown.

It does.  All the ones that aren't in the section entitled
"Non-pandoc extensions" are pandoc extensions.

>   Also, it should list (at one place, comprehensively) all potential
>   extensions which are disabled by default in Pandoc's Markdown, and
>   which need the use of explicit +extension_name for activation.

"Non-pandoc extensions"

**Comment by KurtPfeifle** [comment]
After deleting my previous man page versions (dunno how long they were installed there), and creating new ones with 1.15 I can clearly see what you mean  :-)

**Comment by jgm** [comment]
hopefully the new system will keep installed man pages up to
date.

+++ Kurt Pfeifle [Jul 02 15 10:01 ]:
