### ISSUE TITLE
User privilege regression in 1.15

### ISSUE THREAD

**Issue by graceej** [jgm/pandoc#2259]
On attempting to install the latest version (1.15) on Windows I found that I could no longer do so without  administrator privileges even when using the “Advanced” option.

Going back to an earlier version (1.13.1) did allow installation as a local user.  It looks like there has been a regression regarding what the installer requires.

**Comment by nkalvi** [comment]
I'm sorry to hear that. Which version of Windows did you test this under? Ill look into it later tonight.

**Comment by jgm** [comment]
I can confirm this - just tested with a non-admin account on Windows 7.
It asked for the admin password at the point where it displayed information about the package (code-signing info) and asked whether I wanted to allow the program to make changes to the computer.
Going in through Advanced and selecting a user install explicitly made no difference.

**Comment by jgm** [comment]
This change
https://github.com/jgm/pandoc/commit/4df8c32a53844f431fc98265840b1306c7e1553b
allowed the package to be installed by a non-privileged user, but now we no longer have the option of a systemwide install (even in Advanced...).  So, this isn't a good solution.  @nkalvi please feel free to revert this change if you find something better.

**Comment by jgm** [comment]
@nkalvi also building on Windows is currently broken due to man page creation issues.
I'm working on that.  To work around this, you can comment out these two lines in Setup.hs:
```
    , postBuild = makeManPage
    , postCopy = installManPage
```
Comment them out by putting `--` at the beginning of each line.

**Comment by nkalvi** [comment]
Thanks @jgm. I'll look at the options later today.

**Comment by jgm** [comment]
man page issue should now be fixed

**Comment by nkalvi** [comment]
@jgm Could you try with this updated wxs here: https://gist.github.com/nkalvi/28e4687497212abe1023

Based on https://msdn.microsoft.com/en-us/library/windows/desktop/dd408068(v=vs.85).aspx
I added the following (and removed `InstallPrivileges="limited"`)
```xml
    <Property Id="ALLUSERS" Value="2" Secure="yes" />
    <Property Id='MSIINSTALLPERUSER' Value='1' />
```

I've tested it under Windows 8.1 as a standard user,  selecting default "per user" install (installed without any prompt) and "per machine" install (for which you will get the admin prompt).

@graceej could you please test with this change if possible?

**Comment by jgm** [comment]
Works well for me.  Just one thought:  when you select
"Install for all users," could we have the default path
be C:\Program Files\Pandoc\ instead of
C:\[USERDIR]\AppData\Local\Programs\Pandoc?  The latter
doesn't really make sense as a default for a per-machine
install.

**Comment by nkalvi** [comment]
Yes, I agree. I'll change the default later tonight.

**Comment by nkalvi** [comment]
@jgm Could you try this updated version when you have time: https://gist.github.com/nkalvi/28e4687497212abe1023

I've tested it as standard and admin users under Windows 8.1 (64-bit).
All-users install location now defaults to 
*[TARGETDIR]Program Files (x86)\Pandoc\ 
(Program Files\Pandoc\ under 32-bit)*.

BTW, it is best not to insert line-breaks in long text values (such as the value for `WIXUI_EXITDIALOGOPTIONALTEXT`).

**Comment by jgm** [comment]
Can you confirm that the binary I've been providing 32-bit?  (I can't recall
now which version of ghc I've been using.)

+++ nkalvi [Jul 06 15 23:49 ]:

**Comment by nkalvi** [comment]
@jgm It is 64-bit. I have to figure out why the installer sees it otherwise (and fix it).

**Comment by nkalvi** [comment]
@jgm Could you try this updated version: https://gist.github.com/nkalvi/28e4687497212abe1023
Also in this version, when 'Per Machine' installation is chosen, system path is updated instead of user's path.

Platform needs to be specified in *make-windows-installer.bat*:
```
candle -dVERSION=%VERSION% -arch x64 pandoc.wxs
```


I've tested it under Windows 8.1 (64-bit). I currently don't have a 32-bit system to test it.
Please let me know if you want further testing.

**Comment by nkalvi** [comment]
@jgm I was wrong about the versions you've been providing - look like they are 32-bit (at least for 1.13.2).
 (I realized now that I was looking at the locally built version).

The updated wxs above can be used for both 32 and 64-bit builds (by specifying the platform in `candle`'s command. It would be nice to provide both 32 and 64 bit binaries.

**Comment by jgm** [comment]
Great, it seems to work in my tests as well!

**Comment by jgm** [comment]
+++ nkalvi [Jul 09 15 21:19 ]:
>   [1]@jgm I was wrong about the versions you've been providing - look
>   like they are 32-bit (at least for 1.13.2).
>   (I realized now that I was looking at the locally built version).
>
>   The updated wxs above can be used for both 32 and 64-bit builds (by
>   specifying the platform in candle's command. It would be nice to
>   provide both 32 and 64 bit binaries.

I've never actually had anyone request 64 bit binaries or
say that the 32 bit binaries were inadequate for their
needs.  So, I'm inclined to keep the status quo -- it's a
lot easier just to have to build one version for Windows.

**Comment by nkalvi** [comment]
I agree. Keeping it simple is good.
