### ISSUE TITLE
Readers should be consistent in transforming underline

### ISSUE THREAD

**Issue by hftf** [jgm/pandoc#2264]
Pandoc currently supports the following input formats:

| Input | Output of underline (if exists) |
| --- | --- |
| CommonMark | no underline |
| Haddock | no underline |
| Markdown | no underline |
| Native | no underline |
| OPML | no underline |
| RST | no underline |
| TWiki | no underline |
| DocBook | underline stripped |
| Epub | underline stripped |
| HTML | underline stripped |
| LaTeX | unless `--parse-raw`, underlined text is [deleted](https://github.com/jgm/pandoc/blob/79764df2d5c75c63b92613316fcc8a9b8379f8cc/src/Text/Pandoc/Readers/LaTeX.hs#L429); else RawInline |
| MediaWiki | underline [kept](https://github.com/jgm/pandoc/blob/79764df2d5c75c63b92613316fcc8a9b8379f8cc/src/Text/Pandoc/Readers/MediaWiki.hs#L549) as RawInline |
| Docx | underline [converted](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/Docx.hs#L275-L276) to _Emph_; impl. in #1474 |
| Org | underline [converted](https://github.com/jgm/pandoc/blob/79764df2d5c75c63b92613316fcc8a9b8379f8cc/src/Text/Pandoc/Readers/Org.hs#L1289-L1291) to **Strong** |
| Textile | underline [converted](https://github.com/jgm/pandoc/blob/79764df2d5c75c63b92613316fcc8a9b8379f8cc/src/Text/Pandoc/Readers/Textile.hs#L411) to _Emph_; impl. in 5932d90 |
| Txt2Tags | underline [converted](https://github.com/jgm/pandoc/blob/79764df2d5c75c63b92613316fcc8a9b8379f8cc/src/Text/Pandoc/Readers/Txt2Tags.hs#L392-L393) to _Emph_ |

Since there is no Underline-like type yet, I suggest making the behavior among input formats consistent. I think it would be best if Readers did not convert underlines to Emph or Strong, since there is no way to tell the difference between an actual Emph or Strong and one converted from underline:

<pre>
$ cat &lt;&lt;EOF | pandoc -f textile -t html
*_bold and italic_*

+_underline and italic?_+
EOF
&lt;p&gt;&lt;strong&gt;&lt;em&gt;bold and italic&lt;/em&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;<b>&lt;em&gt;&lt;em&gt;</b>underline and italic?<b>&lt;/em&gt;&lt;/em&gt;</b>&lt;/p&gt;

$ cat &lt;&lt;EOF | pandoc -f org -t html
/*bold and italic*/

*bold and _underline?_*
EOF
&lt;p&gt;&lt;em&gt;&lt;strong&gt;bold and italic&lt;/strong&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;<b>&lt;strong&gt;</b>bold and <b>&lt;strong&gt;</b>underline?<b>&lt;/strong&gt;&lt;/strong&gt;</b>&lt;/p&gt;
</pre>

If not, would it be possible for Pandoc filters to be able distinguish between them?

**Comment by abnerlee** [comment]
Why not export as `Underline`, and make writers decide the output.

Since `Underline` is still widely used in many rich text format, why not make it an inline type

**Comment by jgm** [comment]
See discussion at
https://groups.google.com/d/msg/pandoc-discuss/o98bsCVZ-2w/3RGbzdS0MWcJ
(You may want to add your view there.)

+++ AbnerLee [Apr 24 16 02:02 ]:
