### ISSUE TITLE
org source block header arguments break syntax highlighting

### ISSUE THREAD

**Issue by jo-tham** [jgm/pandoc#2269]
Hi, 

I searched and haven't seen this reported in other open/closed issues. Let me know if I missing something here.

I am running pandoc as follows

    pandoc test.org --from=org --to=html5 --standalone --highlight-style=espresso > test.html

test.org contains:

    #+begin_src python :noeval
    a = [i for i in range(10)]
    print(a) 
    #+end_src

    #+begin_src python
    a = [i for i in range(10)]
    print(a)
    #+end_src

Code highlighting works *only* if no header arguments are specified after language identifier. Otherwise the result has syntax highlighting.

here's a veiw of the html conversion on similar test.org
![example](https://cloud.githubusercontent.com/assets/7353689/8505496/0e6db64c-21b5-11e5-986b-44f26e91a456.png)

Is this known? What is the cause?

**Comment by jgm** [comment]
The code has:

``` haskell
  opts <- option [] $ enclosedByPair '[' ']' inlineBlockOption
```

So, it's expecting the options to be enclosed in square brackets.  I don't know anything about Org-mode, so maybe this is wrong, but that's why this is happening.  @tarleb may be able to help.

**Comment by jo-tham** [comment]
Thank you for that info - this clears some things up.

Indeed with **inline** code blocks in org mode, the 'header' arguments are enclosed in square brackets

    src_haskell[:exports both]{fac 5}

I have not seen it anywhere in the docs before, but arguments in code **blocks** *can* be enclosed in square brackets. I can evaluate the below example in org successfully.

    #+begin_src sh [:results verbatim drawer replace output]
    date
    #+end_src

However, it doesn't seem to resolve this bug. E.g., the following code blocks, which include cases with and without `[]`, do not get syntax highlighting

    #+begin_src sh :noeval
    echo "$HOME"
    #+end_src

    #+begin_src sh [:noeval]
    echo "$HOME"
    #+end_src

While these ones *do* convert with syntax highlighting

    #+begin_src sh :var data1=1
    echo "$data1"
    #+end_src

    #+NAME: test
    #+HEADERS: :noeval
    #+begin_src sh
    echo "$HOME"
    #+end_src

This is quite inconsistent.

Chances are, using the #+HEADERS option is the viable workaround and probably good practice for org users, but it would be nice to have this be more accurate in general.

I think I will try #+HEADERS for a while, and if I find it cumbersome, well... maybe there is a fix by then. Otherwise I can try to grok some haskell...

**Comment by jgm** [comment]
I don't know anything about org mode.
But the current Org reader code assumes that an "org arg key" (like `:var`) will have some data after it.
That's why it runs aground on `:noeval` with nothing following.
@tarleb can you comment?

**Comment by tarleb** [comment]
As @jgm pointed out, the code was written under the faulty assumption that each header argument is followed by a value.  I'll patch things up (might need a week or two).

**Comment by jo-tham** [comment]
Thanks, @tarleb!

**Comment by jo-tham** [comment]
:+1:

thanks!
