### ISSUE TITLE
TeX -> EPUB: pandoc doesn't recognise unit commands

### ISSUE THREAD

**Issue by lblblb** [jgm/pandoc#2273]
Hi,
it seems that pandoc doesn't recognise LaTeX units package commands, which results in the numbers and following unit to not show up at all in the epub. Example:

EPUB:
![2015-07-04 14_13_02-schiit happened_ the story of the world s most improbable start-up - jason stodd](https://cloud.githubusercontent.com/assets/12690798/8507889/3f1a1644-2257-11e5-8edb-2488434609a0.png)

Source:
![2015-07-04 14_13_26-f__latex_dokumente_schiit_schiithappened tex - sublime text 2 unregistered](https://cloud.githubusercontent.com/assets/12690798/8507890/40384668-2257-11e5-99d1-a289fec2be40.png)

**Comment by ousia** [comment]
@lblblb, I guess you need the following source:

``` latex
for loads from 600Ω to 16Ω—a much broader range than speaker amps.
```

[Output here.](http://pandoc.org/try/?text=for+loads+from+600\%2C%CE%A9+to+16%CE%A9---a+much+broader+range+than+speaker+amps.%0A&from=latex&to=html)

**Comment by Photon89** [comment]
I have the same problem, although this issue is marked as completed. Is there any info on the \unit command support in TeX? In my case I try to convert to .docx though.

**Comment by Photon89** [comment]
Oh, sorry, didn't notice that it was OP who closed it... Thanks for the information!
