### ISSUE TITLE
- character inside \text{} in latex math environment causes math not to be rendered

### ISSUE THREAD

**Issue by schmittlauch** [jgm/pandoc#2274]
When writing a `-` sign in a \text{} environment in a latex (inline) math section the math isn't rendered but appears as raw text. This happens with the html5 writer with the --mathml option as well as with the odt writer. The latex writer works as expected as it does only copy the raw latex math. Other writers may also be affected, but I didn't test them all.

Example:
```
$\text{This is text written inside a text block in a latex math-environment}$

$\text{This is text written inside a text block in a latex math environment}$
```
The rendering result looks like this:
![bildschirmfoto3](https://cloud.githubusercontent.com/assets/1479555/8508276/a41d0aac-226a-11e5-9ac6-e22cbf5cbf94.png)

The rendered result should only differ in having a `-` character in the word math-environment or not having one. Actually, the upper line isn't rendered into math while the lower one is. I did the rendering with `pandoc -s -t html5 --mathml`, the bug also appears when rendering as odt.

Affected version: pandoc 1.15.0.4, Compiled with texmath 0.8.2, highlighting-kate 0.6.

This bug is really annoying as it breaks a lot of my math stuff with inline annotations containing \text blocks where - is used as a hyphen.

**Comment by jgm** [comment]
This is quite bizarre.  It's really an issue in jgm/texmath:
```
texmath
\text{This is text written inside a text block in a latex math-environment}
ock in a latex math-environment}
                   ^
unexpected "-"
expecting text or "}"
```
I suspect it should be easy to fix.

**Comment by jgm** [comment]
```
cabal update
cabal install --reinstall --force pandoc texmath
```
