### ISSUE TITLE
Small caps not written to reST

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2275]
When writing to reStructuredText, Pandoc (1.15.0.4) does nothing with text in small caps. The result of the following is the text without any tagging:

```shell
pandoc -t rst << EOT
> <span style="font-variant:small-caps;">test</span>
> EOT
```

I'm not entirely sure what the best way to fix this might be; could we have a custom `:sc:` role (or the like) included in the template when necessary? (Anything at all would be better than nothing: as long as it is tagged somehow.)

**Comment by ousia** [comment]
@adunning, there is a proposal (#1592) to have parse small caps from HTML as a proper class.

But even if pandoc had a internal element for small caps, I’m afraid that according to http://docutils.sourceforge.net/rst.html reStructuredText doesn’t seem to support small caps.

**Comment by jgm** [comment]
The problem is that docutils will emit an error when it
encounters an unknown interpreted text role.

**Comment by adunning** [comment]
I hadn't realized that docutils behaves that way; I'm only using it through the [Project Gutenberg RST format](http://epubmaker.pglaf.org). I suppose, then, that there really isn't a stable way of doing this. Thanks for looking at it!
