### ISSUE TITLE
autolink wrongly converted to XHTML tag

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#2277]
@jgm, the following code:

``` markdown
Valid <http://www.pandoc.org>.

Invalid HTML tag: <pandoc.org>.
```

is converted by [latest pandoc](http://pandoc.org/try/?text=Valid+%3Chttp%3A%2F%2Fwww.pandoc.org%3E.%0A%0AInvalid+HTML+tag%3A+%3Cpandoc.org%3E.&from=markdown&to=html) into the following HTML code:

``` html
<p>Valid <a href="http://www.pandoc.org" class="uri">http://www.pandoc.org</a>.</p>
<p>Invalid HTML tag: <pandoc.org>.</p>
```

If this isn’t a bug, at least it should be converted into `&lt;pandoc.org&gt;`.

**Comment by jgm** [comment]
In XML, you can have a period in a tag name.
Pandoc tends to allow anything that might be an XML tag,
since someone might e.g. want to put raw DocBook in,
if targeting DocBook.

**Comment by ousia** [comment]
@jgm, the actual autolink was `<www.boe.es/buscar/act.php?id=BOE-A-1996-8930#a66>`.

 I’d rather say that this isn’t a valid XML tag.

**Comment by jgm** [comment]
This issue goes back to the tagsoup library, which parses
your input as a valid tag:

```
Prelude Text.HTML.TagSoup> parseTags
"<www.boe.es/buscar/act.php?id=BOE-A-1996-8930#a66>"
[TagOpen "www.boe.es" [("buscar",""),("act.php?id","BOE-A-1996-8930#a66")]]
```

tagsoup purports to be a faithful implementation of the
HTML5 parsing algorithm, so this may for all I know be
correct.  But I'll inquire.

https://github.com/ndmitchell/tagsoup/issues/10


+++ Pablo Rodríguez [Jul 07 15 08:13 ]:

**Comment by ndmitchell** [comment]
Going through the [HTML5 lexer spec](http://www.w3.org/TR/html5/syntax.html#tokenization) step-by-step I get the same result as above. The slightly weird bit is that `/` in a tag name switches you to [self-closing-start-tag-state](http://www.w3.org/TR/html5/syntax.html#self-closing-start-tag-state) which then eats the `/` and goes back to attribute name. Once you have that logic, the rest is not too surprising. If you view the tag above in Chrome HTML5 mode you also get the same effect.
