### ISSUE TITLE
Parsing HTML tables not working

### ISSUE THREAD

**Issue by AnilRedshift** [jgm/pandoc#2278]
I am still seeing the bug mentioned here: https://github.com/jgm/pandoc/issues/2015
  
Tables still aren't showing up as markdown:
  
    root@ed06e5c9091a:/# echo "<table><tr><td>hello world</td><td>text</td></tr></tr><td>text2</td><td>text2</td></tr></table>" | pandoc --from html --to markdown
    hello world
    text
    text2
    text2
    root@ed06e5c9091a:/# pandoc --version
    pandoc 1.15.0.4
    Compiled with texmath 0.8.2.2, highlighting-kate 0.6.
    Syntax highlighting is supported for the following languages:
    
Is there a chance I'm missing something dumb here?

**Comment by jgm** [comment]
Looks like you have a `</tr>` where you meant `<tr>`:

```
</tr></tr>
```

**Comment by AnilRedshift** [comment]
Thanks, the example was copied from #2015. The actual example I have doesn't work so I will spend some time to see if I can narrow down a repro.

**Comment by AnilRedshift** [comment]
The narrowed down repro that I was looking down boils to having multiple <thead> entries in a single table.
No idea why the sample came this way (it was created by copy/pasting a table into an editor). I'm not sure if this is valid HTML or not.
~~~~~~~
<table data-table="resource" style="color: rgb(61, 61, 61); line-height: 175%; background: transparent;">
    <thead>
        <tr data-table-header="togglable"></tr>
    </thead>
     <thead>
        <tr data-table-header="togglable"></tr>
    </thead>
    <tbody>
        <tr>
            <td>test</td>
            <td>test2</td>
        </tr>
        <tr>
            <td>test2</td>
            <td>test3</td>
        </tr>
    </tbody>
</table>
~~~~~~

**Comment by jgm** [comment]
This suggests it's not valid to have multiple thead
elements:
http://stackoverflow.com/questions/16155396/multiple-thead-tbody-in-table-valid

If so, then this isn't a bug; pandoc only needs to parse
valid tables.


+++ AnilRedshift [Jul 06 15 22:31 ]:

**Comment by AnilRedshift** [comment]
thanks for taking a look!

**Comment by foliovision** [comment]
It would be really, really nice to have Pandoc convert troublesome HTML tables (often the person converting them didn't write them). [Dom Christie](https://domchristie.github.io)'s [HTML Tables to Markdown](https://domchristie.github.io/to-markdown/) does the job quite well (I'd grabbed a table out of Adobe's website to store our legacy CS licenses in our own hands).

The table code was pretty nasty and [failed here](http://pandoc.org/try/). I'd hand over the sample table code but as it's full of expensive license keys I shouldn't.

Thanks. Alec

**Comment by jgm** [comment]
@foliovision it's no help without an example; perhaps you can replace the contents with filler and keep the table structure?

**Comment by foliovision** [comment]
@jgm John, good point. I'll work on it. I see that simple html tables are converted to Markdown tables in PHP Markdown Extra, Github and MultiMarkdown flavours. The Pandoc flavour does something strange.

**Comment by MahendraNG** [comment]
Do Parsing HTML tables work in .docx format Now?
