### ISSUE TITLE
reveal.js: lazy-loading via data-src

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#2283]
Some of my decks have lots of embeds and as part of my post-processing I've begun converting 'src' to 'data-src' for image, video, audio and iframe elements -- actually, any non-script element. Yet, maybe pandoc should take advantage of [lazy loading](https://github.com/hakimel/reveal.js/#lazy-loading) on these elements by default?

**Comment by reagle** [comment]
Just wanted to touch this again; I'd much prefer if pandoc converted img, video, and iframe elements to using data-src instead of source.

**Comment by mb21** [comment]
The HTML writer could be changed to produce `data-src` instead of `src` when you're generating a reveal-js slideshow... i.e. `if (writerSlideVariant opts /= RevealJsSlides)`

Should the same also be done for s5, slidy, slideous and dzslides? Or do any of those work with js disabled (in which case we would break the presentation for non-js users).

**Comment by reagle** [comment]
I don't know if they even have lazy loading or how they go about it; I strongly expect this is specific to reveal.js .

**Comment by jgm** [comment]
Note: the above fix only helps with regular images; it won't affect iframes, video, etc.
A better solution would be to postprocess the HTML.
I guess you're already doing that.

**Comment by reagle** [comment]
Great, thank you. It just occurred to me to wonder how this works with the --self-contained option?

**Comment by jgm** [comment]
+++ Joseph Reagle [Feb 20 17 16:35 ]:
>   Great, thank you. It just occurred to me to wonder how this works with
>   the --self-contained option?

It should work fine.

**Comment by Quintasan** [comment]
Sorry to resurrect this, but according to [Media section of reveal.js documentation](https://revealjs.com/media) `data-src` works for images, iframes and videos now. Is this something we would be open to use now in pandoc?

**Comment by Quintasan** [comment]
@jgm That's embarrassing. After reading your comment, I took some time and couldn't make it happen, after an hour or so I realized I was running an old version of Pandoc 😓
