### ISSUE TITLE
EPUB reader mangles URLs

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#2284]
To see this, do
```
pandoc README -o r.epub
pandoc r.epub -t markdown
```
and look at the links at the beginning.

Culprit seems to be
```
  . (walk normalisePath)
```
in `fixInternalReferences`, but I couldn't figure out what this was for.  @mpickering, can you shed any light/fix?

**Comment by mpickering** [comment]
What is the precise problem? I generated it to HTML and all of the internal
links seem to work correctly?

If I remember right this step was because some EPUB documents have internal
references which span internal files - by modifying the IDs in this way,
the internal references work when all the files are read together.

**Comment by jgm** [comment]
+++ Matthew Pickering [Jul 08 15 15:23 ]:
>   What is the precise problem? I generated it to HTML and all of the
>   internal
>   links seem to work correctly?

I'm talking about the *external* links, e.g. in the first long
paragraph of the README:

```
Pandoc is a [Haskell]() library for converting from one markup format to
another, and a command-line tool that uses this library. It can read
[Markdown](), [CommonMark](commonmark.org), and (subsets of)
[Textile](textile), [reStructuredText](introduction.html), [HTML](),
[LaTeX](), [MediaWiki markup](Help:Formatting), [TWiki
markup](TextFormattingRules), [Haddock markup](ch03s08.html),
```

**Comment by mpickering** [comment]
I need to think about how to fix this. The problem is that internal links
need to be mangled to point to the right place when the files get collapsed
together.

**Comment by jgm** [comment]
Is it enough to just leave external links alone?

+++ Matthew Pickering [Jul 21 15 16:21 ]:

**Comment by jgm** [comment]
@mpickering, have you had a chance to think about this?  It would be nice to fix this bug.

**Comment by mpickering** [comment]
Yes leaving external links alone should be sufficient. The transformation
was designed with only internal links in mind.
