### ISSUE TITLE
nocite: control the placement?

### ISSUE THREAD

**Issue by and3k** [jgm/pandoc#2285]
Hi,

right now when I use nocite the citations are added tot he top of the references (when using a numeric citation style, e.g. PNAS). Is there a way to control where they get added? Like at the end of the reference list?

Thanks!
Bela

**Comment by jgm** [comment]
You could put them in a YAML metadata block at the end of
the document, instead of the beginning.

+++ Bela Hausmann [Jul 09 15 01:04 ]:

**Comment by and3k** [comment]
Tried that already, didn’t change anything.

**Comment by mb21** [comment]
Questions should go to pandoc-discuss...
