### ISSUE TITLE
--self-contained in slidy puts unremovable table of content on page

### ISSUE THREAD

**Issue by asimjalis** [jgm/pandoc#2286]
I am running the latest version of pandoc on a Mac. It works fine without --self-contained. But with this the table of content appears frozen on top of the slides. Also the slides are all on one long page.

Here are the steps to reproduce this:

    cat > habits.txt << '__END__'
    % Habits
    % John Doe
    % March 22, 2005

    # In the morning

    ## Getting up

    - Turn off alarm
    - Get out of bed

    ## Breakfast

    - Eat eggs
    - Drink coffee
    __END__

    pandoc --self-contained -t slidy habits.txt -o habits.html
    open habits.html

**Comment by jgm** [comment]
What does `pandoc --version` say?  There were bugs in
`--self-contained` in some early 1.15.x releases.

+++ Asim Jalis [Jul 09 15 12:06 ]:

**Comment by asimjalis** [comment]
Here is the version info for pandoc.

    /usr/local/bin/pandoc --version
    pandoc 1.15
    Compiled with texmath 0.8.2, highlighting-kate 0.6.

Then I built pandoc from sources using Cabal, and saw the same issue there as well. Here is the version info for that.

    $HOME/Library/Haskell/bin/pandoc --version
    pandoc 1.15.0.4
    Compiled with texmath 0.8.2.2, highlighting-kate 0.6.

One other possibility is that it is a bug in Slidy.

**Comment by asimjalis** [comment]
Here is a screenshot of the slideshow that I get when I run the steps in the earlier comment.

![image](https://cloud.githubusercontent.com/assets/227187/8626102/89f66b50-26f7-11e5-8f06-f0032b0e89b3.png)
