### ISSUE TITLE
[Feature request] Handle 'data:'-URIs in HTML input (similar to '--extract-media=...') 

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2289]
Consider the following HTML file, using an embedded image as `<img src=data:image/png;base64,...>`:

``` html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Key</title>
    </head>
    <body lang="en-US">
        <div>
            <p class="Normal">Example 1</p>
            <p class="Normal"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA4CAYAAACyutuQAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAjUlEQV
RoQ+3RQQqAMAxEUc/iWbz/laLiRrqJTBAm4RcedJFSPtkiYpskHejmPjFMOtDNc8lW6Y4gdwS5I8gdQe4IckeQO4Lc/Rp0nf31werI3isIqlgCCfqCoAqCBARVECQgqIIgAUEVBAkIqiBIQFAFQQKC3BHkji
B3BLkjyN38oEHSgV6yVXaTDnRzAnzm9tRRL/2RAAAAAElFTkSuQmCC" alt="" />&#9;a) 2625371;</p>
        </div>
    </body>
</html>
```
1. Converting this file to PDF works as expected:  
   `pandoc sample.html -f html -o sample.pdf`.
2. Converting this file to LaTeX first:  
   `pandoc sample.html -f html -s -t latex -o sample.tex`,  
   and then running `pdflatex` fails and does not create a PDF.

Adding `--verbose` to the direct PDF conversion reveals that the intermediate LaTeX file for this variant contains this line:      

```
 \includegraphics{/var/folders/80/3wtx3wys21l921zvl6mp_lp80000gn/T/tex2pdf.22284/671beef358abf708dd94e781689f1ea67097951c.png}
```

The LaTeX file which was created by the second command however has this line:      

```
 \includegraphics{data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA4CAYAAACyutuQAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAjUlEQV\%0ARoQ+3RQQqAMAxEUc/iWbz/laLiRrqJTBAm4RcedJFSPtkiYpskHejmPjFMOtDNc8lW6Y4gdwS5I8gdQe4IckeQO4Lc/Rp0nf31werI3isIqlgCCfqCoAqCBARVECQgqIIgAUEVBAkIqiBIQFAFQQKC3BHkji\%0AB3BLkjyN38oEHSgV6yVXaTDnRzAnzm9tRRL/2RAAAAAElFTkSuQmCC}
```

All other lines in the respective LaTeX code are identical.

The HTML file comes from this thread: https://groups.google.com/forum/#!topic/pandoc-discuss/TV39ZgMJlAY

(tested with cabal-installed v1.15.0.4)

**Comment by jgm** [comment]
With the new PandocMonad architecture, we could extract this and add it to the mediabag.
But this would only help if we also made `--extract-media` work with non-binary formats (see #1583).
