### ISSUE TITLE
Unbalanced curly brackets in latex sections break the parser

### ISSUE THREAD

**Issue by squisher** [jgm/pandoc#2291]
If there is an unbalanced curly bracket inside a \begin \end block of raw latex, the parser chokes on it and treats it as text instead of raw latex. The example below is quite minimal and illustrates the issue:

% cat example.md
```
# Test

Broken:

\begin{center}
{
\end{center}

Should be parsed like:

\begin{center}
{}
\end{center}
```

% pandoc -t beamer -f markdown -o example.tex example.md

% cat example.tex
```
\begin{frame}{Test}

Broken:

\textbackslash{}begin\{center\} \{ \textbackslash{}end\{center\}

Should be parsed like:

\begin{center}
{}
\end{center}

\end{frame}
```

**Comment by r-gaia-cs** [comment]
@squisher what do you expected that Pandoc does when there is an unbalanced curly bracket inside a LaTeX `\begin`-`\end` block?

**Comment by squisher** [comment]
Simply produce a verbatim "{".

Ok, I should've presented my use case:
```
\usepackage{minted}

Consider this abbreviated dictionary:

\begin{minted}{python}
huge_dict = { 'foo': 'bar,
   #...
\end{minted}{python}
```

Currently this minted listing now gets turned into text, which is rather puzzling at first!

**Comment by jgm** [comment]
The character `{`  behaves differently in verbatim and non-verbatim environments.
So pandoc has to *know* that you've got a verbatim environment to parse this correctly.
Pandoc does know that `minted` is a verbatim environment, but it doesn't recognize `pythoncode` as one.  (It doesn't currently parse `newminted`, but could probably be made to.)
