### ISSUE TITLE
apa-cv.csl not working with pandoc-citeproc

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#2297]
I'm not sure if this is the CSL, pandoc, or me, but I've documented the issue in the CSL repo: citation-style-language/styles#1619. Can anyone reproduce?

**Comment by jgm** [comment]
To make it easier for us, can you post the output you received and the output you expected?
Also versions.

**Comment by reagle** [comment]
On 07/13/2015 05:09 PM, John MacFarlane wrote:
> To make it easier for us, can you post the output you received and the output you expected?
> Also versions.

It should look something like this:

  http://reagle.org/joseph/2015/rtc/reviews.html

That is, full references expanded where the citation is.

pandoc 1.15.0.4
Compiled with texmath 0.8.2, highlighting-kate 0.6.

**Comment by jgm** [comment]
+++ Joseph Reagle [Jul 13 15 14:39 ]:
>   On 07/13/2015 05:09 PM, John MacFarlane wrote:
>   > To make it easier for us, can you post the output you received and
>   the output you expected?
>   > Also versions.
>   It should look something like this:
>   http://reagle.org/joseph/2015/rtc/reviews.html

What output did you receive instead?

>   That is, full references expanded where the citation is.
>   pandoc 1.15.0.4
>   Compiled with texmath 0.8.2, highlighting-kate 0.6.

And most importantly, pandoc-citeproc?

**Comment by reagle** [comment]
On 07/13/2015 05:47 PM, John MacFarlane wrote:
> And most importantly, pandoc-citeproc?

Sorry:  pandoc-citeproc 0.7.2

**Comment by reagle** [comment]
The output should be in the zip file.

--
sent from mobile

**Comment by nickbart1980** [comment]
Looking at the code, apa-cv.csl works as expected.
What you want is a CSL style with everything in the `<citation>` element, and an empty `<bibliography>` element. Not sure whether any such style is in the repo, though.

**Comment by reagle** [comment]
Okay, yes, thank you, this isn't a bug with pandoc but my confusion over what I requested of the CSL folks and what they said their version did. (My confusion was compounded with pandoc by the fact that it picked up a local apa-cv.csl that does what I want when I assumed it would use the one in ~/.csl .)

I do have a CSL that does what I want (inline fully expanded refs) [here](http://reagle.org/joseph/2003/cv/apa-cv.csl).

**Comment by reagle** [comment]
@nickbart1980 I think you understand what I want, and how my CSL achieves it, but I'm having difficulty communicating it over here citation-style-language/styles#1619. Can you help?

**Comment by rmzelle** [comment]
Uh, yeah. I thought there was an issue with pandoc since the references in @reagle's HTML example weren't sorted by date, but I see now that he just used a series of in-text cites instead of a single bibliography, which of course allows for an arbitrary order.

We can continue in the style repo issue tracker. Pretty sure this is just a difference in expectation of what a CV CSL style should do.
