### ISSUE TITLE
Documentation of -D option to say 'system default template' rather than 'default template'

### ISSUE THREAD

**Issue by drbean** [jgm/pandoc#2298]
I think it is not clear what the default template is. What does 'default template' mean?

Is it templates/default.FORMAT in the default data-dir given by 'pandoc --version'?

Or /usr/share/pandoc/data/templates/default.FORMAT, a file which is not documented.

I suggest 'system' being inserted in front of 'default template.'

I spent a couple of hours trying to get pandoc -D beamer to print a file not in the second location.

From a discussion on the #pandoc channel on irc.freenode.net:

16:48:35    drbean | I think that 'pandoc -D' to print the default template does not respect the default data dir, but will only print the /usr/share/pandoc/data/templates/ template.
16:53:50    drbean | You have to use --template for a template in the default data dir. Too many defaults with different meaning here.
17:02:10       _ht | Okay, but whatever template your actually using, you can look through its source to see the meaning of the variables and such?
17:09:37       <-- | Oksana (~chatzilla@Maemo/community/council/Wikiwide) has quit (Ping timeout: 246 seconds)
17:14:10       _ht | drbean: From the documentation: "A custom template can be specified using the --template option. You can also override the system default templates for a given output format FORMAT by putting a file templates/default.FORMAT in the user data directory"
17:15:01       _ht | As far as I understand, unless you specify a different data-dir with the `--data-dir  /path/to/some/dir` option, the user's data dir is ~/.pandoc
17:37:02       <-- | dibblego (~dibblego@haskell/developer/dibblego) has quit (Ping timeout: 244 seconds)
17:38:49       --> | dibblego (~dibblego@haskell/developer/dibblego) has joined #pandoc
18:18:04       --> | Stalkr_ (~Stalkr@unaffiliated/filuren) has joined #pandoc
19:49:33       <-- | dibblego (~dibblego@haskell/developer/dibblego) has quit (Ping timeout: 246 seconds)
19:49:54       --> | dibblego (~dibblego@haskell/developer/dibblego) has joined #pandoc
20:56:01    drbean | Do you think that line means if you move default.FORMAT from the system default location to ~/.pandoc/templates, then 'pandoc -D FORMAT' would still show it?
20:56:01    drbean | In my case, pandoc --version shows 1.12.3.3 and 'Default user data directory: /home/drbean/.pandoc',
20:56:01    drbean | [drbean@sac steve]$ pandoc -D latex > latex_template
20:56:01    drbean | [drbean@sac steve]$ sudo mv /usr/share/pandoc-1.12.3.3/data/templates/default.latex ~drbean/.pandoc/templates/ && sudo chown drbean:drbean ~drbean/.pandoc/templates/default.latex
20:56:01    drbean | [drbean@sac steve]$ pandoc -D latex > latex_template
20:56:01    drbean | pandoc: Could not find data file templates/default.latex
21:07:29       _ht | drbean: I think templates should go  in the .pandoc directory, not in a subdirectory such as "templates"
21:09:26       _ht | scratch that
21:09:35       _ht | It should go in the templates folder
21:11:54       _ht | So, I just made the folder ~/pandoc/templates
21:12:16       _ht | I created the file default.latex with content: "Hi $body$"
21:13:06       _ht | if I run `echo "*bold text*" | pandoc -f markdown -t latex -s -o test.tex
21:13:25       _ht | I get a test.tex file containing: Hi \emph{bold text}
21:13:57       _ht | But if I run pandoc -D latex, I still get the "official" template in the /usr/share/... folder
21:24:57       _ht | Then again, if I don't use the pandoc default templates,  I always use `--template /path/to/a/particular/custom/template.tex` and forego the ~/.pandoc directory alltogether
21:42:38    drbean | Your little test of a minimal template 'templates/default.latex' in the default data-dir also works here. So, all is well.
21:42:38    drbean | I see why you might not want to use the ~/.pandoc data-dir. The pandoc man page recommends forking the github pandoc-templates repository and you might not want to clone that in a dotfile directory.
21:43:55       _ht | True
21:44:32       _ht | Plus I already have an assets folder for most of document with images and stuff, so it ain't a bother to add  a template as well
22:16:23      hftf | i don't see why pandoc -D should show the user template
22:17:50      hftf | maybe for the most forgetful people
22:19:25      hftf | if youre advanced enough to use override templates i feel like the convenience option of pandoc -D isnt that useful
22:19:43      hftf | like _ht, i also only use --template and forgo overrides
22:20:16      hftf | but if you think it's a bug you should file it
22:20:48       _ht | On the other hand, it makes sense that pandoc -D would return the template it would actually use
22:21:24      hftf | i could see it making sense either way
22:21:45      hftf | it's called "--print-default-template" not "--print-override-template-sometimes-and-default-sometimes"
22:21:51       _ht | True
22:22:18       _ht | And it is a nice way to get started with your own custom templates
22:23:06      hftf | frankly i didnt even know about -D until now
22:23:13      hftf | i used to go to github every time
22:23:17      hftf | so thanks for the awareness
22:25:35      hftf | i find the wording in the docs ambiguous though
22:25:35       _ht | Sure thing. Luckily the pandoc documentation is superb, so no "hidden" options or anything
22:25:43      hftf | "If the template is not found, pandoc will search for it in the templates subdirectory of the user data directory (see --data-dir). If this option is not used, a default template appropriate for the output format will be used (see -D/--print-default-template)."
22:26:04      hftf | it makes it seem like the first sentence applies to -t only and second one to not having -t only
22:26:10      hftf | but according to your test
22:26:17      hftf | er
22:26:19      hftf | --template *
22:26:50       _ht | It seems to work as a failsafe
22:27:12      hftf | now i think at least some kind of bug should be filed
22:27:17      hftf | at least to clarify the wording
22:27:22       _ht | If it cannot find the template you specify relative to pwd, it looks for it in the users' pandoc folder
22:27:54       _ht | Still, a bit difficult to understand what exactly it will be doing
22:28:02       _ht | Especially if all these templates look a lot alike
22:28:39      hftf | yeah pandoc should probably be up front about which template is being used
22:29:45       _ht | To be honest, I never had any problem with my templates
22:30:29      hftf | me neither
22:34:49       _ht | All in all, pandoc is a breath of fresh air compared to the arcane TeX, troff, tex4ht, ...

**Comment by jgm** [comment]
Agreed, it would be clearer with "system default template."
`-D` returns the system default, even if you have a
shadowing template in the user data directory.
