### ISSUE TITLE
hyphen at the beginning of a url component break links badly if autolink_bare_uris is enabled.

### ISSUE THREAD

**Issue by rubenarslan** [jgm/pandoc#2299]
Somehow if a hyphen is at the beginning or end of a url component (value of a query string, query parameter name, end of the URL itself), pandoc truncates the URL in a weird way.

In example three (using HTML), which I really expected pandoc not to interfere with, it even generates invalid html, i.e a doubly nested link.

I've tested this in 1.13.1 (ships with rmarkdown) and 1.14.0.1 (compiled on Ubuntu), but only by calling pandoc indirectly via rmarkdown. [Here](http://pandoc.org/try/?text=%23+broken%0Ahttps%3A%2F%2Fexample.org%2F%3Fanchor%3D-lala%0A%0A%5Bhttps%3A%2F%2Fexample.org%2F%3Fanchor%3D-lala%5D(https%3A%2F%2Fexample.org%2Fblabla%2F%3Fanchor%3D-lala)%0A%0A%3Ca+href%3D%22https%3A%2F%2Fexample.org%2F%3Fanchor%3D-lala%22%3Ehttps%3A%2F%2Fexample.org%3Fanchor%3D-lala%3C%2Fa%3E%0A%0Ahttps%3A%2F%2Fexample.org%2F%3F-anchor%3Dlala%0A%0Ahttps%3A%2F%2Fexample.org%2F%3Fanchor%3Dlala-%0A%0Ahttps%3A%2F%2Fexample.org%2F-%0A%0A%23+works%0A%3Chttps%3A%2F%2Fexample.org%2F%3Fanchor%3D-lala%3E%0A%0A%0A%3Chttps%3A%2F%2Fexample.org%2F-%3E%0A%0Ahttps%3A%2F%2Fexample.org%2F%3Fanchor%3Da-lala%0A&from=markdown&to=html), it does fine. Turning on the extension autolink_bare_uris breaks it.

Github (see below) but also e.g. commonmark.js render all links correctly.

Luckily using <>, it still works.

# broken
1. [ ] https://example.org/?anchor=-lala

2. [ ] [https://example.org/?anchor=-lala](https://example.org/blabla/?anchor=-lala)

3. [ ] <a href="https://example.org/?anchor=-lala">https://example.org?anchor=-lala</a>

4. [ ] https://example.org/?-anchor=lala

5. [ ] https://example.org/?anchor=lala-

6. [ ] https://example.org/-

# works
<https://example.org/?anchor=-lala>

<https://example.org/->

https://example.org/?anchor=a-lala

# works
<https://example.org/?anchor=-lala>

<https://example.org/->

https://example.org/?anchor=a-lala

	# broken
	https://example.org/?anchor=-lala
	
	[https://example.org/?anchor=-lala](https://example.org/blabla/?anchor=-lala)
	
	<a href="https://example.org/?anchor=-lala">https://example.org?anchor=-lala</a>
	
	https://example.org/?-anchor=lala
	
	https://example.org/?anchor=lala-
	
	https://example.org/-
	
	# works
	<https://example.org/?anchor=-lala>
	
	
	<https://example.org/->
	
	https://example.org/?anchor=a-lala

**Comment by ousia** [comment]
@rubenarslan, [automatic link markup](http://pandoc.org/README.html#automatic-links) is mandatory. Or you have to enable the [extension `autolink_bare_uris`](http://pandoc.org/README.html#extension-autolink_bare_uris).

It doesn’t have anything to do with hyphens ([see sample](http://pandoc.org/try/?text=http%3A%2F%2Fpandoc.org%0A%0A%3Chttp%3A%2F%2Fpandoc.org%3E&from=markdown&to=html)).

The difference is that GitHub enables automatic links without special markup.

**Comment by rubenarslan** [comment]
@ousia I know, but that's not my point. The point is: once you turn on autolink_bare_uris all of the examples I listed above below `#broken` break badly. Github autolinks bare uris without breaking them.

**Comment by rubenarslan** [comment]
Thanks, that was quick! 

If there's other edge cases that you haven't come across yet or don't want to allow (e.g. a link contained an unmatched parenthesis), it may make sense to somehow turn off autolinking in cases where an explicit link is marked up, e.g. I'm assuming the below URL still leads to invalid HTML, even after your fixes (sorry, didn't build to check).

    [https://example.com/smile:-)](https://example.com/smile:-))


Don't know whether that's easy but if all goes well it is possible to label links using HTML or `[linktext](link)`, so I guess so?
I was a bit flummoxed when explicit HTML didn't do the job (I didn't recall <> at first).

**Comment by jgm** [comment]
Yes, currently

    [http://example.com](http://example.com)

gives a link within a link, which isn't good.  But this
should be a separate issue report.  Want to submit one?


+++ Ruben C. Arslan [Jul 14 15 11:34 ]:

**Comment by ousia** [comment]
> @ousia I know, but that's not my point. The point is: once you turn on autolink_bare_uris all of the examples I listed above below `#broken` break badly. Github autolinks bare uris without breaking them.

Sorry, @rubenarslan. I totally overlooked that you had mentioned enabling the `autolink_bare_urls` in your first message.

**Comment by rubenarslan** [comment]
@ousia probably my fault, I edited it in after posting the issue, hadn't noticed before, since I always use pandoc through rmarkdown and they set that option.
