### ISSUE TITLE
List bug

### ISSUE THREAD

**Issue by Immortalin** [jgm/pandoc#2304]
Hi, the bug shown [here](https://philsturgeon.uk/markdown/2014/11/30/state-of-markdown/) still appears in the Babelmark benchmarks.

**Comment by jgm** [comment]
It's not a bug, it's just a variation in markdown flavor.

In pandoc (like Markdown.pl, but unlike CommonMark), lists
cannot interrupt a paragraph.  So if you have something like

```
Foo
- bar
- baz
```

this isn't parsed as containing a list.  Similarly

```
> Foo
> - bar
> - baz
```

You can always do `pandoc -f commonmark` if you want the
CommonMark interpretation.
