### ISSUE TITLE
pandoc templates - counter in for loop

### ISSUE THREAD

**Issue by mangecoeur** [jgm/pandoc#2306]
Is there a way to get the loop index within a $for$ loop in a template? I'm trying to do something like

```latex
$for(author)$\author[$index$]{$author.name$}
$endfor$
```

**Comment by jgm** [comment]
+++ mangecoeur [Jul 16 15 03:50 ]:
>   Is there a way to get the loop index within a $for$ loop in a template?
>   I'm trying to do something like
>
>$for(author)$\author[$index$]{$author.name$}
>$endfor$
>

No.  (PS.  pandoc-discuss is the right place for questions;
this tracker is for bug reports.)
