### ISSUE TITLE
Feature request : Add a server mode to pandoc

### ISSUE THREAD

**Issue by MathieuDuponchelle** [jgm/pandoc#2308]
My use case is as follows:

I parse a large number of source code comments, formatted in markdown + a custom extension (can be over 1000 separate fragments)

I want to translate these fragments to json (doing this from python), do some processing, and pass that native representation to potential subclasses for further processing.

The problem I have with pypandoc is that it starts a new subprocess for each conversion. Ideally, I would like to be able to start pandoc as a subprocess with no input file a single time, send some data to it, send an EOF, read from the subprocess, process the data, and start over again, closing the subprocess by sending a second EOF immediately after the last fragment.

This would allow me to use pandoc as a "server", without the overhead of having to start a new process for each conversion job.

Alternatively, it could also be argued that pandoc could detect when a json input is done, and output without waiting for the EOF,  but that would be less generic.

**Comment by jgm** [comment]
+++ MathieuDuponchelle [Jul 17 15 11:17 ]:
>   Alternatively, it could also be argued that pandoc could detect when a
>   json input is done, and output without waiting for the EOF, but that
>   would be less generic.

That makes more sense to me; it would only affect the JSON reader.

**Comment by MathieuDuponchelle** [comment]
Well my idea is that ideally it would affect all readers :)

**Comment by jgm** [comment]
In Markdown, for example, streaming parsing doesn't make
sense.  A reference definition in a later chunk might affect
the output of this chunk.  And, with the change you propose,
people who use pandoc from the command line would have to
send EOF twice.

But for JSON input, which is what you really care about,
it might make sense, since pandoc can tell when it has
received a completely json-encoded pandoc document.

**Comment by MathieuDuponchelle** [comment]
> A reference definition in a later chunk might affect the output of this chunk

The idea in that case is that chunks would be independent.

> people who use pandoc from the command line would have to send EOF twice. 

This could be an opt-in switch I'm thinking ?

Basically the problem I have is that pypandoc and anything wrapping pandoc as a subprocess is simply useless for my use case, which consists of many tiny fragments to render, the throughput is just unacceptable, do you see that problem too ?

I'm pretty sure this solution can be implemented fairly easily, and shouldn't involve a lot of maintaining, especially if it's an opt-in switch.

**Comment by jgm** [comment]
I do see the point of it.

One possibility would be to add a "server mode," which
causes pandoc to start up a little web server on localhost
that implements a JSON API.

Would that suit your needs?

+++ MathieuDuponchelle [Jul 17 15 12:51 ]:

**Comment by MathieuDuponchelle** [comment]
It would, but it seems a bit more involved than my solution on pandoc's side, while my solution requires the application side to be able to deal with a subprocess in a nice way (python's subprocess.POpen for instance)

**Comment by MathieuDuponchelle** [comment]
Another, way better solution would be to offer bindings, but I'm not sure how that is done with haskell

**Comment by jgm** [comment]
Someone has done this.

https://github.com/ShabbyX/libpandoc

I don't know how up-to-date this is.

+++ MathieuDuponchelle [Jul 17 15 13:03 ]:

**Comment by MathieuDuponchelle** [comment]
Yeah I was exactly looking at that :)

**Comment by MathieuDuponchelle** [comment]
Not very active though, and I'm not sure I want to introduce an extra dependency that isn't packaged, at least on my distro

**Comment by MathieuDuponchelle** [comment]
Is that the moment when I say "Please just a switch" and you say "all right here you go" ?

**Comment by MathieuDuponchelle** [comment]
Cause that would be awesome :P

**Comment by jgm** [comment]
I'll think about it, but I don't have time to do it in the
near future.

+++ MathieuDuponchelle [Jul 17 15 13:12 ]:

**Comment by MathieuDuponchelle** [comment]
Hey, so I've given a shot at a simple json server that does what I want using zmq, I'll leave it here in case it helps someone (disclaimer : never did haskell before :P)

```haskell
{-# LANGUAGE OverloadedStrings, RecordWildCards #-}
module Main where

import Data.Aeson
import Text.Pandoc
import System.ZMQ4.Monadic
import Control.Monad
import Data.ByteString.Char8 (pack, unpack)
import Data.ByteString.Lazy (fromStrict)
import Control.Concurrent (threadDelay)
import Control.Applicative ((<$>))
 
data Job = Job {informat :: String, outformat :: String, payload :: String}

instance FromJSON Job where
  parseJSON = withObject "job" $ \o -> do
    	informat <- o .: "informat"
    	outformat <- o .: "outformat"
	payload <- o .: "payload"
	return Job{..}

readToPandoc :: Job -> Maybe Pandoc
readToPandoc job = do
	case (informat job) of
		"markdown" -> Just (readMarkdown def (payload job))
		_ -> Nothing

writeFromPandoc :: Job -> Pandoc -> String
writeFromPandoc job pandoc = do
	case (outformat job) of
		"json" -> writeJSON def pandoc
		_ -> "Unsupported output format"
	

myActualConvert :: Job -> String
myActualConvert job = do
		let pandoc = readToPandoc job
		case pandoc of
			Just value -> writeFromPandoc job value
			Nothing -> "Unsupported input format"

myConvert :: Maybe Job -> String
myConvert job = do
		case job of
			Just job -> myActualConvert job
			Nothing -> "Invalid json"

main :: IO ()
main =
    runZMQ $ do  
        repSocket <- socket Rep
        bind repSocket "tcp://*:5555"
  
        forever $ do
            msg <- receive repSocket

	    let x = decode (fromStrict msg)
            send repSocket [] (pack (myConvert x))
```

**Comment by MathieuDuponchelle** [comment]
And a simple python client that expects a markdown file as its first argument : 

```python
import zmq
import sys
import json

context = zmq.Context()

#  Socket to talk to server
socket = context.socket(zmq.REQ)
socket.connect("tcp://localhost:5555")

with open (sys.argv[1], 'r') as f:
    contents = f.read ()

for request in range(100):
    job = json.dumps ({'informat': 'markdown',
                       'outformat': 'json',
                       'payload': contents})
    socket.send(job)

    #  Get the reply.
    message = socket.recv()
    print("Received reply %s [ %s ]" % (request, message))
```

**Comment by MathieuDuponchelle** [comment]
So I ended up continuing in that direction, made some additions and fixed unicode handling, the current code lives at https://github.com/MathieuDuponchelle/better_doctool/tree/master/pandoc_interface , I'd much rather have an upstream solution though, would be great if we could either upstream this code in some way, if the implementation is fine by you (ie is zeromq a dependency you would mind to have for the server mode ?), or discuss an alternate implementation :)

**Comment by MathieuDuponchelle** [comment]
I also wasn't sure how to pass options through the json API so there's simply no parameter for them, I suppose that should be added before potential inclusion.

**Comment by MathieuDuponchelle** [comment]
The code is actually there now : https://github.com/MathieuDuponchelle/better_doctool/tree/master/src/pandoc_interface

**Comment by jgm** [comment]
I would rather not add a dependency on an external C library
like zeromq.

+++ MathieuDuponchelle [Jul 31 15 11:17 ]:

**Comment by MathieuDuponchelle** [comment]
OK, unfortunately I'm not proficient at all with haskell, and zmq was a nice high-level solution :)

**Comment by MathieuDuponchelle** [comment]
I'm also going to investigate how difficult it would be to make actual python bindings for pandoc with FFI, not sure how involved that would be.

**Comment by jgm** [comment]
I think the most complete solution would be to use
https://hackage.haskell.org/package/servant
to define an API that covers all of pandoc's features and
options, and add the HTTP server using wai and warp.

+++ MathieuDuponchelle [Aug 01 15 14:36 ]:

**Comment by MathieuDuponchelle** [comment]
That would be nice indeed, anyway I've opted for another solution, and use handwritten haskell -> C -> python bindings, this removes the zeromq dependency for my project, and improves the speed by a significant factor :)
