### ISSUE TITLE
HTML reader does not interpret type attribute on <ol>

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2313]
The HTML reader does not interpret the type attribute on `<ol>` (output by the HTML5 writer), as in the following case (version 1.15.0.6):

```html
pandoc -f html -t markdown << EOT
<ol type="1">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="I">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="i">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="A">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="a">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
EOT
```

This is the result:

```markdown
1.  One
2.  Two
3.  Three

<!-- -->

1.  One
2.  Two
3.  Three

<!-- -->

1.  One
2.  Two
3.  Three

<!-- -->

1.  One
2.  Two
3.  Three

<!-- -->

1.  One
2.  Two
3.  Three
```

**Comment by adunning** [comment]
Am I missing something here? Given either of these commands:

```shell
pandoc -f markdown -t html5 << EOT | pandoc -f html -t markdown

pandoc -f markdown -t html << EOT | pandoc -f html -t markdown
```

I would expect the following to return identical results:

```markdown
1.  One
2.  Two

<!-- -->

I.  One
II. Two

<!-- -->

i.  One
ii. Two

<!-- -->

A.  One
B.  Two

<!-- -->

a.  One
b.  Two

EOT
```

Instead, I receive the following in both cases:

```markdown
1.  One
2.  Two

<!-- -->

1.  One
2.  Two

<!-- -->

1.  One
2.  Two

<!-- -->

1.  One
2.  Two

<!-- -->

1.  One
2.  Two
```

**Comment by hftf** [comment]
Oops, should have said I started fixing this bug. FYI, I think the nearby `lookup "style"` code (added in [`e814a3f`](https://github.com/jgm/pandoc/commit/e814a3f6d23f640b1aed5b7cb949459d514a3e33#diff-b1c35a3f694e124b0b4ea092ccf36515) from 8 years ago) doesn't work as intended:

```
$ cat <<EOF > foo
<ol class="lower-roman"></ol>
<ol style="lower-roman"></ol>
<ol style="list-style: lower-roman;"></ol>
<ol style="list-style-type: lower-roman;"></ol>
EOF
$ pandoc -f html -t native foo
[OrderedList (1,LowerRoman,DefaultDelim)
 []
,OrderedList (1,LowerRoman,DefaultDelim)
 []
,OrderedList (1,DefaultStyle,DefaultDelim)
 []
,OrderedList (1,DefaultStyle,DefaultDelim)
 []]
```

I also had trouble running the HTML tests using only `cabal test`. It seems I needed to completely install pandoc before my changes were used.

**Comment by jgm** [comment]
Yes, the style thing is messed up.  We need to look for
`list-style-type`.  This may even be wrong in the tests
(`tests/html-reader.html`).

`cabal test` sometimes doesn't work for me either,
for reasons I don't understand.  But you can always run
the test suite manually,
`dist/build/test-pandoc/test-pandoc`.

+++ Ophir Lifshitz [Jul 21 15 13:20 ]:

**Comment by jgm** [comment]
PS.  I'll wait for you to submit a PR fixing these things,
if you still want to work on it.
