### ISSUE TITLE
Docx to textile - Textile doesn't get the colors for text or tables

### ISSUE THREAD

**Issue by cksachdev** [jgm/pandoc#2316]
I have colored text and tables with colors in docx format. Is it possible to maintain the colors used in docx and output them in textile? 

Do I need to use any special flags/parameters in pandoc to get it working?

pandoc --highlight-style=zenburn -f docx -t textile test.docx

Is there a User Interaface utility to use it in OSX?

**Comment by jgm** [comment]
No, Pandoc's document model focuses on structure and doesn't
include any way of representing colors, so this information
will be lost.

There is no GUI that I'm aware of.

**Comment by cksachdev** [comment]
Is it possible to include it? If yes, in which files I should look into, to customise conversion of docx to textile?

**Comment by jgm** [comment]
It would require changes to the underlying Pandoc types
(pandoc-types package), and to EVERY part of Pandoc that
interacts with those types, not just docx reader and textile
writer.

+++ Chetan Sachdev [Jul 21 15 10:50 ]:

**Comment by cksachdev** [comment]
Thanks for the info. Closing this for now.
