### ISSUE TITLE
RFE: Referencing tables/figures/headers

### ISSUE THREAD

**Issue by sils1297** [jgm/pandoc#2317]
Hey, I understand that I currently can do

```markdown
See [Discussion](#EVAL).

# Discussion {#EVAL}

The quick brown fox jumps away.
```

However there are several issues with this.

1. If I change the heading I need to rechange it everywhere :( I use markdown with pandoc to get an abstraction over such details and IMO it would be nice if I could somehow just put the ID there.
2. I can't reference figures and tables it seems.

Ideally I can think of something like:

```markdown
See {#tab1}.

Some  Content
----- -------
a     nother

Table: Holds content! {#tab1}
```

**Comment by jgm** [comment]
+++ Lasse Schuirmann [Jul 21 15 14:19 ]:
>   Hey, I understand that I currently can do
>
>See [Discussion](#EVAL).
>
># Discussion {#EVAL}
>
>The quick brown fox jumps away.
>
>   However there are several issues with this.
>    1. If I change the heading I need to rechange it everywhere :( I use
>       markdown with pandoc to get an abstraction over such details and
>       IMO it would be nice if I could somehow just put the ID there.

Well, you can do this:

    See [Discussion].

    # Discussion

or

    See [the section discussing this below][Discussion]

    # Discussion

or

    See [Discussion].

    # Discussion {#eval}

>    2. I can't reference figures and tables it seems.

Correct, something needs to be done about this,
but it's more complex because of numbering etc.
I think there's at least one issue on the tracker
about this already - did you search?

**Comment by sils1297** [comment]
duplicate of https://github.com/jgm/pandoc/issues/813
