### ISSUE TITLE
Header Link Shortcuts fail in Markdown to PDF or LaTeX conversion

### ISSUE THREAD

**Issue by jabofh** [jgm/pandoc#2321]
I recently had to update an older document; and noticed that the conversion from Markdown to LaTeX or PDF failed on links to Headings.

Using constructs like "`head to [My Heading] for more`", or even "`go to [My Heading][]`" seems to generate:

```{.latex}
{[}My Heading{]}
```

and

```{.latex}
{[}My Heading{]}{[}{]}
```

respectively, and where "`the [previous section][My Heading]`" generates code similar to:

```{.latex}
the
\href{My\%20Heading}{previous section}
```

I have disabled all custom templates and Header Includes; using the following command to produce the LaTeX file:

    /usr/local/bin/pandoc --smart --standalone \
    -f markdown+implicit_header_references+yaml_metadata_block \
    -V papersize:"a4paper" \
    --variable mainfont="CMU Sans Serif" \
    --variable sansfont="CMU Sans Serif" \
    --variable monofont="CMU Typewriter Text" \
    --variable fontsize=11pt -V geometry:margin=2.5cm \
    --latex-engine=xelatex \
    --toc --toc-depth=3 --number-sections --no-tex-ligatures \
    -o myDoc.tex myDoc.md

I have tried `xelatex`, `pdflatex` and `lualatex`; all with similar results.

I used this adapted snippet from the README to verify:

```{.markdown}
# Header identifiers in HTML, LaTeX, and ConTeXt #

## Extension: `implicit_header_references` ##

Pandoc behaves as if reference links have been defined for each header.
So, instead of

    [header identifiers](#header-identifiers-in-html)

which should generate "[header identifiers](#header-identifiers-in-html)" (it fails,
but [this works](#header-identifiers-in-html-latex-and-context)) you can simply write

    [header identifiers]

(for [header identifiers]) or,

    [header identifiers][]

(for [header identifiers][]), or

    [the section on header identifiers][header identifiers]

(for [the section on header identifiers][header identifiers]).
```

**Comment by jgm** [comment]
I am unable to reproduce the problem.  Let's start with the
simplest possible case:

```
% pandoc -t latex
# My header

See [My header]

\hyperdef{}{my-header}{\section{My header}\label{my-header}}

See \hyperref[my-header]{My header}
```

That appears to work properly.  Does it behave differently
for you?

Note that the header you're linking to must exist in the
Markdown file if you want the implicit header links to work.
Perhaps that is your problem.

**Comment by jabofh** [comment]
Here is (probably) the shortest example I could get to reliably fail; I'm using

    /usr/local/bin/pandoc -f markdown -t latex Stuffs.md -o Stuffs.pdf

to convert.

```{.tex}
---
title: Of FOO, Bar, XYZZY and PLUGH
author: Some Dude
...

# Headings #

Lorem ipsum.

## Headings and boom ##

[The Magic Word is XYZZY], [no, it's PLUGH][Or Was it PLUGH?]!

## The Magic Word is XYZZY

Link to [Headings] and to [Headings and boom]...

No? Okay, link to [Headings][] and to [Headings and boom][]...

Still not?!

Okay then: Link to [Headings](#headings) and to [Headings and boom](#headings-and-boom)...

## Or Was it PLUGH?

Lorem ipsum, etc, etc...
```

Without fail it, on my side at least, ens up not linking ` [Headings]` or ` [Headings and boom]`.

Currently I work around by simply linking with the `[foo](#foo)` syntax, but it seems like a regression (ie. I seem to recall that it used to work… 😊)

**Comment by hftf** [comment]
Is this just caused by the atx-style `# Heading #` syntax?

<pre>
$ cat << EOF | pandoc -f markdown -t native
> # foo
> [foo]
> 
> # bar #
> [bar]
> EOF
[Header 1 ("foo",[],[]) [Str "foo"]
,Para <ins>[Link [Str "foo"] ("#foo","")]</ins>
,Header 1 ("bar",[],[]) [Str "bar"]
,Para <ins>[Str "[bar]"]</ins>]
</pre>

**Comment by jgm** [comment]
Yes, it appears that the implicit links fail when you
have the optional `#`s at the end of an ATX heading.
This shouldn't be hard to fix.

+++ Ophir Lifshitz [Jul 22 15 14:47 ]:

**Comment by hftf** [comment]
NB. this affects setext headings with extra spaces as well.
