### ISSUE TITLE
Using CTeX classes for Chinese users in LaTeX

### ISSUE THREAD

**Issue by ghost** [jgm/pandoc#2322]
Currently, Pandoc provides an option `-V CJKmainfont = "foo"` to set Chinese font with the `xeCJK` package under the LaTeX engine XeLaTeX. However, this is not a good way for Chinese users.

As a developer of [the CTeX Collection](https://github.com/CTeX-org/ctex-kit), I would recommend the CTeX classes for Pandoc to match the demand of Chinese users of Pandoc.

The CTeX Collection provides three new classes for Chinese users. They are `ctexart`, `ctexbook` and `ctexrep`. It is apparently that `ctexart` corresponds to `article`, `ctexbook` corresponds to `book` and `ctexrep` corresponds to `report`.

What's more, CTeX classes have a mechanism that could auto-detect user's OS and to set appropriate fonts for Chinese and they could work under pdfLaTeX, XeLaTeX and also LuaLaTeX. As a result, users do not need to set `CJKmainfont` anymore and do note neet to set `--latex-engine=xelatex` any longer.

**Comment by jgm** [comment]
This sounds like a good solution (and could be achieved by
users with a custom template).  But I try not to make the
default templates depend on too many external packages
(especially ones that are not in basic default collections
like texlive-recommended on debian or MacTeX-basic).  So I'm
not inclined tochange the default templates.

+++ Liam Huang [Jul 22 15 23:38 ]:

**Comment by LiamHuang0205** [comment]
@jgm 

Actually, this will not bother you.

If someone (specifically, a Chinese LaTeX and Pandoc user) wants to use Chinese in document, he/she has to install packages more than the TeX-Live-recommended and thus no dependance issues will happen.

I think a better way is to add a `-lang` option. If this option is specified to `chinese`, then load CTeX classes by default, instead of the standard LaTeX classes. Note that, this option is set for users who wants to use Chinese in their documents, and requiring the installation of the CTeX collection is in due course.

**Comment by jgm** [comment]
+++ Liam Huang [Jul 23 15 09:14 ]:
>   [1]@jgm
>
>   Actually, this will not bother you.
>
>   If someone (specifically, a Chinese LaTeX and Pandoc user) wants to use
>   Chinese in document, he/she has to install packages more than the
>   TeX-Live-recommended and thus no dependance issues will happen.
>
>   I think a better way is to add a -lang option. If this option is
>   specified to chinese, then load CTeX classes by default, instead of the
>   standard LaTeX classes. Note that, this option is set for users who
>   wants to use Chinese in their documents, and requiring the installation
>   of the CTeX collection is in due course.

But one can use Chinese without CTeX currently, correct?

**Comment by LiamHuang0205** [comment]
Yes indeed. But the xeCJK package is also a part of CTeX-kit, as you can see. 

My suggestion will not introduce any new dependence under the default situation, only those who need these classes would have to install them, I mean the collection. That is, this change will not influence users that work under the default.

Pandoc depends on the CTeX collection if and only if one specify -lang=chinese explicitly. Hence the dependence issue will not be a big problem.

**Comment by ZelphirKaltstahl** [comment]
> Currently, Pandoc provides an option -V CJKmainfont = "foo" to set Chinese font with the xeCJK package under the LaTeX engine XeLaTeX. However, this is not a good way for Chinese users.

Note: It should be `-V CJKmainfont="foo"`, otherwise it'll give the error: `pandoc: =: openFile: does not exist (No such file or directory)`. But still it doesn't use the specified font for rendering the author in the PDF document.

**Comment by ZelphirKaltstahl** [comment]
Found a way to render Chinese font:

Add the following to your pandoc template:
`\usepackage{xeCJK}
\setCJKmainfont[]{WenQuanYi Micro Hei}`

**Comment by mb21** [comment]
Closing this.... see also https://github.com/jgm/pandoc/wiki/Pandoc-with-Chinese
