### ISSUE TITLE
html to latex: tables are too wide

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#2325]
Hi,

With this html file:
```
<table>
  <tr>
   <th>Tipus d'activitat</th>
   <th>Objectius</th>
   <th>Verbs (principals)</th>
   <th>Actors</th>
  </tr>
  <tr>
   <td>3 actes</td>
   <td>Modelitzar</td>
   <td>modelitzar</td>
   <td>professor-classe, professor-grups (es pot plantejar l'activitat en petits grups de recolsament mutu)</td>
  </tr>
</table>
```

and this command `pandoc -f html -t latex a.html  -o a.pdf`, I get the table overpassed the width of the paper.

Can you simply change `\begin{longtable}[c]{@{}llll@{}}` for paragraph mode?

Thanks,

**Comment by jgm** [comment]
You can fix this by specifying column widths (e.g. as
percentages) in your HTML table.  Otherwise pandoc
has no way of knowing how wide to make each column.

Try with

```
<table>
  <col width="30%"/>
  <col width="20%"/>
  <col width="20%"/>
  <col width="20%"/>
  <tr>
   <th>Tipus d'activitat</th>
   <th>Objectius</th>
   <th>Verbs (principals)</th>
   <th>Actors</th>
  </tr>
  <tr>
   <td>3 actes</td>
   <td>Modelitzar</td>
   <td>modelitzar</td>
   <td>professor-classe, professor-grups (es pot plantejar l'activitat en petits
 grups de recolsament mutu)</td>
  </tr>
</table>
```

**Comment by somenxavier** [comment]
What if I just want to specify the last column width? Is it possible?

**Comment by somenxavier** [comment]
This is not exactly what I want. I want that all the contents fit in the page width.
By the other hand, how can I specify the margins? By default latex has wider margins...

**Comment by somenxavier** [comment]
On the other hand, this works:
```
[xan@argonia proves]$ pandoc -f html -t rst a.html  > a.rst
[xan@argonia proves]$ pandoc -f rst -t latex a.rst -o  a.pdf
```

So, is it incongruent?

**Comment by jgm** [comment]
+++ Xavier [Jul 23 15 09:23 ]:
>   This is not exactly what I want. I want that all the contents fit in
>   the page width.

Sorry.  Default latex table packages require you to specify
a width.

>   By the other hand, how can I specify the margins? By default latex has
>   wider margins...

Then make sure the percentage widths add up to 100%.

**Comment by somenxavier** [comment]
OK. I needed something like `<table width="100%;">`

**Comment by marcoms** [comment]
So is it not possible for pandoc add this table metadata to the generated LaTeX automatically? Defaulting to `(100% / number of columns)` would be a better alternative to allowing tables to overflow out of the page, no?

**Comment by jgm** [comment]
Problem is that you wouldn't always want to set each column
to a fixed width of (100%/numcolumns).

If the cell contents are fairly short, you get better layout
with a "simple" table, with no fixed column widths information.

There's no easy way to determine whether the cell contents
are long enough that we'll need the fixed widths.

+++ Marco Scannadinari [Feb 28 16 12:06 ]:
