### ISSUE TITLE
RFEAllow creating graphs as figures

### ISSUE THREAD

**Issue by sils** [jgm/pandoc#2326]
Hi,

there's a script (mddia) which can create graphs in markdown and using it with pandoc is cool and easy. See https://github.com/nichtich/ditaa-markdown . It has the drawbacks of not providing many options, not providing an alt tag and only generating an _image_.

Here's a proposal for a better solution: it would be pretty simple to realize a similar syntax to what mddia uses for doing dot/graphviz graphics in latex. The dot code can simply be kept and this plugin can be used:
http://www.duocoding.nl/blog/249/how-to-embed-dot-graphs-graphviz-in-latex

This has the major advantage that proper latex code will be crreated out of the graph and not an image that is probably wrongly scaled for the page.

**Comment by ericoporto** [comment]
I would be very interested in a feature like this, being able to convert ascii typed diagrams into png to figures inside the document to print nice pdfs of md typed manuals.

**Comment by jgm** [comment]
This can be done via filters.
