### ISSUE TITLE
reveal.js: Headers are not generated correctly when having inline image only slide

### ISSUE THREAD

**Issue by Quintasan** [jgm/pandoc#2329]
When you try to create an inline image only slide the next slide will fail to parse.
I'm running pandoc 1.15.0.6

Minimal working example:
````
# Test

## Image slide 1

![Placekitten](http://placekitten.com/200/300)\

## This will fail

## Image slide 2

![Placekitten](http://placekitten.com/200/300)\
However

## This will not
````
In case the description is not clear:
![image](https://cloud.githubusercontent.com/assets/6539261/8891164/b17dccd0-331e-11e5-87f8-55907b507068.png)

**Comment by jgm** [comment]
+++ Michał Zając [Jul 25 15 13:48 ]:

>![Placekitten](http://placekitten.com/200/300)\
>
>## This will fail

Why the backslash after the image? In pandoc's markdown,
that's a hard linebreak (`<br>` tag).  This means that
the next line is not recognized as a blank line, which
is required before the heading.

Either leave off the backslash or put an extra
blank line before the header.

Btw, if you simply want to defeat treating the image
as a captioned figure, what you probably want is a backslash
+ space combination, not backslash + newline.

**Comment by Quintasan** [comment]
(What I really want to do is to have a named section with only image inside, no headers, but that's outside of scope of this bug)

Well, I just basically pasted what the documentation [said](http://pandoc.org/README.html#images), namely:
````
http://pandoc.org/README.html#images
````

I didn't realize that the next line wouldn't be recognized as a blank line – my bad then.

**Comment by jgm** [comment]
+++ Michał Zając [Jul 25 15 16:32 ]:
>   (What I really want to do is to have a named section with only image
>   inside, no headers, but that's outside of scope of this bug)
>
>   Well, I just basically pasted what the documentation [1]said, namely:
>http://pandoc.org/README.html#images

Aha, it's a documentation bug.  I probably had my editor
remove line-end spaces and removed the one that should be
there!

**Comment by Quintasan** [comment]
On a sidenote is it possible to somehow:
a) have some style apply only to the generated header (not the whole section),
b) don't generate headers automatically?

Currently I'm circumventing the issue by removing the headers by hand but that's cumbersome. The first approach would be nice but I have no idea about the complexity of such solution. Technically I could write my slides using HAML or Slim, since they give more control, but I'd rather not reinvent the wheel if possible.

**Comment by jgm** [comment]
You can create a slide without a header using a horizontal
rule (see the User's Guide on slide shows).

You can also attach a class to a header

    # Header {.likethis}

It will be attached to the enclosing section tag in
HTML, but you can style with CSS using

    section.likethis h1 { }

+++ Michał Zając [Jul 27 15 01:36 ]:

**Comment by Quintasan** [comment]
@jgm Thanks!
