### ISSUE TITLE
LaTeX `\clearpage` and `\newpage` are ignored

### ISSUE THREAD

**Issue by Hi-Angel** [jgm/pandoc#2330]
Pandoc ignores LaTeX `\clearpage` and `\newpage`. A minimal LaTeX to reproduce the problem:

	\documentclass{article}

	\begin{document}

	\title{Hello World}

	\clearpage\section{First page}
	\newpage
	Second page...
	\clearpage\section{Third page}
	...text...

	\end{document}

The example should produce a three pages document. However, with the command `pandoc -f latex -t odt -o output.odt test2.tex` the app produces a single page .odt document.

*Pandoc version is 1.15.0.6*

**Comment by jgm** [comment]
Pandoc's document model contains nothing corresponding to a
page break, so there's currently nothing we can do with
these but ignore them.

+++ Hi-Angel [Jul 26 15 08:45 ]:

**Comment by Hi-Angel** [comment]
That's sad ☹ Could this be added? At the present moment the only way to do a page-wise formatting to provide someone with an Office format — is to write in an Office tools, which is often uncomfortable to do.

**Comment by jgm** [comment]
See #1934
