### ISSUE TITLE
un-escaped characters for markdown output

### ISSUE THREAD

**Issue by tsagkase** [jgm/pandoc#2334]
Isn't the following a bug?

    $ echo '<a href="http://example.com">][</a>' | pandoc -f html -t markdown
    [][](http://example.com)

**Comment by jgm** [comment]
The most recent version of pandoc gives this output:

```
[\]\[](http://example.com)
```

So I believe this has already been resolved.

+++ tsagkase [Jul 28 15 06:17 ]:

**Comment by tsagkase** [comment]
I should have stated I'm running version 1.12.4.2 on debian. I tried it out on Win 1.15.0.6 and it does work. However, on this latest version I get the same kind of problem asciidoc.

    $ echo '<a href="http://example.com">][</a>' | pandoc -f html -t asciidoc
    http://example.com[][]

Maybe I should rename the issue?

**Comment by jgm** [comment]
Why don't you open a new issue for asciidoc?
Also, please link to the relevant escaping rules in asciidoc
documentation.

+++ tsagkase [Jul 29 15 01:20 ]:

**Comment by tsagkase** [comment]
New issue https://github.com/jgm/pandoc/issues/2337 created for asciidoc. Closing this one.
