### ISSUE TITLE
Error during intalling pandoc via cabal

### ISSUE THREAD

**Issue by VidhyaApple** [jgm/pandoc#2339]
When am trying to install pandoc, am getting following error.

[root@gains [/]# cabal update
Downloading the latest package list from hackage.haskell.org
Skipping download: Local and remote files match.
Note: there is a new version of cabal-install available.
To upgrade, run: cabal install cabal-install
root@gains [/]#  cabal install cabal-install
Resolving dependencies...
Configuring network-2.6.2.1...
Configuring random-1.1...
Configuring stm-2.4.4...
Configuring Cabal-1.22.4.0...
Configuring text-1.2.1.3...
Configuring transformers-0.4.3.0...
Configuring zlib-0.5.4.2...
Failed to install network-2.6.2.1
Build log ( /root/.cabal/logs/network-2.6.2.1.log ):
Failed to install random-1.1
Build log ( /root/.cabal/logs/random-1.1.log ):
Failed to install stm-2.4.4
Build log ( /root/.cabal/logs/stm-2.4.4.log ):
Failed to install transformers-0.4.3.0
Build log ( /root/.cabal/logs/transformers-0.4.3.0.log ):
Failed to install text-1.2.1.3
Build log ( /root/.cabal/logs/text-1.2.1.3.log ):
Failed to install zlib-0.5.4.2
Build log ( /root/.cabal/logs/zlib-0.5.4.2.log ):
Failed to install Cabal-1.22.4.0
Build log ( /root/.cabal/logs/Cabal-1.22.4.0.log ):
.
.
.

[79 0f 79] Compiling Main             ( /tmp/Cabal-1.22.4.0-21414/Cabal-1.22.4.0/dist/setup/setup.hs, /tmp/Cabal-1.22.4.0-21414/Cabal-1.22.4.0/dist/setup/Main.o )
Linking /tmp/Cabal-1.22.4.0-21414/Cabal-1.22.4.0/dist/setup/setup ...
cabal: Error: some packages failed to install:
Cabal-1.22.4.0 failed during the configure step. The exception was:
/tmp/Cabal-1.22.4.0-21414/Cabal-1.22.4.0/dist/setup/setup: runProcess:
runInteractiveProcess: exec: permission denied (Permission denied)
HTTP-4000.2.20 depends on text-1.2.1.3 which failed to install.
cabal-install-1.22.6.0 depends on Cabal-1.22.4.0 which failed to install.
mtl-2.2.1 depends on transformers-0.4.3.0 which failed to install.
network-2.6.2.1 failed during the configure step. The exception was:
user error (The package 'network' requires Cabal library version -any && >=1.8
but no suitable version is installed.)
network-uri-2.6.0.3 depends on text-1.2.1.3 which failed to install.
parsec-3.1.9 depends on text-1.2.1.3 which failed to install.
random-1.1 failed during the configure step. The exception was:
user error (The package 'random' requires Cabal library version -any && >=1.8
but no suitable version is installed.)
stm-2.4.4 failed during the configure step. The exception was:
user error (The package 'stm' requires Cabal library version -any && >=1.10
but no suitable version is installed.)
text-1.2.1.3 failed during the configure step. The exception was:
user error (The package 'text' requires Cabal library version -any && >=1.8
but no suitable version is installed.)
transformers-0.4.3.0 failed during the configure step. The exception was:
user error (The package 'transformers' requires Cabal library version -any &&
>=1.6 but no suitable version is installed.)
zlib-0.5.4.2 failed during the configure step. The exception was:
user error (The package 'zlib' requires Cabal library version -any && >=1.8
but no suitable version is installed.)

(Note: Linux CentOS 64 bit
         Cabal path->  /root/.cabal/bin/cabal)

**Comment by jgm** [comment]
This is actually a problem installing cabal-install.  Something is messed up with your Haskell environment, but it's not a pandoc-specific issue, so I'm closing this here.

You should take a look at the build logs that are referred to in the output above.
