### ISSUE TITLE
Disabling all math parsing in Markdown to HTML

### ISSUE THREAD

**Issue by vsbuffalo** [jgm/pandoc#2344]
As far as I can tell, there's no way to disable pandoc from converting a Markdown line like:

    $$ \frac{2 y}{x} $$

into 

    <p><br /><span class="math"> $$ \frac{2 y}{x} $$</span><br /></p>

I'd like to handle all math parsing entirely with MathJax in HTML and the extra `<p><br /><span class="math"> ...</span><br /></p>` tags are interfering with my CSS styles (especially the breaks). Would it be possible to have a command line option that overrides this, completely disabling pandoc from inserting these tags? I run pandoc with:

    pandoc --smart --no-highlight --to html5 infile.md

**Comment by mb21** [comment]
You can disable the  `tex_math_dollars` and `raw_tex` extensions of the markdown reader:

     pandoc -f markdown-tex_math_dollars-raw_tex infile.md

**Comment by vsbuffalo** [comment]
Thanks @mb21! and my apologies for overlooking this.

**Comment by jgm** [comment]
Try with the `--mathjax` command-line option!



+++ Vince Buffalo [Aug 04 15 00:36 ]:
