### ISSUE TITLE
Concert Markdown to pdf with css styling

### ISSUE THREAD

**Issue by ladislas** [jgm/pandoc#2345]
Is it possible to use css to stylise the pdf output?

**Comment by adunning** [comment]
No; the PDF is generated through LaTeX. The mailing list is a better place for general questions, by the way.

**Comment by jgm** [comment]
Closing here, feel free to ask questions on pandoc-discuss.

**Comment by ladislas** [comment]
okay, thanks for the feedback! :)

I'm going to learn latex templating, could be useful in the future ;)
