### ISSUE TITLE
Inconsistent spacing requirements in Block Quotations

### ISSUE THREAD

**Issue by miltonrg** [jgm/pandoc#2346]
The Pandoc User Guide defines a Block Quotation as a block
"with each line preceded by a > character and a space. (The > need not start at the left margin, but it should not be indented more than three spaces.)"

However, pandoc will block quote any of these

>#Heading

>text

>|  indented address

although the following correctly requires 1+4=5 spaces preceding the verbatim \text\

>     verbatim \text\

The results are confusing. Could Block Quotations be consistently indicated by > followed by a space, so the first three examples are not block quoted?

**Comment by ousia** [comment]
@miltonrg, your sample:

``` md
    #Heading

    text

    | indented address

    verbatim \text\
```

outputs the following HTML code ([with latest stable release](http://pandoc.org/try/?text=++++%23Heading%0A%0A++++text%0A%0A++++|+indented+address%0A%0A++++verbatim+\text\%0A&from=markdown&to=html)):

``` html
<pre><code>#Heading

text

| indented address

verbatim \text\</code></pre>
```

**Comment by miltonrg** [comment]
ERm, I didn't realise the bug tracker  was in markdown, so it has formatted my typing on send, kind of proving my point. What I typed was >#Heading, for example. Guess I'd better verbatim the examples. Here goes...

The Pandoc User Guide defines a Block Quotation as a block
"with each line preceded by a > character and a space. (The > need not start at the left margin, but it should not be indented more than three spaces.)"

However, pandoc will block quote any of these

```````
>#Heading

>text

>| indented address
`````````````````
although the following correctly requires 1+4=5 spaces preceding the verbatim \text\

```````
>     verbatim \text\
````````````````

The results are confusing. Could Block Quotations be consistently indicated by > followed by a space, so the first three examples are not block quoted?

**Comment by mb21** [comment]
I believe the README should be corrected, since almost all markdown processors interpret `>text` [as a blockquote](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Etext). So it should say:

> A block quotation is one or more paragraphs or other block elements (such as lists or headers), with each line preceded by a > character and a**n optional** space.

**Comment by miltonrg** [comment]
But the space is NOT optional. Otherwise > followed by four spaces would produce verbatim text in a comment block, which it doesn’t. There are many other examples of this, typically involving blocks nested within blocks, where the count of leading spaces is significant. If you amend the docs to say that the space is optional you will merely place one inconsistency with another. Anyone in future who wants to do this nesting successfully will need to arrange a series of experiments and interpret the results in order to work out what pandoc is actually doing, as I had to in this case.

**Comment by jgm** [comment]
+++ Robert Milton [Aug 06 15 12:17 ]:
>   But the space is NOT optional. Otherwise > followed by four spaces
>   would produce verbatim text in a comment block, which it doesn’t.

I already added some text that addresses this and your other
points.  See the commit.

>   There are many other examples of this, typically involving blocks nested
>   within blocks, where the count of leading spaces is significant. If you
>   amend the docs to say that the space is optional you will merely place
>   one inconsistency with another. Anyone in future who wants to do this
>   nesting successfully will need to arrange a series of experiments and
>   interpret the results in order to work out what pandoc is actually
>   doing, as I had to in this case.
