### ISSUE TITLE
Latex to ePub - multiple args environment and custom commands

### ISSUE THREAD

**Issue by jbardon** [jgm/pandoc#2347]
Everything works great to convert .tex files to .epub files except in one special case.
Actually, If I declare a custom command within I use an environment with multiple args (as tabular) pandoc throw me an error:

```
% pandoc Example.tex -f latex -t epub -o Example.epub
pandoc: 
Error at "source" (line 21, column 11):
unexpected "{"
expecting letter or lf new-line
```

Here is my Example.tex (line 21 is the empty line after \customcmd call):

```
\documentclass{book}

\newcommand{\customcmd}[1]{
	\begin{tabular}{|l|r|}
		\hline
		command & #1 \\
		\hline
	\end{tabular}
}

\title{Title}
\author{Jeremy}

\begin{document}

\chapter{First chapter}
\customcmd{hello} 

\end{document}
```

Not sure if it is related to my custom command, the fact I use an environment with multiple args or both combination. However this file works well with Latex so the trouble may be with pandoc here.

**Comment by nkalvi** [comment]
@jbardon Which version of Pandoc are you using (and platform)? 
I don't get the error with 1.15.0.5 (using the sample above).

**Comment by jbardon** [comment]
Actually I installed pandoc with Homebrew because I am on OSX. So it sounds like I didn't get the last release but in the repository I found this (not sure if it's relevant):  https://github.com/jgm/pandoc/blob/master/osx/distribution.xml#L14

```
% pandoc --version
pandoc 1.13.2
Compiled with texmath 0.8.0.1, highlighting-kate 0.5.11.1.
[...]
```

**Comment by nkalvi** [comment]
I installed it using the binary distribution from https://github.com/jgm/pandoc/releases/tag/1.15.0.6 (it is newer than what I have). Could you please try with the latest from there, if possible?

**Comment by jbardon** [comment]
Indeed it works better with panda's last release, thank's you ! Yet I get some display troubles with the following sample: 

```
\documentclass{book}
\usepackage{CJKutf8}

\newcommand{\hanyu}[1]{
	\begin{CJK}
		#1
	\end{CJK}
	\sbox0{\input{utf8.def}}
}

\title{Example}
\author{Jeremy}

\begin{document}
\chapter{First chapter}
	
\begin{tabular}{|c|l|l|}
  \hline
  
  \hanyu{你好} & hello\\
  \hanyu{再见} & good bye\\
  
  \hline
\end{tabular}

\end{document}
``` 

This document displays chinese characters with a special package. In the .epub version it seems like the tabular is not used to build the page.

**Comment by nkalvi** [comment]
@jbardon I'm not well versed in LaTex. I'm not sure which variant of TeX package you are using. Anyway, could you take a look at this: http://tex.stackexchange.com/questions/17611/how-does-one-type-chinese-in-latex

**Comment by jbardon** [comment]
Sorry I did a mistake while writing this sample for testing. Thank's for the link but I just miss some extra arguments, here is a version which works with pdflatex:

```
\documentclass{book}
\usepackage{CJKutf8}

\newcommand{\hanyu}[1]{
    \begin{CJK}{UTF8}{gbsn}
        #1
    \end{CJK}
    \sbox0{\input{utf8.def}}
}

\title{Example}
\author{Jeremy}

\begin{document}
\chapter{First chapter}

\begin{tabular}{|c|l|}
  \hline

  \hanyu{你好} & hello\\
  \hanyu{再见} & good bye\\

  \hline
\end{tabular}

\end{document}
```
It seems like the extra arguments for CJK (that I forgot to add) are not used by pandoc.

**Comment by nkalvi** [comment]
@jbardon I haven't figured out why the above fails to produce the expected output. 
May I suggest this workaround while you wait for a better answer:

Contents of `2347.md`:
```latex
---
title: Example
author: Jeremy
documentclass: book
header-includes:
     - \usepackage{CJKutf8}
---

\newcommand{\hanyu}[1]{
    \begin{CJK}{UTF8}{gbsn}
        #1
    \end{CJK}
    \sbox0{\input{utf8.def}}
}

\chapter{First chapter}

\begin{tabular}{|c|l|}
  \hline

  \hanyu{你好} & hello\\
  \hanyu{再见} & good bye\\

  \hline
\end{tabular}

```

with Pandoc command similar to this:
`pandoc 2347.md -o 2347.pdf`

**Comment by jbardon** [comment]
I didn't know it was possible to include Latex code in a Markdown document (only with pandoc I guess ?). Good idea but unfortunately the purpose was to convert my Latex into an ebook and I already have a pdf version because I used latex.

Whatever, thank's a lot for your reactivity you did a nice job by creating pandoc ! May I will try to find out another way to do what I want, if I did it and succeed I will give you some news :)

**Comment by nkalvi** [comment]
@jbardon I'm sorry, I lost sight of the original problem.
Yes, Pandoc is quite powerful - credit goes to @jgm and many others!

**Comment by mb21** [comment]
You can always go LaTeX -> Markdown, fix any issues there -> EPUB...

But the original issue of "Latex to ePub - multiple args environment and custom commands" is fixed in the newest pandoc, right?

**Comment by jbardon** [comment]
@mb21 you're right the original problem is fixed you can close it. I though my second problem was related to the first one (why I choose this title) but it's not.

I will try what you suggest, it can be a bit tricky because my latex document will evolve but it may be a good workaround, thank's! To clearly explain the second problem I created the #2348 issue for future answers.
