### ISSUE TITLE
"Could not determine PDF size"

### ISSUE THREAD

**Issue by sjackman** [jgm/pandoc#2350]
I'm rendering Markdown to DOCX, and I'm seeing the error `could not determine PDF size`. Both Mac OS and ImageMagick report that the PDF size is 522 x 504 pt (7.25 x 7 in). I can send you the PDF, if it's helpful. @GitHub issues unfortunately don't allow uploading PDF.

```
❯❯❯ make docx
pandoc --filter=pandoc-citeproc -o white-spruce-organelles.docx white-spruce-organelles.md
pandoc: Could not determine image size in `figure/mt-gene-order.pdf': could not determine PDF size
❯❯❯ identify figure/mt-gene-order.pdf
figure/mt-gene-order.pdf PDF 522x504 522x504+0+0 16-bit Bilevel Gray 33.3KB 0.000u 0:00.000
❯❯❯ pandoc --version
pandoc 1.15.0.6
```

**Comment by jgm** [comment]
Please put the PDF somewhere and link to it so we can have a look.

+++ Shaun Jackman [Aug 06 15 12:36 ]:

**Comment by sjackman** [comment]
https://www.dropbox.com/s/y99j939woc2vpaw/mt-gene-order.pdf

**Comment by jgm** [comment]
I noticed this in Text.Pandoc.ImageSize:

       Just Pdf  -> Left "could not determine PDF size" -- TODO

which accounts for what you're seeing.  Just need to write
the code for extracting image size from the PDF.  Or maybe
the JuicyPixels library will help with that.


+++ Shaun Jackman [Aug 06 15 13:19 ]:

**Comment by sjackman** [comment]
For now I've converted the PDF to PNG.
```sh
brew install imagemagick
convert -units PixelsPerInch -density 600 fig.pdf fig.png
```

**Comment by nsheff** [comment]
Hi, just wanted to follow-up on this. I'm having the same symptom as in #2381 -- markdown-included PDFs render fine in PDF output, but docx output shows "Read-error". Since it's been a few years since any comments on this thread I just wanted to see if there are any alternative recommendations at this point, or if it's still just pending "code for extracting image size from the PDF".

**Comment by mb21** [comment]
This issue was actually fixed by https://github.com/jgm/pandoc/commit/eeafb3fa773e992174dd460d093653cd77255ce5

@nsheff It's not possible to [include PDFs in docx files](https://github.com/jgm/pandoc/issues/2061).

**Comment by bogdanni** [comment]
It is possible though:
https://support.office.com/en-us/article/Add-a-PDF-to-your-Office-file-74819342-8F00-4AB4-BCBE-0F3DF15AB0DC

Word for Mac can display PDF figures in docx produced by pandoc (2.2.1), albeit the size (or at least the aspect ratio) appears wrong. Word for Windows doesn't display those figures.

Attempting to output to ODT produces this warning ([WARNING] Could not determine image size for '...pdf': could not determine PDF size).

**Comment by mb21** [comment]
@bogdanni, interesting! If you could post a minimal docx file that embeds a PDF and works cross-platform to #2061, that would be great. (Or even better, also the XML snippet responsible...)

**Comment by bogdanni** [comment]
The bad news is that Word for both Mac and Windows convert the PDF on insert into EMF. The attached is made with Word for Mac 16.15.
[pdf_mac.docx](https://github.com/jgm/pandoc/files/2057846/pdf_mac.docx)

**Comment by mb21** [comment]
Ah, so it's not actually embedding the PDF. I guess image conversion is currently out of scope for pandoc...
