### ISSUE TITLE
Lua custom writer doesn't get `$pagetitle$`, so HTML output gets an empty `<title>` tag

### ISSUE THREAD

**Issue by fasiha** [jgm/pandoc#2353]
First, I create the sample custom writer bundled with pandoc: `pandoc --print-default-data-file sample.lua > sample.lua`.

Then I dump the HTML template before I can use the custom writer: `pandoc -D html > html.html`.

Then when I try to render the following:
```
% My title
% Author Name

Hello world.
```
with `pandoc -t sample.lua -f markdown --template html.html test.md`, I see an empty `<title>` tag, but the title is correctly displayed in the `<h1 class="title">` tag.

If I don't use the custom Lua writer with the HTML template, i.e., `pandoc -s -t html -f markdown test.md`, the `<title>` tag is correctly filled in. (Exactly the same issue with `html5` template.)

I infer that when using the custom writer, pandoc doesn't set `$pagetitle$` which the HTML/HTML5 template needs for the `<title>` tag.

**Comment by fasiha** [comment]
This is with pandoc 1.15.0.6.

**Comment by jgm** [comment]
What version of pandoc?  (pandoc --version)

+++ Ahmed Fasih [Aug 08 15 05:37 ]:

**Comment by jgm** [comment]
If you look at src/Text/Pandoc/Writers/HTML.hs, lines 177
and following, you'll see that the HTML writer defines a
number of custom variables, including pagetitle.  So that's
why pagetitle isn't going through.  You can use title, but
that might cause problems if title contains any formatting.
Another option is to insert a metadata field `pagetitle`
before calling the lua writer; you can derive this
programatically from `title` using `stringify`, e.g. in
a filter, or you can just specify it on the command line
manually with `-m pagetitle="foo"`.

+++ Ahmed Fasih [Aug 08 15 05:37 ]:

**Comment by fasiha** [comment]
Thank you! This is helpful in understanding the problem at hand as well as the broader pandoc ecosystem. I didn't realize filters could create metadata fields (from reading the scripting tutorial I gathered that they just did AST transforms).

From your suggestion of creating a `pagetitle` metadata field before calling the Lua writer, I am guessing that there's no way for the Lua writer itself to create such a custom metadata field that pandoc would then pass to the template?

If that's the case, would it be safe to say that one ought to ideally implement custom writers in Haskell to have the full power of pandoc, rather than the Lua functionality which is a bit of a second-class citizen?

**Comment by jgm** [comment]
+++ Ahmed Fasih [Aug 08 15 17:14 ]:
>   Thank you! This is helpful in understanding the problem at hand as well
>   as the broader pandoc ecosystem. I didn't realize filters could create
>   metadata fields (from reading the scripting tutorial I gathered that
>   they just did AST transforms).

The metadata is part of the AST, so it's pretty simple to
insert things there in a filter.

>   From your suggestion of creating a pagetitle metadata field before
>   calling the Lua writer, I am guessing that there's no way for the Lua
>   writer itself to create such a custom metadata field that pandoc would
>   then pass to the template?

Correct.  The lua writer has read-only access to the
metadata; it can't change it.

>   If that's the case, would it be safe to say that one ought to ideally
>   implement custom writers in Haskell to have the full power of pandoc,
>   rather than the Lua functionality which is a bit of a second-class
>   citizen?

That's probably right.  But the huge advantage of lua is
that you can write a custom writer and run it with stock
pandoc, without recompiling etc.

**Comment by fasiha** [comment]
> Correct. The lua writer has read-only access to the
> metadata; it can't change it.
>

It this by design, or could this restriction be lifted in the future? I'm
making a filter that creates `pagetitle` and adds it to the metadata, & I'm
wondering if I should put a TODO reminder in it to check if Lua custom
writers can edit the metadata.

**Comment by jgm** [comment]
+++ Ahmed Fasih [Aug 08 15 21:05 ]:
>   > Correct. The lua writer has read-only access to the
>   > metadata; it can't change it.
>   >
>   It this by design, or could this restriction be lifted in the future?

None of the pandoc writers can modify the AST.  What the
HTML writer does is define template variables (not modify
the metadata).  It might be possible to add something to the
custom writer module to allow lua writers to do that.

**Comment by fasiha** [comment]
Would it be ok to create a separate issue to track progress on Lua custom writers editing template variables?

**Comment by jgm** [comment]
Yes, you could submit a request.  I think it's going to be a
bit complex to do this, though, and it may never happen.

+++ Ahmed Fasih [Aug 09 15 04:41 ]:
