### ISSUE TITLE
Change filename from README to README.md

### ISSUE THREAD

**Issue by sky-y** [jgm/pandoc#2361]
I recommend to change the filename of README to README.md .
Because:

- Some editors (Vim , Emacs, etc.) can automatically recognize .md extension and will open the .md file as Markdown mode. Then syntax highlighting for Markdown will be enabled.
- GitHub also will recognize .md extension and automatically enable syntax highlighting for Markdown.

**Comment by jgm** [comment]
Did you search for closed issues on this topic?

+++ Yuki Fujiwara [Aug 15 15 17:01 ]:

**Comment by sky-y** [comment]
Sorry but I searched only open issued. I didn't search for closed issue.
