### ISSUE TITLE
Design: Logo of Pandoc

### ISSUE THREAD

**Issue by sky-y** [jgm/pandoc#2362]
Let's discuss to make Pandoc logo.

The logo strongly represent the existence of Pandoc and briefly show what it is.
This will be useful when we make a presentation.
To expand Pandoc to the world, the logo will be important.

For example, this is a figure of open source software. Each product is presented with logo.

![open-source1-570x324](https://cloud.githubusercontent.com/assets/1078033/9291405/83bd73b4-43f8-11e5-906b-ff1bf6918020.jpg)

We need to discuss about:
- What is the concept of logo design?
- Who can design the logo or how can we recruit designers?

**Comment by jgm** [comment]
I think this would be better discussed on the pandoc-discuss mailing
list.  This tracker is not for open-ended questions, but for
specific bug reports and enhancement requests.

**Comment by sky-y** [comment]
Thank you for your comment.
I will close this issue and repost this issue to pandoc-discuss.
