### ISSUE TITLE
Option to generate EPUB with math in image file

### ISSUE THREAD

**Issue by dluciv** [jgm/pandoc#2363]
It would probably be great to allow saving formulae images as files among other images instead of storing them  in data URLs when generating EPUB. Many readers handle image files correctly but fail to show data URLs images.

**Comment by jgm** [comment]
I didn't know this.  Can you give a list of some readers
that can't handle data URLs?

+++ Dmitry V. Luciv [Aug 16 15 06:37 ]:

**Comment by dluciv** [comment]
Sure.

FBReader for Android is very good software overall, but unfortunately does not show base64-encoded formulae pictures.

Thank you!

On August 16, 2015 5:08:47 PM EET, John MacFarlane <notifications@github.com> wrote:
>I didn't know this.  Can you give a list of some readers
>that can't handle data URLs?
>
>+++ Dmitry V. Luciv [Aug 16 15 06:37 ]:
>>   It would probably be great to allow saving formulae images as files
>>   among other images instead of storing them in data URLs when
>generating
>>   EPUB. Many readers handle image files correctly but fail to show
>data
>>   URLs images.
>>
>>   —
>>   Reply to this email directly or [1]view it on GitHub.
>>
>>References
>>
>>   1. https://github.com/jgm/pandoc/issues/2363
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/2363#issuecomment-131554350

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by jgm** [comment]
Have you considered a bug report to FBReader?  After all,
this seems a useful feature, and not particularly hard to
implement, I would think.

+++ Dmitry V. Luciv [Aug 16 15 10:28 ]:
>Sure.
>
>FBReader for Android is very good software overall, but unfortunately does not show base64-encoded formulae pictures.
>
>Thank you!
>

**Comment by dluciv** [comment]
*Have you considered a bug report to FBReader?*

Surely ([now](https://github.com/geometer/FBReaderJ/issues/357) =)). Thank you!

**Comment by dluciv** [comment]
BTW it all was about EPUB2...

EPUB3 backend seems to print MathML only. Probably it could be useful option to support other math backends for EPUB3 too. In fact, there are a few sensible EPUB3 readers supporting all its features now.
