### ISSUE TITLE
ODT: Formula and image anchor attributes are exchanged

### ISSUE THREAD

**Issue by nogajun** [jgm/pandoc#2365]
1. Converted to Markdown file to ODT file.
2. Open the ODT file from LibreOffice.
3. Right-click on the formula or the image.
4. Check the "Anchor" of context menu.
5. Fomula anchor is "To Paragraph"(Correctly "As Character") and Image anchor is "As Character"(Correctly "To Paragraph") 

Markdown file:

```
## Formula

$a^2-b^2=(a-b)(a+b)$

* Good -> Anchor: "As Character"
* Bad -> Anchor: "To Paragraph"

## Image

![Haskell](https://wiki.haskell.org/wikiupload/4/4a/HaskellLogoStyPreview-1.png)

* Good -> "Anchor: To Paragraph"
* Bad -> "Anchor: As Character"
```

Command:

```
 $ pandoc -o convert-odt.odt convert-odt.md
```

Environment:

Debian GNU/Linux (sid)

```
ii  pandoc         1.13.2.1~dfsg-1.1   amd64    general markup converter
ii  pandoc-data    1.13.2.1~dfsg-1.1   all      general markup converter - data files

$ pandoc -v
pandoc 1.13.2.1
Compiled with texmath 0.8.2.2, highlighting-kate 0.5.12.
```

**Comment by jgm** [comment]
I'm sorry, I don't know much about OpenDocument or ODT, and
the original author of the OpenDocument writer has not been
responsive.

Here's the OpenDocument XML produced for your fragment:

```
<text:h text:style-name="Heading_20_2" text:outline-level="2">Formula</text:h>
<text:p text:style-name="First_20_paragraph"><text:span text:style-name="T1">a</text:span><text:span text:style-name="T2">2</text:span> − <text:span text:style-name="T3">b</text:span><text:span text:style-name="T4">2</text:span> = (<text:span text:style-name="T5">a</text:span> − <text:span text:style-name="T6">b</text:span>)(<text:span text:style-name="T7">a</text:span> + <text:span text:style-name="T8">b</text:span>)</text:p>
<text:list text:style-name="L1">
  <text:list-item>
    <text:p text:style-name="P1">Good -&gt; Anchor: &quot;As
    Character&quot;</text:p>
  </text:list-item>
  <text:list-item>
    <text:p text:style-name="P1">Bad -&gt; Anchor: &quot;To
    Paragraph&quot;</text:p>
  </text:list-item>
</text:list>
<text:h text:style-name="Heading_20_2" text:outline-level="2">Image</text:h>
<text:p text:style-name="FigureWithCaption"><draw:frame draw:name="img1"><draw:image xlink:href="https://wiki.haskell.org/wikiupload/4/4a/HaskellLogoStyPreview-1.png" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" /></draw:frame></text:p>
<text:p text:style-name="FigureCaption">Haskell</text:p>
```

I don't see anything here corresponding to your "anchor," so I presume defaults are being used.  I also don't see anything relevant in the generated styles or styles.xml.

Can you explain what "Anchor" means, and what the difference is between anchoring To Paragraph and As Character?

**Comment by hftf** [comment]
[Here](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1418758_253892949) is some documentation.

**Comment by jgm** [comment]
```
## Image

![Haskell](https://wiki.haskell.org/wikiupload/4/4a/HaskellLogoStyPreview-1.png)

* Good -> "Anchor: To Paragraph"
* Bad -> "Anchor: As Character"
```

Images, in general, can occur inside a paragraph.  So "as character" is the right default.  In this case, since the image is alone in its paragraph, and hence treated as a "figure," "to paragraph" might make sense.  But does it really make any difference here, since the image is the only thing in the paragraph?  What is the difference in how this renders in ODT with the two different anchoring options?

**Comment by mb21** [comment]
This has been a closing-candidate for almost a year, thus closing now.

If someone can provide the corrected OpenXML pandoc should produce, feel free to reopen.
