### ISSUE TITLE
Indented bullets in markdown lose indentation in mediawiki

### ISSUE THREAD

**Issue by ragesoss** [jgm/pandoc#2367]
When converting from markdown to mediawiki, this input:

```
* item
  * sub-item
  * sub-item 2
```

produces this output:

```
* item
* sub-item
* sub-item 2
```
The indentation / sub-item hierarchy is lost in the conversion. The actual corresponding mediawiki syntax would be either of these:

```
* item
:* sub-item
:* sub-item 2
```
or 

```
* item
** sub-item
** sub-item 2
```

**Comment by KurtPfeifle** [comment]
You have to indent each additional sublevel by 4 extra spaces. Then it works:

~~~
* item
    * sub-item 1
    * sub-item 2
~~~

It will produce:

~~~
* item
** sub-item 1
** sub-item 2
~~~

See also the docu:  http://pandoc.org/README.html#the-four-space-rule

**Comment by ragesoss** [comment]
Thanks, that's helpful. It would be better, though, if Pandoc also recognized the two-space format, since that's how most markdown implementations work.

**Comment by jgm** [comment]
Actually, there is a lot of variation among markdown implementations in this regard.  Many of the implementations that sometimes allow a two-space indent don't do so consistently:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+a%0A++-+b%0A++++-+c%0A++++++-+d%0A

More inconsistency with one-space indents:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+a%0A+-+b%0A++-+c%0A+++-+d%0A

Moreover, if you allow < 4 space indent, but retain Gruber's rule that indented code under a list item must be indented 8 spaces, you get an ugly situation.

In my view, the only implementations with really coherent rules for indented lists are those that adopt the 4-space rule, like pandoc, and those that conform to the CommonMark spec, which allows two-space indentation and alters Gruber's rule about indented code under list items in a way that ensures backwards compatibility with 4-space-rule implementations.
