### ISSUE TITLE
Markdown to EPUB doesn't include image declared in stylesheet

### ISSUE THREAD

**Issue by BruceEckel** [jgm/pandoc#2368]
When I convert from Markdown to EPUB using Pandoc, I include the flag:
**--epub-stylesheet=onjava.css**

**onjava.css** includes the following:

```
h1 {
    font-size:3em;
    padding:10px 60px;
    background-image:url('onjava-chapter.jpg');
    background-repeat:no-repeat;
    background-position-x: left;
    page-break-before: always;
    text-indent: 0;
}
```
And **onjava-chapter.jpg** is in the local directory.

However, in the generated EPUB, **onjava-chapter.jpg** is not included. I suspect this happens because of the indirection -- pandoc has to look at the CSS to see what might be needed.

**Comment by ousia** [comment]
@BruceEckel, have you tried to add `--epub-embed-font=onjava-chapter.jpg`?

I think this is the way to embed files in the output ePub document.

**Comment by BruceEckel** [comment]
That did it -- thank you!

I wouldn't necessarily have guessed that "embed-font" also works for images too...

**Comment by ousia** [comment]
> I wouldn't necessarily have guessed that "embed-font" also works for images too...

Neither did I. @jgm explained it in a similar issue (#1941).

And it seems that there are plans to scan the CSS file for media to be embedded.

**Comment by jgm** [comment]
Right, we don't parse the stylesheet to look for includes.

+++ Bruce Eckel [Aug 19 15 11:20 ]:

**Comment by lifepillar** [comment]
Fast-forward to (almost) 2020, is `--epub-embed-font` still the recommended way to embed CSS-referenced images into the output?

**Comment by jgm** [comment]
Maybe we should just rename the option `--epub-embed-file`?  (But this should be a new issue)

**Comment by lifepillar** [comment]
It seems to me that `--epub-embed-font` puts the specified file into a `fonts` directory. While I may put any file there, it doesn't seem the most logical thing. But I may open a new issue to discuss that: I just wanted to make sure that I wasn't missing any other option.

**Comment by jgm** [comment]
Guess we already have #1941 open
