### ISSUE TITLE
org reader should support export settings

### ISSUE THREAD

**Issue by nchachereau** [jgm/pandoc#2370]
When converting an Emacs org-mode file, it would be great if a subset of org-mode's export options was supported by Pandoc. These options allow for instance to automatically generate section numbers. See [org-mode's manual](http://orgmode.org/org.html#Export-settings) for more information.

I stumbled upon it because I wanted to use [gitit](http://gitit.net/) with my org files, and wanted to [disable automatic subscripts](http://orgmode.org/org.html#Subscripts-and-superscripts) for things like author_date.

**Comment by tarleb** [comment]
Support for the sub/superscript option plus three other export settings has been added with the latest release.

**Comment by tarleb** [comment]
Pandoc supports a couple of export settings now.  The remaining options either deal with features not yet available in pandoc, or don't make sense in the context of pandoc.  Please open a new issue if there is an export setting that I missed and that you'd like to see supported.
