### ISSUE TITLE
Docear4Word support

### ISSUE THREAD

**Issue by KOLANICH** [jgm/pandoc#2371]
There is a nice tool : [Docear4Word]( https://www.docear.org/software/add-ons/docear4word/download/). This tool allows to create a bibliography in bibtex and paste it into docx documents. Every cite is stored in hidden text and somewhere in the document you can paste bibliography which updates automatically. Cytes and bibliography are automatically sorted and styled. When converting docx to latex this cites are processed incorrectly. I'd be good docear4word cites to be transformed into latex ones and docear4word bibliography - into latex command to create bibliography with the same style.

**Comment by jgm** [comment]
I think this is too special-purpose to support.
