### ISSUE TITLE
footnotes in table column captions in LaTeX

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#2378]
I have noticed that footnotes in table captions do not work in LaTeX. I get

```
LuaTeX warning (dest): name{Hfootnote.4} has been referenced but does not exist,
 replaced by a fixed one
```

It seems this is a known LaTeX issue. There appears to be some sort of solution, however. See "[Footnotes in longtable captions](http://tex.stackexchange.com/q/50151/28495)."

**Comment by wilx** [comment]
MWE:

~~~~{.markdown}
          foo[^note1]
-------- ----------
X          23,39
Y          29,33

[^note1]: Foo bar baz.
~~~~

**Comment by mgansler** [comment]
You can use this as a workaround: 

	          foo\footnotemark{}
	-------- ----------
	X          23,39
	Y          29,33
	
	\footnotetext{Foo bar baz.}

**Comment by wilx** [comment]
See https://github.com/jgm/pandoc-templates/pull/208 for possible solution.

**Comment by tolot27** [comment]
I thought the fix will fix the issue, but it is still present in pandoc 1.19.1. Only the Workaround with  `\footnotemark{}` works.

I just have the used the plain example above and just converted it to pdf without supplying any additional parameter to pandoc (Win10, MikTeX).

**Comment by zeeMonkeez** [comment]
The issue still exists because there's a [typo in the commit](https://github.com/jgm/pandoc-templates/commit/1475299c9aebfe3e47c135d6653202db3b2f6696#commitcomment-22638236).
Also, this [will not work when there's a caption in the table](https://github.com/jgm/pandoc-templates/pull/208#issuecomment-309631622).

**Comment by zeeMonkeez** [comment]
A possible solution might be to use the `scrextend` package: https://tex.stackexchange.com/a/95905/19590
