### ISSUE TITLE
Wont use tex_math_dollars extension when converting Markdown to LaTeX

### ISSUE THREAD

**Issue by andrewhamon** [jgm/pandoc#2379]
I installed Pandoc using Homebrew for Mac. `pandoc -v` is reporting `pandoc 1.15.0.6`

Given test.md:
```markdown
$ 1 + 1 = 2 $
```

I am trying to convert to latex using the following command:

`pandoc test.md -o test.tex`

After this didn't produce the results I would like, I tried this:

`pandoc -f markdown+tex_math_dollars test.md -o test.tex`

to explicitly enable the `tex_math_dollars` plugin [described here.](http://pandoc.org/README.html#math)

Both commands lead to the following output:
```tex
\$ 1 + 1 = 2 \$
```

The output I am hoping for is:
```
$ 1 + 1 = 2 $
```

Forgive me if I am missing something extremely obvious.
Thanks!

**Comment by jgm** [comment]
You can't have spaces after the initial $ or before the
final one.  (This is because pandoc applies some heuristics
to distinguish math $'s from regular $'s.)

    $1 + 1 = 2$

+++ Andrew Hamon [Aug 31 15 14:40 ]:
