### ISSUE TITLE
pandoc-produced latex won't convert to pdf.

### ISSUE THREAD

**Issue by naught101** [jgm/pandoc#2380]
`pandoc dissectingPLUMBER.md -o PlumberII.latex --bibtex -s` works fine, and produces valid latex, but:

```{sh}
$ pandoc PlumberII.latex -o Plumber.pdf                     
! Undefined control sequence.
l.94 \autocites

pandoc: Error producing PDF from TeX source
```

The latex won't compile to PDF.

I guess I'm maybe missing a package, but it seems like pandoc should probably produce latex that it can handle by default, so either warn that those packages are missing, or produce older style latex that just works.

**Comment by jgm** [comment]
pandoc doesn't have a `--bibtex` option.  Did you mean `--biblatex`?
That would explain why `\autocites` was generated.

+++ naught101 [Aug 31 15 23:00 ]:

**Comment by naught101** [comment]
Sorry, yes, I meant `--biblatex`. I've never seen/used the `\autocites` command in latex, so I'm not sure what package I should be using to get it to work..

**Comment by jgm** [comment]
Some instructions here:
http://tex.stackexchange.com/questions/13509/biblatex-for-idiots

Pandoc ought to be including the commands you need.
Does the generated tex file include the lines

    \usepackage{biblatex}
    \addbibresource{yourbib}

in the preamble, and

    \printbibliography

at the end?

What version of pandoc are you using?  Are you using a
custom latex template (check for
~/.pandoc/templates/default.latex)?

+++ naught101 [Aug 31 15 23:55 ]:

**Comment by naught101** [comment]
ok, excuse my stupidity, this is a false alarm. I didn't think to inlcude the `--bibliography` argument in the latex->pdf conversion.

`pandoc PlumberII.latex -o PlumberII.pdf --bibliography Citations.bib --latex-engine=xelatex` works fine (`xelatex` for the character accents). Sorry for the hassle. At least maybe people will be able to search and find this now :)

**Comment by naught101** [comment]
Actually, can I convert this into a feature request? There's the option to include a `\bibliography{Citations}` command in a latex file, that pdflatex automatically uses to read in the bibliography.

Could we have a `--bibliography-file` or similar option, that just includes the bibliography call in the header, without actually converting pandoc references to text as `--bibliography` does? That would save one step of manual processing.

**Comment by jgm** [comment]
+++ naught101 [Sep 01 15 19:11 ]:
>   Actually, can I convert this into a feature request? There's the option
>   to include a \bibliography{Citations} command in a latex file, that
>   pdflatex automatically uses to read in the bibliography.
>
>   Could we have a --bibliography-file or similar option, that just
>   includes the bibliography call in the header, without actually
>   converting pandoc references to text as --bibliography does? That would
>   save one step of manual processing.

If you specify `--bibliography` and either `--natbib` or
`--biblatex`, it will give you native latex bibliographies
instead of having pandoc-citeproc do the conversion. Is that
what you haev in mind?

**Comment by naught101** [comment]
Yep, it certainly is thanks. I never fail to be impressed by pandoc :)
