### ISSUE TITLE
option to disable tightlist on conversion to latex

### ISSUE THREAD

**Issue by naught101** [jgm/pandoc#2383]
tightlist isn't always necessary, and it can be a bit annoying having to add it to your style file, especially if you're trying to follow a journal style. Can we have an option to disable it entirely?

**Comment by mb21** [comment]
try:

    - foo

    - bar

instead of:

    - foo
    - bar

see http://pandoc.org/README.html#lists

**Comment by naught101** [comment]
Hrm. Yeah, I know that's possible, but I'm not sure that this wouldn't still be a good idea. I prefer the tight list markdown formatting, and it also might make sense to have both formats available, but be able to fallback gracefully on normal lists for cases where they can't be used (e.g. for specific journal submissions). Similar to the reasoning behind #2384

**Comment by jgm** [comment]
You could always add `\let\tightlist\relax` to your latex header.

**Comment by hasufell** [comment]
> You could always add \let\tightlist\relax to your latex header.

Didn't work here. Had to do `\def\tightlist{}`
also see https://git.finf.uni-hannover.de/fachrat-informatik/pter/commit/1aa09704498c7520be832f87662a9ec25c3f1d8a

**Comment by naught101** [comment]
Hrm... Niether of these seem to work in beamer for me at the moment - have tried adding them both just after the tightlist definition in the beamer default template.
