### ISSUE TITLE
Support multiple dots in image filenames on latex / beamer / pdf output

### ISSUE THREAD

**Issue by gfelbing** [jgm/pandoc#2387]
- Given:
    - input: markdown
    - output: latex / beamer / pdf (maybe more)
- Case 1:
    - When:
        - Adding image with multiple dots in filename, i.e. `![Description](Image.foo.png)`
    - Then:
        - Pandoc exits with code 43: `! LaTeX Error: Unknown graphics extension: .foo.png.`
- Case 2:
    - When:
        - Adding image with multiple dots in filename using delimiters, i.e.  `![Description]({Image.foo}.png)`
        - (Syntax according to http://stackoverflow.com/a/9040813/3739067)
    - Then:
        - Pandoc exists with code 43: `pandoc: Could not find image '{Image.foo}.png', skipping...`

Currently I am adding the images with the `raw_tex` - extension using the "{}"-delimiters as a workaround. It would be great if pandoc supports the delimiter-syntax directly.

**Comment by jgm** [comment]
What pandoc version are you using? I couldn't reproduce the
case 1 problem with the latest version.


+++ gfelbing [Sep 07 15 03:01 ]:

**Comment by gfelbing** [comment]
Indeed - sorry for the inconvenience. I had the pandoc-1.13.2-1-amd64.deb package installed. After upgrading to pandoc-1.15.0.6-1-amd64.deb, i was able to add the image according to Case 1.
