### ISSUE TITLE
Error with pandoc v13 and higher: "could not find locale data for ENU-".

### ISSUE THREAD

**Issue by newhallroad** [jgm/pandoc#2388]
I first want to thank you for your work and generosity in making pandoc available and maintaining it. It is an extremely helpful tool and I really appreciate everything you do for it.

I am having a problem which seems to be similar to [#1548](https://github.com/jgm/pandoc/issues/1548) but I don't think it is identical.

I am using Windows 7. Pandoc works perfectly for me from the command line. I often specify a .csl file and a .bib file and it runs with no problem.

I have recently started using pandoc-mode in Emacs. I am using GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570. It runs fine unless I specify a .bib file. In that case I get the following errors:

	Running `C:\Users\<user-name>\path-to-pandoc\pandoc.exe --read=markdown --write=html --output=c:/Users/<user-name>/MobileSync/teaching//MJH4.lecturenotes.html --csl=c:/Users/<user-name>/path-to-csl/chicago-note-bibliography.csl --standalone --smart --bibliography=c:/Users/<user-name>/path-to-bibliography/My Library.bib'

	pandoc-citeproc.exe: could not find locale data for ENU-
	pandoc.exe: Error running filter pandoc-citeproc

I have tried this with and without the `--standalone` and `--smart` options. I have tried this with and without specifying a .csl file. I get the same result if I specify a .csl file with `<locale xml:lang="en">` in the `<style>` section. My Windows 7 system locale is `en-us`. I also get the same result whether I use the pandoc windows installer or whether I install pandoc with cabal.

I get these results for pandoc 13 and later. However, if I point pandoc-mode to version 1.12.4.2, it runs with no problem. For this reason, it seems likely to be a problem with pandoc itself (or pandoc-citeproc?) rather than anything to do with emacs.

**Comment by jgm** [comment]
You should ask the pandoc-mode maintainers about this.  It seems that you have a strange locale environment variable setting, at least within emacs.  They might understand why.

You can probably work around this by specifying the `locale` explicitly in your markdown file, in YAML metadata:

```
---
locale: en-US
...
```
