### ISSUE TITLE
Raw html appears in latex output

### ISSUE THREAD

**Issue by arsaber101** [jgm/pandoc#2390]
I'm using the same markdown file for two outputs : latex and html. While raw latex does not appear in html output, raw html is read and written in latex output. Example :

* markdown file

```
#Test

<p>&#42; This should be read and written only in html output.</p>

\begin{center}* This should be read and written only in latex output.\end{center}

* This should be read and written in both output.
```

* html output

```
pandoc -f markdown -t html -o test.html test.md
```

```

<h1 id="test">Test</h1>
<p>
* This should be read and written only in html output.
</p>

<ul>
<li>This should be read and written in both output.</li>
</ul>
```

* latex output

```
pandoc -f markdown -t latex -o test.latex test.md
```

```
\section{Test}\label{test}

* This should be read and written only in html output.

\begin{center}* This should be read and written only in latex output.\end{center}

\begin{itemize}
\tightlist
\item
  This should be read and written in both output.
\end{itemize}
```

pandoc version : 1.15.0.6 on windows

**Comment by jgm** [comment]
If you do `pandoc -t native`, you'll understand why it
behaves this way.  Only the `<p>` tags are parsed as raw HTML;
the contents are not.

+++ arsaber101 [Sep 11 15 04:37 ]:

**Comment by arsaber101** [comment]
Thanks for your quick and enlightning answer.

I should have read more carefully the doc (or think twice about it...) :

> but by default, pandoc interprets material between HTML block tags as markdown.

So, for those facing the same issue, actually it is the *feature* that allows markdown formatting inside html block. Disabling the `markdown_in_html_blocks` extension solves it :


```
pandoc -f markdown-markdown_in_html_blocks -t latex -o test.latex test.md

```
