### ISSUE TITLE
Extra parenthesis added in inline citations with multiple authors

### ISSUE THREAD

**Issue by joelostblom** [jgm/pandoc#2391]
When using a csl-style with the author-date format (such as [cell.csl](https://www.zotero.org/styles/cell)), a single in text citation appears as `(Lastname1., year1)`. However, when citing multiple authors, they appear as 
`(Lastname1., year1, Lastname2., (year2), Lastname3., (year3))`
 instead of 
`(Lastname1., year1, Lastname2., year2, Lastname3., year3)`
 as in the Cell journal.

This issue occurs both in html, pdf, latex and docx (didin't test further) output from pandoc, but not when using the same style in Zotero + LibreOffice Writer. Therefore, I thought it was actually related to pandoc rather than any other of the tools involved , but let me know if it is not and I should post this elsewhere.

**Comment by jgm** [comment]
Can you give us the Markdown you're using to produce one of
these multiple author citations?

And preferably a short bibliography file we can use to
reproduce  this?

+++ joelostblom [Sep 11 15 11:17 ]:

**Comment by joelostblom** [comment]
Sure, you can find a minimal example [here](https://github.com/joelostblom/issues/tree/master/pandoc_citation_parenthesis). The command I used to convert to pdf is `pandoc -s -o out.pdf --filter pandoc-citeproc pandoc_citation_parenthesis.md`

**Comment by jgm** [comment]
The citations should be separated using semicolons, not
commas.
http://pandoc.org/README.html#citations

See if that helps things.

+++ joelostblom [Sep 11 15 12:18 ]:

**Comment by joelostblom** [comment]
Well, now I feel stupid. I didn't notice the mention of semicolon when I was reading through the readme and other styles I used with seemed to work fine, so it never occurred to me that the syntax might be incorrect. It works as expected now, sorry about that.
