### ISSUE TITLE
Using \cite instead of \autocite?

### ISSUE THREAD

**Issue by colegleason** [jgm/pandoc#2392]
I am doing Markdown -> LaTeX with Pandoc and would really like to use it with BibTeX (not BibLaTeX). I have a .bst style file I want to use, but I have no support for Biblatex. Is that possible?

**Comment by jgm** [comment]
Try using the `--natbib` option.

+++ Cole Gleason [Sep 11 15 12:29 ]:

**Comment by colegleason** [comment]
That seems to work, although I had to redefine \citep as \cite.

**Comment by jgm** [comment]
Yeah, we support natbib or biblatex, but not plain bibtex.  But your workaround is fine.
