### ISSUE TITLE
Multiple heading ids

### ISSUE THREAD

**Issue by van-de-bugger** [jgm/pandoc#2396]
[`pandoc`](http://pandoc.org/README.html#header-identifiers-in-html-latex-and-context) documentation says:

> A header without an explicitly specified identifier will be automatically assigned a unique identifier based on the header text.

However, `pandoc` assigns an identifier even if identifier is already set, causing incorrect HTML output:

    $ ~/.cabal/bin/pandoc --version
    pandoc 1.15.0.6
    Compiled with texmath 0.8.3, highlighting-kate 0.6.
    ...

    $ cat input.md 
    # Chapter 1 {id="ch01"}

    text

    $ ~/.cabal/bin/pandoc -f markdown -t html -o output.html input.md 

    $ cat output.html 
    <h1 id="chapter-1" id="ch01">Chapter 1</h1>
    <p>text</p>

Note: `h1` tag has *two* `id` attributes.

**Comment by jgm** [comment]
The standard way to set an id in pandoc is

    # Chapter 1 {#ch01}

If you do it this way, it will work the way the docs say.
But probably we should ensure that if someone says id=foo, it
has the same effect.

**Comment by ousia** [comment]
@van-de-bugger,

from this source:

``` markdown
# Chapter 1 {#ch1}
# Chapter 2 {id="ch2"}
```

you will have this HTML output (using [latest stable pandoc](http://pandoc.org/try/?text=%23+Chapter+1+{%23ch1}%0A%23+Chapter+2+{id%3D%22ch2%22}&from=markdown&to=html)): 

``` html
<h1 id="ch1">Chapter 1</h1>
<h1 id="chapter-2" id="ch2">Chapter 2</h1>
```

Extended Markdown requires identifiers tagged as `{#identifier}` and classes as `{.class}`.

Just in case it might help.

**Comment by van-de-bugger** [comment]
Thanks, I am aware about `{#id}` syntax, but I think `{id="id"}` is also valid.
