### ISSUE TITLE
mmd_header_identifiers work improperly

### ISSUE THREAD

**Issue by van-de-bugger** [jgm/pandoc#2397]
`mmd_header_identifiers` extension works improperly. Consider `multimarkdown` behavior first:

```
$ cat input.md 
# Chapter 1: A long name of chapter [Chapter 1]

See [Chapter 1].

$ multimarkdown input.md > output.html 

$ cat output.html 
<h1 id="chapter1">Chapter 1: A long name of chapter</h1>

<p>See <a href="#chapter1">Chapter 1</a>.</p>
```

Note: `multimarkdown` treats bracketed text at the end of heading as a source to compute identifier — `[Chapter 1]` produces (valid) identifier `chapter1`.

Now let us process the same `input.md` with `pandoc`:

```
$ ~/.cabal/bin/pandoc -f markdown+mmd_header_identifiers -o output.html input.md 

$ cat output.html 
<h1 id="Chapter 1">Chapter 1: A long name of chapter</h1>
<p>See [Chapter 1].</p>
```

`pandoc` treats text in brackets as _identifier_ and so produces invalid HTML code — `id` attribute must not contain any space characters. (Frankly, it is not a big deal, because most of browsers tolerate it.)

`pandoc` also fails to recognize `[Chapter 1]` in text as a _link_ to the section. This is a serious usability issue.

`pandoc` v1.15.0.6, `multimarkdown` v4.5.3.

**Comment by jgm** [comment]
Yes, it seems that we should do the following:

- Create an identifier on the header, based on "Chapter 1" (presumably `chapter-1`, with a suffix if not unique)
- Create a reference link, as if `[Chapter 1]: #chapter-1` had been in the document.
