### ISSUE TITLE
Converting from Markdown to Plain Text loses any link URLs

### ISSUE THREAD

**Issue by wadtech** [jgm/pandoc#2399]
e.g.

```markdown
[Here is a link](https://github.com/jgm/pandoc/)
```

becomes

```
Here is a link
```

It's probably not in the right spirit to change the layout of a document but it would be handy to have the option to inline those URLS

e.g.

```
Here is a link https://github.com/jgm/pandoc/
```

**Comment by jgm** [comment]
The `plain` output format is supposed to look like plain text, the kind you'd get in Project Gutenberg for example.  Adding the URLs is against the spirit of that.

If you want, you can write a filter that inserts a `Str` node with the URL after a link, and use it with `plain` output.  But I don't want to modify the plain format, and I'd like to avoid undue proliferation of command-line options.

**Comment by wadtech** [comment]
I thought that might be the case, thanks for the explanation.
