### ISSUE TITLE
org verse paragraphs with blank lines are not parsed properly

### ISSUE THREAD

**Issue by ag91** [jgm/pandoc#2402]
Thank you for Pandoc!

I am using 1.15.0.6 to translate a file from org to pdf.
A simplified of my file is:
<pre><code>
* section
** subsection

#+BEGIN_VERSE
bla

bla
#+END_VERSE
</code></pre>

This file is  translated in the pdf text:

<pre><code> 
Contents
section
1
subsection . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
section
subsection
#+BEGIN VERSE bla
bla
#+END VERSE
</code></pre>
In order to not having the superfluous <code>#+BEGIN VERSE ...</code> bit, I need to close the verse paragraph before the blank line and open another one later:

<pre><code>
* section
** subsection

#+BEGIN_VERSE
bla
#+END_VERSE

#+BEGIN_VERSE
bla
#+END_VERSE
</code></pre>

Since, the QUOTE paragraph works with blank spaces properly, I was wondering if this can be fixed easily.
Thanks!

**Comment by jgm** [comment]
@tarleb - issue is that VERSE environments in the org reader don't seem to allow blank lines.
Easy to fix?

**Comment by tarleb** [comment]
Just looking at the code, it seems like blank lines were allowed already. I'm investigating.
