### ISSUE TITLE
Creating epub from epub's constituent (not md, not tex or text but mainly html) files possible?

### ISSUE THREAD

**Issue by omero72** [jgm/pandoc#2404]
Hello

That's not actually an issue but I'd like to know if it's possible with pandoc to create an epub from OEBPS directory, that is from constituent epub files (I mean the files you get when you have unzipped the epub file: Images/ Text/ toc.ncx Styles/ content.opf and META-INF/ cover.jpg and mimetype) I ask this because sometimes I have to alter the content of some epubs and to do that I have to unzip the epub to its constituent files and then I have to remake it into epub. So far I have used Pandoc basicly to convert from .md files into epub and that was perfect. But I wonder if can make it from epub's constituent files?

**Comment by jgm** [comment]
Hi!  Questions should go to the pandoc-discuss mailing list (on Google Groups) rather than here; this is a bug tracker for specific issues.

Short answer:  there's no automatic support for creating an epub from a directory of constituents with pandoc.
