### ISSUE TITLE
behead.hs example compile error

### ISSUE THREAD

**Issue by technocrat** [jgm/pandoc#2407]
I am trying to compile the version of behead.hs from http://pandoc.org/scripting.html in the following environment without success. 

On OSx 10.10.5 (Yosemite), The Glorious Glasgow Haskell Compilation System, version 7.10.2 and 

pandoc-1.15.0.6
pandoc-citeproc-0.7.4
pandoc-csv2table-1.0.2
pandoc-types-1.12.4.6

	-- behead.hs
	import Text.Pandoc
	import Text.Pandoc.Walk (walk)

	behead :: Block -> Block
	behead (Header n _ xs) | n >= 2 = Para [Emph xs]
	behead x = x

	readDoc :: String -> Pandoc
	readDoc = readMarkdown def
	-- or, for pandoc 1.14, use:
	-- readDoc = case readMarkdown def of
	--                Right doc -> doc
	--                Left err  -> error (show err)

	writeDoc :: Pandoc -> String
	writeDoc = writeMarkdown def

	main :: IO ()
	main = interact (writeDoc . walk behead . readDoc)

with 

	$ ghc --make behead
	
which gives

	ghc --make behead
	[1 of 1] Compiling Main             ( behead.hs, behead.o )

	behead.hs:10:11:
		Couldn't match type ‘Either Text.Pandoc.Error.PandocError Pandoc’
					   with ‘Pandoc’
		Expected type: String -> Pandoc
		  Actual type: String
					   -> Either Text.Pandoc.Error.PandocError Pandoc
		In the expression: readMarkdown def
		In an equation for ‘readDoc’: readDoc = readMarkdown def

Out of an abundance of caution, I made sure to convert the source file

	perl -i -pne "s/\r/\n\n/g" behead.hs

with no different result.

As far as I can tell 

	readMarkdown :: ReaderOptions -- ^ Reader options
				 -> String        -- ^ String to parse (assuming @'\n'@ line endings)
				 -> Either PandocError Pandoc
				 
My Haskell fluency is too weak to figure out what to change in the example to get around this.

**Comment by jgm** [comment]
Note the following comment in the code on the tutorial:

-- or, for pandoc 1.14, use:
-- readDoc = case readMarkdown def of
--                Right doc -> doc
--                Left err  -> error (show err)

The same applies for 1.15.


+++ Richard Careaga [Sep 20 15 22:34 ]:

**Comment by technocrat** [comment]
Thanks. I misread that as 1.14 or *earlier* (it's hard to make things foolproof because fools are so ingenious). However, with the change

	-- readDoc :: String -> Pandoc
	-- readDoc = readMarkdown def
	-- or, for pandoc 1.14, use:
	readDoc = case readMarkdown def of
					Right doc -> doc
					Left err  -> error (show err)

I still get an error

	behead.hs:14:17:
		Couldn't match expected type ‘String
									  -> Either Text.Pandoc.Error.PandocError Pandoc’
					with actual type ‘Either t0 t’
		Relevant bindings include readDoc :: t (bound at behead.hs:13:1)
		In the pattern: Right doc
		In a case alternative: Right doc -> doc
		In the expression:
		  case readMarkdown def of {
			Right doc -> doc
			Left err -> error (show err) }

	behead.hs:15:17:
		Couldn't match expected type ‘String
									  -> Either Text.Pandoc.Error.PandocError Pandoc’
					with actual type ‘Either a0 t1’
		In the pattern: Left err
		In a case alternative: Left err -> error (show err)
		In the expression:
		  case readMarkdown def of {
			Right doc -> doc
			Left err -> error (show err) }  

which suggests that readMarkdown is still not happy.

**Comment by jgm** [comment]
+++ Richard Careaga [Sep 20 15 22:46 ]:
>   Thanks. I misread that as 1.14 or earlier (it's hard to make things
>   foolproof because fools are so ingenious). However, with the change
>-- readDoc :: String -> Pandoc
>-- readDoc = readMarkdown def
>-- or, for pandoc 1.14, use:
>readDoc = case readMarkdown def of
>                Right doc -> doc
>                Left err  -> error (show err)

Oh yes, sorry, this should be:

readDoc s = case readMarkdown def s of
                 Right doc -> doc
                 Left err  -> error (show err)

I'll revise the site.

**Comment by technocrat** [comment]
An s, an s, my source code for an s! Never would I have tripped to that. 
Takes a philosopher. Thanks, I'm compiled and on my way to RMarkdown 
goodness!

John MacFarlane wrote:
