### ISSUE TITLE
Conditional breaks are lost when converting from docx

### ISSUE THREAD

**Issue by swege** [jgm/pandoc#2415]
If I have a docx document which contains conditional breaks (press `Ctrl + -` in MS Word 2013), those are lost when converting to markdown or to HTML.

`pandoc -f docx -t html -o out.html input.docx`

I expected that the output contains `&shy;` entities. Instead, nothing at all was added for the conditional breaks, they are just beeing ignored.

**Comment by mb21** [comment]
Unfortunately, Word doesn't use the unicode character 'SOFT HYPHEN' (U+00AD) but instead creates it's own XML element `<w:softHyphen/>`. The docx reader should be adjusted to fix this.

**Comment by jgm** [comment]
@jkr - this sounds like a pretty easy thing to fix.
