### ISSUE TITLE
CSL problem ... strip-periods 

### ISSUE THREAD

**Issue by kit-lloyd** [jgm/pandoc#2423]
I am having a problem with csl working with pandoc-citeproc; specifically with "Ibid" and "above n" processing.

The command I am using is pandoc -s -S --latex-engine=xelatex --filter pandoc-citeproc -- -o test

.pdf test.md

The csl and bibliography are specified in the md documents YAML

[aglc.csl]([aglc.csl]) is from the Zotero style repository (modified to take out the bibliography and capitalise  ibid)

The problem is that "Ibid" is output in the pdf and latex file as "Ibid.,"  rather than just "Ibid"

For some reason the "strip-periods" does not seem to work and also I do not know how to have the redundant "," removed.

Also I cannot seem to get 'Above n' working

CSL functions well everywhere else and Ibid and Above n work in other applications.

Any suggestions would be greatly appreciated.

This is the Ibid code:

      <citation et-al-min="4" et-al-use-first="1">
          <layout suffix="." delimiter="; ">
            <choose>
              <if position="ibid-with-locator">
                <text term="ibid" strip-periods="true"
      text-case="capitalize-first"/>
                <group delimiter=" ">
                  <text variable="locator" strip-periods="true"/>
                </group>
              </if>
              <else-if position="ibid">
                <text term="ibid" strip-periods="true"
      text-case="capitalize-first"/>
              </else-if>
              <else-if position="subsequent">

as for above n ... it does not get inserted (the rest of the processing work fine, such as stripping the authors name) ... but above n and the locator are omitted. 

Here is the above n code ...

      <else-if position="subsequent">
                <choose>
                  <if type="legal_case bill legislation manuscript"
      match="any">
                    
                    <group delimiter=" ">
                      <group delimiter=", ">
                        <text macro="author-note"/>
                        <choose>
                          <if match="any" variable="title-short">
                            <text macro="title-short"/>
                          </if>
                          <else>
                            <text macro="title"/>
                          </else>
                        </choose>
                      </group>
                      
                      <group delimiter=" ">
                        <text macro="date-parenthesis"/>
                        <text macro="article-case-info"/>
                        <text macro="book-container"/>
                        <text macro="publisher"/>
                      </group>
                    </group>
                    <text macro="manuscript-catchall" prefix=", "/>
                    <text macro="date-news" prefix=", "/>
                    <group delimiter=", " prefix=" ">
                      <text macro="looseleaf"/>
                      <text macro="page-first"/>
                      <text variable="locator"/>
                    </group>
                  </if>
                  <else>
                    <group delimiter=", ">
                      <text macro="author-short"/>
                      <choose>
                        <if disambiguate="true">
                          <text macro="title-short"/>
                        </if>
                      </choose>
                      <text variable="first-reference-note-number"
      prefix="above n "/>
                      <text variable="locator"/>
                    </group>
                  </else>
                </choose>
              

</else-if>

**Comment by jgm** [comment]
You should submit this bug report to jgm/pandoc-citeproc.

**Comment by jgm** [comment]
Closing in favor of jgm/pandoc-citeproc#185
