### ISSUE TITLE
beamer " . . ." pauses appear verbatim in handbook pdf documents

### ISSUE THREAD

**Issue by bozito** [jgm/pandoc#2428]
When I generate both a beamer pdf slideshow and the corresponding pdf handbook from the same markdown file, the beamer pause ". . ." appear in the handbook.

Here is what I do to generate both slides and handbook:

pandoc --slide-level 2 -i -t beamer -s lecture2.md -o lecture2.pdf & pandoc -s lecture2.md -o lecture2_handbook.pdf

The lecture2_handbook.pdf is littered with '. . .'.
I think that by default, these pauses should not appear.
Could this be fixed in the default latex template?

**Comment by jgm** [comment]
It's not a template issue.  The beamer writer gives special
treatment to a paragraph containing just ". . .", converting
it to a pause.  The latex writer does not.

You could write a pandoc filter that removes

    Para [Str ". . ."]

and use it when generating your handout.

+++ bozito [Oct 02 15 08:03 ]:
