### ISSUE TITLE
LaTeX Writer: Generating headings for unnumbered sections

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2429]
Pandoc 1.15.0.6 writes an unnumbered section as follows; this does not set the title to appear in a running head:

```tex
\section*{Section Name}\label{section-name}
\addcontentsline{toc}{section}{Section Name}
```

Unless I am missing something, the following also needs to be added to achieve this, and I wonder whether this should be made the standard behaviour of the LaTeX writer:

```tex
\markboth{Section Name}{Section Name}
```

(One would think that it would be possible to set all this in the template rather than repeating the name of five times, but I haven't found a way to do it thus far without using KOMA-Script.)

**Comment by jgm** [comment]
I'm just a bit hesitant to add the `\markboth` -- what if you've set things up so that section titles are, say, just on the left hand page?  Or would that matter?

**Comment by adunning** [comment]
This only controls the contents of the heads, and not the status of their display. Still, my tendency right now is to leave it out and keep things simple.

**Comment by sjackman** [comment]
There are three independent states for chapters/sections.

1. Numbered?
2. Listed?
3. Running head? (neither, left, right, both)

I use this Markdown:

```markdown
---
numbersections: true
secnumdepth: 0
---

# References {-}
\markboth{\hfill References \hfill}{\hfill References \hfill}
```

to generate this LaTeX.

```latex
\chapter*{References}
\addcontentsline{toc}{chapter}{References}
\markboth{\hfill References \hfill}{\hfill References \hfill}
```

Related issues:
https://github.com/jgm/pandoc/issues/2429
https://github.com/jgm/pandoc/issues/2920 https://github.com/jgm/pandoc/commit/0f9c6c4db0d1c352e2c64d8237252923820be9f4
https://github.com/jgm/pandoc/issues/3474

There's nothing really to do here. I just wanted to post everything that I learned today in one place.
