### ISSUE TITLE
LaTeX reader support for theorems

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#243]
<pre>
If a LaTeX document contains commands like
~~~
\newtheorem{theorem}{Theorem}
\newtheorem{lem}[theorem]{Lemma}
\newtheorem{definition}{Definition}
\newtheorem{example}{Example}
~~~
then it would be nice if Pandoc understood them, turning something like
~~~
\begin{lem}The product of any $4$ consecutive numbers is divisible by
$24$.\end{lem}
~~~
into
~~~
&gt; **Lemma.** The product of any $4$ consecutive numbers
&gt; is divisible by $24$.
~~~

[The optional argument in \newtheorem{lem}[theorem]{Lemma} stands for
"number with the same counter as" and can be ignored as Pandoc doesn't
produce numbering. Also note that a "theorem" environment is not defined by
default, so it is not a good idea to special-case
\begin{theorem}...\end{theorem} environments without reading \newtheorem
commands.] 

Google Code Info:
Issue #: 104
Author: shreevat...@gmail.com
Created On: 2008-11-08T01:10:34.000Z
Closed On: 
</pre>

**Comment by tarleb** [comment]
LaTeX reader support for amsthm was added in pandoc 2.10.1:

> Support amsthm:  `\newtheorem`, `\theoremstyle`, and theorem and proof environments, including labels and references.  The only thing that is unsupported is the second optional argument, which causes numbering to be reset after the specified series is incremented.

I believe this can therefore be closed.
