### ISSUE TITLE
Readme misses .md ending

### ISSUE THREAD

**Issue by daixtrose** [jgm/pandoc#2431]
The Readme file in the top level looks like markdown, but since it misses the expected file extension ".md" it is not rendered.

**Comment by tarleb** [comment]
Quoting jgm:

> We intentionally don't use a .md extension, because github doesn't know how to render all of the pandoc Markdown extensions used in this README (e.g. definition lists). The same README is used to generate the website and man page, so we really need these extensions.

See also #688, #2239, and #2361.
