### ISSUE TITLE
Conversion to pdf fails with "Package graphics Error: Division by 0." message

### ISSUE THREAD

**Issue by qwer1304** [jgm/pandoc#2433]
Hi,

The following command (latest versions):
pandoc.exe -f html  --latex-engine=xelatex.exe --verbose -f html  -o mll.pdf ml.html > mll.log
On html file http://www.iro.umontreal.ca/~bengioy/dlbook/ml.html pandoc 

failed with:
! Package graphics Error: Division by 0.

Tried to attach the log file as txt, log, docx and pdf, but the system wouldn't let me.

Thanx for your help.

**Comment by adunning** [comment]
That works for me, amazingly, though the conversion is not perfect (as can only be expected; that HTML is absolutely awful, itself having been generated from a PDF). Check that you're using the most recent Pandoc (1.15.1.1) and TeX Live 2015.

**Comment by qwer1304** [comment]
Thx.
I managed to convert to pdf w/o errors with the setup you've described.
Unfortunately, the pdf is not very good.

PS I managed to get a very good result with wkhtmltopdf and small hack of the source. See [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2540).

**Comment by adunning** [comment]
Glad you managed something. If this particular problem is solved, would you mind closing the issue?
