### ISSUE TITLE
Incorrect Parsing of LateX file, expecting end of line too early

### ISSUE THREAD

**Issue by sbaker7** [jgm/pandoc#2436]
I'm trying to convert a large latex file into an ePub. I have also attempted to convert to html and the same issue occurs. I can, however, convert (compile?) my tex file into pdf.

The error according to terminal is: 
```Error at "input" (line 110, column 10):
unexpected '}'
expecting letter, lf new-line, "%", "\\", "{", "-", "``", "\8220", "\"`", "\"", "`", "\8216", "''", "\8221", "'", "\8217", "~", "$$", "$", "^^", "&", white space or end of input```

The issue is occurring halfway through a paragraph, where it is definitely pointing at a letter or a white space. I'm not sure if this is an issue because my master file links to import a number of large, separate files or something else. I've seen others with similar issues in the past (the issues now closed) but I haven't been able to fix it thus far.

**Comment by jgm** [comment]
The best way to track this down is divide and conquer.
The line numbers in error messages can get screwed
up by included files.

Try commenting out the lines that include external packages
or import other files, and see if that fixes things.
Then try restoring them one by one.  If you determine
which part is causing the error, try running pandoc
just on that file.  You may get a more useful error
message then.

+++ sbaker7 [Oct 05 15 21:03 ]:

**Comment by sbaker7** [comment]
Thanks, found it. The issue was the same as another already documented issue, the issue with multiple braces not being understood. eg. {{Do the thing}}

**Comment by jgm** [comment]
OK, if there's already an issue for this, I'll close this one.
