### ISSUE TITLE
References in beamer can split over frames, suggest minipage

### ISSUE THREAD

**Issue by blindmelon** [jgm/pandoc#2442]
Currently, when using {.allowframebreaks}, references in beamer can split over frames (e.g. a slide might end with http:// and the next one start with the rest of the URL - not great).

The only way I've found so far that prevents this (although LaTeX gurus might have a better idea) is to wrap the reference with \begin{minipage}{\textwidth} \end{minipage}.

It does cause LaTeX to complain about underfull \hboxes, but it looks alright to me.

**Comment by nickbart1980** [comment]
Try inserting `\widowpenalties 1 10000` before your references. See https://tex.stackexchange.com/questions/21983/how-to-avoid-page-breaks-inside-paragraphs

**Comment by blindmelon** [comment]
@nickbart1980 Oh, that seems to have done the job nicely, and much simpler! I don't know how I missed it, I searched stackexchange for ages to get the minipage idea!

**Comment by jgm** [comment]
Can this issue be closed?

**Comment by blindmelon** [comment]
I do wonder whether the Beamer template should include the command @nickbart1980 suggested, so I won't close myself just yet, but knowing what to type solves the issue for me personally and so I am happy if you want to close.
