### ISSUE TITLE
GHC.generics is a member of hidden package ghc-prim

### ISSUE THREAD

**Issue by lierdakil** [jgm/pandoc#2448]
FYI, 0b91c73456ca4506d50495f58b3b803b389f96e7 (current master) fails to build with the following error:

```
src/Text/Pandoc/Error.hs:37:8:
    Could not find module `GHC.Generics'
    It is a member of the hidden package `ghc-prim'.
    Perhaps you need to add `ghc-prim' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

I think this is introduced by 04307a155407480c2bedd4c6f9c121640ba47b11

**Comment by jgm** [comment]
I see from travis that this only fails for ghc 7.4.  So am
I right to think we only need to add this for older versions
of base?

+++ Nikolay Yakimov [Oct 12 15 11:21 ]:

**Comment by lierdakil** [comment]
Thanks.
