### ISSUE TITLE
Replace error by warning when --bibliography= file is not present.

### ISSUE THREAD

**Issue by serge-stroobandt** [jgm/pandoc#2455]
I use `pandoc` extensively to create a myriad of documents. I always launch `pandoc` indirectly from a template `makefile` with the `--bibliography=filename.bib` option hard-coded in. Now, not every document I create requires citations. Running `pandoc` as stated without the `citations.bib` file present results in the following fatal error messages:

    pandoc-citeproc: user error (Not found: filename.bib)
    pandoc: Error running filter pandoc-citeproc

I circumvent this error by creating an empty `filename.bib` file.
Branching the `makefile` to have two different `pandoc` calls simply adds more complexity to the problem than warranted. Hence my proposal to relax the bibliography presence requirement by replacing the error message with a warning message, whilst continuing execution:

    pandoc-citeproc: user warning (Not found: filename.bib)

I know of more people calling `pandoc` through a `makefile`. Even my 10 year-old son has started to use `pandoc` this way. Implementation of this proposal would make it all less confusing to him, whilst sparing my hard disk from filling up with nearly empty blocks! Thank you in advance for your time and effort!

**Comment by jgm** [comment]
It's not hard to construct a Makefile that tests for
the presence of filename.bib, and adds the
`--bibliography filename.bib` option to the command
line only if this is present.  That's what I'd recommend.
I think that an error is the right response when someone
calls for pandoc-citeproc to be used and the bibliography
is missing.

John

+++ Serge Y. Stroobandt [Oct 16 15 15:52 ]:

**Comment by jgm** [comment]
As an example, here's one approach:

```
ifeq ($(wildcard filename.bib),)
       BIBOPT=
else
       BIBOPT=--bibliography filename.bib
endif

%.html: %.md
	pandoc $(BIBOPT) -s $< -o $@
```

**Comment by serge-stroobandt** [comment]
Thank you for this very useful bit of example code, John!
Perhaps, you should consider adding some information about using `pandoc` with `make` to the documentation page. That would certainly help boost the adoption of `pandoc`.

**Comment by jgm** [comment]
It's a good idea, I'll put it on my list.

+++ Serge Y. Stroobandt [Oct 17 15 09:49 ]:

**Comment by serge-stroobandt** [comment]
Here is what got me started in terms of using `pandoc` with a `makefile`:
<http://lincolnmullen.com/blog/make-and-pandoc/>

This may also serve as a great starting point to write some `make` documentation.
