### ISSUE TITLE
Bug in release 1.15.1: pandoc: Could not find data file templates

### ISSUE THREAD

**Issue by jfmdev** [jgm/pandoc#2459]
There is a bug in **release 1.15.1** which prevents to export to EPUB or to ODT, displaying the following errors:

`pandoc: Could not find data file templates\default.opendocument`

or

`pandoc: Could not find data file templates\default.epub`

I have tested this bug in both Windows 7 & 8.
Note that these errors do not happens when using **release 1.15.0.6**.

**Comment by jgm** [comment]
Yes, the Windows package seems not to have any of the
templates.  I will investigate.

+++ jfmdev [Oct 17 15 09:47 ]:

**Comment by jgm** [comment]
At first I suspected a problem in the build process (leaving
out the `embed_data_files` flag).  But `embed_data_files` is
definitely being used.  And some data files are found,
e.g. `pandoc --print-default-data-file custom.lua`.

Note that `pandoc --print-default-data-file
dzslides/template.html` also fails.

+++ jfmdev [Oct 17 15 09:47 ]:
