### ISSUE TITLE
Pandoc ignores `plain` frame attribute in Beamer

### ISSUE THREAD

**Issue by N4M3Z** [jgm/pandoc#2462]
Following Pandoc documentation here: http://pandoc.org/README.html#frame-attributes-in-beamer, it states that frame options can be passed to Beamer using:
```
# Fragile slide {.fragile}
```
this however does not work with option `plain` which is silently ignored. 

The documentation states that all of the following options should work: `allowdisplaybreaks`, `allowframebreaks`, `b`, `c`, `t`, `environment`, `label`, `plain`, `shrink`.

**Comment by jgm** [comment]
What version of pandoc are you using?  The feature you
quote documentation before was added only in 1.15.1,
released a few days ago.

+++ Martin Zeman [Oct 18 15 19:31 ]:

**Comment by N4M3Z** [comment]
I see! That explains it. Need to get the guys from Homebrew to update pandoc to the latest version. Thanks for the clarification.
