### ISSUE TITLE
Less than character in heading of a input Markdown file with some html mixed in not detecting end of heading

### ISSUE THREAD

**Issue by samogami** [jgm/pandoc#2469]
Less than (<) character in heading of a input Markdown file with some html mixed in html not dectecting end of heading correctly.

Example input (in markdown):
```
# Door width for wheelchair access should be greater than 32 inches  (<813mm)

It is known that most modern wheelchairs are 24 inches to 27 inches wide from one wheel to the other wheel.

<script type="text/javascript" src="utils.js"></script>
```

Pandoc converts the entire text and appends an `h1` at end of document

[See pandoc.org/try webpage page for example of problem.](http://pandoc.org/try/?text=http://pandoc.org/try/?text=%23+door+width+for+wheelchair+access+should+be+greater+than+32+inches++(%3C813mm)%0A%0AIt+is+known+that+most+modern+wheelchairs+are+24+inches+to+27+inches+wide+from+one+wheel+to+the+other+wheel.%0A%0A%3Cscript+type%3D%22text%2Fjavascript%22+src%3D%22utils.js%22%3E%3C%2Fscript%3E&from=markdown_github&to=html5)

Other markdown converters work correctly as in github (see example below):

# Door width for wheelchair access should be greater than 32 inches  (<813mm)
It is known that most modern wheelchairs are 24 inches to 27 inches wide from one wheel to the other wheel. To enable wheelchairs to move freely through doors, the door width for wheelchair access should be not less than 32 inches / 813mm.
<script type="text/javascript" src="utils.js"></script>

**Comment by jgm** [comment]
What version of pandoc are you using?  I get

```
<h1 id="door-width-for-wheelchair-access-should-be-greater-than-32-inches-813mm">Door width for wheelchair access should be greater than 32 inches (&lt;813mm)</h1>
<p>It is known that most modern wheelchairs are 24 inches to 27 inches wide from one wheel to the other wheel.</p>
<script type="text/javascript" src="utils.js"></script>
```

+++ Sam Ogami [Oct 21 15 11:58 ]:

**Comment by samogami** [comment]
I am using:
Windows 7
Pandoc 1.15.1.1

**Comment by jgm** [comment]
Ah, I see.  The problem only arises if you do `-f markdown_github`
or `-f markdown_strict`.  It does not arise with `-f
markdown` (pandoc markdown).  Not sure why this would be,
but it should help to diagnose the problem.

**Comment by jgm** [comment]
More minimal case:
```
# <a

<hr/>
```
With `-f markdown_github`, this yields
```
<h1 id="section"><a

<hr/></h1>
```

**Comment by samogami** [comment]
When will the next build of the windows installer be created with this fix?

**Comment by jgm** [comment]
Next release.  I don't know when.  For now you can just
backslash-escape the offending backslash.

+++ Sam Ogami [Oct 23 15 10:49 ]:
