### ISSUE TITLE
Markdown to Epub doesn't pass http://validator.idpf.org/

### ISSUE THREAD

**Issue by BruceEckel** [jgm/pandoc#2470]
I am starting with padoc-flavored markdown and generating epub. The result works within numerous epub readers including iBooks.

However, when I tried uploading it to Google Play Books, I got a message that says "This file cannot be processed," and it pointed me to the EPUB validator http://validator.idpf.org/, which did indeed show a list of problems. When I looked at these, it does appear that incorrect code is being generated (although, interestingly, different errors depending on whether I generate epub or epub3).

Not sure how to get all the necessary info to you; the book and the build system is in a private Bitbucket repo which I can give you access to.

**Comment by jgm** [comment]
You can email me privately with a link to the repository.

+++ Bruce Eckel [Oct 21 15 12:03 ]:

**Comment by BruceEckel** [comment]
Hmm. Not seeing your email address anywhere...


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by jgm** [comment]
https://hackage.haskell.org/package/pandoc

+++ Bruce Eckel [Oct 21 15 12:44 ]:

**Comment by jgm** [comment]
Thanks, I got access. By the way, what version of pandoc are you using to create the epub?
If you're using an older version, please try again with the most recent one.

**Comment by jgm** [comment]
Some of the errors come from problems in raw HTML that you have included:
```
<img width="200px" src="media/file2.png" />
```
This causes:
```
ERROR(RSC-005): OnJava.epub/ch004.xhtml(125,47): Error while parsing file 'value of attribute "width" is invalid; must be an integer'.
```
See http://stackoverflow.com/questions/6784868/html5-can-i-use-width-and-height-in-img (esp. the first answer).  As epubcheck says, you can't have `px` here.  If you want to specify units, you need to use a `style` attribute.

Pandoc just passes through raw HTML, so if you use invalid HTML5, the resulting EPUB will be invalid.  But that is not pandoc's fault.

```
FATAL(RSC-016): OnJava.epub/ch025.xhtml(2026,3): Fatal Error while parsing file 'The element type "html" must be terminated by the matching end-tag "</html>".'.
```
This error comes from a problem in your markdown file `24_UserInterfaces.md`.  You have `<html>` without backticks around it, so it gets passed through as raw HTML, which is of course invalid in this context.

I don't have time to go through all of these, but it looks to me as if many of the issues come from problems in your source.  I am not sure, though, why you're getting the "fragment identifier is not defined" errors -- in the cases I check, the identifier is defined.  Why don't you hunt down the issues in your source and we'll see if anything remains that might be attributable to pandoc.

**Comment by BruceEckel** [comment]
Will do -- thanks. I did a lot of automated conversion from Word and I see
that I still have some cleaning to do.

I'm using Pandoc 1.14.0.1, so I'll upgrade.


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by BruceEckel** [comment]
After removing all of the artifacts, I was able to get the generated epub to pass all the validator checks. Thanks for the help, and for pandoc!

**Comment by jgm** [comment]
Excellent news!

+++ Bruce Eckel [Oct 23 15 13:04 ]:
