### ISSUE TITLE
pandoc should not download and include an external audio file in the EPUB output

### ISSUE THREAD

**Issue by fedelibre** [jgm/pandoc#2473]
As emerged in [this discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/pandoc-discuss/IcXo_3E7kaY), pandoc downloads and includes an audio file in the EPUB output file.

HTML output does not include external resources by default and you can include them with the option `--self-contained`. IMO epub output should work the same way.

Test file:

```md
# Test

Testing the audio element from an external link:

<audio controls>
 <source src="http://www.sixbarsjail.it/tmp/bach_toccata.mp3" type="audio/mpeg">
</audio>
```

$ pandoc --version
pandoc 1.15.1.1

Command: `pandoc -o output.epub inpub.md`

**Comment by jgm** [comment]
This should probably be discussed on pandoc-discuss.  Why
don't you post there?

+++ Federico Bruni [Oct 23 15 09:19 ]:

**Comment by jgm** [comment]
Oh, sorry -- just saw your post on pandoc-discuss.
Will delete this last comment.

**Comment by jgm** [comment]
Suggestion from pandoc-discuss:

>  In principle we could change this behavior, but a change in
>  the default here might break existing workflows.  One
>  possibility would be to make this behavior sensitive to some
>  kind of flag.  For example, if the `data-external` attribute
>  is set on `<source>` element, don't include in the EPUB.

**Comment by fedelibre** [comment]
Another thought: would it be possible to parse the link and check if it's a local path or an http:// link?
That way, it would work also when CommonMark will add the [syntax to embed audio and video](http://talk.commonmark.org/t/embedded-audio-and-video/441).

**Comment by jgm** [comment]
+++ Federico Bruni [Oct 24 15 01:31 ]:
>   Another thought: would it be possible to parse the link and check if
>   it's a local path or an http:// link?

Many people will want external resources to be embeded, so
that the epub is self-contained.  Since that is the current
behavior, I'd rather have an explicit flag for this.

>   That way, it would work also when CommonMark will add the [1]syntax to
>   embed audio and video.

You've linked to a forum post where people are making
suggestions.  It's not clear that CommonMark will have any
specific syntax for this, or what it will be.
