### ISSUE TITLE
Markdown to Epub: tables can't be separated with '\'

### ISSUE THREAD

**Issue by BruceEckel** [jgm/pandoc#2474]
Alas, I can't attach markdown, epub or zip files to this report, so I'll email them separately.

The commands to build the examples are:
`pandoc Test1.md -t epub3 -o Test1.epub --epub-stylesheet=onjava.css`
and
`pandoc Test2.md -t epub3 -o Test2.epub --epub-stylesheet=onjava.css`

The first one produces:
![image](https://cloud.githubusercontent.com/assets/1001900/10707053/47718a5a-79a2-11e5-93af-f80414ddcb36.png)

With the two tables jammed together. So I did the usual, put a '\' on a line by itself to force a blank line.

The second one, with the separating '\', produces:
![image](https://cloud.githubusercontent.com/assets/1001900/10707040/20077646-79a2-11e5-9c76-c9b1420b3dc7.png)

**Comment by jgm** [comment]
Formatting in epubs (e.g. space around tables) is controlled
by CSS.  Try tweaking your epub css.  (See --epub-css.)

The reason \ doesn't work is that this is syntax for a
newline.  The next line, then, is considered part of
the paragraph, and so you don't have a blank line between
paragraphs.

You could use something else instead, e.g. `&nbsp;`.
But I'd recommend just using CSS to control your formatting.

No bug here that I can see.

+++ Bruce Eckel [Oct 23 15 16:23 ]:

**Comment by BruceEckel** [comment]
The `&nbsp;` trick did work, FYI.

**Comment by nkalvi** [comment]
@BruceEckel Though the issue is resolved, could you please post the source markdown or an example if possible (before and after using `&nbsp;`) if possible? It'd be help me understand the issue and the solution.
