### ISSUE TITLE
Pandoc generating incorrect opening quotes for ongoing British English prose monologue

### ISSUE THREAD

**Issue by evilsoup** [jgm/pandoc#2476]
This is on Pandoc 1.15.1.1.

In prose fiction, when long monologues need to be broken up into multiple paragraphs, the closing quotation mark is omitted from all but the last paragraph of speech, like so:

    'The quick, brown fox jumps over the lazy dog.

    'Blah blee bloo blah blah.

    'Foo bar baz.'

This doesn't cause any problems if you've using double-quotes for your dialogue. But if you run `pandoc -S` over British English speech like the above, you get something like this:

    <p>’The quick, brown fox jumps over the lazy dog.</p>
    <p>’Blah blee bloo blah blah.</p>
    <p>‘Foo bar baz.’</p>

That is, at the beginning of the first two lines I'm getting a closing quote (`’`), when I should be getting an opening quote (`‘`).

**Comment by jgm** [comment]
The only real cure for this, I'm afraid, is to use literal
curly quotes in your text.

With double quotes, pandoc can use a heuristic that an
unmatched double quote is an open (left) curly quote.

But with single quotes, that won't work -- most often,
what you want is a right curly quote.  E.g. 'tis the season
to be jolly.

So I don't see a bug here.

+++ evilsoup [Oct 24 15 19:12 ]:
