### ISSUE TITLE
latex string `${\rm a+b}$` not properly translated

### ISSUE THREAD

**Issue by nschloe** [jgm/pandoc#2479]
With the file
```latex
{\rm a+b}
$a+b$
${\rm a+b}$
```
the pandoc output is
```
$ cat test.tex | pandoc -f latex -t plain
a+b a + b ${\rm a+b}$
```
The first two lines are nicely translated, the third is not.

**Comment by mpickering** [comment]
I think this is because `\rm` is not understood by texmath.

**Comment by jgm** [comment]
>   I think this is because \rm is not understood by texmath.

Correct.  We only understand the fully delimited LaTeX-style font
commands, like `\mathrm{foo}`, not the TeX-style on-switches.
It's a lot harder to parse the latter properly.
