### ISSUE TITLE
Can't get rid of "smart mode"

### ISSUE THREAD

**Issue by borekb** [jgm/pandoc#2480]
I am converting Textile to Markdown and cannot get rid of the "smart" mode (at this point, I'd more likely call it a "stupid" mode :)

From the [docs](http://pandoc.org/README.html) (emphasis mine):

> (Note: This option is significant only when the input format is markdown, markdown_strict, textile or twiki. **It is selected automatically when the input format is textile** or the output format is latex or context, unless --no-tex-ligatures is used.)

This might be the issue - the "smart" mode is turned on automatically for Textile but there is no way to suppress it.

**Comment by borekb** [comment]
BTW, according to the docs (if you read them exactly), `--no-tex-ligatures` should suppress the smart mode even for Textile, but that quite obviously doesn't work.

**Comment by jgm** [comment]
The reason smart mode is automatic for textile input is
simply that this treatment of quotes seems to be part of
standard textile:  see e.g.
http://redcloth.org/hobix.com/textile/

If I'm wrong about this, please link to appropriate docs.

There's no point in making pandoc interpret textile
differently from standard textile processors, is there?

+++ Borek Bernard [Oct 25 15 07:30 ]:

**Comment by borekb** [comment]
That's probably because Textile was created to render to HTML where typography makes a lot of sense. (The docs explicitly state that the output is HTML.) When converting to another textile-like markup, I am not sure typography should be applied, at least I feel it shouldn't be forced.

**Comment by jgm** [comment]
+++ Borek Bernard [Oct 25 15 16:57 ]:
>   That's probably because Textile was created to render to HTML where
>   typography makes a lot of sense. (The docs explicitly state that the
>   output is HTML.) When converting to another textile-like markup, I am
>   not sure typography should be applied, at least I feel it shouldn't be
>   forced.

That's a good point.  You wouldn't normally want it
converting to Markdown, for example.  Perhaps we should
discuss this on pandoc-discuss.

**Comment by borekb** [comment]
Created a topic here: https://groups.google.com/forum/#!topic/pandoc-discuss/dYh9FZw3BmY
