### ISSUE TITLE
Template on different path cannot find its local files

### ISSUE THREAD

**Issue by jimmycallin** [jgm/pandoc#2482]
To structure things up a bit I have all template files in a separate folder called "templates". In the templates folder there is a custom made latex template referencing an external sty file. Unfortunately, this setup doesn't allow the template to find the local sty file, since it isn't in placed in the same folder as I am running my script. [Here is a minimal example](https://www.dropbox.com/s/gwjrctlbg0amvht/example.zip?dl=0).

**Comment by jgm** [comment]
The location of the template is irrelevant.

Pandoc will look in the working directory (from which you
run pandoc) for any included sty files, and in the
directories specified in the TEXINPUTS environment variable.
Your solution is to set TEXINPUTS, probably.

+++ Jimmy Callin [Oct 25 15 12:45 ]:

**Comment by jimmycallin** [comment]
Ah, that helped indeed -- thanks!
