### ISSUE TITLE
internal error building documentation

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#2483]
Building documentation fails with this error:

   >>?haddock: internal error: <stdout>: commitBuffer: invalid argument (invalid character)

DucDuckGo hits seem to indicate it is an error in assuming console supports UTF-8 (Debian build-daemons does not).

Error occurs with pandoc 1.15.1.1 with GHC 7.10.2, but not with pandoc 1.15.0.6 with GHC 7.10.2.

**Comment by jgm** [comment]
Dup of #2457.  Fixed in head and will be fixed in next
release.  If needed for Debian, you can easily cherry-pick
this commit:

https://github.com/jgm/pandoc/commit/317d9eea17e9181e2e0b54651c7f04e6d0e8c230

+++ Jonas Smedegaard [Oct 25 15 19:31 ]:

**Comment by jonassmedegaard** [comment]
Quoting John MacFarlane (2015-10-26 05:03:57)
> Dup of #2457. Fixed in head and will be fixed in next
> release. If needed for Debian, you can easily cherry-pick
> this commit:
> 
> https://github.com/jgm/pandoc/commit/317d9eea17e9181e2e0b54651c7f04e6d0e8c230

Perfect!

...and sorry I didn't find the existing report for this issue.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
