### ISSUE TITLE
Beamer presentations: <recently read> \tightlist

### ISSUE THREAD

**Issue by bachmeil** [jgm/pandoc#2485]
I'm running pandoc 1.15.1 using the provided Ubuntu package.

Example taken from http://pandoc.org/demo/example9/producing-slide-shows-with-pandoc.html

```
% Habits
% John Doe
% March 22, 2005

# In the morning

## Getting up

- Turn off alarm
- Get out of bed
```
Saved in file bugtest.txt. Converted to PDF using

```
pandoc -t beamer bugtest.txt -o bugtest.pdf
```

Output is

```
! Undefined control sequence.
<recently read> \tightlist 
                           
l.61 \end{frame}

pandoc: Error producing PDF from TeX source
make: *** [bug] Error 43
```

**Comment by technocrat** [comment]
The default.latex template is https://github.com/jgm/pandoc-templates/blob/master/default.latex and has the following at lines 143-145

    \providecommand{\tightlist}{%
       \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

When pandoc converts to TeX, if it is reading a template without this definition, you'll see this error.

The most likely cause is a conflicting template in your user data directory (see the output from the bottom of pandoc --version for location).

The file runs correctly under 1.15.1 on OSX.

**Comment by bachmeil** [comment]
You are right. I checked and I have a Beamer template from an older version of Pandoc that fixed another problem with that Beamer template. It was missing the lines above.

**Comment by jgm** [comment]
\tightlist should be defined in the default beamer template.

By the "provided Ubuntu package" do you mean the one from
our github releases page, or from Ubuntu's repository?

ALso, do you have anything in ~/.pandoc/templates?

+++ Lance Bachmeier [Oct 26 15 09:45 ]:

**Comment by bachmeil** [comment]
technocrat's suggestion was correct. I had an edited version of the Beamer template from an old version of Pandoc in ~/.pandoc/templates. I got rid of the old template and now it creates the presentation properly.
