### ISSUE TITLE
[SOLVED] \hyperlink raise an error inside \caption

### ISSUE THREAD

**Issue by hadim** [jgm/pandoc#2490]
`\hyperlink` introduced in d5efa9b35c2e2246d472b5d08367dc58d85ab3f8 does not place nicely with `\caption` command and raise this kind of error : 

```
! Argument of \caption@ydblarg has an extra }.
<inserted text> 
                \par 
```

An easy fix is to use is to use `\protect` wich fix the issue. I tested the following diff and it works for me : 

```diff
$ git diff
diff --git a/src/Text/Pandoc/Writers/LaTeX.hs b/src/Text/Pandoc/Writers/LaTeX.hs
index 9b345fc..7cbfce9 100644
--- a/src/Text/Pandoc/Writers/LaTeX.hs
+++ b/src/Text/Pandoc/Writers/LaTeX.hs
@@ -881,7 +881,7 @@ inlineToLaTeX Space = return space
 inlineToLaTeX (Link txt ('#':ident, _)) = do
   contents <- inlineListToLaTeX txt
   lab <- toLabel ident
-  return $ text "\\hyperlink" <> braces (text lab) <> braces contents
+  return $ text "\\protect\\hyperlink" <> braces (text lab) <> braces contents
 inlineToLaTeX (Link txt (src, _)) =
   case txt of
         [Str x] | escapeURI x == src ->  -- autolink
```

**Comment by hadim** [comment]
@jgm, since the diff is really small, I don't open a PR and let you do the commit.

**Comment by hadim** [comment]
I have a question related to citation. Why does the citation links only applied on the year and note the whole citation ?

**Comment by jgm** [comment]
+++ Hadrien Mary [Oct 28 15 07:24 ]:
>   I have a question related to citation. Why does the citation links only
>   applied on the year and note the whole citation ?

Well, you can have citations like [Smith 1980, 2000, 2007]
where each year links to a different bib entry.

**Comment by hadim** [comment]
Thank you !
