### ISSUE TITLE
4 Spaces are necessary in lists which capital roman numbers

### ISSUE THREAD

**Issue by jevo** [jgm/pandoc#2491]
I've noticed that there is a difference between the formatting and converting of lists.
For example:

~~~~~~
1. item 1
2. item 2 
3. item 3
~~~~~~
and 
~~~~~~
- item 1
- item 2 
- item 3
~~~~~~
and also 
~~~~~~
i. item 1
ii. item 2
iii. item 3
~~~~~~
are converted correct and one space behind the listing sign is enough. But if I use
~~~~~~
I. item 1
II. item 2
III. item 3
~~~~~~

it is converted incorrect to
    <p>I. item 1 II. item 2 III. item 3</p>

but
~~~~~~
I.   item 1
II.  item 2
III. item 3
~~~~~~
is converted correct, where different spaces occur.

**Comment by jgm** [comment]
See the manual:
http://pandoc.org/README.html#extension-fancy_lists
which explains the difference you're seeing.  It's
intentional, not a bug.

+++ Jevo [Oct 29 15 12:23 ]:
