### ISSUE TITLE
Manipulate pandoc variables programmatically before conversion

### ISSUE THREAD

**Issue by mrzool** [jgm/pandoc#2492]
Hi everyone, this is not an issue, I'm searching for input from the Pandoc experts in here.

I'd like to do some basic math on a couple of variables I fetch from the YAML metadata block before printing them into the output. So if in the YAML block I have

````
x: 2
y: 3
````

I would like to come up with a way to end up with `5` in the output (in my case, a PDF through LaTeX).

The problem is, I don't really know where to start. Can something like this be achieved with Pandoc or external tools? I'll be grateful for every input.

**Comment by tarleb** [comment]
These kind of questions are best asked on the [Pandoc discussions mailing list](http://groups.google.com/group/pandoc-discuss).  Please use the issue tracker for bug reports only.

**Comment by mrzool** [comment]
Ok, will do. Thanks for the info.
