### ISSUE TITLE
Feature request: internal links to citations

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#2495]
For HTML output, I see the reference items have already got id's like `<div id="ref-key">`, and I wish there could be links from the citation text to the references section, e.g. `<a href="#ref-key">Foo Bar (2015)</a>`, so readers can easily navigate to the details of a citation.

**Comment by jgm** [comment]
You can do that already, with recent versions of pandoc-citeproc.  Just add

```
link-citations: true
```

to your YAML metadata, using use `--metadata link-citations`
on the command line.

+++ Yihui Xie [Nov 04 15 14:24 ]:

**Comment by yihui** [comment]
Good to know that. I didn't see it in the documentation, though. Thanks a lot!

**Comment by jgm** [comment]
It's in the pandoc-citeproc man page.

+++ Yihui Xie [Nov 04 15 15:43 ]:
