### ISSUE TITLE
Support Jira markup (a form of textile)?

### ISSUE THREAD

**Issue by hisplan** [jgm/pandoc#2497]
Jira Markdown is slightly different from GitHub-flavored Markdown, and it's massively used by lots of software development teams (eBay, Salesforce, LinkedIn, Square, ...)

Any plan to support Jira Markdown?

Here's Jira's markdown spec:
https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all

**Comment by tarleb** [comment]
AFAIK Jira's markup language is Textile, not Markdown.  Textile is fairly well supported by Pandoc, just use <kbd>pandoc -f textile</kbd>  when converting Jira notes.

**Comment by hisplan** [comment]
I do not think JIRA markup is Textile. Just to be sure, I tried http://pandoc.org/try with some JIRA markdown syntax and confirmed that `{code}...{code}` or `{{monospaced}}` were not correctly converted to HTML or any other.

**Comment by tarleb** [comment]
You are right, I missed those `{{mono}}` and `{code}` issues.  I'm not really sure *what* language JIRA is using. It seems closer to Textile than to Markdown (and wikipedia [lists](https://en.wikipedia.org/wiki/Textile_%28markup_language%29) JIRA as a project using textile). However, apparently it isn't standard textile either.

I'm not aware of any plan to support that dialect.  From what I see, it should be possible to add it as a textile variant.  It might actually be a nice task for someone trying to get their feet wet with pandoc/haskell.

**Comment by StevenACoffman** [comment]
From [this Atlassian support source](https://answers.atlassian.com/questions/31681034/how-different-is-jira-markup-from-textile):
> Jira Markdown and Textile are the same for the most used markups like:
> Bullets, enumerable lists, headers, italic, bold, tables, html, quote ...
> 
> And different for other functions like:
> Preformated text, links, identation, code block ...

**Comment by StevenACoffman** [comment]
For reference, [J2M](https://github.com/FokkeZB/J2M/) has some good regex's for the bits of Jira markdown that are not in Textile. Preformated text, links, code block at least. They are [considering using pandoc](https://github.com/FokkeZB/J2M/issues/12) for the much more comprehensive Textile support.

**Comment by retronym** [comment]
Here's a related effort I came across, but haven't tried:

https://github.com/HanStolpo/JiraStructureToDocx/tree/master/PandocReaderJira
https://hanstolpo.github.io/TalksAndStuff/slides/2014-05-12-A_Practical_Haskell_Retrospective_Using_Parsec_REST_and_Pandoc_to_Scrape_Jira.html#(23)

**Comment by jmls** [comment]
did anyone get anywhere with this ? I need to be able to edit jira descriptions in an external website.

**Comment by jeffmacdonald** [comment]
A coworker made this FWIW : https://github.com/stig/ox-jira.el I'm unsure of how applicable this is.

**Comment by tarleb** [comment]
@tupton created a custom Lua writer for JIRA: https://github.com/tupton/pandoc-jira-custom-writer

**Comment by mb21** [comment]
Do we have a reader as well? Or should be open a separate issue about that?

**Comment by tarleb** [comment]
No reader so far; separate issue would be good.
