### ISSUE TITLE
org-mode styles in headers ignored

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#2504]
e.g.

```
** +thing+ other things
```

is rendered literally, rather than having the `strike` styling applied to `thing`. Same for bold/italics/etc.

**Comment by tarleb** [comment]
I tried this with both the current version and v1.13.2.1, but wasn't able to reproduce this.

```
$ echo "** +thing+ other things" | pandoc -f org -t native
[Header 2 ("",[],[]) [Strikeout [Str "thing"],Space,Str "other",Space,Str "things"]]
```

Which Pandoc version are you using and what's the output format?

**Comment by fommil** [comment]
it's in a reveal.js slide if that helps. I'm using `cabal install pandoc` v1.15.1.1. I'll add you to the repo so you can check :smile:

**Comment by fommil** [comment]
@tarleb I shared my slides with you, try doing this on the section titled `Product` (e.g. change to `+Product+ HList`)

**Comment by tarleb** [comment]
Thanks for the sources, I can reproduce it now and am implementing a fix. A minimal version for this bug would be

```
echo "foo\n\n** +test+ testing\n" | pandoc -f org -t native
[Para [Str "foo"]
,Header 2 ("",[],[]) [Str "+test+",Space,Str "testing"]]
```

A (very hacky) temporary fix might be to use plain text as the first text in the header.  E.g.
`** <200b> +Product+ Hlist`, where `<200b> is the zero-width whitespace (<kbd>C-x 8 RET 200b</kbd>).  The extra space should be hardly noticeable in reveal.js.

**Comment by fommil** [comment]
Great, I'll try that! Any idea if you'll get round to the HTML attr parsing? That'd be awesome for setting background images.

**Comment by tarleb** [comment]
I haven't really looked into it yet, sorry.
