### ISSUE TITLE
Expansion of variables in header files

### ISSUE THREAD

**Issue by halloleo** [jgm/pandoc#2511]
Files included via `--include-in-header` could expand variables in the same manner as templates.

This would be greatly appreciated, because then we could add some logic to the header files and would not need to change the default template just for this.

**Comment by jgm** [comment]
With the current architecture, `--include-in-header` just populates a `header-includes` variable (which can also be filled in the metadata).  It behaves like any other variable, so we couldn't change this without changing the way all the other variables behave, which doesn't seem desirable.

I think for now this is a wontfix.
