### ISSUE TITLE
HTML interpretation differing from web browsers

### ISSUE THREAD

**Issue by expipiplus1** [jgm/pandoc#2512]
Both Chrome and Firefox render the html `<em><id></em>` as the string "\<id\>" emphasized. Pandoc outputs an empty emphasized string.

A close reading of the [HTML spec](http://www.w3.org/TR/html5/syntax.html) seems to indicate that this html is malformed: "Foreign elements must either have a start tag and an end tag, or a start tag that is marked as self-closing, in which case they must not have an end tag."

Should Pandoc emulate the behaviour of web browsers here and render the text as though it weren't a tag?

**Comment by jgm** [comment]
By default pandoc will not pass through HTML tags it can't interpret as structural elements.  But if you use `--parse-raw` you'll get `<em><id></em>`.

**Comment by expipiplus1** [comment]
Thanks! This looks more like what I need.

What's the expected behaviour for writers on `RawInline`? `writeMarkdown def` returns `"*<id>*"` as expected, but `writePlain def` and `writeHaddock def` still return `"__"` and `"//"` respectively.

**Comment by jgm** [comment]
+++ Joe Hermaszewski [Nov 12 15 14:01 ]:
>   Thanks! This looks more like what I need.
>
>   What's the expected behaviour for writers on RawInline? writeMarkdown
>   def returns "*<id>*" as expected, but writePlain def and writeHaddock
>   def still return "__" and "//" respectively.

plain and haddock formats don't allow arbitrary raw HTML.
Currently pandoc just omits raw content in formats that
don't support it; e.g. raw latex is omitted in HTML output.

**Comment by expipiplus1** [comment]
gotcha, I'll make a walk to fix this `<id>` issue for me.

Thanks!
