### ISSUE TITLE
YAML lang variable conversion not working for LaTeX writer

### ISSUE THREAD

**Issue by bluetiger300** [jgm/pandoc#2516]
I am working with Pandoc 1.15.1 on Kubuntu 14.04. 
The lang variable (BCP 47 encoded) in a YAML code block is supposed to be converted to the respective variable in LaTex. Instead the variable is passed through, without the conversion taking place.
```
---
author: 
title: Nivel_B1
lang: es
---

## Preguntas ##

- ¿ Por que no vamos ?
- ¿ Que haces el sabado - hay en concierto ?
- ¿ Te apetece + Infinitivo ?
- ¿ Te gustaria + Infinitivo ?
- ¿ Que tal si + Presente ?
```
Converted to LaTeX the `polyglossia` and `babel` variables contain only `es` where they should read `spanish`. I am using a slightly modified standard default.latex template
```
\ifxetex
  \usepackage{polyglossia}
  \setmainlanguage{es}
  \setotherlanguages{}
\else
  \usepackage[shorthands=off,es,ngerman]{babel}
\fi
```

**Comment by mb21** [comment]
Have you updated your templates? (see `~/.pandoc/templates/default.latex`)

**Comment by bluetiger300** [comment]
Just updated the template and the issue is gone. 
I suppose this needs to be done for all other LaTeX related templates!?  Thanks for the information.

**Comment by mb21** [comment]
Yes, it's a good idea to fork the pandoc-templates repo and pull in changes from upstream every time you update pandoc.
