### ISSUE TITLE
text missing when converting docx to epub or mobi.

### ISSUE THREAD

**Issue by dbojan** [jgm/pandoc#2519]
With the latest version on windows: pandoc.exe 1.15.1.1, when converting docx to other formats (epub,mobi, html), parts of text are missing in the output format.
Chapter title exists, but there is no text.

When converting odt to other formats, all is well.
When converting docx using previous version of pandoc (tried using pandoc.exe 1.13.2), it works, too.

files here: https://onedrive.live.com/?id=D3221CFE195F835B!32167&cid=D3221CFE195F835B&group=0

**Comment by jgm** [comment]
I'm sorry, I can't see exactly which text is missing.  Can you please put in a bit of work to create a small (minimal) sample that shows the problem?  E.g. try removing most of the text of your docx, except for the problematic part, to create a new sample.  I don't have time to comb through 300 pages trying to figure out what is missing.

Please let us know also the exact command you used to produce the output you provide.
