### ISSUE TITLE
Specific handling of OneNote HTML

### ISSUE THREAD

**Issue by borekb** [jgm/pandoc#2522]
OneNote is convenient for writing drafts of articles but it generates pretty terrible HTML markup where headings are not real H1/H2/H3 elements, bold is not `<b>` or `<strong>` but `<span style="font-weight: bold">` etc.

Pandoc is already one of the best ways to get Markdown / clean HTML out of OneNote, my current workflow being OneNote > Export > To Word > convert with Pandoc. But for instance headings are not very well understood so I'm filing this ticket to possibly add an input format `html_onenote` and add specific support for it.

**Comment by jgm** [comment]
Too specialized, I think.  Use an HTML transformation tool to convert your spans to proper h1s before passing to pandoc.

**Comment by jgm** [comment]
Or create a pandoc filter.

**Comment by borekb** [comment]
To me it's equally specialized as DOCX support, or all of the Markdown dialects. But if there's not enough demand for it (which there probably isn't), filter is a good suggestion. I guess I should learn how to write them anyway.

Thanks.

**Comment by jgm** [comment]
+++ Borek Bernard [Nov 14 15 07:30 ]:
>   To me it's equally specialized as DOCX support, or all of the Markdown
>   dialects. But if there's not enough demand for it (which there probably
>   isn't), filter is a good suggestion. I guess I should learn how to
>   write them anyway.

It's a really simple filter in this case.  You just match on
a Para that contains just a Span with the appropriate style,
and change it to a Header.  Everything else stays the same.
If you hit a wall, post to pandoc-discuss -- several people
there are happy to help with filters.
