### ISSUE TITLE
Emoji support in markdown_github

### ISSUE THREAD

**Issue by borekb** [jgm/pandoc#2523]
GitHub / GFM supports [emoji](http://www.emoji-cheat-sheet.com/) and it would be nice to have a Pandoc extension for it.

**Comment by borekb** [comment]
Thank you! :clap:

**Comment by miloskroulik** [comment]
This doesn't seem to be working when converting to PDF with `pandoc dokumentace.md -f markdown_github -o dokumentace.pdf`. Following error appears:

```
! Package inputenc Error: Keyboard character used is undefined
(inputenc)                in inputencoding `utf8'.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.83 ... ně odkazujeme pomocí symolů 1^^Le0f^^T
```
The same problem also appears with xetex. I'm using Pandoc 1.15.2

**Comment by jgm** [comment]
Please provide a minimal input file that allows the problem
to be reproduced.  I just tried using a markdown file with
`:smile:` and `--latex-engine=xelatex`.  It compiled fine
and gave me a PDF, though not a smile -- because the font
I'm using doesn't contain a glyph for that unicode code
point.

**Comment by miloskroulik** [comment]
I enclosed the minimal document for inspection:
[emoji.md.txt](https://github.com/jgm/pandoc/files/51779/emoji.md.txt)

Please let me know, if this is what you're looking for. Also, is there some version of Texlive required? I'm using the packages available in Ubuntu 14.04.

**Comment by jgm** [comment]
To simplify things:  the input
```
:one:
```
suffices to reproduce the issue.

**Comment by jgm** [comment]
Looks like there's an issue with `:one:` in HTML output, too.  I'll reopen this issue so we can look into it.

**Comment by jgm** [comment]
OK, I've fixed a bunch of bugs in the emoji character definitions.
But note also that you should use `--latex-engine=xelatex`, and that how the characters appear will depend on your font's support for them.
Thanks for raising this issue!

**Comment by miloskroulik** [comment]
Thanks a lot, I will try it soon.

**Comment by eivindml** [comment]
Hmm. I still have no rendering of emojis when using this. Even with --latex-enginge=xelatex. No errors, but just renders as white space.

**Comment by mb21** [comment]
@eivindml probably your font doesn't have that character...

**Comment by jgm** [comment]
+++ Eivind Lindbråten [Feb 22 17 04:38 ]:
>   Hmm. I still have no rendering of emojis when using this. Even with
>   --latex-enginge=xelatex. No errors, but just renders as white space.

Very likely the reason is that the font you're using doesn't
have glyphs for these emoji characters.  Try with
`--verbose`; you should see some messages about this.

**Comment by eivindml** [comment]
@jgm @mb21 Ok. Thanks! Which font can I use, and how to I specify font with pandoc? On MacOS Sierra.

**Comment by mb21** [comment]
@eivindml the following might work:

    echo 'hi :smile: :one:' | pandoc -f markdown+emoji --latex-engine=lualatex -o foo.pdf --variable mainfont="DejaVu Sans"

**Comment by mb720** [comment]
I tried

    echo 'hi :smile: :one:' | pandoc -f markdown+emoji --pdf-engine=lualatex -o foo.pdf --variable mainfont="DejaVu Sans"

but got this error:

>[WARNING] Missing character: There is no ⃣ (U+20E3) in font DejaVuSans:mode=node;script=

**Comment by jgm** [comment]
As the message indicates, you need to use a font that actually has this glyph.  (See `mainfont`.)
Please ask questions on pandoc-discuss rather than closed issues.
