### ISSUE TITLE
markdown_github acts as if `--email-obfuscation` was set to javascript

### ISSUE THREAD

**Issue by borekb** [jgm/pandoc#2528]
markdown_github automatically triggers JS email obfuscation which is causing trouble to one tool I am using. I don't think there is a reason for this behavior - plain Markdown does not obfuscate email and I don't think GFM should either - try to "view source" for this: test@example.com .

![pandoc-email-obfuscation](https://cloud.githubusercontent.com/assets/101152/11164216/50ecf890-8aea-11e5-88b8-ed366a8f505e.png)

**Comment by jgm** [comment]
It's not specific to `markdown_github`.  It's controllable with a command-line option and affects all HTML output, no matter what the source format:

```
       --email-obfuscation=none|javascript|references
              Specify a method for obfuscating  mailto:  links  in  HTML
              documents.    none  leaves  mailto:  links  as  they  are.
              javascript obfuscates them using  javascript.   references
              obfuscates  them  by  printing their letters as decimal or
              hexadecimal character references.
```

The default is javascript, but maybe in this day and age that should be changed to none or references (which was the Markdown.pl behavior)?

**Comment by borekb** [comment]
Tried input formats `markdown`, `markdown_strict`, `markdown_phpextra` and `markdown_github`. All defaulted to no obfuscation, only `github` format did it.

**Comment by tarleb** [comment]
The writer always behaves the same, it's only `markdown_github` which converts mail addresses to `mailto` links.  That's where the differences come from.

@jgm: I'm personally a big fan of CSS-based obfuscation.  Addresses remain readable and in the default text color/style even without javascript, degrade gracefully in text-only browser with limited CSS support, and can be turned back into normal links with just a little bit of scripting.  Poorly written description [here](https://zeitkraut.de/posts/2013-08-25-avoiding-spam.html).

**Comment by borekb** [comment]
Thanks for the explanation. I was actually reading the docs for the `--email-obfuscation` parameter carefully and didn't find any hint that JS obfuscation is turned on by default.

**Comment by jgm** [comment]
@tarleb the CSS obfuscation scheme you link would be really easy for a harvester to get around:  just look for `data-user` and `data-domain` attributes.  So I think pandoc's js obfuscation is probably a bit safer (though certainly harvesters could be built to handle it too).  The question is whether obfuscation of any kind is necessary any more.  I think nowadays people just rely on spam filters and don't worry about having their emails out there.

**Comment by tarleb** [comment]
I had lengthy discussions on this topic. The consensus seems to be that it doesn't matter which method is used, as long as only a minority of people is using the same method.  As soon as it becomes mainstream, harvesters will adapt.  People have [compared](http://techblog.tilllate.com/2008/07/20/ten-methods-to-obfuscate-e-mail-addresses-compared/) different methods, and at least in 2008, CSS-based obfuscation was highly effective.

Either way, I guess you are right that just dropping the obfuscation is the sane thing to do nowadays.  Apparently [Cory Doctrorow](http://www.theguardian.com/technology/2010/dec/21/keeping-email-address-secret-spambots) has been arguing that as long as 5 years ago.

**Comment by jgm** [comment]
This should probably be discussed on pandoc-discuss.
