### ISSUE TITLE
Footnotes in docx

### ISSUE THREAD

**Issue by tomak-git** [jgm/pandoc#2534]
Hi, I have encountered the same behavior as described in bug #637 (Footnote is not formatted properly - its number is not an index and it is not separated from content by space/tab/whatever is normally used). However, the bug occurs when displaying the docx file in both LO Writer and MS Word. In .odt, footnotes look as expected (checked only with LO Writer so far). Versions of software I use:

Pandoc 1.14.0.1 (on my Ubuntu machine) - output checked only with Writer so far
Pandoc 1.15.1.1 (on my Windows machine) - output checked with both Writer and Word
LO Writer 5.0.2.2
MS Word - can't check right now but it's fairly recent

See the attached sample files (I had to rename test.md to test.txt because Github doesn't support uploading .md files).

[test.txt](https://github.com/jgm/pandoc/files/34811/test.txt)
[test.docx](https://github.com/jgm/pandoc/files/34812/test.docx)

I'm using simply `pandoc test.md -o test.docx` to make the conversion.

**Comment by jgm** [comment]
Is this a dup of #2527?  I don't know what you mean by "number is not an index," but #2527 is complaining about the lack of a space between the footnote reference and the rest.
The footnote number should be styled with the "Footnote Reference" style.  In the default style it's superscripted, but maybe you're using a custom reference.docx?

**Comment by tomak-git** [comment]
Thanks for the quick response! By index I meant superscript, sorry for the bad wording.

I guess it's related to #2527, although I'm not sure if this is an exact duplicate. The point is that it looks like the number of the footnote has the same style as the rest of the footnote, although the footnote number is not really part of the text (it can't be manually edited and so no separate style can be assignet to it). Overall, the result looks like a footnote that just begins with a number, which is styled the same as the rest of the footnote (not superscript) and is in no way separated from its contents (no space, tab, etc.).

For debugging purposes, I'm not using any reference file with custom styles. I use only the command mentioned above, which in the case of .odt creates the expected result (the number is not superscript, but at least it's separated from the rest of the footnote), but with .docx it doesn't. See the screenshots for comparison.

![fn-screen-docx](https://cloud.githubusercontent.com/assets/5860787/11168376/ff9aaef8-8b8c-11e5-9310-b8797cc8d9df.png)
![fn-screen-odt](https://cloud.githubusercontent.com/assets/5860787/11168377/09a03922-8b8d-11e5-9477-8465c1d559ea.png)

**Comment by jgm** [comment]
Oh, so you're viewing the docx using LibreOffice.  I opened your test.docx with Word, and the footnote reference is superscripted.  So this may in fact be a bug in LibreOffice?

**Comment by tomak-git** [comment]
Well, I had exactly the same problem when viewing a docx file created by pandoc in Word. It was not this exact file, but the result was the same so I assumed it applies also to Word. I can try this exact file tomorrow on the windows machine and let you know, possibly provide a screenshot.

**Comment by jgm** [comment]
Okay -- it's strange.  I don't have a version of Word on
Windows, just on OSX.  But you might ask on pandoc-discuss
whether other Word/Windows users have seen this.  I've
not heard it reported by others.

+++ tomak-git [Nov 15 15 08:01 ]:

**Comment by conklech** [comment]
I just examined `test.docx` using Word 15.0.something on Windows, with the following results:

![image](https://cloud.githubusercontent.com/assets/573035/11170663/d35a410c-8b8f-11e5-8f9f-57c97b598eff.png)

![image](https://cloud.githubusercontent.com/assets/573035/11170667/df30555c-8b8f-11e5-986c-628de5a586d0.png)

It appears to be normal, modulo the #2527 behavior.

If it's relevant, @tomak-git, in Word the footnote reference in the text and in the footnote use the same character style, which makes it impossible to style the two separately. Pandoc replicates that behavior AFAIK, and uses the same character style in both places. So it's quite odd (from a Word perspective) that your footnote numbers appear differently. I don't know why that would cause problems in LibreOffice, unless they deliberately override the character style somehow.

**Comment by tomak-git** [comment]
Okay, I just checked with Word and I got the same result as @conklech, so I'm not able to replicate the issue. Well, it seems that it works as it's supposed to (taking into account the #2527 issue), and that's good news. I'll update this if I encounter that behavior again. I'm also thinking about filing a bug against Writer about this but I'll have to do some research first. We'll see.

Anyway, thanks for looking into this and also thanks for the great job you're doing at developing/maintaining Pandoc!

**Comment by jgm** [comment]
Geat, let's close this issue then.  #2527 has been fixed
in the latest release.

+++ tomak-git [Nov 15 15 23:53 ]:

**Comment by phmarek** [comment]
Hi,

using pandoc 2.1.3 the footnote numbers (that should be superscript etc.) appear just like normal text.

If I mark them and associate the footnote marker style, they're formatted correctly, so it seems that the ''.docx'' export simply won't set the style.
