### ISSUE TITLE
Allow automatic links without protocol

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2538]
It would be handy to allow automatic links that do not include a protocol, i.e. converting `<pandoc.org>` to `<p><a href="http://pandoc.org">pandoc.org</a></p>` rather than `<p><pandoc.org></p>`. (But not a priority if this would have implications that I am not considering.)

**Comment by jgm** [comment]
Here I'm just following Markdown standard practice, which
doesn't treat such things as links.

+++ Andrew Dunning [Nov 16 15 07:16 ]:

**Comment by adunning** [comment]
Figured there was a reason for it; thanks for the explanation.
