### ISSUE TITLE
Citation example's output broken?

### ISSUE THREAD

**Issue by petripartanen** [jgm/pandoc#2539]
Hey,

Could someone have a look at the citation examples. I don't know how it is supposed to look like, but http://pandoc.org/demo/example24b.html doesn't seem quite right.

**Comment by jgm** [comment]
Thanks, I've added `--filter pandoc-citeproc` and rebuilt.  I'll also adjust pandoc's code so that pandoc-citeproc is used automatically even if a shortened form of the `--bibliography` option (`--biblio`) is used.

**Comment by petripartanen** [comment]
Thank you. I'll close the issue.
