### ISSUE TITLE
Horizontal rule 50% width in PDF

### ISSUE THREAD

**Issue by dotpao** [jgm/pandoc#2544]
Why Horizontal rules are written as [this](https://github.com/jgm/pandoc/blob/83b1aa042d72cdb7790eec1de5d86bf2bded60db/src/Text/Pandoc/Writers/LaTeX.hs#L557)?

`\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}`

And not as

`\begin{center}\rule{\linewidth}{\linethickness}\end{center}`

Why do you put the 0.5 factor? When you convert from HTML to PDF, you expect the `<hr>` fits the whole page width and not the 50%.

**Comment by jgm** [comment]
In printed books one normally doesn't see horizontal rules
stretching across the whole page.  Usually a shorter
separator is used.  Hence the default.  Of course, you
can easily change it by using a custom template.

If you think the default should be changed, I suggest
you close this (this tracker isn't really the place
for questions) and raise the issue on the pandoc-discuss
mailing list.  If there's general consensus about
changing the default there, I'll consider it.

+++ Carlos Rodríguez [Nov 18 15 03:35 ]:

**Comment by jgm** [comment]
Clarification:  you cannot change the default by changing
the template; this is hardwired into the writer.

It would probably be better to define a command in the
template (perhaps redefine \hrule) so people can change
this.

You might keep this open but raise the issue for discussion
on pandoc-discuss.

**Comment by dotpao** [comment]
This is more or less what I've added to my custom template
>\let\oldrule=\rule 
>\renewcommand{\rule}[1]{\oldrule{\linewidth}}

It is discussed [here](https://groups.google.com/forum/#!searchin/pandoc-discuss/Horizontal$20rule/pandoc-discuss/LzV15A8dyDs/bI380ghz-BgJ)

**Comment by jlduran** [comment]
I agree that the width of the line should not be hardcoded. The current code was introduced in #1574.

I could propose a PR defining, for example `\hrwidth = 0.5\linewidth`, and using this variable in the code instead. However, this will break all current custom templates using `<hr>` (#1571 shows us that this kind of changes should only be introduced in major version numbers).

**Comment by tarleb** [comment]
Closing in favor of the more general #1541.

An existing general solution is to override the hard-coded TeX code via a filter, e.g. with `--lua-filter=custom-hrule.lua`, where the file `custom-hrule.lua` would contain something like

``` lua
local my_hrule = [[\begin{center}\rule{\linewidth}{\linethickness}\end{center}]]

function HorizontalRule (_) return pandoc.RawBlock('tex', my_hrule) end
```

See [filters](https://pandoc.org/filters.html) and [Lua filters](https://pandoc.org/lua-filters.html).
