### ISSUE TITLE
DocX reader does not read more than 1 paragraph of a single list bullet

### ISSUE THREAD

**Issue by infinitisp** [jgm/pandoc#2545]
(see test.docx below)

Hi. If you read this docx file into pandoc, the "two" and "three" are scrubbed completely. 

This same bug does not occur when a soft return is used to create the list. 

To recreate this document in word:
1. Create a list
2. Hard return to create a new list item
3. Press backspace to remove the list bullet/number. This second bullet is now part of the previous list bullet, but is ignored by the Docx reader.

**Comment by infinitisp** [comment]
Also, exact command used to produce output is any of:
pandoc test.docx -f docx -t markdown -s -o out.md
pandoc test.docx -f docx -t html-s -o out.html
pandoc test.docx -f docx -t latex-s -o out.pdf

**Comment by jgm** [comment]
@jkr can you see what's going on here?

**Comment by jkr** [comment]
I'll take a look at it as soon as I get home to a working copy of word. @infinitisp, would you mind posting the working soft-return file as well, when you get a chance?

**Comment by infinitisp** [comment]
[text_2.docx](https://github.com/jgm/pandoc/files/38110/text_2.docx)

Try this one. One, Three, Four and Five show up, but the Two is scrubbed. 

Thanks for looking into this!

**Comment by jkr** [comment]
I see what's happening -- word has the second two items (which it sees as a single two-paragraph item) referenced with a list item that doesn't exist. To be more specific, it now sees two lists: one list that has a numeric bullet type with one entry ("One") and another list which has a dummy bullet type with one entry ("Two<br\><br\>Three"). We don't deal properly with that (non-existent in the numbering file) list type.

I think those dummy bullets are produced through explicit backspacing of the bullet. @infinilisp, was the bullet before "Two" in the second example the only one you backspaced on?

There are two things to do here:

 1. Don't erase dummy bullet items. Whatever else we do, don't erase them.
 2. Come up with some standard on how to deal with them. I propose the following, but @jgm, tell me what you think: if a dummy list item is after a list item, it folds into that list item. If it's after any other sort of paragraph, it gets treated as a normal paragraph. That seems to

**Comment by infinitisp** [comment]
In the first Test document, the Three was created by pressing enter after
the Two, which would, as you say, create a new item in the dummy bullet
list.

This came up from a real document I was trying to convert, and I agree that
your proposed approach (folding them into the previous list item when they
follow it) would address my specific use case. I am not sure if it would
address all use cases, but it seems like a reasonable approach.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Nov 18 15 09:21 ]:
>    2. Come up with some standard on how to deal with them. I propose the
>       following, but [1]@jgm, tell me what you think: if a dummy list
>       item is after a list item, it folds into that list item. If it's
>       after any other sort of paragraph, it gets treated as a normal
>       paragraph. That seems to

Sounds good to me!

**Comment by jkr** [comment]
@infinitisp 

Does this look like the output you were expecting?

```{html}
<ol style="list-style-type: decimal">
<li><p>One</p>
<p>Two<br />
<br />
Three</p></li>
</ol>
```

and 

```{html}
<ol style="list-style-type: decimal">
<li><p>One</p>
<p>Two</p></li>
<li><p>Three<br />
Four<br />
<br />
Five</p></li>
</ol>
```

If so, I've got the fix. If you could do me one favor, though, as a test case: could you create a file with the first bullet point created and then deleted? I'd like to make sure that in that case, we just treat it as an indented paragraph.

**Comment by infinitisp** [comment]
I'm guessing from that output that I did create the very first test1.docx using two soft returns for the Three instead of a single hard return (and I just verified that this is the case). That output looks good to me!

Here is the new test case for you, which also includes one of these dummy bullets following a normal paragraph.

[test_3.docx](https://github.com/jgm/pandoc/files/38156/test_3.docx)
.

**Comment by jkr** [comment]
@infinitisp  I'm going to the first and third docx as part of the test suite. Is that okay? (You don't have any secret identifiying stuff in the document metadata?)

**Comment by infinitisp** [comment]
Hi Jesse. Thanks for pointing that out. Please use these instead:

[test.docx](https://github.com/jgm/pandoc/files/38214/test.docx)

[test_3.docx](https://github.com/jgm/pandoc/files/38215/test_3.docx)

**Comment by jkr** [comment]
Pushed with 5527465c778736e91e88fae414ea26558b966724
