### ISSUE TITLE
'vpath' feature for images

### ISSUE THREAD

**Issue by lemzwerg** [jgm/pandoc#2546]
[pandoc 1.12.3.3]

An instruction like

```
![foo](img/foo.png)
```

makes pandoc search only the current directory for `img/foo.png`.  Especially for builds where srcdir != builddir, and where generated images are used also, it would be very nice if pandoc could provide a 'vpath' feature to give a list of directories to search for such images (and probably other files also), e.g.

```
pandoc -I ../aaa -I ../bbb ...
```

to make pandoc search `img/foo.png`, `../aaa/img/foo.png`, and `../bbb/img/foo.png`.

**Comment by linquize** [comment]
Like C header file include mechanism

**Comment by lemzwerg** [comment]
Exactly. Depending on the output format, this could either be used to configure corresponding environment variables (e.g., TEXINPUTS), or to include correct file paths in the generated output files.

**Comment by jgm** [comment]
The feature could not be implemented in most of the writers,
which are pure (not in the IO monad) and cannot search the
file system.  Perhaps it could be implemented as a filter,
though.  The filter would be quite simple to write.  It
would simply look for Image inlines, check to see if the
image can be found on the file system, and if not, it
would search a list of other paths, determined by the
vpath metadata field.  If a match is found, the Image's
source would be rewritten.

Such a filter would work for all output formats, and could
be written to work with current pandoc.

+++ lemzwerg [Nov 19 15 03:23 ]:

**Comment by jgm** [comment]
Dup of #852 - I plan to implement this.
