### ISSUE TITLE
markdown to html, absence of css

### ISSUE THREAD

**Issue by saccohuo** [jgm/pandoc#2548]
I write a **markdown** file, which contains many **inline codes** but **no fenced code**. When I use pandoc to convert **markdown to html**, there is an **absence of CSS of "code"** in the converted html file.
If I **put fenced code** within the markdown file, the converted **html file will contain CSS of "code"**.
Can you help me with the problem?
My PC operates in **Win7 64bit** OS and **Pandoc 1.15.2**.

**Comment by saccohuo** [comment]
I find the reason is that I use remote css file as my css rendering file, and my network is not always able to connect to the corresponding server. It is all my fault. Sorry for that.

**Comment by jgm** [comment]
Search the user's guide for inline_code_attributes.

If you want highlighting, you need to specify the language.

In fenced blocks:

   ``` ruby
   a = 4
   ```

or

   ~~~ {.ruby}
   a = 4
   ~~~

In inline code,

   This statement `a = 4`{.ruby}


+++ husky [Nov 20 15 03:43 ]:
