### ISSUE TITLE
Problems with LaTeX reader and hyperref

### ISSUE THREAD

**Issue by blindmelon** [jgm/pandoc#2549]
## Problem

When converting from markdown to latex, headers which have been referenced become hyperref targets. On converting these back to markdown, the targets and the references get lost.

This could because the latex writer has developed faster than the reader.
## Example

``` markdown
%  A test document
% Myself
%  2015-11-21

Some text

# Zeroeth Chapter {#zero}

I won't actually refer back to this one.

# First Chapter {#First}

A chapter with a link

# Second Chapter

A chapter without

# Third {#third}

One with again

See the [Introduction](#First)
See the [Conclusion](#third)

```

and running:

``` sh
pandoc test.md -s -o test.tex
pandoc -t markdown --atx-headers -s test.tex
```

returns:

``` markdown

---
author:
- Myself
date: '2015-11-21'
title: A test document
...

Some text

# Zeroeth Chapter {#zero}

I won’t actually refer back to this one.

A chapter with a link

# Second Chapter

A chapter without

One with again

See the See the
```
## Expected behaviour

Latex reader should at a minimum support the same features as the Latex writer, here meaning that the output file is semantically the same as the input file by understanding hyperref commands.

**Comment by jgm** [comment]
We should parse `\hyperlink{identifier}{contents}`
as `Link contents ('#':identifier, "")` and
`\hypertarget{identifier}{contents}` as
`Span ('#':identifier,[],[]) contents` if contents
parses as inlines, or `Div...` if it parses as blocks.
In the special case where it parses as a Header,
we can just insert the attribute directly into the
Header.

**Comment by jgm** [comment]
We should parse `\hyperlink{identifier}{contents}`
as `Link contents ('#':identifier, "")` and
`\hypertarget{identifier}{contents}` as
`Span ('#':identifier,[],[]) contents` if contents
parses as inlines, or `Div...` if it parses as blocks.
In the special case where it parses as a Header,
we can just insert the attribute directly into the
Header.
