### ISSUE TITLE
Umlauts in File > conversion into wrong html entities or not possible

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#255]
<b>What steps will reproduce the problem?</b>
1. Generate a text-file (2do.txt) containing the words "für Qualitätsplot" (among other things in 
markdown syntax)
2. issue "pandoc -s 2do.txt -o 2do.html" in terminal
3. everything works fine, expcept the html-file now contains "fŸr QualitŠtsplot"
4. issue "markdown2pdf 2do.txt -o 2do.pdf"
5. markdown2pdf doesn't want to convert anything
6. issue "pandoc -s 2do.txt -o 2do.tex"
7: TeX-file contains " f¬ür Qualit¬ätsplot" 

<b>What is the expected output? What do you see instead?</b>
3. correct HTML entities
4: working conversion
7: f\"{u}r Qualit\"{a}tsplot

<b>What version of the product are you using? On what operating system?</b>
pandoc-0.46, downloaded today on OS X 10.5.4

<b>Please provide any additional information below.</b>

Google Code Info:
Issue #: 84
Author: david.haberthuer
Created On: 2008-08-21T11:19:57.000Z
Closed On: 2008-08-24T18:44:16.000Z

**Comment by trevor87** [comment]
Even though this is a old post, for future reference: I had a similar problem with umlauts. I could solve it by adding the -s (standalone) option, e.g. pandoc test.md -o test.html -s
