### ISSUE TITLE
How to make clickable references in html5 docs?

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#2551]
Hi,

Is there here any option to generate clickable references in html?

**Comment by jgm** [comment]
See the man page for pandoc-citeproc s.v. 'link-citations'.

+++ Xavier [Nov 21 15 10:58 ]:

**Comment by somenxavier** [comment]
> s.v. 'link-citations'.
What is that?

**Comment by jgm** [comment]
Put

link-citations: true

in your YAML metadata.

+++ Xavier [Nov 21 15 11:13 ]:

**Comment by jgm** [comment]
Or use the command-line option
--metadata link-citations=true

+++ Xavier [Nov 21 15 11:13 ]:

**Comment by ousia** [comment]
>> s.v. 'link-citations'.
>
> What is that?

“s. v.’ stands for _sub voce_ or _sub verbo_. Literally, “under the voice” or “under the word” (in a dictionary).

@jgm, does pandoc have a proper man page? I get the following error message in Fedora

```
$ man pandoc 
No manual entry for pandoc
```

If there is a man page, I’ll report in Fedora so that it gets included in the package.

**Comment by jgm** [comment]
Yes, pandoc has a man page (man/pandoc.1 in the source).

**Comment by somenxavier** [comment]
> Or use the command-line option --metadata link-citations=true

Thanks a lot,
