### ISSUE TITLE
Reveal.js and self-contained option

### ISSUE THREAD

**Issue by hugoroy** [jgm/pandoc#2553]
In a markdown document, 

```
---
revealjs-url: /local/filesystem/to/reveal.js
...
```

Then giving the content to pandoc:

     pandoc --read=markdown --write=revealjs --output=/local/fs/slides.html --self-contained --slide-level=2 --standalone --smart

The result will not be a completely self-contained document, as far as I can see, some reveal.js files will still be referenced (in this case, to `/local/filesystem/`).

**Comment by jgm** [comment]
Yes, I'm seeing local references here in the head:

```html
    link.href = window.location.search.match( /print-pdf/gi ) ? '/home/me/src/reveal.js/css/print/pdf.css' : '/home/me/src/reveal.js/css/print/paper.css';
```
```html
    link.href = window.location.search.match( /print-pdf/gi ) ? '/home/me/src/reveal.js/css/print/pdf.css' : '/home/me/src/reveal.js/css/print/paper.css';
```
```html
  <script src="/home/me/src/reveal.js/lib/js/html5shiv.js"></script>
  <![endif]-->
```

and also here at the end of the body:

``` html
        dependencies: [
          { src: '/home/me/src/reveal.js/lib/js/classList.js', condition: function() { return !document.body.classList; } },
          { src: '/home/me/src/reveal.js/plugin/zoom-js/zoom.js', async: true },
          { src: '/home/me/src/reveal.js/plugin/notes/notes.js', async: true }
        ]
      });
```

Are these the ones you mean?

Here's the problem. With the exception of of `<script>` tag in the
head, these references all occur in the context of JavaScript code.
Pandoc's `--self-contained` isn't yet smart enough to parse JavaScript,
and it's not clear to me how all of these could be replaced by the raw data.

In the case of the `<script>` tag, I'm not sure why `--self-contained`
didn't do its thing here.  I do have html5shiv.js at that location in
my path...  Need to look into this.

Fortunately none of these problems affect basic slide functionality.

**Comment by jgm** [comment]
Oh, I see, the html5shiv.js wasn't incorporated because it's
in a comment that is designed to hide it unless an older
version of IE is used.  So all is okay here.  You've just
run across a limitation of `--self-contained` that I don't
see any way around.  I've documented it but I don't think
there's more I can do on this issue.

+++ John MacFarlane [Nov 23 15 18:37 ]:
>Yes, I'm seeing local references here in the head:
>
>```html
>   link.href = window.location.search.match( /print-pdf/gi ) ? '/home/me/src/reveal.js/css/print/pdf.css' : '/home/me/src/reveal.js/css/print/paper.css';
>```
>```html
>   link.href = window.location.search.match( /print-pdf/gi ) ? '/home/me/src/reveal.js/css/print/pdf.css' : '/home/me/src/reveal.js/css/print/paper.css';
>```
>```html
> <script src="/home/me/src/reveal.js/lib/js/html5shiv.js"></script>
> <![endif]-->
>```
>
>and also here at the end of the body:
>
>``` html
>       dependencies: [
>         { src: '/home/me/src/reveal.js/lib/js/classList.js', condition: function() { return !document.body.classList; } },
>         { src: '/home/me/src/reveal.js/plugin/zoom-js/zoom.js', async: true },
>         { src: '/home/me/src/reveal.js/plugin/notes/notes.js', async: true }
>       ]
>     });
>```
>
>Are these the ones you mean?
>
>Here's the problem. With the exception of of `<script>` tag in the
>head, these references all occur in the context of JavaScript code.
>Pandoc's `--self-contained` isn't yet smart enough to parse JavaScript,
>and it's not clear to me how all of these could be replaced by the raw data.
>
>In the case of the `<script>` tag, I'm not sure why `--self-contained`
>didn't do its thing here.  I do have html5shiv.js at that location in
>my path...  Need to look into this.
>
>Fortunately none of these problems affect basic slide functionality.
>

**Comment by hugoroy** [comment]
↪ 2015-11-24 Tue 03:38, John MacFarlane <notifications@github.com>:
> Fortunately none of these problems affect basic slide functionality.

True, but it seems they affect the “speaker” mode, doesn't it?

I agree that documenting this would be useful.

-- 
Hugo Roy – Free Software Foundation Europe https://fsfe.org/about/roy
 
Please use cryptography for email: see https://emailselfdefense.fsf.org/en/
Merci d’utiliser la cryptographie pour l’email : voir https://emailselfdefense.fsf.org/fr/

**Comment by jgm** [comment]
It's documented now.

+++ Hugo Roy [Nov 24 15 03:01 ]:
