### ISSUE TITLE
image height + width attributes in markdown_github output

### ISSUE THREAD

**Issue by peterjc** [jgm/pandoc#2554]
According to recent commit https://github.com/jgm/pandoc/commit/244cd5644b44f43722530379138bd7bb9cbace9b pandoc 1.16 will add basic support for image sizes.

I would like to specify image sizes for GitHub Flavour Markdown (GFM) and GitHub Pages rendered with Jekyll, using the output from pandoc.

Apparently GitHub briefly supported their own syntax for image sizes in GFM, but now an HTML snippet is required - see http://stackoverflow.com/questions/24383700/resize-image-in-the-wiki-of-github-using-markdown or https://gist.github.com/uupaa/f77d2bcf4dc7a294d109

i.e. If the image has no size information, continue to produce a classic markdown image. However, if the height or width is specified, in order to get a useful image displayed via GitHub, substitute the HTML snippet.

**Comment by peterjc** [comment]
A few examples using the GFM as implemented in the GitHub issue tracker (close to but not identical to GitHub Pages rendered with Jekyll).

No scaling, use a standard markdown image ``![test](https://github.com/favicon.ico)``

![test](https://github.com/favicon.ico)

Defunct GFM, ``![test](https://github.com/favicon.ico | width=48)``

![test](https://github.com/favicon.ico | width=48)

Defunct GFM, ``![test](https://github.com/favicon.ico =24x48)``

![test](https://github.com/favicon.ico =24x48)

Sadly this kramdown variant does not work with GFM, ``![test](https://github.com/favicon.ico){:height="24px" width="48px"}``

![test](https://github.com/favicon.ico){:height="24px" width="48px"}

No scaling, with HTML ``<img src="https://github.com/favicon.ico">``

<img src="https://github.com/favicon.ico">

Setting width to 48, with HTML ``<img src="https://github.com/favicon.ico" width="48">``

<img src="https://github.com/favicon.ico" width="48">

Setting height to 24, with HTML ``<img src="https://github.com/favicon.ico" height="24">``

<img src="https://github.com/favicon.ico" height="24">

Setting height to 24, and width to 48, with HTML ``<img src="https://github.com/favicon.ico" height="24" width="48">``

<img src="https://github.com/favicon.ico" height="24" width="48">

**Comment by mb21** [comment]
markdown_github is defined as a bunch of extensions that are enabled (see the README). The width and height (and other) image attributes are enabled in the link_attributes extension (not enabled for markdown_github, so they are dropped).

So to support the requested feature, we'd have to create a new extension called github_images or so and change the Markdown writer accordingly.

**Comment by peterjc** [comment]
Thanks for your architectural insights - this sounds non-trivial then.

**Comment by jgm** [comment]
+++ Mauro Bieg [Nov 24 15 09:28 ]:
>   markdown_github is defined as a bunch of extensions that are enabled
>   (see the README). The width and height (and other) image attributes are
>   enabled in the link_attributes extension (not enabled for
>   markdown_github, so they are dropped).
>
>   So to support the requested feature, we'd have to create a new
>   extension called github_images or so and change the Markdown writer
>   accordingly.

I'm not sure why---all flavors of Markdown accept raw HTML,
so the plan of using HTML for images with attributes makes
sense without a new extension (well, we'd use the existing
`raw_html` extension).

This would become the default treatment not just for
markdown_github but for all markdowns without
link_attributes.

**Comment by mb21** [comment]
Right, of course. I didn't think of the raw_html extension...

**Comment by peterjc** [comment]
Lovely - thanks!

**Comment by zhangbg** [comment]
Thanks, it work!

**Comment by vishi9780** [comment]
is there is any way to resize the `gif` image

**Comment by regalstreak** [comment]
Resize gifs using the same way you resize images using the <img> tag

`<img src="https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif" width="300" />`

<img src="https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif" width="300" />
