### ISSUE TITLE
Space around ellipses is handled inconsistently

### ISSUE THREAD

**Issue by klausman** [jgm/pandoc#2557]
```
$ echo 'Well \dots I would.' |pandoc -f latex -t plain
Well …I would.
$
```

I'd expect the spaces I put around `\dots` to also be around the `…` in the output. I can of course turn every `\dots ` into a `\dots\ `, but that seems hackish.

**Comment by klausman** [comment]
Also note:

echo 'Well … I would.' |pandoc -f latex -t plain

**Comment by jgm** [comment]
Note that in TeX any space following a command sequence is
ignored.  So, `\ldots I would` is exactly the same, for
TeX, as `\ldots{}I would`.  You can verify this with
pdflatex.  So pandoc is parsing correctly here.

Try `\ldots{} I would` in your input.

+++ Tobias Klausmann [Nov 25 15 02:05 ]:

**Comment by klausman** [comment]
Huh. I never noticed. You're right. Well, one more thing to add to my input filters. And I'll start just using … (the literal) so it's unambiguous.
