### ISSUE TITLE
unexpected converting for hash characters with dashes

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#2558]
Markdown text: 
```
##test
---
```
Converted html by pandc:
```
<h2 id="test">##test</h2>
```
Expected html:
```
<h2 id="test">test</h2><hr />
```

**Comment by jgm** [comment]
This is a precedence issue.  Gruber's syntax description is just ambiguous here -- is this an atx header followed by an hrule, or a setext header with contents `##test`?  Pandoc goes for the latter, giving setext headers priority.  There isn't really a right answer.  If you want the dashes to be an hrule, just put a blank line in front.  (Btw, this is precisely the kind of ambiguity that the CommonMark spec aims to settle.)

As you can see on [Babelmark2](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23%23test%0A---%0A), there's a lot of difference of opinion about this case between different implementations.
