### ISSUE TITLE
Suggest compatible with 3 spaces before asterisk for nested lists

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#2559]
Example markdown text:
```
* `database`
   * `update`–Updates the database to a specified migration
* `dbcontext`
   * `list`–List your DbContext types
   * `scaffold`–Scaffolds a DbContext and entity type classes for a specified database
* `migrations`
```
It can't be converted to nested lists by pandoc. But it works on github.

**Comment by jgm** [comment]
See the [User's Guide](http://pandoc.org/README.html#the-four-space-rule).

Fuller discussion of the options [in the CommonMark spec](http://spec.commonmark.org/0.22/#motivation).

Markdown implementations are all over the place on this.  If we move to anything other than the 4-space rule, it would be the rule described in the CommonMark spec.  Every other implementation has lots of weird edge cases.  The hard thing is getting the interaction between list nesting and indented code blocks right.
