### ISSUE TITLE
User-specifiable abbreviations?

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#256]
Pandoc knows to treat the space after "Mr." as a nonbreaking space rather than a sentence-ending space (the distinction matters in LaTeX without French spacing).  Other abbreviations common in English are also recognized. But this is objectionably language-centric and needs to be configurable.

**Comment by jgm** [comment]
I don't think this would be too hard.

We need an option `--abbreviations-file=PATH`.
And a reader option `readerAbbreviations`, which could default to the list we're currently using.
Pandoc could simply populate this with the contents of the file if it's specified.
We'd need changes to Text.Pandoc.Parsing, Text.Pandoc.Readers.Markdown, MANUAL.txt (noting that this just affects the markdown reader), and Text.Pandoc.App (new option).

File format could be just a list of abbreviations, one per line.
```
Mr.
Mrs.
Dr.
```

**Comment by jgm** [comment]
- [ ] Add `--abbreviations` option in Text.Pandoc.App.  This should read a file, split it (by lines? by words?) and populate the readerAbbreviations in ReaderState.
- [ ] Document `--abbreviations` and the file format in MANUAL.txt.
- [ ] Test case.

**Comment by mb21** [comment]
> Question: Instead of a default value in Options, should we leave it empty there and populate from a data file in Text.Pandoc.App? Performance impact on reading this every time?

Not sure about performance, but somehow feels wrong to hit the disk for such a simple thing... if so, we should read the file when compiling/building pandoc IMHO.

**Comment by jgm** [comment]
@mb21 I'm not too worried about it; the performance hit is on the order or 0.01 second at most (and is incurred once every time the pandoc executable is run).  If you compile with `embed_data_files`, the file won't even need to be read from disk, though pandoc will still check to see if you have an abbreviations file in the user data directory (so that does involve looking at disk, in the way we already do with templates).
