### ISSUE TITLE
Html to Mediawiki - Linking webpages outside mediawiki 

### ISSUE THREAD

**Issue by castor-troy** [jgm/pandoc#2562]
I am not sure if this is the right place to ask, but I need help.

I am trying to convert html to mediawiki using pandoc. Now, let's say my wiki url format is http://site/w/test_page. I have several web pages outside the wiki, for eg http://site/test.htm. In my html content, I used < a href="/test.htm"> test page < /a>. When I use pandoc to convert this html to mediawiki, it emits [[/test.htm|test]], which my mediawiki recognizes as internal page. Can I instead get it to return [/site.htm test] ?

**Comment by jgm** [comment]
Sorry, no -- you'll need to use an absolute URL if you don't want it to be treated as an  internal page.
