### ISSUE TITLE
Allow unescaping the percent sign via %% for LaTeX output

### ISSUE THREAD

**Issue by zommuter** [jgm/pandoc#2564]
The problem: There is currently no way to use a LaTeX comment in a Markdown source, both an isolated `%` _and_ an escaped one `\%` are converted to the escaped version. Both variants have are sensible in their own way, but that leaves no (intuitive) way to comment out LaTeX commands in a way that _leaves_ them as LaTeX comments in the output, e.g.

    % \leftskip 15mm

would become

    \% \leftskip 15mm

and thus not only add a literal `%` to the output but also leave the command `\leftskip` intact.

The problem is that the Markdown reader already turns all possible means to typeset a percent sign (a literal `%`, an escaped one `\%`, a HTML-escaped `&#37;` one), thus the LaTeX writer has no chance of knowing what was intended.

It is clear that the HTML-escape `&#37;` is intended to become a `%` in the output and thus must be escaped in LaTeX, and since HTML has no special interpretation for a literal `%` sign, the same _should_ apply here. And for consistency, a backslash-escaped character should be output by whatever means necessary as well, so again escaping in LaTeX.

One solution could be a variable / command line parameter `unescape-percent`, that would leave a literal `%` unescaped. This would require the Markdown reader to store percent signs with the additional information about their escape-state _and_ the LaTeX writer to be aware of that.

A second solution, which I'd personally favour, would cause a doubled percent sign `%%` in the LaTeX writer input to be output as a (single) literal `%` comment, no matter their origin⁺. There doesn't appear to be much use of this, and one could still use `%\\%` to truly typeset it. And probably only a few lines of code around [this one](https://github.com/jgm/pandoc/blob/5c45a43399536e44d6a53db15e3344912412a32b/src/Text/Pandoc/Writers/LaTeX.hs#L268) would need to be touched.

A third method would be defining a global unescape character, but that sounds over-complicated...

---

⁺ Well, maybe inside inline code it should remain escaped, since it might break the `\texttt` it is wrapped in

**Comment by zommuter** [comment]
Of course one could then go on and let `%%` globally indicate a comment for the rest of this line and e.g. let the HTML-output of `text %% comment` become `text <!-- comment -->`...

**Comment by jgm** [comment]
AS of 5a9ca2617289d59e4de619a7746f04d0b9e70473 you can use

\begin{comment}
my comment
\end{comment}

Will that help?

+++ Tobias Kienzler [Nov 30 15 23:41 ]:

**Comment by zommuter** [comment]
It's the way I "solve" this currently, but that's quite some typing compared to simple percent signs when testing e.g. layout options.

**Comment by jandhau** [comment]
I recently came across the exact same problem and would second zommuter's suggestion.  I have a workaround, which is to mark comments as suggested with %% and then after running pandoc simply run  `perl -pi -e 's/\\%\\%/%/g;' file.tex` on the same file.

Maybe that helps someone in the future.
