### ISSUE TITLE
Beamer templates in current directory producing undefined control sequence error

### ISSUE THREAD

**Issue by arlobryer** [jgm/pandoc#2566]
The Beamer example from [the docs](http://pandoc.org/demos.html), everything works as expected and the example output is produced.

If I copy default beamer template to my current working directory and try:
`pandoc --template=default.beamer example.md -o example.pdf`

I get an `Undefined control sequence` error like:

```
! Undefined control sequence.
l.33 \AtBeginPart

pandoc: Error producing PDF from TeX source
```

I'm not sure if this is me doing something wrong, but I can't find anything about this behaviour or how to solve it.

**Comment by jgm** [comment]
Where aer you getting the default beamer template?  If
you're getting it from the github master branch, it may
presuppose changes to the pandoc code since the version
you have.

To get a version of the template that goes with your
pandoc version, do

    pandoc -D beamer > default.beamer.

+++ Arlo Bryer [Dec 01 15 06:42 ]:

**Comment by arlobryer** [comment]
Hi @jgm ,


I was using the template installed with Pandoc through brew which ends up at `/usr/local/Cellar/pandoc/1.15.0.6/share/x86_64-osx-ghc-7.10.1/pandoc-1.15.0.6/data/templates/default.beamer`.

Following your suggestion produces another error that I was also seeing yesterday (whilst playing around with things, although I don't recall how I got to it):

`pandoc -D beamer > default.beamer`
`pandoc --template=default.beamer example.md -o example.pdf`
```
! Undefined control sequence.
<recently read> \setbeamertemplate

l.2 \setbeamertemplate

pandoc: Error producing PDF from TeX source
```

**Comment by jgm** [comment]
You need to add `-t beamer` to your command line.

+++ Arlo Bryer [Dec 02 15 03:56 ]:

**Comment by arlobryer** [comment]
Ah, OK got it. Thanks for the help!
