### ISSUE TITLE
Text within TeX block macros exported to .docx file

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#2578]
Consider the following markdown content with a TeX block macro embedded within:

```markdown
# Chapter

The letter warned that:

\startletter
In the course of the last four months it has been made probable--through the work of Joliot in France as well as Fermi and Szilárd in America--that it may become possible to set up a nuclear chain reaction in a large mass of uranium, by which vast amounts of power and large quantities of new radium-like elements would be generated. Now it appears almost certain that this could be achieved in the immediate future.
\stopletter

The letter was signed by Einstein and posted back to Szilárd, who received it on August 9.
```

When converted to DOCX using `pandoc -s letter.md -o letter.docx`:

![letter](https://cloud.githubusercontent.com/assets/2131950/11610607/49b399c0-9b5d-11e5-8813-9d64fa38b54f.png)

When converted to ConTeXt using `pandoc -t context -s letter.md -o letter.tex`:

```tex
\starttext

\section[chapter]{Chapter}

The letter warned that:

\startletter
In the course of the last four months it has been made probable--through the work of Joliot in France as well as Fermi and Szilárd in America--that it may become possible to set up a nuclear chain reaction in a large mass of uranium, by which vast amounts of power and large quantities of new radium-like elements would be generated. Now it appears almost certain that this could be achieved in the immediate future.
\stopletter

The letter was signed by Einstein and posted back to Szilárd, who
received it on August 9.

\stoptext
```

This produces the desired ConTeXt code; however, the .docx file is missing the letter altogether.

How can custom TeX block macros be intermingled with markdown such that the block macros themselves are ignored by Pandoc, yet the content of the block macro makes it into .docx file? (Ideally without a filter.)

**Comment by jgm** [comment]
There is a request for an extension to allow markdown to be parsed in tex blocks here: #2453
This would have the desired effect, so I think this issue can be closed in favor of that one.

**Comment by DaveJarvis** [comment]
Duplicate of #2453.
