### ISSUE TITLE
Feature Request: Markdown for centered text

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#2579]
Fiction publishers have standard [manuscript formats](http://www.shunn.net/format/story.html) that include text centered on a page. While centered text, arguably, is a formatting instruction that could go against markdown [philosophy](http://daringfireball.net/projects/markdown/syntax#philosophy), there are some precedents for its inclusion in markdown:

* https://simplpost.com/markdown.html
* http://tedwise.com/markdown/
* http://stackoverflow.com/a/15370539/59087
* http://cl.ly/NpvK
* https://help.madmimi.com/how-do-i-center-or-justify-my-text/
* https://ca.godaddy.com/help/centering-or-justifying-text-15824

There are a number of elements that published manuscripts must have centered:

* Scene separators (i.e., centered hashmarks)
* Title
* Author byline
* Story ending demarcation (i.e., `THE END`) (see also [scriptwriting](http://fountain.io/syntax#section-centered))

Additionally, bloggers desire to center images, but have no easy option using markdown. (They resort to embedding HTML [`<div class="align-center">Centered text</div>`] in the markdown, which defeats the purpose of separating content from presentation--thereby decreasing the text readability, which goes against MD philosophy.)

I'd like to propose an option to suggest that an item be centered, regardless of output format:

    -> Centered Text <-

There is an alternative form, but it strikes me as more difficult to parse:

    > Centered Text <

## Output Formats

HTML:

```html
<div class="align-center">Centered Text</div>
```

ConTeXt:

```context
\startalignment[middle]Centered Text\stopalignment
```

DOCX:

```xml
<w:p>
  <w:pPr><w:pStyle w:val="Normal"/><w:jc w:val="center"/><w:rPr></w:rPr></w:pPr>
  <w:r><w:rPr></w:rPr><w:t>Centered Text</w:t></w:r>
</w:p>
```

**Comment by jgm** [comment]
Dup of #719
See also pandoc-discuss threads on this topic, from a while back.

**Comment by DaveJarvis** [comment]
Duplicate of #719.

**Comment by DaveJarvis** [comment]
See the topic [thread](https://groups.google.com/forum/#%21searchin/pandoc-discuss/center/pandoc-discuss/CFHQvVqsTBs/Fq6_Z-MBxNIJ).
