### ISSUE TITLE
Proper cross-references in reST

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#258]
From Marcin Wojdyr:

It would be useful if pandoc supported proper cross-references
in reST:

http://docutils.sourceforge.net/docs/user/rst/quickref.html#implicit-hyperlink-targets
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#implicit-hyperlink-targets

it would be better to use full titles rather than mangled, i.e.
`[link](#Header identifier)` instead of `[link](#header-identifier)`,
and change it only in HTML output.

**Comment by gsauthof** [comment]
Is this issue really fixed?

The example from the [docutils documentation](http://docutils.sourceforge.net/docs/user/rst/quickref.html#implicit-hyperlink-targets) doesn't work with pandoc 1.17.0.3:

    $ pandoc -f rst -t latex
    Titles are targets, too 
    ======================= 
    Implict references, like `Titles are 
    targets, too`_.
    Ctrl+D
    \section{Titles are targets, too}\label{titles-are-targets-too}
    
    Implict references, like Titles are 
    targets, too\_.
