### ISSUE TITLE
Font commands for ConTeXt

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#2580]
Re: http://wiki.contextgarden.net/Font_Switching

> These mnemonic font switches are pretty smart. You can either use them as font style switches inside a `{ group }`, or as a font changing command that takes an argument.

    This is {\bold bold} and so is \bold{this}. But this is not.

Re: http://wiki.contextgarden.net/Epub_Sample

    \definehighlight[emph][style=italic] % use \emph{something} instead of {\em something}

Usage of `{\em ...}` and `\emph{...}` create identical output. Using `\emph{...}` instead of `{\em ...}` allows for easier stylistic changes. Consider:

```tex
\starttext
\startblockquote
{\em Block Quote Emphasis Font}
\stopblockquote
\stoptext
```

The blockquote can be created using the following markdown:

```markdown
> _Block Quote Emphasis Font_
```

Using the `\emph{...}` command in this situation means that the emphasis font can be readily distinguished and changed independently of the regular blockquote font. Using `{\em ...}` makes changing the emphasized text trickier, technically.

If possible, please use `\emph{...}` and `\bold{...}` instead of their equivalents (`{\em ...}` and `{\bold ...}`). That is, the given markdown should produce:

```tex
\starttext
\startblockquote
\emph{Block Quote Emphasis Font}
\stopblockquote
\stoptext
```

If there are concerns about breaking existing documents, perhaps this could be a command-line switch when producing ConTeXt documents?

**Comment by jgm** [comment]
Sounds good to me.  Can you post a query on pandoc-discuss for other ConTeXt users, to make sure they agree that this would be a good change?

**Comment by ousia** [comment]
@DaveJarvis,

sorry, but I’m afraid I don’t see which is the gain here. I must be missing something.

With your proposal, double emphasis doesn’t seem to work:

``` tex
\setupbodyfontenvironment[default][em=italic]
\definehighlight[emph][style=italic]
\starttext
\startblockquote
\emph{Block Quote \emph{Emphasis} Font}
\stopblockquote
\startblockquote
{\em Block Quote {\em Emphasis} Font}
\stopblockquote
\stoptext
```

And `\em` does also apply automatic italic correction.

I don’t understand why changing the emphasized font in the blockquote is trickier.

As far as I get it, either you change the emphasis command for the whole document (see above), or you change the font for the blockquote (such as in `\setupdelimitedtext[blockquote][style=bold]`).

**Comment by DaveJarvis** [comment]
Setting the emphasis font exclusively within a blockquote can be accomplished without changing the entire blockquote font:

```tex
\setupdelimitedtext[blockquote][
  before={\setupbodyfontenvironment[default][em=mono]},
]
```

I was under the false impression that:

1. Changing the font would be easier with `\emph{...}` than `{\em ...}`.
1. In ConTeXt, `\emph{...}` was preferred.

That double-emphasis doesn't work is a good reason to abandon this request.
