### ISSUE TITLE
DOCX heading number format

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#2582]
# Replicate

First, create a new template for .docx files:

``` bash
echo "# Chapter" > ref.md
pandoc -s -t docx -o ref.docx ref.md
```

Next:
1. Open `ref.docx` in LibreOffice 4 or 5
2. Select **More Numbering** from the numbered list drop-down to open the Bullets and Numbering dialog
   ![more-numbering](https://cloud.githubusercontent.com/assets/2131950/11647198/3b17a8f2-9d1a-11e5-867c-edef254fd2ff.png)
3. Set **Before** to: `CHAPTER` (there's an extra space at the end)
4. Set **After** to: `--` (there's an extra space at the beginning)
   ![bullets-numbering](https://cloud.githubusercontent.com/assets/2131950/11647227/75a3967a-9d1a-11e5-8648-601c65ef7af6.png)
5. Click **OK** to accept the changes
6. Save the document (`CTRL+s`)
7. Click **Use Microsoft Word 2007/2010/2013 XML Format**, if the confirmation dialog appears

This should produce a document such as:

```
CHAPTER 1 -- Chapter
```

Next, use the template and open the result:

``` bash
pandoc -s -t docx --reference-docx=ref.docx  -o final.docx ref.md 
libreoffice final.docx
```
# Expected Results

The `CHAPTER 1 --` prefix to the chapter title should be copied from the reference document.
# Actual Results

The chapter prefix is not used.
# Additional Details

Up to three files are involved with this numbering format for the header (I haven't investigated to see if any are optional; my guess is that header1.xml and numbering.xml aren't being copied by Pandoc):
- header1.xml
- numbering.xml
- styles.xml

If possible, these files should be copied over from the reference document.
# Work Around

Here's a shell script that works around a few issues with converting Markdown to DOCX via Pandoc, which includes a fix for the numbering style:

``` bash
#!/bin/bash

# Builds the manuscript based on the reference document style.

# Filename to update
MANUSCRIPT=convergence.docx
REFERENCE_DIR=docx

chmod 644 $MANUSCRIPT

# Use the reference document (template) to create the DOCX version.
pandoc \
  --filter filter.php \
  --reference-docx=$REFERENCE_DIR/reference.docx \
  -o $MANUSCRIPT \
  -s output/*vars

WORKING_DIR=/tmp/replacement/
DOC_DIR=$WORKING_DIR/word

rm -rf $WORKING_DIR
mkdir -p $WORKING_DIR

# Modify the DOCX file directly.
unzip $MANUSCRIPT -d $WORKING_DIR

# Replace the horizontal rule with a centered hashmark.
sed -e 's!<w:p><w:r><w:pict><v:rect style="width:0;height:1.5pt" o:hralign="center" o:hrstd="t" o:hr="t" /></w:pict></w:r></w:p>!<w:p><w:pPr><w:pStyle w:val="Normal"/><w:jc w:val="center"/><w:rPr></w:rPr></w:pPr><w:r><w:rPr></w:rPr><w:t>\#</w:t></w:r></w:p>!g' $DOC_DIR/document.xml > $DOC_DIR/document.xml.tmp && mv $DOC_DIR/document.xml.tmp $DOC_DIR/document.xml

# Keep the chapter heading style (to include the chapter number)
cp $REFERENCE_DIR/*xml $DOC_DIR

# Repack the document.
pushd $WORKING_DIR
zip -9 -r /tmp/$MANUSCRIPT .
popd
rm -rf $WORKING_DIR

# Replace the existing manuscript with the revised version.
mv /tmp/$MANUSCRIPT .
```

To use the script, all three aforementioned files must be in a subdirectory named `docx`.

**Comment by agusmba** [comment]
This might have something to do with using LibreOffice to edit word's reference doc, or the issue was fixed.

I reproduced the steps (but using word to modify the style) and it worked as expected:

![modifyheading1](https://user-images.githubusercontent.com/3104020/32298602-05ce7092-bf53-11e7-94ad-d9be12e4a979.PNG)
![final](https://user-images.githubusercontent.com/3104020/32298637-1eaa536a-bf53-11e7-8e77-677b3e971fa5.PNG)

**Comment by jgm** [comment]
Closing then!
