### ISSUE TITLE
Modified AST only partially iterated

### ISSUE THREAD

**Issue by steindani** [jgm/pandoc#2584]
I've written the pandoc-include (﻿https://github.com/steindani/pandoc-include) filter based on the scripting tutorial. Using pandoc-include one's able to include markdown files —or a bunch of files if needed— recursively.

1. The following `CodeBlock` is read line-by-line,
2. the referenced file (if exists) is parsed using `readMarkdown`,
3. the resulting `Pandoc` block is stripped from metadata,
4. and the array of `Block`s is returned replacing the `CodeBlock`.

```markdown
﻿```include
﻿chapter1.md
﻿chapter2.md
﻿#dontinclude.md
﻿```
```

## The Problem

This is working nicely, but only for two-level-deep nesting. If there is a 4 level include chain, the content of the last one is not parsed, but included plain-text.

```
input.md
    ↓
alpha.md
    ↓
beta.md
    ↓
gamma.md
```

Is there some limitation that could result in this phenomenon?

## Minimal Working Example
Please take a look at the input provided in the [test folder of the repository](https://github.com/steindani/pandoc-include/tree/master/test).

After checking out the repository (and installing the filter `cabal update && cabal install pandoc-include`):
```bash
cd test
pandoc --from markdown --to markdown --filter pandoc-include input.md
```

### Expected result:
Instead of

```markdown
﻿``` {.include}
﻿gamma.md
﻿```
```

there should be just the content of `gamma.md`: `Gamma.`

**Comment by jgm** [comment]
If you want it to be nestable, you'll need to run
doInclude recursively on the new Blocks.
Something like (untested):

doInclude (CodeBlock (_, classes, _) list)
  | "include" `elem` classes = do
      let toProcess = getProcessableFileList list
      newblocks <- processFiles =<< toProcess
      concat `fmap` mapM doInclude newblocks

A couple more issues with this filter:

1.  You use default reader options (readMarkdown def content).
This means that the included files may be
processed with different options than the outer one.

2.  References and footnotes will be handled separately
for each file.  So you can't have a link definition in one
file that is referred to in another.  This might be a
feature, depending on your interests.

I would think that for markdown includes, it would make
more sense to preprocess the markdown source rather than
using a filter.

**Comment by steindani** [comment]
@jgm I see, thank you.

But how is it possible that the second level is processed? If `input.md` is given as the source, the referenced `alpha.md` is parsed and included *and* the same is done for `beta.md` (referenced in `alpha.md`)? Only the next level is ignored.

Also thank you for the notes, now I clearly see these problems.

1. Is it possible for the filter to get the parent process reader options?
2. I'll write a note about this in the README. This filter is mainly for plain markdown sources, but the problem might be solved using an indirection: if first transformed from markdown to markdown using the filter, then translating the output using pandoc again. Is this solution appropriate?

**Comment by jgm** [comment]
Hm. My thinking on the problem may be wrong.  The `ToJSONFilter` instance for `a -> IO [a]` uses `bottomUpM (fmap concat . mapM f)`.  This may actually recurse into the new Blocks.  I'd have to do some looking/experimenting to get clearer on this.

For a more straightforward and faster filter, you might write a function `Block -> IO Block` that returns a `Div` containing the new blocks.  (Then, as I suggested, run the function recursively on the new blocks.)

There's no way to get the parent process reader options.

You could use this to go md -> md, but that wouldn't really address the issue I was raising.  Example:  suppose alpha.md has an include of beta.md, and the link reference `[foo]: url`, while beta.md has a link `[foo]`.

I think the best way to do markdown includes is not through a filter, but by preprocessing the document before parsing.
