### ISSUE TITLE
LaTeX Writer: Omit line break following block quotations, lists

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2588]
The LaTeX writer places an extra space after block quotations and lists, meaning that the text following these is treated as a new paragraph rather than part of the preceding one. This is not visible with the setup of the default template, but it becomes an issue if one enables indentation. While it is possible (if relatively unusual) to have a line following a block quotation that is intended as an entirely new paragraph, I do not know how one could make a distinction between the two approaches. The docx writer sets a special 'First Paragraph' style, and it would be consistent to omit the line break for LaTeX.

For example ([PDF output](https://github.com/jgm/pandoc/files/60329/test.pdf)):

```latex
\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, per ad mentitum suscipit, elitr vituperata persequeris an cum. Oblique constituam vituperatoribus ius eu, vis ne invidunt imperdiet. Duo in solum epicuri oporteat, malis democritum disputando sit in, at sea dico tacimates.

\begin{quote}
Mea eius ridens eloquentiam te. Tale audire delenit sit ei, no quis case nullam nec, eum dolore gubergren id. Causae perpetua instructior at has, everti graecis repudiandae cu cum, cu nostrud laoreet nec. Vim nisl reque zril et.
\end{quote}

Molestiae rationibus nec no, tale nihil ut nam, ex mea probatus constituto. Oblique nominati tincidunt usu ea, at his sumo indoctum petentium. Viris nostro molestiae no cum, eu mel movet theophrastus, id prima pertinax sit. Sed etiam lobortis eu. Prodesset gloriatur liberavisse eos ea. An dicta discere ius, ei iuvaret ancillae fastidii vis.
\begin{quote}
Mel iuvaret voluptua officiis cu. In suas laudem tibique vis, dicit albucius explicari an pro, vix ut facilis persequeris. Veri theophrastus et eum, senserit petentium prodesset nam at. Ridens inciderint mel id, dico fuisset oportere his te.
\end{quote}
Duo dico expetenda et, nihil laudem vix et. Quis eros an mel. At sit modo placerat pertinacia, alterum menandri te sed. Mea ea soleat adolescens. Augue sonet te qui, at sea singulis inciderint. Et legere liberavisse mea, et dolor dolorum habemus mea. Sea ad nominavi intellegat, an ius referrentur necessitatibus, urbanitas similique ne nec.

\end{document}
```

**Comment by jgm** [comment]
This is a structural problem.  A Para contains a list of Inline elements, and BlockQuote and Lists are Block elements, so they can't be put inside a Para in the internal document representation.  This mirrors the way these elements work in HTML and many other formats.  In LaTeX one can distinguish between the case where the block quote is part of the paragraph and the case where it follows the paragraph, but you can't make this distinction in Pandoc or many other output formats.  There's certainly no way to mark the distinction in Markdown. (This is one reason the default is for no paragraph indentation.)

For LaTeX output you could start the paragraph after the blockquote or list with `\noindent`.  If you need to support other output formats, you could try putting the whole thing (paragraph + blockquote + following paragraph) inside a special Div, and use CSS to adjust indentation inside it.  I'm not sure I see a better solution.

**Comment by adunning** [comment]
It really is a problem. If only HTML allowed `<blockquote>` to be nested in `<p>`!
