### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#2589]
![screen shot 2015-12-13 at 5 11 51 pm](https://cloud.githubusercontent.com/assets/3044/11770829/d5f4958c-a1bc-11e5-9133-93ea01fb3c5e.png)

**Comment by jgm** [comment]
Line 536 of the ICML writer uses pathSeparator - could it just as well use `/`?
Then the test output would not vary with OS.
The pathSeparator was added in 9deb335c.  I think it can be removed safely, or we can use Posix.pathSeparator as we do in Shared.

**Comment by jgm** [comment]
@mb21 this was your code, according to the commit message.  Any ideas?
According to [this](http://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files), one should never get something like `file://./lalune.jpg`, let alone `file://.\lalune.jpg`.
Do we need the `file://`?  If so, should we get the absolute path to the file and insert that?  Finally, can we use posix separators (`/`)?

**Comment by jgm** [comment]
Interestingly, in the ICML spec they have examples like `"file:D:/images/pumpkin.jpg"`
without the `//`.  Looks like forward slashes are fine.

**Comment by mb21** [comment]
It was `"file:" ++ src` before 9deb335ca5fbf9f1db0cd1d046d2b59a9a5a55fe, where I changed it to `"file://." ++ pathSeparator : src` and if I remember correctly, the reason was that relative paths didn't work before. This is not well documented, but seems to be [the only way in IDML](https://twitter.com/sachaheck/status/301616198112669696), even if it's not RFC 3986 conform.

btw, you can get a [free trial of InDesign or InCopy](http://www.adobe.com/downloads.html)...

**Comment by mb21** [comment]
But maybe we should use `file:` for absolute paths and `"file://./" ++ src` for relative ones (it's possible that this would work for Windows as well, I don't have a Windows install handy..)

**Comment by mb21** [comment]
Actually I just tried `"file:foo.jpg"` and  `"file:/Users/myuser/foo.jpg"` on InCopy CS6 and InDesign CC 2015 on Mac OS X and both worked. So not quite sure what's changed, but you can disregard what I said before...

**Comment by jgm** [comment]
OK, thanks - so what I have now in head is okay, then?

+++ Mauro Bieg [Dec 14 15 07:01 ]:

**Comment by mb21** [comment]
yes, at least on a Mac it works, but from the example you posted (`"file:D:/images/pumpkin.jpg"`), I'm fairly confident it works on Windows as well.

**Comment by jgm** [comment]
Great.

+++ Mauro Bieg [Dec 14 15 08:34 ]:
