### ISSUE TITLE
Generate lines for tables automatically or with new syntax

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#259]
Google Issue #56
Reported by alex.ev...@gmail.com, Feb 12, 2008

Perhaps a commandline option to pass to generate /hlines and /vlines for 
an entire table in the current markdown format, or a way of writing them 
by hand in markdown, i.e.

```
-------------
|Truth table|
-------------
| A | B | f |
-------------
| 0 | 0 | 0 |
-------------
| 0 | 1 | 0 |
-------------
```

The structure above looks pretty trivial to parse into `/hlines` and `/vlines` 
(just replace each pipe with a `/vline`, and each dividing `---` becomes a `\
hline`). Being able to do /multicolumn would be really great - but that 
sounds considerably harder to parse.

**Comment by link2xt** [comment]
Related issue about vertical lines in LaTeX output: #922

**Comment by tarleb** [comment]
Closing in favor of the more specific issues #922, #6317, and #6344.
