### ISSUE TITLE
$ works in -f latex but not works in -f markdown_github+tex_math_dollars

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#2596]
The following is raw latex text.
```
test$T = \lbrace (x_1,y_1),(x_2,y_2), \cdots ,(x_N,y_N) \rbrace $,$y_i \in \lbrace c_1,c_2, \cdots ,c_K \rbrace $,
```
pandoc -f latex -t html --mathjax
```
<p>test<span class="math inline">\(T = \lbrace (x_1,y_1),(x_2,y_2), \cdots ,(x_N,y_N) \rbrace \)</span>,<span class="math inline">\(y_i \in \lbrace c_1,c_2, \cdots ,c_K \rbrace \)</span>,</p>
```
pandoc -f markdown+tex_math_dollars -t html --mathjax
```
<p>test$T = (x_1,y_1),(x_2,y_2), ,(x_N,y_N) <span class="math inline">\(,\)</span>y_i c_1,c_2, ,c_K $,</p>
```
The first $ is not be parsed in `-f markdown+tex_math_dollars`.

**Comment by jgm** [comment]
I don't think this is a bug.  Remember, unlike in LaTeX, `$`
in Markdown is often just a plain `$` (dollar sign).  So the
Markdown parser uses some heuristics to determine when we
have a dollar sign and when we have LaTeX math.

Please read the documentation at
http://pandoc.org/README.html#math
which explains clearly why you're seeing what you're seeing.

**Comment by cnblogs-dudu** [comment]
If Use `pandoc -f markdown_github -t html`,  the LaTeX without `<span class="math inline">` is successfuly parsed by mathjax . But this will cause another LaTeX issue.

See the following LaTeX in markdown.
```
- ... $\alpha$ ... $0={\alpha}_0<{\alpha}_1<{\alpha}_2<\cdots<{\alpha}_n$,... $[\alpha_{i},{\alpha}_{i+1})$ ... $T_i$
```
It produces the following output.
```html
<ul>
<li>... $\alpha$ ... $0={\alpha}_0&lt;{\alpha}_1&lt;{\alpha}<em>2&lt;\cdots&lt;{\alpha}<em>n$,... $[\alpha</em>{i},{\alpha}</em>{i+1})$ ... $T_i$</li>
</ul>
```
The \<em\> tags results in the LaTex fails to be parsed by mathjax. `+tex_math_dollars` is for fixing this issue.

How to safely use LaTeX in markdown?

**Comment by jgm** [comment]
Use the --mathjax flag if you want output that will work
well with mathjax.

+++ Yong Du [Dec 19 15 00:31 ]:

**Comment by cnblogs-dudu** [comment]
Removing the space before $ fixes it.
```
test$T = \lbrace (x_1,y_1),(x_2,y_2), \cdots ,(x_N,y_N) \rbrace$,$y_i \in \lbrace c_1,c_2, \cdots ,c_K \rbrace$,
```
