### ISSUE TITLE
language specification for LaTeX is broken for Czech language

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#2597]
I have discovered using `cs-CZ` did not work for `lang` for me. I think I have found the culprit on line [1185](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L1185) in `LaTeX.hs`:

````{.hs}
     fromIso "cz" = "czech"
````

This is wrong. The ISO 639-1 *language* code is "cs".

(It is "CZ" for the country code.)

**Comment by ousia** [comment]
@wilx and @jgm, sorry, [it was my fault](https://github.com/jgm/pandoc/issues/1614#issuecomment-55649901). I didn’t know that language and country codes were different.
