### ISSUE TITLE
Level 1 headings now convert to \chapter{} when converting from .md to .tex under memoir class template

### ISSUE THREAD

**Issue by breschke** [jgm/pandoc#2599]
I upgraded from pandoc 1.15.0.6 to pandoc 1.15.2. I write .md files and create .pdfs using a custom latex template that uses the memoir class. Previously, level 1 headings (#) converted to sections, but now they convert to chapters. I would prefer the previous behavior (level 1 headings = sections) since I rarely write book/dissertation-long documents. More importantly, I also generate html versions of the same .md documents, and I don't want to give up using h1 level headings per se. Best would be an option to specify which level is the starting point (chapter or section). If such an option exists, please advise.

**Comment by jgm** [comment]
There was no change in pandoc.  Pandoc has always made level
1 headings chapters when the memoir class (or book, report,
scrreprt, scrbook) is used.

Have you looked in the manual?  `--base-header-level=2` is
what you want.

+++ Brian Reschke [Dec 22 15 16:13 ]:
