### ISSUE TITLE
Using ePUB metadata block in PDF

### ISSUE THREAD

**Issue by Quintasan** [jgm/pandoc#2601]
I'm trying to generate both ePUB and PDF out of Markdown files. Using the metadata block as [outlined](http://pandoc.org/README.html#epub-metadata) in the documentation works when generating ePUB files. But using the same format with the PDF generator results in the title being set to `true` and the author field being empty. I tried modifying the default LaTeX template to be similar to the ePUBv3 template but it didn't really work. Is it somehow possible to keep the YAML format intact and still get it produce proper title page in PDF?

**Comment by jgm** [comment]
Yes, it's possible, but you'd need to customize your latex
template a bit so that the variables match what the epub
writer expects.

+++ Michał Zając [Dec 23 15 15:47 ]:

**Comment by Quintasan** [comment]
@jgm I can't really do comparisons in the if's, right? Setting the proper author field is going to be problematic since I can't just iterate over all creators.

**Comment by jgm** [comment]
+++ Micha? Zaj?c [Dec 23 15 16:06 ]:
>   [1]@jgm I can't really do comparisons in the if's, right? Setting the
>   proper author field is going to be problematic since I can't just
>   iterate over all creators.

Hm, that's true.  I suppose you could write a pandoc filter
that converts between epub style and regular style author
metadata.  Another (really kludgy) solution would be to
create a latex macro that takes two arguments, and  acts
as a no-op unless the first argument is 'creator'.

**Comment by gitkrax** [comment]
I believe I have a working example of what you're trying to accomplish here: https://github.com/gitkrax/ebook-template

**Comment by gitkrax** [comment]
I'll add to this issue. I think that the general case works: I can use a metadata.yaml-file to be used both in pdf and epub conversions. (see previous comment for a working example)

However, there is a more specific case where this fails: if I convert a markdown document first to a tex-document and then convert that to a pdf with the file metadata.yaml added in this second phase, the metadata is not read as metadata, but is instead added as regular text. It is probably read as a tex-file, so if I read it last, it will be the last text in the file.

Works:

```
pandoc text.md metadata.yaml -o text.pdf
```

Doesn't work:

```
pandoc text.md -o text.tex
pandoc text.tex metadata.yaml -o text.pdf
```

**Comment by jgm** [comment]
+++ Jonne Arjoranta [Jan 25 16 00:29 ]:
>   However, there is a more specific case where this fails: if I convert a
>   markdown document first to a tex-document and then convert that to a
>   pdf with the file metadata.yaml added in this second phase, the
>   metadata is not read as metadata, but is instead added as regular text.
>   It is probably read as a tex-file, so if I read it last, it will be the
>   last text in the file.

YAML metadata is only supported as a Markdown extension.
So, if you're reading latex, it won't work.  Note that the
files you pass to pandoc are simply concatenated and
interpreted in the specified  format; pandoc doesn't treat
them separately (and e.g. read the YAML as pandoc markdown
and the latex as latex).

**Comment by gitkrax** [comment]
@jgm That explains why I'm having a hard time getting it to work. Thanks for the clarification.

@Quintasan can try my approach and see if that solves his problem.
