### ISSUE TITLE
mediawiki lists in tables

### ISSUE THREAD

**Issue by stm2** [jgm/pandoc#2606]
The mediawiki reader treats a \* at the beginning of a cell as a list, but this should only be the case if the \* is at the start of a _line_. For example this

```
pandoc -f mediawiki -t html << EOF
{|
| * hello
|}
```

produces

```
<table>
<tbody>
<tr class="odd">
<td align="left"><ul>
<li>hello</li>
</ul></td>
</tr>
</tbody>
</table>
```

when it should produce

```
<table>
<tbody>
<tr class="odd">
<td align="left"><p>hello</p></td></tr>
</tbody>
</table>
```

However,

```
{|
|
* hello
|}
```

_should_ produce a list inside a table, but

```
{|
|
 * hello
|}
```

should not. See https://www.mediawiki.org/w/index.php?title=Help:Lists for examples.

**Comment by stm2** [comment]
This is still an issue in 1.16.

It concerns the mediawiki *reader*.

**Comment by jgm** [comment]
Sorry, it was closed in error.
