### ISSUE TITLE
mediawiki reader: markup should be active in tt, code, and simple preformatted text

### ISSUE THREAD

**Issue by stm2** [jgm/pandoc#2607]
```
pandoc -f mediawiki -t html << EOF
<code>'''hello''' <br />world</code>
EOF
```
renders as
```
<p><code>'''hello''' &lt;br /&gt;world</code></p>
```
but should produce
```
<p><code><strong>hello</strong> <br />
world</code></p>
```

Character formatting is only inactive inside `<pre>` tags, see https://www.mediawiki.org/wiki/Help:Formatting

**Comment by jgm** [comment]
Pandoc's Code and CodeBlock constructors only take a string as value, so you can't actually embed formatted text in them.  We could work around this by turning

    <code>'''hello''' <br />world</code>

into

    [Strong [Code "hello"], Code " ", LineBreak, Code " world"]

but this is less straightforward to implement.
