### ISSUE TITLE
Reformatting tables can produce HTML instead of Markdown

### ISSUE THREAD

**Issue by mike-ward** [jgm/pandoc#2608]
`table.md` contains:

```
| Field                                                    |  Maximum|
|----------------------------------------------------------|--------:|
| The quick brown fox jumped over the lazy dog a a a a a d |    65535|
| A                                                        |    65535|
| A                                                        |      255|
| A                                                        |      255|
| A                                                        |        1|
```

When processed with

`pandoc -f markdown_github -t markdown_github table.md`

Produces the the indentical output as expected. 

But add a few more characters to the second row,

```
| Field                                                    |  Maximum|
|----------------------------------------------------------|--------:|
| The quick brown fox jumped over the lazy dog a a a a a d a few more |    65535|
| A                                                        |    65535|
| A                                                        |      255|
| A                                                        |      255|
| A                                                        |        1|
```

and the outout becomes HTML markup

```
<table style="width:96%;">
<colgroup>
<col width="81%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Field</th>
<th align="right">Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">The quick brown fox jumped over the lazy dog a a a a a d a few more</td>
<td align="right">65535</td>
</tr>
<tr class="even">
<td align="left">A</td>
<td align="right">65535</td>
</tr>
<tr class="odd">
<td align="left">A</td>
<td align="right">255</td>
</tr>
<tr class="even">
<td align="left">A</td>
<td align="right">255</td>
</tr>
<tr class="odd">
<td align="left">A</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
```

**Comment by jgm** [comment]
If you have a long pipe table (with a line longer than the column width), pandoc will parse it as a table with column widths.  See the difference:
```
%  pandoc -t native
Table 1

| Field                                                    |  Maximum|
|----------------------------------------------------------|--------:|
| The quick brown fox jumped over the lazy dog a a a a a d |    65535|

Table 2

| Field                                                    |  Maximum|
|----------------------------------------------------------|--------:|
| The quick brown fox jumped over the lazy dog a a a a a d a few more |           12341234123|
^D
[Para [Str "Table",Space,Str "1"]
,Table [] [AlignDefault,AlignRight] [0.0,0.0]
 [[Plain [Str "Field"]]
 ,[Plain [Str "Maximum"]]]
 [[[Plain [Str "The",Space,Str "quick",Space,Str "brown",Space,Str "fox",Space,Str "jumped",Space,Str "over",Space,Str "the",Space,Str "lazy",Space,Str "dog",Space,Str "a",Space,Str "a",Space,Str "a",Space,Str "a",Space,Str "a",Space,Str "d"]]
  ,[Plain [Str "65535"]]]]
,Para [Str "Table",Space,Str "2"]
,Table [] [AlignDefault,AlignRight] [0.8194444444444444,0.1388888888888889]
 [[Plain [Str "Field"]]
 ,[Plain [Str "Maximum"]]]
 [[[Plain [Str "The",Space,Str "quick",Space,Str "brown",Space,Str "fox",Space,Str "jumped",Space,Str "over",Space,Str "the",Space,Str "lazy",Space,Str "dog",Space,Str "a",Space,Str "a",Space,Str "a",Space,Str "a",Space,Str "a",Space,Str "d",Space,Str "a",Space,Str "few",Space,Str "more"]]
  ,[Plain [Str "12341234123"]]]]]
```
In the first case you have
```,Table [] [AlignDefault,AlignRight] [0.0,0.0]```
which has widths of 0, indicating a "simple table" with no width information.
In the second you have
```,Table [] [AlignDefault,AlignRight] [0.8194444444444444,0.1388888888888889]```
with relative column widths (82% and 14%) -- these are calculated from the relative sizes of the separator bars, relative to the column width.

When the markdown writer gets this, it sees "I've got a table with relative column widths."  There's no native syntax for that with pipe tables (and github doesn't support the special relative column width behavior that pandoc does), so it uses HTML to make sure no information is lost.

Perhaps it would be worth changing this so that, if pipe tables are the only supported markdown table format, the column width information is just ignored.

**Comment by mike-ward** [comment]
> If you have a long pipe table (with a line longer than the column width), pandoc will parse it as a table with column widths. See the difference:

Did you mean, "longer than the table width"?  Or is it longer than the current column plus adjacent column?

I would favor your proposed solution of changing the current behavior when only pipe tables are specified.

**Comment by jgm** [comment]
+++ Mike Ward [Jan 05 16 12:24 ]:
>     If you have a long pipe table (with a line longer than the column
>     width), pandoc will parse it as a table with column widths. See the
>     difference:
>
>   Did you mean, "longer than the table width"? Or is it longer than the
>   current column plus adjacent column?

Longer than the column width (default 80, but can be set
with --columns).

>   I would favor your proposed solution of changing the current behavior
>   when only pipe tables are specified.

**Comment by tbussmann** [comment]
> Perhaps it would be worth changing this so that, if pipe tables are the only supported markdown table format, the column width information is just ignored.

I would support such an change! That should be somewhere in the following code block, I suppose?https://github.com/jgm/pandoc/blob/5085fe605a84a047598dfdcc9dfe8e98e745c630/src/Text/Pandoc/Writers/Markdown.hs#L605-L641

In the meantime, the Filter given in https://github.com/jgm/pandoc/issues/4497#issuecomment-540757707 should work as an workaround.
