### ISSUE TITLE
Syntax for specifying image size

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#261]
Googlecode Issue #29

There is currently no way to specify the size of an image.
For some ideas, see http://code.google.com/p/pandoc/wiki/ImageSizes.

**Comment by Jmuccigr** [comment]
Just bumping up against this problem today and wondering how far an implementation is?

Thanks.

**Comment by jgm** [comment]
+++ John Muccigrosso [May 11 15 10:33 ]:
>   Just bumping up against this problem today and wondering how far an
>   implementation is?

I have an implementation on a branch in this repository, but
it's not planned for the next release (1.14).  We'll
probably have this in the release after; it's a big breaking
change.

**Comment by Dashed** [comment]
@jgm Is it this branch? https://github.com/jgm/pandoc/commits/new-image-attributes

**Comment by jgm** [comment]
Yes that's it.

+++ Alberto Leal [May 11 15 18:47 ]:
>@jgm Is it this branch? https://github.com/jgm/pandoc/commits/new-image-attributes

**Comment by frumbert** [comment]
Also looking for this change; I'm using the windows binary. It's pretty similar to the format I already use with my custom parser (e.g. ![image caption](image.jpg {width: "500px"}) - this format just pushes the attrib map outside rather than inside the link grouping. Also in my implementation if the output format is HTML5, any custom "unknown" attributes are prefixed with "data-", so that it maintains as much of the input document as possible - such that {width: "500px", id: foo, cake: "lie"} becomes width="500px" id="foo" data-cake="lie".

I also had it [attrib map] implemented on standard hyperlinks, is that part of this change/branch?

**Comment by RobTrew** [comment]
[pandoc.org/installing.html]() suggests [for Windows | OS X] that
> There is a package installer at pandoc’s [download](https://github.com/jgm/pandoc/releases/tag/1.14.0.3) page

I can't (2015-06-15) see installers at [https://github.com/jgm/pandoc/releases/tag/1.14.0.3]() ...

Should perhaps I be looking elsewhere in space, or in time ?

**Comment by nkalvi** [comment]
https://github.com/jgm/pandoc/releases

A bit inconvenient - hopefully fixed soon :smile:

**Comment by magnis** [comment]
At first I thought this was a problem with Pandoc becaused I resized images and all it did was make the images look worst in the PDF (created from a markdown doc). However, as I was reading through here, I saw a mention of using imagemagick to change the DPI. I used Irfanview, went to the image menu and selected Information. I made the DPI extremely high (by multiplying by 10), clicked the 'change' button and noted the 'Print Size' down below. Pandoc will use the print size as dictated by the image DPI. Worked great.

**Comment by KurtPfeifle** [comment]
Good it worked for you!

But be aware...

> *At first I thought this was a problem with Pandoc becaused I resized images and all it did was make the images look worst in the PDF (created from a markdown doc). However, as I was reading through here, I saw a mention of using imagemagick to change the DPI. I used Irfanview, went to the image menu and selected Information. I made the DPI extremely high (by multiplying by 10), clicked the 'change' button and noted the 'Print Size' down below. Pandoc will use the print size as dictated by the image DPI.*

No. It's not ***Pandoc*** which makes use and applies the DPI settings to the output.

Most likely, you produced a PDF? In that case it was the LaTeX PDF generating engine which read the DPI metadata from the image and applied it when producing the PDF. Pandoc does not know anything about that!

Also, you results may change if you change in between the different `--latex-engine=pdflatex|lualatex|xelatex` options.

Lastly, it will not work for other output formats (as far as I'm aware, none of these changes its behavior depending on the DPI setting of the image). You ***are*** aware that this setting doesn't change the actual pixel data, but is only a setting in a metadata field of the image, which can be read and reported to you by a tool like `exiftool`, right?   
 
> *Worked great.*

Don't rely on it. Don't assume it will stay the same over releases (of LaTeX, `xelatex`, `pdflatex`, `lualatex`).

**Comment by jgm** [comment]
+++ Kurt Pfeifle [Jun 25 15 17:21 ]:
>   Good it worked for you!
>
>   But be aware...
>
>     At first I thought this was a problem with Pandoc becaused I resized
>     images and all it did was make the images look worst in the PDF
>     (created from a markdown doc). However, as I was reading through
>     here, I saw a mention of using imagemagick to change the DPI. I used
>     Irfanview, went to the image menu and selected Information. I made
>     the DPI extremely high (by multiplying by 10), clicked the 'change'
>     button and noted the 'Print Size' down below. Pandoc will use the
>     print size as dictated by the image DPI.
>
>   No. It's not Pandoc which makes use and applies the DPI settings to the
>   output.
>
>   Most likely, you produced a PDF? In that case it was the LaTeX PDF
>   generating engine which read the DPI metadata from the image and
>   applied it when producing the PDF. Pandoc does not know anything about
>   that!

Actually, pandoc *does* check the DPI information embedded
in an image, and uses this to figure out how to size images
in some output formats.

**Comment by magnis** [comment]
Yes, you are absolutely correct, Kurt.
I am using MiKTeX (default config) with Pandoc on Windows 8. 
Here is the line I use to make the conversion:

```
pandoc -o "example.pdf" -S -s --toc "example.md" 
```
Also, the same adjustment works great when creating a docx file.

However, and this may be where you are leading, when I created an html file, the icons were indeed blown back up very large. So, I guess I could understand if you want to force icon sizes for generated web-based documentation.

Note: I mostly using Pandoc to create polished docs for documentation out of markdown.

**Comment by KurtPfeifle** [comment]
On Fri, Jun 26, 2015 at 8:17 PM, John MacFarlane <notifications@github.com>
wrote:

> +++ Kurt Pfeifle [Jun 25 15 17:21 ]:
> > Good it worked for you!
> >
> > But be aware...
> >
> > At first I thought this was a problem with Pandoc becaused I resized
> > images and all it did was make the images look worst in the PDF
> > (created from a markdown doc). However, as I was reading through
> > here, I saw a mention of using imagemagick to change the DPI. I used
> > Irfanview, went to the image menu and selected Information. I made
> > the DPI extremely high (by multiplying by 10), clicked the 'change'
> > button and noted the 'Print Size' down below. Pandoc will use the
> > print size as dictated by the image DPI.
> >
> > No. It's not Pandoc which makes use and applies the DPI settings to the
> > output.
> >
> > Most likely, you produced a PDF? In that case it was the LaTeX PDF
> > generating engine which read the DPI metadata from the image and
> > applied it when producing the PDF. Pandoc does not know anything about
> > that!
>
> Actually, pandoc *does* check the DPI information embedded
> in an image, and uses this to figure out how to size images
> in some output formats.
>

Ah! Thanks for the info!

Is it documented somewhere, which list of output formats this applies to?!

@Jason: sorry for my potentially misleading statements then.

**Comment by jgm** [comment]
+++ Kurt Pfeifle [Jun 26 15 12:19 ]:
>   Ah! Thanks for the info!
>   Is it documented somewhere, which list of output formats this applies
>   to?!

ODT, Docx, RTF (since these formats require specification of
a size in non-pixel dimensions).

**Comment by gantech** [comment]
Sorry for the noob comment. Still in progress right?

**Comment by linquize** [comment]
ping

**Comment by jgm** [comment]
Still in progress, there's a PR that adds this.
I will probably merge it before long, but since
it is a breaking change with pandoc-types, I may
do another release in the 1.15 series first.

+++ gantech [Aug 14 15 05:57 ]:

**Comment by 01AutoMonkey** [comment]
I basically *can't* use markdown right now because there isn't "support for defining image size", so looking forward to this feature!

**Comment by flurin** [comment]
This would be really interesting as it would be quite trivial to write filters that could do things with these attributes as well (including other files come to mind)

**Comment by matteobachetti** [comment]
+1

**Comment by crsh** [comment]
:+1:

**Comment by legrostdg** [comment]
Is there still something preventing https://github.com/jgm/pandoc/pull/2351 from being merged (except that it now has conflicts with the current master)?

**Comment by jgm** [comment]
+++ legrostdg [Oct 21 15 07:23 ]:
>   Is there still something preventing [1]#2351 from being merged (except
>   that it now has conflicts with the current master)?

Mainly that it requires changes to pandoc-types and
everything that depends on this...it's a big API change.
I think we should be able to do it soon, though.

**Comment by nichtich** [comment]
Where is the best place to get to know and anticipate the coming changes? I bet the change can also affect custom pandoc filters so authors and developers should be pointed to a good description what to take care of.

On 21. Oktober 2015 16:57:17 MESZ, John MacFarlane <notifications@github.com> wrote:
>+++ legrostdg [Oct 21 15 07:23 ]:
>>   Is there still something preventing [1]#2351 from being merged
>(except
>>   that it now has conflicts with the current master)?
>
>Mainly that it requires changes to pandoc-types and
>everything that depends on this...it's a big API change.
>I think we should be able to do it soon, though.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/261#issuecomment-149923286

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Dashed** [comment]
:+1: Slick. Thanks @jgm!

**Comment by legrostdg** [comment]
\o/

**Comment by signalwerk** [comment]
Awesome! Thx!

**Comment by ambs** [comment]
WEEEEEEEEE!!!

**Comment by katrinleinweber** [comment]
Merci! :sunny:

**Comment by ivoanjo** [comment]
This is huge, thanks! :+1:

**Comment by frumbert** [comment]
Cool, but this won't be available in a full release until 1.16, right? I can't create a windows version of this branch using either stack or cabal.

**Comment by jgm** [comment]
+++ TIm St.Clair [Nov 22 15 17:41 ]:
>   Cool, but this won't be available in a full release until 1.16, right?
>   I can't create a windows version of this branch using either stack or
>   cabal.

What happens on Windows when you try with stack?

**Comment by frumbert** [comment]
Windows 2003 R2 Sp2 32-Bit, on VirtualBox; git, node, cygwin, miktex, haskell platform, cabal, etc all installed and updated ok. (ghc version 7.8.3)

$ stack install
Downloading lts-3.13 build plan ...FailedConnectionException2 "raw.githubusercon
tent.com" 443 True user error (cryptonite: random: cannot get any source of entr
opy on this system)

when compiling via cabal, I also get cryptonite can't be installed (cryptonite: random: cannot get any source of entropy on this system).

**Comment by jgm** [comment]
https://hackage.haskell.org/package/cryptonite
says it supports Windows >= 8.

Is Windows 2003 < Windows 8?  If so, that's your problem.

+++ TIm St.Clair [Nov 22 15 21:19 ]:

**Comment by frumbert** [comment]
*slaps forehead*
compiling happily on my win10 box...

**Comment by Wind4Greg** [comment]
I really want this feature but can't get Pandoc to build with stack on Windows 10. Followed the instructions from <https://github.com/jgm/pandoc/wiki/Installing-the-development-version-of-pandoc>, downloaded the latest `stack` from <http://docs.haskellstack.org/en/stable/install_and_upgrade.html#windows>. But I get a weird error seemingly unrelated to Pandoc:
```
    C:\Users\Greg\AppData\Local\Temp\stack5940\HTTP-4000.2.21\Network\HTTP\Proxy.hs:85:22:
        Not in scope: ‘liftM’
        Perhaps you meant ‘liftM2’ (imported from Control.Monad)
```
Which has something to do with a Haskell HTTP library. Is there any other way to get this feature? Or is there something about Haskell on windows that I'm overlooking.

**Comment by jgm** [comment]
Someone has reported the same issue on pandoc-discuss.
I haven't had a chance to build yet on a Windows machine or
investigate further.

+++ Greg Bernstein [Dec 08 15 11:31 ]:

**Comment by Wind4Greg** [comment]
Thanks. It's a windows/Haskell issue, using a VM was able to build it on Ubuntu and see first hand this really nice feature.  I'll watch pandoc-discuss for the windows fix.
Cheers.

**Comment by mindv0rtex** [comment]
Is there an estimate of when this feature will reach the release?

**Comment by mb21** [comment]
Image dimensions have been in 1.16 for a while already...

**Comment by mindv0rtex** [comment]
Oops, my bad!

**Comment by mofosyne** [comment]
How do you use it btw? I can't seem to find instructions on using it in the manual.

**Comment by KurtPfeifle** [comment]
@mofosyne:

Search for *`link_attributes`*.

See here: http://pandoc.org/README.html#images

**Comment by flrgsr** [comment]
It seems this only works with the *width* and *height* keyword.
What about *scale*?

I would love to be able to do something like this:

`![image description](images/myimage.png){ scale=0.5 }`

Am I missing something or is this really impossible yet?

**Comment by JonasT** [comment]
Similarly to @flrgsr I would like to be able to scale images, mainly so that I don't need to make all my images super low-res and/or hardcode the image sizes just to accommodate the scaling on HTML (which is super low DPI per default).

**Comment by mb21** [comment]
It sounds what you guys are really looking for is:

    ![](image.jpg){srcset="image_2x.jpg 2x"}

**Comment by JonasT** [comment]
Yes! Is there a nicer way to write that? Also, does that work with all backends (e.g. both PDF and HTML)?

**Comment by mb21** [comment]
Depending on your taste, it's already quite nice.. (at least it's consistent with other syntax) see http://pandoc.org/MANUAL.html#extension-link_attributes for the rationale.

No, if you generate your PDF with LaTeX (which is the default), it will use `image.jpg`. You can always write a filter that scales your images, or write some CSS to your needs...

**Comment by JonasT** [comment]
So what about HTML? HTML is one of my required main targets so if it's not working nicely there, sadly I can't really use it.

Filters are often mentioned here, but I consider them quite uninteresting since they require something outside markdown. Similar to CSS, except CSS is even a lot worse since it requires specific stuff for one output format only. Write once in a universal format, output to all targets shouldn't require this..

**Comment by mb21** [comment]
> So what about HTML? 

What about it? Tell us what HTML you expect pandoc to generate for what input...

> Filters are often mentioned here, but I consider them quite uninteresting since they require something outside markdown.

That's not correct. Filters are for you to customize pandoc's behaviour, see https://pandoc.org/scripting.html

But this discussion/QA should move to pandoc-discuss. This issue is closed and we're spamming the people subscribed to it.
