### ISSUE TITLE
(some) citations in YAML issues

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#2611]
I have found [Citeproc YAML for bibliographies](http://blog.martinfenner.org/2013/07/30/citeproc-yaml-for-bibliographies/) article while searching for more information about the CSL YAML references file format. The author of the article offers his own [YAML citations file](http://feed.labs.orcid-eu.org/0000-0003-1419-2405.yml) (bottom of the article). (Interestingly, Pandoc does not like file format and it complains about unrecognized bibliography file format, if I use it whole.) I used one of his entries to model my own entry in my own file:

~~~~{.yaml}
- title: ! 'Preclinical and clinical activity of sunitinib in patients with cisplatin-refractory
    or multiply relapsed germ cell tumors: A Canadian Urologic Oncology Group/German
    Testicular Cancer Study Group cooperative study'
  container-title: Annals of Oncology
  volume: '22'
  issue: '12'
  page: 2654-2660
  author:
  - family: Oechsle
    given: K.
  - family: Honecker
    given: F.
  - family: Cheng
    given: T.
  - family: Mayer
    given: F.
  - family: Czaykowski
    given: P.
  - family: Winquist
    given: E.
  - family: Wood
    given: L.
  - family: Fenner
    given: Martin
  - family: Glaesener
    given: S.
  - family: Hartmann
    given: J.T.
  - family: Chi
    given: K.
  - family: Bokemeyer
    given: C.
  - family: Kollmannsberger
    given: C.
  genre: article
  DOI: 10.1093/annonc/mdr026
  URL: http://dx.doi.org/10.1093/annonc/mdr026
  id: oechsle2011a
  type: ''
  issued:
    date-parts:
    - - 2011
~~~~

Please notice, at the bottom of the entry, the `type` is set to `''`. If I add this entry to my YAML file and use the `[@oechsle2011a]` ID in my document, then when I try to process the citations with `pandoc --bibliography citace.yaml --csl iso690-author-date-cs.csl -f markdown -t markdown-citations -o test.citations.md test.md`, I will get this:

~~~~
pandoc-citeproc: mzero
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
~~~~

I was able to find out that if I fill in the `type` with `article-journal` as value, the processing will succeed.

Now, my questions are:

- Is it mandatory for the `type` to have non-empty string value?
- Would it be possible to get some more useful error message than the above if there is a missing field in the entry?

**Comment by jgm** [comment]
I've fixed this in [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc/commit/ea531e09df8fbb55dbb0b820eebdf37252fd90d2).
