### ISSUE TITLE
Line breaks inserted inside single words breaks formatting in .rst tables

### ISSUE THREAD

**Issue by quarion** [jgm/pandoc#2612]
### Description

When converting from .md with pipe tables to .rst there are line breaks inserted in the middle of single words. This makes resulting .rst render incorrectly (either with rst to html with Pandoc or with Sphinx).

Incorrect formatting observed includes inserting space characters where the word was wrapped, or incorrectly rendering accents (because **Header* [newline] * may not be considered single word).

It seems, that .rst tables width are taken from the realiteve number of dashes in the pipe table in .md. But the documentation states, that the pipe tables do not carry information about relative widths of the columns.

### How to reproduce

Input .md file:

```
| __Parameter__     | __Description__     | __Type__      | __Is Required__ |
| :------------ |:-------------:  | :-----    | :---:       |
| CustomerID | Id of the customer | String | yes |
```

Convert with:

> pandoc -o doc.rst  doc.md --from markdown_github --standalone

Output .rst file:

```
+----------------+-----------------+---------+-------+
| **Parameter**  | **Description** | **Type* | **Is  |
|                |                 | *       | Requi |
|                |                 |         | red** |
+================+=================+=========+=======+
| CustomerID     | Id of the       | String  | yes   |
|                | customer        |         |       |
+----------------+-----------------+---------+-------+
```

### Workaround

Manually maintain pipe tables column widths. But there is no feedback if something will be formated incorrectly unitl you run Pandoc. If the content of the pipe tables would change, output might break again

**Comment by jgm** [comment]
I can't reproduce this with the current dev version of pandoc or  with pandoc 1.15.2 (e.g. on pandoc.org/try):

I get:
```
+-----------------+----------------------+------------+-------------------+
| **Parameter**   | **Description**      | **Type**   | **Is Required**   |
+=================+======================+============+===================+
| CustomerID      | Id of the customer   | String     | yes               |
+-----------------+----------------------+------------+-------------------+
```
You did not say what pandoc version you use.

**Comment by quarion** [comment]
Sorry, my example was wrong. It indeed converts fine for me, too. I have cropped the rest of the table from the real data that I have, and it seems depends on the content of the table (length of content in different rows). Here is the correct example:

```
| __Parameter__     | __Description__     | __Type__      | __Is Required__ |
| :------------ |:-------------:  | :-----    | :---:       |
| CustomerID | Id of the customer | String | yes |
| FirstName | First name of the customer | String | no |
| LastName | Last name of the customer | String | no |
| LanguageTag | The language tag of the customer in IETF standard. The valid values can be retrieved through (...) | String | no |
| PropertyWithALongNameLongName | desc...  | String | no |
```

Result

```
+--------------+----------------+--------+-------+
| **Parameter* | **Description* | **Type | **Is  |
| *            | *              | **     | Requi |
|              |                |        | red** |
+==============+================+========+=======+
| CustomerID   | Id of the      | String | yes   |
|              | customer       |        |       |
+--------------+----------------+--------+-------+
| FirstName    | First name of  | String | no    |
|              | the customer   |        |       |
+--------------+----------------+--------+-------+
| LastName     | Last name of   | String | no    |
|              | the customer   |        |       |
+--------------+----------------+--------+-------+
| LanguageTag  | The language   | String | no    |
|              | tag of the     |        |       |
|              | customer in    |        |       |
|              | IETF standard. |        |       |
|              | The valid      |        |       |
|              | values can be  |        |       |
|              | retrieved      |        |       |
|              | through (…)    |        |       |
+--------------+----------------+--------+-------+
| PropertyWith | desc…          | String | no    |
| ALongNameLon |                |        |       |
| gName        |                |        |       |
+--------------+----------------+--------+-------+
```

If this RST is converted to HTML, then the issues I have described are visible.

I am also running pandoc 1.15.2 on Windows, and tested it also on pandoc.org

**Comment by quarion** [comment]
Also, this kind of input generates table with a lot of line breaks

```
| __Parameter__     | __Description__     | __Type__      | __Is Required__ |
| --- | --- | --- | --- |
| CustomerID | Id of the customer | String | yes |
| LanguageTag | The language tag of the customer in IETF standard. The valid values can be retrieved through (...) | String | no |
```

While this one will be auto-sized

```
| __Parameter__     | __Description__     | __Type__      | __Is Required__ |
| --- | --- | --- | --- |
| CustomerID | Id of the customer | String | yes |

```


In the first example, the output table columns widths then can be manipulated by using different number of dashes `-`. In Github renderer, the number of dashes does not matter (you need at least 3), but the actual Pandoc Markdown documentation do not specify this explicitly.

**Comment by jgm** [comment]
Yes, if your pipe table is very long, pandoc will calculate
relative column widths (otherwise it exceeds page width in
some formats, like latex/pdf).

This calculation is done on the basis of the separator
lines, not the header.  Since the contents of the "is required"
column are so short, you don't end up with enough room for
the header.

Solution is just to use a longer separator line for the "is
required" column: something  like

    :--------------:


+++ Filip Gibki [Jan 02 16 11:18 ]:

**Comment by jgm** [comment]
+++ Filip Gibki [Jan 02 16 11:38 ]:

>   In the first example, the output table columns widths then can be
>   manipulated by using different number of dashes -. In Github renderer,
>   the number of dashes does not matter (you need at least 3), but the
>   actual Pandoc Markdown documentation do not specify this explicitly.

Right.  We need to document this feature (it's described in
the changelog but not the user's guide).

**Comment by jgm** [comment]
My mistake, the relative widths feature *is* documented in
the dev version of the README.  So I consider this issue
resolved.

"If a pipe table contains a row whose printable content is
wider than the column width (see `--columns`), then the cell
contents will wrap, with the relative cell widths determined
by the widths of the separator lines."
