### ISSUE TITLE
Markdown parsing fails in Underscore(_) within bold(**) 

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#2613]
Sample markdown text:

```
**_personRepository.Update**
```

Html output:

```
<p>**_personRepository.Update**</p>
```

Expected output:

```
<p><strong>_personRepository.Update</strong></p>
```

**Comment by jgm** [comment]
Thanks, interesting case.  I would eventually like to replace
pandoc's parsing algorithm for nested strong/emph with what
we have in cmark (which gives the expected result).

You can work around this by backslash-escaping the `_`.

**Comment by jgm** [comment]
Closing in favor of #3909, which subsumes this issue.
