### ISSUE TITLE
Output to latex uses \( and \) instead of $ and $ for inline math.

### ISSUE THREAD

**Issue by Recmo** [jgm/pandoc#2614]
echo "Test \$\\frac ab\$" | pandoc --to=latex

Actual result:

    Test \(\frac ab\)

(which does not parse as valid Latex, at least with xelatex)

Expected result:

    Test $\frac ab$

(pandoc 1.13.2.1. Compiled with texmath 0.8.2.2, highlighting-kate 0.5.12.)
(XeTeX 3.14159265-2.6-0.99992 (TeX Live 2015/Debian))

**Comment by jgm** [comment]
This is perfectly valid latex.  I just compiled a test document with

    test \(\frac ab\)

using both pdflatex and xelatex, and it worked properly.

**Comment by Recmo** [comment]
Thank you for your reponse.

Some further research showed my xelatex environment had `\(` and `\)` redefined, which is why it failed to compile.

I think the dollar sign delimiting is more common, and I would prefer it, but you are entirely right and my issue is invalid. Apologies.

**Comment by CarlKing5019** [comment]
@jgm , thanks for your great work to provide us the very useful tool. As the dollar sign delimiting `$` is more common in latex, would you please change the delimiting from `\(` to `$`, or provide a option to chose?  I do appreciate you.

**Comment by jgm** [comment]
See
http://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode

In principle we could make this selectable, but this is a
path I'd rather not go down.  I'd rather keep it simple.

+++ CarlKing5019 [Aug 13 16 00:37 ]:

**Comment by CarlKing5019** [comment]
Thanks for your response. I would try to adapt it.

**Comment by mgajda** [comment]
I came upon the same problem, and it appears that a simple Lua filter should solve it:
https://stackoverflow.com/questions/56828128/pandoc-is-tex-output-with-dollar-sign-math-possible
