### ISSUE TITLE
converting from pipe table to grid table with blank rows

### ISSUE THREAD

**Issue by vancleve** [jgm/pandoc#2615]
I am trying to use org-mode to write nice tables that I can use with pandoc and latex, so I end up converting pipe table in markdown to grid tables in markdown.

However, it seems that a blank link in a pipe table confuses markdown when converting to a grid table. Using pandoc 1.15.2.1, I start with the following MWE as test.md:

```
| test  | header |
|-------+--------|
| first | row    |
|       |        |
| third | row    |
```

and run `pandoc test.md -t markdown-pipe_tables-simple_tables-multiline_tables` to obtain:

```
+--------------------------------------+--------------------------------------+
| test                                 | header                               |
+======================================+======================================+
| first                                | row                                  |
+--------------------------------------+--------------------------------------+
+--------------------------------------+--------------------------------------+
| third                                | row                                  |
+--------------------------------------+--------------------------------------+
```
where there are missing pipes for the second row.

**Comment by jgm** [comment]
Closing in favor of #2616, which is the same issue.

**Comment by tarleb** [comment]
Sorry, I should have commented here too.  #2616 is a different issue.  I caught it while looking at this issue and wondering why one would use a markdown reader to read org-mode tables.  The answer to this seems to be that the org mode reader makes things even worse.

I haven't spent much time on this, but it seems like the above hints at a bug in the markdown writer.

**Comment by vancleve** [comment]
Thanks @tarleb! Also, the reason I want to use org-mode tables is that the table editor works so much better for me than table-mode in Emacs. So many problems putting in links and the like when editing with  table-mode. Ugh.

**Comment by jgm** [comment]
Sorry, reopening!

**Comment by jgm** [comment]
I thought initially that the reader was interpreting this as two separate tables (as reported in #2616), but actually it is correctly reading it as a single table; it's just the rendering that's wrong.
