### ISSUE TITLE
Unknown program error when supplying path to latex-engine

### ISSUE THREAD

**Issue by brentonk** [jgm/pandoc#2618]
I'm using Pandoc 1.16 on OS X 10.11.2 installed via [the OS X binary](https://github.com/jgm/pandoc/releases/download/1.16/pandoc-1.16-1-osx.pkg). I'm trying to convert a Markdown file to PDF, and I'm supplying a custom LaTeX engine via `--latex-engine`.

Here's what I entered at the command line to produce the error.

```
~$ echo "Hello world" > test.md
~$ which pdflatex
/Library/TeX/texbin/pdflatex
~$ pandoc test.md -o test.pdf --latex-engine=/Library/TeX/texbin/pdflatex
Unknown program /Library/TeX/texbin/pdflatex
pandoc: Error producing PDF
~$ echo $?
43
```

This appears to be a regression from Pandoc 1.15.2, since the same commands produce the expected output when I install that version.

**Comment by jgm** [comment]
This is due to commit
0a768f1cc568722973302554265efa414d097da3

The fix is quite easy.  I will commit a patch shortly.

**Comment by yihui** [comment]
@jgm Could you provide a patch release for this bug at your earliest convenience? It has affected quite a few R Markdown users. Thanks!

**Comment by jgm** [comment]
I will try to get something out this weekend.

+++ Yihui Xie [Jan 08 16 13:13 ]:

**Comment by jgm** [comment]
PS. You could fix this in R Markdown by simply adding the
path to the latex program to PATH in the local environment
in which pandoc is run, and using the basename instead of
the fully qualified path in --latex-engine.

+++ Yihui Xie [Jan 08 16 13:13 ]:

**Comment by yihui** [comment]
Yeah, I know we can fix it in R Markdown, but our problem is that it is not easy for us to make a new release soon (due to the restrictions of [CRAN](https://cran.r-project.org/web/packages/policies.html)). Thanks very much!
