### ISSUE TITLE
Pandoc soft wrapping breaks references

### ISSUE THREAD

**Issue by klapheke** [jgm/pandoc#2619]
When I run pandoc 1.16 and pandoc-citeproc 0.8.1.3 with a `--bibliography` specified and line breaks inside paragraphs, `pandoc-citeproc` fails:

    $ pandoc --bibliography=references.bib
    hello
    world!
    ^D
    pandoc-citeproc: The key "SoftBreak" was not found
    pandoc: Error running filter pandoc-citeproc
    Filter returned error status 1

This happens even with a minimal bibliography and irrespective of the value of `--write` or `--wrap`. It works fine with *only* hard wraps (if "hello" and "world" have a blank line between them) or if no bib file is given.

**Comment by jgm** [comment]
You need to update to pandoc-citeproc 0.9
