### ISSUE TITLE
latex/beamer: babel language option not specified 

### ISSUE THREAD

**Issue by MichaelKofler** [jgm/pandoc#2627]
`pandoc -V lang=german -t beamer in.text -o out.pdf`

fails with:
babel Error: You haven't specified a language option

also: 
`pandoc -s -V lang=german -t latex in.text -o out.tex`

produces a tex file without language option. latex out.tex then gives the same error.

PS: Tested with pandoc 1.16. These errors don't happen with pandoc 1.13, but I have not tested the versions 1.14 and 1.15, so I don't know when they were introduced.

**Comment by jgm** [comment]
Recent versions of pandoc have standardized `lang` attribute so it works the same in all formats.
Try `lang=de-DE`.

**Comment by MichaelKofler** [comment]
Thank you!
