### ISSUE TITLE
Preserve literal, unescaped underscores in YAML metadata block field

### ISSUE THREAD

**Issue by breschke** [jgm/pandoc#2630]
I would like to include a field in the YAML metadata block to be used as a variable in a latex template. The field value is a path that includes underscores. However, when passed to the latex template, the underscores are escaped, which causes problems in latex processing. I would like to pass the field value as a literal string. I've tried quoting the path and prefacing the path with the pipe character, but the underscores are still escaped.

MWE:

.md file:
```
---
title: Some title
graphicspath: '/path/containing/under_scores/'
...
```

latex template:
```
\documentclass[11pt,article,oneside]{memoir}

$if(graphicspath)$
\graphicspath{{$graphicspath$}}
$endif$
\begin{document}
$body$
\end{document}
```

Commands:
```
pandoc -s -S --template=toy.template -o test.tex test.md
```

Resulting .tex document:

```
\documentclass[11pt,article,oneside]{memoir}

\graphicspath{{/path/containing/under\_scores/}}
\begin{document}

\end{document}
```

But the escaping of the underscore causes problems in processing the .tex file with, e.g., xelatex.

**Comment by jgm** [comment]
See #2139.
