### ISSUE TITLE
1.5.2 HTML table width regression

### ISSUE THREAD

**Issue by iffy** [jgm/pandoc#2634]
I encountered a problem when upgrading from 1.15.0.6 to 1.16.

On 1.16 (and also 1.15.2), with this as `foo.md`:

```
<div>
| Date | Event |
|:---:|:---|
| 4 Nov 2015 | XXXXXX XXXXXXXXX XXX XXXXXXXXX XX XXX XXXXXXXXXXX XXXXXXX XXX XXXXXX XXXX XXXXXXXXX. |
| 5 Nov 2015 | XXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXX. XXXXXXXXXXXX XXXXXX. |
| 4 Jan 2016 | XXXXXXXXX XXX XXXXXXXXX. XXXXXXXXXXXX XXX XXXXX XX XX XXXXXXXX XXXXXXXXXXX. |

</div>
```

running `pandoc --to html5 foo.md` produces this:

```
<div>
<table style="width:15%;">
<colgroup>
<col style="width: 8%" />
<col style="width: 6%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Date</th>
<th style="text-align: left;">Event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">4 Nov 2015</td>
<td style="text-align: left;">XXXXXX XXXXXXXXX XXX XXXXXXXXX XX XXX XXXXXXXXXXX XXXXXXX XXX XXXXXX XXXX XXXXXXXXX.</td>
</tr>
<tr class="even">
<td style="text-align: center;">5 Nov 2015</td>
<td style="text-align: left;">XXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXX. XXXXXXXXXXXX XXXXXX.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4 Jan 2016</td>
<td style="text-align: left;">XXXXXXXXX XXX XXXXXXXXX. XXXXXXXXXXXX XXX XXXXX XX XX XXXXXXXX XXXXXXXXXXX.</td>
</tr>
</tbody>
</table>
</div>
```

The table width being 15% is a problem (super skinny tables).  On pandoc 1.15.0.6 the generated HTML table did not include widths on either the `<table>` or `<col>`.  In fact the whole `<colgroup>` element is new in 1.5.2.  Is there a way to disable table-width-guessing completely?

**Comment by iffy** [comment]
Just saw that #2574 is a probably a duplicate of this.  And using `--column=10000` effectively disables this new behavior (until I get a table more than 10000 wide) :)

**Comment by jgm** [comment]
You already saw the other relevant issue.  In short, no bug.

The best solution is not to mess with --columns, but to
adjust your separator lines, since the relative column
widths are calculated from them.

Instead of

    |:---:|:---|

use something like

    |:---:|:--------------------------------------------------------|

You have control over the relative widths.

**Comment by iffy** [comment]
For our use case (where we are using a style sheet to determine table column widths in the rendered HTML) messing with the pipe table is not what we want.  We just want to defer to the HTML/CSS.  So we'll have to go with the --column=BIGNUMBER method.
