### ISSUE TITLE
Protocol relative urls in Markdown image

### ISSUE THREAD

**Issue by dufferzafar** [jgm/pandoc#2635]
I am trying to convert a markdown file with a protocol relative url for an image.

**Contents of the file**

``` markdown
![Image with protocol relative url](//i.stack.imgur.com/muxnt.jpg)
```

**Command**

`/usr/bin/pandoc -s --toc --latex-engine xelatex -f markdown -o pandoc_issue.pdf /tmp/pandoc_issue.md`

**Output**

```
pandoc: Could not find image `//i.stack.imgur.com/muxnt.jpg', skipping...
! Unable to load picture or PDF file '//i.stack.imgur.com/muxnt.jpg'.
<to be read again> 
                   }
l.83 ...udegraphics{//i.stack.imgur.com/muxnt.jpg}

pandoc: Error producing PDF from TeX source
```

**Expectations**

I would expect that Pandoc would just use `http` as a protocol to fetch the image in this case.

**Comment by jgm** [comment]
It's a protocol relative URL...how is pandoc supposed to
know what scheme to use?

+++ Shadab Zafar [Jan 09 16 12:11 ]:

**Comment by dufferzafar** [comment]
Can it not default to `http` ?

**Comment by linquize** [comment]
For html page,  using relative protocol allows the browser to pull the image from the corresponding protocol of html page.
If the page is served via https,  then the image is fetched also from https.
If not,  then from http

**Comment by jgm** [comment]
+++ linquize [Jan 10 16 06:29 ]:
>   For html page, using relative protocol allows the browser to pull the
>   image from the corresponding protocol of html page.
>   If the page is served via https, then the image is fetched also from
>   https.
>   If not, then from http

Or from file...or whatever protocol the page is being served with.

The problem is that in this case pandoc is reading a markdown file
directly from the file system, not over HTTP. So there is no
protocol to relativize to.  Perhaps we could fall back on
http in such cases, though, as suggested.

**Comment by dufferzafar** [comment]
Yes, If there is a scheme/protocol available then use that, else use http by default.

**Comment by timofonic** [comment]
Why not?

Doesn't html support directories and such? Wouldn't this simply work despite being in a local filesystem, ftp, http, https, tor, i2p, git, anewcoolhipsterprotocol?

What about this?

https://www.oasis-open.org/committees/xri/

**Comment by dufferzafar** [comment]
@jgm I experienced this issue again today. Are you still planning to add the default option?
