### ISSUE TITLE
Further Word/DOCX Metadata Capabilities (bidirectional)[Feature Request]

### ISSUE THREAD

**Issue by rdwatters** [jgm/pandoc#2636]
Docx-based workflows are the most popular content creation workflows for nonprofits (my wheelhouse). Even more regrettable, MS-specific solutions like SharePoint are still the most popular for document management. 

Pandoc already does well to transfer YAML metadata blocks in .md files to the "Properties" of a Word document, but currently, I can only get the title and author to populate. If Pandoc could convert for any of the following out-of-the-box properties (or better yet, to accomodate _custom_ metadata as well), it could save entire companies from the tragedy of Microsoft Word on the web, especially in the nonprofit sector, IMHO. 

OOB "Properties" under the "Summary" for word that would be great to auto-populate via markdown yaml block (or said metadata flowing from yaml markdown to the properties section of a word doc):

Title: (Already works)
Subject:
Author: (Already works)
Manager: 
Company: (Seems to autopopulate, for me at least, from my Office365 account maybe?)
Keywords: (This doesn't work either with "tags" or with "keywords" in YAML; either would be great)
Comments: (Not sure this is important)

The "custom" tab in the Properties pane includes many OOB SharePoint-based metadata keys, but also allows for users to create their own custom metadata. Unfortunately, I'm a pandoc fan rather than developer, so I can't make Haskell-related suggestions.

**Comment by larsilus** [comment]
Would really love to see this as well.

**Comment by Zack-83** [comment]
I also need to transfer metadata and would greet it as a great improvement!

My metadata are somehow special (project title, acronym, funding number, version number) but I can try to adapt them to the "standard" ones. I need to use them within some fields to be placed into the header.

A quantum of solace: the `Abstract` seems to be correctly transferred (it will appear on the firs page, after title and author).

**Comment by agusmba** [comment]
Related to https://github.com/jgm/pandoc/issues/3034
Unsure if it's a duplicate

**Comment by jgm** [comment]
There are two issues:

1. Custom properties
2. Standard properties (like Subject) that we currently don't do anything with.

#3034 is about (1); I took this issue to be at least partly about (2).
The issues substantially overlap.

**Comment by rdwatters** [comment]
@jgm Perhaps it's best to close this. I don't even remember asking for this same feature twice in slightly different wording, more or less. It's been a minute, but I guess this was unidirectional, whereas #3034 was bidirectional...

**Comment by jgm** [comment]
OK, let's close this one.
