### ISSUE TITLE
Update installation instructions for Arch

### ISSUE THREAD

**Issue by felixonmars** [jgm/pandoc#2639]
The current `installing.html` page has a dead link for Arch: https://aur.archlinux.org/packages/haskell-pandoc/. Since I have created a package in the [community] repository, please either point the link to https://www.archlinux.org/packages/community/x86_64/pandoc/ (for the executable) or https://www.archlinux.org/packages/community/x86_64/haskell-pandoc/ (for the libraries). Thanks!

**Comment by jgm** [comment]
Thanks, I've made the change.

+++ Felix Yan [Jan 10 16 07:34 ]:

**Comment by felixonmars** [comment]
Thank you :)
