### ISSUE TITLE
Markdown -> Latex -> PDF fails to compile "\n"

### ISSUE THREAD

**Issue by matthiasbeyer** [jgm/pandoc#2641]
If I have a 

```
... for example "\n" ...
```

in a `.md` document which I want to compile to PDF via LaTeX, pandoc fails because LaTeX cannot compile

```latex
``\n``
```

as `\n` is an undefined latex macro. How can I fix this, or is this a bug?

**Comment by jgm** [comment]
Use either

    for example "`\n`"

or

    for example "\\n"

+++ Matthias Beyer [Jan 10 16 08:57 ]:
