### ISSUE TITLE
highlighting-kate's `bold=1` ignored?

### ISSUE THREAD

**Issue by eah13** [jgm/pandoc#2642]
Highlighting-kate does have [`bold=1` in the itemdata for Python operators](https://github.com/jgm/highlighting-kate/blob/0.5.11.1/xml/python.xml#L568), which appears to be ignored in highlighted pandoc codeblocks in PDF and epub.  Bug?

Example in pandoc's pygments-like default:
![screenshot 2016-01-10 at 1 15 28 pm](https://cloud.githubusercontent.com/assets/1702745/12223106/412b05f8-b79c-11e5-8177-bc4c7d680246.png)

I'm helping typeset a python textbook and it's pretty important to have keywords styled differently than normal text for students so they grok the difference between reserved and user-defined names. Even if this is a #wontfix, I'd appreciate a tip on the easiest way to highlight Python operators while keeping the build as vanilla as possible.

See also #2054.  For reference, here's the above in [actual Pygments](http://pygments.org/demo/3534475/)

![screenshot 2016-01-10 at 1 13 45 pm](https://cloud.githubusercontent.com/assets/1702745/12223100/23c0fbee-b79c-11e5-8a19-235aac972997.png)

(Edit: better examples)

**Comment by jgm** [comment]
highlighting-kate ignores the extra styles; it just gives
you the basic classifications of the tokens.

You could compile your own version of h-k with a tweaked
python.xml.  Instructions in the README.


+++ Elliott Hauser [Jan 10 16 10:03 ]:

**Comment by jgm** [comment]
The most current python.xml no longer has bold="1" in itemdata for Operators.
