### ISSUE TITLE
Latex quotes get lost if not all-plain/all-emphasised

### ISSUE THREAD

**Issue by klausman** [jgm/pandoc#2645]
```
$ cat t.tex 
“A quote that \textit{makes a point.”}
$ pandoc -f latex -t html < t.tex 
<p>“</p>
$
```
As far as I can tell, this is behavior is new with pandoc 1.16, 1.15.0.6 did not show this behavior.

(and just in case: no, that "broken" nesting is not broken, it's what western typography does.)

**Comment by klausman** [comment]
Just tested with pandoc-1.15.0.6:

```$ pandoc -f latex -t html < t.tex 
<p>“A quote that <em>makes a point.”</em></p>
```

**Comment by jgm** [comment]
Culprit is probably c73ae81628b77d8b5002e8216650dd8b449768b5
