### ISSUE TITLE
Header attributes on header that is code adds id to wrong element.

### ISSUE THREAD

**Issue by daurnimator** [jgm/pandoc#2647]
test.md:

```
# `foo` {#bar}
```

`pandoc test.md`

```
<h1 id="foo"><code id="bar">foo</code></h1>
```

I expected:

```
<h1 id="bar"><code>foo</code></h1>
```

**Comment by jgm** [comment]
"wrong" is a matter of interpretation here, since you
can add attributes to code spans too.

To ensure it goes on the header, you might try inserting
a blank HTML comment between them.

    # `foo`  {#bar}

+++ daurnimator [Jan 12 16 08:46 ]:

**Comment by daurnimator** [comment]
Ah, I didn't know `fenced_code_attributes` was a thing.
I guess I can just turn that extension off?

**Comment by jgm** [comment]
Yes, you can turn it off.

+++ daurnimator [Jan 12 16 16:01 ]:

**Comment by daurnimator** [comment]
> Yes, you can turn it off.

(I updated my comment on github, please check it out)

**Comment by jgm** [comment]
Turn off `inline_code_attributes`, not `fenced_code_attributes`.

**Comment by daurnimator** [comment]
> Turn off inline_code_attributes, not fenced_code_attributes.

Thankyou. Perhaps it could be noted somewhere that this sort of conflicts with header attributes?

**Comment by mb21** [comment]
I think this has been changed in https://github.com/jgm/pandoc/commit/0159956f7fc008ecc28632920e700878aa3f5996
