### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by kerokeroloid** [jgm/pandoc#2648]
Command used:
```
pandoc nlwiki.wikitext -f mediawiki -t plain  -o nlwiki.plain
```

Result:
```
pandoc: out of memory (requested 5705302016 bytes)
```

nlwiki.wikitext is a 5705256767 byte file.

**Comment by jgm** [comment]
Yes, pandoc reads the whole input into memory before
parsing; it does not parse it as a stream.  (Indeed,
it will need considerably more memory than the file size.)

I never really anticipated that anybody would want to
convert a file this big.

**Comment by kerokeroloid** [comment]
This is actually the whole nl.wikipedia.org.

**Comment by kerokeroloid** [comment]
While I solved this by splitting the file into multiple parts, it still hangs on errors in every file:

```
pandoc: 
Error at "source" (line 1429, column 1):
unexpected "!"
expecting lf new-line or "|}"
! Eigenschap !! Notatie !! EPS 60 !! EPS 100 !! EPS 150 !! EPS 200 !! EPS 250
^
pandoc: 
Error at "source" (line 257, column 1):
unexpected "|"
expecting lf new-line or "|}"
|----- valign="top"
^
pandoc: 
Error at "source" (line 585, column 1):
unexpected "|"
expecting lf new-line or "|}"
|- valign="bottom"
^
pandoc: 
Error at "source" (line 3465, column 1):
unexpected "|"
expecting lf new-line or "|}"
|-----
^
```

Do I put this into a new issue, or am I doing something stupid with the command?

```
for file in nlwiki.wikitext.*.unescaped
do
  pandoc "$file" -f mediawiki -t plain >> nlwiki.plain
done
```

(nlwiki.wikitext.*.unescaped are the pieces split from the file that caused the OOM error)

**Comment by jgm** [comment]
You're not making a mistake.  The parser isn't perfect.

It's most helpful if you can isolate the problem in a small
snippet and include that, plus the exact command you used,
in the issue.
