### ISSUE TITLE
Embedded SVG in PDF

### ISSUE THREAD

**Issue by candlerb** [jgm/pandoc#265]
The syntax:

```
![whee](foo.svg)
```

works for generating HTML pages, but not for PDF. LaTeX barfs with `Unknown graphics extension: .svg`

It would be really useful to support this. SVG is a standard, portable vector image format which is natively editable by tools such as inkscape.

Currently I have a workaround which is to convert the SVG to PDF externally, but this also requires the markdown source to be changed to `![whee](foo.pdf)` by piping through `sed`. At worst, this could perhaps be done as a (pandoc or gitit) plugin.

**Comment by hoxnox** [comment]
Can anybody write filter, that will use rsvg-convert tool from [librsvg](https://en.wikipedia.org/wiki/Librsvg) package? I have no expirience in filter writing to pandoc...

**Comment by jgm** [comment]
+++ Merder Kim [Apr 25 15 01:58 ]:
>Can anybody write filter, that will use rsvg-convert tool from [librsvg](https://en.wikipedia.org/wiki/Librsvg) package? I have no expirience in filter writing to pandoc...

If you post on pandoc-discuss, someone may be able to help
(indeed, if you search that list you may find something relevant.)

**Comment by Jmuccigr** [comment]
Thanks for doing this. Saved me today.

One thing: it's obvious, perhaps, but it bit me: you need to have inkscape available via the command line.

I used homebrew to install it. (I also already have the GUI version installed, so maybe a simple linking of that binary into my path would have worked. Hmmmm…)

Also, I've got this on my local system via the desktop app. Would someone mind updating the gist to this latest version that seems to work?

**Comment by HaoZeke** [comment]
This still seems to be a relevant problem... Particularly for automatic pdf generation from project README files which typically have svg badges...

**Comment by jgm** [comment]
See https://github.com/jgm/pandoc/issues/1793
This has been implemented in
https://github.com/jgm/pandoc/commit/6b72c5e35ba9b0872704b77b2bd8793657adcaba.

+++ Rohit Goswami [Nov 08 17 22:25 ]:

**Comment by HaoZeke** [comment]
Ah, I guess in my use case I need to first download the image...

**Comment by yuwash** [comment]
@hoxnox Thanks for the tip, librsvg is actually a very nice alternative to inkscape for being so much smaller to install. I think, based on @jeromerobert's [work](https://gist.github.com/jeromerobert/3996eca3acd12e4c3d40) you just need to change the line

    cmd_line = ['inkscape', option[0], eps_name, src]

to something like

    cmd_line = ['rsvg-convert', '--format', option[0], '-o', eps_name, src]

I personally converted it to ps instead of pdf and further used [ps2eps](http://manpages.ubuntu.com/manpages/bionic/en/man1/ps2eps.1.html) to create eps.
