### ISSUE TITLE
error 43 when converting md to pdf

### ISSUE THREAD

**Issue by dtenenba** [jgm/pandoc#2651]
This seems similar to https://github.com/jgm/pandoc/issues/2618 except I am using pandoc 1.16.0.1 which supposedly already includes the fix to that.

Apologies for not being able to come up with a less minimal example, but I lack the mad skillz to do that. 

```
curl -LO https://s3.amazonaws.com/pandoc-prob/24445c2e60f6.tex
curl -LO https://s3.amazonaws.com/pandoc-prob/AllelicImbalance-vignette.md
curl -LO https://s3.amazonaws.com/pandoc-prob/template.tex
/usr/local/bin/pandoc +RTS -K512m -RTS AllelicImbalance-vignette.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output AllelicImbalance-vignette.pdf --table-of-contents --toc-depth 2 --template template.tex --number-sections --highlight-style tango --latex-engine /usr/texbin/pdflatex --include-in-header 24445c2e60f6.tex 
```

For me (on Mac OS X 10.9.5 with pandoc 1.16.0.1 and pdflatex from pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013)) this produces:

```
! Undefined control sequence.
<recently read> \tightlist 
                           
l.76 \tightlist

pandoc: Error producing PDF
```

And leaves `$?` set to 43.

None of those 3 files contain the text `tightlist` so I am not sure how to proceed.

**Comment by jgm** [comment]
You're using an outdated template.  You need to incorporate
the definition of \tightlist from the default latex template
into your custom template.tex.

+++ dtenenba [Jan 13 16 13:30 ]:

**Comment by dtenenba** [comment]
OK, that template is provided by a third party, I will ask them to update it. Thanks.

**Comment by mazzma12** [comment]
For the record, You can use `pandoc -D Latex >my-latex-template.tex` to generate the template.
Just adding the snippet of code with `tightlist` command in the old template worked in my case.
```
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
```

Hope it helps
