### ISSUE TITLE
newline before `</ref>` tag in mediawiki

### ISSUE THREAD

**Issue by jlrn7** [jgm/pandoc#2652]
Hello! I noticed that in converting footnotes to mediawiki, the writer adds a `newline` before the closing `<\ref>` tag; I think the newline should be added _after_ the tag, to properly close the reference and keep the paragraph going. I don't know if this behavior is a bug or a feature.

**Comment by jgm** [comment]
As far as I can see, it makes no difference to the rendered output in MediaWiki whether the newline is before or after the closing tag.  Am I wrong?  Testing on MediaWiki sandbox.

I also note that pandoc tries to put block-level content inside `<ref>` tags, but MediaWiki just renders it literally.  This may be a separate issue, but if there's no way to include block-level content (e.g. lists) inside footnotes in MediaWiki, then I'm not sure what the best way to handle this limitation is.

**Comment by jgm** [comment]
I think I'll remove the trailing newline inside the ref element, since it makes no difference and looks better that way.
