### ISSUE TITLE
Latex \title gets split into multiple lines, which generates an error.

### ISSUE THREAD

**Issue by kszys** [jgm/pandoc#2653]
If a title of the document is longer than 80 characters, it seems that in Latex output of `pandoc`, the `\title` tag gets split into multiple lines. This is incorrect Latex syntax and generates an error, such as:

`Missing \begin{document}`

At the same time, it is correctly put in the `\pdftitle` tag.

**Comment by jgm** [comment]
Can you give an example?

This should be fine in LaTeX:

    \title{Title on
    multiple lines}

+++ Krzysztof Socha [Jan 14 16 03:47 ]:
