### ISSUE TITLE
Protect URLs from self-contained?

### ISSUE THREAD

**Issue by noamross** [jgm/pandoc#2656]
Would it be possible to have a syntax to protect links from being fetched for self-contained? Like putting an escape sequence prior to the URL?

**Comment by jgm** [comment]
There already is something like this for the EPUB writer:

https://github.com/jgm/pandoc/commit/c80c0df1fef118d32118dce222b204ae1f7b7f8b

This meaning for the `data-external` attribute could be
extended to Text.Pandoc.SelfContained as well.


+++ Noam Ross [Jan 14 16 12:47 ]:
