### ISSUE TITLE
pandoc --wrap=auto --columns=80 -f markdown_github -t markdown_github does not wrap long lines

### ISSUE THREAD

**Issue by Fordi** [jgm/pandoc#2657]
Sample MD code:

	Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet odio et felis euismod tincidunt ac a dui. Morbi quis pharetra sem. Vestibulum vel dapibus quam. Donec condimentum tortor lorem. Duis eget eros vitae risus iaculis mattis sit amet ac ex. In fermentum mi quam. Nunc pharetra, nisl ut accumsan pellentesque, eros enim tincidunt mi, eget ultricies massa orci et libero. Nulla vitae pretium mauris. Pellentesque sagittis, mauris sit amet facilisis tempor, leo est vehicula libero, sed accumsan lorem magna sit amet risus. Nulla et semper leo, id vulputate leo. Nullam tincidunt lacinia risus id tincidunt. Curabitur varius tortor quis urna efficitur blandit in in eros.

	Fusce sed laoreet mauris. Ut finibus tempus pellentesque. Nam id venenatis magna. Donec vitae turpis vitae tellus ornare consequat eu at orci. Morbi id lorem quis orci convallis varius id nec odio. Mauris vel urna ac purus eleifend fringilla aliquam sed dui. Donec placerat pellentesque nunc. Nullam vitae maximus eros, nec egestas orci. Ut ullamcorper lacus sed eleifend pretium. Maecenas orci magna, varius id sodales sit amet, suscipit et tortor.

	Etiam vestibulum justo egestas, dignissim sem ac, vulputate quam. Etiam iaculis elit et finibus ullamcorper. Donec rutrum nulla non hendrerit facilisis. In justo lectus, vestibulum id facilisis non, semper et est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque viverra rutrum sapien sit amet convallis. Aliquam elementum fermentum ex, sit amet auctor nisl feugiat pulvinar. Donec sit amet scelerisque est. Mauris tincidunt efficitur sapien, at vestibulum metus lacinia vel. Duis nec vehicula ipsum. Morbi vehicula facilisis nibh, vel convallis odio interdum sit amet. Sed facilisis elementum enim sed molestie. Proin vitae vestibulum velit. Pellentesque ut mauris sed tortor porttitor dignissim. Nam consectetur ante diam, sagittis luctus felis rutrum id.

	Duis in sapien magna. Maecenas rutrum faucibus lorem at pharetra. Etiam a scelerisque neque. Aenean finibus fringilla felis sit amet lacinia. Morbi ullamcorper ante ex, quis tempor velit convallis at. Etiam semper, sem efficitur tempus rutrum, sem ante finibus lacus, ut scelerisque justo felis feugiat sem. Aliquam erat volutpat. Proin et magna turpis.

	Sed porta tristique mi, non rhoncus nisl finibus sit amet. Vestibulum ac magna ac elit ultricies tincidunt a vel arcu. Fusce mattis turpis turpis, non suscipit purus dignissim a. Mauris sit amet odio vitae orci faucibus tincidunt eget maximus erat. Curabitur a tincidunt massa. Nulla condimentum nisi ac eleifend maximus. Quisque aliquet mattis est, vel dapibus ligula. Pellentesque scelerisque tincidunt ex quis suscipit. Etiam ultricies, odio et fermentum pulvinar, dui ante ultrices quam, sit amet condimentum ante risus ut neque. Phasellus vel ullamcorper mi. Donec semper sem urna, et tempor est aliquam id. Sed malesuada leo purus, at condimentum felis laoreet eu. Duis imperdiet, nibh vel hendrerit porta, felis nisi pellentesque neque, eget lacinia nulla sapien in nulla. Proin dapibus ante eu nisi pharetra porta. Nullam in lobortis tellus.

Output is equivalent to input.

Expected:

	Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet odio et
	felis euismod tincidunt ac a dui. Morbi quis pharetra sem. Vestibulum vel
	dapibus quam. Donec condimentum tortor lorem. Duis eget eros vitae risus
	iaculis mattis sit amet ac ex. In fermentum mi quam. Nunc pharetra, nisl ut
	accumsan pellentesque, eros enim tincidunt mi, eget ultricies massa orci et
	libero. Nulla vitae pretium mauris. Pellentesque sagittis, mauris sit amet
	facilisis tempor, leo est vehicula libero, sed accumsan lorem magna sit amet
	risus. Nulla et semper leo, id vulputate leo. Nullam tincidunt lacinia risus id
	tincidunt. Curabitur varius tortor quis urna efficitur blandit in in eros.

	Fusce sed laoreet mauris. Ut finibus tempus pellentesque. Nam id venenatis
	magna. Donec vitae turpis vitae tellus ornare consequat eu at orci. Morbi id
	lorem quis orci convallis varius id nec odio. Mauris vel urna ac purus eleifend
	fringilla aliquam sed dui. Donec placerat pellentesque nunc. Nullam vitae
	maximus eros, nec egestas orci. Ut ullamcorper lacus sed eleifend pretium.
	Maecenas orci magna, varius id sodales sit amet, suscipit et tortor.

	Etiam vestibulum justo egestas, dignissim sem ac, vulputate quam. Etiam iaculis
	elit et finibus ullamcorper. Donec rutrum nulla non hendrerit facilisis. In
	justo lectus, vestibulum id facilisis non, semper et est. Vestibulum ante ipsum
	primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque
	viverra rutrum sapien sit amet convallis. Aliquam elementum fermentum ex, sit
	amet auctor nisl feugiat pulvinar. Donec sit amet scelerisque est. Mauris
	tincidunt efficitur sapien, at vestibulum metus lacinia vel. Duis nec vehicula
	ipsum. Morbi vehicula facilisis nibh, vel convallis odio interdum sit amet. Sed
	facilisis elementum enim sed molestie. Proin vitae vestibulum velit.
	Pellentesque ut mauris sed tortor porttitor dignissim. Nam consectetur ante
	diam, sagittis luctus felis rutrum id.

	Duis in sapien magna. Maecenas rutrum faucibus lorem at pharetra. Etiam a
	scelerisque neque. Aenean finibus fringilla felis sit amet lacinia. Morbi
	ullamcorper ante ex, quis tempor velit convallis at. Etiam semper, sem
	efficitur tempus rutrum, sem ante finibus lacus, ut scelerisque justo felis
	feugiat sem. Aliquam erat volutpat. Proin et magna turpis.

	Sed porta tristique mi, non rhoncus nisl finibus sit amet. Vestibulum ac magna
	ac elit ultricies tincidunt a vel arcu. Fusce mattis turpis turpis, non
	suscipit purus dignissim a. Mauris sit amet odio vitae orci faucibus tincidunt
	eget maximus erat. Curabitur a tincidunt massa. Nulla condimentum nisi ac
	eleifend maximus. Quisque aliquet mattis est, vel dapibus ligula. Pellentesque
	scelerisque tincidunt ex quis suscipit. Etiam ultricies, odio et fermentum
	pulvinar, dui ante ultrices quam, sit amet condimentum ante risus ut neque.
	Phasellus vel ullamcorper mi. Donec semper sem urna, et tempor est aliquam id.
	Sed malesuada leo purus, at condimentum felis laoreet eu. Duis imperdiet, nibh
	vel hendrerit porta, felis nisi pellentesque neque, eget lacinia nulla sapien
	in nulla. Proin dapibus ante eu nisi pharetra porta. Nullam in lobortis tellus.

**Comment by jgm** [comment]
`markdown_github` by default treats newlines as hard breaks
(`<br />`), so pandoc never inserts newlines even when
`--wrap=auto`.  Try `-t markdown_github-hard_line_breaks`.
