### ISSUE TITLE
Error on converting epub to pdf

### ISSUE THREAD

**Issue by Ishitori** [jgm/pandoc#2658]
When I use pandoc to convert epub to pdf I get:

> pandoc my.epub -f epub -t latex -s -o my.pdf --latex-engine=xelatex
> ! LaTeX Error: There's no line here to end.

After quick search I realized that there are probably empty lines in epub, and LaTeX doesn't like it. Unfortunately, I have no control over epub file, and I have no idea where these empty lines could be. 

Is there a way to instruct pandoc to omit empty lines before sending the data to LaTeX? Any other strategies to deal with that problem?

Thank you.

**Comment by jgm** [comment]
We need to get a better handle on what the problem is.

Try creating the latex file and running xelatex on it
manually.

    pandoc myepub -f epub -t latex -s -o my.tex
    xelatex my.tex

xelatex will stop at the error and give you the option to
look at the exact source line that is responsible.

**Comment by Ishitori** [comment]
Hi John,

thanks for reaching me out. I run both commands you have provided. Pandoc command run well, no errors occurred, but the latter command gave me the following error:

>LaTeX Warning: File `images/00001.jpeg' not found on input line 74.
> ! Unable to load picture or PDF file 'images/00001.jpeg'.
> <to be read again>
>                  }
>l.74 \includegraphics{images/00001.jpeg}

It does not look the same as my previous error. Should I have run the former command with additional arguments to extract images to /images/ folder? Or this is actually a culprit?

Thank you.

**Comment by jgm** [comment]
Try with --extract-media=images

+++ Ishitori [Jan 18 16 09:50 ]:

**Comment by tushartyagi** [comment]
This is a closed issue but there's a workaround in case anyone else wants it.

The following needs to be done as jgm mentioned above
```bash
pandoc myepub -f epub -t latex -s -o my.tex
xelatex my.tex
```

This will choke on the first error like this:

```bash
LaTeX Warning: File `beno_9780465004683_msr_cvi_r1.jpg' not found on input line
 71.

! Unable to load picture or PDF file 'beno_9780465004683_msr_cvi_r1.jpg'.
<to be read again> 
                   }
l.71 ...raphics{beno_9780465004683_msr_cvi_r1.jpg}
                                                  
? 
```

Pressing `R` on the prompt continues the build and produces the pdf.
