### ISSUE TITLE
Markdown Reader: Comment changes figure into included graphic

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2660]
Under Pandoc 1.16.0.2, I've found that adding a comment after an image causes it to lose its status as a figure:

```shell
pandoc << EOT
![Test 1](test.jpg)<!--test-->

![Test 2](test.jpg)

EOT
```

Results:

```html
<p><img src="test.jpg" alt="Test 1" /><!--test--></p>
<div class="figure">
<img src="test.jpg" alt="Test 2" />
<p class="caption">Test 2</p>
</div>
```

**Comment by adunning** [comment]
(Updated: realized it has nothing to do with LaTeX.)

**Comment by jgm** [comment]
This is intended behavior.  An image is only treated as a
figure if it's the only thing in the paragraph.  An HTML
comment counts as something else.  Indeed, it's good to be
able to disable figurization in this way.

**Comment by adunning** [comment]
Fair enough; thanks!
