### ISSUE TITLE
Support for using ^superscript^, ~subscript~ and [^footnotes] in tables?

### ISSUE THREAD

**Issue by joelostblom** [jgm/pandoc#2661]
Hi,
Is it possible to implement support for using the ^superscript^, ~subscript~ and [^footnotes] syntax in markdown tables? (Or is it already there and I am misunderstanding how to use it?)

This would be useful when referencing and explaining entries in a table, e.g. explaining expenses in a budget template. For now I am using the latex command `\textsuperscript`, but it would be easier to have the usual pandoc syntax.

**Comment by jgm** [comment]
These should work in tables.  If they don't, please give a
specific example, plus the command line you use and the
pandoc version.

**Comment by joelostblom** [comment]
Today, superscript, subscript and footnotes work in tables, using the same markdown file and pandoc command as yesterday.

I did upgrade pandoc yesterday from 1.16.0.2-3 to 1.16.0.2-5 and pandoc-citeproc from 0.9.10 to 0.9.12, but I didn't test it immediately after as I had already implemented the latex solution and was running late with a report.
