### ISSUE TITLE
Support for image alignments

### ISSUE THREAD

**Issue by dustymabe** [jgm/pandoc#2662]
Go to http://pandoc.org/try/ and type in:

```
Here is an image:

.. image:: http://url.to.image/foo.png
   :align: left
   :height: 100px
   :width: 200 px
   :scale: 300 %
   :alt: alternate text
```

Convert this from rst to html and you get back:

```
<p>Here is an image:</p>
<p><img src="http://url.to.image/foo.png" alt="alternate text" width="200" height="100" /></p>
```

I would expect the align and other attribtues to get carried into the html. These are the attributes for image in rst: http://docutils.sourceforge.net/docs/ref/rst/directives.html#images

**Comment by frasertweedale** [comment]
Height and width are now carried through.

My PR #2724 adds suppport for (horizontal) alignment in the RST reader (but not the HTML writer)
