### ISSUE TITLE
Passing styles to ICML from Markdown

### ISSUE THREAD

**Issue by ClintH** [jgm/pandoc#2663]
Hi,

I'm using the HTML 'ASIDE' element as a way of blocking asides in a Markdown document. Classes are used on the ASIDE element so it is rendered as a box in the margin in HTML.

What I would like to do is for this markup to make a transition _somehow_ to ICML. I'm not sure how the semantics should map - it would be ideal if it became a separate text box in InDesign and with a paragraph style applied, or worse case just a paragraph style applied.

At the moment all of this markup is lost when converting to ICML. Same for DIVs and SPANs.

Is there a way to do this?

**Comment by mb21** [comment]
Yes, this is actually under discussion in https://github.com/jgm/pandoc/issues/2542, even if the title of the issue hasn't been updated to reflect the discussion.

**Comment by ClintH** [comment]
Thanks! I'll close this issue and monitor the other one.
