### ISSUE TITLE
LaTeX reader does not properly parse longtable environment

### ISSUE THREAD

**Issue by gitkrax** [jgm/pandoc#2669]
There seems to be a problem with how pandoc deals with tables in .tex-files, or how pandoc creates tables in .tex-files. I can reproduce the problem with a very simple example, by first converting a markdown table directly to pdf and then trying to convert it first to tex and then to pdf.

`test.md`

```
Here is some text.

### The Table

| Testing tables | column 1        | column 2        |
|----------------|-----------------|-----------------|
| row 1          | row 1, column 1 | row 1, column 2 |
| row 2          | row 2, column 1 | row 2, column 2 |
```

Converting this with `pandoc test.md -o test.pdf` produces the table succesfully.

![pdf](https://cloud.githubusercontent.com/assets/5079912/12481283/b364b774-c050-11e5-98c6-65b1d75facde.png)

However, when the same file is first converted to tex and then to pdf, with `pandoc test.md -o test.tex` and `pandoc test.tex -o test.pdf` we get

![pdf2](https://cloud.githubusercontent.com/assets/5079912/12481321/0357d3e2-c051-11e5-9cf8-cb58ded9b82f.png)

I'm not a latex expert, so I'm not sure whether the syntax is incorrectly produced or whether there is some problem with the conversion. As far as I could tell the syntax produced in the tex files was right.

**Comment by mb21** [comment]
Probably something wrong with the LaTeX reader. Note that to convert a .tex file to PDF, you don't have to use pandoc at all, but you can call LaTeX directly: `pdflatex test.tex`

**Comment by jgm** [comment]
Looks like the LaTeX reader doesn't correctly handle `longtable`.  (And I'm guessing, from looking at the source, not `table` either.)  It would be good to be able to round-trip here.  I'll change the title to give a better indication of where the issue lies.

**Comment by gitkrax** [comment]
I'm relying on pandoc in creating a book with chapters, and can't use pdflatex because the template for the whole book is also relying on pandoc features. Are there any guesses when somebody might have a chance of looking at this problem? I just need a heads up if I should instead move on to use some other way of building the book.

I'm also running into other problems that might be related to this. My first conversion (`chapter1.md` -> `chapter1.tex`) seems to work correctly, but trying to put the chapters together (looping `chapterX.tex` -> `book.pdf`) encounters weird problems -- not errors, just weird output, where some commands are ignored or read incorrectly.

**Comment by mb21** [comment]
Maybe there's a good reason you first convert to tex and only then to pdf, but usually you want to go directly from .md to pdf using pandoc templates etc, like `pandoc *.md -o book.pdf --template myLaTexTemplate.tex` (notice the *.md concatenates all md in the directory). Feel free to post your workflow and "weird problems" to the pandoc-discuss mailing list.

**Comment by gitkrax** [comment]
Thanks for the suggestion. I'll be sure to drop by if I have problems. However, mainly I'm interested in hearing if there is anybody working/planning to work with the latex reader.

**Comment by alexander-matsievsky** [comment]
@gitkrax Good day! You may find some relevant information here https://github.com/jgm/pandoc/issues/3087.

**Comment by phmarek** [comment]
I just stumbled upon the same problem...

I've got a `html` as input; can I tell `pandoc` not to use a `longtable` as inbetween?

If I convert the `html` to a `markdown` first and then try to get a `pdf`, `pandoc` stumbles upon the same `longtable` problem again:

```
Error producing PDF.
! Forbidden control sequence found while scanning use of \LT@nofcols.
<inserted text>
                \par
l.119 \begin{longtable}[]{@{}llll@{}}
```
