### ISSUE TITLE
Extension to pandoc's markdown similar to Gitbook, using a "Web template system"

### ISSUE THREAD

**Issue by xoox** [jgm/pandoc#2676]
Hi, [Gitbook Templating](http://help.gitbook.com/format/templating.html) would be a powerful extension to pandoc's markdown (not for pandoc's templates). That could also be a substitution to macros.

Besides, many static site generators are powered by similar templating feature. With it, pandoc will get the capability sharing the same markdown source with others, which could utilize pandoc as their renderer if configurable.

There're so many [template systems](https://en.wikipedia.org/wiki/Web_template_system). To find the one acceptable to pandoc community, a survey might be needed.

**Comment by jgm** [comment]
You know pandoc already has a templating system, don't you?
See the manual under Templates.   It is different from
the one you link to, but at least as powerful.

**Comment by xoox** [comment]
Oops,  I think I used wrong words.

Basically It is an extension to pandoc's markdown instead of pandoc's templates.
That extension would enable variables and tags in markdown.

`{% include "./test.md" %}` Importing an other file's content.

```jinja
{% for author in authors %}
  - {{ author.name }}
{% endfor %}
```
will generate a list of authors.

The extension may be a pre-processing function in [Markdown.hs](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/Markdown.hs) reader.

Here are several Haskell packages supporting similar syntax and features to Jinja2. With them, the extension should need not too much work.

* [ede](https://hackage.haskell.org/package/ede): Templating language with similar syntax and features to Liquid or Jinja2.
* [karver](https://hackage.haskell.org/package/karver): A simple template engine, inspired by jinja2.
* [ginger](https://hackage.haskell.org/package/ginger): An implementation of the Jinja2 template language in Haskell.
* [haiji](https://hackage.haskell.org/package/haiji): A typed template engine, subset of jinja2.

For information of other template system, see [Web template system](https://en.wikipedia.org/wiki/Web_template_system)

**Comment by jgm** [comment]
So the real issue is that you'd like some kind of preprocessor, run *before* Markdown parsing, that interpolates variables from metadata and can include external files.

This wouldn't be easy, since pandoc allows YAML metadata blocks anywhere in the document.  So you really have to parse Markdown in order to know what the metadata is.

I would suggest, if you want a preprocessor, that you just write one yourself and pipe your input through it before sending it to pandoc.  Or use an existing one [as suggested here](https://randomdeterminism.wordpress.com/tag/gpp/).

**Comment by xoox** [comment]
Thanks for your clarification. YAML anywhere in the document is an obstacle to this possible extension.
I'm trying with [nunjucks](https://mozilla.github.io/nunjucks/). And YAML data have to be converted to JSON.
To sharing the same metadata, they should be kept in a separate YAML file.
