### ISSUE TITLE
cannot disable extension - "Unknown extension: shortcut_reference_links"

### ISSUE THREAD

**Issue by azrdev** [jgm/pandoc#2682]
~~~bash
$ pandoc -f markdown-shortcut_reference_links doc.md -o doc.pdf
pandoc: Unknown extension: shortcut_reference_links
~~~

This is pandoc 1.13.2.1 from Ubuntu wily (15.10) repositories, sorry that I couldn't test the current release.

**Comment by jgm** [comment]
That extension was added in 1.14.  So you just need to
upgrade.
