### ISSUE TITLE
org-mode reader does not support `[[file:filename]]` link format for images

### ISSUE THREAD

**Issue by pmagwene** [jgm/pandoc#2684]
Org's default file link format is to include `[[file:filename]]`.  It would be great if Pandoc could support this for conversion of image links.  Currently this require manual intervention to convert to the more Pandoc friendly `[[filename]]`

**Comment by tarleb** [comment]
Whops, yeah, that's wrong.  `[[file://img.jpg]]` does work, with just `[[file:img.jpg]]` the `file:` prefix isn't dropped from the link.
