### ISSUE TITLE
Support listing formats (-l, --list-formats)

### ISSUE THREAD

**Issue by waldyrious** [jgm/pandoc#2685]
It would be nice to have an option to list the available input and output formats (like what is displayed at the top of `pandoc -h`). I was surprised this didn't exist, but couldn't find an existing issue or PR proposing this.

By the way, `pandoc --list` seems to hang in the command line, not sure what's happening there. In contrast, both `-l` and `--list-formats` correctly return "pandoc: unrecognized option `--list-formats'".

**Comment by jgm** [comment]
pandoc --list

is interpreted as

pandoc --listings

since that's the only option that starts with --list.  So
it's just waiting for input.

+++ Waldir Pimenta [Jan 29 16 03:21 ]:

**Comment by waldyrious** [comment]
I'm far from a CLI expert, but that behavior sounds odd to me. Was it intended to be that way, or is it just an implementation artifact?

**Comment by jgm** [comment]
The option parsing library we use behaves this way (as do
many other standard option parsing libraries).

It's kind of handy to be able to say `--biblio` instead of
`--bibliography`, for example.

+++ Waldir Pimenta [Jan 29 16 10:03 ]:

**Comment by jgm** [comment]
Since `--help` already lists the input and output formats, why is it important to have another option that (in effect) just emits part of the `--help` output?

**Comment by waldyrious** [comment]
I believe not having the list option violates the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) in two ways: users may be expecting such an option to exist (as did I) and type `pandoc -l` or `pandoc --list`, which is a pretty common format; but most importantly, by typing `pandoc --list` and getting a prompt without any indication of what the program is expecting, the user will be confused and wonder if something broke. From a UX perspective, it seems to me that adding this option would be clearly a net positive.

**Comment by tarleb** [comment]
Thanks for chiming in @waldyrious. It seems so me that the principle of least surprise doesn't apply here, there are many programs where `-l` and `--list` have very different meanings: To give some examples: With ssh the `-l` option is used to specify the user login name, with curl `--list` is short for an FTP specific option, gpg doesn't accept it because it's ambiguous, imagemagick's convert program prints a list of options instead of all supported formats, etc.

However, I do agree that it might be helpful to have all formats listed without the need to scroll back in the terminal window as one has to do with `--help`, so I'm also in favor of adding this.

**Comment by waldyrious** [comment]
Thanks for the LDP link, @tarleb -- I've bookmarked it :)

**Comment by jgm** [comment]
I think avoiding the need to scroll back is not a strong enough motivation for adding an additional option.  However, this got me thinking.

What if we removed the list of formats from the default `--help` output, and the list of syntaxes from the `--version` output, and added options like `--list-input-formats`, `--list-extensions`, `--list-output-formats`, `--list-highlighting-styles`, `--list-highlighting-languages`?  These could all output something machine-readable (e.g. a list with one entry on each line).  With the extensions, maybe the default setting for pandoc's markdown should be indicated as well.

**Comment by waldyrious** [comment]
Sounds good to me 👍

**Comment by jgm** [comment]
Closing in favor of #3173.
