### ISSUE TITLE
Bold text gets converted to URL

### ISSUE THREAD

**Issue by alexconst** [jgm/pandoc#2686]
URL is taking precedence over bold text, which breaks things when dealing with keywords.

``` text
# About

**this one work fine:**

**file will get converted to a link file:**

**same thing with http:**

**although it will work fine with a space http: **

```

The workaround I've been using is adding a space between the colon and the asterisks.
The problem is that Markdown or at least GFM (redcarpet?), doesn't recognize it any longer as bold text. (this one would be a bug on their side)

In any case IMO text shouldn't be converted to a link when you have `<text><colon><star><star><whitespace>`

Meanwhile, is there any option or workaround I can use to have expressions like "**file:**" not being converted to a link?

**Comment by jgm** [comment]
You could backslash-escape the colon:

    file\:**


+++ Alexandre Constantino [Jan 29 16 04:37 ]:

**Comment by alexconst** [comment]
Escaping the colon prevents the conversion to URL, but now the backslash also shows up in the text, so that is no good.
Am I missing something here?

Running latest pandoc 1.16.0.2

**Comment by jgm** [comment]
OK -- it seems that markdown_github (at least as pandoc interprets it) doesn't allow the `:` to be backslash-escaped.  Pandoc's regular `markdown` format allows all symbols to be escaped, but that's an extension.  I haven't checked on github.  Here goes\:

**Comment by jgm** [comment]
OK, looks like github's parser may have been changed to allow colons to be escaped.  Are all symbols escapable?  \? \& \$  If so, then I can easily change pandoc's markdown_github to conform.

**Comment by jgm** [comment]
Weird:  github's markdown parser allows `:` to be backslash-escaped, but not `?` or `$`.  Well, life's too short.

Do you need bare URLs to be interpreted as links?  If not, try using

    pandoc -f markdown_github-autolink_bare_uris

that should solve the problem in your original input.

**Comment by alexconst** [comment]
It's unfortunate markdown got so fragmented.

Well, bare URLs would be nice. But I can always enclose them.

Thanks for the help and Pandoc as well.

**Comment by jgm** [comment]
You could try using `&#58;` instead of the colon...

+++ Alexandre Constantino [Jan 29 16 16:26 ]:

**Comment by jgm** [comment]
The problem with the spurious links has now been fixed.
