### ISSUE TITLE
Raw TeX extension swallows spaces

### ISSUE THREAD

**Issue by baskerville** [jgm/pandoc#2687]
If `test.md` contains:
```
From \TeX to \LaTeX.
```
then `pandoc -t json test.md` yields:
```
[
  {
    "unMeta": {}
  },
  [
    {
      "t": "Para",
      "c": [
        {
          "t": "Str",
          "c": "From"
        },
        {
          "t": "Space",
          "c": []
        },
        {
          "t": "RawInline",
          "c": [
            "tex",
            "\\TeX "
          ]
        },
        {
          "t": "Str",
          "c": "to"
        },
        {
          "t": "Space",
          "c": []
        },
        {
          "t": "RawInline",
          "c": [
            "tex",
            "\\LaTeX"
          ]
        },
        {
          "t": "Str",
          "c": "."
        }
      ]
    }
  ]
]

```
You'll notice that the space after `\TeX` is not being rendered as `{"t":"Space","c":[]}`.

**Comment by jgm** [comment]
This is correct behavior, I think, because in LaTeX control
sequences swallow trailing space.  Try that in a LaTeX file
and you'll see.

You can try

    From \TeX{} to \LaTeX{}

or

    From \TeX\ to \LaTeX

+++ Bastien Dejean [Jan 29 16 04:50 ]:

**Comment by baskerville** [comment]
Thanks, but none of the suggested fixes work: `\TeX\ ` has the same output as `\TeX `, and `\TeX{} ` yields `{"t":"RawInline","c":["tex","\\TeX"]},{"t":"Str","c":"{}"},{"t":"Space","c":[]}`.

**Comment by jgm** [comment]
> \TeX{} yields
>   {"t":"RawInline","c":["tex","\\TeX"]},{"t":"Str","c":"{}"},{"t":"Space"
>   ,"c":[]}.

I guess this is because the LaTeX reader treats \TeX
specially.  Normally raw LaTeX commands would absorb
following arguments.  This could probably be changed in
the LaTeX reader.

>   Thanks, but none of the suggested fixes work: \TeX\ has the same output
>   as \TeX, and 

There needs to be a following space (and not at end of
line):

 % pandoc -f markdown -t json
\TeX\ and
[[1,16,1],{"unMeta":{}},[{"t":"Para","c":[{"t":"RawInline","c":["tex","\\TeX"]},{"t":"Str","c":"Â and"}]}]]

**Comment by baskerville** [comment]
Thanks, `\TeX\ ` is almost a solution, except that `\ ` generates a non-breaking space, not a regular space.

**Comment by jgm** [comment]
OK, you probably won't like this one, but it does work:

    \TeX&#32;and \LaTeX

+++ Bastien Dejean [Jan 30 16 01:59 ]:

**Comment by baskerville** [comment]
Yes it does.

It has a slight effect on readability though.

**Comment by jgm** [comment]
I think the cleanest solution is to change the inlineCommand
function exported by the LaTeX reader, so that
`{}` trailing a command like `\TeX` gets consumed.

**Comment by baskerville** [comment]
Great!
