### ISSUE TITLE
YAML frontmatter gets broken when converting between markdown formats

### ISSUE THREAD

**Issue by alexconst** [jgm/pandoc#2688]
Given the file
~~~yaml
---
title:  'Hello'
author: 'Someone'
date:   '2016-01-29'
---

# chap 1

hello
~~~

when converting between markdown formats using the command
`pandoc -S -f markdown_github+yaml_metadata_block -t markdown_github+yaml_metadata_block --atx-headers -s yaml.md -o  yaml.markdown`

the YAML section closure is done via "..." instead of the original "---", which breaks several interpreters. In particular Jekyll.
YAML section fences should be done either with what was originally specified in the input document or with "---" which seems to be the standard in other tools.

**Comment by jgm** [comment]
Dup of #2668
