### ISSUE TITLE
Problem with links from docx/odt to markdown

### ISSUE THREAD

**Issue by Pullusb** [jgm/pandoc#2689]
[linkmarkdown.docx](https://github.com/jgm/pandoc/files/111008/linkmarkdown.docx)
converting this document to markdown put a "\n" with an empty text link before each link and split unevenly when the link is a sentence.
The link is also made italic wich I don't want.
ex : 

```
the dvorak keyboard (where the link is 'dvorak')
the[
](link)[*dvorak*](link)

the movie "le nom des gens". (where the link is ' "le nom des gens" ' )
The movie[
](link)[*"*](link)[*L*](link)[*enom des gens"*](link)
```

Note: this docx file was downloaded from a google doc.

**Comment by jkr** [comment]
Weird -- they're actually different links in the docx xml file. I can collapse them, but that would only work if they go to the same place. I guess adjacent links to the same place should be collapsed in general. I wonder if this is something about how word handles French? Any way, thanks for reporting this -- I'll let you know as soon as I figure out the best way to proceed.

**Comment by Pullusb** [comment]
Actually, when I write directly the word document or a google doc with links, the file is clean and the links are processed correctly by pandoc.
I know why the file is faulty.
It was originally a copy/paste from a text with links already generated by a markdown (on [my ghost blog](http://blog.samuelbernou.fr/combattre-le-standard-azerty-keyboard/)). It seems that the copy of this document create multiple links where it's suppose to be only one. Maybe the markdown/text conversion of the ghost platform isn't clean...

**Comment by jkr** [comment]
Well, the docx reader should be robust against these things anyway, since documents come from all sorts of sources. I have a fix almost ready to push -- just fixing up a couple of function names. Is it okay if I use part of the file above as a test case?

**Comment by Pullusb** [comment]
No problem, feel free to use it.
