### ISSUE TITLE
Conversion to EPUB should support meta elements inside the OPF metadata block

### ISSUE THREAD

**Issue by ghost** [jgm/pandoc#269]
Running the following command:

```
pandoc -o mybook.epub --epub-cover-image images/cover.png intro.markdown ch1.markdown
```

produces a `content.opf` file with the following OPF metadata block:

```
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
  <dc:title>My Book</dc:title>
  <dc:language>en-US</dc:language>
  <dc:identifier id="BookId">urn:uuid:b4221f3d-b14a-4f78-b4c2-3a7a414b5b0d</dc:identifier>
  <dc:creator opf:role="aut">Kelsey Hightower</dc:creator>
</metadata>
```

This works, but both the Kindle (after running kindlegen) and Nook (.epub) omit the cover image when the follow element is missing:

```
<meta name="cover" content="cover-image" />
```

Pandoc should include the above element when using the `--epub-cover-image` option.

```
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
  <dc:title>My Book</dc:title>
  <dc:language>en-US</dc:language>
  <dc:identifier id="BookId">urn:uuid:b4221f3d-b14a-4f78-b4c2-3a7a414b5b0d</dc:identifier>
  <dc:creator opf:role="aut">Kelsey Hightower</dc:creator>
  <meta name="cover" content="cover-image" />
</metadata>
```

A more generic solution is to support meta elements in addition to the Dublin Core metadata elements inside the OPF metadata block.

I'm running a development version of Pandoc.

```
Git Commit: 9b5f1cba212f77c2aa3c6b28cbb3c000d805fcd8
```

Below is a pretty good link to a blog post that attempts to explain some best practices for epub cover images.

http://blog.threepress.org/2009/11/20/best-practices-in-epub-cover-images/

**Comment by jeffmcneill** [comment]
I have this same issue, namely meta elements (except for the cover) do not appear to be supported in metadata.xml. Specifically, I am trying to add the popular calibre:series and calibre:series_index tags:

<meta name="calibre:series" content="Classics on War and Politics"/>
<meta name="calibre:series_index" content="2.0"/>

These are not pulled into the content.opf file when generating an epub.

Is there a different process I should be using to include these meta tags (YAML file or something else)?
