### ISSUE TITLE
Czech quotes in backtics inline code block break LaTeX with listings

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#2690]
I was creating a document that talks about different quotation characters and I was trying to use backticks inline code block to make sure they make it into the resulting document un-smarted, since I am also using `--smart`. Here is my reduced test case:

~~~~
Talking about straight quotes (`""`). And here I am talking about Czech quotes (`„“`).
~~~~

If I try to process this into a PDF using `pandoc --listings --smart --self-contained -f markdown -t latex -o test.pdf test.md`, I will get the following error:

~~~~
! Package inputenc Error: Unicode char \u8:�\lst@EC�\lst@EC� not set up for use
 with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.56 about Czech quotes (\lstinline!„“!
~~~~

Is this a LaTeX problem? Is this a Pandoc (template?) problem?

**Comment by jgm** [comment]
Generally you need to use `--latex-engine=xelatex` if you've got non-ASCII characters in your document.
There may also be issues with unicode + listings. See
http://tex.stackexchange.com/questions/24528/having-problems-with-listings-and-utf-8-can-it-be-fixed
for example.

**Comment by wilx** [comment]
I have probably worked around this issue or it has been fixed by using XeLaTeX. I am closing this.
