### ISSUE TITLE
iBook version tag

### ISSUE THREAD

**Issue by jamtur01** [jgm/pandoc#2693]
If you version an iBook and submit updates Apple expects you to increment the version. In the current ePub metadata there's no way to specify a version. The suggested approach is:

Perhaps the thing to do is to allow YAML metadata to contain an ibooks
field, which is a map:

```
ibooks:
  version: 1.3.4
```

If this is included, meta tags are created in the ibooks namespace,
like

```
<meta property="ibooks:version">1.3.4</meta>
```

We might also restrict the fields that are included to the ones
that are explicitly allowed.

We'd also have to add the ibooks prefix to the containing package tag
if any ibooks fields are included. 

(From [this discussion](https://groups.google.com/forum/#!topic/pandoc-discuss/sWtffDYXE_Q)).

**Comment by jgm** [comment]
Can you link to some official documentation on the ibooks:version meta property for EPUBs?
What other properties live in the ibooks namespace?

**Comment by jamtur01** [comment]
Apple's iBook docs are:

https://itunesconnect.apple.com/docs/iBooksAssetGuide5.1Revision2.pdf

There's a Book Versioning section.

**Comment by jgm** [comment]
Looks like we have
```
ibooks:specified-fonts true|false (default false)
ibooks:ipad-orientation-lock portrait-only|landscape-only
ibooks:iphone-orientation-lock portrait-only|landscape-only
ibooks:binding true|false (default true)
ibooks:version (string)
ibooks:scroll-axis: vertical|horizontal|default
```
