### ISSUE TITLE
Can't make this to work, could someone help convert mediawiki export.xml to html?

### ISSUE THREAD

**Issue by Shadesss** [jgm/pandoc#2696]
Sorry I'm a noob and I'd like to move my mediawiki to wordpress but haven't been able to figure out how to convert mediawiki markup to html. I would love if someone could help me out. I could even tip you a few € if it works and I can actually get my wiki pages to wordpress.

**Comment by jgm** [comment]
This is the bug tracker -- for questions like this, please
use the pandoc-discuss mailing list (google groups).

https://groups.google.com/forum/#!forum/pandoc-discuss

+++ Shadesss [Feb 03 16 10:01 ]:
