### ISSUE TITLE
Inconsistency in language of a footnote to <div lang="xx">

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2702]
If I put a footnote on a `<div lang="xx">`, there is inconsistency in various output formats as to the language of a footnote to this section.

## HTML

```
pandoc -t html5 << EOT

<div lang="fr">
C'est un test.[^test]
</div>

[^test]: Test footnote.

EOT
```

Output:

```html
<div lang="fr">
<p>C'est un test.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></p>
</div>
<section class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Test footnote.<a href="#fnref1">↩</a></p></li>
</ol>
</section>
```

## LaTeX

```
pandoc -t latex << EOT

<div lang="fr">
C'est un test.[^test]
</div>

[^test]: Test footnote.

EOT
```

Output:

```latex
\begin{french}

C'est un test.\footnote{Test footnote.}

\end{french}
```

**Comment by jgm** [comment]
Sorry, what's the inconsistency?  And what do you mean by
"the language of a footnote"?

**Comment by adunning** [comment]
In the HTML output, the footnote falls outside the language definition and is thus defined as the main language of the document; in LaTeX, because the footnote is placed inline in an environment, it is defined as the language of the environment.

**Comment by jgm** [comment]
Solution:  Put a `<div lang="fr">` around the contents of
the footnote.

It actually seems like a nice feature that the footnote
language isn't determined by the main text language.

+++ Andrew Dunning [Feb 07 16 09:09 ]:

**Comment by adunning** [comment]
Thanks for the suggestion, and I agree; the HTML is what I'm looking for. I used a `<span>` instead of a `<div>` to prevent the footnote text from being affected in the LaTeX version, but I'm not sure whether there's anything Pandoc can really do to ensure consistency.
