### ISSUE TITLE
Plain text reader

### ISSUE THREAD

**Issue by ryandesign** [jgm/pandoc#2705]
I know pandoc can write plain text files, but is there a reason why pandoc cannot *read* plain text files?

I have plain text documents that I wish to convert to markdown, textile and/or asciidoc, and I am not familiar with all the special formatting capabilities of those languages, such that my valid plain text documents might contain syntax which might be interpreted as formatting in those languages, which I would not want. I want a program like pandoc, which knows what those rules are, to be able to add the necessary escaping and conversion so that my converted plain text document looks the same when viewed in a markdown / textile / asciidoc viewer.

I'm currently using a php script that runs `nl2br(htmlspecialchars($input))` to turn my plain text into html, which I then run through pandoc to convert to my output format, but pandoc should be able to read plain text on its own without an intermediary.

**Comment by jgm** [comment]
Well, _some_ formatting is surely desired -- you do at least
want to split consecutive text blocks into paragraphs, don't
you?

+++ Ryan Schmidt [Feb 08 16 14:53 ]:

**Comment by ryandesign** [comment]
> Well, _some_ formatting is surely desired -- you do at least
> want to split consecutive text blocks into paragraphs, don't
> you?

I just want my plain text content to appear as faithfully reproduced as possible when viewed in a GitHub Markdown context, such as a GitHub issue. Whatever is necessary to accomplish that.

This means multiple consecutive newlines or spaces should be preserved, any punctuation that would be interpreted as Markdown formatting codes should be escaped so that such formatting does not take place, etc.

This plain text content is from an old Bugzilla issue tracker that I'm trying to programmatically import into GitHub Issues. The content includes patches pasted inline, so punctuation and whitespace, including leading spaces, are significant and should not be discarded or mangled.

**Comment by jgm** [comment]
+++ Ryan Schmidt [Mar 24 16 03:11 ]:
>     Well, some formatting is surely desired -- you do at least
>     want to split consecutive text blocks into paragraphs, don't
>     you?
>
>   I just want my plain text content to appear as faithfully reproduced as
>   possible when viewed in a GitHub Markdown context, such as a GitHub
>   issue. Whatever is necessary to accomplish that.
>
>   This means multiple consecutive newlines or spaces should be preserved,
>   any punctuation that would be interpreted as Markdown formatting codes
>   should be escaped so that such formatting does not take place, etc.

OK!  Try this:

    echo "```" > out.md
    cat in.txt >> out.md
    echo "```" >> out.md

Your content will appear exactly as it appears in the input
file, including spacing.

**Comment by ryandesign** [comment]
I am considering doing something like this, but you're assuming the input text does not contain the line "\```". That's probably a safe assumption in my case, but the job of a conversion tool should be to know what syntax constitutes formatting instructions for the output language, and to properly escape the input so that undesired formatting doesn't take place. That is why I am looking for a conversion tool like pandoc to handle the conversion, and why I'm still not sure why pandoc doesn't support reading plain text content—the most basic and universal of all content.

**Comment by jgm** [comment]
If you're worried about this, you could simply add a 4-space
indent to the beginning of every line.  That's another way
of turning the whole thing into a big code block.

>   pandoc to handle the conversion, and why I'm still not sure why pandoc
>   doesn't support reading plain text content—the most basic and universal
>   of all content.

I've already explained that.  It's not really clear what
sort of formatting is wanted in plain text.  If you're
content having the whole thing treated like a giant code
block, then the method I described would work and is easy.
This behavior could be made into a special pandoc writer,
but it hardly seems worth it.  And many other people would
have different expectations for how "plain text" input is to
be treated.  (They might want to think of it, for example,
as a sequence of paragraphs.)
