### ISSUE TITLE
pandoc-1.16.0.2 test suite fails when compiling with shared executables enabled

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#2709]
We see the following errors during the build when compiling with Nix and GHC 7.10.3 on Linux:

```
Running 1 test suites...
Test suite test-pandoc: RUNNING...
/tmp/nix-build-pandoc-1.16.0.2.drv-0/pandoc-1.16.0.2/dist/build/pandoc/pandoc: error while loading shared libraries: libHSpandoc-1.16.0.2-62DUPRWXdeYC7y2x3V2yux-ghc7.10.3.so: cannot open shared object file: No such file or directory
```

**Comment by jgm** [comment]
Can you give me the stack incantation to compile with
shared libraries?

+++ Peter Simons [Feb 12 16 11:54 ]:

**Comment by peti** [comment]
Unfortunately, I don't know how to do that either.

**Comment by juhp** [comment]
(It might be a good stack RFE.)

**Comment by peti** [comment]
Has there been any progress fixing this issue?

**Comment by jgm** [comment]
No.  I have never done anything with shared libraries in Haskell.  If someone wants to help give me the stack incantation to compile with shared libraries, I could look into it further.   But this isn't a high enough personal priority for me to work on without some help from someone for whom it matters.

**Comment by RyanGlScott** [comment]
Based off of the build output from http://hydra.cryp.to/build/1671146/nixlog/2/raw, I managed to reproduce the error using `cabal-install`:

```
$ cabal get pandoc                                      
Unpacking to pandoc-1.17.1/                                                               
$ cd pandoc-1.17.1/
$ cabal install --only-dependencies
$ cabal configure --enable-executable-dynamic
$ cabal build
$ dist/build/pandoc/pandoc --help
dist/build/pandoc/pandoc: error while loading shared libraries: libHSpandoc-1.17.1-55fbhFDS4m8AKo7bzCoEJA-ghc8.0.1.so: cannot open shared object file: No such file or directory
```

So it's not really the test suite that's failing, just the fact that it invokes the failing `pandoc` executable.

`stack` doesn't have an `--enable-executable-dynamic` flag AFAICT, so I'm not sure how to reproduce the issue with `stack`.

**Comment by jgm** [comment]
I think the problem is clear.  The test suite runs the
executable from the build directory.  Since the shared
library hasn't been installed yet (and shouldn't be
prior to testing!), the executable can't find it when it
needs to load it.

We could probably fix this by having the test suite set
the shared library load path in the environment when
it calls 'pandoc'.  DYLD_LIBRARY_PATH or
DYLD_FALLBACK_LIBRARY_PATH on OSX, LD_LIBRARY_PATH on linux.

+++ Ryan Scott [Jun 17 16 06:57 ]:

**Comment by jgm** [comment]
PS. the relevant changes would be in tests/Tests/Old.hs
line 264.  The only difficulty is in determining where
the dynamic library is to be found.
