### ISSUE TITLE
Issues with latexmathml, mathjax, and markdown_github format

### ISSUE THREAD

**Issue by alexconst** [jgm/pandoc#2712]
math.md
```
1) foo \(x_i^2\) bar 

2) foo \[E = mc^2\] bar 

3) foo $x+1$ bar 

4) foo $$z+w$$ bar 
```
With `markdown_github` and `latexmathml` only 1) and 2) work fine.
~~~
pandoc -s -f markdown_github --latexmathml math.md -o math.html && firefox !!:$ 
~~~
Without `markdown_github` and with `latexmathml` only 3) and 4) work fine.
~~~
pandoc -s  --latexmathml math.md -o math.html && firefox !!:$ 
~~~
With `markdown_github` and `mathjax` 3) does not work.
~~~
pandoc -s -f markdown_github --mathjax math.md -o math.html && firefox !!:$ 
~~~

In case it's relevant, my two use cases:
1) I'm using markdown with extensions which I convert to html for local use. Format: `markdown_github+footnotes+pandoc_title_block+yaml_metadata_block`
2) But some files also get converted to Jekyll markdown (still markdown_github format but with some option tweaks) to be hosted on GitHub Pages, which [will only support kramdown](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0). And kramdown uses MathJax.

For my 1) case I'd like to use LatexMathML since that seems to be the only offline option.
But for 2) I will need to use MathJax. (I tried to use MathJax locally but no luck)
So using a common idiom for writing mathematical expressions is relevant. Using the `$...$` and `$$...$$` syntax is also more convenient.

The problem is currently neither LatexMathML nor MathJax are working for me. (bugs?)

So are there any offline options with TeX shorthand support?

**Comment by jgm** [comment]
It's best to use `$...$` or `$$...$$` in your source
file to mark out math.  The `\(..\)` and `\[..\]` that
currently works in markdown_github will not work any longer
after this release (due to changes in gh's markdown), though
you'll still be able to use `+tex_math_single_backslash` as
an extension.

MathJax by default expects the `\(..\)` or `\[..\]` forms,
though I believe this can be configured in MathJax itself.
So the pandoc `--mathjax` option will cause this to be used
in HTML output.

The reason 3 isn't working with `--mathjax` + `-f
markdown_github` is that `markdown_github` doesn't
parse `$..$` as math, so pandoc doesn't know to re-render
this as `\(..\)`.

Try `--mathjax -f markdown_github+tex_math_dollars`.


+++ Alexandre Constantino [Feb 14 16 04:45 ]:

**Comment by alexconst** [comment]
> It's best to use \`$...$\` or \`$$...$$\` in your source file to mark out math.

That doesn't work for me, independently of using mathjax or latexmathml.

Did find the answer to [mathjax 3) not working ](https://docs.mathjax.org/en/v2.6-latest/tex.html)

>  It also defines the TeX delimiters $$...$$ for displayed equations, but it does not define $...$ as in-line math delimiters. That is because dollar signs appear too often in non-mathematical settings

Which kind of sucks (given that it is supported in [SO mathjax](http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference), but that's another story).
But that raises a problem. It means \`$...$\` will not work.
It's kind of strange that github will discontinue \`\\(..\\)\` and \`\\[..\\]\` since it uses kramdown, which uses mathjax, and mathjax doesn't work with \`$...$\`.

**Comment by jgm** [comment]
+++ Alexandre Constantino [Feb 14 16 10:08 ]:
>     It's best to use `$...$` or `$$...$$` in your source file to mark
>     out math.
>
>   That doesn't work for me, independently of using mathjax or
>   latexmathml.

Well then, you can use the `tex_math_single_backslash`
extension, as I noted.

**Comment by alexconst** [comment]
But on which situations do the \`$...$\` or \`$$...$$\` notation work?

**Comment by alexconst** [comment]
Is it then a bug that $...$ and $$...$$ don't work with `--latexmathml`?
FWIW I'm using Pandoc's own LaTeXMathML.js.

I checked the html source in Firefox and there are no `<span class="LaTeX">` tags for the text between the dollar signs.

**Comment by jgm** [comment]
If you want to use `$`, then use

    pandoc --latexmml -f markdown_github+tex_math_dollars

**Comment by alexconst** [comment]
Thanks!
That solved it.
