### ISSUE TITLE
Org to mediawiki: File links with colons

### ISSUE THREAD

**Issue by marcbowes** [jgm/pandoc#2713]
In Org, if I have this:

``` org
[[file:User:Me/about][About]]
```

Then it becomes this after being converted to mediawiki:

``` mediawiki
[User:Me/about About]
```

It should have become:

``` mediawiki
[[User:Me/about About]]
```

The "User:Me" example is used because that is the common practice for user pages in mediawiki.

**Comment by tarleb** [comment]
I currently maintain the org reader, sorry for not getting back to you earlier.  This is an instance of the general impedance mismatch between markup languages. Mediawiki allows a nice way to write and distinguish between external and wiki links.  This isn't the case in markup languages designed for more general (i.e. non-wiki) use. Gitit/Pandoc use the convention of empty links `[[][User:me/about]]` to allow for wiki links.  I'm not aware of a way to write wiki links with labels different from the wiki page they link to.

**Comment by tarleb** [comment]
I'm unsure how the org reader should behave here.  I see two solutions: 1. allow `wikilink:` to be used as a special URI schema and add *wikilink* as a title (like the MediaWiki reader does), or 2. leave as is and leave this kind of processing to filters, which should be fairly easy to write. My preference is on the first idea.

However, there is another issue here: using the MediaWiki reader and writer, ` [[User:about/me|About]]` becomes `[User:about/me About]`, thus just changing the org reader won't fix the problem.  I'm not too familiar yet with MediaWiki markup but will look into this.
