### ISSUE TITLE
Unicode Characters are turned into Tex escape sequences even when XeTeX or LuaTeX are used

### ISSUE THREAD

**Issue by AlfredSchmitt** [jgm/pandoc#2715]
It would be nice to have an option that allows to turn of this behaviour so that for example “…” would not be turned into “\ldots{}”

**Comment by jgm** [comment]
Pandoc's LaTeX writer currently tries to produce LaTeX that can be processed with any of the processors.  That is, the `--latex-engine` option doesn't affect the LaTeX that is produced; it only affects the program used to convert it to PDF.  The LaTeX uses `\ifxetex` and the like to conditionally include different bits for different processors.

Implementing your suggestion would require changing this approach, and generating different LaTeX depending on the value of `--latex-engine`.
