### ISSUE TITLE
html to plain text includes formatting symbols

### ISSUE THREAD

**Issue by meldavis** [jgm/pandoc#2717]
When converting html to plain text, the no-highlight option should omit any formatting symbols:

For example, converting the following html:
`<strong>Hello, world</strong>`
`<em>Goodbye, world</em>`

appears as:
`HELLO, WORLD`
`_Goodbye, world_`

But, I would expect to see:
`Hello, world`
`Goodbye, world`

**Comment by jgm** [comment]
You're using an old version of pandoc, apparently.  Current
output would be

    HELLO, WORLD

+++ meldavis [Feb 15 16 14:27 ]:
