### ISSUE TITLE
LaTeX writer: internal links broken for documents assembled from multiple fragments

### ISSUE THREAD

**Issue by johguenther** [jgm/pandoc#2719]
We build one large pdf via `pandoc` and LaTeX from multiple markdown files (one per chapter), where each source file is converted separately to `.tex` first. Internal links in the final pdf from one chapter to (sections of) other chapters are broken.
The reason is that pandoc's LaTeX writer creates `\hypertarget` anchors only for sections which it sees a reference to -- it cannot see the references from the other chapters that are converted separately. Still, these links worked before commit d5efa9b3, because the then used `\hyperref` links simply targeted the always generated `\label`. 
Converting all `.md` files in one go creates all links, but does not work for us, because we use different `pandoc` options for the different chapters.
So, one solution could be to always create `\hypertarget` for sections, similar to #871.

**Comment by johguenther** [comment]
Any thoughts on this? The issue is still present in v1.17.2.

**Comment by jgm** [comment]
Looks like we're a bit inconsistent on this.  Code blocks with identifiers get hyper targets no matter what.  I think I'd be okay with changing the behavior generally so it's not sensitive to the presence of an actual link.  Would anyone object?

**Comment by boisgera** [comment]
That change would be welcome!
