### ISSUE TITLE
emf aspect ratio unequally scaled to 1.2 w: 1 h in docx (pandoc 1.16.0.2, Mac OS X)

### ISSUE THREAD

**Issue by rfhb** [jgm/pandoc#2720]
When rendering a R markdown document with plots using `device='emf'` into a docx document, all plots in the docx file are scaled to 69% height and 83% width. This does not depend on any setting of figure width or height in R. The rendering results in an undesirable aspect ratio, distorting the plots. In a word processor, the scaling would need to be reset for every plot manually. This is the command line: 

`pandoc Report.md --to docx --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Report.docx`

There is no relevant output using `--verbose`. Could this be a problem with the image size detection? Using pandoc 1.15, the type and size of emf files was not detected at all by pandoc (the error message was `pandoc: Could not determine image size in 'RMarkdownReport_files/figure-docx/figure-1.emf': could not determine image type`. 

In any case it would be preferred if the docx writer would not set any image size for the emf file. Thanks.

**Comment by jgm** [comment]
I can't help at all without having a simple example I can
test with, using plain pandoc.  Can you link to or quote
as much of Report.md as is necessary to reproduce the issue?

**Comment by mb21** [comment]
Pandoc currently can't determine the dimensions of [emf / Windows Metafile](https://en.wikipedia.org/wiki/Windows_Metafile) images. I'm not sure whether it's unusual that RMarkdown produces an `emf` file, or that the output format (`docx` in this case) requires the dimensions to be read out, but I suspect it's the latter. Can you configure RMarkdown somehow to generate Png, Gif, Jpeg, Pdf or Eps?

**Comment by rfhb** [comment]
A minimal example is in Archiv.zip (Report.md, without size information; the EMF graphic and the rendered docx file; also a screen shot for the formatting window of the word processor is included showing the unequal scaling). 

I understand that EMF is not supported and have switched to postscript / EPS. Sorry for raising this; I was intrigued by the error message disappearing when updating to 1.16 and did not check for supported formats. 

[Archiv.zip](https://github.com/jgm/pandoc/files/134508/Archiv.zip)

**Comment by mb21** [comment]
pandoc 1.16 doesn't emit the `Could not determine image size` error anymore? interesting... I think that's due to the `either (const def)` [in the Docx writer](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Docx.hs#L1123), which @jgm introduced in https://github.com/jgm/pandoc/commit/622f09617e7ecac86024a0e63f4371112e315e2e

**Comment by rfhb** [comment]
Have documented a work around which works for me to use EMF graphics from Rmarkdown rendered into docx: https://github.com/rfhb/rmarkdownknitrpandocemf.
