### ISSUE TITLE
Problem with math inline and markdown

### ISSUE THREAD

**Issue by felixsanz** [jgm/pandoc#2722]
I was parsing this piece of markdown: `bla bla bla **35$** bla bla bla`.

And pandoc converted it to `35<span class="math inline>* *`

In some countries the symbol is placed after the number.

Why is $** being interpreted as math ?

**Comment by jgm** [comment]
See http://pandoc.org/README.html#math

You can turn this off, though.  Use

   pandoc -f markdown-tex_math_dollars

Or you can escape the `$` as `\$`.

+++ Felix Sanz [Feb 17 16 07:56 ]:

**Comment by felixsanz** [comment]
Thanks! the readme is so big for remembering everything :P
