### ISSUE TITLE
How to create a link near a header for itself?

### ISSUE THREAD

**Issue by felixsanz** [jgm/pandoc#2723]
for example: `#1 Title`

gets translated to: `<h1 id="title">Title</h1>`

How i can convert that into: `<h1 id="title"><a class="anchor" href="#title"></a>Title</h1>` ?

Like GitHub does, so you can get permalinks at that place.

**Comment by Jmuccigr** [comment]
It is an anchor already: document_name.html#title will get you there. See, for example, http://www.w3.org/TR/html401/struct/links.html#h-12.2.3

**Comment by felixsanz** [comment]
I know it's an anchor, but i want the <a> tag so users can right-click and copy link

**Comment by ousia** [comment]
@felixsanz, I’m afraid I cannot provide you the code.

But since the purpose is so special, isn’t it a task for a filter?

**Comment by felixsanz** [comment]
Well... i didn't know about filters, but i can't get it to work anyway:

[Error: pandoc exited with code 2: pandoc: unrecognized option `--no-highlight --filter /srv/http/filter.js'
Try pandoc --help for more information.
]

my code is:

```
#!/usr/bin/env node

import pandoc from 'pandoc-filter'
const str = pandoc.Str

function action(type, value, format, meta) {
  if (type === 'Str') return str(value.toUpperCase())
}

pandoc.stdio(action)
```

Can someone help please?

**Comment by jgm** [comment]
+++ Felix Sanz [Feb 18 16 07:33 ]:
>   I know it's an anchor, but i want the tag so users can right-click and
>   copy link

I think the best approach is to add some javascript that
adds the anchor links to all header elements.
