### ISSUE TITLE
LaTeX writer shouldn't trigger `--chapters` for all memoir files

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#2726]
The memoir class (as the manual suggests) should be able to emulate the article class as well as book. It offers the `article` document option for this (eg `\documentclass[oneside,article]{memoir}`). Many memoir templates out in the wild are used for article-like styles as well, using this option.

What would you think of something like the code below to check to see if it has `article` in the square-bracket options, and triggering article if so? That would go for anything with the article option (not just memoir) but that's probably okay. It works for my use-case. If it makes sense to you I could put together a test case and either submit as a PR or just push.

~~~{.haskell}
  let documentClass = case P.parse (do P.skipMany (P.satisfy (/='\\'))
                                       P.string "\\documentclass"
                                       classOptions <-
                                         (do P.spaces
                                             P.char '['
                                             P.sepBy (P.many (P.satisfy (\c -> c /= ',' && c /= ']'))) (P.char ','))
                                         <|>
                                         return []
                                       if ("article" :: String) `elem` classOptions
                                         then return "article"
                                         else do P.skipMany (P.satisfy (/='{'))
                                                 P.char '{'
                                                 P.manyTill P.letter (P.char '}')
                                   ) "template"
~~~

**Comment by jkr** [comment]
Forgot to mention: part of the reason this is needed beyond just doing the right thing, is that `--base-header-level=2` doesn't seem to carry to the generated reference header. That's a bug, right?

**Comment by jgm** [comment]
A bit ugly, but...makes sense to me.

**Comment by jkr** [comment]
Closing with 4112b321
