### ISSUE TITLE
Polyglossia environment variables printing with Babel

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2728]
When Pandoc 1.16.0.2 sets additional options for Polyglossia, these are not hidden from Babel. For example:

```
pandoc -o test.pdf << EOT
<div lang="en-CA">Test.</div>
EOT
```

PDF output contains:

```
variant=canadian]
Test.
```

**Comment by mb21** [comment]
The reason

    \begin{english}[variant=canadian]
    Test.
    \end{english}

doesn't work was

    \newenvironment{english}[1]{\begin{otherlanguage}{canadian}}{\end{otherlanguage}}

which should be

    \newenvironment{english}[2][]{\begin{otherlanguage}{canadian}}{\end{otherlanguage}}

see pull request. Hope this fixes it without breaking anything, but pretty confident...

**Comment by adunning** [comment]
That indeed takes care of it; thank you! It also seems that if I mix two variants of one language, it only generates Babel commands for the first of them, but I suppose that's a separate issue.

**Comment by mb21** [comment]
yeah, I haven't found a way to generate `\newenvironment`s that take the variant into account (probably you'd have to generate an `if/else` within the `\newenvironment`). Frankly, I was surprised this works as well as it seems to be..

**Comment by adunning** [comment]
Had you intended to submit that patch as a pull request?

**Comment by mb21** [comment]
@adunning indeed, thanks for the heads-up!
