### ISSUE TITLE
Don't buffer stderr of --filter

### ISSUE THREAD

**Issue by Warbo** [jgm/pandoc#2729]
When calling external filter programs, e.g. `pandoc --filter foo < input > output` the program `foo` will be executed, and all of its standard error stream is captured to a Haskell variable `errbs` (see https://github.com/jgm/pandoc/blob/3b39b16a4b6d2d8078be27d0a1b3fc977c55731f/pandoc.hs#L149 ).

Once the program has finished executing, `errbs` is checked to see if it's empty; if not, its content is written to the the stderr of `pandoc`.

This buffering (waiting until the filter has finished before showing anything on stderr) can make debugging filters tedious. For example, if a filter takes a long time to run (e.g. it's doing a lot of IO), then we would like to be notified of any problems without having to wait for the whole thing to finish. Likewise, if there is a bug in a filter which is transforming a large number of elements, we have to wait until all of them have failed, and look through the whole output of all failures, rather than being able to spot the error immediately after the first failure.

In particular, I use a Pandoc filter called "panpipe" which allows arbitrary shell commands to be executed ( http://chriswarbo.net/git/panpipe/branches/master/ , described in more detail at http://chriswarbo.net/essays/activecode ), and use it to run many resource-intensive scripts. To avoid having to wait for stderr, I must use `pandoc -t json | panpipe | pandoc -f json` rather than `pandoc --filter panpipe`.

The `errbs` variable doesn't seem to be used for anything else, so it could simply be removed, along with a corresponding change to the `Text.Pandoc.Process.pipeProcess` function. The required change would be around https://github.com/jgm/pandoc/blob/3b39b16a4b6d2d8078be27d0a1b3fc977c55731f/src/Text/Pandoc/Process.hs#L63 where `std_err = Inherit` should be used rather than `std_err = CreatePipe` (as per https://hackage.haskell.org/package/process-1.4.2.0/docs/System-Process.html#t:StdStream ).

It looks like the only other user of the `pipeProcess` function is the `Text.Pandoc.PDF` module, which hides all output of conversion processes (including stderr) unless the `verbose` variable is `True`.

Perhaps a simpler and neater solution would be passing the `verbose` flag into `pipeProcess`, and doing something like `std_err = if verbose then Inherit else NoStream`. That way, the `System.Process` module will be doing all of the work: when output it wanted, it will be given immediately without buffering; when it's not wanted, it will never be stored at all; and in either case, all of the custom IO code for handling stderr can be deleted.

If this sounds reasonable, I may take a stab at implementing it.

**Comment by jgm** [comment]
I think that makes a lot of sense.  Of course, we may see
a difficulty after you've implemented it, but I think it
makes sense to implement it as you suggest.

**Comment by jgm** [comment]
It's not as simple as I thought.  The PDF reader doesn't simply print stderr output (or discard it).  It analyzes the log messages in order to present to the pandoc user just the relevant part, without the full output, which can be confusing.

So probably the best approach is to offer an alternative version of pipeProcess (say, pipeProcessStreamingStderr) that streams stderr instead of returning it.

**Comment by jgm** [comment]
It turns out latex log output goes to stdout.
So I'm going to change the pipeProcess signature.
Since this is an API change, I'm doing it in the `typeclass` branch, so it will be in pandoc 2.0.
