### ISSUE TITLE
Line breaks in YAML header?

### ISSUE THREAD

**Issue by baskerville** [jgm/pandoc#2731]
Let's consider the following header:

```
---
title: "Amusing Ourselves to Death"
subtitle: "Public Discourse in the Age of Show Business"
author: "Neil Postman"
date: "1985"
---
```

When it gets translated to ePub3, the title or the subtitle might end up badly split, because of word wrapping.

Is there a way to express `<br/>` in the YAML header?

I tried using nonbreaking spaces for everything but the acceptable split points (while specifying `hyphens: none;` in the stylesheet) but it doesn't work.

**Comment by ousia** [comment]
@baskerville,

`&#13;` is the Unicode character for carriage return. But if `&#160;` (no-break space) didn’t work, this may not work either.

My impression is that the issue is caused by the software reading the ePub3 file.

Could you provide information about the reader (_iBooks_ or which one?) and how the title is split?

If a word is hyphenated in the title (I’m only guessing), maybe you should add to your CSS file:

``` css
h1, h2, h3, h4, h5, h6 {
    -epub-hyphens: none;
    -webkit-hyphens: none;
}
```

It is a typographic convention not to hyphenate headings.

**Comment by baskerville** [comment]
Thanks: the given CSS makes the non-breaking space approach work (both with iBooks and an e-reader).

**Comment by jgm** [comment]
You could try:

```
subtitle: |
  Public Discourse in the\
  Age of Show Business
```

If you're targeting HTML/EPUB, then this should also work:

```
subtitle: Public Discourse in the<br/>Age of Show Business
```

**Comment by javadba** [comment]
None of the above approaches are working in the current pandoc running on os/x high sierra. Here is my command

Tried:

> title: Machine Learning Platform\
> Configuration via XML/DTD
> 

> title: Machine Learning Platform&#13;Configuration via XML/DTD


> title: Machine Learning Platform<br/>Configuration via XML/DTD

The first one fails altogether 
"[WARNING] Could not parse YAML metadata at line 1"

The others simply have no effect.

**Comment by tarleb** [comment]
@javadba, please be aware that posting questions in closed issues is generally considered bad practice:

- *All* participants of the thread will get an email; not everybody is interested in helping with questions.
- It makes it more difficult to keep track of issues.
- Additionally, in the case of pandoc, posting questions to the issue tracker is frowned upon, as the tracker is reserved for bugs and feature requests.

Please direct your question to the pandoc-discuss mailing list.
