### ISSUE TITLE
png files cannot be embedded into .docx and .odt

### ISSUE THREAD

**Issue by chiffa** [jgm/pandoc#2736]
I am using pandoc on Windows and I am trying to convert an .rst file to a .docx file with a figure.

Here is the contents of my .rst file: 

```
.. figure:: my_image.png
    :alt: trying to get the image to work...
    :align: center
    :scale: 50
    :width: 50%


    **Figure 1**

    We are trying to embed a file into a .docx here
```

I tried the following commands

```
pandoc -o main.docx main.rst
pandoc -o main.odt main.rst
```

However if I replace my_image.png by my_image.jpg, the insertion is effected properly. 

I was unable to find anything in documentation or on the internet related to this. Is it a know behavior?

**Comment by jkr** [comment]
What happens when you run those commands? Is there an error? Or does the image just not show up in the output file?

**Comment by chiffa** [comment]
They do not appear in the output file.

**Comment by jgm** [comment]
Works fine for me. What version of pandoc are you using?

**Comment by chiffa** [comment]
```
pandoc 1.16.0.2
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.
```
