### ISSUE TITLE
Pandoc self-contained does not properly handle links to fonts in css

### ISSUE THREAD

**Issue by humburg** [jgm/pandoc#2737]
With Pandoc 1.16.0.2 the following conversion attempt fails:

```sh
echo '<link rel="alternate stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/bootswatch/3.0.0/amelia/bootstrap.min.css" title="Amelia" media="screen"></link>' > test.md
pandoc test.md --to html --from  markdown --self-contained --output out.html
```
producing this error:

```
pandoc: Could not fetch //fonts.googleapis.com/css?family=Lobster|Cabin:400,700
InvalidUrlException "//fonts.googleapis.com/css?family=Lobster%7CCabin:400,700" "Invalid URL"
```

Using pandoc 1.13.2 this seems to work as expected. Related to #1477

**Comment by jgm** [comment]
For posterity, the bug was introduced by ce5583460c9a936a70a05836cb9efb1021c06f2a
which was intended to prevent pandoc from treating `C:/` in a Windows path as a protocol.
It affects 1.16..1.16.0.2.

**Comment by humburg** [comment]
Thanks @jgm, that was very quick work.
