### ISSUE TITLE
Problem converted header containing unicode characters from markdown_github to html

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#2738]
markdown:
```
##### 测试
```
Convert from markdown_github to html and get the following output.
```
<h5>测试</h5>
```
Expect:
```
<h5 id="测试">测试</h5>
```

**Comment by jgm** [comment]
This is specific to `markdown_github`; `markdown` gives the ID.

**Comment by jgm** [comment]
Here's why.  `markdown_github` incorporates the extension `ascii_identifiers` (which forces ascii-only identifiers).  I'm not sure this is still desirable for github markdown; this needs looking into.
But you can do `-f markdown_github-ascii_identifiers` to turn this off.

**Comment by cnblogs-dudu** [comment]
Thanks.
