### ISSUE TITLE
Single quotation mark problem with Chinese characters

### ISSUE THREAD

**Issue by MegaThomas** [jgm/pandoc#2740]
I encountered this problem recently:
When I write
`中文‘中文’`
I get
``中文`中文'``, 
but if with a space before the first single quotation, things are different.
``中文 ‘中文’``produces``中文 \enquote{中文}``
Plus, I can't get single quotation mark too. I can only get `\enquote{blah}`.

the command I use is
`pandoc blah.pandoc -o blah.tex --latex-engine=xelatex --template=e:\pm-template.latex --number-section`
The result is the same even with the `--smart` option.

**Comment by jgm** [comment]
\enquote{..} is used for smart quotes in latex if your
template includes the csquotes package.  If you remove
\usepackage{csquotes} from your template, you should see
this behavior change.  (You need to relly remove it, not
just comment it out.)

+++ MegaThomas [Feb 26 16 23:38 ]:
