### ISSUE TITLE
ConTeXt, Whitespace, and Line Blocks 

### ISSUE THREAD

**Issue by c-forster** [jgm/pandoc#2744]
If I have the following markdown:

```markdown
| Fair fa' your honest, sonsie face,
|     Great Chieftain o' the Puddin'-race!
| Aboon them a' ye tak your place,
|            Painch, tripe, or thairm:
| Weel are ye wordy o' a *grace*
|            As lang's my arm.
```
And I convert it to ConTeXt, I get:

```context
Fair fa' your honest, sonsie face,\crlf
~~~~Great Chieftain o' the Puddin'-race!\crlf
Aboon them a' ye tak your place,\crlf
~~~~~~~~~~~Painch, tripe, or thairm:\crlf
Weel are ye wordy o' a {\em grace}\crlf
~~~~~~~~~~~As lang's my arm.
```

With LaTeX, I get:
```latex
Fair fa' your honest, sonsie face,\\
\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}Great
Chieftain o' the Puddin'-race!\\
Aboon them a' ye tak your place,\\
\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}Painch,
tripe, or thairm:\\
Weel are ye wordy o' a \emph{grace}\\
\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}\hspace*{0.333em}As lang's my arm.
```

The ConTeXt writer converts spaces in Line Blocks into nonbreaking spaces (`~`s), which don't get preserved as horizontal space when it is compiled to PDF.

**Comment by jgm** [comment]
Are there any ConTeXt experts out there who can suggest
better output?

+++ Chris Forster [Feb 28 16 19:43 ]:

**Comment by c-forster** [comment]
I corresponded with @denubis via email, who helped me come up with a solution that seems to work and is represented in https://github.com/jgm/pandoc/pull/2745

**Comment by Denubis** [comment]
It may be worth mentioning that ~\hspace[small] repeated can be replaced
with:
*\definehspace[fourspace][.5in]*
and *\hspace[fourspace]:*

See:
https://github.com/elotroalex/md-tex-jekyll/blob/master/sandbox/poetry.tex
and
https://github.com/elotroalex/md-tex-jekyll/blob/master/sandbox/poetry.pdf

**Comment by ousia** [comment]
> Are there any ConTeXt experts out there who can suggest better output?

I guess this is better (or at least, much simpler):

``` tex
\definelines[spacedlines][space=on]
\starttext
\startspacedlines
Fair fa' your honest, sonsie face,
    Great Chieftain o' the Puddin'-race!
Aboon them a' ye tak your place,
           Painch, tripe, or thairm:
Weel are ye wordy o' a {\em{}grace}
           As lang's my arm.
\stopspacedlines
\stoptext
```

BTW, no line breaks (`\crlf`) are needed.

But activating spaces requires `{\em{}grace}`. Otherwise, two spaces will be added.

**Comment by Denubis** [comment]
The problem (and we considered startlines) is that there's no lines mode in
|. Thus, the only knowledge we have is: "t":"LineBreak" where a linebreak
should occur, and a unicode character for spacing. If we were in modes,
yes, what you propose would be great.

**Comment by ousia** [comment]
> The problem (and we considered startlines) is that there's no lines mode in |. Thus, the only knowledge we have is: "t":"LineBreak" where a linebreak should occur, and a unicode character for spacing. If we were in modes, yes, what you propose would be great.

@Denubis, excuse me, I cannot code.

I cannot imagine what “lines mode in |” might be.

And “if we were in modes” is misleading to me (my fault). ConTeXt also has [modes](http://wiki.contextgarden.net/Modes).

**Comment by Denubis** [comment]
Sorry, let me try to restate from Chris's e-mail conversation where we
discussed this very thing.

| Fair fa' your honest, sonsie face,
|     Great Chieftain o' the Puddin'-race!
| Aboon them a' ye tak your place,
|            Painch, tripe, or thairm:
| Weel are ye wordy o' a *grace*
|            As lang's my arm.

[Para [Str "Fair",Space,Str "fa'",Space,Str "your",Space,Str
"honest,",Space,Str "sonsie",Space,Str "face,",LineBreak,Str
"\160\160\160\160Great",Space,Str "Chieftain",Space,Str "o'",Space,Str
"the",Space,Str "Puddin'-race!",LineBreak,Str "Aboon",Space,Str
"them",Space,Str "a'",Space,Str "ye",Space,Str "tak",Space,Str
"your",Space,Str "place,",LineBreak,Str
"\160\160\160\160\160\160\160\160\160\160\160Painch,",Space,Str
"tripe,",Space,Str "or",Space,Str "thairm:",LineBreak,Str "Weel",Space,Str
"are",Space,Str "ye",Space,Str "wordy",Space,Str "o'",Space,Str
"a",Space,Emph [Str "grace"],LineBreak,Str
"\160\160\160\160\160\160\160\160\160\160\160As",Space,Str
"lang's",Space,Str "my",Space,Str "arm."]]


There is nothing here to indicate to pandoc that a lineblock
<http://pandoc.org/README.html#line-blocks> exists *save* for the
"t":"LineBreak" -- which is distinct from the array which is passed to a
bulleted list. Thus, we must agnostically deal with the lineblock without
reference to other lines. (Which is a whole bunch of no fun at all).

Thus, while \startspacedlines is indeed correct from a ConTeXt point of
view, there is nothing to tell the parser to write \startspacedlines.

**Comment by ousia** [comment]
> Thus, while `\startspacedlines` is indeed correct from a ConTeXt point of view, there is nothing to tell the parser to write `\startspacedlines`.

Many thanks for your reply, @Denubis. It is is clear to me now.

**Comment by c-forster** [comment]
Thanks @ousia and @Denubis; I think it's probably better to stick with `\hspace[small]` because small is defined by default. Defining our own `hspace` value would let us be a bit more precise, but the definition (i.e. `\definehspace[fourspace][.5in]`) should really go in the file header. But the header is only output from with the `--standalone` flag. That is, there are a number of imaginable reasons why one would generate ConTeXt fragments, and those fragments should compile properly (rather than throw an error that they reference some undefined value). (We could use `medium`, but I think `small` is closest to the 0.333em used in the LaTeX writer.)

So, with those constraints (we can't use a `\startspacedlines`; and using custom values seems to carry a high cost), is this the best imaginable output for the example above?

```latex
Fair fa' your honest, sonsie face,\crlf
\strut~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]Great
Chieftain o' the Puddin'-race!\crlf
Aboon them a' ye tak your place,\crlf
\strut~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]Painch,
tripe, or thairm:\crlf
Weel are ye wordy o' a {\em grace}\crlf
\strut~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]As
lang's my arm.
```

**Comment by Denubis** [comment]
I admit to some confusion over the use of both the non-breaking space *and*
hspace small. Both are valid responses, but insofar as typing one space
should create one space, it feels like both combined are problematic. The
only critical component is the intentional strut after the crlf. Your
justification of the use of a predefined unit seems entirely wise, and
advocating for \hspace[small] so that we're not introducing spaces (Which
are then copied) into the document also seems wise.

**Comment by c-forster** [comment]
So, I'm kind of just wildly stabbing in the dark w/r/t ConTeXt (with which I am not familiar and, I've learned, is *significantly* different from LaTeX); but from my experiments you need ***both*** a nonbreaking space (`~`) and the `hspace` to produce horizontal whitespace. I tried without any nonbreaking spaces (just `hspace`), and the `hspace`s produce nothing. I also tried with just *one*, but that didn't work either. For instance, compiling the following:


```tex
Fair fa' your honest, sonsie face,\crlf
\strut\hspace[small]\hspace[small]\hspace[small]\hspace[small]Great Chieftain o' the Puddin'-race!

Fair fa' your honest, sonsie face,\crlf
\strut~\hspace[small]\hspace[small]\hspace[small]\hspace[small]Great Chieftain o' the Puddin'-race!

Fair fa' your honest, sonsie face,\crlf
\strut~\hspace[small]~\hspace[small]~\hspace[small]~\hspace[small]Great Chieftain o' the Puddin'-race!
```

Only the third instance appears correctly.

**Comment by Denubis** [comment]
Okay. I've looked into this more and the hskip primitive is far better for
our purposes if we're not defining dimensions.

I've attached a sample file with two alternatives and their pdfs.
I'm compiling on ConTeXt  ver: 2016.02.26 16:09 MKIV beta  fmt: 2016.2.29
 int: english/english

using \hskip with a measurement looks to be the most primitive and
effective. I've found that 4pt is one ~ in latin modern by default.

I've also tested this using the default "standalone" mkii engine output
used by -s, which also works.

(hopefully the attached files show up in github)

**Comment by c-forster** [comment]
Okay. So, while I've long heeded the advice to avoid TeX primitives in *TeX,`\hskip` does seem simpler (though it clutters the output just as much and because it takes an argument not in braces is slightly confusing to read).

In the interests of consistency with the existing LaTeX writer, the size of the space should be `0.333em`; and for both consistency with the existing LaTeX writer *and* ease of implementation, I think we should just output one `\hskip 0.333em` for each nonbreaking space (rather than, say, trying to determine the number of consecutive nonbreaking spaces, and then outputting a single `\hskip`---a prospect that increases in horror with every moment I spend pondering it).

So, using `hskip` instead of a set `~\hspace[small]`, the desired ConTeXt produced for the line blocks used in the example above should be:

```tex
Fair fa' your honest, sonsie face,\crlf
\strut\hskip 0.333em \hskip 0.333em \hskip 0.333em \hskip 0.333em Great Chieftain o' the Puddin'-race!

Fair fa' your honest, sonsie face,\crlf
\strut~\hskip 0.333em \hskip 0.333em \hskip 0.333em \hskip 0.333em Great Chieftain o' the Puddin'-race!

Fair fa' your honest, sonsie face,\crlf
\strut~\hskip 0.333em ~\hskip 0.333em ~\hskip 0.333em ~\hskip 0.333em Great Chieftain o' the Puddin'-race!
```

Correct? If there are no further emendations/qualifications, I'll change https://github.com/jgm/pandoc/pull/2745 to reflect this (probably sometime this weekend).

**Comment by c-forster** [comment]
Updated https://github.com/jgm/pandoc/pull/2745 so that it now uses `\hskip 0.333em` for each space, producing the output described above. If it's merged, or if other folks have input, I'll close this issue.
