### ISSUE TITLE
Code blocks lost in  translation

### ISSUE THREAD

**Issue by MattiasAsplund** [jgm/pandoc#2746]
I'm using the development version of pandoc (1.17).

I have the following code block in markdown, code.md:

```
message = "Hello world"
print(message)
```

When I do "pandoc -t native code.md" I can see that the code block is actually represented correctly by pandoc:

```
Pandoc (Meta {unMeta = fromList []})
[CodeBlock ("",[],[]) "message = \"Hello world\"\nprint(message)"]

```

Then I do 'pandoc -s code.md -o code.odt" to create an ODT document of the markdown.

Then I do 'pandoc -s code.odt -o code2.md" to recreate markdown from the document.

When I do "pandoc -t native code2.md" I can see that the code block has now been transformed into:

```
Pandoc (Meta {unMeta = fromList []})
[Para [Str "message",Space,Str "=",Space,Str "\"Hello",Space,Str "world\""]
,Para [Str "print(message)"]]

```

Do you think this translation issue is worth looking in to?

**Comment by jgm** [comment]
@MarLinn

**Comment by MarLinn** [comment]
Should be the same underlying issue as in #3437

**Comment by mb21** [comment]
Closing in favour of #3437
