### ISSUE TITLE
List in pdf: why do I have to insert a blank line before the first list item?

### ISSUE THREAD

**Issue by mhabets** [jgm/pandoc#2748]
```
list:
* item 1
* item 2
```
after: pandoc list_test.md -o list_test.pdf
I get all the text in a single line with raw stars instead of bullets

Similar result with -o list_test.tex: no itemize environment.

It works well (but there is a lot of blank space) with a blank line before the first item:
```
a list:

* item 1
* item 2
```
I am using pandoc 1.16.0.2.

**Comment by jgm** [comment]
That's just how Markdown works:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=list%3A%0A*+item+1%0A*+item+2%0A

The intent is to prevent unwanted interpretation of hyphens and
(especially numbers) at the beginning of lines as starting
lists.

Example:

    He got started on this project in the year
    2001.  Etc.

CommonMark diverges from the prior practice and does
interpret this as a list, but this decision is controversial
and may still be reversed:

http://talk.commonmark.org/t/blank-lines-before-lists-revisited/1990/5

**Comment by mhabets** [comment]
Thank you @jgm for your answer.
Ok then for the controversial md specification. As a user, I tend to prefer the CommonMark way. 

What about the tex/pdf export? At least, it should not have so much blank space (useless extra blank line in tex file) between the list introduction line and the list in the tex/pdf export.

**Comment by jgm** [comment]
+++ Emmanuel Habets [Apr 10 16 10:58 ]:
>   What about the tex/pdf export? At least, it should not have so much
>   blank space (useless extra blank line in tex file) between the list
>   introduction line and the list in the tex/pdf export.

Just using tex defaults here.  You can adjust them by adding
some definitions to the header (using -H or a custom
template with --template).  Search for "latex spacing
before and after a list" and you'll find out how.

**Comment by mhabets** [comment]
Ok then, my mistake, coming from confusion between English and French general conventions.
Indeed, the extra blank line before the list items in the tex has no effect on the final list rendering in the pdf document.

**Comment by Sophiabrown** [comment]
Hi All,
I would like to format ordered (numbered) lists with second paragraphs having a blank line and no number. In other words, break up long numbered paragraphs into more than one paragraph for the same "index" number.

This doesn't seem to validate, when i use a <br /> between paragraphs. Seems <br /> are not allowed within <ol> </ol>.

Any ideas? 
Should I be asking in the CSS forum? 
This problem is within a CSS styled page.

Just to recap, in my opinion, this:
<li>text</li> 
<li>text<br /> 
&nbsp;</li> 
<li>text</li>

should be this:

<li>text</li> 
<li style="margin-bottom:1em">text</li> 
<li>text</li>

Or alternately:

<li>text</li> 
<li><p style="margin-bottom:1em">text</p></li> 
<li>text</li>

Of course with the styles placed where appropriate.

See our development work: http://bit.ly/2tlwf1p

**Comment by rauschma** [comment]
The main issue I have with having to insert a blank line, is that this rule isn’t consistent. For example:

```
* foo
  bar
  * baz
```

This looks like the rule does not apply here. I think I’d prefer complying the CommonMark w.r.t. blank lines before bullet lists. Alternatively: make complying with CommonMark in this case, an option that is off by default?

**Comment by jgm** [comment]
We will eventually be moving the default parser over to commonmark + extensions.
In the mean time, if you want to use commonmark (with just a few extensions), you can use the `gfm` format with pandoc.

**Comment by jolars** [comment]
Actually, with `indent: true`, the extra line in latex *will* effect output since paragraphs after the list will be indented, which is usually not the desired behavior.

**Comment by ParkerRobb** [comment]
Pandoc v3.0 added the ability to use the `lists_without_preceding_blankline` extension in the `--from` option like so:
```sh
--from=markdown+lists_without_preceding_blankline
```
