### ISSUE TITLE
MathJax Setup

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#2750]
Hi,

I want to have a custom setup of MathJax, like this:

```html
<script type="text/x-mathjax-config">
	MathJax.Ajax.config.path["Contrib"] = "https://cdn.mathjax.org/mathjax/contrib";
	MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () {
		MathJax.Hub.Insert(MathJax.InputJax.TeX.Definitions.macros,{
			cancel: ["Extension","cancel"],
			bcancel: ["Extension","cancel"],
			xcancel: ["Extension","cancel"],
			cancelto: ["Extension","cancel"]
		});
	});
	MathJax.Hub.Config({
		TeX: {
			equationNumbers: { autoNumber: "AMS"},
			extensions: ["[Contrib]/physics/physics.js", "[Contrib]/siunitx/siunitx.js"]
		}
	});
</script>
```

I tried to dig into the documentation and also search through the issues, but there seems to have no reference on it.

Note that according to MathJax, the setup has to come before the MathJax is loaded. So if I put the above code in the beginning of the Markdown file, and using `pandoc --mathjax -s -o` the mathjax is put in the head and hence the setup will comes after it.

So what's the best way to do this? Template? Are there any way to put something in the head of the html without touching the template? And are there any way to config the mathjax in addition to the link to cdn?

Thanks.

**Comment by jgm** [comment]
Use a custom template and put this before the part of the
header where mathjax gets inserted.

**Comment by ickc** [comment]
I see. Thanks!

**Comment by KeAWang** [comment]
Do you have an example of how to do this?

**Comment by ickc** [comment]
First, you need to follow the doc from MathJax to setup your MathJax config.

Assuming you already done that, the problem with using that in pandoc is that the location of loading the MathJax javascript and the `header-includes` is wrong. I think for a while @jgm has considered to change this ordering (there was a PR somewhere in the past.) But in the end he decided to not change that.

So it means your only bet of getting that work is to have a custom template that you have swap the order of that 2 manually. See [Pandoc - Pandoc User’s Guide](https://pandoc.org/MANUAL.html#templates) for more about how you get the template.

If you have more question, provide a reproducible set of files and instructions you have gone through so far that didn't work, and I may be able to give you some more hints.

**Comment by ickc** [comment]
Ah, I found an old commit as an example: https://github.com/ickc/pandoc-templates-legacy/commit/b6732ae0c93cbc22887bb89cb2e28914c2ba55b1

More details:

jgm/pandoc-templates was a separate repository in the past, but is now currently a git subtree of jgm/pandoc. This means that all history in jgm/pandoc-templates was lost.

The above fork was a fork of the old jgm/pandoc-templates. The shown there is an example of what you need to do (to swap the ordering of loading.) On top of that you need to have a `header-includes` or `--include-in-header` (see pandoc manual) for your javascript mathjax config.

**Comment by KeAWang** [comment]
Thank you that worked perfectly!

**Comment by jgm** [comment]
@ickc I don't really recall this issue.
Were you asking for the MathJax script to be moved to the end of the body, instead of the head, in the custom template?  Perhaps we should revisit this.

**Comment by ickc** [comment]
I opened #7833 tracking this. This is essentially the same patch at https://github.com/ickc/pandoc-templates-legacy/commit/b6732ae0c93cbc22887bb89cb2e28914c2ba55b1 before.
We can move discussion to #7833.
