### ISSUE TITLE
Incosistent conversion of HTML entities

### ISSUE THREAD

**Issue by cortopy** [jgm/pandoc#2756]
I can't find anything in the documentation about how HTML entities are treated by the Pandoc ePub/HTML writers. I can see from a different [issue](https://github.com/jgm/pandoc/issues/844) that Pandoc "may" convert all HTML entities to unicode. However, this doesn't seem the case when I create an ePub. 

Currently, if my file has the character `&`, Pandoc converts it to `&amp;` when producing an ePub.

The problem is that epub3 doesn't accept HTML entities any more and that, too, should be a Unicode character. My concern is that pandoc epub3 is outputting files which are not entirely in line with IDPF standards.

**Comment by jgm** [comment]
`&` must always be escaped in HTML and XML (including XHTML5,
which is the basis of epub3).  I believe pandoc's behavior is correct.
See e.g.
https://wiki.whatwg.org/wiki/HTML_vs._XHTML#Differences_Between_HTML4_and_HTML5

> Do not use entity references in XHTML (except for the 5
> predefined entities: &amp;, &lt;, &gt;, &quot; and
> &apos;); use the equivalent Unicode or numeric character
> reference sequence instead.

So, `&amp;` is fine.  Indeed, it's necessary to escape `&`
or you get invalid XHTML.

+++ Juan J. Jimenez-Anca [Mar 04 16 02:32 ]:

**Comment by cortopy** [comment]
Thanks for that. I couldn't find that info in the ePub 3 specs, but that's clear now.
