### ISSUE TITLE
inline link JSON include processing fails

### ISSUE THREAD

**Issue by gliptak** [jgm/pandoc#2759]
I have this following markdown file:

    This is [an example](http://example.com/ "Title") inline link.

Running ```IncludeFilter.hs``` from http://pandoc.org/scripting.html#include-files shows following error:

     $ pandoc --version
     pandoc 1.16.0.2
     $ runhaskell --version
     runghc 7.10.3
     $ pandoc --from markdown --to json inline.md | runhaskell IncludeFilter.hs | pandoc --from json --to pdf -t latex -o inline.pdf
     IncludeFilter.hs: Error in $[0][4]: When expecting a product of 2 values, encountered an Array of 3 elements instead
     pandoc: Error in $: not enough input

Is there a different way filtering to be used? Thanks

**Comment by jgm** [comment]
You might run into problems is the version of pandoc you're
using is compiled against a different version of
pandoc-types (or perhaps also aeson) than your filter is using.

Did you install pandoc using cabal, or use a binary package?

**Comment by gliptak** [comment]
Yes ```pandoc``` and ```pandoc-types``` had different versions. Thank you for the pointer.
