### ISSUE TITLE
Blank line inside fenced code block, breaks formatting when using bullets

### ISSUE THREAD

**Issue by alexconst** [jgm/pandoc#2763]
I'm unable to paste it without github converting it automatically, so I replaced fences with `+++`
Listing here 2 cases where things are `ok` and the final one when `Not ok`

```text
# ok

without bullets it works fine:
some text
+++
pwd

echo $HOME
+++


# ok

- with bullets and without spaces it works fine:
some text
+++
pwd
echo $HOME
+++



# Not ok

- with bullets and with a space it breaks formatting:
some text
+++
pwd

echo $HOME
+++
```

pandoc -S -f markdown_github -t html5  bug_fenced_code_blocks.md  -o bug_fenced_code_blocks.html

**Comment by jgm** [comment]
I'm surprised pandoc accepts the second one.  Really, block-level elements (such as code blocks) inside a list should be indented 4 spaces.  See the User's Guide.
If you check [Babelmark2](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+with+bullets+and+with+a+space+it+breaks+formatting%3A%0Asome+text%0A%60%60%60%0Apwd%0A%0Aecho+%24HOME%0A%60%60%60%0A%0A) you'll see a huge variety of interpretations.  Recommendation:  don't try to write Markdown this way.

**Comment by alexconst** [comment]
> I'm surprised pandoc accepts the second one. 

Please keep it that way. It's a feature :)

But from now on I'll indent blocks in bullets.
