### ISSUE TITLE
OS X package installer pandoc-1.16.0.2-osx.pkg won't install

### ISSUE THREAD

**Issue by Twangist** [jgm/pandoc#2764]
on OS X 10.7.4: "pandoc can’t be installed on this computer." Why's that? Does it require a later OS version?

**Comment by jgm** [comment]
See this pandoc-discuss thread and see if it helps:
https://groups.google.com/forum/#!searchin/pandoc-discuss/osx$20can$27t$20be$20installed/pandoc-discuss/DfvriGXtu-8/vTq9CUOdiFoJ


+++ Twangist [Mar 08 16 14:17 ]:

**Comment by Twangist** [comment]
It certainly did -- thank you.
