### ISSUE TITLE
Textile to Markdown: Change of behavior regarding escaping square brackets

### ISSUE THREAD

**Issue by paulmenzel** [jgm/pandoc#2767]
With Debian 8.3 (jessie) and pandoc 1.12.4.2, the characters `[` and `]` are converted differently from  Textile to Markdown than in [pandoc 1.16.0.2](http://pandoc.org/try/).

### 1.12.4.2 ###

```
$ pandoc --version
pandoc 1.12.4.2
[…]
$ more test.textile 
[test]
$ pandoc --from textile --to markdown_strict test.textile 
[test]
```

### 1.16.0.2 ###

[Try pandoc!](http://pandoc.org/try/?text=%5Btest%5D&from=textile&to=markdown_strict) converts it to the Markdown text below.

```
\[test\]
```

That’s syntactically correct, as that `[` and `]` [can be escaped by the backslash](https://daringfireball.net/projects/markdown/syntax#backslash), but it doesn’t have to, and is different than in the older version.

Was that an expected change of behavior?

**Comment by jgm** [comment]
Yes.  If brackets aren't escaped, bracketed text might be wrongly interpreted as a Markdown link.  (E.g. if you have `[test]: u` somewhere else in your document.)

It's true that in this particular case that's not going to happen.  But it's not easy to determine when this kind of unintended interpretation might occur, so we escape all brackets.
