### ISSUE TITLE
Formatting of verbatim text in PDF

### ISSUE THREAD

**Issue by candlerb** [jgm/pandoc#277]
A couple of formatting problems in PDF output.

(1) When writing verbatim text in backticks, and this text occurs near the end of a line, it extends past the right margin. Whilst it may undesirable to wrap such text, I think it would be better to move it to the start of the next line. Otherwise, the backticks syntax is only useful for very small pieces of text.

(2) When you have a list item which contains a paragraph, then a delimited code block, then another paragraph, there is a double space between the code block and the second paragraph.

An example showing both problems:

```
% Testing

Blah blah blah blah blah blah blah blah blah blah
blah blah blah blah blah blah blah blah blah blah.

Blah blah blah blah blah blah blah blah blah.
Set environment variable `TCL_TK_INCLUDE_DIR_OPTIONAL` if you want to
blah blah blah blah blah blah blah blah blah blah.

* We can easily generate a view keyed on `[subject, predicate, object]`.
  A search with `startkey=[id]&endkey=[id,{}]` will show all predicates
  relating with that id as the subject. A search with
  `startkey=[id,pred]&endkey=[id,pred,{}]` will just show one type of
  predicate on that id. A reverse index on `[predicate, object, subject]`
  can be used to work backwards, i.e. find all subjects which relate to
  an object in a particular way.

* Another example is when you embed code within a list item:

    ~~~~
    Some sample
    code goes here
    ~~~~

    When you continue onto another paragraph within the same list item,
    you get a double space between the code and the next paragraph.
```

Rendered version at http://psg.com/~brian/pandoc-verbatim-sample.pdf

**Comment by Voleking** [comment]
@jgm The package [spverbatim](https://www.ctan.org/pkg/spverbatim?lang=en) seems to handle breaks in verbatim output. Maybe use spverbatim will be better?

**Comment by jgm** [comment]
Maybe, but I don't like to depend on obscure packages in the
default output.

+++ Voleking [May 29 17 00:17 ]:
>   [1]@jgm The package [2]spverbatim seems to handle breaks in verbatim
>   output. Maybe use spverbatim will be better?

**Comment by Voleking** [comment]
So if there is any way replace the verbatim with spverbatim by using some command in my latex template? Or where should I add `\sloppypar` in my template to make code wrap correctly.
![test](https://cloud.githubusercontent.com/assets/13161779/26143457/9e552b3c-3b17-11e7-83a2-bb158b88488e.png)

**Comment by jgm** [comment]
+++ Voleking [May 29 17 00:46 ]:
>   So if there is any way replace the verbatim with spverbatim by using
>   some command in my latex template? Or where should I add \sloppypar in
>   my template to make code wrap correctly.

Probably, yes.  You could try including this in your
template's preamble:

\renewenvironment{verbatim}{\begin{spverbatim}}{\end{spverbatim}}

**Comment by Voleking** [comment]
@jgm Thx you reply, but it seem cut no ice for VerbatimEnvironment——Highlighting.
