### ISSUE TITLE
Bug: \overrightarrow does not translate from html to docs format

### ISSUE THREAD

**Issue by chiffa** [jgm/pandoc#2770]
Instead a non-recognized symbol is inserted.

HTML excerpt:
`<span class="symbolover">⟶</span><span class="undersymbol">r</span>`

docx symbol that is not recognized:
⟶

**Comment by jgm** [comment]
I tried `pandoc -o my.docx` with `$$\overrightarrow{A}$$`, and it worked fine.
Can you say more precisely what you're trying to do and what happened?
Also, what pandoc version?
