### ISSUE TITLE
Link to the latest release build 

### ISSUE THREAD

**Issue by rossant** [jgm/pandoc#2772]
Is there a link to the latest .deb? This is to ensure that my project that depends on pandoc always uses the latest version on Travis CI. Currently I use `wget https://github.com/jgm/pandoc/releases/download/1.16.0.2/pandoc-1.16.0.2-1-amd64.deb but I'd prefer not to have the version hard-coded in the URL`.

**Comment by jgm** [comment]
No, there isn't, as far as I know.

+++ Cyrille Rossant [Mar 09 16 15:25 ]:

**Comment by rossant** [comment]
Here is a little bash script that will download and install the latest pandoc release on Debian-based systems: https://gist.github.com/rossant/8b751a15d71d6d9403a8
