### ISSUE TITLE
footnotes numbered by chapter in docx writer

### ISSUE THREAD

**Issue by crystalfp** [jgm/pandoc#2773]
I'm writing a long book in markdown and converting it to DOCX and EPUB3. In EPUB3 the footnotes numbering is restarted at each top level chapter. I think this is the correct behavior. Instead in the DOCX output the notes are numbered sequentially in the whole book.
Is it possible to have the footnotes numbered by chapter also in DOCX? Seems there is no way to reconcile the behavior between the two formats (at least my google investigation comes out empty).
Thanks for clarifying!
mario

Using pandoc 1.16.0.2 on Windows 7 64bits

**Comment by crystalfp** [comment]
The same problem happens with latex output only if you don't pass to pandoc the command line ``--chapter`` Obvious, because footnote numbering restarts each chapter and not every section.
The solution seems to insert in the DOCX file a "Section Break (continuous)" before each Level 1 header and set "number footnotes per section". This second setting could be obviated with a template document, but the first one no because the break is not part of the heading. Is it possible to add an option to pandoc to add (in the DOCX writer) the section break before each level 1 header? One possible way is to overload the ``--chapter`` option to work in DOCX writer adding the break. Thanks! mario

**Comment by michalovadek** [comment]
I know this is an old issue but I was wondering if this has been solved in the meanwhile I have tried changing the setting to "number footnotes per section" in the docx template document I'm using but it does not solve the problem. I have also tried applying a filter creating section bibliographies (https://github.com/pandoc-ext/section-bibliographies). That does what it says but does not restart footnote numbering as hoped for.

**Comment by jgm** [comment]
> Is it possible to add an option to pandoc to add (in the DOCX writer) the section break before each level 1 header?

You could probably use a Lua filter to do this.  (Adding `RawBlock` element with format `openxml`; but you need to get the XML exactly right.)

> Is it possible to add an option to pandoc to add (in the DOCX writer) the section break before each level 1 header? One possible way is to overload the --chapter option to work in DOCX writer adding the break. 

This is not a bad idea.

**Comment by michalovadek** [comment]
I was looking for a test file that would show this working; I couldn't find one. Could anyone maybe point me to one? The `notes.docx` test does not have multiple chapter-level sections

The reason for looking is that I cannot get this to work in my setup and I cannot find the source of the issue.
