### ISSUE TITLE
Python 3.5 and "pandoc: error while loading shared libraries: libgmp.so.3: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by ianozsvald** [jgm/pandoc#2774]
Using Python 3.5 and a recent version of pandoc on Linux Mint 17.2 (Ubuntu 14.04) I have a `libgmp` error _if I install the wrong package in Anaconda_. Using Python 3.4 and Pandoc 1.15 I have *no* error. I discovered this recently when upgrading to Python 3.5. 

This is not a bug, it is a description of the problem and a path to the solution (so it can be closed and just left archived).

Working configuration:
```
Python 3.4.4 |Anaconda 2.5.0 (64-bit)| (default, Jan 11 2016, 13:54:01)
...
$ pandoc --version
pandoc 1.15.0.6
Compiled with texmath 0.8.2.2, highlighting-kate 0.6.
```
It looks like I stumbled onto the right configuration when I installed this last on Python 3.4.

Failing configuration:
```
Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
$ pandoc
pandoc: error while loading shared libraries: libgmp.so.3: cannot open shared object file: No such file or directory
```

The Python 3.5 version was installed using the `conda` package manager:
```
$ conda install -c userDil # pandoc: 1.16.0.2-1
```
I tried several recent versions via the `conda` package manager from different submitters for Linux 64bit, they each install and then fail with `libgmp.so.3`. 

The *working* solution for Python 3.5 is:
```
conda install -c anaconda-nb-extensions pandoc
```
and this installs version `1.12.3-3` which works (I can use it with `jupyter nbconvert <file> --to pdf` to export a PDF from a Jupyter Notebook).

Version `1.12` looks old, I'll leave this here in case anyone has a better solution for a more recent build.

Sidenote - I've also just completed building from source (having downloaded the Haskell compiler suite) - this works too.

**Comment by jgm** [comment]
Thanks for reporting.

**Comment by ccordoba12** [comment]
@ianozsvald, please try my pandoc package with

    conda install -c ccordoba12 pandoc

It doesn't have the error you reported, but it's only available for Linux 64 (so no Linux 32 support :-).

By the way, it's not the latest Pandoc, but pretty close (1.15.2).

**Comment by ianozsvald** [comment]
@ccordoba12 yep, that works with Python 3.5, many thanks :-)

**Comment by ccordoba12** [comment]
Great to know it works for you too! :+1:
