### ISSUE TITLE
Interpretation of html base href is wrong when a href begins with slash

### ISSUE THREAD

**Issue by ryandesign** [jgm/pandoc#2777]
Input HTML file:

```
<html>
<head>
<base href="http://www.example.com/some/directory/">
</head>
<body>
<p><a href="/absolute/link">absolute link</a></p>
</body>
</html>
```

Run command:

```
pandoc -f html -t markdown file.html
```

Expected output:

```
[absolute link](http://www.example.com/absolute/link)
```

Actual output:

```
[absolute link](http://www.example.com/some/directory//absolute/link)
```

**Comment by ryandesign** [comment]
Thanks! Do you plan to release a new version of pandoc containing this change soon? Building pandoc from source is [difficult](https://trac.macports.org/ticket/48324).

**Comment by jgm** [comment]
If you want to build from source, I recommend you use stack.
See under "Installing from source" in <http://pandoc.org/installing>.
It's a simple 3-step process, and should be pretty trouble-free.

+++ Ryan Schmidt [Mar 16 16 07:22 ]:
