### ISSUE TITLE
Pandoc requires reference.docx components that are optional in Word

### ISSUE THREAD

**Issue by dmolesUC3** [jgm/pandoc#2781]
Steps to reproduce:
- place this [reference.docx](https://github.com/jgm/pandoc/files/170521/reference.docx) in `~/.pandoc`
- convert [test.md.txt](https://github.com/jgm/pandoc/files/170524/test.md.txt) from `markdown_github` to `docx`
  `
  $ pandoc -f markdown_github -t docx test.md.txt -o test.docx
  `

Expected:
- file converts

Actual:
- `pandoc: user error (word/numbering.xml missing in reference docx)`

Notes:
- This happens whether or not "Maintain compatibility with previous versions of Word" is checked when saving the `.docx` in Office 2016. (The attached version was the box unchecked.)
- Naively, I tried copying `word/numbering.xml` from the [pandoc source](https://github.com/jgm/pandoc/blob/master/data/docx/word/numbering.xml) into `reference.docx`. If I do that, the conversion is apparently successful (see generated file: [test.docx](https://github.com/jgm/pandoc/files/170526/test.docx)), but Office 2016 produces the error message: "Microsoft Office cannot open this file because some parts are missing or invalid":<br/>
  ![screen shot 2016-03-12 at 9 55 14 am](https://cloud.githubusercontent.com/assets/10374934/13724381/8ea85002-e838-11e5-87f3-950ec44dff04.png)<br/>
  I notice that the `numbering.xml` in the generated file is 4974 bytes while the one I copied into `reference.docx` is only 1740 bytes, but that could be a red herring.

**Comment by jgm** [comment]
How did you produce the reference.docx?  The recommended way
is to produce a docx using pandoc, then modify it.

**Comment by dmolesUC3** [comment]
It's based on an existing Word template I've had knocking around since forever. I wasn't aware of that recommendation -- maybe it should be part of the `--data-dir` docs?

**Comment by jgm** [comment]
We've improved the documentation under `--reference-doc`.

**Comment by absolutelybrandon** [comment]
damn what a programmer
