### ISSUE TITLE
[Textile] Paragraphs marked up strong not detected

### ISSUE THREAD

**Issue by paulmenzel** [jgm/pandoc#2782]
The [official(?) Textile specification](http://txstyle.org/doc/16/strong-and-bold-text) at [Textpattern](http://textpattern.googlecode.com/svn/development/4.x/textpattern/lib/classTextile.php)), and their [online demo](http://txstyle.org/) suggest, that marking up text over several lines (line break) does not work. But there are projects/implementations like [OpenProject](https://www.openproject.org/) where it does work.

```
*strong 1st line
strong 2nd line*
```

The text above is marked up as below.

> **strong 1st line
> strong 2nd line**

Pandoc also (rightfully(?)) does not accept that mark-up.

Unfortunately, in our case, there is now text with the incorrect(?) Textile mark-up. How do you deal with that? Would an additional switch to Pandoc be accepted?

**Comment by jgm** [comment]
It's hard enough to cover all of the different light markup syntaxes we already cover; I don't think we should be adding flags to handle buggy implementations of syntaxes too.

**Comment by PowerKiKi** [comment]
The online demo mentioned no longer support bold across lines. The given example is rendered as a single `<p>` without any bold effect. I believe this issue should be closed as invalid/wontfix.

**Comment by jgm** [comment]
Thanks, will close.
