### ISSUE TITLE
no warnings given when tables with merged cells fail to convert

### ISSUE THREAD

**Issue by jamesrharwood** [jgm/pandoc#2783]
E.g. When I convert the attached docx file, pandoc deletes columns 2 and 3 without warning me. It would be useful to get a warning.
[example_table_with_merged_cells.docx](https://github.com/jgm/pandoc/files/172787/example_table_with_merged_cells.docx)

**Comment by jgm** [comment]
@jkr now that you've integrated warnings into the docx reader, it should be fairly simple to issue a warning in this case.  Or have you already added that, too?

**Comment by jkr** [comment]
No -- I just haven't had a chance to look through the xml in detail to
figure out how they do merged horizontal cells, and merged vertical.

I also think the deletion is the result of some shortcuts I take in the
current implementation that force the table to be the width of the first
row. I have a feeling that if I looked closely, I could avoid losing
some data as well.

**Comment by Sen-Sai** [comment]
So it would be really great if a warning could be given!

**Comment by jgm** [comment]
I tried the docx in the original post with the current dev version of pandoc, and no columns are lost.

I'm sorry, we don't backport changes to older versions.  But it looks like things are already fixed?

**Comment by jgm** [comment]
When cells are being merged, though, I agree that a warning should be issued.

**Comment by Sen-Sai** [comment]
> 
> I'm sorry, we don't backport changes to older versions. But it looks like things are already fixed?

Reason I mentioned that is because hosting companies do not very often upgrade their *nix version or PHP version resulting in the fact that as a user you are stuck with certain versions of pandoc.

**Comment by tarleb** [comment]
Commit 56b211120c62a01f8aba1c4512acfe4677d8c7d0 added support for colspans and rowspans to the docx reader, so this should be fixed now.
