### ISSUE TITLE
UTF-8 error trying to convert LaTeX to docx

### ISSUE THREAD

**Issue by StephenDPorter** [jgm/pandoc#2784]
I get the following error when trying to convert from LaTeX to docx on OS X El Capitan.  It has been a while since I have needed to perform this function, but it worked previously.
pandoc: Cannot decode byte '\xba': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream

**Comment by jgm** [comment]
Your LaTeX document is not UTF-8 encoded.  Convert it and
you shoud be fine.  Pandoc requires input text to be UTF-8.

+++ Stephen Porter [Mar 14 16 14:19 ]:

**Comment by micklexqg** [comment]
@jgm ,how to convert it to be UTF-8 encoded?

**Comment by tarleb** [comment]
@micklexqg http://lmgtfy.com/?q=convert+file+to+utf-8
