### ISSUE TITLE
Include more commandline options in YAML yeader

### ISSUE THREAD

**Issue by naught101** [jgm/pandoc#2786]
It would be really cool if I could have a YAML header like this:

```{yaml}
---
title: My Presentation
author: naught101
date: \today{}
to: beamer
output: Presentation_20160315.pdf
header-includes:
  - \usepackage{presentation_style}
---
```

So that I could just type `pandoc filename.md`, and pandoc would automatically recognise that it was intended as a beamer presentation, and use the given filename as the output filename. There are probably other options where this would be useful too, I haven't checked through them all.

Obviously `-o blah.pdf` on the command line should override what ever is in the YAML header if something like this is implemented.

**Comment by jgm** [comment]
I'd like to keep the metadata as metadata.  I'd recommend using a Makefile if you want to simplify building of documents (and make the process self-documenting).
