### ISSUE TITLE
Setting font size for KOMA-Script

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#2789]
After setting `fontsize` to e.g. `24pt`, I observe the following warning when running LaTeX:

```
Package scrartcl Warning: You've used obsolete option `24pt'.
(scrartcl)                Usage of this option indicates an old document
(scrartcl)                and changes compatibility level using
(scrartcl)                `fontsize=24pt,version=first'.
(scrartcl)                If you don't want this, you should simply
(scrartcl)                replace option `24pt' by `fontsize=24pt'.
```

Would it be too clever to prefix `fontsize=` to the `fontsize` variable when `documentclass` is equal to `scrbook`, `scrreprt`,  `scrartcl`, or `scrlttr2`?

**Comment by wilx** [comment]
I would suggest using modified default LaTeX template. I have copied the default and removed `$if(indent)$` chunk from mine for KOMA class documents to avoid another warning produced by KOMA class documents.

**Comment by jgm** [comment]
On reflection I think @wilx is right -- trying to be too fancy will just make it confusing when people write their own komascript templates, which they'll probably want to do anyway for other reasons.
