### ISSUE TITLE
docx reader: numbered headings turn into lists

### ISSUE THREAD

**Issue by rockyallen** [jgm/pandoc#2793]
Saved as strict docx. pandoc 1.16.0.2, Windows 7, MS Word 2013.
Command:
````
pandoc -f docx -t asciidoc --normalize --wrap=none --atx-headers canvas.docx
````
Output:
````
1.  [[h1]]
= H1
1.  [[h2]]
== H2
1.  [[h3]]
=== H3

And some text
````
[headings.docx](https://github.com/jgm/pandoc/files/174836/headings.docx)
I would prefer leading numbers in headings to be stripped.

**Comment by jkr** [comment]
Fixed with 855c8b43f0497125f8d24b113ce0df92ed7d074b
