### ISSUE TITLE
[org-mode to html] Tables not correctly separated

### ISSUE THREAD

**Issue by Jiehong** [jgm/pandoc#2794]
Pandoc used: online demo.

When an org table is exported to html5, line separations are not exported.

Example: http://pandoc.org/try/?text=++|+Name++|+Value+|%0A++|-------%2B-------|%0A++|+Bob+++|++++12+|%0A++|+Alice+|++++14+|%0A++|-------%2B-------|%0A++|+Paul++|++++24+|%0A++|+Chloe+|+++++9+|%0A++|-------%2B-------|&from=org&to=html5

Input:

```
  | Name  | Value |
  |-------+-------|
  | Bob   |    12 |
  | Alice |    14 |
  |-------+-------|
  | Paul  |    24 |
  | Chloe |     9 |
  |-------+-------|
```

Output:

```
<table>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bob</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alice</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paul</td>
<td style="text-align: left;">24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chloe</td>
<td style="text-align: left;">9</td>
</tr>
</tbody>
</table>
```

Expected output (from emacs org-mode export to html, which clean-up):

```
<table>
<colgroup>
<col  class="left" />
<col  class="right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="left">Name</th>
<th scope="col" class="right">Value</th>
</tr>
</thead>
<tbody>
<tr>
<td class="left">Bob</td>
<td class="right">12</td>
</tr>

<tr>
<td class="left">Alice</td>
<td class="right">14</td>
</tr>
</tbody>
<tbody>
<tr>
<td class="left">Paul</td>
<td class="right">24</td>
</tr>

<tr>
<td class="left">Chloe</td>
<td class="right">9</td>
</tr>
</tbody>
</table>
```

`tbody` is closed and re-opened after Alice, which is not the case from Pandoc.

Pandoc should not bypass separation lines in org-mode tables.

Checkin http://pandoc.org/README.html#tables, I think it should be supported, but I may be wrong.

**Comment by tarleb** [comment]
Thanks for the throughout bug report, @Jiehong.  Unfortunately, this is not easily fixable.  The internal Pandoc structure for tables allows only for a single table head/body.  The additional information conveyed by org-mode tables often impossible to transferred to other formats. 
Table-internal separators are simply discarded for that reason.  This is unlikely to change, bare a complete rewrite of pandoc
