### ISSUE TITLE
Error in converting .tex to .docx with elsarticle template

### ISSUE THREAD

**Issue by StephenDPorter** [jgm/pandoc#2796]
Using the elsarticle LaTeX template, pandoc won't covert to .docx. Regardless of where I put `/end{document}`, I get the following error:

> Error at "input" (line 632, column 5):
unexpected "{"
expecting letter or lf new-line
\end{document}

I'm using LaTeX for document versioning but need to convert to Word for co-authors. Or would your recommendation be to write in Word and only convert the final submission copy to LaTeX?

Thanks!

**Comment by jgm** [comment]
Please give sufficient input files and exact build
instructions, so we can reproduce this.  (Also say what
version of pandoc.)

+++ Stephen Porter [Mar 19 16 07:36 ]:

**Comment by StephenDPorter** [comment]
This "issue" can be closed. The source of the error was two lines of code using `\ref` for items that were not labeled in the document (a Figure and a Table - labeled in a previous version but have seen been superseded).

Removing those two lines allows Pandoc to convert the .tex file to .docx with no problems.

Thanks!

BTW, I'm using build 1.16.0.2 for Mac OS X.

**Comment by vjagodnik** [comment]
> This "issue" can be closed. The source of the error was two lines of code using `\ref` for items that were not labeled in the document (a Figure and a Table - labeled in a previous version but have seen been superseded).
> 
> Removing those two lines allows Pandoc to convert the .tex file to .docx with no problems.
> 
> Thanks!
> 
> BTW, I'm using build 1.16.0.2 for Mac OS X.

Could you explain it a little bit more. I am having the same problem but I cannot find extra "\ref" or similar.
With kind regards
