### ISSUE TITLE
definition_lists dd child paragraph

### ISSUE THREAD

**Issue by jamesdbrock** [jgm/pandoc#2798]
Using extension `definition_lists`, [the Pandoc README says](http://pandoc.org/README.html)

> If you leave space before the definition (as in the example above), the text of the definition will be treated as a paragraph.

... but this doesn't seem to work for definition lists of one item.

## `file1.md`

```
definition list dt 1

:   definition list dd 1

```

```
$ pandoc -f markdown+definition_lists -t html5 < file1.md 
<dl>
<dt>definition list dt</dt>
<dd>definition list dd
</dd>
</dl>
```

## `file2.md`

```
definition list dt 1

:   definition list dd 1

definition list dt 2

:   definition list dd 2
```

```
$ pandoc -f markdown+definition_lists -t html5 < file2.md 
<dl>
<dt>definition list dt 1</dt>
<dd><p>definition list dd 1</p>
</dd>
<dt>definition list dt 2</dt>
<dd><p>definition list dd 2</p>
</dd>
</dl>
```

**Comment by jgm** [comment]
See the manual:

"If you leave space before the definition (as in the example
above), the text of the definition will be treated as a
paragraph.  In some output formats, this will mean greater
spacing between term/definition pairs. For a more compact
definition list, omit the space before the definition:"

So, if you want `<p>` tags, include a space before the
definition.  This is standard behavior from PHP Markdown
Extra and other implementations that support this definition
list syntax.

+++ James Brock [Mar 21 16 18:19 ]:

**Comment by jamesdbrock** [comment]
The latest version of Pandoc has the correct behaviour. Sorry, closing issue. Thanks for the prompt reply, John, and thanks for Pandoc, it's a great piece of software.
