### ISSUE TITLE
Markdown Title ending in two or more spaces corrupts date and author metadata

### ISSUE THREAD

**Issue by dfc** [jgm/pandoc#2799]
If the title in the metadata block ends in more than one space the following newline character and the author metadata are treated as a continuation of the title. This happened in 1.16.0.2 (i think, but certainly a 1.16.x.y) and i just upgraded to the most recent pandoc from git. 

Demonstration:

The file `2space.md` is as follows: 

```
% Two Spaces in Title  
% Douglas Calvert
% March 24, 2016


lorem ipsum
```

To be clear if the spaces in the Title line are replaced with `@` the tile line becomes:

```
%@Two@Spaces@in@Title@@
```

Convert to markdown with yaml metadata:

```
dfc@oda550:~/ToDo/pandocbug$ pandoc -t markdown -s -S 2space.md 
---
author:
- 'March 24, 2016'
title: |
    Two Spaces in Title\
    % Douglas Calvert
---

lorem ipsum
```

Convert to native format: 

```
dfc@oda550:~/ToDo/pandocbug$ pandoc -t native -s -S 2space.md 
Pandoc (Meta {unMeta = fromList [("author",MetaList [MetaInlines [Str "March",Space,Str "24,",Space,Str "2016"]]),("title",MetaInlines [Str "Two",Space,Str "Spaces",Space,Str "in",Space,Str "Title",LineBreak,Str "%",Space,Str "Douglas",Space,Str "Calvert"])]})
[Para [Str "lorem",Space,Str "ipsum"]]

```

After reading the user guide I would not expect the multiline title behavior to come into play because the author line begins with a `%` in the first column and not spaces. Obviously I did not intend to have the extra spaces at the end of the title line but if you asked me I would not have thought it made a difference. With one extra space at the end of the title pandoc behaves as I would have expected; pandoc drops the extra space and happily carries on being my favorite text processing tool:

In the following two examples the title line with `@` for spaces looks like:

 `%@One@Spaces@in@Title@`

```
dfc@oda550:~/ToDo/pandocbug$ pandoc -s -S -t markdown 1space.md 
---
author:
- Douglas Calvert
date: 'March 24, 2016'
title: One Spaces in Title
---

lorem ipsum
```

```
dfc@oda550:~/ToDo/pandocbug$ pandoc -s -S -t native 1space.md 
Pandoc (Meta {unMeta = fromList [("author",MetaList [MetaInlines [Str "Douglas",Space,Str "Calvert"]]),("date",MetaInlines [Str "March",Space,Str "24,",Space,Str "2016"]),("title",MetaInlines [Str "One",Space,Str "Spaces",Space,Str "in",Space,Str "Title"])]})
[Para [Str "lorem",Space,Str "ipsum"]]
```

I hope this is helpful. I apologize if this is already covered by another bug or the expected behavior. But I really hope this is not the expected behavior

**Comment by dfc** [comment]
ugh. this is the expected behavior.  I forgot the silly markdown two spaces rule. I only ever think of ending lines with `\` for hard breaks. I would go ahead and close this for you but the one nagging complaint is this line from the User Guide:

> The title may occupy multiple lines, but continuation lines must begin with leading space, thus

In this case the continuation line begins with an `%`:

```
Str "Title",LineBreak,Str "%",Space
```

This is an odd corner case. I apologize for making it known and causing the needless grief...

**Comment by jgm** [comment]
No, it's not the expected behavior.  (Otherwise the line you quote from the manual would be very misleading.)  This can be fixed pretty easily: instead of parsing "many inlines til newline", we need to grab the line as a raw string, then parse its contents as inlines.
