### ISSUE TITLE
RSS or Atom output format?

### ISSUE THREAD

**Issue by samwilson** [jgm/pandoc#2800]
It would be terrific if Pandoc could output RSS or Atom news feeds of sets of files.

The closest I've been able to find is this:
https://github.com/wcaleb/website/blob/81c4ee0a34df964625f45d0faf67a3ee70310577/pansite.sh#L94

But I thought I'd raise this issue in case anyone knows of better ways to do this.

Thanks!

**Comment by jgm** [comment]
This is out of scope, I think.
(It's something you should use another tool to do.)

**Comment by samwilson** [comment]
No worries, makes sense. Thanks for thinking about this.

Do you have any suggestions of tools that could do this?

**Comment by jgm** [comment]
+++ Sam Wilson [Mar 22 16 17:17 ]:
>   No worries, makes sense. Thanks for thinking about this.
>
>   Do you have any suggestions of tools that could do this?

Sorry, I don't know what's out there in this space.
