### ISSUE TITLE
source highlighting not working in reveal.js slides

### ISSUE THREAD

**Issue by Honestpuck** [jgm/pandoc#2801]
Hi,

Running pandoc 1.16.0.2.

I am creating a `reveal.js` slide show and I can't get syntax highlighting working for either a bash script snippet or python. The code is just bright white.

Tony Williams

**Comment by dfc** [comment]
You should also include an example of the input you are using that is giving the unexpected result.

**Comment by Honestpuck** [comment]
### Python Programming

```
from HTMLParser import HTMLParser
import urllib2
import sys

girl = sys.argv[1]
maxpage = sys.argv[2]

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        if tag == 'a':
            for name, value in attrs:
                if name == 'href':
                    print value
```


That's an example slide.

**Comment by jgm** [comment]
You do need the `python` after the opening triple ticks.  But with that change it worked fine for me (using 1.17.0.1).  IF it's still not working, why don't you post the exact command you used, and the output HTML you get.

**Comment by Honestpuck** [comment]
Upgrading to 1.17.0.1 fixed the problem. It may have just been  brain fart
on my side.


Sent over my RFC 1149 compliant IPoAC link.  Lost packets leading to
garbled or strange messages are entirely the fault of the link and should
not be seen as a reflection of the mental state of the person writing.
