### ISSUE TITLE
Conversion of unicode char U+202F to LaTeX

### ISSUE THREAD

**Issue by Eichensaeher** [jgm/pandoc#2802]
The CSL I'm using (`din-1505-2-numeric.csl`) separates author names by semicolon and unicode char `U+202F` (`NARROW NO-BREAK SPACE`) which isn't translated to `\thinspace`. I've also tested it inside a formular and this char isn't translated to `\,` (useless anyway). Both caused the LaTeX compiler (TeX Live) to abort.

Simple Markdown for reproduction:
```markdown
Simple Test
===========

Separated&#8239;text
```

**Comment by andya9** [comment]
In the live interpreter (pandoc -t latex from the cli, then paste the code and ctrl-d) it gets converted just fine (pandoc v 1.17.0.1)

**Comment by Eichensaeher** [comment]
It gets converted, but Tex Live isn't able to compile the result.
```
! Package inputenc Error: Unicode char ΓÇ» (U+202F)
(inputenc)                not set up for use with LaTeX.
```

**Comment by andya9** [comment]
You need xelatex probably, if I remember well latex can’t deal well with unicode

**Comment by Eichensaeher** [comment]
That worked, thanks.
