### ISSUE TITLE
Multiple newlines collapsed into one in markdown_github

### ISSUE THREAD

**Issue by ryandesign** [jgm/pandoc#2805]
**Pandoc version:** 1.17.0.1

**Input:**

    one<br>two<br><br>three<br><br><br>end

**Command:**

    pandoc -f html -t markdown_github

**Expected output:**

```
one
two

three


end
```

**Actual output:**

```
one
two
three
end
```

In fact, when rendered on GitHub, two or more consecutive newlines get turned into a new paragraph. GitHub doesn't seem to support actually rendering an arbitrary number of newlines. But pandoc should at least do the right thing when there are two newlines. Otherwise my paragraphs run together.

**Comment by jgm** [comment]
Rendering `a<br><br>b` as `a\n\nb` is not obviously the right thing, since `a\n\nb` in Markdown isn't a single paragraph containing two line breaks, but two consecutive paragraphs.

**Comment by ryandesign** [comment]
Ok, well two things about that:

1. You handle markdown and markdown_github differently in this regard. markdown outputs each newline. markdown_github condenses consecutive newlines into a single one. That difference is unexpected to me.
2. My original document is plain text, where there is no way for the author to mark up paragraphs specifically. Because pandoc does not support plain text input (#2705) I'm using HTML as an intermediate format, converting my plain text to HTML using the PHP functions `nl2br(htmlspecialchars($input))`. I have had to change this to a custom function that changes two consecutive newlines to a `<p>`, and the remaining newlines to a `<br>`. If there is a better recommended way to get pandoc to accept plain text input, I can switch to that.

**Comment by jgm** [comment]
+++ Ryan Schmidt [Mar 22 16 20:39 ]:
>   Ok, well two things about that:
>    1. You handle markdown and markdown_github differently in this regard.
>       markdown outputs each newline. markdown_github condenses
>       consecutive newlines into a single one. That difference is
>       unexpected to me.

Pandoc's markdown flavor allows you to create a linebreak
using backslash + newline.  So, when that is available, we
use it.  That syntax makes it possible to have two
consecutive line breaks without starting a new paragraph.

In github markdown, we don't have that syntax, so there is
no way to have two consecutive line breaks without starting
a new paragraph.  So we have to choose between two evils:
(a) collapsing the two line breaks into one or (b) creating
a new paragraph where none is indicated in the input.
We choose (a).

I hope that explains the difference.

>    2. My original document is plain text, where there is no way for the
>       author to mark up paragraphs specifically. Because pandoc does not
>       support plain text input ([1]#2705) I'm using HTML as an
>       intermediate format, converting my plain text to HTML using the PHP
>       functions nl2br(htmlspecialchars($input)). I have had to change
>       this to a custom function that changes two consecutive newlines to
>       a <p>, and the remaining newlines to a <br>. If there is a better
>       recommended way to get pandoc to accept plain text input, I can
>       switch to that.

See my comment on #2705.  It's impossible to answer this
question without knowing more about how you would want blank
lines (and newlines generally) treated in the plain text
input.
