### ISSUE TITLE
markdown_github: less-than (&lt;) and greater-than (&gt;) entities not converted; underscore escaped

### ISSUE THREAD

**Issue by ryandesign** [jgm/pandoc#2806]
My original plain text document contains the line:

```
<http://www.example.com/some_page>
```

I want the converted markdown_github document to contain that same line. If it becomes a link to that URL that's great too.

**Pandoc version:** 1.17.0.1

**Command:**

```
echo '&lt;http://www.example.com/some_page&gt;' | pandoc -f html -t markdown_github
```

**Expected output:**

```
<http://www.example.com/some_page>
```

**Actual output:**

```
&lt;http://www.example.com/some\_page&gt;
```

This results in GitHub displaying the string `http://www.example.com/some\_page` and also linking to that URL. Either converting the `&lt;` and `&gt;` entities to `<` and `>`, or not escaping the `_`, will fix the issue.

**Comment by mb21** [comment]
GitHub markdown seems to have weird rules for when you can/should escape underscores. As soon as it detects it to be a link, you aren't supposed to escape the underscore any more.

- `_foo_` -> _foo_
- `x_foo_` -> x_foo_
- `\_foo_` -> \_foo_
- `example.com/some\_page` -> example.com/some\_page
- `www.example.com/some\_page` -> www.example.com/some\_page

But it appears to be safe to only escape an underscore if it's preceded by a space...

**Comment by jgm** [comment]
Fixing this would require a lot of complication in our
character escaping function:  we'd have to look at the
whole surrounding context and figure out whether github
would be likely to interpret the string containing the `_`
as a URL.

+++ Mauro Bieg [Mar 23 16 05:28 ]:

**Comment by ryandesign** [comment]
> But it appears to be safe to only escape an underscore if it's preceded by a space...

And pandoc currently puts a backslash before every underscore? So I could fix it by searching for every backslash-underscore not preceded by whitespace, and delete the backslash?

**Comment by rinetd** [comment]
escaped < > is not working yet :sob:

**Comment by jgm** [comment]
Are you sure you're using pandoc 1.18?  It works fine for me:

% echo '\<hi\>' | pandoc -f markdown_github
<p>&lt;hi&gt;</p>

If it's not working for you, please give pandoc version
(output of pandoc --version) and specific instructions
for reproducing the problem.

+++ rinetd [Nov 16 16 23:21 ]:

**Comment by jlwaugh** [comment]
4,294,967,295 > 888
