### ISSUE TITLE
Blank line after \paragraph in LaTeX

### ISSUE THREAD

**Issue by bgrenet** [jgm/pandoc#2807]
By default, LaTeX does not insert a line break after the command `\paragraph` (headers of level 4). Though, in release 1.14 (through ticket #1658) a systematic blank line was introduced after a `\paragraph`. Thus, this breaks the _normal_ behavior of LaTeX for these headers.

For instance,

```
#### Header of level 4
The corresponding paragraph that follows.
```

is converted to

```
\paragraph{Header of level 4}\label{header-of-level-4}

The corresponding paragraph that follows.
```

while it should be (for LaTeX normal behavior to be respected)

```
\paragraph{Header of level 4}\label{header-of-level-4}
The corresponding paragraph that follows.
```

**Comment by jgm** [comment]
Yes, this was intentionally changed so that pandoc's
LaTeX/PDF output will more closely match what you get in
other formats.

You can make a change to the template if you don't want
this.  (It should be fairly obvious which lines are doing
this.)


+++ Bruno Grenet [Mar 23 16 03:04 ]:
