### ISSUE TITLE
Conversion from txt to pdf does not format pdf output properly

### ISSUE THREAD

**Issue by ag91** [jgm/pandoc#2808]
Hello

many many thanks for pandoc: it is a marvellous and precious piece of software!

Here an issue in converting txt to pdfs: 
if the txt file contains a long line, 
pandoc does not adapt it to the pdf page and the line vanishes out of the border.

I attach a txt test file and the outputs of pandoc and soffice (which returns a formatted output):

[pandocissue.txt](https://github.com/jgm/pandoc/files/186457/pandocissue.txt)
[pandocissue_pandoc.pdf](https://github.com/jgm/pandoc/files/186460/pandocissue_pandoc.pdf)
[pandocissue_soffice.pdf](https://github.com/jgm/pandoc/files/186461/pandocissue_soffice.pdf)

I tried with pandoc 1.17 and pandoc 1.17.0.2 and got the same result.
Thanks again!

**Comment by jgm** [comment]
Pandoc (or more properly latex which creates the PDF) will
break the lines if they contain spaces.  But you don't have
enough spaces in the line, hence there are no good places to
break it.

So, this isn't a bug.

+++ ag91 [Mar 23 16 10:05 ]:

**Comment by ag91** [comment]
I did not know that: thanks!
I am closing this. Sorry for it.
