### ISSUE TITLE
Css class for paragraphs is lost when converting to JSON

### ISSUE THREAD

**Issue by Ishitori** [jgm/pandoc#2816]
Hi,

I am converting an html page to AST (in json) and it seems I lose css classes for <p> items. So for something like this in initial html:

`<p class="header-5b1">EXTRA CREDIT</p>
`
I get:
`                        "t": "Para",
                        "c": [
                          {
                            "t": "Str",
                            "c": "EXTRA"
                          },
                          {
                            "t": "Space",
                            "c": []
                          },
                          {
                            "t": "Str",
                            "c": "CREDIT"
                          }
                        ]
                      },`

The css class is not there.
Is it possible to fix that problem? Can it be a special flag I need to provide? Currently processing goes with the following parameters:

> pandoc input.html -f html -t json -o ouput.html --extract-media=media

**Comment by jgm** [comment]
Pandoc's AST does not provide any way to represent attributes on paragraphs.  So this just gets discarded.

**Comment by Ishitori** [comment]
But it does provide css class for Divs. What is the difference between these?
