### ISSUE TITLE
Guide to special char ?

### ISSUE THREAD

**Issue by ponsfrilus** [jgm/pandoc#2817]
Hi all,
    is there a guide to use special char in markdown to html or pdf convertion ?

For example I would like to have [Unicode Character 'WORLD MAP' (U+1F5FA)](http://www.fileformat.info/info/unicode/char/1f5fa/index.htm) "🗺" in my document, but I can't find a way to succeed.

Any help welcome...

Thanks !

**Comment by wilx** [comment]
You could try this. It works for me in a small test:

~~~~{.latex}
\usepackage{fontspec}
\usepackage{newunicodechar}
\newfontfamily\worldfont{Symbola}
\newunicodechar{🗺}{{\worldfont\char"1F5FA}}
~~~~

**Comment by jgm** [comment]
+++ Nicolas Borboën [Mar 26 16 03:58 ]:
>   Hi all,
>   is there a guide to use special char in markdown to html or pdf
>   convertion ?

You can just put the character in your input document.
Or use an escaped version:

    &#x1F5Fa;

Whether this renders properly in HTML or PDF will depend on
what fonts you're using.  Also, be sure to use
--latex-engine=xelatex when producing PDF.
