### ISSUE TITLE
Add --first-note-number option or honor a similar field in metadata

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#2819]
(Sorry if this is a duplicate. I did a search but couldn't find anything.)

Would you please add a --first-note-number option or honor a similar field in metadata?
The use case is that I have a single text spanning several target documents and I want footnotes to be numbered continuously throughout these documents.

**Comment by jgm** [comment]
Why not put all the documents on the command line; then pandoc will treat them as one and you'll get the numbering you want?

Pandoc doesn't store note numbers in the AST.  Numbering is automatic and depends on the output format.  So the change you're suggesting would require separate implementation in every pandoc writer; it's not a minor change.
