### ISSUE TITLE
cannot pass utf8 to -M author="..."

### ISSUE THREAD

**Issue by rkitover** [jgm/pandoc#2820]
I am passing

```bash
pandoc ... -M author='Abdó Roig-Maranges <abdo.roig@gmail.com>' 
```
for one of my files (he is a contributor to my project) but it comes out as:

```
AbdA3 Roig-Maranges <abdo.roig@gmail.com>
```

in the generated man page.

**Comment by jgm** [comment]
What's your locale?  Use a UTF-8 locale with pandoc.

+++ Rafael Kitover [Mar 27 16 08:04 ]:

**Comment by rkitover** [comment]
Sorry, this was my own code screwing this up, nothing wrong with the -M option.
