### ISSUE TITLE
pandoc should convert all non-breaking spaces to ~ in LateX

### ISSUE THREAD

**Issue by legrostdg** [jgm/pandoc#2826]
When converting a .md to .tex with pandoc, most of non-breaking spaces are converted to "~", but not all of them (very often in footnotes). Some U+202F remains, so pdflatex fails.

    ...
    ! Package inputenc Error: Unicode char   (U+202F)
    (inputenc)                not set up for use with LaTeX.
    ...

**Comment by jgm** [comment]
Please supply an example (as minimal as possible) that allows
us to reproduce the problem.

**Comment by legrostdg** [comment]
$ cat test.md
    test[^1]
    
    [^1]: Test, *Test !*, *op. cit.*, p. 14.

(with U+202F, non-breaking space between "Test" and "!", "op." and "cit.", "p." and "14.")

    $ pandoc test.md -o test.tex
    $ cat test.tex
    test\footnote{Test, \emph{Test !}, \emph{op.~cit.}, p.~14.}
    $ pdflatex test.tex
    This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
    restricted \write18 enabled.
    entering extended mode
    (./test.tex
    LaTeX2e <2016/02/01>
    Babel <3.9q> and hyphenation patterns for 5 language(s) loaded.
    
    ! LaTeX Error: Missing \begin{document}.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.1 t
         est\footnote{Test, \emph{Test !}, \emph{op.~cit.}, p.~14.}
    ?

**Comment by legrostdg** [comment]
(It seems to work with any utf-8 character)

    $ cat test.md
    t[^1]
    
    [^1]: é

**Comment by jgm** [comment]
Sorry, can you be more specific?  What is the exact command
you are using, what do you see, and what do you expect to
see?  What pandoc version are you using?

When I convert a document with a nonbreaking space in
a footnote to latex, I get a ~ in the footnote.

+++ legrostdg [Mar 30 16 10:47 ]:

**Comment by legrostdg** [comment]
You get one ~, or three?
I get:

    $ pandoc test.md -o test.tex
    $ cat test.tex
    test\footnote{Test, \emph{Test !}, \emph{op. cit.}, p.~14.}

so one ~, but two non-breaking spaces.

    $ pandoc --version
    pandoc 1.16.0.2

I (pdflatex) would need three non-breaking spaces

**Comment by jgm** [comment]
U+202F is a "NARROW NO-BREAK SPACE."

~ in LaTeX is for U+00A0, a regular no-break space.

So, it wouldn't be appropriate to produce ~.

Generally, if your source document uses non-ascii
characters, you should use `--latex-engine=xelatex`
with pandoc.  Pandoc doesn't try to convert e.g.
`é` into `\'{e}`.  It does handle regular U+00A0
nonbreaking spaces, but that's a special case because
these are fairly common.

**Comment by legrostdg** [comment]
--latex-engine=xelatex does not work either in this case...

I initially created the .md with "pandoc test.odt -o test.md". If there is absolutely no way pandoc could have introduced these U+202F, it may be related to the way zotero / the libreoffice zotero-connector write footnotes (citations).

I also had U+300 instead of 'è', U+301 instead of 'é'. All problems preventing the .tex to be converted to .pdf were in footnotes, and I had something like 10 errors in a 5000 lines document.

**Comment by jgm** [comment]
+++ legrostdg [Apr 08 16 06:25 ]:
>   --latex-engine=xelatex does not work either in this case...

I just tried it; it worked fine with your test.md and --latex-engine=xelatex.

> I also had U+300 instead of 'è', U+301 instead of 'é'.

That's puzzling.  But it sounds like maybe it's an ODT -> MD issue
rather than a MD -> PDF issue.  Does the MD you obtained
from ODT have the proper characters? If not, try to create
a small ODT that allows us to reproduce the problem.

**Comment by legrostdg** [comment]
You're right: I'm confused, it seems to actually compile with xelatex.

I just checked the .odt file: it definitely seems to be a problem with zotero/libreoffice: the words with "é" in the footnotes are not searchable.

Thanks! (and sorry for this false alarm)
