### ISSUE TITLE
YAML metadata incorrectly interpreted when Markdown dialect is specified

### ISSUE THREAD

**Issue by beatngu13** [jgm/pandoc#2827]
I usually use a YAML header to specify various variables before I transform my Markdown documents into other formats, e.g. PDF.

Since Pandoc supports [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), I often prefer this variant because it provides an additional set of useful features. One of this features is to automatically interpret URLs as hyperlinks.

The [MWE](https://github.com/jgm/pandoc/files/195501/mwe.txt) (change the suffix to `.md`) attached to this issue contains a simple YAML header where I set the color for those links. Unfortunately this is only taken into account if I use CommonMark syntax and the following command line:

`pandoc mwe.md --latex-engine=xelatex -o mwe.pdf `

If I add `--from=markdown_github` the links are recognized, but they're not colored and the YAML metadata is interpreted as plain text.

I use Pandoc 1.17.0.2 on Mac OS X El Capitan (10.11.4).

**Comment by jgm** [comment]
Try:

    pandoc mwe.md -f markdown_github+yaml_metadata_block \
      -o mwe.pdf -Vlinkcolor=blue

+++ beatngu13 [Mar 30 16 05:54 ]:

**Comment by beatngu13** [comment]
That does the trick. Thanks for your prompt reply!

**Comment by jdhao** [comment]
`-f github_markdown` is deprecated. The new command should be
``
pandoc -f gfm -Vurlcolor=blue -o test.pdf test.md
``

**Comment by FilBot3** [comment]
So should it be:

```bash
pandoc \
  --from=gfm+yaml_metadata_block \
  --to=latex \
  --output=my_document.pdf \
  title.yml \
  my_document.md
```

I tried that, and it didn't seem to process it correctly.

**Comment by jgm** [comment]
the yaml_metadata_block extension is not supported for gfm at this point.

**Comment by FilBot3** [comment]
Thank you for the clarification!

**Comment by abitrolly** [comment]
I am so glad I found this issue. )
