### ISSUE TITLE
rst writer: export raw LaTeX as "math"?

### ISSUE THREAD

**Issue by mgeier** [jgm/pandoc#2830]
Is there an option (or some other way) to make pandoc convert raw LaTeX blocks to the reStructuredText directive `math::` instead of `raw:: latex`?

I would like to convert Markdown text with raw LaTeX blocks to reStructuredText. This, in turn, should be used as Sphinx source to generate both HTML and LaTeX documents.

A little example:

```latex
some *Markdown* text

\begin{equation}
\int_{-\infty}^\infty f(x) \delta(x - x_0) dx = f(x_0)
\end{equation}

more text
```

Converted to `rst`, this looks like:

```latex
some *Markdown* text

.. raw:: latex

   \begin{equation}
   \int_{-\infty}^\infty f(x) \delta(x - x_0) dx = f(x_0)
   \end{equation}

more text
```

... which of course works fine for LaTeX output, but not for HTML.

Is there a way to get the following output instead?

```latex
some *Markdown* text

.. math::

   \begin{equation}
   \int_{-\infty}^\infty f(x) \delta(x - x_0) dx = f(x_0)
   \end{equation}

more text
```

**Comment by mgeier** [comment]
This is probably not the right forum for such a question, so I asked it at stackoverflow: http://stackoverflow.com/questions/36339571/pandoc-rest-writer-export-raw-latex-as-math-directive

**Comment by jgm** [comment]
The place to ask questions like this is the pandoc-discuss
mailing list. This tracker is for bug reports rather than
questions.

+++ Matthias Geier [Mar 31 16 10:16 ]:

**Comment by mgeier** [comment]
Thanks, I posted it to the list: https://groups.google.com/forum/#!topic/pandoc-discuss/EvvlHfxzC3c

Sorry for the noise!
