### ISSUE TITLE
table cells in word document are missing during the conversion if the table has merged cells

### ISSUE THREAD

**Issue by strace-zz** [jgm/pandoc#2831]
create a table in word document, like:

![image](https://cloud.githubusercontent.com/assets/339576/14204056/46517aa2-f84d-11e5-90fd-67f9002d4312.png)

the ast json file has all content of the table,
but if I convert it to other format, e.g. plain, html, markdown...
the content of the second cell in the second row will lost.

**Comment by jgm** [comment]
Pandoc doesn't currently support colspans (merged cells) in its internal document model.
Best we can hope for is a better warning here, so I'm closing this in favor of #2783
