### ISSUE TITLE
definition lists issue

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#2833]
I am experiencing weird issue with definition lists. The following test case produces a list item followed by a paragraph and preformatted text instead of definition list. However, if I just switch the order of the two definitions and put `p. 19` first and `s. 19` second, both entries suddenly produce definition lists.

~~~~{.md}
s. 19, word

:   word defintion

    * [link](http://example.com)
    * item
    * another item
    
p. 19, word

:   word defintion

    * [link](http://example.com)
    * item
    * another item
~~~~

This is with pandoc 1.17.0.2.

**Comment by adunning** [comment]
It works if you escape the periods to prevent it from recognizing these as lists, like so:

```markdown
s\. 19, word

:   word defintion

    * [link](http://example.com)
    * item
    * another item

p\. 19, word

:   word defintion

    * [link](http://example.com)
    * item
    * another item
```

**Comment by jgm** [comment]
That's right.  Since you can start ordered lists with
letters in pandoc, the `s.` is getting interpreted as a
list.

Since `p.` is so common (in English texts anyway), I have
a pretty unprincipled exclusion for `p.` in the parser,
which is what explains the difference.

**Comment by wilx** [comment]
@jgm OK. I can live with the escaped dot.
