### ISSUE TITLE
Tabs turn into spaces in embedded HTML <pre> tag

### ISSUE THREAD

**Issue by borisvassilev** [jgm/pandoc#2835]
This might be related to #2804, or not at all. I can't say if it a regression this time. Again, easy to reproduce, but not so easy to notice, or to show: GitHub does something weird with tabs, too. I attach the two files from this command:

    $ pandoc foo.txt >foo.html.txt

Opening both with a browser should make it obvious.

PS. From what I understand, really **all** white space is supposed to be preserved in a `<pre>` tag.

[foo.txt](https://github.com/jgm/pandoc/files/200058/foo.txt)
[foo.html.txt](https://github.com/jgm/pandoc/files/200060/foo.html.txt)

**Comment by borisvassilev** [comment]
Hmm, it seems that I am not able to figure out the "attach files" thing here. It is trivial to reproduce, anyway. This input file should be enough:

```
<pre>
a [tab character here] b
</pre>
```

**Comment by borisvassilev** [comment]
Note: an embedded `&#9;` in the markdown portion of a document actually does get converted to a single tab character in the output:

    $ cat bar.txt
    &#9;some text 
    $ pandoc bar.txt
    <p>	some text</p>

Again, GitHub doesn't show this correctly, but between the opening `<p>` and `some text` there is a single tab character in the output of Pandoc.

**Comment by jgm** [comment]
Pandoc, like most Markdown processors, expands all tabs with a 4-space tab stop before parsing.
Even in code blocks.

CommonMark is an exception, so you could try `-f commonmark` if you don't need pandoc-specific extensions.

**Comment by jgm** [comment]
I'm sorry, I'd forgotten to mention the `--preserve-tabs` option!
