### ISSUE TITLE
[feature request] Implement `--toc` support for ODT writer

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2836]
As is documented in the README, the `--toc` parameter does only work with several output formats, amongst these DOCX.

It would be nice to get this working for ODT output too. It is clear that Pandoc cannot generate a full Table of Content all by itself (because it would have to render the ODT to find the respective page numbers to be used). 

But what is the major obstacle that prevents it from doing it similar to the DOCX writer: create an empty Table of Contents, which could quickly be populated with correct entries once the ODT is opened in LibreOffice (similar as it is for DOCX on MS Word)?

**Comment by anayrat** [comment]
:+1:

**Comment by anayrat** [comment]
Here a template with a table of content.

You can use the variable `toc-title: foo` to add the toc.

[default.opendocument.zip](https://github.com/jgm/pandoc/files/407739/default.opendocument.zip)

**Comment by jgm** [comment]
@anayrat, thanks!
