### ISSUE TITLE
[feature request] Implement `--extract-media` for ODT reader

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2837]
As is documented in the README, Pandoc currently does support the `--extract-media=DIR` parameter only for EPUB and DOCX readers.

Now I'm not sure what kind of other media are supported apart from images. Even if it would be difficult to support embedded multimedia types, at least supporting images should be not too difficult.

For ODT (very similar to DOCX), the embedded images are in subfolder of the archive: it's `Pictures/`, and the contained filetypes may be JPEG, PNG and SVG. (For DOCX it is `word/media/` -- but I'm not sure if SVG can also happen to be amongst the file types, JPEG and PNG certainly are).

It would be nice if the DOCX reader would also extract the `Pictures/` folder from the Zip and place all content into the `--extract-media`-defined DIR. If possible it should also generate the respective references in output Markdown (don't know how difficult _this_ is -- but at least extracting the images to the requested media-DIR should be easily doable...).

**Comment by jgm** [comment]
@MarLinn

**Comment by hubertp-lshift** [comment]
With https://github.com/jgm/pandoc/pull/3165 in place, it looks like this one is fixed. @KurtPfeifle can you verify, please?

**Comment by jgm** [comment]
Tested, yes, this is done.
