### ISSUE TITLE
pandoc-citeproc.exe: could not find locale data for EN-UK

### ISSUE THREAD

**Issue by TheOddler** [jgm/pandoc#2838]
I'm trying to build my markdown file with a bibtex file for citations. However when I run the command "pandoc -s -S --filter pandoc-citeproc paper.md --bibliography refs.bibtex -o paper.pdf" I get the following error:

```
pandoc-citeproc.exe: could not find locale data for EN-UK
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

Why do I get this error? I'm working on Windows 7, using Pandoc 1.17.0.2.

**Comment by ousia** [comment]
@TheOddler, I guess the right language (or locale) is `en-GB`.

**Comment by TheOddler** [comment]
And how do you set the language for pandoc-citeproc?

**Comment by ousia** [comment]
Sorry, but why don’t you invoke `pandoc -s -S --filter pandoc-citeproc paper.md --bibliography refs.bibtex -o paper.pdf`?

Do you get the same error as before?

**Comment by TheOddler** [comment]
The only difference is the `.bibtex` extension, right? I tried that too, but got the same error.

**Comment by jgm** [comment]
Does `--metadata lang=en-GB` help at all?

**Comment by TheOddler** [comment]
@jgm it does not :(

`pandoc -s -S --filter pandoc-citeproc paper.md --bibliography refs.bibtex --csl style.csl --metadata lang=en-GB -o paper.pdf` Again gives the same error.

(Note: I now also added a style for my references. It does work on my mac, so for the moment I'm just using that to build it.)

**Comment by jgm** [comment]
If there is a way to set environment variables on your
Windows system, try setting LANG to en-GB before running
pandoc.

+++ Pablo Bollansée [Apr 05 16 02:14 ]:

**Comment by TheOddler** [comment]
@jgm That solved it! Well, at least your answer made me find what was going wrong. I checken my system variables, and for some reason "LANG" was set to "en-UK". I simply removed it, and now it runs perfectly.

**Comment by jgm** [comment]
I've fixed things in the dev version so that it will work
properly if you set the metadata field, even if LANG is
misconfigured.

+++ Pablo Bollansée [Apr 05 16 09:48 ]:

**Comment by TheOddler** [comment]
Awesome! :dancer: Happy to help find a bug :D
