### ISSUE TITLE
[feature request] Implement preservation of "Custom Properties" document metadata to ODT reader

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2839]
In LibreOffice and OpenOffice authors can add "Custom Properties" metadata to their documents (via menu _"File -> Properties..."_). The screenshot shows how this can look for example:

![](http://i.stack.imgur.com/5cpb9.png)

Some of these properties are pre-defined in LibreOffice and may be selected from a drop-down list. Users can also add their own custom property names and values and assign a type from a drop-down list.

Whatever is defined in this dialog ends up in the file `meta.xml` inside the ODT Zip archive. Here is the difference of two LibreOffice _HelloWorld_ documents, one of which has custom properties defined:

```
$ kp@mbp:~>  sdiff -sbB <(unzip -l helloworld-ohne-custom-properties.odt) <(unzip -l helloworld-with-custom-properties.odt)
 Archive: helloworld-ohne-custom-properties.odt            | Archive:  helloworld-with-custom-properties.odt
       39 04-02-2016 13:37 mimetype                        |       39 04-02-2016 13:51 mimetype
      494 04-02-2016 13:37 Thumbnails/thumbnail.png        |      494 04-02-2016 13:51 Thumbnails/thumbnail.png
     3335 04-02-2016 13:37 content.xml                     |     3335 04-02-2016 13:51 content.xml
        0 04-02-2016 13:37 Configurations2/toolpanel/      |        0 04-02-2016 13:51 Configurations2/toolpanel/
        0 04-02-2016 13:37 Configurations2/popupmenu/      |        0 04-02-2016 13:51 Configurations2/popupmenu/
        0 04-02-2016 13:37 Configurations2/images/Bitmaps/ |        0 04-02-2016 13:51 Configurations2/images/Bitmaps/
        0 04-02-2016 13:37 Configurations2/accelerator/cur |        0 04-02-2016 13:51 Configurations2/accelerator/cur
        0 04-02-2016 13:37 Configurations2/floater/        |        0 04-02-2016 13:51 Configurations2/floater/
        0 04-02-2016 13:37 Configurations2/menubar/        |        0 04-02-2016 13:51 Configurations2/menubar/
        0 04-02-2016 13:37 Configurations2/statusbar/      |        0 04-02-2016 13:51 Configurations2/statusbar/
        0 04-02-2016 13:37 Configurations2/toolbar/        |        0 04-02-2016 13:51 Configurations2/toolbar/
        0 04-02-2016 13:37 Configurations2/progressbar/    |        0 04-02-2016 13:51 Configurations2/progressbar/
      899 04-02-2016 13:37 manifest.rdf                    |      899 04-02-2016 13:51 manifest.rdf
    11742 04-02-2016 13:37 styles.xml                      |    11742 04-02-2016 13:51 styles.xml
    10392 04-02-2016 13:37 settings.xml                    |    10392 04-02-2016 13:51 settings.xml
     1099 04-02-2016 13:37 meta.xml                        |     2032 04-02-2016 13:51 meta.xml
     1086 04-02-2016 13:37 META-INF/manifest.xml           |     1086 04-02-2016 13:51 META-INF/manifest.xml
    29086                  17 files                        |    30019                  17 files
```

Here are the contents of the "_without-custom-properties"_ LibreOffice-generated `meta.xml` file:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<office:document-meta
    xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
    xmlns:ooo="http://openoffice.org/2004/office"
    xmlns:grddl="http://www.w3.org/2003/g/data-view#"
    office:version="1.2">
<office:meta>
    <meta:initial-creator>Kurt Pfeifle</meta:initial-creator>
    <meta:creation-date>2016-04-02T14:30:40.237096000</meta:creation-date>
    <dc:date>2016-04-02T15:37:25.142271000</dc:date>
    <dc:creator>Kurt Pfeifle</dc:creator>
    <meta:editing-duration>PT1H5M9S</meta:editing-duration>
    <meta:editing-cycles>3</meta:editing-cycles>
    <meta:generator>LibreOffice/5.1.1.3$MacOSX_X86_64 LibreOffice_project/89f508ef3ecebd2cfb8e1def0f0ba9a803b88a6d</meta:generator>
    <meta:document-statistic
        meta:table-count="0"
        meta:image-count="0"
        meta:object-count="0"
        meta:page-count="1"
        meta:paragraph-count="1"
        meta:word-count="2"
        meta:character-count="13"
        meta:non-whitespace-character-count="12"/>
</office:meta>
</office:document-meta>
```

Here are the contents of the "**_with**_-_custom-properties"_ LibreOffice-generated `meta.xml` file:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<office:document-meta
    xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
    xmlns:ooo="http://openoffice.org/2004/office"
    xmlns:grddl="http://www.w3.org/2003/g/data-view#"
    office:version="1.2">
<office:meta>
    <meta:initial-creator>Kurt Pfeifle</meta:initial-creator>
    <meta:creation-date>2016-04-02T14:30:40.237096000</meta:creation-date>
    <dc:date>2016-04-02T14:36:01.947516000</dc:date>
    <dc:creator>Kurt Pfeifle</dc:creator>
    <meta:editing-duration>PT3M46S</meta:editing-duration>
    <meta:editing-cycles>2</meta:editing-cycles>
    <meta:generator>LibreOffice/5.1.1.3$MacOSX_X86_64 LibreOffice_project/89f508ef3ecebd2cfb8e1def0f0ba9a803b88a6d</meta:generator>
    <meta:document-statistic
        meta:table-count="0"
        meta:image-count="0"
        meta:object-count="0"
        meta:page-count="1"
        meta:paragraph-count="1"
        meta:word-count="2"
        meta:character-count="13"
        meta:non-whitespace-character-count="12"/>
    <meta:user-defined meta:name="Checked by">me</meta:user-defined>
    <meta:user-defined meta:name="Client">my client</meta:user-defined>
    <meta:user-defined meta:name="Date completed" meta:value-type="date">2016-04-02T00:00:00</meta:user-defined>
    <meta:user-defined meta:name="Department">my department</meta:user-defined>
    <meta:user-defined meta:name="Destinations" meta:value-type="string">my destinations</meta:user-defined>
    <meta:user-defined meta:name="Disposition" meta:value-type="boolean">false</meta:user-defined>
    <meta:user-defined meta:name="Division" meta:value-type="string">my division</meta:user-defined>
    <meta:user-defined meta:name="MyCustomNumber" meta:value-type="float">123456789</meta:user-defined>
    <meta:user-defined meta:name="MyCustomProperty" meta:value-type="string">0123456789abcdefghijklmnopqrstuvwxyz</meta:user-defined>
    <meta:user-defined meta:name="Reference" meta:value-type="string">my reference</meta:user-defined>
</office:meta>
</office:document-meta>
```

Here are the (minimalist) contents of the `meta.xml` file from a Pandoc-generated ODT file:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<office:document-meta
    xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
    xmlns:ooo="http://openoffice.org/2004/office"
    xmlns:grddl="http://www.w3.org/2003/g/data-view#"
    office:version="1.2">
    <office:meta>
        <dc:title>
    </dc:title>
</office:meta>
```

As can be seen, it doesn't include any `<meta:user-defined ...>...</meta:user-defined>` keys.

However, it would be nice to have these as well as keys with respective values for `<meta:initial-creator>` (use same value as Pandoc would use for _$author_), `<meta:creation-date>` (use current date+time) and `<meta:generator>` (use output of `pandoc --version | head -n 2` or similar).

I don't know how difficult it would be to implement this. However, it looks like some or most of these values could be stored in a YAML structure (although I've not yet dived deep enough into YAML in order to even start understanding what I'm talking about here -- so far I myself use the three lines of `pandoc_title_block`  (_`% title,   % author(s),   %date`_) for most of my documents).

So the ODT reader could preserve the contents of these fields in a `yaml_metadata_block` structure for being re-used with Markdown.
## Where this would be most useful

This feature would be most useful if Pandoc's ODT reader could extract the custom metadata keys including their values from the file referenced with `--reference-odt=...` and its ODT writer would put it into the newly generated ODT. (For cases where that isn't wanted, implement an _"--odt-metadata-transfer=no"_ parameter.)

The clou is that power users of ODT frequently define these keys and then use them as values of custom _Field Variables_ (from the LibreOffice menu go _Insert -> Field -> More Fields... -> DocInformation -> Custom_ to see what I mean). Such field variables may be used in page headers and footers, or inside other areas of the document contents.

Currently, if a reference-odt file uses such custom metadata keys they are lost in the generated ODT file. They have to be manually inserted again into the new document (which in many cases defeats the use of Pandoc). On the other hand, the generated ODT file still has "some-unknown-field-value-was-inserted-here" place-holders for these custom keys, however, these are empty. And standard "field" magic such as using _"Page `3` of `12`"_ in page footers work well when defined in the reference ODT: they **_do**_ get correctly transferred over to the newly generated ODT document.

**Comment by jgm** [comment]
Commit b60c64d06e1fa7d5f3e41cc0c93da965a286e11c supports these custom metadata fields in the writer.

**Comment by maxbes** [comment]
There seems to be a mistake in that commit. I generated md file with a "customname:customvalue" property, and the generated ODT looks like this:

```
<meta:user-defined meta_name="customname" meta-value-type="string">customvalue</meta:user-defined>
```

According to section 3.2 of ![The ODT spec](http://docs.oasis-open.org/office/v1.1/OS/OpenDocument-v1.1-html/OpenDocument-v1.1.html) it should instead look like
```
<meta:user-defined meta:name="customname" meta:value-type="string">customvalue</meta:user-defined>
```

**Comment by agusmba** [comment]
Indeed, thanks @maxbes for identifying the typo.
