### ISSUE TITLE
pandoc on iOS?

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#2840]
Are there any port of pandoc on iOS?

The only one I've seen so far is [Using Pandoc on iOS (Sorta) | W. Caleb McDaniel](http://wcm1.web.rice.edu/pandoc-on-ios.html), which uses an Editorial workflow to pass the file to Docverter to convert it by pandoc. But it is not running locally, so there are potential privacy issues.

**Comment by jgm** [comment]
Questions should go to pandoc-discuss mailing list, not here.
