### ISSUE TITLE
`pandoc -t latex --biblatex` sometimes provides unexpected empty output

### ISSUE THREAD

**Issue by bwhelm** [jgm/pandoc#2841]
With pandoc 1.17.0.2:

`echo "# Testing" | pandoc -t latex --biblatex`

produces empty output. By contrast, 

`echo "## Testing" | pandoc -t latex --biblatex`

produces what you'd expect:

`\subsection{Testing}\label{testing}`

The same is true when `--natbib` is used instead of `--biblatex`. However, the problem does not appear when not using `-t latex`.

**Comment by jgm** [comment]
I see why:  src/Text/Pandoc/Writer/LaTeX.hs line 95ff:

    -- Strip off final 'references' header if --natbib or --biblatex
    let method = writerCiteMethod options
    let blocks' = if method == Biblatex || method == Natbib
                     then case reverse blocks of
                               (Div (_,["references"],_) _):xs -> reverse xs
                               _ -> blocks
                     else blocks

The idea is that if they have a document that ends with `# References` (or
some other empty section header designed to catch the references), this
should not be printed when `--biblatex` or `--natbib` is used.

I'm not sure anything should be done about this:  it's a useful feature
(allowing you to use the same source document with either citeproc
or natbib or biblatex), and it only causes bad results in a case
that is unlikely to arise in a normal finished document.

**Comment by bwhelm** [comment]
That makes sense.

What I'm trying to do is get forward-sync to work between markdown and pdf. Inside my text editor I have a script to grab the current paragraph of markdown text, run it through pandoc to generate LaTeX, locate the line number in which that LaTeX text occurs in the .tex file, and then tell the pdf viewer to jump to that place in the .pdf document. It works almost everywhere except in first-level headings. I can easily create a workaround for this case.

Thanks!
