### ISSUE TITLE
Cannot convert Markdown list to PDF

### ISSUE THREAD

**Issue by Honestpuck** [jgm/pandoc#2843]
Using pandoc 1.16.0.2 on OS X 10.11 installed by Homebrew and attempting to convert a Markdown document to a PDF. It fails to convert giving a Latex error.

Input  (also attached):
```
### Before We Begin

- Install Homebrew
- coreutils
- source-highlight
```

Error:
```
 LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.58   I

pandoc: Error producing PDF
```

There is no problem creating HTML or DOCX files.

// Tony Williams

[test.txt](https://github.com/jgm/pandoc/files/203899/test.txt)

**Comment by jgm** [comment]
That's odd.  Try with `--verbose` flag; that should tell you exactly what
the intermediate latex file is, which is necessary for debugging. You can
post here.

**Comment by alexcu** [comment]
@jgm Getting the exact same issues as @Honestpuck; only happening when converting lists to markdown. Running OS X 10.11.4, Pandoc installed using Homebrew (`pandoc 1.17.0.3`).

Using the same input I produced the following [TeX](https://github.com/jgm/pandoc/files/237648/tex.txt) file. Here is the [log](https://github.com/jgm/pandoc/files/237647/log.txt) Pandoc logged using the `--verbose` switch.

**Comment by jgm** [comment]
From the tex output it looks like you're using the `--incremental` option with pandoc, which is intended for slide formats only.

**Comment by jgm** [comment]
By the way, with pandoc bug reports it's always very useful to give (a) the complete pandoc command line you used, (b) the input file.

**Comment by alexcu** [comment]
Yes you're right—I must have been confusing `-i` for `input`. Without `-i` it works fine 👍

**Comment by jgm** [comment]
I'll fix pandoc so that -i doesn't do anything if you use -t latex rather than -t beamer.

+++ Alex Cummaudo [Apr 26 16 21:43 ]:
