### ISSUE TITLE
Don't output \caption in LaTeX when image alt text is empty

### ISSUE THREAD

**Issue by Adri2000** [jgm/pandoc#2844]
Tested with .md as input, LaTeX/Beamer as output.
`![](image.png)` will generate `\caption{}`.

This is a regression according to https://groups.google.com/forum/#!topic/pandoc-discuss/9H_3h20ILj0. Maybe in commit d81b4358ea8d0da615c01a468196fd0592934af6.

Proposed patch on master:

```
diff --git a/src/Text/Pandoc/Writers/LaTeX.hs b/src/Text/Pandoc/Writers/LaTeX.hs
index 9526333..4fac59a 100644
--- a/src/Text/Pandoc/Writers/LaTeX.hs
+++ b/src/Text/Pandoc/Writers/LaTeX.hs
@@ -417,7 +417,9 @@ blockToLaTeX (Para [Image attr@(ident, _, _) txt (src,'f':'i':'g':':':tit)]) = d
   img <- inlineToLaTeX (Image attr txt (src,tit))
   let footnotes = notesToLaTeX notes
   lab <- labelFor ident
-  let caption = "\\caption" <> captForLof <> braces capt <> lab
+  let caption = if null text
+                   then empty
+                   else "\\caption" <> captForLof <> braces capt <> lab
   figure <- hypertarget ident (cr <>
             "\\begin{figure}[htbp]" $$ "\\centering" $$ img $$
             caption $$ "\\end{figure}" <> cr)
```

Not tested, but I successfully tested a similar patch for the pandoc version that's running on my laptop.

**Comment by jgm** [comment]
The change you suggest would mean that uncaptioned images don't get labels, even if an ID is specified.

**Comment by Adri2000** [comment]
Sorry, not sure I understand exactly what you mean. Do you have an example?

**Comment by jgm** [comment]
`![](img.jpg){#myimage}`

With the proposed change, you won't get `\label{myimage}` anywhere in the figure.

**Comment by Adri2000** [comment]
Does the following look better? If not please don't hesitate to just fix it and commit, as I'm really not familiar with Haskell, and not much with Pandoc either :)

Thanks!

```
diff --git a/src/Text/Pandoc/Writers/LaTeX.hs b/src/Text/Pandoc/Writers/LaTeX.hs
index 9526333..683d737 100644
--- a/src/Text/Pandoc/Writers/LaTeX.hs
+++ b/src/Text/Pandoc/Writers/LaTeX.hs
@@ -417,7 +417,9 @@ blockToLaTeX (Para [Image attr@(ident, _, _) txt (src,'f':'i':'g':':':tit)]) = d
   img <- inlineToLaTeX (Image attr txt (src,tit))
   let footnotes = notesToLaTeX notes
   lab <- labelFor ident
-  let caption = "\\caption" <> captForLof <> braces capt <> lab
+  let caption = if null text
+                   then lab
+                   else "\\caption" <> captForLof <> braces capt <> lab
   figure <- hypertarget ident (cr <>
             "\\begin{figure}[htbp]" $$ "\\centering" $$ img $$
             caption $$ "\\end{figure}" <> cr)
```

**Comment by jgm** [comment]
On reflection, I guess that without `\caption`, it probably
doesn't make sense to have `\label`, since there will be no
figure number to refer to.

But that raises the question what behavior would be better.
Some might expect that a figure with empty caption would
still get a figure number and be labelable.

+++ Adrien Cunin [Apr 20 16 06:28 ]:

**Comment by Adri2000** [comment]
Hi,
What's the best way to move forward on this issue?

**Comment by jgm** [comment]
Fixing this by requiring a non-empty caption for `implicit_figures`.

**Comment by jgm** [comment]
Note:  you'll now get no figure at all (not just a figure without a `\caption`) if you have empty alt text.
