### ISSUE TITLE
'<' and '>' not escaped

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#2846]
Pandoc version: 1.17
Command:
```bash
# pandoc -f markdown_github -t html
IRepository\<T\>
```
Expected output:
```
<p>IRepository&lt;T&gt;</p>
```
Actual output:
```
<p>IRepository\<T\></p>
```
It works in `pandoc -f markdown -t html`

**Comment by jgm** [comment]
Test: \<hi\>

**Comment by jgm** [comment]
From the Markdown syntax guide by John Gruber:
```
Markdown provides backslash escapes for the following characters:

\   backslash
`   backtick
*   asterisk
_   underscore
{}  curly braces
[]  square brackets
()  parentheses
#   hash mark
+   plus sign
-   minus sign (hyphen)
.   dot
!   exclamation mark
```
Pandoc's Markdown variant implements an extension `all_symbols_escapable`, which expands the range of escapable symbols to include `<` and `>`.  But this isn't enabled for GitHub Markdown.  (Perhaps it should be, but this needs testing.)
