### ISSUE TITLE
Inline math export to epub3

### ISSUE THREAD

**Issue by jga2004** [jgm/pandoc#2848]
Pandoc exports correctly to epub3 the following inline equation:
\( \omega \)

But not this one, I believe it is because of not interpreting correctly the package amssymb
\( \hslash \).

Note: Pandoc correctly generates the PDF version in both examples.

**Comment by jgm** [comment]
In texmath 0.8.6 I added support for hundreds more symbols,
including \hslash.  So if you recompile pandoc against the
latest texmath, it will support this.  With cabal, this
would be something like:

cabal update
cabal install texmath-0.8.6.1
cabal install --force --reinstall pandoc

The improved support will also be in the next release of
binary packages (though I can't predict when that will be).
