### ISSUE TITLE
Install of dev version fails with `canonicalizePath: does not exist`

### ISSUE THREAD

**Issue by nylki** [jgm/pandoc#2850]
I was following https://github.com/jgm/pandoc/wiki/Installing-the-development-version-of-pandoc to install pandoc from the repo, as I need to the most recent `pandoc-citeproc`.
However `stack` fails with `/home/tom/gits/pandoc-build/pandoc/../cmark-hs: canonicalizePath: does not exist (No such file or directory)`.

```.zsh
➜  pandoc-build ls
pandoc  pandoc-citeproc  pandoc-types  texmath
➜  pandoc-build cd pandoc
➜  pandoc git:(master) git submodule update                             
➜  pandoc git:(master) stack install --test --install-ghc --stack-yaml stack.full.yaml
/home/tom/gits/pandoc-build/pandoc/../cmark-hs: canonicalizePath: does not exist (No such file or directory)
➜  pandoc git:(master) 
```

**Comment by jgm** [comment]
I've updated the instructions.  You need to clone a couple
more repositories, cmark-hs and zip-archive.

+++ Tom Brewe [Apr 11 16 08:02 ]:

**Comment by jgm** [comment]
I really should just add a bootstrap.sh script that install
stack if needed, reads stack.full.yaml to determine which
repositories need to be cloned, clones them, and does the
build.

Feel free to keep this open as a reminder to do this.

+++ Tom Brewe [Apr 11 16 08:02 ]:

**Comment by nylki** [comment]
> I've updated the instructions.
You need to clone a couple more repositories, cmark-hs and zip-archive.

Thanks!
