### ISSUE TITLE
Use of URL linking for SVG images in HTML generation by Pandoc

### ISSUE THREAD

**Issue by alisaad05** [jgm/pandoc#2852]
Hi,
I am currently using [PlantUML](http://plantuml.com/) with Pandoc very nicely to produce UML documentation ([using this python filter](https://gist.github.com/alisaad05/495eae23755e24d9c06c29ae30a2c310).

_Does Pandoc support embedding SVG images files that contains URL information ?_

I ve tried dragging the SVGs produced by PlantUML into my browser and the link is sucessfully rendered and is accessible. However, the Pandoc-generated HTML does not allow to access these links for the same SVG images.

I am not sure if this is just impossible or a bug (using Pandoc 1.16.0.2 with PlantUML v.8038 win7)
Thank you

**Comment by mb21** [comment]
The problem is probably that the output HTML uses the `img` tag instead of `object` to embed the SVG. You can write a filter to change that though...

**Comment by alisaad05** [comment]
Great ! In such case, how can I search for these `img` tags to replace them with `object` or `<svg>` tag? or should I let the filter insert raw HTML whenever it finds an instance of svg image ?

**Comment by jgm** [comment]
Should the HTML writer be changed to recognize .svg extensions on images
and use object automatically?

+++ Mauro Bieg [Apr 15 16 04:04 ]:

**Comment by mb21** [comment]
> Should the HTML writer be changed to recognize .svg extensions on images
and use object automatically?

Well, then `[ ![](my.svg) ](/mylink)` wouldn't result in a clickable link anymore. Also, the `width` and `height` attributes of `<object>` don't rescale the image, but make a box that size with scroll bars.

@alisaad05 yes, my proposed filter would have to insert raw HTML whenever it finds an instance of an svg image...

**Comment by alisaad05** [comment]
@mb21: and does `<svg>` tag have the same caveats ?

**Comment by mb21** [comment]
@alisaad05 you mean reading the entire svg file and placing it in an `svg` tag? yes, that should work, but obviously browsers cannot cache the image independently of the HTML anymore then...

**Comment by alisaad05** [comment]
I am not sure how to proceed for this filter. Should I modify the Para([Image ... ]) in my PlantUML filter to look for img` and replace by `object` tag ? or is it done differently ?

**Comment by alisaad05** [comment]
I finally figured it. Here's the [python filter](http://gist.github.com/alisaad05/b40b3de55afbf1dc2658af160e165771) which does both types of figures (non linking SVG using `img` and linking SVG using `object`). I should it clean it a bit later.
Thank you

**Comment by jgm** [comment]
This is how a figure gets stored in the pandoc AST:

    Para [Image ("",[],[]) [Str "caption"] ("url.jpg","fig:title")]

Note that the title begins with "fig:".  So, you can match
on paragraphs containing just a single image whose title
field begins with 'fig:'.



+++ Ali SAAD [Apr 21 16 01:10 ]:
