### ISSUE TITLE
epub generation

### ISSUE THREAD

**Issue by shd101wyy** [jgm/pandoc#2853]
Hi,

Is there a way to pass more than one css file after `--epub-stylesheet` argument?

like `pandoc test.md --epub-stylesheet style1.css style2.css -o test.epub`

Thanks

**Comment by shd101wyy** [comment]
Also when generating `epub` from `html`, how can I preserve `html` style?

For example, I have 
```html
<head>
    <link href="blabla.css">
    <link href="blabla2.css">
    <style> ... </style>
</head>
```

And I want to apply `blabla.css`, `blabla2.css`, and the inline `style` to the `epub`.
Any way to do that?

Thanks a lot

**Comment by jgm** [comment]
I believe you can use the option multiple times:

    --epub-stylesheet style1.css --epub-stylesheet style2.css

+++ Yiyi Wang [Apr 14 16 23:31 ]:

**Comment by jgm** [comment]
You'd have to manually specify with --epub-stylesheet.

Bringing the styles across automatically wouldn't be
desirable in general.

By the way:  this is not the place to ask questions about
pandoc.  This is for bug reports.  For questions, use the
pandoc-discuss list on google groups.

+++ Yiyi Wang [Apr 14 16 23:40 ]:

**Comment by shd101wyy** [comment]
Thanks!
