### ISSUE TITLE
Code highlighting in PDF output does not work

### ISSUE THREAD

**Issue by matthiasbeyer** [jgm/pandoc#2854]
This is _not_ a duplicate of #888

Here is my current codebase: https://github.com/matthiasbeyer/Unfug-fuer-Anfaenger/tree/code

Here is the code examples I'm trying to get colorized: https://raw.githubusercontent.com/matthiasbeyer/Unfug-fuer-Anfaenger/code/src/020_code.md

And here are the Makefile setup parts which are relevant: https://github.com/matthiasbeyer/Unfug-fuer-Anfaenger/blob/code/Makefile#L66-L92

I don't know what else to try. The pandoc documentation states clearly that pandoc will colorized the codeblocks automatically, so I do not need some `\lstset{}` in my preamble...

**Comment by jgm** [comment]
By default pandoc uses its own method for highlighting
(which will look the same in HTML and PDF).  You have
used the --listings option, which causes pandoc to use
the listings latex package.  Try without --listings
and -M listings=true.

+++ Matthias Beyer [Apr 15 16 07:37 ]:

**Comment by matthiasbeyer** [comment]
Works for me, thank you a lot.
