### ISSUE TITLE
Link highlighting not enabled by default in 1.17.0.2?

### ISSUE THREAD

**Issue by orschiro** [jgm/pandoc#2855]
Dear all,

I am coming from [this[(https://github.com/wereturtle/ghostwriter/issues/77#issuecomment-210505174) conversation on the missing visual highlighting of links in Pandoc `1.17.0.2` which I took directly from the releases page.

I downgraded to `pandoc_1.13.2.1-dfsg-1build6_amd64.deb` and there links are shown in blue by default.

Is it possible to enable this blue highlighting in version 1.17 alike?

Thankfully,

~Robert

**Comment by jgm** [comment]
Sure.  Set

    linkcolor: blue
    citecolor: blue
    urlcolor: blue
    toccolor: blue

in your YAML metadata.  (Or set these variables using -V on the
comand line, e.g. `-Vlinkcolor=blue`)


+++ Robert Orzanna [Apr 15 16 10:06 ]:

**Comment by orschiro** [comment]
Great, thank you John!

I will see how to make this applicable to be used as the default in [Ghostwriter](https://github.com/wereturtle/ghostwriter/issues/77#event-629655112).

Warmly,

~Robert
