### ISSUE TITLE
Handwriting/drawing in docx not parsed as images

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#2857]
Currently if something is hand-drawn on Word, the docx generated would not contain the hand-writing at all, not as an image for example.

The command I used is

``` bash
pandoc -t markdown --normalize -s --wrap=none --atx-headers --extract-media=media -o handdrawing.md handdrawing.docx
```

I'm not sure if it is a bug report/feature request. When I selects all in the Word document it will select all individual strokes, so it is not like an image. And I'm not sure if there's anything that can be done in pandoc.

[MWE: handdrawing.docx](https://github.com/jgm/pandoc/files/222472/handdrawing.docx)

There are some other things disappeared in this example. Probably related to the template I used.

**Comment by jgm** [comment]
I don't think there's anything we can do here (short of implementing a rendering program that creates an image from the corresponding XML description in Word -- and I think that's way beyond scope).
@jkr do you agree?

**Comment by jkr** [comment]
It does contain png versions of the drawing (as a fallback, I guess), but it contains a different png for each individual stroke. So if we used them, we'd have to figure out how to overlay them. I think it's out of scope, but I'll leave this open until I get a chance to take a closer look at the spec.

**Comment by tarleb** [comment]
Closing as out of scope.
