### ISSUE TITLE
Inline LaTeX is ignored in some output formats, but why not remove other LaTeX environments as well?

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#2860]
From the documentation:

> Inline LaTeX is ignored in output formats other than Markdown, LaTeX, and ConTeXt.

How about other LaTeX codes?

e.g. the following **Markdown** files,

```latex
\begin{flushright}
testing
\end{flushright}
```

pandoc to html becomes
```html
...
<body>
\begin{flushright}
testing
\end{flushright}
</body>
...
```

Why wasn't it be removed form the HTML output as well, even `-R` is not used?

**Comment by jgm** [comment]
When I try this input with `pandoc -f markdown -t html`, I
get an empty file.  Are you seeing something different?
What pandoc versionL

+++ ickc [Apr 17 16 21:59 ]:

**Comment by ickc** [comment]
The command I used is actually this

```bash
pandoc -f markdown+mmd_header_identifiers+abbreviations+autolink_bare_uris+mmd_link_attributes+markdown_attribute+mmd_title_block+tex_math_double_backslash -S --base-header-level=1 --toc --toc-depth=6 -N --normalize -s --mathjax -t html5 -o 
```

I tried your bare command and it did becomes empty. I don't know where in the command I used above get it wrong. But since `-R` is not used I guess it is not the expected behavior?

**Comment by jgm** [comment]
See #1938.
With `--mathjax` we include raw LaTeX blocks.

**Comment by ickc** [comment]
I see. Can you take a look at #2758 that @yihui said the raw LaTeX block is not included in his ePub output with `--mathjax`?

**Comment by jgm** [comment]
I'm not sure what's going on there. I just tried and the
'equation' environment did get transferred over to epub with
`--mathjax`.  So I can't reproduce what he's describing.

+++ ickc [May 07 16 20:28 ]:

**Comment by ickc** [comment]
Sorry I closed it too quickly. Now when I think about the reason I open this issue is about an environment like this:

```latex
\begin{flushright}
testing
\end{flushright}
```

Then the problem is that pandoc include "too much" LaTeX environments. This is closely related to #2758, that only a certain environments should be included in MathJax output.

Quoting from MathJax documentation:

> LaTeX environments of the form `\begin{XXX} ... \end{XXX}` are provided where `XXX` is one of the following:
> 
> |	| 		|  
> | ------	| ------	|  
> |align                  | [AMSmath] |
> |align*                 | [AMSmath] |
> |alignat                | [AMSmath] |
> |alignat*               | [AMSmath] |
> |aligned                | [AMSmath] |
> |alignedat              | [AMSmath] |
> |array
> |
> |Bmatrix
> |bmatrix
> |
> |cases
> |CD                     | AMSmath |
> |
> |eqnarray
> |eqnarray*
> |equation
> |equation*
> |
> |gather                 | [AMSmath] |
> |gather*                | [AMSmath] |
> |gathered               | [AMSmath] |
> |
> |matrix
> |multline               | [AMSmath] |
> |multline*              | [AMSmath] |
> |
> |pmatrix
> |
> |smallmatrix            | AMSmath |
> |split                  | [AMSmath] |
> |subarray               | AMSmath |
> |
> |Vmatrix
> |vmatrix

Probably one of these 2 issues (#2758 and #2860) should be closed since they are describing the same issue.

**Comment by ickc** [comment]
I'm closing this in favor of #2758. Hope that you don't mind.

**Comment by jgm** [comment]
IT might be worth reproducing the table and the link to MathJax documentation in the other issue.

**Comment by ickc** [comment]
> IT might be worth reproducing the table and the link to MathJax documentation in the other issue.

It is already there. (and I changed the title over there to reflect the situation)
