### ISSUE TITLE
DocBook tables not rendering in HTML correctly

### ISSUE THREAD

**Issue by noamross** [jgm/pandoc#2861]
When I convert a DocBook table to HTML, tables are not formatted properly.  The contents of the table are rendered as verbatim code.

For example, using `tables.docbook` from the `tests/` directory, I run

    pandoc tables.docbook -t html -o test.html

And I get [this output (HTML file)](https://dl.dropboxusercontent.com/u/3356641/test.html), in which there is HTML code instead of a table, like so:

![screen shot 2016-04-18 at 4 01 00 pm](https://cloud.githubusercontent.com/assets/571752/14618062/ce6bda3e-057e-11e6-8eda-4dbd7c439a19.png)

**Comment by jgm** [comment]
You need to tell pandoc that this is a docbook file:

    pandoc -f docbook -t html -s tables.docbook -o test.html

Otherwise it will interpret it as markdown.  Yes, pandoc
does generally try to guess from the extension, but the
extension currently it recognizes as docbook is .db.


+++ Noam Ross [Apr 18 16 13:02 ]:
