### ISSUE TITLE
Incorrect spacing with org-mode src blocks?

### ISSUE THREAD

**Issue by shosti** [jgm/pandoc#2862]
Let me know if I'm missing some configuration, but I'm running into some trouble with indentation with markdown_github -> org-mode source block translation: pandoc appears to be adding leading indentation within the source blocks. For instance:

    ```ruby
    x = "something"
    y = "something else"
    ```

when run with `pandoc -f markdown_github -t org`, gets translated into:

    #+BEGIN_SRC ruby
        x = "something"
        y = "something else"
    #+END_SRC

and translating back to markdown_github preserves the spacing (so every back-and-forth round trip adds leading space to the code).

I'm running pandoc 1.17.0.3 on Arch.

**Comment by tarleb** [comment]
Just to be sure: You are referring to an identation error occuring when
translating back-and-forth between *github_markdown* and *org*, correct?

Looks like that's my fault (i.e. a bug in the org reader).
Indentation isn't stripped the way it should be.

    echo "#+BEGIN_SRC ruby\n  hello\n#+END_SRC\n" | pandoc -f org -t native
    [CodeBlock ("",["ruby"],[]) "  hello\n"]

I'll look into it.

**Comment by shosti** [comment]
Yes, it's markdown_github->org (other direction seems fine), sorry said that wrong the first time.
