### ISSUE TITLE
Bug Report: Block level image escape, with markdown content, followed by a heading

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#2863]
Using this [test file](https://github.com/jgm/pandoc/files/227104/test.txt):

```markdown
![***Not*** Block **Level**](image.png "Optional Title")\

## RAW ##
```

The heading over there will not be parsed as heading.

If I put one more line between them, it's then fine.

If I have a link that is not formatted, it's then fine.

**Comment by jgm** [comment]
It's not really a bug, I think.  You need a blank line
between the last bit of paragraph content and the header.
In this case you have a `\` at the end of the line.
`\ + NEWLINE` is interpreted as a hard line break.
So the newline at the end of that line is consumed
as part of the hard line break inline.

That leaves no blank line before the header.

+++ ickc [Apr 19 16 18:36 ]:

**Comment by ickc** [comment]
From my memory, it seems if the texts within `[...]` has no markdown, it would be fine. As a sidenote, the same text rendered fine with MultiMarkdown.

But I agree it is not a bug, but a different interpretation. So I'm closing it now.
