### ISSUE TITLE
`\today` in date metadata

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#2865]
I found that if I do this in the YAML metadata:

```yaml
date:	\today
```

In latex output it will leaves it as is, so latex will then be able to substitute today there. But I'm not sure if it will break anything in other output formats. e.g. ePub.

Can someone confirm if this is good or not? And if not, what's the way to let pandoc set date to the date of compilation automatically?

Thanks!

**Comment by KurtPfeifle** [comment]
@ickc: Can't you confirm (or disprove) that it breaks by just constructing a minimal Markdown file and include your YAML, and then let Pandoc create an EPUB (and all the other output formats you're interested in)?

<small>(My bet is on the side that *"This is not working for other output formats"*.)</small>

**Comment by jgm** [comment]
It will only work in LaTeX/PDF.

Your best bet is to set the date on the command line,
e.g.

    --metadata date="`date +%D`"

on linux/unix.

+++ ickc [Apr 20 16 02:27 ]:

**Comment by ickc** [comment]
>Your best bet is to set the date on the command line,

Good idea. May be it can be put in the documentation as a trick worth nothing?

I am used to MultiMarkdown that if I don't specify a date, it will auto added today there. That's why I have such question.

Thanks and I'm closing it now.

**Comment by ickc** [comment]
Just to document it: to replicated the `\today` output LaTeX used,

```bash
-M date="`date "+%B%e, %Y"`"
```

should be used with pandoc.

**Comment by ickc** [comment]
Correction:

```bash
-M date="`date "+%B %e, %Y"`"
```

Do you mind if I add this in the MANUAL as an example?

**Comment by jgm** [comment]
I'd rather not have it in the manual, since it's unix specific.

**Comment by hyiltiz** [comment]
Why don't we put in the MANUAL something that is NOT unix specific? First off, it is *not* unix specific, but rather POSIX specific, including much more than unix. Then we can also write down what works for Windows users. I assume that covers 99.9% of the users of pandoc.

**Comment by ickc** [comment]
> I assume POSIX+Windows covers 99.99% of the users of pandoc.

Interesting statement: would pandoc even work if it's not "POSIX+Windows"?

I think what @jgm means is this is not something pandoc "officially" covered. e.g. nothing within pandoc really can help you to create today in date. So what that did is "a hack" that's outside the scope of pandoc. I guess the manual is already very long, so he don't want to add more unnecessary stuffs there.

Some tricks like this is added in [Pandoc Tricks · jgm/pandoc Wiki](https://github.com/jgm/pandoc/wiki/Pandoc-Tricks#using-markdown-templates). Perhaps I should put this there as well.

**Comment by tarleb** [comment]
FWIW: lua filters will allow to set the date like this in a fully portable manner:

``` lua
function Meta(m)
  m.date = os.date("%B %e, %Y")
  return m
end
```

Might be a good example to add to the docs.

**Comment by joelparkerhenderson** [comment]
To set the date in Y-M-D UTC format, this syntax works for me on macOS:

    --metadata date="`date -u '+%Y-%m-%d'`"
