### ISSUE TITLE
DBUS interface to pandoc

### ISSUE THREAD

**Issue by wolfv** [jgm/pandoc#2867]
I would love to port my application, that relies on pandoc, to an xdg-app.
Therefore it's necessary to communicate with other apps over DBUS on linux.

I was wondering if it would be of interest to the pandoc community to add such functionality to pandoc itself? In that case I would spend some time in creating a pull request.

Otherwise I would probably create the necessary DBUS interface via pypandoc or similar.

Best,
Wolf

**Comment by jgm** [comment]
The problem I see is that pandoc is cross-platform (not just
linux, but OSX and Windows and BSD).  I don't know anything
about DBUS but at first glance it looks pretty
linux-specific...

+++ Wolf Vollprecht [Apr 21 16 12:53 ]:
