### ISSUE TITLE
org to LaTex: org center paragraph is not considered

### ISSUE THREAD

**Issue by ag91** [jgm/pandoc#2869]
Hello, (pandoc is marvellous! Thanks!!)

I am using pandoc 1.17.0.2
compiled with texmath 0.8.5, highlighting-kate 0.6.2.

The problem is that the org center paragraph is not translated in the LaTex center environment:

pandoc translates the org file
```
* Hello
#+BEGIN_CENTER
this should be centered
#+END_CENTER
```
in the following LaTex (I add just the body for readability):

```
\begin{document}

\section{Hello}\label{hello}

this should be centered

\end{document}
```

while it should give:

```
\begin{document}

\section{Hello}\label{hello}

\begin{center}
this should be centered
\end{center}

\end{document}
```

Thanks again.

**Comment by tarleb** [comment]
Thanks for the report. I maintain the org reader. I'm currently a bit short in time, but I'll have a look next week.

**Comment by jgm** [comment]
Pandoc's document model doesn't contain any dedicated way
to represent centered text, so this conversion is lossy.

See #719.

**Comment by tarleb** [comment]
Jep, I forgot that centering isn't part of the doc model.

@ag91 Take a look at [pandoc scripting](http://pandoc.org/scripting.html) and [pandocfilters](https://github.com/jgm/pandocfilters).  The org reader parses the `#+BEGIN_CENTER` block as a `Div` with class "center".  One could surround that div with raw LaTeX blocks `\begin{center}` and `\end{center}` using filters, effectively giving the output you expected.

**Comment by ag91** [comment]
So, I get that this is not allowed behaviour.
Should I simply close the issue?

**Comment by tarleb** [comment]
> So, I get that this is not allowed behaviour.

I'd put it as "might get supported in future versions", though the effect is the same.

> Should I simply close the issue?

The root cause is handled by the issue mentioned by jgm; closing seems appropriate.

**Comment by ag91** [comment]
Okay, finger crossed then ;)
