### ISSUE TITLE
[Feature Request] Automatically fill in internal reference link text

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#2870]
Assume I have this in my Markdown:

``` markdown
# Excursion: What is this all about? {#excurs}
```

Currently I can refer to this from another spot in my text by writing.

``` markdown
You can read more about this problem in section *[What is this all about?](#excurs}*.
```

I would like to know if it could be made easier to write, so I do not have to remember the exact wording of that title when writing the text -- and more importantly, after editing the heading, to also update my references to this section.

Something similar to how it works with citations, bibliographies and `--filter pandoc-citeproc`, but very short to type. What if I just typed

``` markdown
You can read more about this problem in section *[](#excurs}*.
```

So if I do not fill in the `[]` brackets, Pandoc looks it up for me (it has to do that anyway, in order to create the link), and also fill bracket space with the original text of the heading as it currently stands? So Pandoc would just create the same output as if it had seen:

``` markdown
... section *[What is this all about?](#excurs}*.
```

Of course, if I typed...

``` markdown
You can read more about this problem *[another part of the book](#excurs}*.
```

...current behavior should remain unchanged.

Another, easy-to-use syntax for the same purpose would also be welcome.

I have not thought through this idea completely, so I'm not sure if it would break any existing functionality. And of course, I have no idea how much work such a feature would need.

---

<subscript>(This is not urgent for me; I can work around this -- it's just not as comfortable.)</subscript>

**Comment by jgm** [comment]
I'm not sure whether this should be a standard part of
pandoc, but for now it would be fairly easy to write a
filter that accomplishes this.
