### ISSUE TITLE
Failure to build relocatable 1.17.0.2

### ISSUE THREAD

**Issue by tuncer** [jgm/pandoc#2877]
I was able to build pandoc previously as follows, but this failed for 1.17.0.2:

```
$ cabal update
$ cabal get pandoc
$ cd pandoc-1.17.0.2
$ cabal sandbox init
$ cabal install hsb2hs
$ cabal install --flags=embed_data_files 
[...]
[90 of 90] Compiling Text.Pandoc ...
In-place registering pandoc-1.17.0.2... 
Preprocessing executable 'pandoc' for pandoc-1.17.0.2...
[1 of 2] Compiling Paths_pandoc     ...
[2 of 2] Compiling Main             ...
Linking dist/dist-sandbox-1471fe7c/build/pandoc/pandoc ...
setup: data/templates/default.html: does not exist
cabal: Leaving directory '.'
Failed to install pandoc-1.17.0.2
cabal: Error: some packages failed to install:
pandoc-1.17.0.2 failed during the final install step. The exception was:
ExitFailure 1
```

The only non-default setting I use is `split-objs: True` in `~/.cabal/config`.

**Comment by chdemko** [comment]
Did you run

~~~
git submodule update --init
~~~

See https://github.com/jgm/pandoc/wiki/Installing-the-development-version-of-pandoc

**Comment by jgm** [comment]
You need to do

    git submodule update --init

to bring in the missing templates.

+++ Tuncer Ayaz [Apr 25 16 12:19 ]:

**Comment by tuncer** [comment]
I've used `cabal get pandoc` which fetched and extracted the release archive, so I didn't build from the git tree.

**Comment by jgm** [comment]
What does `ls data/templates` say?  The error you got suggests that it's empty or nonexistent.  I just tried `cabal get pandoc`, though, and it did give me `data/templates/default.html`.

**Comment by tuncer** [comment]
I cannot reconstruct how `data/templates/` turned out to be empty, but I couldn't reproduce it when I tried with a fresh cabal download. I didn't delete the files in myself, so I hope there's not some bug lurking. Both 1.17.0.2 and 1.17.0.3 were successful.

**Comment by tuncer** [comment]
I cannot reconstruct how `data/templates/` turned out to be empty, but I couldn't reproduce it when I tried with a fresh cabal download. I didn't delete the files myself, so I hope there's not some bug lurking. Both 1.17.0.2 and 1.17.0.3 were successful.
