### ISSUE TITLE
[Bug] pandoc-1.17.0.2-osx.pkg: Conversion of .json file(s) to .md

### ISSUE THREAD

**Issue by securityfirst** [jgm/pandoc#2879]
Same error has appeared a few times.

Direct install of pandoc-1.17.0.2-osx.pkg

Attempted conversion of .json file(s) to .md

"When expecting a product of 2 values, encountered an Array of 6 elements instead"

I believe the issue has come up a few times before.

**Comment by jgm** [comment]
What produced the .json file you are trying to convert?

Pandoc's json input format is designed for a specific kind
of json - a json serialization of the pandoc AST, produced
by pandoc.  It will fail on arbitrary json files.  And it
may fail if you try to convert .json produced by a different
version of pandoc.

+++ Security First [Apr 26 16 16:07 ]:

**Comment by securityfirst** [comment]
Interesting, it's JSON files from our open source mobile app here:

https://github.com/securityfirst/Umbrella_content/tree/master/json/en

**Comment by jgm** [comment]
As the pandoc documentation says, the json input format is
for "JSON version of the native AST."  You can't just pass
in arbitrary JSON.  So this is not a bug.

+++ Security First [Apr 26 16 21:37 ]:

**Comment by securityfirst** [comment]
Thanks
