### ISSUE TITLE
Math in footnote not detected when reading markdown

### ISSUE THREAD

**Issue by riceissa** [jgm/pandoc#2881]
Pandoc does not seem to detect that there is math in a document if the only math in the document appears in a footnote. The following is a minimal working example that illustrates this problem:

```
echo 'hi[^$a$]' | pandoc -f markdown -t html5 -s --mathjax
```

does not include the MathJax JavaScript line (so one has \\(a\\) in the footnote), whereas

```
echo '$a$ hi^[$a$]' | pandoc -f markdown -t html5 -s --mathjax
```

*does* include MathJax (and both the *a* in the main body and the one in the footnote are converted to math by MathJax).

I am using version 1.17.0.3.

**Comment by ickc** [comment]
I think the problem is your first example has a wrong syntax for inline footnote, should be this:

```bash
echo 'hi^[$a$]' | pandoc -f markdown -t html5 -s --mathjax
```

**Comment by jgm** [comment]
There was a real bug, indeed. Thanks for reporting.
