### ISSUE TITLE
Can't see the readme file with the correct format

### ISSUE THREAD

**Issue by CrisKrus** [jgm/pandoc#2882]
As I say on the title the readme doesn't have the markdown extension ".md" and is to hard to read.
![image](https://cloud.githubusercontent.com/assets/11683316/14896123/19b154d6-0d74-11e6-9255-a00d08acd2a5.png)

**Comment by jgm** [comment]
Hi!  When you open an issue, it says "Please review the
contributing guidelines for this repository," linking to
https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md

If you'd done that, you'd have seen in the second line
"Before you submit a bug report, search the (open and
closed) issues to make sure the issue hasn't come up
before." Try that now!  Search issues for
`is:issue is:closed readme md extension`.

+++ Cristian [Apr 28 16 11:05 ]:
>   As I say on the title the readme doesn't have the markdown extension
>   ".md" and is to hard to read.

**Comment by CrisKrus** [comment]
Thanks :)
