### ISSUE TITLE
pandoc: Could not parse YAML header

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#2885]
I am trying to write markdown source that is dual compatible with mmd and pandoc so that I can use the best of both world. The idea is that the YAML front matter between pandoc and mmd are almost orthogonal, and for those which overlap, they overlap nicely.

Because of that, in my YAML front matter, there's an entry like this (and this is also the MWE that produce the error):

```yaml
---
HTML Header:	<script type="text/x-mathjax-config"> MathJax.Ajax.config.path["Contrib"]="https://cdn.mathjax.org/mathjax/contrib"; MathJax.Hub.Register.StartupHook("TeX Jax Ready",function (){MathJax.Hub.Insert(MathJax.InputJax.TeX.Definitions.macros,{cancel: ["Extension","cancel"], bcancel: ["Extension","cancel"], xcancel: ["Extension","cancel"], cancelto: ["Extension","cancel"]});}); MathJax.Hub.Config({tex2jax:{inlineMath: [['$','$'], ['\\(','\\)']], processEscapes: true}, TeX:{equationNumbers:{autoNumber: "AMS"}, extensions: ["[Contrib]/physics/physics.js","[Contrib]/siunitx/siunitx.js"]}});</script><script type="text/javascript"src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full"></script>
...

testing
```

I understand this is not a feature pandoc support (that a certain HTML code is put in a metadata field named `HTML Header` which will be put in the header in HTML output). But the problem I want to address is the following error:

```bash
pandoc: Could not parse YAML header: mapping values are not allowed in this context "source" (line 3, column 261)
```

which corresponds to the position at `["`.

Is it possible for pandoc to improve the parser so that it won't choke on this error? This metadata field is not used by pandoc anyway. **For example, even if it detects the error, can it allow me to ignore it?**

By the way, escaping any of those character won't be a solution because they have to be read by MultiMarkdown...

**Comment by jgm** [comment]
You're running into YAML escaping issues.  (These don't come up in MMD because it's not using a real YAML parser.) Try like this:

```
HTML Header: |
  <script etc...can be any number of lines, but must be indented at least as far as this line..>
```

**Comment by ickc** [comment]
Thanks, @jgm.

The one you suggest works in pandoc but does not work in MMD, the extra `|` will shows up in the rendered results. Again it is related to MMD not really using YAML exactly.

But if there's nothing that can be done in pandoc's end then feel free to close it. I am going to use MultiMarkdown editors (e.g. the MultiMarkdown Composer, Editorial, Drafts, etc.) to have live view of the markdown code (and other features) so probably I can deal with the extra `|` in the preview.

Thanks!
