### ISSUE TITLE
-f markdown_github ignores metadata title blocks

### ISSUE THREAD

**Issue by rkitover** [jgm/pandoc#2886]
If I use -f markdown_github to make man pages, metadata title blocks at the top of the file are not parsed, while with -f markdown they are, is there a specific reason for this?

**Comment by jgm** [comment]
See #2827

GFM doesn't natively support the YAML metadata (at least, it
doesn't work on github wiki pages).  But you can ask pandoc
to enable that extension.


+++ Rafael Kitover [Apr 29 16 02:44 ]:

**Comment by rkitover** [comment]
Sorry for the late response, `-f markdown_github+pandoc_title_block` works for me, thank you!
