### ISSUE TITLE
Demo example 30 is not reversible

### ISSUE THREAD

**Issue by mcgratta** [jgm/pandoc#2887]
I downloaded pandoc version 1.17.0.2 for Windows and I tried to reverse Example 30, that is:
```
pandoc -s -o example30.tex example30.docx
```
It almost worked, but my version of LaTeX did not recognize the unicode kappa and left it blank. Is there another version of TeX that I should be using?

**Comment by jgm** [comment]
Use --latex-engine=xelatex and specify a font that contains
the kappa (-V mainfont=...).

+++ Kevin McGrattan [Apr 29 16 06:52 ]:

**Comment by mcgratta** [comment]
Great, that worked. Thanks.
