### ISSUE TITLE
readDocx is unsafe

### ISSUE THREAD

**Issue by bhickey** [jgm/pandoc#2891]
Invoking readDocx on a malformed docx ByteString throws an exception. As a caller, I expect this function to be safe and produce a PandocError if provided with garbage.

    Data.Binary.Get.runGet at position 4: Did not find end of central directory signature

This impacts Pandoc 1.17.0.3.

**Comment by jgm** [comment]
This error comes from zip-archive.  @jkr, a simple fix
would be to use toArchiveOrFail instead of toArchive.

+++ Brendan Hickey [Apr 29 16 18:33 ]:

**Comment by jkr** [comment]
On it.

**Comment by jgm** [comment]
While we're at it we should make the same change for odt and ePub readers.

**Comment by jkr** [comment]
I put in the change for the docx reader with 91dc334249883b658e2b91fce80ced6635e07c28. I'll leave the issue open until I get a chance to look at odt and epub as well (probably tonight).

**Comment by jkr** [comment]
Closing with 99eac312feb258ac4129c923e5b4fde57da9fbc3

**Comment by bitnumus** [comment]
I'm getting this now, i've used pandoc for many months and suddenly i'm getting this on ubuntuy 16.04 so i assume its a package update, its fine on 14.04?

**Comment by jgm** [comment]
Are you getting the error on a valid docx file?
If so, could you post it so we can test?

+++ Shaun G [May 03 16 08:27 ]:

**Comment by jgm** [comment]
(Or you can send it to me directly if you don't want to post.)

Also, please say what version of pandoc it is (`pandoc --version`).

+++ Shaun G [May 03 16 08:27 ]:

**Comment by BenQuigley** [comment]
Did this ever get updated for .odt files as well as .docx? I'm seeing it in an .odt conversion with pandoc 1.16.0.2.

**Comment by jkr** [comment]
Yep -- and the change was only released with 1.17.1. (1.16.0.2 came out three months before this bug was reported.)

**Comment by BenQuigley** [comment]
OK, updated and it went away. Thanks!
