### ISSUE TITLE
Impossible to put a comma in listing caption

### ISSUE THREAD

**Issue by legrostdg** [jgm/pandoc#2892]
converting .md to .pdf:

    ~~~~{caption="a b"}
    test
    ~~~~

works great (with `--listings`), but

    ~~~~{caption="a, b"}
    test
    ~~~~

does not compile

    ! Package keyval Error: b undefined.
    
     See the keyval package documentation for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.54 \begin{lstlisting}[caption=a, b]
    
    pandoc: Error producing PDF

This (usually, you put the caption between '{' and '}' in listings if it contains a comma):

    ~~~~{caption={a, b}}
    test
    ~~~~

does not work either

**Comment by jgm** [comment]
This seems like more of a listings issue than a pandoc
issue.  If there's a way to do this with listings,
and pandoc's output could be modified to make it work,
post that here.  Otherwise, there's nothing we can do.

+++ legrostdg [Apr 30 16 11:34 ]:

**Comment by legrostdg** [comment]
As I said (sorry if it wasn't clear in my message), there is a way to make it work with listings: enclosing caption between '{' and '}'

    \begin{lstlisting}[caption={a, b}]
        test
    \end{lstlisting}

I just noticed that this:

    ~~~~{caption="{a, b}"}
    test
    ~~~~

actually work, but it may be a more intuitive solution to automatically enclose caption between '{', '}'
