### ISSUE TITLE
json sent to filters depends on output format

### ISSUE THREAD

**Issue by tomduck** [jgm/pandoc#2893]
Three different calls to pandoc are given below, along with the json seen by `filter.py`.  Notice that for the last two cases the json is completely different, even though they both produce pdf.  The file `test.md` contains a single line: `"test"`.

**Case 1:** `pandoc test.md --filter ./filter.py -o test.html`

    [{"unMeta": {}}, [{"t": "Para", "c": [{"t": "Str", "c": "\"test\""}]}]]

**Case 2:** `pandoc test.md -t json | ./filter.py | pandoc -o test.pdf`

    [{"unMeta": {}}, [{"t": "Para", "c": [{"t": "Str", "c": "\"test\""}]}]]

**Case 3:** `pandoc test.md --filter ./filter.py -o test.pdf`

    [{"unMeta": {}}, [{"t": "Para", "c": [{"t": "Quoted", "c": [{"t": "DoubleQuote", "c": []}, [{"t": "Str", "c": "test"}]]}]}]]

Here is `filter.py`:

~~~ .python
#! /usr/bin/env python3

import sys, json, io

STDIN = io.TextIOWrapper(sys.stdin.buffer, 'utf-8', 'strict')
STDOUT = io.TextIOWrapper(sys.stdout.buffer, 'utf-8', 'strict')

doc = json.loads(STDIN.read())

with open('filter.json', 'w') as f:
    json.dump(doc, f)

json.dump(doc, STDOUT)
STDOUT.flush()
~~~

**Comment by jgm** [comment]
When latex or pdf output is specified, it automatically triggers `--smart` in the parser.  That's why you get different output in your two cases.  Using the pipe, the parser doesn't know that your eventual target will be latex/pdf.

**Comment by tomduck** [comment]
Well, that makes sense.  Sorry for the bother, John.  Cheers.
