### ISSUE TITLE
osx build stuck installing

### ISSUE THREAD

**Issue by dwaggott** [jgm/pandoc#2896]
A dialog opens "verifying" the package and then hangs with no cpu.

pandoc 1.17.0.2 osx 

Daryl

**Comment by jgm** [comment]
What version of OSX, and what kind of machine?

+++ Daryl Waggott [May 03 16 09:48 ]:

**Comment by dwaggott** [comment]
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B17
  SMC Version (system):	2.19f12


 System Version:	OS X 10.11.4 (15E65)
  Kernel Version:	Darwin 15.4.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Daryl’s MacBook Pro
  User Name:	Daryl Waggott (dwaggott)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled

**Comment by dwaggott** [comment]
A couple restarts cleared up some half finished installs and it worked.
