### ISSUE TITLE
Google Code wiki format status

### ISSUE THREAD

**Issue by techtonik** [jgm/pandoc#2897]
What is the status of supporting Google Code wiki format? Is it hard to implement? In particular the  scenario with converting it to GitHub Markdown is interesting.

**Comment by jgm** [comment]
It wouldn't be hard to create a parser for that, but
it's a bit hard to get motivated to do that, since
Google Code is dead.

Have you looked at https://code.google.com/export-to-github/

+++ anatoly techtonik [May 04 16 01:52 ]:

**Comment by techtonik** [comment]
That converter strips edits history, so I do manual import from hg and push to GitHub.

**Comment by techtonik** [comment]
I found the source the Google Code uses, so it might be no actual anymore. But I am still curious just how hard it is to write own converter? I expected to see some docs about this in Documentation menu http://pandoc.org/ but don't see any.

**Comment by tarleb** [comment]
@techtonik One would need to write a new google code wiki reader, converting the wiki syntax into pandoc's internal format. The syntax looks similar to mediawiki, so you'd might get decent results just using that reader.

As to how difficult it is to support a new format, here's a case in point: I wrote the org-mode parser with very moderate haskell skills. It took me about a month to get it into a state I'd describe as "not entirely aweful".  Others would probably be much faster hammering out support for a new format, especially if it is very similar to something that's already supported. Depending on your skill level and whether you plan to polish it up for publication, my very rough guess would be "slightly more than a weekend or up to two full weeks".

**Comment by techtonik** [comment]
@tarleb so there is no any "framework" or some kind of "data transformation theory", just a plain bruteforce haskell coding?

**Comment by tarleb** [comment]
It pays to know how Pandoc works and how to use the Parsec library, but the rest is indeed nothing but plain haskell hacking.

**Comment by techtonik** [comment]
Parsec looks like EBNF parser. So it can validate if markup is right, but I guess the conversion rules have to be written by hand and there is no debugger, no test framework, no declarative mapping of markup constructs.
