### ISSUE TITLE
yaml metadata block for scientific publications

### ISSUE THREAD

**Issue by dwaggott** [jgm/pandoc#2899]
I'm working on a process for getting collaboratively written scientific journal articles (in google docs) into latex via pandoc. Currently I export as a docx, convert to markdown via pandoc, split the markdown into a yaml metadata and main text, then convert to pdf via pandoc. The yaml metadata has the title, authors and abstract.

1) I have multiple authors and each has multiple affiliations. Currently no matter what I do each author gets output as `TRUE`. Any ideas?
2) Has anyone played around with the template to get multiple affiliations working? Ideally with superscript pointers to a list below.
3) Funding or Acknowledgments would be helpful sections to add to the latex template
4) Are there any ways to markup the docx so that the yaml metadata section can be auto-generated?

**Comment by Jmuccigr** [comment]
Hard to tell on #1 without an example.

**Comment by jgm** [comment]
+++ Daryl Waggott [May 04 16 08:59 ]:
>   I'm working on a process for getting collaboratively written scientific
>   journal articles (in google docs) into latex via pandoc. Currently I
>   export as a docx, convert to markdown via pandoc, split the markdown
>   into a yaml metadata and main text, then convert to pdf via pandoc. The
>   yaml metadata has the title, authors and abstract.
>
>   1) I have multiple authors and each has multiple affiliations.
>   Currently no matter what I do each author gets output as TRUE. Any
>   ideas?

You need a custom template to have structured authors.  See
the README.

```
Note: The `author` variable in the default templates expects a simple list or
string.  To use the structured authors in the example, you would need a
custom template.  For example:

    $for(author)$
    $if(author.name)$
    $author.name$$if(author.affiliation)$ ($author.affiliation$)$endif$
    $else$
    $author$
    $endif$
    $endfor$
```
There may be a more elegant way to do this in LaTeX.

>   2) Has anyone played around with the template to get multiple
>   affiliations working? Ideally with superscript pointers to a list
>   below.
>   3) Funding or Acknowledgments would be helpful sections to add to the
>   latex template

Just use a custom template.  See the README on Templates.

>   4) Are there any ways to markup the docx so that the yaml metadata
>   section can be auto-generated?

I believe fields in the docx "properties" will come across as metadata.

**Comment by dwaggott** [comment]
Here is a snippet. 

https://gist.github.com/463d54c083a3d02c74c974cb999221cc

**Comment by jgm** [comment]
Yes, see above. Use a custom template.  Actually, the one I give above won't be enough for you, since you have lists of institutes.  Try something like:

```
\author{
$for(author)$
$author.name$
($for(author.institute)$$author.institute$$sep$, $endfor$)
$sep$\and
$endfor$
}
```

**Comment by jgm** [comment]
PS.  For questions like this, use the pandoc-discuss mailing list.  Many more people will read it and be able to help.  This tracker is for bug reports.
