### ISSUE TITLE
pdf conversion does not work if pdflatex is a batch file

### ISSUE THREAD

**Issue by janschulz** [jgm/pandoc#2903]
There is a new conda package which installs miktex in a python virtualenv, but to include pdflatex and other commandline commands in the PATH, it creates batch files in a dir in the PATH. Unfortunately, it seems that pandoc expects a exe?

```bat
[pypandoc_35] λ where pdflatex
C:\portabel\miniconda\Scripts\pdflatex.bat

[pypandoc_35] λ pandoc --version
pandoc 1.17.0.2
[...]

[pypandoc_35] λ echo "ok" | pandoc -f markdown -t latex -o text.pdf
pandoc: pdflatex not found. pdflatex is needed for pdf output.

[pypandoc_35] λ set PATH=c:\portabel\miniconda\Library\miktex\miktex\bin\;%PATH%

[pypandoc_35] λ where pdflatex
c:\portabel\miniconda\Library\miktex\miktex\bin\pdflatex.exe
C:\portabel\miniconda\Scripts\pdflatex.bat

[pypandoc_35] λ echo "ok" | pandoc -f markdown -t latex -o text.pdf
```

It also works if I specify the full path to the batch file, so the batch files work:
```bat
[pypandoc_35] λ echo "ok" | pandoc --latex-engine=C:\portabel\miniconda\Scripts\pdflatex.bat -f markdown -t latex -o text.pdf
```

It seems that this can be traced down to the useage of `findExecutable` which seems to only consider `*.exe` files on windows :-( 

https://github.com/haskell/directory/blob/595f519d6f44191c52d00577568c6910635bb3d6/System/Directory.hs#L1047 ->
https://github.com/haskell/directory/blob/1f3e013cd0319ae501fa2c337cb4b0135f793e2a/System/Directory/Internal/Config.hs

Would it be possible to also check for *.bat on windows?

**Comment by jgm** [comment]
findExecutable is from the directory library (and I don't
maintain that, so I can't change its behavior).
See its documentation here:
http://hackage.haskell.org/package/directory-1.2.6.3/docs/System-Directory.html#v:findExecutable
It calls a Windows function to find the executable.


+++ Jan Schulz [May 07 16 09:09 ]:

**Comment by janschulz** [comment]
Would it be possible to work around it by doing the same what the directory library does but check for both `.bat` and `.exe`?

**Comment by jgm** [comment]
`findExecutable` currently does this on Windows:
```hs
    Win32.searchPath Nothing binary exeExtension
```
where `exeExtension == ".exe"` and `binary` is (in this case) `"pdflatex"`.
I am not sure how the underlying Windows function works, but it might be worth experimenting a bit:  if you just use an empty string for the last parameter, instead of `exeExtension`, will it behave as you wish?

Replacing this with `".bat"` would not be good, because then we wouldn't find executables with an `.exe` extension (or so I assume).  Trying first with `".exe"` and then with `".bat"` wouldn't be good, because it would mean that a `.bat` higher in the search path would be passed over for an `.exe` lower in the search path.  But how does Windows itself do it?  Perhaps if you just pass the empty string for the `lpExtension` parameter of SearchPath, it will behave as Windows behaves by default and catch both .exe and .bat?

**Comment by janschulz** [comment]
According to the docs in [SearchPath](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365527(v=vs.85).aspx), an extension is only added if the filename itself does not contain one. On the other hand, the docs suggest that if no extension is given, the filename is taken as is = without a extension.

So for me it's not clear if there is an equivalent of `which pdflatex`: if SearchPath is used, it would basically be two calls: "first search exe in PATH and of not found try bat in PATH", but normally it's "no matter what executable extension, find the first one in PATH". 

IMO the easiest would be to call `pdflatex --version` and if that succeeds treat it as available :-)

On the other hand, I'm not sure if haskells `createProcess` can be used to call bat files or if you need to go the `cmd /c name.bat` way like in the windows API equivalent: http://stackoverflow.com/questions/11822051/win32-api-like-createprocess-but-works-on-bat-cmd-etc-i-e-uses-pathext ...:-(

This issue seems to be harder than I thought... We do now have a workaround in miktex package: we compile a small wrapper which just calls the right exe in the subdirectory... It's a bit messy as I currently use GO and the executable is 2MB big, but it works with pandoc: https://github.com/conda-forge/miktex-feedstock/pull/4

**Comment by jgm** [comment]
I'm trying the `pdflatex --version` method.
Let me know how it works for you.

**Comment by janschulz** [comment]
Ist there somewhere a windows build? Or do you want a Appveyor one?

**Comment by janschulz** [comment]
Ok, this didn't work:

```
C:\Users\jschulz\Application Data\pandoc
λ which pdflatex
C:\portabel\miniconda\Scripts\pdflatex.bat

C:\Users\jschulz\Application Data\pandoc
λ echo "ok" | pandoc -f markdown -t latex -o text.pdf
pandoc: pdflatex: readCreateProcessWithExitCode: does not exist (No such file or directory)
```

pandoc from here: https://ci.appveyor.com/project/JanSchulz/pandoc/build/1.0.3/artifacts (stack didn't want to install in my system :-()

**Comment by jgm** [comment]
Try the latest.  And I love the appveyor setup!  I've tried
to get pandoc to build on appveyor many times, but I've
never succeeded (I don't have a paid account, and I always
run up against the build time limitations).  Are you using
a paid account or did you somehow manage to build anyway?

+++ Jan Schulz [May 10 16 05:07 ]:

**Comment by janschulz** [comment]
No, just a regular one... It's more or less the one from the pandoc repo... Will do a PR :-)

**Comment by janschulz** [comment]
The main problem

```
c:\data\external\pandoc (master)
λ echo "ok" | pandoc -f markdown -t latex -o text.pdf
pandoc: Could not find data file C:\stack\.stack-work\install\43452594\share\i386-windows-ghc-7.10.3\pandoc-1.17.1\data\templates\default.latex
```

-> Is there a way to tell pandoc not to look for default templates?

**Comment by jgm** [comment]
+++ Jan Schulz [May 10 16 14:07 ]:
>   -> Is there a way to tell pandoc not to look for default templates?

Yes, you can specify a template manually using `--template`.

Note also that if you compile pandoc with the
`embed_data_files` flag (which requires hsb2hs for the
build) then the binary will embed the data, so you won't
have this problem.

**Comment by janschulz** [comment]
> embed_data_files` flag (which requires hsb2hs

Seems that I have to call stack with `windows/stack.yaml`? Hm...

**Comment by janschulz** [comment]
Ok, still not working:

```
c:\data\external\R
λ echo "ok" | pandoc -f markdown -t latex -o text.pdf
pandoc: pdflatex not found. pdflatex is needed for pdf output.

c:\data\external\R
λ which pdflatex
C:\portabel\miniconda\Scripts\pdflatex.bat
```

-> Could it be that `readProcessWithExitCode`  also only looks for `*.exe`?

**Comment by jgm** [comment]
+++ Jan Schulz [May 10 16 16:42 ]:
>   Ok, still not working:
>c:\data\external\R
>λ echo "ok" | pandoc -f markdown -t latex -o text.pdf
>pandoc: pdflatex not found. pdflatex is needed for pdf output.
>
>c:\data\external\R
>λ which pdflatex
>C:\portabel\miniconda\Scripts\pdflatex.bat
>
>   -> Could it be that readProcessWithExitCode also only looks for *.exe?

I don't know.  Your .bat has executable permissions?

**Comment by janschulz** [comment]
Windows has no executable permission... :-)

I meant this:

```
shell :: String -> CreateProcess
shell str = CreateProcess { cmdspec = ShellCommand str,
                            cwd = Nothing,
                            env = Nothing,
                            std_in = Inherit,
                            std_out = Inherit,
                            std_err = Inherit,
                            close_fds = False,
                            create_group = False,
                            delegate_ctlc = False,
                            detach_console = False,
                            create_new_console = False,
                            new_session = False,
                            child_group = Nothing,
                            child_user = Nothing }

{- |
This is the most general way to spawn an external process.  The
process can be a command line to be executed by a shell or a raw command
with a list of arguments.  The stdin, stdout, and stderr streams of
the new process may individually be attached to new pipes, to existing
'Handle's, or just inherited from the parent (the default.)

The details of how to create the process are passed in the
'CreateProcess' record.  To make it easier to construct a
'CreateProcess', the functions 'proc' and 'shell' are supplied that
fill in the fields with default values which can be overriden as
needed.
```
[from http://hackage.haskell.org/package/process-1.4.2.0/docs/src/System.Process.html#createProcess]

**Comment by jgm** [comment]
OK, I've pushed another attempt using shell.

+++ Jan Schulz [May 11 16 11:05 ]:

**Comment by janschulz** [comment]
Still no change: 

```
c:\data\external\pandoc (master)
λ echo "ok" | pandoc -f markdown -t latex -o text.pdf
pandoc: pdflatex: createProcess: does not exist (No such file or directory)

c:\data\external\pandoc (master)
λ which pdflatex
C:\portabel\miniconda\Scripts\pdflatex.bat

c:\data\external\pandoc (master)
λ git slog |head -1
609fb33 Merge pull request #2913 from jlduran/strut-minipage-tables
```

**Comment by jgm** [comment]
That error message means that the initial check (in pandoc.hs) did indeed find your batch file (otherwise the error would have been trapped and you'd have been told that you need `pdflatex` in the path).

Now, I assume, it's failing to find it in Text.Pandoc.PDF, so that needs to be changed to use shell as well.  Text.Pandoc.PDF uses `pipeProcess` in Text.Pandoc.Process, and this uses `proc` rather than `shell`. 

Could I just change this to use `shell`?  Well, since `shell` just takes a String, I'd have to do all the necessary quoting and escaping myself.  And I'm worried that this would be too error-prone.  Do you have any suggestions?

**Comment by jgm** [comment]
I've reverted everything, so we're back to `findExecutable`.  I can't think of another solution I'd be confident in.  If you think of something, feel free to open a new issue ro suggest it here.

**Comment by janschulz** [comment]
Ok, thanks for your time and effort trying to solve that here! Sorry that it didn't work :-/
