### ISSUE TITLE
auto_identifiers and implicit_header_references 

### ISSUE THREAD

**Issue by jerryasher** [jgm/pandoc#2904]
Examine:

http://pandoc.org/try/?text=%23+A+test+of+pandoc%27s+implicit+header+references%0A%23%23+Header+identifiers+in+html%0A%23%23%23+Simple+testing+of+implicit+header+references%0A%0A1.+[Header+identifiers]%28%23header-identifiers-in-html%29%0A2.+[Header+identifiers]++%0A3.+[Header+identifiers][]%0A4.+[the+section+on+header+identifiers][header+identifiers]%0A5.+[Header+identifiers+in+html]++%0A6.+Visit+[Simple+testing]++&from=markdown&to=html5

It's a test of pandoc markdown documented http://pandoc.org/README.html#header-identifiers

```
# A test of pandoc's implicit header references
## Header identifiers in html
### Simple testing of implicit header references

1. [Header identifiers](#header-identifiers-in-html)
2. [Header identifiers]  
3. [Header identifiers][]
4. [the section on header identifiers][header identifiers]
5. [Header identifiers in html]  
6. Visit [Simple testing]  
```

Reading the section http://pandoc.org/README.html#extension-implicit_header_references, I believe that examples 1-5 above should all render as a hyperlink to the header, "Header identifiers in html", but the generated doc code shows that only examples 1 and 5 render according to the pandoc documentation. Example 6 should render as a hyperlink to the header, "Simple testing of implicit header references", but it does not.

![image of pandoc documentation regarding implicit_header_references](http://i.imgur.com/qB0JtVT.png)

Specifically, it generates as:

```
<h1 id="a-test-of-pandocs-implicit-header-references">A test of pandoc’s implicit header references</h1>
<h2 id="header-identifiers-in-html">Header identifiers in html</h2>
<h3 id="simple-testing-of-implicit-header-references">Simple testing of implicit header references</h3>
<ol type="1">
<li><a href="#header-identifiers-in-html">Header identifiers</a></li>
<li>[Header identifiers]<br /></li>
<li>[Header identifiers][]</li>
<li>[the section on header identifiers][header identifiers]</li>
<li><a href="#header-identifiers-in-html">Header identifiers in html</a><br /></li>
<li>Visit [Simple testing]</li>
</ol>
```

which renders as

<h1 id="a-test-of-pandocs-implicit-header-references">A test of pandoc’s implicit header references</h1>
<h2 id="header-identifiers-in-html">Header identifiers in html</h2>
<h3 id="simple-testing-of-implicit-header-references">Simple testing of implicit header references</h3>
<ol type="1">
<li><a href="#header-identifiers-in-html">Header identifiers</a></li>
<li>[Header identifiers]<br />
</li>
<li>[Header identifiers][]</li>
<li>[the section on header identifiers][header identifiers]</li>
<li><a href="#header-identifiers-in-html">Header identifiers in html</a><br />
</li>
<li>Visit [Simple testing]</li>
</ol>

**Comment by Jmuccigr** [comment]
I think you're misunderstanding the instructions. Right now 2-4 refer to a header that doesn't exist ("Header identifier"). Instead you have the header "Header identifiers in html".

So replace your second line with:

`## Header identifiers`

Then 1-4 will work, but 5 won't.

**Comment by jgm** [comment]
What part of the documentation makes you think that
2-4 should produce implicit references?  You need the
full text of the section header, not just part of it,
in the reference.

**Comment by jerryasher** [comment]
Ah, thanks for clearling that up

> What part of the documentation makes you think that
2-4 should produce implicit references?  You need the
full text of the section header, not just part of it,
in the reference.

If I write:
    [header identifiers](#header-identifiers-in-html)

What should the actual section header be?

If I understand correctly now, you were referring to a header that looks something like

    ### doesn't matter {#header-identifiers-in-html}
or   

    ### Header Identifiers {#header-identifiers-in-html}

but not

    ###Header Identifiers in HTML

If that's right, I guess my confusion stems from two things, first, not understanding in your example that the section *Header Identifiers* would be given the very much longer label of #header-identifiers-in-html, and then second, that this took place immediately after a somewhat complex discussion of how pandoc munges section headers to make valid labels out of them. 

So when I saw

>So, **_instead of_**  
>     \[header identifiers](#header-identifiers-in-html)
>you can simply write
>
>    [header identifiers]
>or
>
>    [header identifiers][]
>or
>
>    [the section on header identifiers][header identifiers]

I interpreted that to mean the very nice *feature*, that I not gather doesn't exist, that I can refer to prior sections using any abbreviated form of their section heading as a label to them, provided that that uniquely identifies them.

    #Best Cars of 2016

might be referred to as

    [Best Cars of 2016](#best-cars-of-2016)
and also

    [Best Cars of 2016]
    [Best Cars]

and so on.

Thanks for the clarification. I'll leave this open, as I figure maybe I still don't understand it, but if I have it now, please do close it.

**Comment by Jmuccigr** [comment]
Read [this section](http://pandoc.org/README.html#header-identifiers) in the user guide.

**Comment by jerryasher** [comment]
Thanks, I actually read that section (many times) and still left a bit confused and for the reasons I gave above. 

Perhaps as a clarification, what may have helped me, is if instead of writing

>  A link to this section, for example, might look like this:

>> See the section on
> >   \[header identifiers](#header-identifiers-in-html-latex-and-context)

It had been written

>  This section, for example, was marked as

>>     ### Header Identifiers

> It can be referenced as....

*might* seems a bit tenuous as if it may or may not work, or as if other alternatives are possible.

**Comment by jgm** [comment]
Looking back at the documentation, I see why it confused
you.  I have attempted a rewrite; let me know if this is
better.

**Comment by jerryasher** [comment]
Yes, I think that's clearer and would have even gotten through to me, so thank you!
