### ISSUE TITLE
Pandow 1.17.0.2 not running on Win 7

### ISSUE THREAD

**Issue by q2apro** [jgm/pandoc#2914]
Got this file:[ pandoc-1.17.0.2-windows.msi](https://github.com/jgm/pandoc/releases/download/1.17.0.2/pandoc-1.17.0.2-windows.msi) 

Installed it under Windows 7. 

Run the CMD. 

`pandoc` gave me: 

![capture](https://cloud.githubusercontent.com/assets/6764548/15189947/1457642a-17b6-11e6-8a1d-e97724f65ef2.PNG)

I tried the group install, then the single install. No difference. 

I started the CMD in admin mode, no difference. 

I cannot submit the text to pandoc. http://pandoc.org/getting-started.html says it is `CTRL+Z` but it does not work...

PS1: In my first installation I was using the "group installatino". 

PS2: `pwd` is not working in the command line.

PS3: Is there no other shortcut to submit the entered text?

**Comment by jgm** [comment]
^Z then hit enter.

You can also try giving it a filename as argument.

+++ q2apro.com [May 11 16 10:25 ]:

**Comment by q2apro** [comment]
> ^Z then hit enter.

Does not work, unfortunately.

However, executing pandoc.exe in its folder with parameters works.
