### ISSUE TITLE
Calling GNUPlot from raw Latex fails, -shell-escape is enabled

### ISSUE THREAD

**Issue by clentfort** [jgm/pandoc#2917]
I'm trying to convert a markdown-file, in which I have a raw tex block with a TikZ-picture, directly to PDF. This fails with the following error ( `-shell-escape` is set in `--latex-engine-opt`).

```
! Package pgfplots Error: Sorry, the gnuplot-result file 'input.pgf-plot.table'
 could not be found. Maybe you need to enable the shell-escape feature? For pdf
latex, this is '>> pdflatex -shell-escape'. You can also invoke '>> gnuplot <fi
le>.gnuplot' manually on the respective gnuplot file..

See the pgfplots package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.70         \addplot gnuplot {sin(x)};

pandoc: Error producing PDF
```

I created a small gist which helps to recreate the error: https://gist.github.com/clentfort/4b0a13fde312d4821ea794d4a6c2f43b

**Comment by clentfort** [comment]
It seems it might be related to the problem described here: http://tex.stackexchange.com/questions/136012/output-directory-and-shell-commands

**Comment by jgm** [comment]
Yes, I think this is the issue.  It seems that some of the
LaTeX packages were not designed keeping in mind that the
output directory might not be the working directory...
I don't think there's anything we can do about this in
pandoc.

+++ Chris Lent [May 12 16 07:54 ]:

**Comment by clentfort** [comment]
I don't know much about the design of pandoc, but might it be possible to CD into the temp-dir instead of specifying it as the output-dir parameter to the latex engine? This is pretty much my workaround for now, use pandoc to convert from markdown to tex and than have my makefile copy all inputs into a temp-dir, CD into it and compile from there.

**Comment by jgm** [comment]
+++ Chris Lent [May 12 16 11:22 ]:
>   I don't know much about the design of pandoc, but might it be possible
>   to CD into the temp-dir instead of specifying it as the output-dir
>   parameter to the latex engine?

Then other things break (e.g. paths to images relative to
the working dir).

**Comment by clentfort** [comment]
Again I don't know anything about pandoc internals but I imagine the input-files are parsed in someway and stored in some form of AST. Wouldn't it be possible to simply update the nodes, that pull anything external in, to use the absolute path instead of a relative one?

**Comment by jgm** [comment]
There are lots of complexities to doing this right.
Determining whether we have absolute or relative paths,
correctly adjusting the paths (which may work differently
on different OSes), interacting properly with LaTeX's
complex methods for finding things, and so on.

Plus, it's not just images.  People might use raw
LaTeX `\include`s, for example.  We'd have to parse all
the raw LaTeX to get these right.

I think that the present system works well, except for
this application, which really seems to me to point to a
deficiency in the package that shells out to gnuplot
(not taking account of output directory), and should be
addressed there.

+++ Chris Lent [May 12 16 12:18 ]:

**Comment by clentfort** [comment]
Well totally agree with you about that this should be a fix in the related package, I was just wondering if a work-around would be possible. Is there any "known issues" page or alike were this information could be added more prominently?

**Comment by jgm** [comment]
+++ Chris Lent [May 12 16 13:34 ]:
>   Well totally agree with you about that this should be a fix in the
>   related package, I was just wondering if a work-around would be
>   possible. Is there any "known issues" page or alike were this
>   information could be added more prominently?

There is a FAQ on the website but I suspect that the search
feature on GitHub issues is going to be more used and more
reliable.
