### ISSUE TITLE
join for $arrays$

### ISSUE THREAD

**Issue by aurium** [jgm/pandoc#2918]
I have this variable on my source document
```
tags: [tag1, tag2, tag3]
```

I have this code on my template.latex:
```
$for(tags)$, tags$endfor$
```
it generates: `, tag1, tag2, tag3`
Not nice :-(

Could we have something like `\join[,]{tags}` or `$join[,](tags)$` ?
_(i don't know latex, sorry if the proposal is not valid)_

**Comment by mb21** [comment]
you can use

    $for(tags)$$tags$$sep$, $endfor$

**Comment by aurium** [comment]
Great! Thanks.
