### ISSUE TITLE
Expose secnumdepth (numbersections)

### ISSUE THREAD

**Issue by mgansler** [jgm/pandoc#2920]
Hi,

the default latex template looks like this:

```
$if(numbersections)$
\setcounter{secnumdepth}{5}
$else$
\setcounter{secnumdepth}{0}
$endif$
```

Why not change it to 

```
$if(numbersections)$
\setcounter{secnumdepth}{$numbersections$}
$else$
\setcounter{secnumdepth}{0}
$endif$
```

That way the user can define exactly how many levels should be numbered.

I don't know if this is used in other templates as well and how it would interfere with the command line option `-N`. I guess when the command line is parsed `numbersections` could be set to `5` by default so it would not break anything.

**Comment by jgm** [comment]
I suspect things would break because people may have `numbersections: true` in metadata.
It would be better to just create a variable `secnumdepth`.
