### ISSUE TITLE
Pandoc replacing some underscores by UTF-8 bytes

### ISSUE THREAD

**Issue by Phyks** [jgm/pandoc#2921]
Hi,

I noticed an issue with underscores, which [arised in pandoc-crossref](https://github.com/lierdakil/pandoc-crossref/issues/66#issuecomment-216030919) when using underscores in section labels.

```
$ pandoc -t latex <<< "#Section {#section_label}"
\section{Section}\label{sectionux5flabel}
```

We can see that `section_label` is turned to `sectionux5flabel` and `ux5f` makes me think in unicode `0x5f` which is `_`. This could be replicated with the latest stable version of Pandoc.

/cc @lierdakil

**Comment by jgm** [comment]
See toLabel in Text.Pandoc.Writers.LaTeX.

To work around latex's limitations in what can go in a
label, we convert everything other than an ASCII letter,
digit, or the punctuation marks `-+=:;.` to its hex
character code.  I see that the underscore `_` is not in
this list, and I wonder why.  (It was a long time ago.)
It could be an oversight, or it could be for a reason.

After a bit of looking, it seems that `_` is supported
in labels (though it can cause problems with certain
external packages).  I think we should probably add
`_` to the list, but maybe others can see a problem
with this?

+++ Lucas Verney [May 16 16 04:00 ]:

**Comment by Phyks** [comment]
Ok, thanks for the explanation!

I have always used `_` in LaTeX labels without noticing any error, I was not aware it could be bad practice.
