### ISSUE TITLE
Markdown reader: add extension for GitHub wiki's internal link syntax [[page name]]

### ISSUE THREAD

**Issue by ferventcoder** [jgm/pandoc#2923]
Forgive me if this has already been noted as an issue but I did a bit of searching through issues and online and didn't turn up with anything.

I'm on the latest version of Pandoc (1.17.0.2) and I'm attempting to use markdown_github to convert to HTML. I'm noticing that Pandoc does not convert links that look like the following:
- `[[example link|MarkdownPage]]`
- `[[MarkdownPage]]`

It's possible we are using outdated constructs, but GitHub has supported this for years. I noticed that Sublime supports the second but not the first with it's regular markdown preview tool.

The command I'm running:
`pandoc --from markdown_github+simple_tables+native_spans+native_divs+multiline_tables --to html5 [..snip..]`

Is this something that could be added for conversion? Or is there an extension that already does this that I may have missed?

**Comment by jgm** [comment]
The syntax is documented [here](https://help.github.com/articles/adding-links-to-wikis/).
However, I believe it only works for GitHub wikis, and not in other contexts (e.g. bug reports).  Proof:
[[example link|MarkdownPage]]

It would be worth adding an extension for this.

**Comment by ferventcoder** [comment]
Thanks @jgm! Pandoc is pretty amazing!  I'll admit I haven't read the source, but this is the regex I'm using to do this conversion now:
https://github.com/ferventcoder/chocolatey.org/blob/45765dd4cc2f9d2675d0f48fd4dd60669afb8bf8/UpdateDocumentation.ps1#L12-L24

**Comment by jgm** [comment]
Re-opening, on the realization that we really need the parser in a commonmark extension (so it can be used with`gfm`).  Once that is available, we could *also* add a parser to pandoc's markdown reader, but I don't want to just add it to the latter; it will cause too much confusion.

**Comment by jgm** [comment]
The tests and extension module work in #6458 will be useful when the commonmark-hs extension is available.

**Comment by edrex** [comment]
[Emanote](https://note.ema.srid.ca/) (a publishing tool compatible with Obsidian and Foam) has its own implementation of the `[[Page|Label]]` syntax used by most wikis but it would be nice to switch to an upstream one.

https://github.com/srid/emanote/blob/master/src/Emanote/Pandoc/Markdown/Syntax/WikiLink.hs

**Comment by anutator** [comment]
Please add mediawiki images conversion:
`![[image1.png]]`
