### ISSUE TITLE
EPUB reader: html entities in epub internal filenames cause errors

### ISSUE THREAD

**Issue by arifz** [jgm/pandoc#2924]
I get errors like the following, on epub files which otherwise test ok (by Sigil) 
   pandoc: No entry on path: OEBPS/Text/Authors%20Note.xhtml
   pandoc: No entry on path: OEBPS/Back%20Cover%20Text.html
The files are there, but the name of the file has a space instead of %20. This seems to cause no problems to epub readers, but pandoc aborts the entire process. The error I noticed occurred trying to convert epub to plain, with the latest pandoc 1.17.0.2 Compiled with texmath 0.8.5, highlighting-kate 0.6.2.

When the space in the filename is replaced with %20, pandoc works without a hitch, but I don't think that should be necessary. I am not sure what the standards say, but I am running into a number of files with this problem.

**Comment by jgm** [comment]
Can you link to or send an epub that causes the issue?

**Comment by arifz** [comment]
The actual epub contains private information, but I could remove personal
stuff from it. Instead I tried to install the latest version from git, so
that I could test it locally. Have been trying to install for the past day,
without success, perhaps because this is the first time I am doing anything
with haskell. Looks like I am getting closer to an install. If not, I will
send a minimal working bug, for you to try.

Arif

**Comment by arifz** [comment]
Success. Installed latest, and it works!
Thanks for the unbelievably speedy response.
