### ISSUE TITLE
pandoc.exe: Data.Binary.Get.runGet at position 0: not enough bytes

### ISSUE THREAD

**Issue by mahteshamulhaq** [jgm/pandoc#2926]
I use to convert my text file into Word (or any other format like PDF) file using Pandoc with this command 
`pandoc -s abc.txt -o abc.docx`

but since yesterday i am getting this error when i try to convert into word file i get this error

`pandoc.exe: Data.Binary.Get.runGet at position 0: not enough bytes`

it work fine when i try to convert into PDF and other format but it stop working for DOCX (word file )

I tried to google but no help on it :(

**Comment by jgm** [comment]
Please upload a file we can test with, and give the exact command you used, and the pandoc version you're using.

**Comment by mahteshamulhaq** [comment]
Pandoc version = 1.17.0.2
Exact command is (which i wrote in my question as well )
`pandoc -s abc.txt -o abc.docx`

error is 
![err](https://cloud.githubusercontent.com/assets/19428027/15417837/6286138a-1e73-11e6-8e16-fc89b8f1f927.png)

file i am using is simple text file with "hello world" in it (i am uploading file any way )

[abc.txt](https://github.com/jgm/pandoc/files/273899/abc.txt)

this conversion was working fine untill 2 day ago , but all of sudden it stop working , it is working fine for pdf and other formats , 
and other intresting thing is that its still working fine for all format in my local system 

System information :
Window server 2008 R2 enterprise 
64 bit system
pandoc-1.17.0.2-windows


i tried to reinstall the pandoc and MS office but still same issue :(

**Comment by jgm** [comment]
Nothing changed in your pandoc installation?

I am guessing that the problem is a corrupted reference.docx file.
How did you install pandoc -- with the installer we provide or in another way?
Also, do you have a file called `reference.docx` in your "default user data directory" (whose location you can learn by doing `pandoc --version`)?

**Comment by mahteshamulhaq** [comment]
i installed pandoc with the help of installer you provide on pandoc site 
[pandoc ](http://www.pandoc.org/installing.html)
[Download link ](https://github.com/jgm/pandoc/releases/tag/1.17.0.2)

and yes i have refrence.docx  in our "default user data directory" , and what do you mean is it corrupt 
i can open it with MS office and no error 
[here is link of reference.docx](https://github.com/jgm/pandoc/files/274059/reference.docx)

this is out of context of this question but i am also having issue styling my table inside my document with the help of above reference doc , please tell me am i doing it correctly 
if not can you please provide a reference doc example in which i can change the table style (right now i only want to border my table )

**Comment by jgm** [comment]
+++ mahteshamulhaq [May 20 16 00:15 ]:
>   i installed pandoc with the help of installer you provide on pandoc
>   site
>   [1]pandoc
>   [2]Download link
>
>   and yes i have refrence.docx in our "default user data directory" , and
>   what do you mean is it corrupt
>   i can open it with MS office and no error
>   [3]here is link of reference.docx

OK, that looks okay.

As I mentioned, also try

    pandoc --print-default-data-file reference.docx > myref.docx

and attach or link to that.

>   this is out of context of this question but i am also having issue
>   styling my table inside my document with the help of above reference
>   doc , please tell me am i doing it correctly
>   if not can you please provide a reference doc example in which i can
>   change the table style (right now i only want to border my table )

You can post qusetions like this to the pandoc-discuss
mailing list.

**Comment by mahteshamulhaq** [comment]
here is the file which i get after running the command you send me 
` pandoc --print-default-data-file reference.docx > myref.docx`

[myref.docx](https://github.com/jgm/pandoc/files/274298/myref.docx)

can you tell me what this command do 
and why there is "hello world" written when i open myref.docx

**Comment by jgm** [comment]
That command generates a copy of the system reference.docx file (which might be different from the one you have in the user data directory).  The "hello world" is just part of the default reference.docx file.  It gets replaced by your own content when you generate a docx using this reference.docx.

Can you try using this reference.docx explicitly?

```
pandoc abc.txt -o abc.docx --reference-docx myref.docx
```

**Comment by mahteshamulhaq** [comment]
I get this file when i try the above command 
`pandoc abc.txt -o abc.docx --reference-docx myref.docx`
[abc.docx](https://github.com/jgm/pandoc/files/283570/abc.docx)
