### ISSUE TITLE
Front Page before TOC in docx

### ISSUE THREAD

**Issue by WILKINSONC2** [jgm/pandoc#2928]
Hi, I'm trying to find an easy way to add a cover page before the TOC, going from markdown to docx. Can't find a simple solution. Tried merging docxs but the orginal TOC is not implemented.

Would appreciate your thoughts...?

**Comment by blindmelon** [comment]
With odt it is possible if you don't mind post-processing the output file with perl or similar. Maybe the same can be done for docx.

This is one of the things that makes me think docx and odt should be implemented using templates like most other output formats. I think it would add a huge amount of flexibility, and enable fancier features of the formats to be used.

**Comment by ah3662** [comment]
I'm wondering the same thing. I also tried merging a cover page onto the content and got the same issue with the TOC.

**Comment by aditivin** [comment]
I would also really like this feature. Seems like there have been many similar tickets for a few years - is there a plan to implement this or is it in progress by any chance? I would love to help if not.
