### ISSUE TITLE
Syntax for summary slides?

### ISSUE THREAD

**Issue by CodeGnome** [jgm/pandoc#2929]
When creating slides from pandoc, the `--table-of-contents` flag doesn't seem to do anything. Even if it did, slide decks often need summary slides that show the headers of the slides below them. Is it possible to support auto-generation of a table of contents and summary slides in pandoc slides?

**Comment by cagix** [comment]
Assuming you are using beamer and latex/xelatex: I can confirm the issue when using level 1 headers (sections) to start slides. This way I just get a blank slide where the toc should be. Using `--slide-level=1` does not change this.

However, using level 1 headers to structure the talk and level 2 headers to start slides, `--toc` (and `--table-of-contents`) works as expected.

Using Pandoc 1.17.2 here.

**Comment by cagix** [comment]
Regarding to some sort of toc in the middle of a talk: You can always use `\tableofcontents` on a slide when you need a (second) toc ... Providing the option `currentsection` will highlight the current section.

There are many more options to `\tableofcontents`, please cf. the beamer manual. 

If you need some sort of automatically inserted toc, like every new section, have a look at `\AtBeginSection` in the beamer manual. You can even add this to your default LaTeX template :)

**Comment by jgm** [comment]
+++ Carsten Gips [Aug 15 16 02:51 ]:
>   Assuming you are using beamer and latex/xelatex: I can confirm the
>   issue when using level 1 headers (sections) to start slides. This way I
>   just get a blank slide where the toc should be. Using --slide-level=1
>   does not change this.
>
>   However, using level 1 headers to structure the talk and level 2
>   headers to start slides, --toc (and --table-of-contents) works as
>   expected.

This is how it's supposed to work.  If everything is level
1, then you just have a bunch of slides with no structuring
sections.  Table of contents just records sections, and
slides are not themselves sections.

**Comment by cagix** [comment]
Yeah, I figured this after sending my comment :)   
Perhaps I should have put the afterthought to a new comment instead of editing the existing one, thus being more obvious and saving your time ... Sorry for this.
