### ISSUE TITLE
Pandoc converted Docx (word) give error when opening 

### ISSUE THREAD

**Issue by mahteshamulhaq** [jgm/pandoc#2931]
If i convert a text file (attched below) to docx with
`pandoc --toc -t docx --reference-docx=reference.docx -s abc.txt -o abc.docx`
i get the docx file but when i open it i give error while opening but show the file at the end 
please see the abc.docx to see what error i get 
all files are attached to check 

[abc.docx](https://github.com/jgm/pandoc/files/274464/abc.docx)
[abc.txt](https://github.com/jgm/pandoc/files/274465/abc.txt)
[reference.docx](https://github.com/jgm/pandoc/files/274463/reference.docx)

System information :
Window server 2008 R2 enterprise
64 bit system
pandoc-1.17.0.2-windows

**Comment by mahteshamulhaq** [comment]
please let me know did you able to replicate it ?

**Comment by mb21** [comment]
Could not reproduce on Mac. I got an error when opening your `abc.docx` file (`there are problems with the contents or the file name might contain invalid characters (for example, \/)`), but with pandoc 1.17.0.2 on Mac your command generated a working docx.

Can you try with pandoc 1.17.1 and a command as simple as possible? i.e. without a custom `reference.docx` and preferably without `--toc`
