### ISSUE TITLE
How can we change the style of heading while converting with Pandoc into PDf 

### ISSUE THREAD

**Issue by mahteshamulhaq** [jgm/pandoc#2932]
we are using pandoc to convert a file into PDF
How can we change the style of heading ( h1, h2)
i also add the --template which i get from 
[pandoc](http://www.pandoc.org/demos.html)
in this page , on example 14 "PDF with numbered sections and a custom LaTeX header:" i am able to change the fonts of PDF
 but how can i change the font of specific header (like H1 )
and how can i format (style , e.g border of table ) inside PDF while creating with Pandoc

**Comment by jgm** [comment]
This tracker is for bug reports.  Questions should go
on the pandoc-discuss mailing list.  Thanks!
