### ISSUE TITLE
How can i border  the table of Docx when its created from wiki with pandoc 

### ISSUE THREAD

**Issue by mahteshamulhaq** [jgm/pandoc#2933]
If i use pandoc to convert wiki into Docx with the help of reference docx ,
i can format or style the heading (h1,h2...) but i also want that i want to add border to my table in the docx
my reference docx and  is attached and you can see that i have give border to "Normaltable" in table design section

[reference.docx](https://github.com/jgm/pandoc/files/274515/reference.docx)
but it is not working

can some one guide me how can i add border to table in docx with reference file

as wiki file is unable to be uploaded here so here is the content of wiki (its simple table with 2 column)

{| class="wikitable"
|-
| '''ID''' 
| '''Name''' 
|-
|115
|sirajTest
|-
|15
|Test 
|-
|92
|haq
|}

please can some one create a refrence docx and share me the command which i need to run

**Comment by jgm** [comment]
Questions like this should go on the pandoc-discuss mailing
list on google groups, not this bug tracker.  This is for bug reports.
Thanks!
