### ISSUE TITLE
Long slides with many titles overflow Beamer theme breadcrumbs

### ISSUE THREAD

**Issue by CodeGnome** [jgm/pandoc#2936]
A number of Beamer themes (e.g. Zeged, Frankfurt) put the slide titles at the top like breadcrumbs. However, slides with long titles, or a large number of summary slides, overflow this line. For example, my slide deck with 12 title slides results in truncated output like the following:

![image](https://cloud.githubusercontent.com/assets/385462/15448797/ee51e0ee-1f39-11e6-84e7-5c080f87f404.png)

As you can see, only 7.5 of the 12 slides are displayed properly, and the long titles make it hard to tell which breadcrumb belongs to which slide title. While I recognize that this is (to at least some extent) a limitation of the theme, I think that Pandoc out to handle this gracefully by either wrapping the breadcrumbs, separating the breadcrumbs, adding a second breadcrumb line, or some other sensible thing.

Alternatively, if the transformation can't be handled gracefully, or if Pandoc knows data is being truncated, it should at least fail gracefully. I'm not sure whether Pandoc can do anything about this directly, but I think it's a generic problem that affects some of my other PDF output, and will certainly affect any large slide deck.

**Comment by jgm** [comment]
This seems like a beamer problem more than a pandoc problem.
I suggest you look in the beamer manual for a solution.  If there's a good solution, we may be able to change the output pandoc produces, but I'd need to know what it is.
