### ISSUE TITLE
Unexpected "\\" in apparently valid latex template

### ISSUE THREAD

**Issue by mesbahamin** [jgm/pandoc#2937]
Pandoc Version: 1.17.0.3

I am using a custom latex template to convert from markdown to pdf. I want itemized lists to use a star symbol, rather than the default hyphen, to mark second level items. I use `\renewcommand{\labelitemii}{$\star$}` in my template to achieve this.

The template itself is valid, compilable latex.

##### template.latex
```latex
\documentclass[12pt]{article} 

\providecommand{\tightlist}{
    \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

\renewcommand{\labelitemii}{$\star$}

\begin{document}
$body$
\end{document}

```

##### example.md
```markdown
List
----
- item
    - subitem
    - subitem
```

##### Output
`pandoc -o test.pdf --template=/path/to/template.latex example.md`

yields the following error:
```
pandoc: "template" (line 6, column 30):
unexpected "\\"
expecting letter
```

Oddly, commenting out `\renewcommand{\labelitemii}{$\star$}` still yields the same error.

**Comment by jgm** [comment]
The `$` character is a special character in pandoc
templates.  To insert a literal `$`, which is what you
want here, you need to escape it by doubling `$$`.

See the documentation on Templates.

+++ Amin Mesbah [May 21 16 13:39 ]:

**Comment by mesbahamin** [comment]
Thank you! That using $$ did indeed solve the problem. Now I'm off to RTFM.
