### ISSUE TITLE
Unexpected behaviour with two adjacent lists in markdown

### ISSUE THREAD

**Issue by jammon** [jgm/pandoc#2939]
If I have two lists in markdown like this:
```
- first item, first list
- second item, first list
- third item, first list

- first item, second list
- second item, second list
- third item, second list
```
then `pandoc -t html test.md` will give me:
```
<ul>
<li>first item, first list</li>
<li>second item, first list</li>
<li><p>third item, first list</p></li>
<li>first item, second list</li>
<li>second item, second list</li>
<li><p>third item, second list</p></li>
</ul>
```
with a `<p>` around the third item of *both* lists. What I expected was something like 
```
<ul>
<li>first item, first list</li>
<li>second item, first list</li>
<li>third item, first list</li>
</ul>
<ul>
<li>first item, second list</li>
<li>second item, second list</li>
<li>third item, second list</li>
</ul>
```
I realize that this reflects pandoc's concept of a "loose" list as indicated by empty lines between the items. I find it somewhat problematic, that this "loose list" idea is applied in a list that started compact. You could discuss, if the "loose item" should be the one before or after the blank line. (I found that behaviour because in the browser the third items had a bigger distance to the second ones than the first items. But that depends on the styling.)

But the `<p>` around the third item of the second list seems outright wrong. This appears even when the file ends after the second list without a blank line, even when there is no line feed after the last line.

**Comment by mb21** [comment]
In commonmark, a list can be ended by [two blank lines](http://spec.commonmark.org/0.25/#example-221). Maybe pandoc will change to that behaviour in a while, meanwhile you can intersperse a HTML comment:

    - first item, first list
    
    - first item, second list

**Comment by jgm** [comment]
I'm afraid this is just how Markdown works.  It's not a pandoc idiosyncracy.
See http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+first+item%2C+first+list%0A-+second+item%2C+first+list%0A-+third+item%2C+first+list%0A%0A-+first+item%2C+second+list%0A-+second+item%2C+second+list%0A-+third+item%2C+second+list%0A

Interspersing an HTML comment is the right approach.  The two-blank-lines thing in the current CommonMark spec isn't fully decided yet, so better not to rely on it.
