### ISSUE TITLE
Install pandoc without root access

### ISSUE THREAD

**Issue by gwgundersen** [jgm/pandoc#2943]
I'd like to install pandoc onto a Linux box to which I do not have root access (shared web hosting). Here are the commands I've run:

```
$ wget https://github.com/jgm/pandoc/releases/download/1.17.0.2/pandoc-1.17.0.2-1-amd64.deb
$ ar p pandoc-1.17.0.2-1-amd64.deb data.tar.gz | tar xvz --strip-components 2 -C $HOME
$ which pandoc
<home>/bin/pandoc
$ pandoc <some command>
pandoc: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory
```

Could someone help me address this? Thanks in advance.

**Comment by jgm** [comment]
GHC-compiled binaries link dynamically to libgmp.  So you
need to install that on your linux box.

+++ Gregory Gundersen [May 24 16 15:24 ]:

**Comment by gwgundersen** [comment]
Okay, thanks. I think I've correctly installed libgmp—all tests pass on `make check`. I used:

`./configure --prefix=$HOME/local`

pandoc still fails. Do I need to reinstall pandoc now that libgmp is installed?

**Comment by jgm** [comment]
+++ Gregory Gundersen [May 24 16 18:04 ]:
>   Okay, thanks. I think I've correctly installed libgmp—all tests pass on
>   make check. I used:
>
>   ./configure --prefix=$HOME/local
>
>   pandoc still fails. Do I need to reinstall pandoc now that libgmp is
>   installed?

Same error message?

Try `find /usr/lib /usr/local/lib -name libgmp.*` and see what you have
installed.  Do you see libgmp.so.10?

**Comment by gwgundersen** [comment]
Yeah, same error message. When I run `find /usr/lib /usr/local/lib -name libgmp.*`, I get `No such file or directory`. I think I'm sandboxed from touching anything outside of my user directory. This works:

```
$ find $HOME -name libgmp.*
/home1/<username>/local/lib/libgmp.a
/home1/<username>/local/lib/libgmp.so.10
/home1/<username>/local/lib/libgmp.so
/home1/<username>/local/lib/libgmp.so.10.3.0
/home1/<username>/local/lib/libgmp.la
/home1/<username>/gmp-6.1.0/.libs/libgmp.a
/home1/<username>/gmp-6.1.0/.libs/libgmp.so.10
/home1/<username>/gmp-6.1.0/.libs/libgmp.so
/home1/<username>/gmp-6.1.0/.libs/libgmp.lai
/home1/<username>/gmp-6.1.0/.libs/libgmp.so.10.3.0
/home1/<username>/gmp-6.1.0/.libs/libgmp.la
/home1/<username>/gmp-6.1.0/libgmp.la
```

**Comment by jgm** [comment]
Since you have everything installed in $HOME, you probably
need to set an environment variable to tell linux where
to find dynamically linked libraries.

See
http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
under LD_LIBRARY_PATH

Try

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home1/<username>/local/lib

You can export this in your .bashrc if you want, or just
set it on the command line before you run pandoc.

+++ Gregory Gundersen [May 24 16 20:59 ]:

**Comment by gwgundersen** [comment]
That worked! Thanks so much for your help.
