### ISSUE TITLE
html boolean attributes

### ISSUE THREAD

**Issue by felixsanz** [jgm/pandoc#2944]
In `<pre>` tags you can use:

``````
``` {.highlight data-language="bash" data-show-linenumbers} ...
``````

`data-show-linenumbers` doesn't work if you don't add `="true"` into it.

That is not a real boolean attribute, but just a string faking it. It is possible to make pandoc compatible with them?

**Comment by jgm** [comment]
This would require changes to pandoc-types, since a
Attribute is currently represented as a pair of strings.

**Comment by felixsanz** [comment]
I don't know in haskell, but in other programming languages this is as simple as an if condition testing for the "=" sign inside the string, right?

It is doable for pandoc or won't fix?

**Comment by jgm** [comment]
+++ Felix Sanz [May 25 16 14:24 ]:
>   I don't know in haskell, but in other programming languages this is as
>   simple as an if condition testing for the "=" sign inside the string,
>   right?

Parsing is no problem of course.

But what do you parse it too?

Currently attributes are parsed from a String to a
pair of Strings (String, String).

If we wanted to allow Boolean attributes, we'd need
a different type:  perhaps (String, Maybe String)
or (String, Value).

>   It is doable for pandoc or won't fix?

It's doable but involved and probably not a high
priority compared to other things.

**Comment by bucklereed** [comment]
HTML doesn't actually have 'true' boolean attributes: the syntax `<foo bar>` is syntactic sugar for `<foo bar="">`. Generally attributes used this way trigger things by their mere presence and the value is ignored, but there are exceptions and weirdness because of course there are exceptions and weirdness, it's the Web...

So, there's not actually any need for an AST change here, just a tweak of the Markdown reader (and possibly a new extension).

**Comment by jgm** [comment]
I think I'd prefer to keep things as they are, and make people use an explicit `=""` if that's what they really want.

**Comment by Porges** [comment]
I ran into this with `itemscope` (wanting to do `[…](…){itemscope itemtype="…"}`).

At the moment it simply fails to parse and you get the raw `{…}` bracketed value in the output. It seems it would be much nicer to allow it to parse (as empty string) – it would have a low chance of compatibility issues as the syntax is currently invalid.

**Comment by Porges** [comment]
Actually, there's a bug here at the moment, `itemscope=""` doesn't work because it turns into `itemscope="&quot;&quot;"`, which is invalid.

**Comment by Porges** [comment]
Actually, there's a bug here at the moment. `itemscope=""` doesn't work because it turns into `itemscope="&quot;&quot;"`, which is invalid.
