### ISSUE TITLE
add timestamp support in markdown variables

### ISSUE THREAD

**Issue by legrostdg** [jgm/pandoc#2952]
YAML seems to understand timestamps: http://www.yaml.org/spec/1.2/spec.html
You it be possible to add support for timestamps in markdown variables?
Something like:

```

---
mydate: 2015-12-31
...
$mydate.year$ $mydate.month$ $mydate.day$
```

**Comment by mb21** [comment]
If this is still desired, it should go to https://github.com/jgm/doctemplates/
