### ISSUE TITLE
beamer output : how to end a block

### ISSUE THREAD

**Issue by bozito** [jgm/pandoc#2957]
Is there a way to explicitly close the current block in beamer?
I want to achieve this in the tex file:

```
\begin{frame}{Slide One}
   \begin{block}{Block 1}
      Content of block 1
   \end{block}
   I want this out of the block one, between the two blocks
   \begin{block}{Block 2}
      Content of block 2
   \end{block}
\end{frame}

```

No matter how hard I try I did not find any way to end the current block without starting a new one.
Is this a bug? Is there a workaround?
Here is my MWE:

```

---
## To get the pdf
# pandoc -s block_ending_issue.md --slide-level 2 -t beamer  -V theme:Warsaw -o block_ending_issue.pdf
## To get the tex
# pandoc -s block_ending_issue.md --slide-level 2 -t beamer  -V theme:Warsaw -o block_ending_issue.tex
...


# Block ending issue in beamer

## Slide One

### Block 1
Content of block 1

I want this out of the block one, between the two blocks

### Block 2
Content of block 2

```

I tried the solution proposed in  https://groups.google.com/forum/#!msg/pandoc-discuss/DtUlwUvk0o8/h-7aQVwVlm4J but it only creates a new block without any title.

Any solution?

Cheers,

Bozito

**Comment by jgm** [comment]
No, there's no solution as far as I can see.  Pandoc turns
the whole section into a block, and the section only ends
when the next one begins.

**Comment by mb21** [comment]
Please mention a specific use-case... I'm closing this for now.

**Comment by henryiii** [comment]
Two use cases: First, a figure or preformatted code under a block (only way to do it now is to put it above the first block or inside a block, which is ugly). Second, this would probably help with #1710.

**Comment by henryiii** [comment]
Pandoc 2.0.0.1, via Brew on macOS.

Code:

```md
---
title: No Escape
author: Henry Schreiner
date: October 31, 2017
theme: Warsaw
---

# Slide 1

<!--- Comment to force correct slide level --->

## Block 1

- Stuff

## Block 2

- Stuff

```python
# This is inside block two and can't be freed
```

```

Compile:

```bash
pandoc -tbeamer noescape.md -noescape.pdf
```

Output: 
[noescape.pdf](https://github.com/jgm/pandoc/files/1431550/noescape.pdf)



As you can see, the code block is stuck inside the block.

**Comment by henryiii** [comment]
That's awesome, thanks! The Div fences look very useful.

**Comment by henryiii** [comment]
That's odd, to make a headerless block you have to write:

```
::: block
###
Block contents
:::
```

Instead of:
```
::: block
Block contents
:::
```

Which doesn't make a block at all.

**Comment by henryiii** [comment]
Nevermind, I thought that `::: block` was a beamer block, not just a conceptual block. So therefore you could put anything in it, and if that doesn't end (like a beamer block), it ends leaving the conceptual block...

Some docs would be nice so I don't have to find this thread to remember what it's called...

**Comment by mb21** [comment]
@henryiii I think it doesn't matter whether you write `::: block` or `::: whatever`. You just need to put in a div and for that you can use this new syntax, see http://pandoc.org/MANUAL.html#extension-fenced_divs
