### ISSUE TITLE
pandoc to s5 slides isn't working. 

### ISSUE THREAD

**Issue by a59** [jgm/pandoc#2958]
I followed the instructions and made s5 slides using.

`pandoc -t s5 -s test.md -o index.html`

where test.md is the files from the pandoc documentation. This fails to pick up the s5 template automatically and so doesn't produce a slide show.

UPDATE: Never mind. I did missed something in the instructions. Problem solved.

**Comment by jgm** [comment]
Can you post or link to the index.html you get?
I tried it, and the template was included.  You should
see a bunch of stylesheet and javascript links in the
head section of the HTML file.

Note that the default template links to s5 resources
at the relative URL `s5/...`, so you need to unpack
the s5 sources there or the slide show won't work.

**Comment by a59** [comment]
I apologize. I hadn’t read the README close enough. I have it now.

If I could make one suggestion, the README could be clearer about the need to go out and download the required supporting files. Maybe you could provide some links and instructions.

Thanks.

Alan
