### ISSUE TITLE
[request] html5: render void elements' tags as self-closing

### ISSUE THREAD

**Issue by AndreyMZ** [jgm/pandoc#2961]
`pandoc --to=html5 --standalone` generates unclosed `<meta>` tags:
```html
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
```

Could you fix it by making the tags closed?
```html
  <meta charset="utf-8"/>
  <meta name="generator" content="pandoc"/>
```

**Comment by blindmelon** [comment]
This isn't a bug, the tag doesn't need closing in html5, only in xhtml. Closing the tag with "/>" is tolerated in html5, but the existing form is more correct.

Which validator or parser is throwing a wobbly on this? I think that is where the bug report should be filed.

**Comment by AndreyMZ** [comment]
> This isn't a bug, the tag doesn't need closing in html5

Ok, this isn't bug, I was wrong.

> Which validator or parser is throwing a wobbly on this?

I was wrong again. I had a problem with [Confluence Source Editor](https://www.digitalocean.com/community/tutorials/how-to-configure-dns-round-robin-load-balancing-for-high-availability), but now I figured out that [Confluence Storage Format](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html) is not html5 but 'XHTML-based'.

> but the existing form is more correct.

Why? According to the specification (https://www.w3.org/TR/html5/syntax.html#self-closing-start-tag-state) both variants are equally correct.
