### ISSUE TITLE
[Feature Request] Convert images to data URI's

### ISSUE THREAD

**Issue by rbrundritt** [jgm/pandoc#2963]
Love this project. I use it to convert word docs to markdown. One feature that would be nice is if there was an option to have images automatically converted to a data URI and embedded in the generated markdown. The raw images are available in the word doc package, it would likely be trivial to convert them to a data URI and add it to the markup. This would save time having to upload the image to a site later. Although I'm sure not everyone would want this, so having an option flag might make sense for this.

**Comment by jgm** [comment]
You can actually do this already with docx -> HTML, if you
use the `--self-contained` option.

I assumed that, with Markdown's emphasis on readability,
nobody would want data URIs in Markdown source.

+++ Ricky Brundritt [Jun 03 16 16:12 ]:

**Comment by rbrundritt** [comment]
Cool. I'm using a batch file to process word docs quickly. Adding an extra step to convert from docx -> HTML then HMTL -> markdown is fairly easy. Thanks
