### ISSUE TITLE
Pandoc can't locate reference.docx in default data-dir

### ISSUE THREAD

**Issue by asifm** [jgm/pandoc#2965]
My freshly-installed Pandoc (version 1.17.1) on Windows 10 can't locate the data-dir apparently. I've put my reference.docx in the default data directory ( C:\Users\USERNAME\AppData\Roaming\pandoc). Note the pandoc folder was not there after installation — I had to create it. I confirmed the default data directory by running `pandoc --version`.

Here's the error:
![image](https://cloud.githubusercontent.com/assets/3958387/15807967/e7c40f1c-2b38-11e6-8343-94f2f9c91373.png)

[I earlier posted this comment on a closed issue #2187, but I deleted that comment and am opening a new issue here.]

**Comment by nkalvi** [comment]
@asifm You're right. I can reproduce the error on OS X as well.

However, pandoc does use the file ```reference.docx``` placed under the default data dir as long as it is named such. Putting a reference file with different name in the data dir and specifying it in the command line fails with an error. 

As you might have seen, specifying the reference file with complete path or putting it in the current directory works without this error.

**Comment by asifm** [comment]
Thanks for looking into this. Yes, not specifying the reference-docx option makes Pandoc to look at the file (but specifying the option leads to the error). I'm now having a different problem: the file generated using this template is corrupted. Should I open a new issue?

![image](https://cloud.githubusercontent.com/assets/3958387/15811753/46fcc050-2b7a-11e6-9c1a-5bec34b20e00.png)
![image](https://cloud.githubusercontent.com/assets/3958387/15811754/4f36e35e-2b7a-11e6-99fc-f2a92fb1d0cb.png)
![image](https://cloud.githubusercontent.com/assets/3958387/15811755/58d738a0-2b7a-11e6-8cd0-e0a3e9fa11e9.png)

Here is my [reference.docx](https://github.com/jgm/pandoc/files/299730/reference.docx).

And here's the [generated file](https://github.com/jgm/pandoc/files/299733/test.docx).

**Comment by jgm** [comment]
The argument of the `--reference-docx` option should be the PATH to a reference.docx file.  If you put a reference.docx file in your data directory (but not your working directory) and say `--reference-docx reference.docx`, it won't find it.  This is not a bug; it's how it's supposed to work.  The `reference.docx` in the user data directory will shadow the system default when the `--reference-docx` option is *not* used.

As for the other issue:  I didn't see any file corruption issues when I used your reference.docx to generate a file.  And I wasn't sure exactly which styles you say aren't being used.  Could you give a simpler example, with just one thing to look at?

**Comment by asifm** [comment]
Thanks for the clarification about `--reference-docx`.

I checked my documents further and saw that I hadn't formatted everything properly. Now the styles in reference.docx are working. Sorry about the false notice.

But the corruption issue persists. Word presents me with a couple of dialog boxes and then says it was able to repair the file (see the screenshots in the previous post). Since you had no problem, it's clearly an issue with my system. Can't figure out what that could be.

Thanks for your help with this.

**Comment by asifm** [comment]
Since the original issue has been resolved, I'm closing this. I wonder though if the documentation could be more explicit about this (maybe it already is but I missed it somehow).

**Comment by nkalvi** [comment]
@asifm Took a quick look at your generated file (I also got an error when opening it) - most of the styles seem to be present in the generated file, except for _'Source Code'_. Not all styles are carriend over - see http://pandoc.org/README.html:

> The following styles are used by pandoc: [paragraph] Normal, Body Text, First Paragraph, Compact, Title, Subtitle, Author, Date, Abstract, Bibliography, Heading 1, Heading 2, Heading 3, Heading 4, Heading 5, Heading 6, Block Text, Footnote Text, Definition Term, Definition, Caption, Table Caption, Image Caption, Figure, Figure With Caption, TOC Heading; [character] Default Paragraph Font, Body Text Char, Verbatim Char, Footnote Reference, Hyperlink; [table] Normal Table.

**Comment by jgm** [comment]
The SourceCode styles (for highlighted code) are inserted
by highlighting-kate, depending on --highlighting-style.

+++ nkalvi [Jun 06 16 04:35 ]:

**Comment by nkalvi** [comment]
Thanks @jgm - I wasn't aware of it.
