### ISSUE TITLE
Div tags disappear in non-pandoc markdown variants output when native_divs extension is enabled in the reader

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#2966]
Apologies if all this is old hat or intentional behavior.

I've found that when generating non-pandoc markdown formats (markdown_github, markdown_phpextra, markdown_strict) with the `native_divs` extension enabled in the reader all div tags disappear. They reappear when disabling the `native_divs` extension. I suspect that this is a bug, particularly as the same thing does *not* happen with span tags when the `native_spans` extension is enabled. It is certainly not what I would expect.

The files used to generate example output for the various markdown variants, plus HTML for comparison, and example output for all four markdown variants + HTML are attached. The expected output is like the first actual output for `--from markdown+native_divs+native_spans --to markdown` (pandoc). The examples were generated with pandoc 1.17.1 built from master this morning (ISO 2016-06-07). I had the same behavior on an older build four days ago.

##### `pandoc --from markdown+native_divs+native_spans --to markdown divbug-test.md`

````
<u>foo</u>

<div class="div">

\*Div content\*

</div>

<span class="span">Span content</span>
````

##### `pandoc --from markdown-native_divs-native_spans --to markdown divbug-test.md`

````
<u>foo</u>

<div class="div">
\*Div content\*

</div>
<span class="span">Span content</span>
````

##### `pandoc --from markdown+native_divs+native_spans --to markdown_github divbug-test.md`

````
<u>foo</u>

\*Div content\*

<span class="span">Span content</span>
````

##### `pandoc --from markdown-native_divs-native_spans --to markdown_github divbug-test.md`

````
<u>foo</u>

<div class="div">
\*Div content\*

</div>
<span class="span">Span content</span>
````

### Two further unexpected behaviors

Incidentally I noticed two further strange behaviors appearing in the course of discovering and exploring this:

*   With the `native_divs` extension disabled there is no blank line after the div in non-pandoc markdown output. I don't think this affects rendering, but it seems unexpected.

*   Backslash escapes inside div content are not removed in non-pandoc markdown formats, but at least on GitHub the backslashes are visible in the rendered version. If you are viewing this on GitHub consider the rendering of the  `--from markdown-native_divs-native_spans --to markdown_github` output:

    ****

    <u>foo</u>

    <div class="div">
    \*Div content\*

    </div>
    <span class="span">Span content</span>

    ****

Should I open separate issues for these?

[disappearing-div-bug.zip](https://github.com/jgm/pandoc/files/302321/disappearing-div-bug.zip)

**Comment by jgm** [comment]
If you have a native Div, the div tags will be printed around your Markdown content if both the `raw_html` and the `markdown_in_html_blocks` options are set.  In e.g. markdown_github, `markdown_in_html_blocks` is not enabled (because GitHub Markdown doesn't support this).  So you wouldn't want to print the div tags, since if you did that GitHub wouldn't interpret the Markdown inside them.
