### ISSUE TITLE
Support textile bare links

### ISSUE THREAD

**Issue by kayrus** [jgm/pandoc#2969]
It looks like textile bare links are not supported. That would be nice if you can implement that.

Current behavior:

```sh
$ echo 'https://example.com/my_site#title' | pandoc -f textile -t markdown_github - -o -
https://example.com/my\_site\#title
```

Expected behavior:

```sh
$ echo 'https://example.com/my_site#title' | pandoc -f textile -t markdown_github - -o -
<https://example.com/my_site#title>
```

**Comment by jgm** [comment]
Textile does not interpret bare URLs as links.  Try it here, for example: <https://txstyle.org/>.  See also <https://txstyle.org/doc/12/links>, which says

> If you wish to link to a URL and want the URL itself in the text, you can use the following “dollar” shorthand: `"$":http://stefdawson.com/sw`

So pandoc is behaving correctly, as far as I can see, in treating this as plain text.  If you want the URL to be linked, use the dollar shorthand:

    "$":https://example.com/my_site#title
