### ISSUE TITLE
Docx Title Class being Converted into a Table

### ISSUE THREAD

**Issue by mohnjatthews** [jgm/pandoc#2971]
Apologies if this has come up before, after a quick search of the issues I didn't spot anything similar.

Pandoc seems to be converting a docx Title class into a table as a pose to making it a H1.

---

**The exact command line used**: `touch example.md && pandoc -s example.docx -t markdown -o example.md`

**The exact input used**: [example.docx](https://github.com/jgm/pandoc/files/304761/example.docx)

**The output received**: 
`---`
`title: This is an example document`
`---`
` `
`This is an example document`
`===========================`
` `
`This is an example document`
`---------------------------`
` `
`This is an example document.`

**The output you expected instead**:
`# This is an example document`
`## This is an example document`
`### This is an example document`
`This is an example document.`

**Comment by tarleb** [comment]
The output you are seeing contains [*setext headings*](http://spec.commonmark.org/0.25/#setext-heading), you seem to expect [*ATX headings*](http://spec.commonmark.org/0.25/#atx-heading).  Both are correct Markdown headers.  You can force Pandoc to produce ATX headers via the `--atx-headers` command-line option.

**Comment by jkr** [comment]
Actually, I think what you're seeing here is the yaml metadata block (with `---` above and below). It's not a table, though it looks similar. It's where metadata (title, author, etc), that describe the document but aren't *part* of it, goes.

**Comment by jgm** [comment]
You can disable the YAML metadata using `-t markdown-yaml_metadata_block` (then you'll get an old-fashioned pandoc title block instead).  If you don't want any title block, just omit the `-s` from your command.  As @tarleb notes you can also use `--atx-headers` to force atx headers.
