### ISSUE TITLE
Will there be support for MultiMarkdown?

### ISSUE THREAD

**Issue by bulrush15** [jgm/pandoc#2973]
I just installed Pandoc 1.17 for Windows cmd.exe. It supports several versions of Markdown but not MultiMarkdown, which supports nested lists. Is MultiMarkdown support planned for the future? I'm just curious. Thank you! :)

**Comment by mb21** [comment]
This kind of question is a better fit for [pandoc-discuss](https://groups.google.com/forum/#!forum/pandoc-discuss).

Nested lists are supported by default and quite a few features of multimarkdown are supported with `pandoc -f markdown_mmd`, see: http://pandoc.org/README.html#markdown-variants

**Comment by bulrush15** [comment]
The `-f markdown_mmd` is not documented in the Pandoc html file I have either in the Description area at the top of the document or in the documentation of the `-f` switch.
