### ISSUE TITLE
Backlash $ Generated in Markdown

### ISSUE THREAD

**Issue by mike-ward** [jgm/pandoc#2975]
```
► pandoc -t markdown
$20,000
^Z
\$20,000

► pandoc -t markdown_strict
$20,000
^Z
$20,000
```
Is `\$` expected? Is there a way to suppress the `\$` in `-t markdown`

**Comment by mike-ward** [comment]
Also
```
► pandoc -t markdown_strict+tex_math_dollars
$20,000
^Z
\$20,000
```

**Comment by Jmuccigr** [comment]
In this context, I was a little surprised to see that the `escaped_line_breaks` extension is on by default in the markdown writer. (And I see this has been raised before: #2126, #902, #2109.)

**Comment by jgm** [comment]
`$` is escaped because it has a special meaning given the tex math extension (which you can disable).

    pandoc -t markdown-tex_math_dollars

The `escaped_line_breaks` extension is on by default in pandoc markdown, both reading and writing.  You can easily disable it though.
