### ISSUE TITLE
Syntax-Highlight lat pandoc go nut in special cases

### ISSUE THREAD

**Issue by amazing-clemo** [jgm/pandoc#2977]
Hi,
I'm using pandoc `1.17.1-2` (also had this bug in earlier versions, for instance `1.17.0.2-1`) to render assigments in university.

I found some edge-cases of syntax-highlighting where pandoc **eats ALL my RAM** (we are talking about 16Gig and 20 Gig of swap) and a whole CPU. In some circumstances causes my operating-system to crash &rarr; but most of the time the OS kills the process aufter some time.

I was able to narro it down to following code:
<pre>
```scheme
SW_Etage_2_Sued(config-if-range)#do show port-se
Secure Port MaxSecureAddr CurrentAddr SecurityViolation Security Action
               (Count)       (Count)        (Count)
--------------------------------------------------------------------
        Fa0/1        1          0                 0         Shutdown
        Fa0/2        1          0                 0         Shutdown
        Fa0/3        1          0                 0         Shutdown
        Fa0/4        1          0                 0         Shutdown
        Fa0/5        1          0                 0         Shutdown
        Fa0/6        1          0                 0         Shutdown
        Fa0/7        1          0                 0         Shutdown
        Fa0/8        1          0                 0         Shutdown
        Fa0/9        1          0                 0         Shutdown
       Fa0/10        1          0                 0         Shutdown
       Fa0/11        1          0                 0         Shutdown
       Fa0/12        1          0                 0         Shutdown
       Fa0/13        1          0                 0         Shutdown
       Fa0/14        1          0                 0         Shutdown
       Fa0/15        1          0                 0         Shutdown
       Fa0/16        1          0                 0         Shutdown
       Fa0/17        1          0                 0         Shutdown
       Fa0/18        1          0                 0         Shutdown
       Fa0/19        1          0                 0         Shutdown
----------------------------------------------------------------------
```
</pre>

I'm a fanboy of the "scheme" highlighting because it fits pretty well for cisco. I tried to render it with `find . -type f -iname "*.md" | sort | xargs cat|pandoc --toc -N  --normalize -S --highlight-style tango -o  "$(basename $(pwd)).pdf"` (this is my default for rendering my assessments). But the bug also occurs if I try the minimal command `pandoc test.md -o test.pdf`. (Note: `test.md` contains *only* the given code fragment!)

My operating system is `Linux 3.19.0-32-generic #37~14.04.1-Ubuntu SMP x86_64 GNU/Linux` with "Linux Mint 17.3 Rosa". But this bug seems not related to a certain distro/version since a friend of mine originally discovered it (running Elementary OS and pandoc form the package-manager).

**Comment by jgm** [comment]
Moving to jgm/highlighting-kate#89 since this is really an issue with that library.
