### ISSUE TITLE
Textile reader skips emphasis _, if the text is in the brackets ()

### ISSUE THREAD

**Issue by dbojan** [jgm/pandoc#2984]
Textile reader skips emphasis _, if the text is in the brackets ()

example:
textile source:
```
_line 1_
_(line 2)_

```
pandoc HTML output:
```
<p><em>line 1</em><br />
<em><span class="2 line"></span></em></p>
```

expected HTML output:
```
<p><em>line 1</em><br />
<em>(line 2)</em></p>
```
Line 2 does not show as text when viewing in browser.
Thank you.

**Comment by jgm** [comment]
There seems to be some difference of opinion between textile variants.  [Here](https://txstyle.org/doc/22/css-classes) it says that attribute modifiers can modify phrase markers like `_`, so we can have things like `_(#special-phrase)emphasized phrase_` (with an id) or `_(class)emphasized phrase_` (with a class).

**Comment by jgm** [comment]
Ah, I see:  if there's a space after the closing `)` , it does not interpret this as attributes.  This should be relatively easy to fix.

```
_(class)with class_

_(regular parens) no class_
```
