### ISSUE TITLE
List item followed by code block behaves different in CommonMark vs. Pandoc

### ISSUE THREAD

**Issue by mike-ward** [jgm/pandoc#2987]
A list item followed by a code block behaves differently in Pandoc (any Markdown flavor) and CommonMark 

http://spec.commonmark.org/dingus/?text=1.%20%20item%0A%0A%0A%20%20%20%20code%20block

http://pandoc.org/try/?text=1.++item%0A%0A%0A++++code+block&from=markdown&to=html

Is this difference expected?

**Comment by mb21** [comment]
I think ultimately the goal is to change pandoc's markdown to comply with commonmark. In the meantime, you can at least use `-f commonmark`, at the expense of all pandoc markdown extensions.

**Comment by jgm** [comment]
Yes, the difference is expected.  In CommonMark (current spec), two blank lines terminate a list.  This is an innovation which is found in no other Markdown implementations, and it may be removed from the final CommonMark spec.
