### ISSUE TITLE
WriterOptions defaults should not rewrite email links

### ISSUE THREAD

**Issue by chris-kahn** [jgm/pandoc#2988]
The default behaviour of `WriterOptions` is to set email obfuscation to JavaScript obfuscation. I believe this is really bad practice for two reasons:

- Should Pandoc really rewrite user content as a default behaviour? I strongly believe that it shouldn't.
- Inserting JavaScript into what was a plain HTML page. This is even more egregious. Pandoc shouldn't insert scripts into a page unless the user asks for it.

**Comment by jgm** [comment]
I agree.  This was only the default because, when I first
wrote this around 2005, email obfuscation was a best
practice.

I think I'll change the default.

+++ Chris [Jun 20 16 07:11 ]:
