### ISSUE TITLE
email obfuscation does not properly rebuild the anchor tag

### ISSUE THREAD

**Issue by chris-kahn** [jgm/pandoc#2989]
When the default e-mail objuscation rewrites anchor tags, it doesn't seem to copy attributes from the original anchor. So if I had an anchor like:

```
<a class="button blue size-32" href="somewhere">lonely swedish</a>
```

It seems that Pandoc rewrites it to a javascript that inserts:

```
    <a class="email" href="somewhere">lonely swedish</a>
```

And my extra class names are lost.

**Comment by jgm** [comment]
Please give exact instructions for how to reproduce this, otherwise I have to guess what you are doing.
A simple conversion markdown -> HTML does not have the result you state:
```
% pandoc
<a class="button blue size-32" href="somewhere">lonely swedish</a>
^D
<p><a class="button blue size-32" href="somewhere">lonely swedish</a></p>
```
Also, what version of pandoc?

**Comment by chris-kahn** [comment]
Oops, my mistake. I was probably half asleep when I wrote it.

It happens with mailto/email obfuscation:

    <a class="button blue" href="mailto:test@example.org">test@example.org</a>

I'm using it via Hakyll, I'll check the exact version when I get back home.

**Comment by jgm** [comment]
```
% pandoc
<a class="button blue" href="mailto:test@example.org">test@example.org</a>
^D
<p><a class="button blue" href="mailto:test@example.org">test@example.org</a></p>
```

**Comment by chris-kahn** [comment]
echo '<a class="button blue" href="mailto:test@example.org">test@example.org</a>' > test.html
    pandoc --email-obfuscation=javascript test.html -o test2.html
    cat test2.html 

    <script type="text/javascript">
    
    </script>    <noscript>&#116;&#x65;&#x73;&#116;&#32;&#x61;&#116;&#32;&#x65;&#120;&#x61;&#x6d;&#112;&#108;&#x65;&#32;&#100;&#x6f;&#116;&#32;&#x6f;&#114;&#x67;</noscript>

Notice in the `document.write(...)` section it only writes `class="email"`

**Comment by chris-kahn** [comment]
localhost ~> pandoc --version
    pandoc 1.17.1

**Comment by jgm** [comment]
OK, it was helpful to be told you were using pandoc to convert from HTML to HTML.  (But why?)

**Comment by chris-kahn** [comment]
I'm using Hakyll and it runs all your templates through pandoc to create the output HTML. Hakyll templates can be any format that pandoc supports including HTML, and the output is HTML.

**Comment by jgm** [comment]
OK.  Well, pandoc isn't designed to do lossless HTML -> HTML
conversion (see the beginning of the README).  However, in
this case it would be possible to include the class.  This
just requires a bit of adjustment to the JavaScript
obfuscation code.

+++ Chris [Jun 20 16 11:38 ]:
