### ISSUE TITLE
pandoc not allowing me to deploy interface graph

### ISSUE THREAD

**Issue by chrisclarkson1** [jgm/pandoc#2990]
with a github R package (https://github.com/cytoscape/r-cytoscape.js/tree/master) I am trying to deploy an interactive graph to the web.
Code:
_b<-createCytoscapeJsNetwork(nodeData = nodes, edgeData = edge)
rcytoscapejs(b$nodes, b$edges)_

Subsequently I click _Publish_ in Rstudio.
However I keep receiving the following error: 
pandoc: Could not fetch //maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/../fonts/fontawesome-webfont.eot?v=4.3.0
//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/../fonts/fontawesome-webfont.eot: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67

I have downloaded the latest version of pandoc and installed "pander"- the interface package between R and Pandoc yet I keep getting the same error.
Googling the error generally reveals a quick-fix solution of inserting the following somewhere:

"_specifying self_contained: false_"

I'm not sure where though?? Also given that it is a temporary solution can someone tell me how to permanently rectify the problem?

**Comment by jgm** [comment]
This is an RStudio or pander issue and you should report it to them.  If they determine there's a bug in pandoc, they can submit something here.
