### ISSUE TITLE
org-reader empty src block results in pandoc: Prelude.minimum: empty list

### ISSUE THREAD

**Issue by ag91** [jgm/pandoc#2991]
Hi there,

the latest changes to the org-reader are so cool! Thanks!
I think that a bug sneaked in:
when you create an org file with an empty src block, such as

```
* hi
#+BEGIN_SRC sh

#+END_SRC
```

you get from pandoc
```
$ pandoc -o pdf my.org
pandoc: Prelude.minimum: empty list
```
Not having empty blocks in the file solves the problem though.
I'm using pandoc 1.17.1
Compiled with texmath 0.8.6.3, highlighting-kate 0.6.2.
Thanks however!

**Comment by jgm** [comment]
@tarleb - this might be a good time to check over the
reader for use of partial functions (head, minimum, etc.).
I'd replace these with total functions to avoid these
surprises.

+++ ag91 [Jun 21 16 03:03 ]:

**Comment by tarleb** [comment]
Yeah, that was stupid. Forgot about `minimum` being a partial function. In case you need empty code blocks: those without an empty line (i.e. with no line at all) work okay.

**Comment by ag91** [comment]
Thanks! I did not try that, good to know.
Thanks again for your work!!

**Comment by tarleb** [comment]
Thank you for the bug report. It's great to hear that the new additions are useful. :smile:
