### ISSUE TITLE
cannot convert multi-lines text in a table from Textile to Markdown(GitHub) correctly

### ISSUE THREAD

**Issue by landall** [jgm/pandoc#2993]
|_. Function name|_. Description|
|abc|Return
ABC|
|@help()@|Display the help window.|
|@destroy()@|*Destroy your computer!*|

This will lead to convert a broken table. Markdown don't  support text with CRLN in a table cell.

**Comment by jgm** [comment]
Yes, I suppose the easiest fix would be to replace LineBreak with raw HTML `<br />` when we're rendering a pipe table cell.
