### ISSUE TITLE
Nesting of quotes and italic gives strange results

### ISSUE THREAD

**Issue by crystalfp** [jgm/pandoc#2996]
The following example, if run with `pandoc -t latex` gives wrong results (i.e. the `*` are ignored and passed to output, see below). The output format is only for convenience, the problem happens also with html and docx writers.

```
1: *“one* two *three.”*

2: *"one* two *three."*

3: “*one* two *three.*”

4: "*one* two *three.*"
```

The result is:
```
1: *``one* two \emph{three.''}

2: *``one* two *three.``*

3: ``\emph{one} two \emph{three.}''

4: ``\emph{one} two \emph{three.}''
```
In (1) the first pair of `*` is not converted, in (2) both are not converted and the second quote is converted wrongly, should be `''`. Instead (3) and (4) are converted correctly. Seems proper nesting of quotes and `*` is required.

Note that cmark converts all examples correctly.

Thanks for looking!
mario

P.S.: pandoc 1.17.1 on Win 7 64 bits. The example file should be UTF-8

**Comment by jgm** [comment]
Yes, proper nesting is required.  Pandoc actually parses the quoted part into a Quoted element (just as it parses the emphasized part into an Emph).  Quoted can be rendered differently in different output formats (e.g. in DocBook a special element is used).

So this is not really a bug in my opinion.

cmark does have a better approach to emph, strong, and smart quotes, and eventually I hope to integrate this into pandoc, but for now I'll close this.
