### ISSUE TITLE
knitr/pandoc: Can't change the latex template in markdown YAML header

### ISSUE THREAD

**Issue by friendly** [jgm/pandoc#2997]
[Env: R Studio, pandoc 1.15.2]
This problem is described in detail at http://stackoverflow.com/questions/37978637/knitr-pandoc-article-template-supporting-keywords-and-linespacing/, but briefly, if I try to substitute my own latex template, via a `template:` line in the YAML header, or even `--template "default-1.15.2.tex"` in the pandoc call, an error is generated in the latex compile.

    output:
      pdf_document:
        fig_caption: yes
        keep_tex: yes
        number_sections: yes
        template: "default-1.15.2.tex"

This happens even if `default-1.15.2.tex` is an **exact copy** of the template used by the `rmarkdown` package, so I suspect this may be pandoc problem.

Is there some way I can track this down further? I think I am unable to upgrade to a later version of pandoc, because R Studio and rmarkdown are set up to use their own copy of pandoc.exe.

**Comment by jgm** [comment]
This seems to be a knitr or RStudio issue rather than a pandoc issue. Please report the issue there, and if their developers determine that there's a bug in pandoc, they can report that here.
