### ISSUE TITLE
docx: Image/Table numbering and cross-references

### ISSUE THREAD

**Issue by michelk** [jgm/pandoc#3000]
- The docx-writer should have a default numbering scheme (eg. Figure 1: My figure caption or Table 1: My table caption)
- Cross-references are currently not supported

A sample tex-source part is listed underneath:

``` latex
As illustrated in figure \ref{fig:myfig},  and listed in table
\ref{tab:mytab}, ...

\begin{figure}
        \centering
        \includegraphics{blub.png}
        \caption{My figure}
        \label{fig:myfig}
\end{figure}

\begin{table}
        \caption{My table}
        \label{tab:mytab}
        \begin{tabular}
                Name & Value \\
                \hline
                Uno & 1 \\
                Due & 2 \\
        \end{tabular}
\end{table}

```

**Comment by mb21** [comment]
I think it's safe to close this in favour of https://github.com/jgm/pandoc/issues/813

(since we're unlikely to implement a solutiont that _only_ works for TeX -> docx...)
