### ISSUE TITLE
'NEXT LINE (NEL)'  character and conversion to LaTeX

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#3002]
I have recently tried to convert one rather old text document into PDF using Pandoc. The document contains ['NEXT LINE (NEL)' (U+0085)](http://www.fileformat.info/info/unicode/char/85/index.htm) characters. pdfLaTeX did not like it and even with XeLaTeX it was not treated as EOL. ~~In the end I edited the default LaTeX template and added `\catcode"85=5` to get the desired result.~~

I am wondering, if either a conversion should be done in Pandoc so that it is treated as EOL or ~~the `\catcode"85=5` (or similarly effective)~~ some magic should be added into LaTeX default template.

**Comment by wilx** [comment]
I have settled for `\newunicodechar{^^^^0085}{\\}` to get a new line in the conversion result, which seems like what it was intended as.

**Comment by jgm** [comment]
I like to avoid unnecessary complexity in the templates, so
I'm disinclined to add something to deal with this case,
which is going to be extremely uncommon.

**Comment by wilx** [comment]
[The \[NEL\] Newline Character (W3C)](https://www.w3.org/TR/newline) page suggests it should be treated the same as more common EOL characters.

**Comment by wilx** [comment]
I have created a patch that handles NEL the same way as NL in Markdown input. See #3003.

**Comment by wilx** [comment]
I was actually completely wrong. The encoding was not ISO-8859-1 or -15 as I thought but CP1252, where the characters is ellipsis.

**Comment by jgm** [comment]
Makes sense.  I have never seen NEL in actual use!

+++ Václav Haisman [Jun 27 16 12:17 ]:
