### ISSUE TITLE
Pass raw latex to html when converting from Markdown using --mathjax

### ISSUE THREAD

**Issue by Cydox** [jgm/pandoc#3006]
When converting from Markdown to html using the `--mathjax` option I think raw latex should be passed through. I know that there are workarounds like
```markdown
$$
\begin{aligned}
<equation>
\end{aligned}
$$
```

However this does not work when you want to export the same file to latex without change and want the equations to be numbered.

**Comment by jgm** [comment]
The aligned environment is passed through with --mathjax
in the current dev code (and will be in the next release).
(Similarly the other supported math environments.)

+++ Cydox [Jun 29 16 18:16 ]:

**Comment by jgm** [comment]
See #2758 and commit ba7868765acae0071f684797771d83f9cc31b402
