### ISSUE TITLE
Multi-line tables generate incorrect LaTeX

### ISSUE THREAD

**Issue by jekstrand** [jgm/pandoc#3013]
I'm working on a document with Pandoc and have included the following table (of floating-point encodings if you're interested):

```
------------------------------------------------
 Bits        Sign bit     Mantissa     Exponent
----------- -----------  ----------   ----------
 64              Y          52           11

 32              Y          23            8

 16              Y          10            5

 11              N           6            5

 10              N           5            5
-------------------------------------------------
```

When I generate HTML, it works fine but when I generate a PDF, it has an extra line under the word "Exponent"  If I add one more hyphen under "Exponent" the problem goes away.  Perhaps Pandoc is getting the trailing newline confused somehow?

I'm using Pandoc 1.16.0.2 from the Fedora packages.

**Comment by jgm** [comment]
I can't reproduce this with 1.17.1.  Try upgrading;
we improved LaTeX tables in 1.17.1.

+++ Jason Ekstrand [Jul 04 16 21:19 ]:

**Comment by jekstrand** [comment]
Yes, pandoc 1.17.1 fixes this issue.
