### ISSUE TITLE
org inline code block equal bug

### ISSUE THREAD

**Issue by ag91** [jgm/pandoc#3016]
Hello,

there is a minor bug in the parsing of inline src blocks for the org reader: in org mode only equal signs adjacent to the code are considered markers, while an = after a space is still part of the code fragment.

A test is:

```
* Test
 =is_subst = True=
```

we should get in verbatim:
is_subst = True

while we get:

is_subst True=

where only is_subst is in verbatim.
I am using pandoc 1.17.1
Compiled with texmath 0.8.6.3, highlighting-kate 0.6.2.

However thanks for the awesome piece of software (I am so pleased every time I generate from org in emacs through Pandoc!!)

**Comment by tarleb** [comment]
Thank you @ag91, both for the bug report and the kind words :blush:

The verbatim text issue should be fixed by #3019. Happy pandocing!
