### ISSUE TITLE
question: how beamer templates loads hyperref?

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#3022]
Hi,

I'm trying to find where is loaded the hyperref package in beamer template. But `pandoc -D beamer | grep hyperref` does not give me any `\usepackage{hyperref}` or similiar. Related to this [question](http://tex.stackexchange.com/questions/319253/how-to-underline-links-with-pandoc/319463?noredirect=1#comment780578_319463) in Stackoverflow.

Thanks,

**Comment by jgm** [comment]
I believe the beamer documentclass loads hyperref itself, so we don't do it in the template (indeed, it would cause problems if we did).

**Comment by somenxavier** [comment]
Thanks.
