### ISSUE TITLE
Superscript in latex block

### ISSUE THREAD

**Issue by qsantos** [jgm/pandoc#3026]
The tikzpicture environments are not delimited by `$$` or `\[`.  This means pandoc need to detect those LaTeX blocks. This usually works pretty well:

```bash
$ echo -E '\begin{tikzpicture}\begin{axis}[x unit=m]\addplot{x};\end{axis}\end{tikzpicture}' | pandoc -t json | python3 -m json.tool
```

```json
[
    {
        "unMeta": {}
    },
    [
        {
            "t": "RawBlock",
            "c": [
                "latex",
                "\\begin{tikzpicture}\\begin{axis}[x unit=m]\\addplot{x};\\end{axis}\\end{tikzpicture}"
            ]
        }
    ]
]

```

Except when using the superscript symbol in some places (`x unit` option of axis environment):

```bash
$ echo -E '\begin{tikzpicture}\begin{axis}[x unit=m^2]\addplot{x};\end{axis}\end{tikzpicture}' | pandoc -t json| python3 -m json.tool
```

```json
[
    {
        "unMeta": {}
    },
    [
        {
            "t": "Para",
            "c": [
                {
                    "t": "Str",
                    "c": "\\begin{tikzpicture}\\begin{axis}[x"
                },
                {
                    "t": "Space",
                    "c": []
                },
                {
                    "t": "Str",
                    "c": "unit=m^2]"
                },
                {
                    "t": "RawInline",
                    "c": [
                        "tex",
                        "\\addplot{x}"
                    ]
                },
                {
                    "t": "Str",
                    "c": ";\\end{axis}\\end{tikzpicture}"
                }
            ]
        }
    ]
]
```

**Remark:** I can actually sometimes fix the bug by using LaTeX block delimiters, but I lose the ability to use PGF to draw graphs. 

This is the smallest example I could come up with. The issue does not arise when using the supercript symbol elsewhere (e.g. `\addplot{x^2}` is fine). I am not familiar enough with Haskell to locate the reason for this behavior.

**Temorary fix:** for now, I am escaping the super script symbol (`\^`) and unescaping through a pandoc filter; however, this is really a hack and may interfere with genuine escaping

**Comment by jgm** [comment]
The `^` symbol is usually not allowed in LaTeX outside of
math environments.  Of course, environments in LaTeX can
redefine things so that it works, and that is apparently
what is happening with tikz.  But pandoc is failing because
the LaTeX parser doesn't expect to see `^` outside of math
mode.

Can you explicitly put this in math mode?

    [x unit=$m^2$]

or does that break?

+++ Quentin Santos [Jul 18 16 00:15 ]:

**Comment by qsantos** [comment]
LaTeX libraries are very inconsistent with modes delimitations; it seems that the value of `x unit` is already being put within a LaTeX environment.

> [x unit=$m^2$]

This raises the following error when trying to compile:

> ! Missing } inserted.

Bypassing Pandoc, the version without the dollar symbols works fine though, including the `²`.

**Comment by qsantos** [comment]
Works great! Thanks!
