### ISSUE TITLE
Table generation fails when header cell contains an image

### ISSUE THREAD

**Issue by gbraad** [jgm/pandoc#3030]
I usually sign the documents I have with a 'stamp' at the bottom, which is composed by a table in markdown format as given:

```
| [!["Gerard Braad"](http://gravatar.com/avatar/e466994eea3c2a1672564e45aca844d0.png?s=60)](http://gbraad.nl "Gerard Braad <me@gbraad.nl>") |
|---|
| [@gbraad](https://twitter.com/gbraad) |
```

This will be rendered as follows on both GitHub and GitLab:

| [!["Gerard Braad"](http://gravatar.com/avatar/e466994eea3c2a1672564e45aca844d0.png?s=60)](http://gbraad.nl "Gerard Braad <me@gbraad.nl>") |
|---|
| [@gbraad](https://twitter.com/gbraad) |

However, when using Pandoc, the result is formatted as:

![sign](https://cloud.githubusercontent.com/assets/1894/16937345/b982476a-4da0-11e6-9afd-b8f239df1249.png)

This is probably related to the fact that the header cell uses an image instead of regular text.

**Comment by jgm** [comment]
I get this HTML using pandoc to convert your input:
``` html
<table>
<thead>
<tr class="header">
<th><a href="http://gbraad.nl" title="Gerard Braad &lt;me@gbraad.nl&gt;"><img src="http://gravatar.com/avatar/e466994eea3c2a1672564e45aca844d0.png?s=60" alt="&quot;Gerard Braad&quot;" /></a></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation">[@gbraad]</span>(https://twitter.com/gbraad)</td>
</tr>
</tbody>
</table>
```
Do you get something different?
What version of pandoc are you using?

This should give you what you want (a table with an image as header), except for one thing: the link on `@gbraad`.  That is because it is interpreting `[@graad]` as a citation.  You can disable citations by doing `pandoc -f markdown-citations`, or you can backslash-escape the `@`.

**Comment by gbraad** [comment]
I am sorry I forgot to mention the version and how the generation happens. I assume now it is a version issue... The version is currently distro provided (Ubuntu Trusty): pandoc `1.12.2.1` (way too old compared to `1.17.2`).

The current output is:
```
<p>| <a href="http://gbraad.nl" title="Gerard Braad &lt;me@gbraad.nl&gt;"><embed src="http://gravatar.com/avatar/e466994eea3c2a1672564e45aca844d0.png?s=60" /></a> | |---| | <span class="citation" data-cites="gbraad">[@gbraad]</span>(https://twitter.com/gbraad) |</p>
```

and I use:

```
pandoc -t html5 -o public/index.html ./md/index.md
```

to generate this. 

Note: Will update the image and try this using a newer version of the Pandoc.

**Comment by gbraad** [comment]
Changed the instruction for the installation to:
```
curl -sSl --location https://github.com/jgm/pandoc/releases/download/1.17.2/pandoc-1.17.2-1-amd64.deb -o/tmp/pandoc.deb &&
    dpkg -i /tmp/pandoc.deb &&
    rm -f /tmp/pandoc.deb
```
and retried:

```
<table>
<thead>
<tr class="header">
<th><a href="http://gbraad.nl" title="Gerard Braad &lt;me@gbraad.nl&gt;"><img src="http://gravatar.com/avatar/e466994eea3c2a1672564e45aca844d0.png?s=60" alt="&quot;Gerard Braad&quot;" /></a></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="gbraad">[@gbraad]</span>(https://twitter.com/gbraad)</td>
</tr>
</tbody>
</table>
```
is the output, as expected. Closing.
