### ISSUE TITLE
html class for rst admonition

### ISSUE THREAD

**Issue by kakawait** [jgm/pandoc#3031]
I want to know if it possible to add some specific html class for _rst_ admonitions http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions like

```
.. note::

    This is a note
```

Actually _pandoc_ will convert it to a `<blockquote>` that would not help to theme it differently from _quotes_ and even more for theming per admonitions (_note_, _attention_, _error_, etc)

**Comment by jgm** [comment]
Now that we have native Divs, it would make more sense
to parse admonitions into Divs with specific classes,
instead of this block quote hack.

That would give users much more flexibility.

+++ Thibaud Lepretre [Jul 19 16 08:06 ]:

**Comment by kakawait** [comment]
Yeah if _admonition_ like 

```
.. note::

    This is a note
```

is transformed to 

```
<div class="admonition note">
  <p class="adminition-title">Note</p>
  <p>This is a note</p>
</div>
```

and 

```
.. error:: my custom title

    This is an error
```

to

```
<div class="admonition error">
  <p class="adminition-title">my custom title</p>
  <p>This is an error</p>
</div>
```

it would be perfect
