### ISSUE TITLE
Change README file to README.md (better displayed on GitHub)

### ISSUE THREAD

**Issue by Naereen** [jgm/pandoc#3032]
Hi,

First, thanks for this wonderful project. :clap:

Now, could I suggest that you add a .md extension to the root README file?
It is not displayed nicely on the GitHub homepage for the project.

Regards.

**Comment by vyp** [comment]
#3028

**Comment by blindmelon** [comment]
and #2361, #2239, #2431, #2875, #2905, #688 - did I miss any?
I had to laugh a bit at this appearing so soon after the last one ;).

**Comment by Naereen** [comment]
Sorry about the doubled (10-bled?) PR.

**Comment by jgm** [comment]
Fixed by #3033

**Comment by Naereen** [comment]
Thanks, it looks great.
