### ISSUE TITLE
++text++ -> <ins>text</ins>, for symmetry 

### ISSUE THREAD

**Issue by keiyakins** [jgm/pandoc#3035]
Currently, you can mark text as deleted in pandoc markdown with `~~text~~`. There's no similar way to mark it as inserted. This'd be a nice enhancement, useful for any time you're communicating changes back and forth.

**Comment by mb21** [comment]
see also https://github.com/jgm/pandoc/issues/1560

**Comment by mb21** [comment]
Duplicate of #1560
