### ISSUE TITLE
Installation fails or not at launch of Windows Installer in CMD - Windows XP

### ISSUE THREAD

**Issue by Terry-Panda** [jgm/pandoc#3039]
Hello,

// I'm a new Pandoc user //

In Windows XP-SP2 using Windows Installer 3.1.4000.2435, msiexec cannot run 
properly in the CMD prompt with at least 5 Pandoc packages, whereas a direct 
double-click in Explorer on respectively the 8 MSI packages listed below works 
quite well. 

Consequently, some Pandoc packages cannot be installed to a different directory by 
setting the APPLICATIONFOLDER parameter or using additional parameters.

Here are some test results with different Pandoc MSI packages I have downloaded. 
The MSI syntax I used is simple and exactly the same for every package : 

  msiexec /i <pandoc-version>.msi

At launch, Windows Installer displays - or not - that error message box (
translated from French):

 "Cannot open this installation package. Please verify that 
  it exists and that you are allowed to access it or verify 
  that this windows installer package is valid."

List of packages tested:
- pandoc-1.17.2-windows.msi  Jul 17, 2016  msiexec in CMD: ERROR
- pandoc-1.14.1.msi          Jun 30, 2015  msiexec in CMD: ERROR
- pandoc-1.13.2.msi          Dec 20, 2014  msiexec in CMD: ERROR
- pandoc-1.12.4.2.msi        May 14, 2014  msiexec in CMD: ERROR
- pandoc-1.12.4.msi          May  8, 2014  msiexec in CMD: ERROR
- pandoc-1.12.3.msi          Jan 10, 2014  msiexec in CMD: OK
- pandoc-1.12.2.1.msi        Dec  8, 2013  msiexec in CMD: OK
- pandoc-1.12.msi            Dec  8, 2013  msiexec in CMD: OK

At the moment, I haven not yet installed any package, because I would like to 
customize the installation the latest release if possible. May be that first level 
issue will not look like too much outdated...

Thank you in advance for reply,
Terry

**Comment by Terry-Panda** [comment]
Correction:
The MSI syntax I used is simple and exactly the same for every package :
msiexec /i pandoc-version.msi

**Comment by jgm** [comment]
@nkalvi may be able to help.

+++ Terry-Panda [Jul 24 16 05:06 ]:

**Comment by nkalvi** [comment]
@Terry-Panda Recent Pandoc installers require more recent versions of MSIEXEC, though the version required in the package is 3.01 (`InstallerVersion="301"`). Anyway, I'll look into this and get back to you by the end of this week.

**Comment by Terry-Panda** [comment]
**@nkalvi** Thank you for short reply today. I'll be waiting for more information. At the moment, I am afraid I won't be able to upgrade to a more recent version of Windows Installer (and Windows system). The installed MSIEXEC version is sometimes called 3.1 (v2). Double-clicking on the latest Pandoc releases with it seems to work, although I did not continue. In opposite, the CMD command line fails at the very beginning.

Sincerely.

**Comment by nkalvi** [comment]
@Terry-Panda I want to replicate your system - is it 32bit?

**Comment by Terry-Panda** [comment]
**@nkalvi** Yes, my system is 32-bit.

**Comment by nkalvi** [comment]
@Terry-Panda I'm starting to test with Windows XP 32-bit SP2 (US English) with Windows Installer 3.1 v2 from https://support.microsoft.com/en-us/kb/893803. A simple run with `msiexec /i pandoc-version.msi` doesn't result in any errors (completes as expected with default settings):

<img width="961" alt="screen shot 2016-07-30 at 10 03 49 am" src="https://cloud.githubusercontent.com/assets/2199312/17271010/f928a0da-563d-11e6-81cf-52129bbbf051.png">

However, the installer seems to ignore `APPLICATIONFOLDER` specified on command-line. I'll look into this.

BTW, were you using the `/q` option also when it fails on your system?

**Comment by Terry-Panda** [comment]
**@nkalvi** Thank you again for help. Sorry, I did not reply in time yesterday but I ran a lot of tests.

First of all, I must apologize. For many weeks I've had a system bug with a partially corrupt NTFS file system but I realized it only yesterday thank to your message. I reformatted the disk partition where the Pandoc packages were stored. This explains why the MSI files could not be read by msiexec correctly.
Secondly, last week I may have typed or copied an incorrect filename for packages having the additional `-windows` string.

To report briefly about my tests:
- All the installation tests were successfully run on two distinct platforms with Window XP 32-bit SP1 and Window XP 32-bit SP2. Most were just launched and stopped, so I could focus my tests only on the last Pandoc release.
- The installed `Windows Installer 3.1.4000.2435` or `3.1 (v2)` works quite well, even when combining three options on the command line: `/i`, `/qn`, and `APPLICATIONFOLDER`. Note: The `/qn` must be written _at end of the command line_ to make msiexec run in silent mode, otherwise the command fails.
- Running the command lines through a batch file (.bat) is convenient to get the error level at end of Pandoc installation. A successful return code is 0.
- Uninstalling Pandoc can be processed either with the command line or by double-clicking the pandoc-version.msi itself in Explorer.
- Every full installation test could be traced with an old freeware called InCtrl5, which is no longer developped nor supported.

Pandoc version                | Date          | Double click | CMD line | APPLICATIONFOLDER
----------------------------  | ------------- | ------------ | -------- | -----------------
pandoc-1.17.2-windows.msi     | Jul 17, 2016  | OK           | OK       | OK
pandoc-1.14.1-windows.msi     | Jun 30, 2015  | OK           | OK       | OK
pandoc-1.13.2-windows.msi     | Dec 20, 2014  | OK           | OK       | not tested
pandoc-1.12.4.2-1-windows.msi | May 14, 2014  | OK           | OK       | not tested
pandoc-1.12.4-windows.msi     | May  8, 2014  | OK           | OK       | not tested
pandoc-1.12.3.msi             | Jan 10, 2014  | OK           | OK       | not tested
pandoc-1.12.2.1.msi           | Dec  8, 2013  | OK           | OK       | not tested
pandoc-1.12.msi               | Sep 15, 2013  | OK           | OK       | not tested

Here is a sample of CMD batch file with some comments.
```
@echo off

rem pandoc-1.17.2-windows.bat

rem Go to the Tools folder where the Pandoc package is temporarily 
rem stored. For instance:

cd F:\Tools

rem Three tests using or not using the APPLICATIONFOLDER parameter 
rem and the /qn option for the quiet mode installation.
rem 
rem TEST 1: With the command line below, Pandoc is installed for a 
rem single user in the Windows default folder:
rem 
rem msiexec /i pandoc-1.17.2-windows.msi
rem 
rem ok... Pandoc installed in 
rem C:\Documents and Settings\<user>\Local Settings\Application Data\Pandoc\
rem 
rem TEST 2: With the command line below, Pandoc is installed for a 
rem single user to the folder assigned with APPLICATIONFOLDER:
rem 
rem msiexec /i pandoc-1.17.2-windows.msi APPLICATIONFOLDER="C:\tools\Pandoc"
rem 
rem ok... Pandoc installed in C:\tools\Pandoc
rem 
rem TEST 3: With the command line below, Pandoc is installed with the 
rem option /qn - with no User Interface - for a single user to the folder 
rem assigned with APPLICATIONFOLDER. Write the /qn at end of command line.
rem Once the command is launched, wait until the process is stopped.
rem 
rem msiexec /i pandoc-1.17.2-windows.msi APPLICATIONFOLDER="C:\tools\Pandoc" /qn
rem 
rem ok... Pandoc installed in C:\tools\Pandoc

msiexec /i pandoc-1.17.2-windows.msi APPLICATIONFOLDER="C:\tools\Pandoc"

echo Returncode: %ERRORLEVEL%

pause

rem EOF
```

Finally with Windows XP 32-bit SP2, I successfully tested the compatibility of Pandoc 1.17.2 with `UWIN win32.i386 32-bit`, a nice Unix-like environment for Windows. I am afraid that AT&T software is no longer available unless its new repository is located at https://github.com/att/ast.

Please feel free to close this thread at any time. On my side, I still will keep my environment alive for further tests if needed. And especially to learn more about Pandoc's splendid features.

Sincerely.
