### ISSUE TITLE
Math operator artifacts when converting to docx

### ISSUE THREAD

**Issue by jrgcmu** [jgm/pandoc#3040]
Converting

```
$$\sum_i x_i$$

$$\left( \sum_i x_i \right)$$

$$\prod_i x_i$$

$$\left( \prod_i x_i \right)$$
```

to docx produces the attached:

![screen shot 2016-07-24 at 12 08 29 pm](https://cloud.githubusercontent.com/assets/5217058/17085167/76e8a520-5197-11e6-8106-af73ed19b57d.png)

As you can see, without parentheses, the operator is converted correctly but the subscript is improperly converted to a superscript. With parentheses, the subscript is correct, but the symbol does not appear to be interpreted as an operator (hence it is small).

I am using 1.17.2, but the problem was present in the previous version as well. (Sorry, I'm not sure if it's best to post these things to `pandoc` or `texmath`).

**Comment by jgm** [comment]
Fixed the first issue, which was a simple transposition bug.  (Bad on me for using positional parameters.)

Not sure whether the second is a bug, or just the way Word lays things out when inside parens.

**Comment by jrgcmu** [comment]
Thanks. I do think the second issue is somehow pandoc related, because entering the same expression manually results in a large operator wrapped in large parens.

**Comment by jgm** [comment]
Can you open an issue for this remaining issue in jgm/texmath?

+++ John Gardner [Jul 24 16 12:06 ]:
