### ISSUE TITLE
[Improvement] Use styles for italics and bold (MD2DOCX at least)

### ISSUE THREAD

**Issue by trylks** [jgm/pandoc#3041]
I think this would be a significant improvement. It is applicable at least to markdown to docx conversion, but it may be relevant for any conversion from a less expressive format (like textile) to more expressive formats (like LaTeX).

In the docx, there are styles like `emphasis`, `strong`, and `subtle emphasis` that could be used for this purpose (from now on "these styles"). 

I guess that these styles are used when converting from HTML, which has italics, bold, and these styles. Nevertheless, markdown should be interpreted as using these styles (also for the conversion to HTML) and not directly italics and bold.

In the case of LaTeX (I don't know the current situation) it would be nice to have special commands, that would then be mapped to emphasis, italics, bold, etc. Then that mapping could be modified to something more ellaborated, e.g. add some special color. Modifying the color of italics can be done in HTML with CSS, but not in docx or LaTeX, AFAIK.

This will give more opportunities to customize and improve the output. Please let me know if something is unclear.

I hope it is easy to change this. I tried to check the code on my own, but my Haskell is rusty and never was that good anyway. I think the change may consist on changing a couple of terms here: 

https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Docx.hs#L517

But I may be wrong.

WRT backwards compatibility (if that's an issue), it should not be broken, the new styles would be just specifying italics and bold, just through an style. Alternatively, it could be a configuration option to enable, so that backwards compability is maintained without that option and the new "indirect" styles are used when activating it. If there is a workaround to do what I propose in a different manner, I would be very interested. 

Thank you.

**Comment by tarleb** [comment]
It is a bit unclear to me what you are proposing, maybe because we are using different terminology.  Most notably, this statement has me seriously confused:

> markdown should be interpreted as using these styles and not directly italics and bold

Could you give a brief example of what you mean by this?

**Comment by trylks** [comment]
Brief and simple example:

```
I write *italics* in Markdown.
```

When converted to Word I get: "I write *italics* in Markdown", where the word *italics* has the font set as "italics" but it does not have any particular style (there are several defined, like `emphasis`, `strong`, and `subtle emphasis`, they can be seen exploring the styles in Word).

If a style was used (probably "`emphasis`"), then the reference Word document (`--reference-docx`) that is used to define the styles could be used to customize the text `*italics*`, such syntax could be used not literally for italics (which would be the default behavior) but for anything else (e.g. italics with some color).

This would:

1. Make the Markdown definition more "semantic".
2. Provide a default behavior as the current state of the art, so no cons for these pros.
3. Give more flexibility to generate better documents directly (it is always possible to edit the Word document manually)

And maybe it is not too hard. The only potential problem that I can think about now is if Word does not allow nested styles (as in HTML), because we may want to use italics in the body, headers, and many other places. I guess it does, otherwise it would be a terrible mess (it may be).

I think that in the conversion to HTML `<em>` and `<strong>` are used instead of `<i>` and `<b>`. This would be the same. In addition, we would be able to use the reference docx to modify those styles, which is an important difference, IMHO, (in contrast, for HTML there isn't much of a difference, `<em>` and `<i>` can be customized with CSS).

**Comment by tarleb** [comment]
Thank you, I think I understand better now.  Just to confirm: The heart of the suggestion is to use different styles in docx output, namely `emphasis` and `strong` instead of `i` and `b`. Is that correct?

Internally, pandoc already has a strong focus on semantics.  E.g. the respective internal constructors are named `Emph` and `Strong`.  That focus is also the reason why there is currently no support for underlined text, which doesn't have a clear semantic meaning.

**Comment by trylks** [comment]
Correct, just one clarification, the terms `emphasis`, `strong`, `i`, and `b`, belong to HTML, I mentioned the styles `emphasis` and `strong`, and the fonts `italics` and `bold` (these are the terms used in Word). Styles and fonts are a different thing in Word. A style may specify a font, spacing, and other stuff. Currently, styles are used for nearly everything in the conversion from Markdown to Word, the only exceptions that I found are italics and bold fonts.

Thank you.

**Comment by tarleb** [comment]
I know very little about docx as a format. @jkr, can you help?

**Comment by jkr** [comment]
I'm pretty skeptical -- it would be equivalent to using custom spans for `<em>` and `<i>` in html, defined in some inserted css. It would allow greater customization, but at the cost of making what 99.9% of folks want more brittle. In particular, it would make basic formatting a lot more dependent on `reference.docx`, which, as the bug reports would suggest, tends to be the weakest and most corruptible link in docx output.

I would prefer to eventually have some sort of user-defined spans (similar to the user-defined div discussed in #3070). Then, if you really wanted this, you could write a filter to translate `Emph` and `Strong` into your custom spans and put those in. But let's see what John thinks of the div idea first.

**Comment by jkr** [comment]
By the way, you can switch replace built-in formatting with your custom style in Word with Advanced Find and Replace. I know that probably isn't what you want (many people use this so they don't have to use word) but it is possible.

**Comment by jkr** [comment]
Also, worth pointing out that all of the inline formatting (smallcaps, strikethrough, vertical alignment) uses the built-in formatting instead of styles. I tend to think this is the right default, for the reasons mentioned above. But I would like it to be filterable eventually, so power users could be powerful.

**Comment by trylks** [comment]
Thank you. I am currently using Advanced Find and Replace in Word, but I have to use it every time that I generate a new docx. If I could customize reference.docx that would be a significant time saver.

WRT the inline formatting, I find no reason why not using styles instead of changing the font ad-hoc. I find several reasons to use styles, please correct me if wrong:

1. It is the encouraged way to do things in Word, for users that are using Word manually.
2. The styles are already present (but not used) in the docx that is generated from Markdown, in the absence of a reference.docx, so this would not make the process any more dependent from reference.docx. 
3. The styles could be used (even in the absence of a reference.docx) to generate visually equivalent docx files.
4. The styles could be used (in the presence of reference.docx) to provide further capabilities for customization and the production of the docx file.
5. The resulting docx file would be more regular and homogeneous, by using styles everywhere, instead of styles sometimes and font modifiers some other times.

About divs and filters, I don't really know how they work, or even if Word has divs as such. From my perspective, my proposal is something much more simple.

**Comment by jkr** [comment]
I don't know what you mean by point 2. There are currently no inline styles in the docx that pandoc puts out.

In any event, I do understand your desire here. I'll take a closer look -- but I think we'd need to be sure that most users (who use Ctrl-i, Ctrl-b, regardless of what MS tells them to do) wouldn't have their experience affected.

As I said, though, I do think that soon you will be able to do what you want to do using pandoc filters (and when that happens, it will be easy to pick up, and will give you even more flexibility).

**Comment by trylks** [comment]
WRT point 2, I refer to the styles in Word.

![styles in Word](http://www.klariti.com/images/microsoft-word-style-menu-clear-all.jpg)

If we use pandoc to generate a docx document from a Markdown file, we can navigate the styles in that docx file and find `emphasis` (just as in the picture), `strong`, `subtle emphasis`, etc. It just happens that there is no text using them, but I think they should be used. Then, of course, it would also be possible to define our own additional styles. That should cause no trouble AFAIK, but that would be more similar to the use of custom spans that you mentioned earlier.

I hope everything is clear now. Thank you.

**Comment by jgm** [comment]
I like @jkr's solution here, and I'm in favor of #3070 (and
why not do the same for Spans?).

+++ Jesse Rosenthal [Aug 14 16 03:44 ]:
