### ISSUE TITLE
Word export: no style for images?

### ISSUE THREAD

**Issue by jmuheim** [jgm/pandoc#3043]
I need to have a solid border around images exported to Word.

I just noticed that Pandoc doesn't apply any custom style to images in Word, it's style is "Normal":

![image](https://cloud.githubusercontent.com/assets/1814983/17140288/371d28dc-5348-11e6-844c-748a853cea11.png)

This makes it impossible to add a border to every image automatically. Pandoc should add a custom style "Image" or something to every image paragraph, the same way it happens for the image caption:

![image](https://cloud.githubusercontent.com/assets/1814983/17140326/6251d552-5348-11e6-89ef-48302b0e31f6.png)

Is there any other way to paint a border around each image?

**Comment by jkr** [comment]
In the development branch, you can now add arbitrary styles to docx. So here, you could write a filter which takes every `Para [Image ...]` and wraps it in `<div custom-style="Image">...</div>` or whatever. You can look [here](http://pandoc.org/scripting.html) for more info on writing filters.

**Comment by jmuheim** [comment]
This sounds interesting. Is it possible only in the dev branch, or already in version 1.16?

Quote from the docs:

> This tutorial is for pandoc 1.16 or higher

**Comment by jkr** [comment]
The tutorial works for pandoc >= 1.16 (and filters work for pandoc versions going way back). But the ability to apply custom styles to a docx is only in the development version. The method for using filters to apply those styles, though, is the same as the methods described in the tutorial.

**Comment by jmuheim** [comment]
I understand. Thanks a lot for explaining it.

**Comment by jmuheim** [comment]
Is there any news on this? Can custom styles be applied to docx it meanwhile? 👍

**Comment by mb21** [comment]
see http://pandoc.org/MANUAL.html#custom-styles-in-docx-output

**Comment by jmuheim** [comment]
It's great to hear that it's possible now.

I took a look at the code, but Haskell looks really scary to me.
