### ISSUE TITLE
Org reader ignores headline if there is no blank line separating a \clearpage

### ISSUE THREAD

**Issue by ag91** [jgm/pandoc#3047]
Hi,

I am using pandoc 1.17.2
compiled with texmath 0.8.6.5, highlighting-kate 0.6.2.1.
I am reporting just a minor bug: for the following org file

```
* Test
\clearpage
** not considered headline
```

pandoc does not consider the second headline, and prints a "\* not considered headline"
Also the LaTex output is:

```
\begin{document}
\maketitle

\clearpage* not considered headline

\end{document}
```

so it is likely that this missing blank line may cause some other problem.
Thanks!!

**Comment by tarleb** [comment]
Thanks for the report, as always.  This one is a bit tricky.  The first star of the headline is parsed part of the preceding LaTeX command.  This is done by the LaTeX reader, so I'm a bit unsure how to proceed short of reimplementing the LaTeX command parser. Actually, that might not be so bad if we ever want to separate the reader into a different package some day.  Only very limited LaTeX parsing capabilities are needed. @jgm, what do you think?

**Comment by tarleb** [comment]
The downside would be that LaTeX citations would no longer work.  Same for some simple math commands allowed inline in Org-mode (e.g. `\oplus`).

**Comment by tarleb** [comment]
This now seems to be fixed.

**Comment by ag91** [comment]
amazing (did not test)! Thanks @tarleb !
