### ISSUE TITLE
beamer: sublists not respected when parent is marked incremental

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#3056]
For the following markdown:

    ## Slide with Bullets

    > - Major Point
        + Subpoint 1
        + Subpoint 2

In pandoc 1.15.2 the following output is produced:

```tex
\begin{frame}{Slide with Bullets}

\begin{itemize}[<+->]
\tightlist
\item
  Major Point

  \begin{itemize}[<+->]
  \tightlist
  \item
    Subpoint 1
  \item
    Subpoint 2
  \end{itemize}
\end{itemize}

\end{frame}
```

Whereas in pandoc 1.17.2 the following output is produced:

```tex
\begin{frame}{Slide with Bullets}

\begin{itemize}[<+->]
\tightlist
\item
  Major Point
\item
  Subpoint 1
\item
  Subpoint 2
\end{itemize}

\end{frame}
```

In the latter case the sublist has been flattened into the parent.

Is this an intended change in constraints and/or syntax for incremental bullets?

**Comment by jgm** [comment]
I can't offhand think of any relevant changes that would
have caused this change in behavior.  But I'd recommend
not using "laziness" in this way; just put a `>` at the
start of every line and make sure the sublist has sufficient
indentation.

**Comment by jjallaire** [comment]
Okay, thanks. For the record this syntax produces the desired output:

    > - Major Point
    >     + Subpoint 1
    >     + Subpoint 2
