### ISSUE TITLE
HTML Writer: TOC is missing items that are inside a pandoc div

### ISSUE THREAD

**Issue by kd7lxl** [jgm/pandoc#3057]
I am converting a Markdown document to HTML. In some places, I use raw HTML within the Markdown. I rely on pandoc's default behavior or interpreting content between HTML tags as Markdown. Between HTML tags, the Markdown is converted to HTML properly, however headings in between HTML tags are not added to the TOC.

http://pandoc.org/MANUAL.html#raw-html

> by default, pandoc interprets material between HTML block tags as Markdown

Here is a gist to reproduce the issue:
https://gist.github.com/kd7lxl/41321c20855eda8614e1b24effe82fcd

Notice that in the output, all three headings are rendered properly in HTML h1 tags, however the table of contents only contains two entries.

The command used to reproduce this with the files in the gist is:

``` sh
pandoc -s --toc -t html5 input.md -o output.html
```

I tested with pandoc 1.17.2.

**Comment by mb21** [comment]
Actually, the problem is not `raw HTML`, but the pandoc native `div` element (which happens to have the HTML syntax for now, even in markdown)...

**Comment by kd7lxl** [comment]
If I understand you correctly, you're saying this is actually a namespace-conflict bug in that there's no way to use use HTML `<div>` in a pandoc markdown document? That sounds like a major fix rather than minor. I was hoping this would be easy. :-/

**Comment by mb21** [comment]
well, the HTML writer outputs a HTML div when it encounters a pandoc [native div](https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Definition.hs#L232)...

so no, it's not that complicated... what I was trying to say is that the name of the issue should be: "HTML Writer: TOC is missing items that are inside a pandoc div"

let's see whether @jgm know more, #2df3dfe commit message says "Longer term, we might think about how hierarchicalize should interact with Div elements."

**Comment by kd7lxl** [comment]
Okay, title changed, and I've used `-f markdown-native_divs` as a workaround on my project.

**Comment by mb21** [comment]
This issue seems to have been discussed already in https://github.com/jgm/pandoc/issues/997
Not sure if we should reconsider the decision to won't-fix...

**Comment by reenberg** [comment]
This deserves documentation in the manual!  

I don't find it intuitive that having my h1 tags inside div's will have this side-effect, and I wasted quite some time figuring out why $toc$ was false, even when running pandoc with `--toc`.

**Comment by mb21** [comment]
> I've looked into this further, and I now think I'm going to mark this one "won't fix."
> The real issue is the `hierarchicalize` function from `Text.Pandoc.Shared`, which creates a nested section structure based on the outer-level headers of the document. It only looks at outer-level headers and does not recurse into other block-level structures (divs, lists, blockquotes, etc.) that can contain headers. I think that is actually the right approach. You might have a div with a header, for example, that works as a sidebar, and this header shouldn't be part of the main document structure. And these containers come with their own scopes that are hard to integrate with what hierarchicalize is doing.

Note though, that this current implementation of the `hierarchicalize` function differs from the [HTML5 Outline Algorithm](https://developer.mozilla.org/de/docs/Web/Guide/HTML/Sections_and_Outlines_of_an_HTML5_document#The_HTML5_Outline_Algorithm), which might or might not be desired.

**Comment by jgm** [comment]
> Note though, that this current implementation of the hierarchicalize function differs from the HTML5 Outline Algorithm, which might or might not be desired.

As far as I can see, this document agrees with the idea that Divs (or at any rate "sections") should not be split up in hierarchicalizing; they operate as units.

> "Relative ranking matters only within a section; the structure of the sections determines the outline, not the heading rank of the sections. "

To me that implies that we should NOT treat
```html
<h1>one</h1>
<div>
<h1>two</h1>
</div>
<div>
<h2>three</h2>
</div>
<h1>four</h1>
```
as having the hierachical structure:
```
- one
- two
  - three
- four
```
since the `h1` in the div should not be regarded as the same outline level as the `h1` outside of it.
(This is like the original issue above.)

What we DO want hierarchicalize to handle better are things like:
```html
<div>
<h1>one</h1>
<div>
<h2>two</h2>
</div>
</div>
```
and also
```
<div>
<h1>one</h1>
<div>
<h1>two</h1>
</div>
</div>
```
which should both come out as
```
- one
  - two
```

**Comment by mb21** [comment]
If I understand correctly, (quickly tested with [this tool](https://gsnedders.html5.org/outliner/)), then `div`s are completely ignored, while things like `section` add structure. But since pandoc native divs probably often are used like sections, maybe it's not the right thing for us to emulate the HTML5 outline algorithm.

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

> If I understand correctly, (quickly tested with [this tool](https://gsnedders.html5.org/outliner/)), then `div`s are completely ignored, while things like `section` add structure. But since pandoc native divs probably often are used like sections, maybe it's not the right thing for us to emulate the HTML5 outline algorithm.

I agree.

**Comment by NightMachinary** [comment]
For html, we need to use `-f html-native_divs`. Why isn't this the default? What do we lose by activating it?
BTW, I want to highlight my experience that the most important thing in a TOC is that the entries exist at all, not their exact hierarchy.

**Comment by jgm** [comment]
The fix here still needs more work and testing.

**Comment by jgm** [comment]
Current problem is that with input like
```
<h1>one</h1>
<div class="special">
<h1>two</h1>
</div>
```
we'll lose the div on translation to HTML.  Essentially, hierarchicalize now collapses attributes of the header and div together in this kind of case, and they can't be disentangled.  The best solution would be to separate the header and section attributes in Section, or provide some other way to preserve the original enclosing div.

**Comment by jgm** [comment]
For relevant discussion see PR #997

**Comment by mb21** [comment]
@jgm are you changing only the toc-generation, or does the html reader use `hierarchicalizeWithIds` indirectly somehow?

My feeling is that it would be good to read the divs in as normal... and do the adjustments on the toc generation.... or yes, disable `native_divs` and `native_spans` by default on the html reader...

**Comment by jgm** [comment]
The change involves `hierarchicalizeWithIds` -- that is used both for toc production and for other things.  You might be right that disabling `native_divs` and `native_spans` would be a better way to go.  But let me try the thing I'm trying now...

Note that this also affects markdown content such as
```
# One

# Two

::: appendices
# Three

# Four
:::
```

With the old method of hierarchicalizing, the whole appendices section gets treated as a chunk and not included in the toc or the numbering.

**Comment by jgm** [comment]
I've started a new experiment in the makehierarchical branch.
The idea is to get rid of the Element type altogether, and just use regular Divs to represent the section structure.  I've got makeHierarchical in Text.Pandoc.Shared, and I've used it in the docbook writer successfully.  It will take a bit of work to make it work elsewhere.
