### ISSUE TITLE
Error in converting `align` environment equations enclosed in `$$`

### ISSUE THREAD

**Issue by pkjkrai66** [jgm/pandoc#3059]
markdown strictly requires all equations to be enclosed in `$$` but `align` environment equations does not require to be enclosed in `$$...$$` in LaTeX. If I try to convert a .md file (Conmmand: `pandoc test1.md -s -o test1.pdf`) containing `align` environment formula enclosed in `$$`, I recieve the following error:

```
! Package amsmath Error: Erroneous nesting of equation structures;
(amsmath)                trying to recover with `aligned'.

See the amsmath package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.57 \end{align}

pandoc.exe: Error producing PDF
```
I have raised the issue at adequate platforms [tex.SE](https://tex.stackexchange.com/questions/322038/error-with-equation-conversion-while-converting-markdown-to-pdf-using-pandoc) and [pandoc-discuss](https://groups.google.com/forum/#!topic/pandoc-discuss/IHB_mcdGxJI), but seems like there is no solution to this.

Would it be possible to allow conversion of `align` environment equation enclosed in `$$` to pdf OR any other option which can work.

Kindly let me know if I have not made myself clear.
Thanks

**Comment by jgm** [comment]
Use the `aligned` environment, which works inside $$.

+++ pkjkrai66 [Aug 06 16 01:45 ]:
