### ISSUE TITLE
add instructions how to install pandoc system-wide

### ISSUE THREAD

**Issue by Tagar** [jgm/pandoc#3061]
http://pandoc.org/installing.html
reads "stack install will install the pandoc executable into ~/.local/bin, which you should add to your PATH"

Any way to install pandoc system-wide, to /usr/bin or something?
This ticket is to fix documentation.
Is it enough just to copy executable there, or there are some dependent libraries are needed too?

INSTALL file missing this information too.

Thanks.

**Comment by chrissound** [comment]
I guess it would depend on your distribution. 

It might be available via your package manager. (It is available in Arch linux for me - `pacman -S pandoc`).

**Comment by Tagar** [comment]
We're all RedHat. RedHar 6.7 currently. I got surprized to not find such a popular package as pandoc neither in yum nor available anywhere as an rpm. 

Other ideas?

Thanks.

**Comment by Tagar** [comment]
After resolving https://github.com/jgm/pandoc/issues/3062 I got pandoc compiled:

> Preprocessing executable 'pandoc' for pandoc-1.17.2...
> [1 of 2] Compiling Paths_pandoc     ( .stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0/build/autogen/Paths_pandoc.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0/build/pandoc/pandoc-tmp/Paths_pandoc.o )
> [2 of 2] Compiling Main             ( pandoc.hs, .stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0/build/pandoc/pandoc-tmp/Main.o )
> Linking .stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0/build/pandoc/pandoc ...
> pandoc-1.17.2: copy/register
> Installing library in
> /opt/pandoc/pandoc-1.17.2/.stack-work/install/x86_64-linux-gmp4/nightly-2016-07-11/8.0.1/lib/x86_64-linux-ghc-8.0.1/pandoc-1.17.2-KADEM54SBr3JwdjzauXf4d
> Installing executable(s) in
> /opt/pandoc/pandoc-1.17.2/.stack-work/install/x86_64-linux-gmp4/nightly-2016-07-11/8.0.1/bin
> Copying man page to
> /opt/pandoc/pandoc-1.17.2/.stack-work/install/x86_64-linux-gmp4/nightly-2016-07-11/8.0.1/share/man/man1
> Registering pandoc-1.17.2...
> Completed 4 action(s).
> Copying from /opt/pandoc/pandoc-1.17.2/.stack-work/install/x86_64-linux-gmp4/nightly-2016-07-11/8.0.1/bin/pandoc to /root/.local/bin/pandoc
> 
> Copied executables to /root/.local/bin:
> - pandoc
> 
> WARNING: Installation path /root/.local/bin not found on the PATH environment variable

Do I just copy now /root/.local/bin/pandoc to i.e. /usr/local/bin/ ? So everyone can use it.

Is a standalone pandoc made up of just that binary, or it also compiles into some dependent libraries?

**Comment by jgm** [comment]
+++ Ruslan Dautkhanov [Aug 10 16 10:34 ]:
>   Do I just copy now /root/.local/bin/pandoc to i.e. /usr/local/bin/ ? So
>   everyone can use it.

If you compiled with the `embed_data_files` flag, then yes,
you can do that.  Otherwise, no.  If you move it, pandoc
will no longer be able to find some necessary data files.
With stack you'd do that with

    --flag pandoc:embed_data_files

on the `stack install` command.

>   Is a standalone pandoc made up of just that binary, or it also compiles
>   into some dependent libraries?

Basically just that binary and some system libraries
(nothing pandoc-specific).  But see above about data
files.

If you want to install system wide, you need to set the
`prefix` to `/usr/local`.  The INSTALL file describes how
to set the prefix for a cabal installation.  stack doesn't
yet give you any way to do this (see
https://github.com/commercialhaskell/stack/issues/848),
so if you use stack, I suggest you use `embed_data_files`
as described above.

**Comment by Tagar** [comment]
Thanks @jgm ! I will definitely give it a try.

**Comment by Tagar** [comment]
I wonder if the error I was getting in https://github.com/jupyter/nbconvert/issues/357 was because I just copied pandoc to /usr/local/bin without embed_data_files flag set. Will re-install pandoc with embed_data_files and try again.

**Comment by jgm** [comment]
Very likely.

+++ Ruslan Dautkhanov [Aug 11 16 12:34 ]:

**Comment by Tagar** [comment]
I have recompiled pandoc using

`sudo stack install --flag pandoc:embed_data_files`

Still getting following error:

> [C 14:46:51.152 NotebookApp] pdflatex failed: [u'pdflatex', u'notebook.tex']
>     This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
>      %&-line parsing enabled.
>     entering extended mode
>     (./notebook.tex
>     LaTeX2e <2005/12/01>
>     Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang, noh
>     yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german, ng
>     erman, danish, esperanto, spanish, catalan, galician, estonian, farsi, finnish,
>      french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua, ibyc
>     us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish, por
>     tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian, swedish,
>     turkish, ukenglish, ukrainian, loaded.
>     (/usr/share/texmf/tex/latex/base/article.cls
>     Document Class: article 2005/09/16 v1.4f Standard LaTeX document class
>     (/usr/share/texmf/tex/latex/base/size10.clo))
>     (/usr/share/texmf/tex/latex/graphics/graphicx.sty
>     (/usr/share/texmf/tex/latex/graphics/keyval.sty)
>     (/usr/share/texmf/tex/latex/graphics/graphics.sty
>     (/usr/share/texmf/tex/latex/graphics/trig.sty)
>     (/usr/share/texmf/tex/latex/config/graphics.cfg)
>     (/usr/share/texmf/tex/latex/pdftex-def/pdftex.def)))
> 
>     ! LaTeX Error: File `adjustbox.sty' not found.
> 
>     Type X to quit or <RETURN> to proceed,
>     or enter new name. (Default extension: sty)
> 
>     Enter file name:
>     ! Emergency stop.
>     <read *>
> 
>     l.19     \usepackage
>                         {color} % Allow colors to be defined^^M
>     !  ==> Fatal error occurred, no output PDF file produced!
>     Transcript written on notebook.log.

Is this problem in pandoc domain, or it is more pdflatex/ texlive specific? (I am not an expert in either one of those)

**Comment by jgm** [comment]
That's latex specific.  You're just missing a package that
is needed (adjustbox.sty).

+++ Ruslan Dautkhanov [Aug 11 16 13:49 ]:

**Comment by tarleb** [comment]
It seems that the issue has been resolved, can this be closed?
