### ISSUE TITLE
pandoc-1.17.2 build/install using stack gives: cabal copy' failed. Error message: Process exited with code: ExitFailure 1

### ISSUE THREAD

**Issue by Tagar** [jgm/pandoc#3062]
pandoc-1.17.2 build/install using stack gives: cabal copy' failed. Error message: Process exited with code: ExitFailure 1

> Warning: File listed in pandoc.cabal file does not exist: data/templates/default.epub
> Warning: File listed in pandoc.cabal file does not exist: data/templates/default.epub3
> pandoc-1.17.2: copy/register
> data/templates/default.html: copyFile: does not exist (No such file or
> directory)
> Completed 86 action(s).
> 'cabal copy' failed.  Error message:
> 
> --  While building package pandoc-1.17.2 using:
>       /opt/pandoc/pandoc-1.17.2/.stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0 copy
>     Process exited with code: ExitFailure 1
> 
> Possible causes of this issue:
> * No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
> * The Setup.hs file is changing the installation target dir.
>

**Comment by jgm** [comment]
Most likely you didn't do a 'git submodule update --init'
after cloning the repository, as advised in the
instructions!

+++ Ruslan Dautkhanov [Aug 06 16 22:42 ]:

**Comment by Tagar** [comment]
Yes, I saw that: 

> 2.  If you used git to get the pandoc source (as opposed to unpacking
>     a release tarball), do
>         git submodule update --init

But I did not use git to get source, I just downloaded 1.7.2 as a tar.gz file.

$ sudo stack install fails with 

```
pandoc-1.17.2: copy/register
data/templates/default.html: copyFile: does not exist (No such file or
directory)
'cabal copy' failed.  Error message:

--  While building package pandoc-1.17.2 using:
      /opt/pandoc/pandoc-1.17.2/.stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-gmp4/Cabal-1.24.0.0 copy
    Process exited with code: ExitFailure 1

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* The Setup.hs file is changing the installation target dir.


```

**Comment by jgm** [comment]
+++ Ruslan Dautkhanov [Aug 08 16 08:14 ]:
>   Yes, I saw that:
>
>    1. If you used git to get the pandoc source (as opposed to unpacking a
>       release tarball), do git submodule update --init
>
>   But I did not use git to get source, I just downloaded 1.7.2 as a
>   tar.gz file.

From where?  If you did this from github releases page, note
that that the tarball they provide is just the same as what
you'd get doing git clone.  The official pandoc source
tarball can be found at
https://hackage.haskell.org/package/pandoc
If I could remove the github tarball I would, but it's
automatically provided in the release.

**Comment by Tagar** [comment]
I think I downloaded from here
https://github.com/jgm/pandoc/releases/tag/1.17.2

Got it - thank you. I will give it another try using the link you provided and report result here.

**Comment by Tagar** [comment]
I was able to compile pandoc when downloaded source from https://hackage.haskell.org/package/pandoc as you were saying. 
Thank you for updating documentation.
