### ISSUE TITLE
Conversion of double dashes to em-dashes

### ISSUE THREAD

**Issue by nirbhasa** [jgm/pandoc#3063]
As per 11.7.1 of the [org mode manual](http://orgmode.org/org.html) -, --, --- should be treated as dashes of varying lengths.

Right now, double dashes are not getting converted to em-dashes

**Comment by tarleb** [comment]
Try calling pandoc with the `--smart` option to enable smart quotes and typography.

Maybe turning this on should be the default when reading org-mode files, as smart quotes/punctuation are the default in org-mode and can be turned off using the `-` and `'` export settings.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Aug 07 16 23:51 ]:
>   Try calling pandoc with the --smart option to enable smart quotes and
>   typography.
>
>   Maybe turning this on should be the default when reading org-mode
>   files, as smart quotes/punctuation are the default in org-mode and can
>   be turned off using the - and ' export settings.

One problem with making "smart" the default for a format is
that there's no command line option `--no-smart`.  So it
can't be turned off.  You could make it sensitive to
these export settings, but then what about document
fragments?

**Comment by tarleb** [comment]
> document fragments

I hadn't thought of those. I guess the change would complicate things too much in that regard.

I prefer consistency, though in this case it the choice of being consistent in respecting the `-S` option or consistently adhering to Org-mode's defaults.  Also given your above argument, consistency within pandoc is probably preferable in this case.

I'm compiling a wiki page to address org-mode peculiarities, addressing this issue there should be sufficient.
