### ISSUE TITLE
Org-mode to HTML conversion of VERSE directive

### ISSUE THREAD

**Issue by nirbhasa** [jgm/pandoc#3064]
A couple of issues here:

- Verses begin with `<p><br />` and end with `<br /><p>`
- The conversion does not preserve indentation at the beginning of lines (at least space indentations)

**Comment by tarleb** [comment]
> Verses begin with <p><br /> and end with <br /><p>

I'm not sure what you mean here.  Could you give me an example, optimally with the expected output?

> The conversion does not preserve indentation at the beginning of lines (at least space indentations)

Fixed in #3065.

**Comment by nirbhasa** [comment]
Apologies for not getting back to this sooner

Org mode format

```
#+BEGIN_VERSE

Twinkle twinkle little star
How I wonder what you are

#+END_VERSE
```

Expected:

```
<p>Twinkle twinkle little star<br />
<p>How I wonder what you are</p>
```

Actual

```
<p><br />
Twinkle twinkle little star<br />
<p>How I wonder what you are<br />
</p>
```

**Comment by tarleb** [comment]
Thank you for the clarification.  I agree that it's a bit irritating to have preceding and trailing newlines preserved in the output, yet I wouldn't rate this as a bug. Emacs orgmode behaves almost identically.  In fact, it even adds an additional trailing `<br />` tag, though that shouldn't matter in practice:

```
<p class="verse">
<br  />
Twinkle twinkle little star<br  />
How I wonder what you are<br  />
<br  />
</p>
```

Either way, thanks for reporting these issues.
