### ISSUE TITLE
Markdown *emphasis* is transformed to __unconstrained emphasized text__ in asciidoc

### ISSUE THREAD

**Issue by amueller** [jgm/pandoc#3068]
I think it should be ``_emphasis_``. Is there an option to change it? What is the reasoning behind it?

**Comment by amueller** [comment]
It seems to be triggered by a full stop:
```
echo " one *test* two *tests*. three *tests*" | pandoc -f markdown -t asciidoc
```
> one _test_ two __tests__. three _tests_

**Comment by jgm** [comment]
The logic is to use `__` for intraword emphasis (where it is needed, if I'm not mistaken, in asciidoc).
Perhaps this is not a case which asciidoc regards as "interlard," because the `.` is punctuation.  We'd have to know *exactly* what the asciidoc rules are for this to improve things.  Perhaps you can point to the relevant part of the manual.

**Comment by amueller** [comment]
I'll try to find it. So with intraword emphasis you mean like th*i*s?

**Comment by amueller** [comment]
The guide says

> Quoted must be bounded by white space or commonly adjoining punctuation characters. These are the most commonly used type of quote.

"commonly adjoining punctuation characters." - great.

It's [around here](http://www.methods.co.nz/asciidoc/userguide.html#X51) in 10.1.2

**Comment by amueller** [comment]
This is from the reference implementation:
```python
        # Unconstrained quotes prefix the tag name with a hash.
        if tag[0] == '#':
            tag = tag[1:]
            # Unconstrained quotes can appear anywhere.
            reo = re.compile(r'(?msu)(^|.)(\[(?P<attrlist>[^[\]]+?)\])?' \
                    + r'(?:' + re.escape(lq) + r')' \
                    + r'(?P<content>.+?)(?:'+re.escape(rq)+r')')
        else:
            # The text within constrained quotes must be bounded by white space.
            # Non-word (\W) characters are allowed at boundaries to accomodate
            # enveloping quotes and punctuation e.g. a='x', ('x'), 'x', ['x'].
            reo = re.compile(r'(?msu)(^|[^\w;:}])(\[(?P<attrlist>[^[\]]+?)\])?' \
                + r'(?:' + re.escape(lq) + r')' \
                + r'(?P<content>\S|\S.*?\S)(?:'+re.escape(rq)+r')(?=\W|$)')
```

**Comment by amueller** [comment]
thanks @jgm :)
