### ISSUE TITLE
exported odt works in CalligraWords, but not in LibreOffice

### ISSUE THREAD

**Issue by robert-debian** [jgm/pandoc#3075]
Hi, exporting a minimal markdown to odt with the -s option, results in a document, which can be opened by CalligraWords, but crashes LibreOffice 5. The behavior is reproducible on fedora 24 with the most recent version of LibreOffice rpm. Any ideas?

**Comment by jkr** [comment]
Can you post the minimal markdown file and the odt file you get? Also -- what version of pandoc are you using?

**Comment by robert-debian** [comment]
Hi Jesse, strangely opening the files works, when invoking them from the 
file manager. I will look for the cause in the configuration of 
LibreOffice/ Fedora 24, but it is not an pandoc (version 1.16.0.2) 
issue. Sorry for the report, it can be closed, Robert.

**Comment by jkr** [comment]
Thanks for the update. Closing.
