### ISSUE TITLE
Pandoc Writer (Docx -> Markdown) should have option to put footnotes immediately after paragraphs

### ISSUE THREAD

**Issue by jalustig** [jgm/pandoc#3076]
Currently, Pandoc will output Markdown with footnotes at the end of the document. For instance:

    This is a paragraph.[^1]

    This is a second paragraph.[^2] Another sentence.[^3]

    [^1]: One footnote.

    [^2]: Another footnote.

    [^3]: A third note.

It would be great to be able to have the writer be able to optionally output footnotes inline to the document - not to the text itself. That it to say, after each paragraph it will list the footnotes, like this:

    This is a paragraph.[^1]

    [^1]: One footnote.

    This is a second paragraph.[^2] Another sentence.[^3]

    [^2]: Another footnote.

    [^3]: A third note.

Right now, this latter format is a valid Markdown *input* format for Pandoc, but it will not be output in this manner.

It would be particularly useful for diffing documents (or printing them for editing purposes). This way, the local changes are near to each other -- and particularly when text is moved from the body to a footnote or vice-versa, it will be clearer how the document has been edited.

**Comment by jkr** [comment]
I would actually like to see this too. It would make it easier to cut and paste  sections of markdown if the footnotes could be attached to the relevant paragraphs.

**Comment by jgm** [comment]
It would require a command-line option, I suppose.
Or should we implement it as an extension?  It would be an
odd extension, though, only affecting rendering, not
parsing.  Perhaps an option is best?


+++ Jesse Rosenthal [Oct 08 16 06:59 ]:

**Comment by jgm** [comment]
Or should it be the default?

If an option, maybe
`--markdown-footnotes=[interspersed|end]` or something like
that?

+++ Jesse Rosenthal [Oct 08 16 06:59 ]:

**Comment by jkr** [comment]
> Or should it be the default?

Emacs markdown-mode offers three options (for both footnotes and reference definitions): end of document, after current block, and before the next header. For footnotes, end of document is the default, which seems sensible. (It's what I prefer anyway.)

So I think I'd propose the same: `--markdown-footnotes=[end|block|header]`, with `end` as the default. Or, if we want, we could include link references (if reference-links is set).

So, I think that gives us three options:

1. `--markdown-footnotes=[end|block|header]`, no effect on links.

2. `--markdown-footnotes=[end|block|header]`, and change `--reference-links` to something like `--markdown-links=[inline|end|block|header]` (with inline as the default).

3. `--markdown-references=[end|block|header]` and have it act on links too iff `--reference-links` is set.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Oct 10 16 04:10 ]:
>    3. --markdown-references=[end|block|header] and have it act on links
>       too iff --reference-links is set.

This seems best to me.  Hard to imagine cases where you'd
want this behavior for links but not footnotes or vice versa.

**Comment by jkr** [comment]
The emacs terms, upon investigation, are `immediately|header|end`. Not sure if that's preferable or not to `block`. And the rule should probably be that it only comes after top-level blocks. I.e., if we have `Pandoc meta [BlockQuote[Para [Note]]]`, the note would come after the blockquote, not after the para within the blockquote.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Oct 10 16 06:39 ]:
>   The emacs terms, upon investigation, are immediately|header|end. Not
>   sure if that's preferable or not to block. And the rule should probably

How about paragraph|section|document or
paragraph|section|end?

>   be that it only comes after top-level blocks. I.e., if we have Pandoc
>   meta [BlockQuote[Para [Note]]], the note would come after the
>   blockquote, not after the para within the blockquote.

Yes, I wondered about this.  It actually works to put
footnote and reference definitions inside blockquote or list
environments, so maybe we don't need to do that?

**Comment by jkr** [comment]
John MacFarlane <notifications@github.com> writes:

> +++ Jesse Rosenthal [Oct 10 16 06:39 ]:
> How about paragraph|section|document or
> paragraph|section|end?

Sure -- I'd be happy with either. "paragraph|section|document" is more
consistent, but "paragraph|section|end" might be more clear.

> It actually works to put footnote and reference definitions inside
> blockquote or list environments, so maybe we don't need to do that?

It just seems that it could lead to too many undesired outcomes, like
references inside a table cell or list item -- things that I imagine are
not what people are intending. Top-level-only is an easy rule, correct
in the majority of the cases, and makes some visual sense: references
will always be on the left margin.

The one exception might be divs: both for the visual reasons mentioned
above, and because those could tend to be much longer.

**Comment by jkr** [comment]
closed with 14209b2ba

**Comment by nikkujensen** [comment]
Does this apply for Markdown -> Docx? I can get the footnotes to go from the end of the document to the end of the section, but my formatting gets messed up (i.e. bullet points become combined into block text)

**Comment by bpj** [comment]
Have you tried `--reference-location=block`? That will place both notes and link definitions after the block (whether a paragraph or some other kind of block) where the reference occurs. I use it all the time.

**Comment by alerque** [comment]
> Does this apply for Markdown -> Docx?

This option is about the Markdown *writer*. The reader handles them in any location anyway, and if you are going to Docx the position is irrelevant because Word doesn't have them inline with the content anyway.
