### ISSUE TITLE
Some math characters are slightly offset vertically when using --katex

### ISSUE THREAD

**Issue by joelostblom** [jgm/pandoc#3077]
I am trying to use Katex with Pandoc to render the following expression

```latex
J(\theta_0, \theta_1) = \frac{1}{2m} \sum\limits_{i=1}^m(h_\theta(x^i) - y^i)^2
```

When trying this on the [Katex home page](https://khan.github.io/KaTeX/), it looks as expected.
![selection-20160816-03](https://cloud.githubusercontent.com/assets/4560057/17708984/47d14276-63b5-11e6-812c-74c1e2f3aecd.png)

However, when I use Pandoc, the fraction/division line and some subset characters seem to be offset vertically from the rest of the text. This is the case both when using single `$` for inline math
![inline](https://cloud.githubusercontent.com/assets/4560057/17708899/fbf87fa4-63b4-11e6-9326-69658a59d2d3.png)

and double `$$` for display math.
![display](https://cloud.githubusercontent.com/assets/4560057/17708898/fbf75174-63b4-11e6-9570-265677e4abba.png)

The offset is worse for inline math. In both cases, the command I use is

```bash
pandoc katex-test.md -s --katex -o out-katex.html
```

I tried adding the `--self-contained` flag with the same result. If I use `--mathjax` instead of `--katex` the output looks as expected, but I would prefer to use Katex if possible. I am new to using math with Pandoc (and to Latex math in general), so I suspect that I might be missing something, but I can't figure out what. Any ideas?

**Comment by joelostblom** [comment]
I just noticed that this only happens when using Katex with the HTML output format. Converting to pdf instead works fine.

**Comment by joelostblom** [comment]
Realized I should have mentioned that I am using Pandoc 1.17.2 on Antergos Linux (arch derivative), kernel 4.6.4-1.

**Comment by jgm** [comment]
Take a look at the generated HTML, that may give a clue.

+++ joelostblom [Aug 16 16 10:44 ]:

**Comment by joelostblom** [comment]
This is the `--katex` output:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css" /><script type="text/javascript">window.onload = function(){var mathElements = document.getElementsByClassName("math");
  for (var i=0; i < mathElements.length; i++)
  {
   var texText = mathElements[i].firstChild
   katex.render(texText.data, mathElements[i])
  }}
  </script>
</head>
<body>
<p><span class="math inline">J(\theta_0, \theta_1) = \frac{1}{2m} \sum\limits_{i=1}^m(h_\theta(x^i) - y^i)^2</span></p>
</body>
</html>
```

This is the `--mathjax` output.

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>
</head>
<body>
<p><span class="math inline">\(J(\theta_0, \theta_1) = \frac{1}{2m} \sum\limits_{i=1}^m(h_\theta(x^i) - y^i)^2\)</span></p>
</body>
</html>
```

The two outputs differ in the `<script>`- tag, where different source urls are referenced and the `--katex`-version also calls a window.onload function. I naively tried removing that part just to make the syntax the same as in the `--mathjax`-version, but then there is no rendering of the math expression at all. 

The only difference in the syntax of the mathematical expression is the surrounding `\)` in the `--mathjax`-version. I tried adding these to the `--katex` output, but then nothing showed up when opening in Firefox or Chromium.

**Comment by joelostblom** [comment]
I found this on the katex issue tracker https://github.com/Khan/KaTeX/issues/332, in which the output looks similar to what I am experiencing. Based on that, I tried different variations of the `<!DOCTYPE> ` line. I found that if the line is changed to 
```
<!DOCTYPE html PUBLIC "//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```
(only removing the hyphen in `-//W3C...`), then the equations are rendered correctly. I am not sure in which output formats this hyphen is needed, but at least I tried removing the same hyphen in the `--mathjax`-html version and the output is still rendered correctly.

**Comment by jgm** [comment]
Every writeup I've seen of how to write the DOCTYPE for XHTML has the initial hyphen.  I don't really know what its meaning is, or what effect removing it would have, but I don't want to depart from the standard DOCTYPE unless I know more about what I'm doing.

Have you tried `-t html5`, which will include the html5 doctype instead?

+++ joelostblom [Aug 20 16 09:44 ]:

**Comment by joelostblom** [comment]
The output of `--katex -t html5` is

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css" /><script type="text/javascript">window.onload = function(){var mathElements = document.getElementsByClassName("math");
  for (var i=0; i < mathElements.length; i++)
  {
   var texText = mathElements[i].firstChild
   katex.render(texText.data, mathElements[i])
  }}
  </script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<p><span class="math inline">J(\theta_0, \theta_1) = \frac{1}{2m} \sum\limits_{i=1}^m(h_\theta(x^i) - y^i)^2</span></p>
</body>
</html>
```

which renders correctly. I did some additional tests with the [doctypes listed at w3schools](http://www.w3schools.com/tags/tag_doctype.asp). The HTML5, strict HTML4, XHTML1.1 and strict XHTML1.0 all works:

```
<!DOCTYPE html>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```

The transitional and Frameset HTML4 and XHTML 1.0 does not work.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
```

Since Pandoc uses the transitional XHTML 1.0 DOCTYPE, maybe removing the hypen causes some sort of error that makes the DOCTYPE fallback to its default, which might be strict? I asked about this on the Katex issue tracker (https://github.com/Khan/KaTeX/issues/519) and will let you know if they have some useful input/recommendations.

**Comment by jgm** [comment]
+++ joelostblom [Aug 20 16 12:56 ]:

>   Since Pandoc uses the transitional XHTML 1.0 DOCTYPE, maybe removing
>   the hypen causes some sort of error that makes the DOCTYPE fallback to
>   its default, which might be strict? I asked about this on the Katex
>   issue tracker ([2]Khan/KaTeX#519) and will let you know if they have
>   some useful input/recommendations.

Yes, I suspect that's what was happening.

The reason we use transitional is because people can inject
their own raw HTML in Markdown, so we can't be too confident
that the result will be well-formed XML.

Anyway, I'm not sure there's anything that can be done on
this issue, other than suggesting in the Manual that `-t
html5` be used with `--katex`.
