### ISSUE TITLE
php exec - pandoc: .: openTempFile: permission denied (Permission denied)

### ISSUE THREAD

**Issue by KrzysztofSikorski** [jgm/pandoc#3078]
I'm executing following command in exec function in php.

`PATH=/usr/local/bin:/usr/bin:/bin: pandoc -t html5 -o /home/www-data/.../articles/13125.pdf /home/www-data/.../articles/13125.html > /home/www-data/debug.log  2>&1` (part of path ommited).

I was following that advice to solve PATH problem - https://github.com/jgm/pandoc/issues/1587 - that why there is "PATH="

Then I have an error - pandoc: .: openTempFile: permission denied (Permission denied)

Executing as www-data by "su www-data -c" works, so the permissions must be well set.

Ver.
pandoc 1.17.2
wkhtmltopdf 0.12.3 (with patched qt)

**Comment by tarleb** [comment]
Looks like a file permission error unrelated to pandoc. The www-data user probably doesn't have write permissions in the current working directory.  Try adding something like `PATH=/usr/local/bin:/usr/bin:/bin: cd /tmp && pandoc …`.
