### ISSUE TITLE
Markdow to PDF: Image short caption not work

### ISSUE THREAD

**Issue by ckybonist** [jgm/pandoc#3079]
I want to show long caption under image, and short caption in the _List of Figures_, so I followed the instructions in [this issue](https://github.com/jgm/pandoc/issues/2417).

Here is my original markdown `test.md`:

``` markdown
Instruction
===========

You can execute me with `pandoc source.md -o final.tex` and
`pandoc source.md -o final.pdf`.


![This is a long caption.](http://fakeimg.pl/439x320/282828/ "short 1")

![This is a long caption blabla.](http://fakeimg.pl/439x320/282828/ "short 2")


\listoffigures
```

After `pandoc test.md -o test.tex`, I got the `test.tex`:

``` tex
\section{Instruction}\label{instruction}

You can execute me with \texttt{pandoc~source.md~-o~final.tex} and
\texttt{pandoc~source.md~-o~final.pdf}.

%========== Images ============
\begin{figure}[htbp]
\centering
\includegraphics{http://fakeimg.pl/439x320/282828/}
\caption{This is a long caption.}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics{http://fakeimg.pl/439x320/282828/}
\caption{This is a long caption blabla.}
\end{figure}
%========= END Images ===========

\listoffigures
```

Notice the `\caption` of two images in `test.tex`, I expect pandoc will give me
`\caption[short 1]{This is a long caption}` instead of the above one. It seems like pandoc doesn't catch the alt-text in markdown.

NOTE: The official doc have mentioned [the feature](http://pandoc.org/MANUAL.html#images)

**Comment by crmackay** [comment]
issue #2417 is still open, meaning this feature is NOT currently supported in Pandoc. In that issue the a branch of pandoc is being talked about which does support the use of the *title* attribute as a short caption, but this has not been merged into Pandoc. The major issue is that using the *title* attribute for a semantically different thing (a short caption) might be confusing and unexpected.

**Comment by ckybonist** [comment]
Got it.

**Comment by tarleb** [comment]
Closing in favor of #2447; most of the discussions about this feature seems to happen in that PR.
