### ISSUE TITLE
md/html/txt => pdf - conversion issues for japanese language

### ISSUE THREAD

**Issue by v1kn** [jgm/pandoc#3080]
`pandoc` does not seem to wrap japanese text, probably due to lack of spaces between words in this language. It  results in a sentence or a whole paragraph being cut off and missing.  This effect also does not respect margins set on the command line. 

here is my usual command:

```
pandoc test.md -o test.pdf \
-f markdown_github+fenced_code_attributes+pandoc_title_block+footnotes \
-S --latex-engine=xelatex \
-V fontsize=12pt -V mainfont='TakaoMincho' -V geometry:margin=3cm
```

**Comment by tarleb** [comment]
See also #534.

**Comment by v1kn** [comment]
Thank You.
However, the referenced issue is a pull request from 4 years ago, which is apparently in conflict with master. I have checked OP's activity - that pull request looks abandoned. 

Personally I ma not familiar with Latex enough to potenitally work around this issue.

Taking this under consideration, I would like to kindly ask the developers, to reconsider working on this feature. It would certainly make many CJK language users happy :)

**Comment by v1kn** [comment]
@tarleb Thank You for adding the tags.
Gives me hope this issue isn't forgotten

**Comment by mb21** [comment]
@v1kn have you tried setting `-V CJKmainfont="STSong"` (or some other font)? This should activate `\usepackage{xeCJK}` in pandoc's default LaTeX [template](http://pandoc.org/MANUAL.html#templates) which is used to generate the PDF.

**Comment by v1kn** [comment]
@mb21 
Today I tried again with these fonts:

* TakaoMincho
* IPAexMincho (japanese government standard)
* Noto Sans CJK JP {Medium,Light,etc}
* AoyagiKouzanFontT
* AR PL UKai CN (chinese font)

I also tried both single quotes and double quotes around the font name to be sure.
Unfortunately all fonts fail. I don't know what STSong is, and I cannot seem to find it in ubuntu repositories.

PS
Not sure if this helps or makes things more difficult, but I found these [word splitting rules][1] on wikipedia

[1]: https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages

**Comment by v1kn** [comment]
I should've mentioned this in case there were updates that might affect this issue.

I am running xubuntu 16.04, which has a fixed `pandoc` version on `1.16.0.2`.

**Comment by wilx** [comment]
Do you have an example text to reproduce this?

**Comment by v1kn** [comment]
@wilx, as for the version, I already updated pandoc on my ubuntu, effects are the same.

    pandoc 1.19.1
    Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3

As for the examples, sure, but better yet I can tell You how to get unlimited supply of examples. simplest way is to choose a topic or thing that is general and popular, look it up in wikipedia, and then scroll down to languages and choose this: 日本語

then you can have all articles in japanese in no time. So, for example, this is a random excerpt from wikipedia on 'milk'

日本同様に、例外的に牛乳の飲用が普及しなかった国としては、中国本土が挙げられる。北方からの牧畜民、遊牧民が華北に大規模に移住してきた五胡十六国時代～北魏時代には華北の食文化にモンゴル高原型の乳製品・乳加工技術が普及したことが斉民要術の記述から伺えるが、その後衰退した。半農半牧地帯に建国された金によって監禁された欽宗の悲劇として、茶を飲ませてもらえず、牛乳（という粗末なもの）を与えられたというエピソードが伝えられる。ただし日本同様、現在の中国でも酪農と牛乳は一般に普及している。

牛乳は腐敗しやすく保存が困難だった事から長年に渡り各農家の小規模な生産に頼っていたが、輸送技術や冷蔵技術の進歩、そして風味を損なわない低温殺菌法（パスチャライゼーション）の実用化により、今日では世界的に牛乳がひとつの産業として大規模に生産されている。先進国では、自動化された搾乳設備を持つ酪農業者によって、その大部分が生産されている。牛の品種のあるものは、ホルスタインのように、牛乳生産量の向上に特化して改良された。マクジーによれば、アメリカ合衆国の乳牛の90%、イギリスの乳牛の85%がホルスタインである。アメリカの代表的な乳牛品種は、ホルスタインのほか、エアシャー、ブラウンスイス、ガーンジー、ジャージー、ミルキング・ショートホーンなどである。今日、乳製品と牛乳の生産量が最も大きい国はインドで、これにアメリカと中国が次ぐ

I just tested this - the pdf output is just two lines that go beyond the page edge

**Comment by wilx** [comment]
This works for me just fine: `pandoc --verbose --self-contained --smart -f markdown -V CJKmainfont=IPAexMincho -t latex --latex-engine=xelatex -o test.pdf test.md`

If that does not work for you, try to simply output the LaTeX without compiling it by changing `-o` to output to `test.tex` and inspect the output.

**Comment by v1kn** [comment]
@wilx 
I've used Your command, and indeed now it works!

The culprit was my lax testing after pandoc upgrade to 1.19. This time I forgot to use `CJKmainfont` and only used `mainfont` variable.

Other fonts, chinese fonts, and chinese text, markdown format modifications also work fine.
Thank You

I can close the issue now.
