### ISSUE TITLE
Text that looks like HTML tags gets lost after two invocations

### ISSUE THREAD

**Issue by kedorlaomer** [jgm/pandoc#3082]
My executable says

        pandoc 1.17.2
        Compiled with texmath 0.8.6.5, highlighting-kate 0.6.2.

When I do

        $ echo '<<pandoc>>' | pandoc -f markdown -t html | pandoc -f html -t markdown

I would expect an output like `<<pandoc>>` or `&lt;&lt;pandoc&gt;&gt`. Instead, I get `&lt;&gt;`.

Although this incantation of pandoc is pointless, I have an application which requires something similar (with more things going on in between the two invocations).

**Comment by jgm** [comment]
`<pandoc>` is being parsed as a raw HTML tag (you can
confirm this by using `-t native`).  This gets passed
through to HTML output literally.  The HTML reader then
omits it as an unknown tag (but you can change this
behavior with `--parse-raw`).

If you use `-f markdown-raw_html` (turning off the raw
HTML extension), you'll get `&lt;&lt;pandoc&gt;&gt;`.

+++ kedorlaomer [Aug 21 16 13:57 ]:
