### ISSUE TITLE
Merging multiple input documents does not insert empty line in between

### ISSUE THREAD

**Issue by prigio** [jgm/pandoc#3083]
Hi, 

If multiple input files are given, pandoc will concatenate them all _without_ blank lines in between them (as stated within the docs). This can pose a problem when a file is not ending with an empty line and the following is a yaml metadata.  Example: 

_file.md_: (no blank line at the end)
```
# First chapter
With some text
```
_md.yaml_: (no blamk line at the beginning)
```
---
title: Title of the document
author: Author's name
...
```
To compile:

    pandoc --standalone -o test.html --from=markdown file.md md.yaml

Result:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
</head>
<body>
<h1 id="first-chapter">First chapter</h1>
<h2 id="with-some-text">With some text</h2>
<p>title: Title of the document author: Author's name ...</p>
</body>
</html>
```

**Comment by jkr** [comment]
This is the correct behavior, according to an earlier comment on a similar issue: 
https://github.com/jgm/pandoc/issues/2494#issuecomment-153431356
