### ISSUE TITLE
Syntax highlighting LaTeX code

### ISSUE THREAD

**Issue by PatrickMassot** [jgm/pandoc#3085]
Using either my own copy of pandoc 1.17.2 or [Try pandoc](http://pandoc.org/try/) I can't manage to get syntax highlighting in HTML for LaTeX code. When I type:

    ~~~ {.latex}
    \begin{itemize}
    \item Test
    \end{itemize}
    ~~~
    
    ~~~ {.bash}
    git pull
    ~~~

I get syntax highlighting in the second example but nothing for LaTeX:
```html
<div class="sourceCode">
  <pre class="sourceCode latex">
    <code class="sourceCode latex">
    \begin{itemize}
    \item Test
    \end{itemize}
    </code>
   </pre>
</div>
<div class="sourceCode">
  <pre class="sourceCode bash">
    <code class="sourceCode bash">
    <span class="kw">git</span> pull
    </code>
  </pre>
</div>
```

 ``pandoc --version`` does show latex as a valid syntax highlighter. What am I doing wrong?

**Comment by jgm** [comment]
See
https://groups.google.com/d/msg/pandoc-discuss/CJ0hXMHv-SI/bhzEZ50Iva4J

It actually is doing highlighting, but because of
the way the kate xml definition for latex is written,
not much happens.  (If you add a comment you'll see
that it is highlighted as such.)

Best thing to do would be change the latex.xml file and
recompile highlighting-kate.

+++ Patrick Massot [Aug 23 16 05:13 ]:

**Comment by PatrickMassot** [comment]
Thank you very much for your very quick answer. Unfortunately, given my Haskell skills, it translates to "you have to give up the idea of using pandoc to document LaTeX stuff". Is there any way to use an external syntax highlighter, say pygments, with pandoc?

**Comment by jgm** [comment]
You could write a filter to do this.  (Can be done using
python; see the pandocfilters or panflute libraries.)

+++ Patrick Massot [Aug 23 16 08:27 ]:

**Comment by PatrickMassot** [comment]
Thank you very much. Those keywords were enough for me to find [pandocfilter-pygments](https://github.com/DoomHammer/pandocfilter-pygments).
