### ISSUE TITLE
please make prebuilt binary available in "flatpak" format too

### ISSUE THREAD

**Issue by zaxebo1** [jgm/pandoc#3090]
at following URLs
https://github.com/jgm/pandoc/releases
and http://pandoc.org/installing.html
the in pre-built binaries are available in .deb , .pkg, .msi formats.

**kindly make it available in one more format of "flatpak"** (please see http://flatpak.org/ ) . The flatpak package was earlier named as xdg-app.

Although ubuntu and debian stable have pandoc packages in their repositories, but they are generally old versions. **So, if we are installing the above flatpak package, the advantage will be that "flatpak" package can be installed even without admin rights and flatpak can be installed on many linux distributions** . It is a distro agnostic format, and can be installed on fedora, fedora, arch, debian, gentoo etc from a single flatpak format ( see http://flatpak.org/getting.html ). In debian testing - it is available at https://packages.debian.org/testing/flatpak

**Comment by zaxebo1** [comment]
some other relevant urls
http://flatpak.org/
https://en.wikipedia.org/wiki/Flatpak
https://wiki.gnome.org/Projects/SandboxedApps
https://blogs.gnome.org/alexl/category/xdg-app/

**Comment by afranke** [comment]
flatpak is meant for desktop applications though and will require things like a .desktop file that pandoc will (rightfully) lack.

**Comment by zaxebo1** [comment]
please refer:
http://news.softpedia.com/news/you-can-now-run-flatpak-universal-apps-outside-a-linux-desktop-environment-506827.shtml

version 0.6.8 of flatpak includes a new feature of the implementation of the "--no-desktop" command-line argument that promises to let users run Flatpack applications outside the graphical desktop environment of their GNU/Linux operating system. Of course, some of the functionality will be lost when running Flatpak apps this way.

**Comment by zaxebo1** [comment]
and "debian testing" as of now includes version 0.6.9 of flatpak already
https://packages.debian.org/testing/flatpak

==============
This will be also be part of new stable , when new debian stable will be forked out of current debian testing in Nov 2016

===============
Fedora 25 will be launched in Nov 2016 with flatpak 0.6.9

**Comment by hadess** [comment]
I don't see any reasons to put pandoc in a Flatpak. The --no-desktop can be used for desktop services that need to be sandboxed, and still provide a service to the session (in this case, it was for a search helper).

I don't see how a command-line document format conversion tool would benefit from being sandboxed, you wouldn't even have a way to access files outside the sandbox without using a toolkit.

**Comment by probonopd** [comment]
https://bintray.com/probono/AppImages/Pandoc/_latestVersion#files has an experimental Pandoc [AppImage](http://appimage.org/). Here is how you can use it:

```
wget https://bintray.com/probono/AppImages/download_file?file_path=Pandoc-1.17.2.glibc2.11-x86_64.AppImage -O pandoc
chmod a+x pandoc
sudo mv pandoc /usr/local/bin # optional when you want to have it on your $PATH

pandoc --version
pandoc 1.17.2
Compiled with texmath 0.8.6.4, highlighting-kate 0.6.2.
```

Let me know how it works for you. It _should_ run on most Linux distributions with glibc 2.11 or newer.

**Comment by zaxebo1** [comment]
@probonopd  : thats really good and thats what i wanted. **"I basically wanted to use latest binary app version of pandoc - without disturbing system installed version of pandoc, and - without requiring the root permission to install it and without compilling it from source on every distribution."** 

I saw the appimage site, can you give the link to the "script for making AppImage of pandoc" and "powershell"?

**Comment by probonopd** [comment]
@zaxebo1 sure:
https://github.com/probonopd/AppImages/blob/master/recipes/pandoc/Recipe

In fact, I would hope that the pandoc project would provide an official AppImage. Mine is just for demonstration.

In https://github.com/probonopd/AppImages/blob/master/recipes/ you will find many more examples including the one for PowerShell.

**Comment by jgm** [comment]
Note: If you don't want to use dpkg (or can't because you
don't have root), you can manually unpack the deb we provide
officially and extract the pandoc executable wherever you
like.

Here's a one-liner to extract the executables and
documentation to the $HOME/.local directory (which we
assume has been created):

    ar p pandoc-1.17.2-1-amd64.deb data.tar.gz | tar xvz --strip-components 2 -C $HOME/.local/

I will add this information to the "installing" web page.

+++ zaxebo1 [Sep 26 16 08:43 ]:

**Comment by zaxebo1** [comment]
**Thanks a lot to @probonopd  and @jgm both** for the excellent info. I will try both the approaches.
you people may close the issue now.

**Comment by zaxebo1** [comment]
though i will put some resistance to https://github.com/jgm/pandoc/issues/3090#issuecomment-247294882  , regarding stated issues in flatpak 

also:  please search  the string "home: Allow full access to the users homedirectory" in the url  https://github.com/flatpak/flatpak/wiki/Metadata
it allows for the file access even in the sandbox through metadata, in the flatpak format. So the stated lacuna does not exist in flatpak

====================

but still the AppImage format and deb extraction - both methods are good enough for me, so you may close the issue.

**Comment by FilBot3** [comment]
I know I'm a bit late to this thread, but I ended up putting Pandoc in a Flatpak so I can use it on Fedora Silverblue. Also, just a fun learning exercise.

* https://github.com/FilBot3/org.pandoc.Pandoc

**Comment by CodeSandwich** [comment]
I want to bump this issue, I'm currently running Fedora and there doesn't seem to be a good way of installing pandoc on my machine. The official repository has version 3.1.11 which is almost 1 year old now, packages I found on copr are 3 years old at minimum and RPM fusion doesn't have any version at all. I must install the binaries manually, from GitHub releases, but it's tedious. Having Flatpak would solve this issue for me and users of many other distros that may not have up-to-date pandoc packaged for them.

**Comment by jgm** [comment]
It's actually not tedious to install from the GitHub releases.  Here's a one-liner to install the arm64 linux build in the `~/.local` directory tree:

```
curl https://github.com/jgm/pandoc/releases/download/3.5/pandoc-3.5-linux-arm64.tar.gz | tar -C ~/.local --strip-components=1 -xvzf -
```

**Comment by thomasboussekey** [comment]
Here is a little script (not a 1-liner anymore), in order to install the pandoc tools, using `$ARCH` and a variable `pandoc_release` in order to define the correct binaries to get:

```sh
pandoc_release="3.9.0.2"
# Map the output of uname -m to the standard binary names
case $(uname -m) in
    x86_64)  ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
    *)       echo "Unsupported architecture" && exit 1 ;;
esac

echo -e "Working on ARCH: ${ARCH}"

# Use the mapped variable
URL="https://github.com/jgm/pandoc/releases/download/${pandoc_release}/pandoc-${pandoc_release}-linux-${ARCH}.tar.gz"

echo -e "Downloading from URL: ${URL}"
rm -f ${HOME}/.local/bin/pandoc*

curl -sL "${URL}" | tar -C ~/.local --strip-components=1 -xvzf -
```
