### ISSUE TITLE
Ugly tagging when producing epub

### ISSUE THREAD

**Issue by Claudio-Sjo** [jgm/pandoc#3098]
Hi,
when producing epub files from xhtml, the < a > tag is converted as < a href="" >
This is formally correct, but epub readers assume that there's an hyperlink, thus showing text with underscore as they were real hyperlinks.
Please remove the automatic insertion of href="" when not explicit in xhtml source file.

Thanks,
Claudio

**Comment by jgm** [comment]
Can you give an example?  Are you saying that when the input contains

    <a>

the output contains

    <a href="">

That does not seem to be the case in my tests.

**Comment by jgm** [comment]
Also please say what version of pandoc you're using.

**Comment by Claudio-Sjo** [comment]
Hi,
pandoc is 1.17.2

Below you have the example.
I just run pandoc -o test.epub test.xhtml


[Downloads.zip](https://github.com/jgm/pandoc/files/451852/Downloads.zip)

**Comment by jgm** [comment]
Not much I can do about this.  The library we're using to
parse HTML doesn't distinguish between href="" and missing
href, so we need to parse both as links, or neither.

+++ Claudio-Sjo [Sep 02 16 04:09 ]:

**Comment by Claudio-Sjo** [comment]
OK, thanks anyhow.
I found an altarnative way for generating epub from xhtml that has not such <a> issue.

BR,
Claudio
