### ISSUE TITLE
LaTeX figures placement issues on pages with tables.

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#3103]
I want Pandoc not to set `[htbp]` placement options on each figure to allow overriding them by them using `\fps@figure` redefintion either in header or in template.

My motivation for this is so that we can work around a bug in LaTeX' `longtable` when it is placed onto a page where there is already a float above it:

* [floats - Figure/image is overflowing bottom of page - TeX - LaTeX Stack Exchange](http://tex.stackexchange.com/questions/326882/figure-image-is-overflowing-bottom-of-page)
* [Longtable and floats: wrong table breaks on pages with floats (part 2) - TeX - LaTeX Stack Exchange](http://tex.stackexchange.com/questions/203629/longtable-and-floats-wrong-table-breaks-on-pages-with-floats-part-2)

This is a long standing issue of `longtable` that will not be fixed any time soon. Instead, we propose a workaround where we avoid placing figures on the same page as tables are placed by overriding figure placement options to just `[p]` so that figures are placed onto separate pages. To support this workaround, Pandoc must not generate `[htbp]` placement option on each figure.

This is implemented in by pull request https://github.com/jgm/pandoc/pull/3093.

**Comment by jgm** [comment]
Am I right that the workaround means that every figure in a
document with tables will be on its own page?  That seems
less than ideal.  I seem to recall finding a fix to the
longtable.sty code somewhere on the net; this has worked
well for me in the past and would seem a better way around
this bug...

**Comment by wilx** [comment]
> Am I right that the workaround means that every figure in a document with tables will be on its own page?

Yes. However, I just want to be able to work around it when hit by it. If you also accept https://github.com/jgm/pandoc-templates/issues/215 then the default will stay the same.

> I seem to recall finding a fix to the longtable.sty code somewhere on the net; this has worked well for me in the past and would seem a better way around this bug...

I have seen some sort of diff/patch that theoretically fixes or works around it in the table code itself. However, patching LaTeX is not something I want to do regularly just to fix this. I'd rather change the default positioning of figures for my document instead.

**Comment by wilx** [comment]
@jgm So I have hit the issue again while creating some reports in Rmarkdown in Rstudio. It plagues pretty much any kind of report where there is a table and a chart on the same page. I would like to reiterate that with my changes to both Pandoc and default LaTeX template the default output will not change. Only people overriding `\fps@figure` should get be affected.

**Comment by jgm** [comment]
Thanks, merged your changes.
