### ISSUE TITLE
Specifying multiline yaml field in opendocument template

### ISSUE THREAD

**Issue by dbobak** [jgm/pandoc#3104]
Hi everyone!

Is it possible to specify in opendocument template reference to multiline position in yaml header?

This is the sample header:
```
---
date: 2016
abstract: |
	This is the first paragraph of abstract. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tristique nulla ac nunc semper tempus. Duis convallis lacus vel ante auctor condimentum. Cras egestas metus quis vestibulum efficitur.
    
	And the second paragraph of abstract. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tristique nulla ac nunc semper tempus. Duis convallis lacus vel ante auctor condimentum.
keywords: test1, test2, test3
...
```

Referencing it in odt template, for example:
```
$if(abstract)$
<text:p text:style-name="Abstract">$abstract$</text:p>
$endif$
```
makes no effect. When the abstract consists of one line, it shows in the document.

Does anybody know, how to reference in template to that abstract? Or is it a pandoc bug?

with best wishes,
Darek

**Comment by jgm** [comment]
What version of pandoc?  It works for me.  Make sure you
don't have any hard line breaks in those long lines.  Every
line in the `|` section must be indented.

+++ Darek Bobak [Sep 04 16 05:48 ]:

**Comment by dbobak** [comment]
Pandoc is the latest version, 1.17.2.

And the header looks exactly as in my previous post. Every line of the multiline is intendet (includind the empty line). And it works as it expected when converting to pdf or docx, the problem is with odt.

I'm attaching the source md file and template files as well as the resulting odt file; the command to produce odt is:

`pandoc --template default.opendocument --reference-odt article.odt --filter pandoc-citeproc  -o 00_header.odt 00_header.md`
[pandoc_odt.zip](https://github.com/jgm/pandoc/files/455206/pandoc_odt.zip)

**Comment by jgm** [comment]
I think I see the problem.

If you look at the opendocument XML source embedded in the ODT, you'll see this kind of structure:
```
<text:p text:style-name="Abstract"><text:p text:style-name="Text_20_body">contents</text:p>
<text:p text:style-name="Text_20_body">second paragraph</text:p></text:p>
```
This is illegal; you can't have a `<text:p>` element inside another `<text:p>` element.

You could fix this by removing the `<text:p>` surround in the template, but then it might not work if you don't have multiple paragraphs.  I'll look at the docx writer to see how we handle this issue there.

**Comment by jgm** [comment]
Yeah, we have some special code in the docx writer that handles the abstract, making sure that in every case we have a list of block-level elements:

```
  let abstract' = case lookupMeta "abstract" meta of
                       Just (MetaBlocks bs) -> bs
                       Just (MetaInlines ils) -> [Plain ils]
                       _ -> []
```

What we really need is a *typed* tempting language for pandoc.

**Comment by dbobak** [comment]
After removing <text:p> surround from the template it is working, even with multiple paragraphs.
The document uses default paragraph style for abstract, but I can live with it.

Thank you, John!
