### ISSUE TITLE
HTML tables with colspans and rowspans, how to convert to docx

### ISSUE THREAD

**Issue by two8g** [jgm/pandoc#3105]
I try to change the code of HTMLReader and DocxWriter,
I have got three list:
1. rows :: [[TableCell]]
2. colspanss :: [[Int]]
3. rowspanss :: [[Int]]
if all item is 1 in rowspanss, i can convert HTML tables to docx perfect
but where some item > 1 in rowspanss, i get trapped.

I need a some code to change colspanss and rows based on rowspanss.
like this:
```haskell
let rows = [[_,_],[_],[_,_]]
     colspanss = [[1,1],[1],[1,1]]
     rowspans = [[2,1],[1],[1,1]]
f colspans rowspans = [[1,1],[1,1],[1,1]]
f rows rowspans = [[_,_],[empty,_],[_,_]]
```
becouse 2 means the cell need 2 rows space

**Comment by jgm** [comment]
Pandoc's document model (the Pandoc structure) does not
support rowspans or colspans in tables.  To support these,
you'd need to make some fairly radical changes in
pandoc-types, or use a very ugly hack (like embedding
colspan info into a div containing the cell).

+++ 易斌鑫 [Sep 05 16 23:56 ]:

**Comment by two8g** [comment]
To support colspans is feasible and easy, but i don't know hwo to start the rowspans.

**Comment by jgm** [comment]
Yes, this requires a lot of thought about what the
underlying data structure should be.  Feel free to discuss
ideas on pandoc-discuss.

+++ 易斌鑫 [Sep 06 16 00:45 ]:

**Comment by tarleb** [comment]
@two8g The usual way to implement this are tree-based structures (exactly like in html); see for example this article on [table rendering with python](https://snai.pe/python/algorithm/rendering-tables/).
