### ISSUE TITLE
rmarkdown html rendering "center" text for every plot in Rmd document

### ISSUE THREAD

**Issue by guillermomarco** [jgm/pandoc#3106]
I'm trying to render an R Markdown report to HTML. If I plot it using the R studio knitr button the HTML is rendered ok, however when I render with the following command a **"center"** text appears below every figure in the document. (check attached image).

` rmarkdown:render(inputfile.Rmd, "html_document")`

I've tried with all the bootstrap themes and the result is the same.

This is the header of my Rmd file:

```
---
title: 'test tile'
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    fig_caption: yes
    fig_height: 13
    fig_width: 18
    highlight: tango
    keep_md: no
    number_sections: yes
    theme: cosmo
    toc: yes
  pdf_document:
    fig_height: 13
    fig_width: 18
    toc: yes
params:
  cnid:
    value: no
  opts:
    value: no
---

{r setup, include=FALSE, echo=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(fig.path='Figs/', dpi=72, echo=TRUE, warning=FALSE, message=FALSE, cache=FALSE, linewidth=80)
```
![center](https://cloud.githubusercontent.com/assets/2011448/18269234/87328b3c-7427-11e6-9f0d-9d0b175b839a.png)

**Comment by jgm** [comment]
I suggest you report this first to RMarkdown.
If they determine it's a problem with pandoc, it can be
escalated here with information about how to reproduce the
problem using pandoc alone.  Until then we assume the
problem is elsewhere.
