### ISSUE TITLE
Conversion of tex -> html does not preserve figure references

### ISSUE THREAD

**Issue by JBorrow** [jgm/pandoc#3110]
Hi all, could already have been a raised issue but I could not find it.

When converting TeX->HTML, figure references are not preserved (they are instead rendered as if they were markdown).

Currently tested on:
- pandoc 1.12.4.2 (deb)
- pandoc 1.17.2 (fedora)

Here's a minimal example:

```
\usepackage{graphicx}
\begin{document}

\begin{figure}
    \includegraphics{test.png}
    \caption{A figure}
    \label{fig:test}
\end{figure}

\end{document}

The above is a figure, with figure label \ref{fig:test}.
```

Then I run:

```
pandoc test.tex -o test.html
```

Output:

```
<div class="figure">
<img src="test.png" alt="A figure" /><p class="caption">A figure</p>
</div>
<p>[fig:test]</p>
<p>The above is a figure, with figure label [fig:test].</p>
```

Perhaps (most likely) this is a user error, but if not then this is certainly something to be fixed.

Expected behaviour: output would look something like this:

```
<div class="figure" id="fig:test">
<img src="test.png" alt="A figure" /><p class="caption">Figure 1: A figure</p>
</div>
<p>The above is a figure, with figure label <a href="#fig:test">1</a>.</p>
```

If this is my fault (which I am expecting it is) then adding figures like this should definitely be added to the docs.

**Comment by JBorrow** [comment]
I think this is an issue with the LaTeX reader...
```
\begin{figure}
	\includegraphics{test.png}
	\caption{A caption}
	\label{fig:test}
\end{figure}

\ref{fig:test}
```
(LaTeX) gets read to
```
[Para [Image ("",[],[]) [Str "A",Space,Str "caption",Span ("",[],[("data-label","fig:test")]) []] ("test.png","fig:")]
,Para [Str "[fig:test]"]]
```
whereas
```
![A caption](test.png){#fig:figtest}

[@fig:figtest]
```
(markdown) gets read to
```
[Para [Image ("fig:figtest",[],[]) [Str "Figure",Space,Str "1:",Space,Str "A",Space,Str "caption"] ("test.png","fig:")]
,Para [Str "fig.\160\&1"]]
```
(using the pandoc-crossref filter as well).

This is with ```pandoc 1.17.2``` and ```pandoc-crossref 0.2.2.1```.

**Comment by jgm** [comment]
A LaTeX label isn't the same as a hyperlink anchor (which is
what the id attribute corresponds to)...

**Comment by JBorrow** [comment]
Hmm, I understand that this is slightly different behavior -- but surely the expected output is the same? People label things so they can be referred to later, just like they do in markdown/html -- just in slightly different ways.

I would expect that references/labels get output to markdown so they could be read by crossref, so \ref{test} -> [@test], etc.

**Comment by jgm** [comment]
+++ Josh Borrow [Sep 12 16 12:19 ]:
>   I would expect that references/labels get output to markdown so they
>   could be read by crossref, so \ref{test} -> [[1]@test], etc.

This would require pandoc to implement its own internal
figure numbering system.  As LaTeX demonstrates, this can
get complicated (you can number figures 2.3, 2.4, IV.2,
or just 3, and so on).

I do agree that getting more uniformity here would be good,
but it's non-trivial to implement the functionality of
the flexible LaTeX label/ref system in pandoc.

**Comment by JBorrow** [comment]
Yes, after looking at the codebase myself it would require quite some work... What you would need to do is have the parser 'recognise' that the labels are inside figure environments, etc.

Either way, here is a python module that I have been writing to (somewhat) help with this: https://github.com/JBorrow/latex-pandoc-preprocessor

It is by no means perfect but gets the job done pretty well.

**Comment by mb21** [comment]
I believe this can be closed in favour of https://github.com/jgm/pandoc/issues/813
