### ISSUE TITLE
Commented out \begin and \end commands error

### ISSUE THREAD

**Issue by michaeljklein** [jgm/pandoc#3113]
Here's the tex file:

```
\begin{document}

\begin{eqnarray}
%\end{eqnarray}
%\begin{eqnarray}
\end{eqnarray}

\end{document}
```

Error occurs with following command on current master branch:

```
pandoc -f latex -t latex -o test.pdf err.tex 
```

The error is:

```
pandoc:
Error at "source" (line 6, column 15):
expecting \end{document}
\end{eqnarray}
              ^
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Error.hs:66:13 in pandoc-1.17.2-8Q2NQjhudZY88M6ytu5K2R:Text.Pandoc.Error
```

(No error when commented lines are removed.)

**Comment by jkr** [comment]
Confirmed. @jgm -- it seems like `verbEnv` in the LaTeX reader isn't comment-aware. I'll try to figure it out, but I'm not too acquainted with the reader.

**Comment by jgm** [comment]
Real verbatim environments don't recognize comments.

The problem is our using `verbEnv` as a shortcut in the
definition of `mathEnv`.

We could try usingd6d `rawEnv` for this (or rather
`snd <$> withRaw rawEnv`.  But I think this might not work
in all cases, because of the way math environments can
redefine symbols.

We probably need something that just gobbles raw content
inside the environment, skipping comments and allowing for
the possibility of nested environments.

+++ Jesse Rosenthal [Sep 08 16 18:06 ]:

**Comment by jkr** [comment]
Would something as simple as this work? (Assuming we rename it or put a boolean flag on to preserve real verbatim behavior when we want it.)

~~~{.haskell}
verbEnv :: String -> LP String
verbEnv name = do
  skipopts
  optional blankline
  let endEnv = try $ controlSeq "end" *> braced >>= guard . (== name)
  res <- manyTill ((many comment) *> anyChar) endEnv
  return $ stripTrailingNewlines res
~~~

All tests pass with it, and the reported bug appears to be fixed. So with a boolean, it would be something like

~~~{.haskell}
verbEnv :: Bool -> String -> LP String
verbEnv ignoreComments name = do
  skipopts
  optional blankline
  let endEnv = try $ controlSeq "end" *> braced >>= guard . (== name)
      charMuncher = if ignoreComments
                    then (many comment) *> anyChar
                    else anyChar
  res <- manyTill charMuncher endEnv
  return $ stripTrailingNewlines res
~~~

**Comment by jkr** [comment]
"ignore" is ambiguous -- `skipComments` would be better, but you get the idea.

**Comment by jgm** [comment]
No, that's too simple, at least if one eqnarray can contain
another (since you'd stop at the end for the inner one).

**Comment by jkr** [comment]
Oh, right.
