### ISSUE TITLE
Convert and maintain code chunks

### ISSUE THREAD

**Issue by jebyrnes** [jgm/pandoc#3118]
Would it be possible for pandoc to handle code chunks in different formats? For example, in a LaTeX file, I have the following code chunk:

```
<<r agraph, echo=FALSE>>=
library(ggplot2)
qplot(mpg, cyl, data=mtcars)
@
```

which in markdown would be

     ```{r agraph, echo=FALSE}
     library(ggplot2)
     qplot(mpg, cyl, data=mtcars)
     ```

(this is going from a .Rnw file to an RMarkdown, .Rmd, file)

Could pandoc either recognize and preserve (as find/replace after would be easy) or properly convert code chunks between different formats?

Thanks for an amazing program!

**Comment by jgm** [comment]
Try a lstlisting environment (using the listings LaTeX package).
These allow you to specify a language (using different names
than pandoc), and pandoc will convert these to other
formats.  You can also specify arbitrary key/value
attributes using 'options' in a lstlisting environment.

+++ Jarrett Byrnes [Sep 14 16 06:06 ]:

**Comment by jebyrnes** [comment]
Do you have an example - sorry, new to pandoc, and thought this was just not possible.

**Comment by jgm** [comment]
http://texdoc.net/texmf-dist/doc/latex/listings/listings.pdf

``` latex
\begin{lstlisting}[language=R, firstline=4]
R code here...
\end{lstlisting}
```

+++ Jarrett Byrnes [Sep 14 16 06:54 ]:
