### ISSUE TITLE
Code block in notes div causes compilation error with beamer

### ISSUE THREAD

**Issue by afranke** [jgm/pandoc#3120]
I'm generating both beamer slides and handouts from the same [test.md](https://github.com/jgm/pandoc/files/474082/test.txt) Markdown file. I use divs with the "notes" class to have text that appears only on handouts and not on the slides. The two command lines I use are the following:

```
pandoc -t beamer -o slides.pdf test.md
pandoc -o slides.pdf test.md
```

I have a backtick block of code inside of a notes div and that makes the beamer compilation fail with the following error:

```
! Illegal parameter number in definition of \beamer@todo.
<to be read again> 
                   i
l.11 }

pandoc: Error producing PDF
```

**Comment by jgm** [comment]
A div with class "notes" already has special treatment in
the beamer writer.  It gets put into a `\note{...}` command,
for speaker notes during slides.

I'd suggest you use a different div class if you want to
do something custom.

+++ Alexandre Franke [Sep 15 16 01:03 ]:

**Comment by cagix** [comment]
I've written a filter to accomplish this task (see https://github.com/cagix/pandoc-lecture) ...This way you can use nearly everything within your notes.

**Comment by afranke** [comment]
> I'd suggest you use a different div class if you want to do something custom.

I don't see how what I'm doing is custom. I'm using the notes as notes.

> I've written a filter to accomplish this task

I don't see how what I'm doing should require anything more than straight pandoc.

> This way you can use nearly everything within your notes.

I haven't found any documentation that stated that you can't use specific stuff within notes. Why would that be the case?

**Comment by jgm** [comment]
>   I don't see how what I'm doing is custom. I'm using the notes as notes.

OK, I wasn't sure from your message.

Because speaker notes go in a LaTeX command, not an
environment, there are some limits to what can go inside
them.  You can't, for example, have multiple paragraphs.

**Comment by cagix** [comment]
In the past I experienced some difficulties regarding the `\notes{}` command in beamer, i.e. using it for arbitrary tex code like lstlistings or sections was not supported ... As far as I can see, this seems to be just the case in your example.

So I'm using my own `\beginnotes` and `\endnotes` commands to enclose lecture notes which should not appear on beamer slides but in the handout.   
* For beamer, the filter removes the commands and everything in between from the AST.    
* For handout, I just declare this commands void, like `\newcommand{\notesbegin}{}`.

**Comment by cagix** [comment]
A nice side effect of using dummy commands is that pandoc  parses the markdown in between (as opposed to using an environment).

**Comment by afranke** [comment]
>  You can't, for example, have multiple paragraphs.

Really? I have examples where it works here.

**Comment by jgm** [comment]
+++ Alexandre Franke [Sep 15 16 03:33 ]:
>     You can't, for example, have multiple paragraphs.
>
>   Really? I have examples where it works here.

OK. Not sure.  But there are definitely things in LaTeX
that can go inside environments but not commands, so I
suspect that might be the root problem.  In any case,
it seems a beamer issue, not a pandoc problem.  I don't
see any way pandoc should be behaving differently, but
if you have something concrete to suggest, please do.
