### ISSUE TITLE
Incorrect LaTeX translation

### ISSUE THREAD

**Issue by charpov** [jgm/pandoc#3121]
This markdown:

``` `` `How are you?` `` ```

is incorrectly translated in LaTeX.  Instead of the verbatim text, it results in an upside-down question mark.

**Comment by jgm** [comment]
Here's what I get (which looks correct):

% pandoc -t latex
`` `How are you?` ``
^D
\texttt{`How\ are\ you?`}

Do you get something different from this?

**Comment by charpov** [comment]
But what does it look like once you process the LaTeX into pdf?

**Comment by jgm** [comment]
+++ Michel Charpentier [Sep 18 16 05:05 ]:
>   But what does it look like once you process the LaTeX into pdf?

OK, I see what you're talking about.

Apparently `` ?` `` is a LaTeX ligature for the
upside-down-question-mark symbol.

If you use `--latex-engine=xelatex`, it avoids the problem.

The fix in pandoc would be to do something that prevents
backticks inside code literals from forming ligatures.

**Comment by jkr** [comment]
Seems like the most standard way to suppress ligatures in LaTeX is to insert an empty pair of brackets:

    \texttt{`How\ are\ you?{}`}

See some discussion [here](http://tex.stackexchange.com/questions/106487/difference-between-and-for-breaking-ligatures)

Not sure what the best general rule would be, though? In front of all verbatim backticks?

**Comment by jgm** [comment]
We could also simply include verbatim backticks inside {`}.

+++ Jesse Rosenthal [Sep 19 16 03:30 ]:

**Comment by jkr** [comment]
Would that be as simple as adding 

~~~{.latex}
case x of
   [...]
   '`' | ctx == CodeString -> "{`}" ++ rest
~~~

to `stringToLaTeX` in the writer? That seems to be the only route to `\texttt{..}`.

**Comment by jgm** [comment]
Yes, I think that would do it!

+++ Jesse Rosenthal [Sep 19 16 06:39 ]:

**Comment by jkr** [comment]
Cool -- I'll do that and add a test.

**Comment by jgm** [comment]
Make sure to check the resulting PDF too -- I am just
assuming this will work!

+++ Jesse Rosenthal [Sep 19 16 13:21 ]:

**Comment by jkr** [comment]
Yes, I checked -- it works fine.

There's still the standard problem with backticks in verbatim environments: they render as open-single-quotes. It doesn't look like there's any simple way to deal with this that doesn't require adding extra package dependencies or preamble code (see discussion [here][1]).

[1]: http://tex.stackexchange.com/questions/63353/how-to-properly-display-backticks-in-verbatim-environment

**Comment by jgm** [comment]
Note that we handle this for ' by escaping it as
\textquotesingle{} in verbatim environments.
Could we do something similar for `?

+++ Jesse Rosenthal [Sep 20 16 05:39 ]:

**Comment by jkr** [comment]
There's \textasciigrave{}, but's in textcomp.

Actually 

~~~
\`{}
~~~

seems to work. Let met test it in xetex and luatex, and see if it carries through all three.

**Comment by jkr** [comment]
Yep 

~~~
\`{}
~~~

compiles as we'd hope in all three.

**Comment by jkr** [comment]
Actually -- now that I look at it, \textquotesingle requires textcomp as well. So maybe \textasciigrave after all? It's more explicit, and more symmetrical.

**Comment by jgm** [comment]
See https://github.com/jgm/pandoc/issues/638

We already include the upquote package, if available. It which provides both
of these I think.

+++ Jesse Rosenthal [Sep 20 16 06:01 ]:

**Comment by jkr** [comment]
Okay, so `\textasciigrave{}` is the way to go. It produces identical (and correct) output with all three engines.
