### ISSUE TITLE
Relative images not loaded when creating epub

### ISSUE THREAD

**Issue by Lambik** [jgm/pandoc#3122]
Hi,

I just installed pandoc from ubuntu's apt-get, and tried this command:

    pandoc -s --toc -o test.epub -r html 'http://www.squidi.net/three/entry.php?id=1'

The output does not contain the images. Maybe because they are relative (like `<img src='set01/img/entry001-illusion.gif' alt='[illusion.gif]'>`)?

The errors I see are:

```
pandoc: Could not find media `poster/poster001.png', skipping...
pandoc: Could not find media `set01/img/entry001-illusion.gif', skipping...
(and so on for the other images)
```

I've tried adding the `--self-contained` option, but that doesn't seem to work (probably because it's epub output).

Is there an issue in the site, or in pandoc?

**Comment by jgm** [comment]
I just noticed you said apt-get.  It's probably a very old
version.  I just tried with current pandoc, and it found all
the images, so I think you can close this.  Try installing
the deb from our github release page.

+++ Tom Muylle [Sep 20 16 07:34 ]:

**Comment by Lambik** [comment]
I'll have to upgrade to 64 bit first then (apt-get version is 1.16.0.2 btw). I'll close the issue since you can just run the command correctly. Thanks for looking into it!
