### ISSUE TITLE
Raw PHP in markdown

### ISSUE THREAD

**Issue by mhlinder** [jgm/pandoc#3123]
I am trying to inject some php into an otherwise-static page, but --parse-raw and markdown_in_html_blocks do not directly address this, and indeed nor do they resolve it:

```
$ echo '<?php echo 1; ?>' | pandoc -f markdown -t html
<?php echo 1; ?>
$ echo '<?php echo "1"; ?>' | pandoc -f markdown -t html
<p>&lt;?php echo &quot;1&quot;; ?&gt;</p>
```

What seems to break this is the inclusion of quotes—which is necessary for, eg, a call to `include`.

**Comment by mhlinder** [comment]
This issue boils down to:

`--parse-raw` will mistake raw PHP containing no quotation marks for valid-but-untranslateable HTML. But raw PHP containing double quotes is correctly flagged as invalid HTML, so that it is treated as literal text that must substitute HTML entities for raw characters like `&`, `>`, `<`.

Short of implementing a separate writer for PHP, one fix would be the option to write invalid HTML by disabling conversion to entities (see also, eg, [Issue 2756](https://github.com/jgm/pandoc/issues/2756)).

**Comment by jgm** [comment]
Can you give a short example?
Also, what version of pandoc are you using?

+++ M. Henry Linder [Sep 20 16 19:05 ]:

**Comment by jgm** [comment]
Sorry, I see the example now (reading mail backwards).

**Comment by jgm** [comment]
I think that this is fixed in the most recent version of pandoc.
```
% echo '<?php echo "1"; ?>' | pandoc 
<?php echo "1"; ?>
```

**Comment by mhlinder** [comment]
Right on, that was it...thanks

**Comment by mhlinder** [comment]
Hi,

This issue was resolved because at the time, I had been running an old version of pandoc.

It appears this has broken again, could we please reopen this issue?

**Comment by jgm** [comment]
This seems to have broken some time between 1.19.2.1 (works) and 2.0.6 (doesn't work).
Need to look at the 2.0 changelog for changes that might have broken this.
It could also have something to do with changes to the tagsoup library we compile against.

**Comment by mb21** [comment]
This time seems to be the HTML write:

    echo '<?php echo "1"; ?>' | pandoc -t native    
    [Para [Str "<?php",Space,Str "echo",Space,Quoted DoubleQuote [Str "1"],Str ";",Space,Str "?>"]]

**Comment by jgm** [comment]
Fixed.

**Comment by mhlinder** [comment]
Thank you!
