### ISSUE TITLE
Nested list in quote environment does not work

### ISSUE THREAD

**Issue by davtorgh** [jgm/pandoc#3125]
Nested item list, when used in a `quote` environment, does not get nested. The items are all aligned at the first level.

Example markdown source:
```markdown
Here it is an item list:

 * item 1;
 * item 2;
    * subitem 1;
 * item item 3;
 * item 4.

This is another paragraph, with a quoted item list.

>* item 1;
> * item 2;
>    * subitem 1;
> * item item 3;
> * item 4.
```
and this is the latex output:
```tex
Here it is an item list:

\begin{itemize}
\tightlist
\item
  item 1;
\item
  item 2;
  \begin{itemize}
  \tightlist
  \item
    subitem 1;
  \end{itemize}
\item
  item item 3;
\item
  item 4.
\end{itemize}

This is another paragraph, with a quoted item list.

\begin{quote}
\begin{itemize}
\tightlist
\item
  item 1;
\item
  item 2;
\item
  subitem 1;
\item
  item item 3;
\item
  item 4.
\end{itemize}
\end{quote}
```
@jgm As you can see, tha latex code generated in the "quoted" case is incorrect, because there is not the inner `\begin{itemize} ... \end{itemize}` to nest "subitem 1".

**Comment by jkr** [comment]
This is expected, if somewhat annoying, behavior. You're encountering the intersection of two rules:

1. There can be an optional space after a block-quote marker (`"> " == ">"`)

2. You need four spaces to produce a new list level (the "four-space rule")

So when you append block-quotes to these list items which have a space before them, the space after the `>` gets eaten, and the the inner list is only indented  by three spaces.

It would be nice if you could just append a block quote and have it work as expected, but I'm not sure there's a way with the four-space rule in effect.

BTW, commonmark's list-handling (which moves away from the four-space rule) seems to address this particular case, so somewhere in the future it will probably be a solved problem.

**Comment by jkr** [comment]
I forgot to mention: the upshot of all this is that adding an extra space to the indentation of the inner list takes care of the problem.

**Comment by davtorgh** [comment]
Thank you for the explanation @jkr and for the suggested workaround. It works.
I close the issue.
