### ISSUE TITLE
[Feature Request] Preprocess recursively defined YAML variable references

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#3126]
# Background

[YAMLP](https://bitbucket.org/djarvis/yamlp) is a pre-processor related to issue #1950. Given a YAML file with delimited variable references such as (`variables.yaml`):

    ---
    a: A
    b: $a$ B
    c: $b$ C $b$
    ...

YAMLP writes new YAML file to standard output with the references substituted using corresponding YAML path values from within the document:

    ---
    a: A
    b: A B
    c: A B C A B
    ...

The [algorithm](https://bitbucket.org/djarvis/yamlp/src/master/src/main/java/com/whitemagicsoftware/yamlp/Main.java?fileviewer=file-view-default#Main.java-227) that performs this feat is relatively [trivial](https://bitbucket.org/djarvis/yamlp/src/master/src/main/java/com/whitemagicsoftware/yamlp/Main.java#Main.java-268).

The output from YAMLP can then be used by pandoc:

    java -jar yamlp.jar --input variables.yaml > v.yaml
    pandoc --template v.yaml filename.md ...

# Request

I'd like to eliminate YAMLP from my tool chain, if possible. That is, it would be great if pandoc could support the following:

    pandoc --dereference-variables --template variables.yaml filename.md

Where `--dereference-variables` causes pandoc to first perform a recursive replacement of all variables within `variables.yaml` before it begins processing the Markdown file.

# Bonus Request

YAMLP also has options to show when delimited references (e.g., `$a$`) refer to non-existent values. My understanding is that this is difficult to do with the way pandoc is currently implemented. If the pre-processing happened before any other behaviour, then it might be possible to "shim" this feature as I've shown with the code for YAMLP.

**Comment by nichtich** [comment]
This can be done [with a filter](http://pandoc.org/scripting.html), let it be named `expandmetavars` and executed this way:

    pandoc --filter expandmetavars variables.yaml filename.md

Add options `-s -t markdown` to see expanded variables. Here is an implementation based on [Pandoc::Elements](https://metacpan.org/release/Pandoc-Elements):

~~~perl
#!/usr/bin/env perl
use v5.14;

use Pandoc::Filter;
use Pandoc::Elements;

my $doc = pandoc_json(<STDIN>);
my $filter = Pandoc::Filter->new(
    Math => sub { # $...$
        my ($e, $f, $m) = @_;
        my $var = $m->{$e->content} or do {
            print STDERR "variable in meta not found: ".$e->content."\n";
            return; # skip if name not found
        };
  
        return Str $var->string;
    }
);
$filter->apply( $doc->meta, shift(@ARGV) // '', $doc->meta );
say $doc->to_json;
~~~

**Comment by DaveJarvis** [comment]
@nichtich:

    pandoc --filter rexpansion.pl variables.yaml -s -t markdown

Returns with an error:

    pandoc: Error running filter rexpansion.pl
    fd:4: hClose: resource vanished (Broken pipe)

```
$ pandoc --version
pandoc 1.16.0.2
```

Any ideas?

**Comment by DaveJarvis** [comment]
Looks like `Pandoc::Filter` wasn't installed:

1. cpan App:cpanminus
1. cpanm Pandoc::Filter

After running the filter, it looks great:

```
$ cat v.yaml 
---
a: A
b: $a$ B
c: $b$ C $b$
...
$ cat f.md 
# Hello

Testing, $c$.
$ pandoc --filter rexpansion.pl v.yaml -s -t markdown --template f.md
# Hello

Testing, A B C A B.
```

**Comment by nichtich** [comment]
Looks like the filter cannot actually work as expected because YAML fields have no order. So this

~~~yaml
---
c: $b$ C $b$
b: $a$ B
a: A
...
~~~

is equivalent to any other oder of fields a, b, c. Sure one can write a working filter with the given algorithm but I don't have the time right now. Anyway, Pandoc filters can be written in any programming language so this is doable. I just doubt that the feature will every directly be implemented in Pandoc, so this issue could be closed.

**Comment by trenkert** [comment]
Just for reference: pandoc-mustache does something like this https://github.com/michaelstepner/pandoc-mustache/
