### ISSUE TITLE
markdown table breaks last column prematurely

### ISSUE THREAD

**Issue by rajinder-yadav** [jgm/pandoc#3129]
The following markdown: (normal markdown and github markdown formats).

<pre>
|Param Type|Description|Usage|
|-----|-----------|-----|
|error |Should be named err| |
|in    |Prefix arg with 'i_'|void foo( const int i_count )|
|out   |Prefix arg with 'o_'|void bar( char& o_address, size_t& o_size )|
|in/out|Param prefix arg with 'd_'|void fetch( char& o_buffer, int& d_size )|
</pre>

Should look like this:

|Param Type|Description|Usage|
|-----|-----------|-----|
|error |Should be named err| |
|in    |Prefix arg with 'i_'|void foo( const int i_count )|
|out   |Prefix arg with 'o_'|void bar( char& o_address, size_t& o_size )|
|in/out|Param prefix arg with 'd_'|void fetch( char& o_buffer, int& d_size )|

However the actual output is like this:
![table](https://cloud.githubusercontent.com/assets/439226/18811821/817819fa-828c-11e6-891c-8c26483162df.png)

**Comment by jgm** [comment]
Please read the pandoc manual to see how relative column
widths are determined, when pipe tables have long cells.

You can use `--columns=N` with an N greater than the default
80, or make your underline bar longer in the last column.

+++ Rajinder Yadav [Sep 24 16 16:26 ]:

**Comment by jgm** [comment]
And of course you can use CSS to apply the styles you like (borders, odd/even shading, etc.)

**Comment by rajinder-yadav** [comment]
John, thanks for the info!

Wondering if it's possible for make pandoc smart enough to figure out column width based on the characters and font being used? This would be a nice default behavior, possibly pass a switch to enable this so it won't break existing expected behavior. Would be a nice enhancement.

**Comment by jgm** [comment]
+++ Rajinder Yadav [Sep 26 16 06:58 ]:
>   John, thanks for the info!
>
>   Wondering if it's possible for make pandoc smart enough to figure out
>   column width based on the characters and font being used? This would be
>   a nice default behavior, possibly pass a switch to enable this so it
>   won't break existing expected behavior. Would be a nice enhancement.

Not possible, because of the separation between readers
(parsers) and writers (renderers).

The parser assigns a column width based on the source
document.  It doesn't know what font will be used for
rendering.

**Comment by rajinder-yadav** [comment]
I see, ok cool. Closing issue, thank you!
