### ISSUE TITLE
Put citations in a class of their own

### ISSUE THREAD

**Issue by nomeata** [jgm/pandoc#313]
It seems that this can neither be achieved by mangling the Pandoc nor the resulting Html, so I guess pandoc needs to be extended:

I’d like to be able to change the style of references in the HTML output. Therefore, I’d need `Text.Pandoc.Writers.HTML` to put the citation in a <span class="cite"> tag.

Additionally, setting an id like id="cite-<citation Id>" would enable some javascript to make nice jumps to and from the reference, as it does on Wikipedia, or fetch the reference while hovering to show a pop-up.

Thanks,
Joachim

**Comment by jgm** [comment]
I think this can be closed now, mpickering's patch was merged long ago.
