### ISSUE TITLE
Embedded html

### ISSUE THREAD

**Issue by charpov** [jgm/pandoc#3130]
I'm getting a weird output on this markdown with embedded html:

```
foo

<span><script>
  code
</script></span>

bar
```

I'm getting `<p></span></p>` instead of the closing span tag, which doesn't seem right.

**Comment by jgm** [comment]
Pandoc version?  With the latest from HEAD, I get

    foo

    <span><script>
      code
    </script></span>

    bar

+++ Michel Charpentier [Sep 25 16 18:28 ]:

**Comment by charpov** [comment]
It's 1.17.2, the most recent I can get using homebrew on macOS.

**Comment by jgm** [comment]
What exact command are you using to convert?

+++ Michel Charpentier [Sep 26 16 04:47 ]:

**Comment by charpov** [comment]
Just `pandoc test.md` where `test.md` is the file I showed above.

**Comment by jgm** [comment]
Okay, yes, I can reproduce it now (not sure why I couldn't before).

**Comment by jgm** [comment]
Basic problem is that pandoc always treats script tags as block-level; you can't have them as inline HTML inside a paragraph.  Ideally this would change but it requires a bit of subtlety.

**Comment by charpov** [comment]
I need my `<script>` to be inside `<span>`.  Any way to achieve that?

**Comment by jgm** [comment]
Put `<p>` tags around the whole thing.  Then it will all come through literally as an HTML block.
Or, if you don't want p tags, use `<div>` tags.

**Comment by charpov** [comment]
Perfect!

**Comment by vyp** [comment]
> Basic problem is that pandoc always treats script tags as block-level

Aren't they technically inline elements though?

**Comment by charpov** [comment]
It would make my life easier.  I had to torture my html a bit to get what I wanted:

    <div class="asSpan"><script>
      code
    </script></div>

and then use CSS to make the `div` display inline (the script inserts contents in the div when it runs).

**Comment by jgm** [comment]
+++ vyp [Sep 26 16 18:02 ]:
>     Basic problem is that pandoc always treats script tags as
>     block-level
>
>   Aren't they technically inline elements though?

It can occur as either "flow content" or "phrasing content."
For pandoc's purposes, the important thing is that script
tags don't need to be inside p tags.
