### ISSUE TITLE
aeson 1.0.1.0 problem with filters

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3131]
```
pandoc MANUAL.txt -t man -s --template man/pandoc.1.template \
		--filter man/capitalizeHeaders.hs \
		--filter man/removeNotes.hs \
		--filter man/removeLinks.hs \
		--variable version="pandoc 1.17.3" \
		-o man/pandoc.1
pandoc: Error running filter man/removeNotes.hs
Error in $.date[1]: key "c" not present
CallStack (from HasCallStack):
  error, called at pandoc.hs:153:46 in main:Main
make: *** [man/pandoc.1] Error 83
```
This probably has to do with changes to ToJSON/FromJSON instances in aeson 1.0.
Need to resolve this before release.

**Comment by jgm** [comment]
Hm, I can no longer reproduce this. Closing.

**Comment by jgm** [comment]
Ah, no doubt this is because I recompiled pandoc and it used aeson < 1.0 because of a dependency.
It is possible to compile pandoc-types with aeson 1.0.1.0, and you then get this problem using a filter with a version of pandoc that was compiled with aeson 0.11.x.  Probably due to a difference in generic serialization.

**Comment by jgm** [comment]
This appears to be the difference:
pandoc with aeson < 1.0
```
{"t":"Space","c":[]}
```
pandoc with aeson > 1.0
```
{"t":"Space"}
```

**Comment by jgm** [comment]
Here's the relevant changeling note in aeson 1.0.0.0:
```
Remove the contents field encoding with allNullaryToStringTag = False, giving us { "tag" : "c1" } instead of { "tag" : "c1", contents : [] }. The contents field is optional when parsing so this is only a breaking change for ToJSON instances.
```

**Comment by jgm** [comment]
So now we face a choice.  Should we modify pandoc-types so that the old behavior is restored?  This would avoid problems when the pandoc executable is compiled against a different version of aeson than the filter.  Or should we just go with the new (otherwise better) behavior, and tell people to make sure they compile filters against the same version of aeson as pandoc itself?

**Comment by jgm** [comment]
Unfortunately I don't see a way to restore the old behavior.  So I think we're stuck with option 2.

**Comment by jkr** [comment]
A while back you speculated about  writing explicit {To/From}JSON instances instead of deriving. It still seems like that would be a good idea -- it would make aeson's occasional erratic nature would be less of an issue. Of course, that assumes we could decide on a good json spec.

**Comment by jgm** [comment]
Yes.  This would be better, since otherwise we have no
consistent JSON format (it depends on which version
of aeson we compile against).

I'm just not sure how much work it would be.  Maybe not
that much?  The easiest spec would just follow current
behavior, which would also ease backwards compatibility.
Maybe there's reason not to do that, though?

+++ Jesse Rosenthal [Sep 27 16 09:50 ]:

**Comment by jkr** [comment]
John MacFarlane <notifications@github.com> writes:

> I'm just not sure how much work it would be.  Maybe not
> that much?  The easiest spec would just follow current
> behavior, which would also ease backwards compatibility.
> Maybe there's reason not to do that, though?

It wouldn't be very much work -- a bit of boilerplate, and cutting and
pasting, but pretty straightforward. I guess a spec that follows current
behavior would be the easiest. I occasionally wish it were a bit more
human-reader-friendly, but I guess that's what native format is for.

Beyond readability, I guess the only reason to change things would be if
it made life easier for filter-library maintainers. That would probably
be a conversation for the mailing list.

In any case, I'll try to whip up a version that follows current
behavior, and is backwards-compatible. It will be easy enough to change
should we ever want to break compatibility. I'll submit a PR to
pandoc-types when I'm done.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Sep 27 16 18:28 ]:
>   John MacFarlane <notifications@github.com> writes:
>   > I'm just not sure how much work it would be. Maybe not
>   > that much? The easiest spec would just follow current
>   > behavior, which would also ease backwards compatibility.
>   > Maybe there's reason not to do that, though?
>   It wouldn't be very much work -- a bit of boilerplate, and cutting and
>   pasting, but pretty straightforward. I guess a spec that follows
>   current
>   behavior would be the easiest. I occasionally wish it were a bit more
>   human-reader-friendly, but I guess that's what native format is for.

I'd be happy for it to be more human-friendly.  This would
break backwards compatibility, though, so existing filters
wouldn't work or would have to be rewritten.

If we're thinking of this, we might also think of adding
version information to the JSON output.
https://github.com/jgm/pandoc/issues/2640

If we do this, we should write the ToJSON and FromJSON
instances in such a way that the version info doesn't become
part of the metadata.

>   In any case, I'll try to whip up a version that follows current
>   behavior, and is backwards-compatible. It will be easy enough to change
>   should we ever want to break compatibility. I'll submit a PR to
>   pandoc-types when I'm done.

Great!

**Comment by tarleb** [comment]
It might also be worth to keep #2925 (Highlight Style In YAML) and #3060 (Allow setting `reference-docx` in YAML front matter) in mind, although those would require bigger architectural changes.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Sep 28 16 00:55 ]:
>   It might also be worth to keep [1]#2925 (Highlight Style In YAML) and
>   [2]#3060 (Allow setting reference-docx in YAML front matter) in mind,
>   although those would require bigger architectural changes.

I don't think either of these would require changes to
pandoc-types.

All that's really needed is to have a conventional place for
these in the metadata, and look at this before calling the
writer.

Still, I'm a bit reluctant to go into this territory; it
seems we might want to rethink more thoroughly.

Another thing we might think about now is
a mechanism for including literal strings in metadata.
https://github.com/jgm/pandoc/issues/2139
This is a frequent request.

**Comment by tarleb** [comment]
>  All that's really needed is to have a conventional place for these in the metadata, and look at this before calling the writer.

My reasoning here was that it would be nice to separate pandoc and pandoc-types version information.  I think it would be beneficial to have pandoc options separate from other metadata as this would offers filters a cleaner interface.  If we allow filters to set pandoc options, those filters should be informed of interface changes, which might be independent from pandoc-types changes.

I guess my point is that `Pandoc` (the type) serialization could be extended with `pandoc` (the program/library) information, where the latter contains the former.  But I may very well be misunderstanding something.

**Comment by jkr** [comment]
I've written a first stab at it. There's a lot of boilerplate that could
probably be passed over with generic things like `toConstr`, but I did
it explicitly to keep it as flexible as possible.

It's here: https://github.com/jkr/pandoc-types/tree/newJSON

Before we merge it or consider fiddling with the format, though, it
would be nice to be able to test it, especially with quickcheck
arbitrary encode-decode roundtrips. Problem is that all of the arbitrary
instances are in pandoc.

@jgm, what would you think about moving the arbitrary instances for
things defined in pandoc-types into pandoc-types? We could then import
these instances in the test suite for pandoc.

The main downside that I see is that it makes -types dependent on
quickcheck. But I'm not sure that actually adds much in the way of build
dependencies, since it looks like aeson brings in a lot of the same
ones.

**Comment by jkr** [comment]
Oh, and as far as version info goes, right now the toplevel JSON format is a two-element list (`[meta, blocks]`). So if we wanted didn't want to mess with anyone's scripts, we could just add the version info as  third element.  

My preference, though, would probably be to make the toplevel JSON an object:

~~~{.json}
{
   "pandoc-api-version": "1",
   "meta" : META,
   "blocks" : BLOCKS
}
~~~

or 

~~~{.json}
{
  "pandoc-api-version": "1",
  "document": OLD_PANDOC_JSON
}
~~~

I prefer the first one, because I don't really like having structure defined by location in a list, but the second one would be a bit easier for backwards-compatibility.

**Comment by jgm** [comment]
>   @jgm, what would you think about moving the arbitrary instances for
>   things defined in pandoc-types into pandoc-types? We could then import
>   these instances in the test suite for pandoc.

I think I'd be fine with that.

**Comment by jgm** [comment]
>{
>   "pandoc-api-version": "1",
>   "meta" : META,
>   "blocks" : BLOCKS
>}
>
>   or
>
>{
>  "pandoc-api-version": "1",
>  "document": OLD_PANDOC_JSON
>}

I agree, first is better than the second.
Either will require changes to existing filters,
so we might as well use the cleaner one.

I'd suggest using an array of integers for the
version; this would make comparisons easier.

**Comment by jkr** [comment]
John MacFarlane <notifications@github.com> writes:

>>   @jgm, what would you think about moving the arbitrary instances for
>>   things defined in pandoc-types into pandoc-types? We could then import
>>   these instances in the test suite for pandoc.
>
> I think I'd be fine with that.

It occurs to me that moving anything for pandoc to pandoc-types requires
an implicit relicensing of the code. John, git-blame says it's
Test.Pandoc.Arbitrary is all you, but I guess it's worth checking
whether it is, to the best of your knowledge, and whether you're okay
with the relicensing.

**Comment by jkr** [comment]
what should the first api version be? [1,0,0]? [3,0,0] because it's the 3rd version or so of the JSON format? [0,0,1] because it's good to start small?

**Comment by jkr** [comment]
A couple more things to consider (the first question is small, the
second one is big).

1. Leaf elements (Space, HorizontalRule, etc) currently have the
following form: `{"t": "Space", "c": []}`. This has the virtue of
consistency, but it would certainly be easier on the eyes if we
dispensed with the "c" element altogether in these elements: {"t":
"Space"}, {"t": "HorizontalRule"}. (Basically, everywhere in
Definition.hs where you see an Aeson.emptyArray.)

2. In general, is the current {"t": TYPE, "c": CONTENT} two-element
array the best way to represent a pandoc element?  For example, we could
make it into a one-element object:

    1a. {"t": "Str", "c": "Hello"}
    1b. {"Str": "Hello"}

    2a. {"t":"Para","c":[{"t":"Emph","c":[{"t":"Str","c":"wow"}]}]}
    2b. {"Para": [{"Emph": [{"Str": "wow"}]}]}

    3a. {"t": "Space", "c": []}
    3b. {"Space": null} 

For a human reader, the second seems far superior. But I'm not sure if
there are some flaws there that make it less friendly for a parser.

**Comment by jkr** [comment]
Following up on the above: after writing the majority of an implementation of the second (easier-to-read?) version, my sense is that it does make it harder for lib writers, who are the only people who really *need* to see it. Instead of just asking for a type (or "t") and proceeding accordingly, you have to do some ad-hoc version of pattern-matching in a language that doesn't support it, using try:/except: or the like.

I think the best thing to do would be to write to the list asking if lib writers have any bees in their bonnets about the current format. Ultimately, since I write my filters in haskell, it's all of academic interest to me only.

**Comment by jgm** [comment]
Yes, I'm okay with it.

**Comment by jgm** [comment]
I was thinking the version would just be identical to the
pandoc-types version.  Is there a reason not to do it this
way?

+++ Jesse Rosenthal [Sep 28 16 14:18 ]:

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Sep 28 16 14:48 ]:
>   1. Leaf elements (Space, HorizontalRule, etc) currently have the
>   following form: `{"t": "Space", "c": []}`. This has the virtue of
>   consistency, but it would certainly be easier on the eyes if we
>   dispensed with the "c" element altogether in these elements: {"t":
>   "Space"}, {"t": "HorizontalRule"}. (Basically, everywhere in
>   Definition.hs where you see an Aeson.emptyArray.)

This is exactly what happens when you compile pandoc-types
against aeson 1.0.  This is what prompted this issue in the
first place, since it is a potential compatibility problem.

I agree, this looks better, so if we're breaking
compatibility anyway we might as well go with this.

>   2. In general, is the current {"t": TYPE, "c": CONTENT} two-element
>   array the best way to represent a pandoc element? For example, we could
>   make it into a one-element object:
>   1a. {"t": "Str", "c": "Hello"}
>   1b. {"Str": "Hello"}
>   2a. {"t":"Para","c":[{"t":"Emph","c":[{"t":"Str","c":"wow"}]}]}
>   2b. {"Para": [{"Emph": [{"Str": "wow"}]}]}
>   3a. {"t": "Space", "c": []}
>   3b. {"Space": null}

I think it's a bit easier to use the t/c style when you're
looking at this in a program.  You can iterate over elements
and check element.t to see the type.  If the elements are
objects, it's more awkward.

Another option would be to use arrays:

    ["Str", "Hello"]
    ["Emph", [["Str", "Hello"], ["Space"], ["Str", "there"]]]
    ["Space"]
    etc.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Sep 29 16 06:33 ]:
>   Following up on the above: after writing the majority of an
>   implementation of the second (easier-to-read?) version, my sense is
>   that it does make it harder for lib writers, who are the only people
>   who really need to see it. Instead of just asking for a type (or "t")
>   and proceeding accordingly, you have to do some ad-hoc version of
>   pattern-matching in a language that doesn't support it, using
>   try:/except: or the like.

Yep.  That was exactly the reason for using the t/c version.

**Comment by jkr** [comment]
John MacFarlane <notifications@github.com> writes:

> I was thinking the version would just be identical to the
> pandoc-types version.  Is there a reason not to do it this
> way?

No, I guess not. My main thought was that there could be breaking
changes in the JSON format without there being any changes in the type
itself. But I guess in that case, the change in the JSON format would
necessitate a change in the types minor version. 

So, I had been thinking that given (MAJOR.MINOR.FIX) he same MAJOR would
mean filters should still work. But we could probably do the same with
the MINOR of the pandoc-api version number.

So, just for the sake of clarity: what should the compatibility-meaning
of the version in the JSON be?  Given api versions X.Y.Z and X'.Y'.Z' we
guarantee json compatibility if X==X' && Y==Y'?

**Comment by jkr** [comment]
BTW, testing with book-length document, compiling pandoc with the version at https://github.com/jkr/pandoc-types/commit/e1f29b5a12d2f68035fbf7723d55cefd680a98cc gives a ~20% increas on write speed and a ~25% increase on read speed. About half of this seems to come just from hand-writing, and the other half seems to come from dropping the unnecessary empty 'c' values in the leaf elements. (I tested with a manual version that just remimplemented the old behavior, and there was a speedup, but not as dramatic.)

Better news: the version I wrote just defined `ToJSON` instances with `toJSON` functions. Aeson now allows you to write `toEncoding` functions that go straight to ByteStrings and can speed things up by as much as 3x (according to the literature, anyway). So there might be a bit more of a speedup coming.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Sep 29 16 09:02 ]:
>   So, just for the sake of clarity: what should the compatibility-meaning
>   of the version in the JSON be? Given api versions X.Y.Z and X'.Y'.Z' we
>   guarantee json compatibility if X==X' && Y==Y'?

That sounds reasonable.  We commit ourselves to bumping the
minor version with any breaking change in JSON format,
even if nothing else changes.

**Comment by jkr** [comment]
@jgm: sorry for piggy-backing on this thread (while closing it) but didn't want to clutter the forums with another one. I have a changeset that removes Tests.Arbitrary and replaces it with an import of the Arbitrary instances from pandoc-types. Should I push that now, or should I wait till the non-stack travis build problems with pandoc-types settle down?

**Comment by jgm** [comment]
@jkr - go ahead.  pandoc is now already committed to using
pandoc-types 1.17.X, because of @tarleb's lineblock patches.
This push isn't going to make the problem any worse!

(Do you have further changes for pandoc-types?  It would
help things to do a release there.  And I'd like to do
a pandoc release too in the not-distant future.)

+++ Jesse Rosenthal [Oct 14 16 05:49 ]:

**Comment by jkr** [comment]
> (Do you have further changes for pandoc-types? It would help things to do a release there. And I'd like to do a pandoc release too in the not-distant future.)

Not really. I was thinking of trying to switch the tests over the Value as we were discussing. But I doubt I'll have the time over the next few days. And that's entirely dev-focused anyway, so it doesn't really matter for the release.

**Comment by jkr** [comment]
Should we add pandoc-types version to the "compiled with" message on `pandoc -v`? It might be useful for diagnosing JSON errors.

**Comment by jgm** [comment]
I had the same idea, and I've already got it implemented on
my laptop at home.  Will try to push it later tonight.

+++ Jesse Rosenthal [Oct 26 16 08:08 ]:

**Comment by jgm** [comment]
Good idea, done.

+++ Jesse Rosenthal [Oct 26 16 08:08 ]:
