### ISSUE TITLE
Suggestion: Split Text.Pandoc.Templates into own package

### ISSUE THREAD

**Issue by qua-bla** [jgm/pandoc#3134]
I found it very useful since it is the only template engine that integrates with Data.Aeson. However, pulling in pandoc completely just for the template engine is suboptimal.

**Comment by jgm** [comment]
It's a good suggestion, and I've thought of doing this.

The main obstacles (besides the time needed and the inconvenience of having to maintain another package) are the dependencies on two functions imported from Text.Pandoc.Shared (`readDataFileUTF8` and `ordNub`).  `ordNub` is trivial, but `readDataFileUTF8` is pandoc-specific.

If Text.Pandoc.Templates were made into its own package, `getDefaultTemplate` would have to be moved to Text.Pandoc.Shared.

**Comment by jgm** [comment]
OK, I'm working on this now.

**Comment by qua-bla** [comment]
Wow thanks! I have spotted <https://github.com/jgm/doctemplates>, that was fast!

Our build server now needs half of the time for the dependencies. Very useful.
