### ISSUE TITLE
latex: pandoc chokes on \begin{the-environment} after multi-line commands

### ISSUE THREAD

**Issue by moi90** [jgm/pandoc#3137]
I'm trying to convert a latex document to a markdown txt:

```
pandoc full_document.tex -o full_document.txt
pandoc: 
Error at "source" (line 2358, column 7):
unexpected "e"
expecting "{document}"
\begin{description}
      ^
```

At an seemingly arbitrary point, pandoc refuses to process environments. In the above case, it is `description`, but the error occurs for every environment, if I remove the environment where the error occurred before.

I suspect, that at some place, pandoc misses the closing of an environment, but if I remove the environment before the one throwing the error, the error persists.

The error vanishes, if I delete everything before the environment up to the previous `\footnote`, that is spanning multiple lines:

```
\footnote{multiple
lines}
```

Same with:

```
\emph{multiple
lines}
```

If I change it to 

```
\footnote{multiple %
lines}
```
the error disappears. How weird is that?

I'm using pandoc 1.12.2.1, Compiled with texmath 0.6.5.2, highlighting-kate 0.5.5.1.

**Comment by jkr** [comment]
First, you should really update your pandoc. That version is well over two years old, and is missing *lots* of features.

I can't reproduce the issue -- but maybe I don't understand the issue. I tried running pandoc 1.17 on this:

~~~
\emph{multiple
lines}
\begin{description}
  foo
\end{description}
~~~

and it worked fine. Was this the sort of .tex document you meant, or was it something else?

**Comment by moi90** [comment]
Thanks, I didn't know that installing the current version is that easy! Everything works with 1.17.2.

**Comment by jgm** [comment]
You're using quite an old version of pandoc (last release is
1.17.2) so my first advice would be to try your document
with a more recent version. (There are binary packages
available for windows, mac, and linux.)

Failing that, we can't really help without a full example
we could use to reproduce the problem.
