### ISSUE TITLE
converting HTML to DOCX ignores directionality

### ISSUE THREAD

**Issue by abartov** [jgm/pandoc#3140]
This has been asked before, but going over all previous issues and threads, I have not been able to identify a solution for my simple use case.  I have an HTML file, which specifies right-to-left directionality (via dir=rtl at the HTML and BODY levels, and does not specify directionality at P or DIV levels) and alignment (via align=right, likewise), which pandoc converts to DOCX correctly except for the directionality and alignment: the text comes out left-aligned and in left-to-right directionality.

I do not find a command line argument to set directionality.  How can I resolve this?  

Thanks in advance.

**Comment by jgm** [comment]
I don't think we've got rtl support built into the docx
writer yet.  It would help if you uploaded or pasted in
a short HTML example file we could work with.

**Comment by abartov** [comment]
Gladly!  Thanks for the rapid response.
[rtl_example.zip](https://github.com/jgm/pandoc/files/505192/rtl_example.zip)

**Comment by jkr** [comment]
Do you have a copy of a word document with correct directionality? Setting rtl doesn't seem to be an option on the Mac (the only copy of word I have access to). I could try it out with Windows copy of Word on a vm tomorrow. But if you have a hebrew word doc that you know behaves correctly, that would be the best thing for us to work from.

**Comment by jkr** [comment]
Hmm... I found one online -- it looks like it has a `<w:rtl>` tag inside each `<w:rPr>` (run props). A bit of experimentation with the document you offered suggested that it seems to work. (Have to switch from left-align to right-align as well).

I could implement it in the writer in the next few days, but I'm not sure what the best way to trigger this would be.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Oct 02 16 18:56 ]:
>   I could implement it in the writer in the next few days, but I'm not
>   sure what the best way to trigger this would be.

See #2419 for how we did this in LaTeX, ConTeXt, and HTML.  And see @mb21's
comment at the end of #2191.  There's a document-wide `dir` metadata field,
which can be overridden with an attribute on a div or span.  This is also
described in the manual thus:

> `dir`:  the base direction of the document, either `rtl` (right-to-left)
> or `ltr` (left-to-right).
> 
> For bidirectional documents, native pandoc `span`s and `div`s
> with the `dir` attribute (value `rtl` or `ltr`) can be used to
> override the base direction in some output formats.
> This may not always be necessary if the final renderer
> (e.g. the browser, when generating HTML) supports the
> [Unicode Bidirectional Algorithm].
> 
> When using LaTeX for bidirectional documents, only the `xelatex` engine
> is fully supported (use `--latex-engine=xelatex`).

There's some inconclusive discussion in that thread about whether dir should be inferred from lang.

Pinging @mb21 who might have something to add here...

**Comment by abartov** [comment]
thank you!  From my perspective, a command line flag setting it explicitly would be most convenient. In HTML input, I suppose another trigger could, and perhaps should, be the dir attribute on HTML, BODY, DIV, and P tags.

**Comment by jgm** [comment]
+++ Asaf Bartov [Oct 03 16 02:33 ]:
>   thank you! From my perspective, a command line flag setting it
>   explicitly would be most convenient.

You can set metadata fields on the command line.

**Comment by mb21** [comment]
As mentioned by jgm, you can set metadata fields on the command line, e.g.: `pandoc -V dir=rtl`

> There's some inconclusive discussion in that thread about whether dir should be inferred from lang.

I guess it could be inferred as long as you can still manually overwrite it... but this should probably be done in the markdown reader.

@jkr I don't know how Word handles bidirectional text, but this is a good [introduction about the issues and how HTML handles them](http://www.w3.org/International/articles/inline-bidi-markup/uba-basics). I've basically tried to follow this model in pandoc, as markdown and the pandoc document AST map very well to HTML.

**Comment by abartov** [comment]
Thanks @mb21 and @jgm.  To be clear, this would only work if the DOCX writer is changed as @jkr said, right?

**Comment by jkr** [comment]
@abartov -- the only other possibility is that, if you're running the dev branch, you *might* be able to do it with custom divs: set `<div custom-style="rtl_hebrew">` or something around the body of the document, and then try defining the "rtl_hebrew" in your reference.docx to be rtl. I'm not sure that will work, since I don't quite know how setting rtl in word works (since they only have the feature in windows).

But, as I said, that's in the dev branch. The change to the writer looks pretty easy (I'm about halfway done with it) so that will be in the dev branch in a day or two as well.

**Comment by jkr** [comment]
@abartov: do you have a copy of a simple Hebrew docx written in a Hebrew copy of Word? There's some inconsistency among the rtl docs I've found on line, so that would be helpful. Mixed Hebrew and English would be particularly helpful.

**Comment by abartov** [comment]
Thank you, @jkr!  Here's one such short file, with rtl directionality and right alignment, with regular paragraphs, bullets, and even a table.

[יוסף_ואשת_פוטיפר_-_סיכום.docx](https://github.com/jgm/pandoc/files/506269/_._._-_.docx)

**Comment by jkr** [comment]
closed with ab31d5ea8d0fc17b900a5843104784a25a2c8ed9

You can set the metadata, run `-M dir=rtl` on the command-line, and/or use divs and spans.

**Comment by mb21** [comment]
@jkr btw, I added a [test file](https://github.com/jgm/pandoc/blob/master/tests/writers-lang-and-dir.native) with expected outputs for context and latex...

**Comment by jkr** [comment]
@mb21: good to know. Unfortunately, docx writer tests are roundtrip-only at the moment (native->docx->native', and then compare). I wrote a [free-monad-based implementation](https://github.com/jkr/pandoc/tree/free) of the IO bytestring writers a while back, so once I polish that a bit, it might might make it easier to test them.

**Comment by abartov** [comment]
Thank you, everyone.  Can any of you create a binary (an x64 .deb in my case), or is my only way to get this fix to build the haskell from source?

**Comment by jkr** [comment]
There aren't binaries supplied for snapshots, but [stack](https://docs.haskellstack.org/en/stable/README/) makes building from source pretty painless. (Provided you have ~15 minutes and some spare disk space.) It will take care of all dependencies. See the INSTALL file in the source for more info.

**Comment by abartov** [comment]
thank you very much!  I finally got around to building it, and the change works well for me.  I really appreciate how responsive and helpful the pandoc team has been.  

(It may please you to know I will be using this to offer additional download formats for the volunteer-run ad-free and free-software digital library of public domain Hebrew texts that I've been running since 1999.)

**Comment by tarleb** [comment]
@abartov would you link to the library here?  I'm composing a list of projects which use pandoc in some way and would like to include it there.

**Comment by abartov** [comment]
Sure!  The library is called Project Ben-Yehuda, and it is here: http://benyehuda.org
