### ISSUE TITLE
ePub cover image not recognised

### ISSUE THREAD

**Issue by xmeltrut** [jgm/pandoc#3151]
I'm generating a ePub and trying to include a cover image. I have tried the metadata:

    cover-image: contrib/cover.jpg

And the command line:

    --epub-cover-image=contrib/cover.jpg

However, in both cases iBooks fails to recognise it and Kindlegen says the cover is not specified. I took a look inside the ePub's contents and noticed that there might be a discrepancy in the ID used for the cover.

In content.opf:

    <meta name="cover" content="cover-image"/>

And again in toc.ncx:

    <meta name="cover" content="cover-image" />

But in the manifest it is listed with the file extension in the ID:

    <item id="cover-image_jpg" href="cover-image.jpg" media-type="image/jpeg" />

**Comment by ousia** [comment]
@xmeltrut, all SVG covers from ePub documents that I have generated with pandoc aren’t recognized by _iBooks_.

Just in case it helps.

**Comment by xmeltrut** [comment]
Kindle does not recognise them either. Or Finder. I'm pretty sure the issue is the ID the element is given. I unzipped the epub, manually edited the ID, then re-zipped the ebook and then all the software started recognising it.

**Comment by jgm** [comment]
@xmeltrut what version of pandoc?  I just tried and got consistent identifiers with the `_jpg` suffix.
I suspect you're using an older version.
According to the changelog, a bug like the one you describe was fixed in pandoc 1.13.
See c5c9b0d2890699ee8fcdbb660662957f8efad319

**Comment by xmeltrut** [comment]
I was using 1.12, but I'm now using 1.17 with the same result.

Are you getting the _jpg suffix everywhere?

**Comment by jgm** [comment]
If you're getting 'cover-image' as the ID of the cover image
in content.opf etc., then I suspect you're not running 1.17.
There's nothing in the code that would insert that.
Are you sure you're not accidentally running the older
version?

+++ Chris Worfolk [Oct 10 16 07:28 ]:

**Comment by xmeltrut** [comment]
To clarify, I'm getting cover-image_jpg, which is the problem.

Both content.opf and toc.ncx reference a cover with identifier 'cover-image', rather than 'cover-image_jpg', but in the manifest the file itself has an identifier of 'cover-image_jpg', so they don't match up.

**Comment by jgm** [comment]
Maybe I'm not understanding properly, but I can't reproduce
this (and what you're reporting is exactly the bug fixed
in 1.13, which is why I suspect you're running an older
verison).

```
% pandoc -o 3151.epub
---
cover-image: tests/lalune.jpg
title: test
...

# Chapter one

hi
% e 3151.epub 
% unzip -d 3151 3151.epub
Archive:  3151.epub
 extracting: 3151/mimetype           
  inflating: 3151/META-INF/container.xml  
  inflating: 3151/META-INF/com.apple.ibooks.display-options.xml  
  inflating: 3151/stylesheet.css     
  inflating: 3151/title_page.xhtml   
  inflating: 3151/content.opf        
  inflating: 3151/toc.ncx            
  inflating: 3151/nav.xhtml          
  inflating: 3151/media/lalune.jpg   
  inflating: 3151/cover.xhtml        
  inflating: 3151/ch001.xhtml        
% ack cover-image 3151
3151/cover.xhtml
12:<div id="cover-image">
```

As you can see, the only place the identifier `cover-image` appears
is in `cover.xhtml`, where it is the id of the enclosing div.



+++ Chris Worfolk [Oct 10 16 09:35 ]:

**Comment by xmeltrut** [comment]
Sorry, you're right, upgrading to 1.17 has fixed it! I am now getting the cover content as cover_jpg. 

I'm guessing iBooks and Kindle have some sort of cache as the new version still isn't working on the device I was testing on, but when I tried it another device it worked straight away.
