### ISSUE TITLE
markdown-fancy_lists also turns off example_lists

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#3152]
Using the example from the manual:

```md
(@)  My first example will be numbered (1).
(@)  My second example will be numbered (2).

Explanation of examples.

(@)  My third example will be numbered (3).

(@good)  This is a good example.

As (@good) illustrates, ...
```

Using

```bash
pandoc -f markdown-fancy_lists -s -o testing.html testing.md
```

will not have example lists numbered but left as is.

```bash
pandoc -f markdown+example_lists-fancy_lists -s -o testing.html testing.md
pandoc -f markdown-fancy_lists+example_lists -s -o testing.html testing.md
```

will both yield the same result.

**Comment by jgm** [comment]
No, turning off fancy_lists does not turn off example_lists.
It just disables example lists that are ALSO fancy, as yours
are (because they use parentheses rather than a period).

Try

    @. My first example will be numbered 1.
    @. My second example...


+++ ickc [Oct 06 16 20:51 ]:

**Comment by ickc** [comment]
Ah... right! So stupid of me! I'm closing this.
