### ISSUE TITLE
Images are wrapped in paragraph

### ISSUE THREAD

**Issue by hrehfeld** [jgm/pandoc#3160]
echo " ![](img.png)\ " | pandoc -t html5

will produce:

    <p><img src="img.png" /> </p>

which is not what I would expect. Rather:

    <img src="img.png" />

This behavior is also present with org as input:

    $ echo "[[./img.png]]" | pandoc -t html5 -f org 
    <p><img src="./img.png" /></p>

or with json as output:

    $ echo "[[./img.png]]" | pandoc -t json -f org 
    [{"unMeta":{}},[{"t":"Para","c":[{"t":"Image","c":[["",[],[]],[],["./img.png",""]]}]}]]

When I specify a caption, no paragraph is emitted in html5:

    $ echo "#+caption: image\n[[./img.png]]" | pandoc -t html5 -f org
    <figure>
    <img src="./img.png" alt="image" /><figcaption>image</figcaption>
    </figure>

It is present in json output, however (but has the fig: type):

    $ echo "#+caption: image\n[[./img.png]]" | pandoc -t json -f org 
    [{"unMeta":{}},[{"t":"Para","c":[{"t":"Image","c":[["",[],[]],[{"t":"Str","c":"image"}],["./img.png","fig:"]]}]}]]

 This is in

    pandoc 1.17.2

**Comment by jgm** [comment]
Pandoc's Markdown treats an image by itself in a paragraph as a figure.  When you add the nonbreaking space, it forces it to treat it just as a paragraph with an image.  If you want an image that is not a figure but also not in p tags, you could do something like `<div>![img](myimg.jpg)</div>`.

I don't see a bug here; pandoc is working as documented.

**Comment by hrehfeld** [comment]
Oh yes, i had read the relevant doc section (for md images) *just* before I wrote the request, doh.

However, I stumbled upon this because of the behavior in #3161 , which makes it hard/impossible to specify an image without an actual caption in org and still have it rendered as a figure.

**Comment by jmuheim** [comment]
Sorry for late commenting, but I try to create an image without container (neither `<p>` nor `<figure>`).

I tried something like `<div>![img](myimg.jpg)</div>`, but this results in:

```html
<div>
  <figure>
    <img src="myimg.jpg" alt="img" />
    <figcaption aria-hidden="true">img</figcaption>
  </figure>
</div>
```

More details why I need an image outside a paragraph can be found here: https://stackoverflow.com/questions/79434114/pandoc-and-reveal-js-how-to-create-a-proper-image-with-r-stretch-helper

**Comment by jgm** [comment]
The only way to do this is to use a raw HTML block.

````
```{=html}
<img src="whatever.jpg" alt="whatever"/>
```

````
