### ISSUE TITLE
org reader: images without caption or empty caption are not converted to figures

### ISSUE THREAD

**Issue by hrehfeld** [jgm/pandoc#3161]
While I would expect the following behavior:

    $ echo "[[./img.png]] test" | pandoc -t html5 -f org
    <p><img src="./img.png" /> test</p>

If the image is on its own line, this is suprising:

    $ echo "[[./img.png]]" | pandoc -t html5 -f org 
    <p><img src="./img.png" /></p>

Additionally, in org it is not possible to specify an empty caption like in markdown:

    $ echo "#+caption: \n[[./img.png]]" | pandoc -t html5 -f org
    <p><img src="./img.png" /></p>

while:
 
    $ echo "#+caption: something\n[[./img.png]]" | pandoc -t html5 -f org
    <figure>
    <img src="./img.png" alt="something" /><figcaption>something</figcaption>
    </figure>

produces a figure as expected.

This is problematic, because I cannot specify an image that is not either wrapped in a paragraph or has an actual caption.

See also #3160.

**Comment by hrehfeld** [comment]
$ echo "#+caption:  \ \n[[./img.png]]" | pandoc -t html5 -f org
    <figure>
    <img src="./img.png" alt="" /><figcaption></figcaption>
    </figure>

specifying \  as the caption at least creates a figure, however it has an empty figcaption.

I would really expect just [[./img.png]] to create the figure.

**Comment by jgm** [comment]
@tarleb can answer better than I can, I don't know the ins and outs of org-mode format.
Note that the pandoc rule "an image by itself in a paragraph is a figure" only applies to Markdown input.  I'm not sure what the rules are for figures in org-mode, but we'd try to follow org-mode itself.

**Comment by hrehfeld** [comment]
#+HTML_DOCTYPE: html5
[[./img.jpg]]

org mode doesn't seem to support figures at all:

    <div class="figure">
    <p><img src="./img.jpg" alt="img.jpg">
    </p>
    <p><span class="figure-number">Abbildung 1:</span> \</p>
    </div>

So I think it would be a good idea not to fix output to the org-mode output.

**Comment by tarleb** [comment]
As @jgm already said, pandoc tries to follow Emacs org-mode as much as possible. The [org manual](http://orgmode.org/manual/LaTeX-specific-attributes.html) states:

> If you have specified a caption as described in Images and tables, the picture will be wrapped into a figure environment and thus become a floating element.

The requirement for a caption to output a figure is intended because of this.  However, empty captions should work as well, so this is a bug in the org reader. Thanks for reporting it.
