### ISSUE TITLE
Spaces inserted before footnotes in org writer

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#3162]
(ping @tarleb)

I was looking to extend `--reference-location` to org and rst output, but ran into a separate issue. The org writer inserts a space before footnotes (the rst writer does too, but that's a separate issue).

~~~{.markdown}
foo[^1]

[^1]: bar
~~~

produces

~~~{.org}
foo [1]

[1] bar
~~~

Note the space inserted. Both emacs and the pandoc reader handle it correctly without the space. @tarleb, any reason not to remove that?

**Comment by tarleb** [comment]
You are right, that extra space is not correct. I'm in my phone rn, can fix it tonight.

Am 17. Oktober 2016 00:41:13 MESZ, schrieb Jesse Rosenthal <notifications@github.com>:
>(ping @tarleb)
>
>I was looking to extend `--reference-location` to org and rst output,
>but ran into a separate issue. The org writer inserts a space before
>footnotes (the rst writer does too, but that's a separate issue).
>
>~~~{.markdown}
>foo[^1]
>
>[^1]: bar
>~~~
>
>produces
>
>~~~{.org}
>foo [1]
>
>[1] bar
>~~~
>
>Note the space inserted. Both emacs and the pandoc reader handle it
>correctly without the space. @tarleb, any reason not to remove that?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/3162

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
