### ISSUE TITLE
How to handle spaces before footnote marker in rst reader?

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#3163]
The rst writer inserts spaces before footnote markers. This is correct behavior, because it seems that docutils can't read a footnote without a space before it. However, I think that perhaps the rst reader in pandoc should munch that space. `rst2latex` seems to do that, along with defining its own footnote macro. To make pandoc rst more suitable for paper output, we should probably do the same. 

So, for example, in

~~~{.rst}
foo [1]_

.. [1]
   bar
~~~

I think we should munch the space after `foo`.

**Comment by jgm** [comment]
We should do whatever rst2latex and rst2html do, so yes, if
they do this, let's do it too.

+++ Jesse Rosenthal [Oct 16 16 15:48 ]:

**Comment by jkr** [comment]
> We should do whatever rst2latex and rst2html do, so yes, if
they do this, let's do it too.

The problem is that rst2html and rst2latex handle it differently: rst2html keeps the space, and rst2latex discards it. But I think it makes more sense to follow rst2latex here since our html output is different anyway (superscript instead of brackets) and removing the space will produce pandoc output that looks correct in both our html and pdf (and any other target format).

**Comment by jgm** [comment]
Agreed.

+++ Jesse Rosenthal [Oct 17 16 06:26 ]:
