### ISSUE TITLE
Use zip instead of zip-archive

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3170]
We should use the new, better designed zip library instead of zip-archive.
https://hackage.haskell.org/package/zip
and perhaps deprecate zip-archive...

**Comment by jkr** [comment]
It seems like zip is file-oriented: the only entry to an archive is through a path. See https://github.com/mrkkrp/zip/issues/13

This wouldn't work with the current approach of having a similar interface to pandoc regardless of String or ByteString. (Not that many people read binary files through stdin, but this would make it impossible.)

Bigger issue: the `ZipArchive` monad is an instance of `MonadIO`. So we couldn't have any pure readers that worked within that monad, unless we did all the extraction at a higher level. And we definitely couldn't have any pure writers.

There's an approach listed on the issue listed above which seems like one possible work-around. But it seems like it's working against the grain a bit.

(This also means, I think, that it might be worth not deprecating zip-archive until there's a pure interface to zip. Though perhaps you could add a note to the effect of "If you're working with files in IO and memory is an issue...")

**Comment by jkr** [comment]
Of course, the other discussion about memory usage in #3169 suggests that we might want to consider different approaches to IO (like the conduit-y ones here). But that seems more like part of a pandoc-2 rethink.

**Comment by jgm** [comment]
Indeed, this is a compelling reason to stay with zip-archive, unless zip makes a pure interface available.  Closing!
