### ISSUE TITLE
Turning off `footnotes` also turns off `inline_notes`

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#3172]
Currently, if I have an inline footnotes, using `pandoc -f markdown -t markdown` would turn it into a non-inline footnotes with `[^1]`, *etc.* If I turn off `footnotes` extension by `pandoc -t markdown-footnotes`, the output will just be `[1]`, *etc.* *i.e.*, the `inline_notes` extensions is also turned off by it. So, they are not really 2 different extensions?

**Comment by jgm** [comment]
`inline_notes` only means that inline notes are allowed, not that they are required. And inline notes are limited -- they only work for footnotes that contain just one paragraph worth of content, without any more complex block structure.  So, we just use regular notes in the Markdown writer.

We could, of course, use inline notes when possible, and regular notes otherwise, but I don't think that's generally a better default.

**Comment by ickc** [comment]
But I think it is reasonable to think that the 2 different extensions can be turned on/off seperately. As I said, for the meanwhile, turning off the footnotes also turns off inline footnote in the writer. So the reason of openning the issue is about the dependency between the extensions.

I agree even if this is changed, this might not help too much for pandoc to becomes a linter, since the info of whether it was an inline footnote or regular footnote is lost. But I think there can be situation that one want to enforce the output footnotes to be purely inline.

To me, I think to use pandoc as the linter means I should enforce the opposite, allowing regular footnotes only.

Thanks anyway!

**Comment by jgm** [comment]
The inline_notes extension allows, but does not require,
inline notes.  And in general inline notes can't always
be used, since they are only possible for simple notes
without block-level content.  So we use regular notes.

+++ ickc [Oct 22 16 01:54 ]:

**Comment by ickc** [comment]
In a sense what I want to do is similar to what `--reference-links` did. `--reference-links` provide an option to control whether *inline or reference-style* link is used.

I agree not every content supported by reference-style footnote is supported by inline footnote, but may be a command line option is given, say, `--inline-footnotes` inspired from `--reference-links`, that whenever possible try to use inline footnotes and only use reference-style footnotes when inline footnotes can't be used.

The advantage of inline footnote is that one need not to worry about the anchor and if they collide (same anchor, multiple footnote) or not.

And by the way, why inline footnote "cannot contain multiple paragraphs"? Are there technical limitation in it? It seems the same rule used by reference-style footnote can be used in inline footnotes as well. Is it because if the footnote contains `]`, the inline footnote will close prematurely? Even then, the requirement of inline footnotes can be relaxed to "cannot contain `]`". Or better, "cannot contain unclosed pairs of `[]`", and the parser just keep track of each pairs of `[]` until it hit the one matching `^[`.

**Comment by jgm** [comment]
If I added such an option, you'd soon want several other options controlling other features of the writer.  This way madless lies.  I think we need to keep things simple and recognize that pandoc is not set up to be a flexible markdown reformatter.

**Comment by ickc** [comment]
How about the point to allow inline notes to support the same features of footnotes? Are there technical difficulties there?

**Comment by ickc** [comment]
A question about the AST:

```bash
$ printf "%s\n\n" "test[^foot]" "[^foot]: footnote anchor?" | pandoc -f markdown -t native
[Para [Str "test",Note [Para [Str "footnote",Space,Str "anchor?"]]]]
```

So the info on the footnote anchor cannot be recorded in the current AST?

To put the issue in another way, so say I start with a bunch of `.docx`, they are converted to md (with footnote inside), and later `cat` to the same file, the footnote anchor will then collide. I understand the new `--file-scope` kind of solves the issue, but `cat`ing the files directly has a benefit of letting pandoc to dealing with headers with the same name and not producing repeated id.

Since the AST is also "inline footnotes" (without anchor, immediately besides the context), it seems that if somehow we can make the inline footnotes supporting all the footnotes features (being block element), setting the inline footnotes be the default markdown writer output seems to be much more natural.

**Comment by jgm** [comment]
+++ ickc [Oct 29 16 01:55 ]:
>   So the info on the footnote anchor cannot be recorded in the current
>   AST?

Correct.  This also means you can't e.g. have two distinct
refs to the same footnote (there's an  issue about this
somewhere).

**Comment by ickc** [comment]
Is it possible to extend inline footnote to support exactly the same features supported by reference-footnote, i.e. more than 1 line? If this can be made happened, then the markdown writer can be rewritten to allow inline-footnote only (perhaps through `markdown-footnotes`), which has another benefit of "getting closer to the AST" since the AST is also using "inline-footnote".

e.g.

# Syntax 1: Doesn't Allow `[]` in Inline-Footnotes

```markdown

Here is a footnote reference,^[Here is the footnote.]
and another.^[Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

        { some.code }

    The whole paragraph can be indented, or just the first
    line.  In this way, multi-paragraph footnotes work like
    multi-paragraph list items.]

This paragraph won't be part of the note, because it
is closed.

This syntax doesn't allow the use of `[]` in inline footnotes.

```

# Syntax 2: Allow `[]` in Inline-Footnotes

```markdown

Here is a footnote reference,^[Here is the footnote, with
no newline character, closed immediately when there's a
closing bracket.] and another.^[Here's one with multiple
blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

        { some.code }

    The whole paragraph can be indented, or just the first
    line.  In this way, multi-paragraph footnotes work like
    multi-paragraph list items.

    Some how I like to write special character ].

    It wasn't closed, since the syntax to close it is this:
]

This paragraph won't be part of the note, because it
is closed.

Lastly,^[
    This is also an inline footnote.
]

```

I think syntax 2 is better, and general enough to cover anything from the AST.

**Comment by skillio** [comment]
I've run into a similar issue with wanting to force inline footnotes, and having complex footnotes. Though I'll defer to the dev,, to me this seems like a specific use case and a flaw in footnote handling, not a "that way madness lies" sort of concession. Any update or workaround outside of writing a custom filter?
