### ISSUE TITLE
'--filter' doesn't respect shebang

### ISSUE THREAD

**Issue by CommunicationAnimale** [jgm/pandoc#3174]
This issue was marked as solved two years ago (https://github.com/jgm/pandoc/issues/1389), however I still have this problem:

filter.py
``` python
#!/usr/bin/env python3
import pandocfilters as PF
import sys

def str_to_py_version(k, v, fmt, meta):
    if k == "Str":
        return PF.Str(sys.version.split()[0])

if __name__ == '__main__':
    PF.toJSONFilter(str_to_py_version)
```

```
~/Programming/PandocTest
$ pandoc -t latex --filter filter.py <<< "foo"
2.7.12

~/Programming/PandocTest
$ pandoc -t json <<< "foo" | python3 filter.py| pandoc -f json -t latex
3.5.1
```

(pandoc 1.16.0.2)

**Comment by jkr** [comment]
What is the result of `which python`? And is filter.py executable?

**Comment by jkr** [comment]
The reason I ask is because pandoc will run a python script even if it's not executable, using whatever the system python is. In that case, it won't read the shebang. It will only read the shebang if the executable bit is set.

**Comment by CommunicationAnimale** [comment]
Maybe you could write this in the documentation? Or maybe even change this behaviour? I think it would be more intuitive.

When I try to mark `filter.py` as executable, I run into another issue:
``` shell
~/Programming/PandocTest
$ chmod +x filter.py

~/Programming/PandocTest
$ pandoc -t json <<< "foo" | ./filter.py | pandoc -f json -t latex
3.5.1

~/Programming/PandocTest
$ pandoc -t latex --filter filter.py <<< "foo"
pandoc: Error running filter filter.py
filter.py: createProcess: runInteractiveProcess: exec: does not exist (No such
file or directory)
```

And as to `which python`:
``` shell
$ which python
/usr/bin/python
```

**Comment by jgm** [comment]
From the manual:

> Note that the EXECUTABLE will be sought in the user’s PATH, and not in the working directory, if no > directory is provided. If you want to run a script in the working directory, preface the filename with ./.

**Comment by jgm** [comment]
Also, the manual for the upcoming release of pandoc contains more detailed documentation under `--filter`, esp. as regards non-executable filters.
