### ISSUE TITLE
Problem with inline math using \bar{x}

### ISSUE THREAD

**Issue by suknat** [jgm/pandoc#3181]
I'm having  a strange problem using \bar{x} in pandoc md, as follows:

If I write
`sample mean as $\bar{x}$.` 

Then the output is produced *literally* as follows: 

![screen shot 2016-10-25 at 12 39 50](https://cloud.githubusercontent.com/assets/16538950/19684628/3d6d2872-9ab0-11e6-90c0-2f0e683e5d9e.png)

However, if I use 
` sample mean as $$\bar{x}$$`

Then I get the expected output: 

![screen shot 2016-10-25 at 12 40 16](https://cloud.githubusercontent.com/assets/16538950/19684635/470ed376-9ab0-11e6-97c6-f7b2943a1d90.png)

I haven't tested this widely but other commands such as \hat also behave in the same way. 

However, inline mode does work for symbols such as \mu or \sigma.

Does anyone have any clues on how to fix this?

**Comment by jgm** [comment]
What's your output format?  If HTML, what are you using to display math?

**Comment by jgm** [comment]
Also, what version of pandoc are you using (give output of `pandoc --version`, which will also tell us what version of texmath it's linked against).

I just tried with docx output and could not reproduce what you're describing.  Both examples worked fine.

**Comment by suknat** [comment]
Hi John

Output of `pandoc --version` is:
`pandoc 1.16
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.`

I'm using [Marked2](http://marked2app.com) and have enabled MathJax in the preferences by selecting `Tex-MML-AM_HTMLorMML`. 

And with that thought, I switched to `Tex-MML-AM_HTMLorMML-full` and the problem has gone away.

Sorry, didn't think to change this setting before posting but hopefully it helps others. 

Is there a particular setting you'd recommend for full LaTeX compatibility?

Thanks!

**Comment by jgm** [comment]
We use https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full
