### ISSUE TITLE
Beamer overlays (\only, \uncover, etc)

### ISSUE THREAD

**Issue by naught101** [jgm/pandoc#3184]
Is there a way to use beamer's overlays with pandoc, as suggested [here](https://tex.stackexchange.com/questions/251702/add-only-and-uncover-sequences-in-pandoc-beamer)?

If there isn't already, would it be possible to add something like that to pandoc somehow?

There is an [existing attempt](https://andrewgoldstone.com/blog/2014/12/24/slides/), but it still results results the contents of the bullet points being treated as raw latex, not markdown...

I'm not sure of a syntax that would work for this though..

**Comment by naught101** [comment]
Thanks John!

**Comment by mardukbp** [comment]
@jgm This issue should not be considered solved. Currently Pandoc allows using `\only` within blocks, but one cannot use `\only` to show certain blocks in a given overlay.

What is needed is something along the lines of:

```
### Block :only 1-3:

Contents
```

which should be converted by Pandoc to the following LaTeX code:

```
\only<2-3>{
\begin{block}{Block}
Contents
\end{block}
}
```

**Comment by h-g-s** [comment]
\only is a horrible solution,   is there any other option ???

**Comment by gergoerdi** [comment]
Here's an example where this approach doesn't work out: https://tex.stackexchange.com/a/158680/2113

This would need the ability to put an overlay specification on a frame itself.

**Comment by drupol** [comment]
Thanks for clarification.
