### ISSUE TITLE
LaTeX reader should optionally capture comments as raw TeX, like Markdown does with raw HTML comments

### ISSUE THREAD

**Issue by jrk** [jgm/pandoc#3187]
I realize most uses of Pandoc are one-way and display-format-oriented, but it is such a rich transformation system that it can be very valuable to capture all available information where possible in readers, rather than dropping or flattening it during reading.

Pandoc readers already do this to a very large degree, and even for comments, the Markdown reader reads comments as raw HTML blocks which can be suppressed by default when going to other targets. The LaTeX reader, however, does not seem to have a way to preserve comments.

It would be useful for (in my case) LaTeX <==> (extended) Markdown round tripping to be able to capture comments when reading LaTeX. I'm glad to handle them in my own desired way using my own filter scripts, but even that is not currently possible since they're elided on reading. It's not obvious why they could not also be parsed as raw TeX strings, starting with `%`, just as Markdown/HTML comments are raw HTML nodes internally enclosed by the text `<!--`…`-->`.

**Comment by ickc** [comment]
Duplicated, see #1926. Should be closed.

**Comment by tarleb** [comment]
The issues are very much related but about different formats, so maybe we should keep it open?

**Comment by ickc** [comment]
Ah, right, in reverse direction. I still suggest you to append to that thread instead, since to underlying problem is the same: pandoc AST do not currently support comment.

**Comment by jgm** [comment]
Closing in favor of #1926 now that the comment has been transferred there.
