### ISSUE TITLE
Unexpected pandoc-api-version number

### ISSUE THREAD

**Issue by sergiocorreia** [jgm/pandoc#3188]
```
>pandoc --to=json
^Z
{"pandoc-api-version":[1,17,0,4],"meta":{},"blocks":[]}
```

I was expecting version [1,18,0], is it a bug?

Thanks!
S

**Comment by jkr** [comment]
It's based on pandoc-types, which won't necessarily increment every time pandoc does. So a filter could remain functional across pandoc versions if pandoc-types doesn't change. (The pandoc-types version should be in `pandoc -v` now).

BTW, compatability just requires that the first two numbers (1, 17) match. The minor number wll only increment for breaking changes.

**Comment by jkr** [comment]
That being said, this should be documented more clearly, so I'll reopen this.

**Comment by jkr** [comment]
@jgm: do you think it would make sense to put info about the JSON format in MANUAL.txt? Can't really think of where else we could put it. Maybe just a description of the schema and very quick account of filters? The info there is sort of spread around between the manual, the wiki, and the -types hackage.

**Comment by jgm** [comment]
Yes, I agree it should be in the manual.

**Comment by mb21** [comment]
There is also http://pandoc.org/scripting.html, which I usually link to when introducing people to pandoc filters... so maybe there should be a TL;DR; there which includes the versioning explanation and maybe the following links:

- https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Definition.hs
- https://github.com/jgm/pandoc/wiki/Pandoc-Filters

**Comment by mb21** [comment]
I gave it a go, see pull request https://github.com/jgm/pandoc-website/pull/6

**Comment by mb21** [comment]
Thanks for merging the pull @jgm. Not sure if this is still needed in the manual then. If not, this issue should be closed...
