### ISSUE TITLE
Inconsistent line continuation for docx vs pdf

### ISSUE THREAD

**Issue by johnlb** [jgm/pandoc#3189]
It seems the docx exporter wants a multi-line equation to look like this:

<pre>
$$
x = y
    + z
$$
</pre>

whereas the pdf exporter wants this:

<pre>
$$
x = y \
    + z
$$
</pre>

I'm jumping back and forth b/w pdf and docx a lot, seems like it would be good to be consistent.

PS - To be clear, they should both be equivalent to:

<pre>
$$
x = y + z
$$
</pre>

**Comment by jkr** [comment]
Could you post your input file (or at least the relevant equation) and the pandoc invocation you used so we can try to reproduce?

**Comment by johnlb** [comment]
It is reproducible with those examples on their own (first ex fails under pdf export, second ex fails under docx export). Command line I run:

`pandoc -o test.pdf test.md`

**Comment by jkr** [comment]
The output to pdf works fine for me. I assume you're using an old version of pandoc? What's the output of `pandoc -v`? 

The output of the second one doesn't fail to produce a docx, but the equation doesn't come out correctly -- I'll check it out.

In the future, for bug reports, please be more specific about what you mean by "fail": explain what you expected to happen, and what happened instead. "It didn't work" can mean lots of different things.

**Comment by jkr** [comment]
Hmm... well the TeX reader in texmath can't handle the second one. Both work for me with pdf output, but that's because texmath just hands LaTeX the equations unchanged, and TeX does the right thing. It fails to convert this one to OMML, though:

~~~
$$
x = y \
    + z
$$
~~~

@jgm: do you think the backslash linebreak is something texmath should handle? See below:

~~~
> readTeX "\nx = y \n    + z\n"
Right [EIdentifier "x",ESymbol Rel "=",EIdentifier "y",ESymbol Bin "+",EIdentifier "z"]
> readTeX "\nx = y \\\n    + z\n"
Left "x = y \\\n    ^\nunexpected \"+\"\nexpecting \"%\", \"\\\\label\", \"\\\\nonumber\" or whitespace"
~~~

**Comment by johnlb** [comment]
FYI, I'm getting a compile error when exporting to pdf (they are both different errors, which is why I opted to see what you got when reproducing). I haven't had a chance to check the version on that system, but I'll get that later tonight.

**Comment by jkr** [comment]
Ok, well if it's a recent version, it would be helpful to see those errors.

**Comment by jgm** [comment]
@jkr I had no idea you *could* put a bare backslash in LaTeX math without an error.  (For a line berak you use a double backslash.) It doesn't seem to have any effect on the output at all.  I'm happy to support it, but I'd like to figure out better what it means in tex.  My current assumption is that backslash newline is equivalent to backslash space -- i.e. a space character?

**Comment by jgm** [comment]
Confirmed experimentally that backslash + newline works like backslash + space and inserts a space.
I'll change texmath to handle this.

**Comment by jgm** [comment]
@johnlb - for now use backslash + space in the input (instead of backslash + newline) if you really want a hard space.  Otherwise just omit the backslash entirely.

**Comment by johnlb** [comment]
@jkr FYI, pandoc 1.17.2 though it probably got updated since last time I was on here. I'm not seeing the compile error with pdf output anymore.

Thanks!
