### ISSUE TITLE
md to OMML (docx) parsing error

### ISSUE THREAD

**Issue by robert-debian** [jgm/pandoc#3190]
Hi, I just tested the formula features of Pandoc. Processing the .md with the standard deviation formula:

$s=\sqrt{\frac{1}{N-1}\sum_{i=1}^N(x_i-\overline{x})^{2}}$

gave the expected result in the pdf.

However, in the docx (opened with LibreOffice), it was

s = sqrt {{1} over {N − 1} sum from {i = 1} to {N} {{x} rsub {i} − overline {x} {)} ^ {2}}  }
instead of
s = sqrt {{1} over {N − 1} sum from {i = 1} to {N} {{\(x} rsub {i} − overline {x} \) ^ {2}}  }
(the parentheses () are wrong).

Is this a Pandoc bug?

Best Regards, Robert

**Comment by jkr** [comment]
Not sure I understand your notation, but I seem to get the same result in  docx (opened in word in a virtualbox vm) and pdf. See below:

 ![docx](https://cloud.githubusercontent.com/assets/835121/19779845/d55bf612-9c50-11e6-9444-de83170e08ce.png)


![pdf](https://cloud.githubusercontent.com/assets/835121/19779853/ddfd0022-9c50-11e6-80aa-3cf6c0b52fb1.png)

**Comment by jkr** [comment]
What version of pandoc and texmath are you using (`pandoc -v`)?

**Comment by robert-debian** [comment]
pandoc 1.16.0.2
Compiled with texmath 0.8.4.2, highlighting-kate 0.6.1.

This is the official Fedora 24 version.

**Comment by jkr** [comment]
That's a somewhat old release -- we just released 1.18 yesterday. In any case, the output I posted above looks correct, right? 

I don't know if you were encountering t a problem with LibreOffice's filters or an old version of texmath (the library pandoc uses for its math conversions). But the current pandoc seems to be doing the right thing. So, closing, unless you have any objections.

**Comment by robert-debian** [comment]
Thanks a lot; I will upgrade and report any issues. I'm just writing an 
article about using Pandoc in scientific writing, so I have to make 
sure, formula work. Best Regards, Robert

**Comment by tarleb** [comment]
That article sounds interesting.  I recently gave a brief 10min talk on the potential of Pandoc for open science.  Please contact me by mail if you'd be interested in discussing this.  The [press](http://pandoc.org/press.html) page is also a good resource.

**Comment by robert-debian** [comment]
Hi Albert,

sounds good; Can you reply from your private/ institutional email, to 
get in touch?

Best Regards,

Robert (robert.winkler@cinvestav.mx )
