### ISSUE TITLE
Add latexmk as pdf engine

### ISSUE THREAD

**Issue by memeplex** [jgm/pandoc#3195]
pandoc is pretty slow generating pdfs because it calls the latex engine twice or trice each time the pdf is produced. It's possible to generate a tex file and externally call latexmk but then the burden of managing auxiliary files (including the intermediate tex output) is on the user side. What do you think about adding latexmk as a new latex engine, so that it chooses the appropriate number of runs in a smarter way?

**Comment by jgm** [comment]
Why not?  But then of course, does one use `latexmk -xelatex`, `latexmk -lualatex`, etc.?

**Comment by memeplex** [comment]
I think the system default will be just fine. When not you can pass `--latex-engine-opt`.

**Comment by jgm** [comment]
Actually I'm skeptical that this will help at all.  You need a minimum of two runs to get PDF bookmarks right, so any document with headings needs this.  Pandoc will do two runs normally, or three if you have a table of contents (since then it needs page numbers).  I think latexmk would do the same.  Since everything gets called in a temp directory, you wouldn't get the advantages latexmk normally has of relying on auxiliary files generated by a previous run.

**Comment by memeplex** [comment]
Currently I run a script that produces tex via pandoc then calls latexmk. I
keep temporary files in a "hidden" directory that looks something like:
/tmp/myscript/mydoc. This way I let latexmk use the files generated by
previous run without cluttering the working directory.

**Comment by jgm** [comment]
Yes, that's a good way to go.  But I don't want pandoc, by
default, to create any new non-temporary files besides the
one requested by the user.  So I wouldn't want to create
a latexmk path to PDF that leaves things in a hidden
directory.

+++ memeplex [Nov 06 16 05:13 ]:

**Comment by memeplex** [comment]
Ok, then I would say your concerns about not taking advantage of latexmk
are true, so this can be closed for good. Thanks for pondering over the
proposal.

**Comment by jgm** [comment]
I want to reopen this, because using latexmk would have some advantages (automatically running biber, mkindex, etc.).  I think we could still avoid creating a persisting hidden temp directory by doing everything within a temp dir that we then delete.

**Comment by jgm** [comment]
I suppose we could also contemplate a command-line option that specifies a persisting temp directory.

**Comment by jgm** [comment]
Looks like `-outdir $DIR` will put all the extra files in $DIR.
So we can just set this to a temp directory.

**Comment by jgm** [comment]
Note also that `latexmk -outdir=foo -outdir=bar` puts the files in `bar`.
So if we specify the outdir in a temp directory first, users can override this using `--pdf-engine-opt=-outdir=bar` if they want to specify a persistent directory for intermediate files.
