### ISSUE TITLE
file:// urls as inputs raise error

### ISSUE THREAD

**Issue by janschulz** [jgm/pandoc#3196]
I'm trying to teach pandoc to open URLs (part of pypandoc https://github.com/bebraw/pypandoc/issues/108) and as a testcase I used local "file://" urls, but it seems that pandoc doesn't like them:

```
λ echo "# headline" > test.md
# works, chrome opens the URL 
λ "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" file:///c:/data/external/pypandoc/test.md
λ pandoc file:///c:/data/external/pypandoc/test.md -t html
pandoc: file:///c:/data/external/pypandoc/test.md: openFile: invalid argument (Invalid argument)
```

Is that expected behaviour, or did I make a mistake when constructing this URLs, or is this a pandoc problem?

**Comment by jgm** [comment]
Currently pandoc only treats an argument as a URL if
it has http or https protocol.  I can't recall now whether
there's any particular reason for this limitation.  It
would be easy enough to lift it, but there may be something
I'm not remembering that caused me to put it there in
the first place...

+++ Jan Schulz [Oct 29 16 13:59 ]:

**Comment by janschulz** [comment]
Thanks!
