### ISSUE TITLE
Pandoc inhibiting images to be attached to Markdown document

### ISSUE THREAD

**Issue by parthkhare** [jgm/pandoc#3202]
Hi,

Have been on wild goose chase trying to upload local image files in a R Markdown document.
Am getting following error `pandoc.exe:Could not fetch Image.png`. Greatly appreciate your help on the same.

**Comment by jgm** [comment]
If you're getting this in the context of R Markdown, it's
best to take this up with R Markdown developers, who can
escalate here if it looks like a problem with pandoc itself.

In any case you haven't given us enough information for us to
be of much help...  What we'd need is detailed instructions for
reproducing the problem, using pandoc itself.  (Pandoc
version, exact command used, exact input file used and
information on the locations of relevant image files, etc.)


+++ Parth [Nov 01 16 12:56 ]:
