### ISSUE TITLE
Docx reader is not rendering the alt text or title of an image

### ISSUE THREAD

**Issue by manoj-compro** [jgm/pandoc#3204]
`I` am converting an docx file into markdown using option --extract-media (stored images in media folder and name these as image1, image2...).
`![](media/image1.jpeg)`
I think bracket here should contains the alt text of image given in docx file.
is there any option for this?

**Comment by jgm** [comment]
If you tell us how alt and title are represented in docx
(perhaps just give us a very short docx file where these
are set, so we can inspect it), we might be able to
implement this. @jkr

+++ Manoj Saini [Nov 02 16 06:26 ]:

**Comment by manoj-compro** [comment]
[MoveProfiles-Advanced.docx](https://github.com/jgm/pandoc/files/566796/MoveProfiles-Advanced.docx)


![2016-11-02_19-58-19](https://cloud.githubusercontent.com/assets/22838010/19932655/e27b0c26-a136-11e6-818f-a82dc25efc47.png)


`![](./02-MoveProfiles/media/MoveProfiles-Advanced/media/image2.svg)`

**Comment by manoj-compro** [comment]
docx  file: 
[Doc1.docx](https://github.com/jgm/pandoc/files/566813/Doc1.docx)
 
markdown file output : ![](media/image1.jpeg)

Here bracket does not have alt or title text given in docx
![alttext](https://cloud.githubusercontent.com/assets/22838010/19932985/f430ee1c-a137-11e6-9cf1-1320990aaba8.png)

**Comment by jkr** [comment]
Thanks @manoj-compro. On it.

**Comment by manoj-compro** [comment]
i used this latest code after  [commit](https://github.com/jgm/pandoc/commit/5684577da557b2fd3e44e648d1af94cb1367610f)  and getting an error on executing following command:
pandoc -S "abc.docx" --extract-media="./01-Fundamentals/media/Fundamentals-Bandwidth" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "abc.md"

Looks like there is an issue with docx writer or json reader. 
Error : 
`F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:36
  return walk(data, action, format, data[0].unMeta);
                                           ^

TypeError: Cannot read property 'unMeta' of undefined
    at filter (F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:36:44)
    at F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:27:18
    at Socket.<anonymous> (F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\node_modules\get-stdin\index.js:13:3)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

CallStack (from HasCallStack):
  error, called at src\Text\Pandoc\Error.hs:55:28 in pandoc-1.18-HKxHsqdA55OEaZdJ0GHVBK:Text.Pandoc.Error`

**Comment by jgm** [comment]
You need to update your filter to use the new JSON format,
as described in the changelog for pandoc 1.18.

**Comment by jkr** [comment]
Unrelated to this fix. Looks like your node filter library needs to be updated. (There's a new JSON format. It looks like the library now recognizes it.)
On Nov 3, 2016 7:30 AM, Manoj Saini <notifications@github.com> wrote:i used this latest code after  commit  and getting an error on executing following command:
pandoc -S "abc.docx" --extract-media="./01-Fundamentals/media/Fundamentals-Bandwidth" -t json | node pandoc_filter.js  | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "abc.md"

Looks like there is an issue with docx writer or json reader. 
Error : 
`F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:36
  return walk(data, action, format, data[0].unMeta);
                                           ^

TypeError: Cannot read property 'unMeta' of undefined
    at filter (F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:36:44)
    at F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:27:18
    at Socket. (F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\node_modules\get-stdin\index.js:13:3)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

CallStack (from HasCallStack):
  error, called at src\Text\Pandoc\Error.hs:55:28 in pandoc-1.18-HKxHsqdA55OEaZdJ0GHVBK:Text.Pandoc.Error`

**Comment by manoj-compro** [comment]
It worked!!
Thanks @jgm  and @jkr
