### ISSUE TITLE
underscore not recognized as emphasis

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#3206]
[As shown in the website](http://pandoc.org/try/?text=[Arist%C3%B3teles]{.author}%2C+_%C3%89tica+a+Nic%C3%B3maco_%2C%0A%0A[Arist%C3%B3teles]{.author}%2C+*%C3%89tica+a+Nic%C3%B3maco*%2C%0A%0A+_%C3%89tica+a+Nic%C3%B3maco_%2C%0A%0A+*%C3%89tica+a+Nic%C3%B3maco*%2C%0A%0A&from=markdown&to=html), pandoc-1.18 seems not to be able to always convert underscore pairs to emphasis. However, asterisks are recognized fine.

``` markdown
[Aristóteles]{.author}, _Ética a Nicómaco_,

[Aristóteles]{.author}, *Ética a Nicómaco*,
```

is parsed by pandoc as:

``` html
<p><span class="author">Aristóteles</span>, _Ética a Nicómaco_,</p>
<p><span class="author">Aristóteles</span>, <em>Ética a Nicómaco</em>,</p>
```

I’m on Fedora 23. I’m afraid it might be a bug.

**Comment by jgm** [comment]
Very strange - small changes in the input make the emph come back.  Perhaps most strikingly:
```
[Aristoteles]{.author}, _etica a nicomaco_, => no emph
[Aristotele]{.author}, _etica a nicomaco_,  => emph
```
What on earth?

**Comment by jgm** [comment]
Another data point: If you turn off `bracketed_spans`, you get emphasis again.

**Comment by jgm** [comment]
More data
```
[Aristoteles]{.author}, _e_  => no emph
[Aristoteles]{.author} _e_  => emph
```
I'm really at a loss; there's nothing evident in the code that could be sensitive to these sorts of differences.

**Comment by jgm** [comment]
OK, I've got a hypothesis.  It has to do with bad interactions between the use of `parseFromString` in `inlinesInBalancedBrackets` (used in parsing the bracketed span) and `updateLastStrPos` (which ultimately affects pandoc's decision about when `_` is intraword).  When we use `parseFromString` we are no longer properly tracking our location in the source, and so the thing pandoc is storing as the location of the last Str element will be wrong. This is all pretty ugly stuff (CommonMark parser has a far more elegant way of handling these things), but not a trivial thing to fix.

**Comment by jkr** [comment]
One more observation to add: inline links, which share a similar surface syntax, do work. I realize the internals are likely different -- still trying to wrap my head around the reader -- but thought it worth pointing out:

~~~
$ echo '[Aristoteles](.author), _e_'|pandoc
<p><a href=".author">Aristoteles</a>, <em>e</em></p>
$ echo '[Aristoteles]{.author}, _e_'|pandoc
<p><span class="author">Aristoteles</span>, _e_</p>

~~~

**Comment by jkr** [comment]
@jgm, I've got a lot of (randomized) data for you. See here: https://gist.github.com/jkr/f7910979de3b3a16b8a2e0e641b0def2

These are all failing cases. The first column is the number of characters in the label, the second column is the number of characters in the class, the third column is the number of chars in the sep (comma in your examples), fourth column is the sep, and fifth column is the input.

These were randomized with text and class both being alph with length 1-30 and the sep being alph or punct with length 1-5.

Here are the things to note:

 1. In *every* case, `len(text) = len(class) + len(sep) + 4`. This corresponds to the Aristotle example above where `len(Aristoteles) = 11; len(author) = 6; len(,)=1`. 

 2. In nearly every case, the sep is all punctuation. There seem to be a few cases where it can be mixed punctuation and alph, but that might be python's output -- I haven't looked closely enough. Note that if you change the comma in your above test, the emphasis comes out properly.

Not sure what this all means, but I hope it can point things forward a bit.

**Comment by jkr** [comment]
Follow-up: this isn't in the data, but it will also fail when `len(sep)=0`, i.e. when the text is 4 greater than the class: `[abcde]{.f} _hi_`

**Comment by jkr** [comment]
And here's the sloppy test program I whipped up, if you want to mess with it:

https://gist.github.com/jkr/99c86b0a027182fe15ae277c3c352aba

**Comment by jgm** [comment]
Actually, I understand exactly what is happening here.
It has to do with the interaction between parseFromString
and the hack we use to detect intraword emphasis (storing
last Str position), given that we can't do lookbehind in
parsec.

If we could do lookbehind this would be trivial.

**Comment by jgm** [comment]
This seems to have now been fixed by changes in parseFromString.
