### ISSUE TITLE
Link reference labels fail when beginning with `@`

### ISSUE THREAD

**Issue by kgryte** [jgm/pandoc#3209]
Tested in `pandoc` versions: `1.11` and `1.18` (latest).

## Command

``` bash
$ pandoc --from=markdown_github-citations --to=html5 <file.md>
```

where `<file.md>` has contents

```
doi:[10.1007/BF02293108][@ahrens:1974]

[@ahrens:1974]: http://dx.doi.org/10.1007/BF02293108
```

## Output

`pandoc` generates the following output

``` html
<a href="doi:%5B10.1007/BF02293108%5D%5B@ahrens:1974%5D" class="uri">doi:[10.1007/BF02293108][@ahrens:1974]</a>
```

## Expected Output

The expected output should match GitHub and the commonmark spec (see [demo](http://spec.commonmark.org/dingus/?text=doi%3A%5B10.1007%2FBF02293108%5D%5B%40ahrens%3A1974%5D%0A%0A%5B%40ahrens%3A1974%5D%3A%20http%3A%2F%2Fdx.doi.org%2F10.1007%2FBF02293108)).

``` html
doi:<a href="http://dx.doi.org/10.1007/BF02293108">10.1007/BF02293108</a>
```

## Debugging

If I insert a space as follows `doi: [10.1007/BF02293108][@ahrens:1974]`, `pandoc` still does not return the expected output.

``` html
doi: [10.1007/BF02293108]<a href="http://dx.doi.org/10.1007/BF02293108">@ahrens:1974</a>
```

If I remove the `@` symbol to check whether `pandoc` is confused by a possible citation,

```
doi:[10.1007/BF02293108][ahrens:1974]

[ahrens:1974]: http://dx.doi.org/10.1007/BF02293108
```

`pandoc` returns similar results

``` html
<a href="doi:%5B10.1007/BF02293108%5D%5Bahrens:1974%5D" class="uri">doi:[10.1007/BF02293108][ahrens:1974]</a>
```

Disabling `autolink_bare_uris`

``` bash
$ pandoc --from=markdown_github-citations-autolink_bare_uris --to=html5 <file.md>
```
gives the following results

``` html
doi:[10.1007/BF02293108]<a href="http://dx.doi.org/10.1007/BF02293108">@ahrens:1974</a>
```

Finally, replacing the colon with a space `doi [10.1007/BF02293108][@ahrens:1974]` yields the following

``` html
doi [10.1007/BF02293108]<a href="http://dx.doi.org/10.1007/BF02293108">@ahrens:1974</a>
```

## Background

The Markdown file in question contains a citation reference generated by `pandoc`

```
Ahrens, J.H., and U. Dieter. 1974. "Computer methods for sampling from gamma, beta, poisson and bionomial distributions." *Computing* 12 (3): 223–46. doi:[10.1007/BF02293108](https://doi.org/10.1007/BF02293108).
```
with the modification that, instead of an inline link, a reference link is used.

```
Ahrens, J.H., and U. Dieter. 1974. "Computer methods for sampling from gamma, beta, poisson and bionomial distributions." *Computing* 12 (3): 223–46. doi:[10.1007/BF02293108][@ahrens:1974].

[@ahrens:1974]: https://doi.org/10.1007/BF02293108
```

**Comment by jgm** [comment]
We recognize

    doi:[10.1007/BF02293108][@ahrens:1974]

as a bare URI because technically, it is a valid URI,
and markdown_github has the autolink_bare_uris extension
enabled.

Evidently GitHub itself only recognizes some valid
URIs.  We could follow, excluding literal square bracket
characters.

+++ Athan [Nov 03 16 03:35 ]:

**Comment by kgryte** [comment]
While not required by all schemes, my understanding is that, in the usual case, if a `scheme` is provided, e.g., `http`, the scheme is [followed by](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) a colon and two forward slahes: `http://`. Hence, the above would fail to be recognized as a valid absolute URI.

`doi` is not a registered [IANA scheme](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), and the [DOI](https://www.doi.org/factsheets/DOIIdentifierSpecs.html) specification does not indicate that `doi:` should be considered a valid absolute URI. And `doi` is not a recognized [URN](http://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml) namespace.

So I am not convinced that `doi:[...]` should be parsed as a valid URI.

**Comment by kgryte** [comment]
Additionally, based on the above, even if `doi:[...]` is recognized as a URI, this does not explain why

```
doi [10.1007/BF02293108][@ahrens:1974]
```
is incorrectly converted to 

``` html
doi [10.1007/BF02293108]<a href="http://dx.doi.org/10.1007/BF02293108">@ahrens:1974</a>
```
even when the `citations` extension is disabled.

**Comment by jgm** [comment]
Sorry, I jumped to conclusions.  You are right.  Here's an input that demonstrates the issue a bit more clearly:
```
[link text][@a]

[@a]: url

[link text][b@a]

[b@a]: url
```
Here `link text` is hyperlinked in the second case but not in the first (even with `-f markdon-citations`).

**Comment by jgm** [comment]
Culprit is this line
https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/Markdown.hs#L1777
which forbids something that parses as a citation from being a link label in a reference link.

Now I need to remember why I put that there in the first place...

**Comment by jgm** [comment]
#1763 was the issue that caused this to be inserted.

**Comment by jgm** [comment]
My suggestion would be to avoid using `@` at the beginning of reference link labels.
If you must do this, then backslash-escape the `@`.

**Comment by jgm** [comment]
I'll change the code so that this condition is used only when `citations` extension is enabled.

**Comment by kgryte** [comment]
@jgm Thanks!
