### ISSUE TITLE
Add a way to set a default location to search for pandoc-citeproc files

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#3212]
I use --- YAML METADATA --- at the top of my pandoc files and have just switched to using pandoc-citeproc for citations. I put my citeproc files in the default pandoc data-dir location (`$HOME/.pandoc/`). If I use hard-coded paths everything works:

```YAML
bibliography: /Users/ian/.pandoc/refs.bib  
csl: /Users/ian/.pandoc/cerebral-cortex.csl  
```

But if I try to let pandoc find them in  the default data-dir location:

```YAML
bibliography: refs.bib  
csl: cerebral-cortex.csl  
```

then pandoc can't find the citeproc files:

```
👉  pandoc --filter pandoc-citeproc CerCor.R2.md -o CerCor.R2.docx
pandoc-citeproc: cerebral-cortex.csl: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

Even if I force the data-dir on the commandline:

```
👉  pandoc --filter pandoc-citeproc --data-dir=$HOME/.pandoc CerCor.R2.md -o CerCor.R2.docx
pandoc-citeproc: cerebral-cortex.csl: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

I'd rather not hard-code the full paths in the document, but still want to use YAML metadata to specify which citeproc files to use.

Pandoc version (pandoc installed on macOS 10.12 via homebrew):
```
👉  pandoc --version
pandoc 1.18
Compiled with pandoc-types 1.17.0.4, texmath 0.8.6.6, highlighting-kate 0.6.3
Default user data directory: /Users/ian/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
`pandoc-citeproc` doesn't know anything about the `data-dir` set by pandoc; it's a separate program, remember.

`pandoc-citeproc` already looks in the `~/.csl` directory for CSL files.
So that just leaves the bibliography files.  Here see jgm/pandoc-citeproc#150.
It seems a bit arbitrary for pandoc-citeproc to look in `~/.pandoc`, though, especially when pandoc might have shifted the user data directory elsewhere, for all pandoc-citeproc knows.

**Comment by iandol** [comment]
Hi John, is there a simple way Pandoc could pass its current `data-dir` to pandoc-citeproc when it is run? Personally I think having one directory with all pandoc dependencies makes some sense, in my naive view, these files are needed by pandoc to enable a conversion (I know technically pandoc doesn't support citations but isn't this splitting hairs?)

Another idea, create a default `~/.pandoc-citeproc` directory in the search path of pandoc-citeproc for .csl, .bib, and abbreviations files?

**Comment by jgm** [comment]
One way would be for pandoc to set an environment variable
PANDOC_DATA_DIR when it calls pandoc-citeproc.
pandoc-citeproc could then check this.

However, a more flexible idea might be to have
pandoc-citeproc check an environment variable
PANDOC_CITEPROC_BIB_PATH or something like that.
This could even have multiple paths.

+++ Ian [Nov 06 16 03:35 ]:

**Comment by iandol** [comment]
Either would work in my case (and they aren't mutually exclusive, however I do have a preference for the former and I suspect this one-size-fits-all general location is more transparent for normal users). But yes I imagine some users may have a specific separate bibliography folder they'd like to use.

For the env var option the the only issue is the name should be generic; there are so many supported formats you don't want an env var for each bibliography format, plus csl path and abbreviations path 😄

**Comment by iandol** [comment]
I'll close this in lieu of a slightly updated #5982
