### ISSUE TITLE
Rendering formulas in Beamer

### ISSUE THREAD

**Issue by tpaskhalis** [jgm/pandoc#3213]
Thank you very much for this great package!

I've started using it recently and ran into a problem when producing beamer slides with nested latex expressions. Specifically, running `pandoc -t beamer slides.md -o slides.pdf` on this markdown code:
```
# Formula
$\hat{\sigma} = \sqrt{\frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}}$
``` 
results in the equation that has square root sign stretched vertically more than needed (as if it expects another fraction underneath). However, when producing regular pdf file with `pandoc slides.md -o slides.pdf`, the rendering of this formula is perfectly fine.

I'm using pandoc 1.18.

**Comment by jgm** [comment]
This must be a beamer issue (not pandoc), because pandoc
produces the same tex math code in latex or beamer output.

**Comment by jgm** [comment]
Btw I don't see any stretching when I try this.
