### ISSUE TITLE
Textile writer doesn't work with org-mode reader and lower headings converted to lists

### ISSUE THREAD

**Issue by kepi** [jgm/pandoc#3216]
Since pandoc 1.17.2 there is new option in org reader which converts heading lower then certain level to lists. This is by default 3.

There was already some discussion about it in #3214 

```
* heading one
text
** heading two
text
*** heading three
text
**** heading four
text
```

In current version of pandoc output from org to textile conversion is wrong:

```
h1(#heading-one). heading one

text

h2(#heading-two). heading two

text

h3(#heading-three). heading three

text

<ol>
<li><p>heading four</p>
<p>text</p></li>
</ol>
```

I'm not sure if problem is in org reader or textile writer. If I try simple list in org:

```
* List test

** Bullet lists

- one
- two
  - second level
  - second leve
- three

** Numbered lists

1. one
  1. second level
  1. second level
2. two
3. three
```

it works without any problem, output is correctly:

```
h1(#list-test). List test

h2(#bullet-lists). Bullet lists

* one
* two
** second level
** second leve
* three

h2(#numbered-lists). Numbered lists

# one
## second level
## second level
# two
# three
```

**Comment by kepi** [comment]
Btw. as @tarleb mentioned in #3214 you can set H option in org file i.e. to 9 and headings will be exported as headings. But it is only workaround and doesn't work as intended.

```
#+OPTIONS: H:9
```

**Comment by jgm** [comment]
As far as I know, there's no native Textile way to have
a list item that includes two paragraphs.  That's why
the Textile writer falls back to HTML in this case.
If I'm wrong about Textile, please let me know.

**Comment by kepi** [comment]
Yes, it is possible (at least in Redmine which uses Redcloth for rendering):

```
# first paragraph

  second paragraph

  third paragraph
# test
# best
```

Tt can be used for both normal and numbered lists.

**Comment by jgm** [comment]
This doesn't work in the "Try RedCloth" box at http://redcloth.org

**Comment by jgm** [comment]
Nor is it documented in their documentation.

**Comment by kepi** [comment]
I see. It is working in RedCloth 3 (which is used in Redmine). I know it isn't documented, I found dicussion about implementation in some bug report on redcloth issue tracking.

Anyway as it is working at least somewhere, it is clearly much better solution than throwing output in html which is totaly unreadable and unusable.

Clearer solution would be to ignore heading limit for textile export as it isn't working but I'm not sure if it is easily possible.

**Comment by jgm** [comment]
+++ Kepi [Nov 10 16 03:56 ]:
>   I see. It is working in RedCloth 3 (which is used in Redmine). I know
>   it isn't documented, I found dicussion about implementation in some bug
>   report on redcloth issue tracking.
>
>   Anyway as it is working at least somewhere, it is clearly much better
>   solution than throwing output in html which is totaly unreadable and
>   unusable.

Well, I still don't know what the general rules are supposed to be,
without any documentation.

And, I don't think we should support something that is only
available in one version which isn't documented...

>   Clearer solution would be to ignore heading limit for textile export as
>   it isn't working but I'm not sure if it is easily possible.

Readers are always independent of writers in pandoc, so
reader settings don't vary with the writer.  You
should simply set this parameter yourself.

**Comment by kepi** [comment]
I have no problem with not supporting undocumented features. But IMHO we need to decide what to do with output to write it in textile. Current behavior is broken as output is in textile/html mix, not in textile.

It seams to me that there are three options:

1. leave it in current broken state
2. remove any formatting when we are unable to write it correctly and just output text
3. implement solution which is working at least in Redmine

From user perspective - 3 is best as it is in fact almost same as in 2 and it renders useful document.

From pandoc perspective - 2 might be better. To be honest I'm not aware of pandoc goals and I don't want to talk to how it should be done. I can imagine why it is better to just not support undocumented features.

1 is wrong IMHO for all.

If you decide to go with 3, I'm willing to find at least exact Redmine implementation for this so it is similar and you don't have to study it yourself.

**Comment by jgm** [comment]
+++ Kepi [Nov 10 16 06:19 ]:
>   I have no problem with not supporting undocumented features. But IMHO
>   we need to decide what to do with output to write it in textile.
>   Current behavior is broken as output is in textile/html mix, not in
>   textile.

On the contrary, it is valid textile -- because HTML is
allowed in textile (again, try it in the dingus and see the
RedCloth 4 manual, under "HTML integration").

Pandoc falls back to this when there's no non-HTML solution.
So the current state is not "broken."

**Comment by ickc** [comment]
> implement solution which is working at least in Redmine

In addition to the point that it is currently not broken but a valid textile, your "best" option makes the ouput broken, since it is invalid and the output depends on the parser.

**Comment by kepi** [comment]
I didn't know about HTML integration. I'm closing this issue as in theory there is no issue at all. 

For me workaround is enough. I simply failed in my effort to make pandoc better :) I clearly shouldn't even try to think that textile is sensible format in any way.
