### ISSUE TITLE
beamer writer doesn't output `\hypertarget` in header correctly

### ISSUE THREAD

**Issue by Frefreak** [jgm/pandoc#3220]
For this test snippet
```markdown
# Header1 {#head1}

## abc {#abc}

text under abc

## def {#def}

text under def

link to [abc](#abc)
```
I want the link under **def** points to **abc** header, the beamer output this by invoking `pandoc test.md -t beamer`:
```latex
\section{Header1}\label{head1}

\begin{frame}{abc}

text under abc

\end{frame}

\begin{frame}{def}

text under def

link to \protect\hyperlink{abc}{abc}

\end{frame}
```
the generated pdf does contains a link but when clicked it redirects to the first page. If I manually add `\hypertarget{abc}{}` before the `\begin{frame}{abc}` line and disable **ignorenonframetext** (which I know from this SO [question](http://stackoverflow.com/questions/28264805/internal-section-link-fails-in-beamer-output-of-pandoc-markdown)) the link works as expected.

Is this behaviour expected? Is there any easier way without manually modifying generated latex code to achieve the same effects? The latex writer (`-t latex`) seems create the link correctly though.

**Comment by georgejean** [comment]
Hi,

it seems that
```markdown
# Header1 {#head1}

## \hypertarget{abc}{abc}

text under abc

## def {#def}

text under def

link to [abc](#abc)
```
does the job.

**Comment by Frefreak** [comment]
Thanks! In this way the link points to the content under the header rather than the header itself (tried in okular), but this is totally acceptable.

**Comment by jgm** [comment]
Should this really be closed?  This seems like a workaround;
if there's a problem in pandoc, it should be fixed.

**Comment by Frefreak** [comment]
I didn't notice the username and thought that was the "official response" to this...  Is it possible to make this work without inline latex code?

**Comment by georgejean** [comment]
According to the doc

> **Frame attributes in beamer**
Sometimes it is necessary to add the LaTeX [fragile] option to a frame in beamer (for example, when using the minted environment). This can be forced by adding the fragile class to the header introducing the slide:
\# Fragile slide {.fragile}
All of the other frame attributes described in Section 8.1 of the Beamer User’s Guide may also be used: allowdisplaybreaks, allowframebreaks, b, c, t, environment, label, plain, shrink.

i think that the pandoc's way to do that should be something like

```markdown
# Header1 {#head1}

## abc {.label = abc}

text under abc

## def 1 {.label = def}

text under def

## otherdef

link to [abc](#abc)

link to [def 1](#def)
```
My expected output for `## def 1 {.label = def}` would be `\begin{frame}[label=def]{def 1}`.
but I get `\begin{frame}{def 1 \{.label = def\}}`
so it doesn't work. I don't know how to use a valued option to a frame.

**Comment by jgm** [comment]
use `{label=def}`, not `{.label = def}`, which isn't a valid
attribute block in pandoc.  (See the manual under
attributes.)

+++ georgejean [Nov 12 16 04:20 ]:

**Comment by alex-ball** [comment]
Note that, in normal HTML, LaTeX, and ConTeXt and in other slide outputs, links to headings of whatever level work as advertised. The same is true of Beamer output *except* for whatever heading level is selected as the slide level.

(Okay, for the above-slide-level links to work you have to remove [ignorenonframetext] from the class options.)

Surely it makes sense to routinely add the `label` attribute (with the auto-generated ID) to all frames in Beamer output to eliminate this inconsistency? It is something of a chore to ask the author to add them all manually for that one heading level...

**Comment by jgm** [comment]
@Frefreak - Disabling `ignorenonframetext` would have a number of other consequences which would amount to a breaking change.

For this reason @georgejean's approach, which puts the hypertarget inside the frame title, seems better.  (Of course, pandoc should do this automatically rather than making the user put in raw latex.)

This should be an easy change; I'll put in in the pandoc 2.0 milestone.
For reference, here's what the latex would look like:
``` latex
\begin{frame}{\hypertarget{abc}{abc}}

text under abc

\end{frame}

\begin{frame}{\hypertarget{def}{def 1}}

text under def

\end{frame}

\begin{frame}{\hypertarget{otherdef}{def 2}}

link to \protect\hyperlink{abc}{abc}

link to \protect\hyperlink{def}{def 1}
```

**Comment by Frefreak** [comment]
Thank you. At that time I would use `{#abc}` instead of `{label = abc}` right?

**Comment by jgm** [comment]
+++ Frefreak [Mar 15 17 18:23 ]:
>   Thank you. At that time I would use {#abc} instead of {label = abc}
>   right?

Correct.
