### ISSUE TITLE
Org: ATTR_HTML still not working?

### ISSUE THREAD

**Issue by hrehfeld** [jgm/pandoc#3222]
$ echo "#+ATTR_HTML: :class small
    [[./img.jpg]]
    " | pandoc -t html5 -f org

    <p><img src="./img.jpg" /></p>

while org-mode outputs:

    <figure>
    <p><img src="./img.jpg" alt="img.jpg" class="small">
    </p>
    </figure>

even though this was supposed to be fixed in #1906 ?

Version is 1.18 from git after the ATTR_HTML block fix.

Sorry for running into so many corner cases! :-)

**Comment by tarleb** [comment]
Did you compile yourself or use the current 1.18 release?  The change hasn't made it into any release yet, can you try it with the current master?  See [INSTALL](https://github.com/jgm/pandoc/blob/master/INSTALL.md#compiling-from-source) for details on how to do that.

**Comment by tarleb** [comment]
Please ignore my previous comment.  `ATTR_HTML` for images hasn't been implemented yet.

> Sorry for running into so many corner cases! :-)

On the contrary, thank you for using pandoc reporting all of those missing features.

**Comment by tarleb** [comment]
That specific issue should be fixed now.  I still expect that there are remaining issues with other elements for which the `ATTR_HTML` is currently ignored. Please report them whenever you find one.

As a side note: there is a slightly annoying discrepancy between the org-mode LaTeX and HTML exporters (tested with v8.3.5): The LaTeX exporter will interpret the example you gave as a simple image, while the HTML exporter will treat the image like a figure.  Pandoc behaves more like the LaTeX exporter and will accept the image only as a figure if it is preceded by a `#+CAPTION:`.

**Comment by hrehfeld** [comment]
Thanks for the quick fix, the class comes out now.

However, there's a regression/new bug:

    #+begin_somediv
    [[./img.jpg]]
    [[./img.jpg]]
    #+end_somediv
    
    #+begin_somediv
    [[./img.jpg]] some text
    [[./img.jpg]]
    #+end_somediv


creates an extra paragraph if there's no text with the images:

    $ pandoc -t html5 /tmp/test2.org
    <div class="somediv">
    <p><img src="./img.jpg" /></p>
    <p><img src="./img.jpg" /></p>
    </div>
    <div class="somediv">
    <p><img src="./img.jpg" /> some text <img src="./img.jpg" /></p>
    </div>

**Comment by hrehfeld** [comment]
Just 

    [[./img.jpg]]
    [[./img.jpg]]

Also generates two ps!

**Comment by hrehfeld** [comment]
(if there is an easy way to add test cases, I could put some in)

**Comment by tarleb** [comment]
That's another case where LaTeX and HTML exporter differ:

``` org-mode
#+CAPTION: test
[[file:1.jpg]]
[[file:2.jpg]]
```

produces 

``` latex
\begin{figure}[htb]
\centering
\includegraphics[width=.9\linewidth]{1.jpg}
\caption{test}
\end{figure}
\begin{figure}[htb]
\centering
\includegraphics[width=.9\linewidth]{2.jpg}
\caption{test}
\end{figure}
```

which (a) seems to imply that each image is a block / paragraph by itself and (b) is very weird behavior. 

Fun corner case to demonstrate that the HTML exporter also has its problems with this kind of situation:

``` org-mode
#+attr_html: :width 50%
[[file:one.png]]
[[file:two.png]]
```

Output:

``` html
<p width="50%">
<img src="one.png" alt="one.png width="50%">
<img src="two.png alt="two.png">
</p>
```

Note how the exporter has difficulties to decide whether this is a figure or a paragraph.

:sigh:

I prefer the slightly saner behavior of the HTML exporter and hence agree that this indeed a regression that needs to be fixed.  Thanks for spotting it.

> `(para $ image "./1.jpg" "" "" $ image "./2.jpg" "" "")`

Almost: `(para $ (image "./1.jpg" "" "") <> (image "./2.jpg" "" ""))`

**Comment by tarleb** [comment]
The regression should be fixed now.  Sorry for the long wait.

**Comment by hrehfeld** [comment]
(This didn't make it into 1.18, right? [Not fixed there.])

**Comment by tarleb** [comment]
Correct. It should work with the current master and will be shipped with the upcoming 1.19 release.

**Comment by jgm** [comment]
+++ Hauke Rehfeld [Nov 29 16 02:21 ]:
>   (This didn't make it into 1.18, right? [Not fixed there.])

correct, it will be in the next release.

**Comment by hrehfeld** [comment]
Hmm, is this a regression or intended behavior? ATTR_HTML were correctly parsed and associated to the images before:

``` org
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]
[[./DSC06724.jpg]]

```
`pandoc --resource-path=src/photography/2017:~/tmp/foo.org --wrap=none --shift-heading-level-by=1 -f org -t json ~/tmp/foo.org | python -mjson.tool`

``` json
{
    "pandoc-api-version": [
        1,
        22
    ],
    "meta": {},
    "blocks": [
        {
            "t": "RawBlock",
            "c": [
                "org",
                "#+ATTR_HTML: :jpeg-quality 95"
            ]
        },
        {
            "t": "Para",
            "c": [
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            []
                        ],
                        [],
                        [
                            "./DSC06738.jpg",
                            ""
                        ]
                    ]
                },
                {
                    "t": "SoftBreak"
                },
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            []
                        ],
                        [],
                        [
                            "./DSC06724.jpg",
                            ""
                        ]
                    ]
                }
            ]
        }
    ]
}
```

This works:

``` org
#+ATTR_HTML: :jpeg-quality 95
[[./DSC06738.jpg]]

[[./DSC06724.jpg]]
```

``` json
{
    "pandoc-api-version": [
        1,
        22
    ],
    "meta": {},
    "blocks": [
        {
            "t": "Para",
            "c": [
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            [
                                [
                                    "jpeg-quality",
                                    "95"
                                ]
                            ]
                        ],
                        [],
                        [
                            "./DSC06738.jpg",
                            ""
                        ]
                    ]
                }
            ]
        },
        {
            "t": "Para",
            "c": [
                {
                    "t": "Image",
                    "c": [
                        [
                            "",
                            [],
                            []
                        ],
                        [],
                        [
                            "./DSC06724.jpg",
                            ""
                        ]
                    ]
                }
            ]
        }
    ]
}
```
