### ISSUE TITLE
Non-standard font type (MIME) Description for woff and woff2 fonts.

### ISSUE THREAD

**Issue by jimholgate** [jgm/pandoc#3228]
# Issue

Non-standard font type (MIME) Description for woff fonts.

# Versions tested

+ pandoc 1.16.0.2  (Ubuntu Linux 16.04)
+ pandoc 1.18 (Windows and MacOS)

# Description

+ Electronic publications produced with pandoc show a MIME 
  type warning when using epubcheck.
+ This is a cosmetic problem. It does not stop programs 
  from using ePub books produced with pandoc.

```
java -jar '~/local/epubcheck-4.0.1/epubcheck.jar' '~/Desktop/notes.epub' 
Validating using EPUB version 3.0.1 rules.
INFO(CSS-007): ./notes.epub/stylesheet.css(34,5): Font-face reference economica-regular.woff refers to non-standard font type application/x-font-woff.
INFO(CSS-007): ./notes.epub/stylesheet.css(41,5): Font-face reference economica-bold.woff refers to non-standard font type application/x-font-woff.
No errors or warnings detected.
```

According to [IANA][1], and [W3][2] the correct MIME type for woff fonts is `application/font-woff`. According to [W3][3], the correct MIME type for woff2 fonts is `font/woff2`.

# How to fix the problem

Apply a patch to `/src/Text/Pandoc/MIME.hs` to correct the MIME types.

```
501,502c501,502
<            ,("woff","application/x-font-woff")
<            ,("woff2","application/x-font-woff2")
---
>            ,("woff","application/font-woff")
>            ,("woff2","font/woff2")

```

  [1]: http://www.iana.org/assignments/media-types/application/font-woff
  [2]: https://www.w3.org/TR/WOFF/
  [3]: https://www.w3.org/TR/WOFF2/

**Comment by jgm** [comment]
Thanks for the excellent report!
