### ISSUE TITLE
csl in metadata

### ISSUE THREAD

**Issue by jlrn7** [jgm/pandoc#3237]
Hello! I'm learning how to process citations with `pandoc-citeproc`, and according to the documentation, I may state a custom CSL template either in the metadata section or in the command line with the `--csl` option; but while the latter works like a charm, the former doesn't quite do it. I've tried with the `csl` file both in the current directory and in Pandoc's home directory. I'm running pandoc 1.18 on windows 7-64. I'm attaching the two testing files. The failing command line is

    pandoc --filter=pandoc-citeproc -o sample.pdf sample.md

and the working command line is 
  
    pandoc --filter=pandoc-citeproc --csl=cms16n.csl -o sample.pdf sample.md

sample.md
~~~
---
ϲsl: 'cms16n.csl'
bibliography: sample.bib
---

Añadamos español, para hacerlo más interesante; con una cita de -@Knuth1989 y otra de -@Turing1950.
~~~

and sample.bib

~~~
@book{Knuth1989,
   author = {Knuth, Donald E.},
   title = {The {TeXbook}},
   publisher = {Addison Wesley},
   address = {Reading, MA},
   date = {1989}
   }

@article{Turing1950,
   author = {Turing, Alan M.},
   title = {Computing Machinery and Intelligence},
   journal = {Mind},
   volume = {59},
   year = {1950},
   pages = {433-460}
   }
~~~

**Comment by cagix** [comment]
Please try it without the `.bib` ending, i.e.

```
---
ϲsl: 'cms16n.csl'
bibliography: sample
---
```

That used to work for me (pandoc 1.18).

**Comment by jlrn7** [comment]
If I drop the filename extension Pandoc dies with a file not found error.

**Comment by tarleb** [comment]
> ---
> ϲsl: 'cms16n.csl'
> bibliography: sample.bib
> ---

The `c` in `csl` in that snippet is not actually a c but a greek lunate
sigma.

**Comment by jlrn7** [comment]
how did you figure it out?

**Comment by tarleb** [comment]
The font I'm using renders the two slightly differently. Finding the glyph-name was a simple copy/paste into wolframalpha.
