### ISSUE TITLE
image height in % does not retain image aspect ratio for odt output

### ISSUE THREAD

**Issue by kwijk** [jgm/pandoc#3239]
### Reproducibility
When an image link is included in markdown input one can give the image width and image height. Providing only the image width should keep the image aspect ratio in the output dcument. It does when the unit is 'cm' or 'px'. It does not when unit is '%'.
 * add to a markdown document an inline reference to an image
    \[A Screenshot](screenshot.png){width=15%}
 * call pandoc myfile.md -o myfile.odt

==> The image in the odt file has its image scaled ok horizontaly, but it does not retain its ascpect ratio. Using {width=15cm} does work as expected.

### expected behaviour
When image width is given explicitly as in {width=x%} without giving the image height I expect the aspect ratio to be kept the same.

### version
pandoc 1.18

**Comment by jgm** [comment]
Here's the relevant code:
``` haskell
       let dims =
             case (getDim Width, getDim Height) of
               (Just w, Just h)              -> [("width", show w), ("height", show h)]
               (Just w@(Percent _), Nothing) -> [("width", show w), ("style:rel-height", "scale")]
               (Nothing, Just h@(Percent _)) -> [("style:rel-width", "scale"), ("height", show h)]
               (Just w@(Inch i), Nothing)    -> [("width", show w), ("height", show (i / ratio) ++ "in")]
               (Nothing, Just h@(Inch i))    -> [("width", show (i * ratio) ++ "in"), ("height", show h)]
               _                             -> [("width", show ptX ++ "pt"), ("height", show ptY ++ "pt")]
             where
               ratio = ptX / ptY
               getDim dir = case (dimension dir attr) of
                              Just (Percent i) -> Just $ Percent i
                              Just dim         -> Just $ Inch $ inInch opts dim
                              Nothing          -> Nothing
```
As you can see, when a percent is used, we use `style:rel-height="scale"`.  That sounds as if it should do what you want, but apparently not?

**Comment by nelas** [comment]
Hi, I just ran into this issue. Using `%` does not maintain image aspect ratio for ODT. Markdown input:

    ![Figure legend.](Fig.png){ width=100% }

ODT output:

    <draw:frame draw:name="img1" svg:width="100.0%" style:rel-height="scale">

Somehow this is not enough for ODT. It seems that it needs both `svg:width` and `svg:height` to draw the figure properly. Removing `rel-height` and adding an explicit `height %` renders the image correctly (no surprise there, though):

    <draw:frame draw:name="img1" svg:width="100.0%" svg:height="40.0%">

I couldn't figure out if this is a ODT bug or feature, but perhaps a workaround would be Pandoc calculating the ratio percentage on its own, if `%` is used.

**Comment by mb21** [comment]
Indeed, this seems to be a [known bug in LibreOffice, reported in 2012](https://bugs.documentfoundation.org/show_bug.cgi?id=45884&redirected_from=fdo). I'll take a look...
