### ISSUE TITLE
--version  "getAppUserDataDirectory: illegal operation (unsupported operation)"

### ISSUE THREAD

**Issue by athafoud** [jgm/pandoc#3241]
I am calling pandoc (via rmarkdown) though an SQL Server (R Services install) 2016 script. The render function of rmarkdown calls a pandoc wrapper (https://github.com/rstudio/rmarkdown/blob/cran-1.1/R/pandoc.R) to identify the version of pandoc. 

The `pandoc.exe --version` returns 1 (running command '"pandoc.exe" --version' had status 1). This happen due to the falling error 

> pandoc.exe: getAppUserDataDirectory: illegal operation (unsupported operation)

Since pandoc has an error when trying to identify the User Directory, it 'breaks' the '--version' function without returning anything.

My suggestion is, instead of breaking the '--version' function to just catch the error and return empty in "Default user data directory:..."

Some more info: For this specific case the getAppUserDataDirectory does not mean the the User does not have a directory, it is just mean that the Haskel functions (https://hackage.haskell.org/package/directory-1.0.0.3/docs/src/System-Directory.html) and subsequently the win32 libraries that Haskell uses cannot 'find' that directory. This is happening, because the user that run the R Script (thus calling the pandoc.exe) is not a 'real' user.  With the SQL Server 2016, introduced trusted launchpad, which decided which worker user (from a worker pool) will execute the R script.

**Comment by jgm** [comment]
Good call, we should trap errors in getUserDataDirectory.
