### ISSUE TITLE
pandoc -h is missing a format list in Version 1.18

### ISSUE THREAD

**Issue by apaeffgen** [jgm/pandoc#3244]
See the attached terminal output for reference.  It would be great to see a list of all supported input / output formats again.

MacBook:~ User$ pandoc -v
pandoc 1.18
Compiled with pandoc-types 1.17.0.4, texmath 0.8.6.6, highlighting-kate 0.6.3
Default user data directory: /Users/apaeffgen/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
MacBook:~ User$ pandoc -h
pandoc [OPTIONS] [FILES]
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT
  -o FILENAME           --output=FILENAME
                        --data-dir=DIRECTORY
  -R                    --parse-raw
  -S                    --smart
                        --old-dashes
                        --base-header-level=NUMBER
                        --indented-code-classes=STRING
  -F PROGRAM            --filter=PROGRAM
                        --normalize
  -p                    --preserve-tabs
                        --tab-stop=NUMBER
                        --track-changes=accept|reject|all
                        --file-scope
                        --extract-media=PATH
  -s                    --standalone
                        --template=FILENAME
  -M KEY[:VALUE]        --metadata=KEY[:VALUE]
  -V KEY[:VALUE]        --variable=KEY[:VALUE]
  -D FORMAT             --print-default-template=FORMAT
                        --print-default-data-file=FILE
                        --dpi=NUMBER
                        --no-wrap
                        --wrap=[auto|none|preserve]
                        --columns=NUMBER
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
                        --no-highlight
                        --highlight-style=STYLE
  -H FILENAME           --include-in-header=FILENAME
  -B FILENAME           --include-before-body=FILENAME
  -A FILENAME           --include-after-body=FILENAME
                        --self-contained
                        --html-q-tags
                        --ascii
                        --reference-links
                        --reference-location=block|section|document
                        --atx-headers
                        --chapters
                        --top-level-division=[section|chapter|part]
  -N                    --number-sections
                        --number-offset=NUMBERS
                        --no-tex-ligatures
                        --listings
  -i                    --incremental
                        --slide-level=NUMBER
                        --section-divs
                        --default-image-extension=extension
                        --email-obfuscation=none|javascript|references
                        --id-prefix=STRING
  -T STRING             --title-prefix=STRING
  -c URL                --css=URL
                        --reference-odt=FILENAME
                        --reference-docx=FILENAME
                        --epub-stylesheet=FILENAME
                        --epub-cover-image=FILENAME
                        --epub-metadata=FILENAME
                        --epub-embed-font=FILE
                        --epub-chapter-level=NUMBER
                        --latex-engine=PROGRAM
                        --latex-engine-opt=STRING
                        --bibliography=FILE
                        --csl=FILE
                        --citation-abbreviations=FILE
                        --natbib
                        --biblatex
  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]
                        --mathml[=URL]
                        --mimetex[=URL]
                        --webtex[=URL]
                        --jsmath[=URL]
                        --mathjax[=URL]
                        --katex[=URL]
                        --katex-stylesheet=URL
                        --gladtex
                        --trace
                        --dump-args
                        --ignore-args
                        --verbose
                        --bash-completion
                        --list-input-formats
                        --list-output-formats
                        --list-extensions
                        --list-highlight-languages
                        --list-highlight-styles
  -v                    --version
  -h                    --help

Here the example from a pandoc 1.17 version:
MacBook:~ User$ pandoc1.7 -h
pandoc1.7 [OPTIONS] [FILES]
Input formats:  commonmark, docbook, docx, epub, haddock, html, json*, latex,
                markdown, markdown_github, markdown_mmd, markdown_phpextra,
                markdown_strict, mediawiki, native, odt, opml, org, rst, t2t,
                textile, twiki
                [ *only Pandoc's JSON version of native AST]
Output formats: asciidoc, beamer, commonmark, context, docbook, docbook5, docx,
                dokuwiki, dzslides, epub, epub3, fb2, haddock, html, html5,
                icml, json*, latex, man, markdown, markdown_github,
                markdown_mmd, markdown_phpextra, markdown_strict, mediawiki,
                native, odt, opendocument, opml, org, pdf**, plain, revealjs,
                rst, rtf, s5, slideous, slidy, tei, texinfo, textile
                [**for pdf output, use latex or beamer and -o FILENAME.pdf]
Options:
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT
  -o FILENAME           --output=FILENAME
                        --data-dir=DIRECTORY
  -R                    --parse-raw
  -S                    --smart
                        --old-dashes
                        --base-header-level=NUMBER
                        --indented-code-classes=STRING
  -F PROGRAM            --filter=PROGRAM
                        --normalize
  -p                    --preserve-tabs
                        --tab-stop=NUMBER
                        --track-changes=accept|reject|all
                        --file-scope
                        --extract-media=PATH
  -s                    --standalone
                        --template=FILENAME
  -M KEY[:VALUE]        --metadata=KEY[:VALUE]
  -V KEY[:VALUE]        --variable=KEY[:VALUE]
  -D FORMAT             --print-default-template=FORMAT
                        --print-default-data-file=FILE
                        --dpi=NUMBER
                        --no-wrap
                        --wrap=[auto|none|preserve]
                        --columns=NUMBER
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
                        --no-highlight
                        --highlight-style=STYLE
  -H FILENAME           --include-in-header=FILENAME
  -B FILENAME           --include-before-body=FILENAME
  -A FILENAME           --include-after-body=FILENAME
                        --self-contained
                        --html-q-tags
                        --ascii
                        --reference-links
                        --atx-headers
                        --chapters
  -N                    --number-sections
                        --number-offset=NUMBERS
                        --no-tex-ligatures
                        --listings
  -i                    --incremental
                        --slide-level=NUMBER
                        --section-divs
                        --default-image-extension=extension
                        --email-obfuscation=none|javascript|references
                        --id-prefix=STRING
  -T STRING             --title-prefix=STRING
  -c URL                --css=URL
                        --reference-odt=FILENAME
                        --reference-docx=FILENAME
                        --epub-stylesheet=FILENAME
                        --epub-cover-image=FILENAME
                        --epub-metadata=FILENAME
                        --epub-embed-font=FILE
                        --epub-chapter-level=NUMBER
                        --latex-engine=PROGRAM
                        --latex-engine-opt=STRING
                        --bibliography=FILE
                        --csl=FILE
                        --citation-abbreviations=FILE
                        --natbib
                        --biblatex
  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]
                        --mathml[=URL]
                        --mimetex[=URL]
                        --webtex[=URL]
                        --jsmath[=URL]
                        --mathjax[=URL]
                        --katex[=URL]
                        --katex-stylesheet=URL
                        --gladtex
                        --trace
                        --dump-args
                        --ignore-args
                        --verbose
                        --bash-completion
  -v                    --version
  -h                    --help

**Comment by tarleb** [comment]
Getting the list of supported formats has become even easier. Simply use
the `--list-…` options, the output of which is even machine-readable
now.  See issues #3173 and #2685 for more information.

**Comment by tarleb** [comment]
As an additional note: in cases like this, where something changed from
one version to the next, it is highly advisable to read the release
changelog: On the project page, click on the "github release" shield at
the top of the readome. The changelog is very complete and well
maintained. You'll notice that one wouldn't have to search for long to
reach the entry for therissue at hand: it's in the first entry for
version 1.18.

**Comment by jekriske-lilly** [comment]
It's good practice to update the manual when making such changes... 
http://pandoc.org/MANUAL.html#syntax-highlighting
Thanks!
