### ISSUE TITLE
Org mode reader doesn't support column width

### ISSUE THREAD

**Issue by hoelterhof** [jgm/pandoc#3246]
Currently the org mode reader doesn't support column width. In the file src/Text/Pandoc/Readers/Org/Blocks.hs I found this note (line 695):

```
-- OrgTable is strongly related to the pandoc table ADT.  Using the same
-- (i.e. pandoc-global) ADT would mean that the reader would break if the
-- global structure was to be changed, which would be bad.  The final table
-- should be generated using a builder function.  Column widths aren't
-- implemented yet, so they are not tracked here.
```

Is it possible in include the column-width feature in org mode reader so you can parse org tables like this one:

```
| Col1       |  Col2 |            Col3 |
|------------+-------+-----------------|
| <l10>      |  <r5> |           <r15> |
| left 10    | right |  right 15 chars |
```

**Comment by tarleb** [comment]
There are two parts to this.  One is parsing, which would be rather quick to implement.  The other is the meaning of this column width parameter.  The Emacs Org-mode (v.8.3.6) HTML and LaTeX exporters seem to ignore the column width.  The documentation mentions column width only in the context of emacs buffers, there's no hint that this should work with exporters.

Pandoc tries to be behave similar to the Org-mode exporters, I don't think this should be changed.

**Comment by hoelterhof** [comment]
Column width is an official and documented feature of the Org-mode markup. See e.g. [here](http://orgmode.org/manual/Column-width-and-alignment.html#Column-width-and-alignment).
I am using the native ODT export feature of Org-mode quite often and this exporter cares about column width (see [here](http://orgmode.org/manual/Tables-in-ODT-export.html)). 

As far as I understood the data structure pandoc already support column width. The markdown reader e.g. supports column width in multiline tables, and pandoc OpenDocument writer creates tables according to the table width in the marup. So I guess it is just a matter of parsing and should be implemented rather quickly...

**Comment by tarleb** [comment]
That's very interesting, I had no idea the ODT exporter respected the column width parameters.  Tried it with org v9.0 and it works like a charm.  The LaTeX and HTML exporters still don't seem to support it though.

I think having one exporter that supports column widths could be enough to warrant the implementation of this feature.  I'm a bit skeptical though, the absence of this feature from other exporters may cause problems for people who use it only to improve their org buffers' readability.  The feature might get into the way of some people.  Are there other opinions on this?

**Comment by tarleb** [comment]
I added a branch here: <https://github.com/tarleb/pandoc/tree/org-column-widths>. Please try it if you can and let me know if it suits your use-case.

**Comment by hoelterhof** [comment]
Wow, that's fast! I tried your branch and can confirm that it works like expected.

Concerning the discussion about this feature I found that column width in Org-mode native latex export should be controlled by an attribute (see e.g. [here](https://lists.gnu.org/archive/html/emacs-orgmode/2009-04/msg00336.html)). In native HTML export it seems impossible to control it (see e.g. [unanswered question on stackoverflow](http://stackoverflow.com/questions/39342374/org-mode-s-table-export-to-html-how-to-set-column-width))? Anyway, the native export modules do not have a consistent way for that. In my opinion this is inappropriate because a benefit of writing texts in markup is the fact that you can easily convert it to different output formats. 

My suggestion is to use this way to control column width because it is more universal and not bound to an attribute of a certain output format (like ATTR_LaTeX or so)...

**Comment by tarleb** [comment]
I raised the issue on [reddit](https://www.reddit.com/r/orgmode/comments/5ecuaq/) to get some additional input.

**Comment by tarleb** [comment]
There wasn't any more input, which I guess means that nobody who read it had a strong opinion on the matter.  I like the idea of being able to control column width, so I pushed the commit.

Thanks for bringing it up, @hoelterhof.
