### ISSUE TITLE
(windows) Pandoc fails to find filters with "\" folder separators

### ISSUE THREAD

**Issue by sergiocorreia** [jgm/pandoc#3247]
Pandoc requires me to specify the full path of a filter using "/" as delimiters (unix style) instead of "\" as delimiters (Windows style):

For instance, given a `debug.py` filter in $datapath:

- Just using the filter name fails:

```
C:\Users\Sergio>echo hello | pandoc -F debug.py
pandoc: Error running filter C:\Users\Sergio\AppData\Roaming\pandoc\filters\debug.py
C:\Users\Sergio\AppData\Roaming\pandoc\filters\debug.py: createProcess: invalid argument (Exec format error)
```

- Using the full path with windows delimiters also fails:

```
C:\Users\Sergio>echo hello | pandoc -F  C:\Users\Sergio\AppData\Roaming\pandoc\filters\debug.py
pandoc: Error running filter C:\Users\Sergio\AppData\Roaming\pandoc\filters\debug.py
C:\Users\Sergio\AppData\Roaming\pandoc\filters\debug.py: createProcess: invalid argument (Exec format error)
```

- But using unix delimiters works:

```
C:\Users\Sergio>echo hello | pandoc -F  C:/Users/Sergio/AppData/Roaming/pandoc/filters/debug.py
(correct output omitted)
```

This is related to #1096 , where running filters located in the same folder required `-F ./myfilter.py`, and has been present for as long as I remember (but with filters in $datapath, I can't use the usual workaround).

I tried to find for the culprit line on the source code but couldn't find it. In case this helps, this is also a common source of bugs in python (concatenating paths a la `path + "/" file`), which is is why we use the `os.path.join(path, file)` pattern.

**Comment by sergiocorreia** [comment]
**Update:**

It seems [this](https://github.com/jgm/pandoc/blob/49b0b67b11b62032b2ade498c3efd5a762193d86/tests/Tests/Shared.hs#L11) import might be the culprit? (or [this one](https://github.com/jgm/pandoc/blob/fd4831dd03c8797af4bcb180dac775a08b7bf3d6/src/Text/Pandoc/Data.hsb#L6))

From [hackage](https://downloads.haskell.org/~ghc/6.6.1/docs/html/libraries/filepath/System-FilePath.html), I see that there are both Windows and Posix versions

**Comment by jgm** [comment]
Are you using the 1.18 release or code compiled from master
(because I just made a change that might be relevant)?

**Comment by sergiocorreia** [comment]
Forgot to include it; I'm using the 1.18 release:

```
C:\Users\Sergio>pandoc --version
pandoc 1.18
Compiled with pandoc-types 1.17.0.4, texmath 0.8.6.6, highlighting-kate 0.6.3
Default user data directory: C:\Users\Sergio\AppData\Roaming\pandoc
```

From what I see in the commit, the issue should still be present (but I don't have ghc installed on my laptop to test it)

**Comment by jgm** [comment]
The first commit you link to is just in a testing program. It shouldn't affect the pandoc executable.
The second one only affects system data files when pandoc is compiled using `embed_data_files` flag. It shouldn't affect finding filters.
In both cases the use of `/` delimiters is intentional.

**Comment by sergiocorreia** [comment]
Are there other locations where `/` delimiters might pop up?

As another data point, I also have the same problem when running filters on the current path: `echo hello | pandoc -F .\debug.py` fails but `echo hello | pandoc -F ./debug.py` works fine.

**Comment by sergiocorreia** [comment]
**Another update:**

The error `createProcess: invalid argument (Exec format error)` [occurs](https://ghc.haskell.org/trac/ghc/ticket/365?cversion=0&cnum_hist=4) if the process created is unknown by the windows loader. For instance, if I try to do `proc "myfilter.py" []` instead of `proc "python" ["myfilter.py"]`

So my best guess is that somewhere around [this line](https://github.com/jgm/pandoc/blob/ac6dfe0b4efb601f24e444ac8a4059c4103881ef/pandoc.hs#L138) the program decides not to use "("python", f:args')", perhaps because it follows the `isExecutable` branch?

On Windows, Python `.py` files [are executable](https://docs.python.org/3/faq/windows.html#how-do-i-make-python-scripts-executable) (so I don't have to type `python myscript.py` from the command line). However, this only works for the command line and not for the windows loader, so from Pandoc we still need to run it with `python ...`.

Now, maybe this weird bug happens because, when we send the correct filename, [executable](https://github.com/jgm/pandoc/blob/ac6dfe0b4efb601f24e444ac8a4059c4103881ef/pandoc.hs#L133) returns True (which leads to failure lines below).

**Fix**: I'm not sure, but perhaps the code below works? (I do not know haskell so its just pseudocode based on pandoc.hs:

```haskell
                                         _ | isExecutable and not isWindows -> (f, args')
                                         ".py"  -> ("python", f:args')
                                         ".hs"  -> ("runhaskell", f:args')
                                         ".pl"  -> ("perl", f:args')
                                         ".rb"  -> ("ruby", f:args')
                                         ".php" -> ("php", f:args')
                                         ".js"  -> ("node", f:args')
                                         _      -> (f, args')
```

**Comment by jgm** [comment]
OK, I've made a change in master that may do the trick.
If you look above the line you flagged, you'll see that
there was a hardcoded '/' in the test for directories.

Give it a try if you can, and report back!

**Comment by sergiocorreia** [comment]
I'm trying to build on source from windows but `stack install` crashes while building the old-time and network packages:

```
Progress: 76/86
--  While building package old-time-1.1.0.3 using:
      C:\Users\Sergio\AppData\Local\Temp\stack4672\old-time-1.1.0.3\.stack-work\dist\b7fec021\setup\setup --builddir=.stack-work\dist\b7fec021 configure "--with-ghc=C:\\Program Files\\Haskell Platform\\8.0.1\\bin\\ghc.EXE" "--with-ghc-pkg=C:\\Program Files\\Haskell Platform\\8.0.1\\bin\\ghc-pkg.EXE" --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\8b7a8b27\pkgdb --libdir=C:\sr\snapshots\8b7a8b27\lib --bindir=C:\sr\snapshots\8b7a8b27\bin --datadir=C:\sr\snapshots\8b7a8b27\share --libexecdir=C:\sr\snapshots\8b7a8b27\libexec --sysconfdir=C:\sr\snapshots\8b7a8b27\etc --docdir=C:\sr\snapshots\8b7a8b27\doc\old-time-1.1.0.3 --htmldir=C:\sr\snapshots\8b7a8b27\doc\old-time-1.1.0.3 --haddockdir=C:\sr\snapshots\8b7a8b27\doc\old-time-1.1.0.3 --dependency=base=base-4.9.0.0 --dependency=old-locale=old-locale-1.0.0.7-6glXNhHF891B41ZfuI8hU8
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Git\pandoc\.stack-work\logs\old-time-1.1.0.3.log

    [1 of 1] Compiling Main             ( C:\Users\Sergio\AppData\Local\Temp\stack4672\old-time-1.1.0.3\Setup.hs, C:\Users\Sergio\AppData\Local\Temp\stack4672\old-time-1.1.0.3\.stack-work\dist\b7fec021\setup\Main.o )
    Linking C:\Users\Sergio\AppData\Local\Temp\stack4672\old-time-1.1.0.3\.stack-work\dist\b7fec021\setup\setup.exe ...
    Configuring old-time-1.1.0.3...
    setup.EXE: The package has a './configure' script. If you are on Windows, This
    requires a Unix compatibility toolchain such as MinGW+MSYS or Cygwin. If you
    are not on Windows, ensure that an 'sh' command is discoverable in your path.
```

From the last 3 lines, it seems I need to install Cygwin or related; will try to do so and test

**Comment by jgm** [comment]
That's surprising.  We test continually with Windows builds
on appveyor.  The appveyor builds install stack and that's
it -- no separate cygwin or anything.

https://ci.appveyor.com/project/jgm/pandoc/build/1.0.515

and see appveyor.yml in the pandoc repository.

I should also mention that the Windows appveyor builds
also build a binary package, so you can just use that to
test.

https://ci.appveyor.com/project/jgm/pandoc/build/1.0.515/artifacts

It's possible that you have an older version of stack?
You could try 'stack upgrade'.

**Comment by sergiocorreia** [comment]
Not sure why my previous install attempt didn't work, but I now installed the appveyor binary and it worked perfectly and I can't reproduce the bug at all.

Thanks again!
