### ISSUE TITLE
LaTeX format not recognised via standard input

### ISSUE THREAD

**Issue by yashsriv** [jgm/pandoc#3248]
I am using `pandoc` for scripting and this is the command I am using:

```shell
$ cat foo.tex | pandoc -t html5
```
This gives me two blank lines as output!

`foo.tex` is:
```
\documentclass{article}

\begin{document}
  Foobar
\end{document}
```

I was expecting something similar to the output of:
```shell
$ pandoc -t html5 foo.tex
<p>Foobar</p>
```

**Comment by jgm** [comment]
You forgot `-f latex` (specifying the input format).
This can be inferred when you specify the filename,
but not when you use pandoc as a pipe.

**Comment by yashsriv** [comment]
Somehow the above works for markdown, so I assumed it might be available for other formats too. Currently I have all the contents of a file in a variable with no indication of filetype. I was hoping that the type inference would work on them too. Thanks.

**Comment by jgm** [comment]
Markdown is the default assumption when pandoc cannot
determine a format from the extension (as happens when
you use it with a pipe).

+++ Yash Srivastav [Nov 22 16 11:27 ]:
