### ISSUE TITLE
github markdown format adds extra paragraph and break line markup inside list items

### ISSUE THREAD

**Issue by joseluis** [jgm/pandoc#3249]
I noticed unnecessary extra markup when parsing github markup. Namely:
- \<br /\> inside \<li\> markup tags.
- \<p\>\</p\> inside \<li\> before the opening of a nested \<ul\>.

markdown source:
```markdown
- one
- two
    - sublist
```

command:
```shell
pandoc -f markdown_github nested-list.md
```

generated html:
```html
<ul>
<li>one<br /></li>
<li><p>two</p>
<ul>
<li>sublist</li>
</ul></li>
</ul>
```

In comparison, the HTML generated by the command `pandoc -f markdown nested-list.md` is much cleaner:
```html
<ul>
<li>one</li>
<li>two
<ul>
<li>sublist</li>
</ul></li>
</ul>
```

**Comment by jgm** [comment]
pandoc --version?  And platform?

With 1.18 on OSX I couldn't reproduce this.

```
% pandoc -f markdown_github
- one
- two
    - sublist
^D
<ul>
<li>one</li>
<li>two
<ul>
<li>sublist</li>
</ul></li>
</ul>
```

**Comment by joseluis** [comment]
Oh yes, sorry. This is pandoc 1.12.2.1 in Linux Mint 17.3

**Comment by jgm** [comment]
I think you just need to upgrade. That's an ancient version,
with hundreds of bugs that have since been fixed.

+++ José Luis Cruz [Nov 22 16 13:14 ]:

**Comment by jgm** [comment]
Note that we supply a 64-bit linux binary package on the
releases page.

**Comment by joseluis** [comment]
Thanks!
