### ISSUE TITLE
latex \providecommand is ignored by latex reader

### ISSUE THREAD

**Issue by woec** [jgm/pandoc#3254]
Converting latex source (created by lyx) to other formats  (all tried formats are affected: docx, odt, pdf ...) does not handle tables correct. I found the reason to be the command

    \providecommand{\tabularnewline}{\\}

in the latex source,

which is issued by lyx to replace `\tabularnewline` by `\\` in tables

How to get it fixed?

regards,
woec

**Comment by ickc** [comment]
Can you provide a Minimum Working Example? pandoc command used, version? See [pandoc/CONTRIBUTING.md at master · jgm/pandoc](https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md) for a checklist.

**Comment by woec** [comment]
Hello,

I attach a latex-input file and the docx-result, which contains a simple tex-table. As one can see in the docx-file, the table is not translated. If I replace the \tabularnewline entries in the table with double-backslash in the input flie, the conversion works as expeced.

Pandoc version is: 1.18
Command line is: pandoc -s -flatex -o test-pandoc.docx -t docx test-pandoc.tex

regards,
woec

**Comment by ickc** [comment]
Did you accidentally closed it? And I don't see, to see the attachment. GitHub's uploader uses markdown format to include a link to the files.

**Comment by woec** [comment]
Hi,
I try it again. Hopefully it is ok this time.
regards,
woec
[test-pandoc.zip](https://github.com/jgm/pandoc/files/611348/test-pandoc.zip)

**Comment by jgm** [comment]
This has already been fixed in master by a commit on Nov. 19.  The fix will be in the next release, or you can compile from source.

**Comment by ickc** [comment]
For reference: see #2669, #3087

If you need the fix now, you can follow the instruction to build from source in <https://github.com/jgm/pandoc/blob/master/INSTALL.md>
