### ISSUE TITLE
Custom default document class not applied by latex writer

### ISSUE THREAD

**Issue by jpcirrus** [jgm/pandoc#3259]
In a custom LaTeX template it is not possible to have a default document class which can also be overridden from the command line. Pandoc always applies `article` rather than in this example `scrartcl`.

```latex
\documentclass{$if(documentclass)$$documentclass$$else$scrartcl$endif$}
```

**Comment by jgm** [comment]
This is true.  The default template assumes that the
documentclass variable has a value, so the LaTeX writer sets
it if no value is specified (normally to "article", but to
"beamer" or "book" when appropriate).

We could change to a different system, where the default
template has "article" as the fallback (similar to your
template), and the writer lets the documentclass variable
be undefined.  That would make sense, and perhaps it's
better than the system we have now.  However, I'm very
reluctant to make this change, as it might break things
for a large number of current users who rely on custom
templates.

I'm willing to break things if the gain is high enough, but
I'm doubtful that it is in this case...

+++ John Purnell [Nov 26 16 12:17 ]:

**Comment by jpcirrus** [comment]
I understand. I have been working on a custom `default.latex` and was trying to make it as flexible as possible to reduce the number of templates to maintain and command options to remember by using many conditions e.g.

```latex
\makeatletter
\@ifundefined{KOMAClassName}
  {% non-KOMA stuff here
  }
  {% KOMA stuff here
  }
\makeatother
```

**Comment by jpcirrus** [comment]
Would it be possible then for a document class specified on the command line to overwrite one specified in the template?

**Comment by jgm** [comment]
+++ John Purnell [Nov 26 16 13:22 ]:
>   Would it be possible then for a document class specified on the command
>   line to overwrite one specified in the template?

Not sure I understand.  With the current default template
you can do

    pandoc -s -V documentclass=foo -t latex

and it will use 'foo'.

**Comment by jpcirrus** [comment]
Yes that works but what I was hoping for was to be able to set a default document class in a custom template

```latex
\documentclass{scrartcl}
```

and be able to override that with one specified either in the document metadata or on the command line, as in your example. In effect achieving what I had originally hoped to do with the template condition.

**Comment by jgm** [comment]
+++ John Purnell [Nov 27 16 10:34 ]:
>   Yes that works but what I was hoping for was to be able to set a
>   default document class in a custom template
>
>\documentclass{scrartcl}
>
>   and be able to override that with one specified either in the document
>   metadata or on the command line, as in your example. In effect
>   achieving what I had originally hoped to do with the template
>   condition.

You can do it if you use your own variable instead of
`documentclass`:

    \documentclass{$if(mydocumentclass)$$mydocumentclass$$else$scrartcl$endif$}

Then if you've set mydocumentclass on the command line, it
will use that, otherwise it will default to scrartcl.

**Comment by jpcirrus** [comment]
Thanks for that suggestion, I'll go with that.
