### ISSUE TITLE
Error when convert \text{$$} equation in docx

### ISSUE THREAD

**Issue by mjohn123** [jgm/pandoc#3264]
Hello all, I got an error when use math mode in text `\text{if $0 \le n_{i}(x) \le 1$}`. The pandoc cannot correctly convert it to docx file.  This is my equation and I am using the lastest version of pandoc

Thanks all

```
\begin{equation}\label{eq:1}
\theta_{0 \le n_i (x)  \le 1}=
\begin{cases}
0,  & \text{if $0 \le n_{i}(x) \le 1$}, i=1 \dots N, \\
+\infty, & \text{otherwise}.
\end{cases}
\end{equation}
```

**Comment by jgm** [comment]
This is a known issue:
https://github.com/jgm/texmath/issues/62
https://github.com/jgm/pandoc/issues/1178

It would be good to solve it.

**Comment by mjohn123** [comment]
Thank jgm. I followed your help with 

` [..., EText TextNormal "under ", ESub (EIdentifier "H") (EIdentifier "0")]`

Apply in my case, I have so complex the equation 

`$\text{if $0 \le n_{i}(x) \le 1$}$`

How could I modify? where can I paste in the equation to run correctly? I tried to insert your solution in my latex at my `\tex{}`, but the output is still wrong. Sorry, I am new user of pandoc

**Comment by mjohn123** [comment]
I solved it. I think I have an easy way. Just do it as follows

`$\text{if $0 \le n_{i}(x) \le 1$}$` ==>`$\text{if} $0 \le n_{i}(x) \le 1$`

**Comment by jgm** [comment]
I was talking about changes to the code, not a workaround
for you.

However, one possible workaround for you would be to move
the math out of the text box:

instead of

    $\text{if $0 \le n_{i}(x) \le 1$}$

use

    if $0 \e n{i}(x) \le 1$

**Comment by jgm** [comment]
+++ mjohn123 [Nov 29 16 02:39 ]:
>   I solved it. I think I have an easy way. Just do it as follows
>
>   $\text{if $0 \le n_{i}(x) \le 1$}$ ==>$\text{if} $0 \le n_{i}(x) \le 1$
>

Exactly.  Bottom line is that pandoc can't handle a `\text`
that itself contains math, but you can always rephrase so it
doesn't.
