### ISSUE TITLE
How to generate the reference item in word from bibitem?

### ISSUE THREAD

**Issue by mjohn123** [jgm/pandoc#3266]
Hello all, In my latex file, I have a reference which wrote by bibitem such as follows:

```
\bibitem{[1]} Z. Kato, and T.C. Pong, This is first paper, Image and Vision Computing 24 (10) (2006) 1103--1114.
\bibitem{[2]} R. Gonzalez, R. Woods, Digital Image Processing, 3rd ed. PrenticeHall, Englewood Cliffs, NJ, 2007. 
\bibitem{[3]} J. Weickert, This is second paper, IEEE Trans. 7 (3) (2001) 398--410.
```

How can I used pandoc to generate the reference file in docx. Thank all. This is my expected result in word. Also, How can I cite it in word. Currently, the position which I cite (using \cite{[1]}) has nothing. Thank all

[1] Z. Kato, and T.C. Pong, This is first paper, Image and Vision Computing 24 (10) (2006) 1103--1114.
[2] R. Gonzalez, R. Woods, Digital Image Processing, 3rd ed. PrenticeHall, Englewood Cliffs, NJ, 2007. 
[3] J. Weickert, This is second paper, IEEE Trans. 7 (3) (2001) 398--410.

**Comment by jgm** [comment]
Hi -- this tracker is for bug reports and specific enhancement requests.
Questions should go to the pandoc-discuss mailing list on google groups.
