### ISSUE TITLE
Pandoc breaking lines in markdown_github when converting to html

### ISSUE THREAD

**Issue by abalter** [jgm/pandoc#3268]
I'm starting out with a file like this:

```
This is a 
sentence broken
over many lines
without double spaces at 
the ends of line. It
renders as a single 
paragraph.
```

Then I run

    pandoc -f markdown_github -t html -o markdown-linebreaks.html markdown-linebreaks.md
    
The resulting file is:

```
<p>This is a<br />
sentence broken<br />
over many lines<br />
without double spaces at<br />
the ends of line. It<br />
renders as a single<br />
paragraph.</p>
```

However, github flavored markdown runs the lines together, as html does, as long as none ends with two spaces.

https://gist.github.com/abalter/668064834481c8560ddecbd4344f9f03

**Comment by jgm** [comment]
Actually GitHub has a couple different "modes" for Markdown.
In comments, release changelogs, etc., you get this
hard breaking behavior.  But in README.md, wikis, etc.,
you don't.

Our markdown_github mode defaults to the hard breaking
behavior, but you can disable this:

    pandoc -f markdown_github-hard_line_breaks

+++ Ariel Balter [Dec 01 16 09:57 ]:
