### ISSUE TITLE
Request: support mixed incremental in reveal.js slides

### ISSUE THREAD

**Issue by Jmuccigr** [jgm/pandoc#3269]
Reveal.js itself will allow you to have some list items incremental and others not. For example, `one` will appear right away with the slide, while `two` and `three` require user action:

```
<h2>Slide 3</h2>
<ul>
<li>one</li>
<li class="fragment">two</li>
<li class="fragment">three</li>
</ul>
```

pandoc though seems to force the entire list to be the same. So this markdown:

```
## Slide 3

> - one
- two
- three
```

yields this html:

```
<h2>Slide 3</h2>
<ul>
<li class="fragment">one</li>
<li class="fragment">two</li>
<li class="fragment">three</li>
</ul>
```

although you might have expected `two` and `three` **not** to have the `fragment` class.

Could this be changed so that pandoc will produce mixed lists?

**Comment by jgm** [comment]
Most Markdown parsers treat

    > - one
    - two
    - three

as equivalent to

    > - one
    > - two
    > - three

(see "laziness").  An exception is CommonMark parsers,
which parse this as a blockquote containing a list followed
by a list.  If pandoc ever switches to CommonMark rules,
then this would be a possibility, but I'd still not be
inclined to treat this the way you're requesting.
Even with this change, you'd have two lists anyway (one in
the blockquote), and you can already get this in pandoc
by leaving a blank space:

    > - one

    - two
    - three

Note that you can always use raw HTML if you're targeting
reveal.js.

**Comment by Jmuccigr** [comment]
I suppose this an inherent problem with using `>` for two purposes. I wonder if it makes sense to change how `increment` is signaled in pandoc. (Should I move this to Google groups for discussion?)

**Comment by jgm** [comment]
+++ John Muccigrosso [Dec 02 16 08:42 ]:
>   (Should I move this to Google groups for discussion?)

Yes.  Any changes in how this works would break existing
documnets and shouldn't be considered without lots of
discussion.
