### ISSUE TITLE
LaTeX→anything drops some mbox inline markup

### ISSUE THREAD

**Issue by alerque** [jgm/pandoc#3271]
Processing an input document in LaTeX format that uses `\mbox{}` to wrap content that should not get split comes across without the content at all. A minimal example would be something like this:

    $ pandoc -f latex -t markdown <<< 'Test \\textit{non} breakable string: \\mbox{ntxoy iroethir} thing'
    Test *non* breakable string: thing

Note the inline markup for italics came across, but the content of the mbox got dropped completely. If the output format doesn't have any concept of an mbox at the very least the plain text content should get passed through. On the other hand some output formats do have this, for example in html the output _should_ be something like this:

    $ pandoc -f latex -t html <<< 'Test \\textit{non} breakable string: \\mbox{ntxoy iroethir} thing'
    <p>Test <em>non</em> breakable string: <span style="whitespace: nowrap;">ntxoy iroethir</span> thing</p>

**Comment by jgm** [comment]
Try with `--parse-raw` and you'll get the raw TeX.  That may not be what you want, though?

**Comment by alerque** [comment]
Actually what I'd like is to have my cake and eat it too. Sometimes I would in fact want the TeX command to come through. Other times I just want the text flattened as much as possible. Ideally these two commands would output as follows:

$ pandoc -f latex -t markdown-raw_tex --parse-raw <<< 'Test \\textit{non} breakable string: \\mbox{ntxoyiroethir} thing'
Test *non* breakable string: ntxoyiroethir thing

$ pandoc -f latex -t markdown+raw_tex --parse-raw <<< 'Test \\textit{non} breakable string: \\mbox{ntxoyiroethir} thing'
Test *non* breakable string: \mbox{ntxoyiroethir} thing

Does that make sense? The `--parse-raw` flags seems to help the data get read **in**, but dropping it entirely is not what should be happening on the way **out**. With `raw_tex` turned on in the output format it should keep the unknown (?) LaTeX command, but with it turned off it should just flatten it.

**Comment by jgm** [comment]
+++ Caleb Maclennan [Dec 03 16 03:32 ]:
>   Does that make sense? The --parse-raw flags seems to help the data get
>   read in, but dropping it entirely is not what should be happening on
>   the way out. With raw_tex turned on in the output format it should keep
>   the unknown (?) LaTeX command, but with it turned off it should just
>   flatten it.

The problem is that this doesn't make sense with all LaTeX
commands.  E.g. `\setlength`.  There you really don't want
the flattening to occur.

**Comment by alerque** [comment]
Of  course. It needs some smarts about specific LaTeX commands, but given the purpose of some commands it doesn't make any sense to discard their contents.

**Comment by jgm** [comment]
One option would be to tell the LaTeX reader to parse the
contents of mbox into, say, a Span (even without
`--parse-raw`).  What would you think about that?

+++ Caleb Maclennan [Dec 03 16 06:30 ]:

**Comment by edwardabraham** [comment]
I just hit this issue as well. We use `\mbox` to control line breaking. For example, in the Southern Hemisphere we might talk about the `summer of \mbox{2015--16}`.

**Comment by jgm** [comment]
With current pandoc we get:
```
% pandoc -f latex -t html  
summer of \mbox{2015--16}
^D
<p>summer of 2015–16</p>
```
Is this unsatisfactory?  @edwardabraham if you get something else, you can upgrade.

**Comment by tarleb** [comment]
It seems this has been fixed. Otherwise please reopen.
