### ISSUE TITLE
Regression: Markdown to LaTeX conversion doesn't always recognize unnumbered headers

### ISSUE THREAD

**Issue by bwhelm** [jgm/pandoc#3272]
Pandoc versions >= 1.18 sometimes do not recognize unnumbered headers, whereas pandoc 1.17.2 does in the same conditions. This happens with a 4th-level header and with `--chapters` (or `--top-level-division=chapter`) specified. See pandoc runs below.

```
> pandoc --version
pandoc 1.17.2
Compiled with texmath 0.8.6.4, highlighting-kate 0.6.2.1.
<snip>

> pandoc -t latex --chapters
#### Testing {-}
\subsubsection*{Testing}\label{testing}
\addcontentsline{toc}{subsubsection}{Testing}
```

This is correct -- with `\subsubsection*`. Compare this with:

```
> pandoc --version
pandoc 1.19
Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3
<snip>

> pandoc -t latex --chapters
[pandoc warning] --chapters is deprecated. Use --top-level-division=chapter instead.
#### Testing {-}
\subsubsection{Testing}\label{testing}
\addcontentsline{toc}{subsubsection}{Testing}
```

Here, the `*` is wrongly omitted from `\subsubsection`.

This does not happen without specifying `--chapters` (or `--top-level-division=chapter`); nor does it happen with 1st--3rd level headings.

**Comment by jgm** [comment]
I think I see what is happening.
```
+  let star = if unnumbered && level < 4 then text "*" else empty
```
This is to avoid adding a star to `\paragraph`, which can't take one.
Normally a level 4 header is a `\paragraph`, but when you use `--chapters` it becomes a `\subsubsection`.  So this needs some revision.

**Comment by tarleb** [comment]
Both `\part*{}` and `\chapter*` exist and have the expected
functionallity; seems that using the primed `level'` variable instead of
`level` gives the desired behavior. Seems like I missed it when I was
touching that region.

John, do you prefer a PR or a direct push to master in cases like this?

**Comment by jgm** [comment]
@tarleb Go ahead and do a direct push!

+++ Albert Krewinkel [Dec 03 16 14:19 ]:
