### ISSUE TITLE
HTML tables with multi head and rowspans, how to convert HTML tables to docx format?

### ISSUE THREAD

**Issue by choies1** [jgm/pandoc#3274]
II would like to convert an HTML file to a docx file. However, there are some problems in a table. Converting HTML table with rowspan is not working.

Following is the HTML table code.
```HTML
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>sum</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th>Price</th>
    </tr>
    <tr>
      <th>Product</th>
      <th>Rep</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">CPU</th>
      <th>Cedric Moss</th>
      <td>95000</td>
    </tr>
    <tr>
      <th>Craig Booker</th>
      <td>65000</td>
    </tr>
    <tr>
      <th>Daniel Hilton</th>
      <td>105000</td>
    </tr>
    <tr>
      <th>John Smith</th>
      <td>35000</td>
    </tr>
    <tr>
      <th>Wendy Yule</th>
      <td>165000</td>
    </tr>
  </tbody>
</table>
```

I uses following command for conversion (I use pandoc ver. 1.18)
```
pandoc -f html -t docx -S --mathjax conversion_test.html -o conversion_test.doc
```

The docx result is as follows:

```
sum
Price
Product
Rep
CPU
Cedric Moss
95000
Craig Booker
65000
Daniel Hilton
105000
John Smith
35000
Wendy Yule
165000
```
When I see the HTML table in my web browser, I can see as follows:

![html_output](https://cloud.githubusercontent.com/assets/10408785/20864221/ac1fe680-ba2a-11e6-8853-78cad1e9f1df.png)

Please let me know how I can convert HTML table to word(docx) format.

**Comment by jgm** [comment]
I'm sorry, rowspan and colspan aren't currently supported.  Pandoc has a very simple table model (based on what is possible in Markdown table formats).

It's on the todo list, though.

**Comment by jgm** [comment]
PS. Multiple rows in header aren't supported either on the current model.

**Comment by choies1** [comment]
Thank you for your response. 
I hope I can make it in the next pandoc version.

**Comment by choies1** [comment]
Now I use pandoc ver. 2.9.2.1. Is there any solution to my question?
