### ISSUE TITLE
Add a style for tables in docx writer

### ISSUE THREAD

**Issue by choies1** [jgm/pandoc#3275]
When I convert HTML table to docx using pandoc (ver 1.18), I would like to change the table style for MS-word(docx).

I used the following Pandoc command for conversion (HTML table to docs)
```
pandoc -f html -t docx -S --mathjax conversion_test.html -o conversion_test.doc
```

HTML table code
```html
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Account</th>
      <th>Name</th>
      <th>Rep</th>
      <th>Manager</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>714466</td>
      <td>Trantow-Barrows</td>
      <td>Craig Booker</td>
      <td>Debra Henley</td>
      <td>CPU</td>
      <td>1</td>
      <td>30000</td>
      <td>presented</td>
    </tr>
    <tr>
      <th>1</th>
      <td>714466</td>
      <td>Trantow-Barrows</td>
      <td>Craig Booker</td>
      <td>Debra Henley</td>
      <td>Software</td>
      <td>1</td>
      <td>10000</td>
      <td>presented</td>
    </tr>
    <tr>
      <th>2</th>
      <td>714466</td>
      <td>Trantow-Barrows</td>
      <td>Craig Booker</td>
      <td>Debra Henley</td>
      <td>Maintenance</td>
      <td>2</td>
      <td>5000</td>
      <td>pending</td>
    </tr>
  </tbody>
</table>
```
Web browser result:

![html_output2](https://cloud.githubusercontent.com/assets/10408785/20864238/d6fab7c6-ba2b-11e6-8135-3a6fd80bd464.png)

MS Word result (after conversion):

![docx_output](https://cloud.githubusercontent.com/assets/10408785/20864245/0155c04c-ba2c-11e6-936c-79c02ce39318.png)

Howe can I change MS-word(docx) table styles as follows when I convert HTML table to docx using pandoc ?

![docx_output2](https://cloud.githubusercontent.com/assets/10408785/20864249/2b001ece-ba2c-11e6-9c2e-5ad6921e4235.png)

**Comment by jgm** [comment]
Here are the official instructions.  Create a reference.docx:

    pandoc --print-default-data-file reference.docx > myref.docx

Open this with Word.  Change the "Normal Table" (or "Table
Normal") style to match what you want.  Save.  Then invoke pandoc with

    pandoc --reference.docx myref.docx yourinput.html -o youroutput.docx

PROBLEM!  This doesn't work, because you can't modify
"Normal Table" (at least I couldn't).

So I think we need some changes in pandoc to make this
possible.  This site
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_other/i-nead-to-edit-the-format-normal-table-how-do-i-do/ab27db4e-a7c3-432f-8d3a-6c5f274f2d6a
recommends creating a custom table style, and we could do
that, and use it for pandoc tables.

@jkr any thoughts?

**Comment by mdolginin** [comment]
You can automatically change default headers, text, lists styles only. 
You can't change the default table style. 
The only way is to create custom table style in your reference file and manually apply it to each table in document after conversion.

**Comment by jkr** [comment]
@jgm -- from what's posted it looks like the best way. I'm not too familiar, but I'll take a look -- probably tomorrow.

**Comment by asknet** [comment]
+1
Having a custom table style would be very useful. Thanks!

**Comment by davebraze** [comment]
+1
I'd like this a lot

**Comment by asknet** [comment]
Hi,
I took nightly build(hash-8300b3fb). First generated pandoc --print-default-data-file reference.docx > myref.docx. Opened myref.docx, but couldn't find table style of name "Table" hence i'm unable to modify the table style. Please assist.

Thanks

**Comment by mmacphail** [comment]
Hi,

I'm experiencing the same problem as asknet. Help would be appreciated !

Thanks

**Comment by mogita** [comment]
Same issue here. I have the latest version of pandoc installed (1.19.2.1).

I tried the method refenreced in the official docs (the `pandoc --print-default-data-file reference.docx > custom-reference.docx` way), edited it and made it the new reference file, but didn't help with the result. Tables were still borderless. 

Then I tried editing the output docx file, like what the author of [this post](https://jabranham.com/blog/2016/11/using-pandoc-export-to-word/) said in the `Styling docx output` section. I applied borders to "All" sides of the table, looks good, then used the edited file as the reference, still, no borders in the result.

I think maybe the official docs could be more clearified about this certain issue, as it takes too much for a user who isn't familiar with the specs of the docx format to make the "right" change, still without significant improvement to this tiny yet critical spot (since all other parts of the convertion were just perfect). Or there could be some args that defines some custom table style I'd like to use in the reference file, as the Normal Table isn't allowed to be modified.

Thanks!

**Comment by jgm** [comment]
@mogita the fix is not in 1.19.2.1, it's only in the dev version.

**Comment by Jasonlhy** [comment]
this feature can be quite useful

**Comment by ryu-jin** [comment]
@jgm do you know when this fix will be integrated in the release by any chance? Cheers.

**Comment by russellsch** [comment]
I would be very interested in this feature as well

**Comment by mb21** [comment]
This should be released as of now, in pandoc 2.0

**Comment by yang-small-fan** [comment]
I also have the same problem.There is no border in the table in the docx file I generated.Please help me.

**Comment by agusmba** [comment]
@yang-small-fan did you edit the table style in your reference docx to fit your needs?

**Comment by yang-small-fan** [comment]
@agusmba I edit the form style in the reference template, but it doesn't seem to work.

**Comment by yang-small-fan** [comment]
@agusmba I edit the form style in the reference template, but it doesn't seem to work.It still has no border.

**Comment by iansco** [comment]
Hey @yang-small-fan - it's my understanding that Pandoc's docx writer creates tables with a Style named "Table", so you need to make sure that you apply styling changes in your "reference-doc" to this particular Table Style. 

According to the [comment](#issuecomment-341034692) above, I believe you also need to be running Pandoc 2.0 or later, as well...

**Comment by yang-small-fan** [comment]
@iandol According to the official website's hint, the custom-reference.docx I generated seems to have some problems, but I can't modify it. My pandoc version is 
[custom-reference.docx](https://github.com/jgm/pandoc/files/1765796/custom-reference.docx)
2.1.1, and office version is 2016..

**Comment by yang-small-fan** [comment]
@iandol According to the official website prompt, the custom-reference.docx form I generated seems to have some problems, but I can't modify it. My pandoc version is 2.1.1, and office version is 2016..
[custom-reference.docx](https://github.com/jgm/pandoc/files/1765798/custom-reference.docx)

**Comment by iansco** [comment]
@yang-small-fan - I just opened the reference doc you attached to your comment, edited the "Table" style (setting "All Borders"), saved the reference doc, then tested the amended reference doc by passing a simple Markdown file through Pandoc. It worked fine for me, so I'm not sure where things aren't quite working out for you. 

Here's modified copy of your reference doc, a source markdown file (for testing purposes), and the docx output file in case they help you:

- [yang-small-fan-custom-reference.docx](https://github.com/jgm/pandoc/files/1766688/yang-small-fan-custom-reference.docx)
- [table.txt](https://github.com/jgm/pandoc/files/1766691/table.txt)
- [table.docx](https://github.com/jgm/pandoc/files/1766692/table.docx)

`pandoc table.txt -f markdown -t docx --reference-doc yang-small-fan-custom-reference.docx -o table.docx`

I'm on Mac OS, so the process I went through to change the Table Style in MS Word was as follows:

1. Open the reference doc
1. Select (or click anywhere inside) the Table
1. Click the "*Table Design*" tab
1. Click the little down-arrow icon on the Quick Styles list _(which annoyingly only appears when you hover your mouse over the styles)_
1. Click "*Modify Table Style*" on the popup menu
1. Make style changes
1. Save the reference doc

Here are some screenshots in case they help:

![screenshot_1140](https://user-images.githubusercontent.com/2323266/36782861-e5aae860-1cac-11e8-9353-fbaa03effa0e.png)

![screenshot_1139](https://user-images.githubusercontent.com/2323266/36782866-ead08980-1cac-11e8-8cb5-fd67a0fb4a1b.png)

**Comment by yang-small-fan** [comment]
@iansco  I used your docx template to generate the correct form, but I also like you to add a border form to my template. At the same time, I don't know why my template didn't work after conversion. I guess it's the MS Word  version or the reason of the operation system. In a word, the problem has been solved. I'm very grateful to you. (๑′ᴗ‵๑)Ｉ Lᵒᵛᵉᵧₒᵤ❤

**Comment by agusmba** [comment]
@yang-small-fan bear in mind that you need to edit the Table Style called "Table" as @iansco explained beautifully. It won't work if you only edit a table with that style in your reference docx.
It's all about styles.

**Comment by iansco** [comment]
Thanks @yang-small-fan :-) When using Pandoc to create docx output I've found the [Options affecting specific writers](https://pandoc.org/MANUAL.html#options-affecting-specific-writers) section in the [Pandoc manual](https://pandoc.org/MANUAL.html) to be helpful - specifically, the section titled **Docx** under `--reference-doc`:

![screenshot_1146](https://user-images.githubusercontent.com/2323266/36837483-1b452a18-1d6f-11e8-82fa-9b0bfa51eecf.png)

This section provides a list of all the Styles which Pandoc uses. You'll see that Pandoc only currently uses a single Table Style named `Table`:

![screenshot_1148](https://user-images.githubusercontent.com/2323266/36838335-7cd6953a-1d71-11e8-8b9e-5e0b773df928.png)

So - as per the comment immediately above (thanks @agusmba!) - if you want to change the styling of _any_ Tables in your docx output, you'll need to make sure you edit the Table Style named `Table` in your `reference-doc`:

![screenshot_1139](https://user-images.githubusercontent.com/2323266/36838914-0d6c44fe-1d73-11e8-9ae1-b58e4c29cd6d.png)

There are _other ways_ to affect the style of docx output (see [Custom Styles in Docx Output](https://pandoc.org/MANUAL.html#custom-styles-in-docx-output) and [filters](http://pandoc.org/filters.html)), but that's a discussion for another day :-)

Good luck!

**P.S.** if you find you're still having problems applying styling changes to your `reference-doc`, please post a comment which explains, in as much detail as you can, exactly _how_ you're making the changes (screenshots can often help, of course), and I'm sure someone will be able to help...

**Comment by yang-small-fan** [comment]
Hey @iandol I now need to convert the HTML file into a word file. Is there a way to keep the style in HTML?

**Comment by agusmba** [comment]
@yang-small-fan AFAIK styles from html do not go through pandoc to docx directly, but simple copy-paste might get you halfway there (from browser into word).

Once you have your desired styles in a word document, you can use that one as `reference-doc` for any additional pandoc conversions.

**Comment by dmenne** [comment]
@iansco Your methods almost work for my, thanks a lot! The "almost": 
Sorry for the German version, "Verbundene Zeilen" is a stupid translation of  "Banded" in English.

This is what I requested in the template, no decorations for last row, and first/last column:

![screen_000047](https://user-images.githubusercontent.com/506275/50164088-1635cd80-02e2-11e9-913e-dfb84b3d2986.png)

This is created by knitr/Pandoc. Too bad, "Last Row" and Last/First Column are selected.

![screen_000048](https://user-images.githubusercontent.com/506275/50164215-539a5b00-02e2-11e9-88b1-c9af72f22d1c.png)

Everything is fine when I manually correct the Options setting for each table. This could be done by a Macro, but does anyone know a method to set these options in the Template?

**Comment by AStrunk** [comment]
I have the same problem as @dmenne. Even though "Total Row" and "Last Column" are unchecked in my reference document, the columns still appear in my generated docx document.

**Comment by yasz** [comment]
PLEASE update this issue

**Comment by conor909** [comment]
@iansco thanks for the clear info.  When I try to modify the styles for a name called "Table", it says 
"This style name already exists or is reserved for a built in style."

**Comment by gatestone** [comment]
I edit in Markdown, and plan to convert to Word. The original instructions 
above work, except it took some googling to understand how to find and edit "Table" style in Office 365/Word, see below. I also got a warning about old format of myref.docx after editing and saving but ignored the warning it and everything works.   

https://support.office.com/en-us/article/format-a-table-e6e77bc6-1f4e-467e-b818-2e2acc488006#bm1

**Comment by joezhouchenye** [comment]
I figured out how to change the table format in reference.docx at last.

- First, I am using Chinese version of Microsoft Word and it is impossible to change the Table style named "Table" if you create a new docx document by yourself. There is no style named "Table" and Word will ignore the change made to the style name. For example, you modified the name to Table, but Word will automatically change it to something like "网格型, Table" (“网格型” is a default style in Word).
- You need to make you own reference.docx on the basis of the reference generated by pandoc using command `pandoc -o custom-reference.docx --print-default-data-file reference.docx`
- The reference.docx generated by pandoc will have the style named "Table" in the table style list. Choose it and customize your own style. Everything works fine now.

**Comment by ZhouJunjun** [comment]
add filter and custom your own Table style, see lua filter: https://github.com/ZhouJunjun/TyporaLuaFilter

**Comment by zkaip** [comment]
Can I Change default "Table" style name to my custom style name? Because I have some other Table here, I want some table  owned its custom name.

**Comment by joezhouchenye** [comment]
Changing the default Table style isn't enough previously.

Recently, I created a Word Macro to cope with this issue.

```vba
Sub TableStyleFix()
  Dim atable As Table
  For Each atable In ActiveDocument.Tables
    If atable.Columns.Count > 2 Then
      atable.Style = ("Custom Table")
    End If
  Next
End Sub
Sub TableAutoFitWindow()
  Dim atable As Table
  For Each atable In ActiveDocument.Tables
    If atable.Columns.Count > 2 Then
      atable.AutoFitBehavior (wdAutoFitWindow)
    End If
  Next
End Sub
Sub TableDistributeColumns()
  Dim atable As Table
  For Each atable In ActiveDocument.Tables
    If atable.Columns.Count > 2 Then
      atable.Columns.DistributeWidth
    End If
  Next
End Sub
Sub TableAutoAdjust()
    Application.Run MacroName:="TableStyleFix"
    Application.Run MacroName:="TableAutoFitWindow"
    Application.Run MacroName:="TableDistributeColumns"
End Sub
```

You can create a custom table style named "Custom Table" or anything you like.

Just Run the TableAutoAdjust Macro. Using auto-fit-window and distribute-columns will be a good choice, although not suitable for small tables.

The reason I created separate macros is that an all-in-one macro only works in debug mode and you have to run it step by step. Not sure why, but using `Application.Run` works.

**Comment by sercutos** [comment]
> @yang-small-fan - I just opened the reference doc you attached to your comment, edited the "Table" style (setting "All Borders"), saved the reference doc, then tested the amended reference doc by passing a simple Markdown file through Pandoc. It worked fine for me, so I'm not sure where things aren't quite working out for you.
> 
> Here's modified copy of your reference doc, a source markdown file (for testing purposes), and the docx output file in case they help you:
> 
> * [yang-small-fan-custom-reference.docx](https://github.com/jgm/pandoc/files/1766688/yang-small-fan-custom-reference.docx)
> * [table.txt](https://github.com/jgm/pandoc/files/1766691/table.txt)
> * [table.docx](https://github.com/jgm/pandoc/files/1766692/table.docx)
> 
> `pandoc table.txt -f markdown -t docx --reference-doc yang-small-fan-custom-reference.docx -o table.docx`
> 
> I'm on Mac OS, so the process I went through to change the Table Style in MS Word was as follows:
> 
> 1. Open the reference doc
> 2. Select (or click anywhere inside) the Table
> 3. Click the "_Table Design_" tab
> 4. Click the little down-arrow icon on the Quick Styles list _(which annoyingly only appears when you hover your mouse over the styles)_
> 5. Click "_Modify Table Style_" on the popup menu
> 6. Make style changes
> 7. Save the reference doc
> 
> Here are some screenshots in case they help:
> 
> ![screenshot_1140](https://user-images.githubusercontent.com/2323266/36782861-e5aae860-1cac-11e8-9353-fbaa03effa0e.png)
> 
> ![screenshot_1139](https://user-images.githubusercontent.com/2323266/36782866-ead08980-1cac-11e8-8cb5-fd67a0fb4a1b.png)

thanks you so much!

**Comment by Smeedy** [comment]
Okay, I have been banging my head against the wall to have a reference.docx file which had the table style I could modify, I could save, and which I could use as a `--reference-doc`. I missed a piece of the puzzle - could be the hour of night...

So instructions are somewhat clear and it dawned to me when I was looking at https://github.com/jgm/pandoc/issues/3275#issuecomment-369198726 and was downloading those files and cloud finally use that table.docx as a reference-doc.

But you don't need to download those files, you can also start from scratch and have the default custom-reference which was provided by your Pandoc version as a starting point.

1. So create a new file with you current pandoc version `pandoc -o custom-reference-step-1.docx --print-default-data-file reference.docx`
2. Use any simple table.txt or a table.md you create and generate a doc using the table as an input. The resulting file will be your final reference doc in which you can tweak the style using the instructions here and you will be able to save it. Something like this: `pandoc table.md -f markdown -t docx --reference-doc custom-reference-step-1.docx -o custom-reference-no-examples-but-with-a-single-table-and-the-std-pandoc-styles.docx`
3. You can now open that file, modify table style like the screenshots without Word erroring out on you. If you miss this step 2, you will get the "This style name already exists or is reserved for a built-in style." when you try to edit the file in step 1.
4. From now on you can use that new custom-reference file as your reference-doc input in your normal pandoc jobs, but with the ability to change the style of the tables.

**Comment by rnwst** [comment]
@Smeedy -- I don't think these steps are necessary to modify the `Table` style. You can simply start with the default reference doc, and follow [these instructions](https://rnwest.engineer/auto-generate-docx-with-pandoc/#how-to-edit-styles) to edit the `Table` style.
