### ISSUE TITLE
RST Writer: auto-wrapping accidentally creates "Definition list" in tables

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#3276]
Sorry I don't have a MWE since the input and output has to be in a specific way such that:

say, in a table cell in markdown: `has_header: True | False`, the rst output wrapped into

```rst
has\_header
: True \| F
alse
```

The `:` on the beginning of the new line becomes a definition list, and rst2html complains:

> Definition list ends without a blank line; unexpected unindent.

# Example

The only example I can give is in native pandoc AST since the table is generated by my filter:

command used:

```bash
# pandoc 1.19
pandoc -f native -o test.rst test.native
# (Docutils 0.12 [release], Python 3.5.2, on darwin)
rst2html.py test.rst > test.html
```

[The AST, generated RST and HTML are here](https://github.com/jgm/pandoc/files/629452/Compressed.file.zip).

**Comment by jgm** [comment]
This is similar to #3270.  We can escape every colon to ensure this never happens, but then the output is ugly.  Ideal thing would be a much more sophisticated wrapping method.

**Comment by ickc** [comment]
Ok, I think this one should be closed. Should the title of #3270 be changed to reflect the more general problem?

**Comment by ickc** [comment]
Since #3270 is fixed, probably I should keave this open instead.

**Comment by jgm** [comment]
I don't really understand your case; can you give a minimal
case I can reproduce?

**Comment by ickc** [comment]
I'll try to hunt down a smaller example. Since the nature of the problem involves wrap and table make it difficult to reproduce.

**Comment by jgm** [comment]
Try using a small value of --columns

+++ ickc [Dec 07 16 03:21 ]:

**Comment by nsoranzo** [comment]
I have a similar issue with Pandoc 1.19 when converting from markdown_github to rST:
```
pandoc schema.md -f markdown_github-hard_line_breaks -s -o schema.rst
```

where `schema.md` contains this table:

```
Attribute | Details | Required
--- | --- | ---
``id`` | Must be unique across all tools; should be lowercase and contain only letters, numbers, and underscores. It allows for tool versioning and metrics of the number of times a tool is used, among other things. Find the Intergalactic Utilities Commision suggested best practices for this element [here](https://planemo.readthedocs.io/en/latest/standards/docs/best_practices/tool_xml.html#tool-ids). | True
``name`` | This string is what is displayed as a hyperlink in the tool menu. Find the Intergalactic Utilities Commision suggested best practices for this element [here](https://planemo.readthedocs.io/en/latest/standards/docs/best_practices/tool_xml.html#tool-names). | True
```

generates this broken rST:

```
+------+------+------+
| Attr | Deta | Requ |
| ibut | ils  | ired |
| e    |      |      |
+======+======+======+
| ``id | Must | True |
| ``   | be   |      |
|      | uniq |      |
|      | ue   |      |
|      | acro |      |
|      | ss   |      |
|      | all  |      |
|      | tool |      |
|      | s;   |      |
|      | shou |      |
|      | ld   |      |
|      | be   |      |
|      | lowe |      |
|      | rcas |      |
|      | e    |      |
|      | and  |      |
|      | cont |      |
|      | ain  |      |
|      | only |      |
|      | lett |      |
|      | ers, |      |
|      | numb |      |
|      | ers, |      |
|      | and  |      |
|      | unde |      |
|      | rsco |      |
|      | res. |      |
|      | It   |      |
|      | allo |      |
|      | ws   |      |
|      | for  |      |
|      | tool |      |
|      | vers |      |
|      | ioni |      |
|      | ng   |      |
|      | and  |      |
|      | metr |      |
|      | ics  |      |
|      | of   |      |
|      | the  |      |
|      | numb |      |
|      | er   |      |
|      | of   |      |
...
```

The workaround for me is using ```--columns=500```.

I think that ``--wrap=none`` should stop pandoc from enforcing a column width, but unfortunately it has no effect on tables.

**Comment by jgm** [comment]
+++ Nicola Soranzo [Dec 08 16 12:26 ]:
>   The workaround for me is using --columns=500.

A nicer solution is to use longer bars under the headers
(see the documentation for pipe tables).

I know you may not have this option, though, if you're
just taking content from GitHub.

>   I think that --wrap=none should stop pandoc from enforcing a column
>   width, but unfortunately it has no effect on tables.

It's still nice to be able to adjust relative column widths
in tables, even if you use --wrap=none.

Remember that --wrap=none also affects formats like HTML and
LaTeX.

**Comment by ickc** [comment]
> I think that --wrap=none should stop pandoc from enforcing a column width, but unfortunately it has no effect on tables.

Also see #3171. I also confused with the wrap and column option too. While the manual said

> It also affects calculation of column widths for plain text tables (see Tables below).
>
> ...
>
> If a pipe table contains a row whose printable content is wider than the column width (see --columns), then the cell contents will wrap, with the relative cell widths determined by the widths of the separator lines.

May be it should mention something related to the fact that `--wrap=none` does not have an effect on it.

**Comment by nsoranzo** [comment]
> > I think that --wrap=none should stop pandoc from enforcing a column width, but unfortunately it has no effect on tables.

> It's still nice to be able to adjust relative column widths in tables, even if you use --wrap=none.
>
>Remember that --wrap=none also affects formats like HTML and LaTeX.

Agreed, but maybe a different option to specify this would be better, e.g. `--table-width` .

**Comment by nsoranzo** [comment]
> A nicer solution is to use longer bars under the headers (see the documentation for pipe tables).

This works only to a certain extent because if multiple columns need to be of a certain width to not break rST syntax, adjusting the relative width is not enough and increasing `--columns` is the only option.

**Comment by jgm** [comment]
I think this is a dup of #3340
