### ISSUE TITLE
Pandoc wraps line in markdown at the wrong point

### ISSUE THREAD

**Issue by zetok** [jgm/pandoc#3277]
pandoc 1.15.0.6

exact input: https://github.com/zetok/tox-spec/blob/66035887b8801bdb6d5c965928816b53e854b8bc/spec.md

command: 
```
pandoc --no-tex-ligatures --atx-headers --columns=79  -f markdown_github-hard_line_breaks-native_spans-raw_html+tex_math_dollars-tex_math_single_backslash -t markdown_github-hard_line_breaks-native_spans-raw_html+tex_math_dollars-tex_math_single_backslash spec.md -o spec.md
```

difference in output: https://travis-ci.org/zetok/tox-spec/builds/181015711#L211

There should be no difference in the output.

**Comment by jgm** [comment]
Why do you say there should be no difference in the output?
You're specifying a column width of 79, and pandoc is rewrapping text for that width.
If you don't want pandoc to rewrap lines, use `--wrap=none`.

**Comment by zetok** [comment]
>Why do you say there should be no difference in the output?
>You're specifying a column width of 79, and pandoc is rewrapping text for that width.

Line in question before pandoc messes up:
```
echo -n '    connections between the peers in the network. Entry point is still' | wc -c
70
```

>If you don't want pandoc to rewrap lines, use `--wrap=none`.

I want wrapping to be done properly.
There's no need to do wrapping for this line, since it doesn't come even close to 79 characters.

**Comment by jgm** [comment]
OK, thanks for the clarification.  Looking quickly at the code, I don't see why it didn't add "still" to the line.  I'll have to investigate this further.

**Comment by jgm** [comment]
Traced this to a bug in `isOrderedListMarker` in the Markdown writer:
```
*Text.Pandoc.Writers.Markdown> isOrderedListMarker "A."
True
*Text.Pandoc.Writers.Markdown> isOrderedListMarker "Failure."
True
```
Note, this is used to avoid bad breaks in lists before something that might be interpreted as an ordered list marker.  A hack we might avoid if we had a smarter prettyprinter.
