### ISSUE TITLE
Is there a way to stop converting $$ to \[ and \] in MD -> TeX?

### ISSUE THREAD

**Issue by sn0wyfall** [jgm/pandoc#3278]
Sorry if this is not the correct place to ask!

I'm just wondering if it is possible to prevent the `$$...$$` from changing into `\[...\]` when a `.md` file is converted into `.tex`.

**Comment by jgm** [comment]
No, that's hardcoded.

+++ sn0wyfall [Dec 04 16 14:37 ]:

**Comment by sn0wyfall** [comment]
If anyone wants to do this, use a simply replace `\[` with `$$`.

**Comment by ickc** [comment]
Note that using TeX's `$` and `$$` is discouraged in LaTeX. Unless you have some special reason you shouldn't be doing that. In fact, it took me some time to convince the MultiMarkdown maintainer to not emit `$...`.
