### ISSUE TITLE
Raw TeX in pandoc markdown

### ISSUE THREAD

**Issue by sn0wyfall** [jgm/pandoc#3279]
So I read from the [pandoc markdown guide](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#raw_tex) that one can insert raw TeX by simply inserting an environment into the document. But I tried inserting this into the markdown document:

    \begin{align*}
    x &= 2-3+20 \\
    &= 19 \\
    \end{align*}

and it converted it into this:

    \[\begin{align*}
    x &= 2-3+20 \\
    &= 19 \\
    \end{align*}\]

which then doesn't seem to compile correctly. Isn't it the opposite of raw TeX if the `\[...\]` environment is added to it?

**Comment by jgm** [comment]
What version of pandoc?  What command used?

With current pandoc (1.19):
```
% pandoc -t latex
   \begin{align*} x &= 2-3+20 \\ &= 19 \\ \end{align*}
^D
\begin{align*} x &= 2-3+20 \\ &= 19 \\ \end{align*}
```
However, if you do `-t html --mathjax`, you'll get the `\[..\]` as reported. This is a feature, as it allows this content to be passed to mathjax, which doesn't mind the `\[..\]` surrounding.

**Comment by sn0wyfall** [comment]
Huh, I just updated to 1.19 (I was on 1.17 or something like that!) and now it seems to work fine. Maybe it was a bug with the older version. Sorry for the inconvenience.
