### ISSUE TITLE
Bug in html to docx conversion

### ISSUE THREAD

**Issue by mdolginin** [jgm/pandoc#3280]
After update to pandoc 1.19 I can't open result docx files in MS Word (version 15.28) because of error (see the screenshot, some text in russian).

<img width="429" alt="2016-12-05 15 37 58" src="https://cloud.githubusercontent.com/assets/9402510/20883699/ef612a9a-bb00-11e6-9d2c-dd026cb6e65f.png">

If I use pandoc 1.18 there is no such problem.

**Comment by jgm** [comment]
Are you using a custom reference.docx?

(Or do you perhaps have one in ~/.pandoc?)

+++ Maksim [Dec 05 16 03:43 ]:

**Comment by mdolginin** [comment]
Yep. I'm using a custom reference file

**Comment by jgm** [comment]
Did you try pandoc 1.18 with the very same reference.docx
file?

Your best bet with reference.docx is to start with the
default one and modify it minimally, just by changing the
styles.  If there's any added content, it can cause this
sort of corruption.

+++ Maksim [Dec 05 16 03:52 ]:

**Comment by mdolginin** [comment]
There is same error when I try default reference.docx in pandoc 1.19. When I remove 1.19 and install 1.18 error is gone.

**Comment by mdolginin** [comment]
But if I try to open result docx in LibreOffice it works fine

**Comment by jgm** [comment]
Can you send or link to the reference.docx you're using?

+++ Maksim [Dec 05 16 22:32 ]:

**Comment by mdolginin** [comment]
It is a default reference that store in pandoc dir by this command pandoc -f html -t doc -o myfile.docx myfile.txt (I don’t know how send it to you)

However, I created a custom reference docx file. See it in attach

Долгинин Максим
maksim@dolginin.ru

**Comment by jgm** [comment]
+++ Maksim [Dec 05 16 23:23 ]:
>   It is a default reference that store in pandoc dir by this command
>   pandoc -f html -t doc -o myfile.docx myfile.txt (I don’t know how send
>   it to you)

Don't create your default reference.docx that way.  It will
very likely not work if your document contains anything
complex.

Instead, I suggest

    pandoc --print-default-data-file=reference.docx > myfile.docx

or maybe

    echo "" | pandoc -o myfile.docx

**Comment by mdolginin** [comment]
here is my default reference (after execute pandoc --print-default-data-file=reference.docx > myfile.docx)

[myfile.docx](https://github.com/jgm/pandoc/files/633386/myfile.docx)

**Comment by jgm** [comment]
Odd, I had no trouble creating a docx using pandoc 1.19 with your original ref.docx.  If you want to repeat what I did, it was

    pandoc --reference-docx ref.docx -o my.docx MANUAL.txt

with the pandoc MANUAL.txt.  Can you try that and see if it works?  To get a copy of the manual you can use `pandoc --print-default-data-file MANUAL.txt > MANUAL.txt`.

I've got Word for Mac 2011, by the way.  Perhaps this is sensitive to Word version?

**Comment by jgm** [comment]
Also, can you do the conversion you were trying before with the default reference.docx you just generated?

**Comment by mdolginin** [comment]
> with the pandoc MANUAL.txt. Can you try that and see if it works? To get a copy of the manual you can use pandoc --print-default-data-file MANUAL.txt > MANUAL.txt.

It works fine with MANUAL.txt.

But if I try to do this with html file with table (in attachment) I get an error. This HTML doc was generated from asciidoctor file. (In pandoc 1.18 this works fine)

[dostup_test.html.zip](https://github.com/jgm/pandoc/files/633662/dostup_test.html.zip)

P.S. thank you for dealing with this issue. I appreciate it
Pandoc is very usefull tool 👍

**Comment by jgm** [comment]
OK.  It's really not about the reference.docx; you can get the failure with just
```
pandoc dostup_test.html -o dostup_test.docx
```
If one does `pandoc -t native dostup_test.html` it's clear what (one) problem is. Pandoc's HTML reader is producing a bunch of spurious empty table rows.
I conjecture this has something to do with commit 5222572033e12948de2786122532f3c589145fe1; that's the only thing that affected table parsing in the HTML reader between 1.18 and 1.19.

**Comment by jgm** [comment]
Oh, I see the problem.  I have `addEmpties` where I should have `map addEmpties`.

**Comment by jgm** [comment]
Several mistakes in that code now fixed!
Thanks for reporting this.

**Comment by mdolginin** [comment]
Thanks man
