### ISSUE TITLE
problem installing under Windows

### ISSUE THREAD

**Issue by justwanttocontactpandocsupport** [jgm/pandoc#3282]
Hi,

I'd like to install pandoc on Windows 7 Enterprise, using pandoc-1.19-windows.msi. This error arises. 

![image](https://cloud.githubusercontent.com/assets/24415830/20934843/e1795042-bbdc-11e6-9aa4-35fe5c4be48b.png)

The MSI los contains no error, here the last lines:

```
Action ended 15:50:33: CostFinalize. Return value 1.
MSI (c) (28:A4) [15:50:33:203]: Doing action: SetARPINSTALLLOCATION
Action 15:50:33: SetARPINSTALLLOCATION. 
Action start 15:50:33: SetARPINSTALLLOCATION.
MSI (c) (28:A4) [15:50:33:204]: PROPERTY CHANGE: Adding ARPINSTALLLOCATION property. Its value is 'C:\Users\Stefan\AppData\Local\Pandoc\'.
Action ended 15:50:33: SetARPINSTALLLOCATION. Return value 1.
MSI (c) (28:A4) [15:50:33:204]: Skipping action: WelcomeDlg (condition is false)
MSI (c) (28:A4) [15:50:33:204]: Doing action: AdvancedWelcomeEulaDlg_Custom
Action 15:50:33: AdvancedWelcomeEulaDlg_Custom. 
Action start 15:50:33: AdvancedWelcomeEulaDlg_Custom.

```
What do I do wrong?

Regards
Stefan

**Comment by jgm** [comment]
Puzzling.  I'm sorry, I don't know much about Windows.  @nkalvi any ideas?

**Comment by nkalvi** [comment]
@justwanttocontactpandocsupport I'd like to look into this more - could you please provide 
- whether Windows installation is 32bit or 64bit
-  the account is an admin account

**Comment by ickc** [comment]
@justwanttocontactpandocsupport, did you experience anything like this on any other installation?

When I googling it, the closest thing I can find is [.NET Framework 4.5 Won't Install "Not enough Disk Space on - Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_install/net-framework-45-wont-install-not-enough-disk/2a6d47da-7346-43c9-9e47-4f3be32489e9).

Can you try to re-install the .NET? pandoc uses WiX toolset which uses .NET. That might be related.

And if that doesn't help, can you try to install an earlier version on the same machine, and then the same version on a different machine (while similar enough, say, a colleague's computer with almost identical setup)? Thanks.
