### ISSUE TITLE
colgroup messes up detection of non-simple tables in html reader

### ISSUE THREAD

**Issue by mvz** [jgm/pandoc#3286]
While trying to find a workaround for #2576 when converting from HTML, I found that `colgroup` elements in tables cause the HTML reader to classify the table as simple and set all widths to 0. The following HTML demonstrates this:

```html
<table>
  <colgroup>
    <col style="width: 50%;">
    <col style="width: 50%;">
  </colgroup>
  <tr>
    <td>A</td>
    <td>B</td>
  </tr>
  <tr>
    <td><div>A</div></td>
    <td>B</td>
  </tr>
</table>
```

This results in the following native output (note the widths set to 0):

```
[Table [] [AlignDefault,AlignDefault] [0.0,0.0]
 []
 [[[Plain [Str "A"]]
  ,[Plain [Str "B"]]]
 ,[[Div ("",[],[])
    [Plain [Str "A"]]]
  ,[Plain [Str "B"]]]]]
```

Removing the colgroup gives the following (widhts set to 0.5):

```
[Table [] [AlignDefault,AlignDefault] [0.5,0.5]
 []
 [[[Plain [Str "A"]]
  ,[Plain [Str "B"]]]
 ,[[Div ("",[],[])
    [Plain [Str "A"]]]
  ,[Plain [Str "B"]]]]]
```

Edit: I'm using pandoc 1.17.2, but the `isSimple` code doesn't seem to have changed since then.

**Comment by jgm** [comment]
It will work properly if you use the `width` attribute instead of `style="width...`.

**Comment by mvz** [comment]
Ah, ok. Then the behavior makes sense since the width value is not set on `col`, and the `isSimple` check has nothing to do with it. Thanks!

**Comment by jgm** [comment]
I added a patch so we can handle the `style` version too.
