### ISSUE TITLE
Github Markdown: Newline within table cell breaks output

### ISSUE THREAD

**Issue by cweiske** [jgm/pandoc#3287]
When a table cell contains a newline, the generated markdown contains no standard markdown table but HTML code:

Input HTML:
```
<table>
 <tbody>
  <tr><td>a<br>b</td></tr>
 </tbody>
</table>
```

As soon as the `<br>` is removed, the correct table code is generated.

I'd say please remove the newline from the cell and replace it with a space. That's better than having HTML code in the generated markdown

## Command used
```
$ pandoc --from html --to markdown_github html-test.html 
<table>
<tbody>
<tr class="odd">
<td>a<br />
b</td>
</tr>
</tbody>
</table>
```

without newline:

```
$ pandoc --from html --to markdown_github html-test.html 
|     |
|-----|
| a b |
```

## Version
    $ pandoc --version
    pandoc 1.19

**Comment by jgm** [comment]
Pandoc falls back to HTML (which is legit in Markdown) when it can't render all the semantic elements of the source as a GitHub pipe table. This is better behavior, in my opinion, than changing the meaning of the document (removing a line break) just so it can be a GitHub markdown table.
