### ISSUE TITLE
formatting style from reference.docx recognized for div, but not span

### ISSUE THREAD

**Issue by mschroen** [jgm/pandoc#3290]
According to the Pandoc Guide, markdown code can contain something like

    <span custom-style="comment">x</span>
    or
    <div custom-style="comment">x</div>

which will show up in docx output as "x" styled with the formatting style "comment", which can be previously defined in a `reference.docx` file and appended to the pandoc command via the flag `--reference-docx`.

So far so good. However, I can get this only to work when using the `<div>`-ish way. For `<span>`, Word does not apply the formatting (e.g. bold or color), but it seems to at least recognize the formatting style correctly. The latter can be confirmed by right-click on the "x" in Word, where Word offers to "update the comment formatting style according to the current format". Interestingly, when you do this and added a format (e.g. color) to "x" manually before, then all `<span>`-elements in the Word document automatically get the new color.

So the internal structure of style-assignments has been set right by pandoc, but the formatting itself is not working.

**Comment by jkr** [comment]
Can you give input, output, and reference.docx you were using to illustrate this issue?

Just to make sure -- you had previously defined your spans (i.e. "red", or "bold", or whatever) in the reference.docx, right?

**Comment by jgm** [comment]
Word has a distinction between character and paragraph styles.
That may be relevant here -- perhaps you defined a character style named 'comment', but not a paragraph style?

**Comment by jgm** [comment]
The span:
```xml
      <w:r>
        <w:rPr>
          <w:rStyle w:val="comment" />
        </w:rPr>
        <w:t xml:space="preserve">
x
</w:t>
      </w:r>
```
The div:
```xml
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Compact" />
        <w:pStyle w:val="comment" />
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">
x
</w:t>
      </w:r>
    </w:p>
```

**Comment by mschroen** [comment]
Hey, thanks for your quick responses, I tried out all different ways of defining formatting styles in MS Word before I posted this issue. However, there was a tiny bit which I did not try before: The MS Word *style type* of my "comment" style was set by MS Word to "Combined (Paragraph and Character)", but it should be only "Character". It is only possible to set/change this property during definition-time in MS Word. Then, the whole styling of pandoc documents in MS Word works like a charm!

Sorry for having bothered the pandoc issue pages with this, I am very poor with Word, but I hope you'll agree that the formatting style descriptions in MS Word are kind of unlogical (at least to me).

**Comment by jgm** [comment]
Can this issue be closed?

**Comment by Dulani** [comment]
So, this is still an issue of sorts (which just consumed a couple of hours of my time trying to figure out what was going on).  I tested this with Pandoc 2.0.5 on Linux (Redhat).  

Essentially, if there are **spaces** in the character style's name, Pandoc somehow doesn't manage to get the span/character style applied where it should be.  With div/paragraph styles, this issue doesn't occur. 

The attached input markdown, output docx, and refdoc docx can be used to reproduce the issue:
[input_markdown.txt](https://github.com/jgm/pandoc/files/1583802/input_markdown.txt)
[output_docx.docx](https://github.com/jgm/pandoc/files/1583803/output_docx.docx)
[refdoc_for_issue.docx](https://github.com/jgm/pandoc/files/1583804/refdoc_for_issue.docx)

**Comment by jgm** [comment]
@Dulani thanks for giving us the info we needed to fix this!

**Comment by kronicd** [comment]
This issue seems to have returned, can this be looked at again?

**Comment by jgm** [comment]
This isn't the same issue; see the replies on pandoc-discuss.
