### ISSUE TITLE
Linker error on macOS/OS X 10.9+

### ISSUE THREAD

**Issue by maseek** [jgm/pandoc#3291]
Hey,

I ran into a problem trying to build the project with `stack build` or `stack install` on macOS/OS X version >= 10.9. It spits out this linker error:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1) 
```

Cheers,
Tomas

**Comment by jgm** [comment]
Reproducing comment on PR:

I'm confused.  We have travis builds that build pandoc constantly on OSX (version 10.11 currently).  Never a problem.  I also develop on OSX.  Nor have I seen any notice about the need for this on Haskell forums.

**Comment by maseek** [comment]
Apologies for the confusion, I should have looked into it further before I opened the issue as I am unable to reproduce it anymore, so I'm not sure what actually caused this. Feel free to close.

**Comment by jgm** [comment]
OK, will close then!
