### ISSUE TITLE
Beamer: LaTeX error with highlighted code inside notes div

### ISSUE THREAD

**Issue by daamien** [jgm/pandoc#3293]
Hi !

Thanks for this wonderful software !

Here's a markdown that I can't compile into beamer. Any other output format (pdf, revealjs, epub) are compiled without problem.

You can download the file here: 
https://gist.githubusercontent.com/daamien/621c2ec08df2fcfc24b2d034ed50f323/raw/12eb521dc1e5f9b86e33340127ed4f1734fe0a9d/test_bug_%2525.md

The problem always occurs within a ```<div class="notes"></div>``` section : if there's  a SQL code bloc like this 
<pre>
```sql
 %
```
</pre>

The % character is not properly escaped in the tex output and then create an error during the pdf generation. 

Here the full test case:

```
$ pandoc --version
pandoc 1.19
Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3
Default user data directory: /home/damien/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ pandoc -st beamer test_bug_%.md -o bug.pdf
! File ended while scanning use of \beamer@readarg.
<inserted text> 
                \par 
l.132 \end{frame}

pandoc: Error producing PDF
```

**Comment by jgm** [comment]
Smaller repro:
````
# slide

<div class="notes">
```sql
hi % there
```
</div>
````

**Comment by jgm** [comment]
This may be a beamer problem rather than something that can be fixed in pandoc.

In this case, the `\note` command is getting confused about where it argument ends, because of the verbatim environments it contains.  (Note that these modify how characters like `%` are to be parsed.)

````
\begin{frame}[fragile]{slide}

\note{\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hi % there}
\end{Highlighting}
\end{Shaded}
}

ok

\end{frame}
````

You might ask on a LaTeX forum (using the pandoc produced tex source) whether there's any way to make this work. If there is, we can try to use it in pandoc.

**Comment by jgm** [comment]
Even more minimal case (causes error with `pandoc -t beamer -o my.pdf`):
```
<div class="notes">

	#

</div>
```
Here's the latex code pandoc produces:
```
\begin{frame}[fragile]

\note{\begin{verbatim}
#
\end{verbatim}
}

\end{frame}
```
You should use this when asking in TeX forums, because it doesn't require any special packages like fancyvrb or any special macro definitions.  Or use a version with `%` instead of `#`.

**Comment by daamien** [comment]
Hi @jgm ! 

Thanks for quick reply ! Your comments are helpful 

I've posted the question here :
http://tex.stackexchange.com/questions/343225/problems-with-inside-a-verbatim-thats-inside-a-note

And I think the following thread is related to the problem:

http://tex.stackexchange.com/questions/134289/handle-character-in-verbatim-inside-a-grey-box

**Comment by daamien** [comment]
Seems like the verbatimbox package is the proper way to use a verbatin inside a note
http://tex.stackexchange.com/a/343243/120740

```latex
\documentclass{beamer}
\usepackage{verbatimbox}
\begin{document}
\begin{frame}[fragile]
\begin{verbbox}
 # verbatim
 \material $%here
\end{verbbox}
\note{\theverbbox}
\end{frame}
\end{document}
```

Anyway this may be a silly idea but the notes are not displayed in the final beamer export... So I wonder why we even need to take care of it. Is it possible to simply ignore or remove the `<div class="notes">........</div>` blocks in the markdown file when generating a beamer output ?

**Comment by jgm** [comment]
>   Anyway this may be a silly idea but the notes are not displayed in the
>   final beamer export... So I wonder why we even need to take care of it.
>   Is it possible to simply ignore or remove the <div
>   class="notes">........</div> blocks in the markdown file when
>   generating a beamer output ?

To display the notes in your beamer document, you need to
add this to your YAML metadata:

    classoption:
    - notes

or alternatively invoke pandoc with

    -V classoption='notes'

Thanks for the pointer about verbatimbox.  I'm not sure
it's worth the fairly involved changes that would be needed
to make pandoc use this (also, we try not to depend on
obscure latex packages).

**Comment by daamien** [comment]
Hi !

Sorry my previous message was not clear. We don't want to display the notes in the beamer document. The notes are displayed in others export formats (epub, odt, etc. ).

My question is there a way to simply ignore or remove the content of ```<div class="notes">........</div>``` blocks in the beamer pandoc template ? 

This would be a praticable workaround to the current problem.... The SQL code blocks that break the beamer export are notes and they don't have to be displayed, so why not removing them form the beamer  export and kill the problem at its source ?

**Comment by jgm** [comment]
+++ damien clochard [Dec 10 16 06:29 ]:
>   Sorry my previous message was not clear. We don't want to display the
>   notes in the beamer document. The notes are displayed in others export
>   formats (epub, odt, etc. ).
>
>   My question is there a way to simply ignore or remove the content of
>   <div class="notes">........</div> blocks in the beamer pandoc template
>   ?

I'd suggest using a pandoc filter to remove all Div elements
with class "notes" when writing to beamer.  Such a filter
would be quite easy to write. (See Scripting with pandoc on
the website.)

In Haskell, something like this:

    import Text.Pandoc.JSON

    main = toJSONFilter removeNotes
      where removeNotes (Div (_,["notes"],_) _) = Div ("",[],[]) []
            removeNotes x = x

**Comment by cagix** [comment]
@daamien I'm doing something very similar in https://github.com/cagix/pandoc-lecture ...

Instead of using the `\note{}` command provided by beamer I use a custom `\notesbegin` and `\notesend` (declared void, i.e. `\newcommand{\notesbegin}{}` and `\newcommand{\notesend}{}`, in my latex include file) and use a simple filter (using [pandocfilters](https://github.com/jgm/pandocfilters)) when creating beamer slides.  This way you can put even listings or sections into your notes :)

**Comment by daamien** [comment]
@jgm : the haskell script works fine ! I understand that fixing this problem adds complexity to the code base for a pretty narrow usecase.  The haskell filter is an acceptable workaround for us. You can close this issue. Thanks a lot for your time and your explanations

@cagix : Many thanks for the python script. Haskell looks a bit frightening to me so we'll definitely consider writing filters in Python and your example is a great starting point.
