### ISSUE TITLE
[Beamer] Latex error when compiling a markdown file with a code bloc containing a #

### ISSUE THREAD

**Issue by daamien** [jgm/pandoc#3294]
This bug is similar to #3293 

Here's a markdown that I can't compile into beamer. Any other output format (pdf, revealjs, epub) are compiled without problem.

You can download the file here:
https://gist.githubusercontent.com/daamien/8e7f81af82c19aa4b96a50c9494857ed/raw/0a2be32e0ec0d4e5b7834b6c82388b46b98ef860/test_bug_%2523.md

The problem always occurs within a `<div class="notes"></div>` section : if there's a code bloc like this:

<pre>
```
 #
```
</pre>

The `# ` character breaks the beamer compilation

Here the full test case:

```
$ pandoc --version
pandoc 1.19
Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3
Default user data directory: /home/damien/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ pandoc -st beamer test_bug_#.md -o bug.pdf
! Illegal parameter number in definition of \beamer@todo.
<to be read again> 
                    
l.13 }

pandoc: Error producing PDF
```

**Comment by jgm** [comment]
Same issue as #3293, essentially.
