### ISSUE TITLE
pandoc doesn't urlencode umlauts in slide titles

### ISSUE THREAD

**Issue by oli-obk** [jgm/pandoc#3299]
If I add a slide called "Einführung" to a markdown presentation and generate it to html with slidy and add a table of contents, the hyperlink in the table of contents won't work. Since changing the `ü` to a `u` works, I assume that at least firefox can't work with umlauts in node ids. The most sensible thing to do would probably be to simply encode (url, base60, ... whatever works) all of those, since there's no reason ever for a user to manually enter such an id.

**Comment by mb21** [comment]
Works for me in Firefox 49 on Mac, you sure you enabled standalone `-s` which specifies unicode etc?

    echo '# Einführung' | pandoc -o foo.html -s --toc

I think the ids actually used to be encoded by pandoc but this was changed since all major browsers support this now...

**Comment by jgm** [comment]
As @mb21 says.  Note, you can also try with `--ascii`, which will give you entities instead of the unicode character.  That may not make a difference with an old browser, I'm not sure.
