### ISSUE TITLE
Unwanted escaping of LaTeX in `header-includes`

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#3300]
I am seeing some unwanted LaTeX escaping when the LaTeX is coming from `header-includes` YAML field. E.g., using the following Markdown...

```markdown
---
header-includes:
  - \makeatletter
  - \def\fps@figure{p}
  - \def\fps@figure\\{p\\}
  - \makeatother
---

Testing.
```

... I get the following LaTeX (with `--self-contained` and most of the preamble removed for brevity):

```latex
\makeatletter
\def\fps@figure\{p\}
\def\fps@figure\textbackslash{}\{p\textbackslash{}\}
\makeatother

\date{}

\begin{document}

Testing.

\end{document}
```

As you can see, the lines pasted from `header-includes` have the backslashes and curly braces escaped as if we were pasting just plain text instead of LaTeX macros. The `\def\fps@figure\\{p\\}` line in the test case is there just to demonstrate the escaping happening.

**Comment by jgm** [comment]
Dup of #2139
