### ISSUE TITLE
JavaScript inside HTML inside Markdown: closing "</script>" tag not recognized correctly

### ISSUE THREAD

**Issue by rluzynski** [jgm/pandoc#3302]
I write a text in Markdown format containing some HTML examples which have JavaScript scripts embedded. Everything works smoothly (congratulations!) except the closing ```</script>``` tag. Consider this example:

```html
<script type="text/javascript">
var t = 3;
function test() {
        console.log("t = " + t);
}
</script>
```

As far as I can see it is formatted correctly in GitHub. But the output from pandoc is:

```html
<div class="sourceCode">
<pre class="sourceCode html"><code class="sourceCode html"><span class="kw">&lt;script</span><span class="ot"> type=</span><span class="st">&quot;text/javascript&quot;</span><span class="kw">&gt;</span>
<span class="kw">var</span> t <span class="op">=</span> <span class="dv">3</span><span class="op">;</span>
<span class="kw">function</span> <span class="at">test</span>() <span class="op">{</span>
    <span class="va">console</span>.<span class="at">log</span>(<span class="st">&quot;t = &quot;</span> <span class="op">+</span> t)<span class="op">;</span>
<span class="op">}</span>
<span class="op">&lt;</span><span class="ss">/script&gt;</span></code></pre>
</div>
```

As you can see, the closing ```</script>``` tag has been parsed as part of JavaScript code: ```<``` is tagged as having ```class="op"``` (operator) and then the rest of the tag (```/script>```) as ```class="ss"``` (special string).

Instead whole ```</script>``` tag should be recognized as HTML closing tag rather than JavaScript code and the whole line should be:

```html
<span class="kw">&lt;/script&gt;</span>
```

Tested with pandoc-static 1.16.0.2-1 on Fedora 24 and pandoc-static 1.17.0.3-2 built for Fedora 25 but also installed on Fedora 24, command line to generate the output:

$ pandoc --from=markdown_github --to=html --standalone --output=test.html test.md

**Comment by jgm** [comment]
I see this in pandoc 1.19 too.

First thing to do is to look at the html.xml highlighting
definition file from Kate, to make sure it doesn't have a
bug.  Pandoc's highlighters are autogenerated from these.

(See jgm/highlighting-kate)

**Comment by jgm** [comment]
Aha, this bug has already been reported in
jgm/highlighting-kate#91

**Comment by jgm** [comment]
This is now fixed (by use of new highlighting library skylighting).
