### ISSUE TITLE
Feature request: support colon alignment markers in all table types

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#3303]
I wish pandoc would support colon alignment markers in all table types, as it currently does in pipe tables.

Would this be reasonably easy to implement? Any reasons it might be a bad idea?

**Comment by jgm** [comment]
It does now do this in grid tables (recent change).

For the other types of tables, alignment is done differently, by actually aligning the text.
This gives better looking source, and I don't want to change that.
