### ISSUE TITLE
Pandoc .tex to .rtf conversion crashes if breakurl package is used

### ISSUE THREAD

**Issue by ruipaulo** [jgm/pandoc#3305]
Hello Pandoc team,

first of all, a big Thank You for the wonderful software you are developing! I think I found a bug in pandoc, but maybe it is just a weird thing on my system: Once I add the breakurl package to my .tex pandoc crashes. 

example.tex
```
\documentclass[10pt,a4paper,onecolumn,twoside,openright]{book}
 \usepackage{breakurl}						
\begin{document}
\end{document}
```

```
$ pandoc -s example.tex -o example.rtf
pandoc.exe:
Error at "source" (line 1, column 15):
unexpected "["
expecting letter or lf new-line
\documentclass[10pt,a4paper,onecolumn,twoside,openright]{book}
              ^
CallStack (from HasCallStack):
  error, called at src\Text\Pandoc\Error.hs:66:13 in pandoc-1.19-9b1eC81onfVIUU1LHjhu6R:Text.Pandoc.Error

```
```
$ pandoc -v
pandoc.exe 1.19
Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3
Default user data directory: C:\Users\Paulo\AppData\Roaming\pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
If you need further information please let me know.

**Comment by jgm** [comment]
Can't reproduce this at all.
Does it behave differently if you delete the `\usepackage{breakurl}` line from the file?  Can you try?
Can you link to a version of example.tex rather than just pasting the lines?  Perhaps there's a hidden character or something?

**Comment by ruipaulo** [comment]
The error disappears if I delete the \usepackage{breakurl} line.
But something super weird happens: If I put the file inside a git repository folder, the error occurs, if I have it outside of it the file compiles normally. Exactly the same file! 
Probably it is just a weird thing on my system, so if you want to close the issue, nevermind. If you want to dive into it I can try further things. 

You can find the file here: https://www.dropbox.com/s/s64v3e8ccxwk04o/example.tex?dl=0

**Comment by jgm** [comment]
Couldn't repro with that file either!
