### ISSUE TITLE
svgs don't show up in wkhtmltopdf pdf if converted from markdown

### ISSUE THREAD

**Issue by oli-obk** [jgm/pandoc#3307]
Including svg images when converting from markdown to pdf with wkhtmltopdf (output format html5, output filename .pdf) doesn't work. Instead one first has to convert the markdown to html (and enable standalone + self-contained) and then convert the html to pdf

**Comment by mb21** [comment]
I think this is an [issue with wkhtmltopdf](http://stackoverflow.com/questions/12395541/wkhtmltopdf-failure-when-embed-an-svg), for which are two resolutions:

1. specifying width and height explicitly: `![](logo.svg){width=200 height=300}`
1. as you suggested, converting to html with `self-contained`, which embeds the whole image, so the dimensions are known to wkhtmltopdf again...
