### ISSUE TITLE
Add `--bom` Option

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#3312]
Even if the official standard doesn't advice to add a BOM for UTF8 files (nor it forbids it!), there are frequent cases when one would like to include a BOM -- for example, Microsoft enforces/requires BOM in many of its products, but it would also be useful in UTF8 plain text documents with custom extensions or no extensions at all (eg a `LICENSE` file).

The  `--bom` option could enforce a BOM (of the correct type, according to language, but I'd say defaulting to UTF8). Since it would be an optional feature up to the user, it shouldn't create any problems for anyone nor break any sort of compatiblity. An harmless feature.

Currently, when converting to `plain` format you get no BOM, even if there characters outside the ASCII range. Under Windows, not all programs are smart enough to assume UTF8 and endianess, therefore many characters end up misrepresented (especially non-English special characters).

**Comment by mb21** [comment]
Not sure that this feature warrants inclusion in pandoc. You can [easily write your own script](http://stackoverflow.com/a/37425154/214446) to add a byte order mark...

Pandoc expects all input to be in UTF-8 and produces only UTF-8 (except for the packaged formats like docx and epub)

**Comment by tajmone** [comment]
I hoped to hear other users voice on this.

It's true that one can easily use a filter to achieve this, or (like pandoc documentation mentions) use iconv tool; but there some Windows related work scenarios that might make this feature worth implementing.

For example, I often use pandoc to generate html pages to be viewed inside software applications via embedded MS Web Browser control. In this case, having the BOM is necessary. Similarly, CHM documents work on the same principle.

After all, using the BOM in UTF-8 files is not against the standard, even though it's common practice not to. Since it falls withing the standards, in my view pandoc should offer built-in support for it.
