### ISSUE TITLE
pandoc: Error in $: endOfInput CallStack (from HasCallStack):   error, called at pandoc.hs:144:42 in main:Main

### ISSUE THREAD

**Issue by twardoch** [jgm/pandoc#3313]
I’m trying to get a Python Pandoc filter working (using `pandocfilters`). I’m struggling with the error: 
```
pandoc: Error in $: endOfInput
CallStack (from HasCallStack):
  error, called at pandoc.hs:144:42 in main:Main
```
which appears when my Python filter calls a Java-tool. 

## Background

I’ve written a tool which “improves” the `.docx` to `.md` conversion, [docxtomd](https://github.com/twardoch/markdown-utils/tree/master/docxtomd). There are three parts of the tool: 

1. `docxtomd.py` is the main Python tool which calls Pandoc twice: once to convert `.docx` to `.json` while also extracting the media from the `.docx`, and then again to convert `.json` to `.md`. I had to run Pandoc twice because the process of extracting the media wasn’t always timed well with the calls to the filter (sometimes the filter couldn’t find the media file because it wasn’t yet written). 

2. `pandoc-wmftosvgpng.py` is a Python Pandoc filter which is called during the `.json` to `.md` conversion. Its task is to prettify the filenames of the extracted media based on the `alt` attribute of the images, stored in the `.json`, and also to convert the extracted `.wmf` files intelligently into either `.svg` or `.png`. 

3. `wmftosvgpng.py` is the Python module (also usable standalone) which the filter calls, which does the conversion from `.wmf` to `.svg` or `.png`. This tool internally calls the Java-based `[wmf2svg](https://github.com/hidekatsu-izuno/wmf2svg)` tool which yields best results out of many WMF-to-SVG conversion paths that I’ve tried. 

## Requirements

To run the test case, you need: 
1. A reasonably up-to-date Java environment. 
2. The Java-based [wmf2svg](https://github.com/hidekatsu-izuno/wmf2svg) tool. Download the repo, build it with `ant`, unzip, move `wmf2svg-0.9.8.jar` to `/usr/local/java`. 
3. A clone of my https://github.com/twardoch/markdown-utils/ repo. 

## Test case

when you’re in `markdown-utils`, do: 
```
cd docxtomd
./docxtomd.py -v -d test/test1 test/test1.docx
```

and you’ll get

```
$ ./docxtomd.py -v -d test/test1 test/test1.docx
Running: /usr/local/bin/pandoc --from=docx --to=json ./test/test1.docx --output=./test/test1/test1.md-tmp.json --smart --section-divs --atx-headers --extract-media=.
Running: /usr/local/bin/pandoc --from=json --to=markdown_github-pipe_tables+auto_identifiers+backtick_code_blocks+blank_before_blockquote+blank_before_header+bracketed_spans+definition_lists+escaped_line_breaks+fenced_code_attributes+footnotes+grid_tables+header_attributes+implicit_header_references+line_blocks+pandoc_title_block ./test/test1/test1.md-tmp.json --output=./test/test1/test1.md --smart --section-divs --atx-headers --filter=./pandoc-wmftosvgpng.py
.svg: ./test/test1/img/image2.svg
./media/image2.wmf: img/image2.svg

pandoc: Error in $: endOfInput
CallStack (from HasCallStack):
  error, called at pandoc.hs:144:42 in main:Main


Done.
```

**Comment by jgm** [comment]
This could be because of changes in the JSON serialization
in pandoc 1.18.  See the changelog for details.

**Comment by twardoch** [comment]
I have moved the buggy code for reference to https://github.com/twardoch/markdown-utils/tree/master/docxtomd-old 

I now have a more elaborate implementation at https://github.com/twardoch/markdown-utils/tree/master/docxtomd 

This one does **three** steps instead of two: 

1. Convert the `.docx` to `.doc.json` using Pandoc, extracting media.
2. Calls the `wmftosvgpng` tool on all extracted media. This tool uses a Java tool [`wmf2svg`](https://github.com/hidekatsu-izuno/wmf2svg) to convert `.wmf` into `.svg`, then parses the `.svg` and if the `.svg` only contains one embedded PNG bitmap, saves it as a plain `.png`. This also produces a `.media.json` file which contains some mapping between the old and the new files.
3. Convert from `.doc.json` to `.md` using Pandoc, calling the `pandoc-mapmedia.py` Pandoc filter, which remaps the path references to the media files and renames those which have the `alt` attribute available. It also copies the new media files from the `media/` subfolder into the `img/` subfolder.

The intermediate step (calling the Java `wmf2svg` tool) is now moved outside the Pandoc filter and is called between the two Pandoc calls. I haven’t changed anything about interacting with the JSON model, so I don’t think it’s the issue with the JSON serialization. It has to do with the Haskell-Python runtime interaction, it seems, because once I moved the costly Java calls out of the filter, everything works smoothly.

**Comment by jgm** [comment]
Speculation:  the java program you're calling prints something to stdout?
This would corrupt the JSON input pandoc is expecting from the filter.

I don't have time to reproduce your environment sufficiently to test and debug this.
If you could confirm or disconfirm the hypothesis above, it might be helpful.
