### ISSUE TITLE
Treat Emacs table.el tables in Org mode files as Pandoc's markdown grid tables

### ISSUE THREAD

**Issue by unixpipecentipede** [jgm/pandoc#3314]
Org mode handles both simple plain ASCII tables (created with `C-c |`)
and Emacs `table.el` tables. The latter are basically the same as
Pandoc's markdown grid tables.

It seems Pandoc's Org reader treats `table.el` tables as Org ASCII
tables, since on conversion to `docx` the output gets mangled when
dealing with rows that contain multi-line paragraphs. The resulting
table arranges every new line of text into --- often several --- new
rows.

On the other hand, Pandoc's markdown documents with grid tables get
what could be called proper treatment, i.e. 1 paragraph (including
multi-lines) == 1 row. This produces somewhat *cleaner*
tables. Division lines are displayed correctly too.

Pandoc's Org reader should distinguish between plain ASCII tables and
`table.el` tables and treat the latter as the markdown reader treats
grid tables.

**Comment by chunlinyao** [comment]
table.el is the only method to support multilines in cell. I have to use `ox-latex` to export when a file contains grid tables.
