### ISSUE TITLE
markdown --> latex: citations not supported

### ISSUE THREAD

**Issue by ber532k** [jgm/pandoc#3315]
Hi there,

I love how citations are implemented in pandoc markdown and tried converting citations from latex to markdown and back again.

Converting: `\autocites[p1]{refkey1}[p2]{refkey2}` correctly produced `[@refkey1 p1; @refkey2 p2]`.
However, converting that back to latex produced `{[}@refkey1 p1; @refkey2 p2{]}`.

Would it be possible to use `\autocites` (note the plural) command as the latex counterpart to markdown citations in some future release?

**Comment by jkr** [comment]
If you convert it back to LaTeX with the `--biblatex` option it should work as expected.

**Comment by ber532k** [comment]
Thanks a lot - my fault. Sorry for the inconvenience.
