### ISSUE TITLE
Using `toc-title` with Markdown (it works!)

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#3318]
In Pandoc user guide we read:
```
toc-title
title of table of contents (works only with EPUB and docx)
```
Actually it works very well also with markdown.

Sometimes I work with multiple markdown source files, which then I process with Pandoc using a markdown template, and build a toc with a title.

If I ask pandoc (v1.19.1) to produce the default markdown template:

```
pandoc -D markdown > default-template.markdwon
```

what I get is this:

```
$if(titleblock)$
$titleblock$

$endif$
$for(header-includes)$
$header-includes$

$endfor$
$for(include-before)$
$include-before$

$endfor$
$if(toc)$
$toc$

$endif$
$body$
$for(include-after)$

$include-after$
$endfor$
```

So, I've edited the `toc` part, and changed it to:

```
$if(toc)$
$if(toc-title)$
# $toc-title$
$endif$

$toc$

$endif$
```

where I'm adding a `$toc-title$` with a header lev.1 ( `# `)

and then invoke pandoc with:

``` 
pandoc --toc -V toc-title:"Table of Contents" ^
	--template=template.markdown ^
	--include-before-body=TOC_TEST.before.md ^
	-f markdown_github ^
	-t markdown_github ^
	-o "TOC_TEST_RESULT.md" ^
	"TOC_TEST.md"
``` 

(I'm using the caret `^` to split on multiple lines under Windows batch file)

The final markdown file (`TOC_TEST_RESULT.md`) will:

1. Show the included file (with `--include-before`) before the generated TOC (and it's headers not indexed in the TOC!)
2. The TOC will show the title set with ` -V toc-title:"Table of Contents"`

Which yelds greate results...

I propose that:

1. The documentation should change the:
     > (works only with EPUB and docx)

   to

    > (works with EPUB, markdown and docx)
2. The default markdown template be changed to include the `$if(toc-title)$` statement block.

**Comment by tajmone** [comment]
Added the above consideration to the Wiki documentation:

https://github.com/jgm/pandoc/wiki/Pandoc-Tricks#using-markdown-templates

**Comment by ickc** [comment]
+1 on the wiki documentation.

I think a post like this should belongs to [pandoc-discuss - Google Groups](https://groups.google.com/forum/#!forum/pandoc-discuss). And if in the discussion they give you the green light, I think you can make pull requests directly to jgm/template and jgm/pandoc.

**Comment by tajmone** [comment]
Thanks, and sorry for posting in the wrong place — I wasn't aware of the discuss group. I'll join in right now.

**Comment by ickc** [comment]
>Thanks, and sorry for posting in the wrong place — I wasn't aware of the discuss group. I'll join in right now.

No problem. And please close this issue too.
