### ISSUE TITLE
Two questions regarding a converter to PandocAST

### ISSUE THREAD

**Issue by hassanshaikley** [jgm/pandoc#3320]
Hey all, I want to know how use divs. 

I also want to understand how to use attributes, I am not sure if it's documented or I don't understand the documentation. Using image width and height would be really appreciated as an example for attributes.

is this correct? (I am pretty sure it is not because my conversion script is failing)

```
var div = {};
div.t = "Div";
div.c = [];
div.c[0] = {}; // Attributes
div.c[1] = []; // Contents
```

How would I give the working image script below a width and height?

```
newNode.t = "Image";
newNode.c[0] = ["",[],[]];
newNode.c[1] = node.attrs.alt ? createTextNodes(node.attrs.alt) : [];
newNode.c[2] = [node.attrs.src, ""];

```

Thank you!

**Comment by ickc** [comment]
Please close this and ask the question in [pandoc-discuss - Google Groups](https://groups.google.com/forum/#!forum/pandoc-discuss). Thanks!
