### ISSUE TITLE
[markdown writer]: long table disappeared

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#3321]
[test.docx](https://github.com/jgm/pandoc/files/662688/987574.151.200.docx)

Applying

```bash
# pandoc 1.19.1
pandoc -s -o test.md test.docx
```

The table becomes

```markdown
++
|  |
++
|  |
++
```

**Comment by ickc** [comment]
Note: if one try `-t markdown-grid_tables`, you will get an HTML table containing all texts in it.

**Comment by ickc** [comment]
This might or might not be related to #3285. I am trying to compile a pandoc from master to test if it has been fixed.

**Comment by ickc** [comment]
I can verify that the HEAD version of pandoc still has this bug.

One property of the table from the docx is that it seems the original author uses a 2 column table to format 2 column texts (it was from doc, may be an ancient trick). So consequently the table only has 1 row, albeit being very very very long.

**Comment by jgm** [comment]
Interestingly, if you write rst (which also uses grid tables), it works.

**Comment by mb21** [comment]
This seems to be fixed somehow in the current master... can you confirm @ickc ?

**Comment by ickc** [comment]
@mb21, I will try it when I have time, probably in a week. (In this holday season I rarely have time in front of my desktop...)

**Comment by ickc** [comment]
@mb21,

Yes, the current master indeed has fixed this already, thanks!
