### ISSUE TITLE
LaTeX output: Long link does not split

### ISSUE THREAD

**Issue by louisabraham** [jgm/pandoc#3328]
If we use either the syntax `<longurl>` or `[longurl](longurl)` to display a functional link, it does not split in a new line. It doesn't work either if we add a space `[longurl ](longurl)`, but for urls and texts that do not match the text splits.

For the moment, my fix is to use https in the link url and http in the text (or conversely), or to add the port number in the url, thus the text and the url are considered different.

I encountered the problem in markdown to pdf conversion, using the option `--latex-engine=xelatex`.

**Comment by mb21** [comment]
Can you give an example? Possibly with the generated latex (`-o output.tex` instead of `-o output.pdf`) and what pandoc version you're using?

Pandoc uses latex by default for PDF generation, there are [a few options](http://tex.stackexchange.com/questions/54946/how-to-break-long-url-in-an-item) on how to break long URLs... which you can try by modifying your pandoc latex template...

**Comment by louisabraham** [comment]
Sure: `<http://verylongurl.com/veryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylongpath>`

I use Pandoc 1.19.1.

After looking at the .tex generated, I understand: when the link and the text are the same, \url is used instead of href.

Adding
    ---
    header-includes:
        - \PassOptionsToPackage{hyphens}{url}\usepackage{hyperref}
    ---
at the beginning doesn't solve my problem…

**Comment by jgm** [comment]
Do you have a suggestion for how we might change pandoc's
output so that the URL would break?

**Comment by wilx** [comment]
I do not think this can be fixed by Pandoc itself or template to satisfy everyone. I would suggest using the following trick put in file included in LaTeX preamble:

```latex
% This allows line breaks in URL in more places.
\def\UrlBreaks{\do\/\do-\do.\do=\do_\do?\do\&\do\%\do\a\do\b\do\c\do\d\do\e\do\f\do\g\do\h\do\i\do\j\do\k\do\l\do\m\do\n\do\o\do\p\do\q\do\r\do\s\do\t\do\u\do\v\do\w\do\x\do\y\do\z\do\A\do\B\do\C\do\D\do\E\do\F\do\G\do\H\do\I\do\J\do\K\do\L\do\M\do\N\do\O\do\P\do\Q\do\R\do\S\do\T\do\U\do\V\do\W\do\X\do\Y\do\Z\do\0\do\1\do\2\do\3\do\4\do\5\do\6\do\7\do\8\do\9}
```

**Comment by dylan-chong** [comment]
@wilx Can you do your UrlBreaks solution in markdown header?

**Comment by wilx** [comment]
[**@dylan-chong**](https://github.com/dylan-chong) commented on [Sep 25, 2017, 10:34 AM GMT+2](https://github.com/jgm/pandoc/issues/3328#issuecomment-331813670 "2017-09-25T08:34:54Z - Replied by Github Reply Comments"):
> [@wilx](https://github.com/wilx) Can you do your UrlBreaks solution in markdown header?

I don't think so. AFAIK, Pandoc will escape the contents of the Markdown metadata block.

**Comment by tolot27** [comment]
> Adding
> 
> ```
> ---
> header-includes:
>     - \PassOptionsToPackage{hyphens}{url}\usepackage{hyperref}
> ---
> ```
> at the beginning doesn't solve my problem…

That will never work because the hyperref package is already loaded, before `header-includes`. Did you try modifying the latex output and compiling it afterwards?

**Comment by louisabraham** [comment]
I tried using \href instead of \url, yes.

**Comment by adunning** [comment]
This was fixed in <https://github.com/jgm/pandoc/commit/b6d13467f6efe0abd09eef6bba7f06138ac9e9ed>, though it requires TeX Live 2018 or later.
