### ISSUE TITLE
Docbook 5 writer: use xml:id tag

### ISSUE THREAD

**Issue by mjang** [jgm/pandoc#3329]
When converting from (canonical) Markdown to Docbook 5, tags include only `id`, such as

\<section id="basic-formatting">

It should convert to 

\<section xml:id="basic-formatting">

The feature request was included in this comment from issue [2164.](https://github.com/jgm/pandoc/issues/2164#issuecomment-103933313)

**Comment by mjang** [comment]
I've verified when converting from 

1) the canonical markdown (daring fireball)
2) CommonMark
3) GH flavored markdown

**Comment by mb21** [comment]
seems like we should indeed use the `xml` prefix (any reason why we don't do that [here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Docbook.hs#L126)?). But we don't have to require it...

from [Namespaces in XML 1.1](https://www.w3.org/TR/xml-names11#ns-decl):

> The prefix xml is by definition bound to the namespace name http://www.w3.org/XML/1998/namespace. It MAY, but need not, be declared, and MUST NOT be bound to any other namespace name.

**Comment by mb21** [comment]
I've hopefully fixed this in [this pull](https://github.com/jgm/pandoc/pull/3330) and added the correct namespace in [this pandoc-templates pull](https://github.com/jgm/pandoc-templates/pull/226). Did I make all the correct changes @mjang ?

**Comment by mjang** [comment]
It looks all right -- I'd check but am having trouble installing the stack
build tool.

Thank you for your fix, and following up.

Thanks,
Mike
