### ISSUE TITLE
Error: pandoc document conversion failed with error 251 // Using R

### ISSUE THREAD

**Issue by cemppa** [jgm/pandoc#3331]
I'm trying to export my mapview in R using built-in mapview-function called mapshot. I get this error message:

**pandoc.exe: Out of memory**

**Error: pandoc document conversion failed with error 251**

**In addition: Warning message: running command 'C:/PROGRA~2/Pandoc/pandoc +RTS -K512m -RTS ...**

How do I increase the Pandoc memory size permanently or even temporary in R without using a Rmarkdown-file? Is there a handle for this? The function in question is called **mapshot**, for example mapshot(m, url=paste0(getwd(), "/heatmap.html")).

**Comment by jgm** [comment]
I don't know, but this sounds like a question for RMarkdown
developers, and you should close this and open an issue on
their tracker instead.

+++ cemppa [Dec 29 16 03:11 ]:

**Comment by cemppa** [comment]
Isn't this a Pandoc related problem? It clearly states that the Pandoc haskell memory has run out.

**Comment by jgm** [comment]
Your question was

> How do I increase the Pandoc memory size permanently or even temporary in R without using a Rmarkdown-file? Is there a handle for this? The function in question is called mapshot, for example mapshot(m, url=paste0(getwd(), "/heatmap.html")).

This is all R-related.  And I have no idea!  I don't know how RMarkdown calls pandoc. The people who would know are the RMarkdown maintainers.  And if there is something pandoc-related they need to find out to answer your question, they can ask here.
