### ISSUE TITLE
[markdown writer] Empty columns in table when first row has only one column

### ISSUE THREAD

**Issue by clopinclopant** [jgm/pandoc#3337]
This looks like an issue in markdown writer.
The file issue.docx when converted to markdown with pandoc-1.19 has the following output:
```
  --------- ------- -------
  SECTION
  COL A
  --------- ------- -------
```
while the expected one is:
```
  --------- ------- -------
  SECTION           
  COL A     COL B   COL C
  --------- ------- -------
```
(generated from converting file passed.docx).

It seems like the docx reader is getting the data right as the rst writer's output for issue.docx is like expected:

```
+-----------+---------+---------+
| SECTION   |
+-----------+---------+---------+
| COL A     | COL B   | COL C   |
+-----------+---------+---------+

```
Thank you for your consideration.
[passed.docx](https://github.com/jgm/pandoc/files/686793/passed.docx)

[issue.docx](https://github.com/jgm/pandoc/files/686794/issue.docx)

**Comment by jgm** [comment]
```
% pandoc -t native ~/Downloads/passed.docx 
[Table [] [AlignDefault,AlignDefault,AlignDefault] [0.0,0.0,0.0]
 [[]
 ,[]
 ,[]]
 [[[Plain [Str "SECTION"]]
  ,[]
  ,[]]
 ,[[Plain [Str "COL",Space,Str "A"]]
  ,[Plain [Str "COL",Space,Str "B"]]
  ,[Plain [Str "COL",Space,Str "C"]]]]]
% pandoc -t native ~/Downloads/issue.docx 
[Table [] [AlignDefault] [0.0]
 [[]]
 [[[Plain [Str "SECTION"]]]
 ,[[Plain [Str "COL",Space,Str "A"]]
  ,[Plain [Str "COL",Space,Str "B"]]
  ,[Plain [Str "COL",Space,Str "C"]]]]]
```
The difference is that in "issue" the header row just has one (empty) cell, while in "passed" it has (as it should) three empty cells.

So there are two questions:

1.  Why is the docx reader returning a header with just one empty cell?
2.  Why does the markdown writer behave as it does when confronted with this?

**Comment by jgm** [comment]
@jkr Any thoughts about this one?

**Comment by jgm** [comment]
@jkr I think I see now. In the docx file, the first table row (header row) has just one `tc` element. So I suppose that's why we get what we get.

And indeed, the reader gives output similar to the output the HTML reader gives on

```
<table>
<tr><td>a</td></tr>
<tr><td>1</td><td>2</td></tr>
</table>
```
So I think the problem is really just with the markdown writer.

**Comment by jgm** [comment]
On second look, it's a bit more complex.

In general, when widths and alignments are not explicitly specified, the readers take them from the headers.

So, for example,
```
% pandoc -f markdown -t native
|a| 
|--|
|b|c|
^D
[Table [] [AlignDefault] [0.0]
 [[Plain [Str "a"]]]
 [[[Plain [Str "b"]]]]]
```
Here we have alignments and widths for only one column, though the second row has two.

Ideally we'd get alignments and widths for all columns, from every reader.  That would be the best solution but would require interventions in most or all readers.  (docx, html, markdown all behave the same in this respect.)

Given that we don't, we could work around this in the markdown writer by padding rows that are "light" relative to the longest row, and padding the alignments and widths too.  But I'm not positive this wouldn't have some weird effects.
