### ISSUE TITLE
drop color and fontSize when convert HTML to docx?

### ISSUE THREAD

**Issue by KMethod** [jgm/pandoc#3338]
I find when I use pandoc to convert HTML to docx,  It drop color and fontSize, is it not support or I use it wrong? 

command I use : 
`pandoc -f html -t docx -s test.html -o test.docx   `

![image](https://cloud.githubusercontent.com/assets/10240163/21681856/27d3790c-d38c-11e6-83d1-21f52e09c65b.png)

**Comment by mb21** [comment]
Pandoc only retains the semantic HTML, no formatting. Please see http://pandoc.org for details...

**Comment by jgm** [comment]
Pandoc ignores CSS and most style commands.  It aims to
capture the structural elements of your text and (as the
manual notes) will typically lose some styling information.

+++ KMethod [Jan 05 17 05:16 ]:
