### ISSUE TITLE
YAML with other markup than emphasis parsed wrong

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#3344]
The following Markdown document:

``` markdown
---
title: **Not** A Title
---
```

gives the following error:

```
pandoc -o metadata-title.epub  metadata-title.md
[pandoc warning] Could not parse YAML header: did not find expected alphabetic or numeric character "source" (line 3, column 9)
```

I’m afraid only emphasis works fine. Any other markup leads to that error.

I’m on Fedora 23 using `pandoc-1.19.1`.

**Comment by jgm** [comment]
Some special characters need quoting or escaping in YAML.

Try

    title: '**Not** A Title'

or

    title: |
      **Not** A Title

**Comment by ousia** [comment]
> Some special characters need quoting or escaping in YAML.

@jgm, sorry it was totally my fault.

I was quoting like this:

``` markdown
---
title: "**Not**" A Title
---
```

Now I see that the whole field contents need to be quoted.
