### ISSUE TITLE
Output auto_identifiers in markdown

### ISSUE THREAD

**Issue by xdbr** [jgm/pandoc#3345]
I like the idea that is outlined in [Pandoc Tricks](https://github.com/jgm/pandoc/wiki/Pandoc-Tricks), converting from markdown to markdown since it essentially would/could possibly allow you to create your own 'canonical markdown' for your own corporation/group/whatever of your own liking.

Thus I would expect the following ...

    echo '# Example Section' | pandoc --atx --id-prefix=sec --to markdown+auto_identifiers

...to output this...

    # Example Section {#sec-example-section}

...just like it does in HTML format:

    echo '# Example Section' | pandoc --atx --id-prefix=sec- --to html
    <h1 id="sec-example-section">Example Section</h1>

However, the output doesn't honor `--to markdown+auto_identifiers` as expected:

    echo '# Example Section' | pandoc --atx --id-prefix=sec --to markdown+auto_identifiers
    # Example Section

**Comment by mb21** [comment]
The trick is to disable `auto_identifiers`.

    $ echo '# Example Section' | pandoc --atx --to markdown-auto_identifiers

    # Example Section {#example-section}

 In https://github.com/jgm/pandoc/commit/15829d5c3a842fdddad149b173b2c57272eeeb57, code was added to not print the ids if they are the same as the automatically-generated ones...

**Comment by xdbr** [comment]
Thanks for clarifying, @mb21! My thinking was just bad. Closing this issue.
