### ISSUE TITLE
don't convert correctly sheets from docx to textile.

### ISSUE THREAD

**Issue by bleedingrose** [jgm/pandoc#3346]
![444](https://cloud.githubusercontent.com/assets/25025280/21796636/9e1fccba-d73c-11e6-91bb-f31ff8307ee8.jpg)
not equal 

[6.txt](https://github.com/jgm/pandoc/files/695445/6.txt)
in textile format
and so on by the all sheets

**Comment by mb21** [comment]
You'll need to post the docx document.

Please also state what exactly is wrong. If you're referring to the table cell that's multiple rows wide, pandoc currently doesn't support col- or rowspans.

**Comment by bleedingrose** [comment]
"pandoc currently doesn't support col- or rowspans." - This is the answer. 10.01.2017, 16:06, "Mauro Bieg" <notifications@github.com>:You'll need to post the docx document.Please also state what exactly is wrong. If you're referring to the table cell that's multiple rows wide, pandoc currently doesn't support col- or rowspans.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jgm** [comment]
OK then, I'll close this.
