### ISSUE TITLE
Does not interpret username and password in http_proxy environment variable 

### ISSUE THREAD

**Issue by halloleo** [jgm/pandoc#3347]
On Windows I use pandoc.exe 1.17.2. When I run (in a bash):

    $ export https_proxy=https://user:password@192.168.81.81:3142
    $ pandoc --self-contained -t revealjs -s slides.mdwn -o slides.html

I get the following error:

    HttpExceptionContentWrapper {unHttpExceptionContentWrapper = InvalidProxyEnvironmentVariable "https_proxy" "https://user:password@192.168.81.81:3142"}

I suspect that pandoc cannot handle credentials in the proxy.

**Comment by jgm** [comment]
I was not able to reproduce this with a recent build of pandoc.
Can you try the latest release?  (There's a windows package.)

**Comment by jgm** [comment]
For me to really reproduce this, you need to supply `slides.mkdwn`.  Presumably that contains some links to images on https?  Or maybe you're using a custom template that links to a remote reveal.js?  In any case, you need to give us more to reproduce the problem.

**Comment by mb21** [comment]
I think the answer to your problem is https://github.com/commercialhaskell/stack/issues/1165

**Comment by halloleo** [comment]
Thanks @mb21, that's exactly it: The https proxy needs to be reachable via http. So 

    $ export https_proxy=http://user:password@192.168.81.81:3142

solved it. 

To @jgm: Yes, my `slides.mdwn` contains links to external images with https-urls
