### ISSUE TITLE
Module ‘Text.Pandoc.Options’ does not export ‘writerStandalone’

### ISSUE THREAD

**Issue by luckypoem** [jgm/pandoc#3350]
hi.

cd /usr/local

git clone https://gitlab.com/doshitan/doshitan.com

cd doshitan.com

cabal sandbox init

cabal install

it shows: ... Configuring doshitan-0.0.0...

Building doshitan-0.0.0...

Failed to install doshitan-0.0.0

Build log ( /usr/local/doshitan.com/.cabal-sandbox/logs/doshitan-0.0.0.log ):

cabal: Entering directory '.'

Configuring doshitan-0.0.0...

Building doshitan-0.0.0... Preprocessing executable 'site' for doshitan-0.0.0...

[1 of 6] Compiling Site.Routes ( src/Site/Routes.hs, dist/dist-sandbox-f2a04341/build/site/site-tmp/Site/Routes.o )

[2 of 6] Compiling Site.Pandoc ( src/Site/Pandoc.hs, dist/dist-sandbox-f2a04341/build/site/site-tmp/Site/Pandoc.o )

src/Site/Pandoc.hs:8:29: error:

Module ‘Text.Pandoc.Options’ does not export ‘writerStandalone’

cabal: Leaving directory '.'

cabal: Error: some packages failed to install:

doshitan-0.0.0 failed during the building phase. The exception was:

ExitFailure 1

root@AR:/usr/local/doshitan.com#

how to fix the error?

tks a LOT.

**Comment by jgm** [comment]
This is not a pandoc bug.
You should consult with the author of
https://gitlab.com/doshitan/doshitan.com
who probably needs some version constraints on pandoc.

writerStandalone was removed in pandoc 1.19.
You'll need to compile against an earlier version
or update the source of 'doshitan'.  See the
pandoc changelog.

You could also try adding

    --constrain 'pandoc < 1.19'

to your cabal install command.

+++ luckypoem [Jan 12 17 17:05 ]:
