### ISSUE TITLE
Combining reference links with footnotes produces unexpected effects

### ISSUE THREAD

**Issue by v1kn** [jgm/pandoc#3352]
pandoc 1.19.1
    Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3

*Using recent The Guardian article as a sample text:* [source](https://www.theguardian.com/technology/2017/jan/13/whatsapp-backdoor-allows-snooping-on-encrypted-messages)

    Facebook [halted the use of the shared user data][06][^L6] for advertising
    purposes in November after [pressure from the pan-European data protection
    agency group][07][^L7] Article 29 Working Party in October. The European
    commission then filed charges against Facebook for providing “misleading”
    information in the run-up to the [social network’s acquisition of messaging
    service WhatsApp][08][^L8], following its data-sharing change.

    [06]: https://www.theguardian.com/technology/2016/nov/17/facebook-halts-use-of-whatsapp-data-for-advertising-in-europe
    [^L6]: https://www.theguardian.com/technology/2016/nov/17/facebook-halts-use-of-whatsapp-data-for-advertising-in-europe
    [07]: https://www.theguardian.com/technology/2016/oct/28/whatsapp-pause-sharing-user-data-facebook-european-privacy-regulators-yahoo
    [^L7]: https://www.theguardian.com/technology/2016/oct/28/whatsapp-pause-sharing-user-data-facebook-european-privacy-regulators-yahoo
    [08]: https://www.theguardian.com/technology/2014/feb/19/facebook-buys-whatsapp-16bn-deal
    [^L8]: https://www.theguardian.com/technology/2014/feb/19/facebook-buys-whatsapp-16bn-deal

*result:* [imgur](http://imgur.com/a/EzUX3)

*additional comments:*
- I believe I have all the necessary extensions in the pandoc invocation
- I use extensively vim's `gw` to wrap text to 80 chars, not sure if this has any influence
- rationale for using both reference links and footnotes: links are better for html, footnotes for pdf, both can make one md file more universal

**Comment by jgm** [comment]
If you put blank lines between your reference definitinos
and your footnote definitions, it will work.

This could be documented better, but I'm not sure it's a
bug.

**Comment by v1kn** [comment]
Indeed separating link and footnotes definitions with one blank line fixes the output. 

A warning concerning this behavior in each extension's section would be great.
