### ISSUE TITLE
Request: Nested Numbered Lists

### ISSUE THREAD

**Issue by phren0logy** [jgm/pandoc#336]
Thanks for an amazing tool! I use it extensively for academic writing. As such, I have a humble request. I looked at the docs and mailing list first; sorry if this has already been addressed. I'd love to see a list like:

 (@) Heading
     (@.@) Subheading
 (@) Another Heading
     (@.@) Another Subheading

Render as:
1. Heading  
    1.1 Subheading
2. Heading  
    2.1 Another Subheading

I don't think this would break anything, but perhaps there is another unintended consequence? Thanks for considering it.

**Comment by vimuel** [comment]
Would like to see this as well.

**Comment by mb21** [comment]
If you're outputting to HTML you can use a nested list and style it with CSS.

```
1. foo
    1. bar
2. baz
```

If you're targeting PDF you can probably [modify your template](http://tex.stackexchange.com/questions/78842/nested-enumeration-numbering).

AFAIK only nested [example lists](http://pandoc.org/MANUAL.html#extension-example_lists) are currently not possible in pandoc, or am I missing something?

**Comment by vimuel** [comment]
@mb21 What I'm after is this:
```
1. foo
    1.1. bar
    1.2. quux
2. baz
```
I don't know of a way of doing this in CSS.

**Comment by mb21** [comment]
@vimuel MDN has a good write-up: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters#Nesting_counters

**Comment by vimuel** [comment]
@mb21 Nice one. Thanks for that.

**Comment by mengwong** [comment]
Not reopening this issue, just adding to the body of knowledge about this particular challenge: https://docs.google.com/document/d/e/2PACX-1vSX5opye0KWQ687nLhYKW1VTs2DljUUl5fra4kicNK7ygj-_Qyc3lhuEQh3g94Z4mM7EKQLPPpa3L3Q/pub
