### ISSUE TITLE
Hyperlinks to footnotes bring to first page

### ISSUE THREAD

**Issue by davtorgh** [jgm/pandoc#3361]
I'm using Pandoc 1.19.1 with MiKTeX-pdfTeX 2.9.6000 and default latex template. Hyperlinks to footnotes bring to first page of the document instead of to the real footnote. Is this a known issue @jgm?
I use pdfTeX directly to typeset other document and hyperlinks to footnotes work well.

Thanks.

**Comment by ickc** [comment]
I think you should give us a complete recipe for the problem. e.g. source code, pandoc command used, tex output (and point out what's wrong and what's expected).

Also, try to come up with a minimum working example. And if possible, produce the `.tex` without the `-s` option.

**Comment by jgm** [comment]
Yes, we can't proceed without an example.  I have not noticed this issue in the past.

**Comment by davtorgh** [comment]
Ok, here's what i discovered with pandoc markdown manual downloaded from http://pandoc.org/demo/MANUAL.txt

First run with xelatex
```sh
pandoc --latex-engine=xelatex manual.txt -o manual-xelatex.pdf
```
If you click on a hyperlinked note (see manual-xelatex.pdf in the attached zip file), nothing seems to happen.

---

Second run with pdftex, after removing some final text that contains annoying charachters for pdftex

```sh
pandoc manual.txt -o manual-pdftex.pdf
```
If you click on a hyperlinked note (see manual-pdftex.pdf in the attached zip file), you find yourself on the first page of the document in a 'full page view'.

---

Then I got the latex version of the document

```sh
pandoc -s manual.txt -o manual-pdftex.tex
```
and removed all the text to get a MWE for the footnotes (see pdftex-no.tex and pdftex-no.pdf in the attached zip file). I suppose the problem comes from the following latex code in the preamble

```latex
\usepackage{fancyvrb}
\VerbatimFootnotes % allows verbatim text in footnotes
```
that goes in conflicts with `hyperref`. After removing these lines of code from the preamble (see pdftex-ok.tex and pdftex-ok.pdf in the attached zip file) the hyperlinked footnotes work fine. @jgm and @ickc, what do you think about?

Thanks

[files.zip](https://github.com/jgm/pandoc/files/723296/files.zip)

**Comment by jgm** [comment]
Excellent diagnosis!

So we have a bit of a puzzle; we need `\VerbatimFootnotes`
if we're to have verbatim in footnotes, but breaking
note hyperlinks isn't a good consequence.

Perhaps poking around on the tex stack exchange (and asking
a question if needed) will reveal some solutions?

**Comment by ickc** [comment]
By simply changing the order between the loading of the 2 packages, we still have warnings but the hyperlink is there:

[pdftex-test.pdf](https://github.com/jgm/pandoc/files/724866/pdftex-test.pdf)

[pdftex-test.tex](https://github.com/jgm/pandoc/files/724871/pdftex-test.tex.txt)

Because

>The hyperref documentation says: "Make sure it comes last of your loaded packages". The reason is that it redefines many LaTeX commands. It's a rule of thumb that helps to avoid errors. From [Which packages should be loaded after hyperref instead of before? - TeX - LaTeX Stack Exchange](http://tex.stackexchange.com/questions/1863/which-packages-should-be-loaded-after-hyperref-instead-of-before)

**Comment by davtorgh** [comment]
By simply moving the following code
```latex
\usepackage{fancyvrb}
\VerbatimFootnotes
```
before hyperref my MWE gets compiled, but latex gives error when compiling, for example, the whole manual file. I think the correct sequence is:
```latex
\usepackage{fancyvrb}
\usepackage[unicode=true]{hyperref}
\hypersetup{
            pdftitle={Pandoc User's Guide},
            pdfauthor={John MacFarlane},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}
\VerbatimFootnotes
```
This works for pdftex and xelatex. I tested with the manual file, maybe some other test could be useful. @jgm, @ickc, if you confirm this is the solution, can you update default template in pandoc packages for the various platforms?

Thanks.

**Comment by ickc** [comment]
I'll test it tomorrow. Meanwhile, jgm/pandoc-templates#238 should be on hold.

**Comment by jgm** [comment]
Seems to work in my tests. I've updated the templates, thanks.
