### ISSUE TITLE
org reader: HTML blocks?

### ISSUE THREAD

**Issue by hrehfeld** [jgm/pandoc#3366]
Are `#+HTML: <test>` blocks supported at all? http://pandoc.org/try/?text=%23%2BHTML%3A+%3Ctest%3E&from=org&to=json

Instead of the Meta, they're supposed to be inserted into the output: http://orgmode.org/manual/Quoting-HTML-tags.html

**Comment by tarleb** [comment]
Fixed in master.  If you don't want to compile yourself, your can either use

    #+BEGIN_export HTML
    <test>
    #+END_export

or, if an raw inline is acceptable instead of a raw block:

    @@html:<test>@@

**Comment by hrehfeld** [comment]
Thanks!
