### ISSUE TITLE
[Possibly a feature request] When converting wikimedia files, the \href links do not go anywhere

### ISSUE THREAD

**Issue by federerfanatic** [jgm/pandoc#3367]
That is, to say we see stuff like \href{text}{Wikipedia_description_tag}, but text is just that text and not
a URL. See #3362 for the raw data examples. Perhaps I am missing an option that might do the trick.

**Comment by federerfanatic** [comment]
I would also note that there are a lot of empty footnotes, i.e., there are numbers on the bottom of the page but NO text following those numbers.

**Comment by mb21** [comment]
It's always good if you have a minimal example that reproduces the issue..

**Comment by federerfanatic** [comment]
See #3362  zip file.

**Comment by mb21** [comment]
yes, that's what I meant with minimal ;) can you post one line that shows unexpected behaviour? I had a quick look and most links seem to work..

**Comment by federerfanatic** [comment]
OK. Here is a smaller sample:

==Early life==
Brown left school at age 15 to work for a small insurance company, later returning to [[Stevenson College, Edinburgh|Stevenson College]] to get her Higher examinations through evening classes.<ref name="THE 27Sep2002">{{cite news |url=https://www.timeshighereducation.com/news/helping-others-to-cross-the-square/171870.article |title=Helping others to cross the square |work=[[Times Higher Education]] |date=27 September 2002 |accessdate=8 January 2017}}</ref> In 1983, at age of 37, she graduated from the University of Edinburgh with first-class honours in economics and politics.<ref>{{cite journal |url=http://www.the3rdimagazine.co.uk/2011/08/inspirational-women-alice-brown/ |title=We are the 51: Professor Alice Brown CBE |website=www.the3rdimagazine.co.uk |date=|accessdate=7 January 2017}}</ref>
 
The command line pandoc <file with above txt> -f mediawiki --standalone file.tex and then process with
xelatex 


\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\PassOptionsToPackage{hyphens}{url} % url is loaded by hyperref
\usepackage[unicode=true]{hyperref}
\hypersetup{
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\date{}

\begin{document}

\subsection{Early life}\label{early-life}

Brown left school at age 15 to work for a small insurance company, later
returning to \href{Stevenson_College,_Edinburgh}{Stevenson College} to
get her Higher examinations through evening classes.\footnote{} In 1983,
at age of 37, she graduated from the University of Edinburgh with
first-class honours in economics and politics.\footnote{}

\end{document}

**Comment by federerfanatic** [comment]
Note the \footnote{}{}

and the \href{Stevenson_College,_Edinburgh}{Stevenson College}

**Comment by mb21** [comment]
Okay, processing your snippet with `pandoc -f mediawiki -t latex` and pandoc 1.19.1 I get:

    Brown left school at age 15 to work for a small insurance company, later
    returning to \href{Stevenson_College,_Edinburgh}{Stevenson College} to
    get her Higher examinations through evening classes. In 1983, at age of
    37, she graduated from the University of Edinburgh with first-class
    honours in economics and politics.

- So the footnotes problems seems to be solved (are you using the newest pandoc version?)
- I can confirm the output of the links, but those are internal mediawiki links. What should pandoc do instead in your opinion?

**Comment by federerfanatic** [comment]
If you click on the links in the resulting PDF they work in the sense that
they are active but they don't go anywhere :-) Please post your PDF so I
can see
what you mean by "most links seem to work..."




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by federerfanatic** [comment]
I am currently do a rebuild of pandoc but I get a weird error from stack:

[11 of 93] Compiling Text.Pandoc.Slides ( src/Text/Pandoc/Slides.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Text/Pandoc/Slides.o )

/home/nafdef/software_engineering.d/downloads/github_sources.d/pandoc_johnmacfarlane.net.d/src/Text/Pandoc/Slides.hs:32:1:
error:
    Failed to load interface for ‘Text.Pandoc.Definition’
    There are files missing in the ‘pandoc-types-1.17.0.4’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
Progress: 1/2
--  While building package pandoc-1.19.1 using:

/home/nafdef/software_engineering.d/downloads/github_sources.d/pandoc_johnmacfarlane.net.d/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup/setup
--builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build lib:pandoc
exe:pandoc test:test-pandoc --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

**Comment by mb21** [comment]
You don't need to build from source to get the newest release... see http://pandoc.org/installing.html

Anyway, I see that `[[Stevenson College, Edinburgh|Stevenson College]]` is converted to `\href{Stevenson_College,_Edinburgh}{Stevenson College}` but AFAIK this is expected behavior, since this is an internal wiki links and pandoc has no way of knowing more about it. You can write a [pandoc filter](http://pandoc.org/scripting.html) to change them if you want to...

**Comment by federerfanatic** [comment]
I think the fact that it's empty link that goes no where is misleading
to the user of pandoc. Perhaps if it doesn't go anywhere it should be
highlighted in somekind of way at the minimum?

**Comment by mb21** [comment]
Not sure what you mean. Can you state exactly what output you would want from the following command:

    echo '[[Stevenson College, Edinburgh|Stevenson College]]' | pandoc -f mediawiki -t latex

**Comment by federerfanatic** [comment]
At the bare minimum? Hmm,

\textbf{Wikipedia: Steven College} or some kind of color perhaps?

FF




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by federerfanatic** [comment]
Also I have posted a thread:
https://groups.google.com/forum/#!topic/pandoc-discuss/zrqQaQacpCE .

FF




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by mb21** [comment]
I don't think inserting bold/red warnings in a document is the way to go. But a goal for pandoc 2.0 is improving the infrastructure for giving warnings and information so we can handle stuff like that better in the future.

**Comment by federerfanatic** [comment]
YES. Certainly better messaging would be nice including suggestions
and how to deal with them. -FF

**Comment by jgm** [comment]
The problem is that there's way pandoc will know it's a
broken link.  It's a relative URL, so whether it's broken
depends on where you're going to put the generated file,
and pandoc can't know that.

Pandoc certainly shouldn't print out anything about
Wikipedia, since mediawiki files are used elsewhere too.

+++ Federer Fanatic [Jan 26 17 06:04 ]:

**Comment by federerfanatic** [comment]
Also, perhaps offering a rich configuration file per user that would allow
the behaviour to change, not merely through a command line option, that
is:-)




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)
