### ISSUE TITLE
[feature request] Use paragraph attributes

### ISSUE THREAD

**Issue by xihh87** [jgm/pandoc#3370]
I love pandoc and I'm using it to generate epubs and would like to use class attributes for paragraphs.

**Comment by mb21** [comment]
Maybe this should be closed in favour of https://github.com/jgm/pandoc/issues/684 ?

**Comment by jgm** [comment]
You can always use divs enclosing the paragraphs, and put
class attributes on those.

+++ xihh87 [Jan 22 17 13:20 ]:

**Comment by jgm** [comment]
Closing in favor of #684
