### ISSUE TITLE
Bug: cannot build pandoc 1.19.1 with Haskell platform 8.0.2

### ISSUE THREAD

**Issue by stefanocoretta** [jgm/pandoc#3372]
Building using the `cabal` method does not work with Haskell Platform 8.0.2. The following traceback is produced. Building seem to work fine on HP 8.0.1

    Resolving dependencies...
    internal error: could not construct a valid install plan.
    The proposed (invalid) plan contained the following problems:
    Package directory is required by several packages, but they require
    inconsistent versions:
    package zip-archive-0.3.0.5 requires directory-1.2.7.1
    package yaml-0.8.21.1 requires directory-1.2.7.1
    package x509-system-1.6.4 requires directory-1.2.7.1
    package x509-store-1.6.2 requires directory-1.2.7.1
    package temporary-1.2.0.4 requires directory-1.2.7.1
    package streaming-commons-0.1.17 requires directory-1.2.7.1
    package pandoc-1.19.1 requires directory-1.2.7.1
    package pandoc-1.19.1 requires directory-1.2.7.1
    package filemanip-0.3.6.3 requires directory-1.2.7.1
    package process-1.4.3.0 requires directory-1.3.0.0
    
    Proposed plan:
    Configured JuicyPixels-3.2.8 (.fake.JuicyPixels-3.2.8)
    Configured SHA-1.6.4.2 (.fake.SHA-1.6.4.2)
    Configured aeson-1.0.2.1 (.fake.aeson-1.0.2.1)
    Configured asn1-encoding-0.9.4 (.fake.asn1-encoding-0.9.4)
    Configured asn1-parse-0.9.4 (.fake.asn1-parse-0.9.4)
    Configured asn1-types-0.3.2 (.fake.asn1-types-0.3.2)
    Configured conduit-1.2.8 (.fake.conduit-1.2.8)
    Configured connection-0.2.6 (.fake.connection-0.2.6)
    Configured cookie-0.4.2.1 (.fake.cookie-0.4.2.1)
    Configured cryptonite-0.21 (.fake.cryptonite-0.21)
    Configured data-default-0.7.1.1 (.fake.data-default-0.7.1.1)
    Configured data-default-instances-containers-0.0.1
    (.fake.data-default-instances-containers-0.0.1)
    Configured data-default-instances-dlist-0.0.1
    (.fake.data-default-instances-dlist-0.0.1)
    Configured data-default-instances-old-locale-0.0.1
    (.fake.data-default-instances-old-locale-0.0.1)
    Configured directory-1.2.7.1 (.fake.directory-1.2.7.1)
    Configured doctemplates-0.1.0.2 (.fake.doctemplates-0.1.0.2)
    Configured enclosed-exceptions-1.0.2 (.fake.enclosed-exceptions-1.0.2)
    Configured exceptions-0.8.3 (.fake.exceptions-0.8.3)
    Configured filemanip-0.3.6.3 (.fake.filemanip-0.3.6.3)
    Configured haddock-library-1.4.2 (.fake.haddock-library-1.4.2)
    Configured hourglass-0.2.10 (.fake.hourglass-0.2.10)
    Configured hslua-0.4.1 (.fake.hslua-0.4.1)
    Configured http-client-0.5.5 (.fake.http-client-0.5.5)
    Configured http-client-tls-0.3.3.1 (.fake.http-client-tls-0.3.3.1)
    Configured http-types-0.9.1 (.fake.http-types-0.9.1)
    Configured lifted-base-0.2.3.8 (.fake.lifted-base-0.2.3.8)
    Configured memory-0.14.1 (.fake.memory-0.14.1)
    Configured mime-types-0.1.0.7 (.fake.mime-types-0.1.0.7)
    Configured mmorph-1.0.9 (.fake.mmorph-1.0.9)
    Configured monad-control-1.0.1.0 (.fake.monad-control-1.0.1.0)
    Configured old-locale-1.0.0.7 (.fake.old-locale-1.0.0.7)
    Configured old-time-1.1.0.3 (.fake.old-time-1.1.0.3)
    Configured pandoc-1.19.1 (.fake.pandoc-1.19.1)
    Configured pandoc-types-1.17.0.5 (.fake.pandoc-types-1.17.0.5)
    Configured pem-0.2.2 (.fake.pem-0.2.2)
    Configured process-1.4.3.0 (.fake.process-1.4.3.0)
    Configured resourcet-1.1.9 (.fake.resourcet-1.1.9)
    Configured semigroups-0.18.2 (.fake.semigroups-0.18.2)
    Configured socks-0.5.5 (.fake.socks-0.5.5)
    Configured streaming-commons-0.1.17 (.fake.streaming-commons-0.1.17)
    Configured tagged-0.8.5 (.fake.tagged-0.8.5)
    Configured tagsoup-0.14 (.fake.tagsoup-0.14)
    Configured temporary-1.2.0.4 (.fake.temporary-1.2.0.4)
    Configured texmath-0.9 (.fake.texmath-0.9)
    Configured time-locale-compat-0.1.1.3 (.fake.time-locale-compat-0.1.1.3)
    Configured tls-1.3.9 (.fake.tls-1.3.9)
    Configured transformers-base-0.4.4 (.fake.transformers-base-0.4.4)
    Configured transformers-compat-0.5.1.4 (.fake.transformers-compat-0.5.1.4)
    Configured unix-compat-0.4.3.1 (.fake.unix-compat-0.4.3.1)
    Configured x509-1.6.5 (.fake.x509-1.6.5)
    Configured x509-store-1.6.2 (.fake.x509-store-1.6.2)
    Configured x509-system-1.6.4 (.fake.x509-system-1.6.4)
    Configured x509-validation-1.6.5 (.fake.x509-validation-1.6.5)
    Configured xml-1.3.14 (.fake.xml-1.3.14)
    Configured yaml-0.8.21.1 (.fake.yaml-0.8.21.1)
    Configured zip-archive-0.3.0.5 (.fake.zip-archive-0.3.0.5)
    PreExisting Cabal-1.24.2.0 (Cabal-1.24.2.0)
    PreExisting HTTP-4000.3.4 (HTTP-4000.3.4-KFReaUDBhDl5IdhBG0OByN)
    PreExisting QuickCheck-2.9.2 (QuickCheck-2.9.2-LUnRjwrWhwjHswl9yQmDJj)
    PreExisting array-0.5.1.1 (array-0.5.1.1)
    PreExisting async-2.1.1 (async-2.1.1-4n6HEMPJR2eJK0JpvCfuPK)
    PreExisting attoparsec-0.13.1.0 (attoparsec-0.13.1.0-3ZzSdwcr60OAwHW88oHBGG)
    PreExisting base-4.9.1.0 (base-4.9.1.0)
    PreExisting base-compat-0.9.1 (base-compat-0.9.1-B9geVZFtCvE8ERS7UcvkRz)
    PreExisting base64-bytestring-1.0.0.1
    (base64-bytestring-1.0.0.1-4O9TExPPz6eI82Yj7L4SIj)
    PreExisting binary-0.8.3.0 (binary-0.8.3.0)
    PreExisting blaze-builder-0.4.0.2
    (blaze-builder-0.4.0.2-CHCuxDJaC37LXaq0Zrx3Kf)
    PreExisting blaze-html-0.8.1.3 (blaze-html-0.8.1.3-9cPqTe36LFJL9M3HGA0Tk7)
    PreExisting blaze-markup-0.7.1.1 (blaze-markup-0.7.1.1-6MJYIi9D1MzAiyCkkp6TH3)
    PreExisting byteable-0.1.1 (byteable-0.1.1-2lU1pexQSLj1KbNO17UifQ)
    PreExisting bytestring-0.10.8.1 (bytestring-0.10.8.1)
    PreExisting case-insensitive-1.2.0.7
    (case-insensitive-1.2.0.7-4Oy3FIXmC4U6Y7ZlsLfFWn)
    PreExisting cereal-0.5.4.0 (cereal-0.5.4.0-5GV8T0cZtQC43fdhZURRFq)
    PreExisting cmark-0.5.4 (cmark-0.5.4-KGIi3HDrjP3LE8SBQT9WCL)
    PreExisting containers-0.5.7.1 (containers-0.5.7.1)
    PreExisting data-default-class-0.1.2.0
    (data-default-class-0.1.2.0-GsXqKN6o1X9jr0fF5qCVD)
    PreExisting deepseq-1.4.2.0 (deepseq-1.4.2.0)
    PreExisting digest-0.0.1.2 (digest-0.0.1.2-ExF2dwgnnwj5rxxaZYWSiQ)
    PreExisting directory-1.3.0.0 (directory-1.3.0.0)
    PreExisting dlist-0.8.0.2 (dlist-0.8.0.2-6Wnps4GD7EFnRucVzXIFD)
    PreExisting extensible-exceptions-0.1.1.4
    (extensible-exceptions-0.1.1.4-IyAM3ARTqH7BVZ5oHMMtXH)
    PreExisting filepath-1.4.1.1 (filepath-1.4.1.1)
    PreExisting ghc-boot-th-8.0.2 (ghc-boot-th-8.0.2)
    PreExisting ghc-prim-0.5.0.0 (ghc-prim-0.5.0.0)
    PreExisting hashable-1.2.5.0 (hashable-1.2.5.0-D2qhjboTBST6rFOSUg03ZP)
    PreExisting highlighting-kate-0.6.3
    (highlighting-kate-0.6.3-FZf23hM7z6F2Qwr3LM6EFQ)
    PreExisting integer-gmp-1.0.0.1 (integer-gmp-1.0.0.1)
    PreExisting integer-logarithms-1 (integer-logarithms-1-96xRAmHs4Fb6n66XL8dC1K)
    PreExisting mtl-2.2.1 (mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6)
    PreExisting network-2.6.3.1 (network-2.6.3.1-ABFtZSq90Z9BfMXNiqgBoe)
    PreExisting network-uri-2.6.1.0 (network-uri-2.6.1.0-L3Uif3PZTvwGEgoez4onJa)
    PreExisting parsec-3.1.11 (parsec-3.1.11-KfZohCLhCERHHaWU51ma7a)
    PreExisting pretty-1.1.3.3 (pretty-1.1.3.3)
    PreExisting primitive-0.6.1.0 (primitive-0.6.1.0-6AbSTw9JXz141LE5p6LGH)
    PreExisting process-1.4.3.0 (process-1.4.3.0)
    PreExisting random-1.1 (random-1.1-9tceXaeYIMZ4JrKq20Egog)
    PreExisting regex-base-0.93.2 (regex-base-0.93.2-3URDEr5Kbe07o8jW0I8mn7)
    PreExisting regex-pcre-builtin-0.94.4.8.8.35
    (regex-pcre-builtin-0.94.4.8.8.35-Jd8og6J4na1HxszezwiC5H)
    PreExisting rts-1.0 (rts)
    PreExisting scientific-0.3.4.10 (scientific-0.3.4.10-ICbf3tuDFCq7d8ztOzZX6R)
    PreExisting stm-2.4.4.1 (stm-2.4.4.1-JQn4hNPyYjP5m9AcbI88Ve)
    PreExisting syb-0.6 (syb-0.6-IcoSwlPi2Nx4zSqMmorFPS)
    PreExisting template-haskell-2.11.1.0 (template-haskell-2.11.1.0)
    PreExisting text-1.2.2.1 (text-1.2.2.1-FeA6fTH3E2n883cNXIS2Li)
    PreExisting tf-random-0.5 (tf-random-0.5-BGjMgO8m67W8CHiEl15kZ7)
    PreExisting time-1.6.0.1 (time-1.6.0.1)
    PreExisting transformers-0.5.2.0 (transformers-0.5.2.0)
    PreExisting unix-2.7.2.1 (unix-2.7.2.1)
    PreExisting unordered-containers-0.2.7.2
    (unordered-containers-0.2.7.2-ICgWIYrGL9xLm3Sokc47MY)
    PreExisting utf8-string-1.0.1.1 (utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5)
    PreExisting vector-0.11.0.0 (vector-0.11.0.0-HhutbadagxHIONIkSRJEug)
    PreExisting zlib-0.6.1.2 (zlib-0.6.1.2-BfeUVhBVvrx1Nvtzv6OD9c)
    
    CallStack (from HasCallStack):
    error, called at ./Distribution/Client/Dependency.hs:658:33 in
    main:Distribution.Client.Dependency

**Comment by jgm** [comment]
I'm confused, because neither pandoc 1.19.1 nor zip-archive
0.3.0.5 requires directory 1.2.x.  Both are compatible with
directory 1.3.x, as you can see by looking at Hackage.
Perhaps they depend on something that requires directory
< 1.3, but it's not immediately obvious to me what...


+++ Stefano Coretta [Jan 23 17 07:19 ]:
>   Building using the cabal method does not work with Haskell Platform
>   8.0.2. The following traceback is produced. Building seem to work fine
>   on HP 8.0.1
>Resolving dependencies...
>internal error: could not construct a valid install plan.
>The proposed (invalid) plan contained the following problems:
>Package directory is required by several packages, but they require
>inconsistent versions:
>package zip-archive-0.3.0.5 requires directory-1.2.7.1
>package yaml-0.8.21.1 requires directory-1.2.7.1
>package x509-system-1.6.4 requires directory-1.2.7.1
>package x509-store-1.6.2 requires directory-1.2.7.1
>package temporary-1.2.0.4 requires directory-1.2.7.1
>package streaming-commons-0.1.17 requires directory-1.2.7.1
>package pandoc-1.19.1 requires directory-1.2.7.1
>package pandoc-1.19.1 requires directory-1.2.7.1
>package filemanip-0.3.6.3 requires directory-1.2.7.1
>package process-1.4.3.0 requires directory-1.3.0.0

**Comment by mb21** [comment]
btw, maybe you have more luck with [stack](https://www.haskellstack.org)...

**Comment by federerfanatic** [comment]
And stack is opensource as @jpm pointed out to me, but it comes with a
convenient binary on Linux.
@federerfanatic




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by ickc** [comment]
If anything, it doesn't seem to be a problem of pandoc. See #3373. Are you sure it isn't just a "cabal dependency hell" instance (that interfere with whatever you already have)?

**Comment by ickc** [comment]
But since the Travis build work ok, it seems it is just some of cabal's problem. May be cleaning them up and install again?

**Comment by jgm** [comment]
Most likely just cabal hell.  You can remove your local package
database (~/.ghc - back it up) and do another cabal install,
and it should work.

+++ Stefano Coretta [Jan 24 17 00:10 ]:
