### ISSUE TITLE
Pandoc doesn't covert markdown to RST properly.

### ISSUE THREAD

**Issue by xoviat** [jgm/pandoc#3375]
Here is a snippet of the input:

```
# subzero
[![build status][2]][3]
[![Codecov][5]][4]
## What is Subzero?
```

And here is a snippet of the output:

```
        subzero
        =======
        
        |build status| |Codecov| ## What is Subzero?
```

The markdown subtitle should be converted to an RST subtitle but is not.

**Comment by mb21** [comment]
Pandoc markdown requires an empty line above the subheading:

    # subzero
    [![build status][2]][3]
    [![Codecov][5]][4]

    ## What is Subzero?

**Comment by xoviat** [comment]
Why is this not an issue?

**Comment by mb21** [comment]
See http://pandoc.org/MANUAL.html#extension-blank_before_header

try `pandoc -f markdown-blank_before_header -t rst`
