### ISSUE TITLE
Running pandoc.exe without options makes it appear to not-run.

### ISSUE THREAD

**Issue by sunk818** [jgm/pandoc#3376]
If I use `pandoc.exe --help`, I get a list of options and am returned to the command line. If I run pandoc.exe by itself, I am not returned to the command prompt. This behavior is like `cat` command and as a new user to pandoc.exe was very confusing to me. I thought the anti-virus found it to be malware or the .MSI I got the file from was not actually an executable binary.

**Comment by mb21** [comment]
> This behavior is like cat command 

exactly. it's waiting for input from stdin, this is expected behavior.
