### ISSUE TITLE
[Feature Request] Be able to insert an extra class attribute in <span class="math inline">\latex code</span>

### ISSUE THREAD

**Issue by federerfanatic** [jgm/pandoc#3381]
I asked a question on the email list of luatex:

=================================== mail to luatex list ================
Basically have complete mathml markup or some other kind of html math output
that is completely capable of doing what is now done for pdf output.

This would elminate the need for the clumsy workarounds that mathjax,
for example, provides---there appears to be no easy way to convert
arbitarilly/personally written latex packages/classes
into something that mathjax can understand. Obviously the original
latex code could still remain
in the resulting html/mathhtml output so that people would still have
access to the "original" source code.

One of my motivations is to allow for google translate to work on html
math documents...
it WORKS provided you add 'notranslate' to the spans:  <span
class="math inline">, <class="math display">latex math commands/span>
etc environments. However LaTeX commands that mathjax is not familiar
with are not rendered....

I realize this may be a better question on mathjax but I regard that
project, while laudable, wrong headed as the real problem should be
solved by a proper TeX engine such as luatex?

---------------------- end of my email to the luatex dev list -------------------------------------

I succeeded in getting this to work with --mathjax option of pandoc to get a nicely rendered
document in html/mathjax, however as noted above when one does this with, say, a french
latex file with the goal to translate this into english while preserving the latex. So
I experimented by doing:

   latex file --> convert to html/js/mathjax using pandoc---> insert into google translate, which
works as I noted above in my email above PROVIDED one can insert the notranslate  tag...

The obviously the next step is to convert the html/js/mathjax file back into latex.....I HAVE NOT
done this....as yet.

I think I have to look into [http://pandoc.org/scripting.html](url) ? Thoughts @jgm ?

**Comment by mb21** [comment]
pandoc spans support class attributes...?

This seems to be a better fit for the pandoc-discuss mailing list...

**Comment by federerfanatic** [comment]
I will consider posting it a day or two...

**Comment by mb21** [comment]
Closing this then...
