### ISSUE TITLE
Unable to read from stdin or URI for binary formats

### ISSUE THREAD

**Issue by dansisan** [jgm/pandoc#3383]
The documentation says an output file must be specified for binary file formats, but not for input, which implies this should be possible.  

I get the following error: 

```
>cat test-article.docx | pandoc -f docx -t odt -o test.odt
pandoc: Cannot read archive from stdin
CallStack (from HasCallStack):
  error, called at pandoc.hs:1385:22 in main:Main
```

which implies it thinks it's getting a zip archive.

When using `-` to signal stdin (which works for non-binary files) I get a different error, indicating it's trying to read from a file:

```
>cat test-article.docx | pandoc - -f docx -t odt -o test.odt
pandoc: -: openBinaryFile: does not exist (No such file or directory)
```
I get this same error if the input is a URI as well, but again only for binary sources.

I'm calling pandoc from another program, where I have an InputStream so it would preferable to not have to write to the file system first.

If reading binary file formats from stdin or URI is not possible, I would suggest making it clearer in the error and modifying the documentation.

**Comment by jgm** [comment]
+++ Dan Sisan [Jan 26 17 08:33 ]:
>   The documentation says an output file must be specified for binary file
>   formats, but not for input, which implies this should be possible.
>
>   I get the following error:
>>cat test-article.docx | pandoc -f docx -t odt -o test.odt
>pandoc: Cannot read archive from stdin
>CallStack (from HasCallStack):
>  error, called at pandoc.hs:1385:22 in main:Main
>
>   which implies it thinks it's getting a zip archive.

In fact, it is:  a docx is just a zip archive (you can test
this by using 'unzip' on it!).

But there's no reason why we can't read a zip from stdin.
And in fact, this is already fixed in the 'typeclass' branch
of pandoc (which will become pandoc 2.0 when it is
released).

>   When using - to signal stdin (which works for non-binary files) I get a
>   different error, indicating it's trying to read from a file:
>>cat test-article.docx | pandoc - -f docx -t odt -o test.odt
>pandoc: -: openBinaryFile: does not exist (No such file or directory)
>
>   I get this same error if the input is a URI as well, but again only for
>   binary sources.

This is also fixed in the typeclass branch.

**Comment by dansisan** [comment]
Thanks for the update (and for pointing out that .docx is in fact an archive).  Do you know when pandoc 2.0 is coming out?

**Comment by jgm** [comment]
I don't know exactly, but I plan to merge that branch soon into master.
I'll close this issue since it's fixed in development code.
