### ISSUE TITLE
raw_tex not processed from Github Markdown to ConTeXt

### ISSUE THREAD

**Issue by alnjxn** [jgm/pandoc#3385]
Edit: This only effects `markdown_github`

- the pandoc version (check using pandoc -v)
  - `pandoc 1.19.1`
  - `Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3`
- the exact command line used
  - `pandoc -f markdown_github -t context --template templates/context.tex -o output.pdf sec02_mechanical.md`
  - OR
  - `pandoc -f markdown_github -t context+raw_tex --template templates/context.tex -o output.pdf sec02_mechanical.md`
- the exact input used
```
\placetable[none]{}
\starttable[|l|c|]
\HL
\NC Space
\NC Noise Criteria
\NC\AR
\HL
\NC Private Office
\NC NC35
\NC\AR
\NC Meeting Room
\NC NC35
\NC\AR
\NC Wellness Room
\NC NC35
\NC\AR
\NC Shared Office and Hot Desks
\NC NC40
\NC\AR
\NC Amenity Area
\NC NC40
\NC\AR
\NC Circulation
\NC NC40
\NC\AR
\HL
\stoptable
```
- the output received
```
\placetable[none]{}
\starttable[|l|c|]
\HL
\NC Space
\NC Noise Criteria
\NC\AR
\HL
\NC Private Office
\NC NC35
\NC\AR
\NC Meeting Room
\NC NC35
\NC\AR
\NC Wellness Room
\NC NC35
\NC\AR
\NC Shared Office and Hot Desks
\NC NC40
\NC\AR
\NC Amenity Area
\NC NC40
\NC\AR
\NC Circulation
\NC NC40
\NC\AR
\HL
\stoptable
```
- the output you expected instead
![screen shot 2017-01-26 at 12 47 05 pm](https://cloud.githubusercontent.com/assets/1423708/22343292/923877fe-e3c5-11e6-8e63-e988b8c848a8.png)

==================

Is there some escape sequence to enable the processing of `raw_tex`? The plugin is enabled as `--list-extensions` shows `raw_tex +`. i have also tried explicitly with `-t context+raw_tex`

Thanks!

Alan

Edit:

The raw Tex output from debug looks like this: 

```
\letterbackslash{}placetable{[}none{]}\{\}\crlf
\letterbackslash{}starttable{[}\letterbar{}l\letterbar{}c\letterbar{}{]}\crlf
\letterbackslash{}HL\crlf
\letterbackslash{}NC Space\crlf
\letterbackslash{}NC Noise Criteria\crlf
\letterbackslash{}NC\letterbackslash{}AR\crlf
\letterbackslash{}HL\crlf
\letterbackslash{}NC Private Office\crlf
\letterbackslash{}NC NC35\crlf
\letterbackslash{}NC\letterbackslash{}AR\crlf
\letterbackslash{}NC Meeting Room\crlf
\letterbackslash{}NC NC35\crlf
\letterbackslash{}NC\letterbackslash{}AR\crlf
\letterbackslash{}NC Wellness Room\crlf
\letterbackslash{}NC NC35\crlf
\letterbackslash{}NC\letterbackslash{}AR\crlf
\letterbackslash{}NC Shared Office and Hot Desks\crlf
\letterbackslash{}NC NC40\crlf
\letterbackslash{}NC\letterbackslash{}AR\crlf
\letterbackslash{}NC Amenity Area\crlf
\letterbackslash{}NC NC40\crlf
\letterbackslash{}NC\letterbackslash{}AR\crlf
\letterbackslash{}NC Circulation\crlf
\letterbackslash{}NC NC40\crlf
\letterbackslash{}NC\letterbackslash{}AR\crlf
\letterbackslash{}HL\crlf
\letterbackslash{}stoptable
```

**Comment by mb21** [comment]
`markdown_github` is defined by pandoc to [not contain](http://pandoc.org/MANUAL.html#markdown-variants) `raw_tex`.

Try `pandoc -f markdown_github+raw_tex`
