### ISSUE TITLE
Remove HTML table widths

### ISSUE THREAD

**Issue by SystemParadox** [jgm/pandoc#3386]
Having recently upgrading from pandoc 1.12.2.1 to 1.16.0.2, I have discovered that pandoc now tries to make pipe tables look more like the markdown source by specifying table/column widths (#2486, #2574).

While I understand this may be desirable for keeping consistency between formats, we are only using pandoc for markdown to HTML, and we specifically want to leave the browser to size the table according to content like you would expect for HTML.

Please, please can we have a way to turn this feature off? It's really messed up our HTML output.

I tried `--columns=10000` but that does not seem to make any difference, and from what I can gather this only affects the overall table width anyway, so it won't help with the column sizes.

I saw that this has been requested before (https://groups.google.com/forum/#!topic/pandoc-discuss/3iCC5UkoXdg) but it seems there is still not an option to disable it.

I fear we are going to have to find an alternative to pandoc if this is not going to be fixed.

**Comment by jgm** [comment]
The widths are only triggered when your pipe table lines overflow the column width (as set by `--columns`).

So an easy solution, if you have pipe tables with long lines and don't want explicit column widths, is to set `--columns` to a very high number.  Of course, you'll have very bad results with latex/pdf output, but if you're only targeting HTML this should be fine.

You claim you tried this and it didn't work.  It works for me. Please give an example we can test with, with the exact command you used.

**Comment by mb21** [comment]
also note that we're on [pandoc 1.19.1](https://github.com/jgm/pandoc/releases) now...

**Comment by SystemParadox** [comment]
Thanks for the reply. I've found the problem - we're actually calling pandoc twice, piping the json output through a graphviz filter. The `--columns` option needs to go on the input stage like this:

```
pandoc -t json --columns=10000 | ./graphviz.py html | pandoc -f json -s --number-sections --toc --toc-depth=4 --section-divs --self-contained -T
```

Contrary to my original understanding, this has removed all the widths so that does indeed fix it.

Thanks.
