### ISSUE TITLE
Implement GFM Anchors ID Scheme for `markdown_github`

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#3388]
I've noticed that pandoc uses a different anchor IDs scheme from that employed by GitHub, even when `markdown_github` extension is specified.

This breaks internal documents links, and cross-document links in html converted documents.

A notable difference is that pandoc strips from the generated anchor ID all non-letter chars up to the first letter in the header. Therefore, in documents with manually numbered sections pandoc will produce anchors with the numbers stripped away, while on GitHub markdown preview the anchors retain the numbers.

GitHub Flavored Markdown is extensively used for quick navigation of the repository through links found in README files. It would therefore be nice to retain a consistent anchor naming scheme for GFM docs, in order to benefit from both GitHub preview navigation as well as working links in html converted documents.

I propose adding an optional extension that handles anchors naming the GitHub way, and to make it default for `markdown_github` specification. I think it wouldn't be incorrect to state that GFM syntax and usage is strictly connected to GitHub behavior.

**Comment by mb21** [comment]
Thanks, I think this is the same as issue https://github.com/jgm/pandoc/issues/2821
