### ISSUE TITLE
Handle w:instrTex for DOCX to HTML conversion

### ISSUE THREAD

**Issue by trapias** [jgm/pandoc#3389]
Hello,
it looks like there's a problem with hyperlinks, when converting from .DOCX to HTML as described in [this discussion on Google groups](https://groups.google.com/forum/#!topic/pandoc-discuss/gbQhIpmzXSE):

 -  if hyperlinks are handled with <w:hyperlink> then Pandoc does recognize them and correctly convert into an "a href" tag, but 
- if hyperlinks are referenced with <w:instrText> it does not, hyperlinks are missing from the resulting HTML.  

I do not know what is the reason that causes DOCX documents to be written with the one or the other tag, but as John suggests in his answer it looks like Pandoc does not recognize the latter format.

**Comment by jgm** [comment]
It looks like the form is just

    <w:instrText>HYPERLINK "http://example.com"</w:instrText>

So this should be simple to support.

**Comment by jgm** [comment]
It's actually more complex than I thought.  This whole contraption has to occur in a structure like this:
```
<w:r>
<w:fldChar w:fldCharType="begin"/>
</w:r>
<w:r>
<w:instrText xml:space="preserve"> DATE </w:instrText>
</w:r>
<w:r>
<w:fldChar w:fldCharType="separate"/>
</w:r>
<w:r>
<w:t>12/31/2005</w:t>
</w:r>
<w:r>
<w:fldChar w:fldCharType="end"/>
</w:r>
```
See http://officeopenxml.com/WPfields.php
Field types are documented here: http://officeopenxml.com/WPfieldInstructions.php

**Comment by jkr** [comment]
@jgm and @trapias -- just wanted to let you know that, a year later, I finally addressed this. Definitely not a good first issue -- accumulating runs in state, introducing a new module with its own little parsec parser. But there's now a framework for handing further fldChar/instrText directives in docx documents.

**Comment by trapias** [comment]
@jkr great, thank you! Will make a test ASAP 👊

**Comment by jkr** [comment]
Great -- if you do create a test document, can you post it? I'd prefer to replace the one that's up there now, but recent versions of Word don't seem to be able to produce links as fields.

**Comment by trapias** [comment]
@jkr for sure - cannot assure I can before 10/15 days, but finally will revert to you!
