### ISSUE TITLE
All newlines in code blocks seem to be prefixed with ~11 spaces

### ISSUE THREAD

**Issue by schell** [jgm/pandoc#3391]
I'm going from markdown and literate haskell to html and it seems that all my code blocks end up misaligned due to some extra indentation. For example the following markdown

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{.haskell}
runFreeType :: IO FT_Error -> IO ()
runFreeType m = do
    r <- m
    unless (r == 0) $ fail $ "FreeType Error:" ++ show r
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

produces this output

```html
<div class="sourceCode"><pre class="sourceCode haskell"><code class="sourceCode haskell"><span class="ot">runFreeType ::</span> <span class="dt">IO</span> <span class="dt">FT_Error</span> <span class="ot">-&gt;</span> <span class="dt">IO</span> ()
            runFreeType m <span class="fu">=</span> <span class="kw">do</span>
                r <span class="ot">&lt;-</span> m
                unless (r <span class="fu">==</span> <span class="dv">0</span>) <span class="fu">$</span> fail <span class="fu">$</span> <span class="st">"FreeType Error:"</span> <span class="fu">++</span> show r</code></pre></div>
```

which ends up looking like 
<img width="665" alt="screenshot 2017-01-28 11 56 07" src="https://cloud.githubusercontent.com/assets/24942/22399414/dd4adf34-e550-11e6-8048-3ff5f592bab6.png">

I think the issue is in the writer, as when I inspect the read block, I see 

```haskell
CodeBlock ("",["haskell"],[]) "runFreeType :: IO FT_Error -> IO ()\nrunFreeType m = do\n    r <- m\n    unless (r == 0) $ fail $ \"FreeType Error:\" ++ show r"
``` 

I'm writing the document using

```haskell
\pandoc ->
let opts  = def{ writerExtensions = allMyPandocExtensions <> pandocExtensions
                   , writerHighlight = True
                   , writerHtml5 = True
                  -- , writerHighlightStyle = zenburn
                   , writerStandalone = False
                   }
in writeHtmlString opts pandoc
```

where

```haskell
allMyPandocExtensions :: S.Set Extension
allMyPandocExtensions = S.fromList [ Ext_link_attributes
                                   , Ext_mmd_link_attributes
                                   , Ext_literate_haskell
                                   ]
```

**Comment by schell** [comment]
Actually it looks like the output of `writeHtmlString` is fine, it produces the newlines that are expected. I've tracked the problem further down my pipeline, where I take that string and use it as the `body` variable in a template that is being compiled with `renderTemplate`.

**Comment by jgm** [comment]
I can't reproduce this. Can you send output of `pandoc
--version`, plus information about how you installed pandoc
(from source, from a binary package, etc.)?

And, can you reproduce this with command line pandoc, or
only with the Haskell program?  If you can reproduce it
with the pandoc command, please send the exact command used.

**Comment by jgm** [comment]
+++ Schell Carl Scivally [Jan 28 17 12:32 ]:
>   Actually it looks like the output of writeHtmlString is fine, it
>   produces the newlines that are expected. I've tracked the problem
>   further down my pipeline, where I take that string and use it as the
>   body variable in a template that is being compiled with renderTemplate.

Ah, okay.  Well, then, the issue is that the template
rendering respects indentation.  Put the variable for the
code flush with the left margin.

**Comment by schell** [comment]
Wow! Magic! Thank you, I didn't think about that.
