### ISSUE TITLE
Markdown to EPUB: YAML block title types are disregarded

### ISSUE THREAD

**Issue by jroedel** [jgm/pandoc#3393]
I have a markdown file with the following YAML front matter block (as suggested in the User's guide):
```
title:
- type: main
  text: Main title
- type: subtitle
  text: Subtitle
creator:
- role: author
  text: Author 1
- role: translator
  text: Author 2
lang: en-US
```
I run the command `pandoc -o doc.epub doc.md`.
When I examine the content.opf file in the resulting ePub, it shows the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<package version="2.0" xmlns="http://www.idpf.org/2007/opf" unique-identifier="epub-id-1">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:identifier id="epub-id-1">urn:uuid:xxxxxxxxxxxxx</dc:identifier>
    <dc:title id="epub-title-1">Main title</dc:title>
    <dc:title id="epub-title-2">Subtitle</dc:title>
    <dc:date id="epub-date-1">2017-01-29T12:49:03Z</dc:date>
    <dc:language>en-US</dc:language>
    <dc:creator id="epub-creator-1" opf:role="aut">Author 1</dc:creator>
    <dc:creator id="epub-creator-2" opf:role="trl">Author 2</dc:creator>
  </metadata>
   ...
</package>
```
The "main" and "subtitle" types have been stripped which means I can't use the file with kindlegen:
`Error(opfparser):E20006: There are more than one title defined in OPF metadata. But none of them is refined with "title-type" as "main" title. Refer http://idpf.org/epub/30/spec/epub30-publications.html#sec-opf-dctitle for more info.`

It would complicate matters in my case to use a separate metadata.opf, because I will be programmatically creating many ePubs. 

I think the YAML title-types should be respected.

**Comment by mb21** [comment]
What you're expecting is the following?

    <dc:title id="epub-title-1">Main title</dc:title>
    <dc:title id="epub-title-2">Subtitle</dc:title>
    <meta refines="#epub-title-1" property="title-type">main</meta>

**Comment by jgm** [comment]
Use -t epub3

According to comments in our source, epub2 doesn't accept
the type refinement on title, so we don't use it there.
But we do if you're producing epub3.  This is what I get
with `-t epub3`:

    <dc:title id="epub-title-1">Main title</dc:title>
    <meta refines="#epub-title-1" property="title-type">main</meta>
    <dc:title id="epub-title-2">Subtitle</dc:title>
    <meta refines="#epub-title-2" property="title-type">subtitle</meta>

**Comment by jroedel** [comment]
That works perfect with kindle gen. Thanks!

If anyone finds their way to this post here's the resulting commands working with kindlegen:
```shell
pandoc --smart --atx-headers --toc --toc-depth=2 --epub-cover-image=cover.png -o dest.epub source.md
kindlegen dest.epub
```
