### ISSUE TITLE
Extended lua support

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#3395]
Pandoc contains a full lua interpreter, which is currently used for custom writers only.  It would be nice to extend pandoc's lua support, enabling lua filters and possibly custom readers.

This issue is intended as a discussion place for basic ideas.

The simplest way to allow lua filters would be to implement a `StackValue` instance for aeson's `Value` type. Lua is very similar to javascript, making json-like objects a good choice for document elements. As an added benefit, any lua library that is built to work with this data, could also be used in a standalone filter.  Lua filters could easily be backported to older pandoc versions.

The only(?) downside of this approach is that it won't be as performant as possible alternatives.

I'd love to see this included in v2.0, but didn't find the time yet to implement it. (I wrote an incomplete [prototype](https://github.com/tarleb/panluna) which I now find to be over-engineered and difficult to debug, putting me back to square one.) 

Exposing reader and writer functions as well as their options to lua would be the second step.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Jan 29 17 14:14 ]:
>   The simplest way to allow lua filters would be to implement a
>   StackValue instance for aeson's Value type.

This sounds like a good approach to me.  Indeed, the
instance could be a standalone package, since it would be
useful outside of pandoc too.

**Comment by tarleb** [comment]
Step 1 (creating `StackValue` instances for Aeson.Value) is mostly done: [hslua-aeson](https://github.com/tarleb/hslua-aeson).  Still requires some minor improvements and proper documentation.

**Comment by jgm** [comment]
Terrific!

+++ Albert Krewinkel [Feb 02 17 15:05 ]:
>   Step 1 (creating StackValue instances for Aeson.Value) is mostly done:
>   [1]hslua-aeson. Still requires some minor improvements and proper
>   documentation.

**Comment by tarleb** [comment]
I created a [branch](https://github.com/tarleb/pandoc/tree/lua-filters) to get started and could use some help with the API: The current implementation adds a new `--lua-filter` command line option; the scripts given with that option are run before JSON filters. Scripts are expected to provide any of `filter_doc`, `filter_block`, or `filter_inline`, taking a single element as argument.  The following for example will append a paragraph containing the filter arguments as a final paragraph, expand the special string `{{helloworld}}`, and turn all `Plain`s into `Para`s. 

``` lua
function filter_doc(doc)
  local args = PandocParameters
  local inlines = {{t = "Str", c = "Params:"}, {t = "Space"}}
  for i = 1, #args do
    inlines[#inlines + 1] = {t = "Str", c = args[i]}
    inlines[#inlines + 1] = {t = "Space", c = args[i]}
  end
  inlines[#inlines] = nil  -- drop final space
  doc.blocks[#doc.blocks + 1] = {t = "Para", c = inlines}
  return doc
end

function filter_block(block)
  if block.t == "Plain" then
    block.t = "Para"
  end
  return block
end

function filter_inline(inline)
  if inline.t == "Str" and inline.c == "{{helloworld}}" then
    return {t = "Emph", c = {{t = "Str", c="Hello, World"}}}
  end
  return inline
end
```

There is a lot to improve.  Asymptotic runtime is proportional to both the depth and length of the document (due to repeated lua stack pushing and popping), leading to a slow-down of about an order of magnitude.  I'm not entirely sure yet how to solve this without reimplementing `walkM` specifically for Lua.

Nicer element creation/manipulation is another problem, for which I'm currently working towards a general solution.

**Comment by tarleb** [comment]
A possible solution to the problems mentioned above would be to keep as much code as possible in haskell.  I'm imagining an interface like this:

```lua
local expandHelloWorld = InlineFilter{
  Str = function(el) return expandHelloWorldString(el) end
}

local plainToPara = BlockFilter{
  Plain = function(el) return Para(el.content) end
}

return {expandHelloWorld, plainToPara}
```

This will probably require a new release of hslua, as some required functionalities are not supported yet.

**Comment by tarleb** [comment]
The following script

```lua
function InlineFilter(x) return setmetatable(x, {"Inline"}) end
function BlockFilter(x) return setmetatable(x, {"Block"}) end

function filter_inline(inline)
  if inline.c == "{{helloworld}}" then
    return {t = "Emph", c = {{t = "Str", c="Hello, World"}}}
  else
    return inline
  end
end

return {
  InlineFilter{Str = filter_inline},
  BlockFilter{Plain = function(blk) blk.t = "Para"; return blk end}
 }
```

now turn this

    [BulletList
     [[Plain [Str "Alfa"]]
     ,[Plain [Str "Bravo"]]]
    ,Para [Str "{{helloworld}}"]]

into this

    [BulletList
     [[Para [Str "Alfa"]]
     ,[Para [Str "Bravo"]]]
    ,Para [Emph [Str "Hello, World"]]]

Performance is much better now: filtering is basically free when done on rare elements, and tolerable otherwise.  The implementation a tad hacky and could be improved slightly by extending hslua.

**Comment by jgm** [comment]
Looks nice.  Questions:

These lines look like boilerplate that will be in every
filter:

>function InlineFilter(x) return setmetatable(x, {"Inline"}) end
>function BlockFilter(x) return setmetatable(x, {"Block"}) end

How about having pandoc add them automatically to the lua
script, or make available a module that can be imported to do this?

>function filter_inline(inline)
>  if inline.c == "{{helloworld}}" then
>    return {t = "Emph", c = {{t = "Str", c="Hello, World"}}}

How about having pandoc make available some lua functions so you
can do

     return Emph{Str("Hello, world")}

instead?

Indeed, it would be cool if the following could be a
complete lua filter, with no boilerplate at all:

    function filter_Str(str)
      if str.c == "{{helloworlhd}}" then
        return Emph{Str("hello, world")}
      else
        str
      end
    end

The lua code added by pandoc could look over
functions with names like filter_* and automatically
set the metatable accordingly.

**Comment by jgm** [comment]
Or maybe something like this?
``` lua
return to_filter{
  Str = function(s) if s.c == "{{helloworld}}" then return Emph(Str("hello world")) end
}
```
`to_filter` here takes a table as argument.  The keys of the table are the different kinds of inline and block elements.  Pandoc can figure out which of these are transformations on blocks and which on inlines, since that is determinable from the key.

It would also be nice to provide a function to pipe two filters together:
``` lua
return to_filter(first_filter_table) + to_filter(second_filter_table)
```
Here `+` is overloaded in the metatable to function composition.

**Comment by daurnimator** [comment]
how does this compare to [lunamark](https://github.com/jgm/lunamark)? Can we keep interfaces the same/similar across the projects?

**Comment by jgm** [comment]
Lunamark is a Markdown parser.  This is something completely
different, a way to manipulate the syntax tree parsed by
pandoc.

**Comment by jgm** [comment]
I'm excited about this.  How is work going?  Are my API suggestions above feasible?

**Comment by tarleb** [comment]
Thank you for the suggestions, I will try to implement them.  Sorry for not getting back earlier.
I'm currently finishing up a second draft of the paper which I mentioned on *discuss* some time ago.  I'm trying to avoid multitasking and plan to return to working on the lua filteres again by the end of this week.

**Comment by tarleb** [comment]
See also osa1/hslua#46.  Ideally I'd get that done first, as that should reduce the amount of glue code considerably.

**Comment by tarleb** [comment]
Recent progress: We now expect scripts to return a list of filters, where a filter is any table containing functions with the name of inline or block elements.  Furthermore, a very rudimentary `pandoc` module is provided, it currently only allow to create a filter table from the global environment via `global_filter()`.  The function was added so that filters can be written in the same style as custom writers.

The above script can now be written like this:

```lua
function Str(inline)
  if inline.c == "{{helloworld}}" then
    return {t = "Emph", c = {{t = "Str", c="Hello, World"}}}
  else
    return inline
  end
end

function Plain(block)
  block.t = "Para"
  return block
end

return {pandoc.global_filter()}
```


Tasks left include:

- [ ] Extend the pandoc module to provide element-creating functions.
- [ ] Evaluate element content lazily to improve performance.
- [ ] Cleanup code.

Anything else that I should include before opening a pull request?

**Comment by tarleb** [comment]
I chose the simple "list of tables" approach for filter representation as it seems quite user friendly to me.  The `filter{Str = …}` approach is much nicer for typing and future extensibility. It could be implemented on top of the current solution.

**Comment by jgm** [comment]
I don't grasp all the details, but the above sample script looks very clean to me.

I'm not sure how the `global_filter()` function works; I suppose it creates a table with all the globally defined functions?  That should be okay, I guess, as long as dependencies are imported as locals.  Still, it might be nice to provide also the alternative of returning a table explicitly, `return filter{Str = _}`.

Is the pandoc module implemented as a data file?  We should make it possible for people to test their lua modules using regular lua tools, so it should be possible to open a lua repl with the pandoc module in scope.

**Comment by tarleb** [comment]
John MacFarlane <notifications@github.com> writes:

> I'm not sure how the global_filter() function works; I suppose it creates a
> table with all the globally defined functions?

Yes, that's pretty much what's happening. It collects all globals with
names that correspond to pandoc elements:

    function global_filter()
      local res = {}
      for k, v in pairs(_G) do
        if inlines[k] or blocks[k] then
          res[k] = v
        end
      end
      return res
    end

> That should be okay, I guess, as
> long as dependencies are imported as locals. Still, it might be nice to provide
> also the alternative of returning a table explicitly, return filter{Str = _}.

The last line of the example script could also be written as

    return {
      { Str = Str, Plain = Plain }
    }

Is that what you have in mind?

> Is the pandoc module implemented as a data file? We should make it possible for
> people to test their lua modules using regular lua tools, so it should be
> possible to open a lua repl with the pandoc module in scope.

The module is currently hard coded, but only because I wasn't sure how
pandoc handles data files. Figuring that out is part of my "Code
cleanup" task.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Mar 11 17 14:09 ]:
>   The last line of the example script could also be written as
>   return {
>   { Str = Str, Plain = Plain }
>   }
>   Is that what you have in mind?

Yes, precisely. Good.

>   The module is currently hard coded, but only because I wasn't sure how
>   pandoc handles data files. Figuring that out is part of my "Code
>   cleanup" task.

Let me know if you have any questions about this. There's a
function readDefaultDataFile in shared.  To add a data file
to pandoc, you just put it in data/ and add it to the
data-files section of pandoc.cabal.
