### ISSUE TITLE
Option --id-prefix does not update references within the document

### ISSUE THREAD

**Issue by aahlborg** [jgm/pandoc#3397]
I found --id-prefix to be a nice solution to my problem with composing a book of multiple markdown documents but I have the same problem as this guy with references not being updated to point to the new IDs:
https://groups.google.com/forum/#!topic/pandoc-discuss/SQ0_mE2TUvM

In short
```
$ cat test.md
# Markdown Test #

## Introduction ##

This is the intro. See the [Introduction].
```
yields this output
```
$ pandoc --id-prefix=ss- -t docbook  test.md
<sect1 id="ss-markdown-test">
  <title>Markdown Test</title>
  <sect2 id="ss-introduction">
    <title>Introduction</title>
    <para>
      This is the intro. See the
      <link linkend="introduction">Introduction</link>.
    </para>
  </sect2>
</sect1>
```
where the link to Introduction is broken.

Shouldn't --id-prefix append the prefix also to references within the document?

**Comment by jgm** [comment]
The problem is that currently id-prefix affects the
writers, while the implicit link resolution is done
in the readers.

It would make sense, I think, to change things so that
id-prefix has its effect in the readers.  The problem
is that some of the things it affects (footnote identifiers)
are only accessible in the writers.

This needs more thought, but thanks for raising the issue.

**Comment by mb21** [comment]
Ultimately, this probably shouldn't be specific to any readers or writers but act on the AST between them, like a filter.

But for now, as long as all the ids/links in the AST are consistent, the HTML/DocBook writers can simply prefix them. But they should prefix not only the ids but also the internal links, which is exactly what my patch fixes.

**Comment by aahlborg** [comment]
@mb21's patch seems to fix my use case (I haven't been able to verify), but as you say it might need to be rewritten in the future.
