### ISSUE TITLE
org-mode MACRO not expanded

### ISSUE THREAD

**Issue by b3** [jgm/pandoc#3401]
When converting from an `org-mode` file org macros are not expanded (in fact there are not dealt at all).

For instance the following `org-mode` file:

```Org
#+MACRO: foo bar
should be foobar but is foo{{{foo}}}
```

should be translated by `pandoc -f org -t tex macro.org macro.tex` to

```TeX
should be foobar but is foobar
```

but is translated instead into:

```TeX
should be foobar but is foo\{\{\{foo\}\}\}
```

**Comment by tarleb** [comment]
Thanks for the report.  Indeed, macros haven't been implemented yet. I hope to get this fixed in time for the upcoming pandoc 2.

**Comment by tarleb** [comment]
Emacs org-mode allows arbitrary recursion in macros, meaning that the following document would loop indefinitely:

    #+MACRO: test {{{test}}}
    {{{test}}}

Doing the same in pandoc would leave *trypandoc* open to very simple denial of service attacks. I'm going to limit recursion to a depth of 15 for that reason.

**Comment by jgm** [comment]
Out of curiosity, what does Emacs itself do with these
infinitely looping macros?  Does it freeze?

**Comment by b3** [comment]
It loops and kinda freezes :-/
One should use C-g to stop it.
