### ISSUE TITLE
RST writer should include document metadata

### ISSUE THREAD

**Issue by nichtich** [jgm/pandoc#3406]
Given this sample file `test.rst`:

~~~rst  
:key: value

text
~~~

The document metadata is parsed by RST reader:

~~~bash
$ pandoc -f rst -t markdown --standalone test.rst 
---
key: value
...

text
~~~

But it is not serialized by the RST writer (tested with pandoc 1.19.2):

~~~bash
$ pandoc -f rst -t rst --standalone test.rst 
text
~~~

Expected output is the original file `test.rst`.

As far as I understand, document metadata values in RST must be plain strings without newline so the values should be stringified, replacing newlines with spaces.

**Comment by jgm** [comment]
I'm reluctant to do any automated conversion here.  For one thing, the convention in RST (see http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bibliographic-fields) seems to be using capitalized metadata names, and that's different from what we usually have in pandoc.  I think the way to handle this is to create a custom template that inserts the fields you're interested in, using the keys you want (see how we currently treat Author and Date in the default.rst template).  You can add anything else you like here, e.g. abstract.

**Comment by infinity0** [comment]
Was the read ability removed in the meantime? Now even markdown output (of the rst input) gives a definition list instead of metadata as mentioned in the OP.

**Comment by infinity0** [comment]
Oh nvmd, you need to give `-s` or in the API set `readerStandalone = True`
