### ISSUE TITLE
Indented code not properly represented in `markdown+lhs` output

### ISSUE THREAD

**Issue by nomeata** [jgm/pandoc#3410]
Given this input:

```
 *  Item 1

    ```{.haskell .literate}
    instance Alternative Fact where …
    ```

    Foobar
```

I would expect `pandoc -f markdown -t markdown+lhs` to somehow turn this into a literate Haskell file where the code-block is picked up by GHC.

But it is not, as it is indented:

```
-   Item1

    > instance Alternative Fact where …

    Foobar
```

I am not sure if there is a better output here (I [asked for it here](http://stackoverflow.com/q/42008870/946226)). If not, then [the docs](http://pandoc.org/MANUAL.html#literate-haskell-support) should maybe document this deficiency.

**Comment by jgm** [comment]
I'm not really sure about this.  If we deindented the
blockquote so it gets picked up as code by ghc, then
it is no longer treated as part of the markdown list
item, and in fact it interrupts the list.

So I don't see a good way to make this work.

**Comment by jgm** [comment]
Feel free to make a suggestion about a specific documentation change that you think would be helpful.

**Comment by schar** [comment]
The following markdown (where the Haskell code is all line-initial) is parsed correctly (by github and seemingly pandoc) -- in particular, the list is not interrupted.

```
1.  Write a recursive `mapList` function. I'll get you started:

    ``` {.haskell .literate}
mapList :: (a -> b) -> List a -> List b
mapList f Empty = Empty
mapList f (Add h t) = error "You didn't complete mapList!"
    ```

2.  And so on...
```

Of course, the `pandoc -t markdown+lhs` conversion inserts spaces:

```
1.  Write a recursive `mapList` function. I'll get you started:

    > mapList :: (a -> b) -> List a -> List b
    > mapList f Empty = Empty
    > mapList f (Add h t) = error "You didn't complete mapList!"

2.  And so on...
```

One possibility would be to have pandoc produce the following output instead:

```
1.  Write a recursive `mapList` function. I'll get you started:

    ```
> mapList :: (a -> b) -> List a -> List b
> mapList f Empty = Empty
> mapList f (Add h t) = error "You didn't complete mapList!"
    ```

2.  And so on...
```

Which seems to be parsed correctly, i.e., without interrupting the list.

**Comment by schar** [comment]
If one's looking to simply embed literate Haskell in markdown documents directly (e.g., such that github code highlighting works), the following seems to be an acceptable solution:

```
1.  Write a recursive `mapList` function. I'll get you started:

    ``` {.haskell .literate}

> mapList :: (a -> b) -> List a -> List b
> mapList f Empty = Empty
> mapList f (Add h t) = error "You didn't complete mapList!"

    ```

2.  And so on...
```

[Which displays nicely](https://gist.github.com/schar/298540a954852232013f1500d0278620), at least on github. (The extra line breaks surrounding the bird-tracked code can be suppressed if GHC(i) is loaded with`-optL -q`.)

**Comment by nomeata** [comment]
That is a decent work-around, especially if `pandoc` could learn to strip the `> ` of such an de-indented code block, so that, say, HTML output comes out properly.

**Comment by jgm** [comment]
OK, it works with current pandoc, and with the markdown renderer GitHub is *currently* using for long-form pages (but *not* with the parser GitHub uses for short comments, which is a variant of cmark).  It is not valid CommonMark.  It is probably not very future-proof.

If you only have one level of list, then you can just put the code blocks between list items.  Since pandoc respects list start numbers, your list's numbering will be correct.  That's what I'd do if I were you.  And if you need a lot of hierachical structure, you can always use headings for that instead of lists.
