### ISSUE TITLE
pandoc document conversion failed with error 83

### ISSUE THREAD

**Issue by guillaumehans** [jgm/pandoc#3411]
Hello,

I'm trying to change the bibliography style in R Markdown to IEEE. But I get the following error when compiling the document to html:

`pandoc-citeproc: Error parsing XML file ieee.csl: ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 45:5}
pandoc.exe: Error running filter pandoc-citeproc
Filter returned error status 1
Error: pandoc document conversion failed with error 83`

My YALM is as follows:

`bibliography: bibliography.bib`
`csl: ieee.csl`
`output:`
`html_document: default`

- The ieee.csl file was downloaded from https://github.com/citation-style-language/styles (but I tried multiple others and I get always the same error)
- If I don't include the line csl: ieee.csl, the document compile without problems (so my .bib file is ok)
- Both, my .bib and .csl files are in the working directory along with the .Rmd file.
- I am under Windows 7 Pro Service Pack 1.

Anyone with a solution?

Thanks

**Comment by jgm** [comment]
Are you sure you downloaded the raw xml and not the HTML version of the CSL file? (This is a common issue people have.) 

Use this: https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl
Not this: https://github.com/citation-style-language/styles/blob/master/ieee.csl

**Comment by guillaumehans** [comment]
Great! Thank you!

**Comment by clersdom** [comment]
Hello, 

I am having a similar error when I try to knit HTML in R Markdown. 

pandoc-citeproc: PandocResourceNotFound "nature.csl"
Error running filter /usr/local/bin/pandoc-citeproc:
Filter returned error status 1
Error: pandoc document conversion failed with error 83
Execution halted

I am quite new to markdown, and regarding the above link provided I assume I should download the nature.csl file, but I am not sure if this needs to be installed... in the terminal? or in R? 

Thanks!

**Comment by mb21** [comment]
@clersdom sounds like you're specifying to use `nature.csl` but that file is not in the right place. Either way, if you're having trouble with the RStudio/RMarkdown-packaged pandoc you should ask them... we would need a plain pandoc example... which could be asked on the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
