### ISSUE TITLE
Nested bullets of github markdown aren't correctly translated

### ISSUE THREAD

**Issue by fab1an** [jgm/pandoc#3414]
Github allows bullet lists like the following which aren't translated correclty:

```
* item1
  * sub1
  * sub2
* item2
```

Example: https://pandoc.org/try/?text=*+item1%0A++*+sub1%0A++*+sub2%0A*+item2&from=markdown_github&to=html

**Comment by mb21** [comment]
see http://pandoc.org/MANUAL.html#the-four-space-rule

> The nested list must be indented four spaces or one tab

**Comment by mb21** [comment]
but yes, for `markdown_github` this is indeed a problem. see https://github.com/jgm/pandoc/issues/2210
