### ISSUE TITLE
unrecognized option `--smart'

### ISSUE THREAD

**Issue by cgrs** [jgm/pandoc#3416]
* Pandoc version 2.0
* Windows 10 (64bit)
* MiKTeX-TeX 2.9.6
* MSYSGit 2.5.0

```bash
$ pandoc -S # or --smart
unrecognized option `-S'
Try pandoc.exe --help for more information.
```

Am I missing something?

**Comment by jgm** [comment]
Version 2 isn't released yet. Please don't use it unless you're willing to go through the git log to see what has changed!

The `--smart` option has been removed.  `smart` is now an extension, so you can specify e.g. `markdown+smart` or `markdown-smart`.  Note that smart is also now default for markdown.

**Comment by ickc** [comment]
@cgrs, may I ask how do you obtain the pandoc 2.0?

**Comment by mb21** [comment]
@ickc https://github.com/jgm/pandoc/blob/master/INSTALL.md#compiling-from-source

**Comment by ickc** [comment]
Ur... I'm asking how he obtained, in case he got it from my pandoc-nightly.

**Comment by cgrs** [comment]
I really don't know what happened. I downloaded the latest pandoc release (from [here](https://github.com/jgm/pandoc/releases/tag/1.19.2.1)), but when I ran `pandoc -v` it shows version 2.0.

**Comment by ickc** [comment]
Can other Windows users confirm this? If it is true, I suspect it is related to the appveyor artifact, since the current master is already 2.0, the latest build downloaded by `make winpkg` will be from the master and so becomes the 2.0.

**Comment by jgm** [comment]
Oh, dear.  I think this must have been a problem with my
packaging.  (It was a bit nonstandard because I was
building from a non-master branch this time.)

I'll have to regenerate the Windows package
and replace it...

+++ carlos gonzález [Feb 04 17 03:19 ]:
>   I really don't know what happened. I downloaded the latest pandoc
>   release (from [1]here), but when I ran pandoc -v it shows version 2.0.

**Comment by jgm** [comment]
I've replaced the msi on the release page.

Could you try uninstalling the version you have now,
downloading the new msi from
https://github.com/jgm/pandoc/releases/tag/1.19.2.1,
and reinstalling?  This should give you pandoc 1.19.2.1.
(Try confirming that with --version.)

Let me know if it worked.
And sorry for the confusion.

+++ carlos gonzález [Feb 04 17 03:19 ]:
>   I really don't know what happened. I downloaded the latest pandoc
>   release (from [1]here), but when I ran pandoc -v it shows version 2.0.

**Comment by jaymon0703** [comment]
thank you @jgm the new msi works now...i was also getting the **unrecognized option `--smart'** error message after installing the msi a few days ago (Mon, 6 Feb)
