### ISSUE TITLE
Can pandoc pass HTML5 custom elements from Markdown to HTML unchanged?

### ISSUE THREAD

**Issue by nrnrnr** [jgm/pandoc#3420]
Issue #997 recommends to use `<article>` instead of a `<div>` to enable Pandoc to capture headers for a table of contents.  I suppose I am willing to hijack `<article>`, but I would prefer to use an HTML5 custom tag for this purpose, e.g., `<x-homework>`.

Is it reasonable to ask Pandoc to recognize such custom tags and pass them through to HTML output unchanged?  At present the tag gets wrapped in `<p>...</p>`, which does not enable me to apply the CSS customization I hoped for.

**Comment by jgm** [comment]
See #2960

**Comment by nrnrnr** [comment]
Oops; my apologies. I don't know how I missed #2960.
