### ISSUE TITLE
no more windows installer?

### ISSUE THREAD

**Issue by andrearicci** [jgm/pandoc#3428]
on the download page there's not any msi nor exe file
1.19.2.1

**Comment by jgm** [comment]
Yes, there was a problem with the installer, so I removed
it.  I will try to replace it tonight, but in the mean time
just use 1.19.2 (which is not much different).

+++ Andrea [Feb 07 17 03:38 ]:
>   on the download page there's not any msi nor exe file
>   1.19.2.1

**Comment by jgm** [comment]
I've replaced the installer.
