### ISSUE TITLE
AMS equation environment for LaTeX writer

### ISSUE THREAD

**Issue by AlexisBRENON** [jgm/pandoc#3429]
Hi,

I didn't find any information to make equation environment from markdown to LaTeX, which will allow equation reference and co.

Is there any blocking issue which prevents to convert the DisplayEquation element to equation environment (according to a variable if necessary to keep compatibility) ?

Thanks.
Alexis.

**Comment by tarleb** [comment]
Apologies for the late reply @AlexisBRENON, the issue got lost somehow. I'm not sure if I understand the question correctly, but it's possible to embed raw LaTeX into Markdown documents:

```latex
\begin{equation}
a^n + b^n = c^n, n \elem \mathcal{N}
\end{equation}
```

One could also use a pandoc (Lua) filter to render display math elements in `equation` environments.
