### ISSUE TITLE
Add a template variable containing the name of the source file

### ISSUE THREAD

**Issue by rohieb** [jgm/pandoc#3431]
I keep several Markdown documents in a Git repository which are rendered to MediaWiki through a custom template. In the MediaWiki template, I want to add a "this file is autogenerated" warning, with a link to the source file in the Git repository. For this reason, it would be nice to have a template variable, e.g. `$filename$` or `$jobname$` (inspired by LaTeX), so my template could have:

``` html
<!-- Warning: this file is auto-generated!
     See instead: https://github.com/stratum0/dokumente/$filename$
  -->
```

**Comment by jgm** [comment]
A reasonable request.  But to mention one complexity:  pandoc can take multiple input files on the command line.  It can also parse from stdin, in which case there are no input files.  Both cases would have to be handled as well.

**Comment by rohieb** [comment]
Right! I just used `\jobname` in LaTeX with stdin, which got rendered as `input`, pandoc could do the same. For multiple files, the variable could be an array, like e.g. `$classoption$` already is. The additional `$for$` is sensible overhead.

**Comment by rohieb** [comment]
BTW, I tried to do a pull-request myself, but I couldn't figure out where the template variables are set in the code… Any pointers on that? :)

**Comment by mb21** [comment]
> I couldn't figure out where the template variables are set in the code…

@rohieb https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L190

**Comment by mb21** [comment]
For the template variable to be available in all formats, I think you'll ned to make sure it is set in [this `doc'`](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/App.hs#L376). The `doc'`  should be of type `Pandoc meta blocks`, so specifically it should be in the `meta` of type [Meta](https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Definition.hs#L103). But I'm not sure where the proper place to set it is...

**Comment by rohieb** [comment]
Thanks for your initial pointer :) I didn't want to patch every single
writer, but I was able to work my way up to where the metadata comes
from :) See pull-request #3439 for what I currently have.

Since this is my first time using Haskell in a project, the last two
days were spent for a lot of reading documentation and understanding the
code, and there will probably still be a couple days to get it working…
;-) I'll raise my voice when I think the pull-request is ready.

 - Roland

**Comment by jgm** [comment]
No, the best approach is to set a variable, not metadata.  Variables just affect template rendering, which is what you want.  Just add it to writerVariables in Text.Pandoc.App.

**Comment by mb21** [comment]
ah right, so somewhere around [here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/App.hs#L231) then...

@rohieb sorry for the wrong tip...

**Comment by rohieb** [comment]
@mb21 you're welcome, I learned a lot today! :D That solution was also what had first had in mind, but somehow I didn't follow it.

It took less time than expected, and I consider #3439 ready now. I still don't quite understand how exactly the `withList` constructs work, but it compiles and does what I want… :) Nevertheless, feel free to nitpick, especially on code style.
