### ISSUE TITLE
list-table support for conversion ReST files

### ISSUE THREAD

**Issue by lruzicka** [jgm/pandoc#3432]
# list-table RST conversion problem

## Problem description

I wanted to convert some `.rst` files and pandoc reported the following error:

~~~~~~~
pandoc: ignoring unknown directive: list-table "source" (line 351, column 1)
~~~~~~~

I went through the source file and realized that it does not recognize the **list-table** directive that is used by reSt to define a table.

## How does that work.

The table designed by the **list-table** directive look like this:

~~~~~~~
.. list-table:: Frozen Delights!
   :widths: 15 10 30
   :header-rows: 1

   * - Treat
     - Quantity
     - Description
   * - Albatross
     - 2.99
     - On a stick!
   * - Crunchy Frog
     - 1.49
     - If we took the bones out, it wouldn't be
       crunchy, now would it?
   * - Gannet Ripple
     - 1.99
     - On a stick!
~~~~~~~

Where:
* `..list-table::` is the beginning of the table data
* *Frozen Delights!* is the title.
* `:widths:` define how wide each column should be
* `:header-rows:` defines the header row (makes it bold)
* each `*` represents a new row
* each `-` represents a column in that row

This would make the following output:

| Treat         | Quantity | Description                                                     |
|---------------|----------|-----------------------------------------------------------------|
| Albatross     | 2.99     | On a stick!                                                     |
| Crunchy Frog  | 1.49     | If we took the bones out, it wouldn't be,crunchy, now would it? |
| Gannet Ripple | 1.99     | On a stick!                                                     |

## Problem solution

It would be nice, if support for understanding tables in this format could be added. Thanks.

**Comment by jgm** [comment]
This should be pretty easy to implement. However,
I note that the RST reader seems to have a bug in
recognizing this kind of list, which would need to
be fixed too.

**Comment by jgm** [comment]
Here's a test case for the bug mentioned above:
```
% pandoc -f rst
* - a
  - b
* - c
  - d
^D
<ul>
<li><ul>
<li>a</li>
</ul>
- b</li>
<li><ul>
<li>c</li>
<li>d</li>
</ul></li>
</ul>
```

**Comment by gingerhot** [comment]
hi, when I  try to convert a ghc user guide file: 

https://github.com/bgamari/ghc-users-guide/blob/master/content/using-warnings.rst

and I have samiliar error messages:

> [pandoc warning] ignoring unknown role :ghc-flag: in "source" (line 1057, column 63)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 1057, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 1047, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 1041, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 1035, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 1029, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 1006, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 993, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 971, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 950, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 932, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 921, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 901, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 889, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 859, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 846, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 825, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 821, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 809, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 793, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 786, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 764, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 746, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 724, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 707, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 694, column 1)
> [pandoc warning] ignoring unknown directive: ghc-flag "source" (line 684, column 1)

 ...

I use a pandoc version 1.19.2.1 in a Ubuntu 16.04 64bit EC2 node.

Thanks a lot.

**Comment by jgm** [comment]
@gingerhot the problem here is that your document uses some custom rst directives (`hlist`, `ghc-option`).  pandoc has no way of knowing what these mean.  (`rst2html.py` will also choke on them, unless special python definitions of the custom directives are given.)

One possible change would be to have pandoc emit the block-level contents of any unknown directive.  So, in the `list-table` case above, pandoc would at least emit the list, and similarly with your `hlist`.  (However, in this case the ghc-option itself would still be omitted.)
