### ISSUE TITLE
markdown+ascii_identifiers when convert html to epub

### ISSUE THREAD

**Issue by s-nt-s** [jgm/pandoc#3435]
When I convert markdown to epub I can prevent problems with identifiers by using markdown+ascii_identifiers, but I don't find something similar in the case of convert html to epub.

How can I do that in the case of convert html to epub?

**Comment by jgm** [comment]
`ascii_identifiers` only affects identifiers that pandoc generates automatically.  When you're converting from HTML, you're dealing with explicitly given identifier attributes, and pandoc doesn't change these.

You can try using the `--ascii` option, which will cause the identifiers in the generated HTML/EPUB to be entity-escaped.  I don't know if that's enough for your needs.

If not, your best option is probably to preprocess the HTML prior to passing it to pandoc, changing the identifiers systematically.

**Comment by jgm** [comment]
PS.  Please direct questions to the pandoc-discuss mailing list.  This tracker is for bug reports.
