### ISSUE TITLE
\struts in LaTeX add too much vertical space above lists inside tables

### ISSUE THREAD

**Issue by andrewheiss** [jgm/pandoc#3436]
When including lists inside grid tables, like so…

```
: Sample grid table.

+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |
+===============+===============+====================+
| Bananas       | $1.34         | - built-in wrapper |
|               |               | - bright color     |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | - cures scurvy     |
|               |               | - tasty            |
+---------------+---------------+--------------------+
```

… there is too much vertical space above the list:

![image](https://cloud.githubusercontent.com/assets/73663/22855871/476d0248-f055-11e6-89bb-f3905fdeab92.png)

This appears to be a result of using a bunch of `\strut`s in the resulting TeX file:

```
\begin{minipage}[t]{0.32\columnwidth}\raggedright\strut
\begin{itemize}
\tightlist
\item
  built-in wrapper
\item
  bright color
\end{itemize}\strut
\end{minipage}\tabularnewline
```

[I've tried adding different commands to the preamble to remove the vertical space,](https://tex.stackexchange.com/questions/353263/how-to-remove-vertical-space-above-itemize-only-inside-longtable-minipage) but it appears that the `\strut`s prevent this from happening.

If I remove `\strut`s that precede `\begin{itemize}` either manually or with `perl -0777 -pe 's/\\strut\n\\begin{itemize}/\n\\begin{itemize}/gm;' blah.tex`, the vertical space disappears:

![image](https://cloud.githubusercontent.com/assets/73663/22856113/378adfb8-f059-11e6-8cb8-1ddd914c9c07.png)

Removing the struts seems to go against earlier pull requests like https://github.com/jgm/pandoc/pull/1573 and https://github.com/jgm/pandoc/pull/2913 and feels wrong (and also depends on the user having Perl or manually adjusting the TeX file before compiling). 

Is there a recommended way to remove vertical space above lists inside grid tables in LaTeX?

(This is all using pandoc 1.19.2.1 with the default TeX template)

**Comment by jgm** [comment]
We need to carefully reconstruct why the `\strut`s were added in the first place.  Otherwise removing them might cause another problem to pop up.  I think there's a relevant pandoc-discuss discussion and some discussions linked to the PRs you cite.  Have you looked at those?

@jlduran perhaps you can shed some light on this issue?

**Comment by andrewheiss** [comment]
I have—the discussions all deal with cell alignment and width resizing, which is fine. I think this extra-spacing-above-the-lists issue is an unintended side effect of using them, since none of the discussions mention the alignment of lists inside table cells.

Ideally it'd be nice to eliminate the spacing with some sort of adjustment or addition to the preamble rather than restructuring all the `\strut`s…

**Comment by jlduran** [comment]
Agreed. I'll take a look at it.

**Comment by jgm** [comment]
@jlduran any progress on this?

**Comment by jlduran** [comment]
Not really. The solution that comes to mind is to check for lists and remove the struts, otherwise leave as is. But that adds too much complexity and may even be another corner cases.

The other option, remove the struts entirely, is simpler and perhaps less noticeable.
