### ISSUE TITLE
Pandoc highlighting does not support JavaScript JSX

### ISSUE THREAD

**Issue by karland** [jgm/pandoc#3440]
React is an extremly popular JavaScript library. It embeds a scripting language called JSX in normal JS code. Even though pandoc supports JavaScript, it does not support JSX. It is also not listed under the `pandoc --list-highlight-languages`. Just wanted to tell how a result looks like. 
![2017-02-13 19 55 46](https://cloud.githubusercontent.com/assets/4803370/22898395/70a7a216-f227-11e6-8682-0275a13414fa.png)

**Comment by jgm** [comment]
We'd need a jsx.xml syntax definition for the KDE syntax
highlighting framework, and then we can add it.  I don't
see one in their repository (over 220 syntaxes).

If you feel like making one, go ahead, but do submit it
upstream to KDE.

Soon pandoc will have the ability to load xml syntax
definitions dynamically, which will give you a way to add
this without recompiling the highlighting library.

**Comment by jgm** [comment]
PS. See jgm/skylighting, which is the library we use for
highlighting, for more details.

**Comment by karland** [comment]
Ok, thanks for the fast response. I have a look at the xml library. Close this for the time being.

**Comment by jakoblind** [comment]
hi @karland did you make any progress on this one? :)

**Comment by karland** [comment]
Hi @jakoblind, no unfortunately not.

**Comment by jakoblind** [comment]
I figured it out. In latest version of pandoc it accepts a parameter `--syntax-definition` so you can pass in a jsx syntax definition like this: `--syntax-definition=pandoc-jsx/jsx.xml`

**Comment by davidroman0O** [comment]
@jakoblind  But is there a jsx.xml somewhere over the internet ? ahah

**Comment by davidroman0O** [comment]
@jakoblind @jgm It may be stupid buuuut is there a pandoc-jsx/jsx.xml somewhere now ?

**Comment by Everettss** [comment]
@davidroman0O I found one here https://phabricator.kde.org/differential/changeset/?ref=262426&whitespace=ignore-most 
Additionally I have to add `pandoc-jsx/language.dtd` I used this one based on [comment](https://github.com/jgm/pandoc/issues/4831#issuecomment-412298678) https://raw.githubusercontent.com/jgm/highlighting-kate/master/xml/language.dtd
