### ISSUE TITLE
Emergency stop when creating PDF with xelatex

### ISSUE THREAD

**Issue by kdelwat** [jgm/pandoc#3442]
When converting Markdown to a PDF using xelatex, I get an error and Pandoc exits early.

The command:
```bash
pandoc --latex-engine=xelatex test.md -o test.pdf
```
The result:
```bash
! I can't write on file `input.pdf'.
(Press Enter to retry, or Control-D to exit; default file extension is `.pdf')
Please type another file name for output
! Emergency stop.
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
                                                  \fi \fi 
l.67 

pandoc: Error producing PDF
```

If I omit the `--latex-engine` command, Pandoc works normally. I'm happy to provide any further information if needed 😄.

### Input

The error occurs with any input. For example,

```markdown
# A title
Some text
```

### Version Information

Pandoc
```bash
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```
Xetex
```
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016/Arch Linux)
kpathsea version 6.2.2
...
Compiled with ICU version 58.2; using 58.2
Compiled with zlib version 1.2.8; using 1.2.8
Compiled with FreeType2 version 2.7.0; using 2.7.1
Compiled with Graphite2 version 1.3.9; using 1.3.9
Compiled with HarfBuzz version 1.3.4; using 1.4.1
Compiled with libpng version 1.6.26; using 1.6.28
Compiled with poppler version 0.50.0
Compiled with fontconfig version 2.12.1; using 2.12.1
```

**Comment by mb21** [comment]
I don't think this is a pandoc bug. It probably has something to do with the contents of the input file... and then XeLaTeX fails for some reason... maybe it's very large? see http://tex.stackexchange.com/questions/16801/xelatex-i-cant-write-on-file-test-pdf

**Comment by kdelwat** [comment]
I've posted an example input Markdown above. The fact that it's so simple leads me to believe the problem is with Pandoc, but you might be right.

**Comment by mb21** [comment]
hm.. cannot reproduce this on macOS with seemingly the same XeTeX version.

    $ cat test.md 
    # A title
    Some text

    $ pandoc --latex-engine=xelatex test.md -o test.pdf

    $ pandoc -v
    pandoc 1.19.2.1

    $ xelatex -v
    XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016)

**Comment by kdelwat** [comment]
Strange, I'm not sure what could be causing it on my system (Ubuntu 16.04). What does the more verbose `xelatex --version` say? It might be a problem with the individual libraries.

**Comment by mb21** [comment]
aren't you on Arch Linux? `(TeX Live 2016/Arch Linux)`

you can try `pandoc test.md -o test.tex`, then `xelatex test.tex` – maybe you can figure out where exactly xelatex stumbles and what exactly in the output should be changed for your system..

**Comment by kdelwat** [comment]
Sorry, I copied the version from the wrong terminal window! It's the same xelatex version anyway. Good idea on the two-step process, I'll try that when I get back to my computer.

**Comment by wilx** [comment]
`! I can't write on file `input.pdf'.` usually means that you have the file open on Windows with another application, like Evince or Acrobat Reader.

**Comment by kdelwat** [comment]
After some painful investigation, @mb21 was right. The problem was a lack of available memory (who knew xetex used so much?!). Adding swap space fixed the problem. Sorry to inconvenience you :smile:
