### ISSUE TITLE
Mistakes highlighting certain Python code split by newlines

### ISSUE THREAD

**Issue by equaeghe** [jgm/pandoc#3443]
I have the following Python console input and output in my source:

```md
>>> list(f.attrs.keys())
['description',
 'source',
 'author',
 'annotations',
 'data_processing',
 'HDF5-conversion',
 'references']
```

This is turned into the following HTML:

```html
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="op">&gt;&gt;&gt;</span> <span class="bu">list</span>(f.attrs.keys())
[<span class="st">'description'</span>,
 <span class="co">'source'</span>,
 <span class="co">'author'</span>,
 <span class="co">'annotations'</span>,
 <span class="co">'data_processing'</span>,
 <span class="co">'HDF5-conversion'</span>,
 <span class="co">'references'</span>]
<span class="op">&gt;&gt;&gt;</span> <span class="bu">print</span>(f.attrs[<span class="st">'description'</span>][:<span class="dv">60</span>] <span class="op">+</span> <span class="st">'…'</span>)
This <span class="bu">file</span> mainly contains the datasets of the met mast at th…</code></pre></div>
```

The `co` (comment) class on all but the first element in the list should be `st` (string).

It seems that the parser does not deal correctly with the newlines, because putting the list items on one line fixes this problem, albeit in a code layout that I don't want. Also, this is not limited to lists, I saw the same issue with a similarly formatted dict-like object.

Info about my setup:

* Command: `name.md --highlight-style tango --self-contained -o name.html`
* Version:

    > pandoc 1.18
    > Compiled with pandoc-types 1.17.0.4, texmath 0.8.6.7, highlighting-kate 0.6.3

**Comment by jgm** [comment]
I'm happy to report that this works fine with the latest
pandoc, which uses the new skylighting library for
highlighting.

Output:

```
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="op">&gt;&gt;&gt;</span> <span class="bu">list</span>(f.attrs.keys())
[<span class="st">&#39;description&#39;</span>,
 <span class="st">&#39;source&#39;</span>,
 <span class="st">&#39;author&#39;</span>,
 <span class="st">&#39;annotations&#39;</span>,
 <span class="st">&#39;data_processing&#39;</span>,
 <span class="st">&#39;HDF5-conversion&#39;</span>,
 <span class="st">&#39;references&#39;</span>]</code></pre></div>
```

If this looks good, you can close this issue.

**Comment by equaeghe** [comment]
Thanks, I'll try to install the new version and test. This may take a while, I've asked my distribution's packager to update the package.

**Comment by jgm** [comment]
We provide a binary package for linux on the github release
page.

+++ Erik Quaeghebeur [Feb 14 17 13:57 ]:

**Comment by equaeghe** [comment]
> We provide a binary package for linux on the github release page.

Debian-based only, it seems? (Not that I'm asking for specific packages, just wondering whetherb I'm missing something.)

**Comment by jgm** [comment]
See http://pandoc.org/installing.html which tells you how
to use the deb if you're on a non-Debian based distro.
