### ISSUE TITLE
Allow HTML relative units for image width/height

### ISSUE THREAD

**Issue by jezcope** [jgm/pandoc#3450]
Would it be possible please to either explicitly support relative units (e.g. `em`, `ex`, `vw`, `vh`) in image width & height attributes, or simply pass through unrecognised units unchanged. I've found when writing reveal.js slides, for example, it's useful to express sizes in relative units so that images scale depending on the size of the viewport. Currently, pandoc seems to output no height/width information at all if the units are not recognised.

```markdown
![image]

[image]: http://example.com/image.jpg {height=30px}
```

becomes

```html
<img src="http://example.com/image.jpg" style="height:30px" />
```

but

```markdown
![image]

[image]: http://example.com/image.jpg {height=3em}
```

becomes

```html
<img src="http://example.com/image.jpg" />
```

My current workaround is to do something like this:

```markdown
![image]

[image]: http://example.com/image.jpg {style="height: 3em"}
```

**Comment by mb21** [comment]
Image sizing was designed with HTML and PDF (i.e. LaTeX) output in mind. To what LaTeX should we convert this? (pixels are converted to cm using the `--dpi` value...)

I recommend you set a class (`![image](foo.png){.myClass}`), then style that with CSS using media queries.

**Comment by jezcope** [comment]
@mb21 That's a good point. `em` and `ex` both exist in LaTeX, with equivalent meanings (proportional to the current font) so could be passed straight through. `vh` and `vw` are a percentage of the current viewport in HTML, so the LaTeX equivalent would be a fraction of `\pageheight` and `\pagewidth`, like the current translation for `%`.

**Comment by mb21** [comment]
> em and ex both exist in LaTeX, with equivalent meanings

Interesting, didn't know that. We'd still have to figure out what to do in other outputs (docx, odt, indesign, etc.) though, and I'm not sure it's worth the effort and increased complexity...

**Comment by kusmi** [comment]
I’m also interested in having **em**, e.g. to display inline images in text which don’t alter the line spacing.

I use this for embedding application icon images in my manual and currently I have to manually tune the images for titles (which have larger font) and normal text (which have smaller font).

**Comment by jgm** [comment]
I suppose we could fully support this in HTML and LaTeX (two of the most important formats), and convert 1 em = 11/64 in (see http://www.convertunits.com/from/em/to/in) for other formats.  (Of course this presupposes a normal font size and could give bad results with a big or small font.  We could emit a warning about the conversion in these cases.)

**Comment by jgm** [comment]
From the mailing list (laperouse):
CSS pixels are defined as 1/96 in and don't correspond to real pixels.
We also use 1/96 for dpi to pixel conversion.
Also

>    In the html5 spec (see chatper 4.7.16), I understand they say only CSS
   pixels are supported in inline width or height option on img, which is
   precisely what pandoc produces with attributes in md.
   https://www.w3.org/TR/html5/embedded-content-0.html#attr-dim-width
   the CSS units are only valid within CSS not in inline attribute, in
   HTML5.
