### ISSUE TITLE
Display Math in LaTex became Inline Math in Mediawiki

### ISSUE THREAD

**Issue by mukulagrawal78** [jgm/pandoc#3452]
This is seems to be exactly same issue reported previously in Issue#1719 :- Display Math in LaTex became Inline Math in HTML/MathML #1719

Converting LaTeX to mediawiki markup causes same problem that `<math display="block">` tag is not created for either `$$` tag in TeX of `\[ tag` in LaTeX.
Tried following:-

`pandoc --verbose --read latex -o math.wiki -t mediawiki math2.tex`
`pandoc --verbose --read latex+tex_math_single_backslash -o math2.wiki -t mediawiki math2.tex`

Also tried going through HTML5

`pandoc --verbose --read latex --mathml -o math2.html -t html5 math2.tex > pandoc-run-debug.log`
`pandoc --verbose --read html --mathml -o math3.wiki -t mediawiki math2.html > pandoc-run-debug.log`

HTML output is rendered correctly but mediawiki rendering is all inline mathhematics.

**Comment by mb21** [comment]
on what pandoc version are you?

**Comment by jgm** [comment]
Pandoc generates a `<math>` tag for display math (same as for inline math).
If you tell me the right way to do display math in MediaWiki, we can change.

**Comment by mukulagrawal78** [comment]
Thanks jgm for your reply. There are three ways to display math in separate lines in mediawiki:

1. Use the display="block" attribute of <math> tag.
This will generate block mathematics in separate paragraph <math display="block">\alpha\times\beta^2</math>  

This will also generate inline mathematics <math display="inline">\alpha^2+\beta^2=\gamma^2</math>.  

https://en.wikipedia.org/wiki/Help:Displaying_a_formula#Display_attribute

2. Put a deliberate line break and then put a colon : in front of <math> tag.
Following  will display mathematics after a line break and with little indentation
:<math>\Sigma^2+\epsilon_0</math>

we need a line break. This  will not display mathematics in a separate line  :<math>\Sigma^2+\epsilon_0</math>

3. Put a deliberate empty line 
You can also deliberately put a blank line to force mathematics in separate paragraph

<math>\beta+\gamma</math>

**Comment by centaure** [comment]
Thanks jgm for fixing this. From where can I download a new version for MS-Win that will include this new change?

**Comment by jgm** [comment]
If you want to live dangerously you can try pandoc-nightlies
https://github.com/pandoc-extras/pandoc-nightly

+++ Sunil [Feb 27 17 19:55 ]:

**Comment by jgm** [comment]
PS.  Since this is the dev version of pandoc 2.0, you'll
find some differences in options, etc.

+++ Sunil [Feb 27 17 19:55 ]:
