### ISSUE TITLE
Improve CodeProject HTML format support

### ISSUE THREAD

**Issue by KvanTTT** [jgm/pandoc#3455]
[CodeProject](https://www.codeproject.com/tips/880934/article-formatting-tips-for-codeproject) uses HTML as an article format and pandoc Markdown -> HTML conversion works fine except of source code blocks.

**Expected:**
```html
<pre lang="objective-c"></pre>
```

**Actual:**
```html
<pre class="objective-c"><code></code></pre>
```

I suppose to add an option for converting to CodeProject format.

**Comment by jgm** [comment]
Too special-purpose.  I recommend simply postprocessing the HTML, a perl one-liner will suffice.
