### ISSUE TITLE
Allow multiple slide-levels (tested with markdown->beamer)

### ISSUE THREAD

**Issue by ikervagyok** [jgm/pandoc#3460]
#### Summary 
Either:
* Make the `--slide-level=` option into a option taking a comment separated list of Integers. E.g. `--slide-level=2,3,4`, so every header of the levels 2-4 start a new slide.
* allow multiple instances of the option `--slide-level`(implemented already), and accumulate their values instead of ignoring all but the last instance.

#### Reasoning
It would be nice to be able to include some information about what will follow in the next couple of slides. Currently anything between a `header above slide-level` and `header at or below slide-level` is lost, except for intermediate headers.

#### Affected
Converting a presentation from markdown to a beamer-pdf.

#### Testcase
test.md:
```{.numberLines}
# Level 1 Header
Description at level 1

## Level 2 Header, pt.1
Description at level 2.1

### Level 3 Header
Description at level 3

## Level 2 Header, pt.2
Description at level 2.2
```
Command:
1. `# pandoc -t beamer --slide-level=2 test.md -o test.pdf`
2. `# pandoc -t beamer --slide-level=3 test.md -o test.pdf`

Result:
1. not sufficient, because:
    * *IGNORE THIS:* lost the content between `# Level 1 Header` and `## Level 2 Header, pt.1`
    * `### Level 3 Header` doesn't start a new slide
2. not sufficient, because:
    * *IGNORE THIS:* lost the content between `# Level 1 Header` and `## Level 2 Header, pt.1`
    * lost the content between `## Level 2 Header, pt.1` and `### Level 3 Header`

System:
* pandoc 1.19.2.1
* NixOS 17.03.git.dc19ba7 (Gorilla)

**Comment by mb21** [comment]
So you want `slide-level` to be a list instead of one number? What would the behaviour be and what's your use case exactly? Also see https://github.com/jgm/pandoc/issues/2265

**Comment by ikervagyok** [comment]
@mb21 thanks for the link, #2265 seems to be similar, if not the same issue/feature request.

i would like to be able to add information to the title-slide, which doesn't get dropped in the generated `pdf` - it seems to be in the generated `tex`, but not in the `pdf`

more generally i would like to do nesting of topics (with some general content/describtion) and sub-topics (with the actual content), while making sure that i don't need to
    * maintain a subtopic `General` where the general description of the topic would fit in.
    * reduce `slide-level` by one, which would change the to the above testcase, meaning slides of level `n` wouldn't get their own slide.

```
# Level 1 Header
Description at level 1 (this is invisible/nonexistent)

## Level 2 Header, pt.1
### General (inserted as a quick-fix, so the next line gets shown)
Description at level 2.1

### Level 3 Header
Description at level 3

## Level 2 Header, pt.2
Description at level 2.2 (this is invisible/nonexistent, as i "forgot" to include "### General" before this)
```

N.B.: when i change the output, the described part of the content dis-/appears:
* `pandoc -t beamer --slide-level=3 test.md -o test.pdf` --- Broken, as content is missing
* `pandoc --slide-level=3 test.md -o test.pdf` --- Working, but not a presentation

**Comment by ikervagyok** [comment]
It's the same with slidy, the two lines are missing from the presentation.
`pandoc -t slidy --slide-level=3 test.md -o test.html` gives me:
```
<div id="level-1-header" class="titleslide slide section level1">
  <h1>Level 1 Header</h1>
</div>
<div id="level-2-header-pt.1" class="titleslide slide section level2">
  <h2>Level 2 Header, pt.1</h2>
</div>
<div id="general-inserted-as-a-quick-fix-so-the-next-line-gets-shown" class="slide section level3">
  <h3>General (inserted as a quick-fix, so the next line gets shown)</h3>
  <p>Description at level 2.1</p>
</div>
<div id="level-3-header" class="slide section level3">
  <h3>Level 3 Header</h3>
  <p>Description at level 3</p>
</div>
<div id="level-2-header-pt.2" class="titleslide slide section level2">
  <h2>Level 2 Header, pt.2</h2>
</div>
```
while just `pandoc --slide-level=3 test.md -o test.html` gives:
```
<h1 id="level-1-header">Level 1 Header</h1>
<p>Description at level 1 (this is invisible/nonexistent)</p>
<h2 id="level-2-header-pt.1">Level 2 Header, pt.1</h2>
<h3 id="general-inserted-as-a-quick-fix-so-the-next-line-gets-shown">General (inserted as a quick-fix, so the next line gets shown)</h3>
<p>Description at level 2.1</p>
<h3 id="level-3-header">Level 3 Header</h3>
<p>Description at level 3</p>
<h2 id="level-2-header-pt.2">Level 2 Header, pt.2</h2>
<p>Description at level 2.2 (this is invisible/nonexistent)</p>
<h1 id="level-1-header-pt.2">Level 1 Header, pt.2</h1>
```
(I know that the `slide-level` argument could be omitted for pure html)
The problem I see is that information gets lost during the transformation of a document. Is that the intended behavior - maybe a feature that I'm not aware of? Is this something other people rely on? While reading up on pandoc I found a few questions about comments that aren't even in the source code of the result - but there was nobody mentioning slides and slide-levels for that.

**Comment by mb21** [comment]
> The problem I see is that information gets lost during the transformation of a document. Is that the intended behavior 

From #2157 (which is linked in #2265):

> Pandoc has a method of carving content into slides
(described in the User's Guide) that works the same for all
slide formats, so you can use the same source for reveal.js
and beamer. That is what motivated the present system,
though I'm open to a better way, as long as it works
uniformly with all formats.

Also see http://pandoc.org/MANUAL.html#structuring-the-slide-show

Maybe we should update that section in the manual and document when content is dropped...?

**Comment by jgm** [comment]
I've made an attempt to clarify things in the MANUAL.

**Comment by ikervagyok** [comment]
@jgm Thank you for this clarification in the docs. Currently I'm occupied, but in the next few days I'll have time to look into this again and tell if this was my issue, or just a part of it.
