### ISSUE TITLE
Format code blocks in MediaWiki markup with <source> or <syntaxhighlight> tags rather than <pre>

### ISSUE THREAD

**Issue by joelostblom** [jgm/pandoc#3461]
Is there a way for pandoc to output syntax highlighted code blocks in mediawiki format (possibly using the `<source>` or `<syntaxhighlight>` tags)? Preferably without converting `<` to `&lt;`.  

---

#### Background
If I have a markdown file `~/test-r.md`:

<pre>
A function in `R`:

```R
x <- 3
x + 5
## 8
```
</pre>

`pandoc -f mediawiki ~/test-r.md` outputs

```
A function in <code>R</code>:

<pre class="r">x &lt;- 3
x + 5
## 8</pre> 
```

which is rendered on mediawiki sites without R-specific syntax highlighting:

![selection-20170221-01](https://cloud.githubusercontent.com/assets/4560057/23171130/a2277624-f81f-11e6-8d82-78e79ac79740.png)

If I manually change the tags to either `<syntaxhighlight lang="r">` or `<source lang="r">` ([as described here](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight))I get output with syntax highlighting:

![selection-20170221-02](https://cloud.githubusercontent.com/assets/4560057/23171334/2faaa44e-f820-11e6-80c2-348e5e4ac793.png)

However, the odd assignment operator conventions in R, `<-`, causes troubles since pandoc converted the `<` to `&lt;`, and it needs to be manually changed back to achieve the desired output ([possibly related](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight#Advanced)):

![selection-20170221-03](https://cloud.githubusercontent.com/assets/4560057/23171562/cc9bc3fa-f820-11e6-9339-2310d9630a79.png)

**Comment by jgm** [comment]
This was just a matter of updating the list of highlighting languages mediawiki supports.

**Comment by joelostblom** [comment]
Wow, that was quick! Thank you!
