### ISSUE TITLE
bump directory bound

### ISSUE THREAD

**Issue by NorfairKing** [jgm/pandoc#3463]
`directory-1.3` is out.

**Comment by jgm** [comment]
We already have a version bound that includes this.
(Just not in a release.)

**Comment by NorfairKing** [comment]
Oh, fair enough. When should I expect a release?

**Comment by jgm** [comment]
I don't know.  Not in the near future, because we're gearing
up for a big 2.0 release.

+++ Tom Sydney Kerckhove [Feb 21 17 14:48 ]:

**Comment by NorfairKing** [comment]
It there ary chance you could release a 1.19 verison with the bumped version then?

**Comment by jgm** [comment]
What I said was wrong. Actually, the latest release
does allow directory 1.3.

https://hackage.haskell.org/package/pandoc-1.19.2.1/pandoc.cabal


+++ Tom Sydney Kerckhove [Feb 27 17 01:58 ]:

**Comment by NorfairKing** [comment]
Oh, how silly of me.
I'm so sorry to have wasted your time.
Thank you for helping me!
