### ISSUE TITLE
Hard line break followed by footnote breaks rendering of footnote

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#3465]
If a footnote is placed after a \ escape hard line break then the footnote fails to be parsed (cf1 fails in the minimal testcase, cf2 is properly converted):

```
Ea mea diam[^cf1] facete democritum, no quidam facilisis dissentias vix[^cf2].  

#Refs#
Jones, A. (2001, October 10). Understanding Old English poetry. Time, 50-62.  \
Pearsall, D. (1977). Old English and Middle English poetry. London: Routledge.  \

[^cf1]: Test footnote A…

[^cf2]: Test footnote B…
```

It wasn't clear from the docs why this is the case:

>"Each footnote should be separated from surrounding content (including other footnotes) by blank lines" 

This is nominally true in this example (unless a blank line following a hard break is not really a blank line) so I'm not sure if this is expected behaviour or not?

pandoc 1.19.2.1, macOS 10.12.3, tested using HTML > stdout

**Comment by mb21** [comment]
> unless a blank line following a hard break is not really a blank line

correct. to see why:

    $ cat test.md
    foo

    bar\

    baz


    $ pandoc test.md
    <p>foo</p>
    <p>bar<br />
    baz</p>
