### ISSUE TITLE
Sections with both .unnumbered and .unlisted are still listed in the TOC

### ISSUE THREAD

**Issue by kuba-orlik** [jgm/pandoc#3474]
The title practically says it all. To sum it up with an example:

```
# Title {.unlisted}
```

gives:

```
\chapter{Title}\label{title}
```

But 

```
# Title {.unlisted .unnumbered}
```

gives:

```
\chapter*{Title}\label{title}
\addcontentsline{toc}{chapter}{Title}
```

AFAIK the second example should not print `\addcontentsinline`

I'm using pandoc 1.19.2.1

**Comment by jgm** [comment]
Why did you think this would work?  Do you see any references
to `unlisted` in the manual?

**Comment by kuba-orlik** [comment]
Whops, my bad. It turns out that the `unlisted` class has no effect. I falsely concluded that the lack of `\addcontentsline` means "don't add the section to the TOC". 

I think it would be nice to have that option, then. I'm creating a book with a preface and want it to not be listed in the TOC, nor for it to have a title.

**Comment by jgm** [comment]
See #1762, where there is a proposal to make writers sensitive a `notoc` class on headers.
(`unlisted` isn't a bad name, actually.)
