### ISSUE TITLE
RST Implicit Internal Links not registering

### ISSUE THREAD

**Issue by wmhorne** [jgm/pandoc#3475]
In an RST document, I have a headline

    Years
    -----

which, by RST standards, becomes the target of an implicit link. I then, later [EDIT: or earlier], write `Years_` in an effort to link to that target, again according to RST protocol. Github renders it correctly; pandoc does not. Presently, `Years_` comes out verbatim (underscore included) in the pdf output, with no link associated. I believe it should be made a link to the related header.

Sound like something that can/should be fixed?

RST Resources:

[RST Headers-as-links](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#implicit-hyperlink-targets)

[RST Hyperlink-references](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-references)

**Comment by jgm** [comment]
This should be fixed.  Is the algorithm for generating an identifier from the header's text documented somewhere?

**Comment by wmhorne** [comment]
Just to confirm: this is now fixed?

**Comment by mb21** [comment]
yes, should be fixed in current master (fixed by https://github.com/jgm/pandoc/commit/d1b50a6c5d3b5a563f15a9a1db05f62d077efecf)
