### ISSUE TITLE
generation of bookmarks in docx writer cannot be disabled

### ISSUE THREAD

**Issue by DmitriyK-CPKIO** [jgm/pandoc#3476]
After I upgraded to 1.19.2.1 the parameter I've been using (-implicit_header_references) along with DOCX conversion does not matter, because references are still there.

**Comment by jgm** [comment]
Please give an example, with full command line and some Markdown input sufficient to show the problem.  Explain what you expected and what you got.

**Comment by DmitriyK-CPKIO** [comment]
> # Header 1
> 
> text
> 
> ## Header 2
> 
> text
> 
> ### header 3
> 
> text

with command line of
`C:\Sublime32\Pandoc\pandoc.exe -f markdown_strict+escaped_line_breaks+definition_lists+strikeout+superscript+multiline_tables+pipe_tables+startnum+fancy_lists+table_captions+simple_tables+footnotes+inline_notes+yaml_metadata_block-implicit_header_references -t docx --reference-docx=I:\Шаблоны\A5.dotx --no-highlight -o r:\temp\tmphqpnef.docx`

I expect to get no bookmarks in .docx file, and AFAIR didnt get them earlier, but after upgrading from 1.18 it seems I get them now. Somethings wrong with file uploading, so cannot attach a screen what bookmarks mean.

**Comment by jgm** [comment]
Yes, we always include bookmarks, even if the AST does not attach identifiers to the headers.  Looks like this has been there since at least 2012 (see d599c4cdabd0d71fd9d27161c949b5e1e692436d), so unless you were using an extremely old version of pandoc, I'm not sure why there would have been a change.

Can you explain why it's not good for you to have the bookmarks?  What harm do they do?

(Note that `implicit_header_references` gives you the ability to do implicit reference links to headers; this is disabled; you can't do `[header 3]` and get a link, for example.  This requires bookmarks, but bookmarks can be useful even without this, so turning this off doesn't turn off bookmarks.)

**Comment by DmitriyK-CPKIO** [comment]
I prefer to make bookmarks manually in a docx (referring not to headers usually), and when these auto-bookmarks are created I have to delete them so they dont mess around. If autocreaton of bookmarks could be turned off, that would be nice.

**Comment by jgm** [comment]
+++ DmitriyK-CPKIO [Feb 28 17 22:47 ]:
>   I prefer to make bookmarks manually in a docx (referring not to headers
>   usually), and when these auto-bookmarks are created I have to delete
>   them so they dont mess around. If autocreaton of bookmarks could be
>   turned off, that would be nice.

I think it will probably work to omit creation of a bookmark
when the header has an empty identifier.  I'll have to check
to make sure this wouldn't break anything.  If we made this
change, then disabling `auto_identifiers` should be enough
to prevent bookmarks from being created.

**Comment by DoctorSubtilis** [comment]
I'd like to chose if I want or not the bookmarks, converting an md to odt, e.g.

**Comment by mb21** [comment]
@DoctorSubtilis try using `-f markdown-auto_identifiers`

**Comment by DoctorSubtilis** [comment]
Perfect! It works! Thank you very much!

**Comment by robclancy** [comment]
The commit here shows it was able to be ignored if no ID but now it seems that is gone? I need to disable bookmarks.

**Comment by lakindu2002** [comment]
I tried this command - `pandoc -o ./output.docx -f markdown-auto_identifiers -t docx ./pricing.md` but still the bookmarks are added @mb21 

@DoctorSubtilis @mb21 do you have any other fix?

**Comment by stephane-klein** [comment]
@lakindu2002 and @DoctorSubtilis Have you found a way to disable bookmarks?

**Comment by cpkio** [comment]
Maybe a lua filter will help?

**Comment by drtingtp** [comment]
> @lakindu2002 and @DoctorSubtilis Have you found a way to disable bookmarks?

In my lua filter where I parse through the blocks, I managed to remove the bookmarks when rendered as docx by setting `el.identifier = ""`

Snippet:
```lua
for i, el in pairs(doc.blocks) do
    el.identifier = ""
end
```
