### ISSUE TITLE
graphviz dot RESULTS ignored in org-mode

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#3477]
I'm trying to get pandoc to show a dot image in org-mode, while hiding the input source.

This is my code

```
#+BEGIN_SRC dot :file images/graphpocalypse.png :exports results :cmdline -Kdot -Tpng
digraph {
  // graph from left to right
  rankdir=LR;
  splines=true;
  node [shape=box];
 
  id [label="Install Graphviz"]
  conf [label="Configure org-babel"]
  dot [label="DOT in org-mode"]
 
  id -> conf
  conf -> dot
  dot -> "Profit"
  dot -> "Success" [style=dotted]
}
#+END_SRC

#+RESULTS:
[[file:images/graphpocalypse.png]]
```

Part of this revealjs talk https://github.com/ensime/ensime.github.io/tree/20e714c2aa3344fda0c3270621859607b11a0fc8/talks/scalasphere17

But every time I run pandoc on it (exact command in the .pandoc file in the same directory), the SRC is included but the image is ignored.

This is kind of weird because I have a dittaa image higher up in the same file, and pandoc is able to correctly hide the SRC but show the RESULTS there.

```
$ pandoc -v
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1, skylighting 0.1.1.5
```

(ArchLinux)

**Comment by stefanq** [comment]
The fix repairs a powerful and thus important feature for users of org-mode and I'm not sure if this will be subject to a release in the near future.
Could this fix therefore maybe back-ported to the current release?

**Comment by tarleb** [comment]
I don't think there will be an intermediate release.  You can grab a current build from [pandoc nightly](https://github.com/pandoc-extras/pandoc-nightly/releases) if multi-word arguments are very important to you.
