### ISSUE TITLE
Get image size variable from markdown

### ISSUE THREAD

**Issue by alaneuler** [jgm/pandoc#3484]
Hi, I am writing a latex template to produce pdf format file from markdown, but I encounter a problem right now: how can I get the image size specified by the user in the template?
I use the code below to include images:

    \let\Oldincludegraphics\includegraphics
    \renewcommand{\includegraphics}[1]{\Oldincludegraphics[width=123pt]{#1}}

123pt is the static image size, but I want to set it to `xxx` according:
   
    ![caption](image.png){width=xxx}

**Comment by jgm** [comment]
I don't really understand the question, but in any case, all questions should go to the pandoc-discuss mailing list, not here.  This is for bug reports, not questions.
