### ISSUE TITLE
Markdown writer does not properly escape list-item-look-alikes

### ISSUE THREAD

**Issue by nichtich** [jgm/pandoc#3492]
This is a follow up from more general issue #1685. Given this `example.md`:

~~~markdown
---
test: '1\. inline'
...

1\. inline
~~~

Parsed and written back as Markdown (tested with pandoc 1.19.2.1.):

    pandoc example.md -t markdown -s

Results in this document:

~~~markdown
---
test: '1. inline'
---

1\. inline
~~~

Escaping is done properly in the document body but not in the document metadata.

**Comment by jgm** [comment]
I see why it's doing this, but it's not an easy thing to fix.

The rule that gives us the `\.` in the body is a special-case rule on `Para`.  If a Para block begins with something that could start an ordered list, we insert the extra backslash.

In the metadata, we don't have a Para; we have a MetaInlines element.
```
Pandoc (Meta {unMeta = fromList [("test",MetaInlines [Str "1.",Space,Str "inline"])]})
```

**Comment by jgm** [comment]
Actually it turned out to have a simple fix, and this also dealt with the linked issue (where you don't explicitly escape the period in the `title` field).
