### ISSUE TITLE
code listings get gobbled in itemize

### ISSUE THREAD

**Issue by svenevs** [jgm/pandoc#3493]
Hello.  I tried to post on pandoc-discuss first, but it never let me actually post.  Not sure why :/

Anyway, I don't know if this is a bug, but I'm not sure if breaking on two-space indentation when the input is specified as github_markdown is correct or not.  I know even less of where I would go to try and fix it...

The desire is to get code listings *inside* the itemize (I'm attaching alert to all of these).  [Gist here for better clarity with renders at bottom](https://gist.github.com/svenevs/81c0f08d20bc8c2f51379ee5fe5768e6)

### 1. Broken: whitespace gobbled.

Excuse: invalid syntax?

    - First bullet
    - Second bullet
    - A third bullet point, **NO** newline before fenced block, no indentation
    ```bash
    echo '*'
    if [[ $thing -eq 1]]; then
        echo "NO"
    else
        echo "YES"
    fi
    ```

### 2. Working: requires exactly four spaces and a newline

Question: invalid GFM syntax?  Four leading spaces is supposed to start a code block, so shouldn't the back-ticks get rendered?

    - First bullet
    - Second bullet
    - A third, newline and four space indentation
    
        ```bash
        echo '*'
        if [[ $thing -eq 1]]; then
            echo "NO"
        else
            echo "YES"
        fi
        ```

### 3. Could be: two space indentation.

I think this is the official notation, but you all here know way more about the standards then I do.  Regardless, it breaks on this and could probably be fixed to not?

    - First bullet
    - Second bullet
    - A third, note newline between fence, and two spaces indentation

      ```bash
      echo '*'
      if [[ $thing -eq 1]]; then
          echo "NO"
      else
          echo "YES"
      fi
      ```

Sorry if this was supposed to go through pandoc-discuss first, I tried two different e-mails and never got anything up.  I have a solution, but noticed the above may actually be a bug and wanted to at least point it out.  Thanks for `pandoc`.  Still very new to it, but it's fascinating!

**Comment by jgm** [comment]
#2 is correct.  John Gruber's original Markdown syntax description specifies that paragraphs and block quotes inside list items need to be indented an additional 4 spaces.

#3 will probably work on some sites, but not with pandoc. Pandoc uses the 4-space rule (see the documentation for motivation).

**Comment by svenevs** [comment]
Very good, thanks for explaining that!  I misunderstood the Note saying

> Note: Although the four-space rule for continuation paragraphs comes from the official Markdown syntax guide, the reference implementation, Markdown.pl, does not follow it. So pandoc will give different results than Markdown.pl when authors have indented continuation paragraphs fewer than four spaces.
> 
> The Markdown syntax guide is not explicit whether the four-space rule applies to all block-level content in a list item; it only mentions paragraphs and code blocks. But it implies that the rule applies to all block-level content (including nested lists), and pandoc interprets it that way.

If anybody stumbles upon this he is referring to the [4 space rule here](http://pandoc.org/MANUAL.html#the-four-space-rule).
