### ISSUE TITLE
\newpage command inside LaTeX table throws pandoc off

### ISSUE THREAD

**Issue by sixtyfive** [jgm/pandoc#3494]
When there' s a `\newpage` command inside of a LaTeX table, pandoc stops interpreting it as a table. The expected behaviour, from my viewpoint as an unsuspecting user who didn't think of pandoc back when I wrote a LaTeX table that was only supposed to be interpreted by LaTeX at that time, would be for pandoc to simply discard the `\newpage` command and keep going, already having figured out it's dealing with a table because of the initial `\begin{tabular}` command. I.e. the only thing that should stop pandoc from considering a LaTeX table a table should be an `\end{tabular}` command.

**Comment by jgm** [comment]
It would be helpful if you could give us a small test case.

**Comment by sixtyfive** [comment]
This is the one that I'm working on atm (pandoc 1.17.2 from Debian Stretch):

```
\documentclass{article}

\begin{document}

\begin{table}[h!]
\begin{tabular}{r|l|l}

  {\large \textbf{ﺍ}} && \\
  \textbf{ﺄﺤﺴﻨﺘـ(ﻭﺍ) IV} & \em{ʾaḥsant(ū)} & thank you \\
  \newpage
  \emph{blah} & \emph{blah} & \emph{blah} \\
  blah & blah & blah \\

\end{tabular}
\end{table}

\end{document}
```

**Comment by sixtyfive** [comment]
o_O

thank you! :smile:
