### ISSUE TITLE
Re-enable support for custom lua writers

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3495]
This was temporarily disabled in the pandoc 2.0 changes.
We need to figure out how to reintegrate them inside PandocMonad.

**Comment by jgm** [comment]
This is from commit 04487779b26458597fb751325b24c576b5088662
```
+  -- disabling the custom writer for now
   writer <- if ".lua" `isSuffixOf` format
                -- note:  use non-lowercased version writerName
-               then return $ IOStringWriter $ writeCustom writerName
-               else case getWriter writerName' of
+               then error "custom writers disabled for now"
```

**Comment by tarleb** [comment]
One option might be to force custom writers into being "pure" by limiting the lua modules available to the writer.  If the `io`, `os`, `debug`, and maybe some more libraries are not loaded into the lua state used by the writer, the lua scripts essentially become pure.  This seems like a justifiable use of `unsafeIO`.

Side-effects would be limited to the filtering stage.  This requires #3395 to be completed.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Mar 06 17 15:04 ]:
>   One option might be to force custom writers into being "pure" by
>   limiting the lua modules available to the writer. If the io, os, debug,
>   and maybe some more libraries are not loaded into the lua state used by
>   the writer, the lua scripts essentially become pure. This seems like a
>   justifiable use of unsafeIO.

Interesting idea...though I think in this case we can just
use liftIO, since we're running this with runIO -- we don't
need to make it possible for custom writers to run in any
instance of PandocMonad.
