### ISSUE TITLE
autolink_bare_uris extension doesn't work

### ISSUE THREAD

**Issue by CodeGnome** [jgm/pandoc#3498]
## Reproducing the Problem
Given an input file containing:

`http://foo.example.com`

the bare link is not converted to a hyperlink when using the autolink extension. For example:

```
$ pandoc -t 'html+autolink_bare_uris' -f markdown /tmp/foo
<p>http://foo.example.com</p>
```

## Expected Behavior
The HTML output should contain an *a* tag with an *href* attribute rather than just paragraph tags.

**Comment by jgm** [comment]
This is a Markdown extension, not an HTML extension. Hence you want:
```
pandoc -f markdown+autolink_bare_uris -t html
```
