### ISSUE TITLE
org reader detects false tables in lists

### ISSUE THREAD

**Issue by chfin** [jgm/pandoc#3499]
In Pandoc 1.19.2.1, the following org file:
```org
- |something|
```
is translated to
```json
{"blocks":[{"t":"BulletList","c":[[{"t":"Table","c":[[],[{"t":"AlignDefault"}],[0],[],[[[{"t":"Plain","c":[{"t":"Str","c":"something"}]}]]]]}]]}],"pandoc-api-version":[1,17,0,5],"meta":{}}
```
i.e., `|something| is recognized as a table, which is different from standard org-mode behaviour.
The same holds for numbered lists:
```org
1. |something|
```
```json
{"blocks":[{"t":"OrderedList","c":[[1,{"t":"DefaultStyle"},{"t":"DefaultDelim"}],[[{"t":"Table","c":[[],[{"t":"AlignDefault"}],[0],[],[[[{"t":"Plain","c":[{"t":"Str","c":"something"}]}]]]]}]]]}],"pandoc-api-version":[1,17,0,5],"meta":{}}
```
and description lists:
```org
- term :: |def|
```
```json
{"blocks":[{"t":"DefinitionList","c":[[[{"t":"Str","c":"term"}],[[{"t":"Table","c":[[],[{"t":"AlignDefault"}],[0],[],[[[{"t":"Plain","c":[{"t":"Str","c":"def"}]}]]]]}]]]]}],"pandoc-api-version":[1,17,0,5],"meta":{}}
```
According to the [org-mode manual](http://orgmode.org/manual/Built_002din-table-editor.html) "any line with ‘|’ as the first non-whitespace character is considered part of a table", which is not the case in these situations.

**Comment by tarleb** [comment]
This is a bit more complicated, as tables are not generally forbidden in list items, they just apparently cannot be the same line as the list marker:

```
- 
   |foo|
```

gives

```
\begin{itemize}
\item \begin{center}
\begin{tabular}{l}
foo\\
\end{tabular}
\end{center}
\end{itemize}
```

when exporting to LaTeX.

**Comment by jgm** [comment]
Ah, I see!  Sorry for the premature fix.

+++ Albert Krewinkel [Mar 08 17 04:23 ]:
>   This is a bit more complicated, as tables are not generally forbidden
>   in list items, they just apparently cannot be the same line as the list
>   marker:

**Comment by jgm** [comment]
PS. In an earlier attempt to fix this I tried to query the
source column.  The problem is that this information gets
corrupted when we use parseFromString.

**Comment by tarleb** [comment]
Thanks for mentioning `parseFromString`: the org-reader keeps track of when it saw some special characters using that function.  This allows us to check if we are in a list and haven't seen any special char yet, which is equal to being right after the list marker.
