### ISSUE TITLE
org -> docx: BEGIN_EXPORT html blocks are not considered

### ISSUE THREAD

**Issue by yssource** [jgm/pandoc#3500]
```
#+BEGIN_EXPORT html
<table>
<tr>
<td>Test</td>
<td>Test 2</td>
</tr>
</table>
#+END_EXPORT
```

Nothing is going to display on .docx

**Comment by tarleb** [comment]
Thank you for your report. The content of `EXPORT` blocks will only be exported if the target format is capable of including raw chunks of the export block format. This is not the case for docx and HTML, which is why it's omitted from Theo output. `src` blocks might be a good alternative here.
