### ISSUE TITLE
Any way to get the dpi from a filter?

### ISSUE THREAD

**Issue by saveman71** [jgm/pandoc#3503]
I'm currently writing a filter in python, is there any way to get such info? The goal is to convert px units to inches.

AFAIK it's not possible either with https://github.com/jgm/pandocfilters or https://github.com/sergiocorreia/panflute

For now I'm using the default 96dpi, which works, but I'd like it to be more dynamic :)

**Comment by jgm** [comment]
Questions should go to the pandoc-discuss mailing list, not here, please.  This is for bug reports.
(But the answer is no, there's no way to access WriterOptions in the filters.)
