### ISSUE TITLE
--bibliography mybib.bib not working

### ISSUE THREAD

**Issue by pbt001** [jgm/pandoc#3505]
Hi, 

I have a problem to implement my references into a .tex to .docx conversion. This is what I get:

> pandoc-citeproc: Error in $: expected product (:*:), encountered Object
> CallStack (from HasCallStack):
>   error, called at ./Text/Pandoc/JSON.hs:99:48 in pandoc-types-1.16.1-480MEXEHIxeFvyjA2KK2ox:Text.Pandoc.JSON
> pandoc: Error running filter pandoc-citeproc
> Filter returned error status 1

from 

`pandoc mwe.tex -o output.docx --bibliography mybib.bib`

This is the content of the .tex file: 

```
\documentclass{article}
\usepackage{biblatex}
\bibliography{mybib}

\begin{document}
\section*{A section}
After this comes the cite \autocite{author00:_title}
\printbibliography
\end{document}
```

and mybib.bib

```
@Book{author00:_title,
  author =   {Author},
  title =    {Title},
  publisher =    {Publisher},
  year =     2000}
```

Could you please help me to find out what’s going on? 

Cheers, 
Paul

**Comment by mb21** [comment]
Have you lately upgraded pandoc but not pandoc-citeproc ?

btw, please ask questions like this on pandoc-discuss, this is for tracking bugs etc.
