### ISSUE TITLE
org-mode parser bug

### ISSUE THREAD

**Issue by balez** [jgm/pandoc#3506]
pandoc 1.12.4.2

level 1 sections are confused with list items, unless two blank lines separate one from the other.

    <ORG INPUT>
    - item
    * section
    </ORG INPUT>

yields:

    <MD OUTPUT>
    -   item
    -   section
    </MD OUTPUT>

instead of

    <MD OUTPUT>
    -   item

    section
    =======
    </MD OUTPUT>

Adding one line between the item and the section is not enough, however with two lines, the expect result is produced.

According to the org-mode manual, asterisks in the first
column always mark a section. When used as lists bullets,
asterisks should be indented.  See "plain-list" in the manual, note (1):

> When using * as a bullet, lines must be indented or they will
> be seen as top-level headlines.  Also, when you are hiding leading
> stars to get a clean outline view, plain list items starting with a
> star may be hard to distinguish from true headlines.  In short: even
> though * is supported, it may be better to not use it for plain list
> items.

**Comment by tarleb** [comment]
Pandoc v1.12.4 is a very old version.  I could not reproduce the problem with the newer versions.  Installing the current release should fix the issue.
