### ISSUE TITLE
inline latex formula $$

### ISSUE THREAD

**Issue by Mantis-Shrimp** [jgm/pandoc#3507]
convert org-mode to markdown

engling$a_i$English           is right。
but
中文$a_i$中文                   is wrong。

why？

**Comment by mb21** [comment]
I believe this has been fixed in the newest pandoc version:

    $ pandoc

    engling$a_i$English is right

    中文$a_i$中文 is wrong


    <p>engling<span class="math inline"><em>a</em><sub><em>i</em></sub></span>English is right</p>
    <p>中文<span class="math inline"><em>a</em><sub><em>i</em></sub></span>中文 is wrong</p>
