### ISSUE TITLE
Move Markdown list parsing closer to CommonMark

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3511]
Currently we follow the 4-space rule.  It would be good to switch to the CommonMark rule for nested list content, which is a bit more complex but allows more flexibility.  Well-formatted 4-space rule lists should still work with no changes, but we'd also be able to handle 2-space indented sublists, for example.  (See many closed bug reports relating to this...#3125 #2367 #2575 #2210 #1990 #1137 #744 #172 #137 #128.)

There'd be some danger of breakage of existing documents when indented code blocks are used inside list items.  Currently these need to be indented 8 spaces relative to the outer list.  With the CommonMark rule, the indentation needed depends on where the list content begins after the list marker.  So, if you had a list like
```
- foo

        code
```
which pandoc currently interprets as
```
<ul>
<li><p>foo</p>
<pre><code>code</code></pre></li>
</ul>
```
with the CommonMark rules you'd get
```
<ul>
<li><p>foo</p>
<pre><code>  code
</code></pre></li>
</ul>
```
with two extra spaces at the beginning of the code.  But if you had
```
  - foo

        code
```
you'd be fine, it would render the same.

All in all, I think the risk of breaking some existing documents is outweighed by the benefits of rendering nested lists where people clearly expect them, and reducing unexpected surprises when moving between Markdown implementations.

**Comment by jgm** [comment]
An extension `four_space_rule` could be added so the old behavior could be selectively enabled.

**Comment by AraHaan** [comment]
the thing I have to use pandoc for is converting markdown to rst as I do not know rst nor can I write rst for jack. However markdown is very easy (unless I want to inline another markdown file inside of it). However I do not know if rst would allow me to inline another rst file inside of another rst file either.

**Comment by AraHaan** [comment]
Also this is incorrect for pypi on [pypi.python.org](https://pypi.python.org/pypi)

like for example when converting an markdown file to restructured textL

```rst
|PyPI| |PyPI|

The ``datetime_diff`` package provides a useful function for comparing
two different datetime objects and returns the time elapsed since.

for example, a datetime object when turned into a string (being
2015-12-03 03:34:57.281000) when compared with a new datetime object
(equivalent to the current time) one can determine how many years,
months, days, hours, minutes, and seconds ago the prior datetime object
was.

This returns the data as a string readable by humans denoting how much
time has passed since the specified prior datetime object.

.. |PyPI| image:: https://img.shields.io/pypi/v/datetime_diff.svg
   :target: https://pypi.python.org/pypi/datetime_diff/
.. |PyPI| image:: https://img.shields.io/pypi/pyversions/datetime_diff.svg
   :target: https://pypi.python.org/pypi/datetime_diff/

```

it should be:

```rst
.. image:: https://img.shields.io/pypi/v/datetime_diff.svg
   :target: https://pypi.python.org/pypi/datetime_diff/
.. image:: https://img.shields.io/pypi/pyversions/datetime_diff.svg
   :target: https://pypi.python.org/pypi/datetime_diff/

The ``datetime_diff`` package provides a useful function for comparing
two different datetime objects and returns the time elapsed since.

for example, a datetime object when turned into a string (being
2015-12-03 03:34:57.281000) when compared with a new datetime object
(equivalent to the current time) one can determine how many years,
months, days, hours, minutes, and seconds ago the prior datetime object
was.

This returns the data as a string readable by humans denoting how much
time has passed since the specified prior datetime object.

```

or any links or images (badges) wont render at all on pypi but will on github. (pypi does not use github's [markup](https://github.com/github/markup) library so this is why it will not render correctly).

**Comment by jgm** [comment]
@AraHaan your comment has nothing to do with this issue (which is about lists). An issue concerning RST images should go elsewhere.  However, note that the RST pandoc produces is valid RST and renders fine using the official RST tools (e.g. rst2html.py).  The use of substitutions is necessary, in general, since images can occur in inline contexts.

**Comment by jgm** [comment]
The tricky part of this is dealing with tabs.

**Comment by vvasuki** [comment]
In addition to the four space rule problem, there is also the problematic need to necessarily have a newline before a markdown list begins - please see [second section here](https://github.com/bebraw/pypandoc/issues/143#issuecomment-319648330).

**Comment by jgm** [comment]
@vvasuki you can enable `+lists_without_preceding_blankline` if you want lists to be able to start without a blank line.

**Comment by bewuethr** [comment]
Should maybe the language in the first example in [Block content in list items](https://pandoc.org/MANUAL.html#block-content-in-list-items) be updated? While "must be indented eight spaces" is true *for the example* because the whole list is indented, it's really "must be indented four spaces more than the first non-space content after the list marker", isn't it?
