### ISSUE TITLE
EPS conversion for pdflatex by pandoc failing

### ISSUE THREAD

**Issue by didibus** [jgm/pandoc#3517]
```
[pandoc warning] Unable to convert `./plantuml-images\7c81e7c548bdf113ae42a63388580338c7252bb0.eps' for use with pdflatex.
 ! Package pdftex.def Error: File `./plantuml-images/7c81e7c548bdf113ae42a633885
 80338c7252bb0-eps-converted-to.pdf' not found.
 
 See the pdftex.def package documentation for explanation.
 Type H <return> for immediate help.
 ... 
 
 l.92 ...1e7c548bdf113ae42a63388580338c7252bb0.eps}
 pandoc: Error producing PDF
```

It appears pandoc fails to convert EPS files on Windows 7. I'm using pandoc 1.19.2.1.

The command I'm running is: `pandoc -s "doc.pmd" -o "doc.pdf"`

My pmd file contains: `![la lune](./plantuml-images\7c81e7c548bdf113ae42a63388580338c7252bb0.eps)`

**Comment by mb21** [comment]
Please post the relevant input and what pandoc version you're using. E.g. without the suffix it might work:

    ![](./plantuml-images/7c81e7c548bdf113ae42a63388580338c7252bb0)

**Comment by jgm** [comment]
Yes, try it without the extension.
The conversion is something LaTeX does, not something pandoc does, so I don't think this is a pandoc bug.

**Comment by didibus** [comment]
So, I do need to provide the extension, but for some reason, it now works.
