### ISSUE TITLE
Wrong parsing of braces in LaTeX to plaintext (exponents)

### ISSUE THREAD

**Issue by Phyks** [jgm/pandoc#3518]
Hi,

It seems Pandoc is incorrectly parsing the braces delimiting an exponent when doing a conversion from LaTeX to plaintext (unicode).

Pandoc version is 1.19.2.1 (Brew installation).

Minimal example to reproduce is:

```
$ cat test.tex
$\alpha^2 \cdot \alpha^{2+3} \equiv \alpha^7$
$ pandoc -f latex -t plain test.tex
α² ⋅ α2 + 3 ≡ α⁷
```

Which is incorrectly rendered and should be rendered as something like
```
α² ⋅ α²⁺³ ≡ α⁷
```

Thanks!

**Comment by mb21** [comment]
I don't think that we support arbitrary complex math formula in plain output...

**Comment by jgm** [comment]
Here's the basic problem.  In `plain` output we don't want to use symbols like `^` for superscript, and we can't use HTML `<sup>` tags.  So how do we represent superscript?  If the math is a sequence of one or more digits, we can use the handy unicode superscript digit characters (as you see above).  But with non-digits like `+`, we can't.

Perhaps, though, there are superscripted unicode characters for `+` and other symbols. If so, we can do better.

**Comment by jgm** [comment]
Oh yes, I see that there are more superscripted characters.  OK, will fix.

**Comment by Phyks** [comment]
@jgm Thanks a lot for the quick fix of this!

Indeed, there are a few extra superscript UTF-8 characters that Pandoc could use.

May I suggest additionnally that rather than dropping completely the exponent if no superscript characters is available, Pandoc would render with `^(…)` notation?

Typically, if one wants to convert

```
2^{\alpha}
```

Pandoc currently outputs `2α`. I would tend to think it would be better to output something like `2^(α)` so as to not break the meaning of the LaTeX input.

**Comment by jgm** [comment]
Good suggestion. I'll do that.

+++ Lucas Verney [Mar 21 17 07:20 ]:
>   May I suggest additionnally that rather than dropping completely the
>   exponent if no superscript characters is available, Pandoc would render
>   with ^(…) notation?

**Comment by Phyks** [comment]
Awesome, thanks!
