### ISSUE TITLE
Converting to PDF breaks, converting to .tex then to PDF works

### ISSUE THREAD

**Issue by hassanshaikley** [jgm/pandoc#3521]
pandoc 1.19.2.1

This command breaks:

`pandoc -f json --top-level-division=chapter  --filter=pandoc-citeproc --bibliography test/test.bib  tmp/12/pandoc.json --csl templates/chicago-fullnote-bibliography.csl --template=templates/aa/template.tex -o tmp/12/published.pdf`

But this works:

`pandoc -f json --top-level-division=chapter  --filter=pandoc-citeproc --bibliography test/test.bib  tmp/12/pandoc.json --csl templates/chicago-fullnote-bibliography.csl --template=templates/aa/template.tex -o tmp/12/published.tex`

`pandoc tmp/12/published.tex -o works.pdf`

The error I am getting on the first conversion is:

```
! LaTeX Error: File `aa.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name:
! Emergency stop.
<read *>

l.2 ^^M

pandoc: Error producing PDF
```

The template in question is: 

[https://gist.github.com/hassanshaikley/528240c6c1b40d9b54e133e6c78e4467](https://gist.github.com/hassanshaikley/528240c6c1b40d9b54e133e6c78e4467)

**Comment by jgm** [comment]
Where is aa.cls?  Do you have it in your working directory?

**Comment by hassanshaikley** [comment]
this file doesn't exist and the json->tex->pdf conversion still worked.

**Comment by mb21** [comment]
The second command (which works) simply generates the .tex file. The first generated the tex file and calls latex internally, which fails since there is no file `aa.cls`. Simply delete the line referencing `aa.cls` in your template if you don't need it...

**Comment by hassanshaikley** [comment]
Nevermind I take this back. The PDF that was produced from the ->latex->pdf conversion looked awfully wrong and was broken. I didn't realize it.
