### ISSUE TITLE
Pandoc does not recognise epigraphs from epigraph-package

### ISSUE THREAD

**Issue by trmd** [jgm/pandoc#3523]
I can successfully convert from .tex to .docx, but pandoc does not recognise or convert my epigraphs. They are simply lost.

MWE:

```
\documentclass{book}
\usepackage{epigraph}
\begin{document}

\epigraph{Das Recht hat kein Dasein f{\"u}r sich, sein Wesen vielmehr ist das Leben des Menschen selbst, von einer besonderen Seite angesehen.}{Friedrich Carl von Savigny}

\end{document}
```

And this for conversion:

`pandoc -f latex -t docx test-epigraph-conversion-pandoc.tex -o test-epigraph-conversion-pandoc.doc`

Version is: pandoc 1.19.2.1

(I have also asked about this here: http://tex.stackexchange.com/questions/357779/usepackageepigraph-with-pandoc-conversion-to-docx)

**Comment by jgm** [comment]
We could support this since it's a common package.

**Comment by trmd** [comment]
@jgm That would be great! Sorry, but I am not an able coder, so I don't think I could help.
