### ISSUE TITLE
does not convert html to docx  as below

### ISSUE THREAD

**Issue by dbissa94** [jgm/pandoc#3525]
`<!DOCTYPE html>
<html>
   <head>
      <title>Outline</title>
      <style type='text/css'>ol { font-family: verdana; font-size: 13px; } .lables { font-family: verdana; font-size: 13px;}</style>
   </head>
   <body>
      <ol style='list-style-type:upper-roman'>
         <li>
            <div>Topic</div>
            <ol style='list-style-type:upper-alpha'>
               <li>
                  <div>Subtopic</div>
                  <ol style='list-style-type:decimal'>
                     <li>
                        <div>Subtopic</div>
                        <ol style='list-style-type:lower-alpha'>
                           <li>
                              <div>Subtopic</div>
                              <ol style='list-style-type:lower-roman'>
                                 <li>
                                    <div>Subtopic</div>
                                    <ol style='list-style-type:lower-alpha'>
                                       <li>
                                          <div>Subtopic</div>
                                          <ol style='list-style-type:lower-roman'>
                                             <li>
                                                <div>Subtopic</div>
                                                <ol style='list-style-type:lower-alpha'>
                                                   <li>
                                                      <div>Subtopic</div>
                                                      <ol style='list-style-type:lower-roman'>
                                                         <li>
                                                            <div>Subtopic</div>
                                                            <ol style='list-style-type:lower-alpha'>
                                                               <li>
                                                                  <div>Subtopic</div>
                                                                  <ol style='list-style-type:lower-roman'>
                                                                     <li>
                                                                        <div>Subtopic</div>
                                                                        <ol style='list-style-type:lower-alpha'>
                                                                           <li>
                                                                              <div>Subtopic</div>
                                                                           </li>
                                                                        </ol>
                                                                     </li>
                                                                  </ol>
                                                               </li>
                                                            </ol>
                                                         </li>
                                                      </ol>
                                                   </li>
                                                </ol>
                                             </li>
                                          </ol>
                                       </li>
                                       <li>
                                          <div>Subtopic</div>
                                       </li>
                                       <li>
                                          <div>Subtopic</div>
                                       </li>
                                    </ol>
                                 </li>
                              </ol>
                           </li>
                           <li>
                              <div>Subtopic</div>
                           </li>
                        </ol>
                     </li>
                     <li>
                        <div>Subtopic</div>
                     </li>
                  </ol>
               </li>
            </ol>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
            <ol style='list-style-type:upper-alpha'>
               <li>
                  <div>Subtopic</div>
                  <ol style='list-style-type:decimal'>
                     <li>
                        <div>Subtopic</div>
                        <ol style='list-style-type:lower-alpha'>
                           <li>
                              <div>Subtopic</div>
                              <ol style='list-style-type:lower-roman'>
                                 <li>
                                    <div>Subtopic</div>
                                    <ol style='list-style-type:lower-alpha'>
                                       <li>
                                          <div>Subtopic</div>
                                          <ol style='list-style-type:lower-roman'>
                                             <li>
                                                <div>Subtopic</div>
                                             </li>
                                          </ol>
                                       </li>
                                       <li>
                                          <div>Subtopic</div>
                                       </li>
                                    </ol>
                                 </li>
                              </ol>
                           </li>
                        </ol>
                     </li>
                  </ol>
               </li>
            </ol>
         </li>
         <li>
            <div>Topic</div>
         </li>
         <li>
            <div>Topic</div>
         </li>
      </ol>
   </body>
</html>`
using pandoc version 1.19.2.1
after certain levels it fails

**Comment by mb21** [comment]
please don't open duplicate issues. see https://github.com/jgm/pandoc/issues/3519
