### ISSUE TITLE
An UTF-8 aware text processing module must be available in lua filters

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#3527]
Slnunicode seems like a good choice for unicode support, but other lua C libraries might be worth checking.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Mar 22 17 13:22 ]:
>   Slnunicode seems like a good choice for unicode support, but other lua
>   C libraries might be worth checking.

I think I've used that one before.

Do we understand why lua C modules can't be loaded from
filters, and is there any way to fix this?  Building in
a utf8 library seems a reasonable workaround, but if we're
never going to be able to load lpeg in a filter, it's
tempting to include that too...

**Comment by tarleb** [comment]
I got C modules working for linux, new hslua release is upcoming. From what I understand, mac os x and windows users should already be able to use C modules, but I wasn't able to confirm this yet. Could you verify for mac?

**Comment by jgm** [comment]
When I reported my failure, it was on a Mac.

However, I now realize that I have lua 5.2 on that machine,
so the rocks I have installed are (I assume) not available
to lua 5.1.  That may have been the issue!

+++ Albert Krewinkel [Mar 23 17 03:43 ]:

**Comment by jgm** [comment]
OK, I installed lua 5.1 and installed luautf8 rock using luarocks-5.1.  Now the filter works!  I'm sorry if I led you down the wrong track with my original report.  Benchmark on macos, using a "capitalize all strings" filter:

lua: 2.39s
python: 1.51s
no filter: 1.15s

So the lua filter is still considerably slower than the python one.  Room for improvement, anyway, but this is still completely usable, and the convenience of having the interpreter built in is great!

**Comment by jgm** [comment]
The code for caps.lua:
``` lua
local utf8 = require("lua-utf8")
return {
  { Str = function (inline)
      return pandoc.Str(utf8.upper(inline.c))
  end,
  }
}
```

**Comment by tarleb** [comment]
Happy its working :smile: It *wasn't* working correctly on linux, so I feel rather lucky that you brought it up.

The benchmark is interesting.  The script takes 0.7s on my test input, compared to 1.1s using python:

``` python
#!/usr/bin/env python3
from panflute import *

def caps(elem, doc):
    if isinstance(elem, Str):
        return Str(elem.text.upper())

if __name__ == "__main__":
    toJSONFilter(caps)
```

**Comment by tarleb** [comment]
Funny.  Tested on the MANUAL, and both take exactly the same time.  Python seems to become more efficient for longer inputs.

**Comment by jgm** [comment]
I was using pandocfilters rather than panflute -- there
may be a performance difference there as well.

**Comment by tarleb** [comment]
I have updated hslua, it now has lua 5.3 embedded per default but can still be built with LuaJIT if required. However, that next hslua version, once it is released, will have many incompatibilities compared to previous versions.  Do you prefer a conservative approach, keeping the current hslua version, or would you rather see lua 5.3 included, which has rudimentary support for UTF-8?  I'm asking so I can set priorities accordingly.

**Comment by tarleb** [comment]
The alternative being that I invest time into the `pandoc.lua` module first.
