### ISSUE TITLE
markdown_github behaves differently with UTF-8 than markdown for PDF output

### ISSUE THREAD

**Issue by RickStrahl** [jgm/pandoc#3528]
When doing a markdown conversion to PDF I see different behavior in terms of UTF 8 conversion between `-f github` and `-f markdown_github`. It looks like markdown_github is choking on Emojii expressions that generate extended ASCII characters.

The error I get:
```
inputenc Error: Unicode char ≡ƒÿä (U+1F604)
(inputenc)                not set up for use with LaTeX.
```

![image](https://cloud.githubusercontent.com/assets/1374013/24273163/04405292-0fc5-11e7-9654-59ab5b898eb1.png)

The error is caused by this markdown in the document:

```markdown
your favorite browser preview pages. :smile:
```

So this works:

```
pandoc -f markdown -s tmp802E.md -o test.pdf
pandoc -f markdown_github -s tmp802E.md -o test.html
```

this doesn't:

```
pandoc -f markdown_github -s tmp802E.md -o test.pdf
```

**Comment by mb21** [comment]
`markdown_github` includes the `emoji` extensions. which translates e.g. `:smile:` to the corresponding unicode char. That unicode char in turns is probably not supported by pdflatex. try `--latex-engine=xelatex`, see https://github.com/jgm/pandoc/issues/2523
