### ISSUE TITLE
LaTeX: Parse Label and Ref Commands

### ISSUE THREAD

**Issue by schrieveslaach** [jgm/pandoc#3538]
LaTeX provides commands for referencing sections (see following code). 

```
Section \ref{sec:Introduction} will provide…

\section{Introduction}
\label{sec:Introduction}

This is an introduction.

\section{Conclusion}

Section \ref{sec:Introduction} provided…
```

If I convert this with pandoc, pandoc will just write the label name in brackets. Is there any way that pandoc will convert the LaTeX into following markdown code?

```markdown
Section 1 will provide…

# Introduction

This is an introduction.

# Conclusion

Section 1 provided…
```

**Comment by schrieveslaach** [comment]
@jgm, I'm trying to implement the stuff, but I have no idea how to continue.

**Comment by jgm** [comment]
This one is not straightforward. One approach would be to
have the LaTeX reader implement its own version of latex's
reference and numbering system, ultimately substituting
hyperlinked numbers for the ref's and some kind of anchor
for the labels.  But LaTeX's system is pretty complicated,
actually.  (There are various numbering registers, and
which one gets picked up by a label depends in subtle
ways on its positioning.)

**Comment by schrieveslaach** [comment]
That's true, LaTeX is tricky... I'm happy to provide PR. However, I need advice.
