### ISSUE TITLE
LaTeX: Read Glossary Entries

### ISSUE THREAD

**Issue by schrieveslaach** [jgm/pandoc#3539]
In LaTeX you can use the [glossaries package](http://mirror.unl.edu/ctan/macros/latex/contrib/glossaries/glossariesbegin.pdf) providing and generating glossaries entries and using them in the text. 

```latex
\newacronym{API}{API}{Application Programming Interface}

Many programming languages provide \glspl{API}. Each \gls{API} should provide a documentation.
```

When I convert this LaTeX code with pandoc, pandoc does not print the entries. Is there any way that pandoc will convert the LaTeX into following markdown code?

```markdown
Many programming languages provide Application Programming Interfaces. Each API should provide a documentation.
```

**Comment by jgm** [comment]
We can't support every conceivable external package.
Best workaround for this is to define a macro.  E.g.
make a file extramacros.tex with

    \newcommand{\glspl}[1]{#1}

and process with

    pandoc -f latex extramacros.tex yourfile.tex

pandoc should parse the macro and resolve it.  At least
the dev version will.

**Comment by schrieveslaach** [comment]
Is there any alternative way? Filter which modify the AST?

**Comment by schrieveslaach** [comment]
@jgm, any ideas for a workaround?

**Comment by schrieveslaach** [comment]
Do you think that pandoc could integrate the behaviour you mentioned (see your example with extra macros). I tried that in an extra [branch](https://github.com/schrieveslaach/pandoc/tree/glossaries-package). What do you think? With this approach pandoc could support similar package, like [acronym](https://www.ctan.org/pkg/acronym).

**Comment by schrieveslaach** [comment]
Is this issue still a closing candidate?
