### ISSUE TITLE
html input nested lists don't produce tex nested lists

### ISSUE THREAD

**Issue by sarnobat** [jgm/pandoc#3541]
**Test case**
Please execute this from the command line

```
pandoc --standalone  <<EOF  -o "output.tex"
<html>
<head></head>
<body>
<ul>
  <li> first bullet</li>
  <li> second bullet
  <ul>
    <li> nested bullet</li>
  </ul>
  </li>
</ul>
</body>
</html>
EOF

```
**Actual Output**

```
first bullet

second bullet

nested bullet
```

In more complex situations (which I cannot determine the root reason for the discrepancy), I get one level of nesting but it's still not correct:

```
first bullet

second bullet

\begin{itemize}
\item nested bullet
\end{itemize}

```

**Expected Output**

first bullet

second bullet
```

\begin{itemize}
\item first bullet
\item second bullet
\begin{itemize}
\item nested bullet
\end{itemize}
\end{itemize}
```

**Version info**

```
pandoc 1.11.1
Compiled with citeproc-hs 0.3.8, texmath 0.6.1.5, highlighting-kate 0.5.5.
```

and also on:

```
pandoc 1.15.1
Compiled with texmath 0.8.4, highlighting-kate 0.6.
```

**Remarks**

I love pandoc, it's perfect for my data needs otherwise.

**Comment by jgm** [comment]
Try adding `-f html` to your command line so pandoc knows it's HTML.
When you use a file argument, it can infer this from the extension, but not when you use stdin.

**Comment by sarnobat** [comment]
Ok my test case didn't reproduce my original issue where I was indeed using `-f html`.

But in any case I found a workaround of converting first to markdown, and then to html. So I'm closing this

**Comment by jgm** [comment]
With `-f html -t latex`, do you not get
```
\begin{itemize}
\tightlist
\item
  first bullet
\item
  second bullet

  \begin{itemize}
  \tightlist
  \item
    nested bullet
  \end{itemize}
\end{itemize}
```
So no workaround should be needed.  (Oh, I just noticed that both versions of pandoc you tested with are quite old.  I would recommend upgrading to the latest release.)

**Comment by sarnobat** [comment]
It works even without any workarounds on my old version now. I'm not sure what bizarre steps I was taking that originally caused the reported output but probably I was not using pandoc correctly as a rookie.

FYI - my original goal was to convert mediawiki to a latex pdf. Maybe using html as an intermediate was introducing something unexpected. If I re-encounter it I'll follow up here. 

Thanks again for designing pandoc so well. Piping input and output is good unix philosophy. If only latex was done this way too...
