### ISSUE TITLE
reformatting this line is not idempotent

### ISSUE THREAD

**Issue by alok** [jgm/pandoc#3542]
The line that gave this 
```
-   [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa - aaaaa](http://aaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
```

if you run `pandoc -f markdown -t markdown`repeatedly, you get:

```
-   [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -
    aaaaa](http://aaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
```

```
-   [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    -
    aaaaa](http://aaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
```

```
-   \[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    ---------------------------------------------------------------------

    aaaaa\](http://aaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
```

I'm not sure if running the markdown formatter this way is even *supposed* to be idempotent, but I thought I'd bring it to your attention.

**Comment by jgm** [comment]
The problem is that the word-wrapping in the second sample creates a setext header.
Perhaps we could solve this by escaping hyphens at the beginning of a line.

**Comment by jgm** [comment]
Honestly, I'm not sure it's worth doing something about this.  It's a very special case that will come up very, very rarely.  If the cost of dealing with it is littering regular markdown documents with unnecessary backslashes, it may not be worth it.
