### ISSUE TITLE
Error running filter createProcess: invalid argument (Exec format error) 

### ISSUE THREAD

**Issue by didibus** [jgm/pandoc#3543]
Pandoc version 1.19.2.1
on Windows 7

If I use a python (*.py) filter that is on the path `--filter raw.py`, I get error:

```
pandoc exited with code 83: pandoc: Error running filter raw.py 
raw.py: createProcess: invalid argument (Exec format error) 
```

If I move the .py file in my directory, and use: `--filter ./raw.py`, then it all works.

Using a .bat file does not work correctly for all filters, so that solution isn't ideal.

As an example, when using a cmd bat file for one of my filters I get:

```
pandoc exited with code 83: pandoc: Error running filter imgvars.cmd 
Error in $: Failed reading: not a valid json value 
CallStack (from HasCallStack): 
error, called at pandoc.hs:144:42 in main:Main 
```

**Comment by jgm** [comment]
Can this be reproduced on 2.7.x?
If not, we should close.

**Comment by didibus** [comment]
I've lost the context in which this error was happening, so I don't know if it would still repro today unfortunately. You should probably close it, if someone else has the problem again, they could re-open or create a new issue where they'd be able to dive deeper into it.
