### ISSUE TITLE
Change the default MathJax URL since MathJax CDN is going to shut down

### ISSUE THREAD

**Issue by Mushiyo** [jgm/pandoc#3544]
As the [announcement](https://www.mathjax.org/cdn-shutting-down/) on the MathJax website states, MathJax CDN will no longer work after April 30, 2017.  
This will cause the `--mathjax` option not working when no URL is provided since Pandoc uses MathJax CDN as the default MathJax URL currently.

**Comment by mb21** [comment]
They recommend using cdnjs:

    https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js
