### ISSUE TITLE
Table style other than TableNormal for DOCX

### ISSUE THREAD

**Issue by tinselspoon** [jgm/pandoc#3546]
Pandoc generates all tables with the table style set to `TableNormal`. Unfortunately, Word does not permit changing the `TableNormal` style in the UI. The only way of modifying it is to hack the `styles.xml` within the generated or reference docx, but any changes to this style are reverted when you open the document in Word and save again, so its not a long-term fix.

The effect of this is that the table appearance cannot be styled via the reference docx by default. Could Pandoc use an alternative table style instead? This could be similar to how the reference docx already defines a number of styles like `Source Code`, `First Paragraph`, etc and Pandoc uses these during generation -- could a `Default Table` style be added to this set?

**Comment by jgm** [comment]
Dup of #3275
