### ISSUE TITLE
Support \texorpdfstring in headers for PDF bookmarks

### ISSUE THREAD

**Issue by priiduonu** [jgm/pandoc#3555]
As PDF bookmarks can only contain plain text, a \texorpdfstring macro is normally used to provide the plain text alternative for PDF bookmarks:

https://en.wikibooks.org/wiki/LaTeX/Hyperlinks#Problems_with_bookmarks

Say we have the following header in MarkDown document:

`## The equation \texorpdfstring{$E=mc^2$}{E=mc2}`

The expected result in PDF bookmark would be:

`The equation E=mc2`

The actual result is:

`The equation `

So the \texorpdfstring part is completely ignored.

When the header is written in raw TeX:

`\section{The equation \texorpdfstring{$E=mc^2$}{E=mc2}}`

The PDF bookmark is displayed correctly.

Note that the header itself is rendered correctly in PDF file.

**Comment by jgm** [comment]
Consider also
```
% pandoc -t latex
## Equation $e=mc^2$
\hypertarget{equation-emc2}{%
\subsection{\texorpdfstring{Equation
\(e=mc^2\)}{Equation e=mc\^{}2}}\label{equation-emc2}}
```

Here it doesn't disappear, but I'm not sure the `\^{}` is desirable.

**Comment by priiduonu** [comment]
Thanks, it seems that my initial example (inline math) would render almost correctly, if I omit the \texorpdfstring and use just:

`## Equation $E=mc^2$`

The resulting PDF bookmark is:

`Equation E=mc^2`

Which is good enough.

But consider the following example:

`## Testing \LaTeX\ logo in header`

The resulting PDF bookmark lacks the word "LaTeX". Again, the header itself is rendered correctly.

I'm preprocessing the .md file before converting it with pandoc and converted it to:

`## Testing \texorpdfstring{\LaTeX}{LaTeX} logo in header`

with no success - the resulting PDF bookmark reads:

`Testing logo in header`

**Comment by tolot27** [comment]
`\LaTeX` is a latex command. Hence, it gets removed during translation to the `\texordpdfstring{}{}`. The only way to avoid this is to use a white list table which maps certain commands to its plain text form.
