### ISSUE TITLE
failed to convert a latex equation (in a list) when the equation has a line starting with *

### ISSUE THREAD

**Issue by irhawks** [jgm/pandoc#3557]
Environment:  pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.5

When I typed texts with

```markdown
* matrix
$\begin{matrix}
  a & *\\
  * & b
\end{matrix}$
```
and convert it with `pandoc -f markdown+tex_math_single_backslash -t latex filename`, I got result

```latex
\begin{itemize}
\tightlist
\item
  matrix \$\textbackslash{}begin\{matrix\} a \& *\textbackslash{}
\item
  \& b \textbackslash{}end\{matrix\}\$
\end{itemize}
```
If there is a `*` in the first column of the matrix, pandoc will parse `*` as an indicator of starting a new item. This can be fixed with avoiding `*` appearing right after a new line. (e.g. merging it with the previous line). But is this a bug in parsing latex inline/display math environment?

B.T.W:

```markdown
* matrix
\(\begin{matrix}
  a & *\\
  * & b
\end{matrix}\)
```

```markdown
* matrix
\[\begin{matrix}
  a & *\\
  * & b
\end{matrix}\]
```
will get the same result. (with `pandoc -t markdown+tex_math_single_backslash`)

**Comment by jgm** [comment]
Pandoc chunks out the list items before parsing their
contents.  In this case the line `* & b` gets treated
as a separate list item, and that's the issue.
I don't think it's a bug.

One workaround would be to enclose this `*` in braces:

    {*} & b
