### ISSUE TITLE
Support LaTeX \figurename, \tablename and \lstlistingname via localization system

### ISSUE THREAD

**Issue by schrieveslaach** [jgm/pandoc#3559]
LaTeX provides placeholders to reference figures, tables and listings. See example below

```latex
\figurename \ref{fig} depicts… 

\tablename \ref{table} shows… 

\lstlistingname \ref{listing} define… 
```

Pandoc should replace these command with the default values, for example: 

```html
<p>Figure [fig] depicts…</p>
<p>Table [table] shows…</p>
<p>Listing [listing] define…</p>
```

Additionally, it would be nice if pandoc solves #3538 in this example as well. 😉

**Comment by jgm** [comment]
I have reservations about replacing these with English strings, since many people write in other languages.

**Comment by schrieveslaach** [comment]
What do you think if you can configure this with command line options? For example, with `--metadata=KEY[:VALUE]`

**Comment by jgm** [comment]
Another option would be building the localization into pandoc.

We could borrow from LaTeX. On my system,

    % ls /usr/local/texlive/2016basic/texmf-dist/tex/latex/polyglossia/gloss-*

gives the data for a lot of languages, and this could be extracted programatically.

We'd have to think a bit about how to do this in a clean way.  We'd probably want a separate localizations module with data files.

**Comment by mb21** [comment]
Was this meant to be closed?

**Comment by jgm** [comment]
```
for x in /usr/local/texlive/2016/texmf-dist/tex/latex/polyglossia/*.ldf; do sed -n '/^\\def\\captions/,/^ *}/p' $x; done > captions.tex
```
extracts the data.

We could put this in data files (YAML, JSON?), and allow all of this to be overridden in metadata in the following way.
```
localizations:
  references:  My References
```

**Comment by jgm** [comment]
Localization system could also encompass smart quotes: #2620.

**Comment by jgm** [comment]
Alternatively, we could use
```
kpsewhich gloss-occitan.ldf
```
to find the file on the host system and parse it, making use of the existing TeX installation and avoiding the need to store data files in pandoc.

**Comment by jgm** [comment]
An architectural suggestion.  We could include `getTranslation` in `PandocMonad`.
```
getTranslation :: Lang -> String -> m (Maybe String)
```
This could then be used in all the readers.  IT could issue a warning when a translation is not available.

That leaves the question how to get the translations.

**Comment by mb21** [comment]
Not sure that it's a good idea to rely on `kpsewhich` and third-party files. People will report wrong translations to pandoc if they use an outdated TeX distribution. Plus what if we want to use translations in HTML export on a system with no installed TeX? Better to periodically parse and convert the LaTeX language files to JSON/YAML, then ship those as part of pandoc.

I like the idea of `getTranslation` though...

**Comment by jgm** [comment]
TODO
- [ ] support `\partname`, etc.  Currently we only have `\figurename` for testing.
- [ ] add more translation files
- [ ] documentation
- [ ] other places, besides LaTeX reader, where this is useful?

**Comment by mb21** [comment]
We should probably at least add some documentation... and modify the docx writer to use the translations figure labels etc? Should I open an issue for that?

**Comment by jgm** [comment]
Sure, go ahead and open an issue.
