### ISSUE TITLE
[Request] Option to treat single new line as new paragraph

### ISSUE THREAD

**Issue by rafal-adamek** [jgm/pandoc#3561]
As we know, Markdown uses an empty line to break to a new paragraph. Many editors however, offer the option to have a new paragraph as a single new line. Would it be possible to offer an option for that in Pandoc?

I just recently switched to Pandoc and have a very large number of files that used a single new line as a new paragraph. Would it be much work to implement such an optional mechanism?

**Comment by jgm** [comment]
It would be possible, yes.  But it would amount to the creation of yet another incompatible Markdown dialect.  I'm not inclined to do it.

You could do the conversion by turning on the `hard_line_breaks` option and writing a filter that splits paragraphs into multiple paragraphs on LineBreak elements.  (Assuming that these are Markdown files in every other respect...)

**Comment by rafal-adamek** [comment]
Thank you for your anwer. Using the hard_line_breaks flags helps in this particular scenerio. Although I would still love the option for new paragraphs on new lines but I understand your reasoning. There are already so many different markdown flavors. But I don't think more options to the great tool the Pandoc is would hurt it. I will close the issue then.
