### ISSUE TITLE
latex->slidy changed behaviour from 1.17.2 to 1.18 - subsection names in TOC missing (replaced by just numbers)

### ISSUE THREAD

**Issue by jwaldmann** [jgm/pandoc#3566]
```
echo "\\documentclass{article}\\begin{document}\\section{Bar}\\subsection{Foo}\\end{document}" |  pandoc --from latex --to slidy  --slide-level=2 -s
```

With pandoc-1.17.2, I get output ending with
```
<body>
<div id="bar" class="titleslide slide section level1"><h1>Bar</h1></div>
<div id="foo" class="slide section level2"><h1>Foo</h1></div>
</body>
</html>
```
and it renders fine.

When I do this with pandoc-1.18 and  1.19.2.1, I get output ending with
```
<body>
<div id="bar" class="titleslide slide section level1"><h1>Bar</h1></div>
<div id="foo" class="slide section level2"><h2>Foo</h2></div>
</body>
</html>
```
(h1 changed to h2 in second div)
For that, the table-of-contents does not show the name of the subsection. Instead, it shows number of slide in parentheses.

But I do want two levels of headings in the TOC. Old output rendered section headings in bold slanted font, and subsection headings in plain upright font.

Version info:
```
andoc 1.17.2
Compiled with texmath 0.8.6.7, highlighting-kate 0.6.4.

pandoc 1.18
Compiled with pandoc-types 1.17.0.5, texmath 0.8.6.7, highlighting-kate 0.6.4
```

**Comment by mb21** [comment]
What do you mean with "subsection names in TOC missing (replaced by just numbers)"? From reading your text it seems the `h1` was changed to `h2` for subsections in the TOC which is desired... so what's the problem?

**Comment by jgm** [comment]
This change was made in response to #2221.  See that issue for the motivation.
It's possible that this change isn't working well with slidy, but I'm not sure I understand from the above message what the issue is.

**Comment by jwaldmann** [comment]
example (click on "contents" to see the TOC pop-up)

* old (shows subsection names) https://www.imn.htwk-leipzig.de/~waldmann/edu/ss17/ad/folien/index.html
* new (shows numbers instead) https://www.imn.htwk-leipzig.de/~waldmann/edu/ss17/ad/folien/index-1.19.2.1.html

this may indeed be a problem with slidy, not with pandoc.

**Comment by EdwardMorehouse** [comment]
This change is biting me as well, my Slidy presentations now all have useless tables of contents.  I appreciate the tension with #2221, but would like to find a solution.  It appears that Slidy is no longer being developed, does anyone know of a work-around?

**Comment by jwaldmann** [comment]
Thanks! patched version works as expected.

**Comment by EdwardMorehouse** [comment]
Thank you @jgm !
