### ISSUE TITLE
man writer creates incorrect output for nested formatting

### ISSUE THREAD

**Issue by magicus** [jgm/pandoc#3568]
The man writes creates incorrect output for nested formatting. The code assumes that \f[] works like a "pop" on the formatting stack, but that is not the case -- it just goes back to the previous format. Also, it's not possible to nest \f arguments like \f[B]\f[I], instead this must be expressed as a single \f[BI].

I've reproduced this on pandoc 1.19.2.1, but judging from the code on Github this goes way back to the beginning.

Example: 
```
$ cat man-formatting-bug.md
normal *italic **bold in the middle** only italic* normal.

normal **bold `code` more bold** normal.

normal `code` normal.

$ pandoc -s -t man man-formatting-bug.md
.\" Automatically generated by Pandoc 1.19.2.1
.\"
.TH "" "" "" "" ""
.hy
.PP
normal \f[I]italic \f[B]bold in the middle\f[] only italic\f[] normal.
.PP
normal \f[B]bold \f[C]code\f[] more bold\f[] normal.
.PP
normal \f[C]code\f[] normal.
```

Expected output:
```
.\" Automatically generated by Pandoc 1.19.2.1
.\"
.TH "" "" "" "" ""
.hy
.PP
normal \f[I]italic \f[BI]bold in the middle\f[I] only italic\f[R] normal.
.PP
normal \f[B]bold \f[CB]code\f[B] more bold\f[R] normal.
.PP
normal \f[C]code\f[R] normal.
```

The esiest way to see how the pandoc output is parsed by man is to let man convert it to html:
```
$ pandoc -s -t man  man-formatting-bug.md  | man -Thtml -l -
... snip ...
<p style="margin-left:11%; margin-top: 1em">normal
<i>italic</i> <b>bold in the middle</b> <i>only italic</i>
<b>normal.</b></p>
.... snip ...
```

**Comment by jgm** [comment]
Yes.  I realized this recently when I wrote the groff ms writer, which started out as a modification of the man writer code.  The ms writer does this correctly.  It's just a matter of porting these parts of the code from the ms writer back to the man writer.
