### ISSUE TITLE
autolink_bare_uris extension incorrectly parses `Notes:` as URI

### ISSUE THREAD

**Issue by alexivkin** [jgm/pandoc#3570]
-f markdown+autolink_bare_uris
on 
```
# Header

**Notes:**

blah
```
Produces
```
Header
======

\*\*<Notes:**>

blah
```

Expected result, same as running -f markdown
```
Header
======

**Notes:**

blah
```
pandoc 2.0 Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.5

**Comment by mb21** [comment]
The issue is that `Notes:` is recognized as a URL, just as `http:` would.

    echo '**Notes:**' | pandoc -f markdown+autolink_bare_uris -t native
    [Para [Str "**",Link ("",[],[]) [Str "Notes:**"] ("Notes:**","")]]

Not sure whether we can avoid false positives like this one easily...

**Comment by alexivkin** [comment]
Thanks. I guess autolink should follow URL defs - "Notes:" is not a URL string by any existing RFC. 
I'll avoid using the colon for now ;)

**Comment by mb21** [comment]
For some reason, `notes` is one of the [URI schemes pandoc recognizes](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Parsing.hs#L436)...

**Comment by alexivkin** [comment]
Probably because of lotus notes. Still, a proper URI should have double slashes following the colon.

**Comment by jgm** [comment]
We're using a function from Network.URI to recognize URLs.
We may need to add some additional rules to rule out obvious
junk like this!

**Comment by jgm** [comment]
See the link in the code comments, and
https://www.iana.org/assignments/uri-schemes/prov/notes

**Comment by jgm** [comment]
mailto: URI don't have double slashes, and I'm sure there
are other exceptions too.

+++ Alex Ivkin [Apr 14 17 07:03 ]:
>   Probably because of lotus notes. Still, a proper URI should have double
>   slashes following the colon.
