### ISSUE TITLE
org-mode-reader: markup like bold/italic at beginning of a footnote isn't converted

### ISSUE THREAD

**Issue by kiuuik** [jgm/pandoc#3576]
I tested with 1.17.0.3 from the fedora repo and the compiled version of 1.19.2.1 from github.

This is the input org-mode file:
```
text [fn:1] text [fn:2] text [fn:3] text [fn:4] text [fn:5] text [fn:6]

\\

[fn:1] /person/ writes.
[fn:2] a /person/ writes.
[fn:3]  /person/ writes.

[fn:4] *person* writes.
[fn:5] a *person* writes.
[fn:6]  *person* writes.

```
&nbsp;

about org-mode-syntax: The first three footnotes should include italic text (`/italic/`), fn4-6 bold text (`*bold*`).

The footnotes don't violate any rule of the org-mode syntax, see [here](http://orgmode.org/worg/dev/org-syntax.html#Footnote_Definitions).

With pandoc I converted to different formats like md, pdf, docx or html but the italic and bold part are not converted if the formatted character is at the beginning of the footnote. Only fn2 and fn5 look as expected.

&nbsp;

Here is the ouput in md. I ran `pandoc -f org -t markdown -o test.md test.org`:

```
text [^1] text [^2] text [^3] text [^4] text [^5] text [^6] 

\

[^1]: /person/ writes.

[^2]: a *person* writes.

[^3]: /person/ writes.

[^4]: \*person\* writes.

[^5]: a **person** writes.

[^6]: \*person\* writes.

```

&nbsp;

emacs org-mode exports the text as desired. Here is the html output just for the the first three footnotes with italics (emacs version 25.1.1 and org-mode version 9.0.5)

```
<div class="footdef"><sup><a id="fn.1" class="footnum" href="#fnr.1">1</a></sup> <div class="footpara"><p class="footpara">
<i>person</i> writes.
</p></div></div>

<div class="footdef"><sup><a id="fn.2" class="footnum" href="#fnr.2">2</a></sup> <div class="footpara"><p class="footpara">
a <i>person</i> writes.
</p></div></div>

<div class="footdef"><sup><a id="fn.3" class="footnum" href="#fnr.3">3</a></sup> <div class="footpara"><p class="footpara">
<i>person</i> writes.
</p></div></div>
```
&nbsp;

Here is the output from pandoc:

```
<ol>
<li id="fn1"><p>/person/ writes.<a href="#fnref1">↩</a></p></li>
<li id="fn2"><p>a <em>person</em> writes.<a href="#fnref2">↩</a></p></li>
<li id="fn3"><p>/person/ writes.<a href="#fnref3">↩</a></p></li>
</ol>
```

**Comment by tarleb** [comment]
Excellent report, thanks.
