### ISSUE TITLE
LaTeX: Support for Subfigure Package

### ISSUE THREAD

**Issue by schrieveslaach** [jgm/pandoc#3577]
Many scientific papers include subfigures. For example:

```latex
\begin{figure}[ht]
    \begin{subfigure}{0.45\textwidth}
        \includegraphics{img1.jpg}
        \caption{Catpion 1}
    \end{subfigure}
    
    \begin{subfigure}{0.45\textwidth}
        \includegraphics{img2.jpg}
        \caption{Catpion 2}
    \end{subfigure}
    \caption{Subfigure with Subfloat}
\end{figure}
```

Pandoc should produces two figures nested in a outer figure. 

```html
<figure>
<figure>
<img src="img1.jpg" alt="Catpion 1" /><figcaption>Catpion 1</figcaption>
</figure>
<figure>
<img src="img2.jpg" alt="Catpion 2" /><figcaption>Catpion 2</figcaption>
</figure>
<figcaption>Subfigure with Subfloat</figcaption>
</figure>
```

**Comment by jgm** [comment]
Pandoc's internal document model doesn't currently have a dedicated block element for figures.  We use the hack of treating images that are by themselves in a paragraph, with a title beginning `fig:`, as figures.

Going forward it would be good to have a dedicated Figure block element.  See #3177.

Without better support for figures in the AST, the best we could do with subfigures would be to parse them as a sequence of figures.

**Comment by schrieveslaach** [comment]
Thanks for the clarification. Currently, a sequence of figures is sufficient for my needs. I assume, that you are already working on this?

I'm trying to fix the caption problem. I think it has something to do with the `setCaption` and `resetCaption` and `addImageCaption`. In an imperative programming language I would use a stack to solve this. Do you have any ideas to solve this in haskell?

**Comment by tarleb** [comment]
Sorry, typo in commit.

**Comment by jgm** [comment]
> I'm trying to fix the caption problem. I think it has something to do with the setCaption and resetCaption and addImageCaption. In an imperative programming language I would use a stack to solve this. Do you have any ideas to solve this in haskell?

@schrieveslaach What currently happens with the above example when you run the code in your PR?
Just eyeballing it, I don't see why captions would be messed up.

**Comment by schrieveslaach** [comment]
The outer caption will be used twice:

```html
<figure>
<img src="img1.jpg" alt="Subfigure with Subfloat" /><figcaption>Subfigure with Subfloat</figcaption>
</figure>
<figure>
<img src="img2.jpg" alt="Subfigure with Subfloat" /><figcaption>Subfigure with Subfloat</figcaption>
</figure>
```

I would expect at least following output. 

```html
<figure>
<img src="img1.jpg" alt="Subfigure with Subfloat" /><figcaption>Caption 1</figcaption>
</figure>
<figure>
<img src="img2.jpg" alt="Subfigure with Subfloat" /><figcaption>Caption 2</figcaption>
</figure>
```

Ideally, the third caption should be placed below:

```html
<figure>
<img src="img1.jpg" alt="Subfigure with Subfloat" /><figcaption>Caption 1</figcaption>
</figure>
<figure>
<img src="img2.jpg" alt="Subfigure with Subfloat" /><figcaption>Caption 2</figcaption>
</figure>
<figcaption>Subfigure with Subfloat</figcaption>
```

**Comment by jgm** [comment]
I found a solution.
