### ISSUE TITLE
org-mode-reader: markup that emacs org-mode (>= 8.3) recognizes in front of footnotes is not detected in pandoc

### ISSUE THREAD

**Issue by kiuuik** [jgm/pandoc#3581]
I tested with the compiled version of 1.19.2.1 from github.

This is the input org-mode file:

``` 
this is /italic/[fn:1] this is not.
\\
this is *bold*[fn:2] this is not.

[fn:1] some text
[fn:2] some text
```
&nbsp;
Here is the ouput in md. I ran `pandoc -f org -t markdown -o test.md test.org`:

``` 
this is /italic/[^1] this is not.\
this is \*bold\*[^2] this is not.

[^1]: some text

[^2]: some text
``` 

The problem: Pandoc doesn't recognize my text as bold or italic. I tried to export to md (shown above) and pdf.

But org-mode versions (starting from 8.3 from 201508) recognize my italic and bold text because of the emacs variable org-emphasis-regexp-components, see [line 4363 of the most recent version of org.el](http://orgmode.org/w/org-mode.git?p=org-mode.git;a=blob;f=lisp/org.el;h=236813f2468053f37889f2fa33137bcda408dce8;hb=HEAD#l4363). I think before org-mode 8.3 this wasn't recognized as text markup because the variable didn't contain "[". The behavior of org.el was deliberately changed in [201406](http://orgmode.org/w/org-mode.git?p=org-mode.git;a=commit;h=518b60aa4274025a7e8fe76b4a49051852bfcf74).

I think the new behaviour is very sensible. In German academic texts names of authors are sometimes set in italic and a footnote is right next to the name. 

Admittedly the new behaviour is somewhat at odds with the draft [Org Syntax document](http://orgmode.org/worg/dev/org-syntax.html#Emphasis_Markers). This document states the following structure for text markup: "PRE MARKER CONTENTS MARKER POST". In my example there is a "[" after the second MARKER (`/` and `*`) which is not in the list of POST characters. The document states: "POST is a whitespace character, -, ., ~,~, :, !, ?, ~’~, ), } or a double quote. It can also be an end of line."

**Comment by tarleb** [comment]
Thanks for the report. Fixed in 464db59394e5ff0e366e1dab40c3edbf7ea32dac
