### ISSUE TITLE
Dead Link in http://pandoc.org/epub.html

### ISSUE THREAD

**Issue by Wabuo** [jgm/pandoc#3583]
In the [Creating an ebook with pandoc](http://pandoc.org/epub.html) guide is this dead link: [User’s Guide](http://pandoc.org/README#epub-metadata).

**Comment by jgm** [comment]
Thanks for reporting!  For future reference, there's a separate repository for the website
jgm/pandoc-website

**Comment by Wabuo** [comment]
Sorry I did look for such a repository but obviously I failed ... guess I'm getting blind.

Should I copy and paste this issue?

**Comment by jgm** [comment]
+++ Wabuo [Apr 17 17 07:22 ]:
>   Should I copy and paste this issue?

No worries, it can stay here.
