### ISSUE TITLE
docx reader: list continuation paragraphs

### ISSUE THREAD

**Issue by zlolik** [jgm/pandoc#3590]
I am writing instructions in docx and publish them in local Gitlab. It has almost Github rules https://github.com/gitlabhq/gitlabhq/blob/master/doc/user/markdown.md#links
Issue have been checked with 2 versions on windows: 1.17.2 and 1.19.2.1.
Simple example: [short.instruction.docx](https://github.com/jgm/pandoc/files/932395/short.instruction.docx)
 Converting line:
```sh
pandoc -s --toc -w markdown_github+backtick_code_blocks-link_attributes-raw_html -o short.instruction.md short.instruction.docx
```
**Expected:**
```md
-   [Installing](#installing)

Installing  
----------
1.  Download installer file  
    > You can download it [*locally*](file:///\\local) or from [*producer site*](https://github.com/producer)  
2.  Use stable version v2.3  
    Do not use latest version. Producer has not closed an [*issue 534*](https://github.com/producer/issue534) – performance degradation.  
3.  Select option 1 and option 2 and press Next:  
    **Here was an image**  
    Image 1 – Installer options  
4.  Choose custom destination folder:
```
**Actually:**
```md
-   [Installing](#installing)

Installing
----------

1.  Download installer file

> You can download it [*locally*](file:///\\local) or from [*producer site*](https://github.com/producer)

1.  Use stable version v2.3

Do not use latest version. Producer has not closed an [*issue 534*](https://github.com/producer/issue534) – performance degradation.

1.  Select option 1 and option 2 and press Next:

**Here was an image**

Image 1 – Installer options

1.  Choose custom destination folder:
```

**Comment by jgm** [comment]
@jkr any thoughts on this?  What is the right way to create list continuation paragraphs in Word that pandoc will recognize as such?

**Comment by jkr** [comment]
It's some mod key + return, I think. (Maybe shift?) I'll take a look when I get to a computer with Word on it in the next day or two.

**Comment by zlolik** [comment]
I have checked. With Shift+Enter:
1. list continuation paragraphs works ok
2. no 2 spaces at line ends
3. Word interpret lines as single paragraph, so:
    - you can not use different align for different lines (left and center, see example docx file)  
    - you can not end paragraph without empty line after it
```
-   [Installing](#installing)

Installing
----------

1.  Download installer file
    You can download it [*locally*](file:///\\local) or from [*producer site*](https://github.com/producer)

2.  Use stable version v2.3
    Do not use latest version. Producer has not closed an [*issue 534*](https://github.com/producer/issue534) – performance degradation.

3.  Select option 1 and option 2 and press Next:
    **Here was an image
    **Image 1 – Installer options

4.  Choose custom destination folder:
```

**Comment by danse** [comment]
is there anything to change in pandoc due to this issue report? it seems to me that when list items are entered correctly they also get correctly converted, righ?

**Comment by zlolik** [comment]
@danse I have tested pandoc 2.1.3 with [list.continuation.paragraphs.test.docx](https://github.com/jgm/pandoc/files/2019234/list.continuation.paragraphs.test.docx)
It seems Shift-Enter is enough to solve issue, so I close it.
Empty lines are produced after each list item even with usual list so it can be different issue but not for me.
