### ISSUE TITLE
Underscores in image filename incorrectly escaped in LaTeX output

### ISSUE THREAD

**Issue by klpn** [jgm/pandoc#3591]
I have a presentation with the logo filename given in the YAML metadata block in the markdown source as  `logo: slu_logo_cmyk`. When I make a LaTeX file to be compiled into a Beamer PDF with `pandoc -t beamer -o arkpres.tex arkpres.md --latex-engine=lualatex --template=default.beamer -N`, the underscores in the filename are escaped in the LaTeX output, so that the LaTeX compilation fails with `LaTeX Error: File 'slu\TU\textunderscorelogo\TU\textunderscorecmyk' not found` (the same error occurs if I try to make a PDF directly with Pandoc). If the file is moved to `slu-logo-cmyk.eps` (and the metadata changed accordingly, of course), the presentation compiles correctly. I have encountered this problem using Pandoc 1.19.2.1 under Windows 10/Cygwin.

**Comment by jgm** [comment]
This is essentially the issue in #2139 -- what you'd like here is a metadata field that is treated as raw LaTeX, but the fields are interpreted as Markdown (so the `_` is escaped in LaTeX output).

You could make this work by defining

    \newcommand{\dummy}[1]{#1}

at the beginning of your template and then using

    \dummy{my_file_name}

in the metadata field. This will be treated as raw LaTeX.  (But of course, it will only work for LaTeX/PDF output.)

When #2139 is fixed we'll have a better solution.
