### ISSUE TITLE
No error on missing source/input file

### ISSUE THREAD

**Issue by GiantCrocodile** [jgm/pandoc#3592]
If you don't provide source/input file you will get no error but an endless running pandoc. This is a case of bad usability.

**Comment by crmackay** [comment]
if no input file is provided pandoc waits for text from `stdin` 

```
$ cat test.md | pandoc -t latex
```

**Comment by GiantCrocodile** [comment]
Fair enough - though it is quite uncommon under Windows. Maybe we should have a warning/info that it listens at stdin for input. Happened to me as a newbie multiple times now, that I just forgot to add input file ...

**Comment by jgm** [comment]
pandoc can act like a pipe, like many unix programs.  Windows users sometimes get confused, but this is explained in the documentation.  Adding a message that appears every time you run pandoc as a pipe would also be un-unixy, so I'm just going to close this.
