### ISSUE TITLE
YAML header options applied inconsistently

### ISSUE THREAD

**Issue by ChrisPenner** [jgm/pandoc#3595]
On pandoc 1.19.2.1,

I find it very confusing that certain cmd-line options can be set in the yaml header whereas others cannot; In my case I'm rendering a markdown file into revealjs slides;

`pandoc -t revealjs  slides.md -o slides.html --self-contained -V theme=moon --highlight-style=tango`

works fine; but if I move some options to the yaml header of slides.md:

```yaml
---
theme: moon
highlight-style: tango
self-contained: true
---
```

Then only `theme: moon` takes effect; It seems as though perhaps only variables used in the pandoc template take effect? Even if there is some rhyme or reason to which options this works for it's very confusing from a usability perspective, it would be nice if all command line options could be specified in the yaml block and you could just run a simple `pandoc filename` without needing to remember which options you used last time.

Cheers!

**Comment by jgm** [comment]
Yes, some of the command line options just set variables; these can be set also in metadata.  Other command line options do other things---for example, `self-contained` causes the HTML output to be put through a function that makes it self-contained.

It's a common request to be able to specify options consistently in metadata (search this tracker).

However, I'm not sure this really makes sense in general.  For example, we have to know what the input format is before we read the metadata at all (it has to be Markdown with the `yaml_metadata` extension enabled).  Indeed, no options that affect parsing could sensibly be specified in metadata, which must be parsed and may occur anywhere in the document.  So I don't think there's any good way to allow all options to be specified.

I just use Makefiles.  In your case, just create a `Makefile` with

```
slides.html: slides.md
<TAB>    pandoc $< -o $@ -s -t revealjs -Vtheme=moon --highlight-style=tango --self-contained
```
Then, to rebuild your slides, you just type `make`.  When you come back to this months later, you don't have to remember what commands you used.
