### ISSUE TITLE
Pipe character not escaped

### ISSUE THREAD

**Issue by rmaicle** [jgm/pandoc#3599]
I tried converting the git manual documentation to gfm and encountered the option in the git-add.txt is not "escaped" and was being rendered as a table in Jekyll.

I used the following commands:

```
asciidoc -b docbook -o tmp.xml "$1".txt
pandoc -f docbook -t markdown_github+blank_before_header+all_symbols_escapable+blank_before_blockquote+definition_lists+fenced_code_blocks+footnotes+pipe_tables+yaml_metadata_block tmp.xml -o "$filename"
```

I don't even know if this is a valid issue for pandoc but just in case.

**Comment by mb21** [comment]
Can you give a minimal example?

**Comment by jgm** [comment]
I believe this was already fixed in connection with #3497.
See test/command/3497.md, last test case.

**Comment by jgm** [comment]
@rmaicle a minimal example would still be helpful, so we can see if the earlier change has in fact fixed your issue.

**Comment by jgm** [comment]
I tried the original conversion with current HEAD pandoc and did not see any problems relating to `|` characters.  (Nor did I see any escaped `|` characters.)  So I'm not sure what's going on, but I'm going to close this.  If you can provide a minimal example to focus our attention on what you take the problem to be, feel free to reopen.
