### ISSUE TITLE
LaTeX math: \textbf inside of \text command not parsed

### ISSUE THREAD

**Issue by schrieveslaach** [jgm/pandoc#3600]
In LaTeX you can write:

```latex
\documentclass[a4paper,11pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{ngerman}
\usepackage{amsmath}

\begin{document}
$ f(x) = \text{\textbf{Test}} $
\end{document}
```

Which results in:

![bildschirmfoto von 2017-04-24 19-29-32](https://cloud.githubusercontent.com/assets/16558417/25350155/7a9b525c-2924-11e7-8ada-d512bec36b49.png)

The dev version of pandoc generate a warning

```
[warning] Could not convert TeX math ' f(x) = \text{\textbf{Test}} ', rendering as TeX:
!  f(x) = \text{\textbf{Test}} 
!              ^
! unexpected "\\"
! expecting "}", text, "{", "$", "$$", "\\(" or "\\["
```

And the resulting html contains the raw math environment.

```html
<p><span class="math inline">$ f(x) = \text{\textbf{Test}} $</span></p>
```

**Comment by jgm** [comment]
This is unnecessary anyway:  you can just use

    \textbf{Test}

instead of

    \text{\textbf{Test}}

and texmath/pandoc will handle that fine.

Our support for commands inside of text environments in math
is a bit limited, partly because of the aims of texmath,
which needs to be able to convert to a number of different
formats.

**Comment by schrieveslaach** [comment]
Sometimes you want to emphasize something in an equation. In my use case, I want to use a user defined marco inside a math environment. See following minimal example code.

```latex
\documentclass[a4paper,11pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{ngerman}
\usepackage{amsmath}

\begin{document}

\newcommand{\mycommand}[1]{Example #1}
$ \text{\mycommand{stuff}} $
\end{document}
```

I'm also relying on the the texmath compatibility---I want to convert my LaTeX documents to ODTs to send them to my reviewers who can use the track changes functionality, the final PDF document will be published because the typographical quality is much better. However, I'm happy if incompatible expressions will be converted into compatible expressions for the review process, e.g. bold text to normal text. Therefore, the formulas need to be included as texmath. 

@jgm, do you think that this behavior can be implemented?

**Comment by schrieveslaach** [comment]
Oh, I forgot to mention that I'm using the `\text` command because the text looks much better than writing the text into the equation. Additionally, if I omit the `\text` command all spaces will be dropped, see below:

![bildschirmfoto von 2017-04-25 08-55-32](https://cloud.githubusercontent.com/assets/16558417/25372267/06ae9266-2995-11e7-975c-83203332bcf4.png)

**Comment by jgm** [comment]
There's no problem in general with macros inside `\text`, as your second example shows:

```
% pandoc -f latex -t docbook --mathml
\newcommand{\mycommand}[1]{Example #1}
$\text{\mycommand{hi}}$
^D
<para>
  <inlineequation><mml:math><mml:mtext mml:mathvariant="normal">Example hi</mml:mtext></mml:math></inlineequation>
</para>
```

The problem is with the `textbf` inside `text`:
```
% pandoc -f latex -t docbook --mathml
\newcommand{\mycommand}[1]{Example \textbf{#1}}
$\text{\mycommand{hi}}$
[warning] Could not convert TeX math '\text{{Example \textbf{hi}}}', rendering as TeX:
! \text{{Example \textbf{hi}}}
!                ^
! unexpected "\\"
! expecting text, "}", "{", "$", "$$", "\\(" or "\\["
<para>
  $\text{{Example \textbf{hi}}}$
</para>
```

It's a limitation of jgm/texmath, which only handles a few commands inside `\text` environments.  We could easily patch texmath so that `\textbf` is just ignored inside `\text`.  Changing it so that `\textbf` is handled properly would be a bit harder.

See https://github.com/jgm/texmath/blob/master/src/Text/TeXMath/Readers/TeX.hs#L3718 and related definitions if you want to look into this.  But I think this should be closed; you can open a related issue on jgm/texmath if you like.

**Comment by schrieveslaach** [comment]
@jgm, thank you for this clarification. 👍 

I have another use case and I hope you have some advice. I'm also using other commands in math environments which behave the same way as `\textbf`. I compile pandoc by myself and use this version. If I want to patch texmath to support other commands, how do I make sure that my patched version of texmath will be used during compilation?

Do you think that texmath could reuse functions that return just strings, e.g. functions like [dosiunitx](https://github.com/jgm/pandoc/blob/d17f0dab841fdda322853c175563792bde50fca2/src/Text/Pandoc/Readers/LaTeX.hs#L732)? For example:

```latex
$ x = \text{\SI{1000}{kg}} $
```

I know, this requires some have changes.

**Comment by jgm** [comment]
+++ schrieveslaach [Apr 25 17 23:28 ]:
>   I have another use case and I hope you have some advice. I'm also using
>   other commands in math environments which behave the same way as
>   \textbf. I compile pandoc by myself and use this version. If I want to
>   patch texmath to support other commands, how do I make sure that my
>   patched version of texmath will be used during compilation?

If your texmath version lives in ../texmath (relative to
your pandoc source directory), then you can just add this to
the packages stanza of stack.yaml:

packages:
- '.'
- '../texmath'

See stack.full.yaml for an example.

>   Do you think that texmath could reuse functions that return just
>   strings, e.g. functions like [2]dosiunitx? For example:
>
>$ x = \text{\SI{1000}{kg}} $

Note that texmath doesn't depend on pandoc; in fact, it
can't (on pain of circular dependencies).

So texmath can't reuse anything from pandoc.

**Comment by schrieveslaach** [comment]
Thanks! Works. 

I think I need to clarify my idea: my idea is to pass functions as arguments from pandoc to texmath (when you will call the texmath conversion in pandoc). If this is possible, you do not need to rewrite function in texmath you can just pass them as arguments to texmath (no circular dependencies).
