### ISSUE TITLE
text wrapping in context table cells

### ISSUE THREAD

**Issue by huashan** [jgm/pandoc#3602]
Can pandoc use the `\starttabulate` command together with `p` switch with table alignments for ConTex?

Using these command and switch I managed to create auto wrapping text cells in ConTex. Demo code:

```
\placetable[none]{}
\starttabulate[|r|lp|]
\HL
\NC cell on
\NC some very long text some very long text some very long text some very long text some very long text
\NC\AR
\stoptabulate
```

**Comment by jgm** [comment]
I'm not sure what you're asking.  What version of pandoc are you using?  Are you talking about ConTeXt as an input format or as an output format?  Pandoc already uses `p` for wrappable cells in its ConTeXt output.  It would be most helpful if you could give a minimal example, with the output pandoc gives and the output you think it should give.

**Comment by huashan** [comment]
Hi, @jgm 

I have a markdown file and want to convert to pdf via ConTeXt format. I am using pandoc version 1.19.2.1. to output the ConTeXt format. The markdown file has a long cell text as below:

```
%Test table wrapping for context

---- ------------------------------------------------
  aa aaa
  bb djka ei9 399 399a 930 a9390a93 3930 a039 a939 djka ei9 399 399a 930 a9390a93 3930 a039 a939 djka ei9 399 399a 930 a9390a93 3930 a039 a939 djka ei9 399 399a 930 a9390a93 3930 a039 a939 
---- ------------------------------------------------
```

The generated ConTeXt from pandoc version 1.19.2.1 is:

```
\placetable[none]{}
\starttable[|r|l|]
\HL
\NC aa
\NC aaa
\NC\AR
\NC bb
\NC djka ei9 399 399a 930 a9390a93 3930 a039 a939 djka ei9 399 399a 930
a9390a93 3930 a039 a939 djka ei9 399 399a 930 a9390a93 3930 a039 a939
djka ei9 399 399a 930 a9390a93 3930 a039 a939
\NC\AR
\HL
\stoptable
```

which produce a pdf with a very wide table than the page width. I don't see any `p` for wrappable cells in the ConTeXt output.

However, if I modify the context file with the `starttabulate` command and `p` switch as below the generated pdf file has a perfect auto wrapping text in the table cells.

```
![starttabulate](https://cloud.githubusercontent.com/assets/2095265/25429903/239563d2-2aad-11e7-9ae1-74657105f272.png)

\placetable[none]{}
\starttabulate[|r|lp|]
\HL
\NC aa
\NC aaa
\NC\AR
\NC bb
\NC djka ei9 399 399a 930 a9390a93 3930 a039 a939 djka ei9 399 399a 930
a9390a93 3930 a039 a939 djka ei9 399 399a 930 a9390a93 3930 a039 a939
djka ei9 399 399a 930 a9390a93 3930 a039 a939
\NC\AR
\HL
\stoptabulate
```




![Uploading starttabulate.png…]()

**Comment by jgm** [comment]
Generally for tables with long cells you should use pandoc
multiline tables instead of simple tables (see the
manual).  These will not only produce a table with a
wrappable 'p' cell, but will include information about the
relative widths of the cells (deriving these from the source
representation).

**Comment by huashan** [comment]
Thanks @jgm

But I still wonder if it's possible to let simple tables produce wrappable cells as well, besides, to let ConTeXt automatically determine the column width with `starttabulate` ?

**Comment by jgm** [comment]
We could try using 'p' instead of 'l' in these cases.
I don't know if there are other differences besides
wrapping?

+++ huashan [Apr 26 17 06:23 ]:

**Comment by huashan** [comment]
I don't know the difference between `starttable` and `starttabulate`, but it seems that `starttabulate` handles column width more properly.

The table generated with `starttable` command:

![starttable](https://cloud.githubusercontent.com/assets/2095265/25466925/f9248a9c-2b3d-11e7-98ba-6525dda95c1a.png)

**Comment by jgm** [comment]
Did some experiments with the first table in test/tables.txt.

With current pandoc, the output looks great:

<img width="785" alt="screen shot 2017-04-27 at 9 40 45 am" src="https://cloud.githubusercontent.com/assets/3044/25472932/a4a05f7e-2b2d-11e7-8092-832cd47adfeb.png">

With starttabulate instead of starttable (and p instead of l), we get a table that is unnecessarily spread out:

<img width="738" alt="screen shot 2017-04-27 at 9 42 05 am" src="https://cloud.githubusercontent.com/assets/3044/25472972/ce06c826-2b2d-11e7-8d49-5ad9d0fdbcc4.png">

I conclude that we should not change anything.
