### ISSUE TITLE
Documentation and howto for lua filters

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#3608]
Documentation of lua filters is currently limited to a short paragraph in the manual and the inline documentation in `pandoc.lua`.  The latter can be rendered via `ldoc data/pandoc.lua`, but the resulting page should also contain some examples and must be linked from somewhere.  It's probably best to either provide a document similar to epub.txt and/or to include a description of the lua system in the scripting doc.

**Comment by jgm** [comment]
This could go into the Customizing pandoc document (#3288), which will eventually include updated filter documentation.

But let's keep this a separate issue; if you write something up, we can figure out where it should go later.

**Comment by tarleb** [comment]
I pushed a very first draft as *doc/lua-filters.md* to get started.

**Comment by jgm** [comment]
Question for @tarleb: does the current lua filter functionality allow you write a filter that traverses a document, pulls out all the link URLs, and create a new document containing a table with the URLs and the number of times each is used?

**Comment by tarleb** [comment]
Something like this?

``` lua
links = {}

function Link (el)
  if links[el.target] then
    links[el.target] = links[el.target] + 1
  else
    links[el.target] = 1
  end
  return el
end

function Doc (blocks, meta)
  function strCell(str)
    return {pandoc.Plain{pandoc.Str(str)}}
  end
  local caption = {pandoc.Str "Link", pandoc.Space(), pandoc.Str "count"}
  local aligns = {pandoc.AlignDefault, pandoc.AlignLeft}
  local widths = {0.8, 0.2}
  local headers = {strCell "Target", strCell "Count"}
  local rows = {}
  for link, count in pairs(links) do
    rows[#rows + 1] = {strCell(link), strCell(count)}
  end
  return pandoc.Doc(
    {pandoc.Table(caption, aligns, widths, headers, rows)},
    meta
  )
end
```

The resulting table isn't ordered in any way.

**Comment by tarleb** [comment]
BTW: writing this filter reminded me of just how bad and uninformative error messages in lua filters are. I'm trying to fix this in hslua. From your experience with the Custom writer, is there anything else you'd like to change hslua?

**Comment by jgm** [comment]
Thanks, that helps.  Why don't you incorporate this example (or one like it) into the tutorial in `doc/lua-filters.md`?

As for error messages, I can't recall anything about them, sorry!

**Comment by jgm** [comment]
I took the liberty of adding this to the lua-filters documentation.  Feel free to tweak as you see fit.

Three thoughts about lua filters:

- Can something be added that allows elements to be deleted from the tree, or lists of elements to be spliced in, as we can do with python pandocfilters (return a list to splice, an empty list to remove)?

- Would it make sense to define a CatchAll function that runs if the function with the name of the block or inline element can't be found?  I'm thinking, for example, of how one might write a filter that deletes everything but header elements.

- Would it be worth using generics to eliminate some of the boilerplate in `execInlineLuaFilter`?  (Using syb generics would have a significant speed penalty, but using GHC generics might not.) This would also aid maintainability, since we wouldn't have to touch this module when basic types change.

**Comment by tarleb** [comment]
Thanks!

About your questions:

- Deleting and splicing: I'm not entirely sure yet how to implement it: would it be better to use a method akin to what JSONFilter does, or would it make sense to write a `Walkable a => Walkable [a] [a]` instance?

- CatchAll: I'm undecided on this.  The current implementation to get the filter functions from lua is not respecting the metatable. Otherwise one could write
    
    ``` lua
    return {setmetatable({},  {__index = function (el) … end})}
    ```

    which should work as a catch-all (but currently doesn't. I'd rather fix this.  On the other hand, CatchAll would be more user-friendly.

- Generics: Absolutely! I started to learn more about them last week, but don't understand yet how to use all these constructors to get what I want.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Jun 29 17 00:51 ]:
>     * Deleting and splicing: I'm not entirely sure yet how to implement
>       it: would it be better to use a method akin to what JSONFilter
>       does, or would it make sense to write a Walkable a => Walkable [a]
>       [a] instance?

Oh, I see now that you are actually using functions from
Text.Pandoc.Walk.  (The python pandocfilters implements its
own, more imperative style 'walk', and that made it easier
to do the splicing and deleting.)

toJSONFilter normally uses Walk functions, but falls back
to the much slower syb functions from Text.Pandoc.Generic
for the `a -> [a]` case.

It's hard to see how you could do anything like that,
without the type information we have with Haskell functions.

Could we add something like

    walkList :: (Walkable a b) => (a -> [a]) -> b -> b

I haven't thought about whether this would pose problems.
If we had this, would you be able to use it in the Lua code?
How would you know up front whether the return value was
supposed to be an a or an [a], so you knew whether to run
walkM or walkListM?

>     * CatchAll: I'm undecided on this. The current implementation to get
>       the filter functions from lua is not respecting the metatable.
>       Otherwise one could write
>return {setmetatable({},  {__index = function (el) … end})}
>       which should work as a catch-all (but currently doesn't. I'd rather
>       fix this. On the other hand, CatchAll would be more user-friendly.

You could always do both, right?  Just set the metatable to
use CatchAll, if it's defined?

>     * Generics: Absolutely! I started to learn more about them last week,
>       but don't understand yet how to use all these constructors to get
>       what I want.

Actually, the easiest way to get the constructor name is to
use Data.Data.toConstr.  This is syb generics, but we are
defining Data for all these types.  I think the thing to do
is to try it and see whether there's a significant
performance penalty.

**Comment by jgm** [comment]
I went ahead and made the change with `toConstr`.  It reduces the code size a lot and I measured no slowdown.

I wonder whether there's a compelling reason to have `DoubleQuoted`, `SingleQuoted`, `DisplayMath`, and `InlineMath` as special exceptions?

**Comment by jgm** [comment]
On `walkList`:  it might be acceptable just to keep things simple and return a Span (perhaps an empty one) when you need to delete an element or expand it to a list of elements.

**Comment by jgm** [comment]
I was asking myself how I'd write a filter that found things like `$name$` in the Markdown text and replaced them with the value of the metadata field `name`, if defined.  How could that be done with the lua filters?  One can access metadata in the `Doc` function, but this only gets applied after we've been through the document.  One would need a way to get metadata values from within e.g. the Math function.  Maybe I'm missing something simple?  Or is this a feature that could be added?

**Comment by tarleb** [comment]
As lua filter functions are run in the order *Inlines → Blocks → Meta → Pandoc*, we need two filters living in the same file:

``` lua
local vars = {}

function get_vars (meta)
  for k, v in pairs(meta) do
    if v.t == 'MetaInlines' then
      vars["$" .. k .. "$"] = v
    end
  end
end

function replace (el)
  if vars[el.text] then
    return pandoc.Span(vars[el.text])
  else
    return el
  end
end

return {{Meta = get_vars}, {Str = replace}}
```

This converts this:

``` markdown
---
name: John MacFarlane
occupation: Professor of Philosophy
---

Name

: \$name\$

Occupation

: \$occupation\$
```

into this:

``` html
<dl>
<dt>Name</dt>
<dd><p><span>John MacFarlane</span></p>
</dd>
<dt>Occupation</dt>
<dd><p><span>Professor of Philosophy</span></p>
</dd>
</dl>
```

**Comment by jgm** [comment]
Oh, nice!  So, if you return a list of filters, they get run in sequence?  This example, too, would be helpful in the documentation.

**Comment by tarleb** [comment]
Hopefully I'll find time to write some docs this weekend. 👍

**Comment by tarleb** [comment]
My current plan is to finally give hslua a new major release and to use that release to fix and extend the filters. Getting the release out the door should take about 2 weeks. I will continue documenting after that.

**Comment by tarleb** [comment]
A note on errors: triggering an error in lua filters will always panic the haskell RTS and crash pandoc (due to Lua's heavy use `longjmp`). I tried to find a solution for this:

The best generic option I found is the [`safer-lua-api`](https://github.com/DemiMarie/safer-lua-api), which hslua would have to include. However, it relies on non-ANSI C features, and could cause portability issues. I haven't tested it, don't know how much it would affect performance, and would to avoid like the tedious work that would come with this change.

A different alternative would be to rewrite some parts of  *Text.Pandoc.Lua* and *Text.Pandoc.Lua.Util* in C, which would allow us to properly catch and handle errors without confusing the haskell RTS. I don't really like that thought, either.

How big of a problem would it be if lua filters were left in their current state, i.e., inherently unsafe?  Custom writers currently suffer from the same problem, but would be much easier to fix.

**Comment by tarleb** [comment]
There might be a simple third option: compiling lua using a C++ compiler will replace the problematic `longjmp`s with `throw`s, which we should be able to catch in Haskell.  Got to look into this some more.

**Comment by tarleb** [comment]
Tested the third option; turns out I had blatantly misunderstood C++ exceptions and stack unwinding. So no, this won't work.

**Comment by jgm** [comment]
It's not horrible for regular command-line use if the errors can't be caught.  The only consequence is bad messages.  For use in a long-running (e.g. web) app, it would be disastrous, but if we document this, people can avoid using lua in such contexts.

**Comment by tarleb** [comment]
I've updated the docs and added the above example.

There is still the issue of having to document the *pandoc* lua module (`data/pandoc.lua`). My initial intention was to use `ldoc -o pandoc-module data/pandoc.lua` to generate the documentation. But that creates only HTML and doesn't look great when converted to roff or similar.

I'm considering to put most of the module documentation into a separate markdown file, but having docs and code in the same file seems like the better idea in this case. Alternatively, one could modify (or rewrite) **ldoc** such that it generates pandoc json instead of HTML.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Aug 21 17 20:03 ]:
>   I've updated the docs and added the above example.
>
>   There is still the issue of having to document the pandoc lua module
>   (data/pandoc.lua). My initial intention was to use ldoc -o
>   pandoc-module data/pandoc.lua to generate the documentation. But that
>   creates only HTML and doesn't look great when converted to roff or
>   similar.
>
>   I'm considering to put most of the module documentation into a separate
>   markdown file, but having docs and code in the same file seems like the
>   better idea in this case. Alternatively, one could modify (or rewrite)
>   ldoc such that it generates pandoc json instead of HTML.

What if you pipe ldoc's HTML through pandoc to convert the HTML to
something else?

**Comment by tarleb** [comment]
> What if you pipe ldoc's HTML through pandoc to convert the HTML to something else?

It contains a few tables and links which don't look so great when converted to groff. A filter converting or removing them might be enough. Which final formats should we aim for, HTML and groff?

**Comment by jgm** [comment]
What would be really nice is if we could convert to Markdown
so we could just tack it on to the lua filter docs, and it
would all be in one place.

+++ Albert Krewinkel [Aug 21 17 23:58 ]:

**Comment by tarleb** [comment]
I opened a PR. LDoc's HTML output isn't fully valid HTML and information was lost when converting with pandoc. There is now a custom LDoc template which does what we need and that can be tuned if necessary.
