### ISSUE TITLE
Syntax highlighting inside footnote - PDF fails to compile

### ISSUE THREAD

**Issue by leviroth** [jgm/pandoc#3609]
Syntax-highlighted code blocks in footnotes cause PDF creation to fail. This also appears to affect other classes, e.g. `.numberLines`.

Input:
```
Body text[^1]

[^1]: Here is some code:

    ```python
    print("Failure")
    ```
```

Command line: ` pandoc .\test.md -o test.pdf `
Expected: A PDF with highlighted Python code in its footnote
Actual:
```
! Argument of \FV@BeginScanning has an extra }.
<inserted text>
                \par
l.105 }

pandoc.exe: Error producing PDF
```
Pandoc version:
```
pandoc.exe 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```
OS: Windows 10

**Comment by jgm** [comment]
This is already fixed in the dev version.
See #3207.
