### ISSUE TITLE
Support tel: scheme

### ISSUE THREAD

**Issue by marcastel** [jgm/pandoc#3610]
Reopening #541 but for bracketed syntax.
Would be nice to support the `tel:` scheme.

```{.markdown}
[Switchboard](tel:+999/01.234.5678)
```
Reference:
<http://www.ietf.org/rfc/rfc3966.txt>

Cheers

**Comment by jgm** [comment]
```
 % pandoc
[Switchboard](tel:+999/01.234.5678)
^D
<p><a href="tel:+999/01.234.5678">Switchboard</a></p>
```
Are you expecting different output than this?
Perhaps you have an older version of pandoc?

**Comment by marcastel** [comment]
No. Thats perfect.
Must be an issue on my side (though I did to some testing before posting the issue).
Sorry for that.
