### ISSUE TITLE
Export other functions from readers and writers

### ISSUE THREAD

**Issue by shym** [jgm/pandoc#3617]
This is a feature request.
At the moment only readMarkdown is exported by the Markdown reader, allowing to parse a full Pandoc document. But other intermediate parsers would often be useful using pandoc-the-library, instead of pandoc-the-executable.

For various purposes, I’d sometimes like to be able to parse just an Inline or a Block and print (with the HTML writer for instance) only that chunk.

In one use case, I’m pulling many small items (in which I’d like to be able to use markdown syntax) from various files to build a web page. At the moment I do the ugly following: render the short markdown string into HTML and strip the surrounding “p” tag…

**Comment by jgm** [comment]
If you just want to render some inlines into HTML, try rendering `Pandoc nullMeta (Plain theInlines)`. Then you won't get the surrounding p tag.  `readMarkdown` will give you a `Para` rather than a `Plain`, but for small snippets, you can combine it with a `paraToPlain` function.

Another option is to use `query` from Walk to extract a list of `Inline` from the `Pandoc` that `readMarkdown` produces:
```
Prelude Text.Pandoc Text.Pandoc.Walk> :set -XScopedTypeVariables
Prelude Text.Pandoc Text.Pandoc.Walk> let getInline :: Inline -> [Inline] = \x -> [x]
Prelude Text.Pandoc Text.Pandoc.Walk> runIO $ query getInline <$> readMarkdown def ("hi *ok*\nthis is nice":: String)
Right [Str "hi",Space,Emph [Str "ok"],Str "ok",SoftBreak,Str "this",Space,Str "is",Space,Str "nice"]
```

**Comment by shym** [comment]
Thank you very much for your fast answer!
I suppose that means you don’t think the extra cost of building a whole Pandoc value to extract a small part inside is really an issue (I’m not sure how big a use-case would have to be for this to become an actual issue). So I’m closing this.

**Comment by jgm** [comment]
+++ shym [May 08 17 14:19 ]:
>   Thank you very much for your fast answer!
>   I suppose that means you don’t think the extra cost of building a whole
>   Pandoc value to extract a small part inside is really an issue (I’m not
>   sure how big a use-case would have to be for this to become an actual
>   issue). So I’m closing this.

I don't think it's too significant a cost.
The "small part inside" is really most of the data structure.
You're not doing much more actual parsing work (which is the
time-consuming part).
