### ISSUE TITLE
Escaping needed to avoid interpretation as reference link def

### ISSUE THREAD

**Issue by davidar** [jgm/pandoc#3619]
```
% pandoc -v
pandoc 2.0
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4, skylighting 0.3.3
% pandoc -f html -t markdown --reference-links
<ul><li><a href="foo">bar</a>: baz</li></ul>
-   [bar]: baz

  [bar]: foo
% pandoc -f html -t markdown --reference-links | pandoc
<ul><li><a href="foo">bar</a>: baz</li></ul>
[warning] Duplicate link reference '[bar]' at line 3 column 1
<ul>
<li></li>
</ul>
```

---

**EDIT**

More minimal example (the list is irrelevant):

```
% pandoc -f html -t markdown --reference-links
<a href="foo">bar</a>: baz
^D
[bar]: baz

  [bar]: foo
```

Similar issues:

```
% pandoc -f html -t markdown --reference-links
<a href="foo">bar</a>(baz)
^D
[bar](baz)

  [bar]: foo

% pandoc -f html -t markdown_strict --reference-links | pandoc
<a href="a">foo</a><br/><a href="b">bar</a>
^D
<p><a href="b">foo</a></p>
```

**Comment by jgm** [comment]
Pandoc allows you to have reference link definitions in any context, including list items.
So indeed, you have a duplicate reference link here!

The fix is simply to escape the colon:

    -   [bar]\: baz

**Comment by davidar** [comment]
So shouldn't this be fixed in the markdown writer, then?

**Comment by davidar** [comment]
There's also a similar issue with parentheses:

```
% pandoc -f html -t markdown --reference-links
<a href="foo">bar</a>(baz)
^D
[bar](baz)

  [bar]: foo
```

**Comment by jgm** [comment]
Sorry, I missed that you were using the writer.  It's really a problem with the writer.

**Comment by jgm** [comment]
Scratch that!  In fact, there's no problem with the writer.

If you give the reader the right input, namely
```
-   [foo]\: bar
```
then the writer will give you the right output, namely
```
-   \[foo\]: bar
```
which will not be interpreted as a reference link def.

**Comment by davidar** [comment]
But the example I gave was using the HTML reader?

**Comment by jgm** [comment]
Argh, right!

**Comment by jgm** [comment]
More minimal example (the list is irrelevant):
```
% pandoc -f html -t markdown --reference-links
<a href="foo">bar</a>: baz
^D
[bar]: baz

  [bar]: foo
```

**Comment by davidar** [comment]
A couple more problems related to escaping around links:

```
% pandoc -f html -t markdown | pandoc
<a href="foo">@bar</a>
^D
<p><span class="citation" data-cites="bar">[@bar]</span>(foo)</p>

% pandoc -f html -t markdown_strict --reference-links | pandoc
<a href="a">foo</a><br/><a href="b">bar</a>
^D
<p><a href="b">foo</a></p>
```

Should I should open separate issues for these?

**Comment by jgm** [comment]
+++ David A Roberts [Apr 30 17 02:19 ]:
>   A couple more problems related to escaping around links:
>% pandoc -f html -t markdown | pandoc
><a href="foo">@bar</a>
>^D
><p><span class="citation" data-cites="bar">[@bar]</span>(foo)</p>
>
>% pandoc -f html -t markdown_strict --reference-links | pandoc
><a href="a">foo</a><br/><a href="b">bar</a>
>^D
><p><a href="b">foo</a></p>
>
>   Should I should open separate issues for these?

The second issue belongs with this one.
The first one is a bit different, so a separate issue for
that (escaping to avoid interpretation as a citation)
would make sense.

**Comment by davidar** [comment]
Also inline notes:

```
% pandoc -f html -t markdown-superscript | pandoc
^<a href="foo">bar</a>
^D
<p><a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>(foo)</p>
<section class="footnotes">
<hr />
<ol>
<li id="fn1"><p>bar<a href="#fnref1" class="footnoteBack">↩</a></p></li>
</ol>
</section>
```

**Comment by jgm** [comment]
As a general note:

Escaping every special character, every time, would suffice
to avoid this whole class of bugs, but I've opted to avoid
that in order to make the Markdown output look better in the
vast majority of cases.

I'm certainly open to fixes that insert escapes
intelligently, but sometimes they're a bit tricky to
implement.

**Comment by davidar** [comment]
Agreed (if anything some symbols could probably do with less escaping, like dollars).

I'll have a go at writing a fix.
