### ISSUE TITLE
Unexpected Accidentally Long <p> Label 

### ISSUE THREAD

**Issue by DingJunyao** [jgm/pandoc#3621]
Version: pandoc 1.19.2

(sorry, I can't upload the files and I don't know why,so the contents of the file is written below)

Input:

```
....

实际价格P=MC=MC1+MC2 销售价格P1=MC1 P1<P，造成实际价格比销售价格低的假象……

(About 6000 characters, which contains some h1~h5, p, ul, etc. in Markdown style)

##### 基尼系数反映的贫富差距

- <0.2：该国/地区……
- \>0.5：收入差距悬殊。

....
```

Command: `pandoc input.md -o output.html`

Expected Output: 

```
<p>....</p>
<p>实际价格P=MC=MC1+MC2 销售价格P1=MC1 P1&lt;P，造成实际价格比销售价格低的假象……</p>
<p>(About 6000 characters, which contains some h1~h5, p, ul, etc. in Markdown style)</p>
<h5>基尼系数反映的贫富差距</h5>
<ul>
<li>&lt;0.2：该国/地区……</li>
<li>&gt;0.5：收入差距悬殊。</li>
</ul>
<p>....</p>
```

Actual Output: 

```
<p>....</p>
<p>实际价格P=MC=MC1+MC2 销售价格P1=MC1 P1<P，造成实际价格比销售价格低的假象……

(About 6000 characters, which contains some h1~h5, p, ul, etc. in Markdown style)

##### 基尼系数反映的贫富差距

- <0.2：该国/地区……
- \>0.5：收入差距悬殊。</p>
<p>....</p>
```

Visual Actual Output: 

```
....

实际价格P=MC=MC1+MC2 销售价格P1=MC1 P10.5：收入差距悬殊。

....
```

Maybe it's because of the unexpected accidentally long `<p>` label , but it's a funny bug I think.

**Comment by jgm** [comment]
I was able to reproduce this bug with pandoc 1.19.1.
However, with the dev version it is gone, and I get your "expected output." So I believe that the issue has already been fixed.  (I'm not sure I know precisely which commit fixed it, though.)
