### ISSUE TITLE
Ampersand in reference key causing pandoc-citeproc to fail when loading a bibliography file.

### ISSUE THREAD

**Issue by norbertschmidtnet** [jgm/pandoc#3624]
```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```

The following reference created from a Zotero export with the Better BibLaTex plugin (v. 1.6.96)
```

@report{orrick_herrington_&_sutcliffe_llp_balancing_2014,
  location = {{London}},
  title = {Balancing Purpose and Profit - {{Legal}} Mechanisms to Lock in Social Mission for “Profit with Purpose” Businesses across the {{G8}}},
  url = {http://www.trust.org/contentAsset/raw-data/1d3b4f99-2a65-49f9-9bc0-39585bc52cac/file},
  timestamp = {2017-04-30T15:13:35Z},
  langid = {english},
  editorb = {{Orrick, Herrington \& Sutcliffe LLP} and {UnLtd} and {Thomson Reuters Foundation}},
  editorbtype = {redactor},
  date = {2014-12},
  file = {2014-balancing_purpose_and_profit_-_legal_mechanisms_to_lock_in_social_mission_for.pdf:/Users/norbert/Documents/eBooks/zotero/2014-balancing_purpose_and_profit_-_legal_mechanisms_to_lock_in_social_mission_for.pdf:application/pdf},
  groups = {21E16000 Sustainable Business and Consumption,25E18000 Sustainable Entrepreneurship,21E16000 Sustainable Business and Consumption,25E18000 Sustainable Entrepreneurship,21E16000 Sustainable Business and Consumption,25E18000 Sustainable Entrepreneurship}
}
```
leads to the following error message when using a .bib file containing it as a reference:
```
pandoc-citeproc: "stdin" (line 2, column 2):
unexpected "r"
expecting "c", "C", "p", "P", "s" or "S"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:113:32 in pandoc-citeproc-0.10.4-BdOyQb33rzG2TMOLj4Fbp9:Text.CSL.Input.Bibtex
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

Joost Kremers on the pandoc-discuss mailing list pointed out that the issue seems to be the ampersand in the reference's key (message thread: https://groups.google.com/forum/#!msg/pandoc-discuss/VZHUBrWBuFY/DtrBqukzCQAJ).

Removing that manually resolved the issue for me and works as a workaround, but maybe there's another way to fix that.

**Comment by jgm** [comment]
Thanks for the report.  Can you move this to jgm/pandoc-citeproc?  It's not an issue in pandoc itself.

**Comment by norbertschmidtnet** [comment]
Sure. I wasn't aware there was a different one for pandoc-citeproc, sorry.

Since I didn't find a way to move this issue there directly, I created a new issue in jgm/pandoc-citeproc and copy-pasted the content. This is it: https://github.com/jgm/pandoc-citeproc/issues/289

I also don't seem to be able to close this one.

Apologies, I'm not really experienced in using GitHub.
