### ISSUE TITLE
html reader: Unicode char ÔÇå (U+2006) not supported (html reader)

### ISSUE THREAD

**Issue by GiantCrocodile** [jgm/pandoc#3634]
The character U+2006 is not supported in html reader. See this: http://www.fileformat.info/info/unicode/char/2006/index.htm

**Comment by GiantCrocodile** [comment]
... maybe it is related to Latex writer. I'm not sure if it is read or written wrongly.

**Comment by mb21** [comment]
The `ÔÇå` in your title suggests you're having encoding issues... pandoc usually passed through unicode fine. If your problem persists, you'll have to be more specific. Please post your input, your command, pandoc version and system, actual output, expected output.

**Comment by GiantCrocodile** [comment]
I will retry and give feedback with this.

**Comment by GiantCrocodile** [comment]
Yep, you were right @mb21. Wrong latex engine was used. Maybe we can have a warning on this or automatic switching to an unicode supporting engine if engine is used with non-supported input?

**Comment by wilx** [comment]
On 3 May 2017 at 17:48, Clemens Prill <notifications@github.com> wrote:

> Yep, you were right @mb21 <https://github.com/mb21>. Wrong latex engine
> was used. Maybe we can have a warning on this or automatic switching to an
> unicode supporting engine if engine is used with non-supported input?
>
>
​U+2006 is SIX-PER-EM SPACE. You can use it with any of the three LaTeX
engin​es if you include package `uspace` in your preamble.


-- 
VH

**Comment by mb21** [comment]
If pdflatex errors out with `Package inputenc Error`, pandoc already [suggest using xelatex](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/PDF.hs#L223). Not sure it's worth to scan the entire input doc for non-ascii chars, I don't think so... but feel free to reopen @jgm if you think otherwise.
