### ISSUE TITLE
Merge generic and Markdown-specific grid table parsers

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#3638]
_Note to self: don't try opening an issue from mobile._

The markdown and RST/generic grid table parser have a different methods of compactifying table cells. The generic parser acts in a per-cell level, while the md parser looks at rows. A two element grid table

    +-------+-------+
    | Hello | World |
    +-------+-------+

will give

    [Table [] [AlignDefault,AlignDefault] [0.1111111111111111,0.1111111111111111]
     [[]
     ,[]]
     [[[Para [Str "Hello"]]
      ,[Para [Str "World"]]]]]

when parsed as markdown and

    [Table [] [AlignDefault,AlignDefault] [0.1111111111111111,0.1111111111111111]
     [[]
     ,[]]
     [[[Plain [Str "Hello"]]
      ,[Plain [Str "World"]]]]]

when parsed as rst.  Is this intended behavior which needs to be preserved?

**Comment by jgm** [comment]
I'm pretty sure it would be safe to have these behave the same way.
Most likely the Markdown parser's way is more correct, but I'm not sure, and I didn't quite understand from your brief description why there's a difference in behavior.

**Comment by tarleb** [comment]
Sorry for the bad explanation, should have taken more time instead of creating this issue in passing.

What's happening is that the Markdown parser compactifies rows the same way that lists are compactified: If none of the other cells in that row contain a para, then the cell in the final column will be converted from Para to Plain:

    +--------+-------+
    | - India | Papa |
    +---------+------+

reads the row as

    [[BulletList
      [[Plain [Str "India"]]]]
     ,[Plain [Str "Papa"]]]

while

    +-------+------+
    | India | Papa |
    +-------+------+

gives

    [[Para [Str "India"]]
     ,[Para [Str "Papa"]]]

Note that the block type of the last cell depends on the cell content of the rest of the cells in that row.

I'd argue that the RST behavior is more natural, in that the block type of the second cell is kept constant, regardless of the first cell's content.  When parsed as RST, the above examples result in the rows

    [[BulletList
      [[Plain [Str "India"]]]]
      ,[Plain [Str "Papa"]]

and

    [[Plain [Str "India"]]
    ,[Plain [Str "Papa"]]]

respectively.

**Comment by tarleb** [comment]
The test suite revealed a second difference between the parsers:  The markdown parser allows header cells to contain multiple blocks, while the rst reader will treat even multi-line headers as if they had been given in a single line.  E.g.:

    +---------+
    | Example |
    |         |
    | Header  |
    +=========+
    | cell    |
    +---------+

As Markdown:

    Table [] [AlignDefault] [0.1388888888888889]
    [[Para [Str "Example"]
     ,Plain [Str "Header"]]]
    [[[Plain [Str "cell"]]]]

As RST:

    Table [] [AlignDefault] [0.1388888888888889]
    [[Plain [Str "Example",Space,Str "Header"]]]
    [[[Plain [Str "cell"]]]]

I assume the Markdown parser's behavior to be preferable in this case.

**Comment by jgm** [comment]
It seems there are really two differences:

1.  the Markdown parser allows the second cell compactification to be influenced by the first cell, as you noticed. I agree, it's puzzling why it should work this way -- but maybe there was a reason.  At least it would be worth using git blame to try to find the commit that added this.

2.  in the case where each cell just has a single word, there's another difference; you get Para in Markdown and Plain in RST.  Here again, I can't recall whether there is a reason for the different behavior, and maybe a bit of git archaeology would help.

On the final issue (multiple blocks in headers), it may be that RST doesn't allow multiple blocks in headers, so this may be intentional. Again, I don't recall, but it would be worth checking this with rst2html.py and looking at git.

**Comment by tarleb** [comment]
Wow, that took quite some digging.  The line in question was changed quite often.

The change can be tracked back to fadc7b0d873cb021b69d06bd37313be84afeecca, i.e. the commit initiating the split between the two parsers.  Nothing in the commit message seems to hint at a reason for the new markdown behavior.

Using `rst2html` from Docutils 0.12 on the multi-paragraph header table, I get

``` html
<thead valign="bottom">
<tr><th class="head"><p class="first">Example</p>
<p class="last">Header</p>
</th>
</tr>
</thead>
```
