### ISSUE TITLE
Pandoc removes HTML5 <figure>/<figcaption> in ePub output

### ISSUE THREAD

**Issue by machal** [jgm/pandoc#3640]
Is there a way to leave `<figure>`/`<figcaption>` in HTML code as defined in source?

HTML input (which is what I want in ePub output too):

```html
<figure>
<img src="image.jpg">
<figcaption>
<p><em>Lorem <a href="#ipsum">Ipsum</a></em></p>
</figcaption>
</figure>
```

Actual ePub output:

```html
<p>
<img src="image.jpg">
</p>
<p><em>Lorem <a href="#ipsum">Ipsum</a></em></p>
```

Command:

```
pandoc -o vdwd.epub input.html 
```

Pandoc version: 1.19.2.1.

**Comment by mb21** [comment]
You can try the `--parse-raw` option to retain all HTML elements that pandoc doesn't handle natively. Please see the MANUAL or ask on pandoc-discuss for details...

**Comment by jgm** [comment]
Try adding the --parse-raw option.

+++ Martin Michálek [May 05 17 02:02 ]:

**Comment by jgm** [comment]
PS. In the dev version, one would do

    -f html+raw_html

but in the released versions,

    -f html --parse-raw

+++ Martin Michálek [May 05 17 02:02 ]:
