### ISSUE TITLE
no lstinputlisting from latex to html5/epub

### ISSUE THREAD

**Issue by cpieringer** [jgm/pandoc#3645]
I want to convert a latex document to html5/epub. I have several script examples in a lstinputlisting environment. The output does not include any script. Is it possible to do that using pandoc?

Thank you in advance.

**Comment by jgm** [comment]
This tracker is for bug reports.  Please ask questions
on the pandoc-discuss mailing list (Google Groups).

+++ Christian Pieringer [May 06 17 05:40 ]:
