### ISSUE TITLE
Latex \includegraphics png-file not found with spaces in path

### ISSUE THREAD

**Issue by GiantCrocodile** [jgm/pandoc#3650]
When I use `pandoc -s -f html -o result.tex "<html source file >` I get this line for png-files:

```latex
\includegraphics{path which contains spaces to subfolder with file inside}
```
This is what LuaLatex reports me:

```latex
Package luatex.def Error: File `[...].png' not found. ...m - [...]/[...].png}
Missing $ inserted. ...[...]/[...].png}
```

If I open this file in TeXstudio I can see a preview of the file. Looks like this isn't applied: https://tex.stackexchange.com/a/9030

**Comment by jgm** [comment]
You don't say what version of pandoc you're using. An issue like this was fixed fairly recently:
#2825.

**Comment by GiantCrocodile** [comment]
Sorry @jgm - I'm using

```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```

**Comment by jgm** [comment]
Can you give something I can use to reproduce this?  E.g. a one-line HTML file with an image that causes a problem?  No need to include the actual image, just the HTML with the path.

**Comment by jgm** [comment]
I tried to reproduce this from your description, but I could not get it to fail using images with spaces in the path.

**Comment by GiantCrocodile** [comment]
@jgm this is one of them:

```
<img id="logo-social-mobile" usemap="#jf-logo-social-map-mobile" src="Medienrecht%20und%20Presserecht%20Forum%20-%20JuraForum.de-Dateien/xlogo-social_mobil.png" pagespeed_url_hash="4136321477" onload="pagespeed.CriticalImages.checkImageForCriticality(this);" class="cszqnriswxuyzcrekvrm" border="0">
```

**Comment by jgm** [comment]
Still can't reproduce.  First, I created a file at the appropriate path:
```
% ls Medienrecht\ und\ Presserecht\ Forum\ -\ JuraForum.de-Dateien/xlogo-social_mobil.png 
Medienrecht und Presserecht Forum - JuraForum.de-Dateien/xlogo-social_mobil.png
```
Then I did
```
% pandoc -f html -o my.pdf
<img id="logo-social-mobile" usemap="#jf-logo-social-map-mobile" src="Medienrecht%20und%20Presserecht%20Forum%20-%20JuraForum.de-Dateien/xlogo-social_mobil.png" pagespeed_url_hash="4136321477" onload="pagespeed.CriticalImages.checkImageForCriticality(this);" class="cszqnriswxuyzcrekvrm" border="0">
^D
pandoc: extracting /var/folders/l0/2t_cldbj26j_vsd9_q2tsf400000gn/T/tex2pdf.9968/c4880ee203cd4c7f129a4c50ad0906b2f04761c1.png
```
I got a PDF with an image.
Do you get different results with these exact steps?

**Comment by GiantCrocodile** [comment]
I can generate a PDF with pandoc but if I open the tex file and try to compile it myself without pandoc this fails. @jgm what is the default engine? If I pass ``--latex-engine=lualatex` pdf production fails. Maybe pdflatex is default and works and also xalatex works but lualatex only fails?

**Comment by jgm** [comment]
OK, that's interesting.
If I generate a standalone tex file and then use pdflatex, it works.
If I use lualatex, I get
```
! Missing $ inserted.
<inserted text> 
$
l.68 ...JuraForum.de-Dateien/xlogo-social_mobil.png}
```
I'm tempted to think this is a lualatex bug.

**Comment by jgm** [comment]
PS. I get the same issue on lualatex with this simple file:
```
\documentclass[]{article}
\usepackage{graphics}
\begin{document}

\includegraphics{Medienrecht und Presserecht Forum - JuraForum.de-Dateien/xlogo-social_mobil.png}

\end{document}
```

**Comment by jgm** [comment]
And none of the suggestions on the linked stackexchange post help.

**Comment by GiantCrocodile** [comment]
Okay, I just tried a lot of different options, parameters and escapings. It is some nasty bug in the engine or graphic package. Nothing can be done from pandoc's site.
