### ISSUE TITLE
\href raise an error inside \caption with links-as-notes

### ISSUE THREAD

**Issue by andresmrm** [jgm/pandoc#3651]
This seems similar to #2490, but the error is caused by a missing `\protect` before a `\href` (not `\hyperlink`). Adding the `\protect` manually solves the error.

input:

```
pandoc -V links-as-notes -o test.pdf << EOT
# This is a test

![This is an image. It has a [link](http://pandoc.org) in captions.](http://pandoc.org/diagram.jpg)

EOT
```

output:

```
! Argument of \Hy@tempa has an extra }.
<inserted text> 
                \par 
l.77 captions.}

pandoc: Error producing PDF
```

pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4, skylighting 0.1.1.5

**Comment by wilx** [comment]
The https://github.com/wilx/pandoc-templates/commit/b23c17ecbc2483c06e51cf16e6b8836c86bafda2 revision fixes the compilation issue. However, it will not make such use usable. The foot note will not show.

**Comment by mb21** [comment]
@wilx btw, on the current master (and for pandoc 2.0) the templates are now in the [normal pandoc repo](https://github.com/jgm/pandoc/tree/master/data/templates)...
