### ISSUE TITLE
[feature request] Support RDF to HTML conversion

### ISSUE THREAD

**Issue by smileygingerbread** [jgm/pandoc#3653]
I was looking for a RDF->HTML converter, but I couldn't find anything online (or anything which is not >10 years old and unmaintained). So, as a pandoc user I thought it would be a really nice feature to add to the project.

RDF comes in [different serialization options](https://en.wikipedia.org/wiki/Resource_Description_Framework#Serialization_formats), but supporting only one of them would be enough because there are already tools to convert from one format to another. `N-Quads` is likely the simplest one (very easy to parse). Would be cool if pandoc could generate an HTML documentation starting from an n-quads file.

**Comment by jgm** [comment]
RDF doesn't look like a text format. (Rather it's a metadata
format.) So it looks out of scope for pandoc.
