### ISSUE TITLE
Using a custom.docx breaks "Figure with Caption" Styling.

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#3656]
This is pretty simple. First create two custom docx reference templates:

```shell
pandoc --print-default-data-file reference.docx > customA.docx
pandoc --print-default-data-file reference.docx > customB.docx
```

Now edit customB.docx in Word — all you need to do is open it, add a space, delete the space and save. Now if you use this markdown and those templates:

```markdown
# Simple test #

![Test image](test.png)  

More text.  
```

```shell
pandoc --reference-docx=customA.docx -o resultA.docx input.md
pandoc --reference-docx=customB.docx -o resultB.docx input.md
```

You find in for resultB.docx in Word that the figure loses its "Figure with Caption" styling (and thus keep with next), and is now "Normal".

The reason is a case issue caused by Word editing the styles on save, here is styles.xml for A vs. B:

![screen shot 2017-05-10 at 12 50 54](https://cloud.githubusercontent.com/assets/153905/25889964/4a1ff642-359e-11e7-972a-22318d8e7d9a.png)

(LEFT==resultA.docx | RIGHT=resultB.docx) For some reason, Word overwrites the w:styleId = Figure**W**ithCaption with the w:val extrapolation so the w:styleId becomes Figure**w**ithCaption. But the document.xml still uses the uppercase version and thus fails to apply. The easiest fix I assume is to rename the original template so _both_ w:val and w:styleId use an uppercase **W**. I couldn't see other styles that use mixed case in the pandoc template, but assume this applies to any such style.

**Comment by iandol** [comment]
Actually, it is not so simple to fix. Basically if you set w:styleId and w:val to `FigureWithCaption`, each time you edit it Word changes it to `FigurewithCaption`. So even if you change w:val in the original reference.docx if you edit it it will break. So the only answer I think is to change to DOCX writer to use `FigurewithCaption` for both the actual document XML and the styleId...

**Comment by jgm** [comment]
Okay, we can change `FigureWithCaption` to `FigurewithCaption`.
This may break some existing reference.docx's, but I don't see a better option.
While we're breaking things, maybe better to use `CaptionedFigure`.
This presumably wouldn't create the same problem (which I imagine is caused by some algorithm that recognizes "small words" like "with").

**Comment by jgm** [comment]
PS. Thanks for the excellent bug report!

**Comment by iandol** [comment]
Well thanks multiplied for such an amazing tool! I agree that `CaptionedFigure` looks better and won't trigger any potential title case weirdness. 

Can't wait for Pandoc 2.0, it's going to be an excellent release!

**Comment by iandol** [comment]
Here is reference.docx edited manually to use w:styleId=`CaptionedFigure` and w:val=`Captioned Figure`, no other changes made.

[reference.docx](https://github.com/jgm/pandoc/files/991784/reference.docx)
