### ISSUE TITLE
MD --> PDF via XeLaTeX RTL language with tables compile error

### ISSUE THREAD

**Issue by lwolfsonkin** [jgm/pandoc#3660]
It seems that the Markdown --> PDF (via XeLaTeX) has issue with RTL languages declarations along with the use of tables. Here, with the following example:

```markdown
---
lang: en
otherlangs:
    - he
mainfont: Arial
---

# Test

| header |
|:------:|
| first  |
| second |
| third  |
```

I get the following error:

~~~
! Package bidi Error: Oops! you have loaded package longtable after bidi packag
e. Please load package longtable before bidi package, and then try to run xelat
ex on your document again.

See the bidi package documentation for explanation.
~~~

I believe this to occur because the polyglossia package calls the bidi package implicitly for RTL languages, and the `longtable` package must be called after the `bidi` package.

To fix this locally, I moved the `lang` variable part of the latex template to the first thing before the `bidi` variable handling.

I don't believe this should cause other issues.

**Comment by jgm** [comment]
This should now be fixed. Feel free to comment here if it isn't fixed by #3661.
