### ISSUE TITLE
Docs say highlighting-kate; dependencies say skylighting

### ISSUE THREAD

**Issue by mpacer** [jgm/pandoc#3672]
In the docs http://pandoc.org/MANUAL.html#syntax-highlighting it is said that the syntax highlighting is provided by `highlighting-kate`. Is that still the case? The `highlighting-kate` library has been deprecated in favour of `skylighting`. This seems to have been updated for the dependencies — is there any systematic way in which `highlighting-kate` continues to play a role?

**Comment by mpacer** [comment]
Happy to make a PR, I just didn't want to until I understood the context of the deprecation and continued support.

**Comment by jgm** [comment]
Thanks, I've fixed this.  `highlighting-kate` plays no role.
