### ISSUE TITLE
docx to md generate "Toc anchors" that are very very slow to reprocess.

### ISSUE THREAD

**Issue by laperouse** [jgm/pandoc#3679]
when converting docx to md, toc anchors may be generated in the md.
Having several of those will cause the reprocessing of the md to be very very slow.
For instance, this md will take several seconds to be processed for nothing (I stripped out all the useful text and kept just what was causing the problem)

```
[[[[[[]{#_Toc453171571 .anchor}]{#_Toc447636940 .anchor}]{#_Toc447535052
.anchor}]{#_Toc447534026 .anchor}]{#_Toc443660776
.anchor}]{#_Toc398199573 .anchor}

[[[[[]{#_Toc453171582 .anchor}]{#_Toc447636951 .anchor}]{#_Toc447535063
.anchor}]{#_Toc447534037 .anchor}]{#_Toc443660787 .anchor}

[[[[[[[[]{#_Ref453947219 .anchor}]{#_Toc453171583
.anchor}]{#_Toc447636952 .anchor}]{#_Toc447535064
.anchor}]{#_Toc447534038 .anchor}]{#_Toc443660788
.anchor}]{#_Ref424922771 .anchor}]{#_Toc398199582 .anchor}

[[[[[]{#_Toc453171586 .anchor}]{#_Toc447636955 .anchor}]{#_Toc447535067
.anchor}]{#_Toc447534041 .anchor}]{#_Toc443660791 .anchor}

[[[[[[]{#_Toc453171587 .anchor}]{#_Toc447636956 .anchor}]{#_Toc447535068
.anchor}]{#_Toc447534042 .anchor}]{#_Toc443660792
.anchor}]{#_Ref425269675 .anchor}

[[[[[[]{#_Toc453171589 .anchor}]{#_Toc447636958 .anchor}]{#_Toc447535070
.anchor}]{#_Toc447534044 .anchor}]{#_Toc443660794
.anchor}]{#_Ref424832404 .anchor}

[[[[[[]{#_Toc453171602 .anchor}]{#_Toc447636971 .anchor}]{#_Toc447535083
.anchor}]{#_Toc447534057 .anchor}]{#_Toc443660807
.anchor}]{#_Ref424919863 .anchor}

[[[[[]{#_Toc453171611 .anchor}]{#_Toc447636980 .anchor}]{#_Toc447535092
.anchor}]{#_Toc447534066 .anchor}]{#_Toc443660816 .anchor}

[[[[[[[[[]{#topic_Blend_products .anchor}]{#topic_Blend_products_2
.anchor}]{#topic_Qualities .anchor}]{#topic_Model_documents
.anchor}]{#topic_DiscreteStreamSource .anchor}]{#topic_Blender
.anchor}]{#topic_Tank .anchor}]{#topic_Model_units
.anchor}]{#topic_Creating_a_blending_model .anchor}

[[[[[[]{#_Toc453171667 .anchor}]{#_Toc447637024 .anchor}]{#_Toc447535136
.anchor}]{#_Toc447534110 .anchor}]{#_Toc446686530
.anchor}]{#_Toc441223871 .anchor}

```

And i have 242 of those in my file so the time seems to grow exponentially.
Same issue with current nightly build.

**Comment by jgm** [comment]
Can you link to or upload a docx file that we can test with?

**Comment by jgm** [comment]
See #1735 for the likely cause of the slowdown.  But I don't understand why you're getting all the open-bracket characters in converting from the docx, so it would be nice to have a docx to try with.

**Comment by laperouse** [comment]
here is a docx to reproduce the problem
[toc.docx](https://github.com/jgm/pandoc/files/1010479/toc.docx)

````
pandoc.exe -s -t markdown -o source.md "toc.docx"
````
then
````
pandoc.exe -s -t docx -o n.docx source.md
````

**Comment by jgm** [comment]
@jkr Any thoughts on this?  Is it desirable/possible to ignore the TOC anchors generated by Word, for cleaner output?

**Comment by jkr** [comment]
We should probably ignore them, since the table of contents itself is generated, so these don't refer to anything. (It is inside an SDT tag, though, so it seems like it should be read. I have to investigate that.)

How about we axe those, and the generated TOC, but use the existence of a generated TOC to mean that we should turn `writerTableOfContents` on?

**Comment by jkr** [comment]
With 4fc3f511863c578be6a3237d02133da25db0ce05, we now read `sdtContents` properly, which means that we read the generated TOC. Note that the output of toc.docx above now at least makes sense in that the generated TOC is included. But that doesn't solve the issue.

The problem right now seems to be the nesting of the anchor links, so renaming isn't done properly. I'll try to fix the underlying problem.

That being said, I still think once we make this work right, it might be beneficial to not read the fall back generated TOC but instead have the existence of the dynamic content trigger `writerTableOfContents` -- the direct translation of the generated TOC is uglier than the format-specific one would be.

So I'll keep this open until I make it work right and we can see what the anchor links *should* look like. But then I'll open a new issue for possibly replacing the dynamic content with pandoc-dynamic content.

**Comment by jkr** [comment]
I'm having a bit of trouble reproducing this with documents I made in word.

@laperouse: how was this document generated? Were the links and anchors automatically inserted, or did you put them in by hand. It would be helpful to have a minimal example to work with. (And sorry for taking so long to get on this issue.)

We should have different output, but to decide what that output would be, it would be useful to know how (and with what intent) the input was produced.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Dec 30 17 05:49 ]:

>   That being said, I still think once we make this work right, it might
>   be beneficial to not read the fall back generated TOC but instead have
>   the existence of the dynamic content trigger writerTableOfContents --
>   the direct translation of the generated TOC is uglier than the
>   format-specific one would be.

Agreed. But in general reader behavior should not be
dependent on writer behavior, and vice versa. Better just to
allow users to specify --toc if they want it.  I think we
could just remove the TOC. Or, setting the 'toc' metadata to
true would actually do the trick in some formats, where
it's just a switch in the template.

**Comment by jkr** [comment]
Actually, is there ever a good reason in pandoc for multiple anchors in the same sport? I feel like we should make an effort to collapse them. Something like this

~~~
[[[[[[[[]{#_Ref453947219 .anchor}]{#_Toc453171583
.anchor}]{#_Toc447636952 .anchor}]{#_Toc447535064
.anchor}]{#_Toc447534038 .anchor}]{#_Toc443660788
.anchor}]{#_Ref424922771 .anchor}]{#_Toc398199582 .anchor}
~~~

comes from multiple bookmarks in the same place in the docx file. Maybe this nesting isn't the best way to do this, but the bigger question is: what is the meaning of multiple overlapping anchors anyway? Couldn't we say that since every link is going to the same place, they're all going to the same anchor?

**Comment by jkr** [comment]
I took care of the overlapping anchors issue mentioned above with 836153de. This does mean that some possible user-entered information from the docx will be lost (bookmark names) but we already had to do that for header auto-ident rewriting. This should make output a good deal cleaner.

I'm not sure how much this is redundant with e90c714, but I think I'll be able to produce cases where neither is sufficient by itself.

**Comment by laperouse** [comment]
@jkr 

> how was this document generated? Were the links and anchors automatically inserted, or did you put them in by hand? It would be helpful to have a minimal example to work with. (And sorry for taking so long to get on this issue.)

It is a big document that contains many titles 1 to 6 and a TOC. The document is stored in sharepoint (office365) and  edited in office365 in mulituser, so maybe the sharepoint merge algorithm is producing weird things in the anchors.
We did not create any anchor manually, just automatic Word stuff.

**Comment by jkr** [comment]
@laperouse Just FYI, this issue was fixed 3 months ago.
