### ISSUE TITLE
GUI build?

### ISSUE THREAD

**Issue by EMLVIRUS** [jgm/pandoc#3693]
Any plan to prepare a official GUI?
If cross-platform compatibility is concerned, maybe try out Qt?

**Comment by Guilz** [comment]
Can you provide an example use case where a graphical interface would make pandoc more efficient?
The only way I can picture such an interface involves an endless drop down menu with all options, or endless check boxes (one for every option). Neither of these seems easier to use than the command line, given the vast number of options.

**Comment by mb21** [comment]
This is out of scope for the pandoc core project. However, please see https://github.com/jgm/pandoc/wiki/Pandoc-wrappers-and-interfaces for a list of third-party GUI wrappers.

Also please use pandoc-discuss for questions like this instead of this issue/bug tracker.
