### ISSUE TITLE
Support author metadata for use with LaTeX and DOCX more robustly

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#3696]
There are several templates for Pandoc > LaTeX that make use of richer author metadata, for example the excellent pandoc-scholar by @tarleb 

```
author:
  - Yi Zeng:
      institute:
        - IoN
        - IoA
  - Yi Deng:
      institute: IoA
  - Yi Heng:
      institute: 
        - IoN
        - CaS
```

However if you use such extended metadata, then the DOCX writer fails to use the author data, so it becomes either/or. It would be nice if we could use the more complex metadata without running into these problems.

As a slight aside, lots of templates seem to try to solve author+affiliation using different variants of the metadata, all a little incompatible with each other, and I wonder whether a guided "formal" decision by Pandoc to use one formatting would help standardise this?

**Comment by tarleb** [comment]
Glad to hear that you find pandoc scholar to be useful. The missing info in docx is mostly a problem with that tool, which I'm currently trying to solve. Docx templates would help with this, but solving it in pandoc scholar for current pandoc versions would be nice.

I'm closing this issue in favor of #3109 (docx templates), but feel free to re-raise it for pandoc scholar.

A discussion leading to a semi-standardization of author and affiliation metadata might be valuable.  The pandoc-discuss mailing list is probably the best place to initiate such a discussion.

**Comment by iandol** [comment]
@tarleb: I think this problem is actually a bug with the pandoc docx writer. It should be able to extract the author names from the pandoc YAML metadata, even if they have institute's attached. 

This works in docx, I get the author in the final document:

```yaml
author:
    - John Doe
```

But the author name disappears if I use:

```yaml
author:
  - John Doe:
      institute:
        - IoO
```

I'm **not** expecting "institute" to make it to the docx (although it could be added to the docx writer right?) _I just don't want the author to disappear completely_.

This is handled around 
```haskell
authors <- withParaProp (pCustomStyle "Author") $ blocksToOpenXML opts $
       map Para auths
```
https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Docx.hs#L772 

...but haskell looks like klingon to me so I don't know how to modify it to stop it breaking. This may be a trivial fix, and I don't think waiting for docx templates (which would also be awesome) should stop this being fixed; so I would ask for this to be reopened. Thanks!

**Comment by jgm** [comment]
+++ Ian [Jun 01 17 19:24 ]:
>   [1]@tarleb: I think this problem is actually a bug with the pandoc docx
>   writer. It should be able to extract the author names from the pandoc
>   YAML metadata, even if they have institute's attached.
>
>   This works in docx, I get the author in the final document:
>
>author:
>    - John Doe
>
>   But the author name disappears if I use:
>
>author:
>  - John Doe:
>      institute:
>        - IoO
>
>   I'm not expecting "institute" to make it to the docx (although it could
>   be added to the docx writer right?) I just don't want the author to
>   disappear completely.

Well, there's a huge difference between these:  in the
second case, 'John Doe' is the name of a metadata key
(an object {institute: IoO}), not a metadata value.

I guess in pandoc-scholar @tarleb has cleverly arranged
things to expect this, but what seems more natural to me
(from an internal representation point of view) is:

    author:
    - name: John Doe
    - institute: IoO

Pandoc can be taught to recognize these forms:  in the
latter case, template changes are generally sufficient
(except for docx, which doesn't have a template).
In the former case, and for docx output, code changes
would be needed.

**Comment by iandol** [comment]
Using the online YAML parser http://yaml-online-parser.appspot.com:

```YAML
author:
    - John Doe

author:
  - John Doe:
      institute:
        - IoO
```

maps to canonical:

```YAML
---
!!map {
  ? !!str "author"
  : !!seq [
    !!str "John Doe",
  ],
  ? !!str "author"
  : !!seq [
    !!map {
      ? !!str "John Doe"
      : !!map {
        ? !!str "institute"
        : !!seq [
          !!str "MoD",
        ],
      },
    },
  ],
}
```

So the code would need to check if `seq.str` then use `str`, otherwise try `seq.map.str`

**Comment by jgm** [comment]
Yes, I know it's possible to do this.  But I'm not sold on
the format that allows the author name to be used as key.
That seems a bit too fancy to me.

**Comment by iandol** [comment]
@jgm: I think it needs to be something like:

```yaml
authora:
  -
    name: John Doe
    institute: IoO
```
otherwise no way to represent more than one author?

**Comment by iandol** [comment]
...which can be a bit more compact:
```yaml
author:
  - name: John Doe
    institute: CoD
  - name: Abe Lincoln
  - name: Jezz Prinz
```

**Comment by jgm** [comment]
+++ Ian [Jun 02 17 02:08 ]:
>author:
>  - name: John Doe
>    institute: CoD
>  - name: Abe Lincoln
>  - name: Jezz Prinz

This is the format I'd find most natural, but I think we
should also support these forms:

    author:
      name: John Doe
      institute: CoD

and

    author: John Ooe

We already support (for authors) either a single author or
a list, so it would just be a matter of supporting a
either a string or a structured object for each.

**Comment by tarleb** [comment]
> ``` yaml
> author:
>  - name: John Doe
>    institute: CoD
>  - name: Abe Lincoln
>  - name: Jezz Prinz
> ```

FWIW: this format is also supported by pandoc scholar and actually the format that's used internally.

**Comment by iandol** [comment]
OK, that format seems ideal. I don't quite understand how Pandoc will support the other options, will you internally rewrite `author: John Doe` into `author: {name: John Doe}`, so that all templates should consistently use author.name field from now on?

Also I still don't understand how this form works, as the `institute` is not linked in any way to the `author` (i.e. they are all siblings):

 ```yaml
 author:
      name: John Doe
      institute: CoD
      name: Joanna Doe
      institute: MoD
```

I'm happy to help rewrite the default templates.

**Comment by tarleb** [comment]
It would be great if pandoc would support this.  I'll try to document the design decisions that went into pandoc scholar in the hope that it might become useful.

The objects in the `author` array are enriched with as much info as possible as to make template writing simple.  Each author object is guaranteed to have the properties *name* and *institute* (which I know believe would be better renamed to *affiliation*).  Additional properties like *email*, *correspondence*, *equal_contributor* etc. are optional. Futhermore, an array of *institute_indices* is defined for each author, the contents of which relates to the *institute* array.

The *institute* array contains the list of affiliation objects. Each affiliation has a *name* and an *index* (i.e. the position in the array, starting with 1).

I found this structure to be enough for basic templates. For more advanced templates, additional information is included in the authors object: First and last authors are marked with a *first_author* and *last_author*, respectively.

Linking affiliations with multiple authors should be simple for writers, which is why the abbrev/object combination was introduced:

``` yaml
- abbr:
    name: entity name
    other_properties: …
```

Which is rewritten internally into

``` yaml
- name: entity name
  abbreviation: abbr
  other_properties: …
```

The *abbr* is used as the name if no name is defined.

This allows to specify an abbreviation for an affiliation object, which can then be referenced in the author's affiliation list:

```
institute:
  - fop:
    name: Federation of Planets
author:
  - Kathrine Janeway:
    institute: fop
  - Jean-Luc Picard
    institute: fop
```

**Comment by iandol** [comment]
Yes, that syntax looks perfect for academic content!!!

There are two parts to this I suppose. The first is just making sure author names don't break Pandoc templates as I think name and title are the most important metadata generally? 

Then it would be good to think about how to handle "affiliation" and other fields once the name has been fixed (and I agree "affiliation" is better than "institute").
