### ISSUE TITLE
Handling of duplicate references with --reference-location

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3701]
We might want to change how we currently handle duplicates with `--reference-location=block` (or `section`).

Currently:
```
% pandoc --reference-location=block  -t markdown --reference-links
[a](u)

[a](u)
^D
[a]

  [a]: u

[a][1]

  [1]: u
```
The `[1]` is used the second time in order to avoid the following output, which would cause a "duplicate link reference" warning if we did `pandoc -f markdown`.

But it would be nicer to have this output:
```
[a]

  [a]: u

[a]

  [a]: u
```
Though this has a duplicate link reference, it's really harmless, because the definitions are identical.
So my thought is that we should change the writer to emit the above output, and change the reader so that it doesn't issue warnings for duplicate link references that are identical.  After all, in this style it's convenient sometimes to repeat references.

**Comment by jgm** [comment]
@jkr I'd be curious if you have any thoughts about this issue.

**Comment by jkr** [comment]
Sorry I missed this, but yep -- I agree with you here.
