### ISSUE TITLE
LaTeX writer creates numbered headings

### ISSUE THREAD

**Issue by RobertGoulding** [jgm/pandoc#3710]
pandoc 1.19.2.1

The manual says:

-N, --number-sections
Number section headings in LaTeX, ConTeXt, HTML, or EPUB output. By default, sections are not numbered.

This minimal example:
~~~
# The first section

This is the first section.
~~~
The output from `pandoc -t latex`

~~~
\section{The first section}\label{the-first-section}

This is the first section.
~~~

But by default the sections should be *unnumbered*, so that one should see

~~~
\section*{The first section}\label{the-first-section}
~~~
The output from `pandoc -t latex -N` is identical.

**Comment by jgm** [comment]
We handle that in the template instead.  The default
template has:

$if(numbersections)$
\setcounter{secnumdepth}{$if(secnumdepth)$$secnumdepth$$else$5$endif$}
$else$
\setcounter{secnumdepth}{0}
$endif$

So no change to the body output is needed.

**Comment by jgm** [comment]
It would be possible to change things so that, instead of the above hack, `\section*` is used.
This would work better for fragments.
I don't recall whether there was a reason for the above approach.

**Comment by avastmick** [comment]
pandoc 2.0.2

I've only recently upgraded to Pandoc 2.0. And now I always get numbered sections, regardless of flag when outputting to PDF.

Expected: No numbering of headings unless the ``-N`` or ``--number-section`` flag is set.

Actual:
```
# Heading
text

## Sub-heading
subtext
```
always gives a numbered output, unless I put in the ``{-}`` for each heading...

The expected output was seen in the version I was using in May (not sure what it was - have to go back through git history)

The command I use is:

```
pandoc --pdf-engine=xelatex --template resume-template.tex --from markdown -o cv/$(CVFILE).pdf resume.md
```

The only change to this I have made is to change the flag ``--latex-engine`` to ``--pdf-engine``

**Comment by jgm** [comment]
I can't reproduce this with the default template.  So, no
doubt it has something to do with the custom template you're
using.

The default template has

    $if(numbersections)$
    \setcounter{secnumdepth}{$if(secnumdepth)$$secnumdepth$$else$5$endif$}
    $else$
    \setcounter{secnumdepth}{0}
    $endif$

and you need something similar to this in your custom
template, since LaTeX's default is to number the sections.

**Comment by jgm** [comment]
Anyway, this issue can be closed.
