### ISSUE TITLE
HTML to markdown : empty tag gives bad markdown

### ISSUE THREAD

**Issue by sloonz** [jgm/pandoc#3715]
Pandoc version : 

```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4, skylighting 0.1.1.5
Default user data directory: /home/simon/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Converting a HTML document containing an empty `<strong>` tag results in a `****` sequence, which many (including pandoc) markdown implementations interpret as 4 literal `*` characters. Similar issue with `<em>` (results in `**`)

* Command to reproduce : 

```
echo '<p>Hello<strong></strong></p>' | pandoc -f html -t markdown | pandoc -f markdown -t html
```

* Expected result :

Either `<p>Hello</p>` or `<p>Hello<strong></strong></p>`

* Actual result : 

`<p>Hello****</p>`

**Comment by jgm** [comment]
I'm inclined to handle this in the Markdown writer by just printing nothing for `Strong []`.

**Comment by caseymrm** [comment]
Easy enough to fix with a regexp, but for the record this still happens with `commonmark` and `gfm`:

```
$ echo '<p>Hello<strong></strong></p>' | pandoc -f html -t commonmark | pandoc -f commonmark -t html
<p>Hello****</p>

$ echo '<p>Hello<strong></strong></p>' | pandoc -f html -t gfm | pandoc -f gfm -t html
<p>Hello****</p>
```

**Comment by jgm** [comment]
This is correct behavior according to the commonmark spec.

**Comment by jgm** [comment]
Since the commonmark and gfm writers currently use cmark-gfm's markdown writer, the best solution would be to change this in the C library (cmark and cmark-gfm).  I suggest you submit an issue to commonmark/cmark.

**Comment by caseymrm** [comment]
Thanks for taking a look, and for everything.

Actually in thinking about this further, I think it's a reasonable choice for the writers to output the asterisks from the markdown string `Hello****` (principle of least astonishment).

I think it's actually the html input that should be changed- seems like `<strong>\w*</strong>` should be treated as an empty string. Not sure if there's a downside to that I'm not seeing.

Thanks again for your time.
