### ISSUE TITLE
Bad interaction of <span> and normalize eats spaces

### ISSUE THREAD

**Issue by bucklereed** [jgm/pandoc#3718]
Test case: `echo 'foo<span> bar </span>bar' | pandoc  -f html -t markdown_strict --normalize`

Output (note missing space between bar and baz):

```
foo<span> bar</span>baz
```

Expected (with the space between bar and baz):

```
foo<span> bar </span>baz
```

pandoc version: 1.19.2.1

**Comment by jgm** [comment]
`--normalize` has been removed in 8165014df679338d5bf228d84efc74b2c5ac39d2. And the default behavior is correct:

```
% echo 'foo<span> bar </span>bar' | pandoc -f html -t markdown_strict 
foo<span> bar </span>bar
```
So , closing.
