### ISSUE TITLE
EPUB OCF structure

### ISSUE THREAD

**Issue by ismith-cm** [jgm/pandoc#3720]
I would like to recommend modifying the OCF structure produced through the EPUB writers.

The main reason is due to retail channel and IDPF recommendation. It is strongly recommended by most of the retail channels, that are accepting EPUB, to contain all content related files in an organized subdirectory. It is also a more organized structure to deal with if anyone has to work on the EPUB after it is produced by pandoc.

It's really just a organizational preference, but I think it could be a valuable addition to pandoc if the resulting arrangement could be configurable. I say configurable, because some recommend "OEBPS", some recommend "OPS" and some recommend "EPUB" as the content subdirectory. 

Here is the existing structure:
- mimetype
- META-INF/
  - com.apple.ibooks.display-options.xml
  - container.xml
- media/
  - cover.jpg
  - fig1.jpg
- font.otf
- stylesheet.css
- content.opf
- toc.ncx
- ch001.xhtml

I'm recommending the below:

- mimetype
- META-INF/
  - com.apple.ibooks.display-options.xml
  - container.xml
- EPUB/   _<<--configurable-->>_
  - fonts/  _<<--static-->>_
    - font.otf
  - images/  _<<--static-->>_
    - cover.jpg
    - fig1.jpg
  - styles/  _<<--static-->>_
    - stylesheet.css
  - content.opf
  - toc.ncx
  - text/  _<<--static-->>_
    - ch001.xhtml

**Comment by jgm** [comment]
I suggest a new option `--epub-subdirectory=STRING`, to specify the subdirectory in the OCF container that will contain the contents of the EPUB.  Default would be `EPUB`.  To avoid problems, the STRING could be sanity-checked and rejected if it contains anything other than ASCII letters.

Directory structure would then be arranged as above.

I suspect the changes needed would be fairly straightforward, but I haven't looked into this.  We'd probably need a new field in WriterOptions.

**Comment by jgm** [comment]
Is it important whether the subdirectory is called `images/` or `media/` (we chose `media` because it might contain e.g. movies).

**Comment by jgm** [comment]
I've added the `--epub-subdirectory` option.

@ismith-cm, could you please test?  After tonight there should be a binary from pandoc-extras/pandoc-nightly, if you don't want to compile from source.

I want to make sure images, links between chapters, fonts, etc. still work.

**Comment by jgm** [comment]
Reopening: there are definitely bugs still.

**Comment by jgm** [comment]
OK, with commit 4a6868885d961b0df782c19f70dd725148446633 I'm reasonably confident that this works.  Please test further.

One potential worry is that existing epub production workflows will break, because they contain links to fonts, for example, and fonts have moved to `fonts/`.  In any case we should try to document carefully the things that might break/might need to be fixed in upgrading.
