### ISSUE TITLE
Example lists with brackets

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [jgm/pandoc#3721]
Not a bug, just an enhancement suggestion.

When using the extension `example_lists`, a special list marker `@` can be used for sequentially numbered examples, but only if it is found inside parenthesis, like this:

```
(@good)  This is a good example.

As (@good) illustrates, ...
```

It would be nice if this could be used with brackets too, like this:

```
[@good]  This is a good example.

As [@good] illustrates, ...
```

By the way, thanks for this great tool!

**Comment by jgm** [comment]
Actually, example lists can be used with any of the ordered list delimiter types pandoc supports:
```
1.
(1)
1)
```
We could in principle add support for
```
[1]
```
and then example lists would work with this -- as would other kinds of lists.

But I'm against this; there's too much risk of ambiguity given the uses square brackets already have. Note that `[@good]` will normally be interpreted as a citation.

**Comment by usernameiwantedwasalreadytaken** [comment]
Ok, thanks anyways.
