### ISSUE TITLE
markdown (extra) and HTML reversibility (footnotes example)

### ISSUE THREAD

**Issue by Netsaver** [jgm/pandoc#3724]
Hi, I do not want to repeat any earlier discussion, but I couldn't find any on this matter: I apologize if not being so.
I would like to discuss the opportunity to get a *full reversibility of the HTML code translated from lightweight markup*.
Let's take a certain environment using markdown for input and pandoc for HTML preview and export: there will be a collection of source md files and generated HTML files.
Now suppose that later in that environment, or in a different one, only the HTML files are available.
Or, as alternative, let's take an environment working basically with HTML files and translating to markdown only for user modifications on-the-fly.
In such cases, it would be useful having a full reversible notation, so that the transformation:
**MDcode --> HTML --> MDcode** could give back exactly the same source.  
As example, see what happens with footnotes:
```
That's some text with a footnote.[^1]

[^1]: And that's the footnote.
```
The above markdown code will be translated into:
```
<p>That’s some text with a footnote.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></p>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>And that’s the footnote.<a href="#fnref1">↩</a></p></li>
</ol>
</div>
```
Now, executing again the transformation to markdown:
```
That’s some text with a footnote.[^1^]

<div class="footnotes">

------------------------------------------------------------------------

1.  <div id="fn1">

    </div>

    And that’s the footnote.[↩]

</div>

  [^1^]: #fn1{#fnref1 .footnoteRef}
  [↩]: #fnref1
```
Repeating forward and backward these passages, both md and HTML codes will explode!
Specifically, pandoc _html to markdown_ converter ignores the `footnotes` and `footnoteRef` classes, but anyway reconstructing the original code is not easy. Maybe it would still be possible reversing the original code by making unique  conventions about _footnote section_, _block structure_, _classnames_, etc.
I suspect this is a general behavior for all [Common idioms without dedicated elements](https://www.w3.org/TR/html5/common-idioms.html#common-idioms)...
Of course it wouldn't be possible when performing these passages on different environments.

Please, consider also an application translating webpages into markdown articles.
In this case it would no more be possible to perform a **semantic conversion**, but at least, once performed the 1st passage to markdown (and having accepted the related _semantic loss_), from that moment onwards it should no longer cumulate any garbage...  

In other terms, I'ld prefer _lightweight constructs which can be made corresponding uniquely to html constructs_. Probably for most application it would not be necessary, but finally we're speaking of a new standard and we do not really know in how many (and which many) different environments these processes will work, so... **the more general, the more robust**...

What do you think about? (and sorry for the english)
Paul Netsaver, Rome (IT)

**Comment by ickc** [comment]
> I would like to discuss the opportunity to get a full reversibility of the HTML code translated from lightweight markup.

I had a somewhat similar discussions with the others about this on pandoc-discuss. And this is incredibly hard to achieve.

First, when you said "full reversibility", this is mission impossible, because each transform is lossy. But I'm going to relax this to being "idempotent". Search this word on pandoc-discuss and you'll see a discussion on this. And simply put it is very hard, and practically undoable (but the situation can be improved case by case whenever there's obviously wrong behavior).

In your example, I believe if you convert the generated HTML to markdown by turning off the "native div" extension, the "problem" you see will go away.

I think this issue should be closed, and probably further discussion on this would better served in pandoc-discuss.

**Comment by Netsaver** [comment]
Ok, I got the point.
I've read the discussion [3051](https://github.com/jgm/pandoc/issues/3051) and was not developed around this interesting matter (maybe for the object), could you eventually open a proper one?
I understand that any generic transformation is lossy, but I deem could be both interesting and useful at least to:
* reduce the _**semantic losses**_, that is keeping the same meaning for corresponding constructs in md and HTML as for footnotes: for instance, the `<hr/>` should not be a result of the forward translation (leaving it to _CSS_) and the _footnotes_ and _footnoteRef_ classes should be used to rebuild the md syntax for footnotes in the back translation, instead of generic links (sorry but I used the <http://pandoc.org/try/> interface, so didn't find how to disable _native divs_).
* accept secondary losses (whitespaces, breaks, etc.).
* try to converge to _idempotent_ constructs when sanitizing markdown and mostly when converting back and forth beetween html and md, e.g. no further variations after 1 or 2 passages.

I also understand that it is an impossible goal to reach when serving so different markups and flavours (what I think is the main purpose of pandoc), anyway what I was suggesting was to:
* select a flavour (e.g. _pandoc md_) on which concentrate some efforts in the direction of having a conceptual *equivalence* with html (in real terms, with the _subset_ of html which is object of the transformation).
* test the proposed syntaxes forth and back against HTML, in order to have more _stable_ solutions (the more _'robust against translations'_ than possible), at least when they are standalone, not mixed each other.

IMHO this would be a plus for the flavour selected (I don't know if the _neutrality_ versus all markups is a goal or not) and it would allow a working environment to keep the published (HTML) code only, converting to the lightweight source on the fly on client side for user modifications.

As alternative, if this goal is totally unreachable, would it be possible to **optionally transfer the source md code in some metadata field** during translation (e.g. saved as txt resource of the page and linked in the _head metadata_ as for CSS)? 
In this case, when translating backwards, the original code could be retrieved from pandoc (if available).

Thanks for the attention and regards,
Netsaver Paul (Rome, IT)

**Comment by ickc** [comment]
I still think that this "issue" will fit [pandoc-discuss - Google Groups](https://groups.google.com/forum/#!forum/pandoc-discuss) better:

1. If you raise the same "issue" there, I bet there will be more suggestions/opinions by the others.
2. The points here are more like suggestions and further improvements but not a particular "issue" (except for the example you've given, but can probably be solved by turning off the native div extension)

**Comment by Netsaver** [comment]
Ok, I moved the discussion to [Google Groups](https://groups.google.com/forum/#!topic/pandoc-discuss/LaDpHlLedPo). I agree this post does not address specific issues, but rather proposes a design goal.
Anyway, if you agree, the last one _"optionally transfer the source md code in some metadata field during translation (e.g. saved as txt resource of the page and linked in the head metadata as for CSS)"_ can be flagged as enhancement request.
Regards,
Netsaver

**Comment by jgm** [comment]
I think the goal of getting reversibility when possible is a
good one in general, it's just a matter of developer time,
and this isn't very high on the priority list.

As for putting the source text into the generated HTML:
I fail to see how this would be helpful.  Why not just store
the markdown source together with the HTML in your database?
You don't save any bytes by embedding this in the HTML page
itself (and you'll have a bulkier page that will take more
time to download and render).

If you want the source to be retrievable client-side by
JavaScript, you could always serve the source at a separate
URL and link to it in the HTML page.  (Pandoc's custom
templates and variables give you an easy way to add such
a link.)
