### ISSUE TITLE
HTML: Adding links to headlines

### ISSUE THREAD

**Issue by chpio** [jgm/pandoc#3725]
hi,

eg github adds links to headlines. This allows you to get a direct link to a chapter by clicking on the headline.

**Comment by mb21** [comment]
You can either write a pandoc filter to transform all headers to headers with links or do so manually, e.g.

    # [test title](#test-title)

Please ask on pandoc-discuss for further questions...

**Comment by jgm** [comment]
+++ chpio [Jun 06 17 01:51 ]:
>   hi,
>
>   eg github adds links to headlines. This allows you to get a direct link
>   to a chapter by clicking on the headline.

I believe github does this with some JavaScript.
You could do the same.
