### ISSUE TITLE
Question: What is pandoc's standard behavior about RAM consumption?

### ISSUE THREAD

**Issue by stefanos82** [jgm/pandoc#3729]
I'm using Pandoc 1.17.2 under Debian testing 64-bit, fully updated and tried to convert PHP's single HTML file documentation to LaTeX with the following command:

```bash
pandoc php_manual_en.html -f html -t latex -s -o manual.tex
```

As soon as I hit the Enter key, it jumped from `516MiB / 7.46GiB` to `7.29GiB / 7.46GiB`. I had to kill process to bring my system back to normal behavior.

Is this kind of behavior normal?

**Comment by ickc** [comment]
Yes, it is normal. There's already an issue on RAM use. And try the latest version of pandoc to see if it has improved. Otherwise you either have to break it down to smaller files or add more RAM

**Comment by jgm** [comment]
See the discussion in #3669 (which also concerns conversion of the PHP manual!).

**Comment by jgm** [comment]
Also #3169.  Closing this as a duplicate.
