### ISSUE TITLE
Markdown parsing confusion with code block after list

### ISSUE THREAD

**Issue by pri22296** [jgm/pandoc#3733]
converting the following as `markdown_github` to `html`

``````
- Item1
- Item2
```yaml
section:
  - Code Line1
  - Code Line2
```
``````
 gives

```
<ul>
<li>Item1</li>
<li>Item2<br />
```yaml<br />
section:</li>
<li>Code Line1</li>
<li>Code Line2<br />
```</li>
</ul>
```

while github renders it correctly.
![screenshot 140](https://user-images.githubusercontent.com/11555869/27011337-0dfab4f2-4ed7-11e7-8002-fbfff066b806.png)

It seems pandoc's `markdown_github` reader is not able to parse the code block correctly due to presence of `-` inside the codeblock. If `-` is removed inside the code block, it is converted correctly.

Pandoc version : 1.19.2

**Comment by jgm** [comment]
Here's a smaller case (it has nothing to do with `markdown_github` specifically, so this just uses default pandoc `markdown`):

````
% pandoc
- a
```
- b
```
^D
<ul>
<li>a ```</li>
<li>b ```</li>
</ul>
````

Pandoc's method for identifying the raw text of a list item is apparently not sensitive to fenced code, when there is no blank line before the fence.

**Comment by jgm** [comment]
Note that pandoc's manual says:

> Like regular code blocks, fenced code blocks must be separated
> from surrounding text by blank lines.

However, pandoc's markdown doesn't obey this consistently:
````
% pandoc
a
```
b
```
^D
<p>a</p>
<pre><code>b</code></pre>
````

And of course, github allows the fences without blank space.

Note: GitHub is now using commonmark, so you could try `pandoc -f commonmark`.  This gives you basic commonmark without the GitHub extensions (e.g. tables), but it might work better in your case.

**Comment by jgm** [comment]
See #3509 for the best way forward for accurate parsing of `markdown_github`. However, as the above shows, there are issues here too for pandoc's markdown.
