### ISSUE TITLE
Tables get randomly rendered as HTML instead of Markdown

### ISSUE THREAD

**Issue by Pastafarianist** [jgm/pandoc#3734]
This might be by design, but IMO this is still inconvenient for the user, hence I'm reporting this here instead of asking on the mailing list.

When using the `markdown_github` writer, some tables get randomly rendered as HTML.

`tables_in.md`:

```markdown
Table 1:

| aaaaaaaaaa | bbbbb | ccccccccccc                                       |
|------------|-------|---------------------------------------------------|
| a          | bb    | ccccccccccccccccccccccccccccccccccccccccccccccccc |

Table 2:

| aaaaaaaaaaaa | bbbbb | ccccccccccc                                                              |
|--------------|-------|--------------------------------------------------------------------------|
| aaaaaaaaaaaa |       | cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc |
```

```
$ pandoc --from=markdown --to=markdown_github --columns=80 tables_in.md
Table 1:

| aaaaaaaaaa | bbbbb | ccccccccccc                                       |
|------------|-------|---------------------------------------------------|
| a          | bb    | ccccccccccccccccccccccccccccccccccccccccccccccccc |

Table 2:

<table>
<colgroup>
<col width="15%" />
<col width="8%" />
<col width="76%" />
</colgroup>
<thead>
<tr class="header">
<th>aaaaaaaaaaaa</th>
<th>bbbbb</th>
<th>ccccccccccc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>aaaaaaaaaaaa</td>
<td></td>
<td>cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc</td>
</tr>
</tbody>
</table>
```

However, if I set more `columns`, everything works as expected:

```
$ pandoc --from=markdown --to=markdown_github --columns=100 tables_in.md
Table 1:

| aaaaaaaaaa | bbbbb | ccccccccccc                                       |
|------------|-------|---------------------------------------------------|
| a          | bb    | ccccccccccccccccccccccccccccccccccccccccccccccccc |

Table 2:

| aaaaaaaaaaaa | bbbbb | ccccccccccc                                                              |
|--------------|-------|--------------------------------------------------------------------------|
| aaaaaaaaaaaa |       | cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc |
```

Looking at the [code](https://github.com/jgm/pandoc/blob/fa719d026464619dd51714620470998ab5d18e17/src/Text/Pandoc/Writers/Markdown.hs#L563), I can't see why this would be the case, although I don't understand what purpose `isSimple` serves exactly. Also, the presence of `isSimple` within a `case` branch for `Ext_pipe_tables` looks like a bug.

I think this is a bug since this behavior is quite unexpected. However, if it isn't, I would be happy to find out how to force rendering all tables as `pipe_tables`.

```
$ pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4, skylighting 0.1.1.5
```

**Comment by jgm** [comment]
If you compare the `-t native` output for your two tables, you'll see that they are different.
With the second, extra-long table, you get relative width information which is based on the lengths of the header lines (see the manual under pipe tables, which also explains why it changes when you increase the column width).
This can't be represented in gfm pipe tables, so we fall back to HTML.

**Comment by ickc** [comment]
> When using the markdown_github writer, some tables get randomly rendered as HTML.

It is not random. Whenever any representation cannot be output as markdown-ish-markdown (in the variant you choose), then since any valid HTML is valid markdown, it will be output as HTML-markdown. And this behavior is not unique to `markdown_github` either.

**Comment by Pastafarianist** [comment]
In the case that this is expected behavior, can I ask you to treat this as a feature request? "Allow wide tables be printed as `pipe_tables`".

**Comment by ickc** [comment]
> can I ask you to treat this as a feature request? "Allow wide tables be printed as pipe_tables".

This feature has already been existed, as you have written: define a larger column width. You might want to specify it as large as you want (I think I have a build currently uses 999 for this).

This can feel counter-intuitive at first, but you'll get used to it. Suggestions have been made about this, but seems like this is the best already. Just remember column affects both the wrap and tables, and if you want it off, you need to specified wrap to be none and column to be a very large number.

**Comment by jgm** [comment]
I can re-open it, but I'm going to close it again unless we can come up with a good specific alternative that works.

**Comment by jgm** [comment]
I suppose the alternative would be to render tables with simple inline cell contents as pipe tables even if there is width information.  This would mean loss of information in some cases, but you may be right that in most cases this would be the preferred output.

**Comment by ickc** [comment]
> This would mean loss of information in some cases, but you may be right that in most cases this would be the preferred output.

Would GitHub's markdown (or other markdown variants) care about this width information?

And I think as far as parsing to markdown is concerned, people care more about having a markdown representation that captures its structural information rather than presentational information (don't know if these are the right words to classify it, I mean, like the content vs. style).

Don't know what's the implication to the idempotent condition though. But as long as it is stable (after n-iteration) I think it's ok.

Another idea: a cli flag to turn off table width info completely. i.e. all zeros. I think I got an error before when the widths are all zeros (like simple table) but with complex cells that requires a minipage in LaTeX output though.

By the way, up till now I'm still uncomfortable to control the table widths through the markdown table extensions. This is one of the primary reasons I wrote pantable, that I hope to control what pandoc's AST granted me without needing to tamper with those difficult-to-edit syntaxes (at least not without emacs?). To me, the only thing in pandoc's markdown that's difficult to type/edit are the tables. This is the only thing I would wish I'm not writing in plain-text. I guess that's why pipe table is popular because using the tab and with the help of editors aligning them, it is so much easier to write (albeit with limitations). That's why in a pandoc-discuss thread I suggested extending the pipe table in pandoc to kramdown's table syntax, which is like pandoc's grid table and pipe table combined, allowing tabs, alignments, complex cells in the mix, etc. i.e. the power of grid table with the simplicity of pipe tables with tabs.

**Comment by jgm** [comment]
I have a fix in the issue3734 branch, but I'm not sure I like it.
It seems to me that there may be many cases where one would not want the width information thrown away.

What if we use HTML in this case, if the `raw_html` extension is enabled, and use a pipe table otherwise?

**Comment by jgm** [comment]
So now the solution will be: use `markdown_github-raw_html` if you don't want the fallback to HTML in these cases.

**Comment by jgm** [comment]
Note that the same issues are going to occur with `gfm`, the new replacement for `markdown_github`.

**Comment by jgm** [comment]
Changed `gfm` output so that pipe tables will be used when possible, even if relative width information is thrown out.

**Comment by ezra100** [comment]
Hi,
I ran into the same problem, after a few test I've found out that if you add a line break it'll fall back to html.
[Here's](https://docs.google.com/document/d/1c9nKOkQ-VVF0j_6OM3Sdz_eedKpRa_KqaLhkhqtfN1s/edit?usp=sharing) the document, I ran the command `pandoc --from=odt -t gfm -s  --out=text.md < './Untitled document (3).odt'` and the output is:
`<table>
<tbody>
<tr class="odd">
<td></td>
<td><p>Line break</p>
<p>here.</p></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
`

**Comment by ec1oud** [comment]
I agree, embedded html is not the way to write tables in gfm format.  Better to use the gfm table extension.  As it stands, I can't find any markdown output format or option that actually does this.  The "markdown" output format is pandoc's own, with a different and incompatible table format that cannot be parsed by md4c, for example.

ATM I'm just trying to convert an rtf file with tables into a markdown file that Qt can read.

**Comment by jgm** [comment]
Pandoc supports grid tables, but grid tables have limitations (they can't take block-level content or colspans or rowspans, for example). Pandoc will use a grid table when possible, but when the limitations don't permit it, it has no choice but to fall back to HTML.

**Comment by annanyearian** [comment]
This causes issues when converting to use with [MyST](https://myst-parser.readthedocs.io) to output PDF files, it uses gfm syntax for tables.

Markup **cannot** be HTML for PDF output to work correctly, and there doesn't seem to be a clear way to get pandoc to output gfm tables.

Looks like only solutions right now are pre-processing the HTML to remove block tags.

**Comment by tarleb** [comment]
@annanyearian see https://pandoc.org/faqs.html#pandoc-adds-column-widths-to-pipe-tables-when-any-line-is-wider-than-the-setting-for---columns.-how-can-i-prevent-this

**Comment by jgm** [comment]
> Looks like only solutions right now are pre-processing the HTML to remove block tags.

Block-level content can't be included in pipe table cells (in gfm syntax).  So yes, if your input can't be represented that way you must preprocess it. There's nothing pandoc could do about this.
