### ISSUE TITLE
preserved line breaks disrupt syntax of headers in markdown

### ISSUE THREAD

**Issue by rose00** [jgm/pandoc#3736]
If HTML input has line breaks inside headers, and the `--wrap=auto` option
is given, then the emitted markdown may have syntax errors in it.

```
$ ( echo '<h2 style="impeccable">Nice Title';
  echo 'with Nice Ending</h2>') | pandoc --wrap=auto -f html -t markdown
Nice Title with Nice Ending {#nice-title-with-nice-ending style="impeccable"}
---------------------------
$ ( echo '<h2 style="impeccable">Nice Title';
  echo 'with Nice Ending</h2>') | pandoc --wrap=preserve -f html -t markdown
Nice Title
with Nice Ending {#nice-title-with-nice-ending style="impeccable"}
--------------—
````

This manifests as markdown syntax leaking into an HTML file after
the broken markdown is retranslated to HTML.  The preserved newline
interferes with the syntax of section headers, which are supposed to
be one-liners.

Suggested fix:  Do not preserve source newlines in headers.
Or, find a way to escape newlines in multi-line headers.

BTW, I like the `wrap=auto` option, because it gives a certain stability
to the output of the HTML to markdown translation.  This stability
means that, when comparing various versions of the HTML using
line-oriented diff tools, there are fewer spurious diffs due to rewrapping.
Arguably I should be using HTML-oriented diff tools, but they are
less widely available.

Workaround:  Preprocess the HTML to suppress newlines within headers.

````
$ sed $'/<h[1-6][ >]/{:L\n;/<\\/h[1-6]>/{p;d;};N;s/\\n */ /;bL\n;}'
````

**Comment by jgm** [comment]
Here's what I get with the current dev version:
```
% ( echo '<h2 style="impeccable">Nice Title';
>   echo 'with Nice Ending</h2>') | pandoc --wrap=auto -f html -t markdown
Nice Title with Nice Ending {#nice-title-with-nice-ending style="impeccable"}
---------------------------
```
That looks fine.  But I think you must have meant `--wrap=preserve` (not `auto`).
```
% ( echo '<h2 style="impeccable">Nice Title';   echo 'with Nice Ending</h2>') | pandoc --wrap=preserve -f html -t markdown
Nice Title
with Nice Ending {#nice-title-with-nice-ending style="impeccable"}
----------------
```
That is a bug indeed.  We should treat soft breaks as spaces inside headers.

**Comment by jgm** [comment]
Note: one way to handle this would be to add a new combinator to Text.Pandoc.Pretty that forces a Doc to lie on a single line.
