### ISSUE TITLE
YAML Blocks Issues

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#3737]
I'be been testing extensively concatenating (pandoc) markdown files with YAML front-matter followed by other YAML files, and noticed some issues.

If the YAML block has no values, or contains only comments, the block is treated as markdown instead — the opening (or closing) `---` is treated as a horizontal rule, the closing `...` as three-dots (or ellipsis), and the comment's pound symbols (`#`) as level one headers.

Also, when the last input file is a YAML file, I noticed that if comments precede the var definition pandoc fails to reckognize the block as YAML, and parses it as markdown:

``` yaml

---

# ==============================================================================
#                                /aaa/butler.yaml                               
# ==============================================================================

title: "Title set in butler.yaml"

...
```

... but if I move the line `title: [...]` before the comments lines, it works correctly.

In some workflows it can be convenient to use predefined templates with commented-out front-matter variables in order to remind users of the available vars/options, along with some instructions.

I understand that there are cases in which it can be tricky to distinguish between a valueless YAML block and the occurence of a genuine markdown horiziontal rule followed by another rule or a line with three dots. The same issue popped up in SublimeText's Markdown-Preview package:

- [SublimeText Markdown-Preview #392](https://github.com/revolunet/sublimetext-markdown-preview/issues/392)

... where the solution adopted takes in consideration the position of the potential block — ie: if it's at the beginning of the file it is likely to be YAML frontmatter. After all, valueless commented out templates are unlikely to appear in the middle of a source file.

**Comment by jgm** [comment]
> I understand that there are cases in which it can be tricky to distinguish between a valueless YAML block and the occurence of a genuine markdown horiziontal rule followed by another rule or a line with three dots.

This is exactly the issue.  If the opening `---` is followed by a blank line, we treat it as a horizontal rule.

> ... where the solution adopted takes in consideration the position of the potential block — ie: if it's at the beginning of the file it is likely to be YAML frontmatter. After all, valueless commented out templates are unlikely to appear in the middle of a source file.

Nothing rules out having a horizontal rule at the beginning of a file, so I wouldn't want to adopt that heuristic just for this case.  Note also that in pandoc, YAML metadata blocks can occur anywhere in the document, not just at the front.

There's no obvious reason why you need blank space before the comment in your template.  Why not just remove that and get on with it?

**Comment by tajmone** [comment]
Thanks for the reply.
I overlooked the blank lines issue — _mea culpa_.
