### ISSUE TITLE
Textile to RST conversion with colspan produces malformed table

### ISSUE THREAD

**Issue by m-aciek** [jgm/pandoc#3738]
Original Textile fragment:
```
table{background:lightgreen}.
|\4=.**Wyjście**|
|_.Nazwa |_.Obligatoryjność|_.Typ |_.Opis |
```
Command used: `pandoc --from textile --to rst`
Fragment output:
```
+---------------+-------------------+-------+--------+
| **Wyjście**   |
+---------------+-------------------+-------+--------+
| Nazwa         | Obligatoryjność   | Typ   | Opis   |
+---------------+-------------------+-------+--------+
```
RST parser error:

    sphinx.util.docutils 2017-06-12 12:18:01,428 WARNING /srv/carflow/docs/source/rejestracja_zakupu_produktu.rst:47: (ERROR/3) Malformed table.

**Comment by mb21** [comment]
The underlying issue is that pandoc doesn't support col-spans (yet), see https://github.com/jgm/pandoc/issues/1024

**Comment by m-aciek** [comment]
Thank you for pointing me that.
