### ISSUE TITLE
in-text citation with notice in brackets does not work with other references

### ISSUE THREAD

**Issue by rriemann** [jgm/pandoc#3740]
The syntax of in-text citations is:

```md
@smith04 [p. 33] says blah.
```

This works for me. Then I try:

```md
@smith04 [cf. @sec:introduction]
```

This does not produce the right latex. I found a workaround in writing

```md
@smith04 [cf. \cref{sec:introduction}]
```

, but I would be interested in a real fix.

pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1.1, skylighting 0.1.1.5

**Comment by rriemann** [comment]
I found another alternative:

```md
[-@smith04, @sec:introduction]
```

**Comment by jgm** [comment]
The syntax `@sec:introduction` is not standard pandoc.  I assume you're using pandoc-crossref or another third-party add-on?  If so, report this there.  They can escalate here if it looks like a problem with pandoc itself.  Looking at pandoc's native output for this, everything seems correct.  (Note that the bracketed part *is* a citation as far as pandoc is concerned; a third-party tool might convert it to something else, like a section number reference.)
