### ISSUE TITLE
MathJax and reveal.js

### ISSUE THREAD

**Issue by dotlambda** [jgm/pandoc#3743]
When using MathJax with reveal.js, the output looks rather ugly:
![2017-06-18-020850_1920x1080_scrot](https://user-images.githubusercontent.com/6806011/27257125-9e0aa876-53ba-11e7-9565-f384d0c641bc.png)
This is taken from [example16d.html](https://pandoc.org/demo/example16d.html) from https://pandoc.org/demos.html.

But there is a reveal.js [plugin](https://github.com/hakimel/reveal.js/#mathjax) that generates better output:
![2017-06-18-000217_1920x1080_scrot](https://user-images.githubusercontent.com/6806011/27257138-282c6af8-53bb-11e7-89da-e2aba9b0022d.png)
This was generated using the same command, i.e.
```sh
pandoc -s --mathjax -i -t revealjs SLIDES -o example16d.html
```
but a modified `default.revealjs` template that includes
```js
dependencies: [
  // ...
  { src: '$revealjs-url$/plugin/math/math.js', async: true },
  // ...
]
```
I think that the we should handle the `--mathjax` option this way when used in combination with reveal.js.

**Comment by jgm** [comment]
Thanks, I didn't know about this.
