### ISSUE TITLE
No Docx created while trying to convert rst to docx

### ISSUE THREAD

**Issue by anand0707** [jgm/pandoc#3745]
Hi All,

I am trying to convert rst to docx .

Version: 
pandoc 1.16.0.2
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.

Command:
pandoc -s -S --toc -f rst -t docx rstFile.rst -o docFile.docx

This gives no output. 

I am sure it is reading my rst as rst file as if I can see some warning if it does not find any image ( i.e when I change supposed directory of rst file)

But at the end no file created under current directory

I think this is a bug because process is failing without giving any errors

**Comment by mb21** [comment]
can you try with the newest released pandoc?

**Comment by anand0707** [comment]
Hey mb21,

It worked for 

pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: C:\Users\anand.bajpai\AppData\Roaming\pandoc

i will close this bug now and thanks a lot
