### ISSUE TITLE
Javascript has wrong encoding in Chrome (using --self-contained)

### ISSUE THREAD

**Issue by Hologos** [jgm/pandoc#3746]
Hello,

I discovered that javascript files encoded in base64 (using --self-contained) get corrupted in Chrome (checked current releases and also version 34). I couldn't reproduce it in Safari on OS X.

```
$ pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/malekjir/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Here is an [archive with test files](https://github.com/jgm/pandoc/files/1084975/corrupted.zip).

In dev console, I found that base64 encoded javascript file gets corrupted (or misinterpreted) as you can see in screenshot:

![chrome dev-console](https://user-images.githubusercontent.com/1620004/27286496-aa8f88cc-5500-11e7-8144-99c9f19eccd4.png)

Encoded CSS files contain charset: `data:text/css;charset=utf-8,...` but JavaScript files does not `data:application/x-javascript;base64,...`. I opened this _local_ file in another tab and check the encoding, chrome decodes it in ISO-8859-1:

![encoded-file default-encoding](https://user-images.githubusercontent.com/1620004/27286497-aa90d7b8-5500-11e7-81df-89ef99fdc903.png)

If I force the encoding to UTF-8, it decodes it correctly:

![encoded-file utf8](https://user-images.githubusercontent.com/1620004/27286495-aa5ab1a6-5500-11e7-9028-eac5c3117bc8.png)

Is it Chrome's fault or pandoc's? I'm not sure if pandoc should include charset definition.

Thank you for help.

**Comment by Hologos** [comment]
I found this [thread on StackOverflow.com](https://stackoverflow.com/questions/37887138/is-there-any-case-where-application-javascript-as-a-mime-type-for-javascript-w). It's a bug in Chrome. The OP found out text/javascript works in every browser but is deprecated. Is it possible to add option to generate base64 encoded javascript with text/javascript?

**Comment by jgm** [comment]
I tried this with the dev version, and I think the problem may be resolved, because the dev version no longer base64 encodes textual content.  Here's a diff between the html in your archive and the html produced by the dev version:
```
% diff -u pp.html.orig pp.html
--- pp.html.orig	2017-06-19 16:14:08.000000000 +0200
+++ pp.html	2017-06-19 16:14:17.000000000 +0200
@@ -4,14 +4,17 @@
   <meta charset="utf-8">
   <meta name="generator" content="pandoc">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
-  <title></title>
+  <title>Untitled</title>
   <style type="text/css">code{white-space: pre;}</style>
   <!--[if lt IE 9]>
     <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
   <![endif]-->
 
 <!-- HEADER - BEGINNING -->
-<script src="data:application/x-javascript;base64,LyoKVnl0dm/FmcOtIGplZGVuIGZvcm11bMOhxZkgeiBVTCBwbyBuYWRwaXN1IHDFmWVqbWVub3bDoW7DrS4KKi8K" type="text/javascript"></script>
+<script type="text/javascript">/*
+Vytvoří jeden formulář z UL po nadpisu přejmenování.
+*/
+</script>
 <!-- HEADER - END -->
 
 </head>
```

**Comment by jgm** [comment]
As far as I can see, the new behavior fixes this.  If not, you can reopen.

**Comment by Hologos** [comment]
Does it mean I have to build pandoc myself or is new release coming in near future? Thank you

**Comment by jgm** [comment]
+++ Jiří Málek [Jun 19 17 23:32 ]:
>   Does it mean I have to build pandoc myself or is new release coming in
>   near future? Thank you

I wouldn't say the near future, but we're gearing up for a
big release at some point.

If you really need this, you can try the nightlies (at your
own risk, and be aware that the command line options have
changed).  See https://github.com/pandoc-extras/pandoc-nightly/releases
