### ISSUE TITLE
YAML metadata block: German date being interpreted as one-item ordered list

### ISSUE THREAD

**Issue by Wolf-at-SO** [jgm/pandoc#3755]
I found the following issue in Pandoc 1.19.2.1 when converting Markdown to HTML:

    ---
    title: 'Titel'
    author: 'Autor'
    date: '22. Juni 2017'
    ---

Pandoc interprets the day part (`22.`) as an indicator for an ordered list (only date part shown here):

    <h3 class="date"><ol start="22" style="list-style-type: decimal">
    <li>Juni 2017</li>
    </ol></h3>

I found a workaround for this by escaping the dot like `22\.` but since Pandoc is generating questionable HTML without it (Who would place a lists into a heading?), it seems to be just a bug.

**Comment by jgm** [comment]
I don't think it's a bug.  All the mechanisms here are completely generic.  Pandoc parses the contents of the metadata fields as Markdown and passes this on to the template engine.  It doesn't know how the content is going to be used (e.g. that it will be put inside an h3 element).  Escaping the dot is the solution.

A better solution, maybe, would be to have some way to indicate the *types* of metadata fields (Blocks, Inlines, or plain String).  I'm not sure how to achieve this, though, without making documents look like computer programs.

**Comment by Wolf-at-SO** [comment]
I see, I observe the same behaviour for the other fields in the YAML metadata block. But would't it be possible/reasonable to restrict the types for these fields or to add a way for disabling Markdown interpretation for their values?

**Comment by jgm** [comment]
Pandoc title blocks parse things as sequences of inlines (so you can't get block structure like lists).

YAML metadata, by contrast, uses a completely general method.  All fields are treated the same.  And block structure is generally allowed, since you need it sometimes (e.g. for abstracts).

We could special-case title, author, and date so they just parse inlines, but that would make the syntax more irregular and less predictable, so I'm not keen to do that.

**Comment by jgm** [comment]
I wonder if we could use a heuristic like this:  if the YAML string contains no newlines, parse it as an inline sequence?  Or we could even require that it contain a blank line before parsing as blocks?

**Comment by mb21** [comment]
The following would also work now, correct?

    date: `22. Juni 2017`{=plain}

**Comment by Wolf-at-SO** [comment]
I think this difference between the processing of the Pandoc title block the YAML metadata block should be pointed out by the [docs](http://pandoc.org/MANUAL.html#variables-set-by-pandoc).

**Comment by Wolf-at-SO** [comment]
> date: `22. Juni 2017`{=plain}

No, this doesn't work.

**Comment by mb21** [comment]
@Wolf-at-SO that was just implemented in master, not released yet. Should be in the nightlies though soon.

**Comment by Wolf-at-SO** [comment]
Do you refer to this commit https://github.com/jgm/pandoc/commit/2b34337a9cf8b025914e8219498b4c0258772be0 ?
Has the value to be back-tick quoted?

**Comment by jgm** [comment]
@mb21, no, this wouldn't work to create a String metadata value:
```
date: `22. Juni 2017`{=plain}
```
That just says:  create a `RawInline (Format "plain")`, which will be emitted only when format == `plain`.

We could change the parser to parse an inline section with `{=plain}` as a `Str` element, or better as text (`Str`s and `Space`s).  That's a bit awkward, since it gives the syntax a different meaning in this special case, and also because `plain` actually is an output format.  Also, we probably wouldn't want to do the same for blocks, since then we'd have strings containing blank lines, and that could cause problems in some formats.

**Comment by jgm** [comment]
+++ Wolf-at-SO [Jun 22 17 07:12 ]:
>   But would't it be possible/reasonable to restrict the
>   types for these fields or to add a way for disabling Markdown
>   interpretation for their values?

We wouldn't want to disable Markdown interpretation; that
would make it impossible to have emphasis on titles,
footnotes on authors, etc.

As I noted before, we *could* treat `author`, `title`,
and `date` as special cases.  But I'd really rather
not do this for the reasons given before.

**Comment by jgm** [comment]
I found a great solution:  if the raw metadata field ends with a newline character, we parse as blocks. Otherwise we parse as inlines, and only fall back on blocks if we can't parse the whole thing.

So, this will be an ordered list:
```
date: |
    22. Juin 2017
```
but this will not:
```
date: 22. Juin 2017
```

**Comment by mb21** [comment]
great, maybe this should be documented in the README?

**Comment by jgm** [comment]
+++ Mauro Bieg [Jun 25 17 04:57 ]:
>   great, maybe this should be documented in the README?

It kind of is already:

> Note that YAML escaping rules must be followed. Thus, for example,
> if a title contains a colon, it must be quoted.  The pipe character
> (`|`) can be used to begin an indented block that will be interpreted
> literally, without need for escaping.  This form is necessary
> when the field contains blank lines or block-level formatting:

That suggests that block formatting will not be applied when
the pipe form isn't used, which is now true.

But if you think there's a way to improve the documentation
and makes things clearer, feel free to suggest a specific
change.
