### ISSUE TITLE
Make it possible to run a subset of tests

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#3756]
`stack test` runs all tests and the more features pandoc gets, the more time it is required to run all tests. Is it possible to somehow split tests into test suites that can be run separately?

**Comment by jgm** [comment]
The tests can already be run separately.  Just add
```
--test-arguments "-p markdown"
```
and you'll only get tests that match the pattern "markdown".
If you use the Makefile, you can do
```
make test TESTARGS='-p markdown'
```
Note that this uses the options
```
--fast --test-arguments='-j4 --hide-successes $(TESTARGS)'
```

**Comment by labdsf** [comment]
Thanks. Is it documented somewhere?

**Comment by jgm** [comment]
INSTALL has instructions for doing this with cabal.
We should add instructions for stack.

+++ Alexander Krotov [Jun 22 17 16:41 ]:
>   Thanks. Is it documented somewhere?

**Comment by mb21** [comment]
Maybe we should move the [INSTALL.md#running-tests](https://github.com/jgm/pandoc/blob/master/INSTALL.md#running-tests) section to [CONTRIBUTING.md#tests](https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md#tests)...?

**Comment by hftf** [comment]
I agree with @mb21.

Also, even with that flag, it seems like other tests are still being run; I added a `traceShow` while debugging a single test, but still saw debug output from many other tests. I can provide more details on this if needed.
