### ISSUE TITLE
org-mode level 1 headers forced uppercase

### ISSUE THREAD

**Issue by kevzettler** [jgm/pandoc#3766]
```bash
kev$ pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/kev/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

pandoc is forcing upper case on level 1 org-mode headers in plain text format

```bash
printf '* Level 1 header \n\n body content' > ./test.org; \
pandoc --columns=80 -t plain ./test.org;
```
current output is:
```
LEVEL 1 HEADER


body content
```

expected output is:
```
Level 1 header

body content
```

**Comment by jgm** [comment]
Yes, this is how the `plain` format works.  It mimics, as closely as possible, the format used in the old Project Gutenberg ebooks.  Caps and blank lines are used to make the header stand out as a header.

If you disagree with this decision, perhaps you should open a thread on pandoc-discuss or comment on this old thread: https://groups.google.com/d/msg/pandoc-discuss/spfSz1CDm6U/zmU_uUZ2IKUJ

**Comment by jgm** [comment]
PS. Only level-1 headers are printed in ALL CAPS.  So one easy solution for you would be to use `--base-header-level=2`.
