### ISSUE TITLE
RST reader: parse width, height, class, and name attributes

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#3767]
in references, headers.

See TODO notes in the source code.

**Comment by jgm** [comment]
Closing, since I no longer understand what this was supposed to be about.

**Comment by mb21** [comment]
probably about parsing RST directives like:

```
.. image:: picture.jpeg
   :height: 100px
   :width: 200 px
   :scale: 50 %
   :alt: alternate text
   :align: right
```

**Comment by jgm** [comment]
We already handle this for `.. image`.
