### ISSUE TITLE
Curly quotes enclosing a lang-tagged span means otherlangs is not set properly

### ISSUE THREAD

**Issue by bucklereed** [jgm/pandoc#3770]
```
$ echo -e '“[foo]{lang="nl"}”\n\n[bar]{lang="fr"}' | pandoc -o output.pdf
! Undefined control sequence.
l.69 ``\textdutch

pandoc: Error producing PDF
```

This also happens with HEAD.

Inspecting the standalone LaTeX, we see this:

```
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,french,main=english]{babel}
  \newcommand{\textfrench}[2][]{\foreignlanguage{french}{#2}}
  \newenvironment{french}[2][]{\begin{otherlanguage}{french}}{\end{otherlanguage}}
\else
  \usepackage{polyglossia}
  \setmainlanguage[]{english}
  \setotherlanguage[]{french}
\fi
```

So it's picking up the French fine, but missing the Dutch.

This doesn't happen if either the start or the end curly quote isn't included, so they're somehow critical.

It's not the Markdown reader specifically: the native output looks OK:

```
$ echo -e '“[foo]{lang="nl"}”\n\n[bar]{lang="fr"}' | pandoc -t native
[Para [Str "\8220",Span ("",[],[("lang","nl")]) [Str "foo"],Str "\8221"],Para [Span ("",[],[("lang","fr")]) [Str "bar"]]]
```

**Comment by bucklereed** [comment]
```
$ echo -e '"[foo]{lang="nl"}"\n\n[bar]{lang="fr"}' | pandoc -o output.pdf
! Undefined control sequence.
l.69 ``\textdutch

pandoc: Error producing PDF
```

Straight quotes tickle it too. I probably should have thought of that before I submitted the bug, not after...

**Comment by jgm** [comment]
Strange!  When I put a `traceShowId` in the code to see how `docLangs` was being set, it worked fine (i.e., Dutch came through).  When I took out the trace, it broke again. Could be a laziness related bug?

**Comment by jgm** [comment]
Never mind: I left out the quotes when I did this test.
The quotes do matter.
