### ISSUE TITLE
Markdown to markdown conversion losing backslash escape before +

### ISSUE THREAD

**Issue by DavidRGriswold** [jgm/pandoc#3773]
I am trying to get a docx output that has images for math instead of equation objects. Should be doable by converting from my original markdown right back to markdown with the --webtex command, then using the output to make the docx. This flow works great, mostly (and might be worth adding as an option for the docx output, honestly, since some people may prefer this).

However, I ran into a weird issue with markdown->markdown conversion itself where it lost a backslash escape. I made this test.md:

```
Testing

A.  \#
B.  \+
C.  \*
D.  o
E.  o or \*
```

And ran pandoc test.md -o test2.md . Test2.md looked like this:
```
Testing

A.  \#
B.  +
C.  \*
D.  o
E.  o or \*
```

Notice it lost the backslash before the + sign in part B.

This seems like maybe it wouldn't matter, but if I THEN convert to docx, the first one works as expected, but the second does not - the plus doesn't show up at all and the list is missing an element.

For my own purposes I can simply change that + to a different symbol that doesn't start a list for now, but it's still quite a funny bug!

**Comment by Wolf-at-SO** [comment]
I observe the same for `\-` which converts to `-`. Both are treated in one case as literal text and on the other as special char. I tried this input
~~~~ 
\#

\+

\*

\-
~~~~

and got this output

~~~~
\#

+

\*

-
~~~~
As to be sure in understanding what changed in the meaning, I generated JSON from both and compared the prettified versions.

![pandoc-issue-3773](https://user-images.githubusercontent.com/29630128/27736079-da36c00e-5da2-11e7-92ce-e88f995bf2f4.png)

**Comment by jgm** [comment]
This is a difficult issue.  We could guarantee that the output is semantically the same by aggressively escaping anything that might serve as a special character, but that tends to make the output fairly ugly in the majority of cases, and only helps in fairly unusual cases like this one.

One solution for you might be to put the `+`, `-`, etc. in backticks.  This makes sense if you're mentioning the symbols.

**Comment by jgm** [comment]
Having said that, I see an easy fix!

**Comment by jgm** [comment]
This is fixed for both + and -.
