### ISSUE TITLE
Hope to increase bracketed_spans function

### ISSUE THREAD

**Issue by momingxu** [jgm/pandoc#3774]
Hope `bracketed_spans`  extension can support direct modification of `p` tags. eg：

```
[Paragraph content]{.class key="value"}
```
one will get

```
<p class="class" key="value">Paragraph content</p>
```
instead of

```
<p><span class="class" key="value">Paragraph content</span></p>
```

**Comment by jgm** [comment]
There's no way to put a attributes on a Para currently.
Also, in any case, `bracketed_spans` is for modifying inlines, not block elements.
Your best bet is to put the paragraph inside a Div with a span.
