### ISSUE TITLE
Documenting Warnings and Errors for Toolchain Devs

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#3775]
I'm coding a **PP**/**pandoc**-based CMS, and right now I'm dealing with handling errors and warnings returned by either PP or pandoc. I've manged to capture both pandoc errors and warnings as strings, and must decide on how to present them within the app's output to the user (CMD/Shell) --- ie: I might need to carry out some basic reformatting (indenting, framing, abridging, etc) that befits the current flow of app-feedback.

I'm having problems finding in pandoc's documentation references to errors and warnings. Right now I need to rise different types of errors and warnings to test handling them (ie: I need to have some kind of expectations on their text lenght variations, etc). Especially so for warnings, which won't interrupt the flow of files convertions, but the user must be noticed about them. Depending on the maximum length of the longest possible warning, I'll need to decide if warnings should be showed in-place or after all operations are over.

It would be nice to have in pandoc's repo a (markdown) file listing the possible errors and warnings that pandoc might raise (at least the main ones), and provide examples of how these could be intentionally caused for testing purposes. Also, it would be useful to provide the main categories these fall into — in many cases some apps might be more interested in focusing on errors/warning raising from template or source documents than those relating to command line arguments or the user's environment.

Possibly, this kind of information (even if in general terms, and not necessarily covering all possible cases of every pandoc release) could provide helpful for developers of apps that rely on pandoc for some operations.

I remember that during my various tests I came across some pandoc warnings, but right now I can't recall how I stumbled upon them and can't produce any.

**Comment by jgm** [comment]
What version of pandoc are you working with?  In the development version we have vastly expanded warnings and logging, and there are modules (Text.Pandoc.Logging, Text.Pandoc.Error) with the possible warning, info, and error messages.

**Comment by jgm** [comment]
PS. Forgot to mention the new --log=FILE option in the dev
version of pandoc.  This gives you a JSON version of the
warnings.

**Comment by tajmone** [comment]
I'm using pandoc 1.19.2.1.

Yes, I've been following the Issue thread on warnings, and it looks really promising. But currently I'm sticking to the release version because that's what final users of my project will be relying on.

**Comment by tajmone** [comment]
Anyone can help with this?

So far I've implemented handling pandoc 1.19.2.1 errors (ie: when pandoc exit code is `>0`) and an error message on `STDERR`.

But I still need to understand what to expect warnings-wise and how to handle them — ie: I'm assuming that warnings are to be detected when pandoc emits some text on `STDERR` but has exit code `0`.

Basically, I have to decide if my app should carry on converting files or should abort; but I don't have enough info on pandoc possible warnings to decide how they should be handled in the context of my application. 

On any exit code `>0` my app will show the text received on `STDERR` by pandoc and abort all operations.

As for `STDERR` messages with a `0` exit code, should I assume that it's a non blocking warning (ie: output was produced nonetheless) and should carry on converting the rest of the files in the app's list, or should it abort also?

Can anyone please give me an example of how to rise a warning with pandoc, via the command line arguments or from the markdown source file? I remember that during my tests I had (accidentally) risen a pandoc warning ... but haven't managed to replicate it since!

I've looked at the source file [Error.hs](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Error.hs) but couldn't work out how warning are handled.

**Comment by jgm** [comment]
I don't actually remember how warnings worked in 1.19, but
I think you could raise one if you had a duplicate reference
link.

[foo]

[foo]: bar

[foo]: baz

You can search the 1.19.2.1 source code for "warn" to get
some idea of what warnings there are.  This isn't something
we'll put any effort into now, since the focus is on the
upcoming 2.0.

+++ Tristano Ajmone [Aug 24 17 14:18 ]:

**Comment by tajmone** [comment]
Thanks a lot! The duplicate ref link worked and helped me test my app's code.

I've finally opted to handle the presence of any messages on pandoc's `STDERR` as if it was an error (even when exit code is `0`) because I assume that something undesirable creeped in the markdown source and should be fixed before publishing — ie: implementing a strict policy on MD source wellformedness.

I might later on add an option to overlook pandoc warnings, but I think that the default behaviour should be to abort on warnings.

Of course this might change with the next release of pandoc (**v2.0**?), which will implement a finer control over warnings, as you mentioned.

**Comment by jgm** [comment]
pandoc 2.0 will have a command-line option to treat warnings
as errors; you'll also have finer grained control over
verbosity levels (warnings vs info messages), and  the
opportunity to get the warnings in machine-readable JSON
form.

+++ Tristano Ajmone [Aug 25 17 14:29 ]:

**Comment by mb21** [comment]
All logging is now bundled in `Logging.hs`, where you have a list of all warnings/errors:

https://github.com/jgm/pandoc/blob/8e8d7802eef373b458653fc87857672c2c376b05/src/Text/Pandoc/Logging.hs#L70
