### ISSUE TITLE
misleading manual on the website pandoc.org

### ISSUE THREAD

**Issue by Wolf-at-SO** [jgm/pandoc#3777]
(Sorry if this is not the right place for issues like that, but I found nothing better so far.)

Today I tried to set PDF paper size to A4, and according to **the manual catching all Google searches**, I used `papersize=A4` which of course failed. This typo was [fixed three months ago](https://github.com/jgm/pandoc/commit/07778ade395a5fbb4543dbdd3b30fccfe9ed45b2), but not in the web version. 

I understand that the web pages are meant to reflect the last stable version, but maybe bugs fixed solely in the manual itself should have the chance to be "previewed" online.

**Comment by jgm** [comment]
I fixed the online version.

**Comment by Wolf-at-SO** [comment]
Thanks for updating. 
BTW: I just wanted to remember you that the demo examples still contain the [unfixed `MANUAL.txt`](http://pandoc.org/demo/MANUAL.txt)

**Comment by callodacity** [comment]
Just informing that the webpage at the moment contain `"A4"`, which if I understand correctly is a typo.

See http://pandoc.org/MANUAL.html#variables-for-latex

<img width="437" alt="screen shot 2017-09-20 at 10 13 03 am" src="https://user-images.githubusercontent.com/1011648/30621077-716b9358-9dec-11e7-8038-aa64151ee6f9.png">

**Comment by jgm** [comment]
This has already been fixed in MANUAL.txt;
MANUAL.html on the website will be updated when there
is a new pandoc release.  So, this can be closed.

+++ callodacity [Sep 20 17 00:14 ]:

**Comment by callodacity** [comment]
No worries 👍 this issue is already closed, I was just making sure that everything was correctly reflected on the website 😄
