### ISSUE TITLE
New release with recent changes

### ISSUE THREAD

**Issue by chisma** [jgm/pandoc#3781]
Thanks for pandoc. I was wondering if you are planning on a new release with recent changes? In particular, I am relying on the fixes for https://github.com/jgm/pandoc/issues/2116, and it would be nice to use pandoc from a released version. Am I missing something?

**Comment by mb21** [comment]
please ask questions on pandoc-discuss...

until the next release, you can try the nightly builds...

**Comment by chisma** [comment]
Thanks, I agree I should have looked at pandoc-discuss.
