### ISSUE TITLE
Confusing column widths in multiline tables

### ISSUE THREAD

**Issue by Wolf-at-SO** [jgm/pandoc#3783]
I tried to use multi-line tables as to describe the meaning of some GUI symbols in a users manual. What I observed is *much* unused space around the icons that I was not able to minimize. In single-line tables, there is no such space around the icons. I built a test case with single characters to show the problem here.

This is the markdown I use as input

~~~~
---------------------------------
 .    long description
----  -------------------------------------------------------------------
 A    the first letter of the alphabet. the ASCII code is 65 decimal, 
      or 0x41 in hexadecimal notation

 B    the second letter of the alphabet. the ASCII code is 66 decimal, 
      or 0x42 in hexadecimal notation
---------------------------------
~~~~

It is converted into this HTML via `pandoc test.md -o test-out.html`

~~~~
<table>
<colgroup>
<col width="8%" />
<col width="91%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">.</th>
<th align="left">long description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">A</td>
<td align="left">the first letter of the alphabet. the ASCII code is 65 decimal, or 0x41 in hexadecimal notation</td>
</tr>
<tr class="even">
<td align="center">B</td>
<td align="left">the second letter of the alphabet. the ASCII code is 66 decimal, or 0x42 in hexadecimal notation</td>
</tr>
</tbody>
</table>
~~~~

And - even more confusing - into this Markdown via `pandoc test.md -o test-out.md`

~~~~
        .       long description
  ------------- -------------------------------------------------------------------------------------------------------------------------------------------------
        A       the first letter of the alphabet. the ASCII code is 65 decimal, or 0x41 in hexadecimal notation
        B       the second letter of the alphabet. the ASCII code is 66 decimal, or 0x42 in hexadecimal notation

~~~~

The conversion into JSON (reformatted) contains this fragment that I read as the encoded column alignments and relative widths:

~~~~
      "t": "Table",
      "c": [
        [],
        [
          {
            "t": "AlignCenter"
          },
          {
            "t": "AlignLeft"
          }
        ],
        [
          0.09722222222222222,
          0.875
        ],
~~~~

How are the column widths calculated? 
Is there a secret minimum width for a column?

I tried to minimize the width of the left column by increasing the line (`----`) unter *long description* but more than some 100 chars seemed me not acceptable for "plain text" input.

**Comment by blindmelon** [comment]
I can't answer the actual questions or directly help with the issue, but you might find https://github.com/ickc/pantable useful until you find the solution you are really after.

**Comment by Wolf-at-SO** [comment]
@blindmelon Thanks, I already found this via Google/StackOverflow. I found that interesting in another aspect of tables: ease of *diff*ing. But in my very case, rewording the user manual will help, because there are only few cases where I currently use the multi-line option.

I think **multi-line** is important for some input formats (Markdown) and some output formats (LaTeX); for  **HTML** it seems a bit **problematic** as it is implemented right now.

**Comment by jgm** [comment]
In the dev version, at least, `pandoc -t markdown` gives a
table of the same width as the original.

As the manual says, column widths are calculated based on
the widths of the header lines (relative to the total
colwidth, which is configurable by a command line option).

So what you need to do is to reduce the width of the first
column, or increase the width of the second.
