### ISSUE TITLE
Make backlink char in HTML footnotes variable

### ISSUE THREAD

**Issue by Wolf-at-SO** [jgm/pandoc#3785]
In HTML output, Pandoc uses the symbol ↩  (8617 dec, 21A9 hex, [LEFTWARDS ARROW WITH HOOK](https://www.w3schools.com/charsets/ref_utf_arrows.asp)) for backlinks at the end of footnote text.

Since the generated HTML uses UTF-8 encoding this is absolutely fine. *But* If you wish to convert it to another encoding, this may be a problem. I'm trying to generate a CHM help file from Pandoc's output, so I have to convert into Windows-1252 which fails at this char.

I'd like to suggest to add a variable to specify the symbol that is getting used.

**Comment by jgm** [comment]
Essentially this is the same as #3149 (which concerns EPUB, but that just uses the HTML writer).
So one of them should be closed as a duplicate.

**Comment by jgm** [comment]
Incidentally, this can't be handled at the template level (with a variable).  We'd need to use a command-line option or metadata.

**Comment by jgm** [comment]
Closing as a dup of #3149.  By the way, in your case an easy fix would be to pipe pandoc's output through tr, sed, or perl to change the character to another one.

**Comment by Wolf-at-SO** [comment]
For those interested, I used Perl with `s/\x{21a9}/^/` to replace ↩ by a simple caret.
I actually had to transform the HTML from Unicode into the windows-1252 encoding for making a [CHM file](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help).

    use strict;
    use warnings;

    open(my $INFILE,  '<:encoding(UTF-8)',  $ARGV[0]) or die $!;
    open(my $OUTFILE, '>:encoding(cp1252)', $ARGV[1]) or die $!;

    while (<$INFILE>) {
        s/<meta charset="utf-8">/<meta charset="windows-1252">/;
        s/\x{21a9}/^/;
        print $OUTFILE $_;
    }
