### ISSUE TITLE
Removed options in HEAD will break scripts without warning

### ISSUE THREAD

**Issue by bucklereed** [jgm/pandoc#3786]
HEAD removes a bunch of options that have probably been used in a lot of scripts, most significantly `--smart` and `--normalize`. Some of them have been spitting warnings in the last released version and probably for a while before, so they are fair game to remove, but not all (and, specifically, not the two I am most worried about). pandoc can interpret them on a DWIM basis and spit out a deprecation warning, which would be good practice before their eventual removal.

**Comment by mb21** [comment]
the next release is going to be pandoc 2.0 and it's probably going to break lots of stuff...

**Comment by bucklereed** [comment]
Yes. But some of that is unavoidable, or difficult to avoid without going insane (e.g., AST changes and the like).

**Comment by bucklereed** [comment]
Also---I don't know the whole list of things that are going to break, but anything touching the command line API is liable to affect a lot more users than changing the AST, and doubly so for likely-to-be-common options like `--smart- and `--normalize`. It's a small change for the user to make, but it's potentially a *lot* of users, so I definitely think that the user pain here could be significant.

**Comment by jgm** [comment]
The dev version already gives you a warning for `--smart`:
```
% pandoc --smart
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
```
We could use a similar warning for `--normalize`.

As for DWIM:  `--normalize` is simply redundant, normalization is essentially automatic now.  So I suppose in that case we could just issue a warning without failing.  On the other hand, given that this is a major breaking release, I see some advantage in forcing people to fix their scripts now, when they'll be expecting to do so.

**Comment by bucklereed** [comment]
Well, 2.0's been released, so this is all moot now.

**Comment by jgm** [comment]
There are warnings for all the changed/removed options, and
they tell you how to fix your command line.

+++ bucklereed [Nov 02 17 12:59 ]:

**Comment by jgm** [comment]
```
% pandoc --normalize
--normalize has been removed.  Normalization is now automatic.
Try pandoc --help for more information.
```
