### ISSUE TITLE
Support math via MathML in OpenDocument/ODT

### ISSUE THREAD

**Issue by krontzo** [jgm/pandoc#3787]
Pandoc 1.19.2.1 and previous version.

Input: [http://pandoc.org/demo/math.text](http://pandoc.org/demo/math.text).
Expected output: [http://pandoc.org/demo/mathMathJax.html](http://pandoc.org/demo/mathMathJax.html)

Current output explained:
The last two math formulas of the pandoc demo are wrong in the ODT output, as seen in LibreOffice (every version I could test under Windows, macOs and Ubuntu) and Google Docs.

```bash
pandoc math.text -o math.odt
``` 

Converting to Word docx gives the correct formulas:

```bash
pandoc math.text -o math.docx
``` 

Docx verified in:
- Word (2016, 2016 mac, 2011, 2013)
- Google Docs
- Pages 6.2

The (identified) La_TeX_ math equations:

```latex
$\int_{0}^{1} x dx = \left[ \frac{1}{2}x^2 \right]_{0}^{1} = \frac{1}{2}$

$e^x = \sum_{n=0}^\infty \frac{x^n}{n!} = \lim_{n\rightarrow\infty} (1+x/n)^n$
```

and the current equivalent in ODT output:

```latex
$\int x dx = \left[ \frac{1}{2}x^2 \right]_{0}^{1} = \frac{1}{2}$

$e^x =  \frac{\sum x^n}{n!} = l_{n\rightarrow\infty} (1+x/n)^n$
```

**Comment by jgm** [comment]
We don't yet support math (except for simple cases) in OpenDocument/ODT.
But it looks as if maybe OpenDocument can contain embedded MathML, and if so it would be an easy change to make pandoc support this.
http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1416212_253892949

> The `<math:math>` element serves as a container for content defined by the MathML 2.0 standard. See [MathML].
> The `<math:math>` element is usable within the following elements: `<db:component>` 12.25.5 and `<draw:object>` 10.4.6.2.

Here's an example of the XML inserted by LibreOffice when I added a formula:
```xml
<draw:frame draw:style-name="fr1" draw:name="Object1" text:anchor-type="as-char" svg:width="0.4138in" svg:height="0.1839in" draw:z-index="0">
    <draw:object>
      <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
       <semantics>
        <mrow>
         <mi>x</mi>
         <mo stretchy="false">⊗</mo>
         <mi>y</mi>
        </mrow>
        <annotation encoding="StarMath 5.0">x otimes y </annotation>
       </semantics>
      </math>
   </draw:object>
 </draw:frame> 
```
It also put the attribute
```
xmlns:math="http://www.w3.org/1998/Math/MathML" 
```
in the `office:document` element.

**Comment by krontzo** [comment]
@jgm That's great!

**Comment by jgm** [comment]
The thing I don't know how to do is to give reasonable values for the svg width and height of the draw:frame element.  These seem to be required.

**Comment by mb21** [comment]
what about `width="100%"`? not sure about the height though...

**Comment by jgm** [comment]
I tried setting width and height to 100%, and I got a formula that took up the entire page. Not really what we want!

**Comment by jgm** [comment]
Sorry:  what I said above was pretty much all wrong.

We DO support mathml in ODT output (not directly in OpenDocument, but via a transformation that happens in the ODT writer).  And resizing is handled well since we store the mathml formulas separately.

I think @krontzo's issue was not that math wasn't supported, but that pandoc was making some mistakes in converting from tex to mathml.

I can confirm that the dev version does not make these mistakes, due to intervening fixes in texmath; everything looks right in the dev version's output.  So this issue can be closed, I believe.
