### ISSUE TITLE
Markdown readers behave badly on pathological input

### ISSUE THREAD

**Issue by DemiMarie** [jgm/pandoc#3799]
Pandoc’s markdown reader behaves badly on pathological input.

**Comment by mb21** [comment]
please see http://pandoc.org/CONTRIBUTING.html#found-a-bug

> Make sure you can reproduce the bug with the latest released version of pandoc (or, even better, the development version).
> 
> Your report should give detailed, reproducible instructions, including
> 
> the pandoc version (check using pandoc -v)
> the exact command line used
> the exact input used
> the output received
> the output you expected instead

**Comment by jgm** [comment]
Yes, we know this. See #1735 for one example.  Further examples are always welcome, but achieving performance that scales linearly with the input size is probably not possible without a complete ground-up rewrite of the parser.  We recommend that if you use pandoc to process user input in a web app, you put it behind some kind of timeout, or use the CommonMark reader.

**Comment by jgm** [comment]
Closing this because it's too generic; specific reports like #1735 are more helpful.
