### ISSUE TITLE
square brackets break raw LaTeX

### ISSUE THREAD

**Issue by darthoctopus** [jgm/pandoc#3804]
With the following line of code:

```\titleformat{\chapter}[display]{\normalfont\large\bfseries}{第\thechapter{}章}{20pt}{\Huge}```

I get the following output:

```\titleformat{\chapter}{[}display{]}\{\normalfont\large\bfseries\}\{第\thechapter{}章\}\{20pt\}\{\Huge\}```

Some experimentation indicates that this behaviour is triggered when the first square brackets are encountered after the first open brace. I'm using pandoc 1.19.2.1 from the AUR.

**Comment by jgm** [comment]
This needs to be handled with a special rule for `\titleformat` in the LaTeX reader (which is used by the Markdown reader).  We can't just assume, in general, that square brackets in this position are part of an optional argument.  They aren't, for example, in this case:

```latex
\emph{ok}[bracketed]{ok}
```
Here the brackets are just brackets.

**Comment by darthoctopus** [comment]
would it be possible to disable this kind of escaping behaviour for header-includes with the latex reader? I presume this is where this sort of syntax would be more likely to be valid (as the latter case that you point out would happen before \begin{document} and give a compilation error in any case, if it weren't already valid latex).
