### ISSUE TITLE
Refactor Lua integration

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#3805]
The current lua integration is based on hslua 0.4. Upcoming hslua versions will provide better data types and more helpers, fix some performance issues, and start to tackle the issue of unsafe API functions that can cause unrecoverable errors, crashing the application.  The code should be refactored to use the new version (once it's released).  Preliminary tests show a ~30% performance improvement while simultaneously providing better safety guarantees.

**Comment by tarleb** [comment]
Just a status update: The current [hslua-0.6](https://github.com/tarleb/pandoc/tree/hslua-0.6) branch includes all changes necessary to work with the next hslua release. Running a filter to upper-case all strings now takes about one third of the time when compared to the old version.  All lua errors are translated into Haskell exceptions.  The code needs a little more polishing (like better error messages) before I'd be comfortable to merge it.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Jul 23 17 20:56 ]:
>   Just a status update: The current [1]hslua-0.6 branch includes all
>   changes necessary to work with the next hslua release. Running a filter
>   to upper-case all strings now takes about one third of the time when
>   compared to the old version. All lua errors are translated into Haskell
>   exceptions. The code needs a little more polishing (like better error
>   messages) before I'd be comfortable to merge it.

Excellent news!

**Comment by jgm** [comment]
@tarleb what's the timeline on this?  Should this be added to the pandoc-2.0 milestone?

**Comment by tarleb** [comment]
I should be done within the next 3 days. I found some hslua issues which needed fixing, thus requiring another hslua release. I wanted to get this out first so I don't have to fix the filter code twice.  The fixes are done now and I'm going to release hslua 0.7.0 later today.  This also allows us to get rid of the `SharedInstances` module, which is now fully handled by hslua.

**Comment by tarleb** [comment]
Performance of pushing and receiving a document to Lua is now on par with using `cat` as a JSON filter.

**Comment by tarleb** [comment]
It seems that the change broke string comparison in Lua on Windows. I have no idea why.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Aug 13 17 10:58 ]:
>   It seems that the change broke string comparison in Lua on Windows. I
>   have no idea why.

Can you give a small test case or example?  (I saw the
appveyor failure, but I wasn't sure what string comparison
was responsible for this.)

**Comment by tarleb** [comment]
I'm on it, currently trying to build a failing test-case for the hslua test-suite. String comparison as the culpit was a quick guess, but that guess was most likely wrong. I don't really know.

**Comment by tarleb** [comment]
Ok, got a minimal test case now.  It's somehow related to the conversion of haskell functions to lua functions.  Interestingly, it only happens with 32bit builds but not 64bit builds, so I was [able to build pandoc](https://ci.appveyor.com/project/tarleb/pandoc) by using a 64bit stack.

**Comment by jgm** [comment]
So is it a bug in hslua, then?  Can 32-bit support on
Windows be fixed?  I'd prefer to continue to make 32-bit
binaries available.

+++ Albert Krewinkel [Aug 14 17 12:03 ]:

**Comment by tarleb** [comment]
> So is it a bug in hslua, then?

Possibly. I witnessed the bug disappear when compiling against lua 5.1 (as opposed to lua 5.3 which is normally shipped with hslua).

> Can 32-bit support on Windows be fixed?

I'm reviewing the hslua code and doing some testing, but so far I couldn't find anything that would explain this issue.
Worst-case would be that lua 5.1 must be compiled into pandoc on 32-bit Windows. I'm not sure how difficult that would be.

**Comment by tarleb** [comment]
I might just give up, there seems to be very little chance that I can identify the root of this. The issue comes and goes when changing small things like adding a *print* in the problematic test (poor man's remote debugging). Could be a race condition or something similar; I have close to no experience with that, even less so on Windows.

**Comment by jgm** [comment]
Have you tried fiddling with the config options in src/luaconfig.h when compiling for Windows 32-bit?
It may be that specific settings of something are needed there?
There's `LUA_32BITS` but I think that just affects numbers.  (Still, are you sure that the root issue couldn't be a numerical comparison?)
`LUA_USE_C89` might make a difference on Windows.
`LUA_USE_WINDOWS` should presumably be set.

**Comment by jgm** [comment]
Going to reopen so we don't lose track of this. If at the end of the day you can't fix this, then we can switch to 64-bit builds (though this may be a problem for some users).  But it would be nice to get to the bottom of it; who knows whether the underlying issue might manifest itself in other ways?

**Comment by jgm** [comment]
> Worst-case would be that lua 5.1 must be compiled into pandoc on 32-bit Windows. I'm not sure how difficult that would be.

Would that just require setting the `lua501` flag for Windows builds?

**Comment by tarleb** [comment]
Thank you, John! Setting either `LUA_USE_C89` or `LUA_32BITS` seems to fix it. I'm updating hslua to support an additional `lua_32bits` cabal flag. Some additional hslua changes are required to make this work.  Type aliases where used where newtypes would be a much better solution.

**Comment by jgm** [comment]
That's great to hear!

**Comment by tarleb** [comment]
HsLua has been updated and pandoc on i386 Windows now builds Lua with the LUA_32BITS option set. This test failing test lua test is fixed by this change, I hope it's safe to close this issue now.
