### ISSUE TITLE
Templates: Add Comments Keyword

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#3806]
While working on HTML pandoc templates, I realized it would be nice to have a `comment` keyword that would allow to insert developers' comments, notes and instructions that will be ingnored in the final HTML doc — unlike HTML comments, which are preserved.

I'm not sure which syntax such a keyword could take, but it should allow single-line and multi-line comments. Possibly, something like this:

```
$comment(I'm a single line comment)$

$comment(
  I'm a mult-line comment.
  I can span across multiple lines, and my content will be ignored
  in the final document.
)$

```

This feature won't affect backward compatibility and it would come very handy in templates development, allowing to annotate TODOs lists, instructions, and so on, without polluting the final document as HTML comments do. Ideally, it would be nice to see it implemented for all the template formats, but even having it just in HTML templates would be cool.

**Comment by jgm** [comment]
This would actually be a change in jgm/doctemplates

**Comment by jgm** [comment]
The problem with the suggested syntax is knowing where the comment ends.  One could scan forward for `)$`, but this would cause problems if you use `comment` to comment out a section of template.

A line comment syntax might work better, maybe something like

```
This is the $title$.
$-- This line is commented out.
```

**Comment by tajmone** [comment]
> this would cause problems if you use comment to comment out a section of template.

True, I didn't think about it. Commenting out template parts would actually be very useful.

Another solution could be to use 3 or more tildas as delimiters, instead of braches, as with markdown code blocks:

```
$comment
~~~~~~~~~~~~
    ... whatever ...
~~~~~~~~~~~~
```

In this case the arbitrarily-variable number of matching tildas in the closing delimiter would prevent erroneous parsing of the comment block as template.

The tildas could be an alternative syntax for the braces, and cover multiline comments; while `$--` could be the single-line comment syntax.

**Comment by jgm** [comment]
Another option would be
```
$comment$
the comments go here...
you can have anything here, including $ and things that
would normally be interpreted in a template, like $if(foo)$,
but the whole comment ends with...
$endcomment$
```
This is consistent with current `$for$...$endfor$`.

**Comment by tajmone** [comment]
Very nice solution, I like it. Having the `$comment$`/`$endcomment$` along the `$--` for single line comments would cover all uses.

But I think that the  `$comment$`/`$endcomment$` could fail when commenting out a template section which include an `$endcomment$` statement — while the tildas delimiter can include any template statements because it relies on the exact number of tildas in the opening and closing delimiters, so it can also skip tilda comments inside its block as long the number of tildas differ.

I thought of the tildas because I saw their usage in [PP's macros](https://github.com/CDSoft/pp#macros), where the last parameter can use tildas instead of round braces:

> The last argument can be enclosed between lines of tildas or backquotes (of the same length) instead of parenthesis, brackets or braces and. This is useful for literate programming, diagrams or scripts (see examples). Code block arguments are not stripped: spaces and blank lines are preserved.

But I also like a lot  the `$comment$`/`$endcomment$`  syntax.

**Comment by jgm** [comment]
It seems that line comments would be the most flexible option; they would allow commenting out sections (which would also be visually distinguished), and they wouldn't run into problems with comments inside comments, like the comment/endcomment idea.

I like the `$--` syntax (reminiscent of Haskell and lua comments); other options would be `$#` or `$//`.

**Comment by tajmone** [comment]
Sounds good. All three solutions (`$--`, `$#` and `$//`) look equally familiar and intuitive.

Visually speaking, my impressions are:

- `$#` requires less typing but it's more visually cluttered and might interfere with reading multiple lines of texts:
    ```
    $# I'm a comment running on multiple lines,
    $# try to see if the comment delimiter
    $# makes it easier or harder to follow the
    $# text on the next line.
    ```
- `$--` is the one that would make comments stick out most amongst the three (the double hyphen, especially if at the beginning of a line, is visually capturing, and also reminds of how bullet lists are represented in text files) and wouldn't interrupt the flow of reading across multiple lines (IMO):
    ```
    $-- I'm a comment running on multiple lines,
    $-- try to see if the comment delimiter
    $-- makes it easier or harder to follow the
    $-- text on the next line.
    ```
   ... so much so that you don't actually need a space after it at all:
    ```
    $--I'm a comment running on multiple lines,
    $--try to see if the comment delimiter
    $--makes it easier or harder to follow the
    $--text on the next line.
    ```
