### ISSUE TITLE
Optional source file name and line numbers in AST

### ISSUE THREAD

**Issue by gpoore** [jgm/pandoc#3809]
I'm working on a Python filter that will execute the code in designated code blocks and replace it with the output. The JSON representation of the AST and `pandocfilters` give me everything I need to do this when the code is valid. In the case of invalid code, it would be nice to have optional source file name and line numbers in the AST to be able to provide a more useful traceback. For example, an error occurred on line 5 of the code, which came from a code block on line 25 of `file.md`. Having this information at the block level would probably be sufficient for most cases.

Currently, I'm looking at parsing the `--trace` output to do this, possibly supplemented by the occasional regular expression.

**Comment by oli-obk** [comment]
I have a similar issue. But instead of the block level, I'd need it for every `inline`, since I'm looking at the text for abbreviations from a list and notify the user if they have not marked their abbreviation appropriately.

**Comment by mb21** [comment]
@oli-obk thanks for finding the duplicate. Closing this in favour of #4565
