### ISSUE TITLE
Generalized syntax for filtered elements in Markdown?

### ISSUE THREAD

**Issue by gpoore** [jgm/pandoc#3810]
It might be nice to have a syntax for elements that will be processed by filters, especially code blocks and inline code. This would provide an obvious indication that the document is intended for use with a filter, rather than just using custom classes.

I'm working on a filter to make some code blocks executable. Currently, I can use something like this:
``````
```{.python evaluate=true}
<code>
```
``````
By analogy with #3537, a filter syntax might allow something like this:
``````
```{!python}
<code>
```
``````

Perhaps filter elements could be given a default filter class in the event that the output format is not native or JSON. In that case, it might be good to discard all key-value style attributes or otherwise handle them specially, since they are probably meant for the filter rather than for an output format directly.

**Comment by jgm** [comment]
This is the sort of suggestion that would be better raised on pandoc-discuss than here.
