### ISSUE TITLE
Bug: escape string

### ISSUE THREAD

**Issue by J88G** [jgm/pandoc#3815]
I'm using pandoc to convert markdown to html.

if I send:

`<script>alert('hi')</script>`  the script tags are not enconded so a alert is display on the page

in case of 
```
'''
<script>alert('hi')</script>
'''
```
The script tags are enconded, as it shoud, so the alert is not display

There is some way that <script> tags be enconded, even if they are outside of a code block ?

**Comment by mb21** [comment]
In most markdown dialects you can embed unsafe HTML. So if you don't trust your input, you shouldn't trust pandoc's output. In that case, you should apply some HTML postprocessing anyway.

See e.g. https://talk.commonmark.org/t/make-commonmark-safe-by-default/1265 and feel free to ask questions on pandoc-discuss.

**Comment by tarleb** [comment]
You can also disable the `raw_html` extension (The extension is required by the original markdown spec and on by default):

    $ echo '<script>alert("hi")</script>'  | pandoc -f markdown-raw_html -t html
    <p>&lt;script&gt;alert(“hello”);&lt;/script&gt;</p>

**Comment by mb21** [comment]
good point @tarleb, however you'll still have to sanitize, e.g. the following (from the other thread):

    [do something evil](javascript:evil())

**Comment by tarleb** [comment]
Oh yeah, hadn't thought of that. Evil indeed ;D

**Comment by tarleb** [comment]
Slightly OT: Configuring the server to send a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) would prevent all of this. Won't work with older browsers though, @mb21's point still stands.

**Comment by J88G** [comment]
thanks @tarleb  it works !
