### ISSUE TITLE
align, equation, eqnarray disappears converting from md to html

### ISSUE THREAD

**Issue by dataopt** [jgm/pandoc#3816]
Using the command `pandoc --mathjax -t html test.md -o test.html ` (macOS Sierra, pandoc nightly version 2.0 compiled with pandoc-types 1.17.0.5, texmath 0.9.4.1, skylighting 0.3.3), the following Markdown input

```
# This is my book

This is an equation:
\begin{equation}
y+2 = 3
\end{equation}

This is a system of equations:
\begin{align*}
x^2+y^2 & = 2 \\
\sin(y) & = 0.5
\end{align*}

This is Euler's formula:
\begin{eqnarray*}
e^{i\pi} + 1 & = & 0.
\end{eqnarray*}
```

gets converted to the following html:

```
<h1 id="this-is-my-book">This is my book</h1>
<p>This is an equation: </p>
<p>This is a system of equations: </p>
<p>This is Euler’s formula: </p>
```

In other words, all the equations are missing in the html output.  However, latex output is fine.

**Comment by jgm** [comment]
This is because these environments are now parsed as inline rather than block.
So the writer just needs a small tweak, to render these raw inline environments when mathjax is used.
