### ISSUE TITLE
AST: Support for multiple headers in Table

### ISSUE THREAD

**Issue by reenberg** [jgm/pandoc#3818]
In html, [a \<thead\> can have multiple <tr> elements](https://www.w3.org/TR/html5/tabular-data.html#the-thead-element). Currently this can't be expressed in the AST.  

I have a filter that generates a Table where i would have liked the HTML output to contain two rows of table headers.  However this is currently not possible to express in the AST, leaving some annoying css to handle it afterwards.

It seems that #1024 is the generic bin for Table related AST issues, and most issues get closed in reference to this.  So feel free to close this as well, but just have it in mind when changing it.

It would be nice to have \<tfoot\> support as well.  I know that there is currently no Markdown syntax to generate it, but at least it would give filters a chance to generate them.

**Comment by mb21** [comment]
you're in luck! the representation of tables in the AST is currently under discussion, feel free to join in: https://github.com/jgm/pandoc/issues/1024

**Comment by reenberg** [comment]
It is a difficult design decision (like #684) that needs to be done correctly.  I wouldn't claim to know the internals of Pandoc and the Markup language good enough to add value to the discussion. 
Not to mention that it would require knowledge about what Pandoc would be willing to add as extensions to the language along the road.

**Comment by ickc** [comment]
> It would be nice to have <tfoot> support as well. I know that there is currently no Markdown syntax to generate it, but at least it would give filters a chance to generate them.

I think kramdown's markdown supported this. See [Syntax | kramdown](https://kramdown.gettalong.org/syntax.html#tables).
