### ISSUE TITLE
latex output: multiple `classoption`s overwrite instead of append

### ISSUE THREAD

**Issue by azrdev** [jgm/pandoc#3820]
The readme says about `classoption`: `option for document class, e.g.  oneside; may be repeated for multiple options`. However, this markdown:
~~~
---
classoption: 11pt
classoption: longpage
---

~~~
is rendered (using `pandoc -s -t latex`) to
~~~
\documentclass[longpage]{article}
...
~~~
instead of the expected
~~~
\documentclass[11pt,longpage]{article}
...
~~~

This is pandoc 1.19.2.1 on archlinux (packet `pandoc-lite`).

**Comment by jgm** [comment]
That documentation concerns variables.  If you specify the
variable on the command line using `-Vclassoption=11pt
-Vclassoption=longpage`, then you repeat.  But if the
variables are being filled from metadata fields, you need
to use a YAML list instead:

```
classoption:
- 11pt
- longpage
```
