### ISSUE TITLE
generates invalid IDs in HTML from markdown when headline contains .

### ISSUE THREAD

**Issue by rubenarslan** [jgm/pandoc#3821]
tested in version: 1.13.1, 1.17.2
`pandoc test.md` on

```markdown
## X.X
invalid ID
```

yields an invalid ID
```html
<h2 id="x.x">X.X</h2>
<p>invalid ID</p>
```

this is annoying when combined with automatically turning sections into tabs as practiced in rmarkdown.

**Comment by mb21** [comment]
Tested with pandoc 1.19.2.1 and the output is still the same.

However, this is valid HTML5 as can be seen with validator.w3.org

**Comment by rubenarslan** [comment]
Ugh, sorry, must have looked this up in the wrong place at some point or misremembered. Nevermind then.
