### ISSUE TITLE
broken pipe while installing binary on Debian 9

### ISSUE THREAD

**Issue by getreu** [jgm/pandoc#3822]
with debian 9 (stretch) I get the following

```
# dpkg -i pandoc-1.19.2.1-1-amd64.deb 
(Reading database ... 250118 files and directories currently installed.)
Preparing to unpack pandoc-1.19.2.1-1-amd64.deb ...
Unpacking pandoc (1.19.2.1-1) over (1.17.2~dfsg-3) ...
dpkg: error processing archive pandoc-1.19.2.1-1-amd64.deb (--install):
 trying to overwrite '/usr/bin/pandoc-citeproc', which is also in package pandoc-citeproc 0.10.2.2-1+b2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 pandoc-1.19.2.1-1-amd64.deb
```

**Comment by mb21** [comment]
Maybe try removing the old `pandoc-cinteproc` first...? or try `--force-overwrite` ? see e.g. https://askubuntu.com/questions/441047/

**Comment by jgm** [comment]
If you've installed `pandoc-citeproc` or `pandoc` from debian's repositories, you should remove these first, before installing our deb.  It includes both pandoc and pandoc-citeproc.

**Comment by getreu** [comment]
Thank you for your quick answer. @Jgm your solution works for me.
May I suggest to modify the dependency definition in your package to replace also Debian's `pandoc-citeproc` and `pandoc-data` by your package? Or, add a note in the installations instructions tell the user to do it manually.

**Comment by jgm** [comment]
If I add

    Replaces: pandoc-data, pandoc-citeproc

to control.in, will that be sufficient?

+++ Jens Getreu [Aug 02 17 08:23 ]:

**Comment by getreu** [comment]
I think so, because I only uninstalled these: ` pandoc-data`, `pandoc-citeproc`.
