### ISSUE TITLE
Code Inside a List causes messy Dokuwiki Output

### ISSUE THREAD

**Issue by phi1010** [jgm/pandoc#3824]
pandoc 1.19.2 is not able to convert markdown containing source code inside a list to dokuwiki without representing the whole list as HTML:

```
text text text

- listitem 1
- listitem 2

        code

text text text
```

results in 

```
text text text

<HTML><ul></HTML>
<HTML><li></HTML>listitem 1<HTML></li></HTML>
<HTML><li></HTML><HTML><p></HTML>listitem 2<HTML></p></HTML>
<code>
code
</code><HTML></li></HTML><HTML></ul></HTML>

text text text
```

Dokuwiki currently supports Code Blocks in Lists (https://www.dokuwiki.org/faq:lists), the example above could be represented as follows:
```
text text text

  * listitem 1
  * listitem 2<code>
code
</code>

text text text
```

**Comment by jgm** [comment]
OK, I can special-case this.
