### ISSUE TITLE
Markdown Parser Incorrectly Parses Leading Numbers in Lists as Numbered List

### ISSUE THREAD

**Issue by phi1010** [jgm/pandoc#3825]
Version 1.19.2:

Pandoc causes a leading "2." in a list item to vanish, because it is incorrectly parsed as a list. In German, "2." is commonly used as abbreviation for second, such as "2nd".

`* 2. foo` causes pandoc to create a list:
```
<ul>
<li><ol start="2" style="list-style-type: decimal">
<li>foo</li>
</ol></li>
</ul>
```
where a single item
```
<ul>
<li>2. foo</li>
</ul>
```
would be appropriate, as in `* 2nd foo`
```
<ul>
<li>2nd foo</li>
</ul>
```

**Comment by jgm** [comment]
Here pandoc agrees with the majority of Markdown implementations.
https://johnmacfarlane.net/babelmark2/?normalize=1&text=*+1.+foo+causes+pandoc+to+create+a+list%3A%0A%0A

If you don't want this to create a list, put a backslash
before the period: `2\.`.
