### ISSUE TITLE
exclude convertig special character

### ISSUE THREAD

**Issue by Alir3za3** [jgm/pandoc#3826]
I'm using pandoc to convert **html** to **LaTeX** 
pandoc converts **non-breaking space** in HTML to **Tilde** in tex file
How can I prevent inserting Tilde instead of non-breaking space in my tex ?

**Comment by mb21** [comment]
please ask questions like this on the pandoc-discuss mailing list, the issue tracker is for bugs etc...

AFAIK you'll have to write a pandoc filter to strip any non-breaking spaces you don't want in the output...

**Comment by jgm** [comment]
Agreed, this should be better asked at pandoc-discuss.
Tilde is a nonbreaking space in LaTeX.

+++ Alir3za3 [Aug 02 17 00:29 ]:
