### ISSUE TITLE
date-meta a author-meta info is not in docs

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#3827]
In [templates sections](http://pandoc.org/MANUAL.html#templates) there is no reference to `date` and `authors` variables you use in HTML5 but even more to `date-meta` and `author-meta` and their difference among that and `date` and `authors`.

Can you please consider this as a documentation bug and clarify this in Manual?

**Comment by jgm** [comment]
This has been fixed.

**Comment by somenxavier** [comment]
Where is reference to `author-meta` and `date-meta`?

**Comment by mb21** [comment]
@somenxavier https://pandoc.org/MANUAL.html#metadata-variables
