### ISSUE TITLE
add draft watermark option or variable

### ISSUE THREAD

**Issue by wookietreiber** [jgm/pandoc#3829]
Support an option or variable that adds **draft** as a  **watermark** to the generated output. I think, the usefulness of this feature is self-explanatory.

---

I don't know if this would be an option or variable that all writers could support. Adding this to the **latex** template for myself was easy enough:

```diff
--- /usr/share/pandoc/data/templates/default.latex      2017-07-26 17:41:30.000000000 +0200
+++ draft-template.latex        2017-08-03 09:35:38.933388151 +0200
@@ -221,6 +221,8 @@
 $endif$
 \date{$date$}

+\usepackage{draftwatermark}
+
 \begin{document}
 $if(title)$
 \maketitle
```

**Comment by mb21** [comment]
I guess this is is out of scope. Especially, as it's easy to add it to your latex template, like you mentioned...

**Comment by siddhantladdha** [comment]
Sorry for necrobumping this old thread. However, this is the first result which comes up when searching for "adding draft watermark" and the given solution requires changing the default latex template, hence posting easier solution for people who land here in the future.

Adding the following to your YAML header solves the issue without needing to change the template.
```
---
title: "Untitled"
header-includes:
  - \usepackage{draftwatermark}
output: 
  pdf_document: 
    keep_tex: yes
---
``` 
Source: [Add a 'DRAFT' watermark on pdf result of R markdown [duplicate] from Stackexchange](https://stackoverflow.com/questions/34955592/add-a-draft-watermark-on-pdf-result-of-r-markdown)
