### ISSUE TITLE
Converting to man fails with empty definition in definition list

### ISSUE THREAD

**Issue by KenJackson** [jgm/pandoc#3832]
I convert an existing man page to html with the the 'man2html' package.  Then use pandoc to convert it back to man.  It fails and writes an empty man file.  For example:

man2html /usr/share/man/man1/chvt.1.gz > chvt.html
pandoc -s -f html -t man -o chvt.html.1 chvt.html

pandoc: blocks is null
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Writers/Man.hs:287:47 in pandoc-1.19.1-K4MTLUCdX282FQ0VY8hDKm:Text.Pandoc.Writers.Man

I've tried many different man files.  I've also tried converting the html file to an intermediate format first and then the intermediate format to man.  

Converting to man fails the same way when when I convert from these intermediate formats: native, jason, markdown, latex, docbook.

Converting to man succeeds when I convert from these intermediate formats: markdown_github, textile.  However the resulting man file doesn't render correctly and has extra junk added.

I'm using pandoc-1.19.1-1.fc26.x86_64 on Fedora Linux 26.

**Comment by mb21** [comment]
can you try with pandoc 1.19.2.1 or even better with the pandoc nightlies?

**Comment by jgm** [comment]
You must have a different version of man2html than I do.
(Mine doesn't take command-line arguments and doesn't
convert zipped man pages.)

Could you attach or link to the chvt.html you used, so
we can test?  Are you sure you don't have a garbage
html file because of the zipped input?

I tested on pandoc.1, using man2html, and could not
reproduce what you're seeing (with the dev version
of pandoc or with 1.19.1.1).

**Comment by KenJackson** [comment]
Here is the chvt.html file.
[chvt.html.zip](https://github.com/jgm/pandoc/files/1200992/chvt.html.zip)

I now see the first line doesn't belong there ("Content-type: text/html"), but I deleted it and got the same result.  Either way, I can view it in a browser.

**Comment by jgm** [comment]
Thank you!  I can reproduce this now, even with the dev version.

**Comment by jgm** [comment]
The HTML file contains
```html
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">SYNOPSIS</A><DD>
<DT><A HREF="#lbAD">DESCRIPTION</A><DD>
</DL>
```
which pandoc interprets as
```haskell
[DefinitionList
 [([Link ("",[],[]) [Str "NAME"] ("#lbAB","")],
   [[]])
 ,([Link ("",[],[]) [Str "SYNOPSIS"] ("#lbAC","")],
   [[]])
 ,([Link ("",[],[]) [Str "DESCRIPTION"] ("#lbAD","")],
   [[]])]]
```
This is a correct parse; the items in the definition list have terms and a single empty definition.

At line 312 of the (current) src/Text/Pandoc/Writers/Man.hs, we have
```haskell
forM defs $ \blocks -> do
                        (first, rest) <- case blocks of
                          ((Para x):y) -> return (Plain x,y)
                          (x:y)        -> return (x,y)
                          []           -> throwError $ PandocSomeError "blocks is null"
```
This fails when a definition is `[]` (empty).

Clearly pandoc should not be failing in this case.  This is an easy thing to fix.

**Comment by jgm** [comment]
One can work around this problem by adding `&nbsp;` after the `<DD>`, but even then pandoc doesn't give great results, because the HTML file is not structured in the way it expects.
It expects the sections to be level-1 headers, and the title to be in metadata.

**Comment by KenJackson** [comment]
I was using the man2html in the Fefora repository, man2html-1.6-18.g.fc26.x86_64.  But it generates sloppy html.

I found and compiled a different one:
   git clone https://github.com/man-pages-zh/man2html.git

It generates cleaner HTML and pandoc doesn't crash.
