### ISSUE TITLE
`--to markdown_github` adds spurious spaces in front of list items

### ISSUE THREAD

**Issue by snarkmaster** [jgm/pandoc#3834]
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.1, skylighting 0.1.1.5

There are two unnecessary spaces in front of list items `out` and `in` in this output:

```
$ echo $'- out\n    - in\n\n      ``` json\n      {"a": 4}\n      ``` \n\n      in2'  | \
    pandoc --from commonmark --to markdown_github 
-   out
    -   in
 
        ``` json
        {"a": 4}
        ```

        in2 
```

These are not required by Github, but they do confuse some other markdown parsers. Is there any way that `markdown_github` mode could output this instead?

```
- out
    - in
 
      ``` json
      {"a": 4}
      ```

      in2 
```

**Comment by snarkmaster** [comment]
It looks like it's part of the core writer:

```
-- | Convert bullet list item (list of blocks) to markdown.
bulletListItemToMarkdown :: WriterOptions -> [Block] -> MD Doc
bulletListItemToMarkdown opts bs = do
  contents <- blockListToMarkdown opts bs
  let sps = replicate (writerTabStop opts - 2) ' '
  let start = text ('-' : ' ' : sps)
  -- remove trailing blank line if item ends with a tight list
  let contents' = if itemEndsWithTightList bs
                     then chomp contents <> cr
                     else contents
  return $ hang (writerTabStop opts) start $ contents' <> cr
```

What is the rationale for trying to align bullet items on tab stops?

Would you be open to adding an extension guard that disables this behavior?

**Comment by mb21** [comment]
see e.g. https://github.com/jgm/pandoc/issues/2575 for the rationale...

**Comment by jgm** [comment]
@mb21 has the answer.  If you want to respect the 4-space rule and have continuation paragraphs lined up, you need either extra spaces after the bullet or extra spaces before the bullet.

Now, GitHub Markdown (now CommonMark) doesn't use the 4-space rule, so this isn't so important for that format, but pandoc's current `markdown_github` support does assume the 4-space rule.

I'm in the process of integrating bindings to `cmark-gfm`, the library GitHub uses to parse Markdown, and this should give you a more accurate parser and writer.

What implementations have trouble with the extra spaces?  That should be reported as a bug in those implementations; I don't consider it a problem with pandoc.  (Ah, I see from [babelmark2](https://johnmacfarlane.net/babelmark2/?normalize=1&text=-+++out%0A++++-+++in%0A+%0A++++++++in2+%0A) that lunamark and MultiMarkdown have trouble with this input.  Well, as the author of both lunamark and of peg-markdown, the basis of MultiMarkdown's current parser, I consider this a bug.)

**Comment by snarkmaster** [comment]
Thanks for the prompt and crisp reply. I agree that it's not a Pandoc bug, and that all implementations should accept the extra whitespace. There could be an extension to permit Pandoc to emit non-aligned continuation paragraphs, but it does not seem to be **that** nice of an idea, even though it's a tiny change. I'd close this out unless several more people have this need.

FWIW, my reason for using `markdown_github` is that it is currently the only flavor emitted by Pandoc that does not inject word-wrap linebreaks into paragraphs. I.e. my conversion takes me from:

```
one
two
```

to

```
one two
```

**Comment by snarkmaster** [comment]
On that tangent, of course writing down precisely what I need for the newlines gave me a good solution:

```
$ echo $'- out\n    - in\n\n      ``` json\n      {"a": 4}\n      ``` \n\n      in2\n      in3'  | \
    pandoc --from commonmark --to commonmark-hard_line_breaks 
  - out
      - in
        
        ``` json
        {"a": 4}
        ```
        
        in2 in3
```

**Comment by jgm** [comment]
Do you know about the `--wrap=[none|auto|preserve]` option?

>   FWIW, my reason for using markdown_github is that it is currently the
>   only flavor emitted by Pandoc that does not inject word-wrap linebreaks
>   into paragraphs.

**Comment by snarkmaster** [comment]
@jgm, unfortunately it doesn't have the desired effect with the `commonmark` writer. E.g.

```
$ echo $'hello, long\nsentence' | \
    pandoc --from commonmark --wrap=none --to commonmark  
hello, long
sentence
```

That might be a bug?

**Comment by jgm** [comment]
Yes, currently wrap=none behaves like wrap=preserve for
commonmark output.  This could be fixed; feel free to submit
an issue.  (We'd need to check for wrap=none and convert
soft breaks to spaces in an AST transformation.)

+++ snarkmaster [Aug 06 17 19:41 ]:

**Comment by snarkmaster** [comment]
I'm not blocked on this right now, so I'm not gonna make an issue, thus distracting you from more important things. Though in the abstract it does seem better if it worked. Thanks for offering to fix it.

**Comment by jgm** [comment]
@snarkmaster I've fixed wrap=none in the dev version.

**Comment by snarkmaster** [comment]
Awesome, thanks! I'll switch to it as soon as we update to the next release.

**Comment by zspitz** [comment]
@jgm 

> I'm in the process of integrating bindings to `cmark-gfm`, the library GitHub uses to parse Markdown, and this should give you a more accurate parser and writer.

What's the status of this? I am currently converting a number of `.docx` files into GFM, and seeing more than one space after the bullet marker:

```
The DLR provides three key components:

-   language implementation services with language interoperability model

-   dynamic language runtime services with fast dynamic dispatch and library support

-   common hosting APIs across languages
```

**Comment by jgm** [comment]
We no longer use cmark-gfm (avoiding a C dependency which isn't easily customizable with extensions).  Instead, for generating markdown of all flavors, we use pandoc's markdown writer, with different settings.  This writer traditionally aligned list contents on 4-space indents, because this gives the most portable output -- it will work with markdown implementations that use the 4-space rule, as well as others.  It's perfectly valid gfm.
