### ISSUE TITLE
`jar:` is unexpectedly converted to link when using `markdown_github`

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#3851]
Pandoc version: 1.19.2.1

Command line used: 
```shell
pandoc -f markdown_github+all_symbols_escapable+tex_math_dollars-ascii_identifiers -t html --mathjax
```

Complete input:
```
CLASSPATH=\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar:\$CLASSPATH
```
Actual output:
```
<p>CLASSPATH=$JAVA_HOME/lib/dt.<a href="jar:\$JAVA_HOME/lib/tools.jar:\$CLASSPATH" class="uri">jar:\$JAVA_HOME/lib/tools.jar:\$CLASSPATH</a></p>
```

Expected:
```
<p>CLASSPATH=$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$CLASSPATH</p>
```

It woks when replacing `markdown_github` with `markdown`.

**Comment by jgm** [comment]
This is from the `autolink_bare_uris` extension, which is part of the `markdown_github` package.  Pandoc has to guess what is a URI, and `jar:\$JAVA_HOME/lib/tools.jar:\$CLASSPATH` satisfies the condition.  You can turn this off with `-autolink_bare_uris`.
