### ISSUE TITLE
image markdown is unexpectedly converted to `embed`

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#3852]
Pandoc version: 1.19.2.1

Command line used: 
```shell
pandoc -f markdown_github -t html
```

Complete input:
```
![](http://7xqftp.com1.z0.glb.clouddn.com/jason_3_baad440c804f738fc62e519efa3fdb32.jpg-origin)
```
Actual output:
```
<p><embed src="http://7xqftp.com1.z0.glb.clouddn.com/jason_3_baad440c804f738fc62e519efa3fdb32.jpg-origin" /></p>
```

Expected:
```
<p><img src="http://7xqftp.com1.z0.glb.clouddn.com/jason_3_baad440c804f738fc62e519efa3fdb32.jpg-origin" /></p>
```

It woks when replacing `markdown_github` with `markdown`.

**Comment by jgm** [comment]
The HTML writer uses `embed` when the extension is not in the list [ "art", "bmp", "cdr", "cdt", "cpt", "cr2", "crw", "djvu", "erf",  "gif", "ico", "ief", "jng", "jpg", "jpeg", "nef", "orf", "pat", "pbm",  "pcx", "pgm", "png", "pnm", "ppm", "psd", "ras", "rgb", "svg", "tiff", "wbmp", "xbm", "xpm", "xwd" ].
See #264, closed by 8d13ff5bc3cff3c0ce0dc9455db9f7f29b384cdf.
