### ISSUE TITLE
Pandoc ignores \newtoggle, \toggletrue, \iftoggle, etc. in Latex Input

### ISSUE THREAD

**Issue by dangrec** [jgm/pandoc#3853]
pandoc 1.19.2.1

A latex file as follows

\documentclass{article}
\begin{document}
\newtoggle{ebook}
\toggletrue{ebook}
\iftoggle{ebook}{
	text
}{
  	%not ebook
}
more
\end{document}

put through pandoc as follows:
pandoc -f latex test.tex -t native -o test.atx

produces file test.atx as follows:

[Para [Str "more"]]

So it appears Pandoc does not support the whole conditional concept of "toggle". Is there a supported method of latex conditionals in Pandoc?
Thanks!

**Comment by jgm** [comment]
Currently no conditional constructions are supported.
I think we should add support for `\newtoggle`,
`\toggletrue`, `\togglefalse`, `\iftoggle` (from
etoolbox).  These would not be hard to support.

**Comment by corbolais** [comment]
Hello,

Just added a comment to commit  bfbdfa6.

It's about the \toggle -- as it is implemented in pandoc right now -- being on a per-file scope. 

This fails when using a LaTeX document w/ multiple input source files that make use of the \toggle.

It would be appreciated having the \toggle feature supported in a global manner. Just set up the \toggle in the main LaTeX file and handle the \toggletrue as needed and wherever needed.

Thanks for your help.
C.
