### ISSUE TITLE
CatchAll function for Lua filter

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#3859]
There should be a way to define catch-all functions in lua filters acting on all elements.

See also the respective [comment](https://github.com/jgm/pandoc/issues/3608#issuecomment-311663421) in the lua documentation issue.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Aug 21 17 09:04 ]:
>   There should be a way to define catch-all functions in lua filters
>   acting on all elements.
>
>   See also the respective [1]comment in the lua documentation issue.

Do you think this should be a reasonably straightforward
change?  If so, we should add to the 2.0 milestone.

**Comment by tarleb** [comment]
I expect it to take me an evening or two; adding it to the milestone.

**Comment by jgm** [comment]
I wonder whether it makes sense for the catch-alls to be
called Block and Inline.  (After all, it would be natural
to have different catch-alls for the two types.)

**Comment by tarleb** [comment]
I agree, that woud be very intuitive.  Should those functions always be run, or only if there is no more specific match?

I've implemented metatable-based catch-all, so the following method to count Inline element works now:

```lua
local num_inlines = 0

function catch_all(el)
  if el.tag and pandoc.Inline.constructor[el.tag] then
    num_inlines = num_inlines + 1
  end
end

function Pandoc(blocks, meta)
  return pandoc.Pandoc {
    pandoc.Para{pandoc.Str(num_inlines)}
  }
end

return {
  setmetatable(
    {Pandoc = Pandoc},
    {__index = function(_) return catch_all end}
  )
}
```

**Comment by jgm** [comment]
+++ Albert Krewinkel [Aug 22 17 21:00 ]:
>   I agree, that woud be very intuitive. Should those functions always be
>   run, or only if there is no more specific match?

Not sure.  I was thinking that they'd only be run if no more
specific function matched, but I hadn't really thought about
the other possibility.

**Comment by tarleb** [comment]
The fallback behavior seems like the saner behavior and was also much simpler to implement, so I went with that.
