### ISSUE TITLE
Markdown embedded HTML code style is invalid in PDF

### ISSUE THREAD

**Issue by XiaTeng1993** [jgm/pandoc#3870]
**The HTML code written in the markdown file is converted to a PDF file. Why did the style fail**

> tese.md
```html
<center>title</center>
<p style="margin-top:100px;color:orange;">https://github.com/jgm/pandoc</p>
```

> output.pdf

![image](https://user-images.githubusercontent.com/17228692/29649743-adf92c56-88c8-11e7-9469-6d81ad550ebb.png)

**Comment by vyp** [comment]
Did you use `-t html5` option?

**Comment by jgm** [comment]
Paragraph styles and colors are not supported.
Pandoc tries to capture structural elements of the document, but generally does not translate all the stylistic information.

**Comment by XiaTeng1993** [comment]
I've found a solution，that I need to install **wkhtmltopdf** and use  option `  -t html5`！thank you all
