### ISSUE TITLE
cannot download deb file

### ISSUE THREAD

**Issue by bubifengyun** [jgm/pandoc#3875]
download page: https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb

But nothing can download. I am in China. is it Blocked? Or it is deleted. Thank you.

**Comment by mb21** [comment]
works for me from Europe...

**Comment by bubifengyun** [comment]
could you send to my mail box, bubifengyun@sina.com ?
thank you very much.

**Comment by mb21** [comment]
you should have received a mail from wetransfer.com now...

**Comment by bubifengyun** [comment]
Thank you very much.
