### ISSUE TITLE
Colorlinks option failing when producing a beamer presentation

### ISSUE THREAD

**Issue by dpuleri** [jgm/pandoc#3877]
Here is the version I am running on macOS Sierra
```
pandoc -v
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/daniel/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

When using beamer and the colorlinks option the following error is produced:
```
! Package xcolor Error: Undefined color `Maroon'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.77 \end{frame}

pandoc: Error producing PDF
```

I realize there is a previous issue (#2680) that discusses this, but I believe that was in regard to the regular LaTeX output and not with the beamer option enabled.

Reproducible with:
```
pandoc -t beamer -V colorlinks -o test.pdf << EOT
# This is a test

So [This is a test].

[Test link](http://test.com).

EOT
```

A quick fix to get the command to run is by specifying the colors manually through the `linkcolor` and `urlcolor` variables:
```
pandoc -t beamer -V colorlinks -V linkcolor=blue -V urlcolor=blue -o test.pdf << EOT
# This is a test

So [This is a test].

[Test link](http://test.com).

EOT
```

However, there seems to be a limited amount of colors you can use through this option. The only ones that have worked for me are blue, white, and black. No fancy colors :frowning_face:.

**Comment by adunning** [comment]
Good catch. The problem is that we're passing the options for colour names to the `color` package, but Beamer loads `xcolor` instead of its own accord and overrides this. For now, you can fix it by adding `-V classoption=dvipsnames`, but I will fix this in the template.

**Comment by NikosAlexandris** [comment]
Is it the version of pandoc I use that still gives this error when, for example, using 
```
urlcolor: blue
```

in the header of a markdown - beamer presentation?

I use the solution provided by @dpuleri to work-around this error (i.e. using `-V colorlinks -V linkcolor=blue -V urlcolor=blue` in the  command line).
