### ISSUE TITLE
Synchronize or combine LaTeX/Beamer templates

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#3878]
Some of the recent changes to the LaTeX template need to be merged into the Beamer template, notably the use of `unicode-math` and `luatexja`.

Before working through this, would it indeed make sense to determine whether the two templates should be combined, as suggested in #3873? I haven't tested it, but it should theoretically be possible if the writer set a `beamer` variable to true and several conditionals were included to include and exclude several parts. This would make the template more complex to customize, but it would also make it easier to maintain within the codebase.

**Comment by jgm** [comment]
I'd welcome investigations about what would be required for
this.  It would be easy for the writer to set a beamer
variable.  But, for testing, you could just set the template
and the beamer variable manually on the command line.
