### ISSUE TITLE
Conversion from markdown to markdown_github alters escaped pipe characters

### ISSUE THREAD

**Issue by cacology** [jgm/pandoc#3887]
Using pandoc 1.19.2.1 converting from pandoc flavored markdown to GitHub flavored markdown, an escaped pipe `\|` becomes a regular pipe `|`, which causes GitHub to make what should be a pipe character a table instead.

input file "example.md":

     This | is | a | pipe | table.
     
     This \| is \| a \| series \| of \| pipes.

command:

    pandoc -f markdown -t markdown_github example.md

output:

    This | is | a | pipe | table.
    
    This | is | a | series | of | pipes.

expected output:

    This | is | a | pipe | table.
    
    This \| is \| a \| series \| of \| pipes.

My Haskell isn't great yet, but I think this might be an easy fix.  If someone wants to try to point me at it, I'll try it, though I realize that may be more work than just fixing it...

Respectfully submitted,
-James

P.S. Probably not needed to fix the issue, but if you're curious as to why I need escaped pipes in my markdown, see: https://cacology.github.io/characters/  which uses pipes as the standard bibliographical notation to indicate line breaks.  See also: http://www2.iath.virginia.edu/gants/Books/key.html or http://polaris.gseis.ucla.edu/jrichardson/dis237/Appendix%20A.htm

**Comment by jgm** [comment]
We just need to escape all `|` characters when the `pipe_tables` extension is enabled.

**Comment by jgm** [comment]
Look in `src/Text/Pandoc/Writers/Markdown.hs`, specifically at the escaping functions.

**Comment by jgm** [comment]
I also noticed that the new `gfm` output format (in dev pandoc) doesn't escape pipes.  This will require changes in the underlying C library.
