### ISSUE TITLE
Error when install Pandoc in my Windows10

### ISSUE THREAD

**Issue by ShixiangWang** [jgm/pandoc#3890]
When I installed pandoc in my Win10  system, error occurred. 

The version is **Pandoc.1.19.2.1**. It said that 
```
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2503.
```

**Comment by ShixiangWang** [comment]
![pandoc_bug](https://user-images.githubusercontent.com/25057508/29992948-b214adce-8fda-11e7-8272-3211c3a5c53d.png)

**Comment by jgm** [comment]
Has anyone else used the package installer on Windows 10?

**Comment by ShixiangWang** [comment]
I install base version before. But the R said I need install complete version.



来自 魅族 PRO 6s



-------- 原始邮件 --------
发件人：John MacFarlane <notifications@github.com>
时间：周三 9月6日 13:37
收件人：jgm/pandoc <pandoc@noreply.github.com>
抄送：王诗翔 <wangshx@shanghaitech.edu.cn>,Author <author@noreply.github.com>
主题：Re: [jgm/pandoc] Error when install Pandoc in my Windows10 (#3890)


Has anyone else used the package installer on Windows 10?

**Comment by CBenghi** [comment]
@jgm 
I've installed pandoc-1.19.2.1-windows.msi with no problem on two Windows 10 machines last week.

**Comment by ShixiangWang** [comment]
@CBenghi First I installed the base version. After uninstalling it, I installed the complete version. Did this operation occur my problem? Which directory did you install ?

**Comment by CBenghi** [comment]
I've used default values for every setting.
I'm not much familiar with pandoc, I was just trying to give jgm an answer to his question, I doubt I can be of much further help.

**Comment by SahilAgarwal321** [comment]
This is not an error of pandoc 

http://www.urtech.ca/2016/02/solved-how-to-fix-error-2503-2502-on-windows-10-when-installing-software/
(Has other useful links as well)

https://answers.microsoft.com/en-us/windows/forum/all/internal-error-25032502/28b361b7-b2d7-494d-8470-5969f6850f5a?auth=1

**Comment by mb21** [comment]
@SahilAgarwal321 thanks, seems to be a Windows permission problem then. Feel free to reopen otherwise...
