### ISSUE TITLE
Default papersize should be A4

### ISSUE THREAD

**Issue by adius** [jgm/pandoc#3894]
I guess pandoc is an international project.
Therefore the default papersize should be A4 and not US Letter.
Always astonishes me when I convert Markdown to PDF.

**Comment by mb21** [comment]
Technically, the `papersize` variable in pandoc's LaTeX template is undefined by default. pdflatex then defaults to US-Letter.

But indeed, we could discuss whether it makes sense to set `papersize` to `A4` by default...

**Comment by jgm** [comment]
+++ Mauro Bieg [Sep 05 17 16:59 ]:
>   But indeed, we could discuss whether it makes sense to set papersize to
>   A4 by default...

Why would we want to do that?
By leaving it unset, we use the default paper size that was
set up with the user's latex distribution.  This seems just
the right thing to do.

The default can be changed in texlive using:

    tlmgr paper a4

**Comment by adius** [comment]
> By leaving it unset, we use the default paper size that was
set up with the user's latex distribution

Except that it's really surprising that my settings in texlive influence the behavior of pandoc.
Imagine you change some settings in texlive and a few weeks later you run a pandoc command (maybe even copy & paste from an online tutorial, or use some 3rd party tool which uses pandoc under the hood) and you get a completely different output than expected / described in the tutorial. 
As if a user would make the connection to texlive … 🙈

**Comment by mb21** [comment]
> The default can be changed in texlive

ah, right...

> Except that it's really surprising that my settings in texlive influence the behavior of pandoc.

Pandoc (by default) uses LaTeX for PDF generation, so there's no way around that.

Maybe one of the tools listed here can help you do more reproducible builds: https://github.com/jgm/pandoc/wiki/Pandoc-Extras#workflow

**Comment by deligant** [comment]
On Ubuntu 20.04 LTS pandoc/latex still uses some hidden info for paper size: my /etc/papersize clearly shows "a4" but running pandoc md -o pdf still produces a letter PDF.

**Comment by bgrenet** [comment]
> By leaving it unset, we use the default paper size that was set up with the user's latex distribution. This seems just the right thing to do. 
> The default can be changed in texlive using:
>
>     tlmgr paper a4

This is quite incorrect, and the explanation can be read here: https://tex.stackexchange.com/questions/356545/why-does-the-hyperref-package-change-the-paper-size. TL;DR: If you use the hyperref package, the system-wide preference has basically no influence on the paper size. As of today, pandoc seems to be defaulting to letter. This is exactly what is described in the latest comment.

**Comment by jgm** [comment]
> After many fiddling reading the documentation, I still could not figure out how to make a default configuration for pandoc to have the command line -V papersize:a4 -V margin:2cm as a default for every PDF I generate from the command line.

One way is to use a default file.  You still need to specify the default file on the command line, but that is less fiddly, it could just be `-d standard` or something.

As for the question raised in this issue, perhaps I was wrong in what I assumed about LaTeX's behavior. Nonetheless, I think switching the default to `a4` is probably not a good idea: it would mean that existing document generation breaks mysteriously and in a hard-to-notice way.  It may also be that there are more `letter` paper users of pandoc than `a4` users -- it is hard to know without analytics.  Moreover, in places where pandoc needs to default to a `lang` setting, it chooses `en-US`, which goes with `letter`.

Perhaps it would be worth making the default paper size depend on the country component of the `lang`. But that might be too "magic."

**Comment by iandol** [comment]
As an A4 user, I also think changing the default behaviour now would be **unexpected** for many users. `papersize` metadata is clearly described in the manual, and it is trivial to add it to your invocation of Pandoc. The fact that LaTeX is complex and each package can override other settings (and solving a trivial problem takes searching through numerous search results) is a LaTeX problem, not a Pandoc problem. Pandoc supports a bunch of PDF engines, many of which have more clearly defined behaviours.

**Comment by nopria** [comment]
> The default can be changed in texlive using:
> 
>     tlmgr paper a4

This does not work; after such command both TeXLive and LibreOffice have A4 as default paper size, but pandoc conversion from Markdown to ODT produces a USLetter size document.

**Comment by jgm** [comment]
`tlmgr` only affects the behavior of LaTeX. If you're converting to ODT, LaTeX is never involved.

**Comment by bpj** [comment]
Can't you create a custom reference ODT and set the paper size to A4 in it? I have done that for DOCX. I use Linux/Android but all my clients use DOCX. I also have a reference DOCX with appropriate settings for each human language I work with.
