### ISSUE TITLE
Polyglossia/Bidi error in LaTeX template

### ISSUE THREAD

**Issue by talazem** [jgm/pandoc#3898]
I am using Pandoc to output to XeLaTeX, using the default.latex template.

When using bidi languages, such as Arabic, I found that I had to move the following code to an earlier point in the stylesheet, placing it *before* the invocation of polyglossia (and thus bidi), in order for bidi to work and not throw up an error.

```
$for(header-includes)$
$header-includes$
$endfor$
```

**Comment by jgm** [comment]
What are you putting in your header-includes?
Generally we like this to come last, giving people the
opportunity to override things in the template.

+++ talazem [Sep 06 17 02:11 ]:

**Comment by talazem** [comment]
To my understanding, I am not explicitly using header-includes. It is not in my YAML.

The packages that are being inserted, via my template's $header-includes$, are:
- subfig
- float
- cleveref
(At one point, the captions package was being called, and that was also causing bidi to panic.)

The following are part of my custom-memoir.latex template, and are also being invoked just before bidi:
- longtable,booktabs
- graphicx,grffile
- parskip

Let me know if this is not what you are looking for, and if you need to see the YAML or something else. I am relatively new to Pandoc.

**Comment by jgm** [comment]
Try using a custom template, and putting the problematic
packages before the polyglossia invocation, instead of
putting them in header-includes.  I'm not sure I'd want
to move header-includes back just because SOME things
you could put in it will confilct with an earlier
polyglossia include...


+++ talazem [Sep 06 17 16:04 ]:

**Comment by jgm** [comment]
On second thought, maybe it wouldn't hurt to put the bidi stuff after header-includes.

**Comment by talazem** [comment]
Just to be clear, I am not explicitly invoking those other packages. They are appearing, via the $header-includes$, depending on what I do in my pandoc .md document. Thus the only solution I found in my custom template was to move the $for(header-includes)$...$endfor$ before polyglossia.

**Comment by mb21** [comment]
@adunning ...?

**Comment by adunning** [comment]
I am not aware of any packages that need to be loaded after bidi, so yes, it would make sense to move that section after `header-includes`.
