### ISSUE TITLE
Arabic characters are generated separately, I think it's a bug after trying all configurations

### ISSUE THREAD

**Issue by wiseomran** [jgm/pandoc#3900]
Arabic characters are generated separately, and it should be one word not separated.
I've tried all possible configurations:

variables:  -V mainfont:"Amiri" -V dir:rtl -V polyglossia-lang:arabic
custom template: --template=cust.latex
included separate tex file with configuration: -H include.tex
yaml file: metadata.yaml

**here is the command I use to compile:**

`>pandoc --latex-engine=xelatex -V lang:arabic -V polyglossia-lang:arabic -V mainfont:Amiri 4.tex -o 4.pdf -V dir:rtl`

**here is a picture after compilation with TeXworks:**

![image](https://user-images.githubusercontent.com/5115327/30199328-ed27f52a-947a-11e7-92c5-52f3be2c9d1e.png)

**and here is the result with pandoc:**

![image](https://user-images.githubusercontent.com/5115327/30199404-43d71bf8-947b-11e7-83b8-2db99376b0f8.png)

**and here is the source file:**

```
\documentclass[a4paper,12pt]{article}
\usepackage[pdfauthor={Yousef Raffa},pdftitle={Translation of The ARRL LoTW Registration Instructions in Arabic}]{hyperref}

\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage{arabic}
\setotherlanguage{english}

\setmainfont[Ligatures=TeX]{Amiri}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\pagestyle{headings}

\title{ترجمة لتعليمات التسجيل في \textenglish{ARRL LoTW}\\ \textenglish{Translation of ARRL LoTW Registration
Instructions in Arabic}}
\author{يوسف عدنان رفـّـه\and Yousef A. Raffah}
\date{\today}

\begin{document}
\maketitle
\thispagestyle{empty} % No page number on 1st page

\section{التعليمات}

بسم الله الرحمن الرحيم


اتبع الخطوات التالية لإتمام عملية إنشاء حسابك الخاص في دفتر سجلات العالم 
\textenglish{Logbook of the World}.

\subsection{الخطوة الأولى - تنزيل و تهيئة البرنامج}
دفتر سجلات العالم \textenglish{Logbook of the World} يستخدم برنامج اسمه \textenglish{TrustedQSL} وهو
\end{document}

```

**here is my metadata.yaml:**

```
title: Foo
author: Omran
keep_tex: true
number_sections: yes
toc: yes
toc_depth: 2
header-includes:
- \newfontfamily\arabicfont[Script=Arabic]{Amiri}
- \setmainfont[Ligatures=NoCommon]{Amiri}
```

**here is my include.tex:** 
```

\usepackage{setspace}

\usepackage{fontspec}
\usepackage{polyglossia}

\setmainlanguage{english}
\setotherlanguage{arabic}

\setmainfont[Ligatures=TeX]{Amiri}

\newfontfamily\arabicfont[Script=Arabic,Scale=1.1]{Scheherazade}
```

**Comment by mb21** [comment]
If your input file is in .tex format, you actually don't need `pandoc`, you can just use `xelatex` directly.

Usually people use pandoc to go e.g. from markdown to LaTeX... if the generated LaTeX can be improved in that case, we would like to do so, but we would have to know exactly what the output should be.

**Comment by wiseomran** [comment]
I've tried from md files to pdf with the same result.
I think the main issue now is the  Arabic Ligatures, the output should be like this:

![image](https://user-images.githubusercontent.com/5115327/30202939-e434ff36-9488-11e7-8767-7d4117ab0983.png)

**Comment by jgm** [comment]
What version of pandect are you using?  `pandoc --version`

**Comment by wiseomran** [comment]
pandoc 1.19.2.1

I want to mention here that when I tried some fonts it worked well, one of them is installed by default in windows 10:  Arial Unicode MS - Geeza Pro - Droid Kufi

**Comment by jgm** [comment]
OK, one thing you should do is use
```
-V lang:ar
```
instead of
```
-V lang:arabic -V polyglossia-lang:arabic
```
Try that and see how it looks.  The `\textenglish` bits will still be missing; I've fixed that in the dev verison.

**Comment by wiseomran** [comment]
OMG That fixed it ! all that time trying `arabic` instead of `ar` because I thought it's like `polyglossia` package.

Thanks a lot for your time and patience.

**Comment by wiseomran** [comment]
I wonder why it doesn't work when I used YAML header?
I've used this header and it also fails:
````
pandoc --latex-engine=xelatex -V mainfont:"Amiri" 4.tex metadata3.yaml -o 4.pdf
---
lang: ar
mainfont: ArialUnicodeMS
header-includes: "\\newfontfamily\\arabicfont[Script=Arabic]{Amiri}
---

**Comment by mb21** [comment]
You shouldn't set the mainfont twice: `-V mainfont:"Amiri"` and in the YAML: `mainfont: ArialUnicodeMS`. Please see http://pandoc.org/MANUAL.html to get a better understanding of how pandoc works...

**Comment by jgm** [comment]
YAML header only works with Markdown input, and you're using
latex input.

+++ Mohamed Omran [Sep 09 17 21:27 ]:

**Comment by Ai80-8** [comment]
Delete it all
