### ISSUE TITLE
docx writer - "different odd/even pages" is not selected even if template has it on

### ISSUE THREAD

**Issue by agusmba** [jgm/pandoc#3901]
First of all thank you for making this amazing tool.

I'm trying to set up a markdown -> docx pipeline, using **pandoc 1.18** on windows 7.

I'm tweaking the docx template (reference-docx), but I just realized that odd/even pages selection (header/footer) on my template is not honored in the generated docx (thus the odd style is applied to the whole document).

**WORKAROUND:**
Thankfully the even/odd styles are not lost and I can manually go to the header of the generated docx and select "different odd/even pages" and I will get the expected result.

Ideally the generated docx should have this option selected if the reference-docx had it.

**Comment by jgm** [comment]
Could you post a link to the reference docx that has this feature?

**Comment by agusmba** [comment]
Certainly.

I created a mimimum (non)working example showing this problem, with a simple markdown file with steps to reproduce, the reference docx, and the resulting docx I get with pandoc.

[pandoc-issue-3901.zip](https://github.com/jgm/pandoc/files/1290353/pandoc-issue-3901.zip)

**Comment by agusmba** [comment]
At first glance it seems simply writing `<w:evenAndOddHeaders/>` to settings.xml would fix this.
It probably would make sense to check the existence of this tag in the reference doc first and include it in the output accordingly.

I've never coded in haskell, but reading the source comments, maybe adding `, 'w:evenAndOddHeaders'` somewhere around [here](https://github.com/jgm/pandoc/blob/8cd1e00bbc50c0d5efc9c5fd08f0336d50c416f8/src/Text/Pandoc/Writers/Docx.hs#L550) could do the trick (sorry if there are more changes to take into account, I havent tested nor even compiled this change)

**Comment by mb21** [comment]
> At first glance it seems simply writing <w:evenAndOddHeaders/> to settings.xml would fix this.

Can you modify the generated docx file and test this? The docx is just a zip which you can modify with the usual tools...

**Comment by agusmba** [comment]
> Can you modify the generated docx file and test this? The docx is just a zip which you can modify with the usual tools...

Yes I tested it manually before posting, that's why I proposed including it in the docx. I should have mentioned it earlier, sorry.

I wasn't sure if on the pandoc side there was something else to consider.

**Comment by agusmba** [comment]
This seems like a simple enough fix to try.
Knowing nothing about haskell I was reluctant about downloading the 3GB dev environment, but if you prefer I could try to send a PR...

**Comment by mb21** [comment]
@agusmba Pull requests are always welcome and hacking on pandoc is a great way to get your feet wet with real-world haskell! Personally, I recommend using [stack](https://github.com/commercialhaskell/stack) to build the pandoc source code:

    $ git clone ...
    $ cd pandoc
    $ stack setup
    $ stack build

see also http://learnyouahaskell.com/chapters and maybe https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md

**Comment by agusmba** [comment]
Ok, I got a working pandoc in my PC with this issue fixed.
I'll check if the current tests are still OK, and I should try to write an automatic test for this issue (this will probably take a lot longer than the fix itself...)

**Comment by jgm** [comment]
We don't really have any tests for the docx writer at the
moment!  (I know, it's shameful.)  So don't feel like you
need to add those for the PR.

+++ Agustín Martín Barbero [Oct 09 17 22:13 ]:

**Comment by agusmba** [comment]
Mmmm I don't see an easy way of automating tests for this.

I have checked that all current tests run OK, and I have manually tested that the fix works for reference doc with and without the evenAndOddHeaders mark set.

It seems all tests (at least in the docx writer section) deal with native pandoc representation of the document. However this is not the case here, as the presence (or absence) of the evenAndOddHeaders mark is only dealt with at the docx writing stage, and as far as I can see is not reflected in the internal pandoc format.

How would you go about making an automated test for this case?

EDIT: @jgm I just saw your comment, I'll make the PR then with the simple fix.

**Comment by jgm** [comment]
+++ Agustín Martín Barbero [Oct 09 17 15:56 ]:
>   It seems all tests (at least in the docx writer section) deal with
>   native pandoc representation of the document. However this is not the
>   case here, as the presence (or absence) of the evenAndOddHeaders mark
>   is only dealt with at the docx writing stage, and as far as I can see
>   is not reflected in the internal pandoc format.

Yes, the current tests are just round-trip tests to see that
write docx >=> read docx is the identity in various cases.
That won't help with these presentational details.

>   How would you go about making an automated test for this case?

You'd have to write a custom test that uses writeDocx to
create a docx using a special refererence.docx, then uses
zip-archive to unzip it and check that it contains the
evenAndOddHeaders mark.  But I think it's okay to go without
this.
