### ISSUE TITLE
PDF convertion fails

### ISSUE THREAD

**Issue by alphardex** [jgm/pandoc#3907]
At first:
``` bash
$ pandoc alias.md -s -o alias.pdf
! Package inputenc Error: Unicode char 鎳?(U+61D2)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.98 鎳?

Try running pandoc with --latex-engine=xelatex.
pandoc.exe: Error producing PDF
```
Then after installing another several packages:
``` bash
$ pandoc alias.md -s -o alias.pdf --latex-engine=xelatex
! Undefined control sequence.
<argument> \LaTeX3 error:
                           Erroneous variable \c__fontspec_shape_n_n_tl used!
l.3806 \emfontdeclare{ \emshape, \eminnershape }

pandoc.exe: Error producing PDF
```
It still failed.

**Comment by mb21** [comment]
Have you tried what it says in your error message?

> Try running pandoc with --latex-engine=xelatex.

Also, from http://pandoc.org/CONTRIBUTING.html:

Make sure you can reproduce the bug with the latest released version of pandoc
(or, even better, the development version).

Your report should give detailed, *reproducible* instructions, including

  * the pandoc version (check using `pandoc -v`)
  * the exact command line used
  * the exact input used
  * the output received
  * the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large,
try to whittle it down to a *minimum working example*.
