### ISSUE TITLE
Pb with Code or Pre inside a List in textile

### ISSUE THREAD

**Issue by vicnet** [jgm/pandoc#3916]
pandoc 1.16.0.2

This textile file is not converted:
```
# text text
<pre>blabla</pre>
```
It is the same with \<code\> instead \<pre\>

with:
```
# text text
@blabla@
```
it is OK

**Comment by vicnet** [comment]
Suppose it is the reader...
See also #3824 or #3733

**Comment by jgm** [comment]
Dev version of pandect gives:
```
<p># text text</p>
<pre><code>blabla</code></pre>
```
IS that the correct output? If so, this can be closed.

**Comment by jgm** [comment]
Sorry, I see the issue now. (Missed that this was a textile list item.)
