### ISSUE TITLE
default.latex 

### ISSUE THREAD

**Issue by NMarkgraf** [jgm/pandoc#3920]
The line:

```
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{long table}}{}

```
in the new default.latex breaks every latex beamer output with the error:

> (/usr/local/texlive/2016/texmf-dist/tex/latex/mdwtools/footnote.sty
> Package: footnote 1997/01/28 1.13 Save footnotes around boxes
> \fn@notes=\box66
> \fn@width=\dimen290
> )
> Runaway argument?
> \def \insertfootnotetext {\@@ }\def \insertfootnotemark {\@makefnmark \ETC.
> ! File ended while scanning use of \@tempa.
> <inserted text>
> \par
> l.95 }{}

running without this line works perfect for me.

**Comment by jgm** [comment]
Fixed by 2e2795412def2f1f7c01b0b719b4d15a9b6f20f4
