### ISSUE TITLE
The latex character "\acute" is not converted to other format.

### ISSUE THREAD

**Issue by erimpapova** [jgm/pandoc#3922]
When having this input
Y$\pi${\'o}$\gamma$$\varepsilon$$\iota$$\alpha$ $\upsilon$$\delta$$\rho$$\alpha$$\upsilon$$\lambda$$\iota$$\kappa$$\acute{\eta}$ $\kappa$$\alpha$$\iota$ $\mu$$\alpha$$\theta$$\eta$$\mu$$\alpha$$\tau$$\iota$$\kappa$$\acute{\alpha}$ $\mu$o$\nu$$\tau$$\acute{\varepsilon}$$\lambda$$\alpha$ $\sigma$$\tau$o A$\rho$$\gamma$o$\lambda$$\iota$$\kappa${\'o} $\pi$$\varepsilon$$\delta$$\acute{\iota}$o

I get this output:
Yπóγεια υδραυλικ$\acute{\eta}$ και μαθηματικ$\acute{\alpha}$ μoντ$\acute{\varepsilon}$λα στo Aργoλικó πεδ$\acute{\iota}$o

As you can see in the output:
The $\acute{\eta} is not converted to ή
The $\acute{\alpha}$ is not converted to ά
The $\acute{\varepsilon}$ is not converted to έ
The $\acute{\iota}$ is not converted to ί

Also, in other examples the ώ is not supported as well.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information.

From [Contributing to pandoc](http://pandoc.org/CONTRIBUTING.html):

> Make sure you can reproduce the bug with the latest released version of pandoc
> (or, even better, the development version).
> 
> Your report should give detailed, *reproducible* instructions, including
> 
>   * the pandoc version (check using `pandoc -v`)
>   * the exact command line used
>   * the exact input used
>   * the output received
>   * the output you expected instead
> 
> A small test case (just a few lines) is ideal.  If your input is large,
> try to whittle it down to a *minimum working example*.


Please also search the (open *and* closed) issues to make sure the issue hasn't come up before.
Check the [User's Guide] and [FAQs] for anything relevant.
Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss).

[User's Guide]: http://pandoc.org/MANUAL.html
[FAQs]:  http://pandoc.org/faqs.html
