### ISSUE TITLE
[markdown to docx] html table breaks

### ISSUE THREAD

**Issue by goumang2010** [jgm/pandoc#3924]
-  the pandoc version (check using pandoc -v)
```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```

- the exact command line used
```bash
pandoc -f markdown -t docx -o test.docx
```

- the exact input used
```
<table summary="Relationship between media groups and media types">
<caption>Relationship between media groups and media types</caption>
<tbody>
<tr>
<th>Media Types </th>
<th>Media Groups</th>
<th>Media Groups</th>
<th>Media Groups</th>
<th>Media Groups</th>
</tr>
<tr>
<th>&nbsp; </th>
<th>continuous/paged </th>
<th>visual/audio/speech/tactile </th>
<th>grid/bitmap </th>
<th>interactive/static</th>
</tr>
<tr>
<th>braille</th>
<td align="center">continuous</td>
<td align="center">tactile</td>
<td align="center">grid</td>
<td align="center">both</td>
</tr>
<tr>
<th>embossed</th>
<td align="center">paged</td>
<td align="center">tactile</td>
<td align="center">grid</td>
<td align="center">static</td>
</tr>
</tbody>
</table>
```

- the output received
![image](https://user-images.githubusercontent.com/12218607/30445989-66fb2fb8-99ba-11e7-82c1-c2a4873d17f2.png)

- the output you expected instead
When using `pandoc -f html -t docx -o test.docx` with the same input, the result is:
![image](https://user-images.githubusercontent.com/12218607/30446233-1a432d50-99bb-11e7-9924-d1aa9766d3d1.png)

**Comment by mb21** [comment]
Thanks for the detailed report. This is expected behaviour, since HTML in markdown input is treated as [raw HTML](http://pandoc.org/MANUAL.html#raw-html). Depending on the rest of your markdown file you can use pandoc to go from markdown -> html -> docx:

    pandoc -f markdown -t html | pandoc -f html -t docx -o test.docx

**Comment by phmarek** [comment]
I've got the same linear output when going from `org-mode` to `docx` directly.

```
| head1 | head 2 |
|-
| data1 | data2 |
| data3 | data4 |
```

looks okay in PDF, but becomes a linear text in `.docx`.

**Comment by mb21** [comment]
@phmarek In order for the second column not be be ignored, your table should look as follows (see the MANUAL for details):

    | head1 | head 2 |
    |-------|---------
    | data1 | data2  |
    | data3 | data4  |

**Comment by phmarek** [comment]
Hmmm, is the exact number of dashes important? This part gets autogenerated, and if I didn't have to check the length of the written columns it would be much easier.

Furthermore, the table is correct with PDF output, so it looks like pandoc knew to create multiple columns! (My real problem is with 4 columns, BTW.)

**Comment by agusmba** [comment]
@phmarek you can use compact mode without problems (at least in the dev version of pandoc)

```markdown
| asdf | asdf | asdf | asdf | asdf |
|---|---|---|---|---|
| s | s | s | s | s |
| dd | dd | dd | d | dd |
| ff | ff | ff | ff | ff |
```
works

**Comment by tarleb** [comment]
I believe there is a misunderstanding here. @phmarek seems to be using org-mode, which uses a subtly different table format. It appears to be parsed correctly, but I'm not sure why the docx output is different.

**Comment by phmarek** [comment]
Okay, thanks a lot!

**Comment by agusmba** [comment]
ah, sorry I wrongly assumed the markdown table format was the same.

**Comment by mb21** [comment]
@phmarek you should probably open a new issue with the exact command and input used... try with the newest pandoc version or even the nightly builds.
