### ISSUE TITLE
html to docx fails to parse certain html tables

### ISSUE THREAD

**Issue by sdsawtelle** [jgm/pandoc#3925]
I am using Pandoc 1.19.2.1 and from command line doing `pandoc -o mfyile.docx myfile.html`. 

A simple test HTML table is correctly parsed and appears as a table object in the resulting docx. However the following table is not recognized as a table (appears as text in the output docx) and I am trying to understand why:

```
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>fr</th>
      <th>num</th>
      <th>frac_dataset</th>
    </tr>
    <tr>
      <th>client_city</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>--</th>
      <td>1.0</td>
      <td>2</td>
      <td>0.000012</td>
    </tr>
    <tr>
      <th>----</th>
      <td>1.0</td>
      <td>1</td>
      <td>0.000006</td>
    </tr>
  </tbody>
</table>
```

This table markup was produced by nbconvert's Jupyter notebook to HTML processor and was the result of displaying a Pandas dataframe. In HTML the table is rendered like:

![image](https://user-images.githubusercontent.com/7070776/30515996-e9337106-9b00-11e7-9576-811a215acddc.png)

**Comment by jgm** [comment]
The problem is that this table has a two-row header (thead
contains two tr elements).  Pandoc can handle a one-row
header (thead contains th elements directly), but not
a multi-row header -- the data model for tables is too
simple.

See https://github.com/jgm/pandoc/issues/1024

**Comment by sdsawtelle** [comment]
Gotcha, thanks very much for the explanation. 

As a makeshift alternative to changing the data model, maybe this specific problem could be handled by some parsing logic : like capturing all the `<tr>` elements that come after the first one and inserting them down at the beginning of the `<tbody>`? Then under some styles the tables still look passable.

I modified my above example a bit, but if I change it by hand as described, then the docx conversion looks OK.
![image](https://user-images.githubusercontent.com/7070776/30516485-be4074ea-9b0e-11e7-9f58-e8748b8e3a4d.png)

**Comment by jgm** [comment]
In general, we try not to modify structure, so if we can't handle the structure of an HTML table, we pass it through as raw HTML.  (Thus it can be used e.g. in Markdown output.)
