### ISSUE TITLE
Docx reader: Split or combine paragraphs ignored with track-changes

### ISSUE THREAD

**Issue by HeirOfNorton** [jgm/pandoc#3927]
When reading a Docx file with tracked-changes, if a paragraph break is added or removed in the changes, then these are always output as separate paragraphs, regardless of how the track-changes option is set.

In docx files, if a tracked edit adds or removes a paragraph break, then it is saved in the document.xml as two changes: one change for the added/removed text, and a separate change (in the "Paragraph properties" of the first of the two paragraphs) for the added/removed paragraph break. It appears Pandoc does not parse the changed paragraph break. I have attached a minimal file that has both an added and removed paragraph break, with no other changes.
[split_para.docx](https://github.com/jgm/pandoc/files/1309425/split_para.docx)

Pandoc should combine these separate paragraphs as appropriate based on the tracked-changes options. (I'm not sure how to deal with tracked-changes=all. Maybe an empty span at the end of the paragraph with an appropriate class marker?)

**Comment by jkr** [comment]
The version in your document and the version that I just created seem to use different methods for registering this. Let me spend a bit of time with the spec and see if this is doable.

**Comment by jkr** [comment]
Okay, I think I understand the spec on this now. But you're right -- we should figure out `--track-changes=all` for this. Docx references the insertion or deletion of the paragraph break that *follows* the paragraph under consideration. I see three options here -- @jgm, any thoughts? (Class names are off the cuff)

1. Put an empty span at the end of the paragraph before the altered break:
~~~
Inserted a break[]{.paragraph-insertion author="jkr" date="..."}

here
~~~

2. wrap the first par in a div
~~~
::: {.pargragraph-inserted-after author="jkr" data="..."}
Inserted a break
:::

here
~~~

3. wrap all paras with modifiied breaks in a div
~~~
:::{.inserted-breaks author="jkr" date="..."}
Inserted a break

here
:::
~~~

I have a pretty strong preference for something like the first one, even though it seems like a misuse to use a span to refer to block-level changes. First of all, it prevents odd complications of changes withing changes: all changes stay at the same level. Second, I think it's just the clearest, though all are pretty ugly. But then, `--track-changes=all` is always pretty ugly.

**Comment by jgm** [comment]
First one looks good to me too.

**Comment by jkr** [comment]
Shoot -- multiwayif formatting problem. I'll have to fix that.
