### ISSUE TITLE
Not catching org-mode code markup with certain ending characters

### ISSUE THREAD

**Issue by paulbdavis** [jgm/pandoc#3933]
When using org mode as an input, certain code formatted text is not being parsed when certain characters are at the end

```
 % pandoc --version 
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.1, texmath 0.9.4.2, skylighting 0.1.1.5
```

```
 % echo "~C-c '~" | pandoc -f org    
<p>~C-c '~</p>

(expected output <p><code>C-c '</code></p>
```

This does not seem to be the case when there are more characters after the `'`

```
 % echo "~C-c ' foo~" | pandoc -f org
<p><code>C-c ' foo</code></p>
```

**Comment by tarleb** [comment]
Thanks for the report. This used to be the correct behavior for previous org versions, but it seems like this was changed recently.

**Comment by tarleb** [comment]
For the record: this was changed in org-mode 9.0, which was released 2016-11-02 (so "recently" was probably the wrong word here).
