### ISSUE TITLE
Do not recognize header from Word 2016

### ISSUE THREAD

**Issue by crystalfp** [jgm/pandoc#3934]
Recently upgraded my Office and pandoc does not recognize anymore headers level 2. Try to convert to markdown the attached file using: `pandoc -s --atx-headers '.\bug titles.docx' -o '.\bug titles.md'`
And the level 2 titles are rendered as normal text.

Office Professional 2016
pandoc  1.19.2.1
Windows 10 64 bits

[bug titles.docx](https://github.com/jgm/pandoc/files/1329859/bug.titles.docx)

**Comment by jgm** [comment]
The headings need to have a heading paragraph style.  (E.g. Heading 1)
I see in your document that the level-1 heading has paragraph style Heading1, but the lower headings seem to have only a character style Heading2Char.  @jkr can you take a look?

**Comment by crystalfp** [comment]
Thanks for looking!
I found other files that instead render without problems. I don't know why this is special.
Anyway, the file has been created by pasting text copied from a web page. Initially the level 2 headers show as "Strong". I selected them and changed the style to "Heading 2".

**Comment by danse** [comment]
i confirm that lever 2 headers in that file are not marked as such, so nothing to fix on the pandoc side. we can probably close this
