### ISSUE TITLE
Error: pandoc document conversion failed with error 67 / TlsExceptionHostPort (HandshakeFailed Error_EOF)

### ISSUE THREAD

**Issue by bobcanthelpyou** [jgm/pandoc#3936]
I am using RStudio Desktop v1.0.153 and R v3.2.3-4 with the Packages rmarkdown and googleVis.

RStudio is packed with Pandoc v1.17.x but i received the following error message
```
/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS Using_googleVis_with_knitr.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Using_googleVis_with_knitr.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /usr/lib64/R/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpvGmQTq/rmarkdown-strcab5188a9b7.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
pandoc: Could not fetch https://www.google.com/jsapi?callback=displayChartComboChartIDcab2daa9d7e
HttpExceptionRequest Request {
  host                 = "www.google.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/jsapi"
  queryString          = "?callback=displayChartComboChartIDcab2daa9d7e"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed Error_EOF))
Error: pandoc document conversion failed with error 67
```

I updated Pandoc to v1.19.2.1 (in /usr/lib/rstudio-server/bin/pandoc/ out of the pandoc-1.19.2.1-1-amd64.deb) now the error message is a little bit different
```
/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS Using_googleVis_with_knitr.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Using_googleVis_with_knitr.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /home/bob/R/x86_64-redhat-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpZZmmvP/rmarkdown-strccd75562dd64.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
pandoc: Could not fetch https://www.google.com/jsapi?callback=displayChartComboChartIDccd77092e5bf
TlsExceptionHostPort (HandshakeFailed Error_EOF) "www.google.com" 443
Error: pandoc document conversion failed with error 67
```

To reproduce the error i downloaded an example file from https://raw.githubusercontent.com/mages/googleVis/master/vignettes/Using_googleVis_with_knitr.Rmd and started R:
```
install.packages("rmarkdown")
install.packages("googleVis")
Sys.setenv(RSTUDIO_PANDOC="/usr/lib/rstudio-server/bin/pandoc")
library("rmarkdown")
render("Using_googleVis_with_knitr.Rmd")
```

The result is the error above.

**Comment by jgm** [comment]
Please report this to the RStudio developers instead.  If they determine that there's a problem in pandoc, they or you can bring it here.  But at this point it's hard to tell what is going on, and I can't even test this.  (I don't use rstudio.)  If you can get an example that allows the problem to be reproduced using pandoc by itself, then we could do something with it.

**Comment by mb21** [comment]
This sounds suspiciously like the [bug the hs-tls library](https://github.com/vincenthz/hs-tls/issues/152) had recently, which pandoc depends on to download images etc. over https.

Most likely, using a more recent [pandoc nightly](https://github.com/pandoc-extras/pandoc-nightly) (or compiling from source) and making sure it uses [tls](https://www.stackage.org/package/tls) >= 1.3.9 will fix your problem.

(cross-post from https://stackoverflow.com/a/44148677/214446)

**Comment by bobcanthelpyou** [comment]
It could be reproduced with Pandoc when using script tags (or other tags containing external files) within the markdown file, e.g.:
```
<script src="https://www.google.com/jsapi?callback=displayChartComboChartIDccd77092e5bf"></script>
```
and run
```
$ pandoc test.md --to html --output test.html --self-contained
pandoc: Could not fetch https://www.google.com/jsapi?callback=displayChartComboChartIDccd77092e5bf
TlsExceptionHostPort (HandshakeFailed Error_EOF) "www.google.com" 443
```

**Comment by bobcanthelpyou** [comment]
With a nightly build of Pandoc the problem is gone, is it possible to provide one of the latest stable releases of Pandoc with updated lib dependencies?

**Comment by mb21** [comment]
AFAIK jgm plans to release pandoc 2.0 in the next couple of months...
