### ISSUE TITLE
PDF output fails for alphabetically enumerated lists with more than 26 items

### ISSUE THREAD

**Issue by mikeplus64** [jgm/pandoc#3939]
e.g. with (27 "hellos")

```{.md}
a. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
#. hello
```

Using pandoc 1.17.2, `pandoc test.md -o test.pdf` outputs:

```
! LaTeX Error: Counter too large.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.109   h

pandoc: Error producing PDF
```

I'd expect it to go a..z, aa..zz, aaa..zzz etc.

**Comment by mikeplus64** [comment]
https://tex.stackexchange.com/questions/52599/error-counter-too-large-with-alphcntr-and-cntr26 (where someone has the issue with plain-old LaTeX) recommends using https://ctan.org/pkg/alphalph instead of `\alph`

**Comment by jgm** [comment]
I like to minimize dependencies on external LateX packages,
so I'd rather not depend on alphalph.  I would suggest
simply not using alphabetical enumeration for long lists!

+++ Mike Ledger [Sep 27 17 23:19 ]:
