### ISSUE TITLE
pandoc Error 43 on one computer but not the other

### ISSUE THREAD

**Issue by ocjr** [jgm/pandoc#3944]
I am not sure what to include here as the code works fine on my work Dell Laptop running Windows 10 (1607) but returns an error 43 when I run it on my personal surface running windows 10 (1703). 

The basics I guess, I am running an RMarkdown file that is creating a pdf. When I run it at work, it works fine, when I open the project at home and run the exact same files I get an error 43. Below you find the header to the markdown file and the error. I am not sure what I am missing I have loaded and reloaded every package I can think of and I am totally lost as to what is causing the issue. 

RMarkdown File Header: 

title: "Orientation Presenter Report: Finances"
author: "Joe O'Connell"
date: "2017-9-11 v1"
output:
    pdf_document:
      latex_engine: xelatex
mainfont: Arial
fontsize: 12pt
header-includes: \usepackage{fontspec}
geometry: margin=.5in
classoption: landscape

Error: 
`output file: O_2017_Finances_Presenter_Report.knit.md

"C:/PROGRA~2/Pandoc/pandoc" +RTS -K512m -RTS O_2017_Finances_Presenter_Report.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output O_2017_Finances_Presenter_Report_TEMP.pdf --template "C:\R\R-3.4.1\library\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine xelatex --variable graphics=yes 
! Undefined control sequence.
<argument> \LaTeX3 error: 
                           Erroneous variable \c__fontspec_shape_n_n_tl used!
l.3806 \emfontdeclare{ \emshape, \eminnershape }

pandoc.exe: Error producing PDF
Error: pandoc document conversion failed with error 43
In addition: Warning message:
running command '"C:/PROGRA~2/Pandoc/pandoc" +RTS -K512m -RTS O_2017_Finances_Presenter_Report.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output O_2017_Finances_Presenter_Report_TEMP.pdf --template "C:\R\R-3.4.1\library\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine xelatex --variable graphics=yes' had status 43`

**Comment by jgm** [comment]
Do you have the same version of pandoc installed on each machine?

**Comment by ocjr** [comment]
How would I find that out? I downloaded the most recent version on the machine that is having issues as I hoped that would fix it but the working machine, I only installed the rmarkdown package, never pandoc individually.

**Comment by jgm** [comment]
Looks like 1.17.0.2 from the log output.

I suspect this may be a bug in the fontspec package in your latex distribution. See
https://sourceforge.net/p/miktex/discussion/33790/thread/fcf98fa1/

**Comment by ocjr** [comment]
That's it! thank you for the help.
