### ISSUE TITLE
binomial symbol rendered incorrectly in mathml

### ISSUE THREAD

**Issue by graboluk** [jgm/pandoc#3948]
pandoc version 1.17.2 (debian stable)

input file:
```
$\binom{9}{2}$
\
${9\choose 2}$
```
command:
`pandoc -f markdown binomial.txt --mathml -s -o binomial.html`

output viewed in firefox attached (it looks like (\frac{9}{2}) )
![screenshot](https://user-images.githubusercontent.com/14864635/31054454-ccb76d92-a6aa-11e7-83ab-88f8d6efbbbe.png)

**Comment by jgm** [comment]
Yes, confirmed that it looks that way in Firefox with latest
dev version pandoc/texmath output as well.

Here's the MathML:

<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="true" form="prefix">(</mo><mstyle linethickness="0"><mfrac><mn>9</mn><mn>2</mn></mfrac></mstyle><mo stretchy="true" form="postfix">)</mo></mrow><annotation encoding="application/x-tex">\binom{9}{2}</annotation></semantics></math>

Note that the 'mstyle linethickness="0"' is being ignored.

At http://www.axeleratio.com/gems/MathML/binomial_coefficient_markup.htm
they recommend putting linethickness="0" directly on the
mfrac element.

+++ graboluk [Oct 01 17 05:17 ]:

**Comment by jgm** [comment]
I can confirm that putting the linethickness="0" attribute
directly on the mfrac element, instead of in a surrounding
mstyle, fixes the problem.

This shouldn't be hard to fix (in jgm/texmath).


+++ graboluk [Oct 01 17 05:17 ]:
