### ISSUE TITLE
docx export: $body not used, whole content replaced

### ISSUE THREAD

**Issue by phmarek** [jgm/pandoc#3949]
Hi,

I'm using pandoc 1.19.2.1.0-1 and I'd like to use document templates that contain some header pages (including a tag for an autogenerated TOC). So I inserted the various tags in such a document (`$title`, `$subtitle`, `$body`, etc.), and passed that in via `--reference-docx`.

While the styles are being used, the complete contents are replaced, so the header pages are missing.

Thank you!

**Comment by phmarek** [comment]
Also, I'd like to fill a table in there from some versioning information; I thought of converting the git log to YAML, and then use `$for()$` ... `$endfor$` from pandoc to format that into the document. 

Can that be included in the template too, or would I have to generate that via the input file somehow?

**Comment by mb21** [comment]
Not sure what exactly you mean by "inser tags ... and pass that in via --reference-dox".

Anyway, please ask questions on pandoc-discuss, this issue tracker is for bugs and new features.

**Comment by jgm** [comment]
You seem to be assuming that the reference-docx will work
like a pandoc template (with substitution of variables,
etc.).

It does not.  As the manual says, the only things that carry
over from the reference docx are the styles.
