### ISSUE TITLE
please implement "#+options:  toc:t \n:t" in orgmode input format

### ISSUE THREAD

**Issue by zaxebo1** [jgm/pandoc#3950]
**please implement "#+options:  toc:t \n:t" in orgmode reader**

EXAMPLE: (the source file a1.org is as following)
bash$  cat a1.org
> #+options:  toc:t \n:t
>
> **Title1
>
>
> aaa
> bbb
> ccc
> ddd

Now, we generate output format using emacs orgmode as following:
bash$ emacs a1.org --batch -f org-odt-export-to-odt --kill
now open the emacs org-mode's generated file a1.odt, then it will show the lines as:
>Table of Contents
>1. Hi1
>
>
> aaa
> bbb
> ccc
> ddd

Now, we generate output format using pandoc's orgmode input as following:
bash$ pandoc a1.org -t odt -o a2.odt
now, opening the pandoc generated file "a2.odt" document shows the lines as following 
>  aaa bbb ccc ddd

=================

HENCE,
Currently pandoc does not implement many of the options 

1)  **toc:t** = means it will generate "Table of content"

2) **\n:t** = by default "\n:nil" . 
But if you explicitly put it as "\n:t"    , then every hard carraige return in the document will be outputted as new line in the output document.

My request is to please implement various options esp. "toc:t \n:t"

**NOTE: more detail regarding these and other export options are at http://orgmode.org/manual/Export-settings.html**

**Comment by tarleb** [comment]
This is a good suggestion. Implementing support for `\n` should be relatively simple. However, supporting `toc` is rather involved and would require some bigger architectural changes in pandoc. For the time being, you can use `--toc` to make pandoc generate a table of contents.

**Comment by tarleb** [comment]
Support for the `\n` option has been added, so I've closed this for now. I'm keeping the `toc` issue in mind though.

**Comment by zaxebo1** [comment]
+ 100 thanks
