### ISSUE TITLE
KaTeX can now support the align environment

### ISSUE THREAD

**Issue by ThermalSpan** [jgm/pandoc#3953]
It would appear that the align environment is not supported when using KaTeX, though it is supported with MathJax. KaTeX added support for the align environment with https://github.com/Khan/KaTeX/issues/61

This issue seems similar to #3816 but I could not find an exact duplicate. 

```
russell$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

russell$ pandoc -v
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/russell/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

russell$ cat align.md
# Test align env

\begin{align}
    x &= y^2 \\
    x &= z + 2^t
\end{align}

russell$ pandoc align.md -o align-mathjax.html --mathjax

russell$ cat align-mathjax.html
<h1 id="test-align-env">Test align env</h1>
<span class="math display">\[\begin{align}
    x &amp;= y^2 \\
    x &amp;= z + 2^t
\end{align}\]</span>

russell$ pandoc align.md -o align-katex.html --katex

russell$ cat align-katex.html
<h1 id="test-align-env">Test align env</h1>
```

**Comment by jgm** [comment]
Can you give me an example of an HTML file that has an align environment and works with KaTeX?  I wasn't able to get it working in my tests.

**Comment by ThermalSpan** [comment]
My apologies for not pushing this a bit further before filing an issue.  

Upon further investigation I realize that the KaTeX issue I linked actually covers the 'aligned' environment. It would seem that align / align* are unlikely to be supported in KaTeX, but the aligned environment _is_ now supported. This can also be seen per https://khan.github.io/KaTeX/function-support.html

For posterity, the important distinction is that aligned is used in math mode, where as align / align* is not. It is also worth noting that you can achieve the effect of line numbers with an additional column in an aligned environment. For example:

$$
\begin{aligned}
x &= y^2 & (1)\\
&= z^2 + 2 & (2)
\end{aligned}
$$

Aligned does work with the '--katex' flag. I think this issue can be closed.

**Comment by jgm** [comment]
Closing. At least this was a good occasion for me to make some latex related improvements.
