### ISSUE TITLE
markdown parser is bad at recognizing intuitive indentation of nested lists

### ISSUE THREAD

**Issue by JonasT** [jgm/pandoc#3957]
## Problem description
The pandoc markdown parser is bad at recognizing the intuitively given indentation of nested lists.

## Example source
```text
Scoping in tethercode is done using a lexical scope at compile time. The
following rules is how an identifier can be resolved (which are checked
in that order):

- The identifier is one of the following:

  - the right-hand side of a member access operator, or
  - the name of a keyword argument in a function definition or
    function call, or
  - the name of a newly defined reference in a let statement, function
    definition or class definition
```
## Example rendered by GitHub

Scoping in tethercode is done using a lexical scope at compile time. The
following rules is how an identifier can be resolved (which are checked
in that order):

- The identifier is one of the following:

  - the right-hand side of a member access operator, or
  - the name of a keyword argument in a function definition or
    function call, or
  - the name of a newly defined reference in a let statement, function
    definition or class definition

---
## Example rendered by pandoc (HTML as seen in browser)

![pandocrender](https://user-images.githubusercontent.com/1573352/31301702-53a10b60-aafc-11e7-96a7-12d0f2674484.png)
---
## Conclusion
Unless pandoc is one of those tools following an exact standard like CommonMark that forbids treating this problematic case better, I highly recommend picking a more intuitive interpretation here that follows more closely what the users see when looking at the raw markdown.

From the markdown source it should be quite obvious the followup items are supposed to indented as sub items, so I propose this is what pandoc should do in this case (as GitHub does).

Affected pandoc version:
```
[jonas@falcon ~]$ pandoc --version
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1, highlighting-kate 0.6.4
Default user data directory: /home/jonas/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
[jonas@falcon ~]$
```

**Comment by jgm** [comment]
Pandoc 1.19.1 follows the "four-space rule" for list indentation (see the manual).

In the dev version of pandoc we have adjusted the rules to work more like CommonMark.

Now your sample renders this way:

<img width="656" alt="screen shot 2017-10-06 at 5 35 22 pm" src="https://user-images.githubusercontent.com/3044/31303112-c3f16832-aabc-11e7-8433-f7122c0d2cb4.png">

**Comment by JonasT** [comment]
That sounds nice <3 thanks, very much looking forward to the nex trelease then!
