### ISSUE TITLE
Pandoc erroneously elides quotes in LaTeX -> epub conversion

### ISSUE THREAD

**Issue by bitemyapp** [jgm/pandoc#3958]
pandoc `fdaae5aec5bf31ae2f4fa1612e4263fb91ded4c0` (this is `HEAD` at time of writing)

Repro: https://github.com/bitemyapp/pandoc-quotes-issue - run `make`, observe the missing quotes in the HTML of the epub.

This:

```tex
\begin{enumerate}
\item \texttt{func "Hello World"}
\item \texttt{func "Hello" "World"}
\item \texttt{func [1, 2, 3] "a, b, c"}
\item \texttt{func ["Hello", "World"]}
\end{enumerate}
```

turns into:

```html
<ol>
<li><p><code>func Hello World</code></p></li>
<li><p><code>func Hello World</code></p></li>
<li><p><code>func [1, 2, 3] a, b, c</code></p></li>
<li><p><code>func [Hello, World]</code></p></li>
</ol>
```

It should be:

```html
<ol>
<li><p><code>func "Hello World"</code></p></li>
<li><p><code>func "Hello" "World"</code></p></li>
<li><p><code>func [1, 2, 3] a, b, c</code></p></li>
<li><p><code>func ["Hello", "World"]</code></p></li>
</ol>
```

**Comment by bitemyapp** [comment]
Before you say, "backslash escape the double quotes", consider that these do _not_ get elided with any LaTeX -> PDF renderer I've used and they're semantically `code` blocks in the HTML which fits my intent. Any content in a code or verbatim block should be sacrosanct.

**Comment by jgm** [comment]
Definitely looks like a bug.  Simpler case:
```
% pandoc -t native -f latex
\texttt{"hi"}
[Para [Code ("",[],[]) "hi"]]
```
This should yield
```
[Para [Code ("",[],[]) "\"hi\""]]
```
