### ISSUE TITLE
Raw HTML <aside> breaks paragraph markup

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#3959]
`pandoc -t html5`

This:
```markdown
---
title: Test CriticMarkup with pandoc
...

Cum sociis natoque <del>penatibus et magnis</del><aside>aside with quite a bit more text here…</aside> dis parturient montes, nascetur ridiculus mus.
```

Generates:
```html
Cum sociis natoque <del>penatibus et magnis</del>
<aside>
aside with quite a bit more text here…
</aside>
<p>dis parturient montes, nascetur ridiculus mus.</p>
```

With the raw HTML &lt;aside&gt; element (which is a block element by default), the first part of the sentence is not wrapped in &lt;p&gt;. Replace &lt;aside&gt; with inline element like &lt;em&gt; and all works. Block elements can contain other blocks, not sure why the paragraph is broken here?

**Comment by jgm** [comment]
>   With the raw HTML <aside> element (which is a block element by
>   default), the first part of the sentence is not wrapped in <p>. Replace
>   <aside> with inline element like <em> and all works. Block elements can
>   contain other blocks, not sure why the paragraph is broken here?

Pandoc paragraphs can't contain other blocks; they only
contain inline elements.  So there's no way for a paragraph
to contain an "aside."

As far as I can see, this is the same in HTML5:  aside is
not phrasing content and can't be contained in a p element.

**Comment by iandol** [comment]
OK, I was aiming to use aside for its "correct" semantic meaning but presenting it as an inline element (HTML content being block or inline is modifiable by CSS)... Workaround is using less semantically correct spans...

I was curious why `Cum sociis natoque...` was not wrapped in a P but `dis parturient montes...` was?

**Comment by jgm** [comment]
+++ Ian [Oct 09 17 00:13 ]:
>   I was curious why Cum sociis natoque... was not wrapped in a P but dis
>   parturient montes... was?

Because no blank line following...
so it's parsed as a Plain block rather than Para.

**Comment by iandol** [comment]
OK, thanks John!
