### ISSUE TITLE
en-dash and smart-quotes for docx output

### ISSUE THREAD

**Issue by anntzer** [jgm/pandoc#3960]
It appears that pandoc does not output either en-dashes or smart quotes for docx output.  This can be easily checked with
```
echo 'a -- b "c"' | pandoc -tdocx -ofoo.docx
```
and opening the resulting file.
It is actually not clear to me whether pandoc intends to treat `--` specially at all or it just happens that it passes it through and LaTeX picks it up (for example, html output just keeps then `--`), but pandoc definitely appears to handle quotes internally (as can be checked, again, on html output).
Support for at least smart quotes in docx output would thus be greatly appreciated.  Thanks!

(pandoc 1.19.2.1)

**Comment by agusmba** [comment]
Hi @anntzer,

Indeed it is not working correctly in 1.19.2.1, but I just tested it in a more recent devel version and it works.

You can wait until v2.0 is released or you can grab a nightly version from [here](https://github.com/pandoc-extras/pandoc-nightly/releases)

**Comment by tarleb** [comment]
The current (v1.19) behavior is that smart quotes mist be enabled explicitly via the `--smart` command line parameter. This was changed in the dev version: smart quotes are now a markup extension which is enabled for pandoc markdown by default.

**Comment by agusmba** [comment]
Right @tarleb I've been using the dev version lately a lot and I forgot about `-S `.

**Comment by anntzer** [comment]
thanks.
