### ISSUE TITLE
[Out of Topic] Pandoc + Carbon?

### ISSUE THREAD

**Issue by sayzlim** [jgm/pandoc#3964]
Hi Damien,

I’m with [Carbon](https://carbonads.net/) from BuySellAds. I apologize for creating an issue that is out of the scope in the issue trackers. May I know whether you’re keen in generating revenue from displaying an ad on the project site?

You have 100% control over the design and the placement for the ad. Some of our existing partners are **lodash.com/docs/, flask.pocoo.org/docs/, and laravel.com/docs/**

Have you considered ad/sponsorship as one of the options to generate revenue for the project funding?

**Comment by jgm** [comment]
It's completely inappropriate to use GitHub issues for a spam sales email like this.
Please do not do this in the future, or I will report this to GitHub as inappropriate use.
