### ISSUE TITLE
Header identifiers in chapters for Context output

### ISSUE THREAD

**Issue by PeterDavidson** [jgm/pandoc#3968]
I'm not sure if it is intended behaviour, but when using the Context writer and 
--top-level-division=chapter, no header identifiers are applied to chapters. This is not the case when the top level identifier is section, and does not seem to apply to other writers (such as latex).

If we have test.md
```
# Chapter

## Section

### Subsection

# Another Chapter {#another}
```
and run

```
pandoc --top-level-division=chapter -t context -o temp.tex test.md
```

we get

```
\chapter{Chapter}
\section[section]{Section}

\subsection[subsection]{Subsection}

\chapter{Another Chapter}

```

but

```
pandoc --top-level-division=chapter -t latex -o temp.tex test.md
```
gives

```
\chapter{Chapter}\label{chapter}

\section{Section}\label{section}

\subsection{Subsection}\label{subsection}

\chapter{Another Chapter}\label{another}
```

and 

```
pandoc --top-level-division=section -t context -o temp.tex test.md
```
gives
```
\section[chapter]{Chapter}

\subsection[section]{Section}

\subsubsection[subsection]{Subsection}

\section[another]{Another Chapter}
```

To make appendices work properly I need to have chapters as the top level division, but the lack of labels/identifiers is causing problems. Can this be fixed?

**Comment by jgm** [comment]
It's just an oversight.  I'll fix it.
