### ISSUE TITLE
RestructuredText -> PDF tables not showing up in list of tables

### ISSUE THREAD

**Issue by gappleto97** [jgm/pandoc#3972]
```bash
$ uname -a
Linux gappleto-Carbon 4.13.5-200.fc26.x86_64 #1 SMP Thu Oct 5 16:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ pandoc --version
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1, highlighting-kate 0.6.4
```

I'm using the `make pdf` command in https://github.com/p2p-today/protocol. The part you care about is `pandoc -o README.pdf README.rst -V lot --latex-engine=xelatex`

**Comment by gappleto97** [comment]
I also tried it with the `.. table::` directive, but it ignored that entirely

**Comment by jgm** [comment]
With the dev version,
```
pandoc -o t.pdf test/tables.rst --pdf-engine=xelatex -V lot
```
gave me a list of tables.  The released version did not.  I'm not sure why, but it seems this is fixed now.

Try a binary from pandoc-nightlies?  Note that you'll need `--pdf-engine` instead of `--latex-engine`.

**Comment by gappleto97** [comment]
[This version](https://github.com/pandoc-extras/pandoc-nightly/releases/tag/hash-eb508c13) does not include them.

**Comment by gappleto97** [comment]
[Output](https://github.com/jgm/pandoc/files/1386025/README.pdf)

**Comment by jgm** [comment]
Only tables with captions are included in LaTeX list of
tables.  Do your tables have captions?

**Comment by gappleto97** [comment]
Thats not possible with pandoc, because it doesn't register the `.. table::` directive. You have to just put a plain one.

**Comment by jgm** [comment]
The dev version supports the table:: directive and allows
captions.

+++ Gabe Appleton [Oct 15 17 21:34 ]:
