### ISSUE TITLE
memoir documentclass ignoring geometry when including an image

### ISSUE THREAD

**Issue by ubitux** [jgm/pandoc#3975]
Steps to reproduce:

- create a small 100x100 image: `convert -size 100x100 canvas:khaki img.png` (`convert` is from the `ImageMagick` project but you can use any other tool)
- create a markdown document with that image: `echo '![Hello World](img.png)' > bug.mkd`
- try to generate a 5x8 inches memoir from this: `pandoc -V geometry:paperwidth=5in -V geometry:paperheight=8in -V documentclass=memoir bug.mkd -o bug.pdf`

Opening `bug.pdf` will show a document much larger than expected (even though the image is pretty small).

This is not reproducible with **text only** or `documentclass=book`, revealing that something is probably wrong in the handling of dimensions in the memoir documentclass when inserting images.

```
% pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.2, texmath 0.9.4.4, skylighting 0.1.1.5
Default user data directory: /home/ux/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment]
It's always helpful to post the LaTeX pandoc generates and what you expected it to generate (via `pandoc bug.mkd -o bug.tex`)...

**Comment by ubitux** [comment]
The generated code doesn't change between `-V documentclass=memoir` and `-V documentclass=memoir`; but the overall template is probably different. My guess is that `memoir` doesn't support to be mixed with the `geometry` package and we should be using other variables such as `stockwidth` and `stockheight`, but I wasn't able to make it work out.

**Comment by ubitux** [comment]
I found a workaround: `-V header-includes="\\setstocksize{8in}{5in}"`. I don't know if it's a safe fix, but for now it seems to work properly.

**Comment by jgm** [comment]
+++ Clément Bœsch [Oct 16 17 09:12 ]:
>   This is not reproducible with text only or documentclass=book,
>   revealing that something is probably wrong in the handling of
>   dimensions in the memoir documentclass when inserting images.

So, this doesn't sound like a pandoc bug.  Perhaps it is a
memoir bug, but I think the real problem is that memoir
has its own built-in ways to specify document dimensions
(see the memoir manual).

I don't think using geometry with memoir is recommended.

**Comment by ubitux** [comment]
> I think the real problem is that memoir has its own built-in ways to specify document dimensions (see the memoir manual).

Yes that's how I found out about `\setstocksize`, but it's not documented in the pandoc documentation where `memoir` is supposed to be supported.

> I don't think using geometry with memoir is recommended.

Well, isn't it the only way to specify dimensions in pandoc? What else am I supposed to use? BTW, the memoir documentation says that you can use it, and I actually do need both `geometry` and the stock size to be set (to the same values) to get a proper output.

**Comment by jgm** [comment]
+++ Clément Bœsch [Oct 16 17 09:18 ]:
>     I think the real problem is that memoir has its own built-in ways to
>     specify document dimensions (see the memoir manual).
>
>   Yes that's how I found out about \setstocksize, but it's not documented
>   in the pandoc documentation where memoir is supposed to be supported.

It's not our job to reproduce documentation for the memoir class.

>     I don't think using geometry with memoir is recommended.
>
>   Well, isn't it the only way to specify dimensions in pandoc? What else
>   am I supposed to use? BTW, the memoir documentation says that you can
>   use it, and I actually do need both geometry and the stock size to be
>   set (to the same values) to get a proper output.

OK, that's good to know.  Still:  if we try to include in
the pandoc documentation instructions for correctly using
all the various latex packages and documentclasses one might
want to use, it would quickly become hundreds of pages long.

My policy is this:  if you use pandoc defaults (normal
documentclasses), things will work as documented. If you
use a special documentclass, then it's your responsibility
to figure out what it requires.

**Comment by ubitux** [comment]
> My policy is this: if you use pandoc defaults (normal documentclasses), things will work as documented. If you use a special documentclass, then it's your responsibility to figure out what it requires.

But `memoir` is in the "normal" documentclasses that pandoc documents.

**Comment by jgm** [comment]
+++ Clément Bœsch [Oct 16 17 16:50 ]:
>     My policy is this: if you use pandoc defaults (normal
>     documentclasses), things will work as documented. If you use a
>     special documentclass, then it's your responsibility to figure out
>     what it requires.
>
>   But memoir is in the "normal" documentclasses that pandoc documents.

It's mentioned in a couple places, yes.  But the fact is
that there are many, many tricky issues getting memoir to
work with various other packages.  I think trying to
document them all in pandoc's documentation is asking too
much.  People who know enough to specify a memoir
documentclass should also know how to search for the
relevant documentation.
