### ISSUE TITLE
parsing bug in raw html from markdown to html

### ISSUE THREAD

**Issue by haozhu233** [jgm/pandoc#3989]
Say I have a markdown file mixed with some raw HTML and markdown text

test.md
```
<span data-toggle="tooltip" data-placement="right" data-html="true" 
title="1st line of text <br> 2nd line of text">
Hover over me
</span>
...
```
(I'm copying the contents from https://www.bootply.com/83099)

Those html tags <> in the title attribute create some bugs when I tried to convert this markdown file to html using
`pandoc -f markdown -t html test.md`
I got 
```
<p><span data-toggle="tooltip" data-placement="right" data-html="true" 
title="1st line of text &lt;br&gt; 2nd line of text"> 2nd line of text&quot;&gt; Hover over me </span></p>
```

My pandoc version is 1.19.2.1. Thank you!

**Comment by mb21** [comment]
HTML usually is supposed to have the `<` encoded as `&lt;`, which most HTML authors consistently do.  Surprisingly, however, this actually seems to be valid HTML5. I tried the following in https://validator.w3.org

```
<!DOCTYPE html>
<html>
<head><title>foo</title></head>
<body>
<span data-toggle="tooltip" data-placement="right" data-html="true" 
title="1st line of text <br> 2nd line of text">
Hover over me
</span>
</body>
</html>
```

**Comment by haozhu233** [comment]
The point of this HTML snippet is to create a two-row tooltip with twitter bootstrap. I guess the question boils down to whether contents inside a pair of quotes need to be escaped.

**Comment by jgm** [comment]
Pandoc can parse the HTML correctly, as you'll see if you do
`pandoc -f html`.  The problem is that the Markdown reader
tries to guess where the HTML tag ends before passing this
off to the HTML reader for parsing.  I think we can fix this
easily by passing in the whole input...TagSoup's parser is
lazy so I don't think this will affect performance, but we'd
have to check.

+++ Hao Zhu [Oct 23 17 13:22 ]:

**Comment by haozhu233** [comment]
@mb21 @jgm Awesome! Thank you both so much for your quick response!

**Comment by jgm** [comment]
Turns out we didn't completely fix this before.
I've updated the test so it fails again.
