### ISSUE TITLE
demo to generate README.pdf 

### ISSUE THREAD

**Issue by mattvend** [jgm/pandoc#3990]
It would be nice if it would be possible to add in the demos example page https://pandoc.org/demos.html the command to generate https://pandoc.org/README.pdf
Otherwise pandoc is a very nice piece of software, great work !

**Comment by mb21** [comment]
Please ask questions like this on the pandoc-discuss mailing list, this is for tracking bugs/features.

What you're looking for is probably https://github.com/jgm/pandoc-website/blob/master/Makefile#L88
