### ISSUE TITLE
Pandoc does not extract cover from epub

### ISSUE THREAD

**Issue by dbojan** [jgm/pandoc#3992]
pandoc.EXE 1.19.2.1, windows 10

command line:
pandoc.exe" "C:\tmp\1632.epub" --extract-media="1632_files" -o "C:\tmp\1632.markdown"
pandoc: extracting 1632_files\067157849901.jpg
pandoc: extracting 1632_files\067157849902.jpg

Result: images and text are extracted, but cover image is not extracted.
Expected result: extraction of the cover image.

I downloaded book from http://www.baen.com/1632.html, in epub format.

When I open epub file using 7zip, there is 0671578499_Cover.jpg, and 0671578499_top.htm inside.

This happens with some other epub files too, and also when converting epub to other formats, like docx.
(When using kindlegen, cover image is supported, and added to destination format, although cover.htm is not supported.)

Thank you.

**Comment by jgm** [comment]
I suppose we could add the cover image to the mediabag and
add "cover-image" plus the path to the metadata.

In the content.opf file, the metadata section contains

    <meta name="cover" content="RW_0671578499_Cover" />

and the manifest contains

    <item href="0671578499_Cover.jpg" id="RW_0671578499"
    media-type="image/jpeg" />

So this would not be hard to extract.
