### ISSUE TITLE
Beamer with XeLaTeX doesn’t render UTF-8 character

### ISSUE THREAD

**Issue by paulmenzel** [jgm/pandoc#3999]
pandoc 1.19.2.1

```
% My Titel
% Joey
% 1. 1. 2017

# Titel

## Sample

Here is the offending character.

φ letter phi
```

Built with `pandoc --latex-engine=xelatex -t beamer … -o …` the Greek letter is not part of the presentation.

**Comment by jgm** [comment]
It's a font issue, undoubtedly.  You need to make sure you're using a font that has this glyph.
