### ISSUE TITLE
FB2 writer: unexpected header in section text

### ISSUE THREAD

**Issue by HelpMeWithPandocFB2** [jgm/pandoc#4000]
I'm absolutely at loss what's causing this. I am trying to convert an EPUB book to an FB2 book, but all I'm getting is `unexpected header in section text`. It's a bit frustrating that the output doesn't even give a hint at what line of the source file I should be looking at. I tried using HTML and Markdown as "middle-men", converting to those formats works absolutely fine, converting from them to FB2 causes the same error. Here's how I am calling the program and its exact output:

```bash
$ pandoc test.markdown -o test.fb2
pandoc: unexpected header in section text
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Writers/FB2.hs:367:27 in pandoc-1.19.2.4-KekXs6uvwDPHgiHHH4Vcih:Text.Pandoc.Writers.FB2
```

Here's the book (after I replaced anything matching `[a-zA-Z]+` with `test`, since the book isn't mine and I do not have a permission to publish it): https://gist.github.com/HelpMeWithPandocFB2/847d565d628bafb3201ef7250312706d. Warning: it's almost 1MB. Even though that replacement butchered HTML-tags, I think Markdown syntax should be fine; and yes, it triggers the same error.

Sorry in advance if my wall of text is hard to understand, I'm not a native speaker.

**Comment by jgm** [comment]
I just tried with the dev version of pandoc (soon to be released as 2.0), and it worked fine without the error.  So I believe this problem has been solved.
See changelog under FB writer:

     + Don't fail with an error on interior headers (e.g. in list) (#3750).
      Instead, omit them with an INFO message.

**Comment by mb21** [comment]
What pandoc version are you using?

This seems to be fixed on current master, probably also in the nightly builds. Thus closing this.

**Comment by HelpMeWithPandocFB2** [comment]
I used the dev version, it works perfectly. Thanks for your software!
