### ISSUE TITLE
Image DPI is ignored for HTML output

### ISSUE THREAD

**Issue by JonasT** [jgm/pandoc#4003]
Image DPI appears ignored entirely for the HTML output:
```sh
#!/bin/sh

wget https://www.startpage.com/graphics/no_tm_startpage_retina_logo.png -O ./test.png

convert -units PixelsPerInch test.png -density 300 test.png

echo '# This is a test

Look at this image:

![](test.png)' | pandoc -o ./test1.pdf

echo '# This is a test

Look at this image:

![](test.png)' | pandoc -o ./test1.html

wget https://www.startpage.com/graphics/no_tm_startpage_retina_logo.png -O ./test2.png

convert -units PixelsPerInch test2.png -density 30 test2.png

echo '# This is a test

Look at this image:

![](test2.png)' | pandoc -o ./test2.pdf

echo '# This is a test

Look at this image:

![](test2.png)' | pandoc -o ./test2.html
```
Expected behavior: image has different sizes in test1.html and test2.html as seen in test1.pdf and test2.pdf

Actual behavior: image has same size in both test1.hml and test2.html, but different size in test1.pdf and test2.pdf

Pandoc version:
```
[jonas@falcon ~]$ pandoc --version
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1, highlighting-kate 0.6.4
Default user data directory: /home/jonas/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
[jonas@falcon ~]$
```

I know browser DPI handling is its own box of pandora, but I think this is very bad for output consistency. What I think pandoc should actually do is calculate the expected size of the image to CSS pixels, and for the example of that being 100px insert something like this per default: `calc(100px * 1.0em)`. This would give the expected behavior of adhering both to the basic DPI scaling of the image, and also adjusting to the whole page being scaled.

Why do I think this would be much more sensible? With the PDF/latex backend, regular images will behave similarly: if you change the DPI print size or the scaling of the whole document, the image will adjust accordingly for the given print output. If you don't want that, you currently need to specify e.g. the percentage width with `![](test.png){width=80%}` to e.g. get some always-page-width-sized large screenshot image or something which will also work fine with the HTML output already - so it's not like there aren't other ways to use if one doesn't want dynamic scaling according to DPI & text. And also, I think it would be much more consistent.

PS: I'm not a print person and I don't know that much about DPI, so maybe this is not the best idea on how to solve this. Therefore, feel free to suggest better ideas. However, I think what I suggested with the CSS pixels and 1.0em would already be a huge consistency improvement over the current DPI-ignoring behavior.

**Comment by mb21** [comment]
For the HTML output, pandoc does what all markdown processors do and browsers never look at image dpi metadata. So your proposal would likely confuse a lot of users.

Feel free to discuss your use-case on pandoc-discuss though...

**Comment by JonasT** [comment]
You make it sound like I had a specific, special use case:

Did you ever export a bigger documentation with pandoc to HTML and PDF? It's just so annoying not to get a consistent result even for a super simple text with simple images layout. The image scaling annotations aren't a good alternative because then you need to hardcode image sizes which works badly e.g. for smaller icons and logos since then you'll need to always update it when you replace it - and the width:X% stuff which is independent of the image size doesn't work nicely either because while it gets you consistent results for PDF exports to known formats, it'll go bonkers in a browser where you don't know the aspect ratio beforehand and the scale will be all over the place as a result. Even if there was a scale:0.5 annotation it'd still need me to strip the DPI information to get a consistent result on the PDF backend.

If at all, I'm surprised if I'm actually the first person suggesting this.

> So your proposal would likely confuse a lot of users.

I understand it would be inconsistent with other markdown processors, but most don't export to other formats and therefore have no such need for DPI consistency. Also many are quite frankly bad and super limited and don't even have proper image scaling annotations, so I'm not sure if it's a good thing if you strive for compatibility with them.

If you are too worried about confusing users, make it an optional `--give-me-proper-dpi-behavior` switch. I know I'd be using it for sure if I knew it existed. Alternatively, I suggest you add a switch that ignores the DPI for all backends although I would consider that a much uglier solution..

**Comment by mb21** [comment]
You can also write a pandoc filter to get the exact output you’re looking for.

**Comment by mb21** [comment]
P.S. What pandoc users used to do before there were image dimension attributes, was simply to scale the image to such a resolution that it's right in the browser, then set the dpi metadata using `convert` so that it's scaled right for the LaTeX PDF. Seems like you could still do this?

Alternatively, you could use `wkhtmltopdf` or `weasyprint` to generate the PDF from HTML/CSS (see pandoc's manual). That will give you more consistent output...

**Comment by JonasT** [comment]
Can you explain why you closed this? (since it's not obvious to me)

Your only point against my proposal as new default behavior appears to have been user confusion, but as I suggested in the response comment a switch would solve that.

**Comment by jgm** [comment]
+++ Jonas Thiem [Oct 29 17 00:33 ]:
>   I know browser DPI handling is its own box of pandora, but I think this
>   is very bad for output consistency. What I think pandoc should actually
>   do is calculate the expected size of the image to CSS pixels, and for
>   the example of that being 100px insert something like this per default:
>   calc(100px * 1.0em). This would give the expected behavior of adhering
>   both to the basic DPI scaling of the image, and also adjusting to the
>   whole page being scaled.

Can you give a bit more detail on what you have in mind here?
Is the idea that the img tag should hard-code a style
attribute with a size in CSS pixels, which is calculated
somehow from the actual pixel size of the image and its DPI?
Sample HTML output for a couple of particular cases?

**Comment by jgm** [comment]
Let's reopen this for more discussion.

**Comment by JonasT** [comment]
> Is the idea that the img tag should hard-code a style attribute with a size in CSS pixels, which is calculated somehow from the actual pixel size of the image and its DPI?

Yea that is exactly what I'd like pandoc to do. This should also mean while it's not exactly matching the PDF output in all cases (since CSS pixels themselves might be scaled by the browser for DPI reasons), at least the font-size-to-image-size ratio is gonna be almost exactly the same which is the most important for consistent looks.

> Sample HTML output for a couple of particular cases?

The only reason I didn't give any is because I'm not good with doing correct maths, so I'd probably mess up the DPI calculation. But the end result for a 300px image with a DPI that somehow means that it needs to be scaled 2x to match a default expected screen DPI for a html web browser (I suppose CSS pixels have a default DPI in most browsers which should be possible to find out) should be something like: `<img width=600px>` 

Forget about the `calc` part, I thought that'd be necessary to make it scale up when the user scales with CTRL+plus/minus but it isn't so that's just unnecessary nonsense.

**Comment by jgm** [comment]
If I understand the proposal correctly, then I think I agree with @mb21's assessment.  It would be confusing for users to find that an HTML file produced from the Markdown

    ![my image](image.jpg)

displays differently in a browser than the HTML

    <img src="image.jpg" alt="my image">

would.  That said, I definitely see why you'd like an alternative behavior. And there, I tend to agree with @mb21 that the best solution is a filter that inspects the image's DPI setting and adds attributes to the Image tag.  This would be relatively easy to write, and easy to use.

**Comment by JonasT** [comment]
Why not add a switch then? I can't write filters off the top of my head and I assume I'm not the only one. Unless of course you are quite certain I'm the only person interested in it, in which case I suppose it's fair enough not to add it

**Comment by jgm** [comment]
Without details on the math, I'm still uncertain about the proposal.

As for a switch vs. a filter:  part of the motivation for adding filters was to avoid complicating pandoc with hundreds of special-purposes switches.  If it seems that lots of people would want this, we could consider it -- pandoc-discuss would be the right place to raise that issue.

So I'm going to close this now, but feel free to raise a discussion on pandoc-discuss, and if there is a general clamor for the feature, we can reconsider.

**Comment by jgm** [comment]
+++ Jonas Thiem [Oct 29 17 19:07 ]:
>   Why not add a switch then? I can't write filters off the top of my head
>   and I assume I'm not the only one. Unless of course you are quite
>   certain I'm the only person interested in it, in which case I suppose
>   it's fair enough not to add it

As I said, that's something we'd need to find out about, and
the best way to do that is to open a discussion on
pandoc-discuss. Feel free to do that.
