### ISSUE TITLE
POOR SPEED ON WINDOWS INTALLERS

### ISSUE THREAD

**Issue by NervenCid** [jgm/pandoc#4005]
I tried to install the msi installer, and i have a good internet speed (30 Mbps), the installers downloads at only 3Kbps and stops at 10 MB.

At least upload the installers to github or Google drive

Thanks

**Comment by vyp** [comment]
https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-windows.msi

**Comment by vyp** [comment]
Actually there's been a new release since my last comment: https://github.com/jgm/pandoc/releases/download/2.0/pandoc-2.0-windows.msi

**Comment by NervenCid** [comment]
OK....

I'm downloading right now...

But the speed is 3.4 KB/s it takes long time

![imagen](https://user-images.githubusercontent.com/10704230/32150362-e1a40512-bcdf-11e7-8645-27fab73e6330.png)

**Comment by jgm** [comment]
I think it's not a problem on the server end.  It downloads
almost instantly from my connection...

**Comment by vyp** [comment]
What I meant to point out was that the installer is available on GitHub. So instead of it being a issue with how pandoc installers are distributed, it would be an issue with GitHub, or your connection, or something else.
