### ISSUE TITLE
pandoc-2.0-1-amd64.deb has old pandoc

### ISSUE THREAD

**Issue by nfleisher** [jgm/pandoc#4006]
The .deb archive for Pandoc 2.0 (version pandoc-2.0-1-amd64.deb) appears to have been packaged with the old man page (version 1.19.2, dated Jan 29, 2017).

**Comment by agusmba** [comment]
Not only that, the pandoc and pandoc-citeproc executables have a date from Feb 12 2017, and things that should be fixed in v2.0 are not working.

Maybe the deb package is not really the proper v2.0?

**Comment by agusmba** [comment]
@nfleisher could you change the title to reflect that it's not only the man page which is old?

"pandoc-2.0-1-amd64.deb has old pandoc" ?

**Comment by nfleisher** [comment]
Yes, I see the same Feb 12 2017 dates in the .deb I downloaded. Changed title.

**Comment by jgm** [comment]
Sorry about that.  I'm looking into it now.

**Comment by jgm** [comment]
I've uploaded a new version of the deb installer, verified to contain the right binary and man page!
