### ISSUE TITLE
Multi-line fenced code blocks fail in numbered lists

### ISSUE THREAD

**Issue by suhlig** [jgm/pandoc#4011]
Example document:

1. This does not work as expected:

    \`\`\`
    $ some command

    $ some other command
    \`\`\`

1. This, however, does work fine (using dots in place of spaces in order to highlight the difference):

........$ some command
........
........$ some other command

The generated HTML for both examples is:

```html
<ol type="1">
<li><p>This does not work:</p>
<p>``` $ some command</p>
<p>$ some other command ```</p></li>
<li><p>This, however, does work fine:</p>
<pre><code> $ some command

 $ some other command</code></pre></li>
</ol>
```

In the first case, the \`\`\` made it into the HTML, which should have triggered the `<pre>` instead, as in the second example.

Reproduce the bug with

```
$ pandoc --output /tmp/bug.html pandoc-fenced-code-blocks-indented.markdown
```

This bug was seen with

```
pandoc 2.0.0.1
Compiled with pandoc-types 1.17.2, texmath 0.9.4.4, skylighting 0.4.2
```

**Comment by jgm** [comment]
You don't put your code sample in a code block, so I can't tell exactly what it is.  But I couldn't reproduce the problem:
`````
1.  This does not work as expected:

    ```
    $ some command

    $ some other command
    ```
<ol type="1">
<li><p>This does not work as expected:</p>
<pre><code>$ some command

$ some other command</code></pre></li>
</ol>
`````
This is with pandoc 2.0.0.1.

Note:   the content under the list item must be indented to the column containing the first text after the `1.` -- in my example, you need 4 spaces indent.  You may not have indented correctly.

**Comment by suhlig** [comment]
Thanks. That explains it. The key difference seems to be that the 'T' in 'This' needs to be aligned with the code block. In the non-working example, I had only one space between '1.' and 'This', which put 'T' into column three, whereas the code block started in column 4.

Is that the expected behavior? I find it a bit surprising, but it seems reasonable.

For reference, here is the difference in a [gist](https://gist.github.com/suhlig/89e1cbb183eacb33af6070669cc0eb3e).

```
$ curl https://gist.githubusercontent.com/suhlig/89e1cbb183eacb33af6070669cc0eb3e/raw/508850482da455888750378eae4f2bacb908692a/gistfile1.txt | pandoc
<ol type="1">
<li><p>This does not work:</p>
<p>``` $ some command</p>
<p>$ some other command ```</p></li>
<li><p>This, however, does work fine (note the alignment of ‘This’ with the block using an extra space):</p>
<pre><code>$ some command

$ some other command</code></pre></li>
</ol>
```

**Comment by jgm** [comment]
For convenience, here's the "not work" case:
```
1. This does not work:

    ```
    $ some command

    $ some other command
    ```
```

In pandoc, currently, fenced code blocks need to start at the left margin, or, if they're in a list item, at the edge of the content of the list item.  In your case the fence is indented, so we don't get a code block.

CommonMark behaves differently, and we might think about changing the behavior to align with CommonMark.  See http://spec.commonmark.org/0.28/#fenced-code-blocks

>  If the leading code fence is indented N spaces, then up to N spaces of indentation are removed from each line of the content (if present). (If a content line is not indented, it is preserved unchanged. If it is indented less than N spaces, all of the indentation is removed.)

**Comment by suhlig** [comment]
Makes sense. Thank you very much!
