### ISSUE TITLE
Output units in millimetres rather than centimetres

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#4012]
Pandoc 2 converts any use of millimetres to centimetres; it would be cleaner and more idiomatic to reverse this. In my experience, millimetres are more common (though not universal) when metric is used in book design, since they mostly eliminate the need for decimals; A4 paper, for example, is usually described as 297 × 210 mm. Avoidance of decimals is desirable particularly because the separator varies by language (Pandoc does not recognize '29,7 cm').

Example (version 2.0.0.1):

```shell
pandoc << EOT
![image]

[image]: http://example.com/image.jpg {height=35mm}
EOT
```

Result:

```html
<figure>
<img src="http://example.com/image.jpg" alt="image" style="height:3.5cm" /><figcaption>image</figcaption>
</figure>
```

**Comment by jgm** [comment]
Sounds reasonable to me!

**Comment by jgm** [comment]
In Text.Pandoc.ImageSize, we have:
```
data Dimension = Pixel Integer
               | Centimeter Double
               | Inch Double
               | Percent Double
               | Em Double
```
No Millimeter.  That's why mm is converted.

@mb21 - can you recall whether there was a reason why we don't have Millimeter?

**Comment by mb21** [comment]
If I recall correctly, the reason was simply that in my personal experience `cm` felt more common. But I'm not in the printing business... and I don't mind either way. Maybe ask around on pandoc-discuss?

**Comment by jgm** [comment]
I've pushed a commit that leaves 'mm' alone.
It doesn't convert 'cm' to 'mm' ; that seems a bit intrusive.

**Comment by adunning** [comment]
Thank you!
