### ISSUE TITLE
Columns: Release note example issue

### ISSUE THREAD

**Issue by henryiii** [jgm/pandoc#4015]
The release notes incorrectly show how to add columns to a document.
Pandoc 2.0.0.1, via Brew on macOS.

Code:

```md
---
title: Release note columns
author: Henry Schreiner
date: October 31, 2017
---

# Slide 1

<!--- Comment to force correct slide level --->

## Block 1

- Stuff

## Block 2

- Stuff

# Slide 5: indented text like release notes

<div class="columns">
  <div class="column" width="40%">
    contents `bla bla`
  </div>
  <div class="column" width="60%">
    contents $\int x^2 dx$
  </div>
</div>

# Slide 5: unindented text

<div class="columns">
<div class="column" width="40%">
contents `bla bla`
</div>
<div class="column" width="60%">
contents $\int x^2 dx$
</div>
</div>

```

Compile:

```bash
pandoc -tbeamer example.md -oexample.pdf
```

Output: [relnote.pdf](https://github.com/jgm/pandoc/files/1431541/relnote.pdf)

As you can see, the `<div>` lines do not cause pandoc to expect an indent, making the indented versions preformatted, since they are at a 4  line indent from the previous non-div lines.

Suggested solution: Corrected documentation or an expected indent after div.

**Comment by jgm** [comment]
Thanks.  I'll redo with fenced divs, and also add this to the manual.

**Comment by henryiii** [comment]
Better! I hadn't seen that sort of divs yet. Thanks.
