### ISSUE TITLE
Author metadata field does not work with jats output format

### ISSUE THREAD

**Issue by pdlug** [jgm/pandoc#4020]
Using pandoc 2.0.0.1 with markdown input and jats output the author metadata field is not present when the template is called. Example with a barebones template below.

**test.md**

```markdown
---
author: Somebody
---
# Test Article
```

**test.jats**

```
<author>$author$</author>
```

Running this command:

```bash
pandoc test.md --template test.jats -s -f markdown -t jats
```

Results in no output for the author variable:

```bash
<author></author>
```

If I switch the output format to anything else (ex: latex) and run it with the same template:

```bash
pandoc test.md --template test.jats -s -f markdown -t latex
```

The output contains the value of the author variable properly:

```bash
<author>Somebody</author>
```

**Comment by jgm** [comment]
Take a look at the default jats template (pandoc -D jats).

You'll see that it assumes that the author metadata is
structured, and you should do the same in a custom template.
So $author$ won't get you anything, but

$for(author)$
$author.surname$
$endfor$

will list the surnames of the authors.

+++ Paul Dlug [Oct 31 17 23:45 ]:

**Comment by pdlug** [comment]
The problem exists with the default jats template which is why I replicated it in a smaller standalone template to demonstrate it exists regardless of the template used with the jats output. I've tried using structured authors as well but that doesn't change things. If you switch the output format to "latex" but specify a copy of the default jats template you can see it does output the authors. It just doesn't work if the output format is "jats".

**Comment by jgm** [comment]
Good, I see the issue now.

**Comment by jgm** [comment]
More feedback welcome -- obviously, this writer has hardly been tested by anyone who knows anything about JATS.

**Comment by pdlug** [comment]
Thanks it's working for me now. I'll continue testing the JATS output.
