### ISSUE TITLE
Ordered lists "restart" (docx to html)

### ISSUE THREAD

**Issue by skippylafarge** [jgm/pandoc#4025]
Using version 2.0.1
`pandoc -f docx -t html+smart --track-changes=all OrderedListExample.docx -o OrderedListExample.docx.html`

Given a docx with an ordered list like this:
```
1. Foo
2. Bar
3. Baz
(intervening paragraph)
4. Boo
...
```
The output ends up as this:
```
1. Foo
2. Bar
3. Baz
(intervening paragraph)
1. Boo
...
```
As one might guess, I'm finding that `<ol>`s are being closed and re-opened, but without a `start` attribute to maintain proper numbering.

Here's a document to demonstrate:
[OrderedListExample.docx](https://github.com/jgm/pandoc/files/1435661/OrderedListExample.docx)

**Comment by jgm** [comment]
@jkr can you take a look?

**Comment by jkr** [comment]
Hmm... it should do the "<ol start=" correctly. Let me take a look in the xml and see if I can figure out what's going on.

**Comment by jkr** [comment]
Okay, this isn't a quick fix. Docx lists don't restart. In other words, even if they're interrupted, they continue where they left off unless otherwise specified. The behavior is the opposite, of course, in pandoc native (and html, tex, etc).

So we have to add a state variable to keep track of the current list number and the "numbering id" for the list type, and then check that variable to see if we're starting over or not. Definitely doable. I'll try to dive into it over the weekend.

**Comment by skippylafarge** [comment]
Thanks so much!

**Comment by skippylafarge** [comment]
Any update on this?

**Comment by jkr** [comment]
Should be fixed in the most recent commit. It works with your uploaded document.

**Comment by skippylafarge** [comment]
Fantastic, thanks!

**Comment by Ramlinbird** [comment]
I met the same problem. The pandoc version is,
```
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```
I run it with the command, `./bin/pandoc -f docx -t html Test.docx -o t.html`, and failed to find that all order number is restarted. How can I solved this, or is it possible to keep outputting the original order number?

Here's the document to demonstrate:
[Test.docx](https://github.com/Ramlinbird/testgit/blob/master/Test.docx)

**Comment by jkr** [comment]
That's a *very* old version of pandoc., and the problem has been fixed since then. We're on [version 2.7.2] now. Try downloading that and see if it works for you.

[version 2.7.2]: https://pandoc.org/releases.html#pandoc-2.7.2-5-april-2019
