### ISSUE TITLE
+tex_math_dollars, reveal and mathjax

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#4027]
As discussed on [pandoc-discuss](https://groups.google.com/d/msg/pandoc-discuss/Q6JSKcEa-0U/n628kRJvBAAJ) and probably related to #3743 .

jgm wrote: We now use the reveal.js mathjax plugin.  And my guess is
that it, unlike the reveal.js configuration we use for HTML, scans the whole document for $'s and treats sections within $ as math.

Indeed, you can see this here:
https://github.com/hakimel/reveal.js/blob/master/plugin/math/math.js

    inlineMath: [['$','$'],['\\(','\\)']] ,

Unfortunately, this doesn't seem configurable!  In our template we set some options, but the mathjax plugin's loadScript inserts the tex2jax stuff regardless of the options.

I'd like to find a good solution to this.  For your purposes, you could modify the revealjs template so it uses regular mathjax rather than the plugin (use the HTML template to guide you).  Or just modify it to point to a local version of the mathjax source, and modify the math plugin in that version.

**Comment by jgm** [comment]
I've asked to see if we can get a config option in the reveal.js texmath plugin.  In the mean time, your best bet is to use a local copy of reveal.js and modify the math plugin as follows.
```js
			tex2jax: {
				inlineMath: [['\\(','\\)']] ,
				skipTags: ['script','noscript','style','textarea','pre']
			},
```

**Comment by reagle** [comment]
Thank you for the [merge request](https://github.com/hakimel/reveal.js/pull/2045), hopefully @hakimel will be able to merge it soon.

**Comment by reagle** [comment]
Now merged at reveal.js! Does this mean the fix could find its way into 2.0.4?

**Comment by jgm** [comment]
We'd just need to modify the default reveal.js template so
that the tex2jax options are set appropriately.

+++ Joseph Reagle [Dec 01 17 06:18 ]:

**Comment by jgm** [comment]
Actually, I'm tempted to do something else, bypassing the math plugin entirely.
We don't really need tex2jax, since we put the math elements in specially marked spans.
tex2jax just slows things down.
I wonder if we could get by with adding a few things to our regular mathjax config (copying some of the things the math plugin does, but without tex2jax).
Note also that my changes to the math plugin still haven't migrated to a released version of mathjax (or to master).

**Comment by jgm** [comment]
I wasn't able to figure out how to do the alternative thing.  Here's the needed template modification, which will work when the change is merged into a released version of reveal.js:
```
diff --git a/data/templates/default.revealjs b/data/templates/default.revealjs
index 78c3c655..aed4b72c 100644
--- a/data/templates/default.revealjs
+++ b/data/templates/default.revealjs
@@ -234,6 +234,18 @@ $if(mathjax)$
         math: {
           mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js',
           config: 'TeX-AMS_HTML-full',
+          tex2jax: {
+            inlineMath: [['\\(','\\)']],
+            displayMath: [['\[','\]']],
+            balanceBraces: true,
+            processEscapes: false,
+            processRefs: true,
+            processEnvironments: true,
+            preview: 'TeX',
+            skipTags: ['script','noscript','style','textarea','pre','code'],
+            ignoreClass: 'tex2jax_ignore',
+            processClass: 'tex2jax_process'
+          },
         },
 $endif$
```

**Comment by jgm** [comment]
I added the tex2jax config to the default reveal.js template.

**Comment by jgm** [comment]
Note that this requires using the current `dev` branch of reveal.js, not `master`.

**Comment by reagle** [comment]
FYI: This is now in pandoc 2.0.5 https://github.com/jgm/pandoc/releases/tag/2.0.5

**Comment by reagle** [comment]
I've updated pandoc to 2.0.5 and reveal.js dev, but $ is still mangled.

I can see the options from the [pandoc generated slides](http://reagle.org/joseph/talks/2014/exemplar.html#/equations) and this is referencing the configuration in [reveal's math.js](http://reagle.org/joseph/talks/_reveal3.js/plugin/math/math.js).

Am I doing something wrong?

**Comment by mb21** [comment]
@reagle? what exact command are you using? try with `--mathjax`?

**Comment by reagle** [comment]
```/usr/local/bin/pandoc -f markdown+mmd_title_block+yaml_metadata_block+smart+implicit_header_references+superscript+subscript+tex_math_dollars+autolink_bare_uris -w html -s --tab-stop 4 --email-obfuscation=references -c http://reagle.org/joseph/talks/_custom/class-handouts-201306.css --section-divs -o /Users/reagle/joseph/handouts/2014/exemplar.html --mathjax /Users/reagle/joseph/handouts/2014/exemplar-2.md```

**Comment by jgm** [comment]
You need to use the dev version of reveal.js, since my change is not yet in a released version.
This means you'll have to self-host reveal.js and set the `revealjs-url` variable so the generated HTML will link to the self-hosted version.

**Comment by reagle** [comment]
Yes, this the link to [reveal's math.js](http://reagle.org/joseph/talks/_reveal3.js/plugin/math/math.js), which is the dev version, and (I think) includes your pull request.

**Comment by reagle** [comment]
I haven't set the revealjs-url variable though, I will look into that. (But when I looked at the source of my slideset, I followed the link to the dev version.)

**Comment by reagle** [comment]
I believe I did it correctly. My [slide](http://reagle.org/joseph/talks/2014/exemplar.html#/equations) ends with this:

```
<script>
  |  
  | // Full list of configuration options available at:
  | // https://github.com/hakimel/reveal.js#configuration
  | Reveal.initialize({
  | // Push each slide change to the browser history
  | history: true,
  | // Transition style
  | transition: 'linear', // none/fade/slide/convex/concave/zoom
  | math: {
  | mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js',
  | config: 'TeX-AMS_HTML-full',
  | tex2jax: {
  | inlineMath: [['\\(','\\)']],
  | displayMath: [['\\[','\\]']],
  | balanceBraces: true,
  | processEscapes: false,
  | processRefs: true,
  | processEnvironments: true,
  | preview: 'TeX',
  | skipTags: ['script','noscript','style','textarea','pre','code'],
  | ignoreClass: 'tex2jax_ignore',
  | processClass: 'tex2jax_process'
  | },
  | },
  |  
  | // Optional reveal.js plugins
  | dependencies: [
  | { src: '../_reveal3.js/lib/js/classList.js', condition: function() { return !document.body.classList; } },
  | { src: '../_reveal3.js/plugin/zoom-js/zoom.js', async: true },
  | { src: '../_reveal3.js/plugin/math/math.js', async: true },
  | { src: '../_reveal3.js/plugin/notes/notes.js', async: true }
  | ]
  | });
  | </script>
``` 

and `'../_reveal3.js/plugin/math/math.js'` links to [this]().

**Comment by jgm** [comment]
No, that doesn't include my pull.

Note that the dev version of reveal.js is not in the master
branch, it's in a special dev branch.

+++ Joseph Reagle [Dec 13 17 10:04 ]:

**Comment by reagle** [comment]
Got it, my webhost repo wasn't switched to dev branch; thanks for the help, looks good now!
