### ISSUE TITLE
MathML to pandoc MD: default columnalign is wrong

### ISSUE THREAD

**Issue by danieltuzes** [jgm/pandoc#4030]
When an `<mtable>` element is converted to pandoc's MD (or to any latex notation I suppose), it forgets that the default value of columnalign attribute is center, and not e.g. left. Therefore converting the mathml equation to md results in aligning the equation to the left, and not to the center.

Input:
```
<math display='block'>
 <mtable>
  <mtr>
   <mtd>
    <mn>222</mn>
   </mtd>
  </mtr>
  <mtr>
   <mtd>
    <mn>2</mn>
   </mtd>
  </mtr>
 </mtable>
</math>
```

Output:
```
 \[\begin{array}{l}
 222 \\
 2 \\
 \end{array}\]
```

If it is stated that `<mtable columnalign='center'>`, it produces
```
$$\begin{matrix}
222 \\
2 \\
\end{matrix}$$
```
which is at least acceptable. But the two results should be the same. (Why not gathered? It isn't a matrix.)
Version I use: Pandoc 2.0.0.1

**Comment by jgm** [comment]
This should go on jgm/texmath, which handles all the math conversions, rather than here.
