### ISSUE TITLE
Character in MathML is not recognised

### ISSUE THREAD

**Issue by danieltuzes** [jgm/pandoc#4034]
The character "SMALL CONTAINS AS MEMBER" is not recognized in MathML either in UTF-8 and HTML Entity (hex).

## Example:
This goes in:
```
In latex:
\[X \mathrel\backepsilon  x\]

In mathml:
<math display='block'>
 <mrow>
  <mi>X</mi><mo>&#x220D;</mo><mi>x</mi></mrow>
</math>
```
This comes out:
`In latex: $$X \mathrel\backepsilon  x$$ In mathml: $$X x$$`

I used Pandoc 2.0.0.1 and `pandoc -f html+tex_math_single_backslash in.html -t markdown -o out.md`.

**Comment by mb21** [comment]
All math conversions by pandoc are done by the https://github.com/jgm/texmath library. Please report the issue there, thanks.
