### ISSUE TITLE
Pandoc 2.x gfm To gfm Use Setex Header

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4035]
When converting from `gfm` to  `gfm` pandoc uses ATX headers for headers level 1 and 2 (as if the `--atx-headers` option was used).

The expected behaviour would be to follow default:

> The default is to use setext-style headers for levels 1-2, and then ATX headers.

**Comment by jgm** [comment]
We don't really have control over this, since we're using
the commonmark writer from a C library, and it doesn't have
this option.

+++ Tristano Ajmone [Nov 03 17 17:01 ]:
>   When converting from gfm to gfm pandoc uses ATX headers for headers
>   level 1 and 2 (as if the --atx-headers option was used).
>
>   The expected behaviour would be to follow default:
>
>     The default is to use setext-style headers for levels 1-2, and then
>     ATX headers.

**Comment by tajmone** [comment]
Ok, it's fine then (not a big deal at all). 

Maybe is worth adding a note about this on the documentation, where gfm format is covered.
