### ISSUE TITLE
Feature request: Better indentation of org-mode blocks

### ISSUE THREAD

**Issue by diamond-lizard** [jgm/pandoc#4036]
When pandoc 1.19.2.1-r1 converts HTML to org-mode format, all the text in org-mode blocks are indented to be flush with the left-most column, like so:

```org-mode
* foo bar
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec
hendrerit tempor tellus. Donec pretium posuere tellus. Proin quam
nisl, tincidunt et, mattis eget, convallis nec, purus. Cum sociis
** baz
natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus. Nulla posuere. Donec vitae dolor. Nullam tristique
diam non turpis. Cras placerat accumsan nulla. Nullam rutrum. Nam
vestibulum accumsan nisl.
```

It would be preferable if the text was instead indented to be directly under the headings, like so:

```org-mode
* foo bar
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec
  hendrerit tempor tellus. Donec pretium posuere tellus. Proin quam
  nisl, tincidunt et, mattis eget, convallis nec, purus. Cum sociis
** baz
   natoque penatibus et magnis dis parturient montes, nascetur
   ridiculus mus. Nulla posuere. Donec vitae dolor. Nullam tristique
   diam non turpis. Cras placerat accumsan nulla. Nullam rutrum. Nam
   vestibulum accumsan nisl.
```

**Comment by jgm** [comment]
This wouldn't be hard to do.  @tarleb, do you agree that we should use this kind of indentation. Would it cause any problems?

**Comment by tarleb** [comment]
I believe most org users use this kind of indentation and think it would
be a good change.

How would we do this? Hierarchicalize?

**Comment by jgm** [comment]
Yes, I think hierarchicalize would be the way to do it.  We'd then render a `Sec` by printing the header and then putting the contents under `nest (n+1)`, where `n` is the header level.

**Comment by jgm** [comment]
Working on this now.

**Comment by jgm** [comment]
I have committed a fix, but I don't know org well enough to know that this is right.
(E.g. are HTML blocks supposed to be indented, too? Does that affect indentation in the output when exported?)
Please have a look and let me know.

**Comment by jgm** [comment]
Actually, I've come to have doubts about this fix.
When I create a document using org mode, emacs shows everything indented as you describe.
That is, the text is indented under the header.  But the actual text file does not contain this indentation; it's just something Emacs does in showing it to you.

Emacs:

<img width="165" alt="screen shot 2017-11-04 at 11 30 49 am" src="https://user-images.githubusercontent.com/3044/32408352-9b145912-c153-11e7-87f8-facd57e561de.png">

The text file:
```
* headere
Some text.
** subhead
More text.
```

If I actually indent the text in the org file, then in Emacs displays indented too far.
So I'm going to revert this change until convinced that it really makes sense.

**Comment by tarleb** [comment]
Interesting. This seems to be controlled by the `org-ajust-indentation` variable and the `#+STARTUP: indent` option.  I wasn't aware of that before.

With this new information, I agree that the writer should not add indentation.
