### ISSUE TITLE
Documentation: Clarify fenced_divs

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4037]
This part of the new `fenced_divs` feature is not very clear:

> The attributes may optionally be followed by another string of consecutive colons

How does the count of matching `:` work?

The example:

```
::: Warning ::::::
This is a warning.

::: Danger
This is a warning within a warning.
:::
::::::::::::::::::
```

... seems to suggest that the closing colon fences must be as long as the full opening line (ie: including non fence-chars, and whitespaces, etc.). How is exactly the criteria? Same colomn?

Clearly, it's not based only on the left-hand-side colomns — there are 3 for both the `Warning `and nested `Danger` divs.

Maybe adding a few notes to the documentation could help.

**Comment by jgm** [comment]
No, the length doesn't matter.  All opening fences must have an attribute.  Fences without attributes are closing fences.
