### ISSUE TITLE
Release tags not being applied to pandoc-templates

### ISSUE THREAD

**Issue by jpcirrus** [jgm/pandoc#4044]
Before 2.0, pandoc-templates was tagged with the appropriate pandoc release numbers but are not anymore. This makes it much harder to apply the corresponding default template diffs between releases to custom templates.

**Comment by jgm** [comment]
I didn't realize they weren't working.  We changed from git
submodules to subtrees.  I just tried something to fix the
tags, and ended up messing up the whole repo.  So I had to
delete and restore, and now we have no tags at all.
