### ISSUE TITLE
Setting otherlangs from the command line

### ISSUE THREAD

**Issue by greut** [jgm/pandoc#4047]
Using pandoc, I managed to produce the following output using the YAML prolog.

    ---
    lang: fr
    otherlangs: [en]
    ---

Generates this latex code.

    \ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
      \usepackage[shorthands=off,english,main=french]{babel}
    \else
      \usepackage{polyglossia}
      \setmainlanguage[]{french}
      \setotherlanguage[]{english}
    \fi

But, I cannot manage to have it working using the commande-line arguments. This what I tried.

    $ pandoc -s -t latex -V lang=fr -V otherlangs="[en]"

Which produces:

    \ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
      \usepackage[shorthands=off,main=french]{babel}
    \else
      \usepackage{polyglossia}
      \setmainlanguage[]{french}
    \fi

Any hints on how I should pass de `otherlangs` variable from the command line? Having `-V` or `-M` to support a list of values seems to be a limitation.

**Comment by greut** [comment]
Funnily, targetting the variables directly has a strange behavior with _polyglossia_.

```console
$ pandoc -s -t latex -V lang=fr -V babel-otherlangs="english" -V polyglossia-otherlangs="english" test.md
```

```latex
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,english,main=french]{babel}
\else
  \usepackage{polyglossia}
  \setmainlanguage[]{french}
  \setotherlanguage[]{}
\fi
```

**Comment by mb21** [comment]
see the discussion on https://stackoverflow.com/a/47140718/214446

**Comment by jgm** [comment]
The command line flag to set metadata is --metadata.
-V sets a variable for the template, but doesn't set the
value in metadata.

I think the main problem, though, is that there's no
good way to set structured metadata from the command
line.  Here you want a list.  If you do

    --metadata otherlangs='[en]'

you'll get a string with value '[en]'.

Your best bet, then, is to create a small YAML file with the
metadata you need:  langs.yaml.

---
lang: fr
otherlangs: [en]
...

and then include this on the command line together with your
markdown source file.  Pandoc will concatenate them before
processing.

+++ Yoan Blanc [Nov 06 17 15:53 ]:

**Comment by greut** [comment]
The full story is that I'm looking for a way to deactivate all the clever things done by the Latex when the language is French, like adding a non-breaking space before every colon. Which breaks some of the code layout.

I ended up altering the `meta` directly through the filter. Since the filter requires it, it feels okayish. At least the hack is contained.

```python
from pandocfilters import (elt, toJSONFilter, Para, RawBlock, CodeBlock,  #noqa
                           RawInline, Str)


# those are not present in pandocfilters.
MetaInlines = elt('MetaInlines', 1)
MetaList = elt('MetaList', 1)


def other(lang, full_lang):
    """
    Create a filter that changes the language before a CodeBlock or a RawBlock.
    """

    before = Para([RawInline('tex',
                             r'\begin{{otherlanguage}}{{{0}}}'
                             .format(full_lang))])
    after = Para([RawInline('tex',
                            r'\end{{otherlanguage}}')])

    def fn(key, value, format, meta):
        """The filter."""

        # Adds the otherlangs properties if not found.
        if 'otherlangs' not in meta:
            meta['otherlangs'] = MetaList([MetaInlines([Str(lang)])])

        if key in ('CodeBlock', 'RawBlock'):
            # Uses CodeBlock and RawBlock, hence the #noqa above.
            block = globals()[key](*value)
            return (before, block, after)

    return fn


if __name__ == "__main__":
    toJSONFilter(other('en', 'english'))
```

Cheers,
