### ISSUE TITLE
ePub generation : issue with media paths when using mixed MD/HTML

### ISSUE THREAD

**Issue by anthonynelzin** [jgm/pandoc#4050]
Hi,

Pandoc is part of the pipeline I am using to produce ePubs for my company. While working on updating our pipeline to Pandoc 2.0.1.1, I stumbled on this issue. We use standard MD markup to link to images (all media files are stored in a `/media` subfolder,):

```
![Lorem ipsum.](media/img-01.jpg)
```

But we have to use HTML to link to audio or video files:

```
<figure>
<video controls="controls" poster="media/img-02.jpg" src="media/img-02.m4v" />
<figcaption>Lorem ipsum.</figcaption>
</figure>
```

When compiling the book using Pandoc 2.0.1.1, the image markup is converted to HTML as such:

```
<figure>
<img src="../media/file01.jpg" alt="Lorem ipsum" />
<figcaption>Lorem ipsum</figcaption>
</figure>
```

That's all fine and well, and reflects the new structure of the ePub files that Pandoc 2.x produces. But the video markup is left untouched, while we were excepting something like this:

```
<figure>
<video controls="controls" poster="../media/file02.jpg" src="../media/file03.m4v" />
<figcaption>Lorem ipsum.</figcaption>
</figure>
```

I thought of using the `--epub-subdirectory` option with an empty string to revert to the old structure, but it doesn't change how the markup is converted (so now the video markup is OK, but the image markup isn't). Am I missing something, or is it a real bug?

**Comment by jgm** [comment]
>   I thought of using the --epub-subdirectory option with an empty string
>   to revert to the old structure, but it doesn't change how the markup is
>   converted (so now the video markup is OK, but the image markup isn't).
>   Am I missing something, or is it a real bug?

That looks like a bug.  Let me look into it.

Another thing you could consider doing is replacing your
raw HTML with something like

    ![Lorem ipsum.](media/img-02.m4v){.video controls="controls" poster="media/img-02.jpg"}

and then using a filter to replace the resulting Image with
raw HTML with a video tag.

+++ Anthony Nelzin-Santos [Nov 07 17 16:00 ]:

**Comment by jgm** [comment]
OK, I found a whole bunch of problems in the epub writer, fixed with latest commit.

`--epub-subdirectory` won't help; this only affects the outermost container.  So the media will still be in `../media/` relative to the chapters.

You could use the approach I suggest above, or perhaps just use `../media` in your HTML tags, and use a symlink so you get the right things to display in the markdown source?

**Comment by jgm** [comment]
Actually, the most practical approach for you (minimum change to your existing setup) would be to create a filter that modifies raw html blocks and inlines, substituting `../media` for `media`.  This would be very easy to do using the new, built-in lua filters system.  See the documentation on the website.

**Comment by anthonynelzin** [comment]
I'll try and use filters, it seems like the best approach for our needs. Thanks!

**Comment by jgm** [comment]
Oh, I completely forgot that we did actually support image links from HTML tags.
I'll fix this soon.
