### ISSUE TITLE
-M/--metadata doesn't override a value in document

### ISSUE THREAD

**Issue by lierdakil** [jgm/pandoc#4054]
From manual:
> -M KEY[=VAL], --metadata=KEY[:VAL]
Set the metadata field KEY to the value VAL. A value specified on the command line overrides a value specified in the document. 

However, with Pandoc-2.0.1.1 at least, I have a very different (and strange) experience.

**test.md**:
```markdown
---
aMetaDataField: somestring
---
```

running `pandoc -t markdown -s test.md -MaMetaDataField=otherstring`, I get this:
```markdown
---
aMetaDataField:
- somestring
- otherstring
---
```

So it would appear that instead of *overriding*, CLI options are *appended* to those in the document. 

Is this intended? Honestly, I would prefer the override. In any case, documentation doesn't match observed behavior.

**Comment by jgm** [comment]
Regression, unintended! `addMetadata` in Text.Pandoc.App needs adjusting.
We need to make sure that this kind of list creation works for separate things specified using `-M`, but we don't want it to do this between an `-M` value and a metadata value defined in the document.
