### ISSUE TITLE
Pandoc markdown reader unexpectedly parses raw latex in pandoc 2+

### ISSUE THREAD

**Issue by jcbagneris** [jgm/pandoc#4056]
Hi there,

Pandoc 2.0.1.1 behaves differently than pandoc 1.19.2.1 when raw latex code is present in a pandoc markdown source. The problem is related to one particular syntax in column definitions in the tabular environnement.

Minimum working example:

```
$ cat mwe.md
Tabular column definition which works as expected:

\begin{tabular}{lrr}
Blah & Foo & Bar \\
\end{tabular}

Tabular column definition which does not work as expected:

\begin{tabular}{l*{2}{r}}
Blah & Foo & Bar \\
\end{tabular}

$ pandoc -f markdown -t native mwe.md
[Para [Str "Tabular",Space,Str "column",Space,Str "definitions",Space,Str "which",Space,Str "work:"]
,RawBlock (Format "latex") "\\begin{tabular}{lrr}\nBlah & Foo & Bar \\\\\n\\end{tabular}"
,Para [Str "Tabular",Space,Str "column",Space,Str "definition",Space,Str "which",Space,Str "which",Space,Str "do",Space,Str "not",Space,Str "work:"]
,Para [Str "\\begin{tabular}{l*{2}{r}}",SoftBreak,Str "Blah",Space,Str "&",Space,Str "Foo",Space,Str "&",Space,Str "Bar",Space,Str "\\",SoftBreak,Str "\\end{tabular}"]]
```

The same minimum working example works as expected in pandoc 1.19.2.1.
An obvious workaround is to use the generic raw attribute extension to explicitly mark the latex block as such.
But unless I missed something, I think this is some kind of regression.

Thank you

**Comment by labdsf** [comment]
Seems you have modified `mwe.md`, text does not correspond ("which work:" in native etc.). Just for reference, here is what I got with current `master`:
```
$ pandoc -f markdown -t native mwe.md
[Para [Str "Tabular",Space,Str "column",Space,Str "definition",Space,Str "which",Space,Str "works",Space,Str "as",Space,Str "expected:"]
,RawBlock (Format "latex") "\\begin{tabular}{lrr}\nBlah & Foo & Bar \\\\\n\\end{tabular}"
,Para [Str "Tabular",Space,Str "column",Space,Str "definition",Space,Str "which",Space,Str "does",Space,Str "not",Space,Str "work",Space,Str "as",Space,Str "expected:"]
,Para [Str "\\begin{tabular}{l*{2}{r}}",SoftBreak,Str "Blah",Space,Str "&",Space,Str "Foo",Space,Str "&",Space,Str "Bar",Space,Str "\\",SoftBreak,Str "\\end{tabular}"]]
```

**Comment by labdsf** [comment]
The problem is with LaTeX reader:
```
$ pandoc -f latex <<EOF
> \begin{tabular}{l*{2}r}
> Blah & Foo & Bar \\
> \end{tabular}
> EOF

Error at "source" (line 2, column 6):
unexpected &
expecting \end{tabular}
Blah & Foo & Bar \
     ^
```

**Comment by jcbagneris** [comment]
Thank you for investigating and sorry for the slightly different versions of `mwe.md`, wrong copy paste after editing for clarity.

**Comment by labdsf** [comment]
By the way seems pandoc never parsed the second format correctly, it does not parse it as table in old versions. However, it should not crash.

**Comment by labdsf** [comment]
Well, the first bad commit is 0feb7504b1c68cef76b30ea9987e2eae3101714c which is a rewrite of LaTeX reader

**Comment by labdsf** [comment]
New parser is correct in treating `&` as error. It is not a regression. `parseAligns` never parsed this syntax correctly, it just need to be extended.

**Comment by jcbagneris** [comment]
Actually this syntax for describing columns is seldom used which is probably why this never showed up before.

**Comment by labdsf** [comment]
Previously LaTeX reader didn't throw error at `&`, but it never parsed it as a table either.

**Comment by jcbagneris** [comment]
Yes, I get it. Unfortunately I don't know Haskell and cannot really read the code, but I guess `parseAligns` is the function responsible for the parsing of tabular spec, and it does not know about the `*{num}{type}` syntax.

**Comment by dylandforbes** [comment]
@jcbagneris how is this syntax not common? I don't know of any way to indicate a new column other than `&`

**Comment by jcbagneris** [comment]
@dylandforbes the uncommon syntax is the column description using `*{num}{type}`.
"Usual" column description works correctly:
```
$ /usr/bin/pandoc -f latex <<EOF
> \begin{tabular}{lrr}
> Blah & Foo & Bar \\
> \end{tabular}
> EOF
<table>
<tbody>
<tr class="odd">
<td style="text-align: left;">Blah</td>
<td style="text-align: right;">Foo</td>
<td style="text-align: right;">Bar</td>
</tr>
</tbody>
</table>
```

**Comment by andrewderrington** [comment]
I have found a different manifestation of what may be the same error. I have a markdown file with latex in it that processes successfully to pdf on pandoc1.19.2.1 but crashes pandoc2.0.1.1.

Processing the files to tex instead of pdf shows a line
\parbox[t]{0.4\textwidth}{

which pandoc1.19.2.1 passes through unchanged but 2.0.1.1 changes to

\textbackslash{}parbox{[}t{]}\{0.4\textwidth\}\{

The command I use is 
pandoc -s /Users/amd/Dropbox/02Andrew/02-Marketing/Marketing -o /Users/amd/Dropbox/02Andrew/02-Marketing/Packages-2.tex 
for pandoc2 and
pandoc -s /Users/amd/Dropbox/02Andrew/02-Marketing/Marketing -o /Users/amd/Dropbox/02Andrew/02-Marketing/Packages-1.tex
for pandoc1.

I have uploaded the source file (I added a .txt extension to get it to upload) and the two output files.
The problematic 'parbox' command is on line 82 of the output files and line 38 of the input file.


[Marketing.txt](https://github.com/jgm/pandoc/files/1464631/Marketing.txt)
