### ISSUE TITLE
Support svg images when going from markdown to docx

### ISSUE THREAD

**Issue by agusmba** [jgm/pandoc#4058]
In a similar way to https://github.com/jgm/pandoc/issues/1793 for pdf generation, it would be nice to automatically convert svg images to png (or any word supported format) when going from markdown to docx.

**Comment by iandol** [comment]
Hi, the latest version of Word 2016 finally supports SVG:

https://support.office.com/en-us/article/edit-svg-images-in-microsoft-office-2016-69f29d39-194a-4072-8c35-dbe5e7ea528c?ui=en-US&rs=en-US&ad=US#id0eaafaaa=office_2016_on_mac

**Comment by agusmba** [comment]
Thanks for the pointer!

It took them a while for a 1999 standard, and it seems it's only for whose with active subscriptions to 365

Anyway, better late than never. Nice!

**Comment by mb21** [comment]
Since we need to generate a fallback-png for this anyway, this seems as good a time as any, to factor out the svg-to-png rendering features that was [added for LaTeX/PDF output](https://github.com/jgm/pandoc/commit/6b72c5e35ba9b0872704b77b2bd8793657adcaba), and generalize it to docx and epub output (https://github.com/jgm/pandoc/issues/2766).

**Comment by mb21** [comment]
@jgm What do you think of factoring out the `rsvg-convert`-related code from `PDF.hs`? I'm not sure where it should go: in `Text.Pandoc.Shared` (where `PDF.hs` lives) or `Text.Pandoc.Writers.Shared` (where `EPUB.hs` etc. are). Or even `Text.Pandoc.ImageSize` which already has morphed into a kind of general-purpose image module, or a new module?

**Comment by agusmba** [comment]
The nice thing is that even older word (2013) can open documents with SVGs (I guess they fall back to showing the png)

**Comment by jgm** [comment]
Are you talking about convertImage from the PDF
module, or are you thinking of something more
special-purpose, just for SVG?

**Comment by mb21** [comment]
I don't remember, it's been a while ;-) But yes, maybe LaTeX and Word understand about the same subset of image formats, then we could just move the whole `convertImage` function...

**Comment by ociule** [comment]
As a heavy user of the docx output format, I'm really interested in this issue. It would allow outputting better quality documents.

**Comment by leonidlezner** [comment]
The issue is still there: When convertig Markdown to PDF the SVGs are embedded, in DOCX files the images are not present, only placeholders (Broken image...). Is there any way to deal with Word documents?

**Comment by jgm** [comment]
It would be good to do something here.  Note that `convertImage` from the PDF module currently has type
```
convertImage :: WriterOptions -> FilePath -> FilePath
             -> IO (Either Text FilePath)
```
It creates a file.  I think we should create a new unexported module Text.Pandoc.Image with
```
convertImage :: WriterOptions
   -> MimeType   -- ^ Input mime type
   -> ByteString  -- ^ Input image as bytestring
   -> MimeType  -- ^ Desired output mime type
   -> IO (Either Text ByteString)
```
This would be more suitable for use in Word, since we don't have a tmp dir.  We'd need a bit of code around this in Text.Pandoc.PDF, but it would be simple.

Note: rsvg-convert can be used as a pipe.

**Comment by jgm** [comment]
Or maybe Text.Pandoc.ImageSize should be folded into the new Text.Pandoc.Image (which would then need to be exported).  ImageSize contains an ImageType type, which could be used instead of MimeType in the new `convertImage`.

**Comment by jgm** [comment]
Also, looking at the code, it's not clear to me why we use rsvg-convert to go to pdf and then juicypixels to go to png.  We could go directly from svg to png with rsvg-convert, no?
And that would eliminate our dependency on JuicyPixels, which would be nice if we don't need it for anything else.  Anyway, this part of the code needs an overhaul.

**Comment by jgm** [comment]
I added an unexported module Text.Pandoc.Image with svgToPng.

**Comment by gijswijs** [comment]
I'm confused. is this a milestone for the next release, or is it not?

Either way, I'm really happy to see that you folks are working on this.

**Comment by mb21** [comment]
hm... I was taking a stab at this... and `svgToPng` in `Text.Pandoc.Image` is great... but we cannot run it in the Pandoc Monad.. :S 

for the record, this is how far I got:

```diff
diff --git a/src/Text/Pandoc/Writers/Docx.hs b/src/Text/Pandoc/Writers/Docx.hs
index 2caba59cc..d5403e65b 100644
--- a/src/Text/Pandoc/Writers/Docx.hs
+++ b/src/Text/Pandoc/Writers/Docx.hs
@@ -44,6 +44,7 @@ import Text.Pandoc.Definition
 import Text.Pandoc.Generic
 import Text.Pandoc.Highlighting (highlight)
 import Text.Pandoc.Error
+import Text.Pandoc.Image (svgToPng)
 import Text.Pandoc.ImageSize
 import Text.Pandoc.Logging
 import Text.Pandoc.MIME (MimeType, extensionFromMimeType, getMimeType,
@@ -1328,7 +1329,12 @@ inlineToOpenXML' opts (Image attr@(imgident, _, _) alt (src, title)) = do
   imgs <- gets stImages
   let
     stImage = M.lookup (T.unpack src) imgs
-    generateImgElt (ident, _, _, img) =
+    svgBlip ident = mknode "a:extLst" [] $
+      mknode "a:ext" [("uri", "{96DAC541-7B7A-43D3-8B79-37D633B846F1}")] $
+        mknode "asvg:svgBlip" [
+          ("xmlns:asvg", "http://schemas.microsoft.com/office/drawing/2016/SVG/main")
+        , ("r:embed", ident) ] ()
+    generateImgElt (ident, _, mbMimeType, img) =
       let
         (xpt,ypt) = desiredSizeInPoints opts attr
                (either (const def) id (imageSize opts img))
@@ -1343,7 +1349,10 @@ inlineToOpenXML' opts (Image attr@(imgident, _, _) alt (src, title)) = do
                             [("descr",T.unpack src),("id","0"),("name","Picture")] ()
                         , cNvPicPr ]
         blipFill = mknode "pic:blipFill" []
-          [ mknode "a:blip" [("r:embed",ident)] ()
+          [ mknode "a:blip" [("r:embed",ident)] $
+              case mbMimeType of
+                Just "image/svg+xml" -> [svgBlip ident]
+                _ -> []
           , mknode "a:stretch" [] $
               mknode "a:fillRect" [] ()
           ]
@@ -1414,6 +1423,8 @@ inlineToOpenXML' opts (Image attr@(imgident, _, _) alt (src, title)) = do
          else do
            -- insert mime type to use in constructing [Content_Types].xml
            modify $ \st -> st { stImages = M.insert (T.unpack src) imgData $ stImages st }
+
+           svgToPng opts $ toLazy img
            return [generateImgElt imgData]
       )
       `catchError` ( \e -> do
```

**Comment by jgm** [comment]
> but we cannot run it in the Pandoc Monad.

`svgToPng` may be too specialized to make a method of PandocMonad.
One possibility would be to add a method to PandocMonad class
``` haskell
ioWithFallback :: PandocMonad m => a -> IO a -> m a
```
This would be implemented in `PandocIO` by simply running the IO action.
In `PandocPure` it would simply return the fallback.
With this we could easily integrate `svgToPng`.
Thoughts?  @tarleb @jkr

**Comment by tarleb** [comment]
I'm not sure. Seems like a reasonably clean and pragmatic solution, but feels a bit weird, too.

Questions that came to mind, in no particular order:

- Would an IOException in the IO action trigger the fallback, or would it bubble up in the form of a PandocError?
- Could a `Text.Pandoc.App.Transform` be a viable option to perform the conversion?
- A separate class `MonadFallbackIO` or the like could allow for finer-graned effects handling; but might be too complicated.

**Comment by jgm** [comment]
> Would an IOException in the IO action trigger the fallback, or would it bubble up in the form of a PandocError?

I suppose we'd want to trap exceptions in the IO action and raise a PandocError.  The fallback would just be for cases that can't perform IO.  If you wanted to return the fallback if there were IO exceptions, you could just handle the exception yourself.

> Could a Text.Pandoc.App.Transform be a viable option to perform the conversion?

Ah, I see; you mean do a pass through the AST first, converting SVGs to PNGs, before rendering the AST?  This might be a bit less performant, but we could do it without changes to the Class API.

**Comment by frabera** [comment]
Is there any update for this?

**Comment by jgm** [comment]
> Could a Text.Pandoc.App.Transform be a viable option to perform the conversion?

It can't be a Transform, those are pure.

We could add an ad hoc step to the pipeline in T.P.App (before extractMedia) but, presumably, after filters?
This would be triggered only if docx is the output format.  It would convert any svgs in the mediabag to pngs, and change the image links accordingly.

**Comment by jgm** [comment]
Support for SVGs has been added!
Note:  this includes PNG fallbacks, but I can't really test to see whether these work on my recent version of Word. If anyone can test on an old version, it would be good to know if it works there too.

**Comment by agusmba** [comment]
Looking great! 👏

I did a quick test on my laptop, and even though I got a warning because I don't have `rsvg-convert`, I still got a proper docx (without the fallback png I guess):

![image](https://user-images.githubusercontent.com/3104020/131451890-52666504-7322-4678-b159-7387f5cc6ea8.png)

I'm using Word 365 (v2102).

If I open it with Word Online, it does *as expected* (W.Online doesn't support embedded SVG and shows the fallback png which is missing since I didn't have rsvg):

![image](https://user-images.githubusercontent.com/3104020/131453360-2c7b8190-ba6a-489e-ab8b-6c68a0031d84.png)

I'll upload my test files if you want to generate a proper docx (with rsvg).
[pandoc-issue-4058.zip](https://github.com/jgm/pandoc/files/7081741/pandoc-issue-4058.zip)

**Comment by jgm** [comment]
Good to know it's falling back to the PNG (or attempting to) on the online version. That's the piece I wasn't able to test.

**Comment by agusmba** [comment]
> Good to know it's falling back to the PNG (or attempting to) on the online version. That's the piece I wasn't able to test.

After obtaining a rsvg-convert build for windows, I could test it again, and it seems to work perfectly.

The online vew (browser) uses the PNG fallback (see the raster in the red curve when zoomed in 400x):
![image](https://user-images.githubusercontent.com/3104020/131663534-76e0a48f-f2b3-4ca1-b252-47322c0b1cf8.png)

which does not happen in the desktop version (real vector graphic included):
![image](https://user-images.githubusercontent.com/3104020/131663706-92d9cf0a-2b00-4963-a3d8-eff17df1b71b.png)

At 100% it is hard to spot the differences. 👍

**Comment by adamryczkowski** [comment]
What exactly do you do, to get the svg into the Word document? I've tried many things on my Ubuntu 22.04 (Pandoc 3.1.4) and all I get is either a placeholder without the rsvg-convert, or a PNG file with it, using the attached [pandoc-issue-4058.zip](https://github.com/jgm/pandoc/files/7081741/pandoc-issue-4058.zip) (I skipped the `--reference-doc`)

**Comment by jgm** [comment]
I'm seeing the svg in there (it's compressed as svgz).

<img width="638" alt="Screen Shot 2023-06-26 at 9 22 23 AM" src="https://github.com/jgm/pandoc/assets/3044/3ce9c0a0-8526-4f6d-bda3-69f638bcea21">

It's also linked in document.xml.  Everything looks right?

PS. The `-i` flag doesn't do what you think it does.  See the manual.
