### ISSUE TITLE
Pandoc Markdown Reader Creates Latex Errors

### ISSUE THREAD

**Issue by andrewderrington** [jgm/pandoc#4060]
I raised this as a comment in "Pandoc markdown reader unexpectedly parses raw latex in pandoc 2+ #4056." But that issue has been closed and this problem persists in 2.0.2. 

I have a markdown file with latex in it that processes successfully to pdf on pandoc1.19.2.1 but crashes pandoc2.0.1.1 and 2.0.2.

Processing the files to tex instead of pdf shows a line
\parbox[t]{0.4\textwidth}{

which pandoc1.19.2.1 passes through unchanged but 2.0.2
 changes to

\textbackslash{}parbox{[}t{]}{0.4\textwidth}{

The command I use is
pandoc -s /Users/amd/Dropbox/02Andrew/02-Marketing/Marketing -o /Users/amd/Dropbox/02Andrew/02-Marketing/Packages-2.tex
for pandoc2 and
pandoc -s /Users/amd/Dropbox/02Andrew/02-Marketing/Marketing -o /Users/amd/Dropbox/02Andrew/02-Marketing/Packages-1.tex
for pandoc1.

I have uploaded a minimal version of the source file (I added a .txt extension to get it to upload) and the two tex output files with extensions changed to txt.

[Marketing.txt](https://github.com/jgm/pandoc/files/1465961/Marketing.txt)
[Packages-2.txt](https://github.com/jgm/pandoc/files/1465963/Packages-2.txt)
[Packages-1.txt](https://github.com/jgm/pandoc/files/1465964/Packages-1.txt)
The problematic 'parbox' command is on line 82 of the output files and line 38 of the input file.

**Comment by mb21** [comment]
Issues are closed when they are fixed in master, not on release. Please try to build from source (or try next night's pandoc-nightly)

**Comment by andrewderrington** [comment]
OK, sorry: didn’t understand that.

Andrew

**Comment by mb21** [comment]
sure, I'll close this then... feel free to reopen if you can reproduce in current master.
