### ISSUE TITLE
html tables with col width="*" not handled properly

### ISSUE THREAD

**Issue by bshannon** [jgm/pandoc#4063]
I have an html file with a table that looks like this:

```
<table>
<col width="30%" />
<col width="30%" />
<col width="*" />
```
In this usage, width="*" means to make this column use all the remaining space.

pandoc turns this into (when converting to asciidoc):

`[width="60%",cols="50%,50%,",options="header",]`

If I change the table to:

```
<table>
<col width="30%" />
<col width="30%" />
<col width="40%" />
```

I get the expected:

`[width="100%",cols="30%,30%,40%",options="header",]`

(Using pandoc 2.0.2)

**Comment by mb21** [comment]
Didn't know about that, but appears to be a thing in HTML4: the [MultiLength unit](https://www.w3.org/TR/html4/types.html#h-6.6). In HTML5 of course, `width` attributes on table rows/cols etc. are deprecated anyway.

So I guess it's not worth adding this unit to pandoc imagesizes. With pandoc 2.0:

    $ pandoc -f html -t native
    <table>
    <colgroup>
      <col width="30%" />
      <col width="*" />
    </colgroup>
    <tr>
      <td>1</td>
    </tr>
    <tr>
      <td>2</td>
    </tr>
    </table>

    ^D

    [Table [] [AlignDefault] [0.3]
     [[]]
     [[[Plain [Str "1"]]]
     ,[[Plain [Str "2"]]]]]

So we could still fix this to have consistently lists of length two (the aligns and the lengths).

**Comment by tarleb** [comment]
The HTML reader now returns `ColWidthDefault` for these `<col>` elements, which seems ok. The Asciidoc writer still needs fixing though.

**Comment by jgm** [comment]
I can fix this in the HTML reader.
