### ISSUE TITLE
Pandoc 2 YAML literal block handling regression, chomp indicator borks parsing

### ISSUE THREAD

**Issue by alerque** [jgm/pandoc#4064]
YAML has a couple syntax options for blocks of text. You can use `>` for to start a multi-line input that will be re-wrapped ("folded style" in the YAML spec) or `|` for a pre-formatted string ("literal style" in the YAML spec). 

Both of these styles may be modified using a [Block Chomping Indicator](http://www.yaml.org/spec/1.2/spec.html#id2794534), most commonly used being the `-` indicator to indicate trailing and leading white-space should be stripped.

I have a number of book projects that employ extensive meta-data files. I used to be able to pass these to Pandoc along with the content file and it would use just the meta data it needed. Since updating to Pandoc-2 none of by book projects build any more. I've traced it to the fact that Pandoc seems to have stopped handling blocks with these chomp modifiers properly.

Specifically, the literal style is problematic if there are any blank lines in the following content (even if they are prefixed with the same whitespace as the block). The presence of any such block will completely bork Pandoc's reading any of the meta data.

Here is an MWE:

`test.yml`:
``` yaml
---
key: |-
  Meta stuff.

  Not Pandoc’s business.
title: MWE Book
...
```
`test.md`:
``` markdown
Test book content.
```

    $ pandoc test.yml test.md -o test.epub
    [WARNING] This document format requires a nonempty <title> element.
      Please specify either 'title' or 'pagetitle' in the metadata.
      Falling back to 'test'
    [WARNING] This document format requires a nonempty <title> element.
      Please specify either 'title' or 'pagetitle' in the metadata.
      Falling back to 'test'
    [WARNING] This document format requires a nonempty <title> element.
      Please specify either 'title' or 'pagetitle' in the metadata.
      Falling back to 'test'
 
Now take off the chomp indicator from `key: |` and it builds fine.

Note the folded style works fine even with a chomp indicator and similarly blank lines in between content in those blocks.

**Comment by mb21** [comment]
Thanks for the report, this was fixed in https://github.com/jgm/pandoc/commit/fb5ba1bb00a0d328db568952925f543b2bd8b584 and released in pandoc 2.0.2
