### ISSUE TITLE
pandoc 2 does not work on Windows XP SP3

### ISSUE THREAD

**Issue by johnd0e** [jgm/pandoc#4065]
Trying to launch `pandoc.exe` I get error:
```
The procedure entry point _wsplitpath_s could not be located in the dynamic link library msvcrt.dll
```

Indeed, `msvcrt.dll` doesn't have `_wsplitpath_s` export.
But `msvcr90.dll` does.

`msvcrt` is a system component and you can't depend on it, it should be either `msvcrVERSION.dll` if you're using dynamic linkage or nothing if you're using static.

https://social.msdn.microsoft.com/Forums/vstudio/en-us/2203f72c-5f09-4565-97b3-21337672b191/msvcrtdll?forum=vcgeneral

P.S.
Last pandoc which is working on XP is https://github.com/jgm/pandoc/releases/tag/1.19.2.1

**Comment by mb21** [comment]
Have you tried building from source on XP? If that works, can you tell us the build params? (windows build config is in https://github.com/jgm/pandoc/blob/master/appveyor.yml)

Maybe with GHC 8.0.0, because 8.0.1 [dropped Windows XP support](https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/8.0.1-notes.html).

**Comment by johnd0e** [comment]
No, I have not tried.

And I failed to find GHC 8.0.0 download.

**Comment by jgm** [comment]
We build on appveyor.  So, it may be that appveyor has
upgraded the versions of the libraries they use since
we put out 1.19.2.1.

Nothing in our build procedure directly brings in a
dependency on msvcrt.dll, so I don't know where this
comes from, exactly.

**Comment by jgm** [comment]
It should be possible to build on Windows with ghc 7.8, we still support that.

**Comment by jgm** [comment]
I don't know how important XP support is (since this isn't even supported by Microsoft anymore).  But if it were important, we could change the appveyor build to use ghc 7.10, I think.

**Comment by johnd0e** [comment]
I can't tell that XP support is important in general (personally I just have it installed on one of my PC's).
But still something is not proper enough in pandoc build chain: executables should not depend on `msvcrt.dll` regardless of XP support.

Anyway when I'll have time I'll  try to build it with ghc 7.10 (though I have no experience in it)

**Comment by mb21** [comment]
My opinion is that we would be doing people a disservice if we were to support an OS that doesn't get security updates anymore...

**Comment by johnd0e** [comment]
**mb21**,
Well, there is ReactOS (it is not dead AFAIK)

Or you can see this issue as a matter of bad exe linking practice, which can potentionally lead to other unpredictable consequences.

**Comment by johnd0e** [comment]
[The case against msvcrt.dll](https://sourceforge.net/p/mingw-w64/wiki2/The%20case%20against%20msvcrt.dll/)

And here is some recommendations for gcc http://www.mingw.org/node/25#comment-106 (not if they are relevant here)

**Comment by mb21** [comment]
@johnd0e I guess you'd have to talk to the GHC devs about that...

**Comment by jgm** [comment]
Yes, there's nothing we're doing explicitly that does this;
it appears to be something ghc is doing.  (For the same
reason, there's not much we can do about it.) I'd recommend
submitting a bug report to them rather than here.

+++ Mauro Bieg [Nov 27 17 13:15 ]:

**Comment by johnd0e** [comment]
https://ghc.haskell.org/trac/ghc/ticket/14537#ticket

**Comment by johnd0e** [comment]
Well, they are not going to fix that.
Actually, this can be changed on pandoc level, [using GCC specs file](http://www.mingw.org/node/25#comment-106).

Perhaps it'll be easier just to use old version of GHC.
I see [pandoc-nightly](https://github.com/pandoc-extras/pandoc-nightly) repository consist of yaml config only.
Is it really enough for all?

If so, am I able to clone that repository, and make simple changes in config to use needed GHC version?

**Comment by jgm** [comment]
You can build the most current release of pandoc with any
ghc version from 7.8 on.  You'll need to get the haskell stack
tool and the pandoc source code, but that should be all
you need.  stack uses 8.0.2 by default, currently, but you
can specify another ghc version on the command line.

+++ johnd0e [Nov 30 17 08:21 ]:

**Comment by johnd0e** [comment]
I mean that I would prefer to do it not on my local machine, but on appveyor.
I have zero experience in it, but see that pandoc-nightly repository is rather simple.
So my question: is it really that easy to setup appveyor build process?

**Comment by jgm** [comment]
pandoc-nightly pulls binaries from pandoc's own appveyor
build.

+++ johnd0e [Nov 30 17 09:57 ]:

**Comment by johnd0e** [comment]
Thanks, I see now.
Just've [tried](https://ci.appveyor.com/project/johnd0e/pandoc) to make build on appveyor and found that it uses ghc 8.0.2.
And I failed to found where I can specify other version.
Could you assist me in changing appveyor config in order to use specific ghc version?

**Comment by jgm** [comment]
Instead of 'stack setup' try

stack setup --compiler ghc-7.8.4

+++ johnd0e [Nov 30 17 23:59 ]:

**Comment by jgm** [comment]
You may also need the --compiler flag for 'stack install'
etc.  I can't remember.

+++ johnd0e [Nov 30 17 23:59 ]:

**Comment by johnd0e** [comment]
It failed..
https://ci.appveyor.com/project/johnd0e/pandoc/build/1.0.27

Also I tried to specify `compiler` in `stack.pkg.yaml`, still without success.
Perhaps other changes needed in stack config.
May be `resolver` version (have tried some values, but build also failed)

**Comment by jgm** [comment]
>  constructing the build plan, the following exceptions were encountered:
> In the dependencies for foundation-0.0.17:
>     base-4.7.0.2 must match >=4.8 && <5 (latest applicable is 4.10.0.0)
> needed due to pandoc-2.0.3 -> foundation-0.0.17
> In the dependencies for pandoc-types-1.17.3:
>     deepseq-generics-0.2.0.0 must match >=0.1 && <0.2 (latest applicable is 0.1.1.2)
> needed due to pandoc-2.0.3 -> pandoc-types-1.17.3
> Plan construction failed.

Try with ghc 7.10.3, then?

This is odd, though.  We still build with ghc 7.8.4 on
travis (though using cabal rather than stack).

I was not aware that we had a transitive dependency on
foundation -- I wonder where that comes from?

+++ johnd0e [Dec 02 17 01:58 ]:

**Comment by johnd0e** [comment]
7.10.3 fails compiling Compiling Network.HTTP.Proxy
https://ci.appveyor.com/project/johnd0e/pandoc/build/1.0.37

**Comment by jgm** [comment]
OK.  Maybe it isn't going to work with stack.  It's
definitely possible to compile with these older ghc
versions using cabal, though.  We do it in CI.

Try getting an older version of the Haskell Platform.
https://www.haskell.org/platform/download/7.10.3/HaskellPlatform-7.10.3-i386-setup.exe

Install this, and then use

'cabal install pandoc -fembed_data_files'

I'm sorry, I can't give you an appveyor recipe for this.
You may need to find a Windows machine to build on.

+++ johnd0e [Dec 02 17 22:15 ]:

**Comment by tarleb** [comment]
> I was not aware that we had a transitive dependency on foundation -- I wonder where that comes from?

http-client-tls → tls → cryptonite → foundation (from <http://packdeps.haskellers.com/reverse>).

**Comment by johnd0e** [comment]
> You may need to find a Windows machine to build on.

```
cabal install pandoc -fembed_data_files
Resolving dependencies...
Configuring http-client-0.5.7.1...
Building http-client-0.5.7.1...
Failed to install http-client-0.5.7.1
Build log ( C:\Users\admin\AppData\Roaming\cabal\logs\http-client-0.5.7.1.log ):
Building http-client-0.5.7.1...
Preprocessing library http-client-0.5.7.1...
[ 1 of 18] Compiling Network.PublicSuffixList.Types ( publicsuffixlist\Network\PublicSuffixList\Types.hs,
dist\build\Network\PublicSuffixList\Types.o )
[ 2 of 18] Compiling Network.PublicSuffixList.Serialize ( publicsuffixlist\Network\PublicSuffixList\Serial
ize.hs, dist\build\Network\PublicSuffixList\Serialize.o )
[ 3 of 18] Compiling Network.PublicSuffixList.DataStructure ( publicsuffixlist\Network\PublicSuffixList\Da
taStructure.hs, dist\build\Network\PublicSuffixList\DataStructure.o )
[ 4 of 18] Compiling Network.PublicSuffixList.Lookup ( publicsuffixlist\Network\PublicSuffixList\Lookup.hs
, dist\build\Network\PublicSuffixList\Lookup.o )
[ 5 of 18] Compiling Network.HTTP.Client.Util ( Network\HTTP\Client\Util.hs, dist\build\Network\HTTP\Clien
t\Util.o )
[ 6 of 18] Compiling Network.HTTP.Client.Types ( Network\HTTP\Client\Types.hs, dist\build\Network\HTTP\Cli
ent\Types.o )
[ 7 of 18] Compiling Network.HTTP.Client.Connection ( Network\HTTP\Client\Connection.hs, dist\build\Networ
k\HTTP\Client\Connection.o )
[ 8 of 18] Compiling Network.HTTP.Client.Headers ( Network\HTTP\Client\Headers.hs, dist\build\Network\HTTP
\Client\Headers.o )
[ 9 of 18] Compiling Network.HTTP.Client.Body ( Network\HTTP\Client\Body.hs, dist\build\Network\HTTP\Clien
t\Body.o )
[10 of 18] Compiling Network.HTTP.Client.Request ( Network\HTTP\Client\Request.hs, dist\build\Network\HTTP
\Client\Request.o )
[11 of 18] Compiling Network.HTTP.Proxy ( Network\HTTP\Proxy.hs, dist\build\Network\HTTP\Proxy.o )

Network\HTTP\Proxy.hs:223:9:
    Non type-variable argument
      in the constraint: Data.String.IsString [a]
    (Use FlexibleContexts to permit this)
    When checking that `hasLocal' has the inferred type
      hasLocal :: forall a.
                  (Eq a, Data.String.IsString [a]) =>
                  [a] -> Bool
    In the expression:
      do { let isURLlocal "127.0.0.1" = True
               isURLlocal "localhost" = True
               isURLlocal _ = False
               hasLocal exceptions = "<local>" `isInfixOf` exceptions;
           settings <- fetchProxy proto;
           return $ \ url -> do { ... } }
    In an equation for `systemProxy':
        systemProxy proto
          = do { let isURLlocal "127.0.0.1" = ...
                     isURLlocal "localhost" = ...
                     isURLlocal _ = ...
                     ....;
                 settings <- fetchProxy proto;
                 return $ \ url -> ... }
cabal: Error: some packages failed to install:
http-client-0.5.7.1 failed during the building phase. The exception was:
ExitFailure 1
http-client-tls-0.3.5.1 depends on http-client-0.5.7.1 which failed to
install.
pandoc-2.0.3 depends on http-client-0.5.7.1 which failed to install.
```

**Comment by jgm** [comment]
I'm not sure I can help you with this one, you may need
to contact the maintainer of http-client.

As you can see, we build on linux with 7.10.3
https://travis-ci.org/jgm/pandoc/jobs/311453168
and this issue doesn't look Windows-specific, so
I'm puzzled...

+++ johnd0e [Dec 04 17 19:43 ]:

**Comment by tarleb** [comment]
Do we still hope to fix this, or should the issue be closed? It seems that there is not much we can do here.

**Comment by jgm** [comment]
Let's close it.
