### ISSUE TITLE
Creole reader: itemlist exponential parsing performance

### ISSUE THREAD

**Issue by FrankKoormann** [jgm/pandoc#4067]
The creoleparser consumes processing time with exponential growth with higher numbers of items 
(recognizable around 10 items) in an item list. 
[creole-itemlist-bug.txt](https://github.com/jgm/pandoc/files/1471508/creole-itemlist-bug.txt)

**Comment by jgm** [comment]
@swilde - can you take a look?  From a quick look at the code, I think the problem is that `listItem` is defined in terms of `anyListItem` which is defined in terms of `listItem`...but I haven't looked at it in detail.

Test case:
```
* a
* a
* a
* a
* a
* a
* a
* a
* a
* a
* a
* a
* a
```

**Comment by swilde** [comment]
I'll have a look this weekend.

**Comment by swilde** [comment]
Was easy to fix.  :-)
