### ISSUE TITLE
Org-Reader: Honor #OPTION: tex:nil in order to use literal backslash

### ISSUE THREAD

**Issue by salamynder** [jgm/pandoc#4070]
I need to easily convert windows file paths.

Therefore
```bash
$ echo "C:\hello\there" | pandoc -f org -t native
[Para [Str "C:",RawInline (Format "latex") "\\hello",RawInline (Format "latex") "\\there"]]
```
should just product Str instead of RawInLine.

The tex-Option (pandoc\src\Text\Pandoc\Readers\Org\ExportSettings.hs) in the org-file is currently ignored. Suppose I could work on not ignoring this?

**Comment by mb21** [comment]
Shouldn't you use as org input:

    This is verbatim =C:\hello\there= or code ~C:\hello\there~

**Comment by salamynder** [comment]
Yes, of course I could! Thx for the reminder.

However, I'd rather not think about adding verbatim markup (=/~), plus for my current project I'm pretty sure I don't need raw_tex for documenting things.

Anything against unignoring this option?

**Comment by jgm** [comment]
Does `-f org-raw_tex` work?

**Comment by salamynder** [comment]
From what I saw in code ExtRawTex is explicitly enabled when parsing, so it shouldn't. Will try to do this ... ^^

**Comment by jgm** [comment]
You're right, `-raw_tex` doesn't work.  We could enable this, but I think it would be much better to make the parser sensitive to tex:nil.

**Comment by mb21** [comment]
Pandoc currently supports turning extensions on and off only for markdown, with the exception of the newly added [Ext_amuse](https://github.com/jgm/pandoc/commit/3a83b3843db6434e9806558ea1e912055d5baf04).

But I guess we could think about adding extensions to other readers/writers... @tarleb, @jgm..?

**Comment by jgm** [comment]
It is actually possible to turn them on and off in some
other cases, e.g. smart, and you can do -f latex-raw_tex.

But in this case, I think it's far better to change the
parser so it behaves the same way as org-mode itself.

+++ Mauro Bieg [Nov 15 17 08:49 ]:
