### ISSUE TITLE
otherlangs parameter in YAML doesn't work for latex output after recent update

### ISSUE THREAD

**Issue by qifei9** [jgm/pandoc#4072]
After recent update (at least from version `2.0.1.1`), `otherlangs` parameter in YAML doesn't work for latex output.
```
$ pandoc -v
pandoc 2.0.2
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.4.3.2
```

the exact command line used
```
pandoc -s -o test.tex test.md
```

the exact input used
```yaml
---
documentclass: article
lang: en
otherlangs: [de]
---

test
```

the output received
```latex
\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[english,]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,main=english]{babel}
\else
  % load polyglossia as late as possible as it *could* call bidi if RTL lang (e.g. Hebrew or Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[]{english}
\fi

\date{}

\begin{document}

test

\end{document}
```

the output you expected instead, `otherlangs` should be set for `babel` and `polyglossia`
```latex
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,ngerman,main=english]{babel}
\else
  % load polyglossia as late as possible as it *could* call bidi if RTL lang (e.g. Hebrew or Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[]{english}
  \setotherlanguage[]{german}
\fi
```

**Comment by jgm** [comment]
The way it works now, you don't set `otherlangs` explicitly.  Instead, pandoc will traverse the document and see what `lang` attributes are found on Spans and Divs.  The `babel-otherlangs` and `polyglossia-otherlangs` variables are then set automatically to support the languages that are actually used.

**Comment by jgm** [comment]
Manual says:

> This is automatically generated from the `lang` attributes
 > in all `span`s and `div`s but can be overridden.

That's not really accurate; it can't be overridden as `otherlangs`, though you can override `babel-otherlangs` and `polyglossia-otherlangs`.  Perhaps we should change things so that if `otherlangs` is set, the list of languages is taken from it rather than by traversing the document.  I don't know if there'd be a point to that.  But at least the documentation should be revised.

**Comment by mb21** [comment]
I think originally, it could be overriden by setting `otherlangs` in the metadata (or at least that's what I intended to implement back then). The reasoning being that it's much nicer and more portable to write `otherlangs: [de]` than `polyglossia-otherlangs: german; bable-otherlangs: German` (or whatever the exact syntax).

**Comment by qifei9** [comment]
Many thanks for your answers. Now I know how to set `otherlangs`, but I stll have a question: how to set some additional options for that language?

My previous working input is like:
```markdown
---
documentclass: article
lang: en-US
otherlangs: [de-DE]
---

English

\begin{german}[latesthyphen=true]
Deutsche
\end{german}
```
and get output like:
```latex
...
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,ngerman,main=english]{babel}
\else
  % load polyglossia as late as possible as it *could* call bidi if RTL lang (e.g. Hebrew or Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[variant=american]{english}
  \setotherlanguage[]{german}
\fi

...

English

\begin{german}[latesthyphen=true]
Deutsche
\end{german}
```
Now I change the input to
```markdown
---
documentclass: article
lang: en-US
---

English

::: {lang=de-DE}
Deutsche
:::
```
and get output :
```latex
...
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,ngerman,main=english]{babel}
\else
  % load polyglossia as late as possible as it *could* call bidi if RTL lang (e.g. Hebrew or Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[variant=american]{english}
  \setotherlanguage[]{german}
\fi

...

English

\begin{german}
Deutsche
\end{german}
```

So the question is how could I get `[latesthyphen=true]` back for `german`?

I tried to just change the `otherlangs: [de-DE]` to `polyglossia-otherlangs: [de-DE]` or `polyglossia-otherlangs: german` in my previous working input, but it doesn't work.

**Comment by mb21** [comment]
I guess you'll have to do your own template and put `\setotherlanguage[latesthyphen]{german}` in there instead of doing the `polyglossia-otherlangs`.

**Comment by qifei9** [comment]
@mb21, I got it. Many thank!

**Comment by jgm** [comment]
Keeping this issue open because we need to either make the latex writer check `otherlangs`, or change the documentation.
