### ISSUE TITLE
list of negated symbols whose commands are not in TeX by default

### ISSUE THREAD

**Issue by Konfekt** [jgm/pandoc#4078]
For example,
```tex
\nequiv
```
is not in TeX by default, but has to be defined by, say,
```
\newcommand{\nequiv}{\not\equiv}
```
Therefore, a document including say `$a \nequiv b` compiles fine to `HTML`, but the compiled TeX document does not compile to `pdf` but throws an error about the unknown command `\nequiv`.

It would be convenient if all of these command definitions were included in the preamble of the TeX document compiled from the markdown file.

**Comment by mb21** [comment]
What exactly do you mean with "all of these command definitions" ? There are hundreds of LaTeX packages and thousands of `\newcommand` conventions out there. Pandoc cannot possible support all.

**Comment by Konfekt** [comment]
More common commands, such as `\neq` are contained in TeX by default, but pandoc defines in `TexChar.hs` additional negated relations such as `\nequiv`. If they work in `HTML` for example, why not make them work in `TeX`, too? There is no package defining `\nequiv` that I am aware of.

**Comment by jgm** [comment]
TexChar.hs?  That's not part of pandoc.

+++ Konfekt [Nov 18 17 13:38 ]:

**Comment by Konfekt** [comment]
I am sorry, I do not know then how pandoc subsitutes `\nequiv` by the corresponding unicode symbol when generating `HTML`.

**Comment by jgm** [comment]
Try with `--pdf-engine=xelatex`.  Then the `unicode-math` package will be included, and this symbol will be defined.
(If pandoc < 2, `--latex-engine=xelatex`)

**Comment by Konfekt** [comment]
Ok, as `pdflatex` is still common and caused the issue, why is the `unicode-math` package not included by default?

**Comment by Konfekt** [comment]
Ok, this package only works for `luatex` and `xelatex`. It would still be useful to have at least a list of all custom TeX command of `pandoc` so that the `TeX` file compiled under `pandoc` compiles also under the most common pdf-engine `pdftex`.

**Comment by jgm** [comment]
You're welcome to compile such a list if you think it would
be useful, but this isn't a high priority for us.

+++ Konfekt [Nov 20 17 14:32 ]:

**Comment by Konfekt** [comment]
It catches the user off guard that math commands such as `\nequiv`  compile fine to `HTML` but not to`TeX`, at least if not additional packages and a different pdf-engine is used. Therefore, this should at least be mentioned in the documentation. I could do so.

A potential list is given by those commands that also appear in `/src/Text/Pandoc/Readers/Docx/TexChar.hs`  with a prepended `n`. 

As an aside, at this point, I do not understand that `TexChar.hs` is not part of `pandoc`, even though https://searchcode.com/codesearch/view/64337606/ lists it as such.

**Comment by jgm** [comment]
It was part of an old version.

+++ Konfekt [Nov 21 17 12:48 ]:
>   As an aside, at this point, I do not understand that TexChar.hs is not
>   part of pandoc, even though
>   [1]https://searchcode.com/codesearch/view/64337606/ lists it as such.

**Comment by Konfekt** [comment]
This is a list of negated commands
```tex
\napprox
\nasymp
\ncong
\neq
\nequiv
\nexists
\ngeq
\ngtr
\ngtrless
\ngtrsim
\nleftarrow
\nleftrightarrow
\nleq
\nless
\nlessgtr
\nlesssim
\nmid
\notasymp
\notbackslash
\notin
\notslash
\nparallel
\npolint
\nprec
\npreccurlyeq
\npreceq
\nrightarrow
\nsim
\nsime
\nsimeq
\nsqsubseteq
\nsqsupseteq
\nsubset
\nsubseteq
\nsucc
\nsucccurlyeq
\nsucceq
\nsupset
\nsupseteq
\ntriangleleft
\ntrianglelefteq
\ntriangleright
\ntrianglerighteq
```
However, there are others, for example `\Equiv` instead of `\equiv`. It would be nice if there is a unicode package for the standard `pdftex` latex-engine that defined all these unicode names not included in (AMS-)TeX by default.

**Comment by Konfekt** [comment]
I am sorry for the noise. It was the option `nosymbolsc` passed to the font `newtxmath` that undefined all negated TeX symbols. Without it, all of the above commands are defined.
