### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by shunconf** [jgm/pandoc#4079]
下载不下来啊  我下载win.msi的都下载不下路 压缩包也试过了 都不行啊

**Comment by mb21** [comment]
Not sure whether google translate got this through correctly...

But if you're having trouble downloading pandoc, it's probably due to the great firewall.

**Comment by mb21** [comment]
Try this WeTransfer link to `pandoc-2.0.2-windows.msi`:

https://we.tl/5V4j6yILl1
