### ISSUE TITLE
Provide convenience functions for working with lists

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#4081]
Operations on lists, like checking whether an element has a certain class, currently requires users to awkwardly iterate over the lists.  Working with lists should be made more convenient.

**Comment by jgm** [comment]
Would it make sense to export a `list` module, similar to `text`, with things like `reverse`, `filter`, and `map`?

Alternatively (or in addition), for the common case of checking a class, we could add a method on `Attr`, so you could do `el.attributes.has_class("foo")`.

**Comment by tarleb** [comment]
Maybe [penlight's List class](https://stevedonovan.github.io/Penlight/api/classes/pl.List.html) could be used. Penlight aims to be kind of a standard library in Lua.
I've yet to evaluate whether using it is feasible and desireable.

**Comment by jgm** [comment]
I'm reluctant to include penlight, it's kind of a big
library, isn't it? (by lua standards).  That's why I thought
of just exposing some Haskell list manipulation functions.

+++ Albert Krewinkel [Nov 19 17 21:27 ]:

**Comment by tarleb** [comment]
John MacFarlane <notifications@github.com> writes:

> I'm reluctant to include penlight, it's kind of a big
> library, isn't it? (by lua standards).

I thought it might be possible to include only the List module, but I
see now that it depends on other modules, pulling in a considerable
fraction of the rest of penlight. I agree that this would be too
heavy-weight.

> That's why I thought of just exposing some Haskell list manipulation
> functions.

Unfortunately, hslua isn't yet flexible enough to support function
polymorphism in an appropriate way: there is no general `LuaValue` type
as of now. We'd have to restrict the module functions to concrete values
like `String -> [String] -> Bool`; this seems highly impractical. Adding
a LuaValue type is on my todo list, but that list has become quite long
lately…

I guess I'd prefer if we wrote a small list module in lua instead. This
would come with the obvious downsides of having more lua code to test
and maintain, but maybe we could split it of into a separate library.
Maybe that's something that could go into the @pandoc organisation?

**Comment by jgm** [comment]
+++ Albert Krewinkel [Nov 20 17 21:44 ]:
>   I guess I'd prefer if we wrote a small list module in lua instead. This
>   would come with the obvious downsides of having more lua code to test
>   and maintain, but maybe we could split it of into a separate library.

Sounds okay to me.  But maybe this needs to go in the pandoc
repo, since we'll want this code to be made available to all
lua filters.

**Comment by tarleb** [comment]
Do you have a favorite list library that could serve as a template for the new module? I'd prefer a more functional approach (as in JavaScript's [`Array.prototype`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype)) than the python approach implemented in penlight.  Or should we just port the relevant `Data.List` functions to lua?
