### ISSUE TITLE
Issues with epub3 validation in 2.0.2

### ISSUE THREAD

**Issue by jamtur01** [jgm/pandoc#4082]
1. My content.opf includes the following lines:

```html
 <guide>
    <reference type="toc" title="TItle of Book" href="nav.xhtml" />
    <reference type="cover" title="Cover" href="cover.xhtml" />
  </guide>
```
When I epubcheck the outputted I see:

```
ERROR(RSC-007): /Users/james/src/pm/output/Title.epub/EPUB/content.opf(79,64): Referenced resource could not be found in the EPUB.
```
Line 79 is: `<reference type="cover" title="Cover" href="cover.xhtml" />` which I believe should read:

`<reference type="cover" title="Cover" href="text/cover.xhtml" />`

2. I see similar in `nav.html`.

```html
<a href="cover.xhtml" epub:type="cover">Cover</a>
```
epubcheck:

```
ERROR(RSC-007): /Users/james/src/pm/output/Title.epub/EPUB/nav.xhtml(21,47): Referenced resource could not be found in the EPUB.
```

This line should be: `<a href="text/cover.xhtml" epub:type="cover">Cover</a>`

**Comment by jamtur01** [comment]
Ah dupe of #4069.

**Comment by jgm** [comment]
I'll try to put out a new release soon that fixes this.

**Comment by jamtur01** [comment]
Thanks!
