### ISSUE TITLE
beamer “\alert” not recognized

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#4091]
pandoc does not seem to recognize the beamer command `\alert`.

From the beamer manual: “beamer offers the command `\alert`, which is used like `\emph` and, by default, typesets its argument in bright red.”

Example:

`echo '\alert{Foo bar}' | pandoc -f latex -t markdown`

Expected:

Either `Foo bar` or `*Foo bar*`

Actual:

(nothing)

**Comment by mb21** [comment]
Sounds a bit like the dreaded HTML `<marquee>` ;) But I suppose we could support it...
