### ISSUE TITLE
Pandoc 2.00 and LATEX special characters

### ISSUE THREAD

**Issue by erimpapova** [jgm/pandoc#4092]
The latest version of Pandoc (2.0.1.1) has very strict conditions for Latex special characters (# $ % & ~ _ ^ \ { }) that causes problems with parsing of these symbols. We’re forced to add ‘/’ symbol before every special character to get it parsed. For example, if we need to get $Sigma$ parsed then we need to have something like /$Sigma/$. So, will it be possible to have a special fork of 2.0.1.1 Pandoc version that doesn’t have such strict conditions for Latex special characters and so that they will be parsed as normal characters, not special ones?
Alternatively, the Pandoc version 1.19.2.1 was working fine for us, except of the https://github.com/jgm/pandoc/issues/3922 issue which has been fixed: https://github.com/jgm/texmath/commit/970a9c453d7f744e835cdea82f1db0d38371ae7c
So, a new fork which includes the Pandoc version 1.19.2.1 with the fix https://github.com/jgm/texmath/commit/970a9c453d7f744e835cdea82f1db0d38371ae7c will work for us as well.

Thank you.

**Comment by mb21** [comment]
Can you give a minimal example of input, pandoc command used, generated output, expected output?
