### ISSUE TITLE
Smart Ext: Wrong Double Quotes

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4093]
While converting from markdown to markdown (to cleanup source), smart produced closing double quotes in place of opening quotes:

```
("`#opt_`…")
```

became:

```
(”`#opt_`…”)
```

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information.

From [Contributing to pandoc](http://pandoc.org/CONTRIBUTING.html):

> Make sure you can reproduce the bug with the latest released version of pandoc
> (or, even better, the development version).
> 
> Your report should give detailed, *reproducible* instructions, including
> 
>   * the pandoc version (check using `pandoc -v`)
>   * the exact command line used
>   * the exact input used
>   * the output received
>   * the output you expected instead
> 
> A small test case (just a few lines) is ideal.  If your input is large,
> try to whittle it down to a *minimum working example*.


Please also search the (open *and* closed) issues to make sure the issue hasn't come up before.
Check the [User's Guide] and [FAQs] for anything relevant.
Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss).

[User's Guide]: http://pandoc.org/MANUAL.html
[FAQs]:  http://pandoc.org/faqs.html

**Comment by tajmone** [comment]
Sorry, I should have mentioned I'm using latest pandoc release: v2.0.3.

I didn't provide the full command because this occured in a complex toolchain (the point being that with pandoc v1.9 the quotes were correctly interpreted).

I've worked out this smallest viable example:

```
echo ("`test`") | pandoc -f gfm+smart -t gfm
```

... which will produce the wrong closing quote in place of an opening one:

```
(”`test`”)
```
It seems the problem is GFM-only, didn't reproduce with pandoc markdown.

**Comment by mb21** [comment]
Agreed, this is wrong (opening quote is `8221` instad of `8220`):

    $ echo '("`test`")' | pandoc -f gfm+smart -t native
    [Para [Str "(\8221",Code ("",[],[]) "test",Str "\8221)"]]

While this is correct:

    $ echo '"`test`"' | pandoc -f gfm+smart -t native 
    [Para [Str "\8220",Code ("",[],[]) "test",Str "\8221"]]

This is an upstream bug in the commonmark smart punctuation code, can even be reproduced in JS:

http://spec.commonmark.org/dingus/?text=wrong%3A%20(%22%60test%60%22)%0A%0Aright%3A%20%22%60test%60%22%0A%0Aright%3A%20(%22test%22)&smart=1

**Comment by jgm** [comment]
This now seems fixed with the new gfm/commonmark readers:
```
% pandoc -f gfm+smart -t native
("`test`") 
[Para [Str "(",Quoted DoubleQuote [Code ("",[],[]) "test"],Str ")"]]
```
