### ISSUE TITLE
Default Theme is Kate not Pygments

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4096]
**Pandoc v2.0.3**

Documentation mentions "pygments" as being the default style:

```
--highlight-style=STYLE|FILE
    Specifies the coloring style to be used in highlighted source code.
    Options are pygments (the default), kate, monochrome, breezeDark,
    espresso, zenburn, haddock, and tango.
```

But the command `pandoc --print-default-data-file default.theme` outputs the "kate" theme, not "pygments":

```json
{
    "metadata" : {
        "revision" : 1,
        "name" : "Default",
        "author" : "Kate Authors",
        "license" : "MIT",
        "read-only" : true
    },
    "text-styles": {
        "Normal" : {
            "text-color" : "#1f1c1b",
            "selected-text-color" : "#ffffff",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Keyword" : {
            "text-color" : "#1f1c1b",
            "selected-text-color" : "#ffffff",
            "bold" : true
        },
[...]
```

... pygments doesn't use the `"#1f1c1b` color for keywords, kate does.

**Comment by tajmone** [comment]
**NOTE** — I'm not sure if the above is a mistake or intended; my understanding is that `pandoc --print-default-data-file default.theme` should output a template file covering all the possible syntax elements, so that it might be used as a starting point to build a custom style.

As of now, the documentation suggests that the above command will output the default theme used by pandoc.

Maybe the metadata of the [`default.theme`](https://github.com/jgm/pandoc/blob/2.0.3/data/default.theme) file could be changed so that it's clearer that it's a template to build-on: 

```json
{
    "metadata" : {
        "revision" : 1,
        "name" : "Default",
        "author" : "Kate Authors",
        "license" : "MIT",
        "read-only" : true
    },
```

Also, does the current `default.theme` cover all possible skylighting syntax elements? This is important to build a theme that covers all possible language syntaxes. So far I haven't found any documentation listing and explaining all the syntax elements covered by skylighting — except by peeking at the source code.

It would be useful to add to pandoc documentation the full list of skylighting syntax elements, with some comments regarding their scope, and possibly also their HTML equivalent class names — it would make it easier to create custom CSS stylesheets, instead of using pandoc styles, for handling different styling for different languages in a same document.

**Comment by mb21** [comment]
The documentation is correct in saying that `pygments` is the default theme if none is specified. See [Options.hs](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Options.hs#L221) or compare the CSS in the output of `pandoc --highlight-style=pygments -s` and `pandoc -s` – it's the same colors.

I guess it's a bit confusing that `pandoc --print-default-data-file default.theme` outputs the `kate` theme then, and this might have been an accident. We should change the `data/default.theme` file then.

Not sure about your other questions... you've seen https://github.com/jgm/skylighting and the links at the bottom?

**Comment by tajmone** [comment]
Yes, then it's just a question of confusion as to what to expect from `pandoc --print-default-data-file default.theme`.

> Not sure about your other questions... you've seen https://github.com/jgm/skylighting and the links at the bottom?
 
... sorry for not being clear. What I meant is that pandoc documentation doesn't offer references on how to handle syntax highlighting in custom CSS. For example, I'm working on some Sass boilerplates for creating custom CSS that allow different styles for different langs:

- https://github.com/tajmone/pandoc-goodies/tree/master/skylighting-css

So far, the only way I've managed to work my way through the CSS classes required for the task has been to extract all the built-in styles' CSS from pandoc-created HTML5 docs; and by referencing the skylighting source files which I've linked above. A bit of a "hard way" to go about it.

It would be nice to have a document in the pandoc project which covers this topic (a markdwon file would be fine) — it's a topic which interests pandoc users directly, so it's worth including it in pandoc even if it really belongs to skylighting.

Syntax highlighters differ in behaviour, and anyone interested in creating custom CSS targeting pandoc-higlighted html docs needs to know basic things, like: Do elements nest into each other? How to handle embedded syntaxes (eg: CSS in hml docs)? So far I haven't found useful starters-info on such topics in pandoc documentation, nor in skylighting. 

As for the `default.theme`, what I'd expect from the output of `pandoc --print-default-data-file default.theme` is a reference file that makes it easy to build a custom Style — ie: it should cover all possible syntax highlighting tokens (I'm not sure if all built-in styles do, some are less detailed than others). Unfortunately JSON doesn't allow comments, otherwise it would have been easy to add instructions in comments.

The built-in styles' CSS output do have some useful comments explaining what skylighting token the classnames referr to, but you can't access the built-in styles' CSS except by actually converting a doc — for these reason I've manually extracted their CSS versions and published them:

- https://github.com/tajmone/pandoc-goodies/tree/master/skylighting-css/built-in-styles

Today I'm planning to add to my "pandoc-goodies" project some documentation covering the syntax tokens and their HTML classes counterparts. Hopefully, if it turns good and useful it might be reused in pandoc documentation.

**Comment by tajmone** [comment]
### Default Theme Unrelated Entries

As an example of the "default theme"  vs a "theme template" argument above, the [`default.theme`](https://github.com/jgm/pandoc/blob/9e78a9d/data/default.theme#L147) contains some keys which are specific to Kate editor (or other KDE tools that support syntax highlighting):

``` json
   },
    "editor-colors": {
        "background-color" : "#ffffff",
        "code-folding" : "#94caef",
        "bracket-matching" : "#ffff00",
        "current-line" : "#f8f7f6",
        "icon-border" : "#f0f0f0",
        "indentation-line" : "#d2d2d2",
        "line-numbers" : "#a0a0a0",
        "current-line-number" : "#1e1e1e",
        "mark-bookmark" : "#0000ff",
        "mark-breakpoint-active" : "#ff0000",
        "mark-breakpoint-reached" : "#ffff00",
        "mark-breakpoint-disabled" : "#ff00ff",
        "mark-execution" : "#a0a0a4",
        "mark-warning" : "#00ff00",
        "mark-error" : "#ff0000",
        "modified-lines" : "#fdbc4b",
        "replace-highlight" : "#00ff00",
        "saved-lines" : "#2ecc71",
        "search-highlight" : "#ffff00",
        "selection" : "#94caef",
        "separator" : "#898887",
        "spell-checking" : "#bf0303",
        "tab-marker" : "#d2d2d2",
        "template-background" : "#d6d2d0",
        "template-placeholder" : "#baf8ce",
        "template-focused-placeholder" : "#76da98",
        "template-read-only-placeholder" : "#f6e6e6",
        "word-wrap-marker" : "#ededed"
    }
}
```

... I'd think that these keys shouldn't affect how pandoc highlights code, since they are intended for editor GUI elements.

Pandoc documentation states that theme files:

> ... will be parsed as a KDE syntax highlighting theme and (if valid) used as the highlighting style.

... however, it's not clear how pandoc will establish if the theme is valid or not; but it would reasonable to think that the JSON keys-group `"editor-colors"` could be omitted in a theme file for pandoc, since it doesn't affect syntax highlighting in this context.

A "theme template" shouldn't present unnecessary JSON keys; whereas a default theme might --- ie: a theme might be an original KDE file, or it might be built for pandoc usage only, in the latter case not bothering with KDE editors' specific entries. 

Again, with all that I've been using pandoc on a daily base for years, and followed the change from Highlighting Kate to skylighting, I've always found it difficoult to get hold of documentation covering similar issues.

**Comment by tajmone** [comment]
### Theme Tests Results

I've managed to carry out some tests with `.theme` files. As it turns out, I was wrong about the `"editor-colors"` section: _some_ keys are actually used by Skylighting (eg: `"background-color"` for the background); but I've discovered that you can freely omit most of the keys.

The following custom theme I've created and tested works fine:

``` json
{
    "metadata" : {
        "revision" : 1,
        "name" : "Incomplete",
        "author" : "tajmone"
    },
    "text-styles": {
        "Normal" : {
            "text-color" : "#ff0000"
        },
        "Keyword" : {
            "text-color" : "#3333ff",
            "bold" : true
        }
   },
    "editor-colors": {
        "background-color" : "#003333"
    }
}
```

So, I think that it would be a good idea to reduce the contents of `default.theme` so that only entries which are actually used by pandoc/skylighting are presented. For example, the `"selected-text-color"` key (which is present in all text-styles) doesn't seem to have any effect on the highlighted syntax, even when selected.

Reducing `default.theme` to an example template makes, IMO, more sense. After all, most users will probably invoke the `pandoc --print-default-data-file default.theme` option to get hold of a file from which to start building their own theme. Presenting them with keys that don't affect the final output only adds a burden and confusion. 

We can reasonably argue that the `default.theme` file thus produced is meant for pandoc-usage only, and that there is no need to fulfill KDE standards here. If a user wants to resues a KDE syntax theme, he can just leave those extra keys there, since they don't do any harm. But building a theme from the `default.theme` is another story altogether, and the file should simplify the task.

**Comment by tajmone** [comment]
### Themes Documentation

Today I've written some documentation covering highlighting themes:

- [github.com/tajmone/pandoc-goodies/tree/master/skylighting-themes](https://github.com/tajmone/pandoc-goodies/tree/master/skylighting-themes)

I've done some local tests with `*.theme` files, and looked at skylighting source files, and managed to write a fairly decent page on the subject.

### Theme Boilerplate

I've also created a public domain theme boilerplate:

- [github.com/tajmone/pandoc-goodies/blob/master/skylighting-themes/boilerplate.theme](https://github.com/tajmone/pandoc-goodies/blob/master/skylighting-themes/boilerplate.theme)

This file contains only those JSON entries which are relevant to pandoc highlighting.

I hope these might help others who have faced the same problems I had to regarding themes and styles (and hopefully spare them hours of researching).

**Comment by jgm** [comment]
I agree that `default.theme` should be pared down to the things that will actually affect pandoc's highlighting.  Do you want to submit a PR?

The only fields used are `text-color`, `background-color`, `bold`, `italic`, and `underline`.

`strikethrough` has no effect.

**Comment by tajmone** [comment]
> `strikethrough` has no effect.

thanks, I'll fix my boiler plate file accordingly.

> Do you want to submit a PR?

I'd be appy to, I just wanted to be sure I got all the fields right.

For example, in the metadata section:

``` json
{
    "metadata" : {
        "revision" : 1,
        "name" : "boilerplate",
        "author" : "tajmone",
        "license" : "Unlicense",
        "read-only" : true
```

... what does `revision` stand for, the KDE standard of the theme format, or the current theme's revision? How should it be used? or should it be ignored/omitted?

Also, the `read-only` field: should it be omitted from the template? as it any use?

**Comment by tajmone** [comment]
### Print Default Style is Still Kate

    pandoc v2.0.5

> I guess it's a bit confusing that pandoc `--print-default-data-file default.theme` outputs the kate theme then, and this might have been an accident. We should change the `data/default.theme` file then.

I was comparing the output of `--print-default-data-file default.theme` with that of the built-in themes extracted via `--print-highlight-style`. Beside the differences in the resulting JSON contents (ie: data order, and differences in some fields), by looking at the actual color values it seems that `--print-default-data-file default.theme` still prints the Kate style (KDE JSON version).

As for the output of `--print-highlight-style`, the resulting JSON (adapted to pandoc needs) is much clearer and intuitive now. Well done.

**Comment by jgm** [comment]
+++ Tristano Ajmone [Dec 19 17 14:18 ]:
>  Print Default Style is Still Kate
>
>pandoc v2.0.5
>
>     I guess it's a bit confusing that pandoc --print-default-data-file
>     default.theme outputs the kate theme then, and this might have been
>     an accident. We should change the data/default.theme file then.

I'm just going to get rid of data/default.theme.  It's not
needed any more; it existed previously only to serve as an
example, and now you can just --print-highlight-style.

**Comment by aubertc** [comment]
Hi, @tajmone , where did the handy guide you wrote, that used to be at
https://github.com/tajmone/pandoc-goodies/tree/master/skylighting-themes
and that is referenced in this discussion go?

I mention it at
https://stackoverflow.com/a/47876166
and, as far as I know, this is still the most complete guide to writing your own json theme.

Thanks!

**Comment by tajmone** [comment]
Ciao @aubertc,

the guide is still there, I've just renamed the folders a couple of months ago to reorganize the repository structure:

https://github.com/tajmone/pandoc-goodies/tree/master/skylighting/themes

I've been contacted before for the same issue, and I really wonder why GitHub gives a 404 error on a missing file or folder instead of redirecting to the repository main page — people get the impression that the whole repository was shut down, whereas it's just a missing file error due to structural changes. I find this 404 error very confusing and misleading.

> I mention it at
> https://stackoverflow.com/a/47876166

Any change you could amend the link in the StackOverflow thread? Or add a comment next to it with the new link?

> and, as far as I know, this is still the most complete guide to writing your own json theme.

Glad to know that it's helpful!

**Comment by aubertc** [comment]
> Ciao @aubertc,

Hey @tajmone 

> https://github.com/tajmone/pandoc-goodies/tree/master/skylighting/themes

Ok, thanks. I'm glad you're still working on it!

> I find this 404 error very confusing and misleading.

It is. And I could not find your rep. with any of the "obvious" keywords either…


> Any change you could amend the link in the StackOverflow thread? 

Done :-)
