### ISSUE TITLE
wrong highlighting with numberLines class

### ISSUE THREAD

**Issue by johnd0e** [jgm/pandoc#4103]
With numberLines variables names get wrong pale color.

See example here:

http://farmanager.is-best.net/highlight/v2/skylighting.pygments.html

(Compare the same code block with numbers and without them)

**Comment by jgm** [comment]
I see this in the highlighting CSS:

    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; color: #aaaaaa;  padding-left: 4px; }

Note: this is added by skylighting.  I'm not sure why the
'color: #aaaaaa' is in there, but it seems to be the
problem.  This is something we can change easily in
jgm/skylighting, I think.
