### ISSUE TITLE
Lua module loading

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#4112]
The *pandoc* and *pandoc.List* Lua modules are currently loaded from files `pandoc` and `List` in the datadir, respectively. This allows to overwrite the default modules by adding files of the same name to their datadir.

I'd like to discuss a different behavior implemented in my branch lua-module-refactor. It integrates pandoc's module loading into the Lua interpreter's module loading mechanism.  This has the effect that Lua, when searching for a module, will search `LUA_PATH` before falling back to files in datadir and lastly to the baked-in scripts.

The advantages I see are consistency, and that we could use tools like luarocks to publish new versions of the modules.

The downsite is that the default `LUA_PATH` includes the current working directory, so pandoc would always try to load `pandoc.lua` and `pandoc.List.lua` from the current directory.  This might be quite unexpected.

A compromise could be to only do this for pure Lua modules like *pandoc.List* for which the downsites seem less relevant.  Is this a good idea or should we just keep the current behavior?

**Comment by jgm** [comment]
I'm not sure.  I'll defer to your judgment on this.
You might also ask on pandoc-discuss.

**Comment by tarleb** [comment]
Thank you for the feedback. After thinking about it some more, I now seriously dislike the solution described above. Below is what I came up with instead:

I'd like to keep the current behavior (getting pandoc modules from datadir only) as default. We can still plug into Lua's module loading mechanism to do this. We can use an additional file `init.lua` to load all default dependencies like the `pandoc` module. Since this file can be overwritten by placing a file of the same name in the datadir, users who need the flexibility can change the way modules are loaded by configuring the module system in their custom init file.  This should avoid any weird and unexpected behavior while still offering enough flexibility.

I'll implement it that way unless you have concerns.

**Comment by jgm** [comment]
Sounds good.

+++ Albert Krewinkel [Dec 03 17 04:46 ]:
