### ISSUE TITLE
Pandoc stripping custom classes. [markdown with html to gfm]

### ISSUE THREAD

**Issue by HaoZeke** [jgm/pandoc#4113]
# Bug description

As markdown supports pure html, it is reasonable to expect that conversions between markdown (pandoc) to markdown (gfm) should include all classes which usually show up in the HTML output.

However, the classes are stripped from the gfm output instead.
This is more baffling with explicit html elements which really shouldn't be stripped from the output.

Version details:

```bash
pandoc --version
pandoc 2.0.1.1
Compiled with pandoc-types 1.17.2, texmath 0.10, skylighting 0.4.3.2
Default user data directory: /home/haozeke/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

# Minimum example:

Input (a file called bug.md containing the following) :-

**(A)**
```markdown
# Hi

::::{.bug}
I am a bug.
::::

````

OR

**(B)**
```markdown
# Hi

<div class="bug">
I am a bug.  
</div>
```

# Commands

```bash
# GFM
pandoc -f markdown bug.md -t gfm

# HTML
pandoc -f markdown bug.md -t html
```

# Output

Output [HTML] :-

```html
<h1 id="hi">Hi</h1>
<div class="bug">
<p>I am a bug.</p>
</div>
```

Expected GFM Output :-

```markdown
# Hi

<div class="bug">
I am a bug.
</div>
```

Actual GFM Output :-

```markdown
# Hi

I am a bug.
```

## Context

It's a minor annoyance in the trivial example above, however this bug makes it nigh impossible to convert from pandoc markdown to gfm and still use pandoc-citeproc, which adds ids and classes for every reference.

The above bug is also true for ids.

(ie. no id attributes are generated)

### Update

**(B)** As pointed out by @mb21, using `pandoc -f markdown-native_divs -t gfm` fixes the output for this case.

**(A)** does not work as expected with this setting.

**Comment by mb21** [comment]
Try:

    pandoc -f markdown-native_divs -t gfm

the `-native_divs` is needed to convert the divs to raw HTML fragments instead of pandoc native div elements.

**Comment by HaoZeke** [comment]
That fixes it for the case where the input explicitly has div elements...

However the native ::::{.bug} syntax is still not rendered correctly..

**Comment by mb21** [comment]
Indeed, the following is probably a bug:

    $ echo '::: .bug\nfoo\n:::' | pandoc -f markdown-native_divs -t native
    [Div ("",[".bug"],[])
      [Para [Str "foo"]]]

**Comment by HaoZeke** [comment]
Yup, feels more like a bug than a filter use case..

**Comment by jgm** [comment]
I think I can fix that, so native divs will generate HTML
div tags in gfm output.

+++ Rohit Goswami [Dec 03 17 04:45 ]:

**Comment by jgm** [comment]
I've added some text.

+++ Mauro Bieg [Dec 04 17 09:30 ]:
