### ISSUE TITLE
Org to PDF: \textcolor does not work

### ISSUE THREAD

**Issue by arumoy-shome** [jgm/pandoc#4114]
**Pandoc version**

```
❯ pandoc -v                                                                                 
pandoc 2.0.1.1
Compiled with pandoc-types 1.17.2, texmath 0.10, skylighting 0.4.3.2
Default user data directory: /Users/aru/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

I am trying to convert an org file into a PDF. Following the first answer on [this post](https://stackoverflow.com/questions/29067541/rmarkdown-how-to-change-the-font-color), I used the `\textcolor` command in a **markdown** file to generate text with a specific color.

**exact text used in conversion**

```latex
\textcolor{red}{*}
```

**command used for conversion**

```sh
pandoc log.md -f markdown -t latex --variable linkcolor=cyan -o exports/log.pdf
```

This works fine and generates the following output

![screen shot 2017-12-03 at 4 09 52 pm](https://user-images.githubusercontent.com/6236828/33529865-7b8a9400-d844-11e7-9820-0ea4238f5515.png)

However, when I use the same text in an **org** file, and run the above command (using an org file now) I get the following output

![screen shot 2017-12-03 at 4 10 17 pm](https://user-images.githubusercontent.com/6236828/33529884-9ebd16fa-d844-11e7-972f-2dec1660a4fe.png)

Please let me know if I can provide any further information or if there is any other command I ought to use when converting org to PDF in order to get the same functionality?

**Comment by mb21** [comment]
So the following should be picked up by the org reader as raw tex?

    $ echo -E '\textcolor{red}{*}' | pandoc -f org -t native
    [Para [Span ("",[],[("style","color: red")]) [Str "*"]]]

**Comment by tarleb** [comment]
Related issue: #3047.

As a work-around, you can write `@@latex:\textcolor{red}{*}@@` to force pandoc to pass the command to LaTeX.

**Comment by arumoy-shome** [comment]
@tarleb just did a quick check and the work around doesn't work for me. I don't even see the `*` anymore.

**Comment by tarleb** [comment]
Arumoy Shome <notifications@github.com> writes:

> @tarleb just did a quick check and the work around doesn't work for me. I don't even see the * anymore.

How did your quick check look? This works for me:

echo '@@latex:\\textcolor{red}{*}@@' | \
  pandoc -f org -t latex --variable linkcolor:cyan -o test.pdf

**Comment by arumoy-shome** [comment]
This works! Previously I forgot to pass in the `--variable` flag. Thanks for your help @tarleb. 😊
