### ISSUE TITLE
Amazon KDP won't import pandoc -> epub any more

### ISSUE THREAD

**Issue by incredion** [jgm/pandoc#4115]
Amazon won't import any of these files since I upgraded pandoc to 2.x

epub2
epub Validator says: epub is ok.
Sigil epub Validation says: OPS document is reachable but not present in the OPF. OEBPS/Text/nav.xhtml

epub3
epub validator says: epub not ok, errors: "Error while parsing file 'element "dd" not allowed yet;" etc.

**Comment by mb21** [comment]
exactly what version are you on? can you try with the latest released? also, what input did you use/is causing the validation error?

**Comment by jgm** [comment]
2.0.4, released yesterday, contains some changes that may affect pub validity, so please try with that version, and if it still fails, give us some input and the exact command line that can reproduce the problem.

**Comment by mb21** [comment]
Using http://validator.idpf.org, the following is valid with pandoc 2.0.5

    echo '# foo' | pandoc -o test.epub -M title=test

Thus closing unless we get a reproducible example.
