### ISSUE TITLE
Pass language to latex lstlisting environment when use `--listings`

### ISSUE THREAD

**Issue by ProgramFan** [jgm/pandoc#4116]
The current output of the latex writer with the `--listings` option drops the language of a code block, and makes it impossible to color code blocks with different languages in the same document.

Hope this can be fixed. I hope to help but I don't yet understand haskell. :(

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information.

From [Contributing to pandoc](http://pandoc.org/CONTRIBUTING.html):

> Make sure you can reproduce the bug with the latest released version of pandoc
> (or, even better, the development version).
> 
> Your report should give detailed, *reproducible* instructions, including
> 
>   * the pandoc version (check using `pandoc -v`)
>   * the exact command line used
>   * the exact input used
>   * the output received
>   * the output you expected instead
> 
> A small test case (just a few lines) is ideal.  If your input is large,
> try to whittle it down to a *minimum working example*.


Please also search the (open *and* closed) issues to make sure the issue hasn't come up before.
Check the [User's Guide] and [FAQs] for anything relevant.
Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss).

[User's Guide]: http://pandoc.org/MANUAL.html
[FAQs]:  http://pandoc.org/faqs.html

**Comment by ProgramFan** [comment]
Pandoc version: 2.0.3 from homebrew

Command line: `pandoc -f markdown -o 1.tex --template eisvogel Test.md --listings`

Markdown file:

    ```cmake
    cmake_minimun_required(VERSION 3.0)
    project(Test CXX C Fortran)
   ```

Resulant tex file snippet:

```latex
\begin{lstlisting}
cmake_minimum_required(VERSION 3.0)
project(Test CXX C Fortran)
\end{lstlisting}
```

**Comment by ProgramFan** [comment]
The language settings are not there.

**Comment by jgm** [comment]
That's because listings doesn't support cmake.
Only supported language names are passed through (sometimes
after being converted to a form listings likes).

+++ Zhang YANG [Dec 05 17 01:04 ]:

**Comment by jgm** [comment]
If you try with `c`, you'll see that supported languages are passed through.

**Comment by ProgramFan** [comment]
Indeed. Why? Shouldn't it be possible to support any languages passed in?

**Comment by ProgramFan** [comment]
Anyway, the built-in highlighter supports cmake.

**Comment by ProgramFan** [comment]
Can #4117 would be a proper alternative to address this issue?

**Comment by jgm** [comment]
+++ Zhang YANG [Dec 04 17 17:20 ]:
>   Indeed. Why? Shouldn't it be possible to support any languages passed
>   in?

The listings package only supports certain languages.
And the names of these languages for listings are generally
different from our normal ones, so we have to do a
conversion.  This is a limitation in listings, mostly.

**Comment by sruffell** [comment]
I'm using the listing package with pandoc. I have used \lstnewenvironment to define a new language, but I've not yet determined how to get pandoc to use the newly defined environment.

Is this something that should be possible?

**Comment by jgm** [comment]
No that's not possible.

**Comment by vcapra1** [comment]
Why is this impossible?  I'd like to use listings with Rust, but it's not working.  If all pandoc is doing is converting something like 

<pre>```c</pre>

into 

<pre>\begin{lstlisting}[language=C]</pre>

Then why can't it convert this:

<pre>```rust</pre>

into 

<pre>\begin{lstlisting}[language=Rust]</pre>

and just _assume_ Rust exists?  Then it's up to the user to make sure it's defined somewhere.  That way, if I use a package like listings-rust, it will work.

**Comment by jgm** [comment]
Of course it would be possible to treat (the first?) class as a language name if none of the classes match a supported listings name, and hope that the user will define an appropriate lstnewenvironment.  That would mean that pandoc's latex output will cause an error if the special environment isn't defined, instead of just producing generic listings output.  I can see some people preferring the current approach, some the alternative.

A safer approach might be to look for a `listings-language` attribute (or maybe just `language`) and use that if found.  One could use a filter to add that if certain classes are present.

**Comment by sruffell** [comment]
There may be a better way, but I ended up using the following lua-filter to change ` ```json ` code blocks into raw latex blocks that set the language explicitly. Then I have the json language I defined in my template file.

```lua
local function CodeBlock (elem)
    if elem.c[1][2][1] == "json" then
        return pandoc.RawBlock("latex", "\n\\begin{lstlisting}[language=json]\n"..elem.text.."\n\\end{lstlisting}\n")
    else
        return elem
    end
end

return { { CodeBlock = CodeBlock } }
```

**Comment by jgm** [comment]
Good solution!

**Comment by zatarain** [comment]
> There may be a better way, but I ended up using the following lua-filter to change `` ```json `` code blocks into raw latex blocks that set the language explicitly. Then I have the json language I defined in my template file.
> 
> ```lua
> local function CodeBlock (elem)
>     if elem.c[1][2][1] == "json" then
>         return pandoc.RawBlock("latex", "\n\\begin{lstlisting}[language=json]\n"..elem.text.."\n\\end{lstlisting}\n")
>     else
>         return elem
>     end
> end
> 
> return { { CodeBlock = CodeBlock } }
> ```

When I saw this, I was so happy, but then I got sad an annoyed :( I mean, it works but for beamer when a code listing is added to a frame, the frame should be fragile.

**Comment by zatarain** [comment]
Following workaround seems to work (I founded in [pandoc/lua-filters repository](https://github.com/pandoc/lua-filters/blob/master/minted/minted.lua)):
```lua
-- Override code blocks to use \begin{lstlisting}[language=algorithm]...\end{lstlisting}
-- for beamer/latex writers when ```algorithm is used due to following unresolved issue:
-- https://github.com/jgm/pandoc/issues/4116
local function CodeBlock(element)
    if element.c[1][2][1] == "algorithm" then
        return pandoc.RawBlock("latex", "\n\\begin{lstlisting}[language=algorithm]\n"..element.text.."\n\\end{lstlisting}\n")
    else
        return element
    end
end

-- Override headers to make all beamer frames fragile, since any frane with lstlisting
-- environments will halt compilation if the frame is not marked as fragile.
function Header(element)
	if FORMAT == 'beamer' then
		-- Check first that 'fragile' is not already present.
		local has_fragile = false
		for _, val in ipairs(element.classes) do
			if val == 'fragile' then
				has_fragile = true
				break
			end
		end

		-- If not found, add fragile to the list of classes.
		if not has_fragile then
			table.insert(element.classes, 'fragile')
		end

		-- NOTE: pass the remaining work to pandoc, noting that 2.5 and below
		-- may duplicate the 'fragile' specifier.  Duplicated fragile does *not*
		-- cause compile errors.
		return element
	end
end
return {
	{ CodeBlock = CodeBlock },
	{ Header = Header }
}
```

However, I don't like the idea to mark all the frames with fragile :/

**Comment by rgevrek** [comment]
Just for all of those, who are trying to make this work for pandoc >= 2.16 and getting the error `attempt to index a nil value (field 'c')`:
`element.c[1][2][1]` shall be replaced by `elem.classes[1]` to continue work with newer versions.

**Comment by vupiggy** [comment]
There is a workaround that is a bit ugly, but working, saying you don't want to bother with programming.
```
 ```{.Rust language=Rust}
```
The keyval `language=Rust` will be added "as is" into the generated LaTeX code.

**Comment by markshevchenko** [comment]
> There is a workaround that is a bit ugly, but working, saying you don't want to bother with programming.
> 
> ```
>  ```{.Rust language=Rust}
> ```
> 
> The keyval `language=Rust` will be added "as is" into the generated LaTeX code.

My solution is
```
  ```rust{language=Rust}
  // Rust code here
  ```
```

It's translated to HTML `<code class="language-rust{language=Rust}">` and it's worked correctly.
Also it's translated to TeX `\begin{lstlisting}[language=Rust]`.
