### ISSUE TITLE
indent: True —> seems to mess up reference list

### ISSUE THREAD

**Issue by GandalfSaxe** [jgm/pandoc#4118]
If I use:
`indent: True`
In the YAML metadata, I get the paragraph indentation that I want, however the references goes 

looking like this:
![image](https://user-images.githubusercontent.com/12127864/33565023-440e7108-d91c-11e7-989d-91e5b41f1e2f.png)

to looking like this:
![image](https://user-images.githubusercontent.com/12127864/33564968-224ee66a-d91c-11e7-87c7-5aa74767d42b.png)

Is this intentional? Shouldn't there be indentation exception for the reference list?
How can I retain the paragraph indentation but not mess up the reference list?

**Comment by jgm** [comment]
Assuming you're targeting PDF, put some raw LaTeX before the references section.

```
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
```

By the way, as CONTRIBUTING.md says, this tracker is for bug reports, not questions. Questions should go to pandoc-discuss.  So, closing this.
