### ISSUE TITLE
Consider removing overlapping instances

### ISSUE THREAD

**Issue by treeowl** [jgm/pandoc#4122]
`PandocMonad` has a very general instance and one for `ParsecT` that overlaps it. This can be avoided using the `DefaultSignatures` extension. If you make the `MonadTrans` method implementations defaults, then you can write empty instance declarations for the usual transformers and a custom one for `ParsecT`.

**Comment by jgm** [comment]
Not sure I understand fully -- want to make a PR?

Caveat: it needs to work with ghc versions back to 7.8.x; I don't know when `DefaultSignatures` was introduced.

**Comment by treeowl** [comment]
I believe it's been around at least since 7.2, so I think that's fine. I'll open a PR; it's not a big deal. TBH, I don't really like `DefaultSignatures` either, but I dislike it much less than I dislike overlapping instances.

**Comment by jgm** [comment]
Thanks for the PR, that helps me understand what is involved.

I do see the downside you mention about the need for orphan instances if people want their fancy stacks to be instances of PandocMonad.  That seems to me a serious concern.  And I'm not sure what is gained in return.  We avoid a use of UndecidableInstances, but this use doesn't cause any obvious problems.  Can you explain what the real advantage of this change would be?
