### ISSUE TITLE
Allow raw XML processing instructions in Markdown

### ISSUE THREAD

**Issue by getreu** [jgm/pandoc#4125]
> Markdown allows you to insert raw HTML (or DocBook) anywhere in a document (except verbatim contexts, where <, >, and & are interpreted literally). (Technically this is not an extension, since standard Markdown allows it, but it has been made an extension so that it can be disabled if desired.)
The raw HTML is passed through unchanged in HTML, S5, Slidy, Slideous, DZSlides, EPUB, Markdown, Emacs Org mode, and Textile output, and suppressed in other formats.

I need to insert XML tags like `<?asciidoc-toc?>` or `<?asciidoc-numbered?>` in my docbook output. Unfortunately this does not work yet. They are treated as regular text and not passed through.

Maybe this feature can be enabled for reStructuredText (and other markup-languages) as well?

**Comment by mb21** [comment]
`<?asciidoc-toc?>` is not an XML tag. (What exactly do you hope to achieve with having `<?asciidoc-toc?>` inside docbook output?)

However, you can embed any raw format: see http://pandoc.org/MANUAL.html#generic-raw-attribute

For questions, please ask on pandoc-discuss.

**Comment by jgm** [comment]
`<?asciidoc-toc?>` is a valid XML processing instruction.
See e.g. http://doccookbook.sourceforge.net/html/en/dbc.common.pi.html

I agree that we should pass these through as raw html.

**Comment by jgm** [comment]
PS. You can include raw xml in reStructuredText, but you have to use the proper syntax for it.
(`raw` directive or interpreted text role)

**Comment by getreu** [comment]
Thank you @jgm and @mb21 !

@mb21  
> What exactly do you hope to achieve with having <?asciidoc-toc?> inside docbook output?

I am using the `asciidoctor-fopub` toolchain for processing docbook5. For example, the above is a switch to include a table of contents.

I have another issue and question: I need to place theses switches before and outside the `<book>` tag which contains all content. Is there a way of doing so?

**Comment by mb21** [comment]
@getreu sorry, I didn't think of XML processing instructions.

> I need to place theses switches before and outside

You can modify your [template](http://pandoc.org/MANUAL.html#templates), from `pandoc -D docbook`

**Comment by jgm** [comment]
You can use --include-before-body=FILE to include them, or
use a custom template.

+++ Jens Getreu [Dec 07 17 07:08 ]:
