### ISSUE TITLE
BUG?: Pandoc disrespects lists when converting from markdown to docx

### ISSUE THREAD

**Issue by IgnusG** [jgm/pandoc#4126]
Input file:
```markdown
1. This should be
2. a list
```
Output document:
![deepinscreenshot_select-area_20171206122440](https://user-images.githubusercontent.com/6438760/33659601-0add332c-da81-11e7-863a-d7702e5f58bc.png)

Conversion command:
`pandoc -o test.md -f markdown -t docx test.docx`
Tried with `-f markdown_strict` and github's markdown as well ... without luck

### Versions
Pandoc 2.0.3

**Comment by KurtPfeifle** [comment]
A screenshot does not "proof" anything.
It does not even proof that it is Word (*Microsoft* Word) which opened the resulting *\.docx*...   :-)

I would check my output with *LibreOffice* as well.
A very fast way to do so is using one of the AppImage packages from here: 

* http://libreoffice.soluzioniopen.com/index.php/pre-releases/
* http://libreoffice.soluzioniopen.com/index.php/daily-version/
* http://libreoffice.soluzioniopen.com/index.php/old-versions/
* http://libreoffice.soluzioniopen.com/index.php/stable-2/

Finally, should this bug really show itself when you test with other viewers which should be able to display that docx: if you want to get a real evaluation of the problem, provide a link to the real .docx.

----

<sub>(**P.S.:** I also love Deepin Linux <3 !)</sub>

**Comment by mb21** [comment]
You mixed up the input and output files, should be:

    pandoc -o test.docx -f markdown -t docx test.md

Please use pandoc-discuss to ask questions.
