### ISSUE TITLE
Enable --extract-media by default for docx to markdown

### ISSUE THREAD

**Issue by Shahor** [jgm/pandoc#4127]
# Versions

`$> pandoc -v`

> pandoc 2.0.4
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.4.4.1
Default user data directory: /Users/alexandregaudencio/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

# Files used

This [docx file](https://www.dropbox.com/s/qwiky0otxqz0eqa/Lesson%20plan.docx?dl=1) 

# Command used

`pandoc -f docx -t markdown Lesson\ plan.docx`

# Result

```markdown
![Placeholder image](media/image4.png){width="3.8854166666666665in"
height="2.0754604111986in"}

[]{#_az97se5ul39q .anchor}Math -- 1st Period

[]{#_ws7mb2zihyzt .anchor}Lesson Plan

**Teacher**: Ms. Writer

**Date:** 09/04/20XX

Overview & Purpose
==================

Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
volutpat.

Education Standards
===================

1.  Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

2.  Sed mollis aliquam nibh.

3.  Pellentesque pellentesque dictum urna.

Objectives
==========

1.  Vivamus gravida lorem vel neque pulvinar bibendum.

2.  Aenean vestibulum odio faucibus sapien.

3.  Pellentesque accumsan auctor tortor.

Materials Needed
================

1.  Pellentesque (30)

2.  Ut ullamcorper ultricies est (5)

Verification
============

*Steps to check for student understanding*

1.  Vivamus ultrices eros nec lectus interdum condimentum.

2.  Cras vel felis a leo pretium pulvinar.

3.  Curabitur tincidunt elementum ante

Activity
========

*Describe activity that will reinforce the lesson*

Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
volutpat.

+--------------------+--------+------------------------+--------+
| zib                | zob    | plop                   | lala   |
+====================+========+========================+========+
| Cell 1             | Cell 2 | Cell 3                 | Cell 4 |
+--------------------+--------+------------------------+--------+
| -   List in table  |        | Previous cell is empty | lel    |
|                    |        |                        |        |
| -   Second element |        |                        |        |
+--------------------+--------+------------------------+--------+
|                    |        |                        |        |
+--------------------+--------+------------------------+--------+

![page break](media/image6.png){width="3.0088976377952754in"
height="0.3072922134733158in"}

```

# Expected

- Either the images get auto extracted (it won't happen unless `--extract-media` is used as well)
- Provide an option to embed images in base64 into the markdown

# Result 

We get image blocks that will display a broken image since it can't be accessed.

**Comment by Shahor** [comment]
I saw that this can be done with a filter script, but I think it would be nice to have one of the proposed solutions active by default. 

The current default ends up being unusable.

**Comment by mb21** [comment]
So what you are proposing is to make `--extract-media` enabled by default?

I think this wasn't done because people might find it annoying if their working directory is being cluttered with image files when all they wanted was the text in the word file...

**Comment by Shahor** [comment]
We're kind of in the middle right now since: 

- We extract the image blocks
- The Image blocks are all broken by default since:
   - images are not extracted
   - Images are not converted to base64

**Comment by jgm** [comment]
I don't understand this bug report.  It sounds as if you want `--extract-media DIR`.  We're not going to enable that by default, but it's not hard to type.  If you use that, do you get an acceptable result?

**Comment by Shahor** [comment]
@jgm It's not about it being hard to type, it's about the conversion failing. 

By default when converting from docx (and probably other formats) to markdown we lose images in the process.

I know that medias can be extracted with that option, I read the documentation. The question though is why having a part of the document conversion failing by default ok?

**Comment by jgm** [comment]
+++ Alexandre Gaudencio [Dec 07 17 00:53 ]:
>   I know that medias can be extracted with that option, I read the
>   documentation. The question though is why having a part of the document
>   conversion failing by default ok?

By default pandoc does not create any files that have not been
specifically requested by the user.  We want to keep this
guarantee.  If you want the media files from the docx, you
need to request them explicitly, and specify where they are
to be put on the file system, using --extract-media.

**Comment by Shahor** [comment]
I understand, thank you for the explanation :)

**Comment by alphaCTzo7G** [comment]
I would actually prefer that the media be extracted into a specific folder in the same working directory by default and links to the images/media in those directories be placed in the markdown file.

It would be more inituitive if this is the default behavior when converting between docx and markdown and vice-versa.

**Comment by jgm** [comment]
It's a basic principle that we don't write files unless
we're explicitly told to.

+++ alphaCTzo7G [Mar 05 18 20:04 ]:
