### ISSUE TITLE
recent versions of pandoc fail behind proxy

### ISSUE THREAD

**Issue by ldfreight** [jgm/pandoc#4131]
I am using pandoc (through [rmarkdown][1]) to generate html dashboards.

I am also behind a company proxy, which I setup in R through 

    Sys.setenv(http_proxy   = "IP.IP.IP.IP:PORT")
    Sys.setenv(https_proxy  = "IP.IP.IP.IP:PORT")
    Sys.setenv(ftp_proxy    = "IP.IP.IP.IP:PORT")

I was using pandoc 1.17.2 until I decided to upgrade recently to 1.19.2.1

Since then I get an error:
```
> "//path/to/pandoc/pandoc-1.19.2.1/pandoc" +RTS -K512m -RTS
> dashboard.utf8.md --to html --from
> markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
> --output dashboard.html --email-obfuscation none --self-contained --standalone --section-divs --template "\\path\to\library\lib\SHARED~2\FLEXDA~1\RMARKD~1\TEMPLA~1\FLEX_D~1\RESOUR~1\DEFAUL~1.HTM"
> --variable "theme:cosmo" --include-in-header "AppData\Local\Temp\RtmpKEt5a0\rmarkdown-str3b6c39ce6996.html"
> --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
> --include-in-header "AppData\Local\Temp\RtmpKEt5a0\file3b6c55963b3ehtml"
> --highlight-style pygments --include-before-body "\AppData\Local\Temp\RtmpKEt5a0\file3b6c75e8bca.html"
> --include-after-body "\AppData\Local\Temp\RtmpKEt5a0\file3b6c1c117c0d.html" 
> Could not fetch
> /15477F~1.IT/Libs/R/RWORKI~1/lib/SHARED~2/RMARKD~2/rmd/h/JQUERY~1.3/JQUERY~1.JS
> InvalidUrlException ""IP.IP.IP.IP:PORT" "Invalid URL" Error: pandoc
> document conversion failed with error 61
```

I have also tried with most recent version of pandoc 2.0.4 (fails with same error), then I tried to revert back to pandoc 1.17.2 and it worked again.

is it a known bug in pandoc?

  [1]: http://rmarkdown.rstudio.com/

**Comment by mb21** [comment]
Not sure about rMarkdown (ask them), but in plain pandoc should support the proxy, on: https://github.com/jgm/pandoc/blob/6a1476e7e26b603bb69112a2666c47ac883ee36f/src/Text/Pandoc/Class.hs#L496

Can you try with plain plandoc 2.0.4 on the command line?

**Comment by jgm** [comment]
Just checking that `"IP.IP.IP.IP:PORT"` is a placeholder you added?  You need an actual IP address and port number here, not the literal string `"IP.IP.IP.IP:PORT"`.

Assuming it's just a placeholder, the best way to diagnose this is to use pandoc on the command line.  Try stripping away some of the extra stuff you have (e.g. mathjax and the header includes). Note that the manual says that mathjax doesn't work with `--self-contained` -- this may be a problem in rmarkdown, if it's trying to make this work.

You should be able to isolate the problem more precisely, and then we can offer more help.

**Comment by mb21** [comment]
Closing this unless we get more info...

**Comment by ximeg** [comment]
Hi, I also get a similar error with pandoc 1.19.2.1. My markdown code in the file `report.md` is
`![sample image](http://imgs.xkcd.com/comics/is_it_worth_the_time.png)`

```
$ pandoc -s --verbose --self-contained report.md -o report.html
pandoc: Could not fetch http://imgs.xkcd.com/comics/is_it_worth_the_time.png
InvalidUrlException "proxy.jenoptik.corp:8080" "Invalid scheme"
```

However, if I use `wget`, I can download the very same image through the very same proxy:
```
$ wget http://imgs.xkcd.com/comics/is_it_worth_the_time.png
--2018-06-12 11:13:53--  http://imgs.xkcd.com/comics/is_it_worth_the_time.png
Resolving proxy.jenoptik.corp (proxy.jenoptik.corp)... 10.110.15.6
Connecting to proxy.jenoptik.corp (proxy.jenoptik.corp)|10.110.15.6|:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 64050 (63K) [image/png]
Saving to: ‘is_it_worth_the_time.png’
```

I would appreciate any hints

**Comment by mb21** [comment]
@ximeg try upgrading to the newest pandoc

**Comment by ximeg** [comment]
@mb21 It's a good point, I was actually running the latest pandoc available in Ubuntu... But it's still very old. So I updated to pandoc 2.2.1, but this did not help - still getting the same error message `"Invalid scheme"`.

**Comment by mb21** [comment]
That's odd. Works for me with pandoc 2.2.1 on macOS. Which exact command are you using?

**Comment by ximeg** [comment]
@mb21, thanks for the answer. In my case this is

```
$ echo '![](http://via.placeholder.com/350x150)' | /usr/bin/pandoc -
s --self-contained > test.html
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'Untitled'
Could not fetch http://via.placeholder.com/350x150
InvalidUrlException "proxy.jenoptik.corp:8080" "Invalid scheme"
```

```
$ /usr/bin/pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
Default user data directory: /home/ximeg/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment]
What's the result of `echo $http_proxy` ?

**Comment by ximeg** [comment]
```
$  echo $http_proxy
proxy.jenoptik.corp:8080
```
Looks to be correct

**Comment by jgm** [comment]
Works fine for me. Looks like maybe your computer is
behind a proxy that is interfering.

**Comment by jgm** [comment]
John MacFarlane <jgm@berkeley.edu> writes:

Sorry, I didn't read all the context -- I see that
this is precisely about using pandoc behind a proxy.

> Works fine for me. Looks like maybe your computer is
> behind a proxy that is interfering.

**Comment by jgm** [comment]
It looks like maybe `http_proxy` is expected to include a scheme?
Try setting it to `http://proxy.jenoptik.corp:8080`.

**Comment by ximeg** [comment]
Hello @jgm, thank you for your advice. I prefixed the proxy with `http://` and this helped, now pandoc can download the image! It also works with the old pandoc v1.19.2.1

It would never occur to me that the word "scheme" means "protocol" (`http://` in this case )...

**Comment by jgm** [comment]
"Scheme" is the standard term for this part of a URI.
See https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

"While most URI schemes were originally designed to be
used with a particular protocol, and often have the
same name, they are semantically different from
protocols. For example, the scheme http is generally
used for interacting with web resources using HTTP,
but the scheme file has no protocol."
