### ISSUE TITLE
Use theme obtained with --print-highlight-style

### ISSUE THREAD

**Issue by aubertc** [jgm/pandoc#4133]
I'm trying to use the newly developed `--print-highlight-style` option (context: https://github.com/jgm/pandoc/pull/4106 and https://github.com/jgm/pandoc/issues/4096) to obtain a theme file and then use it with `--highlight-style`, but get an error message.

I'm using pandoc 2.0.4 (Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.4.4.1)

```bash
pandoc --print-highlight-style pygments > pygments.theme
pandoc pygments.theme --highlight-style pygments.theme -o test.pdf
```

Output:
`Could not read highlighting theme pygments.theme`

Expected output:
The pdf rendering of the file pygments.theme using the theme pygments.theme.

**Comment by aubertc** [comment]
@tajmone , do you have an idea?

**Comment by jgm** [comment]
This is a bug.  Apparently ToJSON and FromJSON instances of Style don't match (jgm/skylighting).

**Comment by jgm** [comment]
I've pushed some changes to skylighting that will fix this (with a few more changes needed in pandoc). Waiting on some possible CSS changes before making a release.
