### ISSUE TITLE
--pdf-engine-opt does not work correctly for wkhtmltopdf

### ISSUE THREAD

**Issue by adius** [jgm/pandoc#4137]
```shell
pandoc \
  --pdf-engine=wkhtmltopdf \
  --pdf-engine-opt='--page-size' \
  --pdf-engine-opt='A6' \
  --output test.pdf \
 test.html
```
yields error

```txt
--page-size specified in incorrect location
```
---

```shell
pandoc \
  --pdf-engine=wkhtmltopdf \
  --pdf-engine-opt='--page-size A6' \
  --output test.pdf \
 test.html
```

yields error

```txt
Unknown long argument --page-size A6
```

---

```shell
$ pandoc --version
pandoc 2.0.4
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.4.4.1
```

**Comment by iandol** [comment]
I use [pandocomatic](https://github.com/htdebeer/pandocomatic) to manage my pandoc options, but the working solution should be the same, use equals: `'--page-size=A6'`

**Comment by adius** [comment]
Doesn't work either: `Unknown long argument --page-size=A6`

**Comment by jgm** [comment]
This worked for me:

    pandoc -t html5 -o my.pdf MANUAL.txt --pdf-engine wkhtmltopdf --pdf-engine-opt='A6' --pdf-engine-opt='--page-size'

This shows what the bug is.  We're collecting the PDF engine
opts in reverse order; we need to reverse the list in
constructing the command line.  This should be a simple fix.
