### ISSUE TITLE
weird behaviour of producing list from Markdown to PDF

### ISSUE THREAD

**Issue by jdhao** [jgm/pandoc#4141]
I encounter a weird behaviour when I try to convert Markdown file to PDF which is related to generate list. In order to generate the list, I use `+` followed by space and the actual list content. Sometimes it works, but other times, it fails: in the produced PDF file, the actual `+` is printed instead of bullet sign.

Example file content:
```
+ https://stackoverflow.com/questions/2029651/how-do-you-initialise-a-dynamic-array-in-c
```
Command used to generate PDF is:
```
pandoc -o test.pdf test.md
```

The produced pdf is:
![image](https://user-images.githubusercontent.com/16662357/33837551-a928e626-dec7-11e7-960c-292249ecab1d.png)

You can see that the list is not generated properly.

But if I delete the `+` and type again, sometimes the generated PDF is correct (I am not sure why). For example, the following content in Markdown
```
+ https://stackoverflow.com/questions/2029651/how-do-you-initialise-a-dynamic-array-in-c

+ https://stackoverflow.com/questions/2029651/how-do-you-initialise-a-dynamic-array-in-c
```
will produce two different output:
![image](https://user-images.githubusercontent.com/16662357/33837985-10d1f65e-dec9-11e7-9b30-ebdc592525e3.png)

I have no idea how does it happen. 

## Version info 
* Pandoc version: 2.0.4
* Platform: Windows 8.1

**Comment by mb21** [comment]
I cannot reproduce this with pandoc 2.0.4 Are you sure you don't have unwanted tabs or other weird characters in there? Can you upload a markdown file that reproduces this?

**Comment by jgm** [comment]
I can't reproduce the issue on the command line or on trypandoc:

https://pandoc.org/try/?text=%2B+https%3A%2F%2Fstackoverflow.com%2Fquestions%2F2029651%2Fhow-do-you-initialise-a-dynamic-array-in-c%0A&from=markdown&to=


+++ Jiedong Hao [Dec 11 17 15:08 ]:

**Comment by jdhao** [comment]
The file is attached below, change extension to md to run the file.
[test.txt](https://github.com/jgm/pandoc/files/1548570/test.txt)

**Comment by mb21** [comment]
@jdhao In that file, the problem is the space right after the first plus. It's `0xA0` instead of the normal `0x20`

**Comment by jdhao** [comment]
Thanks for the prompt reply. I will investigate that further.

**Comment by mb21** [comment]
@jdhao I used vim to see what's which character: http://vim.wikia.com/wiki/Showing_the_ASCII_value_of_the_current_character
