### ISSUE TITLE
Print warnings if cli flags / variables are not consumed

### ISSUE THREAD

**Issue by adius** [jgm/pandoc#4143]
At the moment it's possible to specify all kinds of flags (e.g. `--variable fontfamily:Arial`) and one only knows if they were consumed by looking at the output. This is not very Haskell like ;-).

There should be a warning that the flag wasn't consumed and ideally a tip what needs to be set instead. (E.g. that the font family must be set via the `--css` flag, or that the feature is not supported yet)

**Comment by latk** [comment]
Such a feature would improve usability very much. In particular, it would also warn about typos for variables. I've done that often enough.

But this would also disrupt existing workflows: Some flags are intended as defaults when compiling a batch of documents, even when not all documents consume these variables and flags. Scripting becomes a lot easier when you can specify all variables up front, whether or not they will be used. Starting to issue warnings for some documents of a batch would be annoying.

If such a feature were to be implemented, please only in combination with a `--quiet-unused` flag to suppress just these warnings.

For the specific case of metadata variables (either set in a metadata block or provided as an `-M` flag), consider that these variables might not only be consumed by Pandoc itself but also by external filters. Detecting unused metadata variables is therefore impossible in the general case.

**Comment by mb21** [comment]
I tend to agree with @latk, thus closing this. (Feel free to reopen if you disagree @jgm)
