### ISSUE TITLE
Is it possible to producte beamer output with tikz without having custom template?

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#4147]
By default, tikz is not included in beamer template. Is it possible to use it without having to create a custom template?

**Comment by tarleb** [comment]
There are multiple ways: using `-H`/`--include-in-header` options, specifying `header-includes: \usepackage{tikz}` in a YAML block, or [using a filter](https://pandoc.org/lua-filters.html#building-images-with-tikz).  Please consult the [manual](https://pandoc.org/MANUAL.html) for details.

Please also note that this issue tracker is intended for bugs and feature requests only. Questions like this are best directed to the [pandoc-discuss mailing list](https://groups.google.com/forum/#!forum/pandoc-discuss).

**Comment by somenxavier** [comment]
Thanks a lot. I thought `-H` was only for html documents.
