### ISSUE TITLE
cannot switch off quotation mark conversion for LaTeX

### ISSUE THREAD

**Issue by teoric** [jgm/pandoc#4152]
With pandoc 2.0.5, I get a surprising change in my quotation marks when converting to PDF via (Xe/Lua)LaTeX.

    $ pandoc -f markdown-smart -t latex

Input:

    "abc" “abc” „abc“ de

Output:

    "abc" ``abc'' „abc`` de

I.e., some of the Unicode characters (only those which are current in English) are turned into old-style TeX encoding. If you then turn off old-style TeX ligatures, (which I do because I also need backticks, straight typewriter quotation marks etc. occasionally), this looks bad.  I think it is quite unlikely that someone intentionally uses Unicode quotation marks and wants them changed, especially if `--pdf-engine` is `xelatex` or `lualatex`.  Would it be an option to let Unicode characters pass unchanged?

**Comment by jgm** [comment]
Try using -t latex-smart.

+smart in LaTeX essentially turns on the ligatures.  If you
want to leave quotes alone, disable smart.

+++ teoric [Dec 13 17 16:01 ]:

**Comment by teoric** [comment]
Ah, thank you, I did not understand from the documentation that `±smart` can be given both on reading and writing. It seems I have never used output extensions and did not know they existed. Sincere apologies for the noise!

**Comment by jgm** [comment]
Here's where it's documented in the manual:

> In LaTeX, `smart` means to use the standard TeX ligatures
> for quotation marks (` `` ` and ` '' ` for double quotes,
> `` ` `` and `` ' `` for single quotes) and dashes (`--` for
> en-dash and `---` for em-dash).  If `smart` is disabled,
> then in reading LaTeX pandoc will parse these characters
> literally.  In writing LaTeX, enabling `smart` tells pandoc
> to use the ligatures when possible; if `smart` is disabled
> pandoc will use unicode quotation mark and dash characters.

**Comment by teoric** [comment]
Thank you. I read that, but as I did not unstand that you can activate output extensions on the export language, I thought that the extension applied differently when going to LaTeX instead of going from LaTeX.

I would not have understood either that smart is active by default. The section discusses extensions to Pandoc Markdown, if I understand correctly. Smart LaTeX is technically something else, if I may nitpick, and as the documentation discusses enabling and disabling, the default is not necessarily obvious, in my opinion.  Maybe it would be helpful to add a first sentence like: ‘This extension is enabled by default for all formats in both reading and writing.’?

**Comment by jgm** [comment]
I've added:

 It is enabled by default for `markdown`, `latex`, and `context`
 (in both input and output).

+++ teoric [Dec 14 17 07:04 ]:

**Comment by teoric** [comment]
That is very useful and informative, thank you!
