### ISSUE TITLE
org-reader: #+include: "file.org" should work w/ :minlevel 1 as well

### ISSUE THREAD

**Issue by reuleaux** [jgm/pandoc#4154]
suppose I have a file `tour.org` that I want to include from another file `other.org`:
then I can use:
```org
  #+include: "tour.org"
```
in `other.org` (or on the command line in a pipe for that matter) and pandoc will happily include this file `tour.org`:
```
$ echo '#+include: "tour.org"' | pandoc -f org -t native
```
(output not shown here, but this simple include works fine).
However if I add a `:minlevel 1` param (which is convenient for org's own exporter at least)

```
$ echo '#+include: "tour.org" :minlevel 1' | pandoc -f org -t native
[]
```
then nothing is included any more.

**Comment by tarleb** [comment]
Thanks for the report.
