### ISSUE TITLE
underscore in inline literal (``) interpreted as reference

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#4155]
If in the test I have something like ` ``set_<field>()`` `

    [WARNING] Reference not found for 'st' at line 123 column 4

According to 

http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-literals

characters in *inline literals* shall not be interpreted in any way.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information.

From [Contributing to pandoc](http://pandoc.org/CONTRIBUTING.html):

> Make sure you can reproduce the bug with the latest released version of pandoc
> (or, even better, the development version).
> 
> Your report should give detailed, *reproducible* instructions, including
> 
>   * the pandoc version (check using `pandoc -v`)
>   * the exact command line used
>   * the exact input used
>   * the output received
>   * the output you expected instead
> 
> A small test case (just a few lines) is ideal.  If your input is large,
> try to whittle it down to a *minimum working example*.

**Comment by rpuntaie** [comment]
version: ``pandoc 2.0.3``
commnad line: ``pandoc -f rst -t docx a.txt -o a.docx``
This creates the example ``a.txt``:

``` python

    T=["The quick brown fox jumped over the lazy dog."]*100
    with open('a.txt','w',encoding='utf-8') as f:
        f.writelines('\n\n'.join(T+[".. _`SOMEID`:","TARGET IS HERE"]+T+["`LINK <#SOMEID>`_"]))

```

The output has text marks, but with the `` ` ``.
Ctrl+click jumps to the top of the page and not to the target as expected.

**Comment by mb21** [comment]
Could you please paste or upload the `a.txt` file?

**Comment by rpuntaie** [comment]
It turned out not to be a general error. Here is the a.txt:

```
    I found a problem with my rst, which can be seen in this ``text`:
    I didn't close the last ``double quotes``:
    Some more text here
    ``set_<field>()`` produces the error 
    and that does not point to the actual line.


```

**Comment by mb21** [comment]
So the problem lies actually in your input file? And you're suggesting better error reporting?

**Comment by rpuntaie** [comment]
Yes, it is only about the error reporting now.

I didn't know that the problem was in my input file, when I created the issue.
Only when creating a small test example I found out.
The error in my input was many lines away from the reported error location.

This is very minor now. I could also close it, but I leave the decision to you.

Tell me, if you prefer, that I close it and make a new issue.

**Comment by mb21** [comment]
AFAIK, currently only the LaTeX reader is set up to report line numbers precisely. If and when we get around to rewriting the RST reader that could be added. So closing this for now.
