### ISSUE TITLE
RST .. _`SOMEID`: is converted to `SOMEID` textmark in docx instead of SOMEID

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#4156]
`` ` ``  starts an interpreted text and should not be included in the text.
 `.. _` tells that the interpretation should be a link target.

`.. _SOMEID` is valid in rst, too. But it should be considered as a shorthand for 
``.. _`SOMEID` ``  in the case where there is no blank. 

Blanks in marks regarding docx: If there is a blank, then that blank
needs to be converted to `_` to work as a mark in a Word document.
The same needs to be done for a reference like `` `link <#SOME ID>`_ ``.

I normally don't use `.. _SOMEID`, 
because a search for the word under the cursor would pick up `_SOMEID`,
i.e. `_` is a identifier character and is thus counted to the word. `` `SOMEID`_ `` occurrences are then not found.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information.

From [Contributing to pandoc](http://pandoc.org/CONTRIBUTING.html):

> Make sure you can reproduce the bug with the latest released version of pandoc
> (or, even better, the development version).
> 
> Your report should give detailed, *reproducible* instructions, including
> 
>   * the pandoc version (check using `pandoc -v`)
>   * the exact command line used
>   * the exact input used
>   * the output received
>   * the output you expected instead
> 
> A small test case (just a few lines) is ideal.  If your input is large,
> try to whittle it down to a *minimum working example*.

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss).

**Comment by rpuntaie** [comment]
version: ``pandoc 2.0.3``
commnad line: ``pandoc -f rst -t docx a.txt -o a.docx``
This creates the example ``a.txt``:

``` python

    T=["``The_<quick>`` brown_<> fox_ jumpe_<d> over<> the `lazy` dog_.``"]*100
    with open('a.txt','w',encoding='utf-8') as f:
        f.writelines('\n\n'.join(T+[".. _`SOMEID`:","TARGET IS HERE"]+T+["`LINK <#SOMEID>`_"]))

```

The output has text marks, but with the `` ` ``.
Ctrl+click jumps to the top of the page and not to the target as expected.

**Comment by mb21** [comment]
Is this the same as https://github.com/jgm/pandoc/issues/4155?

**Comment by rpuntaie** [comment]
No.

**Comment by rpuntaie** [comment]
Instead of textmark, please read bookmark.

**Comment by mb21** [comment]
>Instead of textmark, please read bookmark.

what?

again: can you post the `a.txt` file so we can reproduce this? It's also possible that by looking at the file, you'll figure out what's the cause for yourself.

**Comment by rpuntaie** [comment]
Yes, the above script to generate a.txt produces an unnecessarily big file. Here a better version:

```
    In the docx generated from this file, 
    in the bookmark dialog, the following bookmark 
    will be ```SOMEID``` instead of ``SOMEID``.

    .. _`SOMEID`:

    TARGET SOMEID

    The quick brown fox jumped over the lazy dog.

    This `LINK <#SOMEID>`_ jumps to the start 
    or the first occurrence of ``SOMEID``
    and not to the TARGET bookmark.

    On the other hand this works:

    In the docx generated from this file, 
    in the bookmark dialog, the following bookmark 
    is ``OTHERID``.

    .. _OTHERID:

    TARGET OTHERID

    The quick brown fox jumped over the lazy dog.

    This `LINK <#OTHERID>`_ jumps to the right location,
    i.e. if a bookmark is available, word will jump
    to it else it will search for the first occurrence.

```

**Comment by rpuntaie** [comment]
I checked also for the HTML target. It is the same problem. 

While in word you can observe to which location the cursor jumps, in HTML you will need to put some more text in between link and target to observe, whether the link works.

So the problem is, how the RST reader interprets ``.. _`SOMELINK`:``.

**Comment by mb21** [comment]
I'm not sure I understand exactly (expected and actual HTML output for the minimal snippet would be helpful, since your issue seem to occur both in html and docx output). But does it work if you use all-lowercase `id`s?

**Comment by rpuntaie** [comment]
Here is the html snippet. It contains ``<div id="`SOMEID`">`` 
instead of ``<div id="SOMEID">``.

``` html

<p>In the docx generated from this file, in the bookmark dialog, the following bookmark will be <code>`SOMEID</code>` instead of <code>SOMEID</code>.</p>
<div id="`SOMEID`">
<p>TARGET SOMEID</p>
</div>
<p>The quick brown fox jumped over the lazy dog.</p>
<p>This <a href="#SOMEID">LINK</a> jumps to the start or the first occurrence of <code>SOMEID</code> and not to the TARGET bookmark.</p>

```

**Comment by mb21** [comment]
I see, so the minimal repro is:

```
% pandoc -f rst
.. _`SOMEID`:

foo
^D
<div id="`SOMEID`">
<p>foo</p>
</div>
```

although it should be `id="SOMEID"` (at least that's what http://rst.ninjs.org does).

Although I'm not sure why you use ``.. _`SOMEID`:`` instead of the normal `.. _SOMEID:`
