### ISSUE TITLE
How i can to place code blocks or fenced divs into paragraph (<p> element) of list item? (markdown to HTML)

### ISSUE THREAD

**Issue by kazalex** [jgm/pandoc#4157]
How i can to place code blocks or fenced divs into paragraph (<p> element) of list item? Or after item without paragraph?

This code block will be placed out of paragraph of list item:

- list item
  ```
  ```

This fenced div will not be parsed as div:

- list item
  :::
  :::

Workaround:

- list item
  <div>
  :::
  :::
  </div>

pandoc 2.0.4

**Comment by mb21** [comment]
Divs and codeblocks are not inline, but block elements and are thus not supposed to go into paragraphs.

Please ask questions like this on pandoc-discuss. This is an issue tracker.
