### ISSUE TITLE
Better type checks for lua filters

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#4158]
Currently, pandoc happily accepts single elements where it expects lists of elements: elements are treated as lists of length 0, since they are tables without numerical keys.  Pandoc should perform some additional type checking, either auto-convert single elements to singletons, and/or throw an error if the lua table doesn't look like a list.

**Comment by jgm** [comment]
I think it would probably be fine to auto-convert single elements to one-element lists, in cases where pandoc expects a list. That would allow things like
``` lua
   return pandoc.Str("(") .. elem.contents .. pandoc.Str(")")
```

**Comment by tarleb** [comment]
Error messages now contain some info on the context in which a lua operation failed. Cases in which we try multiple alternatives are not handled well yet.

I'm not sure yet about treating single elements like lists. It doesn't feel quite right, but is probably fine and would probably avoid a lot of confusion for users. Apart from adding metamethods to `pandoc.Block.behavior` and `pandoc.Inline.behavior`, we'd also have to modify all constructors.

**Comment by tarleb** [comment]
I've update the constructors to accept single elements and, in the case of Inlines, plain strings instead of a list of elements.  This currently incurs a small performance penalty due to the fact that we use these constructors during serialization. We can work around this if performance becomes an issue.

Todo:

- [ ] alter element setters to accept single elements;
- [ ] change `peekInline` such that a plain string get's treated as `Str`;
- [ ] add metamethod for concatenation.

**Comment by jgm** [comment]
+++ Albert Krewinkel [Jan 13 18 14:41 ]:
>   I've update the constructors to accept single elements and, in the case
>   of Inlines, plain strings instead of a list of elements. This currently
>   incurs a small performance penalty due to the fact that we use these

How much performance impact?

**Comment by tarleb** [comment]
This wouldn't be difficult to fix, but would result in a lot of boilerplate.  Currently, about ¾ of `pandoc.lua` are boilerplate.  Property naming is the only relevant info in the code, together with the order in which they should be passed to constructors. If we had this info in Haskell, then we could auto-generate most of the file.

**Comment by jgm** [comment]
I don't like the idea of a 20% performance decrease in the
constructors; I'd maybe rather just force people to
construct lists. But autogenerating pandoc.lua and fixing
the performance problem sounds even better.

+++ Albert Krewinkel [Jan 14 18 08:01 ]:

**Comment by tarleb** [comment]
Ok then. I can't promise to get everything done in time for the next release, so I'll revert the recent changes.

**Comment by jgm** [comment]
I'm having second thoughts now.  It really does make things
much more intuitive for users, and we can stand the slowdown
until we have a chance to work around it, I think.

+++ Albert Krewinkel [Jan 14 18 20:20 ]:

**Comment by tarleb** [comment]
A third alternative would be to just add the additional boilerplate for now. It should solve the performance degradation and we can still refactor later.

My approach would be to split the internal constructors into a separate lua module which would be used for serialization.  The main pandoc module would then re-export these functions and add normalizations where necessary. Not pretty, but simple, easy and fast to implement.

**Comment by jgm** [comment]
Whatever you think is best, I'll go along.

I do think we need to remember that adding more lines of lua
code is riskier (in terms of bugs) than adding more lines
of Haskell.  It would be good to have good test coverage
of the lua, since even a typo might not be caught til
run time.  I also like the idea of autogenerating the lua
module from a Haskell data structure, for this reason.
(Also, this would help us keep lua nomenclature in line
with Haskell.)

+++ Albert Krewinkel [Jan 15 18 08:32 ]:

**Comment by tarleb** [comment]
There was a different, easier to solve, but more sever performance problem. Tackling that lead to a ~50% performance boost for constructor calls during marshalling. Filtering should be roughly as fast or faster than it was before the extra type checks in the constructors.

I have yet to find a satisfying solution for constructors and marshalling in general. I'm still experimenting.

**Comment by jgm** [comment]
Hurrah!

+++ Albert Krewinkel [Jan 23 18 20:41 ]:
>   There was a different, easier to solve, but more sever performance
>   problem. Tackling that lead to a ~50% performance boost for constructor
>   calls during marshalling. Filtering should be roughly as fast or faster
>   than it was before the extra type checks in the constructors.

**Comment by tarleb** [comment]
I think type checks and error messages are mostly OK now.
