### ISSUE TITLE
\newcommand bug

### ISSUE THREAD

**Issue by Hendrikto** [jgm/pandoc#4159]
* pandoc version:

  ```
     pandoc 2.0.5
     Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.5
  ```
* texlive-core version: `2017.45811-1`
* command used: `pandoc -o repro.pdf repro.md`

The following Markdown document can be compiled without problems

```
---
title: Bug Repro
header-includes:
	- \usepackage[mathscr]{euscript}
---
\newcommand{\gen}[2]{#1\ Gen\ #2}

\newcommand{\pow}{\mathscr{P}}
```

but removing the empty line leads to compile errors. When I compile the following document

```
---
title: Bug Repro
header-includes:
	- \usepackage[mathscr]{euscript}
---
\newcommand{\gen}[2]{#1\ Gen\ #2}
\newcommand{\pow}{\mathscr{P}}

```
I get this error:

```
Error producing PDF.
! Undefined control sequence.
l.66 newcommand\{\pow
```

The expected result would be both documents resulting in the same output pdf.

Both documents are identical except for the empty line in between the `\newcommand`s. The problem arises because in the generated LaTeX code, the braces are escaped, and whitespace is added.

The only related issue I could find was https://github.com/jgm/pandoc/issues/4007, but the issue is closed with a fix, that does not seem to help me. Also I succesfully compiled the version without the empty line recently. I assume that update 2.0.5 broke this.

**Comment by jgm** [comment]
This shows where the problem lies:
```
% pandoc  -t native
\newcommand{\gen}[2]{#1\ Gen\ #2}
\newcommand{\pow}{\mathscr{P}}
[RawBlock (Format "latex") "\\newcommand{\\gen}[2]{#1\\ Gen\\ #2}\n\\"
,Para [Str "newcommand{",RawInline (Format "tex") "\\pow",Str "}{",RawInline (Format "tex") "\\mathscr{P}",Str "}"]]
```
For some reason, the first backslash on the second line is getting included in the raw latex block associated with the first `\newcommand`.

**Comment by jgm** [comment]
Even simpler:
```
 % pandoc  -t native
\newcommand{\gen}{a\ Gen\ b}
abc
^D
[RawBlock (Format "latex") "\\newcommand{\\gen}{a\\ Gen\\ b}\na"
,Para [Str "bc"]]
```
The problem seems to have something to do with the escaped spaces:
```
 % pandoc  -t native
\newcommand{\gen}{a Gen b}
abc
^D
[RawBlock (Format "latex") "\\newcommand{\\gen}{a Gen b}"
,Para [Str "abc"]]
```
Add one escaped space and the `\n` gets included:
```
% pandoc  -t native
\newcommand{\gen}{a Gen\ b}
abc
^D
[RawBlock (Format "latex") "\\newcommand{\\gen}{a Gen\\ b}\n"
,Para [Str "abc"]]
```
Add two and the `a` gets included too:
```
% pandoc  -t native
\newcommand{\gen}{a\ Gen\ b}
abc
^D
[RawBlock (Format "latex") "\\newcommand{\\gen}{a\\ Gen\\ b}\na"
,Para [Str "bc"]]
```
Add three and `ab` gets included. And so on.

**Comment by jgm** [comment]
Ah, this makes sense; I changed the tokenizer for escaped spaces in the last release, so there must be a bug in that change.
