### ISSUE TITLE
HTML Writer: LineBlock should use <br>, not <div> with CSS white-space property

### ISSUE THREAD

**Issue by hftf** [jgm/pandoc#4162]
Related:

1. #3072 22cb9e3 New LineBreak AST element\
   HTML Writer converts LineBreak to `<div>` with style attribute
2. #1623 66b0839\
   HTML Writer converts LineBreak to `<div>` with class instead of style attribute
3. [Summary of a discussion about rendering RST line blocks to HTML in the Docutils project](http://docutils.sourceforge.net/docs/dev/rst/alternatives.html#output)

----

There are problems with using a div with style to indicate a line block. First, it is presentational, not semantic: HTML's `<div>` does not have the meaning of preserving line breaks, but HTML already does have a semantic element to indicate line breaks: `<br>`. When CSS is disabled or broken, the block is rendered incorrectly without any line breaks. It also cannot be round-trip converted back into `LineBlock`:

```
echo '[LineBlock [[Str "A"],[Str "B"]]]' | pandoc -f native

<div class="line-block">A
B</div>
```
```
echo '[LineBlock [[Str "A"],[Str "B"]]]' | pandoc -f native | pandoc -f html -t native

[Div ("",["line-block"],[])
[Plain [Str "A",SoftBreak,Str "B"]]]
```

I would like to propose that the HTML Writer be modified like so:
```
echo '[LineBlock [[Str "A"],[Str "B"]]]' | pandoc -f native

<div class="line-block">A<br />
B</div>
```
and that the HTML Reader also be modified to recognize such markup as `LineBlock`.

I could also not find any HTML tests for LineBlock (but there are a few in the unmerged PR #1545).

**Comment by jgm** [comment]
The change was made in #1623.  I guess I don't see any reason to prefer using CSS to just putting br tags in there, as long as we still have a div with the special class. But maybe @uvtc or @mb21 would like to comment?

**Comment by mb21** [comment]
It seems we have being going back and forth on this one a couple of times (e.g. [here](https://github.com/jgm/pandoc/pull/3072#issuecomment-240491442))... but in principle, I agree, we could just emit `<br>`s as well -- as long as we also keep the `div` with the class so people can apply their custom styling with CSS.

Then again, I don't really see much of an advantage for the change either. The two reasons mentioned above seem fairly theoretical. But yes, we could get rid of a few lines of CSS in the templates.

What does @tarleb think, who introduced the LineBlock element?

**Comment by uvtc** [comment]
If I understand this correctly, the question is whether to use inline css styling "`style="white-space: pre-line"`", versus `<br/>`. Regardless we still have the `div class=line-block` around them.

Since there is no "line block" element in html, I think it makes sense to produce them with `<br/>`'s. That's exactly what br's are for. I presume each output format has its own "br" for that purpose as well.

**Comment by tarleb** [comment]
Cutting out any semantical correctnes arguments in this case, I agree that `br` elements are easier to work with. I slightly favor HTML elements over line break characters, but don't feel stronly either way.

**Comment by mb21** [comment]
> If I understand this correctly, the question is whether to use inline css styling "`style="white-space: pre-line"`", versus `<br/>`.

Almost. It's about whether to use `<div class="line-block">` and `.line-block { white-space: pre-line; }` in the template (current implementation), versus `<div class="line-block">` with text and `<br/>`s inside.

**Comment by uvtc** [comment]
Thanks for the clarification, @md21!

**Comment by jgm** [comment]
+++ hftf [Dec 26 17 17:00 ]:
>   Thanks, John.
>   Fwiw, I also suggested that the HTML Reader recognize <div
>   class="line-block"> as LineBlock.

Done.
