### ISSUE TITLE
Removing Backslash for embedded CSS

### ISSUE THREAD

**Issue by alban1973** [jgm/pandoc#4164]
Hello,

I used pandoc for years for my workflows.
But since your 2.0 version, pandoc do not  work anymore in my workflows.
I tried for some days different extensions, parameters, ..., but i didn't found any solution , if you have an idea.

My data source is an opml file. This file is gernerated with any outliner , mind mapper, ...

`<?xml version="1.0"?>
<opml version="1.0">
	<head>
		<title>
test
		</title>
	</head>
	<body>
		<outline text="test">
			<outline text="try" _note="Hello everyone.&#xA;Carriage return before and after.&#xA;Test.&#xA;&#xA;Here is inline html :&#xA;&#xA;&lt;div&gt; &#xA;&lt;balise&gt;&#xA;bla bla&#xA;&lt;/div&gt;"/>
		</outline>
	</body>
</opml>
`

As you can see, i have html tags inside text.
It is because, after converting this text into markdown, i convert it to html with a css file attached (-H).

But my first convertion to Markdown is not working at all.

`pandoc -f  opml test.opml -t markdown -o test.md`

The result is something like that :

`Here is inline html : \<div\> \<balise\> bla bla \</div\>`

The problem is : **Every special character has a backslash (for escaping).**

**For my html transformation, pandoc is not able anymore to understand correctly div tags (and all html tags at all).**
If i use `all_symbols_escapable` , this do not work either, because i do not want entity inside my html tags ...

Is this a bug ? 

Regards,

A.M.

**Comment by alban1973** [comment]
[test.opml.txt](https://github.com/jgm/pandoc/files/1565526/test.opml.txt)
Here is the example of an opml file used for test.

**Comment by alban1973** [comment]
It seems that I finally found a workaround. I need to update my data source but it's the best I currently can do. I just use the `markdown+raw_attribute` option and by changing my html code in OPML source file :

<img width="204" alt="capture d ecran 2017-12-17 a 13 29 02" src="https://user-images.githubusercontent.com/17214231/34079464-4ad6e53a-e32e-11e7-9f63-85d20da090d5.png">

the markdown converted file with +raw_attribute option :

<img width="303" alt="capture d ecran 2017-12-17 a 13 30 22" src="https://user-images.githubusercontent.com/17214231/34079473-862890e8-e32e-11e7-8e5a-36d87a2d52bc.png">

And the final html converted file :

**Comment by jgm** [comment]
This looks like a regression to me.  We didn't intend to
change behavior here.
