### ISSUE TITLE
Couldn't parse odt file.

### ISSUE THREAD

**Issue by retorquere** [jgm/pandoc#4165]
pandoc version: 2.0.5.1

When I try to convert the attached odt file to markdown, pandoc just says "Couldn't parse odt file.". As attached here the file has a docx extension but that's just because github doesn't allow .odt extensions.

[article-field.odt.docx](https://github.com/jgm/pandoc/files/1565481/article-field.odt.docx)

**Comment by alban1973** [comment]
Hello,
Work like a charm for me. 
Regards,

**Comment by retorquere** [comment]
Then it must be something about my system. If there's something I can do to provide more data I'll be glad to do so, otherwise we'll have to close as non-reproducible I guess.

**Comment by alban1973** [comment]
I'm on Mac OS X. did you try to install pandoc again ?

**Comment by retorquere** [comment]
I'm on Linux, and I just upgraded pandoc before trying the conversion.

**Comment by jgm** [comment]
I couldn't reproduce this either.  After downloading the
file, this worked fine:

    pandoc -f odt -t markdown ~/Downloads/article-field.odt.docx

**Comment by retorquere** [comment]
Then it must be some peculiarity of my system. On macos it works for me too.

**Comment by jgm** [comment]
Does `pandoc --version` confirm that you're not accidentally running an older version?

**Comment by retorquere** [comment]
```
pandoc --version
pandoc 2.0.5
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.5
Default user data directory: /home/emile/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
Do you perhaps have a `reference.odt` file in your `~/.pandoc` directory?

**Comment by retorquere** [comment]
I don't have a `~/.pandoc` directory, but I'm also no longer able to reproduce the issue. I've not upgraded pandoc, so I'm at a loss to explain what happened.
