### ISSUE TITLE
reStructuredText outputs monospace links incorrectly

### ISSUE THREAD

**Issue by AbigailBuccaneer** [jgm/pandoc#4166]
When pandoc converts a link containing monospace text to reStructuredText, the generated output is incorrect (according to the official docutils tools):

```
$ cat test.md
[`monospace link`](https://example.org)

$ pandoc --from markdown --to rst test.md
```monospace link`` <https://example.org/>`__

$ pandoc --from markdown --to rst test.md | rst2html5.py | grep 'monospace link'
<p><span class="docutils literal">`monospace link</span> &lt;<a class="reference external" href="https://example.org/">https://example.org/</a>&gt;`__</p>
```

Other output formats are okay with this:
```
$ pandoc --from markdown --to html test.md
<p><a href="https://example.org/"><code>monospace link</code></a></p>
```

I don't actually know if rST supports monospace text inside links - I can't get the output I was hoping for in any way. In that case, Pandoc should presumably strip and/or warn about the monospace, rather than generating invalid output.

Version info:
```
$ pandoc --version
pandoc 2.0.5
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.5
...

$ rst2html5.py --version
rst2html5.py (Docutils 0.14, Python 2.7.12, on linux2)
```

**Comment by jgm** [comment]
This is a dup of #3973, I think.
