### ISSUE TITLE
LaTeX math equation is not rendered when using github flavored markdown

### ISSUE THREAD

**Issue by jdhao** [jgm/pandoc#4168]
## Description
I am using pandoc to convert markdown to pdf. I have found that if I use the flag `-f gfm`, the equation in the markdown file are not rendered.  For example, `test.txt` contains following equation,
```
$e=mc^2$
```
If I use command:
```
pandoc -o test.pdf test.md
```
The equation is generated as expected (see the below image).
![image](https://user-images.githubusercontent.com/16662357/34105761-8be71e34-e430-11e7-9353-f18e325953d5.png)

But if I use 
```
pandoc -f gfm -o test.pdf test.md
```
The rendered image is not correct (shown below).
![image](https://user-images.githubusercontent.com/16662357/34105693-50336f8c-e430-11e7-9c8e-c7690acdd7ab.png)

Is this the expected behaviour?

## Version info
+ pandoc: 2.0.5
+ Platform: Windows 8.1

**Comment by mb21** [comment]
This is expected. GitHub currently doesn't support math in its markdown.

Please ask questions like this on pandoc-discuss.

**Comment by tarleb** [comment]
This is already supported in recent pandoc versions.
