### ISSUE TITLE
Text wrapping can turn Org mode footnote reference into footnote

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#4171]
Consider the following example:
```
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa [fn:1] a

[fn:1] b
```

After passing it through `pandoc -f org -t org` it becomes:
```
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
[fn:1] a

[fn:1] b
```
Now there are two footnote definitions, but no reference.

After passing it through `pandoc -f org -t org` it becomes:
```
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
Now there are no footnotes because nobody referenced them.

I have not looked into Emacs Org mode code, but it seems that Emacs avoids this when I reflow the text with M-q. Basically it behaves as if footnote reference and previous word is a single word. Pandoc should do the same in Org writer.

**Comment by labdsf** [comment]
I have actually discovered this bug in Muse writer, but footnotes in Org mode are similar so I filed two bugs and hope to steal a solution from Org writer :P

**Comment by jgm** [comment]
I'm about to post a solution, which you can borrow.

+++ Alexander [Dec 18 17 22:00 ]:
