### ISSUE TITLE
LaTex macros not expanded in align environments.

### ISSUE THREAD

**Issue by dataopt** [jgm/pandoc#4179]
pandoc version 2.0.5

I have the following file `align.md`:
```
\newcommand{\tuple}[1]{\langle #1 \rangle}

$\tuple{a, b, c}$

\begin{align}
\tuple{a, b, c}
\end{align}
```
The command `pandoc --from markdown+latex_macros --mathjax -t html align.md -o align.html` expands the first tuple but not the one within align.  Here is the output file `align.html`

```
<p><span class="math inline">\(\langle a, b, c \rangle\)</span></p>
<span class="math display">\[\begin{align}
\tuple{a, b, c}
\end{align}\]</span>
```

**Comment by mb21** [comment]
This is expected AFAIK. From the Manual:

> Note that in LaTeX environments, [...] the material between the begin and end tags will be interpreted as raw LaTeX, not as Markdown.

**Comment by dataopt** [comment]
I wonder if there could be an option to expand macros within these begin and end tags as well. I am using bookdown for a few large projects with targets that include html, epub, and pdf. Since bookdown uses rmarkdown which in turn uses pandoc, without macro expansion within begin and end tag basically makes macros useless within bookdown/rmarkdown.

Is it difficult to add an option to expand macros within being and end tags?

**Comment by jgm** [comment]
Current behavior in reading markdown is:

- parse macros and apply them in $..$ or $$..$$ math (assuming
  `latex_macros` is set, the default)
- don't apply macros in raw LaTeX inlines/blocks

I agree that this seems a bit inconsistent.

What would be desirable is this:

- if the intended target is LaTeX, don't apply macros
  anywhere
- if the intended target is not LaTeX, apply the macros
  in both math and raw LaTeX

However, that violates a basic expectation that readers and
writers are independent (how a reader parses does not depend
on what writer will be used).

So I suppose we could change things thus:

- if `latex_macros` is set, apply macros to both math and
  raw LaTeX
- if it isn't set, don't apply macros to either.

This seems more sensible than what we have now, and I don't
think I see a downside.  Anyone have thoughts on this?

**Comment by dataopt** [comment]
The proposed change to apply macros to *both* math and raw LaTex if and only if `latex_macros` is set would seem to work for my use case.
