### ISSUE TITLE
running parsers in API

### ISSUE THREAD

**Issue by noinia** [jgm/pandoc#418]
Would it be possible to extend the API so external programs using pandoc as a library can run the readers themselves? My reason for requesting this is because it allows for more flexibility in error handling. 

In my particular case I'm trying to run pandoc to convert a file in markdown format into html (as part as a webapplication in snap). In case pandoc will fail to parse the input file correctly some other part of my code should be executed. It seems that the API does not export the required functions to allow for this. I think there are two options to fix this: 

1) Provide an alternative function to `readWith' as found in Text.Pandoc.Parsing that simply returns an Either. e.g.

``` haskell
readWith' :: GenParser t ParserState a     -- ^ parser
         -> ParserState                                  -- ^ initial state
         -> [t]                                                  -- ^ input
         -> Either ParseError a
readWith' parser state input = runParser parser state "source" input 
```

or 

2) export the parse\* functions in Text.Pandoc.Readers.\* (e.g. parseMarkdown ) so a program can run a particular parser itself. 

In this case (1) would be sufficient. But (2) is a bit more flexible.

**Comment by jgm** [comment]
We now do return an Either, so this was long ago fixed.
