### ISSUE TITLE
HTML Reader: Regression for figure without figcaption

### ISSUE THREAD

**Issue by davidar** [jgm/pandoc#4183]
HTML `figure`s without a corresponding `figcaption` should fall back to the `alt` text of the `img` (as was the behaviour prior to #3813) rather than having no caption at all.

```
$ pandoc -v
pandoc 2.0.5
$ echo '<figure><img src="foo" alt="bar"></figure>' | pandoc -f html -t markdown
![](foo)
$ echo '<img src="foo" alt="bar">' | pandoc -f html -t markdown
![bar](foo)
```

A related issue is that `figcaption` is ignored when it contains block tags like `div` or `p`:

```
$ echo '<figure><img src="foo" alt="bar"><figcaption><p>baz</p></figcaption></figure>' \
  | pandoc -f html -t markdown
![](foo)
$ echo '<figure><img src="foo" alt="bar"><figcaption><div>baz</div></figcaption></figure>' \
  | pandoc -f html -t markdown
![](foo)
$ echo '<figure><img src="foo" alt="bar"><figcaption><span>baz</span></figcaption></figure>' \
  | pandoc -f html -t markdown
![baz](foo)
```

**Comment by jgm** [comment]
> HTML figures without a corresponding figcaption should fall back to the alt text of the img (as was the behaviour prior to #3813) rather than having no caption at all.

I'm not sure why.  In the HTML page as displayed by a browser, there will be no caption.  So, why should pandoc parse this as a figure with a caption?

**Comment by davidar** [comment]
For the same reason this happens:

```
$ echo '<p>baz</p><p><img src="foo" alt="bar"></p><p>baz</p>' | pandoc -f html -t markdown
baz

![bar](foo)

baz

$ echo '<p>baz</p><p><img src="foo" alt="bar"></p><p>baz</p>' | pandoc -f html -t markdown \
  | pandoc
<p>baz</p>
<figure>
<img src="foo" alt="bar" /><figcaption>bar</figcaption>
</figure>
<p>baz</p>
```

**Comment by jgm** [comment]
A better fix for the round-trip failure you point to would be making the markdown output from the first step something like
```
![bar](foo)<!-- nofig -->
```
to avoid having it interpreted as an implicit figure.

**Comment by davidar** [comment]
Basically all I'm saying is that wrapping an `img` in `figure` shouldn't result in the `alt` text being completely ignored, I'm not sure what the best way to handle that would be.

**Comment by mb21** [comment]
> I'm not sure why. In the HTML page as displayed by a browser, there will be no caption. 

I changed the pull request accordingly.

I guess parsing the alt text when there is no figcaption will have to wait for https://github.com/jgm/pandoc/issues/3177

**Comment by gwern** [comment]
I disagree about the need for waiting for #3177 (which has been 4 years and shows no particular sign of being solved soon). Pandoc *already* supports the necessary construct in the form of attributes, and *already* correctly parses and deals with img tags with alt attributes... just only in the Markdown->HTML direction:

```
$ echo '![](foo.jpg){alt="bar"}'                              | pandoc -f markdown -t html
<p><img src="foo.jpg" alt="bar" /></p>
$ echo '<p><img src="foo.jpg" alt="bar" /></p>' | pandoc -f html -t markdown
![bar](foo.jpg)
```

And of course, Pandoc even solves figures to some degree by treating it as a HTML literal... but only if you parse the HTML as Markdown, as parsing the HTML as HTML delivers worse results, erasing attributes and classes:

```
$ echo '<figure><img src="foo.jpg" alt="bar" /></figure>' | pandoc -f html -t markdown
![](foo.jpg)
$ echo '<figure><img src="foo.jpg" alt="bar" /></figure>' | pandoc -f markdown -t markdown
 \```{=html}
<figure>
 \```
 \`<img src="foo.jpg" alt="bar" />`{=html}
 \```{=html}
</figure>
 \```
```

The HTML reader just needs to be improved to handle alt/title/class attributes on imgs,

**Comment by tarleb** [comment]
> waiting for #3177 (which has been 4 years and shows no particular sign of being solved soon).

We aim to tackle this in a GSoC project this summer, see #7184.

**Comment by jgm** [comment]
We *could* easily change the reader so that the alt was used as the caption when no caption exists.  But I'm not sure this is the right way forward; it would mean that a figure without a caption became a figure with a caption after round-tripping html -> markdown -> html.
