### ISSUE TITLE
.. target: produced for docx headers, when converting from docx to rst, are no good

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#4188]
pandoc 2.0.3

For a title "Hardware" in docx I get this:

```
.. hardware-1:

Hardware
~~~~~~~~
```

It should be

```
.. _hardware1:

Hardware
~~~~~~~~
```

- The underscore was missing
- The hyphen is no good because when converting back it cannot be used as docx  bookmark

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information.

From [Contributing to pandoc](http://pandoc.org/CONTRIBUTING.html):

> Make sure you can reproduce the bug with the latest released version of pandoc
> (or, even better, the development version).
> 
> Your report should give detailed, *reproducible* instructions, including
> 
>   * the pandoc version (check using `pandoc -v`)
>   * the exact command line used
>   * the exact input used
>   * the output received
>   * the output you expected instead
> 
> A small test case (just a few lines) is ideal.  If your input is large,
> try to whittle it down to a *minimum working example*.


Please also search the (open *and* closed) issues to make sure the issue hasn't come up before.
Check the [User's Guide] and [FAQs] for anything relevant.
Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss).

[User's Guide]: http://pandoc.org/MANUAL.html
[FAQs]:  http://pandoc.org/faqs.html

**Comment by jkr** [comment]
Not sure if it's the docx reader or the rst writer, but it would be helpful to see the docx that produces this problem (I get neither the target nor the trailing `1` when I try it). Could you please post that?

**Comment by jgm** [comment]
The missing underscore is a bug, I'll fix it right away.

Can you say more about

> The hyphen is no good because when converting back it cannot be used as docx bookmark

**Comment by rpuntaie** [comment]
All I can say is: I tried to set a bookmark in MS Word, that contained a hyphen (a minus), and it didn't work.
I googled a bit and found this: https://stackoverflow.com/questions/852922/what-are-the-limitations-for-bookmark-names-in-microsoft-word

**Comment by jgm** [comment]
Hm, I just tried with a hyphenated bookmark, and it worked fine.

**Comment by rpuntaie** [comment]
Here some arguments for you to reconsider:

- With ``.. _id-1:`` the editor will not see `id` but `_id` because `_` is a word chars and `-` is not a word char.

  RST ist mostly used by programmers. The editor will have `_` in word chars and `-` not in word chars.

  Find under cursor will look for all `_id` and find none, because `` `id-1`_ `` or `id-1_` is used for ref.

- MS Word does not allow `-` when converting back from RST to DOCX, at least not in my version of MS Word (see link above).

- `_` is just a special role, analogue to ``:math:`2x` ``. For consistency one should also use ``_`id1` ``.

One should try to make life easier:
There is no disadvantage in using ``.. _`id1`: ``, while there are for ``.. _id-1:``.
