### ISSUE TITLE
docx table cells containing content controls get stripped in html output

### ISSUE THREAD

**Issue by iredwards** [jgm/pandoc#4190]
When converting Word files to HTML, if the docx files have content controls in table cells then 
[ContentControlTest.docx](https://github.com/jgm/pandoc/files/1583366/ContentControlTest.docx)
in the HTML output, the cells with content controls are stripped.
I'm using Pandoc version 2.0.5 and Word 2013, running in git bash on Windows 7.

In the attached ContentControlTest.docx file, there is a table with 3 columns in the first (header) row. The second row has a content control in the middle column. But the html conversion drops the middle cell:

```
$ pandoc -f docx -t html ContentControlTest.docx
<table>
<tbody>
<tr class="odd">
<td><strong>col1Header</strong></td>
<td><strong>col2Header</strong></td>
<td><strong>col3Header</strong></td>
</tr>
<tr class="even">
<td>col1 content</td>
<td>col3 content</td>
</tr>
</tbody>
</table>
```

I looked at the contents of the docx file, and found that the table cell doesn't actually contain the control. It is the other way around: the control contains the cell.

Here is the heavily elided WordML, showing the cell <w:tc> wrapped in a "structured document tag" <w:sdt>:
```
<w:tbl>
    <w:tr>
        <w:tc><w:p><w:r><w:t>col1Header</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>col2Header</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>col3Header</w:t></w:r></w:p></w:tc>
    </w:tr>
    <w:tr>
        <w:tc><w:p><w:r><w:t>col1 content</w:t></w:r></w:p></w:tc>
        <!-- wrapped cell start-->
        <w:sdt>
            <w:sdtPr>
                <w:dropDownList>
                    <w:listItem w:value="Select content type"/>
                    <w:listItem w:displayText="Accessibility text" w:value="Accessibility text"/>
                    <w:listItem w:displayText="Body copy" w:value="Body copy"/>
                    <w:listItem w:displayText="Button label" w:value="Button label"/>
                    <w:listItem w:displayText="Checkbox label" w:value="Checkbox label"/>
                    <w:listItem w:displayText="Dropdown list" w:value="Dropdown list"/>
                    <w:listItem w:displayText="Field instruction" w:value="Field instruction"/>
                </w:dropDownList>
            </w:sdtPr>
            <w:sdtContent>
                <w:tc><w:p><w:r><w:t>Body copy</w:t></w:r></w:p></w:tc>
            </w:sdtContent>
        </w:sdt>
        <!-- wrapped cell end -->
        <w:tc><w:p><w:r><w:t>col3 content</w:t></w:r></w:p></w:tc>
    </w:tr>
</w:tbl>
```

**Comment by jkr** [comment]
What would be the best output? Lists aren't part of the pandoc AST. 

I guess, look for a "Body Copy" field, and default to the first item in the list?

**Comment by iredwards** [comment]
The presence of "Body copy" in the list is a coincidence following the docx file where I first came across a content control (i.e. <w:sdt>). The docx file was being used to describe a web form, so there is no meaningful equivalence between the <w:dropDownList> and one of the possible _values_ being "Body copy", or "Dropdown list" for that matter. In retrospect I should have provided an example where the list items had nothing to do with software things.

As far as I know, the best output when a <w:sdt> is found would be to replace it with the contents of the <w:sdtContents> tag contained within the <w:sdt>. I'm guessing the <w:sdtPr> (structured document tag properties) should just be discarded.

There may be other kinds of Word content controls that should be handled differently. I don't know. I know as little about Word as possible. I'll take a look at the Office file format spec (Open XML, ECMA-376) and report if I see anything useful and survive the ordeal.

**Comment by jkr** [comment]
That matches my quick reading of the spec. Let me know if you come up with anything further, but if not I'll implement some version of "replace w:sdt>w:sdtContents>x with x".

`<w:sdtContent>` looks like it only takes `ParPart`s (as we call it in the docx parser: runs, insertions, deletions, omath, etc). So we can just add a pattern-match to `elemToParPart` (typing it up now so I remember what I was thinking later):

``` haskell
elemToParPart ns element 
    | isElem ns "w" "sdt" element
    , Just content <- findChildByName ns "w" "sdtContent" element
    , child : _ <- elChildren content
    = elemToParPart ns child
```
Not sure if it will cover every case, but it should take care of most.

**Comment by iredwards** [comment]
Related to [Content Controls are left out of the document (.docx) #2587](https://github.com/jgm/pandoc/issues/2587)

**Comment by jkr** [comment]
Hmm... that won't work, because it's not just ParParts -- it's also, in this case, `w:tc` -- so I have to assume that nearly any content can be inside the `sdtContent` tag.
