### ISSUE TITLE
org mode to md pygment problem

### ISSUE THREAD

**Issue by abate** [jgm/pandoc#4191]
I've an org mode with a code snippet as : 

```
#+BEGIN_SRC ocaml
let int31_encoding = Data_encoding.int31
#+END_SRC
```

that is converted to md as 

>\`\`\` {.ocaml}
>let int31_encoding = Data_encoding.int31
>\`\`\`

using sphinix-build (bu I think any pygment based processors) I get this warning : 
`WARNING: Pygments lexer name '{.ocaml}' is not known`

It seems to me that the conversion is wrong as the correct annotation for code should be

> \`\`\`ocaml ....

$pandoc -v
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1

**Comment by tarleb** [comment]
`{.ocaml}` is pandoc Markdown, which apparently is not understood by Pygments. Try CommonMark output instead:

    $ pandoc --to=commonmark --from=org
    #+BEGIN_SRC ocaml
    let int31_encoding = Data_encoding.int31
    #+END_SRC
    ^D

Output:

    ``` ocaml
     let int31_encoding = Data_encoding.int31
    ```
