### ISSUE TITLE
FB2 writer does not support `cover-image` metadata

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#4195]
FB2 format supports covers but there is no way to create a book with cover with pandoc.

**Comment by jgm** [comment]
The problem is that the fb2 is just an xml file.  So, if an
image were to be included, it would presumably have to be
via a data uri.

If you let us know how covers are usually supported in fb2,
we can try to implement it.

**Comment by labdsf** [comment]
FB2 writer already supports images. They are encoded in base64.

All that is needed is to add a `<coverpage>` element inside `<description>` and place an `<image>` inside `<coverpage>`. Nothing else is supported inside `<coverpage>` anyway and FB2 writer already has code for images inside document.
