### ISSUE TITLE
TeX \foreignlanguage text is omitted from .docx output

### ISSUE THREAD

**Issue by RhvdG** [jgm/pandoc#4199]
Invoking pandoc from within LyX (2.2.3 Mac) to produce a .docx is largely successful, but all text tagged as \foreignlanguage is omitted from the output. (These are inline strings of German words. Entire quotation paragraphs preceded by \selectlanguage{ngerman} survive into the output just fine.) 

I have pandoc 2.0.5 installed. Here's the command used by LyX: 
`pandoc -s -f latex -o "Chapter05.docx" -t docx "Chapter05.tex"`

Any help is appreciated. I'm only a philosopher; coding isn't my forte.

**Comment by mb21** [comment]
Indeed, we don't parse this to a native span with lang attr. Minimal repro:

    $ echo '\\foreignlanguage{ngerman}{foo}' | pandoc -f latex -t native
    [RawBlock (Format "latex") "\\foreignlanguage{ngerman}{foo}"]

**Comment by jgm** [comment]
Closed by 9e1d86638ce7ee9e22e0623f77ffe8609f552b15

**Comment by RhvdG** [comment]
Wow, that's fast! Thanks. Looking forward to seeing it in action on a release that I can run.
