### ISSUE TITLE
pandoc output error saying that my file contains invalid utf-8 characters when actually it does not

### ISSUE THREAD

**Issue by jdhao** [jgm/pandoc#4200]
I am using pandoc on my Windows system and when I tried to convert my markdown (mixed with chinese characters and english characters) to  pdf. Error message occured:
>pandoc: Error producing PDF from TeX source.
! Undefined control sequence.
pandoc: Cannot decode byte '\xbd': Data.Text.Encoding.decodeUtf8: Invalid UTF-8 stream

My file is encoded with utf-8 format. Then I tried to filter out those invalid characters, following the instructions [here](https://unix.stackexchange.com/questions/6516/filtering-invalid-utf8/175106?noredirect=1#comment740838_175106):
```
iconv -f utf-8 -t utf-8 -c test.md >output.md
```
Then I tried to convert `output.md` to pdf. Pandoc still output the same error message.  I also tried to grep invalid characters suggested in that post, but can not grep any invalid characters.

### other info

+ I have upload my file [here](https://raw.githubusercontent.com/jdhao/setting_backup/master/test.md).
+ On both the Windows system (Windows 8.1) and Linux system (CentOS 7), pandoc is giving the same error message. 
+ Pandoc version: 2.0.5 (Windows), 1.12.3.1 (Linux).

Can you reproduce this error? This is driving me crazy, I have been wrestling with it for several days but still got no idea what is wrong.

**Comment by mb21** [comment]
The following works for me on macOS:

    curl 'https://raw.githubusercontent.com/jdhao/setting_backup/master/test.md' | pandoc -f markdown -t latex

Maybe GitHub sanitized your input automagically?

**Comment by Wandmalfarbe** [comment]
When you convert the text to PDF then the error persists:

```bash
curl 'https://raw.githubusercontent.com/jdhao/setting_backup/master/test.md' | pandoc -f markdown -o test.pdf --pdf-engine=xelatex
```

```
Error producing PDF.
! Undefined control sequence.
pandoc: Cannot decode byte '\xbd': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream
```

**Comment by mb21** [comment]
I don't have xelatex installed on this machine... but are you saying that the command I posted doesn't work for you? on Windows? CentOS as well?

**Comment by jdhao** [comment]
@mb21, I want to convert my markdown to pdf not latex. On windows systems, the command I use is
```
pandoc --pdf-engine=xelatex -V CJKmainfont=KaiTi test.md -o test.pdf
```
On Linux systems, the command I use is 
```
pandoc --latex-engine=xelatex -V mainfont='WenQuanYi Zen Hei Mono' test.md -o test.pdf
```

I have [asked this question on pandoc-discuss](https://groups.google.com/forum/#!topic/pandoc-discuss/rj6PPl5zyLw), but @jgm said he can not reproduce this error.

**Comment by jdhao** [comment]
On both Windows (with git bash installed)  and Linux system, your command
```
curl 'https://raw.githubusercontent.com/jdhao/setting_backup/master/test.md' | pandoc -f markdown -t latex
```
does not produce any error message. But that is not related to the issue here.  If you convert the markdown to pdf, the error will occur.

**Comment by mb21** [comment]
Pandoc doesn’t create the pdf itself, bit calls the supplied pdf engine. To debug where the error lies you can try:

    pandoc test.md -t latex -o test.tex -s
    xelatex test.tex

**Comment by jdhao** [comment]
Thanks for your hint. I am finally able to solve the problem.
After converting the `test.md` to `test.tex` and then use xelatex to compile the tex file:
```
pandoc -s -t latex -V CJKmainfont=KaiTi test.md -o test.tex
xelatex test.tex
```
The error message changed (no longer UTF-8 related error). `xelatex` produced error messages that complained undefined command.  That is because that there are several places in the text which start with `\`, which are unfortunately recognized as LaTeX command but are perfectly fine for Markdown. For example:
```
* 一般现在时\过去时\将来时，simple present\past\future
* 现在(过去\将来)进行时，present(past\ future) continuous
* 现在（过去\将来）完成时，present(past\future) perfect
* 现在（过去\将来）完成进行时，present(past\future) perfect continuous
```
The above text will cause an error when I try to convert markdown to pdf. If I simply remove the slash or replace slash with other characters or wrap the command in inline code block (e.g., \`\columnwidth\`). I can compile the markdown and generate the pdf file.

It has nothing to do with the UTF-8 encoding of the file, though.  I thought that text starting with slash in markdown should be treated as plain text instead of special command. But apparently, I was wrong.

Is this the expected behaviour of pandoc that we can not include plain text starting with slash in the markdown?

**Comment by jdhao** [comment]
After pinpointing the issue, I found #2790. Indeed, backslash in markdown need to be escaped to produce valid PDF files. 

If I use 
```
pandoc -f markdown-raw_tex --pdf-engine=xelatex -V CJKmainfont=KaiTi test.md -o test.pdf
```
instead of
```
pandoc -f markdown --pdf-engine=xelatex -V CJKmainfont=KaiTi test.md -o test.pdf
```
The problem disappears. I can produce the correct PDF file.

One question remains, though. Why are the error message related to UTF-8 decoding error and not to undefined command. The error message is really misleading and uninformative.

**Comment by tarleb** [comment]
I suspect that this is an issue with XeLaTeX's error reporting. Using `--pdf-engine=lualatex`, I get the error message

    Error producing PDF.
    ! Undefined control sequence.
    l.416 ...宽度有问题，应该把\textwidth换成

So it's the xelatex error which contains the bad UTF-8 character.

**Comment by jdhao** [comment]
But if we separate the pdf-generating steps, i.e., first generate tex file and then generate pdf from tex file (see the code below). The error message will change to `undefined control sequence`. 

## one step way
```
pandoc --pdf-engine=xelatex -V CJKmainfont=KaiTi test.md -o test.pdf
```

## two step way
```
pandoc -s -t latex -V CJKmainfont=KaiTi test.md -o test.tex  # first step
xelatex test.tex # second step
```

 Shouldn't the one step way and two step way be equivalent?

**Comment by tarleb** [comment]
> Shouldn't the one step way and two step way be equivalent?

Yes, absolutely. But I'm afraid there isn't much that we can do about that here. You can see what's going on by running

    pandoc -s -t latex -V CJKmainfont=KaiTi test.md -o test.tex
    xelatex test.tex | tee test.xelatex.output
    iconv -f UTF8 -t UTF8 test.xelatex.output

Which gives me `l.416 ...iconv: illegal input sequence at position 33368`, proving that xelatex produces non-UTF8 characters in its error message. It's probably worth raising an issue for xelatex.

**Comment by jdhao** [comment]
The command `xelatex test.tex` will not finish because there are errors: "undefined control sequence".
Anyway, running `iconv -f utf-8 -t utf-8 test.xelatex.output` gives the following message:
>l.424 ...
iconv: test.xelatex.output:104:9: cannot convert

**Comment by jdhao** [comment]
Thanks to the guru in tex.stackexchange, the cause has been finally found. Essentially, it is xelatex which will produce invalid utf-8 sequence if it encounters invalid control sequence during its processing of tex files. For more information, see [here](https://unix.stackexchange.com/questions/413067/pandoc-continues-complain-about-non-utf8-character-even-though-it-seems-there-is/413212#413212) and [here](https://tex.stackexchange.com/questions/407744/producing-pdf-from-markdown-with-pandoc-and-xelatex-generate-misleading-error-me).

I think one option is to use double slash when you mean literal slash.  Also pandoc may turn off the functionality of recognizing the text start with backslash as LaTeX command by default and let user explicitly turn on it.  I think few user will use LaTeX command inside their markdown files.

**Comment by jgm** [comment]
+++ Jiedong Hao [Dec 28 17 06:09 ]:
>   Thanks to the guru in tex.stackexchange, the cause has been finally
>   found. Essentially, it is xelatex which will produce invalid utf-8
>   sequence if it encounters invalid control sequence during its
>   processing of tex files. For more information, see [1]here and [2]here.

Yes, we've already changed pandoc (in the dev version) so it
won't crash on this error output.
