### ISSUE TITLE
Regression: `sample.lua` custom writer no longer works

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#4202]
```
 % echo "Test" | pandoc -t data/sample.lua
pandoc: PandocLuaException "attempt to call a nil value"
```
@tarleb, is this connected to 0abb9bdc546d8a675bdfae95f0c402b79db19df5?

**Comment by tarleb** [comment]
I'll have a look

**Comment by tarleb** [comment]
It was 4c64af44 which broke it. I'll fix it.

**Comment by tarleb** [comment]
Sorry 'bout that. Could have sworn I tested before committing, but apparently not. Should we add an old-style writer test for Custom?

**Comment by jgm** [comment]
Thanks, I'll add a test.

**Comment by jgm** [comment]
The test revealed another problem, with definition lists.
```
%  .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/pandoc/pandoc -t data/sample.lua 
apple
:   red fruit

orange
:   orange fruit

banana
:   yellow fruit
^D
pandoc: PandocLuaException "[string \"-- This is a sample custom writer for pandoc....\"]:251: bad argument #1 to 'concat' (table expected, got string)"
```
Looking at the code I see
```
-- Revisit association list STackValue instance.
function DefinitionList(items)
```
so I think you meant to fix this earlier...

**Comment by tarleb** [comment]
Looks like I had broken DefinitionList when adding Lua filters. 😞 Fixed now as well.

**Comment by tarleb** [comment]
Argh, I hadn't noticed you had fixed it as well. Which means I broke it again. The fix which I pushed restores the behavior pre-2.0, while yours seems a bit cleaner. Should I revert?

**Comment by jgm** [comment]
I'll revert mine.  I think it's best not to break backwards compatibility; people might have custom writers that rely on the old behavior.
