### ISSUE TITLE
Caption for images not appearing

### ISSUE THREAD

**Issue by noorbakerally** [jgm/pandoc#4203]
I've noticed that caption for images are not appearing in pandoc 1.12.2.1. 

`![Figure 1](file:images/AbstractModelLDPDL.png "Figure 1")`  renders the following HTML
```
<div class="figure">
<img src="file:images/AbstractModelLDPDL.png" title="Figure 1" alt="Figure 1"><p class="caption">Figure 1</p>
</div>
```

However,  
```
<div>
![Figure 1](file:images/AbstractModelLDPDL.png "Figure 1")
</div>
``` 
renders the following HTML without the caption:

```
<div>
<img src="file:images/AbstractModelLDPDL.png" title="Figure 1" alt="Figure 1">
</div>
```

**Comment by mb21** [comment]
This is expected behavior of http://pandoc.org/MANUAL.html#extension-implicit_figures

Try the following (plus upgrading pandoc to the newest version):

    <div>

    <img src="file:images/AbstractModelLDPDL.png" title="Figure 1" alt="Figure 1">

    </div>
