### ISSUE TITLE
Bug in mediawiki -> markdown transforming table containing piped link

### ISSUE THREAD

**Issue by masonicboom** [jgm/pandoc#4210]
Given this mediawiki input,
```
{|
|-
! A !! B !! C
|-
| 1 || 2 || 3
|-
| x || y || [[link|text]]
|}
```

and this CLI invocation (pandoc version 2.0.5),
`pandoc --from=mediawiki --to=markdown-simple_tables-multiline_tables-grid_tables-fenced_code_blocks tablelink.mediawiki
`
output is:
```
| A   | B   | C        |          |
|-----|-----|----------|----------|
| 1   | 2   | 3        |          |
| x   | y   | \[\[link | text\]\] |
```

Note the 4th column introduced in the last table row.

It looks like the parser is treating the link's pipe without regard to the context (it's in a link).

**Comment by link2xt** [comment]
This bug is already fixed, pandoc 2.7.3 outputs:
```
| A   | B   | C                       |
|-----|-----|-------------------------|
| 1   | 2   | 3                       |
| x   | y   | [text](link "wikilink") |
```
