### ISSUE TITLE
Numbering problems with alphanumeric items markdown to epub

### ISSUE THREAD

**Issue by trevor87** [jgm/pandoc#4211]
Hi everyone,

first of all thanks for your great work!

When converting from markdown to epub I encountered the following unexpected behaviour: My document contains a list with an alphanumeric item (after "9." the next item is" 9a."). This numbering cannot be changed because it is a legal document that has to keep this numbering.

The problem is that pandoc seemingly does not recognize "9a." as a part of the numbering and because of that the whole list numbering including the formatting breaks. Neither in the manual nor in the issues could I find a way to modify this behaviour. Is it somehow possible or is this a bug?

Here is an example (one hyphen stands for one indent):

>-9.  
>----a) 
>----b) 
> 
>-9a. 
>----a) 
>----b) 
> 
>-10.

Gets converted to this:

>-9.
>----a.
>----b.
>-9a.
>-a)
>-b)
>-10.

Another issue regarding lists is that "(1)" gets transformed to "1." and thus causes a confusing numbering.

Example:

> (1)
> 1. 
>     a)

turns to:

> 1. 
> 1. 
>     a.

Thanks and keep up the good work!

**Comment by mb21** [comment]
Markdown really only know unordered and [ordered lists](http://pandoc.org/MANUAL.html#ordered-lists). However, you can always use custom CSS to provide the generated `<ol>` with custom list markers...

**Comment by trevor87** [comment]
But is not the Problem with "9a." that it doesn't even get recognized as a list element, so that custom CSS could not be used here?

**Comment by jgm** [comment]
It's not a bug.  When you're converting from markdown, you need to use markdown syntax. Markdown doesn't allow list items like this (not even with pandoc extensions).

You can have something like this:

```
1. a) one
   b) two
```

but you can't have a list item `1a`.

**Comment by trevor87** [comment]
Hm I thought so.. Well then I have to find some workaround. Thanks for your help!
