### ISSUE TITLE
Add support for dpub-aria in HTML output

### ISSUE THREAD

**Issue by xi** [jgm/pandoc#4213]
The [Digital Publishing WAI-ARIA Module 1.0](https://www.w3.org/TR/dpub-aria/) has recently become a W3C recommendation. It contains semantic structures that are derived from EPUB. I think that these that are well suited for many of pandoc's usecases.

The relevant parts are:

- Use `doc-endnotes`, `doc-endnote`, `doc-noteref`, and `doc-backlink` roles for footnotes.
- Use `doc-bibliography`, `doc-biblioentry`, and `doc-biblioref` roles for bibliography.
- Use `doc-toc` role for auto-generated table of contents.

Unfortunately, I do not know enough haskell to implement this myself.

See also https://github.com/michelf/php-markdown/pull/287

**Comment by mb21** [comment]
This would only require changes to https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/HTML.hs

**Comment by labdsf** [comment]
@mb21 why not also reader?

**Comment by mb21** [comment]
@labdsf as I understood, this was only about output.. but sure, input can be considered as well... just parse them to `Attr`?

**Comment by labdsf** [comment]
HTML reader does not parse footnotes/endnotes now, but given these attributes, it can.

**Comment by jgm** [comment]
+++ Alexander [Dec 30 17 12:27 ]:
>   HTML reader does not parse footnotes/endnotes now, but given these
>   attributes, it can.

Yes, this would be worth doing, though a bit complex.
Probably the easiest way would be to store the note
references as Spans a special attribute, and store the notes
themselves as Divs with a special attribute.  Then, after
parsing, apply an AST transformation that matches these
and converts the Spans into regular notes.

**Comment by Porges** [comment]
I just came here looking for this. Might tackle a few things myself...

**Comment by jgm** [comment]
Closing this because the writer parts have been implemented.
I'll open a new issue for the reader.
