### ISSUE TITLE
LaTeX writer: columns after a block are broken

### ISSUE THREAD

**Issue by trou** [jgm/pandoc#4220]
Hello,
the fix for #4016 is good for one case: blocks inside columns, but columns after a block are still broken.

From my MarkDown source, using pandoc 2.0.6

```md
## Bug example

### Block title

* item

<div class="columns">
<div class="column" width="60%">

### Inside block 1

* item 1

</div>
<div class="column" width="40%">

### Inside block 2

* item 2


</div>
</div>
```

outputs:
```tex
\begin{frame}{%
\protect\hypertarget{bug-example}{%
Bug example}}

\begin{block}{Block title}

\begin{itemize}
\tightlist
\item
  item
\end{itemize}

\begin{columns}[T]
\begin{column}{0.60\textwidth}
\begin{block}{Inside block 1}

\begin{itemize}
\tightlist
\item
  item 1
\end{itemize}

\end{block}
\end{column}

\begin{column}{0.40\textwidth}
\begin{block}{Inside block 2}

\begin{itemize}
\tightlist
\item
  item 2
\end{itemize}

\end{block}
\end{column}
\end{columns}

\end{block}

\end{frame}
```
as you can see, the top block is not closed when `columns` are created.

**Comment by jgm** [comment]
It is closed.  The last `\end{block}` closes the first `\begin{block}`.  As far as I can see, all the pairs of begins and ends are properly matched and nested.

I suppose you expected the top block to be closed before the columns div.  But that's not how it works.    In general, we need the ability to put columns inside blocks.

Try this:
```
## Bug example

<div>
### Block title

* item
</div>

<div class="columns">
<div class="column" width="60%">

### Inside block 1

* item 1

</div>
<div class="column" width="40%">

### Inside block 2

* item 2


</div>
</div>
```

**Comment by trou** [comment]
It works indeed ! Sorry for the confusion and thanks for the tip.
