### ISSUE TITLE
Lua filters: Citation field names don't match documentation

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#4222]
In the docs, the field names are listed as:

    Citation (id, mode[, prefix[, suffix[, note_num[, hash]]]])

In practice, the fields seem to be

    citationSuffix
    citationId
    citationHash
    citationPrefix
    citationNoteNum
    citationMode

according to this filter:

```lua
function Cite(el)
   for _, c in pairs(el.citations) do
      for k, _ in pairs(c) do
	 print(k)
      end
   end
   os.exit(0)
end
```

**Comment by tarleb** [comment]
Related: Citations don't share a common metatable, which makes it difficult to add new behavior.
