### ISSUE TITLE
running tests on 32-bit run out of memory

### ISSUE THREAD

**Issue by andreasbaumann** [jgm/pandoc#4224]
Running 1 test suites...
Test suite test-pandoc: RUNNING...
Setup: out of memory (requested 1048576 bytes)
==> ERROR: A failure occurred in check().
    Aborting...

Happened on Archlinux32.

**Comment by tarleb** [comment]
This might be related to 32bit issues as discussed in #3805. Can you give us more information on your setup? I.e., are you using stack, cabal, or cabal new-test to compile? With haskell packages installed via pacman, or stack/cabal? Could you try setting the `lua_32bits` flag for hslua (see the [hslua README](https://github.com/hslua/hslua#build-flags))?

**Comment by andreasbaumann** [comment]
Ah. Ok. So its in haskell-hslua and the flag is set to `-f-lua_32_bits`. We are currently on the split
of Archlinux and Archlinux32 and sometimes things get lost. :-)
Thanks, I'll try and report back.

**Comment by mb21** [comment]
Feel free to reopen with more info... then again, 32bit is on the way out...
