### ISSUE TITLE
Massive performance difference between Pandoc <2 and >2 for minimal Markdown input files

### ISSUE THREAD

**Issue by simon-kr** [jgm/pandoc#4226]
Since any Pandoc version from 2.0, the conversion time from Markdown to X for small inputs has significantly risen. I generate PDF files in Rails with lots (1000+) of snippets of Markdown that need to be converted to LaTeX separately and have recognized massively slower performance. I was using Pandoc 1.16. beforehand, because it was the newest version in my Ubuntu distribution. I now want to use Lua filters and recognized the performance degradation:

My test setup:

Input: `__HelloWorld__`
Task: Convert 50 times from Markdown to LaTeX

Ruby source code:
```ruby
start = Time.now
50.times { `#{ARGV[0]}` }
puts "#{((Time.now - start) * 1000).round(3)} ms running time"
```

Ruby call:
```ruby
ruby timer.rb "pandoc -t html minimal.txt > minimal.html"
```

Test results:
> 1.16.0.2 ---- 147.791 ms running time
> 1.19.2.1 ---- 133.611 ms running time
> 2.0 ---------- 11673.897 ms running time 
> 2.0.5 -------- 12621.895 ms running time
> 2.0.6 -------- 12484.951 ms running time

**Since version 2.0, the processing time is nearly 100 times(!) slower**

It seems to be the Markdown reader because the output format does not seem to matter, and the other way round, it's much faster. This seems to have nothing to do with #4216 (and my ticket #4225 ;-) ) as the degradation started with 2.0

**Comment by jkr** [comment]
I'm actually not sure if it has anything to do with a specific reader. I'm actually getting the same slowdown (~10-fold) on `pandoc --version`.

Comparing my stack-built HEAD with a binary ripped out of a downloaded 1.19.2.4 deb. I can't build 1.19.2.4 because of the templates change.

**Comment by jgm** [comment]
I can confirm this with my own tests (using `bench` from Hackage, pandoc 2.0.6 from the binary OSX package, and pandoc 1.19.2 from the binary OSX package).

```
pandoc --version
2.0.6 : 27.5ms
1.19.2:  23.11 ms

echo "Hello" | pandoc
2.0.6: 177.6 ms
1.19.2: 25.88 ms
```
Similar slowdowns with `pandoc -f html` and `pandoc -f latex`, so it's not specific to the Markdown reader.

When I tried with a larger input (MANUAL.txt), I got 757 ms vs 447 ms, a difference of 310 ms.  That suggests that the slowdown is not entirely attributable to a startup cost.

Troubling!  I suspect this has something to do with the move to PandocMonad, though when we benchmarked this before we only saw a ~10% performance change.

Next step, profiling.

**Comment by jgm** [comment]
@simon-kr how did you install pandoc 2.x?  Our binary package or self-compiled? If compiled, how did you compile it (I want to make sure optimizations were used).

**Comment by simon-kr** [comment]
All versions used where from the precompiled deb Files.

Am 05.01.2018 10:47 nachm. schrieb "John MacFarlane" <
notifications@github.com>:

**Comment by jgm** [comment]
Based on profiling, I'm pretty sure some of this has to do with skylighting:
```
        Fri Jan  5 14:05 2018 Time and Allocation Profiling Report  (Final)
  
           pandoc +RTS -K16m -P -RTS

        total time  =        0.07 secs   (74 ticks @ 1000 us, 1 processor)
        total alloc = 246,795,800 bytes  (excludes profiling overheads)

COST CENTRE                  MODULE                          SRC                                                %time %alloc  ticks     bytes

get                          Data.Text                       Data/Text.hs:(369,5)-(373,31)                       40.5   27.1     30  66863888
decodeUtf8With.\             Data.Text.Encoding              Data/Text/Encoding.hs:(132,59)-(153,35)              6.8    1.2      5   2844184
decodeUtf8With.\.go.\.\.loop Data.Text.Encoding              Data/Text/Encoding.hs:(136,15)-(151,50)              4.1    0.9      3   2221136
syntax                       Skylighting.Syntax.Lilypond     src/Skylighting/Syntax/Lilypond.hs:12:1-122671       4.1    2.0      3   4938328
syntax                       Skylighting.Syntax.Jsp          src/Skylighting/Syntax/Jsp.hs:12:1-277140            4.1    4.6      3  11424984
decodeUtf8With.\.go.\        Data.Text.Encoding              Data/Text/Encoding.hs:(134,9)-(152,34)               2.7    3.8      2   9471176
syntax                       Skylighting.Syntax.Scala        src/Skylighting/Syntax/Scala.hs:12:1-162720          2.7    2.8      2   6918344
syntax                       Skylighting.Syntax.Mediawiki    src/Skylighting/Syntax/Mediawiki.hs:12:1-92769       2.7    1.3      2   3179032
missingIncludes              Skylighting.Parser              src/Skylighting/Parser.hs:(34,1)-(39,39)             2.7    0.1      2    283480
MAIN                         MAIN                            <built-in>                                           1.4    0.0      1     23592
CAF                          GHC.IO.Encoding.Iconv           <entire-module>                                      1.4    0.0      1       200
decodeUtf8With               Data.Text.Encoding              Data/Text/Encoding.hs:(132,1)-(155,71)               1.4    0.0      1         0
parserReturn.\               Text.Parsec.Prim                Text/Parsec/Prim.hs:234:7-30                         1.4    0.0      1     21816
syntax                       Skylighting.Syntax.Sql          src/Skylighting/Syntax/Sql.hs:12:1-40142             1.4    0.6      1   1461752
syntax                       Skylighting.Syntax.Sci          src/Skylighting/Syntax/Sci.hs:12:1-45351             1.4    0.7      1   1622848
syntax                       Skylighting.Syntax.Ruby         src/Skylighting/Syntax/Ruby.hs:12:1-86396            1.4    1.1      1   2809224
syntax                       Skylighting.Syntax.Roff         src/Skylighting/Syntax/Roff.hs:12:1-18922            1.4    0.2      1    611792
syntax                       Skylighting.Syntax.Python       src/Skylighting/Syntax/Python.hs:12:1-46182          1.4    0.6      1   1576616
syntax                       Skylighting.Syntax.Perl         src/Skylighting/Syntax/Perl.hs:12:1-76272            1.4    1.0      1   2469456
syntax                       Skylighting.Syntax.Octave       src/Skylighting/Syntax/Octave.hs:12:1-88826          1.4    1.3      1   3252368
syntax                       Skylighting.Syntax.Objectivecpp src/Skylighting/Syntax/Objectivecpp.hs:12:1-20780    1.4    0.3      1    694040
syntax                       Skylighting.Syntax.Nasm         src/Skylighting/Syntax/Nasm.hs:12:1-32785            1.4    0.5      1   1118464
syntax                       Skylighting.Syntax.Mathematica  src/Skylighting/Syntax/Mathematica.hs:12:1-140167    1.4    2.3      1   5746384
syntax                       Skylighting.Syntax.Markdown     src/Skylighting/Syntax/Markdown.hs:12:1-9137         1.4    0.1      1    315136
syntax                       Skylighting.Syntax.Java         src/Skylighting/Syntax/Java.hs:12:1-181803           1.4    3.1      1   7725992
syntax                       Skylighting.Syntax.Haskell      src/Skylighting/Syntax/Haskell.hs:12:1-39588         1.4    0.6      1   1383928
syntax                       Skylighting.Syntax.Doxygen      src/Skylighting/Syntax/Doxygen.hs:12:1-60395         1.4    0.8      1   2066304
syntax                       Skylighting.Syntax.Cpp          src/Skylighting/Syntax/Cpp.hs:12:1-92317             1.4    1.6      1   3939568
syntax                       Skylighting.Syntax.Cmake        src/Skylighting/Syntax/Cmake.hs:12:1-76524           1.4    1.2      1   3053184
syntax                       Skylighting.Syntax.Bash         src/Skylighting/Syntax/Bash.hs:12:1-87240            1.4    1.2      1   2841320
syntax                       Skylighting.Syntax.Abc          src/Skylighting/Syntax/Abc.hs:12:1-6151              1.4    0.1      1    191016
decodeUtf8With.\.go.\.\      Data.Text.Encoding              Data/Text/Encoding.hs:(134,42)-(152,34)              0.0    1.6      0   3899896
syntax                       Skylighting.Syntax.Rhtml        src/Skylighting/Syntax/Rhtml.hs:12:1-112423          0.0    1.5      0   3810536
syntax                       Skylighting.Syntax.Purebasic    src/Skylighting/Syntax/Purebasic.hs:12:1-80851       0.0    1.3      0   3300424
syntax                       Skylighting.Syntax.Php          src/Skylighting/Syntax/Php.hs:12:1-268386            0.0    4.5      0  11076736
syntax                       Skylighting.Syntax.Maxima       src/Skylighting/Syntax/Maxima.hs:12:1-77513          0.0    1.2      0   3022656
```

Older versions of ghc were requiring a ton of memory to compile the > 100 syntax definitions, and the workaround we found was to store the definitions as encoded strings which could be decoded at runtime.  Maybe back to the drawing board...

**Comment by jgm** [comment]
Confirmed.  Taking out the loading of the default syntax map fixes the problem, as far as I can see.
But this will need a fix on the skylighting side.  If we can go back to precompiled syntax definitions, that would be the best thing.

**Comment by jgm** [comment]
If we can't go back to procompiled definitions, then setting up a system where we can load just the definitions we need, when we need them, would be best.

**Comment by jgm** [comment]
The commit I just pushed (3a22907) seems to fix the problem, at least if you're not using custom syntax definitions.

Ultimately I think we should probably just avoid using `missingIncludes` at all, even if the user specifies a custom syntax definition.  Checking this up front requires evaluating every syntax definition.  Could we catch this at run time and raise an informative exception?

**Comment by jgm** [comment]
It would also make sense to change `missingIncludes` so that it checks a particular syntax, rather than globally looking at every syntax.

**Comment by jgm** [comment]
```
% bench 'echo "hello" | pandoc-2.0.6/bin/pandoc'
benchmarking echo "hello" | pandoc-2.0.6/bin/pandoc
time                 203.0 ms   (187.5 ms .. 222.9 ms)
                     0.995 R²   (0.990 R² .. 1.000 R²)
mean                 194.1 ms   (190.0 ms .. 201.3 ms)
std dev              7.077 ms   (1.651 ms .. 9.574 ms)
variance introduced by outliers: 14% (moderately inflated)

% bench 'echo "hello" | pandoc-2.1/bin/pandoc'
benchmarking echo "hello" | pandoc-2.1/bin/pandoc
time                 35.28 ms   (34.51 ms .. 36.56 ms)
                     0.996 R²   (0.990 R² .. 1.000 R²)
mean                 36.14 ms   (35.57 ms .. 37.56 ms)
std dev              1.693 ms   (631.5 μs .. 2.906 ms)
variance introduced by outliers: 12% (moderately inflated)
```

**Comment by jgm** [comment]
@simon-kr why don't you try the latest version 2.1?
I think the probelm is solved, but it would be good
to have you confirm this with your setup.

**Comment by simon-kr** [comment]
@jgm First of all Thanks for your speedy reaction and bug fixes / implementation

I did run it today with the new version and am happy about the result:
> 2.1 ---------- 186.252 ms running time

So it's back to normal again, great!
