### ISSUE TITLE
LaTeX reader - long captions with multiple paragraphs

### ISSUE THREAD

**Issue by mikecee** [jgm/pandoc#4229]
Pandoc doesn't seem to  be able to handle multiple paragraphs in the default option to a `figure`'s `caption`.  (Possibly related:  jgm/pandoc/#766).  

With Pandoc 2.0.6 (compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.5.0.1), the following MWE can be used to reproduce the problem:

```latex
\documentclass{article}

\begin{document}
    \begin{figure}
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, etc.
        \caption[Short caption]{This is the long caption for this awesome ode to a typesetter's art,
        as evinced by the Latin contained herein.

        This caption contains more than one paragraph. This happens frequently with figures that use
        longer captions to clarify points of interest in the attached figure.}
    \end{figure}
\end{document}
```

**Note that the figure here is plain text - not an image.**  Running `pdflatex` on the MWE works happily, producing a Figure with long caption:
[mwe.pdf](https://github.com/jgm/pandoc/files/1610716/mwe.pdf)

Running pandoc gives:
```shell
$ pandoc -f latex -t markdown mwe.tex

Error at "source" (line 9, column 1):
unexpected ()
        This caption contains more than one paragraph. This happens frequently with figures that use
^
```

For comparison, using a slightly-less minimal MWE which includes an image instead of just text:
```latex
\documentclass{article}
\usepackage{graphicx}
\begin{document}
    \begin{figure}
        \includegraphics[totalheight=0.75\textheight]{picture}
        %Lorem ipsum dolor sit amet, consectetur adipiscing elit, etc.
        \caption[Short caption]{This is the long caption for this awesome ode to a typesetter's art,
        as evinced by the Latin contained herein.

        This caption contains more than one paragraph. This happens frequently with figures that use
        longer captions to clarify points of interest in the attached figure.}
    \end{figure}
\end{document}
```

Allowing for a change in line number, the result seems to be the same:
```
$ pandoc -f latex -t native mwe.tex

Error at "source" (line 10, column 1):
unexpected ()
        This caption contains more than one paragraph. This happens frequently with figures that use
^
```

So, multi-paragraph captions seem to be independent of the figure content.

Removing the inter-paragraph blank line in each of these MWEs (i.e. making the caption a single paragraph) works in the sense that pandoc no longer returns an error.

However, for the first MWE (text figure), neither the short or long caption text is handled:

```shell
$ pandoc -f latex -t native mwe.tex
[Para [Str "Lorem",Space,Str "ipsum",Space,Str "dolor",Space,Str "sit",Space,Str "amet,",Space,Str "consectetur",Space,Str "adipiscing",Space,Str "elit,",Space,Str "etc."]]
```

Pandoc runs without reporting an error, but the caption text has totally disappeared.  Granted, not all the output formats support captioned figures, but if the captions aren't in the AST, then even the most carefully coded Writer is probably going to have difficulty providing support :-)

The behavior that I'd expect to see is at least one of:
(1) Pass through the captions, unaltered or as raw LaTeX 
(2) Some kind of placeholder in the AST, with caption(s) attached.
(3) An error or warning message that the LaTeX reader can only process captions which are a single paragraph.

Not sure if this is a bug or feature request :-/

**Comment by jgm** [comment]
See #3177.  Ultimately it would be good to allow block content in captions, and non-image content in figures. In the mean time, though, we might be able to do something better with this.

**Comment by mb21** [comment]
Closing in favour of #3177, feel free to comment with use-cases for multi-paragraph captions there!
