### ISSUE TITLE
lua filters can't access distro-installed lua libs (package.path setting)

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#4230]
Linux distros usually install libraries under `/usr/share`, but the embedded lua doesn't look there -- only in `/usr/local`. Issue and possible fix below.

System lua `package.path`:

~~~
/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua
~~~

Embedded lua `package.path`:

~~~
/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua
~~~

One easy fix (that I've already implemented at a user level), is to change `init.lua`, something like:

~~~lua
package.path = table.concat({"/usr/share/lua/5.3/?.lua",
			     "/usr/share/lua/5.3/?/init.lua",
			     "/usr/lib/lua/5.3/?.lua",
			     "/usr/lib/lua/5.3/?/init.lua",
			     package.path}, ";")
~~~
But I don't know enough to know whether there are advantages to compiling it in, or how the order works. But it does seem that easy access to distro-installed libs (penlight, lpeg, etc) would be good.

**Comment by tarleb** [comment]
I'm not sure whether we can fix this other than by adding better documentation.  The issue is that hslua comes with its own lua interpreter, which uses some default value for `package.path`. HsLua *does* come with a `system-lua` flag, which causes cabal to build with an external Lua.  After running

    stack install --flag=hslua:system-lua --flag=hslua:use-pkgconfig

the following commands give me the same output (on Ubuntu, with package liblua5.3-dev installed):

    pandoc --lua-filter <(echo 'print(package.path)') -o /dev/null /dev/null
    lua -e 'print(package.path)'

It's a bit more difficult when using cabal:

    cabal install hslua --force-reinstalls --flag=system-lua --flag=use-pkgconfig
    cabal install hslua-module-text --force-reinstalls
    cabal install

Personally, I'm using locally installed packages from luarocks and set the `LUA_PATH` environment variable by running `eval "$(luarocks path)"` somewhere in my init files.

**Comment by jkr** [comment]
I had thought about doing it at the `init.lua` level as above (along with the requiring of the various pandoc modules). But it might not be a big enough deal to merit worrying about, since it's not too hard for users to take care of it themselves.

**Comment by tarleb** [comment]
One thing I worry about it that this would further users' believe that they can use any pre-installed lua package from the default pandoc as downloadable from github. However, that version doesn't include a linker (see #3986), so lua packages build using C modules are unusable with stock pandoc.

**Comment by jkr** [comment]
Makes sense and since it's easily fixable at a user leave, I'll close. I'll put up a PR door docs on this later.

**Comment by alerque** [comment]
For anybody else landing on this thread Googling for archaic errors, the fix described above is the right track but the flag names for HSLua seem to have changed sometime in the last 3 years. I got some love out of `stack build` to generate a Pandoc binary that plays nice with my system Lua paths like this:

```console
$ stack build \
    --flag 'pandoc:embed_data_files' \
    --flag 'hslua:system-lua' \
    --flag 'hslua:pkg-config'
```

Note the change from earlier comments: `hslua:use-pkgconfig` is now `hslua:pkg-config`.

**Comment by alerque** [comment]
For completeness since I just found myself debugging this issue all over again and landing on this page while Googling, the flags have changed again a while back when hslua offloaded the lua bindings to a lua package:

```
		--flag 'lua:system-lua' \
		--flag 'lua:pkg-config' \
```
