### ISSUE TITLE
v2.1 crashes on Win 10 just trying to --version

### ISSUE THREAD

**Issue by mchalkley** [jgm/pandoc#4231]
I just installed the new version (using Chocolatey, then by uninstalling and reinstalling using the msi), but Pandoc 2.1 won't run at all.  One of the messages I got is pasted below.  Is there some way I can get the previous version to use for now?

Thanks,

Mark

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The paging file is too small for this operation to complete. (Exception from HRESULT: 0x800705AF)
   at shim.ShimProgram.Main(String[] args)

**Comment by mb21** [comment]
The exception you posted seems to be related to chocolatey: https://github.com/chocolatey/shimgen/issues/19

Can you tell us exactly what happens if you run the pandoc from the msi-installer?

**Comment by mchalkley** [comment]
Using your information, I determined that the Chocolatey install was apparently still interfering with the pandoc msi one.  After removing it completely from Chocolatey's configuration, rebooting, then reinstalling from the msi again, it's working.  Thank you for your help!

**Comment by mb21** [comment]
That's good to hear...
