### ISSUE TITLE
Extension for Referencing Numbered Headers by Their Number

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4232]
It would be nice to have a new extension that allows implicit references to a Header by it's header number.

For example, suppose in our document there is a section with a very long header:

```
### Unelievably Long Header
```

and that somewhere in the document we want to link-reference that header by its header number. Since header numbers are auto-generated at build time, we don't have means to reference its final number. Also, changes in the document structure will cause changes in the headers numbering.

The proposed syntax is:  

```
For more info see section [@Unelievably Long Header].
```

which in the final document would be somthing like:

    For more info see section 3.4.8.

where "3.4.8" is a link to "Unelievably Long Header".

Its syntax would be a hybrid between the syntax of `implicit_header_references` and `example_lists` extensions, so it should be intuitive and familiar to pandoc users. Basically, the addition of a `@` in an implicit header references is telling pandoc to substitute the link text with the number that the referenced header will take in the final document.

Currently to achieve this one needs to use reference style links, checking the actual section numbers in the final document, and manually updating their numbers in the source whenever there are changes in the sections structure.

**Comment by mb21** [comment]
Indeed... sounds like the same issue as https://github.com/jgm/pandoc/issues/813

**Comment by tajmone** [comment]
Thanks for pointing out #813, I hand't seen it. Maybe the headers numbering case is simpler though, as the current extension for `implicit_header_references` could be tweaked to handle the `@` independently of Figures. (I haven't worked with Figures so far, nor LaTex, so I'm not really aware of how these work in pandoc).

The `[@Some Header]` syntax should also be able to handle cases in which the given header is not actually numbered (either because it was individually singled out to be unnumbered, or because the document is being built without the headers numbering option) — in such cases, the link should dispaly just the Header text in the link, as a fallback. 

Syntax-wise, it seems a straight forward case (at least theorically), but of course I have no idea of how this could complicate building the AST of a doc and its output conversion in real practice.

**Comment by jgm** [comment]
Closing as a dup of #813.  Workaround until we have something better is to use the `pandoc-crossref` filter, which works well for this.

**Comment by tajmone** [comment]
Thanks a lot for pointing out `pandoc-crossref` filter @jgm! It's really a great tool and solved my problem.

I've been playing with it a couple of hours now, and finally got a grip on it. Powerful tool indeed. Also comes with precompiled Windows binaries. Couldn't really ask for more!
