### ISSUE TITLE
Multiline content in tables forces width percentage

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#4234]
The following code:

``` .html
<table>
  <tr>
    <td><strong>ID</strong></td>
    <td>ID-1</td>
  </tr>
  <tr>
    <td><strong>Steps</strong></td>
    <td>
      <div>
        <ol>
          <li>One</li>
          <li>Two</li>
          <li>Three</li>
        </ol>
      </div>
    </td>
  </tr>
</table>
```

When run against PR https://github.com/jgm/pandoc/pull/4223 :

    pandoc --toc --toc-depth=2 -t context --top-level-division=chapter -o filename.tex filename.html

Produces the following content:

``` .tex
\startplacetable[location=none]
\startxtable
\startxtablebody[body]
\startxrow
\startxcell[align=right,width={0.50\textwidth}] {\bf ID} \stopxcell
\startxcell[align=right,width={0.50\textwidth}] ID-1 \stopxcell
\stopxrow
\stopxtablebody
\startxtablefoot[foot]
\startxrow
\startxcell[align=right,width={0.50\textwidth}] {\bf Steps} \stopxcell
\startxcell[align=right,width={0.50\textwidth}] 

\startitemize[n,packed]
\item
  One
\item
  Two
\item
  Three
\stopitemize

 \stopxcell
\stopxrow
\stopxtablefoot
\stopxtable
\stopplacetable
```

This is due to:

https://github.com/jgm/pandoc/blob/78b142b880730bceaae7b9c0491e7f645d133380/src/Text/Pandoc/Readers/HTML.hs#L520-L524

Where the `isSimple` is `True` iff there are only empty or `Plain` cell contents (no `Para` or `Div` etc.) Only if there might be multiline content the columns get widths assigned.

This behaviour mixes content with presentation logic and precludes the possibility of the typesetting engine determining ideal widths based on font metrics.

I'd like to request that an extension be added to the ConTeXt writer to suppress injecting table widths at any time.

**Comment by jgm** [comment]
So is the context xtable environment (unlike latex table environments) always able to figure out optimal column widths?

I'm reluctant to throw away width information, because sometimes the author needs the flexibility to specify a certain width, and pandoc's table formats give you that.

**Comment by DaveJarvis** [comment]
> I'm reluctant to throw away width information, because sometimes the author needs the flexibility to specify a certain width, and pandoc's table formats give you that.

From http://www.pragma-ade.nl/general/manuals/xtables-mkiv.pdf:

> If you don’t give the width of a cell, the widest natural size will be taken. Otherwise the given width
applies to the whole column.

I don't know if this means it is optimal.

**Comment by hmenke** [comment]
That's not an issue in the ConTeXt writer.  Please remove it from the issue title.  The ConTeXt writer behaves properly in that it assigns width to column if those are forwarded from the reader.

**Comment by jgm** [comment]
The underlying issue is that many output formats require relative width information for tables, when the cells can contain multiline content.  ConTeXt evidently doesn't, but we need to encode this information in the AST.  So the HTML reader is ok.  What about the ConTEXt writer? Could we tell it to ignore the width information?  This would be a bad idea, because in some cases the width information is intended and needed.

An alternative approach, though it would be quite a bit of work, would be to use 0 widths when widths aren't specified (as in the above HTML sample), and have the writers that require widths compute the widths, rather than the readers. This would give better results in the above case, but it would require touching all of the readers and quite a few writers.

**Comment by DaveJarvis** [comment]
A kludge would be a command-line option that forces `isSimple` to `true`. If that would have knock-on effects, an alternative would be to change line 521 to:

     then if isSimple || suppressTableWidths

Then:

    pandoc -t context --suppress-table-widths ...

There are other cases where the table widths are written using a computed value even though no tables widths are specified in the corresponding HTML/Markdown tables and no multi-line content is present. When time allows, I'll post an example.

**Comment by jgm** [comment]
You could always use a lua filter to set table widths to 0.

+++ Dave Jarvis [Jan 11 18 02:18 ]:
>pandoc -t context --suppress-table-widths ...
>
>   There are other cases where the table widths are written using a
>   computed value even though no tables widths are specified in the
>   corresponding HTML/Markdown tables and no multi-line content is
>   present. When time allows, I'll post an example.

**Comment by DaveJarvis** [comment]
> You could always use a lua filter to set table widths to 0.

I have tried that -- the Windows 7 32-bit build from @hmenke crashes immediately. However, even if the crash didn't occur, it's still far faster to write a one-liner sed script to modify the output:

``` .bat
sed -i "s/\/xwiki/.\/images/g" %TEX%
sed -i "s/location=none/location={split,here,repeat}/g" %TEX%
sed -i "s/\[align=right.*]//g" %TEX%
```

In theory, issues could occur with modifying the document this way (without an AST context). In practice, the one-liners work to modify the `.tex` file.

**Comment by jgm** [comment]
You need to build hslua with a special flag on 32-bit windows, I
believe.

+++ Dave Jarvis [Jan 11 18 19:25 ]:

**Comment by hmenke** [comment]
It's not really “my build”.  It is merely the artifact you can download from AppVeyor CI: https://ci.appveyor.com/project/hmenke/pandoc/build/artifacts

**Comment by jgm** [comment]
I suspect the segfault on Windows 7 with 32-bit pandoc is the same issue as #4283.
Try the new 64-bit build.

**Comment by mb21** [comment]
Upon reading this again closer, we cannot fix this without completely changing the way we do table widths (which would be a separate issue), thus closing.

**Comment by DaveJarvis** [comment]
Instead of writing a Lua filter, providing a large columns value also removes the hard-coded widths:

```  bash
pandoc --columns=10000 -f markdown -t context filename.md
```

Produces:

``` tex
\startplacetable[title={Note on the regulation of my household expenses}]
\startxtable
\startxtablebody[body]
\startxrow
\startxcell For the little seminary \stopxcell
\startxcell 1,500 livres \stopxcell
\stopxrow
```
