### ISSUE TITLE
long text in pipe table does not wrap in pdf

### ISSUE THREAD

**Issue by tewarid** [jgm/pandoc#4239]
Assuming

```
$ pandoc --version
pandoc 2.0.2
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.4.3.2
``` 

A md document such as
```
| Name               | Value    | Description        | Additional Comment |
|--------------------|----------|--------------------|--------------------|
| SOME_LONG_VARIABLE_NAME | 00 (default) | Description of SOME_LONG_VARIABLE_NAME | Some additional comment about SOME_LONG_VARIABLE_NAME |
```

when rendered to pdf using
```
pandoc test.md -f markdown_github -o test.pdf
```

renders as

![screen shot 2018-01-10 at 07 39 51](https://user-images.githubusercontent.com/838284/34768565-f46b35a2-f5d9-11e7-92d1-77e08776a5eb.png)

when rendered to PDF using
```
pandoc test.md -f gfm -o test.pdf
```

renders as (text off the page)

![screen shot 2018-01-10 at 07 40 29](https://user-images.githubusercontent.com/838284/34768640-2e6d693c-f5da-11e7-9948-b89450c2f968.png)

See also #2471.

**Comment by wilx** [comment]
It is the underscore that disables the line breaking algorithm in LaTeX. You can fix this by adding `--include-in-header=table.header.tex` to your command line, where the `table.header.tex` file contains just this line:

```latex
\usepackage{underscore}
```

**Comment by tewarid** [comment]
@wilx That works. Thanks!

Any suggestion for camel case?

```
| Name               | Value    | Description        | Additional Comment |
|--------------------|----------|--------------------|--------------------|
| SomeLongVariableName | 00 (default) | Description of SomeLongVariableName | Some additional comment about SomeLongVariableName |
```
renders as 

![screen shot 2018-01-10 at 08 28 09](https://user-images.githubusercontent.com/838284/34770634-5f3c8038-f5e0-11e7-845e-bdf0d3bca6bc.png)

**Comment by wilx** [comment]
Who is generating the documentation/table? If you can insert soft hyphen (U+00AD) character to the right places, you could use my [`uspace`](https://ctan.org/pkg/uspace) LaTeX package. Alternatively, you could list all of these in the header like `\hyphenation{Some-Long-Variable-Name}` to let LaTeX know where to hyphenate.

**Comment by wilx** [comment]
Also, somebody has already asked this before and there is also a LaTeX solution (with some limitations): [hyphenation - Automatic camel case breaking - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/66593/automatic-camel-case-breaking)
