### ISSUE TITLE
DOCX header level pushed if preceded by link target (from RST)

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#4240]
Pandoc version 2.1

RST to DOCX problem

Here an example a.txt:

```
=====
Title
=====

--------
Subtitle
--------

header1
=======

header2
-------

.. _id:

header3
~~~~~~~
```

- header3 will be of higher level with the ``.. _id:``
- header3 will be of wanted level without

header1 will become subtitle, unless I put an actual subtitle there.

**Comment by rpuntaie** [comment]
```
.. _id:
..
header3
~~~~~~~
```

is a workaround

**Comment by jgm** [comment]
That's weird.  Here's the output I get with `pandoc -f rst -s -t native` (it has nothing to do with the docx writer).
```
Pandoc (Meta {unMeta = fromList [("subtitle",MetaInlines [Str "Subtitle"]),("title",MetaInlines [Str "Title"])]})
[Header 1 ("header1",[],[]) [Str "header1"]
,Header 2 ("header2",[],[]) [Str "header2"]
,Div ("id",[],[])
 [Header 5 ("header3",[],[]) [Str "header3"]]]
```

**Comment by jgm** [comment]
Ah, I see.  `promoteHeaders` assumes the headers are at the top level; it doesn't recurse inside a Div.  Adding the id anchor causes a div to be produced here.  Since headers have id attributes, we shouldn't produce the Div in this case.
