### ISSUE TITLE
The Chinese character within math formula was filtered out After converted from docx to Markdown 

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#4243]
please download the `a.docx` file to try ,
https://drive.google.com/file/d/1L0zd1xlw9Vk8JL46feYqZ4x28sHhW8kF/view
( it is not an empty document )
After converted using 
`pandoc a.docx -t markdown --wrap=none -o a.md`

The Chinese character `或` within math formula was filtered out  with only the following left in  `a.md`
`$$A_{1} = \{ x \in \mathbb{Q}|x^{2} < 2\mathrm{}x < 0\}$$`
Anyone can help resolve the issue ?

**Comment by mb21** [comment]
What pandoc version?

Also, did you create the files with Word or Google Docs?

**Comment by jkr** [comment]
I can confirm the problem with the most recent pandoc. But I imagine it's a TeXMath problem, not a pandoc problem.

**Comment by jgm** [comment]
texmath can be checked directly, using the texmath
executable (build with the 'executable' flag set).

texmath -f omml -t tex

will convert your word omml to tex.

+++ Jesse Rosenthal [Jan 10 18 20:52 ]:

**Comment by jkr** [comment]
Submitted to texmath: https://github.com/jgm/texmath/issues/110

**Comment by redstoneleo** [comment]
@mb21 
```
C:\Users\i>pandoc -v
pandoc 2.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.5.1
Default user data directory: C:\Users\i\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

the files was created with Word 2016
