### ISSUE TITLE
ePubs warn on CSS selector specifies absolute position

### ISSUE THREAD

**Issue by jamtur01** [jgm/pandoc#4245]
I am building ePubs with Pandoc (2.1) and I note that:

https://github.com/jgm/skylighting/blob/master/src/Skylighting/Format/HTML.hs#L158
https://github.com/jgm/skylighting/blob/master/src/Skylighting/Format/HTML.hs#L161

Both result in `position: absolute` being set. When validating ePubs built with Pandoc I see:

```
WARNING(CSS-017): /Users/user/src/book/output/TheBook.epub/EPUB/text/ch010.xhtml(32,5): CSS selector specifies absolute position.
WARNING(CSS-017): /Users/user/src/book/output/TheBook.epub/EPUB/text/ch010.xhtml(35,5): CSS selector specifies absolute position.
```
In most readers this doesn't pose a problem but many import/process ePubs and choke on warnings - Google Play Books is an example here. I don't know what the solution is or if there is a solution or if it's worth fixing (and from reading #4128 it seems fairly complex). :)

**Comment by jamtur01** [comment]
Also - if you'd prefer this is Skylighting - I can close and re-open there.

**Comment by jgm** [comment]
Yes, it would be better to put this in skylighting, thanks!
You're right, it's complex to get this right.

+++ James Turnbull [Jan 11 18 03:58 ]:
