### ISSUE TITLE
\renewcommand does not work within "header-includes:" in YAML

### ISSUE THREAD

**Issue by gnpan** [jgm/pandoc#4246]
Pandoc v.2.1 or 2.0.6. The issue is not present in 2.0.5 and before. 
If a \renewcommand latex command is present in the "header-includes:" section of the YAML data, it is not interpreted. For example, using the fancyhdr package and a \renewcommand{\headrulewidth}{2pt} command does not alter the rule width, and the same for changing color, etc. Other header/footer instructions, not involving a \renewcommand, are OK. The same with a different package, titleps, and its \renewcommand\makefootrule... command. If the header info is in a separate tex file and called with -H header.tex, then it behaves OK.
pdf-engine=xelatex
macOS 10.13.2
Example: A txt file with the following contents will give a pdf with no line under the header and a red line  over the footer using pandoc v. 2.0.5, xelatex and the default latex template. With 2.0.6 or 2.1 the pdf file has the default black line under the header and no line over the footer:

```
---
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage[dvipsnames]{xcolor}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \newfontfamily\headerfont{Times New Roman}
  - \chead{\color{Gray}\fontsize{11}{12}\headerfont Header text}
  - \cfoot{\color{Gray}\fontsize{11}{12}\headerfont Footer text}
  - \renewcommand\headrulewidth{0pt}
  - \renewcommand\footrule{\color{Red}\hrule height 0.5pt}
---

Test
```

**Comment by jgm** [comment]
Try with

    -f markdown-latex_macros

+++ gnpan [Jan 10 18 22:24 ]:

**Comment by gnpan** [comment]
Thanks, it works with -f markdown-latex_macros.

**Comment by jgm** [comment]
Explanation:  with +latex_macros (the default), the markdown
reader will expand latex macros itself.  This is needed for
better handling of math in non-latex output formats.  In
this case the macro definitions are not passed through.

When latex/pdf is your output format, you can safely leave
the macros unexpanded and keep the definitions.  That's
what -latex_macros does.

Now, what I don't yet understand is why the macro-expansion
didn't work in your case.  Perhaps you could provide a
minimal example for us to test with, showing the failure?

+++ gnpan [Jan 11 18 10:04 ]:

**Comment by jgm** [comment]
I see.  `\renewcommand{\headrulewidth}{2pt} ` affects the `\headrulewidth` command, but this doesn't actually appear directly in your document; it's used indirectly by `fancyhdrs` when it formats a page.  For this kind of case we want the macro definitions to be passed through.

This makes me think we should change back to the old behavior of passing through the macros even when we expand them.

**Comment by jgm** [comment]
Or maybe a better alternative would be to automatically disable the `latex_macros` extension on the reader if the writer is latex?  It's hard to see how this would cause any problems, though it goes against the usual separation of readers and writers.

**Comment by gnpan** [comment]
Not sure what's best. In any case, I don't like long Yaml headers in my text files, so I will probably stick with the -H header.tex solution with a separate file for the header. 
PS I have added an example that reproduces the issue in my original post.

**Comment by dataopt** [comment]
I don't think it is a good idea to go against the separation of readers and writers unless there is no other solution.

**Comment by jgm** [comment]
+++ Kevin Cheung [Jan 12 18 11:37 ]:
>   I don't think it is a good idea to go against the separation of readers
>   and writers unless there is no other solution.

Well, the other solutions are

(a) keep the status quo, which leads to breakage in cases
like this, where the macro is used in an included package
and not directly in the document, at least with the
default `-f markdown`

(b) pass the macro definitions through AND resolve macros.
This may also have bad effects in certain cases, though
I haven't got a specific example yet.

**Comment by dataopt** [comment]
It seems that no default behaviour will address all use cases.  Could new options be added for specifying various ways of expanding macros?  Or is this simply not possible?
