### ISSUE TITLE
Aspectratio not kept when only height or width of graphic are set

### ISSUE THREAD

**Issue by pajowu** [jgm/pandoc#4247]
If only width or height are set in a included graphic, the other one will be set to full `\textwidth`/`\textheight` in LaTeX output. This behaviour was introduced in 1193c1a505aac616d41a7b1c61c0cde07d2560d2. When doing this, `keepaspectratio` should also be set (as we did until b2a190546d9f8bbc853b5e65539093275252e0ef). If not, the output will distort the image

### Input
```
![Description](filename){width=100%}
```
### Command line
```
pandoc -o example.tex example.md
```
### Actual Output
```
\begin{figure}
\centering
\includegraphics[width=1\textwidth,height=\textheight]{filename}
\caption{Description}
\end{figure}
```

### Expected Output
```
…
\includegraphics[width=1\textwidth,height=\textheight,keepaspectratio]{filename}
…
```

## Version
```
pandoc 2.0.6
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.5.0.1
```

This also happens is the current master (c5ba3b8ee32704f1fdf241480ba64950f8ceedd8)

**Comment by jgm** [comment]
The default template has keepaspectratio as a default.
Are you using a custom template, perhaps?

+++ pajowu [Jan 11 18 08:14 ]:

**Comment by pajowu** [comment]
Thank you
