### ISSUE TITLE
an header in a bullet point followed by a quoted paragraph leads to a syntax error in RST

### ISSUE THREAD

**Issue by danse** [jgm/pandoc#4248]
given the following native document:

```
[BulletList
 [[Header 2 ("bullet",[],[]) [Str "bullet",Space]]]
,BlockQuote [Para [Str "quoted"]]]
```

when converted via Pandoc the result is:

```
-  .. rubric:: bullet
      :name: bullet

    quoted
```

which raises a syntax error when passed for example through `rst2html`, because `quoted` is interpreted as the content of the `rubric` directive wich does not allow content.

note that `quoted` starts aligned with the second dot in the directive block. it's anyway considered _indented_ by `rst2html`.

the [documentation](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#directives) states that:

> Simple directives may not require any content. If a directive that does not employ a content block is followed by indented text anyway, it is an error. If a block quote should immediately follow a directive, use an empty comment in-between (see Comments below).

so something like the following seems to be the right way to write the document:

```
-  .. rubric:: bullet
      :name: bullet
   ..

    quoted
```

Pandoc version 2.1

i am working at a pull request where the empty comment is always added to close a rubric

**Comment by jgm** [comment]
Here's a simpler version of the problem (which has nothing to do with rubrics):
```
- a

> quoted
```
The problem is that we need something to close a list when it occurs before an indented blockquote.

**Comment by jgm** [comment]
So, what we need is to put an empty comment between any list and a following BlockQuote.

**Comment by danse** [comment]
aha, i've been misled by the indentation in the native file. thanks for the better explanation, i'm going to turn this into a test case and dive in the code

**Comment by danse** [comment]
i see that the writer doesn't currently analyse the sequence of blocks, while [it processes the blocks independently from each other](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/RST.hs#L358), which makes sense except in this case.

as far as i understand we have a tradeoff between code complexity and time performance versus readability and space performance. we can either:

- keep processing by block and just close every list. that would produce uglier and bigger documents
- check for the required sequence to appear and render with the comment. that would require more processing time and add complexity to the code

i'd opt for the first option mainly in order to keep the code simple. in my opinion the value added is not worth the complexity here. there is also the possibility that always terminating lists will prevent other syntax errors. maybe someone has ideas about how similar problems were fixed elsewhere, and can suggest a simple and performant way to check for sequences of blocks

**Comment by danse** [comment]
here is a branch with the simplest solution https://github.com/jgm/pandoc/compare/master...italia:4248, which already fixes a problem for us. tests in `Old.hs` fail and before updating the file i'd like to know your opinion about the approach

**Comment by jgm** [comment]
See blockListToMarkdown in the Markdown writer, where we do
something similar, inserting an HTML comment between a list
and indented code.  There's a function that turns lists of
blocks into a Doc, and we simply put this check there.
I don't want to close every list.  That's ugly and
unidiomatic output.  The performance impact of modifying
blockListToMarkdown in this way is minimal.

+++ Francesco Occhipinti [Jan 12 18 02:40 ]:

**Comment by danse** [comment]
wow that case is really similar. there is probably a way to abstract out of `fixBlocks` but it's above my skills. i'll write a similar `fixBlocks` within `blockListToRST'`

**Comment by danse** [comment]
`isListBlock` could be reused but not sure it's worth it

**Comment by danse** [comment]
i admit i force pushed a couple of times to remove a comment :sweat_smile:

**Comment by danse** [comment]
should i start the commit message with an upper case?
