### ISSUE TITLE
Cannot convert math with `\over` command

### ISSUE THREAD

**Issue by abnerlee** [jgm/pandoc#4251]
input: demo.md
```
$$x+1\over\sqrt{1-x^2}$$
```

command:

```
pandoc -f markdown demo.md      
```

error:

```
[WARNING] Could not convert TeX math 'x+1\over\sqrt{1-x^2}', rendering as TeX:
  x+1\over\sqrt{1-x^2}
          ^
  unexpected "\\"
  expecting "%", "\\label", "\\nonumber" or whitespace
<p><br /><span class="math display">$$x+1\over\sqrt{1-x^2}$$</span><br /></p>
```

The error also happens if I try to convert demo.md into docx. The tex equation are not converted.

Pandoc version info is 
```
pandoc 2.0.1.1
Compiled with pandoc-types 1.17.2, texmath 0.10, skylighting 0.4.3.2
Default user data directory: /Users/abner/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by hmenke** [comment]
It is not recommended to use `\over` because the semantics are a little freaky.  Consider
```latex
\documentclass{article}
\begin{document}
$\displaystyle \int f(x) dx \over \sum_i f(x_i)$
\end{document}
```
You'd expect both the numerator and the denominator to be in display style, but this is the ouput
![test](https://user-images.githubusercontent.com/1903556/34901181-dcafe950-f86b-11e7-9216-450cf199e790.png)

**Comment by mb21** [comment]
> The texmath library doesn't yet implement `\over`.  If you want to request support for it, put up an issue at jgm/texmath.

Thus closing this.

**Comment by sjackman** [comment]
```
[WARNING] Could not convert TeX math '\textrm{PPV} = \frac{55}{210} = 0.26', rendering as TeX
```
What should I use instead of `\frac{…}{…}` inside `$ math goes here $`?

**Comment by xu-song** [comment]
Is it possible to use `\[` instead of `$$`?

Here is a [demo](http://pandoc.org/try/?text=%23+good%0A%24%24x%2B1%5Cover%5Csqrt%7B1-x%5E2%7D%24%24%0A%0A%23+bad%0A%5C%5Bx%2B1%5Cover%5Csqrt%7B1-x%5E2%7D%5C%5D%0A%5C(x%2B1%5Cover%5Csqrt%7B1-x%5E2%7D%5C)&from=markdown&to=)

**Comment by xu-song** [comment]
thanks, it works
