### ISSUE TITLE
linebreak in math not possible (converting from rst to latex/pdf)

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#4254]
pandoc 2.1

The reason seems to be that pandoc issues ``\[\]`` instead of an environment:
https://tex.stackexchange.com/questions/46189/how-do-i-add-a-line-break-in-display-math-mode

**Comment by jgm** [comment]
This would be more helpful if you gave the RST sample you're converting from.

**Comment by rpuntaie** [comment]
```
Sample

.. math:: 

   &\mathrm{samp\_inter\_pulse}  =
   \frac{10*\mathrm{FCY}}{\mathrm{PR3\_VALUE\_US}*\mathrm{config.frequency}} - \\
   &\mathrm{samp\_in\_phase1} - \mathrm{samp\_in\_interphase} - \mathrm{samp\_in\_phase2} - \mathrm{samp\_in\_afterpulse}

```

**Comment by jgm** [comment]
Looks like rst2latex.py puts math in an `align*` environment.

We could simulate this by having the RST reader add `\begin{aligned}...\end{aligned}` around math if it contains `\\`.
