### ISSUE TITLE
Ending support for GHC 7.8

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#4255]
What is our timeline for ending support for GHC 7.8? Debian stable is now on 8.0, and oldstable backports are at 7.10. It would be nice to have applicative-monad throughout (I just had to define a `concatMapM` again, because 7.8 needs Functor for `concat <$> mapM`). Is there some distro or niche compiling need we're still considering here?

**Comment by jgm** [comment]
I'm not aware of any pressing need to support 7.8 (though it typically uses less memory than later versions and might be able to compile pandoc on resource-limited systems where other ghcs won't work).  On the other hand, we should also consider the option of using `base-compat` (this might also let us get rid of our custom prelude).  From their readme:
```
{-# LANGUAGE NoImplicitPrelude #-}
import Prelude.Compat

main :: IO ()
main = mapM_ print (Just 23)
```

**Comment by jkr** [comment]
If anyone is actively using it, I suppose there's no rush to drop it. Writing a few one-line compat functions certainly is no big deal.. And it looks like base-compat adds AMP to 7.8, so that would be interesting to investigate.

**Comment by jgm** [comment]
I wonder if we could replace our custom prelude with one that simply reexports the prelude from base-compat?  That would cover all the bases and we wouldn't need to change any other code.

**Comment by jgm** [comment]
All right, I've removed ghc 7.8 support.  Life's too short.
