### ISSUE TITLE
Speaker notes not converting w. reveal.js

### ISSUE THREAD

**Issue by mberasategi** [jgm/pandoc#4257]
Hi,

I'm using pandoc 1.19.2.1 and speaker notes are not being converted at all when I use the [Markdown syntax specified in the documentation](http://pandoc.org/MANUAL.html#speaker-notes). They do display and work correctly when using the html (`<aside class="notes">`). What could be going wrong?

Thanks,

Miren

**Comment by mb21** [comment]
That syntax was introduced in pandoc 2.0, please upgrade...

**Comment by mberasategi** [comment]
Solved, thanks! 

For the record, I had installed pandoc through the Ubuntu repositories and realised now that they are old. After apt remove and installing the .deb file, `pandoc -v` keeps saying 1.19.2.1 (?). But notes are now properly converted, so I guess that's not the actual version that's running... odd.

**Comment by mb21** [comment]
Try `which pandoc` to see which binary is being called...
