### ISSUE TITLE
Pandoc OSX installer installs 64-bit executables on a 32-bit machine.

### ISSUE THREAD

**Issue by ntolva** [jgm/pandoc#426]
Download pandoc-1.9.1.1.dmg.  Run it.  Open Terminal.  Run pandoc.  Error follows:

-bash: /usr/local/bin/pandoc: Bad CPU type in executable

run file on executable:
$ file /usr/local/bin/pandoc
/usr/local/bin/pandoc: Mach-O 64-bit executable x86_64

The output should be more like, for example with python2.7:
$ file /usr/local/bin/python2.7
/usr/local/bin/python2.7: Mach-O universal binary with 2 architectures
/usr/local/bin/python2.7 (for architecture i386):   Mach-O executable i386
/usr/local/bin/python2.7 (for architecture x86_64): Mach-O 64-bit executable x86_64

**Comment by barracuda156** [comment]
> I'm not sure how to go about producing a universal binary
> with ghc...

A standard solution is to build whatever archs needed separately and then use `lipo` to glue slices together.
