### ISSUE TITLE
markdown table is not "stable" by pandoc

### ISSUE THREAD

**Issue by louisabraham** [jgm/pandoc#4265]
This table is not preserved by the command `pandoc -f markdown --standalone -t markdown`

```
  -------------
  col1   col2
  ------ ------
  1      2
  -------------
```

After a few iterations we obtain

```
  -------------------------------
  col1            col2
  --------------- ---------------
  1               2
  -------------------------------
```

I use pandoc version 2.1.

**Comment by mb21** [comment]
The multiline table is converted to native AST with columns of width=0.097222...

Depending on your usecase you might be better off using simple tables?

**Comment by louisabraham** [comment]
What do you call simple tables? Isn't it the default output of pandoc for tables?

**Comment by mb21** [comment]
> What do you call simple tables?

http://pandoc.org/MANUAL.html#extension-simple_tables

> Isn't it the default output of pandoc for tables?
yes, unless your table has widths, then the writer cannot use simple table output. So what I was suggesting is to use simple tables as input (basically remove the first and last horizontal line).
