### ISSUE TITLE
my hyper link disappeared after converted for docx to Markdown  

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#4266]
The first hyper link disappeared after converted for docx to Markdown  using 
`pandoc c.docx -t markdown --wrap=none -o c.md
`
![](https://i.imgur.com/mIrABke.png)
Test file here
https://drive.google.com/open?id=1HcQrbuocvnu8hgHobW08eNilgxTYTcYZ

**Comment by jkr** [comment]
Confirmed. The problem here is that the first hyperlink is set by a `<w:instText>` command instead of the normal hyperlink elements. I'm not sure why Word does this, or how to parse it dependably, but I'll work on it.

**Comment by jkr** [comment]
Closed with 95d602d3b7df8946f236aaad310bedf8fdc2e09f
