### ISSUE TITLE
Don't wrap lines to the column width specified by --columns (default 72) in source code

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#4267]
It is [this problem](https://groups.google.com/forum/#!topic/pandoc-discuss/NKQDYGO1jAY) caused me to post the suggestion here.
By default, pandoc will attempt to wrap lines to the column width specified by --columns (default 72) in source code, however , there are Markdown render engines(like https://dillinger.io) which treat the line wrap a new line, which is not what we want.
The current solution is `--wrap=none`, however , I hope the it could be the default option. 

> --wrap=auto|none|preserve
> Determine how text is wrapped in the output (the source code, not the rendered version). With auto (the default), pandoc will attempt to wrap lines to the column width specified by --columns (default 72). With none, pandoc will not wrap lines at all.

**Comment by mb21** [comment]
Everyone has their preference... not everyone's preference can be the default.

**Comment by redstoneleo** [comment]
@mb21  It is the feature which lead some Markdown engines to cause a layout problem ,  I post the suggestion in order to get rid of the problem .

**Comment by jgm** [comment]
If you are targeting one of those engines, then you should use `-t markdown+hard_line_breaks`.

I'm not going to change the default for pandoc, which respects the Markdown philosophy that the original source should be as readable as possible in its original form.
