### ISSUE TITLE
 suggest ignoring "——" convert

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#4268]
Two Em dashes（U+2014）"——"  are used as the Chinese style Em dash, when convert docx including "——"  to Markdown , "——" was converted to "------" in Markdown , however , Markdown engines doesn't render  "------"  back to "——" , so I suggest ignoring "——" convertion .

**Comment by mb21** [comment]
try `-f markdown-smart`

See http://pandoc.org/MANUAL.html#extension-smart

**Comment by redstoneleo** [comment]
The input format is docx , not included in `smart `extension input formats
> input formats
> markdown, commonmark, latex, mediawiki, org, rst, twiki

**Comment by mb21** [comment]
In that case `-t markdown-smart`

**Comment by redstoneleo** [comment]
Great ! Another similar question : Why not make `markdown-smart` be the default behavior so as to avoid the problem ?

**Comment by mb21** [comment]
Good. Feel free to ask question like this or start discussions about defaults on pandoc-discuss, this is the issue tracker...
