### ISSUE TITLE
Docx Reader with Track Changes does not convert comments than span multiple lines properly

### ISSUE THREAD

**Issue by mbroedl** [jgm/pandoc#4270]
I just tested the Docx reader functionality in pandoc2, and found some unexpected behaviour when comments are spanning multiple lines or comments are longer than a line.

_pandoc 2.0.6_
_Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.5.0.1_

`$ pandoc -s test.docx --wrap=none --track-changes=all --atx-headers -t markdown -o test.md`
screenshot of test.docx: https://www.imageupload.co.uk/image/E1YS

_Case 0:_
single line with a comment that has a single line
`Test 3: [test 3]{.comment-start id="1" author="m" date="2018-01-16T12:34:14Z"}Comment[]{.comment-end id="1"}`
--> works as expected

_Case 1:_
single line with a comment, that has multiple lines
`Test 5: [line 1 ¶ line 2 ¶ line 3]{.comment-start id="2" author="m" date="2018-01-16T12:50:51Z"}multiline comment[]{.insertion author="m" date="2018-01-16T12:50:33Z"}`
--> ends on insertion instead of an comment-end

_Case 2:_
multiple lines with a comment that has multiple lines
`Test 7: []{.comment-end id="3"}multiline`
` `
`comment[]{.insertion author="m" date="2018-01-16T12:35:00Z"}`
--> ends on insertion and does not include any comment text (it seems as if numbers comment ids 4 and 5 are still given to some other lines spanned the comment)

_Case 3:_
multiple lines with a comment that has one line
`Test 8: []{.comment-end id="6"}multiline`
` `
`comment[]{.insertion author="m" date="2018-01-16T12:53:13Z"}`
--> ends on insertion and does not include any comment text

**Comment by mb21** [comment]
Can you upload the `test.docx` with minimal text that reproduces the problem?

**Comment by mbroedl** [comment]
Didn't realise that was possible, sorry!
[test.docx](https://github.com/jgm/pandoc/files/1635390/test.docx)

**Comment by mbroedl** [comment]
Found another two anomalies relating to empty comments/texts:

_Case 4:_
selected text empty, comment written:
`Test 9: empty[]{.insertion author="m" date="2018-01-16T14:19:47Z"} text`
--> as insertion without any text

_Case 5:_
text selected, comment text empty
`Test 10: [[]{.comment-start id="10" author="Malte Rödl" date="2018-01-16T14:19:57Z"}]{#__DdeLink__92_2858857069 .anchor}empty comment[]{.insertion author="m" date="2018-01-16T14:19:57Z"}`
--> same problem with the comment-end, not sure what happened in between

[updated test.docx](https://github.com/jgm/pandoc/files/1635448/test.docx)

**Comment by jkr** [comment]
What version of word did you make this on? Word 2013 is unable to open it on my computer, complaining that "One or more comments referenced in the document are missing or corrupt." Perhaps the issues are related?

**Comment by mbroedl** [comment]
I actually used LibreOffice 5.3.7.2.0... :-O

**Comment by jkr** [comment]
Sounds like you found a LibreOffice export bug. Needless to say, if real MS Word can't read it, we can't promise to read it either. But let me know if the issue arises in a document created by word.

**Comment by mbroedl** [comment]
Interesting. I could swear I have used comments spanning multiple lines in LibreOffice before, and they were not an issue. Occurs as well when in Libre Office I "save as copy" from a functioning MS Office file. Need to file another bug report there then. Should've checked, really.

Here updates of the files.
[test.docx](https://github.com/jgm/pandoc/files/1635956/test.docx)
[test.md](https://github.com/jgm/pandoc/files/1635960/test.md.txt)

1-8 work, 9 is impossible with word 2010 but works fine when recreated via md->docx->md.

Test 10 with an empty comment still causes problems though:
`Test 10: [[]{.comment-start id="17" author="m" date="2018-01-16T16:27:00Z"}]{#__DdeLink__92_2858857069 .anchor}empty[]{.comment-end id="17"} comment`

And then, I don't know if it's intended, when converting comments from docx to md linebreaks in comments become paragraph signs ` ¶ `, which are then taken up by word as the character, lone as a linebreak, and the linebreak gets lots.

Thanks for the great work though, I love the comment features!

**Comment by jkr** [comment]
With pandoc 2.1, I get

~~~
Test 10: []{.comment-start id="17" author="Malte Roedl"
date="2018-01-16T16:27:00Z"}empty[]{.comment-end id="17"} comment
~~~

That's correct, right? Your output looks like the result of a couple of issues I fixed in 2.1 (e90c714c and 836153de). Try upgrading to the latest pandoc -- it should work.

The ¶ signs are there because the line breaks are actually paragraph breaks (returns). Since we can't put blocks inside a span, we collapse them to inlines, and use ¶s to mark breaks between paragraphs.

**Comment by mbroedl** [comment]
Ah, thanks a lot, @jkr then all my issues are solved. :)

Might be nice to put the paragraph breaks back with the Docx writer? That might save a bit of explanation when working with other people.
Nonetheless, next time I make sure I test with the most recent version and an actual MS Office. 😆

**Comment by jkr** [comment]
Problem is, there would be no way to know if it's a real paragraph break or a comment with a ¶ in it ("this sentence should go in the next ¶."). Because of the structure of pandoc's AST, we lose information when we go from comments that could contain multiple blocks to spans.

It would be pretty easy to use a lua filter to put linebreaks in, though, so the output almost looks the same. Here is one that should work for 2.1.1.

~~~lua
reliner = {
   Str = function (s)
      if s.text == "¶" then
	 return pandoc.LineBreak()
      end
   end
}

function Span (elt)
   local classes = elt.classes or elt.attr.classes
   if classes:includes("comment-start") then
      return pandoc.walk_inline(elt, reliner)
   end
end
~~~

**Comment by mbroedl** [comment]
Ah, thanks, the lua filter should work well!
It's unlikely I'll ever use a paragraph sign, so for me this would be fine.

**Comment by tolot27** [comment]
What is more frequent? A multi-paragraph comment with real paragraph breaks or a comment with a ¶? I believe the former one and I would love to see that the introduced ¶ (hence all ¶s) get converted back to a line break per default.

**Comment by tolot27** [comment]
@jkr The multi-paragraph comment in your test file [comments.docx](https://github.com/jgm/pandoc/blob/master/test/docx/comments.docx) has two line breaks but only one " ¶ " (sourrounded by a space on each site) is extracted (`comments.native: Space,Str "\182",Space`). Shall I open a separate issue for that?

**Comment by jkr** [comment]
Sure -- though I remember it being only two paragraphs, so I'm not sure if it should have two line breaks. But I'm on my phone, so I might well be remembering wrong.Make sure to include what the expected output should be.The work for this, by the way, is mainly in `blocksToInlines` in Text.Pandoc.Shared. if there's a big it's probably there.On Jan 26, 2018 6:37 AM, Mathias Walter <notifications@github.com> wrote:@jkr The multi-paragraph comment in your test file comments.docx has two line breaks but only one " ¶ " (sourrounded by a space on each site) is extracted (comments.native: Space,Str "\182",Space). Shall I open a separate issue for that?

**Comment by tolot27** [comment]
There are three paragraphs, one is just empty:
![image](https://user-images.githubusercontent.com/1370732/35444227-1ebc6f3e-02ae-11e8-9021-c505a5727a7d.png)

There are three `w:p` here as well:
```XML
  <w:comment w:id="3" w:author="Jesse Rosenthal" w:date="2016-05-09T16:14:00Z" w:initials="jkr">
    <w:p w14:paraId="207C7565" w14:textId="77777777" w:rsidR="0008235A" w:rsidRDefault="0008235A">
      <w:pPr>
        <w:pStyle w:val="Kommentartext"/>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:rStyle w:val="Kommentarzeichen"/>
        </w:rPr>
        <w:annotationRef/>
      </w:r>
      <w:r>
        <w:t>This one has multiple paragraphs.</w:t>
      </w:r>
    </w:p>
    <w:p w14:paraId="61B066AD" w14:textId="77777777" w:rsidR="0008235A" w:rsidRDefault="0008235A">
      <w:pPr>
        <w:pStyle w:val="Kommentartext"/>
      </w:pPr>
    </w:p>
    <w:p w14:paraId="475FE386" w14:textId="77777777" w:rsidR="0008235A" w:rsidRDefault="0008235A">
      <w:pPr>
        <w:pStyle w:val="Kommentartext"/>
      </w:pPr>
      <w:r>
        <w:t>See?</w:t>
      </w:r>
    </w:p>
  </w:comment>
```
I thought it is related to #2252 but it isn't.

**Comment by jkr** [comment]
from the manual:

~~~md
#### Extension: `empty_paragraphs` ####

Allows empty paragraphs.  By default empty paragraphs are
omitted.

This extension can be enabled/disabled for the following formats:

input formats
:  `docx`, `html`

output formats
:  `markdown`, `docx`, `odt`, `opendocument`, `html`
~~~

~~~
$ pandoc ~/devel/pandoc/test/docx/comments.docx --track-changes=all -t markdown 
I want [I left a comment.]{.comment-start id="0"
author="Jesse Rosenthal" date="2016-05-09T16:13:00Z"}some text to have a
comment []{.comment-end id="0"}on it.

This is [A comment across paragraphs.]{.comment-start id="1"
author="Jesse Rosenthal" date="2016-05-09T16:13:00Z"}a new paragraph.

And so[]{.comment-end id="1"} is this.

One [This one has multiple paragraphs. ¶ See?]{.comment-start id="2"
author="Jesse Rosenthal" date="2016-05-09T16:14:00Z"}more[]{.comment-end
id="2"}. And this is one with a [Do something.]{.comment-start id="3"
author="Jesse Rosenthal" date="2016-06-22T14:35:00Z"}[Do something
else.]{.comment-start id="4" author="Jesse Rosenthal"
date="2016-06-22T14:36:00Z"}comment in a comment[[]{.comment-end
id="4"}]{.comment-end id="3"}.

$ pandoc ~/devel/pandoc/test/docx/comments.docx -f docx+empty_paragraphs --track-changes=all -t markdown
I want [I left a comment.]{.comment-start id="0"
author="Jesse Rosenthal" date="2016-05-09T16:13:00Z"}some text to have a
comment []{.comment-end id="0"}on it.

This is [A comment across paragraphs.]{.comment-start id="1"
author="Jesse Rosenthal" date="2016-05-09T16:13:00Z"}a new paragraph.

And so[]{.comment-end id="1"} is this.

One [This one has multiple paragraphs. ¶ ¶ See?]{.comment-start id="2"
author="Jesse Rosenthal" date="2016-05-09T16:14:00Z"}more[]{.comment-end
id="2"}. And this is one with a [Do something.]{.comment-start id="3"
author="Jesse Rosenthal" date="2016-06-22T14:35:00Z"}[Do something
else.]{.comment-start id="4" author="Jesse Rosenthal"
date="2016-06-22T14:36:00Z"}comment in a comment[[]{.comment-end
id="4"}]{.comment-end id="3"}.
~~~

**Comment by tolot27** [comment]
You are right. I tried `-empty-paragraphs` which was the oposite.

Just one more question. Why are the extra spaces inserted?
