### ISSUE TITLE
kindly put pandoc "in backports repository for debian stable" 

### ISSUE THREAD

**Issue by zaxebo1** [jgm/pandoc#4276]
see https://packages.debian.org/search?keywords=pandoc

debian linux 8 stretch (current stable ) has doconce version 1.12.4.2
debian linux 9 stretch (current stable )  has doconce version 1.17.2
debian linux testing (buster 10 ) has doconce version 1.19.2.4

whereas https://github.com/jgm/pandoc/releases shows doconce project itself has released 2.1 latest version .deb available (but this .deb is outside the debian's official repository, which makes it difficult to push the latest version usage in organiation's development team)

--

SUGGESTION:
May i suggest that in debian stable repository, as the pandoc package will always get version behind debian testing, Hence *can you kindly make the later pandoc versions available for debian stable IN OFFICIAL DEBIAN STABLE "BACKPORTS" repository**
see
  - *https://wiki.debian.org/Backports*
 - *https://backports.debian.org/FAQ/*
 - *https://packages.debian.org/stretch-backports/*
 - *https://backports.debian.org/changes/stretch-backports.html*
"for example": java-jdk, telegram-desktop, Virtualbox etc are available in stretch-backports repository

This backports repository strategy will keep debian stable pandoc version mostly as much latest as version available in debian testing
Thanks in advance

**Comment by jgm** [comment]
This isn't up to us; you'd have to ask the debian developers who maintain the package.
