### ISSUE TITLE
fix Odt format writer for some math formulas 

### ISSUE THREAD

**Issue by zaxebo1** [jgm/pandoc#4277]
When we convert the following sample markdown code to pdf, odt, docx ; 

--

My Equation1:

$$\lim_{x \to \infty} \exp(-x) = 0$$

My Equation2:

$e^x = \sum_{n=0}^\infty \frac{x^n}{n!} = \lim_{n\rightarrow\infty} (1+x/n)^n$

--

THEN following thing occurs:
  'Pdf and Docx writers' output Equation1 and equation2 correctly, *but Odt outputs Equation1 incorrectly* . *So please fix Odt output for equation 1 and 2*

**Comment by mb21** [comment]
What version of pandoc? What exactly do you mean with "incorrectly"?

**Comment by zaxebo1** [comment]
> What version of pandoc? 

pandoc 2.1 on debian stable 9

**Comment by zaxebo1** [comment]
Equation 1 output in docx and PDF format: CORRECT
![Equation 1 output in docx and PDF format: CORRECT](https://user-images.githubusercontent.com/4308927/35089449-faad3f12-fc5c-11e7-8820-433f7e6afe5c.png)

Equation 1 output in odt format :WRONG
![Equation 1 output in odt format :WRONG ](https://user-images.githubusercontent.com/4308927/35089416-e2f6feda-fc5c-11e7-93fd-832436bc7214.png)


Equation 2 output in docx and PDF format: CORRECT
![Equation 2 output in docx and PDF format: CORRECT](https://user-images.githubusercontent.com/4308927/35089627-7acf8100-fc5d-11e7-8804-1304266a0a93.png)


Equation 2 output in odt format :WRONG
![Equation 2 output in odt format :WRONG](https://user-images.githubusercontent.com/4308927/35089491-181a9db0-fc5d-11e7-91af-9dc319705686.png)

**Comment by mb21** [comment]
So basically the limes is missing...

**Comment by zaxebo1** [comment]
in equation 1:  
   "l" should be changed to "lim"

in equation2 : 
       "l" should be changed to "lim"
    AND  "n!"  should come inside the "Sigma" sign

**Comment by jgm** [comment]
ODT uses MathML for the math.  LibreOffice often doesn't do a very good job rendering the MathML, in my experience, so the first thing we need to determine is whether the problem is (a) in the MathML pandoc generates, or (b) in LibreOffice's rendering of this math.  Here's the mathml produced for your equations by texmath (the library pandoc uses).  I think the problem is in (b) the rendering, but you can look yourself.

`\lim_{x \to \infty} \exp(-x) = 0`
``` xml
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <munder>
      <mo>lim</mo>
      <mrow>
        <mi>x</mi>
        <mo>→</mo>
        <mi>∞</mi>
      </mrow>
    </munder>
    <mo>exp</mo>
    <mo stretchy="false" form="prefix">(</mo>
    <mo>−</mo>
    <mi>x</mi>
    <mo stretchy="false" form="postfix">)</mo>
    <mo>=</mo>
    <mn>0</mn>
  </mrow>
</math>
```

`e^x = \sum_{n=0}^\infty \frac{x^n}{n!} = \lim_{n\rightarrow\infty} (1+x/n)^n`

```xml
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <msup>
      <mi>e</mi>
      <mi>x</mi>
    </msup>
    <mo>=</mo>
    <munderover>
      <mo>∑</mo>
      <mrow>
        <mi>n</mi>
        <mo>=</mo>
        <mn>0</mn>
      </mrow>
      <mo accent="false">∞</mo>
    </munderover>
    <mfrac>
      <msup>
        <mi>x</mi>
        <mi>n</mi>
      </msup>
      <mrow>
        <mi>n</mi>
        <mi>!</mi>
      </mrow>
    </mfrac>
    <mo>=</mo>
    <munder>
      <mo>lim</mo>
      <mrow>
        <mi>n</mi>
        <mo>→</mo>
        <mi>∞</mi>
      </mrow>
    </munder>
    <mo stretchy="false" form="prefix">(</mo>
    <mn>1</mn>
    <mo>+</mo>
    <mi>x</mi>
    <mi>/</mi>
    <mi>n</mi>
    <msup>
      <mo stretchy="false" form="postfix">)</mo>
      <mi>n</mi>
    </msup>
  </mrow>
</math>
```

**Comment by jgm** [comment]
PS. You might look inside the odt container (it's just a zip file so you can unzip it with 'unzip').
There should be an xml file for each formula.

**Comment by labdsf** [comment]
You can always compile to HTML5 with --mathml flag. Firefox displays math correctly, so the problem is in LibreOffice.
