### ISSUE TITLE
rst header with trailing space after name not recognized

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#4280]
Pandoc 2.1.1

In this example

```
=====================
Software Requirements
=====================

------
Device
------

Requirements - Functionality
============================

Installer
---------

Driver 
------

About driver

```

converted to docx with

```
pandoc -f rst -t docx tmp.rest -o "tmp.docx"
```

I get 

```
Driver ------
```

but not a 

**Driver**

with header formating.

This is a rst reader problem because towards HTML 

```
pandoc -f rst tmp.rest
```

I get the same:

```
<h1 id="software-requirements">Software Requirements</h1>
<h2 id="device">Device</h2>
<h3 id="requirements---functionality">Requirements - Functionality</h3>
<h4 id="installer">Installer</h4>
<p>Driver ------</p>
<p>About driver</p>
```

**Comment by jkr** [comment]
I can't reproduce (with pandoc 2.1.1 or 2.0.6)

~~~
$ cat tmp.rest      
=====================
Software Requirements
=====================

------
Device
------

Requirements - Functionality
============================

Installer
---------

Driver
------

About driver
$ pandoc -f rst tmp.rest
<h1 id="software-requirements">Software Requirements</h1>
<h2 id="device">Device</h2>
<h3 id="requirements---functionality">Requirements - Functionality</h3>
<h4 id="installer">Installer</h4>
<h4 id="driver">Driver</h4>
<p>About driver</p>
~~~

Maybe it has something to do with your line endings? What OS are you using?

**Comment by jkr** [comment]
Oh, I see -- it has to do with an extra space at the end of "Driver", i.e.
`Driver \n------` instead of `Driver\n------`.

MWE:
~~~
$ echo 'Foo \n==='|pandoc -f rst
<p>Foo ===</p>
~~~

@jgm -- this is a bug, right? `rst2html.py` does it correctly.

**Comment by rpuntaie** [comment]
Yes, rst2html.py produces the title, even if there is a space after `Driver`.

**Comment by jgm** [comment]
Proper test case is
```
echo -e 'Foo \n==='|pandoc -f rst
```
and actually I DO get a header with this for pandoc 1.19.2.1, but not for 2.x.
So, apparently it's a regression?  I tracked it down to f4bff5d3 where for some reason I replaced a `blankline` with `newline`.

Will fix immediately.
