### ISSUE TITLE
why markdown file with ANSI encoding format not converted to html file ? how jekyll detects the encoding for this ?

### ISSUE THREAD

**Issue by SyncTimesheets** [jgm/pandoc#4288]
I have markdown file which is encoded in ANSI and it is not converted to html file using a jekyll project but a while with a utf-8 without BOM encoding gets converted to html file . how to find the encoding of a file using program , already tried the method in https://social.msdn.microsoft.com/Forums/vstudio/en-US/b172cd4d-25fe-4696-8c0f-37226c053d71/how-to-detect-encoding-file-in-ansi-utf8-and-utf8-without-bom?forum=csharpgeneral , the ude.dll is not helping .

i get different result from notepad++ than the program. why is it so ? how to get the encoding of a file effectively ?

**Comment by mb21** [comment]
Please ask questions like this on pandoc-discuss.

btw. ASCII is a subset of UTF-8 so there shouldn't be a difference. See also http://pandoc.org/MANUAL.html#character-encoding

**Comment by SyncTimesheets** [comment]
HI ,

thanks for the information , but my file with ansi encoding does not change to html file using a jekyll project whereas a file with utf-8 without bom encoding gets converted to html . hence i need to detect the encoding efficiently before moving the md files to my project .
