### ISSUE TITLE
org to latex-pdf footnotes

### ISSUE THREAD

**Issue by mclearc** [jgm/pandoc#4290]
Using pandoc 2.1.1 on  Mac OS High Sierra 

I think the org-reader/latex-writer is exhibiting a problem similar to that which the markdown reader/latex-writer exhibited in issue [#4062](https://github.com/jgm/pandoc/issues/4062). Using latex footnotes like `\footnote[][-1in]{witty footnote}` in the org source results in the square brackets being ignored in latex (and thus pdf) output.

**Comment by jgm** [comment]
In fact, both `pandoc -f latex -t latex` and `pandoc -f org -t latex` produce the same output for your input:
```
\footnote{witty footnote}
```
Note that pandoc conversions are, in general, lossy. See the MANUAL, which says:

> Because pandoc's intermediate representation of a document is less
expressive than many of the formats it converts between, one should
not expect perfect conversions between every format and every other.
Pandoc attempts to preserve the structural elements of a document, but
not formatting details such as margin size.  And some document elements,
such as complex tables, may not fit into pandoc's simple document
model.  While conversions from pandoc's Markdown to all formats aspire
to be perfect, conversions from formats more expressive than pandoc's
Markdown can be expected to be lossy.

Our internal model for notes doesn't contain a parameter for the `[-1in]` to affect.

**Comment by mclearc** [comment]
RTF is fair enough. I should have specified that this is a note format for tufte latex. Perhaps in the future org-mode could be on par with markdown in this case (since markdown conversion respects the parameter). But thanks for the clarification!
