### ISSUE TITLE
siunitx still not parsing unit string

### ISSUE THREAD

**Issue by michaelaye** [jgm/pandoc#4296]
pandoc version 2.1

Using this example:
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
This is a measurement unit (\SI{30}{\milli\meter}) which is not parsed.
\end{document}
```
and using the command
```bash
pandoc pandoc_test.tex -o pandoc_test.docx
```
I get
```doc
This is a measurement unit (30) which is not parsed.
```
in the Word file. Note that the **value** is being parsed but not the **unit**.

**Comment by jgm** [comment]
@schrieveslaach do you want to take a look?

**Comment by zz77zz** [comment]
pandoc 2.1.1
some more examples describing the issue with common uses of siunitx:

    \documentclass{article}
    \usepackage{siunitx}
    \begin{document}
    This is a measurement unit (\SI{30}{\milli\meter}) which is not parsed.\\
    This is a measurement unit (\SI{30}{m}) which is parsed.\\
    This is a measurement unit (\SI{6}{\gram\per\square\meter}) which is not parsed.\\
    This is a measurement unit (\SI{6}{g.m^{-2}}) which is badly parsed.\\
    This is a measurement unit (\SI{18.2}{\degreeCelsius}) which is not parsed.\\
    This is a measurement unit (\SI{18.2}{°C}) which is parsed.\\
    \end{document}

and with the command  `pandoc -s Test_Pandoc_siunitx.tex -o Test_Pandoc_siunitx.rtf`

I get:

    This is a measurement unit (30) which is not parsed.
    This is a measurement unit (30 m) which is parsed.
    This is a measurement unit (6) which is not parsed.
    This is a measurement unit (6 g.m^-2) which is badly parsed.
    This is a measurement unit (18.2) which is not parsed.
    This is a measurement unit (18.2 °C) which is parsed.

**Comment by schrieveslaach** [comment]
@michaelaye, I created a PR solving your examples. @zz77zz, I wasn't able to provide code to solve all of your example.

**Comment by broncodev** [comment]
I don't know any Haskell, but hope that this helps (adapt and add to https://github.com/jgm/pandoc/commit/155a2ac0391e8b800d8d2ff0fb3ebe5e049ca278#diff-1c5206ea07dccd86de1ea3be10ff30d9):

, ("angstrom","\SIUnitSymbolAngstrom");
, ("arcmin","\arcminute");
, ("arcminute","\SIUnitSymbolArcminute");
, ("arcsecond","\SIUnitSymbolArcsecond");
, ("astronomicalunit", lit "ua");
, ("atomicmassunit", lit "u");
, ("atto", lit "a");
, ("bar", lit "bar");
, ("barn", lit "b");
, ("becquerel", lit "Bq");
, ("bel", lit "B");
, ("candela", lit "cd");
, ("celsius","\SIUnitSymbolCelsius");
, ("centi", lit "c");
, ("coulomb", lit "C");
, ("dalton", lit "Da");
, ("day", lit "d");
, ("deca", lit "d");
, ("deci", lit "d");
, ("decibel","\deci \bel");
, ("degree","\SIUnitSymbolCelsius");
, ("degree","\SIUnitSymbolDegree");
, ("deka", lit "d");
, ("electronvolt", lit "eV");
, ("exa", lit "E");
, ("farad", lit "F");
, ("femto", lit "f");
, ("giga", lit "G");
, ("gram", lit "g");
, ("hectare", lit "ha");
, ("hecto", lit "h");
, ("henry", lit "H");
, ("hertz", lit "Hz");
, ("hour", lit "h");
, ("joule", lit "J");
, ("katal", lit "kat");
, ("kelvin", lit "K");
, ("kilo", lit "k");
, ("kilogram","\kilo \gram");
, ("knot", lit "kn");
, ("liter", lit "L");
, ("litre", lit "l");
, ("lumen", lit "lm");
, ("lux", lit "lx");
, ("mega", lit "M");
, ("meter","\metre");
, ("metre", lit "m");
, ("milli", lit "m");
, ("minute", lit "min");
, ("mmHg", lit "mmHg");
, ("mole", lit "mol");
, ("nano", lit "n");
, ("nauticalmile", lit "M");
, ("neper", lit "Np");
, ("newton", lit "N");
, ("ohm","\SIUnitSymbolOhm");
, ("Pa","\pascal");
, ("pascal", lit "Pa");
, ("percent","\char 37");
, ("peta", lit "P");
, ("pico", lit "p");
, ("radian", lit "rad");
, ("second", lit "s");
, ("siemens", lit "S");
, ("sievert", lit "Sv");
, ("steradian", lit "sr");
, ("tera", lit "T");
, ("tesla", lit "T");
, ("tonne", lit "t");
, ("volt", lit "V");
, ("watt", lit "W");
, ("weber", lit "Wb");
, ("yocto", lit "y");
, ("yotta", lit "Y");
, ("zepto", lit "z");
, ("zetta", lit "Z");

(adapted from https://github.com/Authorea/LaTeXML/blob/master/lib/LaTeXML/Package/siunitx.sty.ltxml)

**Comment by jgm** [comment]
Thanks, that's helpful.
