### ISSUE TITLE
OS X installer does not check for PPC, but is Intel only.

### ISSUE THREAD

**Issue by KC8ZKF** [jgm/pandoc#430]
On a Mac PowerPC G4, running OS X 10.5.8, the installer runs without incident.  But when the user tries to run pandoc, the following error is given:

-bash: /usr/local/bin/pandoc: Bad CPU type in executable

**Comment by barracuda156** [comment]
@jgm What was the last version to build on `ppc`? (Or the last one to build with GHC 7.6.3, which is what we have on macOS PowerPC at the moment.)

**Comment by jgm** [comment]
ghc 7.6 support was dropped Sept 2 2016.
So I'd guess 1.17.2 was the last version that built with that.

**Comment by barracuda156** [comment]
@jgm Thank you! Do I need something beyond GHC itself (and obviously GCC)?

(The issue is that pre-built stuff never existed for those versions. I have fixed 7.6.3, but any other Haskell tools will have to be built from sources – and those potentially may be broken.)

**Comment by jgm** [comment]
You'll need cabal-install -- and hopefully the version constraints are strict enough that it will build. You will just have to try.

**Comment by barracuda156** [comment]
I will try. From descriptions it looks trivial: https://gist.github.com/wting/8498731
Though no one tested it on `ppc`, so surprises could happen.
