### ISSUE TITLE
[feature request] autolinebreak for fenced code under skylighting

### ISSUE THREAD

**Issue by jannick0** [jgm/pandoc#4302]
Pandoc 2.0.6 / skylighting 0.5.0.1:

It appears that for fenced code blocks with long lines there is no autolinebreak feature (for style pygments, at least).

**Example:**
`pandoc -f markdown -t latex -o long-code-line.pdf long-code-line.md`
~~~~
long-code-line.md:
~~~
   this is a very long long long long long long long long long long long long long line which is not broken
~~~
~~~~

NB: Options of the LaTeX [listings package](https://ctan.org/pkg/listings):
- breaklines (boolean)
- breakatwhitespace (boolean)
- breakautoindent
- linewidth

Apologies if there is a trivial solution to this issue making this feature request obsolete.

**Comment by jgm** [comment]
I don't think this can be implemented in skylighting itself, because skylighting has no way of knowing how much space each token takes and hence when the end of the line is reached.

If there's some latex magic that can cause auto wrapping inside a custom verbatim environment defined using fancyvrb, then we could use that.

**Comment by jannick0** [comment]
These edits in the preamble would work, too:
~~~tex
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
~~~

**Comment by georgerbr** [comment]
> These edits in the preamble would work, too:
> 
> ```tex
> \usepackage{fvextra}
> \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
> ```

How about prepending to `verbatim` instead of creating a custom environment?

```tex
% single line spacing for code
\usepackage{etoolbox}
\BeforeBeginEnvironment{verbatim}{\def\baselinestretch{1}}
```

**Comment by jannick0** [comment]
`baselinestretch` changes the spacing in **everything** of the document **after** its has been triggered. That is not the aim of the proposed feature, namely line beaks of long lines in fenced code blocks. So I can not see how this would help solving the issue.

BTW - my suggestion would amend an already existing 'custom' environment created by the current version of `pandoc`. The adjustment is tiny, and it fully addresses the issue.

Or am I missing anything here, since I am lightyears away from being a LaTeX expert?

**Comment by georgerbr** [comment]
> `baselinestretch` changes the spacing in everything of the document after its has been triggered. That is not the aim of the proposed feature, namely line beaks of long lines in fenced code blocks. So I can not see how this would help solving the issue.

Sorry, now I see expressed myself poorly. That was just an example of how it is possible to prepend commands to the existing `verbatim` environment instead of creating a new one...

> BTW - my suggestion would amend an already existing 'custom' environment created by the current version of pandoc. The adjustment is tiny, and it fully addresses the issue.

... but pandoc already does it, so your suggestion to amend looks good to me.

**Comment by aubertc** [comment]
I also think @jannick0 's suggestion perfectly fits the bill. I took the liberty to mention it as an answer to a question asked on StackExchange, cf. https://tex.stackexchange.com/a/412316/34551

**Comment by noraj** [comment]
Writing a technical report with code blocks or long string is really a nightmare. Even with fvextra and the `breakanywhere` option I did not succeed to do something about very long string.

**Comment by jgm** [comment]
> When it's code it is easy to split strings but hen you just want to put the output of a command with very long lines you can't do that.

If you don't care about where they split, you can use a lua filter to add line breaks automatically.

**Comment by noraj** [comment]
I'm using markdown to PDF conversion through a LaTeX template made by someone else. I'll rather avoid to have to tweak it.

**Comment by jgm** [comment]
A filter doesn't require changes to tempate.

**Comment by noraj** [comment]
@jgm I imagined it was something you put in your LaTeX document, but I looked for it an I saw it was an additional option to pass to pandoc. This make an extra file and I know anything about lua lang.

**Comment by tarleb** [comment]
Pandoc tries to use only packages which are shipped with *texlive-latex-recommended* in Debian-based distros. The suggested package `fvextra` is in *texlive-latex-extra*.  I believe that solving linebreaks in code is out of scope for pandoc.

My personal suggestion would be to use minted, e.g. via the [minted Lua filter](https://github.com/pandoc/lua-filters/tree/master/minted).

**Comment by doitian** [comment]
My workaround to handle the code blocks without a language is setting the language to text via a lua filter

```lua
function CodeBlock(el)
  if #el.classes == 0 then
    el.classes[1] = 'text'
  end
  return el
end

function replace (el)
  if vars[el.text] then
    return pandoc.Span(vars[el.text])
  else
    return el
  end
end

return {{CodeBlock = CodeBlock}}
```

Save the file and use it via the pandoc command line option: `--lua-filter path/to/the/filter.lua`.

**Comment by tigerhawkvok** [comment]
Perhaps I took a hammer to an egg here, but I was having a hard time line breaking code of regex so I needed break-anywhere. I ended up with this:

```yaml
---
format:
    html:
        code-fold: true
    pdf:
        header-includes:
            - "\\usepackage{fvextra}"
            - "\\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\\\\{\\}, breaklines, breaknonspaceingroup, breakanywhere}"
            - "\\fvset{breaklines}"
            - "\\fvset{breaknonspaceingroup}"
            - "\\fvset{breakanywhere}"
latex-auto-install: true
---
```
