### ISSUE TITLE
Beamer {.plain} frames still show title bar/color

### ISSUE THREAD

**Issue by luub** [jgm/pandoc#4307]
In Pandoc version 1, I was able to add a png to a beamer presentation that covered the full frame. No title or title color was shown with the option ## {.plain}. This is also covered in the Pandoc manual. Since version 2, the title color (in the title bar of the frame) still shows up and the png image is "shifted down" (hence, lower part of the png is outside the frame now).

Pandoc 2.1.1 (or anything since version 2.0).
RStudio 1.1.414 for typesetting

Minimal working example:

```
---
title: "Untitled"
author: "Name author"
output:
  beamer_presentation:
    keep_tex: true
    theme: "AnnArbor"
---
## Title one
Hello!

## {.plain}
\vspace*{-1pt}
\makebox[\linewidth]{\includegraphics[width=\paperwidth]{test.png}}

## {.plain}
Hello, plain again?
```

The difference in the tex-file from Pandoc version 1 and 2 seems to be that a \protect command has been added. If I remove these commands in TexShop and run it, everything works.

Tex-File since Pandoc v2:

```
\begin{frame}[plain]{%
\protect\hypertarget{section}{%
}}
\vspace*{-1pt}
\makebox[\linewidth]{\includegraphics[width=\paperwidth]{test.png}}
```

Tex-File from Pandoc v1:

```
\begin{frame}[plain]{}
\vspace*{-1pt}
\makebox[\linewidth]{\includegraphics[width=\paperwidth]{test.png}}
```

![test](https://user-images.githubusercontent.com/35816143/35409276-01b85b74-0212-11e8-985c-b23e5b11ea72.png)

![example](https://user-images.githubusercontent.com/35816143/35409643-2219327a-0213-11e8-8a49-33152d56d4f9.png)

![screen shot 2018-01-25 at 20 56 37](https://user-images.githubusercontent.com/35816143/35409650-2b7efbf6-0213-11e8-99bf-a276f6d06540.png)

**Comment by idrhee** [comment]
Just to add: I'm having the exact same issue. It used to work before the update, but not anymore :(

**Comment by mb21** [comment]
I think this was added in https://github.com/jgm/pandoc/commit/38c3a683468428fc26485f3346bdbbb4eb7d6ef2

Do you have recommendation for the LaTeX output that works in both use cases?

**Comment by idrhee** [comment]
Thanks for the response. Do you think maybe it'd be possible to build some kind of if-statement that allows any {.plain} frames to automatically skip the hypertarget generation? Maybe that'll provide a solution.

**Comment by jgm** [comment]
I've pushed a fix.  Note: you can disable the `auto_identifiers` extension (`-f markdown-auto_identifiers`), and that should work around the problem with current pandoc.
