### ISSUE TITLE
yaml files are not added to the yaml meta block

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#4312]
According to the manual (extension: `yaml_metadata_block`, which is on by default) it should be possibe to add metadata information using a `.yaml` file:

> A YAML metadata block may occur anywhere in the document, but if it is not at the beginning, it must be preceded by a blank line. (Note that, because of the way pandoc concatenates input files when several are provided, you may also keep the metadata in a separate YAML file and pass it to pandoc as an argument, along with your Markdown files

I've tried this with pandoc version 2.1.1 but the metadata blocks get's not merged, it gets appended to the input file, if the yaml file is the last one. Here is my test case with a simple `test.md` file:

```markdown
# Test

Some text.
```
metadata.yaml:
```yaml
---
title: metatests
---
```
Command: `pandoc -s -f markdown+yaml_metadata_block -t markdown test.md metadata.yaml`
Output:
```markdown
Test
====

Some text.
----------

title: metatests
----------------
```
If I change the `metadata.yaml` to use `...` als yaml block end:

```yaml
---
title: metatests
...
```
Output:
```markdown
Test
====

Some text.
----------

title: metatests ...
```
If I provide the yaml file with the parameter `-H` (`pandoc -s -f markdown+yaml_metadata_block -t markdown test.md -H metadata.yaml`), the output is:
```markdown
---
title: metatests
---

Test
====

Some text.
```

It looks like, the yaml file is now treated as yaml. 

But if I convert it to html, an error occurs:
> [WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'test'

If I change the order of the input files and provide `metadata.yaml` as the first file or pipe the markdown source in (`echo -e "# Headline\n\nsome text" | pandoc - -s -f markdown+yaml_metadata_block -t markdown metadata.yaml`) everything is fine.
It does not matter if I provide the yaml file with the parameter `-H`.

In case the source markdown contains a yaml block already, like:
```markdown
---
author: Mathias Walter
...

# Test

Some text.
```
The output with `pandoc -s -f markdown+yaml_metadata_block -t markdown test.md -H metadata.yaml` is, even if I change the order of the markdown and yaml file (with `-H`):
```markdown
---
author: Mathias Walter
---

---
title: metatests
---

Test
====

Some text.
```
But if I use `metadata.yaml` without `-H` and as the first input file (`pandoc -s -f markdown+yaml_metadata_block -t markdown metadata.yaml test.md`, the two metadata blocks get merged:
```markdown
---
author: Mathias Walter
title: metatests
---

Test
====

Some text.
```
Conversion to html works fine without a warning.

That's all a bit wired.

**Comment by tolot27** [comment]
Just to note: I've discovered these problems as I tied to write a lua filter which adds some lines to header-includes (i. e. [track-changes filter](https://github.com/tolot27/lua-filters/tree/track-changes/track-changes). It worked fine with/without metadata blocks inside the source markdown file until a yaml input file and/or `-H/--include-in-header` was used.

**Comment by jgm** [comment]
You need to make sure there's a blank line before the
metadata, or the top `---` may cause a previous text
line to be interpreted as a setext header.

Either put the blank at the end of the previous file,
or put it at the beginning of the yaml file.

**Comment by tolot27** [comment]
Okay that solves most of the problems reported above.

The manual should be improved at that point. Currently, your suggestion is not mentioned. Only:

> Just be sure that the YAML file begins with `---` and ends with `---` or `...`.)

Also not the unbalanced closing bracket

I suggest that in case the yaml file has the extension `.yaml` a blank line will be prefixed automatically, if necessary,

**Comment by jgm** [comment]
> I suggest that in case the yaml file has the extension .yaml a blank line will be prefixed automatically, if necessary,

That seems like a good idea.

**Comment by tolot27** [comment]
I assume this can be easily fixed. Am I right?

**Comment by tolot27** [comment]
I've checked this case. The major difference is that the row of three or more tildes (`~`) starting a code fence does not have to have a line break at the end. It is added automatically if a code fence spans multiple files. Interesting behaviour ... and exactly the same behaviour I'd like to see for the reported case.
Anyway, the manual could mention this case. Maybe:

> Just be sure that the YAML file begins with --- and ends with --- or ....) and there is a line break at the and of the previous file.

**Comment by tolot27** [comment]
You commented on 26th, January:
>You need to make sure there's a blank line before the metadata, or the top `---` may cause a previous text line to be interpreted as a setext header.

But I think the only requirement is that there should be a NEWLINE character at the end of the previous file. I've tested my initial example which does not work. It looked like:

![image](https://user-images.githubusercontent.com/1370732/39894576-9c7f545e-54a7-11e8-8125-4698d63bb06e.png)

But as soon as I add a NEWLINE (LF), it works:

![image](https://user-images.githubusercontent.com/1370732/39894273-96b5782e-54a6-11e8-8d42-1ebd4e103297.png)

... and I get:
```
---
title: metatests
---

Test
====

Some text.
```

Probably it is easier to implement and would behave identically to fenced code blocks splitting over multiple files.

**Comment by jgm** [comment]
So you have a text file that does not end with a LF?
It's standard on *nix for all text files to end with a LF,
and that's what pandoc assumes.

As this SO post says
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
it's part of the POSIX standard that a line ends with a terminating
newline character.  "All Unix tools expect this convention and work with
it."

I think this issue can be closed.  Make sure your text files
end with a newline. Many text editors will do this by default.

**Comment by tolot27** [comment]
I'm working in both worlds, Unix and Windows. And my example was created using Notepad. Neither Notpad nor Notepad++ end a text file with an CR+LF automatically.
Indeed, I can take care of adding an LF to markdown files I write, but not for files other people write.

Since pandoc is line based (I assume), it would make sense for me to treat the last line of a text file till the EOF as one complete line regardless if it ends with an LF or not.

I just suggest a *consistent* behavior of pandoc. Currently, it behaves differently if the last line contains some text or the start sequence of a code fence (`~~~`) and does not end with an LF before the EOF.

**Comment by jgm** [comment]
Mathias Walter <notifications@github.com> writes:

> Since pandoc is line based (I assume), it would make sense for me to treat the last line of a text file till the EOF as one complete line regardless if it ends with an LF or not.

We intentionally don't do that.

This is to support the possibility of using files that do not end with
a line-ending character for special purposes.  When `a.md` and
`b.md` end with LF, the effect of `pandoc a.md b.md` is that there
will be a blank line between the contents of the files.  If you don't
want this, and I've seen some cases where you don't (e.g., the case
where `a.md` ends with a starting code fence and `b.md` contains the
code), then you can avoid it by making sure that `a.md` does not end
with a LF.

This behavior seems ideal to me.  In the normal case (text files
end with LF), it does what you'd normally expect.  But it gives the
user the flexibility to do something else with special intervention.

> I just suggest a *consistent* behavior of pandoc. Currently, it
> behaves differently if the last line contains some text or the start
> sequence of a code fence (`~~~`) and does not end with an LF before
> the EOF.

The behavior is entirely consistent.  One LF is added between the
files. Always. Consistently. This couldn't be more predictable.
A user who doesn't want lines from two files to be adjoining must ensure
that the files end with LF.

**Comment by tolot27** [comment]
You are right. I've verified it again and confirm this behavior. I don't know why I came to a different conclusion this morning. I was sure I saw a difference, otherwise I had not wrote it.
Anyway, everything is fine now. Thanks for clarification.
