### ISSUE TITLE
Converting from Markdown to DokuWiki preserves backslashes/escapes in table.

### ISSUE THREAD

**Issue by RobertZenz** [jgm/pandoc#4313]
When I'm converting from Markdown to DokuWiki, backslashes which are used to create paragraphs inside table cell are preserved.

Example:

    ----------------------------------------------------------------------------
    Column             Column
    -----------------  ---------------------------------------------------------
    Value              This is some text.\
                       \
                       And this is a new paragraph.
    ----------------------------------------------------------------------------

HTML (is as expected):

    <table>
        <colgroup>
            <col style="width: 25%" />
            <col style="width: 75%" />
        </colgroup>
        <thead>
            <tr class="header">
                <th style="text-align: left;">Column</th>
                <th style="text-align: left;">Column</th>
            </tr>
        </thead>
        <tbody>
            <tr class="odd">
                <td style="text-align: left;">Value</td>
                <td style="text-align: left;">This is some text.<br />
                        <br />
                        And this is a new paragraph.</td>
                </tr>
        </tbody>
    </table>

DokuWiki:

    ^Column ^Column ^
    |Value |This is some text.\\\\ \\\\ And this is a new paragraph. |

As far as I can see, these should not be preserved.

**Comment by jgm** [comment]
+++ RobertZenz [Jan 26 18 12:26 ]:
>   DokuWiki:
>^Column ^Column ^
>|Value |This is some text.\\\\ \\\\ And this is a new paragraph. |
>
>   As far as I can see, these should not be preserved.

What do you mean exactly?  Is this invalid DokuWiki?  How
does this display in DokuWiki?

Note:  if you want multiple paragraphs in a Markdown table,
you should use grid tables. That's the only format that
allows multiple blocks in cells.

**Comment by RobertZenz** [comment]
It is displayed with the backslashes when rendered by DokuWiki:

    This is some text.\\
    \\
    And this is a new paragraph.

But it should display without them, I'd say. So it shouldn't be converted to 4 backslashes, but only two.

I just tried with grid tables, and that works. It's a lot more type-work, though.

**Comment by jgm** [comment]
Can you confirm that
```
^Column ^Column ^
|Value |This is some text.\\ \\ And this is a new paragraph. |
```
will render as expected in DokuWiki (with line breaks in the cell)?

**Comment by RobertZenz** [comment]
Sorry for the long delay, yes, I can confirm that the two-backslash variant is rendering correctly.

![Screenshot of a DokuWiki showing that.](https://user-images.githubusercontent.com/611377/36100254-8a3815ae-0ffd-11e8-8dfd-af9f1abb1ce9.png)

**Comment by RobertZenz** [comment]
As an additional note, the backslashes are not present in the native/JSON representation:

    [Table [] [AlignLeft,AlignLeft] [0.25,0.75]
     [[Plain [Str "Column"]]
     ,[Plain [Str "Column"]]]
     [[[Plain [Str "Value"]]
      ,[Plain [Str "This",Space,Str "is",Space,Str "some",Space,Str "text.",LineBreak,LineBreak,Str "And",Space,Str "this",Space,Str "is",Space,Str "a",Space,Str "new",Space,Str "paragraph."]]]]]

**Comment by RobertZenz** [comment]
I'm not able to read much Haskell (well, I did never read some until some minutes ago), but it seems like [line #370 and below in DokuWiki.hs (0d935bd)](https://github.com/jgm/pandoc/blob/0d935bd081bb4013168dc114461ab7c47fec2f44/src/Text/Pandoc/Writers/DokuWiki.hs#L370) has something to do with it.

**Comment by mb21** [comment]
Indeed, that `backSlashLineBreaks` function was introduced by [this commit](https://github.com/jgm/pandoc/commit/ccda2a902c537d7c81fcf9131d4f92cad6ab968d) without any test cases. Maybe @jkr can tell us whether the double escaping was intended?

**Comment by jkr** [comment]
Don't have a strong memory, but extensive discussion is here:

https://github.com/jgm/pandoc/issues/1576

**Comment by jkr** [comment]
The proposed test case was here: https://github.com/jgm/pandoc/pull/1580#issuecomment-53961737

It looks like, despite best laid plans, it was never added.

**Comment by mb21** [comment]
No it was, in `test/dokuwiki_multiblock_table`: seems the heuristic used in `backSlashLineBreaks :: String -> String` works for splitting up `Para` (e.g. as in `test/dokuwiki_multiblock_table` but not when the input contains `LineBreak`... so maybe it was https://github.com/mb21/pandoc/commit/a6b469c02b3c21cfc1b5169ea3e75b7388f55691 that's the issue here...

**Comment by mb21** [comment]
@jkr, so the bug was indeed added with the `LineBreak`s, not with `backSlashLineBreaks`.

I still am not quite sure why `backSlashLineBreaks` works in all cases, though. `backSlashLineBreaks . vcat` could probably rewritten as a single function that does only one pass etc... but anyway...
