### ISSUE TITLE
Separate tables seem to be joined in docx output

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#4315]
In the golden test for tables in the docx writer, three consecutive tables appear in word to be one table. Compare the file in `test/docx/tables.docx` and `test/docx/golden/tables.docx`. In the first, clicking in a table in Word allows you to select the boundaries of that individual table. In the latter, you seem only able to select all three tables together.

Note that the docx writer does write each table within its own `<w:tbl>` tags, so these *are* separate tables -- but they don't seem like it from a user POV.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Jan 27 18 13:15 ]:
>   In the golden test for tables in the docx writer, three consecutive
>   tables appear in word to be one table. Compare the file in
>   test/docx/tables.docx and test/docx/golden/tables.docx. In the first,
>   clicking in a table in Word allows you to select the boundaries of that
>   individual table. In the latter, you seem only able to select all three
>   tables together.
>
>   Note that the docx writer does write each table within its own <w:tbl>
>   tags, so these are separate tables -- but they don't seem like it from
>   a user POV.

Weird. Do you have any idea what we can do to ensure that these are
separated?

**Comment by jkr** [comment]
BTW, the empty paragraphs were there in the original. What I haven't experimented with is whether we can achieve something similar using styles in the reference doc.

**Comment by artasom** [comment]
Hello,
I know this is an open and somehow old issue but I am facing this problem right now... Are there any (recent) updates on it?
Regards.

**Comment by khalid-hussain** [comment]
This issue is still present in Pandoc `v2.10.1`. Any updates?

**Comment by khalid-hussain** [comment]
Temporary solution.

Add the following code between tables.

```
```{=openxml}
<w:p />
```
```

**Comment by agusmba** [comment]
FWIW, I think Word automatically merges tables when they are next to each other.

The solutions is to have an empty line between them (that's what I'm compelled to do when working exclusively within Word).

Converting from .md, I have also used `&nbsp;` in a single line between the tables (surounded by empty lines) as a workaround

**Comment by jgm** [comment]
I've fixed this, inserting an empty p.
