### ISSUE TITLE
Automatic section references are incorrect in Markdown to DokuWiki conversion with special symbols.

### ISSUE THREAD

**Issue by RobertZenz** [jgm/pandoc#4318]
When using Pandoc 2.0.5 and converting from Markdown to DokuWiki, the automatic section references are incorrect if the section header contains a special character.

`example.markdown`

    This header / Or something else
    ===============================
    
    And here is an automatic reference: [This header / Or something else]

Which yields the following DokuWiki markup:

    ====== This header / Or something else ======
    
    And here is an automatic reference: [[#this-header-or-something-else|This header / Or something else]]

DokuWiki itself, however, generates HTML that uses a different identifier:

    <h1 id="#this_headeror_something_else">This header / Or something else</h1>
    <div>
        <p>And here is an automatic reference: <a href="#this-header-or-something-else">This header / Or something else</a></p>
    </div>

Note that the two words in the identifier (which were separated by the slash) are collapsed. Also DokuWiki uses underscores instead of dashes (but that doesn't seem to be a problem).

Now that I think about it, not sure if that isn't actually a bug in DokuWiki.

**Comment by jgm** [comment]
Looks like DokuWiki just uses a different scheme for automatic generation of IDs for headers than pandoc's Markdown does.  I don't see this as a bug, though.

**Comment by RobertZenz** [comment]
Ahrm, well, the resulting document is not "well formed/valid", so I'd consider it a bug.

I mean, I can wok around it by using a filter, but still.

**Comment by jgm** [comment]
+++ RobertZenz [Feb 03 18 11:24 ]:
>   Ahrm, well, the resulting document is not "well formed/valid", so I'd
>   consider it a bug.

There's not much we can do, since the gfm writer embeds a C
library and it doesn't support header identifiers.

**Comment by RobertZenz** [comment]
Mh, I'm a little bit lost here. Do I understand this correctly:

 1. The Markdown is parsed.
 2. The internal representation is created, including the creation of the identifiers (among everything else).
 3. This is handed to the DokuWiki writer to be written.

Did I get that right? If yes, step 3 is performed by a different library?

**Comment by mb21** [comment]
> If yes, step 3 is performed by a different library?

yes, with `-t gfm` cmark is used...
