### ISSUE TITLE
Inconsistent numbering on multilevel list when reading from docx

### ISSUE THREAD

**Issue by ggirard07** [jgm/pandoc#4324]
# Steps to reproduce
I am trying to test Pandoc by converting a fairly simple docx to HTML.
It looks like the reader used for docx does not properly handle numbering restarting on multilevel lists.
I think the issue comes from the docx reader as native representation also contains the wrong restart index.

Command line used
```
pandoc.exe -s -f docx -t html -o output.html --verbose "C:\Users\me\Desktop\pandoc-2.1.1\Numbering issue.docx"
```

Here a simple file to reproduce the issue:  [Numbering issue.docx](https://github.com/jgm/pandoc/files/1674956/Numbering.issue.docx)

# Docx content:
```
1. Head 1
  1. Head 1.1
  2. Head 1.2
2. Head 2
  1. Head 2.1
```

# Expected HTML result:
```
1. Head 1
  1. Head 1.1
  2. Head 1.2
2. Head 2
  1. Head 2.1
```

# Actual HTML result:
```
1. Head 1
  1. Head 1.1
  2. Head 1.2
2. Head 2
  3. Head 2.1
```

# Native result:
```
Pandoc (Meta {unMeta = fromList []})
[OrderedList (1,Decimal,Period)
 [[Para [Str "Head",Space,Str "1"]
  ,OrderedList (1,Decimal,DefaultDelim)
   [[Para [Str "Head",Space,Str "1.1"]]
   ,[Para [Str "Head",Space,Str "1.2"]]]]
 ,[Para [Str "Head",Space,Str "2"]
  ,OrderedList (3,Decimal,DefaultDelim)
   [[Para [Str "Head",Space,Str "2.1"]]]]]]
```

# Version
```
C:\Users\me\Desktop\pandoc-2.1.1>pandoc -v
pandoc 2.1.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.6
```

**Comment by jkr** [comment]
Hmm... lists in docx continue to be weird. They do continue after an interruption, but not if the interruption is a lower level of the same list. I think this requires a fix in `Docx/Lists.hs`.

**Comment by achern** [comment]
Are there any workarounds for this issue? It's still happening in 2.4.

It seems like the list numbering never restarts at all after converting to markdown. I've even tried separating the list into multiple lists and the numbering still always continues where it previously left off (example: [listtest.docx](https://github.com/jgm/pandoc/files/2561193/listtest.docx))

**Comment by jgm** [comment]
@jkr any idea how to solve this?
