### ISSUE TITLE
Invalid depth attribute in docx to TEI

### ISSUE THREAD

**Issue by joeytakeda** [jgm/pandoc#4331]
Using 2.1.1 and converting from docx to TEI. For images in docx, the result TEI has an invalid `@depth` attribute. Should this be height?

When the attached file is converted using command:
```
pandoc -f docx -t tei sample.docx
```
The result TEI is:
```
<p>
<figure>
<graphic url="media/image1.png" width="5.06875in" depth="2.66109in" />
</figure>
</p>
```
I suggest that `graphic/@depth` should be changed to `graphic/@height`: 

```
<graphic url="media/image1.png" width="5.06875in" height="2.66109in" />
```

**Comment by jgm** [comment]
Seems plausible to me, but I don't know anything about TEI.
Let's see if @c-forster (who contributed the TEI writer) had a reason for using depth instead of height?

**Comment by c-forster** [comment]
That seems like an outright error to me. depth is not a valid attribute in TEI. I built the TEI writer by modifying the DocBook writer, and in DocBook the imagedata element takes width and depth, so I suspect that is the source of this error.
