### ISSUE TITLE
latex reader ignores \include statements

### ISSUE THREAD

**Issue by beaniecopter** [jgm/pandoc#4332]
pandoc 1.12.4.2

Attempting to convert LaTeX to HTML:

pandoc -r latex -f html -o testfile.html testfile.tex

testfile.tex has a series of \include staments:
   \include(orange)
   \include(apple)
   \include(banana)

All .tex files are in the same directory:
   testfile.tex
   orange.tex
   apple.tex
   banana.tex
but testfile.html does not include orange, apple, and banana.

**Comment by tolot27** [comment]
Please try a newer pandoc version, i. e. 2.1.1, because it should work now (see examples in the fixed issue #3971). `\input` should work as well.

**Comment by beaniecopter** [comment]
Pardon the duplicate; I searched the reports, but missed #3971.  Regrettably, I am running Debian 8, and version 1.12.4.2 is the latest in the synaptic repository.  So either I wait until Debian has a newer version, or else I learn to bypass Synaptic (which I hesitate to do).  But thanks for the quick response!

**Comment by tolot27** [comment]
You can also try to install the Debian package from the [releases page](https://github.com/jgm/pandoc/releases). Or extract the linux version to `~/bin`.

**Comment by beaniecopter** [comment]
On Thu, 01 Feb 2018 06:26:59 +0000 (UTC), Mathias Walter  wrote:
> You can also try to install the Debian package from the [releases page](https://github.com/jgm/pandoc/releases). Or extract the linux version to `~/bin`.


Thanks; I never have done that. I'll check it out tomorrow.  RLH
