### ISSUE TITLE
Pandoc cannot parse odt files from Calligra

### ISSUE THREAD

**Issue by dcbuist** [jgm/pandoc#4336]
odt files created, modified or saved in Calligra (KDE office suite) cannot be parsed by pandoc. Pandoc expects content.xml to contain the element  `<office:font-face-decls>`. However this element is optional and not all odt files contain it. odt files produced by Libreoffice contain this element by default, but odt files from Calligra do not. When attempting to convert an odt file from Calligra the following output is obtained:

`[buist@DL-7370 ODT]$ pandoc -s -o TestDocument.docx TestDocument1.odt 
Couldn't parse odt file.
[buist@DL-7370 ODT]$ pandoc -s -o TestDocument.txt TestDocument1.odt    
Couldn't parse odt file.`

If the file is unzipped and content.xml is modified by the insertion of `<office:font-face-decls/>` and then rezipped, pandoc can now parse and convert the file.

Pandoc version: 2.1.1

**Comment by jgm** [comment]
@MarLinn do you want to have a look at this issue?
