### ISSUE TITLE
Pandoc latex chokes on alltt underscore (_)

### ISSUE THREAD

**Issue by matthiasdiener** [jgm/pandoc#4337]
pandoc 2.1.1 (Homebrew)

The following code works in latex but not in pandoc:

```latex
\documentclass{article}
\usepackage{alltt}
\begin{document}
\begin{alltt}
_
\end{alltt}
\end{document}
```

Error message:
```
Error at "source" (line 5, column 1):
unexpected _
expecting \end{alltt}
_
^
```

**Comment by jgm** [comment]
We could add support for alltt.  As I understand it, it's like a verbatim environment, but `\`, `{`, and `}` have their normal meanings so that commands can be used.

**Comment by matthiasdiener** [comment]
From what I understood, alltt was already supported (see e.g. https://github.com/jgm/pandoc/commit/754d1cef7ba30d1df8fbc8e1a9612d67d5a8aa99), but this has not been working recently.

**Comment by jgm** [comment]
Yes, we sort of support it. Actually, we should parse it
as a LineBlock element, that would be the best fit.
We'll need a better parser that understands that only
`\`, `{`, and `}` are special characters in this context.

+++ Matthias Diener [Feb 02 18 17:43 ]:
>   From what I understood, alltt was already supported (see e.g.
>   [1]754d1ce), but this has not been working recently.

**Comment by Geremia** [comment]
I get a similar issue but with `flalign*`:
```
$ iconv --from-code=ISO-8859-1 --to-code=UTF-8 25157-t.tex > utf8.tex

$ pdflatex utf8.tex  # runs without errors and produces correct utf8.pdf

$ pandoc -o out.epub utf8.tex

error at "source" (line 387, column 4):
unexpected _
expecting \end{flalign*}
& X_1f=0,\ X_2f=0,\ldots X_qf=0  &
```
input file from ProjectGutenberg: [25157-t.tex](https://www.gutenberg.org/files/25157/25157-t/25157-t.tex)

**Comment by jgm** [comment]
Relevant: https://tex.stackexchange.com/questions/469274/when-are-underscores-allowed-and-when-are-they-not-allowed

**Comment by tarleb** [comment]
The original sample document now compiles ok.

```
% pandoc test.latex -t native             
[Para [Code ("",[],[]) "_"]]
```

However, I don't quite understand the intricacies of this issue. Should it stay open?

**Comment by jgm** [comment]
Looks like we added support for altt and didn't close this!
