### ISSUE TITLE
Support --base-header-level=-1

### ISSUE THREAD

**Issue by rauschma** [jgm/pandoc#4342]
Use case: the topmost level in my content is `##`, but I’d like it to be output as if it were `#`.

Details: I’m finding that \parts don’t work well for EPUB and MOBI, but are nice for PDF. So my work-around is to exclude the parts for the former two. However, then the top heading level is `##` and I’d like to reduce it to `#`. `--base-header-level=-1` would be the simplest solution.

**Comment by mb21** [comment]
> I’m finding that \parts don’t work well for EPUB

ePUB actually contains HTML not LaTeX, so not sure what you mean.

Also, `base-header-level` actually defaults to 1...
