### ISSUE TITLE
Docx writer: Deleted tracked changes converted to regular text

### ISSUE THREAD

**Issue by HeirOfNorton** [jgm/pandoc#4346]
I found this trying to round-trip files from Docx to Markdown and back again, but it happens even with hand-written minimum test. When converting from Markdown to Docx, spans with the ".addition" or ".deletion" class should be converted to tracked changes in the Docx output. This does work with ".addition", but spans with ".deletion" are output as normal text. This happens no matter what value I use for the `--track-changes` option.

Tested with pandoc 2.1.1 on Linux.

**Comment by jkr** [comment]
I believe this was fixed in https://github.com/jgm/pandoc/commit/0d7aedca58742f9c353010d9877ef666ee4c7af0. (I don't have your exact test case, so I can't say for sure, but it looks like that issue.)

**Comment by HeirOfNorton** [comment]
Oh, sorry I missed the earlier issue. I don't have a way to compile the newer commits at the moment, but I'll test it at the next release.
I also noticed that Insertion changes were being doubled up in the docx file, and looking at the code this might fix that, as well.
Thanks!
