### ISSUE TITLE
Bracketed spans lose leading or trailing space

### ISSUE THREAD

**Issue by HeirOfNorton** [jgm/pandoc#4347]
With bracketed spans, if the text in the span begins or ends with a space, that space is stripped on conversion. This does not happen with raw spans, which convert leading or trailing spaces into Space nodes in the AST.

Tested with Pandoc 2.1.1 on Linux.

**Comment by jkr** [comment]
I believe this was fixed in https://github.com/jgm/pandoc/commit/0d7aedca58742f9c353010d9877ef666ee4c7af0. (I don't have your exact test case, so I can't say for sure, but it looks like that issue.)

**Comment by jgm** [comment]
This is consistent with how pandoc has always behaved with bracketed links. I'd be reluctant to change this.  Raw spans behave similarly:
```
% pandoc -t native
x` raw `{=html}
[Para [Str "x",RawInline (Format "html") "raw"]]
```

**Comment by HeirOfNorton** [comment]
I suppose that makes sense. I was comparing it to raw HTML spans, that do not behave that way:

    pandoc -t native
    x<span> raw </span>
    [Para [Str "x",Span ("",[],[]) [Space,Str "raw",Space]]]

Keeping native Spans and raw Spans consistent makes more sense to me, especially since Docx tracked changes and comments convert to and from Spans, so those missing Spaces are sometimes important. But, if you do decide to keep them this way, there is a workaround just by using HTML-style spans.
