### ISSUE TITLE
Self-contained HTML coding style used is deprecated  in Chrome M65 (March 2018)

### ISSUE THREAD

**Issue by rbubley** [jgm/pandoc#4351]
When generating a self-contained html document, I now see the following message in Chrome Developer tools:
 `[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.`

[Google github link on this issue](https://github.com/TakayoshiKochi/deprecate-style-in-html-imports)

**Comment by mb21** [comment]
Which pandoc version are you using? Cannot reproduce with 2.1.1 and the following:

    echo 'foo' | pandoc -s -o foo.html

Also from the link I don't quite understand what would be the preferred HTML output. Can you post it?
