### ISSUE TITLE
Backslash escapes in $...$ LaTeX pairings are rendered literally

### ISSUE THREAD

**Issue by bitemyapp** [jgm/pandoc#4353]
This LaTeX with escaped curly brackets gets rendered improperly by the ePub target.

```
The input set is $\{1, 2, 3\}$ and the output set is $\{A, B, C\}$.
```

PDF screenshot:

![screenshot from 2018-02-06 22-36-09](https://user-images.githubusercontent.com/320177/35898777-2b7cf2b4-0b8e-11e8-81f7-2cba0438bc85.png)

HTML from the ePub in Google Chrome:

![screenshot from 2018-02-06 22-36-18](https://user-images.githubusercontent.com/320177/35898781-3020ddc6-0b8e-11e8-818e-457f7f0000c8.png)

```
$ pandoc --version
pandoc 2.1.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1.1, skylighting 0.6
```

Pandoc invocation: `pandoc --css ../css/epub.css -f latex --webtex -t epub -o sample.epub epub-sample.tex`

Sorry for the bother! Please let me know if I'm doing something wrong.

**Comment by bitemyapp** [comment]
Currently entities don't seem to handled the way I'd expect either. The following LaTeX source:

```
The input set is $\lbrace 1, 2, 3 \rbrace$ and the output set is $\{A, B, C\}$
```

Results in the following HTML:

![screenshot from 2018-02-06 22-39-28](https://user-images.githubusercontent.com/320177/35898842-b0998098-0b8e-11e8-9774-e7149e0181e6.png)

But the PDF looks correct and identical to the escaped variant.

**Comment by jgm** [comment]
EPUB renderers vary wildly in how they handle math.

What method are you using to render math in HTML/EPUB?
See the "Math rendering in HTML" section of the pandoc manual.

What version of epub are you targeting?

What command are you using to produce it?

What pandoc version are you using?

**Comment by jgm** [comment]
What version of pandoc are you using?  epub3 is the default
in 2.x.  With epub3, pandoc uses mathml for math (since
that's supposed to be supported in epub3).  The result with
your input renders perfectly in iBooks.  I don't know what
ereader you're using, but it may not fully support
epub3/mathml.

+++ Chris Allen [Feb 07 18 10:16 ]:

**Comment by bitemyapp** [comment]
It must be epub3 then,

```
$ pandoc --version
pandoc 2.1.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1.1, skylighting 0.6
```

My screenshot was from Google Chrome which I am pretty sure supports MathML.

**Comment by tarleb** [comment]
> My screenshot was from Google Chrome which I am pretty sure supports MathML.

[Unfortunately, this is not true](https://bugs.chromium.org/p/chromium/issues/detail?id=152430#c43).

**Comment by jgm** [comment]
Chrome won't directly render an epub3, though.  (At least,
when I tried, it just downloaded.)  How are you viewing the
epub3 with Chrome?

You might try, e.g., the Readium plugin.

+++ Chris Allen [Feb 07 18 08:47 ]:

**Comment by bitemyapp** [comment]
@tarleb wow, that's rough.

>Chrome won't directly render an epub3,

Unzipping and navigating to the relevant HTML file. The linked stylesheet in the sub-pages works fine. I'm doing this in part because it seems to be how my intended readers consume a lot of content. Unzip -> browser. Admittedly it's usually the case that they use Firefox but same basic idea.

**Comment by jgm** [comment]
You could try a filter like https://github.com/jgm/pandoc-tex2svg


+++ Chris Allen [Feb 07 18 18:41 ]:
