### ISSUE TITLE
HTML to Docx conversion - CSS is not applying 

### ISSUE THREAD

**Issue by JagadishVaranasi** [jgm/pandoc#4354]
Hi , 

 I am facing issue in applying Css while converting HTML to Docx.

Below is the code we are using for conversion

exports.ExportToWord = async (req, res) => {
  let pandoc = require('node-pandoc');

  src = ``;

  args = '-s --toc -H pandoc.css  Inputfile.html -o outputfile.docx';

  callback = function(err, result) {
    if (err) console.error('Oh Nos: ', err);
    else {
     
      return console.log(result), result;
    }
  };

  // // Call pandoc

  pandoc(src, args, callback);
};

The pandoc.css file contains styles , When I use the doc format as output file instead of docx , css is applying but with DOCX it is not working.

Please help to solve the issue.

**Comment by jgm** [comment]
Pandoc does not attempt to interpret CSS.  That's out of scope.
