### ISSUE TITLE
pandoc 0.19: no more line numbers and bad code block appearance

### ISSUE THREAD

**Issue by haasn** [jgm/pandoc#4356]
# Steps to reproduce

example.md:

    # This is an example
    
    A code block will follow:
    
    ```c
    int main()
    {
        return 0;
    }
    ```

# Pandoc 0.19

```
λ pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.3.1, texmath 0.9.4.2, skylighting 0.4.3.2
Default user data directory: /home/nand/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
λ pandoc -o test-0.19.html example.md
```

Resulting in the following HTML:
```html
<h1 id="this-is-an-example">This is an example</h1>
<p>A code block will follow:</p>
<pre class="sourceCode c"><code class="sourceCode c"><div class="sourceLine" id="1" data-line-number="1"><span class="dt">int</span> main()</div>
<div class="sourceLine" id="2" data-line-number="2">{</div>
<div class="sourceLine" id="3" data-line-number="3">    <span class="cf">return</span> <span class="dv">0</span>;</div>
<div class="sourceLine" id="4" data-line-number="4">}</div></code></pre>
```

Which looks very bad for me (excessive line spacing):
![pandoc 0.19](https://0x0.st/scvS.png)

I tried playing around with some CSS rules, but even setting `margin: 0; padding: 0` as well as `line-height: 100%` didn't seem to fix anything. I still get this crazy line spacing that I just can't seem to get rid of.

# Pandoc 0.18

If you compare this, for example, to pandoc 0.18, the result is much better:

```
λ pandoc --version
pandoc 1.18
Compiled with pandoc-types 1.17.3.1, texmath 0.8.6.7, highlighting-kate 0.6.4
Default user data directory: /home/nand/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
λ pandoc -o test-0.18.html example.md
```

Resulting in:
```html
<h1 id="this-is-an-example">This is an example</h1>
<p>A code block will follow:</p>
<div class="sourceCode"><pre class="sourceCode c"><code class="sourceCode c"><span class="dt">int</span> main()
{
    <span class="cf">return</span> <span class="dv">0</span>;
}</code></pre></div>
```

Which renders like this for me:
![pandoc 0.18](https://0x0.st/scv2.png)

# Missing line numbers

In addition to the above issues, I also noticed that pandoc no longer seems capable of generating line numbers. In the
past, you were able to generate line numbers for code blocks by using the following syntax:

    # This is an example
    
    A code block will follow:
    
    ~~~~ {.c .numberLines}
    int main()
    {
        return 0;
    }
    ~~~~

This resulted in HTML like this under pandoc 0.18:

```html
<h1 id="this-is-an-example">This is an example</h1>
<p>A code block will follow:</p>
<div class="sourceCode"><table class="sourceCode c numberLines"><tr class="sourceCode"><td class="lineNumbers"><pre>1
2
3
4
</pre></td><td class="sourceCode"><pre><code class="sourceCode c"><span class="dt">int</span> main()
{
    <span class="cf">return</span> <span class="dv">0</span>;
}</code></pre></td></tr></table></div>
```

Resulting in the following appearance:

![pandoc 0.18 with line numbers](https://0x0.st/scvp.png)
(the result of which could be further styled to look better as well)

With pandoc 0.19, this seems gone - `numberLines` just gets added to the list of classes for the `pre.sourceCode` element.

All of this seems to be a result of the switch from highlighting-kate to skylighting. Failing support for the former,
would it be possible to at least get back the option to generate line numbers, if not the ability to suppress all of
those superfluous `<div>` elements that mess up the appearance?

**Comment by haasn** [comment]
After asking around, I managed to find something that sort of seems to work:

```css
pre.sourceCode {
    line-height: 120%;
}

code.sourceCode > div.sourceLine {
    display: inline;
}
```

The key is the `display:inline`. That alone removes most of the spacing, but it still looks somewhat unnatural. Adding the `line-height: 120%` fixes that as well.

That said, I still can't figure out how to get padding in between the `pre.sourceCode`'s border and the content itself, but I'll have to live with that.

That solves one half of this issue, but I also still can't figure out how to get line numbers to display at all.

**Comment by jgm** [comment]
Why don't you try the latest version of pandoc instead?

**Comment by haasn** [comment]
This is the latest version of pandoc available for my system and configuration. (pandoc 2.1 pulls in GHC HEAD)

**Comment by jgm** [comment]
We supply binaries for linux, windows, macos.  The linux
binary is fully statically linked. Have you tried that?
There have been changes in code presentation since your
version; there's a good chance your issue has been fixed,
and if not, we'll need a report for the current version.

+++ Niklas Haas [Feb 09 18 23:49 ]:
>   This is the latest version of pandoc available for my system and
>   configuration. (pandoc 2.1 pulls in GHC HEAD)

**Comment by jgm** [comment]
I'm closing this, but feel free to open up a new issue if the current version does not work for you.

Note:  if you're using a custom template instead of the CSS pandoc automatically inserts from skylighting, you may have bad results.  Skylighting does have different CSS expectations than highlighting-kate.
