### ISSUE TITLE
at sign cannot escaped in markdown output

### ISSUE THREAD

**Issue by louisabraham** [jgm/pandoc#4366]
I have a markdown document that contains citations (with `--filter pandoc-citeproc`).

However, I want to put an at sign ("@") without it being treated as a citation, which is achieved by escaping it ("\@").

The problem is that the markdown output (that I use for formatting) doesn't keep the "\@".

Maybe there should be an option for that ? Or the escaped at signs should be kept ?

**Comment by jgm** [comment]
Could you please give a complete example (input, output, exact command used)?  I can't quite tell what the problem is.

**Comment by louisabraham** [comment]
test.md

    @abc

    \@bcd

test.bib

    @article{abc,
      title=abc,
      author=abc,
      year=2018
    }

build.sh

    pandoc test.md -o test.pdf --filter pandoc-citeproc --bibliography test.bib

format.md (modified version of `pandoc -D markdown`, see [there](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pandoc-discuss/3LHnq4A_w0U/qlBOeHl8AQAJ))

    $if(titleblock)$
    $titleblock$

    $endif$
    $for(include-before)$
    $include-before$

    $endfor$
    $if(toc)$
    $table-of-contents$

    $endif$
    $body$
    $for(include-after)$

    $include-after$
    $endfor$

format.sh

    pandoc test.md -so test.md

test.md after format.sh

    @abc

    @bcd

And after that, the pdf produced build.sh interprets `@bcd` as an unknown reference and prints some "(???)".

**Comment by jgm** [comment]
So, the problem is that, in producing markdown output, a
literal @ is not escaped, even when it would otherwise
be interpreted as starting a citation.

**Comment by louisabraham** [comment]
I think so too.
Originally I thought it could also be solved in citeproc, but indeed escaping @ is better.
