### ISSUE TITLE
smart handling of unsorted RST headers

### ISSUE THREAD

**Issue by danse** [jgm/pandoc#4373]
the RST format deducts header levels from the order headers are presented in the document. as a result a sequence of headers with levels 2, 1, 2, 3 will be represented in RST with a structure whose actual semantic is 1, 2, 1, 3 which is a malformed header structure and would trigger errors in software consuming the RST. the following native doc is enough to generate a fatal RST parsing error in `rst2html`
```
[Header 2 ("",[],[]) [Str "2"]
,Header 1 ("",[],[]) [Str "1"]
,Header 2 ("",[],[]) [Str "2"]
,Header 3 ("",[],[]) [Str "3"]]
```
the following code is the first draft of a filter which fixes the problem by adding missing headers. in a long RST file, having additional headers added by pandoc is better than having to fix the structure manually, and having additional headers in an HTML generated from RST is way better than having an empty file due to a malformed input RST
```
#!/usr/bin/env runhaskell
import Text.Pandoc.JSON
import Text.Pandoc.Walk
import qualified Data.ByteString.Lazy as BL
import Text.Pandoc.Definition (Inline(..))
import Data.Aeson
import Data.List
import Data.Monoid ((<>))
import GHC.Integer (absInteger)

{-

not sure about the precise constraint, my guess is that levels should
move just one step up or one step down and not more than that. for
example if the last header had lever 3, the next one cannot have a
level less than 4

-}

amended :: Block -> [Block] -> [Block]
amended h [] = []
amended h (b@(Header _ _ _):bs) = additional h b <> amended b bs 
amended h (b:bs) = b:amended h bs

additional :: Block -> Block -> [Block]
additional (Header expected _ _) h@(Header available _ _) = 
  let padding n = Header n ("", [], []) [Str "header added by pandoc"]
  in map padding [expected..available-1] <> [h]

amend = amended (Header 1 ("", [], []) [])

f :: Pandoc -> Pandoc
f (Pandoc m b) = Pandoc m (amend b)

main = BL.getContents >>=
    BL.putStr . encode . f . either error id .
    eitherDecode'
```
while the filter can be useful in itself, i'd argue that it's worth including this logic directly in the writer. note that the guess in the code comment has been validated with a few tests

**Comment by jgm** [comment]
Probably the best solution would be to use the hierarchicalize function in the RST writer (as we do already in the DocBook writer, for example).  This would ensure that we have a coherent header structure.

**Comment by danse** [comment]
i also found out that this logic [is already supposed to be in place](https://github.com/jgm/pandoc/pull/2079/files) ... didn't expect that ... i will investigate further

**Comment by danse** [comment]
https://github.com/jgm/pandoc/commit/24f68654e919a8ff138d0a1fcfbf8e045b8ae38b is related to the normalization logic ... it seems that the logic gets applied only with `-s`. I keep this here in order to look at it better eventually

**Comment by danse** [comment]
Yes, this is already applied with `-s`, we can close this

```
 tmp $ pandoc -f native -t rst | rst2html > /dev/null 
[Header 2 ("",[],[]) [Str "2"]
,Header 1 ("",[],[]) [Str "1"]
,Header 2 ("",[],[]) [Str "2"]
,Header 3 ("",[],[]) [Str "3"]]
<stdin>:10: (SEVERE/4) Title level inconsistent:

3
~
Exiting due to level-4 (SEVERE) system message.
 tmp $ pandoc -s -f native -t rst | rst2html > /dev/null 
[Header 2 ("",[],[]) [Str "2"]
,Header 1 ("",[],[]) [Str "1"]
,Header 2 ("",[],[]) [Str "2"]
,Header 3 ("",[],[]) [Str "3"]]
 tmp $ 
```
