### ISSUE TITLE
bug: latex reader (latex files contains a bibtex reference which contains % at the end of line

### ISSUE THREAD

**Issue by ouboub** [jgm/pandoc#4374]
Hi

Using pandoc 2.1.1
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1.1, skylighting 0.6

and running 
pandoc bug-test.tex -o bug-test.txt, I receive

Error at "source" (line 12, column 46):
unexpected %
\cite{oliynyk16:_futur_flrw,oliynyk15:_newton%

Github **does not allow me to attach a latex file**! so I rename it with the extension **.txt** (which is **wrong**)

Uwe Brauer 

[bug-bib.txt](https://github.com/jgm/pandoc/files/1733535/bug-bib.txt)

**Comment by jgm** [comment]
Minimal case:
```
\cite{a%
}
```

**Comment by ouboub** [comment]
Does this mean the bug is solved in the current version of pandoc?
Only in master of the repo? Or can I obtain a version via cabal?

**Comment by jgm** [comment]
You'd have to build from source.  Fetch the repo and
do 'cabal install' from inside it.

+++ Uwe Brauer [Feb 18 18 07:26 ]:

**Comment by ouboub** [comment]
shall I delete my .cabal and .ghc directory first?

**Comment by jgm** [comment]
You shouldn't need to.

+++ Uwe Brauer [Feb 19 18 03:24 ]:

**Comment by jgm** [comment]
But if you run into problems, you can try that.
Another alternative is to use cabal new-build or cabal
sandbox for sandboxed builds.

+++ Uwe Brauer [Feb 19 18 03:24 ]:

**Comment by ouboub** [comment]
ok, building and installation worked without any problem. 
thanks
