### ISSUE TITLE
Footnotes from markdown to html inserts garbage chars

### ISSUE THREAD

**Issue by meldavis** [jgm/pandoc#4376]
Using Pandoc version 2.1.1 (also tried 2.1 and 2.0.6) on Windows 

input:
``` markdown
This has a footnote.[^a]

[^a]: hello.
```
Command: `pandoc --from=markdown_strict+footnotes --to=html mytest.md`

output:
``` html
<p>This has a footnote.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<section class="footnotes">
<hr />
<ol>
<li id="fn1"><p>hello.<a href="#fnref1" class="footnote-back">Γå⌐</a></p></li>
</ol>
</section>
```

Garbage characters `Γå⌐`  appear both when the output is directed to the console and when the -o output file is specified. In the browser the footnote appears as:

```1. hello.â†©```

The output is the same for both Dos and Unix style line endings. The extra characters do not appear when the output format is plain text.

**Comment by meldavis** [comment]
This should fix it. In the line below, change the symbol `"↩"` to `"&crarr;"`.

  https://github.com/jgm/pandoc/blob/377640402f32e8189fc88e54515c397ce48cc916/src/Text/Pandoc/Writers/HTML.hs#L1157

**Comment by jgm** [comment]
It's not a garbage character. It's a UTF-8 encoded symbol.
If you generate a fragment with pandoc (not using `--standalone/-s` option), then there is nothing to tell the browser that this is UTF-8, and so many browsers will assume it's latin1 encoding.  Solution:  use `-s`, or just select an option on your browser to display UTF-8.

Another option, if you want all-ASCII output, is to use the `--ascii` option.  Then you'll get an entity.

**Comment by rootbeersoup** [comment]
For anyone googling this problem like me, you need to add `<meta charset="UTF-8">` in the compiled HTML

**Comment by mb21** [comment]
@rootbeersoup or better use pandoc's `-s` option, which uses a template that contains `<meta charset="UTF-8">`.

**Comment by rootbeersoup** [comment]
@mb21 I should have clarified. I'm using Pandoc as an "external helper" to compile Markdown via Hugo. Hugo passes `--mathjax` as a default but does not allow any other arguments to be passed to Pandoc. Adding `<meta charset="UTF-8">` is the only acceptable workaround for my use case.

This isn't a Pandoc issue, per se, but this was the most relevant page that came up while searching the issue on Google.
