### ISSUE TITLE
Add `incremental` div in presentations for incremental lists

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#4381]
Currently presentations use a list-inside-blockquote convention for incremental lists. But that feels fairly hacky (and non-portable), since we have native divs and a nice fenced div syntax.

Suggestions::

1. use an `incremental` classed div for incremental lists.

2. keep the old convention for backwards compatibility

3. but use the new syntax in preference to it in the MANUAL.

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Feb 20 18 15:12 ]:
>   Currently presentations use a list-inside-blockquote convention for
>   incremental lists. But that feels fairly hacky (and non-portable),
>   since we have native divs and a nice fenced div syntax.
>
>   Suggestions::
>    1. use an incremental classed div for incremental lists.
>    2. keep the old convention for backwards compatibility
>    3. but use the new syntax in preference to it in the MANUAL.

Yes, this makes sense to me.

**Comment by jkr** [comment]
Cool -- I'll start look through to see what's involved.

**Comment by jkr** [comment]
Okay -- I implemented it here: https://github.com/jkr/pandoc/commit/7177eb327e32323553278845150dff82fddafae6

One bit of bikeshedding: I currently have the two class names as `incremental` and `nonincremental`. The latter is a bit of a mouthful. Perhaps a hyphenated `non-incremental`? Or `all-at-once`? Or just leave it as is?

**Comment by cagix** [comment]
> I currently have the two class names as `incremental` and `nonincremental`. 

Just out of curiosity: Does that mean that for normal (i.e. non incremental) itemize/enumeration lists in presentations a fenced div will also be needed?

**Comment by jkr** [comment]
No -- if the user passes the `-i/--incremental` flag on the command line, `nonincremental` would turn it off on a per-case basis. The default would be the document default (which would be non-incremental if no flag were passed0.

**Comment by jkr** [comment]
Or to put it another way, if you don't use the divs, your presentations will continue to work just as before.

**Comment by cagix** [comment]
Ah, understood. Thanks for clarification :)
