### ISSUE TITLE
width and height image attribute not working correctly in version 2.1+

### ISSUE THREAD

**Issue by nussi98** [jgm/pandoc#4384]
When I add a {width} or {height} to an image in markdown and convert it to latex using pandoc it doesn't adjust the size correctly. 

For example I used {width=90%} but the image spanned the complete height of the document and the aspect ratio was completely broken.

_Pandoc_ version 2.1 and 2.1.1

**Comment by AugustH** [comment]
This
 `![text ](image.png){width=90%}`
gives an additional (and wrong) height 
  `\includegraphics[width=0.9\textwidth,height=\textheight]{image.png}`

worked with 2.0.x

**Comment by jgm** [comment]
pandoc's output presupposes something which is now in the
default latex template -- but may not be in your template,
if you have a custom template you were using before:

    % Scale images if necessary, so that they will not overflow the page
    % margins by default, and it is still possible to overwrite the defaults
    % using explicit options in \includegraphics[width, height, ...]{}
    \setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}

Do you have that in your template?  If not, add it and 
things should work.

**Comment by jgm** [comment]
For reference, see commit 1193c1a505aac616d41a7b1c61c0cde07d2560d2

By adding the `\textheight`, we allow you to specify just width, or just height -- previously, both needed to be specified, unless the image was being resized to smaller than the original size.

This requires setting `keepaspectratio` as a default, which is what the above line in the template does.

**Comment by AugustH** [comment]
thanks for the quick response

just for the records (and anybody searching for this): the changes needed for the template (from commit 9e52ac6bb02afd7b4ed5d)
```
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```

**Comment by nussi98** [comment]
Unfortunately I wasn't able to fix it using this fix...
It still inserts the wrong height on version 2.1.1.
```latex
\includegraphics[width=0.9\textwidth,height=\textheight]
```

**Comment by mb21** [comment]
@nussi98 are you using a custom template? if so, have you updated it?

**Comment by nussi98** [comment]
I have inserted what AugustH proposed:
```tex
\makeatletter
    \def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
    \def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```

**Comment by mb21** [comment]
can you try with the new default template?

**Comment by jankap** [comment]
This should be part of the default latex template, right? Do I have to explicitly use that teamplate when calling pandoc? `keepaspectratio` is not added for me when converting from md to tex via `pandoc -L /tools/strip_brackets.lua --filter pandoc-crossref --biblatex 'paper.md' -o 'paper_converted.tex" `. It results in `  \includegraphics[width=0.5\textwidth,height=\textheight]{attachments/image.png}`

thx :)

**Comment by jankap** [comment]
I think this effect is caused by not using the `--standalone` option, which seems not to use a template at all: https://pandoc.org/MANUAL.html#templates

**Comment by jankap** [comment]
A simple solution is here: https://github.com/flow123d/flow123d/issues/1363#issuecomment-1618066086
