### ISSUE TITLE
Bold and Italics in output docx should be characters styles

### ISSUE THREAD

**Issue by elmimmo** [jgm/pandoc#4391]
Bold and italics in output docx are so by having direct formatting applied instead of character styles. The latter would be more useful for cleanliness and editability purposes.

Is there any reason I am not taking into account why they had rather not be?

**Comment by jkr** [comment]
We try to match our docx output with what would be produced by a (reasonable) user of ms word. Word uses direct `bold` and `italic` tags. (You can ee #3041 for discussion on this exact topic)

We have a feature for users that wish to apply their own formatting: [word custom styles][1]. It is quite easy, with [lua filters][2], to convert bold and italics to custom styles of your choosing: 

[1]: https://pandoc.org/MANUAL.html#custom-styles-in-docx-output
[2]: https://pandoc.org/lua-filters.html

```lua
function String (elem)
   local attrs = pandoc.Attr("", {}, {["custom-style"]="strong"})
   return pandoc.Span(elem.content, attrs)
end


function Emph (elem)
   local attrs = pandoc.Attr("", {}, {["custom-style"]="emph"})
   return pandoc.Span(elem.content, attrs)
end
```

Run this with `pandoc --lua-filter /path/to/thisfilter.lua input.md -o output.docx`

**Comment by vv73** [comment]
It seems to be this lua script creates another user style, not "strong", but "strong1".
This is what I see in generated Word document.

**Comment by agusmba** [comment]
@vv73 I seem to recall running into this.
Have you tried using a reference-doc where you explicitly use the "Strong" style? At least that's how I solved it (if it was not explicitly present in the reference doc, Word would create an alternate Strong1)

I'm explicitly using the custom style "Strong" in my markdown source, I haven't tried the lua script, but it should work the same way.
