### ISSUE TITLE
Add an option, --no-script

### ISSUE THREAD

**Issue by jidanni** [jgm/pandoc#4398]
Add an option, --no-script, that would ensure no
```
    <script src="//cdnjs.cloudflare...
```
etc. ends up in what would otherwise be pure HTML(5). Yes, header templates or not.

Version 1.19.2.4~dfsg-1+b3 (Debian)

**Comment by jidanni** [comment]
Or add --pure-html, to eliminate CSS and script.

**Comment by mb21** [comment]
What exactly is your use case/problem? You can always use a custom template or output without `-s` to get a HTML fragment.

btw, please use preferably the pandoc-discuss mailing list to propose changes like this.

**Comment by jidanni** [comment]
I just think there should be a mode,
where we are getting minimal pure HTML out.

For instance, if a hyperlink is to be created,
we know that it must at least have <a href=...>...</a>.
Any addition of class=... etc. is no longer pure minimal HTML.

**Comment by mb21** [comment]
What is your definition of "pure minimal HTML"? It's pretty subjective, don't you think?

As mentioned, you can use a custom template to your liking, or run the HTML produced through a post-processor. Also, the output is already pretty minimal, e.g. usually there is no class created in links so not sure exactly what you're doing...

**Comment by jidanni** [comment]
I would make everything in the <head> have a switch. E.g.,

$ man tidy

       tidy-mark

              Type:    Boolean
              Default: yes
              Example: y/n, yes/no, t/f, true/false, 1/0

              This option specifies if Tidy should add a meta element to the document head to indicate that the document
              has been tidied.

That way one could remove the IE stuff, the javascript stuff, the CSS
via options, without having to write templates.

Minimal would mean HTML minus CSS minus JS.

**Comment by mb21** [comment]
> I would make everything in the <head> have a switch.

That can already be achieved with a custom template. Thus I don't think it's a good idea to add yet another option to pandoc.

**Comment by jgm** [comment]
I should also note that you can write a custom lua writer
(see data/sample.lua for an example) and customize the
HTML output exactly to your needs.
