### ISSUE TITLE
Remove unreachable sites from documentaion

### ISSUE THREAD

**Issue by jidanni** [jgm/pandoc#4401]
https://github.com/jgm/pandoc says
> Universal markup converter http://johnmacfarlane.net/pandoc

And the man page mentions https://pandoc.org, both of which give browser ERR_CONNECTION_TIMED_OUT . So maybe remove them.

**Comment by jkr** [comment]
They were temporarily down (for about an hour). They're up again.

**Comment by jgm** [comment]
+++ 積丹尼 Dan Jacobson [Feb 23 18 18:33 ]:
>   [1]https://github.com/jgm/pandoc says
>
>     Universal markup converter [2]http://johnmacfarlane.net/pandoc
>     And the man page mentions [3]https://pandoc.org, both of which give
>     browser ERR_CONNECTION_TIMED_OUT . So maybe remove them.

I imagine this was a temporary server glitch.  Or perhaps
a problem with a local firewall?  I have no trouble reaching
either of those sites.
