### ISSUE TITLE
Regression: figure without caption does not have the "Figure" style in docx

### ISSUE THREAD

**Issue by kugelblitz** [jgm/pandoc#4402]
Hello,

With pandoc 2.1.1 I convert a simplest Mardown with an image to docx

```
$ pandoc -o a.docx 
Hello

![](image.png)

Goodbye
^D
```

and I get a docx where the image has the "Body text" style, despite the image is occupying the whole paragraph, so it should have the "Figure" style.

In Pandoc 1.19.2.1, it has the "Figure" style as expected (I do not know the exact version where it broke).

When the image has any caption inside the `[]`, it is properly rendered with "Captioned Figure" style in both 2.1.1 and 1.19.1.1.

Best regards,

Dmitry

**Comment by jgm** [comment]
This is not a regression, but a documented change in behavior.
From the pandoc 2.0 changelog:

    + Require nonempty alt text for `implicit_figures` (#2844).
      A figure with an empty caption doesn't make sense.

You can always include a nonbreaking space or something like
that, if you really want a blank caption.

**Comment by kugelblitz** [comment]
First, I was wrong to call this an outright regression, and I apologize.

I must make some further comments so maybe we find a common ground here.

I gather that prior to Pandoc 2.0, there were three kinds of images:
1. standalone with caption ("Captioned Figure" style, or "Figure with Caption" before it)
2. standalone without caption ("Figure") style.
3. inline ("Body text" style).

Now, since Pandoc 2.0, there are only two kinds (1 and 3), in docx output anyway, am I correct?
(If there is still a way to get "Figure" style in output, I will be happy to know it.)

Now, you write in #2844:

> On reflection, I guess that without \caption, it probably doesn't make sense to have \label, since there will be no figure number to refer to.

I fully agree.

What I would love to have in docx output is just that -- an image without caption, number, and label to refer to, but otherwise looking as a separate, not inline, image, centered, with vertical margins etc.

Your proposed solution with a nonbreaking space caption does not quite fit the bill due to two reasons:
1. It creates an extra blank line below the image, which is not always wanted.
2. It loses the distinction between captioned and uncaptioned figures for further docx postprocessing.

Best regards,

Dmitry

**Comment by kugelblitz** [comment]
Oh, answering my own question:

> (If there is still a way to get "Figure" style in output, I will be happy to know it.)

    ::: {custom-style="Figure"}
    ![](image.png)
    :::

So I guess I can use that, thanks!

**Comment by jgm** [comment]
Another thing you can do is

    ![](myimage.jpg "fig:")

But this is hacky and relies on the workaround we use
in the absence of a proper Figure container.
