### ISSUE TITLE
SI units not parsed in LaTeX raw blocks

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#4406]
With #3588 parsing of SI units were introduced for latex input files. Unfortunately, it is not supported for latex raw blocks yet.

Hence, the following line is converted to `About  are converted.` (with two spaces) in all output formats other than LaTeX/PDF.

```markdown
About `\SI{99.8}{\percent}`{=latex} are converted.
```

**Comment by latk** [comment]
That is by-design: raw blocks should not be parsed, but be passed through *raw* to the respective output format. If you want to write documents that can be rendered in multiple output formats, you must restrict yourself to common Pandoc Markdown, e.g. by using `$math$` in this case.

In the future, please ask such questions (“Why aren't raw LaTeX blocks rendered in non-LaTeX output formats?”) on the pandoc-discuss mailing list. As per the [contributing guidelines](https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md), this issue tracker is intended for bugs.

**Comment by mb21** [comment]
Indeed, or use something like:

    About `\SI{99.8}{\percent}`{=latex} `99.8%`{=html} are converted.
