### ISSUE TITLE
pandoc 2.1.1 freezes using package createspace in latex input with no logging - works in release 1.19.2.1

### ISSUE THREAD

**Issue by dangrec** [jgm/pandoc#4408]
A latex file as follows

\documentclass{book}
\usepackage{createspace}
\begin{document}
something
\end{document}

Run through pandoc 2.1.1 with the following command

pandoc -f latex test.tex -t native -o test.atx --verbose --log=output.log

Causes pandoc to use 100% CPU forever.
Nothing is printed to the console, the log file is never written.
No output file is produced.

The latex package createspace can be found here: https://github.com/aginiewicz/createspace

Pandoc release 2.0.5 has the same issue.

Pandoc release 1.19.2.1 everything works perfectly.

**Comment by jgm** [comment]
I assume you have `createspace.sty` in the working directory.  With that, I can reproduce the problem.

**Comment by jgm** [comment]
As a practical matter:  pandoc has gotten better at parsing LaTeX, but it is still not anywhere near being able to handle a complex plain tex style like `createspace.sty`.  (The difference between 2.x and 1.19.x is that pandoc 2.x tries to parse more -- and evidently it is getting mixed up.)

I consider it a bug that pandoc hangs rather than failing gracefully here. However, for your purposes the best solution would be to remove `createspace.sty` from your working directory, so pandoc won't attempt to parse it.  Then pandoc will do more or less what it did in 1.19.x with the rest of your file.

**Comment by dangrec** [comment]
Thanks for the reply, I really appreciate it.

After removing createspace.sty it does process my entire .tex file, though it does nothing like it did in 1.19.x 
I can't figure out why, but in verbose mode it tells me it's skipping most of my included chapters:

[INFO] Skipped '\include{./chapters/awakening}' at line 194 column 31

There are ~30 chapters just like that. 2.1.1 skips about 75% of them, while 1.19.x happy includes them all.
Even when I make the chapters just one sentence of boring text, it still skips the same ones

Is there are way to know WHY 2.1.1 is "SKIPPING" stuff?

Thanks again

**Comment by dangrec** [comment]
Thanks very much. Removing createspace.sty did indeed fix the hang and allow pandoc to continue.

**Comment by jgm** [comment]
Problem seems to arise in the vicinity of line 808-812 of createspace.sty.
```
head -812 createspace.sty | pandoc -f latex --trace
```

**Comment by jgm** [comment]
```
\let\@pdftitle\@empty
\let\@pdfauthor\@empty
\let\cs@author\author
\let\cs@title\title
\renewcommand\author[1]{\pdfauthor{#1}\cs@author{#1}}
\renewcommand\title[1]{\pdftitle{#1}\cs@title{#1}}
\newcommand\pdfauthor[1]{\pdfstringdef\@pdfauthor{#1}}
\newcommand\pdftitle[1]{\pdfstringdef\@pdftitle{#1}}
\PackageError{createspace}{you must specify book title}{specify title using \protect\title\space or \protect\pdftitle\space command}
```

**Comment by jgm** [comment]
We're getting a loop in processing the macros, because `\cs@title` resolves to `\title`, but `\title` is defined in terms of `\cs@title`.  Clearly we don't have the logic of `\let` quite right.

**Comment by jgm** [comment]
Some debug output:
```
Expanding "title" to \pdftitle{#1}\cs@title{#1}
Expanding "cs@title" to \title
Expanding "pdftitle" to \pdfstringdef\@pdftitle{#1}
Expanding "@pdftitle" to \@empty
Expanding "title" to \pdftitle{#1}\cs@title{#1}
Expanding "cs@title" to \title
Expanding "pdftitle" to \pdfstringdef\@pdftitle{#1}
Expanding "@pdftitle" to \@empty
Expanding "@pdftitle" to \@empty
Expanding "@pdftitle" to \@empty
Expanding "title" to \pdftitle{#1}\cs@title{#1}
Expanding "cs@title" to \title
Expanding "pdftitle" to \pdfstringdef\@pdftitle{#1}
Expanding "@pdftitle" to \@empty
Expanding "@pdftitle" to \@empty
Expanding "@pdftitle" to \@empty
...and so on...
```

**Comment by jgm** [comment]
After several changes:
```
\let\@pdftitle\@empty
\let\cs@title\title
\renewcommand\title[1]{\pdftitle{#1}\cs@title{#1}}
\newcommand\pdftitle[1]{\pdfstringdef\@pdftitle{#1}}
\title{Hi}
```
loops, but if you add one space between `\pdftitle{#1}` and `\cs@title{#1}` on the 3rd line, it doesn't.
!!!
