### ISSUE TITLE
loose RST lists are parsed as tight lists

### ISSUE THREAD

**Issue by danse** [jgm/pandoc#4410]
blank lines between items in an RST list [are optional](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bullet-lists), and currently not added by pandoc. in cases when they are desired, rather than adding them manually, we would like to have a writer option that changes the default behaviour

**Comment by jgm** [comment]
In fact, pandoc will include the blank lines if the list is
a "loose list" (i.e. there were blank lines between items
in the original markdown source, or `<p>` tags in HTML).

So depending on your input format you ought to be able
to select either form by writing your list accordingly.

If you want to automatically make tight lists loose,
you can use a filter for that.

I think an option is overkill here.

**Comment by danse** [comment]
i see, therefore i simply have to adopt [`isTightList`](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Shared.hs#L542-L546) in the RST writer, and use filters where desired. i renamed the issue, thanks 👍

**Comment by danse** [comment]
actually i found out that the error is in the parser. i added a test case [here](https://github.com/italia/pandoc/commit/86f58db26406bd988f541b671a4f1ad2718cfb8e)

**Comment by jgm** [comment]
Your test case is for the RST reader. This issue, as I understood it, was about the writer.

The RST reader's behavior is correct, I think. It is designed to match how docutils parses.  Docutils gives the same output whether or not the blank lines are there.

**Comment by danse** [comment]
Well i consider that the error is in the reader because i follow the reasoning about loose and tight lists. If we take the definition of a tight list from the implementation of `isTightList`, tight lists are lists whose elements are all `Plain`, as opposed to lists containing `Para` i guess.

This works for the users' needs. In our specific case we were passing RST files through Pandoc, and we found that loose lists were turned into tight ones. That's because the parser will consider the elements to be `Plain` even when they are separated by blank lines, and that's what my last test case is about. If the reader would consider those elements as `Para` the writer would write them back as loose lists as far as i could understand by reading the writer code.

In other cases when the user might want to simply produce loose lists regardless on how they were in the input document, that can be achieved via a filter.

We can also fix this with a filter, but more users could stumble upon our same problem. Besides being a translator from one format to the other, pandoc is a powerful macro system and when used this way i guess that it's desirable that a file passing through it has as little side changes as possible

**Comment by jgm** [comment]
+++ Francesco Occhipinti [Mar 07 18 19:14 ]:
>   Well i consider that the error is in the reader because i follow the
>   reasoning about loose and tight lists. If we take the definition of a
>   tight list from the implementation of isTightList, tight lists are
>   lists whose elements are all Plain, as opposed to lists containing Para
>   i guess.

Tight/loose is really a Markdown distinction.  For RST, we
have to follow the meaning things have in RST.  docutils is
the guide here.

>   This works for the users' needs. In our specific case we were passing
>   RST files through Pandoc, and we found that loose lists were turned
>   into tight ones. That's because the parser will consider the elements
>   to be Plain even when they are separated by blank lines, and that's
>   what my last test case is about. If the reader would consider those
>   elements as Para the writer would write them back as loose lists as far
>   as i could understand by reading the writer code.

If we changed this as you suggest, then pandoc would produce
a loose list where rst2html.py produces a tight list.  So we
wouldn't be parsing RST accurately.

>   We can also fix this with a filter, but more users could stumble upon
>   our same problem. Besides being a translator from one format to the
>   other, pandoc is a powerful macro system and when used this way i guess
>   that it's desirable that a file passing through it has as little side
>   changes as possible

Well, since the presence of blank lines between items is
semantically meaningless in RST, and the pandoc AST encodes
the semantics and not syntactic details of presentation,
it's inevitable that round-tripping will sometimes produce
changes here.

**Comment by danse** [comment]
Makes sense, it's a solid standpoint that clarifies what we want the RST reader to be, while other readers follow different criteria. If i'm not mistaken, an indentation is considered a quote in the DOCX reader, because this is how most users format their quotes. I understand that a WISIWYG format is different in purpose from a markup format, where adhering to markup semantics can be chosen as the goal. I'll try to write a filter just to be sure that everything works as expected and then close this issue

**Comment by danse** [comment]
a simple filter like the following can be used in order to make sure that lists are loosened before rendering

```
#!/usr/bin/env runhaskell
import Text.Pandoc.JSON
import Text.Pandoc.Definition
import Data.List

parafy (Plain i:bs) = Para i:bs
parafy b = b

onLists :: ([Block] -> [Block]) -> Block -> Block
onLists f (BulletList i) = BulletList (map f i)
onLists f (OrderedList a i) = OrderedList a (map f i)
onLists f b = b

loosen :: Block -> Block
loosen = onLists parafy

main = toJSONFilter loosen
```
