### ISSUE TITLE
Pandoc 2.1.1 skips including multiple latex files unless there is a blank line directly before the \include{} statement

### ISSUE THREAD

**Issue by dangrec** [jgm/pandoc#4411]
A latex file as follows

\documentclass{book}
\begin{document}
\include{chap1}
\include{chap2}
\include{chap3}
\end{document}

is run through pandoc as such

pandoc -f latex test.tex -t native -o test.atx --verbose

output to console is

[INFO] Skipped '\include{chap2}' at line 4 column 16
[INFO] Skipped '\include{chap3}' at line 5 column 16

and resulting .atx file does not contain contents of files chap2 and chap3

If, however the latex \include directives have blank lines before them as follows

\documentclass{book}
\begin{document}
\include{chap1}

\include{chap2}

\include{chap3}
\end{document}

the everything works as expected i.e. the console stays quiet and the contents of those other files is included in the output .atx

I tested this many different ways, and it really seems to depend on a blank line immediately BEFORE an \include{}, EXCEPT the very first \include{} in the document. The first one always appears to work correctly, regardless.

Even when the line immediately before the other \include{} statements are simply text, the \include{} on the next line will be "skipped" as reported by the --verbose and demonstrated in the resulting .atx.

Thanks!

**Comment by mb21** [comment]
thanks for the detailed report, what pandoc version?

**Comment by dangrec** [comment]
Pandoc release 2.1.1

**Comment by jgm** [comment]
With pandoc 2.1.2, I could not reproduce this.
Your sample works perfectly and the include files are included, with on blank line before `\include`.
