### ISSUE TITLE
Regression on PDF output with `wkhtmltopdf`

### ISSUE THREAD

**Issue by krontzo** [jgm/pandoc#4413]
Environment:

- Windows: Version 10.0.16299.248
- wkhtmltopdf: 0.12.4 (with patched qt)
- Erroneous process: pandoc 2.1 and 2.1.1
- Succesful process: pandoc 1.19.2.1

Input:
- Pandoc markdown with local resources (CSS, images)
- Resources in the `.` path (same folder)

```pandoc
---
title: ToPdf
papersize: a4
margin-left: 20mm
margin-right: 25mm
margin-top: 10mm
margin-bottom: 20mm
css: style.css
#pandoc -t html5 -s -o invoice.pdf invoice.pandoc
... 

![](logo.png){ width=13.587mm height=13.559mm}
![](signature.png){ width=33.8mm }
```

Output:

Pandoc 1.19.2.1 works well

```
C:\Users\xxxxx>Downloads\pandoc-1.19.2.1-windows\pandoc -t html5 invoice.pandoc -o invoice19.pdf --verbose
[makePDF] Command line:
wkhtmltopdf "--page-size" "a4" "--title" "" "--margin-bottom" "20mm" "--margin-top" "10mm" "--margin-right" "25mm" "--margin-left" "20mm" ".\\html2pdf4118467.html" ".\\html2pdf633426500.pdf"
```

Pandoc 2.1 and 2.1.1 do not

```
C:\Users\xxxxx>pandoc -t html5 invoice.pandoc -s -o invoice.pdf --verbose
[makePDF] Command line:
wkhtmltopdf "--page-size" "a4" "--title" "" "--margin-bottom" "20mm" "--margin-top" "10mm" "--margin-right" "25mm" "--margin-left" "20mm" "-" ".\\html2pdf7604-0.pdf"

Warning: Failed to load file...
Warning: Failed to load file...
Warning: Failed to load file...
```

Pandoc 2 versions create a PDF with no CSS style and no images; because it searches for them in the %TEMP% directory.

`wkhtmltopdf` is not at fault since it works well with `pandoc` 1.19.2.1.

It appears that the modifications in `PDF.hs` are the reason to this.

The `--resource-path=SEARCHPATH` does not work either since it is meant for the `pandoc` tool and not for the `wkhtmltopdf`.

The `--self-contained` option does **not** work either. But even if it worked it would not be optimal since it requires more processing time and wastes the life of a SSD (in the case of documents with hundreds of images).

**Comment by mb21** [comment]
You're saying that the HTML generated by pandoc 1.19.x and 2.x is basically identical (especially the paths), but when you call it with wkhtmltopdf the assets are not included?

**Comment by krontzo** [comment]
That is correct.

I renamed the above `pandoc` document, and processed with both versions, and run `diff` on the output.

```
C:\Users\xxxxx>pandoc -t html5 -s -o issue4413-pdc2.html issue4413.pandoc

C:\Users\xxxxx>Local\apps\pandoc-1.19.2.1-windows\pandoc -t html5 -s -o issue4413-pdc1.html issue4413.pandoc

C:\Users\xxxxx>diff issue4413-pdc1.html issue4413-pdc2.html
2c2
< <html>
---
> <html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
4,6c4,6
<   <meta charset="utf-8">
<   <meta name="generator" content="pandoc">
<   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
---
>   <meta charset="utf-8" />
>   <meta name="generator" content="pandoc" />
>   <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
8c8,13
<   <style type="text/css">code{white-space: pre;}</style>
---
>   <style type="text/css">
>       code{white-space: pre-wrap;}
>       span.smallcaps{font-variant: small-caps;}
>       span.underline{text-decoration: underline;}
>       div.column{display: inline-block; vertical-align: top; width: 50%;}
>   </style>
18c23
< <p><img src="logo.png" width="51" height="51" /> <img src="signature.png" width="127" /></p>
---
> <p><img src="logo.png" style="width:13.587mm;height:13.559mm" /> <img src="signature.png" style="width:33.8mm" /></p>
```
As I mention before, the calling of `wkhtmltopdf` from `pandoc` has changed. Check:

```
wkhtmltopdf "--page-size" "a4" "--title" "ToPdf" "--margin-bottom" "20mm" "--margin-top" "10mm" "--margin-right" "25mm" "--margin-left" "20mm" ".\\html2pdf4118467.html" ".\\html2pdf633426500.pdf"
```
vs

```
wkhtmltopdf "--page-size" "a4" "--title" "ToPdf" "--margin-bottom" "20mm" "--margin-top" "10mm" "--margin-right" "25mm" "--margin-left" "20mm" "-" ".\\html2pdf7732-0.pdf"
```

I guess the offending part is ` "-" ` instead of a temporal html file.

 As a result, it now expects the resources from the **`%TEMP%`** folder, but the `[makePDF] Command line` do not indicate from which location `wkhtmltopdf` is being called :

```
C:\Users\xxxxx>pandoc -t html5 -s -o issue4413-pdc2.pdf issue4413.pandoc --verbose
[INFO] No value for 'lang' was specified in the metadata.
  It is recommended that lang be specified for this format.
[makePDF] Command line:
wkhtmltopdf "--page-size" "a4" "--title" "ToPdf" "--margin-bottom" "20mm" "--margin-top" "10mm" "--margin-right" "25mm" "--margin-left" "20mm" "-" ".\\html2pdf7732-0.pdf"

[makePDF] Environment:
("","::=::\\")
("","C:=C:\\Users\\xxxxx")

**Edited for privacy**

("TEMP","C:\\Users\\xxxxx\\AppData\\Local\\Temp")
("TMP","C:\\Users\\xxxxx\\AppData\\Local\\Temp")

[makePDF] Contents of intermediate HTML:
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>ToPdf</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <link rel="stylesheet" href="style.css">
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<header>
<h1 class="title">ToPdf</h1>
</header>
<p><img src="logo.png" style="width:13.587mm;height:13.559mm" /> <img src="signature.png" style="width:33.8mm" /></p>
</body>
</html>

Loading pages (1/6)
Warning: Failed to load file:///C:/Users/xxxxx/AppData/Local/Temp/style.css (ignore)
Warning: Failed to load file:///C:/Users/xxxxx/AppData/Local/Temp/logo.png (ignore)
Warning: Failed to load file:///C:/Users/xxxxx/AppData/Local/Temp/signature.png (ignore)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

**Comment by mb21** [comment]
I see, I can reproduce this also on Linux (`Warning: Failed to load file:///tmp/logo.png`). This was broken [here](https://github.com/jgm/pandoc/commit/c7e3c1ec1797d633c181e5701c94f4169b0e5471#diff-87268c8f8c723945b7a577f101eaff24L356), when I changed from writing to a temp-file in the current working directory to piping the HTML directly to wkhtmltopdf and the other engines.

@jgm, I guess we should just revert to the old behaviour with the temp file? Alternatively, we could add a `<base>` tag to the HTML, which [apparently works for wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3627) but would have to test for the other html-to-pdf-engines, and not sure its worth the added complexity.

**Comment by jgm** [comment]
It's generally nicer to avoid creating intermediate temp files if we can, and in general I've tried not to create temp files in the working directory.  (After all, you might run pandoc from a directory where you don't have write permission.)  So let's investigate whether the base tag trick works.  We could use `tagsoup` to insert it in to the HTML before processing.

**Comment by mb21** [comment]
> We could use tagsoup to insert it in to the HTML before processing.

We call `writer opts doc` in `PDF.hs` which returns a `Text` that we'd have to parse again.

Maybe instead append `header-includes: <base href="/my/path">` to the metadata of `doc`. This would only work for templates that have `$header-includes$` though...

**Comment by jgm** [comment]
tagsoup can parse that text and add a tag fairly efficiently, I think.

**Comment by krontzo** [comment]
Environment:

macos: Version 10.12.6
wkhtmltopdf: 0.12.4 (with patched qt)
Erroneous process: pandoc 2.1.3

Pandoc output with verbose:

```Loading pages (1/6)
Warning: Failed to load file:///var/folders/xxxxxxxxxx/style.css (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done     
```

wkhtmltopdf cannot find the `style.css` file because the `<base>` tag was given after the stylesheet:

```html
[makePDF] Contents of intermediate HTML:
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang xml:lang>
<head>
  <meta charset="utf-8"></meta>
  <meta name="generator" content="pandoc"></meta>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"></meta>
  <title>invoice</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <link rel="stylesheet" href="style.css">
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
<base href="/Users/xxxxxx/invoice_pandoc/">
</head>
<body>
<p><img src="logo.png" style="width:13.587mm;height:13.559mm"></img></p>
```

Perhaps the `<base>` tag should be provided at the begining of the `<head>` tag?

Thank you for fixing the missing assets.

**Comment by mb21** [comment]
@krontzo ah right, that's something I didn't think of.

Also, links inside the page [are broken by the base tag](https://stackoverflow.com/questions/1889076), so I'll have to insert the following JS:

```
document.addEventListener('DOMContentLoaded', function(){
  var es = document.getElementsByTagName('a')
  for(var i=0; i<es.length; i++){
    es[i].addEventListener('click', function(e) {
      e.preventDefault()
      document.location.hash = e.target.getAttribute('href')
    })
  }
})
```

**Comment by mb21** [comment]
But a more fundamental problem is that, links inside the page (document fragment links like `[go](#here)`) [are broken by the base tag](https://stackoverflow.com/questions/1889076). Normally you would [insert some JavaScript](https://stackoverflow.com/questions/8108836/) to execute on the link click (`onclick` event), but that's not going to work when producing a PDF because most PDF-viewers don't execute JavaScript.

I guess injecting a `<base>` tag is a dead-end and we'll have to either write to a temp file again, or modify all the links (`style`, `script`, `img` tags, etc.) to be absolute. Seems e.g. [drupal is doing the same](https://www.drupal.org/project/print/issues/1313754) for PDF generation with wkhtmltopdf.

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

>> I guess injecting a `<base>` tag is a dead-end and we'll have to either write to a temp file again, or modify all the links (`style`, `script`, `img` tags, etc.) to be absolute. 
>
> @jgm which one is it going to be?

I don't have a strong opinion about this.
Modifying all the links to be absolute is not too hard, using `walk`.
Would using a temp file cause problems?

**Comment by mb21** [comment]
> Would using a temp file cause problems?

no, that’s what we had previously and it worked well and was simple. But it’s not that performant for huge files... but no one has ever complained about that, so I think it’s a good idea.

**Comment by mb21** [comment]
I think creating a temp file in the working dir is a reasonable compromise to keep it simple.

At that point in the code we only have the HTML string so we cannot use `walk`.

**Comment by jgm** [comment]
Good, let's just go back to the old way, then!
