### ISSUE TITLE
contents of docx w:sdt tag not output in html

### ISSUE THREAD

**Issue by cwoolner** [jgm/pandoc#4415]
Hello,

Simple docx: [pandoc-sdt-tag-edited.docx](https://github.com/jgm/pandoc/files/1765702/pandoc-sdt-tag-edited.docx)

Found issue running pandoc 2.1.  Was hopeful that 2.1.1 fixed the issue (based on #4190), but it does not appear to fix this particular use of sdt/sdtContent tags.

`pandoc -f docx -t html+smart -s --track-changes=all pandoc-sdt-tag-edited.docx -o pandoc-sdt-tag-edited.html`

Expected html body:

```
<body>
<p>Test Paragraph1</p>
<p>Test Paragraph2</p>
<p>Test Paragraph3</p>
</body>
```

Actual html body:

```
<body>
<p>Test Paragraph1</p>
<p>Test Paragraph3</p>
</body>
```

Thanks.

**Comment by jkr** [comment]
Okay -- the issue here seems to be that there are nested sdt tags, and we had only checked for the top-level one. That's easy enough to fix (I'll try to do it this evening).

I am curious, though: how did you produce this file? Word complains that it's corrupt, and the xml file is indent-formatted, which isn't the case in office-generated files.

**Comment by cwoolner** [comment]
Ahh sorry about that.  Copy and pasted chunks of document.xml out of our customer doc to create it (to avoid exposing IP), but I blew it.  Running Linux, so just made sure it opened without error in Libreoffice.

I'll generate a new one soon and make sure someone with Word verifies it opens correctly.

**Comment by jkr** [comment]
Word was able to repair it, so I think I have a fix based on that file. But if you can upload something generated by Word, that would be helpful.

**Comment by cwoolner** [comment]
Taking our customers doc and trying to remove any trace of who they are has proven to be a huge pain.  I tried creating a new doc from scratch using Word, but was unable to create one that showed the same embedding.  Sorry I couldn't get a better example.

I tried out the patch and it fixed our customer's doc.  Thank you very much for the quick fix!
