### ISSUE TITLE
How to convert partial html content to markdown using pandoc tool

### ISSUE THREAD

**Issue by friends110110** [jgm/pandoc#4417]
generate test.docx from http://www.fsf.org .

pandoc -f html -t docx http://www.fsf.org -o test.docx
Now ,I wanna fetch partial content from http://www.fsf.org , such as fetch the specify html label content ?

pandoc --version
pandoc 2.1.1
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1, skylighting 0.6

**Comment by tarleb** [comment]
This is seems to be a question, not a bug. Please raise it on the pandoc-discuss mailing list. The issue tracker is reserved for bugs and feature requests.
