### ISSUE TITLE
HTML line break / new line (<br>) converted to Markdown breaks following header (<h1>)

### ISSUE THREAD

**Issue by dhebbeker** [jgm/pandoc#4418]
Pandoc version: 1.17.2

When converting HTML to Markdown a line break (`<br>` or `<br />`) will break a directly subsequent header (`<h1>`). A paragraph ending with a line break `<br>` in HTML will be converted to paragraph with a [backslash-escaped newline](http://pandoc.org/MANUAL.html#backslash-escapes) in Markdown. When converting this result back to HTML a subsequent header is not parsed as header. I assume because the empty line between the paragraph and the header is escaped by the backslash.

My guess to fix the conversion of a line break at the end of a paragraph to Markdown would be to either
* make sure a paragraph with a backslash-escaped newline at the end is followed by _two blank lines_ or
* omit backslash-escaped newline at the end of a paragraph.

From @rose00's [comment](https://github.com/jgm/pandoc/issues/3730#issuecomment-307651433) on #3730 I guess that it may have the same source of error. But #3730 seems to be fixed.

:thought_balloon: Using `markdown_strict` or `markdown-escaped_line_breaks` as output format does avoid the foregoing behavior. Using that format as a _workaround_ has the downside that without the **extension `escaped_line_breaks`** [multilines are not supported in table cells](http://pandoc.org/MANUAL.html#paragraphs). Thus a fix to the default `markdown+escaped_line_breaks` would be ideal.

# minimum working example

This is the HTML code original-ISO.hml:
```
<h1>Header 1</h1>
Text 1
<h1>Header 2</h1>
<p>Text 2</p>
<h1>Header 3</h1>
<p>Text 3<br></p>
<h1>Header 4</h1>
Text 4<br>
<h1>Header 5</h1>

Text 5<br>

<h1>Header 6</h1>
Text 6
```
Which I converted to Markdown `pandoc -o intermediate-ISO.md original-ISO.html`:
```
Header 1
========

Text 1

Header 2
========

Text 2

Header 3
========

Text 3\

Header 4
========

Text 4\

Header 5
========

Text 5\

Header 6
========

Text 6
```
And then converted back to HTML `pandoc -o final-ISO.html intermediate-ISO.md`:
```
<h1 id="header-1">Header 1</h1>
<p>Text 1</p>
<h1 id="header-2">Header 2</h1>
<p>Text 2</p>
<h1 id="header-3">Header 3</h1>
<p>Text 3<br />
Header 4 ========</p>
<p>Text 4<br />
Header 5 ========</p>
<p>Text 5<br />
Header 6 ========</p>
<p>Text 6</p>
```
As one can see the original headers 4, 5, and 6 are broken.

**Comment by mb21** [comment]
You're using an ancient pandoc version, this is fixed in the current one.

You can also customize this with the `escaped_line_breaks` extension, e.g. 

    pandoc -f markdown-escaped_line_breaks intermediate-ISO.md

**Comment by dhebbeker** [comment]
Grüezi @mb21 and thank you for the explanation. Apparently the [version of pandoc](https://packages.debian.org/stretch/pandoc) is ancient in the current (stretch) Debian stable distribution. I guess this is the cost of using this distribution. :unamused: 

I am sorry for having bothered you with old issues.

**Comment by mb21** [comment]
Grüezi ;) You can download the latest debian package from https://github.com/jgm/pandoc/releases
