### ISSUE TITLE
reStructuredText: image & figure “:align:” handling is inconsistent

### ISSUE THREAD

**Issue by Zopieux** [jgm/pandoc#4420]
```console
$ pandoc -f rst -t native | tee /dev/stderr | pandoc -f native -t rst
```
```rst
.. image:: foo.png
   :align: right
   :width: 100px
```
```
[Image ("",["align-right"],[("width","100px")]) …]
```
```rst
.. |image| image:: foo.png
   :class: align-right
   :width: 100px
```

I would expect the `align-right` class to produce back `:align: right`, as other properties (width, height, …) are properly serialized from the AST.

Same issue with `.. figure::`, which is just a wrapper around `image`.

Version: 2.1.1

**Comment by Zopieux** [comment]
Related: #2724 #2662 #3767

**Comment by jilljenn** [comment]
@Zopieux :heart:

**Comment by Zopieux** [comment]
Better late than never! Thanks.
