### ISSUE TITLE
When creating an ePub from a Docx, H1’s lose their bolding

### ISSUE THREAD

**Issue by daveredfern** [jgm/pandoc#4421]
Hi,

I’m using bolding to highlight certain words inside H1’s. When converting to ePub, this bolding is lost. H2’s seem to retain their bolding though. I’m converting from a Docx to a ePub.

Thanks,

Dave.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information.

From [Contributing to pandoc](http://pandoc.org/CONTRIBUTING.html):

> Make sure you can reproduce the bug with the latest released version of pandoc
> (or, even better, the development version).
> 
> Your report should give detailed, *reproducible* instructions, including
> 
>   * the pandoc version (check using `pandoc -v`)
>   * the exact command line used
>   * the exact input used
>   * the output received
>   * the output you expected instead
> 
> A small test case (just a few lines) is ideal.  If your input is large,
> try to whittle it down to a *minimum working example*.

[User's Guide]: http://pandoc.org/MANUAL.html
[FAQs]:  http://pandoc.org/faqs.html

**Comment by daveredfern** [comment]
Sorry, here is the information.

the pandoc version:
**pandoc 2.1.1**

the exact command line used:
pandoc book.docx -o book.epub --epub-cover-image=cover.jpg --epub-metadata=metadata.xml --css=stylesheet.css --epub-chapter-level=2 --toc --toc-depth=2

the exact input used
Any Word document with a H1 and some bolding within. I’ve tried it within my document and new ones.

the output received
All bolding inside H1 was stripped.
`<h1>Hello, World</h1>`

the output you expected instead
All bolding to be retained so you’d get:
`<h1>Hello, <strong>World</strong></h1>`

H2’s work as expected and retain their bolding during the conversion.

**Comment by mb21** [comment]
With my pandoc 2.1.1 the bolding inside both titles is lost on the docx reader:

    pandoc book.docx -t native | grep Strong

is empty.

**Comment by daveredfern** [comment]
Sorry @mb21. I found the issue, it’s with Word. If the default styling for a heading level is bold, you can’t bold words—or unbold them—to get the strong tag to appear. Setting it as normal weight by default and then bolding works great.
