### ISSUE TITLE
Installing pandoc from Git sources with `stack` fails

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#4423]
I'm trying to build Pandoc from current Git sources on Debian Stretch 9.3.

```
$> stack --version | head -n 1
Version 1.5.1 x86_64

$> stack setup
Could not parse '/home/kp/svn-stuff/git.pandoc/stack.yaml':
Aeson exception:
Error in $['ghc-options']: failed to parse field 'ghc-options': Invalid package name: "$locals"
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

The last lines in stack.yml are:

```
[....]
ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-10.3
```

So I change the respective lines in stack.yml (WARNING: I don't really know what I'm doing, I've now clue about Haskell and `stack`) to read:

```
[....]
ghc-options:
   locals: -fhide-source-paths
resolver: lts-10.3
```

Try again; get a different error:

```
$> stack setup
Downloaded lts-10.3 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

Now I'm lost...  Is this a (temporary) bug in building Aeson?

**Comment by jgm** [comment]
You need to update stack.

+++ Kurt Pfeifle [Mar 01 18 23:56 ]:

**Comment by jgm** [comment]
Or, simply delete the ghc-options line and the next line
from stack.yaml.

**Comment by KurtPfeifle** [comment]
I did run

    $> stack update ; stack upgrade

    $> stack --version | head -n 1
     Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0

Now the build process is on its way.... **Shouldn't it be documented how users can make sure they have the recent enough `stack` command** in order to follow instructions here: http://pandoc.org/installing.html#quick-stack-method ?

Thanks a lot!

**Comment by jgm** [comment]
Yes, this should be added to the INSTALL.md documentation.
