### ISSUE TITLE
Issues with Wiki (renamed some pages, can't undo)

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4426]
I wanted to clone and edit the Wiki locally, but some page names had invalid characters for working under Windows (`"`, `?`, `:`) so I renamed them online in order to clone the Wiki.

The affected pages are:

- How to add a 'Table of Contents' title in the HTML template
- Trials and Tribulations, How to find correct font names for Pandoc's use with LuaLaTeX
- Tabular overview, Pandoc's supported Markdown dialects and extensions enabled by default

... removing the unsupported chars allowed cloning to Windows locally.

Then I made my changes, but when I tried to push them I realized that, even though the Wiki is editable by anyone online, this doesn't apply to pushing changes.

I now realize that I've unnecessarily renamed pages, and potentially broken some links — if local editing was possibile, it might have been worthy to do so, since GitHub recommends not using characters like `"`, `?` and `:` in filenames. But since pushing local changes to the Wiki is not possible, I wanted to revert my changes, and undo the file renames.

Initially, I thought that I could after undo the renames from the Wiki WebUI, but then discovered I can't — I can't revert the commits locally, because then the old filenames break Git workings.

Unfortunately, it looks like I can't revert the edits, even from the Wiki history page. Basically, I wanted to revert the following changes I commited (online, via WebUI):

- `f3e9403`
- `af7aa18`
- `614230f`
- `273e883`

... but it looks like this can only be done by and Admin.

I'm really sorry for the unconvenience; I was just hoping to allow working locally with the Wiki, since using an IDE for editing markdown simplifies the task — but it looks like the only way is to copy the source of the page from the Wiki and paste into the editor, change the doc, and then paste it back in the Wiki's WebUI.

If it was possible to clone and edit the Wiki locally it would be great (and in this case, it would be worth fixing filenames with illegal characters for some OSs). With my own repos I always work on the Wiki locally, so I just assumed that for project Wikis opens to contributions anyone could push changes. I'm not sure if this restriction depends on some repository settings in the pandoc project, or if it's a default GitHub behaviour.

Sorry about this. 😢

**Comment by jgm** [comment]
I think I've done this, now -- but I did it in git offline, so could you check online to make sure everything looks right?
