### ISSUE TITLE
Text.Pandoc.Readers.LaTeX compilation consumes too much memory

### ISSUE THREAD

**Issue by labdsf** [jgm/pandoc#4435]
Other files are compiled without problems, but on this file I keep getting "Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)" unless I close my browser.

I don't know what the problem is exactly, maybe it is the use of some GHC extension.

**Comment by mb21** [comment]
Could you post the file and exact command used?

**Comment by labdsf** [comment]
@mb21 Command is `stack build -j 1`. I am compiling pandoc source code, not reading some LaTeX file.

**Comment by mb21** [comment]
ah, I was confused by "close my browser"... so how much memory does your system have/is consumed by ghc? (not sure the performance tag is applicable... compiling haskell is known to be performance-intensive, running pandoc is another matter.)

**Comment by labdsf** [comment]
ghc consumes ~1.7G

**Comment by mb21** [comment]
AFAIK, 2GB memory usage is well within what's to be expected when compiling a largish haskell code-base... the compiler does a lot of work so the produced program doesn't have to do it at runtime. However, you can try tweaking things like disabling optimizations (`ghc -O0`) etc...
