### ISSUE TITLE
ms export with Unicode headings

### ISSUE THREAD

**Issue by teoric** [jgm/pandoc#4436]
When using pandoc to export to ms with unicode headings, there is an error in the `.pdfhref M` (pdf marks)  requests which makes the resulting Postscript / PDF useless.  This can be avoided by replacing non-ASCII characters with ASCII equivalents (or something else).

Example:

```markdown
---
title: Test
author: None
...

# Bäh

Buh.
```
Converting with Pandoc 2.1.2,
```sh
pandoc Test.md -o Test.ms
```
results in

```roff
.SH 1
Bäh
.pdfhref O 1 "Bäh"
.pdfhref M "bäh"
.LP
Buh.
```

wich my `evince` shows as an empty page. (Viewing intermediate PostScript gives an error.)

Changing the `.pdfhref M` to ASCII-only gives:

```roff
.SH 1
Bäh
.pdfhref O 1 "Bäh"
.pdfhref M "baeh"
.LP
Buh.
```

, which works, e.g. with
```sh
pdfroff -step -Kutf-8 -ms -mspdf
```
, and gives a 1-page document.

**Comment by mb21** [comment]
Isn't this a bug in `pdfroff`? Or do they specify that they only support ascii-urls in `.pdfhref`?

Because modern URLs technically can contain non-ascii chars and as such pandoc usually passes them on to output formats as such.

**Comment by teoric** [comment]
Well, I am not sure who is to blame (probably history), but this is related to **internal** links/anchors, not URLs.  I suppose names are generally better kept as ASCII in (g)roff.  It is possible to use
```roff
.pdfhref M -N baeh -- "bäh"
```
for setting an ASCII name with a (useless, undisplayed) non-ASCII descriptive text. This gives no error message. Setting a non-ASCII name explicitly,
```roff
.pdfhref M -N "bäh" -- baeh
```
gives the same error as using no "-N bäh", i.e. bad PostScript.

For URI destinations, one would use a
```roff
.pdfhref L -D URI
```
, if I read the pdfmark documentation correctly. I have not tried non-ASCII URL linking yet, but to me, it seems rather a different problem.

**Comment by teoric** [comment]
Thank you!
