### ISSUE TITLE
LaTeX \looseness command values appear in output document

### ISSUE THREAD

**Issue by simonrob** [jgm/pandoc#4439]
Pandoc (v2.1.2) treats the LaTeX \looseness command as a text modifier rather than an internal command. The following source document ends up outputting "Test =-1" rather than just "Test"

```
\documentclass{article}
\begin{document}
Test
\looseness=-1
\end{document}
```

The same thing happens for other unbracketed commands (such as \parindent, \parskip, \widowpenalty, etc - there are many, but I couldn't find a comprehensive list), but these are less of an issue as they are normally set in the document preamble, whereas \looseness can be scattered around the document and applied to individual paragraphs.

**Comment by circleb** [comment]
I'm running Pandoc (installed with Homebrew—2.7.3) but I'm having the same issue described here as fixed... Is this supposed to be fixed, or am I misunderstanding something?

**Comment by mb21** [comment]
It's going to be in 2.7.4... you can try the nightly builds in the meantime...
