### ISSUE TITLE
Docx reader: Parse nested smartTags

### ISSUE THREAD

**Issue by edoshor** [jgm/pandoc#4446]
Parse nested smartTags

Similar to #2242 just with a deeply nested `w:smartTag` structure.

I have something like this in a `document.xml`:
```xml
<w:smartTag w:uri="urn:schemas-microsoft-com:office:smarttags" w:element="country-region">
    <w:smartTag w:uri="urn:schemas-microsoft-com:office:smarttags" w:element="place">
        <w:r w:rsidRPr="00AF4549">
            <w:t>Israel</w:t>
        </w:r>
    </w:smartTag>
</w:smartTag>
```

Using version 2.1.2

Hope it's easy as #4415

**Comment by jkr** [comment]
@edoshor any chance you can upload your document as a test case?

**Comment by edoshor** [comment]
[633_eng_t_bs-159-ve-yehi-ba-yamim.docx](https://github.com/jgm/pandoc/files/1805753/633_eng_t_bs-159-ve-yehi-ba-yamim.docx)
