### ISSUE TITLE
docx conversion fails with "\bmod" in math

### ISSUE THREAD

**Issue by isobit** [jgm/pandoc#4447]
## Environment

Pandoc 1.16.0.2

## Steps to Reproduce

- Create an file `input.md` with the contents `$a \bmod b$`
- Run `pandoc test.md -o test.docx`
- Open `test.docx` and note that the equation is left untranslated (with `$`'s reproduced verbatim)

**Comment by mb21** [comment]
Try with the newest pandoc version...

**Comment by isobit** [comment]
Whoops, you're right, had an old version. Trying on `2.1.2` yields the same results, with the following message:
```
[WARNING] Could not convert TeX math 'a \bmod b', rendering as TeX:
  a \bmod b
          ^
  unexpected "b"
  expecting "%", "\\label", "\\nonumber" or whitespace
```

**Comment by mb21** [comment]
I don't think `\bmod` is supported by https://github.com/jgm/texmath

**Comment by jgm** [comment]
This is really an issue in texmath, a library pandoc uses.
Please report this there instead: jgm/texmath.

**Comment by isobit** [comment]
Closing as duplicate of jgm/texmath#115.
