### ISSUE TITLE
Undue Missing Title Warning

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4449]
pandoc v2.1.2 | Win10 x64

I get an empty title warning even when the title is passed via `-V` option:

    D:\>pandoc -V title:MyTtitle README.md --template=GitHub.html5 > README.html

    [WARNING] This document format requires a nonempty <title> element.
      Please specify either 'title' or 'pagetitle' in the metadata.
      Falling back to 'README'

The title shows up correctly in the final html doc. Somehow, pandoc is reporting an empty `title`, and falling back to the filename even though the title variable is actually defined and used.

**Comment by mb21** [comment]
Set the metadata directly (instead of via `--variable`):

    pandoc -M title:MyTtitle

**Comment by tajmone** [comment]
This warning message is going to confuse new users, especially the `Falling back to '<filename>'` part — this part of the warning is not very clear, it seems to say that the value of `title` is going to be the file's name.

Maybe this warning message could be improved.

**Comment by mb21** [comment]
> it seems to say that the value of title is going to be the file's name.

that's exactly what's going to happen. from your example it would be:

    <title>README</title>

**Comment by tajmone** [comment]
But even if the warning says `Falling back to 'README'`, the actual title in the document of the above example is `MyTtitle` — the warning is considering only the metadata, but then the variable passed for title is used for the doc title. The warning should also check if a title variable is present, before stating that it will fallback on the filename.

It seems to me that the warning is issued without considering template variables as alternative to metadata. Of course, in similar cases the message is confusing: since the title passed as variable is working, the user is left wondering if there is a problem somewhere else.

**Comment by jgm** [comment]
There are two places the title shows up in the generated HTML:
in the body of the document (as a header) and in the `<title>`
tag. I think you'll find that the content of your `<title>`
tag is `README`.

If you look at the template, you'll see there's a difference
between `title` and `pagetitle`.

**Comment by tajmone** [comment]
I see. I though that in lack of a metadata title pandoc would always fallback on a `title` variable, when available. If I'm not wrong, at least with pandoc v1, `title` and `title-meta` were the page and metadata variants of the title for HTML documents, and the former would always imply the latter.

**Comment by jgm** [comment]
There have to be separate metadata variables for title and title-meta,
because formatting that is allowed in the title is not always allowed
in the title tag.  Pandoc will generate the title-meta automatically
from a title in metadata, but if you're just setting the variable
this doesn't work.
