### ISSUE TITLE
HTML to -> conversion Inline style align lost

### ISSUE THREAD

**Issue by olimpoweb** [jgm/pandoc#4451]
Hi all,
 i have a problem, when convert an html file (i.e. to pdf or epub) i lost inline align formatting
Original
```
<p style="text-align:right;">Some example text</p>
```
After
```
<p>Some example text</p>
```
Please help me!

Regards

**Comment by jgm** [comment]
Pandoc tries to capture structure, not presentational things like this.  And currently there is no way to put attributes on a paragraph (there's already an open issue for adding attributes to every block-level item). So, closing as out of scope.
