### ISSUE TITLE
Feature suggestion: enhance `auto_identifiers` 

### ISSUE THREAD

**Issue by psychelzh** [jgm/pandoc#4452]
Currently, the `auto_identifiers` can be a little flawed. For example, if I write an essay in non-English language, say Chinese, the non-English headers won't generate a valid `auto_identifiers`. I wonder whether is it a plausible request to support these types of header generation?

There are many issues related to this: rstudio/rmarkdown#1149, rstudio/rmarkdown#1241, rstudio/bookdown#520

**Comment by jgm** [comment]
What version of pandoc are you using?  With the latest version:

```
% pandoc -t html
# 标题 {.tabset}

## 标签一

内容

## 标签二

内容
^D
<h1 id="标题" class="tabset">标题</h1>
<h2 id="标签一">标签一</h2>
<p>内容</p>
<h2 id="标签二">标签二</h2>
<p>内容</p>
```

So this statement from the linked issue is misleading:

> That is not possible, because Pandoc cannot generate automatic ID's for headers that do not contain any alphanumeric characters (e.g. pure Chinese): http://pandoc.org/MANUAL.html#header-identifiers You will have to file a feature request to Pandoc.

Note:  Chinese letters are alphanumeric!

**Comment by jgm** [comment]
Also, be sure you're generating `html5` (in current pandoc this is the default `html`), and not `html4`, which requires ascii identifiers.

**Comment by psychelzh** [comment]
Thank you for your response! But I have tried the newest version, the results generated are not yet as expected. Seemingly it is not an issue of `pandoc`? Let me do some more research.

**Comment by psychelzh** [comment]
After another talk, `Rmarkdown` developers told me that there is another extension to do the job. Thanks again. @jgm Closing this issue.
