### ISSUE TITLE
footnote problem with pandoc 2.1.2

### ISSUE THREAD

**Issue by andalou** [jgm/pandoc#4453]
I'm using pandoc 2.1.2 on Windows 7.
I converted to epub the following text:

    % Title
    % Author
    
    # Chapter 1[^1]
    This is a test
    
    [^1]: Hur mår du?

when testing it with epubcheck I got:

Validating against EPUB version 3.0
ERROR: tmp1.epub/EPUB/nav.xhtml(18,28): element "section" not allowed here; expected the element end-tag, text or element "a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "command", "datalist", "del", "dfn", "em", "embed", "epub:switch", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "map", "mark", "meter", "ns1:math", "ns2:svg", "object", "output", "progress", "q", "ruby", "s", "samp", "script", "select", "small", "span", "strong", "sub", "sup", "textarea", "time", "u", "var", "video" or "wbr" (with xmlns:ns1="http://www.w3.org/1998/Math/MathML" xmlns:ns2="http://www.w3.org/2000/svg")
ERROR: tmp1.epub/EPUB/nav.xhtml(21,38): element "p" not allowed here; expected element "a" or "span"
ERROR: tmp1.epub/EPUB/nav.xhtml(21,103): element "li" incomplete; expected element "a" or "span"
ERROR: tmp1.epub/EPUB/nav.xhtml(17,209): report: The a element must not appear inside a elements.
ERROR: tmp1.epub/EPUB/nav.xhtml(21,89): report: The a element must not appear inside a elements.
WARNING: tmp1.epub/EPUB/nav.xhtml(17,209): hyperlink to resource outside spine 'EPUB/nav.xhtml'
WARNING: tmp1.epub/EPUB/nav.xhtml(21,89): hyperlink to resource outside spine 'EPUB/nav.xhtml'

Check finished with warnings or errors

Apparently, with the new version, you cannot put footnotes on headers.

I don't get these errors and warnings with pandoc 1.16

-- 
Cesar

**Comment by jgm** [comment]
Note that pandoc 1.16 only produces epub2.  epub3 is now the default.  You can try `-t epub2` to see if that works better.

**Comment by andalou** [comment]
Doing
pandoc -t epub2 -o tmp.epub tmp.txt

and validating with epubcheck I get:

Validating against EPUB version 2.0
ERROR: tmp2.epub/EPUB/nav.xhtml(19,24): element "div" not allowed here; expected the element end-tag, text or element "a", "abbr", "acronym", "applet", "b", "bdo", "big", "br", "cite", "code", "del", "dfn", "em", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "q", "samp", "script", "small","span", "strong", "sub", "sup", "tt" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")
WARNING: tmp2.epub/EPUB/nav.xhtml(18,173): hyperlink to resource outside spine 'EPUB/nav.xhtml'
WARNING: tmp2.epub/EPUB/nav.xhtml(22,68): hyperlink to resource outside spine 'EPUB/nav.xhtml'

Check finished with warnings or errors


With pandoc 1.16 I can get epub3 using -t epub3. Validating with epubcheck doesn't throw any errors or warnings.
