### ISSUE TITLE
Markdown syntax for beamer "\alert"

### ISSUE THREAD

**Issue by gjherbiet** [jgm/pandoc#4457]
Hello, 

This issue can be thought as a reverse of #4091 : would it be possible to have a Markdown syntax element that translates to LaTeX Beamer `\alert` command.

For instance, using `!!` as delimiter, this would give:

```
$ echo "This text has an !!alert part with *emphasis*!!." | pandoc -f markdown -t beamer
\begin{frame}

This text has an \alert{alert part with \emph{emphasis}}.

\end{frame}
```

Ideally, this would support nested formatting, as in the example.

**Comment by mb21** [comment]
You can simply write raw TeX, e.g. `\alert` inside your markown document.

**Comment by cagix** [comment]
You could also use `(blabla){.alert}` and translate the resulting span with a short lua-filter ...

**Comment by CLRafaelR** [comment]
@gjherbiet 

You can use the following lua filter (say, `alert.lua`) when you produce a beamer presentation.

``` lua
if FORMAT:match 'beamer' then
    function Span(el)
        if el.classes[1] == "alert" then
            table.insert(el.content, 1, pandoc.RawInline("latex", "\\alert{"))
            table.insert(el.content, pandoc.RawInline("latex", "}"))
        end
        return el
    end
    return { { Span = Span } }
end

```

In a md file, `[what you want to highlight]{.alert}` is the command to produce a text with an alert. Note that you need to enclose the text with square bracket `[...]`, not `(...)`.

``` markdown
## frame header

- This is important
- This is also important
- This is [the most important]{.alert} line

```

Then, your md is converted into a beamer presentation pdf with alerts.

``` bash
pandoc --lua-filter=alert.lua -t beamer presentation.md -o presentation.pdf
```
