### ISSUE TITLE
pandoc-2.1.2 does not comile with ghc 8.4.1 becaues of haddock-library constraint

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#4460]
GHC 8.4.1 needs `haddock-library-1.5.0.1`. Therefore, attempts to compile `pandoc` with that compiler fail because of the constraint `haddock-library >=1.1 && <1.5`.

**Comment by mb21** [comment]
What pandoc version are you on? Can you try with current master?

**Comment by peti** [comment]
I did, and fad8d0d67ff4736e1af554d2bfcf1688aa28c8ec compiles fine with GHC 8.4.1 and haddock-library 1.5.x.

**Comment by mb21** [comment]
Great, so this was fixed by fad8d0d then.
