### ISSUE TITLE
Fedora: One markdown file fails to convert after update

### ISSUE THREAD

**Issue by Devices** [jgm/pandoc#4461]
Setup:
- Fedora 27
- Pandoc 2.1.1 from [Petersen copr repo](https://copr.fedorainfracloud.org/coprs/petersen/pandoc/)
- 1GB RAM

Commands to reproduce the problem:
1. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -t ms -o ruhletest.pdf`
2. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -o ruhletest.html`
3. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -o ruhletest.mobi`
4. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -o ruhletest.epub`

File in question: [ruhle_1928_karl_marx_life_and_work.txt](https://github.com/jgm/pandoc/files/1821641/ruhle_1928_karl_marx_life_and_work.txt)
**Note: Since github does not support the .md extension, I have attached it as a txt file. Rename the file.**

Output:
fish: “pandoc ruhle_1928_karl_marx_lif…” terminated by signal SIGSEGV (Address boundary error)
Usually it also freezes my server for a while until it terminates.
Note: fish is my shell.

Elaboration:
I was using pandoc version 2.0.0.1 before from that copr repo, but after the update to 2.1.1 I get the error listed under 'output'. I convert about 250 other markdown files at once and this is the only file that produces this error after the upgrade to 2.1.1.

When I use pandoc 1.19.1 in the official fedora repo's I also do not get an error when running the commands. Except command 1, since 1.19 does not have pdfgroff support yet.

I also performed the command with strace, maybe it is helpful. [pandoc_strace.txt](https://github.com/jgm/pandoc/files/1821658/pandoc_strace.txt)

Summary:
1.19.1 and 2.0.0.1 convert the markdown file fine, but since 2.1.1 it produces an error.

If more information is required I'd be happy to provide it if it's within my capabilities. I am not a programmer and not very good at things like compiling.

**Comment by mb21** [comment]
Can you try with an official build: https://github.com/jgm/pandoc/releases

**Comment by Devices** [comment]
I downloaded pandoc-2.1.2-linux.tar.gz, extracted it and ran the command `./pandoc ruhle_1928_karl_marx_life_and_work.md -s -t ms -o ruhletest.pdf` and got the same output as in the top post.

**Comment by mb21** [comment]
also `-o ruhletest.html` ?

I cannot reproduce this on macOS...

**Comment by mb21** [comment]
Could you also try a different shell maybe?

**Comment by Devices** [comment]
I tried converting to .html using fish and also bash and they both fail. Using bash I get a different output: "Segmentation fault (core dumped)".

**Comment by mb21** [comment]
Strange... but other conversions work? e.g. `echo test | pandoc -o test.html`

Sounds like its Fedora-specific (or possibly Linux-specific). I guess you could try [building from source](https://github.com/jgm/pandoc/blob/master/INSTALL.md#compiling-from-source)

**Comment by Devices** [comment]
Yes other conversions work, it's only this file that causes a problem for me. I convert an entire repository with markdown files to html, pdf, epub and mobi (this one: https://github.com/redtexts/texts) and all conversions go fine, except this one file.

The file does convert with the two other pandoc versions I listed on the same OS, so I figured there must be something new introduced in 2.1.

Also I just tried converting the file on [Solus](https://solus-project.com/) with the official 2.1.2 build and that works fine. Seems like it's maybe indeed be Fedora specific. I don't have other Fedora machines to test on though.

**Comment by Devices** [comment]
Small update.

I spun up another Fedora 27 server on vultr (where my other server is too) and I get the same error when converting that file while other files work.

I also spun up an ubuntu 16.04 server and the file did convert there. I used the official 2.1.2 build for both OSs.

Seems like we have two OS (Solus, Ubuntu 16.04) where it works so far and one (Fedora 27) where it does not.

**Comment by mb21** [comment]
Our official build is created on Debian (or Ubuntu) so it's not that surprising... from INSTALLING:

> If you use an RPM-based distro, you may be able to install the deb from our download page using alien.

Or as I mentioned: building from source should work fine.

**Comment by jgm** [comment]
Do all of these commands produce the problem with this file,
or just one of them?

> 1. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -t ms -o ruhletest.pdf`
> 2. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -o ruhletest.html`
> 3. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -o ruhletest.mobi`
> 4. `pandoc ruhle_1928_karl_marx_life_and_work.md -s -t ms -o ruhletest.epub`

Note:  pandoc does not support 'mobi' output, so command 3 is just
going to produce html.

**Comment by Devices** [comment]
>Or as I mentioned: building from source should work fine.
The 2.1.1 package in that copr repo is also build from source, isn't it? Or would building it on my own server make a difference?

>Do all of these commands produce the problem with this file, or just one of them?
All of them.

>Note: pandoc does not support 'mobi' output, so command 3 is just going to produce html.
This is good to know, thanks.

**Comment by mb21** [comment]
> Or would building it on my own server make a difference?

It just might, since the libraries linked against (and other system-specific stuff) might be different on your system...

**Comment by ousia** [comment]
@Devices,

I’m using both Fedora 27 (64bit & 8GB RAM) and pandoc-2.1.1 from @juhp’s repo.

I can generate both ePub and HTML outputs perfectly fine. I don’t have LaTeX installed on my system.

Just in case it helps.

**Comment by ousia** [comment]
I also have `ghc-pandoc-types` and `ghc-pandoc-types-devel` installed, but I don’t think this should affect to the problem you describe.

**Comment by juhp** [comment]
Just for the record, when @Devices and I discussed this earlier in private I was not able to reproduce: it is probably worth testing with Fedora 28 too which is approaching Beta.
