### ISSUE TITLE
`stack ghci` fails

### ISSUE THREAD

**Issue by oltolm** [jgm/pandoc#4464]
`stack ghci` fails with the following error message. `intero` does not work either because of the same problem.

```
pandoc-2.1.3: configure (lib + exe)
Configuring pandoc-2.1.3...
pandoc-2.1.3: initial-build-steps (lib + exe)
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: pandoc
Using main module: 1. Package `pandoc' component exe:pandoc with main-is file: C:\src\pandoc\pandoc.hs
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help

<interactive>:1:1: error:
    attempting to use module `main:Prelude' (C:\src\pandoc\prelude\Prelude.hs) which is not loaded
```

**Comment by jgm** [comment]
This is because of the custom Prelude we're now using for compatibility across base versions.
The problem is a thorny one:
https://ghc.haskell.org/trac/ghc/ticket/10920
https://www.reddit.com/r/haskell/comments/3ryf2p/how_can_you_use_a_custom_prelude_with_ghci/

**Comment by jgm** [comment]
The most recent commit should allow you to use `stack ghci` or `cabal repl` as long as you use ghc 8.4.1.

**Comment by jgm** [comment]
Better fix coming soon.
