### ISSUE TITLE
div inside enumeration

### ISSUE THREAD

**Issue by danieltuzes** [jgm/pandoc#4465]
pandoc version 2.1.2
The following **html** code
```
<ol>
  <li> An ordered list can contain block-level elements ind html, it means that divs are also allowed.</li>
  <li>Let's see the problem! <div class="example">This is an example.</div></li>
</ol>
```
converts to the following **markdown** code
```
1.  An ordered list can contain block-level elements ind html, it means
    that divs are also allowed.
2.  Let\'s see the problem!
    ::: {.example}
    This is an example.
    :::
```
by `pandoc test.html -o test.md`. This md with a switch `--filter pandoc-latex-environment` translates into the following **latex** code 
```
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  An ordered list can contain block-level elements ind html, it means
  that divs are also allowed.
\item
  Let's see the problem! ::: \{.example\} This is an example. :::
\end{enumerate}

```
by `pandoc -f markdown+header_attributes+auto_identifiers+ascii_identifiers --filter pandoc-latex-environment test.md -o test.tex`

Outside an enumeration the conversion works fine. How can I translate the html divs to latex environments, like pandoc did before version 2? I tried to turn it off without success.

**Comment by jgm** [comment]
Note, this doesn't work outside an enumeration either:
```
% pandoc -t latex
Let\'s see the problem!
::: {.example}
This is an example.
:::
^D
Let's see the problem! ::: \{.example\} This is an example. :::
```
You need a blank line before the fenced div.

Pandoc translates your HTML code thus:
```
[OrderedList (1,DefaultStyle,DefaultDelim)
 [[Plain [Str "An",Space,Str "ordered",Space,Str "list",Space,Str "can",Space,Str "contain",Space,Str "block-level",Space,Str "elements",Space,Str "ind",Space,Str "html,",Space,Str "it",Space,Str "means",Space,Str "that",Space,Str "divs",Space,Str "are",Space,Str "also",Space,Str "allowed."]]
 ,[Plain [Str "Let's",Space,Str "see",Space,Str "the",Space,Str "problem!"]
  ,Div ("",["example"],[])
   [Plain [Str "This",Space,Str "is",Space,Str "an",Space,Str "example."]]]]]
```
When rendering Markdown, it renders the Plain without a following blank line (contrast Para, which gets a following blank line).  That's why you don't get the blank line you need.

So, maybe the markdown writer needs to be changed, to ensure that there are always blanks around a fenced div.

**Comment by thosgood** [comment]
what is the correct way to have a fenced div in the middle of an enum item? I can't seem to get anything to work

**Comment by mb21** [comment]
> what is the correct way to have a fenced div in the middle of an enum item?

In markdown, you would do e.g.:

```
1.  An ordered list can contain block-level elements ind html, it means
    that divs are also allowed.

2.  Let's see the problem!

    ::: {.example}
    This is an example.
    :::
```

**Comment by 3geek14** [comment]
If I add a blank line before the fenced div, pandoc is putting each list item into a paragraph, adding unwanted vertical spacing between list elements. Currently, my wordaround is to use native divs within lists, but is there another workaround?
