### ISSUE TITLE
wrong text coloring for TeX command

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#4466]
For some strange reason, [latest `pandoc`](https://pandoc.org/try/?text=%60%60%60%7B.tex%7D%0A%5Cdef%5CDesiredFont%7BTeX+Gyre+Heros%7D%0A%60%60%60&from=markdown&to=html5) parses:

``` tex
\def\DesiredFont{TeX Gyre Heros}
```
into

``` html
<div class="sourceCode" id="cb1">
  <pre class="sourceCode tex">
    <code class="sourceCode latex">
      <a class="sourceLine" id="cb1-1" data-line-number="1">
        <span class="fu">\def</span>\DesiredFont{TeX Gyre Heros}
      </a>
    </code>
  </pre>
</div>
```

It detects `\def` as command, but it doesn’t `\DesiredFont` as a command.

Could it be fixed?

**Comment by jgm** [comment]
This concerns syntax highlighting of code.
See jgm/skylighting.  It could be reported there instead.
Note that that tex tokenizer is generated from a KDE syntax highlighting definition, and there are some limitations there.
