### ISSUE TITLE
ms writer uses minus instead of dash, even with -smart

### ISSUE THREAD

**Issue by teoric** [jgm/pandoc#4467]
The ms writer uses minus (`\-`) instead of dash, even with `-smart`. This means that any hyphen is replaced by a minus sign ([U+2212](https://www.fileformat.info/info/unicode/char/2212)), and hence basically looks like an en dash.  I think it would be better to leave the dash as is, at least with `-smart`.

For `+smart`, a plausible en-dash (not any hyphen!) should not be `\-` either, but could be `\(en`, according to [`groff_char(7)`](http://man7.org/linux/man-pages/man7/groff_char.7.html).  But as the text must be piped through as UTF-8, anyway, one could also just use a Unicode en dash ([U+2013](https://www.fileformat.info/info/unicode/char/2013)) in the latter case.

Example:

```sh
echo "no-one" | pandoc -f markdown-smart -t ms-smart 
```
leads to output
```roff
.LP
no\-one
```
Should be:
```roff
.LP
no-one
```

Pandoc 2.1.2, Linux

**Comment by jgm** [comment]
We don't want `\(en`, which is an en-dash.  (That's what you get
with `--` in smart.)

Looks like we want `(hy`, hyphen, or just leave it as `-`.

> the ISO latin1 ‘Hyphen, Minus Sign’ (code 45) prints as a
> hyphen (Unicode u2010).  The same output glyph can be
> requested explicitly with ‘\(hy’.  A minus sign can be
> obtained with ‘\-’ (Unicode u2212).
