### ISSUE TITLE
Comments in LaTeX templates effect non-commented lines

### ISSUE THREAD

**Issue by Joedang** [jgm/pandoc#4469]
It seems that when commenting-out some lines in a LaTeX template, Pandoc can end up commenting-out _unrelated_ adjacent lines in the resulting `.tex` file.

Here's a nearly minimal example of what I'm experiencing: 

```
$ make all
pandoc example.md --template=bugTemplate.tex -o bug.tex
pandoc example.md --template=nobugTemplate.tex -o nobug.tex
pandoc --version | head -n 1
pandoc 1.16.0.2
make -v | head -n 1
GNU Make 4.1

diff between templates:
colordiff -y bugTemplate.tex nobugTemplate.tex || true
\documentclass{$documentclass$}                                 \documentclass{$documentclass$}
% $if(tables)$                                                | $if(tables)$
% \usepackage{longtable,booktabs}                             | \usepackage{longtable,booktabs}
% $endif$                                                     | $endif$
$if(indent)$                                                    $if(indent)$
$else$                                                          $else$
\IfFileExists{parskip.sty}{                                     \IfFileExists{parskip.sty}{
\usepackage{parskip}                                            \usepackage{parskip}
}{% else                                                        }{% else
\setlength{\parindent}{0pt}                                     \setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}                    \setlength{\parskip}{6pt plus 2pt minus 1pt}
}                                                               }
$endif$                                                         $endif$
\begin{document}                                                \begin{document}
\end{document}                                                  \end{document}

diff between outputs:
colordiff -y bug.tex nobug.tex || true
\documentclass{article}                                         \documentclass{article}
% \IfFileExists{parskip.sty}{                                 | \IfFileExists{parskip.sty}{
\usepackage{parskip}                                            \usepackage{parskip}
}{% else                                                        }{% else
\setlength{\parindent}{0pt}                                     \setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}                    \setlength{\parskip}{6pt plus 2pt minus 1pt}
}                                                               }
\begin{document}                                                \begin{document}
\end{document}                                                  \end{document}

```

As you can see, commenting-out the stuff about tables in the template causes the totally unrelated stuff about `parskip.sty` to be commented-out in the resulting LaTeX. In this example, the resulting file is not only incorrect, but it can't be compiled to a `.pdf`, since an opening brace gets commented-out without its pair.

Here are my example files:  
[pandocBug.zip](https://github.com/jgm/pandoc/files/1823429/pandocBug.zip)

**Comment by mb21** [comment]
Can you try with the newest pandoc version?

**Comment by wilx** [comment]
I think you are confusing LaTeX comments and Pandoc template comments. The LaTeX comment starting character `%` does not comment out the `$if(tables)$`. This, combined with trailing newline eating behaviour of the Pandoc templates directives, is probably the reasons for what you are seeing. If you want to actually comment out something in Pandoc template so that the templating engine does not put it into the resulting .tex file, then use the `$-- ` comment starting sequence. See also [`pandoc-template-mode.el`](https://github.com/jgm/pandoc/blob/master/tools/pandoc-template-mode.el), for code highlighting Pandoc templates in Emacs.

**Comment by mb21** [comment]
Thanks @wilx for looking into this!

**Comment by jgm** [comment]
Joe Shields <notifications@github.com> writes:

```
% $if(tables)$
% \usepackage{longtable,booktabs}
% $endif$
```

I think this is a case of misplaced expectations.  Pandoc's template
engine is completely format-neutral.  It doesn't know about latex
comments!  So your latex comments don't affect template processing.

Recent versions of pandoc (maybe not your quite old version) support
a special comment syntax for templates:

```
$-- $if(tables)$
$-- \usepackage{longtable,booktabs}
$-- $endif$
```
