### ISSUE TITLE
Markdown parser confused by "DDC." in bullet list

### ISSUE THREAD

**Issue by garethstockwell** [jgm/pandoc#4480]
When the string "DDC." appears in a bullet list item, it is transformed into some strange hieroglyph.

A MWE follows.  The bug was reproduced with pandoc 2.1.3.

Source file input.md:

    Here is a list.
    For some reason, the item DDC. is corrupted in the output.
    This happens regardless of whether DDC is lower- or upper-case.
    This only happens when DDC is followed immediately by a full stop:

      - DDC.
      - ddc.
      - DDC .
      - DDC
      - D DC.
      - FOO.
      - FOO

    This occurs regardless of the position of DDC. within the list:

      - DDC
      - DDC.
      - FOO.
      - FOO

Command to convert to TeX:

    pandoc --from markdown input.md --to latex --output output.tex

Output output.tex:

    Here is a list. For some reason, the item DDC. is corrupted in the
    output. This happens regardless of whether DDC is lower- or upper-case.
    This only happens when DDC is followed immediately by a full stop:

    \begin{itemize}
    \item
      \begin{enumerate}
      \def\labelenumi{\Roman{enumi}.}
      \setcounter{enumi}{1099}
      \item
      \end{enumerate}
    \item
      \begin{enumerate}
      \def\labelenumi{\roman{enumi}.}
      \setcounter{enumi}{1099}
      \item
      \end{enumerate}
    \item
      DDC .
    \item
      DDC
    \item
      D DC.
    \item
      FOO.
    \item
      FOO
    \end{itemize}

    This occurs regardless of the position of DDC. within the list:

    \begin{itemize}
    \item
      DDC
    \item
      \begin{enumerate}
      \def\labelenumi{\Roman{enumi}.}
      \setcounter{enumi}{1099}
      \item
      \end{enumerate}
    \item
      FOO.
    \item
      FOO
    \end{itemize}

Command to convert to HTML:

    pandoc --from markdown input.md --to html --output output.html

Output output.html:

    <p>Here is a list. For some reason, the item DDC. is corrupted in the output. This happens regardless of whether DDC is lower- or upper-case. This only happens when DDC is followed immediately by a full stop:</p>
    <ul>
    <li><ol start="1100" type="I">
    <li></li>
    </ol></li>
    <li><ol start="1100" type="i">
    <li></li>
    </ol></li>
    <li>DDC .</li>
    <li>DDC</li>
    <li>D DC.</li>
    <li>FOO.</li>
    <li>FOO</li>
    </ul>
    <p>This occurs regardless of the position of DDC. within the list:</p>
    <ul>
    <li>DDC</li>
    <li><ol start="1100" type="I">
    <li></li>
    </ol></li>
    <li>FOO.</li>
    <li>FOO</li>
    </ul>

**Comment by jgm** [comment]
pandoc thinks DDC is a roman numeral (1100).  Of course, it isn't; this is a bug in the Roman Numeral parser that should be fixed.  But I hope that explains the output.  I'll just illustrate with `I`, which you'll agree is a Roman Numeral.
```
I.
```
is a one-item Roman-numbered list with an empty item.
```
- I.
```
is the same thing, but inside a bulleted list item.
```
- DDC.
```
is the same thing, but with the "Roman numeral" DDC instead of I.

**Comment by garethstockwell** [comment]
Thanks @jgm for the very prompt response.  I confirm that the workaround works.
