### ISSUE TITLE
Starting in pandoc 2, figures without captions are left-justified in PDF output

### ISSUE THREAD

**Issue by nsheff** [jgm/pandoc#4483]
I am producing PDF output from markdown source.

In pandoc 1, figures without captions were centered by default. In pandoc 2, figures without captions are left-justified.

Was this change intended? I did not see documentation of this change in the release notes. I believe this is a bug and figures without captions should be centered in pandoc 2.

Reproducible example:

image.md:
```
# Here's an image:

![](example_figure.png)
```
example_figure.png: 
![example_figure](https://user-images.githubusercontent.com/5271009/37775189-a7042726-2db8-11e8-8ea2-93918e1b33f3.png)

command: `pandoc image.md -o image.pdf

Result under pandoc1: [image.pdf](https://github.com/jgm/pandoc/files/1837819/image.pdf)

Result under pandoc2: [image-pandoc2.pdf](https://github.com/jgm/pandoc/files/1837820/image-pandoc2.pdf)

**Comment by jgm** [comment]
Here's the relevant changelog entry:

    + Require nonempty alt text for `implicit_figures` (#2844).
      A figure with an empty caption doesn't make sense.

See #2844 for background.

If you want to make the image a figure anyway, then add a nonbreaking
space as the alt text, or (somewhat hackish and not guaranteed to be
future-proof:) add a title beginning with `fig:`.

**Comment by jpeacock29** [comment]
Unfortunately, adding a non-breaking space still triggers "Figure 1:" as the caption. Any other suggestions for a work around here? It seems odd that images in pdfs are centered with a caption and left justified without; would you consider a pull request to center all images in pdfs? Thanks!

**Comment by trou** [comment]
For those having the problem, adding a [Zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) does the trick.
You can copy the following text `(​)` and remove the parenthesis.

**Comment by nacaru-w** [comment]
I wonder if there have been any developments on this. I have tried a thousand ways to do it and still can't make it work.

**Comment by jgm** [comment]
You could achieve this with a Lua filter:
https://pandoc.org/lua-filters.html#center-images-in-latex-and-html-output

**Comment by nacaru-w** [comment]
Alright. I finally found a way. I'll leave the answer here for everyone else to see (worked for me in Pandoc 3.1.9):

Using the Lua filter alone will add an unnecessary caption (images with captions are centered by default), so you need to:

1. Create a `.lua` file (for example, `center.lua`) that contains the following code:

```lua
-- Filter images with this function if the target format is LaTeX.
if FORMAT:match 'latex' then
  function Image (elem)
    -- Surround all images with image-centering raw LaTeX.
    return {
      pandoc.RawInline('latex', '\\hfill\\break{\\centering'),
      elem,
      pandoc.RawInline('latex', '\\par}')
    }
  end
end
```

2. Remove the `implicit_figures` plugin when you make the Pandoc call to convert the file, make sure to add the filter to the call:

```bash
pandoc --lua-filter=center.lua <YOUR FILE>.md -fmarkdown-implicit_figures -o <OUTPUT FILE>.pdf
```

Adding a fake caption and then removing the plugin, as some in StackOverflow have suggested, won't work (image sticks to the left).

**Comment by jgm** [comment]
Instead of `-implicit_figures`, you could have the Lua filter set the images `caption` to `{}`.
