### ISSUE TITLE
PDF generation speed w.r.t. image compression

### ISSUE THREAD

**Issue by paulmelis** [jgm/pandoc#4484]
I'm writing a report with dozens of pictures in it. When letting pandoc create a .pdf file with xelatex as engine this takes ages (almost 2 minutes), due to compression being applied to the images. I'm using `--pdf-engine-opt -output-driver='xdvipdfmx -z0'` to speed up the dvi -> pdf conversion (to less than 10 seconds) to inspect intermediate versions. 

It just occurred to me that for the multiple latex invocations that are run by pandoc (to get all the references correct) only the last one really needs to apply compression. If the `-z0` option could be added on all but the last steps it would speed up the process even when generating a compressed version.

**Comment by mb21** [comment]
If speed is very important, I guess you can always generate the tex and then run `xelatex` yourself (e.g. using a make file).

**Comment by jgm** [comment]
paulmelis <notifications@github.com> writes:

> I'm writing a report with dozens of pictures in it. When letting pandoc create a .pdf file with xelatex as engine this takes ages (almost 2 minutes), due to compression being applied to the images. I'm using `--pdf-engine-opt -output-driver='xdvipdfmx -z0'` to speed up the dvi -> pdf conversion (to less than 10 seconds) to inspect intermediate versions. 
>
> It just occurred to me that for the multiple latex invocations that are run by pandoc (to get all the references correct) only the last one really needs to apply compression. If this could be added it would speed up the process even when generating a compressed version.

So, your recommendation is that we add

    --pdf-engine-opt -output-driver='xdvipdfmx -z0'

to all invocations but the last one?  Can you think of any potential
drawbacks to this?  I don't know anything about image compression
in latex.

**Comment by paulmelis** [comment]
I don't think there are drawbacks. As far as I know the earlier latex invocations are mostly to get correct references and other data, not to produce an output file.
