### ISSUE TITLE
csv reader

### ISSUE THREAD

**Issue by lollipopman** [jgm/pandoc#4485]
Would it be possible to add a csv reader option to pandoc? As an example this would be very useful for converting spreadsheets into markdown tables.

Thanks for making pandoc!

**Comment by mb21** [comment]
There was something on the way: https://github.com/jgm/pandoc/issues/3533

But for now, you can use my https://github.com/mb21/pandoc-placetable filter, e.g.:

    pandoc-placetable --file=foo.csv | pandoc -f json -o output.html

**Comment by agusmba** [comment]
You can use filters to add csv tables to pandoc. See [pandoc-csv2table](https://github.com/baig/pandoc-csv2table) or [pantable](https://github.com/ickc/pantable)

If you simply want to convert spreadsheets into markdown tables you have several options also:
* Copy the table into a word document and convert from docx to markdown with pandoc (I normally do this for initializing my markdown tables)
* use an online (CSV -> markdown) converter: https://www.tablesgenerator.com/markdown_tables or https://jakebathman.github.io/Markdown-Table-Generator/
