### ISSUE TITLE
Bookmarks in PDF output (regression against markdown2pdf)

### ISSUE THREAD

**Issue by hickford** [jgm/pandoc#449]
Hi. I used to make PDFs with `markdown2pdf`. Those PDFs would have 'bookmarks' as [SumatraPDF](http://blog.kowalczyk.info/software/sumatrapdf/free-pdf-reader.html) calls them. I liked that, they show in a [sidebar](http://cdn.portableapps.com/SumatraPDFPortable.png) and let me navigate the document.

I recently upgraded Pandoc. Now there is no `markdown2pdf` and the instructions tell me to do `pandoc readme.txt -o readme.pdf`. The PDFs it makes don't have bookmarks :( What gives?

**Comment by pkaramol** [comment]
Hi, in the same context and to avoid creating a new issue, I would like to ask for some feedback if possible on this:
I have created a script that parses a `README.md` file with multiple linked `.md` documents, e.g.

    1. [Chapter 0](chapter0.md)
    1. [Chapter 1](dir1/chapter1.md)
      a. [Section 1.1](dir1/section1_1.md)
    1. [Chapter 2](dir2/chapter2.md)

and creates a stand alone `.pdf` file.

However, the ToC unfortunately maintains literal links to `.md` files and not using them as bookmarks pointing to the imported `.md` file.

i.e. when I hover over `Chapter 1` on the `.pdf` file, I get a link that opens the `dir1/chapter1.md` in my text editor.

Does pandoc handle automatic bookmarks creation somehow?

**Comment by mb21** [comment]
@pkaramol Why not use `pandoc out.pdf --toc **/*.md` ?

**Comment by pkaramol** [comment]
```
$ pandoc out.pdf --toc **/*.md
pandoc: Unknown reader: pdf
Pandoc can convert to PDF, but not from PDF.
```

**Comment by pkaramol** [comment]
@mb21 that was helpful ... 
However after the toc which is now created, is there a way to add a pagebreak? It goes on with the content.
many thanks either way

**Comment by mb21** [comment]
> is there a way to add a pagebreak?

add `\pagebreak` at the top of your first file or change your LaTeX template.

> I want the files parsed in a specfic order

see e.g. https://stackoverflow.com/questions/4779582/markdown-and-including-multiple-files or ask around on pandoc-discuss
