### ISSUE TITLE
Add Support for Blocks With Different Format

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4495]
This is a feature request.

When working with complex docs, especially when using multiple files as source document, it would be really useful to have some syntax to tell pandoc to treat a block as another format.

For example, I'm working with an automated app that dynamically creates the markdown source that is then fed to pandoc as a pandoc `markdown`  source; during the document creation the app also takes some external files (HTML, GFM).

Since the output format is HTML, external html files can be easily handled with the [raw_attribute] extension, and just enclose the imported file in a `~~~{=html}` block.

As for GFM documents (which might use some GFM specific syntax), I currently have to first convert them from `gfm` to `markdown` via pandoc, and then inject the result in the source doc the app is creating. Because, if my understanding is correct, __raw content__ via the [raw_attribute] extension has to be in the same format as the output format — ie, pandoc doesn't process it.

It would be sweeter to have a syntax that allows to tell pandoc that a given block is in another (supported) input format, so that pandoc will convert it to the _source_ format of the conversion option, before handling the rest of the conversion. This would allow the imported external content to be treated as native input format, and processed like the rest of the document (references, TOC, etc).

An example could be a syntax like this (along the lines of raw_attribute, an `<` instead of `=`):

``````````

```{<gfm}
GitHub flavoured markdown block
```

``````````

This feature would allow including all sorts of formats into the source document (not just markdown formats). While the above example might seem trivial (since pandoc supports most GFM features anyhow), inverting the two formats would not be so trivial: when converting from `gfm` to `html`, it would allow using pandoc markdown blocks within the GFM source (without having to specify any command line options that alter the default source format settings).

Extensions could be specified as usual:

``````````

```{<markdown+smart-auto_identifiers}
Markdown block with different extensions enabled.
```

``````````

Which would allow the given block to be in the same format as the input format, but using different extensions — this would be very practical even when working with a single source file, just to allow specific blocks to be treated differently in terms of extensions.

Also, an HTML external file would not be treated as raw HTML but converted into the input format on the fly:

``````````

```{<html}
<h1>Heading</h1>

<p>Some text.</p>
```

``````````

... in the above example, the heading would be integrated into the TOC generated by pandoc.

[raw_attribute]: http://pandoc.org/MANUAL.html#extension-raw_attribute

**Comment by tarleb** [comment]
If you are ok with using Lua filters, then you can emulate this as follows:

``` lua
function CodeBlock (blk)
  if #blk.classes == 1 and blk.classes[1]:sub(1,1) == '<' then
    local format = blk.classes[1]:sub(2)
    return pandoc.read(blk.text, format).blocks
  end
end
```

Just drop the curly braces (<code>``` <markdown+smart-auto-identifiers`</code>) and everything should work.

**Comment by tajmone** [comment]
Nice solution @tarleb !

What's your view on adding this feature natively, is it worth it or it belong to edge case usage scenarios that should be handled with filters?

Obviously, built in features have the advantage of working with out-of-the-box pandoc, and dispells the risk of any filter becoming incompatible with future versions — at the same time it might introduce more maintainance work to pandoc. I guess much depends on how useful this might be to users in general.

I think it would be good to have it because somehow it's the counterpart of Raw attributes (which targets the output format) and offers a similar feature targeting the source format instead (even though the latter adds conversion work to pandoc, unlike the former which is a passthrough functionality).

**Comment by tarleb** [comment]
Decisions like this are only @jgm's to make.

Personally, I very much like your proposed syntax. What worries me most is that every feature makes Markdown more complex, but simplicity seems to be one of Markdown's greatest features. The best solution from my point of view would be a method to easiy discover, download, and use filters like the above. But we don't have that (yet).

**Comment by tajmone** [comment]
Something like package manager for pandoc? that could find, setup and keep updated resources like templates, filters, etc?

It's actually a very good idea, and possibly one that could be developed in parallel (eg: a Node.js package). Beside having an app for this task, there could be an official repository storing a catalogue of all contributed resources, so contributors could make them available by making a PR there (a JSON or YAML based catalogue) — something along the lines of Sublime Text's [Package Control Default Channel](https://github.com/wbond/package_control_channel), which stores enough info to allow updating packages according to the version of ST the user has installed.

Yes, this would solve many current issues with keeping third party resources updated, and also promote discovery of new resources. Good thought.

**Comment by tarleb** [comment]
@ickc was the first to come up with that idea, IIRC.

Package managers are very tricky to get right, which is why I hope that we can somehow leverage @daurnimator's excellent [luarocks](https://luarocks.org): it's stable, well tested, and could save us from causing security problems. Furthermore, using a Lua-based system should prevent possible portability issues.

**Comment by jgm** [comment]
I think that this is just the kind of thing lua filters are good for, and we shouldn't complicate pandoc's parsers or markdown syntax when this is so easy to achieve with a filter.

**Comment by daurnimator** [comment]
> @daurnimator's excellent luarocks

Huh? It's not mine...

**Comment by tarleb** [comment]
@daurnimator argh, right. I was mixing up people who's Lua work I admire. Sorry.
