### ISSUE TITLE
Filter to create raw output overriding the writer.

### ISSUE THREAD

**Issue by manelio** [jgm/pandoc#4496]
Hi, guys.

I like very much this project, but I miss the possibility of filtering or customizing the writer.

For the 95% of my work, the features pandoc provide out of the box are enough. But sometimes I would like to full control the output.

I think it could be a game changer if pandoc provide some kind of block element that could be processed to create a raw output for the writer. Fenced divs are great candidates for this, but most of writer output is hardcoded.

Two examples:

1. Customized blocks to LaTeX

```
::: Warning
... some content ...
:::
```

Fenced divs are powerful, but what if I need, for example, a custom environment for showing the warning in LaTeX?

    \warningstart
    ... some content ...
    \warningend

Or, what if I want to add a title to the warning?

    ::: Warning
    title: Warning title
    ... some content ...
    :::

or

    ::: Warning: Warning title
    ... some content ...
    :::

what would be converted in

    \warningstart{Warning Title}
    ... some content ...
    \warningend

2. Widgets in LaTeX and HTML

```
::: pricingplans: Pricing Plans
plans:
    -
        name: Basic
        description: Description of basic plan
        price: 20.00
    -
        name: Silver
        description: Description of silver plan
        price: 50.00
    ...
:::
```

I would like to write my own output for LaTeX and HTML output formats.

Is there any way to manage this kind of situations?

If isn't, I think it could be a great addittion.

**Comment by mb21** [comment]
Please have a look at https://pandoc.org/MANUAL.html#generic-raw-attribute and https://pandoc.org/filters.html

Also, please ask questions like this on pandoc-discuss.
