### ISSUE TITLE
Make it easier to specify a prefered table format

### ISSUE THREAD

**Issue by nolange** [jgm/pandoc#4497]
Hello,

I would like to have a simple way to request a table format,
indented use is automatic formatting of markdown.
Currently this requires to basically disable everything else, which is cumbersume and error-prone, see the original discussion on the [Forum](https://groups.google.com/d/topic/pandoc-discuss/iYqejuaTcxo/discussion).

I wwould expect `-t markdown+pipe_tables` to give priority to pipe_tables, or at least the line below to not degenerate to raw html. An own switch like its done `--reference-links` would work aswell

```
echo '||||
|-----|-----|-----|
something rather long | and has a windy description | I cant bring my self to format this manually
pandoc|is so great that it can fix everything|
bug|but it wont currently|' | pandoc -t markdown-simple_tables-multiline_tables-grid_tables+pipe_tables -
```

**Comment by tbussmann** [comment]
> But I do think pipe tables should have priority over raw HTML when this can be done without loss of information. This should be a straightforward change. You'd still have to disable the other table formats.

To my understanding, the reason for the preference of HTML output in that example is that the internal representation of the input does contain column widths (which may be an error in the markdown reader). Converting that to a `pipe_table` would be treated as a loss of information (which is debatable in itself).
@nolange You would get the desired output by either disabling `-raw_html` altogether or by applying a filter to remove the width information like `--lua-filter=zerowidthtable.lua` with

```
function Table (elem)
  local zerowidths = {}
  for i = 1, #elem.widths do
    zerowidths[i] = 0
  end
  return pandoc.Table(elem.caption, elem.aligns, zerowidths, elem.headers, elem.rows)
end
```

**Comment by tbussmann** [comment]
> which may be an error in the markdown reader

it seems that is done on purpose, see https://github.com/jgm/pandoc/issues/2608#issuecomment-169082646
