### ISSUE TITLE
LaTeX parser should parse text in boxes

### ISSUE THREAD

**Issue by acesnik** [jgm/pandoc#4499]
I've been using Pandoc quite a bit for LaTex -> docx conversions. It works really well; thanks for working on this!

I have one little bug to report. When running Pandoc on Windows 10 to convert `.tex` to `.docx`, Pandoc misses `\mbox{}` blocks that are used to keep text from line breaking (useful for abbreviations and such).

Example:
```
\documentclass{article}
\begin{document}
text \mbox{missing text} more text
\end{document}
```

Pandoc script example:
`Pandoc.exe -o test.docx test.tex`

Expected result:
`text missing text more text`

Pandoc produces:
`text more text`

Version info:
```
Pandoc.exe 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```

**Comment by jkr** [comment]
The docx output part of this is irrelevant -- it's a question about the LaTeX reader. Right now, it reads `\mbox` as a `RawInline`. So `text \mbox{missing text} more text` produces `[Para [Str "text",Space,RawInline (Format "tex") "\\mbox{missing text}",Space,Str "more",Space,Str "text"]]`

Notice the `RawInline` has type `tex`, so it produces no output in non-TeX formats.

Question: what do you think pandoc should do when it encounters `\mbox`? Just ignore it and parse the text inside?

**Comment by acesnik** [comment]
In general, I think the reader should look inside boxes and read the `tex` code like the rest of the rest of the document. 

I would say horizontal boxes like `\mbox` should be processed starting in the same paragraph, and vertical boxes like `\minipage` should start in new paragraphs. ((Some good notes on the different types of boxes)[https://tex.stackexchange.com/questions/83930/what-are-the-different-kinds-of-boxes-in-latex/83936#83936].)

**Comment by mb21** [comment]
I can reproduce on pandoc 2.1.3

**Comment by jgm** [comment]
We could use the `rawInlineOr` combinator in the LaTeX reader to
preserve the mbox command as raw tex when the `raw_tex` extension
is enabled, and otherwise parse as some fallback; I'd suggest
something like a Span with class "mbox".
