### ISSUE TITLE
Hebrew vowel pointing offset by 1 character in pdf output

### ISSUE THREAD

**Issue by c-s-brown** [jgm/pandoc#4500]
I have a markdown file which is mostly in English with some words in Hebrew. The Hebrew words are rendered correctly from right to left, but the vowel pointing is offset by 1 character to the right.

I have installed pandoc using Homebrew on MacOS High Sierra

pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.1

The pandoc command I'm using is:
pandoc --pdf-engine=xelatex  --variable mainfont="Times New Roman" --variable sansfont=Arial test.txt -o test.pdf

I have attached test.txt and test.pdf which demonstrate the issue with a small test case.

[test.pdf](https://github.com/jgm/pandoc/files/1850774/test.pdf)

[test.txt](https://github.com/jgm/pandoc/files/1850776/test.txt)

**Comment by mb21** [comment]
That's an issue in XeLaTeX (maybe you can try updating it?). See https://pandoc.org/MANUAL.html#creating-a-pdf and maybe ask on tex.stackexchange...

**Comment by c-s-brown** [comment]
Thank you for the suggestion. Searching on tex.stackexchange identified a solution. Changing the main font to Lucida Grand works perfectly. Looks like a font issue.
