### ISSUE TITLE
Markdown blockquote not managed

### ISSUE THREAD

**Issue by Louson** [jgm/pandoc#4502]
# Issue
Markdown allows quotes with '>' which is not managed.

# Version
> $ pandoc -v
> pandoc 2.1.2
> Compiled with pandoc-types 1.17.3.1, texmath 0.10.1.1, skylighting 0.6

# Command line
> $ pandoc -t html example_quote.md -o example.html

# Markdown input
```markdown
This is normal text
> This is a quote

normal text again
```

# HTML output received
```html
<p>This is normal text &gt; This is a quote</p>
<p>normal text again</p>
```

# HTML output expected
Conforming to [markdown syntax](https://daringfireball.net/projects/markdown/syntax#blockquote)
```html
<p>This is normal text</p>
<blockquote><p>This is a quote</p></blockquote>
<p>normal text again</p>
```

**Comment by mb21** [comment]
Please see https://pandoc.org/MANUAL.html#pandocs-markdown and https://pandoc.org/MANUAL.html#extension-blank_before_blockquote

Please also ask questions like this on pandoc-discuss first.

**Comment by agusmba** [comment]
beat me to it by a few seconds!
http://pandoc.org/MANUAL.html#block-quotations

**Comment by Louson** [comment]
Ok, sorry for that. It appears that you also need a new line before the quote while you don't need it in markdown. The following input might need to give the right result :
```markdown
This is normal text
 > This is a quote

normal text again
```

What do you think ?

**Comment by agusmba** [comment]
As mb21 pointed out, it's well documented.

By default pandoc requires the new line before, but if you want to enforce regular markdown behavior in this case there is a flag for it. Just check the links we provided.
