### ISSUE TITLE
pandoc does not support the calculation LaTeX environment in Markdown

### ISSUE THREAD

**Issue by NickHu** [jgm/pandoc#4503]
The [`calculation` package](https://ctan.org/pkg/calculation) provides an environment for equational reasoning, which implicitly enters math-mode; however, pandoc is not aware of this.

On input (as Markdown, not LaTeX) `test.md`:

```markdown
---
header-includes:
  - \usepackage{calculation}
...

\begin{calculation}
a_b
\end{calculation}

\begin{equation}
a_b
\end{equation}
```

Result:

```
 ❯ pandoc -t latex test.md
\textbackslash{}begin\{calculation\} a\_b
\textbackslash{}end\{calculation\}
\begin{equation}
a_b
\end{equation}
```

Expected:

```
 ❯ pandoc -t latex test.md
\begin{calculation}
a_b
\end{calculation}

\begin{equation}
a_b
\end{equation}
```

As you can see, it gets confused by the `_`, interpreting it as Markdown instead of LaTeX. I believe a solution would be to add an entry to the map https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/LaTeX.hs#L1238.

Pandoc version information:

```
 ❯ pandoc -v
pandoc 2.1.2
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1.1, skylighting 0.6
Default user data directory: /home/nick/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
Would it be sufficient to parse the calculation environment as
display math?

**Comment by NickHu** [comment]
I think so. Inside the calculation environment, one can issue `\step{…}` to justify the next line of the equational proof, with the contents in text-mode, e.g.

```latex
\begin{calculation}
(a + b)^2
\step{Binomial expansion}
a^2 + 2 a b + b^2
\end{calculation}
```

It takes an optional argument (which is interpreted in math-mode) if you want something other than an equals sign, e.g.

```latex
\begin{calculation}
\pi
\step[\approx]{Rounding}
3
\end{calculation}
```

I think this would be handled the same way the `\text{…}` is handled in display-math mode.

**Comment by jgm** [comment]
So, we probably want to parse this into something like an aligned
environment (multiple lines) with the right-hand side reserved
for the justificatoins.  (Or should the justification be
on a separate line?)

**Comment by NickHu** [comment]
The justification is a separate line, like so

```
  line1
= { justification}
  line2
```

I don't understand what you mean by parsing into an `aligned` environment; I think the best thing to do is just stop pandoc from parsing it as Markdown.

**Comment by jgm** [comment]
> I don't understand what you mean by parsing into an `aligned` environment; I think the best thing to do is just stop pandoc from parsing it as Markdown.

Well, we could pass it through as raw LaTeX, but then it will just
disappear in formats that don't support raw LaTeX (e.g. Word, DocBook).
Better to parse it as a pandoc Math element, which can be converted
into many different formats.

**Comment by NickHu** [comment]
I see. But I don't think the functionality of the package is something you can easily emulate with standard LaTeX math constructs.

**Comment by jgm** [comment]
Nick Hu <notifications@github.com> writes:

> I see. But I don't think the functionality of the package is something you can easily emulate with standard LaTeX math constructs.

Right.  Well, we can pass it through as raw TeX, but this won't
appear in other formats.  Perhaps we could fake it by interspersing
TeX math with other constructions (Divs e.g.).

**Comment by NickHu** [comment]
Is it possible to parse it as some construct for which the writer can make the choice depending on whether it supports raw TeX or not?

**Comment by jgm** [comment]
Nick Hu <notifications@github.com> writes:

> Is it possible to parse it as some construct for which the writer can make the choice depending on whether it supports raw TeX or not?

No, but the parsing can be made sensitive to the `raw_tex` extension on
the reader.  So `-f latex+raw_tex` and `-f latex-raw_tex` can give
different results.

**Comment by jgm** [comment]
You can now simply do this -- I think it's an adequate solution:

````
```{=latex}
\begin{calculation}
(a + b)^2
\step{Binomial expansion}
a^2 + 2 a b + b^2
\end{calculation}
```
````
