### ISSUE TITLE
Misalignment of beamer lists (was: Numbered example lists look awful with many beamer themes)

### ISSUE THREAD

**Issue by memeplex** [jgm/pandoc#4505]
```
---
title: Title
theme: Berlin
---

# Slide

(@) One
(@) Two
```

Then you get

![2018-03-27-161345_181x102_scrot](https://user-images.githubusercontent.com/2845433/37989538-0b9656b2-31da-11e8-9418-24c8c4c8b7a3.png)

**Comment by memeplex** [comment]
A bit better, but still not pretty, with Copenhagen

![2018-03-27-161629_130x100_scrot](https://user-images.githubusercontent.com/2845433/37989581-37f62282-31da-11e8-99a7-0a214bf39e5d.png)

I think surrounding parenthesis should be omitted for beamer.

**Comment by memeplex** [comment]
Here is an ugly workaround

```
`\setbeamertemplate{items}[default]`{=tex}

(@) One

`\setbeamertemplate{items}[circle]`{=tex}

(@) Two
```

**Comment by memeplex** [comment]
Also notice that when the number has two digits you get this:

![2018-03-27-163555_68x222_scrot](https://user-images.githubusercontent.com/2845433/37990525-f0a98dc6-31dc-11e8-8231-2ff27fa0f895.png)

I think beamer is assuming no more than two digits here, so not only the closing parenthesis will be concealed but, worst, the second digit will be also.

**Comment by jgm** [comment]
As long as some themes look good with the surrounding parens,
I'd be against omitting them.

It should be easy to write a small lua filter that changes
the list format style on all ordered lists.  This ought to
be 3 or 4 lines at most.

**Comment by memeplex** [comment]
Good point, but just take into consideration that *most* themes look bad.

**Comment by jgm** [comment]
You don't have to use the `()` form for lists, you know!
(Even for example lists -- any delimiter that works for ordered lists will work.)

**Comment by memeplex** [comment]
Ahhh ok that changes things a bit. I think the docs are a bit misleading here since all examples use the `(@)` prefix.

Now, is there any way to avoid additional markers altogether? `@)`, `@.` will add a `)` or a `.` respectively. `@` doesn't signal that what follows is a list item.

**Comment by memeplex** [comment]
Mmmm I think the problem is worse than that.

For example, by adding the `[.1]` specification to the enumerate environment the layout of beamer lists (and not only the ones produced from example lists) is changed:

* With `[.1]`:

![2018-03-29-162535_351x128_scrot](https://user-images.githubusercontent.com/2845433/38109312-1ed8d2fa-336e-11e8-976e-783f79c56343.png)

* Without `[.1]`:

![2018-03-29-162551_350x141_scrot](https://user-images.githubusercontent.com/2845433/38109328-28da66d8-336e-11e8-909b-1b99294332ad.png)

Is mapping some kind of list indicator (say `<n>.`) to the latex default (ie. without further specification) too problematic?

**This only happens for beamer**.

**Comment by memeplex** [comment]
Maybe something changed here since the last upgrade of my system since I'm now unable to reproduce the misalignment issue anymore, therefore I'm closing this and opening a new issue to request that `n.` style lists map to the default (that is, without a `[1.]` specifier in the latex output), at least in beamer, since it looks bad with many themes and there is no way of getting the usual looks & feelz.
