### ISSUE TITLE
tabular custom columns in markdown source not recognised as latex

### ISSUE THREAD

**Issue by mathematicalcoffee** [jgm/pandoc#4509]
Pandoc 2.0.5.

Defining a custom column type in a tabular causes it not to be recognised by pandoc and escaped instead. (When embedding latex in a Markdown file).
Here is an example *.md file

```
---
title: "asdf"
header-includes:
    - \usepackage{array}
---

\newcolumntype{b}{>{\centering\arraybackslash}p{1cm}}
\newcolumntype{B}{>{\centering\arraybackslash}p{1cm}}

\begin{figure}
\centering 
\begin{tabular}{@{}rBBBBBBB@{}}
one & two & three & four & five & six & seven & eight \\
\end{tabular}
\caption{Foo}
\label{fig:testfigure}
\end{figure}

```

Running `pandoc -t latex test.md` gives

```
\newcolumntype{b}{>{\centering\arraybackslash}p{1cm}}\newcolumntype{B}{>{\centering\arraybackslash}p{1cm}}

\textbackslash{}begin\{figure\} \centering 
\textbackslash{}begin\{tabular\}\{@\{\}rBBBBBBB@\{\}\} one \& two \&
three \& four \& five \& six \& seven \& eight \textbackslash{}
\textbackslash{}end\{tabular\}

\caption{Foo}
\label{fig:testfigure}
```

The figure is escaped with `\textbackslash`.

However changing the column type to `b` rather than `B` works:

```
\newcolumntype{b}{>{\centering\arraybackslash}p{1cm}}\newcolumntype{B}{>{\centering\arraybackslash}p{1cm}}

\begin{figure}
\centering 
\begin{tabular}{@{}rbbbbbbb@{}}
one & two & three & four & five & six & seven & eight \\
\end{tabular}
\caption{Foo}
\label{fig:testfigure}
\end{figure}
```

I suspect it's because "b" is an accepted column type in tabularx while "B" is not, and it seems the code that recognises latex tables only allows specific column types ([`parseAligns` in `LaTex.hs`](https://github.com/jgm/pandoc/blob/62c395dafa467ea760cdc938993ef61379e07ace/src/Text/Pandoc/Readers/LaTeX.hs#L2405)).

It's too much to expect the latex reader to parse a `\columntype` and do the appropriate translations I think. However it could be good if whatever bit of code in the Markdown reader would know that this stuff is acceptable LaTeX and to leave it alone (like it does if you don't have custom column types).

It's also no big deal if this is not fixed and it is simply a restriction that you shouldn't use custom column types when trying to embed latex; in that case I leave this bug here as a google target for future people with this problem. Workarounds are to define the column type as 'X', 'b', or some other letter already used in the tabular/tabularx packages (though then you are overwriting it!), or to simply manually put in the column definitions.

**Comment by mb21** [comment]
Can you try with the latest pandoc release?

**Comment by mathematicalcoffee** [comment]
No. I am in the final weeks of preparing my PhD thesis for submission [using a precarious arrangement of makefile, pandoc, knitr, rmarkdown, ...] and dare not change any versions or the whole house of cards will collapse. Perhaps you could? I have provided a complete and minimal working example.

**Comment by mb21** [comment]
With pandoc 2.1.2 I get:

    \newcolumntype{b}{>{\centering\arraybackslash}p{1cm}}
    \newcolumntype{B}{>{\centering\arraybackslash}p{1cm}}

    \begin{figure}
    \centering 
    \begin{tabular}{@{}rBBBBBBB@{}}
    one & two & three & four & five & six & seven & eight \\
    \end{tabular}
    \caption{Foo}
    \label{fig:testfigure}
    \end{figure}

So this seems to be fixed.
