### ISSUE TITLE
Support "lhs" as name for literate Haskell

### ISSUE THREAD

**Issue by ad-si** [jgm/pandoc#4510]
When converting markdown to markdown+lhs following 2 variants should yield the same output:

~~~md
``` {.literate .haskell}
main = putStr "Hello World!"
```
~~~

~~~md
```lhs
main = putStr "Hello World!"
```
~~~

should both yield

~~~
> main = putStr "Hello World!"
~~~

**Comment by jgm** [comment]
The behavior is exactly as documented in the manual, isn't it?

> In Markdown [+lhs] output, code blocks with classes `haskell` and `literate`  will be rendered using bird tracks, and block quotations will be indented one space, so they will not be treated as Haskell code.

Nothing is said here about `lhs`.  Your code block with `lhs` is just a regular code block.

**Comment by jgm** [comment]
I think it's actually quite useful to have a way to do *both* of these things in a Markdown document:

1.  Insert some literate Haskell, which will be treated as code in markdown+lhs output.
2. Insert a regular code block which happens to display some literate Haskell code, and which will be highlighted as such in output formats that do highlighting.

**Comment by ad-si** [comment]
> I think it's actually quite useful to have a way to do both of these things in a Markdown document:

Yeah, I guess you're right!

It just bugs me, that's not really correct markdown, or rather markdown which other parsers can easily handle. E.g. Commonmark will do this:

~~~
```{.literate .haskell}
etst
```

<pre lang="{.literate"><code>etst
</code></pre>
~~~

Which is not really what anyone wants, who writes this code...

Other parsers completely mess it up: https://github.com/gettalong/kramdown/issues/503

It would be cool if there was a more standard compliant way to differentiate between Haskell code which gets displayed and code which gets executed ...

**Comment by jgm** [comment]
You could use a very simple lua filter to change code blocks
with class `lhs` to `literate haskell`, and use this when you're
converting using pandoc...

**Comment by ad-si** [comment]
Well, for the time being I use this workaround to execute / compile the Haskell:

```shell
cat document.md \
| sed 's/```haskell/```{.literate .haskell}/g' \
| pandoc \
  --from markdown \
  --to markdown+lhs \
  --output temp.lhs \
| stack runhaskell \
  --resolver lts-11.1 \
  --package cmdargs \
  -- \
  temp.lhs \
; rm -f temp.lhs
```
Not glamorous, but get's the job done =P.
I'll switch to a Haskell pipeline for my blog in the future (shake + pandoc probably), then the lua filter might be a good idea. Thanks for the tip.
