### ISSUE TITLE
header-includes does not recognize input of TeX file

### ISSUE THREAD

**Issue by Konfekt** [jgm/pandoc#4514]
The command `MakeOuterQuote{"}` by `csquotes` is not recognized if given inside a TeX file included by the header, for example

```
lang:                 pt
babel-lang:           portuguese
header-includes:      |
    \input{$HOME/header.tex}
...

"Test"
```
and `$HOME/header.tex` containing
```
    \RequirePackage{csquotes}
    \MakeOuterQuote{"}
```
does not show the angular quotes used in `portuguese`. However, replacing
```
    \input{$HOME/header.tex}
```
by
```
    \RequirePackage{csquotes}
    \MakeOuterQuote{"}
```
does correctly show the angular quotes.

**Comment by jgm** [comment]
Are you sure you can use environment variables
like `$HOME` in this context?  Try replacing with
the full path, or moving the header to the  working
directory.

**Comment by Konfekt** [comment]
Yes, I can, I checked the TeX docs. (However, `~/` is not allowed.) 

The file `$HOME/header.tex` is injected just fine, all other commands have their effect . However `csquotes` not. It's mysterious.

**Comment by Konfekt** [comment]
A wild guess: If pandoc detects `csquotes` in the header, then it does not replace the double quotes by TeX quotes. However, if `csquotes` is loaded by an included TeX file, then this check files and the TeX quotes are used anyway.

**Comment by Konfekt** [comment]
Regarding the manual, which says
```
... csquotes will be used for typography if added to the template or included in any header file.
```
 this seems at least plausible.

**Comment by Konfekt** [comment]
If this is indeed what happens, then one could replace this issue by one that asks about these kind of checks including the TeX files included in the header.

**Comment by jgm** [comment]
Yes, the manual is misleading, I think.  We check for
`\usepackage{csquotes}` in the template and in the header-includes
fields, but it won't be found if it's included indirectly via
`\input`, for example.

**Comment by Konfekt** [comment]
Ok, so the manual should be more exact in what the check does. That said, I would be glad if the check could read in the included files as well.
