### ISSUE TITLE
ms writer references: Slash and Links

### ISSUE THREAD

**Issue by teoric** [jgm/pandoc#4515]
Consider the following example:
```markdown
---
title: Test
author: Some One
bibliography: test.bib
link-citations: true
references:
- id: cit/1
  type: book
  author:
  - family: Braune
    given: Wilhelm
  issued:
  - year: 2004
  title: Althochdeutsche Grammatik I
  publisher: Niemeyer
  publisher-place: Tübingen
  edition: 15\. Aufl., bearbeitet von Ingo Reiffenstein
  language: de-DE

- id: cit/2
  type: book
  author:
  - family: Braune
    given: Wilhelm
  issued:
  - year: 1904
  title: Über die Einigung der deutschen Aussprache; akademische Rede zur Feier des
    Geburtsfestes des höchstseligen Grossherzogs Karl Friedrich am 22. November 1904
    bei dem Vortrag des Jahresberichts und der Verkündung der akadem. Preise
  title-short: Über die Einigung der deutschen Aussprache
  publisher: Hörning
  publisher-place: Heidelberg
  language: de-DE
...


blah [cf. @cit/1 blah blah].

@cit/2 blah blah
```

## Bib links are broken

When run through
```bash
pandoc  -s -F pandoc-citeproc -t ms  bib-test2.md
```
, this produces the following links:
```nroff
.pdfhref L -D "ref-cit/1" -A "\c" \
 -- "2004"
.pdfhref L -D "ref-cit/2" -A "\c" \
 -- "1904"
```
However, internal PDF links cannot contain a slash. For bib keys with slash,the slash should be substituted, e.g. by `+`.
```bash
pandoc  -s -F pandoc-citeproc -t ms  bib-test2.md| groff -Kutf8 -Tpdf -ms -mspdf > bib-test2.pdf
```
gives
```
PDF Dict Key '[' does not start with '/'
```
(Compiling with `-Tps` works; however, it only works as long as there are no link targets yet, see immediately below.)

## Bib Links are dead
Moreover, the Links are created, but the targets are not. I.e., the Links point nowhere. The following is **missing**:
```
.pdfhref M "ref-cit+1" \" at reference 1
.pdfhref M "ref-cit+2" \" at reference 2
```
(substituting `/` with `+`, as suggested above)

> Anyway, happy holidays and thanks for your good work!

**Comment by jgm** [comment]
@teoric the links still don't seem to work for me, but the ms output looks okay. Can you take a look and let me know if you spot a problem?

**Comment by teoric** [comment]
Thank you very much for looking into this!  I can try, but my Haskell is probably to bad to fully appreciate the code. Could you send me an `ms` document generated with the current version?  Otherwise I can try whether I manage to build pandoc.
(I managed to fix this with the following Lua filter for my documents:
```lua
{
    Link = function (cit)
      -- sanitize Link ID
      -- protect against https://github.com/jgm/pandoc/issues/4515
      if FORMAT == "ms" then
        if string.sub(cit.c[3][1], 1, 1) == "#" then
          cit.c[3][1] = string.gsub(cit.c[3][1], '/', "+")
        end
        return cit
      end
    end,
}
```
(Manipulating the `el.id` of `Cite`s and the `div.c[1][1]` of `Div`s seemed to be unnecessary.)

**Comment by teoric** [comment]
Thank you very much for looking into this!  I can try, but my Haskell is probably to bad to fully appreciate the code. Could you send me an `ms` document generated with the current version?  Otherwise I can try whether I manage to build pandoc.
(I managed to fix this with the following Lua filter for my documents:
```lua
{
    Link = function (cit)
      -- sanitize Link ID
      -- protect against https://github.com/jgm/pandoc/issues/4515
      if FORMAT == "ms" then
        if string.sub(cit.c[3][1], 1, 1) == "#" then
          cit.c[3][1] = string.gsub(cit.c[3][1], '/', "+")
        end
        return cit
      end
    end,
}
```
(Manipulating the `el.id` of `Cite`s and the `div.c[1][1]` of `Div`s seemed to be unnecessary.)
But this was only the syntax part, not the linking!

**Comment by teoric** [comment]
Thank you!
For me, this works; how did you typeset it?
I used:
```sh
groff -Dutf8 -ms -Tpdf test.ms > test.pdf
```
and
```
pdfroff -Dutf8 -ms -mspdf test.ms > test.pdf
```
(Note that `-mspdf` is necessary in the second case; without it, the link text will be dropped.)
In both cases the links work; with `pdfroff` they seem to be a bit off the desirable position, but that seems to be normal.

**Comment by jgm** [comment]
I was just using pandoc's output to PDF.
This runs pdfroff with `-ms -mpdfmark -e -t -k -KUTF-8 -i --no-toc-relocation`.
Should this be changed?

**Comment by teoric** [comment]
Using
```sh
pdfroff -ms -mpdfmark -e -t -k -KUTF-8 -i --no-toc-relocation < test.ms> test.pdf
```
leads to working links as well for me (groff 1.22.3 and 1.22.4.rc2).  (I used `-mspdf`, but Pandoc probably only uses generic pdfmark commands, so this was not necessary.)
Personally, I prefer to use the PDF device because it is a little more Unicode-friendly and gives better results with Unicode in Bookmarks. (There is a warning, but non-ASCII characters like German umlauts get through well; with pdfroff, i.e. the PostScript device, they are butchered to numbered escapes `[u____]`.)
The main advantage of `pdfroff` is that it multiple runs (like LaTeXmk), isn't it?  Does Pandoc use anything where this is necessary, e.g. for references?

**Comment by jgm** [comment]
teoric <notifications@github.com> writes:

> The main advantage of `pdfroff` is that it multiple runs (like LaTeXmk), isn't it?  Does Pandoc use anything where this is necessary, e.g. for references?

I'm pretty sure I used it for some good reason, but it was a while
back.  Possibly table of contents, or bookmarks?

**Comment by jgm** [comment]
I'll consider this issue closed, in any case.
