### ISSUE TITLE
pdf bookmark nesting errors

### ISSUE THREAD

**Issue by casperdcl** [jgm/pandoc#4519]
`foo.md`:

```markdown
---
subparagraph: true
toc: true
header-includes:
 - \usepackage{titlesec}
---

# one

## one.two

# two

## two.one
```

```bash
$ pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
$ pandoc -o foo.pdf foo.md
```

produces a correct ToC but the pdf bookmarks are nested as:

- one
  - one.two
    - two
      - two.one

**Comment by casperdcl** [comment]
also an issue in pandoc 2.1

**Comment by mb21** [comment]
This is probably a [problem with pdflatex](https://tex.stackexchange.com/questions/57284/pdf-contains-incorrect-bookmark-hierarchy)... can you reproduce with the newest `pdflatex` and also without `titlesec`?

**Comment by jgm** [comment]
It appears that if you move the `\usepackage{titlesec}` up before `\usepackage{hyperref}`, the problem goes away.  So, you're going to have to use a custom template here, since `header-includes` always go at the end of the preamble.

**Comment by casperdcl** [comment]
Interesting. The odd thing is if you for example remove `## two.one` then the pdf bookmarks are fine.

I've resolved the issue by adding `- \usepackage{bookmark}` after `- \usepackage{titlesec}`, which doesn't require altering the template.

Cheers
