### ISSUE TITLE
Unnecessary table header overlapping

### ISSUE THREAD

**Issue by dylan-chong** [jgm/pandoc#4520]
f.md

```markdown
| aaaaa aaaa                                                                                                  | cccccccccc   | bbbbbbbb   | aaaaaaaaaaa                                                      |
| ----------------------------------------------------------------------------------------------------------- | ------------ | ---------- | ---------------------------------------------------------------- |
| [aaaaaaa](aaaa://aaaaaaaaaa.aaa.aaaaaa.aaaa.aa/aaaaaaa/aaaaa/aaaaaaa/aaaaa-aaaaaaaaa#aaaaaaaaaaaaa)         | aaaa         | aaa        | aaa aaaa aa aaaaa -- aaaaa, aaaaa, aaa                           |
| [aaaaaaaaaaaaa](aaaa://aaaaaaaaaa.aaa.aaaaaa.aaaa.aa/aaaaaaa/aaaaa/aaaaaaa/aaaaa-aaaaaaaaa#aaaaaaaaaaaaa)   | aaaa         | aaa        | aaaaaaaaa aaa aaaaaa aaaa aaa aaaaaaaaaa aaaa (a.a. \'aaaaa\')   |
| [aaaaaaaaaaa](aaaa://aaaaaaaaaa.aaa.aaaaaa.aaaa.aa/aaaaaaa/aaaaa/aaaaaaa/aaaaa-aaaaaaaaa#aaaaaaaaaaa)       | aaaa         | aaa        | aaa aaaa aa aaaaaaaaaaa (a.a. \'aaaa\')                          |
| [aaaaaaaaaa](aaaa://aaaaaaaaaa.aaa.aaaaaa.aaaa.aa/aaaaaaa/aaaaa/aaaaaaa/aaaaa-aaaaaaaaa#aaaaaaaaaa)         | aaaa         | aa         | aaaaaa aaa aaaaaaaaaaaa aaaaaa (a.a. \'aaaa aaaaaaaa\')          |
| [aaaaaaaaaa](aaaa://aaaaaaaaaa.aaa.aaaaaa.aaaa.aa/aaaaaaa/aaaaa/aaaaaaa/aaaaa-aaaaaaaaa#aaaaaaaaaa)         | aaaaaaa      | aa         | a aaaaaaa aaaaa aaaaaaaaaa aaaa aaa aaaaa (a.a. aa)              |
```

convert: `pandoc f.md -o f.pdf`

expected result:

none of the table cells should overlap

actual result: 

<img width="794" alt="screen shot 2018-04-03 at 12 14 50 pm" src="https://user-images.githubusercontent.com/17482349/38222405-b072084e-3738-11e8-86aa-78ad469e9fb3.png">

**Comment by jgm** [comment]
Please see the User's Guide:

> If a pipe table contains a row whose printable content is wider than the
> column width (see --columns), then the cell contents will wrap, with the
> relative cell widths determined by the widths of the separator
> lines. (In this case, the table will take up the full text width.) If no
> lines are wider than column width, then cell contents will not be
> wrapped, and the cells will be sized to their contents.

You need to either specify a larger `--columns` width or
use smaller header lines.

**Comment by dylan-chong** [comment]
Ah maybe i misinterpreted the documentation. 

That documentation does not make clear that it is the number of dashes in each of the columns of the separate lines that defines the width, not the actual width of the column. Perhaps we could reword the documentation to make the above points clear?

**Comment by jgm** [comment]
We say: "with the relative cell widths determined by the widths of the
separator lines."  I imagined that "separator lines" would be clear,
though it isn't explicitly defined. Is there some alternative wording
that would have been less confusing?

**Comment by jgm** [comment]
Dylan Chong <notifications@github.com> writes:

>> with the relative cell widths determined by the widths of the
> separator lines.
>
> Hmm, I think this is a little bit misleading. From my understanding, a separator line is something like line 2 in here:

By "separator lines" I meant the lines of dashes.  (I thought the plural would make that clear, but we should be more explicit.)

**Comment by mb21** [comment]
@dylan-chong what do you think of the wording in https://github.com/jgm/pandoc/pull/4630 ?
