### ISSUE TITLE
CommonMark writer: small caps are rendered with <span>, even without raw_html

### ISSUE THREAD

**Issue by quasicomputational** [jgm/pandoc#4528]
```
$ cat test2.tex
This has \textsc{small caps} text.
$ pandoc -f latex -t commonmark-raw_html test2.tex 
This has <span class="smallcaps">small caps</span> text.
```

I grepped the CommonMark spec and it seems that `<span>` will be interpreted as raw HTML, which seems against the user's stated intent.

I think that the Markdown writer's behaviour, which is to capitalise the small-caps span, is much better in this case:

```
$ pandoc -f latex -t markdown_strict-raw_html test2.tex 
This has SMALL CAPS text.
```

**Comment by mb21** [comment]
So use the markdown writer instead of the commonmark writer if you prefer that behavior. How latex is parser has nothing to do with the commonmark spec...

**Comment by quasicomputational** [comment]
Respectfully, I disagree, and I would request that this issue be re-opened.

You're exactly right that the LaTeX reader has nothing to do with the CommonMark spec! Small caps are represented in Pandoc's internal AST; I chose LaTeX as an example purely because it is a convenient syntax. Here is the same behaviour with HTML input:

```
$ echo '<span style="font-variant: small-caps">small caps</span>' | pandoc -f html -t markdown_strict-raw_html
SMALL CAPS
$ echo '<span style="font-variant: small-caps">small caps</span>' | pandoc -f html -t commonmark-raw_html
<span class="smallcaps">small caps</span>
```

Why do I want this? Because the `<span>` is semantically opaque to CommonMark, and is tied to HTML-type output. If some other processor is transforming CommonMark to LaTeX, then the small caps here become lowercase text, which is a worse outcome than the small caps becoming normal caps. If the user specifically requests not to include raw HTML, that should be respected.

**Comment by mb21** [comment]
I'm sorry, I misread your original post, agreed.
