### ISSUE TITLE
Quoted sentence not included when exporting to powerpoint

### ISSUE THREAD

**Issue by smu** [jgm/pandoc#4532]
Consider the following example:

```
# Slide one
this is a 'test'
```

When exporting this to beamer, the sentence "this is a 'test'" is shown as expected in the resulting pdf.
When exporting to powerpoint (`pandoc test.md -o test.pptx`), however, only the first part ("this is a") is shown on the slide. The text between the quotes and also the quote symbols are not exported to powerpoint.

pandoc version: 
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2

**Comment by jkr** [comment]
I assume it's because of changes in default smart-quoting, and the writer not handling that correctly. It should be pretty easy to fix.

**Comment by jgm** [comment]
@jkr it looks like the inline writer in Text.Pandoc.Writers.Powerpoint.Presentation is missing a clause for `Quoted`.

Suggestion:  don't use a catchall match like `inlineToParElems _ = return []`; without this, the compiler would have caught this problem.

**Comment by jkr** [comment]
Yep -- remnant from incremental development.
