### ISSUE TITLE
Incorrect parsing paragraphs in <div>

### ISSUE THREAD

**Issue by dataopt** [jgm/pandoc#4534]
I am using Pandoc version 2.1.3 on Mac El Capitan.

Consider the markdown file called ``simple.md``:
```
<div class="para">
First paragraph.

Second paragraph.
</div>
```
``pandoc simple.md -t native`` gives, as expected, the following:
```
[Div ("",["para"],[])
 [Para [Str "First",Space,Str "paragraph."]
 ,Para [Str "Second",Space,Str "paragraph."]]]
```
However, changing ``simple.md`` to
```
<div class="para">
First paragraph.

Second paragraph. </div>
```
``pandoc simple.md -t native`` gives
```
[Div ("",["para"],[])
 [Para [Str "First",Space,Str "paragraph."]
 ,Plain [Str "Second",Space,Str "paragraph."]]]
```
Shouldn't it be ``Para`` instead of ``Plain`` in the last line?  If parsed as ``Plain``, css for ``<p>`` won't be applied to the second paragraph.

**Comment by jgm** [comment]
I think the existing behavior is good.  It allows an author to
get output like

    <div>foo</div>

if they want it, while also allowing them to put paragraphs
inside divs without adding an extra blank line at the very end.

**Comment by jgm** [comment]
Probably anything we do is going to be unintuitive in some cases.
But I think the present system works well enough.

**Comment by dataopt** [comment]
Ok then. I'll close the issue.
