### ISSUE TITLE
Markdown image `width` option changes h:w ratio in tex file

### ISSUE THREAD

**Issue by gaow** [jgm/pandoc#4537]
#I'm on version 2.1.3. Here is a minimal working example in markdown, 

```md
![text](image.jpg){ width=60% }
```

converted to tex via:

```
pandoc -s -o test.tex test.md
```

The output tex file is:

```
\begin{figure}
\centering
\includegraphics[width=0.6\textwidth,height=\textheight]{image.jpg}
\caption{test}
\end{figure}
```

The problem here is that `height` now got added automatically and is set to `textheight`. Such setup distorted the image. Earlier version of `pandoc` do not have this problem.

My `pandoc` version:

```
$ pandoc --version
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2
Default user data directory: /home/gaow/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Thanks a lot!

**Comment by mb21** [comment]
Are you using the default template? I think this was added in https://github.com/jgm/pandoc/commit/1193c1a505aac616d41a7b1c61c0cde07d2560d2 which mentions having `keepaspectratio` in the template.

**Comment by jgm** [comment]
If you're not using `-s`, you're generating a document fragment, not using the template at all.

**Comment by gaow** [comment]
Thank you @jgm. In my actual application (not the minimal working example above) I did use `-s` yet the problem was the same. I've revised my example above to include `-s`. The relevant tex content is still:

```
\begin{figure}
\centering
\includegraphics[width=0.6\textwidth,height=\textheight]{image.jpg}
\caption{text}
\end{figure}
```

that is, it forces a 0.6:1 ratio on my image.

**Comment by mb21** [comment]
That should be fine, as long as you also have the following (again, included in the most recent default template):

```
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```

**Comment by gaow** [comment]
Ahh now I  see the problem -- somehow this default template did not kick in for my updated `pandoc`. Manually loading it worked for me, so this is indeed the current default as expected. Thanks @mb21 for sharing those lines!
