### ISSUE TITLE
Preserving empty paragraphs

### ISSUE THREAD

**Issue by Lord-Evil** [jgm/pandoc#4540]
What am I doing wrong? Can't get it to work..
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2
![image](https://user-images.githubusercontent.com/3912626/38473824-452f4a24-3bd9-11e8-8ec9-ec47de2020f6.png)

**Comment by jgm** [comment]
The empty_paragraphs extension affects `markdown` but not `gfm` (currently).
Btw, please don't ask questions here. Ask them on pandoc-discuss, as requested in CONTRIBUTING.md.

**Comment by Lord-Evil** [comment]
@jgm Well, it doesn't work for `markdown` as well, so it must be a bug.
![image](https://user-images.githubusercontent.com/3912626/38784983-1d2a869a-415d-11e8-9d81-543c04749083.png)

**Comment by jgm** [comment]
Maybe it's a documentation bug.  I don't think it was ever intended to work with markdown output, because there's no way to represent an empty paragraph in markdown.

**Comment by Lord-Evil** [comment]
Actually, there is way to represent it
![image](https://user-images.githubusercontent.com/3912626/38851289-84daab0c-4258-11e8-9d34-5042110f94ba.png)
Replace empty paragraphs with &nbsp; or actual \xc2 byte

**Comment by jgm** [comment]
I suppose one could do that, though it's a change in meaning
(empty /= contains one nonbreaking space).

**Comment by Lord-Evil** [comment]
Can this be implemented in next version? Parameter that can replace empty paragraph with user defined string?
