### ISSUE TITLE
discrepancy re datadir on cygwin

### ISSUE THREAD

**Issue by VladimirAlexiev** [jgm/pandoc#4549]
pandoc 2.1.3 on cygwin 64bit.
- `pandoc -v` reports
Default user data directory: `C:\Users\<USER>\AppData\Roaming\pandoc`
- `--bash-completion` reports
`datadir="C:\pandoc\.stack-work\install\415d48d7\share\i386-windows-ghc-8.2.2\pandoc-2.1.3"`

#2749 says to edit the path in the `--bash-completion` output. But https://pandoc.org/MANUAL.html#options says to feed it directly to bash.

Would be good if the two paths were the same

**Comment by jgm** [comment]
This is not a bug.  The datadir in `--bash-completion` is only used for
one thing: auto-completion of `--print-default-data-file`.  So it
points to the system data directory, where the default data files are
kept. This is distinct from the user data directory, where you can
put user overrides.

**Comment by jgm** [comment]
Maybe there is a problem, though not exactly the one you thought.
I noticed that the packaged macOS binary's --bash-completion gives this for datadir:
```
datadir="/Users/jgm/src/pandoc/.stack-work/install/x86_64-osx/lts-10.10/8.2.2/share/x86_64-osx-ghc-8.2.2/pandoc-2.1.3"
```
That's my local build directory, which is obviously not what we want here.

**Comment by VladimirAlexiev** [comment]
@jgm There is also a problem on cygwin: after installation, there is no folder
`C:\pandoc\.stack-work\install\415d48d7\share\i386-windows-ghc-8.2.2\pandoc-2.1.3`
(in fact no folder `C:\pandoc` either).
How can I check where is its default data folder to report it to you?

Cheers!

**Comment by jgm** [comment]
If pandoc was compiled with embed_data_files flag, as it is
in the binaries we supply, then there's no system data directory,
as all the data files are baked into the binary.

**Comment by VladimirAlexiev** [comment]
I know I'm asking too much, but would it then be possible for `--bash-completion` to use the baked-in data files when `embed_data_files`? Rather than `find` that section of the script should be hard-coded by the `embed_data_files` process.

Thanks for an excellent tool!
