### ISSUE TITLE
ms writer, font handling for strong, emph, code within strong, emph, header

### ISSUE THREAD

**Issue by teoric** [jgm/pandoc#4552]
The `ms` writer of pandoc 2.1.3 does not handle font changes too well.  E.g.
```sh
echo 'abc **de*fgh*** ghi' | pandoc -t ms
```
produces
```nroff
.LP
abc \f[B]de\f[BI]fgh\f[B]\f[] ghi
```
This uses `\f[]` as a normalizer, but it is an alias for ‘previous font’, so the chain is: **Regular → **Bold** → **Bold Italic** → **Bold** → previous font, i.e. **Bold Italic**, i.e. `ghi` is typeset in this wrong font. 

The easiest way to fix this, in my opinion, would be to always insert a `\f[R]`before the next-to-last change. This is a hack, but anything else would have to be done on the `troff` level (probably with the `\n[.sty]` register, and I have not tested whether it works). The hack even works in headers, which in the current configuration are always bold.
The insertion can be implemented in a Lua filter as follows; it might get into problems if fonts are stacked more than two levels deep, but I assume this is not so probable.
```lua
local walker = {
  -- just to avoid duplication of embolden_emph
  Strong=pandoc.walk_inline,
  Emph=pandoc.walk_inline,
  Header=pandoc.walk_block,
}

function embolden_emph(elem)
  if FORMAT == "ms" then
    return walker[elem.t](
      elem,
      {
        Emph = function (el)
          local ret = List:new({
              pandoc.RawInline("ms", "\\f[BI]"),
          })
          ret:extend(el.c)
          -- interesting line:
          ret:extend({
              pandoc.RawInline("ms", "\\f[R]\\f[B]"),
          })
          return pandoc.Span(ret)
        end
    })
  end
end

function emphasize_bold(elem)
  if FORMAT == "ms" then
    return walker[elem.t](
      elem,
      {
        Strong = function (el)
          local ret = List:new({
              pandoc.RawInline("ms", "\\f[BI]")
          })
          ret:extend(el.c)
          -- interesting line:
          ret:extend({
              pandoc.RawInline("ms", "\\f[R]\\f[I]"),
          })
          return pandoc.Span(ret)
        end
    })
  end
end

return {
    Header = embolden_emph,
    Strong = embolden_emph,
    Emph = emphasize_bold,
}
```

## Applies also to constant width

This might go into its own issue, but it is deeply linked.  The **problem with font change** also occurs with constant width (`code`), where the font stays constant if embedded in italics, and there is a **font name mistake** there: **Constant Bold** is `CB`, not `BC` as currently.  The approach of inserting an `\f[R]` should help there, too.
```sh
echo 'abc *de`fgh`* ghi' | pandoc -t ms
```
gives
```nroff
.LP
abc \f[I]de\f[CI]fgh\f[I]\f[] ghi
```
with constant width ghi.
```sh
echo 'abc **de`fgh`** ghi' | pandoc -t ms
```
gives
```nroff
.LP
abc \f[B]de\f[BC]fgh\f[B]\f[] ghi \" ← BC should be CB, but the problem is the same
```
where font `BC` is not found (as it should be `CB`), but you can see that it needs both same fix of inserting `\f[R]` before the last `\f[B]` and `\f[I]`, respectively.

## headers

As said above, headers are always bold according to `ms`'s definition. It would make sense, in my opinion, to treat them as bold text, as I did above in the Lua filters.  Otherwise italic text in headers is typeset non-bold:
```sh
echo '# abc *defgh* ghi' | pandoc -t ms
```
gives (shortened by two lines):
```nroff
.SH 1
abc \f[I]defgh\f[] ghi
```
You can see that this uses **Italic** within bold text, not **Bold Italic**.  Using the fix in the above Lua filter works, though the `\f[R]` is probably not needed. (If I remember correctly, ms resets the font itself at the beginning of the next paragraph, anyway, so the `\f[R]` will never be ‘popped’.)

## Sorry
Sorry for the lengthy report.

**Comment by jgm** [comment]
The writer currently keeps track of the font features used at any point, so it would be easy to have it use `\f[R]` instead of `\f[]`.  I just didn't understand correctly how `\f[]` works. We could probably also figure out a way to change things so that pandoc knows that it's in a header.

**Comment by teoric** [comment]
Imagine Font management is a two-item stack containing the previous and the current font. `\f[]` pops the last item (i.e. the current font). This is why I inserted the `\f[R]`: I makes sure that when the last change is popped, the font reverts to regular, and not to bold italic.
(For the headers, as I said, the popping is not necessary because it does not happen, but it would be nice if italic in headers defaulted to bold italic.)

**Comment by jgm** [comment]
teoric <notifications@github.com> writes:

I was wondering why we need to use `\f[]` at all. Why not
just use `\f[R]` (or whatever is appropriate at that
point) to revert?

**Comment by teoric** [comment]
I see (now), this is why I had changed the comment to which you responded. I agree that using `\f[R]` is better.
