### ISSUE TITLE
Both rendered formulas and corresponding TeX math code are shown in epub files obtained from markdown files

### ISSUE THREAD

**Issue by harisont** [jgm/pandoc#4555]
When I convert a markdown file containing any math formula in TeX, such as `$-b \pm \sqrt{b^2 - 4ac} \over 2a$`, to epub, both the rendered formula and  `-b \pm \sqrt{b^2 - 4ac} \over 2a` will be visible in the epub output (tried many readers). Using pandoc 2.1.3

**Comment by jgm** [comment]
Note that `\over` isn't handled by the texmath library, which pandoc
uses for math conversion.  Use the more proper LaTeX `\frac` instead:
`$\frac{-a \pm \sqrt{b^2 - 4ac}}{2a}$`.  Let us know if this doesn't
give you better results.

**Comment by harisont** [comment]
Same thing: both the (correctly) rendered formula _and_ the LaTeX markup are visible in the resulting .epub file, no matter what's inside the $s.

**Comment by jgm** [comment]
Are you targeting epub3 or epub2?  (epub == epub3 in recent pandoc)

**Comment by harisont** [comment]
I've tried both, same issue. 
Something similar happens with all pictures' alt text: the image is displayed perfectly, but the alt text is visible, too (that isn't very annoying, though, while on the other hand the LaTeX issue makes formulas a bit confusing).

**Comment by jgm** [comment]
Arianna Masciolini <notifications@github.com> writes:

> I've tried both, same issue. 

Strange.  I've never noticed any problem in iBooks with epub3.  With
epub2, there is no math support in any reader unless you use --webtex
or something to generate images. I haven't tried many other epub
readers. What readers are you using?  Does this happen for all formulas,
or only some?

> Something similar happens with all pictures' alt text: the image is displayed perfectly, but the alt text is visible, too (that isn't very annoying, though, while on the other hand the LaTeX issue makes formulas a bit confusing).

If you have an image alone in a paragraph, it will be treated
as a figure with the alt text as caption -- perhaps that's what you're
seeing here?  You can disable this:  `-f markdown-implicit_figures`.

**Comment by mb21** [comment]
I cannot reproduce this with the calibre ebook-viewer:

    echo '$\sqrt{b^2 - 4ac}$' | pandoc -o test.epub --webtex

Does that not work for you? If not, can you give a specific command and possibly produced epub file?

**Comment by harisont** [comment]
Cool, if I use --webtex **_and_** target epub3 it works (in calibre), so I guess that's a solution and the pocketbook software is acting weird for some other reason.
Thank you very much anyway, you've been really kind and pandoc is an amazing software.
