### ISSUE TITLE
the RST reader fails to parse emphasis around a resource identifier

### ISSUE THREAD

**Issue by danse** [jgm/pandoc#4561]
pandoc 2.1.4 behaves like the following:

    $ pandoc -f rst -t native
    *http://location*
    [Para [Str "*",Link ("",[],[]) [Str "http://location*"] ("http://location*","")]]

rather than `Str "*",Link ("",[],[]) [Str "http://location*"] ("http://location*","")` we would expect it to produce `Emph [Str "http://location"]`

**Comment by jgm** [comment]
This is because the trailing `*` is parsed as part of the URL.
It's very difficult to get good heuristics for bare URLs,
and different tools use different ones.

See `uri` in Text.Pandoc.Parsing.  We could probably
tweak this to get this case right, though it might break
a bare URL somewhere else!

**Comment by danse** [comment]
this is affected by #4582. as in #4581, also here one could say that the problem is parsing nested inlines so when recursive parsing is disabled the result is:

```
 pandoc (4581)$ pandoc -f rst -t native
*http://location*
[Para [Emph [Str "http://location"]]]
```
note that the behaviour exhibited by pandoc 2.1.4 garbles an RST document in a round-trip workflow, while the behaviour proposed by #4582 keeps it intact:

```
 pandoc (4581)$ pandoc -f native -t rst
[Para [Str "*",Link ("",[],[]) [Str "http://location*"] ("http://location*","")]]
\*\ http://location*
 pandoc (4581)$ pandoc -f native -t rst
[Para [Emph [Str "http://location"]]]
*http://location*
```
