### ISSUE TITLE
prevent markdown from converting dollar sign into  math

### ISSUE THREAD

**Issue by ppKrauss** [jgm/pandoc#4566]
The dollar sign (`$`) is a very usual symbol primarily used to indicate currency... So is very usual a markdown text (any flavor including `gfm`) that need `$` as a text symbol, **not as  LaTeX mark for equations**. 

Example: an original markdown was generated by `pandoc -f html-native_divs-native_spans -t gfm myFile.html > my.md`. So is "all pandoc compatible". When back to HTML with  `pandoc -s -t HTML5 --template html5.tpl < my.md` it was interpreted as LaTeX.

The use of `markdown_strict` option is not a solution, is so strict.

Suggestion:

1. To change defaults: the usual is "no LaTeX".
2. To offer an option `no-tex_math_dollars`:  opposite of `markdown-tex_math_dollars`, to disable `tex_math_dollars` and only it (preserving all other options).

----

Using pandoc 2.1.1. 

More examples: https://stackoverflow.com/questions/29553312

**Comment by mb21** [comment]
the minus in `markdown-tex_math_dollars` actually means that. see http://pandoc.org/MANUAL.html#extensions

also please ask questions like this on pandoc-discuss.

**Comment by ppKrauss** [comment]
When use `pandoc -s -t HTML5 -markdown-tex_math_dollars`  generates a warning,
> [WARNING] Deprecated: --latexmathml, --asciimathml, -m

something is wrong on my pandoc version?

... and produces `<span class="LaTeX">`... Summarizing:

* default:  `R<span class="math inline">2<em>m</em><em>i</em><em>l</em> ...`. It is ugly (!), seems a bug. 
* with `-markdown-tex_math_dollars`  option: ` R<span class="LaTeX">$2mil ...`. So, it is not "no LaTeX", is a bug.

**Comment by mb21** [comment]
it should be: `pandoc -s -t html -f markdown-tex_math_dollars`
