### ISSUE TITLE
[feature request] consolidated template instead of separate ones for flags -H, -B, -A

### ISSUE THREAD

**Issue by jannick0** [jgm/pandoc#4568]
For better and easier maintenanc of included template code snips for the header (`-H`) and before and after the body (`-B` and `-A`) it would be great to have a new flag to assign one single template file comprising all three pieces like, e.g., so (using any break point syntax as you like):

```
%%out:include-in-header=template-H.tex
   header
%%out:include-before-body=template-B.tex
   before body
%%out:include-after-body=template-A.tex
   after body
```
As a current workaround I am using a script to split the single template file into the three pieces which are then passed onto pandoc.

As a separate request it would be great if `$`-variables in the included templates (flags `-H`, `-B`, `-A`) are expanded.

**Comment by jgm** [comment]
You can already do this.  Just use a custom template with `--template`.  Let's not make things unnecessarily complex.
