### ISSUE TITLE
What does it mean of this error? It shows Mojibake. What I can do to solve it?

### ISSUE THREAD

**Issue by ddkk3000** [jgm/pandoc#4570]
pandoc version： 2.1.3

As shown in following snap:

![](http://cache.lixiaozhe.com/image/180420/3eaIhB4Be1.png)

files: []((http://lixiaozhe.com/demo-scholar-markdown-docx-master.zip)

script: pandoc --filter pandoc-citeproc --bibliography=paper1.bib --csl=chinese-gb7714-2005-numeric.csl paper1.md -o paper.demo.docx

**Comment by jgm** [comment]
Running this on macos, I get:
```
pandoc-citeproc: reference 王觅泉2014约书亚 not found
```
and no error.  I suspect this probably has to do with terminal support in Windows.
Looks like you're missing a close `]` character in
```
[@王觅泉2014约书亚
```
in your md file?

**Comment by ddkk3000** [comment]
thank you very much.

It's great to know what a mistake is.
________________________________
