### ISSUE TITLE
unexpected Tok "source" Symbol "_"  when reading latex

### ISSUE THREAD

**Issue by gtheler** [jgm/pandoc#4576]
The following (valid) LaTeX input (call it `mwe.tex`)

```
donde~$\rho$ es la densidad del acero, $\rho_\text{D$_2$O}=\SI{866}{\kilogram\per\cubic\meter}$ la densidad del agua pesada a~$\SI{250}{\celsius}$, y $r_i$ y $r_o$ los radios internos y externos respectivamente.
```

fails with the following error

```
$ pandoc mwe.tex 

Error at "source" (line 1, column 54):
unexpected Tok "source" (line 1, column 54) Symbol "_"
expecting end of input
donde~$\rho$ es la densidad del acero, $\rho_\text{D$_2$O}=\SI{866}{\kilogram\per\cubic\meter}$ la densidad del agua pesada a~$\SI{250}{\celsius}$, y $r_i$ y $r_o$ los radios internos y externos respectivamente.
                                                     ^
$
```

Latest debian package was used:

```
$ pandoc -v
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2
Default user data directory: /home/gtheler/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

This bug error was first posted in the pandoc-discuss mailing list and jgm did confirm it was a bug.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by jgm** [comment]
It's okay, this was reported first on pandoc-discuss and is diagnosed
there.  The problem is that the latex parser tries to identify a math
section in a way that ignores the possibility that `$` may occur
inside `\text{..}` in math.

**Comment by jgm** [comment]
There is still a residual issue, shown by the following:
```
% pandoc -f latex --mathml
$\SI{866}{\kilogram\per\cubic\meter}$
[WARNING] Could not convert TeX math '\SI{866}{\kilogram\per\cubic\meter}', rendering as TeX:
  \SI{866}{\kilogram\per\cubic\meter}
     ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
<p><span class="math inline">$\SI{866}{\kilogram\per\cubic\meter}$</span></p>
```

This is really an issue in jgm/texmath, which doesn't support the `\SI` command. Feel free to open an issue about this there.

**Comment by gtheler** [comment]
thanks for your time
