### ISSUE TITLE
--trace is not documented

### ISSUE THREAD

**Issue by doronbehar** [jgm/pandoc#4580]
#### Version:
```
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2
Default user data directory: /home/doron/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
I guess it's pretty obvious what this option does but if not even mentioned in [the manual](http://pandoc.org/MANUAL.html) how can users be aware of it?

**Comment by jgm** [comment]
I didn't document it because it's really just for developers to diagnose problems.

**Comment by mb21** [comment]
Maybe we could add something around https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md#profiling

**Comment by jgm** [comment]
That would make a lot of sense.

**Comment by jgm** [comment]
I'll do this.
