### ISSUE TITLE
nocite isn't used with biblatex

### ISSUE THREAD

**Issue by louisabraham** [jgm/pandoc#4585]
When using the options `biblatex: True` and `nocite: '@*'`, nocite isn't used.

I solved that with a biblatex-nocite field in `default.latex`:

```
$if(biblatex-nocite)$
\nocite{$biblatex-nocite$}
$endif$
```

Then, I can put `biblatex-nocite: '*'`.

**Comment by CLRafaelR** [comment]
The native `nocite` field does the same job as the `biblatex-nocite` field which @louisabraham implemented does, by inserting the following commands into the [`default.latex`](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex), especially around the [`body`](https://github.com/jgm/pandoc/blob/35688c42627dce4641f4f61253e3d3786452b61a/data/templates/default.latex#L484), [for instance here](https://github.com/jgm/pandoc/blob/35688c42627dce4641f4f61253e3d3786452b61a/data/templates/default.latex#L485). This method works not only with `--biblatex` option but also `--natbib`.

```latex
$if(nocite)$
\nocite{$nocite$}
$endif$
```

One caveat of this method (and probably `biblatex-nocite`) is that we cannot use [`@` mention for the uncited items](https://pandoc.org/MANUAL.html#including-uncited-items-in-the-bibliography) on the YAML section of a `.md` file. Rather, we need to delete `@` like

```yaml
---
nocite: |
  item1, item2
---
```

or 

```yaml
---
nocite: |
  *
---
```

If we use the canonical `@` mention as explained in the manual ( i.e. [`@` mention for the uncited items](https://pandoc.org/MANUAL.html#including-uncited-items-in-the-bibliography)), unwanted LaTeX cite commands are included: `
\nocite{\citet{Chomsky1993}}` with `--natbib` and `\nocite{\textcite{Chomsky1993}}` with `--biblatex`

@mb21 

Is there any idea to use `@` mention for the uncited items on the YAML section without deleting the `@` symbol?

**Comment by jgm** [comment]
It seems to me that, when --biblatex or --natbib is used, the latex writer should modify the `nocite` variable before passing it to the template, so that it just contains a comma-separated list of citation ids.  That shouldn't be too hard a change.
