### ISSUE TITLE
If you use two commands defined in your document without a space between them, pandoc gets stuck in latex mode.

### ISSUE THREAD

**Issue by atomicwrites** [jgm/pandoc#4589]
If you use two commands defined in your document without a space between them, pandoc gets stuck in latex mode (ignoring markdown formatting). Using built in latex commands does not cause the issue.I'm running pandoc 2.1.3 on Arch Linux.

````
\newcommand{\one}[1]{#1}
\newcommand{\two}[1]{#1}

Formatting *is* working **here**. But sticking \one{two }\two{comands} together *breaks* formatting. 

This applies also to:

- Lists
- `Code`
- Code Blocks

``` shell
ls -l /
```
````
![shot](https://user-images.githubusercontent.com/9218927/39218447-d167f5f2-47f2-11e8-9905-bbb03afb80ef.png)

[test.pdf](https://github.com/jgm/pandoc/files/1944894/test.pdf)

**Comment by jgm** [comment]
I think I see the problem. Line 258 of LaTeX reader.
```haskell
           rawstring <- takeP (T.length (untokenize raw))
```
`raw` here is the parsed token string AFTER macro expansion, but we're taking tokens from the input before macro expansion, so we take too many tokens.  At least that's my current theory.
