### ISSUE TITLE
Code licensed as GPL-2-only not mentioned as such in COPYRIGHT file

### ISSUE THREAD

**Issue by jonassmedegaard** [jgm/pandoc#4591]
The file src/Text/Pandoc/Readers/TikiWiki.hs lists its license as "GPLv2".

Seems important to update COPYRIGHT file to include that - or better: Contact the author and request a re-licensing as GPLv2 or later, like surrounding code.

**Comment by jgm** [comment]
I'm sure this is just an oversight. I've contacted the original author.

**Comment by jgm** [comment]
Author has given permission to relicense.
See commit cf0b1e435b849193720c33d3e78857ccf1837e6d
