### ISSUE TITLE
LaTeX code inside markdown gets changed unexpectedly.

### ISSUE THREAD

**Issue by Wandmalfarbe** [jgm/pandoc#4594]
When converting a markdown document with some LaTeX inside the LaTeX code gets changed unexpectedly. In the following example the code `svgwidth` is replaced by `columnwidth` which results in an infinite loop.

Input:
```markdown
Some **bold** text here.

\begin{figure}[htbp]
\centering
\def\svgwidth{\columnwidth}
\import{img/}{vectors.pdf_tex}
\caption{Some caption.}
\end{figure}

Some *italic* text here.
```

Command:
```
pandoc -o "doc.tex" "doc.md" --from markdown --listings --biblatex --bibliography="bib.bib"
```

Output:
```
Some \textbf{bold} text here.

\begin{figure}[htbp]
\centering
\def\columnwidth{\columnwidth}
\import{img/}{vectors.pdf_tex}
\caption{Some caption.}
\end{figure}

Some \emph{italic} text here.
```

Expected output:
```
Some \textbf{bold} text here.

\begin{figure}[htbp]
\centering
\def\svgwidth{\columnwidth}
\import{img/}{vectors.pdf_tex}
\caption{Some caption.}
\end{figure}

Some \emph{italic} text here.
```

The example can be [reproduced online](https://pandoc.org/try/?text=Some+**bold**+text+here.%0A%0A%5Cbegin%7Bfigure%7D%5Bhtbp%5D%0A%5Ccentering%0A%5Cdef%5Csvgwidth%7B%5Ccolumnwidth%7D%0A%5Cimport%7Bimg%2F%7D%7Bvectors.pdf_tex%7D%0A%5Ccaption%7BSome+caption.%7D%0A%5Cend%7Bfigure%7D%0A%0ASome+*italic*+text+here.&from=markdown&to=latex).

---
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2

**Comment by jgm** [comment]
It appears to be applying the macro definition to the definition itself, which isn't good.
Possibly related to #4246.

**Comment by jgm** [comment]
OK I see the problem.
LaTeX reader:
```haskell
rawLaTeXBlock :: (PandocMonad m, HasMacros s, HasReaderOptions s)
              => ParserT String s m String
rawLaTeXBlock = do
  lookAhead (try (char '\\' >> letter))
  -- we don't want to apply newly defined latex macros to their own
  -- definitions:
  snd <$> rawLaTeXParser macroDef
  <|> ((snd <$> rawLaTeXParser (environment <|> blockCommand)) >>= applyMacros)
```

This works fine to avoid applying macros to their own definitions, as long as those definitions don't occur *inside* a larger raw LaTeX block, as in your example.
