### ISSUE TITLE
Latex \MakeUppercase problem

### ISSUE THREAD

**Issue by EliseyP** [jgm/pandoc#4595]
Hello!
pandoc 1.17.2 (Debian 9x64) can't see text in \MakeUppercase{}. My short example:
```
\documentclass{book}
\begin{document}
test \MakeUppercase{Case Text.} \textsc{testsc}
\end{document}
```
running pandoc, I get: (plain format here - for clearness, with other format - the similar resultat)
```
$ pandoc -f latex -t plain  main-uppercase.tex
test TESTSC
```

**Comment by jgm** [comment]
We should add support for `\MakeUppercase`, `\MakeLowercase`,
`\uppercase`, `\lowercase`, and perhaps also
`\MakeTextUppercase` and `\MakeTextLowercase` from textcase.
See http://www.tex.ac.uk/FAQ-casechange.html.
