### ISSUE TITLE
Different Writers treat {.smallcaps} inconsistently

### ISSUE THREAD

**Issue by teoric** [jgm/pandoc#4596]
Different writers seem to treat smallcaps inconsistently. With the HTML and MarkDown writer, `{.smallcaps}` leads to a CSS class even if used with a link. With other readers, e.g. LaTeX, CommonMark, MS, Word, and ODT, it seems to be dropped in this case, while it is translated to small caps when used as a span on its own (Pandoc 2.1.3). Consider the following input file `test.md`:
```markdown
[Pandoc](https://www.pandoc.org){.smallcaps}

[Pandoc]{.smallcaps}
```
Using `pandoc -t html test.md`, you get (HTML: **kept**):
```html
<p><a href="https://www.pandoc.org" class="smallcaps">Pandoc</a></p>
<p><span class="smallcaps">Pandoc</span></p>
```
Using `pandoc -t latex test.md`, you get (LaTeX: **lost**):
```latex
\href{https://www.pandoc.org}{Pandoc}

\textsc{Pandoc}
```
Using `pandoc -t ms test.md`, you get (MS: **lost**):
```nroff
.LP
\c
.pdfhref W -D "https://www.pandoc.org" -A "\c" \
 -- "Pandoc"
\&
.PP
P\s-2ANDOC\s0
```
Using `pandoc -t docx test.md -o test.docx` or  `pandoc test.md -o test.odt` also gives smallcaps on the second but not the first (DOCX, ODT: **lost**), while `pandoc -t markdown test.md` preserves smallcaps  (DOCX, ODT: **kept**), but `pandoc -t commonmark test.md` gives  (CommonMark: **lost**):
```markdown
[Pandoc](https://www.pandoc.org)

<span class="smallcaps">Pandoc</span>
```

**Comment by adunning** [comment]
This looks like another facet of the same issue as #4102.

**Comment by ickc** [comment]
> This looks like another facet of the same issue as #4102.

Agree. Suggest closing this in favor of #4102.
