### ISSUE TITLE
lua filename is always used in lowercase (--to=FileName.lua)

### ISSUE THREAD

**Issue by jankatins** [jgm/pandoc#4610]
If I use '--to' with a lua file, the lua filename must be lowercase otherwise it fails because it searches for the lowercase filename:

```bash
λ pandoc --print-default-data-file sample.lua > /tmp/sample_LUA.lua     
λ echo '# Title' | pandoc --from 'markdown' --to /tmp/sample_LUA.lua
pandoc: /tmp/sample_lua.lua: openFile: does not exist (No such file or directory)
λ mv /tmp/sample_LUA.lua /tmp/sample_lua.lua 
λ echo '# Title' | pandoc --from 'markdown' --to /tmp/sample_lua.lua
<h1 id="title">Title</h1>
```

Original issue: https://github.com/bebraw/pypandoc/pull/156

**Comment by jankatins** [comment]
Could be https://github.com/jgm/pandoc/commit/c8f97d3d418f929a1f499a9ef37c17d71f282d45

I ran the test with:
```bash
λ pandoc --version                                                
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2
[...]
```

**Comment by labdsf** [comment]
@jankatins I almost fixed it. The problem is not with this commit, though it adds a TODO ("-- note:  use non-lowercased version writerName") that was never resolved.
