### ISSUE TITLE
Strange grid_table to pdf render

### ISSUE THREAD

**Issue by jona-sassenhagen** [jgm/pandoc#4611]
This grid_table:

```
+-----------------+--------------+-----------+-------------+--------------+
|Condition        | Estimate     |         SE|     z-value |     Pr(>|z|) |
+:================+=============:+==========:+============:+=============:+
| sdcdfvdfgd      |  -15.3137    |  0.00102  |-15019.97    |    .001      |
+-----------------+--------------+-----------+-------------+--------------+
| aaaaaaaa        |   -8.0219    |  0.00104  |-7725.25     |    .001      |
+-----------------+--------------+-----------+-------------+--------------+
| xxxxxxxxx       |   -6.9084    |  5.37989  |-1.28        |        .199  |
+-----------------+--------------+-----------+-------------+--------------+
```

Renders to pdf like this:

<img width="843" alt="screenshot 2018-04-29 17 55 26" src="https://user-images.githubusercontent.com/4321826/39408452-b78dea28-4bd6-11e8-93ef-45fc2b96367a.png">

I've tried `--wrap=none` and various versions for `--columns` and they don't fix the problem. In fact, very large values for `--columns` make the problem much worse.

```
pandoc -v
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
```

**Comment by jgm** [comment]
This is easy to explain.

Grid tables accept block-level formatting in cells.  In your lower-right
cell, you have > 4 spaces in front of .199, so it is treated as an
indented code block.  Remove the spaces and you'll be fine.

**Comment by jona-sassenhagen** [comment]
Ah yes, I see. Thanks.
