### ISSUE TITLE
file: based urls do not work on windows

### ISSUE THREAD

**Issue by jankatins** [jgm/pandoc#4613]
I try to make pypandoc useable with file based URLs: https://github.com/bebraw/pypandoc/pull/157. 

According to the tests in https://github.com/bebraw/pypandoc/pull/157 they work on linux but not on windows. I can't really debug that further because I do not have a windows system, but that's what appveyor gives me: https://ci.appveyor.com/project/bebraw/pypandoc/build/job/jlbxo137luujc4cm

```bash
# printed file: based url
file:///C:/users/appveyor/appdata/local/temp/1/tmpxy_wob.md
[...]
# python exception because of pandoc failure
RuntimeError: Pandoc died with exitcode "1" during conversion: pandoc: /C:/users/appveyor/appdata/local/temp/1/tmpxy_wob.md: openBinaryFile: invalid argument (Invalid argument)
```
During the codepath (in the call to [_identify_path](https://github.com/bebraw/pypandoc/pull/157/files#diff-f4bc68ff01eef7bed2f3a64cad7d37caR176)), that file url was converted to a normal path and [validated that the file exists](https://github.com/bebraw/pypandoc/pull/157/files#diff-a7662d9aa273ad55c64c91542b606fadR163).

(original addition of file: urls in pandoc: https://github.com/jgm/pandoc/issues/3196)

**Comment by mb21** [comment]
Well, what exact pandoc command does pypandoc call that’s failing? And with what input? Also: pandoc version?

**Comment by labdsf** [comment]
Looks like you tried to open `/C:/users/appveyor/...`, instead of `C:/users/appveyor/...`. Linux does not care about extra slashes in the beginning of absolute filenames, while Windows obviously does, because of that slash before `C:`.

**Comment by jankatins** [comment]
The call should be `pandoc --from=markdown --to=rst file:///C:/users/appveyor/appdata/local/temp/1/tmpxy_wob.md` (which is a correct URL on windows according to https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/). On linux it calls it with `--to=file:///tmp/tmp6_jab5gc.md` and that works.

**Comment by labdsf** [comment]
So on Linux it is `/tmp/tmp6_jab5gc.md`, on Windows `/C:/users/appveyor/appdata/local`. You should call `pandoc --from=markdown --to=rst file://C:/users/appveyor/appdata/local` on Windows.

**Comment by jankatins** [comment]
According to [MS](https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/) that is not a correct URL:

> For the local Windows file path C:\Documents and Settings\davris\FileSchemeURIs.doc
> The corresponding valid file URI in Windows is: file:///C:/Documents%20and%20Settings/davris/FileSchemeURIs.doc

**Comment by labdsf** [comment]
Hmm, looks like a bug in pandoc then. `file:///C:/users/appveyor/appdata/local` should be interpreted as `file://localhost/C:/users/appveyor/appdata/local`.

**Comment by jgm** [comment]
We just try to open up the path returned by `Network.URI.uriPath`:
```
Prelude Network.URI> uriPath <$> parseURI "file:///c:/data/external/pypandoc/test.md"
Just "/c:/data/external/pypandoc/test.md"
```
When we're on linux, we want to treat this initial `/` as part of the path, or we'll (incorrectly) get a relative, not absolute path.

We could ad something ad hoc so that it is stripped off on Windows (i.e., when it's followed by LETTER + COLON).  Is there a better approach?

**Comment by mb21** [comment]
> won't it replace an absolute path with a relative one?

yes:

    dropWhile (=='/') "/foo"
    "foo"
