### ISSUE TITLE
Pandoc doesn't parse markdown headings directly preceded by an anchor tag

### ISSUE THREAD

**Issue by rgb-one** [jgm/pandoc#4616]
```
<a name="installation"></a>
## Installation
```
or 
```
<a name="installation"></a>## Installation
```
results in
```
<p><a name="installation"></a> ## Installation</p>
```
instead of
```
<p><a name="installation"></a><h2>Installation</h2></p>
```
This applies for all heading tags (h1-h6).

[Try Pandoc](https://pandoc.org/try/?text=%3Ca+name%3D%22installation%22%3E%3C%2Fa%3E%0A%23%23+Installation%0A&from=markdown&to=html5)

**Comment by jgm** [comment]
The way pandoc sees this:  with `<a...` we have inline
HTML so we start a new paragraph.  This continues until
the end of the paragraph.  When does a paragraph end?
With a blank line, or the beginning of a list.  So the `##`
is just regular paragraph content.

If you'd like to be able to start a header right after
a paragraph line, without a preceding blank line, then
use `markdown-blank_before_header`.

See the manual under http://pandoc.org/MANUAL.html#atx-style-headers
`blank_before_header`.

In short: not a bug.

**Comment by rgb-one** [comment]
Indeed. Thank you.
