### ISSUE TITLE
Pandoc chokes on valid LaTeX in a comment

### ISSUE THREAD

**Issue by kdheepak** [jgm/pandoc#4617]
MWE below to reproduce the error.

**Input files**

Template

```tex
% ieee_jrnl.tex
%\IEEEpubid{0000--0000/00\$00.00~\copyright~2015 IEEE}
```

See [here](http://ieeeauthorcenter.ieee.org/create-your-ieee-article/use-authoring-tools-and-ieee-article-templates/ieee-article-templates/templates-for-transactions/) for full source.

Markdown

```markdown
<!-- Markdown file -->
Hello world
```

**Run**

Command line:

```bash
$ pandoc --template ./template.tex paper.md -o paper.pdf
"template" (line 1, column 28):
unexpected "0"
expecting letter
```

My current version of Pandoc:

```bash
$ pandoc --version
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.1
Default user data directory: /Users/$USER/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
This is not a bug.  In pandoc's template language, `$` is a special
character; hence, you must escape all literal `$` characters as `$$`.
Even in a comment!  The template language is language-agnostic; it
doesn't know anything about tex comments.

**Comment by kdheepak** [comment]
Ah, that makes sense. I'll close this issue.
