### ISSUE TITLE
LaTeX environments interpreted as CodeBlock lose trailing blank lines and newline

### ISSUE THREAD

**Issue by gpoore** [jgm/pandoc#4624]
Losing trailing blank lines typically won't be an issue, but it does mess up line numbering when code containing blank lines is broken up between multiple environments. Losing a trailing newline lacks symmetry with the markdown fenced code equivalent.

File `test.txt`:
```latex
\begin{Verbatim}[key1=value1]
code1

\end{Verbatim}


\begin{lstlisting}[key2=value2]
code2

\end{lstlisting}
```

Output of `pandoc -f latex -t json test.txt` with pandoc 2.2:
```
{"blocks":[
    {"t":"CodeBlock","c":[["",[],[["key1","value1"]]],"code1"]},
    {"t":"CodeBlock","c":[["",[],[["key2","value2"]]],"code2"]}
 ],"pandoc-api-version":[1,17,4,2],"meta":{}}
```

**Comment by jtpereyda** [comment]
Another use case is a sample HTTP request, which by definition ends with a blank line:
```
GET /index.html HTTP/1.1
Host: *

```
An HTTP request without the blank line is not valid.
