### ISSUE TITLE
--pdf-engine-opt='--disable-toc-links' with wkhtmltopdf not working

### ISSUE THREAD

**Issue by sgrassie** [jgm/pandoc#4626]
Firstly, I want to apologise for asking about this on the mailing list, as it's blocked by the company, but I also think it's a bug anyway.

Using wkhtmltopdf, and using the `--toc` option, the links in the generated TOC in the PDF don't work, and instead rather than linking to the relevant section in the document, they want to link externally to the filesystem relative to where the PDF is.

Not sure whether this is a bug, or I've just done something wrong, but having the TOC linkable isn't a requirement, so I've attempted to disable it by passing `--pdf-engine-opt='--disable-toc-links'`, but that just results in `--disable-toc-links specified in incorrect location`. I'm passing in a whole other bunch of wkhtmltopdf options in using this method, it just seems to be this one.

Pandoc version: 2.2

Simplified command line:

    pandoc test.md -s -f gfm -N -t html5 --pdf-engine=wkhtmltopdf --pdf-engine-opt='--disable-toc-links' --toc -o output.pdf

**Comment by mb21** [comment]
> the links in the generated TOC in the PDF don't work

Yes, that's [currently a known bug](https://github.com/jgm/pandoc/issues/4413).

Using `--toc`, the toc is generated by pandoc, not wkhtmltopdf, thus passing `--disable-toc-links` to wkhtmltopdf has no effect. However, try:

    pandoc -s -t html | wkhtmltopdf toc - output.pdf

**Comment by sgrassie** [comment]
I saw that bug and didn't fully make the connection that it was the same problem I was having :(

That seems to work and produces a toc as the first page of the document. I'll see what I can do about moving it or adding a title page. 

Thanks.

**Comment by mb21** [comment]
btw. you can also work around the bug like this:

    pandoc --toc input.md -s file.html && wkhtmltopdf file.html output.pdf
