### ISSUE TITLE
Reader option for support RedMine textile format

### ISSUE THREAD

**Issue by KindDragon** [jgm/pandoc#463]
RedMine wiki use textile format with minor modification. Instead of _ for underscore they use +.
Please add pandoc option for that.

**Comment by Hipska** [comment]
Hi,

I'm also trying to convert redmine issue's and wiki and came to the problem that > also renders as a block quote.

```
> test
> * item 1
> * item 2
```
Renders like this in Redmine
> test
> * item 1
> * item 2

Should I open new issue?

**Comment by jgm** [comment]
Are you sure the pages you're dealing with aren't Markdown?  Redmine seems to support both Markdown and Textile.  `>` is blockquote syntax in Markdown, but not textile (which uses `.bq`).

**Comment by Hipska** [comment]
Hmm , okay need to re-check that.

I think it is mixed, I think I saw in the same text it also used `"link":url` notation for links, which is typical Textile and not Markdown. (I guess)
