### ISSUE TITLE
Some sort of infinite loop when the input file is not present

### ISSUE THREAD

**Issue by s1291** [jgm/pandoc#4632]
Say I have in my directory only one markdown file: `mydocument.md`
If I try something like this (I provide non-existing file):
`pandoc document.md --from markdown --to docx -o document.docx`
we get an error:
`pandoc.exe: document.md: openBinaryFile: does not exist (No such file or directory)`
That's fine. But what if I forget to provide the input file, pandoc will enter in an infinite loop and it will never terminates (it takes a long time I don't know how):
**Example** (Note I forgot to provide an input file)
`pandoc  --from markdown --to docx -o document.docx`
This command will not terminate.

**Comment by mb21** [comment]
From the [MANUAL](http://pandoc.org/MANUAL.html):

> If no *input-files* are specified, input is read from *stdin*.

Please ask questions like this on pandoc-discuss.

**Comment by Erquint** [comment]
The documentation never specified how to terminate `stdin` input.
`EOT` control character, entered with `^D` (`[Ctrl]+[D]`) submits entered text to Pandoc.
`ETX` control character, entered with `^C` (`[Ctrl]+[C]`) breaks Pandoc execution.

**Comment by agusmba** [comment]
> The documentation never specified how to terminate `stdin` input.
> `EOT` control character, entered with `^D` (`[Ctrl]+[D]`) submits entered text to Pandoc.
> `ETX` control character, entered with `^C` (`[Ctrl]+[C]`) breaks Pandoc execution.

I'm not sure that pandoc should document [standard OS behavior](https://unix.stackexchange.com/a/16338)

**Comment by Erquint** [comment]
Standards are out of the window once every developer can code their program to interpret any control character and/or signal as they please.
There are truckloads of programs that use other "shortcuts" for the same purpose.
`^Q`,`^Z`,`^R`,`^W`, you name it! All in console. More often than not, just for termination.

At this point, yes, you should document if your program follows a standard an which one it is.

Don't get me wrong, I'd love to see standards work, but I can also see the irony of this very program's purpose being a bridge between countless standards.
