### ISSUE TITLE
Underline not working for the docx writer

### ISSUE THREAD

**Issue by mirraj2** [jgm/pandoc#4633]
I had submitted a question on the message board about this and John MacFarlane said I should open this as an issue, so here it is!

Version
-------------------------
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.0.2

Bug Report
-----------------------
Based on [this pull request](https://github.com/jgm/pandoc/pull/2270), it seems like Pandoc supports underlines.

When I tried to export `<span class="underline">This is a test</span>` to docx format, it exported, but the text was not underlined.

I am just using the most basic command:
`./pandoc -s input.html -o output.docx`

**Comment by jgm** [comment]
Underline hasn't yet been supported in the docx writer.  This would probably not be hard to add.
