### ISSUE TITLE
Markdown: Awkward soft break after abbreviation between ( and newline

### ISSUE THREAD

**Issue by fiapps** [jgm/pandoc#4635]
Test case:
``` bash
echo '(cf.
Foo)' | pandoc -f markdown -t markdown
```
Output: `( cf. Foo)`.

A space has been added after the open parenthesis. More precisely, if the native output format is chosen, we see it's a `SoftBreak`: `[Para [Str "(",SoftBreak,Str "cf.\160Foo)"]]`.

This is a sufficiently rare case that it only occurred once in a 350 page document.

**Comment by msprev** [comment]
This is actually a pretty common bug if you used hard line wrapping in your source document. It produces the error any time a line in your source document ends in an abbreviation prefixed by parenthesis:

```
Lorem (e.g.
ipsum)
```
produces output

```
Lorem ( e.g. ipsum)
```

I hard wrap at 78 characters in my source documents. On average for me, this produces ~3 errors per 8,000 words and of course it affects all output formats.

**Comment by mb21** [comment]
A possible workaround is to use `--abbreviations=/dev/null`
