### ISSUE TITLE
Beamer not giving a TOC

### ISSUE THREAD

**Issue by eyJhb** [jgm/pandoc#4636]
In reference to #4622 that got closed, even though the bug still persists!
Using the --toc when generating a beamer (.pdf), then you still do not get a table of contents for your presentation.

This question is not a reference on how to make sections, but rather that no toc is generated.
```
---
toc:
- true
title:
- test
author:
- eyJhb
---

# test section0
Yeah!

# test section1
Yeah!

# test section2
Yeah!

# test section3
Yeah!

# test section4
Yeah!
```

Output (.tex)
```
\begin{frame}{test section0}
\protect\hypertarget{test-section0}{}

Yeah!

\end{frame}

\begin{frame}{test section1}
\protect\hypertarget{test-section1}{}

Yeah!

\end{frame}

\begin{frame}{test section2}
\protect\hypertarget{test-section2}{}

Yeah!

\end{frame}

\begin{frame}{test section3}
\protect\hypertarget{test-section3}{}

Yeah!

\end{frame}

\begin{frame}{test section4}
\protect\hypertarget{test-section4}{}

Yeah!

\end{frame}
```

**Comment by eyJhb** [comment]
@mb21 I don't even get the toc page, which is as stated, the problem..

**Comment by mb21** [comment]
Yes, if you don't put in the right header, you don't get the toc page. But you do get the toc page with the sample I posted above, right?

**Comment by eyJhb** [comment]
Stupid me, yeah I do. I'll continue seeing if I can get my theme to work.
