### ISSUE TITLE
The equation environment is lost when converting Markdown to HTML with Pandoc 2.2

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#4639]
Minimal example `test.md`:

```tex
\begin{equation}
  E=mc^2
\end{equation}
```

With the latest Pandoc 2.2:

```sh
$ pandoc -t html --mathjax test.md

```

The output is empty.

It works as expected with Pandoc 2.1.3:

```sh
$ ./pandoc-2.1.3/bin/pandoc -t html --mathjax test.md

<span class="math display">\[\begin{equation}
  E=mc^2
\end{equation}\]</span>
```

It has been working since Pandoc 1.x, but was broken in 2.2.

Note that the LaTeX output is still good with 2.2:

```sh
$ pandoc -t latex test.md

\begin{equation}
  E=mc^2
\end{equation}
```

I have only tested it on macOS.

**Comment by jgm** [comment]
I see what's happening.  The LaTeX reader now parses these as "inline environments" -- previously they were parsed as blocks.  So, previously, we got:
```
RawBlock (Format "latex") "\\begin{equation}\n  E=mc^2\n\\end{equation}"
```
and now, we get:
```
Para [RawInline (Format "tex") "\\begin{equation}\n  E=mc^2\n\\end{equation}"]
```
The Markdown reader is looking for the former, not the latter.

**Comment by jgm** [comment]
This was the interaction of a couple different things.
I've added a test case so we don't regress on this in the future. Sorry!

**Comment by yihui** [comment]
Great! Thanks a lot for the quick fix!
