### ISSUE TITLE
finer-grained --self-contained especially for images

### ISSUE THREAD

**Issue by PerBothner** [jgm/pandoc#4643]
It would be helpful to have more control over which "resources" get inlined as `data:` when the `--self-contained` flag is used.  I see two useful dimensions:

1. Only inline images, but not css or js. Maybe `--self-contained=images`.
2. Only inline relative file names, or only inline filenames (not http: or other URLS). Maybe `--self-contained=relative` and `--self-contained=file`.

The two could potentially be combined: `--self-contained=relative-images`.

My use-case is "printing" a document to a terminal that can embed HTML in the terminal window, specifically [DomTerm](https://domterm.org). For such uses the option `--self-contained=file-images` would be helpful: Inlining js or css just makes the output bulkier, and adds more work/complication to the DomTerm html sanitizer (which disallows js). However, it is desirable to inline local images for various reasons: the pandoc command may be running on a different host than the display; stability of the terminal output in case the image is changed and the display needs to be refreshed; it is easier to save/copy the terminal output if the image is inline.

I can solve this problem for DomTerm by post-processing the pandoc-generated html, but if it seems like useful pandoc enhancement it should be easy to implement, as the hard stuff is already there.

**Comment by jgm** [comment]
Did you read in the manual about the `data-external="1"` attribute?

You could use a simple lua filter to add this attribute to a class
of images depending on the path; this would happen prior to
`--self-contained`.

**Comment by mb21** [comment]
@PerBothner Have a look at http://pandoc.org/filters.html

**Comment by jgm** [comment]
Per Bothner <notifications@github.com> writes:

> _"Did you read in the manual about the `data-external="1"` attribute?"_
>
> I saw it. That will help for a *specific* document.  I've no idea how
> to write a "simple lua filter".  If one wanted it to work for multiple
> input formats, it seems like it would need to be injected *after*
> parsing the input.

Yes, that's what it does.  The document linked to above is a good place
to learn the basic idea of filters. For lua filters, see
http://pandoc.org/lua-filters.html.  This one would be quite simple --
probably just a few lines.  It would require no software other than
pandoc itself, which embeds the lua interpreter.

**Comment by anishmittal2020** [comment]
@PerBothner  Did you create the lua filter? If yes, could you please share it?

**Comment by PerBothner** [comment]
No, I have not looked into how to write a filter.  Since my knowledge of Lua is less than my knowledge of Haskell, using a Haskell filter might make more sense - if/when this gets high enough on my stack.  (If some
