### ISSUE TITLE
docx writer does not respect yaml toc variable

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc#4645]
The following markdown snippet does not produce a docx with a TOC but a PDF with a TOC:

```markdown
---
toc: true
toc-title: Inhaltsverzeichnis
...

# Test

Some text.
```

Only after addint `--toc` to the command line of pandoc, a TOC is generated in docx but now also with the title defined in the yaml variable `toc-title`.

**Comment by mb21** [comment]
Yes, that's due to the fact that the docx writer doesn't use a template. Thus you cannot use metadata to change the writer's behavior.

**Comment by tolot27** [comment]
I don't understand this explanation. Currently, the docx writer supports the yaml variable `toc-title` but not `toc`. What's the difference here? And what is ment by "use a template"?

**Comment by mb21** [comment]
> Currently, the docx writer supports the yaml variable `toc-title`

Ah yes, the docx writer [looks up that variable here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Docx.hs#L270). So I guess we could do the same thing for `toc`... or consider something like https://github.com/jgm/pandoc/issues/4627...

> And what is ment by "use a template"?

see http://pandoc.org/MANUAL.html#templates

**Comment by tolot27** [comment]
I'd love to see consistency here with other writers like latex. It would be nice if a writer would read command line switches already made available as yaml variable.
In this case here, `toc` and `toc-depth` in addition to `toc-title`.

WRT to templates: Okay, that kind of templates were already known to me. As far as I know, the docx writer uses a default reference.docx. But you are right at that point that this reference.dox does not check variables like the latex template does, because it is simply not possible.

**Comment by mb21** [comment]
Note: the following produces a toc for latex, but not html and docx:

```
---
toc:
  - true
---

# Test
```

but maybe that's okay...

**Comment by tolot27** [comment]
But does the following work now:

---
toc: true
---

That would be sufficient.

**Comment by mb21** [comment]
@tolot27 yes it does (current nightly build)
