### ISSUE TITLE
Pandoc creates Asciidoc files with illegal ids

### ISSUE THREAD

**Issue by neurocline** [jgm/pandoc#4649]
I converted some Github-flavored markdown files to Pandoc. My output files don't make Asciidoctor all that happy, because they have IDs that start with numbers, and that's currently illegal in Asciidoctor, it doesn't see the `[[<id>]]` string as an ID, it sees it (and outputs it) as text; to make things worse, the following section heading is also ignored and emitted as text. That's a bug in Asciidoctor, but for now, it's a bug in Pandoc, since it makes Asciidoc text that the main Asciidoc parser doesn't like. I filed a bug report with the Asciidoctor project to seek clarification.

Suggestion: Pandoc should probably prepend numeric-only IDs with some letter; maybe this is an option, especially since this is needed until Asciidoctor revs (and this rev makes it through the ecosystem, including to Github, where I'd like my Asciidoc files to be legible).

My next immediate step is to see if I can write a Pandoc filter that will do this for me, so I'm not horribly broken, just faced with some work to do.

I'm using pandoc 2.2 on Windows (installed it yesterday).

My sample Markdown

```
# 2018-05-01

## 10:45

Friends posting album links
```

The command-line I used:

```
pandoc -f gfm -t asciidoc --atx-headers test.md -o test.adoc
```

The asciidoc I received

```
[[2018-05-01]]
= 2018-05-01

[[1045]]
== 10:45

Friends posting album links
```

The as-viewed HTML that Asciidoctor (including viewing on Github) shows me:

```
[[2018-05-01]] = 2018-05-01

[[1045]] == 10:45

Friends posting album links
```

**Comment by mb21** [comment]
try `-t asciidoc+ascii_identifiers`

**Comment by mb21** [comment]
Actually, the identifiers are generated by the reader. Try `-f markdown` (or `-f markdown_github) instead of `-f gfm`

**Comment by neurocline** [comment]
This works in one respect - I get Asciidoc that is respected by tools like Asciidoctor. However, I lose all the anchors, because auto_identifiers won't work for my content.

The problem with auto_identifiers is that all my anchors will end up being called `section`, and that's not going to be useful. If only there was a `prefix-identifiers` extension or some way I could remap. Also, I had a brief exchange with the Asciidoctor folks and they were adamant that legal block ids (used for anchors) must start with an alphabetic character.

I started writing a Pandoc lua filter last night to handle this (essentially, to implement "prefix identifiers"). I'll post what I end up with, because maybe someone else will have this same issue.

**Comment by mb21** [comment]
They would be called `section`, `section-1`, etc. If that doesn't work for you, you can also assign them ids manually, using the `header_attributes` extension.

**Comment by jgm** [comment]
You could just use `--id-prefix=foo`, then all your identifiers
will start with `foo`.

**Comment by jgm** [comment]
@neurocline do either of these suggestions address your problem?  If so, can we close this?

**Comment by neurocline** [comment]
Sorry, yes. Closed.
