### ISSUE TITLE
I want to retain quality of image when exporting to Docx (300dpi). Not reduce quality of image. (72dpi)

### ISSUE THREAD

**Issue by smks** [jgm/pandoc#4650]
If you have an image at 300dpi, and you export it but set a width and a height, it creates a smaller version of the image resulting in a DPI of 72.

```markdown
![](./images/pencil.png){ width=10% height=10% }
```
Expected behaviour:
The image should not be reduced in size on the file system (which causes loss of quality) and instead embed the image as is (with the highest quality) but reduce the size down in Word instead so it retains DPI.

This is because I am using KDP to create a book and it is complaining the images should be 300dpi.

Because I use this image many times in the Doc, I don't want to remove the set height and width and manually reduce the size of all pencils in the docx.

Original
https://imgur.com/XUjJNnm

Generated
https://imgur.com/fbHAZbT

**Comment by smks** [comment]
I have also set the `--dpi=300` when I run pandoc:

```
pandoc -o "A:\Development\Books\AutomatingWithNode\automating-with-nodejs\build\docx\automating-with-nodejs.docx" --extract-media "A:\Development\Books\AutomatingWithNode\automating-with-nodejs\chapters\images" --dpi 300 --table-of-contents --toc-depth=3 --highlight-style kate --reference-doc=custom-reference.docx
```

**Comment by mb21** [comment]
I cannot reproduce this:

    echo '![](https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png){ width=10% height=10% }' | pandoc -o test.docx
    unzip -d test test.docx

Then looking at `test/word/media/rId20.png`, it's still 800x600.

The `--dpi` option shouldn't have any effect on this. Maybe it's the Word version with which you're opening the file that makes it look pixelated..?

**Comment by mb21** [comment]
You'll have to come up with a minimal, reproducible example to show us.

**Comment by smks** [comment]
I have found out I had a smaller sized pencil image in a parent folder and it was using that instead... My bad.

**Comment by smks** [comment]
Thanks @mb21
