### ISSUE TITLE
Dropping minus sign after overset command in .docx

### ISSUE THREAD

**Issue by drtondo** [jgm/pandoc#4654]
complete input: minus-sign.docx
exact command line used: pando.txt
expected output: minus-sign.log
actual output: minus-sign.txt

[minus-sign.docx](https://github.com/jgm/pandoc/files/1999106/minus-sign.docx)
[minus-sign.txt](https://github.com/jgm/pandoc/files/1999107/minus-sign.txt)
[pandoc-version.txt](https://github.com/jgm/pandoc/files/1999108/pandoc-version.txt)
[minus-sign.log](https://github.com/jgm/pandoc/files/1999113/minus-sign.log)
[pando.txt](https://github.com/jgm/pandoc/files/1999119/pando.txt)

**Comment by mb21** [comment]
can you try with latest pandoc and post entire command?

**Comment by drtondo** [comment]
Version: 

pandoc.exe 1.17.2

Compiled with texmath 0.8.6.4, highlighting-kate 0.6.2.

 

I downloaded the Windows version last week from pandoc.org

 

original .docx file I used (two lines):         minus-sign.docx

what pandoc produced:                             minus-sign.txt    (the minus sign is missing before 0.0684; the other minus signs are there)

what I need:                                                 minus-sign.log   (with a minus sign inserted manually before 0.0684)

command used:                                           pandoc  -v -f docx  -t latex  -o minus-sign.txt  minus-sign.docx

                                                                        running in bash-3.1 in Windows 7 (output in pandoc-version.txt)

 

If you can help, it’d be nice.

Thanks.

**Comment by mb21** [comment]
We're currently on pandoc 2.2 where this has been fixed. See https://github.com/jgm/pandoc/releases

```
pandoc -f docx -t latex minus-sign.docx 

\[= \ 1.0\ \overset{}{j}\  \times \ \left\lbrack 1.0\ \overset{}{j} \times \left( 0.1879\ \overset{}{i}\ -\ 0.0684\ \overset{}{j} \right) \right\rbrack\text{\ \ \ \ \ \ \ \ \ \ \ \ \ }\ m/s^{2}\text{\ \ \ \ \ }\]
\[= \  - \ 1.0\ \overset{}{j} \times 0.1879\ \overset{}{k}\text{\ \ \ \ \ \ }\ m/s^{2}\  = \  - \ 0.1879\ \overset{}{i}\text{\ \ \ \ \ \ \ \ \ }\ m/s^{2}\text{.\ }\]
```

**Comment by drtondo** [comment]
You are right indeed! Thanks.
