### ISSUE TITLE
Keeping lines around block element (figure environment) in LaTeX output together

### ISSUE THREAD

**Issue by wuffi** [jgm/pandoc#4655]
The issue I have is strongly related to <https://stackoverflow.com/questions/25952137/pandoc-adds-extra-paragraph-breaks>. The post concluded that it might be worth opening an issue here on GitHub:

pandoc adds empty lines before any block element like, for example, a figure float environment.

The problem now is that if the figure floats (as it is intended to), there is now space between the two parts of text that have code for the figure in between.

I already did extensive web search and tried to put the section into `\empty{}` or put a `noindent` but so far nothing had the desired effect.

**Comment by mb21** [comment]
Try with http://pandoc.org/MANUAL.html#generic-raw-attribute

**Comment by wuffi** [comment]
Thanks for the link, but it seems somehow unrelated to my question.
Isn't the link about how to include code in a way that it is not modified by pandoc?

**Comment by mb21** [comment]
Well, it depends on the exact situation.. you'll have to post a specific example that you think is a bug.

For question, please post to pandoc-discuss.

**Comment by wuffi** [comment]
The problem occurs with the following minimal example:

    ---
    output: pdf_document
    ---
    
    This is my first paragraph. 
    Next in the Rmd file would be the code for the figure.  
    The figure is correctly treated as a float by LaTeX, meaning that LaTeX will put it to the next suitable position.
    ```{r pressure, echo=FALSE, fig.cap="Example", out.width='0.5\\textwidth', fig.pos='B'}
      plot(pressure)
    ```
    The problem now is, that this leaves space to my second paragraph.
    Usually, this should not be the case.
    In pure LaTeX, there is a linebreak, of course, but no vertical space in addition.

**Comment by jgm** [comment]
Pandoc parses this as two paragraphs with a code block between.
If you just want a single paragraph, then put the code block before or after.

**Comment by wuffi** [comment]
Thanks a lot for your help and answers.
I thought a lot about putting the code block before or after, but there situations, where it really makes a difference:  
If there is sufficient space, it is much better to have the image right after the part of the text which refers to it.  
If there isn't, it is okay to have the float moved, but a newline would be sufficient to emphasize the beginning of a new idea/part of the text.  
`Pandoc`'s behavior surprises me in this case. To be honest, I can't really imagine a case, where it the new paragraph would be the better solution.  
Adding a new paragraph manually would always work, whereas I don't know how to remove the blank line between the two paragraphs in the output.
Although some might argue that this is a issue of minor importance, having illustrations close to the text which refers to them is for me a major determinant of readability. 
This would help readers a lot to understand texts written with `pandoc` as easy as possible.

**Comment by wuffi** [comment]
Thanks a lot, this workaround helped me a lot.
