### ISSUE TITLE
Docx image caption is not inside image

### ISSUE THREAD

**Issue by pyssling** [jgm/pandoc#4656]
On the latest master (2.2.1) I tried generating a docx with an image caption (reusing the imageWithCaption.native from the odt test-cases.) For odt this creates an image with an associated caption, but on docx the caption is a free-floating piece of text (but with the correct style).

It would be a nice improvement for pandoc to create images with associated captions for Docx as it does for ODT.

**Comment by jgm** [comment]
If you happen to know what the internal XML should look like for
that (or can attach or link to a small docx that has an associated
caption), that would be helpful.

**Comment by pyssling** [comment]
Ok, I had a look in word today and it seems that this "feature" is LibreOffice specific, i.e. Word doesn't let you attach a caption to a figure permanently. So I'm closing this.
