### ISSUE TITLE
Removing \strut breaks table entries with anchors

### ISSUE THREAD

**Issue by ptoboley** [jgm/pandoc#4660]
Using pandoc 2.1.3 ("Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.1")

The fix for issues #3436 (https://github.com/jgm/pandoc/commit/f3d81056d66147a42587607a3f8926c0baf06b7e) breaks the following case because of the removal of \strut:

```
The following table contains anchors so I can create links to entries:

+------------------------------+-------------+
| <span id="anchor_1">1</span> | Test case 1 |
+------------------------------+-------------+
| <span id="anchor_2">2</span> | Test case 2 |
+------------------------------+-------------+
```

The resulting output in LaTeX renders poorly, with the link text dropped down below the baseline. I'm not a LaTeX expert, but it appears the removal of the \strut from the output by the above fix "causes" this.

![image](https://user-images.githubusercontent.com/39366643/40165613-59aa2fde-59b4-11e8-89c2-bc82dfd9ced9.png)

I will also acknowledge that the problem the above fix solves is likely to be a more common problem for users than this rather more obscure case!

**Comment by ptoboley** [comment]
(By the way, we work around this by adding a RawInline \strut before the anchor.)

**Comment by tarleb** [comment]
It appears that this has been fixed, as I can no longer reproduce it with pandoc 2.13.
