### ISSUE TITLE
Advise users about size of homebrew installation

### ISSUE THREAD

**Issue by briatte** [jgm/pandoc#4661]
Perhaps the page at http://pandoc.org/installing.html could help users by mentioning that `brew install pandoc` requires a lot of disk space (over 1GB for `ghc` and `cabal`), whereas the installer version of pandoc takes only a few dozens MB.

The page already mentions something similar about LaTeX.

**Comment by briatte** [comment]
Thank you very much!

**Comment by mb21** [comment]
I guess somebody could also make a brew package with a precompiled binary...

**Comment by iandol** [comment]
I think this documentation change is not correct. Homebrew uses binary bottles that are precompiled by the Homebrew servers. So in 99% of the cases installing via Homebrew installs from the bottle, no need to install the build dependencies at all. In rare cases (I think when a package was just updated before the bottle is available, possibly if a network error causes the bottle download to fail but not a source sdownload, and possibly for an unsupported OS version), it will build from source, but this is not the default behaviour!

**Comment by iandol** [comment]
I just checked the standard Pandoc formula and confirmed it does use binary packages (bottles in brew speak) for the last 3 OS releases:

```ruby
class Pandoc < Formula
  include Language::Haskell::Cabal

  desc "Swiss-army knife of markup format conversion"
  homepage "https://pandoc.org/"
  url "https://hackage.haskell.org/package/pandoc-2.2.1/pandoc-2.2.1.tar.gz"
  sha256 "fe037f5fbb62fb27e7b1dbddfbd0aa45ea6e9fcdaff1f2203f7484c245b211b7"
  head "https://github.com/jgm/pandoc.git"

  bottle do
    sha256 "3e14ae13d451490f931a168939397987ce5934cd687b0f48d4b6c920d1a0d129" => :high_sierra
    sha256 "2d58d3cdb84a1f95682d9b5b4f15d4881824886784ef9c79434e4500c911aa5c" => :sierra
    sha256 "c57339f27a8a8039d5639d305f59e0b399403ae5c7a96e747425d3084f19191e" => :el_capitan
  end
```

**Comment by briatte** [comment]
In that case, perhaps the documentation note can be restricted to older OS releases? I do not know whether Pandoc follows Homebrew in its support only of recent OS releases, and [it seems](http://gs.statcounter.com/macos-version-market-share/desktop/worldwide) at least 5% of users have not jumped to 10.10+.
