### ISSUE TITLE
Description list containing only (fenced) code block

### ISSUE THREAD

**Issue by aubertc** [jgm/pandoc#4662]
The following:

```
Here is the header of a description list
~ ~~~{.sqlmysql}
SELECT * FROM;
~~~
```

renders, using ` pandoc MWE.md -o MWE.pdf`:

![image](https://user-images.githubusercontent.com/16466689/40275486-f8f84052-5bbd-11e8-9812-01d4582cdf13.png)

```
pandoc -v
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.0.2
Default user data directory: /home/caubert/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by aubertc** [comment]
I realize my example is not as minimal as it could be.

     Header
     ~ ```
     Code
     ```

(or the same code, replacing \` with ~)  yields a correct 

![image](https://user-images.githubusercontent.com/16466689/40347549-b271fc06-5d6e-11e8-8323-68bac91398cf.png)

But 

     Header
     ~ ```bash
     Code
     ```

yields

![image](https://user-images.githubusercontent.com/16466689/40347574-c8e4bea6-5d6e-11e8-904b-7ed20b82cfe1.png)

The same goes with any syntax highlighting, as far as I can tell.

**Comment by mb21** [comment]
I can confirm this. The produced intermediary LaTeX is:

```
\begin{description}
\item[Header]
\begin{Shaded}
\begin{Highlighting}[]
\ExtensionTok{Code}
\end{Highlighting}
\end{Shaded}
\end{description}
```

Not sure what we'd need to change... maybe somethings in the template...

**Comment by aubertc** [comment]
A workaround is to add a space, creating a new line:

```
Header
~ \ 

    ```bash
    Code
    ```
```

gives

![image](https://user-images.githubusercontent.com/16466689/40469907-f99301e2-5eff-11e8-871b-a22193485ebc.png)

the intermediate LaTeX being


```
\begin{description}
\item[Header]
~
\begin{Shaded}
\begin{Highlighting}[]
\ExtensionTok{Code}
\end{Highlighting}
\end{Shaded}
\end{description}
```
