### ISSUE TITLE
New command Latex function disappears after compiling

### ISSUE THREAD

**Issue by sammo3182** [jgm/pandoc#4667]
Not sure since when (but must be in a month), rmarkdown files fail to include latex functions created by \newcommand when compiling, no matter I added them in the yaml or the main content. The preload latex function still works, though.

The minimal repro:

test.md:
```r
---
title: "Newcommand"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---


testing lines 1

\blandscape

testing lines 2

\elandscape


\begin{landscape}

testing lines 3

\end{landscape}

```

Output:

```r
$ pandoc -f markdown -t latex test.md
testing lines 1

testing lines 2

\begin{landscape}

testing lines 3

\end{landscape}
```

**Comment by jgm** [comment]
The problem is related to the fact that the macro evaluates to the open command for an environment.  If you replace `\begin{landscape}` with say `\emph{landscape}` in the definition, it comes through.

**Comment by jgm** [comment]
Confirmed that the regression was introduced in pandoc 2.2 release.
Undoubtedly because of this item:

> Improve handling of raw LaTeX (for markdown etc.) (#4589, #4594). Previously there were some bugs in how macros were handled.

**Comment by jgm** [comment]
Here's how you can work around this.  Put the macro definitions in your header inside an explicit raw LaTeX block. This prevents them from being parsed at all by pandoc.
```
---
title: "Newcommand"
header-includes:
- ```{=latex}
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\emph{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  ```
---
```

**Comment by sammo3182** [comment]
I'm using your code above with Rmarkdown. It doesn't work and shows the following message:

```
Error in yaml::yaml.load(string, ...) : 
  Scanner error: while scanning for the next token at line 3, column 3 found character that cannot start any token at line 3, column 3
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load_utf8 -> <Anonymous>
Execution halted
```

If I do 

```latex
---
title: "Newcommand"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\emph{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---
```
the file compiles but it just added an Italic `\blandscape`. That's it.

I'm using Pandoc 2.2.1., by the way.

**Comment by jgm** [comment]
Try this:
````
---
title: "Newcommand"
header-includes:
- |
  ```{=latex}
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\emph{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  ```
---
````

**Comment by sammo3182** [comment]
This only works when I changed `\emph` to `\begin` actually. But thank you for the solution! That helps a lot!

**Comment by sammo3182** [comment]
The above codes work well until calling the `kableExtra` package. Here's a sample code:

````
---
title: "Untitled"
header-includes:
- |
  ```{=latex}
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  ```
output: pdf_document
---

```{r setup, include=FALSE}
library(kableExtra)
```
````

The compiled file led to a `LaTex Error`:

````
! LaTeX Error: Missing \begin{document}.

Error: Failed to compile test.tex. See test.log for more info.
Execution halted
````

If moving `library(kableExtra)` or changing to other package, the file compiled smoothly.

**Comment by jgm** [comment]
This looks like something rmarkdown is doing, not
pandoc itself, so you should report there.

**Comment by sammo3182** [comment]
Thank you! I will send an issue to them.
