### ISSUE TITLE
How would you like to accept a dedicated zsh completion?

### ISSUE THREAD

**Issue by doronbehar** [jgm/pandoc#4668]
This is not a usage question and not a bug report. I'm writing an extensive ZSH completion function for `pandoc`. I wanted to ask if you'd like to accept a separate file that will be compiled into `pandoc` like [`/data/bash_completion.tpl`](https://github.com/jgm/pandoc/blob/499c91dd9698c15bac2667a90b2b3ddc1a0f1930/data/bash_completion.tpl) or perhaps just a `_pandoc` file that won't be compiled into `pandoc` is a better way to do it?

**Comment by jgm** [comment]
If you can create a template that works like the bash_completion.tpl,
we'd consider compiling it in.

**Comment by doronbehar** [comment]
The completion is finished, the final result can be [found here](https://gist.github.com/doronbehar/134d83ae75309182d9fad8ecd7a55daa). Usually, when one uses ZSH, it is common to just put completion files (named `_<command>`) somewhere in the `$fpath`. I tend to advice that it will be better for the pandoc project to put the completion in a file named `_pandoc` inside [`data/`](https://github.com/jgm/pandoc/tree/499c91dd9698c15bac2667a90b2b3ddc1a0f1930/data) and advice packagers to put it in `/usr/share/zsh/site-functions/`.

P.S I would like to create a PR with my 12 commits progress on this completion so please don't just copy it from the gist and put it where you want.

**Comment by jgm** [comment]
One worry I have about this is that it contains a full list of all the pandoc options and their documentation.  Hence, it will need constant updating every time pandoc's options change.  (The same is not true of the bash completion template.)  Indeed, it is already a bit out of date.

Adding this would increase the maintenance burden going forward.

**Comment by doronbehar** [comment]
Part of my ZSH completion is generated (and updated) automatically - everything related to input and output formats including their extensions, that's thanks to `pandoc --list-{out,in}put-formats` and `pandoc --list-extensions=<format>`.

In addition, I'm subscribed to pandoc's announcements mailing lists so they reach my INBOX. I'm ready to be in charge of updating the completion when needed, in compliance with the releases of course and through the active development.

**Comment by jgm** [comment]
The problem is that the zsh completion script would need to be updated *before* a release (and hence before a release announcement).  To keep it in sync, it would need to be changed whenever there is a change in any of the options.

**Comment by jgm** [comment]
For this reason, I wonder whether it wouldn't make more sense to put your completion script where you originally had it -- in the zsh repository.  Then you could update it in response to pandoc updates, and it would be one less thing for me to worry about prior to a release.  Your .tpl is not really a template file anyway, in the sense of bash_completion.tpl, which gets variables filled in by pandoc itself, so there is less reason to keep it with pandoc.

**Comment by doronbehar** [comment]
I tend to agree with this approach as it is taken by most other projects. I would have suggested contributing my completion to zsh's repository but I noticed pandoc has bash completion so I thought my zsh completion should complement it.

**Comment by jgm** [comment]
OK, let's do it this way, then.  Thanks for creating the completion script!

**Comment by alok** [comment]
@doronbehar I dunno where you decided to put your script, but you should know that it has an option to sed that will break on macos. Use `sed -n` instead of `sed --quiet`.

**Comment by doronbehar** [comment]
Got it, thanks! I'll be contributing it to the main zsh repository. I have some pending patches discussed already with the mailing list, as soon as I'll finish those I'll suggest adding my completion of pandoc as well.
