### ISSUE TITLE
markdown should be more flexible regarding newlines

### ISSUE THREAD

**Issue by ghost** [jgm/pandoc#467]
`markdownToHtml = writeHtml myWriterOptions . readMarkdown defaultParserState`

If I apply it to a markdown string:
`"header\n=======\nA line of text.\n### A list ###\n- apple\n- orange\n- pear"`

I end up with:
`"<h1 id=\"header\">header</h1>\n<p>A line of text. ### A list ### - apple - orange - pear</p>"`

All other implementations allow a single newline from what I can tell.
Notice how it is correctly parsed by github below:
# header

A line of text
### A list
- apple
- orange
- pear

**Comment by pwall2222** [comment]
To fix this you can use the `gfm` and the feature `+hard_line_breaks`.
