### ISSUE TITLE
Markdown to DokuWiki Code Blocks Issue

### ISSUE THREAD

**Issue by runeimp** [jgm/pandoc#4671]
pandoc 2.2.1 on macOS Sierra 10.12.6

### Attempting

Convert Markdown documents to DokuWiki format

### Expectation

Something like

<pre><code>
```json
{
    "json": "document",
    "keys": 2
}
```
</code></pre>

Should convert to

```
<code json>
{
    "json": "document",
    "keys": 2
}
</code>
```

### What's Happening

Code is being converted to:

`''%%json {    "json": "document",    "keys": 2} %%''`

when converting to DokuWiki format. Which would be almost acceptable if that didn't kill newlines in the transition and newlines added back into the code block weren't ignored using that syntax.

I have an example gists with a source [Mardown](https://gist.github.com/runeimp/f14a504f6cb402856c23d27decc133ac) and [DokuWiki](https://gist.github.com/runeimp/306ad1c92c8d3f661108ab2ef4f7bac7) output.

Converting inline code to the `''%% code %%''` syntax is fine and works well. Just the fenced code blocks seem to be a problem.

**Comment by jgm** [comment]
Oh, I see you listed the version.  Are you really getting this result?
That's hard to explain.  Perhaps you had some other content on the line with the backticks, which caused it to be interpreted as inline code?
