### ISSUE TITLE
Installation of Pandoc for Rstudio

### ISSUE THREAD

**Issue by pranavpawar3** [jgm/pandoc#4673]
Asking a question?
Please use the pandoc-discuss mailing list instead:
https://groups.google.com/forum/#!forum/pandoc-discuss
This tracker is for bug reports and enhancement requests.

Reporting a bug?
Please include your pandoc version and an example that allows us
to reproduce the problem (complete input, exact command line
used, expected and actual output).  The smaller the example, the
better.

I have installed Pandoc-2.2.1 from the authorised website of pandoc install. But i couldn't set it up for Rstudio. Whenever i tried to change my Rmd file to HTML notebook i got following error;
`Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).`
And after running 
```
> rmarkdown:::find_pandoc()
> as.list(rmarkdown:::.pandoc)
```
following output is printed:
```
$version
NULL
$dir
NULL
```
 Can you please guide me for setting it up for Rstudio?

**Comment by mb21** [comment]
please search on stackoverflow.com or ask the rstudio people...

**Comment by pranavpawar3** [comment]
Thanks for your reply,
I installed RStudio again and then the error got fixed.

**Comment by ImSanjayChintha** [comment]
can I know which r studio version you installed in your system, because I am facing same issue
