### ISSUE TITLE
\subtitle undefined with LaTeX default template

### ISSUE THREAD

**Issue by MAccadia** [jgm/pandoc#4675]
Hi,

When I override `\maketitle` using header-include with this code :

```yaml
---
title:  "De la possibilité et de la réalité de l'introspection"
subtitle: "Une exploration intérieure"
author: "Archibald Dulapin"
header-includes:
  - |
    ```{=latex}
    \makeatletter
    \renewcommand{\maketitle}{%
        \@title

        \@author
        
        \@subtitle
    }
    \makeatother
    ```
...
```

I get the following error with _pandoc 2.2.1_:

```
$ pandoc test.yml -o test.pdf
Error producing PDF.
! Undefined control sequence.
\maketitle ...title \par \@author \par \@subtitle 
                                                  
l.73 \maketitle
```

It works if I use a modified default.latex template with :
```latex
\makeatletter
\providecommand\subtitle[1]{\renewcommand\@subtitle{#1}}
\providecommand\@subtitle{\@latex@error{No \noexpand\subtitle given}\@ehc}
\makeatother
\subtitle{$subtitle$}
```

I don't know if this code could have any side effect ; I don't understand it well enough. I got it from [here](https://stackoverflow.com/questions/2833954/how-do-i-create-a-command-like-title-in-latex).

As for a workaround, putting the `\providecommand`s in header-include works.

**Comment by mb21** [comment]
Please ask questions this on pandoc-discuss. This tracker is for issues only.

(btw, tot sure what you're asking anyway...)

**Comment by MAccadia** [comment]
Hi, sorry if I wasn't clear. 

My point is that the [default.latex](https://github.com/jgm/pandoc-templates/blob/master/default.latex) template could be improved with :
```latex
$if(subtitle)$
\makeatletter
\providecommand\subtitle[1]{\renewcommand\@subtitle{#1}}
\providecommand\@subtitle{\@latex@error{No \noexpand\subtitle given}\@ehc}
\makeatother
\subtitle{$subtitle$}
$endif$
```

instead of

```latex
$if(subtitle)$
\providecommand{\subtitle}[1]{}
\subtitle{$subtitle$}
$endif$
```
