### ISSUE TITLE
allow passing the tag to use for html math output

### ISSUE THREAD

**Issue by cjerdonek** [jgm/pandoc#4676]
Thank you for a superb tool! I'd like to suggest a new command-line option for html math rendering. It would be a slightly more general variation of an existing option (`--gladtex`).

The idea is to allow passing a tag that would then be used to enclose TeX math. It could be something like `--mathtag=TAG`, in which case `--gladtex` would be the same as `--mathtag=eq`.

There are a couple reasons for this:

One is that it would provide a programmatic way to robustly find all of the html that was originally encoded as TeX math (e.g. by passing a custom tag known to be unique).

The second is that it would let one guarantee that all of the math in the html output is "well-formed."

For example, with the current `--gladtex` option (which comes closest to what I'm suggesting), the following Markdown input:

    math: $x = 1 <b>bad</b>$

    math: <eq env="math">x = 1 <b>bad</b></eq>

gives (using Pandoc 2.2.1)--

    $ pandoc -f markdown -t html5 --gladtex test.md

    <p>math: <eq env="math">x = 1 &lt;b&gt;bad&lt;/b&gt;</eq></p>
    <p>math: <eq env="math">x = 1 <b>bad</b></eq></p>

Observe that the second paragraph didn't come from the originally encoded TeX math, and it isn't well-formed. So users would need to do additional processing to detect and fix up content like the second line.

**Comment by cjerdonek** [comment]
Thanks for noting that, @mb21. It would still be nice if this can be added.

Here's the logic that would need to be duplicated in a lua filter (note that it's not just setting the tag name, but also correctly setting the attribute values):
https://github.com/jgm/pandoc/commit/b7356d3ddf788d83b41b1100d718087bd83a7506#diff-9da4893eeab88b87f94db2b69af787ffR1032

**Comment by jgm** [comment]
> The second is that it would let one guarantee that all of the math in the html output is "well-formed."

I'm not sure how it would do this.  No matter what you choose as your custom tag, you could reproduce the sort of example you give above, substituting the custom tag for `<eq>`, couldn't you?

**Comment by cjerdonek** [comment]
I meant for my parenthetical remark "by passing a custom tag known to be unique" to apply to both reasons and not just the first. The idea is that before calling pandoc, you can choose a custom tag that you know doesn't occur, for example by choosing a sufficiently long random string: `''.join(random.choices(string.ascii_lowercase, k=20))`. If you were paranoid, you could check that the string doesn't occur in the document as a substring, but if the string is long enough, you wouldn't need to do this for probability reasons.

Note that, just to be clear, this approach assumes that the user is already doing some post-processing of the resulting html, at which point the custom tag elements can be replaced by something more reasonable, etc. This is what I meant by "robustly find all of the html that was originally encoded as TeX math."

**Comment by mb21** [comment]
Still think this is best solved with a pandoc filter. Thus closing.
