### ISSUE TITLE
Pandoc loses image Caption when writing to Markdown (switching link_attributes force switches implicit_figures as well)

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#4677]
Here I use special markdown flavour. This flavour is of interest because it's useful for exporting to Jupyter notebook markdown with cross-references in [Pandoctools](https://github.com/kiwi0fruit/pandoctools) (see [the last example](https://github.com/kiwi0fruit/knitty#usage)).

**Pandoc version**: 2.2.1

## 1. issue case (to Markdown flavor):
```sh
echo '![Caption](img.png){#img:1}' | pandoc --to "markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions-smart"
```
output:
```html
<img src="img.png" alt="Caption" id="img:1" />
```

## 2. to HTML:
```sh
echo '![Caption](img.png){#img:1}' | pandoc --to html
```
output:
```html
<figure>
<img src="img.png" alt="Caption" id="img:1" /><figcaption>Caption</figcaption>
</figure>
```

## 3. to standard Pandoc Markdown:

```sh
echo '![Caption](img.png){#img:1}' | pandoc --to markdown
```
output:
```
![Caption](img.png){#img:1}
```

# Test if changing to behaviour in 2. makes sence in case of special markdown flavor

## 1.
```sh
echo '<figure><img src="img.png" alt="Caption" id="img:1" /><figcaption>Caption</figcaption></figure>' | pandoc --from markdown --to markdown
```
output:
```html
<figure>
<img src="img.png" alt="Caption" id="img:1" />
<figcaption>
Caption
</figcaption>
</figure>
```

## 2.
```sh
echo '<img src="img.png" alt="Caption" id="img:1" />' | pandoc --from markdown --to markdown
```
output:
```html
<img src="img.png" alt="Caption" id="img:1" />
```

## 3.
```sh
echo '<figure><img src="img.png" alt="Caption" id="img:1" /><figcaption>Caption</figcaption></figure>' | pandoc --from html --to markdown
```
output:
```html
![Caption](img.png){#img:1}
```

## 4.
```sh
echo '<img src="img.png" alt="Caption" id="img:1" />' | pandoc --from html --to markdown
```
output:
```html
![Caption](img.png){#img:1}
```

**Comment by mb21** [comment]
I don't understand. What exactly is the expected and actual output of what exact input/command?

**Comment by kiwi0fruit** [comment]
I expect Pandoc not to lose image caption during export so it's a bug report (now Pandoc looses caption that is under the picture).

input:
```sh
echo '![Caption](img.png){#img:1}' | pandoc --to "markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions-smart"
```
real output:
```html
<img src="img.png" alt="Caption" id="img:1" />
```
expected output:
```html
<figure>
<img src="img.png" alt="Caption" id="img:1" /><figcaption>Caption</figcaption>
</figure>
```

**Comment by mb21** [comment]
Your output format is markdown with a lot of disabled extensions (maybe you're looking for `--to markdown_strict`, or `--to html` ?)

It's not clear why one HTML fallback should be preferred to another one. The information (the string "Caption") is still there in both.

See for example also the [`link_attributes`](http://pandoc.org/MANUAL.html#extension-link_attributes) extension.

**Comment by kiwi0fruit** [comment]
The short variant is expected behaviour of `markdown_strict`. The long varian is default Pandoc befavior. They are actually different content (not just another encoding of the equal content).

from `"markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions-smart"`: we didn't disable text caption and disabled some features of default Pandoc Markdown. So I expect to have same content as default Pandoc Markdown but encoded differently.

it's also consistent with:
```sh
echo '<figure><img src="img.png" alt="Caption" id="img:1" /><figcaption>Caption</figcaption></figure>' | pandoc --from html --to markdown
```
out:
```
![Caption](img.png){#img:1}
```

**Comment by mb21** [comment]
> They are actually different content (not just another encoding of the equal content).

how so? the alt text and caption are the same, are they not?

From the `implicit_figures` extension:

> The image’s alt text will be used as the caption.

It would also help if you would remove the disabled extensions that are unrelated to this discussion.

**Comment by kiwi0fruit** [comment]
> how so? the alt text and caption are the same, are they not?
No, in the short variant there is no caption at all. The caption is present only in long variant. `alt` html attr is not a caption.

**Comment by mb21** [comment]
> alt html attr is not a caption.

For better or worse, by the current definition of the `implicit_figures` extensions and how it's implemented in pandoc, it is the same.

So I don't think we need to change anything here...

**Comment by kiwi0fruit** [comment]
So that's the `implicit_figures`... The second responsible is `link_attributes`.

I know that `implicit_figures` are already in `markdown` so I write this way only to be explicit:

## Should have long html version with caption:

```sh
echo '![Caption](img.png){#img:1}' | \
pandoc --from "markdown+implicit_figures" --to html
# it's OK now
```

```sh
echo '![Caption](img.png){#img:1}' | \
pandoc --from "markdown+implicit_figures" --to "markdown+implicit_figures-link_attributes"
# it's buggy now
```

## Should have short html version (without caption):

```sh
echo '![Caption](img.png){#img:1}' | \
pandoc --from "markdown-implicit_figures" --to "markdown-implicit_figures-link_attributes"
# it's OK now
```

```sh
echo '![Caption](img.png){#img:1}' | \
pandoc --from "markdown+implicit_figures" --to "markdown-implicit_figures-link_attributes"
# it's OK now
```

```sh
echo '![Caption](img.png){#img:1}' | \
pandoc --from "markdown-implicit_figures" --to html
# it's OK now (note: extra <p>...</p>)
```

**Comment by kiwi0fruit** [comment]
The key point: switching `link_attributes` should not force switch `implicit_figures` as well. It definitely looks like a bug.

**Comment by jgm** [comment]
Some confusing behavior here:
```
[1]% echo '![Caption](img.png){#img:1}' | pandoc --to "markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions-smart"
<img src="img.png" alt="Caption" id="img:1" />

[2]% echo '![Caption](img.png){#img:1}' | pandoc --to "markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions-smart" -t native
[Para [Image ("img:1",[],[]) [Str "Caption"] ("img.png","fig:")]]

[3]% echo '![Caption](img.png){#img:1}' | pandoc --to "markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions-smart" -t native | pandoc -f native -t html
<figure>
<img src="img.png" alt="Caption" id="img:1" /><figcaption>Caption</figcaption>
</figure>

[4]% echo '![Caption](img.png){#img:1}' | pandoc --to "markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions-smart" -t html
<figure>
<img src="img.png" alt="Caption" id="img:1" /><figcaption>Caption</figcaption>
</figure>
```

I have no idea why explicitly adding `-t html` should make a difference here!

**Comment by kiwi0fruit** [comment]
Now I wonder if 

```
echo '![Caption](img.png){#img:1}' | \
pandoc --from "markdown-implicit_figures" --to html
```

```
echo '![Caption](img.png){#img:1}' | \
pandoc --from "markdown-implicit_figures" --to native | pandoc --from native --to html 
```

give the same result.
