### ISSUE TITLE
Pandoc ignores multiple include\input-s (latex -> docx)

### ISSUE THREAD

**Issue by quicky84** [jgm/pandoc#4680]
First of all, pandoc is a great tool!

Unfortunately pandoc ignores multiple include\input in latex files when converting to docx, only the first input\include gets included.

Working example is [here](https://github.com/quicky84/pandoc-latex)

Converting with 
```
pandoc -f latex -t docx -s -o main.docx main.tex
```

```
pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
```
My workaround is to use [latex_flatten](https://github.com/rekka/latex-flatten ) to flatten the file and then use pandoc.

**Comment by tarleb** [comment]
Alternative work-around: insert additional blank lines after each `\input{}`.

**Comment by quicky84** [comment]
Thanks @tarleb!
That's much easier, but I could not have guessed.
Still this is an issue, I believe.

**Comment by jgm** [comment]
This is essentially the same issue as #4553, so closing in favor of that.
