### ISSUE TITLE
custom-style not applied in odt output

### ISSUE THREAD

**Issue by AugustH** [jgm/pandoc#4684]
using the sample from the manual as `sample.md`

```
Dickinson starts the poem simply:

::: {custom-style="Poetry"}
| A Bird came down the Walk---
| He did not know I saw---
:::
```

running `pandoc -N -f markdown+fenced_divs -o sample.docx sample.md` (pandoc 2.2)
gives a docx file with the text style set to `Poetry`.

Changing the output to `sample.odt` the text style isn't set in the odt file.

**Comment by mb21** [comment]
Duplicate of #2106
