### ISSUE TITLE
pandoc datafile is missing error

### ISSUE THREAD

**Issue by rankum01** [jgm/pandoc#4689]
I am converting html to docx. By using following pandoc command:
pandoc htmlfilename -o docxfilename
On local system, it works fine. On amazon elastic beanstalk, it throws an error.
    Could not find data file /home/ec2-user/.cabal/share/x86_64-linux-ghc-8.4.2/pandoc- 
    2.2.1/data/abbreviations
    return code of pandoc system call is 97
When I ssh to ec2 instance, file is present there.
pandoc version is 2.2.1

**Comment by mb21** [comment]
Sounds like you didn't install pandoc properly... please ask questions like this on pandoc-discuss.

**Comment by mb21** [comment]
Closing in favour of https://stackoverflow.com/questions/50716981/pandoc-error-datafile-is-missing

**Comment by danse** [comment]
i am also having some portability problems for a pandoc wrapper and i found out that there is a `pandoc:embed_data_files` flag that can be used at compile time in order to embed the data files in the pandoc executable. This could be useful to @rankum01

**Comment by dorianmariecom** [comment]
For me the solution was to install the deb file and not pandoc on ubuntu:

```
https://github.com/jgm/pandoc/releases/download/3.1.12.1/pandoc-3.1.12.1-1-amd64.deb
```
