### ISSUE TITLE
LaTeX/pdf output error: ? + “ (German closing quote) -> ¿‘

### ISSUE THREAD

**Issue by f34739** [jgm/pandoc#4695]
pandoc converts this input (`test.txt`) which includes a question and an exclamation mark in front of closing German quotation marks:

```
„Was?“ – „Das!“
```

to the following LaTeX code (command line: `pandoc -t latex test.txt`):

```
„Was?`` -- „Das!``
```

When generating a pdf (command line: `pandoc -t latex -o test.pdf test.txt`), the output is as follows:

> „Was¿‘ – „Das¡‘

For LaTeX itself (rather than pandoc) the exact same problem has been described previously at https://tex.stackexchange.com/questions/159110/avoid-inverted-exclamation-and-question-marks-when-followed-by-quotes.

One possible solution mentioned in the stackexchange thread is to have pandoc output the “real” UTF character (“LEFT DOUBLE QUOTATION MARK”). Since pandoc seems to output many other UTF characters when generating LaTeX, including the opening German double quotes, I can’t imagine any problems with this approach.

**Comment by jgm** [comment]
The solution is to use

    pandoc -t latex-smart

(together with xelatex, if you're producing a PDF).  That will
prevent the conversion to a ligature.

**Comment by f34739** [comment]
Ok, `latex-smart` does work. Still, I feel that with or without `smart`, pandoc should never convert `?“` to `¿‘` since it’s safe to say that the latter is never correct given this input.
