### ISSUE TITLE
Pandoc  failing to convert valid xelatex file

### ISSUE THREAD

**Issue by kashcit** [jgm/pandoc#4698]
When running `pandoc --from latex --pdf-engine=xelatex --to html5 skanda.tex -o skanda.tex.html
` upon this file https://github.com/hindutva/tex-files/blob/master/skanda/skanda.tex (on which `xelatex skanda.tex` works perfectly, assuming that the [siddhanta font](http://svayambhava.blogspot.com/p/siddhanta-devanagariunicode-open-type.html) is installed), I get the following error:

```
pandoc --from latex --pdf-engine=xelatex --to html5 skanda.tex -o skanda.tex.html

Error at "source" (line 102, column 1):
unexpected \end
\end{document}
^
```

**Comment by jgm** [comment]
It seems to be choking on this:
```latex
{\normalsize{\skt ॐ कं क्षं कं कार्त्तिकेयाय फट् ॥\\
ॐ श्रीं ह्रीं क्लीम् ऐं सौं शरवनभवाय नमः ॥\\
ॐ वचद्भुवे नमः ॥\\
ॐ भुवे नमः स्वाहा ॥\\
ॐ षं षण्मुखाय नमः ॥\\
ॐ श्रीम् ए इ उ न श्रीं रीं कुमाराय नमः ॥
}\\
```
It looks like the `{` before `\normalize` isn't matched by a close `}`, and if you delete it this should work.

**Comment by vvasuki** [comment]
Thank you! It was indeed so.

However I found a separate problem: 
Images such as : 

```
\graphicspath{ {images/} }
...
    \includegraphics[width=0.5\textwidth]{kaumara_magic_square}
```
is converted to 
```
<img src="kaumara_magic_square" alt="The magic square Kaumāra-yantra" style="width:50.0%" />
```
rather than
```
<img src="images/kaumara_magic_square.jpg" alt="The magic square Kaumāra-yantra" style="width:50.0%" />
```
.

**Comment by kashcit** [comment]
Thank you! It was indeed so.

However I found a separate problem: 
Images such as : 

```
\graphicspath{ {images/} }
...
    \includegraphics[width=0.5\textwidth]{kaumara_magic_square}
```
is converted to 
```
<img src="kaumara_magic_square" alt="The magic square Kaumāra-yantra" style="width:50.0%" />
```
rather than
```
<img src="images/kaumara_magic_square.jpg" alt="The magic square Kaumāra-yantra" style="width:50.0%" />
```
.

**Comment by jgm** [comment]
This second problem isn't really a bug either.
In LaTeX you can leave off the image extension.
Pandoc isn't just going to guess what it should be.

However, you can use the --default-image-extension
option if you want these to all default to, say, jpg.


Vishvas Vasuki विश्वासः <notifications@github.com>
writes:

**Comment by kashcit** [comment]
Thanks for the tip - that solves the image extension problem!

However, it doesn't address pandoc ignoring: `\graphicspath{ {images/} }`, which was also illustrated in https://github.com/jgm/pandoc/issues/4698#issuecomment-396450492 ..

**Comment by jgm** [comment]
You don't mention your pandoc version.  In recent pandoc, `\graphicspath` is indeed supported. However, it won't rewrite the path unless you also use `--extract-media`.  (Path rewriting doesn't make sense in general since `\graphicspath` can contain multiple directories, but it makes sense with `--extract-media`.)

So,
```
pandoc -f latex --default-image-extension .jpg --extract-media=mymedia
```

However, there's still a small issue.  I noticed that pandoc chokes on the spaces inside the argument of `\graphicspath`.  Removing them will make it work:
```
\graphicspath{{images/}}
```
I can fix this.

**Comment by vvasuki** [comment]
Thank you!
