### ISSUE TITLE
Support for Slack Formatting

### ISSUE THREAD

**Issue by omarish** [jgm/pandoc#4705]
It'd be great if we supported writing to Slack. I'll often write up a few paragraphs of text in my preferred markdown editor, only to lose formatting because slack formatting differs from Markdown. Moreover, Slack does not plan to support markdown.

https://api.slack.com/docs/message-formatting

**Comment by omarish** [comment]
Nice, ok. I looked through the spec and added a list of formatting types we might support.

**Comment by mb21** [comment]
Yes, I had listed those already, with the exception of links/URLs which are not supported...

**Comment by omarish** [comment]
RE: urls - I wonder if there's a way we could incorporate this? https://api.slack.com/docs/message-formatting#linking_to_urls

**Comment by omarish** [comment]
@mb21 here's a very rough draft of the writer. The code isn't great yet since this is my first haskell project and I'm mostly pattern matching. Thoughts so far?

https://github.com/jgm/pandoc/pull/4706

**Comment by mb21** [comment]
Closing this, since Slack is really not a full document format.

Use a custom writer instead, like @marish's https://github.com/omarish/pandoc-md-to-slack
