### ISSUE TITLE
Suggestion: add instruction set to output of `pandoc --version` (whether x86-64)

### ISSUE THREAD

**Issue by Wolf-at-SO** [jgm/pandoc#4710]
Currently the command line argument `--version` gives me this output (on Windows):

```
C:\Users\Me>pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
Default user data directory: C:\Users\Me\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

I understand that it absolutely makes sense to keep the first line as it is, because someone may have to extract the information by a program. But in the rather free formatted text after this line mentioning whether it's 32 or 64 bits could be of help to decide for the best matching update (the command line is much faster than checking the *Programs and Features* section in the *Windows Control Panel*)

**Comment by mb21** [comment]
There seems to be no easy, non-hacky way to do this, currently: https://stackoverflow.com/questions/6217406/how-can-i-detect-if-ghc-is-set-to-generate-32bit-or-64bit-code-by-default Thus I think it's out of scope.

You can also use the unix `file` command to check on a binary, like:

    file /path/to/pandoc

Or whatever the Windows equivalent to `file` is... maybe `dumpbin`?
