### ISSUE TITLE
lost space when converting Markdown to LaTeX

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#4712]
I see odd behaviour where a space is lost after interpunction when converting Markdown to LaTeX. This is my minimal test case:

```bash
echo -e "A, 'Y 'do' Z?' Foo.'" | pandoc -t latex
```

This produces:

```
A, `Y 'do' Z?`Foo.'
```

The space before `Foo` is lost.

**Comment by mb21** [comment]
This appears to be fixed on current master, since I get:

    A, `Y 'do' Z?' Foo.'

**Comment by wilx** [comment]
[**@mb21**](https://github.com/mb21) commented on [Jun 18, 2018, 10:53 AM GMT+2](https://github.com/jgm/pandoc/issues/4712#issuecomment-397986182 "2018-06-18T08:53:47Z - Replied by Github Reply Comments"):
> This appears to be fixed on current master, since I get:
> 
>     A, `Y 'do' Z?' Foo.'

Ah, yes, it seems so. I was testing with 2.2.
