### ISSUE TITLE
Could not fetch Image-Resource for pdf and docx-conversion (html-conversion works fine)

### ISSUE THREAD

**Issue by kehle** [jgm/pandoc#4714]
Since updating to the newest release (2.2.1.1 deb for Linux), pandoc gives an error message for every image located on servers (Wikipedia and Dropbox). Downgrading to an older version of pandoc did not solve the problem. Local Images in a folder work fine, but I need to embed images located on a server: 
Following error comes: 
[WARNING] Could not fetch resource 'https://upload.wikimedia.org/wikipedia/commons/9/91/Johann_natterer.jpg': HttpExceptionRequest Request {
    host                 = "upload.wikimedia.org"
    port                 = 443
    secure               = True
    requestHeaders       = []
    path                 = "/wikipedia/commons/9/91/Johann_natterer.jpg"
    queryString          = ""
    method               = "GET"
    proxy                = Nothing
    rawBody              = False
    redirectCount        = 10
    responseTimeout      = ResponseTimeoutDefault
    requestVersion       = HTTP/1.1
  }
Replacing image with description.

**Comment by mb21** [comment]
Cannot reproduce on macOS with:

    echo '![](https://upload.wikimedia.org/wikipedia/commons/9/91/Johann_natterer.jpg)' | pandoc --self-contained

**Comment by kehle** [comment]
Thank you very much for your fast testing and comment. My network connections were working, but after restart of my laptop everything is working fine now. I don't know the error but I think we should close the issue.
