### ISSUE TITLE
Pandoc errors out when trying to convert an empty file with file extension

### ISSUE THREAD

**Issue by adamliter** [jgm/pandoc#4717]
I haven't looked too closely at the codebase, so I'm not sure if this is a reasonable thing to request, but would it be possible to have `pandoc` first check whether a file is empty when trying to convert it, rather than first using the file extension in the name?

The use case for this would be for diffing new files in the working tree of a `git` repository against an empty file of the same name after you've indicated your intent to add the file to the index with `git add --intent-to-add` (or `-N`, for short).

Some details are here: [git diff not working with Word document, --intent-to-add, and pandoc diff driver](https://stackoverflow.com/q/50891512/2571049)

In brief, if you're trying to use `pandoc` as a diff driver for `git` for Word documents, it works in most cases except the corner case where you've introduced the Word document into the repository for the first time and want to see what the content of that file in your working tree is, in diff format. You can usually do this by running `git add -N`, which creates an empty file of that same name in the index, against which you can then diff the version of the file in the working tree.

But this causes `pandoc` to error out.

Steps to reproduce:

```sh
touch my_document.docx
pandoc --to=markdown my_document.docx
```

This is admittedly an edge case, and so if it's unreasonable given the codebase or would take some time to implement, feel free to just close the issue.

Thanks! 🎉

**Comment by mb21** [comment]
Isn’t this something you could check in the git driver? An empty file is not a valid docx file, so I think pandoc should error out and let the user know about it.

**Comment by adamliter** [comment]
@mb21 Hmm, I hadn't thought about that, since I'm not sure if there's a way to access the file name in the driver. But I guess it would be possible to create a script with, say, the following contents 

```sh
#!/usr/bin/env bash
if [ -s "$1" ]; then
    pandoc --to=markdown "$1"
else
    pandoc --to=markdown /dev/null
fi
```

And then use that script as the driver.

You're probably right that the error is the correct thing for pandoc to do in this case.

**Comment by mb21** [comment]
Sounds like the right approach.
