### ISSUE TITLE
Please teach commonmark the table_caption extension

### ISSUE THREAD

**Issue by petterreinholdtsen** [jgm/pandoc#4718]
The table_caption extension do not work with the gfm input format.  This make it impossible, as far as I can tell, to generate docbook from gfm with table captions.  Here is a simple example demonstrating the problem:

```
% cat x.md
# A simple table with caption

| **Navn**              | **Merknad**          | 
|-----------------------|----------------------|
| The name of the thing | The note on the name |

Table:  Demonstration of simple table syntax.
% pandoc --top-level-division=chapter -f gfm+table_captions -t docbook4 x.md -o x.xml
% cat x.xml 
<chapter id="a-simple-table-with-caption">
  <title>A simple table with caption</title>
  <informaltable>
    <tgroup cols="2">
      <colspec align="left" />
      <colspec align="left" />
      <thead>
        <row>
          <entry>
            <emphasis role="strong">Navn</emphasis>
          </entry>
          <entry>
            <emphasis role="strong">Merknad</emphasis>
          </entry>
        </row>
      </thead>
      <tbody>
        <row>
          <entry>
            The name of the thing
          </entry>
          <entry>
            The note on the name
          </entry>
        </row>
      </tbody>
    </tgroup>
  </informaltable>
  <para>
    Table: Demonstration of simple table syntax.
  </para>
</chapter>
%
```

I was able to get a better result using -f markdown_github+table_captions+auto_identifiers, but given that the markdown_github format is depricated, it would be great if the gfm format would be able to handle table captions too.

**Comment by mb21** [comment]
I think work on a new commonmark reader is underway on a separate branch: https://github.com/jgm/pandoc/tree/commonmark-github

**Comment by jgm** [comment]
Correct.  We can't implement most extensions without changes in the underlying C library, so the long term plan is to move to a pure Haskell library.
