### ISSUE TITLE
Tikiwiki reader should parse lists that have no space after list marker

### ISSUE THREAD

**Issue by drsassafras** [jgm/pandoc#4722]
when evaluating tikwiki, an unordered list is not evaluated.

example:

*list
**will not
**evaluate

**Comment by mb21** [comment]
Judging from the [documentation](https://doc.tiki.org/Wiki-Syntax-Lists#Creating_a_Nested_List), you have to put a space between the list marker and the first character.

**Comment by drsassafras** [comment]
hmm. Can you point out where it says that? I just read the documentation
and could not find mention of needing a space.

Instructions for making a list in tiki found on the documentation link you
quoted:

To create a bulleted list, do the following:


   1. Place the insertion point at the *beginning* of the line.
      2. Type an asterisk.
      3. Type the item's text.
      4. Press Enter.

I don't see any mention of placing a space after the asterisk.

I also loaded a tiki 12 and tiki 19 instance and tried it out. both worked
without a space.

Thoughts?

**Comment by mb21** [comment]
Agreed, the documentation is ambiguous.

> I also loaded a tiki 12 and tiki 19 instance and tried it out. both worked without a space.

Great, then this is a bug in pandoc.
