### ISSUE TITLE
Line-wrapping of HTML output is not supported in version 2.2.1

### ISSUE THREAD

**Issue by nrnrnr** [jgm/pandoc#4730]
When converting Markdown to HTML, pandoc 2.2.1 appears not to respect the combination of `--wrap` and `--columns` options.  I have recently upgraded from version 1.17.

Here is a short transcript that demonstrates the problem.  The output is not wrapped.

I have searched both open and closed issues and have not found any mention of this behavior.

````
nr@labrador ©105/c/hofs> pandoc --wrap=auto --columns=40
Since the general form of a simulation program is reasonably standard
(they all consist of collections of processes and resources, entities
and queues, or events), they have found it useful to have a template noweb
file which helps us in the program development as well. The
philosophy is always to have a running simulation program from the
beginning of the project. 
<p>Since the general form of a simulation program is reasonably standard (they all consist of collections of processes and resources, entities and queues, or events), they have found it useful to have a template noweb file which helps us in the program development as well. The philosophy is always to have a running simulation program from the beginning of the project.</p>
nr@labrador ©105/c/hofs> pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
Default user data directory: /home/nr/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
````

**Comment by mb21** [comment]
Well, there is this disclaimer in the MANUAL:

> Automatic wrapping does not currently work in HTML output.

**Comment by nrnrnr** [comment]
An unfortunate regression.  If this issue is intended not to be fixed, it would be good for the disclaimer to propagate into the Unix man pages, which might at present lead a user to conclude that the behavior is not expected.

Do we know what changed since 1.x?  I imagine if the problem could be solved simply, it would have been solved already.  I  can pipe the output from pandoc into `fmt(1)`, but that seems rather a big hammer.

**Comment by jgm** [comment]
The disclaimer is in the man pages, which are generated automatically from the manual.
Perhaps your man page has not been updated properly?

**Comment by jgm** [comment]
I thought that wrapping had never worked in HTML output, since we use the blaze-html library to generate it. Am I mistaken?

**Comment by nrnrnr** [comment]
@jgm, indeed, Cabal seems to have left several stray man pages.  Once I removed them, I get the appropriate disclaimer.

Regarding wrapping, we have just expunged the last vestiges of pandoc 1 from our systems, but I am confident that 1.19 or thereabouts did in fact wrap the HTML output.  (I have an emacs macro that pushes the current region through pandoc, which is how I noticed that something had changed.  I have updated the macro to push the results through `fmt(1)` as well, which is a bit disappointing, but can work.

**Comment by nrnrnr** [comment]
OK, given that I can't duplicate the change in behavior, I think it best just to close the issue.  If you have ideas about how line-wrapping might be supported from within pandoc, please add a comment to this issue---there's a (slim) chance I'll have a look and submit a PR.

**Comment by jgm** [comment]
Norman Ramsey <notifications@github.com> writes:

> I agree that speed is of the essence.
>
> Does the `--wrap=preserve` path also go through blaze-html?  If so, I'll give it a try.

Yes.
