### ISSUE TITLE
Modify warning when included file not found?

### ISSUE THREAD

**Issue by skurzinz** [jgm/pandoc#4736]
Pandoc version: 2.2.1

I have the following setup: 

`personal-hyphenation.tex` is residing in my `texmf-local` tree (FWIW it's actually a symlink to a version controlled file someplace else, but a test confirmed that even if the link is replaced by an actual file it is not found) and consists solely of `\hyphenation{word-list}`. `kpsewhich` finds the file, and so does `pdflatex`. 

In my .md sources I use `\include{personal-hyphenation.tex}` to load these patterns. 

Up until pandoc 2.1.3 (which was the last version I had installed), pandoc used find that file. Now I get a warning: 
> [WARNING] Could not load include file 'personal-hyphenation.tex' at line 1 column 25

**Comment by mb21** [comment]
Does it work if the file is not a symlink?

**Comment by skurzinz** [comment]
Temporarily tried replacing the symlink with a current copy of the file -- without success. Updated the original post accordingly.

**Comment by skurzinz** [comment]
Fun fact: the include actually works, but the warning remains. Same using `\input`.
With respect to functionality the issue could be closed, but a faux warning can still be considered a bug.

**Comment by jgm** [comment]
When you're converting latex, including latex embedded
in markdown, pandoc will try to find the included file
and parse it.  This is generally helpful.

When it can't, it issues the warning but passes the
`\include` command verbatim.  But the warning is still
helpful; it tells you that in this case pandoc was not
able to find the file and parse its contents.

**Comment by skurzinz** [comment]
Thanks @jgm! This perfectly explains pandoc's behaviour, which does a successful job in this case. 

Would it make sense to somehow reflect this in whe warning's text? Something like "[WARNING] Could not load include file $$$ at line $$$ column $$$, include command is passed on verbatim"?
