### ISSUE TITLE
Image alt tag and figcaption should be differentiated

### ISSUE THREAD

**Issue by matthewlehew** [jgm/pandoc#4737]
[As discussed in this thread on the discussion group,](https://groups.google.com/d/msg/pandoc-discuss/BefkPmp0x84/OYbnQcR9AAAJ) the behavior of captioning images is less than ideal for maintaining accessibility.

Currently, the bracketed text becomes both the alt tag and the figcaption:

``` 
![alt text](lalune.jpg) 

  -> 

<figure> 
<img src="lalune.jpg" alt="alt text" /><figcaption>alt text</figcaption> 
</figure> 
```

When wanting to create accessible documents, it is very often necessary to provide an alt tag that describes the image itself with a caption that provides extra explanatory content. Having them be the same doesn't align with their intended use.

Adding an additional descriptor creates a title tag, which is unhelpful in this instance:

``` 
![alt text](lalune.jpg "title") 

  -> 

<figure> 
<img src="lalune.jpg" title="title" alt="alt text" /><figcaption>alt text</figcaption> 
</figure> 
``` 

I propose amending the behavior so that the additional descriptor becomes the alt text and the bracketed text becomes the figure caption, with some other method used to derive the image title.

``` 
![caption text](lalune.jpg "alt text") 

  -> 

<figure> 
<img src="lalune.jpg" alt="alt text" /><figcaption>caption text</figcaption> 
</figure> 
``` 

**The additional benefit is that this would no longer require the unofficial method of escaping a space to suppress a caption and have it persist as solely an alt tag.** Instead, you would simply:

``` 
![](lalune.jpg "alt text") 

  -> 

<figure> 
<img src="lalune.jpg" alt="alt text" /> 
</figure> 
```

**Comment by mb21** [comment]
Should this be closed in favour of https://github.com/jgm/pandoc/issues/3177 ?

**Comment by reagle** [comment]
@mb21 I don't *think* so, I think you'd have to say more as how it would fit...?

**Comment by mb21** [comment]
It’s just that the current figure handling is somewhat of a hack and a proper figure elemtn int the AST, i.e. #3177, would handle caption and alt separately.

**Comment by matthewlehew** [comment]
@mb21 I agree. I missed #3177 when searching on this topic. It appears my issue is a subset of the issue raised there. 

My only additional comment is that #3177 should be considered high priority. The current way Pandoc handles figures is a serious hindrance for accessibility in academic publishing.

**Comment by reagle** [comment]
I don't see it as a subset. #3177 could be done and the request of #4737 would be unresolved. If the present concern was added to #3177, that would be great.

**Comment by matthewlehew** [comment]
I just added it to be sure, but my understanding is that creating an explicit figure object in AST implies that the caption would be separate from the alt text.

**Comment by afcady** [comment]
I think this bug should be left open.  The syntax shouldn't be changed, but the documentation should deprecate the usage.  Alt text and caption text should never ever be the same, this never makes sense, it means that blind readers see the hear saem sentence repeated twice, it means that blind readers hear the same sentence repeated twice, and the documentation should explain that.

**Comment by jgm** [comment]
I recognize that this isn't ideal.  But the reason
this was closed is that there's no way to
differentiate these things without an explicit Figure
element.  The issue for adding that is still open;
that's the way forward to improve this.

**Comment by mb21** [comment]
> 2. That there exists a feature that sets the alt text and the caption to be the same.

Pandoc's  currently simply generates the caption from the alt text and there is no place in pandoc's internal document representation to store the caption separately. So we cannot fix 2) without fixing 1) first.

However, we could change pandoc's HTML writer to only output a caption, and no alt text if a caption is output. That way, screen readers wouldn't read it twice.

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

> However, we could change pandoc's HTML writer to only output a caption, and no alt text if a caption is output. That way, screen readers wouldn't read it twice.

Yes, this is definitely feasible.  I don't know much
about how screen readers work; but if they always read
the caption, maybe this is a good idea.

Thoughts?

**Comment by matthewlehew** [comment]
> However, we could change pandoc's HTML writer to only output a caption, and no alt text if a caption is output. That way, screen readers wouldn't read it twice.

This would certainly be an improvement on current behavior. However, I still stress that with the current explosion of open educational resources in higher ed and the absolute necessity of accessibility, my personal belief is that it should be a top priority for Pandoc to be able to output separate `alt` text and captions without having to manually add them after conversion.
