### ISSUE TITLE
gfm+tex_math_dollars not working for mathjax

### ISSUE THREAD

**Issue by cnblogs-dudu** [jgm/pandoc#4738]
Pandoc version is 2.2.1.

Working:
```bash
pandoc -f markdown_github+tex_math_dollars -t html5 --mathjax
```
Not Working:
```bash
pandoc -f gfm+tex_math_dollars -t html5 --mathjax
```
Input:
```text
$$
test
$$

$test$

\$test2\$
```
Expected output:
```html
<p><span class="math display">\[
test
\]</span></p>
<p><span class="math inline">\(test\)</span></p>
<p>\$test2\$</p>
```

**Comment by mb21** [comment]
This is simply not implemented yet, search the MANUAL for:

> Note, however, that commonmark and gfm have limited support for extensions.

**Comment by jgm** [comment]
We can't implement this without changing the underlying C library.
When we replace the commonmark writer with a pure haskell one (see jgm/commonmark-hs), it will be possible to support most extensions.

**Comment by makslevental** [comment]
is this supported yet?
