### ISSUE TITLE
\colortext doesn't convert to html?

### ISSUE THREAD

**Issue by gandalfsaxe** [jgm/pandoc#4741]
jgm wrote in [this](https://groups.google.com/forum/#!topicsearchin/pandoc-discuss/subject$3Acolor/pandoc-discuss/SUwJEKISXcQ) thread on pandoc-discuss:

> If you use 
>     \textcolor{blue}{paragraph with color} 
> it should work fine. 

While it works fine for `tex->pdf`, I can't get `tex->html` to work.

Input `test.md`:
```markdown
---
header-includes: \usepackage{color}
---

Sentence without color. \textcolor{blue}{Sentence with color} .
```

To PDF (works): `pandoc test.md -o test.pdf`
Output:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/12127864/42024746-2d44f8a4-7ac3-11e8-8240-474a057de9c0.png">

To HTML (doesn't work): `pandoc test.md -o test.html`
Output:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/12127864/42024820-55594746-7ac3-11e8-87c1-235045456c24.png">

**Comment by mb21** [comment]
What he meant was that it should work fine when outputting to LaTeX/PDF.

From the MANUAL:

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size. And some document elements, such as complex tables, may not fit into pandoc’s simple document model. While conversions from pandoc’s Markdown to all formats aspire to be perfect, conversions from formats more expressive than pandoc’s Markdown can be expected to be lossy.

Please ask questions on pandoc-discuss.

**Comment by gandalfsaxe** [comment]
Are you sure? The thread was specifically about latex to HTML.

**Comment by mb21** [comment]
Can't speak for him, but 99% sure.

**Comment by mb21** [comment]
Actually, tex -> HTML works, just not markdown-with-raw-text -> HTML.

**Comment by gandalfsaxe** [comment]
Ok so there's no working syntax for writing color in markdown that converts to both LaTeX/PDF and html?

**Comment by mb21** [comment]
Not as far as I know. Because pandoc is about content.

I would go with e.g. `[my span]{.important}`, then style the `important` class in CSS and for LaTeX output write a [lua-filter](http://pandoc.org/lua-filters.html) that converts this to the desired RawTex.

Alternatively, [write it twice with raw attributes](http://pandoc.org/MANUAL.html#generic-raw-attribute).

**Comment by gandalfsaxe** [comment]
> Because pandoc is about content.

I don't see why text color is fundamentally different from text boldface, italics, underline, quote blocks, strikeout, verbatim, subscript, superscript etc. Sure there are less conventions about what color means than the formerly mentioned, but to me it feels like it belongs in the same category.

I guess you could argue that it belongs to text styling, along with front, header sizes etc. But color could just as well be used to convey meaning as a block quote or boldface, e.g. comments from different authors.

I think I'll just use one of the two notations depending on whether I'm targeting .tex or .html.
I just like universality whenever possible. I'll make the feature request on pandoc-discuss then :)

**Comment by gandalfsaxe** [comment]
Can it really be true that Tex->PDF doesn't work?
```latex
\documentclass[]{article}
\usepackage{xcolor}

\begin{document}

This is normal content, \textcolor{orange}{warning content} and
\textcolor{red}{important content}.

\end{document}
```

This won't give colors on command `pandoc test.tex -o test.pdf` - however with pdflatex it will, and it also works `tex->HTML`.

**Comment by gandalfsaxe** [comment]
> Doesn't pandoc actually not do, for example, bold or italic by default from md? Those styles are actually applied by convention to strong and emphatic text, no? That is, that * makes text italic is a consequence of interpreters that make "emphatic" text italic. In a related way, quoted text has no obvious visual format, at least to me, so it comes out different in different output formats.
> 
> I'm not saying that there shouldn't be an easy-ish way to do colored text, just that it isn't really the same as those other things.

If I understand you right, you're saying that there is no obvious visual format / no universal way to do quoted text, yet obviously pandoc has an internal representation of what quoted text looks like. How is that different from having a universal representation of what colored text looks like?

The only difference I see is that the is only *one* interpretation of what emphasized text or quoted text is, whereas colors can be used for different purposes and have no single interpretation. That doesn't make it less universal feature of a written document, or useful, and IMO belongs with the content source code, not external CSS styling or the likes. I could be persuaded otherwise I guess, but the usefulness of such support would be very good. For example, you could color equations as Stuart Riffle originally did, and which is [also possible in MathJax](http://adereth.github.io/blog/2013/11/29/colorful-equations/), and comment the equation with colored text. Or you could have authors provide comments to a document in each their own color during collaboration/review etc.

**Comment by gandalfsaxe** [comment]
In simpler words, I'd argue it's still part of the contents of the document because you have to specify exactly which parts of the text are colored, and which color. It's not the same as a the general style, dimensions, fonts, header sizes, margin settings, header/footer style etc. as the non-content / styling template part of a document.

**Comment by mb21** [comment]
> Can it really be true that Tex->PDF doesn't work?

yes, pandoc doesn't really optimize for that use-case because you can just use `pdflatex` directly.


About what is content and what is presentation: it's kind of an endless debate and a slippery slope. But if we were to continue in that direction, we'd have to implement not only color, but also margins, fontsize, floating etc. Some argue we've already gone too far with strikethrough and underline. Anyway, if you're interested in the philosophy behind, I can recommend for example this read about [resilient web design](https://resilientwebdesign.com/chapter2/#themeaningofmarkup).

**Comment by gandalfsaxe** [comment]
Ah ok. It's just convenient to be able to do all in pandoc. Using pdflatex also means I have to deal with cleaning up temporary/auxiliary files.

I guess my now viewpoint is:

1. If some text document feature is more or less ubiquitous across many popular document formats, it's worth implementing in `pandoc`.

2. All kinds of global options that affect the whole document obviously belongs in the template for the specific format, and can then be set as metadata variables / YAML header.

Pandoc only needs to support various formatting types for the global options to style. Text emphasize, strong, strikethrough, underline, color etc. is all fair game IMO because it's something that can only be done "on-location" where it's needed to change the meaning of the text, and cannot be dealt with by a global styling option. I can't see why this would be going too far, I think it's great.

Thanks for the recommendation, it's on my reading list now 👍
