### ISSUE TITLE
feature request: email output

### ISSUE THREAD

**Issue by green7ea** [jgm/pandoc#4745]
Pandoc is very useful when outputting HTML. However, this HTML output is meant for a web browser and not an e-mail client (it has a title, javascript for IE9, etc.). When using a text based e-mail client, it is nice to be able to send an HTML version of the e-mail so that it formats nicely on phones.

To use pandoc to do this, a few workarounds have to be used such as deleting the <title>, <style> and <if lt IE 9>. It would be nice if pandoc could support outputting to a standalone email friendly HTML.

An optional, nice to have, feature would be to skip the email header and to insert the meta data (`<#multipart type=alternative>`) lines.

Sample input:

```
From: manu@green7ea.ca
To: pandoc@pandoc.org
Subject: Test
Fcc: sent
--text follows this line--
Hello,

the email text is formatted in markdown and should be output in HTML.


Cheers,
green7ea
```

Sample output:

```
From: manu@green7ea.ca
To: pandoc@pandoc.org
Subject: Test
Fcc: sent
--text follows this line--
<#multipart type=alternative>
Hello,

the email text is formatted in markdown and should be output in HTML.


Cheers,
green7ea
<#part type=text/html>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
</head>
<body>
<p>Hello,</p>
<p>the email text is formatted in markdown and should be output in HTML.</p>
<p>Cheers, green7ea</p>
</body>
</html>
<#/multipart>
```

**Comment by mb21** [comment]
> a few workarounds have to be used such as deleting the <title>, <style> and <if lt IE 9>

just leave away the `-s` flag.

I think you can do what you want with a [custom template](http://pandoc.org/MANUAL.html#templates).

**Comment by cognivore** [comment]
Hey, @green7ea! Did you end up making a relevant template or found one?

**Comment by green7ea** [comment]
I ended up making one, using it for some time and losing it in a computer migration :-(
