### ISSUE TITLE
Enumerated lists with actual numbers from exporting from Org to RST

### ISSUE THREAD

**Issue by kaushalmodi** [jgm/pandoc#4749]
Can the enumerated lists in exported RST configured to use actual numbers rather than **#.**?

## Pandoc version

pandoc 2.2.1

## Command

```
pandoc input.org -o output.rst
```

## Org Snippet

```org
1. Item one
2. Item two
3. Item three
```

## Actual RST output

```rst
#. Item one
#. Item two
#. Item three
```

## Expected/Requested RST output

```rst
1. Item one
2. Item two
3. Item three
```

**Comment by jgm** [comment]
Yes, this is possible with a lua filter.  The org reader parses lists as having the `DefaultStyle`; if you change this to `Decimal`, it should cause actual numbers to be produced.
```
% cat lists.lua 
function OrderedList(el)
  if el.style == 'DefaultStyle' then
    el.style = 'Decimal'
    return el
  end
end
```
```
% pandoc --lua-filter lists.lua -f org -t rst
1. Item one
2. Item two
3. Item three
^D
1. Item one
2. Item two
3. Item three
```

**Comment by kaushalmodi** [comment]
@jgm Thank you. That works perfectly! I am not yet a seasoned pandoc user. How can I know which "API" of pandoc is configurable? For example, can I get list of configuration knobs for Org, RST, etc.?

**Comment by jgm** [comment]
The manual (User's Guide) is your first resource.
For lua filters, see the documentation on lua filters
on the website.  But it would probably have been hard
to figure out this particular trick without looking
at the source :).
