### ISSUE TITLE
RST output: Generate simple-style tables if possible

### ISSUE THREAD

**Issue by kaushalmodi** [jgm/pandoc#4750]
See [the original request on Google Groups][1] for details.

Here's  my original message copy/pasted from that thread:

---

I am trying to use Org mode to document few Nim (https://nim-lang.org) packages. Nim has an internal HTML documentation generator that parses ReST markup docs and doc-strings.

So I am doing:

```
pandoc foo.org -o foo.rst
```

to export Org docs to ReST.

This works mostly fine except that the Nim document generator doesn't parse the grid-style ReST tables generated by Pandoc.

Example:

This style of ReST tables is parsed fine by the Nim doc generator:

```
  =======  =========
  Option   Meaning
  -------  ---------
  ``+``    All numbers (including positive ones) are preceded by a sign.
  ``-``    Only negative numbers are preceded by a sign.
  *SPACE*  Negative numbers are preceded by a sign, positive numbers are preceded by a space.
  =======  =========
```

But this style (grid-style) is not:

```
    +-----------------------------------+-----------------------------------+
    | Option                            | Meaning                           |
    +===================================+===================================+
    | ``+``                             | All numbers (including positive   |
    |                                   | ones) are preceded by a sign.     |
    +-----------------------------------+-----------------------------------+
    | ``-``                             | Only negative numbers are         |
    |                                   | preceded by a sign.               |
    +-----------------------------------+-----------------------------------+
    | *SPACE*                           | Negative numbers are preceded by  |
    |                                   | a sign, positive numbers are      |
    |                                   | preceded by a space.              |
    +-----------------------------------+-----------------------------------+
```

Here is the Org source:

```
  | Option    | Meaning                                                                              |
  |-----------+--------------------------------------------------------------------------------------|
  | =+=       | All numbers (including positive ones) are preceded by a sign.                        |
  | =-=       | Only negative numbers are preceded by a sign.                                        |
  | /SPACE/   | Negative numbers are preceded by a sign, positive numbers are preceded by a space.   |
```

Is there a way to choose the former style of ReST table when exporting from Org?

If not, would you please add this feature?

Thanks!

---

To which, @jgm replied:

> In principle, we could change the RST writer so it produces the simple tables when the contents of the table are simple enough (no block structure, no overly long lines). 

[1]: https://groups.google.com/forum/m/#!msg/pandoc-discuss/GDzFYzr_Od4/ojMGuMy0CAAJ

**Comment by kaushalmodi** [comment]
Ref: https://github.com/nim-lang/Nim/issues/6429

**Comment by kaushalmodi** [comment]
@jgm Thank you! Now I'm desperately waiting for a static binary including this commit. Many thanks!

**Comment by rpuntaie** [comment]
What would be the command line to have grid_table output for RST?
