### ISSUE TITLE
ODT to RTF output: only first line of output visible (macOS)

### ISSUE THREAD

**Issue by emendelson** [jgm/pandoc#4751]
Apologies from a first-time poster. I've been trying to use pandoc to create RTF from ODT files under macOS. When I look at the output RTF in a text-only editor, all of the text from the ODT seems to be present, but when I open the RTF file in any RTF-reading application, only the first line gets displayed. I've experimented with adding headers from other RTF files with no success.

Using the same input ODT file, pandoc produces correct DOCX output. The only problem is that only the first line of the RTF appears in TextEdit or anything else that uses the macOS rich text viewer.

Sample files attached; version 2.2.1

Command line: pandoc -t rtf -o testing.rtf testing.odt

[BadRTFfromODT.zip](https://github.com/jgm/pandoc/files/2151784/BadRTFfromODT.zip)

Again, apologies if I've left out crucial details.

**Comment by mb21** [comment]
You're missing the `-s` option.
