### ISSUE TITLE
PDFs can be embedded in pdfs as images, but not webpages

### ISSUE THREAD

**Issue by gappleto97** [jgm/pandoc#4753]
pandoc --version
pandoc 2.0.1.1
Compiled with pandoc-types 1.17.2, texmath 0.10, skylighting 0.4.3.2

The following works when going from rst -> pdf

```restructuredText
.. image:: ./path/to/image.pdf
```

It embeds the pdf after converting it to an image. It does *not* do this if you convert to html. Because of a problem with the way I have to include documents, that means that I have to first convert them to a very lossy image before they can be embedded, and I can't say "oh, if compiling to latex, do this, otherwise that".

It would be nice if we could get consistent behaviour between the two.

**Comment by mb21** [comment]
Actually, it should convert to `<p><embed src="./path/to/image.pdf" /></p>`

See also http://pandoc.org/MANUAL.html#generic-raw-attribute and http://pandoc.org/filters.html

Finally, please ask questions on pandoc-discuss.
