### ISSUE TITLE
docbook writer latex math enhancement

### ISSUE THREAD

**Issue by dooboolacky** [jgm/pandoc#4754]
Hi, I imagine this is an easy customization if you you know Lua, but...

Converting from latex to docbook it would be really useful to me to have some option analogous to the --mathml output, whereby  inline math $e=mc^2$ gets written out pretty much the same as it went in:

`<inlineequation><alt role='tex'>\( e=mc^2 \)</alt></inlineequation>`
and  displaymath is written out like:

`<equation><alt role='tex'>\[ 
    \int_{M}\Div(f)dV = \int_{\partial M} f\cdot A
  \]</alt></equation>`

Thanks.

**Comment by mb21** [comment]
You can output mathml: `pandoc -t docbook --mathml`

If you want someone to help write a lua-filter, please ask on pandoc-discuss. This tracker is for issues.

**Comment by dooboolacky** [comment]
On Thursday, 5 July 2018 12:53:21 AM AWST Mauro Bieg wrote:
> You can output mathml: `pandoc -t docbook --mathml`
> 
> If you want someone to help write a lua-filter, please ask on
> pandoc-discuss. This tracker is for issues.

My apologies. I thought it was bugs and enhancements.

I do not want mathml.
I want latex math embedded in DocBook.

mathml is uneditable.
The current pandoc docbook writer's rendering of inline math is uneditable.
Latex math embedded in docbook would be editable.

**Comment by dooboolacky** [comment]
A filter, just for posterity...

```
#!/usr/bin/env python
from pandocfilters import toJSONFilter, RawInline, RawBlock
"""
   https://github.com/jgm/pandocfilters
Pandoc filter to pass latex math straight through to DocBook "alt" elements.
This approach to math in DocBook was pioneered by Allin Cottrell 
   http://ricardo.ecn.wfu.edu/~cottrell/dbtexmath/about.pdf
using dsssl processing, but was greatly improved by Jirka Kosek using XSLT. 
The XSLT approach allowed graphical representations to be automatically 
generated and injected into transformed HTML documents. More recently 
display of raw latex in transformed HTML has become possible with MathJax.
"""

def docbook_latex_math(key, value, format, meta):
    if format != "docbook": return
    if key == "Math":
        [fmt, code] = value
        if isinstance(fmt, dict) and fmt['t'] == "InlineMath":
            s = "<inlineequation><alt role='tex'>\(" + code.strip('`') + \
                 "\)</alt></inlineequation>"
            return RawInline(format, s)
        elif isinstance(fmt, dict) and fmt['t'] == "DisplayMath":
            s = "\n<equation><alt role='tex'>\[\n" + code.strip('`') + \
                 "\n\]</alt></equation>\n"
            return RawInline(format, s)
            #return RawBlock(format, s)

if __name__ == "__main__":
    toJSONFilter(docbook_latex_math)
```
