### ISSUE TITLE
Code correctly compiling in `pdflatex` but choking `pandoc`.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jgm/pandoc#4761]
[Simple.zip](https://github.com/jgm/pandoc/files/2176653/Simple.zip)

The enclosed `Simple.tex` file (in `Simple.zip`, generated by `knitr` from `Simple.Rnw` file) correctly compiles with `pdflatex`. But trying to convert it to HTML via `pandoc -t HTML Simple.tex` gives me : 
```
Error at "source" (line 87, column 24):
unexpected %
\includegraphics[width=\maxwidth]{figure/FigureR-1} \caption[Figure générée par \textsf{R}]{Figure générée par \textsf{R}}\label{fig:FigureR}
                       ^
```
The definition of `\maxwidth` (lines 3--11 of `Simple.tex`) probably comes from `knitr` :
```
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother
```

There is a suspicious whitespace at the start of the definition (before the `%`), but I can't see how this would cause a problem. Anyway, `pdflatex` has no problem with this. I *think* that this is a `pandoc` parsing error.

**Comment by jgm** [comment]
In fact, this macro definition is part of the default pandoc latex template!

But pandoc's latex parser can't presently handle this plain tex macro definition (for one thing it doesn't support `\ifdim`).  To improve this, it might suffice to add code so that `\ifdim` constructions are passed through as raw latex.

**Comment by EmmanuelCharpentier** [comment]
Thanks for this answer !

>In fact, this macro definition is part of the default pandoc latex template! But pandoc's latex parser can't presently handle this plain tex macro definition [...]

Isn't this an almost perfect example of a bug ?

I might try my hand at this, but I'm afraid that this is way above my levet of \TeXpertise... BTW : isn't this doable *via* **\Latex** macroes, rather than requiring plain \TeX ?

**Comment by jgm** [comment]
I've added a commit which allows this to be parsed, though the `\maxwidth` will not be passed through to the destination latex.
