### ISSUE TITLE
Bug: makeindex index cannot locate at chapter name's tail

### ISSUE THREAD

**Issue by bubifengyun** [jgm/pandoc#4762]
Thank you,

## pandoc version

```
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
```

## exact command

```
$ pandoc test.md --to latex --from markdown --output result.tex --template template.tex --pdf-engine xelatex
```

## exact input
here  two files, one `test.md`, one `template.tex`

This is  test.md,
<pre>
# Test pandoc\index{pandoc} chapter {#chap:pandocchapter} 
# Test pandoc\index{pandoc} {#chap:pandoc} 
</pre>

here is template.tex

<pre>
\documentclass{ctexbook}
\RequirePackage{etoolbox}
\RequirePackage[centering,a4paper,body={16cm,22cm}]{geometry} %设置版面
\RequirePackage{fancyhdr}
\RequirePackage{pageslts}
\RequirePackage[titles]{tocloft}
\RequirePackage{mathtools,amsthm,amsfonts,amssymb,bm}
\RequirePackage[defaultsups]{newtxtext}
\RequirePackage{newtxmath}
\RequirePackage[opentype]{sourcecodepro}
\RequirePackage{upgreek}
\RequirePackage{wasysym}
\RequirePackage{anyfontsize}
\RequirePackage{metalogo,doc}
\RequirePackage{array}
\RequirePackage{threeparttable}
\RequirePackage{dcolumn}
\RequirePackage{multirow}
\RequirePackage{booktabs}
\RequirePackage{graphicx}
\RequirePackage{caption}
\RequirePackage[list=off]{bicaption}
\RequirePackage{subcaption}
\RequirePackage[backend=biber,style=gb7714-2015]{biblatex}
\RequirePackage{xcolor}
\RequirePackage{textcomp}
\RequirePackage[xetex, bookmarksnumbered, colorlinks, urlcolor=black, linkcolor=black, citecolor=black, plainpages=false, pdfstartview=FitH]{hyperref}
\RequirePackage{longtable}
\RequirePackage[perpage, bottom]{footmisc}
\RequirePackage[inline]{enumitem}
\RequirePackage{pdfpages}
\RequirePackage{calc}
\RequirePackage{algorithm, algorithmicx, algpseudocode}
\RequirePackage{siunitx}
\RequirePackage{tikz}
\RequirePackage{imakeidx}
\makeindex
\begin{document}
$body$
\printindex
\end{document}
</pre>

## the output received, it is result.tex
<pre>
\documentclass{ctexbook}

\RequirePackage{etoolbox}
\RequirePackage[centering,a4paper,body={16cm,22cm}]{geometry} %设置版面
\RequirePackage{fancyhdr}
\RequirePackage{pageslts}
\RequirePackage[titles]{tocloft}
\RequirePackage{mathtools,amsthm,amsfonts,amssymb,bm}
\RequirePackage[defaultsups]{newtxtext}
\RequirePackage{newtxmath}
\RequirePackage[opentype]{sourcecodepro}
\RequirePackage{upgreek}
\RequirePackage{wasysym}
\RequirePackage{anyfontsize}
\RequirePackage{metalogo,doc}
\RequirePackage{array}
\RequirePackage{threeparttable}
\RequirePackage{dcolumn}
\RequirePackage{multirow}
\RequirePackage{booktabs}
\RequirePackage{graphicx}
\RequirePackage{caption}
\RequirePackage[list=off]{bicaption}
\RequirePackage{subcaption}
\RequirePackage[backend=biber,style=gb7714-2015]{biblatex}
\RequirePackage{xcolor}
\RequirePackage{textcomp}
\RequirePackage[xetex, bookmarksnumbered, colorlinks, urlcolor=black, linkcolor=black, citecolor=black, plainpages=false, pdfstartview=FitH]{hyperref}
\RequirePackage{longtable}
\RequirePackage[perpage, bottom]{footmisc}
\RequirePackage[inline]{enumitem}
\RequirePackage{pdfpages}
\RequirePackage{calc}
\RequirePackage{algorithm, algorithmicx, algpseudocode}
\RequirePackage{siunitx}
\RequirePackage{tikz}
\RequirePackage{imakeidx}
\makeindex

\begin{document}

\hypertarget{chap:pandocchapter}{%
\section{\texorpdfstring{Test pandoc\index{pandoc}
chapter}{Test pandoc chapter}}\label{chap:pandocchapter}}

\hypertarget{test-pandoc}{%
\section{\texorpdfstring{Test
pandoc\index{pandoc} {#chap:pandoc}}{Test pandoc}}\label{test-pandoc}}
\printindex

\end{document}
</pre>

## the output I expected instead

<pre>
\documentclass{ctexbook}

\RequirePackage{etoolbox}
\RequirePackage[centering,a4paper,body={16cm,22cm}]{geometry} %设置版面
\RequirePackage{fancyhdr}
\RequirePackage{pageslts}
\RequirePackage[titles]{tocloft}
\RequirePackage{mathtools,amsthm,amsfonts,amssymb,bm}
\RequirePackage[defaultsups]{newtxtext}
\RequirePackage{newtxmath}
\RequirePackage[opentype]{sourcecodepro}
\RequirePackage{upgreek}
\RequirePackage{wasysym}
\RequirePackage{anyfontsize}
\RequirePackage{metalogo,doc}
\RequirePackage{array}
\RequirePackage{threeparttable}
\RequirePackage{dcolumn}
\RequirePackage{multirow}
\RequirePackage{booktabs}
\RequirePackage{graphicx}
\RequirePackage{caption}
\RequirePackage[list=off]{bicaption}
\RequirePackage{subcaption}
\RequirePackage[backend=biber,style=gb7714-2015]{biblatex}
\RequirePackage{xcolor}
\RequirePackage{textcomp}
\RequirePackage[xetex, bookmarksnumbered, colorlinks, urlcolor=black, linkcolor=black, citecolor=black, plainpages=false, pdfstartview=FitH]{hyperref}
\RequirePackage{longtable}
\RequirePackage[perpage, bottom]{footmisc}
\RequirePackage[inline]{enumitem}
\RequirePackage{pdfpages}
\RequirePackage{calc}
\RequirePackage{algorithm, algorithmicx, algpseudocode}
\RequirePackage{siunitx}
\RequirePackage{tikz}
\RequirePackage{imakeidx}
\makeindex

\begin{document}

\hypertarget{chap:pandocchapter}{%
\section{\texorpdfstring{Test pandoc\index{pandoc}
chapter}{Test pandoc chapter}}\label{chap:pandocchapter}}

\hypertarget{test-pandoc}{%
\section{\texorpdfstring{Test
pandoc\index{pandoc}}{Test pandoc}}\label{chap:pandoc}}
\printindex

\end{document}
</pre>

If \index located at the end of chapter name, it cannot produce as expected. Thank you.

**Comment by mb21** [comment]
You are saying that in

    echo '# Test pandoc\index{pandoc} {id="chap:pandoc"}' | pandoc -t latex

the markdown attribute is not being picked up?

Try the following, which uses a [raw attribute](http://pandoc.org/MANUAL.html#generic-raw-attribute):

    echo '# `Test pandoc\index{pandoc}`{=latex} {id="chap:pandoc"}' | pandoc -t latex

Not saying the latex in markdown parser could not be improved, but I this is a reasonable workaround.

**Comment by bubifengyun** [comment]
it seems that it cannot show in contents. The output is 

```latex
\hypertarget{chap:pandoc}{%
\section{\texorpdfstring{Test pandoc\index{pandoc}}{}}\label{chap:pandoc}}
```

I think it should be

```latex
\hypertarget{chap:pandoc}{%
\section{\texorpdfstring{Test pandoc\index{pandoc}}{Test pandoc}}\label{chap:pandoc}}
```

**Comment by bubifengyun** [comment]
I decide use another bad method, put index in the front of text, such as

```
Test \index{pandoc}pandoc {id="chap:pandoc"}
```

now it can works well.

**Comment by jgm** [comment]
This is the right approach.  In trying to determine
what is part of raw LaTeX, pandoc assumes that
`{id="chap:pandoc"}` is a further argument to
the `\index` command.  You could disrupt this
by inserting, say, a blank HTML comment between
them, or (better) use the raw attribute as suggested,
to make it explicit where the raw latex ends.

**Comment by bubifengyun** [comment]
Thank you. I think changeing the `\index` location is easy. I would adopt it.  Add others' thing would make paper not beautiful.
