### ISSUE TITLE
LaTeX Reader \def\Sec#1[#2]#3{ 

### ISSUE THREAD

**Issue by h4ck3rm1k3** [jgm/pandoc#4768]
using the versoin 1.19.2.4~dfsg-1 in debian
on the file 
https://github.com/cplusplus/draft/blob/master/source/macros.tex#L85
in this part of the code
```
% The basic sectioning command.  Example:
%    \Sec1[intro.scope]{Scope}
% defines a first-level section whose name is "Scope" and whose short
% tag is intro.scope.  The square brackets are mandatory.
\def\Sec#1[#2]#3{%
\ifcase#1\let\s=\chapter\let\l=\clauselabel
      \or\let\s=\section\let\l=\label
      \or\let\s=\subsection\let\l=\label
      \or\let\s=\subsubsection\let\l=\label
      \or\let\s=\paragraph\let\l=\label
      \or\let\s=\subparagraph\let\l=\label
      \fi%
\s[#3]{#3\hfill[#2]}\l{#2}\addxref{#2}}
```

Gives the output 
```
macros.tex
pandoc: 
Error at "source" (line 2104, column 26):
unexpected "l"
expecting "bgroup" or "begingroup"
\ifcase#1\let\s=\chapter\let\l=\clauselabel
                         ^
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Error.hs:66:13 in pandoc-1.19.2.4-5gSN3yQBinE8IAhFhCAEYe:Text.Pandoc.E\
rror
```

**Comment by mb21** [comment]
Can you try with the latest pandoc version?
Also, what exact command are you using?

**Comment by mb21** [comment]
Since that repo is huge, it would certainly help if you could post a link to a zip with only the `/source` folder. Even better, find specific minimally reproducible examples that fail with the newest pandoc version and post them here (e.g. the `std.tex` file on its own works, but it might fail on following the includes, so the minimal repro would be in there somewhere).

**Comment by h4ck3rm1k3** [comment]
sure will do that

**Comment by h4ck3rm1k3** [comment]
Ok here is the test case for this https://github.com/h4ck3rm1k3/pandoc/blob/master/test/tex/def_pattern.tex

**Comment by jgm** [comment]
Command test:
```
% pandoc -f latex -t plain
\def\foo#1!#2!#3{#1 or #2 and #3}
\foo aa!bbb bbb!{ccc}
^D
aa or bbb bbb and ccc
```
