### ISSUE TITLE
1.19.2.4~dfsg-1

### ISSUE THREAD

**Issue by h4ck3rm1k3** [jgm/pandoc#4769]
Relating to Macro Crash #4768

using 2.2.1-2+b1 on debian unstable. 

```
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.6
```

Running on this source https://github.com/cplusplus/draft/blob/master/source/std.tex#L6

Running `pandoc std.tex -t json`

Gives
```
Error at "source" (line 6, column 15):
unexpected [
\documentclass[a4paper,10pt,oneside,openany,final]{memoir}
              ^
```
In fact it bombs on most of those files in there.

**Comment by mb21** [comment]
Closing in favour of #4768

**Comment by h4ck3rm1k3** [comment]
I think this is a different one, because the other ticket  #4768 shows one error in the older version, this new version fails more often.
