### ISSUE TITLE
Strange error when included file has error

### ISSUE THREAD

**Issue by h4ck3rm1k3** [jgm/pandoc#4771]
If you include a file with errors you get a misleading error message like this 
```
Error at "source" (line 1, column 15):
unexpected [
\documentclass[a4paper,10pt,oneside,openany,final]{memoir}
```
see source https://github.com/h4ck3rm1k3/pandoc/blob/master/test/tex/document_class.tex

Now the included macros.tex has this error message.
https://github.com/h4ck3rm1k3/pandoc/blob/master/test/tex/macros.tex.err
source file
https://github.com/h4ck3rm1k3/pandoc/blob/master/test/tex/macros.tex

**Comment by jgm** [comment]
That's odd; normally it should report the location in the included file.
I'll have to look into this one.
