### ISSUE TITLE
Support more sunitx macros

### ISSUE THREAD

**Issue by gandalfsaxe** [jgm/pandoc#4773]
On jgm's suggestion, I'm creating this issue after discussion on [pandoc-discuss](https://groups.google.com/d/msg/pandoc-discuss/s8jRWo5iGUQ/LxGCYCf2AgAJ) (see thread for minimum example).

The problem is that some macros, such as `\km` are not supported. I have noticed that older versions of `siunitx` didn't have a lot of the macros it has today, and I think `\km` (among others) was added around 2015.

Anyway I'd be great to have all the `siunitx` macros supported. If somebody could point me to the right place / file, I'd be happy to do it myself.

**Comment by jgm** [comment]
Note that as a workaround, you can simply add something like this to your document:
```
\renewcommand{\km}{km}
```
Pandoc should be able to parse that and resolve the macro.

**Comment by jgm** [comment]
Closed by 1579e578332536e9b36534dfeb3c0f36f9162fd5
