### ISSUE TITLE
windows MSI installer for 2.2.2 says 2.2.1

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#4775]
I have downloaded [`pandoc-2.2.2-windows-x86_64.msi`](https://github.com/jgm/pandoc/releases/download/2.2.2/pandoc-2.2.2-windows-x86_64.msi), SHA-256 `D11F3E08156C0544417AF6A44CB44AF8E5C17C0475663BEBC046D395DE4916DD`, and double-clicked it to run it. It says 2.2.1 in the installer:

![pandoc-installer-2 2 2](https://user-images.githubusercontent.com/1098563/42761412-bbb17812-890d-11e8-8ba9-18a1123623ce.png)

**Comment by snow212-cn** [comment]
Same to this commenter. What the hell is jgm doing. We're all played by him

**Comment by jgm** [comment]
I'm not sure what went wrong here.  (The creation of the packages is automated, and I don't have a Windows machine to test on.)

I've regenerated Windows packages and uploaded them with the suffix `-1`, e.g. `pandoc-2.2.2-1-windows-i386.msi`.  Can you please test the new packages and let me know that they contain the pandoc 2.2.2 executable?

**Comment by jgm** [comment]
My guess is that an intermediate file from an earlier package build wasn't properly deleted.

**Comment by wilx** [comment]
The `-1` looks correct. Thank you.
