### ISSUE TITLE
When converting markdown to docx, alternative text shows as figure captions

### ISSUE THREAD

**Issue by DrewParallel** [jgm/pandoc#4776]
I'm using pandoc version 2.2

I have the following line in a markdown file:
![Image Description](./images/media/image.png)

I convert the markdown file to docx using:
pandoc -f markdown -t docx markdown_file.md -o docx_file.docx

Unfortunately, the alternative text "Image Description" shows up as a title to the image. I can fix this by removing the alternative text, but then it won't be available as alternative text in the online version.

**Comment by mb21** [comment]
This is a current limitation of how pandoc handles figures, see https://github.com/jgm/pandoc/issues/3177

**Comment by jgm** [comment]
If you just want the image (not a figure with title),
then (as the MANUAL suggests), you just have to make
sure it's not the only thing in the paragraph. For
example, you could add a nonbreaking space after the
image.  (See manual under implicit_figures.)

Other option is to disable the implicit_figures
extension altogether:  pandoc -f markdown-implicit_figures.
