### ISSUE TITLE
Can no longer find custom templates in data-dir/templates under 2.2.2

### ISSUE THREAD

**Issue by rbubley** [jgm/pandoc#4777]
Under version 2.2.1 and prior pandoc found latex templates in the templates directory under the data directory, but this is no longer working for me under 2.2.2.

`pandoc --from=markdown+raw_attribute+smart --pdf-engine=xelatex --template=template-report.latex  test.md  -o test.tex`

gives

```
File template-report.latex not found in resource path
```

Working version:
```
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
```

Non-working version:
```
pandoc 2.2.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
```

In each case this is the version installed using the macOS .pkg installer on the github release page.

**Comment by mb21** [comment]
You shouldn't need `--template` then. From the MANUAL:

> You can also override the system default templates for a given output format FORMAT by putting a file `templates/default.*FORMAT*` in the user data directory (see `--data-dir`

**Comment by giovino** [comment]
```
OS: Mac OS 10.13.5
Pandoc: pandoc 2.2.2
  * Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
  * Installed using Brew
```

I am also seeing a regression when using `--template`. Prior to 2.2.2 the following command worked:

```pandoc --template=GitHub.html5 -s test.md -o test.html --metadata pagetitle="asdf"```

Now I get the error message:

`File GitHub.html5 not found in resource path`

 * Location of `GitHub.html5`:
  ```/Users/giovino/.pandoc/templates/GitHub.html5```

If I specify the full path of the template, the original command works as expected:

``` pandoc --template=/Users/giovino/.pandoc/templates/GitHub.html5 -s test.md -o test.html --metadata pagetitle="asdf"```

**Comment by rbubley** [comment]
Amending title following comments from @mb21 and @giovino.

**Comment by mb21** [comment]
Ah, I understand now. This seems indeed like a bug, since it's documented in the MANUAL:

>  If the template is not found, pandoc will search for it in the templates subdirectory of the user data directory (see `--data-dir`).

**Comment by jgm** [comment]
I'll do a bugfix release soon, because I hate regressions!

**Comment by hoclun-rigsep** [comment]
On Mac OS 10.14.5 installed with homebrew:
```
$ pandoc --version
pandoc 2.8.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: /Users/jim/.local/share/pandoc or /Users/jim/.pandoc
```
However, this only works for me when files are in `.local/share/pandoc`, not ~/.pandoc. This is apparently true even if there is no ~/.local/share/pandoc directory.
