### ISSUE TITLE
inconsistent handling of definition lists in HTML

### ISSUE THREAD

**Issue by lemzwerg** [jgm/pandoc#478]
(This is pandoc version 1.9.1.2)

This pandoc markup

    foo
    :   foo1

    bar
    :   bar1

converted to HTML looks like this:

    foo

        foo1

    bar

        bar1

In other words, 'foo1' and 'bar1' are wrapped within paragraph tags.  I think this is a bug, since this code:

    foo
    :   foo1

    xxx

    bar
    :   bar1

gets correctly rendered without paragraph tags:

    foo
        foo1 

    xxx

    bar
        bar1

**Comment by jgm** [comment]
Closing as obsolete. Pandoc's treatment of definition lists has been brought into line with PHP Markdown Extra's.
