### ISSUE TITLE
`pandoc_title_block` extension does not work while using input format `gfm`

### ISSUE THREAD

**Issue by griffin-stewie** [jgm/pandoc#4782]
## How to reproduce

```sh
pandoc sample.md -f markdown_github+pandoc_title_block -t json
```

Non-empty `meta` object is contained in json when I ran command above.

```sh
pandoc sample.md -f gfm+pandoc_title_block -t json
```
However `meta` object is empty when I ran command above.

My understanding is that `gfm` and `markdown_github` are same format.

`pandoc_title_block` extension is not  the only problem, `yaml_metadata_block` extension does not work as well.

## Environment

macOS: 10.13.6

```
$ pandoc -v
pandoc 2.2.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
```

pandoc is installed by homebrew.

## Sample markdown

```md
%  'This is the title'
% Jack White; Mike Brown
% 2018/06/23

# Header Level1

## Header Level2

- AAAAA
- BBBBB
```

**Comment by mb21** [comment]
> My understanding is that gfm and markdown_github are same format.

Nope. From the MANUAL:

> `markdown_github`, which provides deprecated and less accurate support for Github-Flavored Markdown; please use `gfm` instead, unless you need to use extensions other than `smart`.

Since you need extensions, please use `markdown_github` until the new `gfm` reader is implemented...
