### ISSUE TITLE
org-mode export gives literal tilde instead of code block after a bulleted list

### ISSUE THREAD

**Issue by treese** [jgm/pandoc#4784]
Version: pandoc 2.2.2.1 installed with homebrew on Mac OX 10.13.5 (High Sierra)

If a term is marked with tildes for export as inline code, such as `~code~`, immediately following a bulleted list, the tildes are exported literally instead of with a different display for "code". The following examples use the command line of the form `pandoc -o bug.html bug.org`

For example, the output from the attached bug.org file is attached as bug.html. For comparison, the file works.org, with the addition of one word of regular text after the bulleted list, properly results in "code" being marked with `<code>` tags. This problem also occurs with docx files, but it's easy to see in the HTML. (Note: the files are attached as .txt since GitHub won't attach .org or .html directly).
[bug.html.txt](https://github.com/jgm/pandoc/files/2214622/bug.html.txt)
[bug.org.txt](https://github.com/jgm/pandoc/files/2214623/bug.org.txt)
[works-ok.html.txt](https://github.com/jgm/pandoc/files/2214624/works-ok.html.txt)
[works-ok.org.txt](https://github.com/jgm/pandoc/files/2214625/works-ok.org.txt)

**Comment by tarleb** [comment]
Thanks for the report.

**Comment by treese** [comment]
I was away for a bit so this was delayed: thanks for the quick turnaround!
