### ISSUE TITLE
Slide specific theme affects the following pages and notes

### ISSUE THREAD

**Issue by pacien** [jgm/pandoc#4786]
The Metropolis beamer theme supports "standout" frames which are inverted and centered.

Rendering `test.latex` with `pdflatex` directly gives a correctly generated reference document (`out/test.pdf`).

Compiling the equivalent Pandoc markdown file using `pandoc -t beamer test.md -o out/test.pandoc.pdf` gives a buggy output: frames and notes after the standout slide are also affected with the theme which should only apply to the specific slide.

Using `--template=template.latex` with `template.latex` from [this commit](https://github.com/jgm/pandoc/commit/748aa920f6cdbe5c7f828a706a048eda8340abc7) doesn't affect this issue.

Side-by-side comparison with the reference on the left, the incorrect output on the right:

![15322628855280](https://user-images.githubusercontent.com/1449319/43045633-72c3e000-8dbc-11e8-8d9c-cf57e318a59e.png)

## Steps to reproduce

See the minimal working example at https://github.com/pacien/pandoc-beamer-metropolis-standout-bug.

## Environment

```
 % pdflatex --version
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.28; using libpng 1.6.28
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.48.0

 % pandoc --version
pandoc 2.2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Default user data directory: /home/kea/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment]
Do you have a suggested fix for the template? Or alternatively, what's the expected output of:

    pandoc -t beamer https://raw.githubusercontent.com/pacien/pandoc-beamer-metropolis-standout-bug/master/test.md

**Comment by minijackson** [comment]
I have the same issue, and from what I've seen, even though the notes on the side are affected, even without the notes, the "standout" property seems to extend until the next title slide (level 1 title with `--slide-level=2`, unlike @pacien's example)

**Comment by pacien** [comment]
@mb21 [Here](https://github.com/pacien/pandoc-beamer-metropolis-standout-bug/raw/master/out/test.pdf) is the expected output, and [here](https://github.com/pacien/pandoc-beamer-metropolis-standout-bug/raw/master/out/test.pandoc.pdf) is the actual ouput.

**Comment by mb21** [comment]
@pacien I mean in terms of the generated LaTeX (see the mentioned command).

**Comment by pacien** [comment]
My bad, here is the LaTeX output:

```latex
\begin{frame}{A frame}
\protect\hypertarget{a-frame}{}

\note{Some notes}

\end{frame}

\begin{frame}[standout]{}
\protect\hypertarget{section}{}

A standout frame.

\note{Some notes}

\end{frame}

\begin{frame}{Another frame}
\protect\hypertarget{another-frame}{}

\note{Some notes}

\end{frame}
```

I'm not sure whether `\note{…}` should be part of the `\begin{frame}` blocks.
Nevertheless, putting those outside of the frames doesn't solve the problem.

**Comment by mb21** [comment]
Ah, so `test.latex` is the expected output:

    \begin{frame}{A frame}
    \end{frame}
    \note{Some notes}

    \begin{frame}[standout]
      A standout frame.
    \end{frame}
    \note{Some notes}

    \begin{frame}{Another frame}
    \end{frame}
    \note{Some notes}

But there you have content _between_ slides (aka frames). AFAIK this is not possible with pandoc, because... why would you? Not sure why this layout works though as I'm no LaTeX/Metropolis expert.

**Comment by pacien** [comment]
Section 19.1 of the Beamer User guide states that `\note{}` should indeed be preferably used inside of the slides. So there's nothing to change here regarding the nesting.

Running `pandoc -t beamer --template=template.latex test.md > intermediate.latex` and editing the intermediate file manually to remove the `ignorenonframetext` class option solves parts of the issue: the slide theme doesn't affect the following frames anymore. It still applies to its embedded note block though, but that's tolerable as it doesn't break the whole presentation anymore.

Is there a pandoc option that can be used to prevent that class option to be added automatically?

**Comment by mb21** [comment]
`ignorenonframetext ` is only in the template, right? So use a custom [template](http://pandoc.org/MANUAL.html#templates) and remove it there.

**Comment by pacien** [comment]
It's in the [default template at line 8](https://github.com/jgm/pandoc/blob/748aa920f6cdbe5c7f828a706a048eda8340abc7/data/templates/default.latex#L8).
Is there any reason to set it by default for the Beamer class?

**Comment by jgm** [comment]
I don't know if this is relevant, but just last night I commited a change to the default.latex template that is intended to make metropolis work better.  If you haven't already, try using that template.

**Comment by jgm** [comment]
Could this be relevant: https://tex.stackexchange.com/questions/181032/ignorenonframetext-option-breaks-frame-background-color-option

**Comment by jgm** [comment]
For motivation for `ignorenonframetext`:
```
 % pandoc -t beamer --slide-level=2
# Section

Not in slide

## Slide

in slide
^D
\hypertarget{section}{%
\section{Section}\label{section}}

Not in slide

\begin{frame}{Slide}
\protect\hypertarget{slide}{}

in slide

\end{frame}
```
This is how you proceed if you want to produce an article with embedded slides and textual material between the slides.  Here we'll have problems without `ignorenonframetext`.

**Comment by pacien** [comment]
Thanks for your reply. I have tried with the latest template, with no luck.

I think that the fixes for `ignorenonframetext` should be implemented directly in the theme.
I have submitted issue on Metropolis's repository [here](https://github.com/matze/mtheme/issues/334) and [here](https://github.com/matze/mtheme/issues/335).

**Comment by basbebe** [comment]
I still have the same problem.
Was there a regression in pandoc?

**Comment by pacien** [comment]
Quoting basbebe (2021-11-10 09:33:42)
> I still have the same problem.
> Was there a regression in pandoc?

I could not reproduce the issue with ***@***.*** and pandoc 2.13.
Note that, at the time of writing, you still have to use the metropolis
theme from the master branch of its repository because the current
latest release predates the fix.

***@***.***: https://github.com/matze/mtheme/commit/2fa6084b9d34fec9d2d5470eb9a17d0bf712b6c8

**Comment by basbebe** [comment]
I'm sorry, this is apparently what happened:

I did `make sty` in master and copied the resulting `.sty` files to `beamertheme/` in my pandoc project.\
I added `theme: metropolis` in my `default.yaml`.\
Then I got the described behavior.

When I copied the files to my project root, the problem was gone.

I deleted `theme: metropolis` in my `default.yaml` and added to my `settings.tex`:
```latex
\usepackage{beamertheme/beamercolorthememetropolis}
\usepackage{beamertheme/beamerfontthememetropolis}
\usepackage{beamertheme/beamerinnerthememetropolis}
\usepackage{beamertheme/beamerouterthememetropolis}
\usepackage{beamertheme/beamerthememetropolis}
```

had to omit `beamertheme/beamercolorthememetropolis-highcontrast.sty` (contrast too high)
 and `beamertheme/pgfplotsthemetol.sty` (error when running `pandoc`)
