### ISSUE TITLE
LaTeX to EPub: German quotation marks not translated correctly

### ISSUE THREAD

**Issue by aschatt** [jgm/pandoc#4789]
German quotation marks in LaTex like "`this"' are not translated to the correct German typography but to English quotation marks in the EPub document.

**Comment by mb21** [comment]
Duplicate of #661

**Comment by mb21** [comment]
Meanwhile:

> You could try using the `--html-q-tags` option. Then use CSS to style the q tags appropriately.

**Comment by jgm** [comment]
Closer to #84 and #2620
