### ISSUE TITLE
HTML-to-gfm reader does not interpret type attribute on <ol>

### ISSUE THREAD

**Issue by ppKrauss** [jgm/pandoc#4797]
Using pandoc v2.2.2, it seems the same old bug  reported at issue #2313 

The problem can be reproduced by 

```sh
pandoc -f html -t gfm << EOT
<ol type="1">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="I">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="i">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="A">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
<ol type="a">
<li>One</li>
<li>Two</li>
<li>Three</li>
</ol>
EOT
```

The result is a bug, all as `type="1"`.

**Comment by mb21** [comment]
The HTML reader actually parses this fine. But since github markdown doesn't support those kinds of lists, the `gfm` and `markdown_github` output formats fall back to normal lists. Try `-t markdown` instead and it works as you want.
