### ISSUE TITLE
Markdown reader: Semantics of space between # and header title changed after v1.19.2.4?

### ISSUE THREAD

**Issue by krlmlr** [jgm/pandoc#4801]
I have read the release notes (searched for instances of "Markdown reader") but haven't found any hint. Is this intended?

```
$ echo "#header" | pandoc
<h1 id="header">header</h1>
$ echo "#header" | /usr/lib/rstudio/bin/pandoc/pandoc
<p>#header</p>

$ pandoc -v | head -n 1
pandoc 1.19.2.4
$ /usr/lib/rstudio/bin/pandoc/pandoc -v | head -n 1
pandoc 2.2.1
```

**Comment by agusmba** [comment]
Probably.
Space after # is standard in commonmark, and in pandoc's markdown (if I'm reading the [manual](http://pandoc.org/MANUAL.html#extension-space_in_atx_header) correctly).

If you want the old behavior try with

```
$ echo "#header" | pandoc -f markdown-space_in_atx_header
<h1 id="header">header</h1>
```

**Comment by krlmlr** [comment]
Thanks! I missed that, sorry for the noise.

**Comment by krlmlr** [comment]
Thanks. How do I submit a PR to the `releases.html` page? Apart from typos, I think this is really a behavioral change (too), because the default has changed.

**Comment by jgm** [comment]
It's jgm/pandoc-website
But you should simultaneously check changelog in jgm/pandoc
