### ISSUE TITLE
slides: support customizable alignment of columns

### ISSUE THREAD

**Issue by smancill** [jgm/pandoc#4805]
When using the new syntax to add side by side columns inside a slide, the beamer writer [hardcodes the alignment of columns to `[T]` (top-level)](https://github.com/jgm/pandoc/blob/69a72099305ff4efe10f8bc5dbab103f1302b2ad/src/Text/Pandoc/Writers/LaTeX.hs#L480). While it may look fine for columns of just text, the result may not be ideal with other combinations of columns with text and images, or just images.

It would be good to have a way to customize the alignment by setting an option in the columns div, just like the width.

**Comment by jgm** [comment]
From the beamer manual:

> The following soptions may be given:
>
> ∙ b will cause the bottom lines of the columns to be vertically aligned.
> ∙ c will cause the columns to be centered vertically relative to each other. Default, unless the global option t is used.
> ∙ onlytextwidth is the same as totalwidth=\textwidth.
> ∙ t will cause the first lines of the columns to be aligned. Default if global option t is used.
> ∙ T is similar to the t option, but T aligns the tops of the first lines while t aligns the so-called baselines of the first lines. If strange things seem to happen in conjunction with the t option (for example if a graphic suddenly “drops down” with the t option instead of “going up,”), try using this option instead.
> ∙ totalwidth=⟨width⟩ will cause the columns to occupy not the whole page width, but only ⟨width⟩, all told. Note that this means that any margins are ignored.

**Comment by jgm** [comment]
One option would be to make each column div sensitive to `alignment="top|bottom|center"`.
In LaTeX we could translate this to `T`, `b`, `c`.

**Comment by cagix** [comment]
this is related to #4150
