### ISSUE TITLE
the rST parser could ignore newlines and other elements

### ISSUE THREAD

**Issue by danse** [jgm/pandoc#4811]
Under some circumstances the rST parser seems to fail detecting newlines, appending the following text with spaces and other newlines until it stops. I cannot see an obvious element marking the start or stop of this behavior.

i ran pandoc 2.2.2.1 on the `.rst` file in [this archive](https://github.com/jgm/pandoc/files/2253731/ignored-newlines.zip) getting as a result the `.native` file included there. In the native file you can search for `\n` finding some of them within a long string. The string eventually stops and spaces seem to be correctly parsed until the behaviour happens again with another long string.

note: this rST file is part of a file that has been generated by pandoc's rST writer

**Comment by jgm** [comment]
It looks like in

     aperta <#rilascio-di-software-esistente-sotto-licenza-aperta>`__)
     
you're missing a backtick before `<#rilascio`.

If this got generated by pandoc, it's a bug -- can you
find a small case to reproduce the bug in the writer?

**Comment by danse** [comment]
the backtick is actually two lines above in an odd place:
```
proprietà delle amministrazioni (3`.6. Rilascio di software esistente
sotto licenza
aperta <#rilascio-di-software-esistente-sotto-licenza-aperta>`__), sia
```

**Comment by jgm** [comment]
Ah, I see.

rST requires a space before inline elements, so the
rST writer should be generating this instead:

proprietà delle amministrazioni (3\ `.6.
Rilascio di software esistente sotto licenza
aperta <#rilascio-di-software-esistente-sotto-licenza-aperta>`__), sia

And in general, we should be inserting a `\ ` before
any complex inline element that doesn't occur at the
beginning of a line or after a space.

Francesco Occhipinti <notifications@github.com>
writes:

**Comment by danse** [comment]
a note: differently from other issues i opened, i don't plan to propose a fix in the foreseeable future for this one. my team will be busy on other topics for the next few months. personally i'm rather surprised by the parsing behavior in this case and i imagine that it would be demanding for me to pinpoint the cause

**Comment by jgm** [comment]
To be clear, there are two issues here:

- an issue with the rST writer, which should insert `BACKSLASH + SPACE` before inline constructs that don't occur after a space.
- an issue with the rST reader, which is is gobbling up a huge amount of text into a Str for reasons I don't yet understand.

**Comment by jgm** [comment]
OK, here's a simple case:
```
% pandoc -f rst -t native
`hi there
ok

there`
^D
[Para [Str "hi there\nok\n\nthere"]]
```
I tracked down the issue.
```haskell
   titleRef ref = return $ B.str ref -- FIXME: Not a sensible behaviour
```
introduced in fe246ce01c4c523b7391d58d910af09bf3bac6e6.

The backquoted material is being parsed as an interpreted role.  There's no explicit role, so the default is used. The default is title-section, but there's no good interpretation for this, so it renders as a string.

Note that, apart from having no good interpretation for title-section, this implementation is flawed because it should stop at blank lines.

**Comment by jgm** [comment]
Pinging @merijn who might be able to clarify further or suggest a fix.

**Comment by merijn** [comment]
I'm not convinced this is a bug? Per the rST spec`title-reference` is the default "default" role, unless the user explicitly specifies a default role: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#interpreted-text

Pandoc, at the time of implementation, didn't really have a way for me to cover `title-reference`'s behaviour (which is what "not sensible behaviour" refers to). The use-case is for citing titles and explicitly calls out italics as misleading/ambiguous and thus undesirable in the spec: http://docutils.sourceforge.net/docs/ref/rst/roles.html#title-reference

As for the multi-line behaviour, the spec doesn't specify the parsing of interpreted-text should end at the end of a line. I agree that the spec isn't very specific and entirely clear in this regard, but considering the number of things roles can be used for I'm not convinced the behaviour should end at newlines?

**Comment by jgm** [comment]
Note that `:raw:` doesn't seem to allow empty lines either (testing with rst2html.py).

**Comment by danse** [comment]
brilliant! well done! :)
