### ISSUE TITLE
language in headings not being translated to LaTeX

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#4813]
I’m afraid that language attributes aren’t translated to LaTeX when they are part of titles

``` markdown
## இது தமிழில் ஒரு தலைப்பு {lang=ta}

[இது பொது சொற்றொடர்.]{lang=ta}
```

which is [converted to](http://pandoc.org/try/?text=%23%23+%E0%AE%87%E0%AE%A4%E0%AF%81+%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AE%BF%E0%AE%B2%E0%AF%8D+%E0%AE%92%E0%AE%B0%E0%AF%81+%E0%AE%A4%E0%AE%B2%E0%AF%88%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81+%7Blang%3Dta%7D%0A%0A%5B%E0%AE%87%E0%AE%A4%E0%AF%81+%E0%AE%AA%E0%AF%8A%E0%AE%A4%E0%AF%81+%E0%AE%9A%E0%AF%8A%E0%AE%B1%E0%AF%8D%E0%AE%B1%E0%AF%8A%E0%AE%9F%E0%AE%B0%E0%AF%8D.%5D%7Blang%3Dta%7D&from=markdown&to=latex):

``` latex
\hypertarget{uxb87uxba4-uxba4uxbaeuxbb4uxbb2-uxb92uxbb0-uxba4uxbb2uxbaauxbaa}{%
\subsection{இது தமிழில் ஒரு
தலைப்பு}\label{uxb87uxba4-uxba4uxbaeuxbb4uxbb2-uxb92uxbb0-uxba4uxbb2uxbaauxbaa}}

\texttamil{இது பொது சொற்றொடர்.}
```

Of course, [a crappy workaround might be](http://pandoc.org/try/?text=%23%23+%5B%E0%AE%87%E0%AE%A4%E0%AF%81+%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AE%BF%E0%AE%B2%E0%AF%8D+%E0%AE%92%E0%AE%B0%E0%AF%81+%E0%AE%A4%E0%AE%B2%E0%AF%88%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81%5D%7Blang%3Dta%7D%0A%0A%5B%E0%AE%87%E0%AE%A4%E0%AF%81+%E0%AE%AA%E0%AF%8A%E0%AE%A4%E0%AF%81+%E0%AE%9A%E0%AF%8A%E0%AE%B1%E0%AF%8D%E0%AE%B1%E0%AF%8A%E0%AE%9F%E0%AE%B0%E0%AF%8D.%5D%7Blang%3Dta%7D&from=markdown&to=latex):

``` markdown
## [இது தமிழில் ஒரு தலைப்பு]{lang=ta}

[இது பொது சொற்றொடர்.]{lang=ta}
```

But I think this is a bug and it should be fixed.

**Comment by jgm** [comment]
The workaround is precisely what you're supposed to do -- put the foreign-language material in a span with the language attribute.

Otherwise the attribute goes on the header, not its contents.

**Comment by ousia** [comment]
Sorry, but I may be missing something. I think that you are mixing how LaTeX deals with languages in headings and how XML (HTML) handles language attributes.

Compare the LaTeX conversion above to the [HTML code](http://pandoc.org/try/?text=%23%23+%E0%AE%87%E0%AE%A4%E0%AF%81+%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AE%BF%E0%AE%B2%E0%AF%8D+%E0%AE%92%E0%AE%B0%E0%AF%81+%E0%AE%A4%E0%AE%B2%E0%AF%88%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81+%7Blang%3Dta%7D%0A%0A%5B%E0%AE%87%E0%AE%A4%E0%AF%81+%E0%AE%AA%E0%AF%8A%E0%AE%A4%E0%AF%81+%E0%AE%9A%E0%AF%8A%E0%AE%B1%E0%AF%8D%E0%AE%B1%E0%AF%8A%E0%AE%9F%E0%AE%B0%E0%AF%8D.%5D%7Blang%3Dta%7D&from=markdown&to=html5):

``` html
<h2 id="இத-தமழல-ஒர-தலபப" lang="ta">இது தமிழில் ஒரு தலைப்பு</h2>
<p><span lang="ta">இது பொது சொற்றொடர்.</span></p>
```

Adding a span only would make sense if the heading has a different language, the contents of the section are in the main language from the document and `--section-divs` are selected.

In other cases heading and section contents may have the same language, such as in:

``` markdown
---
title: Philosophische Schriften
author: Gottlob Frege
lang: de-1901
---

# Logisch-philosophische Abhandlung 

[Deutscher Text.]

# Tractatus Logico--Philosophicus {lang=en}

[English translation.]
```

With the properly rewritten sample:

``` markdown
## இது தமிழில் ஒரு தலைப்பு {lang=ta}

இது பொது சொற்றொடர்.
```

Or if headings attributes aren’t wrapped in a section containing them, it makes no sense not to have the language as an attribute to the heading element (although LaTeX may need an span added to have the language tagged).

**Comment by jgm** [comment]
lang attributes in pandoc generally have an effect
only on Div and Span elements.  Of course, in HTML
output, the attributes are passed through verbatim.
But lang attributes on, say, headers, will not have
any effect on latex output.

The solution is to use a Span.  This gives you
acceptable output in both HTML and LaTeX.  In
the HTML output, the lang attribute will be on a
span rather than the h2 element, but that shouldn't
matter for how the output is displayed.
