### ISSUE TITLE
convert to md file from org-mode lose image link information

### ISSUE THREAD

**Issue by standin000** [jgm/pandoc#4816]
```
pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.6
armel version
```

I have  1.org file
```
$ cat 1.org
[[p06fyg2s.jpg]]

```

run pandoc like this

`pandoc 1.org -o 1.md`

get 1.md like this
```
$ cat 1.md
*p06fyg2s.jpg*
```

it must be

`![](p06fyg2s.jpg)`

**Comment by mb21** [comment]
`[[./p06fyg2s.jpg]]` works though... what does org's reference implementation do?

**Comment by jgm** [comment]
It would be good to get @tarleb's feedback on this.

**Comment by tarleb** [comment]
Org distinguishes between [internal](https://orgmode.org/manual/Internal-links.html#Internal-links) and [external](https://orgmode.org/manual/External-links.html#External-links) links. Images must be given as external links, i.e., the link must be file path, as @mb21 pointed out. An alternative notation would be `[[file:p06fyg2s.jpg]]`.

Emacs behaves similarly to what is described by @standin000 , but would even refuse to convert the document unless the target of the internal link is defined, e.g. if there is a header named `* p06fyg2s.jpg`.

**Comment by jgm** [comment]
If I correctly understood @tarleb's comment, this can be closed.  But I may not have.
If not, I can reopen the issue.
