### ISSUE TITLE
YAML metadata regression in 2.2.3

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#4817]
The following metadata is parsed by 2.2.2.1 but not 2.2.3:
```
---
foo:
- bar: bam
...
```

**Comment by samouy** [comment]
Hello,

I am running pandoc 2.2.3-1 and this author's metada throws an error as documented in Pandoc's user guide : 

```
---
author:
- name: Author One
...
```

Thanks !

**Comment by jgm** [comment]
Upgrade to version 2.2.3.1.

Note:  2.2.3-1 is not the same as 2.2.3.1.

The -1 indicates that this is the first package for
version 2.2.3.
