### ISSUE TITLE
Different interpretation of inline markup in Emacs Org mode and pandoc

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#4820]
Pandoc converts `**foo*` to `*<strong>foo</strong>`, while Emacs converts it to `<b>*foo</b>`.

Other things I have tested:
```
Source:      **foo*
Emacs Org:   <b>*foo</b>
Pandoc Org:  *<strong>foo</strong>

Source:      *foo**
Emacs Org:   <b>foo*</b>
Pandoc Org:  <strong>foo*</strong>

Source:      *foo*bar*
Emacs Org:   <b>foo*bar</b>
Pandoc Org:  <strong>foo*bar</strong>

Source:      *foo**bar*
Emacs Org:   <b>foo**bar</b>
Pandoc Org:  <strong>foo**bar</strong>

Source:      *foo***bar*
Emacs Org:   <b>foo***bar</b>
Pandoc Org:  <strong>foo***bar</strong>
```

**Comment by labdsf** [comment]
Another bug:
```
Source:      *foo *bar*
Emacs Org:   <b>foo *bar</b>
Pandoc Org:  *foo <strong>bar</strong>
```

**Comment by tarleb** [comment]
Not sure yet what's going wrong there. I unassigned myself as I don't have the time to work on this right now. Help welcome.

**Comment by jgm** [comment]
There are ever so many ways to parse nested emphasis,
and this is not formally specified.

The best approach would be to look at the elisp source
and see how emacs org does it.

But this is a pretty low-priority issue, since these
cases are rarely going to come up in real texts.

**Comment by tarleb** [comment]
Closing this in favor of #6132, as this will require us to rethink emphasis parsing as a whole.
