### ISSUE TITLE
Option --wrap=none doesn't affect fb2 writer

### ISSUE THREAD

**Issue by murrrf** [jgm/pandoc#4821]
When converting text with line wrapping to fb2, the option `--wrap=none` has no effect. This does not affect the display of the fb2 file in the reader, but makes it difficult to edit the file manually.

pandoc version 2.2.3.2

Input:
```
pandoc -t fb2 --wrap=none | xmllint --format -
one
two
three

four
five
six
```
Expected output (description is omitted):
```
<p>one two three</p>
<p>four five six</p>
```
Actual output:
```
<p>one
two
three</p>
<p>four
five
six</p>
```

**Comment by jgm** [comment]
This module uses the renderer showContent from
Text.XML.Light.  I don't see a good way to add wrapping.

**Comment by jgm** [comment]
If someone wants to rewrite the whole module to use Text.Pandoc.XML, we could implement wrapping.

**Comment by murrrf** [comment]
In my case, I resort to a double conversion - from plain text to the markdown with the option` --wrap=none` and then to fb2.

**Comment by mb21** [comment]
I deem it unlikely, that someone wants to rewrite the whole fb2 writer using `Text.Pandoc.XML`. Therefore this is probably a "won't fix".
