### ISSUE TITLE
`xcolor` defined colors not working with Pandoc Yaml Header

### ISSUE THREAD

**Issue by anishmittal2020** [jgm/pandoc#4822]
pandoc 2.2.1
TeX 3.14159265
Ubuntu 18.04

[Pandoc - Pandoc User’s Guide](https://pandoc.org/MANUAL.html) states that `color for internal links, citation links, external links, and links in table of contents: uses options allowed by xcolor, including the dvipsnames, svgnames, and x11names lists`.

[xColor Documentation](http://ftp.fernuni-hagen.de/ftp-dir/pub/mirrors/www.ctan.org/macros/latex/contrib/xcolor/xcolor.pdf) states that `Within xcolor.sty, the following color names are defined: red, green,
blue, cyan, magenta, yellow, black, gray, white,
darkgray, lightgray, brown, lime, olive, orange, pink,
purple, teal, violet.`

My YAML header is like this 
```yaml
linkcolor: purple
citecolor: teal
urlcolor: violet
```

But  when I run Pandoc I get this error: `Error producing PDF.
! LaTeX Error: Undefined color `purple'.` 
! LaTeX Error: Undefined color `teal.` 
! LaTeX Error: Undefined color `violet.`

**Comment by jgm** [comment]
Works fine for me. You didn't say what pandoc version you're using.

**Comment by anishmittal2020** [comment]
@jgm  Thanks for the reply. But I stated in the beginning that Pandov Version is 2.2.1? Are you referring to some other version?

**Comment by jgm** [comment]
Sorry, missed the version!  It should work.  I'm not sure why it doesn't.  Here's what I'm doing, with no problems (a minimal case):
```
% cat test.md
---
linkcolor: purple
...

[link](url)
% pandoc test.md -o test.pdf
```
This gives me a PDF with a purple link, and no errors.  Do you get a different result with this simple case?

Another question:  are you using a custom template?  That could be the problem.  (Check also to make sure you don't have `~/.pandoc/templates/default.latex`, which would be used implicitly as a custom template.)

**Comment by jgm** [comment]
You aren't by any chance setting a `colorlinks` variable to false, are you?

**Comment by jgm** [comment]
Please provide a minimal case we can use to reproduce the problem, together with the exact command line used.  Otherwise I'm afraid we can't help.

**Comment by anishmittal2020** [comment]
Sorry for the delay, I tried this with colors like red, green, darkgray, violet, purple
    % cat test.md
    ---
    linkcolor: purple
    ...
    
    [link](url)
    % pandoc test.md -o test.pdf

But, all the colors look the same.

**Comment by anishmittal2020** [comment]
OUTPUT of `pandoc test.md -t latex -s`:

\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{
            colorlinks=true,
            linkcolor=purple,
            citecolor=Blue,
            urlcolor=Blue,
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\date{}

\begin{document}

\href{url}{link} \textcolor{red}{some text} \textcolor{blue}{sometext}
\textcolor{green}{sometext} \textcolor{violet}{sometext}
\textcolor{purple}{sometext} \textcolor{teal}{sometext}
\textcolor{darkgray}{sometext} \textcolor{olive}{sometext}

\end{document}

**Comment by anishmittal2020** [comment]
The first one is colored but is it Purple?

**Comment by jgm** [comment]
Agreed, the link is not purple.

I think I see what's going on.  According to the hyperref manual, `linkcolor` is for "normal internal links."  `filecolor` is for "URLs which open normal files."  I tried it, and setting `filecolor` to purple in the latex file makes the link purple.

**Comment by jgm** [comment]
This is a bit unintuitive, so we may want to set `filecolor` automatically to the value of `linkcolor`...
