### ISSUE TITLE
Docx writer mishandles display math in spans

### ISSUE THREAD

**Issue by lierdakil** [jgm/pandoc#4826]
Hi. So, the subject says it all really. Consider this snippet:
```markdown
Here's some display math: $$y = x$$

Here's some display math wrapped in a span:
[$$z = t$$]{#eq:eq1}
```
The first equation will be converted just fine. The second, however, will render as inline. I believe the reason for that is `fixDisplayMath` function here:
https://github.com/jgm/pandoc/blob/9752dcd61aa72a9e1e59bafcd55376ab1d275620/src/Text/Pandoc/Writers/Shared.hs#L200-L219
which apparently doesn't handle this case.

This creates problems in pandoc-crossref: https://github.com/lierdakil/pandoc-crossref/issues/192.

Not sure if earlier versions of Pandoc handled this or not.

Not entirely sure what a proper fix would be, advice is appreciated. At the very least, I'd like to be able to reference math, and wrapping it in a span seems to be the only sensible way to do that (?). The kneejerk fix that immediately comes to mind is to amend `isDisplayMath` to handle the case of math-in-span in particular, but that's probably not the most elegant or robust solution.

**Comment by jgm** [comment]
> Not entirely sure what a proper fix would be, advice
> is appreciated. At the very least, I'd like to be
> able to reference math, and wrapping it in a span
> seems to be the only sensible way to do that (?).

Another option would be to wrap it in a Div.
Then this special treatment would be avoided.

> The kneejerk fix that immediately comes to mind is
> to amend `isDisplayMath` to handle the case of
> math-in-span in particular, but that's probably not
> the most elegant or robust solution.

I'd be okay with this solution, as a first step.

It's true, in general you might have e.g.

   Emph [Math DisplayMath _, Math DisplayMath _,
      Span _ [Math DisplayMath _]]

and in principle this kind of thing should be handled
too.  I'm open to ideas about a more general solution.
But if it's too involved, the basic thing should
be implemented.

**Comment by jgm** [comment]
OK, just changing isDisplayMath won't be enough: we'd need to change the Span to a Div, or change the pattern matching in the docx writer (which is looking for Para [Math DisplayMath _]).

**Comment by lierdakil** [comment]
> Another option would be to wrap it in a Div. Then this special treatment would be avoided.

Wrapping an inline element in a Div, which is a block element is non-trivial and in part defeats the purpose, since it's functionally similar to `Para [Span _ [Math DisplayMath _]]`

> OK, just changing isDisplayMath won't be enough: we'd need to change the Span to a Div, or change the pattern matching in the docx writer (which is looking for Para [Math DisplayMath _]).

Docx writer should just use `isDisplayMath` too instead of pattern-matching directly, probably.

**Comment by jgm** [comment]
Nikolay Yakimov <notifications@github.com> writes:

>> OK, just changing isDisplayMath won't be enough: we'd need to change the Span to a Div, or change the pattern matching in the docx writer (which is looking for Para [Math DisplayMath _]).
>
> Docx writer should just use `isDisplayMath` too instead of pattern-matching directly, probably.

That makes sense.
