### ISSUE TITLE
Powerpoint Output: bullet points are rendered as indented to level 2

### ISSUE THREAD

**Issue by rich-iannone** [jgm/pandoc#4828]
The issue here was originally posted in https://github.com/rstudio/rmarkdown/issues/1418, where the OP expressed that this output (bullet points appearing as indented to level 2) is not the expected behaviour, requiring manual editing after rendering.

To reproduce, use the following (bullets.md):

````
### Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3
````

I ran this with pandoc (v.2.2.1):

```
pandoc +RTS -K512m -RTS bullets.md --to pptx --from markdown --output bullets.pptx
```

Here's a screenshot of bullets.pptx, showing the bullet characters appearing reasonably far from the left border of the text box.

<img width="883" alt="bullets-indented" src="https://user-images.githubusercontent.com/5612024/43918135-13e1860a-9bc7-11e8-887a-e0b8cc47fc11.png">

**Comment by jgm** [comment]
@jkr when you have a chance, could you look at this and #4827?

**Comment by jkr** [comment]
Yes -- sorry I've been offline this summer. (Newly associated, so
checked out a bit.) I will take a look at these today, and get something
up soon.

**Comment by dvbuntu** [comment]
I've noticed this recently as well.  Any update or workaround on this?

**Comment by jkr** [comment]
Sorry to take so long on this. This is just PowerPoint's default template's formatting. The bullets are actually level 1. If you want it to be indented differently, you need to use a different template (`reference-doc`, in pandoc-speak).

Run pandoc on the above example to produce a PowerPoint doc.

~~~
$ cat input.text                                         
### Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3
~~~

~~~
$ pandoc input.text -o output.pptx                             
~~~

Note the "lvl = 1" in the output
~~~
$ unzip -p output.pptx ppt/slides/slide1.xml|xmllint --format -

<?xml version="1.0" encoding="UTF-8"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr>
        <p:cNvPr id="1" name=""/>
        <p:cNvGrpSpPr/>
        <p:nvPr/>
      </p:nvGrpSpPr>
      <p:grpSpPr>
        <a:xfrm>
          <a:off x="0" y="0"/>
          <a:ext cx="0" cy="0"/>
          <a:chOff x="0" y="0"/>
          <a:chExt cx="0" cy="0"/>
        </a:xfrm>
      </p:grpSpPr>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="2" name="Title 1"/>
          <p:cNvSpPr>
            <a:spLocks noGrp="1"/>
          </p:cNvSpPr>
          <p:nvPr>
            <p:ph type="title"/>
          </p:nvPr>
        </p:nvSpPr>
        <p:spPr/>
        <p:txBody>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p>
            <a:pPr lvl="0" marL="0" indent="0">
              <a:buNone/>
            </a:pPr>
            <a:r>
              <a:rPr/>
              <a:t>Slide</a:t>
            </a:r>
            <a:r>
              <a:rPr/>
              <a:t> </a:t>
            </a:r>
            <a:r>
              <a:rPr/>
              <a:t>with</a:t>
            </a:r>
            <a:r>
              <a:rPr/>
              <a:t> </a:t>
            </a:r>
            <a:r>
              <a:rPr/>
              <a:t>Bullets</a:t>
            </a:r>
          </a:p>
        </p:txBody>
      </p:sp>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="3" name="Content Placeholder 2"/>
          <p:cNvSpPr>
            <a:spLocks noGrp="1"/>
          </p:cNvSpPr>
          <p:nvPr>
            <p:ph idx="1"/>
          </p:nvPr>
        </p:nvSpPr>
        <p:spPr/>
        <p:txBody>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p>
            <a:pPr lvl="1"/>
            <a:r>
              <a:rPr/>
              <a:t>Bullet 1</a:t>
            </a:r>
          </a:p>
          <a:p>
            <a:pPr lvl="1"/>
            <a:r>
              <a:rPr/>
              <a:t>Bullet 2</a:t>
            </a:r>
          </a:p>
          <a:p>
            <a:pPr lvl="1"/>
            <a:r>
              <a:rPr/>
              <a:t>Bullet 3</a:t>
            </a:r>
          </a:p>
        </p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
</p:sld>
~~~

**Comment by eptesicus** [comment]
> Sorry to take so long on this. This is just PowerPoint's default template's formatting. The bullets are actually level 1. If you want it to be indented differently, you need to use a different template (`reference-doc`, in pandoc-speak).
> 
> ```
> 
> Note the "lvl = 1" in the output

Indentation levels start at 0 in Powerpoint, so lvl = "1" is actually the second level.

**Comment by jkr** [comment]
Yes, but we treat 0-level as content paragraphs (everything is a leveled paragraph, with our without a bullet).

**Comment by jkr** [comment]
I suppose we could have content and first-level bullets both at 0, but that would cause problems if you have unbullleted-style lists...

**Comment by jgm** [comment]
What would the problems be?
And by unbulleted-style lists, do you mean just regular paragraphs, or something else?

**Comment by stevenjcarr** [comment]
Any further update on this? Would be good to get a fix. I would expect both content and first-level bullets to be at level-0 this is how most PowerPoint content is written from what I've seen. Slides are typically written in two ways... all bullets in which case they need to be at level-0, or you have a leading paragraph followed by bullets, but they aren't typically indented, they would still be at level-0.

**Comment by cameronneylon** [comment]
I came across this issue which wasn't the behaviour I was expecting and arrived here pretty quickly based on a search. There is one super-hacky work-around which appears to be viable. That is to change the position and format in the Second and other level bullets in the ppt template file.

1. In your template view the Slide Master (View Menu, select 'Slide Master' from ribbon)
2. In view menu select the checkbox for 'Ruler' in the ribbon
3. Return to the 'Home' menu in the ribbon
4. Select the _lowest_ level of bullets you want to adjust and move by grabbing the handles in the ruler and using the level above as an approximate guide (change the font size first, then move the bullets, its a fiddly pain)
5. Work your way back up to Level 2 using Level 1 as a guide
6. Use the template (and if there is an eventual fix remember you did this, although if you only ever use one level of bullets it shouldn't matter much)
