### ISSUE TITLE
Square brackets in markdown get escaped

### ISSUE THREAD

**Issue by jmgirard** [jgm/pandoc#4830]
I am using pandoc v2.2.2.1. When including square brackets in markdown, they get escaped with backslashes. How can I prevent this?

```
$ echo '[1, 2]' | pandoc -f markdown -t gfm
\[1, 2\]
```

**Comment by jgm** [comment]
Jeffrey M Girard <notifications@github.com> writes:

> I am using pandoc v2.2.2.1. When including square brackets in markdown, they get escaped with backslashes. How can I prevent this?

You can't.  It's not a bug.  It's designed to prevent
unintentional links.

**Comment by jgm** [comment]
PS. In general, you should ask questions on pandoc-discuss.
This tracker is for bug reports.
