### ISSUE TITLE
Markdown to docx with custom styles in spans result in reference styles being overwritten 

### ISSUE THREAD

**Issue by kronicd** [jgm/pandoc#4843]
When using custom styles with the span syntax pandoc will create a new style in the output document, even where the style exists in the source document.

For instance in the following, example1 will appear rendered correctly, but example2 will have an additional default style defined with the same name, overriding the style when viewed in Word.

```
The following style (example1) will work as expected <div custom-style="example1">this works
 great</div> however when using span tags the style will be defined again, overriding the previous
 as you can see<span custom-style="example2">this doesn't work great</span>. This makes me sad :(
```

If we run the above through pandoc with a reference document that shows example1 highlighted yellow and example2 highlighted green, we get the following:

`cat input.txt | pandoc -f markdown --reference-doc='custom-reference.docx' --output testabcd.docx`

![image](https://user-images.githubusercontent.com/551541/44294130-04590500-a2c5-11e8-918a-c1a5a6eb3629.png)

I have attached all files here, this issue should be trivial to replicate with the files and command provided.

[custom-reference.docx](https://github.com/jgm/pandoc/files/2299032/custom-reference.docx)
[input.txt](https://github.com/jgm/pandoc/files/2299035/input.txt)
[testabcd.docx](https://github.com/jgm/pandoc/files/2299033/testabcd.docx)

**Comment by jgm** [comment]
If I understand correctly, spans with custom styles should generate character styles, while divs generate paragraph styles.  Isn't that the issue here?  A paragraph style named `example2` isn't the same as a character style named `example2`.

**Comment by kronicd** [comment]
Thanks very much for the explanation, I've tried with a character style and can see that it works now.

I will modify the documentation slightly and submit a pull request. Cheers

**Comment by vishalmudgalpw** [comment]
@kronicd Could you re-upload custom-reference.docx, input.txt, output.docx files after correction that you made, if possible.

@kronicd , @jgm Is there any possibility in conversion of html to docx file, i could add custom style for display:flex on any element 
`<div style="display:flex">content</div>`
