### ISSUE TITLE
Space inside of a tag being removed

### ISSUE THREAD

**Issue by myfriend12** [jgm/pandoc#4845]
Have an interesting issue regarding spaces in links. When converting from HTML to doc. if you have a trailing space inside of the link, it strips it but does not add it outside of the link. For example:

`This is a test sentence with a link <a href="https://www.google.ca">inside </a>of it`
The sentence will convert to this: This is a test sentence with a link [inside](https://www.google.ca)of it.
The sentence should be: This is a test sentence with a link [inside](https://www.google.ca) of it.
Ran the standard pandoc config, pandoc -s input.html -o output.docx

This is happening on the latest version of Pandoc on Ubuntu 12.04

The document converts fine and works except for the above issue.

**Comment by jgm** [comment]
```
% pandoc -f html -t native
x<a href="/foo"> leading trailing space </a>x
^D
[Plain [Str "x",Link ("",[],[]) [Str "leading",Space,Str "trailing",Space,Str "space"] ("/foo",""),Str "x"]]
```
We should handle this the same way we handle:
```
% pandoc -f html -t native
x<em> hi </em>x
^D
[Plain [Str "x",Space,Emph [Str "hi"],Space,Str "x"]]
```

**Comment by myfriend12** [comment]
Thanks for the quick fix, Looking forward for the next release.
