### ISSUE TITLE
--include-before-body and --toc duplicates the "before-body" part in EPUB

### ISSUE THREAD

**Issue by psoukie** [jgm/pandoc#4857]
pandoc doubles the include-before-body content when generating an epub with --toc.

pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2

Repro Steps:

**test.md**
```---
title: Test
---

# Heading

Test
```

**before.html**
```<p>Foo</p>```

Command:  `pandoc --include-before-body=before.html test.md -o book.epub --toc`

Outcome:  'Foo' is included both before and after the TOC.

Note that converting to HTML doesn't create the same issue.

**Comment by jgm** [comment]
I can't reproduce this.
I only see one Foo, before the TOC.
Can you upload or link to the `book.epub` you produced this way?

**Comment by jgm** [comment]
psoukie <notifications@github.com> writes:

> Np. See attached (I renamed it to .zip so I could upload it.). The string 'Foo' appears both in the nav.xhtml and ch001.xhtml files.

OK, I understand what you mean now.

Well, this is because the nav.xhtml uses the same
template as the chapters.  This isn't obviously a bug.
After all, some people might WANT to include something
consistently in all chapters and the nav.

**Comment by psoukie** [comment]
I’m not an expert on EPUB so there might be use cases like that. My understanding of include-before-body is that it’s to allow inclusion of things such as front matter of the book, in front of the TOC and the main content of the ebook. The way it works now is that it gets represented in the nav document (which I am not sure the nav is for) and then it appears in front of the first chapter, but nevertheless AFTER the TOC. In short, if this is the intended behavior, then I need to find a workaround for injecting content BEFORE the TOC and not as part of the nav or as part of the main document. Again, my assumption was, this is what the include-before-body function was designed to do.

**Comment by jgm** [comment]
`--include-before-body` adds a piece that is rendered
in the template.

For epub, the template is used to generate each
chapter (and also the nav.xhtml "chapter").

So the `--include-before-body` text will be added
in front of every chapter.

Most likely that's not what you want to use, if
your intent is to add front matter to a book.

The table of content isn't actually put in order
by anything in the epub.  It is included as the
'guide' element, and the epub reader decides how
to display it.

You could try adding your content to the title
page "chapter".  If you look at the default epub
template, you'll see a conditional `$if(titlepage)$`;
everything inside that conditional will go on the
title page.  You could include an abstract,
publication info, acknowledgments, and so on there,
after the title and author.

That's about as close as we can currently come to
front matter.  If there are better places to include
this in an epub, we can explore changes to pandoc.

**Comment by psoukie** [comment]
This is very good information, thank you for sharing it!

**Comment by jgm** [comment]
see also #4823
