### ISSUE TITLE
katex-stylesheet flag does not exist

### ISSUE THREAD

**Issue by stop-start** [jgm/pandoc#4862]
I'm using version 2.2.3.2 on osx
When trying to use the --katex-stylesheet=URL flag as mentioned in the doc I get the error `Unknown option --katex-stylesheet`.

Example of failed command:
```
pandoc -s --katex=https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.js --katex-stylesheet=https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.css -o output.html input.md
```
Output:
```
Unknown option --katex-stylesheet.
Try pandoc --help for more information.
```

Also, I don't know if it's related but when using --katex=URL with html5 output, the math in the html file is not formated but with just --katex it is. If it isn't related to the above I can open another issue with more details.

**Comment by jgm** [comment]
Trying to track down why `--katex-stylesheet`
disappeared. The option was removed, and the argument
for a stylesheet was removed from the KaTeX
constructor in commit
23eaf2a74f686f0af95544047020bff5fcb6ab4f.
But the commit message didn't mention removing
the option, so the changelog doesn't include it
and the man page was never updated!

I also don't recall why it was removed, but looking
in the mailing list from around Oct. 5, 2017 should
give a clue.

In any case the manual should be updated.

**Comment by mb21** [comment]
It appears that the two options (for loading the js and loading the css file respectively), were replaced with one, which only accepts `the base URL for the KaTeX library`. So it accepts a directory.

**Comment by stop-start** [comment]
@mb21  Now I understand why using the --katex=URL wasn't working for me. I was putting the whole .js path instead of the directory. Now it works
