### ISSUE TITLE
How to add html style?

### ISSUE THREAD

**Issue by qq253498229** [jgm/pandoc#4864]

**Comment by wilx** [comment]
See the [manual](http://pandoc.org/MANUAL.html):

`-c URL, --css=URL`

>    Link to a CSS style sheet. This option can be used repeatedly to include multiple files. They will be included in the order specified.

**Comment by qq253498229** [comment]
Is it written like this?
`pandoc test.md -f markdown -c ./css.css -t html -o test.html`
I tried it and it didn't work.

**Comment by wilx** [comment]
> I tried it and it didn't work.

Could you be more specific?

**Comment by mb21** [comment]
Please ask questions like this on the pandoc-discuss mailing list.
Also, we cannot help you unless you tell use _exactly_ what's the output and what's wrong with it.

**Comment by qq253498229** [comment]
I want to add style to the output html, but I don't know how to implement it.

This is the command I am using:

```
pandoc test.md -f markdown -c ./css.css -t html -o test.html
```

test.md:

```
# This is h1

- li1
- li2
  - li2.1
  - li2.2
- li3
```

css.css:

```
h1 {
  color: red;
}
```

**Comment by link2xt** [comment]
@qq253498229 You have to add option `-s` or `--standalone`.

**Comment by qq253498229** [comment]
@link2xt Thank you very much, it's works for me.
