### ISSUE TITLE
highlighting with soul (\hl) stopped working after upgrade

### ISSUE THREAD

**Issue by hvwaldow** [jgm/pandoc#4866]
The following source works well in pandoc 1.17.2. With pandoc 2.2.3.2 however, the curly braces belonging to `\hl{Highlight this text!}` show up in the output and only the first (openening) curly brace is highlighted.

    ---
    header-includes:
    - \usepackage{soul}
    - \usepackage{color}

    ---

    \hl{Highlight this text!}

The output was created with `pandoc -t latex -o demo_pandoc-v[XXX].pdf demo.md`.

The output-files are [demo_pandoc-v1.17.2.pdf](https://github.com/hvwaldow/pandocbug/blob/master/demo_pandoc-v1.17.2.pdf) and [demo_pandoc-v2.2.3.2.pdf](https://github.com/hvwaldow/pandocbug/blob/master/demo_pandoc-v2.2.3.2.pdf), respectively.

**Comment by jgm** [comment]
That's odd, because I get a different result.  Let's
try to reduce this to a minimal test case. Since the
problem occurs in the LaTeX intermediary, just use
`pandoc -t latex` (no need for `-s`).  Do you still
see the braces escaped?  Can you reduce your input
to an absolute minimum, for a reproducible test case?

**Comment by hvwaldow** [comment]
Funny. It looks like there is something subtle about the string `hl`:

    vonwalha@inf-vonwalha-pc:~/rdm/pandocbug$ pandoc -v
    pandoc 2.2.2
    Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
	Default user data directory: /home/vonwalha/.pandoc
	Copyright (C) 2006-2018 John MacFarlane
	Web:  http://pandoc.org
	This is free software; see the source for copying conditions.
	There is no warranty, not even for merchantability or fitness
	for a particular purpose.
	vonwalha@inf-vonwalha-pc:~/rdm/pandocbug$ echo "\hl{}" |pandoc -t latex
	\hl\{\}
	vonwalha@inf-vonwalha-pc:~/rdm/pandocbug$ echo "\foo{}" |pandoc -t latex
	\foo{}

Compare with version 2.2.1:

	vonwalha@inf-vonwalha-pc:~/rdm/pandocbug$ pandoc -v
	pandoc 2.2.1
	Compiled with pandoc-types 1.17.4.2, texmath 0.11, skylighting 0.7.0.2
	Default user data directory: /home/vonwalha/.pandoc
	Copyright (C) 2006-2018 John MacFarlane
	Web:  http://pandoc.org
	This is free software; see the source for copying conditions.
	There is no warranty, not even for merchantability or fitness
	for a particular purpose.
	vonwalha@inf-vonwalha-pc:~/rdm/pandocbug$ echo "\hl{}" |pandoc -t latex
	\hl{}

That gives me at least a workaround, this works:

    \newcommand{\highlight}[1]{\hl{#1}}
    \highlight{Highlight this text!}

**Comment by jgm** [comment]
Aha!  I see what is happening.  This issue was fixed
with commit 1b668657632c58964e8d7df42ea88e5ea6abfb1e.

**Comment by hvwaldow** [comment]
Ah, OK,  good diagnostics. A hectoliter of thanks :).
