### ISSUE TITLE
Org-Mode Reader: Confusion between DEADLINE and PROPERTIES

### ISSUE THREAD

**Issue by jholewinski** [jgm/pandoc#4867]
When parsing org-mode input, pandoc appears to get confused when a heading has a DEADLINE attached before the PROPERTIES block.

For example:

```
* Heading One
  DEADLINE: <2018-09-28 Fri>
  :PROPERTIES:
  :MYPROP: 1234
  :END:

* Heading Two
  :PROPERTIES:
  :MYPROP: 5678
  :END:
  DEADLINE: <2018-09-17 Mon>
```

Looking at the pandoc native output, I see:

```
$ pandoc org-repo.org -t native
[Header 1 ("heading-one",[],[]) [Str "Heading",Space,Str "One"]
,Para [Str "DEADLINE:",Space,Str "<2018-09-28",Space,Str "Fri>"]
,Header 1 ("heading-two",[],[("myprop","5678")]) [Str "Heading",Space,Str "Two"]
,Para [Str "DEADLINE:",Space,Str "<2018-09-17",Space,Str "Mon>"]]
```

Notice that the `myprop` property is only on the second heading. I can work around this, but emacs wants to insert the DEADLINE line right after the heading, before the PROPERTIES block.

Pandoc version 2.2.3.2

**Comment by tarleb** [comment]
Planning info is now parsed and stripped from the document. I'll add support for the `p` export option later (so users can add the planning info back into the final output).

**Comment by tarleb** [comment]
Support for the `p` [export option](https://orgmode.org/manual/Export-settings.html) has been added.

**Comment by jholewinski** [comment]
Thanks!
