### ISSUE TITLE
[feature request] Is it possible to add "nocite" as a pandoc argument?

### ISSUE THREAD

**Issue by haozhu233** [jgm/pandoc#4872]
Based on the documentation site (https://pandoc.org/MANUAL.html#citations), 
> It is possible to create a bibliography with all the citations, whether or not they appear in the document, by using a wildcard 
```
---
nocite: |
  @*
...
```

I'm wondering if it's possible to add `nocite` as a pandoc argument, like `--nocite="@*"`, so that people can use it in the same way as they deal with `--csl=FILE`. Right now, it seems that `nocite` is the only variable that is only acceptable in the "metadata field". Thank you!!

Related issue: https://github.com/bearloga/wmf-product-analytics-report/issues/1

**Comment by jgm** [comment]
You can do:

    pandoc -M nocite='@*'

That's good enough, I think!  (And it's not true, in
general, that for each significant metadata field
there is a crommand line option.)

**Comment by haozhu233** [comment]
Oh! That's good to know. Yes, I also think it's good enough :D

**Comment by bearloga** [comment]
Oh neat, thank you very much!!!

**Comment by jgm** [comment]
I'm sorry, but what I said above is wrong.  You can't use `-M nocite='@*'`, because values for `-M` are treated as plain text and not parsed as Markdown.
