### ISSUE TITLE
Supply links to lua-filters repo

### ISSUE THREAD

**Issue by uvtc** [jgm/pandoc#4874]
If https://github.com/pandoc/lua-filters is the canonical location of Pandoc's lua filters, there should be a links to it from:

  * https://pandoc.org/lua-filters.html
  * https://github.com/jgm/pandoc/wiki/Pandoc-Extras , or https://github.com/jgm/pandoc/wiki/Pandoc-Filters ?
  * and maybe in a section in http://pandoc.org/CONTRIBUTING.html called "Contribute a filter?"

**Comment by mb21** [comment]
Indeed. I guess the introductions of the http://pandoc.org/filters.html and http://pandoc.org/lua-filters.html pages could also use an overhaul, as they don't even link to each other.

**Comment by jgm** [comment]
PRs welcome!

**Comment by jgm** [comment]
Note that the filters.md and lua-filters.md documents are in the pandoc repository, under doc/.
