### ISSUE TITLE
HTML output of mathematical formulas

### ISSUE THREAD

**Issue by profgerto** [jgm/pandoc#4879]
I'm having issues converting markdown latex formulas to html. Using \begin{equation}/\end{equation} doesn't give any output at all, and using $/$$ I mainly have issues with the \frac{}{} operator. More specifically, a formula without \frac works, but adding a \frac term messes it up. Output to pdf of such a file does work.

Tried with pandoc 2.2.1 and 2.2.3, downloaded through anaconda.

**Comment by profgerto** [comment]
Solved: after a long google hunt, turned out I had to turn on mathjax with the --mathjax flag.

**Comment by jgm** [comment]
It's in the manual here:
http://pandoc.org/MANUAL.html#math-rendering-in-html

> Solved: after a long google hunt, turned out I had to turn on mathjax with the --mathjax flag.
>
