### ISSUE TITLE
Org mode writer escapes special chars with backslash

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#4882]
Org mode tries to escape special characters, like "_", with a backslash:
```
$ echo '\_foo_' | pandoc -f markdown -t org
\_foo\_
```
But it still gets interpreted as underline, and in addition you have those backslashes.

It looks like there is no easy way to escape speical characters in Org mode, but at least it would be nice not to insert backslashes that don't work: https://stackoverflow.com/questions/15324852/how-do-i-escape-slash-in-org-mode

**Comment by jgm** [comment]
Interesting.  We could switch to "escaping" with
zero-width spaces instead.  Would that be better
than just leaving them so they cause emphasis?

**Comment by link2xt** [comment]
@jgm Inserting zero-width whitespace before the `_` character seems like a hack that relies on the fact that Org does not recognize it as a space, I don't like it. Just leave it as is, at least it will work for words like `foo_bar`, where `_` should not be escaped at all.

If someone has time, it is better to recognize when special characters are going to be interpreted and remove them together with emitting the warning, but it is not that important IMO.
