### ISSUE TITLE
Please add more support for doc's form，it doesn't look well 

### ISSUE THREAD

**Issue by doubliekill** [jgm/pandoc#4886]
Asking a question?
Please use the pandoc-discuss mailing list instead:
https://groups.google.com/forum/#!forum/pandoc-discuss
This tracker is for bug reports and enhancement requests.

Reporting a bug?
Please include your pandoc version and an example that allows us
to reproduce the problem (complete input, exact command line
used, expected and actual output).  The smaller the example, the
better.

**Comment by mb21** [comment]
If you're asking for the docx reader to support forms, I'm guessing this is out-of-scope for pandoc at the moment.

If you have a question, please use the pandoc-discuss mailing instead.
