### ISSUE TITLE
markdown emphasis for Chinese text does not work

### ISSUE THREAD

**Issue by jdhao** [jgm/pandoc#4887]
I  am using pandoc to generate PDF from Markdown files. I have found that Markdown emphasis does not work for Chinese text. The content of Markdown file:

```
__test__ some text

__测试__一些文字

**test** test

**测试** 测试
```

The command I use to generate PDF is 

```
pandoc --pdf-engine=xelatex -V CJKmainfont=SimHei test.md -o test.pdf
```

The generated PDF is 

![image](https://user-images.githubusercontent.com/16662357/45418721-c2e72a00-b6b7-11e8-985d-9ec933b68f84.png)

You can see that for emphasis works for English but not for Chinese.  

## Version info
+ Pandoc verison: 2.2.3.2
+ OS: Windows 10
+ LaTeX: MikTeX with xelatex installed

**Comment by mb21** [comment]
For the second line, try `**测试**一些文字` instead. There needs to be space behind the underscores for them to be recognized as emphasis.

The fourth line seems to be a LaTeX font problem. Make sure you have a bold variant of `SimHei` installed... try `-s -o output.tex` and then running `xelatex output.tex` to see what's going on under the hood.

**Comment by jdhao** [comment]
Thanks, the main reason is that the font used does not have bold shape. I changed the font to `Microsoft YaHei`. Now the emphasis works as expected.
