### ISSUE TITLE
Possible to turn off siunitx macros?

### ISSUE THREAD

**Issue by pbreheny** [jgm/pandoc#4888]
I have a longstanding habit of using a user-defined latex macro `\as{}`.  This always used to parse correctly in Pandoc, but now fails, apparently due to a conflict with `siunitx`.  The markdown code:

```
\as{2+2}
```

is parsed to the invalid latex code:

```
\as\{2+2\}
```

I have no desire to use `siunitx`, nor had I ever heard of it until trying to diagnose this problem.  Is there a way to turn it off and prevent it from taking over my macros?

I am using Pandoc 2.2.3.2.

**Comment by mb21** [comment]
Thanks for reporting. This seems to be fixed on current master. You could try [a nightly](https://github.com/pandoc-extras/pandoc-nightly), or wait for the next release.

**Comment by pbreheny** [comment]
Ah, perfect -- I didn't know you could get nightly builds from `pandoc-extras/pandoc-nightly`, but that fixes my problem.  Thank you so much!

**Comment by jgm** [comment]
As noted, it's fixed in master.

But if your macro definition is in the tex parsed by
pandoc, it should be applied.  (If you're converting
from markdown, try putting the macro definition in
your document.)

**Comment by jgm** [comment]
Probably another bug in 2.3.2.2 that has since been
fixed. Current master gives:

\providecommand{\as}[1]{\begin{align*}#1\end{align*}}

\begin{align*}2+2\end{align*}
