### ISSUE TITLE
Line breaks in the header of a Markdown table with PDF output

### ISSUE THREAD

**Issue by sjackman** [jgm/pandoc#4890]
I'd like to include a line break in the header of a markdown table. This works when converting Markdown to HTML, but not yet converting Markdown to PDF.

For example:
```markdown
| Distance<br>(km) | Time<br>(s) |
|------------------|-------------|
| 12               | 34          |
| 56               | 78          |
```

Produces correct HTML, but incorrect LaTeX.
```latex
\toprule
Distance(km) & Time(s)\tabularnewline
\midrule
…
```

**Comment by jgm** [comment]
You use `<br>`.  That gets parsed as raw HTML, and raw
HTML only goes through to formats allowing HTML.  A
native pandoc line break would come across to LaTeX, but
to enter one, you'll need to use a grid table.

**Comment by sjackman** [comment]
Thanks for your quick response, John. It'd be nice to have a native Pandoc line break that worked with Markdown tables. The following grid table worked:

```
+------------------+-------------+
| Distance \       | Time \      |
| (km)             | (s)         |
+==================+=============+
| 12               | 34          |
+------------------+-------------+
| 56               | 78          |
+------------------+-------------+
```

**Comment by sjackman** [comment]
Since `<br>` works with HTML output, it gave me the idea that `\newline` may work for PDF output. It does make it through to the TeX output by Pandoc as I had hoped, but `\newline` only works in paragraphs and not in tables. `\\` works in tables, but Pandoc outputs `\textbackslash` rather than `\\`, which I understand, since `\\` is Markdown for a backslash, not a line break.

Is there a way for Pandoc to pass the TeX `\\` straight through to its output without interpretation? I was thinking something like `\tex{\\}`.

**Comment by jgm** [comment]
Try

\newcommand{\dummy}[1]{#1}

and use \dummy{\\}

Also run with pandoc -f markdown-latex_macros, to
ensure that this is passed through verbatim and not
resolved.  I don't know if it will work but it might.

**Comment by sjackman** [comment]
That nearly worked! The TeX output by Pandoc is correct, but the table is formatted incorrectly.

![table](https://user-images.githubusercontent.com/291551/45507350-b3fb8880-b746-11e8-89d7-49858953ca66.png)


This works! (though it's a bit unsightly)

```
| \vtop{\hbox{\strut Distance}\hbox{\strut (km)}} | \vtop{\hbox{\strut Time}\hbox{\strut (s)}} |
|-----|----|
| 12  | 34 |
| 56  | 78 |
```
https://tex.stackexchange.com/a/132661
