### ISSUE TITLE
\pageref in TeX template doesn't work

### ISSUE THREAD

**Issue by phmarek** [jgm/pandoc#4892]
I'm using `\pageref{LastPage}` in a TeX template. Upon rendering, I only get the output `??`.

Is there a way to have `pandoc` run the latex commands twice, so that the page numbers can be calculated? Alternatively, is there a way to keep the temporary (`.aux`) files used by TeX?

**Comment by mb21** [comment]
What pandoc version/command are you using?

**Comment by jgm** [comment]
Pandoc does currently run latex at least twice when creating PDFs.
Try running with `--verbose` to see if you see a relevant error message or warning.

**Comment by phmarek** [comment]
I'm using 2.2.1-2+b1 (Debian amd64).

`--verbose` gives more hints, thanks:

```
LaTeX Warning: Reference `LastPage' on page 2 undefined on input line 107.
LaTeX Warning: Reference `LastPage' on page 3 undefined on input line 112.
LaTeX Warning: Reference `LastPage' on page 4 undefined on input line 202.
LaTeX Warning: Reference `LastPage' on page 5 undefined on input line 268.
```


The default template in `/usr/share/pandoc/data/templates/default.latex` doesn't set this label; I now put an explicit `\label{LastPage}` into my copy of the template, and now it works.

Thanks a lot!

**Comment by phmarek** [comment]
Wait, I left the issue open so that the default template gets the label included?!

**Comment by jgm** [comment]
You want us to include `\label{LastPage}` in the *default* template?  Why would we do that?  Just include it in your custom template and be happy it works.
