### ISSUE TITLE
pandoc 2.2.x adds missing dimension to images and ignores scaling when converting from markdown to PDF

### ISSUE THREAD

**Issue by perusio** [jgm/pandoc#4895]
pandoc 2.2.x (I tried 3 different versions) the latest, the one in debian testing and 2.2-1. All of them add the missing dimension to scaled images.

Both 2.2 and 1.19 add the code.

```latex
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```
in the preamble, but 2.2 issues the command:

```latex
\centering
\includegraphics[width=\textwidth,height=0.5\textheight]{./tex2pdf.-23f0b3cd97092780/59e0ef44840f75b3668c1588fbd8d217fffbb988.png}
\caption{Device selection}
```
while 1.19 does:

```latex
\begin{figure}
\centering
\includegraphics[height=0.50000\textwidth]{../_assets/screenshot-select-devices.png}
\caption{Device selection}
\end{figure}
```
as you can see 2.2 adds the spurious `width=\textwidth` to the `\ìncludegraphics` options.

This is how I generate the doc.

```shell
pandoc --from markdown+latex_macros -V documentclass=relayr --pdf-engine=lualatex -V classoption=article,oneside,a4paper,berlin --filter pandoc-tablenos --filter pandoc-fignos -V date="September 2018" --highlight-style=tango --standalone  --include-in-header ../common-source/preamble.tex \
        -o pdf/analytics_user_guide.pdf \
        metadata.yaml all.md
```
```shell
pandoc --version
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.0.2
Default user data directory: /home/appa/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
Dup of #4384 - please read the discussion there.

**Comment by jgm** [comment]
Did you read the motivation for adding the `\textwidth` for the missing width dimension?
https://github.com/jgm/pandoc/commit/1193c1a505aac616d41a7b1c61c0cde07d2560d2

You shouldn't be having problems if you're using the default template.  Are you having wrong results when you create a PDF, or are you just looking at the LaTeX code and assuming it will be wrong?  If you're having bad results, can you post a minimal example to reproduce the problem, including a link to the image and the exact markdown code and pandoc command line used?

**Comment by perusio** [comment]
@yes I did. I'm checking both the LaTeX output with `--verbose`. Now the funny thing is that with 
`width=50%`it scales correctly although the output is the same.

```latex
 \includegraphics[width=0.5\textwidth,height=\textheight]{./tex2pdf.-1147636739e5a680/59e0ef44840f75b3668c1588fbd8d217fffbb988.png}
\caption{Device selection}
```
but with `height=50%`it doesn't:

```latex
\includegraphics[width=\textwidth,height=0.5\textheight]{./tex2pdf.-1147636739e5a680/fa5224a30595978985c0454e8bb85879ee5fcd47.png}
\caption{Select measurements button}
```
You can find the images and the source markdown file here: https://gist.github.com/perusio/f3e022d67d1956a7ae46647309676aa8


This is the command:

```shell
pandoc --from markdown+latex_macros -V documentclass=relayr --pdf-engine=lualatex -V classoption=article,oneside,a4paper,berlin --filter pandoc-tablenos --filter pandoc-fignos -V date="September 2018" --highlight-style=tango --standalone  --include-in-header ../common-source/preamble.tex \
        -o pdf/test_user_guide.pdf \
        metadata.yaml test.md
```
This is my `metadata.yaml`:

```yml
---
title: Analytics User Guide
author:
subtitle: 
language:
```

**Comment by perusio** [comment]
@jgm thank you for your investigation into this. I manage to locate the problem. There is some strange interaction between the geometry package and graphicx. If I add this to my class:

```latex
%% Paper size for Europe.
\DeclareOption{a4paper}{
  \PassOptionsToClass{a4paper}{memoir}
  % Margins set by the geometry package.
  \PassOptionsToPackage{top=2 cm, bottom=2 cm, left=2.5 cm, right=2.5cm}{geometry}
} %
```
it reproduces the problem. If I comment it out it doesn't. Is really strange. I guess my options are to delve into the memoir class geometry options and let go of geometry altogether. Strangely enough when it didn't added the other dimension to the `\includegraphics` it didn't appear. So is not a pandoc issue is a LaTeX package issue. Dropping `geometry` and using instead the `memoir` page geometry setting macros, if I add `\setulmarginsandblock{2cm}{2cm}{*}` it breaks the `keepaspectratio` option for the graphics. 

So I'm going to remove it as a stop gap measure for the time being.

**Comment by mb21** [comment]
But there is no problem when using the default template, or..? If so, I guess this issue can be closed?

**Comment by perusio** [comment]
@mb21 I'm using the default template. I just have my own class that changes the margins, among other things. Is the top and bottom margin that break the scaling. The problem probably comes from the way `graphicx` estimates the width when you scale the height, but not the width.

**Comment by jgm** [comment]
I think this can be closed, but if you come across any
ideas for making pandoc's output more compatible with
these sort of geometry changes, we'd very much like
to hear them.
