### ISSUE TITLE
html to epub footnote id stripped out

### ISSUE THREAD

**Issue by naeluh** [jgm/pandoc#4897]
Version:
pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Copyright (C) 2006-2018 John MacFarlane

I am running a command to generate an epub from html

```
pandoc -f html-native_divs-native_spans-raw_html -t epub html/epub.xhtml -o output.epub --epub-metadata=html/metadata.yml --template=html/template.xhtml  --standalone --css=site/css/epub.css
```

Which all is working really well. 

There is just one issue when I input the html it looks like this for footnotes

```
<sup class="footnote-ref" id="fnref-5"><a href="#fn-5">5</a></sup>
``` 

```
<ol>
<li id="fn-5">Tucker, Paul Hayes (1998). Manet’s Le Déjeuner Sur L’Herbe. Cambridge: Cambridge UP. pp. 5–14.
 <a class="footnote-return" href="#fnref-5">↩</a></li>
</ol>
```

However in the epub it looks like this 

```
<sup><a href="ch005.xhtml#fn-5">5</a></sup>
``` 

```
<ol>
    <li><span id="fn-5">Tucker, Paul Hayes (1998). Manet’s Le Déjeuner Sur L’Herbe. Cambridge: Cambridge UP. pp. 5–14. <a href="#fnref-5" class="footnote-return">↩</a></span></li>
</ol>
```

Is there a reason why the id and class are being stripped off the `<sup>` element?

Let me know if I can provide any other info.

Thanks !

**Comment by jgm** [comment]
> Is there a reason why the id and class are being stripped off the `<sup>` element?

Yes. See the fifth paragraph of the pandoc manual.
Pandoc's internal representation of Superscript
doesn't have space for attributes, so this is just
lost.

**Comment by mb21** [comment]
Basically, going from html to another html-based format with pandoc will be lossy. Maybe better use another tool for that specific use-case, sorry.

**Comment by naeluh** [comment]
Thanks for the quick response! ok sounds good !
