### ISSUE TITLE
Issues with converting from Markdown to Markdown

### ISSUE THREAD

**Issue by anishmittal2020** [jgm/pandoc#4902]
Version: **pandoc 2.2.1**

## Description

- In the following example, I am 
  - converting from Markdown to Markdown 
    - to convert inline links to references.

```bash
$ cat Simple.md
- Some text

<center>![Hi](Image/Image_18-09-14_18-28-22.png){width=500px}</center>

- Some

$ pandoc --reference-links Simple.md -o temp.md

$ cat temp.md
-   Some text

<center>
![Hi]
</center>
-   Some

  [Hi]: Image/Image_18-09-14_18-28-22.png {width="500px"}
```
## How can

- Pandoc Preserve newlines as in the original Markdown?
- Avoid generation of extra newlines by Pandoc in the output Markdown file?
- Pandoc avoid adding 2 blank spaces before the Reference Links definition? Is it necessary?

**NOTE**: Pandoc can't render Image any more, when converted to `html`

## Expected results

With rendering of Image, when converted to `html`.

```bash
$ cat temp.md
-   Some text

<center>![Hi]</center>

-   Some

[Hi]: Image/Image_18-09-14_18-28-22.png {width="500px"}
```

**Comment by mb21** [comment]
The `--wrap=preserve` option does that to some extent. But it won't work for HTML elements. So the answer is no.

Basically, having user-customizable output formatting for markdown wasn't (and isn't) one of the design goals of pandoc.

Please ask questions like this on pandoc-discuss.

**Comment by anishmittal2020** [comment]
`--wrap=preserve` has no effect, the output is as before. I am replying to this here as you mentioned it. But I will not add any more comments here as you mentioned to use pandoc-discuss.
