### ISSUE TITLE
broken link in FAQ to TeX geometry package

### ISSUE THREAD

**Issue by uvtc** [jgm/pandoc#4903]
At http://pandoc.org/faqs.html#how-do-i-change-the-margins-in-pdf-output the link to geometry no longer works. I'm not familiar with TeX's sources and packaging, but a quick search turned up https://www.ctan.org/pkg/geometry . Is that the canonical source containing the correct link to the geometry docs?

**Comment by jgm** [comment]
Yes, that should be the right link.
I'll fix it.

**Comment by uvtc** [comment]
Thanks!
