### ISSUE TITLE
[Docs] Contradictory descriptions of the `--biblatex` flag

### ISSUE THREAD

**Issue by jpeacock29** [jgm/pandoc#4904]
In the Pandoc User's Guide section "Citation rendering", `--biblatex` is described as applicable only to LaTeX output:

> Use biblatex for citations in LaTeX output.

However, in "Citations" `--biblatex` is described as applicable to both LaTeX and PDF output: 

> For LaTeX or PDF output, you can also use natbib or biblatex to render bibliography. In order to do so, specify bibliography files as outlined above, and add --natbib or --biblatex argument to pandoc invocation. 

I believe the first is correct as when I used `--biblatex` with PDF output all the citations were merely bolded and no bibliography added.

**Comment by mb21** [comment]
If you read http://pandoc.org/MANUAL.html#creating-a-pdf, you'll see that pandoc uses LaTeX by default for PDF creation.

> with PDF output all the citations were merely bolded and no bibliography added.

are you using the latest pandoc? you'd also have to tell us about your OS etc. Please ask on the pandoc-discuss mailing list unless you're quite certain that it's a bug.

**Comment by jgm** [comment]
> I believe the first is correct as when I used --biblatex with PDF output all the citations were merely bolded and no bibliography added.

That's because pandoc doesn't run bibtex or biber in generating a PDF.  So, I agree, the docs were confusing.  I've made the small change you suggested, thanks.

**Comment by jpeacock29** [comment]
@mb21 Indeed, using the latest pandoc (2.3) on OSX 10.13.6 with pdfTeX Version 3.14159265-2.6-1.40.19 (TeX Live 2018) and pandoc-citeproc 0.14.3.1. I'm not certain it's a bug as I'm not sure what the intended behavior is.
