### ISSUE TITLE
markdown_mmd and example_lists not compatible?

### ISSUE THREAD

**Issue by fncll** [jgm/pandoc#4908]
Pandoc: pandoc 2.2.3.2 Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Multimarkdown: 6 v6.4.0

Given this document (listest.md):

```
(@) Example one
(@) Example two

some text

(@) Example three
```

The following command line:

    pandoc -f markdown_mmd+fancy_lists+example_lists listest.md

Doesn't start the numbering of the third item at 3, but restarts at 1:

```
<ol class="example" type="1">
<li>Example one</li>
<li>Example two</li>
</ol>
<p>some text</p>
<ol class="example" type="1">
<li>Example three</li>
</ol>
```

Using markdown, as with the following, it works:

    pandoc -f markdown_mmd+fancy_lists+example_lists listest.md

result:

```
<ol class="example" type="1">
<li>Example one</li>
<li>Example two</li>
</ol>
<p>some text</p>
<ol start="3" class="example" type="1">
<li>Example three</li>
</ol>
```

Should the example lists work with markdown_mmd?

**Comment by jgm** [comment]
It will work if you also enable +startnum.
This shouldn't be necessary, though; I'll fix this.
