### ISSUE TITLE
pandoc.org/try/ not properly indexable by google

### ISSUE THREAD

**Issue by roberth** [jgm/pandoc#4917]
The google search result [(example, may or may not be right on your google profile)](https://www.google.com/search?q=online+html+to+markdown&ie=utf-8&oe=utf-8&client=firefox-b-ab) looks like this

-----

[Try pandoc!](#)
pandoc.org/try/
No information is available for this page.
[Learn why](https://support.google.com/webmasters/answer/7489871?hl=en)

-----

I suppose you may have a valid reason not to appear in a search like this, but even then this situation doesn't seem optimal.

**Comment by mb21** [comment]
This is explicitly disallowed by http://pandoc.org/robots.txt because we don't want that page to be DDOSed by crawlers.

If there's still a way to make some info available to google, please suggest so (or make a pull!) at https://github.com/jgm/pandoc-website Thanks!

**Comment by roberth** [comment]
You'd probably have to change server behavior to special case google here because robots.txt doesn't let you be precise enough, considering the URLs you have been using.
These are my 2 cents. I'm going to leave this to someone more familiar with the project. Thank you for considering the issue.

**Comment by jgm** [comment]
I just removed try from the robots.txt.
It should be harmless for crawlers to hit that page, because the cgi script isn't called unless the javascript on the page is evaluated.
