### ISSUE TITLE
Context PDF Engine - Undefined control sequence error

### ISSUE THREAD

**Issue by SimonCRussell** [jgm/pandoc#4918]
### Issue
Pandoc 2.3
Windows 10 64-bit

When generating a PDF using the context pdf engine Pandoc fails with the following error message:

<pre>
Error producing PDF.
tex error       > tex error on line 62 in file D:/Pandoc/tex2pdf.-fc1cc2e159e335d3/input.tex: ! Undefined control sequence
</pre>

### Command line used

pandoc --pdf-engine=context -o testimage.pdf testimage.md

### Contents of testimage.md

<pre>
# An Image #

![Caption](media/image2.png)
</pre>

### Line 62 from input.tex giving the error

<pre>
62 >>  \placefigure{Caption}{\externalfigure[.\tex2pdf.19900/216421bdf523d6ea9ec3c88400c8a25bc064a3cc.png]}
</pre>

It looks like the issue may be with the \ at the start of the filepath. 

I copied input.tex from the log file and modified the filepath to directly reference the image (the temp folder test.pdf.19900 had been deleted by pandoc)

<pre>
\placefigure{Caption}{\externalfigure[.\media/image1.png]}
</pre>

Running this directly through context gives the same error as above.

If the line is modified to change the \ at the start of the filepath to a /

<pre>
\placefigure{Caption}{\externalfigure[./media/image1.png]}
</pre>

then context doesn't error and generates the pdf with the image as expected.

It looks like the \ at the start of the filepath is confusing context.

Should the Pandoc context writer change the \ in the filepath to a / when it writes the tex file?

**Comment by jgm** [comment]
Thanks for the detailed report.  I've changed the code to convert `\` to `/` in these paths.
We already do that in the LaTeX writer.
