### ISSUE TITLE
Indented lonely math block not converted to math typesetting like rst2html.py does

### ISSUE THREAD

**Issue by rpuntaie** [jgm/pandoc#4919]
pandoc 2.2.3.2

`example.rst`: 

```

.. _`tgtmath`:

  .. math:: 
     :name:

     V = \frac{K}{r^2}


Go to `tgtmath`_.
```

```
pandoc -f rst -t html --standalone --mathml example.rst -o example.html
```

does not produce math typesetting, while this does

```
rst2html.py example.rst example.html
```

It works, if the math block is not indented or there is some other indented text before the math block.

**Comment by rpuntaie** [comment]
This might apply to all lonely indented directive blocks.

**Comment by jgm** [comment]
It wasn't about indented directives, but rather about
any indented content under an internal link target.
It should be fixed now.
