### ISSUE TITLE
Improve documentation for setting variables

### ISSUE THREAD

**Issue by paulmenzel** [jgm/pandoc#4924]
Reading the documentation I am unable to figure out, how to set variables, for example `[aspectratio][1]`

Running for example `pandoc -t beamer --variable aspectratio=169 test.md -o test.pdf` with the attached [minimal example](https://github.com/jgm/pandoc/files/2405457/test.txt) – suffix changed from md to txt for GitHub –, does not work.

[1]: https://pandoc.org/MANUAL.html#variables-for-slides

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by mb21** [comment]
What do you mean "does not work"?

Produces the correct aspect-ratio-slides for me with pandoc 2.3

**Comment by paulmenzel** [comment]
On 09/21/18 15:30, Mauro Bieg wrote:
> What do you mean "does not work"?

It is still 4:3.

> Produces the correct aspect-ratio-slides for me with pandoc 2.3

1.19.2.4 from Ubuntu 18.04 LTS is used here.

Did you use my example command?

**Comment by mb21** [comment]
yes I did.
But note that pandoc 1.19 is ancient. Get a new one: https://github.com/jgm/pandoc/releases
