### ISSUE TITLE
Generated title format problem in rst

### ISSUE THREAD

**Issue by randombenj** [jgm/pandoc#4932]
Hi all

We are generating rst files with a template engine (e.g. jinja2) the input rst file looks like the following:

```rst
{{title}}
=====

Text text text

{{subtitle}}
-----

text here
```

Sometimes the generated output can look like this:

```rst
title title title title
=====

Text text text

subititle subtitle
-----
```

When trying to generate a pdf by using `pandoc -o out.pdf test.rst` when `test.rst` contains the above input. The result looks like the following:

![problem](https://user-images.githubusercontent.com/5184499/45996718-7a5b4380-c09d-11e8-9d2f-431446acb232.png)

The title then has to be adjusted like this:

```rst
title title title title
=======================

Text text text

subititle subtitle
------------------
```

To get the desired result:
![no-issue](https://user-images.githubusercontent.com/5184499/45996818-da51ea00-c09d-11e8-8d6e-56a0d60ca41b.png)

I was using pandoc version 2.2.3.2:

```sh
$ pandoc --version
pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Default user data directory: /home/users/fassbinb/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Is this intended behaviour?
Thanks for your help!

Cheers Benj

**Comment by mb21** [comment]
> Is this intended behaviour?

Yes. From the [rst docs](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections):

> An underline/overline is a single repeated punctuation character that begins in column 1 and forms a line extending at least as far as the right edge of the title text.

So maybe make your lines longer in the template?

**Comment by randombenj** [comment]
Okay I think we will go for markdown then, because we have the same problems with tables in rst ...
Thanks for your help :beers:
