### ISSUE TITLE
slide tiltes with linebreaks no longer work with recent pandoc (beamer)

### ISSUE THREAD

**Issue by bozito** [jgm/pandoc#4936]
Slide titles with linebreaks are not producing expected result in recent pandoc.
See the attached md file and the resulting tex files obtained when running:

- `pandoc --slide-level 1  -t beamer  -f markdown linebreakregression.md.txt -o linebreakregression_1.19.2.4.tex.txt`
- ` ../pandoc-2.3/bin/pandoc --slide-level 1  -t beamer  -f markdown linebreakregression.md.txt -o linebreakregression_2.3.tex.txt`

Pandoc 1.19.4 produces the expected result:

```
\begin{frame}{Line\\
break}

\end{frame}
```
while pandoc 2.3 gives unexpected result:

```
\begin{frame}{Line\\
}
\protect\hypertarget{line}{}

break

\end{frame}
```

[linebreakregression.md.txt](https://github.com/jgm/pandoc/files/2421261/linebreakregression.md.txt)

[linebreakregression_1.19.2.4.tex.txt](https://github.com/jgm/pandoc/files/2421265/linebreakregression_1.19.2.4.tex.txt)

[linebreakregression_2.3.tex.txt](https://github.com/jgm/pandoc/files/2421266/linebreakregression_2.3.tex.txt)

**Comment by mb21** [comment]
Yes, multiline headers are no longer possible. But you can use e.g. the following:

    # Line \newline break

**Comment by jgm** [comment]
See #3730.

**Comment by bozito** [comment]
Le 26/09/2018 à 21:55, Mauro Bieg a écrit :
> Yes, multiline headers are no longer possible. But you can use e.g. the following:
>
>      # Line \newline break
>

OK, but that's kind of a bad workaround: now I get linebreaks in the 
titles of the pdf version of my slides (beamer) but not in the html 
versions (reveal.js or slidy, ...).
I think it goes a bit against pandoc amazing feature of generating a 
whole bunch of coherent documents from a single source: here, each 
document is slightly different.
And from a feature perspective, allowing precise linebreak and 
justification is quite essential to design non-ugly slides.

**Comment by mb21** [comment]
You can always write a filter, to essentially generate:

    # Line \newline <br> break
