### ISSUE TITLE
JATS writer bug: Don't include `role` attribute on `<bold>` tags

### ISSUE THREAD

**Issue by coryschires** [jgm/pandoc#4937]
## Problem
Some of our Pandoc-generated JATS documents are failing the [PubMed Central validator](https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker) with:

<img width="700" alt="45716829-b18d9a00-bb5d-11e8-8170-1ace7b03d2f5" src="https://user-images.githubusercontent.com/104563/46164835-a66cf500-c254-11e8-915d-faa89db83982.png">

And, based on my understanding of the [JATS spec for `<bold>`](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/bold.html), this validation error is accurate: `<bold>` cannot have a `role` attribute. 

## Pandoc version
I'm using the latest version of Pandoc (2.3)

## Steps to recreate
1. Run `pandoc --from markdown --to jats` to open the interactive mode
3. Paste in: `This include **some bold** text`
4. It will return `<p>This include <bold role=\"strong\">some bold</bold> text</p>`

## Desired behavior
1. Run `pandoc --from markdown --to jats` to open the interactive mode
3. Paste in: `This include **some bold** text`
4. It should return: `<p>This include <bold>some bold</bold> text</p>`

**Comment by jgm** [comment]
Thanks for the report!

**Comment by coryschires** [comment]
Thanks for the super quick fix! 

I can confirm this bug is fixed in >= 2.3.1
