### ISSUE TITLE
Out-of-memory while compiling Text.Pandoc.Readers.LaTeX @ OpenBSD 6.3 with default optimization

### ISSUE THREAD

**Issue by VaclavSynacek** [jgm/pandoc#4940]
Compiling pandoc fails due to out of memory.

Produced with pandoc versions:
* pandoc 2.3.1 downloaded with `cabal install pandoc` and later reproduced with
* git cloned 890d67bc2f1c67a2aea819cec4374cadcbcbd986 which already contains 9dac993835603a1a92136f07e80a6561b1598754 which should have fixed this issue but did not.

Both attempts run with:
* cabal-install 2.0.0.1
* ghc 8.2.2
* OpenBSD 6.3 / amd64

```
[109 of 132] Compiling Text.Pandoc.Readers.LaTeX ( src/Text/Pandoc/Readers
/LaTeX.hs, dist/build/Text/Pandoc/Readers/LaTeX.o )                       
ghc: out of memory (requested 1048576 bytes)                              
cabal: Leaving directory '.'                                              
cabal: Error: some packages failed to install:                            
pandoc-2.3.1-Lt9xSiLfz3tGCoJ1CcBlAh failed during the building phase. The 
exception was:                                                            
ExitFailure 251
```

At first I suspected that compiling pandoc might really take more that 2GB RAM (which was the size on the system on which I first tried). So I built a fresh OpenBSD system with 16GB RAM and still got the same error even though `top` was showing over 14GB free RAM at the time of this error.

**Comment by jgm** [comment]
Very strange.  We could try breaking up the LaTeX reader further into submodules; it is still bigger than any other module by quite a few lines.  But I'm puzzled why this issue has been popping up now (and not before).

**Comment by VaclavSynacek** [comment]
Very strange indeed. I just checked out version 2.2.1 and tried to compile on the same system. And surprisingly this older version fails too. Even more strange is that it fails with exactly the same number of bytes requested even though the code under compilation is different (or at least restructured into different number of modules, I don't really understand Haskell to judge how much different it really is).

```
[107 of 131] Compiling Text.Pandoc.Readers.LaTeX ( src/Text/Pandoc/Readers
/LaTeX.hs, dist/build/Text/Pandoc/Readers/LaTeX.o )                       
ghc: out of memory (requested 1048576 bytes)                              
cabal: Leaving directory '.'                                              
cabal: Error: some packages failed to install:                            
pandoc-2.2.1-8VnulyGZ20W62yy5x5bVkX failed during the building phase. The 
exception was:                                                            
ExitFailure 251
```

**Comment by VaclavSynacek** [comment]
I tried compiling more versions and here are the results - out of memory error happens since tag 2.1.3

2.1.3:

```
[106 of 130] Compiling Text.Pandoc.Readers.LaTeX ( src/Text/Pandoc/Readers
/LaTeX.hs, dist/build/Text/Pandoc/Readers/LaTeX.o )                       
ghc: out of memory (requested 1048576 bytes)                              
cabal: Leaving directory '.'                                              
cabal: Error: some packages failed to install:                            
pandoc-2.1.3-6eqSbO1bgS1Fcqj0YidmzN failed during the building phase. The 
exception was:                                                            
ExitFailure 251 
```               

2.0.6, 2.1, 2.1.1, 2.1.2:

```
src/Text/Pandoc/Readers/Odt/ContentReader.hs:523:66: error:  
    * Could not deduce (Data.Semigroup.Semigroup m)                       
        arising from a use of `<>'                                        
      from the context: Monoid e                                          
        bound by the type signature for:                                  
                   matchingElement :: forall e.                           
                                      Monoid e =>                         
                                      Namespace                           
                                      -> ElementName -> OdtReaderSafe e e 
-> ElementMatcher e                                                       
        at src/Text/Pandoc/Readers/Odt/ContentReader.hs:(516,1)-(519,35)  
      or from: (ArrowChoice a, Monoid m)                                  
        bound by the type signature for:                                  
                   asResultAccumulator :: forall (a :: * -> * -> *) m.    
                                          (ArrowChoice a, Monoid m) =>    
                                          a m m -> a m (Fallible m)       
        at src/Text/Pandoc/Readers/Odt/ContentReader.hs:522:4-80          
      Possible fix:                                                       
        add (Data.Semigroup.Semigroup m) to the context of                
          the type signature for:                                         
            asResultAccumulator :: forall (a :: * -> * -> *) m.           
                                   (ArrowChoice a, Monoid m) =>           
                                   a m m -> a m (Fallible m)              
    * In the second argument of `(>>%)', namely `(<>)'                    
      In the second argument of `($)', namely                             
        `keepingTheValue a >>% (<>)'                                      
      In the expression: liftAsSuccess $ keepingTheValue a >>% (<>)       
    |                                                                     
523 |    asResultAccumulator a = liftAsSuccess $ keepingTheValue a >>% (<>
)                                                                         
    |                                                                  ^^^
^                                                                         
cabal: Leaving directory '.'                                              
cabal: Error: some packages failed to install:                            
pandoc-2.0.6-8ICj2DxF9M35TTG8sLnyng failed during the building phase. The 
exception was:
ExitFailure 1
```
1.19.2.4:

```
data/templates/default.html: copyFile: does not exist (No such file or dir
ectory)cabal: Leaving directory '.'                                       
cabal: Error: some packages failed to install:                            
pandoc-1.19.2.4-JDpaUXqj6jbKkLgvXjb2kz failed during the final install ste
p.                                                      
```

I also tried to remove the LaTeX.hs (and the LaTeX subdirectory) and recompile to prove the problem is within this source file. But later I learned that the module is imported in 7 other modules including Text.Pandoc.Readers.HTML and Text.Pandoc.Readers.Markdown. At that point I realized this kind of surgery is unfortunately above my almost nonexistent Haskell knowledge.

On the other hand it is for sure also connected to the platform used - OpenBSD. I also tried to `cabal install pandoc` the current (2.3.1) version on Debian buster/amd64 and it finished successfully even on a system with only 4GB RAM.

So my guess is there is something unportable in LaTeX.hs that is incorrectly reported by ghc as out of memory error, but that only affects some platforms and is not related to RAM size.

Now I begin to understand why there is no OpenBSD port of pandoc. On the other hand some people succeeded in building pandoc on OpenBSD, I found extremely helpful this info that confirms successful build some time in September 2017 https://deftly.net/posts/2017-10-12-using-cabal-on-openbsd.html by @qbit .

**Comment by jgm** [comment]
Thanks for trying to pin this down.  Just to be clear,
is this what you're reporting?

- 2.1.3 fails with out of memory (exit 251)
- 2.0.6, 2.1, 2.1.1, 2.1.2 can't build because of a
  compiler error (this is hard to understand, because
  we have tested all these versions with CI and that
  ghc version -- maybe something is off in your build
  procedure?)
- versions prior to 2.0.6 build without the oom erro
  (except 1.19.2.4 which fails with a nonexistent
  template file)

I suspect that there's a problem somewhere
with your build procedure.  Are you building from
release tarballs, directly doing 'cabal install
pandoc-X.Y.Z', or what?

It would be good to try with cabal new-build,
or alternatively remove the ~/.ghc and ~/.cabal
directories and start fresh.

In any case, if the above summary is right, it
suggests that the issue is linked to additions
between 2.0.6 and 2.1.3.

Note:  I have seen ghc fail with out of memory on
Windows/appveyor -- that was what motivated my
recent split of the LaTeX reader package -- and
also on linux/travis.

**Comment by VaclavSynacek** [comment]
Hello, I am reporting the out-of-memory in 2.1.3 - 2.3.1 versions. The errors in older versions were just found when I was looking for the first version that fails on out-of-memory, but I have very little interest in following these errors in old versions further (although I believe they are real and reproducible at least on OpenBSD with the same steps as described bellow, just on older git tag versions).

My build environment and steps to reproduce are as follows:

* [hetzner.de](http://hetzner.de) VPC host, instance size CX11 or CX41 (the later to test if more RAM would fix the issue, but build still fails with out-of-memory even on CX41 instance with 16GB RAM)

* fresh install of OpenBSD 6.3/amd64 stable, directly from official iso image, default installation packages and default disk layout.

* add `wxallowed` flag in `/etc/fstab` to home partition and reboot. This is needed to disable [W^X protection](https://en.wikipedia.org/wiki/W%5EX) in binaries in /home. cabal is such a binary that does not respect W^X and if this is not disabled, some cabal builds fail with `permission denied`. Other option would be to build in /usr/local which is wxallowed by default, but on the CX11 /usr/local was to small to build pandoc in and I was too lazy to repartition.

* `doas pkg_add ghc cabal-install` install cabal and ghc from OpenBSD packages. Versions happen to be cabal-install 2.0.0.1 and ghc 8.2.2

* from non-root user's home execute the following. (The tmp remaping is needed for W^X again, so that cabal does not run our of /home partition and run anything in /tmp. Alternatively this can probably be handled by adding wxallowed in fstab to /tmp partition too.)
```
mkdir ~/cabaltmp
alias cabal='env TMPDIR=/home/user/cabaltmp/ cabal'  
git clone https://github.com/jgm/pandoc.git
cd pandoc
```


* Then for each version tested I repeated these steps:
```
git checkout tags/<THE VERSION UNDER TEST>
cabal sandbox delete
cabal sandbox init
cabal configure
cabal install --only-dependencies
cabal build
```
Originally for my [previous comment](https://github.com/jgm/pandoc/issues/4940#issuecomment-425677324) I had simpler workflow without cabal sandbox, but I rerun most of the builds and all had the same results as previously reported. Including errors in 2.1.2 which you suspected are caused by my build procedure.

---

Now the good news: I finally managed to get pandoc compiled on OpenBSD. It seems like the optimization is at fault. After modifying the above procedure as follows the build succeeds:

```
git checkout tags/2.3.1
cabal sandbox delete
cabal sandbox init
cabal configure --disable-optimization
cabal install --only-dependencies
cabal build
```

And with this one, I got a self contained binary that as far as I can tell works the same as pandoc binary in debian buster repository. So I can resume my work of moving one CI server to OpenBSD and all is reasonably fine for me now.

```
git checkout tags/2.3.1
cabal sandbox delete
cabal sandbox init
cabal configure --disable-optimization -fembed_data_files
cabal install --only-dependencies
cabal install file-embed
cabal build
```

For the sake of hunting the bug down and maybe later getting pandoc into OpenBSD ports/packages, I would still keep this issue open. On the other hand, if disabling optimizations is the intended procedure on OpenBSD, maybe you could put this in install instructions for others not to get burned. This might also *kind of fix* the issues in your windows CI, but that's a blind guess.

**Comment by jgm** [comment]
I've made a few more size reductions in the LaTeX reader.  If the problem is related to the size of that module, and I suspect it is, it's possible that the latest changes may help.

**Comment by jgm** [comment]
I've put some compilation statistics (from current HEAD) here: https://gist.github.com/jgm/b0dce067a3b7dd8bfd34a7fb9d0f01df
This allows us to compare the allocations used in various compilation phases for each module.

**Comment by jgm** [comment]
@mpickering since you've worked on ghc and also pandoc, I wonder if you have any insight into why compiling the LaTeX reader in particular takes so much memory?

**Comment by mpickering** [comment]
I can't see anything obvious from a very brief glance. I'm not sure if I will be able to investigate this further. 

The fact that code gen takes longer is probably because the simplifier produces more code. It would be useful to compare the files produced by -ddump-simpl-stats for the two modules in question.

**Comment by jgm** [comment]
@mpickering, okay, thanks for having a look!

**Comment by VaclavSynacek** [comment]
Please pardon my stupidity.
I recompiled today with cc76c5e6b4d6a7e5b57220c0cd93f8e9adf86026 . It failed again with:
```
[ 54 of 134] Compiling Text.Pandoc.Lua.Util ( src/Text/Pandoc/Lua/Util.hs, 
dist/build/Text/Pandoc/Lua/Util.o )                                        
[ 55 of 134] Compiling Text.Pandoc.Lua.StackInstances ( src/Text/Pandoc/Lua
/StackInstances.hs, dist/build/Text/Pandoc/Lua/StackInstances.o )          
ghc: out of memory (requested 1048576 bytes)     
```

Again the exact same number of bytes, but in different module. What are the odds. So I googled for that number specifically and finally found 4 years old [GHC ticket 9904](https://ghc.haskell.org/trac/ghc/ticket/9904). Turns out, that I didn't know about a very conservative memory limit set by OpenBSD based on default /etc/login.conf . After removing the limits, all went fine even with default optimizations.

So I am sorry for bothering you and am closing the issue now.

PS: it took about 2GB, which is not that catastrophic. So maybe check your CI if you are not too close to that on your windows builds.

**Comment by jgm** [comment]
Great to have that resolved!  I hope that whoever
tries to make a pandoc port for openbsd will find
this.
