### ISSUE TITLE
Aspect ratio for images in Markdown to LaTeX->PDF

### ISSUE THREAD

**Issue by uliska** [jgm/pandoc#4941]
This is (probably) a follow-up to #3239

Is it possible that this problem is also (and still) present for PDF (LaTeX) output?

```
$ pandoc -v
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.6

$ pandoc --pdf-engine=lualatex \
       -t beamer \
       --slide-level=3 \
       -o slides.pdf \
       slides.md && xdg-open slides.pdf

```

I'm including a PDF in a Markdown file and converting using `-t beamer`.  Without any sizing the PDF exceeds the slide's margins. Adding `{ width=50% }` causes the PDF to be horizontally scaled to 50% of the available width - but the height is strangely scrambled (increased!) at the same time.

```markdown
![](../media/goldberg.pdf){ width=50% }
```

PDF included "as is":
![image](https://user-images.githubusercontent.com/1812148/46276598-e2f46580-c560-11e8-9c36-8bf261c20330.png)

PDF included with `{ width=50% }` (scaling of the screenshot is identical)
![image](https://user-images.githubusercontent.com/1812148/46276549-bb050200-c560-11e8-87df-3f6db06e5841.png)

Is this a bug in Pandoc or am I doing something wrong? I must say the documentation on pandoc.org doesn't seem to be very clear in this respect.

---

Inspecting the generated .tex file (using `-o sample.tex`) reveals that the width and height parameters are converted to this (with width=50% and no height set):

```TeX
\includegraphics[width=0.5\textwidth,height=\textheight]{../media/goldberg.pdf}
```
So it seems passing `width` but no `height` causes the height to be set to `\textheight`, causing the image to be arbitrarily scaled. The same is true in the other direction if only a height is given.

Clearly if no height or width is given it should *not* be added as an option to `\includegraphics`, the resulting code should be:

```TeX
\includegraphics[width=0.5\textwidth]{../media/goldberg.pdf}
```

Incidentally: It should be clarified in the manual that a given % value refers to the textwidth and not the original image size.

**Comment by jgm** [comment]
Have you read the discussion at #4384 ?
Setting height to textheight should not cause the image to be squished, as long as the preamble contains the bit of code mentioned there (which should be in the default template):
```
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```
Do you see that in the generated tex file?
Are you perhaps using a custom template? (Maybe in `~/.pandoc/templates`?)
