### ISSUE TITLE
Implicit figure where the image is a link (feature)

### ISSUE THREAD

**Issue by quite** [jgm/pandoc#4952]
Image in nice figure-tag in html:

    ![it's](foo.jpg)

But I would like to link from my image, so I try:

    [![it's](foo.jpg)](foo_large.jpg)

But that way I lose the figure-tag, since I have something other than a single
image in my paragraph, I guess.

Is this currently doable? I'm currently considering post-processing the html
resulting from my first example here, adding the a-tag around the img-tag.

**Comment by mb21** [comment]
Not without some tricks... see https://groups.google.com/forum/#!topic/pandoc-discuss/9No_6I7DWjs

Closing this as the issue tracker is not for questions.

**Comment by jgm** [comment]
I think this could be a reasonable feature request (as a change to `implicit_figures`), though I think I might prefer just to wait for a better syntax for figures (#3177).
