### ISSUE TITLE
Imbricated tables in docx

### ISSUE THREAD

**Issue by schtroumf** [jgm/pandoc#4953]
When you ask pandoc to construct imbricated tables in docx, word says that an ambiguous cell mapping is encountered and fails to render the table. 
This error seems to be the result of a missing <w:p/>. Apparently, word requires at least one empty paragrph in each cell and pandoc doesn't add it in the cell containing the imbricated table.

It can be tried with this wiki text:
```
{| class="wikitable"
!cell1
!cell2
|-
|
{|
!cell3
!cell4
|-
|cell5
|cell6
|}
|cell7
|-
|cell8
|cell9
|}
```

```
+-------------------+-------+
| cell1             | cell2 |
+===================+=======+
| +-------+-------+ | cell7 |
| | cell3 | cell4 | |       |
| +=======+=======+ |       |
| | cell5 | cell6 | |       |
| +-------+-------+ |       |
+-------------------+-------+
| cell8             | cell9 |
+-------------------+-------+
```

The xml code produced by pandoc in document.xml is schematically this one:
```
<w:tbl>
	<w:tr>
		<w:tc>
			<w:p><w:r><w:t>cell 1</w:t></w:r></w:p>
		</w:tc>
		<w:tc>
			<w:p><w:r><w:t>cell 1</w:t></w:r></w:p>
		</w:tc>
	</w:tr>
	<w:tr>
		<w:tc>
			<w:tbl>
				<w:tr>
					<w:tc>
						<w:p><w:r><w:t>cell 3</w:t></w:r></w:p>
					</w:tc>
					<w:tc>
						<w:p><w:r><w:t>cell 4</w:t></w:r></w:p>
					</w:tc>
				</w:tr>
				<w:tr>
					<w:tc>
						<w:p><w:r><w:t>cell 5</w:t></w:r></w:p>
					</w:tc>
					<w:tc>
						<w:p><w:r><w:t>cell 6</w:t></w:r></w:p>
					</w:tc>
				</w:tr>
			</w:tbl>
		</w:tc>
		<w:tc>
			<w:p><w:r><w:t>cell 7</w:t></w:r></w:p>
		</w:tc>
	</w:tr>
	<w:tr>
		<w:tc>
			<w:p><w:r><w:t>cell 8</w:t></w:r></w:p>
		</w:tc>
		<w:tc>
			<w:p><w:r><w:t>cell 9</w:t></w:r></w:p>
		</w:tc>
	</w:tr>
</w:tbl>
```

and should be (notice the <w:p/> just between the </w:tbl> and </w:tc>)
```
<w:tbl>
	<w:tr>
		<w:tc>
			<w:p><w:r><w:t>cell 1</w:t></w:r></w:p>
		</w:tc>
		<w:tc>
			<w:p><w:r><w:t>cell 1</w:t></w:r></w:p>
		</w:tc>
	</w:tr>
	<w:tr>
		<w:tc>
			<w:tbl>
				<w:tr>
					<w:tc>
						<w:p><w:r><w:t>cell 3</w:t></w:r></w:p>
					</w:tc>
					<w:tc>
						<w:p><w:r><w:t>cell 4</w:t></w:r></w:p>
					</w:tc>
				</w:tr>
				<w:tr>
					<w:tc>
						<w:p><w:r><w:t>cell 5</w:t></w:r></w:p>
					</w:tc>
					<w:tc>
						<w:p><w:r><w:t>cell 6</w:t></w:r></w:p>
					</w:tc>
				</w:tr>
			</w:tbl>
			<w:p/>
		</w:tc>
		<w:tc>
			<w:p><w:r><w:t>cell 7</w:t></w:r></w:p>
		</w:tc>
	</w:tr>
	<w:tr>
		<w:tc>
			<w:p><w:r><w:t>cell 8</w:t></w:r></w:p>
		</w:tc>
		<w:tc>
			<w:p><w:r><w:t>cell 9</w:t></w:r></w:p>
		</w:tc>
	</w:tr>
</w:tbl>
```

**Comment by jgm** [comment]
So, to summarize:  if a table cell contains a table,
we need to emit `<w:p />` immediately after the table?

**Comment by jgm** [comment]
Is this documented in the ooxml spec?

**Comment by schtroumf** [comment]
I don't know if you must put it after or before the table. When MsWord generate a cell containing only a table, it put the ```<p/>``` after the table.

To anwser to your second question:  yes it's in ooxml spec. in [WPtableCell](http://officeopenxml.com/WPtableCell.php), we can read:

> A table cell must contain at least one block-level element, even if it is an empty <p/>

**Comment by schtroumf** [comment]
The exact french MsWord message is:
> Un mappage de cellule ambigu a été rencontré. Il peut s'agir d'un paragraphe manquant. Des éléments ```<p>``` sont nécessaires avant chaque ```</tc>```

In english, it's something like that :
> An ambiguous cell mapping was encountered. It may be a missing paragraph. ```<p>``` elements are needed before each ```</tc>```

MsWord 2007 and 2010 don't respect the ooxml spec in this case.
