### ISSUE TITLE
Prevent embedded CSS?

### ISSUE THREAD

**Issue by baskerville** [jgm/pandoc#4954]
Is there a way to stop *pandoc* from inserting *style* tags when generating ePUBs?

I have created a `~/.pandoc/epub.css` file and I'd like that (or another stylesheet passed through `-c`) to be the only stylesheet used by the generated ePUB.

**Comment by mb21** [comment]
Yes, see http://pandoc.org/epub.html#changing-the-format.
And the `style` tag is from the HTML template, see http://pandoc.org/MANUAL.html#templates – so do `pandoc -D html > ~/.pandoc/default.html`

Closing this, as questions should be asked on [pandoc-discuss](https://groups.google.com/d/forum/pandoc-discuss), not this issue tracker.
