### ISSUE TITLE
[ePUB] The classes used for the title page are too generic

### ISSUE THREAD

**Issue by baskerville** [jgm/pandoc#4955]
I think it would be good to add a *title-page* class to all the elements of the title page. `p.author` is too generic, `p.title-page.author` is better.

**Comment by mb21** [comment]
You can put a div with a class in your custom epub template, then use `.mytitlediv .author`

Closing this, as questions should be asked on [pandoc-discuss](https://groups.google.com/d/forum/pandoc-discuss), not this issue tracker.
