### ISSUE TITLE
use html comments to add extensions

### ISSUE THREAD

**Issue by legrostdg** [jgm/pandoc#4961]
https://github.com/jgm/pandoc/issues/2069 was closed, but I think that @lierdakil had a great idea: use html comments to add extensions. Something like this:

    

That would be a nice feature to have in pandoc.

**Comment by mb21** [comment]
I guess this falls under https://github.com/jgm/pandoc/issues/4627 ?

**Comment by mb21** [comment]
E.g. with [panrun](https://github.com/mb21/panrun/) you can do:

    ---
    output:
      html:
        from: 'markdown+compact_definition_lists'
    ---

    Term 1
      ~ Definition 1
    Term 2
      ~ Definition 2a
      ~ Definition 2b

**Comment by jgm** [comment]
If we did this at all, I think it would make more
sense to have a YAML metadata field:

---
extensions: +compact_definition_lists -pipe_tables
...

One possible problem with this is that parsing YAML
metadata is itself an extension.  So is parsing raw
HTML (including comments).

We'd also have to change the parser to keep extensions
in state, and possibly modify them on the fly, rather
than getting them from reader options.

**Comment by jgm** [comment]
If we did this at all, I think it would make more
sense to have a YAML metadata field:

    ---
    extensions: +compact_definition_lists -pipe_tables
    ...

One possible problem with this is that parsing YAML
metadata is itself an extension.  So is parsing raw
HTML (including comments).

We'd also have to change the parser to keep extensions
in state, and possibly modify them on the fly, rather
than getting them from reader options.

**Comment by mb21** [comment]
Closing in favour of  #4627
