### ISSUE TITLE
Markdown nested lists don't break lines when number has more than two digits

### ISSUE THREAD

**Issue by lkmorlan** [jgm/pandoc#4965]
I discovered this with a numbered list with over 100 items. This input:

```
1. test
    (a) test
    (b) test
100. test
    (a) test
    (b) test
```
Gives output arranged like this (tested when converting to PDF and DOCX):
```
1. test
    (a) test
    (b) test
2. test (a) test (b) test
```

Command: `pandoc -o test.pdf test.md`
pandoc 2.2.1 (Debian 2.2.1-2)

**Comment by jgm** [comment]
Not a bug.  See the documentation on indentation rules for block content (including nested lists) under list items:  http://pandoc.org/MANUAL.html#block-content-in-list-items

Before 2.0, pandoc used a different rule, the "four space rule," which might be more to your liking. If so, you can enable this behavior using `-f markdown+four_space_rule`.
