### ISSUE TITLE
Surprising default configuration (was: Pandoc 2.3 mistranslates nested power in LaTeX inline math from Markdown to Org)

### ISSUE THREAD

**Issue by edom** [jgm/pandoc#4969]
## Output of `pandoc --version`

```
pandoc 2.3
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.2
```

## How to reproduce

Save this in `a.md`:

```
\\( a^{b^c} \\)
```

Then run `pandoc a.md -o a.org`.

Then observe that `a.org` contains:

```
\( a^{{b}c} \)
```

## What is expected

The file `a.org` should contain:

```
\( a^{b^c} \)
```

## What I think

I think I may be inadvertently using Markdown superscripts. Replacing the `^` with `\^` causes the problem to disappear.

Alternatively, I can also use `pandoc --from=gfm-superscript` or `pandoc --from=markdown-superscript`.

**Comment by edom** [comment]
I think nothing needs to be done from Pandoc's side. Sorry for dirtying the issue tracker with this monolog.

**Comment by jgm** [comment]
If you intend to be writing LaTeX math, you should use the syntax pandoc provides for that.
```
$a^{b^c}$
```

**Comment by edom** [comment]
I see. Unfortunately, I have some hundreds of legacy Markdown files that did not follow that convention.

Disabling the `superscript` extension works for me; I happen to never used Markdown superscripts.

**Comment by jgm** [comment]
Try `pandoc -f markdown+tex_math_double_backslash` and you'll get exactly what you want. (In fact it will work better, because this will be parsed as math.)

**Comment by edom** [comment]
Thank you very much! Indeed `tex_math_double_backslash` is what I want.

Thanks a lot for going the extra mile helping an impatient newcomer!
