### ISSUE TITLE
man writer does not terminate nested formatting correctly

### ISSUE THREAD

**Issue by magicus** [jgm/pandoc#4973]
The man writes still creates incorrect output for nested formatting. :-( This was reported in #3568 which was closed as fixed, however, the fix was not complete. (This is reproduced on pandoc 2.3.)

The issue is still with \f[]. Prior to the fix of #3568, pandoc created troff code as if \f[] meant "pop" the formatting stack, but it does not. It just switches back to the previously used format. Now, \f[] is used as if it means "remove all special formatting", but that is **still** not what it does. Really, the way \f[] functions means that it is a construct that pandoc just should not use, since it does not know what the previously used formatting was.

The proper way to remove all formatting is to explicitly set the regular font, \f[R]. This was shown in the expected output given in #3568, but perhaps not stated clearly enough in the bug report.

So, let's go back to the original example. :-)

Example: 
```
$ cat man-formatting-bug.md
normal *italic **bold in the middle** only italic* normal.

normal **bold `code` more bold** normal.

normal `code` normal.

$ pandoc -s -t man man-formatting-bug.md
.\" Automatically generated by Pandoc 2.3
.\"
.TH "" "" "" "" ""
.hy
.PP
normal \f[I]italic \f[BI]bold in the middle\f[I] only italic\f[] normal.
.PP
normal \f[B]bold \f[BC]code\f[B] more bold\f[] normal.
.PP
normal \f[C]code\f[] normal.
```

Expected output:
```
.\" Automatically generated by Pandoc 2.3
.\"
.TH "" "" "" "" ""
.hy
.PP
normal \f[I]italic \f[BI]bold in the middle\f[I] only italic\f[R] normal.
.PP
normal \f[B]bold \f[BC]code\f[B] more bold\f[R] normal.
.PP
normal \f[C]code\f[R] normal.
```

The esiest way to see how the pandoc output is parsed by man is to let man convert it to html:
```
$ pandoc -s -t man  man-formatting-bug.md  | man -Thtml -l -
... snip ...
<p style="margin-left:11%; margin-top: 1em">normal
<i>italic</i> <b><i>bold in the middle</i></b> <i>only
italic</i> <b><i>normal.</i></b></p>

<p style="margin-left:11%; margin-top: 1em">normal <b>bold
code more bold normal.</b></p>
.... snip ...
```

**Comment by magicus** [comment]
It is also worth noting that pandoc generates consecutive \f[...] codes. For example, this input:

```
normal **`bold and code`** normal
```

will result in:

```
normal \f[B]\f[BC]bold\ and\ code\f[B]\f[] normal
```

While this is not technically incorrect, it's pointless and not very good style. The first \f[...] will just be overwritten by the second. A more proper formatting would look like this:

```
normal \f[BC]bold\ and\ code\f[R] normal
```

**Comment by link2xt** [comment]
@magicus As for consecutive \f[] codes, feel free to open a separate issue.

**Comment by jgm** [comment]
In addition, it needs to be `\f[CB]` rather than `\f[BC]`.
