### ISSUE TITLE
Support for ghc-8.6.1?

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#4974]
Current versions of `pandoc` don't compile with ghc 8.6.1 because of the following constraints:

- [ ] containers >=0.4.2.1 && <0.6
- [ ] haddock-library ==1.6.*

It would be great to get an updated version of `pandoc` that works with recent versions of those packages. Generally speaking, it would be nice if all dependencies would be supported in their most recent versions (see http://packdeps.haskellers.com/feed?needle=exact:pandoc), but this is a "nice to have" kind-of thing, not a "must have".

**Comment by peti** [comment]
Will you release an update to Hackage?

**Comment by jgm** [comment]
Probably there will be a new release before too long.
