### ISSUE TITLE
Generating epub does not honour css in metadata file

### ISSUE THREAD

**Issue by quite** [jgm/pandoc#4990]
I have `blue.css`:

    * { color: blue !important; }

`doc.md`:

    ---
    title: foo
    css: blue.css
    ---

Doing `pandoc -s -o test.epub doc.md` does not embed (or link to) `blue.css` from the epub. If I generate html, it gets blue indeed.

If I generate using `pandoc -s -o test.epub --css=blue.css doc.md` the my custom css does take effect, entirely replacing the default built-in epub css (https://github.com/jgm/pandoc/blob/master/data/epub.css).

This is pandoc 2.3.1.

**Comment by mb21** [comment]
Indeed, this seems to be due to https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/EPUB.hs#L355

There, the following works:

```
---
title: foo
stylesheet: blue.css
---
```
