### ISSUE TITLE
Powerpoint fenced code blocks and verbatim uses hard coded formatting

### ISSUE THREAD

**Issue by mainframed** [jgm/pandoc#4999]
I reported these two issues on the google group and was told to submit them here. 

Basically fenced code blocks ` ``` ` and verbatim ` `` ` do not match the font size of the slide reference doc. Using custom `--reference-doc` I have a theme but unfortunately the size of code blocks are hard coded to 18pt [as seen here](https://github.com/jgm/pandoc/blob/11e681edac3cbdc94af90bee8370e8aa4fddf955/src/Text/Pandoc/Writers/Powerpoint/Output.hs#L738): ` then [("sz", "1800")]`

Here's what that looks like in my presentation:

<img width="868" alt="screen shot 2018-10-21 at 9 35 12 pm" src="https://user-images.githubusercontent.com/1973519/47277923-b89f3200-d579-11e8-8b8b-5401f38af559.png">

The second issue can be found [here](https://github.com/jgm/pandoc/blob/11e681edac3cbdc94af90bee8370e8aa4fddf955/src/Text/Pandoc/Writers/Powerpoint/Output.hs#L834). This code `Just px -> [("marL", show $ 12700 * px), ("indent", "0")]` indents the code block about 1.4 inches from the start of the text area. It doesn't appear there's a way to set this distance without modifying the source as it too is hard coded.

**Comment by jeroendehaas** [comment]
@mainframed For my own work, I tried to address the issues you reported a couple of months ago. My changes are now merged. You might appreciate them. If you do get a chance to try a new version, I'd be interested in your thoughts on the new behavior.

**Comment by mb21** [comment]
So this issue can be closed?
