### ISSUE TITLE
Powerpoint Output: Verbatim/Fenced Code Block uses hard coded font size

### ISSUE THREAD

**Issue by mainframed** [jgm/pandoc#5000]
I reported this issues on the google group and was told to submit it here. 

Basically fenced code blocks ` ``` ` and verbatim ` `` ` do not match the font size of the slide reference doc. Using custom `--reference-doc` I have a theme but unfortunately the size of code blocks are hard coded to 18pt [as seen here](https://github.com/jgm/pandoc/blob/11e681edac3cbdc94af90bee8370e8aa4fddf955/src/Text/Pandoc/Writers/Powerpoint/Output.hs#L738): ` then [("sz", "1800")]`). Currently to get around this I manually change the 1800 to a size that matches my theme and recompile pandoc.

Here's what that looks like in my presentation:

<img width="868" alt="screen shot 2018-10-21 at 9 35 12 pm" src="https://user-images.githubusercontent.com/1973519/47277923-b89f3200-d579-11e8-8b8b-5401f38af559.png">

**Comment by mb21** [comment]
This seems the same issue as #4999 ?

**Comment by mainframed** [comment]
Yes, sorry I submitted this and the other issue during the github issues last night. I'll close this one.
