### ISSUE TITLE
Setext-style header (missing some =) wrongly parsed as text instead of header

### ISSUE THREAD

**Issue by timotheecour** [jgm/pandoc#5009]
not 100% sure this is a bug if a `Setext-style header` in RST file is missing some `=` , github renders it correctly as a header but pandoc doesn't, and it renders the `===` as regular text, wrapping it weirdly:
```
The Git stuff
============

```
renders as:
```
The Git stuff ============
```

pandoc /tmp/foo.rst -f rst -t markdown -o /tmp/foo.md
pandoc --version
pandoc 2.3.1

**Comment by jgm** [comment]
rst2html.py, which is the reference implementation, renders it as
```html
<p class="system-message-title">System Message: WARNING/2 (<tt class="docutils">&lt;stdin&gt;</tt>, line 2)</p>
<p>Title underline too short.</p>
<pre class="literal-block">
The Git stuff
============
</pre>
```
So I think pandoc's implementation is basically correct.

**Comment by jgm** [comment]
RST documentation says: "An underline/overline is a single repeated punctuation character that begins in column 1 and forms a line **extending at least as far as the right edge of the title text.**"
So GitHub is wrong here, not pandoc.
