### ISSUE TITLE
Remove width attribute for ordered list in ConTeXt writer

### ISSUE THREAD

**Issue by hason** [jgm/pandoc#5016]
I want to remove [width attribute](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/ConTeXt.hs#L231-L236) in ConTeXt writer. This attribute is hardcoded. Would it be possible to turn off or set value of the attribute in a lua filter?

**Comment by tarleb** [comment]
Sorry, looks like this issue got lost. I don't see why we need the `width` attribute here, but my ConTeXt experience is limited. @denismaier, can you help?

**Comment by jgm** [comment]
My guess is that this was added to deal with cases where you have big list numbers (1000 or maybe LXVII, perhaps with parentheses around them).  So if changes are contemplated, they should be tested against such cases, and also against cases where the widths of the markers change (e.g. numbers 98..102).

**Comment by denismaier** [comment]
A quick test:
```
1. asdf
2. jklö
3. qwer
4. uiop
5. yxcv
6. asdf
7. jklö
8. qwer
9. uiop
<!--
10. m,.- 
-->
```

=> no width attribute.
```
1. asdf
2. jklö
3. qwer
4. uiop
5. yxcv
6. asdf
7. jklö
8. qwer
9. uiop
10. m,.- 
```
=> widith set to 2em

**Comment by jgm** [comment]
To see the need for this, try compiling the following with context.  (This is the pandoc output for a list beginning with 99., but with the `width` attribute removed.)
```
% Enable hyperlinks
\setupinteraction
  [state=start,
  style=,
  color=,
  contrastcolor=]

% make chapter, section bookmarks visible when opening document
\placebookmarks[chapter, section, subsection, subsubsection, subsubsubsection, subsubsubsubsection][chapter, section]
\setupinteractionscreen[option=bookmark]

\setuppagenumbering[location={footer,middle}]
\setupbackend[export=yes]
\setupstructure[state=start,method=auto]

% use microtypography
\definefontfeature[default][default][script=latn, protrusion=quality, expansion=quality, itlc=yes, textitalics=yes, onum=yes, pnum=yes]
\definefontfeature[smallcaps][script=latn, protrusion=quality, expansion=quality, smcp=yes, onum=yes, pnum=yes]
\setupalign[hz,hanging]
\setupitaliccorrection[global, always]

\setupbodyfontenvironment[default][em=italic] % use italic as em, not slanted

\definefallbackfamily[mainface][rm][CMU Serif][preset=range:greek, force=yes]
\definefontfamily[mainface][rm][Latin Modern Roman]
\definefontfamily[mainface][mm][Latin Modern Math]
\definefontfamily[mainface][ss][Latin Modern Sans]
\definefontfamily[mainface][tt][Latin Modern Typewriter][features=none]
\setupbodyfont[mainface]

\setupwhitespace[medium]

\setuphead[chapter]            [style=\tfd\setupinterlinespace,header=empty]
\setuphead[section]            [style=\tfc\setupinterlinespace]
\setuphead[subsection]         [style=\tfb\setupinterlinespace]
\setuphead[subsubsection]      [style=\bf]
\setuphead[subsubsubsection]   [style=\sc]
\setuphead[subsubsubsubsection][style=\it]

\setuphead[chapter, section, subsection, subsubsection, subsubsubsection, subsubsubsubsection][number=no]

\definedescription
  [description]
  [headstyle=bold, style=normal, location=hanging, width=broad, margin=1cm, alternative=hanging]

\setupitemize[autointro]    % prevent orphan list intro
\setupitemize[indentnext=no]

\setupfloat[figure][default={here,nonumber}]
\setupfloat[table][default={here,nonumber}]

\setupxtable[frame=off]
\setupxtable[head][topframe=on,bottomframe=on]
\setupxtable[body][]
\setupxtable[foot][bottomframe=on]


\starttext

\startitemize[n,packed][start=99,stopper=.]
\item
  asdf
\item
  jklö
\item
  qwer
\item
  uiop
\item
  yxcv
\item
  asdf
\item
  jklö
\item
  qwer
\item
  uiop
\item
  m,.-
\stopitemize

\stoptext
```
I get:

<img width="109" alt="Screen Shot 2021-05-18 at 9 13 08 AM" src="https://user-images.githubusercontent.com/3044/118686889-49356180-b7b9-11eb-8b84-48e7f2acc531.png">

Case closed?  Can we close this issue?

**Comment by tarleb** [comment]
The only solution I can think of is to set `width=\itemwidth{type}{start}{end}`. If the widths must be changed, it would be possible to do so by adjusting the template. But that seems like a lot of work, so I'm in favor of closing.

**Comment by denismaier** [comment]
Wait. I bet there is a better solution. I'll see if I can figure something out, or I'll ask on the list if someone knows something. If nothing exists, maybe Hans can build something. My untested guess for now:
`\startitemize[n,fit]`

**Comment by denismaier** [comment]
Ok, tested now:

```
\startitemize[n,packed,fit][start=99,stopper=.]
```

![grafik](https://user-images.githubusercontent.com/4668198/118714810-1f188980-b823-11eb-8641-37de767c95e7.png)

```
\startitemize[n,packed,fit][start=1,stopper=.]
```

![grafik](https://user-images.githubusercontent.com/4668198/118714983-60109e00-b823-11eb-8b8b-4b5367d08f46.png)

With only 9 items:

![grafik](https://user-images.githubusercontent.com/4668198/118715094-80d8f380-b823-11eb-8b6a-51bd7882d79c.png)

I guess all we need is a bit of extra distance between the item number and the content, e.g. `\startitemize[n,packed,fit][start=99,stopper=.,distance=.05em]`:

![grafik](https://user-images.githubusercontent.com/4668198/118715616-1c6a6400-b824-11eb-9cfc-fd0c2562dda1.png)

**Comment by denismaier** [comment]
Another option: `\startitemize[n,packed,fit][start=99,stopper=.,distance=.1em,itemalign=left]`

![grafik](https://user-images.githubusercontent.com/4668198/118717398-50df1f80-b826-11eb-935f-057bb56e07eb.png)

Maybe that's to opinionated?

**Comment by jgm** [comment]
I like that pretty well.  Could we get a bit more distance between the list number and the item?  It still looks "squeezed" to me.

**Comment by tarleb** [comment]
Would it be possible, and sensible, to move the `distance` and `itemalign` settings from the `\startitemize` to a `\setupitemize` in the template?

**Comment by denismaier** [comment]
> I like that pretty well. Could we get a bit more distance between the list number and the item? It still looks "squeezed" to me.

I think `distance=.5em` gives nice results:

![grafik](https://user-images.githubusercontent.com/4668198/118722093-0496de00-b82c-11eb-9e8a-1dcf29546cba.png)

> Would it be possible, and sensible, to move the `distance` and `itemalign` settings from the `\startitemize` to a `\setupitemize` in the template?

I think we should do that. At least that would give users the opportunity to override the defaults.

**Comment by denismaier** [comment]
Now, finally with tabular figures: first we need `\definefontfeature[f:tnum][tnum=yes,pnum=no]`
then later:
`\startitemize[n,packed,fit][start=99,stopper=.,itemalign=left,distance=.5em,style={\feature[+][f:tnum]}]`

![grafik](https://user-images.githubusercontent.com/4668198/118723868-33ae4f00-b82e-11eb-9102-78c26d0e848a.png)

**Comment by denismaier** [comment]
So, how shall we proceed? I think the last option is the best.

**Comment by jgm** [comment]
I don't know what "tabular figures" means.
I like @tarleb's idea to use `\setupitemize` in the preamble, allowing these things to be customized.

**Comment by denismaier** [comment]
> I don't know what "tabular figures" means.

Compare my last two screenshots. The first uses proportional old style numbers, the second tabular figures => with tabular figures each glyph has the same width, whereas with proportional figures some glyphs are wider than others (that is especially visible with the "1" in that font.)

**Comment by denismaier** [comment]
> 
> 
> > I don't know what "tabular figures" means.
> 
> Compare my last two screenshots: The first uses proportional old style numbers, the second tabular figures => with tabular figures each glyph has the same width, whereas with proportional figures some glyphs are wider than others (that is especially visible with the "1" in that font.)

**Comment by jgm** [comment]
OK, tabular figures makes sense here.  But I think we should have all the things that don't vary per-list set up in the preamble.  Maybe someone wants to test changes to the template and do a PR?

**Comment by denismaier** [comment]
> Maybe someone wants to test changes to the template and do a PR?

Sure, I can do this.

**Comment by denismaier** [comment]
PR opened. I have added a new itemgroup for ordered lists so we can have all the settings for these lists in the preamble without interfering with unordered lists.
