### ISSUE TITLE
Image width attribute discrepancy

### ISSUE THREAD

**Issue by khalid-hussain** [jgm/pandoc#5017]
Pandoc version: 2.3.1
OS: Windows 10 1803

Expression (Pandoc Markdown): `![](file.jpg){ width=50% }`

From p. 62 of the [PDF manual](https://pandoc.org/MANUAL.pdf):
> The % unit is generally relative to some available space. For example the above example will render
to `<img href="file.jpg" style="width: 50%;" />` (HTML), `\includegraphics[width=0.5\textwidth]{file.jpg}` (LaTeX), or `\externalfigure[file.jpg][width=0.5\textwidth]` (ConTeXt).

---

This is not true (for me). Running,

```bash
echo '![](file.jpg){ width=50% }' | pandoc -t latex
```

gives me the following (LaTeX),

```latex
\includegraphics[width=0.5\textwidth,height=\textheight]{file.jpg}
```

Whereas the expected output (LaTeX) should be,

```latex
\includegraphics[width=0.5\textwidth]{file.jpg}
```

**Comment by khalid-hussain** [comment]
I think the current behavior warrants mention in the manual. What do you think?

**Comment by khalid-hussain** [comment]
Yes, I would check the manual first before posting. I checked and found it outdated and downloaded the latest just to double check.

@mb21 has a good enough suggestion I believe.

**Comment by jgm** [comment]
I think I'd rather put this on a FAQ, rather than
clutter up the already long manual.

Mohammad Khalid Hussain <notifications@github.com>
writes:

**Comment by jgm** [comment]
I've added this:
<http://pandoc.org/faqs.html#when-i-specify-an-image-width-of-50-and-convert-to-latex-pandoc-sets-the-height-to-textheight-and-the-aspect-ratio-isnt-preserved-how-can-i-prevent-this>

**Comment by mb21** [comment]
@jgm, either way, the current MANUAL contains an inaccuracy to what the output actually is. See my referenced pull...

**Comment by jgm** [comment]
Right, okay.  I merged your PR too.

**Comment by khalid-hussain** [comment]
Yes, I believe this is good.

Clutter is one thing, misinformation is another. If it still doesn't feel right, we can choose not to give the LaTeX example at all.

Thanks guys.
