### ISSUE TITLE
man reader fails on line '\&..   '

### ISSUE THREAD

**Issue by Yanpas** [jgm/pandoc#5025]
File `man3/basename.3` from [kernel.org/man-pages-4.16.tar.xz](https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/Archive/)

Parsing it produces the following:
```
Error at "source" (line 1, column 1):
unexpected MMacro "." [] "source" (line 1, column 1)
MMacro "." [] "source" (line 1, column 1)
^
```

Removing line 119, fixes it.
Line 116-121:
```
usr     	.	usr
/       	/	/
\&.       	.	.
\&..      	.	..
.TE
.RE
```

**Comment by jgm** [comment]
I see why this happens.  The Roff lexer carves the table into cells, then lex the tokens in each cell.
For a cell containing just `.`, the lexer parses this as a line beginning with `.`.

We can perhaps fix this by checking source position.

**Comment by Yanpas** [comment]
We should also differ `..` (macro with name `.` or end of macro AFAIR) from `\&..` (line containing two dots) somehow.
