### ISSUE TITLE
Roff reader fails on empty table description

### ISSUE THREAD

**Issue by Yanpas** [jgm/pandoc#5026]
Code:
```
.TS
;
lb lb
l l.
Function	Description
_
```
File `linuxmans/stdio.3:183`

**Comment by Yanpas** [comment]
```
.TS
lb2 lb2 lb2 lb2 lb1
lb l l l l l.
```
produces:
```
Error at "source" (line 696, column 3):
unexpected "2"
expecting "|", " ", "\t", lf new-line, ",", white space or "."
lb2 lb2 lb2 lb2 lb1
  ^
Failed to convert man7/mount_namespaces.7
```

**Comment by Yanpas** [comment]
From [man-pages-posix-2013-a.tar.xz](https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-posix/)/man0p/complex.h.0p:
```
Error at "source" (line 2, column 1):
unexpected MMacro "nf" [] "source" (line 2, column 1)
MMacro "nf" [] "source" (line 2, column 1)
^
Failed to convert /mnt/d/dev/mandocset/resource/man-pages-posix-2013-a/man0p//complex.h.0p
```
Suppose it fails on line 195:
```
T{
.nf
\fIcerf\fR()
\fIcerfc\fR()
\fIcexp2\fR()
T}!T{
.nf
```

**Comment by jgm** [comment]
I just fixed the empty table options bug.  The other issues should ideally have been reported separately, but we can keep them here for now.

**Comment by jgm** [comment]
I usually just recompile the whole thing.  I should probably do what you advise, but of course recompiling runs the test suite and it's good to know nothing has broken.

**Comment by jgm** [comment]
Perhaps open another issue about block-level content (e.g. nf) inside table cells?

**Comment by jgm** [comment]
We can now get through everything in the kernel.org man pages without a parse error.

**Comment by Yanpas** [comment]
> Perhaps open another issue about block-level content (e.g. nf) inside table cells?

I have tested pandoc on my archlinux on all **posix** and **linux** mans. Only one file failed:
```
Error at "input" (line 477, column 5):
unexpected "2"
expecting lf new-line, ",", white space or "."
Failed to convert man1p//stty.1p
```
From line 474
```
.TS
center tab(@) box;
cB cB | cB cB | cB cB
lf5 2 l 6 | lf5 2 l 6 | lf5 2 l.
\&^c@Value@^c@Value@^c@Value
```
Is there still a reason for opening issue for nf? Are we just silently ignore .nf macro?

**Comment by Yanpas** [comment]
BTW linting warnings
![image](https://user-images.githubusercontent.com/7345761/47609942-81d18c00-da51-11e8-90e3-c02ad0912a32.png)

**Comment by jgm** [comment]
Yan Pashkovsky <notifications@github.com> writes:
> Is there still a reason for opening issue for nf? Are we just silently ignore .nf macro?

No, I pushed a commit yesterday that handles block-level content in lists.

**Comment by jgm** [comment]
I fixed the issue with stty.1 above.
