### ISSUE TITLE
roff reader \d symbols inside table fail

### ISSUE THREAD

**Issue by Yanpas** [jgm/pandoc#5032]
Using latest master 39f026298d83316de8a64664059f75c4a5c7dc63

Testing all posix and linux files only one failed man1p//od.1p:
```

Error at "input" (line 405, column 52):
unexpected end of input
Failed to convert man1p//od.1p
```

Line since 397: 
```
.TS
center box tab(@);
cB cB | cB cB | cB cB | cB cB
l lb | l lb | l lb | l lb.
Value@Name@Value@Name@Value@Name@Value@Name
_
\e000@nul@\e001@soh@\e002@stx@\e003@etx
\e004@eot@\e005@enq@\e006@ack@\e007@bel
\e010@bs@\e011@ht@\e012@lf \fRor\fP nl\u\s-3*\s+3\d@\e013@vt
\e014@ff@\e015@cr@\e016@so@\e017@si
\e020@dle@\e021@dc1@\e022@dc2@\e023@dc3
\e024@dc4@\e025@nak@\e026@syn@\e027@etb
\e030@can@\e031@em@\e032@sub@\e033@esc
\e034@fs@\e035@gs@\e036@rs@\e037@us
\e040@sp@\e177@del
.TE
```

**Comment by jgm** [comment]
Problem is not the `\e`. It's the `\d` before the newline. Current code for unknown escape characters has them eating up the following character.

**Comment by jgm** [comment]
I'm fixing this by putting in exact instructions for the arguments each escape sequence takes (even for escapes we're ignoring).
