### ISSUE TITLE
roff lexer \9

### ISSUE THREAD

**Issue by Yanpas** [jgm/pandoc#5034]
File man7/suffixes.7 (linux)
```
Error at "input" (line 67, column 8):
Unknown escape character \9
Failed to convert man7/suffixes.7
```

Line: ` .[0-\9]+gf	TeX generic font files`
Personaly I think that's not an issue but error inside the file (according to the next lines). But should it be treated as an error or warning? 

Python e.g. by default ignores unknown escapes (`'\g' is treated as '\\g'`). I think `\9` should be treated as `9`

**Comment by Yanpas** [comment]
groff treats it as **9**:
`echo '1\93' | groff -T html`

**Comment by Yanpas** [comment]
Seems like groff requires TH macro:
`echo -e '.TH a b c\n.B g\naaa' | groff -man -T html`

**Comment by jgm** [comment]
Ah, this is from man 7 groff:

"If  a  backslash  is followed by a character that does not constitute a
 defined escape sequence, the backslash  is  silently  ignored  and  the
 character maps to itself."

I'll change accordingly.

**Comment by jgm** [comment]
Thanks for the continued thorough testing!

**Comment by Yanpas** [comment]
Yep, now with ffd3aa4f090f9add3521ce88f01b96518489d49c every man and posix files are parsed correctly! Thanks for fixes!

Now I'll compare the results with man2html of some files and I think run tests on man files of some other projects like freebsd or systemd

**Comment by Yanpas** [comment]
I've noticed that man file for fread has a table, but that table in HTML has no borders. Is it by design or an issue? Currenly pandoc-types do not support table border

**Comment by Yanpas** [comment]
I've also noticed that You removed pseudo links (`.BR feof (3),` e.g.) to other pages, that are generated by man2html (the version that is in ubuntu repositories). Shall we leave it as it is now i. e. follow the standard?

man2html html:
![image](https://user-images.githubusercontent.com/7345761/47817210-2dd2ea00-dd66-11e8-97a5-ece5dce39c7c.png)

**Comment by Yanpas** [comment]
All freebsd mans were parsed successfully. (revision 339972)
To obtain them use `svn co https://svn.freebsd.org/base/head/share/man`

**Comment by jgm** [comment]
Yan Pashkovsky <notifications@github.com> writes:

> I've noticed that man file for fread has a table, but that table in HTML has no borders. Is it by design or an issue? Currenly pandoc-types do not support table border

Correct.  That's a presentation detail.
OF course you can add CSS that puts borders around all
your tables.

**Comment by jgm** [comment]
Yan Pashkovsky <notifications@github.com> writes:

> I've also noticed that You removed pseudo links (`.BR feof (3),` e.g.) to other pages, that are generated by man2html (the version that is in ubuntu repositories). Shall we leave it as it is now i. e. follow the standard?

I was following the standard:  the groff_man 7 manual.

       .BR text
              Causes text on the same line to appear alternately in bold  face
              and roman.  The text must be on the same line as the macro call.
