### ISSUE TITLE
--ascii should probably escape control characters as well

### ISSUE THREAD

**Issue by quasicomputational** [jgm/pandoc#5042]
This shouldn't be hard to do. I'll get to it myself soon if no-one beats me to it, since I'm touching this code anyway on a related thing.

**Comment by jgm** [comment]
I'm not sure why.  Control characters are, technically, ASCII.

**Comment by quasicomputational** [comment]
The problem with control characters is that they're often invisible and hard to deal with. Making the weird corners of Unicode visible & deal-with-able is why I'd want to use `--ascii`, so for me the exact same logic applies.

**Comment by jgm** [comment]
We could consider just stripping them out before
parsing, as we do with CR and (depending on settings)
TAB.

**Comment by jgm** [comment]
One concrete proposal:  replace `crFilter` with a more general filter that strips out everything from `\0` to `\31` except `\10` (LF) and `\9` (tab).

The only one that might be controversial here is FF (form feed), which I think I recall someone using for something with pandoc...

**Comment by tarleb** [comment]
John MacFarlane writes:

> One concrete proposal: replace crFilter with a more general filter that strips out everything from
> \0 to \31 except \10 (LF) and \9 (tab).
>
> The only one that might be controversial here is FF (form feed), which I think I recall someone
> using for something with pandoc...

FF does serve nicely as a page break marker (e.g.,
https://stackoverflow.com/a/52131435)

**Comment by tarleb** [comment]
I'd prefer to keep control characters as they are, just in case other users rely on them being passed through. I don't see a clear advantage in filtering them out.
