### ISSUE TITLE
LaTeX reader: support \underline{text}

### ISSUE THREAD

**Issue by mabundis** [jgm/pandoc#5044]
I reported on pandoc-discuss that:
– I ran Pandoc ver 2.3.1 on a Mac OS X 10.11.6, converting LaTeX(.tex)  to MS Word (.docx).
– ANY use of the LaTeX command \underline{. . .} returned a omission/deletion of the entire '. . .' text, in the .docx output. Example:
     \underline{most-primitive}
     \underline{\textit{analytic} base} *(an embedded example)*
     both return ' '.
– I expected the { . . . } text to be returned underlined.
– In checking on jgm/pandoc on GitHub, I see that item #2264 reported that same issue, but that it was closed.
– Conversely, I was asked by John McFarlane to submit a change request:
> Pandoc doesn't have a native representation for 
> underlined text in its data model, but we could parse 
> this as a Span with class "underline", just as we do 
> with <u> in HTML.  Could you add an issue requesting 
> this to the bug tracker (jgm/pandoc on GitHub)? 

– I see the suggested solution given in #2264 is to run pandoc with '--parse - raw', but I've not tried this approach to see if it actually works.
– it would be nice to see \underline{ . . . } incorporated into standard pandoc functioning as this seems like a fairly standard need in working with text.

**Comment by mb21** [comment]
This is implemented as of pandoc 2.7.3

```
$ pandoc -f latex -t native 
\underline{\textit{analytic} base}

\underline{most-primitive}
^D

[Para [Span ("",["underline"],[]) [Emph [Str "analytic"],Space,Str "base"]]
,Para [Span ("",["underline"],[]) [Str "most-primitive"]]]
```
