### ISSUE TITLE
Add a "sandboxed mode" that limits IO

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5045]
A command-line option could be added that runs pandoc in a sandboxed environment.

IO would be used to fetch input files and other files mentioned on the command line, and to produce the output, but the conversion would be run in a PandocPure monad, guaranteeing that no other IO takes place.

In this mode you'd be unable to produce PDFs via LaTeX, or process include files, or read data files other than the ones baked into the binary using `embed_data_files`.

**Comment by jgm** [comment]
Filters would be ruled out, too, of course, as well as custom lua writers.
(Though maybe we could get really fancy and introduce the concept of a pure lua writer, using lua sandboxing?)

**Comment by mb21** [comment]
Sounds like you have a specific use-case in mind :-) Would be important to know the threat-model, i.e. who is this feature supposed to protect from what?

If I were running the pandoc binary on a shared server and wouldn't trust it, say, because pandoc wasn't designed with that use-case in mind, I would build a sandbox _around_ it, i.e. docker or something, not necessarily trusting myself that I've configured pandoc with the right option to behave safely (this applies to #5047 as well).

**Comment by tarleb** [comment]
> (Though maybe we could get really fancy and introduce the concept of a pure lua writer, using lua sandboxing?)

I've long wanted to try this. Let me take a stab at it.

**Comment by jgm** [comment]
> Sounds like you have a specific use-case in mind :-) Would be important to know the threat-model, i.e. who is this feature supposed to protect from what?
>
> If I were running the pandoc binary on a shared server and wouldn't trust it, say, because pandoc wasn't designed with that use-case in mind, I would build a sandbox _around_ it, i.e. docker or something, not necessarily trusting myself that I've configured pandoc with the right option to behave safely (this applies to #5047 as well).

Yes, I agree with the general advice here.  So maybe
this is a bad idea. I'd be interested in other
thoughts, though.  I don't have a particular use in
mind, but I do think that there are probably a lot of
people out there who are using pandoc naively (perhaps via
some wrapper library for a dynamic language) and who
might benefit from something like this.

Actually, what motivated me was just the fact that
we CAN give substantial guarantee (because of
PandocPure).

**Comment by tarleb** [comment]
I recently came across an application which uses LibreOffice to perform transformations to/from docx. Using pandoc instead would offer great new possibilities for that application. The current setup renders use of an additional container highly impractical, and the possibility to include arbitrary files basically rules out LaTeX, org, and rst as acceptable input formats in that setting. So yes, I do believe that this could have value.

**Comment by mb21** [comment]
Yeah, I can see a valid use-case there: running `pandoc --save-mode ...` or something when you don't trust the input file. But can we come up with a configuration that actually gives the guarantees we are after? What happens with `pandoc --save-mode --template myUnsafeTemplate -M header-includes='<script> ...`? I.e. is save-mode only save unless you override it with some option? Or does it prevent you from setting those options? Also, does it disable the `--to html-raw_html` extension?

If we don't want to do all those things, maybe it should be better called `--limit-memory` or `--limit-file-system-access` etc.

**Comment by jgm** [comment]
This is not about preventing you from creating a dangerous HTML file (there's another issue about that, #5046). It's about giving the user a guarantee about the I/O operations pandoc will perform (limiting them to the files explicitly mentioned on the command line).  Currently you don't have that guarantee.  For example, if you run pandoc on a latex file and it contains `\include{/etc/man.conf}`, a file will be read.  And a filter or custom writer might do just about anything.

Pandoc has an architecture which enables it to give a guarantee here.  If we run the conversions in PandocPure, we know they can't touch IO.  So the proposal is to provide a command-line option that turns on this guarantee.

**Comment by mb21** [comment]
Ah, so the threat model is:

- when feeding pandoc untrusted input (either from stdin or from the input file)
- protect the system running pandoc
- does nothing to make the output safe.

Options like `--filter` or `--metadata-file` wouldn't work I assume?

Sounds kind of like it could be called `--sandboxed`, but `--limit-io` is fine too (`--pure-mode` is probably only understandable for Haskellers).

**Comment by jgm** [comment]
`--metadata-file` could work, since this is a file
you're explicitly specifying on the command line.
`--filter` no, because we can't control what filters
do.

`--sandboxed` might be a good name.

**Comment by mb21** [comment]
Yes, it feels like there would be one or two other places where such an ersatz file system would come in handy, but I cannot remember where...

**Comment by tarleb** [comment]
Have you started working on this already? Asking as I'm working on
splitting Text.Pandoc.App in yet smaller parts. Most sandboxing work
would happen in that module, so it might be better to delay the cleanup
to avoid merge conflicts.

On the other hand, finishing the clean-up first might make implementing
a sandbox simpler.

**Comment by jgm** [comment]
I haven't started.  Just thinking about it.  I will
wait for you to finish before doing anything.

**Comment by mb21** [comment]
We should probably implement the `--sandboxed` option. I just discovered https://pandoc.org/MANUAL.html#a-note-on-security and one thing that isn't mentioned is that malicious input can leak information from your server (running pandoc) to the attacker. E.g. `echo '![](mysecretfile.txt)' | pandoc --self-contained`.

**Comment by mb21** [comment]
Maybe PDF production could go into the "final section that writes this out" step?

But yes, it's somewhat doubtful that you would want to run pdflatex on untrusted input... but wkhtmltopdf for example should probably fine?

**Comment by jgm** [comment]
That's the question I'm wondering about.
I did see https://www.usenix.org/system/files/login/articles/73506-checkoway.pdf
You can, for example, put `\loop\iftrue\repeat` in a tex file and pdflatex will loop forever.
This article also claims you can write arbitrary files and "escape the tex sandbox," but I wasn't sure if this was with `-no-shell-escape` enabled.

I also don't know how safe other pdf generation tools are.

So to play it safe I'd say we should not allow PDF production inside the sandbox.  The only IO allowed should be reading files *specified on the command line* and writing files *specified on the command line* (with `-o`).

**Comment by jgm** [comment]
Started a `sandboxed` branch.

**Comment by jgm** [comment]
So it's more complex than I thought.  `makePDF` doesn't just accept a the output of the writer and pass it to the PDF engine; it also does an image transformation in the temp dir, so it needs to run the writer.  Making `makePDF` a method of PandocMonad could work perhaps.  (The instance for PandocPure would just raise an error.)

**Comment by jgm** [comment]
On the output side, I had the thought that PandocMonad could have a `produceOutput :: m (IO ())` method.  Nothing stops a pure function from returning something of type `IO ()`, which can then be run in IO.

**Comment by mb21** [comment]
Couldn't we just error out if you use `--sandboxed -o foo.pdf`?

**Comment by deliciouslytyped** [comment]
With respect to sandboxing, I've recently acquired an interest in trying to sandbox Lua, though I don't know if I'll get anywhere.
This could apply to both lua and/or pandoc; has anyone considered using the chromium sandbox? https://chromium.googlesource.com/chromium/src/+/master/docs/design/sandbox.md

**Comment by jgm** [comment]
I've been thinking about this feature.  Running the converters in PandocPure is fairly limiting; it means, for example, that bibiographies and csl stylesheets referred to in the YAML metadata can't be read.  We could work around some of the issues but it would take a lot of restructuring -- we'd need an IO core outside of `runPure` that reads all the files we need, and writes the result.  And "include" directives and the like just wouldn't work at all.

Instead of running in PandocPure, I was thinking we could modify PandocIO:
Create a data structure Sandbox that encodes restrictions about which files/directories/environment variables are readable/writeable, and whether arbitrary IO operations can be done via liftIO.
Add a function runSandboxed which is like runIO but sets this data structure. (Don't export anything else that can modify the Sandbox.)
Update the PandocIO instance of PandocMonad to check the sandbox restrictions before allowing IO operations.

If we did this, we could change Text.Pandoc.App to use runSandboxed instead of runIO, when the `--sandboxed` option is specified.  We'd have to provide some way for users to pass in the restrictions: maybe a JSON file that decodes to the Sandboxed structure?  Perhaps certain things could be automatic: allowing read access to files specified on the command line, and write access to the output file.

**Comment by jgm** [comment]
Tracking some ideas in the `sandbox3` branch.
Some of these commits could be merged into master now, I think, as they improvements independently of sandbox mode.
