### ISSUE TITLE
Add an option to sanitize HTML

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5046]
It would be easy to add an option that passes generated HTML through xss-sanitize.

**Comment by mb21** [comment]
Would this happen before or after the template? If before, how to check variable contents without context? If after, wouldn't the `<script>` tags for mathjax etc. be stripped?

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

> Would this happen before or after the template? If before, how to check variable contents without context? If after, wouldn't the `<script>` tags for mathjax etc. be stripped?

Good point.  I think probably before the template.
If you're processing user input, they won't have any
way to set variables.  They can set metadata fields
via YAML metadata blocks, but this content is
processed by the HTML writer and would be handled
by any sanitizer built into it.

**Comment by mb21** [comment]
> [metadata fields are] processed by the HTML writer and would be handled by any sanitizer built into it.

But wouldn't sanitation depend on where a piece of text is placed in a template? To play devil's advocate: a user creates a template containing:

```
<header $header-type$>
</header>
```

The intended usage is:

```
header-type: 'id=myHeader class="myClass"'
```

The user naively assumes he's fine when run with `pandoc --sanitize-html`. But he didn't consider the input:

```
header-type: 'onload=alert(7)'
```

This may be a bad example, but I'm sure there are many more.

But yes, it sounds feasible to do this, as long as the user uses the default template. So we would probably at least have to emit a warning when the `--template` option is used in addition to this option.

**Comment by jgm** [comment]
@mb21 yes, good point.  I'm not sure this is so important, though, since the primary users of this feature would be people generating fragments to include in web page templates, or people using their own templates.  We could include in the documentation a note that you are responsible for the contents of any templates.

**Comment by jgm** [comment]
I'm thinking this is probably best left out of pandoc itself; this is better done with an external tool.
