### ISSUE TITLE
md -> pdf with html5 template and toc

### ISSUE THREAD

**Issue by dylnmc** [jgm/pandoc#5049]
I seem to be unable to generate a pdf that contains a table of contents from a markdown file using an html5 template. I use the toc a lot with zathura. Below are all of the things I have tried and why they do not succeed.

command | why it doesn't work
------- | :-----------------:
`pandoc -f gfm -t html --template=foo.html5 -o bar.pdf bar.md` | no **toc**
`pandoc -f gfm -o bar.pdf bar.md` | no template
`pandoc -f gfm -t html -o bar.pdf bar.md` | no template
`pandoc -f gfm --template=foo.html5 -o bar.pdf bar.md` | latex error
`pandoc -f gfm -t latex --template=foo.html5 -o bar.pdf bar.md` | (same) latex error

**Comment by jgm** [comment]
The first line is the right approach if you want to use wkhtmltopdf to generate a PDF via HTML.  If you want a table of contents, perhaps you should try using the `--table-of-contents` option?

Btw, questions like this should go to the pandoc-discuss mailing list, not here.
This tracker is for bug reports.

**Comment by dylnmc** [comment]
Solution: use `wkhtmltopdf-static` instead of just `wkhtmltopdf` and use the first **command** verbatim

---

I thought it might be a bug with pandoc, but it's just that my wkhtmltopdf didn't support PDF TOCs until I installed the -static version.

Also, --toc with pandoc is not at all what anyone would ever want (exaggeration). It generates a table of contents in the markdown—completely useless (for me). I wanted a toc in the pdf, so that I could hit <kbd>Tab</kbd> in Zathura.
