### ISSUE TITLE
HTML Reader: <tfoot> before <tbody> causes table parsing to fail

### ISSUE THREAD

**Issue by znerd** [jgm/pandoc#5079]
**Steps to reproduce:**
1. `echo '<table><tbody><tr><td>Cell</td></tr></tbody></table>' > test1.html`
2. `echo '<table><tfoot></tfoot><tbody><tr><td>Cell</td></tr></tbody></table>' > test2.html`
3. `pandoc --from html --to html test1.html`
4. `pandoc --from html --to html test2.html`

**Expected results:**
1. In step 3, the produced HTML is equivalent to the input HTML.
2. In step 4, the produced HTML is equivalent to the input HTML.

**Actual results:**
1. OK: In step 3: indeed the produced HTML is equivalent to the input HTML:
```
$ pandoc --from html --to html test1.html 
<table>
<tbody>
<tr class="odd">
<td>Cell</td>
</tr>
</tbody>
</table>
```
2. NOK: In step 4 the output is not even HTML:
```
pandoc --from html --to html test2.html 
Cell
```

**Additional information:**
- This issue may be related to #274 and/or #285.
- Pandoc version 2.4:
```
pandoc 2.4
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: /Users/ernst/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
The issue here is that pandoc expects tfoot to occur after tbody.   This can be fixed.

**Comment by jgm** [comment]
For easy reference, test2.html:
```html
<table>
<tfoot>
</tfoot>
<tbody>
<tr>
<td>Cell</td>
</tr>
</tbody>
</table>
```
