### ISSUE TITLE
Support <small> in HTML Reader and AsciiDoc Writer

### ISSUE THREAD

**Issue by znerd** [jgm/pandoc#5080]
Please support `<small>` in HTML input and translate it to `[.small]` in AsciiDoc output.

**Sample input:**
```
This <small>MUST NOT</small> be done.
```

**Sample output:**
```
This [.small]#MUST NOT# be done.
```

**Extra information:**
- AsciiDoc Reference: [“Asciidoctor User Manual”, section: “Custom Styling With Attributes”](https://asciidoctor.org/docs/user-manual/#custom-styling-with-attributes)
- HTML5 reference: [`small` tag (W3C HTML Reference)](http://w3c.github.io/html-reference/small.html)

**Comment by jgm** [comment]
We don't have a dedicated element for this.  We could consider parsing it as a native Span with class "small".  That would mean it would be treated exactly the same as `<span class="small">MUST NOT</span>`.  Note that we currently use spans with class `smallcaps` for small caps.

**Comment by znerd** [comment]
> We could consider parsing it as a native Span with class "small". That would mean it would be treated exactly the same as `<span class="small">MUST NOT</span>`.

If that produces `[.small]#MUST NOT#` in AsciiDoc, then great. Then that loop is at least closed.

**Comment by znerd** [comment]
I tried converting this HTML:
```
<span class="small">Smaller</span>
```
…to AsciiDoc using Pandoc, but it just results in:
```
Smaller
```

**Comment by znerd** [comment]
I also tried this HTML:
```
<span style="font-size:small">Smaller</span>
```
…but again, converting it to AsciiDoc just produces this:
```
Smaller
```

Is there _something_ that will generate this AsciiDoc?
```
[.small]#MUST NOT#
```

**Comment by jgm** [comment]
Ernst de Haan <notifications@github.com> writes:

> Is there _something_ that will generate this AsciiDoc?
> ```
> [.small]#MUST NOT#
> ```


Currently not.  We could consider converting spans to
this format, but only if you can have arbitrary inline
content (and not just plain text) inside the #s.

In the mean time you can use a small lua filter to
convert spans with class "small" to this syntax.

**Comment by jgm** [comment]
With the commit I just pushed, `<span class="small">hi</span>` will turn into `[.small]#hi#`.

**Comment by znerd** [comment]
> `<span class="small">hi</span>` will turn into `[.small]#hi#`.

What about an HTML `<small>` tag? Will it also be interpreted as `<span class="small">` ?

If not, should we keep this issue open until that is also covered? Or is that part of the request rejected?

(Note that I'm not too bothered if it is indeed rejected, because I would do some preprocessing of the HTML to convert any `<small>` to a `<span class="small">` myself…)

**Comment by mb21** [comment]
@znerd yes, the HTML tag is converted. See the test in the referenced commit.

**Comment by znerd** [comment]
@jgm Thanks!

I checked the referenced, but my Haskell skills are seriously lacking, I'm afraid. I find it difficult to interpret the code.

My background is in procedural languages (C, Java, etc.) and while I've done some functional programming (Clean) in the past, it's seriously rusty, and the syntax is not immediately obvious to me.
