### ISSUE TITLE
Converting from Wikidpad to Zim Wiki with tree hierarchy

### ISSUE THREAD

**Issue by jcoub** [jgm/pandoc#5082]
I'm looking to convert several wikis created with Wikidpad to Zim Wiki.

I can export from Wikidpad in a variety of formats:
HTML
xml
set of .wiki files
a multi page text file

The key aspect for me during this export would be to keep the existing hierarchy of notes. In my various export attempts, there is no easy way to re-import the data without losing the hierarchical tree.

Is there a way to achieve this with Pandoc ?

**Comment by mb21** [comment]
You'll have to write a custom script. Pandoc only deals with a single document, not with document hierarchies.

Also, please ask questions on [pandoc-discuss](https://groups.google.com/forum/?nomobile=true#!forum/pandoc-discuss) in the future. This tracker is for issues.
