### ISSUE TITLE
HTML conversion, language attribute is not translated into ISO 639-1 language code but output verbatim

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#5085]
It appears that `lang` attribute is not translated into ISO 639-1 language code as it seems to be required (https://www.w3schools.com/tags/ref_language_codes.asp) but it is used directly in output. Test:

```sh
printf "---\nlang: cs-CZ\ntitle: test\n...\n\nText." | pandoc -f markdown -t html --self-contained
```

This output (I have stripped the irrelevant parts):

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="cs-CZ" xml:lang="cs-CZ">
```

**Comment by jgm** [comment]
So the output should be what, exactly?

    lang="cs" xml:lang="cs" ?

**Comment by mb21** [comment]
As specified in the pandoc MANUAL, the markdown input is expected to be [BCP 47](https://tools.ietf.org/html/bcp47). Yes, this is passed directly through to the HTML, but HTML5 language tags are BCP 47 as well.
