### ISSUE TITLE
AsciiDoc Writer: Output language

### ISSUE THREAD

**Issue by znerd** [jgm/pandoc#5088]
Please enhance the AsciiDoc writer to output the language used in the `lang` attribute.

Sample HTML input document:
```
<!DOCTYPE html>
<html lang="nl">
<head><title>Dit is een test</title></head>
<body>Hallo wereld.</body>
</html>
```

Expected output when converting to AsciiDoc with the `--standalone` option:
```
== Dit is een test
:lang: nl

Hallo wereld
```

Actual output:
```
== Dit is een test

Hallo wereld
```

The `lang` attribute is not documented extremely well, but here are some references:
- [AsciiDoc User Guide, Appendix D: Using AsciiDoc with non-English languages](http://asciidoc.org/userguide.html#_using_asciidoc_with_non_english_languages) (on the original AsciiDoc site)
- [Asciidoctor User Manual: 75. Using Asciidoctor with Other Languages](https://asciidoctor.org/docs/user-manual/#language-support)

**Comment by jgm** [comment]
You can make it do this yourself, by customizing the asciidoc template.  See the manual under Templates.

The default template contains
```
$if(titleblock)$
= $title$
$if(author)$
$for(author)$$author$$sep$; $endfor$
$endif$
$if(date)$
$date$
$endif$
$if(keywords)$
:keywords: $for(keywords)$$keywords$$sep$, $endfor$
$endif$
$if(toc)$
:toc:
$endif$
```
so you'd just have to add to this:
```
$if(lang)$
:lang: $lang$
$endif$
```

We could consider including this in the default template.

**Comment by znerd** [comment]
@jgm Thanks for the suggestion, I will explore the option to use templates.

**Comment by znerd** [comment]
Thanks @jgm – looking forward to test the new release.
