### ISSUE TITLE
header identifiers longer than 40 characters do not work when writing docx

### ISSUE THREAD

**Issue by agusmba** [jgm/pandoc#5091]
I've been having problems with internal header auto identifiers when converting to docx.
If the section/chapter name is long, the reference link does not work (it points to the beginning of the document).

Testing it manually (without relying on the auto-identifier part which seems to work), I have narrowed it down to having reference identifiers longer than 40 characters.

See the following tests:

```
pandoc -f markdown -o broken.docx <<EOF
Start of the document

# one chapter {#one-chapter}

[Cross Reference 1](#one-chapter)

# long chapter name {#long-chapter-name-over-forty-characters-long}

[Cross Reference 2](#long-chapter-name-over-forty-characters-long)

EOF
```

Check the docx links, the first one works, the second one doesnt.

At least the internal representation seems correct:

```
pandoc -f markdown -t native <<EOF
Start of the document

# one chapter {#one-chapter}

[Cross Reference 1](#one-chapter)

# long chapter name {#long-chapter-name-over-forty-characters-long}

[Cross Reference 2](#long-chapter-name-over-forty-characters-long)

EOF
[Para [Str "Start",Space,Str "of",Space,Str "the",Space,Str "document"]
,Header 1 ("one-chapter",[],[]) [Str "one",Space,Str "chapter"]
,Para [Link ("",[],[]) [Str "Cross",Space,Str "Reference",Space,Str "1"] ("#one-chapter","")]
,Header 1 ("long-chapter-name-over-forty-characters-long",[],[]) [Str "long",Space,Str "chapter",Space,Str "name"]
,Para [Link ("",[],[]) [Str "Cross",Space,Str "Reference",Space,Str "2"] ("#long-chapter-name-over-forty-characters-long","")]]
```

Which seems to point to a problem in the docx writer pipeline (or docx format limitation)

If there isn't a problem in the writer, and this is a limitation in the docx format, it would be nice if pandoc handled this transparently at least in the case of `implicit_header_references`, so that the limit is not crossed. In the case of explicit header references like the ones in my examples above, it would also be nice to get a warning if an id-ref longer than the 40char limit is found when writing docx.

My pandoc version:

```
$ pandoc -v
pandoc.exe 2.3.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.1, skylighting 0.7.3
```

EDIT: Tested also with the latest pandoc:

```
$ pandoc -v
pandoc.exe 2.4
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
```

Thank you!

**Comment by mb21** [comment]
Maybe you could quickly try with pandoc 2.4?

**Comment by agusmba** [comment]
Sure thing.

I updated my pandoc to 2.4 and the issue still exists (I'll update the first post to reflect that).

**Comment by jgm** [comment]
It would be nice to find the place in the OOXML
documentation where this limitation is documented.

**Comment by jgm** [comment]
When I save the file with Word, and then inspect with Emacs, I see in the header:
```xml
<w:bookmarkStart w:id="1"                   
  w:name="long-chapter-name-over-forty-characters-"/>
```
So Word seems to be truncating the name.  But not in the hyperlink:
```xml
<w:hyperlink                          
  w:anchor="long-chapter-name-over-forty-characters-long">
```

**Comment by jgm** [comment]
Here is some documentation: bookmark names must be 40 characters or less and start with a letter.

https://social.msdn.microsoft.com/Forums/office/en-US/5e06f79c-ecbd-4301-a1ed-4801ee9c3858/the-restrictions-with-bookmark-name?forum=worddev

https://social.technet.microsoft.com/Forums/lync/en-US/17d3e353-5491-43a3-82b6-25eebf030385/remove-bookmark-length-limit?forum=word

**Comment by agusmba** [comment]
Thanks @jgm for digging up the docs!

Ideally pandoc should:

1.  Limit and manage internally header auto-identifiers so that
    ```
    # long chapter name over forty characters long
    
    [Cross Reference][long chapter name over forty characters long]
    ```
    works out of the box when going from md to docx (creating an id ref of 40 chars or less)
2. Warn when a user explicitly sets reference ids longer than 40 characters when converting to docx
    ```
    # long chapter name {#long chapter name over forty characters long}
    
    [Cross Reference](#long-chapter-name-over-forty-characters-long)
    ```
    would issue a warning.

Does this look sensible?

**Comment by jgm** [comment]
The docx writer won't know if the identifier was generated automatically or specified manually.
The solution is to handle all cases the same; if the identifier isn't a legal bookmark name, then we generate a legal bookmark name based on its sha1 hash.
