### ISSUE TITLE
Lua filters: Add type/tag to pandoc element metatable

### ISSUE THREAD

**Issue by vrish88** [jgm/pandoc#5092]
Hello,

Could we add the type or tag to the metatable of the pandoc elements in lua?

I'm working on several lua filters with a fair amount of complexity and I'm using LuaUnit to test out the filters as I'm going along. One of the things LuaUnit doesn't look at (for some reason) is the type of element.

The following passes but should fail:

```lua
function testSample()
    lu.assertEquals(pandoc.LineBreak(), pandoc.SoftBreak())
end
```

To make the above fail, I believe it would be an additive change from this: https://github.com/jgm/pandoc/blob/master/data/pandoc.lua#L226-L228

to: 
```lua
  function constr:new(...)
    local mTable = fn(...)
    mTable.t = tag
    return setmetatable(mTable, self.behavior)
  end
```

I'd be happy to open a PR, but wanted to make sure I was looking in the right place first.

Thanks!

**Comment by tarleb** [comment]
I assume LuaUnit uses `==` to test for equality, which means that,
currently, `pandoc.LineBreak() == pandoc.SoftBreak()`. That's not good.

I think the best way forward would be to fix the problem at its root by
adding an `__eq` metamethod to all AstElements. That method should test
types as well and contents in a way that makes `testSample` fail as
desired. The best place to add this would probably be
`create_accessor_behavior` in lines 112 ff.

**Comment by tarleb** [comment]
Equality checking is now done on the unmarshaled objects. This means you can use `assertIs` to test equality. Which leads us to another issue: `__tostring` on AST elements is not very informative. However, it should be possible to fix this via monkey-patching, so I'll leave it at this for now.

**Comment by vrish88** [comment]
@tarleb Thanks for the fast fix on this. Do you have a way to monkey patch the elements for now?

**Comment by mb21** [comment]
@vrish88 you can also try the [nightly build](https://github.com/pandoc-extras/pandoc-nightly)

**Comment by tarleb** [comment]
Pandoc 2.5 includes the fix. Let us know if it doesn't work the way you expected.

**Comment by vrish88** [comment]
@tarleb pandoc 2.5 works as expected, thank you. However, above (https://github.com/jgm/pandoc/issues/5092#issuecomment-440039619) you had mentioned that the Lua elements could be monkey patched to have the `__tostring` include the type. How might someone go about this? I'm still not too fluent in lua to know how to do that.

**Comment by tarleb** [comment]
Try putting the following at the beginning of your test filters:

``` lua
local lu = require 'luaunit'
for k, v in pairs(pandoc) do
  if type(v) == 'table' and v.behavior then
    v.behavior.__tostring = function(x)
      local content = x.c
      return x.tag .. (content and ':' .. lu.prettystr(x.c) or '')
    end
  end
end
```

Testing `lu.assertIs(pandoc.LineBreak(), pandoc.SoftBreak())` should now give you

    Expected: SoftBreak
    Received: LineBreak
