### ISSUE TITLE
HTML Reader: colspan attribute causes table parsing error

### ISSUE THREAD

**Issue by znerd** [jgm/pandoc#5096]
**Steps to reproduce:**
1. Have an HTML file with a `<table>` that does not contain a cell with a `colspan` attribute. E.g.:
```
<table><tr><td>Hello world!</td></tr></table>
```
2. Run `pandoc` to convert the HTML to AsciiDoc format.
3. Then, add a `colspan=2` on any of the cells in the table. E.g.:
```
<table><tr><td colspan="2">Hello world!</td></tr></table>
```
4. Rerun `pandoc`.

**Expected result:**
1. In step 2, an AsciiDoc table is produced that represents the HTML table.
2. In step 4, an AsciiDoc table is produced that represents the HTML table.

**Actual result:**
1. OK: In step 2, indeed an AsciiDoc table is produced:
```
[cols="",]
|============
|Hello world!
|============
```
2. NOK: In step 4, the table is gone, only the table cell contents are printed:
```
Hello world!
```

**Additional information:**
- Pandoc version 2.4:
```
pandoc 2.4
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: /Users/ernst/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment]
We should really do https://github.com/jgm/pandoc/issues/1024...

**Comment by znerd** [comment]
@mb21 That would be great, as it could offer full colspan/rowspan support also for AsciiDoc.

However, the scope of my bug fix request is merely to make sure a table is still being output. That's perhaps the low-hanging fruit. If the `colspan`/`rowspan` attributes are ignored, then this issue may be fixed already.

**Comment by jgm** [comment]
Ignoring the colspan attribute would mean that we get
a table, but an incorrect one.  I don't see that as a
clear improvement.

Note that with `--verbose` enabled, you get some
feedback about what is being skipped.

Note also that if you enable `raw_html`, you can get
something that will work well for some output formats
(html, markdown).

The best way forward is to get colspan support for
pandoc -- that's probably the highest priority
large-scale change at the moment.

**Comment by znerd** [comment]
> Ignoring the colspan attribute would mean that we get
> a table, but an incorrect one.  I don't see that as a
> clear improvement.

For me it would be an important improvement. I don't expect Pandoc to be perfect, but I do expect it to be a helpful tool, which may require some manual follow-up to perfect things.

I'm exporting large HTML pages to AsciiDoc, some containing tables with dozens of rows. If there's just a single `colspan` in there, due to this bug I'm not getting any value out of Pandoc for such tables. I'd rather have to make some small corrections rather than having to rebuild the whole table.

My current workaround is to preprocess the HTML and remove the `colspan` and `rowspan` attributes. Then I'm getting a much better result, even though it's arguably a half-product.

**Comment by jgm** [comment]
I see how changing the behavior would improve things
for your purposes, but it's also important to consider
purposes for which it would make things worse.

For example, if you're converting HTML to Markdown,
you'll be better served by the current behavior
(with html+raw_html) which will lead to an HTML table,
which is legal in Markdown.

So, there's a danger that in changing this we'd break
workflows that work for other people.

**Comment by mb21** [comment]
Closing in favour of #1024 then...

**Comment by henribru** [comment]
@jgm Would it be possible to automatically fall back to HTML tables when encountering a colspan insted of having to specify this explicitly with `raw_html`?

**Comment by jgm** [comment]
henribru <notifications@github.com> writes:

> @jgm Would it be possible to automatically fall back to HTML tables when encountering a colspan insted of having to specify this explicitly with `raw_html`?

It would be possible, of course, but not desirable.
If `raw_html` is disabled, it means "don't parse
anything as raw HTML."

**Comment by henribru** [comment]
Would that be so different from how currently if you have a block inside a table cell, it automatically falls back to HTML?

**Comment by jgm** [comment]
henribru <notifications@github.com> writes:

> Would that be so different from how currently if you have a block inside a table cell, it automatically falls back to HTML?

You've got to distinguish between readers and writers.

The markdown writer will fall back to HTML for Table
elements when no other format works, but only if
+raw_html is enabled (which it is by default for
markdown).

Here we're talking about the HTML reader, and the
question is whether to parse something as a
RawBlock.
