### ISSUE TITLE
meta elements (except cover) not supported in metadata.xml

### ISSUE THREAD

**Issue by jeffmcneill** [jgm/pandoc#5098]
It appears that meta elements (except for  the cover) do not appear to be supported in metadata.xml. See: #269 similar issue.

Specifically, I  am trying to add the popular calibre:series and calibre:series_index  tags:   These are not pulled into the content.opf file when generating an epub. Is there a different process I should be using to include these meta tags (YAML file or something else)?

Pandoc version: 1.17.2~dfsg-3

Meta tags included in metadata.xml, which do not appear in content.opf:

    <meta name="calibre:series" content="Classics on War and Politics"/>
    <meta name="calibre:series_index" content="2.0"/>

**Comment by jgm** [comment]
As the documentation for `--epub-metadata` says, "The file should contain a series of Dublin Core elements" (dc: namespace).  Other elements, including things in a `calibre` namespace, are ignored.

**Comment by jgm** [comment]
OK, looking at https://www.eboundcanada.org/Resources/whats-in-an-epub-the-opf-file/ I see that `meta` elements are sometimes included in content.opf.  I didn't know this.  It shouldn't be too hard to modify pandoc to include them too.  Note that you're using an ancient version of pandoc.

**Comment by jgm** [comment]
I misremembered. We actually parse the metadata into a structured EPUBMetadata type, which defines the metadata that get put in content.opf.  We could probably address this by adding a field for generic custom metadata like this.

**Comment by jeffmcneill** [comment]
I really appreciate the speedy responses and fix. I'm a big fan of your software. Is there a way to incorporate these latest changes into the 2.4 release? I've tried various ways of compiling from source but no joy. I can of course wait until the next release. I'm on Debian (and I have updated to the most recent Github release, thanks for pointing that out).

**Comment by mb21** [comment]
@jeffmcneill you can try the [unofficial nightly builds](https://github.com/pandoc-extras/pandoc-nightly).

**Comment by jeffmcneill** [comment]
@mb21 nightly worked a charm :)

**Comment by jeffmcneill** [comment]
I'm trying to put all the metadata in a YAML header instead of a metadata.xml file. This seems to work for everything except for the Calibre meta tags as mentioned above in this original issue. Is there any way to get these kinds of tags into the YAML header of a markdown file? Note that I generate PDF and Epub from this file.

~~~~
<meta name="calibre:series" content="Classics on War and Politics"/>
<meta name="calibre:series_index" content="2.0"/>
~~~~

**Comment by mb21** [comment]
Can you post the YAML you tried?

**Comment by jgm** [comment]
Try
```
---
calibre:
   series: Classics on War and Policitics
```

**Comment by jeffmcneill** [comment]
Works for me, thanks!

~~~
calibre: 
  series: "Children's Classics" 
  series_index: "1.0" 
~~~

**Comment by YannKervran** [comment]
Sorry to make this thread alive after a long time, but I wanted to check I have not missed something before making a possible Issue message.

Following the instructions here, I have included in the YAML preamble of my markdown text 
```
---
schema:
   accessMode: textual
---
```
in the hope I would get 
`<meta property="schema:accessMode">textual</meta>`
in the resulting content.opf in my epub file, but it seems it doesn’t work.

Is there something I have misunderstood ?

**Comment by jgm** [comment]
The manual contains a list of the fields that are recognized in epub metadata:
https://pandoc.org/MANUAL.html#epub-metadata

**Comment by YannKervran** [comment]
Thank you very much for your answer (and this marvelous engine)
And yes, I have seen this part in the Documentation, but as the calibre fields are not specified, I was wondering why it accepts it and not mine. (as I am not native English speaker I can miss something).

**Comment by davidlday** [comment]
> The manual contains a list of the fields that are recognized in epub metadata: https://pandoc.org/MANUAL.html#epub-metadata

@jgm Unless I missed something, I don't think the manual does contain them all. I see in the code [epubCalibreFields](https://github.com/jgm/pandoc/blob/021cdb543b00995f86eefd5d84314d9e1f5abf82/src/Text/Pandoc/Writers/EPUB.hs#L97) but I don't see any mention of calibre fields in the manual, as @YannKervran pointed out. I potentially have a need for the accessibility metadata as well, and at first read this thread made me think I could just add them and have them get picked up, since that's what appears to happen with calibre fields. It's not, though, correct? Would the accessibility fields  need coded in as well?

Just trying to confirm before I start looking at putting a PR together. Thank you!

**Comment by jgm** [comment]
@davidlday yes, it needs to be coded in ... we want to make sure that we don't generate invalid EPUBs, so all the metadata must be representable in the EPUBMetadata record.
(Also, it wouldn't hurt to update the manual.)
The clauses at line 259 and around 981 would also need to be updated (this is really ugly code anyway and something more elegant could be done).
