### ISSUE TITLE
HTML Reader: Link inside <code> not picked up

### ISSUE THREAD

**Issue by znerd** [jgm/pandoc#5101]
**Prerequisites:**
Have this file `succeeds.html`:
```
<a href="https://duckduckgo.com/"><code>mindcurv-docs</code></a>
```

And this file `fails.html`:
```
<code><a href="https://duckduckgo.com/">mindcurv-docs</a></code>
```

**Steps to reproduce:**
1. `pandoc -f html -t asciidoc succeeds.html`
2. `pandoc -f html -t asciidoc fails.html`

**Expected output:**
1. In step 1:
```
https://duckduckgo.com/[`mindcurv-docs`]
```
2. In step 2 the same:
```
https://duckduckgo.com/[`mindcurv-docs`]
```

**Actual output:**
1. OK: In step 1:
```
https://duckduckgo.com/[`mindcurv-docs`]
```
2. NOK: In step 2 the link is missing:
```
`mindcurv-docs`
```

**Additional information:**
```
$ pandoc --version
pandoc 2.4
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: /Users/ernst/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
Pandoc's data model for code just contains a raw string, so it doesn't allow for links inside code.  (Just as you can't have emphasis inside code, etc.)

Indeed, in Markdown you can't have a link inside code.  You'd have to rewrite this to code inside a link.

**Comment by znerd** [comment]
@jgm OK, thanks for the elaboration. I worked around it with a preprocessor that indeed puts the link outside the `<code>` tag, per your suggestion.
