### ISSUE TITLE
Feature Request: suport for `\inputminted` in LaTeX reader

### ISSUE THREAD

**Issue by joeydumont** [jgm/pandoc#5103]
I use minted to highlight code listings in LaTeX. When using pandoc to convert this to other formats, minted listings that are added with `\inputminted{<language>}{<path_to_file>}` are not in the final output.

It is feasible to add support for `\inputminted`?

**Comment by jgm** [comment]
It should be possible.  Am I right that this just includes the contents of the file in a code block highlighted as the specified language?

**Comment by joeydumont** [comment]
Yes, this is correct.
