### ISSUE TITLE
Comments getting lost with Docx writer

### ISSUE THREAD

**Issue by shawes** [jgm/pandoc#5106]
When I convert a word document using the reader to markdown, it puts in the comments with the text.

Using 
`pandoc --track-changes=all test-comment.docx -o test-comment.md`

The markdown apeears as:
`This is a new [My Comment]{.comment-start id="0" author="Steve" date="2018-11-28T10:12:00Z"}comment.[]{.comment-end id="0"}`

However, when I convert back to the docx leaving the comment there, 

Using 
`pandoc test-comment.md -o new-document.docx`

The comment is missing and instead [My Comment] is written as text., e.g. "This is a new [My Comment] comment." Is this expected behaviour or should it be writing the comment using the docx writer?

I am using Pandoc 2.4 and Word 16.19.

**Comment by jgm** [comment]
@jkr might be able to comment on this.

**Comment by shawes** [comment]
I downgraded my local version of pandoc to 2.3 and this issue goes away. Seems a change in the 2.4 release broke the way the comments are being handled in the docx writer - it stops writing the comments.xml for docx for some reason.

**Comment by jgm** [comment]
Odd, I don't see anything in the changelog for 2.4 that would relate to this.

**Comment by agusmba** [comment]
I tested this with pandoc 2.4+ (nightly before 2.5) and it seems to work (Win 7 Ent. box, Word 2013):

```
$ pandoc -f markdown -t native <<EOF
> This is a new [My Comment]{.comment-start id="0" author="Steve" date="2018-11-28T10:12:00Z"}comment.[]{.comment-end id="0"}
> EOF
[Para [Str "This",Space,Str "is",Space,Str "a",Space,Str "new",Space,Span ("0",["comment-start"],[("author","Steve"),("date","2018-11-28T10:12:00Z")]) [Str "My",Space,Str "Comment"],Str "comment.",Span ("0",["comment-end"],[]) []]]
```

Generating the docx with:

```
$ pandoc -f markdown -o test-5106.docx <<EOF
> This is a new [My Comment]{.comment-start id="0" author="Steve" date="2018-11-28T10:12:00Z"}comment.[]{.comment-end id="0"}
> EOF
```
![image](https://user-images.githubusercontent.com/3104020/49362261-a4089a80-f6de-11e8-984c-7f8df9d2338e.png)

See the attached file:
[test-5106.docx](https://github.com/jgm/pandoc/files/2638617/test-5106.docx)

I'll upgrade to 2.5 and retest (I'll update this post when I do)

**Comment by shawes** [comment]
Yes, it seems to be some configuration issue on my side. I can open the word document @agusmba  generated and I the comment is working fine.

However, when I generate word documents in pandoc version 2.3, 2.4, and 2.5, using the command used above:

`$ pandoc -f markdown -o test-5106.docx <<EOF
> This is a new [My Comment]{.comment-start id="0" author="Steve" date="2018-11-28T10:12:00Z"}comment.[]{.comment-end id="0"}
> EOF`

I can only seem to get comments working properly for pandoc 2.3 (test-pandoc23.docx). When I generate the native code it is all exactly the same. 

[test-pandoc23.docx](https://github.com/jgm/pandoc/files/2651487/test-pandoc23.docx)
[test-pandoc24.docx](https://github.com/jgm/pandoc/files/2651489/test-pandoc24.docx)
[test-pandoc25.docx](https://github.com/jgm/pandoc/files/2651491/test-pandoc25.docx)

So I am at a bit of a loss, seems like it is something to do with my configuration. I'm using OSX Mojave (v10.14.1) with Word for Mac 2018 v16.19.

**Comment by shawes** [comment]
I uninstalled all versions of pandoc and reinstalled it and now it appears to be working for me fine, so there was something messed up with my configuration (perhaps an older version of pandoc lurking on my path somewhere). Therefore this is not an issue.
