### ISSUE TITLE
DokuWiki writer: unnecessary HTML for mixed lists

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#5107]
DokuWiki writer unnecessarily uses HTML to render mixed inner list:
```
$ pandoc -f muse -t dokuwiki
 - foo
   1. bar
   - baz
^D
<HTML><ul></HTML>
<HTML><li></HTML><HTML><p></HTML>foo<HTML></p></HTML>
<HTML><ol style="list-style-type: decimal;"></HTML>
<HTML><li></HTML><HTML><p></HTML>bar<HTML></p></HTML><HTML></li></HTML><HTML></ol></HTML>

<HTML><ul></HTML>
<HTML><li></HTML><HTML><p></HTML>baz<HTML></p></HTML><HTML></li></HTML><HTML></ul></HTML>
<HTML></li></HTML><HTML></ul></HTML>
```

Instead, the output should be (you can test it on https://www.opensourcecms.com/dokuwiki/, it works)
```
  * foo
    - bar
    * baz
```

Note that for non-mixed list, the result is correct:
```
$ pandoc -f muse -t dokuwiki
 - foo
   1. bar
   2. baz
^D
  * foo
    - bar
    - baz
```

**Comment by IceWreck** [comment]
Not only this, but I've seen multiple errors while converting HTML -> Dokuwiki, especially when the html contains lists, code and other monospaced text.

The solution I've come up with is to run the text through a post-processing script **after running it through pandoc html -> dokuwiki**

Essentially we gotta replace the following stuff after processing the text through pandoc.

Format: ("toBeReplaced", "replacementText")

- ("    *" , "  *")
- ("<HTML><ul></HTML>" , "")
- ("<HTML></ul></HTML>" , "")
- ("<HTML></li></HTML>" , "")
- ("<HTML><li></HTML>" , "  * ")
- ("<p>", "")
- ("</p>", "")
- ("%%", "")
