### ISSUE TITLE
Chrome warns about Pandoc 2.5 for macOS pkg file

### ISSUE THREAD

**Issue by znerd** [jgm/pandoc#5113]
**Steps to reproduce:**
1. Use Chrome latest stable on macOS (I used 70.0.3538.110 on macOS 10.14.1)
2. Visit https://github.com/jgm/pandoc/releases
3. Download Pandoc 2.5 release for macOS (pkg file)

**Expected results:**
1. Chrome downloads the file.
2. Chrome does not warn about the file.

**Actual results:**
1. OK: Chrome indeed downloads the file.
2. NOK: Chrome does warn about the file:
![screenshot 2018-11-30 15 06 53](https://user-images.githubusercontent.com/117866/49293966-e4cf9c00-f4b1-11e8-9f66-5f9ba0b155cf.png)

**Comment by mb21** [comment]
Uh, what about older versions? Me might put the pkg in a .zip file...

some context: https://blog.chromium.org/2012/01/all-about-safe-browsing.html

**Comment by jgm** [comment]
I have downloaded the package from github releases and verified that it exactly matches the package I created and uploaded.  So, no tampering has occurred.  The package also has been verified to install successfully.

**Comment by Guilz** [comment]
This also happens with Firefox 63.0.3 on macOS 10.14.1.

<img width="489" alt="screen shot 2018-11-30 at 15 09 19" src="https://user-images.githubusercontent.com/9656546/49317528-1d6f7580-f4b2-11e8-8f30-7235919d0575.png">

<img width="489" alt="screen shot 2018-11-30 at 15 09 40" src="https://user-images.githubusercontent.com/9656546/49317535-24968380-f4b2-11e8-9d45-af35f25d27f0.png">

The zip file doesn't raise this red flag.

**Comment by jgm** [comment]
Very strange.  I would love to get to the bottom of
this.  Does Firefox give any information about how
they make this determination, e.g. if you click
on the arrow?

It would also be helpful for those with virus scanning
software to run this file through it to see if we get
a (false) positive.

**Comment by znerd** [comment]
I wonder why the ZIP does not trigger the problem? Does it contain the same contents as the PKG file? If not, then what's different?

Or is the ZIP not scanned, but the PKG file is?

**Comment by jgm** [comment]
@Guilz I just tried with firefox 63.0.3 on macOS 10.13.6 and it didn't give me the warning.

**Comment by mb21** [comment]
Firefox [appears](https://blog.mozilla.org/security/2016/08/01/enhancing-download-protection-in-firefox/) to be using Google's service to determine whether a URL is blacklisted...

btw. for me, the download works fine on both Chrome 70.0.3538.110 and Firefox 63.0.3 on macOS 10.14.1. It might depend on on the Google service's caches (which might be different in different countries/continents).

**Comment by znerd** [comment]
I performed a scan using ESET Endpoint Security, detection engine 18472 (20181201).

Results: no issues found:

<img width="1022" alt="screenshot 2018-12-01 11 06 25" src="https://user-images.githubusercontent.com/117866/49326899-54e52d00-f559-11e8-97e2-1614b1c14ec3.png">

**Comment by znerd** [comment]
I just tried on a different computer (iMac) with the same versions of macOS and Chrome (macOS 10.14.1, Chrome 70.0.3538.110) and now I'm no longer getting the warning:
![screenshot 2018-12-01 11 39 16](https://user-images.githubusercontent.com/117866/49327153-be673a80-f55d-11e8-85ea-77063f051196.png)

Let me try it again on the original computer (MBP) and if it's no longer an issue there, then my conclusion is that it's _probably_ a temporary glitch in Google's online services.

**Comment by znerd** [comment]
It's fixed on the MBP on which I encountered the issue in the first place.

On the left you see today's download attempt (OK) and on the right is still yesterday's download attempt (NOK):
<img width="614" alt="screenshot 2018-12-01 11 42 55" src="https://user-images.githubusercontent.com/117866/49327196-6f6dd500-f55e-11e8-80f2-0788c8120908.png">

Marking as closed…

**Comment by znerd** [comment]
One more thing: the file had not changed between the first time I downloaded it and the second time. So it really was a quirk.

**Comment by jgm** [comment]
I suspect that Google's algorithm may have a bias
against new uploads, so that just waiting a bit can
make a difference.
