### ISSUE TITLE
Provide a way to specify caption position in LaTeX output

### ISSUE THREAD

**Issue by stfl** [jgm/pandoc#5116]
version 2.2.1 or 2.1.3 (< this one gets installed when installing pandoc-citeproc from cabal)

I am converting markdown > latex > pdf (pdflatex)
The caption for tables always end up above the table regardless if I put the `Table: label` above or below the markdown table.

the latex looks like this:

```
\begin{longtable}[]{@{}rl@{}}
\caption{label}\tabularnewline
\toprule
...
```

It also does not change when adding

    \usepackage[tableposition=bottom]{caption}

to the template.

It would be very nice to have this as an option or if the markdown location reflects the location at the output.

**Comment by jgm** [comment]
Although the markdown syntax allows you to put the table above or below, this location isn't represented in the Pandoc AST, and it will be ignored by all output formats.  There isn't currently any good way to change this.  I believe the `caption` package won't affect it because longtable isn't a genuine float environment.

**Comment by stfl** [comment]
Thank you for the clarification. I hope there will be an option at some point.

**Comment by jgm** [comment]
If you want, you could reopen this as an enhancement request.

**Comment by stfl** [comment]
Yes. That's a good point. I am reopening this one then, or should I open a new one?

**Comment by stfl** [comment]
Thank you for updating the title. Not possible from Android.

**Comment by michael-hillmann** [comment]
Is there any known workaround to place a table caption below the table?

**Comment by michael-hillmann** [comment]
We should correct the [official manual](https://pandoc.org/MANUAL.html#pandocs-markdown), which is currently:

Extension: table_captions
A caption may optionally be provided with all 4 kinds of tables (as illustrated in the examples below). A caption is a paragraph beginning with the string Table: (or just :), which will be stripped off. **It may appear either before or after the table.**

Proposal: removing the marked sentence.

**Comment by jgm** [comment]
The sentence is okay. The caption may indeed appear either before or after in the source.  It's just that this doesn't affect its position in the output.

**Comment by jgm** [comment]
My view is that the caption position should be determined globally; so it doesn't make sense to store it in the AST.  Perhaps we could make some writers sensitive to a `caption-position` metadata option (or variable) that would influence this.  Maybe something like:
```
table-captions: above
figure-captions: below
```

**Comment by jpcirrus** [comment]
This has become more of an issue as the APA Style Guide 7th edition, now requires figure captions to be above the figure, at it does for tables.

**Comment by jgm** [comment]
I've added this to a "don't forget this" milestone -- not actually going to be in the next release, though.
