### ISSUE TITLE
Markdown writer incorrect output of a figure with attributes

### ISSUE THREAD

**Issue by cprecioso** [jgm/pandoc#5121]
When putting an image on its own paragraph in order to make it a figure _and_ appending an attribute to it, the outputted markdown contains an HTML block with the figure, but the following block is appended in the same line, instead of being separated by newlines. (It works if the image doesn't have additional attributes)

[Repro on pandoc 2.5](http://pandoc.org/try/?text=%23+Header+1%0A%0A!%5BMy+caption%5D(.%2Fmy-figure.jpg)%7Bwidth%3D500px%7D%0A%0A%23%23+Header+2%0A&from=markdown&to=markdown_mmd)

I tried all the markdown variants, and only happens with `markdown_mmd` and `markdown_strict` (although the rest of markdowns just lose the figure and output a regular image). I checked the JSON format output and it seems the AST is correct, so I think it's an issue of the writer.

Because of this issue, the next block [will not be parsed correctly in most markdown variants](
https://johnmacfarlane.net/babelmark2/?normalize=1&text=Header+1%0A%3D%3D%3D%3D%3D%3D%3D%3D%0A%0A%3Cfigure%3E%0A%3Cimg+src%3D%22.%2Fmy-figure.jpg%22+alt%3D%22My+caption%22+width%3D%22500%22+%2F%3E%3Cfigcaption%3EMy+caption%3C%2Ffigcaption%3E%0A%3C%2Ffigure%3EHeader+2%0A--------%0A).

In what I think is related, if the figure caption contains a footnote, it will be rendered just under the figure, not joined with the rest of the footnotes in the document. [(Repro case)](
http://pandoc.org/try/?text=%23+Header+1%0A%0A!%5BMy+caption+%5E%5Bwith+a+footnote%5D%5D(.%2Fmy-figure.jpg)%7Bwidth%3D500px%7D%0A%0A%23+Header+2%5E%5Bthis+is+how+footnotes+should+be+outputted%5D%0A&from=markdown&to=markdown_strict). If it's not part of the same issue, tell me so and I will open a separate issue.

**Comment by jgm** [comment]
The footnote issue is separate and deserves a separate issue. Since `markdown_strict` doesn't have the "implicit figures" extension, we render figures in it using raw HTML.  (If you don't want figures, turn off the `implicit_figures` extension in your source format.)

If the figure contains a footnote, it gets rendered with the figure by the HTML writer. I'm honestly not sure how to fix this.  One could remove the note from the figure caption before rendering, but then where do you add it back again?

**Comment by cprecioso** [comment]
Yes, I understand that it writes HTML into the markdown, and that's to be expected, that's not the issue. I'm trying to report a bug about how this HTML is mixing with the markdown. Maybe I haven't been clear or I'm not understanding you 😅. I think this issue deserves to be reopened, I'll try to rephrase in case I've not been straightforward when reporting.

What I mean is when feeding this markdown (`-f markdown`):

```md
# Header 1

![My caption](./my-figure.jpg){width=500px}

## Header 2
```

`-t markdown_strict` and `-t markdown_mmd` both output:

```md
Header 1
========

<figure>
<img src="./my-figure.jpg" alt="My caption" width="500" /><figcaption>My caption</figcaption>
</figure>Header 2
--------
```

The problem is the `</figure>Header 2` in the same line. It should be on different lines, as most markdown renderers will not understand that. The output should then be:

```md
Header 1
========

<figure>
<img src="./my-figure.jpg" alt="My caption" width="500" /><figcaption>My caption</figcaption>
</figure>

Header 2
--------
```

Is this clearer? Or have I not understood you? Thanks 🙂

**Comment by jgm** [comment]
Oh no! You were perfectly clear. Maybe you missed the fact that I already fixed the bug with the blank line; that's what closed the issue.

**Comment by jgm** [comment]
See commit 4060df6.

**Comment by cprecioso** [comment]
Oh, I absolutely did, sorry! Thanks for fixing the bug and for Pandoc, it's saving me plenty on time with my thesis! ☺️

I'll open another bug with the footnote issue.
