### ISSUE TITLE
docx header missing after conversion to markdown

### ISSUE THREAD

**Issue by abrahamneben** [jgm/pandoc#5122]
When I convert a docx file to a markdown file using `pandoc -f docx -t markdown test.docx -o test.md`, the output markdown file is missing is the header in the original docx file. When converting this file ([link to the docx file](https://github.com/jgm/pandoc/files/2642381/test.docx)) ...
![screen shot 2018-12-03 at 11 15 12 pm](https://user-images.githubusercontent.com/3770156/49418668-56794580-f751-11e8-8039-896d76591e5f.png)
...the output is 
```
and here is some body text
```
Is there a way to get pandoc to include the docx header?

**Comment by jgm** [comment]
Try with -s.

**Comment by abrahamneben** [comment]
Sorry, `-s` doesn't change anything. The header is still missing with `pandoc -s -f docx -t markdown test.docx -o test.md`

**Comment by mb21** [comment]
Hm.. that's a funny docx file. The text that's missing is actually in a `header1.xml` file, not the usual `document.xml`. How did you create that header?

**Comment by abrahamneben** [comment]
Uh, I double clicked in the header area and added the text.

**Comment by mb21** [comment]
Ah, this is a [page header](https://support.office.com/en-us/article/add-or-edit-headers-and-footers-in-word-for-mac-98a28ebf-8bf5-478c-a91f-548aebe87725)? It appears on top of every page, right? Pandoc doesn't have a concept of a page (neither does markdown), so it doesn't really make sense to import this. Wouldn't you agree?

**Comment by abrahamneben** [comment]
I was hoping pandoc would put a single copy of the docx page header at the beginning of the output markdown file. Is there any way to do that during the conversion?

**Comment by jgm** [comment]
Abraham Neben <notifications@github.com> writes:

> I was hoping pandoc would put a single copy of the docx page header at the beginning of the output markdown file. Is there any way to do that during the conversion? 

Sorry, no.

**Comment by mb21** [comment]
Duplicate of https://github.com/jgm/pandoc/issues/5211
