### ISSUE TITLE
Docx file giving corrupt error while modifying in python using python.docx. 

### ISSUE THREAD

**Issue by LakshmiTadikonda1** [jgm/pandoc#5125]
Docx file giving corrupt error while modifying in python using python.docx. I am adding a new section in .docx file which is already 2 pages with some data. I am adding a new page in landscape orientation and  adding a picture and saving it. The output docx generated on opening gives an error popup -"Were sorry We can't open "document" because we found a problem with its contents. XML parsing error. Location Part:/word/footer1.xml, Line: 0, Column:0" Any help is appreciated

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by jgm** [comment]
If I understand you correctly, you're creating a docx using pandoc, then modifying it using a python program.  The docx pandoc creates opens successfully with Word, but the modified version doesn't.

Is that right?  If so, why think this is a problem with pandoc rather than the python program?
