### ISSUE TITLE
src:url property of css for ePub expects relative path

### ISSUE THREAD

**Issue by earthbound19** [jgm/pandoc#5129]
Perhaps this requirement is technically correct, but this was a doozy to figure out.

in a css stylesheet, I attempted to refer to an embedded truetype font:

```
@font-face {
	font-family: customFont;
	font-style: normal;
	font-weight: normal;
	src:url("CustomFont.ttf") ;
	}
```

--and after a clue from epubcheck errors about not finding the embedded font, I figured out it expects a path that is relative to the stylesheet (where the style is embeeded in a /styles directory in the ePub archive) :

```
@font-face {
	font-family: customFont;
	font-style: normal;
	font-weight: normal;
	src:url("../fonts/CustomFont.ttf") ;
	}
```

Maybe the example sytlesheets I found about this simply did it wrong? There are many out there, though, all omitting the apparently necessary relative path.

Is this a bug? Or is this just a hard thing that has to be learned? :)

**Comment by mb21** [comment]
Jup, that's just how it works: https://stackoverflow.com/a/940475/214446

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
