### ISSUE TITLE
load parskip only if not handled by document class

### ISSUE THREAD

**Issue by Konfekt** [jgm/pandoc#5131]
Regarding the default inclusion of `parskip` at https://github.com/jgm/pandoc-templates/blob/7fed34ab85d9c89b7f17707f7e97b4daa75276fb/default.latex#L162 , how about making this conditional on the documentclass being different from one of the KOMA classes (in TeX, this can be tested for by `\@ifundefined{KOMAClassName}{}{...}`) so that KOMA does not warn about the incompatibilities arising when using both, KOMA and `parskip` at the same time?

According to https://tex.stackexchange.com/questions/133003/using-the-parskip-package-i-find-the-space-between-subtitles-ugly it is better to solely rely on KOMA instead.

**Comment by Konfekt** [comment]
Thank you for pointing the `indent` option out. I made a PR.

**Comment by mb21** [comment]
@Konfekt Thanks, but you made to pull to the wrong repo. From that repo's README:

> This repository is a subtree of pandoc; it will be updated each time there is a new pandoc release. However, changes to templates are made first in pandoc; thus, issues and pull requests should be made pandoc's issue tracker rather than here.

**Comment by Konfekt** [comment]
Thank you, I hope the PR now applies to the correct repo.

**Comment by Konfekt** [comment]
True, thank you, that was a self-referential pull request to my own repo. Now it is fixed: https://github.com/jgm/pandoc/pull/5143
