### ISSUE TITLE
Repository topics

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#5132]
GitHub allows repository owners to give a set of topics for their project. It might be nice to add some topics to this repo, as it helps discoverability.  E.g., adding *Markdown* topic would cause this repo to show up here: https://github.com/topics/markdown

**Comment by mb21** [comment]
There is even https://github.com/topics/pandoc

**Comment by jgm** [comment]
Sure, I've added a few topics. There's a limit of 20, so we can't list all the formats pandoc supports; I've opted for a minimal approach.  Feel free to suggest changes.

**Comment by tarleb** [comment]
I like the minimal approach. We could replace *markup-converter* with the more generic *converter*, then adding *documents*, *presentations*, and maybe *publishing* to clarify the conversion subject.

**Comment by jgm** [comment]
I went with document, presentation, publishing, converter.
