### ISSUE TITLE
Why does pandoc convert "<br>" to "+ \n" on html to asciidoc conversion?

### ISSUE THREAD

**Issue by repomorphic** [jgm/pandoc#5136]
Hi there. I am trying to convert HTML to asciidoc using pandoc but pandoc converts `<br>` tags into `+\n` instead of `\n` like the following.I also tried asciidoc-escaped_line_breaks but nothing changed. 

Terminal Command:
`pandoc +RTS -K100000000 -RTS --wrap=preserve -f html -t asciidoc-escaped_line_breaks "input.html" -o "output.asciidoc"`

input.html
```
s
<br>
s
```

output.asciidoc
```
s +
s
```

Expected Output:
```
s
s
```

Version:pandoc 1.19.2.4

**Comment by mb21** [comment]
The `escaped_line_breaks` extension is currently only implemented for markdown, not for AsciiDoc.

You could write a pandoc lua filter to strip all `LineBreak` elements from the document...

Note also that you have a really old pandoc version.

**Comment by mb21** [comment]
see https://stackoverflow.com/questions/53693028/why-does-pandoc-convert-br-to-n-on-html-to-asciidoc-conversion
