### ISSUE TITLE
YAML title in Epub Crashes Adobe Digital Editions 4.5.9

### ISSUE THREAD

**Issue by frastlin** [jgm/pandoc#5141]
When title is specified in the yaml metadata and the document is exported to Epub, [Adobe Digital Editions](https://www.adobe.com/it/solutions/ebook/digital-editions/download.html#) can't open it. If title is not included in the yaml data and Pandoc has to do the title generation itself, the Epub works just fine.

Problem:

Pandoc's yaml title crashes Adobe Digital Editions, but the automatically generated title does not.

What should happen:

Adobe Digital Editions should open both files without a problem.

What happens:

Adobe Digital Editions opens in a "not responding" state.

Pandoc version:
2.5

Adobe Digital Editions version:
4.5.9
OS:
Windows 10 64 bit

Other information:
Attached are 4 files, the markdown and the Epub generated from the Markdown. Adobe Digital Editions opens test2.epub, but not test1.epub.

[epubTests.zip](https://github.com/jgm/pandoc/files/2663711/epubTests.zip)

**Comment by mb21** [comment]
The `test1.epub` file validates with http://validator.idpf.org

Also, I cannot reproduce this with my Kobo Glo HD 4.8.11073 firmware, which I believe uses some Adobe reader as well.

Can you reproduce in older Adobe Digital Editions versions? It's most probably a bug on their end...

**Comment by frastlin** [comment]
I've tried it on an older version, but I don't remember what it was, that is why I updated it.
It's strange that it only hangs when the title element is specified and it works when no title is specified. What changes between the two?

**Comment by mb21** [comment]
All I know is that the reviews for Adobe Digital Editions say it's very unstable... and I can recommend the open source [calibre](https://calibre-ebook.com/)...

**Comment by jgm** [comment]
If it's valid epub, then this is not a bug with pandoc.
Note:  in test2.epub, there is no `dc:title` element in the `metadata` element of content.opf.
In test1.epub, there is a `dc:title` element.
So that is the relevant difference.
