### ISSUE TITLE
Encoded URL spaces in GridTables

### ISSUE THREAD

**Issue by chapterjason** [jgm/pandoc#5147]
Pandoc Version: 2.5-windows-x86_64, also works with our try online version.

Let me explain this by example.

Example input markdown:
```markdown
+-------------------------------------+-------------------------------------+
| First                               | Second                              |
+=====================================+=====================================+
| Try out panndoc                     | And read the docs                   |
| [here](https://pandoc.org/try/?text | [here](https://pandoc.org/MANUAL.ht |
| =%23%23+Test&from=markdown&to=)     | ml)                                 |
+-------------------------------------+-------------------------------------+
```

Output latex:
```tex
\begin{longtable}[]{@{}ll@{}}
\toprule
\begin{minipage}[b]{0.45\columnwidth}\raggedright
First\strut
\end{minipage} & \begin{minipage}[b]{0.45\columnwidth}\raggedright
Second\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.45\columnwidth}\raggedright
Try out panndoc
\href{https://pandoc.org/try/?text\%20=\%23\%23+Test\&from=markdown\&to=}{here}\strut
\end{minipage} & \begin{minipage}[t]{0.45\columnwidth}\raggedright
And read the docs \href{https://pandoc.org/MANUAL.ht\%20ml}{here}\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}
```
You can see there are this `%20` in the urls what makes the url invalid. Also same result in HTML.

```html
<table style="width:95%;">
<colgroup>
<col style="width: 47%" />
<col style="width: 47%" />
</colgroup>
<thead>
<tr class="header">
<th>First</th>
<th>Second</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Try out panndoc <a href="https://pandoc.org/try/?text%20=%23%23+Test&amp;from=markdown&amp;to=">here</a></td>
<td>And read the docs <a href="https://pandoc.org/MANUAL.ht%20ml">here</a></td>
</tr>
</tbody>
</table>
```
I also tried to remove the spaces before and after the pipe in the grid table, but same result.

I expected something like that:

```html
<table style="width:95%;">
<colgroup>
<col style="width: 47%" />
<col style="width: 47%" />
</colgroup>
<thead>
<tr class="header">
<th>First</th>
<th>Second</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Try out panndoc <a href="https://pandoc.org/try/?text=%23%23+Test&amp;from=markdown&amp;to=">here</a></td>
<td>And read the docs <a href="https://pandoc.org/MANUAL.html">here</a></td>
</tr>
</tbody>
</table>
```

**Comment by mb21** [comment]
It's probably best to just use [reference links](https://pandoc.org/MANUAL.html#reference-links) for cases like this...

**Comment by mb21** [comment]
Try:

    +-------------------------------------+-------------------------------------+
    | First                               | Second                              |
    +=====================================+=====================================+
    | Try out panndoc                     | Pandoc!                             |
    | [my link title is just              | [here](https://pandoc.org/)         |
    | a bit][foo-bar-identifier]          |                                     |
    +-------------------------------------+-------------------------------------+

    [foo-bar-identifier]: https://pandoc.org/try/?text=%23%23+Test&from=markdown&to=

**Comment by jgm** [comment]
This isn't a bug.  Your first table cell contains the content
```
Try out panndoc
[here](https://pandoc.org/try/?text
=%23%23+Test&from=markdown&to=)
```
Soft line breaks in pandoc are interpreted as spaces, so you get a space after `text`.
If you don't want this, you need get the link on one line.  You can do that with reference links, as noted.  Or you might consider using pipe tables with very wide cells (see the documentation for how widths are managed).
