### ISSUE TITLE
Org writer could match org-mode's fill-paragraph especially for links

### ISSUE THREAD

**Issue by bradyt** [jgm/pandoc#5160]
If I have a file `test.md` with contents

``` markdown
The `dart-sdk-path` variable can be set to tell Emacs where to find the Dart
SDK. This is used to run the [Dart analysis server](#dart-analyzer) and the Dart
formatter. By default, it's set by finding the `dart` executable on the system
path.
```

and I apply `pandoc test.md -o test.org --columns=70` (selecting `70` as that is default `fill-column` in Emacs), then I have the following result,

``` org-mode
The =dart-sdk-path= variable can be set to tell Emacs where to find
the Dart SDK. This is used to run the [[#dart-analyzer][Dart analysis
server]] and the Dart formatter. By default, it's set by finding the
=dart= executable on the system path.=
```

Now, this is justified correctly if one is viewing as plain text. But org-mode in Emacs, which I'm sure is the primary environment for reading .org files, renders it as such:

``` org-mode
The =dart-sdk-path= variable can be set to tell Emacs where to find
the Dart SDK. This is used to run the Dart analysis
server and the Dart formatter. By default, it's set by finding the
=dart= executable on the system path.=
```

You can get back the previous view via `M-x org-toggle-link-display RET`.

Perhaps one could write a little bit of Haskell to help the writer measure the line length according to the link description. Unfortunately I do not see myself getting to this soon. I just wanted to put out this idea first.

That is, I'd like pandoc to write as

``` org-mode
The =dart-sdk-path= variable can be set to tell Emacs where to find
the Dart SDK. This is used to run the [[#dart-analyzer][Dart analysis server]] and the
Dart formatter. By default, it's set by finding the =dart= executable
on the system path.
```

so that it is rendered by Emacs as

``` org-mode
The =dart-sdk-path= variable can be set to tell Emacs where to find
the Dart SDK. This is used to run the Dart analysis server and the
Dart formatter. By default, it's set by finding the =dart= executable
on the system path.
```

**Comment by jgm** [comment]
Personally I don't think it's worth the extra complexity to achieve this.
Matching word-wrapping in Emacs isn't a design goal.
