### ISSUE TITLE
Option --reference-links is ignored when setting both -f and -t to "gfm"

### ISSUE THREAD

**Issue by skddc** [jgm/pandoc#5161]
Version: 2.3.1 (with bash on Arch Linux)

I'm trying to clean/re-format GitHub-flavored Markdown files in a shared repo, and want to use these two options:

1. No automatic IDs in headings, i.e. turn off `auto_identifiers` extension
2. Turn all inline links into reference links, i.e. `--reference-links` command line arg

This command should work as intended, afaics:

    pandoc -f gfm -t gfm-auto_identifiers --reference-links --atx-headers -o $filename $filename

However, when running this, `--reference-links` is ignored, and even existing reference links are turned into inline links.

**Comment by jgm** [comment]
Currently the gfm writer uses a wrapped version of the library GitHub uses (a variant of cmark).
This doesn't have an option to create reference links, so there's nothing we can do about that here.
You could request the feature at jgm/cmark, and if it were implemented there it could be activated in pandoc.

**Comment by jgm** [comment]
You can also try with `-t markdown_github`, which will work with `--reference-links`.
