### ISSUE TITLE
org mode headings past level three converted to numbered outline list

### ISSUE THREAD

**Issue by acate** [jgm/pandoc#5169]
Converting emacs org mode document to docx and markdown (at the very least) doesn't preserve heading levels past level three.  Higher numbered headings are converted to a numbered outline list, complete with (unwanted) hierarchical indentation.

**Comment by jgm** [comment]
@tarleb should be able to comment on the rationale for doing it this way.  (I suspect it is to match the behavior of org's own exporters.)

**Comment by tarleb** [comment]
This is intended behavior, and done for the reason mentioned by jgm (i.e., pandoc uses the same defaults as Emacs). See #3214 for details.

TL;DR: insert this line at the top of your org file:

    #+OPTIONS: H:9

**Comment by acate** [comment]
Many thanks for your time.
