### ISSUE TITLE
Pandoc should use cmark-gfm / gfm not exactly the same as Github -- concerned about further differences

### ISSUE THREAD

**Issue by rogusdev** [jgm/pandoc#5173]
With a line of text followed by a line that is a link:
```
cat <<EOF > in.md
Github Link:
https://github.com/
EOF
```

Github puts them on separate lines inside the paragraph (newline in between):
https://gist.github.com/rogusdev/a660fa5eb653b6cf947748404ca2649a

```html
<p>Github Link:
<a href="https://github.com/">https://github.com/</a></p>
```

With pandoc version 2.5 (manually installed because ubuntu 18.04 apt has 1.19.2.4 which does not have gfm input, only old markdown_github, which is even less accurate):
```
pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
```

Pandoc removes the newline between the text and the link:
`pandoc -f gfm -o out.html in.md`

```html
<p>Github Link: <a href="https://github.com/">https://github.com/</a></p>
```

As above, that is not what Github actually does, and you can also verify exactly that with a python wrapper around cmark-gfm:
`pip install --user cmarkgfm`

```python
import cmarkgfm

with open("in.md","r") as fileIn:
    markdown_text = fileIn.read()

    html = cmarkgfm.github_flavored_markdown_to_html(markdown_text)

    with open("out2.html","w") as fileOut:
        fileOut.write(html)
```

`python md.py`

which generates out2.html with the same output as Github actual, unlike pandoc.

Is pandoc using cmark-gfm, which is what github actually uses, or something else?  Are there any other inconsistencies I should be aware of?

This discrepancy has left me nervous but I would very much like to rely on pandoc for this -- it's a great tool!

Thanks.

**Comment by jgm** [comment]
Pandoc's gfm writer does indeed use cmark-gfm.

However, the `hard_line_breaks` extension is not
enabled by default.  You can enable it using
`-f gfm+hard_line_breaks`.

Why not enable it by default?  Because in GitHub
it's only enabled for short content (issue comments
and the like), and not for long-form content like
READMEs.
