### ISSUE TITLE
"Prelude.read: no parse" when giving -M with --template

### ISSUE THREAD

**Issue by K4zuki** [jgm/pandoc#5177]
### condition

- pandoc = 2.5
- OS = Ubuntu 16.04
- blank tex template = `markdown/template.tex`
- simple markdown file = `markdown/markdown.md`

```markdown
This is a pen
```

### how to reproduce
- input:
    `pandoc -f markdown -t latex -M meta='1e' --template markdown/template.tex markdown/markdown.md`
- output:
    `pandoc: Prelude.read: no parse`

- changing to `meta=''` stops error
- `meta='1e|3e|5e|7e|9e'` causes error but `'e'` does not
- removing quote does not stop error
- position of `-M meta=1e` does not stop error
- similar with #5162 ?

**Comment by jgm** [comment]
Simple repro:
```
% echo "" | pandoc -t html -M meta='1e' -s
pandoc: Prelude.read: no parse
```

**Comment by jgm** [comment]
I confirm that this issue affects current HEAD (5101f4324b08d6b7589a3a6a60eb4dc9b148e879).

**Comment by mb21** [comment]
Interestingly even:

    echo '' | pandoc -- -M foo=1e -s -f html -t native
    pandoc: Prelude.read: no parse

The `e` looks suspiciously like something is trying to parse this as an exponential number, scientific notation. But what/where?

**Comment by mb21** [comment]
Reading to `MetaInlines` works:

    cat foo.yaml
    foo: "1e"

    $ echo '' | stack exec pandoc -- --metadata-file foo.yaml -s -t native
    Pandoc (Meta {unMeta = fromList [("foo",MetaInlines [Str "1e"])]})
    []

But `-M` would be reading to `MetaString`... possibly it's the [`Read` instance on `Many`](https://github.com/jgm/pandoc-types/blob/master/Text/Pandoc/Builder.hs#L192) or something similar?

**Comment by jgm** [comment]
@mb21 - Thanks for tracking this down!

**Comment by jgm** [comment]
Interestingly we don't get the error if you include this metadata value in the YAML metadata in a markdown file.  Only with -M.

**Comment by jgm** [comment]
OK, we should be able to fix this in pandoc by using the failsafe schema instead of the json schema, which is used by default with `decodeStrict`, in `Text.Pandoc.App`'s function `readMetaValue`.

**Comment by jgm** [comment]
Note also this workaround:
```
echo '' | pandoc -- -M foo='!!text 1e' -s -f html -t native
```
