### ISSUE TITLE
RST reader giving `startFrom` a blank value when no line number specified

### ISSUE THREAD

**Issue by leungbk** [jgm/pandoc#5182]
The RST reader presently has

``` haskell
 let kvs = maybe [] (\n -> [("startFrom", trimr n)]) numberLines
```

where `n` can be an empty string. I would have expected the lambda here to return the alist only for non-empty  `n`,  and to return an empty list for empty `n`. The problem is that round-tripping 

```
.. code:: haskell
   :number-lines:

   main = putStrLn "Hello World!"
   unsafePerformIO main
```

from RST to native output back to RST adds an extra space after the `:number-lines:` that makes sense only for non-empty `n` in the above reader snippet; see the following snippet from the RST writer.

``` haskell
let startnum = maybe "" (\x -> " " <> text x) $ lookup "startFrom" kvs
```

Changing the reader snippet to have something like

``` haskell
\n -> let trimmed = trimr n in
                                     if trimmed == ""
                                       then []
                                       else [("startFrom", trimmed)]
```

in the lambda is what I would do, but I also noticed that the MediaWiki reader has something similar that also seems to admit a blank value corresponding to `startFrom`:

``` haskell
let kvs = maybe [] (\x -> [("startFrom",x)]) mbstart
```

An alternative way of preventing the aforementioned round-trip blank space would be to modify the RST writer, but changing the reader instead makes more sense to me. I don't know MediaWiki (or RST, for that matter) very well, so I'm not sure if there's some other reason to keep the reader snippets looking like this.

**Comment by jgm** [comment]
> I would have expected the lambda here to return the alist only for non-empty n, and to return an empty list for empty n.

Yes: this would be better.
