### ISSUE TITLE
Dokuwiki Writer : wrong path for internal images

### ISSUE THREAD

**Issue by daamien** [jgm/pandoc#5183]
Hi !

Thanks for this wonderful software, we're producing thousands pages of PostgreSQL trainings with it !

Here's a report  for what looks to me like a bug in the dokuwiki writer:

the markdown syntax `![](foo.png)` is converted into `{{:foo.png}}`

See https://pandoc.org/try/?text=!%5B%5D(images%2Ffoo.png)&from=markdown&to=dokuwiki`

The colon character (`:`) is a marker for namespaces in the dokuwiki syntax  (see  https://www.dokuwiki.org/namespaces ) and `{{:foo.png}}` means the files is located in the root namespace. This is similar to an absolute path. 

The markdown `![](foo.png)` means the file is located in the same relative path that the document. Therefore it should be translated as `{{foo.png}}` (no colon).

The problem seems to be on lines 134 and 520 of the DokuWiki writer: 

https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/DokuWiki.hs#L134
https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/DokuWiki.hs#L520

**Comment by mb21** [comment]
But how would a user produce `{{:foo.png}}` in dokuwiki output then? Seems like it was done like this to accommodate what is probably the default use-case when using pandoc to produce dokuwiki: to paste it in a online doku wiki, and refer to images in the default namespace. Or am I missing something?

**Comment by daamien** [comment]
`![](/foo.png)` will produce `{{/foo.png}}` which is equivalent to `{{:foo.png}}`

I understand that the dokuwiki engine uses absolute path by default but it is possible to include internal images with a relative path... With the current version of the dokuwiki writer, a  `:` is added as prefix to all internal media locations and there's no way to produce a relative location

**Comment by claremacrae** [comment]
I guess if the test(s) added for #1739 still pass, and new test(s) have been added for this case, it should be fine.
