### ISSUE TITLE
Failure to convert included files from .org to .rst 

### ISSUE THREAD

**Issue by guanqun-yang** [jgm/pandoc#5188]
# Problem
I am writing blogs using Emacs org-mode. Specifically, I first create contents and get `ml.org` file and then convert it into `ml.rst` using pandoc command `pandoc -f org -t rst ml.org`.

In order to modulize the contents I wrire. I use the
following code in org-mode

    * Supervised Learning
    ** Regression
    #+INCLUDE: "ml/linear.org" :minlevel 3
    ** Classification
    #+INCLUDE: "ml/logistic.org" :minlevel 3
    
    * Unsupervised Learning
    ** Clustering
    #+INCLUDE: "ml/kmeans.org" :minlevel 3
    #+INCLUDE: "ml/spectral.org" :minlevel 3
    
    ** Dimensionality Reduction
    #+INCLUDE: "ml/pca.org" :minlevel 3
    #+INCLUDE: "ml/tsne.org" :minlevel 3

When converting this file into pdf using LaTex, the structure is correct and is shown [here][1]. However, after conversion to `ml.rst` file, **none** of these files are included.

# What I Have Done

It seems that this could be resolved using template feature in pandoc, but I am not sure what to do.

Could anyone help me, thank you in advance.

  [1]: https://i.stack.imgur.com/G3x5v.png

**Comment by tarleb** [comment]
Thank you for the report. When testing with the latest pandoc version, the files are included, but the header level is set incorrectly. This means there is a bug in pandoc's handling of the `:minlevel` attribute.

**Comment by tarleb** [comment]
@leungbk, since you contributed to pandoc's org components, would you like to take a look? I won't get around to do any coding this week.

**Comment by leungbk** [comment]
OK, I'll try to finish this by the end of the weekend.

**Comment by tarleb** [comment]
That is great, thanks! (and no rush)
