### ISSUE TITLE
How to suppress numbering in Markdown -> Epub TOC?

### ISSUE THREAD

**Issue by jeffmcneill** [jgm/pandoc#5192]
Looking at the documentation, it does not appear that there is an option to suppress the generation of numbers for each toc element. I'd prefer to have no numbering whatsoever, but definitely have a TOC.

For example:

1. Copyright
2. Dedication
3. Preface
4. Book One
5. Book Two
...

I would prefer:

Copyright
Dedication
Preface
Book One
Book Two
...

Is this possible?

**Comment by mb21** [comment]
AFAIK the default is not to have numbering. Can you unzip the generated .epub file and say in which subfile you have numbers? It might just be some CSS or be your ebook viewer.

**Comment by jgm** [comment]
We use an ol for the nav page, which gives you
numbers.

But the ol has a special class `toc`, so you
should be able to add a CSS rule for

ol.toc

that suppresses the numbering.

**Comment by jgm** [comment]
Indeed, pandoc's default epub css has this in it:
```
ol.toc li { list-style-type: none; margin: 0; padding: 0; }
```
If you're using custom css, you just need to include this.

**Comment by jeffmcneill** [comment]
Note: the "landmarks" that are generated do not have a class on the ol, therefore the display of the numbering of them (e.g., "Cover," "Table of contents") cannot be suppressed. Any idea how to either suppress numbers on the landmarks?

**Comment by jgm** [comment]
Putting a rule on

**Comment by jgm** [comment]
Try putting a rule on

    nav ol

That should work.  Or to be more precise

    nav[epub:type="landmarks"] ol

I suspect many readers already suppress numbers for
these, but we could add a rule to our default CSS to
do it.

**Comment by jgm** [comment]
I'm going to change the writer to put an id
"landmarks" on the nav, so you can style

nav#landmarks ol

**Comment by jeffmcneill** [comment]
The id will help. I can't seem to get referencing nav[epub to work in my ebook viewers.

Here is the css I am using to hide numbers, preserve indents in the NCX-based TOC, and hide the landmarks (once I add the id)

```
/* remove numbering in toc, set indent of subsections */
ol.toc { list-style-type: none; margin: 0px 0px 0px 15px !important; padding: 0 !important; }
/* hide landmarks */
nav#landmarks ol { display: none !important; }
```

**Comment by Monirzadeh** [comment]
> The id will help. I can't seem to get referencing nav[epub to work in my ebook viewers.
> 
> Here is the css I am using to hide numbers, preserve indents in the NCX-based TOC, and hide the landmarks (once I add the id)
> 
> ```
> /* remove numbering in toc, set indent of subsections */
> ol.toc { list-style-type: none; margin: 0px 0px 0px 15px !important; }
> /* hide landmarks */
> nav#landmarks ol { display: none !important; }
> ```

I have an e-book with RTL chapter name
this style hide numbering part but make chapter name LTR.
Is there any option to remove `ol.toc` element completely?

**Comment by jgm** [comment]
> Is there any option to remove ol.toc element completely?

``` css
ol.toc { display: none; }
```

**Comment by Monirzadeh** [comment]
> > Is there any option to remove ol.toc element completely?
> 
> ```css
> ol.toc { display: none; }
> ```

Thanks but it just hide that.
I want to pandoc don't add that.
