### ISSUE TITLE
Soft line breaks become hard in GitHub-flavored markdown (gfm+hard_line_breaks)

### ISSUE THREAD

**Issue by Rufflewind** [jgm/pandoc#5195]
I recently noticed what I think is a change in Pandoc's behavior around `gfm`.

```
$ pandoc -f markdown_strict -t gfm+hard_line_breaks <<EOF
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
EOF
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
```

I don't think this is correct, as it would imply these paths do not yield the same result:

    markdown_strict -> gfm+hard_line_breaks -> html
    markdown_strict -> html

In contrast, this problem does *not* occur with `markdown_strict -> markdown_strict+hard_line_breaks`:

```
$ pandoc -f markdown_strict -t markdown+hard_line_breaks <<EOF
The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog.
EOF
The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.
```

This I would think ought to be the correct output of any `-t <writer>+hard_line_breaks`.

<details>

```
$ pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.5
Default user data directory: /home/rf/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

</details>

**Comment by jgm** [comment]
Actually, the commonmark/gfm writers do support `hard_line_breaks`.

**Comment by jgm** [comment]
This is definitely not right:
```
% pandoc -f native -t gfm+hard_line_breaks
[Para [Str "hello",SoftBreak,Str "hi"]]
^D
hello
hi
```

**Comment by jgm** [comment]
Okay, cmark is a bit odd; `OPT_HARDBREAKS` only affects the writers, causing SOFTBREAK elements to be rendered as hard line endings in a writer-dependent way.  It would have made more sense to have `OPT_HARDBREAKS` affect the parser. I'm not sure why I did it that way, but it could be revisited.

IN the short term, I can work around this in pandoc.

**Comment by Rufflewind** [comment]
Thank you!
