### ISSUE TITLE
HTML writer does not separate adjacent footnote references

### ISSUE THREAD

**Issue by edom** [jgm/pandoc#5197]
# How to reproduce

Pandoc version

```
pandoc 2.4
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.2, skylighting 0.7.4
```

Command line

```
pandoc a.org -o a.html
```

Input file `a.org`

```
Reference[fn::Footnote 1][fn::Footnote 2][fn::Footnote 3].
```

Actual output:

```
<p>Reference<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a><a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
<section class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Footnote 1<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Footnote 2<a href="#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>Footnote 3<a href="#fnref3" class="footnote-back">↩</a></p></li>
</ol>
</section>
```

Expected output (Note that every footnote reference is surrounded by square brackets, a la Wikipedia):
```
<p>Reference<a href="#fn1" class="footnote-ref" id="fnref1"><sup>[1]</sup></a><a href="#fn2" class="footnote-ref" id="fnref2"><sup>[2]</sup></a><a href="#fn3" class="footnote-ref" id="fnref3"><sup>[3]</sup></a>.</p>
<section class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Footnote 1<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Footnote 2<a href="#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>Footnote 3<a href="#fnref3" class="footnote-back">↩</a></p></li>
</ol>
</section>
```

There are two options:
- The Wikipedia way: Surround each footnote reference with square brackets.
- The Org Mode way: Separate footnote references with `<sup>, </sup>`.

I recommend the first, because it should be less effort.

For comparison,
Org mode version 9.1.14 with body-only export (C-c C-e C-b h H) has this output:

```
<p>
Reference<sup><a id="fnr.1" class="footref" href="#fn.1">1</a></sup><sup>, </sup><sup><a id="fnr.2" class="footref" href="#fn.2">2</a></sup><sup>, </sup><sup><a id="fnr.3" class="footref" href="#fn.3">3</a></sup>.
</p>
<div id="footnotes">
<h2 class="footnotes">Footnotes: </h2>
<div id="text-footnotes">

<div class="footdef"><sup><a id="fn.1" class="footnum" href="#fnr.1">1</a></sup> <div class="footpara">Footnote 1</div></div>

<div class="footdef"><sup><a id="fn.2" class="footnum" href="#fnr.2">2</a></sup> <div class="footpara">Footnote 2</div></div>

<div class="footdef"><sup><a id="fn.3" class="footnum" href="#fnr.3">3</a></sup> <div class="footpara">Footnote 3</div></div>


</div>
</div>
```

**Comment by tarleb** [comment]
The current method is in line with other output formats, e.g., LaTeX. Consistent output is one of pandoc's goals, so this is unlikely to change.

Not that one can use CSS to get a Wikipedia-like output. For example, just adding the following to your org file should be sufficient:

```
#+BEGIN_HTML
<style type="text/css">
.footnote-ref > sup::before {
  content: "["; 
}
.footnote-ref > sup::after {
  content: "]"; 
}
</style>
#+END_HTML
```

**Comment by edom** [comment]
I see, so this is a problem with the HTML writer.

Thanks for the code fragment, but I'm happier with the broken output. I fear that my future self will hate my present self if I use that fragment. I am using Org as my authoring format, and I am converting tens of Org files with tens of footnotes each, and I am trying to not fall deeper into Org's hackiness, because I may also want to export some of my Org files into LaTeX files in the future. I am authoring in Org, and using Pandoc to convert Org to HTML for screen and to LaTeX for printing.

About consistency, the plain-text writer does surround the footnotes with brackets though.

```
pandoc a.org -o a.txt --to plain
```

```
Reference[1][2][3].

[1] Footnote 1

[2] Footnote 2

[3] Footnote 3
```

**Comment by tarleb** [comment]
Good point about the plain writer. I guess the square brackets there are just a substitute for the lack of superscript in plain text. CC @jgm

A less hacky solution than including the snippet directly would be to use a separate CSS file. One could create a file `footnotes.css` and either pass it to pandoc via the `--css` option, or link it from your org files by adding

    #+CSS: footnotes.css

None of these methods, including the raw HTML blocks, should interfere with LaTeX output.

**Comment by edom** [comment]
I see. I just remembered that I am already using a custom HTML
`--template`, so your CSS fragment is indeed a satisfactory solution for
me. Thank you!

Therefore, this issue is now about the consistency between the HTML writer
and the plain writer.

**Comment by jgm** [comment]
Erik Dominikus <notifications@github.com> writes:

> I see. I just remembered that I am already using a custom HTML
> `--template`, so your CSS fragment is indeed a satisfactory solution for
> me. Thank you!
>
> Therefore, this issue is now about the consistency between the HTML writer
> and the plain writer.

Well, we could use unicode superscript numbers for
footnotes in the plain writer.  But that gets a bit
ugly since not all fonts have these.  So instead we
use the brackets.

I think this can be closed.
