### ISSUE TITLE
Support for Glob 0.10.x

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#5199]
Would it be possible to let `pandoc` support http://hackage.haskell.org/package/Glob-0.10.0? The build works just fine, so it seems like it's just a matter of editing the Cabal file on Hackage to include that version in the acceptable range.

**Comment by mb21** [comment]
`pandoc.cabal` has `Glob >= 0.7 && < 0.11`, isn't that what you're asking for?

**Comment by mb21** [comment]
Ah, this was only added [recently](https://github.com/jgm/pandoc/commit/39efcedf8a201e2fa20802ce15647454535859c7). Simply use current master instead of the latest release.

**Comment by peti** [comment]
> Ah, this was only added [recently](https://github.com/jgm/pandoc/commit/39efcedf8a201e2fa20802ce15647454535859c7). Simply use current master instead of the latest release.

I am packaging pandoc for both openSUSE Linux and NixOS Linux, and neither of these distributions is keen on distributing "current master". It would be much better to just edit the Cabal file on Hackage, honestly, so that everyone benefits from the more accurate dependency specification.

**Comment by mb21** [comment]
We close issues when they are fixed in current master. You'll have to wait for the next pandoc release, at that point you'll also see the change reflected on Hackage.

**Comment by peti** [comment]
So, I read this correctly as that you are unwilling to spend 60 seconds editing the cabal file of the current release on Hackage to allow me to distribute the current version to thousands of users?

**Comment by mb21** [comment]
Uh, I'm sorry... I was not aware one could do that. Either way, I don't have access to the pandoc hackage package. I'll reopen this issues so you can discuss this with @jgm.

**Comment by jgm** [comment]
I updated the metadata on hackage.

**Comment by peti** [comment]
> I updated the metadata on hackage.

Thank you very much.
