### ISSUE TITLE
Please add support for tasty 1.2

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#5200]
Would it be possible to let pandoc support http://hackage.haskell.org/package/tasty-1.2? The build works just fine, so it seems like it's just a matter of editing the Cabal file on Hackage to include that version in the acceptable range.

**Comment by jgm** [comment]
The dev version already allows tasty 1.2, so this will be in the next release. If it's urgent, we could consider doing a Hackage metadata revision.

**Comment by jgm** [comment]
I did a metadata revision.
