### ISSUE TITLE
Support for IRI links (Unicode, Emojis)

### ISSUE THREAD

**Issue by robmuh** [jgm/pandoc#5201]
Conversion of slug (internal header ids) from heading titles that contain [valid IRI characters](https://tools.ietf.org/html/rfc3987) such as unicode international language characters and emojis fails to be recognized. This limits pandoc's adoption internationally or when covering foreign language topics. 

![screen shot 2019-01-06 at 6 08 32 pm](https://user-images.githubusercontent.com/3749067/50742832-1ab51e00-11de-11e9-851e-79f5b344790c.png)

It is perhaps informative to mention VuePress observes these correctly with the following JavaScript algorithm (just for illustration, not very efficient):

 ```js
const removeDiacritics = require('diacritics').remove
// eslint-disable-next-line no-control-regex
const rControl = /[\u0000-\u001f]/g
const rSpecial = /[\s~`!@#$%^&*()\-_+=[\]{}|\\;:"'<>,.?/]+/g

module.exports = function slugify (str) {
  return removeDiacritics(str)
    // Remove control characters
    .replace(rControl, '')
    // Replace special characters
    .replace(rSpecial, '-')
    // Remove continous separators
    .replace(/\-{2,}/g, '-')
    // Remove prefixing and trailing separators
    .replace(/^\-+|\-+$/g, '')
    // lowercase
    .toLowerCase()
}
```

Here is the ABNF for a visible rune/codepoint from the IRI specification:

```abnf
vrune       = %x21-7E / %xA1-167F / %x1681-1FFF
            / %x200B-2027 / %x202A-202E / %x2030-205E
            / %x2060-2FFF / %x3001-D7FF / %xF900-FDCF
            / %xFDF0-FFFD / %x10000-1FFFD / %x20000-2FFFD
            / %x30000-3FFFD / %x40000-4FFFD / %x50000-5FFFD
            / %x60000-6FFFD / %x70000-7FFFD / %x80000-8FFFD
            / %x90000-9FFFD / %xA0000-AFFFD / %xB0000-BFFFD
            / %xC0000-CFFFD / %xD0000-DFFFD / %xE0000-EFFFD
```

**Comment by mb21** [comment]
See https://pandoc.org/MANUAL.html#extension-auto_identifiers

Emojis are just stripped, you can still link to them:

    $ echo '# foo 🤣 bar' | pandoc
    <h1 id="foo-bar">foo 🤣 bar</h1>

International character (like é) are kept as is. Or can you give examples where they are stripped?

**Comment by mb21** [comment]
The function that does this is [`inlineListToIdentifier`](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Shared.hs#L491).

Probably [`Data.Char.isAlphaNum`](https://www.stackage.org/haddock/lts-13.1/base-4.12.0.0/Data-Char.html#v:isAlphaNum) does not recognize emojis as alphanumerical characters.

We should probably change the documentation from:

> Remove all punctuation, except underscores, hyphens, and periods.

to something like:

> Remove all non-alphanumeric characters, except underscores, hyphens, and periods.  Alphanumeric detection is Unicode-aware, thus for example `é`, `ö` or Chinese characters, are kept.

**Comment by robmuh** [comment]
I love that clarification. Still digging into the underlying `WCsubst.c` but I'm betting what I was looking for was `isPrint` instead of `isAlphaNum`. The IRI RFC calls is the "printable" range as well. I had a hunch this was what was going on. I would perhaps add "... thus for example ... are kept but emojis, which are not considered part of the alphanumeric span, are not." Thank you for research this and responding. Feel free to close this if you feel it is addressed sufficiently.
