### ISSUE TITLE
DokuWiki reader: parse table alignment

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#5202]
DokuWiki format allows to [align table cells with whitespace](https://www.dokuwiki.org/wiki:syntax#tables). Pandoc has no way to represent individual cell alignment, but it may still be useful to align the whole column according to header alignment, if header is present.

This would allow Pandoc to correctly parse such tables:
```
^          right^   center   ^left            ^
|  right-aligned|  centered  |left-aligned    |
|  right-aligned|  centered  |left-aligned    |
```

**Comment by damon-sava-stanley** [comment]
Howdy, I've taken a stab at this (in the linked pull request), though it is a bit of a bodge.
