### ISSUE TITLE
Image reader

### ISSUE THREAD

**Issue by ycpei** [jgm/pandoc#5205]
I am working on a project to solve the pdf parsing problem by using computer vision to convert images to AST.

Assuming such an image reader exists, then one can convert pdf to say markdown by the following route:
pdf -> png / jpg / whatever -> ast -> md

Has this been done or discussed before? Would this fit in the framework of the Pandoc project?

**Comment by mb21** [comment]
I guess this question is a better fit for the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss).

Yes, this has been done before by numerous people. It's called [OCR](https://en.wikipedia.org/wiki/Optical_character_recognition). Nobody has managed to make this 100% failure-proof, simply because the information is not there in the image. Thus I think it's fair to say that it's out-of-scope for pandoc. However, you can use any OCR tool which can output to HTML, then use pandoc to go from there.

**Comment by ycpei** [comment]
@mb21 Thanks, correct me if I am wrong, but OCR systems do not convert images to AST, as they merely output unstructured plaintext.

So you are saying it's out of scope due to the probabilistic nature of such tasks, fair enough.

**Comment by mb21** [comment]
Fairly certain that there are OCR system that output HTML – with all the guess-work that's involved there (is it bold or a header?). And HTML is usually parsed to an AST (often called DOM).

**Comment by ycpei** [comment]
From what I have read about OCR systems I think have a different focus from Pandoc. They are more interested on getting text from scanned / photographed images, and care less about the structure of the documents.

Sure html has AST, but the focus of OCR again produces html that does not seem to preserve the logical structure of the document. 

For example, I converted the stackedit readme markdown to html and from html to image 

![stackedit](https://imgur.com/a/FUUdBx4)

and then used [tesseract](https://github.com/tesseract-ocr/tesseract) to convert to html. The original html is very simple, with a hearder and some unordered lists, but in the converted html there was no <ul> or header like <h2>. It was just a jumble of text.

It is tempting to say that this is belongs to an issue of tesseract, but my point is, even the leader of / state-of-the-art open-source OCR Tesseract can not output sensible html, and this means perhaps the OCR we have today is not a solution to conversion of structured documents e.g. from pdf to markdown.

Disclaimer: This is my impression so far, and I may need to do more research to confirm it.
