### ISSUE TITLE
--css doesn't include MIME-type when using pandoc 2.5?

### ISSUE THREAD

**Issue by caroline-lin** [jgm/pandoc#5206]
## The issue
When I pass pandoc 2.5 the `--css` flag and format from Markdown -> HTML, the resulting HTML doesn't include the MIME-type of the included css.

## Example

`pandoc --css style.css index.md -o index.html`

will produce an HTML file which uses

`<link rel="stylesheet" href="style.css" />`

to include the CSS instead of 

`<link rel="stylesheet" href="style.css" type="text/css" />`

Interestingly, pandoc 1.19.2.4 (on my personal computer) does add the MIME type when `--css` is used.

## Why this is an issue
Not including the MIME type in index.html resulted in chrome not being able to render my statically-served, pandoc-generated webpages with CSS. :(

**Comment by jgm** [comment]
See the discussion in #5146 which prompted this change.
The type is supposed to be optional for link elements, according to the HTML5 spec.  It isn't needed to validate.  What doctype is used in your index.html?  (You don't include `-s` or `--template` on your command line -- is that intentional?  If not, try with `-s` to get a standalone HTML document.)

**Comment by caroline-lin** [comment]
Yes, the lack of `-s` was intentional (although it doesn't really matter either way for what I'm using it for).

I don't think my issue was caused by the lack of type tag after all--it has to do with the fact that the stylesheet is named `pandoc.css`.

For whatever reason:

1. Renaming `pandoc.css` to something like `temp.css` causes styling to work;
2. Removing `<meta name="generator" content="pandoc />` from the generated HTML causes styling to work;
3. Changing the content field of the meta tag above to something else causes styling to work.

All of the above work regardless of if the type field is included.

**Comment by jgm** [comment]
None of the changes you described could possibly make a difference here, as far as I can see.
Can you provide a full minimal example we can test with?  (markdown input, css file, exact pandoc command used)

**Comment by jgm** [comment]
Without more information, we'll have to close this.  But feel free to submit a working example so we can look into it.
