### ISSUE TITLE
specifying hypperref forms spanning multiple markdown sections

### ISSUE THREAD

**Issue by biocyberman** [jgm/pandoc#5209]
I asked on [stackexchange](https://tex.stackexchange.com/questions/469380/hyperref-form-spanning-multiple-markdown-sections) but decided to post a bug report because I think this is rather a pandoc's bug or incomplete support to hyperref forms. I am testing with pandoc on macOS Mojave 

```
pandoc -v 
pandoc 2.3.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1.1, skylighting 0.7.3
```
## This works:

```markdown
---
title: "Test Latex Form"
geometry: "left=2.5cm,right=2cm,top=2cm,bottom=2cm"
output: pdf_document
header-includes:
    - \usepackage{hyperref}
    - \usepackage{datetime}
    - \usepackage{xcolor}   
---

# Overview

\begin{Form}
\TextField[name=Title, width=0.87\textwidth, bordercolor=black, value = {Some default value}]{Title:}
\end{Form}
## A heading

and some texts
```

## But this doesn't
```markdown
---
title: "Test Latex Form"
geometry: "left=2.5cm,right=2cm,top=2cm,bottom=2cm"
output: pdf_document
header-includes:
    - \usepackage{hyperref}
    - \usepackage{datetime}
    - \usepackage{xcolor}   
---

# Overview

\begin{Form}
\TextField[name=Title, width=0.87\textwidth, bordercolor=black, value = {Some default value}]{Title:}

## A heading:
* Some markdown syntax here*

\TextField[name=field1, width=\hsize, bordercolor=black, value = {}]{}

## Another heading:
*And form field below*

\TextField[name=field2, width=\hsize, bordercolor=black, value = {}]{}
\end{Form}
```
it *seems* to work when omitting `begin{Form}` and `end{Form}` completely like many others do. But actually the resulting PDF file has mal-formed forms. The form fields do not show up correctly, and some readers (i.e. evince) does not understand and let users to fill the form. 

A possible (ugly and not logically correct) is to turn all fields in to a separate form: 

```markdown
\begin{Form}
\TextField[name=field1, width=\hsize, bordercolor=black, value = {}]{}
\end{Form}
## Another heading:
*And form field below*

\begin{Form}
\TextField[name=field2, width=\hsize, bordercolor=black, value = {}]{}
\end{Form}
```

**Comment by jgm** [comment]
If I understand you correctly, you want to insert some raw LaTeX in your markdown file.

The best way to do this (particularly with begin/end environments that have markdown between them) is to use raw blocks:

````
# Overview

```{=latex}
\begin{Form}
\TextField[name=Title, width=0.87\textwidth, bordercolor=black, value = {Some default value}]{Title:}
```

## A heading:
* Some markdown syntax here*

```{=latex}
\TextField[name=field1, width=\hsize, bordercolor=black, value = {}]{}
```

## Another heading:
*And form field below*

```{=latex}
\TextField[name=field2, width=\hsize, bordercolor=black, value = {}]{}
\end{Form}
```
````
You could get by with just using the raw blocks for `\begin{Form}` and `\end{Form}`, since pandoc should handle the `\TextField` command without it.  But it doesn't hurt to be explicit.

**Comment by biocyberman** [comment]
Salute!
Awesome, it works 😀  I read the manual about specifying `{=latex}` explicitly in the `header-includes` but did not understand that it would be used to place literal `latex` code at other places. I was fumbling with `$` and `$$` wrappers for latex formulas but they did not help. Long story short, here is the working version, which saves me from editing the form fields again.

```markdown
     ---
     title: "Test Latex Form"
     geometry: "left=2.5cm,right=2cm,top=2cm,bottom=2cm"
     output: pdf_document
     header-includes:
         - \usepackage{hyperref}
         - \usepackage{datetime}
         - \usepackage{xcolor}
     ---
     # Overview

      ```{=latex}
     \begin{Form}
     ```

     \TextField[name=Title, width=0.87\textwidth, bordercolor=black, value = {Some default value}]{Title:}

     ## A heading:
     * Some markdown syntax here*

     \TextField[name=field1, width=\hsize, bordercolor=black, value = {}]{}

     ## Another heading:
     *And form field below*

     \TextField[name=field2, width=\hsize, bordercolor=black, value = {}]{}

     ```{=latex}
     \end{Form}
      ```

```
I could not have figured all these out without you. Thanks.
