### ISSUE TITLE
Add support for PPTX blank newline on same page

### ISSUE THREAD

**Issue by GeekMasher** [jgm/pandoc#5210]
I want to convert some of my markdown content to PPTX (PowerPoint) but in some of the slides I want to add blank newline(s) between content to clearly separate paragraphs but keep the content on the same page.

I'm using `<br />` as the example but it could be anything else.

**Test cases:**
Please also check files below.

1. Single newline between paragraphs (correct)
    - Same line when converted
2. Two newlines between paragraphs (correct)
    - New paragraph
3. Added multiple `<br />` (on different newlines) to add multiple blank lines between content
    - This doesn't add any newlines (appends to previous line)
    - Seems like the `<br />` gets striped out.
4. Added `<br />` to add a newline in the content page
    - This also doesn't add newline (appends to previous line)

**Command used:**
```bash
pandoc -t pptx -f markdown -o example.pptx index.md
```

*Note:* I tried also adding `-f markdown+smart` but still doesn't work.

**File: index.md**
```markdown
# Here are my slides

## Here is some of my content
<!-- correct -->
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget lorem ac dui fermentum posuere nec quis velit. Suspendisse lobortis dictum dignissim.
Nulla vulputate, lacus ac aliquet viverra, arcu nulla ultricies lectus, at sagittis turpis enim vel ante.


Nullam et urna turpis. Maecenas feugiat ut felis a posuere. Curabitur maximus elit nec nisi tristique, vitae posuere odio varius. Maecenas in leo a urna euismod euismod.

## Second content slide
<!-- slide with the issues -->
In eget sollicitudin turpis, ac imperdiet felis.
Integer non purus vehicula, tempus elit imperdiet, volutpat mauris. In aliquet turpis eu vestibulum porttitor.
Phasellus efficitur aliquet pharetra. Quisque faucibus egestas pharetra. 
<br />
<br />
Duis lobortis odio arcu, a finibus ipsum volutpat ut.
<br />
Etiam diam nisl, bibendum eget dignissim eu, tristique nec lacus.
```

**Output files:**
- [example.pptx](https://github.com/jgm/pandoc/files/2745638/example.pptx) (original Pandoc output)
- [sample.pptx](https://github.com/jgm/pandoc/files/2745639/sample.pptx) (example of expected output)
    - Third slide is where the issue is

**Comment by mb21** [comment]
Pandoc markdown supports such linebreaks with this syntax:

```
foo\
\
\
bar
```

See https://pandoc.org/MANUAL.html#extension-escaped_line_breaks

**Comment by GeekMasher** [comment]
Hi @mb21,
You solution does work and thanks for helping me out with this. A `<br />` or other indicator would be great but this will do.
