### ISSUE TITLE
Org-mode: Conversion is still incomplete

### ISSUE THREAD

**Issue by eubarbosa** [jgm/pandoc#5216]
Hi,

I have a [project](https://github.com/eubarbosa/novels.org) to read classic novels using Emacs org-mode

I use Pandoc to convert from Epub to Org:

`pandoc book.epub -f epub -t org -s -o book.org`

Once completed, the issued org file has yet a lot of XML elements throughout the file as you can confirm here: https://gist.github.com/eubarbosa/951c7ff11babb5c1403c6d610964d7af

Thanks! 

----------------------
pandoc 2.2.1
Emacs 26.1
Org-mode 9.1.9
Debian SID

**Comment by jgm** [comment]
are you talking about things like `<<main4.xml#chapter_830>>`?
These aren't XML elements; they're org-mode internal link anchors.  See https://orgmode.org/manual/Internal-links.html.

So this isn't incomplete conversion; it's accurate conversion, the original document probably contained divs with these anchors.

If you want to get rid of them, you can use a simple lua filter to strip out the id attribute from every Div in the AST:

``` lua
function Div(el)
  el.identifier = ''
  return el
end
function Span(el)
  el.identifier = ''
  return el
end
```

Save this as `strip_ids.lua` and then use `--lua-filter strip_ids.lua` on your command line.

**Comment by eubarbosa** [comment]
Oh, ok. 

THanks for info!
