### ISSUE TITLE
Missing cli options in lua filter

### ISSUE THREAD

**Issue by hason** [jgm/pandoc#5221]
I want  to react to certain options (e.g. `--top-level-division`) in Lua filter. What about create a global variable `PANDOC_OPTIONS` for all options or `PANDOC_WRITER_OPTIONS` for options which were provided to the writer?

**Comment by tarleb** [comment]
Making writer options available to filters could be useful. We should probably do this for JSON filters as well as for Lua filters. JSON filters should be kept as powerful as Lua filters when possible.

**Comment by jgm** [comment]
If we do this, should we provide the raw argv strings or rather a structured Opt?

Note that Text.App.Opt.Opt provides Generic and ToJSON instances.
