### ISSUE TITLE
"ATTR_HTML" doesn't work for table width in converting org to docx

### ISSUE THREAD

**Issue by mgcyung** [jgm/pandoc#5222]
The org code is as follows

#+NAME: tab:1
#+CAPTION: test
#+ATTR_HTML: :width 400
|---------+------+--------|
|    test | this | is Not |
|---------+------+--------|
| chinese |    1 |      3 |
|    word |    2 |      4 |
|---------+------+--------|

**Comment by tarleb** [comment]
Thanks for the report. This is a known issue and due to current limitations of the pandoc AST, see #1024. I'm closing this in favor of that issue.
