### ISSUE TITLE
How to show top and bottom lines in a multiline table from org to docx

### ISSUE THREAD

**Issue by mgcyung** [jgm/pandoc#5223]

**Comment by mb21** [comment]
Note sure exactly what you're asking. But generally, you cannot do layouting with pandoc. See the MANUAL.

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by tarleb** [comment]
@mb21 I'm not sure pandoc-discuss is really an option here, as google groups [seems to be blocked](https://viewdns.info/chinesefirewall/?domain=groups.google.com) by the Great Firewall.

**Comment by mgcyung** [comment]
The exact case is that there are two tables in a orgmode file. The
first has one horizonal line. The second has three horizonal lines.

#+NAME: tab:1
#+CAPTION: test
| test    | this | is Not |
|---------+------+--------|
| chinese |    1 |      3 |
| word    |    2 |      4 |


#+NAME: tab:2
#+CAPTION: test
|---------+------+--------|
| test    | this | is Not |
|---------+------+--------|
| chinese |    1 |      3 |
| word    |    2 |      4 |
|---------+------+--------|

When it is exported to latex/pdf by org-export, there are one
horizonal line in the first table and three horizonal line in the
second table.

![pandoc-table-2](https://user-images.githubusercontent.com/16061518/51106412-a7875980-1826-11e9-9b7b-a49d6656288e.png)

However, when it is export to latex/pdf by pandoc, there are three
horizonal lines in both tables.

![pandoc-table-3](https://user-images.githubusercontent.com/16061518/51106434-b706a280-1826-11e9-9535-f5c872f35186.png)

When it is exported to docx by pandoc, there are only one horizonal
line in both tables.

![pandoc-table-1](https://user-images.githubusercontent.com/16061518/51106450-c7b71880-1826-11e9-885a-05dffe2ac343.png)

**Comment by mb21** [comment]
@tarleb but Github is [blocked as well](https://viewdns.info/chinesefirewall/?domain=github.com) :P 

@mgcyung this is a limitation of pandoc. From the MANUAL:

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size. And some document elements, such as complex tables, may not fit into pandoc’s simple document model. While conversions from pandoc’s Markdown to all formats aspire to be perfect, conversions from formats more expressive than pandoc’s Markdown can be expected to be lossy.
