### ISSUE TITLE
Chapter title in YAML front matter [feature request]

### ISSUE THREAD

**Issue by sjackman** [jgm/pandoc#5226]
I have one chapter in each Markdown file. Each file has a YAML front-matter block with a `title` element for the chapter title. Sections titles use Markdown `#`. I'm rendering this with `pandoc -o thesis.pdf chapter1.md chapter2.md chapter3.md`. This doesn't currently work. The `title` of each file (except the first) is ignored. Any chance it could work?

The workaround is straight forward enough. I'll need to change all the `#` to `##` and so on. It'd be a nice feature though, for writing books and larger reports, if you're up for it. Feel free to close this issue if not.

**Comment by mb21** [comment]
From the MANUAL:

> If multiple input files are given, pandoc will concatenate them all (with blank lines between them) before parsing.

This is not easy to change at all. The way pandoc is implemented is that it takes exactly one input document (with one metadata set, where the title is stored) and produces one output document. Thus closing.

**Comment by tarleb** [comment]
The only way to make this work would be to write some wrapper script or, my favorite, a pandoc filter.

For a filter, you'd have to pass the input files as somewhere in the metadata, `--metadata chapter_files=chapter1.md,chapter2.md,chapter3.md`, then use `pandoc.read` on the contents of these files and modify and merge the documents as you see fit. Not a trivial script though.

See https://pandoc.org/lua-filters.html

**Comment by sjackman** [comment]
Here's my sed script to merge multiple chapters into a single Markdown document. It retains the first YAML block. `title:` of each chapter becomes `#`. Then `#` becomes `##` and so on.

```sh
gsed -E \
	-e '1,/^---/b' \
	-e 's/^#/##/' \
	-e 's/^title: "(.*)"/# \1/' \
	-e '/^author:/,/^---/d' \
	-e '/^## References/d' \
	-e '/^---/d' frontmatter.md chapter1.md chapter2.md chapter3.md >book.md
```

**Comment by jgm** [comment]
The best way to do this is to use level-1 headers '#'
for chapters, level-2 '##' for sections.   Then use
--top-level-division=chapter on the command line.

To convert what you have to that format, you could
use a filter, but it's probably easier just to
do it manually unless you have tons of chapters.
