### ISSUE TITLE
Reduce runs for LaTeX

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#5228]
The PDF creation function runs LaTeX a fixed number of times to ensure everything comes out correctly.

<https://github.com/jgm/pandoc/blob/4dddfbc4351cfa267946210c9aea59adbaa62f3b/src/Text/Pandoc/PDF.hs#L270> 

This is overkill for the majority of documents, many of which could be completed in one or two runs. The venerable [`latexmk`](https://ctan.org/pkg/latexmk) searches the log for strings such as `Rerun to get` (you'll see a series of regular expressions in the [Perl source](https://ctan.org/tex-archive/support/latexmk) if you search for that phrase). Could pandoc take this approach as well, or would that add too much complexity?

**Comment by mb21** [comment]
We've had problems with not running latex enough times in the past... so I would caution against that. If you really need the performance, I suppose using `-t latex` and piping to latexmk or whatever is your best bet.

**Comment by adunning** [comment]
It's not a problem for me personally: I certainly do that already. When using LuaLaTeX, however, PDF generation can sometimes take a minute or two, which isn't ideal for new users.

Earlier versions of the code guessed the needed number of runs based on the arguments, e.g. whether or not a table of contents was present. The `latexmk` technique of scanning for strings, however, should be much more reliable; it's just a question of whether it belongs here.

**Comment by jgm** [comment]
A long time ago we did actually parse the logs and try
to figure out when additional runs were needed.

I can't now recall why I gave that up, but git log
reveals:

commit acdbdd7da575f94e6fd326879fd8632edc9dd9cd
Author: John MacFarlane <fiddlosopher@gmail.com>
Date:   Mon Feb 6 12:12:23 2012 -0800

    Text.Pandoc.PDF:  Simplified tex2pdf.
    
    We no longer try to parse the log file to determine whether latex
    needs to be rerun. Instead, we run latex twice -- which should be
    enough for table of contents and hyperrefs.
    
    Closes #402.

I believe the issue was that my log-parsing code
wasn't detecting all the reasons for additional runs.
As I recall, there may have been variation among
different latex versions in the messages.

We could always reconsider this.

**Comment by dbosk** [comment]
If `pdflatex` exists on the system, how less likely is it that `latexmk` exists? Does `pandoc` ensure the existence of `pdflatex` in some way?

Isn't `latexmk` included in the default installation of TeXLive? At least Ubuntu has a package for `latexmk`.

It seems like [Windows users (MikTeX) must install `latexmk` and Perl manually](https://github.com/thomasjo/atom-latex/wiki/Using-latexmk-with-MiKTeX) though.

**Comment by mb21** [comment]
@adunning If you think you can pull it off and want to submit a pull requests, go for it :-)

**Comment by adunning** [comment]
It might be another month or two before I can finish it, but I'll definitely give it a go if there is no disagreement on the principle of it.

**Comment by dbosk** [comment]
Sounds great to me! :-)

**Comment by jgm** [comment]
Andrew Dunning <notifications@github.com> writes:

> It might be another month or two before I can finish it, but I'll definitely give it a go if there is no disagreement on the principle of it.

OK with me!

**Comment by jgm** [comment]
See #3195

**Comment by adunning** [comment]
Yes, simply adopting latexmk outright would certainly be another approach!

**Comment by dbosk** [comment]
The advantage of that is that we benefit from any updates to latexmk without having to sync pandoc code.

**Comment by jgm** [comment]
`latexmk` is now a valid option for `--pdf-engine`.
