### ISSUE TITLE
FB2 output: support for explicit header identifiers

### ISSUE THREAD

**Issue by KetzerX** [jgm/pandoc#5229]
It would be good to have a possibility to set explicit identifier for header (and produce section element with that id), as now it is ignored. Although footnote produces correct section element with id.

## the pandoc version

pandoc 2.5

## the exact command line used

pandoc -s -o test.fb2 test.md

## the exact input used

```
# Section 1

Footnote[^f1]

[^f1]: my footnote

My link [link](#l1)

# Section 2 {#l1}

Section text
```

## the output received

(added newlines for readability)

```
<?xml version="1.0" encoding="UTF-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
<description><title-info><genre>unrecognised</genre></title-info>
<document-info><program-used>pandoc</program-used></document-info>
</description>
<body><title><p /></title>
<section><title><p>Section 1</p></title>
<p>Footnote<a l:href="#n1" type="note"><sup>[1]</sup></a></p>
<p>My link <a l:href="#l1">link</a></p></section>
<section><title><p>Section 2</p></title><p>Section text</p></section></body>
<body name="notes">
<section id="n1"><title><p>1</p></title><p>my footnote</p></section>
</body></FictionBook>
```

As we can see id is set only to footnotes section: `<section id="n1">`

## the output you expected instead

```
<?xml version="1.0" encoding="UTF-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
<description><title-info><genre>unrecognised</genre></title-info>
<document-info><program-used>pandoc</program-used></document-info>
</description>
<body><title><p /></title>
<section><title><p>Section 1</p></title>
<p>Footnote<a l:href="#n1" type="note"><sup>[1]</sup></a></p>
<p>My link <a l:href="#l1">link</a></p></section>
<section id="l1"><title><p>Section 2</p></title><p>Section text</p></section></body>
<body name="notes">
<section id="n1"><title><p>1</p></title><p>my footnote</p></section>
</body></FictionBook>
```
Id for section 2 should be set also `<section id="l1"><title><p>Section 2</p>...`

As we can see footnote produces correct section with id and link works. Explicit link creates only correct link element, but there are no target as section id is not set.

Also it would be good to have opportunity to return raw content for fb2 (as it is xml-based format). Now they are also ignored.

Related discussion: https://groups.google.com/forum/#!msg/pandoc-discuss/2PaMBfNmz_0/TkDJjMUhAgAJ

**Comment by jgm** [comment]
While we're at it, it would be worth replacing the custom `splitSections` with `hierarchialize` from T.P.Shared.  This provides Sec structures that contain the identifier, which can then be used in `renderSection`.

Including raw content would be easy -- see how this is done in the DocBook writer, for example.
