### ISSUE TITLE
Hackage documentation for 2.5 is missing.

### ISSUE THREAD

**Issue by wizzup** [jgm/pandoc#5232]
https://hackage.haskell.org/package/pandoc

**Comment by jgm** [comment]
The logs show the builds failing at the end for unknown reasons.
I tried to upload haddocks manually, but the server
gave me an inscrutable error.  Maybe bring this up
with Hackage maintainers?

**Comment by jgm** [comment]
Triggered a rebuild and now I see this in the logs:
```
  18% (  2 / 11) in 'Text.Pandoc.Writers.OOXML'
  Missing documentation for:
    mknode (src/Text/Pandoc/Writers/OOXML.hs:54)
    nodename (src/Text/Pandoc/Writers/OOXML.hs:58)
    toLazy (src/Text/Pandoc/Writers/OOXML.hs:64)
    renderXml (src/Text/Pandoc/Writers/OOXML.hs:67)
    parseXml (src/Text/Pandoc/Writers/OOXML.hs:71)
    elemToNameSpaces (src/Text/Pan/tmp/ghc16637_0/ghc_862.s: Assembler messages:
/tmp/ghc16637_0/ghc_862.s: Fatal error: can't close /tmp/ghc16637_0/ghc_164.dyn_o: No space left on device
doc/Writers/OOXML.hs:87)
```
So this is a hackage infrastructure issue, not a pandoc issue. It would be good to report it to hackage devs.

**Comment by jgm** [comment]
Submitted https://github.com/haskell/hackage-server/issues/808

**Comment by jgm** [comment]
The docs are back!
