### ISSUE TITLE
build pandoc-crossref together with pandoc

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#5239]
There is a nice Pandoc filter: [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref). But unfortunately at the moment the main developer cannot dedicate a lot of time and there are bugs in compiling binaries for macOS and Linux.

Is it possible to add building of the pandoc-crossref to Pandoc automatic building toolchain? Or is there a way to fork it fast so even me that is not familiar with Haskell at all could tweak it.

**Comment by mb21** [comment]
>  there are bugs in compiling binaries for macOS and Linux.

What do you mean? Have you raised this as an issue on the pandoc-crossref repo? They even provide binaries for macOS and Linux: https://github.com/lierdakil/pandoc-crossref/releases

Generally, pandoc is becoming more and more powerful every year. So maybe in a couple of years, you won't need the filter any more...

**Comment by kiwi0fruit** [comment]
Sure. See the end of the https://github.com/lierdakil/pandoc-crossref/issues/213

**Comment by mb21** [comment]
There's really nothing for pandoc to do here.
I commented on the linked issue.
