### ISSUE TITLE
Feature Request: --template  url 

### ISSUE THREAD

**Issue by SylvainGuieu** [jgm/pandoc#5246]
Currently only a local file can be parsed to --template option. however --css accept url as well as input files. 
It would be great if `--template http://colabwebsite/mdtemplate/tehcnotes.tex` exists 
so in a scope of a collaborative project anybody can use the appropriate up-to-date project template. 

Is their any security issue into this ?

**Comment by jgm** [comment]
You can already do this (since pandoc 2.2.2).
