### ISSUE TITLE
In EPUB3, some math characters are displayed as empty rectangles

### ISSUE THREAD

**Issue by aburkov** [jgm/pandoc#5250]
$ pandoc --version
pandoc 2.3.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.2

On Android in EPUB3 books generated from markdown, many characters such as $\mathbf{x}$ or Greek characters such as $\theta$ are displayed as empty rectangles. It doesn't depend on readers: I observed the same problem is multiple of them. Try Kobo for example.

There's no such a problem on iOS or Mac (in iBooks reader for example).

At Kobo, they suggested to embed fonts into the EPUB file, but I don't know which font to embed. Do you have an idea how to fix that?

**Comment by jgm** [comment]
You can use --epub-embed-font=FILE with pandoc.
I'm not sure, either, which font to embed...
Maybe someone else here can help.

**Comment by mb21** [comment]
Does the kobo support MathML? see http://pandoc.org/epub.html#math

If it's really the font, maybe ask on [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss)...

**Comment by aburkov** [comment]
Kobo was just an example. I tried **all** e-book reading apps for Android. Those that support MathML all have this problem.

**Comment by mb21** [comment]
Maybe try [STIX](https://www.stixfonts.org/) and [Ubuntu Mono](https://design.ubuntu.com/font/#charset-mono-regular).

**Comment by aburkov** [comment]
STIX are otf fonts.  Pandoc needs ttf.

This is definitely a bug of Pandoc: the same book works on iOS/Mac and doesn't work on Android. If not fixing the bug, at least could you provide instructions as for what to do with EPUB3 that contain MathML generated from LaTeX equations in markdown?

**Comment by jgm** [comment]
Pandoc can embed otf fonts, too, as far as I know...

**Comment by mb21** [comment]
From https://github.com/kobolabs/epub-spec#supported-fonts

> TTF, OTF, and WOFF (v. 1.0) fonts are supported by all Kobo platforms.

so you should be fine. have you tried it?

> This is definitely a bug of Pandoc

I don't think so. It's not in the project's scope to anticipate all ebook readers and embed fallback fonts for them.

> at least could you

Pandoc is run by volunteers in our spare time... you are welcome.

**Comment by aburkov** [comment]
> It's not in the project's scope to anticipate all ebook readers and embed fallback fonts for them

Oh, supporting e-book readers on the most popular mobile OS is not project's scope? Are you sure we talk about pandoc? Because the below doesn't work in none Android reader for a bunch of standard LaTeX math characters:

> [LaTeX math](https://pandoc.org/) (and even macros) can be used in markdown documents. Several different methods of rendering math in HTML are provided, including MathJax and translation to MathML. LaTeX math is converted (as needed by the output format) to unicode, native Word equation objects, MathML, or roff eqn.

> Pandoc is run by volunteers in our spare time

And the work of those volunteers is very appreciated. However it doesn't change the fact that a bug is a bug.

**Comment by jgm** [comment]
@aburkov can you explain why you say that pandoc doesn't support embedding otf fonts?

**Comment by aburkov** [comment]
Not sure how my answer will help to fix the bug, but I read the doc: https://pandoc.org/MANUAL.html and didn't find any reference to OTF there. Maybe there are other docs and I didn't see them, then my bad. I just cannot figure out what exactly I have to include in my EPUB for the math to start working in my pandoc-generated e-book on Android. And unfortunately, instead of actually trying to help I'm getting lectured that it's the work of volunteers and I'm not being thankful.

I'm thankful, I really am. But how that helps in solving the problem?

**Comment by jgm** [comment]
Well, why don't you try embedding the stix fonts, as suggested above?  Unfortunately I don't have an android device, so I'm limited in what I can do to test and diagnose this.  You should start with the most minimal test case you can, and try embedding the stix fonts to see if that helps.  You'll also need some custom css as noted in the manual.

**Comment by aburkov** [comment]
Ok, I'll try embedding all STIX fonts and let you know if it worked!

**Comment by jgm** [comment]
Also, did you look at the list here http://docs.mathjax.org/en/latest/misc/epub.html to see whether the specific ebook programs you're using really do support mathml in epub3? In my experience, not many do -- and some that claim to do so very poorly.

**Comment by aburkov** [comment]
I actually spent several hours and tried all (I mean all) e-book reading apps for Android. As you say, most don't support MathML at all. Those that support, all have this problem: many unsupported math characters, but the equations overall look good. It has to be a missing font on Android. But which one and how to make the book use it, I cannot understand: unfortunately, text file formats is not my field of expertise.

**Comment by jgm** [comment]
Yes, it does sound like a font issue.  But I don't think we have evidence yet that there is any bug in pandoc -- it could be a limitation with the fonts bundled with these readers.  Here's what I'd suggest:

- Ask for help on pandoc-discuss. There are others there with lots of experience producing ebooks with pandoc, embedding fonts, etc.
- Find an epub3 with mathml that actually displays properly on your reader.  Then unpack it (with unzip) and inspect the contents, comparing with the one pandoc produces.  Look at the CSS it contains (in particular, any parts relating to fonts), and the fonts, if any, it embeds.

It may turn out that there's a problem with pandoc. If so, you can raise an issue on this tracker with the information we need to do something about it.  But it may also turn out that you simply need to embed the right fonts and add some CSS to tell the reader to use them.

**Comment by aburkov** [comment]
Maybe someone will find [the book](http://themlbook.com) interesting enough to actually try to solve the problem? :-)

**Comment by link2xt** [comment]
I have created a file `1.md` with `$\theta$` and converted it to EPUB3:
```
$ pandoc 1.md -o 1.epub -t epub3 --mathml -s
```

It displays theta in [Cool Reader](https://play.google.com/store/apps/details?id=org.coolreader) and theta with `\theta` string in [FBReader](https://play.google.com/store/apps/details?id=org.geometerplus.zlibrary.ui.android), no empty rectangles.

**Comment by aburkov** [comment]
That strange. These two readers don't display MathML at all for me. FBReader displays raw LaTeX, Cool Reader displays something completely ugly and unreadable.

- What's your Android version/Phone model?
- Can I send you the book and so you can check if all math characters are rendered OK and take a couple of screenshots?

**Comment by link2xt** [comment]
According to https://docs.mathjax.org/en/latest/misc/epub.html FBReader and Cool reader don't actually support MathML. I have successfully displayed your example with [IDEAL Group Reader](https://play.google.com/store/apps/details?id=org.easyaccess.epubreader), which downloads MathJax in the background the first time it encounters a math formula.

I don't think there are any problems with MathML in pandoc, but most EPUB readers don't support it or require you to be online. I suggest that you use one of the options that convert math to images, such as `--webtex` or `--gladtex`, instead.

**Comment by aburkov** [comment]
Buy the way, in IDEAL Group Reader, there's another problem. Images inserted this way:

`![An example of an SVM model for two-dimensional feature vectors.](Illustrations/SVM.png){#fig:svm}`

Are rendered huge (wider than phone screen width), while the text's width is about 20% of the screen width and you cannot make it wider. I never saw something like this in other readers.

**Comment by link2xt** [comment]
> If we cannot fix Android, can we simplify the epub3 book creation process for pandoc users by letting then embed the right fonts the right way?

I think we have narrowed the problem down to displaying the https://www.compart.com/en/unicode/U+1D431 character in EPUB3 readers. @aburkov Can you confirm that if you create a document with this character, without any math at all, and convert it to EPUB3, it displays this character as a rectangle? What reader do you use to reproduce this bug? Then, doesn't `--epub-embed-font` solve the problem?

I want to decouple MathML problems from this discussion, because the problem is not only with the fonts. The problem is that many popular Android readers, such as FBReader and Cool Reader, don't support MathML at all. And `pandoc` uses MathML for EPUB3 unconditionally:
https://github.com/jgm/pandoc/blob/2932ac8574e79d5d5b3b65ed81b0125d4d146f12/src/Text/Pandoc/Writers/EPUB.hs#L460-L462 I think we need a way to switch EPUB3 math to plain math mode used in HTML by default. I will open a separate bug for this.

**Comment by aburkov** [comment]
I just tried in four readers that support EPUB3 and MathML:

In Kobo, $\mathbf{x}$ and "𝐱" are both rendered as [].

PocketBook reader, Gitden Reader, and Infinity Reader render $\mathbf{x}$ and most other math characters well. 𝐱 is rendered as [].

PocketBook reader, Gitden Reader, and Infinity Reader, however, all have a problem with $\mathbf{\theta}$ or $\bm{\sigma}$ which they render as [].

**Comment by link2xt** [comment]
@aburkov 
Your example becomes
```
<p><span class="math inline">{(<strong>x</strong><sub><em>i</em></sub>, <em>y</em><sub><em>i</em></sub>)}<sub><em>i</em> = 1</sub><sup><em>N</em></sup></span></p>
```
in plain math mode.

**Comment by aburkov** [comment]
Ok, and what will happen to the MathML equations that use those characters?
