### ISSUE TITLE
SVG text disappearing in HTML

### ISSUE THREAD

**Issue by anishmittal2020** [jgm/pandoc#5253]
```bash
$ pandoc -v
pandoc 2.5
```

```markdown
# Markdown file
![Online](https://upload.wikimedia.org/wikipedia/commons/1/14/Window_%28windowing_system%29.svg)

![Offline](Image/Image_Window_(windowing_system).svg)
```
```bash
# Bash
pandoc Input.md -o Output.html
```

The html includes both the images, but the text inside svg is not rendered. But with the context menu on the svg inside the html, when I open it in  new tab the labels are displayed in the image.

---

The way svg is getting rendered:

![The way svg is getting rendered](https://user-images.githubusercontent.com/42092626/51799741-75fa8f00-2225-11e9-8dd4-90a0e886430f.png)

Actual svg:

![Actual svg](https://user-images.githubusercontent.com/42092626/51799750-91fe3080-2225-11e9-9bfb-27a4fb3c3658.png)

**Comment by mb21** [comment]
Anyway, closing this since this has nothing to do with pandoc. You'll need to fix the svg file.

Feel free to ask future question on the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss). Thanks!
