### ISSUE TITLE
From markdown to markdown: yaml metadata removed

### ISSUE THREAD

**Issue by TiBeN** [jgm/pandoc#5257]
Hi, 
I use the following command:

    $ pandoc -t markdown -f markdown

to format my markdown files which i find pretty handy (Result looks nice).
The issue is YAML header metadatas are removed from the source file.

Pandoc v1.19.2.4, installed on an Ubuntu 18.04 via Ubuntu repositories (APT)

**Comment by agusmba** [comment]
Did you try with `-s`?

**Comment by mb21** [comment]
you should also use the newest pandoc version: http://pandoc.org/installing.html

**Comment by TiBeN** [comment]
Oh, thanks and sorry, i was not aware of this option. YAML metadata are keeped using it. 

Now there is a "true" in the top of the final document between YAML metadatas and the beginning of the content of the document. Like this

     ---
     yaml content
     ---

     true

     Title document
     ============

But this is another issue, i'll do some search about that. 

This one is solved thank you

**Comment by mb21** [comment]
Probably a variable being printed in the template. See http://pandoc.org/MANUAL.html#templates and specifically the output of:

    pandoc -D markdown

**Comment by TiBeN** [comment]
Ok i found the culprit which was `toc: true` in YAML metadata. This variable is displayed in Markdown template. I replaced it by `--table-of-content` cli arg. 

Thanks :)
