### ISSUE TITLE
Separate template variable for references

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#526]
Currently the list of references is part of the document body (replacing the 'body' variable in the template). It might make more sense to have a separate 'references' variable.  This would mean that the list of references would not be included in a fragment, but I think that is probably what is wanted anyway.  This change would give more flexibility in styling the references.

On the other hand:  if we ever added a pandoc-markdown construct that works like '\thebibliography' (i.e., insert the bibliography here), then the references would need to stay in the body.  Not sure what the best path is here.

**Comment by jranke** [comment]
Any news on this? Would be a really cool feature!
