### ISSUE TITLE
LaTeX parser not parsing siunitx commands inside math env

### ISSUE THREAD

**Issue by cristobaltapia** [jgm/pandoc#5262]
Hi,
I am using pandoc to convert a `tex` file into a `docx` file. Everything works correctly, including `stunitx` commands, except for the cases when I have a `stunitx` command within an equation environment (like `$...$`).
In that case I get the following warning message:

```
[WARNING] Could not convert TeX math 't=\SI{20}{mm}', rendering as TeX:
  t=\SI{20}{mm}
       ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
```

I am using pandoc 2.5, installed with the `deb` file in the release page of the github repo.

**Comment by jgm** [comment]
Right.  Pandoc's LaTeX reader has support for siunitx,
but for math conversions, pandoc hands things off to the texmath
library, which doesn't.

As a workaround, you could add macro definitions for
teh stunix commands you use to your tex file; pandoc
will interpret them prior to passing things to
texmath.

You can also add an issue to jgm/texmath requesting
support for siunitx commands.

**Comment by cristobaltapia** [comment]
Thanks for your answer! I think I will add an issue to jgm/texmath.
