### ISSUE TITLE
Html to docs

### ISSUE THREAD

**Issue by sidharthsahu** [jgm/pandoc#5264]
I have a html with text,paragraph,ul, li ,tables , images tags.
Need to generate a doc from the data
Format
----Cover page
----header with text
----footers with page numbers
---TOC with level 1 and 2 with page number
---custom font family
and page orientation.
Can all these above be achieved using pandoc ?
 Any sample will be appreciable.

**Comment by mb21** [comment]
Probably yes. See http://pandoc.org/MANUAL.html

For questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
