### ISSUE TITLE
Conversion to tex fails when escaped $ character included in tex template

### ISSUE THREAD

**Issue by ml-evs** [jgm/pandoc#5266]
I'm having some issues using the latest pandoc to convert to tex, with some extra LaTeX listings options. The aim is to tell listings to treat lines that would correspond to user-input to a shell i.e. "$ blah" as comments, and recolour them.

First things first, pandoc compiled from source with stack from the current 
```
$ git rev-parse HEAD
e752669e50815b0c1bef62fc5b1de95c33317f89

$ pandoc --version
pandoc 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5
```

For the following MWE:
```
    $ cat mwe.md 
    # MWE for $ chars inside latex listings options
    ```
     $ pandoc --version
    pandoc 2.6
    Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5
    ```
```
with the .tex template as default, apart from the additional lines:

```
$ pandoc -D latex >> template.tex; diff mwe_template.tex template.tex 
382,387d381
< \lstset{
<   mathescape=false,
<   morecomment=[l]{\$},
<   commentstyle=\color{red},
< }
```
Running this through pandoc yields the following crash.
```
$ pandoc --verbose --listings --template mwe_template.tex -o mwe.tex mwe.md 
"template" (line 384, column 21):
unexpected "}"
expecting letter
```
Even commenting out the "morecomment" line above leads to the same crash. This only seems to be the case for $, I can happily escape % and use that to signify a comment.

If instead, the extra settings are added after pandoc has made the tex, the LaTeX works as expected:

![2019-02-01-152157_622x134_scrot](https://user-images.githubusercontent.com/7916000/52131686-44befc00-2635-11e9-8d60-c33a9432b262.png)

Love pandoc, so happy to assist in any way I can.

**Comment by jgm** [comment]
```
<   morecomment=[l]{\$},
```
See Templates documentation.  To insert a literal `$`, you need to escape it as `$$`.  So, what you want is:
```
<   morecomment=[l]{$$},
```

**Comment by ml-evs** [comment]
I missed that line in the docs, apologies. Thanks for getting back to me.
