### ISSUE TITLE
--metadata-file does not read LineBlock content (|)

### ISSUE THREAD

**Issue by msprev** [jgm/pandoc#5272]
```
lines: |
  | line1
  | line2
```

If this appears inside a standard YAML metadata frontmatter block, the content is (correctly) interpreted as:

```
[LineBlock [[Str "line1"],[Str "line2"]]]
```

However, if `lines` appears in a separate yaml file imported via `--metadata-file`, it is interpreted as:

```
[Plain [Str "|",Space,Str "line1",SoftBreak,Str "|",Space,Str "line2"]]
```

`--metadata-file` does not seem to be reading `LineBlock` content

**Comment by mb21** [comment]
Indeed. That's weird, since both pathways use the same [`yamlToMeta`](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/Markdown.hs#L252) function...

**Comment by mb21** [comment]
Ah, I have the suspicious that the `def` in https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/Markdown.hs#L257 might not enable the default pandoc-markdown extensions but no extensions?

**Comment by jgm** [comment]
This should be fixed now.
