### ISSUE TITLE
Does Pandoc binaries from github on Linux need gmp and zlib to run?

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#5281]
I've noticed in the [conda-forge recipe of Pandoc](https://github.com/conda-forge/pandoc-feedstock/blob/master/recipe/meta.yaml) (that simply repackages Pandoc binaries from github) depends on gmp and zlib. So I'm curious whether they are needed or obsolete.

**Comment by jgm** [comment]
A normal build of pandoc will depend on these
libraries.  The linux binaries we supply are
statically linked and do not depend on any dynamic libraries.

**Comment by kiwi0fruit** [comment]
Thanks!
