### ISSUE TITLE
Support for -f textile+tex_math_dollars

### ISSUE THREAD

**Issue by v217** [jgm/pandoc#5282]
`pandoc 2.6, Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5`

Reading through https://textile-lang.com specs, I think there should be no conflicts.

**Comment by mb21** [comment]
Can you give an example of sample input, expected output?

**Comment by v217** [comment]
for example using `pandoc -f textile+tex_math_dollars -t html5`

    h2(#id_h2). Chapter 4
    
    paragraph text $\sum\alpha\Phi$`

should render to

    <h2 id=id_h2>Chapter 4</h2>h2>
    <p>paragraph text <span class="math inline">∑αβ</span> </p>

Note that the textile markup for ids and attributes for tex_math_dollars is not really needed, because you can easily apply the attributes to the paragraph.

**Comment by mb21** [comment]
I cannot find this syntax on https://textile-lang.com... are you proposing pandoc should implement a non-standard textile dialect? Also, what would happen to more complex math like `$\sqrt{x^2+y^2}$`?

Current behaviour is to pass through the dollars and backslashes to the HTML, which seems sensible if you want to render the HTML with MathJax, as described in e.g. [Writing Mathematics with Textile and MathJax](http://blog.felixbreuer.net/2010/03/19/writing-math.html).

**Comment by jgm** [comment]
If you were going from textile to LaTeX (rather than HTML), it would be important to have the math recognized as such, or the $s and other special characters would be escaped.  So that is one reason for doing this, I suppose.

**Comment by v217** [comment]
I am not sure anymore if support for `tex_math_dollars` is really necessary for textile, because of katex's autorender script etc..., so I am closing this issue.
