### ISSUE TITLE
Support for math attributes in markdown

### ISSUE THREAD

**Issue by v217** [jgm/pandoc#5286]
`pandoc 2.6, Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5`

This does not work:
`$x^2${.class_colored #nr:3}`

To achieve the same right now, you have to use the extensions `bracketed spans` or `fenced divs`:
`[$x^2$]{.class_colored #nr:3}`

**Comment by mb21** [comment]
See https://github.com/jgm/pandoc/issues/684

**Comment by mb21** [comment]
Closing in favour of #684
