### ISSUE TITLE
Support the `subject` metadata variable when generating PDFs via LaTeX.

### ISSUE THREAD

**Issue by Wandmalfarbe** [jgm/pandoc#5288]
The [hyperref option `pdfsubject`](http://mirrors.ctan.org/macros/latex/contrib/hyperref/doc/manual.pdf) can be used to embed the value of the [metadata variable `subject`](https://pandoc.org/MANUAL.html#metadata-variables) into the generated PDF (when generating PDFs via LaTeX).

<img width="724" alt="screenshot 2019-02-09 20 55 50" src="https://user-images.githubusercontent.com/17237627/52525663-5f384b80-2cad-11e9-9b81-f051583d54b8.png">

**Comment by jgm** [comment]
Closed by PR #5289
