### ISSUE TITLE
ipynb: bibliography isn't generated

### ISSUE THREAD

**Issue by choldgraf** [jgm/pandoc#5295]
**Pandoc version: `2.6`**

I've been trying to get citations/bibliographies working with the markdown that's in an ipynb file, and I think I may have found a bug that prevents this from happening.

Here's some markdown with a citation inside:

```markdown
## Bibliography

Let's test the bibliography here

Testing this [bibliography @holdgraf_rapid_2016]

:::{#ref}
:::
```

If I run something like

```
pandoc bib_demo.md -o outputs/bib_demo.html --bibliography=references.bib
```

Then the HTML contains properly interpolated references as we'd expect.

If I put that markdown in an empty `.ipynb` file (as a markdown cell), then run 

```
pandoc bib_demo.ipynb -o outputs/bib_demo.html --bibliography=references.bib
```

Then the text is preserved literally (e.g. I see things like

```
<p>Testing this [bibliography @holdgraf_rapid_2016]</p>
```

Has anybody else experienced something like this? I can't think of a reason that it should work in "regular" markdown but not `.ipynb` markdown.

**Comment by jgm** [comment]
The ipynb reader does not enable the `citations` markdown extension by default -- it tries to match the extensions that are enabled in Jupyter notebooks.  (You don't see citations resolved there, do you?)

So to get the effect you want, you need to enable this explicitly by saying `-f ipynb+citations`.

**Comment by jgm** [comment]
Similarly, if you're converting from pandoc's markdown *to* ipynb, if you enable the citations extension with `-t ipynb+citations`, the ipynb markdown cells will contain things like `[@smith2000]`.  But if you don't enable the citations extension (the default), they will contain resolved citations (assuming you specified a bibliography and used pandoc-citeproc).

By the way, it's good practice to specify `--filter pandoc-citeproc` explicitly when you want citations resolved, even though (for backwards compatibility) pandoc does this automatically when you use `--bibliography` on the command line.

**Comment by choldgraf** [comment]
ah perfect, thanks for the clarification! I'm gonna write up a little exploration post so will include that in there! Will close this now

**Comment by jgm** [comment]
Chris Holdgraf <notifications@github.com> writes:

> ah perfect, thanks for the clarification! I'm gonna write up a little exploration post so will include that in there! Will close this now

I think I told you already about the bug in 2.6
regarding attachments.  I have been thinking about
putting out a new version fixing this and slightly
changing how output cells are handled...you might want
to wait til then for the exploration post.

**Comment by choldgraf** [comment]
sounds good, I'll hold off for a sec

**Comment by jgm** [comment]
OK, pandoc 2.7 is out; hopefully a more useable ipynb
reader and writer!

**Comment by choldgraf** [comment]
yahoo! will play around with it a bit more today. anything in particular I should be aware of?
