### ISSUE TITLE
ODT lists lose styling

### ISSUE THREAD

**Issue by alecgibson** [jgm/pandoc#5296]
I have a very simple ODT document (attached) generated in Open Office, which just contains this bulleted list with simple italic, bold and underline applied to the list items.

When I turn this into JSON, I get this output, which contains no styling at all:

```json
{
  "blocks": [
    {
      "t": "BulletList",
      "c": [
        [
          {
            "t": "Plain",
            "c": [
              {
                "t": "Str",
                "c": "A"
              }
            ]
          }
        ],
        [
          {
            "t": "Plain",
            "c": [
              {
                "t": "Str",
                "c": "B"
              }
            ]
          }
        ],
        [
          {
            "t": "Plain",
            "c": [
              {
                "t": "Str",
                "c": "C"
              }
            ]
          }
        ]
      ]
    }
  ],
  "pandoc-api-version": [
    1,
    17,
    5,
    4
  ],
  "meta": {}
}
```

I'm using Pandoc v2.6, and running:

```bash
pandoc --from=odt --to=json test.odt
```

[test.odt.zip](https://github.com/jgm/pandoc/files/2850942/test.odt.zip)

**Comment by mb21** [comment]
The relevant snippet extracted from `content.xml` from your odt file is:

         <text:list xml:id="list9096320000886234813" text:style-name="L1">
            <text:list-item>
               <text:p text:style-name="P1">A</text:p>
            </text:list-item>
            <text:list-item>
               <text:p text:style-name="P2">B</text:p>
            </text:list-item>
            <text:list-item>
               <text:p text:style-name="P3">C</text:p>
            </text:list-item>
         </text:list>

As you can see, the italics/bold/underline is only applied as styles there. That's why pandoc doesn't pick it up. And that's out-of-scope. From http://pandoc.org/MANUAL.html:

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size.

**Comment by alecgibson** [comment]
Aha, didn't spot that. What a shame. Thanks for clarifying.

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

> As you can see, the italics/bold/underline is only
> applied as styles there. That's why pandoc doesn't
> pick it up. And that's out-of-scope.

It's definitely not currently supported, but I'm not
sure it should be out of scope. After all, we could
have the odt reader parse the styles and take them
into account in parsing.

If desired, this could be opened up as a separate
enhancement request.

@MarLinn may want to comment on feasibility.
