### ISSUE TITLE
Couldn't parse odt file produced by FocusWriter

### ISSUE THREAD

**Issue by toonn** [jgm/pandoc#5297]
I've been getting some `.odt` files produced by FocusWriter and pandoc can't parse them. There's several closed issues which seem similar but were fixed. Are these just badly formatted `.odt`s or is this a bug?

```
> pandoc -f odt -t markdown -o lorem.md Lorem\ ipsum.odt 
Couldn't parse odt file.
```

Here's the version I'm running.
```
pandoc 2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.3
```

Here's an example file this happens with (added the `.txt` extension because github doesn't allow uploading of `.odt`): [Lorem ipsum.odt.txt](https://github.com/jgm/pandoc/files/2851868/Lorem.ipsum.odt.txt)

**Comment by mb21** [comment]
Works fine in pandoc 2.6

**Comment by toonn** [comment]
Yep, 2.5 works too, thanks. Was inconvenient to update because my repo didn't have newer versions. 👍
