### ISSUE TITLE
default language for codeblocks

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#53]
see the text below for a description of the enhancement, which i posted
recently to pandoc-discuss.

a diff is attached; please feel free to use/modify/ignore it.

note that i have not updated README to mention the new option

---

i love the new syntax-highlighting of codeblocks, but the one downside
for me is having to use delimited-codeblock sytax and the language
annotation for all my code snippets, where previously the indented-
code syntax was so simple and readable.

but it was easy (what nice code!) to add a --default-codeblock-class
option to pandoc, which is then used to populate a new writer option
that specifies the classes to use for a codeblock when none have been
specified (which is the result of an indentation-style codeblock).

now all my code is magically highlighted, without changing the
markdown at all!  (and for the rare case of code that shouldn't be
highlighted, i can use the delimited syntax to give some non-assigned
"language" like "ignore".) 

Google Code Info:
Issue #: 87
Author: butt...@gmail.com
Created On: 2008-10-03T23:05:03.000Z
Closed On: 2009-12-01T06:56:47.000Z

**Comment by aubertc** [comment]
Note: the name of the option that ended up being added is "`--indented-code-classes`", not "`--default-code-classes`".
This issue is discussed [here](https://github.com/jgm/pandoc/issues/2104).
