### ISSUE TITLE
Allow placement of MathJax script in document

### ISSUE THREAD

**Issue by vincerubinetti** [jgm/pandoc#5301]
**Problem:**
Providing configuration options to MathJax [requires creating a custom template](https://github.com/jgm/pandoc/issues/1181). Additionally, the user has no control of where/when the MathJax script is loaded in the document, making any interaction with other tools/plugins difficult to control and manage. It is also quite inconsistent to include these in their own special spot, whereas other hotlinked scripts need to be included `in-header`, `before-body`, etc.

These also probably apply to the other HTML math rendering options as well.

Some solutions I can think of:

**Solution 1:**
Split up `--mathjax` parameter. Have `--mathjax` only format the HTML in the manner needed for MathJax to pick up, but not insert the MathJax script. Allow `--include-in-header`, `--include-before-body`, `--include-after-body` to specify the inclusion of the script, either with a url or perhaps some kind of keyword (`[mathjax]`?) that is assumed to mean the latest (or latest supported by pandoc) version of MathJax.

This would be a breaking change, but is probably the cleanest and most expected imo.

**Solution 2:**
Have extra parameter prefixes, eg `--mathjax-in-header`, `--mathjax-before-body`. And have them respect order with the regular `--include-` parameters.

This is quite verbose.

**Solution 3:**
Have a parameter to specify a path to a configuration `<script>` file for MathJax, eg `--mathjax-config=config/mathjax.js`

Extra files to maintain and include. Not super clean imo.

**Solution 4:**
Same as solution 1, except try to somehow detect whether the user has included the MathJax script via a `--include` parameter, and give that one precedence. In other words, if the user only specifies `--mathjax`, it will behave as it behaves currently: by fetching the CDN version of MathJax. But if the user specifies `--mathjax` and `--include-after-body=scripts/mathjax.js`, the former command will only format the HTML properly, and the latter command will insert the script.

It would be hard to robustly/reliably detect a mathjax script in the `--include` parameters.

**Comment by jgm** [comment]
**Solution 4** (already possible with no code changes):  Note that the template simply has a `math` variable.  This gets set to a default value by the HTML writer, but you can override it using `-V` on the command line.  So,
```
pandoc --mathjax -s -Vmath=''
```
will have an effect that is equivalent to your Solution 1.

**Comment by vincerubinetti** [comment]
I was not aware of this option, thank you!

**Comment by dhimmel** [comment]
Also didn't know that `--variable math=''` was an option. Cool.
