### ISSUE TITLE
.docx: text in `instrtext` inside `fldchar` is not parsed

### ISSUE THREAD

**Issue by nyomanb** [jgm/pandoc#5302]
Hello,

as recommended on the [mailing list](https://groups.google.com/forum/#!topic/pandoc-discuss/oiVVV8rCqdw) I'm posting my issue with pandoc's handling of Word Content Control fields created by Citavi (a reference management program) here.

I've attached an an example docx document with two footnotes added by Citavi. Unfortunately, pandoc is omitting the content of the Word Content Control fields instead of converting these into plain text.

Cheers!

> pandoc -f docx "[test.docx](https://github.com/jgm/pandoc/files/2857164/test.docx)" -o "[test.txt](https://github.com/jgm/pandoc/files/2857168/test.txt)" -w gfm --reference-location "block"

--
pandoc.exe 2.6 (Windows 10/1803)
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5

**Comment by jkr** [comment]
@nyomanb -- would you mind posting a trimmed-down version of the file (just a sentence of lipsum and a footnote) that I could use as a test case for the test suite? I wouldn't know how to produce this myself, and I don't have access to a copy of word till tomorrow. (If you wouldn't get a chance until tomorrow, I could just take care of it then.)

**Comment by nyomanb** [comment]
Thank you very much!
[trimmed docx file](https://github.com/jgm/pandoc/files/2857893/test.docx)

**Comment by jkr** [comment]
Thanks -- I just pushed the test.
