### ISSUE TITLE
ipynb - don't create attachments for data URIs

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#5303]
Bad attachment name when `![](data:image/png;base64,...==)` to ipynb. It converts to attachent with a name that is `data:image/png;base64,...==`

I'd also rather prefer that such embeddings were in the image as the writer intended instead of auto-moving them to the attachments. Otherwise Pandoc will literally have no means of not using attachments.

**Comment by kiwi0fruit** [comment]
UPD: Could you please also tell me what way do you plan to fix this bug?

**Comment by kiwi0fruit** [comment]
I also found that `https://avatars3.githubusercontent.com/u/19735117?s=460&v=4` URL turnes into `attachment:https://avatars3.githubusercontent.com/u/19735117?s=460&amp;v=4` URL with created attachment with name `https://avatars3.githubusercontent.com/u/19735117?s=460&v=4`.

`&` -> `&amp;` was replaced and I'm not sure if that's a good thing.

**Comment by jgm** [comment]
I think we should not create attachments for images with absolute URIs (including data URIs).
This should be a fairly easy change to make.

**Comment by kiwi0fruit** [comment]
But what about `--self-contained` mode?

**Comment by jgm** [comment]
As documented, `--self-contained` only affects the HTML writer.  This is about the ipynb writer.

**Comment by jgm** [comment]
In theory, we could extend `--self-contained` to other formats.  But currently the code is very HTML-centric; it actually operates on the final HTML itself, to ensure that even resources referenced in templates get included.
