### ISSUE TITLE
in -f markdown -t markdown conversion Pandoc mangles code blocks containing backticks

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#5304]
I just discovered that in -f markdown -t markdown conversion Pandoc mangles a code block where any line starts with a backtick like

``````````````````
````````` {.markdown}
`«sträng»`

`` «sträng» ``

``` «sträng» ```

````«sträng»````
... 
`````````
``````````````````

with the output looking like

``````````````````
``` {.markdown}
`«sträng»`

`` «sträng» ``

``` «sträng» ```

````«sträng»````
... 
```
``````````````````

which unlike you make the fence longer manually becomes this the next time you run -f markdown -t markdown:

````
\`\``{.markdown}`«sträng»\`

`«sträng»`

`«sträng»`

`«sträng»` ... \`\`\`
````

pandoc 2.6, Linux.

There is the closed issue #1206 which is quite similar but as that particular issue was fixed I thought it was better to open a new one.

[Here is a filter] which does what Pandoc/the Markdown writer ought to do: counts the longest sequence of backticks in a code block and wraps the code in twice that number of backticks. (CodeBlock elements with backticks in the text are replaced with a RawBlock element containing the backtick-wrapped code.) I tried to make it smart about any attributes.

  [Here is a filter]: https://gist.github.com/bpj/772b93fe58e98e41a4dad61b9e32eec7

**Comment by jgm** [comment]
The previous issue affects the writer only covers lines with consist entirely of backticks.
This issue is really about the reader.  Only a line consisting entirely of backticks should end the code block, so pandoc should parse this as a code block.

**Comment by bpj** [comment]
Actually code blocks like this one break the vim-pandoc syntax highlighting too, so from that POV it would still be good if the fences were guaranteed to be at least one backtick longer than the longest stretch of backticks in the text, if possible.

**Comment by jgm** [comment]
Benct Philip Jonsson <notifications@github.com>
writes:

> Actually code blocks like this one break the vim-pandoc syntax highlighting too, so from that POV it would still be good if the fences were guaranteed to be at least one backtick longer than the longest stretch of backticks in the text, if possible.

Just to be clear: it's not necessary to make the
fencing longer than the longest stretch of backticks
in the code.  We only need a longer fence if there's
a code line consisting ONLY of backticks.  At least
that's how it's supposed to work. The reader needs
to be fixed, and then the markdown produced by the
writer will be fine.

**Comment by jgm** [comment]
John MacFarlane <jgm@berkeley.edu> writes:

> Benct Philip Jonsson <notifications@github.com>
> writes:
>
>> Actually code blocks like this one break the vim-pandoc syntax highlighting too, so from that POV it would still be good if the fences were guaranteed to be at least one backtick longer than the longest stretch of backticks in the text, if possible.
>
> Just to be clear: it's not necessary to make the
> fencing longer than the longest stretch of backticks
> in the code.  We only need a longer fence if there's
> a code line consisting ONLY of backticks.  At least
> that's how it's supposed to work. The reader needs
> to be fixed, and then the markdown produced by the
> writer will be fine.

Oh, I see, you're talking about vim-pandoc
highlighting.  Well, I'd consider that a problem
with vim-pandoc highlighting; I'd rather get that
fixed than modify pandoc.

**Comment by bpj** [comment]
Den 2019-02-13 kl. 22:37, skrev John MacFarlane:> Oh, I see, 
you're talking about vim-pandoc
 > highlighting.  Well, I'd consider that a problem
 > with vim-pandoc highlighting; I'd rather get that
 > fixed than modify pandoc.

Note that *both* pandoc and vim-pandoc-syntax get confused by the 
code blocks in question, so both would seem to need to be fixed by 
their respective caretakers.

**Comment by jgm** [comment]
Benct Philip Jonsson <notifications@github.com>
writes:

> Den 2019-02-13 kl. 22:37, skrev John MacFarlane:> Oh, I see, 
> you're talking about vim-pandoc
>  > highlighting.  Well, I'd consider that a problem
>  > with vim-pandoc highlighting; I'd rather get that
>  > fixed than modify pandoc.
>
> Note that *both* pandoc and vim-pandoc-syntax get confused by the 
> code blocks in question, so both would seem to need to be fixed by 
> their respective caretakers.

Yes, as noted, the pandoc *reader* needs to be fixed
(but the writer is okay).
