### ISSUE TITLE
resolve idiosyncrasies in new support for  ODT "Custom Properties"

### ISSUE THREAD

**Issue by brainchild0** [jgm/pandoc#5307]
I tested  the new feature from #2839, and while I find it very helpful, I also find a few quirks that impair usability:

1. YAML fields appear to be processed as custom metadata fields, but not `--variable` CLI parameters.  The latter is useful for scripting support for values calculated on-the-fly or fetched from external sources.
1. All fields not otherwise recognized are included unconditionally.  In many cases, such leaks are no more than a passing inconvenience, in others, a significant embarrassment, and in yet others, far worse than a mere embarrassment.  Perhaps fields processed in this way should be limited to those specifically designated for that purpose.
1. Specially recognized fields are not processed in this way, meaning the user cannot define a field as an ODT "Custom Property" if Pandoc recognizes the same field for some other use.  It is not always possible to choose another name if the required name must match an external constraint.  Further, users may be baffled by apparently disappearing fields, not realizing that  field is recognized as special and excluded for that reason.  Also, backward compatibility is broken if a new version changes the of processing a particular field such that it is no longer included in the list of "Custom Properties".
1. Several space characters appear after any "insert variable" block in the output ODT file, which do not appear in the reference document.

Ultimately, the custom properties rules should be clarified and unified for all output types, with such properties appearing in a dedicated namespace either one per output type, one for all output types, or both. Currently, the issue tracker features an intricate web of related issues for custom metadata in various output types.  A selection is referenced below.

(Also, some users may benefit from the ability to define multiple sets of custom variables, with the selected set resolved by the command line parameters.  Various uses cases may occur.  For example, a project team may use variables to share internal information that must not be published for external reading.)

**Related issues:** ##3034, #5252, #5243.

**Pandoc version:** 2.6.

**Comment by mb21** [comment]
> 1\. YAML fields appear to be processed as custom metadata fields, but not `--variable` CLI parameters.

This is intended. Please see the manual for the distinction between metadata variables and template variables.

Your points 2. and 3. concern namespacing of the metadata keys. This issue has been discussed before implementation (I'm sure you've seen the comment somewhere in the issues you linked to), and the trade-off between possibly namespace-collision and simplicity (ease-of-getting-started) has been made in favour of simplicity. If we have concrete evidence of many users complaining of collisions happening in real use-cases, we might revisit that decision.

> 4\. Several space characters appear after any "insert variable" block in the output ODT file, which do not appear in the reference document.

If you have a reproducible case, please file a new issue with the exact input, expected output.

**Comment by brainchild0** [comment]
> > 1. YAML fields appear to be processed as custom metadata fields, but not `--variable` CLI parameters.
> 
> This is intended. Please see the manual for the distinction between metadata variables and template variables.  

Yes, the manual makes the distinction.  But notice that the two statements are not identical: "Behavior _X_ is documented in the manual," and "Behavior _X_ is not idiosyncratic".  From a user standpoint, substituting custom values in a text sequence is achieved in LaTeX templates with a `$<name>$` sequence, with `--metadata` and `--variable` working equally well, the latter taking precedence, whereas in the case of ODT "insert variable", only `--metadata` has the effect.  So even if the behavior follows from specific, prescribed rules, the user invoking `--variable` observes that a particular effect appearing in the LaTeX output but not in the ODT output.  

Hence, from the top-down user perspective, the behavior is idiosyncratic. It is useful to identify ways to make the user experience more consistent and clear.  

> 
> Your points 2. and 3. concern namespacing of the metadata keys. This issue has been discussed before implementation (I'm sure you've seen the comment somewhere in the issues you linked to), and the trade-off between possibly namespace-collision and simplicity (ease-of-getting-started) has been made in favour of simplicity. If we have concrete evidence of many users complaining of collisions happening in real use-cases, we might revisit that decision.

I accept that currently a respectable portion of users are expressing satisfaction with the   simpler approach, but I am concerned that it can lead to a few very bad scenarios, and I'm not convinced as easily as you that in every case that a large number of content users, many with simpler use cases, necessarily offsets a handful of very bad experiences.  The cost of another layer of nesting in the YAML structure might be a small price to pay for some of the worse things that can happen.  Some examples: 1) A user loses hours or days of productivity because of a system-wide update to a new version of Pandoc introducing a special metadata variable that breaks the processing of a document that had previously used the same variable name as a custom field. 2) A team contributor adds a variable, for internal drafts, containing confidential information, that is unwittingly embedded into the published document's list of custom fields.  A third party discovers the variables hidden in the published document, while the original team remains oblivious to the breech.

So asking for concrete evidence is very wise, but so is anticipating problems that no one wants to happen even once.

A simple approach, an alternative to a distinct namespace, is a list of variable names that serve as a filter for what gets included.  An blacklist-style filter would preserve full compatibility with the current behavior, whereas a whitelist would offer better security to users who were not aware of the problem until too late.  (Whilelist-style has the added benefit of catching omissions.)


> 
> > 4. Several space characters appear after any "insert variable" block in the output ODT file, which do not appear in the reference document.
> 
> If you have a reproducible case, please file a new issue with the exact input, expected output.
> 

Will try to reproduce, and send test case if successful.  How would I submit a packet of bin files for review?

**Comment by jgm** [comment]
Namespacing would not help with the security concern
about private properties becoming manifest.  The whitelist
approach would. But the proper place to discuss this would be
the pandoc-discuss list.  Raise it there and see what
users think.

**Comment by brainchild0** [comment]
I can try to get some feedback from the community.  Aside from the understandable concerns about building and maintaining a bloated feature set, do you have any specific reservations about a CLI option that, if present, limits the included user-defined metadata fields to those found in a comma-delimited list from the option value?

**Comment by jgm** [comment]
brainchild0 <notifications@github.com> writes:

> I can try to get some feedback from the community.  Aside from the understandable concerns about building and maintaining a bloated feature set, do you have any specific reservations about a CLI option that, if present, limits the included user-defined metadata fields to those found in a comma-delimited list from the option value?

This could be done using a filter; it's essentially an
AST -> AST transformation between the reader and the writer.
So, if an option were implemented, it would amount to
including a built-in filter and hooking it to a
command-line argument. That's not necessarily an
argument against it; we have things like
--base-header-level which work the same way. But since
there are ever so many such transformations some
people might want to use, we need to be careful about
creating command-line options. Pandoc already has too
many!

**Comment by brainchild0** [comment]
If the CLI options are long-form, each derived from several natural-language words, then there is little danger of polluting the name space so badly that distinct features try to use the same name or new features cannot be assigned a useful name.  Name space issues commonly result when multiple parties contribute names without mediation or coordination.

If the concern is restricting the number of options to one that can be reasonable represented in a help screen, then you could move to model where a single option is used multiple times to refer to a name from a list of builtin filters.  In this case, though, you need a way to pass an options list for each filter invocation using semantics that are agnostic to the particular parameters of the filter.

_Note: Not being a contributor to the codebase, I have little to say about implementation details, but many new applications are using a design based on a light, pluggable core, with most builtin functionality achieved through a set of buitlin "plugins".  Perhaps implementing as many as possible of your advanced  features through builtin filters is a design you would like._    
_However, it does appear that filters are currently implemented as standalone programs that communicate through standard I/O.  This model may not provide the efficiency and robustness desired to achieve builtin functionality outside the core._

**Comment by jgm** [comment]
When I said "built-in filter," I didn't mean a
separate program that you'd shell out to. I just
meant a function Pandoc AST -> Pandoc AST that
is applied between the reader and the writer.

**Comment by brainchild0** [comment]
Ah, OK, well, like I say, I have little to say about implementation details (and what I do say seems not to be much use), so I will only emphasize that the feature is useful, at least to me, and hopefully to others, and let your work out how you might achieve it.

**Comment by brainchild0** [comment]
> > > 1. Several space characters appear after any "insert variable" block in the output ODT file, which do not appear in the reference document.
> > 
> > 
> > If you have a reproducible case, please file a new issue with the exact input, expected output.
> 
> Will try to reproduce, and send test case if successful. How would I submit a packet of bin files for review?


Could not reproduce the behavior with the extra space characters against the current development trunk.  I guess  the behavior was an artifact of some other issue recently fixed.
