### ISSUE TITLE
all metadata fields go to ipynb instead of jupyter field value only

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#5314]
According to [creating-jupyter-notebooks-with-pandoc](https://pandoc.org/MANUAL.html#creating-jupyter-notebooks-with-pandoc)  "Metadata will be taken from the jupyter metadata field". But now all metadata go to ipynb metadata.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by kiwi0fruit** [comment]
I guess you can handle it without additional info.

**Comment by kiwi0fruit** [comment]
I'm using pandoc 2.6 Windows GitHub build.

**Comment by jgm** [comment]
Fixed by 7aeabd8430bce7253d34a9a4baf26bbf71e9869e
