### ISSUE TITLE
LaTeX reader cannot parse \newenvironment having an \endgroup

### ISSUE THREAD

**Issue by scmu** [jgm/pandoc#5316]
With input
```
\documentclass{article}
\newenvironment{env}{\def\cmd{\endgroup}}{\dummy}
\begin{document}
\end{document}
```
`pandoc -f latex -t html -s` produces an error:
```
Error at "source" (line 2, column 41):
unexpected }
\newenvironment{env}{\def\cmd{\endgroup}}{\dummy}
                                        ^
```

It appears that the error is triggered by combination of `\newenvironment` and `\endgroup`. 
Pandoc processes the file fine if `\endgroup` is replaced by, say, `\dummy`.

`pandoc --version`:
```
pandoc --version
pandoc 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5
```

**Comment by jgm** [comment]
This has already been fixed in master, but the fix isn't yet in a released version.
