### ISSUE TITLE
Support conversion of math formulas from ODT to MarkDown/AsciiDoc

### ISSUE THREAD

**Issue by mojca** [jgm/pandoc#5318]
I have an ODT document with formulas which end up in the converted MarkDown or AsciiDoc documents as
```
image:./ObjectReplacements/Object 1[image,width=146,height=46]
```
even though `Object 1/content.xml` contains a nice valid MathML code which I'm sure Pandoc is able to handle.

If I first convert the document to `docx` (using LibreOffice) and do the conversion to md/adoc from that one, I get a nice valid formula, coded in TeX.

Would it be possible to support formulas directly from ODT documents?

**Comment by mb21** [comment]
The ODT writer already supports math, round-tripping would indeed be nice.
