### ISSUE TITLE
Pandoc doesn't convert html tables to mediawiki

### ISSUE THREAD

**Issue by krosssc** [jgm/pandoc#5320]
Pandoc doesn't convert HTML tables into media wiki format. A media wiki table has this syntax. Am I missing something or does this just not work?

{| class="wikitable"
|+ The table's caption
! Column header 1
! Column header 2
|-
| Cell 1
| Cell 2
|}

Command: pandoc.exe -f html -t mediawiki -i example.html

Version:
pandoc.exe -v
pandoc.exe 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5
Default user data directory: C:\Users\kross\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

Input:

```
<table>
<caption>Example Vehicle Data</caption>
<thead>
  <th>Make</th>
  <th>Model</th>
  <th>Color</th>
  <th>Year</th>
  <th>VIN</th>
  <th>Odometer Reading</th>
</thead>
<tbody>
  <tr>
	<td>Toyota</td>
	<td>Yaris</td>
	<td>Red</td>
	<td>2003</td>
	<td>1MEBM2898HW604169</td>
	<td>189653</td>
  </tr>
  <tr>
	<td>Ford</td>
	<td>Escape</td>
	<td>Blue</td>
	<td>2017</td>
	<td>2B7HB23W9HK211782</td>
	<td>23535</td>
  </tr>
</tbody>
</table>
```

Output:
Example Vehicle Data
Make
Model
Color
Year
VIN
Odometer Reading
Toyota
Yaris
Red
2003
1MEBM2898HW604169
189653
Ford
Escape
Blue
2017
2B7HB23W9HK211782
23535

**Comment by mb21** [comment]
Your input HTML is invalid. Wrap the cells in the `thead` in a `tr`:

```
<table>
<caption>Example Vehicle Data</caption>
<thead>
<tr>
  <th>Make</th>
  <th>Model</th>
  <th>Color</th>
  <th>Year</th>
  <th>VIN</th>
  <th>Odometer Reading</th>
</tr>
</thead>
<tbody>
  <tr>
	<td>Toyota</td>
	<td>Yaris</td>
	<td>Red</td>
	<td>2003</td>
	<td>1MEBM2898HW604169</td>
	<td>189653</td>
  </tr>
  <tr>
	<td>Ford</td>
	<td>Escape</td>
	<td>Blue</td>
	<td>2017</td>
	<td>2B7HB23W9HK211782</td>
	<td>23535</td>
  </tr>
</tbody>
</table>
```

**Comment by krosssc** [comment]
Doh. Thanks. I found https://github.com/jgm/pandoc/issues/3046 and got discouraged thinking this wasn't supported.
