### ISSUE TITLE
LaTeX reader does not handle hscode

### ISSUE THREAD

**Issue by scmu** [jgm/pandoc#5323]
I am not sure whether it should be an issue: `hscode` is the environment generated by `lhs2TeX` to format code. Stuffs in `hscode` are supposed to be in math mode, but pandoc does not recognise so. Therefore doing `pandoc -f latex -t html -s` on the following file
```
\documentclass{article}
\begin{document}
\begin{hscode}
\Varid{expr}_{0}
\end{hscode}
\end{document}
```
produces an error
```
Error at "source" (line 4, column 13):
unexpected _
expecting \end{hscode}
\Varid{expr}_{0}
            ^
```
The file goes through if I change `hscode` to, say, `equation`.

It might be reasonable that Pandoc does not support arbitrary environment, though.

This pandoc was compiled from the latest development version.
```
pandoc 2.6.1
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.6
```

**Comment by tarleb** [comment]
I'm doing a "spring-cleaning" and just found this issue. Sorry for the long wait!

The best way would probably be to define the `hscode` environment in a separate tex file:

``` latex
% file: hscode-stub.tex
\newenvironment{hscode}{\begin{equation}}{\end{equation}}
```

Then you can pass this file to pandoc as the first argument, with the other input files after it. This will cause pandoc to parse the `hscode` environments as equations.

I believe that adding full support for these environments is probably out of scope for pandoc.

**Comment by scmu** [comment]
Thank you so much! Will try the workaround.

**Comment by tarleb** [comment]
Closing. Please let us know in case the proposed solution should prove to be insufficient.
