### ISSUE TITLE
add support for github actions (done, actually)

### ISSUE THREAD

**Issue by maxheld83** [jgm/pandoc#5325]
[GitHub actions](https://github.com/features/actions) is a new workflow automation service from GitHub, currently in limited beta.
It makes it really easy to recombine simple tools to build complex chains, and it's all build on docker.

I've created such a [github action for pandoc](https://github.com/maxheld83/pandoc), based on @tarleb and @svenevs generous work to provide dockerfiles for pandoc (discussed in #3399).

There's not really anything to do, other than:

- [ ] maybe somewhere in the documentation point users to this (convenient?) possibility?
- [ ] migrate the repo in which I created the action to the pandoc organisation? (I'd be happy to keep up maintenance, I actually find it a bit awkward to have it under my own name, even though I didn't do the hard work). (is the pandoc github organisation the new place for pandoci-things on github?)

**Comment by tarleb** [comment]
This is quite cool!

The docker images are still a work in progress (we've slowed down a little for various reasons). I wouldn't want to advertise the docker related-things too widely just yet.

I'm in favor of publishing your github actions repo to the pandoc organization, but it is @jgm's decision to make.

**Comment by jgm** [comment]
> I'm in favor of publishing your github actions repo
> to the pandoc organization, but it is @jgm's
> decision to make.

Makes sense to me, but let's wait til the docker image
is stable before doing this.

**Comment by maxheld83** [comment]
gotcha. 
GitHub actions is still in limited beta, so that's limiting as well.

I agree it makes sense to wait for the docker images to mature before publishing this too widely. (There were some other pandoc docker images floating around, but I figured it make sense to build off of @tarleb and @svenevs "official" work.

Can we just keep this open until the docker images are mature? Or you can just poke me whenever you'd like to transition the repo.

**Comment by jgm** [comment]
Max Held <notifications@github.com> writes:

> Can we just keep this open until the docker images are mature?

Yes.

**Comment by maxheld83** [comment]
update:

GitHub has released a new, pretty different version of GitHub Actions last week.
I'm currently updating my GitHub action for pandoc.

Once that is stable and GitHub actions is in wide release (Nov 2019 I think?) it might still be nice to:

- [ ] migrate my repo over to the pandoc org
- [ ] mention the action somewhere in the pandoc docs.

I'll take care of both once this is stable.

The new GitHub actions also allows people to download build artifacts (pandoc conversion results!) and is super easy to set up, so this might be quite attractive for simple and more advanced pandoc users who are also on GitHub.

**Comment by jgm** [comment]
Nice, sounds good.

**Comment by maxheld83** [comment]
With GitHub Actions now in wide release, here's another update:

- I've added information on using pandoc in GitHub Actions on the wiki in https://github.com/jgm/pandoc/wiki/Pandoc-Extras/b0dbf21ce0a206cd7f8169a86465e5b73e73abb4
- I've soft-deprecated my old [github action for pandoc](https://github.com/maxheld83/pandoc-action), because it no longer does much on top of just using the containers directly.
- I've written a [couple of examples](https://github.com/maxheld83/pandoc-action-example) to help users use pandoc on GitHub Actions.

Remaining todos (suggestions, obvs):

- [ ] migrate my [examples](https://github.com/maxheld83/pandoc-action-example) over to the official pandoc org, as per https://github.com/maxheld83/pandoc-action-example/issues/1

When that is done, this issue can be closed.

**Comment by tarleb** [comment]
I've pushed the content from maxheld83/pandoc-action-example to https://github.com/pandoc/github-action-example/ and given repo permissions to @maxheld83.
