### ISSUE TITLE
md -> html conversion - improvement for pre tag contents

### ISSUE THREAD

**Issue by ORESoftware** [jgm/pandoc#5326]
I am using this command:

```
$ pandoc x.md --from=gfm -t html -o x.html
```

I have this html input:

```html
<pre lang="java" class="prettyprint">

 class NeoEach {
   
   static <T, V, E> void Each(int limit, Iterable<T> i, Asyncc.IEacher<T, E> m, Asyncc.IEachCallback<E> f) {
     
     final CounterLimit c = new CounterLimit(limit);
     final ShortCircuit s = new ShortCircuit();
     final var iterator = i.iterator();
     RunEach(iterator, c, s, m, f);
     handleSameTickCall(s);
   }
   
 }
</pre>
```

the problem is that these characters get interpreted as html in pre tags `<>` so we need escape them like so:
https://stackoverflow.com/questions/42182/how-to-escape-and-inside-pre-tags

so I am looking for output where the < character is replaced by &lt; and the > character is replaced with &gt;, something like this:

```html
<pre lang="java" class="prettyprint">

 class NeoEach {

   static &lt;T, V, E&gt; void Each(int limit, Iterable&lt;T&gt; i, Asyncc.IEacher&lt;T, E&gt; m, Asyncc.IEachCallback&lt;E&gt; f) {
     
     final CounterLimit c = new CounterLimit(limit);
     final ShortCircuit s = new ShortCircuit();
     final var iterator = i.iterator();
     RunEach(iterator, c, s, m, f);
     handleSameTickCall(s);
   }
   
 }
</pre>
```

**Comment by mb21** [comment]
Why are you using `--from=gfm` if you're converting from HTML?
Or alternatively, why are you not using https://pandoc.org/MANUAL.html#fenced-code-blocks

**Comment by jgm** [comment]
Your input pre isn't valid HTML, since the `<` should be escaped as `&lt;`.

**Comment by jgm** [comment]
To be clear:  markdown will just pass through raw HTML verbatim.
That's what pandoc did here.  You had invalid HTML in the input, so you get invalid HTML in the output.

**Comment by ORESoftware** [comment]
@mb21 I thought it was clear that I was converting from markdown to html, but maybe it wasn't.

@jgm I am not sure if I follow, I have this in a markdown file

```
<pre>
   <div>hello</div>
</pre>
```

I guess what you are saying is that the <div></div> tags aren't valid html.
But the thing is, I am not trying to produce html, I am trying to put a code sample. The conversion as it stands today will just ignore the <> characters, so I will get this output:

```
<pre>
  hello
</pre>
```

or something like that

**Comment by jgm** [comment]
HTML tags are allowed inside `<pre>` (though I believe `<div>` tags are not).
For example, you can have boldface inside your preformatted text:
```
<pre>
This is <b>boldface</b>
</pre>
```
Because HTML tags are allowed, you need to escape every `<` as `&lt;`; otherwise it isn't valid HTML.  Compare what you get with the above sample with
```
<pre>
This is &lt;b&gt;boldface&lt;/b&gt;
</pre>
```
