### ISSUE TITLE
Backticks appear when converting raw openxml input in markdown to docx

### ISSUE THREAD

**Issue by Gootjes** [jgm/pandoc#5327]
**Short description**
Backticks appear in docx output (where they should not) when using raw openxml markdown input: a combination of inline (single backticks) and in block form (three backticks).

**Type**
Bug

**Pandoc version**

> pandoc.exe 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5

**Conversion**
From markdown to docx

**Example**
_Markdown input:_
```
`<w:bookmarkStart w:id="bug" w:name="bug" />`{=openxml}```{=openxml}<w:pPr></w:pPr><w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="Arial" w:cs="Arial"/><w:sz w:val="22"/><w:szCs w:val="22"/><w:color w:val="111111"/></w:rPr><w:t xml:space="preserve">Cylinder</w:t></w:r>````<w:bookmarkEnd w:id="bug" />`{=openxml}
```
_Expected docx output:_

> Cylinder

(Wrapped in a bookmark called "bug")

_Actual docx output:_

> ``Cylinder

**Workaround**
Placing a newline between the first two and the last two openxml code blocks fixes the issue, but introduces spaces in the output:
```
`<w:bookmarkStart w:id="bug" w:name="bug" />`{=openxml}
```{=openxml}
<w:pPr></w:pPr><w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="Arial" w:cs="Arial"/><w:sz w:val="22"/><w:szCs w:val="22"/><w:color w:val="111111"/></w:rPr><w:t xml:space="preserve">Cylinder</w:t></w:r>
\```
`<w:bookmarkEnd w:id="bug" />`{=openxml}
```
(Please note the backslash that I had to put there to avoid formatting errors in this report.)

Note that only placing a newline between the first two blocks does not resolve the issue, and only placing a newline between only the last two blocks produces another bug.

When both newlines are placed, undesired spaces appear inside the bookmark "bug". _I rather not have those!_

**NB**
Unfortunately, I cannot simply wrap the whole segment into one inline openxml segment. I have to use the three backticks, as they are not my output. I am trying to wrap that output with a bookmark.

**Comment by agusmba** [comment]
According to the [Manual](https://pandoc.org/MANUAL.html#verbatim-code-blocks), fenced code blocks require that the backticks be in their own lines (as per your *workaround*)

**Comment by Gootjes** [comment]
> According to the [Manual](https://pandoc.org/MANUAL.html#verbatim-code-blocks), fenced code blocks require that the backticks be in their own lines (as per your _workaround_)

I see. If I use my workaround, would it be possible to avoid the spaces in the output (that are created because of the newlines)?

**Comment by jgm** [comment]
You might try putting an empty HTML comment between the closing ` ``` ` and the opening `` ` ``.
Otherwise you get four ticks in a row.  In inline code (and raw inline with backticks) an opening with three backticks must be matched by a sequence of exactly three backticks (not part of a longer sequence).

**Comment by Gootjes** [comment]
I tried multiple combinations, but it does not seem to work, as I either get the backticks, or openxml content (in plain text) in the docx output.
```
`<w:bookmarkStart w:id="bug" w:name="bug" />`{=openxml}
```{=openxml}
<w:pPr></w:pPr><w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="Arial" w:cs="Arial"/><w:sz w:val="22"/><w:szCs w:val="22"/><w:color w:val="111111"/></w:rPr><w:t xml:space="preserve">Cylinder</w:t></w:r>
\```<!-- -->`<w:bookmarkEnd w:id="bug" />`{=openxml}
```

**Comment by agusmba** [comment]
Did you try with this?

    `<w:bookmarkStart w:id="bug" w:name="bug" />`{=openxml}
    ```{=openxml}
    <w:pPr></w:pPr><w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="Arial" w:cs="Arial"/><w:sz w:val="22"/><w:szCs w:val="22"/><w:color w:val="111111"/></w:rPr><w:t xml:space="preserve">Cylinder</w:t></w:r>
    ```
    `<w:bookmarkEnd w:id="bug" />`{=openxml}

Not sure I understood your problem completely. You seemed to imply the middle line was given to you externally?

What is preventing you from doing this directly (see below)?

    ```{=openxml}
    <w:bookmarkStart w:id="bug" w:name="bug" />
    <w:pPr></w:pPr><w:r xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="Arial" w:cs="Arial"/><w:sz w:val="22"/><w:szCs w:val="22"/><w:color w:val="111111"/></w:rPr><w:t xml:space="preserve">Cylinder</w:t></w:r>
    <w:bookmarkEnd w:id="bug" />
    ```
