### ISSUE TITLE
Allow to highlight some text in an #+INCLUDE block

### ISSUE THREAD

**Issue by phmarek** [jgm/pandoc#5330]
When quoting some documents (sources, hexdumps, json, whatever), `#+INCLUDE` provides nice highlightning. However, sometimes it would be even better to get some parts of the included text marked up especially - for example, to more easily reference that from the surrounding text.

Please consider adding that feature the Pandoc; the most often backends I use are LaTeX and HTML.

Thank you so much!

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by phmarek** [comment]
```
# pandoc -v
pandoc 2.3.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.2
```

With an (org) input file like
```
    #+ATTR: highlight=some.*regex
#+INCLUDE "foobar.json"
```

I'd like to have each occurrence of `someXXXregex` in the json file be highlighted; if the colors (foreground, background) can be specified as well, and perhaps multiple independent highlightnings can be achieved as well, it would be great.

Thanks a lot for considering this!

**Comment by mb21** [comment]
Is this documented somewhere in the org syntax, or are you proposing for pandoc to add custom things to its org-mode implementation?

Either way, this is hard to implement currently. However, you can use a pandoc filter like e.g. https://github.com/owickstrom/pandoc-emphasize-code

**Comment by phmarek** [comment]
That was just something that I would have some use for. Asciidoc has something similar (https://asciidoctor.org/docs/user-manual/#callouts).

Thanks, I'll take a look at that filter.

**Comment by mb21** [comment]
Maybe you'll have to write you own filter. See e.g. https://pandoc.org/lua-filters.html

Feel free to ask for help on the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss).
