### ISSUE TITLE
pandoc.MetaBlocks in lua filter does not create discrete objects 

### ISSUE THREAD

**Issue by msprev** [jgm/pandoc#5331]
Run this lua filter on pandoc 2.6:

```
function Pandoc(doc)
    doc.meta['b1'] = pandoc.MetaBlocks(doc.blocks)
    return doc
end
```

on this markdown:

```
block 1

block 2
```

produces (as expected):

```
---
b1: |
    block 1

    block 2
---

block 1

block 2
```

but run this:

```
function Pandoc(doc)
    doc.meta['b1'] = pandoc.MetaBlocks(doc.blocks)
    doc.meta['b2'] = pandoc.MetaBlocks(doc.blocks)
    return doc
end
```

on the same source, produces a fatal error:

```
Error while trying to get a filter's return value from lua stack.
Could not get Pandoc value: Could not get Meta value: Could not read value of key-value pair: Could not get MetaValue: Could not read list: Could not get Block value: Unknown block type: MetaBlocks
```

Shouldn't `MetaBlocks` work as a constructor, creating a new object for each instance it is called, so that different invocations create discrete objects that can be assigned to `b1` and `b2` respectively?

**Comment by tarleb** [comment]
I agree, that is a problem. Alternative demonstration of the problem:

``` lua
local plain = {pandoc.Plain("test")}
local mb1 = pandoc.MetaBlocks(plain)
local mb2 = pandoc.MetaBlocks(plain)
print(mb1 == plain)    -- true
print(mb1.tag)         -- MetaBlocks
print(mb2 == plain)    -- false
print(mb2[1] == plain) -- true
```

Creating a new object would indeed solve this, but it would also affect performance (since we use the constructor for marshaling). I'll have to think about this some more.

Workaround for the time being: don't use `pandoc.MetaBlocks` at all. Just passing the plain list of blocks will work fine.

    function Pandoc (doc)
      doc.meta.b1 = doc.blocks
      doc.meta.b2 = doc.blocks
      return doc
    end

**Comment by msprev** [comment]
Thanks -- I'm glad to know that this is an issue as the behaviour surprised me.

On the workaround: Does this produce a valid pandoc AST? I thought that block values of a metadata field should be wrapped inside a MetaBlocks element?

**Comment by tarleb** [comment]
> On the workaround: Does this produce a valid pandoc AST? I thought that block values of a metadata field should be wrapped inside a MetaBlocks element?

We try to not restrain users too much when it comes to types, so yes: this produces a valid pandoc AST. Having a list of blocks tagged as `MetaBlocks` makes unmarshalling a tiny bit faster, as it helps us to distinguish between `MetaInlines`, `MetaList`, and `MetaBlocks` early on. It also helps to distinguish, for example, an empty `MetaList` from an empty `MetaBlocks` element.

Other than that, one should always be able to swap `MetaBlocks` with a (non-meta) list of blocks without problems.

**Comment by msprev** [comment]
Thanks, that is good to know. It feels wrong, but I should try to get over it at least for the moment.

**Comment by tarleb** [comment]
This will be fixed in the next pandoc release: all metavalue constructors, including `pandoc.MetaBlocks`, now return a fresh copies of their arguments.
