### ISSUE TITLE
Missing article in an error message

### ISSUE THREAD

**Issue by colourful-land** [jgm/pandoc#5332]
There are 2 grammar issues in this error and one semantic issue.

    $ pandoc --latex-engine=xelatex -o design.pdf design.md
    [pandoc warning] Unable to convert `3.svg' for use with pdflatex.
    ! LaTeX Error: Cannot determine size of graphic in 3.svg (no BoundingBo
    x).
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.1650 \includegraphics{3.svg}
    
    pandoc: Error producing PDF
    Makefile:2: recipe for target 'design.pdf' failed
    make: *** [design.pdf] Error 43

Two grammar issues:

1. Cannot determine size of graphic in 3.svg should be:
Cannot determine size of *the* graphic in 3.svg

2. See the LaTeX manual or LaTeX Companion for explanation. should be:
See the LaTeX manual or LaTeX Companion for *an* explanation.

One semantic issue:

`Cannot determine size of graphic in 3.svg (no BoundingBox)` can mean:

a. No bounding box is found in the SVG file where it should be.
b. No bounding box is specified (in LaTex) for the SVG file.

This can be easily amended by changing it to:

Cannot determine size of graphic,  *no BoundingBox* *in 3.svg.

By the way, I really appreciate if you also address the underlying technical problem I am having since my SVG file does have a bounding box. I asked in the group: https://groups.google.com/forum/#!topic/pandoc-discuss/_VPm7XoqMQA

**Comment by jgm** [comment]
This error message comes from LaTeX itself, not pandoc. Pandoc is simply passing it on.  If you'd like, you can try to get LaTeX developers to change it.
