### ISSUE TITLE
Russian translation (ru.yaml): extra "Author" definition causes Pandoc to not load translation

### ISSUE THREAD

**Issue by gdg-work** [jgm/pandoc#5334]
Found a possible **bug** in translations.

## Description:

There is an `Author:` field in Russian translations file `<DATADIR>/translations/ru.yaml`.
This field causes Pandoc to not load translation table with warnings like:
```
[WARNING] The term Table has no translation defined.
[WARNING] The term Figure has no translation defined.
```
Corresponding terms are never appear in the output. Figures' and tables' captions
are just `1. A table caption` instead of `Таблица 1. A table caption`.

## Solution: 

Remove this 'Author' translation table item.

As I can see, this problem presents in `uk.yaml` file, too. 

## (non-working) example:

```
# Table example

|  1 | 2  |  3 |
|---:|:--:|:---|
| first | second | third |

Table: A sample table

# Figure example

![A sample figure with online image][fig1]

[fig1]: https://www.clipartmax.com/png/small/6-65037_cartoon-space-ship-space-shuttle-clip-art.png "Space ship"

A sample figure
```
Pandoc command line and STDERR:

```
$ pandoc -t odt -V lang=ru-RU --metadata lang:ru-RU -o /tmp/t.odt -f markdown+implicit_figures t.md
[WARNING] Could not load translations for ru-RU
  translations/ru.yaml: expected Term instead of !!str
[WARNING] The term Table has no translation defined.
[WARNING] The term Figure has no translation defined.
```
Problem presents itself with ODT output.

Result:

![image](https://user-images.githubusercontent.com/11077638/53502514-0e5b8c00-3ad0-11e9-830e-9695aff249ec.png)

Expected: 'Таблица' before number in table caption and 'Рис.' before number in figure caption.

**Comment by gdg-work** [comment]
Pandoc version:
pandoc 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5

**Comment by mb21** [comment]
Looks like we have a problem parsing our own YAML file...? The error probably comes from https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Class.hs#L418

**Comment by mb21** [comment]
Indeed, `Author` is not in the list of `Term`s anymore: https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Translations.hs#L61
