### ISSUE TITLE
URLs with double dashes behave differently than without double dashes

### ISSUE THREAD

**Issue by dark-panda** [jgm/pandoc#5340]
Links with double dashes in the URL with identical link text behave differently than URLs without double dashes.

Example:

```
<a href="https://example.com/foo-bar">https://example.com/foo-bar</a>
<a href="https://example.com/foo--bar">https://example.com/foo--bar</a>
<a href="https://example.com/foo%2Dbar">https://example.com/foo-bar</a>
<a href="https://example.com/foo%2D%2Dbar">https://example.com/foo--bar</a>
<a href="https://example.com/foo%2D%2Dbar">https://example.com/foo%2D%2Dbar</a>
```

Produces:

```
\url{https://example.com/foo-bar}
\href{https://example.com/foo--bar}{https://example.com/foo--bar}
\href{https://example.com/foo\%2Dbar}{https://example.com/foo-bar}
\href{https://example.com/foo\%2D\%2Dbar}{https://example.com/foo--bar}
\url{https://example.com/foo\%2D\%2Dbar}
```

Basically, the double dashes produces a `\href` but without the double dashes produces a `\url` when the link text is the same as the `href`. If you URL-escape the the dashes, a `\url` is again used. I noticed this because some of the links in my document were being generated with `\href` and weren't being given monospaced font and weren't line breaking correctly as my `\url`s were. I've started URL-encoding dashes in my links as a result and it works fine and consistently using `\url`, which is what I want.

**Comment by jgm** [comment]
This is due to the code (in LaTeX writer) for detecting when a link is just a URL.
