### ISSUE TITLE
feature: stylized elements in document titles

### ISSUE THREAD

**Issue by brainchild0** [jgm/pandoc#5341]
Though obviously very rare for academic publishing,  use of formatting elements within titles is not wildly uncommon in popular printing, including some nonfiction.

Some lighthearted illustrations might be:

* `<xml/>`: The E*x*tensible *M*arkup *L*anguage
  
  ``` 
  `<xml/>`: The E*x*tensible *M*arkup *L*anguage 
  ```

* The Story of How I Became the  
loneliest  
Man in the World's Largest City
  
  ``` 
   The Story of How I Became the  
   loneliest   
   Man in the World's Largest City
   ```

* Welcome to the  
Wonderful  
World of  
Whirring  
Widgets

   ```
   Welcome to the  
   Wonderful  
   World of  
   Whirring  
   Widgets
   ```

* Foundational Identities in Mathematics: $e^{i \pi} + 1 = 0$ and Beyond

   ```
   Foundational Identities in Mathematics: $e^{i \pi} + 1 = 0$ and Beyond
   ```

   *Note: Maths not displaying in GitHub.*

* **Accounting:** The World's Most _Exciting_ Career Choice

   ```
   **Accounting:** The World's Most _Exciting_ Career Choice
   ```

*Pandoc* already features a precedent for stylizing text read from a metadata source.  Abstract blocks, it seems, are able to be typeset in the target format using MarkDown style elements.

Similar support might be adapted to title text.  Support in subtitle and even author text ought also to be included for completeness. Obviously, text included in actual metadata fields of the output must be unformatted.  As such, this feature might be best implemented by adding a display version of each of these fields (e.g. `display_title`, etc.), which would contain the stylized text, if formatting is desired in the metadata-derived text displayed in documents (e.g. title blocks, title pages).  Then, convenience and backward compatibility are maintained by using the standard version of each field for the display text when the display version is not given.

**Comment by mb21** [comment]
You didn't provide sample input, but have you actually tried it? It should be supported already.

**Comment by mb21** [comment]
This input works well for LaTeX output:

```
---
title: '`<xml/>`: The E*x*tensible *M*arkup *L*anguage'
---

# `<xml/>`: The E*x*tensible *M*arkup *L*anguage 
```

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by brainchild0** [comment]
I'm sorry for the distraction.  I tested beforehand with line breaks in the title, which did not  appear to work at that time.  It is possible that the editor, ever so helpfully, removed the trailing whitespace in the YAML input, that marks a line in MarkDown as the last in the paragraph.


One further remark, though, I do think it would be a slight improvement if the user could separately specify a display title, if desired.  One can still consider cases where the unformatted metadata ought not to include exactly the same characters as the formatted representation of a field.  For example, suppose in my first example, the author feels that the triangle braces `<>` are too distracting without the code-style formatting, and wishes the title metadata field of the target document to literally contain only *xml: The Extensible Markup Language*.  Or suppose he wishes to capitalize *XML*, lacking the clear indication that it is to read as code.  Or, in other cases, slashes or vertical bars might serve as substitutes for line breaks. The intention of a document author cannot be inferred with deterministic accuracy   in the general case, pointing to the benefit of  allowing overriding default behavior with a separate field.
