### ISSUE TITLE
Add tectonic as a pdf engine

### ISSUE THREAD

**Issue by cormacrelf** [jgm/pandoc#5345]
I was reminded by #3195 that I wanted this, hope it's not too late for 2.7.

https://tectonic-typesetting.github.io/en-US/

Tectonic is a fairly new engine that mirrors XeTeX, and although it's beta software in active development, it's pretty stable. It also doesn't write any support files by default, so no need to fluff around with .aux. It does its own steady state detection, so also only needs one run from Pandoc's point of view.

You might find if you try it out that it takes a very long time the first time -- it's auto-downloading support files. You should be able to see that with `--verbose`.

**Comment by cormacrelf** [comment]
It appears tectonic supports STDIN instead of temp directories, and also has decided not to read any of the usual environment variables, so I might special-case the whole execution.

**Comment by jgm** [comment]
I wonder if this might be premature, since this is a new tool that hasn't yet seen widespread use.

Also, without the environment variables (I assume that includes TEXINPUTS), how will it know where to look for images etc.?

**Comment by cormacrelf** [comment]
What are the stability guarantees with Pandoc's CLI? If this is added, can it never be removed? The project isn't that young, and its forums and GitHub issues seem quite active (even if the forum has been 503ing today).

Markdown linked images, local or downloaded, seem to work fine without environment variables. They are being written into the temp directory at some point, but I don't know if that covers all situations.

```markdown
![img][something.png]
```

```latex
...
\includegraphics{/private/var/folders/22/.../T/tex2pdf.-38e6370705df870f/0b01df7427f8df389f76930c5cfca1a5d27b7494.png}
...
```

**Comment by jgm** [comment]
No stability *guarantees*, but we tend to be extremely
conservative about removing CLI options. (We did it in 2.0.)
There are always people who grow to depend on them.
And any addition adds to the maintenance overhead.
Hence we're conservative about adding options, too.
In the case of latexmk, we've had many requests for
it. This is the first I've heard about tectonic,
though it seems easy enough to add support for it.

I can't recall when the TEXINPUTS is needed --
possibly for includes.  Can you test with `\input` and
`\include`, using relative paths?

**Comment by cormacrelf** [comment]
I tested that out, I have a few observations:

* I have learned that TEXINPUTS is for .sty/.cls files, not `\input` and `\include`. Yes, pretty confusing.
* Tectonic can't be told to use a particular TEXINPUTS -- its sty/cls files come from either the cached bundle, or from the same directory as your tex file. This is something they want to build a better system than TEXINPUTS for, as I understand it.
* When using `--pdf-engine=xelatex` for example, `\input` and `\include` are PWD-relative, so they refer to tex files relative to the directory you execute pandoc in.
  * This means if you normally do `pandoc input.md` with \includes in it, and then you run `cd ..; pandoc dir/input.md`, the relative paths will be wrong and xelatex will succeed but warn you.
* Tectonic deviates from this: input/include paths are relative to the tex file, which in the way I implemented it in the PR means in the temporary directory.

Tectonic can actually behave the same way as the rest of the engines if you use its STDIN mode, e.g.

    pandoc input.md -s -t latex | tectonic -

... will pick up an \include from the PWD. Unfortunately it always names the resulting PDF `texput.pdf`.

So there is a way in `PDF.hs`: Not writing the latex to a file, but piping it to `tectonic - --outdir $TMPDIR` and picking up the PDF from `$TMPDIR/texput.pdf` instead of the usual name.

**Comment by jgm** [comment]
Cormac Relf <notifications@github.com> writes:

> * Tectonic can't be told to use a particular TEXINPUTS -- its sty/cls files come from either the cached bundle, or from the same directory as your tex file. This is something they want to build a better system than TEXINPUTS for, as I understand it.

Ah yes.  This is probably why we set TEXINPUTS, to
allow people to include their own .sty files in the
working directory.  This won't work with current
tectonic setup.  If you changed to using a pipe
(and not creating a temp dir) it might work, but
you'd still need to put the images in the temp dir.

> * When using `--pdf-engine=xelatex` for example, `\input` and `\include` are PWD-relative, so they refer to tex files relative to the directory you execute pandoc in.
>   * This means if you normally do `pandoc input.md` with \includes in it, and then you run `cd ..; pandoc dir/input.md`, the relative paths will be wrong and xelatex will succeed but warn you.
> * Tectonic deviates from this: input/include paths are relative to the tex file, which in the way I implemented it in the PR means in the temporary directory.

This will break includes, then, right?  Since we copy
the input  source but not any included files into the
temp dir.

> Tectonic can actually behave the same way as the rest of the engines if you use its STDIN mode, e.g.
>
>     pandoc input.md -s -t latex | tectonic -
>
> ... will pick up an \include from the PWD. Unfortunately it always names the resulting PDF `texput.pdf`.

> So there is a way in `PDF.hs`: Not writing the latex to a file, but piping it to `tectonic - --outdir $TMPDIR` and picking up the PDF from `$TMPDIR/texput.pdf` instead of the usual name.

That seems promising. However, there's also the issue
of handling images.  Currently we go through the
document looking for images and writing them to the
temp directory, sometimes doing format conversions.
This has to be done in a temp directory.  But I
think you could make it work with tectonic, as long
as the paths in the Image elements are changed to
point to the right place.

**Comment by cormacrelf** [comment]
Worry not: images still get put in the temp dir and are thereafter referred to with an absolute path in the converted tex. That happens a little higher up in the code. So they still work.

**Comment by cormacrelf** [comment]
You may have missed (via email) my edit saying the PR implements stdin now.

**Comment by igalic** [comment]
this still needs to be fixed on the website online manual, where it's not mentioned at all

**Comment by jgm** [comment]
@igalic It is mentioned:
```
--pdf-engine=PROGRAM
Use the specified engine when producing PDF output. Valid values are pdflatex, lualatex, xelatex, latexmk, tectonic, wkhtmltopdf, weasyprint, prince, context, and pdfroff. If the engine is not in your PATH, the full path of the engine may be specified here. If this option is not specified, pandoc uses the following defaults depending on the output format specified using -t/--to:

-t latex or none: pdflatex (other options: xelatex, lualatex, tectonic, latexmk)
-t context: context
-t html: wkhtmltopdf (other options: prince, weasyprint)
-t ms: pdfroff
```

**Comment by igalic** [comment]
@jgm hm… 
no, i meant the the actual website: https://pandoc.org/index.html

> **PDF***
>    → via pdflatex, xelatex, lualatex, pdfroff, wkhtml2pdf, prince, or weasyprint.

so i reckon i should submit this issue / a potential fix to https://github.com/jgm/pandoc-website

**Comment by igalic** [comment]
done: https://github.com/jgm/pandoc-website/pull/39
