### ISSUE TITLE
xelatex russian lang error

### ISSUE THREAD

**Issue by habamax** [jgm/pandoc#5347]
**pandoc version:** 2.7

## test_poly.md

```
---
title: Check Polyglossia with Russian language
subtitle: LaTeX и pandoc
author: Maxim Kim
lang: ru
toc: true
numbersections: true
documentclass: article
mainfont: Arial
sansfont: Arial
monofont: Consolas
header-includes:
	- \newfontfamily\cyrillicfont{Arial}
	- \newfontfamily\cyrillicfontsf{Arial}
	- \newfontfamily\cyrillicfonttt{Consolas}
---


# Однажды в студеную зимнюю пору

Я из лесу вышел -- был сильный мороз.

```

## pandoc commands

    pandoc test_poly.md -o test_poly.pdf -s --pdf-engine=xelatex
 
**ERROR**

```
Error producing PDF.
! File ended while scanning use of \__fontspec_strip_leading_sign:Nw.
<inserted text>
                \par
<*> ...al/Temp/tex2pdf.-94a352d6ab057212/input.tex

Here is how much of TeX's memory you used:
 26614 strings out of 492933
 476332 string characters out of 6136537
 712251 words of memory out of 5000000
 30452 multiletter control sequences out of 15000+600000
 532980 words of font info for 46 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 51i,1n,119p,870b,446s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.
```

If I use `lualatex`:

    pandoc test_poly.md -o test_poly.pdf -s --pdf-engine=lualatex

No errors, it works.

**Comment by jgm** [comment]
Have you tried updating the underlying texlive packages?  This seems like a tex issue that pandoc isn't going to be able to do anything about.

On texlive `tlmgr update --self --all`

**Comment by adunning** [comment]
Either engine works for me with an updated copy of TeX Live 2018.

**Comment by habamax** [comment]
I have just updated tex live aaaand:

1. xelatex command works
2. lualatex doesn't :)

lualatex (`pandoc test_poly.md -o test_poly.pdf -s --pdf-engine=lualatex`) gives me:

```
Error producing PDF.
!  ==> Fatal error occurred, no output PDF file produced!
```
I guess you're right -- it has nothing to do with pandoc.

**Comment by mb21** [comment]
> it has nothing to do with pandoc.

Probably not, thus closing this. If you see something in the TeX output of pandoc that could be improved, we can reopen.

**Comment by adunning** [comment]
LuaLaTeX is broken with the last update to TeX Live 2018 when using the microtype package. Unfortunately they froze it a couple of days before the fixed version of microtype was released, so you need to either update microtype manually from CTAN or [load the luatexbase package](https://tex.stackexchange.com/questions/476740/).

**Comment by habamax** [comment]
@adunning thx.
