### ISSUE TITLE
reference with bibkey which includes "[..]" is not inserted

### ISSUE THREAD

**Issue by andrewufrank** [jgm/pandoc#5350]
I have a bibliography which includes bibtex keys of the format `author[somecode]` (produced by the literature referencing system of my university); according to the bibtex rules, such formats are not forbidden. References of this form are not dereferenced by pandoc, obviously because they clash with the pandoc format `[@author]`. 

Would it be possible to extend the parsing of references to include cases like `[@author[somecode]]` - i.e. if a `[` is parsed then a closing `]` is expected and part of the reference before the closing of the reference. 

I use the Haskell API (`processCites'`) and checked the code, but cannot see where a change to the parser would be required. Thank you for consideration!

**Comment by jgm** [comment]
Look at Text.Pandoc.Parsing.citeKey
Because `[` and `]` have a prominent role in Markdown, I'm somewhat reluctant to allow this, as it could create ambiguities and unexpected results.

**Comment by andrewufrank** [comment]
Thank you - I found the code (I was expecting it in pandoc-citeproc). I understand your hesitations and, for now, will change the (hopefully few) references with `[..]` to something which does not cause issues and not change the code. I assume this is simpler.
