### ISSUE TITLE
Roundtrip from manpage to manpage shows slight problem

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#5352]
To test Pandoc's manpage reader and writer capabilities I converted its own manpage to a manpage (using the latested shipped release, v2.7) on macOS:

~~~
 pandoc -o pandoc.1.man /usr/local/share/man/man1/pandoc.1 -f man
~~~

When viewing the resulting manpage the output looks garbled. Checking both groff codes with vimdiff, the first major difference is that the first 3 lines of the original's groff code are missing in the created file:

~~~
.\"t
.TH PANDOC 1 "March 2, 2019" "pandoc 2.7"
.SH NAME
~~~

Manually adding them back into the *`./pandoc.1.man`* output restores the well-rendered view in the manpage viewer.

----

*(There are other small differences in the output as compared to the input manpage, but these do not seem to influence the usability of the resulting man page at any point inside the document.)*

**Comment by KurtPfeifle** [comment]
### Update

#### 1. Roundtrip *`'man => docx => man'`*

~~~
 pandoc -o pandoc.1.docx /usr/local/share/man/man1/pandoc.1 -f man
 pandoc -o pandoc.1.fromdocx.man pandoc.1.docx -f docx -t man
~~~

Resulting manpage also looks garbled. Manually fixing first few lines helps.


#### 2. Roundtrip *`'man => odt => man'`*

~~~
 pandoc -o pandoc.1.odt /usr/local/share/man/man1/pandoc.1 -f man
 pandoc -o pandoc.1.fromodt.man pandoc.1.odt -f odt -t man
~~~

Resulting manpage also looks garbled. Manually fixing first few lines helps.


#### 3. Roundtrip *`'man => html => man'`*

~~~
 pandoc -o pandoc.1.html /usr/local/share/man/man1/pandoc.1 -f man
 pandoc -o pandoc.1.fromhtml.man pandoc.1.html -f html -t man
~~~

Resulting manpage also looks garbled. Manually fixing first few lines helps.

#### 4. Roundtrip *`'man => epub3 => man'`*

~~~
 pandoc -o pandoc.1.epub /usr/local/share/man/man1/pandoc.1 -f man -t epub3
 pandoc -o pandoc.1.fromepub.man pandoc.1.epub -f epub3 -t man
~~~

Resulting manpage also looks garbled. Manually fixing first few lines helps.

**Comment by tarleb** [comment]
It seems that your commands are missing the `-s`/`--standalone` flag. I got very good results when trying your first command with that flag.

Roundtrips will almost always be lossy in some way, and differences rarely classify as bugs. However, please do let us know if your tests uncover a deeper problem somewhere.

**Comment by KurtPfeifle** [comment]
@tarleb wrote:

> *"It seems that your commands are missing the `-s/--standalone` flag. I got very good results when trying your first command with that flag."*

Thanks a lot. That fixed it. *(The roundtrip via ODT is an exception, though I wouldn't rate it as a "deeper" problem. See below.)*

@tarleb wrote:

> *"Roundtrips will almost always be lossy in some way, and differences rarely classify as bugs."*

Of course you are right. But un-lossy roundtrips, on the other hand, are a positive proof about the quality of conversions. Especially if they are run on a very "cleanly" formatted input document, such as the Pandoc manpage. That's why I ***DO*** run them from time to time...

In this case the bug was clearly located right in between the chair and the keyboard. I totally forgot about `-s` being also relevant for the man output format.

@tarleb wrote:

> *"However, please do let us know if your tests uncover a deeper problem somewhere."*

As I said, the roundtrip via ODT results in a man page which displays the first three text lines in the man viewer as:

~~~
--------------------
()                                                                                                                                                                  ()

       PANDOC

       March 2, 2019

NAME
       pandoc - general markup converter
--------------------
~~~

whereas the other results (more correctly) look like:

~~~
--------------------
PANDOC()                                                                                                                                     PANDOC()

NAME
       pandoc - general markup converter
--------------------
~~~

**Comment by tarleb** [comment]
Thanks @KurtPfeifle! The problem with odt (and docx) is that, as I understand it, don't lend themselves to simple extraction of metadata. I thought there was a ticket for this, but I can't seem to find it. Issue #3109 is related, but doesn't quite capture the problem. Probably worth to open a new issue for this.
