### ISSUE TITLE
Pandoc default reference.docx unreadable

### ISSUE THREAD

**Issue by unnamedcrewman** [jgm/pandoc#5357]
Windows 10 Pro 1809
    Office 365 (2016)
    pandoc.exe 2.7 (installed from the .msi installer)
    Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.1, skylighting 0.7.7

I'm trying to generate a sample reference.docx.  In PowerShell on Windows 10, I'm using this command from the documentation:

`pandoc --print-default-data-file reference.docx > custom-reference.docx`

## Expected Output
A readable, docx file that can can be opened in Word.

## Unexpected Result
The resulting file generates an "Unreadable content" error when attempting to open in Word.  I've tried to unzip the file, but 7-zip says the file is not an archive and won't extract anything.

## Additional Info
I can open any `.docx` file generated by pandoc from my own source files without issue.

The only problem is trying to open the `custom-reference.docx` generated by the command above.  If I use Word's [document recovery process](https://support.office.com/en-us/article/Open-a-document-after-a-file-corruption-error-47df9d48-2165-4411-a699-1786ac734bc3) to open the `custom-reference.docx` document, I can "read" the file and it opens with the following text shown:

    [Content_Types].xmlÃUâ•”nÃ
    0
    _rels/.relsÂ¡Ã†
    docProps/app.xmlÃ˜Râ•¦Nâ
    (piUv9
    %cIuÃ°
    docProps/core.xmlÃ‘Ã†]kÃ¢0
    ^m0Ã¿ccw!9mCâ•
    I:â
    '<Â¡Â­Ã±â•‘,wfA$q(r^aH>gOÂ¤Â§
    docProps/custom.xmlÃ˜â•
    =
    word/document.xmlÃÃ–
    3?J6+w
    /ÃeÃ»"LVn

    $#
    3Â³hkÃ¡Ã¦Zâ”¼Hc}<|@
    word/fontTable.xmlÃÃ²]OÃ¢0
    word/footnotes.xmlÃ˜Ã´
    EÂ¸|EÃµ=8â”¤RUE$lP
    ?4Â¸Ã—y8Y,?m
    word/comments.xmlÃ˜Ã
    {Æ’"xOM{X
    CAh+Bv
    P/e9Jb~Ã
    a,}
    word/numbering.xmlâ”¼Ã
    word/settings.xmlÃ˜V]sÃ³0
    vPÃ‰ÃšPNâ–„Ã¬â•©BMW Ãªn	FÃ²Ãˆ25-*E(
    ktÃ…lâ–’Ã¥â–‘eP<3j6

    *

    7DÃ³Â
    ^
    ^Ã´SgÂ©BÃ¦Â³Ã -WÂªÃ¼â–’â• <2aâ•Â§&Ã„6ySÃ´ÃŸv;e0n7
    word/webSettings.xml]Ã„;
    word/styles.xmlÃÃœ[sÃ”6
    [r%9Ã¹â– Â·JÃ£6Ã»â–’Ã¤!NÃŠlyC:
    Ãš\>]l
    vjFâ”¤kFâ”¤{@â”¤Ã‡hÃ¾3 Ã¨ÃˆÃÃ¾Fâ”¤gFâ”¤w@â”¤Ã‡hÂ¸3 Â·â•” <6Cx|
    !<1Cxr
    word/_rels/document.xml.relsÃÃˆ
    c[%SÃœD1% 
    Sâ–“+SjveBIâ
    M

    Ã¿ÃŠ)Fn.%,Ã
    word/_rels/footnotes.xml.relsÃ¬Ã…
    word/theme/theme1.xmlÃYMoâ–ˆ6
    CÃ…â”¤DKl(Q 
    %â”´]Ã·Ã­Ã€Ä±Â´Â»U	nIX["
    bs`Fx,
    k]z]uN
    \Q
    c2e{PZ
    ]Câ””Â¦SÃ”m//X[â•—â–’Â¿ÃÃŠOUt|O*
    `â–‘?Â yKVs.IUÂ
    [Content_Types].xmlPK
    _rels/.relsPK
    docProps/app.xmlPK
    docProps/core.xmlPK
    docProps/custom.xmlPK
    word/document.xmlPK
    word/fontTable.xmlPK
    word/footnotes.xmlPK
    word/comments.xmlPK
    word/numbering.xmlPK
    word/settings.xmlPK
    word/webSettings.xmlPK
    word/styles.xmlPK
    word/_rels/document.xml.relsPK
    word/_rels/footnotes.xml.relsPK
    word/theme/theme1.xmlPK

**Comment by mb21** [comment]
That sounds a lot like https://github.com/jgm/pandoc/issues/4758:

> So the main problem, Default reference.docx cannot be opened in Word 2016 is due to the PowerShell redirection messing up the binary content and thus corrupting the zip file (docx). 

See https://www.leeholmes.com/blog/2007/01/18/redirecting-binary-output-in-powershell/

Maybe we should update the documentation with a disclaimer...

If that's not it: What Word version are you using? What tool to unzip? Can you post the generated file as an attachment?

**Comment by jgm** [comment]
I've changed things so you can use `--print-default-data-file` with `-o` (but `-o` must come first on command line).

**Comment by jkr** [comment]
> Alternatively, we would have to provide a --write-default-data-file FILE option that writes to a file instead of STDOUT.

This feels like it should be the default. I'm sure it's been discussed before, but what's the purpose of piping binary to stdout here? 99% of the time users will just pipe it to a file. And for the other 1%, we could include some syntax like `--write-default-data-file -`. 

I know it provides symmetry with `--print-default-template` but I'm not ure symmetry is a good thing here.

**Comment by jkr** [comment]
I wrote my comment without having seen @jgm's followup. So this will probably fix the issue. But I'm still curious if the symmetry is proper in this case. We don't allow users to write binary formats to the terminal after all (requiring a dash to force a write to stdout).

**Comment by jgm** [comment]
It may not be ideal.  But now that it does work this
way, I'm hesitant to change the option and break
previously working commands...

**Comment by unnamedcrewman** [comment]
The windows redirect was indeed my issue.  Thanks for taking the time on this.
