### ISSUE TITLE
Converted html->docx-files can't be edited in Word Online

### ISSUE THREAD

**Issue by fjellandermedia** [jgm/pandoc#5358]
I installed Pandoc via homebrew today, so I have version 2.7. 

The issue is that when I convert a file either from HTML or TXT to docx the generated file can't be edited in Word Online. It open in read-only mode and when I click Edit in browser, I get the error message _Sorry this message can't be opened for editing._ It does open fine in the desktop mac app (latest version), however, in Compatibility mode. 

Steps to reproduce:
- Create a file input.txt with some simple string. 
- Run pandoc -t docx -o output.docx input.txt
- Upload output.docx to Onedrive Online. 
- Open output.docx in Word Online.
- Click Edit Document->Edit in browser

I have also tried to upload and open the custom-reference.docx that i generated using _pandoc --print-default-data-file reference.docx > custom-reference.docx_ and that opened fine in Word Online, also for editing.

**Comment by jgm** [comment]
Hm.  This suggests that compatibility mode works in Word Online:
https://support.office.com/en-us/article/using-compatibility-mode-in-word-online-03ff7a17-a32d-42f7-81a9-f65a4b270795

On compatibility mode:  we generate Word 2006 docx (`http://schemas.openxmlformats.org/wordprocessingml/2006/main`) so they'll be readable by the widest variety of Word versions.

**Comment by jgm** [comment]
Note that in the link I posted above, it says

>  to insert pictures and resize them, or edit alt text, you must open the document in Microsoft Word 2010 or later, convert the document, and then save it. If you don't need to insert pictures, you can continue to work with the document in Word Online in compatibility mode, and there's no need to convert the document.

**Comment by fjellandermedia** [comment]
Thanks for answering!

> Note that in the link I posted above, it says

Yeah, I saw that. There is however no image in my example above and I have not tried to add one. Word Online never gives me a chance! 

I suppose there is no built in support for Word 2010 docx or later in Pandoc that I can try? I skimmed the documentation but couldn’t find a setting for docx version.

**Comment by jgm** [comment]
There is no support for later docx standards.  We could consider adding an option for this but I'm not sure what would be involved.

**Comment by fjellandermedia** [comment]
> There is no support for later docx standards. We could consider adding an option for this but I'm not sure what would be involved.

Ok! I have no idea if this is the problem, though. I’ll try to find some sample file of the .docx 2006 version and see if it opens in Word Online.

**Comment by fjellandermedia** [comment]
After some further digging this doesn's seem to be the problem. The output file generated from Pandoc has AppVersion 12.000 (as in a Word 2007 file). After some googling I found this [Calibre sample file](https://calibre-ebook.com/downloads/demos/demo.docx) and it also has AppVersion 12.000. The Calibre sample file opens fine for editing in Word Online, but the Pandoc output file does not. So it can't be the AppVersion. It must be something else in the Pandoc file that Word Online can't handle.

**Comment by jgm** [comment]
Try opening the original Calibre sample in regular Word, and see if it says "Compatibility Mode." This isn't determined entirely by the AppVersion.

**Comment by jgm** [comment]
To investigate further we'll need a sample that DOES fail to open with Word Online.  Can you give the exact input and pandoc command you used?

**Comment by jgm** [comment]
Are you sure you aren't using a custom reference.docx (e.g. in the user data directory, `~/.pandoc/` on unix)?

**Comment by fjellandermedia** [comment]
> Are you sure you aren't using a custom reference.docx (e.g. in the user data directory, ~/.pandoc/ on unix)?

Pretty sure. I installed Pandoc entirely fresh earlier today via homebrew on MacOs. 

> To investigate further we'll need a sample that DOES fail to open with Word Online. Can you give the exact input and pandoc command you used?
Sure! 

- Create a text file _input.txt_ with some simple string, e.g. "Hi! This is a test file!" in your code editor of choice. 
- Run pandoc -t docx -o output.docx input.txt

This file, when uploaded on OneDrive and opened in Word Online, can't be edited but is in read-only mode. At least for me.

**Comment by jgm** [comment]
There aren't too many differences between the reference.docx (which you say works) and a docx produced with a simple string.  I'm at a loss.  Unfortunately I can't test this myself.

**Comment by jgm** [comment]
Try using the same content as a reference.docx contains: Save this as input.md:

```
Heading 1
=========

Heading 2
---------

### Heading 3

#### Heading 4

##### Heading 5

###### Heading 6

####### Heading 7

######## Heading 8

######### Heading 9

First Paragraph.

Body Text. Body Text Char.`
Verbatim Char
`.[Hyperlink](http://example.com).Footnote.[^1]

> Block Text.

Table caption.

  Table   Table
  ------- -------
  1       2

  : Table caption.

Image Caption

DefinitionTerm

:   Definition

DefinitionTerm

:   Definition

[^1]: Footnote Text.
```
Then create a docx with `pandoc input.txt -o sample.docx`.  And see if Word Online likes that any better.

**Comment by jgm** [comment]
Oh, one more thing to check:  as of 2.7, pandoc checks the $XDG_DATA_HOME/pandoc for its user data files, only going to `~/.pandoc` if nothing is found there.  Default XDG_DATA_HOME is `~/.local/share`, so check also `~/.local/share/pandoc`.

**Comment by fjellandermedia** [comment]
First, I really appreciate you investigating this! Thanks!

>Oh, one more thing to check: as of 2.7, pandoc checks the $XDG_DATA_HOME/pandoc for its user data files, only going to ~/.pandoc if nothing is found there. Default XDG_DATA_HOME is ~/.local/share, so check also ~/.local/share/pandoc.

Nope, also empty.

>Then create a docx with pandoc input.md -o sample.docx. And see if Word Online likes that any better.

Nope, sorry, it does not. 🙁

**Comment by fjellandermedia** [comment]
I also tried the example docx-file on your examples webpage, [example29.docx](https://pandoc.org/demo/example29.docx). It didn’t work either.

**Comment by fjellandermedia** [comment]
>Unfortunately I can't test this myself.
I can give you an account on my developer O365 account if you’d like? But maybe that’s not the problem.

**Comment by fjellandermedia** [comment]
>Try using the same content as a reference.docx contains: 
I tried again, and the output of `pandoc --print-default-data-file reference.docx > custom-reference.docx` opens fine in Word Online. This is however not the same content as you posted above. I don't know how much it matters, though.

**Comment by jgm** [comment]
> I can give you an account on my developer O365 account if you’d like

If it's not too hard, this might help.  But then again:  I'm not sure what I'll be able to learn that you can't, given the lack of feedback about what the actual problem is.

I suppose another option could be to ask on a MS forum.  The docx pandoc produces should be up to Word 2007 standard, and their documentation says that these should open with full edit privileges in Word Online.

**Comment by jgm** [comment]
One more thought: if you have access to MS dev tools, you could try this little program to validate the docx pandoc produces.
https://docs.microsoft.com/en-us/office/open-xml/how-to-validate-a-word-processing-document
It might give us some more articulate feedback, if there is a problem.

**Comment by HeirOfNorton** [comment]
I think I found the problem. I have access to a SharePoint install (which uses the same Word Online as Office 365), and I messed around with the generated files until I could find what made it break.

The "numbering part" of the docx (word/numbering.xml) is being corrupted on output. Specifically, the w:abstractNum and w:num entries are duplicated. This is not the case in the template file that comes with Pandoc (which is why the output of --print-default-data-file still works). So the Docx writer is somehow re-writing those entries without removing or overwriting them from the original file.

Here's an example. In the archive, `numbering.xml` is the file as output by `pandoc --print-default-data-file=reference.docx`, and `numbering-bad.xml` is the exact same file output by `pandoc -t docx`.
[numbering.zip](https://github.com/jgm/pandoc/files/2949933/numbering.zip)

I know nothing about Haskell, so I couldn't begin to write a fix, but that's what's going wrong.

**Comment by fjellandermedia** [comment]
>I think I found the problem. I have access to a SharePoint install (which uses the same Word Online as Office 365), and I messed around with the generated files until I could find what made it break.

Wow, that’s great! Thanks a lot! 

@jgm I guess this would be an easy fix? (No hurry, though!)

**Comment by agusmba** [comment]
does this happen if you use a correct reference document?
I haven't had problems opening my pandoc-created docx, but I use a custom reference document.

**Comment by jgm** [comment]
Good detective work! I note that we "fixed" this
before in cf3b9a4058a6acba87d4dfe60dc9d0c0a3289d57.
That was a good change, but we overwrote it later
with: commit 596257f3506e3c89d9471c0b0a1a8c560aba41b2.

The fix wasn't robust. It would get overwritten in
people's custom reference.docx. So the solution is to
tell the docx reader NOT to carry over those elements
with w:numId >= 1000 or w:abstractNumId >= 990.

**Comment by jgm** [comment]
lines 468-476 of src/Text/Pandoc/Writers/Docx.hs
We just need to limit which old elements are carried over.
