### ISSUE TITLE
automatic newlines prevent use of \hspace* in beamer writer

### ISSUE THREAD

**Issue by darthoctopus** [jgm/pandoc#5361]
The input
```
\hspace*{-6ex}\includegraphics[width=\pagewidth]{figure.pdf}
```
produces the output
```
\hspace*{-6ex}

\includegraphics[width=\pagewidth]{figure.pdf}
```

Since the `\includegraphics` command is now in a new paragraph, the `\hspace*` command fails to take effect. I am seeing this using pandoc 2.6 installed from the AUR on arch linux.

**Comment by jgm** [comment]
You can avoid this by using the `raw_attribute` syntax:
````
```{=latex}
\hspace*{-6ex}\includegraphics[width=\pagewidth]{figure.pdf}
```
````
