### ISSUE TITLE
new \mainmatter breaks continous pagenumbering in latex + memoir

### ISSUE THREAD

**Issue by mbroedl** [jgm/pandoc#5362]
> pandoc 2.7
> Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7

As discussed in #5306 and introduced in b76ba44, there is now a `\mainmatter` in book-like latex documents. This resets the page counter (in memoir at least) and gives the front matter roman page numbering.

Technically it's good, but my writing guidelines suggest continuous page numbers from title page to last page, so the previous behaviour was correct. According to [stackexchange](https://tex.stackexchange.com/a/343089) a `\mainmatter*` in memoir would suffice to not overwrite the counter, but I cannot see an easy option to change this, and there seems to be no YAML-option?

**Workaround**
In the header.tex set arabic numerals manually, and then delete the command so that no counter can be reset (see [stackexchange](https://tex.stackexchange.com/a/343089) again).
```latex
\pagenumbering{arabic}
\renewcommand{\pagenumbering}[1]{}
```

**Comment by jgm** [comment]
You could use a header-includes that does something
like

   \renewcommand{\mainmatter}{\mainmatter*}

or a custom template.

**Comment by mbroedl** [comment]
This does not actually work because it ends up circular. Tried some simple \let sequences, but also without success (the stars are a bit messy to hack, if I remember correctly).

Looking at the template again, this yaml metadata worked (to my surprise).
Is there any way/reason to document this?
```yaml
book-class: false
```

This might also fix @habamax issue posted after #5306 was closed?

**Comment by jgm** [comment]
book-class is set automatically by the latex writer,
depending on the documentclass.  But you can override
this automatic value by specifying it explicitly.
So, as you see, it's not that the default is true;
the default varies with the documentclass.

**Comment by mbroedl** [comment]
Sorry, I realised that from the commit referenced.
I should have made more clear that I was confused to see that the default behaviour (book-class true/false) had changed with the last update when using the `memoir` class as indicated above (and the other classes identified as 'books').
Of course there is no problem to this, I just wanted to highlight that the default behaviour had changed, and looking back at the release notes I probably simply overlooked that this could be an issue for my case.

**Comment by brainchild0** [comment]
It is definitely possible to insert a LaTeX sequence  that either 1) invokes a command only if it is yet defined, or 2) that defines a command to a null operation only if it is not defined.  Other than the peculiarities of LaTeX semantics, which some understand better than others, I am aware of no major obstacle to doing so.  

Such solutions are much more robust and user-friendly than determining which commands are supported by looking in a static table of document classes, or relying on the user to set a particular option.
