### ISSUE TITLE
Improving appearance of subparagraph with indentation

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc#5365]
The `\paragraph` rewrite in the LaTeX template gives an odd appearance when indentation is enabled. Would you mind if I moved it so that these lines are only run when the `indent` option is false? Or would you prefer that I come up with a way of making this look right with indentation?

Here's an example showing an indented document, before and after the (sub)paragraph lines:

<img width="421" alt="Screen Shot 2019-03-13 at 21 21 52" src="https://user-images.githubusercontent.com/1084407/54324906-07577200-45d6-11e9-97f7-82421f8d638f.png">

```latex
\documentclass{article}
\usepackage{mwe}

\begin{document}

\paragraph{test}

\blindtext

\subparagraph{test}

\blindtext

\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\paragraph{test}

\blindtext

\subparagraph{test}

\blindtext

\end{document}
```

**Comment by jgm** [comment]
Normally paragraphs following headings aren't indented. So, if we want the default `\paragraph` and `\subparagraph` to resemble lower-level headings, that's how they should work too.  It should be fairly easy to add something after the `\mbox{}` that does this -- `\noindent` would work, but there may be something else that is standardly used for that.

Were there other aspects of the output you think need changing?

**Comment by adunning** [comment]
The `\noindent` command doesn't work here, as it turns out; I think we would need to modify the commands directly to fix the indentation issues. It would be much safer to add an extra conditional disabling the `\paragraph` modifications when `indent` is true.

The broader problem is that the template's modifications to `\paragraph` and `\subparagraph` remove all visual distinction between heading levels 3–5. We could fix this in a number of ways, for example by adding italics or small capitals, but this will inevitably create more problems with non-standard document classes. Further, it isn't obvious that problems with headings 4/5 need to be fixed with a variable called `subparagraph` – but that name is my fault, from <https://github.com/jgm/pandoc/commit/4698c2f5cb565619bc5bcc89024152b7696ed938>!

The change was originally prompted by #1658. This is an edge case, and it would be ideal if it could be addressed in `longtable` directly; I've opened an issue at <https://github.com/latex3/latex2e/issues/131> to see whether this is possible.

For reference, this is Pandoc's default PDF output:

<img width="141" alt="Screen Shot 2019-03-14 at 07 46 11" src="https://user-images.githubusercontent.com/1084407/54354520-3ea53d80-462d-11e9-9bfc-97b5af21d78e.png">

```shell
pandoc -o test.pdf << EOT

# Heading 1

test

## Heading 2

test

### Heading 3

test

#### Heading 4

test

##### Heading 5

test

EOT
```

This is the output with the default article class settings:

<img width="185" alt="Screen Shot 2019-03-14 at 07 47 09" src="https://user-images.githubusercontent.com/1084407/54354576-61cfed00-462d-11e9-874b-cb361884dc21.png">

```shell
pandoc -o test.pdf -V subparagraph -V indent << EOT

# Heading 1

test

## Heading 2

test

### Heading 3

test

#### Heading 4

test

##### Heading 5

test

EOT
```

**Comment by jgm** [comment]
It's currently possible to set `subparagraph` and `indent` together to get the output you want.
So, if I understand correctly, your proposal is to make it unnecessary to set `subparagraph` to get this output. This makes it impossible to get the output you display above (since `indent` would, effectively, imply `subparagraph`).  Probably that's okay, because it's pretty ugly output and it's hard to imagine anyone wanting it.  But on the other hand, it's not going to be clear to people why `indent` implies `subparagraph`, and might they not run into the issue with longtable?  So I'm not sure about this.

**Comment by adunning** [comment]
The brilliant LaTeX team came up with a much cleaner solution in <https://github.com/latex3/latex2e/issues/131#issuecomment-473256212> that works with or without indentation. We could include this in the template in place of the fix there now; though it would likely need to be emended slightly to ensure it isn't patched again if they include the fix in `longtable` itself:

```latex
\documentclass{article}
\usepackage{longtable}

% Ensure tables are placed after \paragraph and \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\par\if@noskipsec\mbox{}\fi}{}{}
\makeatother

\begin{document}
\begin{longtable}{l}
yyy
\end{longtable}

\paragraph{paragraph}

\begin{longtable}{l}
yyy
\end{longtable}

\subparagraph{subparagraph}
\begin{longtable}{l}
yyy
\end{longtable}

\paragraph{paragraph} abc

\begin{longtable}{l}
yyy
\end{longtable}

text
\begin{longtable}{l}
yyy
\end{longtable}

\section{blblb}

\begin{longtable}{l}
yyy
\end{longtable}

\end{document}
```

<img width="370" alt="Screen Shot 2019-03-15 at 12 50 37" src="https://user-images.githubusercontent.com/1084407/54447925-efd8d000-4720-11e9-8309-e771b62a7b56.png">

**Comment by jgm** [comment]
@adunning that's great.
One possibility is that we could just have the latex writer insert
```
\par\if@noskipsec\mbox{}\fi
```
between a level 3+ section header and a following table. Would this do the trick?  Then we wouldn't need any patching, and presumably this would be harmless even with a patched longtable?  (I'm guessing here; I actually don't understand it fully.)

If we did this, or added the fix you quote above to the template, what would you suggest doing about the existing `subparagraph` option and the indenting issue?

**Comment by adunning** [comment]
Good point: yes, adding this inline works. Contrary to what I thought, duplicating the line doesn't appear to have any effect. This should mean that we also don't have to worry about patching a potential updated version of the package.

The inline code would need to be more verbose, using `\makeatletter`, which makes me hesitant to suggest adding it in each location:

```latex
\documentclass{article}
\usepackage{longtable}

\begin{document}

\paragraph{paragraph}

\makeatletter\if@noskipsec\mbox{}\fi\makeatother % duplicating this line has no effect
\begin{longtable}{l}
yyy
\end{longtable}

\end{document}
```

My suggestion would be to remove the `subparagraph` code from the template and insert the `etoolbox` lines from above in its place (dependent on the `table` variable). I am basing this, however, on the commit message at <https://github.com/jgm/pandoc/commit/9ad336f586542cd8af30f2e16d2c935fb0f97a3e> that presents it as a fix to the `longtable` issue. I am not clear on whether you also wanted the modified aesthetics, or whether this was necessary collateral damage. (I approach improvements to the design of the default classes as beyond the template's scope, but you may have a different view on this.)

If you think the `\paragraph` modifications need to stay, I would suggest including the `longtable` patch regardless (it makes no difference if both this and the `subparagraph` code is included) and make `subparagraph` dependent on indentation being disabled:

```latex
$if(subparagraph)$
$else$
$if(indent)$
$else$
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
$endif$
$endif$
```

**Comment by jgm** [comment]
I'm of two minds.  Part of the motivation for the original change was to make the latex/pdf output of pandoc resemble the output in other formats more closely.  In other formats you have 5+ levels of headers, all of them on separate lines.  And part of the motivation was to fix the longtable issue.

At this point I'd rather have the default behavior be the standard latex one -- with paragraph and subparagraph creating a heading at the beginning of a paragraph, not on a separate line.  Perhaps the current default behavior could be added as on optional one -- keyed to a variable like `subsubsection` perhaps?  But of course it would be a behavior change, and one has to think carefully about that.

**Comment by adunning** [comment]
Keeping it as an optional variable would be a good compromise, and make it clearer that additional formatting needs to be applied when using this code to make headings level 4/5 distinguishable from level 3.

For the variable name, perhaps `block-headings`? `freestanding-headings`?

One could also go further and come up with a variable that would more fully emulate the default appearance of Pandoc output in other formats, making not only headings freestanding but also definition lists, using more sensible default font styles, and possibly applying smaller default margins (one could accomplish that easily using `scrartcl`). But I suspect that would become more of a distraction than it would merit.

**Comment by jgm** [comment]
> But I suspect that would become more of a distraction than it would merit.

Agreed.  About the other thing, my main concern is breaking existing behavior, which some people may be relying on.  If we did do that, `block-headings` sounds reasonable.

**Comment by adunning** [comment]
Absolutely: best to change the default appearance of PDFs only to fix things that are clearly wrong. I would argue that the lack of visual distinction in headings 3–5 puts this problem into that category, but it's on the edge. There's no question that some users would expect this style by default, and I am only suggesting its removal rather than improvement because I don't see a way to do so without causing further problems when using other document classes.

**Comment by jgm** [comment]
@adunning do you want to prepare a PR along these lines?
