### ISSUE TITLE
Table caption and footnote (again)

### ISSUE THREAD

**Issue by kysko** [jgm/pandoc#5367]
Footnotes in table captions were already addressed in issue #4683.

I'd never used a footnote on a caption, so didn't notice, but came up with this minimal example:

```
: Sample table.[^1]

-----------
 Fruit[^2]
-----------
 Bans[^3]
-----------

[^1]: one
[^2]: two
[^3]: three
```

The LaTeX output inserts the `\footnotetext{one}` at the very end of the table (after `\end{longtable}`), which makes the footnotes appear in the PDF like:
```
2. two
3. three
3. one
```
so, in the wrong order, and mislabeled with a duplicate number.

**Solution for now :** Moving the `\footnotetext{one}` just after the **first** `\toprule` though, for example, closest to its corresponding `footnotemark`, made the footnotes appear properly.

(yes, I know it's in the header, and the documentation says it's not supposed to be, but it works for now)

Placing it *after* the second `footnotemark` will also lead to a mislabel/misorder.

The [SE link](https://tex.stackexchange.com/questions/50151/footnotes-in-longtable-captions) referred to in issue #4683 (or rather the `longtable` documentation) does mention placing the `\footnotetext` 

> anywhere in the table body that will fall on the same page

But it does also say

>  Note however that \footnote will not work in the ‘head’ or ‘foot’ sections of the table. 

which contradicts my "solution" above, although it works... I'm confused!

Using a different markdown like

```
-----------
Fruit[^1]
-----------
Bans[^2]
-----------

: Sample table.[^3]

[^1]: one
[^2]: two
[^3]: three
```
won't help, since the `footnotemark` for the caption is placed near the top of the table, and the related `footnotetext` at the very end of the LaTeX table.

Since the `footnotetext` does seem to recognize being associated to the right `footnotemark`, the mislabeling/misordering is more a package bug (or lack of support) than a `pandoc` one, but as seen above it should be easy to fix (at least manually for now).

Note: LaTeX output with pandoc 2.6 and default template/standalone; compiled the same in TeXLive2018 (pdfLaTeX) as well as in Overleaf online LaTeX engine

(A few edits since first creation)

**Comment by kysko** [comment]
Apart from the apparent fact that putting `footnotetext` in the header section for caption seems to work, and that the LaTeX produced by pandoc does put it in the header, here are two more comments on the subject.

1) I don't know much about Haskell, but the code for [notesToLaTeX](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L914) does mention adding at one point the  command `\addtocounter`, but it doesn't seem to appear in the latex produced by pandoc.

   For the following markdown:

```
hello[^1]

: Sample table.[^2]

-----------
 Fruit[^3]
-----------
 Bans[^4]
-----------

dolly[^5]

[^1]: body footnote
[^2]: caption footnote
[^3]: header footnote
[^4]: table cell footnote
[^5]: body footnote
```
here's what the pandoc 2.7.1 demo gives:
```
hello\footnote{body footnote}

\begin{longtable}[]{@{}c@{}}
\caption[Sample table.]{Sample table.\footnotemark{}}\tabularnewline
\toprule
\begin{minipage}[b]{0.15\columnwidth}\centering
Fruit\footnotemark{}\strut
\end{minipage}
\footnotetext{header footnote}\tabularnewline
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{0.15\columnwidth}\centering
Fruit{}\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.15\columnwidth}\centering
Bans\footnotemark{}\strut
\end{minipage}
\footnotetext{table cell footnote}\tabularnewline
\bottomrule
\end{longtable}
\footnotetext{caption footnote}

dolly\footnote{body footnote}
```
no `addtocounter`.

2) Reading an [old SE question](https://tex.stackexchange.com/questions/43692/footnotetext-numbering-for-many-footnotemark-automatic-solution), I've added `addtocounter` and `stepcounter`, and put **all** the `footnotetext` after `end(longtable)`, even those in header and body of table:

```
hello\footnote{body footnote}

\begin{longtable}[]{@{}c@{}}
\caption[Sample table.]{Sample table.\footnotemark{}}\tabularnewline
\toprule
\begin{minipage}[b]{0.15\columnwidth}\centering
Fruit\footnotemark{}\strut
\end{minipage}
\tabularnewline
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{0.15\columnwidth}\centering
Fruit{}\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.15\columnwidth}\centering
Bans\footnotemark{}\strut
\end{minipage}
\tabularnewline
\bottomrule
\end{longtable}
\addtocounter{footnote}{-3} % -3, because a total of 3 footnotemarks in the table
% adding in the right sequence
\stepcounter{footnote}\footnotetext{footnote in caption}
\stepcounter{footnote}\footnotetext{header footnote}
\stepcounter{footnote}\footnotetext{table cell footnote}

dolly\footnote{body footnote}
 ```
This produces the intended result. I haven't tested this extensively, and don't know what other requirements people need. I seldom put notes in tables myself, stumbled upon this for other reasons.

I hope this helps.

**Comment by adunning** [comment]
More simply, the writer can be modified to use the standard `\footnote` command (which works because we're using the `footnotehyper` or `footnote` package). This produces what I assume is the expected output:

```latex
\documentclass{article}
\usepackage{longtable,booktabs}
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}

\begin{document}

\begin{longtable}[]{@{}c@{}}
\caption[Sample table.]{Sample table.\footnote{one}}\tabularnewline
\toprule
\begin{minipage}[b]{0.16\columnwidth}\centering
Fruit\footnote{two}\strut
\end{minipage}
\tabularnewline
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{0.16\columnwidth}\centering
Fruit{}\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.16\columnwidth}\centering
Bans\footnote{three}\strut
\end{minipage}
\tabularnewline
\bottomrule
\end{longtable}

\end{document}
```

**Comment by kysko** [comment]
Heh... that looks much simple indeed. Didn't see it, was working within current mechanism, and reading too old links!

Also, the package wasn't installed (I didn't make a full TeXLive install), so now I'll make sure to get it.

**Comment by adunning** [comment]
The potential incompatibility is with the `footnote` package; `footnotehyper` fixes it with version 1.0.

**Comment by kysko** [comment]
Yes, but the `footnotehyper` manual on p1 says (italics mine):

> Since v1.0 it is possible to use footnotehyper also in absence of hyperref _or when the latter is loaded with its hyperfootnotes=false option_.

As I said, haven't encountered any problem yet, so I may misunderstand the statement!

**Comment by adunning** [comment]
Yes, that's written to distinguish `footnotehyper` from the strictures provided in the `footnote` package documentation.

**Comment by adunning** [comment]
Many thanks, @jgm, for implementing this. It just occurs to me that it changes Beamer output, since `footnotehyper` does not function there. An easy solution would be removing the `minipage`s, but I haven't looked into the full background to their use.

Before:

![Screen Shot 2019-03-22 at 16 38 07](https://user-images.githubusercontent.com/1084407/54851605-e02d2e80-4cc0-11e9-8654-0370522f2bd0.png)

```latex
\documentclass{beamer}
\usepackage{longtable,booktabs}
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother

\begin{document}

\begin{frame}

\begin{longtable}[]{@{}c@{}}
\caption[Sample table.]{Sample table.\footnotemark{}}\tabularnewline
\toprule
\begin{minipage}[b]{0.16\columnwidth}\centering
Fruit\footnotemark{}\strut
\end{minipage}
\footnotetext{two}\tabularnewline
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{0.16\columnwidth}\centering
Fruit{}\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.16\columnwidth}\centering
Bans\footnotemark{}\strut
\end{minipage}
\footnotetext{three}\tabularnewline
\bottomrule
\end{longtable}
\footnotetext{one}

\end{frame}

\end{document}
```

After:

![Screen Shot 2019-03-22 at 16 37 16](https://user-images.githubusercontent.com/1084407/54851556-c25fc980-4cc0-11e9-91c4-37e9323e55f9.png)

```latex
\documentclass{beamer}
\usepackage{longtable,booktabs}
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother

\begin{document}

\begin{frame}

\begin{longtable}[]{@{}c@{}}
\caption[Sample table.]{Sample table.\footnote{one}}\tabularnewline
\toprule
\begin{minipage}[b]{0.16\columnwidth}\centering
Fruit\footnote{two}\strut
\end{minipage}
\tabularnewline
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{0.16\columnwidth}\centering
Fruit{}\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.16\columnwidth}\centering
Bans\footnote{three}\strut
\end{minipage}
\tabularnewline
\bottomrule
\end{longtable}

\end{frame}

\end{document}
```

Without `minipage`:

![Screen Shot 2019-03-22 at 16 47 57](https://user-images.githubusercontent.com/1084407/54852112-3fd80980-4cc2-11e9-8b3b-ecf62ec48eee.png)

```latex
\documentclass{beamer}
\usepackage{longtable,booktabs}
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother

\begin{document}

\begin{frame}

\begin{longtable}[]{@{}c@{}}
\caption[Sample table.]{Sample table.\footnote{one}}\tabularnewline
\toprule
Fruit\footnote{two}\tabularnewline
\midrule
\endfirsthead
\toprule
Fruit\tabularnewline
\midrule
\endhead
Bans\footnote{three}\tabularnewline
\bottomrule
\end{longtable}

\end{frame}

\end{document}
```

**Comment by jgm** [comment]
Re-opening to fix this issue with beamer.

Looks like minipages were added in dd6dab45fb4d55ff6aaeda2707526bc1e2e3b0bb
because of #663 (specifically for verbatim code in grid tables).

Maybe there's another way to do this?  Or maybe we could change things so that parbox is used instead of minipage, unless minipage is needed because the cell contains a verbatim, rather than using minipage everywhere?

**Comment by jgm** [comment]
Actually when I try with beamer, it doesn't even compile:
```
% pandoc -o my.pdf -t beamer
hello[^1]

: Sample table.[^2]

-----------
 Fruit[^3]
-----------
 Bans[^4]
-----------

dolly[^5]

[^1]: doc footnote
[^2]: caption footnote
[^3]: header footnote
[^4]: table cell footnote
[^5]: doc footnote
^D
Error producing PDF.
! Undefined control sequence.
<argument> \@@magyar@captionfix 
                                
l.96 \begin{document}
```

**Comment by jgm** [comment]
Note that
```
: Sample table.[^1]

-----------
 Fruit[^2]
-----------
 Bans[^3]
-----------

[^1]: one
[^2]: two
[^3]: three
```
isn't correct for any supported pandoc table format.  For a simple table, you'd want
```
: Sample table.[^1]

-----------
 Fruit[^2]
 Bans[^3]
-----------

[^1]: one
[^2]: two
[^3]: three
```
which works fine in beamer.

**Comment by jgm** [comment]
OK, I think this is all fixed now.
