### ISSUE TITLE
Headers in Div following bulletlist without blank line before are not recognized correctly

### ISSUE THREAD

**Issue by jiewuza** [jgm/pandoc#5375]
Here is a demo doc
```
:::: header-in-div
# Header1
- bullet1
- bullet2
## header2
....
::::
```

Run `pandoc -f markdown-blank_before_header demo.md -o demo.tex --lua-filter=test.lua`.
(note the `-blank_before_header` option)

I find in the lua-filter that there are only 2 elements in the div.

 But if I add a blank line before `header2`, there are 4 elements in the div.

This is my test.lua
```
function Div(el)
   print(#el.content)
end
```

**Comment by mb21** [comment]
> I find in the lua-filter that there are only 2 elements in the div.

yes, apparently the first header and the list. The second header is part of the list item. Btw, you can also debug things like this with `-t native`.

There are a lot of edge-cases involved here, including the extensions. Posting some output:

```
$ pandoc -f markdown-blank_before_header
# Header1
- bullet1
- bullet2
## header2
....

<h1 id="header1">Header1</h1>
<ul>
<li>bullet1</li>
<li><p>bullet2</p>
<h2 id="header2">header2</h2>
<p>….</p></li>
</ul>

$ pandoc -f markdown                    
# Header1
- bullet1
- bullet2
## header2

<h1 id="header1">Header1</h1>
<ul>
<li>bullet1</li>
<li>bullet2 ## header2</li>
</ul>

$ pandoc -f commonmark
# Header1
- bullet1
- bullet2
## header2

<h1>Header1</h1>
<ul>
<li>bullet1</li>
<li>bullet2</li>
</ul>
<h2>header2</h2>
```

**Comment by jgm** [comment]
Not a bug. See the documentation for the `blank_before_header` extension.
Pandoc markdown requires a blank line before an ATX header.
You can use `markdown-blank_before_header` or `commonmark`.

**Comment by jiewuza** [comment]
> yes, apparently the first header and the list. The second header is part of the list item. 

@mb21 You are right. 
But note that I have already used `markdown-blank_before_header`. 
So I expect 4 elements in the div (Header, BulletList, Header and Para).
But no. I just got 2 elements.

@jqm
I have already used `markdown-blank_before_header`.

**Comment by jiewuza** [comment]
I test `markdown-blank_before_header` with (bulletlist replaced by regular text)
```
:::: header-in-div
# Header1
regular text
## header2
....
::::
```

It works as expected. 

So I think the problem lies in the bulletlist.
There must be a blank line after it.

**Comment by mb21** [comment]
Yeah, looks like lazy list continuation... from https://pandoc.org/MANUAL.html#bullet-lists:

> But Markdown also allows a “lazy” format:
> 
>     * here is my first
>     list item.
>     * and my second.


you cannot just add a newline?

**Comment by jiewuza** [comment]
Since other elements do not require a blank line before headers with `-blank_before_header`,
it is quite easy missing the blank line.
And `-blank_before_header` also suggests there could be no blank line to make the headers work.

So I thought it's bug.
Maybe we should stop the lazy list when it encounters a header with`-blank_before_header`?

**Comment by mb21** [comment]
Maybe.. I think @jgm has been working on a new markdown reader implementation that's commonmark-compliant, so might make sense to look at this then...

**Comment by jgm** [comment]
Not clear whether this is a bug; this is one of those underspecified corners of Markdown (since one could argue that the `## header 2` is a lazy continuation line).

Commonmark tries to clean all of this up and specify it.  And indeed, with `pandoc -f commonmark` you'll find that
```
# Header1
- bullet1
- bullet2
# Header2
```
works as you'd expect.  (But fenced divs aren't supported yet.)

**Comment by jiewuza** [comment]
@mb21 @jqm
I came across this situation by accident.
At first I thought it was a bug. But it is really hard to tell :)

I cannot switch to commonmark, as I used fenced divs.
I am looking forward to the new markdown reader ;)
