### ISSUE TITLE
extract media as high quality png images

### ISSUE THREAD

**Issue by anuragnagarkota** [jgm/pandoc#5376]
Hi

I am converting docx file to latex. It is working fine but there are tow issues-

1. It is extracting images as .emf file
2. the quality of emf file is very poor

How can I get png file with good quality?

**Comment by mb21** [comment]
Can you post a minimal example of such a docx file? What program are you displaying the emf files in?

**Comment by anuragnagarkota** [comment]
i am using the following command-
>pandoc  -o convert.tex input.docx --extract-media=DIR

Here after running the above command the images from the input.docx file are extracted into DIR folder but have .emf extension but I want them to be .png files.

**Comment by jgm** [comment]
They must be stored as .emf in the docx container;
that's why they come out that way.  You can use
imagemagick or a similar tool to convert them to png.

**Comment by alerque** [comment]
@anuragnagarkota This sounds like a case of "garbage in, garbage out." In most cases Pandoc seems to dump the media out in the same format as the container stored it. As suggested by jgm it doesn't sound like you have high quality PNGs embeded in the first place.

You can always write a lua filter to munge the document and run all the EMF images through ImageMagic and convert them to PNG, but image processing and format conversion isn't Pandoc's job.
