### ISSUE TITLE
Headers followed by an empty BulletList item has `#` in header content

### ISSUE THREAD

**Issue by jiewuza** [jgm/pandoc#5379]
Here is a demo doc
```
# Header1
## header2
-
- bullet2
```

$ pandoc -f markdown-blank_before_header+lists_without_preceding_blankline
```
<h1 id="header1">header1</h1>
<h2 id="header2">## header2</h2>
<ul>
<li>bullet2</li>
</ul>
```

You can see that the header2 got `##` in its content.
Also note that I have used `markdown-blank_before_header+lists_without_preceding_blankline`.

**Comment by jiewuza** [comment]
While for
```
# Header1
## header2
- bullet1
- bullet2
```
(bullet1 is not empty )
Everything just works fine.

**Comment by mb21** [comment]
This is the same as https://github.com/jgm/pandoc/issues/5375 (the div has nothing to do with it).

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
