### ISSUE TITLE
Add JSMD (markdown) support

### ISSUE THREAD

**Issue by wizzup** [jgm/pandoc#5380]
[JSMD](https://iodide-project.github.io/docs/jsmd/), is a markdown format for Mozilla [ Iodide](https://github.com/iodide-project/iodide) notebooks.

**Comment by mb21** [comment]
It might be possible to implement this as an extension on the markdown reader/writers...

Basically it seems that they just went with `%% python` instead of ` ``` python ` to open a code block. It's unclear to me why they felt the need invent yet another such syntax. They even mention:

> This format is inspired by [...] .Rmd (RMarkdown notebook) files.

But `iodide` is a very new project, maybe they're still open to change? Either way, looks like an interesting thing. Basically a web-first Jupiter/Rmarkdown notebook-like environment, if I understand correctly.

**Comment by wizzup** [comment]
I think notebook in markdown is better than current Jupyter's [ipynb](https://nbformat.readthedocs.io/en/latest/format_description.html) format because it is human-readable and allowed editing notebook directly in text editor.

**Comment by jgm** [comment]
Does this have widespread use yet?
If we do support it, we should use the same AST representation of a notebook that we use for ipynb; this would facilitate translations between this format and ipynb.

**Comment by wizzup** [comment]
> Does this have widespread use yet?

Not yet, Iodide is still in alpha state but the markdown format is unlikely to have any major change (IMHO)

**Comment by mb21** [comment]
Some background about the project: https://hacks.mozilla.org/2019/03/iodide-an-experimental-tool-for-scientific-communicatiodide-for-scientific-communication-exploration-on-the-web/

I could perhaps start with the markdown writer, so you could do `pandoc -f ipynb -t jsmd`.
`jsmd` would be implemented as a new writer that mostly calls the markdown writer, similar to how the epub writer mostly calls the html writer...

**Comment by esg** [comment]
The Iodide project development and maintenance has ceased: <https://github.com/iodide-project/iodide/blob/master/README.md>. Perhaps this issue could be closed?
