### ISSUE TITLE
Nested <b> tags don't convert to Markdown correctly (and don't roundtrip to <b>)

### ISSUE THREAD

**Issue by cjerdonek** [jgm/pandoc#5381]
Nested `<b>` tags don't seem to convert to Markdown correctly.

Example: https://pandoc.org/try/?text=a+%3Cb%3Eb%3C%2Fb%3E+%3Cb%3E%3Cb%3Ec%3C%2Fb%3E%3C%2Fb%3E+d&from=html&to=markdown

* `a <b>b</b> <b><b>c</b></b> d` ->
* `a **b** ****c**** d`

This, in turn, roundtrips to: https://pandoc.org/try/?text=a+**b**+****c****+d%0A&from=markdown&to=html5

* `a **b** ****c**** d`
* `<p>a <strong>b</strong> ****c**** d</p>`

It seems like `<b><b>c</b></b>` should convert the same as `<b>c</b>` (just converting to bold `**c**`).

**Comment by cjerdonek** [comment]
It's possible there's a similar issue with nesting of other tags, but I haven't checked.

**Comment by jgm** [comment]
Happy to report that round-tripping this works for commonmark and gfm:
```
 % pandoc -f commonmark -t html | pandoc -f html -t commonmark
a **b** ****c**** d
a **b** ****c**** d
```
Pandoc's markdown just treats sequences of 4 or more `*`s as literal. Eventually we'll move over to commonmark as the basis for pandoc's markdown, but for now, there's not much that can be done, so...closing.

In general round-tripping isn't going to be idempotent.

**Comment by cjerdonek** [comment]
Oh, great, thanks!
