### ISSUE TITLE
nested unordered lists not recognized with uppercase Roman numbers when starting from 2

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#5382]
pandoc doesn’t recognize nested lists from uppercase Roman numerals when the starting number is different from one:

``` markdown
II.  item.
    - item.
    - item.
I.  item.
    - item.
    - item.
i. item.
    - item.
    - item.
1. item.
    - item.
    - item.
a. item.
    - item.
    - item.
A.  item.
    - item.
    - item.
```

[HTML 5 output](http://pandoc.org/try/?text=II.++item.%0A++++-+item.%0A++++-+item.%0AI.++item.%0A++++-+item.%0A++++-+item.%0Ai.+item.%0A++++-+item.%0A++++-+item.%0A1.+item.%0A++++-+item.%0A++++-+item.%0Aa.+item.%0A++++-+item.%0A++++-+item.%0AA.++item.%0A++++-+item.%0A++++-+item.%0A&from=markdown&to=html5):

``` html
<ol start="2" type="I">
<li>item. - item. - item.</li>
<li>item.
<ul>
<li>item.</li>
<li>item.</li>
</ul></li>
</ol>
<ol type="i">
<li>item.
<ul>
<li>item.</li>
<li>item.</li>
</ul></li>
</ol>
<ol type="1">
<li>item.
<ul>
<li>item.</li>
<li>item.</li>
</ul></li>
</ol>
<ol type="a">
<li>item.
<ul>
<li>item.</li>
<li>item.</li>
</ul></li>
</ol>
<ol type="A">
<li>item.
<ul>
<li>item.</li>
<li>item.</li>
</ul></li>
</ol>
```

**Comment by jgm** [comment]
Your inner list isn't indented enough.  It needs to
line up with the first nonspace content after the
parent list.

(Or, you may want to enable the `four_space_rule`
extension.)

**Comment by ousia** [comment]
@jgm, many thanks for your fast reply.

I enablee the `four_space_rule` extension.

I wonder whether it would make sense to document this in the user guide.

**Comment by jgm** [comment]
It is documented.

> A list item may contain multiple paragraphs and other block-level content. However, subsequent paragraphs must be preceded by a blank line and indented to line up with the first non-space content after the list marker.

**Comment by ousia** [comment]
@jgm, I’d say it isn’t especially clear (although it is documented there).

I wonder whether the code sample that comes next could include a sample of what is meant with that description.

``` md
i. item
    - subitem
    - subitem

I.  but special item (2 spaces before)
    -  subitem needs two spaces before too
```

Just in case it might help.
