### ISSUE TITLE
Custom bulleted itemize env with Latex input and epub output

### ISSUE THREAD

**Issue by robinp** [jgm/pandoc#5386]
I have a custom `itemize` env in latex which overrides the bullet:

```
\newlist{mitigations}{itemize}{1}
\setlist[mitigations]{leftmargin=2em,label={\footnotesize{$\yinyang$}}}
```
```
\begin{mitigations}
\item foo
\end{mitigations}
```
But this doesn't even seem to have the bullets (let alone the specific one), when converting to epub.

Is there a suggestion here? First to accept this as a standard itemize env (with bullets), and maybe even to have the customized bullets. Thank you!

*Edit*: Actually, it's not a grave issue. I can use some output-dependent includes to switch the style used for epub.

**Comment by jgm** [comment]
We don't support `\newlist` (part of enumitem).
Workaround:  add this to the beginning of your latex document or preamble:
```
\newenvironment{mitigations}{\begin{itemize}}{\end{itemize}} 
```
This will cause the mitigations list to be parsed as a standard bullet list.

**Comment by robinp** [comment]
Thank you!
