### ISSUE TITLE
nested lines with tagging

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#5387]
``` markdown

works

- item:
    <div class="two-cols">
    - item
    - item
    - item
    - item
    </div>
- item
- item

doesn’t work

- item:
    ::: {.two-cols}
    - item
    - item
    - item
    - item
    :::
- item
- item

loose list

- item:

    ::: {.two-cols}
    - item
    - item
    - item
    - item
    :::
- item
- item
```

I get this output:

``` html
<p>works</p>
<ul>
<li>item:
<div class="two-cols">
<ul>
<li>item</li>
<li>item</li>
<li>item</li>
<li>item</li>
</ul>
</div></li>
<li>item</li>
<li>item</li>
</ul>
<p>doesn’t work</p>
<ul>
<li>item: ::: {.two-cols}
<ul>
<li>item</li>
<li>item</li>
<li>item</li>
<li>item :::</li>
</ul></li>
<li>item</li>
<li>item</li>
</ul>
<p>loose list</p>
<ul>
<li><p>item:</p>
<div class="two-cols">
<ul>
<li>item</li>
<li>item</li>
<li>item</li>
<li>item</li>
</ul>
</div></li>
<li><p>item</p></li>
<li><p>item</p></li>
</ul>
```
pandoc-2.7.1 gives different output ([link to HTML5 code](http://pandoc.org/try/?text=%0Aworks%0A%0A-+item%3A%0A++++%3Cdiv+class%3D%22two-cols%22%3E%0A++++-+item%0A++++-+item%0A++++-+item%0A++++-+item%0A++++%3C%2Fdiv%3E%0A-+item%0A-+item%0A%0Adoesn%E2%80%99t+work%0A%0A-+item%3A%0A++++%3A%3A%3A+%7B.two-cols%7D%0A++++-+item%0A++++-+item%0A++++-+item%0A++++-+item%0A++++%3A%3A%3A%0A-+item%0A-+item%0A%0Aloose+list%0A%0A-+item%3A%0A%0A++++%3A%3A%3A+%7B.two-cols%7D%0A++++-+item%0A++++-+item%0A++++-+item%0A++++-+item%0A++++%3A%3A%3A%0A-+item%0A-+item%0A&from=markdown&to=html5)), since I cannot set the `four_space_rule` extension.

Shouldn’t be Markdown tagging read the same way as XML tags?

Many thanks for your help.

**Comment by jgm** [comment]
From the documentation:

>  The fenced Div should be separated by blank lines from preceding and following blocks.

The case of `<div>` is rather different. There is no way to treat this as inline content; it's completely unambiguous, since `<div>` is a block-level tag.  But `:::` is possible inline content.

**Comment by ousia** [comment]
> The case of `<div>` is rather different. There is no way to treat this as inline content; it's completely unambiguous, since `<div>` is a block-level tag. But `:::` is possible inline content.

Many thanks for your reply, @jgm.

At the beginning of a line, `::: {` should be unambiguous too.

Or at least, both `::: {.` and `::: {#` should be.
