### ISSUE TITLE
feature request: strikethrough in pdf

### ISSUE THREAD

**Issue by isomorphisms** [jgm/pandoc#5395]
I see at https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/HTML.hs#L1034 that `<strike>` has been implemented for `~~words~~` in HTML.

Could (via roff or latex or … I don’t know) PDF’s render the `~~words~~` instruction as text covered by a black box?  (rectangle at the appropriate (x,y) coordinates)

**Comment by jgm** [comment]
`~~words~~` is already rendered to PDF as strikeout (line through) via intermediate latex `\sout{words}`.

You could add a `\renewcommand` to your `header-includes` to redefine `\sout` so it creates a black box.  But this is not the right place to ask questions.  Please ask on the pandoc-discuss mailing list.
