### ISSUE TITLE
Citations rendered incorrectly when writing JATS

### ISSUE THREAD

**Issue by coryschires** [jgm/pandoc#5397]
## Background
Most of my JATS articles are failing to pass the [PubMed Central validator](https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker). I understand folks use JATS for lots of different purposes (archiving, publishing, etc), and your desired formatting may depend on your use case. Nevertheless, [PubMed Central](https://www.ncbi.nlm.nih.gov/pmc) is one of the main reasons journals use JATS – especially medical journals. So, I think it would be desirable – if not expected – for the rendered JATS to pass the PMC validator.

## Problem
So far I have seen two specific issues both related to how citations are rendered. For this reason, I am pretty darn sure the problem lies somewhere in [`pandoc/data/jats.csl`](https://github.com/jgm/pandoc/blob/master/data/jats.csl). But I am not a CSL expert, so?

#### 1. Punctuation between citations elements should be removed
JATS citations often contain commas floating between name-part elements:

    ...</name>, <name>...
    Element name content does not follow the DTD, expecting (((surname , given-names?) | given-names) , prefix? , suffix?), got (surname CDATA given-names)

This causes the PMC validator to fail. Specifically, the citations are placed in `<element-citation>` tags which [according to the spec](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/element-citation.html) should contain "no untagged text and all the punctuation and spacing between elements [should be] removed". So the loose commas are not allowed.

To fix this, we could either (a) remove the loose punctuation or (b) wrap the citation in [`<mixed-citation>`](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/mixed-citation.html) which tolerates loose text (unlike `<element-citation>`). FWIW, my preference would be to remove the loose punctuation.

#### 2. Mis-formatted `pub-id` element in citations
When a DOI is present in the citation metadata, the PMC validator fails with the following error:

    <pub-id pub-id-type="doi">
      <ext-link ext-link-type="uri" xlink:href="https://doi.org/10.1186/1471-2288-4-25">10.1186/1471-2288-4-25</ext-link>
    </pub-id>
    Error: Element pub-id was declared #PCDATA but contains non text nodes

[Based on the JATS spec](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/pub-id.html), the `<pub-id>` tag should contain only an ID string. For example, I can make the previous example pass PMC validation by changing it to:

    <pub-id pub-id-type="doi">10.1186/1471-2288-4-25</pub-id>

It's possible I could discover other issues as I continue to test different types of articles. If so, I'll follow up. But these two problems are very consistent and easy to reproduce.

#### Pandoc version
2.7.1

#### Files
[jats-example-files.zip](https://github.com/jgm/pandoc/files/3009341/jats-example-files.zip)

#### To reproduce the issues described above:
1. `pandoc -s --metadata-file metadata.json --bibliography bib.json --filter pandoc-citeproc --csl jats.csl --to jats example.md -o output.xml`
2. Validate `output.xml` using the PMC online validation tool: https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker
3. The validation tool will display the errors described above

**Comment by jgm** [comment]
Thanks for the feedback. I don't think these issues will be too hard to fix.

**Comment by jgm** [comment]
2 is done.
1 is trickier.  jats.csl contains
```xml
 <name prefix="{{jats}}&lt;name&gt;{{/jats}}" suffix="{{jats}}&lt;/name&gt;{{/jats}}" name-as-sort-order="all" sort-separator="">
```
but it looks like pandoc-citeproc is ignoring `sort-separator=""` and using the default sort separator.  Actually, it's not ignoring it completely, since if you set it to `!!!` you'll see that in the output.  My guess is that it's responding to an empty value by substituting the default, which would be a bug in pandoc-citeproc. I'll look into that next.

**Comment by jgm** [comment]
I've fixed the issue with `sort-separator` in pandoc-citeproc, but there's still a similar issue with `delimiter`.

**Comment by coryschires** [comment]
Thanks for fixing this so quickly! 

Based on your comment, I tried adding a blank space to `sort-separator`:
    
    <... sort-separator=" "> // instead of
    <... sort-separator="">

And that seems to remove the punctuation. Definitely a hack, but not terrible imo.

Once you release a new version, I'll update and let you know how everything shakes out. 

Thanks again!

**Comment by jgm** [comment]
Do the same thing on `names`:
```
    <names variable="author" delimiter=" ">
```
That should fix the remaining commas
