### ISSUE TITLE
Double dash is lost in man page

### ISSUE THREAD

**Issue by joto** [jgm/pandoc#5404]
I have written some man pages in markdown and convert them to roff. It used to be that double dashes `--` came out okay (tested with pandoc 1.17.2) but now (pandoc 2.2.1) the double dash is converted to a single dash. It seems the markdown reader interprets `--` as an en-dash which the roff-writer writes as `[en]` which is then displayed as a single `-`. I can revert to the earlier behaviour using `-f markdown-smart`, but I still consider this is a bug.

Example input here: https://github.com/osmcode/osmium-tool/blob/master/man/osmium-cat.md

See osmcode/osmium-tool#161

**Comment by mb21** [comment]
I think this is intended behaviour. As you mentioned, you can either turn this off with `markdown-smart`, or you can also prevent this on a case-by-case basis, by using `\--foo` instead of `--foo` in the markdown input.

**Comment by joto** [comment]
Okay, thanks. The `\--foo` is a good workaround for me that works in old and new pandoc.
