### ISSUE TITLE
Using BST Files for Citations?

### ISSUE THREAD

**Issue by frastlin** [jgm/pandoc#5405]
Hello,
It would be very nice if pandoc could use bst files to format citations rather than just csl.
I was given a customized BST file from a conference for formatting citations. I've managed to kind of reproduce it using a similar CSL document, but not exactly.
There doesn't seem to be any kind of method for converting from bst to csl, so I'm not sure what others in this situation do.
Thanks,

**Comment by mb21** [comment]
Perhaps you're looking for pandoc's `--biblatex` option?

**Comment by frastlin** [comment]
It's not extremely clear how you get a .docx or pdf from the output from --biblatex.

> Use biblatex for citations in LaTeX output. This option is not for use with the pandoc-citeproc filter or with PDF output. It is intended for use in producing a LaTeX file that can be processed with bibtex or biber.

What it sounds like is that I need to install bibtex or biber, then use the latex output I get from running pandoc with the --biblatex option with biber. I have no idea what output biber produces, but it's probably not the same outputs you get with pandoc.
It seems as if this is kind of defeating the reason for using pandoc in the first place.

**Comment by mb21** [comment]
Well, pandoc calls LaTeX (and by extension BibTeX as far as I know) when it produces a pdf. See https://pandoc.org/MANUAL.html#creating-a-pdf

So you should be able to do something like:

    pandoc --biblatex --bibliography=foo.bst input.md output.pdf

or equivalently:

    pandoc --metadata bibliography=foo.bst input.md output.pdf

**Comment by frastlin** [comment]
The bst file is for how the citations should be formatted. It's the csl file, but in bst. I attached it to this post:
[IEEEtran.txt](https://github.com/jgm/pandoc/files/3023393/IEEEtran.txt)

**Comment by jgm** [comment]
You can use a bst with `--biblatex` and output to PDF/LaTeX, but not other formats.
pandoc-citeproc does not (and will not) support bst.

**Comment by jgm** [comment]
I'm sorry, my answer was misleading. `--biblatex` isn't compatible with `.bst` files.

You can instead use `--natbib`.

So, in your markdown document, include this YAML metadata:
```
---
biblio-style: IEEEtran
bibliography: name-of-your-bibtex-bibliography
...

Then citations as usual [@smith2000, p. 33].
```
Try running this using
```
pandoc input.md --natbib --pdf-engine=latexmk -o output.pdf
```
If that doesn't work, you can create a tex file and process it in the usual way
```
pandoc input.md --natbib -t latex -s -o output.tex
pdflatex output
bibtex output
pdflatex output
pdflatex output
```

PS. This tracker is for bug reports. For questions (including any further questions about this), use the pandoc-discuss mailing list.

**Comment by frastlin** [comment]
Thank you!
