### ISSUE TITLE
unable to install pandoc from rstudio

### ISSUE THREAD

**Issue by ImSanjayChintha** [jgm/pandoc#5406]
I am unable to install pandoc due to github issue. I am not able to understand how to fix this below one. please help anyone!

![](https://i.stack.imgur.com/56Tc8.png)

**Comment by tarleb** [comment]
I'm closing this, as it is not a pandoc issue. The problem seems related to R and its tools.

As an aside: posting pictures of error messages is generally frowned upon, see http://idownvotedbecau.se/imageofcode for why.

**Comment by mb21** [comment]
For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by ImSanjayChintha** [comment]
I am still unable to figure it out what is cause of issue, anyway I can overpass pandoc issue by running a command in r studio:

shinyloadtest_report(df,"run1.html",self_contained=F)

Hence my issue was resolved.
