### ISSUE TITLE
Input error from man page

### ISSUE THREAD

**Issue by tdhawk** [jgm/pandoc#5410]
I'm piping a man page from zcat to pandoc and outputting HTML. This works great most of the time but occasionally fails on certain man pages. The error it fails with is:

`Error at "input" (line 184, column 1):
unexpected end of input
expecting ".", "\\}", ".\\\"", "'", "\\", "\"", " ", "\t" or lf new-line
`
I'm using pandoc 2.7.1

The command line I'm using is:
`zcat /usr/share/man/man1/piconv.1.gz | pandoc --from=man --to=html -o /home/user/man/piconv.html`

The full content of one of the man pages causing the issue:
Pasting it in a code block didn't format well. File can be found at https://github.com/tdhawk/manpage/blob/master/manpage

**Comment by jgm** [comment]
Minimal repro:
```
.ie n \{\
'br\}
.el \{\
'br\}
```

**Comment by jgm** [comment]
Relevant code is in lexConditional in Roff reader.
