### ISSUE TITLE
fb2 produced from odt have invalid <empty-line /> tags

### ISSUE THREAD

**Issue by vbwagner** [jgm/pandoc#5419]
pandoc 1.17.2 from debian stable produces following fb2 markup when converting odt file:
```
</p>
<p><emptyline /> sometext</p>
```
or
``` 
<p>somethext<empty-line /> more text</p>
```
However, Fiction Book schema doesn't allow `<empty-line>` inside paragraph.
These examples should be
```
</p>
<empty-line/>
<p> sometext
```
and 
```
<p>sometext</p><emptyline /><p> more text</p>
```
respectively.

**Comment by mb21** [comment]
Can you try with the newest pandoc version and also attach the input file?

**Comment by vbwagner** [comment]
Version 2.7.1, downloaded from this site, doesn't have this problem.

**Comment by mb21** [comment]
great, then we can close this.
