### ISSUE TITLE
(Harmless) error in filescope code?

### ISSUE THREAD

**Issue by jkr** [jgm/pandoc#5422]
@jgm: I was looking at the implementation of file-scope, and saw the following in App.hs (l. 254):

~~~ haskell
    let sourceToDoc :: [FilePath] -> PandocIO Pandoc
        sourceToDoc sources' =
           case reader of
                TextReader r
                  | optFileScope opts || readerName == "json" ->
                      mconcat <$> mapM (readSource >=> r readerOpts) sources
                  | otherwise ->
                      readSources sources' >>= r readerOpts
                ByteStringReader r ->
                  mconcat <$> mapM (readFile' >=> r readerOpts) sources
~~~

Note that when it does filescope, it uses an unprimed `sources`, which is a bound value, not the argument to the function. It doesn't make a difference at the moment, because the function is just run on `sources` 20 lines later. But this is an error, right? Or am I missing something?

**Comment by jgm** [comment]
@jkr Weren't you the one who wrote this code?
I think you're right, it looks like a mistake.
You could check the git history for this part of
the code to make sure nobody made the change
intentionally.

**Comment by jgm** [comment]
Ah, I see -- I did write this.  I'm sure it's just a mistake.
