### ISSUE TITLE
Table in odt format convert to markdown incorrect

### ISSUE THREAD

**Issue by rickywu** [jgm/pandoc#5425]
pandoc 2.7.1
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7

Try this command with zip file:
`pandoc libre.odt -f odt -t gfm+pipe_tables+gfm_auto_identifiers+shortcut_reference_links --atx-headers --wrap=none --extract-media="" -o out.md`

[libre.zip](https://github.com/jgm/pandoc/files/3036460/libre.zip)

1.Convert to markdown, the table header position is incorrect, see line 3,
also column in merged cells incorrect

```
|           |            |            |         |
| --------- | ---------- | ---------- | ------- |
| Type1     | Type2      | Req        | Comment |
| Req       | Project    | User story |         |
| Inv spec. |            |            |         |
| Task      | User story |            |         |
| Fun spec. |            |            |         |
| T2        |            |            | N/A     |
```

2.Convert to markdown, table with multi line missed header row
```
<table>
<tbody>
<tr class="odd">
<td>Item</td>
<td>Type</td>
<td>Desc</td>
</tr>
<tr class="even">
<td>Req#</td>
<td>auto</td>
<td>A</td>
</tr>
<tr class="odd">
<td>Req template</td>
<td>dropdown</td>
<td><p>Some desc</p>
<p>Other desc.</p></td>
</tr>
<tr class="even">
<td>Name</td>
<td>Input</td>
<td></td>
</tr>
</tbody>
</table>

```

**Comment by mb21** [comment]
When I open your file in LibreOffice and place the cursor in a cell of the first row, it just says "Default Style" in the style dropdown:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/157497/55461386-96afde00-55f4-11e9-94ad-d25fee120632.png">

But it should be "Table Heading", I think:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/157497/55461413-a7f8ea80-55f4-11e9-86b0-055bcd2fd8f2.png">

**Comment by mb21** [comment]
If you look at the contained XML:

    unzip -d foo libre.odt
    cat foo/content.xml

The cells in the first and second row have both have the same `style-name`:

            <table:table-row table:style-name="Table1.1">
               <table:table-cell table:style-name="Table1.A1" office:value-type="string">
                  <text:p text:style-name="P4">Type1</text:p>
               </table:table-cell>
            ...

            <table:table-row table:style-name="Table1.1">
               <table:table-cell table:style-name="Table1.A1" table:number-rows-spanned="4" office:value-type="string">
                  <text:p text:style-name="P7">Req</text:p>
               </table:table-cell>

So there is simply no table header in there.

About merged cells: that's unfortunately not supported by pandoc yet.

**Comment by mb21** [comment]
You could disable some extensions on the markdown write so that it emits another type of table, because [pipe tables](https://pandoc.org/MANUAL.html#extension-pipe_tables) require a header, that's why you get the empty line.

**Comment by rickywu** [comment]
@mb21 If disable pipe_tables, there is no result content for table 1

But merge cells in docx written by MS Word works well in pandoc

**Comment by mb21** [comment]
Well, you cannot disable _all_ table extensions... but the default works quite well:

```
~/Downloads pandoc libre.odt -t markdown
1.Convert to markdown, the table header position is incorrect

  ----------- ------------ ------------ ---------
  Type1       Type2        Req          Comment
  Req         Project      User story   
  Inv spec.                             
  Task        User story                
  Fun spec.                             
  T2                                    N/A
  ----------- ------------ ------------ ---------

2.Convert to markdown, table with multi line missed header row

+--------------+----------+-------------+
| Item         | Type     | Desc        |
+--------------+----------+-------------+
| Req\#        | auto     | A           |
+--------------+----------+-------------+
| Req template | dropdown | Some desc   |
|              |          |             |
|              |          | Other desc. |
+--------------+----------+-------------+
| Name         | Input    |             |
+--------------+----------+-------------+
```

> But merge cells in docx written by MS Word works well in pandoc

That must be a coincidence, see #1024

**Comment by rickywu** [comment]
@mb21 

I mean not work for gfm format not common markdown format:
pandoc libre.odt -f odt -t gfm

**Comment by mb21** [comment]
Yes, `gfm` only supports `pipe_tables`, which as I mentioned require a header, even if it's empty.

**Comment by rickywu** [comment]
@mb21 

Sorry, not understand that I added table heading sytle in first row and use this command:
pandoc libre.odt -f odt -t gfm+pipe_tables or pandoc libre.odt -f odt -t gfm

The table header still not right.

**Comment by rickywu** [comment]
This is caused by the table in docx not have a header row:
Must make sure the heading row checkbox is true in table design tab

**Comment by dogmatic69** [comment]
Stumbled across this issue with the latest version. I understand the needs for header style in the table, but the problem file is pandoc generated from markdown. 

markdown with table -> file.odt `-f markdown -t odt`
file.odt -> markdown `-f odt -t markdown`

results in something like this which does not render as a table 

```
--- -----------
x   foobar
y   fizz buzz
--- -----------
```

eg: 
--- -----------
x   foobar
y   fizz buzz
--- -----------

**Comment by jgm** [comment]
@dogmatic69 that does render as a table in pandoc's markdown.  Maybe you are using some other variant, in which case you should use `-t gfm` or whatever instead of `-t markdown`.
