### ISSUE TITLE
R Markdown error with Pandoc 2.7.1: --latex-engine has been removed.  Use --pdf-engine instead.

### ISSUE THREAD

**Issue by emcghee73** [jgm/pandoc#5428]
I installed the package rticles (https://cran.r-project.org/web/packages/rticles/index.html) to add more functionality to the preamble of my R Markdown document (I'm new to R Markdown and am trying to see what it can do).  It prompted me to update Pandoc, so I updated to 2.7.1 and now I can't run any of my .Rmd files.  I get this error:

--latex-engine has been removed.  Use --pdf-engine instead.

This occurs with the simplest of markdown documents.  For example:

---
output: pdf_document
---

The quick brown fox jumps over the lazy dog.

Updating R Markdown doesn't solve the problem.  Any help would be appreciated!

**Comment by jgm** [comment]
Your R Markdown is evidently calling pandoc with the wrong option. You need to talk to R Markdown people about this, we can't do anything about it.

**Comment by emcghee73** [comment]
OK, thanks
