### ISSUE TITLE
Windows Instruction for Convert Whole Directory of Files FAQ

### ISSUE THREAD

**Issue by kcyarn** [jgm/pandoc#5429]
Under "how can I convert a whole directory of files from Markdown to RTF" on the [FAQ](https://pandoc.org/faqs.html) page, 

For Windows Powershell

```
gci -r -i *.txt |foreach{$rtf=$_.directoryname+"\"+$_.basename+".rtf";pandoc -f markdown -s $_.name -o $rtf}
```

For example, my go-to docx conversion command is

```
gci -r -i *.md |foreach{$docx=$_.directoryname+"\"+$_.basename+".docx";pandoc -f markdown+smart -s $_.name -o $docx}
```

**Comment by jgm** [comment]
Thank you

**Comment by zk-zephyr** [comment]
I've been trying to run this, but get an error for any sub-folders:

`pandoc.exe: test.md: withBinaryFile: does not exist (No such file or directory)`

Everything in the top level folder converts fine, but all of the sub folders don't. My work around is to just navigate to the subfolders, but I'm curious about how to solve the issue.

**Comment by jgm** [comment]
I'll update it in the next release, thanks.
