### ISSUE TITLE
Feature Request: Embedding modules concept for pandoc portable

### ISSUE THREAD

**Issue by getkub** [jgm/pandoc#5432]
We are trying to incorporate _pandoc_ into our software as single point of document conversion magic. We are really looking forward for the portable versions of _pandoc_
But it seems like portable version of _pandoc_, still relies on full blown installations of other dependencies like MiKTeX etc. which defeats the whole purpose.

So suggestion/feature request is if it is possible for "_Pandoc portable_" to have a modular concept similar to the likes of notepad++ to have a plugins directory where you can add/load required plugins? That would make _pandoc_ awesome

**Comment by jgm** [comment]
Please ask questions like this on the pandoc-discuss mailing list instead of here.
You might be interested in recent work on a pandoc docker image; you'll get some feedback if you post on the list.
