### ISSUE TITLE
new undocumented vimwiki behavior breaks wikilinks in html output

### ISSUE THREAD

**Issue by slonik-az** [jgm/pandoc#5437]
pandoc-2.7.2 made a radical change to vimwiki format and does not add `.html` extension to wikilinks any longer even if html is the target. While this change solves some of the problems reported (#5414), it unfortunately breaks html generated from wikis that use default vimwiki syntax.  Release notes for pandoc-2.7.2 contain a solution in a form of a simple Lua filter and it works fine. But this info is only available in the release notes. I was unable to find it anywhere in the pandoc documentation.

 __Please, add this lua-filter based solution to the pandoc documentation.__

**Comment by jgm** [comment]
The original behavior was mistaken; it did not conform to the normal pandoc behavior for wiki formats.  So this is a fix, and bug fixes and behavior changes are documented in the changelog, not the user's guide.  (The changelog is 7 MB; trust me, you don't want all of this information in the manual.)

If the original behavior had been documented in the user's guide, of course we'd have to change that. But it was not.
