### ISSUE TITLE
Raw TeX: always include curly braces after a TeX command

### ISSUE THREAD

**Issue by rauschma** [jgm/pandoc#5439]
(Pandoc 2.7.2)

Currently, braces after a TeX command are sometimes included in the RawInline, sometimes not:

```
namespace\fshyp{}container
[Para [Str "namespace",RawInline (Format "tex") "\\fshyp",Str "{}container"]]

namespace\aaa{}container
[Para [Str "namespace",RawInline (Format "tex") "\\aaa{}",Str "container"]]
```

Downside: It becomes impossible to write a filter that does something different when targeting, e.g., HTML. Such a filter needs access to the complete raw TeX (e.g., `\fshyp{}` and not just `\fshyp`).

Suggestion: Always include trailing curly braces in a TeX RawInline.

**Comment by khalid-hussain** [comment]
I'm having somewhat of a similar issue.

```
pandoc.exe 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
```

Command (1)

```
echo "{\addfontfeatures{Style=Swash}{Fancy Title}}" | pandoc -t latex
```

Result (1)

```
\{\addfontfeatures{Style=Swash}{Fancy Title}\}
```

The outer braces are not included as part of the TeX command but rather as text.

Command (2)

```
echo "{\addfontfeatures{Style=Swash}{Fancy Title}}" | pandoc -t native
```

Result (2)

```
[Para [Str "{",RawInline (Format "tex") "\\addfontfeatures{Style=Swash}{Fancy Title}",Str "}"]]
```

Is there a workaround?

**Comment by agusmba** [comment]
Instead of having a TeX group with `{` and `}` you could try to use `\bgroup` and `\egroup` which should behave the same way:

    echo "\bgroup\addfontfeatures{Style=Swash}{Fancy Title}\egroup" | pandoc -t native

    [RawBlock (Format "tex") "\\bgroup\\addfontfeatures{Style=Swash}{Fancy Title}\\egroup"]

**Comment by jgm** [comment]
Another solution is to use the raw attribute:
```
`{\addfontfeatures{Style=Swash}{Fancy Title}}`{=latex}
```
