### ISSUE TITLE
org writer: indentation in code blocks

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5440]
````
% pandoc -t org
```
hi
```
^D
#+BEGIN_EXAMPLE
    hi
#+END_EXAMPLE
````
As far as I can see, the indentation here is completely unnecessary, and we could just emit
```
#+BEGIN_EXAMPLE
hi
#+END_EXAMPLE
```
@tarleb is that correct? Should this be changed?

**Comment by tarleb** [comment]
This is correct, the indentation is technically unnecessary. However, the standard way seems to be to indent with two spaces. That is also what emacs produces when editing a source block in a separate buffer, e.g. by pressing <kbd>C-c '</kbd> while on a block. So maybe we should keep the indentation, but reduce it to two spaces?

**Comment by jgm** [comment]
Albert Krewinkel <notifications@github.com> writes:

> This is correct, the indentation is technically unnecessary. However, the standard way seems to be to indent with two spaces. That is also what emacs produces when editing a source block in a separate buffer, e.g. by pressing <kbd>C-c '</kbd> while on a block. So maybe we should keep the indentation, but reduce it to two spaces?

That would be fine with me.  But I wonder why the two
spaces?  That makes copy-paste trickier.

**Comment by gregoryg** [comment]
@jgm It's common to execute an org-mode command that brings up the code block in its own buffer using the specified program language mode (C-c', or `org-edit-special` as mentioned by @tarleb ).  In that buffer, the lines are no longer indented.  Also, any org-mode command that exports will "do the right thing" for the export, which usually means losing the indentation.

**Comment by jgm** [comment]
OK, I'm fine with reducing indentation to 2 spaces, if that's the standard.

**Comment by tarleb** [comment]
> I wonder why the two spaces?

I don't know, really. Seems inconsistent, as, e.g., contents of `QUOTE` blocks is not indented when hitting tab. Whether a line in a SRC block is indented when hitting tab depends, among others, on whether `org-src-tab-acts-natively` is non-nil. I fail to recognize an underlying concept for these behaviors.

**Comment by alexalekseyenko** [comment]
Would it make sense to put this behind an option? In practice, this convention may [hopefully] be on its way out:
- https://github.com/jkitchin/scimax/blob/11894cec915a7801fc5d54ad4dfd223232fa508f/scimax-org.el#L192
- https://github.com/hlissner/doom-emacs/blob/9137cbaaa472025e119097d4cb35ef26034a587b/modules/lang/org/config.el#L190

**Comment by xeruf** [comment]
I agree, I never used these spaces. But there is another issue:

```sh
❯ printf '```sh\necho hi\n```' | pandoc -t org
#+begin_example
  echo hi
#+end_example
```

why is this an example block? I would expect (duh!) a source block:

```sh
#+begin_source sh
echo hi
#+end_source
```

**Comment by jgm** [comment]
I found this:
https://orgmode.org/manual/Languages.html

```
asymptote
lisp
awk
lua
C
matlab
C++
mscgen
clojure
ocaml
css
octave
D
org
ditaa
oz
calc
perl
emacs-lisp
plantuml
eshell
processing
fortran
python
gnuplot
R
screen
ruby
dot
sass
haskell
scheme
java
sed
js
sh
latex
sql
ledger
sqlite
lilypond
vala
```
I'll update.

**Comment by xeruf** [comment]
thx :)
