### ISSUE TITLE
Error with markdown to pdf conversion with DeclareMathOperator and xelatex

### ISSUE THREAD

**Issue by micahjsmith** [jgm/pandoc#5441]
When converting from markdown to pdf using XeLaTeX, the LateX DeclareMathOperator macro (#5149) is expanded to what appears to be incorrect LaTeX syntax, causing compilation errors.

MWE:
```
$ cat test.md
---
header-includes:
    - \usepackage{amsmath}
    - \DeclareMathOperator*{\argmin}{argmin}
---

This works

$$
a = \argmin_g 1
$$

This should work again, but actually fails with XeLaTeX

$$
a = \argmin_g 1
$$

$ pandoc -s test.md -o test.pdf --pdf-engine=xelatex
Error producing PDF.
! Missing { inserted.
<to be read again> 
                   \__um_group_begin: 
l.62 a = \mathop\mathrm
```

Note that the conversion works when pdf engine is not specified, maybe because pandoc does not convert internally to latex first? Not exactly sure.

The problem seems to be that pandoc generates not-quite-valid LaTeX when expanding the `\argmin` macro inline:

```
\[
a = \mathop\mathrm{argmin}_g 1
\]
```

The proper `\mathop` [syntax](https://texfaq.org/FAQ-newfunction) is to enclose the argument with braces, like so: `\mathop{\mathrm{argmin}}`. And it takes a while (in terms of lines in the document) for this to cause a failure as the first opening brace is searched for.

A workaround is to use `-f markdown-latex_macros` (See #4846).

**Comment by jgm** [comment]
Weird.  Here's the intermediate latex that works with pdflatex but not xelatex:
```latex
\begin{document}

This works

\[
a = \mathop\mathrm{argmin}_g 1
\]

This should work again, but actually fails with XeLaTeX

\[
a = \mathop\mathrm{argmin}_g 1
\]

\end{document}
```
I don't understand why this fails with xelatex.  That's very weird.

Note: manual does say

>  When `latex_macros` is disabled, the raw LaTeX and math will
not have macros applied. This is usually a better approach when
you are targeting LaTeX or PDF.

**Comment by micahjsmith** [comment]
Agreed that it is very weird!

Thanks for the pointer about `latex_macros` option, I missed that at first in the manual.

**Comment by micahjsmith** [comment]
Thank you for the quick response and fix :)
