### ISSUE TITLE
can pandoc support highlight lines in fenced code block

### ISSUE THREAD

**Issue by laoshaw** [jgm/pandoc#5442]
Based on this: https://zpao.com/posts/adding-line-highlights-to-markdown-code-fences/, this is a really useful feature request.
<pre>
```javascript{1,3,8-12}
</pre>
will highlight line 1,3 and 8-12

**Comment by mb21** [comment]
Probably this is out of scope. But you can use pandoc filters for things like that:

Have a look at [pandoc-emphasize-code](https://owickstrom.github.io/pandoc-emphasize-code/).
