### ISSUE TITLE
{\em my text} not converting as emphasis in RST

### ISSUE THREAD

**Issue by josephcslater** [jgm/pandoc#5446]
Version 2.3.2.2

`{\em  my text}` doesn't result in `*my text*` like `\emph{my text}` does. 

This is a problem when converting bibtex output- at least in the case of the format I'm using. 

The following has one that works and another that does (using `\emph` and `\em`)

```
pandoc -f latex  pubs.tex.txt -o pubs.rst
```
Github won't upload files with `.tex` extension, so I've added .txt. 
[pubs.tex.txt](https://github.com/jgm/pandoc/files/3078159/pubs.tex.txt)

**Comment by jgm** [comment]
```
% pandoc -f latex -t native
{\em ASME Turbo Expo 2018:  Turbomachinery Technical Conference and Exposition\/}
^D
[Para [Span ("",[],[]) [Emph [Str "ASME",Space,Str "Turbo",Space,Str "Expo",Space,Str "2018:",Space,Str "Turbomachinery",Space,Str "Technical",Space,Str "Conference",Space,Str "and",Space,Str "Exposition"]]]]
```
As you can see, pandoc *is* recognizing this as Emph(asized), but the Emph element is put inside a Span (because of the `{` `}` grouping).

You'll get emphasis in HTML:
```
<p><span><em>ASME Turbo Expo 2018: Turbomachinery Technical Conference and Exposition</em></span></p>
```
but the extra span is blocking emphasis in RST output.

**Comment by josephcslater** [comment]
Right- so can this be "corrected"? 

Note that this is the output of bibtex- I don't necessarily directly control it then. I have written a dirty work around to string replace `{\em` with `\emph{`, but I think that this should be done in general by pandoc.

**Comment by jgm** [comment]
Yes, I'll fix it.

**Comment by josephcslater** [comment]
Someday I might understand the code enough. Sorry. I actually tried, but coming from "zero" I couldn't make heads or tales of it.

btw- awesome code. Thanks!
