### ISSUE TITLE
Implement true conditional control sequences: if depending on values in templates

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#5447]
Please implement that we control the values in the `if` statements: something like
```
$if(lang)==(es)$
Hola
$else$
Hello
$endif$
```
With this we could control if statements. Now if we want to filter values, we have to go outsite and use an external template system (I use ERB but it's tedious, because I have two layers of control).  With this, we can control templates more easyly. A `case` statement could be worth, also.

Thanks in advance,

**Comment by jgm** [comment]
Dup of #3697

**Comment by somenxavier** [comment]
I could offer some bucks ($20) for implementing this via paypal or so. For me it is first-class feature.
