### ISSUE TITLE
ConTeXt Writer: startplacetable cross reference

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#5449]
**Replicate**
Consider the following Markdown document named `test.md`:

``` md
| Description | Scope? |
|-------------|-----------|
| Text   | N |

Table: Caption. {#tbl:scope}
```

Run `pandoc test.md -t context -o test.tex`.

**Expected**
Expected results:

``` tex
\startplacetable[title={Caption.}, reference=tbl:scope]
```

Or:

``` tex
\startplacetable[title={Caption.}, reference=scope]
```

**Actual Results**
``` tex
\startplacetable[title={Caption. \{\#tbl:scope\}}]
```

**Additional Details**
This prevents cross-referencing tables. The figure (`Image`) parsing portion of the ConTeXt writer is able to handle cross-references. See:

* https://github.com/jgm/pandoc/blob/be929bcc80466623462102a39dd98726bb6c7781/src/Text/Pandoc/Writers/ConTeXt.hs#L267
* https://github.com/jgm/pandoc/blob/be929bcc80466623462102a39dd98726bb6c7781/src/Text/Pandoc/Writers/ConTeXt.hs#L170

**Comment by jgm** [comment]
This has nothing to do with the context writer, nor is it a bug at all. Table captions cannot take attributes in pandoc's markdown.  So the `{#tbl:scope}` is being interpreted as plain text. You can verify this by doing `-t native` instead of `-t context`.

See #1024 for a request for attributes in tables.

**Comment by DaveJarvis** [comment]
> See #1024 for a request for attributes in tables.

That makes sense. I tried to override the behaviour using lua, but it looks like in order to revise the `\startplacetable` macro to account for the reference, the entire table code must be re-written. See attached a starting attempt to introduce the `reference` attribute of the `\startplacetable` macro.

[xref.lua.txt](https://github.com/jgm/pandoc/files/3085886/xref.lua.txt)

**Comment by jgm** [comment]
I'll close this since it isn't a bug.  I agree that it would be good to have a way to do this, but I think table attributes are what we need.
