### ISSUE TITLE
use a noslide heading class to designate material which should _not_ be output as a slide

### ISSUE THREAD

**Issue by agoldst** [jgm/pandoc#5453]
Prior to v2.7, content following a heading above the slide level was not output as a slide. This was handy for using the same markdown for both a beamer slide show and a PDF article version or lecture script. (Details below.) As @jgm suggested on [pandoc-discuss](https://groups.google.com/d/msg/pandoc-discuss/At9jiV0LQt4/z0H38yY_AwAJ), a replacement for this capability might be to introduce a special class for headings, say `noslide`; for beamer output, content under a `# {.noslide}` would be output as LaTeX without being enclosed in a `frame` environment. I suppose this should only apply to headers at or above the slide level.

Details: the idea is to write markdown like

    ## slide

    - slide stuff

    # script section {.noslide}

    Here is non-slide text for a presenter script.

    ## next slide

    - slide stuff

and, with appropriate templates, generate via `pandoc -t beamer` both a beamer slideshow (with class option `ignorenonframetext`) and article-formatted presentation script (sic; `pandoc -t beamer` but with a template with document class `article`, `\usepackage{beamerarticle}` in preamble). The slide show would omit the "Here is non-slide text..." This was possible before v2.7 with `pandoc -t beamer --slide-level 2`.. In pandoc v2.7, a new and undesired slide is unavaoidably created.

This would also make it possible to use beamer mode-switching with `\mode<...>` to make some material presentation-only or script-only, but this is no longer fully possible, since under 2.7 you can't output anything between one `\end{frame}` and the next `\begin{frame}`.

This is not the same as making presenter notes with `::: notes` or `\note{}`. These are  dropped by `beamerarticle` and do not allow the preparation of a discursive lecture script with many paragraphs of text for a given slide. (This really is something reasonable people do for lectures in some academic disciplines. The number of such people who use pandoc and beamer is perhaps somewhat smaller...)

I am not sure whether this would be of any use for HTML slideshow formats. Probably not, but who knows?

I think proposing new Pandoc code is beyond me, but I could supply a draft template using `beamerarticle` if this is of interest.

**Comment by jgm** [comment]
One question is whether
```
# script section {.noslide}

Here is non-slide text for a presenter script.
```
should create a "title slide" without the content under the slide (this was pandoc's old behavior), or simply nothing.

Another possible syntax idea would be to use specially marked divs
```
::: hide
This content won't be put on a slide.
:::
```
Indeed, this approach could already be implemented using a lua filter that simply strips out the Divs with class `hide`.

**Comment by agoldst** [comment]
Maybe the filtering strategy would be enough for all reasonable purposes. One could use ordinary latex output for the lecture script (instead of beamer output with a different template). That strategy doesn't allow you to generate LaTeX of the form

```latex
\begin{frame}
...
\end{frame}

Non-frame text or perhaps beamer commands like

\mode<presentation>

\begin{frame}
...
```

but since the only use I can now come up with for that is the beamer mode-switching commands, it seems pretty marginal. I will experiment with your proposed filtering solution to see if I miss anything else from my pre-2.7 workflow.

**Comment by cagix** [comment]
I've been using native Divs in combination with simple Lua filters to create 
slides (LaTeX Beamer or Reveal.JS) as well as lecture notes from a single
markdown document.

This way there is no need for any additional syntax and you can use nearly 
arbitrary markdown elements inside the notes. This works for Div and Span 
as well. 

Also there is no need for special templates :)

See https://github.com/cagix/pandoc-lecture for more examples ...^


Here is a simple example:

```markdown
# Overview slide (beamer) or vertical slide (reveal.js)

## Normal slide

This content will appear in slides and handout.

::: notes
This will only be visible in handout. You can use 

### Further section 

* bullet lists
* bullet lists 

```python
def foo():
    passs
```

...
:::

## Next slide

content to appear again on slides and handout

[this will only be visible on slides]{slides} 
```

To remove the notes-Div (e.g. for slides), you can use a filter like
```lua
-- remove block notes: `::: notes ... :::` ... (Div class)
function blockNotes(el)
    if el.classes[1] == "notes" then
        return {}
    end
end
```

To include the notes-Div, simply remove the Div an replace it by its content:
```lua
-- remove block notes div, return content: `::: notes ... :::` ... (Div class)
-- rationale: w/o this filter content would appear in generated html but not in toc
function blockNotes(el)
    if el.classes[1] == "notes" then
        return el.content
    end
end
```

**Comment by jkr** [comment]
If you use the `notes` div, you'll also get real speaker notes in supporting slide formats (reveal.js and PowerPoint). So this approach will allow for greater interoperability between different formats.

**Comment by agoldst** [comment]
Many thanks @cagix for your examples, which helped me in trying out this approach myself.

@jkr quite right about interoperability, but as I said in the initial post, speaker notes are not fit for my particular purpose. Thanks to Beamer's restrictions on how it handles `\note{}` (and in combination with Beamer's equally strict constraints on the paper size!) you really can't get paragraphs of non-slide text into a usable form with this command.

But a simple lua filter to remove native Divs with a specified class can do almost everything I was using the pre-2.7 behavior for. One has to do a little extra work in the filter to visually delimit the script text from the slide material, as I wanted to do, and the resulting markdown is a bit more verbose. About the only Beamer command that's ruled out is `\mode*`, which cannot appear within a frame environment.

But I think that trade-off is preferable to asking @jgm et al. to add any new syntax. I'll close this issue. (Here, for no one's benefit but my own, is what I have: [agoldst/elsmd](https://github.com/agoldst/elsmd).)
