### ISSUE TITLE
Feature Request: Add a "heading" class to <p> tags that result from demotions in --base-header-level=2-5

### ISSUE THREAD

**Issue by CxRes** [jgm/pandoc#5457]
Suppose I have `foo.md` with:
```
###### Hi
```

On running `pandoc --base-header-level=2 foo.md` the output is:
```
<p id="hi">Hi</p>
```

It would be nice if one could get an output like:
```
<p id="hi" class="heading-7">Hi</p>
```
or at least
```
<p id="hi" class="heading">Hi</p>
```

so that one could apply extra styling through css, if one so desires!

**Comment by jgm** [comment]
Sounds reasonable to me!
