### ISSUE TITLE
bibkey with '-' does not work

### ISSUE THREAD

**Issue by zwz** [jgm/pandoc#5458]
I have a reference with the bibkey as `2015.9a-.d`
pandoc will convert it into `\autocite[.d]{2015.9a}` instead of `\autocite{2015.9a-.d}`

As https://tex.stackexchange.com/questions/408530/what-characters-are-allowed-to-use-as-delimiters-for-bibtex-keys shows, '-' should be OK in bibkey.

And I also checked pandoc manual, there is no specifications on what can be used in a bibkey.

**Comment by jgm** [comment]
> And I also checked pandoc manual, there is no specifications on what can be used in a bibkey.

From the Citations section of the manual:

> Citations go inside square brackets and are separated
> by semicolons. Each citation must have a key, composed
> of ‘@’ + the citation identifier from the database,
> and may optionally have a prefix, a locator, and a
> suffix. The citation key must begin with a letter,
> digit, or _, and may contain alphanumerics, _, and
> internal punctuation characters (:.#$%&-+?<>~/).

**Comment by zwz** [comment]
Oops, can not believe I missed it.
So those `internal punctuation characters (:.#$%&-+?<>~/)` can not be used one next to another, 
just as my test bibkey `2015.9a-.d` shows (where `-.` is internal of the key)?

**Comment by jgm** [comment]
Yes, "internal" here means, essentially, between two alphanumerics.  It's a bit of a rough heuristic, but this is needed so that e.g. we don't absorb the period or hyphen in the following cases into the citation key:
```
See @jones2000.
See @jones2000---and also @smith2000.
```

**Comment by zwz** [comment]
Fair enough. :)

**Comment by wlupton** [comment]
Where does it say that the key can't contain multiple adjacent internal punctuation characters? I've read (and re-read) that section of the manual, and I don't see it.

**Comment by jgm** [comment]
"internal punctuation characters" is not really defined.  (What is internal and what is external?)  We use a heuristic for this which counts a single punctuation character between non-punctuation characters as "internal."  (Sample motivation:  we don't want to capture an em-dash in e.g. `@foo2000---among others`.)  The manual doesn't describe the heuristic in detail, but we could add something about this.

**Comment by wlupton** [comment]
Thanks. Yes I think that a mention that only _single_ internal punctuation characters are permitted would definitely be useful.
