### ISSUE TITLE
Cyrillic symbols when converting to pdf

### ISSUE THREAD

**Issue by sudoandros** [jgm/pandoc#5459]
**Pandoc version**: 1.19.2.1
Hello. I'm trying to get a pdf file from a markdown file. My text contains cyrillic symbols (it's in Russian language). When converting to pdf without any additional parameters
```
pandoc -f markdown -t beamer slides.md -o slides.pdf
```
I get the following
```
! Package inputenc Error: Unicode char З (U+417)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.68 \section{Заголовок}

Try running pandoc with --latex-engine=xelatex.
pandoc: Error producing PDF
```
So I've installed xelatex and tried again with
```
pandoc -f markdown -t beamer slides.md -o slides.pdf --latex-engine=xelatex
```
Now there are no errors but cyrillic symbols just don't show up in pdf. Blanks are in their place. Then I tried to do
```
pandoc -f markdown -t beamer slides.md -o slides.pdf --latex-engine=xelatex -V lang:russian
```
But it's still the same. How do I use pandoc for Russian text?

Here is the output I get:
[slides.pdf](https://github.com/jgm/pandoc/files/3100566/slides.pdf)

For the input:
```
# Заголовок

## Подзаголовок 1

It is English text. А это русский текст

## Subtitle 2

И снова русский текст. And English again.
```

**Comment by jgm** [comment]
You need to set `mainfont` to something that has cyrillic glyphs, probably.
You can do that by adding
```
-V mainfont='Name of Font'
```
where Name of Font is replaced with the name of a Cyrillic font on your system.

**Comment by wpnwbn** [comment]
`pandoc --pdf-engine=xelatex -V mainfont="*some Cyrillic font*" *something*.md -o *something*.pdf`

**Comment by dvoropaev** [comment]
I have a similar problem:
```
 $ cat ./markdown_example.md
#Заголовок
Списрок:
* Элемент 1
* Элемент 2
* Элемент 3
$ pandoc --latex-engine=xelatex -V mainfont="Liberation Serif" ./markdown_example.md -o markdown_example.pdf
pandoc: Error producing PDF from TeX source.
! Text line contains an invalid character.
l.48 \section{^^W
```

**Comment by tarleb** [comment]
@dvoropaev judging from the command, it appears that you are using a pandoc version that was released about 5 years ago. Please try with a recent version.
