### ISSUE TITLE
EPUB with multiple `--css` causes duplicate IDs in `content.opf`

### ISSUE THREAD

**Issue by nybblr** [jgm/pandoc#5463]
To reuse styling between my web and epub versions, I split up my styling into several files and add them with `--css`:

```bash
pandoc \
  -f json \
  --standalone \
  --css publish/fonts.css \
  --css publish/typography.css \
  --css publish/highlight.css \
  -o build/book.epub \
  ...
```

I'm using Pandoc 2.7.2. The resultant `content.opf` file has this:

```xml
    <item id="style" href="styles/stylesheet1.css" media-type="text/css" />
    <item id="style" href="styles/stylesheet2.css" media-type="text/css" />
    <item id="style" href="styles/stylesheet3.css" media-type="text/css" />
```

The ePub opens fine in Calibre/iBooks, but since each stylesheet gets the same ID of `style`, it ticks off validators and is causing conversion to MOBI to fail for Kindle readers.

Is `--css` meant to be used multiple times in this way? Would it be enough to generate unique `id`s, or do the stylesheets need to be concatenated?

I thought I'd be clever and use a named pipe to concatenate them first, but apparently it interferes with processing a JSON AST from stdin.

```bash
process-that-generates-json-ast | pandoc \
  -f json \
  --standalone \
  --css <(cat publish/{fonts,typography,highlight}.css) \
  -o build/book.epub \
  -
```

**Comment by jgm** [comment]
Yes, `--css` is meant to be usable in this way. The duplicate `style` is probably leftover from when we only allowed one CSS file.  I can fix.
