### ISSUE TITLE
Add working dir / source path as template variable

### ISSUE THREAD

**Issue by tstenner** [jgm/pandoc#5464]
I've got almost the same problem as in #3431: I want to include the source file in the output document.

For `context`, I have included the following snippet:

```
$if(includesource)$
$for(sourcefile)$
\attachment[file=$sourcefile$,method=hidden] 
$endfor$
$endif$
```

This will include the source file as PDF attachment, but only with an absolute input file name (`pandoc $PWD/test.md -t context -s -o test.pdf`) or with context running from the same directory (`pandoc test.md -t context -s -o test.tex; context test.tex`), otherwise `context` will look for the file in the temporary pdf folder.

This could be solved either with a variable with the full paths (`fullpathsourcefile`?) or a variable with pandoc's current working directory (usable as `\attachment[file=$pwd$/$sourcefile$,method=hidden]`).

**Comment by tarleb** [comment]
As a workaround, one can set the `pwd` metadata field in a Lua filter:

``` lua
function Meta (meta)
  -- set current working directory. Works on Mac and Linux; not sure about Windows.
  meta.pwd = os.getenv 'PWD'
  return meta
end
```

**Comment by agusmba** [comment]
If `'PWD'` doesn't work in windows (I haven't checked) you could use `'CD'`

**Comment by tstenner** [comment]
@tarleb  That's an option, another idea I had was `pandoc test.md -V pwd=$PWD -s -t context`.

For most of my documents I have rather basic needs so panzer et al are overkill. This addition would make another common usecase doable without any addons and it complements the `$sourcefile$` variable quite nicely. On the other hand, I can understand if it's found to be out of scope for plain pandoc.

**Comment by tarleb** [comment]
According to a StackOverflow answer, there is no easy, platform independent way to get the current working directory. I've started work on a [module](https://github.com/hslua/hslua-module-system) to expose the relevant Haskell functions to Lua. This should also help with other common filter operations.

**Comment by mb21** [comment]
> I've started work on a module to expose the relevant Haskell functions to Lua. 

for reference: I guess, that's https://github.com/jgm/pandoc/pull/5468
