### ISSUE TITLE
commitBuffer: invalid argument 

### ISSUE THREAD

**Issue by schell** [jgm/pandoc#5472]
I'm seeing this error when writing :
```
haskell-games: build/site/games/snake/index.html: commitBuffer: invalid argument (invalid character)
```
but I'm only seeing it on the gitlab runner during CICD. If the same program is run locally everything works as expected. Both machines are Ubuntu 18.04. Is there any obvious source of the error?

**Comment by jgm** [comment]
Does this have something to do with pandoc?  If so,
how are you running pandoc, what is the input, etc.?

**Comment by schell** [comment]
Ah, yes it does have something to do with Pandoc the library. At least I think it does - I had assumed that `commitBuffer` was an internal Pandoc function. It's hard for me to pinpoint which part of the program is calling `commitBuffer` but my intuition is it's some pure code within pandoc. I run pandoc a number of times here to render a `Pandoc` into variables to use in a template.

https://github.com/schell/milkshake/blob/master/src/Milkshake/Compile.hs#L152-L186

You can see the callsite and what happens with those vars (I'm calling `renderTemplate'` with them) here: 

https://github.com/schell/milkshake/blob/master/src/Milkshake/Compile.hs#L289-L300

I think the error happens somewhere in `renderTemplate'` but I'm not sure.

Actually now that I think of it maybe it's happening in `writeFile`. I'll do a test with my CICD server and get back to you.

Also - thanks for this wonderful library!

**Comment by jgm** [comment]
commitBuffer is not a pandoc function.

This very likely has something to do with encodings in
reading or writing files.
See e.g.
https://www.reddit.com/r/haskell/comments/43tmt8/commitbuffer_invalid_argument_invalid_character/
