### ISSUE TITLE
\mathit in tex markup doesn't work for html output

### ISSUE THREAD

**Issue by khatchad** [jgm/pandoc#5477]
## Summary
The \mathit macro in tex markup when using html output doesn't work correctly. Specifically, it is treating operators inside the macro argument, when rather it should be treating those as text.

## Input
README.md:
```tex
$\mathit{S-expression}$
```

## Command
```bash
pandoc --standalone README.md -o README.html
```
## Expected Output
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<title>README</title>
<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
</style>
</head>
<body>
<p><span class="math inline"><em>S-expression</em></span></p>
</body>
</html> 
```
S-expression

## Actual Output
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<title>README</title>
<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
</style>
</head>
<body>
<p><span class="math inline"><em>S</em> <em>−</em> <em>e</em><em>x</em><em>p</em><em>r</em><em>e</em><em>s</em><em>s</em><em>i</em><em>o</em><em>n</em></span></p>
 </body>
</html> 
```
S − expression

## Version
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.6
Default user data directory: /home/rk1424/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

**Comment by mb21** [comment]
You probably want to use `--mathjax`, see https://pandoc.org/MANUAL.html#math-rendering-in-html

What you're seeing here is just a plain-text fallback.

**Comment by khatchad** [comment]
Hm. I used the default and was expecting the URL to be that of Cloudflare as in the documentation but I got `<script src="/usr/share/javascript/mathjax/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>`, which doesn't exist on my machine.

**Comment by khatchad** [comment]
I think it should be: `<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>` as described in https://www.mathjax.org/#gettingstarted.

**Comment by khatchad** [comment]
Even with mathjax, I'm seeing the same behavior (minus sign instead of a hyphen).

**Comment by mb21** [comment]
Try with the newest pandoc version:

    echo '$\mathit{S-expression}$' | pandoc --mathjax -s | grep MathJax

    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

**Comment by khatchad** [comment]
What is the output of that command without the grep? Does it produce the correct HTML as described above? I entered this URL manually yesterday and I still saw the same problem.

**Comment by agusmba** [comment]
easy enough to test (pandoc 2.7.2):

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Untitled</title>
  <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<p><span class="math inline">\(\mathit{S-expression}\)</span></p>
</body>
</html>
```

**Comment by khatchad** [comment]
Interesting. I see the same problem with this version. Should this bug be on mathjax then?

**Comment by agusmba** [comment]
I think if you want to have italics text you should use `$\textit{S-expression}$` instead of `mathit`.

> generally `\mathit` is better for math and `\textit` is better for text. – [David Carlisle](https://tex.stackexchange.com/questions/405552/mathit-vs-textit-for-multi-letter-identifiers#comment1010943_405554)

**Comment by jgm** [comment]
> I used the default and was expecting the URL to be that of Cloudflare as in the documentation but I got <script src="/usr/share/javascript/mathjax/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>, which doesn't exist on my machine.

Are you on debian?  Debian modifies the default pandoc template to use a locally installed mathjax, if I recall.

**Comment by jgm** [comment]
> I think if you want to have italics text you should use $\textit{S-expression}$ instead of mathit.

Exactly right.  If you render your input with latex, you'll see it behaves exactly as pandoc does.
Use `\textit`.

**Comment by khatchad** [comment]
> > I used the default and was expecting the URL to be that of Cloudflare as in the documentation but I got <script src="/usr/share/javascript/mathjax/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>, which doesn't exist on my machine.
> 
> Are you on debian? Debian modifies the default pandoc template to use a locally installed mathjax, if I recall.

I'm on Ubuntu.

**Comment by khatchad** [comment]
Ah, I didn't think to try that. Thanks.
