### ISSUE TITLE
Org reader: specification of latex compiler does not work

### ISSUE THREAD

**Issue by atbest** [jgm/pandoc#5480]
In the [LaTeX specific export settings](https://orgmode.org/manual/LaTeX-specific-export-settings.html), there is an option ( `LATEX_COMPILER`) to specify the latex compiler, `pdflatex`, `xelatex` or `lualatex`. However, this option is ignored and Pandoc always uses `pdflatex` as default engine. This is annoying if non-ASCII characters or special characters exist in the org files. For example, `\Delta` is parsed to `Δ` symbol and the document has to be converted to pdf using `xelatex` because `pdflatex` cannot process non-ASCII characters directly. It will be great if Pandoc can recognize `LATEX_COMPILER` or provide a mechanism to set `xelatex` as default `pdf-engine` for Windows users.

**Comment by jgm** [comment]
Use `--pdf-engine=xelatex` (or whatever).

This setting is controlled by writer options, not by document metadata.  So there's no way for the org reader to affect it, currently.

**Comment by jgm** [comment]
If #4627 were implemented, then we could do this.

**Comment by atbest** [comment]
I am curious why you choose pdflatex as the default engine. It does not support unicode charecters and produces larger files compared to xelatex.
The only reason I can imagine is backward compatibility. However, this option has been changed from latex-engine to pdf-engine. Thus backward compatibility is not sufficient to explain the decision.

**Comment by jgm** [comment]
@atbest Remember that pandoc is a 13 year old project.  When we started, it wasn't a given that people would have xelatex installed, and xelatex didn't work as well as it did now.  The decision could be rethought.

I think there are two issues to consider:

1.  Are there going to be people who only have pdflatex and not xelatex?  (I imagine this is now rare.)
2.  pdflatex is still significantly faster in my experience.

Another sensible option would be to default to xelatex if the latex intermediary contains non-ascii characters.

**Comment by jgm** [comment]
However, I think it would be better to raise this issue on the pandoc-discuss mailing list. This is not the best place to discuss it.

**Comment by atbest** [comment]
> This setting is controlled by writer options, not by document metadata. So there's no way for the org reader to affect it, currently.

OK, even if this option does not affect the writer settings, it should be omitted in the pdf file in consistence with Emacs. However, Pandoc converts `#+OPTIONS: pdf-engine:xelatex` to `pdf-engine:xelatex` directly.

**Comment by atbest** [comment]
I guess it's better to print unrecognoized options to `stderr` instead of retaining them in the final output.

**Comment by jgm** [comment]
@tarleb do you agree that the unrecognized options should be omitted, perhaps along with a warning?

**Comment by tarleb** [comment]
Wholeheartedly agree, the current behavior is not good. I'll look into it.

**Comment by jgm** [comment]
I'll re-open this issue then to keep track.

**Comment by tarleb** [comment]
Unknown options are now ignored with a warning (00ef03827e4ab77a1213b2adf261c818ddae076d)
