### ISSUE TITLE
Whitespace between columns in EPUB output.

### ISSUE THREAD

**Issue by Wandmalfarbe** [jgm/pandoc#5482]
Commit https://github.com/jgm/pandoc/commit/6d00e6e8c3d483cc36afe2c065cdfdd4ef811f85 removed whitespace between column divs in the HTML writer so columns are actually next to each other instead of falling on the next line. 

When generating an EPUB, the whitespace between columns is still added resulting in broken columns:

```
## Columns auto width

:::::::::::::: {.columns}
::: {.column}
left column content
:::
::: {.column}
right column content
:::
::::::::::::::
```

```
<section id="columns-auto-width" class="level2">
<h2>Columns auto width</h2>
<div class="columns">
<div class="column">
<p>left column content</p>
</div>
<div class="column">
<p>right column content</p>
</div>
</div>
</section>
```

Result: <https://codepen.io/anon/pen/bybmLP>

**Comment by jgm** [comment]
Are you sure you're using up-to-date pandoc in generating the epub?
I get this inside the epub:
```html
<section id="columns-auto-width" class="level2">
  <h2>Columns auto width</h2>
  <div class="columns">
  <div class="column">
  <p>left column content</p>
  </div><div class="column">
  <p>right column content</p>
  </div>
  </div>
  </section>
```
As you can see, no space.
Slides and epub follow the same code path here.

**Comment by Wandmalfarbe** [comment]
It seems to be an issue with the editing app [Sigil](https://github.com/Sigil-Ebook/Sigil) that I use to look inside the epub. When extracting the ZIP file manually, the correct text is present in the HTML. I should have checked it in another app.
