### ISSUE TITLE
Org reader emphasizes special symbols unexpectedly

### ISSUE THREAD

**Issue by atbest** [jgm/pandoc#5483]
Let me use `\alpha, \beta, \gamma` as an example. When exported to Html, Pandoc converts it to `<p><em>α</em>, <em>β</em>, <em>γ</em></p>`, while Emacs converts it to
```
<p>
&alpha;, &beta;, &gamma;
</p>
```
 You can see that Pandoc wraps the Greek letters with unexpected `em` tags. In fact, this also happens for other formats, like markdown (`*α*, *β*, *γ*`) and latex (`\emph{α}, \emph{β}, \emph{γ}`). So the bug should be produced in the Org reader.

**Comment by tarleb** [comment]
Just a note: the original behavior was intentional, as that's how org-mode behaves when exporting to LaTeX/PDF. However, we default to HTML-exporting behavior in general, so this seems like a good change.

**Comment by jgm** [comment]
I suspect what happens with org -> LaTeX is that math mode is used, e.g. `\alpha` becomes `$\alpha$`.  This would normally be rendered in italic font.

We could alternatively handle it this way, parsing `\alpha` as `Math InlineMath "\alpha"`, and  then it would render as math in formats that support this.
