### ISSUE TITLE
LaTeX Error: Environment columns undefined.

### ISSUE THREAD

**Issue by annProg** [jgm/pandoc#5485]
pandoc version: 2.7.1

```
:::: {.columns}
::: {.column width="50%"}
- item1
- item2
:::
::: {.column width="50%"}
- item3
- item4
:::
::::
```

use `pandoc -t latex` will produce

```tex
\begin{columns}[T]
\begin{column}{0.5\textwidth}
\begin{itemize}
\tightlist
\item
  item1
\item
  item2
\end{itemize}
\end{column}

\begin{column}{0.5\textwidth}
\begin{itemize}
\tightlist
\item
  item3
\item
  item4
\end{itemize}
\end{column}
\end{columns}
```

when compile the tex file, will report error:

```
Error producing PDF.
! LaTeX Error: Environment columns undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.99 \begin{columns}
```

**Comment by jgm** [comment]
This environment `columns` is for beamer only.  I'll modify the LaTeX writer so it isn't produced in this case.

**Comment by annProg** [comment]
Please do not remove this from LaTeX writer.  I am working on define the `columns` and `column` environment in `header-includes`:

```tex
\usepackage{keyval}
\newlength\Colsep
\setlength\Colsep{10pt}

\makeatletter
\define@key{columns@col}{T}[true]{\vspace{.5cm}}
\makeatother

\newenvironment{columns}[1][]
        {\setkeys{columns@col}{#1}
         \noindent\begin{minipage}{\textwidth}}
        {\end{minipage}\vspace{.5cm}}

\newenvironment{column}[1]
        {\begin{minipage}[t]{#1}}
        {\end{minipage}}
```

when use in very simple sample, it will work, but with default latex template it was not expected.

I'm not familiar with LaTeX,  please help me. Thanks

**Comment by annProg** [comment]
I found the `blank line` between columns will produce wrong result
![image](https://user-images.githubusercontent.com/4145852/57197085-90b37100-6f95-11e9-8629-af61b6808938.png)

```tex
\begin{columns}[T]
\begin{column}{0.5\textwidth}
\begin{itemize}
\tightlist
\item
  item1
\item
  item2
\end{itemize}
\end{column}  % Blank line between two column environment will cause unexpected result

\begin{column}{0.5\textwidth}
\begin{itemize}
\tightlist
\item
  item3
\item
  item4
\end{itemize}
\end{column}
\end{columns}
```

after delete this line, will get correct result

![image](https://user-images.githubusercontent.com/4145852/57197075-7e393780-6f95-11e9-9c61-a99484b33b13.png)

**Comment by jgm** [comment]
> Please do not remove this from LaTeX writer.  I am working on define the `columns` and `column` environment in `header-includes`:

I don't want to produce latex that won't work with the
default template, and I don't want to introduce ad hoc
environment definitions in the default template.

If you really want the columns environment to
be produced, you can use a lua filter to add the
environment commands around the Divs with class
'column' and 'columns'.

**Comment by annProg** [comment]
> Please do not remove this from LaTeX writer. I am working on define the `columns` and `column` environment in `header-includes`:
> I don't want to produce latex that won't work with the default template, and I don't want to introduce ad hoc environment definitions in the default template. If you really want the columns environment to be produced, you can use a lua filter to add the environment commands around the Divs with class 'column' and 'columns'.

Thanks. I will try lua-filter

**Comment by annProg** [comment]
@jgm Hi，I wrote lua filter

```lua
function divColumns(el)
	local column = {}
	for k,v in pairs(el) do
		if v.t == "Div" and v.attr.classes[1] == "column" then
			local width = v.attr.attributes.width
			if type(width) == string and string.find(width, "%d+%%$") then
				width = string.gsub(width, "%", "")
				width = width/100
			else
				width = "0.5"
			end
			table.insert(column, pandoc.RawBlock("latex", "\\begin{column}{" .. width .. "\\textwidth}"))
			for c,content in pairs(v.content) do
				table.insert(column, content)
			end
			table.insert(column, pandoc.RawBlock("latex", "\\end{column}"))
		else
			table.insert(column, v)
		end
	end
	
	return column
end

function Pandoc(doc)
	local nblocks = {}
	for i,el in pairs(doc.blocks) do
		if el.t == "Div" and el.attr.classes[1] == "columns" then
			table.insert(nblocks, pandoc.RawBlock("latex", "\\begin{columns}"))
			for k,v in pairs(divColumns(el.content)) do
				table.insert(nblocks, v)
			end
			table.insert(nblocks, pandoc.RawBlock("latex", "\\end{columns}"))
		else
			table.insert(nblocks, el)
		end
	end
	return pandoc.Doc(nblocks, doc.meta)
end
```

but it also will produce new line between column. Any way to resolve it ?

```
\begin{columns}

\begin{column}{0.5\textwidth}

\begin{itemize}
\tightlist
\item
  item1
\item
  item2
\end{itemize}

\end{column}  % new line after column won't get correct result

\begin{column}{0.5\textwidth}

\begin{itemize}
\tightlist
\item
  item3
\item
  item4
\end{itemize}

\end{column}

\end{columns}
```

**Comment by annProg** [comment]
I had fix the `new line` issue above.

before produce `RawBlock`, check if previous or next block is a `column Div`，if next block is `column`， insert `\end{column}\n\begin{column}` 

```lua
if k > 1 and el[k-1].t == "Div" and el[k-1].attr.classes[1] == "column" then
	-- do nothing
else
	table.insert(column, pandoc.RawBlock("latex", "\\begin{column}{" .. getWidth(v.attr.attributes.width) .. "\\textwidth}"))
end
for c,content in pairs(v.content) do
	table.insert(column, content)
end

if k+1 <= #el and el[k+1].t == "Div" and el[k+1].attr.classes[1] == "column" then
	table.insert(column, pandoc.RawBlock("latex", "\\end{column}\n\\begin{column}{" .. getWidth(el[k+1].attr.attributes.width) .. "\\textwidth}"))
else
	table.insert(column, pandoc.RawBlock("latex", "\\end{column}"))
end
```
