### ISSUE TITLE
Markdown -> HTML -> PDF creates broken footnote links

### ISSUE THREAD

**Issue by lyneca** [jgm/pandoc#5490]
Pandoc version: `pandoc 2.7.2`

Command run:
```
$ pandoc -t html -o test.pdf test.md
```

Input:
```
# Title

## Subtitle

There is a footnote on this[^1] here

[^1]: Footnote explained here, go to section [Subtitle]
```

Output:
![image](https://user-images.githubusercontent.com/7028282/57284830-4ba65080-70f5-11e9-82af-02428a333e9e.png)

Clicking on the footnote link attempts to open the URL `file:///home/user/html2pdf24786-0.html#fn1`, instead of navigating the PDF to the correct part of the document.

**Comment by mb21** [comment]
If you're using `-t html` for PDF generation, it will use wkhtmltopdf. So this will depend on your installed wkhtmltopdf version. It worked for me on `wkhtmltopdf 0.12.5 64bit` on macOS.

**Comment by lyneca** [comment]
Interesting, using the same version on Arch Linux...

**Comment by mb21** [comment]
Sounds like a known problem on some platforms: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2153

Might also depend on whether you're running headless or not. Unfortunately, we cannot fix this in pandoc, thus closing.

**Comment by lyneca** [comment]
Yup, thanks - I'll head over there.
