### ISSUE TITLE
Orgmode parser: incorrect timestamp location for h3

### ISSUE THREAD

**Issue by atbest** [jgm/pandoc#5494]
When timestamp information is set to be shown, it should located right after the headlines. This works for `h1` and `h2` but not `h3` in Pandoc generated files. For example, the following file was converted to pdf file with Pandoc and Emacs.

```
#+OPTIONS: toc:nil
#+OPTIONS: todo:nil
#+OPTIONS: num:nil
#+OPTIONS: timestamp:nil
#+OPTIONS: p:t

* DONE This is head 1
CLOSED: [2019-05-10 Fri 13:42]

Text 1

** DONE This is head 2
CLOSED: [2019-05-10 Fri 13:42]

Text 2

*** DONE This is head 3
CLOSED: [2019-05-10 Fri 13:42]

Text 3

```

![pandoc](https://user-images.githubusercontent.com/8389395/57512721-756c9c80-72da-11e9-9440-5f91b345b133.png)

As you can see from the figure, the timestamp info of `h3` is located below `Text 3` in Pandoc generated file. 

When the file is converted to html by Pandoc, the contents are shown below:

```html
<h1 id="this-is-head-1">This is head 1</h1>
<strong>CLOSED:</strong> <em>[2019-05-10 Fri 13:42]</em>
<p>Text 1</p>
<h2 id="this-is-head-2">This is head 2</h2>
<strong>CLOSED:</strong> <em>[2019-05-10 Fri 13:42]</em>
<p>Text 2</p>
<h3 id="this-is-head-3">This is head 3</h3>
<p>Text 3</p>
<strong>CLOSED:</strong> <em>[2019-05-10 Fri 13:42]</em>
```
Again, the timestamp info is behind of Text 3. So the bug should exist in the orgmode reader.

**Comment by tarleb** [comment]
Thanks for the report!
