### ISSUE TITLE
s5, revealjs, etc files not found 

### ISSUE THREAD

**Issue by pprw** [jgm/pandoc#5502]
On my debian sid system:

```
$ pandoc -t s5 -s --self-contained slides.md -o slides.html
File s5/default/slides.css not found in resource path
```
pandoc and s5 are installed from official packages in debian repositories.

s5 files seems to be in /usr/share/javascript/s5:

```
$ pwd
/usr/share/javascript/s5
$ ls -lR
.:
total 8
drwxr-xr-x 3 root root 4096 déc.   4 11:47 default
drwxr-xr-x 3 root root 4096 janv. 18 09:49 s5-blank

./default:
total 4
drwxr-xr-x 3 root root 4096 déc.   4 11:47 ui

./default/ui:
total 4
drwxr-xr-x 2 root root 4096 janv. 18 09:49 default

./default/ui/default:
total 64
-rw-r--r-- 1 root root    49 juin  27  2003 blank.gif
-rw-r--r-- 1 root root 10119 oct.   3  2004 bodybg.gif
-rw-r--r-- 1 root root   950 janv. 16 11:57 framing.css
-rw-r--r-- 1 root root  3136 janv. 16 11:57 iepngfix.htc
-rw-r--r-- 1 root root   207 janv. 16 11:57 opera.css
-rw-r--r-- 1 root root   696 janv. 16 11:57 outline.css
-rw-r--r-- 1 root root  3569 janv. 16 11:57 pretty.css
-rw-r--r-- 1 root root   952 janv. 16 11:57 print.css
-rw-r--r-- 1 root root   394 janv. 16 11:57 s5-core.css
-rw-r--r-- 1 root root   238 janv. 16 11:57 slides.css
-rw-r--r-- 1 root root 15706 janv. 16 11:57 slides.js

./s5-blank:
total 8
-rw-r--r-- 1 root root 1808 janv. 16 11:57 s5-blank.html
drwxr-xr-x 3 root root 4096 déc.   4 11:47 ui

./s5-blank/ui:
total 4
drwxr-xr-x 2 root root 4096 janv. 18 09:49 default

./s5-blank/ui/default:
total 64
-rw-r--r-- 1 root root    49 juin  27  2003 blank.gif
-rw-r--r-- 1 root root 10119 oct.   3  2004 bodybg.gif
-rw-r--r-- 1 root root   950 janv. 16 11:57 framing.css
-rw-r--r-- 1 root root  3136 janv. 16 11:57 iepngfix.htc
-rw-r--r-- 1 root root   207 janv. 16 11:57 opera.css
-rw-r--r-- 1 root root   696 janv. 16 11:57 outline.css
-rw-r--r-- 1 root root  3569 janv. 16 11:57 pretty.css
-rw-r--r-- 1 root root   952 janv. 16 11:57 print.css
-rw-r--r-- 1 root root   394 janv. 16 11:57 s5-core.css
-rw-r--r-- 1 root root   238 janv. 16 11:57 slides.css
-rw-r--r-- 1 root root 15753 janv. 16 11:57 slides.js
```
Using the "--data-dir" does work.

```
$ pandoc -t s5 -s --self-contained slides.md -o slides.html --data-dir=/usr/share/javascript/
```
P-S : the same for revealjs and maybe some other.

**Comment by mb21** [comment]
the debian versions are usually out of date. please try the newest version.. see https://pandoc.org/installing.html

**Comment by pprw** [comment]
I was using pandoc 2.2.1. I just installed 2.7.2 but the problem persists.

PS: Do I have to download the .deb time to time to keep pandoc updated ? Is there a way to have automatic upgrades ?

**Comment by mb21** [comment]
You're supposed to create a folder `s5` in the current working dir and put a file in `s5/default/slides.js`. See https://pandoc.org/MANUAL.html#producing-slide-shows-with-pandoc

**Comment by jgm** [comment]
I believe the official repositories are way behind 2.7.2, so I'm guessing you may have installed one version of pandoc from debian's repository and one from the deb we provide?
If so, are you sure you're running the one from our deb?

Debian's own packages modify the templates to look for the s5, revealjs etc. files in the `/usr/share` tree, where they should be installed by s5, revealjs, etc. packages.  Our own deb doesn't do this; it just keeps the default templates, and in the case of revealjs you need to install it yourself.  But it looks like you're running the official debian pandoc, not ours...

> PS: Do I have to download the .deb time to time to keep pandoc updated ? Is there a way to have automatic upgrades ?

I suppose we could look into providing an alternative repository -- that's not something I've thought of, and I don't know how to do it, but it might be worth bringing up either on pandoc-discuss or in a separate issue.

**Comment by jgm** [comment]
See @mb21's comment above.
Note that you can also supply a URL or path yourself, if you want to use the ones in `/usr/share`.
Set the variable `revealjs-url` or `s5-url`.
```
-V s5-url=/usr/share/javascript/s5
```
