### ISSUE TITLE
"Download the latest installer" link should be replaced with "Assets" dropdown

### ISSUE THREAD

**Issue by kenthe3rd** [jgm/pandoc#5503]
Version reported on : 2.7.2

the exact command line used : not applicable
the exact input used : not applicable
the output received : not applicable
the output you expected instead : not applicable

I propose replacing the "Download the latest installer" link found in INSTALL.md with the collapsable Assets box as seen in https://github.com/jgm/pandoc/releases/tag/2.7.2.  Doing so would allow the user to see the install instructions while browsing the available installer resources.

**Comment by mb21** [comment]
> Doing so would allow the user to see the install instructions while browsing the available installer resources.

I don't quite understand what you mean with that.

The "Download the latest installer" link was constructed to make it very easy to get the installer you probably need. If you don't like the default, just scroll down...

**Comment by jgm** [comment]
Agreed.
