### ISSUE TITLE
MediaWiki reader parsing table row with multiple attributes

### ISSUE THREAD

**Issue by sleepinggenius2** [jgm/pandoc#5508]
Pandoc version 2.7.2

The MediaWiki reader errors when it encounters a table that has a row with multiple attributes.  Looking at the code, it is using parseAttr for rows, but parseAttrs for cells.

```
$ cat | pandoc --from=mediawiki --to=gfm
{|
|- valign="top" style="background: silver"
! Column 1 || Column 2
|- valign="top"
| Value 1 || Value 2
|}

Error at "source" (line 2, column 17):
unexpected "s"
expecting lf new-line
|- valign="top" style="background: silver"
```

**Comment by jgm** [comment]
Dup of #5471 (fixed in master)?

**Comment by mb21** [comment]
Jep, I can confirm this is fixed on current master.
