### ISSUE TITLE
Pandoc throwing InvalidURL exception while accessing default Slidy URL

### ISSUE THREAD

**Issue by vojtapolasek** [jgm/pandoc#5509]
Pandoc 2.7.2
running
pandoc -s --self-contained -t slidy -o pandoc.html pandoc.md
on the attached file shows
Could not fetch https://www.w3.org/Talks/Tools/Slidy2/styles/slidy.css
InvalidUrlException "" "Invalid URL"

But the URL is correct. When I specify the local Slidy folder with -Vslidy-url it works.

Running Arch Linux.
[pandoc.zip](https://github.com/jgm/pandoc/files/3184602/pandoc.zip)

**Comment by jgm** [comment]
I can't reproduce this.  It works fine for me.
Do you perhaps have a custom slidy template in your user data directory?

**Comment by ajeep8** [comment]
The latest version 3.1.8 pandoc has same problem, it's because of proxy, when I unset https_proxy http_proxy env var, the (InvalidUrlException "" "Invalid URL") warning disappear.
