### ISSUE TITLE
multimarkdown sub and superscript are not correctly converted

### ISSUE THREAD

**Issue by sDC2** [jgm/pandoc#5512]
on the pandoc "try" site, multimarkdown\~subscript is not correctly converted. Instead the pandoc\~subscript\~ needs to be used.  The same mistake is noted for^superscript.

**Comment by jgm** [comment]
Can you link to the syntax specification for this?

**Comment by sDC2** [comment]
Please see (https://rawgit.com/fletcher/MultiMarkdown-6-Syntax-Guide/master/index.html) for an example. I found this inconsistency when I tried to convert my IA Writer files to pdf using pandoc.

It turns out that math is also not converted when using the markdown_mmd filter

**Comment by jgm** [comment]
Looks like the super/subscript syntax is like pandoc's except that a space implicitly closes them, without the need for a closing `^` or `~`.

As for math, it used to be that mmd only supported  the `\\(..\\)` and `\\[..\\]` forms.
Look like they now support the `$..$` and `$$..$$` forms as well. So this can be fixed simply by adding `tex_math_dollars` to the list of extensions included for `markdown_mmd`.
(And as a workaround you can simply use `-f markdown_mmd+tex_math_dollars`.)

**Comment by sDC2** [comment]
Thanks for the tip about the math! I'm really impressed with this tool and not at all that fluent in all possibilities. Thanks for the quick response. It is clear that pandoc is very much supported with a lot of passion!

On 18 May 2019, at 19:56, John MacFarlane <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like the super/subscript syntax is like pandoc's except that a space implicitly closes them, without the need for a closing ^ or ~.

As for math, it used to be that mmd only supported the \\(..\\) and \\[..\\] forms.
Look like they now support the $..$ and $$..$$ forms as well. So this can be fixed simply by adding tex_math_dollars to the list of extensions included for markdown_mmd.
(And as a workaround you can simply use -f markdown_mmd+tex_math_dollars.)

**Comment by OCzarnecki** [comment]
Just trying to get my bearings around the code for the potential GSoC project. Would this be a good issue to start with?

@tarleb @apreshill @cderv
(Also I'm not sure if tagging all of you is the way to go, please correct me if it's not!)

**Comment by tarleb** [comment]
This seems like a good choice to get started. 👍

It's probably enough if you ping just me for now.
