### ISSUE TITLE
headers and footers in the template for odt output

### ISSUE THREAD

**Issue by omichaelo** [jgm/pandoc#5515]
I have been trying to make an ODT template that includes a header. Referring to the [Open Documentation Specification](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1416290_253892949), it should look something like this in the template.

```
<office:master-styles>
  <style:master-page>
   <style:header>
    <text:p>My Header</text:p>
   </style:header>
  </style:master-page>
 </office:master-styles>
```

The specification also noted that the `<office:master-styles>` element should be a child of the root element `<office:document>` or `<office:document-styles>`. However, the default.opendocument template from [pandoc-templates](https://github.com/jgm/pandoc-templates) only contains the root element `<office:document-content>`.

So, when I tried to add the header, either by inserting it under `<office:document-content>`, inserting it under an additional `<office:document-styles>`, or changing `<office:document-content>` to `<office:document>` and inserting it under that, the output cannot be opened. Libreoffice shows an read error format error. 

I aren't really a programmer. But I suspect the reason is because pandoc only takes the `<office:document-content>` element to create ODT output. If this is the case, isn't impossible to make headers and footers in ODT templates?

**Comment by jgm** [comment]
You'll find a `<office:document-styles>` element in the `styles.xml` inside the ODT container. That's where you can add this in your reference odt.

**Comment by jgm** [comment]
PS. Questions like this should go to the pandoc-discuss mailing list. This tracker is for bug reports.
