### ISSUE TITLE
pypandoc does not work correctly for wkhtmltopdf

### ISSUE THREAD

**Issue by F35X70** [jgm/pandoc#5516]
pandoc version:
  pandoc 2.7.2
  Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
pypandoc version:
  pypandoc              1.4

pandoc command running successfully 

$ pandoc --from=mediawiki IT.mwwiki.txt --pdf-engine=wkhtmltopdf --metadata pagetitle="XXX" -o xx.pdf
Loading page (1/2)
Printing pages (2/2)                                               
Done 
python code
pdoc_args = ['--variable','mainfont=Microsoft YaHei','--pdf-engine=wkhtmltopdf']
pypandoc.convert_text(wiki_text,'pdf','mediawiki',outputfile=target_file,extra_args=pdoc_args) 

debug output:
to: pdf
format: mediawiki
args: ['/usr/bin/pandoc', '--from=mediawiki', '--to=latex', u'--output=IT.pdf', '--variable', 'mainfont=Microsoft YaHei', '--pdf-engine=wkhtmltopdf']
    pypandoc.convert_text(wiki_text,'pdf','mediawiki',outputfile=target_file,extra_args=pdoc_args)
  File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 103, in convert_text
    outputfile=outputfile, filters=filters)
  File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 331, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "1" during conversion: pdf-engine wkhtmltopdf is not compatible with output format latex   

if I remove this line 
/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py
#args.append('--to=' + to) 

pypandoc generate the corrent pdf

**Comment by jgm** [comment]
You should submit this as a bug report to pypandoc.  This repo is for pandoc itself.
However, it's obvious what the problem is from the error message:
pdf-engine wkhtmltopdf is not compatible with output format latex

If you use `--pdf-engine=wkhtmltopdf`, then you can't use `--to=latex`; use `--to=html5` or just leave it out.
