### ISSUE TITLE
[mac] org to pdf image absolute path not work

### ISSUE THREAD

**Issue by peng051410** [jgm/pandoc#5517]
- pandoc veriosn: pandoc 2.7.2
- os: mac 10.14.3 (18D109)
- org version: 9.1.9

when i run command
`pandoc --self-contained --pdf-engine=xelatex --template=/Users/username/soft/plugin/latex/pm-template.latex -f org -t latex apollo-config-swim.org -o test.pdf`

I got warn info:
`[WARNING] Could not fetch resource 'file:///Users/username/github/blog/images/apollo-home-screenshot.png': PandocHttpError "file:///Users/username/github/blog/images/apollo-home-screenshot.png" (InvalidUrlException "file:///Users/username/github/blog/images/apollo-home-screenshot.png" "Invalid scheme")`

org file image content:
[[file:/Users/username/github/blog/images/apollo-home-screenshot.png]]
[[/Users/username/github/blog/images/apollo-home-screenshot.png]]

these all not work!

What should i do ?

**Comment by mb21** [comment]
You don't want to use `--self-contained` when outputting a PDF. Also make sure the image file is actually there.

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by tarleb** [comment]
I can reproduce the problem for this syntax:

    [[/Users/username/github/blog/images/apollo-home-screenshot.png]]

while this works as expected for me

    [[file:/Users/username/github/blog/images/apollo-home-screenshot.png]]

Reopening, both variants should work.

**Comment by tarleb** [comment]
We currently convert a link `[[file:/path/to/file.jpg]]` to a link with source `file:///path/to/file.jpg`. We then run into problems in later conversion stages.

This is not unique to org-mode. Specifying an image with schema `file:` leads to problems with other input formats as well:

    $ echo '![my image](file:///path/to/existing/image.jpg)' | pandoc --output image-output.pdf
    [WARNING] Could not fetch resource …

**Comment by mb21** [comment]
But only `file:///path` is a valid URL, right?

I guess this is the place to look: https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Class.hs#L577

**Comment by jgm** [comment]
Mauro Bieg <notifications@github.com> writes:

> But only `file:///path` is a valid URL, right?

It's a valid URL, but you can't make an HTTP request
to it.  I think what's happening is that pandoc is
trying to make an HTTP request since it sees it's a URL.

**Comment by mb21** [comment]
Ah, both `file:///path` and `file:/path` seem to be valid, [according to wikipedia](https://en.wikipedia.org/wiki/File_URI_scheme#How_many_slashes?).

**Comment by tarleb** [comment]
> Ah, both file:///path and file:/path seem to be valid, according to wikipedia.

Interesting, I didn't know. The org reader currently translates
`file:/path` into `file:///path`. It is what org does when exporting to
HTML, and the behavior is described (or hinted at) in this list here:
https://orgmode.org/manual/External-Links.html#External-Links.

**Comment by peng051410** [comment]
> You don't want to use `--self-contained` when outputting to PDF. Also make sure the image file is actually there.
> 
> For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

I remove the --self-contained option, the problem is still.

**Comment by mb21** [comment]
With `echo '![](file:///foo/bar.jpg)' | pandoc --self-contained`, I get

    InvalidUrlException "file:///foo/bar.jpg" "Invalid scheme"

I wanted to play around with some function in `Pandoc.Class`, but unfortunately `stack ghci` seems to be broken for me currently:

```
<no location info>: error: [-Wmissing-home-modules, -Werror=missing-home-modules]
    Modules are not listed in command line but needed for compilation: 
        Paths_pandoc
```

**Comment by jgm** [comment]
InvalidUrlException comes from Network.HTTP.Client, used by `openURL`.

Check out this code from Text.Pandoc.Class:
``` haskell
downloadOrRead :: PandocMonad m
               => String
               -> m (B.ByteString, Maybe MimeType)
downloadOrRead s = do
  sourceURL <- getsCommonState stSourceURL
  case (sourceURL >>= parseURIReference' .
                       ensureEscaped, ensureEscaped s) of
    (Just u, s') -> -- try fetching from relative path at source
       case parseURIReference' s' of
            Just u' -> openURL $ show $ u' `nonStrictRelativeTo` u
            Nothing -> openURL s' -- will throw error
```

If the source parses as a URI, then we use `openURL`, but of course this doesn't make much sense when it's a `file:/` URI.  So we should check the scheme.

**Comment by mb21** [comment]
@peng051410 for me the following works:

    echo '[[file:/Users/myuser/myfile.jpg]]' | pandoc -f org -o foo.pdf

**Comment by peng051410** [comment]
It works for me, Thanks!

**Comment by mb21** [comment]
Reopening for the `file:///` case...
