### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [jgm/pandoc#5520]
I would like to contribute to the development of the project. I am a graphic designer. I want to help. I want to design a logo. What do you say?

**Comment by jgm** [comment]
See https://groups.google.com/d/msg/pandoc-discuss/1bKIuyBnWaQ/xorl7JGXDQAJ
where a number of designs have been proposed.  If you want to propose another one, that's the place to do it!  No decision has been made, yet.  If you have a good idea for a design, we'd definitely consider it.

**Comment by allefeld** [comment]
@Batarian711, we have recently been discussing the logo issue again on the Google Groups list jgm linked to, and your input would certainly be welcome.
