### ISSUE TITLE
Temporary files are created in directory where pandoc is called instead of in /tmp

### ISSUE THREAD

**Issue by JJK96** [jgm/pandoc#5521]
When I run `pandoc -o /tmp/output.pdf input.md` there are temporary files created in the directory where I ran the command. 

Is there a reason that these are not created in /tmp?

I think it would be better to create those in /tmp both for increased speed and less unnecessary wear of the hard drive.

```
> pandoc -o /tmp/output.pdf file.md & sleep 0.5 && tree
[1] 20551
.
├── file.md
└── tex2pdf.-24e135a2d83cd08a
    ├── input.aux
    ├── input.log
    ├── input.out
    ├── input.pdf
    └── input.tex
```

The files are deleted afterwards.

The directory I run it from is a subdirectory of my homedir, so there is a ~ in that path, but that should not matter

edit: more detailed description

**Comment by mb21** [comment]
What pandoc version and OS are you on?

I believe we're using [getTemporaryDirectory](https://www.stackage.org/haddock/lts-13.22/directory-1.3.3.0/System-Directory.html#v:getTemporaryDirectory) for this..

**Comment by jgm** [comment]
On Windows, we create the temp directory locally if
the system temp directory path has a tilde (which
happens with longer user names), because the tilde can
cause problems in latex.

But this should not occur on a non-windows
system.  As noted, we need to know the exact pandoc
version and your OS and environment.

Jan-Jaap Korpershoek <notifications@github.com>
writes:

**Comment by JJK96** [comment]
I'm on arch linux.
```
> pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: /home/jjk/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment]
can you try with the newest pandoc version?

**Comment by JJK96** [comment]
I'm sorry, I thought I had the most recent version since I update regularly, but something went wrong there. 

Anyhow, it works with the newest pandoc version.
