### ISSUE TITLE
Code with strikeout generates undesired LaTeX

### ISSUE THREAD

**Issue by mpark** [jgm/pandoc#5529]
`pandoc 2.7.2`

Consider the following markdown:
```
~~`hello world`~~

~~_`hello world`_~~
```

They generate the following LaTeX:
```latex
\sout{\texttt{hello\ world}}

\sout{\emph{\texttt{hello\ world}}}
```

which then outputs:
![Screen Shot 2019-05-29 at 1 57 22 AM](https://user-images.githubusercontent.com/2275240/58543936-3f258d00-81b5-11e9-8a50-4bda7e925782.png)

The desired output would be:
![Screen Shot 2019-05-29 at 2 00 45 AM](https://user-images.githubusercontent.com/2275240/58544151-975c8f00-81b5-11e9-9b3b-d453dd823e9d.png)

---

1. In #1694, escaped spaces were added to `\texttt`. `\sout` does not handle this properly.
2. In #1294, inline __highlighted__ code was wrapped in `\mbox` within strikeout. This is not applied to inline non-highlighted code. That is, removing [this line](https://github.com/jgm/pandoc/blob/2.7.2/src/Text/Pandoc/Writers/LaTeX.hs#L1327) would make it such that the first case would be fixed.
3. The [`protectCode`](https://github.com/jgm/pandoc/blob/2.7.2/src/Text/Pandoc/Writers/LaTeX.hs#L1325-L1330) added in #1294 doesn't seem to __walk__ through the elements. If it did, I think the second case would also be fixed.

My current solution is to run the following `panflute` filter:
```
def protect_code(elem, doc):
    if isinstance(elem, pf.Code):
        return pf.Span(
                   pf.RawInline('\\mbox{', 'latex'),
                   elem,
                   pf.RawInline('}', 'latex'))

def strikeout(elem, doc):
    if not isinstance(elem, pf.Strikeout):
        return None

    elem.walk(protect_code)

if __name__ == '__main__':
    pf.run_filter(strikeout)
```

**Comment by mb21** [comment]
Can you please also post the expected LaTeX output?

**Comment by mpark** [comment]
I purposefully didn't include an "expected" LaTeX output because I don't particularly have one.
The `\mbox` solution seems to work but I'm not a LaTeX expert. It was also implemented in 2014 so I'm not sure that that's still the correct solution here. Having said that, the LaTeX generated by the filter which produces the desired output is:

```latex
\sout{{\mbox{\texttt{hello\ world}}}}

\sout{\emph{{\mbox{\texttt{hello\ world}}}}}

```

**Comment by bpj** [comment]
Similar issues are described in section 3 of [the *ulem* manual pdf](http://tuxedo.net/pkg/ulem). It does indeed seem like `\mbox` is the correct workaround.

**Comment by jgm** [comment]
Thanks for the excellent bug report!
