### ISSUE TITLE
The word `exception` triggers an empty example block (converting markdown to org-mode)

### ISSUE THREAD

**Issue by stroiman** [jgm/pandoc#5530]
I converted a markdown file to org-mode file:

The text

```
We just assigned a number to a string value. This will probably generate a hard
to diagnose exception further down the line. And a particular annoying exception
because the bug is in the test code, not the production code.
```

Got converted to

```
We just assigned a number to a string value. This will probably generate
a hard to diagnose #+begin_example

#+end_example
ception further down the line. And a particular
annoying exception because the bug is in the test code, not the
production code.
```

Command executed:

pandoc -f markdown -t org -o Documentation.org Documentation.md

Input file: https://github.com/stroiman/respect/blob/master/Documentation.md (commit 20783a2)

Pandoc version

```
$ pandoc --version                                                                                                 
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /Users/peter/.local/share/pandoc or /Users/peter/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment]
Hm.. cannot reproduce, neither locally nor [on try. pandoc.org](https://try.pandoc.org/?text=We+just+assigned+a+number+to+a+string+value.+This+will+probably+generate+a+hard%0Ato+diagnose+exception+further+down+the+line.+And+a+particular+annoying+exception%0Abecause+the+bug+is+in+the+test+code%2C+not+the+production+code.&from=markdown&to=org)

**Comment by stroiman** [comment]
Strange. I used the macOS version, installed using homebrew - installed just a few hours ago.

**Comment by stroiman** [comment]
Strangely enough, neither can I reproduce. Same input file, same command. Different result. 🤔

**Comment by stroiman** [comment]
This is probably an emacs-thing, as `ex<tab>` produces the example block.
