### ISSUE TITLE
epub: the class hidden is not processed correctly

### ISSUE THREAD

**Issue by alibou99** [jgm/pandoc#5534]
```
<h1 class="heading1" id="int"><span id="page1" epub:type="pagebreak">
<span class="hidden">1</span></span><a class="link" href="Table_des_matieres.xhtml#int">
<span style="color: #000000;">Introduction</span></a></h1>

```
Current output : 1Introduction

expected output : Introduction , with a hidden link to the TOC

**Comment by jgm** [comment]
Is the use of this class part of the epub standard?  If so, can you link to the documentation?

If not, then just be aware that pandoc doesn't process CSS.  If you have a CSS rule for the `hidden` class that suppresses this element, pandoc will simply ignore that. It handles structural elements, not presentation.

**Comment by jgm** [comment]
Best solution would be to use a lua filter to remove Span elements with class 'hidden'.

**Comment by alibou99** [comment]
that's exactly what I'm seeing, but as I'm new to this unviver it takes a bit of time, but I plan to get involved in this project, if you have any advice, where to start, I'm interested. thank you so much
