### ISSUE TITLE
Exclude ASCII Characters

### ISSUE THREAD

**Issue by nima87** [jgm/pandoc#5536]
Hi,
Sorry if this is not the right place to ask this question. I have a MS Word(docx) file which I want to convert to `markdown`, the file is utf-8 with non-latin characters and is BIDI. 
My problem could be divided in two parts:
1. **Converting special characters:**
In converting this file to `md` unfortunately it makes end of the line characters disappear and the character at the end of the line sticks character at the begining of the next line. This problem does not exist in `reStructuredText`.
2. **Finding asciii characters:**
As mentioned, there are different character sets in this document: Persian and English. I want to add something before English words or Group of English words. Consider the following example:
<div dir=rtl>
این صرفاً یک امتحان **This is a test 1324** است.
</div>

I want the English word be enclosed in something like this `\lr{This is a test 1324}`_(latex left to right command in a local package for Persian)_ without affecting the surrounding Persian characters.
And some occurrences this English text is enclosed in parentheses, is there a way to include the parentheses also: 

<div dir=rtl>
این صرفاً یک امتحان (This is a test) است.
</div>

to `\lr{(This is a test)}`.
3. Is there any way to convert Heading Styles of MS-Word to markdown tags for example **Heading 1** to `#` and so on.
Thank you.

**Comment by jgm** [comment]
Please ask this sort of question on the [pandoc-discuss mailing list](https://groups.google.com/forum/#!forum/pandoc-discuss).

**Comment by nima87** [comment]
Thank you.
