### ISSUE TITLE
Warning does not indicate which file contains the problem.

### ISSUE THREAD

**Issue by bulrush15** [jgm/pandoc#5537]
Pandoc: 2.2.1. I cannot use a newer version because it forces justification of all my EPUB files. I already posted on the Google Groups about this. 

**Problem:** When a footnote is defined or not used, the filename with the footnote is not even mentioned. Please check in the current version of Pandoc that the filename is mentioned for every single error message. In some cases I have to use 10 Markdown files to make an EPUB. Some of my EPUBs get large. 

**To reproduce:** 

1. Make a single Markdown (text) file with a footnote that is defined but not used. Example markdown: `[^foot1]: This is not used.`
2. Convert the markdownfile to EPUB using this command line: `pandoc --from=markdown_mmd+backtick_code_blocks+yaml_metadata_block+line_blocks+auto_identifiers --css=\pandocbooks\style01.css --to=epub -o infile.epub infile.md`
3. Notice if error message contains file name of the error.

**Sample markdown file**

```
# Heading 1

This is text to be used in an EPUB file.

[^foot1]: This is not used.

```

**Comment by jgm** [comment]
The way pandoc currently works, the input files are simply concatenated and then passed to the parser. So, the parser actually does not have the information about which file contains the line in question.

It would take some larger architectural changes to make this possible.
