### ISSUE TITLE
Improve missing glyph warning

### ISSUE THREAD

**Issue by worstje** [jgm/pandoc#5538]
I occasionally help out with another OS project that supports exporting thru Pandoc, and earlier today we had a user who came across an error that is a bit troublesome for us to diagnose:

> [WARNING] Missing character: There is no  in font [lmroman12-regular]:mapping=tex-text!

Despite the program dumping the error message in box a dialog box and console for debugging purposes, it does not show a character that helps us identify what the issue is and where in the source material that problem might be hiding.

I have some ideas on ways to solve this problem (Google is useful that way) which I might try out at some point, but that does not take away that this error message could be made more useful.

Is it viable to quote the troublesome character and also show a unicode codepoint and/or friendly name? For example, assuming the missing character is the interrobang and that whatever font used to read the log does not support displaying said interrobang:

> [WARNING] Missing character: There is no `` (interrobang, U+203D) in font [lmroman12-regular]:mapping=tex-text!

Because it is trying to directly print the character in some sort of encoding to begin with I believe this would not be too impossible to achieve.

(I also realize there is also a source encoding that may not be Unicode, but because it is about glyph identification which is logically separate from the encoding itself, Unicode seems to have a pretty convenient naming and identification system available.)

**Comment by jgm** [comment]
This message is simply passed on by pandoc. It comes from LaTeX.
Probably your console font lacks the character.

I guess we could parse the LaTeX message and substitute a unicode code point number for the character before passing it on.

**Comment by worstje** [comment]
Ah, my bad. Apologies. It seems I should have dug deeper where the error came from, but I have never used LaTeX myself. 😄 I was merely passing on an observation I made while looking at a reported issue for our program. It should probably be fixed further upstream then?

(Assuming that even makes sense...! I have no clue about LateX' inner architecture; maybe this kind of error message improvement is out of scope for LateX if it never does anything with unicode. Which would make pandoc the right spot after all? All guesswork on my part.)

Funny thing is that the character did not show in either the console nor the QtMessagebox our project pops up that alerts the user something failed. So it should be at least two fonts that are missing the character in question...

Thank you for the timely response. Please handle this suggestion as you see fit. I'll just go and see what else I can do in my little domain to help the user in question.

**Comment by jgm** [comment]
Now it says
```
[WARNING] Missing character: There is no 😄 (U+1F604) in font [lmroman10-regular]:mapping=tex-text;!
```
Thanks for the suggestion.

**Comment by jgm** [comment]
This message is coming from LaTeX, pandoc is just
passing it on.  Very likely the console font doesn't
contain the character either, which is why it doesn't
show up.
