### ISSUE TITLE
Markdown reader: empty title followed by [] is parsed as title and link

### ISSUE THREAD

**Issue by jolars** [jgm/pandoc#5549]
I am trying to compile the following source file using `pandoc -t beamer test.md -o test.pdf`

```md
---
title: Test
---

## 

- [x] Done!
- [ ] Not yet done.
 ```

I expect to get a slide without header and with a task list with one checked box and one empty box. What I get, however, is the following:

![image](https://user-images.githubusercontent.com/13087841/58866952-e2950700-86b9-11e9-95cd-b091ee2caaa3.png)

If I output to `.tex` I get the following:

```tex
\begin{itemize}
\tightlist
\item[$\boxtimes$]
  Done!
\item
  \protect\hyperlink{section}{} Not yet done.
\end{itemize}
```

The reason this happens is the inclusion of an empty frame title. If I insert text into the title:

```md
---
title: Test
---

## Frame

- [x] Done!
- [ ] Not yet done.
```

it now works fine:

```tex
\begin{itemize}
\tightlist
\item[$\boxtimes$]
  Done!
\item[$\square$]
  Not yet done.
\end{itemize}
```

It doesn't seem to matter where in the document the empty header is. As long as there is an empty section title somewhere, tasks lists will start failing.

I am running pandoc 2.7.2

**Comment by mb21** [comment]
Do you have an expected latex output? I'm not sure we officially support empty titles... what happens if you enter a non-breaking space as the title?

    ## &nbsp;

**Comment by jolars** [comment]
The expected output is by the end of my post (after "it now works fine"). Yup, adding `&nbsp;` does the trick. I also realized that adding a horizontal rule also does, which I suppose is the preferred solution to this.

> I'm not sure we officially support empty titles...

Haha, well that makes this issue a non sequitur. However, I understand why empty titles would make little sense for a regular article, but in the context of presentations it makes sense to request a new frame with no title.

**Comment by mb21** [comment]
Sorry, I missed that part. The problem is actually more generic. The title-parser seems to be too greedy with an empty title and parse `[]` (or `[ ]`) as a link, which should not happen:

```
~ pandoc -t native
##

[]
^D

[Header 2 ("section",[],[]) []
,Para [Link ("",[],[]) [] ("#section","")]]
```

**Comment by mb21** [comment]
@jolars You can use the following as a workaround:

```
## &nbsp;

- [x] Done!
- [ ] Not yet done.
```

**Comment by jgm** [comment]
What you're seeing here is not due to over-greedy parsing. Rather, it's the `implicit_header_references` extension.  To avoid confusion, we should change this extension so it doesn't work for empty headers.

**Comment by jgm** [comment]
Or just use

    -f markdown-implicit_header_references

if you don't need that extension.
