### ISSUE TITLE
Custom Footer Beamer theme

### ISSUE THREAD

**Issue by huyhoang8398** [jgm/pandoc#5550]
Im currently using Ilmenau theme with beaver colorscheme.
Can i custom my footer in YAML so that i can have the slide number ( Thus ilmenau default theme doesnt have that ). 
![Screen Shot 2019-06-05 at 5 22 10 AM](https://user-images.githubusercontent.com/25379882/58918620-225cfc80-8755-11e9-8d8d-86a0c926e3eb.png)

**Comment by jgm** [comment]
Please ask questions on pandoc-discuss. This tracker is for bug reports, not questions.
