### ISSUE TITLE
Failed to convert to pdf when using `context` pdf engine.

### ISSUE THREAD

**Issue by stevenleeS0ht** [jgm/pandoc#5554]
Pandoc version: 2.7.2
Context version: 1.02

Sample command:
`pandoc -s --toc hello.md --pdf-engine=context -o hello.pdf`

Error output message:
```
Error producing PDF.
tex error       > tex error on line 91 in file /tmp/tex2pdf.-2876d576a620aa5a/input.tex: ! Undefined control sequence
```

**Comment by mb21** [comment]
Can you provide a minimal reproducible example of the input?

**Comment by stevenleeS0ht** [comment]
Sorry the document is huge and is confidential. it works properly under other engine but stuck in `context`. 

The debugging mechanism of this toolchain is poor it doesn't produce where it got error in Markdown. And it will delete intermediate tex file when error occurs.

The feature of this document: fixing latex math equation with markdown.

**Comment by mb21** [comment]
Sorry, but how are we supposed to fix it if you cannot tell us what input is causing the error?

You could try splitting your document in the middle and see which half causes the problem (then do that again and again, binary-search). In the end, give us the minimal example that causes the problem.

**Comment by jgm** [comment]
You will see the intermediate file if you use `--verbose`.
I'd recommend using pandoc to produce a context file `-t context -s -o myfile.ctx` and processing it manually using the same command pandoc is using (`--verbose` will tell you that).
This should help you diagnose the issue.
