### ISSUE TITLE
+smart extension disables --self-contained

### ISSUE THREAD

**Issue by frabjous** [jgm/pandoc#5559]
If I try this command (supposing image.png really exists; it can be whatever):

```sh
echo 'an "image" ![](image.png)' | pandoc --self-contained --metadata pagetitle="test" -t html5+smart
```
I get:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>test</title>
  <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<p>an “image” <img src="image.png" /></p>
</body>
</html>
```
Notice that despite using `--self-contained`, we just have a normal img tag here.

If I remove the "`+smart`", then image.png is converted to base64 and embedded in the img tag, as one would expect with the `--self-contained option`.

Seems like a bug that adding "`+smart`" would make a difference. Of course, I think smart is more or less the default these days, so it may be without practical import, but thought I'd report anyway, especially as it may affect other extensions as well.

Version:
```
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

**Comment by jgm** [comment]
Already fixed in 66dd2008b060d285d5e07ace8a89b17c63132022
