### ISSUE TITLE
Cannot convert from FB2 if there is "id" in "author" tag

### ISSUE THREAD

**Issue by juliancoffee** [jgm/pandoc#5560]
```
<?xml version="1.0" encoding="UTF-8"?>
<FictionBook xmlns:l="http://www.w3.org/1999/xlink" xmlns="http://www.gribuser.ru/xml/fictionbook/2.0"><description><title-info><genre>literature_19</genre><genre>prose_rus_classic</genre><author><first-name>Лев</first-name><middle-name>Николаевич</middle-name><last-name>Толстой</last-name><id>69f09542-2a81-102a-9ae1-2dfe723fe7c7</id></author><book-title>Война и мир. Книга 1</book-title> <annotation><p>В книгу вошли первый и второй тома романа «Война и мир» – одного из самых знаменитых произведений литературы XIX века.</p>
```
when I wrote 
`--> pandoc -f fb2 -i voyna-i-mir-kniga-1-yyReA.fb2 -o voyna_i_mir.html`
I have answered 
`Couldn't parse FB2 file: unexpected element id in author.
`
```
`--> pandoc --version
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/julian/.local/share/pandoc or /home/julian/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
(I install pandoc in Arch Linux by pacman)

If I delete "id" it works fine.
(FBReader can read it any way)

**Comment by jgm** [comment]
I notice that the TODO list in the source includes "Parse ID attributes for all elements that have it."
@link2xt do you want to look into this?

**Comment by link2xt** [comment]
> I notice that the TODO list in the source includes "Parse ID attributes for all elements that have it."

This TODO is about id *attributes*, not elements.

`authorType` cannot contain `id` element according to the XML schema:
https://github.com/link2xt/fb2/blob/08a67bdf2eefc809feee389d50e60811e677024c/FictionBook2.1.xsd#L177

Some libraries add all kinds of custom elements that they use internally, though, so we may want to turn unexpected element errors into warnings.

**Comment by jgm** [comment]
I see. Seems like the best approach would be to ignore these unknown elements, with a SkippedContent warning.

**Comment by jgm** [comment]
I'll take care of this, we need to add a new log message since we don't have source positions in this parser.
