### ISSUE TITLE
lua filter 

### ISSUE THREAD

**Issue by alibou99** [jgm/pandoc#5561]
I simply wish to reach the content of the ref attribute in order to delete all the contents before the # character. except that the filter lua does not recognize ref as an attribute. in a global way, is there documentation that allows a beginner to do a minimum of excercise?

`'<span id="footnote-000-backlink"><a class="_idFootnoteLink" href="../Text/eBook-Dans_neige-3.xhtml#footnote-000"> textlink</a></span>' | pandoc -f html+epub_html_exts -t native --lua-filter=href2.lua `

**Comment by jgm** [comment]
Hi! Questions should go to the pandoc-discuss mailing list, not here.  People on that list can help with questions about lua filters. This tracker is for bug reports.
