### ISSUE TITLE
Missing Text

### ISSUE THREAD

**Issue by alibou99** [jgm/pandoc#5562]
`'<div class="_idFootnotes"><div id="footnote-000" class="_idFootnote" epub:type="footnote"><p class="_10-notes"><a class="_idFootnoteAnchor" href="../Text/eBook-Dans_neige-3.xhtml#footnote-000-backlink">1</a>Text</p></div></div>' | pandoc -f html+epub_html_exts -t native`

result :  

```
[Div ("",["_idFootnotes"],[])
 []]
```

**Comment by jgm** [comment]
The epub footnotes are stored in state; a Note in the AST is produced when the corresponding note reference is parsed (element with `epub:type="noteref"`).  If there's no reference to the note, it doesn't appear in the AST at all.

**Comment by alibou99** [comment]
Thank you,
As you probably understood, I have a problem with the footnotes that are not properly processed when converting from epub to docx, the reason is that the footenotes are not in the same file as its reference. my idea is to remove the string part from the call of the note that refers to a file, because this is well located before the # in the link.target. Now, i understand that this is not possible in the state. is it possible via an option to give the user the ability to mechanically produce the footnotes and their references in the AST and let the lua filter repair the links after ? Or i have to do that before pandoc conversion via string replacement in the epub.

**Comment by mb21** [comment]
I'm not clear whether you think there is a bug in the epub reader, or whether you're trying to do something custom with a lua-filter.

For questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by jgm** [comment]
@mb21, the underlying bug is #5531.  The question here is about a workaround.

@alibou99 I think for now you'll need to preprocess the input.
