### ISSUE TITLE
support mathescape in default highlight

### ISSUE THREAD

**Issue by annProg** [jgm/pandoc#5563]
This is feature request.
Is it possible to support `mathescape` in default code highlight？
Just like `mathescape=true` in `listings` and `mathescape` in `minted`.

~~~markdown
math test [@lst:math]

```{#lst:math .csharp .mathescape mathescape=true caption="Test Math Escape"}
string title = "This is a Unicode π in the sky"
/*
Defined as $\pi=\lim_{n\to\infty}\frac{P_n}{d}$ where $P$ is the perimeter
of an $n$-sided regular polygon circumscribing a
circle of diameter $d$.
*/
const double pi = 3.1415926535
```
~~~

**Comment by mb21** [comment]
Pandoc stores code blocks as plain text, so there's no easy way to do this by default. However, you can certainly do that with a lua filter.

Please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) if you have questions / need help writing the filter. Thanks!

**Comment by annProg** [comment]
I had found solution from https://tex.stackexchange.com/questions/179926/pandoc-markdown-to-pdf-without-cutting-off-code-block-lines-that-are-too-long. It mentioned `fvextra`。Use `fvextra`，some problem in default highlight may be solved：

1.  mathescape
2. long line auto break

I think may use `fvextra`，and transfer user defined params to `fvextra`
~~~
```{#lst:test .md  .numberLines mathescape=true breaklines=true breakanywhere=true startFrom="100" caption="Markdown 代码高亮测试"}
test
```
~~~

generate 
```latex
\begin{Highlighting}[numbers=left,mathescape=true,breaklines=true,breakanywhere=true,firstnumber=100,]
```

when user define `mathescape=true`, pandoc leave math code original.

default `Highlight` define can be

```latex
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
```
