### ISSUE TITLE
CSS targetting table classes is not applied to PDF output

### ISSUE THREAD

**Issue by alastairmoore** [jgm/pandoc#5564]
I have noticed that CSS that targets a table class or ID is not applied when outputting a PDF file, however if I target a table element in the CSS file then it does style the table correctly.

Using the following example HTML (testing.html):

```
<!DOCTYPE html>
<html>
<head>
	<title>Testing</title>
</head>
<body>
<table class="shaded">
	<tr>
		<td>
			Praesent facilisis purus justo, at dapibus mauris elementum nec. Sed tortor turpis, imperdiet non ante condimentum, iaculis hendrerit nisi. Aenean at pretium neque, aliquam fermentum augue. Suspendisse bibendum accumsan dapibus. Curabitur eget sem in purus sodales pharetra maximus eget eros. Nullam ullamcorper vehicula aliquam. In pretium lacus sit amet sapien dignissim lacinia. Nulla sed luctus nunc, sit amet ultrices eros. 
		</td>
	</tr>
</table>
</body>
</html>
```

and the following CSS (table-class.css):

```
.shaded {
  background-color: #eee;
  border: 1px solid #333;
  padding: 15px;
}
```

Running the following command: `pandoc -s table-class.html -o table-class.pdf --css=table-class.css --pdf-engine=/usr/local/bin/wkhtmltopdf`

Results in the table not being affected. However, if I then use the following css

and the following CSS (table-element.css):

```
table {
  background-color: #eee;
  border: 1px solid #333;
  padding: 15px;
}
```

Running the following command: `pandoc -s testing.html -o table-element.pdf --css=table-element.css --pdf-engine=/usr/local/bin/wkhtmltopdf` renders the table as expected.

Using pandoc 2.7.2 and wkhtmltopdf 0.12.3

**Comment by mb21** [comment]
This is correct. Unfortunately, pandoc currently doesn't have attributes on table elements, see #1024.

**Comment by alastairmoore** [comment]
Ah, thank you. I shall keep an eye on the other thread.

**Comment by jgm** [comment]
If you want a certain styling to apply to all tables, then you may be able to add something to the latex header-includes that does this.

**Comment by alastairmoore** [comment]
@jgm unfortunatel I need to target individual tables by class. I shall wait and see what develops with this. Thanks all the same!

**Comment by mb21** [comment]
The current workaround is to wrap the table in a div....
