### ISSUE TITLE
Lua filters: can't remove named attribute

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#5569]
This is connected to #5568

Trying to remove a key—value with `el.attributes.foo = nil` causes an infinite loop in C code called by the `__newindex` metamethod. For now I can work around it by modifying the function quoted in #5568 to allow passing a plain table as second argument, and updating the intermediate map with its contents, deleting an existing value if the update value is false.
It works but it shouldn't be that hard!

If it doesn't work to get the nil assignment to work please consider adding a `:remove(attr_name)` method.

FWIW setting the key to an empty string is no good workaround since the attribute shows up with an empty value in Markdown and HTML output.

**Comment by tarleb** [comment]
I don't get an infinite loop, but setting *any* attribute key to
nil seems to remove the last key-value pair. Definitely not what we
want.

**Comment by tarleb** [comment]
Benct Philip Jonsson writes:

> Trying to remove a key—value with `el.attributes.foo = nil` causes an
> infinite loop in C code called by the `__newindex` metamethod.

I see it now, it happens if the list of attributes is empty.

**Comment by bpj** [comment]
That explains. I could have sworn I had done it successfully before (apparently without noticing that the last named attribute disappeared too!)
