### ISSUE TITLE
Inline highlighted code within a header generates invalid LaTeX

### ISSUE THREAD

**Issue by mpark** [jgm/pandoc#5574]
`pandoc 2.7.2`

The following Markdown:
```
# `foo`{.cpp}
```
generates:
```latex
\hypertarget{foo}{%
\section{\texorpdfstring{\VERB|\NormalTok{foo}|}{foo}}\label{foo}}
```
and attempting to produce a PDF results the following error:
```
Error producing PDF.
! TeX capacity exceeded, sorry [parameter stack size=10000].
\@ifundefined #1->
                  \ifcsname #1\endcsname \@ifundefin@d@i \else \@ifundefin@d...
l.90 ...|\NormalTok{foo}|}{foo}}\label{foo}}
```

**Comment by mpark** [comment]
@jgm: I looked into this a bit. The following workaround seems to work:
```
\hypertarget{foo}{%
\section[foo]{\VERB|\NormalTok{foo}|}\label{foo}}
```
I guess this could be a decent workaround:
```
\hypertarget{foo}{%
\section[\texttt{foo}]{\VERB|\NormalTok{foo}|}\label{foo}}
```
---
On the other hand, I wonder whether the `\VERB` environment is all that useful now that most special characters are escaped by https://github.com/jgm/skylighting/commit/1832ce0f28770bb706917e7a097d33a43f0fb68c anyway. Is it possible to simply use `\texttt` for inline code instead?

**Comment by Wandmalfarbe** [comment]
I just want to add that it compiles perfectly without the label:

1. <code># \`foo\`{.cpp}</code>: Error
2. <code># \`foo\`</code>: Ok
3. <code># \`foo\`{.cpp}</code> with `--listings`: Error
4. <code># \`foo\`</code> with `--listings`: Ok

**Comment by mpark** [comment]
@Wandmalfarbe: Yes, that works today because raw verbatim code produces `\texttt{...}`. The highlighted code is produced by skylighting inside `\VERB|...|`, including a "language tag" such as `foo`{.default}.
