### ISSUE TITLE
Pandoc stripping <p> from <figcaption>

### ISSUE THREAD

**Issue by machal** [jgm/pandoc#5576]
I'm curious why Pandoc removes `<p>` from `<figcaption>`. 

My original HTML:

```html
<figure>
  <img src="image.jpg" alt="">
  <figcaption>
    <p><em>Caption…</em></p>
  </figcaption>
</figure>
```

Then I run:

```bash
pandoc -o target.epub source.html --from=html+raw_html --to=epub
```

EPUB's HTML then looks like:

```html
<figure>
  <img src="image.jpg" alt="">
  <figcaption>
    <em>Caption…</em>
  </figcaption>
</figure>
```

My Pandoc version:

```bash
$ pandoc --version
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

**Comment by mb21** [comment]
Pandoc currently does not support block elements (like `<p>`) as figure captions. Closing in favour of #3177.

btw. if you only want to do html to epub (which is basically just a zipped html bundle), you'll probably get better results with another tool than pandoc, e.g. calibre. From our manual:

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size. And some document elements, such as complex tables, may not fit into pandoc’s simple document model. While conversions from pandoc’s Markdown to all formats aspire to be perfect, conversions from formats more expressive than pandoc’s Markdown can be expected to be lossy.
