### ISSUE TITLE
Lineblocks in MS output should start with .LP instead .PP

### ISSUE THREAD

**Issue by tkurtbond** [jgm/pandoc#5588]
Lineblocks in MS output frequently (maybe always?) start with a .PP, resulting in the first line of the lineblock being indented, which seems against the purpose of the lineblock.  Can a .LP always be output instead?  That way the first line would not be indented.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by tkurtbond** [comment]
pandoc 2.7.1
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7

$ pandoc -r rst -w ms -o lb.ms
This is a paragrpah, which will probably be output unindented.

| This is the first line of a lineblock,
| which will probably be indented,
| which is bad.
^D

produces

.LP
This is a paragrpah, which will probably be output unindented.
.PP
This is the first line of a lineblock,
.br
which will probably be indented,
.br
which is bad.

Notice that the lineblock begins with a .PP, resulting in an indented first line.  It should use a .LP, which would result in a non-indented first line.
