### ISSUE TITLE
get_working_directory() is missing in pandoc.system

### ISSUE THREAD

**Issue by niszet** [jgm/pandoc#5594]
I tried to use the function of `pandoc.system.get_working_directory()` in the manual https://pandoc.org/lua-filters.html#system-get_working_directory to get working directory in my Lua script as following code.

```
function Doc(e)
  print(pandoc.system.get_working_directory())
end
```

Then following messages are returned.

```
Error running filter xxx.lua:
xxx.lua:3: attempt to call a nil value (field 'get_working_directory')
stack traceback:
        xxx.lua:3: in function 'Doc'
```

I run the following code to check functions in pandoc.system.

```
function Doc(e)
  for k,v in pairs(pandoc.system) do
    print(k)
  end
end
```

Then followings are listed.

```
arch
with_environment
os
get_current_directory
with_temp_directory
with_working_directory
environment
```

Using `get_current_directory` instead of `get_working_directory` as

```
function Doc(e)
  print(pandoc.system.get_current_directory())
end
```

then I got correct working directory as following.

```
C:\Users\niszet\Documents\work
```

Also, `with_temporary_directory` in manual https://pandoc.org/lua-filters.html#system-with_temporary_directory is implemented as `with_temp_directory` as shown in above.

My environment is following.

```
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
```

And released binary `pandoc-2.7.3-windows-x86_64.zip` is used in Windows10 1803.

**Comment by tarleb** [comment]
It seems that I successfully confused myself when I went back and forth while deciding on a name. The documentation contains the "correct" names, with the sources being wrong. The module is defined in file `src/Text/Pandoc/Lua/Module/System.hs`. If you have some time, a PR would be greatly appreciated.

**Comment by tarleb** [comment]
and thanks for noticing :)

**Comment by niszet** [comment]
Thank you for confirming. I will try to make a PR in this weekend.

**Comment by niszet** [comment]
Can we close this issue? (because PR is already merged)
