### ISSUE TITLE
Top-level bullet lists turned into plain text when converting html to markdown

### ISSUE THREAD

**Issue by eaganj** [jgm/pandoc#5598]
In pandoc 2.7.3, converting from html to markdown sometimes converts top-level bullet lists into plain text.

Consider the following html :

```
<h2>Header</h2>

<ul>
    <li>Apples</li>
    <ul>
        <li>MacIntosh</li>
        <li>Granny Smith</li>
        <li>Pink Lady</li>
    </ul>
    <li>Oranges</li>
    <ul>
        <li>Naval</li>
        <li>Blood</li>
        <li>Maltaise</li>
    </ul>
</ul>
```

Its corresponding markdown would be expected to be something like :

```
Header
------

* Apples
    * MacIntosh
    * Granny Smith
    * Pink Lady
* Oranges
    * Naval
    * Blood
    * Maltaise
```

However, running through pandoc `cat apples-oranges.html | pandoc -f html -t markdown` removes the top-level bullets :

```
Header
------

Apples

-   MacIntosh
-   Granny Smith
-   Pink Lady

Oranges

-   Naval
-   Blood
-   Maltaise
```

System info:

```
Atraxi:~ $ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

Atraxi:~ $ pandoc --version
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
...
```

This bug seems to exist at least as far back as pandoc 2.2.2.

**Comment by mb21** [comment]
Your HTML input is invalid, see https://validator.w3.org

**Comment by eaganj** [comment]
Ugh.  Indeed.  I couldn't imagine how this could remain a bug for so long!  Oups!

(Turns out, it's a garbage input coming from wonky contentEditable handling, which didn't manifest itself in WebKit & Blink's permissive rendering.)
