### ISSUE TITLE
ODT reader fails if document contains SVG images

### ISSUE THREAD

**Issue by priiduonu** [jgm/pandoc#5599]
When trying to convert ODT document containing SVG image(s) to markdown or html, an error is produced:

```
pandoc --extract-media=asdf -f odt -s test.odt -t markdown -o test.md
[WARNING] Could not fetch resource 'Pictures/10000B0D0000402F000030E33BD9B5FCC77B946C.svgPictures/100002010000026D000001D96D383B8BE0CA3266.png': replacing image with description
[WARNING] IO Error (ignored): asdf/.: openBinaryFile: inappropriate type (Is a directory
```
Steps to reproduce:

- create a new ODT document
- insert an SVG image (e.g. https://commons.wikimedia.org/wiki/File:Test.svg)
- save document
- run the command above

pandoc 2.7.3
LibreOffice Writer 6.1.5.2-5.fc29

**Comment by mb21** [comment]
Could you attach such a minimal odt please?

**Comment by priiduonu** [comment]
Here you are:
[test.zip](https://github.com/jgm/pandoc/files/3302120/test.zip)
(please rename it to test.odt)

**Comment by blmage** [comment]
This is due to the fact that the document (unexpectedly) contains two images in a single frame:
```xml
<draw:frame draw:style-name="fr1" draw:name="Pilt1" text:anchor-type="paragraph" svg:width="16.431cm" svg:height="12.515cm" draw:z-index="0">
    <draw:image xlink:href="Pictures/10000B0D0000402F000030E33BD9B5FCC77B946C.svg" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" loext:mime-type="image/svg+xml"/>
    <draw:image xlink:href="Pictures/100002010000026D000001D96D383B8BE0CA3266.png" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" loext:mime-type="image/png"/>
</draw:frame>
```
Because the `png` image was most certainly added as a fallback, I've just pushed a PR (#5601) that makes sure that extraneous images get ignored.
