### ISSUE TITLE
JATS Template: abstract not included

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc#5603]
Currently, the JATS Template does not include the abstract. However, Abstracts are clearly part of the JATS specification (https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/abstract.html). Would be great if this could be added.

**Comment by mb21** [comment]
Could you perhaps test the template in the pull request?

**Comment by denismaier** [comment]
This seems to work. 

Other metadata fields are still not there, though. (Although they appear in the template, see [here](https://groups.google.com/forum/#!topic/pandoc-discuss/4gfAT-EhWtY)) But I guess I should open a new issue for this if this turns out to be a bug, right?

**Comment by mb21** [comment]
@denismaier apparently, there can be only one journal entry. So the value of journal should not be an array (like you had), but rather:

```
---
journal:
  title: Journal
---
```

**Comment by denismaier** [comment]
Oh. I See. Thank you!
