### ISSUE TITLE
Add Dart syntax highlighting (I'd like to submit a PR)

### ISSUE THREAD

**Issue by thosakwe** [jgm/pandoc#5607]
Running Pandoc `2.7.2`. I am interested in sending a pull request to add syntax highlighting for the Dart language to Pandoc. Dart's popularity has seen a boost in recent years, especially because of the rise of Flutter.

I'm not super well-versed with the workings of this package, but IIRC, I need to create a Kate's file for the language (there may be tools out there to auto-convert from TextMate or VSCode).

Can I send in a PR?

**Comment by mb21** [comment]
Sure! For testing you can do the following (from https://pandoc.org/MANUAL.html#syntax-highlighting):

> you can use the `--syntax-definition` option to load a [KDE-style XML syntax definition file](https://docs.kde.org/stable5/en/applications/katepart/highlight.html). Before writing your own, have a look at KDE's [repository of syntax definitions](https://github.com/KDE/syntax-highlighting/tree/master/data/syntax).

If you've got an XML file that works, send a pull request with a new file to https://github.com/jgm/skylighting/tree/master/skylighting-core/xml

**Comment by mb21** [comment]
I'm closing this, but feel free to make a pull to jgm/skylighting or ask more questions on pandoc-discuss.
