### ISSUE TITLE
ConTeXt writer: improve PDF/A output

### ISSUE THREAD

**Issue by mb21** [jgm/pandoc#5608]
Moved from #5409:

> mb21: @klpn Any downsides when using your gist? If not, would you like to make a pull request? For context: the `pdfa` tempalte variable was added in https://github.com/jgm/pandoc/commit/46f4238a2a40b5542612bc745e63ce503ce12a32

> klpn: I have not discovered any problems, but I should perhaps test with some more documents. However, the Pandoc manual explicitly states that the `pdfa` variable "adds to the preamble the setup necessary to generate PDF/A-1b:2005", so this should then be changed as well, if we want to always use 2a (i.e. version 2, level A conformance). When using PDF/A for documents born digital, it is best to use level A (which includes Unicode mapping and tagging) if possible, rather than B, but some older preservation guidelines still require version 1. Perhaps, the `pdfa` variable should be changed so that the user can choose which version of PDF/A to use ([different PDF:s supported by ConTeXt](https://source.contextgarden.net/tex/context/base/mkiv/lpdf-fmt.lua?search=pdf-fmt))?

**Comment by mb21** [comment]
@klpn sounds good! The template could be sensitive to two variables: `pdfa1b` and `pdfa2a`. For backwards compatibility, the ConTeXt writer would set `pdfa1b` to true if `pdfa` was set.

@hmenke what do you think?

**Comment by klpn** [comment]
Or perhaps, we could leave the boolean `pdfa` variable as it is (for compatibility), and add a new `pdfatype`, whose value could be specified as `1a:2005`, `1b:2005`, `2a` and so on (if `pdfa` is not specified). Something like this in the template:
```
$if(pdfa)$
% attempt to generate PDF/A
\setupbackend
  [format=PDF/A-1b:2005,
   intent=sRGB IEC61966-2.1,
   profile=sRGB.icc]
$else$
$if(pdfatype)$
\setupbackend
  [format=PDF/A-$pdfatype$,
   intent=sRGB IEC61966-2.1,
   profile=sRGB.icc]
$endif$
$endif$
```

**Comment by mb21** [comment]
Or the Context writer could set the `pdfa` variable to `1b:2005` if it was to `true`, then:

    $if(pdfa)$
    % attempt to generate PDF/A
    \setupbackend
      [format=PDF/A-$pdfa$,
       intent=sRGB IEC61966-2.1,
       profile=sRGB.icc]
    $endif$

**Comment by klpn** [comment]
Yes, the last suggestion is probably the most elegant, I think (but it requires changes to the writer, as well as the template and the manual).

**Comment by klpn** [comment]
Made a fork of Pandoc with [changes according to the last suggestion](https://github.com/jgm/pandoc/compare/master...klpn:master): it seems to work correctly.

**Comment by mb21** [comment]
Nice! I would use `lookupMetaBool "pdfa" metadata` from `Pandoc.Writers.Shared`, but then please make a pull request and @jgm is going to take a look..
