### ISSUE TITLE
Fenced div main class as string and more attributes later

### ISSUE THREAD

**Issue by chaoxu** [jgm/pandoc#5611]
In the fenced div, if I want to give it a class, and then add attributes. I can try the following. 

```
::: Theorem {#id}
This is a theorem.
::: 
```

The HTML output is
```
<p>::: Theorem {#id} This is a theorem. :::</p>
```

However, wouldn't the following be a much more reasonable output?

```
<div id="id" class="Theorem">
<p>This is a theorem.</p>
</div>
```

Of course, I can do the following instead. But it looks quite ugly, and most of the time there are no additional attributes other than the class. 

```
::: {.Theorem #id}
This is a theorem.
::: 
```

**Comment by mb21** [comment]
That could certainly be debated. Maybe bring it up on the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead?

**Comment by jgm** [comment]
I think raising this on pandoc-discuss is a good idea.  (You can link here.)

**Comment by tarleb** [comment]
The proposal was discussed in a pandoc-discuss [thread](https://groups.google.com/g/pandoc-discuss/c/2NWx-P7p7P4/m/PRwPHaJhAAAJ). No clear conclusion was reached, but there were worries about inconsistencies which seem to make this difficult.
