### ISSUE TITLE
Feature suggestion: Code Callouts

### ISSUE THREAD

**Issue by coatless** [jgm/pandoc#5613]
Recently, I stumbled upon AsciiDocs' ability to annotate lines of code using a language specific comment followed by a number and, then, a description of the code line outside of the code block. How feasible would it be to add this feature into pandoc?

c.f. https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code

![Screen Shot 2019-06-20 at 2 45 08 PM](https://user-images.githubusercontent.com/833642/59979260-05288a80-95ab-11e9-8da5-dab8ea71d6ef.png)

**Comment by jgm** [comment]
It should be possible to write a lua filter that does this, if you have a restricted range of output formats in mind.  Given the way code blocks are represented in pandoc (as just a block of text), there isn't a good way of doing callbacks that will work in all output formats.

**Comment by coatless** [comment]
@jgm a couple of quick questions:

1. Looking at [pandoc's overview of lua filters](https://pandoc.org/lua-filters.html#type-ref-CodeBlock), the closest example I think is the [ABC notation conversion](https://pandoc.org/lua-filters.html#converting-abc-code-to-music-notation). Would this be a good reference implementation for file format type restrictions and substitution?
2. By callbacks, are you referencing the _hyperlinks_ in the callout to the list items after the codeblock? If so, I'm not too concerned about retaining the linking feature compared to injecting an annotation. 
3. I read that the codeblocks are accessible under the lua filtering; however, would it be possible to modify the parsing done by [`skylighting`](https://github.com/jgm/skylighting/)?

**Comment by jgm** [comment]
>  Looking at pandoc's overview of lua filters, the closest example I think is the ABC notation conversion. Would this be a good reference implementation for file format type restrictions and substitution?

Take a look at the sample tikz filter, which behaves differently in different formats. (See the documentation for FORMAT.)

> By callbacks, are you referencing the hyperlinks in the callout to the list items after the codeblock? If so, I'm not too concerned about retaining the linking feature compared to injecting an annotation.

Yes.  Leaving a literal `// <1>` in the code block could be a possibility, but if you just want that, you can already create a code block followed by a list.

> I read that the codeblocks are accessible under the lua filtering; however, would it be possible to modify the parsing done by skylighting?

No, though you can always use your own syntax highlighter via a lua filter (I think there's an example somewhere that uses python's pygments).

**Comment by coatless** [comment]
> Yes. Leaving a literal // <1> in the code block could be a possibility, but if you just want that, you can already create a code block followed by a list.

My thought was to replace `// <1>` or `# <1>` with a circle similar to the asciidoc implementation. Otherwise, as you say, we could do that immediately. 

Though, now that I think of it, callbacks exist through the footnote / url extension. Or am I misunderstanding their representation?

c.f. 

```
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.
``` 

https://pandoc.org/MANUAL.html#footnotes

```
Here is [my link][FOO]

[Foo]: /bar/baz
```

https://pandoc.org/MANUAL.html#reference-links

**Comment by jgm** [comment]
> My thought was to replace `// <1>` or `# <1>` with a circle similar to the asciidoc implementation. Otherwise, as you say, we could do that immediately.

This would require format-specific code; the filter would have to render the code block in the specified format, modify it slightly (adding the circles), and return a RawBlock with that format.

If you do all this, you could add links too presumably.

**Comment by mb21** [comment]
Sounds like a custom filter is the way to go here. For questions, feel free to use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss).
