### ISSUE TITLE
html from url to markdown results in malformed .md file

### ISSUE THREAD

**Issue by Tset-Noitamotua** [jgm/pandoc#5614]
Here is the command to reproduce the issue:

```
pandoc -f html -t markdown \
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html \
-o index.md --extract-media=media

# pandoc version
pandoc --version
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
```
here is example of result

![image](https://user-images.githubusercontent.com/5635462/59980724-15b42180-95fa-11e9-9882-6a62dc69c8f3.png)

Moreover the resulting .md file is broken in a way that it can't be processed by mkdocs:

```
...
WARNING -  Documentation file 'index.md' contains a link to 'h | ttps | le | rg/library/functions.html' which is not found in the documentation files. 
ERROR   -  Error reading page 'index.md': Invalid IPv6 URL
...
```

**Comment by jgm** [comment]
Grid tables encode width information by the relative widths of the cells.  So if your HTML table specifies widths, you can get this kind of result, where the content is too wide to fit in the cells and has to be broken manually.

See https://github.com/jgm/pandoc/issues/4943 which is essentially the same issue.
I'm not sure this issue adds anything, so perhaps it should be closed as a duplicate.

As a workaround, you can increase the column width with `--columns`, which will make all the tables wider.

Or disable grid tables extension, which will give you an HTML table in this case.

**Comment by Tset-Noitamotua** [comment]
Thank you.

Disabling grid tables extension made mkdocs happy but not me. 

```
pandoc -f html -t markdown-grid_tables \
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html \
-o index.md --extract-media=media
```

I will continue to  research how to convert the original source files of Robot Framework user guide which are written in RST (restructuredtext).
