### ISSUE TITLE
Man writer behaves strangely when multiple code spans are used in a definition list

### ISSUE THREAD

**Issue by craigbarnes** [jgm/pandoc#5620]
Example input:

```
`-o`, `--output=`*OUTFILE*
:   Write output to *OUTFILE* instead of `stdout`(3)
```

Command used to compile:

```sh
$ pandoc -s -tman -o output.1 input.md

$ pandoc --version
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
...
```

When the output is viewed with `man ./output.1`, the `-o` code span appears bolded, as expected, but the `--output=` span is just in the regular font.

Raw output:

```
.\" Automatically generated by Pandoc 2.7.2
.\"
.TH "" "" "" "" ""
.hy
.TP
.B \f[C]-o\f[R], \f[C]--output=\f[R]\f[I]OUTFILE\f[R]
Write output to \f[I]OUTFILE\f[R] instead of \f[C]stdout\f[R](3)
```

**Comment by craigbarnes** [comment]
Hmm, I guess I was just added excessive markup to the input. If changed to the following, the output is as desired:

```markdown
`-o`, `--output=`*OUTFILE*
:   Write output to *OUTFILE* instead of `stdout`(3)
```

**Comment by jgm** [comment]
I think this is a real issue; in fact, it affects pandoc's own man page, which uses much the same form as the example above.

It seems that when you have a `.B` at the beginning of a line, the boldface gets reset by the `\f[R]`.
So this is a problem with the way we're rendering definition lists.

**Comment by craigbarnes** [comment]
I think part of the problem was my misconception about what the man writer would turn code spans into. I initially thought they'd be rendered in boldface because the `-o` was, but I see now that's just a side effect of using definition lists and the whole line being affected by the `.B` macro in the output.

The actual result of using code spans seems to be that they're wrapped with `\f[C]...\f[R]`, which the terminal man viewer just renders the same as normal text (thus cancelling the effect of the `.B` macro). If I instead use the input:

```markdown
**-o**, **--output=***OUTFILE*
:   Write output to _OUTFILE_ instead of **stdout**(3)
```

...it does work as expected, although as noted above, the bold spans in the definition are superfluous in the presence of the `.B` macro.

So I guess this isn't so much a bug as just code spans being indistinguishable from normal text when viewed in a terminal.

**Comment by jgm** [comment]
I think it is a real bug, since our intent in adding the `.B` is to boldface the term, but it doesn't actually have this effect in all cases.  (We could easily do better by just doing the thing we normally do to boldface formatted text.)
