### ISSUE TITLE
pandoc.exe 2.0.4: --pdf-engine fails with full path

### ISSUE THREAD

**Issue by tempodox** [jgm/pandoc#5622]
I'm getting an error message when passing a full path to --pdf-engine in pandoc.exe 2.0.4:

> pdf-engine ... not known.

**Comment by mb21** [comment]
try the newest pandoc version

**Comment by JohnScott623** [comment]
@mb21 Would you know which version this was fixed in? The manual has had it since [2.0](https://github.com/jgm/pandoc/blob/2.0/MANUAL.txt#L1021) but the disparity is causing [trouble in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941440#20)
