### ISSUE TITLE
man writer renders bold and verbatim text (e. g. **`--help`**) incorrectly.

### ISSUE THREAD

**Issue by van-de-bugger** [jgm/pandoc#5624]
man writer renders bold _and_ verbatim text (e. g. ``**`--help`**``) incorrectly.

Fedora 30 @ x86_64
pandoc-2.2.1-1.fc30.x86_64 (pandoc 2.2.1; Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.5)
man-db-2.8.4-4.fc30.x86_64
groff-base-1.22.3-19.fc30.x86_64

    $ cat test.md
    NAME
    ====

    test - purpose.

    DESCRIPTION
    ===========

    Use **--help** option to get help.

    Use `--help` option to get help.

    Use **`--help`** option to get help.

    $ pandoc -s --read=markdown --write=man -o test.man test.md

    $ cat test.man
    .\" Automatically generated by Pandoc 2.2.1
    .\"
    .TH "" "" "" "" ""
    .hy
    .SH NAME
    .PP
    test \- purpose.
    .SH DESCRIPTION
    .PP
    Use \f[B]\[en]help\f[] option to get help.
    .PP
    Use \f[C]\-\-help\f[] option to get help.
    .PP
    Use \f[B]\f[BC]\-\-help\f[B]\f[] option to get help.

    $ man ./test.man
    <b>NAME</b>
            test - purpose.

    <b>DESCRIPTION</b>
            Use <b>–help</b> option to get help.

            Use --help option to get help.

            Use <b>--help option to get help.</b>

HTML-like tags `<b>` and `</b>` are not a part of actual `man` output, I used them to denote beginning and end of bold font in actual `man` output.

**Note the last line:** bold font does not stop at the end of `--help`, as expected, but continues until the end of the line. This is the problem.

Also:

    $ man -Thtml ./test.man
    ...
    <p style="margin-left:11%; margin-top: 1em">Use
    <b>&ndash;help</b> option to get help.</p>

    <p style="margin-left:11%; margin-top: 1em">Use
    <tt>&minus;&minus;help</tt> option to get help.</p>

    <p style="margin-left:11%; margin-top: 1em">Use
    <b>&minus;&minus;help option to get help.</b></p>
    ...

I am not very familiar with `groff`, but it seems the last line of `test.man`:

    Use \f[B]\f[BC]\-\-help\f[B]\f[] option to get help.

Should be

    Use \f[B]\f[CB]\-\-help\f[B]\f[R] option to get help.

Note `\f[CB]` (instead of `\f[BC]`) and `\f[R]` (instead of `\f[]`). In such a case man page is formatted properly: **`--help`** is bold and monospace, the rest is not.

The problem is similar to #3568.

**Comment by mb21** [comment]
Can you try in the newest pandoc version please?

**Comment by van-de-bugger** [comment]
I tried to build pandoc with cabal with no success. Fedora 30 has cabal 2.2.0.0 and ghc 8.4.4, so requirements described in "[Installing pandoc](https://github.com/jgm/pandoc/blob/master/INSTALL.md)" are met. However, the build process fails:

    $ cabal update
    Downloading the latest package list from hackage.haskell.org

    $ cabal install pandoc
    Resolving dependencies...
    ...
    Downloading Cabal-2.4.1.0...
    Configuring Cabal-2.4.1.0...
    Building Cabal-2.4.1.0...
    Installed Cabal-2.4.1.0
    Downloading pandoc-1.9.4.3...
    Configuring pandoc-1.9.4.3...
    Failed to install pandoc-1.9.4.3
    Build log ( /home/vdb/.cabal/logs/ghc-8.4.4/pandoc-1.9.4.3-GKcE6LvbU1k55vThF6GVPD.log ):
    cabal: Entering directory '/tmp/cabal-tmp-21907/pandoc-1.9.4.3'
    cabal: Leaving directory '/tmp/cabal-tmp-21907/pandoc-1.9.4.3'
    cabal: Error: some packages failed to install:
    pandoc-1.9.4.3-GKcE6LvbU1k55vThF6GVPD failed during the configure step. The
    exception was:
    dieVerbatim: user error (cabal: '/usr/bin/ghc' exited with an error:

    /tmp/cabal-tmp-21907/pandoc-1.9.4.3/dist/setup/setup.hs:10:33: error:
    Module
    ‘Distribution.Simple.GHC’
    does not export
    ‘ghcPackageDbOptions’
    |
    10 | import Distribution.Simple.GHC (ghcPackageDbOptions)
    | ^^^^^^^^^^^^^^^^^^^

    /tmp/cabal-tmp-21907/pandoc-1.9.4.3/dist/setup/setup.hs:19:1: error:
    Could not find module ‘System.Time’
    Perhaps you meant
    System.CPUTime (from base-4.11.1.0)
    System.Cmd (from process-1.6.5.1)
    System.Mem (from base-4.11.1.0)
    Use -v to see a list of the files searched for.
    |
    19 | import System.Time
    | ^^^^^^^^^^^^^^^^^^

    /tmp/cabal-tmp-21907/pandoc-1.9.4.3/dist/setup/setup.hs:24:1: error:
    Could not find module ‘Data.Default’
    Use -v to see a list of the files searched for.
    |
    24 | import Data.Default
    | ^^^^^^^^^^^^^^^^^^^
    )

It is not clear why cabal downloaded pandoc 1.9.4.3 (the latest release published on github is 2.7.3).

**Comment by van-de-bugger** [comment]
I also tried "Custom cabal method":

    $ tar xaf pandoc-2.7.3.tar.gz

    $ cd pandoc-2.7.3/

    $ cabal update
    Downloading the latest package list from hackage.haskell.org
    To revert to previous state run:
        cabal update --index-state='2019-07-01T18:18:39Z'

    $ cabal install --only-dependencies
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    [__0] trying: pandoc-2.7.3 (user goal)
    [__1] trying: exceptions-0.10.2 (dependency of pandoc)
    [__2] trying: transformers-0.5.6.2/installed-BNI... (dependency of exceptions)
    [__3] next goal: template-haskell (dependency of exceptions)
    [__3] rejecting: template-haskell-2.14.0.0, template-haskell-2.13.0.0 (only
    already installed instances can be used)
    [__3] rejecting: template-haskell-2.12.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base>=4.8 && <4.11)
    [__3] rejecting: template-haskell-2.11.1.0, template-haskell-2.11.0.0
    (conflict: transformers => base==4.11.1.0/installed-4.1..., template-haskell
    => base>=4.7 && <4.10)
    [__3] rejecting: template-haskell-2.10.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base==4.8.*)
    [__3] rejecting: template-haskell-2.9.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base==4.7.*)
    [__3] rejecting: template-haskell-2.8.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base==4.6.*)
    [__3] rejecting: template-haskell-2.7.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base==4.5.*)
    [__3] rejecting: template-haskell-2.6.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base==4.4.*)
    [__3] rejecting: template-haskell-2.5.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base==4.3.*)
    [__3] rejecting: template-haskell-2.4.0.1 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base==4.2.*)
    [__3] rejecting: template-haskell-2.4.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base>=3 && <4.3)
    [__3] rejecting: template-haskell-2.3.0.1, template-haskell-2.3.0.0,
    template-haskell-2.2.0.0 (conflict: transformers =>
    base==4.11.1.0/installed-4.1..., template-haskell => base<4.3)
    After searching the rest of the dependency tree exhaustively, these were the
    goals I've had most trouble fulfilling: template-haskell, base, exceptions,
    transformers, pandoc

**Comment by jgm** [comment]
You can use [try pandoc](<https://pandoc.org/try/?text=Use+**--help**+option+to+get+help.%0A&from=markdown&to=man>) to test with the latest release.

I can't help with cabal issues here.  If you have already installed some things with cabal, the build path can be blocked. I recommend using `cabal new-build`, which will build pandoc in a sandboxed environment, or `stack`.

**Comment by van-de-bugger** [comment]
> You can use try pandoc to test with the latest release.

Sorry for a false alarm. It seems pandoc 2.7.1 works as expected.
