### ISSUE TITLE
GitHub release files with version replaced by "latest"

### ISSUE THREAD

**Issue by hoijui** [jgm/pandoc#5630]
As it is now, there is no way to simply fetch and install the latest version (without knowing the version number).
GitHub allows to reffer to the latest releasae with "latest", but the actual file names therein are with version number, so that alone is not enough. I can think of two possible solutions:

* upload a copy of all the release files (symlinks possible?) called along the lines of "pandic-current-amd64.deb" (same content like "pandic-2.7.3-1-amd64.deb")
* host a simple text file on the pandoc site with the latest release version, for example at pandoc.org/VERSION.txt, containing "2.7.3"

    Then one can do somethign along the line of:

        version=`curl https://pandoc.org/VERSION.txt`
        wget "https://github.com/jgm/pandoc/releases/download/${version}/pandoc-${version}-linux.tar.gz"

And this could the be documented in the release text.

This feautre is quite important, because at least Debian (even testing) comes wiht a very old version of pandoc, and pandoc might be used a lot in static site generation of other documentation, CI generated and pushed to github pages, for example.

**Comment by mb21** [comment]
You can grab the latest version like this:

    version=`curl https://github.com/jgm/pandoc/releases/latest | sed 's/.*\/tag\/\([^"]*\).*/\1/'`

We're doing something similar for the download-latest-version button on the website, but in JavaScript: https://github.com/jgm/pandoc-website/blob/master/js/downloadInstallerBtn.js#L31

**Comment by hoijui** [comment]
ahh perfect! :-)
thank you!

hope others will find this here.

Using [this SO answer](https://stackoverflow.com/a/32340879/586229),
I also came up with this possible solution:

```bash
curl https://api.github.com/repos/jgm/pandoc/releases/latest > release_info.json
# magically parse JSON, extracting the value of 'tarball_url' to a bash variable wiht the same name
curl -o pandoc-latest.tgz "$tarball_url"
```

I preffer your solution though, for its simplicify, and more control: what if the tarbal is not for my arch?

**Comment by mb21** [comment]
yes, in the js version we parse the json as well...

I guess these work-arounds are good enough for now.
