### ISSUE TITLE
Huge slowdown in converting Markdown to HTML in Pandoc 2.2

### ISSUE THREAD

**Issue by Godsmith** [jgm/pandoc#5631]
Using the precompiled Linux binaries and the Markdown file in this archive: [slow.zip](https://github.com/jgm/pandoc/files/3362576/slow.zip)

```
$ time pandoc-2.1/bin/pandoc slow.md 
[...]
0.960u 0.059s 0:01.03 98.0%	0+0k 0+0io 0pf+0w
$ time pandoc-2.2/bin/pandoc slow.md 
[...]
26.836u 3.240s 0:30.09 99.9%	0+0k 0+0io 0pf+0w
```

The slowdown persists in the latest version 2.7.3:

```
$ time pandoc-2.7.3/bin/pandoc slow.md   
[...]
28.718u 4.113s 0:32.81 100.0%	0+0k 0+0io 0pf+0w
```

The generated HTML files are very similar though, just differing in some table column widths.

Any idea what caused this? Sadly, it makes pandoc 2.2+ unusable for my use case, which is previewing Markdown documents in the Markdown plugin in Eclipse.

**Comment by mb21** [comment]
Would be great to have a minimal input example... and also to know exactly which version introduced this.

**Comment by jgm** [comment]
Thanks for this.  Using --trace reveals that the problem arises at this line:

```
## [aaaaaaa\] aaaa-aaaaaaaa aaa aaa aaa (a11/a1-a, a4, a5 aaa aa), aaaa
```
and again at a similar line (1388).
```
## [aaaaaaaaaa\]: aaaaaaaa aaa aaa aaa (a11/a5), aaaa
```
Adding an backslash escape to the `[` seems to make a difference.

**Comment by jgm** [comment]
Minimal case:
```
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
## [a\]: aaaaaaaa
```
This takes over 5 seconds to convert using my old laptop and pandoc 2.7.3 release binary on macOS.

**Comment by jgm** [comment]
In pandoc, reference link definitions can occur in arbitrary contexts, including headers.
So I think what's happening here is that we're trying to parse this as a link reference definition.
These can extend over lines, so we get exponential backtracking.  We don't get the problem with `-f commonmark`, because commonmark will close the heading block on the next line.

**Comment by jgm** [comment]
@Godsmith seemed to indicate that 2.1 was fast but 2.2 was slow.
I'm not finding this when I test with the sample above.  Indeed, 2.1.1 is about the same as 2.7.3, but 2.1 is incredibly slow -- still hasn't terminated at all on the same input.

**Comment by Godsmith** [comment]
Fantastic! It turns out a lot of lines had that issue. After running the file through

```
sed 's/# \[/# \\\[/g' slow.md > slow_fixed.md
```

I get a major improvement:

```
time pandoc-2.1/bin/pandoc slow_fixed.md
0.911u 0.066s 0:00.99 97.9%	0+0k 0+0io 0pf+0w
time pandoc-2.2/bin/pandoc slow_fixed.md
1.412u 0.155s 0:01.58 98.7%	0+0k 0+0io 0pf+0w
```

Still slightly slower, but it works great for my use case.

Thank you so much!

**Comment by Godsmith** [comment]
@jgm Hmm, I used the pandoc from here: https://github.com/jgm/pandoc/releases/tag/2.1, file pandoc-2.1-linux.tar.gz. Not sure why it's not the same for you.

**Comment by jgm** [comment]
Actually, the part about reference link definitions is wrong. Pandoc doesn't allow them inside ATX headers.

**Comment by jgm** [comment]
We could fix this by disallowing this "spillover," but this would change behavior.  I wonder if anyone is relying on the current spillover-allowing behavior?

**Comment by jgm** [comment]
The underlying issue here is #1735.  Even if we changed ATX headings so that nested inline parsing can't continue onto the next line, we could get similar slowdowns in regular paragraphs.  Thus, I don't think this really raises a new issue, and we can close this given that we have #1735.

**Comment by Godsmith** [comment]
Just for completeness, I fixed one remaining unmatched bracket, and now the processing time for 2.2 is below that for 2.1.

`0.886u 0.066s 0:00.96 97.9%	0+0k 0+0io 0pf+0w`

Your quick answer is very much appreciated!
