### ISSUE TITLE
@misc bibtex items cause invalid JATS output

### ISSUE THREAD

**Issue by arfon** [jgm/pandoc#5634]
I'm trying to produce JATS XML using from Markdown source and validating the output using the the [Pubmed central validator](https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker)

## The problem

If the reference metadata (bibtex in this case) includes a `@misc` item, which is citing a GitHub repository then the the output JATS XML is not well-formed. Included in the zip file here is a minimal example that demonstrates the issue

This results in the following error:

```
37:    GitHub</publisher-name></element-citation></ref>
>                           ^
>  Element publisher-name was declared #PCDATA but contains non text nodes
38:  </ref-list>
```

Apologies for not fixing this with a pull request - I'm struggling with the `jats.csl` template and couldn't remedy locally.

## Steps to reproduce

**Pandoc version**

2.7.3

**Files**

Minimal example files demonstrating the problem: [jats-example-files.zip](https://github.com/jgm/pandoc/files/3363795/jats-example-files.zip)

Note the `jats.csl` file here is the same in `master`.

**Commands**

1. `pandoc -s --metadata-file metadata.json --bibliography references.bib --filter pandoc-citeproc  --to jats example.md -o output.xml`
2. Validate the output using the [Pubmed central validator](https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker)
3. XML returns the error above.

**Also**

Note, if I updated the DTD to v1.1 (as in #5632) then I get the following error with the validator and [this file](https://github.com/jgm/pandoc/files/3363800/output.xml.zip)

```
37:    GitHub</publisher-name></element-citation></ref>
>                           ^
>  Element ext-link is not declared in publisher-name list of possible children
```

**Comment by jgm** [comment]
Can you post the XML pandoc produces that fails the validation?  (The whole reference.)

**Comment by arfon** [comment]
Sure thing. It's `output.xml` in the zipped files above. I've also posted it in this Gist: https://gist.github.com/arfon/879173bb710e94ed0e8301b7e42473b9

**Comment by jgm** [comment]
>  Element ext-link is not declared in publisher-name list of possible children

Strange. At https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/publisher-name.html it seems to say that ext-link IS a valid child of publisher-name. Same for 1.2: https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/publisher-name.html

**Comment by arfon** [comment]
So it turns out that this is because the current DTD for the [JATS writer template](https://github.com/jgm/pandoc/blob/6c435a17cd48af40dbf87ebbec8baf6ac6aabe27/data/templates/default.jats#L5) is for Journal Publishing (`JATS-journalpublishing1.dtd`), which does not permit `ext-link` as a valid child (https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/publisher-name.html).

In https://github.com/jgm/pandoc/issues/5634#issuecomment-513491155 @jgm, you're linking to the _archiving_ DTD which _does_ permit `ext-link` as a child element.

Talking with @jeffbeckncbi, he suggested that we should switch to the more flexible JATS archiving and interchange DTD which systems like PubMed use internally to represent their articles. 

@jgm - if this sounds reasonable, I'll open a pull request to update the `default.jats` to switch out the DTD to the following:

```
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2d1 20190208//EN" "JATS-archivearticle1.dtd">
```

(Note, I updated the DTD in the [`output.xml`](https://gist.github.com/arfon/879173bb710e94ed0e8301b7e42473b9/revisions) linked to above and can confirm that the Pubmed central validator no-longer reports errors).

**Comment by jgm** [comment]
I don't know much about JATS.  So I'll have to defer to what JATS experts/users say is best here.

**Comment by jgm** [comment]
It would probably make sense to post on pandoc-discuss to see if anyone would have objections to the DTD change

**Comment by arfon** [comment]
> It would probably make sense to post on pandoc-discuss to see if anyone would have objections to the DTD change

@jeffbeckncbi is about as close as it gets to a world expert on these topics and he seemed to think this would be a reasonable change.

That said, it would still probably be a good idea to get some broader feedback from the community though so I'm happy to post something.

**Comment by jgm** [comment]
Good, why don't you post something; but if nobody replies, we'll assume it's okay.
