### ISSUE TITLE
LaTeX \providecommand wrongly interpreted

### ISSUE THREAD

**Issue by qogn9daohs1** [jgm/pandoc#5635]
`\providecommand` statements in latex inputs are not translated correctly by pandoc. When a latex file contains multiple, identical assignments with `\providecommand` only the first one is interpreted. Pandoc seems to interpret all of them.

Given this document
```latex
\documentclass{article}
\providecommand{\test}{foo}
\providecommand{\test}{bar}

\begin{document}
The value is: \test
\end{document}
```
latex produces a document stating: `The value is: foo`

However, given the same document to pandoc results in: `The value is: bar`

My pandoc version is 2.7.2

**Comment by jgm** [comment]
Currently we treat providecommand just like newcommand. This can be changed.
