### ISSUE TITLE
"--no-check-certificate" option, or equivalent

### ISSUE THREAD

**Issue by phlummox** [jgm/pandoc#5636]
It's sometimes useful to fetch content from a TLS-enabled website, despite the fact it has an invalid certificate. When using a standalone HTTP client like `curl` or `wget`, there are options for disabling the certificate check (using `--insecure` and `--no-check-certificate`, respectively), but Pandoc has no such option.

I'd suggest it would be a useful enhancement would be to add such an option. Besides the option-parsing code, this would require only a couple of lines additional code in src/Text/Pandoc/Class.hs: instead of `tlsManagerSettings` being used as the settings for `Network.HTTP.Client.TLS`, when the option was enabled, code like:

```
mkManagerSettings (def  { settingDisableCertificateValidation = True }) Nothing
```
would be used instead.

Alternatively, if that's considered out of scope, it might be useful to improve the error-reporting when a TLS-related exception is thrown, suggesting to the user that they use `curl` or `wget` instead. Currently, understanding the exceptions requires some knowledge of how TLS works -- 

```
$ pandoc -f html https://self-signed.badssl.com/
Could not fetch https://self-signed.badssl.com/
HttpExceptionRequest Request {
  host                 = "self-signed.badssl.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: [SelfSigned]",True,CertificateUnknown))))
```
which users who simply want to use Pandoc to convert website content might not be familiar with.

**Comment by mb21** [comment]
We already have the `--request-header` option, so this wouldn't be something completely new. That being said, in such a case you could also use `curl` or `wget` to download the required things and then use pandoc locally...

**Comment by phlummox** [comment]
Of course. My own current workaround is to use curl and convert locally. Since I mentioned the tools, and the relevant options, it's reasonable to assume I know how to use them, and have a perfectly good workaround; otherwise, I'd probably be reporting this as a bug, I suppose, instead of suggesting an enhancement, mentioning the alternative tools, and pointing out specific bits of code that would need to be amended. I suggested the enhancement not because *I* don't know how to solve this problem, but because it seemed to me that there are many non-programmer users of Pandoc who wouldn't, and that this might make Pandoc more useful to them.

Hence my further suggestion was that if this is *out* of scope for Pandoc, it could be useful instead to improve the error reporting for TLS-related exceptions. A non-programmer is unlikely to be able to make much sense of the raw exception being printed out, which is what currently happens; a suggestion, in the error message, that the end-user try `wget` or `curl` and converting locally might be useful.

**Comment by jgm** [comment]
I'm open to `--no-check-certificate`, I guess.
Another option would be try first with the default (checking) mode, and if that fails, issue a warning and repeat the download without certification validation.  That would be more automatic and would not require an additional option.

**Comment by agusmba** [comment]
> Another option would be try first with the default (checking) mode, and if that fails, issue a warning and repeat the download without certification validation. That would be more automatic and would not require an additional option.

Even though in many cases this would help users, I wouldn't do this. The checking fails for a reason and it should be up to the user to understand the implications of skipping such checking by making them explicitly request it. Doing this in an automatic way could open pandoc users to unwanted risks (MitM attacks, etc.)

**Comment by mb21** [comment]
@phlummox would you like to submit a pull request?
