### ISSUE TITLE
filter application during markdown to markdown conversion

### ISSUE THREAD

**Issue by ttxtea** [jgm/pandoc#5651]
When using `pandoc` to convert from markdown to markdown filters like (citeproc, fignos, ...) are not executed. For example

~~~
pandoc -t markdown --bibliography my.bib -F pandoc-fignos text.md
~~~

will not substitute reference or apply the fignos as it would for example be the case when using `-t plain`. I would like to suggest that this may not be the intended behaviour. If you do not whant to apply the filters you would not include them in the pandoc command. You may want to apply them if you intend to further process `pandoc`'s output to `pandiff` of `pancritic`.

**Comment by alerque** [comment]
I just did something like this yesterday using Pandoc 2.7.3 to convert Markdown+CSV to Markdown tables using `-F pantable`. What version are you using?

**Comment by ttxtea** [comment]
I am also using pandoc 2.7.3

**Comment by ttxtea** [comment]
Thanks!!! That is interesting, my output is

~~~
~$ echo '```table\nfoo,bar,baz\n```' | pandoc -t markdown -F pantable
`table\nfoo,bar,baz\n`
~~~

**Comment by ttxtea** [comment]
I've tested it with

1. pandoc 2.7.3 on Ubuntu Disco Dingo
2. pandoc 2.2.2 on Debian 9 stretch

in both cases I get the above string. I think you output is much more meaningfull. I both cases I did not wittingly alter any of the default settings of pandoc.

**Comment by alerque** [comment]
Hmm, the difference in your test is actually that you are using Bash as your `$SHELL` and I'm using ZSH which allowed me to include the escapes that way. On Bash you will need to run this to test:

```sh
$ echo -e '```table\nfoo,bar,baz\n```' | pandoc -t markdown -F pantable
```

If you have more troubles with the shell echo that just back to you and make sure you get this as the starting value alternatively you can stick this in a markdown file and use it instead with `pandoc -i file.md`:

    ```table
    foo,bar,baz
    ```

**Comment by ttxtea** [comment]
Cool I learn quite a bit about shell subtleties here :). Now it work and I also get the table output.

Tried to make a minimal example for `pandoc-citeproc`:

~~~
echo -e '---\nreferences:\n- id: foo\n  author: bar\n...\n\n[@foo]' | pandoc -t markdown -F pandoc-citeproc
~~~

In my case the output is however still

~~~
[@foo]
~~~

**Comment by alerque** [comment]
With citeproc and your tests I get the same results you do. But now I have to wonder if your expectation of the the filter might be wrong. I'm not actually that familiar with it, but it looks like it's outputting valid Markdown that _shouldn't_ be anything other than what it is.

If you are looking for a way to expand the citations in Markdown, I think you'd need to remove that extension from your output format (it seems to be enabled by deflaut:

```sh
echo -e '---\nreferences:\n- id: foo\n  author: bar\n...\n\n[@foo]' | pandoc -t markdown-citations -F pandoc-citeproc
```

For which I get:

```markdown
(n.d.)

::: {#refs .references}
::: {#ref-foo}
n.d.
:::
:::
```

**Comment by ttxtea** [comment]
Thank you that helped me a lot. Indeed, I can completely corroborate your results using `markdown-citations`. I could not find any mentioning of `markdown-citations` in the man-page or on [pandoc's webpage](www.pandoc.org). I was wondering if it is helpful for others to mention this in the documentation?

**Comment by alerque** [comment]
The extension is document [in the manual here](https://pandoc.org/MANUAL.html#citations). It works the same as other format/syntax extensions that you can add (`+citations`) or remove (`-citations`) from any base format that supports them.
