### ISSUE TITLE
Inline Listing gets lost when converting from pandoc generated LaTeX

### ISSUE THREAD

**Issue by waschk** [jgm/pandoc#5659]
When converting a Markdown text containing inline code to LaTeX with --listings and back to Markdown, the code gets lost:
```
> echo test is `working` fine | pandoc -f markdown -t latex --listings | pandoc -f latex -t markdown --listings
test is fine
```

Without the listings argument it is working as expected:
```
> echo test is `working` fine | pandoc -f markdown -t latex | pandoc -f latex -t markdown
test is `working` fine
```

Tested on Windows 10 with stable 2.7.3 and nightly db5f6dd4f:
```
> pandoc --version
pandoc 2.7.4
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.2
```

**Comment by jgm** [comment]
It works if you use `-s` in the writer, which will include the definition of `\passthrough`, used in rendering the listing.

**Comment by jgm** [comment]
I'll change the latex reader to ignore the passthrough macro.
