### ISSUE TITLE
Conversion fails on Windows when image path includes hash (#)

### ISSUE THREAD

**Issue by AB-Kent** [jgm/pandoc#5664]
When the path to an included image includes a #, converting with `--self-contained` fails. For example, given this directory:
```
C:\> dir /b temp#
sample.png
test1.md
```

where `test1.md` contains this, and `sample.png` is any PNG file:
```
---
title: Test
...

![](C:/temp#/sample.png)<!-- -->
```

Then pandoc fails with a Permission denied error.
```
C:\> pandoc "C:/temp#/test1.md" -f markdown -t html -o C:/temp#/test1.html --self-contained
pandoc: C:/temp: openBinaryFile: permission denied (Permission denied)
```

If I remove the `#` from the image path in `test1.md` and copy `sample.png` to `C:/temp` the conversion works as expected.

If I convert without `--self-contained` the conversion completes without error but the image path is incorrect; in this example the converted file contains
```
<p><img src="C:/temp#/sample.png" /><!-- --></p>
```
The correct `src` is `C:/temp%23/sample.png`.

This is with pandoc 2.7.3 on Windows 10.

**Comment by mb21** [comment]
The link in markdown is a URL. Thus the part following the `#` is treated as a fragment, see https://en.wikipedia.org/wiki/URL#Syntax

Can you try percent-encoding it:

    ![](C:/temp%23/sample.png)

**Comment by AB-Kent** [comment]
Yes, that works, thanks for the quick response! I'll have to bug the creator of the markdown document.
