### ISSUE TITLE
Some emojis aren't showing up

### ISSUE THREAD

**Issue by luispuerto** [jgm/pandoc#5666]
Hey! 

Some emojis aren't showing up in my install. I don't know if I'm missing something, there is a bug or it's like this. It isn't because they are new emojis or something because github markdown produces the emoji perfectly. 

```
$ echo 'hi :smile: :one: :slightly_smiling_face:' | pandoc -f gfm
```

produces: 

<img width="699" alt="Screen Shot 2019-07-26 at 14 17 12" src="https://user-images.githubusercontent.com/22882880/62066358-f48cb500-b1e5-11e9-8875-1df96ba346ad.png">

`:slightly_smiling_face:` should produce: 🙂 

My version of Pandoc is: 

```
andoc -v
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: /Users/lpuerto/.local/share/pandoc or /Users/lpuerto/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Installed through Homebrew.

**Comment by jgm** [comment]
Here's the module that defines the supported emojis:
https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Emoji.hs
Looks like `slightly_smiling_face` isn't supported.  Can we find an accurate, up-to-date list of emoji characters supported by GitHub?  (Side note: it would be good to split out this module as an independent package that can be used by other Haskell libraries.)

**Comment by luispuerto** [comment]
Quite interesting that one isn't supported… it's been a regular emoji since the 2014 when they approved unicode 7. 

https://emojipedia.org/slightly-smiling-face/

**Comment by jgm** [comment]
If it's not supported by GitHub (let's try, :slightly_smiling_face:) then this can be closed.

**Comment by jgm** [comment]
Hm, it *is* supported, it seems!

**Comment by jgm** [comment]
@kivikakk Is there an official list somewhere of the emoji GitHub supports?  I couldn't find this anywhere.  (I found several unofficial lists, which don't seem to be quite accurate.)

**Comment by luispuerto** [comment]
Yes it's here. 

https://github.com/github/gemoji/blob/master/db/emoji.json

They seems to be using gemoji gem https://github.com/github/gemoji

**Comment by luispuerto** [comment]
perhaps this is useful too! http://unicode.org/Public/emoji/12.0/emoji-test.txt

**Comment by luispuerto** [comment]
now it's working!! 

Thanks!

**Comment by luispuerto** [comment]
A stupid addiction… perhaps we can add 

`:octocat:` :octocat: 

😛

**Comment by jgm** [comment]
`:octocat:` doesn't have a unicode character, so (if I understand correctly) GitHub inserts a special image. We can't really do that in pandoc.

**Comment by luispuerto** [comment]
a pity! it's fun!  but I understand
