### ISSUE TITLE
Blank line in markdown display math

### ISSUE THREAD

**Issue by silencial** [jgm/pandoc#5669]
Inserting a blank line in display math will cause the equation not rendered correctly.

Example:
```
$$
1 = 1 \\
2 = 2
$$
```
will be rendered correctly as
![image](https://user-images.githubusercontent.com/26143109/62328930-4f820e80-b469-11e9-90f2-b01c8ae45f14.png)

But
```
$$
1 = 1 \\

2 = 2
$$
```
will be rendered as
![image](https://user-images.githubusercontent.com/26143109/62329098-c7e8cf80-b469-11e9-8603-e63eccbb39b4.png)

I am using pandoc with mathjax to parse mardown to html. This seems more like a parsing rule rather than a bug. But when writing markdown with typora, adding a blank line in display math environment does not cause any problem. Is there any way to keep the blank line in markdown but still make pandoc render correctly?

**Comment by agusmba** [comment]
What version of pandoc are you using?

I don't see the extra `\` in your second approach if I go to native:

```
$ pandoc -f markdown -t native << EOF
$$
1 = 1 \\

2 = 2
$$
EOF
``` 
yields:
```
[Para [Str "679",SoftBreak,Str "1",Space,Str "=",Space,Str "1",LineBreak]
,Para [Str "2",Space,Str "=",Space,Str "2",SoftBreak,Str "679"]]
```

**Comment by silencial** [comment]
I am using pandoc 2.7.2

By the way, I am using hexo to parse my markdown to html with hexo-renderer-pandoc plugin when this error happens.

I tried your method in the command line and here is output:
```
$ pandoc -f mardown -t native
$$
1 = 1 \\

2 = 2
$$
```
yields:
```
[Para [Str "$$",SoftBreak,Str "1",Space,Str "=",Space,Str "1",Space,Str "\\"]
,Para [Str "2",Space,Str "=",Space,Str "2",SoftBreak,Str "$$"]]
```

**Comment by agusmba** [comment]
yeah, nevermind my previous test, my terminal was messing up with the `$`s.

It seems if there is a paragraph break, pandoc won't detect displaymath (not sure if it's a bug or a feature)

**Comment by silencial** [comment]
This seems to be a feature since latex does't allow paragraph break in math mode either.

**Comment by mb21** [comment]
So this issue can be closed I guess?
