### ISSUE TITLE
Markdown math syntax: allow space around dollars signs

### ISSUE THREAD

**Issue by ashwinvis** [jgm/pandoc#5672]
This is similar to #47, but for inline math with single `$` sign
```
❯ pandoc --version
pandoc 2.7.3
```

## Input
```
$ x + y = z $
```
Command
```
❯ pandoc test.md -o test.tex
```

## Expected results
```tex
\( x + y = z \)
```

## What happens
```tex
\$ x + y = z \$
```

I understand parsing `$` is difficult because of issues like #1127. Can we enforce parsing $ as math with an option like `markdown+tex_math_dollars`, with which to get $ you would have to explicitly escape it `\$`?

**Comment by mb21** [comment]
This would increase the chances of writing something that would mistakenly be recognized as a math environment significantly. What's the upside?

You could also write a pandoc-filter that does this transformation if you absolutely need it for some weird input. Note that also MultiMarkdown behaves the same way as pandoc currently.
