### ISSUE TITLE
JIRA: Escaping characters inside code blocks

### ISSUE THREAD

**Issue by jkroepke** [jgm/pandoc#5674]
Hi,

i'm start using pandoc to generator confluence pages from markdown since the jira writer perfectly match the legacy wiki format language in confluence.

Since some character enconding is hardcoded on the writer
https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Jira.hs#L67-L89
somethink like

````
```
2019-07-24 16:24:37 +0200 | 6c88507 | Start next iteration with 0.47.0-SNAPSHOT
2019-07-24 16:23:37 +0200 | beb3160 | Adding right favicons and manifest files and deleting unnecessary
```
````

will result into

```
{code}
2019&hyphen;07&hyphen;24 16:24:37 &plus;0200 &vert; 6c88507 &vert; Start next iteration with 0.47.0&hyphen;SNAPSHOT
2019&hyphen;07&hyphen;24 16:23:37 &plus;0200 &vert; beb3160 &vert; Adding right favicons and manifest files and deleting unnecessary
{code}
```

Since there is no html entity encoding inside code blocks, users just the the raw html entities on the page.

**Comment by jkroepke** [comment]
https://github.com/jgm/pandoc/blob/ea3a779f7baf2a2d7cb2105f3b453c7968c17ab8/src/Text/Pandoc/Writers/Jira.hs#L147

Removing the escape function here may should resolve this issue

**Comment by tarleb** [comment]
Thank you for the report, that code is indeed very wrong. We should still escape stray `{code}`, but that's about it.

If you'd like, you could do a PR for this – otherwise I'm going to fix it at the end of this week.

**Comment by jkroepke** [comment]
I'll try it!

**Comment by tarleb** [comment]
According to my experiments and to the [Jira community](https://community.atlassian.com/t5/Confluence-questions/How-can-I-escape-curly-braces-within-code-tags/qaq-p/29147) there is actually no way to escape curly braces. I guess just deleting the escape function is all that's needed.

**Comment by jkroepke** [comment]
> I guess there is no better way than just deleting the escape function.

For jira maybe.

If some has the ability to write a confluence writer he should use the confluence XHTML reference instead the crappy jira markup language.

> I guess there is no better way than just deleting the escape function.

I could delete the function from the line 147. But i'm not familiar with haskel. Do we need tests for this case?

**Comment by tarleb** [comment]
Writers are tests (at the very least) by comparing output generated from a default document to a golden file. It's a good idea to put the new output into a jira/confluence and do a visual check to make sure nothing looks weird. Then just replace the old file with the updated output:

    stack exec pandoc -- -r native -w jira --columns=78 -s tests/testsuite.native -o writer.jira

**Comment by jkroepke** [comment]
Could you do it please?

I don't want to setup an haskel environment on my local machine for a one time scenario. I tried it compile pandoc inside [haskell](https://hub.docker.com/_/haskell) but i'm running out of memory inside the docker vm.

Otherwise I can just create an PR without compile pandoc locally but tests should fail.
