### ISSUE TITLE
Feature Request: Generate table of contents (not standalone)

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#5675]
The `--toc` option states:

> This option has no effect unless -s/--standalone is used, and it has no effect on man, docbook4, docbook5, or jats output.

Consider a file named `test.md` with the following contents:

```
# Heading 1

Content 1

## Subheading 1

Subheading 1

### Subsubheading 1

Subsubheading 1

## Subheading 2

Subheading 2

# Heading 2

Heading 2
```

Generate an HTML document using `pandoc test.md`:

``` html
<h1 id="heading-1">Heading 1</h1>
<p>Content 1</p>
<h2 id="subheading-1">Subheading 1</h2>
<p>Subheading 1</p>
<h3 id="subsubheading-1">Subsubheading 1</h3>
<p>Subsubheading 1</p>
<h2 id="subheading-2">Subheading 2</h2>
<p>Subheading 2</p>
<h1 id="heading-2">Heading 2</h1>
<p>Heading 2</p>
```

It would be convenient to generate the table of contents either as part of the document or as a document by itself. Using `pandoc --toc test.md` would produce:

``` html
<nav id="TOC" role="doc-toc">
<ul>
<li><a href="#heading-1">Heading 1</a><ul>
<li><a href="#subheading-1">Subheading 1</a><ul>
<li><a href="#subsubheading-1">Subsubheading 1</a></li>
</ul></li>
<li><a href="#subheading-2">Subheading 2</a></li>
</ul></li>
<li><a href="#heading-2">Heading 2</a></li>
</ul>
</nav>
<h1 id="heading-1">Heading 1</h1>
<p>Content 1</p>
<h2 id="subheading-1">Subheading 1</h2>
<p>Subheading 1</p>
<h3 id="subsubheading-1">Subsubheading 1</h3>
<p>Subsubheading 1</p>
<h2 id="subheading-2">Subheading 2</h2>
<p>Subheading 2</p>
<h1 id="heading-2">Heading 2</h1>
<p>Heading 2</p>
```

Running `pandoc --toc-only test.md` would produce:

```
<nav id="TOC" role="doc-toc">
<ul>
<li><a href="#heading-1">Heading 1</a><ul>
<li><a href="#subheading-1">Subheading 1</a><ul>
<li><a href="#subsubheading-1">Subsubheading 1</a></li>
</ul></li>
<li><a href="#subheading-2">Subheading 2</a></li>
</ul></li>
<li><a href="#heading-2">Heading 2</a></li>
</ul>
</nav>
```

This is in addition to running `pandoc -s --toc test.md`, which needs to be post-processed if the table of contents is to be extracted from the standalone document.

**Work Around**

A quick work around is to use `xmllint`, such as:

``` bash
pandoc -s --toc test.md 2> /dev/null | \
xmllint --html --xpath "//html/body/nav" - 2> /dev/null > toc.html
```

**Comment by jgm** [comment]
You can already do this with a custom template.  For example, try using this template:

```
<nav id="$idprefix$TOC" role="doc-toc">
$table-of-contents$
</nav>
```

**Comment by sucrecacao** [comment]
This is not

> You can already do this with a custom template. For example, try using this template (save this as `toc-only.html5` and invoke with `pandoc --toc --template toc-only`):
> 
> ```
> <nav id="$idprefix$TOC" role="doc-toc">
> $table-of-contents$
> </nav>
> ```

This is not working for me.  I got the following error:
```
pandoc \
	--toc \
	--template toconly.html5 \
	-s \
 		-o ./toc.pdf "./FINAL.md" && okular toc.pdf

Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 <

make: *** [Makefile:8: toc.pdf] Error 43
```

**Comment by sucrecacao** [comment]
Same error if I remove the `-s`

**Comment by jgm** [comment]
Add `-t html5` or pandoc will create the PDF via a latex intermediate, for which your template is inappropriate.
