### ISSUE TITLE
Feature Request: TOC Stop Depth and Start Depth

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#5676]
Pandoc supports `--toc-depth=NUMBER` to limit the number of sections included in the table of contents. As a variation, consider:

    --toc-depth-start=2
    --toc-depth-stop=4

This would include heading levels 2 through 4 in the table of contents, inclusive, omitting heading levels 1 and 5 and up. This suggests that `--toc-depth` can be aliased to `--toc-depth-stop` and the default value for `--toc-depth-start` would be 1.

**Comment by jgm** [comment]
Why would you want to include heading levels 2-4 but not 1?

**Comment by DaveJarvis** [comment]
I have a [blog series](https://dave.autonoma.ca/blog/2019/05/22/typesetting-markdown-part-1/) where the H1 is the top title and H2/H3 are subtitles. The menu at the top of the blog extracts heading levels 2 through 3 because H1 isn't part of the "contents" per se.

![typesetting-md](https://user-images.githubusercontent.com/2131950/62748102-3569a280-ba0c-11e9-8cb8-77fc001919d8.png)

**Comment by jgm** [comment]
Pandoc really wants you to use the `title` in metadata for the title (this will create a level 1 heading on the page, but also help populate the title tag).  Then your top-level headings can be level 1.

You could write a fairly simple lua filter to match on a level 1 header, populate the title in metadata with its contents, and remove it, while demoting other headers by 1 level.

**Comment by jgm** [comment]
See also #5615, which I think is a cleaner solution than making TOC start depth configurable.

**Comment by DaveJarvis** [comment]
> but also help populate the title tag

That is a useful default. In this use case, I'm using fmpp (a FreeMarker template engine preprocessor) to generate the document template:

``` html
<#ftl encoding="UTF-8">
<#assign updated = .now>
<!doctype html>
<html lang="en">
<head>
  <title>Markdown Typesetting with Pandoc and ConTeXt Blog Series</title>
  <style>
    <#include "includes/css/main.min.css">

    <#if resource?starts_with( "blog" )>
    <!-- ... -->
    <#if>
</head>
<!-- ... body, main, and other elements ... -->
      <#include "includes/html/body.html" parse=false encoding="UTF-8">
<!-- ... article, footer, and end of body/html ... -->
```

And have a function, loops over "index.md" files, to convert Markdown into HTML:

``` bash
convert_markdown() {
  local -r FILE_HTML="$INC_DIR/html/body.html"
  local -r FILE_TOC="$INC_DIR/html/toc.html"
  local -r XPATH="//html/body/nav/ul/*/ul"

  if [[ "${PWD}" == *blog* ]]; then
    echo "<nav class='toc'>" > "${FILE_TOC}"
    pandoc -s --toc "$1" 2> /dev/null | \
      xmllint --html --xpath "${XPATH}" - 2> /dev/null >> "${FILE_TOC}"
    echo "</nav" >> "${FILE_TOC}"
  fi

  pandoc "$1" \
    -f markdown-tex_math_dollars-raw_tex-auto_identifiers+auto_identifiers \
    -o "$FILE_HTML"
}
```

There's little functional difference between the echo statements above and the suggestion in #5675 to externalize the TOC to a file. In both cases users still must code `<nav>` elements somewhere, which slightly duplicates pandoc's existing ability to generate `<nav>` elements. The combination of `--toc` and `--toc-depth-start` would simplify the `convert_markdown` function to a single pandoc call with no external dependencies, such as:

``` bash
convert_markdown() {
  local -r FILE_HTML="$INC_DIR/html/body.html"

  pandoc "$1" \
    --toc --toc-depth-start=2 \
    -f markdown-tex_math_dollars-raw_tex-auto_identifiers+auto_identifiers \
    -o "$FILE_HTML"
}
```

This would also eliminate the warning that a page title is needed because standalone mode would no longer be necessary (to generate the TOC, external template notwithstanding).

**Comment by jgm** [comment]
Using a custom template to generate the TOC (as I suggested in the other issue) would be cleaner than what you're doing.  And using a lua filter as suggested above would be cleaner than using xmllint.  This would also give you "no external dependencies", since you don't need to have a lua interpreter to use lua filters.

Anyway, I don't like to multiply our already plentiful command-line options without strong reasons, and in this case I don't see a strong reason other than what might be handled by #5615.
