### ISSUE TITLE
internal links and footnotes

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#5677]
With the following [sample](https://pandoc.org/try/?text=As+explained+in+%5BMain+Title%5E%5BWith+footnote.%5D%5D...%0A%0A%23%23+Main+Title%5E%5BWith+footnote.%5D%0A%0AExplanation&from=markdown&to=):

``` md
As explained in [Main Title^[With footnote.]]...

## Main Title^[With footnote.]

Explanation
```

I get two footnotes, which isn’t intended and it cannot be avoided.

Would it be possible that footnotes may not be required in internal link references?

If this were no possible, could footnotes be removed from the referenced title?

Many thanks for your help.

**Comment by jgm** [comment]
For this case, just don't use the implicit header links feature.
Define an explicit anchor and use it.
