### ISSUE TITLE
backslash inside url rendered as forward slash label:bug label:format:LaTeX

### ISSUE THREAD

**Issue by whrose** [jgm/pandoc#5680]
Using pandoc 2.7.3., the `markdown` string `<https://duck.com/?q=\site:pandoc.org+help>`

  * processed through `-t latex --pdf-engine=xelatex` results in **<https://duck.com/?q=/site:pandoc.org+help>** (note that the backslash — after ‘?q=’ has become a forward slash).

  * processed through `-t odt` provides the correct url: **<https://duck.com/?q=\site:pandoc.org+help>**

	(FYI: the backslash in the duckduckgo query syntax is the equivalent of the google “Feeling Lucky” function \[btnI=I], which means clicking the link brings the user straight to the top hit resulting from the search query — click on each of the links above to see the difference).

Writing the string between backticks makes the url unclickable.

Am I right to think this is a bug?

**Comment by Wandmalfarbe** [comment]
The backslash is not allowed in a URL and sometimes automatically replaced with a forward slash:
- <https://bugs.chromium.org/p/chromium/issues/detail?id=25916>
- <https://bugzilla.mozilla.org/show_bug.cgi?id=64488>

You should use the URL encoded form of the backslash which is `%5C`. So passing in `<https://duck.com/?q=%5Csite:pandoc.org+help>` as Markdown results in the desired LaTeX output.
