### ISSUE TITLE
newcommand bug with optional arguments

### ISSUE THREAD

**Issue by umutacar** [jgm/pandoc#5682]
When translating LaTeX to html, pandoc doesn't seems to handle newcommand with optional arguments.  Opening this bug report on the advice of @jgm 

Example: consider the definition
```
\newcommand{\ittakestwo}[2][defaultone]{#2}
```
The following should eval to "tango" but it doesn't.
```
\ittakestwo[to]{tango} 
```

**Comment by alerque** [comment]
I think something is missing from your example. As it stands I don't see how it could be expected to evaluate the way you suggest. Can you expand the LaTeX side of things to be a full MWE?

**Comment by umutacar** [comment]
the following prints `tango` when run through pdflatex.  not with pandoc. 
```
\newcommand{\ittakestwo}[2][defaultone]{#2}
\ittakestwo[to]{tango} 
```
