### ISSUE TITLE
[markdown to html] Sequence "\t0" breaks conversion

### ISSUE THREAD

**Issue by manualbashing** [jgm/pandoc#5686]
With the following input in markdown:

```markdown
# This part is fine

FOO\t0BAR

## This part does not make it to

the html output.
```
running `pandoc .\test.md -o .\test.html` the expected output would be: 

```html
<h1 id="this-part-is-fine">This part is fine</h1>
<p>FOO\t0BAR</p>
<h2 id="this-part-does-not-make-it-to">This part does not make it to</h2>
<p>the html output.</p>
```
but the actual output is: 

```html
<h1 id="this-part-is-fine">This part is fine</h1>
FOO
```

- I am using pandoc 2.7.3 on Windows 10, PowerShell 5.1

**Comment by mb21** [comment]
Indeed, the markdown reader converts this to `RawInline (Format "tex") "\\t0BAR"` and gobbles up everything following that.

Using `-f markdown-raw_tex` is a workaround.

**Comment by manualbashing** [comment]
> Using `-f markdown-raw_tex` is a workaround. Or better, you can escape the backslash:
> 
> ```
> FOO\\t0BAR
> ```

Works for me, thanks!
