### ISSUE TITLE
Update CI pipeline to use latest fpco/stack-build:lts

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#5692]
The docker image fpco/stack-build:lts was updated to a new version on Docker Hub. It seems that it includes changes which break the current CI pipeline. The docker image used during Circle CI builds has been fixed at fpco/stack-build:lts-13 for the time being. The build-pipeline should be updated.

**Comment by tarleb** [comment]
The sources for the new release have not been published yet. We may have to manually probe the image to find out why lts-14 is not working for us.

**Comment by jgm** [comment]
Can you clarify what motivated this?  I don't see any recent build failures for pandoc master in Circle CI.

**Comment by tarleb** [comment]
All my builds were suddenly failing while working on the Lua fix:

```
#!/bin/bash -eo pipefail
apt-get install -y cabal-install-2.4

Reading package lists... Done


Building dependency tree       


Reading state information... Done

E: Unable to locate package cabal-install-2.4
E: Couldn't find any package by glob 'cabal-install-2.4'
E: Couldn't find any package by regex 'cabal-install-2.4'
Exited with code 100
```

Took me a while to realize that the docker image had changed: https://hub.docker.com/r/fpco/stack-build/tags The latest image had been uploaded just a few minutes prior.

**Comment by jgm** [comment]
@tarleb is this still an issue?

**Comment by tarleb** [comment]
Yes, still an issue:

``` sh
docker run --rm -it fpco/stack-build:latest sh -c 'apt-get update && apt-get install cabal-install-2.4'
```

failes, while this succeeds:

``` sh
docker run --rm -it fpco/stack-build:lts-13 sh -c 'apt-get update && apt-get install cabal-install-2.4'
```

**Comment by tarleb** [comment]
Or quicker:

```
$ docker run --rm -it fpco/stack-build:lts-13 grep -r hvr '/etc/apt/'
/etc/apt/sources.list.d/hvr-ubuntu-ghc-xenial.list:deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main
/etc/apt/sources.list.d/hvr-ubuntu-ghc-xenial.list:# deb-src http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main
/etc/apt/sources.list.d/hvr-ubuntu-ghc-xenial.list.save:deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main
/etc/apt/sources.list.d/hvr-ubuntu-ghc-xenial.list.save:# deb-src http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main
```

Doesn't return a result:

```
$ docker run --rm -it fpco/stack-build:lts grep -r hvr '/etc/apt/'
```

**Comment by jgm** [comment]
I don't understand how this is affecting our CI.  The CI is working fine, isn't it?  Can you link to relevant failures?  Is there something we need to change, or is this really a bug for fpco?

**Comment by tarleb** [comment]
Since we seem to be moving away from Circle CI, this can probably be closed. I created a test-PR just to verify whether problems in Circle CI persist.

**Comment by jgm** [comment]
Failed, interesting.  Should this be reported to fpco?  Not much we can do about it on this end -- though remaining with fpco/stack-build:lts-13 has few ill effects.  (We're using lts-14 in recent builds.)

As for moving away from Circle CI, we'll see.  I've got the GitHub actions CI working fairly well now, but it's still in beta and we may find that there are still things it doesn't do as well as Circle CI.

**Comment by tarleb** [comment]
I raised this at the stack repo. There is no intend to restore the previous behavior, so we'll have to update the CI scripts.

**Comment by jgm** [comment]
So the difference is that we need to add the hvr repo manually?

**Comment by tarleb** [comment]
No longer applies since we moved to GitHub CI.
