### ISSUE TITLE
Makefile is outdated

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#5694]
Some Makefile targets are outdated. E.g., some targets set flag `weight-pandoc`, which has been removed in pandoc 2.1.3.

**Comment by tarleb** [comment]
Would it make sense to move most of the CI scripts to the makefile? It might make it easier to keep the build process maintainable.

**Comment by jgm** [comment]
I can see an advantage to moving CI scripts to the Makefile if the same script is used by multiple CIs.  But if each CI uses its own somewhat different script, then it makes most sense to me to keep this in the CI config -- at least I don't see the advantage of having it in the Makefile.  Could you say more about how you're thinking of this?

**Comment by tarleb** [comment]
My thoughts were

- it is easier for developers to test the CI setup locally if there is a make target to do so;
- the number of places in which build options are defined could be reduced;
- the Makefile is more likely to be kept up to date.

I think what I'm worried about is that people might believe that the Makefile takes a similar role as it does in projects written in different languages, where it is often the central point for building the project, and then being irritated when it doesn't satisfy their expectations.

**Comment by jgm** [comment]
> it is easier for developers to test the CI setup locally if there is a make target to do so;
> the number of places in which build options are defined could be reduced;

Yes, good points.

> the Makefile is more likely to be kept up to date.

Not so sure about that -- since CI failures are noticed immediately, but some Makefile targets don't get exercised much.

Another issue is that the Makefile wouldn't help much with appveyor CI -- just with CircleCI.

I guess I don't feel too strongly about this: if you want to make this change, we can try it and see how it goes.

**Comment by tarleb** [comment]
The issue no longer applies. Closing.
