### ISSUE TITLE
Muse round-trip failure

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5697]
```
%  pandoc -f native -t muse
 [DefinitionList [([],[[OrderedList (3,Example,Period) []]])]]
^D
 <verbatim></verbatim> :: 
% pandoc -f muse -t native
 <verbatim></verbatim> :: 
^D
[DefinitionList
 [([],
   [[]])]]
```

**Comment by jgm** [comment]
I'm tempted to think this should be dealt with by changing the Arbitrary instance, so that empty lists can't be produced.

**Comment by link2xt** [comment]
Can you link to CI run with this failure? There should be one more previous representation, otherwise it is not a failure.

Round trip test writes the tree to muse, reads it, writes it again and reads it again. Then it compares the last two results. In this case, the last two results are the same:
```
$ pandoc -f muse -t native
 <verbatim></verbatim> ::
^D
[DefinitionList
 [([],
   [[]])]]
$ pandoc -f native -t muse
^D
[DefinitionList
 [([],
   [[]])]]
 <verbatim></verbatim> ::
```

**Comment by link2xt** [comment]
In other words, round trip test allows Muse writer to simplify the tree generated by Arbitrary, to remove any elements that are not representable in Muse markup.

**Comment by jgm** [comment]
Here's another one I just got:
```
  Readers
    Muse
      Blocks
        Round trip:                                                  FAIL (1.31s)
          *** Failed! Falsifiable (after 17 tests and 10 shrinks):
          Many {unMany = fromList [DefinitionList [([],[[OrderedList (2,DefaultStyle,Period) []]])]]}
          Use --quickcheck-replay=869737 to reproduce.
```

**Comment by jgm** [comment]
This is on my doctemplates branch, so it could be that some change there affects things, but the sample above was with normal pandoc.

**Comment by jgm** [comment]
OK, on doctemplates we have:
```
 % pandoc -f muse -t native
 <verbatim></verbatim> ::
[DefinitionList
 [([],
   [[]])]]
% pandoc -f native -t muse
[DefinitionList
 [([],
   [[]])]]
^D
```
So this must be something I broke in the doctemplates branch.

**Comment by jgm** [comment]
OK, it was a bug in the new doclayout library. Sorry for the false alarm.
