### ISSUE TITLE
Markdown writer: block inside numbered list with roman III. is indented 4 instead of 5 spaces

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#5705]
pandoc, latest dev, seems to have trouble with numbered lists and roman numbers with >2 letters (see below). Same result if roman numbers are lowercase, and for vii, viii, xii etc. 

In my example, “`I.`” and “`V.`” are followed by two spaces (as per the manual).

Additional issue (example not shown here): If two-letter roman numbers are followed by two or more spaces (which should be ok according to the manual), again the following bullet lists are formatted incorrectly, like after “`III.`” below .

```
$ pandoc -t plain
I.  Blah
    - Blah
    - Blah
II. Blah
    - Blah
    - Blah
III. Blah
    - Blah
    - Blah
IV. Blah
    - Blah
    - Blah
V.  Blah
    - Blah
    - Blah
^D

I.  Blah
    -   Blah
    -   Blah
II. Blah
    -   Blah
    -   Blah
III. Blah - Blah - Blah
IV. Blah
    -   Blah
    -   Blah
V.  Blah
    -   Blah
    -   Blah
```

**Comment by mb21** [comment]
So the trouble is with the third list item? From the [MANUAL](https://pandoc.org/MANUAL.html#block-content-in-list-items):

> A list item may contain multiple paragraphs and other block-level content. However, subsequent paragraphs must be preceded by a blank line and indented to line up with the first non-space content after the list marker.

So you'd have to do:

    I.  Blah
        - Blah
        - Blah
    II. Blah
        - Blah
        - Blah
    III. Blah
         - Blah
         - Blah
    IV. Blah
        - Blah
        - Blah
    V.  Blah
        - Blah
        - Blah

**Comment by mb21** [comment]
For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by njbart** [comment]
Ok, thanks. 

This doesn’t survive a round trip through markdown, though:

```
$ pandoc -t markdown
I.  Blah
    - Blah
    - Blah
II. Blah
    - Blah
    - Blah
III. Blah
     - Blah
     - Blah

I.  Blah
    -   Blah
    -   Blah
II. Blah
    -   Blah
    -   Blah
III. Blah
    -   Blah
    -   Blah
```

**Comment by mb21** [comment]
Indeed. That's a bug in the markdown writer. Minimal repro:

```
III. Blah
     - Blah
```

**Comment by jgm** [comment]
Note that you can enabled the `four_space_rule` option if you want the older behavior in the reader.

**Comment by edusantana** [comment]
```
$ pandoc -t markdown
I)  roman one

     A.  alalalal

         1. one
         2. two

     B.  bababababa

         > quoting

         1. aba
         2. bata
         3. caca

II)  roman two

     C.  okokokokoko

         > bla bla

         1. bla bla
         2. bla bla

     D.  dadadadada

         > quoting

         1. one
         2. two

III)  roman three

     E.  erererer

         > more quoting

         01. item 1
         02. item 2

     F.  bla bla

         > quote

         1. one
         2. two

IV)  foram four

     G.  erererer

         > other quoting

         01. item 1
         02. item 2

     H.  bla bla

         > last quote

         1. one
         2. two

^D

I)  roman one

    A.  alalalal

        1.  one
        2.  two

    B.  bababababa

        > quoting

        1.  aba
        2.  bata
        3.  caca

II) roman two

    C.  okokokokoko

        > bla bla

        1.  bla bla
        2.  bla bla

    D.  dadadadada

        > quoting

        1.  one
        2.  two

III) roman three

```{=html}
<!-- -->
```
     E.  erererer

         > more quoting

         01. item 1
         02. item 2

     F.  bla bla

         > quote

         1. one
         2. two

IV) foram four

    G.  erererer

        > other quoting

        1.  item 1
        2.  item 2

    H.  bla bla

        > last quote

        1.  one
        2.  two

```

I have this problem too.

**Comment by jgm** [comment]
This issue is closed; if you think you've found a new bug, open a new issue (and please give pandoc version).

**Comment by jgm** [comment]
But @edusantana you don't have the list content properly aligned  under III).
That's the problem.  See the quoted section from the manual in comments above.
