### ISSUE TITLE
RST Reader ignores isolated inline math in grid table cell

### ISSUE THREAD

**Issue by ociule** [jgm/pandoc#5708]
If we put only an inline math tag as the only content of a grid table cell, it's not seen as inline math in most situations (but it is in others, see below!).

Adding any text before the inline math ~or dividing it into two math inline tags~ fixes the issue.

Seen on pandoc 2.7.1 on windows.

Result:

![test](https://user-images.githubusercontent.com/54329/63693380-35431280-c814-11e9-87f9-16e4a0035507.png)

Here's the rst:

```rst


This inline math does work here (which is disturbing!):

+--------+-----------------------------+
| Test   | Test                        |
+========+=============================+
| Test   | :math:`SMYS+2 \cdot \sigma` |
+--------+-----------------------------+

But it's broken here:

+-------------------+------------------------------+
| Distribution type | Mean                         |
+===================+==============================+
| normal            | :math:`SMYS+2 \cdot \sigma`  |
+-------------------+------------------------------+

Also broken without the header:

+--------+-----------------------------+
| normal | :math:`SMYS+2 \cdot \sigma` |
+--------+-----------------------------+

But works with a different text in the first col:

+---+-----------------------------+
| a | :math:`SMYS+2 \cdot \sigma` |
+---+-----------------------------+

Also broken with any other latex inside that math:

+--------+-----------------------------+
| normal | :math:`1234`                |
+--------+-----------------------------+

Works with simple table:

==================== ===================
 normal                :math:`1234`
==================== ===================


The math works anywhere else: :math:`SMYS+2 \cdot \sigma`

.. math::
  SMYS+2 \cdot \sigma

Current workaround that works in table cells is to divide it into two inline math pieces:

:math:`SMYS` :math:`+2 \cdot \sigma`

```

To test, simply copy the sample rst code in the raw code block above to test.rst and run:

 $ pandoc test.rst -o test.html

Points to a bug in the RST reader. The whitespace inside the cell content seems significant, depending on that the parsing can work sometimes.

**Comment by ociule** [comment]
The correct workaround is:

```rst
*SMYS*:math:`+2 \cdot \sigma`
```

Simply dividing the inline math content into two will not help, the first one is ignored.

**Comment by mb21** [comment]
Happens only if the first cell has exactly 6 characters. This fails:

    +--------+----------------+
    | 123456 | :math:`a + b`  |
    +--------+----------------+

while this suceeds:

    +--------+----------------+
    | 12345  | :math:`a + b`  |
    +--------+----------------+

**Comment by mb21** [comment]
ha, that was odd 😅  good old state ;)

**Comment by ociule** [comment]
Thanks for the great work guys! @mb21  good catch on it being broken with text of length six.
