### ISSUE TITLE
Character references in XHTML output. In particular with `--ascii`.

### ISSUE THREAD

**Issue by JohnLukeBentley** [jgm/pandoc#5718]
## The proposal

I propose that `--ascii` output character references as numbered hexadecimal character references rather than named character references. And/Or perhaps an additional switch be created to force the kind of character reference e.g.

    --character-references literal  (In effect turning character references off)
    --character-references named
    --character-references hexadecimal 
    --character-references decimal

... or maybe that sort of switch exists and I'm missing it!

## The problem

In our markdown source we have some plain text serving as a target for output as fancy typography characters

    ## Smart Typography

    * "Smart quotes"
    * Em-dashes --- lorem.
    * En-dashes -- lorem.
    * Elipses ... lorem.

If we use a command like ...

    pandoc TestBasic.md --from markdown --to html5 --output TestBasic.xhtml --standalone

... then that will invoke the *smart* extension and, as desired, output literal fancy characters:

    <li>“Smart quotes”</li>
    <li>Em-dashes — lorem.</li>
    <li>En-dashes – lorem.</li>
    <li>Ellipses … lorem.</li>

That's all fine. That'll render in the browser just fine when served with the XHTML mime type. Moreover, given that you only need to use (named or numbered) character references, rather than literals, when dealing with character encodings that don't support the literals; UTF-8 supports all those literals; and UTF-8 is the recommend character encoding for (X)HTML - then outputting literals in XHTML is generally the best way to go (with the notable exceptions of &, <, and >).

However, if we use the `--ascii` switch (say for some quirky reason our tool chain doesn't necessarily preserve UTF-8 encoding and we want an ascii set of characters for safety) ...

    pandoc TestBasic.md --from markdown --to html5 --output TestBasic.xhtml --standalone --ascii

... We'll get Xhtml markup like this ...

    <li>&ldquo;Smart quotes&rdquo;</li>
    <li>Em-dashes &mdash; lorem.</li>
    <li>En-dashes &ndash; lorem.</li>
    <li>Ellipses &mldr; lorem.</li>

... when served with an XHTML mime type, the web page will not validate (it will choke in the browser).

[Polyglot Markup stipulates that](https://www.w3.org/TR/html-polyglot/#named-entity-references), outside of `&`, `<`, `>`, `'`, and `"`; and when we don't want to use literals, we:

* MUST use numbered character references; and
* Of the two numbered character references, hexadecimal V decimal, we SHOULD use the hexadecimal.

E.g.

    // For 
    “                               // Validates in XHTML

    // Do this
    &#x0201C;                       // Validates in XHTML 

    // Not this
    &ldquo; &OpenCurlyDoubleQuote;  // Chokes
    &#8220;          // Validates in XHTML, but discouraged. 

Edit: added "when we don't want to use literals".
Edit2: formatted chars and added "and" to make paragraph beginning "Polyglot Markup stipulates ..." clearer.

**Comment by jgm** [comment]
It would be easy to make this change:  just use `toEntities` instead of `toHtml5Entities` for HTML5.
That said, I inserted code to use `toHtml5Entities` so there must have been some reason.
That was in commmits
f379edc4ad372f96d4a5cc7cd38292f095dfdf35
and 
5350ce26b463ccb8edc7b0c7b1be72558e87992c
I can't recall now what motivated this change.

**Comment by jgm** [comment]
I agree that we should try to produce valid XHTML, and that seems a strong reason to make the change.

**Comment by JohnLukeBentley** [comment]
Thanks John.

On at a quick glance at your linked historical code changes, perhaps there's a terminological confusion, inherited from W3C's usage, that might be impeding your recollection. ...

Historically the W3C has spoken in a manner consistent with the current wikipedia edit at https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references 
> each character can manifest directly (representing itself), or can be represented by a series of characters called a character reference, of which there are two types: a numeric character reference and a character entity reference.

That is, with talk of "numeric character reference" and "character entity reference". That sort of (confusing) talk is reflected in historical W3C docs, as at https://www.w3.org/TR/html-polyglot/#named-entity-references 
> Polyglot markup uses only the following named entity references .... For entities beyond the previous list, polyglot markup uses character references. ....

I think it conceptually clearer to think about it, and use terms as follows ...

    // Literal 
    &

    // Character references.

      // Named character reference (W3C historically speaks of "character entity references")
      &amp;

      // Numeric character references
      &#x00026;  // Hexadecimal numeric character reference
      &#38;      // Decimal numeric character reference

And lo and behold (this comes as a welcome surprise to me) that phrasing is currently reflected at https://html.spec.whatwg.org/#character-references. That is, confusing talk of "entities" is dropped.

I mean presumably `toHtml5Entities` meant to point to the set of "named character references" (formerly "character entity references") that HTML5 supports, as at https://html.spec.whatwg.org/#named-character-references. But in [your code](https://github.com/jgm/pandoc/commit/5350ce26b463ccb8edc7b0c7b1be72558e87992c), line 114, it seems you are using it for a numeric character references (if I'm reading the code right).  I'm not sure what's going on there.

What set of "named character references" (formerly "character entity references") did/does `toEntities` mean to point to, the smaller HTML 4 set, as at [Character entity references in HTML 4](https://www.w3.org/TR/html4/sgml/entities.html)?

In any case what we want (outside of dealing with `&`, `<`, `>`, `'`, and `"`) are not "named character references" (formerly "character entity references") but Hexadecimal numeric character references.

Does that help jog the memory?

Additionally If my conceptual framing, and whatwg's language, appeals to you then perhaps a refactor of those variable names `toHtml5Entities` and `toEntities` might help. E.g. to something like

    toHtml5NamedCharacterReferences
    toHtml5NumericCharacterReferencesHexadecimal 
    toHtml5NumericCharacterReferencesDecimal

    toHtml4NamedCharacterReferences
    toHtml4NumericCharacterReferencesHexadecimal 
    toHtml4NumericCharacterReferencesDecimal

**Comment by JohnLukeBentley** [comment]
On the other hand, supposing that we defaulted `--ascii` to use Hexadecimal numeric character references, I could imagine someone coming along who strongly prefers to use named character references. We can imagine they output HTML rather than XHTML and find named character references more mnemonic/readable.

That might speak in favour of the additional `--character-references` switch I spoke of. So they could override the `--ascii` Hexadecimal default. 

Or maybe a  `--character-references` switch could wait until a real user makes a complaint about a `--ascii` Hexadecimal default.

**Comment by jgm** [comment]
I've always found the terminology around this confusing, but unfortunately that does not give me any clues as to why I made this change.  It might have just been because the descriptive names are easier to read.

**Comment by JohnLukeBentley** [comment]
Thanks John. Yes that seems like a plausible thought process: to have made the change because named character references are easier read. I'd have likely made the same choice, for that reason, at that point in time. That is, without the recent practical experience of having my XHTML choke on (non famous-five) named character references.

**Comment by JohnLukeBentley** [comment]
Thanks John. Just reading the code, rather than testing it, it looks like you've chosen to go with decimal numeric character references.

If that reading is right are you going against the Standards stipulation that you SHOULD use the Hexadecimal numeric character references as: a SHOULD is not a MUST; and your existing code base makes using decimals much more convenient?

Looking more closely at the issue ... it's not merely the Polyglot standard that stipulates that SHOULD. Rather that standard points to [Character Model for the World Wide Web 1.0: Fundamentals, C048](https://www.w3.org/TR/2005/REC-charmod-20050215/#C048):
>  C048  [I]  [C]  Content SHOULD use the hexadecimal form of character escapes rather than the decimal form when there are both.
>
> NOTE: The hexadecimal form is preferred because character encoding standards (in particular Unicode) usually list character numbers as hexadecimal, making lookup easier.

If the SHOULD is based on convenience of lookup then that is borne out if we look at 
[Whatwg's Character References List](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references). For example for "eacute;" only the hexadecimal U+000E9  (&#x000E9;) is given.

However there's also [W3C's Character References List](https://dev.w3.org/html5/html-author/charref) (ironically you need to turn off the CSS to make it usable) where the hexadecimal and decimal codes are given.

Either the hexadecimal or decimal form will yield valid XHTML. 

So the reasons for preferencing the hexadecimal form don't appear to be that weighty.

If all else were equal I'd favour the hexadecimal form. However, if there's some reason for favouring the decimal form (as there could well be in pandoc's case) then I can see how it would be easy to make the choice in the direction of that favour.

**Comment by jgm** [comment]
I didn't notice the part about hex.  Sure, it doesn't matter to me; I can change that easily enough.

**Comment by JohnLukeBentley** [comment]
Yeah I think the change to hex is best, as you've just done. 

Especially given [Whatwg's Character References List](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references) has lately become THE reference list for this (and doesn't list the dec codes), in virtue of Whatwg's html spec becoming THE html spec. 

As I also mentioned in the OP potentially a pandoc user could, in addition, want finer control over the character reference output. E.g. if they wanted to output and serve html rather than xhtml and given that choice preferred named character references for readability. Such wants could be taken care of through an additional `--character-references` switch (perhaps only having relevance if the `--ascii` switch is also used). 

I'm personally unlikely to ever have such a need. So it may well be best to save time and wait 'till somebody finds this very post, or raises the issue separately, and presses the need.

**Comment by bulrush15** [comment]
> I agree that we should try to produce valid XHTML, and that seems a strong reason to make the change.

Thanks JGM, EPUB uses XHTML so this should help EPUB makers too, like me. I write in Markdown and create EPUB files and sometimes create HTML files.
