### ISSUE TITLE
Article citation edit: pandoc-citeproc & pdf

### ISSUE THREAD

**Issue by huangwb8** [jgm/pandoc#5724]
Recently I use pandoc to write my journal articles.
I have to use one of the filter --  pandoc-citepro to keep a standard citations output. Actually,it work well when I want a .docx output. 
However, I also want a .pdf output  and  pandoc-citepro seems not work for pdf output.
Do you have any suggestion? I use Window 10 as OP of my computer. 
Thanks a lot!

**Comment by mb21** [comment]
Yes it does, see https://pandoc.org/MANUAL.html#creating-a-pdf

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
