### ISSUE TITLE
Self-contained HTML contains wrong <style> for web-hosted CSS

### ISSUE THREAD

**Issue by yutannihilation** [jgm/pandoc#5725]
(Originally reported at https://github.com/rstudio/rmarkdown/issues/1636)

When a URL is specified for `css`, self-contained version of HTML uses the MIME type that the server returns. The type string is usually `text/css; charset=utf-8`, but the HTML spec doesn't allow this value for a style tag.

```console
$ cat > tmp.md <<EOF
---
title: test
css: https://shklinkenberg.github.io/uva_style/ioslides_style.css
---

test
EOF

$ pandoc --from markdown --to html4 --self-contained tmp.md | grep '<style'
  <style type="text/css">
  <style type="text/css; charset=utf-8">slides > slide { border-radius: 30px; border: solid 3px white; }
```

[The spec](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element) says a `style` tag is processed by the following steps:

> 1. Let element be the style element.
> 1. If element has an associated CSS style sheet, remove the CSS style sheet in question.
> 1. If element's root is neither a shadow root nor a document, then return.
> 1. If element's type attribute is present and its value is neither the empty string nor an ASCII case-insensitive match for "text/css", then return.
> 1. If the Should element's inline behavior be blocked by Content Security Policy? algorithm returns "Blocked" when executed upon the style element, "style", and the style element's child text content, then return. [CSP]
> 1. Create a CSS style sheet with the following properties:

`text/css; charset=utf-8` doesn't pass the step 4, which only accepts either of these cases:

a. `type` attribute is absent
b. `type` attribute is present and its value is empty string
c. `type` attribute is present and its value is an ASCII case-insensitive match for "text/css"

As a result, this `style` tag is ignored on modern browsers (e.g. Chrome). The note clearly describes this:

> In particular, a type value with parameters, such as "text/css; charset=utf-8", will cause this algorithm to return early.

Though I don't try the older version of Pandoc, I believe this didn't use to happen before https://github.com/jgm/pandoc/commit/8d4fbe6a2a50d93bff0e9c7ada73774ff1bc17c6#diff-e4142091d8b82884f712082e419341b0L128. This commit changes

``` hs
                       TagOpen "style" [("type", "text/css")]
```

to

``` hs
                       TagOpen "style" [("type", mime)]
```

So, before this point, Pandoc uses the valid string, `type = "text/css"` fixedly. I think `type` attribute should be removed as [it's marked as obsolete](https://html.spec.whatwg.org/multipage/obsolete.html#attr-style-type).

---
pandoc version: 2.3.1

**Comment by jgm** [comment]
Thanks for pointing this out. The `type` is obsolete in html5, but we should keep it for html4, no?

**Comment by yutannihilation** [comment]
Sorry I was confused about the spec. You are right, in HTML4, `type` is a required attribute.

> Authors must supply a value for this attribute; there is no default value for this attribute.
(https://www.w3.org/TR/html401/present/styles.html#h-14.2.3)

And, as it requires [content-type](https://www.w3.org/TR/html401/types.html#type-content-type), charset parameter seems valid in HTML4... Considering these two specs are diverged, IIUC, it seems using the fixed string `text/css` is the safest choice.

**Comment by yutannihilation** [comment]
Wow, thanks for fixing this so quickly!!!
