### ISSUE TITLE
Bug: pandoc doesn't include some headers in toc

### ISSUE THREAD

**Issue by NightMachinary** [jgm/pandoc#5726]
```
$ pandoc --version
pandoc 2.1.3
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.1, skylighting 0.7.1
Default user data directory: /Users/evar/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

I have this file, `a.html`, that has some `h2` elements that are not included in the toc. My guess is that this is because they are wrapped by a div element, but I am not sure. The same conversion works fine with calibre.

```
$ pandoc --toc --toc-depth 3 -s a.html -o a4.epub
```

The correct result (produced via calibre):
![image](https://user-images.githubusercontent.com/36224762/64243815-38798500-cf1d-11e9-9d39-31068f66f20b.png)

pandoc's output:
![image](https://user-images.githubusercontent.com/36224762/64243743-1aac2000-cf1d-11e9-87a1-55d9d5789444.png)

[a.zip](https://github.com/jgm/pandoc/files/3573808/a.zip)

**Comment by tarleb** [comment]
You are correct that headers nested in divs won't show up in the toc. Please refer to #3057 for more discussions on this issue.
