### ISSUE TITLE
Missing dependency on skylighting-core

### ISSUE THREAD

**Issue by blackgnezdo** [jgm/pandoc#5729]
I'm using pandoc-2.7.3. 

Looks like [skylighting-core is used here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/App/OutputSettings.hs#L30)
without listing it in .cabal file. At least I'm getting this error which goes away if I add the
dependency:

```
Text/Pandoc/App/OutputSettings.hs:30:1: error:
    Could not load module `Skylighting.Parser'
    It is a member of the hidden package `skylighting-core-0.8.2'.
    You can run `:set -package skylighting-core' to expose it.
    (Note: this unloads all the modules in the current scope.)
   |
30 | import Skylighting.Parser (addSyntaxDefinition, parseSyntaxDefinition)
```

**Comment by jgm** [comment]
Note that skylighting re-exports the modules from skylighting-core, so it's not clear why this should be needed.  But I'm happy to put it in if you do need it.  How are you building?  What cabal / cabal-install / ghc versions?

**Comment by blackgnezdo** [comment]
Thanks for the fix. This is what ended up doing internally before the import.

We are building with a descendant of https://github.com/google/cabal2bazel which internally runs ghc-8.6.4 with somewhat stricter visibility settings. @judah, do you think there's any chance we aren't correctly handling re-exports?

**Comment by judah** [comment]
@blackgnezdo yeah, our cabal2bazel doesn't currently handle Cabal's reexported-modules.  To work around that, when I originally wired up skylighting internally, I modified the .cabal file in a similar way to this PR.

It probably wouldn't be difficult to fix cabal2bazel.  We'd just need to implement something like this in our internal build rules:
https://release.api.haskell.build/haskell/haskell.html#haskell_library.exports
