### ISSUE TITLE
Feature toggles

### ISSUE THREAD

**Issue by tdammers** [jgm/pandoc#5731]
Pandoc has a fairly large dependency footprint, but many of its dependencies seem to be used only for a small, relatively isolated subsets of its features. When using pandoc as a library, you typically only need some of those features, which means that you link a lot of redundant code into the final executable.

IMO, a workable solution would be to use cabal flags to control these features, allowing library users to enable or disable things like readers and writers individually, and only depending on those libraries that are actually needed to process those.

If this is something worth having, I might be convinced to do the work myself.

**Comment by jgm** [comment]
I think it's generally regarded as bad practice for cabal flags to affect the exposed API.

**Comment by jgm** [comment]
For your worries about executable size, see
https://downloads.haskell.org/~ghc/8.2.2/docs/html/users_guide/phases.html#ghc-flag--split-objs
