### ISSUE TITLE
A video file are not exported

### ISSUE THREAD

**Issue by mgcyung** [jgm/pandoc#5735]
A hyperlink is exported instead of a video from orgmode to pptx by the code below
```
[[file:/home/magic/Downloads/9343.mp4]]
```
And there is no exported content in the pptx by the code blow

```
#+begin_export html
  <video id="tubthumping" > <source
           src="/home/magic/Downloads/9343.mp4" type="video/mp4">
           </video>
#+end_export

```

**Comment by mb21** [comment]
Maybe related to https://github.com/jgm/pandoc/issues/5454?

**Comment by tarleb** [comment]
I searched the web and couldn't find any reference that Emacs org-mode supports embedding of videos (without extra code). We aim to match Emacs' behavior, so there is nothing we can do here. Closing.
