### ISSUE TITLE
Unable to syntax-highlight the entire file?

### ISSUE THREAD

**Issue by mouse07410** [jgm/pandoc#5737]
`pandoc` seems to understand a ton of programming languages (as evidenced by the output of `pandoc --list-highlight-languages`)  - but I've been unable to "highlight" the entire file.

What I'm trying to do is something like
```
$ pandoc -s -t latex -o t.tex t.c
```
but it doesn't come out syntax-highlighted - at best it packs my source code into `verbatim`.

- Pandoc 2.7.3
- macOS 10.14.6
- MacTeX 2019
- Cabal 3.0.0.0
- Stack 2.1.3

**Comment by mb21** [comment]
Save [include.lua](https://github.com/jgm/lcmark/blob/master/filters/include.lua) somewhere, then something like:

    echo -e '``` {include=t.c}\n```' | pandoc --lua-filter=include.lua -s -o t.tex

See also https://pandoc.org/MANUAL.html#syntax-highlighting

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by jgm** [comment]
Another option is to use the `skylighting` executable provided with the skylighting package.

**Comment by mouse07410** [comment]
```
$ cabal install skylighting
. . . . .
Haddock      skylighting-0.8.2 (lib)
Installing   skylighting-0.8.2 (lib)
Completed    skylighting-0.8.2 (lib)
Warning: You asked to install executables, but there are no executables in
target: skylighting. Perhaps you want to use --lib to install libraries
instead.
```

**Comment by mb21** [comment]
see https://github.com/jgm/skylighting#installing

**Comment by mouse07410** [comment]
> see https://github.com/jgm/skylighting#installing

Thank you, very helpful. Following the guidance (adding `-fexecutable` to Cabal invocation), it works now!
