### ISSUE TITLE
List items past 100 with subcontent can't be round-tripped

### ISSUE THREAD

**Issue by alerque** [jgm/pandoc#5739]
I have a list of items that's been growing for a while now. Up until this week I've been able to round-trip the Markdown through Pandoc for normalization. Since my list hit 100+ items I can hand generate Markdown that works to convert to other formats, but tho Markdown Pandoc writes cannot be read.

```markdown
1. foo

    bar

2. foo

    bar
```

These "bar" paragraphs attached to the list items have the four-space indent generated by Pandoc, but as soon as the list item hits 3 digits, it requires 5 spaces for them to stay associated. Pandoc continues to output 4 spaces even when it read 5.

Since the input is somewhat repetitive, here is a script that demonstrates the problem:

```sh
for i in $(seq 1 102); do echo -e "$i. foo\n\n     bar\n"; done | pandoc -t markdown | pandoc -t markdown
```

Note I've output 5 spaces manually, but the first pass through Pandoc reduces it to four. The second pass now can't read the input and ends up with a weird empty HTML comment:

```txt
99. foo

    bar

100. foo

<!-- -->

    bar

101. foo

<!-- -->

    bar

102. foo

<!-- -->

    bar
...

**Comment by mb21** [comment]
probably has to do with the fact that `100` is three characters long...

might have been fixed in https://github.com/jgm/pandoc/issues/5705

**Comment by alerque** [comment]
Confirmed working in `HEAD`. But the fix seems wrong to me. Why can't it read four-space indents? This makes programmatic generation of Markdown hard. Now I have to either do string length tests or always generate at least 5 space indents, most of which are going to be cropped to 4 when Pandoc touches the content. If and when things ever move around (say item 99 is swapped for 100) all the lines need to be re-indented instead of just changing the source order.

**Comment by alerque** [comment]
I guess part of my complaint here is that Pandoc is inconsistent with the rules about "matching" up until it hits 4+.

* List items are re-indented to 4 spaces:

   ```sh
    $ echo -e "- foo\n  bar" | pandoc -t markdown
    -   foo bar
    ```

**Comment by mb21** [comment]
I'm not sure I follow... can you post input and actual and expected output?
btw... the idea is to follow commonmark, but pandoc's MANUAL regarding lists should mirror commonmark quite closely.

**Comment by jgm** [comment]
You can use the `four_space_rule` extension; it might makes things easier.

As far as the inconsistency goes, using a default four-space indent ensures that the lists pandoc's markdown writer produces will be readable with the largest number of markdown processors, since there are big differences in handling of nested lists.  But of course, when the list number is extra-long, we have to depart from the default.
