### ISSUE TITLE
GitHub CI failure on FB2 reader

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5747]
@link2xt - I've started experimenting with GitHub actions CI.  Everything works except the FB2 reader tests on Windows:

https://github.com/jgm/pandoc/runs/222299416

The failure messages are unilluminating.  The actual output seems to match the golden files exactly.  I thought it might be a newline issue and added a filter to remove CRs, but that didn't fix it.

Oddly, these tests work fine on appveyor windows CI.

Do you have any idea what could be happening here?

**Comment by link2xt** [comment]
FB2 reader is the only reader that uses `goldenVsString` tests.

It is a quite simple function:
https://hackage.haskell.org/package/tasty-golden-2.3.2/docs/src/Test.Tasty.Golden.html#goldenVsString

Maybe try copy-pasting it and change it to output both versions instead of the filename?

**Comment by link2xt** [comment]
I also don't see any difference that could be there except in how `core.autocrlf` is configured for checkouts there.

**Comment by jgm** [comment]
Yes, that was it, CRs (in the golden file not the test output).
