### ISSUE TITLE
Write PDF to stdout

### ISSUE THREAD

**Issue by dAnjou** [jgm/pandoc#5751]
As suggested in #2677 I'm opening a new issue for support of writing PDF to stdout.

**Current behavior:**
```
$ pandoc --version
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
$ pandoc -t pdf README.md -o -
Unknown writer: pdf
To create a pdf using pandoc, use -t latex|beamer|context|ms|html5
and specify an output file with .pdf extension (-o filename.pdf).
```
**Desired behavior:**

Whether it's the output file extension or `--to`, it's both going to be `pdf`. Pandoc could then use a default writer (i.e. LaTeX), or you can specify another one with `--pdf-engine`.

Source: https://pandoc.org/MANUAL.html#creating-a-pdf

**Comment by mb21** [comment]
Pandoc calls `pdflatex` (or whatever is specified with `--pdf-engine`), which writes the PDF to a file. So we would have to read that file again and send it to stdout... it's doable but not especially straight-forward (cross-platform) and you don't gain any performance...

**Comment by jgm** [comment]
I think the motivation isn't for performance, but just for ease of using pandoc in pipeline contexts.

**Comment by jgm** [comment]
I came up with a good workaround/hack for this:
```
% ln -s /dev/stdout stdout.pdf
% pandoc -o stdout.pdf myfile.md
```
Of course this won't work on windows.

**Comment by dAnjou** [comment]
Nice, thank you!
