### ISSUE TITLE
install pandoc from apt got error

### ISSUE THREAD

**Issue by jinfagang** [jgm/pandoc#5752]
```
pandoc: Unknown extension: smart

```

I am runing ubuntu 16.04 and installed pandoc from apt-get.

What should I do to install smart extension.

**Comment by alerque** [comment]
What version did you end up with? (`pandoc --version`)

What extensions are enabled? (`pandoc --list-extensions=markdown`)

What (full) command are you using to run Pandoc that gives you that error?

**Comment by mb21** [comment]
The pandoc version in the debian repos is quite outdated, instead use the one from https://pandoc.org/installing.html
