### ISSUE TITLE
Jira writer performs redundant HTML encoding on code blocks

### ISSUE THREAD

**Issue by pandasauce** [jgm/pandoc#5754]
Pandoc version: 2.7.3-1 (Linux)

Source example:

    ```
    Some-Text-With Spaces-And-Hyphens
    ```

Output example:

```
{code}
Some&hyphen;Text&hyphen;With Spaces&hyphen;And&hyphen;Hyphens
{code}
```

Jira renders this as:

```
Some&hyphen;Text&hyphen;With Spaces&hyphen;And&hyphen;Hyphens
```

Desired output:

```
{code}
Some-Text-With Spaces-And-Hyphens
{code}
```

To be rendered in Jira as

```
Some-Text-With Spaces-And-Hyphens
```

**Comment by jgm** [comment]
It appears that this issue has already been fixed in the dev version.
Commit a0a41c7a8e4e385450c55459b9a01a59755766d2

**Comment by jkroepke** [comment]
@jgm Do you have plans for a new release?

**Comment by jgm** [comment]
Yes, when it's ready.  No specific date planned at this point, but I'd hope within a month or so.
