### ISSUE TITLE
mediawiki to gfm parsing error on table:   unexpected "{"

### ISSUE THREAD

**Issue by imbilltucker** [jgm/pandoc#5757]
I'm experiencing an error with pandoc converting mediawiki files to gfm.  

**Here's the version I'm using:**

pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1

**The command I'm using:**   `pandoc --from=mediawiki --to=gfm problem_table.txt `

Creates this error:

> Error at "source" (line 2, column 4):
> unexpected "{"
> expecting lf new-line, "!", "<" or "|"
> {| {{table}}
>    ^

**with this file:**   problem_table.txt
[problem_table.txt](https://github.com/jgm/pandoc/files/3628709/problem_table.txt)

----- begin file contents-----
=== Host List ===
{| {{table}}
| align="center" style="background:#f0f0f0;"|'''IP'''
| align="center" style="background:#f0f0f0;"|'''Machine Name'''
| align="center" style="background:#f0f0f0;"|'''Owner'''
| align="center" style="background:#f0f0f0;"|'''Live'''
|-
| 127.0.184.86||host1||Windows Server|| align="center" | Y
|-
| 127.0.184.89||host2||Windows Server|| align="center" | Y
|-
| 
|}
----end file contents------

I believe this is valid mediawiki markup.   I expected this to render a table without an error.

.

**Comment by jgm** [comment]
The problem is the `{{table}}` at the beginning. If you remove this, it will work.
What does that do in mediawiki?

**Comment by jgm** [comment]
If it's a template, see #4404

**Comment by mb21** [comment]
Fairly certain it's a template... not sure why it can appear there, but I suppose we could at least parse it to raw mediawiki or drop it without failing.

**Comment by imbilltucker** [comment]
Using sed to replace `{{table}}` with class="wikitable":
`sed s/{{table}}/class=\"wikitable\"/ problem_table.txt > problem_table2.txt`

then re-running the pandoc command: 
`pandoc --from=mediawiki --to=gfm problem_table2.txt `

pandoc successfully converts the table without error.

**Comment by jgm** [comment]
It would be good to get some documentation or explanation of what the `{{table}}` is doing there.

**Comment by imbilltucker** [comment]
I'm not sure where to look for documentation for {{table}}, but from experimentation, it's creating a table tag, centering column names with background (#f0f0f0).

That seems to be the extent of it.

**Comment by jgm** [comment]
Here's documentation:
https://en.wikipedia.org/wiki/Template:Table
