### ISSUE TITLE
Timeline for releasing a new version?

### ISSUE THREAD

**Issue by coryschires** [jgm/pandoc#5758]
First, I don't mean to rush you. Pandoc is a great tool, and I really appreciate the excellent work y'all do to maintain it.

I'm wondering when you plan to release a new version? The current version includes a significant bug with the JATS writer. Fortunately, that bug has been fixed by https://github.com/jgm/pandoc/pull/5595. But, unfortunately, that fix is not included in the most recent 2.7.3 release. As a result, I am not able to use 2.7.3. 

I understand I could install / use a nightly build. But I obviously would rather avoid the extra work (and risk) involved in migrating to a nightly build. But, depending on your timeline, I'm willing to do that work. I just don't want to rush ahead if y'all are planning to cut a new release soon.

Thanks again! This is a great tool!

**Comment by jgm** [comment]
Let's just say the not too distant future.
There's no specific timeline.  Less than a month I'd say.
Btw, pandoc-discuss is the place for qusetions like this.

**Comment by coryschires** [comment]
Thanks for the update, and the tip.

I will be sure to post to `pandoc-discuss` with these kinda questions in the future.
