### ISSUE TITLE
URL in a footnote does not accept a '# 'in it when creating PDF output.

### ISSUE THREAD

**Issue by ktk** [jgm/pandoc#576]
It looks like the escaping of the '#' character is broken in the LaTeX/PDF output of pandoc when it is used in a footnote. In normal text it works just fine.

Example URL: http://www.netlabs.org/#broken

I'll try to attach an example file.

**Comment by anayrat** [comment]
Hello, I have a similar issue with a url containing `%20` inside footnotes. The `%` is not escaped in the tex output.

**Comment by jgm** [comment]
Instead of posting on a closed issue, why don't you post a question in Discussions? Or a new bug report if warranted? Be sure to include complete information for reproducing the issue.

**Comment by anayrat** [comment]
Sorry, I create a new issue
