### ISSUE TITLE
misleading warning over missing title

### ISSUE THREAD

**Issue by brainchild0** [jgm/pandoc#5760]
Currently, Pandoc warns if an EPUB document is created with no title metadata:

```
$ pandoc doc.md -o doc.epub
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata,
  e.g. by using --metadata pagetitle="..." on the command line.
  Falling back to 'doc'
```

You can reproduce with any MarkDown input lacking metadata.

But a faithful user is not always helped by keeping faith:

```
$ pandoc doc.md -o doc.epub --metadata pagetitle="Title"
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata,
  e.g. by using --metadata pagetitle="..." on the command line.
  Falling back to 'doc'
```

The actual resolution   requires:
```
$ pandoc doc.md -o doc.epub --metadata title="Title"
```

The documentation makes no mention that I can find of `pagetitle` as a recognized metadata field, so removing it from the text of the warning seems like the simplest way to eliminate the conflict.

Also note, the final line is confusing to  me.  I interpret it to mean that the tool will generate a Word document (i.e. `.doc` file) instead of EPUB, but such is not what actually occurs.

**Comment by jgm** [comment]
`Falling back to 'doc'` is saying that pandoc is using `doc`, the basename of your filename, as the title in the absence of an explicitly specified title.

**Comment by brainchild0** [comment]
Oh.

I completely missed that meaning.

Maybe `Using fallback title 'doc'.`?

I probably would have been more likely to understand if I recognized the string as a default title I might expect to be used, like _Title_ or _Document_.

Maybe others are more likely to get it, but no harm in being clearer.
