### ISSUE TITLE
odt writer does not apply custom styles for characters, blocks and so on

### ISSUE THREAD

**Issue by N0rbert** [jgm/pandoc#5764]
I'm using pandoc 2.7.3 to produce some bookdown documents.
I know that [custom styles](https://pandoc.org/MANUAL.html#custom-styles) and styles reference works normally in docx (at least for paragraphs).
But it does not work for OpenDocument.

I have the following simple Markdown document named *styles.md*. It use predefined style names from LibreOffice 6.2 and contains the following:

```
::: {custom-style="Title"}
This is some text.
:::

::: {custom-style="Caption"}
This is text with an [placeholder]{custom-style="Placeholder"} text style.
And this is text with a [teletype]{custom-style="Teletype"}
text style.
:::

::: {custom-style="Illustration"}
> Here is a styled paragraph that inherits from illustration style.
:::
```

I expect that the document should look as shown below:

![styled-odt-expected](https://user-images.githubusercontent.com/309456/65378226-3ace3400-dcbe-11e9-8cf8-b53800c935db.png)

But if I produce OpenDocument from my Markdown document it with `pandoc styles.md --to odt+styles -o styles.odt`. The styles are not applied:

![styles-odt](https://user-images.githubusercontent.com/309456/65378199-f5116b80-dcbd-11e9-936c-5adf21b82427.png)

**Comment by jgm** [comment]
Judging from the manual, `custom_styles` is only currently implemented for docx and icml.

**Comment by mb21** [comment]
Closing in favour of https://github.com/jgm/pandoc/issues/2106#issuecomment-369197863

**Comment by N0rbert** [comment]
In anyway it would be very useful to have described functionality inside pandoc itself. This means without plugins and third-party tools. This will make pandoc even better. Having this functionality only for docx is unfairly.

**Comment by mb21** [comment]
@N0rbert agreed, pull requests welcome!

**Comment by ulatekh** [comment]
Note that this can be fixed with a [custom Lua filter](https://github.com/josineto/pandoc-odt-filters). `odt-custom-styles.lua` gets pandoc 3.1.3 to convert Markdown spans (whether bracketed or HTML-like) to character styles during ODT output.
