### ISSUE TITLE
Bold and italic in generated docx

### ISSUE THREAD

**Issue by vv73** [jgm/pandoc#5768]
I tried https://github.com/jgm/pandoc/issues/4391 solution, used the lua-script.
But it seems to be there are not Strong style in the generated word, but  Pandoc creates new style for bold markdown Strong1. It is not right, I think.

**Comment by jgm** [comment]
"Strong1" is the display name Word uses (confirmed with latest dev version as well).
I think this must be because there is a built-in style named "Strong".
The solution is to use a different name for your style.  Custom styles should have names distinct from built-in Word styles.

**Comment by vv73** [comment]
But I want to get built-in Strong style, not my own.
We get Header1-3 built-in styles, can I get built-in Strong from markdown **...**?

**Comment by agusmba** [comment]
There is a very recent improvement that might solve this (See #5732), without needing the reference-doc.
@vv73 could you try again with a recent nightly build?

**Comment by agusmba** [comment]
Nevermind, this is not working yet.
As a workaround, @vv73  you need to use a reference-doc with the standard Strong style applied somewhere in the document.
Note that for international users, it may be called differently in Word, such as "Texto en negrita" in Spanish, but the lua filter is correct in using the English name of the style.

@jgm it might be interesting to include these built-in styles in the internal default reference doc so that this problem is solved without the need for a custom reference-doc. I say *might* because I understand the rationale for keeping the default reference doc as simple as possible.

**Comment by vv73** [comment]
That's works fine, thank you. The last problem is it does not work for nested italic in bold (* * in ** **). Can I get combined third style fo that?

**Comment by jgm** [comment]
Yes, I think it might make sense to include Strong and others in the default reference.docx.
If someone wants to come up with a list of such styles and produce a styles.xml that includes them, I can splice them in and we can try it.

**Comment by agusmba** [comment]
There are many built-in styles in Word, but the thing is that there isn't a *clear* correspondence with Markdown styles as there is with **Strong** and *Emphasis*. Therefore I'm not sure how many of them we should include (if at all).

I made a quick test with:

```markdown
$ pandoc -f markdown -t docx -o test.docx --reference-doc testR.docx << EOF
---
title: AMB Título
author: AMB
date: 24/05/19
...

# My first level title

Blah blah blah

**Bold** or [Strong]{custom-style="Strong"}.

*Italics* or [Emphasis]{custom-style="Emphasis"}.

> Block Text

::: {custom-style="Block Text"}
Block Text style.
:::

::: {custom-style="Quote"}
Quote style.
:::

::: {custom-style="Intense Quote"}
Intense Quote style
:::

EOF
```

Block Text is already defined, so probably only Strong and Emphasis should be included. Optionally I sometimes use *Quote* and *Intense Quote* but this might be not relevant for the majority of Word users out there.

<details>
<summary>The relevant styles parts are:</summary>

```xml
<!-- not sure if this first one is new or if it's already in the default reference-doc -->
	<w:style w:type="character" w:default="1" w:styleId="Fuentedeprrafopredeter">
		<w:name w:val="Default Paragraph Font"/>
		<w:uiPriority w:val="1"/>
		<w:semiHidden/>
		<w:unhideWhenUsed/>
	</w:style>
...
	<w:style w:type="character" w:styleId="Textoennegrita">
		<w:name w:val="Strong"/>
		<w:basedOn w:val="Fuentedeprrafopredeter"/>
		<w:rsid w:val="00060B39"/>
		<w:rPr>
			<w:b/>
			<w:bCs/>
		</w:rPr>
	</w:style>
	<w:style w:type="character" w:styleId="nfasis">
		<w:name w:val="Emphasis"/>
		<w:basedOn w:val="Fuentedeprrafopredeter"/>
		<w:rsid w:val="00060B39"/>
		<w:rPr>
			<w:i/>
			<w:iCs/>
		</w:rPr>
	</w:style>
...
<!-- just in case... -->
	<w:style w:type="paragraph" w:styleId="Cita">
		<w:name w:val="Quote"/>
		<w:basedOn w:val="Normal"/>
		<w:next w:val="Normal"/>
		<w:link w:val="CitaCar"/>
		<w:rsid w:val="00060B39"/>
		<w:pPr>
			<w:spacing w:before="200" w:after="160"/>
			<w:ind w:left="864" w:right="864"/>
			<w:jc w:val="center"/>
		</w:pPr>
		<w:rPr>
			<w:i/>
			<w:iCs/>
			<w:color w:val="404040" w:themeColor="text1" w:themeTint="BF"/>
		</w:rPr>
	</w:style>
	<w:style w:type="character" w:customStyle="1" w:styleId="CitaCar">
		<w:name w:val="Cita Car"/>
		<w:basedOn w:val="Fuentedeprrafopredeter"/>
		<w:link w:val="Cita"/>
		<w:rsid w:val="00060B39"/>
		<w:rPr>
			<w:i/>
			<w:iCs/>
			<w:color w:val="404040" w:themeColor="text1" w:themeTint="BF"/>
		</w:rPr>
	</w:style>
	<w:style w:type="paragraph" w:styleId="Citadestacada">
		<w:name w:val="Intense Quote"/>
		<w:basedOn w:val="Normal"/>
		<w:next w:val="Normal"/>
		<w:link w:val="CitadestacadaCar"/>
		<w:rsid w:val="00060B39"/>
		<w:pPr>
			<w:pBdr>
				<w:top w:val="single" w:sz="4" w:space="10" w:color="4F81BD" w:themeColor="accent1"/>
				<w:bottom w:val="single" w:sz="4" w:space="10" w:color="4F81BD" w:themeColor="accent1"/>
			</w:pBdr>
			<w:spacing w:before="360" w:after="360"/>
			<w:ind w:left="864" w:right="864"/>
			<w:jc w:val="center"/>
		</w:pPr>
		<w:rPr>
			<w:i/>
			<w:iCs/>
			<w:color w:val="4F81BD" w:themeColor="accent1"/>
		</w:rPr>
	</w:style>
	<w:style w:type="character" w:customStyle="1" w:styleId="CitadestacadaCar">
		<w:name w:val="Cita destacada Car"/>
		<w:basedOn w:val="Fuentedeprrafopredeter"/>
		<w:link w:val="Citadestacada"/>
		<w:rsid w:val="00060B39"/>
		<w:rPr>
			<w:i/>
			<w:iCs/>
			<w:color w:val="4F81BD" w:themeColor="accent1"/>
		</w:rPr>
	</w:style>
```

</details>

I don't know what's the deal with the character styles associated to the paragraph ones (Quote and Intense Quote) which seem to lose any English name reference. Maybe they're best left out of the default reference doc.

Note that StyleIds are localized, and *Fuentedeprrafopredeter* is the style with name *Default Paragraph Font*

I also attach the reference docx... as a reference:
[testR.docx](https://github.com/jgm/pandoc/files/3647754/testR.docx)

**Comment by agusmba** [comment]
If we want to include more built-in styles, some additional ones could be: Plain Text, E-mail Signature, HTML xxx(many of them), Comment Subject, Balloon Text, Placeholder Text, No Spacing, Revision, List xxx (many of them), Subtle Emphasis, Intense Emphasis, Subtle Reference, Intense Reference, Book Title, ...

There are many more, you can create a list using a [DocTools](https://www.thedoctools.com/word-macros-tips/word-macros/create-style-name-list/) macro.

**Comment by jgm** [comment]
@agusmba thanks for putting this together; can you create a new issue with this information?  Here we'll lose track.

**Comment by agusmba** [comment]
Sure thing
