### ISSUE TITLE
Option to omit links emission

### ISSUE THREAD

**Issue by am11** [jgm/pandoc#5770]
It is somewhat uncommon to have link in the middle of text in manpages. OTOH, for example, a well-written markdown document could be littered with inline links. The default behavior of pandoc is to add URL next to anchor text in brackets, e.g.:

```sh
docker run --interactive --volume "`pwd`:/data" --user `id -u`:`id -g` pandoc/core:2.7.2
-s -f markdown -t man -V section=1 -V header="My Header" --column=500 <<EOF
## My Title
Some text with [link](/to/path).
EOF
```

results in:

```manpage
.\" Automatically generated by Pandoc 2.7.2
.\"
.TH "" "1" "" "" "My Header"
.hy
.SS My Title
.PP
Some text with link (/to/path).
```

Currently, we can add [a filter](https://github.com/dotnet/cli/blob/b44490d7c335e6be07e7ebae9c597695525c3950/Documentation/manpages/tool/man-pandoc-filter.py#L37-L43) to remove the link. IMO, it would be helpful for other users if there is an option to omit links out of the box.

Thank you for this wonderful tool! 👍

**Comment by jgm** [comment]
it might make sense just to change the man writer so that all internal links are omitted.
External links still make sense.

**Comment by jgm** [comment]
I should have spoken of "relative URLs" vs "absolute", instead of internal/external.
Note that links like `#foo` are already suppressed by the man writer.
So the question is whether `/foo/bar` should also be suppressed.
