### ISSUE TITLE
CommonMark conversion appears to choke on HTML

### ISSUE THREAD

**Issue by iand675** [jgm/pandoc#5774]
I'm using pandoc-2.7.3 (Stack LTS 14.7):

When feeding CommonMark input with HTML tags, the conversion returns an empty string:

### Definitions
```
commonMarkToHaddock :: Text -> IO Text
commonMarkToHaddock mark = runIOorExplode (readCommonMark def mark >>= writeHaddock def)

commonMarkToHtml :: Text -> IO Text
commonMarkToHtml mark = runIOorExplode (readCommonMark def mark >>= writeHtml5String def)
```

### Examples

```
> commonMarkToHaddock "<p>Hi</p>"
""
> commonMarkToHtml "<p>Hi</p>"
""
```

As far as I understand it from reading the CommonMark spec, HTML blocks are valid inputs, so I'm pretty sure something's getting gummed up on the Pandoc side.

**Comment by jgm** [comment]
Try setting the `Ext_raw_html` extension (`readerExtensions` in `ReaderOptions`).
You can use `getDefaultExtensions "commonmark"` to get the extensions the pandoc executable defaults to.

**Comment by iand675** [comment]
Thanks for the advice!

Unfortunately, that doesn't seem to do anything:

``` haskell
commonMarkToHaddock :: Text -> IO Text
commonMarkToHaddock mark = runIOorExplode 
  (readCommonMark commonMarkDefs mark >>= writeHaddock haddockDefs)
  where
    commonMarkDefs =
      def { readerExtensions = enableExtension Ext_raw_html $ getDefaultExtensions "commonmark" }
    haddockDefs =
      def { writerExtensions = getDefaultExtensions "haddock" }

```

``` haskell
commonMarkToHaddock "<p>Noodle</p>"
> ""
```

**Comment by iand675** [comment]
Followup: it appears that everything after the first HTML tag is truncated:

```
commonMarkToHaddock "uwu<p>Noodle</p>noow"
> "uwu"
```

**Comment by jgm** [comment]
Try to isolate the isue.
```
% pandoc -f commonmark -t native
<p>Noodle</p>
[RawBlock (Format "html") "<p>Noodle</p>\n"]
```
Looks like the commonmark reader is working.  Let's look at the haddock writer:
```
% pandoc -f native -t haddock
[RawBlock (Format "html") "<p>Noodle</p>\n"]
^D
```
No output.  So the question is now: what does the haddock writer do with raw HTML blocks, and what *should* it do?  Looking at the code:
```haskell
blockToHaddock _ b@(RawBlock f str)
  | f == "haddock" =
      return $ text str <> text "\n"
  | otherwise = do
    report $ BlockNotRendered b
    return empty
```
It ignores raw HTML blocks.  That is by design.  Haddock doesn't allow raw HTML, does it?

**Comment by jgm** [comment]
You may be expected pandoc to parse the raw HTML parts and convert to native Haddock.
That's not how raw HTML in markdown gets handled by pandoc -- it is just passed through.
However, if you want this behavior you can get it by using `walk` with a function that calls the HTML reader.
