### ISSUE TITLE
docx convert header, footer and text box text to end or start of document

### ISSUE THREAD

**Issue by Zeppelin456** [jgm/pandoc#5775]
I would like to use pandoc to convert text from job applicant cvs who have sent to us, just into plain text or rtf which can be easily added to a database, however the most important information (their name, contact details etc, are usually in the header of the doc, and sometimes text boxes. If I can at least be sure the information is there, even if in the wrong place then I would be overjoyed!! End of document or top is fine for me. Maybe a switch --worddoc-header-text and set to doc-end, doc-start or in-place (wherever they are found). and a similar one for text boxes? Same for .docs as well.

**Comment by agusmba** [comment]
it might be easier to convert the csv to json->yaml as a first step (using a node library or any alternative), once in yaml it's pretty easy to use pandoc to generate dynamic docs.

**Comment by alerque** [comment]
@agusmba It sounds like this guy wants the other way around, he is trying to convert CVs (as is *Curriculum Vitae*, plural) in doc format to plain text, not CSV tabular data do docs.

@Zeppelin456 Given how much work often goes into making CVs I think I would be offended and want to walk away from any prospective employer who scrapped my CV into a text only database. Also given how CV data is often in tables and with other special organization, is it really realistic to get anything useful out of a dump of non-normalized data do you think? If you are just looking for searchability there are better extraction methods than Pandoc.

**Comment by Zeppelin456** [comment]
@alerque - I think you very much misunderstand the use here.  We work with recruitment agencies who are given cvs by candidates who want to use their services to get a job.  The candidates sign up and accept terms to have their cvs and personal data stored in the recruiters database and sent out to prospective employers and apply for jobs.  To get them onto their database we parse the CV for basic contact detail and employment history in order to populate the database.  CVs can be in pfd docx doc etc so we convert to text and then parse.   The header of the document often has their personal contact details, and without it we cannot extract name and address etc.  We use another tool to extract at the moment, but pandoc has support for more document types and better final conversion format, hence it would be good to use if we can.  We also convert the docx to rtf to edit onside the app and then convert back to pdf at the end. Our requirements really are to get the text in a reasonable format to display as html and parse for content and to convert between formats easily.   Apache TIKA server as an example does add Header text at the top, footer text at the bottom and text box text in the middle and is perfect some of this but has less document types to convert to, basically you can get text or html but not PDF which is used as a standard to send the final documents out.  At the moment we use lots of tools that are not very consistent and this would give us the opportunity to consolidate into one.

**Comment by jgm** [comment]
You can ask on pandoc-discuss if anyone has a good way to do this.  This issue tracker isn't the right place for questions like this.

**Comment by Zeppelin456** [comment]
The issue was an enhancement request / bug so I do think this is the right place.  It is not a case of how to do something.  The docx reader does not pull in the header, footer or text boxes which is makes it unusable for me, and I am sure for others.   Most other docx converters put the Header at the top of the text, Footer at the bottom of the text and the text boxes in place where they are found.  Pandoc is great, but I can’t use it at the moment as in my case the most important information in the document is often in the header and footer.
Anyway, of course I defer to your better judgement!

**Comment by alerque** [comment]
@Zeppelin456 I think I _do understand_ the issue actually. And even if I would go about tooling my own projects differently (deliberately using different pipelines for extraction & indexing than for format conversion & document rendering) I do agree that this is an issue with the reader that could be fixed. Re-opening the issue as a feature request seems correct to me.

**Comment by Zeppelin456** [comment]
Apologies, I did not mean to imply you did not understand.  We do use different tools for indexing,  but we convert docs to rtf and html for adding to controls on the app, and extracting text to parse to database fields. We also generate branded documents to pdf for consistent send formats. We separately index documents for text search, but Tika and most indexers cannot convert to document formats outside text or html, so we use a lot more tools than we would like specifically for doc conversion.  Basically just need to header and footer and text boxes in a sensible place, and understand totally that it may not be a perfect fit for everyone, but seems a good halfway house. Thanks for reopening.

**Comment by jgm** [comment]
Have you looked at open issues like #3086 and #5211 to see if your request has already been made?
