### ISSUE TITLE
Provide option to prevent line breaks in links

### ISSUE THREAD

**Issue by gpanders** [jgm/pandoc#5777]
I often use pandoc to format Markdown documents like so

``` console
pandoc -f gfm -t gfm --standalone --columns=79
```

This works almost perfectly, except that inline links like this

```markdown
[A link to a really cool website](https://coolwebsite.coolstuffnow.biz/2019/09/26/cool/stuff/is/so/cool/wow/omg/)
```

will be wrapped like this
```markdown
[A link to a really cool
website](https://coolwebsite.coolstuffnow.biz/2019/09/26/cool/stuff/is/so/cool/wow/omg/)
```

I would prefer that links do not get wrapped. I realize this is strictly a matter of opinion so I'm not asking that the default behavior change, but could this be added as an option? Maybe another variant to `--wrap` or something like `--no-break-links`?

Or, if there is a way to do this with the existing implementation, I'm all ears!

**Comment by jgm** [comment]
You can use nonbreaking spaces:
```
[A \link\ to\ a\ really\ cool\ website](...)
```
If you don't want to do that manually, you could use a simple lua filter that matches Link elements and replaces Space inside the Link text with `Str "\160"`.

**Comment by gpanders** [comment]
That does seem to work when using `-f markdown -t markdown`, but not with `-f gfm -t gfm`:
```markdown
[A\ link\ to\ a\ really\ cool\ website](https://coolwebsite.coolstuffnow.biz/2019/09/26/cool/stuff/is/so/cool/wow/omg/)
```
becomes
```markdown
[A\\ link\\ to\\ a\\ really\\ cool\\
website](https://coolwebsite.coolstuffnow.biz/2019/09/26/cool/stuff/is/so/cool/wow/omg/)
```

**Comment by gpanders** [comment]
This will work well enough for me for now. For anyone who may be curious, I use vim to "pre-process" the link text before running it through pandoc: https://github.com/gpanders/dotfiles/commit/94b2a2e275574d972094804ac64a46c657615675#diff-c368d2724a560fb072562999aef24e77R1

**Comment by jgm** [comment]
@gpanders `gfm` doesn't support this syntax for a nonbreaking space, though you can still just insert a unicode nonbreaking space, or use `&nbsp;`.
