### ISSUE TITLE
org to docx export : export colored text

### ISSUE THREAD

**Issue by deb75** [jgm/pandoc#5781]
Hello,

I use pandoc 2.7.3 (windows 2016) to translate org file to docx, this works well except for colored text.

Within orgmode, I hve the following macro 
```
#+MACRO: textcolor @@latex:\textcolor{$1}{$2}@@@@odt:<text:span text:style-name="$1">$2</text:span>@@
```

so that I can get colored text indifferently when exporting an org file directly to pdf or odt with emacs.

I am unable to get the same result when exporting the org file to docx with pandoc. I tried putting manually either `\textcolor{...}{...}` or `<text:span ...>...</text:span>` into the org file, I just get a raw export.

Is there a way to make pandoc understand `\textcolor{}{}` ?

I guess it should be possible as pandoc is able to understand latex equations and org tables when exporting from org to docx.

Regards

**Comment by agusmba** [comment]
Equations and tables are supported by pandoc's internal AST. Colors aren't AFAIK, that might be why you lose them.
I'm not sure if you can mark custom-styles in org files (which would translate to docx)

**Comment by deb75** [comment]
In order to make the `<text:span ...>...</text:span>` work with the emacs odt exporter, I had first to define a custom-style in a xml file, here is the lines I added : 
```
<style:style style:name="magenta" style:family="text"> <style:text-properties fo:color="#ff00ff"/> </style:style>
<style:style style:name="red" style:family="text"> <style:text-properties fo:color="#ff0000"/> </style:style>
<style:style style:name="blue" style:family="text"> <style:text-properties fo:color="#0000ff"/> </style:style>
<style:style style:name="green" style:family="text"> <style:text-properties fo:color="#00ff00"/> </style:style>
<style:style style:name="cyan" style:family="text"> <style:text-properties fo:color="#00ffff"/> </style:style>
<style:style style:name="yellow" style:family="text"> <style:text-properties fo:color="#ffff00"/> </style:style>
```

Do you mean I have to do the same for pandoc to interpret   `<text:span ...>...</text:span>` ?

**Comment by jgm** [comment]
Color is out of scope for pandoc: we try to capture structural elements, but not presentation details.

Adding raw HTML or LaTeX won't help when you're exporting docx, because these are omitted in docx output.

**Comment by deb75** [comment]
Hi,

It is really sad colors could not be exported from org to docx.

In org mode, bold text (within stars) or italic text (within slashes) are nicely exported to docx,
why colors could not be exported ?

How do you translate bold text from org to docx ? Isn't it some kind of `<span weight="bold">bold text</span>` expression ? would it be possible to write the same kind of expression for colors :  `<span color="red">red text</span>`  ?

I am sure there is some workaround, otherwise it would be so sad I could not use pandoc just because of that.

But of course, I perfectly understand that you may regard this issue as not prioritary.

Regards

deb75
