### ISSUE TITLE
Lack of detailed documentation on how to write pandoc's Markdown

### ISSUE THREAD

**Issue by tomchor** [jgm/pandoc#5783]
I am currently considering the possibility of writing large documents using Pandoc's Markdown and I am having a lot of trouble to find examples of how to do that. Sure, I can write a simple Markdown document, but Pandoc's Markdown has lots of useful functionalities (like defining variables in the preamble, citations, etc.) that, frankly, seem to me to be very poorly documented. 

I think the focus of Pandoc's documentation lies really heavily on the conversion between formats, which is why this part gets left out. So I'd like to request a section on the docs dedicated to this. I think it'd really help new users with Pandoc.

PS: If there is such a documentation and I just have missed it, please let me know! But, really, I've looked and couldn't find much.

**Comment by jgm** [comment]
Well, there is a whole section of the manual called "Pandoc's markdown."
https://pandoc.org/MANUAL.html#pandocs-markdown
Did you miss that, or were there specific things you think it didn't cover well enough?

**Comment by tomchor** [comment]
I didn't miss that, but that's a good point. I thought is was smaller than it is. So in a way my comment may not be very relevant and I apologize.

However, I guess I thought it was smaller because to me it doesn't do a very good job of showing how things works. Every time I need to figure out how to do something I generally search there first and I find that it doesn't help me at all. I end up finding my answer somewhere else.

One suggestion I have is to make a sample document available that uses most of the features that one needs to get started. Then a new user could compile it and see how things translate. Shouldn't be hard, I think.

**Comment by jgm** [comment]
I think it is actually hard, because "what ones needs to get started" depends very much on what sort of document you're writing.  (Slide show?  Ebook?  Academic article with math and citations?  Manual?  Letter?)

**Comment by tomchor** [comment]
Okay, if you think that this isn't easy, then my point may not be relevant. Feel free to disregard it.

**Comment by mb21** [comment]
I think there is a lot of documentation out there, but it's a bit all over the place... in addition to the MANUAL, there is for example:

- https://github.com/jgm/pandoc/tree/master/doc
- https://github.com/jgm/pandoc/wiki/Documentation-and-Tutorials

Feedback definitely welcome, but yes, I think we cannot make it right of everybody.

**Comment by bpj** [comment]
This looks like  a good use case for [the wiki][]. The OP and others should contribute to the wiki describing the solutions they have found to the problems they have had. Why not start a page "Tips for writing ‹type of document› in Markdown", or contributing to the page if/when it already exists? If something turns up which is generally useful it can easily be added to the manual, but the manual can clearly not cover everything — it's already huge! — and the wiki seems the right place for this.

[the wiki]: https://github.com/jgm/pandoc/wiki

**Comment by mb21** [comment]
I think the MANUAL actually covers everything, but unless you read the whole thing, it's easy to miss something.

There are several different target audiences to consider:
- people that don't know markdown, coming from Word (or maybe RST or HTML)
- people that know markdown, but don't know pandoc's markdown

But agreed, the wiki seems like a good place for that.

**Comment by bpj** [comment]
Yeah, and on the wiki you can easily have different pages for people coming
from different backgrounds.  Perhaps a "wanted topics" page on the wiki
would be a good idea.


Den lör 2 nov. 2019 12:46Mauro Bieg <notifications@github.com> skrev:
