### ISSUE TITLE
Merge doclayout branch

### ISSUE THREAD

**Issue by link2xt** [jgm/pandoc#5788]
@jgm How is the project of moving pretty-printer to [doclayout](https://hackage.haskell.org/package/doclayout) going?

I see there are some improvements to Muse writer in the doclayout branch.

Are there any issues that need to be resolved before it could be merged into the master branch?

**Comment by jgm** [comment]
It has already been merged!
Commit 1ee6e0e0878bcd655f31deb0caf6a4766e500cc6

**Comment by link2xt** [comment]
Ah, I see, these commits got squashed. I should have pruned my remote branches then.
