### ISSUE TITLE
Parse <samp> tags in HTML

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5792]
```
<samp>foo</samp>
```
should be parsed as
```
Code ("",["sample"],[]) "foo"
```
or something like that.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/samp

This could be supported by the writer as well.

**Comment by lemzwerg** [comment]
Thanks for adding this to the tracker!

While you are at it, maybe the same should happen for
```
<var>foo</var>
```

**Comment by jgm** [comment]
I added another issue for var.

**Comment by amogh09** [comment]
I would like to contribute this feature.

**Comment by jgm** [comment]
@amogh09 go ahead!

**Comment by amogh09** [comment]
@jgm I think it makes sense to treat `<samp>` in the same way we treat `<code>` and `<tt>` elements. However, `<code>` and `<tt>` convert to `Code ("", [], "")`  and not to `Code ("", ["code"], "")` and `Code ("", ["tt"], "")`, respectively. Do we want to add `"sample"` as an Attribute class for `<samp>` as mentioned in the description? If yes, should I change the parsing of `<code>` and `<tt>` similarly?

**Comment by mb21** [comment]
For `<tt>`, I think it might make sense to add a class. But `<code>` is kind of considered the default in pandoc (think of markdown), so it's probably better that it doesn't have a class.

**Comment by amogh09** [comment]
I see. I'll create a separate issue (and assign to myself) to update parsing of `<tt>` and the newly added `<samp>` to add appropriate attribute class. Let me know if any concerns. 

I have added #5843 to add support for `<samp>`. This change doesn't add "sample" to attribute class as I am using the existing function that parses `<tt>` and `<code>`.

**Comment by jgm** [comment]
Personally I'm fine with continuing to treat `<tt>` just like `<code>`.  It's "unmarked" typewriter font text in both cases.  But I could probably be convinced if people think there's a real use for putting a class on tt.

**Comment by jgm** [comment]
I think adding the class `sample` for `<samp>` should be part of the PR you just submitted, rather than a separate issue.  That is part of what is described above.

**Comment by amogh09** [comment]
Added new commit to add "sample" as an attribute class for `<samp>`. Please check.
