### ISSUE TITLE
Support <kbd> in HTML

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5796]
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd
```
Please press <kbd>Ctrl</kbd>
```
would better be parsed as a Span with a special class `kbd`.
The writer should be sensitive to this as well, rendering such spans using `<kbd>`.

**Comment by salim-b** [comment]
While switching to Pandoc 2.8.x I've noticed that

```sh
echo "This is my [key]{.kbd} example" | pandoc --from=markdown --to=markdown-raw_attribute-inline_code_attributes
```

outputs

```
This is my [key]{.kbd} example
```

while

```sh
echo "This is my <kbd>key</kbd> example" | pandoc --from=markdown --to=markdown-raw_attribute-inline_code_attributes
```
outputs

```
This is my <kbd>key</kbd> example
```

I think it would be awesome if the former command would produce the same output as the latter since

> [Markdown allows you to insert raw HTML (or DocBook) anywhere in a document (...)](https://pandoc.org/MANUAL.html#extension-raw_html)

Currently [inline code attributes](https://pandoc.org/MANUAL.html#extension-inline_code_attributes) seem like a one-way road to me...

**Comment by jgm** [comment]
Yes, but raw HTML is just passed through as raw HTML; it isn't parsed.

**Comment by salim-b** [comment]
> Yes, but raw HTML is just passed through as raw HTML; it isn't parsed. (That's by design.)

Well, since Pandoc 2.8, `<kbd>` isn't just "passed through" anymore as long as I don't explicitly disable the `raw_attribute` extension:

```sh
echo "This is my <kbd>key</kbd> example" | pandoc --from=markdown --to=markdown
```

yields:

```
This is my `<kbd>`{=html}key`</kbd>`{=html} example
```

**Comment by jgm** [comment]
That is just a pandoc-markdown syntax for explicitly marking up raw text in some format.
If you don't like it, disable the `raw_attribute` extension:
```
 % echo "This is my <kbd>key</kbd> example" | pandoc --from=markdown --to=markdown-raw_attribute
This is my <kbd>key</kbd> example
```

**Comment by salim-b** [comment]
> That is just a pandoc-markdown syntax for explicitly marking up raw text in some format.

OK, I got that.

But somehow I still feel that

```sh
echo "This is my [key]{.kbd} example" | pandoc --from=markdown --to=markdown-inline_code_attributes
```

should then yield

```
This is my `<kbd>`{=html}key`</kbd>`{=html} example
```

instead of

```
This is my [key]{.kbd} example
```

(as I tried to explain in my [first post](https://github.com/jgm/pandoc/issues/5796#issuecomment-561878777))

Anyway, feel free to ignore this and focus on more important stuff 😄
