### ISSUE TITLE
Handle cite attribute of <q> in HTML

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5798]
If `cite` attribute is present, we should parse a `<q>` as a Link around a Quoted.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q
```
<q cite="https://www.imdb.com/title/tt0062622/quotes/qt0396921">I'm sorry, Dave. I'm afraid I can't do that.</q>
```

**Comment by barskern** [comment]
I'd like to implement this feature.
