### ISSUE TITLE
Handle <var> in HTML

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5799]
Should be parsed as Code with a class `var`.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var
This could be supported bidirectionally, in both reader and writer.

**Comment by Mauricio-123** [comment]
Primeramente el var para que quieres usarlo

**Comment by Wandmalfarbe** [comment]
The elements [`<samp>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/samp) and [`<tt>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt) could be treated similarly.

**Comment by DavSanchez** [comment]
Hello!

I'd like to know more about this issue. For example, when talking about an HTML reader, do you just want `<var>` to have the same behaviour as `<code>`?

Maybe I can try and contribute to it. I'll read the code a little bit to see if I'm capable of doing it.

**Comment by jgm** [comment]
No, not the same behavior.  In pandoc Code elements can have attributes; the suggestion is to add the `var` class to these attributes in parsing `var`.

**Comment by jgm** [comment]
@Wandmalfarbe  on samp, see #5792.  tt is already parsed as generic Code, which seems right.

**Comment by amogh09** [comment]
For Writers/HTML, do we want to check if `var` or `samp` is a member of `Code`'s attribute classes and if so write `<var>` or `<samp>`, respectively, instead of `<code>`?

**Comment by jgm** [comment]
> For Writers/HTML, do we want to check if var or samp is a member of Code's attribute classes and if so write <var> or <samp>, respectively, instead of <code>?

Yes, I think so.

Question: should we use `var` and `samp` as the classes, or `variable` and `sample`?

**Comment by amogh09** [comment]
I think `variable` and `sample` makes more sense. I will add this feature if @DavSanchez is not working (or planning to work) on it.

**Comment by DavSanchez** [comment]
@amogh09 please feel free to do it! At the moment I’m focusing my free time on HIE, so I don’t think I’ll be able to work in this, at least for a time.

**Comment by amogh09** [comment]
@jgm Added a PR for this feature. Please take a look.
