### ISSUE TITLE
Pandoc hangs forever instead of failing - mermaid

### ISSUE THREAD

**Issue by lopezator** [jgm/pandoc#5800]
Pandoc version:

```
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: /Users/d.lopez/.local/share/pandoc or /Users/d.lopez/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Command used:

```
MERMAID_FILTER_FORMAT='svg' pandoc --verbose -V geometry:margin=1in --highlight-style haddock --standalone --self-contained --toc --top-level-division=chapter -f markdown -t latex -F mermaid-filter -o .artifacts/my-pdf rfc/my-pdf.md
```

Altough I think the main issue might be on `mermaid-filter` tool itself:

https://github.com/raghur/mermaid-filter/issues/37

I think pandoc should fail instead of hanging forever. 

It's a serious issue for us, because as we are using pandoc on ci, and builds hang, once `n` builds are hanging forever, ci server crashes.

**Comment by lopezator** [comment]
I add more info to reproduce the issue.

Create a markdown file containing this mermaid code block (taken from mermaid docs):

https://mermaidjs.github.io/#/flowchart?id=entity-codes-to-escape-characters

```
```mermaid
graph LR;
    A-->B;
    click A callback "Tooltip for a callback"
    click B "http://www.github.com" "This is a tooltip for a link"
```
```

Then try to run the command above.

**Comment by jgm** [comment]
This seems like an issue with the mermaid-filter (whatever that is), not with pandoc. You should report to the people who develop that filter.

**Comment by lopezator** [comment]
@jgm It indeed is.

The purpose of the issue was also to ask if pandoc shouldn't terminate/timeout if a filter is not behaving correctly as is in this case?

This way pandoc would err/fail on a bad behaving filter instead of hang (undesired behaviour IMHO).

**Comment by jgm** [comment]
Well, pandoc doesn't know whether the filter is in an infinite loop, or merely taking a long time because it's doing a big job.  We could put an arbitrary time limit on it, but what if someone wants to exceed it?

Probably better to put a timeout around the whole pandoc command, if you're worried about this sort of thing.

**Comment by lopezator** [comment]
Makes sense, thanks for the details!

**Comment by faxik** [comment]
I noted that updating the version of underlying `mermaid` to the latest git version solved most of my problems
