### ISSUE TITLE
Correctly convert back Latex "tightlist" to markdown 

### ISSUE THREAD

**Issue by Gullumluvl** [jgm/pandoc#5804]
I am trying to produce markdown _from latex_. 

However, regular lists (itemize environment) are converted to the "loose" type of list, i.e the markdown output has blank lines between each item:

    * item1
    
    * item2
    
    * item3

While I would personally always prefer the markdown compact list format, this choice is consistent with the conversion from markdown _to latex_ (where the `\tightlist` command is added to compact lists).

I therefore tried to add the `\tightlist` command to my itemize environments, but pandoc simply ignored it: it still produces loose markdown lists.

Is there a way to produce markdown compact lists _from latex_? Either by interpreting the `\tightlist` command when seen, or by simply converting all lists to compact using some command-line option?

Thanks a lot for your help.

**Comment by jgm** [comment]
You can convert all lists to compact using a lua filter, certainly.  (What you'd do is convert all Para elements inside lists to Plain elements.  This could be done with `walk_blocks`.)

**Comment by Gullumluvl** [comment]
Thank you for the suggestion. I looked at the native document output and managed to write this filter in Python using panflute (as I had done this once and also don't know lua):

```python
#!/usr/bin/env python3


"""Convert all "loose" lists to "compact" (no blank line between items in markdown)"""


from panflute import *


def prepare(doc):
    pass


def action(elem, doc):
    if isinstance(elem, (BulletList, OrderedList)):
        # TODO: check if there is a "\tightlist" command inside.
        for list_item in elem.content:
            list_item.content = [Plain(*item.content)
                                  if isinstance(item, Para) else item
                                  for item in list_item.content]
    return elem


def finalize(doc):
    pass


def main(doc=None):
    return run_filter(action,
                      prepare=prepare,
                      finalize=finalize,
                      doc=doc)


if __name__ == '__main__':
    main()
```

**Comment by Gullumluvl** [comment]
Alright, I admit the following Lua code wasn't so complicated:

```Lua
local function Para_to_Plain(item)
  return pandoc.Plain(item.c)
end

local filter = {Para=Para_to_Plain}

function BulletList(elem)
  return pandoc.walk_block(elem, filter)
end

function OrderedList(elem)
  return pandoc.walk_block(elem, filter)
end
```
I haven't tested if the resulting lists conserve their original attributes though.

I think this issue can be closed.
