### ISSUE TITLE
MacVim and Ruby after update to Catalina

### ISSUE THREAD

**Issue by marek-step** [jgm/pandoc#5806]
Hello all!

After long hesitation I upgraded to Catalina. My first task: firing up my beloved MacVim! And my first step with Catalina failed (hope there will be not more problems)!

MacVim installed with Homebrew does not find the path to Ruby or wants to find an old Version (suppose the system Ruby). I added to my ~/.zshrc the path of 

`export PATH="/usr/local/opt/ruby/bin:$PATH"`

Here some infos: 

```
which ruby 
/usr/local/opt/ruby/bin/ruby
ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
mvim --version
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib
  Referenced from: /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
[1]    17388 abort      mvim --version
brew doctor
Your system is ready to brew.
```

I reinstalled Ruby several times, and MacVim too. Also the vim is not working from my Terminal (same problem with Ruby). How to reinstall MacVim with `/usr/local/opt/ruby/bin/ruby`?

Best greetings to all

marek

**Comment by jgm** [comment]
This is the bug tracker for pandoc. It's not the right place to report this issue.

**Comment by marek-step** [comment]
Sorry!
