### ISSUE TITLE
incompatibilities with hyperref latex package

### ISSUE THREAD

**Issue by brainchild0** [jgm/pandoc#5811]
The LaTeX template contains a large number of `\usepackage` and other declarations, followed by an interpolation of `header-includes`, in which users  will load further needed packages.

One of the packages loaded by the template is *hyperref*.  

**Unfortunately, some packages will not load after hyperref is loaded.**  

Hyperref is apparently a fussy package, as documented in [ the manual][man] and expounded in [ a blog article][blog]:

> The hyperref package documentation says: “Make sure it comes last of your loaded packages”. The reason is that it redefines many LaTeX commands. It’s a rule of thumb that helps to avoid errors.

**Problems can therefore be avoided by moving the use of    hyprref  to follow after the user header (i.e. `$header-includes$`).**  

In fact, the template already does exactly so for select packages (e.g. *Load polyglossia as late as possible*):

``` latex
$for(header-includes)$
$header-includes$
$endfor$
$if(lang)$
\ifxetex
  % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[$polyglossia-lang.options$]{$polyglossia-lang.name$}
$for(polyglossia-otherlangs)$
  \setotherlanguage[$polyglossia-otherlangs.options$]{$polyglossia-otherlangs.name$}
$endfor$
\else
  \usepackage[shorthands=off,$for(babel-otherlangs)$$babel-otherlangs$,$endfor$main=$babel-lang$]{babel}
$if(babel-newcommands)$
  $babel-newcommands$
$endif$
\fi
$endif$
$if(dir)$
\ifxetex
  % Load bidi as late as possible as it modifies e.g. graphicx
  \usepackage{bidi}
\fi
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \TeXXeTstate=1
  \newcommand{\RL}[1]{\beginR #1\endR}
  \newcommand{\LR}[1]{\beginL #1\endL}
  \newenvironment{RTL}{\beginR}{\endR}
  \newenvironment{LTR}{\beginL}{\endL}
\fi
$endif$
$if(natbib)$
\usepackage[$natbiboptions$]{natbib}
\bibliographystyle{$if(biblio-style)$$biblio-style$$else$plainnat$endif$}
$endif$
$if(biblatex)$
\usepackage[$if(biblio-style)$style=$biblio-style$,$endif$$for(biblatexoptions)$$biblatexoptions$$sep$,$endfor$]{biblatex}
$for(bibliography)$
\addbibresource{$bibliography$}
$endfor$
```

[man]: https://www.tug.org/applications/hyperref/manual.html#x1-30002
[blog]: http://texblog.net/hyperref/

**Comment by jgm** [comment]
Although it's true that hyperref is fussy, moving it to after header-includes would prevent people from using any commands defined in hyperref in their header-includes.  So it's a tradeoff.  I'm tempted to say:  if you are in this situation, just use a custom template.

**Comment by brainchild0** [comment]
In a manually-written LaTeX document, an author normally puts all the `\usepackage`declaration immediately after  the declaring for the document class, followed by further definitions.  If the template could be extended to support this effect, then it would avoid fringe effects owing to Pandoc output taking a different sequence from that which has been used and refined over the history of LaTeX.

I can't say necessarily that the below is the cleanest solution, but maybe the template could process  metadata fields that look as such:

``` yaml
latex-packages:
  -
    name: somepkg
    args:  
      - a1
    optargs:
      - b1=val
```

Or maybe just  introduce a complement to `header-includes` called `package-includes`.

**Comment by brainchild0** [comment]
> Although it's true that hyperref is fussy, moving it to after header-includes would prevent people from using any commands defined in hyperref in their header-includes. So it's a tradeoff. I'm tempted to say: if you are in this situation, just use a custom template.

Turning the matter back the other way, if a package has yet to be loaded, the situation is less bleak than if it has been loaded at a point when it is already causing problems.  If loading were deferred, an ambitious user who needed to use the package could use `etoolbox` to put a hook in front of the opening of the document environment.  Or a user could simply load the package manually at the point where it is needed, and cause no problems for anyone else.

**Comment by brainchild0** [comment]
> Although it's true that hyperref is fussy, moving it to after header-includes would prevent people from using any commands defined in hyperref in their header-includes

It appears that redundant `\usepackage` declarations are harmless, so perhaps one solution is to move the automatic declaration from before the user header to after it, which still leaves open the possibility for a user to place an explicit declaration at a point in the user header where doing so is safe.

**Comment by jankap** [comment]
Hmm, now cleveref complaints, it must be loaded *after* hyperref..

`! Package cleveref Error: cleveref must be loaded after hyperref!.`
