### ISSUE TITLE
[docx to markdown] nested list not converted well

### ISSUE THREAD

**Issue by fsoedjede** [jgm/pandoc#5814]
Hello!
Thanks for this tool

I'm facing one issue and I don't know if it's a bug or if I just don't understand how it works.

## Version: 
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1

## Case 1:
I have this docx : [1a-ordered-list.docx](https://github.com/jgm/pandoc/files/3720732/1a-ordered-list.docx) - which gives me this output

```markdown
1.  Qui Lorem ipsum dolor sit amet, consectetur adipiscing elit

    a.  Lorem

    b.  Ipsum

    c.  Quis

2.  In tempus mauris et odio cursus dictum ?

3.  Vestibulum interdum enim placerat, tristique neque nec, aliquet diam

4.  Pellentesque commodo erat pulvinar diam posuere

<!-- -->
a.  Arcu

b.  Ligua

c.  Mattis

<!-- -->

5.  Maecenas ut leo id augue molestie dapibus nec ac purus
```
Command: `pandoc -f docx -t markdown --output 1b-ordered-list.md 1a-ordered-list.docx`

As you can see, the second nested list is not indented with 4 spaces as expected.

## Case 2:
I have this markdown (What I want to have from the docx) :
```markdown
1.  Qui Lorem ipsum dolor sit amet, consectetur adipiscing elit

    a.  Lorem

    b.  Ipsum

    c.  Quis

2.  In tempus mauris et odio cursus dictum ?

3.  Vestibulum interdum enim placerat, tristique neque nec, aliquet diam

4.  Pellentesque commodo erat pulvinar diam posuere

	a.  Arcu

	b.  Ligua

	c.  Mattis

5.  Maecenas ut leo id augue molestie dapibus nec ac purus
```
Command: `pandoc -f markdown -t docx --output 2b-ordered-list.docx 2a-ordered-list.md`
This markdown output this docx:  [2b-ordered-list.docx](https://github.com/jgm/pandoc/files/3720740/2b-ordered-list.docx) (looked almost same as what I used in case 1)

## Question:

In my context, I can't just use the docx generated in case 2 because anybody can submit a docx

- Am I missing something in the docx?
- Do you know if there is a way to solve my problem?

## Other issues I see can be related:
https://github.com/jgm/pandoc/issues/4324, https://github.com/jgm/pandoc/issues/4298

Regards

**Comment by mb21** [comment]
Are you sure the list in 1a-ordered-list.docx  is actually logically nested and not just visually indented in word?

**Comment by fsoedjede** [comment]
@mb21 You are right about the logically/visually intentation.
Now I have the following output in markdown where the second nested list starts with **d**

```markdown
1.  Qui Lorem ipsum dolor sit amet, consectetur adipiscing elit

    a.  Lorem

    b.  Ipsum

    c.  Quis

2.  In tempus mauris et odio cursus dictum ?

3.  Vestibulum interdum enim placerat, tristique neque nec, aliquet diam

4.  Pellentesque commodo erat pulvinar diam posuere

    d.  Acru

    e.  Ligua

    f.  Mattis

5.  Maecenas ut leo id augue molestie dapibus nec ac purus
```

**Comment by jgm** [comment]
Can you post the new docx file that gave this markdown output?
Looks like it might be a bug in the docx reader.

**Comment by fsoedjede** [comment]
[1a-ordered-list.docx](https://github.com/jgm/pandoc/files/3720815/1a-ordered-list.docx)
Here is the file

**Comment by jgm** [comment]
Looks like the same issue as #4324 (cc @jkr).
Closing this in favor of that issue.
