### ISSUE TITLE
--epub-cover-image option in md->epub failing

### ISSUE THREAD

**Issue by jeffmcneill** [jgm/pandoc#5816]
I'm using the latest (12-Oct-2019) nightly build, previous to that it was a recent release (which was fine). For some reason the --epub-cover-image is failing. The cover image IS copied into the epub, and the cover page is created, but the following html in the body is not being generated:

```
<div id="cover-image">
<img src="../media/COVER-FILENAME.jpg" alt="cover image" />
</div>
```

I can confirm that my June 12 version of Pandoc does the correct generation, but the Oct 12 version of Pandoc fails (silently) in this regard. I'm on Debian 9.

**Comment by mb21** [comment]
I cannot reproduce this... can you post exact command (minimal example) and the resulting epub?

**Comment by jeffmcneill** [comment]
Sorry, must be my template that is causing the issue (though the earlier version of Pandoc does produce the image and the latter does not, using the same template). If i generate the epub without a template the image is coming through fine. I will research further on this and report back.

**Comment by jgm** [comment]
Often templates need to be adjusted for new pandoc releases. The changelog generally indicates when this is so, but sometimes we miss something.
