### ISSUE TITLE
md->pdf markup of H1 is not consistent when TOC generated

### ISSUE THREAD

**Issue by jeffmcneill** [jgm/pandoc#5817]
Comparing the nightly build Oct 12, to the release Jun 12, there is a difference in how the H1 sections are being marked up (and interpreted) once the ToC is generated.

Minimum example markdown:

```
# Copyright
Some text

# Preface
Some text

# Chapter I
Some text

# Chapter II
Some text
```

Command line command: 

`pandoc example.md -f markdown -o test.pdf --template default.latex --toc`

[test.pdf](https://github.com/jgm/pandoc/files/3721666/test.pdf)
[test2.pdf](https://github.com/jgm/pandoc/files/3721667/test2.pdf)

Note: test2.pdf is the Jun12 pandoc, test.pdf is the oct12 pandoc. Note that this uses the `book` document class, but the same thing occurs using `scrbook`. 

I don't see any differences when comparing the epub generation in terms of ToC and header markup (though there are some additional tags present on Oct12). However, the PDFs are definitely not identical, and there are header issues which also occur, where "Contents" the ToC appears as a higher level section and is repeated in the header on left-hand header pages.

The Oct12 pandoc does fix an issue that was in the Jun12 pandoc in terms of page numbering, but it seems to break the markup/display and treats further H2s as H1s or something different.

**Comment by mb21** [comment]
Can you use `pandoc -t latex` to see what the difference is and post exactly what's bothering you with the new output?

**Comment by jgm** [comment]
I don't get the results you get when using
```
pandoc test.md -o test.pdf --toc -Vdocumentclass=book
```
(the headings in the TOC are boldface) so maybe this has something to do with some customizations you've made to `default.latex`?

**Comment by jeffmcneill** [comment]
Yes, it looks like it is the template that is the issue, though it works differently with the earlier version of Pandoc (same template). I will look further and report back.
