### ISSUE TITLE
Markdown to revealjs: pause not generated on title slide --slide-level > 1

### ISSUE THREAD

**Issue by rorlork** [jgm/pandoc#5819]
When running pandoc to convert from markdown to html to create slides for revealjs, the following

```
. . .
```

Should be converted to a pause (class fragment in reveal). It is not converted as such when `--slide-level` is set to a value higher than 1, and is instead just outputted as a paragraph with three dots.

Example code:

```
---
---
# Slide Title
Content

. . .

More Content
```

Compiling with the following will generate the unexpected result:

```
pandoc -t revealjs -s --slide-level 2 -o test.html test.md -V revealjs-url=./reveal.js
```

**Comment by luca-ing** [comment]
Confirmed in pandoc 2.9.1.1

In fact, not only on the title slide, but any slide with a pause in it.

**Comment by jgm** [comment]
```
% pandoc -t beamer --slide-level=1
# Heading

one

. . .

two

^D
\begin{frame}{Heading}
\protect\hypertarget{heading}{}
one

\pause

two
\end{frame}

% pandoc -t beamer --slide-level=2
# Heading

one

. . .

two

^D
\hypertarget{heading}{%
\section{Heading}\label{heading}}

\begin{frame}{Heading}
one

\pause

two
\end{frame}
```
As you can see, `\pause` is generated regardless of the slide level.  And I get the pause with slide level 2.  So I can't reproduce this.  Do you get different results generating a beamer fragment as above?

**Comment by jgm** [comment]
Here's the HTML output:
```
% pandoc -t revealjs --slide-level=2
# Heading

one

. . .

two
<section id="heading" class="title-slide slide level1">
<h1>Heading</h1>
<p>one</p>
<p>. . .</p>
<p>two</p>
</section>
% pandoc -t revealjs --slide-level=1
# Heading

one

. . .

two

<section id="heading" class="slide level1">
<h1>Heading</h1>
<p>one</p>
<div class="fragment">
<p>two</p>
</div>
</section>
```

**Comment by jgm** [comment]
OK I think I've got a fix.
