### ISSUE TITLE
Improve docx template to more closely follow APA or Chicago

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#5820]
As [discussed on the list](https://groups.google.com/forum/#!msg/pandoc-discuss/uVVuNNBq5iw/rGQsN5b8BAAJ) I'd like the default docx style to adhere more closely to that required by publishers. At the least I think I'd recommend:

- blockquote
      - definitely same font type;
      - definitely 0.5" left margin
      - recommend same size;
- headings:
      - no color changes, but proportionate font size changes and/or
      use of italics

I included a docx file in the thread.

**Comment by agusmba** [comment]
Disclaimer: I use a reference-doc for most of my docx conversions, as it gives me the great control on the output.

Personally I wouldn't try to deviate pandoc's default too much from Word's default.
The blockqote changes seem sensible, but I'm kind of used to having blue-colored headings as default.

**Comment by reagle** [comment]
I'm not opposed to keeping Word's default blue for headings. However, pandoc uses a light blue for a high-level heading which I do find confusing.

**Comment by agusmba** [comment]
Fair enough. I usually don't deal too much with the default template since I have my (very personalized) custom one.
