### ISSUE TITLE
table of contents is not created when converting from ipynb

### ISSUE THREAD

**Issue by grst** [jgm/pandoc#5827]
When I convert a jupyter notebook (`ipynb`) into HTML, there is no table of content created from the markdown cells. I would expect `#` headings in markdown cells to behave the same as if I converted from a `md` file to `html`. 

## Example:
Example files are in [this gist](https://gist.github.com/grst/201546299eafa91b268fb7828dbbb12f). 

```
pandoc toc_example.ipynb --output=ipynb.html -s --toc  --metadata pagetitle="test"
```
[toc_example.ipynb](https://gist.github.com/grst/201546299eafa91b268fb7828dbbb12f#file-toc_example-ipynb)

### Result: 
[ipynb.html](https://gist.github.com/grst/201546299eafa91b268fb7828dbbb12f#file-ipynb-html)
--> no table of contents. 
```html
<body>
<div class="cell markdown">
<h1 id="test-heading-1">Test Heading 1</h1>
<h2 id="test-heading-11">Test Heading 1.1</h2>
<p>Lorem ipsum...</p>
<h2 id="test-heading-12">Test Heading 1.2</h2>
<p>Lorem ipsum...</p>
</div>
<div class="cell markdown">
<h1 id="test-heading-2">Test Heading 2</h1>
<p>Lorem ipsum</p>
</div>
</body>
```

## Comparison using markdown file
If I put the markdown from the notebook cells in a `.md` file everything works as expected: 
```
pandoc toc_example.md --output=md.html -s --toc  --metadata pagetitle="test"
```
[toc_example.md](https://gist.github.com/grst/201546299eafa91b268fb7828dbbb12f#file-toc_example-md)

### Results:
[md.html](https://gist.github.com/grst/201546299eafa91b268fb7828dbbb12f#file-md-html)
--> table of contents is there
```html
<body>
<nav id="TOC" role="doc-toc">
<ul>
<li><a href="#test-heading-1">Test Heading 1</a><ul>
<li><a href="#test-heading-1.1">Test Heading 1.1</a></li>
<li><a href="#test-heading-1.2">Test Heading 1.2</a></li>
</ul></li>
<li><a href="#test-heading-2">Test Heading 2</a></li>
</ul>
</nav>
<h1 id="test-heading-1">Test Heading 1</h1>
<h2 id="test-heading-1.1">Test Heading 1.1</h2>
<p>Lorem ipsum…</p>
<h2 id="test-heading-1.2">Test Heading 1.2</h2>
<p>Lorem ipsum…</p>
<h1 id="test-heading-2">Test Heading 2</h1>
<p>Lorem ipsum</p>
</body>
```

**Comment by jgm** [comment]
I'm happy to report that this already works in the dev version of pandoc (will be 2.8).
