### ISSUE TITLE
Relative paths fails when exporting not to working directory

### ISSUE THREAD

**Issue by mitinarseny** [jgm/pandoc#5831]
Hello!

Firstly, let me thank all contributors for Pandoc, it is awesome!

I encountered a problem that I am not able to build `html` file to another build directory since images paths are relative to current working directory.  
I have a project with following structure:
```
./
├── assets/
│   ├── img.svg
├── build/
├── hw.md
```
Here are the contents of `hw.md`:
```markdown
# Example
![Example Image](assets/img.svg)
```
Then I run this command while in project root directory:
```bash
pandoc --katex --extract-media=build -s -o build/hw.html
```
Here is the result:
```
./
├── assets/
│   ├── img.svg
├── build
│   ├── ed3856bb1c49deca690f3b9b44878608160ecf9b.svg
│   ├── hw.html
├── hw.md
```
But in `build/hw.html` file it is translated like this:
```html
<img src="build/ed3856bb1c49deca690f3b9b44878608160ecf9b.svg" alt="">
```
So, when I open `build/hw.html` in browser, image is not displayed since it already is in `build/` directory and it searches for `build/build/img.svg` file.  
If not specify `--extract-media`, then it comes to this situation in `build/hw.html`:
```html
<img src="assets/img.svg" alt="">
```
And again it cannot be found and image is empty, because `build/assets/img.svg` does not exist.  
The only way to do that was to run following:
```bash
cd build && pandoc ../hw.md --katex --resource-path=.. --extract-media=. -s -o hw.html
```
and `build/hw.html` file contents:
```html
<img src="./ed3856bb1c49deca690f3b9b44878608160ecf9b.svg" alt="">
```
Is it a bug?  

P.S.: It is really inconvenient because sometimes I want to do things like traversing all `.md` files in current working directory and make `build/` directory that consists of the same structure, but all `.md` in replaced with `.html` versions. This is done with script `compile_all.sh`
```bash
#!/bin/sh
for f in $(find . -regex '\./[^.]*.md$' -type f); do
    mkdir -p $(dirname "build/$f") && pandoc "$f" --katex -s -o "./build/${f%.md}.html"
done
```
So I before it was:
```
./
├── README.md
├── compile_all.sh
└── hse
    ├── README.md
    └── cs
        ├── README.md
        └── statistics
            ├── README.md
            └── hw
                └── hw.md
```
I run `./compile_all.sh` and I get:
```
./
├── README.md
├── build
│   ├── README.html
│   └── hse
│       ├── README.html
│       └── cs
│           ├── README.html
│           └── statistics
│               ├── README.html
│               └── hw
│                   └── hw.html
├── compile_all.sh
└── hse
    ├── README.md
    └── cs
        ├── README.md
        └── statistics
            ├── README.md
            └── hw
                └── hw.md
```

**Comment by jgm** [comment]
I don't think it's a bug.  You wrote
```
![Example Image](assets/img.svg)
```
For HTML output, that means include an image link with the relative URL `assets/img.svg`.  Now it's up to you to put the output file somewhere where that relative URL makes sense.

If you plan to put the output in the `build` directory, then you could use the relative URL `../assets/img.svg`.

Note: there's absolutely no reason to use `--extract-media` if you're producing HTML from md.

**Comment by mitinarseny** [comment]
@jgm You're right! Thank you for your response and your time!
