### ISSUE TITLE
from rst to revealjs + --self-contained is not rendered correctly in Chromium

### ISSUE THREAD

**Issue by goekce** [jgm/pandoc#5834]
if I compile from .rst slideshow to revealjs using pandoc 2.7.3 with --self-contained option, the output is not rendered correctly by chromium. Firefox presents the output fine.

The slideshow and compile command are here: [s.tar.gz](https://github.com/jgm/pandoc/files/3742392/s.tar.gz)

This issue could be related to #5780

**Comment by jgm** [comment]
> This issue could be related to #5780

Can you verify this by changing the boolean attributes?

**Comment by mb21** [comment]
What do you mean with "is not rendered correctly in Chromium"? The attached file (rename to `.html`), which I generated with your command, works fine on Chrome 77 on macOS for me.


[s.txt](https://github.com/jgm/pandoc/files/3746383/s.txt)

**Comment by goekce** [comment]
@mb21 Thank you for providing your output! In my case the output is slightly different:
```
$ diff mine yours
diff s.html ../s.html 
10c10
<   <style type="text/css; charset=utf-8">
---
>   <style type="text/css">
36c36
<   <style type="text/css; charset=utf-8">
---
>   <style type="text/css">
1370c1370
<   <style type="text/css; charset=utf-8">
---
>   <style type="text/css">
```
[s.html.gz](https://github.com/jgm/pandoc/files/3746394/s.html.gz)

**Comment by mb21** [comment]
Can you try with the [nightly build](https://github.com/pandoc-extras/pandoc-nightly)?

**Comment by goekce** [comment]
Yeah, the nightly build fixes this problem. Thank you @mb21
