### ISSUE TITLE
basic LaTeX math parsing error

### ISSUE THREAD

**Issue by meereeum** [jgm/pandoc#5836]
Pandoc incorrectly parses LaTeX math when two variables occur in a row: first a variable that expands to a command, followed by a variable that expands to text.

Specifically, the output of the left variable is seemingly concatenated with the output of the right variable, producing a nonsensical command. The conversion then fails.

A minimal example....

### In markdown:
```.md
---
output: pdf_document
header-includes:
  - \newcommand{\vara}{\alpha}
  - \newcommand{\varb}{b}
---
                                                                          
$\vara \varb$
```
^ compiling with pandoc errors out with:

> Error producing PDF.
> ! Undefined control sequence.
> l.53 \(\alphab

OTOH, `$\alpha \varb$` or `$\vara b$` work just fine. (or, my current workaround: `$\vara \, \varb$`)

### Same thing in latex:
```.tex
\documentclass[11pt]{article}

\newcommand{\vara}{\alpha}
\newcommand{\varb}{b}

\begin{document}
$\vara \varb$
\end{document}
```
^ compiles just fine (in fact, no space is necessary between `\vara` and `\varb`).

### version
```
$ pandoc --version
pandoc 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

**Comment by jgm** [comment]
This also affects pandoc's conversion from latex:
```
pandoc -f latex
\newcommand{\vara}{\alpha}
\newcommand{\varb}{b}

\begin{document}
$\vara \varb$
\end{document}
^D
[WARNING] Could not convert TeX math '\alphab', rendering as TeX:
  \alphab
         ^
  unexpected eof
  expecting "%", "\\label", "\\nonumber" or whitespace
```

**Comment by meereeum** [comment]
Yes! I should have clarified—the latex version compiles successfully via pdflatex.
