### ISSUE TITLE
LaTeX writer removes float number of meta

### ISSUE THREAD

**Issue by Grandement** [jgm/pandoc#5838]
Hi,

Seems that the LaTeX writer and maybe other writers change the float number of a meta field to an integer when it's *.0
This is bad for document versioning where 1.0 would be a valid version number and 1 would look like a typo mistake. Is there a way to change this? I read the release notes and saw that the integer representation was introduced for ipynb. https://github.com/jgm/pandoc/issues/5398

I do not really understand why this should be changed for writers like LaTeX. When I remember correctly the float number worked in the past.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by Grandement** [comment]
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: C:\Users\merstlin\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

**minimal testcase:**
markdown file with yaml meta only (content.md) :
```
---
VERSION1: 1.0
VERSION2: 1.1
---
```
latex template file (template.tex) :
```
$VERSION1$

$VERSION2$
```

pandoc call:
pandoc --template=template.tex -t latex -o output.tex content.md

Output result (output.tex) :
```
1

1.1
```

**Comment by jgm** [comment]
This seems to be fixed already in the dev version!
```
 % pandoc --template my.templ -t latex -s
---
VERSION1: 1.0
VERSION2: 1.1
---
1.0

1.1
```
