### ISSUE TITLE
Issue with \linethickness macro

### ISSUE THREAD

**Issue by aubertc** [jgm/pandoc#5841]
Version:

````
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
`````

Minimal document raising an issue:

```
* * *
```

Command:

```
pandoc -o test.pdf test.md
```

Expected output: a `pdf` file containing a line across the document.

Output: error message, 
```
Error producing PDF.
! Missing number, treated as zero.
<to be read again> 
                   \protect 
l.51 ...enter}\rule{0.5\linewidth}{\linethickness}
```

The `tex` source file generated on my installation, 

```
\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}
```

cannot be compiled on my installation:
```
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.36; using libpng 1.6.36
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```

**Comment by mb21** [comment]
I think this is already fixed, can you try the [nightly build](https://github.com/pandoc-extras/pandoc-nightly)?

**Comment by aubertc** [comment]
That is correct, this issue was fixed in the nightly build.
Do you know when pandoc will benefit from this fix?

**Comment by mb21** [comment]
pandoc 2.8 should be released within the next couple of weeks or months, nothing set in stone...

**Comment by aubertc** [comment]
Thanks a lot.

A possible "hot fix" is to add

```
---
header-includes:
    - \renewcommand{\linethickness}{0.4pt}
---
```

at the very beginning of your document.

My example then becomes:

```
---
header-includes:
    - \renewcommand{\linethickness}{0.4pt}
---

***
```

and it compiles just fine to pdf, using latex.

**Comment by aubertc** [comment]
Thanks a lot.

A possible "hot fix" is to add

```
---
header-includes:
    - \renewcommand{\linethickness}{0.4pt}
---
```

at the very beginning of your document.

My example then becomes:

```
---
header-includes:
    - \renewcommand{\linethickness}{0.4pt}
---

***
```

and it compiles just fine to pdf, using latex.
