### ISSUE TITLE
Dokuwiki reader: image paths are relative to root

### ISSUE THREAD

**Issue by uuksu** [jgm/pandoc#5842]
Using pandoc version 2.7.3.

Let's say I have directory structure like this (actual directory structure from Dokuwiki):

> data
> ----- pages
> --------------- category
> -------------------- article.txt
> ----- media
> --------------- category
> -------------------- image.png

Current working directory is "data".

Article.txt has following contents:

> 
> ====== This is a header ======
> 
> This is some text written in the article.
> 
> {{:category:image.png|}}

Now when I try to make conversion from dokuwiki to for example html by running this:

> pandoc pages/category/article.txt -f dokuwiki -t html -o output.txt --resource-path=media --self-contained

I get message back saying:

> pandoc: /category/image.png: openBinaryFile: does not exist (No such file or directory)

Why pandoc is prepending the slash so that it is trying to find the file from root of the filesystem instead of from the specified resource path?

**Comment by jgm** [comment]
@link2xt may be able to explain

**Comment by link2xt** [comment]
It is an attempt to follow [namespaces](https://www.dokuwiki.org/namespaces) specification. See https://github.com/jgm/pandoc/pull/5108#issuecomment-450104433 for the discussion.

To got relative path, you can use
```
$ pandoc -f dokuwiki -t html
{{.category:image.png|}}
^D
<p><img src="category/image.png" /></p>
```

In your case, you get
```
$ pandoc -f dokuwiki -t html
{{:category:image.png|}}
^D
<p><img src="/category/image.png" /></p>
```

So if you drop resulting HTML files on some HTTP server, results are going to be correct, with `/` referring to the root of the website, not filesystem.

What should be fixed is that root should refer to `getResourcePath` when searching for media. At the same time `.` should refer to the `dirname` of the currently processed filename.

**Comment by link2xt** [comment]
In other words, generated HTML is correct, but media should be searched relative to the `getResourcePath` result if image path is absolute and relative to the (`getResourcePath` ++ dirname(filename)) if image path is relative.

@jgm Is it a problem of HTML writer or even the media reading code?

**Comment by uuksu** [comment]
I see, it makes sense now. Guess my use case was a bit different than usual as I was not going drop output to HTTP server but open it from plain file system so that did not even come to my mind that paths work that way in server.

However as @link2xt noted there is still some fixing as it should work as self-contained, right? Pandoc is just unable to find the media file. I see this happening with other targets formats as well, for example latex/pdf acts the same.

**Comment by jgm** [comment]
@link2txt Pandoc never interprets paths relative to the dirname of the currently processed file.
(Indeed, there may be no file, or there may be several, in different directories, and the parser just has access to a stream of characters, with no indication of which file each character comes from.)

**Comment by tarleb** [comment]
I believe the remaining issues are discussed in #3752. Closing in favor of that issue.
