### ISSUE TITLE
Latex Command in md file causes memory leak

### ISSUE THREAD

**Issue by nicolae-stroncea** [jgm/pandoc#5845]
**Pandoc version** pandoc 2.2.1
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.5
**OS**: Fedora 30

# How to reproduce

## test.md:
```
\newcommand{\highlight}[1]{\colorbox{yellow}{\parbox{\dimexpr\linewidth-2\fboxsep}{#1}}

Hello World
```
# Run:

```
pandoc test.md -o test.pdf
```

Result: Memory doubles in size almost every 2 seconds, reaching 15 Gigabytes of RAM on my machine very in less than a minute.

**Comment by mb21** [comment]
can you try the newest pandoc release, or even better the [nightly build](https://github.com/pandoc-extras/pandoc-nightly)?

**Comment by jgm** [comment]
I've reproduced with the latest dev version. Here's a smaller case:
```
\newcommand{\highlight}[1]{{\parbox{1em}{#1}}
```

**Comment by jgm** [comment]
Wait a sec, this isn't valid latex.
The newcommand is missing a closing `}`.
If that is added, pandoc has no trouble with it.

That's not to say we shouldn't fix this; pandoc shouldn't hang like this even on invalid input.

**Comment by jgm** [comment]
Note that the latex reader fails with an error message; the problem only arises when this tex is embedded in markdown.

**Comment by jgm** [comment]
Even shorter:
```
\newcommand{\hi}[1]{\parbox{1em}{#1}
```

**Comment by jgm** [comment]
Even shorter:
```
\parbox{1em}{#1}
```

**Comment by jgm** [comment]
Thanks for reporting his. I've finally found the problem.
