### ISSUE TITLE
group biblatex citations if prefix present

### ISSUE THREAD

**Issue by rnuske** [jgm/pandoc#5849]
Would it be possible to also group biblatex citations if there is only a simple prefix like `[cf. @a1;@a2;@a3]`?

I've seen that revision  a92e435 closing #4960 facilitates grouping of biblatex citations without pre- or suffixes. With current pandoc (2.7.3) I get the following (notation following [test/command/4960.md](https://github.com/jgm/pandoc/blob/a92e43575fb44c47263603b1dc5db9ef4f7421d3/test/command/4960.md))
```
% pandoc -t latex --biblatex
[@a1;@a2;@a3]
^D
\autocite{a1,a2,a3}
```
and
```
% pandoc -t latex --biblatex
[cf. @a1;@a2;@a3]
^D
\autocites[cf.~][]{a1}{a2}{a3}
```

The later prevents citation from being sorted automatically using `\usepackage[sortcites]{biblatex}`

Similar issues: #2065, #2091

**Comment by jgm** [comment]
That makes sense to me.

**Comment by UnkDevE** [comment]
hey, I would like to take this issue on, what should the output be for it to be able to sort automatically?

**Comment by rnuske** [comment]
That's great.
BibLaTeX needs all keys to be in one set of curly braces separated by commas to understand that they belong to one group and to thus can be sorted. So it should be like
```
\autocites[cf.~][]{a1,a2,a3}
\autocites[DAP, e.g.~][]{b1,b2,b3,b4}
```

**Comment by UnkDevE** [comment]
right, what do you do if there are multiple prefixes? do we have something like 
`\autocites[cf.~][]{a1,a2,a3}[cg.~]{b1,b2,b3}`
or could you do something like this:
`\autocites[cf.~, e.g.~][]{a1,a2,a3}{b1,b2,b3}`

**Comment by UnkDevE** [comment]
also what happens when there are prefixed citations and non prefixed citations?

**Comment by rnuske** [comment]
Multiple prefixes might be more complicated. That's why I asked for the simple case of only one prefix.

The behavior of pandoc 2.3.1 with multiple prefixes is
```
% pandoc -t latex --biblatex
[e.g. @a1;@a2;@a3; but also @b1;@b2;@b3]
^D
\autocites[e.g.][]{a1}{a2}{a3}[but also][]{b1}{b2}{b3}
```

I guess the following could be a viable solution at least it gets sorted correctly by biblatex-sortcites
```
\autocites[e.g.][]{a1,a2,a3}[but also][]{b1,b2,b3}
```

**Comment by UnkDevE** [comment]
ah cool thanks!

**Comment by rnuske** [comment]
Great news. Thank you both!
