### ISSUE TITLE
Markdown with nested lists to Latex

### ISSUE THREAD

**Issue by collinmccarthy** [jgm/pandoc#5850]
In version 2.7.3, I'm not seeing the behavior I would expect when converting nested markdown lists to Latex. Here's an example:

Markdown:
```
# Section 1
- Main point 1.1

- Main point 1.2
    - Sub point 1.2.1
    - Sub point 1.2.2

# Section 2
- Main point 2.1
    - Sub point 2.1.1
    
- Main point 2
    - Sub point 2.2.1
```

The first section gets translated to Latex the way I would like, with the outer list as a normal itemized list, and the inner list with \tightlist, as follows:
```
\section{Section 1}\label{section-1}}

\begin{itemize}
\item
  Main point 1.1
\item
  Main point 1.2

  \begin{itemize}
  \tightlist
  \item
    Sub point 1.2.1
  \item
    Sub point 1.2.2
  \end{itemize}
\end{itemize}
```

However the second section ends up having \tightlist for both the outer list and the inner list, which is not what I would like.
```
\section{Section 2}\label{section-2}}

\begin{itemize}
\tightlist % DO NOT WANT THIS 
\item
  Main point 2.1

  \begin{itemize}
  \tightlist
  \item
    Sub point 2.1.1
  \end{itemize}
\item
  Main point 2

  \begin{itemize}
  \tightlist
  \item
    Sub point 2.2.1
  \end{itemize}
\end{itemize}
```
Is this expected behavior? If so is there a workaround for me? Thank you!

**Comment by collinmccarthy** [comment]
With some trial and error I found a workaround, by always putting one blank line after the first bullet point in the list, like so:

```
# Section 2
- Main point 2.1

    - Sub point 2.1.1

- Main point 2
    - Sub point 2.2.1
```
This renders in markdown and Latex the way I would like, but I'm guessing this isn't expected behavior?

**Comment by kysko** [comment]
From [compact and loose list](https://pandoc.org/MANUAL.html#compact-and-loose-lists):

> Since “Second” is followed by a list, and not a blank line, it isn’t treated as a paragraph. The fact that the list is followed by a blank line is irrelevant. 

In your case, the "Second" mentioned above is your "Main point 2.1". And as you saw, adding a blank line resolved your problem (even if "Main point 2" isn't followed by a blank line).
This happens at the reading level (difference between Plain and Para blocks in the AST), and outputting to html for example would have given the same thing.

**Comment by jgm** [comment]
Pandoc doesn't follow commonmark here.  It does its own thing which predates the commonmark spec.  At some point in the hopefully not distant future, we'll start using a new commonmark + pandoc extensions parser I've been working on.
