### ISSUE TITLE
luafilters documentation fixes

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5851]
From ChrisD via pandoc-discuss:

(1) The example for mediabag.fetch (https://pandoc.org/lua-filters.html#mediabag-fetch) is incorrect. Fetch returns two values. The second line should read:

```
local mt, contents = pandoc.mediabag.fetch(diagram_url, ".")
```

(2) In the mediabag list example usage (https://pandoc.org/lua-filters.html#mediabag-list), the for statement is incorrect. It needs a "do", and the colon should be removed.

(3) The docs on mediabag (https://pandoc.org/lua-filters.html#module-pandoc.mediabag) say that "The media bag is used when pandoc is called with the `--extract-media` or `--standalone` option."   The media bag appears to be populated only when `--extract-media` is used, and not if `--standalone` is used without `--extract-media`.

(4) The example for replacing placeholders with metadata values (https://pandoc.org/lua-filters.html#replacing-placeholders-with-their-metadata-value) fails if the metadata includes boolean values.   For example, if your YAML includes a line such as:

```
toc: true
```

The code will fail with the error "attempt to index a boolean value". That's because boolean values are stored in the metadata table as MetaBools, which are lua booleans, not tables, and the "`v.t`" will fail. I believe this code will also fail if the metadata table contained a MetaString, though I do not know how to get a MetaString into the meta table; strings seem to be represented as MetaInlines. The code should check for MetaBools and MetaStrings, or check that `(type(v) == "table")`.

**Comment by jgm** [comment]
@tarleb any objectons to these proposed changes?

**Comment by tarleb** [comment]
On the contrary! I'll try to fix things over the weekend.

**Comment by tarleb** [comment]
I fixed 1)-3), but want to have a closer look at 4).

**Comment by jgm** [comment]
I fixed 4 so it doesn't give an error.
