### ISSUE TITLE
Wrong syntax for Textile tables

### ISSUE THREAD

**Issue by chseip** [jgm/pandoc#5852]
I really don't know why, but Pandoc produces HTML-output for tables when transforming to Textile. I've researched this but could not find anything useful (apart from https://github.com/jgm/pandoc/issues/1922 and https://github.com/jgm/pandoc/issues/22 but which unfortunately aren't really helpful).

Our Redmine instance doesn't support HTML and thus I cannot use tables converted to HTML. This is an example for correct Textile syntax for tables which Redmine accepts:

`| 1 Spalte und 1 Zeile | 2 Spalte und 1 Zeile | 3 Spalte und 1 Zeile | 4 Spalte und 1 Zeile|
|\3=.Verknüpfen von Spalte 1-3 | 4 Spalte und 2 Zeile       |`

Screenhot:
![textile_tables](https://user-images.githubusercontent.com/3062968/67289342-bea65680-f4de-11e9-8034-e9ba43d7bdb7.png)

I'm asking in context of Arc42 which are using Pandoc here for Textile output: https://github.com/arc42/arc42-generator/blob/master/subBuild.gradle#L243

I tried it with https://pandoc.org/try/ which produces HTML tables for Textile output as well.

Was the correct syntax for tables for Textile output format not considered or am I doing something wrong?

**Comment by mb21** [comment]
What's your input format and input?

The Textile writer falls back to HTML in case the table columns [have widths defined](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Textile.hs#L171), because otherwise you'd lose that information.

A work-around could be to write a lua-filter that drops those widths.

**Comment by rdmueller** [comment]
Input format is docBook

**Comment by jgm** [comment]
The textile writer falls back to HTML when it's not a "simple" table, i.e. when the table contains information about relative column widths.  (You can check this with `pandoc -t native`, the relative column widths will appear after the Table constructor.)  Typically these are tables whose cells contain block-level content (multiple paragraphs, lists, code blocks, etc.).  These tables can't be represented in native textile.

To defeat this, you could use a lua filter that sets all relative table widths to 0.

**Comment by chseip** [comment]
@jgm thanks, @rdmueller resolved it using a groovy filter (cf. https://github.com/arc42/arc42-template/issues/127).
