### ISSUE TITLE
Prelude.!!: negative index with Pandoc 2.7.3

### ISSUE THREAD

**Issue by jespercockx** [jgm/pandoc#5853]
When attempting to process the following markdown file (with embedded latex) with `pandoc --from markdown+tex_math_dollars pandoc_bug.md -o pandoc_bug.html`, I get an error `pandoc: Prelude.!!: negative index`.

File `pandoc_bug.md`:
```
$$
\newcommand\foo{\color{#0000CD}{foo}}
\foo
$$
```

I am using pandoc 2.7.3 compiled with GHC 8.6.5 and Cabal 3.0.0.0 on Linux Mint 19.1.

**Comment by jgm** [comment]
I can confirm that this is due to jgm/texmath:
```
% texmath
\newcommand\foo{\color{#0000CD}{foo}}
\foo
texmath: Prelude.!!: negative index
```

**Comment by jgm** [comment]
It's illegal tex by the way: `! Illegal parameter number in definition of \foo.`.
The `#` needs to be properly escaped.

**Comment by jgm** [comment]
texmath is failing because of this line:
```
src/Text/TeXMath/Readers/TeX/Macros.hs
237:         then args !! (argnum - 1) ++ apply args xs
```
Here argnum == 0 because `#0` is being interpreted as a macro argument.

**Comment by jespercockx** [comment]
Thanks for fixing, and thanks for pointing out the mistake in my code.
