### ISSUE TITLE
Discrepancy between pandoc and org-mode regarding empty comments

### ISSUE THREAD

**Issue by thblt** [jgm/pandoc#5856]
In the org-mode format, a line beginning with `# `  (pound sign, then a space) is treated as a comment.  Using the Org-Mode native exporter, a line containing only a pound sign (ie, matching `^#$`) is also treated as a comment. The org reader from pandoc 2.7.3 (NixOS) has a different behavior, and treats such lines as text. It reads the following input:

```
First line
#
Second line
```

as

```
First line # Second line
```
where Org understands it as:

```
First line

Second line
```

This behavior is [undocumented](https://orgmode.org/manual/Comment-lines.html), but I believe it's correct regardless, since it allows empty comment lines without trailing whitespace.

**Comment by alerque** [comment]
You might be right in suggesting that the upstream implementation is better and Pandoc should match it, but I wouldn't say it's correct to call this undocumented:

> Lines starting with zero or more whitespace characters followed by one ‘#’ and a whitespace are treated as comments and, as such, are not exported.

In this case having whitespace after the pound sign is required as part of the comment syntax itself, starting with a hash is not enough (and according to this documentation a line starting say `#foo` would not be a comment.

That leaves a bit of a conundrum: follow the documentation or follow other implementation's example?

Perhaps this is worth clarifying upstream first.

**Comment by thblt** [comment]
I may not have been clear enough: #foo is never a comment in Org.  The exception I'm referring to is `#\n`, and nothing else. I'll check in the git log and the source if this is intentional, but I think it is.

**Comment by mb21** [comment]
This is probably rooted in this line: https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/Org/BlockStarts.hs#L95

    commentLineStart = try $ skipSpaces <* string "# "

**Comment by jgm** [comment]
Yes, agreed, we probably want to change this to something like
```
commentLineStart = try $ skipSpaces >> char '#' >> notFollowedBy (satisfy (not . isSpace))
```
@tarleb what do you think?

**Comment by thblt** [comment]
I got a [partial reply from the Org mailing list](https://lists.gnu.org/archive/html/emacs-orgmode/2019-10/msg00222.html). Although it's still unclear whether org-mode's behavior is intentional, a key point is:

> 'whitespace' in emacs normally covers newline as well. 

If this is exact, it means that the exact definition of a comment is: zero or more space or tab, followed by either a space, a tab, or the end of the line.

**Comment by tarleb** [comment]
Thanks! Org-mode doesn't seem to accept any unicode spaces in that position, nor any "spacy" control char like form feed, carriage return, or tab. This should do: `followedBy (oneOf " \n")`.
