### ISSUE TITLE
Minor formatting issues with Jira output

### ISSUE THREAD

**Issue by jgneff** [jgm/pandoc#5858]
Thank you @tarleb for adding the Jira notation writer! That feature let me [automate](https://github.com/jgneff/netbeans-doc-src/blob/master/Makefile) the conversion of a long [README.md](https://github.com/jgneff/netbeans-doc-src) file in Markdown to an [issue description](https://issues.apache.org/jira/browse/NETBEANS-3296) in Jira notation. I found a few issues with the Jira output, summarized below. I'm using Pandoc version 2.7.3.

## Backslash

An extraneous backslash is inserted before an opening brace in a code block:

```ShellSession
$ printf '```\ntest {\n  one, two, three\n}\n```\n' \
    | ~/opt/pandoc-2.7.3/bin/pandoc --from=gfm --to=jira
{code}
test \{
  one, two, three
}

{code}

$
```

## Newlines

An additional newline character is added before the closing `{code}` of a code block:

```ShellSession
$ printf '```\nthis is some code\n```\n' \
    | ~/opt/pandoc-2.7.3/bin/pandoc --from=gfm --to=jira
{code}
this is some code

{code}

$
```

An additional newline character is added after a block quote:

```ShellSession
$ printf '>Block quote.\n\nNext paragraph.\n' \
    | ~/opt/pandoc-2.7.3/bin/pandoc --from=gfm --to=jira
bq. Block quote.


Next paragraph.

$
```

## Entities

The output contains entity references even for ASCII characters:

```ShellSession
$ printf '"-_\n' | ~/opt/pandoc-2.7.3/bin/pandoc --from=gfm --to=jira
&quot;&hyphen;&lowbar;

$
```

I was unable to find in the documentation the reason for converting ASCII characters to entities, nor any way to disable them.

## Wrap

It seems the option ```--wrap=preserve``` has no effect:

```ShellSession
$ printf 'Sentence one.\nSentence two.\n' \
    | ~/opt/pandoc-2.7.3/bin/pandoc --from=gfm --to=jira --wrap=preserve
Sentence one. Sentence two.

$
```

**Comment by tarleb** [comment]
Sorry for the late reply.

- The backslash issue has already been fixed in the development version.
- Newlines: already fixed for code; I'm looking at fixing the block quote issue.
- Entities: this is, for the most part, intentional: it is difficult for us to know precisely when one of these ASCII characters would be printed as-is, and when it would be treated as markup (text delimited by `-` is strike-through, `_` is for emphasized, etc). We thus take the safe route and always escape characters that could be used for markup.
- Wrap: I left this out, because newlines are not just whitespace in Jira, but can mark the end of a paragraph. Supporting `--wrap=preserve` could completely alter the document structure. What would be a typical use-case for this feature in combination with Jira?

**Comment by jgneff** [comment]
> We thus take the safe route and always escape characters that could be used for markup.

I figured it was working as designed. I had no trouble replacing the entity references with their ASCII version, anyway. My particular issue report had so many hyphens that the Jira output was difficult to read in its plain form, which is why I brought it up.

> Wrap: I left this out, because newlines are not just whitespace in Jira, but can mark the end of a paragraph. Supporting `--wrap=preserve` could completely alter the document structure. What would be a typical use-case for this feature in combination with Jira?

I like to put each sentence on a separate line so that I can better see the changes to a document under version control. I didn't realize that Jira uses the newline to indicate the end of a paragraph.

I discovered later that GitHub also honors newlines within a paragraph in issue reports, starting a new line rather than a new paragraph (see below). In a *README.md* file, though, GitHub treats a newline the same as a space character. So I may have to let go of this particular habit, anyway.

* Testing a newline character at the end of a sentence in a comment.
This is the same paragraph but on a new line.

Thanks for the quick commit!

**Comment by tarleb** [comment]
>  I didn't realize that Jira uses the newline to indicate the end of a paragraph.

Sorry, I was wrong about this. Jira *does* continue the paragraph, and your request is very reasonable.

I am making slow-but-steady progress on a separate jira-wiki-markup package, which can be used for reading and writing jira markup once it's done. My energy will be focused on getting that package out and integrated into pandoc, meaning that I won't do many fixes to the jira writer till then.

**Comment by jgneff** [comment]
Thanks for the follow-up, Albert. Now that I'm going back and forth between GitHub and Jira, I use your *pandoc* Jira writer all the time!

There is one extra thing I noticed recently. A Markdown code block without a language identifier is converted to a block surrounded by the  `{code}` notation, but that actually [defaults to Java syntax highlighting](https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=advanced) in Jira. Converting these blocks to `{noformat}` instead of `{code}` causes Jira to display them the same as GitHub—without syntax highlighting.

I tried to do that conversion myself with `sed`, but converting the ending `{code}` requires that you keep track of whether the opening `{code}` contained a language identifier. Does the *pandoc* Jira writer keep track of these pairs?

By the way, here's my latest conversion script:

```Bash
#!/bin/bash
# Converts GitHub Flavored Markdown to Jira Notation
# See: https://github.com/jgm/pandoc/issues/5858
if [ ! -f "$1" ]; then
    echo "Usage $0 file.md"
    exit 1
fi
pandoc=$HOME/opt/pandoc-2.7.3/bin/pandoc

# Makes the following changes to the Jira output:
# - Replaces entities with their ASCII characters
# - Removes the image subdirectory for image attachments
# - Removes the backslash before an opening brace (see #5858)
# - Removes extra newline characters (see #5858)
$pandoc --from=gfm --to=jira "$1" \
    | sed -e 's/&quot;/"/g' -e 's/&hyphen;/-/g' -e 's/&lowbar;/_/g' \
          -e 's/&commat;/@/g' -e 's/&ast;/*/g' -e 's/&plus;/+/g' \
    | sed -e 's/!images\//!/g' \
    | sed -e 's/ \\{/ {/' \
    | tr '\n' '\r' \
    | sed -e 's/\r{code}\r\r/{code}\r\r/g' -e 's/\r\r\r/\r\r/g' \
    | tr '\r' '\n'
```
