### ISSUE TITLE
lines using {=html} are wrapped in <p></p>

### ISSUE THREAD

**Issue by jeffmcneill** [jgm/pandoc#5860]
When using Markdown to Epub:

Code:

~~~
`<p style="text-align:center"><img src="politics/analects/images/figure-analects-02.jpg" /></p>`{=html}
~~~

I get the following in the Epub file (markdown to epub)

~~~
<p><p style="text-align:center"><img src="politics/analects/images/figure-analects-02.jpg" /></p></p>
~~~

Expected:

~~~
<p style="text-align:center"><img src="politics/analects/images/figure-analects-02.jpg" /></p>
~~~

The main issue here is that I need to style the paragraph text to get the image to center within it.

I can't use a raw code block, as with Latex output (using the same source for md->pdf), I get the raw text (not html). I have an alternate {=latex} line for the same thing, in latex syntax. 

It does seem that, unless there is an alternate way to put a style or class header on an implicitly generated <p>, the behavior here is not as expected (that is, any {=html} should be interpreted as literal and not itself be formated).

Any thoughts?

**Comment by mb21** [comment]
Markdown also supports raw HTML without the generic raw attributes... just write:

    <p style="text-align:center"><img src="politics/analects/images/figure-analects-02.jpg" /></p>

**Comment by jgm** [comment]
As noted on pandoc-discuss, you're using the syntax to insert inline-level HTML, so it's assumed to be an inline-level tag. You want to use the syntax for block-level HTML.  Or just do what @mb21 suggests.

**Comment by jeffmcneill** [comment]
Hi,

I understand this syntax, however when I try and generate a PDF I get a left-aligned image or text. It is not ignored in MD->PDF, though the styling is. Yes, definitely there are no extra <p></p>s involved.

When I use the {=html} syntax, the MD->PDF does ignore this (and I can use {=latex} syntax to properly insert as needed on the latex side). However, I get the extra <p></p>s. 

I do understand this is about inline and block, but I do not seem to be able to have a single source that can properly align text or images from markdown/latex, and produce both epub and pdf.

**Comment by jgm** [comment]
That's because (unless you use the explicit raw attribute syntax `{=html}`), only the tags are parsed as raw HTML; the text in between in parsed as regular text.  If you want to ignore it all in non-HTML formats, use a raw attribute *block*:

````
``` {=html}
<p style="text-align:center"><img etc.></p>
```

**Comment by jgm** [comment]
To get a better sense of what is going on, you can use `pandoc -t native` to see the intermediate representation produced by the reader.

**Comment by jeffmcneill** [comment]
Ah, got it. Thanks, that works.
