### ISSUE TITLE
Recent updates in TeXLive and "grffile does not work with LuaTeX any more"

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#5862]
There is an issue with `grffile` package used by the default LaTeX template in recent TeXLive 2019 as of 2019-10-28: ho-tex/oberdiek#73. This issue manifests when images are included LaTeX document:

```
LaTeX Warning: File `example-image-a.pdf' not found on input line 5.

! error:  (file """example-image-a".pdf) (pdf backend): cannot find image file 
'"""example-image-a".pdf'
!  ==> Fatal error occurred, no output PDF file produced!
```

It seems is possible to avoid it by removing `grffile` from the template. I am not sure if we need `grffile` for anything so I am not attaching a patch. Consider this issue only as an attempt to raise awareness of this issue.

**Comment by jgm** [comment]
Dup of #5848 -- why don't you add the information to that issue that the problem arises for lualatex as well as xelatex, and we'll close this?
