### ISSUE TITLE
Unable to find custom Lua writer with --standalone 

### ISSUE THREAD

**Issue by mitinarseny** [jgm/pandoc#5866]
When passing `--standalone` option and `-t sample.lua` (`sample.lua` exists in current working directory) it writes an error:
```
$ ls
sample.lua   hw.md

$ pandoc --standalone -t sample.lua hw.md
Could not find data file /usr/local/Cellar/pandoc/2.7.3/share/x86_64-osx-ghc-8.6.5/pandoc-2.7.3/data/templates/default.sample.lua
```
The same result will be even if pass `--data-dir=.` or  `--data-dir=$(pwd)`.
But it works normally if remove `--standalone` option. 

It seems like `--standalone` is an option for default writers and it forces to look for a writer in a specific folder. Is it a small bug? If not, it should better be documented that `--standalone` forces a default writer and if passing `-t <format>` option, than it will look for given format template.

Another question, why `-t <format>` looks for a **template** and **not writer** in this case?

BTW: Is it possible to get cli writer flags (e.g. `--standalone`, `--number-sections`, etc...) inside a custom writer written in Lua?

P.S.: If you're curious, why I need this, read the discussion in #5867.

## Info
I'm working on macOS Catalina
```
$ pandoc -v
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: /Users/mitinarseny/.local/share/pandoc or /Users/mitinarseny/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by jgm** [comment]
The effect of `--standalone` is to use a template which provides an appropriate header and footer.
The default templates are named using the scheme `default.FORMAT`, e.g. `default.html5`.
Here it is looking for `default.sample.lua` because your format is (custom) `sample.lua`.
If you put a template file named `default.sample.lua` in `$USER_DATA_DIR/data/templates`, then pandoc will use it when you use this writer with `--standalone`.  Alternatively, you can just set up yoru custom writer so that it produces the necessary header and footer.  (You'd put this in the function `Doc`.)

**Comment by mitinarseny** [comment]
Okay, so maybe include this in documentation then?
> it should better be documented that `--standalone` forces a default writer and if passing `-t <format>` option, than it will look for given format template.

**Comment by jgm** [comment]
The manual already contains this:

```
When the `-s/--standalone` option is used, pandoc uses a template to
add header and footer material that is needed for a self-standing
document.  To see the default template that is used, just type

    pandoc -D *FORMAT*

where *FORMAT* is the name of the output format. A custom template
can be specified using the `--template` option.  You can also override
the system default templates for a given output format *FORMAT*
by putting a file `templates/default.*FORMAT*` in the user data
directory (see `--data-dir`, above). *Exceptions:*

- For `odt` output, customize the `default.opendocument`
  template.
- For `pdf` output, customize the `default.latex` template
  (or the `default.context` template, if you use `-t context`,
  or the `default.ms` template, if you use `-t ms`, or the
  `default.html` template, if you use `-t html`).
- `docx` and `pptx` have no template (however, you can use
  `--reference-doc` to customize the output).
```

I suppose the only thing that's missing here is an explicit mention of custom writers among the exceptions.
