### ISSUE TITLE
streamDecodeUtf8With: Invalid UTF-8 stream when convert from Markdown to PDF

### ISSUE THREAD

**Issue by vhquang** [jgm/pandoc#5872]
The issue can be a duplicate of #5600 , but I want to provide separate reproduce setup.
The issue (hopefully) can be reproduce at:
https://github.com/vhquang/pandoc-utf8-issue

```
$ pandoc test.md -o test.pdf
# [WARNING] Missing character: pandoc: Cannot decode byte '\xb9': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream
```

However, saving intermediate file is no problem, and produce the file I expect:
```
pandoc test.md -so test.tex && pandoc test.tex -o test.pdf
```
Also, running `pdflatex` on the intermediate .tex file to produce the PDF file is also fine. So I am not sure if this is something similar to #4200 (which relates to `xelatex`).

Both the input file and the Tex `.cls` file are saved as UTF-8, and trying to (find non-UTF8 character)[1] return negative:
```
grep -axv '.*' test.md acmart.cls 
```

System info:
```
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Ubuntu 18.04
GNOME Terminal 3.28.2, with Encoding set to UTF-8
```
I have another computer which runs Ubuntu 16.04, with the same version of pandoc, but has TexLive installed over a year ago. And I cannot reproduce the issue (aka: it works). So, it could be the issue from external dependencies. But without more output from pandoc, I am clueless on what the issue could possibly be. If any extra info that could be helpful, please let me know.

[1]: https://unix.stackexchange.com/a/175096/151098

**Comment by jgm** [comment]
Thanks for the complete issue report!
I can reproduce it, and I see what is happening.  The log file produced by compiling the intermediate tex file (which is fine) contains the line
```
Missing character: There is no ¹ in font lmsy7!
```
and this file is not UTF-8 encoded (but ISO-8859).
It's this superscript 1 character that is causing the problem -- it's B9 in the latin1 encoding.
Pandoc tries to read the log file to see if there were any problems, and seems to be assuming wrongly that the file is UTF-8 encoded.

**Comment by jgm** [comment]
The culprit:
```haskell
  let warnings = [ addCodePoint (UTF8.toStringLazy (BC.drop 19 l))
                 | l <- ls
                 , isMissingCharacterWarning l
                 ]
```
Here we try to convert the message from the log file to a string, so it can be displayed using the usual error routine, and this assumes it's UTF-8 encoded.

**Comment by vhquang** [comment]
Thanks for a super fast fix!
This makes sense. My other system has the same version of Pandoc, but has older version of `pdflatex` (3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)). And running Pandoc on that system is "fine", as there is no warning about the missing character.

I am curious. Why does running pandoc on the .tex file work `pandoc test.tex -o test.pdf` ? Are we skipping the pdflatex log if the input is .tex file?

**Comment by jgm** [comment]
the tex file is UTF-8 encoded.  It's just the log file produced by pdflatex that isn't.
Pandoc only looks at the former.

**Comment by vhquang** [comment]
For the sake of completeness and for the benefit of other people having the exact same issue as mine, the root cause of the "Missing font" is because the particular Tex class that I used (ACM, `acmart.cls`) specifically recommends using font `libertine` instead of `lmodern` (Latin Modern), which is used as default in pandoc. The character is in Libertine, but not in Latin Modern. So, beside the code fix done by **jgm**, the proper fix is to tell pandoc which font it needs to use:
```
---
documentclass: acmart
fontfamily: libertine
---
```
