### ISSUE TITLE
Unable to resolve dependencies on macOS Catalina

### ISSUE THREAD

**Issue by remko** [jgm/pandoc#5874]
I'm trying to build pandoc with Homebrew on macOS catalina (GHC 8.8.1).

I get the following build problem:

```cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.7.3 (user goal)
[__1] next goal: haddock-library (dependency of pandoc)
[__1] rejecting: haddock-library-1.8.0 (conflict: pandoc =>
haddock-library>=1.7 && <1.8)
[__1] trying: haddock-library-1.7.0
[__2] next goal: base (dependency of pandoc)
[__2] rejecting: base-4.13.0.0/installed-4.1... (conflict: haddock-library =>
base>=4.5 && <4.13)
[__2] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__2] fail (backjumping, conflict set: base, haddock-library, pandoc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: pandoc, base, haddock-library
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

Can this be resolved?

**Comment by mb21** [comment]
Using stack or cabal? Which version?

**Comment by remko** [comment]
Sorry, i forgot to include one line. The homebrew formula seems to use cabal.
My cabal version is 3.0.0.0.

**Comment by mb21** [comment]
So you're saying this was using `brew install pandoc`? That should actually include a binary and not build from source... but maybe the people maintaining that haven't gotten around to releasing a version for catalina...?

**Comment by remko** [comment]
Right, this was `brew install pandoc`.

Looking at the formula, there indeed isn't a catalina binary version yet. There was an issue with GHC on Catalina that was only fixed today in homebrew, which won't have helped.

I wasn't sure who was responsible for creating these binaries. However, given the dependency problem, whoever is in charge will also run into this?

**Comment by mb21** [comment]
I think we currently only have a problem with GHC 8.8.1, but @jgm will know more... (see https://github.com/jgm/pandoc/commit/62dc2f893ec21f3daa2e9c78eb6392698145d204)

**Comment by jgm** [comment]
That's right, 2.7.3 won't build with ghc 8.8, which is apparently what homebrew has installed for you.  The next release, 2.8, will.  For now you could use a binary package from our releases page.
