### ISSUE TITLE
Support metadata directory in data directory

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#5876]
Since both templates and defaults can be placed in their respective `$DATA_DIR/templates/` and `$DATA_DIR/defaults/` why not also metadata files in `$DATA_DIR/metadata/`?

**Comment by tarleb** [comment]
Seems like a good idea! Should not be too difficult either, so I'm marking it as a "good first issue".

**Comment by evenbrenden** [comment]
Hi, is anyone working on this? If not I'd like to take a stab at it.
