### ISSUE TITLE
Support both arrays and singletons wherever reasonable in default files

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#5877]
Some default file options like `metadata-file(s)` take both a plural version with a list and a singular version with a single value, but some like `input-files` do not.  That's confusing.

Also it should probably be OK to use both the singular and the plural version of the key with both a list and a single value, since it is very easy to forget to change the key when you change a single value into a list.  Since the code probably checks what kind of value it is anyway it shouldn't be picky about the form of the key.

**Comment by jgm** [comment]
As far as I can see, the only thing that needs changing is `input-files` (allow singular).
