### ISSUE TITLE
Adjust styles in reference.docx

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#5883]
Currently block quotes come out in a different font (sans-serif).  That is undesirable.  More "vanilla" behavior would be

-  same typeface
- indented (left margin 0.5"?)
- either same size or possibly smaller

Also consider changing heading styles.  Currently we use styles that are similar to the Word defaults, but these are quirky.  The color changes between level 1 and 2+.  Levels 2 and 3 are almost the same size. etc.

**Comment by reagle** [comment]
Duplicate of #5820?

**Comment by jgm** [comment]
Oh, I missed that somehow! Sorry.
