### ISSUE TITLE
Cannot convert an equation with tag to docx file

### ISSUE THREAD

**Issue by s1291** [jgm/pandoc#5886]
I am using pandoc 2.7.3.
With the following basic markdown file:
```
some text

$$
\cos^2{x} + \sin^2{x} = 1 \tag{1}
$$

another text
```

When I convert it to pdf it works fine. But it fails when I try to convert it to docx or powerpoint file format

```
pandoc file.md -o file.docx
```
I get the following error:

```
[WARNING] Could not convert TeX math '
  \cos^2{x} + \sin^2{x} = 1 \tag{1}
  ', rendering as TeX:
  
                     ^
  unexpected "{"
  expecting "%", "\\label", "\\nonumber" or whitespace
```
When I remove `\tag{1}` it converts successfully.

Thanks

**Comment by jgm** [comment]
Workaround: add to your markdown file
```
\renewcommand{\tag}[1]{}
```
