### ISSUE TITLE
defaults file quirks

### ISSUE THREAD

**Issue by brainchild0** [jgm/pandoc#5888]
Consider defaults file:

```
to: latex
writer: html
standalone: true
input-files: []
```

When used, I might expect Pandoc to do both of the following:
- Complain that `to` and `writer` fields are redundant.  Instead it ignores `writer`.
- Process empty input set, then exit.  Instead it waits for standard input.

**Comment by jgm** [comment]
I think the interpretation of
```
input-files: []
```
could go either way.  Some users might naturally expect that setting `input-files` to `[]` has exactly the same effect as omitting any file arguments on the command line. That is the present behavior.  I can also see some users expecting the behavior you were.  What real-world cases do you have in mind where you'd want pandoc to process empty input?

**Comment by brainchild0** [comment]
It's a stretch to consider that someone would want empty input for some main sequence of workflow. Perhaps someone might try to test the effect is something else were failing for unknown causes. The main reason I would favor the base case not being treated as a special case is that in a scripted or otherwise automated environment the result is more likely to match the assumptions of the calling mechanism if the empty set is handled simply as the trivial case.

I place reduced emphasis on such a strong parallel to the CLI handling. Files omitted on the command line meaning that standard input is read is a familiar metaphor  Mostly these reasons relate to what is natural for someone to write when working in the interactive command prompt, not about the way one thinks of the data structure that would be constructed internal to application as a result. The strict interpretation of the CLI metapor translates poorly to the YAML data block.

However, it is a good idea that an explicit value can be given that has the same affect as the field being omitted.  I suppose one option would be that Boolean false represents standard input, though there are good reasons to dislike this idea.

I think my single largest problem with the current behavior is that if I needed to put some value that I thought might make standard input get read, then an empty list would be the last thing that would occur to me.  

Also, would there be a way to concatenate standard input with real files?

By the way, the reason I originally used this form was to create a minimal test case for the `to`/`writer` validation problem that I had posted on an earlier topic before it was closed.  I suppose that use is plainly not "real word", but it's still real.

**Comment by jgm** [comment]
> I think my single largest problem with the current behavior is that if I needed to put some value that I thought might make standard input get read, then an empty list would be the last thing that would occur to me.

Understood. But others may think differently.  To them it may seem natural to think, "well, if I want stdin, I leave the arguments empty on the command line, so I'll write `[]`."  You're right that the YAML format could diverge in various ways from the command line, but there are advantages to keeping it as similar as possible, as it allows people to use one mental model instead of two.

> Also, would there be a way to concatenate standard input with real files?

That's an interesting question.  Currently, you can do things like
```
input-files:
 - my.txt
 - "-"
```
which concatenates my.txt with stdin.  I'm not sure that should be allowed, though on the command line you can do
```
pandoc my.txt /dev/stdin
```
You can even do
```
input-files:
 - "-"
 - "-"
```
which doesn't really work.

One way to exclude these things would be to keep the convention that
```
input-files: []
```
means input from stdin, and remove the convention that `-` = stdin.

**Comment by brainchild0** [comment]
> Understood. But others may think differently. To them it may seem natural to think, "well, if I want stdin, I leave the arguments empty on the command line, so I'll write `[]`." You're right that the YAML format could diverge in various ways from the command line, but there are advantages to keeping it as similar as possible, as it allows people to use one mental model instead of two.

While being misguided to dismiss as impossible the case you consider, it might be equally unwise to fail to weigh it against a fuller breadth of possibilities. The effect of such a design would be that the YAML structure is in some sense held hostage to the command-line constraints. Whether in some cases the importation of metaphors is viable, surely it is not so in all cases. Thus, consistent application of patterns demands adoption of patterns suitable for the context across which is to be applied.

As you correctly note I am not in the mindset of one who might make the particular extrapolation you imagine.

But turning the same issue to show the other side, suppose a user is creating a YAML structure before having learned about the command-line interface, or indeed any command-line interface.  Should understanding of YAML patterns not be enough to build the structure correctly?  Would anyone in this circumstance be imagined to guess the particular design that carries the unnecessary legacy of the command-line interface?  Why give privilege to one side versus another when both might be fully equal for their own merit? Why not adopt designs appropriate for the contexts they inhabit, as long as we are free to do so?  

> 
> > Also, would there be a way to concatenate standard input with real files?
> 
> That's an interesting question. Currently, you can do things like
> 
> ```
> input-files:
>  - my.txt
>  - "-"
> ```
> 
> which concatenates my.txt with stdin. I'm not sure that should be allowed

It think it should not, largely for the reasons above.  I add that the command line offers tools to handle cases in which the file name is `-`, which is allowed by the file system, whereas in this context no such tools would be available. 

 though on the command line you can do
> 
> ```
> pandoc my.txt /dev/stdin
> ```
> 

On some systems, yes, but this use will not port. I would hope that the features of a file read by Pandoc for this purpose are portable, even if it is unavoidable that some  users might include a path to a special system file.


> You can even do
> 
> ```
> input-files:
>  - "-"
>  - "-"
> ```
> 
> which doesn't really work.

No, it should be caught as an error that prompts an abnormal exit as soon as detected.

**Comment by brainchild0** [comment]
You might find that standard input has limited or no practical use in the current context.  Choosing to avoid support completely avoids the issue of representation.

**Comment by jgm** [comment]
I'm pretty convinced that we shouldn't support the `-` synonym for `stdin`.
Still not sure what I think about the best interpretation of `input-files: []`.
One application for "empty input" might be filling a template with variables specified in a defaults file.

**Comment by brainchild0** [comment]
Is support for standard input needed in this context?

**Comment by alerque** [comment]
@jgm Why not use `-` from the command line? I could maybe see that for inside a YAML data array, but from the command line it's very standard usage and expected behavior for anything that accepts a filename.

**Comment by brainchild0** [comment]
I didn't notice that part of the comment.  I also don't see the rationale for such an alteration to the CLI.  As everyone agrees this metaphor is common for CLI.  However support for `--` as in basic POSIX tools would be appropriate.  Is it supported currently?  The basic intention has always been to mimic `cat`, right?

**Comment by jgm** [comment]
OK, I'm happy to keep `-` for the command line.

And yes, `--` is supported.  You can try `pandoc -- -s` for example, and you'll get

    -s: openBinaryFile: does not exist

**Comment by brainchild0** [comment]
I think that's a good choice.

Not to beat a dead horse, but suppose that another application invokes Pandoc using a defaults YAML block constructed from its own internal data structures.  If one such structure is a list, then that list being empty,  if this case is  special, would change completely  the behavior of Pandoc.  Such special treatment is likely not to be considered by the authors of the other application.  Rather, from such a programmatic paradigm it is natural to consider that the difference between lists of no elements versus one element is as small as the difference for the cases of one versus two elements. If Pandoc enters into a blocking mode to wait for data from standard input, then the logic of the calling application is disrupted. Even in the best case, that in which the application correctly   handles the special case, then the internal logic of the application is complicated by the choice.  I'm not sure that the command-line interface is all that is needed to be considered in this question.

**Comment by jgm** [comment]
I implemented your suggestion for `input-files`. I'm not going to worry for now about the use of `to` and `writer` (there are a number of similar cases).

**Comment by brainchild0** [comment]
That's fine.  Just curious, are the similar cases currently reported explicitly?  Should a general issue be opened?
