### ISSUE TITLE
xelatex:  Images Missing

### ISSUE THREAD

**Issue by patrickbucher** [jgm/pandoc#5895]
When I use Pandoc with the `--pdf-engine=xelatex` flag, no images show up in the PDF, whereas the images show up without that option. In general, `xelatex` works on my setup; images show up in PDFs generated without Pandoc.

I created an [example](https://github.com/patrickbucher/pandoc-bugreport); just clone the repo and run `make`. Two PDFs will be generated, one with `xelatex` and images missing.

I'm using pandoc 2.7.3 from Arch Linux. See the `*-version` files in the repo for other versioning information (`latex`, `xelatex`).

**Comment by jgm** [comment]
Dup of #5848 -- to make this work you'll need to use a custom template that removes `grffile`.  Some other workarounds are also mentioned in that issue.
It will be fixed in the upcoming 2.8 release.
