### ISSUE TITLE
[Feature request] Rotate included images in output

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/pandoc#5897]
I'm wondering if it's easily possible to implement the rotation of images (by 90, 180 and 270 degrees) in some or all output formats generated from markdown and make it simple for users by extending the list of attributes (f.e. with `rotate=XXX`) :

     ![](some.jpg){ width=66% rotate=270 }

**Comment by alerque** [comment]
I would handle this with a Lua filter that actually rotates the image during conversion so all output formats can play.

**Comment by jgm** [comment]
Yes, I agree, a filter is the best approach.
