### ISSUE TITLE
Backslashed in MD file are interpreted as escape sequences

### ISSUE THREAD

**Issue by raffaem** [jgm/pandoc#5901]
Input MD file 'doc.md':

> The file can be found under: "\data\"

pandoc command

`pandoc.exe doc.md -o doc.pdf`

Error message:
```
Error producing PDF.
! Undefined control sequence.
l.52 "\data
```
pandoc version: 2.7.3

**Comment by mb21** [comment]
You could either write:

    The file can be found under: `\data`

or disabled the [raw_tex extension](https://pandoc.org/MANUAL.html#raw-htmltex).

**Comment by alerque** [comment]
As @mb21 suggested disabling the `raw_tex` extension on your input end is the right way to to this — if you don't also need raw TeX. If for some reason you do the backticks are a way to avoid this, but the output in a code block may not be desirable.

You can also escape the backslash to inform Pandoc to treat it literally:

```markdown
The file can be found under: "\\data"
```
