### ISSUE TITLE
A given reference file is ignored when I try to covert a markdown file into docx.

### ISSUE THREAD

**Issue by tan-wei** [jgm/pandoc#5902]
Version: pandoc 2.7.3
OS: Windows 10

Firstly, I get a template file named `custom_reference.docx` from `--print-default-data-file=reference.docx` option:
```console
pandoc -o custom_reference.docx --print-default-data-file=reference.docx
```
Then I open it with Word 2016, just change the color of titles of every level into black and save (Word will complain compatibility check warning, more information can be found [here](https://support.office.com/en-us/article/compatibility-changes-between-versions-cb713c85-3145-4e83-a8b6-1e3227a4c059?ocmsassetID=HA010370116&CorrelationId=b7e71117-ff84-4574-b18b-94c96a9efb00&ui=en-US&rs=en-US&ad=US)). If I click `continue`, the changed template file is saved. 
![图片](https://user-images.githubusercontent.com/28227509/68676511-2b1fed00-0595-11ea-9315-624e8e67a01c.png)

However, it seems that pandoc will ignore the changement in the template file (the modification of the color of titles), still output a docx file with default stlye:
```console
pandoc --reference-doc custom_reference.docx -o demo.docx demo.md
```
![图片](https://user-images.githubusercontent.com/28227509/68676474-16dbf000-0595-11ea-85de-69561ece966d.png)

The input markdown file 'demo.md' is here:
```markdown
This is the title
=================


Chapter 1 Test
--------------

This is contents of chapter 1
I will try some gems

### Some small chapter

balbalbla...


### Another small chapter

balbalbla...

Chapter 2 Tables
----------------

I'll add a table below:

|unnecessarily|lengthy|sentence|
|-:|:-:|:-|
|the|quick|brown|
|fox|jumps|over|
|the|lazy|dog|
```

BTW, Libreoffice is tried, too. However, I get the same result.

**Comment by kysko** [comment]
Try with `--reference-doc=custom_reference.docx`.
When using `--` in options, use `=`; for single dash versions of options, separate with space.
e.g.  `-c mystyles.css` vs `--css=mystyles.css`

**Comment by tan-wei** [comment]
@kysko Thanks for your advice.
`--reference-doc=custom_reference.docx` does not work, either. I think it is not the problem, when I give a filename which does not exist, `pandoc` will complain no such file:
```console
$ pandoc --reference-doc custom_reference1.docx -o demo.docx demo.md
pandoc: custom_reference1.docx: openBinaryFile: does not exist (No such file or directory)
```
So I think it is not the problem.

**Comment by jgm** [comment]
You need to actually change the heading styles. Did you do that? It isn't enough to select the headings in the sample doc and change their color to black.

**Comment by tan-wei** [comment]
@jgm 
Got it. Forgive me I misunderstand the document. After I change the **styles**, the output successfully changed correspondingly. Thanks very much.

**Comment by Asxer** [comment]
Excuse me, but I don't get it. In the documentation, I see the following:

```
To produce a custom reference.docx, first get a copy of the default reference.docx: pandoc -o custom-reference.docx --print-default-data-file reference.docx. Then open custom-reference.docx in Word, modify the styles as you wish, and save the file.
```

I opened this file in LibreOffice, modified the colors of the heading, and nothing changed. What styles are you talking about?

**Comment by Asxer** [comment]
It looks like I get it. 
It is located in the top menu of the Office, not in the document itself. 

```
Styles->Manage Styles
```

**Comment by iandol** [comment]
Useful documentation from @rnwst -- https://rnwest.engineer/auto-generate-docx-with-pandoc/#how-to-edit-styles
