### ISSUE TITLE
Way to specify HTML tags that should be treated as block-level

### ISSUE THREAD

**Issue by amundo** [jgm/pandoc#5903]
In #2960 and #3420 difficulties with determining whether a given custom element should be treated as block-level or inline resulted in some misparsing where raw HTML input like this in a markdown file:

```html
<a-custom-element>
    <p>*test*</p>
</a-custom-element>
```

Would result in output like this:

```html
<a-custom-element>
<p>
<em>test</em>
</p>
<p></a-custom-element></p>
```

@jgm explained that this was due to the fact that the list of block-level elements is hard-coded, and since custom elements have unspecified block or inline flow, it’s not clear what pandoc should do. 

So my question is: would it be possible to add functionality which would allow passing in a list of custom elements which should be treated the same as the hard-coded list of  block-level level elements via a command line argument? Something like:

$ cat something.md | pandoc -f markdown -t html --block-level-elements="a-custom-element another-custom-element" 

PS, Thanks for pandoc.

**Comment by jgm** [comment]
You can force interpretation as an HTML block using the raw attribute syntax:
````
```{=html}
<a-custom-element>
```
*test*
```{=html}
</a-custom-element>
```
````

**Comment by amundo** [comment]
So in the case where I want to have a custom element which has its own internal elements which _also_ shouldn't be interpreted by pandoc, I just wrap the whole thing:

```{=html}
<a-custom-element>
<strong>test</strong>
</a-custom-element>
```

This is just what I needed, thanks! I didn't read the manual section on the [generic raw attribute](https://pandoc.org/MANUAL.html#generic-raw-attribute) carefully enough.
