### ISSUE TITLE
header-includes support dropped

### ISSUE THREAD

**Issue by brainchild0** [jgm/pandoc#5904]
Commit 20309691c38eff32b16c0cb734ecc350caaba220 drops support for  `header-includes`?:

```
echo | pandoc -s -t latex --variable header-includes:'WHERE AM I?' | grep WHERE
```

Can anyone reproduce?  Unit tests pass but the above is definitely different from the previous commit.

**Comment by jgm** [comment]
Not intentionally.  I see the problem, though.

**Comment by brainchild0** [comment]
With the new support for list aggregation, is the complete header generated from  `header-includes`and `include-in-headers` by processing all values of one type, then all of the other; or rather each or the other as they appear in the sequence?

**Comment by jgm** [comment]
They don't combine smoothly yet at this point:
```
% echo | pandoc -s -t markdown -H test/B.txt --variable header-includes:'WHERE AM I?' -H test/A.txt
here is b

this is a
```
I need to look into why.

**Comment by brainchild0** [comment]
I guess the special cases will need to be teased out.

This specific category of abstraction, combining sets of options that widely vary in type and  purposes, into a single set, while preserving the intended function of each value, tends to make me nervous because of bad experiences when it was not approached in an adequately nuanced way.
