### ISSUE TITLE
Get line number of element being filtered in Lua filters

### ISSUE THREAD

**Issue by mitinarseny** [jgm/pandoc#5907]
It's a feature request to provide opportunity to get the line number of element that is being filtered with Lua filters. It would be useful to have `sourceLineNumber` field in each element inside pandoc's AST as if you want to throw an error while applying filter, it's hard to guess where is the block which caused an error. Of course, It can be done by assigning id to every block that you write:
````markdown
```{#errorBlock filterAttr="unsupported"}
something here
```
````
And in the filter:
```lua
function CodeBlock(block)
  if block.attributes['filterAttr'] ~= 'supported' then
    error('An error while processing block'
      .. ((block.identifier ~= '' and (' #' .. block.identifier)) or '')
      .. ': unsupported \'filterAttr\' value \'' .. block.attributes['filterAttr'] .. '\'')
  end
  -- something here with filterAttr
end
```
That would give an error:
```
An error while processing block #errorBlock: unsupported 'filterAttr' value 'unsupported'
```
But what if end user do not want to give each block an id?

Moreover, it would be even better if i can leave it to pandoc and just throw an error:
```lua
function CodeBlock(block)
  if block.attributes['filterAttr'] ~= 'supported' then
    error('unsupported \'filterAttr\' value \'' .. block.attributes['filterAttr'] .. '\'')
  end
  -- something here with filterAttr
end
```
And pandoc would handle errors and write id of element and line number when element starts:
```
An error while processing CodeBlock #errorBlock on line 1: unsupported 'filterAttr' value 'unsupported'
```
Or if id is empty:
```
An error while processing CodeBlock on line 1: unsupported 'filterAttr' value 'unsupported'
```

**Comment by tarleb** [comment]
Line numbers in elements are the central part of #4565, so I'm closing in favor of that issue.

Error messages could certainly be improved in general. Would you open a new issue for that?
