### ISSUE TITLE
Allow alphabetic lists to go beyond "z" ("aa", "ab", etc.)

### ISSUE THREAD

**Issue by jakov** [jgm/pandoc#591]
Alpha lists dont go beyond "z" in pandoc, even though in HTML lists 
continue with "aa", "ab", "ac", etc. There's a javascript way of 
converting those to integers [at 
stackoverflow](http://stackoverflow.com/a/8604591). 

Then however also 
e.g. "iv" would get ambiguous, but with only a few exceptions the roman 
numeral has a lower value and is therefore more probable. Thus, "i", "v" and "x" should default to roman. "l", "c", "d" and "m" should be the exceptions that default to alphabetic. All higher letter combi ations that can be interpreted as roman numerals should default to roman numerals.

**Comment by jgm** [comment]
I'm going to close this, as it opens up lots of ambiguities.  (A word followed by a period might be treated as a list.)
