### ISSUE TITLE
Creating handout example not working with figure

### ISSUE THREAD

**Issue by tamas-ferenci** [jgm/pandoc#5911]
The 'Creating a handout from a paper' from the lua filter [examples](https://pandoc.org/lua-filters.html#creating-a-handout-from-a-paper) states that it extracts figures (among others) from the document.

Yet, the following example:

```
---
title: "Untitled"
author: "Author"
---

## Example

![](tempmarkdown_files/figure-html/pressure-1.png)<!-- -->

Example.
```

produces this output with the cited filter (`pandoc -f markdown -t beamer tempmarkdown.md --lua-filter handoutfilter.lua`):

```
\hypertarget{example}{%
\subsection{Example}\label{example}}
```

I.e., the figure is *not* extracted.

(The reason why I included the figure with the above syntax is simply that this is the default produced by `knitr` from `RMarkdown`. The example above is simply the default RMarkdown document knitted to `md`.)

**Comment by jgm** [comment]
Pandoc doesn't parse an image as a figure if it has an empty alt text (which would become the caption).  So this doesn't count as a figure.

**Comment by tamas-ferenci** [comment]
Thanks @jgm for the extremely quick answer! But I don't think this is the solution:

```
---
title: "Untitled"
author: "Author"
---

## Example

![alt](tempmarkdown_files/figure-html/pressure-1.png)<!-- -->

Example.
```

produces the same phenomenon (despite the presence of the alt text).

**Comment by tarleb** [comment]
Pandoc requires figures to be images which are the only element in a paragraph. By writing `<!-- -->` at the end, you create a raw HTML block, thus adding another element to the paragraph and preventing the interpretation of the image as figure.

**Comment by tamas-ferenci** [comment]
Ah, indeed! Thank you very much @tarleb , removing that really solves the problem. I wonder if there is any workout here from the lua filter side, because [it seems](https://github.com/yihui/knitr/blob/bf98f2a846d4214b86cf39e2503263c4ba10f47c/R/hooks-md.R#L45) that `knitr` is intentionally inserting that...

**Comment by tarleb** [comment]
You could remove the check `and #el.c == 1` from the filter. This causes all paragraphs which start with an image will be included.

**Comment by tamas-ferenci** [comment]
Thanks @tarleb ! It worked perfectly.

(Only problem is, if you set a knitr parameter, such as `fig.align`, it will change the `![]()` format to include direct LaTeX code. However, adding the line

```
(el.t == "RawBlock" and el.format == "tex" and string.match( el.text, "includegraphics" ) ) or
```

to the filter seems to solve this as well; hope this is really the sound solution here.)
