### ISSUE TITLE
Convert dokuwiki with inline code

### ISSUE THREAD

**Issue by AnthonyHebig** [jgm/pandoc#5916]
Hello,

I use pandoc version **2.7.3.**

There is a weird behaviour when dealing with inline code in dokuwiki format, when we use '%%' to prevent further interpretion.

**For example :** 
- you have this text in markdown format (1) : here is some `inline code`
- you convert (1) to dokuwiki format (2) : here is some ''%%inline code%%'' (it's ok, the "%%" part is not displayed when interpreting dokuwiki)
- you convert (2) back to markdown format : here is some `%%inline code%%`
In the end you have some extra "%%". 

**The same problem occurs with this example :** 
- you have this text in dokuwiki format : here is some ''%%inline code%%''
- you convert to HTML : %%inline code%% 
You have extra "%%" that are displayed in the HTML page.

See there for another example : https://groups.google.com/forum/#!topic/pandoc-discuss/rClN82ofG9o

**Comment by link2xt** [comment]
The bug is in the monospace reader, `''` markup is treated as code, not just monospace. I have checked with https://www.opensourcecms.com/dokuwiki/, the behaviour is incorrect, preparing a fix.

**Comment by link2xt** [comment]
The problem is, DokuWiki allows markup like
```
''foo **bar** baz''
```

It is bold inside monospace. The problem is even [documented in the DokuWiki writer code](https://github.com/jgm/pandoc/blob/787ad00167cb225817f2b6d7dddb989db52de068/src/Text/Pandoc/Writers/DokuWiki.hs#L435-L444).

I'll need to write a function that converts `Inlines` to `Code` then.

**Comment by jgm** [comment]
In one of the readers (HTML?) we have some code that handles cases like this by splitting, so you'd get

```
[Code "foo ", Strong [Code "bar"], Code " baz"]
```
