### ISSUE TITLE
Allow customization of type Block

### ISSUE THREAD

**Issue by spockz** [jgm/pandoc#592]
Currently the datatype Block is not open. This hinders extending and using pandoc for specific applications. In my case I would like to add a UID to each Block. @tdammers mentioned the ability to propagate class names through the AST.

I know this would mean extending quite a lot of code. Perhaps most of all the parsers and writers as everyone should be able to extend those as well when you have your custom Block data type.

**Comment by mb21** [comment]
Is this a request for [attributes for all elements](https://github.com/jgm/pandoc/issues/684) or am I missing something here?

**Comment by jgm** [comment]
Closing as a dup of #684
