### ISSUE TITLE
Code indentation is not correctly handled

### ISSUE THREAD

**Issue by raffaem** [jgm/pandoc#5920]
In the attached file (renamed to have a .txt extension due to extension constratints by GitHub)

[optimization-1.md.txt](https://github.com/jgm/pandoc/files/3871912/optimization-1.md.txt)

```
 pandoc optimization-1.md -o optimization-1.pdf
Error producing PDF.
! Missing $ inserted.
<inserted text>
                $
l.216 \textbackslash{}(\max
```

**Comment by jgm** [comment]
Looks like you're including math like so:
```
\\(\max(0,-)\\)
```
So you need to enable the `tex_math_double_backslash` extension.
`-f markdown+tex_math_double_backslash`.
Note that there are several incompatible ways of representing math out there.
The way you're using is the default in multimarkdown, so you could also use `-f markdown_mmd`.
