### ISSUE TITLE
TEI writer strips hash `#` from internal links

### ISSUE THREAD

**Issue by frederik-elwert** [jgm/pandoc#5922]
Using this simple input document:

```markdown
This is a [link](#test).
```

produces this TEI output:

```xml
<p>This is a <ref target="test">link</ref>.</p>
```

but this HTML output:

```html
<p>This is a <a href="#test">link</a>.</p>
```

The `target` attribute in the TEI output is wrong, as it is missing the leading hash character `#`. In TEI, `target` is of data type `xsd:anyURI`. Like in HTML, the `#` acts as a fragment identifier that links to an element with a corresponding `xml:id`. Without the `#`, the link would point at a local file called `test`.

This also breaks internal reference linking for pandoc-citeproc.

**Comment by mb21** [comment]
Hm.. we explicitly drop the `#`: https://github.com/jgm/pandoc/commit/25a9ca697a9fa3354e7a634d386efdef4031776f#diff-b9872715062ab62d357c7eb80ebcd10aR296

This has been there since day one of the TEI writer... @csforste ?

**Comment by frederik-elwert** [comment]
Here’s an [example](https://tei-c.org/release/doc/tei-p5-exemplars/html/tei_jtei.doc.html#quotations) from the jTEI documentation for bibliographic references that shows the use of `#`. I don’t know what motivated dropping it, but it seems clearly wrong.
