### ISSUE TITLE
No TOC links with commonmark

### ISSUE THREAD

**Issue by psyboros** [jgm/pandoc#5923]
`pandoc -f commonmark -s --toc -o file.html file.md` produces no header reference links in table of contents.
`markdown_strict` doesn't either.
Not sure if this is intended but seems broken to me.

version: 2.7.3

**Comment by mb21** [comment]
can you post a simple input example and/or test with the nightly builds (in the actions menu above)..

**Comment by psyboros** [comment]
```
# header 1
Some text.

## header 1.1
Some more text

# header 2
Some more text
```

Just tested this input with same command on latest nightly build.
New to github so not sure how you want me to post.

**Comment by mb21** [comment]
You're right. It's because the commonmark reader doesn't implement the extension: https://pandoc.org/MANUAL.html#extension-auto_identifiers

Try `-f gfm` (which is a superset of commonmark).

But it's indeed confusing from a user perspective.

**Comment by psyboros** [comment]
Yes I already tried `-f gfm` and it works. I'll use that instead.

**Comment by jgm** [comment]
You'll need to add the `auto_identifiers` extension: `-f markdown-auto_identifiers`. It's not enabled by default in commonmark. Otherwise there are no identifiers for a TOC to link to.
