### ISSUE TITLE
Figure in the conversion from markdown to jats

### ISSUE THREAD

**Issue by GrazingScientist** [jgm/pandoc#5924]
When I have a file `fig-test.md` with the following content:

```
# This is a test

Some text goes here!

![](media/image1.png)
: **Fig: 1**: This is an amazing image!

Then comes some more text!
```

Converting with:
`pandoc -t jats --filter=pandoc-citeproc fig-test.md`

I get this result:

```
<sec id="this-is-a-test">
  <title>This is a test</title>
  <p>Some text goes here!</p>
  <def-list>
    <def-item>
      <term><inline-graphic mimetype="image" mime-subtype="png" xlink:href="media/image1.png" /></term>
      <def>
        <p><bold>Fig: 1</bold>: This is an amazing image!</p>
      </def>
    </def-item>
  </def-list>
  <p>Then comes some more text!</p>
</sec>
```

However, this is wrong! The image should be in a `fig` block with a `caption` and a `graphic` element and, best case, an `alt-text` ([see JATS standard](https://jats.nlm.nih.gov/articleauthoring/tag-library/1.2/element/fig.html)). Could you please correct this, because although I see this is the more generic way, an image in a JATS file is highly likely to be a figure, not an `inline-graphic`.

pandoc 2.7.3

**Comment by jgm** [comment]
Pandoc markdown will treat an image as a figure if (and only if) it is (a) by itself in the paragraph (which yours isn't -- it is followed by a colon and other stuff) and (b) has a nonempty alt text (which is then used as the figure caption).  So try
```
![This is an amazing image!](media/image1.png)

```

**Comment by GrazingScientist** [comment]
Cool! Yes this worked perfect. However, is there a way to add alt-text that is not the caption text?

**Comment by jgm** [comment]
Currently no
