### ISSUE TITLE
LaTex to pdf conversion problem

### ISSUE THREAD

**Issue by asc84** [jgm/pandoc#5932]
Pandoc version: 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1

Let's take the following project from GitHub:
https://github.com/samjuvonen/pandoc_resume_template

Then inside that directory the following commands work as expected:
$ pandoc --template resume.pandoc.tex --pdf-engine=xelatex -o exmaple.pdf example.yml
(pdf is generated)

$ pandoc --template resume.pandoc.tex --pdf-engine=xelatex -o example.tex example.yml
(tex file is generated)

The previous tex file gets converted fine to pdf this way:
$ xelatex example.tex

Until here, the actual result (AR) equals the expected result (ER).

But let's try the same with pandoc (from the valid tex file):
$ pandoc --pdf-engine=xelatex example.tex -o example.pdf

AR:
Error at "source" (line 95, column 3):
unexpected \end
expecting \end{document}
  \cventry{1/2010 - 10/2015}{Goatherd First Class}{Evil Corp}{Rockville}{}{As a First Class Goatherd, I was responsible for half of our whole herd
  ^

ER: pdf file should be produced without error.

Well, then let's try with explicit types:
$ pandoc -f latex -t pdf --pdf-engine=xelatex -s example.tex -o example.pdf

AR:
pdf-engine xelatex is not compatible with output format pdf
:-O (Quite weird error message, isn't it?)

ER: pdf file should be produced without error.

**Comment by jgm** [comment]
Why don't you go through these steps with the latest release, 2.8, before submitting a report?

**Comment by asc84** [comment]
Well, because I recognized that a new version exists only after submitting the report.
Now I tried with 2.8 and it works with displaying this warning (so this is ok):
[WARNING] Unusual conversion: to convert a .tex file to PDF, you get better results by using pdflatex (or lualatex or xelatex) directly, try `pdflatex example.tex` instead of `pandoc example.tex -o example.pdf`.
