### ISSUE TITLE
convert reStructuredText include directive to Asciidoc include macro

### ISSUE THREAD

**Issue by vvavrychuk** [jgm/pandoc#5934]
I am converting reStructuredText document with include directive, for example:

    .. include:: file2.rst

using command:

    pandoc -f rst -o file1.adoc file1.rst

I would like that include directive gets converted to Asciidoc include macro:

    include::file2.rst[]

But instead pandoc performs actual inclusion of `file2.rst` into `file1.rst`.

**Comment by jgm** [comment]
Sorry, that's the best we can do given our document model.
