### ISSUE TITLE
Pandoc-citeproc returns 'Incompatible API versions' in Pandoc 2.8

### ISSUE THREAD

**Issue by p3palazzo** [jgm/pandoc#5935]
Running `pandoc -s -o test.html --filter pandoc-citeproc test.md` on this file:

````
---
title: "Test"
bibliography: 'biblio.bib'
---

This is a test.
````

Returns: 

````
pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1,20]
  but attempted to decode with [1,17,5,4].
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:111:48 in
  pandoc-types-1.17.5.4-CtgVGTltZpM4n7yJRNHrdV:Text.Pandoc.JSON
Error running filter pandoc-citeproc:
Filter returned error status 1
````

The error is independent of output format or whether I referenced a valid bibliography file in the metadata.

Homebrew Pandoc version 2.8 Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.2.3

**Comment by jgm** [comment]
You'll have to use a version of pandoc-citeproc that was compiled against pandoc-types 1.20 (like pandoc 2.8).  The binary packages of pandoc sholud contain a compatible version.  if you installed pandoc by source, you'll need to reinstall pandoc-types too.
