### ISSUE TITLE
css option no longer works

### ISSUE THREAD

**Issue by OptikSage** [jgm/pandoc#5937]
I have tried this on both windows and linux (wsl1) and something has changed between 2.7.3 and 2.8.

Command Line: pandoc --from=markdown --to=epub --output=out.epub --css=in.css --metadata title="TEST" in.md

in.md:
`# Test #`
`This is a Test`

in.css:
`/* TEST */`
`body { text-align: justify;}`

Open out.epub (I used calibre-edit) and inspect stylesheet1. It's the default epub.css instead of the in.css. I have tried a number of different permutation: different file location, data-dir options, file encoding, but its always the default.

**Comment by jgm** [comment]
Probably because `css` is getting a list value now.
I will look into it.

**Comment by OptikSage** [comment]
Thanks for the quick response and fix. That appears to have done the trick.

**Comment by jgm** [comment]
2.8.0.1 now released with this fix

**Comment by DavidLandup0** [comment]
I'm still having this same issue with the same `in.md` and `in.css` file as mentioned here, and the same command. It looks like any CSS file is just being ignored :(

```
pandoc.exe 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1
User data directory: C:\Users\User\AppData\Roaming\pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
@DavidLandup0 - try reproducing with 2.19.2.
And if you find that you can reproduce the issue, consider submitting a new report with full instructions for reproducing it.  (Did you use `-s` to get the document header? You should see a link to your css file there.)

**Comment by NCP-X** [comment]
> @DavidLandup0 - try reproducing with 2.19.2. And if you find that you can reproduce the issue, consider submitting a new report with full instructions for reproducing it. (Did you use `-s` to get the document header? You should see a link to your css file there.)

I was going to report the same thing, but I forgot to put the -s option :). Replying because I got here from Google, so if someone else is in the same position check if you are using '-s'.
