### ISSUE TITLE
pdf not showing with --list-output-formats

### ISSUE THREAD

**Issue by richardbrinkman** [jgm/pandoc#5938]
`pandoc --list-output-formats` does not list `pdf` whereas it produces pdf's correctly.

```sh
$ pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/username/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
$ pandoc --list-output-formats | grep pdf
$ 
```

**Comment by mb21** [comment]
See https://pandoc.org/MANUAL.html#general-options

pdf is not an output format in that sense...

btw. your pandoc version is also old..

**Comment by jgm** [comment]
Actually, we *have* recently added the ability to do `-t pdf`, and `pdf` is listed in that list!
So I will add it to `--list-output-formats`.
