### ISSUE TITLE
environment variables are not passed on to latex-pdfengine

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#5939]
I'm trying to create identical PDFs via Pandoc. Specifically, I have a Pandoc-Markdown file that I process with

    pandoc <file.md> <other options> --pdf-engine=xelatex -o <file.pdf>

If the Markdown file does not change, I would like to obtain the exact same PDF file each time I run Pandoc. The Markdown contains nothing that would lead to different `.tex`-files being generated, or LaTeX code that itself produces different outputs (e.g. `\date` macro).

The reason xelatex does not produce the exact same PDF is that the generated PDF contains the  ID field, which among other things depends on the current time. According to <https://tex.stackexchange.com/a/391541/38399>, this time can be overridden with the environment variable `SOURCE_DATE_EPOCH` introduced for [reproducible builds](https://reproducible-builds.org/specs/source-date-epoch). And indeed, when I skip Pandoc and process a LaTeX file with

    SOURCE_DATE_EPOCH=0 xelatex <file.tex>

I obtain the exact same PDF every time.

Unfortunately, doing the same with Pandoc

    SOURCE_DATE_EPOCH=0 pandoc <file.md> <other options> --pdf-engine=xelatex -o <file.pdf>

does not work. I therefore suspect that `SOURCE_DATE_EPOCH` is not copied from Pandoc's environment to xelatex's.

I propose that this behavior of Pandoc is changed.

In the meantime, is there a workaround, other than having Pandoc produce LaTeX and then run xelatex separately?

I tested Pandoc's behavior with the following `minimal.md`:
````
# Hi
````
and xelatex's behavior with the LaTeX file produced by
````
pandoc minimal.md -s -o minimal.tex
````

**Comment by jgm** [comment]
The environment *is* passed through to xelatex.  See Text.Pandoc.PDF aronud line 380.

**Comment by jgm** [comment]
If you can figure out how to print environment variables from within latex, you might be able to confirm whether this is getting passed through.

**Comment by allefeld** [comment]
Well, this is strange. Having the following document `testenv.m`:
```
---
header-includes:
- |
  ```{=latex}
  \usepackage{catchfile}
  \newcommand{\getenv}[2][]{%
    \CatchFileEdef{\temp}{"|kpsewhich --var-value #2"}{}%
    \if\relax\detokenize{#1}\relax\temp\else\let#1\temp\fi}
  ```
...
  
HOME:
\getenv{HOME}

SOURCE_DATE_EPOCH:
\getenv{SOURCE_DATE_EPOCH}
```

I can confirm that environment variables are indeed passed through with the command

````
SOURCE_DATE_EPOCH=0 pandoc testenv.md --pdf-engine=latexmk -o testenv.pdf
```

Moreover, the CreationDate and ModDate PDF properties have the expected value Jan 1st 1970.

However, the PDF ID still changes depending on the time.

On the other hand, if I separately convert to tex and then run latexmk

````
pandoc testenv.md -s -o testenv.tex
SOURCE_DATE_EPOCH=0 latexmk -xelatex -gg testenv.tex
````
the PDF ID is always the same. Additionally, ModDate is not present.

**Comment by jgm** [comment]
Weird.  I don't know how to explain it.

**Comment by allefeld** [comment]
I'm not sure what these header commands do exactly though, I just found them somewhere. If I understand correctly, it runs `kpsewhich`, which reads the environment variable and sends it to stdout, to be captured by tex. Strictly speaking, this only gives information on the environment of the `kpsewhich` subprocess. Is it possible that that environment is different from latex's?

**Comment by jgm** [comment]
It's possible I suppose.  But one would think it would inherit the environment variables from the subprocess running latex.

**Comment by jgm** [comment]
According to 
https://tex.stackexchange.com/questions/229605/reproducible-latex-builds-compile-to-a-file-which-always-hashes-to-the-same-va
there are some other options: sounds like you can put
```
\pdfinfoomitdate=1
\pdftrailerid{}
```
in your preamble with pdflatex, and
```
\pdfvariable suppressoptionalinfo \numexpr32+64+512\relax
```
with lualatex.  Don't know if these suggestions help with xelatex.

**Comment by jgm** [comment]
OK, I did an experiment in which I changed the source to add SOURCE_DATE_EPOCH=0 explicitly to the environment variables in the process running pdflatex.  The resulting PDFs still differ.
```
--- a/src/Text/Pandoc/PDF.hs
+++ b/src/Text/Pandoc/PDF.hs
@@ -372,6 +372,7 @@ runTeXProgram verbosity program args runNumber numRuns tmpDir' source = do
           $ lookup "TEXINPUTS" env'
     let env'' = ("TEXINPUTS", texinputs) :
                 ("TEXMFOUTPUT", tmpDir) :
+                ("SOURCE_DATE_EPOCH", "0") :
                   [(k,v) | (k,v) <- env'
                          , k /= "TEXINPUTS" && k /= "TEXMFOUTPUT"]
     when (runNumber == 1 && verbosity >= INFO) $ liftIO $
```
So this is odd too.

**Comment by allefeld** [comment]
Thanks for the tip. But I need this for a package I'm developing, actually a Pandoc-LaTeX-PDF-preview package for the Atom editor, and I'd like to leave the pdf-engine to be selected by the user. Keeping the PDF ID constant is necessary for the embedded PDF viewer not to lose its scroll position on reload.

Those commands work AFAIK only for pdflatex, while `SOURCE_DATE_EPOCH` should work across pdf/xe/lualatex.

**Comment by jgm** [comment]
Ah! I understand now what must be happening.
Pandoc produces the PDF in a temporary directory, and then renames it afterwards. So the path is different and this affects the PDF id.

**Comment by jgm** [comment]
If you use `latexmk` as your pdf engine and specify `--pdf-engine-opt=-outdir=bar` you can specify your own persistent temp directory (and I think avoid this issue).

**Comment by allefeld** [comment]
OK, that makes perfect sense! Yes, the PDF ID seems to be generated based on pathname & current time.

**Comment by allefeld** [comment]
I'll try `--pdf-engine-opt=-outdir=bar`, thanks!
