### ISSUE TITLE
Detect alternative PDF engines

### ISSUE THREAD

**Issue by afranke** [jgm/pandoc#5940]
With pandoc 2.5 if I type `pandoc -s --toc --css print.css foo.md -o bar.pdf` on my machine it will complain that pdflatex is not installed. Well, I know, I didn’t install it on purpose. But surely if pandoc is able to detect that pdflatex is not available, it should be able to detect that weasyprint is. I know, I can “just” use `--pdf-engine` but… why not “just” fall back?

**Comment by jgm** [comment]
I'd rather keep the output predictable and force people to be explicit.

**Comment by KurtPfeifle** [comment]
@jgm wrote:

> *"I'd rather keep the output predictable and force people to be explicit."*

I agree with that and also prefer to "force people to be explicit".

However, it may be worth while to think about adding a hint to the "complaint" which advices the user to try explicitly invoking the weasyprint (or any other auto-detected) pdf-engine? This would NOT silently "just fall back" and suggest ways to the user to be explicit....

**Comment by alerque** [comment]
I also agree I'd rather be forced to be explicit. More specifically I'd rather my build pipelines die with an error than "successfully" return PDFs built with an engine other than the one I'm setup for just because it happened to be detected first.

That being said a message about possible engines plus any that are detected would make a nice addition to the error message as @KurtPfeifle was saying.

**Comment by afranke** [comment]
> I'd rather keep the output predictable and force people to be explicit.

Although I understand that, I’d like to point out the irony of having pdflatex used by default in that case.

As others have commented, even if you don’t go as far as falling back to something else, there is still room for improvement. Can we:
1. list the supported alternatives (current message just mentions `--pdf-latex` but not the possible values)
2. detect which of those are available on the system and tell the user about them?

It goes without saying that 1 without 2 is a viable option if 2 is deemed to be too much work or out of scope.

**Comment by alerque** [comment]
> I’d like to point out the irony of having pdflatex used by default

Of course, this is perhaps one of the less predictable and more complicated backend options. But such is the burden of a legacy option that isn't explicit; you can't just change this default (to anything) without seriously breaking a lot of peoples' stable workflows. Personally I almost always prefer XeLaTeX as a backend and hard code the backend I want into anywhere I script my Pandoc usage, but a lot of code I've seen does not do this and depends on the implied default.

**Comment by jgm** [comment]
In the manual section on creating a PDF, we have
```
To produce a PDF, specify an output file with a `.pdf` extension:

    pandoc test.txt -o test.pdf

By default, pandoc will use LaTeX to create the PDF, which requires
that a LaTeX engine be installed (see `--pdf-engine` below).

Alternatively, pandoc can use [ConTeXt], `pdfroff`, or any of the
following HTML/CSS-to-PDF-engines, to create a PDF: [`wkhtmltopdf`],
[`weasyprint`] or [`prince`].
```
which omits mention of the groff option and several others.  This should be fixed.

Current doc for `--pdf-engine` option seems adequate and lists all the options.
```
`--pdf-engine=`*PROGRAM*

:   Use the specified engine when producing PDF output.
    Valid values are `pdflatex`, `lualatex`, `xelatex`, `latexmk`,
    `tectonic`, `wkhtmltopdf`, `weasyprint`, `prince`, `context`,
    and `pdfroff`. The default is `pdflatex`.  If the engine is
    not in your PATH, the full path of the engine may be specified here.
```
You also get a list of all the options if you specify an illegal option on the command line.  And there is bash completion for all the options.

I'm open to adding a list of options to the message indicating that the pdf-engine is not found.
