### ISSUE TITLE
Figure, table, example and equation numbering changed from two-level to single-level in HTML output with pandoc 2.8

### ISSUE THREAD

**Issue by N0rbert** [jgm/pandoc#5942]
I'm using pandoc under the hood of RMarkdown _bookdown_ pipeline.

Below is the simplest _numbering.Rmd_ document:

<pre>
---
title: Item numbering
site: bookdown::bookdown_site
---

# Figure

![(\#fig:md-logo) Markdown logo](Markdown-mark.svg.png)

Link: see Fig. \@ref(fig:md-logo) ...

# Table

Table: (\#tab:results) Demo table

| **Head L** | **Head R** |
|------------|------------|
| r1, c1     | r1, c2     |
| r2, c1     | r2, c2     |

Link: see Table \@ref(tab:results) ...

# Equation

\begin{equation}
f\left(k\right) =\binom{n}{k} p^k\left(1-p\right)^{n k}
(\#eq:binom)
\end{equation}

Link: see equation \@ref(eq:binom) ...

# Example

```{example, simple-code}
Simple code
```
```
int main() {
  return 0;
}
```

Link: see example \@ref(exm:simple-code) ...
</pre>

I transform it to HTML using R language:

```
Rscript -e "bookdown::render_book('numbering.Rmd', 'bookdown::html_document2')"
```

I have double checked it - I have no problems with previous pandoc 2.7.3-1 version. The expected rendering with two-level numbering is below:

>![n273](https://user-images.githubusercontent.com/309456/69673156-c68f8280-10aa-11ea-9d6d-242bb0ec8269.png)

But pandoc 2.8 produces wrong rendering with one-level numbering as shown below:

>![n28](https://user-images.githubusercontent.com/309456/69673206-deff9d00-10aa-11ea-86e0-9a30b6704ff1.png)

The problem is caused only by pandoc 2.8. As all other related components remain the same.
The EPUB writer is affected too.

I understand that there are some difficulties with two-level numbering in ODT and DOCX, but HTML is now broken with pandoc 2.8. Please revert the changes.

**Comment by jgm** [comment]
Pandoc doesn't add figure numbers or table numbers itself.  This must be added by something else in your toolchain.  Talk to bookdown developers.  If they identify a problem in pandoc, it can be reported here.
