### ISSUE TITLE
resource-path not working as expected with CSS files

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [jgm/pandoc#5960]
I have a markdown file in a subfolder called `unit1/test.md` . I want to build it to a standalone HTML file in `build/unit1/test.html` . There is an image inside of the `unit1` directory, call it `img.png` linked from the markdown file with `![image](img.png)` .  I also have styles in `styles/style.css`.

Before adding the image, i built successfully many times from the outer directory with `pandoc unit1/test.md -c styles/style.css --self-contained -o build/unit1/test.html` . After adding the images, I'm struggling. Here is what I've tried:

`pandoc unit1/test.md -c styles/style.css --self-contained -o build/unit1/test.html` (original command) - result: cannot find image in resource path (as expected)

`pandoc unit1/test.md --resource-path=.:unit1 -c styles/style.css --self-contained -o build/unit1/test.html` - result: cannot find style.css in the resource path (why?)

`pandoc unit1/test.md --resource-path=.:styles:unit1 -c style.css ...` - result: cannot find style.css in the resource path (also why?)

`pandoc unit1/test.md --resource-path=. -c styles/style.css --self-contained ...` - result: finds style.css, but not the image (as expected).

I feel like each of those last two should work, if I'm understanding the documentation correctly. It seems like when looking for css files the `--resource-path` flag is not being used correctly. Is this a bug or a user error?

My workaround for now is to `cd` into the unit1 subdirectory and use `../styles/style.css` for the css file path, but I don't love that as I want to be able to script this for arbitrarily deep subdirectories eventually.

**Comment by jgm** [comment]
I did a minimal test.
```
% echo "ok" | pandoc --self-contained --css style.css 
```
This correctly included the file `styles/style.css`.

What OS are you using, and what version of pandoc?

**Comment by DavidGriswoldTeacher** [comment]
Windows 10, latest version  (downloaded it yesterday using chocolatey
before reporting). I think the thing that is breaking it is the
`--resource-path=.:styles` line - did you just leave that out in your
write-up?

I will try to put together a more complete broken example today.

**Comment by agusmba** [comment]
> Windows 10, latest version (downloaded it yesterday using chocolatey before reporting). I think the thing that is breaking it is the `--resource-path=.:styles` line - did you just leave that out in your write-up?

On Windows you need to use `;` as path separator instead of `:`

**Comment by DavidGriswoldTeacher** [comment]
The semi-colon alone caused another error, but when I used quotes as well, e.g. --resource-path=".;styles;unit2" it works!

Is this Windows exception in the documentation somewhere and I just missed it? If not, can I make a PR to add it?

**Comment by DavidGriswoldTeacher** [comment]
Uggh, sorry, I just saw the semi-colon in the user guide. No idea how I missed that. In powershell you do need to wrap it in quotes, though (otherwise it interprets the semi-colon as the end of a command and tries to start the command over".
