### ISSUE TITLE
Error generating \rule in tex

### ISSUE THREAD

**Issue by grmat** [jgm/pandoc#5966]
- pandoc 2.7.3

When trying to generate pdf from md, horizontal rules are broken. I'm including the intermediate .tex step in this description for context. Normally I'd do `pandoc min.md -o min.pdf` (with the same error as result).

minimal example:

- min.md:

      some text
      ---
      more text

- `pandoc min.md -o min.tex`

- min.tex:

      some text
      
      \begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}
      
      more text

- `pandoc min.tex -o min.pdf`

      Error producing PDF.
      ! Missing number, treated as zero.
      <to be read again>
                         \protect
      l.53 ...enter}\rule{0.5\linewidth}{\linethickness}

Seems like `\linethickness` isn't known/set.

**Comment by jgm** [comment]
This is dealt with in pandoc 2.8.x.
See #5801 for workarounds/discussion.
(Always a good idea to search closed issues.)
