### ISSUE TITLE
command-line - template option affected

### ISSUE THREAD

**Issue by ptMcGit** [jgm/pandoc#5968]
**Problem**: `--template=` doesn't appear to search local directories.

pandoc 2.8.0.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: /Users/XXX/.local/share/pandoc or /Users/XXX/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

Darwin XXXs-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct  4 23:08:59 PDT 2019; root:xnu-4570.71.57~1/RELEASE_X86_64 x86_64

**Commands**

can't find it

```
pandoc  --template=groovy -f markdown -t html -o python.md.html python3.md
Could not find data file /usr/local/Cellar/pandoc/2.8.0.1/share/x86_64-osx-ghc-8.8.1/pandoc-2.8.0.1/data/templates/groovy.html
```

I don't think this should work...

```
pandoc  --template=/Users/XXX/.pandoc/groovy.html -f markdown -t html -o python.md.html python3.md
Could not find data file /usr/local/Cellar/pandoc/2.8.0.1/share/x86_64-osx-ghc-8.8.1/pandoc-2.8.0.1//Users/XXX/.pandoc/styles.html
```

it exists

```
ls -al /Users/XXX/.pandoc/groovy.html
-rw-r--r--  1 XXX  staff  1510 Dec  7 01:06 /Users/XXX/.pandoc/groovy.html
```
dir is readable

```
ls -al ~/.pandoc/
total 8
drwxr-xr-x   6 XXX  staff   192 Dec  7 01:06 .
```

**Comment by jgm** [comment]
First, note that templates should go in `~/.pandoc/templates/`, not directly in `~/.pandoc/`.
Try that.  There might be another residual problem due to the `styles.html` partial, so report back.

**Comment by ptMcGit** [comment]
I think that worked--

will search for templates in 

`/Users/b/.local/share/pandoc/templates`, `/Users/b/.pandoc/templates`
