### ISSUE TITLE
prevent `--defaults` fail

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#5969]
I just saw the new `--defaults` option and think it is a great enhancement!

One way I would like to use it in a software I'm developing is to associate the different file extensions for Markdown that Pandoc supports with different sets of Pandoc options.

For example, the software would call Pandoc with the option `--defaults=[file extension].yaml`, and then the user could put files `md.yaml` and `text.yaml` into `[data-dir]/defaults`, where one contains e.g. `from: gfm` and the other `from: markdown+smart`. This way, file extensions indicate different flavors of Markdown.

The problem with such an approach is that for every possible file extension there would have to be a corresponding options file in `[data-dir]/defaults`, or else Pandoc throws an error.

I see two approaches to avoid this:

-   Have Pandoc only warn, but not abort, if the defaults file cannot be found (either in the working directory or `[data-dir]/defaults`). This would be somewhat analogous to the behavior of `--template=defaults.[format]` not failing if the file does not exist, but providing a virtual built-in `defaults.[format]`.

-   Have my software check whether Pandoc will be able to find the file, and omit the `--defaults` option if not (possibly with a warning).

    The problem here is that it is non-trivial to identify `data-dir` programmatically. `pandoc --version` gives the information, but formatted for humans not software, and on *nix/macOS it doesn't even say definitively which of the two possible directories is used. (Actually, what happens if both exist?) It is possible to work around this, but cumbersome. An option which would simply write the actually used `data-dir` to stdout, with no other text, would make this easier (e.g. in a shell script: ``DATADIR=`pandoc --print-data-dir` ``).

Would you consider including one of these possible enhancements in a future version?

**Comment by jgm** [comment]
Here's a way to do it with a lua filter. Create a filter `print_data_dir.lua`:
``` lua
function Pandoc(el)
    print(PANDOC_STATE.user_data_dir)
end
```
Then do
```
echo "" | pandoc --lua-filter print_data_dir.lua
```
and you'll get it...
