### ISSUE TITLE
Issue with lua filter parsing a string including space

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#5972]
To bold a specific author's name (Smith, J.) in my MD file, I used the following `lua` filter; however, the regex `%s` does not take effect at all.

```lua
function Str(el)
  if el.text:match("Smith,%sJ.") then
    return pandoc.Strong(el)
  end
end
```

Why doesn't `pandoc` catch a space with the regex above?

**Comment by kysko** [comment]
`Smith, J.` converts to `Str "Smith,",Space,Str "J."` in the intermediate AST.
If you write `Smith,\ J.` to insert a non breaking space, it would convert to `Str "Smith,\160J."`, which now you could treat with your lua filter.
Alternatively, you could iterate on inline contents of Para or Plain and look for above successive elements (probably more a question for the discussion forum though).

**Comment by jooyoungseo** [comment]
Thank you very much, @kysko!

I hav just posted the question to the Google forum again.
I still haven't been able to solve the issue as I am not familiar with the lua syntax to walk the Para block to achieve this goal.

I have read several lua documents and examples; however, it was not a low-hanging fruit.

**Comment by jgm** [comment]
Moving this to the forum...
