### ISSUE TITLE
suggestion: JSON parse error - clearer error message

### ISSUE THREAD

**Issue by jendas1** [jgm/pandoc#5973]
Hello, I am trying to write a pandoc filter, but I can't get over the strange JSON parse errors.
E.g. the example below, when running `pandoc -f json -t markdown` it throws an "JSON parse error".
```
{
  "meta": {},
  "pandoc-api-version": [
    1,
    17,
    5,
    4
  ],
  "blocks": [
    {
      "t": "BulletList",
      "c": [
           [
        {
          "t": "Plain",
          "c": [
            {
              "t": "Str",
              "c": "tell"
            }
          ]
        }
      ]
      ]
    }
  ]
}
```
This issue is partially a question and partially an enhancement request as I would be happy to know where the mistake is & also propose an enhancement to output a more detailed error message text than just JSON parse error.

**Comment by kysko** [comment]
It does work using pandoc 2.7.3.
If you're with pandoc 2.8.x, put the api version at `[1,20]` in the above json.

**Comment by jendas1** [comment]
Thanks, you were right, the `pandoc-api-version` was the problematic piece. 
But it would be great, if the error message was `pandoc-api-version` mismatch if it requires the exact same version.
Nevertheless, my problem was solved, thank you @kysko.

**Comment by jgm** [comment]
Agreed, I've fixed the error message and now it is:
```
JSON parse error: Error in $: Incompatible API versions: encoded with [1,17,5,4] but attempted to decode with [1,20].
```
