### ISSUE TITLE
Pandoc ignores reference-doc styles

### ISSUE THREAD

**Issue by arkadyb** [jgm/pandoc#5974]
Pandoc completely ignores the styles customized and passed in with reference-doc argument.
According to README, I have generated the custom-reference.docx:

> pandoc -o custom-reference.docx --print-default-data-file reference.docx

I then opened the docx (using OO) and changed every single text color. 
Next i created a very simple md file:

> Document Title
> ==============
> 
> # Subtitle
> Normal text
> 
> ## Subsubtitle
> Normal text

Then used custom-reference.docx in reference-doc argument:

> pandoc -o test.docx --reference-doc=custom-reference.docx demo.md

In the output all the headings writtem in blue (default) color.

pandoc 2.8.1 (installed via brew)

**Comment by jgm** [comment]
As the manual says, only certain styles in the reference doc will make a difference. The manual gives a complete list of these styles.

Are you changing the styles themselves, or just changing the color of the (sample) text?

Which styles are you changing?

**Comment by arkadyb** [comment]
> As the manual says, only certain styles in the reference doc will make a difference. The manual gives a complete list of these styles.
> 
> Are you changing the styles themselves, or just changing the color of the (sample) text?
> 
> Which styles are you changing?

Yes you were right. I was updating the text color, not the style. Works ok with styles.

**Comment by quintonn** [comment]
This helped me too.  
It makes sense now that I think about it, but it's not the most obvious thing to edit the style rather than the document directly.
