### ISSUE TITLE
Heading attributes in slides

### ISSUE THREAD

**Issue by ps0ares** [jgm/pandoc#5975]
In Pandoc 2.8, heading attributes are no longer carried over to the
surrounding  `<div>` or `<section>`. This way it became impossible to style individual slides.
According to John MacFarlane, this is related to the following changelog item:

>   Replace Element and makeHierarchical with makeSections. Now that
>   we have Divs, we can use them to represent the structure of
>   sections, and we don’t need a special Element type. makeSections
>   reorganizes a block list, adding Divs with class section around
>   sections, and adding numbering if needed. This change also fixes
>   some longstanding issues recognizing section structure when the
>   document contains Divs (#3057, see also #997).

**Comment by jgm** [comment]
See #5965 
I believe that the commit
https://github.com/jgm/pandoc/commit/7f4154a8bbeff772b778b60c75fe1081b3b9b5f1
will take care of this issue as well. You might try testing with a nightly (see Actions tab).
