### ISSUE TITLE
data-dir confusion

### ISSUE THREAD

**Issue by hoclun-rigsep** [jgm/pandoc#5978]
Picking up on #4777: On Mac OS 10.14.5 installed with homebrew:

$ pandoc --version
pandoc 2.8.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: /Users/jim/.local/share/pandoc or /Users/jim/.pandoc

However, this only works for me when files are in .local/share/pandoc, not ~/.pandoc. This is apparently true even if there is no ~/.local/share/pandoc directory.

**Comment by jgm** [comment]
What only works?
Are you trying to find a template?  If so, is it in the templates subdirectory?  Perhaps you're doing something else wrong?  All checks out fine for me: if the `~/.local/share/pandoc` directory does not exist, pandoc looks in `~/.pandoc`.

**Comment by hoclun-rigsep** [comment]
Sheepishly I withdraw this issue. Sorry to steal your attention.
