### ISSUE TITLE
Class Applied to RevealJS Slide Fails

### ISSUE THREAD

**Issue by innomadic** [jgm/pandoc#5983]
Previously I was able to add a class to the end of a header {.classname} and it would apply the class to my revealjs slides, like this:
```
--- 
title: test
---
<style>
.seventy {
   font-size: 70%;
}
</style>

# Test one 

text 

# Test two {.seventy}

more text
```
I used it to contol font sizes.

I am 100% sure that this was working before, but I'm not sure what changed -- possibly a new version of Pandoc?

When I use this command:
```
pandoc -t revealjs -V revealjs-url=../../../presentation/reveal.js -o testreveal.html testreveal.md && open testreveal.html
```

I get this output:

```
<section class="slide level1">

<style>

.seventy {
   font-size: 70%;
}
</style>
</section>
<section id="test-one" class="slide level1">
<h1>Test one</h1>
<p>text</p>
</section>
<section id="test-two" class="slide level1">
<h1 class="seventy">Test two</h1>
<p>more text</p>
</section>
```

So I think the problem is that it is applying the class to the header, whereas for Revealjs, the style should be applied to the section.  

```
pandoc -v
pandoc 2.8.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
```

**Comment by innomadic** [comment]
Maybe this is a duplicate of https://github.com/jgm/pandoc/issues/5965

I am not running the section-divs command but maybe that is implicit with the revealjs option?

**Comment by jgm** [comment]
Yes, it's a duplicate (see also #5980).
Anyway, a lot of people are having this problem; I'll try to push out a new release before long.
