### ISSUE TITLE
org-reader/table: wrap table in a div in order to process table-label with pandoc-crossref 

### ISSUE THREAD

**Issue by michelk** [jgm/pandoc#5984]
pandoc version:  2.8.0.1

Currently table references in `org-mode` won't get resolved with `pandoc-crossref`. 

e.g.

```org
See figure [-@fig:label]

#+CAPTION: Caption
#+LABEL: fig:label
file:tt.png

See table [-@tbl:label]

#+CAPTION: Caption
#+LABEL: tbl:label
| a   | b   | c   |
|-----+-----+-----|
| 1   | 2   | 3   |
| 4   | 5   | 6   |
```
Produces with `pandoc -F pandoc-crossref -F pandoc-citeproc -t txt`

```txt
See figure 1

![Figure 1: Caption](tt.png){#fig:label}

See table **¿tbl:label?**

  a   b   c
  --- --- ---
  1   2   3
  4   5   6

  : Caption
```
Wrapping the table in a div should resolve the issue. See https://github.com/lierdakil/pandoc-crossref/issues/241 for discussion.

**Comment by tarleb** [comment]
After some more thought, I decided to add an empty span with the label as the span's id to the caption. This is more in line with org-mode's behavior, which adds a `\label` to the table's caption when exporting to LaTeX.

**Comment by michelk** [comment]
Thanks @tarleb. 

@lierdakil is there an adaption in `pandoc-crossref` required? With the last pandoc commit I get: 

```
See figure 1
  
![Figure 1: Caption](tt.png){#fig:label}

See table **¿tbl:label?**

  a   b   c
  --- --- ---
  1   2   3
  4   5   6

  : []{#tbl:label}Caption

```

**Comment by lierdakil** [comment]
@tarleb, I'm not a fan of this approach at all. It's hacky, ambiguous (imagine several spans in caption), and will be converted to questionable HTML (that is, table references will scroll to table caption, not table itself). Please reconsider.

**Comment by lierdakil** [comment]
@michelk, yes, pandoc-crossref has no idea what that span means and how to handle it. I also won't be able to add support for this hack anytime soon, supporting it would require considerable changes to internal logic, and it's the end of the year. Also, as I said above, I'm not a fan of the approach taken here, so I also don't really _want_ to implement support for this.

**Comment by tarleb** [comment]
Here's a Lua filter to make the new behavior usable with pandoc-crossref:

``` lua
function Table (tbl)
  local idSpan = tbl.caption[1]
  if idSpan and idSpan.t == "Span" and idSpan.identifier then
    table.remove(tbl.caption, 1)
    return pandoc.Div(tbl, pandoc.Attr(idSpan.identifier))
  end
end
```

The current approach is modeled after org's LaTeX output. I agree that the HTML output isn't particularly nice. I'd be ok to change this if there is agreement that table properties are stored in a surrounding div. Is there already a precedence for this behavior in other readers?

**Comment by lierdakil** [comment]
I'm not up-to-date on pandoc's code base, so I can't really comment on that. But at least one instance when div is used (that I can name from the top of my head) is https://github.com/mb21/pandoc-placetable.

**Comment by lierdakil** [comment]
Also, side note, the thing you should be looking into is not how many readers do something like this, but how writers will handle that adequately. As far as I can tell from the top of my head, the _only_ writer that will do what is intended is LaTeX. Also, while on the topic of writers, perhaps a good idea to add the capability to output correct org from this AST in the org-mode writer.

**Comment by michelk** [comment]
Thanks @tarleb. The workaround with the lua filter works. 

`pandoc -L org-table-span.lua -F pandoc-crossref -F pandoc-citeproc`

produces

```
See figure 1

![Figure 1: Caption](tt.png){#fig:label}

See table 1

::: {#tbl:label}
  a   b   c
  --- --- ---
  1   2   3
  4   5   6

  : Table 1: Caption
:::

```

**Comment by lierdakil** [comment]
I did a quick search, and at least one example of a div being used for table attributes is in JATS reader:
https://github.com/jgm/pandoc/blob/90e436d49604e3fd1ef9432fb23f6d7f6245c7fd/src/Text/Pandoc/Readers/JATS.hs#L185-L186

**Comment by tarleb** [comment]
Thanks @lierdakil. Reopening, so we won't forget about this.

**Comment by jgm** [comment]
I agree, putting the whole table in a Div is better. (This will work better with more writers, and won't get in the way of things like pandoc-crossref.)
