### ISSUE TITLE
styles.html partial not found when using template in subdirectory

### ISSUE THREAD

**Issue by frederik-elwert** [jgm/pandoc#5987]
I noticed a very special bug related to the newly introduced `styles.html` partial. It occurs when using a custom template that is in a different directory. Pandoc version is 2.8.1.

```bash
$ mkdir mytemplate
$ pandoc -D html > mytemplate/custom.html
$ echo "Test" | pandoc -s --template mytemplate/custom.html 
Could not find data file templates/mytemplate/styles.html
```

Interestingly, it works when the template is in the same directory, i.e.

```bash
$ pandoc -D html > custom.html
$ echo "Test" | pandoc -s --template custom.html 
```

I could solve this by putting a copy of the file into the `mytemplate` directory.

I also tried putting it into `~/.pandoc/templates`, but that failed as well. I had to put it into `~/.pandoc/templates/mytemplate` to work. So it looks like the template path somehow gets appended to the search path, making pandoc fail to find the default data file.

**Comment by jgm** [comment]
Try with 2.9; there were some template partial-related changes.

**Comment by frederik-elwert** [comment]
Tested again with 2.9, but the error is exactly the same.
