### ISSUE TITLE
no defaults file entry equivalent to --no-highlight

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#5989]
As far as I can tell, right now there is no defaults file entry that is equivalent to `--no-highlight`.

> @allefeld if not that's an oversight, but it should be requested in a new issue
> _Originally posted by @jgm in https://github.com/jgm/pandoc/issues/4205#issuecomment-565608508_

Pandoc 2.9

**Comment by jgm** [comment]
Oh, there is a way to do  this already.
```
highlight-style: null
```
or
```
highlight-style:
```

**Comment by allefeld** [comment]
Just so I understand, for the defaults file table I'm making:

`null` means undefined in YAML and is therefore false-like,
while an omitted value means logical true, is that correct?

**Comment by jgm** [comment]
The corresponding haskell type is a Maybe Style value (can be Nothing or Just style).
null (or omitted) => Nothing
Setting this to Nothing is what `--no-highlighting` does.
