### ISSUE TITLE
Markdown -> odt : table not rendered

### ISSUE THREAD

**Issue by ngirard** [jgm/pandoc#5991]
The following test.md file, when rendered as text or html, produces a table as expected. 
But when calling `pandoc test.md -o test.odt`, no table appears in the produced odt file.

test.md:
```markdown
# Lorem ipsum

1) Lorem ipsum
   
   | Name               | Description        |
   | -------------------|--------------------|
   | `param_1`          | Lorem ipsum        |
   | `param_2`          | Lorem ipsum        |

2) Dolor sit amet
```

**Comment by mb21** [comment]
Probably a duplicate of https://github.com/jgm/pandoc/issues/3430 ?
