### ISSUE TITLE
pandoc problem during parsing for colons in headline

### ISSUE THREAD

**Issue by treese** [jgm/pandoc#5993]
pandoc gives a "problem parsing org" error for the attached Org file, which contains only

>  ** This headline goes on for 5:23: is it good?

The problem is likely something about parsing the `:23` as a tag. The file is attached as .txt because Org files can't be attached here.
[foo.txt](https://github.com/jgm/pandoc/files/3965541/foo.txt)

**Comment by treese** [comment]
That was quick! Thanks.

**Comment by tarleb** [comment]
And thanks to you for reporting it!
