### ISSUE TITLE
\usepackage[space]{xeCJK} cause error: Option clash for package xeCJK

### ISSUE THREAD

**Issue by annProg** [jgm/pandoc#6002]
this issue was introduced by https://github.com/jgm/pandoc/pull/5855

This may be problem when documentclass already load xeCJK with no option.  
```
! LaTeX Error: Option clash for package xeCJK.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.19     \setCJKmainfont
                        [BoldFont=Source Han Serif SC Heavy,ItalicFont=Fando...

? H
The package xeCJK has already been loaded with options:
  []
There has now been an attempt to load it with options
  [space]
Adding the global options:
  ,space
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.
```

May use `\xeCJKsetup { CJKspace = true }` to do this. Code from `ctex-engine-xetex.def`

```
\keys_define:nn { ctex }
  {
    space .choice: ,
    space / true  .code:n =
      { \xeCJKsetup { CJKspace = true } } ,
    space / auto  .code:n =
      { \xeCJKsetup { CJKspace = false } } ,
    space / false .code:n =
      { \xeCJKsetup { CJKspace = false } } ,
    space .default:n = { true } ,
    space .initial:n = { auto }
  }
```

So, I think it is not good idea to add this to default template. May use variable?

```
\usepackage[$for(xeCJKoptions)$$xeCJKoptions$$sep$,$endfor$]{xeCJK}
```

**Comment by jgm** [comment]
Or we could use the approach we use for some other packages: see the beginning of the latex template:
```
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode$for(hyperrefoptions)$,$hyperrefoptions$$endfor$}{hyperref}
\PassOptionsToPackage{hyphens}{url}
```

Thus, at beginning of template, add
```
$if(CJKmainfont)$
\PassOptionsToPackage{space}{xeCJK}
$endif$
```
and then remove the `[space]` from the place where we currently have
```
\usepackage[space]{xeCJK}
```
Testing of this approach welcome!

**Comment by jgm** [comment]
Can anyone help test with the revisions of the default template suggested above?

**Comment by annProg** [comment]
@jgm I tested it and it looks ok

**Comment by waynon** [comment]
I'd like to make a summary of what happened and how to solve such problems to help other people seeing this issue.

This happens because a documentclass has already loaded the package.

A macro package cannot be initialized more than once with different options passed.

To modify the options of a macro package in such situation, instead of passing parameters in the usepackage command, use a command the package provides to modify its settings (e.g. \xeCJKsetup{} in this issue).
