### ISSUE TITLE
Strange linker error in GitHub Actions for release candidate

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#6003]
This affects the linux build.
```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lz
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```

Doe anyone have any ideas?  Not much has changed since the last successful release candidate build, ten days ago.  We do install libz-dev, and that has always worked in the past.

**Comment by tarleb** [comment]
I can reproduce this locally, seems to be a problem with alpine 3.11. Everything works fine after setting the base image to `FROM alpine:3.10`.

**Comment by jgm** [comment]
Ah, thanks!  That's an easy fix (and explains maybe why my local build worked -- probably using a cached container).  I wonder what changed?

**Comment by snoyberg** [comment]
I stumbled on this issue while investigating a similar issue while working on Stack. It looks like installing `zlib-static` is now necessary.
