### ISSUE TITLE
pandoc-2.7.3\data\docx/[Content_Types].xml cannot be found

### ISSUE THREAD

**Issue by hanjoosten** [jgm/pandoc#6007]
[Ampersand](https://github.com/AmpersandTarski/Ampersand) is an application written in Haskell. It uses the pandoc api. When compiled, it is supposed to create a relocatable binary. However, one of our users [reported](https://github.com/AmpersandTarski/Ampersand/issues/1023) that he couldn't produce an .docx document:

```
Generating functional design document for ProjectAdministration...
Could not find data file C:\sr\snapshots\869ae550\share\x86_64-windows-ghc-8.6.5\pandoc-2.7.3\data\docx/[Content_Types].xml
ExitFailure 97
```

I did some investigation myself. I [see](https://github.com/jgm/pandoc/blob/73efef589a14616972cf4e3b96b3b1dc366b80f1/doc/using-the-pandoc-api.md#data-files) that pandoc has a flag to embed it's data files. It uses [file-embed](https://hackage.haskell.org/package/file-embed) in order to have a relocatable binary itself. 

I would expect that an application that uses the API would be fine, but obviously it doesn't work that way. Either this is a bug, or the consumer application should do 'something' extra to have the data files contained in the executable.

**Comment by jgm** [comment]
If you set the `embed_data_files` flag for pandoc when you're compiling your application, it should work.  Did you do this?

If not, things can still be made to work work, but where the data files end up is dependent on the build system you use and other things.  Embedding the data files is a more robust way to go.

**Comment by hanjoosten** [comment]
Thanks. I didn't know that flags could be supplied this way. I figured it out now. Still compiling, but I am confident that this did the job. Thank you very much for pointing this out.
