### ISSUE TITLE
RST: lang does not set mainlang when using xelatex

### ISSUE THREAD

**Issue by matclab** [jgm/pandoc#6008]
When using xelatex, `setmainlanguage` is correctly set for markdown from `lang` metadata, but not for restructuredText.

```
pandoc --version                                             
pandoc 2.7.3
Compiled with pandoc-types 1.17.6.1, texmath 0.11.3, skylighting 0.8.3
```

When doing:
```
pandoc -s --pdf-engine=xelatex -t latex << EOT | grep setmain     

---
lang: fr-FR
...
EOT
```
I get `\setmainlanguage[]{french}`

But when doing:
```
pandoc -f rst -s --pdf-engine=xelatex -t latex << EOT | grep setmain

:lang: fr-FR 
...
EOT
```
I get `\setmainlanguage[]{}`.

**Comment by jgm** [comment]
Pandoc only recognizes this as metadata if it occurs in the title block. (Otherwise it's just a definition list.)

So this should work:
```
Le Titre
=====
:lang: fr-FR

Le text...
```

**Comment by mb21** [comment]
jep, using pandoc 2.9.1

```
~ pandoc -s --pdf-engine=xelatex -t latex << EOT | grep setmain
pipe heredoc> ---
lang: fr-FR
...
EOT


  \setmainlanguage[]{french}
```

**Comment by jgm** [comment]
Looks like docutils parses
```
:lang: fr-FR
```
as "docinfo" if it occurs at the beginning of a document, or right after a title block.  (Otherwise, it's a regular "field list", i.e. definition list.)

Pandoc should do the same. Should be an easy change.

**Comment by jgm** [comment]
Never mind.  It's not an issue in the reader.  The reader behaves correctly whether or not the title block is there (in either case the `lang` is registered as metadata).

And in fact the altered version I suggested above (with the title) doesn't produce `setmainlanguage[]{french}`.

**Comment by jgm** [comment]
Markdown reader produces
```
Pandoc (Meta {unMeta = fromList [("lang",MetaInlines [Str "fr-FR"])]})
```
while RST reader prodics
```
Pandoc (Meta {unMeta = fromList [("lang",MetaBlocks [Para [Str "fr-FR"]])]})
```
So the problem seems to be that the latex writer isn't handling `lang` when it's included as blocks.

**Comment by jgm** [comment]
Issue is actually in Text.Pandoc.BCP47.getLang.
