### ISSUE TITLE
CodeBlock parsing affected by indentation of prior HTML, despite intervening Para

### ISSUE THREAD

**Issue by jimblandy** [jgm/pandoc#6009]
Using pandoc changeset 5484a63 (Sun Dec 22 2019), `pandoc input.md -t json` shows that the line beginning `//#atom1` is parsed as a `Para`, not a `CodeBlock` when `input.md` contains this text:
```
  <td>
  <div></div>
  </td>

Integer

    //#atom1
    match meadow.count_rabbits() {

```

However, if we remove the indentation from those three raw HTML lines, then the code block is parsed correctly:
```
<td>
<div></div>
</td>

Integer

    //#atom1
    match meadow.count_rabbits() {

```

Possibly related: #5360

**Comment by jgm** [comment]
Just to confirm that it has nothing essentially to do with Divs, here's another case that triggers the bug:
```
  <tr>
  <td></td>
  </tr>

x

    y
```

**Comment by jimblandy** [comment]
\o/ Thanks!

We used Pandoc to write our book, "Programming Rust", in Markdown and convert to O'Reilly's HTMLBook, with a pretty hairy filter in Haskell using Text.Pandoc.Definition. We were stuck on Pandoc 1.17 for a while, and when we updated to 2.9, several of our tables ran afoul of this.
