### ISSUE TITLE
invalid epub from markdown due to empty list in nav landmarks

### ISSUE THREAD

**Issue by vv01f** [jgm/pandoc#6017]
epubcheck sais: 

> Error while parsing file: element "ol" incomplete; missing required element "li"

for me the error is thrown by epubcheck after generating an epub with pandoc from markdown (when not using `--toc`).

the empty `ol` is inside the nav landmarks… I would kindly ask to not create the nav landmarks or to have at least one child `li` for `ol` referencing the toc.

reproducable with follwoing [known example](https://github.com/jgm/pandoc/issues/1757#issuecomment-72393834) by @elmimmo in issue #1757 .

**Comment by jgm** [comment]
Pandoc version?

**Comment by jgm** [comment]
Can't reproduce, no followup on pandoc version -- suspect an old one. Closing.
