### ISSUE TITLE
links with @ interpreted as reference in YAML headers?

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#6019]
When I run pandoc with this file:
```
$ cat foo.md 
---
links: ["https://mathstodon.xyz/@somenxavier/102180322573266094", "https://twitter.com/somenxavier/status/1133773317016567808"]
---

*Hola*
```

I get this

```
$ pandoc --toc --toc-depth=4 --mathml -standalone --from=markdown+smart+table_captions+simple_tables+pipe_tables+multiline_tables+strikeout+tex_math_dollars+raw_html+footnotes+inline_notes+implicit_figures+citations --to=html5 --filter pandoc-citeproc --metadata link-citations=true foo.md 
pandoc-citeproc: reference somenxavier/102180322573266094 not found
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'foo' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>foo</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<p><em>Hola</em></p>
</body>
</html>
```
This is confusing to me. Is anyway to scape @ in YAML headers? I did not find in the documentation

**Comment by tarleb** [comment]
Please be aware that this type of question is better asked on the pandoc-discuss mailing list.

Depending on whether you want a raw string value or a link, use either `"https://mathstodon.xyz/\\@somenxavier/102180322573266094"` (backslash escape) or `"<https://mathstodon.xyz/@somenxavier/102180322573266094>"` (explicit marking as link).

**Comment by somenxavier** [comment]
I tried to scape with only one backslash. Can you put this trick into documentation? Thanks

**Comment by somenxavier** [comment]
Your scape solution does not work for me

**Comment by somenxavier** [comment]
On the other hand making links within `< >` return links as `<a class=uri` and not as text. How can I specify the title of the link: `"<https://mathstodon.xyz/@somenxavier/102180322573266094 Title>"` does not work for me.

**Comment by tarleb** [comment]
You'd have to use the full [link syntax](https://pandoc.org/MANUAL.html#inline-links) to specify a link title.

**Comment by somenxavier** [comment]
Mmm... but I have the link in the YAML header, not in the body

**Comment by somenxavier** [comment]
Yes. `[title](link)` works for me.
