### ISSUE TITLE
From docx to gfm with merged cells table

### ISSUE THREAD

**Issue by rickywu** [jgm/pandoc#6025]
pandoc -v: 2.9.1
command: pandoc -f docx -t gfm gfm_table.docx -o gfm.md

Input: 
[gfm_table.docx](https://github.com/jgm/pandoc/files/4018535/gfm_table.docx)

Output:
`
<table>
<thead>
<tr class="header">
<th></th>
<th>2</th>
<th>3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>a</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>b</td>
<td></td>
<td><p>Yes</p>
<p>No</p></td>
</tr>
<tr class="odd">
<td>c</td>
<td></td>
<td>Test</td>
</tr>
</tbody>
</table>
`

Problem is the merged cells were lost

I expect this:
![gfm_table](https://user-images.githubusercontent.com/442398/71714440-e4d66400-2e48-11ea-9672-10f2dfcc9a91.png)

**Comment by mb21** [comment]
Unfortunately, this is currently a limitation of pandoc, see #1024

**Comment by rickywu** [comment]
@mb21 Any plan to support?
