### ISSUE TITLE
intermediate file not recreated with explicitly specified temporary directory

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#6027]
When Pandoc creates a PDF file directly, and the temporary directory is specified explicitly with `--pdf-engine-opt=-output-directory=`, the intermediate file (e.g. `input.tex`) is not recreated on subsequent runs.

Example: first run
```
$ echo "# Test" > test.md
$ pandoc test.md --pdf-engine-opt=-output-directory=. -o test.pdf
$ ls
total 124
-rw-r--r-- 1 ca ca     7 2020-01-03 19:54:15 test.md
-rw-r--r-- 1 ca ca  1708 2020-01-03 19:54:19 input.tex
-rw-r--r-- 1 ca ca   939 2020-01-03 19:54:20 input.aux
-rw-r--r-- 1 ca ca 37941 2020-01-03 19:54:20 input.pdf
-rw-r--r-- 1 ca ca 28774 2020-01-03 19:54:20 input.log
-rw-r--r-- 1 ca ca 37941 2020-01-03 19:54:20 test.pdf
```

Second run:
```
$ echo "" >> test.md
$ echo "text" >> test.md
$ pandoc test.md --pdf-engine-opt=-output-directory=. -o test.pdf
$ ls
total 124
-rw-r--r-- 1 ca ca  1708 2020-01-03 19:54:19 input.tex
-rw-r--r-- 1 ca ca    13 2020-01-03 19:54:52 test.md
-rw-r--r-- 1 ca ca   939 2020-01-03 19:54:59 input.aux
-rw-r--r-- 1 ca ca 37941 2020-01-03 19:54:59 input.pdf
-rw-r--r-- 1 ca ca 28774 2020-01-03 19:54:59 input.log
-rw-r--r-- 1 ca ca 37941 2020-01-03 19:54:59 test.pdf
```

On the second run, even though `test.md` was changed, `input.tex` is not recreated.

**Comment by allefeld** [comment]
As a workaround, I deleted all files in the temporary directory, but that leads to problems with a file-watching pdf viewer.

I assume it should be sufficient to delete `input.tex`?

To delete only those files for which it is necessary, can I assume that the intermediate files are always called `input.*`, and specifically `input

**Comment by jgm** [comment]
line 361 of Text.Pandoc.PDF:
``` haskell
    let file = tmpDir ++ "/input.tex"  -- note: tmpDir has / path separators
    exists <- liftIO $ doesFileExist file
    unless exists $ liftIO $ BS.writeFile file $ UTF8.fromText source
```
It's this existence check that is causing the reported behavior.  I need to remember why the existence check is there in the first place...

**Comment by jgm** [comment]
Probably the check is there to avoid recopying the input source on subsequent runs.
For this purpose, we could replace the existence check with a check of runNumber.
But maybe there was another reason I'm not thinking of?

**Comment by allefeld** [comment]
It would make sense not to recreate `input.tex` if the source file hasn't changed (make-like), but that is not the behavior. I don't think this issue is particularly grave, and I can work around it, but why the close?

What do you mean by recopying? Isn't `input.tex` written directly into the temporary directory?
(Now that I think of it, it is surprising that a PDF engine option affects Pandoc's behavior itself.)

**Comment by mb21** [comment]
jgm closed the issue by fixing the code on master. you can try the nightly builds (actions tab on github, above) or wait for the next release.

**Comment by allefeld** [comment]
Ah sorry, should have seen the commit reference. Thanks!
