### ISSUE TITLE
Feature request: abstract title in docx output

### ISSUE THREAD

**Issue by enricoscarpella** [jgm/pandoc#6028]
Hi all,

As suggested in pandoc-discuss, I would like to request a feature to be added to future Pandoc releases. Could we please have the header "Abstract" automatically added before the abstract text in the docx output when the abstract is either in the metadata of the input file or in the text the input file and is moved to the metadata by the abstract-to-meta Lua filter? At the moment, the only way I found around the lack of this feature is to have the abstract and its title in the text, and use fenced-divs and "Abstract Title" and "Abstract" custom styles in the reference.docx file. Thank you for your consideration.

Best regards,
Enrico

**Comment by jgm** [comment]
We wouldn't generally want to include a hard-coded English word.  (Not everyone writes in English, after all.) But now that we have the Translations module I think we could do this.

Still, I'm not sure it's entirely desirable, since (unlike in LaTeX) there'd be no way to customize or remove this word in the docx output.

**Comment by alerque** [comment]
Translations module? I missed something! Can you point me to the docs and/or code?

P.S. I hope it's based on Fluent!

**Comment by jgm** [comment]
Text.Pandoc.Translations
see also `data/translations`

**Comment by enricoscarpella** [comment]
> Still, I'm not sure it's entirely desirable, since (unlike in LaTeX) there'd be no way to customize or remove this word in the docx output.

You are right: this is an important limitation because some journals expect the title of that section to be "Summary" and not "Abstract", for example. It still seems then that fenced_divs in combination with custom styles in a reference.docx file is the way to go... But thank you for your consideration.
