### ISSUE TITLE
Missing table headers with Jira writer

### ISSUE THREAD

**Issue by jack-kirton** [jgm/pandoc#6035]
The Jira writer does not appear to produce table header rows. It is being parsed properly as it appears in the markdown -> JSON and markdown -> markdown conversions.

**Pandoc version:** 2.9.1.1 (.deb installation)
**Command:** `pandoc --from=markdown --to=jira < test-table.txt`
**Input file (just contains a one row markdown grid table):** [test-table.txt](https://github.com/jgm/pandoc/files/4031149/test-table.txt)
**Actual output:**
`| High | It is highly likely that adversaries will probe for weakness. Impact decided by examining the impact of similar issues. | Control | Due to the risk, the threat must be controlled. |`
**Expected output:**
There should be a header row similar to `|| Initial Risk || Initial Risk Rationale || Action || Action Rationale ||` before the actual output.

**Comment by tarleb** [comment]
Thanks for the report. [This conditional](https://github.com/jgm/pandoc/blob/d4651b3a5b2e31b22bf80adbe44964e09da41f9b/src/Text/Pandoc/Writers/Jira.hs#L103) must be inverted. I'll fix it later today.
