### ISSUE TITLE
handling latex templates in versions >2.7

### ISSUE THREAD

**Issue by knaaptime** [jgm/pandoc#6036]
Hi, thanks for the great software

I use this [cookiecutter template](https://github.com/knaaptime/cookiecutter-academic-python) for writing papers. It uses a [custom latex](https://github.com/knaaptime/cookiecutter-academic-python/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/paper/.pandoc/org-preamble-xelatex.sty) template and [this command](https://github.com/knaaptime/cookiecutter-academic-python/blob/3ed897e6e54da5c36f05a820af9b5de54837b238/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile#L68) to compile the paper. Everything works great through pandoc verion 2.7.3. Any pandoc version >=2.8, however, gives
```
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.19 N

make: *** [paper/draft.pdf] Error 43
```

all the underlying documents are unchanged so I'm pretty sure it's newer versions of pandoc that are inducing the breakage. Is there a different way that new versions handle latex templates, e.g. a new flag i need to set or something? If not, any ideas about what might be going on?

thanks again

**Comment by jgm** [comment]
That's not a template, it's just a preamble.  It doesn't contain any template variables such as `$body$`.

It's possible there's some issue, but it would help to diagnose it if you created a small repository with everything needed to reproduce, including a Makefile with the relevant command.

**Comment by knaaptime** [comment]
oops, sorry linked the wrong file ([that's](https://github.com/knaaptime/cookiecutter-academic-python/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/paper/.pandoc/xelatex.template) the template)

to reproduce:

```
git clone git@github.com:knaaptime/pandoc-test.git
cd pandoc-test
make environment  # will install deps and pandoc 2.9.1.1
conda activate pandoc-test
make clean
make paper
```
fails

followed by

```
conda install  pandoc==2.7.3
make clean; make install
```
works great

**Comment by knaaptime** [comment]
the template uses some open fonts, but they're available in the `paper/.pandoc/fonts` dir if necessary

**Comment by jgm** [comment]
Before I spend time looking at this, I think there's more you could do to investigate.
Try running pandoc with the `--verbose` option; this will spit out the entire intermediate latex file generated by pandoc, and the latex build log, and you can then see exactly what is happening. (Or just generate a standalone latex file instead of pdf, and inspect that.)

**Comment by knaaptime** [comment]
cool, thanks again for your help.

If i build the [latex file](https://gist.github.com/knaaptime/966333af8510037ae2adc0ade97e636c) the error shows up on line 18 which is adding an erroneous line break in the middle of the line

pandoc 2.7.3 produces [this](https://gist.github.com/knaaptime/7dd547c72d51cfbe7b9069dfde47c04f) latex file without the line break

**Comment by jgm** [comment]
I see what is happening.

In pandoc 2.8 the template system changed, allowing interpolated variables to wrap.

Obviously you don't want this in a case where the variable is on a commented-out latex line.

The solution is to either remove this line from the template (if it's commented out, perhaps you don't need it), or replace the latex comment with a *template* comment (`$--`), or use the `nowrap` pipe (see the manual).

In this case the template has
```
%\author{$for(author)$$author$$sep$\\$endfor$}

\author{$for(author)$\large $author.name$\vspace{0.05in} \newline\normalsize\emph{$author.affiliation$} \newline\footnotesize \url{$author.email$}\vspace*{0.2in}\newline $sep$ \and $endfor$}

%\author{$for(author)$$author.name$ ($author.affiliation$)$sep$ \and $endfor$}
```
And I think the intent is to give the user a few options.  It's not particularly desirable for these comments to appear in the generated tex, so it would be best to use a template comment:
```
\author{$for(author)$\large $author.name$\vspace{0.05in} \newline\normalsize\emph{$author.affiliation$} \newline\footnotesize \url{$author.email$}\vspace*{0.2in}\newline $sep$ \and $endfor$}

$-- Depending on your needs, you may want to use one of these lines instead:
$-- \author{$for(author)$$author$$sep$\\$endfor$}
$-- \author{$for(author)$$author.name$ ($author.affiliation$)$sep$ \and $endfor$}
```

**Comment by knaaptime** [comment]
Great I’ll look into making those changes. Thanks again!
