### ISSUE TITLE
Support custom checkbox characters in task lists

### ISSUE THREAD

**Issue by DCsunset** [jgm/pandoc#6037]
As mentioned in #3051, the task lists have been implemented.
The checkboxes are now ☒ (BALLOT BOX WITH X) and ☐ (BALLOT BOX).

It would be nice to support custom characters like ☑ (BALLOT BOX WITH CHECK).

**Comment by mb21** [comment]
This was modeled after [GitHub tasklists](https://github.github.com/gfm/#task-list-items-extension-). Not convinced that we should diverge from that... similarly, also from CommonMark:

> A bullet list marker is a -, +, or * character.

so no unicode characters (like unicode bullet points).

**Comment by alerque** [comment]
@mb21 The issue isn't very clear but I read it as wanting this Unicode as a rendering in some other output format, not a change to the Markdown format.

**Comment by mb21** [comment]
ah, yeah that would depend on the output format.

**Comment by mb21** [comment]
@fullstopslash you want custom unicode characters in the markdown input?

Note that normal checkboxes for latex output already work out of the box:

```
echo '- [ ] foo' | pandoc -t latex

\begin{itemize}
\tightlist
\item[$\square$]
  foo
\end{itemize}
```

**Comment by fullstopslash** [comment]
Yeah, I'm trying to write a filter that changes ` \item[$\square$` to `\item[$my custom LaTeX$]`
