### ISSUE TITLE
Make it easier to filter lists of inlines or lists of blocks

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#6038]
Some filtering tasks are best solved by having information on the order of elements in a sequence instead of just looking at single elements. An example, which [came up on pandoc-discuss](https://groups.google.com/d/topic/pandoc-discuss/ChZ5YhNjJxQ/discussion), is a filter which removes spaces before citations.

Possible solutions include:

- allowing `ListOfInlines` as a filter function, which is run on the document via the `[Inline] -> [Inline]` instance of Text.Pandoc.Walkable;
- adding Lua helper functions which make it easier to traverse elements.

**Comment by kljensen** [comment]
(Please forgive me if this is crazy.) When I encountered this problem, my first thought is that I wanted to write some grammar (e.g. in BNF format) that I would match against the AST, and I could have callbacks that act on the matches. 

In the end, [here is what I did](https://gist.github.com/kljensen/b4d4580b678d44d2d85e07fc1e450c1c).

**Comment by tarleb** [comment]
Not crazy. An xpath-like query language has been requested before in #4541. I hope to revisit that issue soon.

I really like [panflute](http://scorreia.com/software/panflute/), where elements have [prev and next]](http://scorreia.com/software/panflute/code.html#panflute.base.Element.prev] properties linking to the previous and next element sibling, respectively. Unfortunately, this is difficult to do with the way Lua filters work right now.

**Comment by tarleb** [comment]
Maybe we can somehow use a [zipper](https://en.wikibooks.org/wiki/Haskell/Zippers) to walk the AST in a more flexible way. This should give us access to parent elements as well. Problem: we'll have to find a way to marshall elements to Lua lazily, or we'll likely run into performance problems.

**Comment by jgm** [comment]
> allowing ListOfInlines as a filter function, which is run on the document via the [Inline] -> [Inline] instance of Text.Pandoc.Walkable;

This seems like the most obvious approach, if you can marshall a lua function to an `[Inline] -> [Inline]`.

**Comment by jgm** [comment]
Adding a zipper interface to the Pandoc AST is a nice idea; this could go in pandoc-types. If the heavy lifting is done there, maybe it would be fairly simple to make it available in lua?
