### ISSUE TITLE
latex reader misinterprets arguments to begin environment 

### ISSUE THREAD

**Issue by hoclun-rigsep** [jgm/pandoc#6039]
Pandoc 2.8.1 on macOS 10.14.5
```
$ pandoc -f latex -t markdown
> \begin{wrapfigure}{r}[2.5in]{4in}\centering\includegraphics{agenda.png}\caption{The
Approval Queue}\end{wrapfigure} In the ``Approval Queue'' view, officers

r\[2.5in\]4in![image](agenda.png)

In the "Approval Queue" view, officers
```

Looks like the reader is not getting that these bits are arguments to the begin environment latex command.

**Comment by jgm** [comment]
There's no way pandoc can know about every single latex environment defined by every latex package.  It tries to handle basic latex + some of the more common packages.

Without knowing how the environment is defined, there isn't a way to know what parts are arguments to the environment and what parts are contents.

**Comment by hoclun-rigsep** [comment]
Oh, I see. I thought the syntax for beginning an environment and providing arguments was a latex standard. I can work around.

**Comment by jgm** [comment]
No, actually each environment can define its own behavior...
