### ISSUE TITLE
\textbf<1>{} not supported by the current beamer writer

### ISSUE THREAD

**Issue by bozito** [jgm/pandoc#6043]
Currently, this
`\textbf<1>{Bold Text On Slide1}`
does not work correctly with pandoc beamer output ( with pandoc 2.7.3 ).

The generated tex is:
`\textbf<1\textgreater\{Bold Text On Slide1\}`
instead of:
`\textbf<1>{Bold Text On Slide1}`

One ugly workaround is:
`$\text{\textbf<1>{Bold Text On Slide1}}$`
that gets correctly translated into:
`\(\text{\textbf<1>{Bold Text On Slide1}}\)`

Is there a way to fix this?

Thanks.

**Comment by mb21** [comment]
can you try in the newest pandoc version?

**Comment by bozito** [comment]
I just tried with 2.9.1.1 and the issue is still there.
BTW, the workaround can be simplified a bit: `\text{\textbf<1>{Bold Text On Slide1}}`.

**Comment by mb21** [comment]
so what's the exact command and input/output?

**Comment by bozito** [comment]
Here we go (mwe.md):
```
---
#  pandoc -f  markdown -t beamer mwe.md -o mwe.tex
...
# Slide
- \textbf<1>{Bold Text On Slide1}
- \text{\textbf<1>{Bold Text On Slide1}}
```

The output is (mwe.tex):
```
\begin{frame}{Slide}  
\protect\hypertarget{slide}{}
\begin{itemize}
\item
  \textbf<1\textgreater\{Bold Text On Slide1\}
\item
  \text{\textbf<1>{Bold Text On Slide1}}
\end{itemize}
\end{frame}
```

Note that running `pandoc  -f  markdown -t beamer mwe.md -o mwe.pdf` fails:
```
! Paragraph ended before \beamer@sortzeroread was complete.
<to be read again> 
                   \par 
l.101
```

**Comment by agusmba** [comment]
I'm a bit rusty on my latex, what is `<1>` supposed to do?

**Comment by bozito** [comment]
That's a beamer thing, not really a LaTeX one.
It's an overlay specification, used by beamer to generate poor-man's animations on the slide by creating for each slide several pages with slightly different content.
Here, `<1>` means that the command \textbf should only be present on the first page of the slide, the text being normal on all the other.

For example:
```
# Slide
- \textbf<1>{Bold First}
- \textbf<2>{Bold Second}
- \textbf<3>{Bold Third}
```

Should result in a beamer pdf file with 3 pages that will all read:
```
# Slide
- Bold First
- Bold Second
- Bold Third
```

but with line _p_ in bold on page _p_:

# Slide
- **Bold First**
- Bold Second
- Bold Third
# Slide
- Bold First
- **Bold Second**
- Bold Third
# Slide
- Bold First
- Bold Second
- **Bold Third**

**Comment by agusmba** [comment]
Ok, thanks for the clarification.

I know it may not be a clean solution, but have you tried using spans? (esp. since your workaround is shorter already)

```markdown
# Slide
- `\textbf<1>{Bold Text On Slide1}`{=latex}
- \textbf<1>{Bold Text On Slide1}
- \text{\textbf<1>{Bold Text On Slide1}}
```

The first line should work now

**Comment by jgm** [comment]
I've fixed this so that the whole thing is passed through as raw tex.
However, a better approach would be to use spans with classes, and a lua filter to add the overlay specifications.  This is better because it would let you use markdown inside the contents. E.g.,
```
[Bold text with [link](http://example.com) and @citation on slide]{only=1}
```
and then your lua filter can find Span elements with attribute only and convert them to raw tex
```
\only<1>{Bold text ... }
```
