### ISSUE TITLE
Pandoc API: Problems with EPUB generation

### ISSUE THREAD

**Issue by bmc** [jgm/pandoc#6060]
Feel free to close this issue and tell me I'm a moron for missing something in the docs (or the Pandoc source, which I also scanned), but ...

I'm using the Pandoc API to parse Markdown and generate HTML and EPUB3. When passing the `Pandoc` AST to `writeEPUB3`, I get the error:

```
PandocCouldNotFindDataFileError "data/data/epub.css" 
```
I'm using code like this to produce the AST:

```haskell
parseMarkdown :: T.Text -> Either PandocError Pandoc
parseMarkdown markdown =
  let desiredExtensions = [Ext_line_blocks, Ext_escaped_line_breaks,
                           Ext_smart, Ext_fenced_code_attributes,
                           Ext_fenced_code_blocks, Ext_yaml_metadata_block,
                           Ext_backtick_code_blocks ]
      extensions        = setExtensions desiredExtensions
      opts              = def { readerExtensions = extensions }
  runPure $ readMarkdown opts markdown
```
I'm then taking the AST and passing it to `writeEPUB3`, more or less like this:

```haskell
import qualified Text.Pandoc.Writers as PW

runPure $ PW.writeEPUB3 def ast
```

I looked for an option I could pass to specify the location of the EPUB CSS file, but I didn't see one. (If I missed it somewhere, I'd appreciate a pointer.)

I'm building with `stack`. I tested this behavior with Pandoc 2.7.3 (the latest one in Stackage) and with Pandoc 2.9.1.1 (after some laborious updates to `stack.yaml`). The problem occurs in both.

Any assistance is gratefully accepted and appreciated.

**Comment by jgm** [comment]
This is one of the data files (`data-files` stanza in Cabal).  `cabal install` used to install these in a sensible location where pandoc could find them (Cabal provides a function that gives their path).  But if you just do `cabal build`, or if you use stack, you're better off compiling with the `embed_data_files` flag, which will embed the data files as binary blobs and avoid this sort of issue.

**Comment by jgm** [comment]
Oh, you said you use stack.  Well then, put something like this in your stack.yaml:
```
flags:
  pandoc:
    embed_data_files: true
```

**Comment by bmc** [comment]
Added. Still seeing the error, I'm afraid. :-(

**Comment by bmc** [comment]
Hmm. However...

I may need to force a recompile of the dependencies to make that work. Trying that now.

**Comment by bmc** [comment]
Okay, that fixed it. Thanks. Closing. May all your issues be this easily disposed.
