### ISSUE TITLE
Asciidoctor style smart quotes in markdown?

### ISSUE THREAD

**Issue by esnahn** [jgm/pandoc#6063]
Feature request/asking for guidance: related to the need for [partial word quotes](https://github.com/jgm/pandoc/issues/6057)

After reviewing many markup's solutions for smart quotes, now I think that maybe one heuristic algorithm can't solve all the edge cases between quotes and apostrophes.

But in the process I found Asciidoctor's 'dumb' smart quotes and found it useful for my case. You can assign opening and closing quotes as you want, like latex's ligature.

```
"`double curved quotes`"
'`single curved quotes`'
Olaf's desk was a mess.
All of the werewolves`' desks were a mess.
Olaf had been with the company since the `'60s.
```
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#formatted-text

Also it is already [implemented in asciidoc(tor) format.](https://github.com/jgm/pandoc/commit/5affa30e8ad8b5c6ce31240ecd271fd4cccab219) 

So what I want is replacing markdown's smart extention with this version of 'smart' quotes. But I am not sure of the best way to do that.

1. Would it be possible to officially create _smartbacktick(?)_ extension in pandoc's markdown?
2. Can this be accomplished by a lua filter? (maybe by me)
3. Any other tips or suggestions

Thanks!

**Comment by jgm** [comment]
Why not just use literal unicode curly quotes in your markdown text, which you can already do?
That has the advantage of actually looking good, and not conflicting with existing backtick code syntax.

You couldn't do this with a lua filter because by the time the filter gets the AST, the backticks will have created code spans.
