### ISSUE TITLE
Sample filters in documentation no longer compile

### ISSUE THREAD

**Issue by elliottslaughter** [jgm/pandoc#6065]
The page https://pandoc.org/filters.html lists a number of example filters that no longer compile with Pandoc 2.9.1.1 (and probably haven't for a long time).

For example, taking `behead.hs` as listed on that page, I cannot get either the pre- or post- 1.14 versions to compile. The two issues with it seem to be (a) it needs to swap `Text` for `String`, and (b) everything needs to be rewritten to use `PandocMonad`.

This is actually surprisingly difficult to fix if you're not a Haskell expert. I spent about 30 minutes trying to fix up this example, eventually resulting in the following:

```
-- behead.hs
import Data.Text
import Data.Text.IO
import Text.Pandoc
import Text.Pandoc.Walk (walk)

behead :: Block -> Block
behead (Header n _ xs) | n >= 2 = Para [Emph xs]
behead x = x

readDoc :: Text -> Pandoc
readDoc s = case runPure $ readMarkdown def s of
                 Right doc -> doc
                 Left err  -> error (show err)

writeDoc :: PandocMonad m => Pandoc -> m Text
writeDoc doc = writeMarkdown def doc

unwrap :: Either PandocError Text -> Text
unwrap s = case s of
                Right doc -> doc
                Left err -> error (show err)

main :: IO ()
main = Data.Text.IO.interact (unwrap . runPure . writeDoc . walk behead . readDoc)
```

Which works, but... wow is that ugly. Is this really how we want users to interact with Pandoc?

I was going to rewrite it to use `toJSONFilter` but I see that example is already further down the page. That version is so much shorter that I wonder if it would be better to just move it up and bypass the Markdown version entirely.

At any rate, one way or another we should make sure all the examples on the page actually compile.

**Comment by jgm** [comment]
Agreed. I'll rewrite it and just start right off with `toJSONFilter`.
