### ISSUE TITLE
Citations inside Listings Captions do not work

### ISSUE THREAD

**Issue by cagix** [jgm/pandoc#6068]
Citations inside listings captions won't be translated at all:

    ```{.python caption="The preprocessing step, cf. [@Nystrom2018]" #lst:huh}
    def foo():
    """ Wuppie! """
    pass
    ```

yields something like (using `pandoc --filter=pandoc-citeproc --listings xxx.txt -o xxx.pdf`)

    Listing 1: ]The preprocessing step, cf. [@Nystrom2018]

However, I'd expect something like

    Listing 1: The preprocessing step, cf. (Nystrom 2018)

Citations in table captions and figure captions work, see attached MWE.

[xxx.txt](https://github.com/jgm/pandoc/files/4063624/xxx.txt)
[xxx.pdf](https://github.com/jgm/pandoc/files/4063623/xxx.pdf)

(using pandoc 2.9.1.1, debian)

**Comment by jgm** [comment]
All attributes are treated as plain strings.  I think it would be confusing to diverge from this behavior.
However, you can use the [`pandoc-crossref` filter](https://github.com/lierdakil/pandoc-crossref/blob/master/docs/index.md):

````
Listing: Listing caption *with formatting* and @citation.

```{#lst:code .haskell}
main :: IO ()
main = putStrLn "Hello World!"
```
````

**Comment by cagix** [comment]
Well, I see your point.

On the other hand, captions in figures and tables *are* processed by pandoc, just captions in listings are ignored. This is kind of unexpected for me.

However, pandoc-crossref is not a real solution for me because I'd need some kind of cabal and Haskell installation ...

I would find it helpful if all captions were treated uniformly by pandoc.
