### ISSUE TITLE
Windows zip file paths

### ISSUE THREAD

**Issue by jimhester** [jgm/pandoc#6071]
In pandoc releases (at least between 2.0.2 and 2.7.3) the windows binary zip files always included a versioned subdirectory.

```
unzip -l pandoc-2.0.2-windows.zip
Archive:  pandoc-2.0.2-windows.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  11-12-2017 12:55   pandoc-2.0.2/
    20434  11-12-2017 12:55   pandoc-2.0.2/COPYING.rtf
     7868  11-12-2017 12:55   pandoc-2.0.2/COPYRIGHT.txt
   194704  11-12-2017 12:55   pandoc-2.0.2/Pandoc User's Guide.html
 43686939  11-12-2017 12:55   pandoc-2.0.2/pandoc-citeproc.exe
 52445211  11-12-2017 12:55   pandoc-2.0.2/pandoc.exe
---------                     -------
 96355156                     6 files
```

However pandoc 2.8 and above no longer have this sub-directory.

```
unzip -l pandoc-2.8-windows-x86_64.zip
Archive:  pandoc-2.8-windows-x86_64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    20434  11-22-2019 16:58   COPYING.rtf
   281471  11-22-2019 16:58   MANUAL.html
 74802176  11-22-2019 16:58   pandoc-citeproc.exe
104802816  11-22-2019 16:56   pandoc.exe
---------                     -------
179906897                     4 files
```

This change broke my [setup-pandoc](https://github.com/r-lib/actions/tree/master/setup-pandoc#setup-pandoc) GitHub Action to install pandoc. https://github.com/r-lib/actions/issues/34

I wasn't sure if this was an intentional change or not...

**Comment by jgm** [comment]
No, not intentional.
I agree it's best to have a versioned directory.

**Comment by jgm** [comment]
Trying a new script here:
https://github.com/jgm/pandoc/commit/31f9dab6b5a776feaec4bf5ec2649196157d5aef/checks?check_suite_id=407349285

**Comment by jgm** [comment]
Second attempt:
https://github.com/jgm/pandoc/commit/89aac322851e70ee838652b6246f3566007f2a56/checks?check_suite_id=407983820

**Comment by jgm** [comment]
OK, this is working now in the release candidate builds and will be fixed in next release.

**Comment by jimhester** [comment]
Great, thanks!
