### ISSUE TITLE
Compact List Spacing Regression Bug in .docx

### ISSUE THREAD

**Issue by mangelico15** [jgm/pandoc#6072]
### Pandoc versions starting with 2.8.0 don't style compact lists correctly in .docx

Pandoc versions prior to 2.8.0 assigned the style "Compact" to compact lists, which has 1.8pt Before and After spacing.  On the other hand, starting with Pandoc version 2.8.0, the style changed to "Normal" with 0pt spacing Before and 10pt spacing After.

Steps to reproduce: Generate .docx from enclosed .md using:
```
ren mcq.txt mcq.md
pandoc --from markdown --to docx --output mcq.docx mcq.md
```
I enclosed two screen captures to show the difference in styling between Pandoc versions 2.7.3 and 2.9.1.1

[mcq.txt](https://github.com/jgm/pandoc/files/4080834/mcq.txt)
![2 7 3](https://user-images.githubusercontent.com/60038699/72665790-bb394300-39d9-11ea-9bc3-942bac9f236a.png)
![2 9 1 1](https://user-images.githubusercontent.com/60038699/72665793-be343380-39d9-11ea-8084-448f396f2097.png)

**Comment by jgm** [comment]
I found a relevant item in the pandoc 2.8 changelog:
```
  * Docx writer:

    + Preserve built-in styles in DOCX with custom style (Ben Steinberg,
      #5670).  This change prevents custom styles on divs and spans
      from overriding styles on certain elements inside them, like
      headings, blockquotes, and links. On those elements, the
      "native" style is required for the element to display correctly.
      This change also allows nesting of custom styles; in order to do so,
      it removes the default "Compact" style applied to Plain blocks,
      except when inside a table.
```

See #5670 for the motivation for this change.  I think we should try to find some way to restore the difference between compact and non-compact lists.

**Comment by jgm** [comment]
I've added a PR that fixes this issue, but there may be side-effects I'm not anticipating.
@bensteinberg - It would be helpful if you could take a look.  I didn't quite understand why it was necessary to override the Compact styles to enable nesting of custom stypes.

**Comment by bensteinberg** [comment]
@jgm, I'll take a look.

**Comment by bensteinberg** [comment]
@jgm, I think this was an oversight on my part, and I think your fix looks correct. Thanks for checking with me, and thanks for the fix.
