### ISSUE TITLE
Could not parse YAML metadata error

### ISSUE THREAD

**Issue by alexeykosh** [jgm/pandoc#6074]
pandoc version: 2.9.1.1
operating system: OSX 10.15.2

I was migrating on a new computer and when trying to run pandoc the following error occured:

`[WARNING] Could not parse YAML metadata at line 40 column 1: Duplicate key in mapping: Scalar (Pos {posByteOffset = 248, posCharOffset = 248, posLine = 19, posColumn = 0}) (SUnknown Nothing "geometry")`

The command that I was executing goes as follows: 

`pandoc --metadata bibliography=biblio.bib --filter pandoc-citeproc main_text.md -o final.pdf`

My files are here:
[issue.zip](https://github.com/jgm/pandoc/files/4083670/issue.zip)

**Comment by jgm** [comment]
The message pandoc emits tells you exactly what the problem is.  You have a duplicate `geometry` key in your YAML block.
