### ISSUE TITLE
No bibliography items inserted when using `nocite: @*` in a metadata YAML file

### ISSUE THREAD

**Issue by brouberol** [jgm/pandoc#6076]
It appears that including `nocite: @*` in the metadata file causes the un-cited references to be ignored. However, including `nocite: @*` directly in my markdown file, in a YAML metadata block, causes the these references to be included in the bibliography.  

### Steps to reproduce

```yaml
# metadata.yaml
link-citations: true
reference-section-title: References
bibliography: test-biblio.bib
nocite: |
  @*
...
```

```markdown
<!-- chapters/99-references.md -->

# References

```

```bibtex
% test-biblio.bib

@article{small,
author = {Freely, E.},
title = {A small paper},
journal = {The journal of small papers},
year = 1997,
volume = {-1},
note = {to appear},
}

@article{big,
author = {Ern, Hugh},
title = {A big paper},
journal = {The journal of big papers},
year = 7991,
volume = {MCMXCVII},
}
```

I execute the following commands to convert the markdown chapters into both HTML and EPUB

```bash
% pandoc \
    --toc --toc-depth=2 --webtex --css=style.css \
    --metadata-file=metadata.yaml --filter=pandoc-citeproc \
     -o build/epub/book.epub chapters/*.md

% pandoc \
    --toc --toc-depth=2 --webtex --css=style.css \
    --metadata-file=metadata.yaml --filter=pandoc-citeproc \
    --standalone --to=html5 -o build/html/book.html chapters/*.md
```

In both cases, the References section is empty. For example, the generated HTML is

```html
<h1 id="references">References</h1>
```

instead of the expected

```html
<h1 id="references">References</h1>
<div id="refs">
<div id="ref-small">
<p>Freely, E. 1997. “A Small Paper.” <em>The Journal of Small Papers</em> -1.</p>
</div>
<div id="ref-small">
<p>Ern, Hugh “A Big Paper.” <em>The Journal of Big papers</em></p>
</div></div>
```

However, if I add the following YAML block at the top of my markdown file, then all un-cited citations get inserted in the References section.

```yaml
# chapters/01-test.md
---
nocite: |
  @*
...
```

### Versions

```
% pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: /Users/balthazarrouberol/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

% pandoc-citeproc --version
pandoc-citeproc 0.15
```

### External links

[pandoc-discuss](https://groups.google.com/forum/?pli=1#!topic/pandoc-discuss/5-CTTULKddE)

**Comment by jgm** [comment]
Oh, you've got quite an old version of pandoc. Try upgrading.
I can't reproduce your issue with the latest version.

**Comment by brouberol** [comment]
Indead, after upgrading to pandoc to `2.9.1.1` and `pandoc-citeproc` to `0.16.4.1`, I can use `nocite: '@*` in the metadata file itself and have all the un-cited references inserted. 

Thanks!
