### ISSUE TITLE
Pandoc lost the image caption numbers while convert docx to markdown or html

### ISSUE THREAD

**Issue by totumfaktum88** [jgm/pandoc#6080]
Hi,

i trying convert docx documents to html for process the content automatically for an application. This documents contains tables with images (every column contains an image) with caption numbering.

The Word use table head in default options for the first table rows. 
When i convert the document to html the table head rows loses the generated numbers from the caption like this:

```
<table>
<thead>
<tr class="header">
<th><p><img src="media/image1.jpeg"/></p>
<p>. picture</p></th>
<th><p><img src="media/image2.png"/></p>
<p>. picture</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p><img src="media/image3.png"/></p>
<p>3. picture</p></td>
<td></td>
</tr>
</tbody>
</table>

```

Anyone has same experience about this?

**Comment by jgm** [comment]
That's as expected.  We can't generally handle field values at all.

**Comment by totumfaktum88** [comment]
Thanks for your help!
