### ISSUE TITLE
Re-write links to other source files when collating 

### ISSUE THREAD

**Issue by kasbah** [jgm/pandoc#6081]
Say you have 

```
$ tree
.
├── 1.md
└── 2.md

$ cat 1.md
# 1
[link](2.md)

$ cat 2.md
# 2

```

And you do

```
pandoc 1.md 2.md -o example.pdf
```

Wouldn't it be nice if the link was re-written to link internally?

**Comment by jgm** [comment]
It's not really possible because pandoc doesn't keep track of what files things are from: the input is concatenated before being sent to the parser.

Note, however, that you could do something like this and it will work:

```
$ cat 1.md
# 1
[2]

$ cat 2.md
# 2
```
