### ISSUE TITLE
Page suffix for citation is omitted

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#6082]
I am using `pandoc` v2.9.1.1.

I have found that page suffix (p. or pp.) after citation key is omitted when processed.

Please see the below:

```markup
"A is B" [@key, p. 100].
```

The above is rendered as follows:

```markup
"A is B" (last_name, 100).
```

The expected output should be as follows:

```markup
"A is B" (last_name, p. 100).
```
Would there be any way to fix this issue?

**Comment by jgm** [comment]
This depends on the CSL style you use.  You are apparently using a style which doesn't put in the 'p.' for page.  Try another one.

**Comment by jgm** [comment]
See manual under `--csl`.
