### ISSUE TITLE
Release downloads fail with a network error

### ISSUE THREAD

**Issue by imoutsatsos** [jgm/pandoc#6089]
I have repeatedly tried to download pandoc-2.9.1.1-win64 (as well as zip) and in every case the download fails with a network error . I have no problems with other internet sites. 
![image](https://user-images.githubusercontent.com/3408226/73173182-c0317d00-40d2-11ea-8fb2-55d658462b98.png)

Using Chrome Version 79.0.3945.130 (Official Build) (64-bit) on Windows 10

**Comment by mb21** [comment]
Those are hosted by github... not much we can do about it except wait until they fix it... or maybe it's your DNS or something? seems to work for me from Switzerland: https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-windows-x86_64.msi

**Comment by imoutsatsos** [comment]
@mb21 Thanks for the feedback! I would have thought that if this was a DNS issue the download would never start. Instead it always seems to download a small chunk and then eventually fails. Good to know its not a general issue, but for me here in the US, Boston area has been an issue for more than 12 hours. 
![image](https://user-images.githubusercontent.com/3408226/73173626-cd02a080-40d3-11ea-97c4-088177028277.png)

**Comment by jgm** [comment]
I'm not seeing a problem.  If you're still having the issue, then I think you need to contact GitHub about it; there's nothing we can do here.
