### ISSUE TITLE
HTML-writer should preserve bold enumeration from Latex

### ISSUE THREAD

**Issue by jups23** [jgm/pandoc#6094]
I have LaTeX code using bold enumerations which I want to convert to Markdown and then to epub3. With "bold enumerations" I mean that the following components are bold:
a) the enumeration label
b) the text items.
See screenshot:
<img width="139" alt="bold-enumeration-html" src="https://user-images.githubusercontent.com/217980/73343657-fcb5d200-42a6-11ea-953e-f6cdc467edc9.png">

The convention in LaTeX seems to be using the `\bfseries` command: https://tex.stackexchange.com/a/116103.

## Input
The following minimal example illustrates my LaTeX:

```
\begin{enumerate}\bfseries
  \item{first item}
  \item{second item}
\end{enumerate}
```

## Actual output

```
<ol>
<li><p><span>first item</span></p></li>
<li><p><span>second item</span></p></li>
</ol>
```

### Expected output HTML writer (epub)

```
<ol style="font-weight: bold;">
<li><p><strong>first item</strong></p></li>
<li><p><strong>second item</strong></p></li>
</ol>
```
### Expected output Markdown
I could imagine the Markdown writer to produce:

```
::::: {.ol-bold}
1. *first item*
2. *second item*
:::::
```
Then, I could add a css rule:
```
.ol-bold {
  font-weight: bold;
}
```
Why I propose to fence the list in a div? Because I do not know if there is another way in Markdown to bold the enumeration labels.

# Further discussion
## Input 2
Let's assume I could change the LaTeX code from using \bfseries to something else which would result in the desired HMTL/Markdown. For example, I could wrap the enumeration items within `\textbf{}` like this:

```
\begin{enumerate}
  \item{\textbf{first item}}
  \item{\textbf{second item}}
\end{enumerate}
```

## Output 2
```
<ol style="font-weight: bold;">
<li><p><strong>first item</strong></p></li>
<li><p><strong>second item</strong></p></li>
</ol>
```
However, this HTML gets rendered in an unsatisfactory manner because the item labels are not bold. Seen screenshot and compare it to the one given on top of this post:
<img width="131" alt="Workaround is not working" src="https://user-images.githubusercontent.com/217980/73344158-dba1b100-42a7-11ea-9383-b31d6a0e8fc0.png">

I would appreciate your comments on my observation and proposal. Thank you for the excellent tool which has enabled me to do so much!!!

## System info
pandoc version: 2.9.1.1

**Comment by mb21** [comment]
I guess this is out of scope for pandoc... from https://pandoc.org/MANUAL.html#description:

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size.

**Comment by jups23** [comment]
@mb21 thank you for your evaluation.
What would be your suggestion to produce an epub which preserves the bold formatting of LaTeX also for enumerations?
Editing the HTML or Markdown which pandoc produces?

**Comment by alerque** [comment]
@jups23 That looks like a job to either pre-process (to wrap those in some env you can interpret later) or use a Lua filter to detect and modify during conversion. Either way the point would be to give yourself something to then style in post-processing. As mb21 noted style information about bold/notbold list markers is simply outside the scope of Pandoc's AST (and Markdown and 90% of document formats for that matter, LaTeX is simply has much richer presentation information than most).

One idea would be to pre-process and convert tho `\bfseries` to an enumerate attribute where you overload the list numbering style so you pass regular lists through to Pandoc as, say, numstyle=Decimal but pass bold lists as numstyle=UpperAalpha, then use a Lua filter to detect list types and wrap the latter in a Div, then convert to Decimal.

**Comment by jgm** [comment]
In general we don't handle well plain tex things like `\bfseries` which change formatting for everything going forward.  In principle we could handle this better.  But even if we did, there'd be no way to get the enumeration labels boldfaced.  Nothing in the Pandoc AST corresponds to that.  The Strong element only applies to inlines.  So I'm going to call this out of scope.

**Comment by jups23** [comment]
thank you for your help!
