### ISSUE TITLE
Feature request: Support for Outlook's .msg format

### ISSUE THREAD

**Issue by ad-si** [jgm/pandoc#6098]
- Short description: https://www.loc.gov/preservation/digital/formats/fdd/fdd000379.shtml
- Specification: https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxmsg/b046868c-9fbf-41ae-9ffb-8de2bd4eec82

**Comment by tarleb** [comment]
Hi Adrian!  If I'm not mistaken, then "msg" is a file format which may wrap text, HTML, or other information and there doesn't seem to be markup information in the format itself. If that is the case then it's probably out of scope for pandoc.

**Comment by ad-si** [comment]
As far as I can tell every `.msg` has one main `Message object`:

> A set of properties that represents an email message, appointment, contact, or
other type of personal-information-management object. In addition to its own properties, a
Message object contains recipient properties that represent the addressees to which it is
addressed, and an attachments table that represents any files and other Message objects that
are attached to it.

And otherwise it can embed other files / attachments, similar to HTML (which is supported by pandoc):

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
  <img
    src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
      AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
      9TXL0Y4OHwAAAABJRU5ErkJggg=="
    alt="Red dot"
  />
</body>
</html>
```

So I think it should be supported.

**Comment by tarleb** [comment]
I looked into this some more recently. The msg container format is basically an in-file version of the FAT file system. There is very little hope for pandoc supporting this as long as there is no Haskell library handling the container format, which again seems unlikely to be developed in the future. Thus closing.

**Comment by ad-si** [comment]
Aha Ok, thanks for looking into this!
