### ISSUE TITLE
Enhancement / Feature Request: csv (comma separated value) to MediaWiki

### ISSUE THREAD

**Issue by StewAlexanderACC** [jgm/pandoc#6100]
Apparently there is no convenient way (outside of using some sort of web portal thing that exposes potential security risks if you upload sensitive data) to export CSV or _Comma Separated Values_ data to MediaWiki format.

It would be a nice enhancement to Pandoc if it would convert csv formatted files

**Comment by StewAlexanderACC** [comment]
Just import this code and tweak it a little (from https://gist.github.com/0ncorhynchus/6605020)
```
"""
 Usage: python csv2wikitable.py csv_file
 -----
 input: csv format
 output: wiki table format
"""

import sys

if __name__ == '__main__':
	argvs = sys.argv
	argcs = len(argvs)
	if argcs != 2:
		sys.stderr.write('Usage: python %s csv_file\n' % argvs[0])
		sys.exit(1)
	filename = argvs[1]

	infile = open(filename, 'r')
	inlines = infile.readlines()
	infile.close()

	outlines = []
	for line in inlines:
		outlines.append(line.replace(',','|'))

	outfile = open('wiki_'+filename, 'w')
	outfile.write('{|\n')
	outfile.writelines(outlines)
	outfile.write('|}')
	outfile.close()
```

**Comment by jgm** [comment]
I kind of like this idea:  CSV -> pandoc table (hence any format).  We could assume the first row to be headings.

One problem, though, is that there are many ways of doing CSV.  But maybe we could just handle https://tools.ietf.org/html/rfc4180 style.

**Comment by jgm** [comment]
I implemented this.  It could use some real-world testing.

**Comment by mb21** [comment]
cool, but isn't this a bit of duplication with [`Text.Pandoc.CSV`](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/CSV.hs)?

**Comment by jgm** [comment]
Geez, I'd completely forgotten about Text.Pandoc.CSV!

**Comment by jgm** [comment]
I'll use the code from there instead; that makes this module trivial.

**Comment by mb21** [comment]
:-)

**Comment by StewAlexanderACC** [comment]
Thanks all, even one format would be better than none...

**Comment by StewAlexanderACC** [comment]
@jgm 

I'd love to test any implementation, FYI

**Comment by alerque** [comment]
@StewAlexanderACC Everything is in `master`, you can compile and test yourself, or check out artifacts from CI builds.

**Comment by lollipopman** [comment]
love this feature, thanks so much for adding it @jgm!
