### ISSUE TITLE
Syntax highlight style ignored when no language provided instead of using default

### ISSUE THREAD

**Issue by noraj** [jgm/pandoc#6104]
## Command

```
$ pandoc basic-example.md \
--from markdown \
--to pdf \
-o bug.pdf \
--pdf-engine=pdflatex \
--highlight-style breezedark
```

## Input document

~~~markdown
---
title: "Example PDF"
author: [Author]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
lang: "en"
book: true
...

# fenced code blocks

## with lang

```java
public class Example implements LoremIpsum {
    public static void main(String[] args) {
        if(args.length < 2) {
            System.out.println("Lorem ipsum dolor sit amet");
        }
    } // Obscura atque coniuge, per de coniunx
}
```

## without lang

```
public class Example implements LoremIpsum {
    public static void main(String[] args) {
        if(args.length < 2) {
            System.out.println("Lorem ipsum dolor sit amet");
        }
    } // Obscura atque coniuge, per de coniunx
}
```

## with default

```default
public class Example implements LoremIpsum {
    public static void main(String[] args) {
        if(args.length < 2) {
            System.out.println("Lorem ipsum dolor sit amet");
        }
    } // Obscura atque coniuge, per de coniunx
}
```
~~~

## output document

![image](https://user-images.githubusercontent.com/16578570/73616527-cebcee80-4614-11ea-93d8-ae68ecff1b9e.png)

## wrong behavior

if no language is specified for markdown fenced code block the style from `--highlight-style` is ignored.

## expected behavior

when no language is specified for markdown fenced code block the style from `--highlight-style` is respected like if the `default` language was provided.

**Comment by noraj** [comment]
## Workaround

My temporary workaround was to make a _match and replace_ regex search with VSCode:

![image](https://user-images.githubusercontent.com/16578570/73616644-4b040180-4616-11ea-982f-44e8b1c5c092.png)

To add `default` to all fenced code blocks not having a language.

**Comment by jgm** [comment]
I don't consider this a bug. The highlighting style is for highlighted code.  One might use a code block (without a syntax specification) for other kinds of things.  If you want code with no special highlighting except the style's background and foreground, use `default`.  You don't need to do it manually; you could use a lua filter to add it or you could use indented code blocks and `--indented-code-classes=default`.

**Comment by noraj** [comment]
> If you want code with no special highlighting except the style's background and foreground

I agree if one didn't set teh flag `--highlight-style`, but when you set `--highlight-style` yo uactually want syntax highlight style to be applied everywhere. That's what all syntax highlighter like prism.js, highlight?js, etc. are doing.

**Comment by noraj** [comment]
Is there an equivalent to `--indented-code-classes=default` ?

**Comment by jgm** [comment]
> when you set --highlight-style you actually want syntax highlight style to be applied everywhere.

Maybe you do.  I'm not sure about *everybody*.  I've certainly had occasions where I've wanted to be able to distinguish highlighted code from other kinds of verbatim content.

**Comment by noraj** [comment]
>  I've certainly had occasions where I've wanted to be able to distinguish highlighted code from other kinds of verbatim content.

I agree with you, I just think the opposite behavior is expected. Like default fenced code block are styled even without a language provided when `--highlight-style` is provided and are not if a pandoc specific lang like `verbatim` is set or maybe a `--no-highlight-style-verbatim` that doesn't apply style to fenced code blocks **when** and only when `--highlight-style` is used.

Highlight libs I tried that styles the fenced code blocks without a lang:

- highlight.js 
- prism.js
- pygments
- rouge

I also understand you prefer to avoid introducing braking changes.

**Comment by noraj** [comment]
Seems like the `--indented-code-classes=default` is also ignored.
