### ISSUE TITLE
A (perfectly legitimate) ampersand (&) in a \cite is not accepted by pandoc

### ISSUE THREAD

**Issue by bothide** [jgm/pandoc#6110]
In pandoc 2.9.1 running

pandoc ampersanderror.tex -t html
where the LaTeX file ampersanderror.tex is
\documentclass[oneside,12pt,a4paper]{memoir}

\usepackage{lualatex-math,luatextra,luaotfload}
\usepackage{unicode-math,mathtools}
\usepackage[swedish]{babel}
\usepackage[autostyle,swedish=guillemets*,english=british]{csquotes}

\begin{document}

Hello world \cite{Tamburini&al:MNRASL:2020} 

\end{document}

Crashes with the following message:

Error at "source" (line 11, column 28):
unexpected &
Hello world \cite{Tamburini&al:MNRASL:2020} 
                           ^
"

However, ampersand "&" is a legitimate (and common) character in cites like the one here.  Is this a bug or is there an option to make pandoc accept this?

**Comment by jgm** [comment]
No, but this is easily fixed.
