### ISSUE TITLE
Feature request: filter profiling flag

### ISSUE THREAD

**Issue by SuperV1234** [jgm/pandoc#6112]
I propose the addition of a new `--profile-filters` flag that would report something like the following on the command line, after a complete execution of `pandoc`:

```
filter "foo" took 1235ms to execute
filter "bar" took 524ms to execute
filter "baz" took 5212ms to execute
```

This would be useful to identify expensive filters that could be optimized.

**Comment by jgm** [comment]
Maybe we could put something in `applyFilter` that tells you when it is running each filter when `--verbose` is set.  This would give you a visual indication.  (We could also add timings I suppose.)
This wouldn't require a new option.

**Comment by SuperV1234** [comment]
Awesome. Thank you so much.
