### ISSUE TITLE
MediaWiki writer: default section heading deviates from standard formatting

### ISSUE THREAD

**Issue by vdurdux** [jgm/pandoc#6118]
The  [MediaWiki standard format](https://www.mediawiki.org/wiki/Help:Formatting#Level_2) recommends starting section headings at level, as level 1 is the page title (and thus HTML h1 header).

But the MediaWiki writer starts sections from level 1.

I would suggest adding after line 137 in `pandoc/src/Text/Pandoc/Writers/MediaWiki.hs` an additional equal sign. As that would change the current behavior, it could also be added through a command line option in the same style as `--top-level-division` or `--number-offset`

**Comment by jgm** [comment]
You could just use `--shift-heading-level-by=1`.

**Comment by vdurdux** [comment]
Thank you, sorry I browsed the writer options but not the reader ones…
