### ISSUE TITLE
wrong citation conversion

### ISSUE THREAD

**Issue by davidenitti** [jgm/pandoc#6119]
executing the command to convert latex to mediawiki with ieee citations:
`pandoc full_article.tex -f latex -t mediawiki -o NCE.wiki --bibliography bibliography/bibl.bib --metadata link-citations  --csl=ieee.csl -s`

The citations are converted in e.g.:
`[[[#ref-gutmann2010noise|1]]]`

however this is not working in mediawiki. Probably because the 3 parenthesis are not properly recognized. it should be converted in e.g.:
`[[#ref-gutmann2010noise|[1]]]`

that becomes [1] with the link

In alternative:
`[ [[#ref-gutmann2010noise|1]] ]`

 but this results in an additional space e.g. [ 1 ]

Version:
pandoc 2.9.1.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3

**Comment by jgm** [comment]
`[[#ref-gutmann2010noise|[1]]]` would be easy to generate instead!

**Comment by jgm** [comment]
Oh, wait -- I'm sorry, you're using pandoc-citeproc to generate these citations, so the fix isn't so easy after all.  Pandoc-citeproc links individuals numbers in the numerical citations, because you can have e.g. `[1,2,3]` where each links to a different item.  So we can't really change that.

**Comment by jgm** [comment]
One approach would be to use `&#91;` and `&#93;` for brackets when they're adjacent to links.

**Comment by jgm** [comment]
or more readably `&lbrack;` `&rbrack;`.
We could even use these across the board for `[` and `]` to avoid all problems of this kind.

**Comment by jgm** [comment]
Can you confirm that this will work?
```
&lbrack;[[#ref-gutmann2010noise|1]]&rbrack;
```

**Comment by davidenitti** [comment]
this works on mediawiki:
`[<nowiki/>[[#ref-gutmann2010noise|1]]]`
why this cannot be used?
` [[#ref-gutmann2010noise|[1]]]`
in any case how do I change the command? any idea to solve the problem? (whatever ways is welcomed! I'm not expert of pandoc

**Comment by jgm** [comment]
> why this cannot be used?

I explained this above.  If you had multiple citations like `[1,2,3]` then each number needs a separate link, so the brackets shouldn't be part of the link.

**Comment by davidenitti** [comment]
I see, @jgm  thanks for the reply. why did you close the issue? this is a bug, no?
The solution would be to make pandoc write this ` [<nowiki/>[[#ref-gutmann2010noise|1]]]`.
I don't know how and if this is possible without fixing the code.
I tried using `[<nowiki/>` instead of `[` as delimiter and I get the error:
```
pandoc-citeproc: ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 218:7 (7226)}
```
I didn't find a way to escape the character and still print ` [<nowiki/>[[#ref-gutmann2010noise|1]]]` in the output.

**Comment by jgm** [comment]
I closed it with a commit that fixes the issue.

**Comment by davidenitti** [comment]
ah thanks! sorry for bothering
