### ISSUE TITLE
Number-offset in Markdown to HTML conversion not being set

### ISSUE THREAD

**Issue by hccunningham** [jgm/pandoc#6121]
Using  pandoc 2.9.1.1 on MacOS 10.15.3, the command

    pandoc --standalone  --number-sections --number-offset=2 --toc -o Test.html Test.md

numbers the sections beginning with 3 (as expected), but umbers the table of contents beginning with 1. This worked corrected on some previous versions of pandoc.

I produced this error with the following simple file Test.html.
------
% TITLE

# One

## Sub Two
-----

**Comment by jgm** [comment]
Closed by 9c12024e072ea24f05e98f21dacaf1833a58c2e8
