### ISSUE TITLE
Performance degradation from 2.2.2.1 to 2.2.3.1 on org-mode files with many "_" characters on a line

### ISSUE THREAD

**Issue by jsomers** [jgm/pandoc#6127]
Consider the following org-mode file:

```org
#+TITLE: Underscores

x_x_x_x_x_x_x_x_X_x_x_x_x_X_x_x_X_x_x_x_X_x_x_x_x_x_x_x_x_X_X_x_x_x_x_x_x_X_x_x_x_x_x_X_x_X_X_x_x_X_x_X_x_x_X_x_x_x_x_x_x_X_x_x_x_x_X_x_x_x_x_x_x_x_x_
```

Version 2.2.2.1 renders this to HTML instantly:

```sh
$ /usr/bin/time ~/pandoc/pandoc-2.2.2.1/bin/pandoc input.org -f org -t html -o /tmp/output.html
0.00user 0.01system 0:00.03elapsed 67%CPU (0avgtext+0avgdata 25304maxresident)k
0inputs+8outputs (0major+7418minor)pagefaults 0swaps
```

It produces:

```html
<p>x<sub>xxxxxxxXxxxxXxxXxxxXxxxxxxxxXXxxxxxxXxxxxxXxXXxxXxXxxXxxxxxxXxxxxXxxxxxxxx</sub>_</p>
```

Emacs renders the same markup as:
```html
x<sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>X</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>X</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub><sub>x</sub>_
```

Version 2.2.3.1 hangs when processing the same file -- as does the latest release, 2.9.1.1.

**Comment by tarleb** [comment]
I confirmed that the changes in 4e899eb9c886df2200551f69a3f593ab5258f2e2
are to blame. The code is probably too lazy.

**Comment by jgm** [comment]
My guess is that the cause is a laziness-related memory leak, but rather just a regular parsing bug (e.g. exponential search) that was uncovered when this other bug was fixed.  (That is, something that was being skipped or incorrectly parsed before is now being handled, but not in an efficient way.)

**Comment by tarleb** [comment]
You were absolutely right.

**Comment by jsomers** [comment]
@tarleb Thanks for being so responsive and quick with the fix. I'll look out for it in the next release!

**Comment by tarleb** [comment]
Thank you for the report and easily reproducible example. You don't have to wait for the next release but can already try the latest [nightly build](https://github.com/jgm/pandoc/actions/runs/36469844).

I just noted that the problem isn't *fully* solved yet, in that parsing of subscript in braces still takes longer than it should. I'll open yet another issue to keep track.
