### ISSUE TITLE
lang=RU-ru breaks formatting

### ISSUE THREAD

**Issue by StrausMG** [jgm/pandoc#6131]
OS: macOS Mojave 10.14.6
pandoc --version: pandoc 2.9.1.1
pdflatex --vesion: pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019) kpathsea version 6.3.1

Input:
```
# привет
**привет** *привет*
```

**Command A**:
```
pandoc --from commonmark --to pdf --pdf-engine=pdflatex -o tmp.pdf tmp.md
```
Output:
```
Error producing PDF.
! Package inputenc Error: Unicode character п (U+043F)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.52 ...ring{\textbf{привет}}{привет}}

Try running pandoc with --pdf-engine=xelatex.
```

**Command B** (-V lang=RU-ru is added):
```
pandoc --from commonmark --to pdf --pdf-engine=pdflatex -V lang=RU-ru -o tmp.pdf tmp.md
```
This leads to the first line having the font size of heading, which is correct. But it is not bold and the words on the second line are not bold/italic either.

I would like to have both cyrillic and formatting, is it possible?

**Comment by tarleb** [comment]
Please try with `--pdf-engine=xelatex`, as stated in the last line of the first error. XeLaTeX usually works better with non-ASCII inputs.

**Comment by StrausMG** [comment]
xelatex --version: XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019) kpathsea version 6.3.1

**With -V lang=RU-ru**
```
>>> pandoc --from commonmark --to pdf --pdf-engine=xelatex -V lang=RU-ru -o tmp.pdf tmp.md
Error producing PDF.
! Package polyglossia Error: The current latin font latinmodern-math.otf(3) doe
s not contain the "Cyrillic" script!
(polyglossia)                Please define \cyrillicfont with \newfontfamily co
mmand.

See the polyglossia package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.59 \begin{document}
```

**Without -V lang=RU-ru**
```
>>> pandoc --from commonmark --to pdf --pdf-engine=xelatex -o tmp.pdf tmp.md
[WARNING] Missing character: There is no п (U+043F) in font [lmroman12-bold]:mapping=tex-text;!
<and many similar messages for every cyrillic symbol>
```
Produces an empty pdf.

P.S. I've googled a lot, but with no success.

**Comment by njbart** [comment]
Try adding

`header-includes: '\newfontfamily\cyrillicfont[Script=Cyrillic]{Times New Roman}'`

to your document’s YAML metadata. (Any other font that contains cyrillic characters should be fine, too.) Note that this will work with xelatex only.

**Comment by StrausMG** [comment]
Thank you, this works! However, it works only if I remove `--from commonmark`. Is there a similar hack, but for CommonMark?

JFYI: Markdown preview in Visual Studio Code successfully handles Cyrillic. According to the [docs](https://code.visualstudio.com/docs/languages/markdown#_does-vs-code-support-github-flavored-markdown), VSCode targets CommonMark. Moreover, [this](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf) extension successfully generates pdfs.

**Comment by jgm** [comment]
commonmark doesn't allow raw latex.  So, with commonmark, you'll have to use `--include-in-header` on the command line, or use the command line or a defaults file to set the `header-includes` variable.

```
-V header-includes='\newfontfamily\cyrillicfont[Script=Cyrillic]{Times New Roman}'
```

**Comment by StrausMG** [comment]
For my scenario it is ok to put everything in the command. However, if I add  
`-V header-includes='\newfontfamily\cyrillicfont[Script=Cyrillic]{Times New Roman}'` to my command, I get:
```
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 \fi
```

I have encountered this before when trying to pass `-V mainfont="Times New Roman"`. Google suggests some related links (for example, [this](https://github.com/jgm/pandoc/issues/4017) one), but it doesn't help much.

**Comment by jgm** [comment]
You can get a better idea what is going on (perhaps) by generating a standalone tex file (`-t latex -s`) and running xelatex on it manually.

**Comment by StrausMG** [comment]
Finally solved it, thank you!

The problem was that I was running `pandoc` from Python and during building the command, I added the following to the argv:
```
[..., '-V', 'header-includes="\\newfontfamily\\cyrillicfont[Script=Cyrillic]{Times New Roman}"',  ...]
```
The thing is that the quotes`"` are not needed when running the command from Python's `subprocess` module. The `-s` option helped to understand that :)
