### ISSUE TITLE
Strange got in MMD title block

### ISSUE THREAD

**Issue by saf-dmitry** [jgm/pandoc#6133]
I recently discovered some strange behavior when converting from MMD to MMD:

If I take the following MMD file `test.md`:

```
author: Author 
title: Title 

Some text 
```

and convert it again to MMD via pandov v2.9.1.1 using the following command:

    pandoc -f markdown+mmd -t markdown_mmd --standalone test.md

I get this:

```
author: Author 
  . 
title: Title 
  . 

Some text
```

I am just wondering about an indented dot appearing after each metadata pair.

**Comment by jgm** [comment]
The dot is used for blank lines (since MMD doesn't allow them in metadata and would otherwise start the document).
But we really shouldn't have a blank line here; we should chomp this before rendering.
