### ISSUE TITLE
A space becomes a linebreak when the space is followed by a word with more than 70 letters.

### ISSUE THREAD

**Issue by atusy** [jgm/pandoc#6134]
Is this an intended behavior?
I can suppress this by escaping the space by a backslash.

```bash
echo 'a aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' | pandoc --from markdown --to markdown
```

becomes

```
a
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Comment by alerque** [comment]
Yes, this is intended. The default options have a line wrap that tries to optimize fitting words on lines no longer that 70 characters.

You can set `--wrap=preserve` or `--wrap=none` to disable this if your use case would be better off without it.

**Comment by mb21** [comment]
btw. for future questions, you can also use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by atusy** [comment]
Thanks a lot. I will post to the mailing list from the next time.
