### ISSUE TITLE
"will add do" typo in sample.lua?

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#6135]
The `Doc` function comments say `pandoc will add do the template processing`. The `add` is extraneous?

https://github.com/jgm/pandoc/blob/114d77c2abac17d3e4676bb654f54535e0b809c9/data/sample.lua#L82

**Comment by wlupton** [comment]
Sorry, I noticed another! I think that `img_format` is a typo for `image_format`?

There may be more...

**Comment by alerque** [comment]
Don't be sorry! Every little fix is a good thing. I'm not at a computer at the moment but I'll check that when I am. Or somebody else can.

**Comment by jgm** [comment]
Re-opening to keep alive the comment about `img_format` which may require another PR.
