### ISSUE TITLE
Headers 4 levels deep render differently 

### ISSUE THREAD

**Issue by chrissound** [jgm/pandoc#6145]
Input:

```
* test
** test 2
*** test 3
**** test 4
***** test 5
****** test 6
bla bla
```

Command: `pandoc -s x.org -o x.md`

Output:
```
test
====

test 2
------

### test 3

1.  test 4

    1.  test 5

        1.  test 6

            bla bla

```

Also mentioned here: https://stackoverflow.com/questions/21198025/pandoc-generation-of-pdf-from-markdown-4th-header-is-rendered-differently
https://github.com/jgm/pandoc/issues/1221
https://github.com/jgm/pandoc/issues/754
https://github.com/jgm/pandoc/issues/1658?

**Comment by mb21** [comment]
What pandoc version are you on?

Try also `-t native`... you sure this is valid orgmode heading syntax for h4 and deeper?

**Comment by chrissound** [comment]
Will read up on `-t native` however it seems to generate some strange output?

`pandoc -t native -s x.org -o x.md` generates:

```
Pandoc (Meta {unMeta = fromList []})
[Header 1 ("test",[],[]) [Str "test"]
,Header 2 ("test-2",[],[]) [Str "test",Space,Str "2"]
,Header 3 ("test-3",[],[]) [Str "test",Space,Str "3"]
,OrderedList (1,DefaultStyle,DefaultDelim)
 [[Para [Str "test",Space,Str "4"]
  ,OrderedList (1,DefaultStyle,DefaultDelim)
   [[Para [Str "test",Space,Str "5"]
    ,OrderedList (1,DefaultStyle,DefaultDelim)
     [[Para [Str "test",Space,Str "6"]
      ,Para [Str "bla",Space,Str "bla"]]]]]]]]

```

But yes this should be valid org mode syntax.

**Comment by tarleb** [comment]
See #3214:

Adding `#+OPTIONS: H:9` to the top of your org file will fix this.

**Comment by chrissound** [comment]
Thank you!
