### ISSUE TITLE
Trying to get a copy of the default reference.docx causes an error 

### ISSUE THREAD

**Issue by r4dian** [jgm/pandoc#6147]
**Steps to repro:** 

As given in the docs:

```
pandoc -o custom-reference.docx --print-default-data-file reference.docx
```
produces:
```
QP8^  %     [Content_Types].xmlj0E
pandoc: <stdout>: hPutBuf: hardware fault (Input/output error)
```

```
ls /home/████████/.pandoc
```
Shows the directory doesn't exist but the other default possibilties given in `https://pandoc.org/MANUAL.html#option--data-dir` also don't seem to.

**Version**

pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/████████/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

**OS Info**

OS: Ubuntu 18.04.4 LTS on Windows 10 x86_64
Kernel: 4.4.0-18362-Microsoft
Shell: zsh 5.4.2

**Comment by jgm** [comment]
Hm, I've never seen that; I'm guessing it may have to do with a locale setting, but in any case you're running an ancient version of pandoc, and we only support the latest.  You can use our portable linux package to upgrade (see Releases).

**Comment by jgm** [comment]
If you can reproduce with the latest version, then we can reopen this.
