### ISSUE TITLE
Inconsistent behaviour of resource-path on Windows

### ISSUE THREAD

**Issue by ImkeF** [jgm/pandoc#6149]
Resource-path is working inconsistently on my windows machine: pandoc version 2.9.1.1, windows 10

```pandoc --resource-path=figures -s lists_records_and_tables_in_M_short.md -o testpdf5a.pdf --self-contained```

the above command works only for one document where the reference to the image looks like so:

```![Creating a measure table, using an empty list in M](02_Empty_list_for_measure_table.jpg)```

The image itself lies in a subfolder (relative to the working directory): "figures"

But this setup is not ideal, as the preview of the picture doesn't show up in VS Code. And what's also very strange is that the same syntax doesn't work with other files.

I'm pretty sure that my preferred setup to address everything related to the working directory has worked before, but I cannot get it to work any more: Documents lying under WorkingDirectory\Documents\Subfolders.. and images lying under: WorkingDirectory\figures...

The commands were as follows:

``` pandoc -s Documents/I_Basics/03_Lists_records_and_tables/lists_records_and_tables_in_M.md -t epub -o testpdf.epub --resource-path=figures --metadata title:"test" --toc --number-sections```

references to images looked like so:

```![Creating a measure table, using an empty list in M](/figures/02_Empty_list_for_measure_table.jpg)```

Having a hard time to figure out what's going wrong here, so would appreciate every help.
Thanks!
(BTW: Uninstalled and Re-Installed Pandoc already and rebooted the system a couple of times)

**Comment by jgm** [comment]
If you use
```
![Creating a measure table, using an empty list in M](figures/02_Empty_list_for_measure_table.jpg)
```
(note: I dropped the initial `/` before `figures`) then it should work, and you won't need `--resource-path` at all.  Adding the `/` at the beginning of the path makes pandoc treat it as an absolute, not a relative path.

**Comment by ImkeF** [comment]
Thanks @jgm , that did the trick. Actually, I had to delete the `--resource-path` to make it work.
But now the preview of the images in VS Code doesn't work any more. Do you have an idea about how to make this work as well?
Or do you have a better recommendation which editor to use that supports a cloned GitHub repo?
Thanks heaps!

**Comment by jgm** [comment]
> Adding information: Moved the file directly into the workspace and there the previews worked. So it seems that pandoc is interpreting the relative link notation as relative to the workspace, whereas VS Code interprets it as relative to where the current file is stored. Any idea here?

Correct.  I can't do anything about the way VS Code works, obviously.  Might be possible to use symlinks to fool it.
