### ISSUE TITLE
Automatic numbering of figures and tables in HTML output

### ISSUE THREAD

**Issue by nichtich** [jgm/pandoc#615]
Pandoc supports numbering of section headings in LaTeX and HTML output with option `-N, --number-sections`. Figures and tables are only numbered in LaTeX (because this is default in LaTeX). There should be options to add automatic numbering of figures and tables (`--number-tables`/`--number-figures`?) also in HTML output like this:

```
<span class="figurename">Fig. 1</span> Caption
<span class="tablename">Table 1</span> Caption
```

The prefix could be modified by a template variable that also works in LaTeX:

```
\renewcommand{\figurename}{$figurename$}
\renewcommand{\tablename}{$tablename$}
```

A dot or colon can be added after the figurename/tablename with CSS, so no addition template magic is needed, for instance:

```
.figurename:after { content: ":"; }
```

By the way this was already asked [in this thread](https://groups.google.com/forum/?fromgroups=#!topic/pandoc-discuss/el6zQnIQR6s)

**Comment by sjackman** [comment]
:+1:

**Comment by kebno** [comment]
👍

**Comment by aleb** [comment]
Automatic numbering of figures is already possible with the implicit_figures extension: https://pandoc.org/MANUAL.html#extension-implicit_figures

**Comment by jgm** [comment]
Implicit figures doesn't give you figure numbering in HTML.
(You do get it in LaTeX/PDF output, though.)

**Comment by mb21** [comment]
Closing in favour of https://github.com/jgm/pandoc/issues/813

In the meantime, you can do this with a filter or possibly CSS counters.
