### ISSUE TITLE
Non-breaking spaces in HTML ignored

### ISSUE THREAD

**Issue by timtroendle** [jgm/pandoc#6154]
The user manual states:

> A backslash-escaped space is parsed as a nonbreaking space. It will appear in TeX output as ~ and in HTML and XML as \&#160; or \&nbsp;.

While it works for TeX, it doesn't seem to work for HTML in my case.

```bash
$ echo "jo\ what " | pandoc -t html
<p>jo what</p>

$ echo "jo\ what " | pandoc -t latex
jo~what

$ echo "jo\ what " | pandoc -t json
{"blocks":[{"t":"Para","c":[{"t":"Str","c":"jo what"}]}],"pandoc-api-version":[1,20],"meta":{}}
```

pandoc: 2.9.2

**Comment by tarleb** [comment]
You are right, the manual is a bit misleading there. The non-breaking
space is inserted via the unicode character in most formats, including
HTML.  You can use the `--ascii` option to create an entity instead:

% echo "jo\ what" | pandoc -t html | hexdump
0000000 703c 6a3e c26f 77a0 6168 3c74 702f 0a3e
0000010

% echo "jo what" | pandoc -t html | hexdump 
0000000 703c 6a3e 206f 6877 7461 2f3c 3e70 000a
000000f

% echo "jo\ what" | pandoc -t html --ascii
<p>jo&#xA0;what</p>


Thanks for noticing. Pull requests are always welcome. ;)

**Comment by timtroendle** [comment]
Ok, thanks for letting me know. So this means the feature does actually work and only the documentation requires an update? I can have a look at that, but will need some time. ;)

**Comment by fabschurt** [comment]
@timtroendle Done :slightly_smiling_face:
