### ISSUE TITLE
Please help！

### ISSUE THREAD

**Issue by Jukka-GRW** [jgm/pandoc#6155]
How to modify the table style of reference.docx
![image](https://user-images.githubusercontent.com/8872282/75138045-394ce000-5724-11ea-9fe1-b67f1d40f54f.png)

I want to make this table's border to be solid line

**Comment by alerque** [comment]
Please ask support questions like this on the [pandoc-discuss](https://groups.google.com/d/forum/pandoc-discuss) group. This is not an issue report (bug, feature request, etc.) with the software itself.
