### ISSUE TITLE
LaTeX writer: add scrreport wrapper class to chaptersClasses

### ISSUE THREAD

**Issue by jpcirrus** [jgm/pandoc#6168]
[Version 3.29] (2020-01-24), and possibly earlier versions, of KOMA-script include wrappers for the classes `scrartcl`, `scrlttr2` and `scrreprt`. Accordingly `chaptersClasses` of the LaTeX writer needs to be extended with the `scrreprt` wrapper class: `scrreport`.

[Version 3.29]: http://mirror.aarnet.edu.au/pub/CTAN/macros/latex/contrib/koma-script/README

**Comment by jgm** [comment]
I'm a bit confused: what's the difference between `scrreport` and `scrreprt`?

**Comment by jpcirrus** [comment]
`scrreport` just calls `scrreprt`. According to the [README]:

> scrreport is a very simple wrapper class to scrreprt. Is has
> been made, because several younger KOMA-Script users do not
> understand the 8.3 name scheme.
 
[README]: http://mirror.aarnet.edu.au/pub/CTAN/macros/latex/contrib/koma-script/README
