### ISSUE TITLE
body epub:type mapping for types listed in the manual no longer working

### ISSUE THREAD

**Issue by NickBarreto** [jgm/pandoc#6170]
This is mentioned in passing by [Desbeers in this comment](https://github.com/jgm/pandoc/issues/5986#issuecomment-565766723), but pandoc 2.9 no longer assigns an epub:type other than 'bodymatter' to the <body> element of a document in EPUB3, even when an epub:type of one of the types listed in the [manual](https://pandoc.org/MANUAL.html#the-epubtype-attribute) is used.

For example 

`# Dedication {.hidden epub:type=dedication}`

is resulting in this output

```
<body epub:type="bodymatter">
<section id="dedication" class="level1 hidden" data-number="1" epub:type="dedication">
```

It is defaulting to 'bodymatter' in all cases. (pandoc 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2)

Something in the change from 2.7 to 2.8 looks like the EPUB writer isn't matching any of the front or back matter types.

This is a very small related issue, but for the user's convenience we place copyright pages at the end of an EPUB, rather than at the start, and so it shouldn't necessarily be 'frontmatter'. This is a relatively common practice with EPUB files.

**Comment by jgm** [comment]
I see the issue.  Now that we have containing Divs around the Header element, the pattern matching isn't seeing it.  This relates to the EPUB writer around line 599.  Should be easy to fix.

As for the other issue:  maybe we should add a way to specify explicitly that something belongs in back or front or bodymatter, e.g. a class `.bodymatter`, `.backmatter`, ...?

**Comment by NickBarreto** [comment]
I think having a class `.bodymatter` or `.backmatter` would work really well. 

Or, depending on the complexity of implementation, the way latex handles it could work also: the document begins, by default, as `frontmatter`, and after a `\mainmatter` command every section becomes `bodymatter`, until a `\endmatter` style command, after which all sections are `endmatter`. This may become more confusing, however, and create the problem that if the mainmatter command never gets triggered, the whole document would end up as `frontmatter`.

Probably safest, for document integrity, to have it default to `bodymatter` as it does, and allow a method of setting an alternative on a per-heading basis. 

Would a class as you envision be triggered in the following way, where 'endmatter' is a special class that will assign an epub:type to the document body?

`# Copyright {.hidden .endmatter epub:type=copryight-page}`

resulting in:

```
<body epub:type="endmatter">
<section id="dedication" class="level1 hidden" data-number="1" epub:type="copyright-page">
```

I think this might be overloading class declarations in a slightly opaque way. Is it perhaps less confusing and clearer to have another data attribute like epub:type? Something like this:

`# Copyright {.hidden epub:type=copyright-page body-epub:type=endmatter}`

It also signposts a bit more clearly that this is an epub-specific attribute.

**Comment by jgm** [comment]
I think this needs more discussion. I'd suggest opening a separate issue for the ability to override the defaults for frontmatter, backmatter, and bodymatter, and leaving this issue for fixing the bug.

**Comment by NickBarreto** [comment]
That makes sense. I'll create a new issue separately. This one can get closed as soon as the bug is addressed.
