### ISSUE TITLE
Support cover pages for wkhtmltopdf

### ISSUE THREAD

**Issue by joeyhoer** [jgm/pandoc#6171]
Attempting to run the following results in an `wkhtmltopdf` error:
```sh
pandoc --verbose input.md --pdf-engine wkhtmltopdf --pdf-engine-opt='cover' --pdf-engine-opt='http://google.com' -o output.pdf
```

The error is `--title specified in incorrect location`.

This is because the generated command is:
```sh
wkhtmltopdf "cover" "http://google.com" "--title" "Title" "--margin-bottom" "1.2in" "--margin-top" "1.25in" "--margin-right" "1.25in" "--margin-left" "1.25in" "./html2pdf-0.html" "./html2pdf-1.pdf"
```

when it should be: 
```sh
wkhtmltopdf "--title" "Title" "--margin-bottom" "1.2in" "--margin-top" "1.25in" "--margin-right" "1.25in" "--margin-left" "1.25in" "cover" "http://google.com" "./html2pdf-0.html" "./html2pdf-1.pdf"
```

Note that the `cover` argument has been moved after the global arguments. The cover argument is a page argument which must come after the global argument. The position of the `cover` argument is important here.

**Comment by jgm** [comment]
Thanks, it's fixed in master, you can test with a nightly tomorrow.
