### ISSUE TITLE
Failed to convert to pdf with lualatex in Windows

### ISSUE THREAD

**Issue by nanofi** [jgm/pandoc#6173]
Hi. I found a similar bug to #5451. I tried to convert html to pdf with lualatex and got an error as
```shell
Error producing PDF.
! I can't find file `C:'.
<to be read again> 
\/
<*> "C:\/
      Users/<Username>/AppData/Local/Temp/tex2pdf.-545ee5acfe90e00b/inpu...
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<to be read again> 
\/
<*> "C:\/
      Users/<Username>/AppData/Local/Temp/tex2pdf.-545ee5acfe90e00b/inpu...

 270 words of node memory still in use:
   1 hlist, 39 glue_spec nodes
   avail lists: 2:12,3:1,4:1,5:3
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.
```
where I replace the username as `<Username>` in the paths.

My environment is
- Windows 10 19041.113
- Powershell 5.1.19041.1
- lualatex Version 1.10.0 (TeX Live 2019/W32TeX)
- Pandoc 2.9.2 installed by chocolatey https://chocolatey.org/packages/pandoc
```shell
> pandoc -v
pandoc.exe 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: C:\Users\<Username>\AppData\Roaming\pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

A simple example to reproduce the bug is to execute command 
```bash
pandoc -f html -o test.pdf --pdf-engine=lualatex test.html
```
with the html file 
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Test HTML file</title>
    </head>
    <body>
        <h1>Test html file</h1>
        <p>This is test.</p>
    </body>
</html>
```

This error may come from `changePathSeparators` like #5451; that is, `changePathSeparators` won't remove the backslash just after the drive name. I also tried to set the environment variables `TMP` and `TEMP` to `./`, i.e., the relative path to the working folder. However, the pandoc converts the relative path to the absolute path and produces the error.

**Comment by kysko** [comment]
Works for me without problems, although not exactly in the same context:

- Windows 10 1909 (18363.693)
- PS 6 (or cmd line also works)
- lualatex also from texlive2019 (but portable install, path set manually in command line)
- pd 2.9.2 (manual install)

my user name is with simple ascii letters without spaces (if that matters here)

**Comment by fpopineau** [comment]
Hi all,

I can confirm the problem and it is annoying.
Using the verbose option, pandoc reports the following command line:
```
lualatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "C:\\/Temp/tex2pdf.-e9d4cc01dfdb1ff2" "C:\\/Temp/tex2pdf.-e9d4cc01dfdb1ff2/input.tex"
```
Unfortunately, it messes up lualatex, even manually. If I remove the '\\\\' part, then it runs ok.
This is with Windows 10, lualatex 1.12, Mingw64 shell or cmd shell, pandoc 2.10 and 2.11.

**Comment by jgm** [comment]
Just to confirm, what do we want the path to be in this case? (I don't do Windows.)
Should it be `C:/Temp/tex2pdf/etc.`?  Or something else?

**Comment by jgm** [comment]
Adding a special case in changePathSeparators should do the job if we just need to remove the backslash.
`splitDirectories` produces a list whose first component is `"C:\\"`; we could just look for this and remove the backslash.
Relevant code is in Text.Pandoc.PDF.

**Comment by fpopineau** [comment]
Le dim. 15 nov. 2020 à 19:32, John MacFarlane <notifications@github.com> a
écrit :

> Just to confirm, what do we want the path to be in this case? (I don't do
> Windows.)
> Should it be C:/Temp/tex2pdf/etc.? Or something else?
>
c:/Temp would be great !

**Comment by jgm** [comment]
OK, that's easy to fix then.

**Comment by jgm** [comment]
Please test (after tonight a nightly with this fix should  be available).

**Comment by fpopineau** [comment]
So I rebuild it.

It fixes the test case problem, but also the one I had with my markdown
files.

Great and thanks a lot for the quick fix !

Best regards,

Le dim. 15 nov. 2020 à 19:55, John MacFarlane <notifications@github.com> a
écrit :

**Comment by jgm** [comment]
I don't know about quick, since the original report was from early March. But you're welcome!
