### ISSUE TITLE
man to html conversion, escaped period is converted to a backtick (instead of just a period).

### ISSUE THREAD

**Issue by Jas0n99** [jgm/pandoc#6175]
Pandoc Version: 2.9.2 (binaries from github release page)
Linux Version: Centos 7

I was converting some man pages (-f man) to html (-t html5) when I noticed in the output that some pages the period ( . ) was being converted to a backtick ( ` ).

Upon further examination it appears the offending man pages were **escaping the period** (i.e. `\.`), I'm guessing either poor conversion from markdown or the author wasn't thinking as some pages have just a few periods escaped, and some pages have all periods escaped...

Example (from zstd.1):
```
\fBzstd\fR compresses or decompresses each \fIfile\fR according to the selected operation mode\. If no \fIfiles\fR are given or \fIfile\fR is \fB\-\fR, \fBzstd\fR reads from standard input
and writes the processed data to standard output\.
```
Example (from find.1):
```
.P
The syntax
\.B \-perm +MODE
does not work as expected in findutils-4.5.11 and it
was removed in findutils-4.5.12, in favour of
\.B \-perm
.BR /MODE .
The
.B +MODE
syntax had been deprecated since findutils-4.2.21
which was released in 2005.
```

Actual Output:  **Compress or decompress `zst files**
Expected Output:  **Compress or decompress .zst files**

My current workaround is to pre-filter the raw man page through `sed` but that seems less than ideal.

The stock `man` command seems to be able to handle parsing them okay.

I did a quick grep on a couple servers and they seem to average around 3% of the man pages have this issue. So it's not like I could just contact one or two authors and tell them to fix their docs as there are literally hundreds.

**Comment by Jas0n99** [comment]
Ugh, it also appears there are escaped single-quotes ( `\'` ) in the text which get converted to a backtick also.

Seems there is a single usage where that case also exists in some accent definitions located in *some* man pages. I don't know if those are used or have an affect on pandoc yet.

**Comment by jgm** [comment]
OK, I think both problems are now fixed in master. Thanks for reporting.
