### ISSUE TITLE
Horizontal Rule in ODT

### ISSUE THREAD

**Issue by 3N4N** [jgm/pandoc#6176]
I'm basically having the same issue as #2573. I did not understand the solution posted there, as i don't know about lua filters and how to use it. Also, the solution in that issue #2573 is for DOCX file format, but I use ODT file format

**Comment by mb21** [comment]
>  i don't know about lua filters and how to use it

see https://pandoc.org/lua-filters.html and ask on pandoc-discuss for help writing specific filters.

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
