### ISSUE TITLE
image path wrong when concatinating markdown files from different directories

### ISSUE THREAD

**Issue by jonassanoj** [jgm/pandoc#618]
concatenation of two markdown files that are in different directories and producing a pdf works properly,
as long as no relative addressed image is included in the file that is in the sub folder. see e.g. the following code:

> pandoc main.md subfolder/1.md -o main.pdf

produces this output:

> pandoc: Error producing PDF from TeX source.
> ! Package pdftex.def Error: File `map.png' not found.
> 
> See the pdftex.def package documentation for explanation.
> Type  H <return>  for immediate help.
> ...                                              
> 
> l.65 \includegraphics{map.png}

this problem does not occur if the image in the sub folders file is referenced by a hard link!
(using pandoc with ubuntu 12.04)

**Comment by lambdafu** [comment]
It may not be a bug, but it is definitely a missing feature.  If you want to use the same files for web and print output, there are no winning options without support from pandoc here. :(

**Comment by shoeffner** [comment]
@lambdafu I just ran into the same problem and solved it by just globbing for the image paths using a [filter](https://github.com/shoeffner/pandoc-img-glob/blob/master/pandoc_img_glob/pandoc_img_glob.py).
I put it up on pip, so you can easily try it out:

```
pip install pandoc-img-glob
pandoc main.md subfolder/1.md --filter pandoc-img-glob -o main.pdf
```

It recursively searches from your current working directory for images matching the paths you provided. Unfortunately this way all of your images need to have uniquely identifiable names, but maybe this is a step towards what you are looking for?

**Comment by lambdafu** [comment]
@shoeffner Well, personally I fixed it with quite a bit of preprocessing: https://github.com/lambdafu/hugo-material-book/blob/master/pandoc-book.py#L63
