### ISSUE TITLE
Markdown to TeX conversion fails when lang=zh-*

### ISSUE THREAD

**Issue by sgalal** [jgm/pandoc#6181]
Pandoc version: 2.9.2

Steps to reproduce:

This works:

```markdown
---
title: 测试文档
dir: ltr
documentclass: ctexart
classoption:
  - UTF8
---

# 测试 1

测试文档

# 测试 2

测试文档
```

The result is:

![The result of the working example](https://user-images.githubusercontent.com/32255369/76376102-70f19400-6382-11ea-96c4-f556cae48d99.PNG)

But when I add `lang: zh-CN` (or similarly `lang: zh-HK`):

```markdown
---
title: 测试文档
dir: ltr
lang: zh-CN
documentclass: ctexart
classoption:
  - UTF8
---

# 测试 1

测试文档

# 测试 2

测试文档
```

It fails:

```sh
$ pandoc -s index.md -o index.tex
$ xelatex -interaction=errorstopmode -halt-on-error --shell-escape index.tex
...
Package polyglossia Warning: File gloss-.ldf does not exist!
(polyglossia)                I will nevertheless try to use hyphenation pattern
s for . on input line 52.

! Argument of \str_upper_case:n has an extra }.
<inserted text>
                \par
l.52   \setmainlanguage[]{}

No pages of output.
Transcript written on index.log.
```

**Comment by mb21** [comment]
Looks like a problem with your xelatex installation... see https://github.com/jgm/pandoc/wiki/Pandoc-with-Chinese or ask on [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
