### ISSUE TITLE
pandoc: Cannot decode byte '\x8b': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

### ISSUE THREAD

**Issue by Ygarr** [jgm/pandoc#6182]
Asking a question?
Please use the pandoc-discuss mailing list instead:
https://groups.google.com/forum/#!forum/pandoc-discuss
This tracker is for bug reports and enhancement requests.

Reporting a bug?
Please include your pandoc version and an example that allows us
to reproduce the problem (complete input, exact command line
used, expected and actual output).  The smaller the example, the
better.
Error while running:"
`pandoc -s -r html http://maxim-nm.livejournal.com/551641.html  -o EXAMPLE.docx`"

got:
`pandoc: Cannot decode byte '\x8b': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
`

**Comment by mb21** [comment]
see https://pandoc.org/MANUAL.html#character-encoding

(also without the input file we couldn't help you if we wanted...)

**Comment by Ygarr** [comment]
So unsolvable case with streams
