### ISSUE TITLE
Jira import: bullet lists not recognized

### ISSUE THREAD

**Issue by git4-me** [jgm/pandoc#6183]
My Jira instance is putting spaces at the beginning of each bullet item of a list. Unlike what Atlassian writes on their syntax where it says "* bullet" they generate " * bullet" with a leading space. Not sure if this was due to a recent change in Jira.

Can you please make the Jira import tolerate leading spaces for lists?

Thanks, Philipp

--------------------------->8-----------
Here is my list:
 * One.
 * Two.
 * Three.

**Comment by tarleb** [comment]
Thanks for the report. I no longer have access to any Jira instance, so unfortunately I can't test this. Which Jira version is this? Jira cloud has support for Markdown in *some* fields, but not others. Could this be one of those cases?

If we want to implement this, I'd like to match Jira's behavior on corner cases. E.g., could you give me the output for these lists:

```
* One
 * Two

 * One
* Two

 ** One
*** One.One
```

**Comment by git4-me** [comment]
Not sure your list came across on GitHub correctly. Therefore I showed you both the visual version as rendered by Jira as well as the raw text version by Jira of an example I just created to illustrate the issue.

Here is what I entered in the visual text editor of the recent Jira 8.5.3:
![image](https://user-images.githubusercontent.com/62103114/76534242-8695b500-6479-11ea-8629-64efb1650688.png)

The result is the following:
Test of bullet lists
 * One
 * Two
 * Three

Test of another list
 * One
 ** One.One
 ** One.Two
 * Two
 * Three
 ** Three.One
 *** Three.One.One

Test of a numbered list
 # One
 # Two
 ## Two.One
 ## Two.Two
 # Three

As you can see Atlassian isn't compliant with their own spec here. Each bullet is prefixed with a space in the very beginning of the line.

Would be great if you could get this fixed.

Viele Grüße, Philipp

**Comment by git4-me** [comment]
OK, now I understand why I wasn't able to read your example properly. My raw text example also got formatted by github. Here is a second screenshot showing the raw text matching the visual example screenshot above:
![image](https://user-images.githubusercontent.com/62103114/76534912-661a2a80-647a-11ea-8bc6-bbd8bfc16493.png)

**Comment by git4-me** [comment]
If you look closely you can see the * or # is not aligned with the 'T' of Test but with the 'e'.

**Comment by tarleb** [comment]
Sorry for not being clear. What I mean is: how is the above text rendered if it is input as raw text.

**Comment by git4-me** [comment]
Ok, now I got it. Basically the number of leading spaces does not result in indentation of the bullets as you can see.

![image](https://user-images.githubusercontent.com/62103114/76537000-6962e580-647d-11ea-9d54-672df54b8145.png)

**Comment by tarleb** [comment]
Great, thanks! Just to be sure, could you also try with multiple spaces, like so:

```
        * One
        ** Two
    * Three
```

**Comment by git4-me** [comment]
Sure:
![image](https://user-images.githubusercontent.com/62103114/76538097-0d00c580-647f-11ea-9885-786aa32b7324.png)

**Comment by tarleb** [comment]
Perfect, thanks.
