### ISSUE TITLE
Jira import: text color not supported

### ISSUE THREAD

**Issue by git4-me** [jgm/pandoc#6184]
The Jira markup supports colored text in this syntax:

This problem has been {color:#00875A}fixed{color}. You can also make text{color:red}red{color}.

Full syntax is here:
https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all

Can you please support colored text during Jira import?

**Comment by tarleb** [comment]
We sorta-kinda already support colored text, but it's both incomplete and complicated. Background:

Jira puts very little restrictions on when and where `{color}` can be used. It is possible to wrap single words, whole tables, or multiple paragraphs between color markers. However, for quite a lot of these uses, the HTML markup by Jira is actually invalid. The browsers fix the invalid markup as far as possible, so nobody really notices. Except for us; we'd have to do the same error-correction that the browsers are doing, which would be quite complicated.

So for now, based on what I've seen "in the wild", I decided to only support coloring of single blocks:

``` jira
{color:red}
This is a paragraph; it is red.
{color}
```

I'll check if I can get the parser to also support inline use, as in your example. No promises though.

Another issue seems to be hex-colors, which are not recognized yet. That should be easy to fix.

**Comment by tarleb** [comment]
Support for inline coloring has been added.
