### ISSUE TITLE
Italic ODT input produces Bold Italic output in TXT and EPUB

### ISSUE THREAD

**Issue by tridral** [jgm/pandoc#6190]
Italic ODT input produces Bold Italic output in TXT and EPUB

This seems to be a random occurrence as most italic text is rendered correctly.

Version is
pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.

The input file is called bold_test_2.odt and the text output (md) file is bold_test_2.txt

The command line is 

pandoc bold_test_2.odt -o bold_test_2.txt

I've attached the two files zipped
[bold_test_2.zip](https://github.com/jgm/pandoc/files/4338998/bold_test_2.zip)

Thank you for any help.

**Comment by jgm** [comment]
If you look at the XML in the odt container it has text marked as "Strong Emphasis" style.  I don't know why it isn't appearing that way in LibreOffice, but pandoc is simply reacting to that.
``` xml
<text:span text:style-name="T1">So . . . it was not terrible – and I was always available for band rehearsals. </text:span></text:p><text:p text:style-name="P3"><text:span text:style-name="Strong_20_Emphasis"><text:span text:style-name="T4">Break, break, break, / At the foot of thy crags, O Sea! / But the tender grace of a day that is dead / Will never come back to me. <text:s/><text:line-break/></text:span></text:span><text:span text:style-name="Strong_20_Emphasis"><text:span text:style-name="T5">Alfred Lord Tennyson—Break</text:span></text:span><text:span text:style-name="Strong_20_Emphasis"><text:span text:style-name="T6">,</text:span></text:span><text:span text:style-name="Strong_20_Emphasis"><text:span text:style-name="T5"> Break</text:span></text:span><text:span text:style-name="Strong_20_Emphasis"><text:span text:style-name="T6">,</text:span></text:span><text:span text:style-name="Strong_20_Emphasis"><text:span text:style-name="T5"> Break—1834</text:span></text:span><text:span text:style-name="Strong_20_Emphasis"><text:span text:style-name="T7"> </text:span></text:span></text:p><text:p text:style-name="P2">At band rehearsals and gigs I was free of spontaneous</text:p><
```

**Comment by tridral** [comment]
Dear John,

Thank you very much for your help. It looks like a LibreOffice error  not a
Pandoc error.

I will check the content.xml file if I run into somehting like this again.

best regards,

'ö-Dzin




འོད་འཛིན་དྲི་བྲལ
'ö-Dzin Tridral
[image: https://]about.me/tridral
<https://about.me/tridral?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
☸
*Drala Jong Appeal - creating a Buddhist retreat centre in Wales:
https://www.drala-jong.org/ <https://www.drala-jong.org/> *☸

☸ Achos pan ddaw y Pedwar Marchog i ofyn a roist ti o dy gyfan - fydd gen
ti ddim esgus - Meinir Gwilym ☸
