### ISSUE TITLE
MD->RST: Repeated "alt" text leads to repeated images

### ISSUE THREAD

**Issue by mgeier** [jgm/pandoc#6194]
When converting images from Markdown to reStructuredText, it seems that Pandoc uses the "alt" text as image ID in the RST output.

If the "alt" text is repeated (which I think is a perfectly reasonable thing to do), the image ID is repeated as well, which leads to repeated images (which is of course not intended).

Example:

```
$ pandoc -f markdown -t rst
image1: ![foo](x.png)

image2: ![foo](y.png)
^D
image1: |foo|

image2: |foo|

.. |foo| image:: x.png
.. |foo| image:: y.png
```

I would expect some kind of unique ID instead.

```
$ pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

**Comment by petr-kalinin** [comment]
Apparently this affects not only Markdown, but other source formats too.

E.g. for LaTeX: the following input:

```
\includegraphics{a.png}
\includegraphics{b.png}
```
produces the following output:
```
|image| |image|

.. |image| image:: a.png
.. |image| image:: b.png
```

Moreover, I don't know any way to add alt to LaTeX images.

**Comment by mgeier** [comment]
Thanks for the fix @jgm!
