### ISSUE TITLE
Extract media from different .docx files to same directory

### ISSUE THREAD

**Issue by tifDev** [jgm/pandoc#6195]
# Goal

I'm converting some .docx to .md with pandoc. These .docx have images that, after conversion, were being placed in a directory (markdown-repository/media/) and it's URL was being referenced in the resulting .md file.

So the goal is to have the resulting .md files with links pointing to the proper images stored in markdown-repository/media/. For this to happen, all images under markdown-repository/media/ need to have an unique name.

# The problem

For each conversion, the images were being smashed by the last conversion, because pandocs doesn't track the image names, it creates image1.png, image2.png, image3.png, etc... for each converted file.

**How can i do this? Does pandoc have any option for this?**

**Comment by jgm** [comment]
No, pandoc doesn't. But you could create two directories, then use a script to copy files from one to the other, adding a prefix.

**Comment by jgm** [comment]
I see you asked on pandoc-discuss, which is the right thing to do.
