### ISSUE TITLE
Jira import: strike out style detected by mistake

### ISSUE THREAD

**Issue by git4-me** [jgm/pandoc#6196]
Jira is using dashes around words to denote the strike out (aka. strike through) style. This works nicely in most cases but is broken on this Jira string:

20.09-15 2-678

This string isn't a strike out in Jira. However the importer is getting confused by the digits and is mistaking this as strike out style. Here is the LaTeX output as generated corrupt by pandoc:

20.09\sout{15 2}678

Correct output would the plain input above:

20.09-15 2-678

Interesting note:
The string
Weihnachts-baum sammel-aktion
is processed without any problems and isn't recognized by pandoc as a strike out. It seems to be related to the fact that the above example uses digits.

**Comment by tarleb** [comment]
Thanks for the report.

I'm trying to determine if this is just a single bug or the result of two bugs combined. Could you tell me what whether Jira produces strikeout for this text `-15 2-3`, i.e. with `-` as the first character?

**Comment by git4-me** [comment]
Sure, here it is. I also added a few more tests. Only one came out with strike out:

![image](https://user-images.githubusercontent.com/62103114/76984672-72512c80-693f-11ea-9f02-72fccdba11be.png)

![image](https://user-images.githubusercontent.com/62103114/76984722-84cb6600-693f-11ea-9ecd-b69b3ef91223.png)

**Comment by git4-me** [comment]
BTW, first is the raw 'text' and the second is the rendered 'visual' output in Jira.

**Comment by tarleb** [comment]
Great, thanks!

**Comment by git4-me** [comment]
Thanks you so much for your quick responses and fixes! Highly appreciated. 🥇

**Comment by Estigy** [comment]
I found one example of formatting that should not become strike-out:
`-> test ->`

This should stay regular text.

**Comment by jgm** [comment]
@Estigy maybe best to open a new issue for this; comments in old issues tend to get lost.
