### ISSUE TITLE
Jira reader: tables only recognized when preceded with empty line

### ISSUE THREAD

**Issue by Estigy** [jgm/pandoc#6198]
Pandoc 2.9.2

This works:
```
*tabletest*

||Name|
|Test|
```

This does not work:
```
*tabletest*
||Name|
|Test|
```

Unfortunately, the latter is what I get from Jira 8.2.3 via their API.

Please have a look into this.
Thanks, Estigy

**Comment by tarleb** [comment]
Confirmed. The problem is a mistake in the detection of new blocks, which only recognizes `|| ` as the start of a table (note the space).

As a temporary workaround, you could use this `sed` command on your input to insert an extra space.

     sed 's/^||/|| /g' your_input.jira | pandoc -f jira
