### ISSUE TITLE
EPUB Metadata support belongs-to-collection?

### ISSUE THREAD

**Issue by ivysrono** [jgm/pandoc#6199]
I'm using pandoc 2.9.2
https://pandoc.org/MANUAL.html#creating-epubs-with-pandoc
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#sec-belongs-to-collection

It has been supported by Sigil and Calibre GUI, however, I do not find how to set it.

**Comment by mb21** [comment]
I don't understand your question. Either way, for questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by jgm** [comment]
I think the request is to add `belongs-to-collection` to the list of EPUB metadata attributes supported by pandoc.

**Comment by jgm** [comment]
However, I don't know whether this concerns pandoc's epub reader or epub writer. Perhaps @ivysrono can comment.

**Comment by ivysrono** [comment]
> I think the request is to add `belongs-to-collection` to the list of EPUB metadata attributes supported by pandoc.

You are right.


> However, I don't know whether this concerns pandoc's epub reader or epub writer. Perhaps @ivysrono can comment.

I try to convert markdown to epub, so it may be epub writer?

**Comment by brainchild0** [comment]
It seems reasonable to consider a mechanism for providing values  generically of the metadata fields, without any particular awareness of the specific field. The data might be given in YAML or directly in XML. The main drawback is  that without checking per-field validity, user misuse might lead to problems in the target.

**Comment by jgm** [comment]
Closed by PR #7063.
