### ISSUE TITLE
Creating a reference.odt (and docx) does not work as recommended

### ISSUE THREAD

**Issue by offlinefreund** [jgm/pandoc#6200]
Hi,

i use Kubuntu 19.10.

I try to create a reference.odt like in the Documentation proposed:
 
pandoc -o custom-reference.odt --print-default-data-file reference.odt

The result is a "Letter Salad" in the Terminal. To me it looks like the output of an File that is not written properly in a file. 
There is no File created, no error message.

Then i tried: pandoc -o custom-reference.odt --print-default-data-file reference.odt >>test2.odt

Which creates a working test2.odt with "Hello World!" on the page.

Hope this helps.

Bye

**Comment by offlinefreund** [comment]
The resulting test2.odt does not seem to work as a reference.odt

pandoc: Cannot decode byte '\xc6': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

**Comment by mb21** [comment]
What pandoc version are you using?

**Comment by offlinefreund** [comment]
Hi
i'm used Version 2.5 from the ubuntu repository.

Now i am with Version 2.9.2.

And it works fine now.

Sorry for not having upgraded to newest version in first place!

This is an awesome tool!

Thanks
