### ISSUE TITLE
Add attributes to --- MD element

### ISSUE THREAD

**Issue by nocommentlab** [jgm/pandoc#6205]
Is not possible to declare attributes for --- Markdown element.
Example:
`---{.hr1 text-description="IoCS"}`
to generate the below HTML element
`<hr class="hr1" text-description="IoCS">`

**Comment by jgm** [comment]
No, it's not. However, you can enclose it in a div:
```
::: {.hr1 text-description="IoCS"}
---
:::
and then use css to style the hr.

Eventually we may provide a way to add attributes to everything, but in the mean time I'll close this.

**Comment by nocommentlab** [comment]
Thanks for your reply but this solution doesn't solve my problem.
I use the attr() css function to set a text inside my hr html tag.
Below my css code:
`hr:before {
  content: attr(text-description);
  position: absolute;
  top: 0;
  left: 50%;
  background: black;
  color: white;
  padding: 0.5em 3em;
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}`
By using the div tag, I can't assign the content value to the hr child tag.

**Comment by jgm** [comment]
I see. Well, you'll have to wait for an extension allowing attributes on every element.
But you could still do this with a bit of added JavaScript.

**Comment by alerque** [comment]
Can't you access the parent element's text-description from CSS?

**Comment by nocommentlab** [comment]
I solved my problem by replacing the hr with a h6+code. 
Now I can write this:
`###### `Threat Attack Map``
to obtain this:
`<h6 id="threat-attack-map"><code>Threat Attack Map</code></h6>`
with this final result:
![immagine](https://user-images.githubusercontent.com/33418596/77520070-ea0fe180-6e80-11ea-9c58-b5deb2fac011.png)

Thanks for the support.

**Comment by nocommentlab** [comment]
> 
> 
> Can't you access the parent element's text-description from CSS?

No, it is not possible, the `attr` function working only in the declared element.

**Comment by alerque** [comment]
@nocommentlab If text content belongs in the separator, a heading as you used is probably semantically more correct anyway. Also they can take attributes, so you could add a class:

```markdown
###### Threat Attack Map {.separator}
```

**Comment by jgm** [comment]
Good solution!
