### ISSUE TITLE
Replicate HTML writer behavior for --shift-heading-level-by=1 to Markdown writer

### ISSUE THREAD

**Issue by p3palazzo** [jgm/pandoc#6207]
Using this file:

```
---
title: "My title"
---

My document
```

And running this command: `pandoc -s -o somefile.html --shift-heading-level-by=1 somefile.md`

I get, as expected, something like:

```
<html><head><title>My title</title></head>
<body><h1>My title</h1>
<p>My document</p>
</body></html>
```

What I would like to get when running the following command: `pandoc -s -o somefile2.md --shift-heading-level-by=1 somefile.md` is this:

```
My title
========

My document
```

Alas, it does not work. Headings that are already in the text are correclty shifted by a level, but the title remains only in the metadata. The above behavior would be useful when concatenating a number of markdown files into a single document, so that each file's metadata title becomes a h1 in the concatenated file.

**Comment by jgm** [comment]
They are actually behaving the same.  Metadata title never gets promoted to a level-1 heading; however, in HTML an h1 element is used to render the metadata title.

For a little while we did promote the metadata title to a level-1 heading, but this was reverted. The explanation is in the changelog:
```
  * Roll back part of of `--shift-heading-level-by` change (#5957).
    With positive heading shifts, starting in 2.8 this option
    caused metadata titles to be removed and changed to regular
    headings.  This behavior is incompatible with the old
    behavior of `--base-header-level` and breaks old workflows,
    so we have rolled back the change. Note that there is now an
    asymmetry in positive and negative heading level shifts:
    With positive shifts, the metadata title stays the same and
    does not get changed to a heading in the body, while with
    negative shifts, a heading can be converted into the
    metadata title.
```
