### ISSUE TITLE
Mutliple <br> in a row combine to one line in "plain"

### ISSUE THREAD

**Issue by mindreader** [jgm/pandoc#6213]
pandoc 2.9.2.1

`pandoc -f html -t plain`

Input: `"asdf<br><br>fdsa"`
Output: `"asdf\nfdsa"`

`pandoc -f html -t native`
Output: `[Plain [Str "asdf",LineBreak,LineBreak,Str "fdsa"]]`

Reading the code it seems like this is because plain text is just markdown without the markdown, and in markdown, multiple newlines in a row would be meaningless.

It seems like it would be an easy fix, and I'd be happy to provide a pr, but I cannot find the spot in the code that removes extra `LineBreak`s.  But I'll continue to search.

**Comment by mb21** [comment]
This might very well be intended behaviour. From https://pandoc.org/MANUAL.html#description

> Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size.

normalizing things like line breaks might fall into this category.

**Comment by mindreader** [comment]
We ended up working around it for ourselves by converting it from html to commonmark to plain.  It is kind of weird, but it seems to work.

`pandoc -f html -t commonmark | pandoc -f commonmark -t plain`
Output: `"asdf\n\nasdf"`

**Comment by mb21** [comment]
huh, that's the same output you posted in the OP?
btw. what pandoc version are you on?

**Comment by jgm** [comment]
A LineBreak starts a new line within a paragraph. If you want blank space, you probably want a new paragraph.  It's true that you can do this kind of thing in HTML, but see the above quote from the manual.

**Comment by mindreader** [comment]
Sorry I can't believe I forgot to put the version.  pandoc 2.9.2.1

For input: "a<br><br>b"
  html to plain: "a\nb\n"
  html to markdown: "a\\\n\\b\n"
  html to commonmark: "a\n\nb\n"

Input: "a\n\nb\n"
  commonmark to plain: "a\n\nb\n"

So the fix for me to go from html to plain text while preserving newlines was to go from html -> commonmark -> plain

**Comment by jgm** [comment]
I'd say that's incorrect behavior by the commonmark writer, since two newlines creates a new paragraph in commonmark, and that's not semantically the same as two intraparagraph line breaks.
