### ISSUE TITLE
Empty HTML comments in mediawiki -> markdown

### ISSUE THREAD

**Issue by ripperdoc** [jgm/pandoc#6214]
When I have the following mediawiki text, the markdown output includes empty HTML comments, which is not what I expected:

```
pandoc -f mediawiki -t markdown-raw_attribute --strip-comments <<EOF --wrap=none --strip-comments <<EOF
* Test1

* Test2
EOF
```
Gives
```
-   Test1

<!-- -->

-   Test2
```
`--strip-comments` have no effect on the outcome it seems. When I check the AST I can't find any element that represents the HTML comment. It seems this happens because the empty line between Test1 and Test2 in the input, but why not just output two markdown lists separated by empty line as well?

**Comment by jgm** [comment]
This is needed to create two separate lists instead of a single list with two elements.
Markdown lists can have empty space between items.
