### ISSUE TITLE
Markdown to plain: tables indented 2 spaces

### ISSUE THREAD

**Issue by Bill-Stewart** [jgm/pandoc#6217]
pandoc version: 2.9.2.1

Markdown file `test.md`:

    Col A | Col B | Col C
    ----- | ----- | ------
    A 1   | B 1   | C 1
    A 2   | B 2   | C 2

Output when I use `pandoc --columns=79 --tab-stop=2 -t plain+smart test.md`:

      Col A   Col B   Col C
      ------- ------- -------
      A 1     B 1     C 1
      A 2     B 2     C 2
    xx

[The two `x` characters do not appear in the output; I added those to illustrate the indentation of the table]

Is there a way to control the indentation of output tables when using the `plain` format?

**Comment by jgm** [comment]
Sorry, there isn't.

**Comment by jgm** [comment]
Btw, questions like this should be asked on pandoc-discuss rather than in this bug tracker.

**Comment by Bill-Stewart** [comment]
Understood; I thought this was a bug - I'm fine with closing this if working as designed.
