### ISSUE TITLE
The extension empty_paragraphs is not supported for markdown

### ISSUE THREAD

**Issue by vveider** [jgm/pandoc#6218]
PanDoc 2.9.2

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by vveider** [comment]
```
pandoc -f markdown+implicit_header_references+empty_paragraphs+yaml_metadata_block-smart --template templates/template.latex --listings --toc -V fontpath=fonts/ -t latex+empty_paragraphs+escaped_line_breaks-smart -s -V toc-title=Оглавление -V version=8.5.18 -V imagedir=templates/ -V secnumdepth=4 -o /tmp/file2_snnO /tmp/file1_623P
```

**Comment by vveider** [comment]
I've tested several versions — this problem emerged in 2.8, 2.7.3 is working.

**Comment by tarleb** [comment]
Markdown does not support the empty_paragraphs extension, see https://pandoc.org/MANUAL.html#extensions-empty_paragraphs. By itself, this is not new behavior.

What *has* changed, however, is that pandoc now errors if an unsupported extension is given. I assume this is what you are referring to.

**Comment by vveider** [comment]
What should I do then? Fix my markdown and remove empty_paragraphs?

**Comment by tarleb** [comment]
Yes, changing your input format to `markdown+implicit_header_references+yaml_metadata_block-smart` should do the trick.

I'm not sure what you mean by "fix my markdown", can you please provide an example of what you are trying to do?

**Comment by vveider** [comment]
Thanks! That really helped.
