### ISSUE TITLE
Jira: falsly styled text

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#6220]
The Jira parser seems to incorrectly parse certain text as styled, while Jira displays it verbatim. E.g. `-> step ->`

**Comment by tarleb** [comment]
@Estigy, @git4-me, could one of you tell us the Jira output for this raw Jira input?

```
->step-
-step -
-$step-$
*%step*
-step->
```

**Comment by git4-me** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/62103114/77818412-52a1cd00-70d2-11ea-85ca-a39243a3f41d.png)

**Comment by tarleb** [comment]
Thanks!

**Comment by tarleb** [comment]
One more: `<-backwards<-`

**Comment by git4-me** [comment]
![image](https://user-images.githubusercontent.com/62103114/77819968-2d678b80-70df-11ea-9cdc-85316182a623.png)

**Comment by tarleb** [comment]
Great, thx. That last one made me realize why I handled things the way I did. Fix incoming.
