### ISSUE TITLE
Word: buggy rendering of RTL (text is stuck as LTR)

### ISSUE THREAD

**Issue by mustafa0x** [jgm/pandoc#6222]
Quite an odd bug.

pandoc 2.9.2.1, Word 16.35 for Mac (also tested on Word 2010 for Windows)

```
$> pandoc -o ar-good-parens.docx
(مثال)  
```
![Screen Shot 2020-03-28 at 12 07 57 AM](https://user-images.githubusercontent.com/1473102/77817498-76d8bc00-7088-11ea-8f95-cdef5080ce58.png)

```
$> pandoc -o ar-bad-parens.docx
(مثال) مثال
```
![Screen Shot 2020-03-28 at 12 08 52 AM](https://user-images.githubusercontent.com/1473102/77817501-7d673380-7088-11ea-8262-9ed5b73f9313.png)

Regardless of how I set the text direction, the parentheses remain as above. The issue is in the rendering, as if I copy the text to a plain text editor the parentheses are correct.

Note: it manifests in other ways too, and the issue is always the same: text is stuck in LTR mode, even if I click on the RTL button (¶‹). It does align to the right, but the RTL Unicode rules aren't applied.

**Comment by jgm** [comment]
Does it help if you specify `--metadata lang=ar`?

**Comment by mustafa0x** [comment]
No, same result.

Using a reference doc where the Normal style is RTL doesn't help either.

**Comment by jgm** [comment]
@jkr any ideas on this one?

**Comment by mustafa0x** [comment]
The following change to word/document.xml helped.

```diff
 <?xml version="1.0" encoding="UTF-8"?>
 <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
   <w:body>
     <w:p>
       <w:pPr>
         <w:pStyle w:val="FirstParagraph" />
       </w:pPr>
       <w:r>
+        <w:rPr><w:rtl/></w:rPr>
         <w:t>(مثال) مثال</w:t>
       </w:r>
     </w:p>
     <w:sectPr />
   </w:body>
 </w:document>
```

**Comment by mustafa0x** [comment]
It seems that Word's approach is to store parentheses in their own `<w:r>` tag. If I create a new Word document, enter مثال, then save it I get something like the following:

```xml
<w:p>
  <w:r>
    <w:t>(</w:t>
  </w:r>
  <w:r>
    <w:rPr>
      <w:rFonts w:cs="Arial"/>
      <w:rtl/>
    </w:rPr>
    <w:t>مثال</w:t>
  </w:r>
  <w:r>
    <w:t>)</w:t>
  </w:r>
</w:p>```

**Comment by jkr** [comment]
@mustafa0x: that's incredibly helpful. I'll take a look today and see if I can figure out how to make it work dependably.

**Comment by jkr** [comment]
@mustafax: Interestingly, this seems to be dependent on Word versions. I'm getting correct parentheses rendering with Word 2013 (windows, virtualbox). So I might need to come back to you for further testing.

Note though that you do need to set `dir=rtl` in Metadata (because pandoc can't guess based on input), or in a over the div (check the manual on rtl direction for more). So you would want to run the following:

~~~
echo "(مثال) مثال" | pandoc -Mdir=rtl -o out1.docx      
~~~

When I run that, I get the following in word:

![rtl](https://user-images.githubusercontent.com/835121/77940535-d69cb600-7286-11ea-8143-12d2ecb31cf1.png)

**Comment by jkr** [comment]
By the way, I take it that the different order of the parenthesized and non-parenthesized term are because of how the shell handles it (rtl within the word, ltr outside). When i cut and paste your plain text input and put it into emacs, it puts the parenthesized term first, right-aligned, as in the Word output.

**Comment by mustafa0x** [comment]
@jkr Thanks, that fixes it! `-Mdir=rtl` seems to actually do just that (i.e. adds `<w:rPr><w:rtl/></w:rPr>`).

Perhaps a warning should be issued if the user converts an RTL document to Docx and fails to set `dir=rtl`.

**Comment by mustafa0x** [comment]
Shooting in the dark: perhaps docx stores all directionality-weak characters in their own `<w:t>` so that their direction can be set by the paragraph rules or bidi algorithms.

**Comment by jkr** [comment]
@mustafa0x: You can also override the full-document direction with spans and divs: ie, have the whole document in rtl, and then use "dir=ltr" attributes to set it locally. For example, with document-wide `dir=rtl`

~~~
مثال مثال مثال مثال مثال.

::: {dir=ltr}
example example
:::

مثال مثال مثال مثال [example]{dir=ltr} مثال
~~~

> Perhaps a warning should be issued if the user converts an RTL document to Docx and fails to set dir=rtl.

if a document is coming from plain text, though, it might not be possible to tell if it should be RTL. We could read the unicode codepoints and guess ("more than half of this document is an right-to-left language") but it seems like you'd mess up a lot too (e.g. semitic philology in English-language journals with lots of block-quotes).
