### ISSUE TITLE
getRandomUUID is wrong

### ISSUE THREAD

**Issue by josephcsible** [jgm/pandoc#6228]
https://github.com/jgm/pandoc/blob/c12bf49e596c47ae91ce4d3bdfe320a838beaf31/src/Text/Pandoc/UUID.hs#L48-L60

`getUUID` doesn't return a new random state, so it's only safe to call it with one that's immediately discarded. However, `getRandomUUID` calls it with the system random state, without then updating/replacing it after. As a result, if you call `getRandomUUID` twice in a row, you get the same UUID both times.

What should we do about this?

1. Just remove `getRandomUUID`, since it looks like nothing currently uses it
2. Change `getRandomUUID` to use [`newStdGen`](https://hackage.haskell.org/package/random-1.1/docs/System-Random.html#v:newStdGen) instead of `getStdGen`
3. Change `getUUID` to return an updated random state, and change all of its callers to save the updated state back to where they got it

Let me know which you prefer, and I'll PR it.

**Comment by jgm** [comment]
Indeed, the only use of this module in pandoc is in the EPUB writer, which does
```
166:            randomId <- (show . getUUID) <$> lift P.newStdGen
```
So I'd recommend:

1. Redefining `getRandomUUID` along lines of your (2)
2. Using that function in the EPUB writer.
3. Removing the export of `getUUID` from the UUID module - since it would not be used anywhere.
