### ISSUE TITLE
Jira Reader: Blockquote bq.

### ISSUE THREAD

**Issue by Estigy** [jgm/pandoc#6233]
Sample code:

```
This is reqular text
bq.This is a blockquote
This is reqular text again
```

**Comment by tarleb** [comment]
Thanks for the report. Please add the expected output for this text, ideally by adding a screenshot of the rendered output produced by Jira. Does the second line produce a blockquote even without a space after `bq.`?

**Comment by Estigy** [comment]
Hi, Tarleb.

The given example yields this output:
```
<p>This is regular text</p>
<blockquote><p>This is a blockquote</p></blockquote>
<p>This is regular text again</p>
```
And yes, it works with and without the space. (Which seems to be the case for other block formatting options like h1 as well. According to a co-worker in former versions adding the space actually could break rendering...)
