### ISSUE TITLE
Jira reader: Icons

### ISSUE THREAD

**Issue by Estigy** [jgm/pandoc#6236]
Sample code:
```
(i)(/)(x)(!)(+)(-)(?)
```
Current output (transform to HTML):
```
ℹ✓🅇⚠⊞⊟?
```

The question mark does not get transformed to an icon.

**Comment by tarleb** [comment]
I guess I couldn't decide for a good character to use. Jira shows `(?)` as a white questionmark in a blue circle, for which there doesn't seem to be a matching unicode representation. Which of the following would you suggest for the questionmark? 

- Small questionmark: ﹖
- Red questionmark:❓
- White questionmark: ❔

I'm leaning towards the small questionmark, as it matches the conversion of `(i)`.

**Comment by Estigy** [comment]
Yes, I think the small questionmark would fit nicely.
