### ISSUE TITLE
Jira: "inserted" markup gets lost via HTML

### ISSUE THREAD

**Issue by Estigy** [jgm/pandoc#6237]
Jira sample:
```
+test+
```
Transform to HTML:
```
<p><span class="inserted">test</span></p>
```
Transform back to Jira:
```
test
```

**Comment by tarleb** [comment]
There may be two issues here: `+test+` is the Jira equivalent to the HTML `<ins>test</ins>`. Pandoc transforms the HTML into `Span ("", ["underline"], []) [Str "test"]`, but the Jira string into `Span ("", ["inserted"], []) [Str "test"]`. It would be better to use the same internal representation for both.

In general, one should not expect the conversion `jira -> HTML -> jira` to always yield the input again, but in this case it makes sense.

**Comment by Estigy** [comment]
> In general, one should not expect the conversion jira -> HTML -> jira to always yield the input again, but in this case it makes sense.

Hi, tarleb.
I totally understand that there will be edge cases where this wish can't be fulfilled all the time. I'm perfectly happy to jump in and do some text transformation myself. For now I'm basically filing some reports where I think things could be imporved, trying to get some understanding of what can be done by pandoc and where I do have to make my hands dirty myself.
Please feel free do give me a "won't do" in these cases.
