### ISSUE TITLE
Jira: Citation

### ISSUE THREAD

**Issue by Estigy** [jgm/pandoc#6238]
Sample code:
```
This is a ??citation??
```
Expected output:
```
<p>This is a <cite>citation</cite></p>
```

**Comment by tarleb** [comment]
There is a discrepancy between the documentation and the current Jira version which can be used for testing. The docs use `<cite>` as mentioned above, but the latest Jira renders it as

    <p>This is a — <em>citation</em></p>

Therefore I am leaning towards converting `??citation??` into `[Str "—", Space, Emph [Str "citation"]`.

**Comment by Estigy** [comment]
Hi, tarleb.
To be honest, I don't care too much about what Jira's owhn rendered HTML output would be. I'd rather have (semantically) correct HTML which can then in turn be converted back into the proper Jira markup.
Therefore, I'd go with <cite> instead of <em>.

**Comment by tarleb** [comment]
I think Jira's rendering is correct.

From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite

> The HTML Citation element (<cite>) is used to describe a reference to a cited creative work, and must include the title of that work. The reference may be in an abbreviated form according to context-appropriate conventions related to citation metadata.

**Comment by Estigy** [comment]
I don't quite see why using `<em>` should be more correct. It propably depends on using Jira's citation markup correctly in the first place.
So if I do something like `this quotation is from ??Behind Bars, Elaine Gould, p23??` then `<cite>` would be perfectly correct, right?

Also, when we transform `??` to `<em>`, we lose all possibility to transform it back to Jira later; the original markup will be "lost in translation", so to speak. At least the `<em>` should get some sort of attribute that stores where it's coming from.

**Comment by tarleb** [comment]
> So if I do something like `this quotation is from ??Behind Bars, Elaine Gould, p23??` then `<cite>` would be perfectly correct, right?

Yes, I think that's correct. I was a too brief in my explanation. What I'm worried about is that the above, in my experience, is not how citations are usual used in Jira issues. Far more often I've seen `"a quote" ??some user??`, which should probably not be put in a `<cite>`. I might well be wrong though.

Anyway, I also just realized that this is mostly a moot point, as there is no natural pandoc representation which would output a `<cite>` element in HTML.

No worries though, you can still use `<cite>` by using a [Lua filter](https://pandoc.org/lua-filters.html). We can cross that bridge when we get there.

**Comment by tarleb** [comment]
Here's a way to get what you want: below is a Lua filter which helps to convert Jira citations into HTML `<cite>` elements and back again. Save this to a file – `jira-citations.lua` for example – and use `--lua-filter=jira-citations.lua` to pass it to pandoc. You'll also need to enable the `raw_html` extension via `-f html+raw_html` when going from HTML to Jira.

``` lua
if FORMAT:match 'html' then
  function Inlines (inlines)
    for i = #inlines, 3, -1 do
      if inlines[i-2].text == "—" and
         inlines[i-1].tag == 'Space' and
         inlines[i].tag == 'Emph' then
        local emph = inlines[i]
        for j, v in ipairs(emph.content) do
          inlines:insert(i + j, v)
        end
        inlines:insert(i + #emph.content + 1, pandoc.RawInline('html', '</cite>'))
        inlines:insert(i + 1, pandoc.RawInline('html', '<cite>'))
        inlines:remove(i)
        inlines:remove(i-1)
        inlines:remove(i-2)
      end
    end
    return inlines
  end
elseif FORMAT == 'jira' then
  function RawInline (raw)
    if raw.format:match 'html' and raw.text:match '<%/?cite>' then
      return pandoc.RawInline('jira', '??')
    end
  end
end
```
