### ISSUE TITLE
Different result when using the emoji option

### ISSUE THREAD

**Issue by Grandement** [jgm/pandoc#6241]
Hi,

I found a different expected result when I use emoji together with latex commands.

pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: C:\...............
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

Example:
```markdown
:smile:

\textcolor{red}{:smile:}

:heart_eyes:

\textcolor{red}{:heart_eyes:}
```

Result 1 with `pandoc -t latex -f markdown+emoji -o result.tex example.md`
```tex
{😄}

\textcolor{red}{:smile:}

{😍}

\textbackslash textcolor\{red\}\{{😍}\}
```

Result 2 with `pandoc -t latex -f gfm+emoji -o result.tex example.md`
```tex
{😄}

\textbackslash textcolor\{red\}\{{😄}\}

{😍}

\textbackslash textcolor\{red\}\{{😍}\}
```

I would expect for both variants markdown or gfm following result.
```tex
{😄}

\textcolor{red}{:smile:}

{😍}

\textcolor{red}{:heart_eyes:}
```
or
```tex
{😄}

\textcolor{red}{{😄}}

{😍}

\textcolor{red}{{😍}}
```

Interesting is that all emojis which contain underscore are handled differently to the one without underscore when using `-f markdown`.

**Comment by jgm** [comment]
The underscore is a special character in LaTeX.  So this isn't actually valid TeX, is it?
```
\textcolor{red}{:heart_eyes:}
```
If you try running latex on this you'll get an error:
```
! Missing $ inserted.
<inserted text>
                $
l.52 \textcolor{red}{:heart_eyes:}
```
You need
```
\textcolor{red}{:heart\_eyes:}
```

**Comment by Grandement** [comment]
Hi @jgm,
I am not reffering to the latex run. Of course the latex result would fail as you have shown. My issue is about the replacement of the emoji. It is a little bit buggy. In the pandoc manual is noted following.

Extension: emoji
Parses textual emojis like :smile: as Unicode emoticons.

Reffering to my example and the result 1 markdown+emoji. The replacement of the emoji to an Unicode character is not the same everytime. Emojis without underscore are not replaced but emojis with underscore are replaced by the Unicode but the rawlatex is converted as well. 

The example is just a minimal example to show the differnce. 
Using gfm+emoji breaks the rawlatex completly.

I think it would be correct when the emoji replacement not happen inside a latex environment. Probably two things clash here text underscore replacement and emoji replacement?

**Comment by jgm** [comment]
In your example you're only getting the emoji replaced in tex when the tex is invalid and pandoc is then treating it not as tex but as regular text.
Inline LaTeX would be processed as tex and emojis not replaced.

**Comment by Grandement** [comment]
I understand it with your explanation. Keeping the tex valid will fix it. Thanks @jgm .
