### ISSUE TITLE
pandoc doesn't work on a fresh download

### ISSUE THREAD

**Issue by lrdegeest** [jgm/pandoc#6248]
running MacTex 2017

installed pandoc 2.9.2.1 via `brew`

created a file called "test.md"

```
---
title: "title"
author: "author"
---
  
# header

test
```

try to make a pdf:

```
pandoc test.md -o test.pdf
```

get this error:

`! LaTeX Error: File `ifxetex.sty' not found.`

**Comment by jgm** [comment]
This isn't a problem with pandoc itself; you're missing a latex style file pandoc needs to produce the pdf via pdflatex.  If you already have texlive installed, you may be able to install the required package via `tlmgr install`.  The pandoc manual contains a list of the LaTex packages you need to have installed for normal operation.

**Comment by lrdegeest** [comment]
No, I already did this. The package `iftex` is already installed.
