### ISSUE TITLE
pandoc says a package is missing when it really isn't

### ISSUE THREAD

**Issue by lrdegeest** [jgm/pandoc#6249]
Asking a question?
Please use the panrunning MacTex 2017

installed pandoc 2.9.2.1 via `brew`

created a file called "test.md"

```
---
title: "title"
author: "author"
---
  
# header

test
```

try to make a pdf:

```
pandoc test.md -o test.pdf
```

get this error:

`! LaTeX Error: File `ifxetex.sty' not found.`

This was initially dismissed out of hand as "you're missing ifxetex.sty". But I'm not. I'm running MacTex 2019, and according to `tlmgr` I have the latest `iftex.sty` (which includes `ifxetex.sty`). So what is going on?

**Comment by jgm** [comment]
Try creating a standalone tex file
```
pandoc test.md -s -o test.tex
```
and then compile it with pdflatex. That may give you more information (you should see where tex is looking).  Make sure that the pdflatex in your path is the mactex 2019 one.

**Comment by jgm** [comment]
In any case this seems not to be a problem with pandoc itself, but with your tex setup.  

For a minimal test, create a file `test.tex` with these contents:
```
\documentclass{article}
\usepackage{ifxetex}
\begin{document}


Hi

\end{document}
```
Then do
```
pdflatex test
```

**Comment by lrdegeest** [comment]
Cool. So when if I create a file "test_pdflatex.tex":

```
\documentclass{article}
\usepackage{ifxetex}
\begin{document}
Hi
\end{document}
```

and compile it with `pdflatex test_pdflatex.tex`, no errors. 

Next I ran `pandoc test.md -o test.tex` and then `pdflatex test.tex` I get this error:

```
! Undefined control sequence.
l.1 \hypertarget
                {header}{%
```

and if I try to get straight to the pdf and run `pandoc test.md -o test.pdf`,  I get this error:

```
Error producing PDF.
! Undefined control sequence.
l.10 \ifnum 0\ifxetex
```

Is it possible that pandoc just can't find `ifxetex` (or the whole `iftex` package)?

**Comment by lrdegeest** [comment]
Follow up: why does default.latex load the package `ifxetex.sty`? Because the macro `ifxetex` is provided by `iftex.sty`

**Comment by jgm** [comment]
> when I looked at test.tex, all it has is:

You forgot the `-s` option. Without that, you just get a fragment without a preamble.

**Comment by jgm** [comment]
I don't know what is happening here. But do try with `-s` and separate latex compilation. (Or use `--verbose`  which gives you the whole log file from the latex compilation.)

**Comment by lrdegeest** [comment]
oops, good catch, sorry about that. but it doesn't solve the problem.

**Comment by jgm** [comment]
glad it works now.
