### ISSUE TITLE
Copying metadata from frontmatter to defaults file breaks linebreaks

### ISSUE THREAD

**Issue by rriemann** [jgm/pandoc#6250]
Dear all,

I use now a defaults file to configure my latex templates. However, when I copy some variables from the markdown frontmatter to the defaults file, linebreaks get lost. The latex `\\` is converted to `\textbackslash{}`.

I use pandoc 2.9.2.1 on Linux x64_86.

## MWE

I run this command with the files below:

    pandoc --template template.tex -d defaults.yaml -t latex mwe.md

### Output

```latex
Frontmatter:

street\\
city

Defaults:

street\textbackslash{} city
```

### mwe.md

```md
---
fm: |
  street\
  city
---
```

### defaults.yaml

```yaml
metadata:
  defaults: |
    street\
    city
```

### template.tex

```
Frontmatter:

$fm$

Defaults:

$defaults$
```

**Comment by jgm** [comment]
This isn't a bug.  `metadata` in the defaults file behaves like metadata specified on the command line using `--metadata`.  And about that, the manual sayeth:

> Values will be parsed as YAML boolean or string values. 

Metadata in a YAML metadata section of a Markdown document, by contrast, is parsed as Markdown like the rest of the document.

This explains the difference you're seeing.

**Comment by rriemann** [comment]
A work-around for future reference:

The following template allows to render the pipe block in the front matter and list values from the defaults file equally:

```tex
$for(defaults)$$defaults$$sep$\\
$endfor$
```
