### ISSUE TITLE
Listings inline code doesn't work with markdown to pdf

### ISSUE THREAD

**Issue by BenBanerjeeRichards** [jgm/pandoc#6253]
Pandoc version 2.9.2.1

Pandoc listings inline code doesn't seem to work when converting from markdown to pdf. As an example, test.md contains the following - 

```markdown
int f() {} 

`int f() {}`
```

Running the command `pandoc test.md -o test.pdf --listings` produces -

![image](https://user-images.githubusercontent.com/5972559/78581213-7f20bc00-782b-11ea-9897-eb6c3ec6caa5.png)

You can tell that the normal text and inline code are not exactly the same, however the inline code is certainly not monospace.

One interesting point is that this works fine if you convert from markdown to .tex, and then from .tex to pdf. If I run `pandoc test.md --listings -o test.tex` this produces the following tex file (test.tex) - 

```latex
int f() \{\}

\texttt{int\ f()\ \{\}}
```

and then running `pandoc test.tex -o test.pdf` produces the following, which looks like it's working exactly as expected - 

![image](https://user-images.githubusercontent.com/5972559/78793074-d351aa80-79a9-11ea-8549-05ff4b32e27d.png)

[Edited as I was looking at the wrong LaTex file]

Further edit - 
inline code works fine when used in headings

**Comment by mb21** [comment]
You're saying it produces:

```
int f() \{\}

\texttt{int\ f()\ \{\}}
```

what LaTeX would you want it to produce?

see also https://pandoc.org/MANUAL.html#creating-a-pdf

**Comment by BenBanerjeeRichards** [comment]
The issue is only with markdown to PDF - `pandoc test.md -o test.pdf --listings`. See the first screenshot. Markdown to latex to PDF works fine (i.e. `pandoc test.md --listings -o test.tex` followed by `pandoc test.tex -o test.pdf` produces the second screenshot which is correct).

**Comment by mb21** [comment]
To debug the PDF creation, it can be useful to look at the intermediate representation: instead of -o test.pdf, use for example -s -o test.tex to output the generated LaTeX. You can then test it with pdflatex test.tex.

**Comment by BenBanerjeeRichards** [comment]
Right that makes sense thanks, I was omitting the `-s`. 

Turns out that this is a listings thing, and the font can be made monospace by adding `\lstset{basicstyle=\footnotesize\ttfamily}` to my file header.

Thanks for the help
