### ISSUE TITLE
ignoring underscored text 

### ISSUE THREAD

**Issue by nedvedikd** [jgm/pandoc#6255]
Hi,

I'm using pandoc (**version 2.9.2.1**) to convert documents to dokuwiki format.
I ran into a problem using this command:

```bash
pandoc input.html -f html -t dokuwiki -o output_dokuwiki.txt --preserve-tabs
```

**Input:**
```html
<strong>bold</strong>
<em>italic</em>
<u>underline</u>
```

**Output:**
```
**bold** //italic// underline
```

**Expected output:**
```
**bold** //italic// __underline__
```

As you can see, pandoc is clearly ignoring underscored text.

Thank you so much for your help!

**Comment by jgm** [comment]
Currently pandoc parses HTML u as
```
Span ("",["underline"],[]) inlines
```
so it would be easy to modify the docuwiki writer to recognize this form and emit `__...__`.

**Comment by 3v0k4** [comment]
Would it make sense to introduce an additional `Underline` value constructor in [`Inline`](https://hackage.haskell.org/package/pandoc-types-1.20/docs/Text-Pandoc-Definition.html#t:Inline)?

I'm asking because I see there is a `Emph` and `Strong` but not a `Underline`. Instead `Span` is used as @jgm mentioned.

**Comment by jgm** [comment]
Probably yes. https://github.com/jgm/pandoc-types/pull/53
I've resisted this for a long time, on grounds that Underline is presentational not structural.
But doing all of this via Spans is not very robust.

**Comment by mb21** [comment]
> I've resisted this for a long time, on grounds that Underline is presentational not structural.
> But doing all of this via Spans is not very robust.

True, there is also the point that `<em` and `<strong` are encouraged in HTML5 but, `<u` is deprecated...

**Comment by julianespinel** [comment]
Hello! I just ran the commands suggested by @nedvedikd (against master), and I got the expected result:
```
**bold** //italic// __underline__
```

Could we close this issue?

**Comment by jgm** [comment]
yes, thanks
