### ISSUE TITLE
latex template sets fonts before applying beamer theme

### ISSUE THREAD

**Issue by Drakulix** [jgm/pandoc#6260]
Using pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
In an ubuntu/eoan container environment

`metadata.yaml`:
```yaml
---
theme: metropolis
monofont: JetBrainsMono
...
```

`cmdline`:
`pandoc -s -f markdown -t beamer --pdf-engine=lualatex -V classoption=notes --fail-if-warnings --metadata-file=metadata.yaml -o slides.pdf slides.md`

Results in a PDF that uses `FiraMono` as metropolis sets defaults for fonts (`FiraSans` and `FiraMono`), which is unexpected to say the least.

WIth a custom template I confirmed, that re-ordering the blocks that apply beamer themes and the font block fixes this problem for me. I am not very familiar with latex and therefor am not aware of any new problems this might cause for other latex-engines.

Would you accept a PR changing the default latex template?

**Comment by jgm** [comment]
I'd certainly consider one.  Just as long as it doesn't break anything for other themes.
(I seem to recall other similar issues -- have you searched issues and pull requests?)
