### ISSUE TITLE
How to place bibliography in orgmode for exporting to docx?

### ISSUE THREAD

**Issue by mgcyung** [jgm/pandoc#6262]
It is said in MANUAL.txt that if the style calls for a list of works
cited, it will be placed in a div with id `refs`. However, I have
tried
```
#+BEGIN_REFS
#+END_REFS
```
and
```
#+REFS:
```
which did not work. I have also tried a lua filter
```
function Div (div)
  if div.classes[1]=='refs' then
     div.id = 'refs'
     return div
  end
end
```
and it didn't work either.

**Comment by tarleb** [comment]
This should work:

``` org
#+ATTR_HTML: :id refs
#+BEGIN_bib
#+END_bib
```

The name of the block doesn't matter, the ID is set via `#+ATTR_HTML`.

The filter would work as well, but should check for `div.classes[1] == 'REFS'`.

**Comment by mgcyung** [comment]
I tried both in the beginning of the buffer, but the bibliography still in the end of the docx.

**Comment by tarleb** [comment]
Could you provide use with an example file demonstrating the problem? Please also include pandoc version as well as the exact command used to convert the input.

**Comment by mgcyung** [comment]
Problem solved. It works for
```
#+ATTR_HTML: :id refs
#+BEGIN_bib
#+END_bib
```

The problem is caused by ox-pandoc I use for exporting. It didn't export 
```
#+ATTR_HTML: :id refs
```
to the intermediate org file which is used for the pandoc command.
