### ISSUE TITLE
Jira: Transforming the (x) icon

### ISSUE THREAD

**Issue by Estigy** [jgm/pandoc#6264]
Hi!

Of all the icons that Jira defines, the (x) icon is the only one that gets transformed a 4-byte utf8 character that can't be stored to a regular utf8 datatable

May I suggest to use ⊠, the "squared times" sign, instead.
- It is only a 2-byte utf8 character that can therefore correctly be stored to a utf8 database.
- It plays nicely with the transformations of (-) and (+) which get translated to ⊟ "squared minus" and ⊞ "squared plus"

Thanks, Estigy

**Comment by tarleb** [comment]
How about ❌ "cross mark"?

**Comment by tarleb** [comment]
Since we are at it, maybe ✅ would be the better check mark `(/)`.

**Comment by Estigy** [comment]
3-bytes characters are perfectly fine :-)

I'd suggest the following changes to the current icon transformation map:
(/) => ✔
(x) => ❌
(!) => ❗
(+) => ➕
(-) => ➖
(?) => ❓
(*) => ⭐

**Comment by tarleb** [comment]
I like that! ⚠ seems a bit closer to Jira's output, but I like the consistency of using "heavy …" for as many things as possible. Let's go with your suggestions.

**Comment by tarleb** [comment]
Do you happen to also have a suggestion for `(off)`? It's currently 💡, same as `(on)`.

**Comment by Estigy** [comment]
I know... I had included the "bulb off" icon in my search before posting my list but did not come up with anything usable.
(Also the colored stars don't have any meaningful replacements...)

**Comment by tarleb** [comment]
Maybe "power sleep symbol" ⏾ or "crescending moon" 🌙

**Comment by tarleb** [comment]
I went with 🌙 for now.

If star color is important, please raise another issue. We could wrap the emoji in a `Span` and add the color as an attribute.
