### ISSUE TITLE
Variables: defaults file vs cli definition

### ISSUE THREAD

**Issue by blaggacao** [jgm/pandoc#6273]
Command line variable definition does **NOT override** the defaults file (interpretable as per _"default"_ in _"defaults"_). possibly true for metadata, as well. They get string-concatenated, instead.

```yaml
# defaults.yaml
...
variables:
  letterhead: ".data/letterheads/default.png"
...
```
Using `pandoc 2.9.2.1`...
```shell
docker run --rm --volume "`pwd`:/data" --user `id -u`:`id -g` pandoc:2.9.2.1 \
     --defaults=defaults.yaml \
     --data-dir=.data \
     --variable=letterhead:".data/letterheads/P1s/letterhead.png" \
     --to=pdf

# with an appropriate tex template yields:
...
! Unable to load picture or PDF file '.data/letterheads/default.png.data/letter
heads/P1s/letterhead.png'
...
```
... on the following `tex` snippet ...
```tex
% install{background}
% install{everypage}
$if(letterhead)$
\usepackage{background}
\backgroundsetup{
  scale=1,
  color=black,
  opacity=1,
  angle=0,
  contents={%
    \includegraphics[width=\paperwidth,height=\paperheight]{$letterhead$}
    }%
}
$endif$
```
... which, for elimination of doubt, is rendered to ...
```tex
% install{background} - this is custom parsable syntax
% install{everypage} - this is custom parsable syntax
\usepackage{background}
\backgroundsetup{
  scale=1,
  color=black,
  opacity=1,
  angle=0,
  contents={%
    \includegraphics[width=\paperwidth,height=\paperheight]{.data/letterheads/default.png.data/letterheads/P1s/letterhead.png}
    }%
}

```

**Comment by jgm** [comment]
The behavior is actually consistent: if you use `-V` multiple times on the command line to set the same variable, pandoc makes the variable a list with all values:
```
% cat my2.html
$for(foo)$
$foo$
$endfor$
% pandoc --template my2.html -Vfoo=a -Vfoo=b -s --quiet
a
b
```

The same thing happens when the variable has a value set in the defaults file and then the same variable has a value set on the command line: it's exactly as if you'd set the same variable twice on the command line.

Why the concatenation?  Because the doctemplates library will concatenate lists when rendering them as strings:
```
% cat my.html
$foo$
% pandoc --template my.html -Vfoo=a -Vfoo=b -s --quiet
ab
```

**Comment by jgm** [comment]
If our templating system had a `first` and `last` pipe that took the first or last value of a list, that could provide a workaround:  `$foo/last$` would give you the last value set.  This could be a worthy addition to `doctemplates`.

**Comment by blaggacao** [comment]
I see. Indeed a `first` or `last` pipe was needed in another context as well, it would be useful well beyond this default selection.

**Comment by jgm** [comment]
I've added these in doctemplates 04aa5b899f10ef213a770b3a00c9bb27f9949565

**Comment by blaggacao** [comment]
Nice, thank you. Should this issue be closed, then?
