### ISSUE TITLE
Add text color variable to default.latex

### ISSUE THREAD

**Issue by blaggacao** [jgm/pandoc#6274]
For some layouts a dark gray, especially when using coloured letterheads, just looks better.
A solution I found here https://tex.stackexchange.com/questions/26549/how-do-i-globally-set-the-text-color-in-xelatex

adapted to pandoc
```tex
...

\usepackage{xcolor}

\makeatletter
\newcommand{\globalcolor}[1]{%
  \color{#1}\global\let\default@color\current@color
}
\makeatother

$if(textcolor)$
\AtBeginDocument{\globalcolor{$textcolor$}}
$endif$

\begin{document}

\section{A section heading}

some test text

\end{document}
```
`fontspec`'s `Color` does break `hyperref`'s link coloring, the [docs](http://mirrors.ucr.ac.cr/CTAN/macros/latex/contrib/fontspec/fontspec.pdf) read:
>Color(orColour) uses font specifications to set the colour of the text. You should think ofthis as the literal glyphs of the font being coloured in a certain way. Notably, this mechanismis different to that of thecolor/xcolor/hyperref/etc. packages, and in fact usingfontspeccom-mands to set colour will prevent your text from changing colour using those packages at all!

**Comment by blaggacao** [comment]
they can then be relatively easily set with mix expressions: `textcolor: black!25!darkgray!100`

**Comment by jgm** [comment]
I'm not sure I want to clutter up the default template with this, given that it's going to be needed fairly rarely.  You can always insert a bit of code in a header-includes section to get this effect.

**Comment by blaggacao** [comment]
True, the only argument would be that's not quite obvious how to do this with tex.
