### ISSUE TITLE
[Feature Request] Enable/disable numbered sections from metadata

### ISSUE THREAD

**Issue by coldacid** [jgm/pandoc#6275]
When processing a large number of Markdown files, it'd be helpful if writers would check for the value of the `numbersections` property in a Markdown document's YAML metadata block to determine whether or not to use section numbering for that particular document's output, and only rely on the `-N` command line option when the property is not explicitly set in YAML. This would save time and effort sorting between which files need section numbering when converted to another format, and which ones require that they not have section numbering.

**Comment by mb21** [comment]
Since `numbersections` is a template variable, setting it in the document's YAML metadata should already work... have you tried it?

see e.g. https://github.com/jgm/pandoc/blob/master/doc/customizing-pandoc.md#template-variables

**Comment by jgm** [comment]
The issue is that for some formats, section numbering can be triggered by setting a template variable, but for others the numbering is added by the writer.

In any case, you can set section numbering in a defaults file (see `--defaults`); metadata is for proper metadata, not processing instructions.

**Comment by coldacid** [comment]
It turns out that pandoc-crossref does what I need, and handled the number sectioning by file for me. I looked at defaults files but my understanding from the documentation is that it would apply to all files I'd pass through, there would be no way to make exceptions by file that way.

**Comment by jgm** [comment]
You can specify different defaults files for different pandoc runs.
