### ISSUE TITLE
Filter out special character on parsing 

### ISSUE THREAD

**Issue by skymonio** [jgm/pandoc#6278]
Not really an issue. Maybe a feature request. 

Would pandoc provide a command to remove, or just not aknowledge the existence of a defined special character (namely curly braces for instance) while it parses a file ?

I could'nt find such a feature in the documentation, but I'm sure Pandoc is capable of doing that.

**Comment by jgm** [comment]
I don't understand the request, without more detail.  But questions like this should be directed to the pandoc-discuss mailing list rather than here.

**Comment by mb21** [comment]
You can filter out specific words  by matching on `Str` in your lua-filter, see https://pandoc.org/lua-filters.html:

```lua
return {
  {
    Str = function (elem)
      if elem.text == "{" then
        return nil
      else
        return elem
      end
    end,
  }
}
```

**Comment by skymonio** [comment]
Thank you very much @mb21 that's exactly what I was looking for!

Sorry for wrong posting..
