### ISSUE TITLE
Does pandoc-2.9.2.1-macOS.pkg work? Has it been tested?

### ISSUE THREAD

**Issue by kiwi0fruit** [jgm/pandoc#6281]
Does [pandoc-2.9.2.1-macOS.pkg](https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-macOS.pkg) work? Has it been tested?

Conda package manager [**cannot repackage**](https://github.com/conda-forge/pandoc-feedstock/pull/65) it for some reason (pandoc binary is packaged and available from path (type pandoc works) during tests but it can't run properly). Windows and Linux versions work OK. Previous 2.9.2 worked OK on macOS too.

**Comment by mb21** [comment]
what do you mean with "it can't run properly"?

**Comment by kiwi0fruit** [comment]
I don't have a Mac so all I have is CI log:

```
+ type pandoc
+ pandoc --help
pandoc is $PREFIX/bin/pandoc
/usr/local/miniconda/conda-bld/pandoc_1586783992960/test_tmp/run_test.sh: line 8: 14121 Killed: 9               pandoc --help
```

bash has pandoc binary in path but when build system attempts to run pandoc it returns cryptic error. So it would be useful to know if binary works at least on one machine. That might rule out some redundant bugfixing work.

**Comment by mb21** [comment]
Jep pandoc-2.9.2.1-macOS.pkg works fine for me on Catalina, just tested. But what is `run_test.sh` (it's not in this repo) and what's on line 8 of that file? Also, what macOS version is that?

**Comment by kiwi0fruit** [comment]
Thanks a lot for confirming! I guess next I would start with macOS version...

**Comment by kiwi0fruit** [comment]
`run_test.sh` is autogenerated by conda-build so who knows what it looks like. But on the trouble line is most likely `pandoc --help`.

**Comment by jgm** [comment]
Since we've confirmed that the package works, it seems this is an issue with conda and not pandoc. Can it be closed?

One relevant difference btw 2.9.2.1 and 2.9.2 is that the 2.9.2.1 package is notarized for macOS, to keep Catalina's gatekeeper happy.

**Comment by kiwi0fruit** [comment]
Thanks for details!
