### ISSUE TITLE
Parse OMML in Markdown

### ISSUE THREAD

**Issue by bwiernik** [jgm/pandoc#6282]
I find it much easier to write and read equations in the [UnicodeMath/OMML syntax](http://www.unicode.org/notes/tn28/UTN28-PlainTextMath-v3.pdf) than in TeX Math. Considering that pandoc already includes an OMML reader/writer, I am wondering whether it might be possible to enable equations to be entered in either format in Markdown (e.g., perhaps using a YAML argument)?

**Comment by jgm** [comment]
I'm not sure you and I mean the same thing by OMML.  What pandoc can read and write is the XML format used by Word.  You seem to have something else in mind?  Surely you don't really prefer to write
``` xml
  <m:oMath>
    <m:sSup>
      <m:e>
        <m:r>
          <m:t>x</m:t>
        </m:r>
      </m:e>
      <m:sup>
        <m:r>
          <m:t>2</m:t>
        </m:r>
      </m:sup>
    </m:sSup>
    <m:r>
      <m:t>=</m:t>
    </m:r>
    <m:f>
      <m:fPr>
        <m:type m:val="bar" />
      </m:fPr>
      <m:num>
        <m:r>
          <m:t>1</m:t>
        </m:r>
      </m:num>
      <m:den>
        <m:r>
          <m:t>2</m:t>
        </m:r>
      </m:den>
    </m:f>
  </m:oMath>
```
rather than
```
x^2 = \frac{1}{2}
```

**Comment by bwiernik** [comment]
Sorry, I was misunderstanding what OMML was; Murray Sargent's writing on this for Microsoft is confusing with names sometimes. I was meaning the UnicodeMath syntax

```
x^2 = 1/2
```

My apologies for the confusion. I see that that's a much bigger undertaking, then.

**Comment by jgm** [comment]
See the existing issue at https://github.com/jgm/texmath/issues/125
If that were done then there'd be options in pandoc. Until then...closing.
