### ISSUE TITLE
pdflatex not found. Please select a different --pdf-engine

### ISSUE THREAD

**Issue by muv1** [jgm/pandoc#6283]
If I run a command like this:

~~~
pandoc -o out.pdf in.md
~~~

I get this result:

~~~
pdflatex not found. Please select a different --pdf-engine or install pdflatex
~~~

Why is `pdflatex` being called for a Markdown file? I can understand if the
input file was TeX or LaTex, but its not.

**Comment by jgm** [comment]
As the manual indicates, pandoc produces a PDF by first converting the source to LaTeX and then running pdflatex.  There are also other possible routes to a PDF. As the error message indicates, look in the manual under `--pdf-engine` for full enlightenment.

**Comment by muv1** [comment]
Thanks for the response. After some thinking, Pandoc seems heavy for my use. For
any interested, I think I am going to try a different route. Goldmark and
Prince:

- <https://github.com/yuin/goldmark>
- <https://princexml.com/download>

**Comment by alerque** [comment]
@muv1 Prince is not free. That may be fine for your usage, but not for everybody.

Yes LaTeX is a heavyweight as far as software footprints go, but you don't have to use it either. There are several other backends you can use to get PDF output from Pandoc.

**Comment by muv1** [comment]
@alerque yeah I wish Prince was open source, but it seems like a decent lightweight solution for HTML to PDF. If you know any open source options that arent huge I would be interested.

**Comment by jgm** [comment]
Again, see pandoc's `--pdf-engine` documentation:  weasyprint, wkhtmltopdf, ...
Actually the lightest-weight path to PDF from pandoc is probably via pdfroff, which is a very small dependency.

**Comment by muv1** [comment]
https://github.com/jgm/pandoc/issues/6286
