### ISSUE TITLE
--pdf-engine should allow arbitrary arguments

### ISSUE THREAD

**Issue by muv1** [jgm/pandoc#6286]
In another thread it was suggested I use something like `--pdf-engine pdfroff`.
With a Windows system, you can get `pdfroff` as part of a base Cygwin install
as `man-db` requires it (`ghostscript` package also required). However with
Cygwin at least `pdfroff` is just a shell script. So I dont think its currently
possible to use with Pandoc, as Windows Pandoc uses `createProcess`:

~~~
$ pandoc -o a.pdf --pdf-engine C:/cygwin/bin/pdfroff a.md
pandoc.exe: C:/cygwin/bin/pdfroff: createProcess: invalid argument (Exec
format error)
~~~

Another option could be to invoke the shell, with `pdfroff` as an argument. It
seems Pandoc does not like that though:

~~~
$ pandoc -o a.pdf --pdf-engine C:/cygwin/bin/sh.exe a.md
pdf-engine must be one of wkhtmltopdf, weasyprint, prince, pdflatex, lualatex,
xelatex, latexmk, tectonic, pdfroff, context
~~~

To workaround, I had to create my own executable called `pdfroff`, that calls
the real `pdfroff`. Here is example code with Go:

~~~go
package main
import (
   "os"
   "os/exec"
)
func main() {
   a1 := os.Args
   a1[0] = "/bin/pdfroff"
   c1 := exec.Command("sh", a1...)
   c1.Stdin = os.Stdin
   c1.Stdout = os.Stdout
   c1.Run()
}
~~~

It might be helpful if Pandoc relaxed its requirements on the executable name,
then I could just call `sh.exe` directly. Unless someone has a better idea.

**Comment by muv1** [comment]
https://github.com/jgm/pandoc/issues/6283

**Comment by jgm** [comment]
Pandoc needs to know which pdf engine is being used, since each one requires different handling.  It would have no idea what to do with `sh.exe`.  The workaround you mention is what I would have suggested.

**Comment by alerque** [comment]
If your environment is setup correctly it should be possible to exec a shell script just like anything else. It sounds like the hash-bang handling is wrong in the Cygwin package. Not Pandoc's fault.

**Comment by muv1** [comment]
@alerque no, Windows doesnt work like that. It can just Exec a script like
Linux. Have you tried it? If so you would know that it fails:

~~~
$ cat a.sh
#!/bin/sh
echo Sunday

$ cat a.go
package main
import (
   "log"
   "os"
   "os/exec"
)
func main() {
   c1 := exec.Command("./a.sh")
   c1.Stdout = os.Stdout
   e1 := c1.Run()
   if e1 == nil {
      log.Println("Cmd.Run")
   } else {
      log.Fatal(e1)
   }
}

$ go run a.go
2020/04/15 06:32:46 fork/exec ./a.sh: %1 is not a valid Win32 application.
exit status 1

$ cat b.go
package main
import (
   "os"
   "os/exec"
)
func main() {
   c1 := exec.Command("sh", "a.sh")
   c1.Stdout = os.Stdout
   c1.Run()
}

$ go run b.go
Sunday
~~~

**Comment by alerque** [comment]
@muv1 I think that's a function of what shell you are running. I used to use Cygwin and I _could_ execute scripts like that. I don't have a Windows box to test with now but I'm guessing you are in Powershell or something besides Cygwin or the WSL. I think something is off about your environment because there should be a system in place to make that work.

**Comment by muv1** [comment]
@alerque I dont think youre understanding.

Yes, I can execute the script itself in a Cygwin shell. But programs compiled
with Go dont execute with a Cygwin shell. They execute with the system shell
(`cmd.exe`).

A possible way around this would be to compile a Cygwin program, rather than a
native Windows program. But I dont think Go can do this, so I might have to use
C.

**Comment by muv1** [comment]
Closing this as I found a workaround, will post as new issue, thanks
