### ISSUE TITLE
Info re:   HTML --> TeX --> PDF

### ISSUE THREAD

**Issue by ORESoftware** [jgm/pandoc#6293]
For the life of me, I cannot figure out why this works:

```shell
pandoc ./test-2.html  --pdf-engine=xelatex -t latex  -o  ./test.pdf   
```

but this doesn't work:

```shell
pandoc ./test-2.html  -t latex | pdflatex  >  ./test.pdf  
```

I would expect the 2nd one to  

1. convert to latex
2. convert from latex to pdf

but when I upon the resulting file with a pdf viewer, I get "cannot open text/plain file - unsupported"

but the first one works - it converts to latex (but I am not sure if it converts to pdf) but at least it's viewable by a pdf reader...

**Comment by jgm** [comment]
You opened another issue about this same thing, and I've answered there...but you should not open issues for such things.  As requested, questions should go to pandoc-discuss mailing list.
