### ISSUE TITLE
HTML validator complaining about "Stray end tag col" with --self-contained option

### ISSUE THREAD

**Issue by aubertc** [jgm/pandoc#6295]
The following `temp.md` file

```mardown
| A | B| 
| --- | ---------- |
|  A long, long, long, long, long, long, text. | A long, long, long, long, long, long, text. |
```

when compiled with 

```bash
pandoc --self-contained -o temp.html temp.md
```

produces a table that begins with 

```html
<table>
<colgroup>
<col style="width: 23%"></col>
<col style="width: 76%"></col>
```

which causes e.g. the [Nu HTML Checker](https://validator.w3.org) to complain about 

> Error: Stray end tag col.

Pandoc 2.9.2.1

Maybe this is documented somewhere, but I could not find where: what is the cause / justification / rationale for this?
This error is not present with the `-standalone` option.

**Comment by jgm** [comment]
Does it still complain if you change it to
```
<col style="width: 23%" />
```

**Comment by aubertc** [comment]
Nope.

**Comment by aubertc** [comment]
There is an update, and now it complains with

> Info: Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.
>
> From line …
> `<col style="width: 23%" />`

This code could be replaced by

`<col style="width: 23%">`

to comply with this validator.

**Comment by jgm** [comment]
Well, we try to produce polyglot HTML that is also valid XHTML.  That's because we need XHTML for valid EPUBv3.
For background see e.g. #5146.

**Comment by aubertc** [comment]
Thanks a lot for the context, it makes sense.
