### ISSUE TITLE
Handling of raw <img> tags in Markdown vs. CommonMark?

### ISSUE THREAD

**Issue by mgeier** [jgm/pandoc#6297]
I'm converting Markdown to reStructuredText and I would like to handle raw `<img>` tags afterwards.

The strange thing is that Markdown and CommonMark seem to behave differently regarding `<img>` tags:

```
$ pandoc -f markdown -t rst
<img src="test.png">
^D

```

```
$ pandoc -f commonmark -t rst
<img src="test.png">
^D
.. raw:: html

   <img src="test.png">

```

Shouldn't both have the same behavior in this case?

The extension `raw_html` doesn't seem to have an influence on this:

```
$ pandoc -f markdown+raw_html -t rst
<img src="test.png">
^D

```

```
$ pandoc -f commonmark+raw_html -t rst
<img src="test.png">
^D
.. raw:: html

   <img src="test.png">

```

I'm using this Pandoc version (on Debian Linux):

```
$ pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

**Comment by jgm** [comment]
```
% pandoc -f markdown -t native
<img src="test.png">

[Para [RawInline (Format "html") "<img src=\"test.png\">"]]
% pandoc -f commonmark -t native
<img src="test.png">

[RawBlock (Format "html") "<img src=\"test.png\">\n"]
```
As you can see, the difference is whether this is parsed as a block or inline element.  `-f markdown` parses it as inline, and the rst writer doesn't have a way to deal with inline HTML (only block-level).

**Comment by mgeier** [comment]
Oh, very interesting!

I guess one could argue that `<img>` should not be a block, but according to the current CommonMark spec it is (because any open tag starts an HTML block).

Anyway, thanks for clearing this up!

I still find it confusing that Markdown and CommonMark create such utterly different output in this case.

Feel free to close this, though!

**Comment by jgm** [comment]
commonmark tries to get by without hardcoding a gigantic list of HTML tags that would constantly need updating.  See the spec for its heuristics.

**Comment by mgeier** [comment]
Thanks! Yes, that makes sense. I've seen the heuristics in https://spec.commonmark.org/0.29/#html-blocks, but it would probably be good to add the motivation you have just mentioned?
