### ISSUE TITLE
Use setlanguage instead of setmainlanguage

### ISSUE THREAD

**Issue by qaisjp** [jgm/pandoc#6298]
File `my.yaml`:

````yaml
header-includes:
- |
    ```{=latex}
        \usepackage{enumerate}
    ```
````

File `test.md`:

````md
Some markdown line here

```{=latex}
\begin{enumerate}[label=Line \arabic*]
\item something here, should be one,
\item this should say line two, and
\item yeah this should say three
\end{enumerate}
```

Some markdown line here
````

Command `pandoc --metadata-file my.yaml test.md -o project.pdf`:

```
Error producing PDF.
! Missing number, treated as zero.
<to be read again> 
                   \c@* 
l.1738 \begin{enumerate}[label=Line \arabic*]

```

Googling the error in a bunch of different ways leads me to this link, which may be related: https://tex.stackexchange.com/a/378051

Which may be relevant, since we do not use `selectlanguage`: https://github.com/jgm/pandoc/blob/9a809d4d01f1a9cba4401e98d95cccf8a0ec7e75/src/Text/Pandoc/Readers/LaTeX.hs#L1872-L1873

But I am not good at LaTeX (which is why I'm writing Markdown), so maybe I am doing something wrong.

**Comment by jgm** [comment]
Have you looked at the documentation for the latex enumerate package?
http://tug.ctan.org/tex-archive/macros/latex/required/tools/enumerate.pdf
Looks like you need the syntax
```
\begin{enumerate}[Line 1]
\item something here, should be one,
\item this should say line two, and
\item yeah this should say three
\end{enumerate}
```

**Comment by qaisjp** [comment]
Oh, sorry, thank you.

(For others, I actually needed `\begin{enumerate}[{Line} 1]`, as per the docs.)
