### ISSUE TITLE
Proposal: Adding support for textual subtitle files (VTT, SRT...)

### ISSUE THREAD

**Issue by anasram** [jgm/pandoc#6299]
Pandoc version: 2.9.2.1

# The Problem

I'm trying to take advantage of `smart` extension to normalize video subtitle files, using Pandoc like this:

```sh
pandoc --wrap=preserve -t plain-smart "foo.srt" -o "foo2.srt"
```

Where `foo.srt` file is:

```srt
1
00:01:30,500 --> 00:01:35,000
- Hello world!
- Hi!
```

The output file (`foo2.srt`) will look like this:

```srt
1
00:01:30,500 –> 00:01:35,000
- Hello world!
- Hi!
```

with the follwing warning message:

> [WARNING] Could not deduce format from file extension .srt
>  Defaulting to markdown

So, of course, I use an external tool like`sed` to fix ` –>`, turning it back to `-->`.

# A Proposed Solution

I'm wondering now, what do you think of adding support to common subtitle file formats, so that a command like this for example:

```sh
pandoc --wrap=preserve -t subtitle-smart "foo.srt" -o "foo2.srt"
```

can produce a `foo2.srt` file like this:

```srt
1
00:01:30,500 --> 00:01:35,000
— Hello world!
— Hi!
```

As you can see, such a support maybe needs to consider just two points:

* Maintaing `-->` string.
* Converting `-` in the beginning of lines to em dash `—`, since such line mean a dialog; not an unordered list.

**Comment by mb21** [comment]
you might get away with: `pandoc -f markdown-smart -t plain-smart`

but yeah.. using pandoc for this is borderline-abusive ;-)

**Comment by alerque** [comment]
Short of having a srt reader/writer in Pandoc, you should probably write your own basic parser that iterates through the text block in the subtitle file and passes just the plain text to Pandoc one string at a time (probably through a library, not instantiating new processes for every string) for normalization.

**Comment by jgm** [comment]
I think using sed with pandoc sounds like a good solution to this problem.
You could always apply sed first, as a preprocessor rather than a postprocessor, changing `-` at the start of a line to `--` and changing `-->` to `\-\->`.

**Comment by jgm** [comment]
As @mb21 notes,
```
pandoc -f markdown-smart -t plain-smart
```
should preserve the `-->`.  But I agree with other posters above that pandoc is not the right tool for this.
