### ISSUE TITLE
corrupt powerpoint output from markdown with outline math in :::notes

### ISSUE THREAD

**Issue by iwelch** [jgm/pandoc#6301]
```
# Header

Example

::: notes
An outline equation in a note triggers a defective pptx file

$$ E(D) = 1/6\cdot(-\$6) $$
:::


# Needed

otherwise nothing shows.

```

run this through pandoc and the resulting pptx file is considered corrupt by Microsoft Office.

**Comment by jkr** [comment]
It seems that powerpoint can't handle math expressions in the notes. So I guess the question is what we should replace it with. The simplest thing would be to keep it as LaTeX. This would have the benefit of correctness. We could also try converting it to pandoc inlines, and seeing what it can do with that. But the speaker notes have pretty primitive formatting, so I'm afraid that will end up being pretty lossy.

@jgm: does TeXMath have any nifty tricks for producing equations in text?

**Comment by jgm** [comment]
TeXMath has a renderer which creates an `[Inline]` -- this is "faking it as unicode." You can fall back to raw tex when this isn't possible.  Or you could just use raw tex in all cases; it's just notes.

**Comment by iwelch** [comment]
hi john---I don't really need this content.  my problem is more with the
creation of a file that MS Powerpoint declares to be corrupt.  I think
pandoc should create valid files, even if they are incomplete.

Suggestion: maybe, for now, you might just put a "math not yet supported"
string into the output stream when math is detected in the `::: notes```
section.

regards,

/iaw

--
Ivo Welch (ivo.welch@ucla.edu)
http://www.ivo-welch.info/
J. Fred Weston Distinguished Professor of Finance, UCLA Anderson
