### ISSUE TITLE
Curly quotes in RTL strings (Arabic, Urdu,... etc)

### ISSUE THREAD

**Issue by anasram** [jgm/pandoc#6302]
Pandoc version: 2.9.2.1

According to Pandoc User's Guide, `smart` extension interprets straight quotes "" as curly quotes “”.

e.g., say we have an English input:

> He said: "Yes".

Pandoc with `smart` extension (`pandoc -t plain-smart`) turns it into:

> He said: “Yes”.

Now suppose we have a RTL text:

> &#8235;قال: "نعم".

Pandoc with `smart` extension currently turns it into:

> &#8235;قال : “نعم”.

Whilst it should be:

> &#8235;قال : ”نعم“.

![Arabic curly quotes](https://user-images.githubusercontent.com/12219238/79726732-ee021880-82f3-11ea-9571-2d7bb72dbf27.png)

**Comment by tarleb** [comment]
Hey, thanks for your patience. Could you take a look at the [pandoc-quotes.lua filter](https://github.com/pandoc/lua-filters/tree/master/pandoc-quotes.lua) and see if it solves your problem?

**Comment by anasram** [comment]
Thank you Albert!

It doesn't support Arabic yet.

**Comment by tarleb** [comment]
Thanks for the feedback. I added support for Arabic, could you try again?

**Comment by anasram** [comment]
Didn't work!

After saving `~/.pandoc/pandoc-quotes.lua` or `~/.local/share/pandoc/pandoc-quotes.lua`, I tried:

```sh
pandoc -f markdown -t plain "in.md" -o "out.txt";
```

where input file is:

```md
---
title: اختبار
language: ar
lang: ar
---

أبجد "هوز" حطي كلمن

```

The output was:

```
أبجد “هوز” حطي كلمن
```

Did I miss something?

**Comment by tarleb** [comment]
Try adding `--lua-filter pandoc-quotes.lua` to your pandoc command.

**Comment by anasram** [comment]
Works fine! Thanks.

However, I think a character-based approach could be better.

**Comment by tarleb** [comment]
Happy to hear it's working!

I'm afraid changes to the writer would add too much complexity and are likely out of scope for pandoc.

**Comment by mustafa0x** [comment]
The lua filter won't work for mixed language documents. A crude solution is: `s/“([ء-ي].*?)”/”\1“'/g`.
