### ISSUE TITLE
[pptx] Regression: pandoc cannot read pptx template

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#6320]
To reproduce the bug:

```bash
# with pandoc 2.9.2.1 macOS:
% pandoc -o custom-reference.pptx --print-default-data-file reference.pptx
% printf '# testing\n\nA test.' |
pandoc --template=custom-reference.pptx -o testing.pptx ||
rm -f custom-reference.pptx
pandoc: Cannot decode byte '\xb5': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

# The version that this bug is introduced

Use this command on different versions of pandoc:

```bash
./pandoc -o custom-reference.pptx --print-default-data-file reference.pptx
printf '# testing\n\nA test.' |
./pandoc --template=custom-reference.pptx -o testing.pptx ||
rm -f custom-reference.pptx
```

Valid output with pandoc 2.7.3 on macOS.

Invalid output on these versions

- pandoc 2.8 macOS
- pandoc 2.8.1 macOS
- pandoc 2.9.2.1 macOS
- pandoc 2.9.2.1 linux-amd64
- pandoc 3324412d7 macOS (latest non-failing master)

i.e. **first breaking release is 2.8**

```bash
# with pandoc 2.8 macOS:
% ./pandoc -o custom-reference.pptx --print-default-data-file reference.pptx
% printf '# testing\n\nA test.' |
./pandoc --template=custom-reference.pptx -o testing.pptx ||
rm -f custom-reference.pptx
pandoc: Cannot decode byte '\xb4': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

Note that the byte it is complaining is different from 2.9.2.1

# Notes

Diff between 2.7.3 and 2.8: <https://github.com/jgm/pandoc/compare/2.7.3...2.8>

It only affects the output template. Without specifying a template pandoc can successfully output to a pptx file. So it must be the case that the "internal template" pandoc used without `--template` is different from that generated by `pandoc -o custom-reference.pptx --print-default-data-file reference.pptx`.

(Sorry, this is as far as I dig. I can dig deeper if the origin is still unclear.)

# More observation (Edit)

Interestingly, if I use the reference produced by 2.7.3 and take that as the `--template` in 2.9.2.1 then it has this error:

```bash
pandoc: Cannot decode byte '\x9b': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

So after all the problem might not be the template produced, but when pandoc is reading the template from `--template`. Another support for this is that the template produced can actually be read by other programs.

**Comment by jgm** [comment]
You don't use `--template` with a pptx reference doc.  That's just for text-format templates.

Use `--reference-doc`.
