### ISSUE TITLE
Slashes inside blockquotes prevent breaklines from working reliably

### ISSUE THREAD

**Issue by kalbj** [jgm/pandoc#6322]
I'm converting markdown to pdf using pandoc.exe 2.9.2.1 on Windows, and the xelatex pdf engine.

I'm using fvextra and defining options to breaklines, but am finding some lines break while other almost identical lines don't.

Commandline is
```
pandoc input.md --from=markdown --to=pdf --pdf-engine=xelatex -V mainfont="Arial" -V monofont="Consolas" -V geometry:margin=1in -o output.pdf
```

input.md file:
```
---
header-includes:
 - \usepackage{fvextra}
 - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines=true,breakanywhere=true,breakatwhitespace=true,breakautoindent=true,commandchars=\\\{\}}
---

1. Block quote with \\ or \/ doesn't wrap, falls off edge of paper

    abc abc abc abc abc abc abc abc abc abc abc abc `C:\Program Files (x86)\abcdefgh\abcdefghijk\abc\abcdefh\abcdefghijk.json`

    abc abc abc abc abc abc abc abc abc abc abc abc `C:/Program Files (x86)/abcdefgh/abcdefghijk/abc/abcdefh/abcdefghijk.json`

1. Increase the width of leading text, and it starts working!!

    abc abc abc abc abc abc abc abc abc abc abc abc abc abc abcd `C:\Program Files (x86)\abcdefgh\abcdefghijk\abc\abcdefh\abcdefghijk.json`

1. With spaces or hyphens instead of slashes, line breaks ok in middle of word.

    abc abc abc abc abc abc abc abc abc abc abc abc `C: Program Files  x86  abcdefgh abcdefghijk abc abcdefh abcdefghijk.json`

    abc abc abc abc abc abc abc abc abc abc abc abc `C:-Program Files (x86)-abcdefgh-abcdefghijk-abc-abcdefh-abcdefghijk.json`

```

Output:

![image](https://user-images.githubusercontent.com/36740299/80502250-4a0a1400-8968-11ea-94d8-9eed6a6f4ae7.png)

I've tried different variations of the `commandchars` option but without success.

Is this a bug, or an error on my part? Is there a way of putting long file paths inside block quotes like this?

**Comment by jgm** [comment]
You mean backtick code spans, not block quotes, right?
In any case, the thing to do is to examine the LaTeX output produced by pandoc and try to get a minimal example just in the latex.

**Comment by kalbj** [comment]
Thanks, yes I did mean backtick code spans.

So the LaTeX output of Pandoc looks fine. There's no difference between the line which wraps and the one which doesn't. Running this directly through xelatex or lualatex exhibits the problem. 

Does this mean it's a problem with fvextra? In which case this issue is on the wrong repo - apologies.

LaTeX doc here: [input2.tex](https://github.com/jgm/pandoc/files/4548021/input2.txt)

Here's the important part:
```
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Backtick code span with \textbackslash{} doesn't wrap, falls off edge of paper

  abc abc abc abc abc abc abc abc abc abc abc abc
  \texttt{C:\textbackslash{}Program\ Files\ (x86)\textbackslash{}abcdefgh\textbackslash{}abcdefghijk\textbackslash{}abc\textbackslash{}abcdefh\textbackslash{}abcdefghijk.json}
\item
  Increase the width of leading text, and it starts working

  abc abc abc abc abc abc abc abc abc abc abc abc abc abc abcd
  \texttt{C:\textbackslash{}Program\ Files\ (x86)\textbackslash{}abcdefgh\textbackslash{}abcdefghijk\textbackslash{}abc\textbackslash{}abcdefh\textbackslash{}abcdefghijk.json}
\end{enumerate}
```

Output looks like:
![image](https://user-images.githubusercontent.com/36740299/80527923-0b3a8500-898d-11ea-9c7d-7106289f5d7a.png)

**Comment by jgm** [comment]
If there's no obvious problem with pandoc's tex output, then I think it would make sense to see if it's a bug in fvextra.  (They might say we're doing something wrong, but if we knew what tex we should be producing, we could fix it.)

**Comment by kalbj** [comment]
Pandoc is using \texttt for these backtick code spans, but apparently it computes the line width incorrectly - described here: https://tex.stackexchange.com/a/304

A solution which seems to work is to insert \allowbreak at various points in the text - described here: https://tex.stackexchange.com/a/247335/214285

I'm not sure if Pandoc should reasonably be expected to workaround this "feature" of \texttt.

**Comment by tarleb** [comment]
I'm closing this, as there doesn't seem to be much we can do on the pandoc side of things.

As for the workaround: hphenation can also be automated, see https://groups.google.com/d/topic/pandoc-discuss/jgFSE0Xniyw/discussion.
