### ISSUE TITLE
Latex reader fails parsing `\author{}` if it contains empty lines

### ISSUE THREAD

**Issue by TiredFalcon** [jgm/pandoc#6324]
`pandoc 2.9.2.1`

When converting this document with the command `pandoc -s -f latex -t native main.tex`:

```tex
\documentclass{article}

\begin{document}
    \title{Document title}
    \author{
        Me

    }
    \maketitle
\end{document}
```

the parser fails with this error:
```
Error at "source" (line 8, column 1):
unexpected ()
    }
^
```

It also fails if the empty line comes before `"Me"`.  
If the `\author` command is moved before `\begin{document}`, then the parser fails silently (i.e., no "author" is included in the parsed `Meta`).

When removing the empty line inside the author block, instead, the command successfully completes and `Meta` containns the author list.

Using `pdflatex`, everything rennders perfectly in all cases.  
My use case is converting the raw `tex` code into `markdown`, for purposes of text extraction.

**Comment by jgm** [comment]
Fixed by 0b5e2601f5700522e392400eee992938c086ef7a
