### ISSUE TITLE
Can't \usepackage{cstypo} in header-includes

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#6326]
The `default.latex` template has changed somewhat recently to include `babel` or `polyglossia` packages after expansion of `$header-includes$`. This breaks some documents like mine which contains `\usepackage{cstypo}` in the `$header-includes$`. The `cstypo` package relies on being included after `babel` or `polyglossia`.

I can imagine that there was a good reason for this change. Would it be possible to provide secondary `$right-before-begin-document-header-includes$` kind of hook so that packages like `cstypo` are again usable with Pandoc templates?

**Comment by brainchild0** [comment]
It seems that lack of fine control of package loading order generates a variety of specific recurring problems for users.

This general problem also appears in #5811.

Note that apparently subsequent `\usepackage` declarations for the same target are harmless. As such a solution is sufficient if only it ensure  that the first declaration for each package appears in sequence with others such as to avoid conflicts.

**Comment by jgm** [comment]
Yes, I do recall there was a reason for this.  Package loading order in LaTeX can be fiddly.
For details see commit 732005456e2b28150943a5a4e11bca6e1566f309 and issue #3898.

I'm a bit reluctant to proliferate variables -- after all, you can just use a custom template in cases like this.

**Comment by brainchild0** [comment]
> after all, you can just use a custom template in cases like this.

From a strictly user standpoint,  @jgm,  or at the very least a personal one, this response unfortunately comes across as starkly unsatisfactory. 

 Assimilating a forked version of the distribution template into a project is not a trivial affair. Bringing a custom template into a project may be easy for some users, but surely not for all. Worse, maintaining a parallel version of the template incurs challenges and perils that largely undermine the utility of using the application.

> I'm a bit reluctant to _proliferate variables_

I'm not understanding your language. What specifically have you considered that you have come to regard as problematic?

**Comment by tarleb** [comment]
It seems that this is unlikely to be implemented, so I'm closing the issue for now.
