### ISSUE TITLE
Can't use # for headings inside minipages

### ISSUE THREAD

**Issue by ritobanrc** [jgm/pandoc#6327]
If I have two minipages side by side, I can't use # to declare a heading inside them: 
```
\begin{minipage}{0.45\textwidth}
# Left Section

\end{minipage}
\begin{minipage}{0.45\textwidth}
# Right Section

\end{minipage}
```

I get the error: 

```Error producing PDF.
! You can't use `macro parameter character #' in internal vertical mode.
l.53 #
```

But if I replace the # with `\section`, it works just fine: 

```latex
\begin{minipage}{0.45\textwidth}
\section{Left Section}

\end{minipage}
\begin{minipage}{0.45\textwidth}
\section{Right Section}

\end{minipage}
```

For some reason, pandoc doesn't expand the `#` when it's inside a minipage. The latex output is this: 

```latex
\begin{minipage}{0.45\textwidth}

# Left Section

\end{minipage}
\begin{minipage}{0.45\textwidth}

# Right Section

\end{minipage}
```

**Comment by jgm** [comment]
In a Markdown document pandoc will treat a LaTeX environment as a raw LaTeX block (thus not parsing anything inside as Markdown).
One way to workaround this would be to use the `raw_attribute` syntax.

````
```{=latex}
\begin{minipage}{0.45\textwidth}
```

# Left Section

``` {=latex}
\end{minipage}
\begin{minipage}{0.45\textwidth}
```

# Right Section

```{=latex}
\end{minipage}
```
````

**Comment by piiskop** [comment]
The last suggestion does not work and gives the same error message.

**Comment by jgm** [comment]
It works for me. Perhaps you have an older version of pandoc, or you're not using `-f markdown`.

**Comment by piiskop** [comment]
This is what RStudio Server shows:

```
/usr/lib/rstudio-server/bin/quarto/bin/tools/pandoc +RTS -K512m -RTS keemia.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output keemia.tex --lua-filter /home/kalmer/R/x86_64-pc-linux-gnu-library/4.3/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /usr/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /tmp/RtmpOSwCsP/file11ba351429efdf --embed-resources --standalone --table-of-contents --toc-depth 2 --template default.latex --number-sections --highlight-style tango --pdf-engine xelatex --include-in-header preamble.tex --wrap preserve --include-in-header /tmp/RtmpOSwCsP/rmarkdown-str11ba3524102664.html --variable tables=yes --standalone -Mhas-frontmatter=false --citeproc 
output file: keemia.knit.md
```

`pandoc --version`

> pandoc 2.9.2.1
> Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
> Default user data directory: /home/kalmer/.local/share/pandoc or /home/kalmer/.pandoc
> Copyright (C) 2006-2020 John MacFarlane
> Web:  https://pandoc.org
> This is free software; see the source for copying conditions.
> There is no warranty, not even for merchantability or fitness
> for a particular purpose.

**Comment by jgm** [comment]
That version is several years old.

**Comment by cagix** [comment]
@piiskop you could also redefine `\begin{...}` and `\end{...}` in your `preamble.tex` like this:

```tex
\newcommand{\minipagebegin}{\begin{minipage}}
\newcommand{\minipageend}{\end{minipage}}
```

in your markdown you can use this:

```markdown
\minipagebegin{0.45\textwidth}
# Left Section

\minipageend
\minipagebegin{0.45\textwidth}
# Right Section

\minipageend
```

this should work even with pandoc 2.9.x :) i remember using something like this in the olden days ...

**Comment by piiskop** [comment]
This is the newest possible version on _Ubuntu 22.04 LTS_.

**Comment by piiskop** [comment]
My desktop computer has _Ubuntu 23.10_:

`pandoc --version`

> pandoc 2.17.1.1
> Compiled with pandoc-types 1.22.2.1, texmath 0.12.4, skylighting 0.12.3.1,
> citeproc 0.6.0.1, ipynb 0.2
> User data directory: /home/kalmer/.local/share/pandoc
> Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
> This is free software; see the source for copying conditions. There is no
> warranty, not even for merchantability or fitness for a particular purpose.

The layout works but it gives messages like

> You can't use `macro parameter character #' in internal vertical mode. #

**Comment by piiskop** [comment]
_pandoc 2.9.2.1_ works without an error message if using redefinition.
