### ISSUE TITLE
Final list element becomes loose if any previous ones are

### ISSUE THREAD

**Issue by dulsonan** [jgm/pandoc#633]
I think this is a dupe of [issue 17](https://github.com/jgm/pandoc/issues/17), but I also do think it's a bug. Or, if not a bug, something that produces slightly undesirable output, in my case at least.

This input:

```
* List item 1
* List item 2
* List item 3
* List item 4
```

Produces the following html:

```
<ul>
<li>List item 1</li>
<li>List item 2</li>
<li>List item 3</li>
<li>List item 4</li>
</ul>
```

Do anything that causes an li to become loose, like add some code, and the final element acquires a paragraph tag:

```
* List item 1
* List item 2 - with some code

        println("Hello, world")
* List item 3
* List item 4
```

produces:

```
<ul>
<li>List item 1</li>
<li><p>List item 2 - with some code</p>
<pre><code>println(&quot;Hello, world&quot;)</code></pre></li>
<li>List item 3</li>
<li><p>List item 4</p></li>
</ul>
```

Which looks strange if you have a few compact bullets at the end of a list. I wouldn't expect the blank line which terminates the list to also cause the final bullet to be interpreted as a paragraph.

(Actually, in the document I'm working on the bullet with code in it being given extra paragraph tags also makes things look weird, but that's a separate thing --- I don't think there's a way to embed code in an li without adding that blank line; without it the code is treated as a continuation of the preceding line, even with 8 spaces of indent. But the blank line _also_ causes the preceding text to treated as a paragraph.)

**Comment by jgm** [comment]
See also #671

**Comment by jgm** [comment]
The relevant code is `compactify` in `Text.Pandoc.Shared`.
It checks to see if the last paragraph would be the only Para; if so, it converts it to Plain.
Since we have a Para above the code block, it stays a Para.

Not really sure how to fix this without a drastic overhaul in list parsing.
Note that parsing as `commonmark` gives you paragraphs all around.
