### ISSUE TITLE
No longer can put a line break into header

### ISSUE THREAD

**Issue by kugelblitz** [jgm/pandoc#6333]
Hello,

With Pandoc 2.9.2 I no longer can produce a line break inside header with a custom style and label, as I was able in Pandoc 2.1.1 and probably some later version, too.

The Markdown source that once did the trick for me is the following

```markdown

# [Appendix\ A \
**Some Title**]{custom-style="AppendixHeadingOne"} {#sec:app-a label="A"}
```

It no longer works. Even with `-f markdown-escaped_line_breaks` it produces the header, but without the line break.

I also tried `<br />` and hanging double space, to no avail.

In case output format matters, I am using docx output.

Is there any other way? And why the way that used to work is broken now?

**Comment by jgm** [comment]
It has been this way for a very long time now. See the changelog for pandoc 2.0:

```
  * Markdown reader:

    + Don't allow backslash + newline to affect block structure (#3730).
      Note that as a result of this change, the following, which formerly
      produced a header with two lines separated by a line break, will
      now produce a header followed by a paragraph:

        # Hi\
        there

      This may affect some existing documents that relied on
      this undocumented and unintended behavior.  This change makes pandoc
      more consistent with other Markdown implementations, and with itself
      (since the two-space version of a line break doesn't work inside ATX
      headers, and neither version works inside Setext headers).
```

**Comment by tarleb** [comment]
[StackOverflow answer of mine](https://stackoverflow.com/a/52193443/2425163) describing a method to input line breaks in headers and titles.

**Comment by kugelblitz** [comment]
Albert, 
Thank you very much for the reference. Your lua script works flawlessly indeed.

John,
The Markdown I posted definitely worked in 2.1.1, so the backslash+newline approach (at least for headers with brackets and braces after them) was prohibited not in 2.0 but later.

In any case, is there a Markdown-only way to put a line break into header, that does not cause inconsistency that the backslash+newline had? If not, maybe it is worth considering translating `<br>` into a newline?

**Comment by jgm** [comment]
You can use a Lua script to convert something else (such as the raw html inline `<br>` into a LineBreak element.
