### ISSUE TITLE
Allow less indentation in definition lists

### ISSUE THREAD

**Issue by a-vrma** [jgm/pandoc#6334]
Version:
```
pandoc 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /home/aman/.local/share/pandoc or /home/aman/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

The definition list's content has to be indented 4 spaces. Why doesn't it allow 2 spaces? It
allows 2 spaces for all the other lists. Here is an example of a definition list that doesn't get parsed correctly with `pandoc -f markdown+compact_definition_lists`:

```
microtype
~ Make text look even nicer. More specifically character protrusion and font expansion,
  the adjustment of interword spacing and additional kerning, as well as hyphenatable
  letterspacing (tracking) and the possibility to disable all or selected ligatures.
```

I get this output (if converting to markdown):

```
microtype
:   Make text look even nicer. More specifically character protrusion
    and font expansion,

the adjustment of interword spacing and additional kerning, as well as
hyphenatable letterspacing (tracking) and the possibility to disable all
or selected ligatures.
```

**Comment by jgm** [comment]
No, it doesn't allow 2 spaces indent for all other lists.  See the manual for the rules for list indentation.  Block-level content included in the list must be indented to the level of the first content after the opening list marker: if the marker is `-` followed by one space, that will be two spaces, but it might be more for other kinds of lists. The problem with def lists is that the marker is generally quite long, so this rule doesn't make sense.  Hence we fall back to the old pandoc behavior (described also in the original Markdown documentation), requiring 4 spaces indent.

**Comment by a-vrma** [comment]
Okay that's fair. I still think it looks ugly for those of us that use a two space indent for their unordered and ordered list continuations but what you said makes sense.
