### ISSUE TITLE
Support org-mode checkboxes (i.e. allow task_lists extension for org reader)

### ISSUE THREAD

**Issue by patkun** [jgm/pandoc#6336]
I have tried to use org-mode checkboxes in an org input file for specific processing via a pandoc filter, but noticed that whilst there is a task_lists extension for pandoc markdown sources, the extension is not available for org input. From what I can gather, the gfm and org-mode checkboxes differ merely in whether the x (for a checkmark) is lower- or uppercase (org has `[X]`). Would it be possible to extend the org reader accordingly?
The org-mode progress cookies (e.g. `[3/3]`, `[/]`, `[%]`) are updated within org-mode and would not necessarily require particular processing. It seems org-mode itself exports them as code snippets.

**Comment by eddiegroves** [comment]
Reference: https://orgmode.org/manual/Checkboxes.html
