### ISSUE TITLE
Missings Instructions/Feature to add sub-heading to "Section Header" slide layout in PPTX

### ISSUE THREAD

**Issue by seesharprun** [jgm/pandoc#6338]
> *I'm not sure if this is a missing instruction in the User Guide or a missing feature in the tool. I searched both GitHub and the guide and could not find an answer.*

If you generate the default reference PPTX file using ``pandoc -o custom-reference.pptx --print-default-data-file reference.pptx``, the file will have a Section Header layout with a subtitle:

![image](https://user-images.githubusercontent.com/5067401/80982619-92f31a00-8df9-11ea-8678-44b8a2f79cdd.png)

I was unable to find a way to provide content for the subtitle with a placeholder of ``"Some explanatory text"``.

I first tried to generate a PPTX file using the [sample presentation Markdown](https://pandoc.org/MANUAL.html#producing-slide-shows-with-pandoc) found on the User Guide and the simple command ``pandoc sample.md --output sample.pptx``:

![image](https://user-images.githubusercontent.com/5067401/80982941-faa96500-8df9-11ea-9d56-8d953b738856.png)

I even tried adding text after the header to see if it shows up as a subtitle but it only showed up as an extra slide:

```
...
# In the evening

Some subtitle here

## Dinner
...
```

```
pandoc sample.md --output sample.pptx --slide-level=2
```

![image](https://user-images.githubusercontent.com/5067401/80983177-48be6880-8dfa-11ea-8436-51845251204c.png)

Am I missing something basic here? I couldn't tell if it was an undocumented feature or unimplemented feature.

**Comment by seesharprun** [comment]
Almost forgot, I am running pandoc 2.7.3 on Windows 10.

**Comment by jgm** [comment]
I don't use pptx writer myself, but have you tried setting the metadata title and subtitle in your document?

**Comment by seesharprun** [comment]
If you set the metadata title and subtitle at the top of the document, that only impacts the title slide.

For the section header slides, I didn't see an easy way to set the subtitle. I tried this syntax:

```
## Setting the scene { subTitle="Demo" }
```

**Comment by jgm** [comment]
Try a YAML header:
```
---
title: My title
subtitle: My subtitle
author: Me
...

# First slide

etc.
```

**Comment by jgm** [comment]
Oh, I see, you want something similar on slides other than the first one.

**Comment by jgm** [comment]
@jkr can probably answer this.

**Comment by jkr** [comment]
Yeah -- this isn't implemented, and shouldn't be in the template. We could do something with metadata as discussed above, but I don't think this feature would be worth messing up the parity with the other slide writers.

**Comment by seesharprun** [comment]
Fair point. I saw it in the reference template and thought I may have missed a feature. I am closing this issue.
