### ISSUE TITLE
Jira: quote mistakenly taken as bold

### ISSUE THREAD

**Issue by git4-me** [jgm/pandoc#6343]
The following in Jira isn't rendered in any special way, i.e. raw text and visual will be the same:
```
func('${bar}', module_env.Glob('*.py'))
next_func('${foo}/*.py')
```

What I'm getting as HTML from pandoc is falsely putting a <strong>...</strong> into the text:
```
<p>func('${bar}', module_env.Glob('<strong>.py'))<br />
next_func('${foo}/</strong>.py')</p>
```

Here is the rendered html:
![image](https://user-images.githubusercontent.com/62103114/81058680-38c48880-8ecf-11ea-9035-11ab529842e0.png)

Correct is the first one which doesn't get any special treatment by Jira.

**Comment by tarleb** [comment]
Looks like Jira doesn't allow markup to span across two lines.
