### ISSUE TITLE
pandoc does not respond

### ISSUE THREAD

**Issue by Gahamelas** [jgm/pandoc#6345]
Just installed it.  » pandoc --version is working.
When I type "pandoc", the terminal is hanging and I see nothing coming on the screen. I must exit. Anyone experiencing this problem? I am on MacOS Catalina.

**Comment by tarleb** [comment]
From the pandoc user's manual, section "using pandoc":

> If no input-files are specified, input is read from stdin. Output goes to stdout by default.

Pandoc doesn't hang, it awaits input. Try writing some text, press enter, then send the "end of file" signal by pressing <kbd>^</kbd><kbd>D</kbd>.

**Comment by jgm** [comment]
https://pandoc.org/getting-started.html

**Comment by OfirD1** [comment]
@tarleb, I'm bumping this to ask a related question. I'm on Windows. When executing:

`pandoc -o test.txt`

hitting <kbd>Enter</kbd> and then entering some input text to stdin: 

`this is a test text`

and then pressing <kbd>ctrl</kbd>+<kbd>d</kbd> doesn't do anything; pressing <kbd>ctrl</kbd>+<kbd>c</kbd> writes *an empty* `test.txt` file to cwd and terminates pandoc.

Why does the file is empty?

**Comment by OfirD1** [comment]
Found the answer on the getting started page (emphasis mine):

>When you’re finished (**the cursor should be at the beginning of the line**), type Ctrl-D on OS X or Linux, or Ctrl-Z followed by Enter on Windows.
