### ISSUE TITLE
Feature request : add Ext_implicit_figures to CommonMark reader

### ISSUE THREAD

**Issue by PaulRivier** [jgm/pandoc#6350]
Hi John,

if it is compatible with your plans for the CommonMark reader, I would appreciate the implicit_figures behaviour, which is handy to use image as blocks.

To be honest, I don't think I have ever included any image as inline element in a Markdown document, this seems too impractical to me.

Cheers,

**Comment by jgm** [comment]
It's in the works and can be done when this is implemented:
https://github.com/jgm/commonmark-hs/issues/9

**Comment by jgm** [comment]
Actually it would be possible to add this even to the current cmark-based commonmark reader.
I'm not sure if it's worth doing that, since I hope to switch over to the Haskell lib soon, but maybe I'll reopen this for now.

**Comment by PaulRivier** [comment]
Thank you, that was fast !

**Comment by tg-x** [comment]
This doesn't seem to work anymore in pandoc 2.19, was this removed at some point?
Or does this work again in pandoc 3?

**Comment by jgm** [comment]
Support for this disappeared unintentionally due to some archictectural changes. Will fix!

**Comment by jgm** [comment]
Fixed in commit 725ec09a104d8ad486989f32a4c55d9d731629ea
