### ISSUE TITLE
Hint to Atlassian Confluence

### ISSUE THREAD

**Issue by moridius** [jgm/pandoc#6351]
Atlassian Confluence seems to use the same wiki markup as Jira. Would be nice to have a hint to that in the documentation. I spent quite some time looking for a way to convert Markdown to Confluence markup and didn't realise that Pandoc supports that already.

**Comment by mb21** [comment]
Is it the same? or just mostly the same?

**Comment by alerque** [comment]
I believe the same wiki engine code drives both products. It's just a bunch of marketing shenanigans as Atlassian is trying to endear themselves to more than just developers. Jira is an issue tracker and very technical, Confluence is trying to capture more whole-company buy-in.

**Comment by tarleb** [comment]
Good idea. Would you like to draft a PR with a concrete suggestion?

> Is is the same?

It is *mostly* the same, with minor, very annoying differences. At least the Confluence instance which I had to work with was not able to parse HTML entities like `&bsol;`, but parsed others just fine (e.g., `&auml;`). Jira parses HTML entities just fine.

**Comment by moridius** [comment]
That means it's two different engines... I thought it's the same. Maybe write a hint that Jira markup _might_ work for Confluence? Just finding the word "Confluence" in the documentation would have been really helpful for me.

**Comment by tarleb** [comment]
BTW, this also means that issues will occur if a backslash-containing document is imported into Confluence. HTML entities appear to be the only way to reliably produce a plain backslash in Jira markup, so this is what pandoc uses.

**Comment by alerque** [comment]
Perhaps they are the same engine at two different versions or the engine has feature flags? Should this be supported in Pandoc via a common format with `jira+confluence` or whatever extension to smooth over the differences?

**Comment by mb21** [comment]
maybe we can just put in the manual:

> `--to`:
> ...
> `jira` (Atlassian Jira wiki markup, mostly the same as Confluence)

**Comment by tarleb** [comment]
I'd be ok with calling it "Atlassian Jira/Confluence wiki markup".  The official docs are sometimes imprecise and even partially wrong, but seem to describe the same format. It doesn't seem too bad to conflate the two formats.

I also like @alerque's idea of adding an extension, but I won't be able to implement that within the near future.
