### ISSUE TITLE
link_attributes does not convert size unit

### ISSUE THREAD

**Issue by CodeSandwich** [jgm/pandoc#6353]
I'm converting an MD to a HTML. According to the [docs](https://pandoc.org/MANUAL.html#extension-link_attributes), the `link_attributes` extension should convert an image size unit to px for the HTML output. It doesn't seem to happen:

```bash
echo '![](pic.jpg){width=5cm}' | pandoc -f markdown -t html
```
prints
```html
<p><img src="pic.jpg" style="width:5cm" /></p>
```
Enabling the extension manually doesn't fix the issue. `-f markdown+link_attributes` has no effect, but `-t html+link_attributes` causes an error: `The extension link_attributes is not supported for html`.

`pandoc --version`:
```
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.3.4
```

**Comment by mb21** [comment]
Indeed, the behaviour was changed in https://github.com/jgm/pandoc/commit/cb7b0a69859cbf838519c5ad5f35d40ffd4f4246#diff-9da4893eeab88b87f94db2b69af787ff without updating the MANUAL.

**Comment by CodeSandwich** [comment]
Interesting! I'm no haskeller, but it looks like the unit conversion funcitonality was completely removed? Or is there some other way to do that in Pandoc?

**Comment by mb21** [comment]
No, it's still there for certain output format and unit combinations... but centimeters are actually valid units in CSS, and some people want them to be passed through as is.

I'm not sure I agree with this, since CSS just defines `1cm = 96px`, which is the default behaviour of pandoc's `--dpi` option anyway... so maybe we should revert this? @jgm Passing through `em` makes sense, but why cm and in?

**Comment by jgm** [comment]
The manual says:
"The width and height attributes on images are treated specially. When used without a unit, the unit is assumed to be pixels. However, any of the following unit identifiers can be used: px, cm, mm, in, inch and %."

So, the attributes are treated as pixels only if no unit is specified.  Here a unit is specified, and it's passed through unchanged.  That accords with the docs, no?

**Comment by jgm** [comment]
Oh, I see now: " Dimensions are converted to pixels for output in HTML-like formats. "

**Comment by jgm** [comment]
Seems like we just need to update the documentation?
The current behavior in HTML seems fine: `style` is used to set the width and height (rather than width/height attributes, which only accept pixel values).  And CSS allows all of these dimensions, if I'm not mistaken?

**Comment by jgm** [comment]
See https://www.w3.org/Style/Examples/007/units.en.html
`in` and `cm` are definitely allowed, and there are cases where they might be preferred in HTML (esp. when you're targeting print).

**Comment by CodeSandwich** [comment]
You're right, I'll stick with `cm`s, after all for CSS they are strictly equivalent to `px`s, just with a multiplier.

I got mislead by all the materials on the internet discouraging from using real life units, but they seem to be focused on manual designing sites from scratch, for documents generated automatically it seems fine.

Thank you!

**Comment by mb21** [comment]
Yeah, I actually liked having the `width` and `height` HTML attributes, as they can be easily overriden with CSS, and it's good practice anyway to have them, as new browsers [use them to calculate aspect ratio before external CSS is loaded](https://wiki.developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping).

But yeah, guess it doesn't really matter. The markdown width/height attributes are probably only used mostly for one-off documents anyway, and nobody appears to have complained about the change.

**Comment by CodeSandwich** [comment]
@jgm You've closed this issue, are the docs fixed?

**Comment by mb21** [comment]
will be put live in the next release, you can see the change here https://github.com/jgm/pandoc/commit/82eb4df284cd9f0f62836df9aea6f1aab0ed63e2
