### ISSUE TITLE
Cannot Find Image file

### ISSUE THREAD

**Issue by liangzid** [jgm/pandoc#6357]
I use pandoc for latex2docx, and I find the image of latex cannot be included.

Here is my input:
```
 pandoc main.tex --filter pandoc-crossref.exe --bibliography=ref\refs.bib --extract-media=result.doc   -o result.docx
```
Here is the output debug information:
> [WARNING] Could not fetch resource '../figures/intro1.jpg': replacing image with description
[WARNING] Could not fetch resource '../figures/1-1.png': replacing image with description
[WARNING] Could not fetch resource '../figures/1-2.png': replacing image with description
[WARNING] Could not fetch resource 'e-gcn.png': replacing image with description
[WARNING] Could not fetch resource '../figures/fastgat.png': replacing image with description
[WARNING] Could not fetch resource '../figures/dotattention.png': replacing image with description
[WARNING] Could not fetch resource '../figures/angle-LSH.png': replacing image with description
[WARNING] Could not fetch resource '../figures/chunk.png': replacing image with description
[WARNING] Could not fetch resource '../figures/datasetoverview.png': replacing image with description
[WARNING] Could not fetch resource '../figures/sdataplottime.png': replacing image with description
[WARNING] Could not fetch resource '../figures/sdataplotm.png': replacing image with description
[WARNING] Could not fetch resource '../figures/sdataplotbucket.png': replacing image with description
[WARNING] Could not fetch resource '../figures/coraloss.png': replacing image with description
[WARNING] Could not fetch resource '../figures/corabucket.png': replacing image with description

And this is my dir-structure:
```
├─auto
├─data
│  └─auto
├─figures
├─ref
│  └─auto
└─result.doc
```
ENV: Windows10.
Can you help me? Thanks.

**Comment by liangzid** [comment]
I have sloved it, So ...

**Comment by RayBB** [comment]
@liangzid how did you solve it?
