### ISSUE TITLE
Page break `\newpage` does not work in `docx` output

### ISSUE THREAD

**Issue by SuperV1234** [jgm/pandoc#6358]
Using pandoc 2.9.2 on Windows. It seems that any `\newpage` directive is ignored in `docx` output. If this is not a bug (intended behavior), consider this a feature request for page breaks that work in `docx` output as well.

**Comment by tarleb** [comment]
Pandoc currently does not handle page breaks, see #1934. See https://github.com/pandoc/lua-filters/tree/master/pagebreak for a easy-to-use Lua filter which adds this functionality.
