### ISSUE TITLE
Column layout using `{.columns}` does not work in `docx` output

### ISSUE THREAD

**Issue by SuperV1234** [jgm/pandoc#6359]
Using pandoc 2.9.2 on Windows. The following example markdown source:

``````markdown

::::::{.columns}

:::{.column width="33%"}
```cpp
// foo.h

template <typename T>
void foo() { /* ... */ }



```
:::

:::{.column width="33%"}
```cpp
// foo.cpp
#include "foo.h"

template void foo<int>();

```
:::

:::{.column width="33%"}
```cpp
// main.cpp
#include "foo.h"

extern template void foo<int>();

int main()
{
    foo<int>();
}
```
:::

:::::

``````

Renders correctly in `pdf` or `html` output, but the column layout is completely ignored in `docx` output.

**Comment by jgm** [comment]
What made you think it would work?  The only mention of this in the manual is in the discussion of beamer slide shows.  It's supported only for beamer, powerpoint, and HTML formats.
