### ISSUE TITLE
Development version: Lua `require 'file.lua'` – raises `PandocCouldNotFindDataFileError "file.lua"`

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc#6361]
Given:
* The Pandoc development version, as per commit `8fc5766`.
* Two Lua scripts, where one `require`-s the other.
* Both scripts are placed in `~/.pandoc/filters`.

Example code for the script that `require`-s the other:

```Lua
local concat = table.concat
local unpack = table.unpack
local stderr = io.stderr

PATH_SEP = package.config:sub(1, 1)

do
    local split = '(.-' .. PATH_SEP .. '?)([^' .. PATH_SEP .. ']-)$'
    local sanitisers = {{PATH_SEP .. '%.' .. PATH_SEP, PATH_SEP},
        {PATH_SEP .. '+', PATH_SEP}, {'^%.' .. PATH_SEP, ''}}
    
    function split_path (path)
        assert(path ~= '', 'path is the empty string')
        for _, s in ipairs(sanitisers) do path = path:gsub(unpack(s)) end
        local dir, fname = path:match(split)
        dir = dir:gsub('(.)' .. PATH_SEP .. '$', '%1')
        if dir == '' then dir = '.' end
        if fname == '' then fname = '.' end
        return dir, fname
    end
end

local wd = split_path(PANDOC_SCRIPT_FILE)
stderr:write('working directory: ', wd, '\n')
package.path = concat({package.path, concat({wd, '?.lua'}, PATH_SEP)}, ';')
stderr:write('package.path: ', package.path, '\n')

local test = require 'test'
```

I refer to this script as `require-debug.lua` below. 

The script that is `require`-ed, `test.lua` in the example above, only has to exist and be syntactically correct. In the present example, it's an empty file.

Then, calling the development version of Pandoc with

```shell
pandoc -L require-debug.lua </dev/null
```

outputs:

> working directory: /Users/odin/.pandoc/filters
package.path: /usr/local/Cellar/luarocks/3.2.1/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/Users/odin/.luarocks/share/lua/5.3/?.lua;/Users/odin/.luarocks/share/lua/5.3/?/init.lua;/Users/odin/.pandoc/filters/?.lua
Error running filter /Users/odin/.pandoc/filters/require-debug.lua:
PandocCouldNotFindDataFileError "test.lua"
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/Users/odin/.pandoc/filters/require-debug.lua:28: in main chunk

The exit status is 83.

By contrast, calling Pandoc v2.9.2.1 with the same arguments outputs:

> working directory: /Users/odin/.pandoc/filters
package.path: /usr/local/Cellar/luarocks/3.2.1/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/Users/odin/.luarocks/share/lua/5.3/?.lua;/Users/odin/.luarocks/share/lua/5.3/?/init.lua;/Users/odin/.pandoc/filters/?.lua

@njbart [discovered the issue](https://github.com/odkr/pandoc-zotxt.lua/issues/2) when he tried to run [pandoc-zotxt.lua](https://github.com/odkr/pandoc-zotxt.lua) with the development version of Pandoc.

He conjectures that [commit 0fafe9dd32d5a0266d74ac78b1818050bc69a4bd](https://github.com/jgm/pandoc/commit/0fafe9dd32d5a0266d74ac78b1818050bc69a4bd) is to blame.

Thanks for looking into this!

**Comment by odkr** [comment]
I can’t confirm @njbart's suspicion. I’ve checked out commit 9e7572da1fcc5f7299e92c93f8960e8705d184db, i.e., the one before 0fafe9dd32d5a0266d74ac78b1818050bc69a4bd, and `pandoc -L require-debug.lua </dev/null` still raises an error, if a less pretty one:

> working directory: /Users/odin/.pandoc/filters
package.path: /usr/local/Cellar/luarocks/3.3.1/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/Users/odin/.luarocks/share/lua/5.3/?.lua;/Users/odin/.luarocks/share/lua/5.3/?/init.lua;/Users/odin/.pandoc/filters/?.lua
Error running filter /Users/odin/.pandoc/filters/require-debug.lua:
PandocLuaError "PandocCouldNotFindDataFileError \"test.lua\"\nstack traceback:\n\t[C]: in ?\n\t[C]: in function 'require'\n\t/Users/odin/.pandoc/filters/require-debug.lua:28: in main chunk"

**Comment by tarleb** [comment]
Thanks for the report. I expect the guilty commit to be either 62cf21cbaa9ac3fbc2ba7218a3037208364c80a4 or fb54f3d6792d2f8e7b05e458b59142f8ae6bb3e2.

**Comment by tarleb** [comment]
Confirmed, this is to blame on a faulty change of T.P.Lua.Packages in 62cf21c. Fix incoming.

**Comment by odkr** [comment]
Thanks a lot.
