### ISSUE TITLE
Are round trips supported between ipynb and org-mode?

### ISSUE THREAD

**Issue by mwouts** [jgm/pandoc#6367]
Hello,

At https://github.com/mwouts/jupytext/issues/62 we are discussing the option to use `pandoc` to offer an automated pairing between Jupyter notebooks and org files.

I was glad to learn that Pandoc also knows about org files, that is so impressive!

Now the conversion ipynb -> org seems to work fine, but I am not sure the reverse conversion works so well.

Take for instance this notebook:
![image](https://user-images.githubusercontent.com/29915202/81949085-b476b180-9602-11ea-9ebd-3aed9484fb4f.png)

When I do
```
pandoc testing_org.ipynb -o testing_org.org
```

the result is
```
A markdown cell

#+BEGIN_SRC python
  # A code cell
  1 + 1
#+END_SRC

#+BEGIN_EXAMPLE
  2
#+END_EXAMPLE

Another markdown cell
```

which looks fine, but then, when I do
```
pandoc testing_org.org -o testing_org_back.ipynb
```

I get a different notebook, with just one Markdown cell:
![image](https://user-images.githubusercontent.com/29915202/81949663-60200180-9603-11ea-9d13-14fb845add4b.png)

Can I get the original notebook back with some additional command on the CLI? Thanks!

**Comment by jgm** [comment]
Instead of the image, can you upload the actual ipynb file?

**Comment by mwouts** [comment]
Sure! Below is the content of `testing.org.ipynb`. Also, I forgot to mention, this is happening with pandoc 2.9.2.1 from conda forge. Thank you @jgm for having a look at this!

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "A Markdown cell"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "2"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# A code cell\n",
    "1 + 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Another Markdown cell"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

**Comment by jgm** [comment]
Here's how pandoc parses this:
```
[Div ("",["cell","markdown"],[])
 [Para [Str "A",Space,Str "Markdown",Space,Str "cell"]]
,Div ("",["cell","code"],[("execution_count","1")])
 [CodeBlock ("",["python"],[]) "# A code cell\n1 + 1"
 ,Div ("",["output","execute_result"],[("execution_count","1")])
  [CodeBlock ("",[],[]) "2"]]
,Div ("",["cell","markdown"],[])
 [Para [Str "Another",Space,Str "Markdown",Space,Str "cell"]]]
```
You can round-trip to markdown because markdown output from this AST uses fenced divs to indicate the cell structure.  But this information is lost in the conversion to org.

@tarleb:  Does the org reader currently have a structure that it parses as a Div with attributes?  If so, I suppose we could make the writer produce this.

**Comment by tarleb** [comment]
Org has no real div structures, but blocs come close:

Org allows wrapping text in `#+BEGIN_type / #+END_type` to create a Div with type `type`. Additional attributes can be added with `#+ATTR_HTML:` lines:

``` org
#+ATTR_HTML: :class markdown
#+BEGIN_cell
A Markdown cell
#+END_cell
```

 produces

```
Div ("",["markdown","cell"],[])
 [Para [Str "A",Space,Str "Markdown",Space,Str "cell."]]]
```

These blocks cannot be nested, and most users don't want them because they don't behave well when producing LaTeX, where each block becomes an environment (`\begin{cell}A Markdown cell \end{cell}` for the above example), which is usually not defined.

We could add an extension to enable this behavior on demand.

**Comment by jgm** [comment]
Would we need an extension?  Why not emit this output whenever a Div has the `cell` class?  Maybe it would be odd to single out this class as a special case like that, but it would allow smooth round-tripping with org, it seems.

Another option could be to avoid the need for ATTR_HTML, by using
```
#+BEGIN_cell_markdown
```
or
```
#+BEGIN_cell_code
```

Not sure what we'd do about the nested `execution_result` structure, though.  Maybe it could just be rendered as a code block with a special class, so we don't have a nested Div.

**Comment by tarleb** [comment]
I'm torn, I neither like the increase in extensions, nor having to introduce special cases. I take it that you prefer the special case, which seems ok to me. Also, I was imprecise about nesting: it *is* possible, just not for blocks of the same name. I'm going to prepare a PR.

I learned about ox-ipynb through the issue linked above. They use special lines like `#+ipynb-newcell` as cell boundary demarcations. It would be great if we could generate compatible output consumable by that package, if not with standard output, then at least via a filter. CC @jkitchin.

**Comment by tarleb** [comment]
I've opened a draft PR here: #6375. With those changes the output becomes somewhat verbose

``` org
#+BEGIN_markdown_cell                                                          
A Markdown cell                                                                
                                                                               
#+END_markdown_cell                                                            
                                                                               
#+BEGIN_code_cell                                                              
#+BEGIN_SRC python                                                             
  # A code cell                                                                
  1 + 1                                                                        
#+END_SRC                                                                      
                                                                               
#+BEGIN_EXAMPLE                                                                
  2                                                                            
#+END_EXAMPLE                                                                  
                                                                               
#+END_code_cell                                                                
                                                                               
#+BEGIN_markdown_cell                                                          
Another Markdown cell                                                                                                                                          

#+END_markdown_cell
```

The result is currently lost when converting this back to ipynb.

**Comment by tarleb** [comment]
Maybe the best way forward would be to target ox-ipynb with a Lua filter. Here is one which inserts the `#+ipynb-newcell` marker to separate cells. @mwouts, would that work for your use case?

```lua
function Div (div)
  if div.classes:includes 'cell' and div.classes:includes 'markdown' then
    return {pandoc.RawBlock('org', '#+ipynb-newcell')} .. div.content
  end
end
```

We can still later add this to the main org writer when we've found a good conversion.

**Comment by jgm** [comment]
#5408 might be relevant too.

**Comment by tecosaur** [comment]
For maintaining cell information in moving from ipynb to markdown, perhaps named blocks could be useful?
I imagine this should work cleanly when the output is a single object (text, table, image, etc.). Then if you have to deal with multiple objects you could use the `:results draw` heading.

Here's an example of simple named code blocks and results:
```
* A heading

Here's a small paragraph of text.
Immidiately following this we have two cells.

#+NAME: cell-1
#+BEGIN_SRC shell
echo "Just a small demo"
#+END_SRC

#+RESULTS: cell-1
: Just a small demo

#+NAME: cell-2
#+BEGIN_SRC python
rows = []
r = 12
c = 6
rows.append([chr(67+j) for j in range(c)])
for i in range(r):
    rows.append([i**2 - i*j for j in range(c)])
return rows
#+END_SRC

#+RESULTS: cell-2
|   C |   D |  E |  F |  G |  H |
|   0 |   0 |  0 |  0 |  0 |  0 |
|   1 |   0 | -1 | -2 | -3 | -4 |
|   4 |   2 |  0 | -2 | -4 | -6 |
|   9 |   6 |  3 |  0 | -3 | -6 |
|  16 |  12 |  8 |  4 |  0 | -4 |
|  25 |  20 | 15 | 10 |  5 |  0 |
|  36 |  30 | 24 | 18 | 12 |  6 |
|  49 |  42 | 35 | 28 | 21 | 14 |
|  64 |  56 | 48 | 40 | 32 | 24 |
|  81 |  72 | 63 | 54 | 45 | 36 |
| 100 |  90 | 80 | 70 | 60 | 50 |
| 121 | 110 | 99 | 88 | 77 | 66 |

```

I hope this might be of some use. I'd love it if round-trip notebook format conversion became seamless :grinning:

**Comment by tarleb** [comment]
We now have reader support for the syntax used by emacs-jupyter, see #8236. I think the issue could be completed by adding support for that package in the writer as well.

**Comment by tarleb** [comment]
We now have basic round-tripping support for emacs-jupyter. It's probably not perfect, so please report any issue you find.

**Comment by morgandavidson** [comment]
Great news, thanks! I'll test it as soon as the new bin is available.

**Comment by martibosch** [comment]
How can we handle kernel and language metadata in the converted ipynb files?

There are many ways in which org mode can interact with jupyter kernels, so getting the kernel and language info almost surely requires some ad-hoc elisp load/save hooks, however, are there any pandoc flags to achieve that?

For instance, I could write some elisp function that gets my kernel and language name (maybe even the kernel display name) and forwards it to a shell call to pandoc. It still remains a challenge to see how this information could be preserved in a round trip.

A straightforward option would be to keep this information in the org files as buffer-wide properties, e.g.:

```
#+PROPERTY: kernel <my-kernel-name>
#+PROPERTY: kernel_display_name "<my-kernel-display-name>"
#+PROPERTY: kernel_language <my-kernel-language>
```

but this is far from a standard. Any clues on how this should be handled?

<hr />

This is out of the scope of this issue, but in case it interests anyone, my approach is (following https://sqrtminusone.xyz/posts/2021-05-01-org-python) to have the following buffer-wide header arguments at the beginning of each file:

```
#+PROPERTY: header-args:jupyter-python :session /path/to/kernel.json
#+PROPERTY: header-args:jupyter-python+ :async yes
```

so automatically deriving the kernel and language may require quite some elisp hacking (especially for the kernel name). Additionally, it is not practical to keep this information in round trips (especially since paths to kernels change). So far, my approach is to use elisp to get the kernel name and then combine pandoc and nbformat as in:

```
python -c "import nbformat, json, sys; nb = nbformat.read(sys.stdin, as_version=4); nb['metadata']['kernelspec'] = json.loads(sys.argv[1]); nbformat.write(nb, sys.stdout)" "$(jupyter kernelspec list --json | jq '.kernelspecs | to_entries | map(select(.key == "'"<my-kernel-name>"'") | .value.spec)' | jq '.[] | {name: "<my-kernel-name>", display_name: .display_name, language: .language}')" < path-to-my-notebook.ipynb > path-to-my-notebook.ipynb
```

this is a start but is obviously still far from ideal.

Best,
Martí
