### ISSUE TITLE
Redefining previously defined @node in texinfo output

### ISSUE THREAD

**Issue by YorkZ** [jgm/pandoc#6368]
pandoc version: 2.9.2.1
OS: Arch Linux

I was trying to convert the `systemd` documentation from `markdown` to `texinfo`. Here's the command I used:
```
cd PATH/TO/SYSTEMD/SOURCE/TREE/docs
pandoc *.md -s -o systemd.texi
```
The command succeeded. However, as I was trying to generate the GNU Info file by:
```
makeinfo --no-split --output=systemd.info -- systemd.texi
```
I got the following errors and warnings, and no output file was produced:
```
systemd.texi:1129: @node `Links' previously defined
systemd.texi:604: here is the previous definition as @node
systemd.texi:3135: @node `Final Words' previously defined
systemd.texi:3025: here is the previous definition as @node
systemd.texi:6180: @node `Execution Environment' previously defined
systemd.texi:2694: here is the previous definition as @node
systemd.texi:6787: @node `Frequently Asked Questions' previously defined
systemd.texi:3773: here is the previous definition as @node
systemd.texi:9278: @node `General Structure' previously defined
systemd.texi:4719: here is the previous definition as @node
systemd.texi:9452: @node `Fields in the regular section' previously defined
systemd.texi:4338: here is the previous definition as @node
systemd.texi:9873: @node `Fields in the privileged section' previously defined
systemd.texi:4383: here is the previous definition as @node
systemd.texi:9919: @node `Fields in the perMachine section' previously defined
systemd.texi:4393: here is the previous definition as @node
systemd.texi:9983: @node `Fields in the binding section' previously defined
systemd.texi:4406: here is the previous definition as @node
systemd.texi:10029: @node `Fields in the status section' previously defined
systemd.texi:4415: here is the previous definition as @node
systemd.texi:10135: @node `Fields in the signature section' previously defined
systemd.texi:4425: here is the previous definition as @node
systemd.texi:10198: @node `Fields in the secret section' previously defined
systemd.texi:4431: here is the previous definition as @node
systemd.texi:10345: @node `Extending These Records' previously defined
systemd.texi:4505: here is the previous definition as @node
systemd.texi:10370: @node `Examples' previously defined
systemd.texi:4510: here is the previous definition as @node
systemd.texi:604: warning: node prev `Links' in menu `Out of Focus' and in sectioning `Boot Loader Entry Identifiers' differ
systemd.texi:604: warning: node up `Links' in menu `The Boot Loader Specification' and in sectioning `The Boot Loader Interface' differ
systemd.texi:1097: warning: node next `Out of Focus' in menu `Links' and in sectioning `' differ
systemd.texi:2694: warning: node next `Execution Environment' in menu `Access to host resources' and in sectioning `Environment Variables' differ
systemd.texi:2694: warning: node `Requirements on Images' is prev for `Execution Environment' in menu but not in sectioning
systemd.texi:2694: warning: node up `Execution Environment' in menu `Portable Services Introduction' and in sectioning `The Container Interface' differ
systemd.texi:3025: warning: node prev `Final Words' in menu `Posting Pull Requests' and in sectioning `Fully Unprivileged Container Payload' differ
systemd.texi:3025: warning: node up `Final Words' in menu `Contributing' and in sectioning `The Container Interface' differ
systemd.texi:3109: warning: node next `Posting Pull Requests' in menu `Final Words' and in sectioning `' differ
systemd.texi:3773: warning: node prev `Frequently Asked Questions' in menu `systemd's Support for Filling the Kernel Entropy Pool' and in sectioning `Sharing of File Systems between Installations' differ
systemd.texi:3773: warning: node up `Frequently Asked Questions' in menu `Random Seeds' and in sectioning `The Discoverable Partitions Specification' differ
systemd.texi:4338: warning: node `General Structure' is prev for `Fields in the regular section' in menu but not in sectioning
systemd.texi:4338: warning: node up `Fields in the regular section' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4383: warning: node up `Fields in the privileged section' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4393: warning: node up `Fields in the perMachine section' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4406: warning: node up `Fields in the binding section' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4415: warning: node up `Fields in the status section' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4425: warning: node up `Fields in the signature section' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4431: warning: node next `Fields in the secret section' in menu `Mapping to struct passwd and struct spwd' and in sectioning `Mapping to struct group and struct sgrp' differ
systemd.texi:4431: warning: node up `Fields in the secret section' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4505: warning: node prev `Extending These Records' in menu `Mapping to struct passwd and struct spwd' and in sectioning `Mapping to struct group and struct sgrp' differ
systemd.texi:4505: warning: node up `Extending These Records' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4510: warning: node up `Examples' in menu `JSON User Records' and in sectioning `JSON Group Records' differ
systemd.texi:4719: warning: node next `General Structure' in menu `Fields in the regular section' and in sectioning `Storage Mechanism Plain Directory/btrfs Subvolume' differ
systemd.texi:4719: warning: node `Why JSON?' is prev for `General Structure' in menu but not in sectioning
systemd.texi:4719: warning: node up `General Structure' in menu `JSON User Records' and in sectioning `Home Directories' differ
systemd.texi:6061: warning: node next `Requirements on Images' in menu `Execution Environment' and in sectioning `' differ
systemd.texi:6188: warning: node prev `Access to host resources' in menu `Execution Environment' and in sectioning `' differ
systemd.texi:6634: warning: node next `systemd's Support for Filling the Kernel Entropy Pool' in menu `Frequently Asked Questions' and in sectioning `' differ
systemd.texi:9269: warning: node next `Why JSON?' in menu `General Structure' and in sectioning `' differ
systemd.texi:10222: warning: node next `Mapping to struct passwd and struct spwd' in menu `Extending These Records' and in sectioning `' differ
systemd.texi:10222: warning: node prev `Mapping to struct passwd and struct spwd' in menu `Fields in the secret section' and in sectioning `' differ
```
I'm new to `pandoc`, so my apology if this isn't a bug but missing something at my side.

Thanks in advance

**Comment by jgm** [comment]
Can you upload the texi file and the markdown source so we can have a look?

**Comment by YorkZ** [comment]
Hi @jgm, sorry for responding late because I didn't expect the lightening fast response from you which I really appreciated! So I just reported the issue and went away. :)

Here's the markdown source files:

file:///home/yzhao/src/systemd/docs/AUTOMATIC_BOOT_ASSESSMENT.md
file:///home/yzhao/src/systemd/docs/BLOCK_DEVICE_LOCKING.md
file:///home/yzhao/src/systemd/docs/BOOT_LOADER_INTERFACE.md
file:///home/yzhao/src/systemd/docs/BOOT_LOADER_SPECIFICATION.md
file:///home/yzhao/src/systemd/docs/CGROUP_DELEGATION.md
file:///home/yzhao/src/systemd/docs/CODE_OF_CONDUCT.md
file:///home/yzhao/src/systemd/docs/CODE_QUALITY.md
file:///home/yzhao/src/systemd/docs/CODING_STYLE.md
file:///home/yzhao/src/systemd/docs/CONTAINER_INTERFACE.md
file:///home/yzhao/src/systemd/docs/CONTRIBUTING.md
file:///home/yzhao/src/systemd/docs/CONVERTING_TO_HOMED.md
file:///home/yzhao/src/systemd/docs/DESKTOP_ENVIRONMENTS.md
file:///home/yzhao/src/systemd/docs/DISCOVERABLE_PARTITIONS.md
file:///home/yzhao/src/systemd/docs/DISTRO_PORTING.md
file:///home/yzhao/src/systemd/docs/ENVIRONMENT.md

and here's the texi file:

file:///home/yzhao/src/systemd/docs/systemd.texi

Thanks

**Comment by YorkZ** [comment]
Hi @jgm, sorry for responding late because I didn't expect the lightening fast response from you which I really appreciated! So I just reported the issue and went away. :)

Please see the attached markdown source files along with the produced `texi` file.
[md-and-texi.tar.gz](https://github.com/jgm/pandoc/files/4652147/md-and-texi.tar.gz)

Thanks


Thanks

**Comment by jgm** [comment]
You have duplicate node names because you have duplicate headings in the different markdown files (e.g. two different .md files have `## Links`).

From texinfo documentation:

> All the node names for a single Info file must be unique.
>
> Duplicates confuse the Info movement commands. This means, for example, that if you end every chapter with a summary, you must name each summary node differently. You cannot just call each one “Summary”. You may, however, duplicate the titles of chapters, sections, and the like. Thus you can end each chapter in a book with a section called “Summary”, so long as the node names for those sections are all different.

**Comment by jgm** [comment]
I don't think this is something that can be fixed in pandoc. You need to change the heading names so you get unique node names.

**Comment by Apteryks** [comment]
> 



> From texinfo documentation:
> 
> > All the node names for a single Info file must be unique.
> > Duplicates confuse the Info movement commands. This means, for example, that if you end every chapter with a summary, you must name each summary node differently. You cannot just call each one “Summary”. You may, however, duplicate the titles of chapters, sections, and the like. Thus you can end each chapter in a book with a section called “Summary”, so long as the node names for those sections are all different.

If I understand correctly, it means the titles (text) of chapters, sections or the like *can* be share the same name, but that the Texinfo specific @node added should be made unique.

Thus, when converting from say Markdown to Texinfo, Pandoc could in theory append e.g. a counter to repeated node names, while preserving the associated section title, which would greatly help.

I stumbled on this issue trying to convert https://github.com/drduh/YubiKey-Guide/blob/master/README.md via `pandoc --from=gfm --to=texinfo README.md -o README.texi && makeinfo --no-split README.texi`, made a few changes to the source, only to realize probably they wouldn't be welcome by upstream, as they are merely working around the default behavior of Pandoc (which names the nodes with their associated section titles, disregarding duplicates).

**Comment by jgm** [comment]
We'd have
```
@node Synopsis2
@chapter Synopsis
```
and then in the menu, instead of
```
@ menu
* Synopsis::
```
we'd have
```
@ menu
* Synopsis: Synopsis2
```

One possibility would be to always use the identifier on the Header element as node name. This would allow authors to choose it, and when converting from Markdown, at least, you'd automatically get unique identifiers assigned. What if you're not converting from a reader that assigns unique identifiers?  In that case we could fall back to a node name generated from the node text.

**Comment by Apteryks** [comment]
This sounds good to me!  I could  try and give it a spin, unless you are interested in implementing it.

**Comment by jgm** [comment]
Please, go ahead!

**Comment by jgm** [comment]
I fixed this.

**Comment by Apteryks** [comment]
Thanks, and sorry for dropping the ball!
