### ISSUE TITLE
Enable Banded Rows and Columns  for Tables in docx output

### ISSUE THREAD

**Issue by grafmarton** [jgm/pandoc#6371]
Word tables have so-called *Table Style Options* allowing to turn the following features on or off:
(This is found under Table Tools -> Design -> Table Style Options)

- [x] Header Row
- [x] First Column
- [x] Total Row
- [x] Last Column
- [ ] Banded Rows
- [ ] Banded Columns

Basically they activate or deactivate the extra styling defined in the Table style for the corresponding elements. Currently the docx writer outputs table with the first 4 items active and the last two inactive (as indicated by the checkboxes). This means that defining styling for e.g. "Even Banded Rows" within Table Style (in the style reference document) will not have any effect in the output.

***

**My suggestion:** per default all of the available options should be active for all tables. The user can still decide which elements he or she wants to look different, by defining the Table Style in the style referece document accordingly.

**Hint at the technicalities of a solution:**

Current output from pandoc
```
<w:tblLook w:firstRow="1" />
```

Aftter manually activating the options in MS Word and saving:
```
<w:tblLook w:firstRow="1" w:lastRow="1" w:firstColumn="1" w:lastColumn="1" w:noHBand="0" w:noVBand="0"/>
```

I belive, the change would not break anything, as the deafult *"Table"* style does not contain extra styling for these elements, so the output will only be any different if the user actively elects to define them. 

***

Alternatively, could the missing statements somehow be injected via a filter? (And if so, could someone help me write one?)

**Comment by jgm** [comment]
It would be easy to make this change, but it doesn't seem to be necessary.
With the released version of pandoc, I was able to modify the Table style to add banded colors.

**Comment by jgm** [comment]
Ah, never mind, I see now that you are suggesting that they be enabled by default. (I was misled by the ="0", but it's a double negative.)  Yeah, I guess there's no good reason not to.
