### ISSUE TITLE
--syntax-definition doesn't work with absolute paths in Windows

### ISSUE THREAD

**Issue by THS-on** [jgm/pandoc#6374]
System info
* Pandoc 2.9.2.1
* Tested using Windows 10 and 7
* Tested using cmd.exe and calling pandoc using python subprocess

If I use the absolute path for `--syntax-definition` it will fail with the following message.
```
C:\Users\User\Desktop>pandoc --syntax-definition C:\Users\User\Desktop\cpp.xml test.md
pandoc: file:///C:/Users/User/Desktop/cpp.xml: openBinaryFile: invalid argument (Invalid argument)
```

Relative paths work fine.
```
C:\Users\User\Desktop>pandoc --syntax-definition cpp.xml test.md


C:\Users\User\Desktop>
```
To recreate this problem
* Download https://github.com/jgm/skylighting/blob/master/skylighting-core/xml/cpp.xml
* Create empty  `test.md`
* run `pandoc --syntax-definition C:\path\to\cpp.xml test.md`

**Comment by jgm** [comment]
See #4836, which I thought could be fixed by turning this into a `file:` URL -- but the OP never confirmed that the fix worked, and I wasn't able to test it myself since I don't have a windows box to test on.

**Comment by THS-on** [comment]
Thanks for the quick reply. I switched my scripts to use relative paths under Windows, to make them work.
If I find the time I'll setup Haskell on Windows and try to debug it. At which parts of pandoc and hxt should I look?
Can this be fixed in pandoc or should I look into fixing it in hxt?

**Comment by jgm** [comment]
Fixing in HXT would be best, if the maintainer is responsive (I never got any reply to my bug report).  I'm not sure how to fix in pandoc, but maybe there's something I haven't thought of.

**Comment by jgm** [comment]
Try a (precompiled) nightly, you don't need to build it yourself.
https://github.com/jgm/pandoc/actions/runs/1319449072

**Comment by tim-elmer** [comment]
Ah, missed that, thanks. That build does appear to resolve the issue. I was able to process a markdown document to html with an absolutely pathed syntax definition.

👍

**Comment by THS-on** [comment]
I can confirm that this fixes the issue.
