### ISSUE TITLE
reST -> Markdown issue with LaTeX formuale

### ISSUE THREAD

**Issue by FabriceSalvaire** [jgm/pandoc#6378]
In order to convert this reST document to a suitable Markdown for Jupyter Notebook

```
.. note::
   You can see the source by clicking on the eye

.. math::

   I_d = I_s \left( e^{\frac{V_d}{n V_T}} - 1 \right)
```

Any Markdown conversion is right, for example Markdown strict add \ in LaTeX formulae

```
Note

You can see the source by clicking on the eye

$$I\_d = I\_s \\left( e^{\\frac{V\_d}{n V\_T}} - 1 \\right)$$
```

**Comment by jgm** [comment]
You need the `tex_math_dollars` extension.  Use `-t markdown_strict+tex_math_dollars`.

I'm actually not sure which extensions Jupyter allows.
