### ISSUE TITLE
LaTeX `\end{document}/\endinput` compliance

### ISSUE THREAD

**Issue by kludger56** [jgm/pandoc#6380]
By the discussion at [the group](https://groups.google.com/d/msg/pandoc-discuss/tAbc28_qkDo/C5DR5_hLBQAJ), it seems that pandoc does not recognize the commands `\end{document}` or `\endinput` commands while processing LaTeX input, and keeps on converting source to the target format, instead of ignoring it, as a standard TeX would do. I suggest to add code to tell pandoc to discard the material after these commands.

**Comment by jgm** [comment]
`\endinput` is properly handled now (#5233).
We can do something similar for `document` environment, but it will require a change in the current handling of `\subfile`.
