### ISSUE TITLE
Linux x86 (32 bit) binary

### ISSUE THREAD

**Issue by jarnosz** [jgm/pandoc#6381]
From the discussion at the [group](https://groups.google.com/forum/#!searchin/pandoc-discuss/Rivera|sort:date/pandoc-discuss/X-q4F6wr3fU/Py99HW7rAQAJ), it seems that older (32 bit) PC hardware can't run pandoc without troubles: both the windows 32 bit binary (on wine) and the Linux 64 bit binary (on qemu) exhaust their resources. I therefore request to include a 32 bit Linux statically linked binary in further releases, if practicable.

**Comment by jgm** [comment]
Dup of #1998.

Currently the static binaries are generated by a GitHub Actions script (see release-candidate over on Actions).  If you can show me how to add a 32-bit build to this script, I'd definitely consider adding it.

**Comment by kludger56** [comment]
If I were you, I'd leave this ticket open; I'll give it a shot in the summer.

**Comment by tarleb** [comment]
Whoops, I missed that #1998 had been closed too.

**Comment by tarleb** [comment]
Hi @jarnosz, did you get a chance to work on this? If so, did you run into issues that we can help with?
