### ISSUE TITLE
pandoc: Cannot decode byte '\xcb': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream

### ISSUE THREAD

**Issue by guidao17** [jgm/pandoc#6382]
Asking a question?
Please use the pandoc-discuss mailing list instead:
https://groups.google.com/forum/#!forum/pandoc-discuss
This tracker is for bug reports and enhancement requests.

Reporting a bug?
Please include your pandoc version and an example that allows us
to reproduce the problem (complete input, exact command line
used, expected and actual output).  The smaller the example, the
better.

**Comment by mb21** [comment]
you should actually fill out the issue template.... but anyway, see https://pandoc.org/MANUAL.html#character-encoding
