### ISSUE TITLE
<p> elements wrapped around <summary> elements producing invalid html5 (2.9.2.1)

### ISSUE THREAD

**Issue by poppadum** [jgm/pandoc#6385]
When converting the following markdown to html:
```md
<details>
<summary>Show me:</summary>
details para 1

details para 2
</details>
```
produces:
```html
<details>
<p><summary>Show me:</summary>details para 1</p>
details para 2
</details>
```
which is not valid html5. The `<summary>` element must be the first child of a `<details>` element ([see the html5 spec](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element))

I would expect the output to be
```html
<details>
<summary>Show me:</summary>
<p>details para 1</p>
<p>details para 2</p>
</details>
```

This looks closely related to #3694

**Comment by tarleb** [comment]
As a work-around, stop pandoc from adding additional `<p>` tags by marking summary as a raw HTML block:

~~~ markdown
<details>
```{=html}
<summary>Show me:</summary>
```
details para 1

details para 2
</details>
~~~

**Comment by jgm** [comment]
fixed.  Note that pandoc's parsing scheme will require a blank line after `details para 2` if you want it to be treated as a paragraph, and not "plain inline content."
