### ISSUE TITLE
Bug: native_divs with nested <divs> does not work [2.9.2.1] 

### ISSUE THREAD

**Issue by gabyx** [jgm/pandoc#6396]
**Input:**
```
<div class="img-with-caption">
    <img src="/files/NormalKegel.svg" style="max-width:400px;width:80%"/>
</div>
```

**Command:** 
```shell
pandoc -t native -o ./Content.ast  -f markdown+native_divs --verbose`
```

Gives:
```
[Div ("",["img-with-caption"],[])
 [CodeBlock ("",[],[]) "<img src=\"/files/NormalKegel.svg\" style=\"max-width:400px;width:80%\"/>"]]
```

The `CodeBlock` inside of the `Div` is kind of wrong.
However without the flag, e.g. `-native_spans`
```shell
pandoc -t native -o ./Content.ast  -f markdown-native_divs --verbose`
```
the output is correct.

**Comment by jgm** [comment]
Actually, this does work.  It is not a bug.
The material inside the native div is interpreted as Markdown.  In Markdown, four spaces indent gives you a code block.  And so that's what you get!
