### ISSUE TITLE
GFM with Citeproc results in Markdown inside raw HTML blocks

### ISSUE THREAD

**Issue by p3palazzo** [jgm/pandoc#6397]
When converting from Pandoc Markdown to GFM, Pandoc-citeproc correctly processes the citations and outputs a reference list. However, each reference is formatted in Markdown yet enclosed within `<div>` tags. in GFM, this means the Markdown within the divs is not interpreted. Notice the asterisks in the example below:

```html
<div id="ref-hillier:2002society">
Hillier, Bill, e Vinicius Netto. 2002. "Society Seen Through the Prism of Space: Outline of a Theory of Society and Space". *Urban Design International* 7 (3): 181--203. &lt;https://doi.org/10.1057/palgrave.udi.9000077&gt;.
</div>
```

I understand the named `<div>` are necessary for the `link-citations` feature to work, but they break GFM output, so maybe a good compromise would be to not output the divs when `link-citations` is set to `false`. The above example was taken from [this source file](https://github.com/dmcpatrimonio/adaptive-construction/blob/master/pibic21-distrib.md) and [this output file](https://github.com/dmcpatrimonio/adaptive-construction/blob/master/docs/pibic21-distrib.md).

Versions: Pandoc 2.9.2.1 and Pandoc-citeproc 0.17

**Comment by jgm** [comment]
It will work in gfm if we have blank lines separating the div tags from the rest.
That should be fixed in the markdown writer.

**Comment by jgm** [comment]
Wait, I see that in your actual output you do get the blank lines.
The content inside should be interpreted as markdown on GitHub (at least, that's what the spec says).

**Comment by jgm** [comment]
And it *is* interpreted as markdown, as you can see from viewing the file on GitHub.
Closing.

**Comment by p3palazzo** [comment]
Thanks. I neglected to pay attention to the repository output. I suppose Jekyll is at fault in this case, since on the website it does not format within the divs.

**Comment by jgm** [comment]
Ah yes. I believe Jekyll may use a different markdown processor, kramdown, where GitHub uses a modified version of cmark for other content.

As a workaround you could try `-t gfm-raw_html`, which will remove all the div tags entirely (and thus break anchors to the bib entries).

Or maybe targeting another markdown flavor willl give better results with kramdown.
