### ISSUE TITLE
Org-File, JSON src, syntax coloring broken with non-ASCII characters in keys

### ISSUE THREAD

**Issue by phmarek** [jgm/pandoc#6406]
Given this input (`a.org`):

```
#+BEGIN_SRC json
{
  "gründung-rfc3339": "2020-02-02T02:00:00.000000+02:00",
  "city": null,
  "zip": "1030",
  "fbn": null
}
#+END_SRC

#+BEGIN_SRC json
{
  "gründung-rfc3339": "2020-02-02T02:00:00.000000+02:00",
  "gründung": 2020,
  "city": null,
  "zip": "1030",
  "fbn": null
}
#+END_SRC
```

and the command line `pandoc a.org -o a.pdf` the PDF shows the keys in the second example in red, starting from `city` - although the `ü` is the same as in the line above, where it doesn't break the highlightning.

Looks like the non-ASCII character needs a following non-alnum character within the key - changing `gründung` to `grü-ng` fixes the problem.

**Comment by jgm** [comment]
I can't reproduce this. What version of pandoc are you using?

**Comment by phmarek** [comment]
I've got debian testing/unstable, which is at 2.5-3+b1 currently.

An strace only showed `pdflatex` as being `execve`d, so I guess the highlighting gets done by pandoc?! (I didn't have `highlight` installed, and when it's installed, it doesn't get run and the output is the same)

[a.pdf](https://github.com/jgm/pandoc/files/4697787/a.pdf)

**Comment by phmarek** [comment]
Ack, sorry - with your current 2.9.1 it works for me too.

Didn't check how far the Debian package was behind.
