### ISSUE TITLE
Jira reader: support anchors and anchor links

### ISSUE THREAD

**Issue by W1M0R** [jgm/pandoc#6407]
[This Pandoc markdown](https://pandoc.org/try/?text=BLA-123%3A+All+about+bla+%7B%23BLA-123%7D%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0ARead+about+bla+%5Bhere%5D%0A%0A++%5Bhere%5D%3A+BLA-123&from=markdown&to=jira&standalone=0) produces the **correct** Jira markdown.

[This Pandoc markdown](https://pandoc.org/try/?text=BLA-123%3A+All+About+Bla+%7B%23BLA-123%7D%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0ARead+more+about+BLA-123+%5Bhere%5D(%23BLA-123).%0A&from=markdown&to=jira&standalone=0) produces the **correct** Jira markdown.

[This Jira markdown](https://pandoc.org/try/?text=h1.+%7Banchor%3ABLA-123%7DBLA-123%3A+All+about+bla%0ARead+about+bla+%5Bhere%7CBLA-123%5D&from=jira&to=markdown&standalone=0) produces the **incorrect** Pandoc markdown.

[This Jira markdown](https://pandoc.org/try/?text=h1.+%7Banchor%3ABLA-123%7DBLA-123%3A+All+About+Bla%0ARead+more+about+BLA-123+%5Bhere%7C%23BLA-123%5D.&from=jira&to=markdown&standalone=0) produces the **incorrect** Pandoc markdown.

@tarleb Do you agree regarding my observations on this?

**Comment by tarleb** [comment]
I tried with both "incorrect" versions, and neither produced a link for me in Jira. I don't think we can do any better than what we do now. Does it work for you, and which Jira version are you using?

**Comment by mb21** [comment]
According to [the documentation](https://confluence.atlassian.com/doc/anchors-139442.html), the anchor syntax is as follows (and can roughly confirm in jira v8.5.1:

```
{anchor:x}

[link|#x]
```

so this should produce the following HTML (modulo some paragraphs):

```
<a name="x"></a>

<a href="#x">link</a>
```

funnily, `foo{anchor:x}bar` produces:

```
<p>
  foo<a name="x"></a>bar
</p>
```

**Comment by tarleb** [comment]
Ah, right! We are not actually parsing links to anchors at all! Fixing it now. Thanks!

**Comment by tarleb** [comment]
Which, btw, means that the current cloud jira has a bug. Anchor links are only parsed in the preview, but fail to render in the actual ticket :thinking:

**Comment by mb21** [comment]
> We are not actually parsing links to anchors at all! Fixing it now.

thanks! and yes, we're not parsing anchors either :)


> Which, btw, means that the current cloud jira has a bug. Anchor links are only parsed in the preview, but fail to render in the actual ticket 

yeah, I observed something similar. I think the feature only really works in confluence, but they use the same parser, so the syntax is valid in jira tickets, but the anchors just get stripped on save... or something like that :)

**Comment by tarleb** [comment]
> we're not parsing anchors either

Could you give an example for that? It seems to work ok from what I can tell.

**Comment by mb21** [comment]
ah yes, anchors actually work.. (I tested on an older version..) nice!

**Comment by 0xDAFE** [comment]
@tarleb Sorry I don't want to hijack this Issue but I see it most fitting here:

We have a special case where the link text in Jira Markup contains square brackets, e.g.
`Please refer to [[3]|#appendix]`

Unfortunately, this is converted to the following HTML:
```html
<p>Please refer to [[3]|#appendix]</p>
```

instead of expected:
```html
<p>Please refer to <a href="#appendix">[3]</a></p>
```

**Comment by tarleb** [comment]
@0xDAFE please open a new issue for this, ideally with a fully reproducible example and description of the Jira version which you are using. I entered the above into Jira cloud, but got the same output as produced by pandoc.
