### ISSUE TITLE
revealjs output is broken

### ISSUE THREAD

**Issue by mrpg** [jgm/pandoc#6408]
**pandoc 2.9.2.1** on Arch Linux

```bash
git clone https://github.com/hakimel/reveal.js.git
wget https://pandoc.org/demo/SLIDES
pandoc -s --mathjax -i -t revealjs SLIDES -o example16d.html
```

produces output with the following error messages in Web Developer:

> SyntaxError: import declarations may only appear at top level of a module (reveal.js:1)
> ReferenceError: Reveal is not defined (example16d.html:75:7)

The example16d.html file itself looks like plain old HTML, with no CSS or JavaScript to speak of. I attach the entire folder to this issue.

I expected to get [this](https://pandoc.org/demo/example16d.html#/title-slide).

[pandoc-revealjs.tar.gz](https://github.com/jgm/pandoc/files/4697199/pandoc-revealjs.tar.gz)

**Comment by jgm** [comment]
The new version of reveal.js changes some paths and breaks pandoc's output.  We've made changes in the dev version to work with the latest reveal.js, so try a nightly and see if your issue is fixed already in the master branch.

**Comment by ale66** [comment]
Hello John thanks a lot for your work on Pandoc, we all owe to you!
I too report reveal not working anymore:

pandoc -t revealjs -s -o myslides.html myslides.md -V revealjs-url=https://revealjs.com

creates an output file myslides.html that is not interpreted at runtime.

**Comment by hakimel** [comment]
Hey all 👋 The website at https://revealjs.com was recently updated to reveal.js 4.0. To make it easier for existing pandoc users, I have uploaded a copy of the 3.9.2 release. If you swap out "revealjs.com" for "revealjs.com/demos/3.9.2" your exports should work again.

```
pandoc -t revealjs -s -o s.html s.md -V revealjs-url=https://revealjs.com/demos/3.9.2
```

**Comment by hakimel** [comment]
@jgm If you're adding support for reveal.js 4.0 in an upcoming pandoc version, it would be more future-proof to point to a versioned copy of reveal.js on unpkg. For example https://unpkg.com/reveal.js@^4/ should avoid any breaking changes.

**Comment by mrpg** [comment]
Hey @jgm and @hakimel, thanks a lot. While I can't currently check out the development version of Pandoc due to conflicting or unavailable dependencies on my machine, what @hakimel wrote fixes my issues for now. Again, thanks a million for all you do!

**Comment by jgm** [comment]
@hakimel thanks for the suggestion. I think I'll change that in the defaults.
