### ISSUE TITLE
Chocolatey distribution: what is the actual version?

### ISSUE THREAD

**Issue by ale66** [jgm/pandoc#6409]
Hello, I keep pandoc updated on my Windows 10 with Chocolatey.
But now:

```bash
C:\Users\ale>pandoc --version
pandoc 2.1.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.6
Default user data directory: C:\Users\ale\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
However, if I try to update:

```bash
C:\Users\ale>choco upgrade pandoc
Chocolatey v0.10.15
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

Upgrading the following packages:
pandoc
By upgrading you accept licenses for the packages.
pandoc v2.9.2.1 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

So, am I running the old 2.1.1 or am I running the [almost] latest  version 2.9.2.1?
Thanks!

**Comment by mb21** [comment]
The chocolatey package is not done by us... so you'll have to raise the issue there.. or use an alternative install method: https://pandoc.org/installing.html

**Comment by ale66** [comment]
Thanks, but the P.S. shows that you haven't really read my message.

On  [ https://pandoc.org/installing.html](https://pandoc.org/installing.html) is explicitly offered as as a channel for installing pandoc 

```
Alternatively, you can install pandoc using Chocolatey:

choco install pandoc
```
so it was easy to believe that you cared for how pandoc was distributed for Windows users no?

**Comment by mb21** [comment]
Yeah, we should probably put a link to the chocolatey package maintainer there..

**Comment by jgm** [comment]
Sorry, no. We are happy to provide information about third-party installers, but we're not obligated to support them ourselves (and it would be crazy to expect this).
