### ISSUE TITLE
LaTeX: ranges of SI units disappear during conversion

### ISSUE THREAD

**Issue by efharkin** [jgm/pandoc#6417]
# Description of bug and steps to reproduce 

As of the current master (7c6dbd37eb3e785f875e0030d723e422db72d453) ranges of SI units provided by `\SIRange{firstvalue}{secondvalue}{unit}` of siunitx are dropped during parsing of LaTeX files. This leads to funny conversions like the following:

Original LaTeX `test_sirange.tex`
```latex
Something important is happening \SIRange{100}{200}{\ms} after the event.
```

Expected output in markdown
```markdown
Something important is happening 100 ms to 200 ms after the event.
```

Actual output of `pandoc -so test_sirange.md test_sirange.tex`
```markdown
Something important is happening after the event.
```

## Why is this a bug?

The manual states that pandoc doesn't aim for perfect document conversion, and that in particular formatting details may not be preserved across formats. However, by dropping `\SIRange`, pandoc's output can become semantically different from the original LaTeX (ie phrases might not make sense or even take on a different meaning after conversion), so this isn't a formatting detail.

# Proposed fix

siunitx's `\SIRange` is highly configurable. Depending on the options used, `\SIRange{100}{200}{\ms}` might be rendered as 
- 100 ms to 200 ms
- 100 ms &ndash; 200 ms
- 100 &ndash; 200 ms
- etc

In the spirit of prioritizing semantics over formatting details, I think it would be good enough for pandoc to support only the first option. I've implemented this approach and will submit a PR shortly.

# Related issues and PRs

How pandoc should parse siunitx commands has also been discussed in issue https://github.com/jgm/pandoc/issues/3587. I'm opening a new issue because that issue (and the associated PR https://github.com/jgm/pandoc/pull/3823) have been focused on the `\num` command and are a bit stale.

**Comment by efharkin** [comment]
Implemented a fix here https://github.com/jgm/pandoc/pull/6418.

**Comment by tarleb** [comment]
Closing, as the fix was merged last year. (Thanks!)
