### ISSUE TITLE
Bug: numbersections not working with HTML (?, 2.9.2.1)

### ISSUE THREAD

**Issue by gabyx** [jgm/pandoc#6419]
The MWE
```markdown
---
title: Test
numbersections: true
secnumdepth: 4
---
# First

## Second
```

with
```shell
pandoc -t html -f markdown -s --self-contained  -o Test.html Test.md
```
does not produce section numbers:

```html
<h1 id="first">First</h1>
<h2 id="second">Second</h2>
```
**only adding `--number-sections` to the command works**. According to the doc setting the variable in the metadata should work.

**Comment by jgm** [comment]
> According to the doc

Can you say which part of the documentation made you think this, and why?

**Comment by gabyx** [comment]
Ohh, RTFM ;-)
A combination of:
- secnumdepth
    numbering depth for sections (with --number-sections option or numbersections variable)

- numbersections
non-null value if -N/--number-sections was specified

I think now its clear -> `numbersections` is in the `automatic sections` area
I think the `- secnumdepth` doc is a bit unclear.
So it means section-numbering can only be set in `--defaults` or over the argument `--N`...

**Comment by jgm** [comment]
This often confuses people.  In some output formats, setting `numbersections` is enough to cause section numbers, because in those formats the section numbers can be added by setting something in the template. But in most formats that's not enough; the numbers need to be generated by pandoc.

**Comment by Jmuccigr** [comment]
Yeah, I just got bit by this too, thinking ```numbersections: true``` in the yaml was sufficient for ePub. I'd be happy to suggest a PR for the docs, but I'm not sure exactly for which formats ```numbersections``` isn't sufficient.

PS As the docs get longer, it can be easy to find yourself searching for some bit of text and finding it in a subsection that you don't realize you're in. User error, of course, but still easy to fall prey to.
