### ISSUE TITLE
Thoughts on adding support for filter flags and options?

### ISSUE THREAD

**Issue by LaurentRDC** [jgm/pandoc#6420]
Hello,

I'm a big user of Pandoc filters to transform documents on their way to publising. Right now, Pandoc allows to specify which filter to run on the AST (with special handling for Lua and Python filters). However, there is no way to pass arguments to filters to modify their behavior.

For an example, consider filters like [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref), [pandoc-acronyms](https://gitlab.com/mirkoboehm/pandoc-acronyms), or [pandoc-plot](https://github.com/LaurentRDC/pandoc-plot). These filters support configuration via a file (e.g. YAML), but there is no way to elegantly pass this file as a flag. 

I've created a hack in pandoc-plot to pass a configuration file as a parameter using pandoc metadata:

```bash
pandoc --filter pandoc-plot -M plot-configuration=/path/to/file.yml -i input.md -o output.html
```

but this is rather tedious to maintain, and not easily extensible. 

*What if we allowed to specify options and flags to filter?* I'm thinking of something like GHC, where flags and options present between `+RTS` and `-RTS` are passed to the runtime system.

Here's an example of what I'm thinking of in action:

```bash
pandoc --filter filter.exe +FOPTS (...) -FOPTS -i input.md -o output.html
```

where the string between `+FOPTS` and `-FOPTS` is passed *directly* to the filter. It could be simple flags `--yes` or more complex things that look like `--foo bar:qux` or anything else really. Note that the notation above would extend naturally to many filters:

```bash
pandoc --filter filter1.exe +FOPTS (...) -FOPTS --filter filter2.exe +FOPTS (...) -FOPTS -i input.md -o output.html
```

What do you think? Provided that there is interest, I will put together a pull request to implement this.

**Comment by mb21** [comment]
FYI: there was discussion around that [on pandoc-discuss](https://groups.google.com/forum/#!topic/pandoc-discuss/LIAfgkZKUiE) a while ago...

**Comment by LaurentRDC** [comment]
Good point, I had only looked at issues and PRs. 

It has already been discussed [here](https://groups.google.com/d/msg/pandoc-discuss/LIAfgkZKUiE/_KfI3VI6EgAJ) and [here](https://groups.google.com/forum/#!msg/pandoc-discuss/Wb20JhBlQLE/72zsvBbEU4sJ), for example.
