### ISSUE TITLE
Sometimes block math leaves $$ in output and messes up HTML structure

### ISSUE THREAD

**Issue by dramforever** [jgm/pandoc#6421]
## What happens

Given this input as `test.md`:

```markdown
$$
\begin{aligned}

x
\end{aligned}
$$
```

`pandoc --mathjax -f markdown -t html test.md` gives:

```html
$$
<span class="math display">\[\begin{aligned}

x
\end{aligned}\]</span>
<p>$$</p>
```

As you can see there are two `$$` pieces that shouldn't be there, and the document structured is a bit messed up.

If there is no empty line:

```markdown
$$
\begin{aligned}
x
\end{aligned}
$$
```

Then the output is correct:

```html
<p><span class="math display">\[
\begin{aligned}
x
\end{aligned}
\]</span></p>
```

## What I expect to happen

The first HTML output should be like the second one, with no `$$` showing up and with correct structure.

## Version

2.9.2.1, tested on [pandoc.org/try (link contains input)](https://pandoc.org/try/?text=%24%24%0A%5Cbegin%7Baligned%7D%0A%0Ax%0A%5Cend%7Baligned%7D%0A%24%24&from=markdown&to=html5&standalone=0)

**Comment by jgm** [comment]
You can see how pandoc is parsing this using `pandoc -t native`:
```
% pandoc -t native
$$
\begin{aligned}

x
\end{aligned}
$$
^D
[Plain [Str "$$"]
,RawBlock (Format "tex") "\\begin{aligned}\n\nx\n\\end{aligned}"
,Para [Str "$$"]]
```
As you can see, this *isn't* being parsed as display math (apparently because of the blank line). So this is really a markdown reader issue.

**Comment by jgm** [comment]
This is why: we explicitly rule out blank lines in display math. See
```haskell
mathDisplayWith :: Stream s m Char => Text -> Text -> ParserT s st m Text
mathDisplayWith op cl = try $ fmap T.pack $ do
  textStr op
  many1Till (noneOf "\n" <|> (newline <* notFollowedBy' blankline)) (try $ textStr cl)
```
I assume there's a reason for this -- probably to avoid parsing the whole document for an end `$$` if someone puts `$$` in for some other reason.

**Comment by dramforever** [comment]
Thank you. Now that I know exactly why pandoc has this behavior, I guess I can adjust my habits to not put blank lines in block math for now and not put blank lines.

I'm neutral on whether to change this or not.

**Comment by jgm** [comment]
I guess I'll leave this as it is, on the assumption that there was a good reason for writing it that way originally...
