### ISSUE TITLE
Compatibility problem with the calc library of TikZ

### ISSUE THREAD

**Issue by nasmi3** [jgm/pandoc#6423]
Hello,

I am currently working on a customizable cover page for a latex output from markdown.

I used Latex to develop the design aspect and I wanted to include that in my template file to get access to the power of custom fields offered by Pandoc.

However, Pandoc seems to be unable to treat properly the syntax used by TikZ

**Output from Pandoc :**

```sh
"template" (line 44, column 23):
unexpected "("
expecting letter
```

The problem is located in this part of the code : `($(current page.north west)+(0,+1)+(0,-2*\i)$)` where Pandoc seems to expect something different.

If I run the same file with `(current page.north west)` instead it runs without any problem.

**Command :** ` pandoc --from=markdown+abbreviations --output=output/report.tex --standalone -t latex --pdf-engine=xelatex --number-sections --filter pandoc-crossref --filter pandoc-citeproc --template=template/template.tex --top-level-division=chapter title.txt part1.md`

**Version :** pandoc 2.7.3 - Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1

Here is an extract of the `template.tex` file

```Tex
% !TEX program = xelatex

\documentclass[11pt,fleqn]{book}

\usepackage{graphicx}
\usepackage{tikz}
\usetikzlibrary{calc}

$if(title-en)$
	$if(author)$
\hypersetup{pdftitle={$title-en$},pdfauthor={$author$}}
	$endif$
$endif$

$if(bibliography)$
\addbibresource{$bibliography$} % BibTeX bibliography file
$endif$

\begin{document}

%----------------------------------------------------------------------------------------
%	TITLE PAGE
%----------------------------------------------------------------------------------------
\begin{titlepage}
  \pagestyle{empty}
  
  \begingroup
  
      \begin{tikzpicture}[overlay,remember picture]
      
      \fill[lightgray!5] (current page.south west) rectangle (current page.north east);
  
      % Horizontal lines
      \foreach \i in {1,2,...,15}{
        \draw[ocre] ($(current page.north west)+(0,+1)+(0,-2*\i)$) -- ($ (current page.north east)+(0,+1)+(0,-2*\i) $);} 
      \end{tikzpicture}
  
  \endgroup
 
\part{Part 1}

...

\end{document}
```

Thank you for your time !

**Comment by mcrucifix** [comment]
use $$ instead of $ (cf. https://github.com/jgm/pandoc/issues/970#issuecomment-23877197 )
