### ISSUE TITLE
bug: asciidoc export: literal "]" interrupts footnote.

### ISSUE THREAD

**Issue by Will47** [jgm/pandoc#6424]
If a footnote text includes right brackets - ] - the first one will match with the "footnote:[" markup of asciidoc, provoking an early interruption of the footnote, and pushing back the end of the footnote text in the main text.

Example, using [test.docx](https://github.com/jgm/pandoc/files/4729610/test.docx), and running:
`pandoc -f docx -t asciidoc test.docx`
produces the following output:
`textfootnote:[[…] footnote]`

Escaping the inner right brackets should fix the issue (cf. https://github.com/asciidoctor/asciidoctor/issues/2495#issuecomment-380270022), producing this output instead:
`textfootnote:[[…\] footnote]`

I used Pandoc v2.5 for the test, but it should still apply to the latest version from my understanding of the AsciiDoc writer code.

**Comment by jgm** [comment]
The big question is whether we can get away with just always escaping literal bracket characters.

**Comment by Will47** [comment]
Escaping ] is only required inside macros, cf. https://asciidoc.org/userguide.html#_macros:
> - `<attrlist>` is a list of attributes enclosed in square brackets.
> - ] characters inside attribute lists must be escaped with a backslash.

Outside of macros, ] has no particular meaning and `\]` will be rendered as ´\]`. So if that's what you mean by always, I'm afraid you won't get away with that.

AsciiDoctor seems a bit more generic but aligned nevertheless on AsciiDoc on this particular issue, cf. https://asciidoctor.org/docs/user-manual/#attribute-list-substitutions:
>If the attribute value contains the same quote character being used to enclose the value, escape the quote character in the value by prefixing it with a backslash (e.g., title="\\"Dark Horse\\" is a song by George Harrison").
