### ISSUE TITLE
A specific file always fails.

### ISSUE THREAD

**Issue by lalitaalaalitah** [jgm/pandoc#6427]
The specific file which I've attached here is failing every time.
I've tried to copy text and create a separate file and then test again. It still fails.
I'm sure that there is some part of text which makes pandoc cripple.
BTW, I was trying to convert it to tex.
[x.txt](https://github.com/jgm/pandoc/files/4734923/x.txt)

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by lalitaalaalitah** [comment]
Thanks for replying.
- pandoc version is pandoc 2.9.2.1
- The exact command used was ```pandoc x.txt -o x.tex'''
- No extra input was provided.
- no output was produced.
- I expected a file 'x.tex' in the same folder as source file `t.txt'.
Actually, I've already attached the file creating problem in original post. Please, check the link x.txt which is at bottom of the original post.

The command was applied for a bunch of files in a folder. All files were successfully converted, apart from this. I tried to convert this separately. It still fails.

**Comment by jgm** [comment]
I can confirm that this file takes a long time to convert on my (fairly fast) computer, though it does eventually finish.
So there is some pathological parsing behavior here.
It relates to smart quote parsing; if you disable that `-f markdown-smart` it should finish quickly.

**Comment by jgm** [comment]
Or use `-f gfm` or `-f commonmark`.

**Comment by lalitaalaalitah** [comment]
Thanks, it resolved the problem.
I've updated my workflow accordingly.
