### ISSUE TITLE
Export from .md to .rtf

### ISSUE THREAD

**Issue by pharaoh23** [jgm/pandoc#6428]
Using Pandoc 2.9.2.1, I simply would like to export a file from markdown to .rtf (rich text format).
The export contains this text: 

# Title

This is a file I am trying to use.

Hopefully.

I use the following command: 

pandoc -f markdown test.md -t rtf -o test.rtf

The result is as follows in the .rtf file:

{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs36 Title\par}
{\pard \ql \f0 \sa180 \li0 \fi0 This is a file I am trying to use.\par}
{\pard \ql \f0 \sa180 \li0 \fi0 Hopefully.\par}

**Comment by mb21** [comment]
you're missing the `-s` option.

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
