### ISSUE TITLE
notebook reader: support more embedded media types

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#6430]
Jupyter notebooks can contain embedded media in output cells, described by MIME types. When converted to Markdown, for some like `image/png` this results in something like `![](fae4f33eeeb69713a11e13a9c5cb43e3f12668ec.png)` to be generated. Actually creating the referenced files requires the `--extract-media` option.

However, others like `image/svg+xml` or `application/pdf` are simply ignored.

To make the notebook reader more useful, I propose that support for embedded media is extended. Supporting more than pngs is important because they are not well suited for conversion targets like pdf.

**Comment by allefeld** [comment]
I just found `--ipynb-output=all` and thought it might solve the problem, since the description says it "means that all of the data formats included in the original are preserved", but it does not preserve svgs or pdfs.

**Comment by jgm** [comment]
Looking at the code, it seems to me that anything with an `image/` prefix in its mime type should turn into an image.  Are you sure `image/svg+xml` doesn't work?  We could fairly easily change the code to treat `application/pdf` like the other images.

**Comment by jgm** [comment]
This is around line 160 ff in T.P.Readers.Ipynb.hs.

**Comment by allefeld** [comment]
I just tested it again for SVG. This is what the notebook looks like in VS Code:
![Screenshot_20200608_204336](https://user-images.githubusercontent.com/1738353/84073453-bb59cf80-a9c8-11ea-8ca7-36f4d0d42211.png)

The saved notebook file looks like this:
<details>
  <summary>Click to expand</summary>
<pre>
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plotly graphics library\n",
    "import plotly.graph_objects as go"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# configure Plotly to create SVG graphics\n",
    "import plotly.io as pio\n",
    "pio.renderers.default = 'svg'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "image/svg+xml": "<i>removed SVG code</i>"
     },
     "metadata": {}
    }
   ],
   "source": [
    "# create plot\n",
    "fig = go.Figure()\n",
    "fig.add_bar(y=[2, 3, 1])\n",
    "fig.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2-final"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python38264bitstdcondafbc71e15ee1847f1ad9c90ba15b2ed53",
   "display_name": "Python 3.8.2 64-bit ('std': conda)"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
</pre></details>

It contains an output cell of type `image/svg+xml`. But when I run

    pandoc pandoc-test.ipynb --extract-media=. -t markdown --ipynb-output=all -o pandoc-test.md

no SVG file is created, and the Markdown contains an empty output cell:

```
::: {.output .display_data}
:::
:::
```

Here is the full notebook file:
[pandoc-test.ipynb.gz](https://github.com/jgm/pandoc/files/4748230/pandoc-test.ipynb.gz)

pandoc 2.9.1

**Comment by allefeld** [comment]
And here the same for PDF, with the same results:
[pandoc-test.ipynb.gz](https://github.com/jgm/pandoc/files/4748258/pandoc-test.ipynb.gz)

**Comment by jgm** [comment]
I see, it's because it's textual data, not binary.
Fix should be easy.

**Comment by allefeld** [comment]
Great, thanks for the rapid fix!

Would it be much harder to give `application/pdf` the same treatment?
