### ISSUE TITLE
Markdown to HTML latex bug

### ISSUE THREAD

**Issue by joaogui1** [jgm/pandoc#6433]
Reporting a bug?
Please include your pandoc version and an example that allows us
to reproduce the problem (complete input, exact command line
used, expected and actual output).  The smaller the example, the
better.

When I try to convert from markdown to latex i get the following error: 
```bash
[WARNING] Could not convert TeX math '
  \begin{aligned}
  c_t &= \sum_{i=1}^n \alpha_{i}^th_i & \text{: Context vector for output }y_t \\
  \alpha^t &= align(y_i, x_i) & \text{: How well two words }y_t\text{ and }x_i\text{ are aligned.} \\
  &= \frac{\exp(score(s_{t-1}, h_i))}{\sum_j \exp(score(s_{t-1}, h_j)} & \text{: Softmax of some predefined alignment score.}
  \end{aligned}
  ', rendering as TeX
```
But it renders normally in markdown, any idea how to fix this problem?
My version of pandoc is 2.5

**Comment by mb21** [comment]
Can you try with the newest pandoc version and narrow it down to a minimal example?

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by jgm** [comment]
It's important to give the command line you use, as requested in the template. But I assume you didn't use `--mathjax`.  See the section of the manual on math output  in HTML; you'll see that there are many options.  The default option is 'fake it with unicode', and pandoc can't do this when the math gets too complex.  If you have any complex math, you need to use mathjax or katex.

**Comment by jgm** [comment]
Sorry:  I misread your message.  You are converting to LaTeX, not HTML.

In that case, I think the solution is simply to upgrade to a more recent version.
The most recent release has not trouble with this input.

**Comment by joaogui1** [comment]
I am converting to HTML, but I found a workaround that doesn't use pandoc
