### ISSUE TITLE
<simplesect> titles in Docbook are dropped

### ISSUE THREAD

**Issue by mboes** [jgm/pandoc#6434]
Consider the Docbook example in [its documentation](https://tdg.docbook.org/tdg/4.5/simplesect.html):

```xml
<!DOCTYPE sect1 PUBLIC "-//OASIS//DTD DocBook XML V4.1.2//EN"
          "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd">
<sect1><title>Additional Coding</title>

<para>
Support for the additional features requested will be provided.
</para>

<simplesect><title>Estimated Time</title>

<para>
2 to 3 weeks.
</para>

</simplesect>
</sect1>
```

The output to Markdown omits the `<simplect>` title:

```
$ pandoc -f docbook -t markdown simplesect.xml 
Additional Coding
=================

Support for the additional features requested will be provided.

2 to 3 weeks.
```

**Comment by mb21** [comment]
jep, as can be seen [in the pandoc source](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/DocBook.hs#L422), this is not implemented yet. we should simply pass the tag contents through I guess...
