### ISSUE TITLE
Create synopsis like git in man pages

### ISSUE THREAD

**Issue by albfan** [jgm/pandoc#6440]
```
$ pandoc --version
pandoc 2.9.2.1
```

man pages for git use some indentation on synopsis:

```
SYNOPSIS
       git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|-P|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>]
           <command> [<args>]
```

This is write in roff as:

```
.nf
\fIgit\fR [\-\-version] [\-\-help] [\-C <path>] [\-c <name>=<value>]
    [\-\-exec\-path[=<path>]] [\-\-html\-path] [\-\-man\-path] [\-\-info\-path]
    [\-p|\-\-paginate|\-P|\-\-no\-pager] [\-\-no\-replace\-objects] [\-\-bare]
    [\-\-git\-dir=<path>] [\-\-work\-tree=<path>] [\-\-namespace=<name>]
    [\-\-super\-prefix=<path>]
    <command> [<args>]
.fi
```
`.nf` `.fi` can be replicated with ```

    ```
    git [--version] [--help] [-C <path>] [-c <name>=<value>]
        [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
        [-p|--paginate|-P|--no-pager] [--no-replace-objects] [--bare]
        [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
        [--super-prefix=<path>]
        <command> [<args>]
    ```

but seems there's no way to replicate bold or underscore respecting whitespace. If you try to include the bold on underscore, they are escaped

source:

```
\f[I]git\f[R]
```

output:
```
\[rs]f[I]git\[rs]f[R]
```

instead of being put raw. I found this is done on: 

https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/RoffChar.hs#L37
https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Roff.hs#L74

is there a way to put bold or underscore keeping space indentation and line breaks?

**Comment by mb21** [comment]
you're converting markdown to roff man using `pandoc -t man`, or..?

**Comment by jgm** [comment]
You can do this using line block syntax (see the manual).

E.g.
```
| `git [--version]`
|     `[--exec-path=`*`path`*`]`
```

**Comment by albfan** [comment]
```
| **git** `[--version]`
|     `[--exec-path=`*`path`*`]`
```

![Captura de pantalla de 2020-06-08 09-42-57](https://user-images.githubusercontent.com/220968/84004844-815ae000-a96c-11ea-895a-13cd8f51dfbd.png)

Amazing!
