### ISSUE TITLE
pandoc does not pick up title from --epub-metadata

### ISSUE THREAD

**Issue by captn3m0** [jgm/pandoc#6447]
This results in a warning, but any attempts to fix this warning will result in more issues, because you'll end up with double title tags instead of single. And because of #6445, I can't add a refinement to make any of the titles primary either.

Script to reproduce:

```sh
#!/bin/bash

pandoc --version

cat <<__HTML__ > bug3.html
<html>
<body>
<h1>Chapter 1</h1>
<p>Contents</p>
</body>
</html>
__HTML__

cat <<__METADATA__ > bug3.xml
<dc:title>Ebook Title Goes Here</dc:title>
__METADATA__

pandoc --from=html \
    --output="bug3.epub" \
    --epub-metadata=bug3.xml \
    bug3.html

unzip -c bug3.epub EPUB/content.opf

unzip -c bug3.epub EPUB/nav.xhtml
```

Output:

```
pandoc 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /home/nemo/.local/share/pandoc or /home/nemo/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'bug3' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
Archive:  bug3.epub
  inflating: EPUB/content.opf
<?xml version="1.0" encoding="UTF-8"?>
<package version="3.0" xmlns="http://www.idpf.org/2007/opf" unique-identifier="epub-id-1" prefix="ibooks: http://vocabulary.itunes.apple.com/rdf/ibooks/vocabulary-extensions-1.0/">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:identifier id="epub-id-1">urn:uuid:b71aa344-b049-4ecd-ad26-11958c863cf1</dc:identifier>
    <dc:title id="epub-title-1">Ebook Title Goes Here</dc:title>
    <dc:date id="epub-date">2020-06-09T11:18:33Z</dc:date>
    <dc:language>C</dc:language>
    <meta property="dcterms:modified">2020-06-09T11:18:33Z</meta>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml" />
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav" />
    <item id="stylesheet1" href="styles/stylesheet1.css" media-type="text/css" />
    <item id="title_page_xhtml" href="text/title_page.xhtml" media-type="application/xhtml+xml" />
    <item id="ch001_xhtml" href="text/ch001.xhtml" media-type="application/xhtml+xml" />
  </manifest>
  <spine toc="ncx">
    <itemref idref="title_page_xhtml" linear="no" />
    <itemref idref="ch001_xhtml" />
  </spine>
  <guide>
    <reference type="toc" title="Ebook Title Goes Here" href="nav.xhtml" />
  </guide>
</package>


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="C">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <title>bug3</title>
  <link rel="stylesheet" type="text/css" href="styles/stylesheet1.css" />
</head>
<body>
<nav epub:type="toc" id="toc"><h1 id="toc-title">Ebook Title Goes Here</h1><ol class="toc"><li id="toc-li-1"><a href="text/ch001.xhtml#chapter-1">Chapter 1</a></li></ol></nav>
</body>
</html>
```

The title in the EPUB is set correctly: `<dc:title id="epub-title-1">Ebook Title Goes Here</dc:title>`, so the warning is partially erroneous:

```
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'bug3' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
```

The title in the `nav.xhtml` is set incorrectly though:

`<title>bug3</title>`

**Comment by tarleb** [comment]
If I understand correctly, then the request is to let pandoc parse the `--epub-metadata` file instead of just inserting it verbatim?

**Comment by captn3m0** [comment]
Kinda. I'm not aware if there are other similar special tags (language perhaps?)

The end-user shouldn't be expected to fill in the title twice - they've provided it as part of the metadata file, it should get applied everywhere (and not warn when it has been provided)

**Comment by captn3m0** [comment]
This is the output I'd expected:

```
pandoc 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /home/nemo/.local/share/pandoc or /home/nemo/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
Archive:  bug3.epub
  inflating: EPUB/content.opf
<?xml version="1.0" encoding="UTF-8"?>
<package version="3.0" xmlns="http://www.idpf.org/2007/opf" unique-identifier="epub-id-1" prefix="ibooks: http://vocabulary.itunes.apple.com/rdf/ibooks/vocabulary-extensions-1.0/">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:identifier id="epub-id-1">urn:uuid:b71aa344-b049-4ecd-ad26-11958c863cf1</dc:identifier>
    <dc:title id="epub-title-1">Ebook Title Goes Here</dc:title>
    <dc:date id="epub-date">2020-06-09T11:18:33Z</dc:date>
    <dc:language>C</dc:language>
    <meta property="dcterms:modified">2020-06-09T11:18:33Z</meta>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml" />
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav" />
    <item id="stylesheet1" href="styles/stylesheet1.css" media-type="text/css" />
    <item id="title_page_xhtml" href="text/title_page.xhtml" media-type="application/xhtml+xml" />
    <item id="ch001_xhtml" href="text/ch001.xhtml" media-type="application/xhtml+xml" />
  </manifest>
  <spine toc="ncx">
    <itemref idref="title_page_xhtml" linear="no" />
    <itemref idref="ch001_xhtml" />
  </spine>
  <guide>
    <reference type="toc" title="Ebook Title Goes Here" href="nav.xhtml" />
  </guide>
</package>


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="C">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <title>Ebook Title Goes Here</title>
  <link rel="stylesheet" type="text/css" href="styles/stylesheet1.css" />
</head>
<body>
<nav epub:type="toc" id="toc"><h1 id="toc-title">Ebook Title Goes Here</h1><ol class="toc"><li id="toc-li-1"><a href="text/ch001.xhtml#chapter-1">Chapter 1</a></li></ol></nav>
</body>
</html>
```

**Comment by tarleb** [comment]
Pandoc's expectation is that the title is given in YAML metadata or via the command line. When entered that way, there is no need to enter the same information twice.

But I think the request to allow specifying it in the epub metadata is sensible.

Maybe a different issue, but I also note that giving the title in YAML metadata *and* the epub metadata file leads to duplicate `<dc:title>` entries, which contradicts the behavior described in the manual  (emphasis mine):

>  By default, pandoc will include the following metadata elements:
>  `<dc:title>` (from the document title), `<dc:creator>` (from the
>   document authors), `<dc:date>` (from the document date, which should
>  be in [ISO 8601 format]), `<dc:language>` (from the `lang`
>  variable, or, if is not set, the locale), and `<dc:identifier id="BookId">`
> (a randomly generated UUID). **Any of these may be
>  overridden by elements in the metadata file.**

**Comment by tarleb** [comment]
Ah, I see that you already opened an issue for that last point: #6446

**Comment by Darthagnon** [comment]
I'm seeing the same issue: I'm trying to build an EPUB from a bunch of markdown files, and I'm using the following command:
```
pandoc -o "The Gathering Storm.epub" --epub-metadata=metadata-storm.yaml 00-titlepage.md 01-chapter-one.md 02-chapter-two.md 03-chapter-three.md 04-chapter-four.md 05-chapter-five.md 06-chapter-six.md 07-chapter-seven.md 08-chapter-eight.md 09-chapter-nine.md 10-chapter-ten.md 11-chapter-eleven.md 12-chapter-12.md 13-chapter-thirteen.md 14-chapter-fourteen.md 15-chapter-fifteen.md 16-chapter-sixteen.md 17-chapter-seventeen.md 18-chapter-eighteen.md 19-chapter-nineteen.md 20-chapter-twenty.md 21-end.md
```

`metadata-storm.yaml` contains:
```
---
title: 
- type: main
  text="The Gathering Storm"
creator:
- role: author
  text: Django Wexler
- role: editor
  text: Darthagnon
date: 2023-05-13
publisher: Wizards of the Coast
rights:  [Wizards of the Coast's Fan Content Policy (15 Nov 2017)](https://company.wizards.com/en/legal/fancontentpolicy): This ebook is unofficial Fan Content permitted under the Fan Content Policy. Not approved/endorsed by Wizards. Portions of the materials used are property of Wizards of the Coast. Copyright © 2019  Penguin Random House LLC, 1745 Broadway, New York, NY 10019. All rights reserved.  TM and © 2019 Wizards of the Coast LLC
language: en-US
output:
  html:
   include-in-header:
      - foo.css
      - bar.js
no-check-certificate: true
reference-links: true
reference-location: section
number-section: true
epub-cover-image: cover.jpg
epub-embed-font: Beleren.ttf
---
```

All of this metadata is ignored, and the build log says:
```
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to '00-titlepage' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
```

**Comment by jgm** [comment]
`--epub-metadata` expects an XML metadata file (see the manual).  I would have expected an error to have been raised in this case, though, so it's a bug if one was not.

**Comment by jgm** [comment]
In your case you should just use `--metadata-file` with this yaml.

**Comment by Darthagnon** [comment]
Thank you so much! Guess I missed that while skimming the manual. I'm guessing there's a technical reason there isn't one command that accepts and parses both XML and YAML. Thank you for making Pandoc, it is very useful!

**Comment by git001** [comment]
@Darthagnon can this issue be closed?

**Comment by Darthagnon** [comment]
> @Darthagnon can this issue be closed?

It would be nice if `--metadata-file` and `--epub-metadata` commands were merged into one command that accepts all possible formats of Pandoc metadata file. Would that be an option?

**Comment by jgm** [comment]
No, these files have different formats and it's best to be explicit, I think.
Also `--metadata-file` is not epub specific.

**Comment by patrickfav** [comment]
Just to chime in here because I tryed for an hour now and couldn't figure out why `--epub-metadata` didnt work with the yaml. In the documentation it is presented as:

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/57e178e1-7bfb-4c28-8380-f576674ec589" />

So hinting to `--epub-metadata` with a direct example of the yaml file. You would need to scroll down and see that this actually expects an XML. Also the the paramter names a unclear, why not call it `--epub-metadata-xml`?

Nevertheless, thank you for the great tool!

**Comment by tarleb** [comment]
@patrickfav Thanks for chiming in. A PR to improve this would be most welcome.

**Comment by jgm** [comment]
Personally I don't see any unclarity in the docs as they stand.  If you follow the link to `--epub-metadata`, you'll see the format this option expects. And the word "but" clearly indicates that YAML metadata blocks are an alternative, not the format that `--epub-metadata` expects.

However, a simple way to avoid the misunderstanding would be to add:

> EPUB metada may be specified using the `--epub-metadata` option, **which takes an XML file with Dublin Core elements as its argument.**  But if the source document is Markdown, it is better...

**Comment by patrickfav** [comment]
@jgm I'm not saying anything stated in that part of the doc is incorrect, just that it is (IMHO) easy to misunderstand. I agree with your change, but I would also hint to the YAML being a different parameter

> EPUB metada may be specified using the [`--epub-metadata`](https://pandoc.org/MANUAL.html#option--epub-metadata) option, which takes an XML file with Dublin Core elements as its argument. But if the source document is Markdown, it is better to use [`--metadata-file` with a YAML metadata block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block). Here is an example such a metadata block with EPUB metadata:

I can create a PR if you like, but not sure where the source of truth for the doc is, is it MANUALS.txt?

**Comment by jgm** [comment]
Well, the metadata can simply be embedded in the markdown file itself. You don't need to use `--metadata-file`.  I can make the change.

**Comment by jgm** [comment]
See commit ef822ef8e7a885a3b13e8e736912755f26782a42 and let me know if that looks right.

**Comment by patrickfav** [comment]
Looks good, thank you @jgm!
