### ISSUE TITLE
latex output: description lists and `lstinline'

### ISSUE THREAD

**Issue by ft** [jgm/pandoc#645]
When writing description lists in markdown such as this:

```
`--foo` **BAR**

:   Enables the foo feature with **BAR** as its flavour.
```

...and you use the latex (or pdf) writer backends with the `--listings` option,  you'll get `\lstlinline` within `\item[...]` which doesn't work without additional workarounds (i.e. the part within `\item[...]` disappears or sometimes appears in an entirely different place).

Hence, I'd propose to use `\texttt{...}` instead of `\lstinline` within `\item[...]` even if the `--listings` option is used.

To reproduce the issue, use the document body from above and call pandoc like this:

```
% pandoc --listings -o foo.pdf foo.mdwn
```

This is with pandoc 1.10 (actually a build from git, that is a week or two old) and pdfTeX 3.1415926-2.4-1.40.13 (TeX Live 2012/Debian).

**Comment by jwr** [comment]
I'm not sure if this issue is understood. I think it deserves more attention than it currently gets. To rephrase: currently Pandoc produces corrupted output if `--listings` is used. Not just in code listings, in document text.

`\lstinline` should not be used, because it breaks with UTF-8.

**Comment by jgm** [comment]
@jwr If, as you say, the whole listings package is limited to 8-bit data, then I don't see how avoiding `\lstinline` in favor of `\texttt` would really help -- we'd still have problems with code blocks.  Why shouldn't we just add the following advice to the README:  If your code is non-ASCII, don't use `--listings`?

**Comment by jwr** [comment]
@jgm well, that's throwing out the baby with the bathwater. If you have UTF-8 in your text, you likely write in a language other than English, and yet most (if not all) code gets written in English. That is a pattern I see in all companies I know of.

Hence, `--listings` is still very useful, as it produces beautifully formatted code listings. It's just the forced use of `\lstinline` that is the problem.

**Comment by jgm** [comment]
+++ Jan Rychter [May 19 15 09:55 ]:
>@jgm well, that's throwing out the baby with the bathwater. If you have UTF-8 in your text, you likely write in a language other than English, and yet most (if not all) code gets written in English. That is a pattern I see in all companies I know of.
>
>Hence, `--listings` is still very useful, as it produces beautifully formatted code listings. It's just the forced use of `\lstinline` that is the problem.

So, then, your objection to `\lstinline` has nothing to do with UTF-8?
(Because that objection extends to code blocks as well.)
Is it just about code size and styling?

**Comment by jwr** [comment]
@jgm My objection to `\lstinline` is exactly (and only) because of UTF-8.

I also point out a frequent use case (which happens to be my case, too): documentation with UTF-8 and code without UTF-8. My code listings only contain ASCII, as they are in English, but the rest of my document is in Polish. So I *do* want `--listings`, just without the forced use of `\lstinline`.

You seem to think that if one uses UTF-8 in documents, one also has code blocks with UTF-8, which is actually not necessarily the case.

**Comment by nkalvi** [comment]
@jwr I'm familiar neither Polish nor LaTex, but just trying to understand the issue - so please pardon me if I'm completely off.

I used your example, `--images-directory [ścieżka]`, which is output by Pandoc as `--images-directory ś[żcieka]` with `pandoc --listings --latex-engine=xelatex`.

After seeing a similar issue here 
http://stackoverflow.com/questions/1116266/listings-in-latex-with-utf-8-or-at-least-german-umlauts
I tried the one of the suggestions (by GDR for Polish language) there and seems to work:

foo.txt
```latex
\lstset{literate={ą}{{\k{a}}}1 {ł}{{\l{}}}1 {ń}{{\'n}}1 {ę}{{\k{e}}}1 {ś}{{\'s}}1 {ż}{{\.z}}1 {ó}{{\'o}}1 {ź}{{\'z}}1 {Ą}{{\k{A}}}1 {Ł}{{\L{}}}1 {Ń}{{\'N}}1 {Ę}{{\k{E}}}1 {Ś}{{\'S}}1 {Ż}{{\.Z}}1 {Ó}{{\'O}}1 {Ź}{{\'Z}}1 }

`--images-directory [ścieżka]`
```

Output with `pandoc --listings  -o foo.pdf foo.txt`:
![screen shot 2015-05-19 at 2 10 48 pm](https://cloud.githubusercontent.com/assets/2199312/7710299/e99b1a14-fe30-11e4-8446-cd93939e2cba.png)


Would something similar be a viable solution for you?

**Comment by jgm** [comment]
I don't ever use `--listings`, so the proposed change -- using `\texttt` instead of `\lstinline` -- wouldn't affect me.  But I'm reluctant to make the change, since some users who do use `--listings` may want `\lstinline`.  @jwr I recommend you ask on pandoc-discuss whether anyone would object if `--listings` didn't use `\lstinline` for inline code.  If nobody objects, I'd be willing to make the change.  But it does still seem to me that it's going to be a fairly rare case where you have non-ASCII in code spans, but not in code blocks.

**Comment by jgm** [comment]
I don't think this discussion ever occurred, and I'm not going to make the change without it, so closing for now.

**Comment by jgm** [comment]
Reopening, not for the unicode issue, but for the disappearing stuff issue.
We can fix that by using texttt if in an `\item[...]` context.

**Comment by anishmittal2020** [comment]
I concur that this modification would be useful as can be seen here:

```markdown
# Temp.md
Edit Configuration: `sudo nano /etc/default/grub`
```

```bash
pandoc Temp.md -s -o Temp.tex
pandoc Temp.md -o Temp.pdf
pandoc Temp.md --listings -s -o TempListing.tex
pandoc Temp.md --listings -o TempListing.pdf
```

**Comment by anishmittal2020** [comment]
@jgm Please support `\texttt{...}` instead of `\lstinline` as no one in the `pandoc-discuss` objected.

**Comment by jgm** [comment]
Anish Mittal <notifications@github.com> writes:

> @jgm Please support `\texttt{...}` instead of `\lstinline` as no one in the `pandoc-discuss` objected.

I'm not sure your message was clear enough for people
to know what the proposal was.

Also, I would like to hear more about your
motivations.  Is it because you have non-ascii
characters in your inline code spans, but not
in code blocks?  As I point out above, this seems
quite an unusual case to optimize for.

**Comment by Agarwal-Nikhil** [comment]
I don't have a strong motivation. But we can observe (in the following) that in the `--listings` case the monospace fonts are not getting rendered.

```markdown
# Temp.md
Edit Configuration: `sudo nano /etc/default/grub`
```

```bash
pandoc Temp.md -o Temp.pdf
pandoc Temp.md --listings -o TempListing.pdf
```

**Comment by jgm** [comment]
LaTeX listings doesn't use monospace fonts generally,
unless you tell it to.  Why are you using --listings
in the first place?  Just don't use it, and you'll
get a monospaced font.

**Comment by mbanck** [comment]
So I decided to use a smaller font for codeblocks in order to get more of them on a page.

Now as soon as I use `--listings`, all my inline `texttt` snippets are suddently rendered in a smaller font. Is there at least a way to override/work around this, if it is not considered a bug?

**Comment by DanielGibson** [comment]
When I convert Markdown to Tex or PDF, I'd like it to use `\texttt` for <code>\`inline code\`</code> and listings for full code blocks (enclosed in ` ``` `).
