### ISSUE TITLE
pandoc -> revealjs improper use of background-image variable

### ISSUE THREAD

**Issue by utdrmac** [jgm/pandoc#6450]
pandoc 2.9.2.1 (as installed with mac homebrew)

Attempting to use a plain background image with the variable:
`-V background-image:myimage.jpg`

For whatever reason, pandoc is setting the above parameter to the parallaxBackgroundImage image feature. This is not intended for static images but for "moving" images. There exists a separate variable `-V parallaxBackgroundImage` which is specific to using parallax images.

Please fix the revealjs template code to properly assign `-V background-image` to the correct revealjs configuration parameter.

```
# pandoc -D revealjs
...
$if(parallaxBackgroundImage)$
        // Parallax background image
        parallaxBackgroundImage: '$parallaxBackgroundImage$', // e.g. "'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'"
$else$
$if(background-image)$
       // Parallax background image
       parallaxBackgroundImage: '$background-image$', // e.g. "'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'"
$endif$
```

**Comment by mb21** [comment]
might already be fixed in the [nightly-build](https://github.com/jgm/pandoc/actions)...

**Comment by jgm** [comment]
I tried changing this locally, but then background-image yielded no background image for me, whereas I did get an image with parallaxBackgroundImage.  Are you sure it actually works? There may be a reason it's the way it is.
Pinging @Jmuccigr who added this feature.

**Comment by Jmuccigr** [comment]
IIRC my contribution was simply to make the background-image variable work in revealjs as it already did in Beamer. I simply used the existing revealjs background method (parallax). I don’t object to the change as long as it works. :-)

**Comment by jgm** [comment]
There isn't a global `backgroundImage` setting in reveal.js as far as I can see.
We could set `data-background-image` on every section, I suppose, except for those that set this explicitly.

**Comment by lentzi90** [comment]
How about just changing the docs to explain this? Perhaps an extra note like this:

> Note that for reveal.js, the `background-image` will be used as a `parallax-background-image` (see below).
