### ISSUE TITLE
Reveal.js 4.0 breaks Pandoc export

### ISSUE THREAD

**Issue by p3palazzo** [jgm/pandoc#6451]
Pandoc 2.9.2.1 used to work with Reveal.js 3.9.2, but some [documented changes in asset locations](https://revealjs.com/upgrading/#update-asset-locations) in Reveal.js cause it to break. Specifically, the Javascript required for the slideshow to work as well as the Theme stylesheets have changed place.

**Comment by mb21** [comment]
I think this already fixed in master, see https://github.com/jgm/pandoc/pull/6390

**Comment by p3palazzo** [comment]
Thanks. I only searched for open issues before submitting this, so I missed it.
