### ISSUE TITLE
Textile pre-formatted text doesn't render in <pre> blocks

### ISSUE THREAD

**Issue by AlexVasiluta** [jgm/pandoc#6454]
Version: `2.7.3, compiled with pandoc-types 1.17.6.1, texmath 0.11.3, skylighting 0.8.2.1.`

Example input (saved as `test.textile` on disk):
```textile
pre. Bob and Alice
Like to drink apple juice
```
Command used: `pandoc test.textile`
Command output:
```html
<p>pre. Bob and Alice<br />
Like to drink apple juice</p>
```
Expected output:
```html
<pre>Bob and Alice
Like to drink apple juice</pre>
```

This happens to multiple conversions (I have also tested with markdown, everything is perfect except the pre-formatted code blocks), so i think this might be a problem with the textile parser.

By the way, I find it weird that you use `<pre>` blocks in the test file, since the textile standard that pandoc links in the readme [supports the `pre.` keyword](https://www.promptworks.com/textile/html-integration-and-escapement#preformatted-text)

**Comment by jgm** [comment]
`bc.` works but not `pre.` (maybe that was a later addition? the textile parser was written a long time back).  Anyway, I can easily add this.

**Comment by AlexVasiluta** [comment]
Awesome
Thank you so much!
