### ISSUE TITLE
As a user, I would like more information on how to bulk convert files on Windows

### ISSUE THREAD

**Issue by EricPonvelle** [jgm/pandoc#6463]
Hello,

I am working on a project where we are taking generated .htm files and converting them to .md files to build our documentation using Mkdocs.

I am able to manually convert each file, but when I followed the instructions on the FAQ on Windows 10: https://pandoc.org/faqs.html--changing the RTF to MD and the txt input to HTM as my files are in that format.

I received the following error: 

pandoc.exe: file 1.htm: openBinaryFile: does not exist (No such file or directory)

This, however, did produce my desired Markdown files for the entire folder, but I am unsure why the error comes up the way it does. Am I missing something in my environment? Also, is there a way to change this command to be issued from a Parent Folder and convert all the children folders too?

**Comment by kysko** [comment]
This is more a subject for [pandoc-discuss](https://groups.google.com/forum/#!forum/pandoc-discuss).

Search there with terms "batch windows", others and me have given some pointers.

**Comment by mb21** [comment]
Yes, questions should go to pandoc-discus... 

and this is also windows powershell specific... but see e.g. https://stackoverflow.com/questions/27852067/batch-convert-files-with-pandoc-in-windows
