### ISSUE TITLE
Support passthrough for RST block attributes/metadata in parser

### ISSUE THREAD

**Issue by mmcky** [jgm/pandoc#6465]
We are starting work on a project for converting `rst` to [myst](https://myst-parser.readthedocs.io/en/latest/using/syntax.html) format and would like to use `pandoc`. A discussion on [technology choices](https://github.com/executablebooks/rst2myst/issues/2) has led to posting this issue here. 

Our current approach is to use [panflute](https://github.com/sergiocorreia/panflute) to incorporate filters to pick up on `roles` and `directives` found in `rst` such as `.. code-block::` (a sphinx provided directive for rst).

Using the following string, 

```python
s2 = """
    .. code-block:: python3
       :linenos:
       :emphasize-lines: 1
       :name: test-block

       import pandas as pd
    """
```

it looks like the internal `json` representation is missing `block options` metadata such as `:linenos:` which is necessary for a lossless conversion of metadata associated with directives. 

```python
OrderedDict([('pandoc-api-version', (1, 17, 5, 1)), ('meta', OrderedDict()), ('blocks', [OrderedDict([('t', 'BlockQuote'), ('c', [OrderedDict([('t', 'CodeBlock'), ('c', [['', ['sourceCode', 'python3'], []], 'import pandas as pd'])])])])])])
```

Any advice on how to get this information passed through pandoc (or supported by pandoc parser) would be greatly appreciated. Thanks. 

cc: @tarleb

**Comment by mb21** [comment]
what you're saying is that the `linenos` and `emphasize-lines` attributes on code blocks are not read in by the RST reader. I suppose we could add them [here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/RST.hs#L674)...

**Comment by mmcky** [comment]
@mb21 thanks for the info and link. The `linenos` and `emphasize-lines` are just two examples of the [attributes available](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block) for the code-blocks directive

Is there a mechanism to extend the pandoc `rst` parser (i.e. via an extension)? I am wondering if it is possible to update the `rst` parser to teach it about sphinx, or other custom directives, and pass through the associated metadata and options that are available?

**Comment by mb21** [comment]
no, that's something that would need to be done in the  haskell parser itself. I guess it could be modified to pass through all unknown attributes... but not sure that's a good idea... probably this was discussed already somewhere..

but once it' in the document AST, you can use filters to change it...

**Comment by jgm** [comment]
I changed the parser to let through all attributes except the ones pandoc is  already doing something with.
