### ISSUE TITLE
Org mode - Support ":lines" for Include Files

### ISSUE THREAD

**Issue by eddiegroves** [jgm/pandoc#6466]
The include statement can specify which lines of the file to include:

```
‘#+INCLUDE: "~/.emacs" :lines "5-10"’ | Include lines 5 to 10, 10 excluded
‘#+INCLUDE: "~/.emacs" :lines "-10"’ | Include lines 1 to 10, 10 excluded
‘#+INCLUDE: "~/.emacs" :lines "10-"’ | Include lines from 10 to EOF
```

Example `src` instruction:

```
#+INCLUDE: "~/.emacs" src emacs-lisp :lines "5-10"
```

https://orgmode.org/manual/Include-Files.html

**Comment by jgm** [comment]
Note that the RST reader currently supports something similar to this, so that might be useful to look at when implementing.
