### ISSUE TITLE
word reference

### ISSUE THREAD

**Issue by 1269626032** [jgm/pandoc#6467]
Conversion of latex to word with pandoc does not support references and indexes 

#  pandoc version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/wyz/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
#  example

begin{equation}
  \label{eq:1}
  a^2+b^2=c^2
\end{equation}

\ref{eq:1}is  Pythagorean theorem

**Comment by mb21** [comment]
Can you try with the latest pandoc version please? 1.19 is ancient..

**Comment by 1269626032** [comment]
OK



---Original---

**Comment by jgm** [comment]
Correct: at this time we do not support equation references.
You could look into the pandoc-crossref filter.
