### ISSUE TITLE
Markdown raw html table to rst, the <a href ></a> in the table is omited. 

### ISSUE THREAD

**Issue by chenxshuo** [jgm/pandoc#6468]
# Version and Platform
Pandoc Version : pandoc 2.2.3.2; Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2

Platform: Ubuntu 16.04 LTS 

# Problems 
When I try to convert a MD document to rst, I found that the raw HTML table which contains a hyperlink cannot show as a link in the converted rst document. 

## Example
For example, I insert a raw HTML table in a MD (because I want to merge some grids and MD table cannot support it), and some contents are links. 

```html
<table>
<thead>
  <tr>
    <th>Model</th>
    <th>Hardware</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="2"><a href="http://www.google.com" target="_blank" rel="noopener noreferrer">V 1.0</a></td> 
   <!--Here is the link -->
    <td>Arm M8</td>
  </tr>
  <tr>
    <td>Arm A78</td>
  </tr>
</tbody>
</table>
```

after conversion using `pandoc -s -t rst --toc test-pandoc.md -o test-pandoc.rst `

I get below:

```
.. raw:: html

   <table>

.. raw:: html

   <thead>

.. raw:: html

   <tr>

.. raw:: html

   <th>

Model

.. raw:: html

   </th>

.. raw:: html

   <th>

Hardware

.. raw:: html

   </th>

.. raw:: html

   </tr>

.. raw:: html

   </thead>

.. raw:: html

   <tbody>

.. raw:: html

   <tr>

.. raw:: html

   <td rowspan="2">

V 1.0

.. raw:: html

   </td>

.. raw:: html

   <td>

Arm M8

.. raw:: html

   </td>

.. raw:: html

   </tr>

.. raw:: html

   <tr>

.. raw:: html

   <td>

Arm A78

.. raw:: html

   </td>

.. raw:: html

   </tr>

.. raw:: html

   </tbody>

.. raw:: html

   </table>

```

You can see that the link of `V 1.0` is missing and it becomes plain text in the rst document. 

What I want to see is the `<a href> </a>` stills shows in the table and I can click it.

**Comment by mb21** [comment]
> For example, I insert a raw HTML table in a MD (because I want to merge some grids and MD table cannot support it),

that's will eventually be supported in #6317

**Comment by chenxshuo** [comment]
> > For example, I insert a raw HTML table in a MD (because I want to merge some grids and MD table cannot support it),
> 
> that will eventually be supported in #6317

Got that, thanks a lot !

**Comment by tarleb** [comment]
My current recommendation is to put the table HTML into a "raw block", like so:

    ```{=html}
    <table>
    ...
    </table>
    ```

Then use a Lua filter to parse the table:

    if FORMAT:match 'html' then return {} end

    function RawBlock (raw)
      if raw.format == 'html' then
        return pandoc.read(raw.text, 'html').blocks
      end
    end
