### ISSUE TITLE
[latex] loading amssymb-package and using lualatex is "nonsensical" 

### ISSUE THREAD

**Issue by LukasCBossert** [jgm/pandoc#6469]
Consider as well:
> https://github.com/alif-type/libertinus/issues/327
> https://tex.stackexchange.com/questions/549933/symbol-eth-already-defined-when-using-libertinus-otf-and-lualatex-pandoc

Using `libertinus` as fontfamily within a yaml-header of a `.md`-file and trying to convert with pandoc (2.9.2) and the pdf-engine `lualatex` (TL 2020, LuaLaTeX 1.12.0) I get the following error-message:

```
! LaTeX Error: Command `\eth' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.240 ...mbol{\eth}            {\mathord}{AMSb}{"67}
```

**Steps to reproduce**
Take this mwe for the `.md`-file

```
---
title: Test
author: Author
date: \today
fontfamily: libertinus
---
This is a test-file. 

ÄÜÖß

1234567890
```

the command for the conversion is 

```
pandoc -s libertinus-test.md --pdf-engine=lualatex -o libertinus-test.pdf
```

I figured out that the problem is the line with the math-packages:

https://github.com/jgm/pandoc/blob/9d0506e4047f797a0672d7767830b59f1710d191/data/templates/default.latex#L100

** Note **
As soon as I change the fontfamily to `libertine` it is no problem.
But same problem also occurs with `libertinus-otf` (by HV).

There is a suggestion from user [egreg](https://tex.stackexchange.com/users/4427/egreg) for a change of the default latex-template:

```
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[$if(fontenc)$$fontenc$$else$T1$endif$]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb,amsmath}
\else % if luatex or xetex
$if(mathspec)$
  \ifxetex
    \usepackage{amssymb,amsmath}
    \usepackage{mathspec}
  \else
    \usepackage{unicode-math}
  \fi
$else$
  \usepackage{unicode-math}
$endif$
```
see https://tex.stackexchange.com/a/549938/98739

**Comment by jgm** [comment]
I can see the conflict with `amssymb`.
But doesn't `amsmath` provide definitions that are lacking in `unicode-math`?
The unicode-math documentation suggests this for both xelatex and lulatex:
```
\usepackage{amsmath}
\usepackage{unicode-math}
\setmathfont{texgyrepagella-math.otf}
```

**Comment by jgm** [comment]
Maybe worth asking on the forum if this was an oversight.

**Comment by lemzwerg** [comment]
Egreg has updated his stackexchange answer.

**Comment by angelo-peronio** [comment]
It seems that this issue [can be fixed](https://tex.stackexchange.com/a/549938). If it helps, I could prepare a dumb pull request.

**Comment by jgm** [comment]
Yes, a PR would be most welcome!

**Comment by jgm** [comment]
@LukasCBossert @angelo-peronio @argent0 - see #6825, and let me know what you think should be done.

**Comment by argent0** [comment]
1. One option would be to add the package latexsym and use: [\Box](https://tex.stackexchange.com/questions/115809/how-to-use-a-ballot-character-instead-of-a-bullet)

2. Another is keep using a math symbol, but this time from the unicode-math package if present or amssymb (the current usage) if not. The symbol could be: `enclosesquare`
documented [here](http://ctan.mirrors.hoobly.com/macros/unicodetex/latex/unicode-math/unimath-symbols.pdf)
This has the benefit of not adding a new package. OTOH, I think a  `newcommand`  will be needed to support each case.

Currently the LaTex writer uess:

```{haskell}
       let checkbox  = if checked
                       then "$\\boxtimes$"
                       else "$\\square$"
```

Using unicode directly on latex requires loading a font that supports the needed characters through the `fontspec` package.
This is not the case for the default font in my system.

```{latex}
\documentclass{article}
\usepackage{latexsym}

\begin{document}

\def\Item{\item[☐]}

\begin{itemize}

\Item
A
\Item 
B
\item
C
\end{itemize}

\end{document}
```
`$ xelatex test.tex` results in:

![result](https://user-images.githubusercontent.com/691306/98880119-cc21dc00-2465-11eb-9e1d-608307c540f6.png)

**Comment by jgm** [comment]
These could be viable workarounds.  But the bigger concern is that there may be other symbols people are relying on that are defined in `amssymb` -- apparently not *all* of them are in `unicodemath`.

**Comment by jgm** [comment]
Note:  I have effectively reverted PR #6762 with commit ea8097e41249387613cae2552866f1ea1cea1462

This is in response to #6825 -- the loss of amssymb meant that task lists no longer work.

I have not been able to find a single case where things fail with the current template, including the case described above, which I tried with all 3 tex engines -- but I've missed something, let me know.
