### ISSUE TITLE
Markdown writer: select table format on a per table basis

### ISSUE THREAD

**Issue by bwl21** [jgm/pandoc#6471]
There are lots of table formats supported by Pandoc. Each one has it pros and cons. Therefore one might want to use different formats per table.  But when i use pandoc as a prettifier for markdown all tables are converted to the same format.

Markdown writer should output the table in the same format as it was read. Alternatively, it should be possible to control the format on a per table basis, e.g. by an attribute.

**Comment by jgm** [comment]
I think this goes against the basic idea of pandoc: we are converting to an AST that indicates document structure (not implementation details), and inevitably semantically insignificant differences will be lost if you convert to and from such an AST.  Pandoc is not designed to be used as a prettifier; another tool, which represents a concrete syntax tree, would be more appropriate for that purpose.

**Comment by bwl21** [comment]
@jgm even if Pandoc is not designed to be used as a prettifier, it is capable to act as such.

It outputs markdown according to the way how pandoc understands the input.  Thus it is a **normalizer**  which does prettifying as a side effect.

As the markddown writer can select the table formats, I always face the problem that there is no format which has a superset of all features. So whatever I do, I am going to loose some details. This is the reationale behind this request.
