### ISSUE TITLE
rst to html: basic internal links don't work

### ISSUE THREAD

**Issue by hardingprofessional** [jgm/pandoc#6475]
Restructured text internal hyperlink targets are documented [here](https://docutils.sourceforge.io/docs/user/rst/quickref.html#internal-hyperlink-targets). 

My test document (test.rst) has the following content:

```
Internal crossreferences, like example_.

.. _example:

This is an example crossreference target.
```

The document is compiled with the following command:

 ```
$ pandoc test.rst -f rst -t html -s -o test.html
[pandoc warning] Could not find reference for Key "example" "source" (line 1, column 40)
```

As indicated by the error, pandoc failed to generate a valid link target for the link `example`.

I was going to include the HTML output here, but github isn't smart enough to escape html content.

In the HTML output, the link `<a href="">` should point to some id, and that id should be assigned to the `<p>` tag enclosing `This is an example crossreference target.</p>`

pandoc version:
```
pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
```

**Comment by jgm** [comment]
You can use backtick fences to quote the HTML.

Your pandoc version is ancient!

Here's what recent pandoc gives you:
```html
<p>Internal crossreferences, like <a href="#example">example</a>.</p>
<div id="example">
<p>This is an example crossreference target.</p>
</div>
```
The link works.  It's not on the p tag, because pandoc's internal document AST doesn't have a slot for attributes on paragraphs, so we introduce an enclosing Div.

**Comment by hardingprofessional** [comment]
Thanks! Silly of me not to realize my version was out of date.
