### ISSUE TITLE
Lua-filters – pandoc v2.9.2.1 ignores __ipairs metamethod   

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc#6477]
pandoc v2.9.2.1 appears to ignore the `__ipairs` metamethod.

Save the following script as `ipairs.lua`:

```Lua
function noipairs () return function () end end
local t = setmetatable({'This should not print.\n'}, {__ipairs = noipairs})
for _, v in ipairs(t) do io.stdout:write(v) end
```
Then, calling `pandoc -L ipairs.lua /dev/null 2>/dev/null` prints:

> This should not print.

Compare to `lua ipairs.lua`, which prints nothing.

**Comment by tarleb** [comment]
What you are seeing is the difference between Lua 5.2, where the `__ipairs` metamethod was introduced, and Lua 5.3, where it got [removed/deprecated again](https://www.lua.org/manual/5.3/manual.html#8.2). I believe it's still possible to enable this functionality in Lua 5.3 by compiling in compatibility mode. Pandoc ships with Lua 5.3 and does not enable Lua 5.2 compatibility, so the behavior is expected.

**Comment by tarleb** [comment]
BTW, you can make pandoc use your system's Lua installation by compiling it with `cabal install --constraint='hslua +system-lua +pkg-config' pandoc`

**Comment by odkr** [comment]
Oh, presumably the Homebrew packages was compiled in compatibility mode. I didn’t notice `__ipairs` went away again. Good to know, thanks!

**Comment by tarleb** [comment]
Personally I'm rather unhappy about this change, it makes some things a lot harder or requires specialized functions as iterators. If you search the web, you'll find quite a few discussions related to this.
