### ISSUE TITLE
any character before brackets causes inconsistent escaping with Jira

### ISSUE THREAD

**Issue by Eising** [jgm/pandoc#6478]
Hello,

This issue can be easily reproduced on the Try pandoc! page.
Using any text-based markup, such as org-mode as input with the following string, and Jira as output:
<pre>
Test f{this}
</pre>

Expected output:

<pre>
Test f\{this\}
</pre>

Actual output:
<pre>
Test f{this\}
</pre>

**Comment by mb21** [comment]
Is there official documentation on whether `{` needs to be escaped as well? because in our jira v8.5.1 `Test f{this\}` actually works...

**Comment by tarleb** [comment]
We try to make the markup as readable as possible and therefore escape as little as possible. We are pretty careful about escaping everything that needs escaping. E.g. putting a subscript between the braces `Test f{_1}` produces `Test f\{~1~\}`, so it *does* escape the opening brace in this case.

Regardless, there might be something amiss. @Eising, does the reported behavior cause any rendering problems?

**Comment by Eising** [comment]
Yes. It doesn't render correctly if only the last bracket is escaped.

I have also observed some similar escaping problems when brackets appear together with some other special characters. I can probably document these issues as well later.

**Comment by Eising** [comment]
> Is there official documentation on whether `{` needs to be escaped as well? because in our jira v8.5.1 `Test f{this\}` actually works... but yes, escaping it also works and might be safer?

I have some documents with loads of ${something} pieces inside the text. This breaks confluence's ability to recognize it as valid markup. Sometimes it renders it correctly nonetheless, but the behavior seems a bit inconsistent.

I would suggest escaping both brackets for a more consistently correct behavior.

**Comment by tarleb** [comment]
Could it be that this happens in Confluence only? That would explain why we didn't catch that before. I no longer have access to a Confluence version which allows Jira Wiki imports, so I can't really verify this.

Adding the extra escaping just for opening braces seems like a good way forward.

**Comment by Eising** [comment]
> Could it be that this happens in Confluence only? That would explain why we didn't catch that before. I no longer have access to a Confluence version which allows Jira Wiki imports, so I can't really verify this.

I just tested this, and you're absolutely right. Jira seems to be a lot more forgiving when it comes to this.

> Adding the extra escaping just for opening braces seems like a good way forward.

Yeah. I do assume that a lot more documents will be converted in to Confluence than the small Jira tickets in the future - that at least is my use case.

**Comment by tarleb** [comment]
I found that the string `a{b } d` (`[Str "a{b",Space,Str "}",Space,Str "d"]` in native representation) also results in rendering problems in Jira, so this is not just a Confluence issue.
