### ISSUE TITLE
Div surrounding grid table does not produce correct output

### ISSUE THREAD

**Issue by jack-kirton** [jgm/pandoc#6481]
Pandoc version: 2.9.2.1

Having a div surround a table that pandoc will write as a grid table in markdown creates invalid pandoc markdown, as reading that markdown back into pandoc causes the table to not be recognised as a table.

[table-test.txt](https://github.com/jgm/pandoc/files/4818828/table-test.txt) is a grid table in hand-written markdown.

Running the command `pandoc --from=markdown+smart --to=native < table-test.txt | pandoc --from=native --to=markdown+smart` produces a grid table surrounded by native markdown div markers, `::: {.div-class}` and `:::`.

Examining the AST by running `pandoc --from=markdown+smart --to=native` shows that the table was not interpreted as a table but as plain text.

**Comment by mb21** [comment]
so the output of `pandoc table-test.txt -t markdown` (which is basically what you're doing) is:

```
::: {.div-class}
+-------+-----+-----+-------------------------------------------------+
| Col 1 | Col | Col | Col 4                                           |
|       | 2   | 3   |                                                 |
+:=====:+:===:+:===:+:================================================+
| High  | Med | Med | Some description of something.                  |
|       | ium | ium |                                                 |
|       |     |     | Another paragraph to ensure Pandoc produces a   |
|       |     |     | grid table.                                     |
+-------+-----+-----+-------------------------------------------------+
:::
```

and you would prefer html divs instead of markdown divs, or...?

**Comment by jack-kirton** [comment]
Sorry for the roundabout series of commands, you are exactly right that is what is produced.
The problem arises when that table is fed back into pandoc as it is no longer recognised as a table, just a paragraph in a div.

**Comment by mb21** [comment]
ah yes, of course. there are newlines missing...
