### ISSUE TITLE
[makePDF] logging written to STDOUT

### ISSUE THREAD

**Issue by garethstockwell** [jgm/pandoc#6483]
Pandoc version: 2.9.2.1

When rendering to PDF with `--verbose`, [makePDF] logging is written to STDOUT whereas all other logging is written to STDERR.  It would be easier to integrate pandoc into workflows if all logging was to STDERR.

Steps to reproduce:

    echo foo | pandoc --from markdown --filter filter.py --to latex --output test.pdf --verbose > log.out 2> log.err

With the following in `filter.py`:

    #!/usr/bin/env python
    from pandocfilters import toJSONFilters
    toJSONFilters([])

`log.out` contains

    [makePDF] temp dir:
    /tmp/tex2pdf.-61fc320f83e009f2
    [makePDF] Command line:
    pdflatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "/tmp/tex2pdf.-61fc320f83e009f2" "/tmp/tex2pdf.-61fc320f83e009f2/input.tex"
    
    [makePDF] Environment:
    ("TEXINPUTS","/tmp/tex2pdf.-61fc320f83e009f2:")
    ("TEXMFOUTPUT","/tmp/tex2pdf.-61fc320f83e009f2")
    
    ...
    
    Output written on /tmp/tex2pdf.-61fc320f83e009f2/input.pdf (1 page, 17828 bytes
    ).
    Transcript written on /tmp/tex2pdf.-61fc320f83e009f2/input.log.

`log.err` contains

    [INFO] Running filter filter.py
    [INFO] Completed filter filter.py in 3 ms

From a quick look at the source:

* [makePDF] logging is generated in `src/Text/Pandoc/PDF.hs` using `putStrLn` directly
* All other logging is generated by `PandocMonad.logOutput` using formatting functions in `src/Text/Pandoc/Logging.hs`, which also associate a given message type with a log level (warning / info / verbose)

Is there any reason why [makePDF] logging could not use `PandocMonad.logOutput`?

**Comment by jgm** [comment]
I agree that it shouldn't go to stdout (unless there's something I'm not thinking of).

I'm not sure it should use logOutput -- this would require a new constructor for LogMessage -- but maybe this is the right thing to do.

Note that we're dumping log output as bytestrings.  If we had a LogMessage we might want to make the parameter Text, and then we'd need to do a conversion. And sometimes latex log output is not UTF-8 encoded.  We could do a lenientDecode, however.

**Comment by jgm** [comment]
It may be that I didn't want the two-space indent that `logOutput` gives.  (Since we're looking at tex source for example.)
