### ISSUE TITLE
Multiline `lookupMeta` for org-mode files.

### ISSUE THREAD

**Issue by yogsototh** [jgm/pandoc#6485]
My version:

```
pandoc 2.9.1.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.4
```

So I've got an org-mode file with:

```orgmode
#+DESCRIPTION: A short and intense introduction to Haskell.
#+DESCRIPTION: This is an update of my old (2012) article.
#+DESCRIPTION: A lot of things have changed since then.
#+DESCRIPTION: Mostly I changed my approach about the easiest way to install
#+DESCRIPTION: a Haskell playground.
#+DESCRIPTION: I removed the not as important part, and added a short
#+DESCRIPTION: introduction about starting a new project.
```

By default orgmode exporter concatenate those entries.
But `lookupMeta` only keep the last line.

```haskell
 descr $ lookupMeta "description" meta
 where
    descr (Just (MetaString t)) = t
    descr _ = ""
```

returns `"introduction about starting a new project."`

It would be nice to support these multiline orgmode metas. The ideal being having a `MetaList _`

**Comment by tarleb** [comment]
A general solution for this is difficult: last time I checked, some of these export setting lines overwrite previous lines. I added `#+DESCRIPTION` to the list of supported options, allowing text spreadable across multiple lines.
