### ISSUE TITLE
Error When conveting via https://pandoc.org/try/

### ISSUE THREAD

**Issue by teemo0803** [jgm/pandoc#6486]
Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server.
Apache/2.4.38 (Debian) Server at johnmacfarlane.net Port 443

**Comment by teemo0803** [comment]
By the way, are there any tutor about how to host a online converter?

Cheers

**Comment by mb21** [comment]
You didn't expect us to not put a length limit on that and be open to DDOS?

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
