### ISSUE TITLE
ipynb to markdown: disable escaping 

### ISSUE THREAD

**Issue by teucer** [jgm/pandoc#6489]
Planning to use jupyter notebooks for documentation purposes. The idea is to:

1. Use jupyter to create document interactively: each cell would be either a markdown cell or a code cell outputting markdown
2. Convert the notebook to markdown for version control purposes
3. Convert the markdown file to latex

I am using `pandoc  --from ipynb --to markdown-smart notebook.ipynb -o notebook.md --atx-headers --wrap=preserve  --standalone --preserve-tabs` for the second step. 

The issue is that pandoc is escaping special characters. In general this is useful, but it is not ideal in this setup.

E.g. if I insert an image like below in the notebook (planning to use [pandoc-fignos](https://github.com/tomduck/pandoc-fignos))

```markdown
![A Markdown logo](markdown.png){#fig:fig1}
``` 
, it gets converted to 

```markdown
![A Markdown logo](markdown.png){\#fig:fig1}
```

Is there a way to disable all escaping in the markdown writer?

**Comment by mb21** [comment]
you're saying you would do that with a filter like pandoc-fignos? then the filter will do this correctly... or maybe I'm misunderstanding, and that is part of the `notebook.ipynb`? if so, you'd need to post that file. Also, are you using the newest pandoc version?

**Comment by teucer** [comment]
I am planning to use `pandoc-fignos` in step 3 (using pandoc 2.9.2.1.).

 Please find `notebook.ipynb`  below. 

```json
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Section\n",
    "This is our first section.\n",
    "\n",
    "We can use Markdown for figures.\n",
    "\n",
    "![A Markdown logo](markdown.png){#fig:fig1}\n",
    "\n",
    "We can display equations:\n",
    "\n",
    "$$\n",
    "y = -2.5x + 0.5\n",
    "$$"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We can insert figures as below:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "![The function $y=\\sin(x)$](plot.png){#fig:fig2 width=100% max-width=400px}\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "x = np.linspace(0, 10, 100)\n",
    "\n",
    "plt.plot(x, np.sin(x))\n",
    "plt.plot(x, np.cos(x))\n",
    "\n",
    "plt.savefig('plot.png', transparent=True, bbox_inches='tight')\n",
    "plt.close()\n",
    "markdown = '''\n",
    "![The function $y=\\\\sin(x)$](plot.png){#fig:fig2 width=100% max-width=400px}\n",
    "'''\n",
    "print(markdown)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Reference to fig. @fig:fig2."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

**Comment by jgm** [comment]
There isn't a way to disable escaping.

However, see #5408 -- I think this is really what you want.

**Comment by teucer** [comment]
@jgm closing this and will comment on #5408
