### ISSUE TITLE
html to markdown did not render completely..

### ISSUE THREAD

**Issue by fdq09eca** [jgm/pandoc#6494]
here is the [html](https://docs.cs50.net/web/2020/x/projects/2/project2.html) I want to render to `markdown`.

I tried this

```bash
pandoc --from html https://docs.cs50.net/web/2020/x/projects/2/project2.html --to markdown_strict -o README.md    
```

but it only renders until the **Hints** section, the **How to Submit** section is neglected, see below.

![image](https://user-images.githubusercontent.com/51902242/86216535-c4495580-bbb0-11ea-9966-7024378807ad.png)

Why? did I do anything wrong? Thank you.

**Comment by mb21** [comment]
Can you try the newest pandoc version?

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. 


Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by tarleb** [comment]
I don't see any section named  "How to submit" on the linked page.

**Comment by fdq09eca** [comment]
> I don't see any section named "How to submit" on the linked page.

that's weird

![image](https://user-images.githubusercontent.com/51902242/86227847-38d7c080-bbc0-11ea-8091-65a843b8579e.png)

**Comment by fdq09eca** [comment]
i think i have found the answer.. @tarleb is right, there is no such section in the link. they must have updated it just now.
