### ISSUE TITLE
[Markdown]  Dash-separated long list items rendered as sublist

### ISSUE THREAD

**Issue by kdeldycke** [jgm/pandoc#6497]
Here is a Markdown file with a list of very long items:

```markdown
❯ cat ./dash-separated-link-list.md
- [Link 1](#link-1) - Description of line 1.
- [Link 2](#link-2) - A very long description for the second link in the list. That description is more than 80 characters wide.
- [This is a very long title, pointing to an awesome article on incredible stuff we're not used to see everyday](#link-3) - Line #3's description.
- [Link number three](#this-is-a-very-long-url-that-is-pointing-to-a-really-really-great-website) - Fourth description.
```

Which renders into a clean list of four items:

- [Link 1](#link-1) - Description of line 1.
- [Link 2](#link-2) - A very long description for the second link in the list. That description is more than 80 characters wide.
- [This is a very long title, pointing to an awesome article on incredible stuff we're not used to see everyday](#link-3) - Line #3's description.
- [Link number three](#this-is-a-very-long-url-that-is-pointing-to-a-really-really-great-website) - Fourth description.

Now I want to clean this file and have pandoc automatically wraps long lines. Here is the CLI I run:

```markdown
❯ pandoc ./dash-separated-link-list.md --to=gfm
  - [Link 1](#link-1) - Description of line 1.
  - [Link 2](#link-2) - A very long description for the second link in
    the list. That description is more than 80 characters wide.
  - [This is a very long title, pointing to an awesome article on
    incredible stuff we’re not used to see everyday](#link-3) - Line
    \#3’s description.
  - [Link number
    three](#this-is-a-very-long-url-that-is-pointing-to-a-really-really-great-website)
    - Fourth description.
```

Which renders to:

  - [Link 1](#link-1) - Description of line 1.
  - [Link 2](#link-2) - A very long description for the second link in the list. That description is more than 80 characters wide.
  - [This is a very long title, pointing to an awesome article on incredible stuff we’re not used to see everyday](#link-3) - Line \#3’s description.
  - [Link number three](#this-is-a-very-long-url-that-is-pointing-to-a-really-really-great-website)
    - Fourth description.

You can see how the fourth description is rendered as a sub-list because of the dash? I think this is a bug.

What's interesting in this case is that other variants of Markdown seems to account for this edge-case and keep the dash in the previous line to prevent accidental rendering of sublists:

```markdown
❯ pandoc ./dash-separated-link-list.md --to=markdown_github
[WARNING] Deprecated: markdown_github. Use gfm instead.
-   [Link 1](#link-1) - Description of line 1.
-   [Link 2](#link-2) - A very long description for the second link in
    the list. That description is more than 80 characters wide.
-   [This is a very long title, pointing to an awesome article on
    incredible stuff we’re not used to see everyday](#link-3) - Line
    \#3’s description.
-   [Link number
    three](#this-is-a-very-long-url-that-is-pointing-to-a-really-really-great-website) -
    Fourth description.

❯ pandoc ./dash-separated-link-list.md --to=markdown_mmd
-   [Link 1](#link-1) - Description of line 1.
-   [Link 2](#link-2) - A very long description for the second link in
    the list. That description is more than 80 characters wide.
-   [This is a very long title, pointing to an awesome article on
    incredible stuff we’re not used to see everyday](#link-3) - Line
    \#3’s description.
-   [Link number
    three](#this-is-a-very-long-url-that-is-pointing-to-a-really-really-great-website) -
    Fourth description.

❯ pandoc ./dash-separated-link-list.md --to=markdown_strict
-   [Link 1](#link-1) - Description of line 1.
-   [Link 2](#link-2) - A very long description for the second link in
    the list. That description is more than 80 characters wide.
-   [This is a very long title, pointing to an awesome article on
    incredible stuff we’re not used to see everyday](#link-3) - Line
    \#3’s description.
-   [Link number
    three](#this-is-a-very-long-url-that-is-pointing-to-a-really-really-great-website) -
    Fourth description.
```

For the record, here is my version of pandoc, straight out of `brew` on macOS Catalina:
```shell-session
❯ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
```

**Comment by jgm** [comment]
For gfm we use libcmark's renderer, which in this respect is less sophisticated than the native pandoc renderers.  (Of course I could do something about this, since I'm also the maintainer of libcmark, but it would have to be fixed there: commonmark/cmark on GitHub.  You can report this there if you like.)

**Comment by kdeldycke** [comment]
Thanks @jgm for the tip. I just reproduced the bug with the standalone `cmark` CLI and created a bug report at https://github.com/commonmark/cmark/issues/347 .

**Comment by kdeldycke** [comment]
BTW @jgm, what do you think of @DavidAnson workaround at https://github.com/DavidAnson/markdownlint/issues/302#issuecomment-653167524 of using link references?

**Comment by jgm** [comment]
I'll close here, since it's really an upstream issue.
Yes, using link references can help in particular cases.

**Comment by kdeldycke** [comment]
Fair enough! Thanks @jgm for the feedback! :)
