### ISSUE TITLE
reStructuredText reader bug

### ISSUE THREAD

**Issue by cpkio** [jgm/pandoc#6502]
RST reader parses custom roles differently, depending on item location.

Test text:

```
.. role:: button
.. role:: tab

На вкладке :tab:`Файлы` под кнопками :button:`Завершить работу` и :button:`Выйти`,
расположены три кнопки: :button:`Загрузить`, :button:`Новый` и |refreshicon| (:button:`Обновить`)
(рисунок `Кнопки "Загрузить", "Новый" и "Обновить"`_). Функциональность этих кнопок
описана в таблице `Кнопки файл-менеджера`_.

|figure05|
   
.. |figure05| figure:: img\dummy.png

   Кнопки :button:`Загрузить`, :button:`Новый` и :button:`Обновить`
```
As you can see, the `:button:` role is in the text and in the paragraph.

Still, the JSON output is not the same.

This is how it looks like inside a paragraph:
```
{"t":"Span","c":[["",["button"],[]],[{"t":"Str","c":"Обновить"}]]}
```

And this is how it is in a Figure caption:
```
{"t":"Code","c":[["",["interpreted-text"],[["role","button"]]],"Новый"]}
```

This difference is important in writing filters, please fix. I'd suggest to stick to the first variant.

**Comment by jgm** [comment]
This is no longer an issue with the latest changes.
