### ISSUE TITLE
markdown->pdf: Bold text after level 4 heading is missing newline

### ISSUE THREAD

**Issue by camoz** [jgm/pandoc#6503]
**Pandoc Version**

    $ pandoc -v
    pandoc 2.9.2.1
    Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5

**Texlive version**

    $ pacman -Q texlive-core 
    texlive-core 2020.55416-1

**Reproducing steps**

1. Create a file `test.md` with the following input:
```
# heading1

## heading2

### heading3

#### heading4

**some bold text**
```
2. Run the command: `pandoc -f markdown -t pdf -o test.pdf test.md`
3. View the resulting file `test.pdf`

**Expected behaviour**

`heading4` and `some bold text` appear on different lines.

**Actual behaviour**

`heading4` and `some bold text` appear on the same line.
Screenshot:
![slurp_2020-07-05_001433](https://user-images.githubusercontent.com/6276613/86521799-99336000-be55-11ea-994f-d71989b5fa1d.png)

**Comment by mb21** [comment]
please try `-t latex` to see what latex we generate. what would you expect instead?

I don't think there's any latex for h5 and more...

**Comment by camoz** [comment]
```
$ pandoc -f markdown -t latex test.md 
\hypertarget{heading1}{%
\section{heading1}\label{heading1}}

\hypertarget{heading2}{%
\subsection{heading2}\label{heading2}}

\hypertarget{heading3}{%
\subsubsection{heading3}\label{heading3}}

\hypertarget{heading4}{%
\paragraph{heading4}\label{heading4}}

\textbf{some bold text}
```
I don't know any latex at all, but this looks like `some bold text` appears not on the same line as `heading4`.
I have written in the first post what behavior I would expect.

Sorry if this is not an issue with pandoc but with pdf generation...

**Comment by tarleb** [comment]
There is a [nice answer for this on StackExchange](https://tex.stackexchange.com/q/5035). Translated to pandoc, it should be enough to add this to your document:

```` markdown
---
header-includes: |
  ```{=latex}
  \usepackage{titlesec}
  \titleformat{\paragraph}[hang]{\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}
  \titlespacing*{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{0.5em}
  ```
---
````

**Comment by camoz** [comment]
Okay, so from what I understand this is expcted behaviour with Latex, since there is no `\subsubsubsection` ("h4") by default - `\paragraph` is used for defining the section level below `\subsubsection`.

This means one cannot use level 4 headings like `#### heading` in a markdown document when one wants to convert this markdown document to both HTML and Latex/PDF at the same time - at least not without further modifications/additions such as the one @tarleb pointed out above. If said modifications/additions are not taken, level 4 headings look very different in the Latex/PDF document than in the generated HTML, as described in my first post.

**Comment by tarleb** [comment]
If by "cannot be used" you mean that they render slightly differently, then yes, this is correct. Pandoc aims to preserve the structural representation of a document and mostly relies on the target format's defaults for the visual representation. There are multiple ways to adjust the final rendering: custom templates, CSS, header includes, etc.. Users have complete freedom when adjusting the result to their specific requirements.

This seems to be resolved, thus closing.

**Comment by camoz** [comment]
Yes, that's what I've meant. I realize now my previous comment sounds a bit rude, my apologies.
Thanks for explaining it to me :)
Cheers.
