### ISSUE TITLE
Missing Ampersand in Code Blocks in ms Output

### ISSUE THREAD

**Issue by tkurtbond** [jgm/pandoc#6505]
# Missing Ampersand in Code Blocks in `ms` Output

Using pandoc version

``` 
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
```

Here's some ReStructuredText (file `ma.rst`) input that has a code block
in it:

``` restructuredtext
Missing Ampersand in Code Block -ms output
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Here's a code block containing ReStructuredText:

.. code::

   .. container:: for-format ms

      .. figure:: davesmapper-2017-04-10-caves-4-numbered.eps
         :alt: Map of Bandit's Cave

      Map of Bandit's Cave

   .. container:: for-format html latex context epub

      .. figure:: davesmapper-2017-04-10-caves-4-numbered.png
         :alt: Map of Bandit's Cave

         Map of Bandit's Cave

How's that look?
```

Using the command line `pandoc -r rst -w ms -o ma-rst.ms ma.rst`, here's
the `ms` output from it:

``` nroff
.SH 1
Missing Ampersand in Code Block -ms output
.pdfhref O 1 "Missing Ampersand in Code Block -ms output"
.pdfhref M "missing-ampersand-in-code-block--ms-output"
.LP
Here\[aq]s a code block containing ReStructuredText:
.IP
.nf
\f[C]
.. container:: for-format ms

   .. figure:: davesmapper-2017-04-10-caves-4-numbered.eps
      :alt: Map of Bandit\[aq]s Cave

   Map of Bandit\[aq]s Cave

\&.. container:: for-format html latex context epub

   .. figure:: davesmapper-2017-04-10-caves-4-numbered.png
      :alt: Map of Bandit\[aq]s Cave

      Map of Bandit\[aq]s Cave
\f[]
.fi
.LP
How\[aq]s that look?
```

See the first line that starts with `.. container::`? That line should
start with `\&` so it isn't interpreted as an **roff** command. As it
is, when you build the PDF output from output that line disappears
entirely with no warning to the user. (The default for **roff**
processors like **groff** is to ignore unknown commands.)

See the second line that starts with `.. container::`? That line
**does** start with `\&`. It makes it through fine. The other lines
whose first non-whitespace character is `.` make it through fine because
to make it a **roff** command the first character on the line has to be
a period.

Oddly enough, it doesn't happen with `man` output. Using the command
`pandoc -r rst -w man -o ma-rst.man ma.rst` here's the `man` output from
it:

``` nroff
.SH Missing Ampersand in Code Block -ms output
.PP
Here\[aq]s a code block containing ReStructuredText:
.IP
.nf
\f[C]
\&.. container:: for-format ms

   .. figure:: davesmapper-2017-04-10-caves-4-numbered.eps
      :alt: Map of Bandit\[aq]s Cave

   Map of Bandit\[aq]s Cave

\&.. container:: for-format html latex context epub

   .. figure:: davesmapper-2017-04-10-caves-4-numbered.png
      :alt: Map of Bandit\[aq]s Cave

      Map of Bandit\[aq]s Cave
\f[R]
.fi
.PP
How\[aq]s that look?
```

The first line that starts with `.. container::` has a `\&` at the
beginning.

**Comment by jgm** [comment]
The man writer contains this code
```haskell
  ((case T.uncons str of
    Just ('.',_) -> literal "\\&"
    _            -> mempty) <>
```
in the handler for CodeBlock. We need something like that in the ms writer.

**Comment by brisad** [comment]
Hi! I'd be happy to try to fix this one.
