### ISSUE TITLE
upgrading to 2.x from 1.19.2.1

### ISSUE THREAD

**Issue by glb94** [jgm/pandoc#6507]
I'm trying to upgrade pandoc from 1.19.2.1 to a up to date version. 
I'm having problems with the unistall process of 1.19.2.1 in windows.
No matter the way I remove it when I try to run the new version it says that pandoc could't be found ( it is old location)
I have searched in the PATH both in system and user but there is not any reference to the older path. 
I can't use the old path because it's going from x86 to x64 ( so program files (x86) to program files.
I have tried restarting the computer, turning it on and off and restarting the console/powershell with no results

Any idea where could be the lost reference to the old pandoc instalation?

**Comment by mb21** [comment]
Don't think we have any windows powershell experts here, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker to ask questions. Thanks!
