### ISSUE TITLE
Clash between memoir, frenchb and footnotehyper in latex/pdf output

### ISSUE THREAD

**Issue by porlk** [jgm/pandoc#6510]
I am using pandoc 2.9.2.1 on latest archlinux, with pdfTeX 3.14159265-2.6-1.40.21 on TeX Live 2020.

When converting from markdown to pdf with latex, the combination of the `memoir` class, the `frenchb` babel lang package and the use of a table in the document generates a crash of latex.

See the following example document:
```
---
documentclass: memoir
lang: fr-FR
---

| test | test | test |
|------|------|------|
|      |      |      |
```
Compiling with `pandoc example.md -s -o example.pdf` generated the following error message:
```
Error producing PDF.
! Illegal parameter number in definition of \FNH@prefntext.
<to be read again> 
                   1
l.68 \begin{document}
```
Using --pdf-engine=lualatex does not change anything. Upon investigation, it seems that when using a table in the markdown file, pandoc loads the `footnotehyper` package:
```
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
```
Commenting these lines in the intermediary tex file (`pandoc example.md -s -o example.tex`) leads to a successfull build with pdflatex. Replacing `\usepackage{footnotehyper}` with `\usepackage{footnote}` leads also to a succesfull build. Therefore it seems to me that the combination of `memoir`, `frenchb` and `footnotehyper` is clashing.

**Comment by kysko** [comment]
The author of this package, Jean-Francois Burnol, is [already aware of this](https://github.com/sphinx-doc/sphinx/issues/7576):
> A general fix may be some time in coming.

**Comment by jfbu** [comment]
Latest [footnotehyper](https://ctan.org/pkg/footnotehyper) fixes incompatibility with the combination `memoir` + `babel-french` which causes this issue (sorry for late). TeXLive 2020 mirrors have it.

**Comment by jgm** [comment]
Excellent!  Thanks very much, I'll close this here.
