### ISSUE TITLE
Possible Error in Manual » Template » Delimiters?

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#6531]
I think there might be an error in [pandoc Manual » Template syntax » Delimiters]:

> ### Delimiters
> 
> To mark variables and control structures in the template, either $…$ or ${…} may be used as delimiters. The styles may also be mixed in the same template, but the opening and closing delimiter must match in each case. The opening delimiter may be followed by one or more spaces or tabs, which will be ignored. **The closing delimiter may be _followed_ by one or more spaces or tabs**, which will be ignored.

Possibly, the last sentence was meant to be:

> The closing delimiter may be _**preceded**_ by one or more spaces or tabs, which will be ignored

The above seems to make more sense.

[pandoc Manual » Template syntax » Delimiters]: https://pandoc.org/MANUAL.html#delimiters

**Comment by mb21** [comment]
Did you try it? I thought the delimiter followed by space works `$foo$ `, while this doesn't: `$foo $`

**Comment by tajmone** [comment]
You're absolutely right. I got confused.
