### ISSUE TITLE
Jira reader: Square brackets in link text for anchor links

### ISSUE THREAD

**Issue by 0xDAFE** [jgm/pandoc#6532]
Hi everyone,

I am having a special case where the text to be displayed for a Jira Markup anchor link contains square brackets.
Example: "Please see [[1]](#ref1)"
When using pandoc to convert from Jira Markup to other formats such as HTML5, the links are not converted correctly.

[This example is correct.](https://pandoc.org/try/?text=Please+refer+to+%5B1%7C%23ref1%5D.&from=jira&to=html5&standalone=0)
[This example is not correct.](https://pandoc.org/try/?text=Please+refer+to+%5B%5B1%5D%7C%23ref1%5D.&from=jira&to=html5&standalone=0)
[This example with manual escaping in Jira's text mode *would* be correct but as soon as you changes something in the the issue's description and save it, the manual escaping is undone by Jira](https://pandoc.org/try/?text=Please+refer+to+%5B%5C%5B1%5C%5D%7C%23ref1%5D.&from=jira&to=html5&standalone=0)

Pandoc version: 2.10
Jira Datacenter/Server: 7.13.X
Jira Cloud does not let you enter "plain" anchor links without a base URL in the first place.

@tarleb I am not sure if this is a Jira issue or something that can/should be addressed in the Jira Reader.

**Comment by tarleb** [comment]
Huh, weird. I was able to use escaped brackets in Jira Cloud, but only when creating the issue. And the link only renders correctly if I choose the "old view", not the new default.

I'm afraid there isn't much we can do on our side. It does indeed seem like a Jira issue.

**Comment by tarleb** [comment]
I'm closing this for now, but will happily reopen if there are concrete steps we can take to improve the situation.
