### ISSUE TITLE
pandoc handles quotes combined with newlines in triple-quoted codeblocks incorrectly when they appear after a doubly-nested list

### ISSUE THREAD

**Issue by JasonGross** [jgm/pandoc#6533]
Pandoc version 2.10 installed from [the latest .deb release](https://github.com/jgm/pandoc/releases/download/2.10/pandoc-2.10-1-amd64.deb)
```
$ pandoc --version
pandoc 2.10
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/jgross/.local/share/pandoc or /home/jgross/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

```
$ cat foo.md
```
    - a
    ```
    "a"
    
    b
    ```
    
    
    - a
      - b
    ```
    "a"
    
    b
    ```

```
$ pandoc -s foo.md -o foo.tex; cat foo.tex
```
    % Options for packages loaded elsewhere
    \PassOptionsToPackage{unicode}{hyperref}
    \PassOptionsToPackage{hyphens}{url}
    %
    \documentclass[
    ]{article}
    \usepackage{lmodern}
    \usepackage{amssymb,amsmath}
    \usepackage{ifxetex,ifluatex}
    \ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
      \usepackage[T1]{fontenc}
      \usepackage[utf8]{inputenc}
      \usepackage{textcomp} % provide euro and other symbols
    \else % if luatex or xetex
      \usepackage{unicode-math}
      \defaultfontfeatures{Scale=MatchLowercase}
      \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
    \fi
    % Use upquote if available, for straight quotes in verbatim environments
    \IfFileExists{upquote.sty}{\usepackage{upquote}}{}
    \IfFileExists{microtype.sty}{% use microtype if available
      \usepackage[]{microtype}
      \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
    }{}
    \makeatletter
    \@ifundefined{KOMAClassName}{% if non-KOMA class
      \IfFileExists{parskip.sty}{%
        \usepackage{parskip}
      }{% else
        \setlength{\parindent}{0pt}
        \setlength{\parskip}{6pt plus 2pt minus 1pt}}
    }{% if KOMA class
      \KOMAoptions{parskip=half}}
    \makeatother
    \usepackage{xcolor}
    \IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
    \IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
    \hypersetup{
      hidelinks,
      pdfcreator={LaTeX via pandoc}}
    \urlstyle{same} % disable monospaced font for URLs
    \setlength{\emergencystretch}{3em} % prevent overfull lines
    \providecommand{\tightlist}{%
      \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
    \usepackage{xcolor}
    \IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
    \IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
    \hypersetup{
      hidelinks,
      pdfcreator={LaTeX via pandoc}}
    \urlstyle{same} % disable monospaced font for URLs
    \setlength{\emergencystretch}{3em} % prevent overfull lines
    \providecommand{\tightlist}{%
      \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
    \setcounter{secnumdepth}{-\maxdimen} % remove section numbering

    \author{}
    \date{}

    \begin{document}

    \begin{itemize}
    \tightlist
    \item
      a
    \end{itemize}

    \begin{verbatim}
    "a"

    b
    \end{verbatim}

    \begin{itemize}
    \tightlist
    \item
      a

      \begin{itemize}
      \tightlist
      \item
        b ``` ``a''
      \end{itemize}
    \end{itemize}

    b ```

    \end{document}

If I remove the newline in the codeblock, things work fine even when there are two levels of list nesting.

**Comment by mb21** [comment]
Indeed, with `-f commonmark`, this doesn't happen....

**Comment by kysko** [comment]
But shouldn't code blocks be surrounded by blank lines? Else the risk of interpreting as "lazy" (sic) writing.
I'm more surprised the "lazy" format didn't kick in for the block after the single list.

**Comment by JasonGross** [comment]
Surrounding them with newlines breaks nesting of bulleted lists, especially when the bullets are indented 4 or more spaces, which are mistakenly treated as code blocks if they aren't registered as nested under previous bullets

**Comment by jgm** [comment]
What is your intention in writing
````
- a
  - b
```
"a"

b
```
````

If you want to close off the bullet list and have the code block after it, then put a blank line before the triple backticks.

If you want the code block to belong to the list item with "b", then you need to indent it properly:
````
- a
  - b
    ```
    "a"

    b
    ```
````

The way you've written it, pandoc is interpreting the triple backticks as a "lazy" continuation of the list item "b".

So, no bug really.  Commonmark treats this differently, but this is an edge case and can be avoided by clearly marking the syntax as noted above.  Eventually we'll switch over to commonmark in the main parser, but if you want that now you can just use `-f commonmark`.

**Comment by JasonGross** [comment]
Ah, great, thanks!  Indenting sounds like a good solution
