### ISSUE TITLE
Selectively disable typographic ligatures in LuaLaTeX

### ISSUE THREAD

**Issue by fkohrt** [jgm/pandoc#6534]
[English](https://github.com/mrkline/modern-latex/blob/ac485ba/fonts.tex#L219-L225) and [German](http://mirrors.ctan.org/macros/latex/contrib/tudscr/doc/tutorials/treatise.pdf#subsection.11.3) introductions to typography mention that some words must not contain ligatures at certain points, such as

- shel**ff**ul
- Kau**fl**eute

(illegal ligature in **strong emphasis**)

In LaTeX, one would either have to manually disable them with `\kern0pt` or `\hspace{0pt}`(such as `shelf{\kern0pt}ful`), or use `microtype` to [disable them globally](https://texfragen.de/ligatur#global).

However, there's a LuaLaTeX package that does this automatically for an included selection of words: `selnolig`. According to [`selnolig`'s documentation](http://mirrors.ctan.org/macros/luatex/latex/selnolig/selnolig.pdf#subsection.2.3), it has to be loaded after the `babel` package. Therefore, just using `header-includes` is not feasible, as that's located [before](https://github.com/jgm/pandoc-templates/blob/70a4509/default.latex#L324-L336).

Hence I suggest loading the `selnolig` package in case the LuaLaTeX engine is used, probably somewhere after [line 341](https://github.com/jgm/pandoc-templates/blob/70a4509/default.latex#L341) of the LaTeX template:

```diff
--- pandoc-templates/default.latex	2020-07-15 00:28:58.124000000 +0200
+++ -	2020-07-15 00:31:00.189391730 +0200
@@ -339,6 +339,9 @@
 $endif$
 \fi
 $endif$
+\ifluatex
+  \usepackage{selnolig} $-- @template
+\fi
 $if(dir)$
 \ifxetex
   % Load bidi as late as possible as it modifies e.g. graphicx
```

**Comment by mb21** [comment]
you can probably use a [custom template](https://pandoc.org/MANUAL.html#templates)?

**Comment by fkohrt** [comment]
Oh yeah, I'm doing that. But I thought this might improve the default template; in a similar way everybody could load `microtype` themself, but instead it's been added to the default template.

**Comment by jgm** [comment]
My only worry here is about depending on packages that aren't widely available.  We try to stick with the most common ones so the default template will work with a more minimal install.

**Comment by jgm** [comment]
Still, I think this is probably a good idea.

**Comment by jgm** [comment]
I tried this. Maybe I'm doing it wrong, but I can't see any difference in the output (e.g. for Auflage in German). I still see a ligature.

**Comment by fkohrt** [comment]
Maybe you haven't set the `lang`uage?

Running `pandoc --standalone --from=markdown --to=latex --pdf-engine=lualatex --output=with-selnolig.pdf --template=default.latex test.md` on the patched `default.latex` and the following `test.md` works for me:

```markdown
---
title: Test
lang: de
---

Auflage
```

Compare this with `pandoc --standalone --from=markdown --to=latex --pdf-engine=lualatex --output=without-selnolig.pdf test.md`

**Comment by jgm** [comment]
I did set lang.  But I forgot to specify lualatex!

**Comment by fkohrt** [comment]
Shouldn't the [`selnolig`](https://ctan.org/pkg/selnolig) package be also mentioned in the [MANUAL](https://pandoc.org/MANUAL.html#creating-a-pdf), now that it's used in the template?

**Comment by jgm** [comment]
Good thought, I added something.
