### ISSUE TITLE
Support YAML metadata block in gfm

### ISSUE THREAD

**Issue by abitrolly** [jgm/pandoc#6537]
As explained in https://github.com/jgm/pandoc/issues/2827#issuecomment-658921843 the `gfm` format specifier doesn't support YAML metadata blocks. This doesn't work currently.
```shell
pandoc mwe.md -f gfm+yaml_metadata_block -o mwe.pdf
```
The workaround for now is to use deprecated `markdown_github` format specifier.
```
pandoc mwe.md -f markdown_github+yaml_metadata_block -o mwe.pdf
```

<details>
  <summary>✗ pandoc -v</summary>

```bash
pandoc 2.7.3
Compiled with pandoc-types 1.17.6.1, texmath 0.11.3, skylighting 0.8.2.1
Default user data directory: /home/anatoli/.local/share/pandoc or /home/anatoli/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
</details>

**Comment by craigbarnes** [comment]
GitHub has had special rendering for YAML metadata for several years already, so it may even make sense for `yaml_metadata_block` to be a part of the base `gfm` format.

**Comment by caressofsteel** [comment]
I can't think of any good reason not to support this. I wasted an hour or two trying to figure out why the YAML was being spit as part of the PDF before I stumbled upon the workaround.

**Comment by tarleb** [comment]
I think the merits of this request are undisputed. What's missing is the
contributor power to make it happen.

**Comment by abitrolly** [comment]
@taleb so the task is to find the code for `yaml_metadata_block` and merge it into `gfm` to make it the default behavior? Or the task is to fix behavior of compound format specifier `gfm+yaml_metadata_block`?

**Comment by tarleb** [comment]
GitHub Flavored Markdown is a variant of CommonMark and pandoc uses the commonmark-hs library for parsing it. The challenge is to add YAML support there. The repo is <https://github.com/jgm/commonmark-hs>.

**Comment by tarleb** [comment]
See also https://github.com/jgm/commonmark-hs/issues/17

**Comment by jgm** [comment]
This is a bit more complicated than the average commonmark extension, because here we need to parse the YAML into a YAML object, and then parse the terminal nodes as commonmark.  I have to think about the best way to handle this.

**Comment by shiftybit** [comment]
In the mean time, is there any way to hide the metadata block from the output? For my purposes, just discarding it is fine.

**Comment by jgm** [comment]
Your best bet is probably to preprocess the input and strip it off before passing to pandoc.
An alternative approach would be to use pandoc's markdown instead of gfm as your input format.

**Comment by shiftybit** [comment]
Ended up doing this
```python3
from pandocfilters import toJSONFilter
incomment = False
firstLine = True

def comment(k, v, fmt, meta):
	global incomment
	global firstLine
	if(firstLine and k == 'HorizontalRule'):
		incomment = True
		firstLine = False
		return []
	elif(incomment and k == 'HorizontalRule'):
		incomment = False
		return []

	if incomment:
		return []  # suppress anything in a header

if __name__ == "__main__":
	toJSONFilter(comment)
```
