### ISSUE TITLE
asciidoctor images

### ISSUE THREAD

**Issue by docsAsCode** [jgm/pandoc#6538]
In asciidoc (or asciidoctor) format we can use two kind of images : inline or block.
inline image syntax is : 
```
Click image:icons/play.png[Play, title="Play"] to get the party started.
```

block image syntax is (double `:`) : 
```
image::sunset.jpg[Sunset]
```

block image can be considered as figure in other language (rst, docbook).

In pandoc 2.10 only inline image is generated. Like you generate figure in rst or docbook, can you generate block image in asciidoc ?

Thx

**Comment by mb21** [comment]
hm... and how should we decide whether to render inline or block?

**Comment by jgm** [comment]
We can do what we do in other formats.
If the image is the only element in a Para, and has a title beginning with the prefix `fig:`, then we render it as a figure, stripping the prefix from the title.

**Comment by kukimik** [comment]
Hello! I'd be happy to work on this issue. The change to make looks rather easy and isolated, but I'm new to pandoc and want to understand what's going on here, so this may take me a while.

**Comment by tarleb** [comment]
Great! Don't hesitate to reach out if you have questions or run in to problems.

**Comment by argent0** [comment]
@kukimik  I made the pull-request before seeing your claim. Sorry

**Comment by kukimik** [comment]
@argent0 That's ok. I'll find myself another issue to work on. :wink:

**Comment by docsAsCode** [comment]
Hello,

Happy to see the progress for my issue.

I forget to say block images support horizontal alignement: 

`image::sunset.jpg[Sunset,align=center]`

**Comment by tarleb** [comment]
It may be better to raise this as a new issue once this one is closed.
