### ISSUE TITLE
LaTeX: Support `arara` compilation tool as pdf engine

### ISSUE THREAD

**Issue by Delanii** [jgm/pandoc#6540]
I would like to ask, whether is it possible to support `arara` compilation tool as `pdf engine` in `pandoc`.
For those who are not familiar with it, it is an CLI application, that compiles given `.tex` file according to
directives written in the file itself or supported by configuration file.

Example:

file `test.tex`:
```
% arara: lualatex
% arara: lualatex

\documentclass{article}

\begin{document}
\tableofcontents
\clearpage

\section{Section 1}
Just to provide source that requires to compilation in order to generate table of contents.

\clearpage

\section{Section 2}
blank
\end{document}
```

Compilation command is simply as:

```
arara test.tex
```

Supporting this tool would be helpfull for those users, that write documents with many compilation steps or use more "arcane" tex processing tools (`pythontex`, `perltex` - my case).
This could be implemented in form of specific block in `.md` source, or could be provided in separate file. For other source files than `tex`, `latex` or `context` this could be ignored with information, that use of filters or extensions is encouraged to achieve conversion.
`arara` is part of TeXlive and MikTeX distributions. For complete reference, please visit:

[https://ctan.org/pkg/arara](https://ctan.org/pkg/arara)

Thank you in advance for reply, regards Tomas

**Comment by tarleb** [comment]
Interesting suggestion, but I think I don't fully understand the benefits of arara over latexmk in the context of pandoc. Is the purpose is to have a central place to configure the build? If so, maybe a pandoc *defaults* file would work?

**Comment by Delanii** [comment]
Oh, for me this is a little blast from the past :)

Well, the use case was that I believe that some edge-case processing tools as mentioned above are hard to incorporate with `latexmk`, but pretty trivial with `arara` (even I was "mostly alone" able to do that), and also to bring more alternatives to `latexmk` (I personally never understood its documentation).

Later on, I have ended up using emacs, babel, GNU make and arara to do what I wanted, so this is probably mostly suggestion originating from personal preference and affinity to creating more options when there is (mostly) one.

Defaults file could also be used (eventhough I am not sure now if it allows to state more than one compilation step, but you will know :) ), but `arara` allows for some crazy things like conditional compilation and other shenanigans, that I dont think are supported in defaults file.

But, actually, all of this is possible by simply using specific arara configuration file (per-project or central basis) that sets things up, so this request might be off-topic. I am not requesting it adamantly and I also dont have the skills to implement it, so feel free to close this issue as "superseeded" ... :D

Regards, Tomas

**Comment by tarleb** [comment]
> Oh, for me this is a little blast from the past :)

Yeah, sorry. I'm just now combing through old issues that got lost somehow.

I think I'll close this, but add a note to #6126, so we can still consider this.
