### ISSUE TITLE
Move PandocError into the pandoc-types package

### ISSUE THREAD

**Issue by ddssff** [jgm/pandoc#6545]
It would be a convenience for me to have access to the PandocError type in the pandoc-types package, because I don't include the full pandoc in the client side of our web application, but I want to be able to transmit PandocError values to the client.

**Comment by jgm** [comment]
pandoc-types is devoted to defining the document structure, so I don't really think it makes sense to put PandocError there.

**Comment by tarleb** [comment]
Relevant: #6215
