### ISSUE TITLE
Demo 37 doesn't work

### ISSUE THREAD

**Issue by asatarov** [jgm/pandoc#6548]
pandoc version 2.10 

On demo page (https://pandoc.org/demos.html)  there is an example:

37. Using a template to produce a table from structured data:
pandoc fishwatch.yaml -t rst --template fishtable.rst -o fish.rst # see also the partial species.rst

Just copied all files content and run the given command. Result file contains only table header.

**Comment by jgm** [comment]
Did you copy over the partial, species.rst, as well?

**Comment by jgm** [comment]
Those results are generated automatically by running the command, so I know it works.

**Comment by jgm** [comment]
I also tried downloading the files and verified that it works.

**Comment by asatarov** [comment]
> Did you copy over the partial, species.rst, as well?

Yes I do.

May be I do something wrong, bu it doesn't work for me:

```sh
user@cmp:/mnt/c/tmp$ pandoc --version
pandoc 2.10
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/user/.local/share/pandoc or /home/user/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
user@cmp:/mnt/c/tmp$ ll
total 432
drwxrwxrwx 1 root root   4096 Jul 21 11:21 ./
drwxrwxrwx 1 root root   4096 Jul 20 17:22 ../
-rwxrwxrwx 1 root root    240 Jul 21 11:21 fish.rst*
-rwxrwxrwx 1 root root    448 Jul 20 17:04 fishtable.rst*
-rwxrwxrwx 1 root root 426116 Jul 20 17:02 fishwatch.yaml*
-rwxrwxrwx 1 root root     59 Jul 20 17:03 species.rst*
user@cmp:/mnt/c/tmp$ pandoc fishwatch.yaml -t rst --template fishtable.rst -o fish.rst
[WARNING] Could not deduce format from file extension .yaml
  Defaulting to markdown
user@cmp:/mnt/c/tmp$ cat fish.rst
+------------------+----------+-----------------------------------------------+
| Species          | Calories | Location                                      |
+==================+==========+===============================================+
user@cmp:/mnt/c/tmp$
```

**Comment by jgm** [comment]
Weird.  To diagnose, I'd try breaking things down.  First make sure this works:
```
pandoc  fishwatch.yaml -t native -s
```
This should tell you if pandoc is correctly parsing the yaml metadata.

**Comment by asatarov** [comment]
> Weird. To diagnose, I'd try breaking things down. First make sure this works:
> 
> ```
> pandoc  fishwatch.yaml -t native -s
> ```
> 
> This should tell you if pandoc is correctly parsing the yaml metadata.

I think this command works fine.

```
p$ pandoc  fishwatch.yaml -t native -s
[WARNING] Could not deduce format from file extension .yaml
  Defaulting to markdown
Pandoc (Meta {unMeta = fromList []})
[HorizontalRule
,CodeBlock ("",[],[]) "# Data from https://www.fishwatch.gov\nfish:\n- calories: 92\n  physical_description: |\n    -   Female shortfin squid range from 7 to 12 inches in mantle length,\n        while males are 7 to 10.6 inches in mantle length.\n    -   They can regulate their body color, but are primarily orange-colored\n        with a brown stripe that extends along the top side of the mantle.\n  human_health:\n  texture: Firm and meaty.\n 
.....
```

a long output shortened

**Comment by jgm** [comment]
No, this is the problem.  You should be getting metadata, not a code block, from fishwatch.yaml.
Open fishwatch.yaml.  You should see that it begins with
```
---
---
# Data from https://www.fishwatch.gov
fish:
```
and end with the line
```
...
```
If it doesn't, something got corrupted when you downloaded it.
