### ISSUE TITLE
Linebreaks in org mode

### ISSUE THREAD

**Issue by samhedin** [jgm/pandoc#6554]
First of all, thank you for pandoc! 

Following this: https://groups.google.com/g/pandoc-discuss/c/hhLqIuBwowQ/m/NFIgfX-BBQAJ
I have solved the issue of `Space` leading to linebreaks by replacing them with `Str " "`, but I have not figured out what to do about the extra linebreaks after headers. As you can see in the image in the linked discussion, these additional linebreaks can take up quite a bit of extra space if you have a lot of headers.

## Example `pandoc test.html -o test.org`
**Input test.html**
``` html
<h1>I am a header</h>
<p>I am some text</p>
```
**Observed test.org**
``` org
* I am a header
  :PROPERTIES:
  :CUSTOM_ID: i-am-a-header
  :END:

I am some text
```

**Expected test.org**
``` org
* I am a header
  :PROPERTIES:
  :CUSTOM_ID: i-am-a-header
  :END:
I am some text
```

## Example `pandoc test.md -o test.org`
**test.md**
``` markdown
# I am a header
I am some text
```
**Observed test.org**
``` org
* I am a header
  :PROPERTIES:
  :CUSTOM_ID: i-am-a-header
  :END:

I am some text
```
**Expected test.org**
``` org
* I am a header
  :PROPERTIES:
  :CUSTOM_ID: i-am-a-header
  :END:
I am some text
```

``` bash
$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/sam/.local/share/pandoc or /home/sam/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by samhedin** [comment]
This also happens when converting from at least markdown, and there is another thing I noticed:
## Example `pandoc test.md -o test.md`
**Input**
``` markdown
I am a header
=============
I am some text
```
**Observed output**
``` markdown
I am a header
=============

I am some text
```

**Expected output**
*see original*

**Comment by archiif** [comment]
I have a similar issue with line breaks when trying to convert opml to org, where the linebreak between every single heading gets doubled. 
Here's an example of the opml file I was dealing with (they were exported from Workflowy, an outliner similar to Dynalist):
https://github.com/archiif/random/raw/master/workflowy-export%20(4).opml
Is this issue relevant to mine, or should I open a different one?

**Comment by tarleb** [comment]
The underlying cause for this is the same as far as I can tell, no need
for a separate issue.

**Comment by tarleb** [comment]
I'd like to stress that this is not a bug, as both styles are valid and
share the same semantics. But I believe that the proposed style is more
common and thus preferable.
