### ISSUE TITLE
Markdown (gfm) to MediaWiki: unexpected results (using HTML) with indented source code

### ISSUE THREAD

**Issue by OliverO2** [jgm/pandoc#6556]
Version: `pandoc-nightly-linux-2020-07-22`
```
pandoc 2.10
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
```

Markdown input:
```markdown
#### Example 1

1. Point 1
    ```bash
    date
    pwd
    ```
1. Point 2
    ```bash
    pwd
    date
    ```
```

Command like: `pandoc --from=gfm --to=mediawiki`

Actual MediaWiki output:
```text
==== Example 1 ====

<ol style="list-style-type: decimal;">
<li>Point 1
<source lang="bash"> date
 pwd</source></li>
<li>Point 2
<source lang="bash"> pwd
 date</source></li></ol>
```

Expected output:
```text
==== Example 1 ====

# Point 1<source lang="bash">date
pwd
</source>
# Point 2<source lang="bash">pwd
date
</source>
```

**Comment by jgm** [comment]
Really two issues here -- one concerns the space at the beginning of the code lines, which seems a bug in commonmark-hs (and is not present when you use the released version, which uses a wrapper around cmark).

The other issue is the use of HTML to render the list.  This is done for lists which have a structure that pandoc believes can't be represented in pure mediawiki.  Perhaps that is incorrect in this case and the heuristic could be improved.

**Comment by OliverO2** [comment]
Would be great if pandoc would use MediaWiki's capability to display indented code blocks. I could not find a proper workaround to avoid the HTML fallback. Removing indentation from code blocks in the input always broke the list structure.

**Comment by jgm** [comment]
I think I'm going to call this fixed.
The indentation issue is solved:
```
==== Example 1 ====

<ol style="list-style-type: decimal;">
<li>Point 1
<source lang="bash">date
pwd</source></li>
<li>Point 2
<source lang="bash">pwd
date</source></li></ol>
```
You still get HTML tags which is perhaps not fully idiomatic, but this renders correctly in mediawiki's sandbox.  And in general, we need to resort to such tags when list items are not a simple paragraph but a sequence of block-level items.

**Comment by OliverO2** [comment]
You are right that the HTML renders correctly. There is a downside in usability: MediaWiki's [VisualEditor](https://www.mediawiki.org/wiki/Extension:VisualEditor) normally accepts inserting MediaWiki source code via copy&paste. Once an HTML segment is present, VisualEditor will not insert anything at all.

**Comment by OliverO2** [comment]
After some additional testing it seems that the current version of MediaWiki's VisualEditor handles the mix of MW markup and HTML quite well. So pandoc's current behavior seems good enough. Thanks!
