### ISSUE TITLE
missing metadata with wkhtmltopdf

### ISSUE THREAD

**Issue by aflueckiger** [jgm/pandoc#6558]
When converting files with `wkhtmltopdf`, the metadata is not propagated to the resulting pdf.

To reproduce the issue, try: 

```
pandoc -t html5 -s in.md -o out.pdf \
--css css/style.css \
-V title-meta="test"
```

Versions:
`wkhtmltopdf 0.12.5`
`pandoc 2.9.2.1`

On the opposite, converting markdown files directly into pdf works as expected:

```
pandoc -s in.md -o out.pdf \ 
-V title-meta="test"
```

The circumvention of `wkthtmltopdf` above is not an option since css styling is no longer possible. 
I guess the missing metadata is due to a lacking implementation rather than a bug. If I am wrong, please correct me.

**Comment by mb21** [comment]
you're looking for the title as part of the PDF metadata? if so, you'd need to pass that option to wkhtmltopdf

```
pandoc -t html5 -s in.md -o out.pdf \
--pdf-engine-opt='--title test'
```

it's something pandoc could be change to do itself probably..

**Comment by aflueckiger** [comment]
Yes, I would like to set the PDF metadata using pandoc. Besides title, there is a need for author, keywords and date as well. However, it seems that wkhtmltopdf still lacks this functionality: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2000

Moreover, I couldn't get your example work:
```
pandoc -t html5 -s in.md -o out.pdf \
--pdf-engine-opt='--title test'
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'letter' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
Unknown long argument --title "test"
...
```

**Comment by mb21** [comment]
ah sorry, probably it's:

   --pdf-engine-opt='--title' --pdf-engine-opt='test'

**Comment by jgm** [comment]
If wkhtmltopdf lacks the functionality, then I don't see any way to improve things in pandoc.
Should this be closed?

**Comment by mb21** [comment]
wkhtmltopdf can set the title, but not other metadata like author...

**Comment by aflueckiger** [comment]
Currently, there is no way to improve as `wkhtmltopdf`lacks the functionality to set all metadata. Use `exiftool` instead.
