### ISSUE TITLE
How will a Lua filter identify the Platform or the "Lua Environment" it is running on.

### ISSUE THREAD

**Issue by kjambunathan** [jgm/pandoc#6559]
**How will a Lua filter identify the Platform or the "Lua Environment" it is running on**

Here is the usecase for the request.  

One of Better BibTex's Lua filter worked when running on  Pandoc 2.9/MacOS but failed when working on Pandoc 2.9/Debian.  (We aren't sure about the minor versions).  We feel merely checking for `PANDOC_VERSION` and `PANDOC_API_VERSION` wouldn't work.  We feel that having access to the platform--Mac or Debian--will help add suitable checks.

Please advise us what to do. (cc. @retorquere)

cf, https://github.com/jgm/pandoc/issues/6557
 cf. https://github.com/retorquere/zotero-better-bibtex/issues/1581

**Comment by retorquere** [comment]
I've since been advised that 2.9.2 was the version that introduced inlines.

**Comment by jgm** [comment]
Was it the same pandoc version (e.g. 2.9.2 in both cases)?  Or just 2.9.x?  As @retorquere notes, there were differences in the lua apa in 2.9.2.

To determine the OS from a lua script, see https://stackoverflow.com/questions/295052/how-can-i-determine-the-os-of-the-system-from-within-a-lua-script

**Comment by retorquere** [comment]
I can't tell anymore, sorry - I upgraded pandoc via homebrew to make sure 2.10 would still work. My Linux system is also on 2.10

**Comment by retorquere** [comment]
I'm also going to see if I can go without Inlines - I think I can.

**Comment by tarleb** [comment]
See also https://pandoc.org/lua-filters.html#pandoc.system.os
