### ISSUE TITLE
Feature request: more general support for literate programming/reproducible research

### ISSUE THREAD

**Issue by michelk** [jgm/pandoc#656]
I am looking for a `pandoc`-preprocessor in spirit of `org-mode`/`babel` (as
described in  [A Multi-Language Computing Environment for Literate Programming
and Reproducible Research](http://www.jstatsoft.org/v46/i03)), but much more
lightweight and based on `markdown`/`rst`. 

`org-mode` is very very powerful; [knitr](https://github.com/yihui/knitr) does already a good job, is
more lightweight but pretty focused on `R`, although you could mix-in other
languages as well. 

Anyway it would be nice to have a general lightweight "literate
programming"/"reproducible research" `pandoc`-preprocessor. 

I guess the challenge is to unify the existing plugins, extend them to other
languages and finding a proper syntax how to handle/evaluate the code-chunks.
## Existing plugins

I know there are already some separate plugins around for
- [tikz](https://github.com/sdiehl/cats.git)
- [dot](http://gitit.net)
- [ghci](http://byorgey.wordpress.com/blogliterately/)
- [diagrams](http://byorgey.wordpress.com/blogliterately/)
## Existing syntax for code-chunks

Existing "reproducible research"-tools do it like that: 
### knitr with markdown

``````
```{r chunk-tag, <options>}
<body>
```
``````

where `<options>` is valid R-code, describing how to handle the chunk. 

For example you could state: 

```
echo = TRUE                  # code is printed
eval = TRUE                  # code is evaluated
results = 'asis'             # how to show the results; could also be 'hide' or 'markup'
engine = 'R'                 # which engine to use to process the chunk
dev = 'pdf'                  # output device of figures
fig.{cap,width,height} = ... # if code generates a figure
...
```
### org-mode

```
#+begin_src <engine> <options>
  <body>
#+end_src
```

where <options> controls how to handle the chunk: eg 

```
:eval no
:export none
...
```
## Afterthoughts 

I am not sure if a subset of `org-mode` really makes sense. But in the same way
you could argue with `latex` vs `markdown`. But the nice thing about `pandoc` is
the opportunity to scale your documentation language according to your needs.

**Comment by sdbbs** [comment]
Not wanting to reopen the issue - I was just wondering about this:

> The general pattern for plugins, literate programming and reproducible research is to embed it in code sections with [fenced code blocks](http://johnmacfarlane.net/pandoc/README.html#fenced-code-blocks) attributes:
> 
> ```
> ```{.foo <options>}
> <body>
> ```
> ```
> 
> If `foo` (the name of the first class) is a known plugin, then options and body are passed to the plugin and the result is used by Pandoc. WIth Pandoc extension `inline_code_attributes` one can also use it inline. For instance one could use a plugin that includes othr markdown files:
> 
> ```
> `chapter1.md`{.include}
> ```
> 

I was wondering whether there was an existing Pandoc plugin/filter for this, and it turns out, there is - https://pandoc.org/lua-filters.html#converting-abc-code-to-music-notation
