### ISSUE TITLE
Unexpected line break when converting org to markdown

### ISSUE THREAD

**Issue by Brethland** [jgm/pandoc#6561]
I shall thank you for creating pandoc such a nice tool.

When I tried to convert a Org-mode file including Chinese and English at the same time(with UTF-8 encoding) to markdown file, I find that it contains unexpected line breaks between English words. Here is an example which can be reproduced:

#### Input
```org
测试测试测试测试测试测试测试测试测试测试测试 Fransisco TEST，测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试
```

#### Expected Output
```markdown
测试测试测试测试测试测试测试测试测试测试测试 Fransisco TEST，测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试
```

#### Output
```markdown
测试测试测试测试测试测试测试测试测试测试测试 Fransisco
TEST，测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试
```

#### Command
```shell
$ pandoc -s .\test.org -o .\test.md
```

#### Pandoc Version
```shell
pandoc.exe 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
```

**Comment by mb21** [comment]
Try the `--wrap=none` option...
Yes, personally, I feel this should be the default as well... but I think @jgm disagrees :-)

**Comment by Brethland** [comment]
> Try the `--wrap=none` option...
> Yes, personally, I feel this should be the default as well... but I think @jgm disagrees :-)

Thank you! It has fixed my problems now.
