### ISSUE TITLE
Height/scale inversion in rst image reader

### ISSUE THREAD

**Issue by docsAsCode** [jgm/pandoc#6566]
Hello,

When you convert a rst with image directive, height and scale are not properly red.

An example here with pandoc 2.10.1 : https://pandoc.org/try/?text=..+image%3A%3A+picture.jpeg%0A+++%3Aheight%3A+100px%0A+++%3Awidth%3A+200px%0A+++%3Ascale%3A+50%25%0A+++%3Aalt%3A+alternate+text%0A+++%3Aalign%3A+right%0A+++%3Atarget%3A+google.com&from=rst&to=native&standalone=0

Thx

**Comment by jgm** [comment]
Looks right to me.
Original has
```
   :height: 100px
   :width: 200px
   :scale: 50%
```
Pandoc has
```
[("width","100px"),("height","50px")])
```
Note: 100px is 50% of 200px and 50px is 50% of 100px.

**Comment by docsAsCode** [comment]
OK during conversion, pandoc apply scale indice. I think height,width and scale will be preserved in properties.
Sorry.
