### ISSUE TITLE
 _Additional _ user-defined variables created in `Meta` doesn't show up in `Pandoc` function later.  i.e., In ODT context, the meta.xml doesn't contain these _additonal_ user variables

### ISSUE THREAD

**Issue by kjambunathan** [jgm/pandoc#6570]
## Attachment

[meta.xml-bug.zip](https://github.com/jgm/pandoc/files/4989006/meta.xml-bug.zip)

## start in a tmp dir

~$ cd tmp/

## unzip the attachment and place it in tmp

~/tmp$ unzip meta.xml-bug.zip 

Archive:  meta.xml-bug.zip
   creating: meta.xml-bug/
  inflating: meta.xml-bug/works.lua  
  inflating: meta.xml-bug/Makefile   
  inflating: meta.xml-bug/doesnotwork.lua  

## Do a `make`

~/tmp/meta.xml-bug$ make 

Just look at what is shown on the screen.   I have attached a `make` transcript at the end of this bug.  Here is what the above set of files do (or don't do)

---------

In the `works.lua` case, the 

```
$ cat works.lua        

function Meta(meta)
  meta.AAAAAAAAAAAAAAAA='BBBBBBBBBBBBBBBB'
  return meta
end
```
the resulting `works.odt:meta.xml` has the above LibreOffice user variable

```
    <dc:date>2020-07-28T14:40:33Z</dc:date>
    <meta:user-defined meta:name="AAAAAAAAAAAAAAAA" meta:value-type="string">BBBBBBBBBBBBBBBB</meta:user-defined>
  </office:meta>
```
This is good.

But in the `doesnotwork.lua` case, the 

```
$ cat doesnotwork.lua        

function Meta(meta)
  meta.AAAAAAAAAAAAAAAA='BBBBBBBBBBBBBBBB'
  return meta
end

function Pandoc(doc, meta)

  table.insert(doc.blocks, 1, pandoc.RawBlock('opendocument', "<text:p>Hello World</text:p>"))
  table.insert(doc.blocks, pandoc.RawBlock('opendocument', "<text:p>Good Bye!</text:p>"))
  
  return pandoc.Pandoc(doc.blocks, meta)
end
```

the `doesnotwork.odt:content.xml` has `Hello World` and `Good Bye!` added to body text.  This is good. 

```
$ cat content.xml | tail

<office:text>
<text:p>Hello World</text:p>
<text:p text:style-name="Text_20_body">Body text</text:p>
<text:p>Good Bye!</text:p>
</office:text>

```

but ... **the `meta.xml` doesn't have the LibreOffice Vairable.  This I consider as a bug.**

```
$ cat meta.xml | tail

    <meta:creation-date>2020-07-28T14:40:33Z</meta:creation-date>
    <dc:date>2020-07-28T14:40:33Z</dc:date>
  </office:meta>

```

The two `lua` files, differ only in the presence/absence of `function Pandoc`, and in that function I only modify the blocks, but return the incoming `meta` variable as such.  

The `lua-filters.md` says that 

```
Lua filter functions are run in the order

> *Inlines → Blocks → Meta → Pandoc*.
```
So,  in my test case, **I expect the `Pandoc` function  to receive the (clone of?)  _augmented_ `meta`.  But it doesn't.**

## Transcript of a `make` session

**I am adding this only for the sake of completion.  You can skip this part if you _get_ what I _meant_ in the previous paragraphs.

~/tmp/meta.xml-bug$ make 

```
rm -f *.odt *.xml

---------------- works.lua ----------------
cat works.lua        
function Meta(meta)
  meta.AAAAAAAAAAAAAAAA='BBBBBBBBBBBBBBBB'
  return meta
end
---------------- works.lua ----------------

echo "Body text" | pandoc -L works.lua -f markdown -o works.odt
unzip works.odt content.xml meta.xml
Archive:  works.odt
  inflating: meta.xml                
  inflating: content.xml             
cat content.xml | tail
  <office:automatic-styles>
    <style:style style:name="fr2" style:family="graphic" style:parent-style-name="Formula"><style:graphic-properties style:vertical-pos="middle" style:vertical-rel="paragraph-content" style:horizontal-pos="center" style:horizontal-rel="paragraph-content" style:wrap="none" /></style:style>
    <style:style style:name="fr1" style:family="graphic" style:parent-style-name="Formula"><style:graphic-properties style:vertical-pos="middle" style:vertical-rel="text" /></style:style>
  </office:automatic-styles>
<office:body>
<office:text>
<text:p text:style-name="Text_20_body">Body text</text:p>
</office:text>
</office:body>
</office:document-content>
cat meta.xml | tail
    <dc:description></dc:description>
    <dc:subject></dc:subject>
    <meta:keyword></meta:keyword>
    <meta:initial-creator></meta:initial-creator>
    <dc:creator></dc:creator>
    <meta:creation-date>2020-07-28T14:40:33Z</meta:creation-date>
    <dc:date>2020-07-28T14:40:33Z</dc:date>
    <meta:user-defined meta:name="AAAAAAAAAAAAAAAA" meta:value-type="string">BBBBBBBBBBBBBBBB</meta:user-defined>
  </office:meta>
</office:document-meta>rm -f *.odt *.xml
rm -f *.odt *.xml

---------------- doesnotwork.lua ----------------
cat doesnotwork.lua        
function Meta(meta)
  meta.AAAAAAAAAAAAAAAA='BBBBBBBBBBBBBBBB'
  return meta
end

function Pandoc(doc, meta)

  table.insert(doc.blocks, 1, pandoc.RawBlock('opendocument', "<text:p>Hello World</text:p>"))
  table.insert(doc.blocks, pandoc.RawBlock('opendocument', "<text:p>Good Bye!</text:p>"))
  
  return pandoc.Pandoc(doc.blocks, meta)
end
---------------- doesnotwork.lua ----------------

echo "Body text" | pandoc -L doesnotwork.lua -f markdown -o doesnotwork.odt
unzip doesnotwork.odt content.xml meta.xml
Archive:  doesnotwork.odt
  inflating: meta.xml                
  inflating: content.xml             
cat content.xml | tail
    <style:style style:name="fr1" style:family="graphic" style:parent-style-name="Formula"><style:graphic-properties style:vertical-pos="middle" style:vertical-rel="text" /></style:style>
  </office:automatic-styles>
<office:body>
<office:text>
<text:p>Hello World</text:p>
<text:p text:style-name="Text_20_body">Body text</text:p>
<text:p>Good Bye!</text:p>
</office:text>
</office:body>
</office:document-content>
cat meta.xml | tail
    <dc:title></dc:title>
    <dc:description></dc:description>
    <dc:subject></dc:subject>
    <meta:keyword></meta:keyword>
    <meta:initial-creator></meta:initial-creator>
    <dc:creator></dc:creator>
    <meta:creation-date>2020-07-28T14:40:33Z</meta:creation-date>
    <dc:date>2020-07-28T14:40:33Z</dc:date>
  </office:meta>
</office:document-meta>rm -f *.odt *.xml
```

**Comment by kjambunathan** [comment]
I would appreciate if you could the two recipes in this bug report to your manual.

The recipe 1 tells how to add extra user variables.

The recipe 2 tells how to add extra text at the beginning and end of body text.

In the recipe, I use "plain text" `Hello World` and `Good Bye`.  If  they are raw XML then the corresponding blocks have to be generated like so.  Note the use of `opendocument` `pandoc.RawBlock`.  


----

**You can skip stuff here ... This is for the benefit who may hit this forum for solution to problems they may be having.**

The recipe adds the secret sauce for bibliography to a `refs` Div, and when there is none it is added to the secret sauce goes towards the end of the file.

```

local function zotero_bibl()
  if (not string.match(FORMAT, 'odt')) or config.csl_style == '' then return '' end

  local docprefs = '{&quot;uncited&quot;:[],&quot;omitted&quot;:[],&quot;custom&quot;:[]}'

  return string.format(
    '<text:section text:name=" %s">'
      .. '<text:p text:style-name="Bibliography_20_1">'
      .. 'Please refresh'
      .. '</text:p>'
      ..'</text:section>',
    'ZOTERO_BIBL ' .. docprefs .. ' CSL_BIBLIOGRAPHY' .. ' RND' .. utils.random_id(10))
end


local hasbibliography=false
function Div(div)
  if not div.attr or div.attr.identifier ~= 'refs' then
    return nil
  end

  hasbibliography=true
  if string.match(FORMAT, 'odt') then
    return pandoc.RawBlock('opendocument', zotero_bibl())
  end
end

function Pandoc(doc)
  if not hasbibliography then
    table.insert(doc.blocks, pandoc.RawBlock('opendocument', zotero_bibl()))
  end
  return pandoc.Pandoc(doc.blocks)
end
---

**Comment by jgm** [comment]
@tarleb can you see what's going on here?

**Comment by kysko** [comment]
He was mixing two kinds of notations.
This works:
```
function Pandoc(doc)
  table.insert(doc.blocks, 1, pandoc.RawBlock('opendocument', "<text:p>Hello World</text:p>"))
  table.insert(doc.blocks, pandoc.RawBlock('opendocument', "<text:p>Good Bye!</text:p>"))
  return pandoc.Pandoc(doc.blocks, doc.meta)
end
```

**Comment by tarleb** [comment]
Thanks for the excellent report @kjambunathan. The analysis by @kysko is spot on: Filter functions are always called with the element as a single argument, additional parameters are initialized with `nil`, so `meta` in function `Pandoc` is always nil. Calling `pandoc.Pandoc(doc.blocks, nil)` will result in a document without metadata.

Thanks for pointing out the faulty example, going to fix that right away.

**Comment by kjambunathan** [comment]
> return pandoc.Pandoc(doc.blocks, doc.meta)

This resolves my issue.  Thanks.

Btw, [sample.lua#78](https://github.com/jgm/pandoc/blob/1e1c5e7f4ca46676fe8bbdd7545369220b71e9a3/data/sample.lua#L78) requires revision too.

**Comment by kjambunathan** [comment]
> ["Extracting information about links"](https://pandoc.org/lua-filters.html#extracting-information-about-links)

Compare that example with my own.  Specifically, the line that returns the final Doc.

Compare this

```
  return pandoc.Doc(
    {pandoc.Table(caption, aligns, widths, headers, rows)},
    meta
  )
```

with my

```
function Pandoc(doc)
  table.insert(doc.blocks, 1, pandoc.RawBlock('opendocument', "<text:p>Hello World</text:p>"))
  table.insert(doc.blocks, pandoc.RawBlock('opendocument', "<text:p>Good Bye!</text:p>"))
  return pandoc.Pandoc(doc.blocks, doc.meta)
end
```


My example has many advantages:

1.  It has less lines of code
2.  The essential aspect `pandoc.Pandoc(doc.blocks, doc.meta)` are immediately visible.
3.  Blocks--as paragraphs--are simple and easier to understand than the Tables are.
4. The usecase is simple:  Add a header and a footer dynamically (so to speak)

I _feel_ that my example will serve as a good sample example that _may_ precede the above cited example.  The only modification I will do my example is to replace 'ODT' with 'HTML'.  

I will send you a pull request in few minutes.

**Comment by kjambunathan** [comment]
I sent  you a PR for `lua-filters.md` a few minutes ago. 

I would appreciate if you could take this  issue to review [sample.lua#78](https://github.com/jgm/pandoc/blob/1e1c5e7f4ca46676fe8bbdd7545369220b71e9a3/data/sample.lua#L78).

**Comment by kjambunathan** [comment]
> > ["Extracting information about links"](https://pandoc.org/lua-filters.html#extracting-information-about-links)
> 
> Compare that example with my own, specifically, the line that returns the final Doc.

When I posted this comment, I didn't notice that you have already removed that example from the manual.  That example was detailed (in terms of length and semantics) to serve as quick starter.

**Comment by tarleb** [comment]
The main issue has been resolved. For better handling of tables in Lua, see #6571 and #6573. Closing in favor of these tickets.
