### ISSUE TITLE
--atx-headers error

### ISSUE THREAD

**Issue by hh02** [jgm/pandoc#6574]
heading 1 ~ 3 is correct, but heading 4~6 start not with `#'
![image](https://user-images.githubusercontent.com/57320088/88807590-7f7f0180-d1e4-11ea-9591-a46509c4515f.png)

## the pandoc version 
pandoc --version
pandoc.exe 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
## the exact command line used

`pandoc test.org -f org -t gfm --atx-headers test.md`

## the exact input used
``` org
* head 1
** head 2
*** head 3
**** head 4
***** head 5
****** head 6
```
## the output received
``` md
# head 2

## head 2

### head 3

1.  head 4

    1.  head 5

        1.  head 6

```

## the output you expected instead
``` md
# head 2

## head 2

### head 3

#### head 4

##### head 5

###### head 6

```

 @mb21

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by hh02** [comment]
pandoc --version
pandoc.exe 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5

**Comment by hh02** [comment]
the exact command line used:  
pandoc test.org -f org -t gfm --atx-headers  test.md

use other format such as markdown_github, markdown is the same error.

the exact input used:
* head 1
** head 2
*** head 3
**** head 4
***** head 5
****** head 6

the output received:
# head 2

## head 2

### head 3

1.  head 4

    1.  head 5

        1.  head 6

the output you expected instead:
# head 2

## head 2

### head 3

#### head 4

##### head 5

###### head 6

**Comment by mb21** [comment]
ah, you're talking about org-mode input...

this is intended, see https://github.com/jgm/pandoc/issues/5169

**Comment by hh02** [comment]
Many thanks for your time.

**Comment by tarleb** [comment]
See also https://pandoc.org/org.html
