### ISSUE TITLE
latest release does not export default templates

### ISSUE THREAD

**Issue by MaralWa** [jgm/pandoc#6580]
I just downloaded the latest binary release for Mac OS. After the installation I tried to export the default template for docx but pandoc could not find any template file.

Here is the output:

▶ pandoc --version
pandoc 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /Users/Sarah/.local/share/pandoc or /Users/Sarah/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

~
▶ pandoc -o pandoc_default.docx -D docx
Could not find data file templates/default.docx

**Comment by kysko** [comment]
see: https://pandoc.org/MANUAL.html#option--reference-doc

`pandoc -o custom-reference.docx --print-default-data-file reference.docx`

**Comment by MaralWa** [comment]
okay, that seems to work, but the manpage suggests a different aproach:

       -D FORMAT, --print-default-template=FORMAT
              Print  the  system default template for an output FORMAT.  (See -t for a list of possible
              FORMATs.) Templates in the user data directory are ignored.  This option may be used with
              -o/--output  to  redirect  output to a file, but -o/--output must come before --print-de-
              fault-template on the command line.

Maybe it's just a misunderstanding on my side. I always thougt reference documents and template are kind of the same.

**Comment by mb21** [comment]
template is a single plain text file. that doesn't work for docx (and similar formats), so that's why there is the reference file for them.
