### ISSUE TITLE
HTML writer: moving scripts to the end of documents

### ISSUE THREAD

**Issue by LaurentRDC** [jgm/pandoc#6582]
Hello,

It is good practice to place HTML `<script>` tags at the bottom of a document, as close to `</body>` as possible, to defer the parsing and execution of Javascript scripts. Otherwise, the loading of an HTML page can be halted until scripts are executed.

Users of `pandoc-plot` have brought forward (https://github.com/LaurentRDC/pandoc-plot/issues/9) that it would be helpful to them to move scripts generated by `pandoc-plot` to the bottom of the document. Right now, `pandoc-plot` uses deferred external scripts (`<script src="..." defer></script>`) as much as possible, but there is no elegant way to do this with inline scripts (although [dirty hacks](https://github.com/LaurentRDC/pandoc-plot/issues/9#issuecomment-667170377) work).

Would you be open to add an option to the HTML writer to move all scripts in `<body>` to the bottom, in order? Consider an example where the following command

```
pandoc -i doc.md -o page.html
```

results in this webpage:

```html
<!DOCTYPE html>
<html>
<body>
<script src="myscript.js"></script>

<p>Content</p>

<script>
    console.log("Hello world")
</script>

</body>
</html>
```

I'm thinking of a flag (e.g. `--defer-scripts`) that would instead result in:

```html
<!DOCTYPE html>
<html>
<body>

<p>Content</p>

<script src="myscript.js" defer></script>

<script>
    console.log("Hello world")
</script>
</body>
</html>
```

Given interest in this feature, I can put together a pull request.

**Comment by mb21** [comment]
how do you generate that? there is the include-after template variable...
https://github.com/jgm/pandoc/blob/master/data/templates/default.html5#L60

or you're thinking of scripts pandoc injects itself?

**Comment by LaurentRDC** [comment]
The `include-after` template variable is a good idea in general. 

However, when using `pandoc-plot`, scripts are injected by the filter by reading certain code blocks, executing them, and embedding the result. For interactive HTML + JS plots, the plot data will be injected as JS as well.

**Comment by mb21** [comment]
> and embedding the result

guess the filter could append that to the `include-after` metadata variable?

**Comment by LaurentRDC** [comment]
> or what exactly are you suggesting that pandoc should do? have an option that post-processes the AST and moves all js to the end? that sounds quite fragile (some js might break if executed in different order).

That was my suggestion, if there was general interest in this. Given that you have suggested an acceptable solution, I'll close this for now.

**Comment by mb21** [comment]
Yeah, unless I've been missing something, I think that's the best solution...
