### ISSUE TITLE
ICML Writer doesn't set SingleColumnWidth on a Column

### ISSUE THREAD

**Issue by lrosenthol** [jgm/pandoc#6585]
When outputting a simple table from Markdown to ICML, the widths fo the columns aren't set - so that the table ends up quite small in the final output.  

Given the following markdown
```
| Column 1 | Column 2 | Column 3 |
| -------- | -------- | -------- |
| Ut | ornare | lectus |
| sit amet | est placerat | in |
```

produces this table:

![image](https://user-images.githubusercontent.com/5074741/89131984-dcc5cc00-d4de-11ea-9beb-49a2de246b78.png)

**Comment by mb21** [comment]
This will actually depend on the markdown syntax you use for the table. Try `-t native`, to see that in pipe tables, there isn't any width info in the document AST. But using [grid tables](https://pandoc.org/MANUAL.html#extension-grid_tables) for example, it should work.

**Comment by lrosenthol** [comment]
I just tried that @mb21 with the following grid table

```
+----------+--------------+----------+
| Column 1 | Column 2 	  | Column 3 |
+==========|==============|==========|
| Ut 	   | ornare		  | lectus   |
| sit amet | est placerat | in 		 |
+----------+--------------+----------+
```

and the command line `pandoc -o sample-pdf.icml sample-pdf.md -s`

and it didn't even process the grid table - let it as plain text

![image](https://user-images.githubusercontent.com/5074741/89186447-ce70c200-d569-11ea-9d5b-199474d7b402.png)

**Comment by mb21** [comment]
yes, spaces work better for markdown... try `pandoc -t native` to see whether your markdown is wrong, or it's the ICML writer...

**Comment by lrosenthol** [comment]
It was a bad grid table - when I construct a real one - it works much better, thanks!

Closing this issue!
