### ISSUE TITLE
Pandoc's Markdown requires a newline after a paragraph for a list to render

### ISSUE THREAD

**Issue by nathanlesage** [jgm/pandoc#6590]
There is a (possibly very minor) issue that a user of Zettlr [has pointed out](https://github.com/Zettlr/Zettlr/issues/1143). I could confirm that this is Pandoc behavior and not introduced via Zettlr. I looked through the issue list, but the amount seemed daunting, so if I missed the right issue, I would like to apologize beforehand! Additionally, if the following is intended behaviour (I know that Pandoc supports both CommonMark and Pandoc Markdown output), I would also like to apologize for adding to the amount of work here.

The point of the matter is that if you create a list immediately following a paragraph with no blank line, the list will not be rendered, but in fact added to the paragraph as if it was simply a paragraph with hard wrapping.

## Test example

Write this (or something similar) into an empty Markdown document:

```markdown
# A test file

This should be a paragraph.
- This should be a list
- ... with two items.
```

Export it using `pandoc -o test.pdf test.md`

## Expected output

***

# A test file

This should be a paragraph
- This should be a list
- ... with two items.

***

## Actual output

# A test file

This should be a paragraph - This should be a list - ... with two items.

***

GitHub actually renders it as one might expect (the "expected output" is exactly the same as the test example).

While I personally think that it's "bad style" to not pad paragraph and list with a blank space, I am bringing this to your attention both because the [CommonMark 0.29](https://spec.commonmark.org/0.29/#lists) specification precisely mentions this case, and as Pandoc's Markdown also implements a lot of CommonMarks concepts (albeit I know that both are not exactly the same).

It would be great to either implement this in the default output (e.g. without specifying the specific Markdown format, hence Pandoc's Markdown) or give a short confirmation that this behaviour is indeed to be expected so that I can add corresponding documentation for my users.

Thank you very, very much for your work for this piece of software which indeed is, without exaggeration, the backbone of Zettlr.

## Additional information

* Pandoc version used: 2.10.1 (on macOS 10.15.6, installed via Homebrew)

**Comment by tarleb** [comment]
The `markdown` reader has an extension `lists_without_preceding_blankline` which can be enabled to give the CommonMark behavior: `pandoc --from=markdown+lists_without_preceding_blankline -o test.pdf test.md` should give the expected result.

Nota bene: there is now (pandoc 2.10.1) a new `commonmark_x` reader which uses CommonMark rules, but also allows to enable extensions not available in `commonmark`; the current Markdown reader is planned to be phased out in favor of the new reader.
