### ISSUE TITLE
Reference Not Found Error

### ISSUE THREAD

**Issue by tkurtbond** [jgm/pandoc#6592]
When I process the following reST file (notice it the whole file is
indented 3 spaces)

       **Option:** Arachnaurs' webs are made with a neurotoxin_ that can
       quickly paralyze their prey!  When wrapped in a web, make a Vigor
       roll or quickly lose consciousness.

       .. _neurotoxin: https://www.sciencenews.org/article/spiders-poisonous-webs-neuro-toxins-genes

into `ms` or PDF via `ms` output with the command

    pandoc -s -r rst -w ms -o rnf.ms.pdf rnf.rst

I get the errors

    [WARNING] Reference not found for 'neurotoxin' at chunk line 1 column 57
    <standard input>:70: macro error: pdfhref has no destination

and the resulting output PDF file and `.ms` file indeed do not have the
link.

Here's the `.ms` file that was generated:

    .QS
    .LP
    \f[B]Option:\f[R] Arachnaurs\[aq] webs are made with a \c
    .pdfhref W -D "" -A "\c" \
     -- "neurotoxin"
    \& that can quickly paralyze their prey! When wrapped in a web, make a
    Vigor roll or quickly lose consciousness.
    .QE

I'm using the following version of Pandoc:

    pandoc 2.10.1
    Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5

My OS information is:

    Mac OS X, Version 10.15.6, Build 19G73

**Comment by jgm** [comment]
If you unindent it, it will work.

Looks like we're wrongly assuming that the reference definitions will be unindented.

**Comment by jgm** [comment]
Closed by c8fda8f4d38a05fd494e7ee74d9c75930bdbcf12
