### ISSUE TITLE
Undefined control sequence error with Pandoc’s Markdown

### ISSUE THREAD

**Issue by noraj** [jgm/pandoc#6595]
## Command & Error message

```
$ pandoc test.md -o test.pdf -f markdown            
Error producing PDF.
! Undefined control sequence.
l.53 RealVNC HKEY\_LOCAL\_MACHINE\SOFTWARE
```

## Minimal document for error reproduction

Contextual:

```md
> RealVNC
> HKEY_LOCAL_MACHINE\SOFTWARE\RealVNC\vncserver
```

Minimal with error:

```md
> \SO
```

Minimal without error:

```md
> \S
```

## Notice

Occurring only from `markdown` (Pandoc’s Markdown), with `gfm` or `commonmark` there is no issue.
The bug seems to appears when there is a backslash followed by two letters.

**Comment by kysko** [comment]
it thinks it's latex code... escape the backlashes if they're only as text: `\\SO`

**Comment by noraj** [comment]
> it thinks it's latex code... 

Yeah it must be that.

> escape the backlashes if they're only as text: `\\SO`

This is a painful workaround. Idk if there is supposed to be latex command interpretation in pandoc's markdown? If no other renderrer doesn't have this problem so a solution must exist. If yes it can maybe limited contextually like not interpreting when in a quote, a code block, inline code, etc.

**Comment by jgm** [comment]
You can disable raw tex in markdown:
```
pandoc -f markdown-raw_tex
```

**Comment by jgm** [comment]
Or use a variant like `gfm`, which doesn't enable raw tex by default.
