### ISSUE TITLE
LaTeX reader and multirow-multicol problem

### ISSUE THREAD

**Issue by kysko** [jgm/pandoc#6596]
from an example in the code:
```
\begin{tabular}{ |l|l|l| }
\multicolumn{2}{c}{One} & Two \\
\end{tabular}
```
does give the desired effect.
However, this one doesn't span and loses the text in the multicol:
```
\begin{tabular}{ |l|l|l| }
Two & \multicolumn{2}{c}{One} \\
\end{tabular}
```
Similarly,
```
\begin{tabular}{ |l|l| }
\multirow{2}{c}{One} & Two \\
a
\end{tabular}
```
gives the desired result, but not the following one (no row span, text lost):
```
\begin{tabular}{ |l|l| }
Two & \multirow{2}{c}{One} \\
a
\end{tabular}
```
(pandoc 2.10.1 on win10x64, but verifiable on the demo page)

I noticed this when I tried to successive multicols and failed, but it appears from the above there is a problem for a right-most multicolumn/multirow (at least that)

**Comment by LaurentRDC** [comment]
I can confirm that it's true, and very puzzling. I am taking a look at why right now.
