### ISSUE TITLE
[Feature Request] TiddlyWiki Reader/Writer

### ISSUE THREAD

**Issue by Atlas48** [jgm/pandoc#6602]
Hello!

I'm writing in to suggest the inclusion of a [TiddlyWiki](https://tiddlywiki.com/) format reader/writer, as personally I don't feel like I have the time, nor the knowledge of haskell to make one myself.

Tiddlywiki has a unique format, although some elements are similar to DokuWiki and Creole, the syntax for headings and images differs.

**Comment by mb21** [comment]
ah, closing in favour of https://github.com/jgm/pandoc/issues/5356
