### ISSUE TITLE
Documentation missing for new commonmark/gfm parser.

### ISSUE THREAD

**Issue by marczz** [jgm/pandoc#6604]
I have installed the new 2.10.1 version of pandoc. It is a great improvement for parsing gfm. I often have to parse markdown that I have written for GoldMark. I looked at the new manual which say:

> commonmark and gfm have limited support for extensions.  Only those listed  below  
> (and smart, raw_tex, and hard_line_breaks) will work.

Which is quite confusing, because no extension is listed *below*, and the list of extension under gfm paragraph seems to be a list of extension yet included in gfm, like the lists under each other variant.

But I tried nevertheless `gfm+footnotes+attributes+definition_lists+smart` which is close to the GoldMark syntax, and it works very well.

When writing this report I also checked the output of  `pandoc --list-extensions=gfm`and I see that the extensions I used above are well listed as available for gfm format.

But the output of the previous command differs from the manual, several extensions listed in the manual as included in gfm don't appear at all:

> native_divs, fenced_code_blocks, backtick_code_blocks, space_in_atx_header, intra‐word_underscores, 
> shortcut_reference_links, angle_brackets_escapable, lists_without_preceding_blankline.

and  emoji is listed in the output of the command, but not in the manual.

May be I could also use the new `commonmark-x` variant, the changelog says 

> This is commonmark with a number of useful pandoc extensions enabled.

Nice but which one? If I tried `pandoc --list-extensions=commonmark-x` return only `-east_asian_line_breaks`. 

Finally I looked in the code and in the file `Extensions.hs`. The lists of extensions are clear for each variant. And it is guaranteed to correspond to the last release! And probably commonmark_x is pretty close to what I need. I have to look closely to what extensions need to be disabled/enabled. 

Again this new commonmark parser seems a great improvement, but some doc would ease its use.

**Comment by jgm** [comment]
> Nice but which one? If I tried pandoc --list-extensions=commonmark-x return only -east_asian_line_breaks.

This one has already been addressed in commit 3f2bb78f6bc01c892d9404d8c0188a29f2baa7cc

I'm going to remove these lists from the manual and tell people to use `--list-extensions`.
