### ISSUE TITLE
endterm attribute of xref element of DocBook is not respected

### ISSUE THREAD

**Issue by mmatrosov** [jgm/pandoc#6619]
Take this `input.db` file:

```
<chapter xml:id="_responsibility">
<simpara>See regular link: <xref linkend="SEC-Definitions"/>.</simpara>
<simpara>See link with endterm: <xref linkend="SEC-Definitions" endterm="link"/>.</simpara>
</chapter>
<chapter xml:id="SEC-Definitions">
<title>Definitions</title>
<simpara>Some definitions.</simpara>
</chapter>
```

Convert it to `output.docx`:

    pandoc.exe -s input.db -o output.docx

See the generated output:

![image](https://user-images.githubusercontent.com/3617951/90491911-42ee5800-e149-11ea-807e-284da1d86320.png)

*Expected:* The second link has the text "link". 

*Actual:* The second link has the text "???".

[The docs say](https://tdg.docbook.org/tdg/5.1/xref.html):

> If the endterm attribute is specified on xref, the content of the element pointed to by endterm will be used as the text of the cross-reference.

**Comment by jgm** [comment]
See https://github.com/jgm/pandoc/pull/6637#discussion_r478698734
for the claim that there isn't a bug here.  That seems convincing to me; there is no element in your sample with id `link`, so there is no "element pointed to by 'endterm'".  @mmatrosov Do you still think there's a bug; are we missing something?
