### ISSUE TITLE
LaTeX SI uncertainty dropped during conversion

### ISSUE THREAD

**Issue by efharkin** [jgm/pandoc#6620]
The `\SI` command of SIUnitX supports uncertainties on SI quantities using the `\pm` operator, but pandoc 2.10.1 does not, and instead drops the uncertainty. 

# Minimal example

LaTeX input:
```latex
The duration was \SI{10.0 \pm 3.3}{\ms}.
```

Expected markdown output:
```markdown
The duration was 10.0 ± 3.3 ms.
```

Actual markdown output (as of 2.10.1):
```markdown
The duration was 10.0  ms.
```
(Note extra space.)

# Proposed fix

A fast, inelegant solution might be to specifically check for the `\pm` command inside the first set of curly braces and render it as unicode ± in the output.

A better solution might be to have pandoc parse the contents of the first set of curly braces as inline math (which is what I suspect SIUnitX does anyway). This might help:

https://github.com/jgm/pandoc/blob/c22b12100d11a5ebb9ab58f1829a44288b640b6d/src/Text/Pandoc/Readers/LaTeX.hs#L616-L617

Either way, this is the function that needs updating:

https://github.com/jgm/pandoc/blob/c22b12100d11a5ebb9ab58f1829a44288b640b6d/src/Text/Pandoc/Readers/LaTeX.hs#L247-L260

---

I'm happy to work on this, but probably can't get to it right away. If someone else is itching to take this on, just drop a comment below.

**Comment by weber-s** [comment]
Hello,

I don't know if you want to implement it, but uncertainties is also often given in the following way:

```latex
\SI{23(2)}{\m}

\SI{125(12)}{\m}

\SI{0.135(21)}{\m}
```

that should be translated to : 

```md

23±2 m

125±12 m

0.135 ± 0.021 m

```

This notation is however more difficult to implement...

**Comment by jgm** [comment]
I've added that.

**Comment by jgm** [comment]
I've also supported `\pm` now, so closing this.
