### ISSUE TITLE
center enviorment is not showing up when converting org files to latex.

### ISSUE THREAD

**Issue by saheratarch** [jgm/pandoc#6624]
Pandoc version is 2.10.1

Input text:

```
* Focus on the result
Always ask the critical question:

#+BEGIN_CENTER
What do I want?
#+END_CENTER
```

Actual output:

```
\hypertarget{focus-on-the-result}{%
\section{Focus on the result}\label{focus-on-the-result}}

Always ask the critical question:

What do I want?
```

Expected output:

```
\hypertarget{focus-on-the-result}{%
\section{Focus on the result}\label{focus-on-the-result}}

Always ask the critical question:

\begin{center}
What do I want?
\end{center}
```

**Comment by tarleb** [comment]
"Pandoc attempts to preserve the structural elements of a document, but not formatting details." Centering is considered a formatting detail, which is why it is not preserved.

You can use a simple [Lua filter](https://pandoc.org/lua-filters.html) to get the desired result:

```lua
function Div (d)
  if d.classes:includes 'CENTER' then
    return {pandoc.RawBlock('latex', '\\begin{center}')}
      .. d.content
      .. {pandoc.RawBlock('latex', '\\end{center}')}
  end
end
```

**Comment by saheratarch** [comment]
I did not know about this, my apologies. 
The filtered worked as expected. Thank you!

Feel free to close this issue.

**Comment by tarleb** [comment]
Np. Happy it worked. Cheers!
