### ISSUE TITLE
numbering lines is no more working in 2.10.1 with higlighting

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#6625]
Since pandoc 2.10.1, line numbering using `.numberLines` on code chunk does not showa anymore when we use pandoc and its highlighting in **rmarkdown**. Specificity is that HTML templates are using boostrap.  

The change with rmarkdown are reported here https://github.com/rstudio/rmarkdown/issues/1876, and I believe this could be a result of this commit in skylighting that remove a css rule https://github.com/jgm/skylighting/commit/7234122d64431e5f73af93637af1746c5f92ab07#diff-933373e2d607798b1a054eb67b03d682L173

in bootstrap files, we have this rule 
```css
pre {
  overflow: auto;
}
```
and that was overriden in previous pandoc version by this rule from skylighting 

```css
.sourceCode { overflow: visible; } -- needed for line numbers
````
but it has been removed in the commit mentioned. 

Is this an intended change in skylighting for pandoc ? 

If so, then we will see to add this rule back in our template. 

A reproducible example is the rmarkdown issue. If you need another one, please tell me I'll see what I can do.

**Comment by dbaynard** [comment]
I'll go through the blame at the weekend — it's not immediately clear to me whether skylighting has invalid assumptions or whether overriding `pre` is something skylighting shouldn't have to consider.

**Comment by danobi** [comment]
Hitting this issue as well, any known workarounds?

**Comment by jgm** [comment]
You might try using `--css` and a file containing the line
```
.sourceCode { overflow: visible; }
```

@dbaynard have you been able to figure out the issue?

**Comment by danobi** [comment]
@jgm, I did try that, but unfortunately it "breaks" the border if scrolling is required:

![break scroll](https://user-images.githubusercontent.com/824615/93025314-daf92900-f5b1-11ea-80d8-9992fe992c45.png)

**Comment by brunoprietog** [comment]
If you enter this feature again, please make sure it works well with screen readers. Until the previous version, when there was code with syntax highlighting, screen readers read a link before the line of code, for each one, and it was very annoying. Now it doesn't happen, and I suppose it's for this reason. Thanks!

**Comment by cderv** [comment]
> Until the previous version, when there was code with syntax highlighting, screen readers read a link before the line of code, for each one, and it was very annoying. Now it doesn't happen, and I suppose it's for this reason. Thanks!

@brunoprietog I believe this is related to this change discussed in https://github.com/jgm/pandoc/issues/6352 and not the current issue.

> I'll go through the blame at the weekend — it's not immediately clear to me whether skylighting has invalid assumptions or whether overriding `pre` is something skylighting shouldn't have to consider.

@dbaynard do you have news on this one ? It would be awesome a fix can be included for pandoc next version. Thank you.

**Comment by brunoprietog** [comment]
> @brunoprietog I believe this is related to this change discussed in #6352 and not the current issue.

@cderv You're absolutely right, I'm sorry

**Comment by cderv** [comment]
@jgm @dbaynard Is there any news on this ? 

This change broke the styling of our documents using bootstrap and I believe there was no reason to remove the CSS rule in the first place. 

```css
.sourceCode { overflow: visible; } /* -- needed for line numbers */
```

If you agree with that, I can make a PR.

Otherwise, I can obviously fix it in our tool by adding this rule but I would need to make it conditional of Pandoc's highlighting being used or not. I think it would be better to have it put back upstream in skylighting as it seems required for the `.numberLines` feature to work. 

Thanks.

**Comment by jgm** [comment]
Pinging @dbaynard again.
If we don't hear back, maybe I'll just put this line back and hope things don't break unexpectedly?

**Comment by jgm** [comment]
I'm not sure how to test changes here, because I don't have an example sufficient to reproduce the problem.  Can you provide one? (I don't use rmarkdown, so please provide one that just uses pandoc.)

Here's what I tried.  I converted a small markdown file containing a code block with `.numberLines` to HTML, using `--include-in-header` to add the bootstrap CSS:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
```

The result looked fine.  I could see the line numbers (tested on both Safari and Firefox). I tried adding and then removing
```
.sourceCode { overflow: visible; } /* -- needed for line numbers */
```
and it made no difference.

What is the problem, exactly?

**Comment by cderv** [comment]
It seems you have already fix this issue by adding the above suggested CSS rule inside Pandoc's templates in `styles.html`
https://github.com/jgm/pandoc-templates/commit/b5f9ac0d0ec74abfaf7bdbc27ee0bee11391d0ee#diff-0b7756a55d81ae1a3d3a547e7f3ef33379d32a948f42a0ff7871af4099f7a1d3R99

```css
.sourceCode {
 background-color: transparent;
 overflow: visible;
}
```
So with last Pandoc version the correct CSS rule is included when using the template but no more inserted by Pandoc highlighting only. As we are using a custom template, I believe we now need to insert this rule in the template.

**Comment by jgm** [comment]
Ah, that makes sense. Thanks.

**Comment by jgm** [comment]
I've added this back to skylighting's default CSS with 0.10.2.
