### ISSUE TITLE
False values disappear from YAML metadata blocks

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#6630]
This is an issue in the markdown writer:
```
% pandoc -f native -s -t markdown
Pandoc (Meta {unMeta = fromList [("foo",MetaBool False)]})
[]
---
---
```

**Comment by GeorgeSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by jgm** [comment]
It's not as easy as some, but yes, I think this is a self-contained enough issue to be a good first issue.

**Comment by jgm** [comment]
This seems to have been fixed already.
```
% pandoc -f native -s -t markdown  
Pandoc (Meta {unMeta = fromList [("foo",MetaBool False)]})
[]
^D
---
foo: false
---
```
