### ISSUE TITLE
Better ReST: Directive to include external code snippets?

### ISSUE THREAD

**Issue by saurabhnanda** [jgm/pandoc#6631]
Follow-up from https://github.com/jgm/pandoc/issues/223#issuecomment-674846024

If I use the `..include file.hs` directive to include an external source file, pandoc doesn't treat it source code (therefore, no syntax highlighting).

> Can you do this in RST? If so, try the same syntax with pandoc and see if it works. 

I'm not sure if this is a Sphinx extension or built into ReST, but I've used [literalinclude](https://www.sphinx-doc.org/en/1.8/usage/restructuredtext/directives.html?highlight=literalinclude#directive-literalinclude) and it works as advertised.

Right now, I've had to do the following to get some old Sphinx based docs to work with my new Pandoc pipeline:

```haskell
transformRSTBlocks :: (MonadIO m) => FilePath -> P.Pandoc -> m P.Pandoc
transformRSTBlock basePath doc = (flip P.walkM) doc $ \x -> case x of
  P.Div (id_ classes_, attrs_) children ->
    if "literalinclude" `notElem` classes_
    then pure x
    else case children of
           [ P.Para [ P.Str fname ] ] -> do
             -- TODO: sniff the language syntax based on file extension
             codeBlock <- liftIO $ TIO.readFile $ basePath </> toS fname
             pure $ P.CodeBlock (id_, (toS "haskell"):(toS "numberLines"):classes_, attrs_) codeBlock
           _ ->
             -- TODO: break the build? report error? what?
             pure $ P.Div (id_, (toS "alert"):(toS "alert-danger"):classes_, attrs_)
             [ P.Plain [ P.Str (toS $ "unhandled literalinclude directive: " <> show children) ] ]
```

**Comment by jgm** [comment]
No and yes.
We aim to support everything in canonical reST, but there are a few omissions (there are bug reports for many of them already).
