### ISSUE TITLE
Better ReST: Function to resolve external includes?

### ISSUE THREAD

**Issue by saurabhnanda** [jgm/pandoc#6632]
Following up from https://github.com/jgm/pandoc/issues/223#issuecomment-674846024

The motivation for this feature-request is partially given at https://github.com/jgm/pandoc/issues/6631

The filename in `.. include` directives is treated as relative to the entire process's current-directory. However, I'd expect it to be relative to the file being parsed. So, if I move an RST file (along with its external includes) up/down a directory level, I don't need to change all include paths within the file.

The generalization of this behaviour would be a `loadExternalInclude :: FilePath -> IO String` type of function that can be overridden by the library user.

**Comment by jgm** [comment]
"as expected" here means what?  Our aim would be to have it work the way docutils tools work, to the extent possible.  So see how it is processed by docutils' rsthtml.py.

Unfortunately we can't reliably go relative to the directory containing the input file. Multiple input files can be specified on the command line; pandoc concatenates them before passing them to the RST reader, which therefore doesn't know which file corresponds to  a particular part of the input.

We could use `fetchItem`, which would at least allow you to work around this with resource-path, but it would also introduce some non-reST behavior (e.g. you could specify a URL).  Maybe worth it though.
