### ISSUE TITLE
Please support latex /newif /ifthing /else /fi

### ISSUE THREAD

**Issue by nathanieltagg** [jgm/pandoc#6633]
As related to #6096, I would find it very helpful if conditionals were supported when parsing LaTeX.

**Comment by mb21** [comment]
I assume you tried this with `-f latex` in the newest pandoc version?

**Comment by silby** [comment]
This got done! https://github.com/jgm/pandoc/commit/81eadfd99ad3e905b806cc6c80ab0fea0185286f#diff-3feeab153c189013ab52e1963b077cc3787cc78c27bc21cc394fafb532559c89
