### ISSUE TITLE
HTML5 dpub-aria support not including doc-biblioentry role

### ISSUE THREAD

**Issue by emarsden** [jgm/pandoc#6634]
The functionality added in #4213 adding ARIA roles to pandoc-citeproc content is correctly adding a `doc-bibliography` role to the `refs` div, but not adding `doc-biblioentry` roles to each reference div. This makes validators such as Google Lighthouse complain.

I see that there is code to include this role in `src/Text/Pandoc/Writers/HTML.hs` (handling blockToHtml of a Div and looking for a "ref-" prefix on the identifier), but it doesn't seem to work.

To reproduce: 

```
pandoc --from=markdown+citations --to=html5 --bibliography=biblio.bib content.md
<p>As stated in <span class="citation" data-cites="Foo">(Foo 1984)</span>.</p>
<div id="refs" class="references hanging-indent" role="doc-bibliography">
<div id="ref-Foo">
<p>Foo. 1984. <em>Foobles</em>.</p>
</div>
</div>
```

[content.txt](https://github.com/jgm/pandoc/files/5119113/content.txt)
[biblio.txt](https://github.com/jgm/pandoc/files/5119114/biblio.txt)

Pandoc version is 2.10.1, pandoc-citeproc version is 0.17.0.1.

**Comment by jgm** [comment]
If you're using the released version, then the reason it doesn't work is that this code was added after the release!

**Comment by jgm** [comment]
Commit 49e810b4ed3642cf549622046bd7f2b98c700894
Try a nightly.

**Comment by emarsden** [comment]
Indeed, this is fixed in nightly builds from https://github.com/jgm/pandoc/actions?query=workflow%3ANightly, thanks!
