### ISSUE TITLE
Support ZWNJ for LaTeX

### ISSUE THREAD

**Issue by lemzwerg** [jgm/pandoc#6639]
The standard Unicode way to break a ligature is to insert U+200C, the zero-width non-joiner character.  This is especially useful for German: At word compound boundaries, ligatures should be suppressed.  Examples: `beruf<200C>lich`, `Schaf<200C>fell`, `Dorf<200C>idylle`.

Both polyglossia and babel support this with the `"|` shorthand: `beruf"|lich`. Note that, at least for German, `"|` does not only break up the ligature, it also inserts a small horizontal space of 0.03em if there is no line break (and we are not within a PDF string; see `tex/generic/babel-german/german.ldf` in TeXLive for more).

Looking into `LaTeX.hs` I see that there is already support for U+200B, the zero-width space character.  I thus ask to do the same for U+200C.  However, it's not clear to me how to implement it: The simplest solution would be to add

```Haskell
'\x200C' -> emits "\"|"  -- zero-width non-joiner
```

but normally users disable babel shortshands since they can't be used in Pandoc...

**Comment by jgm** [comment]
This is about the LaTeX writer, I gather.
If you use xelatex or lualatex, won't these unicode characters just be emitted literally in the LaTeX output?

**Comment by lemzwerg** [comment]
Yes, this is about the LaTeX writer.

And yes, xelatex and friends emit ZWNJ literally.  However, most fonts don't contain a glyph for it, causing a visible warning.  Additionally, as explained earlier, it's not sufficient for German, thus my request for a special handling similar to zero-width space if.

At least for scripts like Latin, Cyrillic, or Greek the German approach (i.e., inserting some extra horizontal space) is OK, I believe.  For other scripts, in particular Arabic and Indic scripts, Pandoc should probably do nothing.

**Comment by jgm** [comment]
So if we escape `'\x200C'` as `"\"|"` would that be enough?
I didn't really understand your comment 
"normally users disable babel shortshands since they can't be used in Pandoc..."

**Comment by lemzwerg** [comment]
> So if we escape `'\x200C'` as `"\"|"` would that be enough?

Yes, provided Babel shorthands are active.

> I didn't really understand your comment "normally users disable
> babel shortshands since they can't be used in Pandoc..."

Only within a LaTeX document I can write `f"|l` to break the ligature.  With Pandoc, I get `"|` literally.  For this reason, many users (from what I gather from the internet) explicitly disable Babel shorthands in customized LaTeX templates for Pandoc by saying
```
\usepackage[shorthands=off,ngerman]{babel}
```
or something similar.

It would be thus helpful to implement a solution that works even if shorthands are disabled.

**Comment by jgm** [comment]
Does this shorthand also work with polyglossia?

I guess the other question is whether there is any good alternative.

**Comment by jgm** [comment]
What about `\hspace{0pt}`?

**Comment by jgm** [comment]
Or `{\kern0pt}`.
With that we get pretty nice output (comparison without and with):
<img width="157" alt="Screen Shot 2020-08-29 at 9 20 21 PM" src="https://user-images.githubusercontent.com/3044/91651126-8b592000-ea3d-11ea-90bd-086b4a45d360.png">

**Comment by lemzwerg** [comment]
`"|` works with polyglossia, too.  While `\hspace{0pt}` or `\kern{0pt}` is an improvement, it is not sufficient.

* It disables hyphenation after `"|` for the rest of the word.
* There should be a little additional space to avoid the collision of the glyphs.

What about using some code derived from `babel-german`'s code?
```latex
\def\ZWNJ{%
  \texorpdfstring{%
    \TextOrMath{%
      \penalty\@M
      \discretionary{-}{}{\kern.03em}%
      \ifvmode
      \else
        \nobreak
        \hskip\z@skip
      \fi}{}%
  }{}%
}
```
The command `\texorpdfstring` is part of `hyperref`, which is always loaded in pandoc's LaTeX template, AFAICS.  `\TextOrMath` is part of the LaTeX kernel.

Here is a comparison image for `fl`, `f{}l`, and `f\ZWNJ l`.
![fl](https://user-images.githubusercontent.com/1630245/91651835-cedd7980-ea91-11ea-9476-8c1f91e88466.png)

**Comment by jgm** [comment]
If `"|` works with both babel and polyglossia, then it's tempting just to use that.

Sure, it may fail if people change the default settings for these packages, but then the solution for them is easy: don't do that!

I kind of hate to clutter up the LaTeX template with a 10-line definition like the one you suggest.

Note: just to be clear, the suggestion would not be to allow you to write `"|` in pandoc markdown and have it transfer verbatim to LaTeX.  The suggestion is to convert literal Unicode U+200C in pandoc markdown to "| in LaTeX.

**Comment by lemzwerg** [comment]
For me personally this is a good solution :-)

I just wanted to point out an alternative.

**Comment by tarleb** [comment]
Just to revive this discussion and to throw in another alternative: would `\DeclareUnicodeCharacter` work for this? It might be less invasive than adding a custom command or forcing babel shorthands to be disabled. Would the definition look similar to that of `\ZWNJ` given above?

**Comment by jgm** [comment]
We now have code in the default templates to *disable* all language-specific Babel shorthands (see #6817).
So using `"|` isn't an alternative.  Using `\DeclareUnicodeCharacter` with something like the code above seems like a good option to me.  (Worth trying anyway.)

**Comment by tarleb** [comment]
I've created two PRs: #7290 converts the char into a command in the writer, while #7291 extends the template to define the character as a command. Both have the same effect, and both are ugly in their own way.

There is a third option similar to that in #7291, but which would use the package *newunicodechar* to define the character. This would make the code at least a little simpler.

**Comment by lemzwerg** [comment]
I have no preference for your solutions (thanks for that!).  I disagree on the uglyness, but this is in the eye of the beholder :-)
