### ISSUE TITLE
Bug formatting multilevel lists in Word document 

### ISSUE THREAD

**Issue by rebecca-hh-rosen** [jgm/pandoc#6642]
Hello,

I'm experiencing some challenges getting multilevel lists to render with proper formatting in Word using pandoc (specifically in pander_0.6.3). Most notably, when I've organized a multilevel list and seek to render it using pandoc.list(), the following occurs:

<img width="591" alt="Screen Shot 2020-08-26 at 10 32 48 AM" src="https://user-images.githubusercontent.com/41338345/91317006-7fdccf00-e787-11ea-9ebb-d84a589b1937.png">

As you can see, the code renders appropriately for single level lists (like Subsection2 etc), but perverts the formatting for Section1 in both background color and bullet points.

Additionally, if I go into the created word doc and manually delete / re-enter the space between the beginning point and asterisk, a bullet automatically forms and even adjusts some of the odd formatting (ie that beige highlight behind the words).

Most curiously, as I was preparing this example, I noticed that for three-tiered lists this is not an issue. See below for an example in "Section7", where the bullets align with what is outlined in the reference document:
<img width="973" alt="Screen Shot 2020-08-26 at 10 34 20 AM" src="https://user-images.githubusercontent.com/41338345/91317169-b581b800-e787-11ea-83a9-df2bc1ffe7c0.png">

The only difference I have noted on this is that Section7 contains no trailing whitespace in the Word doc, while the others do - however, I have a call to trimws() prior to adding these points to the list, so it should not be programming it that way. Furthermore, I have tried to set pandoc.list's argument "loose" to TRUE, which only produces the same above formatting for the misaligned lists, and seems to create more of a double-spaced format for the correctly adhering lists.

Any thoughts would be helpful, as I've seen issues raised around this spacing issue in only one issue ([here](https://github.com/jgm/pandoc/issues/5645) on pandoc's github page), but found none that detail using pandoc lists for multilvel bullet points or numbered lists with any ease. I've also tried multiple reference documents, using Rmd and not officedown, and even attempted to manually re-create pandoc.list as a function with formatting to my desired specifications, to no avail.

Thanks so much!

Please see my attached files for further reference and full code, dummy data and referenced Word document.

[officedown-REPREX-export.zip](https://github.com/davidgohel/officedown/files/5130571/officedown-REPREX-export.zip)

**Comment by jgm** [comment]
It would be helpful if you could give us  a simple test case with a pandoc command and markdown or native input.

Your output is being produced by RMarkdown; we need to figure out if it's a problem with pandoc itself or with the larger ecosystem.  You can do some work to pin this down for us -- I don't use R and I don't have the setup available to run your test case.

**Comment by the-solipsist** [comment]
I think this issue was solved by the original poster: https://github.com/davidgohel/officedown/issues/36#issuecomment-681054481

**Comment by jgm** [comment]
thanks, closing then!

**Comment by rebecca-hh-rosen** [comment]
@the-solipsist yes thank you so much!

Sorry for my delay -  I believe that first instantiating the nested lists as vectors (eg listy <- c() ) as opposed to lists ( eg listy <- list() ) was causing some trouble within pandoc list - even though I later wrapped them in a list. I am now wondering if casting it to a list (as.list() ) instead of wrapping them would also have fixed the problem.... 
Either way - once I changed that and cleaned up the reference doc it worked fine. Thank you so much for your time! I'd been working on this for a while and it was very useful to get some perspective.
