### ISSUE TITLE
Convert a webpage with dynamically generated content from javascript 

### ISSUE THREAD

**Issue by SignificantCell2** [jgm/pandoc#6645]
Is it possible to convert a webpage that has some content generated by javascript (e.g tables, etc) to another file format using pandoc?
When I try, pandoc retrieves only static html, and the content generated by javascript is not there.

Thanks

**Comment by agusmba** [comment]
While pandoc does not process dynamic content, you should be able to, just [save it first](https://superuser.com/a/837493) locally as rendered, and feed that to pandoc:

> Chrome and Firefox will save a copy of the page as it's currently displayed (ie using the current DOM) with `Ctrl+S / Save Page As...` if you choose `Web page, complete`.

**Comment by SignificantCell2** [comment]
Thanks for the reply
I mean, couldn't pandoc do that automatically because I have thousands of links and it not possible to manually save each page.

Thanks

**Comment by tarleb** [comment]
This would require a JavaScript to be included in pandoc, which is not the case. I'm sure you could automate JS execution and HTML downloading with something like selenium.

**Comment by alerque** [comment]
@SignificantCell2 Parsing dynamically generated content is not a job for a document conversion tool. Pandoc is not a web crawler! There are lots of tools that *are* crawlers and can be automated to fetch, generate and render dynamic content into static pages — but you need to use a tool designed for that job and use it to same static HTML pages with relevant resources in the right places. Then use Pandoc to convert those.

**Comment by SignificantCell2** [comment]
@alerque : You are right,  I could use a browser in headless mode to do that. But I am just perplexed Lately I started to see your post everywhere o unix SE, ...etc. I was about to see your website but found that it no longer exist. After 2 days you reply to a closed issue github. Please don't tell me you can read minds remotely 🤔

**Comment by alerque** [comment]
I don't think you have anything to worry about. Given that I effectively quit participating on SE sites last year in protest over their handling of volunteer moderators yet you are only now bumping into my posts over there I would have to not only read minds but predict the future in order to be the one following you. I don't even know who you are on any of those other platforms. I suspect you've just started wandering into topical areas where I've had ongoing interest for a while.
