### ISSUE TITLE
Perhaps 3 lines are uneeded in epub.css?

### ISSUE THREAD

**Issue by a-vrma** [jgm/pandoc#6648]
```
pandoc 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

https://github.com/jgm/pandoc/blob/8369eb67d77e52c4ee01c6080b335a8afd0a19d0/data/epub.css#L10-L12

I don't think the above lines do anything. Giving an empty body to CSS selectors doesn't unset them. Also Pandoc doesn't output h2.author or h3.date anymore, it outputs p.author and p.date.

**Comment by jgm** [comment]
Correct, we should have, if anything, `p.author` and `p.date`.
Although you're right that these don't do anything, I thought they'd be helpful because they tell you what you need to modify to change the appearance of these title page elements.

**Comment by a-vrma** [comment]
> Although you're right that these don't do anything, I thought they'd be
helpful because they tell you what you need to modify to change the
appearance of these title page elements.

That's a good point, that's exactly how I discovered this bug. I'll send a
patch to change it to p.author and p.date.
