### ISSUE TITLE
bug with beamer: "! LaTeX Error: Option clash for package hyperref."

### ISSUE THREAD

**Issue by lrdegeest** [jgm/pandoc#6652]
when I run the [demo beamer slideshow](https://pandoc.org/demo/SLIDES) using `pandoc -t beamer SLIDES -o example8.pdf` I get the error ` LaTeX Error: Option clash for package hyperref."`

I know beamer already loads `hyperref`, and `hyperref` is not loaded in `default.beamer`, so I am not sure what the issue is.

**Comment by Delanii** [comment]
Could it be that you are using different template? I am using default beamer template, recent pandoc version, and have no issue at all running file (just checked).
Which version of pandoc are you using?

**Comment by tarleb** [comment]
The available info is insufficient, thus closing.
