### ISSUE TITLE
Difference in h2 conversion for gfm

### ISSUE THREAD

**Issue by Barsonax** [jgm/pandoc#6656]
I used the following command:
```
pandoc .\input.html -f html -t gfm -o .\output.md --wrap=none
```

input.html:
```
<h2>foobar</h2>
```

On version 2.9.2.1 the output markdown is this:
```
##foobar
```

On version 2.10.1 the output markdown is this:
```
foobar
------
```
Why is there this difference? I prefer the ## style.

**Comment by mb21** [comment]
whats the exact command?

**Comment by Barsonax** [comment]
> whats the exact command?

Updated first post with the command

**Comment by jgm** [comment]
If what you want is ATX (`#`-style) headings, then just use the option `--atx-headers`.

It might be worth thinking about changing the default to ATX headings and adding a `--setext-headings` option.

**Comment by mb21** [comment]
> It might be worth thinking about changing the default to ATX headings and adding a --setext-headings option.

Agreed, seems much more common nowadays...
