### ISSUE TITLE
SIunitx and power of unit (squared, cubed and tothe{X})

### ISSUE THREAD

**Issue by weber-s** [jgm/pandoc#6657]
Hello here! Thanks for pandoc!

Using the siunitx package on latex is unable to produce correct power of unit (square, cube and generic) :

```latex
\documentclass{article}
\usepackage{siunitx}

\begin{document}
    Test with \SI{0.5}{\m} unit : works

    Text with \SI{0.5}{\square\m} unit : doesn't work

    Text with \SI{0.5}{\m\squared} unit : doesn't work

    Text with \SI{0.5}{\cubic\m} unit doesn't work

    Text with \SI{0.5}{\m\cubed} unit doesn't work

    Text with \SI{0.5}{\m\tothe{3}} unit doesn't work

    Text with \SI{0.5}{\raisetothe{3}\m} unit doesn't work
\end{document}
```

Is there any plan to support them? There are 6 of them, listed above. `square`, `cubic` and `raisetothe{X}` are used before the unit, and `squared`, `cubed` and `tothe{X}` after. 

Have a nice day!

**Comment by jgm** [comment]
Sure, we could add support for these.  The desired effect is just an exponent 2, 3, or n on the unit?
