### ISSUE TITLE
Improve siunitx support

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#6658]
Here are some examples from the documentation:
```
\num{12345,67890}

\num{1+-2i}

\num{.3e45}

\num{1.654 x 2.34 x 3.430}

\si{kg.m.s^{-1}}

\si{\kilogram\metre\per\second}

\si[per-mode=symbol]{\kilogram\metre\per\second}

\si[per-mode=symbol]{\kilogram\metre\per\ampere\per\second}


\numlist{10;20;30}

\SIlist{0.13;0.67;0.80}{\milli\metre}

\numrange{10}{20}

\SIrange{0.13}{0.67}{\milli\metre}

\ang{10}

\ang{1;2;3}

\ang{;;1}

\ang{+10;;}

\ang{-0;1;}

\si{kg.m/s^2}

\si{g_{polymer}~mol_{cat}.s^{-1}}

\si{\kilo\gram\metre\per\square\second}

\si{\gram\per\cubic\centi\metre}

\si{\square\volt\cubic\lumen\per\farad}

\si{\metre\squared\per\gray\cubic\lux}

\si{\henry\second}
```
They render as follows:
<img width="304" alt="Screen Shot 2020-09-02 at 11 14 08 AM" src="https://user-images.githubusercontent.com/3044/92020731-74505180-ed0d-11ea-9b22-414afd390abd.png">

**Comment by jgm** [comment]
Still need numlist and some spacing issues.

**Comment by jgm** [comment]
And `\ampere`

**Comment by jgm** [comment]
need to add tests and fix spacing.

**Comment by tarleb** [comment]
Related: #6620.

**Comment by jgm** [comment]
Current renderings of the above examples:
<img width="229" alt="Screen Shot 2021-05-20 at 8 20 46 AM" src="https://user-images.githubusercontent.com/3044/119005476-5468c880-b944-11eb-9d87-3b50e329250d.png">

**Comment by jgm** [comment]
Discrepancies:

`\num{1+-2i}` should have plus-or-minus symbol instead of +-

`\si{\kilogram\metre\per\second}` (without per-mode=symbol) should use exponent `-1` instead of `/`

`\num{.3e45}` should have a leading `0.`

`\si[per-mode=symbol]{\kilogram\metre\per\ampere\per\second}` should be kgm/(A s) not kgm/A/s

`\SIlist{0.13;0.67;0.80}{\milli\metre}` doesn't render at all!

`\ang{+10;;}` should have the + sign

`\si{\kilo\gram\metre\per\square\second}` should render with negative exponent instead of /

`\si{\gram\per\cubic\centi\metre}` (a) should use negative exponent instead of slash, (b) splits up "cm" and puts the exponent on c

Some others have discrepancies which will be fixed if these are.

**Comment by krtko1** [comment]
Hi.
Why is this issue closed when this feature is not implemented?

> * [ ]   `\si[per-mode=symbol]{\kilogram\metre\per\ampere\per\second}` should be kgm/(A s) not kgm/A/s

**Comment by jgm** [comment]
Maybe just an oversight?  Probably best to open a new issue for this.

**Comment by krtko1** [comment]
probably add new issue for it.

**Comment by MohammadNft** [comment]
[]()
