### ISSUE TITLE
Error with hidelinks 

### ISSUE THREAD

**Issue by hahahaL** [jgm/pandoc#6659]
cat c.md
# title
1. skt
2. t1
The command is pandoc c.md -o ccc.pdf,then I get the following error like these:
Error producing PDF.
! Package keyval Error: hidelinks undefined.
See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
l.40   pdfcreator={LaTeX via pandoc}}

can you help me to solve this problems thanks alot

**Comment by mb21** [comment]
sounds like something your LaTeX installation is out of date...

But please ask questions like this on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss)...
