### ISSUE TITLE
Change markdown writer to use ATX headings by default

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#6662]
After consensus reached on pandoc-discuss.

- [ ] Change `writerSetextHeaders` in default `WriterOptions` to False.
- [ ] Add `--setext-headings` option to change this option.
- [ ] Still respond to `--atx-headers`, as a no-op, for compatibility; but deprecate.
- [ ] Adjust T.P.App.Opt to add new option and change default.
- [ ] Adjust any tests that assume the other default.

**Comment by the-solipsist** [comment]
A quick question: Why is `--markdown-headings=setext` a commandline option rather than a markdown extension (i.e., something like `-t markdown+setext`)?

**Comment by jgm** [comment]
Because setext headings are part of the core default markdown features.

**Comment by alerque** [comment]
This is a great change and I'm grad to see it happen, but just a postmortem on the release process:

This should have been at least a minor release bump, not a patch release bump. I use Pandoc in a lot of workflows for normalizing content formatting and would not have expected upgrading a patch version to cause a significant change in the default output formatting.

Nothing to do now that the harm is done, but maybe keep it in mind for next time.

**Comment by tarleb** [comment]
Pandoc uses the [Haskell Package Versioning Policy](https://pvp.haskell.org/), so the jump from 2.11.1 to 2.11.2 *was* a minor release bump.

**Comment by mb21** [comment]
Should we add a link to the Haskell PVP in https://pandoc.org/releases.html ?

**Comment by jgm** [comment]
Good suggestion: I've added an explanation of the PVP to releases page.
