### ISSUE TITLE
ICML Writer - cleanup/modernize the code

### ISSUE THREAD

**Issue by lrosenthol** [jgm/pandoc#6665]
The code uses some older stylistic methods as well as using parameters vs. Style for passing information such as the identifier.  

Would be good to coordinate it with some of the other (more up to date) writers.

**Comment by jgm** [comment]
I think I'd rather avoid having issues like this.  There is a lot of code that could be improved stylistically, and if we opened issues for all of it, it would drown out everything else.

Either add a lot more specifics (describe the proposed change precisely enough that someone would know what to do to submit a PR), or let's close this.

**Comment by lrosenthol** [comment]
This was based on discussions on `pandoc-discuss` and #5541 about the need to use a more modern approach to passing information around.   I was asked to file an issue to track it - so this is it.

@jgm - if you want to close the issue, it's fine with me.  I was just doing what was asked...

**Comment by jgm** [comment]
Understood! Thanks for filing the issue. Still, I think I'll close it for the reason given.
