### ISSUE TITLE
ICML Writer - Links have visible boxes around them

### ISSUE THREAD

**Issue by lrosenthol** [jgm/pandoc#6675]
there is no reason for there to be visible boxes around the links - and it's no longer possible to remove them directly in InDesign, so better to do it in the conversion.

**Comment by lrosenthol** [comment]
I guess that this might be something that someone wants to configure - but it's not an option for any other writer, so this change will make things consistent with others.

**Comment by jgm** [comment]
Closed by #6676 

Note: in the LaTex/PDF writer you can select whether you want boxes around links; it's a hyperref option and I think there's a template variable for it.  But I think it's fine if this is non-configurable.

**Comment by nathan-artist** [comment]
@jgm, it would be good to add labels to this issue: **format:ICML** and **writer**.
