### ISSUE TITLE
commonmark_x does not support pipe_tables or multiline_tables

### ISSUE THREAD

**Issue by mikeheamber** [jgm/pandoc#6677]
I would love to use commonmark for our company's documentation format, but unfortunately it doesn't seem to support pipe_tables or multi_line tables, even with commonmark_x. I haven't tried the others. It looks like I will have to downgrade to plain markdown.

**Comment by jgm** [comment]
Yes, it supports `pipe_tables`.  But not (yet) multiline.

**Comment by jgm** [comment]
```
% pandoc -f commonmark_x
|a  |b  |
|---|---|
| 1 |  2|
<table>
<thead>
<tr class="header">
<th>a</th>
<th>b</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
</tr>
</tbody>
</table>
```

**Comment by mikeheamber** [comment]
![image](https://user-images.githubusercontent.com/68443729/92979928-10363780-f449-11ea-8035-5abf51b826f4.png)

**Comment by jgm** [comment]
Oh yes -- that's a bug fixed already in master.
It actually is enabled by defaul -- it's part of the commonmark_x package -- but you can't enable it manually in 2.10.
