### ISSUE TITLE
support minted option for source code highlight generation (markdown->latex)

### ISSUE THREAD

**Issue by larrycai** [jgm/pandoc#668]
I recorded as new feature from the discussion https://groups.google.com/d/topic/pandoc-discuss/skFVwpaDBRI/discussion

For markdown codes like

```
~~~~~  {.bash}
$ sudo apt-get install pandoc
$ sudo apt-get install texlive-xetex
~~~~~~
```

I want to have option in pandoc to generate minted based latex like below

```
\begin{minted}[bgcolor=bg]{bash}
$ sudo apt-get install pandoc
$ sudo apt-get install texlive-xetex
\end{minted}
```

In current solution, highlighting-kate (or pygments ) will generate the formatted latex instead.  While if minted package is used, it will handle the syntax highlight in its package like virbatim, It is more clean for me to handle.

**Comment by jepio** [comment]
I wrote a filter that does exactly what @jgm suggested, it is available in this [gist](https://gist.github.com/jepio/3ecaa6bba2a53ff74f2e). To use it under linux you need to make it executable and run pandoc with `--no-highlight --filter ./minted.py`.

**Comment by FilterKaapi** [comment]
@jepio I am getting an error as follows: 

```bash
File "./minted.py", line 38
    language, *pos = classes
              ^
SyntaxError: invalid syntax
```

I don't know `python`. How do I fix this issue?
