### ISSUE TITLE
Make header#title-block-header toggleable

### ISSUE THREAD

**Issue by thomasgalvin** [jgm/pandoc#6683]
The HTML standalone output always includes:

```html
<header id="title-block-header">
<h1 class="title">Gargoyle</h1>
</header>
```

At the top of the `body`; there should be a switch to disable this.

**Comment by mb21** [comment]
you can simply not set the `title` variable... or use a custom [template](https://pandoc.org/MANUAL.html#templates)...

**Comment by tarleb** [comment]
One can even do that on the command line:

    pandoc --to=html -V title="" input.md

This will keep the `<title>` element in the header, but remove the `<header>` block in the body.
