### ISSUE TITLE
error during markdown double quote parsing

### ISSUE THREAD

**Issue by docsAsCode** [jgm/pandoc#6686]
I try to convert the following markdown line into asciidoc but double quotes failed :+1: 

```
<2> un second bucket avec *security_flag* exactement à "S"
```

the native conversion says : 

```
Pandoc (Meta {unMeta = fromList []})
[Para [Str "<2>",Space,Str "un",Space,Str "second",Space,Str "bucket",Space,Str "avec",Space,Emph [Str "security_flag"],Space,Str "exactement",Space,Str "\224",Space,Quoted DoubleQuote [Str "S"]]]
```

But in asciidoc : 

`
<2> un second bucket avec _security_flag_ exactement à ``S''
`

double quotes are replaced by two single quotes ?

Tested in pandoc 2.10.1

thx

**Comment by mb21** [comment]
To turn this off, do:

    pandoc -f markdown-smart -t asciidoc

Of course, we should also make sure that the default output (```S''`) is valid asciidoc...

**Comment by docsAsCode** [comment]
ok, thank you
