### ISSUE TITLE
Comment in RMarkdown PowerPoint presentations fails to render properly

### ISSUE THREAD

**Issue by nwstephens** [jgm/pandoc#6688]
RMarkdown PowerPoint presentations that include comments after the section header do not render properly. Instead of rendering as separate slides, the following code renders as a single slide. I would expect the following code to render as two slides, not one.

```
---
output: powerpoint_presentation
---

# Section Header

<!-- Some comments here -->

## Content Slide

Lorem ipsum
```

**Comment by tarleb** [comment]
The headers are on different levels -- only top-level headers become slides (or use `--slide-level`). To force a new slide, use a horizontal bar

    first slide

    ---

    next slide

See https://pandoc.org/MANUAL.html#producing-slide-shows-with-pandoc for more details

**Comment by tarleb** [comment]
Ah, looking at the linked issue I now see were the confusion comes from. Pandoc choses the "slide level" of the first header level for which slides contain content. An HTML comment, despite being a comment, is treated as content. The solution is to specify `--slide-level=2` in the `pandoc_args` field.

**Comment by nwstephens** [comment]
Thank you very much, @tarleb . That's a fine solution. I tried it out in R Markdown and it works beautifully.

```
---
output: 
  powerpoint_presentation:
    slide_level: 2
---

# Section Header

<!-- Some comments here -->

## Content Slide

Lorem ipsum
```
