### ISSUE TITLE
markdown to pdf conversion using pdfroff fails when using PIC or EQN if the --number-sections or --toc arguments are used

### ISSUE THREAD

**Issue by kevin-nel** [jgm/pandoc#6692]
This example fails when ``--number-sections`` or ``--toc arguments`` are used.

````md
# heading

## sub heading

### Using PIC

```{=ms}
.PS
box
.PE
```

### Using EQN
```{=ms}
.EQ (2)
s = sqrt { { sum from i=1 to infty ( x sub i - x bar ) sup 2 } over { N - 1 } }
.EN
```

````

This example does not 
```md
# Heading

some text

## Subheading

some text

### Sub sub heading

some text
```
Here is the output of the working example.
![output of working example](https://user-images.githubusercontent.com/41850179/93768504-c6540b00-fc19-11ea-98ff-515bd4a8d79e.png)

This is the command being used.
``pandoc -f gfm test.md -t ms --pdf-engine=pdfroff --pdf-engine-opt=-p --pdf-engine-opt=-e  --number-sections -o out.pdf``

The error shown at output when using PIC is 
```
pic:<standard input>:185: syntax error before '\'
pic:<standard input>:185: giving up on this picture
pic:<standard input>:260: end of file before .PE or .PF
pic:<standard input>:183: .PS was here
```

and error shown at output when using EQN is 
```
eqn:<standard input>:103: fatal error: end of file before .EN
:0: macro error: diversion open while ejecting page (recovering)
```

I expected the document to work with the numbered headings and PIC/EQN and the numbered headings, TOC, PIC, and EQN all work individually when used with markdown and pandoc conversion. 

My pandoc version is 2.5 running in Ubuntu 20.04 on WSL windows 10

**Comment by jgm** [comment]
Note: if you want to quote code that contains triple backtick fences, use fences with four (or any N > 3) backticks.

**Comment by kevin-nel** [comment]
Thank you. I fixed it in the original post

**Comment by jgm** [comment]
Can't reproduce this with pandoc 2.10.1.  (You might try upgrading.)

Note:  `gfm` doesn't support the raw attribute syntax you're using.  That may be part of the problem you're having.

If you use `-f markdown` it works, at least on pandoc 2.10.1.

**Comment by kevin-nel** [comment]
Thank you the ``gfm`` was the problem
