### ISSUE TITLE
fenced divs forced to become sections breaks revealjs presentations

### ISSUE THREAD

**Issue by miguelmarco** [jgm/pandoc#6705]
I have a custom style file for my revealjs that applies a specific style to div's of the "thm" class. So I used to implement it with:

~~~~~~
% Making slides with pandoc and revealjs
% Miguel Angel Marco Buzunariz
% Zaragoza, June 2019

# Overview

## Theorem boxes

The code

``` markdown
::: thm
## **Theorem:**

The ring of polynomials over a field is noetherian.
:::
```

will be seen as

::: thm
## **Theorem:**

The ring of polynomials over a field is noetherian.
:::
~~~~~~

Running it with pandoc 2.7.3 by 

```
pandoc example.md -o example.html        -t revealjs  -V theme=beamer   -V transition=none     -i --slide-level 2 
```

produced:

```
<section id="title-slide">
  <h1 class="title">Making slides with pandoc and revealjs</h1>
  <p class="author">Miguel Angel Marco Buzunariz</p>
  <p class="date">Zaragoza, June 2019</p>
</section>
<section><section id="overview" class="title-slide slide level1"><h1>Overview</h1></section>
<section id="theorem-boxes" class="slide level2">
<h2>Theorem boxes</h2>
<p>The code</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb8-1"><a href="#cb8-1"></a>::: thm</span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="fu">## **Theorem:**</span></span>
<span id="cb8-3"><a href="#cb8-3"></a></span>
<span id="cb8-4"><a href="#cb8-4"></a>The ring of polynomials over a field is noetherian.</span>
<span id="cb8-5"><a href="#cb8-5"></a>:::</span></code></pre></div>
<p>will be seen as</p>
<div class="thm">
<h2 id="theorem"><strong>Theorem:</strong></h2>
<p>The ring of polynomials over a field is noetherian.</p>
</div>
```

which is what i wanted: inside a slide, i have a part with my specific style.

But in version 2.9.2.1, I get:

```
<section>
<section id="overview" class="title-slide slide level1">
<h1>Overview</h1>

</section>
<section id="theorem-boxes" class="slide level2">
<h2>Theorem boxes</h2>
<p>The code</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode markdown"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true"></a>::: thm</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true"></a><span class="fu">## **Theorem:**</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true"></a>The ring of polynomials over a field is noetherian.</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true"></a>:::</span></code></pre></div>
<p>will be seen as</p>
<section id="theorem" class="slide level2 thm">
<h2><strong>Theorem:</strong></h2>
<p>The ring of polynomials over a field is noetherian.</p>
</section></section>

```

Which is broken, since it has promoted the div to a section... and then revealjs turns it into a new slide.

Was this change intended?

**Comment by tarleb** [comment]
Yes, this was intended. From the changelog for version 2.8:

>  * Text.Pandoc.Slides: recognize content in Divs when determining slide level.

That's the change you are seeing here.

**Comment by miguelmarco** [comment]
Is there a way to disable that behaviour? Or to obtain the result i want in the newer versions? 

It limits a lot what you can do with revealjs. I need a way to create divs of a  specific class inside a slide.

**Comment by tarleb** [comment]
> Is there a way to disable that behaviour?

None that I know of.

> Or to obtain the result i want in the newer versions?

Either use a third level header `### **Theorem:**` or write your desired output directly in HTML.

>  I need a way to create divs of a specific class inside a slide.

That's generally unaffected. The only thing that changed is that headers at the `--slide-level` are now recognized even when nested in a Div. Other Divs and lower-level headers should be handled as before.

**Comment by miguelmarco** [comment]
Oh, I see. Thanks.

**Comment by miguelmarco** [comment]
I tried to use a thirthd level header, but it is still put into a section. Was it some other change introduced?

**Comment by tarleb** [comment]
Oh, right. Huh. Not sure, to be honest.

You can work around it by adding an HTML comment between div and header:

```` markdown
::: thm
<!-- -->
### **Theorem:**

The ring of polynomials over a field is noetherian.
:::
````

**Comment by miguelmarco** [comment]
That seemed to work, thank you!


It seems to work also with the same level of headers.

**Comment by miguelmarco** [comment]
Oops, not it doesn't work with the same level. Anyways, it works. thank you.

**Comment by jgm** [comment]
If you use a 3rd-level header, you need to set `--slide-level=2`.
