### ISSUE TITLE
docx-writer: Center Images and Tables

### ISSUE THREAD

**Issue by asdfjkl** [jgm/pandoc#6707]
When exporting a markdown-pandoc document to docx, all tables, figures, table-captions and figure-captions are left-centered.

It would be nice if it could be specified - globally or per figure/table - if tables and captions are centered, left-aligned or right-aligned. As far as I understand, it is not possible to do this via the reference-doc with paragraph or character styles.

**Comment by agusmba** [comment]
It should be possible to do this for figures+captions with paragraph styles in your reference-doc (I'm doing it).
Just check what paragraph style does your converted figure and caption have and tweak it.
For tables, you need to modify (IIRC) pandoc's "Table" table style (not paragraph nor character style)

**Comment by asdfjkl** [comment]
indeed table styles are supported. After carefully checking with a produced document on which style was applied to tables, table captions, figures and figure captions and changing all styles, everything works now. For tables it is important to really change the table style (and not the style of text in the tables, as this is "compact" which is also used for lists and enumerations).

**Comment by aburkov** [comment]
> indeed table styles are supported. After carefully checking with a produced document on which style was applied to tables, table captions, figures and figure captions and changing all styles, everything works now. For tables it is important to really change the table style (and not the style of text in the tables, as this is "compact" which is also used for lists and enumerations).

How to change the table style in the reference doc? I only see the Compact style and by changing it, the table in the rendered docx is still aligned to the left. I couldn't find the style with name Table and couldn't create one because Word says it's reserved for built-in styles.

**Comment by andyleemitchell** [comment]
> > indeed table styles are supported. After carefully checking with a produced document on which style was applied to tables, table captions, figures and figure captions and changing all styles, everything works now. For tables it is important to really change the table style (and not the style of text in the tables, as this is "compact" which is also used for lists and enumerations).
> 
> How to change the table style in the reference doc? I only see the Compact style and by changing it, the table in the rendered docx is still aligned to the left. I couldn't find the style with name Table and couldn't create one because Word says it's reserved for built-in styles.

Go to Styles -> Apply Styles in your reference doc and there should be a drop down list of all of styles in the document.

![image](https://github.com/user-attachments/assets/83258372-a7f7-4e48-87d4-e6fb6528317f)
![image](https://github.com/user-attachments/assets/976e39ab-65ff-4d74-8d85-90958c07c3fb)
