### ISSUE TITLE
Suggestion - pandoc-include as a first-party feature

### ISSUE THREAD

**Issue by AmitMY** [jgm/pandoc#6708]
I think including files in other files is a very lightweight module, that is widely needed, and should be supported by pandoc as a first-party feature.

Installing `pandoc-include` is not as trivial as one would think. I tried both on Windows and Ubuntu with no success.

Also, having pandoc docker containers for github actions, there is no control over adding pandoc with include.

For Windows specifically, if there were just executables for "pandoc" and all of its sub-packages, that would also work, but not for linux.

**Comment by mb21** [comment]
Looks like a duplicate of https://github.com/jgm/pandoc/issues/553 ?

**Comment by AmitMY** [comment]
I think the conversation there steered a bit from including it without a plugin, but you are right!
