### ISSUE TITLE
 Rendering of tables got broken if there are tabs inside their cells when file scope option is activated

### ISSUE THREAD

**Issue by N0rbert** [jgm/pandoc#6709]
This issue was first seen while using bookdown - see https://github.com/rstudio/bookdown/issues/960 .

Minimal reproducible example for plain Markdown is below:

https://gist.githubusercontent.com/N0rbert/aacb9f4397bdedf8302a9ed321508c3f/raw/80d59c56600d73f67e2b331372d60193b0c7c5e0/index.Rmd

Some cells have tab symbols inside.

Coverting this document to latex and then PDF by

```
pandoc index.Rmd --to latex --output index.tex --self-contained --variable tables=yes --file-scope && xelatex index.tex && xdg-open index.pdf
```

gives wrong table rendering as shown below:

![](https://i.stack.imgur.com/zfpMB.png)

In the above image pipes (|) are rendered in plain.

This happens with latest pandoc 2.10.1 with `--file-scope` command line argument.

**Comment by jgm** [comment]
More minimal:
```
| **Header1** | **Header2** | **Header3** | **Header4** | **Header5** |
|----------|----------|----------------|--------------|--------------------|
| r3c1 | r3c2 | r3c3 | r3c4 | r3c5 |
| r4c1 | r4c2 | r4c3 tab	text |  |	tab r4c5 |
```
I can confirm that `--file-scope` makes a difference.  It's hard to see how it could -- this needs more investigation.

**Comment by tarleb** [comment]
The problem was that pandoc didn't convert tab chars when called with `--file-scope`.
