### ISSUE TITLE
Bug in formula conversion from LaTeX to ODT

### ISSUE THREAD

**Issue by INeedToPickAUsername** [jgm/pandoc#6714]
Writing this in LaTeX ...

\\[
\int_1^2 \frac{3}{4} = 5
\\]

\\[
\int_1^2 {\frac{3}{4}} = 5
\\]

... will both produce the same result and will be correctly shown when converting LaTeX e.g. to EPUB.

When converting LaTeX to ODT however, i get ...

{ int_1^2 3 over 4 = 5}

... in both cases, where it should be ...

{ int_1^2 {3 over 4} = 5}

**Comment by jgm** [comment]
Here's the mathml texmath produces from that LaTeX formula:
```
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msubsup><mo>∫</mo><mn>1</mn><mn>2</mn></msubsup><mfrac><mn>3</mn><mn>4</mn></mfrac><mo>=</mo><mn>5</mn></mrow><annotation encoding="application/x-tex">\int_1^2 \frac{3}{4} = 5</annotation></semantics></math>
```
Can you identify the problem with this? If so, it might be worth a bug report to jgm/texmath.

**Comment by INeedToPickAUsername** [comment]
> Here's the mathml texmath produces from that LaTeX formula:
> 
> ```
> <math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msubsup><mo>∫</mo><mn>1</mn><mn>2</mn></msubsup><mfrac><mn>3</mn><mn>4</mn></mfrac><mo>=</mo><mn>5</mn></mrow><annotation encoding="application/x-tex">\int_1^2 \frac{3}{4} = 5</annotation></semantics></math>
> ```
> 
> Can you identify the problem with this? If so, it might be worth a bug report to jgm/texmath.

I cannot see a problem here ... \int_1^2 \frac{3}{4} ... looks good. The problem seems to be that the "\frac{3}{4}"-part seems to be translated into "3 over 4" for ODT ... instead of "{3 over 4}"

**Comment by jgm** [comment]
I'm not sure...pandoc uses mathml for math in ODT (this is supposed to be supported).  The syntax you give is not MathML---what is it?  Maybe there is a problem with the MathML support in the application you're using?

**Comment by INeedToPickAUsername** [comment]
The Syntax i am giving is what i see when i double click the formula in LibreOffice.

**Comment by INeedToPickAUsername** [comment]
Indeed ... if i unzip the ODT file PanDoc creates and look at the formla this is what i see:
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><mrow><msubsup><mo>∫</mo><mn>1</mn><mn>2</mn></msubsup><mfrac><mn>3</mn><mn>4</mn></mfrac></mrow></math>
This clearly looks good, so it really seems to be an issue with LibreOffice showing the document, not pandoc ...

**Comment by INeedToPickAUsername** [comment]
the xml was interpreted ...

> <math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><mrow><msubsup><mo>∫</mo><mn>1</mn><mn>2</mn></msubsup><mfrac><mn>3</mn><mn>4</mn></mfrac></mrow></math>

**Comment by INeedToPickAUsername** [comment]
again interpreted ... how do i copy xml code here?
`<math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><mrow><msubsup><mo>∫</mo><mn>1</mn><mn>2</mn></msubsup><mfrac><mn>3</mn><mn>4</mn></mfrac></mrow></math>`

**Comment by INeedToPickAUsername** [comment]
ok, this worked
bottom line: seems to be a LibreOffice issuw

**Comment by jgm** [comment]
Ok, thanks for confirming that.  Maybe worth an issue report to LibreOffice, if you haven't already.

**Comment by INeedToPickAUsername** [comment]
I'm working on a bug report for LibreOffice ...
Sorry having bothered you with an issue that wasn't yours ...
