### ISSUE TITLE
TeX conversion failure without any indication of _what_ actually caused the failure.

### ISSUE THREAD

**Issue by Pomax** [jgm/pandoc#6715]
I tried running pandoc 2.5 on Ubuntu 20 against the following maths tex:

```tex
\documentclass{article}

\begin{document}
\[
\int_{0}^{z}\sqrt{ \left (dx/dt \right )^2+\left (dy/dt \right )^2} dt
\simeq
\frac{z}{2} \cdot \left [ f\left( \frac{z}{2} \cdot \frac{-1}{\sqrt{3}} + \frac{z}{2} \right)
              + f\left( \frac{z}{2} \cdot \frac{1}{\sqrt{3}} + \frac{z}{2} \right)
          \right ]
\]
\end{document}
```

And get the following output:

```
[WARNING] Could not convert TeX math '\int_{0}^{z}\sqrt{ \left (dx/dt \right )^2+\left (dy/dt \right )^2} dt
  \simeq
  \frac{z}{2} \cdot \left [ f\left( \frac{z}{2} \cdot \frac{-1}{\sqrt{3}} + \frac{z}{2} \right)
                + f\left( \frac{z}{2} \cdot \frac{1}{\sqrt{3}} + \frac{z}{2} \right)
            \right ]', rendering as TeX
<p><br /><span class="math display">$$\int_{0}^{z}\sqrt{ \left (dx/dt \right )^2+\left (dy/dt \right )^2} dt
\simeq
\frac{z}{2} \cdot \left [ f\left( \frac{z}{2} \cdot \frac{-1}{\sqrt{3}} + \frac{z}{2} \right)
              + f\left( \frac{z}{2} \cdot \frac{1}{\sqrt{3}} + \frac{z}{2} \right)
          \right ]$$</span><br /></p>
```
However, this output does not identify _which instruction_ is causing the conversion to fail. How do I force pandoc to tell me where things actually went wrong?

Note that dropping running `latex test.tex` or even dropping the equation into https://www.codecogs.com/latex/eqneditor.php works, so there's nothing that immediately jumps out as "this is probably what's wrong", so pandoc's help in actually identifying the problem would be greatly appreciated.

Also, on a secondary note, `$$` as both start and end marker for maths mode is the legacy pure TeX syntax for maths mode, and [isn't actually supported by LaTeX](https://tex.stackexchange.com/a/69854/8406) (and never has). Instead, the syntax is `\[` at the start and `\]` at the end, so rewriting `\[ ... \]` to `$$ ... $$` is pretty odd, and worth keeping `\[ ... \]`.

(also see http://ctan.mirror.rafal.ca/info/l2tabu/english/l2tabuen.pdf, section 1.6 for this)

**Comment by jgm** [comment]
You don't say what you're trying to convert this to.  What is your output format and what command line, exactly, are you using?  It looks as if you're targeting HTML, but using the default math processing option of "trying to fake it with unicode."  This fails if you have things like fractions.  If you have any kind of complex math, you need to use `--mathjax` or `--katex` or `--webtex` or `--mathml` one of the other supported math options.  See the manual.

**Comment by Pomax** [comment]
Ah, apologies, this was a straight up `pandoc -s test.tex -o test.text`.

**Comment by jgm** [comment]
Pandoc will do a decent job of converting math to plain text, as long as the math doesn't contain things that are really hard to represent in plain text (mostly things that require vertical as well as horizontal arrangement, like fractions or matrices).

If you have complex equations, targeting plain text is probably an impossible goal.

**Comment by Pomax** [comment]
Story of my life. I've written plenty of things to make the impossible possible, although at this point I _really_ don't want to have to do this myself anymore... Thanks for the dialogue, I'll probably just cop out and embed the original LaTeX as comments/content instead =P
