### ISSUE TITLE
Lua custom writer interface extensions

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#6731]
A recent pandoc-discuss thread discussed use of Lua custom writers for generating standalone documents. The problem at the moment is that:
* The writer is responsible for generating the toc, but it can't discover that a toc has been requested (because the supplied variables don't include `toc`)
* Even if the writer knew to generate a toc, it doesn't have a way of setting the `table-of-contents` variable (which is where the template will expect to find the generated toc)

Therefore I'd like to suggest:
* The writer should have access to all the writer options, e.g., via a `PANDOC_WRITER_OPTIONS` global variable
* The writer's `Doc()` function's `variables` argument should include those [variables-set-automatically](https://pandoc.org/MANUAL.html#variables-set-automatically) that can reasonably be set at this stage (this could include `toc`)
* The writer's `Doc()` function should be able to modify variables, e.g. (if this is feasible) by modifying its `variables` argument

I suppose if we have (1) then we don't need (2) (not `toc` anyway). In fact I can see that (2) might be regarded as undesirable, because it's insufficient (you need (1) for `toc-depth` and there's no need for `toc-depth` to be a variable because it's not relevant in a template).

One other note (which could go into a separate issue): the man page doesn't document the `table-of-contents` variable. I gather there's some history here (`toc` used to be used both indicate the need for a toc and to contain the generated toc).

**Comment by tarleb** [comment]
Related (same request but for filters): #5221.

**Comment by tarleb** [comment]
Reopening: the new code only adds the global variable, but setting variables is not possible yet.
