### ISSUE TITLE
asciidoctor heading 1 confusion

### ISSUE THREAD

**Issue by docsAsCode** [jgm/pandoc#6735]
When I want to convert a markdown like this : 

```markown
---
author: me
---

# title

body ...
```

the result after asciidoctor conversion is : 

```
= 
me

== title

body ...
```

Some operations with this asciidoc (i.e asciidoctor-pdf) generate error (due to empty title).
The expected asciidoctor is (heading move in first line) : 

```
= title
me

body ...
```

my pandoc version is 2.10.1
pandoc command is : 

`pandoc -s -f markdown-smart -t asciidoctor h1.md -o h1p.adoc`

Jérôme

**Comment by tarleb** [comment]
This is intended behavior. The title is expected to be given in the YAML metadata:

```
---
author: me
title: title
---

body ...
```

You can also call pandoc with `--shift-heading-level-by=-1` to correct this.

Pandoc could still do better by showing a warning when the title is empty, as it does for HTML documents.

**Comment by jgm** [comment]
I don't think showing an error is right here, unless asciidoc considers documents without titles invalid.  The fact that one asciidoc tool requires a title (for producing PDFs) is not enough.  But if it's documented that asciidoc documents must contain a title, we could consider it.

**Comment by docsAsCode** [comment]
Thank you very much for your response. This parameter helps me.
