### ISSUE TITLE
Backslash escapes in autolink urls not recognized by Pandoc Markdown reader

### ISSUE THREAD

**Issue by cjerdonek** [jgm/pandoc#6736]
Pandoc 2.11 doesn't seem to recognize backslash escapes in Pandoc Markdown when they occur inside an autolink url.

For example (using `pandoc --from markdown --to html5`):

Example 1:

```
md: <http://a.com/b\)c>

html: <p><a href="http://a.com/b\)c" class="uri">http://a.com/b\)c</a></p>
```

Example 2:

```
md: <http://a.com/b\>c>

html: <p><a href="http://a.com/b\" class="uri">http://a.com/b\</a>c&gt;</p>
```

However, Pandoc does recognize them in non-autolink hyperlinks:

```
md: [link](http://a.com/b\)c)

html: <p><a href="http://a.com/b)c">link</a></p>

md: [link](http://a.com/b\>c)

html: <p><a href="http://a.com/b%3Ec">link</a></p>
```

**Comment by jgm** [comment]
Pandoc is by no means alone in this interpretation:
<https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Chttp%3A%2F%2Fa.com%2Fb%5C)c%3E%0A%0A+%3Chttp%3A%2F%2Fa.com%2Fb%5C%3Ec%3E%0A>

And the commonmark is pretty explicit about this:
<https://spec.commonmark.org/0.29/#example-306>

So, not a bug.

**Comment by cjerdonek** [comment]
Ah, thank you!
