### ISSUE TITLE
[Changelog] CSL JSON is not a bibutils output format

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#6737]
https://github.com/jgm/pandoc/blob/master/changelog.md, under the heading “pandoc 2.11 (2020-10-11)”, says 

> Some of the bibliography formats supported by pandoc-citeproc (via hs-bibutils) are no longer supported: Copac, EndNote, ISI, MEDLINE, MODS, and RIS. If you use one of these formats, you may use the bibutils utility to convert to CSL JSON or BibTeX.

The reference to CSL JSON should be removed: bibutils does not support CSL JSON output (see https://sourceforge.net/p/bibutils/home/Bibutils/).

On the other hand, in addition to bibtex output, bibutils supports biblatex output, which I would expect to provide a somewhat less lossy intermediate format that bibtex and so should probably be the recommended one of the two.

**Comment by jgm** [comment]
Good, thanks for this.
