### ISSUE TITLE
Codespell report for "Pandoc" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [jgm/pandoc#6738]
The FOSS server [fossies.org](https://fossies.org) - supporting and heavily using itself "Pandoc" - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the "Pandoc" release 2.11:

&nbsp;https://fossies.org/linux/www/pandoc/codespell.html

That version-independent URL should redirect always to the last report (if available), so currently to

&nbsp;https://fossies.org/linux/www/pandoc-2.11.tar.gz/codespell.html

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. Especially interesting may be unassigned errors marked by a "?" since they may be contained in the source code itself. Some more according information is offered by a tooltip if the mouse is over the string "error context type character" above the table, over the "T" in the table header or over such a context character itself within the table. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable. So for e.g. also the many entries in the `changelog.md` file (that may not be correctable or for which the correction effort seems too high) could be excluded.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/www/pandoc/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/www/pandoc/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/www/pandoc/codespell_hist.html) (log).

Perhaps more meaningful may be a similar and continuously updated report for the Pandoc GitHub "master" version which is available within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:

&nbsp;https://fossies.org/linux/test/pandoc-master.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently half-hourly.

Although no severe errors were found and the correction of misspellings and typos has probably not a top priority, I hope that the report can nevertheless be a little bit useful.

**Comment by tarleb** [comment]
Thank you, this looks very helpful. I'm starting by correcting the typos in docs/lua-filters.md.

Question: in MANUAL.txt, the British spelling `targetting` is marked, while the spelling `marshalled` in lua-filters.md in not. I'd expect that it marks either both or none. Is that intended?

**Comment by jschleus** [comment]
@tarleb No, this is just a result of the way the "codespell" tool works, which simply uses a flat dictionary text file and this file does not yet contain the word `marshalled`. And yes, British spelling is a bit of a problem (may be generally accepted here or may be not).

**Comment by tarleb** [comment]
All relevant typos have been fixed. The remaining reports appear to either

- have been chosen deliberately,
- are in third-party files used for testing, or
- are an in the poem "The Tyger" which is used in test files.

Thanks again @jschleus!

**Comment by jschleus** [comment]
Great, so  currently there are no misspellings found by codespell (and thanks for the detailed information about the remaining FPs).
