### ISSUE TITLE
Difference in gfm output in Pandoc 2.11

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#6740]
I've noticed that `gfm` behaves a bit differently in Pandoc 2.11. For example, in Pandoc 2.9.2.1: 

```bash
echo '## <https://www.google.com>' | pandoc --to gfm
```
Gives:

```
## <https://www.google.com>
```

Whereas in Pandoc 2.11 it gives:

```text
<a href="https://www.google.com" class="uri">https://www.google.com</a>
-----------------------------------------------------------------------
```

If this is intentional we can work around the header difference w/ `--atx-headers`. For the `class="uri"`, is there something we can do to suppress that and get a regular markdown link

**Comment by argent0** [comment]
In current master this is:

```
$ stack run pandoc -- --to gfm
## <https://www.google.com>
## <a href="https://www.google.com" class="uri">https://www.google.com</a>
$
```

First line is the input. Second the output.

This is with the #6693 patch, but I don't think that is affecting this case.

**Comment by jgm** [comment]
In 2.10 we switched from a wrapped C library to using pandoc's normal markdown writer, with some tweaks.

When #6693 is merged, ATX headings will be the default.

The difference in the links is surprising, though.  I see the issue and it should not be hard to fix.
