### ISSUE TITLE
Pandoc 2.11 and Citation Order

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#6741]
In Pandoc < 2.11, for citation styles like IEEE numbering is based on in-text order. However in Pandoc V2.11, the order of the numbers is taken from the bibliography file itself. [Here is the sample bibliography and csl file, note the order](https://gist.github.com/iandol/d8371b9941b7f1cc8bab722a63ed1b51) — the CSL is taken from here: http://www.zotero.org/styles/ieee 

Processing in Pandoc V2.10 (not showing the bibliography text for brevity):

```
➜ pandoc --bibliography test.json --csl ieee.csl test.md -t plain
First Heading

Here is some text. And a reference [1], [2].

Second Heading

Here is some text[3]. And a reference [1], [3].

Third Heading

Here is some text. And a reference [4]–[6].

```

But the same files in Pandoc V2.11 (numbers come from the order found in test.json):
```
➜ pandoc211 --citeproc --bibliography test.json --csl ieee.csl test.md -t plain
First Heading

Here is some text. And a reference [4], [6].

Second Heading

Here is some text[5]. And a reference [5], [6].

Third Heading

Here is some text. And a reference [1]–[3].

```

And test.md markdown:

```markdown
---
title: 'A Simple Citations Test'
author: 'Joanna Doe'
...

# First Heading #
Here is some **text**. And a reference [@brainard2015;@brainard2015a].

# Second Heading #
Here is some *text*[@cavanagh1991]. And a reference [@cavanagh1991;@brainard2015].

# Third Heading #
Here is some [text]{.underline}. And a reference [@mathot2020;@zokaei2019;@suzuki2019].

::: {#refs}
## Bibliography ##
:::

```

**Comment by jgm** [comment]
I have to admit, I'm unsure from the CSL spec how to assign citation numbers (and the test suite is terribly confusing too).  I had been sorting the bibliography according to the sort rules defined for the bibliography, then assigning the numbers according to that sorting.  But is that right?  @njbart @denismaier can you help?

**Comment by denismaier** [comment]
Under sorting there is this sentence:  

> In the absence of cs:sort, cites and bibliographic entries appear in the order in which they are cited.

**Comment by jgm** [comment]
Thanks @denismaier -- I must have missed that!
What about uncited items in the bibliography? I guess they go at the end?

**Comment by denismaier** [comment]
That would be quite an edge case. The assumption is probably that you wouldn't add uncited items when using such a style. Anyway, adding them at the end is probably the best option. But then again, how would you sort them if there is more than one uncited item?
