### ISSUE TITLE
CSLReferences usage does not have enough arguments

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#6745]
I am having issue with `iso690-author-date-cs.csl` style generated references. The attached files generates the following `CSLReferences` environment. The parameters of the environment are crucial to reproduce this issue:

```latex
\hypertarget{refs}{}
\begin{CSLReferences}{0}{1}
\leavevmode\hypertarget{ref-Yoshida2016}{}%
YOSHIDA, Shosuke, Kazumi HIRAGA, Toshihiko TAKEHANA, Ikuo TANIGUCHI,
Hironao YAMAJI, Yasuhito MAEDA, Kiyotsuna TOYOHARA, Kenji MIYAMOTO,
Yoshiharu KIMURA a Kohei ODA, 2016. A~bacterium that degrades and
assimilates poly(ethylene terephthalate). \emph{Science} {[}online{]}.
\textbf{351}(6278), 1196--1199. Dostupné
z:~doi:\href{https://doi.org/10.1126/science.aad6359}{10.1126/science.aad6359}

\end{CSLReferences}
```

Notice there are only two arguments to the `CSLReference` environment, while the [LaTeX code in the template needs three arguments](https://github.com/jgm/pandoc/blob/2.11/data/templates/default.latex#L373-L384):

```latex
\newenvironment{CSLReferences}[3] % #1 hanging-ident, #2 entry sp
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set line spacing
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#3\baselineskip}
  \fi
 }%
 {}
```

I used this command line to reproduce this:

```
pandoc --verbose --citeproc --bibliography ./bib.yaml --csl iso690-author-date-cs.csl  --toc  --self-contained -V lang=cs-CZ -V colorlinks=true -V csquotes=true -M link-citations=true --pdf-engine=lualatex -f markdown+smart -t latex -o test.tex test.md
```

The missing argument produces this failure when compiling the LaTeX:

```
! Missing number, treated as zero.
<to be read again> 
\unhbox 
l.107 \leavevmode
               \hypertarget{ref-Yoshida2016}{}%
```

[test.md.txt](https://github.com/jgm/pandoc/files/5372986/test.md.txt)
[bib.yaml.txt](https://github.com/jgm/pandoc/files/5372987/bib.yaml.txt)
[iso690-author-date-cs.csl.txt](https://github.com/jgm/pandoc/files/5372991/iso690-author-date-cs.csl.txt)

**Comment by wilx** [comment]
This is with `pandoc 2.11`.

**Comment by jgm** [comment]
Closed by 82280cc62c9fdfe7ffe1b0d8443d1739b441e22b

**Comment by jgm** [comment]
If you could test with the updated template, that would be great.

**Comment by wilx** [comment]
The fix fixes it.
