### ISSUE TITLE
Acronym support for latex reader is missing `\acl` and `\aclp` commands

### ISSUE THREAD

**Issue by darcamo** [jgm/pandoc#6746]
Pandoc supports several acronym commands but the `\acl` and `\aclp` commands are missing. Consider the input file below

```latex
% Latex code
\ac{MIMO} a

\acp{MIMO} b+

\acl{MIMO} c

\aclp{MIMO} d+

\acs{MIMO} e

\acsp{MIMO} f+

\acf{MIMO} G

\acfp{MIMO} H+

\gls{MIMO} i

\glspl{MIMO} j+

\acrshort{MIMO} k

\acrlong{MIMO} l
```

Running the command `pandoc sample.tex -t native` results in

```haskell
[Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","singular+short")]) [Str "MIMO"],Space,Str "a"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","plural+short")]) [Str "MIMOs"],Space,Str "b+"]
,Para [Str "c"]
,Para [Str "d+"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","singular+abbrv")]) [Str "MIMO"],Space,Str "e"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","plural+abbrv")]) [Str "MIMOs"],Space,Str "f+"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","singular+full")]) [Str "MIMO"],Space,Str "G"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","plural+full")]) [Str "MIMOs"],Space,Str "H+"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","singular+short")]) [Str "MIMO"],Space,Str "i"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","plural+short")]) [Str "MIMOs"],Space,Str "j+"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","singular+abbrv")]) [Str "MIMO"],Space,Str "k"]
,Para [Span ("",[],[("acronym-label","MIMO"),("acronym-form","singular+long")]) [Str "MIMO"],Space,Str "l"]]
```
where we can see that `\acl{MIMO}` and `\aclp{MIMO}` are not in the output as expected.

Pandoc version is  2.10.1 from Arch Linux repository. There is a new version 2.11 here in github, but from the changelog it didn't change anything related to acronym support and thus I haven't tried it.

**Comment by jgm** [comment]
What should pandoc produce in response to `\acl{MIMO}` and `\aclp{MIMO}`?

**Comment by darcamo** [comment]
I don't know about pandoc inner working, but comparing with the output of the other commands, probably the "acronym-form" for the `\acl command could be something such as `"singular+long" and the "acronym-form" for the `\aclp` command could be "plural+long".

Furthermore, each of these commands as a version with the first letter capitalized (Ac, Acp, Acl, Acf, etc), which is supposed to be used in the beginning of a sentence. Currently none of them is supported by pandoc and if any is present in the input latex document they will be missing in the converted document.
