### ISSUE TITLE
Gemtext support

### ISSUE THREAD

**Issue by sburris0** [jgm/pandoc#6747]
The [Gemini protocol](https://gemini.circumlunar.space/) uses a markup language that is more or less a very trimmed down version of markdown.

Here is the syntax from the cheatsheet at gemini://gemini.circumlunar.space/docs/cheatsheet.gmi (Gemini [client](https://gemini.circumlunar.space/clients.html) needed)

```
Gemtext cheatsheet

Here's the basics of how text works in Gemtext:

Long lines get wrapped by the client to fit the screen
Short lines *don't* get joined together
Write paragraphs as single long lines
Blank lines are rendered verbatim

You get three levels of heading:

# Heading

## Sub-heading

### Sub-subheading

You get one kind of list and you can't nest them:

* Mercury
* Gemini
* Apollo

Here's a quote from Maciej Cegłowski:

> I contend that text-based websites should not exceed in size the major works of Russian literature.

Lines which start with ``` will cause clients to toggle in and out of ordinary rendering mode and preformatted mode.  In preformatted mode, Gemtext syntax is ignored so links etc. will not be rendered, and text will appear in a monospace font.
```

I really like the idea of the Gemini project, but as it is new there is a lack of content.
Easy conversion from markdown (or whatever) -> gemtext will make it possible to mirror content, something I am looking to do myself.

**Comment by makeworld-the-better-one** [comment]
Converting from markdown to gemtext requires making some decisions about features that don't exist in gemtext. Ideally these decisions would be offered to the user as options, but I'm not sure how willing the pandoc project will be to create more command line flags just for this one format.

The main example of something that is not clear cut is inline links. Gemtext doesn't support them, but most document/markup formats do. How should they be handled?

This is something I have had to deal with for [md2gemini](https://github.com/makeworld-the-better-one/md2gemini). I've outlined the different options available for converting inline links on the README, in the [link modes section](https://github.com/makeworld-the-better-one/md2gemini#link-modes). I hope this is useful to whoever ends up implementing this writer, and that my tool can suffice for some people in the meantime.

**Comment by sburris0** [comment]
Yeah, I did start trying to make my own converter in Rust. I found there isn't an obvious way to correctly handle a few things.
For example, I had a function to sort of just normalize/round all of the header levels to a set that would work, e.g. it yields a hashmap `{2:1, 3:2, 4:2, 5:3}` if the header levels 2-5 are used in a document.

**Comment by makeworld-the-better-one** [comment]
Yeah, header levels is another good point. In md2gemini I just leave higher level headers as is, so level 4 would appear as `#### text` and just not be valid gemtext, but still be somewhat understandable.

I would appreciate getting a link to your converter! You should also send it to the [mailing list](https://lists.orbitalfox.eu/listinfo/gemini) for other people to check out.

**Comment by davidmrt98** [comment]
I would also like to see pandoc having Gemtext support - can I have a try at implementing the Writer?

**Comment by jgm** [comment]
I think gemini might not have enough adoption yet for a regular pandoc writer. I'd suggest creating a custom lua writer.  (If in the future we wanted a regular writer, this work wouldn't be wasted.)

**Comment by makeworld-the-better-one** [comment]
For now, I find connecting pandoc and [md2gemini](https://github.com/makeworld-the-better-one/md2gemini) to work decently.

```bash
pandoc your_document.docx -t markdown | md2gemini
```

**Comment by toastal** [comment]
> I think gemini might not have enough adoption yet for a regular pandoc writer

Won't there always be a chicken-egg situation here? Less people bother converting to Gemtext _because_ Pandoc doesn't support it? If it were as easy as Pandoc

**Comment by alerque** [comment]
> Won't there always be a chicken-egg situation here?

Yes, there will. That's a valid point, but think about the converse proposition for a second. If picking technologies we think *should* thrive and favoring those implementations were the driving force behind Pandoc, what would be to stop us from removing DOCX support, or for that matter removing all formats except Common Mark, SILE, and org-mode? Surely those are the three best formats for general prose content, typeset rendering, and interlinked personal wiki respectively. Web browsers should just render from CommonMark?

I jest — mostly. The point is exaggerated, but the point that picking implementations based on advocacy for a technology that isn't widely used rather than extant usage would completely reshape not just the current feature set but the actual utility (or lack thereof) and contributor pool (or shallowness thereof).

**Comment by tarleb** [comment]
See also: https://github.com/jgm/pandoc/issues/7353#issuecomment-855297307

**Comment by toastal** [comment]
That's fair. Is there specific "bar" that needs to be met and is it documented? It seems this sort of request probably comes up a lot then for every sort of document language that wants to get adoption.

Where Gemini+Gemtext caught my eye is that [SourceHut supports it](https://srht.site/) natively for their 'Pages' which is a small endorsement, but I would then assume that that doesn't count as a making the cut. This said, it appears there are a fairly large set of non-Pandoc [tools](https://git.sr.ht/~kr1sp1n/awesome-gemini#tools) for moving between some formats, like what was posted in a [previous comment](https://github.com/jgm/pandoc/issues/6747#issuecomment-729772201).

**Comment by xplosionmind** [comment]
Hi! Has this discussion been completely dropped or there is a chance for Pandoc to support importing and exporting from/to Gemtext?

I believe it would be extremely useful.

**Comment by tarleb** [comment]
I think this still holds true: <https://github.com/jgm/pandoc/issues/6747#issuecomment-725639386>.
Note that pandoc now supports [custom readers](https://pandoc.org/custom-readers), so support for reading and writing could be added by doing a bit of Lua coding.

**Comment by Wandmalfarbe** [comment]
I found a pandoc filter that can convert to gemtext https://github.com/kr1sp1n/gemini-pandoc-lua-filter

**Comment by sjehuda** [comment]
I think that Gemtext be useful.

I am working on an XMPP publishing system of which files are edited in RST, and it publishes the files as HTML over HTTP and XMPP, and also as GemText over Gemini.

Considering the LLM junk over the internet, I think that Gemini and other lesser known and private publishing platforms (e.g. XMPP PubSub) are more interesting for researchers and people in general.

To realize how I am motivated to publish over Gemini.

This is my journal.

gemini://woodpeckersnest.space/~schapps/journal/ (over 100 articles)

It really was intended to be a mirror for the HTTP site.

https://schapps.woodpeckersnest.eu/ (less than 10 articles)

Yet, once I have studied GemText, I had to restructure my articles, descipline myself to write differently, and it is a pleasure, especially when links are positioned each in its own line.

**Comment by toastal** [comment]
@sjehuda as a rST & XMPP user, I would like to here more if you ever come across a solution. I would gladly post my blog for Gemini as well if possible.

**Comment by sjehuda** [comment]
@toastal

I should have something working within a xouple of weeks.

Most of the work is done, and the missing work is a few more XSLT
stylesheets.

I would be glad to receive suggestions.

For information, read entries about "Rivitsa" over my journal.

Contact me over XMPP gemini://woodpeckersnest.space/~schapps/contact/
