### ISSUE TITLE
Latest pandoc download of 2.11 still installs 2.10 and hence, I am unable to use citeproc

### ISSUE THREAD

**Issue by bprakg** [jgm/pandoc#6748]
I have tried to download latest pandoc through the mac installer and also through brew install, both install 2.10 but the link says 2.11.  In 2.10, there is no citeproc.

**Comment by ickc** [comment]
2.11 has citeproc built in so you don't need that. Read the manual for more info on migration.

If you install pandoc through brew, then you need to `brew install pandoc-citeproc`. But don't mix pandoc 2.11 with pandoc-citeproc.

**Comment by bprakg** [comment]
I probably should talk only about the base issue.  If i install 2.11, it actually installs 2.10 and NOT 2.11

**Comment by ickc** [comment]
```bash
$> wget -qO- 'https://github.com/jgm/pandoc/releases/download/2.11.0.1/pandoc-2.11.0.1-macOS.zip' | bsdtar -xf-
$> pandoc-2.11.0.1/bin/pandoc --version
pandoc 2.11.0.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.2
Default user data directory: /Users/kolen/.local/share/pandoc or /Users/kolen/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Seems like it is working fine as least for 2.11.0.1 portable version.

Do this and post the stdout here first:

```bash
which -a pandoc
echo $PATH | tr ':' '\n'
```

**Comment by bprakg** [comment]
If this is working, I will use this approach.  The brew and mac install still install 2.10, just in case someone is interested in resolving them.

**Comment by bprakg** [comment]
Thanks for the echo $PATH | tr ':' '\n' command, it shows another install of pandoc, this was installed by my python editor(didn't expect this).  If I use the 'perl uninstall-pandoc.pl', script, it says "Pandoc not installed."
But if I do pondac --version, it still shows 2.10 installed.  I think this is the problem now.

<img width="644" alt="Screen Shot 2020-10-14 at 10 09 24 PM" src="https://user-images.githubusercontent.com/8314346/96079635-16fe0300-0e6a-11eb-8fb0-4f6f05592e69.png">

**Comment by bprakg** [comment]
Please feel free to close it.  I replaced the pandoc executable in the default location, which was inside anaconda editor for python, with 2.11 file and it worked :-)

**Comment by ickc** [comment]
Welcome. You can close it as you are the author of the issue.

**Comment by bprakg** [comment]
Got it, thanks Kolen!
