### ISSUE TITLE
Access violation after installing pandoc-2.11.0.1-windows-x86_64.msi

### ISSUE THREAD

**Issue by BruceEckel** [jgm/pandoc#6750]
```
>pandoc

Access violation in generated code when reading 0x7ffc7a2e0fff

 Attempting to reconstruct a stack trace...


Access violation in generated code when reading 0x7ffc7ad50fff

 Attempting to reconstruct a stack trace...


NOTE: Symbols could not be loaded. Addresses may be unresolved.

   Frame        Code address
 * 0x804fa48    0x7900000
 * 0x804fa50    0x1

   Frame        Code address
 * 0x7e4fa48    0x78f0000
 * 0x7e4fa50    0x1
```

(Locks up the Windows terminal; you can't Control-C out of it)

If I revert to pandoc 2.11, it works OK.

**Comment by mb21** [comment]
what exact pandoc and windows versions? 64bit?

**Comment by mb21** [comment]
weird.. have you tried reinstalling? does it also happen for pandoc-2.11.0.1-windows-x86_64.zip ?

**Comment by jgm** [comment]
What Windows version are you running?
And is anyone else experiencing this?

**Comment by kysko** [comment]
Can only say that the windows standalone (in the zip) didn't show any such error on a test (Win10 x64; also Win7 x64).

**Comment by BruceEckel** [comment]
> weird.. have you tried reinstalling? does it also happen for pandoc-2.11.0.1-windows-x86_64.zip ?

Yes, I also tried the zip file version with the same results.

This is on Windows 10 with all the most recent updates.

**Comment by BruceEckel** [comment]
OK, I just tried reinstalling from the MSI file and it worked. But I notice that when I tried to install it, it would only run the uninstaller the first time, then I ran it again and it worked. I think I might have just deleted the pandoc.exe file before, when I was uninstalling. That might have caused the problem somehow.
