### ISSUE TITLE
syntax highlighting for groovy

### ISSUE THREAD

**Issue by MyriaCore** [jgm/pandoc#6756]
currently, there isn't any syntax highlighting support for groovy. It'd certainly be much appreciated, though!

**Comment by tarleb** [comment]
To get support for groovy highlighting by getting the [`groovy.xml`](https://raw.githubusercontent.com/KDE/syntax-highlighting/master/data/syntax/groovy.xml) from the KDE syntax-highlighting repo and feeding it to pandoc via `--syntax-definition`.

**Comment by jgm** [comment]
I've added support for groovy to the skylighting library.  You'll have to wait for another skylighting and pandoc release before this becomes available in pandoc, but in the mean time you can use `--syntax-definition` to get support.  The repo is https://github.com/KDE/syntax-highlighting and you'll find the groovy.xml file in `data/syntax`.
