### ISSUE TITLE
v2.11.0.2 does not work well with springer-lecture-notes-in-computer-science.csl

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#6758]
I could personally share my draft with @jgm for reproducible example, but just wanted to file an issue regarding Pandoc v2.11.0.2 citation.

I used [springer-lecture-notes-in-computer-science.csl](https://github.com/citation-style-language/styles/blob/master/springer-lecture-notes-in-computer-science.csl) for my paper draft, and have found that one of the references (the sixth citation) is presented as 7, resulting in having 7. citation two times.

**Comment by jgm** [comment]
Please do share a reproducible example with me.

**Comment by tarleb** [comment]
Closing this, as there have been many improvements to citeproc. Also, I don't know how to reproduce this. Please reopen if this is premature.
