### ISSUE TITLE
docx -> markdown image paths incorrect

### ISSUE THREAD

**Issue by BruceEckel** [jgm/pandoc#6761]
When converting from docx (created using most recent version of Word on Windows 10) to Markdown using pandoc 2.11.0.2, the image paths come out like this:
```
![](C:\Git\TIJ4\Markdown/media/image30.wmf)
```
Some slashes are backwards, some are forwards. Not a deal-breaker for me as I'm automatically readjusting the paths, but it seems like a bug.

This is my pandoc command (in the form of a python f-string):
```
f"pandoc -f docx -t markdown+inline_notes+smart --atx-headers --extract-media={processedDir} -o {raw_markdown_file} {docxFile}"
```

**Comment by jgm** [comment]
Analysis:  `adjustImagePath` in T.P.Class.IO does this:  `pack dir <> "/" <> src`, where `dir` is the filepath specified by the user iwth `--extract-media`.  The slash before `media` is this literal `"/"`.  The slash after `media` is due to line 1450 of T.P.Writers.Docx.   Using FilePath's `</>` in both places instead of a literal `"/"` should result in all backslashes in the sample above.

**Comment by jgm** [comment]
Is the docx you're converting one produced by pandoc, or by other means?
It may be that the use of forward slashes for paths is standard within docx containers.

**Comment by BruceEckel** [comment]
Created using latest version of Word on Windows 10

**Comment by jgm** [comment]
I've pushed a fix, I think, but I don't have a Windows box handy to test with.
Can you try it out?  (After tonight a Windows nightly should be available.)

**Comment by BruceEckel** [comment]
If I understand correctly there's no build for me to test right now but one
will be created overnight -- correct?

**Comment by jgm** [comment]
Correct. Check https://github.com/jgm/pandoc/actions?query=workflow%3ANightly
tomorrow.

**Comment by BruceEckel** [comment]
When I installed the new version I seem to be able to run `pandoc -h` successfully but when I try `pandoc -v` I get an access violation again:
```
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. All rights reserved.

Tue 10/20/2020 11:57:42.27
C:\Users\Bruce
>pandoc -h
pandoc [OPTIONS] [FILES]
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT
  -o FILE               --output=FILE
                        --data-dir=DIRECTORY
  -M KEY[:VALUE]        --metadata=KEY[:VALUE]
                        --metadata-file=FILE
  -d FILE               --defaults=FILE
                        --file-scope
  -s                    --standalone
                        --template=FILE
  -V KEY[:VALUE]        --variable=KEY[:VALUE]
                        --wrap=auto|none|preserve
                        --ascii
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
  -N                    --number-sections
                        --number-offset=NUMBERS
                        --top-level-division=section|chapter|part
                        --extract-media=PATH
                        --resource-path=SEARCHPATH
  -H FILE               --include-in-header=FILE
  -B FILE               --include-before-body=FILE
  -A FILE               --include-after-body=FILE
                        --no-highlight
                        --highlight-style=STYLE|FILE
                        --syntax-definition=FILE
                        --dpi=NUMBER
                        --eol=crlf|lf|native
                        --columns=NUMBER
  -p                    --preserve-tabs
                        --tab-stop=NUMBER
                        --pdf-engine=PROGRAM
                        --pdf-engine-opt=STRING
                        --reference-doc=FILE
                        --self-contained
                        --request-header=NAME:VALUE
                        --no-check-certificate
                        --abbreviations=FILE
                        --indented-code-classes=STRING
                        --default-image-extension=extension
  -F PROGRAM            --filter=PROGRAM
  -L SCRIPTPATH         --lua-filter=SCRIPTPATH
                        --shift-heading-level-by=NUMBER
                        --base-header-level=NUMBER
                        --strip-empty-paragraphs
                        --track-changes=accept|reject|all
                        --strip-comments
                        --reference-links
                        --reference-location=block|section|document
                        --atx-headers
                        --listings
  -i                    --incremental
                        --slide-level=NUMBER
                        --section-divs
                        --html-q-tags
                        --email-obfuscation=none|javascript|references
                        --id-prefix=STRING
  -T STRING             --title-prefix=STRING
  -c URL                --css=URL
                        --epub-subdirectory=DIRNAME
                        --epub-cover-image=FILE
                        --epub-metadata=FILE
                        --epub-embed-font=FILE
                        --epub-chapter-level=NUMBER
                        --ipynb-output=all|none|best
  -C                    --citeproc
                        --bibliography=FILE
                        --csl=FILE
                        --citation-abbreviations=FILE
                        --natbib
                        --biblatex
                        --mathml
                        --webtex[=URL]
                        --mathjax[=URL]
                        --katex[=URL]
                        --gladtex
                        --trace
                        --dump-args
                        --ignore-args
                        --verbose
                        --quiet
                        --fail-if-warnings
                        --log=FILE
                        --bash-completion
                        --list-input-formats
                        --list-output-formats
                        --list-extensions[=FORMAT]
                        --list-highlight-languages
                        --list-highlight-styles
  -D FORMAT             --print-default-template=FORMAT
                        --print-default-data-file=FILE
                        --print-highlight-style=STYLE|FILE
  -v                    --version
  -h                    --help

Tue 10/20/2020 11:57:45.70
C:\Users\Bruce
>pandoc -v

Access violation in generated code when reading 0x7ffc7a2e0fff

 Attempting to reconstruct a stack trace...


Access violation in generated code when reading 0x7ffc7ad50fff

 Attempting to reconstruct a stack trace...


NOTE: Symbols could not be loaded. Addresses may be unresolved.

   Frame        Code address
 * 0x7fbfa48    0x7870000
 * 0x7fbfa50    0x1

   Frame        Code address
 * 0x81bfa48    0x7860000
 * 0x81bfa50    0x1
```

**Comment by BruceEckel** [comment]
When I try the new version I get this:

Access violation in generated code when reading 0x7ffeae7f0fff

 Attempting to reconstruct a stack trace...


Access violation in generated code when reading 0x7ffeaf950fff

 Attempting to reconstruct a stack trace...


NOTE: Symbols could not be loaded. Addresses may be unresolved.

   Frame        Code address
 * 0x82afa48    0x7900000
 * 0x82afa50    0x1

   Frame        Code address
 * 0x80afa48    0x78f0000
 * 0x80afa50    0x1

I've also notice that when I run the MSI installer on the previous version
and the Pandoc is installed, it gives me the option to uninstall Pandoc but
when I run that, it doesn't actually uninstall it -- all the files are
still in C:\Program Files\Pandoc when it finishes, and the PATH settings
still include the Path to C:\Program Files\Pandoc. So I wonder if that's
part of the problem.

To install the new version I simply unpacked it and copied the exe file
into C:\Program Files\Pandoc, and I wonder if the installer is doing
something else; without that additional step perhaps the above trace is
being produced.

This is on a Windows 10 machine with all recent updates.

*Bruce Eckel*
MindViewLLC.com
Blog: BruceEckel.com
EvolveWork.co
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicKotlin.com
Reinventing-Business.com <http://www.Reinventing-Business.com>

**Comment by BruceEckel** [comment]
I was able to successfully use the MSI installer in the release candidate here: https://github.com/jgm/pandoc/actions/runs/316006124

The paths are now correct, but notice that the numbers on the image files sometimes skip values:
```
![](C:\Git\TIJ4\processed\media\image1.wmf)
![](C:\Git\TIJ4\processed\media\image2.wmf)
![](C:\Git\TIJ4\processed\media\image3.wmf)
![](C:\Git\TIJ4\processed\media\image4.wmf)
![](C:\Git\TIJ4\processed\media\image5.wmf)
![](C:\Git\TIJ4\processed\media\image6.wmf)
![](C:\Git\TIJ4\processed\media\image7.wmf)
![](C:\Git\TIJ4\processed\media\image8.wmf)
![](C:\Git\TIJ4\processed\media\image9.emf)
![](C:\Git\TIJ4\processed\media\image10.wmf)
![](C:\Git\TIJ4\processed\media\image11.wmf)
![](C:\Git\TIJ4\processed\media\image13.wmf)
![](C:\Git\TIJ4\processed\media\image14.wmf)
![](C:\Git\TIJ4\processed\media\image16.wmf)
![](C:\Git\TIJ4\processed\media\image18.wmf)
![](C:\Git\TIJ4\processed\media\image19.wmf)
![](C:\Git\TIJ4\processed\media\image21.wmf)
![](C:\Git\TIJ4\processed\media\image23.wmf)
![](C:\Git\TIJ4\processed\media\image25.wmf)
![](C:\Git\TIJ4\processed\media\image27.wmf)
![](C:\Git\TIJ4\processed\media\image28.wmf)
![](C:\Git\TIJ4\processed\media\image29.wmf)
![](C:\Git\TIJ4\processed\media\image30.wmf)
![](C:\Git\TIJ4\processed\media\image31.wmf)
![](C:\Git\TIJ4\processed\media\image32.wmf)
![](C:\Git\TIJ4\processed\media\image35.wmf)
![](C:\Git\TIJ4\processed\media\image37.wmf)
![](C:\Git\TIJ4\processed\media\image39.wmf)
![](C:\Git\TIJ4\processed\media\image41.wmf)
![](C:\Git\TIJ4\processed\media\image42.wmf)
![](C:\Git\TIJ4\processed\media\image44.wmf)
![](C:\Git\TIJ4\processed\media\image46.wmf)
![](C:\Git\TIJ4\processed\media\image48.png)
```

**Comment by jgm** [comment]
I'm a bit confused, because that release candidate build is from before the change that closed this issue...

Not sure why the nightly doesn't work; I'd need to check the differences between build procedures on teh nightly and the release candidate. Maybe there is something there that would explain the difference?

**Comment by BruceEckel** [comment]
I can keep testing them as they come out. Feel free to ping me when you
need me to try again.

Yes, it seems mysterious that the MSI can work, but just putting the exe
file into the directory doesn't. Seems like the MSI file might be doing
some extra work.

*Bruce Eckel*
MindViewLLC.com
Blog: BruceEckel.com
EvolveWork.co
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicKotlin.com
Reinventing-Business.com <http://www.Reinventing-Business.com>

**Comment by nixsee** [comment]
I'm just now discovering 2 issues in my code based on this commit. 
1. the drive letter is now capitalized, whereas all the drive letters that I get from other functions in powershell are lowercase. This makes a Replace function that I use no longer match. Would it be more "proper" in the context of powershell to have lower case drive letters?
2. As detailed in issue 7186, https://github.com/jgm/pandoc/issues/7186, the forward slashes in image paths now make it very difficult for me to do a global search/replace for the forward slash escape character in my markdown files
