### ISSUE TITLE
Feature request - Output format specific blocks

### ISSUE THREAD

**Issue by AmitMY** [jgm/pandoc#6764]
I have a markdown file `index.md` that I would like to convert once to `html` and once to `pdf`.

In the HTML output, I would like to show an interactable SVG -
```html
<object type="image/svg+xml" data="assets/tasks.svg" class="logo"></object>
```

and in the PDF output I would like to show it as an image (doesn't support svg, so png instead):
```md
![](assets/tasks.svg)
```

Maybe I even want to add some latex code to the PDF output, and not to the HTML, etc...

It would be nice to have output specific blocks such that I could write the following, and just use a single input file:

```md
---latex,pdf---
![](assets/tasks.png)
---html---
<object type="image/svg+xml" data="assets/tasks.svg" class="logo"></object>
------
```

**Comment by mb21** [comment]
we have that, see https://pandoc.org/MANUAL.html#generic-raw-attribute

**Comment by AmitMY** [comment]
Thanks @mb21 , that is almost what I intended, but not exactly.

See, if I do:
![image](https://user-images.githubusercontent.com/5757359/96732970-9a1ade00-13c1-11eb-8a3d-2c0108cc0668.png)

My PDF contains:
![image](https://user-images.githubusercontent.com/5757359/96732999-a3a44600-13c1-11eb-8b96-791a7ae4ff5a.png)

And I was wondering if its possible to **still use markdown**, but it will only show in latex compilation.

Of course, you are a life saver, and I can just use:
```
\includegraphics[width=\linewidth]{assets/tasks/tasks.png}
```
Instead of markdown, so I guess problem solved anyway. Thanks!

**Comment by mb21** [comment]
> if its possible to still use markdown, but it will only show in latex compilation.

ah, for that you'd need to do something like:

```
::: latex
![](tasks.png
:::
```

then write a [filter](https://pandoc.org/lua-filters.html) to match on that div and filter remove it if format is not latex... possibly there are already filters that do that out in the wild...

**Comment by tarleb** [comment]
Might be helpful: https://twitter.com/kraut0xA/status/1304059217813417986
