### ISSUE TITLE
html div rendering in CommonMark is not possible

### ISSUE THREAD

**Issue by THS-on** [jgm/pandoc#6768]
Since 2.10.1 pandoc uses the Markdown writer for CommonMark. This breaks the old behavior that fenced divs are rendered to html divs. 
## Input
```
::: .custom_div
This is a div
:::
```

## Output
`pandoc test.md --to commonmark`
### Before 2.10.1 (Tested with 2.10)
```
<div class=".custom_div">

This is a div

</div>
``` 
### After 2.10 (Tested with 2.10.1 and 2.11.0)
```
This is a div
```

Is this intended? Currently there is also no way to enable this old behavior because `native_divs` is [not an extension](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Extensions.hs#L476.) for `commonmark`. Also all other combinations that would enable this are not possible that are checked here: https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Markdown.hs#L429.

**Comment by jgm** [comment]
I think this should be easy to fix; thanks for  reporting.
