### ISSUE TITLE
--extract-media fails with SVGs embedded in HTML document

### ISSUE THREAD

**Issue by ngirard** [jgm/pandoc#6770]
Using Pandoc 2.11.0.2 on Ubuntu 20.04.

[This web page](https://www.nouvelobs.com/coronavirus-de-wuhan/20201023.OBS35141/bientot-un-million-de-cas-de-covid-en-france-mais-ce-n-est-pas-le-chiffre-le-plus-inquietant.html) contains a series of graphics near the title "Evolution de l'épidémie en France".
These graphics are not extracted by Pandoc using
```sh
pandoc --extract-media=assets -s -f html -t html -o out.html "https://www.nouvelobs.com/coronavirus-de-wuhan/20201023.OBS35141/bientot-un-million-de-cas-de-covid-en-france-mais-ce-n-est-pas-le-chiffre-le-plus-inquietant.html"
```
Granted, the code is convoluted and these SVGs belong to an iframe; but Pandoc cannot extract them from the source of the iframe either, namely:

```sh
pandoc --extract-media=assets -s -f html -t html -o out.html "https://create.piktochart.com/embed/44693036-les-foyers-de-coronavirus-en-france"
```

**Comment by jgm** [comment]
Currently pandoc doesn't attempt to fetch the contents pointed to by the `src` attribute of an `iframe`. Maybe we should add this feature -- just fetch and parse.

**Comment by jgm** [comment]
for reference, here's the iframe element:
```
<iframe width="650" height="2553" frameborder="0"scrolling="no" style="overflow-y:hidden;" src="https://create.piktochart.com/embed/44693036-les-foyers-de-coronavirus-en-france" ></iframe>
```
But you're right, if you point pandoc at that embedded URL, it gets the gif but not the svg.

**Comment by jgm** [comment]
OK, I see why: in the embedded URL, you don't actually have an svg element; you just have some JavaScript that generates it dynamically. That's definitely out of scope for pandoc (to handle this kind of thing, we'd have to interpret the JavaScript like a browser).

**Comment by ngirard** [comment]
@jgm, thanks for your time & dedication!

> That's definitely out of scope for pandoc (to handle this kind of thing, we'd have to interpret the JavaScript like a browser).

Sure.

Unfortunately the problem remains when we save the contents as rendered by the browser.

For this I used [the SingleFile](https://github.com/gildas-lormeau/SingleFile) extension for Firefox to save the contents of "https://create.piktochart.com/embed/44693036-les-foyers-de-coronavirus-en-france" as rendered by Firefox 82 in such `s.html` file.
Then I indented its html markup using
```sh
tidy -quiet -indent -utf8 -ashtml --wrap 0 --vertical-space yes --indent yes --indent-attributes yes --punctuation-wrap yes --fix-style-tags no --custom-tags blocklevel --drop-empty-elements no < s.html > st.html
```

I'm attaching the resulting `st.html` file to this report.
As you can see the file does contain the SVG graphics.
Yet `pandoc --extract-media=assets -s -f html -t html -o out.html st.html` cannot extract them.

**Comment by ngirard** [comment]
[st.zip](https://github.com/jgm/pandoc/files/5432201/st.zip)

Actually uploading it within a zip file, apparently attaching plain html files isn't possible

**Comment by jgm** [comment]
Looks like, although we can handle svg images, we don't yet do anything with an svg element embedded in HTML.  This could be fixed by parsing the svg as an Image with a data: URL as the source.

**Comment by jgm** [comment]
I think we just need to untokenize the whole svg element, base-64 encode it, and emit
```
Image attrs [] ("data:image/svg+xml;base64,BASE64ENCODEDSVGHERE","")
```

**Comment by ngirard** [comment]
Thank you very much !
