### ISSUE TITLE
Epub: why rely on a web service for processing math when a LaTeX distribution is available?

### ISSUE THREAD

**Issue by tobiasBora** [jgm/pandoc#6776]
When I want to create an epub2 output with math:

```
Here are some math:

$$\Delta = b^2 - ac$$
```

I need to rely on `webtex`:

```
pandoc -t epub2 test.org -s -o test_pandoc.epub --webtex
```

This greatly increases the time or proceeding (which is a problem since I want to create for all pages of my website an `epub` version), and make me rely on an external website on which I have no control. Would it be possible to provide a way to locally build the equations that uses a local LaTeX?

Thanks!

**Comment by mb21** [comment]
The `--webtex` option takes a URL, so you could run your local server...

btw, for questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker...

**Comment by tobiasBora** [comment]
Well this is not really a question, but more a feature request. And if there is already a solution, cool, but then it would be nice to document it in the epub page before closing this issue.
And, I'm not yet convinced that the issue is solved. As far as I can see the website that is used is codegogs and it does not provides sources to deploy your own server. Apparently I'm not the only one having troubles to find an open source alternative: https://stackoverflow.com/questions/60996097/standalone-alternatives-to-webtex-for-pandoc
 The only server that they propose in an answer apparently only works for old versions of pandoc. The second alternative seems to use GladTex but this is quite a different solution since it involves a third party software. And again, if GladTex is the solution, then it should be documented in the epub section.

**Comment by jgm** [comment]
What @mb21 meant, I think, is that you could set up your own local server that shells out to LaTeX, if you like.

There are other options, too.  For example, you could use this Lua filter (still in PR phase) to include SVG graphics generated by MathJax: https://github.com/pandoc/lua-filters/pull/118/files.  (I don't know if epub2 supports SVG, though.)  Here's another filter that uses TeX to convert math to images: https://github.com/liamoc/latex-formulae
