### ISSUE TITLE
Cross platform package manager for Lua filters

### ISSUE THREAD

**Issue by mjfs** [jgm/pandoc#6779]
This feature request attempts to sketch a way towards `Pandoc` specific package manager for Lua filters.

The idea is to present a set of design principles and limitations, followed by implementation ideas. Unfortunately, due to my time constraints, only a small part of this will be covered at the time of opening the issue. Nevertheless, I believe it is better to put something out there early and possibly start a discussion that might save some time further on.

**Principles of package manager for Lua filters**:

1.	No external dependencies outside the ones distributed with `Pandoc`. Since `Pandoc` is also used in secure environments where any additional executable is problematic (e.g. increased exposure surface, outside of pre-approved code reviewed list etc.).

2.	It in some ways follows from the above, but just to make it clearer - all functionality of package manager should be either:
	a)	integrated into `Pandoc` (e.g. something similar to integrated `pandoc.mediabag.fetch`);
	b)	written in pure Lua (not possible for a lot of IO);
	b)	available in OS default install (e.g. such as `curl` is standard on Windows 10).

3.	Package manager should enable declaring packages in YAML block and should install them (and their dependencies) from trusted repositories automatically. Trusted locations are to be declared separately (e.g. `Pandoc` defaults file)

4.	Package manager should respect declared order of the filters as well as information which filters can be chained and applied in one go and which need full iterations of the document.

5.	Package manager should enable project scoping and therefore enable full reproducibility (e.g. similar to what `Packrat` enables for `R`)

6.	Package manager should support fetching dependencies via corporate proxies requiring authentication. Ideally it would support HTTP Negotiate (SPNEGO) mechanism (e.g. `curl --negotiate -u : "http://some.corporate.repository/readme.txt"`).

7.	In order to not reinvent the wheel, LuaRocks architecture should be followed where it makes sense. It should however be possible to have a single file filters containing everything that is minimally required.

**Implementation ideas - at this point in time only what I am currently using for my use case**:

Lua filters have a designated directory under the one where markdown document is located. Defaults file points to a single Lua filter already in the designated directory. This filter reads a list of further filters in YAML part of the markdown file and iterates them. If it does not find a corresponding filter in subdirectory, it downloads it from corporate repository (dependency resolution and versioning is not implemented yet). Each filter has an `apply` method with a list of tags and corresponding functions (same as a regular Pandoc filter) and also supports initialization parameters (e.g. `Pandoc` metadata). Filter's metadata also contain information on which filters can be merged (in predefined order) and which ones require a full independent iteration. This information is used in the final filter composition.

**Comment by ickc** [comment]
Shouldn't something like this be in pandoc discuss instead? I think no one has committed to the idea of having a pandoc package manager yet not to mention implementing one.

**Comment by jgm** [comment]
Yes, better to hash out ideas in pandoc-discuss.

**Comment by mjfs** [comment]
Even if the discussion is moved somewhere else, I would perhaps propose that we at least leave the issue open. Rationale for that would be that this gives the message that the functionality is worth pursuing, same as with other no yet implemented functionality.

The counterargument that I see for that is if there is no added value to be seen in implementing this or if there is an aversion to even an infrastructure layer being implemented in `Pandoc` itself. Since this is an advanced use case, that would of course be completely understandable stance. 

If necessary I can reformat the content of the issue to reflect only the desired end result.

**Comment by jgm** [comment]
There has been some discussion elsewhere (#6760) about packages, but the idea that has been pursued there is broader than just Lua filters.  A package, as there discussed, can include Lua filters, templates, default files, and other resources such as images.  If we supported any kind of packages, this broader view makes sense to me.  Hence I'm not inclined to keep an issue open that concerns package management just for Lua filters.

**Comment by mjfs** [comment]
Thank you for explaining, I was not aware that there is an initiative on-going that could result in addressing the issue more comprehensively. That would of course be even better.
