### ISSUE TITLE
"Invalid UTF-8 stream" error thrown when converting to JATS using "--citeproc" option

### ISSUE THREAD

**Issue by hubgit** [jgm/pandoc#6784]
When converting to JATS XML from other formats while using the `--citeproc` option, an error is thrown:

> pandoc: Cannot decode byte '\xc9': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

This doesn't occur when converting to other formats (e.g. pdf or docx) while using `--citeproc`, nor does it occur when converting to JATS XML using `--filter=pandoc-citeproc` with an earlier version of pandoc.

<details>
<summary>Example input</summary>

```md
---
references:
- author:
  - family: Willing
    given: Carol
  container-title: Proceedings of the 17th Python in Science Conference
  id: ref-1
  issued:
    year: 2018
  title: Binder 2.0 - Reproducible, interactive, sharable environments
    for science at scale
  type: paper-conference
title: Test
---

Testing
=======

This is a test[@ref-1].
```
</details>

```
> pandoc --version                              
pandoc 2.11.0.4

> pandoc -s -t jats input.md --citeproc
pandoc: Cannot decode byte '\xc9': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

**Comment by jgm** [comment]
Closed by 3190ce95c2175936ffded9ecf356d9ac1cc15d8a
