### ISSUE TITLE
doesn't install with ghc 8.10.2

### ISSUE THREAD

**Issue by GeorgeCo** [jgm/pandoc#6789]
ghc --version
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.2
bash-3.2$ cabal v1-install pandoc
cabal v1-install pandoc
Resolving dependencies...
In order, the following would be installed:
Glob-0.10.1 (via: pandoc-2.11.0.4) (new package)
HsYAML-0.2.1.0 (via: pandoc-2.11.0.4 doctemplates-0.8.2) (new package)
QuickCheck-2.14.1 (via: pandoc-types-1.22) (reinstall) (changes: random-1.2.0
-> 1.1)
SHA-1.6.4.4 (via: pandoc-2.11.0.4) (new package)
base16-bytestring-1.0.0.0 (via: text-conversions-0.3.1) (new package)
base64-bytestring-1.1.0.0 (latest: 1.2.0.0) (via: pandoc-2.11.0.4
skylighting-core-0.10.0.3 ipynb-0.1.0.1 text-conversions-0.3.1) (new package)
basement-0.0.11 (via: connection-0.3.1 cryptonite-0.27 pem-0.2.4 socks-0.6.1
memory-0.15.0) (new package)
blaze-builder-0.4.1.0 (via: http-client-0.7.2.1 blaze-html-0.9.1.2
blaze-markup-0.8.2.7) (new package)
case-insensitive-1.2.1.0 (via: pandoc-2.11.0.4 http-client-tls-0.3.5.3
citeproc-0.1.0.3 skylighting-core-0.10.0.3 http-client-0.7.2.1
http-types-0.12.3) (new package)
cereal-0.5.8.1 (via: tls-1.5.4 socks-0.6.1) (new package)
commonmark-0.1.0.2 (via: pandoc-2.11.0.4 commonmark-pandoc-0.2.0.1
commonmark-extensions-0.2.0.1) (new package)
cookie-0.4.5 (via: http-client-0.7.2.1) (new package)
digest-0.0.1.2 (via: zip-archive-0.4.1) (new package)
emojis-0.1 (via: pandoc-2.11.0.4 commonmark-extensions-0.2.0.1) (new package)
haddock-library-1.9.0 (via: pandoc-2.11.0.4) (new package)
hourglass-0.2.12 (via: tls-1.5.4 x509-validation-1.6.11 x509-1.7.5
asn1-encoding-0.9.6 asn1-types-0.3.4) (new package)
hslua-1.3.0 (via: pandoc-2.11.0.4 hslua-module-system-0.2.2.1
hslua-module-text-0.3.0.1) (new package)
hxt-charproperties-9.4.0.0 (via: hxt-9.3.1.18 hxt-regex-xmlschema-9.2.0.3
hxt-unicode-9.0.2.4) (new package)
jira-wiki-markup-1.3.2 (via: pandoc-2.11.0.4) (new package)
mime-types-0.1.0.9 (via: http-client-0.7.2.1) (new package)
network-3.1.2.0 (via: pandoc-2.11.0.4 http-client-tls-0.3.5.3 connection-0.3.1
tls-1.5.4 conduit-extra-1.3.5 http-client-0.7.2.1 streaming-commons-0.2.2.1
HTTP-4000.3.15 socks-0.6.1) (new package)
network-uri-2.6.3.0 (latest: 2.7.0.0) (via: pandoc-2.11.0.4
http-client-tls-0.3.5.3 http-client-0.7.2.1 hxt-9.3.1.18 HTTP-4000.3.15) (new
package)
rfc5051-0.2 (via: citeproc-0.1.0.3) (new package)
safe-0.3.19 (via: pandoc-2.11.0.4 citeproc-0.1.0.3 doctemplates-0.8.2
skylighting-core-0.10.0.3 doclayout-0.3 errors-2.3.0) (new package)
tagsoup-0.14.8 (via: pandoc-2.11.0.4) (new package)
temporary-1.3 (via: pandoc-2.11.0.4 hslua-module-system-0.2.2.1) (new package)
typed-process-0.2.6.0 (via: conduit-extra-1.3.5) (new package)
unicode-transforms-0.3.7.1 (via: pandoc-2.11.0.4) (new package)
uuid-types-1.0.3 (via: aeson-1.5.4.1) (reinstall) (changes: random-1.2.0 ->
1.1)
xml-1.3.14 (via: pandoc-2.11.0.4 texmath-0.12.0.3) (new package)
xml-types-0.3.8 (via: xml-conduit-1.8.0.1) (new package)
zlib-0.6.2.2 (via: pandoc-2.11.0.4 JuicyPixels-3.3.5 streaming-commons-0.2.2.1
zip-archive-0.4.1) (new package)
memory-0.15.0 (via: http-client-tls-0.3.5.3 tls-1.5.4 x509-validation-1.6.11
x509-1.7.5 http-client-0.7.2.1 asn1-types-0.3.4 cryptonite-0.27 pem-0.2.4)
(new package)
blaze-markup-0.8.2.7 (via: pandoc-2.11.0.4 xml-conduit-1.8.0.1
blaze-html-0.9.1.2) (new package)
http-types-0.12.3 (via: pandoc-2.11.0.4 http-client-tls-0.3.5.3
http-client-0.7.2.1) (new package)
commonmark-extensions-0.2.0.1 (via: pandoc-2.11.0.4 commonmark-pandoc-0.2.0.1)
(new package)
hslua-module-text-0.3.0.1 (via: pandoc-2.11.0.4) (new package)
hxt-unicode-9.0.2.4 (via: hxt-9.3.1.18) (new package)
hxt-regex-xmlschema-9.2.0.3 (via: hxt-9.3.1.18) (new package)
socks-0.6.1 (via: connection-0.3.1) (new package)
HTTP-4000.3.15 (via: pandoc-2.11.0.4) (new package)
errors-2.3.0 (via: text-conversions-0.3.1) (new package)
doclayout-0.3 (via: pandoc-2.11.0.4 doctemplates-0.8.2) (new package)
hslua-module-system-0.2.2.1 (via: pandoc-2.11.0.4) (new package)
aeson-1.5.4.1 (via: pandoc-2.11.0.4 citeproc-0.1.0.3 doctemplates-0.8.2
skylighting-core-0.10.0.3 aeson-pretty-0.8.8 aeson-pretty-0.8.8 ipynb-0.1.0.1
pandoc-types-1.22) (reinstall) (changes: uuid-types-1.0.3 removed)
zip-archive-0.4.1 (via: pandoc-2.11.0.4) (new package)
streaming-commons-0.2.2.1 (via: conduit-extra-1.3.5 http-client-0.7.2.1) (new
package)
JuicyPixels-3.3.5 (via: pandoc-2.11.0.4) (new package)
pem-0.2.4 (via: x509-system-1.6.6 x509-validation-1.6.11 x509-store-1.6.7
x509-1.7.5) (new package)
cryptonite-0.27 (via: http-client-tls-0.3.5.3 tls-1.5.4 x509-validation-1.6.11
x509-store-1.6.7 x509-1.7.5) (new package)
asn1-types-0.3.4 (via: tls-1.5.4 x509-validation-1.6.11 x509-store-1.6.7
x509-1.7.5 asn1-parse-0.9.5 asn1-encoding-0.9.6) (new package)
blaze-html-0.9.1.2 (via: pandoc-2.11.0.4 xml-conduit-1.8.0.1
skylighting-core-0.10.0.3) (new package)
hxt-9.3.1.18 (via: skylighting-core-0.10.0.3) (new package)
text-conversions-0.3.1 (via: pandoc-2.11.0.4 doctemplates-0.8.2) (new package)
pandoc-types-1.22 (via: pandoc-2.11.0.4 citeproc-0.1.0.3
commonmark-pandoc-0.2.0.1 texmath-0.12.0.3) (new package)
ipynb-0.1.0.1 (via: pandoc-2.11.0.4) (new package)
aeson-pretty-0.8.8 (via: pandoc-2.11.0.4) (new package)
http-client-0.7.2.1 (via: pandoc-2.11.0.4 http-client-tls-0.3.5.3) (new
package)
conduit-extra-1.3.5 (via: xml-conduit-1.8.0.1) (new package)
asn1-encoding-0.9.6 (via: tls-1.5.4 x509-validation-1.6.11 x509-store-1.6.7
x509-1.7.5 asn1-parse-0.9.5) (new package)
skylighting-core-0.10.0.3 (via: pandoc-2.11.0.4 skylighting-0.10.0.3) (new
package)
doctemplates-0.8.2 (via: pandoc-2.11.0.4) (new package)
texmath-0.12.0.3 (via: pandoc-2.11.0.4) (new package)
commonmark-pandoc-0.2.0.1 (via: pandoc-2.11.0.4) (new package)
xml-conduit-1.8.0.1 (latest: 1.9.0.0) (via: citeproc-0.1.0.3) (new package)
asn1-parse-0.9.5 (via: x509-1.7.5) (new package)
skylighting-0.10.0.3 (via: pandoc-2.11.0.4) (new package)
citeproc-0.1.0.3 (via: pandoc-2.11.0.4) (new package)
x509-1.7.5 (via: connection-0.3.1 tls-1.5.4 x509-system-1.6.6
x509-validation-1.6.11 x509-store-1.6.7) (new package)
x509-store-1.6.7 (via: connection-0.3.1 tls-1.5.4 x509-system-1.6.6
x509-validation-1.6.11) (new package)
x509-validation-1.6.11 (via: connection-0.3.1 tls-1.5.4) (new package)
x509-system-1.6.6 (via: connection-0.3.1) (new package)
tls-1.5.4 (via: http-client-tls-0.3.5.3 connection-0.3.1) (new package)
connection-0.3.1 (via: pandoc-2.11.0.4 http-client-tls-0.3.5.3) (new package)
http-client-tls-0.3.5.3 (via: pandoc-2.11.0.4) (new package)
pandoc-2.11.0.4 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
yaml-0.11.5.0
hlint-3.2.1
Use --force-reinstalls if you want to install anyway.

**Comment by mb21** [comment]
Well, our CI is building it with ghc 8.10.2 (see e.g. https://github.com/jgm/pandoc/runs/1336121968), but I think you need to use cabal v2

see also https://pandoc.org/installing.html

You also don't mention which OSS you're on...  but for future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by tarleb** [comment]
This is about cabal reinstalling packages which are also used by other programs installed via cabal v1. It has nothing to do with pandoc.
