### ISSUE TITLE
Wrong macro argument position in command definition

### ISSUE THREAD

**Issue by peterzjx** [jgm/pandoc#6796]
Here is a minimum working sample
```
\documentclass[]{amsart}
\newcommand{\cL}{\mathcal{L}}
\newcommand{\til}[1]{\tilde{#1}}
\begin{document}
$$\til\cL$$
\end{document}
```
Expecting `\tilde{\mathcal{L}}` but getting `\tilde{\mathcal}{L}`. Seems reproducible for several other format commands (e.g. `\textrm`). No matter which macro gets expanded first it should not separate the argument of `mathcal` whatsoever.
Command used: `pandoc -t markdown -f latex 1.tex -o 1.md` with pandoc version 2.10

**Comment by jgm** [comment]
I need to look again at the code, but looks like we are expanding `\cL` before parsing for parameters of `\til`. Instead, we need to parse parameters first and then expand them.
