### ISSUE TITLE
RawInline and RawBlock with format 'plain' are not rendering when output to plain

### ISSUE THREAD

**Issue by averms** [jgm/pandoc#6797]
I am experimenting with a filter that augments the plain text output of Pandoc and I am using RawInline quite often. One surprising thing I found out was that you can never make them render with the plain output.
Here is an example filter:

```lua
return {
  {
    Code = function(elem)
      return pandoc.RawInline('plain', 'balls')
    end,

    CodeBlock = function(elem)
      return pandoc.RawBlock('plain', 'doodoo')
    end
  }
}
```

If you run it with `pandoc --verbose` you get messages like

```
[INFO] Not rendering RawInline (Format "plain") "balls"
[INFO] Not rendering RawBlock (Format "plain") "doodoo"
```

Is this on purpose? If yes, can it be changed?

**Comment by tarleb** [comment]
The behavior is defined [here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Markdown.hs#L1237-L1240). As you can see, using `markdown` instead of `plain` would work in this case.
I think `plain` would be a logical addition to that list. Would you like to open a PR?

**Comment by tarleb** [comment]
My first reply was nonsense, so I deleted it.
It seems that this behavior [is intended](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Markdown.hs#L1237); but it would be logical to me to output `plain` entries, so we might want to change this?

**Comment by jgm** [comment]
Yes, I think it would be fine to emit raw content marked as `plain` in `plain` output.

**Comment by ncfavier** [comment]
This looks like it was fixed in https://github.com/jgm/pandoc/commit/0b254ea4af38cf53c027eb5e9977e96c2b7975c7?

What I don't understand is why `RawInline`s aren't always rendered by first parsing their contents (if the format is known and supported) and then rendering it?

**Comment by tarleb** [comment]
Thanks for noticing @ncfavier; closing.
