### ISSUE TITLE
Epub can't jump from toc

### ISSUE THREAD

**Issue by ghost** [jgm/pandoc#6798]
Hi.
I would like to use pandoc convert a gfm file to epub.But it can't jump to chapter from toc.
I use this command to convert
```
pandoc.exe -f gfm --metadata title="ex" -s -o .\ch1.epub -t epub .\ch1.md
# ch1.md can download from https://github.com/Vonng/ddia/blob/master/ch1.md
```

pandoc version:2.10.1

How to correct it?

**Comment by mb21** [comment]
Do you have a minimal example of a code snippet that demonstrates the problem? Also, what epub viewers have you tried?

**Comment by noxmoe** [comment]
Epub reader is Sterra. It use edgehtml.

Example markdown file can download from [https://github.com/Vonng/ddia/blob/master/ch1.md](https://github.com/Vonng/ddia/blob/master/ch1.md).

Epub file can download from [here](https://drive.google.com/drive/folders/1jJgbZK23OkAFZO6aok_fnOQSksGINpVB?usp=sharing)

incorrect.epub is generated by pandoc use this command

```
pandoc.exe -f gfm --metadata title="ex" -s -o .\ch1.epub -t epub .\ch1.md
```

correct.epub is generated by typora (a markdown editor). It use pandoc to generate epub from native.

```
pandoc -f native -o ./ch1.epub -t epub 
```

**Comment by jgm** [comment]
I don't see the problem. The TOC links work for me on my ereader.
Also, I don't see how there could be much of a difference if both are generated by pandoc ; the machinery for generating the TOC won't change depending on the different reader options.

Thus, closing.

**Comment by denisftw** [comment]
I see this is closed, but I want to comment just in case someone else stumbles upon it. The thing is that some readers don't like non-ASCII characters in header links. Specifically, Lucidor would jump to the top-level header (`#` in Markdown), but not to subheaders. A similar behavior may occur on some devices as well, i.e on old PocketBooks.

The solution is to use ASCII-identifiers: `pandoc -f markdown+ascii_identifiers`
