### ISSUE TITLE
[Enhancement] RAW format

### ISSUE THREAD

**Issue by sebi5361** [jgm/pandoc#6800]
# Enhancement: Adding the raw format

Sometimes one might have to **preprocess** a file to make it **pandoc-compatible** at first.
Adding the **raw** format would allow to use the pandoc CLI syntax to make preprocessing like standard **pandoc filtering**.

## Illustration
My Markdown file contains `@sinx@` which is common for AsciiMath notation.
I need to parse it to render AsciiMath notation to `$:a sinx$` to use [yuwash/asciimathml-pandocfilter](https://github.com/yuwash/asciimathml-pandocfilter) afterwards.
As `@` is a special element in **pandoc-markdown**, this substitution needs to be done **beforehand**.
Currently I am using a pre-pandoc-parser, but with the added **raw** format doing so might become useless.
The raw format would prevent pandoc from parsing its input to its internal dialect, thus allowing **filters not based on pandoc grammar** necessarily.

## Commands
Typing
`cat file.md | pandoc -f raw -F my_pre_pandoc_parser_becoming_a_pandoc_standard_filter_now | pandoc...`
rather than
`cat file.md | ./my_pre_pandoc_parser | pandoc...`

- - -

- [ ] Is this a good idea?
- [ ] Can it be done easily?

**Comment by mb21** [comment]
I think this already exists and it's called `-f native` ..?

**Comment by alerque** [comment]
> The raw format would prevent pandoc from parsing its input to its internal dialect, thus allowing **filters not based on pandoc grammar** necessarily.

What you are asking for is simply nonsensical. The filter system operates on the native internal AST format. What you want is a preprocessor not a filter. So just pre-process it. If you want syntax sugar try something like `pandoc <(my_ preprocessor file.md) ...`.

**Comment by sebi5361** [comment]
Indeed what I was asking is nonsensical once understanding the philosophy around pandoc.
I have nothing against the syntax of using a preprocessor. It was more about syntax sugar indeed.
Thanks so much for your enlightenments 😃
Am closing this thread.

**Comment by tarleb** [comment]
I think @sebi5361's proposal this is not too far from some ideas mentioned in #6393.

**Comment by tarleb** [comment]
BTW, on Mac and Linux you can simulate a `raw` reader like so:

    pandoc <(printf '```{=raw}') input.file <(printf '```')

**Comment by alerque** [comment]
@tarleb I think @sebi5361 is expecting the input to still be processed as Markdown by Pandoc.

**Comment by tarleb** [comment]
Thanks @alerque; I should have read more closely. :+1:

**Comment by sebi5361** [comment]
Very close indeed to what @tarleb mentioned.
Good to know about the `{=raw}` / `RawBlock` field encapsulation possibility.
Thanks to all of you for your reactivity and explanations 😀
