### ISSUE TITLE
pandoc-2.11.0.4 failed build on FreeBSD i386 system

### ISSUE THREAD

**Issue by wenheping** [jgm/pandoc#6804]
Hi,

    pandoc-2.11.0.4 build well on FreeBSD-amd64 system, but failed build on FreeBSD-i386 system, 
the last lines of build log is : 
[130 of 182] Compiling Text.Pandoc.Writers.Markdown
[131 of 182] Compiling Text.Pandoc.Writers.OPML
[132 of 182] Compiling Text.Pandoc.Writers.Ipynb
ghc: panic! (the 'impossible' happened)
  (GHC version 8.10.2:
        getClassPredTys
  Module
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:1179:37 in ghc:Outputable
        pprPanic, called at compiler/basicTypes/Predicate.hs:89:29 in ghc:Predicate

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug

cabal: Failed to build pandoc-2.11.0.4 (which is required by exe:pandoc from
pandoc-2.11.0.4).
 

Any suggestions ?

**Comment by mb21** [comment]
I'd try removing all temp files cabal stores anywhere on your system. If you can reproduce this on a clean system, e.g. using a docker image... guess we should do what is says:

> Please report this as a GHC bug: https://www.haskell.org/ghc/reportabug

**Comment by jgm** [comment]
Does it fail each time in the same place, or is it unpredictable?
Only other thing I can think of is to set the `lua_32bits` flag when compiling `hslua`.

**Comment by jgm** [comment]
Closing without further information.
