### ISSUE TITLE
--self-contained produce HTML that is not self-contained if rendered in IE <9

### ISSUE THREAD

**Issue by nod5** [jgm/pandoc#6809]
When converting Markdown files to HTML with parameter [--self-contained](https://pandoc.org/MANUAL.html#option--self-contained) the output contains
```
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
<![endif]-->
```
That seems inconsistent with the `--self-contained` documentation

> The resulting file should be “self-contained,” in the sense that it needs no external files and no net access to be displayed properly by a browser. 

To reproduce the above use Pandoc 2.11.04 on Windows 10, save string `# test` to file `test.md` and then run
`pandoc.exe --to html test.md --self-contained -o test.html`

Background: I open the pandoc created HTML files both in modern browsers (no issue there) but also in an older application using embedded Internet Explorer in document mode IE7. There the html5shiv line causes the app to freeze. My current workaround is to remove the offending html5shiv lines with other tools downstream from pandoc. But I'd rather have pandoc not add those non-self-contained lines.

Note: With `--to html4` no html5shiv lines are added, naturally. But I want HTML5 output, but without non-self-contained content.

**Comment by jgm** [comment]
The problem is that the process of making the HTML self-contained begins by tokenizing the HTML using an HTML5-compatible tokenizer.  So this whole thing comes out as a comment and we ignore the script element embedded in it.

IE < 9 is so rare now that I don't know if it's worth introducing additional complexities to deal with this. My advice for you would be to use a custom template that omits this code.

**Comment by nod5** [comment]
Ok, I'll consider this known/official behaviour of `--self-contained` for HTML5 output then.

Tip to others who might find this through search and want a custom template: modifying [default.html5](https://github.com/jgm/pandoc-templates/blob/master/default.html5) via `sed` like this
```
sed -i "/<!--\[if lt IE 9]>/I,+2 d" default.html5
```
removes these lines
```
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
<![endif]-->
```

**Comment by jgm** [comment]
Today I removed the html5shiv comment from the default template. I think at this point we can stop worrying about supporting IE 8.
