### ISSUE TITLE
LaTeX reader: matrix environment inside tabular broken

### ISSUE THREAD

**Issue by tumidi** [jgm/pandoc#6811]
I encountered an issue with LaTeX to Markdown conversion using a `matrix` inside a `tabular` environment. I've created a minimal example.

Input:
```latex
\begin{tabular}{ll}
  1 & $\begin{matrix}{2\\3}\end{matrix}$ \\
\end{tabular}
```

Output:
```markdown
ll 1 & $\begin{matrix}{2\\3}\end{matrix}$\
```

Expected output:
```markdown
  --- ------------------------------------
  1   $\begin{matrix}{2\\3}\end{matrix}$
  --- ------------------------------------
```

The command line used:

```sh
$ pandoc --to=markdown test.tex
```

I thoroughly searched both issue tracker and mailing list for a similar problem.

Apparently pandoc fails to recognize the tabular environment as it gets confused by the double backslash of the `matrix` environment.

```sh
$ pandoc -v
pandoc 2.11.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.1.0.3, ipynb 0.1.0.1
```

**Comment by jgm** [comment]
I understand the problem.

In parsing tables rows, first we split the contents into "raw cells", and then we parse the tokens in these cells.  The splitting process is evidently too simple and gets confused by the `\\`.  See around l.2170 of the LaTeX reader.

It may be that we can rewrite with a continuous parse and avoid the splitting altogether.
