### ISSUE TITLE
Double quote character in backtick code blocks using Ubuntu Mono with LuaLaTeX

### ISSUE THREAD

**Issue by VincentTam** [jgm/pandoc#6812]
pandoc version: 2.5
OS: Ubuntu 20.04
Input: Markdown
Target output: PDF
PDF engine: LuaLaTeX
Minimal example `test.md` to show the bug:
~~~
---
monofont: Ubuntu Mono
---

`"a"`
~~~
command: `pandoc --pdf-engine=lualatex test.md -o test.pdf`
output: curly double quotes
![image](https://user-images.githubusercontent.com/5748535/98267669-ece0c200-1f8b-11eb-955c-c39b76537f57.png)
expected output: symmetric double quotes `"`
![image](https://user-images.githubusercontent.com/5748535/98268132-709aae80-1f8c-11eb-949b-ac7b92abb35e.png)
source code for above picture: `test.tex` compiled with `lualatex test.tex`
```tex
documentclass[preview]{standalone}
\usepackage{fontspec}
\setmonofont{Ubuntu Mono}
\begin{document}
\texttt{"a"}
\end{document}
```
My TeX Live 2020 has been installed directly from tug.org, and its version number is v1.12.0.
![my texlive 2020](https://i.stack.imgur.com/Kp9Ob.png)
Screenshot showing my TeX Live version number from [my earlier TeX.SE question](https://tex.stackexchange.com/q/568030/126386)

**Comment by mb21** [comment]
Can you try with the newest pandoc version?

You can also debug it using `-t latex` or probably fix it by turning off the `smart` extension..

**Comment by VincentTam** [comment]
@mb21 Thanks for quick reply.  I've found out the reason for this by `pandoc -s test.md -o test.md`.  It's caused by a line `\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}`.  Once this line is commented out, everything is fine.  I would if there's a way to disable this.  Is there a way to get rid of `Mapping=tex-ansi` in the following line?

```tex
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
    \setmonofont[Mapping=tex-ansi]{Ubuntu Mono}
\fi
```

![Screenshot from 2020-11-05 18-03-56](https://user-images.githubusercontent.com/5748535/98272370-4dbec900-1f91-11eb-8c20-e77657eb9a22.png)

**Comment by jgm** [comment]
Try with
```
---
monofont: Ubuntu Mono
monofontoptions:
- Ligatures=ResetAll
---
```
(untested)

I'm not sure where you're getting the `Mapping=tex-ansi`.
That is not inserted by pandoc with its default template.
Are you perhaps using a custom template, perhaps in the `templates` subdirectory of your user data directory?

**Comment by VincentTam** [comment]
![image](https://user-images.githubusercontent.com/5748535/98286513-697f9a80-1fa4-11eb-8254-d40e9a0e45a6.png)

@jgm This works.  Thx v. much!

**Comment by VincentTam** [comment]
> I'm not sure where you're getting the `Mapping=tex-ansi`.
> That is not inserted by pandoc with its default template.

The mapping is found at 9d9390a75ae8886f3a92ff785aa21c7dbfefba7d.

> Are you perhaps using a custom template, perhaps in the templates subdirectory of your user data directory?

Lemme check this tmr when I hav time.

**Comment by jgm** [comment]
The `Mapping=tex-ansi` used to be in the default template, but it isn't now (and hasn't beensince January 2019).  See 666bf8ac5cf2574303874be2cd8234e8b99ad459

**Comment by VincentTam** [comment]
oic.  Thanks for your response.  That's in v2.11.1.  I downloaded the latest stable release .deb, and everything's fine.
![image](https://user-images.githubusercontent.com/5748535/98299564-2e876200-1fb8-11eb-8df9-3c906e2d6a22.png)
