### ISSUE TITLE
Interaction between underscore and quotes in Markdown

### ISSUE THREAD

**Issue by gwselke** [jgm/pandoc#6818]
It seems to me that a quoted underscore "_" in  a Markdown document somehow throws off Pandoc's parser: the underscore comes out unquoted, but subsequent text comes out quoted.
(Note that there is only a single underscore in the input, and it is correctly recognized as NOT being an emphasis marker.)
Here's some small input to demonstrate:

Debitis ut et quia et exercitationem underscore ("_") amet vitae.
Percent sign ("%") Quos temporibus expedita facilis deserunt.

Here is the JSON-formatted AST:

{"pandoc-api-version":[1,22],"meta":{},"blocks":[{"t":"Para","c":[{"t":"Str","c":"Debitis"},{"t":"Space"},{"t":"Str","c":"ut"},{"t":"Space"},{"t":"Str","c":"et"},{"t":"Space"},{"t":"Str","c":"quia"},{"t":"Space"},{"t":"Str","c":"et"},{"t":"Space"},{"t":"Str","c":"exercitationem"},{"t":"Space"}**,{"t":"Str","c":"underscore"},{"t":"Space"},{"t":"Str","c":"(\"_"},{"t":"Quoted","c":[{"t":"DoubleQuote"},[{"t":"Str","c":")"},{"t":"Space"},{"t":"Str","c":"amet"},{"t":"Space"},{"t":"Str","c":"vitae."},{"t":"SoftBreak"},{"t":"Str","c":"Percent"},{"t":"Space"},{"t":"Str","c":"sign"},{"t":"Space"},{"t":"Str","c":"("}]]},{"t":"Str","c":"%\")"},{"t":"Space"},{"t":"Str","c":"Quos"},{"t":"Space"},{"t":"Str","c":"temporibus"},{"t":"Space"},{"t":"Str","c":"expedita"},{"t":"Space"},{"t":"Str","c":"facilis"},{"t":"Space"},{"t":"Str","c":"deserunt."}]}]}

I am running Pandoc 2.11.0.2 under Windows 10, using this command line:

``pandoc +RTS -K512m -RTS --from markdown --to json --output test.json < test.md``

Usually Pandoc is very good at intuiting my intentions, but in this case we seem to be at odds. I'd be happy, however, to learn that I have somehow incorrectly expressed my intentions here.

**Comment by jgm** [comment]
Very strange!  It's easier to see this with native output rather than json.
```
 % pandoc -t native
Debitis ut et quia et exercitationem underscore ("_") amet vitae.
Percent sign ("%") Quos temporibus expedita facilis deserunt.
[Para [Str "Debitis",Space,Str "ut",Space,Str "et",Space,Str "quia",Space,Str "et",Space,Str "exercitationem",Space,Str "underscore",Space,Str "(\"_",Quoted DoubleQuote [Str ")",Space,Str "amet",Space,Str "vitae.",SoftBreak,Str "Percent",Space,Str "sign",Space,Str "("],Str "%\")",Space,Str "Quos",Space,Str "temporibus",Space,Str "expedita",Space,Str "facilis",Space,Str "deserunt."]]
```

Apparently pandoc's smart-quote heuristics are failing here.  I'm not inclined to spend a long time figuring this out, though, because in the future we'll be moving to commonmark, and for that we have it pretty well figured out.

```
% pandoc -t native -f commonmark+smart
Debitis ut et quia et exercitationem underscore ("_") amet vitae.
Percent sign ("%") Quos temporibus expedita facilis deserunt.
[Para [Str "Debitis",Space,Str "ut",Space,Str "et",Space,Str "quia",Space,Str "et",Space,Str "exercitationem",Space,Str "underscore",Space,Str "(",Quoted DoubleQuote [Str "_"],Str ")",Space,Str "amet",Space,Str "vitae.",SoftBreak,Str "Percent",Space,Str "sign",Space,Str "(",Quoted DoubleQuote [Str "%"],Str ")",Space,Str "Quos",Space,Str "temporibus",Space,Str "expedita",Space,Str "facilis",Space,Str "deserunt."]]
```

**Comment by gwselke** [comment]
Thank you, John, for your quick reply! Yes, native output is indeed easier to read than json, sorry about that.
I have found a (possibly undocumented?) workaround with pandoc markdown: escape the underscore with a backslash. I'm fine with this.
Otherwise, I understand from your reply that these days using commonmark(_x) is the way to go. I will embark on this then!

Btw: thanks fo giving us pandoc!
