### ISSUE TITLE
Add a fancyhdr check before \maketitle to avoid misplacement of the page number

### ISSUE THREAD

**Issue by lygamac** [jgm/pandoc#6819]
The title page created with default latex template always has the page number centered. Page number positioning done by fancyhdr only starts to work after the second page.

Adding the following makes the title page behaves the same as the rest of pages:
```
\makeatletter
	\@ifpackageloaded{fancyhdr}{
	\fancypagestyle{plain}{}
	}
\makeatother
\maketitle
```

**Comment by jgm** [comment]
Currently `fancyhdr` is not loaded by default.
Wouldn't it make more sense for people using `fancyhdr` in a custom template or header-includes to add this customization if they want it?

**Comment by lygamac** [comment]
On second thoughts, that seems better.

I was thinking that in most people's template, the page number on the title page is wiped out. Removing the fancy seems to be a bit too strong.
