### ISSUE TITLE
[Feature Request] Highlight table header row

### ISSUE THREAD

**Issue by jcs090218** [jgm/pandoc#6822]
If I have a following table

```md
| Hello | World |
|-------|-------|
| data  | data  |
```

I think it will be better if highlight the first row (header)? Maybe make the word **bold** or change the background color, etc.

**Comment by tarleb** [comment]
Which target format are you referring to? PDF, HTML, or yet another?
It would also be helpful to learn more about how you are using tables, and why you think this would be a good change. Pandoc usually follows good typographic practices, so any typography resource supporting your request would be ideal. Otherwise we run into the realm of personal preferences and we try to avoid that as much as possible.

**Comment by jcs090218** [comment]
> Which target format are you referring to? PDF, HTML, or yet another?

I am using `pandoc` converting from `markdown` to `docx`.

> It would also be helpful to learn more about how you are using tables, and why you think this would be a good change. Pandoc usually follows good typographic practices, so any typography resource supporting your request would be ideal. Otherwise we land in the realm of personal preferences and we try to avoid that as much as possible.

Sounds good to me. This indeed may be a personal preferences thing; and yet it is why I mark it as **feature request**! ;)

Anyway, thanks for this amazing tool!

**Comment by jgm** [comment]
Current docx output is very much like current pdf output (neither bolds the heading).

**Comment by alerque** [comment]
You should be able to write a Lua filter that snags table heading cells and bolds the contents if that's the effect you want, or you can just do it it Markdown so that all formats actually have the same source and semantics.

**Comment by jgm** [comment]
Bolding of the header is a presentational detail.
You can modify the Table style in a reference.docx so that it automatically bolds the header.
That's the thing to do if you want that look.
