### ISSUE TITLE
Allow defaults files to inherit options from other defaults files

### ISSUE THREAD

**Issue by frederik-elwert** [jgm/pandoc#6827]
When using defaults files to simplify certain conversions, often multiple defaults files share certain settings. E.g., beamer, letter, and regular PDF output might share underlying latex settings.

It would be convenient if a defaults file could specify that it inherits settings from another defaults file. This would allow users to create a file with the shared properties and import this file in the more specific ones.

A straightforward mechanism for implementing this would be to allow the property `defaults` in the defaults files. E.g., the defaults file `letter.yaml` could looke like this:

```yaml
defaults:
    - latex
filters:
    - scrlttr2.lua
```

As a result, calling `pandoc -d letter` would be the same as previously `pandoc -d latex -d letter`.

A comparable mechanism was implemented in the pandoc wrapper [panopy](https://github.com/balachia/panopy). With the addition of defaults files, the tool became mostly obsolete, but the lack of inheritance makes defaults files currently less flexible.

**Comment by jgm** [comment]
This makes a lot of sense, I think.

**Comment by davidmrt98** [comment]
@frederik-elwert Do you plan on implementing this yourself? If that's not the case, I would like to work on it!

**Comment by frederik-elwert** [comment]
@davidmrt98 No, I don’t (unfortunately, my Haskell skills are virtually non-existent). But it would be great to see this, so you have my gratitude if you want to give it a shot!
