### ISSUE TITLE
Bug: `metadata: ...` is parsed as markdown [2.11.0.4]

### ISSUE THREAD

**Issue by gabyx** [jgm/pandoc#6829]
Maybe a bug, or I read the doc not correctly:

> metadata values specified here are parsed as literal
> string text, not markdown:
> metadata:

**Input:**
```markdown
---
metadata:
  "giraffe and zebra" : "`cool and humble  !`"
---
```

**Invoke**
`cat "test.md" | pandoc -t json`

**Output**

```json
{
  "pandoc-api-version": [1, 22],
  "meta": {
    "metadata": {
      "t": "MetaMap",
      "c": {
        "giraffe and zebra": {
          "t": "MetaInlines",
          "c": [{ "t": "Code", "c": [["", [], []], "cool and humble  !"] }]
        }
      }
    }
  },
  "blocks": []
}
```

I thought key "giraffe and zebra" its at least a `MetaString` but is a `Code` block.

**Comment by jgm** [comment]
`metadata` fields in *defaults files* are parsed as strings.
Your metadata field is in a YAML metadata block in a markdown file.
