### ISSUE TITLE
[MarkDown]: List content parsed as new list.

### ISSUE THREAD

**Issue by Kangie** [jgm/pandoc#6831]
For the following content: 

```MarkDown
* Essential:
    * 1; and
    * 999.
```

Pandoc interprets `* 999.` as a list item that contains a new ordered list beginning at 999:

```HTML
<ul>
<li>Essential:
<ul>
<li>1; and</li>
<li><ol start="999" type="1">
<li></li>
</ol></li>
</ul></li>
</ul>
```

Compare to the `Markdown.pl` output:

```HTML
<ul>
<li>Essential:
<ul>
<li>1; and</li>
<li>999.</li>
</ul></li>
</ul>
```

I'm not sure if this is desired behaviour - it seems to be compliant with the `commonmark.js` implementation. I'm currently working around the issue by inserting a zero width space between the `999` and the `.`, so this isn't a showstopper for me by any means, but thought it worth raising an issue to clarify the behaviour.

Tested on: pandoc 2.11.0.2; 2.11.1.1.

**Comment by jgm** [comment]
Yes, it's kind of a corner case.  You can make it clear that the `999.` isn't an ordered list marker by backslash-escaping the period:  `999\.`.
