### ISSUE TITLE
Allow to choose Markdown extensions used to parse metadata-file

### ISSUE THREAD

**Issue by naivenaive** [jgm/pandoc#6832]
I tried to use pandoc to convert html file to docx. I use a YAML file to provide metadata data. As per the description of [-metadata-file](https://pandoc.org/MANUAL.html#option--metadata-file), 'string scalars in the YAML file will **always be parsed as Markdown**.' However, the superscript and subscript cannot be parsed correctly.

Here is an example. (pandoc 2.10.1, windows-x86-64)
metadata.yaml:
`---
title: \"I am title\"

author: 
\- Author One\^1\^
\- Author Two\~2\~
\- Author Three\*3\*
\- Author Four\*\*4\*\*
---`

input.html:
'\<p\>I am input content\</p\>'

input.md:
'I am input content'

After calling `pandoc --metadata-file metadata.yaml input.html -o output_html.docx`, I get the following output_html.docx file.
'I am title
Author One\^1\^       //**Incorrect**
Author Two\~2\~        //**Incorrect**
Author Three*3*          
Author Four**4**        
I am input content
'
After calling `pandoc --metadata-file metadata.yaml input.md -o output_md.docx`, I get the following output_md.docx file.
'I am title
Author One<sup>1</sup> 
Author Two<sub>2</sub> 
Author Three*3*                
Author Four**4**               
I am input content
'
The emphasis symbol(*, **) can be parsed correctly. However, the superscript and subscript of metadata.yaml can only be handled and display correctly when the input is in .md format and **can not** be handled correctly when the input file is in .html format. 
Please help to solve the problem.

**Comment by jgm** [comment]
This is due to #5272 (commit https://github.com/jgm/pandoc/commit/0216b68aae35c2935247667b9c61271e6d122b48).

Yes, it's parsed as markdown -- but there's a question which extensions are enabled on the markdown.

After the fix to #5272, we use the extensions enabled on the reader. This makes sense, in that if you do `-f gfm`, then gfm extensions are enabled in the metadata file, and if you do `-f markdown`, then pandoc extensions are enabled, etc.  But when your main input is HTML, it means that no markdown extensions will be enabled, because HTML doesn't take markdown extensions.

**Comment by jgm** [comment]
I'm not really sure what the best solution is, since the fix to #5272 was well motivated and makes sense in most contexts.

**Comment by naivenaive** [comment]
Thanks for your help. 

I think metadata.yaml is parsed as gfm format in default so the superscript(^) and subscript(~) symbol cannot be parsed correctly but the bold(**) and italic(*) symbol can be parsed.  Is it possible to set the default parser of metadata.yaml to pandoc markdown parser instead of gfm parser?

**Comment by jgm** [comment]
It's possible, and in fact it was done like this before the change noted above.
It was thought useful to allow the extensions to be determined by the user, but I don't think we considered the case where the main input format is not markdown.

**Comment by naivenaive** [comment]
Yes, It will be great to let users determine which parser is used to parse metadata.yaml. Despite the main input format is not markdown, Pandoc performs very well in converting .html file to .docx file. There is only small problem in parsing metadata.yaml.

**Comment by mb21** [comment]
> I don't think we considered the case where the main input format is not markdown.

Nope, we left that case to solve for a later time... from https://github.com/jgm/pandoc/issues/1960#issuecomment-376457466:

> We can always add more things later, like:
> - parsing `.. meta::` in RST or `<meta>` in HTML (which would act analogous to the current YAML metadata blocks in markdown)
> - adding an additional option that specifies the markup language the metadata is interpreted as (overriding the default which would be set to markdown).

**Comment by tarleb** [comment]
Closing in favor of the more general issue #5914.
