### ISSUE TITLE
paragraphs after first one in fenced div are dropped if the class name ".output" is used

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#6841]
When using Pandoc v2.11.1.1 I am seeing paragraph after the first one in a fenced DIV dropped from the AST **if and only if** the `.output` class is included for the fenced div. e.g For this markdown source:

```markdown
::: {.output}
1

2

3
:::
```

The AST is transformed to:

```bash
$ pandoc input.md --to json | jq .
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": [
    {
      "t": "Div",
      "c": [
        [
          "",
          [
            "output"
          ],
          []
        ],
        [
          {
            "t": "Para",
            "c": [
              {
                "t": "Str",
                "c": "1"
              }
            ]
          }
        ]
      ]
    }
  ]
}
```

**Comment by tarleb** [comment]
Confirmed that this happens no matter the input format. It appears to be caused by code used to clean ipynb output. Workaround: set `--ipynb-output=all`.

**Comment by jgm** [comment]
I've dealt with this by making the filterIpynbOutput step conditional on the input format being `ipynb`.
I think that's the best approach, but please let me know if it's a bad idea or if you have a better one.
