### ISSUE TITLE
Error in the haskell API documentation

### ISSUE THREAD

**Issue by danieltuzes** [jgm/pandoc#6849]
Please check the [pandoc Hackage documentation](http://hackage.haskell.org/package/pandoc). Some html elements are escaped accidentally, therefore html code is visiable:
```
 <!-- Do not edit this file. It is generated automatically from README.template and MANUAL.txt via the command: pandoc --lua-filter tools/update-readme.lua README.template -o README.md --> 
 <div id="input-formats"> 
 </div> 
```

**Comment by jgm** [comment]
This is an issue with hackage-server; there's nothing we can do about it.
This issue should fix it, if they ever resolve it:
https://github.com/haskell/hackage-server/issues/565
Looks like they have a PR that is not quite working:
https://github.com/haskell/hackage-server/pull/904
