### ISSUE TITLE
hslua: Dynamic loading not supported

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#6850]
```
pandoc 2.11.1.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.1.1.1, ipynb 0.1.0.1
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
/usr/bin/luarocks 3.4.0
Arch Linux:
lua53-MobDebug 0.70.r15.g9959357-1
lua53-socket 20200329-1
export LUA_PATH='/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua'
export LUA_CPATH='/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so'
```

Following the instructions in <https://github.com/pandoc/lua-filters/tree/master/lua-debug-example>, I installed mobdebug and luasocket. Trying to run a filter results in complaints:
```
Error running filter /home/gesh/.local/share/pandoc/filters/highlight.lua:
error loading module 'socket.core' from file '/usr/lib/lua/5.3/socket/core.so':
	Dynamic loading not supported
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/share/lua/5.3/socket.lua:12: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.3/mobdebug.lua:99: in main chunk
	[C]: in function 'require'
	/home/gesh/.local/share/pandoc/filters/highlight.lua:1: in main chunk
```
In contrast, trying to ```require('socket.core')``` in a lua repl works fine. Digging deeper, I note pandoc uses hslua -- possibly it is that which is at fault?

**Comment by hseg** [comment]
I note that hslua has a flag ```export-dynamic```, on by default, and not disabled by Pandoc, that should make dynamic loading of c libraries possible.

**Comment by jgm** [comment]
Are you using the statically compiled executable we provide?  It doesn't allow dynamic loading, but if you self-compile pandoc it should work.

**Comment by tarleb** [comment]
Another option would be [pandoc Docker images](https://hub.docker.com/u/pandoc). The binaries therein are compiled with support for dynamic loading of C libraries.

**Comment by jgm** [comment]
@tarleb have we documented this restriction on the binary packages somewhere? I thought we had, but I can't seem to find it.

Also, maybe I'll try to include something in `--version` output to indicate whether dynamic linking is supported?

**Comment by tarleb** [comment]
It's documented in the third paragraph [here](https://pandoc.org/installing.html#linux). Maybe we should make this more visible somehow?

Including this in `--version` output would be great. I don't know the first thing about that, though.

**Comment by jgm** [comment]
I think the documentation is fine.  Not clear how to determine this for `--version` output.  We could have the `static` flag for pandoc set a CPP macro that we can check.  But I think this flag is borderline obsolete, since static linking options are now being included in the build tools, so this wouldn't be reliable (you could create a static build without using this flag).

What about, instead, trapping the "Dynamic loading not supported" error from lua and emitting a more informative message, like
```
Error running filter /home/gesh/.local/share/pandoc/filters/highlight.lua:
error loading module 'socket.core' from file '/usr/lib/lua/5.3/socket/core.so':
	Dynamic loading not supported
Statically linked pandoc binaries do not support dynamic loading.
```

**Comment by jgm** [comment]
I think I'll leave things as they are for now.  If we get more confusion like this, we can revisit.

**Comment by hseg** [comment]
OK. Noted this on the [Arch Linux package](https://aur.archlinux.org/packages/pandoc-bin/#comment-776019) to hopefully avoid others running into this problem.

**Comment by hseg** [comment]
It might be an idea to trap the error and be more explicit, but the status quo is OK.

**Comment by jgm** [comment]
Note that there's no reason the Arch package couldn't statically link in all the Haskell dependencies without being full static.  The default stack build will do this and should support dynamic loading of lua modules.  We provide a fully static binary for linux so that it will work with as many distros as possible, but Arch doesn't have that concern.

**Comment by hseg** [comment]
That package basically redistributes the static generic Linux binary pandoc provides. Is there an official release that does this or is it up to distributions to make the choice between full dynamic/static Haskell, dynamic lua/full static, with the associated build costs? As far as I understand, the binary release only gives the third option, with the two others requiring users/distributions to build things themselves, even if they're the most full-featured versions.

On November 18, 2020 12:26:38 AM GMT+02:00, John MacFarlane <notifications@github.com> wrote:
>Note that there's no reason the Arch package couldn't statically link
>in all the Haskell dependencies without being full static.  The default
>stack build will do this and should support dynamic loading of lua
>modules.  We provide a fully static binary for linux so that it will
>work with as many distros as possible, but Arch doesn't have that
>concern.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/6850#issuecomment-729251371

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jgm** [comment]
Correct, it's up to distros to build themselves.  We provide the fully static binary so we don't have to build different binaries for different distros -- that's something the distros should do, not us.

**Comment by hseg** [comment]
Because any amount of dynamic linking is dependent on the location and identity of shared libraries being consistent among users, and so is better done by distros?

On November 18, 2020 9:16:58 AM GMT+02:00, John MacFarlane <notifications@github.com> wrote:
>Correct, it's up to distros to build themselves.  We provide the fully
>static binary so we don't have to build different binaries for
>different distros -- that's something the distros should do, not us.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/6850#issuecomment-729486358

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jgm** [comment]
My memory is that to support dynamic linking, we need to dynamically link to libc, but there are different versions of this for different distros, so you don't get something that is really portable.
