### ISSUE TITLE
Make list of tags for self-contained data-uri embedding configurable?

### ISSUE THREAD

**Issue by alexbozhenko** [jgm/pandoc#6854]
[Self-contained option](https://pandoc.org/MANUAL.html#option--self-contained) allows to embed assets using [data uris](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)
 
The list of the tags that are being processed by this seems to be hard-coded in here:
https://github.com/jgm/pandoc/blob/94c9028819415a874b2469890de44108a98f8c48/src/Text/Pandoc/SelfContained.hs#L59-L60

I would be nice to allow it to process other customs tags as well. For example, to use it with [asciinema-player tag](https://github.com/asciinema/asciinema-player#use-the-player-in-your-html-page).

Do you think it is a reasonable request? If so, should it be a cli flag? Would you be open to a pull request for this?

**Comment by jgm** [comment]
I wonder if it would work to do this by default for anything that has a `src` attribute?

**Comment by alexbozhenko** [comment]
I think it makes sense. I did not find a list of valid tags with src attribute in rfc for html, but mozilla has this:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

**Comment by alexbozhenko** [comment]
Nice! Thank you very much John!

**Comment by cagix** [comment]
this would easily break many workflows. ~~currently~~ previously the behaviour is to embed all **local** assets, but with this change suddenly even links/url would be embedded?! i.e. i'd forced to add a "date=external" to each and every url? 

if you implement this, please also add an option to allow users to configure the elements to be embedded!

**Comment by jgm** [comment]
No.  Links are not embedded.  `href` elements are embedded only on `link` elements.

**Comment by jgm** [comment]
And no -- previously the behavior was not limited to local assets.
The feature is designed to give you an HTML file that can be viewed without any access to the net.

**Comment by cagix** [comment]
oh, my understanding was that something like `[alt](url)` would be parsed as `link` element i.e. given the behavior implemented in this ticket, it would then be embedded in the target document. apparently there was a misunderstanding on my part.

**Comment by cagix** [comment]
ok, now i see my confusion: i read "link" and "href" and thought of links (urls). But you meant images and other links with a `src` attribute, didn't you?

**Comment by jgm** [comment]
Yes, `src` attributes (and stuff like `poster`) -- `href` too, but only for `link` (which is e.g. for stylesheets, not hyperlinks).

**Comment by cderv** [comment]
Just sharing that it also happens with `<iframe>` tags. Usually, when included in a document you plan to have online access, but you could still want self contained content for the other dependencies. 

It broke some document created using **rmarkdown** tools which uses Pandoc. However, using `data-external="1"` allows to easily prevent this from happening for iframes but I wonder if it is expected to have those tags also concerned by the self-contained mechanism.

**Comment by jgm** [comment]
iframes have a `src` attribute, so yes, they are treated the same, as seems proper (otherwise your document isn't really self-contained).

**Comment by cderv** [comment]
I understand. It makes senses for self contained meaning no net access needed. Thanks!
