### ISSUE TITLE
LaTeX writer: improve table spacing?

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#6860]
See https://tex.stackexchange.com/questions/571329/minipage-in-table-has-strange-inter-row-spacing
for some suggestions.
It's unclear whether this approach will work for all the block-level constructions we need to support; this needs investigation.

**Comment by Delanii** [comment]
Both suggestions in linked question are from LaTeX experts. However, accepted answer to me does not seem to be applicable for pandoc-generated TeX code. I think that the `\setlist` command acts globally, so all following `itemize` lists would have the same behavior. Would that be intended for pandoc?
Are there any situations, in which it is known, that p (parbox) columns are not acceptable? As far as I know, it is need to set theyre column width manually.
Solution from Mico seems simpler, but looks like it is limited to `booktabs` package.
I hope I am not hijacking conversation, just thought to point that out (but maybe its obvious) ...
Regards, Tomas

**Comment by jgm** [comment]
I think the linked answer has `\setlist` acting just within the context of the longtable.

**Comment by Delanii** [comment]
Oh, you are right, I am sorry for that misinformation.

**Comment by jgm** [comment]
Experimented a bit.
Removing the `\strut`s and replacing `\tabularnewline` with `\\ \addlinespace`, as suggested in the linked post, does seem to improve things for the cases I checked.
