### ISSUE TITLE
Alignment of task_lists in markdown output

### ISSUE THREAD

**Issue by amitbeka** [jgm/pandoc#6866]
Hello,

I've noticed that using task lists with pandoc (version 2.12.2), the ASCII checkbox (`[ ]`) is considered as part of the list item, and not part of the bullet. Since this is the case, when line breaks are part of the markdown output, the alignment seems wrong.

Example:

```
- [ ] main item:
  - [ ] secondary item
- [ ] some very long text that eventually will be wrapped automatically if the settings are there
```

Command:

```
pandoc -f markdown -t markdown --tab-stop 2 sample.md
```

Current output:

```
- [ ] main item:
  - [ ] secondary item
- [ ] some very long text that eventually will be wrapped automatically
  if the settings are there
```

In the desired output, at least according to my personal taste and understanding, the word "automatically" should be aligned with the word "some", not with the checkbox. This is of course also happening when having explicit line breaks and using `--wrap=preserve`.

A few questions follow:

1. Is this intended behavior or a bug?
2. Does it happen when converting from another format that contains checkboxes to markdown? I tried vimwiki, but it fails in other ways (returns `- []{.done0}main item:`)
3. Assuming the words should be aligned with each other and not with the checkbox, is this also the desired behavior for nested lists? I think aestechically the main/secondary items are aligned correctly, while the words are not (so one bullet aligns with the middle of the second bullet)

Thanks a lot!

**Comment by mb21** [comment]
I think it's just a side-effect of how we represent task_lists in pandoc's internal AST. It's just a normal unordered list, with the first character being a unicode checkbox:

```
~ pandoc -t native
- [ ] item one
- [x] item two

^D

[BulletList
 [[Plain [Str "\9744",Space,Str "item",Space,Str "one"]]
 ,[Plain [Str "\9746",Space,Str "item",Space,Str "two"]]]]
```

Note that pandoc's markdown writer is not a pretty-printer and lacks extensive ways to customize the output.

> Does it happen when converting from another format that contains checkboxes to markdown?

yes, although I'm not sure which other pandoc readers support task lists..

**Comment by amitbeka** [comment]
I see, thanks for the quick reply. I generally think the markdown output should be pretty (as an output format), but I guess the number of use cases is quite small (except re-formatting existing markdown).

**Comment by lollipopman** [comment]
I would love to see this issue reopened as it makes the current markdown output harder to read.
