### ISSUE TITLE
roff -> asciidoc: '.IP' formatting is elided from resulting asciidoc file

### ISSUE THREAD

**Issue by ThomasAdam** [jgm/pandoc#6868]
Hi,

@jgm -- I suspect this is a variation of 0962b30d8428ef875034c15ae7d9c67c62c2f177 -- if that makes things easier for you.  I would have loved to have had a crack at submitting a PR for this myself, but I know nothing about Haskell, alas.

Pandoc version:

```
 % ./.local/bin/pandoc --version
pandoc 2.11.2
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.2, ipynb 0.1
User data directory: /home/n6tadam/.local/share/pandoc or /home/n6tadam/.pandoc
```

The following roff example doesn't produce correct AsciiDoc formatting:

```
.TH FvwmAnimate 1 "DATE" Fvwm "Fvwm Modules"
.UC
.SH NAME
\fBFvwmAnimate\fP \- the fvwm animate module

.IP "*FvwmAnimate: Color \fBcolor\fP"
Tells \fBFvwmAnimate\fP what color to draw with.
The color is "XOR'ed" (exclusive ORed) onto the background.
Depending on the display type you are using,  the effect this
causes will vary.  Especially on 8-bit displays, it helps if the background
is a solid color.  You have to experiment with this to see how it works.

The default color is not really a color and can be entered as "Black^White",
or more simply "None".  This is the same as the default XOR mask used
by fvwm for move and resize frames.

Other colors can be specified using standard X color notation.  Ie. color
names like "LightBlue", or RGB values like "#FFFFFF".
```

The pandoc command I'm using is:

```
pandoc -s -f man -t asciidoctor ./FvwmAnimate.1 -o ./FvwmAnimate.adoc
```

What this produces is the following:

```
= FvwmAnimate(1)

== NAME

*FvwmAnimate* - the fvwm animate module

* Tells *FvwmAnimate* what color to draw with. The color is "XOR'ed"
(exclusive ORed) onto the background. Depending on the display type you
are using, the effect this causes will vary. Especially on 8-bit
displays, it helps if the background is a solid color. You have to
experiment with this to see how it works.

The default color is not really a color and can be entered as
"Black^White", or more simply "None". This is the same as the default
XOR mask used by fvwm for move and resize frames.

Other colors can be specified using standard X color notation. Ie. color
names like "LightBlue", or RGB values like "#FFFFFF".
```

What should be produced in terms of `Asciidoc` output is:

```
*FvwmAnimate: Color color::

	Tells *FvwmAnimate* what color to draw with. The color is "XOR'ed"
	(exclusive ORed) onto the background. Depending on the display type you
	are using, the effect this causes will vary. Especially on 8-bit
	displays, it helps if the background is a solid color. You have to
	experiment with this to see how it works.

	The default color is not really a color and can be entered as
	"Black^White", or more simply "None". This is the same as the default
	XOR mask used by fvwm for move and resize frames.

	Other colors can be specified using standard X color notation. Ie. color
	names like "LightBlue", or RGB values like "#FFFFFF".
```

Note that:

1.  The original .IP line (`.IP "*FvwmAnimate: Color \fBcolor\fP"`) doesn't exist in the asciidoc output at all.
2.  The  first paragraph after where the `.IP` would have been, starts with an asterisk, which is incorrect.

Thanks again for your help!

Thomas

**Comment by jgm** [comment]
Are you sure you're running the latest pandoc?
I get this output:
```
== NAME

*FvwmAnimate* - the fvwm animate module

*FvwmAnimate: Color color::
  Tells *FvwmAnimate* what color to draw with. The color is "XOR'ed"
  (exclusive ORed) onto the background. Depending on the display type
  you are using, the effect this causes will vary. Especially on 8-bit
  displays, it helps if the background is a solid color. You have to
  experiment with this to see how it works.

The default color is not really a color and can be entered as
"Black^White", or more simply "None". This is the same as the default
XOR mask used by fvwm for move and resize frames.

Other colors can be specified using standard X color notation. Ie. color
names like "LightBlue", or RGB values like "#FFFFFF".
```
Confirmed by <https://pandoc.org/try/?text=.TH+FvwmAnimate+1+%22DATE%22+Fvwm+%22Fvwm+Modules%22%0A.UC%0A.SH+NAME%0A%5CfBFvwmAnimate%5CfP+%5C-+the+fvwm+animate+module%0A%0A.IP+%22*FvwmAnimate%3A+Color+%5CfBcolor%5CfP%22%0ATells+%5CfBFvwmAnimate%5CfP+what+color+to+draw+with.%0AThe+color+is+%22XOR%27ed%22+(exclusive+ORed)+onto+the+background.%0ADepending+on+the+display+type+you+are+using%2C++the+effect+this%0Acauses+will+vary.++Especially+on+8-bit+displays%2C+it+helps+if+the+background%0Ais+a+solid+color.++You+have+to+experiment+with+this+to+see+how+it+works.%0A%0AThe+default+color+is+not+really+a+color+and+can+be+entered+as+%22Black%5EWhite%22%2C%0Aor+more+simply+%22None%22.++This+is+the+same+as+the+default+XOR+mask+used%0Aby+fvwm+for+move+and+resize+frames.%0A%0AOther+colors+can+be+specified+using+standard+X+color+notation.++Ie.+color%0Anames+like+%22LightBlue%22%2C+or+RGB+values+like+%22%23FFFFFF%22.%0A&from=man&to=asciidoctor&standalone=0>

**Comment by ThomasAdam** [comment]
Hi.

Well, don't I feel stupid.  I hadn't updated PATH correctly.  All fixed, and apologies for the noise!
