### ISSUE TITLE
Path to custom writer fails when using --defaults

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#6872]
Using a custom writer (https://github.com/iandol/dotpandoc/blob/master/bbcode.lua but I suspect which writer is irrelevant) I can specify a path and everything works:

```
➜ pandoc -t ~/.local/share/pandoc/bbcode.lua
This is a `test` to see what happens.
This is a [color=#BF2700][b]test[/b][/color] to see what happens.
```

But if I also specify a defaults file, then pandoc prepends `templates/default.` to the custom writer file path and fails.

```
➜ pandoc --defaults refs -t ~/.local/share/pandoc/bbcode.lua
Could not find data file templates/default./Users/ian/.local/share/pandoc/bbcode.lua
```

`pandoc` version:

```
➜ pandoc --version
pandoc 2.11.2
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.2, ipynb 0.1.0.1
User data directory: /Users/ian/.local/share/pandoc or /Users/ian/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
Does your defaults style have `standalone: true`?
Pandoc seems to be seeking a template for your custom writer.

**Comment by iandol** [comment]
Yes, `standalone: true` is set; here is the defaults file: 

https://github.com/iandol/dotpandoc/blob/master/defaults/refs.yaml  

The custom writer was made by @tajmone...

**Comment by iandol** [comment]
If I specify `--data-dir` explicitly then I get a slightly different broken directory:

```
➜ pandoc -d refs --data-dir ~/.local/share/pandoc -t bbcode.lua
Could not find data file templates/default.bbcode.lua
```

**Comment by jgm** [comment]
>  Yes, standalone: true is set;

Well that's the answer.  As I said, it's looking for a template (as usual, based on the writer name, which in this case is the name of your custom writer).  You need to specify a template explicitly if you want one, or don't use standalone.

**Comment by iandol** [comment]
OK, that makes sense, thank you and sorry for this false alarm...
