### ISSUE TITLE
UTF-8 quotation marks (lower-99/„) → no processing applied

### ISSUE THREAD

**Issue by pripple** [jgm/pandoc#6873]
Hi, sorry, this is somehow a follow-up on the just solved (thank you again 😃) #6869 … 🙈

I’d like to display a closing bracket in a citation postnote when converting from LaTeX to DOCX. LaTeX renders `{]}` in this context correctly and so does pandoc as long as there isn’t a opening German quotation mark (lower-99/„) in the postnote.

I would expect

```sh
echo "\cite[„Etwas […{]} auslassen“]{key}" | pandoc -f latex -t native -C
```

to yield

```
[WARNING] Citeproc: citation key not found
[Para [Cite [Citation {citationId = "key", citationPrefix = [], citationSuffix = [Str "\8222Etwas [\8230] auslassen\8220"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 0}] [Str "(",Strong [Str "key?"],Str "\8222Etwas [\8230] auslassen\8220)"]]]
```

however, it yields, with the current version (2.11.2)

```
[WARNING] Citeproc: citation key not found
[Para [Cite [Citation {citationId = "key", citationPrefix = [], citationSuffix = [Str "[\8222Etwas [\8230{]} auslassen\8220]"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 0}] [Str "(",Strong [Str "key?"],Str "[\8222Etwas [\8230{]} auslassen\8220])"]]]
```

The extra brackets around are fixed with 9a40976, however, I still can’t display a closing bracket inside the postnote – see the output with the new nightly build:

```
[WARNING] Citeproc: citation key not found
[Para [Cite [Citation {citationId = "key", citationPrefix = [], citationSuffix = [Str "\8222Etwas [\8230{]} auslassen\8220"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 0}] [Str "(",Strong [Str "key?"],Str "\8222Etwas [\8230{]} auslassen\8220)"]]]
```

By the way, just to check, it works as expected when there isn’t a German opening quotation mark (lower-99/„):

```sh
echo "\cite[“Leaving something […{]} out”]{key}" | pandoc -f latex -t native -C
```

I’ve also tried inserting the brackets with a custom command `\newcommand{\bracket}[1]{[#1]}`, but this doesn’t work with pandoc either, because as soon as there is the German opening quotation mark (lower-99/„), it won’t be able to recognize the command anymore.

This works:

```sh
echo "\newcommand{\bracket}[1]{[#1]}\cite[“Leaving something \bracket{…} out”]{key}" | pandoc -f latex -t native -C
```

This throws an error message:

```sh
echo "\newcommand{\bracket}[1]{[#1]}\cite[„Etwas \bracket{…} auslassen“]{key}" | pandoc -f latex -t native -C
```

**Comment by jgm** [comment]
I know exactly why this is happening.  OK, a more complex fix is needed.

**Comment by jgm** [comment]
Note to self: see https://tex.stackexchange.com/questions/531987/why-does-latex-parse-square-brackets-differently-than-curly-braces on parsing of bracketed options.

**Comment by jgm** [comment]
OK, I think I have a robust solution now.

**Comment by pripple** [comment]
Great, it works now with the nightly build, thank you! 😎👍🏻👍🏻👍🏻
