### ISSUE TITLE
Reference section list has wrong line breaks

### ISSUE THREAD

**Issue by MavropaliasG** [jgm/pandoc#6882]
This bug is described here

https://community.rstudio.com/t/reference-section-text-has-wrong-line-breaks/88838/4

For pandoc versions 2.11.0.4 and 2.11.2. but NOT 2.7.3

rendering references using this style https://www.zotero.org/styles/vancouver-brackets-only-year-no-issue

Adds wrong line breaks when rendered as part of a Rmarkdown, like this 

![image](https://user-images.githubusercontent.com/13523909/100019838-b32c0a00-2e19-11eb-990f-46fefe4e411d.png)

**Comment by jgm** [comment]
You're rendering to what format?

**Comment by MavropaliasG** [comment]
Hi, thanks for the reply, this is an HTML, rendered through the `bookdown::html_document2` YAML command.

**Comment by cderv** [comment]
After looking more into it, by trying to isolate to pandoc or rmarkdown, I believe this is an issue with **rmarkdown** only as it is using its own html template and did not update yet to the style required for new --citeproc built-in
https://github.com/jgm/pandoc/blob/2f110265ff4a1dc429d58e7401d68968e42b6db1/data/templates/styles.html#L156-L179

Adding this CSS in the rmarkdown example solves the formatting issue. 

* `test.Rmd`
````md
---
title: "Untitled"
date: "`r Sys.Date()`"
output: html_document
bibliography: packages.bib
csl: https://www.zotero.org/styles/vancouver-brackets-only-year-no-issue
---

# A header

```{css, echo = FALSE}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
$if(csl-entry-spacing)$
  margin-bottom: $csl-entry-spacing$;
$endif$
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
```


```{r setup, include=FALSE}
knitr::write_bib("knitr", "packages.bib")
```

See [@R-knitr]

# References
````

* `rmarkdown::render("test.Rmd")`

* We get the expected output.
