### ISSUE TITLE
Localization in table name

### ISSUE THREAD

**Issue by miguescri** [jgm/pandoc#6885]
Further localization should be added to `data/translations` to be able to get different outputs for the same language in different countries (es-ES, es-MX...). For example, the following translation

https://github.com/jgm/pandoc/blob/2f110265ff4a1dc429d58e7401d68968e42b6db1/data/translations/es.yaml#L20

is not something that it is said in Spain. Instead we refer to a table as "Tabla". But maybe it is valid in other Spanish speaking countries.

**Comment by jgm** [comment]
We got this data from the polyglossia package, if I recall correctly:
```
/usr/local/texlive/2020/texmf-dist/tex/latex/polyglossia/gloss-*
```
on my system.  I just checked, and this includes `Cuadro` for both es-ES and es-MX.  If this isn't right, maybe you should submit a bug report to polyglossia? (I imagine this affects the use of plain latex with polyglossia as well?)

By the way, the pandoc infrastructure does allow for translations like `es-MX.yaml`; it's just that polyglossia didn't distinguish them so we just have `es.yaml`.  If lang is `es-MX`, pandoc will look first for `es-MX.yaml` and fall back on `es.yaml`.

You could always create a `translations` subdirectory in your default user data directory (`pandoc --version` will tell you where that is) and add your own `es-MX.yaml` there.

**Comment by miguescri** [comment]
Thank you for the pointer. If I add a `es-ES.yaml` to my local user directory with only a subset of all the options (let's say I only write `Table: Tabla`), will pandoc default to the included `es.yaml` for all the others? Or should I just copy the whole file and modify the specific field?

**Comment by jgm** [comment]
copy the whole file and modify

**Comment by miguescri** [comment]
Adding the file to the user folders does not produce any change. I have tried putting it in all these locations:

- `~/.pandoc/es-ES.yaml`
- `~/.pandoc/translations/es-ES.yaml`
- `~/.pandoc/data/translations/es-ES.yaml`
- `~/.local/share/pandoc/translations/es-ES.yaml`
- `~/.local/share/pandoc/data/translations/es-ES.yaml`

Do I have to use any flag or config file?

**Comment by miguescri** [comment]
By the way, I have created an issue in polyglossia about the topic https://github.com/reutenauer/polyglossia/issues/464

**Comment by jgm** [comment]
If you have a `~/.pandoc` directory it would be `~/.pandoc/translations/es-ES.yaml`; otherwise, if you have a `~/.local/share/pandoc` it would be in `~/.local/share/pandoc/translations/es-ES.yaml`.

**Comment by jgm** [comment]
This assumes you aren't using `--data-dir` to reassign the user data dir.
If it doesn't work, could you post a minimal example to reproduce?

**Comment by taydu** [comment]
> https://github.com/jgm/pandoc/blob/2f110265ff4a1dc429d58e7401d68968e42b6db1/data/translations/es.yaml#L20
> 
> is not something that it is said in Spain. Instead we refer to a table as "Tabla". But maybe it is valid in other Spanish speaking countries.

There are a couple of resources in Spanish that explain why `cuadro` is used by default instead of `tabla` in the babel package:

- Spanish TeX Users Group (CervanTeX): see question [¿Por qué spanish para babel dice cuadro en lugar de tabla?](http://www.aq.upm.es/Departamentos/Fisica/agmartin/webpublico/latex/FAQ-CervanTeX/FAQ-CervanTeX-6.html#ss6.7)
- [Explanation](http://www.texnia.com/spanish2.html) from the current maintainer of the babel package.

Polyglossia may be following the same convention, so it seems pandoc is doing the right thing, at least according to these LaTeX packages.

Anyway, if you are converting to LaTeX, the option `es-tabla` in babel replaces `cuadro` with `tabla` in captions (not sure about polyglossia).

**Comment by miguescri** [comment]
@taydu thank you very much for the pointers; today I learned a little bit more about my own language (damm, it is a semantically complex one).

I will close the upstream issue I created.
