### ISSUE TITLE
Wrong render of "et al."

### ISSUE THREAD

**Issue by miguescri** [jgm/pandoc#6887]
Pandoc version:
```
pandoc 2.11.0.4
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10,
citeproc 0.1.1, ipynb 0.1.0.1
```

Pandoc-citeproc version
```
pandoc-citeproc 0.17.0.2
```

My `Bib.md` contains:

```
---
lang: es-ES
---

[@vaswaniAttentionAllYou2017]
```

My `Bib.bib` file contains:

```
@article{vaswaniAttentionAllYou2017,
  title = {Attention {{Is All You Need}}},
  author = {Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N. and Kaiser, Lukasz and Polosukhin, Illia},
  year = {2017},
  month = dec,
  abstract = {The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 Englishto-German translation task, improving over the existing best results, including ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.8 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature. We show that the Transformer generalizes well to other tasks by applying it successfully to English constituency parsing both with large and limited training data.},
  archivePrefix = {arXiv},
  eprint = {1706.03762},
  eprinttype = {arxiv},
  journal = {arXiv:1706.03762 [cs]},
  keywords = {Computer Science - Computation and Language,Computer Science - Machine Learning},
  language = {en},
  primaryClass = {cs}
}
```

After running `pandoc --from=markdown Bib.md --citeproc --bibliography Bib.bib  --to=pdf -o Bib.pdf` I obtain this:

![image](https://user-images.githubusercontent.com/24360431/100099975-67e91a00-2e60-11eb-9c31-e07b6ef37004.png)

According to https://github.com/jgm/citeproc/blob/42b1d154b02435229acbe98ae0f17d01b757ee93/locales/es-ES.xml#L38 and https://github.com/citation-style-language/locales/blob/cbb45961b815594f35c36da7e78154feb5647823/locales-es-ES.xml#L38 the resulting citation should be "et al."

**Comment by jgm** [comment]
Note: it works perfectly with `--pdf-engine=xelatex`.

**Comment by jgm** [comment]
The intermediate tex file has
```
(Vaswani et~al. 2017)
```
which is correct.  Perhaps the babel mode for spanish makes `~` an active character and changes its meaning?

**Comment by jgm** [comment]
@lygamac could this be related to the issue in #6817?

**Comment by lygamac** [comment]
@jgm it's related to babel's shorthands.

"et al." has rendered correctly when I removed the `shorthand=off` option in the header file or when I used xelatex to render.

However, unlike the comma, this only happens with Spanish babel, not with Galician babel.

**Comment by lygamac** [comment]
![image](https://user-images.githubusercontent.com/49118209/100175568-f2686280-2ece-11eb-963e-0a796528c4fa.png)

[source](https://osl.ugr.es/CTAN/macros/latex/required/babel/base/babel.pdf)

@jgm I tried many languages with `~` as shorthand but only Spanish didn't handle it.

`~` in Spanish seems to be defined quite [recently](https://tex.stackexchange.com/questions/509421/list-of-babel-shorthands), and might be a bug.

**Comment by jgm** [comment]
Using `~` as a shorthand certainly seems like a bad idea!
But I'm still confused: are you saying that *removing* `shorthands=off` *deactivates* the shorthands? I would have thought it would be the reverse.

**Comment by lygamac** [comment]
No, removing `shorthands=off` keeps the shorthands activated.

For example, in math mode `$1.1$` would rendered as `1,1` and not `1.1` in Spanish. My understanding is that with `shorthands=off`, "what the shorthand should be" is removed but the "shorthand character" itself remains. Like this:

```
% without shorthand option
\renewcommand{\dot}{\comma}

% with shorthand=off
\renewcommand{\dot}{}

% with shorthand=on
% I don't why this happens but it's its behavior
\renewcommand{\dot}{}
```

However, as I tried before, it breaks with `shorthands=on` too. For it to work properly were either:

- Removing `shorthands=on/off` option (the text format would follow each country's standard).
- Adding a workaround (redefining the shorthand) so all the shorthands characters remains as they are.

I think this topic should moved to [latex3/babe](https://github.com/latex3/babe), or its language specific repo. But it's seems to be already reported but no action has been taken yet.

**Comment by jgm** [comment]
@lygamac I'm going with your suggestion from #6817 .
It seems to work well for both that issue and this one.
Thanks!

**Comment by miguescri** [comment]
@jgm Thank you for addressing the issues so fast. Pandoc is a really amazing tool and your effort is very valuable. Cheers!
