### ISSUE TITLE
Bug secondary slide (down in revealjs) from markdown

### ISSUE THREAD

**Issue by mdtrooper** [jgm/pandoc#6889]
Asking a question?
No

Reporting a bug?

```
$ pandoc -v
pandoc 2.11.2
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.2, ipynb 0.1.0.1
User data directory: /home/miguel/.local/share/pandoc or /home/miguel/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana
```

Example the empty presentation (without content in each slide) of course pandoc runs fine.

[presentation1.zip](https://github.com/jgm/pandoc/files/5595708/presentation1.zip)

```
$ pandoc -s -f markdown -t revealjs -o presentation1.html presentation1.md; xdg-open presentation1.html
```

Example the "complete" presentation with content in each slide, pandoc fails in the slides of ## .

[presentation2.zip](https://github.com/jgm/pandoc/files/5595715/presentation2.zip)

```
$ pandoc -s -f markdown -t revealjs -o presentation2.html presentation2.md; xdg-open presentation2.html
```

And another example with less content in the slides, but pandoc still fails in the slides of ## .

[presentation3.zip](https://github.com/jgm/pandoc/files/5595729/presentation3.zip)

```
$ pandoc -s -f markdown -t revealjs -o presentation3.html presentation3.md; xdg-open presentation3.html
```

**Comment by mb21** [comment]
What exactly do you mean with "fails in the slides" ?

**Comment by mdtrooper** [comment]
Thanks for your quickly reponse.

I put a screenshot of slideshow structure of each example....maybe it is more clear:

presentation1.zip

![image](https://user-images.githubusercontent.com/1285451/100215688-9c68de80-2f11-11eb-858e-3c1766c7dfac.png)

There are three slides ("is it in spain?", "is it in portugal", "is it in france")  down of the slide "Where is it?" . Well the screenshot shows only the 2 first slides down it.

presentation2.zip

![image](https://user-images.githubusercontent.com/1285451/100215778-bc000700-2f11-11eb-81ff-2e9b538b1b88.png)

You can see the slide "Where is it?" is a hodgepodge of other down slides.


presentation3.zip

![image](https://user-images.githubusercontent.com/1285451/100215821-c91cf600-2f11-11eb-8723-e111904de1e7.png)

**Comment by mb21** [comment]
I'll have to check your zip files later.. but have you seen https://pandoc.org/MANUAL.html#structuring-the-slide-show ?

**Comment by mdtrooper** [comment]
Yes, yes.

**Comment by jgm** [comment]
With attention to the manual, ask yourself "what **slide level** will pandoc calculate for this markdown file?"  Then ask yourself, "given what slide level means, is that the slide level I want?"  Finally, ask yourself: "how do I set the slide level to 2 using a pandoc option?"

**Comment by mdtrooper** [comment]
Yes it runs fine with (--slide-level=2):
```
$ pandoc -s -f markdown -t revealjs --slide-level=2 -o presentation2.html presentation2.md; xdg-open presentation2.html
```

But I wonder that a "empty slideshow" runs fine and the same slideshow with some contents fails.

Well, Thanks, I am going to close this ticket.
