### ISSUE TITLE
unconverted unicode math symbols from docx

### ISSUE THREAD

**Issue by Ultrahero** [jgm/pandoc#6891]
Hi, 
first of all: You've done an incredible job with pandoc. It's really really helpful.

But some missing features are bothering me. When I convert a docx file to tex, the 
number ranges N, Q, R, ... are not properly converted to \mathbb{N}, etc. and the symbol for 
'is element in' is not properly converted as well: in latex $\in$. As well as
'less/greater [or equal}' this also as to be in $$: $\leq$,etc.

There are probably some more symbols that are not covered yet. I have found that no free service offers tis capability, so I hope you might add it.

I convert files using the following command:
pandoc file.docx -f docx -t latex -s -o ofile.tex

**Comment by mb21** [comment]
What pandoc version and if you can reproduce with the latest, can you post your minimal docx file?

**Comment by Ultrahero** [comment]
pandoc version: 2.11.1.1
Update on the real reason: math symbols outside of math expression are not converted.

I'm sorry for confusing you. But I figured out the workaround: Just place your math symbols in math expressions not in plain text.

[pandoc_error.docx](https://github.com/jgm/pandoc/files/5602925/pandoc_error.docx)
[pandoc_no_error.docx](https://github.com/jgm/pandoc/files/5602926/pandoc_no_error.docx)

[error.tex.txt](https://github.com/jgm/pandoc/files/5602931/error.tex.txt)
[no_error.tex.txt](https://github.com/jgm/pandoc/files/5602932/no_error.tex.txt)


Maybe you can fix this as well. You would have to convert these math symbols from plain text to math expressions. 
Sorry Again.

**Comment by jgm** [comment]
I don't think this is a bug.  Pandoc will convert Word equations to LaTeX math.  But it won't try to guess that something in Word which is not in an equation object is actually math.
