### ISSUE TITLE
reStructuredText inline role should not contain `\n`

### ISSUE THREAD

**Issue by cpkio** [jgm/pandoc#6897]
This bug is in 2.11.2 and before.

```
This is ordinary text, that is entered as usual. It can contain :cmd:`some
strange text` commands. It can contain ``other kinds`` of text.
```
This should behave like every other text, this is a paragraph with no separating newlines.

If the role is not delared before, the resulting json `pandoc211 -f rst -t json .\testtext.txt` would be
```
{"t":"Code","c":[["",["interpreted-text"],[["role","cmd"]]],"some\nstrange text"]}
```

I think the instead of `\n` there should be a space char.

**Comment by jgm** [comment]
Can you cite some RST documentation?
When I use `rst2html.py` on
```
:code:`hi
there`
```
I see a newline preserved.  So this doesn't seem to be a general expectation of interpreted text roles.

**Comment by cpkio** [comment]
`:code:` is a [predefined role](https://docutils.sourceforge.io/docs/ref/rst/roles.html#code) similiar to literal role, which can behave in a special way, since line breaks usually are meaningful for source code. I'm talking about non-predefined roles, not inherited from `:code:`. I couldn't find any direct mention of line breaks parsing in [inline interpreted text](https%3A%2F%2Fdocutils.sourceforge.io%2Fdocs%2Fref%2Frst%2Frestructuredtext.html#id86) (and a role is a marker for this interpreted text).

Most of the examples have no line breaks inside this interpreted text, which makes sense: it is *inline* text and should not break paragraph flow. So we have a few options: 1) leave newlines in non-literal-inherited inline interpreted text role as `\n`, which seems to me inconsistent with RST paragraph flow logic; 2) treat these new lines as we treat newlines in any ordinary non-interpreted text — replace by spaces; 3) fail to parse interpreted text with a line break inside ( &#96; … `\n` … &#96;) as valid, rendering interpreted text as ordinary.

Pandoc behaves differently from docutils documentation:

> Only pre-determined roles are recognized; unknown roles will generate errors.

In my example the role was not predefined higher in the document, but the text was still rendered as code block. If I predefine the role with `.. role:: cmd` (not `.. role:: cmd(code)`), the JSON will be
```
{"t":"Span","c":[["",["interpret"],[]],[{"t":"Str","c":"some"},{"t":"SoftBreak"},{"t":"Str","c":"strange"},{"t":"Space"},{"t":"Str","c":"text"}]]}
```
Nothing indicates I wanted to preserve line endings in ordinary inline text, though marked as interpreted.

**Comment by jgm** [comment]
We don't generate errors for unknown roles; that wouldn't make sense, since pandoc has no way of defining special roles.  What we do instead is insert an AST item that contains the raw data you'd need to do something with the role, presumably in a filter.  I see no reason to replace newlines with spaces in this raw data, since (as `:code:` shows) *some* roles are going to want to see the difference between a newline and a space.  If you use a filter to do something with this role, you can remove the newlines at that stage.

**Comment by jgm** [comment]
> Nothing indicates I wanted to preserve line endings in ordinary inline text, though marked as interpreted.

And nothing indicates that you don't. That's my point.
