### ISSUE TITLE
conversion from pandoc to pandoc creates redundant header-includes lines

### ISSUE THREAD

**Issue by basbebe** [jgm/pandoc#6901]
I'm trying to use pandoc to format / 'beautify' markdown files.

However, if I have `header-includes` lines in my header, these get duplicated under the header.

**Example:**

```
---
title: "title"
lang: "de"
date: \today
header-includes: |
    \usepackage{amsmath}
    \usepackage{mathtools}
    \usepackage{amssymb}
    \usepackage{wasysym}
    \usepackage{extarrows}
    \usepackage[iso,german]{isodate}
    \setcounter{page}{1}
---
# Header

```

```
pandoc reference.md -f markdown -t markdown -s -o test.md
```

```
---
date: "`\\today`{=tex}"
header-includes: |
  ```{=tex}
  \usepackage{amsmath}
  \usepackage{mathtools}
  \usepackage{amssymb}
  \usepackage{wasysym}
  \usepackage{extarrows}
  \usepackage[iso,german]{isodate}
  \setcounter{page}{1}
  \```
lang: de
title: "title"
---

```{=tex}
\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{amssymb}
\usepackage{wasysym}
\usepackage{extarrows}
\usepackage[iso,german]{isodate}
\setcounter{page}{1}
\``` 

#Header

```

(here I "escaped" two lines for better formatting.
And if I 'beautify' this file again, I will have even another block of "redundant" latex lines.

```
❯ pandoc -v

pandoc 2.11.2
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.2, ipynb 0.1.0.1
User data directory: /Users/bastian/.local/share/pandoc or /Users/bastian/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by tarleb** [comment]
This can be worked around this by using a custom template. The default template is

```
$if(titleblock)$
$titleblock$

$endif$
$for(header-includes)$
$header-includes$

$endfor$
$for(include-before)$
$include-before$

$endfor$
$if(toc)$
$table-of-contents$

$endif$
$body$
$for(include-after)$

$include-after$
$endfor$
```

Remove the `$for(header-includes)$`...`$endfor$` lines and all other lines that you don't want, then pass the resulting file via the  `--template` command line option.

Pandoc can often be used as beautifier, but it's not its primary function, which is why I'm closing this.

The best place to ask further questions is the [pandoc-discuss mailing list](https://groups.google.com/forum/#!forum/pandoc-discuss).

**Comment by jgm** [comment]
I think it would also work to set `-Vheader-includes=""` on the command line.

**Comment by basbebe** [comment]
(but: this will add newlines at the beginning of a file if there is no header present)

**Comment by jgm** [comment]
@basbebe you could also use a custom template for your md->md conversions; just omit the header-includes from the template you use for this purpose.

**Comment by basbebe** [comment]
> @basbebe you could also use a custom template for your md->md conversions; just omit the header-includes from the template you use for this purpose.

Thanks for the tip!

In this case though, I need to keep it as portable as possible, so I'm trying to avoid a template file.

I guess I'll have to use a regex to add `-Vheader-includes=''` only when needed?
