### ISSUE TITLE
org-mode erroneous extra slide when using custom TODOs at top

### ISSUE THREAD

**Issue by fommil** [jgm/pandoc#6905]
> Please include your pandoc version

```
$ pandoc --version

pandoc 2.11.0.4
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.1.0.3, ipynb 0.1.0.1
User data directory: /home/shalliday/.local/share/pandoc or /home/shalliday/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

```

> and an example

```
#+TITLE: My Title
#+AUTHOR: My Name
#+DATE: My Date
#+TODO: TODO | RESEARCH | NOTES | CHART | DIAGRAM | DRAWING | CODE | VIDEO
* Introduction

- Hello World!

# Local Variables:
# compile-command: "pandoc --write=revealjs --from org --output index.html pandoc-bug.org"
# End:
```

produces

```
<section class="slide level1">


</section>
<section id="introduction" class="slide level1">
<h1>Introduction</h1>
<ul>
<li>Hello World!</li>
</ul>
</section>
```

The first `<section ...> ... </section>` should not be there.

A workaround is to move the custom TODO section

```
#+TODO: TODO | RESEARCH | NOTES | CHART | DIAGRAM | DRAWING | CODE | VIDEO
```

to the end of the file.

**Comment by jgm** [comment]
This gets parsed as
```
RawBlock (Format "org") "#+TODO: TODO | RESEARCH | NOTES | CHART | DIAGRAM | DRAWING | CODE | VIDEO"
```
As a raw block, it will be omitted in the html output. However, the code that splits the document into slides is run before the writer, so this goes on a slide.

I suppose one fix coud be to change the HTML writer so that a completely empty slide is never omitted?

**Comment by tarleb** [comment]
This is (also) a problem with the org reader, as the `#+TODO` line should be parsed but not be included in the output.

The org manual states

> The vertical bar separates the TODO keywords (states that need action) from the DONE states (which need no further action). If you do not provide the separator bar, the last state is used as the DONE state.

It does not say what multiple pipes mean, but it seams that org ignores them. The org reader should be changed to do the same, but currently allows only a single pipe char in a `#+TODO` line.

**Comment by tarleb** [comment]
Closing this, as the org-mode issue has been resolved.
