### ISSUE TITLE
Admonitions are rendered as normal text in .docx output

### ISSUE THREAD

**Issue by DanielSWolf** [jgm/pandoc#6906]
The following DocBook code contains a text paragraph, followed by a number of admonition blocks:

*admonitions.dbk*
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?asciidoc-toc?>
<?asciidoc-numbered?>
<article xmlns="http://docbook.org/ns/docbook"
  xmlns:xl="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
  <info>
    <title>Admonitions</title>
    <date>2020-12-02</date>
  </info>
  <simpara>Lorem ipsum dolor sit amet.</simpara>
  <note>
    <simpara>This is a note.</simpara>
  </note>
  <tip>
    <simpara>This is a tip.</simpara>
  </tip>
  <important>
    <simpara>This is important.</simpara>
  </important>
  <caution>
    <simpara>Take care!</simpara>
  </caution>
  <warning>
    <simpara>This is a warning.</simpara>
  </warning>
</article>
```

When exporting to .docx, I expected these admonitions to be highlighted in some way, according to their type. Actually, however, they are styled as normal text, identically to the preceding paragraph.

* Pandoc version: 2.11.2
* Command line: `pandoc --from docbook --to docx --output admonitions.docx admonitions.dbk`

Here is [the resulting file *admonitions.docx*](https://github.com/jgm/pandoc/files/5627790/admonitions.docx). This is what the relevant section looks like: 
![image](https://user-images.githubusercontent.com/5963162/100845919-2f5bc880-347e-11eb-9a7a-98ef5584a371.png)

For comparison, when I convert an equivalent AsciiDoc file using Asciidoctor PDF, the same section looks like this: 
![image](https://user-images.githubusercontent.com/5963162/100846330-adb86a80-347e-11eb-977e-bcc1fb34c7f8.png)

**Comment by jgm** [comment]
Using `pandoc -f docbook -t native`, you can see how pandoc is parsing this:
``` haskell
[Para [Str "Lorem",Space,Str "ipsum",Space,Str "dolor",Space,Str "sit",Space,Str "amet."]
,Div ("",["note"],[])
 [Para [Str "This",Space,Str "is",Space,Str "a",Space,Str "note."]]
,Div ("",["tip"],[])
 [Para [Str "This",Space,Str "is",Space,Str "a",Space,Str "tip."]]
,Div ("",["important"],[])
 [Para [Str "This",Space,Str "is",Space,Str "important."]]
,Div ("",["caution"],[])
 [Para [Str "Take",Space,Str "care!"]]
,Div ("",["warning"],[])
 [Para [Str "This",Space,Str "is",Space,Str "a",Space,Str "warning."]]]
```
So the information about the admonition sections is preserved, but pandoc doesn't apply any particular formatting.  That's reasonable, I think, because the formatting is a stylistic element and different users may want different things.  You can use lua filters to customize the rendering of these Divs in your output format.

**Comment by DanielSWolf** [comment]
I'm talking specifically about the .docx output. When using Pandoc to create a Word document, information about admonition blocks is currently lost.

One possible approach might be to add five new paragraph styles for the five types of admonitions and to give them sensible default visualizations. This way, when using Pandoc out of the box, one would get a Word document with clearly recognizable admonitions. And if somebody wants to change the look of these admonitions, they can simply create a reference document [as described here](
![image](https://user-images.githubusercontent.com/5963162/101025523-fef75580-3575-11eb-99e1-a57a980f056a.png)https://pandoc.org/MANUAL.html#option--reference-doc).

**Comment by jgm** [comment]
> One possible approach might be to add five new paragraph styles for the five types of admonitions and to give them sensible default visualizations.

Yes, we *could* do that.  But then the question arises, why docx, and not other document formats? And before long we have created, in effect, a new "stringly typed" AST element.  I don't think this is a good way to go. Try the lua filter approach.

**Comment by jgm** [comment]
Also see this paragraph from the beginning of the manual:

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size. And some document elements, such as complex tables, may not fit into pandoc’s simple document model. While conversions from pandoc’s Markdown to all formats aspire to be perfect, conversions from formats more expressive than pandoc’s Markdown can be expected to be lossy.

**Comment by DanielSWolf** [comment]
Thanks for the clarification! I didn't realize that full coverage of the features of individual formats was out of scope for Pandoc. Thank you for the tip regarding Lua filters. I'll check them out.

**Comment by FilipeBrasAlmeida** [comment]
Sorry to revisit this closed issue, but does anyone have an example of what a Lua Filter for rendering admonitions (from docbook xml format to docx) would look like?

**Comment by jgm** [comment]
Sure. Try this.
``` lua
local admonitions = {
  warning   = {pandoc.Str("Warning")},
  note      = {pandoc.Str("Note!")},
  tip       = {pandoc.Str("Tip"), pandoc.Space(),
                  pandoc.Image("Tipping hat", "hat-tip.jpg")},
  important = {pandoc.Str("Important!")},
  caution   = {pandoc.Str("Caution!")}
  }

function Div(el)
  local admonition_text = admonitions[el.classes[1]]
  if admonition_text then
    table.insert(el.content, 1,
        pandoc.Para{ pandoc.Strong(admonition_text) })
  end
  return el
end
```
Use with `--lua-filter admonition.lua`.
Customize as you need.

**Comment by aireilly** [comment]
answered here: https://groups.google.com/g/pandoc-discuss/c/65G0Kuih1wA :)

**Comment by gusbemacbe** [comment]
@aireilly 

I published the question on July 2022: https://stackoverflow.com/questions/73049303/convertng-markdown-admonition-syntax-to-html-using-lua-for-pandoc. But I really wanted to use Pandoc Lua to write, and not to render. 

You published on November 2022: https://stackoverflow.com/questions/74289155/formatting-docbook-admonitions-with-pandoc

I tested your updated code, and it did not work. 

I use Codebraid Pandoc, Codebraid Preview and the `markdown_github` format.

**Comment by sylvaticus** [comment]
Sorry as well to post on a closed issue, but my need is very similar to the op, except that my source is a Markdown file. How can I keep admonitions in a markdown file (either in `!!! TIP` or `::: [tip]` or whatever format) when converting to docs using pandoc ?

**Comment by Smeedy** [comment]
After discussing and experimenting based on this issue, I've had a back-and-forth conversation with ChatGPT solving my issues exporting my MkDocs Material files to Word so Pandoc supports `!!! type` admonitions , with styling support for Word output. Thanks to @mcdemarco and everyone else in this thread for the core logic builds on your insights. Feedback and refinements are welcome!

### Features

- Recognizes `!!! type` syntax (e.g. `!!! warning`, `!!! note`)
- Supports both **single-paragraph** and **multi-paragraph** admonition blocks
- Applies a **custom Word paragraph style** to the entire block:
  - `AdmonitionStyle-warning`
  - `AdmonitionStyle-note`
  - etc.
- Injects a **label paragraph** at the top of each block (e.g., `WARNING:`) using a second Word style:
  - `AdmonitionLabelStyle-warning`
- Designed for use with a `reference.docx` that defines these paragraph styles

### Example Markdown Input

```markdown
This is normal text and will render into a First-Paragraph style (default behaviour).

!!! tip
    This is a single-paragraph tip.

!!! warning
    This warning spans multiple paragraphs.

    It should still be treated as one block and not as source-code.

This is regular body text again.
```

### Code

The Lua filter is published here:  
👉 https://gist.github.com/Smeedy/07260f712216d1490f6ab0f5cf763fad

### Word Styling

To fully enable this in Word:

1. Create a `reference.docx`
2. Define paragraph styles:
   - `AdmonitionStyle-warning`, `AdmonitionStyle-tip`, etc.
   - `AdmonitionLabelStyle-warning`, etc. for label lines
3. Pandoc will apply these automatically when using `--reference-doc=reference.docx`

Btw, the lua script injects the `admonition_type:upper()` in the label, but that can be omitted and use something fancy in the reference.docx style definition. Working on that part still. 

### Usage

```bash
pandoc input.md -o output.docx \
  --lua-filter=pandoc-admonition.lua \
  --reference-doc=reference.docx
```

---
