### ISSUE TITLE
When converting to RTL docx, bold/italics are not preserved

### ISSUE THREAD

**Issue by Namos129** [jgm/pandoc#6911]
Related discussion in pandoc-discuss: https://groups.google.com/g/pandoc-discuss/c/J2VHrCPkdAk

Pandoc version: 2.11.2

When converting markdown to RTL docx using the command:

pandoc test.md -f markdown -t docx -o test.docx -M dir=rtl

**bold** and *italics* are not preserved.

Example text:
```
**בדיקה** **test**
*בדיקה2* *test2*
```
With the expected result being the same (but right-aligned).

Actual result:
בדיקה test
בדיקה2 test

Based on the discussion in the mailing group, Pandoc uses <w:b> tag to apply bold in Word. RTL scripts are considered Complex script by word, and use a different tag for bolding **<w:bCs>**.
The same is true of italics - pandoc uses <w:i> while complex script italics are tagged **<w:iCs>**.

Complex script tags should be applied whenever converting to RTL, although it might be safer to apply them whenever converting text to docx.

**Comment by jgm** [comment]
Would it work just to use `<w:b>` and `<w:bCs>` together (and similarly for italics) everywhere?  Then we don't need to figure out whether it's LTR.
