### ISSUE TITLE
Allow altering base url for HTML5 table of contents

### ISSUE THREAD

**Issue by creesch** [jgm/pandoc#6912]
I am facing a situation where I need to host pandoc generated HTML5 documentation on Sharepoint/Teams. HTML documents uploaded there are displayed through iframes, specifically the source is put in the [iframe `srcdoc` attribute](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/srcdoc). 

As a result the links in the TOC generated by pandoc do not work properly which is unfortunate. This can however be worked around by prefixing the anchor links with `about:srcdoc`. 

Having gone through the documentation there doesn't appear to be anyway to have pandoc prefix anything to the `href` attribute of TOC links which is why I am opening this issue as a feature request. 

So to illustrate, currently pandoc generates the TOC like this 

```html
<nav id="TOC" role="doc-toc">
     <ul>
          <li>
               <a href="#1-introduction">1. introduction</a>
          </li>
          <li>
               <a href="#2-chapter">2. chapter</a>
          </li>
     </ul>
</nav>
```

I'd like the option to generate the TOC urls like this

```html
<nav id="TOC" role="doc-toc">
     <ul>
          <li>
               <a href="about:srcdoc#1-introduction">1. introduction</a>
          </li>
          <li>
               <a href="about:srcdoc#2-chapter">2. chapter</a>
          </li>
     </ul>
</nav>
```

**Comment by jgm** [comment]
This is a fairly specialized use case, so I'm not inclined to add an option to handle it.
Better just to postprocess pandoc's output using HTML tools?

**Comment by creesch** [comment]
It would be possibly of course to set up a tool chain to correct this and I might have to do that, it would however mean that instead of using one tool which is fairly standalone I now need to find a secondary tool to correct for this. 
Which I can do but considering that in the near future I have to transfer the process to the care of other people who are less technically inclined and possibly even on a different OS I was really hoping to be able to keep it to the one tool. 

I do however understand the specialized use case argument.

**Comment by jgm** [comment]
It's a tradeoff:  if I implemented this, it would make your job less complex, but it makes my job more complex and increases risk of bugs for everyone who uses pandoc.  Complexity is the enemy, so I need a strong reason to add something like this. I'll close this issue but if lots of other people request this, I could reconsider.
