### ISSUE TITLE
nav.xhtml css href is not correct

### ISSUE THREAD

**Issue by codelabor** [jgm/pandoc#6914]
When converting markdown to epub, the css path of nav.xhtml is incorrect.

* as-is: styles/stylesheet1.css
* to-be: ../styles/stylesheet1.css

**cover.xhtml**
```html
  <link rel="stylesheet" type="text/css" href="../styles/stylesheet1.css" />
```

**title_page.xhtml** 
```html
  <link rel="stylesheet" type="text/css" href="../styles/stylesheet1.css" />
```

**nav.xhtml**
```html
  <link rel="stylesheet" type="text/css" href="styles/stylesheet1.css" />
```

**Comment by jgm** [comment]
Looks correct to me.
In the container we have
```
EPUB/nav.xhtml
EPUB/styles/stylesheet1.css
```
A relative link to `styles/stylesheet1.css` in `EPUB/nav.xhtml` will link to `EPUB/styles/stylesheet1.css`.

**Comment by codelabor** [comment]
You're right. I see what I've mistaken. 
Now I see that the location where nav.xhtml is generated is different Sigil and Pandoc.

* EPUB/nav.xthml
* OEBPS/text/nav.xthml

But If you look at the eub made by Pandoc through Sigil's GUI, the location seems to be confused. 
If you look at Sigil GUI, it's nav.The xthml appears to be under the Text directory.

![](https://github.com/codelabor/pandoc-nav-location-test/raw/main/sigil%20vs%20pandoc.png)

This difference is very confusing. Why don't you put the nav.xhtml under OEBPS/Text unless you have a special reason? (The default setting would be EPUB/Text)

Actually, it was confusing that EPUB was the default directory, not OBPS. I hope the default directory for --epub-subdirectory is OEBPS. And if nav.xhtml is under OEBPS/Text, I believe the user will not be confused because Sigil has the same shape as the result.

I tested this here:
* https://github.com/codelabor/pandoc-nav-location-test

**Comment by jgm** [comment]
https://www.w3.org/publishing/epub3/epub-ocf.html#sec-container-file-and-dir-structure

META-INF is required. Otherwise you can use any directory layout you like.  Pandoc's EPUBs are conformant.  They are different from Sigil's but not wrong.
