### ISSUE TITLE
nav.xhtml body need epub:type

### ISSUE THREAD

**Issue by codelabor** [jgm/pandoc#6918]
The nav.xhtml created by Sigil has **epub:type="frontmatter"** in body tags.
It would be nice to include this information when Pandoc creates nav.xhtml.

* as-is: &lt;body&gt;
* to-be: &lt;body epub:type="frontmatter"&gt;

**nav.xhtml (Sigil)**
```
<body epub:type="frontmatter">
  <nav epub:type="toc" id="toc">
```

**nav.xhtml (Pandoc)**
```
<body>
  <nav epub:type="toc" id="toc">
```

**Comment by jgm** [comment]
Can you link to epub documentation that recommends this?
What difference in practice does this make?

I don't see this, e.g., in the samples I checked at https://github.com/IDPF/epub3-samples
which is maintained by the standards body itself.

**Comment by codelabor** [comment]
I can't find best practice document to refer to yet.
But I know the toc is not a bodymatter, but frontmatter.

According to this post, toc is frontmatter. 
https://www.oxygenxml.com/dita/1.3/specs/langRef/technicalContent/frontmatter.html

`The <frontmatter> element contains the material that precedes the main body of a document. It might include items such as an abstract, a preface, and various types of book lists such as a <toc>, <tablelist>, or <figurelist>.`

If you look at the epub created by Sigil, the toc is frontmatter, so why don't you follow it?

In Pandoc, titlepage are set as frontmatter, right? I wish toc would do the same.

**title_page.xhtml**
```
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <title>example</title>
  <link rel="stylesheet" type="text/css" href="../styles/stylesheet1.css" />
</head>
<body epub:type="frontmatter">
```

**nav.xhtml**
```
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <title>example</title>
  <link rel="stylesheet" type="text/css" href="styles/stylesheet1.css" />
</head>
<body>
```

**Comment by jgm** [comment]
I think it probably does make sense to use the frontmatter annotation here, and I think I'll do that, but it's nice to follow guidance from an official spec.  (dita, which you link to, is not epub.)
