### ISSUE TITLE
landmark in nav.xhtml toc, titlepage needed

### ISSUE THREAD

**Issue by codelabor** [jgm/pandoc#6919]
The nav.xhtml created by Pandoc has only **cover** in the landmark information. nav.xhtml and title_page.xhtml are also generated, so there should also be **nav, titlepage** in the landmark information.
Even the href path of **cover** information is wrong. It shall not be 'text/cover.xhtml' but 'cover.xhtml'.

* as-is: cover only
* to-be: cover, toc, titlepage is generated. and href is "cover.xhtml" not "text/cover.xhtml"

**nav.xhtml (Sigil)**
```
  <nav epub:type="landmarks" id="landmarks" hidden=""><h1>Landmarks</h1>
  <ol>
    <li><a epub:type="cover" href="cover.xhtml">Cover</a></li>
    <li><a epub:type="toc" href="#toc">Table of Contents</a></li>
    <li><a epub:type="titlepage" href="title_page.xhtml">Title Page</a></li>
  </ol></nav>
```

**nav.xhtml (Pandoc)**
```
  <nav epub:type="landmarks" id="landmarks" hidden="hidden"><ol>
    <li><a href="text/cover.xhtml" epub:type="cover">Cover</a></li>
  </ol></nav>
```

**Comment by jgm** [comment]
Isn't `text/cover.xhtml` correct?  The `nav.xhtml` is in the EPUB subdirectory of the container, and the cover is `EPUB/text/cover.xhtml`.  So this is a correct relative link path, no?  (Sigil may put the cover in a different place.)

I see from the code that we do add a link to `#toc`, but only if `--toc` has been specified on the command line.  If you want this, specify `--toc`.

We could add a link to the title page, I suppose. Is this considered best practice?  Can you link to documentation that supports this?

**Comment by codelabor** [comment]
I wrote the reason why nav.xhtml's path is confusing on another issue.
(https://github.com/jgm/pandoc/issues/6914#issuecomment-738549578)

What I'm trying to say here is that it would be nice to have toc and tablepage in the landmarks.

I referred to this document.
https://ebookflightdeck.com/handbook/landmarks

```
The EPUB 3 spec mentions the following epub:type values to consider for your landmarks nav:

cover – the book cover(s), jacket information, etc.
toc – table of contents
bodymatter – First "real" page of content (e.g. "Chapter 1")
title-page – page with possibly title, author, publisher, and other metadata
frontmatter
backmatter
loi – list of illustrations
lot – list of tables
preface
bibliography
index – back-of-book style index
glossary
acknowledgments
```
