### ISSUE TITLE
Standalone HTML example differs from actual result

### ISSUE THREAD

**Issue by emlautarom1** [jgm/pandoc#6920]
This is the first time that I've used Pandoc so I apologize in case I'm missing something.

In the [Demos page](https://pandoc.org/demos.html) the `Example 2` shows how to produce a Standalone HTML, yet when I try to reproduce this example, the resulting HTML looks like the first example, an HTML fragment.

**Official site example:**

![Screenshot from 2020-12-03 18-26-07](https://user-images.githubusercontent.com/31224949/101090237-15f97000-3595-11eb-85ab-64ab9cb29e0f.png)

[You can also access this example from here](https://pandoc.org/demo/example2.html)

**Local result:**

![Screenshot from 2020-12-03 18-26-13](https://user-images.githubusercontent.com/31224949/101090260-201b6e80-3595-11eb-892e-0bf2ef2069a6.png)

I ran the command specified in the example: `pandoc -s MANUAL.txt -o example2.html`. Yet as you can see, the results are totally different when it comes to CSS.

---

I'm running `Fedora 33`, but I really don't think that this could be the issue.

<details>
<summary>
Output from "pandoc --version"
</summary>

```
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/emlautarom1/.local/share/pandoc or /home/emlautarom1/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
</details>

**Comment by emlautarom1** [comment]
Also, when running the [online version](https://pandoc.org/try/) I get the expected CSS when using the same content from the  `MANUAL.txt` file and setting `HTML5` as output. I get no error message from the CLI whatsoever.

**Comment by jgm** [comment]
You've got an older version of pandoc. The fancy CSS in the default template is new.
Note that you should be able to install our linux binary on Fedora, if you want to use the latest.
