### ISSUE TITLE
HTML comment code block appearing when converting ODT to markdown

### ISSUE THREAD

**Issue by makeworld-the-better-one** [jgm/pandoc#6927]
pandoc 2.11.0.4

When converting from ODT to markdown, sometimes I get these in the output:

````markdown
```{=html}
<!-- -->
```
````

It has to do with bullet lists I think, as it's happening in the middle of one, and that's where it's happened in the past.

Here's the context of the markdown output:

````markdown
-   Programming in Python
    -   Visual results with Pygame
    -   Physical/electronic programming with Raspberry Pi
    -   Website design with Flask and Jinja2 and HTML
    -   ORM with peewee
-   Some HTML website design
-   Limited 3D design with Blender

```{=html}
<!-- -->
```
-   blah blah
````

And the `-t native` output for that area:

```haskell
,BulletList
 [[Para [Str "Programming",Space,Str "in",Space,Str "Python"]
  ,BulletList
   [[Plain [Str "Visual",Space,Str "results",Space,Str "with",Space,Str "Pygame"]]
   ,[Plain [Str "Physical/electronic",Space,Str "programming",Space,Str "with",Space,Str "Raspberry",Space,Str "Pi"]]
   ,[Plain [Str "Website",Space,Str "design",Space,Str "with",Space,Str "Flask",Space,Str "and",Space,Str "Jinja2",Space,Str "and",Space,Str "HTML"]]
   ,[Plain [Str "ORM",Space,Str "with",Space,Str "peewee"]]]]
 ,[Plain [Str "Some",Space,Str "HTML",Space,Str "website",Space,Str "design"]]
 ,[Plain [Str "Limited",Space,Str "3D",Space,Str "design",Space,Str "with",Space,Str "Blender"]]]
,BulletList
 [[Plain [Str "blah",Space,Str "blah"]]
```

I believe this is occuring because of there being two bulleted lists right next to eachother in the ODT file, as can be seen in the native output. By editing the ODT file, I can change where the second bulleted list starts, and change where the weird code block appears too.

As you can see, there's no code block object in the native output, so maybe this is some bug in the markdown writer.

Edit: I can confirm I was able to remove and re-introduce this code block in the output, just by switching between one bulleted list versus two right next to each other.

**Comment by jgm** [comment]
This is inserted because, without it, the two consecutive bullet lists would be treated as a single bullet list in markdown.

**Comment by jgm** [comment]
To clarify,
```
- a 
- b

- c
- d
```
is considered a single bullet list in Markdown; so we need to break up the list with something non-printing.

**Comment by makeworld-the-better-one** [comment]
Okay, but the problem for me is that this means the markdown output is not equivalent to the input. Word processors display the two separate lists exactly the same as having one big list, there is no way to tell the difference visually. The only reason I have two lists side by side in my document is by accident. Maybe could you only insert that character if there's an empty line between the lists?

>non-printing

````markdown
```{=html}
<!-- -->
```
````

becomes

```{=html}
<!-- -->
```
GitHub appears to print it ^^, and some other renderers I tried did as well. If it was actually non-printing I wouldn't have an issue, but it is printing, which means the markdown output has unexpected extra content.

Maybe you meant to just add `<!-- -->` which would be non-printing? Instead of the HTML code block.

**Comment by jgm** [comment]
It's not a a code block.  See the manual under `raw_attribute`.  It's a pandoc extension for explicitly marking something up as raw HTML.  If you don't want this, use `-t markdown-raw_attribute`, and then you'll just get
```
<!-- -->
```

**Comment by makeworld-the-better-one** [comment]
Oh, thanks.
