### ISSUE TITLE
Proposal: Sed filters under Pandoc

### ISSUE THREAD

**Issue by anasram** [jgm/pandoc#6929]
Pandoc version: 2.9.11.2

---

Think of something like this:

```sh
pandoc -f markdown -t html\
	sed-filters="some_sed_filters.sh"\
	"in.md" -o "out.html";\
```

where `some_sed_filters.sh` looks like this:

```sh
s/foo1/foo2/g
s/foo3/foo4/g
…
```

**You might wonder**: Why don't just simply call sed commands independently:

```sh
pandoc …
sed …
```
or:

```sh
sed …
pandoc …
```

**The answer is**: The idea here is to maintain file-format codes and in-context codes (e.g. `<code>` and `<pre>` contents). Check #6299 issue.

**Comment by mb21** [comment]
Seems like this should already be possible using pandoc filters. Can we close this issue and keep discussion in #6299 ?

**Comment by tarleb** [comment]
Note that this is achievable using normal JSON filters:

File `sed.sh`:

``` shell
#!/bin/sh
sed -f "$SED_FILE"
```

Then call pandoc with `SED_FILE=some_sed_filters.sh pandoc -F sed.sh`.
