### ISSUE TITLE
Wrong CSL layout when converting Markdown to PDF

### ISSUE THREAD

**Issue by asakura42** [jgm/pandoc#6930]
```
pandoc 2.11.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.1,
citeproc 0.1.1.1, ipynb 0.1.0.1
```

For example, I want to use this style: https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fcambridge-university-press-law-note

But when generating a PDF, instead of a full citation with the author's name, title, publisher and year, only the author's name is shown, the rest is footnoted. Other citation styles are also "broken". Where I need to enclose a quote in brackets (using prefix and suffix in a CSL file), no brackets are visible for example.

I have this in beginning of my `paper.md`:
```
---
bibliography: bib.bibtex
csl: cambridge-university-press-law-note.csl
---
```
in `bib.bibtex`:
```
@book{alighieri1893divine,
  title={The Divine Comedy of Dante Alighieri},
  author={Alighieri, D. and Parsons, T.W. and Guiney, L.I.},
  lccn={12031786},
  url={https://books.google.ru/books?id=0U87AAAAYAAJ},
  year={1893},
  publisher={Houghton, Mifflin}
}
```

And a line in text: `... @alighieri1893divine ...` and this line is replaced as `D. Alighieri, T. W. Parsons, and L. I. Guiney`, that is, the citeproc itself works, but not that correct as I think.

**Comment by jgm** [comment]
This is a note style, so it produces footnotes.  If you don't want footnotes, you should use a different style.
