### ISSUE TITLE
"Unknown reader: dokuwiki" on a fresh installation of v 2.5

### ISSUE THREAD

**Issue by fridde** [jgm/pandoc#6937]
In the documentation for the parameter ```--from``` (see [here](https://pandoc.org/MANUAL.html#option--from)) the "dokuwiki" format is specified.
Yet when running ```pandoc --list-input-formats``` I can't see "dokuwiki" anywhere. 

Running 
```
pandoc some_file.txt -f dokuwiki -o some_other_file.html
```
returns "Unknown reader: dokuwiki"

The list of output formats given by ```pandoc --list-output-formats``` *does* contain "dokuwiki".

What is going on here? Are the docs wrong? Is the package I got via ```apt install pandoc``` incomplete?

I am running pandoc version 2.5 on Ubuntu 20.04 on WSL 2.

**Comment by jgm** [comment]
The documentation on the website is for the most recent version (2.11.2).
A lot has changed since 2.5.
But the ubuntu man page for pandoc should give you that version's documentation.
