### ISSUE TITLE
pandoc ignores attributes prefixes like `xml:lang=""`

### ISSUE THREAD

**Issue by alikazemkhanloo** [jgm/pandoc#6938]
In original epub file, exported from InDesign, xhtml files have an extra attr with `xml:` prefix, just like this

```html
<body id="something" lang="fa-IR" xml:lang="fa-IR">
```
When converting from epub to epub, to add extra stuff like cover page, Pandoc will remove `xml:` part of the attribute and produces a duplicated attribute. which causes an error when opening the book in an epub reader.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by jgm** [comment]
There are probably two issues here.

One is reproducible with things like `<span lang="fr" xml:lang="fr">foo</span>`, which when processed with `pandoc -f html -t html` will yield a duplicated attribute.  That's an issue in the HTML reader, as can be seen using `-f html -t native`.

The other issue is that we don't currently check the `<body>` tag for a lang attribute (only `<html>`).  It would be good to do this.

**Comment by alikazemkhanloo** [comment]
@mb21 
I'm using the latest version

```
$ pandoc -v
pandoc 2.11.2
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.2, ipynb 0.1.0.1

```
@jgm Thank you for providing a nice minimal example of the issue. The issue with `body` may not be critical, but duplicate attributes cause an error.

**Comment by jgm** [comment]
This is due to the use of `stripPrefixes` in the HTML reader.
Now, why did we put that there to begin with?

**Comment by jgm** [comment]
This was added in 266e1977e03383f806867d9d3af86b5d55717830
I'm not sure why.  @mpickering do you recall why you needed to strip the prefixes on HTML attributes in the HTML reader? (I know, it was a long time ago.)
