### ISSUE TITLE
--highlight-style does not support WINDOWS shortpath name as other argument

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#6939]
The issue is that `--highlight-style` does not handle Windows' shortpath name. This type of path can be created when there is a space in the path.
Example of error 
```powershell
PS > pandoc -t html  --highlight-style=C:\Users\chris\AppData\Local\Temp\dummy\DIRWIT~1\PYGMEN~1.THE --metadata title=test  test.md
Unknown highlight-style C:\Users\chris\AppData\Local\Temp\dummy\DIRWIT~1\PYGMEN~1.THE
```

Argument like `--template` does not have an issue with it 

Here is a full reproducible example of the problem using WINDOWS and Powershell 7

```powershell
PS > # use a temp dir for the example
PS > cd $env:TEMP
PS > mkdir dummy      
    Directory: C:\Users\chris\AppData\Local\Temp       
Mode                 LastWriteTime         Length Name 
----                 -------------         ------ ---- 
d----          09/12/2020    17:29                dummy
PS > cd dummy
PS > # Create a test file
PS > echo '#header' > test.md
PS > cat test.md
#header
PS > # We need a template file
PS > echo '$body$' > template.html
PS > # And a theme file
PS > pandoc --print-highlight-style=pygments > pygments.theme
PS > # issue is with space in path
PS > mkdir "dir with space"
    Directory: C:\Users\chris\AppData\Local\Temp\dummy
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          09/12/2020    17:29                dir with space
PS > cp template.html "dir with space"
PS > cp pygments.theme "dir with space"
PS > # get short path version
PS > $a = New-Object -ComObject Scripting.FileSystemObject
PS > $f = Resolve-Path "dir with space/pygments.theme"
PS > $theme = $a.GetFile($f).ShortPath
PS > echo $theme
C:\Users\chris\AppData\Local\Temp\dummy\DIRWIT~1\PYGMEN~1.THE
PS > $f = Resolve-Path "dir with space/template.html"
PS > $template = $a.GetFile($f).ShortPath
PS > echo $template
C:\Users\chris\AppData\Local\Temp\dummy\DIRWIT~1\TEMPLA~1.HTM
PS >
PS > # Pandoc works if template is a short path 
PS > pandoc -t html --template=$template --metadata title=test test.md
<p>#header</p>
PS > # But not highlight-style
PS > pandoc -t html  --highlight-style=$theme --metadata title=test  test.md
Unknown highlight-style C:\Users\chris\AppData\Local\Temp\dummy\DIRWIT~1\PYGMEN~1.THE
```

Let's not that the issue is with the ShortPath name being in the filename itself. When only in the directory path, no issue
```powershell
PS > $f = Resolve-Path "dir with space"
PS > $shortdir = $a.GetFolder($f).ShortPath
PS > $theme2 = Join-Path $shortdir pygments.theme
PS > $theme2
C:\Users\chris\AppData\Local\Temp\dummy\DIRWIT~1\pygments.theme
PS > pandoc -t html  --highlight-style=$theme2 --metadata title=test  test.md
<p>#header</p>
```

```powershell
PS > # clean example
PS > cd ..
PS > rm -Recurse -Force dummy
```

This was found with **rmarkdown** R package https://github.com/rstudio/rmarkdown/issues/1976

Related question: Does Pandoc handles path with space on Windows ? Would it be possible to avoid using Short Path Name ? 

Thank you.

**Comment by jgm** [comment]
`--highlight-style` can only be used with a FILE argument if the file has the extension `.theme` (lowercase).  `.THM` will not work.  In addition, the `.theme` file must be a JSON file in the format of KDE theme definitions. Please see the manual for more on this.

**Comment by jgm** [comment]
In general file names with spaces should be fine; just enclose in double quotes.

**Comment by cderv** [comment]
Thanks for your quick reply !
 
The extension is changed by the transformation made on Windows for getting short path name. 
So I understand this is expected that `--highlight-style` is not working with filepath transformed by Windows in short path name. 

I'll take that into account in our tool.

**Comment by jgm** [comment]
If it's important, I could probably relax the `.theme` requirement. But better just to use the long name.

**Comment by cderv** [comment]
We could work around that. Thank you!
