### ISSUE TITLE
Is less able to convert org to docx with citations.

### ISSUE THREAD

**Issue by fu123456** [jgm/pandoc#6943]
I tried to convert my org file to docx file with citations by the following command:
``` shell
pandoc -s -S ~/MEGA/bibtex-pdfs/bib/references.bib ./Export-org-mode-to-docx-with-citations-via-pandoc.org ./temp1.docx
```
But I got the error:
``` txt
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
```
So I want to know how to avoid this issue and correctly convert org to docx with citation.
Very thanks.

**Comment by Delanii** [comment]
The error states that you have used wrong command-line argument. Have you tryed the suggested command, meaning:

```
pandoc -s -f org+smart ~/MEGA/bibtex-pdfs/bib/references.bib -o ./temp1.docx ./Export-org-mode-to-docx-with-citations-via-pandoc.org
```

But I think you should also specify some argument for bib file; look into docs ;)
