### ISSUE TITLE
Jira Reader: Link not correctly parsed

### ISSUE THREAD

**Issue by anxgstadler** [jgm/pandoc#6944]
Using Pandoc 2.11.1

I get this from the Jira API:
`[http://www.example.com/ -->|http://www.example.com/]`

When transformed to HTML, it yieds:
`<p><a href="http://www.example.com/"><a href="http://www.example.com/ --&gt;">http://www.example.com/ --&gt;</a></a></p>`

There is a link nested within another link...

Thanks for all your work!

**Comment by jgm** [comment]
What *should* the output be here?

**Comment by anxgstadler** [comment]
Sorry for not adding this.
The output should probably be this:
`<p><a href="http://www.example.com/">http://www.example.com/ --&gt;</a></p>`

**Comment by tarleb** [comment]
Can confirm that this should be the result. I'll fix this with the next jira-wiki-markup release.
