### ISSUE TITLE
Pandoc release for linux on power platform (ppc64le)

### ISSUE THREAD

**Issue by kishorkunal-raj** [jgm/pandoc#6945]
Hi Team,
As I was looking through the releases of pandoc, I didn't found release for ppc64le platform( linux on power) which is being widely used across the countries. So will it be possible to release for the same in future.

Thanks!

**Comment by mb21** [comment]
> which is being widely used across the countries

[citation needed] ;-)

Meanwhile, have you tried building from source?

**Comment by jgm** [comment]
We only provide binaries for the most common platforms, as a convenience. This is an open source project and the normal method of getting a binary is to build from source on your own platform, or to use your distro's package manager.

**Comment by ickc** [comment]
Actually Anaconda releases pandoc in that arch: https://anaconda.org/anaconda/pandoc

For more info: conda has channels. The "defaults" channel is provided by the Anaconda company which has their own infrastructure. The "conda-forge" channel is the community built channel which supports platform similar to that supported by pandoc officially.

The one I linked is provided by Anaconda, (which means that it is supported by Anaconda too.)

May be we should add this info to pandoc.org?

**Comment by ickc** [comment]
More info: for the conda-forge recipe, you can see they download the releases here: https://github.com/conda-forge/pandoc-feedstock/blob/master/recipe/meta.yaml

And from the same file you see they download the ppc64le binary from fedoraproject.org so that's another location to look for support. (Theirs are older and I recommend the one you get from Anaconda.)

**Comment by ickc** [comment]
Correction: conda-forge can handle ppc64le, aarch64:

https://conda-forge.org/docs/maintainer/conda_forge_yml.html?highlight=provider

I'll look into it as it might be good to utilize conda-forge's infrastructure to provide more support of pandoc on different arch. But don't hold your breath.
