### ISSUE TITLE
Ignore shebang at the top of markdown file?

### ISSUE THREAD

**Issue by hoclun-rigsep** [jgm/pandoc#6947]
It's all in the title; `pandoc` is fundamentally a filter, an interpreter of markup.

**Comment by mb21** [comment]
what shebang?

**Comment by tarleb** [comment]
Could you provide a motivating example that demonstrates why this would be useful?

**Comment by jgm** [comment]
Presumably they want to be able to have an executable file like
```
#!/usr/bin/env pandoc -t html
# Hello there
This is my file.
```

**Comment by jgm** [comment]
Note that you can already do this:
```
#!/bin/sh
pandoc -t latex << EOF
# Hello there
EOF
```
And this approach is not limited to Markdown input.

**Comment by hoclun-rigsep** [comment]
Yes, this is perhaps not significant enough to justify anyone's attention. I am content to close it.

**Comment by tarleb** [comment]
OK, thanks! Closing...

**Comment by RokeJulianLockhart** [comment]
A reason for this might be that without it, a shebang would break YAML preambles. I stopped using shebangs for that reason.
