### ISSUE TITLE
epub html table convert to docx failed

### ISSUE THREAD

**Issue by looric** [jgm/pandoc#6953]
pandoc-2.11.2-windows-x86_64.msi

pandoc -s Costing.epub  -o Costing.docx
the generated docx file lost format of table

Sample file attached.
[Costing.zip](https://github.com/jgm/pandoc/files/5699893/Costing.zip)

**Comment by jgm** [comment]
You don't say which features were lost; that would have been helpful.

Looks like one issue is borders, but this isn't part of our document model; we consider these a presentation detail, not part of the content.

The other issue is row/colspans.  We have only recently started adding support for row/colspans to pandoc tables, so I'm not surprised to see problems with such tables. I don't think this issue adds to the existing issue for the docx writer #6315 so perhaps it should be closed.

**Comment by looric** [comment]
thanks, you are right. that's the issue of #6315.
