### ISSUE TITLE
Code block stripped when no language class is present

### ISSUE THREAD

**Issue by Barsonax** [jgm/pandoc#6955]
When converting
```
<pre><code>
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;configuration&gt;
&lt;system.net&gt; 
&lt;defaultProxy useDefaultCredentials="true" enabled="true"&gt; 
&lt;proxy proxyaddress="http://hostname:port" /&gt; 
&lt;/defaultProxy&gt; 
&lt;/system.net&gt; 
&lt;/configuration&gt;
</code></pre>
```
Output:
```
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
    <system.net> 
    <defaultProxy useDefaultCredentials="true" enabled="true"> 
    <proxy proxyaddress="http://hostname:port" /> 
    </defaultProxy> 
    </system.net> 
    </configuration>
```
The only way to get the code block is to add a language:
```
<pre class="xml"><code>
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;configuration&gt;
&lt;system.net&gt; 
&lt;defaultProxy useDefaultCredentials="true" enabled="true"&gt; 
&lt;proxy proxyaddress="http://hostname:port" /&gt; 
&lt;/defaultProxy&gt; 
&lt;/system.net&gt; 
&lt;/configuration&gt;
</code></pre>
```
Output:
````
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<system.net> 
<defaultProxy useDefaultCredentials="true" enabled="true"> 
<proxy proxyaddress="http://hostname:port" /> 
</defaultProxy> 
</system.net> 
</configuration>
```
````

Can also see this happening on [pandoc try](https://pandoc.org/try/?text=%3Cpre%3E%3Ccode%3E%0A%26lt%3B%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%26gt%3B%0A%26lt%3Bconfiguration%26gt%3B%0A%26lt%3Bsystem.net%26gt%3B+%0A%26lt%3BdefaultProxy+useDefaultCredentials%3D%22true%22+enabled%3D%22true%22%26gt%3B+%0A%26lt%3Bproxy+proxyaddress%3D%22http%3A%2F%2Fhostname%3Aport%22+%2F%26gt%3B+%0A%26lt%3B%2FdefaultProxy%26gt%3B+%0A%26lt%3B%2Fsystem.net%26gt%3B+%0A%26lt%3B%2Fconfiguration%26gt%3B%0A%3C%2Fcode%3E%3C%2Fpre%3E&from=html&to=gfm&standalone=0)

**Comment by mb21** [comment]
It's actually indented four spaces, which is a code block as well. See https://pandoc.org/MANUAL.html#verbatim-code-blocks

**Comment by Barsonax** [comment]
ok but hugo doesn't seem to understand this. Any way to make it output backticks?.

**Comment by jgm** [comment]
If Hugo doesn't understand indented code blocks (a core part of the original Markdown, supported by every Markdown implementation I'm aware of, [proof here](https://johnmacfarlane.net/babelmark2/?normalize=1&text=++++%3C%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A++++%3Cconfiguration%3E%0A++++%3Csystem.net%3E+%0A++++%3CdefaultProxy+useDefaultCredentials%3D%22true%22+enabled%3D%22true%22%3E+%0A++++%3Cproxy+proxyaddress%3D%22http%3A%2F%2Fhostname%3Aport%22+%2F%3E+%0A++++%3C%2FdefaultProxy%3E+%0A++++%3C%2Fsystem.net%3E+%0A++++%3C%2Fconfiguration%3E%0A)), then it's a serious bug in Hugo and should be reported there.

**Comment by mb21** [comment]
You could probably write a pandoc lua filter to add some dummy attributes to force the writer to use fenced code blocks...
