### ISSUE TITLE
LuaLaTex: Wrong ordering of quotes

### ISSUE THREAD

**Issue by ragreener1** [jgm/pandoc#6958]
This issue does not occur with pandoc-citeproc.

I am using pandoc 11.22 and citeproc 0.2. I am using chicago-author-date (the default) as the CSL

I am trying to cite an article with the title: 'On the Outside': Constructing Cycling Citizenship

With citeproc it gets rendered incorrectly as (double, single, double single):
Aldred, Rachel. 2010. “‘On the Outside”: Constructing Cycling Citizenship.’ Social & Cultural Geography 11 (1): 35–52. https://doi.org/10.1080/14649360903414593.

Whereas with pandoc-citeproc I get single, double, double, single:
Aldred, Rachel. 2010. ‘ “On the Outside”: Constructing Cycling Citizenship’. Social & Cultural Geography 11 (1): 35–52. https://doi.org/10.1080/14649360903414593.

**Comment by jgm** [comment]
https://tex.stackexchange.com/questions/575292/unexpected-difference-between-lualatex-and-pdflatex-with-babel-and-quotes

**Comment by jgm** [comment]
Apparently it's expected behavior for lualatex.
I think pandoc's LaTeX writer will automatically insert the `\,` to separate quotes, but this is not happening now because of the span surrounding the inner quotes.
I think I can make a small modification to the LaTeX writer that will handle this case.

**Comment by jgm** [comment]
Workaround:  add `-t latex-smart` to your command line.  This will cause unicode quote characters to be inserted instead of the ligatures, and it avoids the problem entierly.

**Comment by ragreener1** [comment]
The workaround works as expected. Thanks a lot for your help--much appreciated!

**Comment by denismaier** [comment]
> add `-t latex-smart` to your command line. This will cause unicode quote characters to be inserted instead of the ligatures, and it avoids the problem entirely.

By the way, why aren't unicode quote characters the default with unicode-aware pdf-engines. I guess that would be a safe choice with `xelatex` and `lualatex`, and even `pdflatex` has basic utf-8 support baked into the kernel nowadays.

**Comment by jgm** [comment]
> By the way, why aren't unicode quote characters the default with unicode-aware pdf-engines

It's because we generate the same latex no matter what engine is chosen.  (We also need to support the case where people generate a tex file and then do what they like with it.)

**Comment by tarleb** [comment]
I tried to solve this, but got confused: in my tests I got the correct result if the PDF is generated with pandoc and `--pdf-engine=lualatex`, but a faulty result when going via a new LaTeX file first.

**Comment by denismaier** [comment]
> I tried to solve this, but got confused: in my tests I got the correct result if the PDF is generated with pandoc and `--pdf-engine=lualatex`, but a faulty result when going via a new LaTeX file first.

I'm even more confused. I get correct results with both ways.

**Comment by jgm** [comment]
I can no longer reproduce the issue either.
(Either with direct-to-pdf or via a tex file.)

**Comment by tarleb** [comment]
This is what I'm using:

``` markdown
---
lang: en-GB
---

'["On the Outside"]{}: Constructing Cycling Citizenship.'
```

with command

    pandoc -t latex -s input.md -o out.tex && lualatex out

Checking the output of

    pandoc -t latex input.md -o out.pdf --verbose

I noticed that the intermediary LaTeX produced by when going directly to PDF uses Unicode characters as quotes, which is not the case in `out.tex`.

**Comment by jgm** [comment]
OK, I can reproduce it this way.

**Comment by jgm** [comment]
What's the recommended action, if any?  Going straight to pdf with pandoc works fine already, because we disable the `smart` extension for that.  We could disable the `smart` extension for LaTeX by default, but I don't want to change that.  People creating tex files using pandoc and running lualatex on them could be advised to disable `smart` (`-t latex-smart`).
So I don't see anything that really needs changing.

**Comment by tarleb** [comment]
> So I don't see anything that really needs changing.

I don't see anything obvious either.

**Comment by denismaier** [comment]
Maybe disable smart if the pdf-engine is set to lualatex?
