### ISSUE TITLE
Consider not overwriting reveal.js default for history

### ISSUE THREAD

**Issue by lassepe** [jgm/pandoc#6968]
On the current master (7e98562c04be19f533bc806a8525fe203d1ede58) fragments on revealjs slides cause background videos (rendered via `data-background-video`) to restart if the config option `fragmentInURL` is set to `true`. Thus, whenever the next fragment is displayed, the background video starts from the beginning. Here is a minimal example to reproduce the bug:

```pandoc
---
title: Test
theme: simple
revaljs-url: https://unpkg.com/reveal.js@^4/
---

# Some Slide {data-background-video="https://upload.wikimedia.org/wikipedia/commons/transcoded/9/96/Curiosity%27s_Seven_Minutes_of_Terror.ogv/Curiosity%27s_Seven_Minutes_of_Terror.ogv.480p.vp9.webm"}


::: incremental
- one
- two
- three
:::
```

I have an old deck of slides where this still worked. I'm not sure which pandoc version it was rendered with (is there a way to recover that information from the output document?). The only hint I have is that that version was using revealjs 3.9 so it must have something like pandoc 2.8.

**Comment by mb21** [comment]
Could you compare the current HTML generated and the old (working) one? What's the difference?

**Comment by jgm** [comment]
I'd check first to make sure this isn't a bug or intentional behavior change in reveal.js.
If it's a bug in pandoc we'd need to know specifically how to change the HTML we are generating.

**Comment by lassepe** [comment]
I finally found the time to reproduce the old output with pandoc 2.7.3 and found the source of the difference in behavior:

In pandoc 2.7.3 `fragmentInURL` was not yet supported by the default template and instead I used a custom reveal.js template that would just forward all config options in the way I suggested in https://github.com/jgm/pandoc/issues/5963. Thus, for any option that I did not specify, the revealjs default was used. This caused `history` to be set to `false`. With `hash: true` and `fragmentInURL: true` I got the desired behavior which is:

1. Due to `hash: true` the slide number is part of the URL I will land on the same page, even if I reload.
2. Due to `fragmentInURL: true` the fragment-id is part of the URL and I will get the exact same fragment state on reload

In newer pandoc releases that now include the changes introduced in https://github.com/jgm/pandoc/pull/6347 `fragmentInURL` is officially supported. However, the `history` default of revealjs is overwritten in the revealjs.default template:

https://github.com/jgm/pandoc/blob/9cbbf18fe18d740e12f564506079f3a2cb853be6/data/templates/default.revealjs#L125

Thus, in order to yield the desired behavior, one has to additionally specify `history: false` as this would cause the video to reload. Therefore, I would consider this issue resolved.

That said, I would suggest to maybe remove the overwriting of the default value for `history` in the `revealjs.default` template. In fact, I believe it is good to stay as close as possible to the upstream defaults. Is there a particular reason, why this has been overwritten?

**Comment by mb21** [comment]
Thanks for reporting back!

> Is there a particular reason, why this has been overwritten?

not sure, this was introduced already 3 years ago: https://github.com/jgm/pandoc/commit/8b9448aa17e330f9ff25fc7ddf909151fb876132

perhaps we thought it's a better default?

**Comment by lassepe** [comment]
It seems like `history: true` is a possible workaround to make sure that the slide is the same on reload. However, if that is the desired behavior, then `hash: true` seems like the cleaner solution (maybe that was not available at the time?).

**Comment by jgm** [comment]
I'll re-open this as a request to reconsider the default.

**Comment by mb21** [comment]
> hash: true seems like the cleaner solution 

why do you think so?

I generally agree that pandoc should stay as closely to the defaults of upstream things like revealjs as possible... but this one has been like that for so long, that changing it would probably cause more trouble (i.e. broken links) than not (e.g. your use-case with the custom template and video seems an edge-case).

**Comment by lassepe** [comment]
I certainly think that avoiding to break any existing documents is important. Thus, I'm totally fine with keeping the current default. After all, I am typically starting with my own default header whenever I start a new deck of slides so there is no need to force my personally preferred defaults onto everyone using pandoc. 

> > hash: true seems like the cleaner solution
> 
> why do you think so?

If the intention of the default `history: true` is only to make sure that refreshing the tab will yield the same slide to be rendered, then using `history: true` seems like an unnecessary level of indirection. As per the [documentation of the revealjs config](https://revealjs.com/config/):

```javascript
  // Push each slide change to the browser history.  Implies `hash: true`
  history: true,
```
and

```javascript
  // Add the current slide number to the URL hash so that reloading the
  // page/copying the URL will return you to the same slide
  hash: true,
```

Thus, if only the reload behavior is relevant, `hash: true` seems the right thing to do. If what is needed is to actually populate the browser history, `history: true` seems the right option to set. So it really depend on what the intention of that default is.

That said, it may be considered a revealjs bug if `history: true` causes the background video to restart with every fragment change. So maybe the right fix here is to file that issue upstream.

**Comment by tarleb** [comment]
Does this mean the issue can be closed, or should there be changes to either the code or documentation?

**Comment by jgm** [comment]
I think I agree that it might make sense to stop imposing our default `history: true`.
Adding a default to `hash: true` also seems sensible.
