### ISSUE TITLE
org code listing caption not processed

### ISSUE THREAD

**Issue by credmp** [jgm/pandoc#6977]
When a caption is defined in an org file it is not processed when set on a SRC block.

In the below sample the table and figure caption are processed correctly, the code caption is only added to the text, but not as caption.

```
#+TITLE: Test

Here is some text

#+caption: This is code
#+BEGIN_SRC php
if ($this) {
    $that;
}
#+END_SRC


#+CAPTION: This is a table
| col1 | col 2 | col 3 |
|    1 |     2 |     3 |
|      |       |       |

#+CAPTION: This is a figure
[[./rapport_att/akount-full-run.png]]
```
The following markdown is created. I changed the code block markdown indicators to not mess up the formatting, they are ok in the output.

```
Here is some text

<div>

[This is code]{.label}

` ` ` {.php}
if ($this) {
    $that;
}
` ` `

</div>

  ------ ------- -------
  col1   col 2   col 3
  1      2       3
                 
  ------ ------- -------

  : This is a table

![This is a figure](./rapport_att/akount-full-run.png)
```
Pandoc version output, :

```
pandoc 2.11.3.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.2,
citeproc 0.3.0.1, ipynb 0.1.0.1
User data directory: /root/.local/share/pandoc or /root/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
There's no space for a code caption in the pandoc AST, but we could perhaps just include the caption as a paragraph in front of the code block?

**Comment by credmp** [comment]
When a caption is added in markdown it does produce correct output.

```
{.html caption="Porrigitur et Pal.."}
```

**Comment by credmp** [comment]
I have been going through the code, I don't quite understand Haskell yet, but I did find that a block can have a [caption attribute](https://github.com/jgm/pandoc/blob/99e1b67b74ddcbf7ffc8add640493f73471cf50a/src/Text/Pandoc/Readers/Org/Blocks.hs#L95).

**Comment by jgm** [comment]
If you generate TeX with `--listings`, then yes, the caption attribute will have an effect. Otherwise, not.  And in general, our writers do not pay attention to the caption attribute on code blocks.  So setting this (while possible) won't have the desired effect in most output formats.

**Comment by credmp** [comment]
I created 2 documents; one markdown and one org-mode.

Markdown:
```
---
title: "Test"
...

` ` `{.php caption="This is code"}
if ($this) {
    $that;
}
` ` ` 
```
(spaces in the code fence to make it visible here)

Org:
```
#+TITLE: Test

#+CAPTION: This is code
#+BEGIN_SRC php
if ($this) {
    $that;
}
#+END_SRC
```
I then ran `pandoc` as follows:
```
pandoc  test-code.org  --to latex  -o "org-tex.tex"  --listings
pandoc  test-code.md  --to latex  -o "md-tex.tex"  --listings
```
The resulting LaTeX document differs. The markdown reader takes the caption of the code block and passes it on to the writer of the latex code, the org reader seems to not process the caption correctly. Seeing that the markdown reader processes it correctly indicates to me that this would be a bug in the org reader.

```
> diff org-tex.tex md-tex.tex
1,3c1
< {This is code}
< 
< \begin{lstlisting}[language=PHP]
---
> \begin{lstlisting}[language=PHP, caption={This is code}]
```

**Comment by jgm** [comment]
Yes.  That's what I said above, essentially.  The caption attribute has an effect in writing LaTeX, but *only in the special case where `--listings` is used*.  It doesn't affect any other writers.  So, if we changed the org reader to populate the caption attribute of code blocks, this would only make a difference when producing LaTeX using `--listings`.  If this is all that is wanted, it would not be hard to achieve.

**Comment by credmp** [comment]
That would be great, this means the org reader and markdown reader work the same! Thank you!

**Comment by jgm** [comment]
@tarleb what is your view about how this should be handled?

**Comment by tarleb** [comment]
I think the proposed change makes sense, I'll add it.
The downside is that any markup within the caption will be lost.

**Comment by tarleb** [comment]
On second thought, adding the caption in a Div before the code block would preserve the markup. It would still be possible to write a filter to replace the div with a caption attribute. I think we should have another look at the way org treats captions when exporting to other formats.

**Comment by credmp** [comment]
Why would a org caption be treated differently then a markdown caption? The goal of the caption is to be a caption on the listing. 

Esp for master papers it is important to have the caption properly on a code listing.

**Comment by credmp** [comment]
I have to check the org docs, but I don't think markup is supposed to be in the caption itself.

**Comment by credmp** [comment]
The manual does not mention anything about markup (https://orgmode.org/manual/Captions.html), however it does mention short captions vs long captions. For me personally I never used short captions and have not seen them in any student work either.

**Comment by tarleb** [comment]
Here's what different org exporters produce from the snippet.

#### HTML

``` html
<div class="org-src-container">
<label class="org-src-name"><span class="listing-number">Listing 1: </span>This <b>is</b> code!</label>
<pre class="src src-php">if ($this) {
    $that;
}
</pre>
</div>
```
(Syntax highlighting spans removed for readability).

#### LaTeX

``` latex
\begin{verbatim}
if ($this) {
    $that;
}
\end{verbatim}
\captionof{figure}{This \textbf{is} code!}
```
The `\captionof` command is provided by the `capt-of` package.

#### ODT

``` xml
<text:p text:style-name="Listing">
<text:bookmark text:name="nil"/>Listing <text:sequence text:ref-name="nil" text:name="Listing" text:formula="ooow:Listing+1" style:num-format="1">1</text:sequence>: This <text:span text:style-name="Bold">is</text:span> code!</text:p>
<text:p text:style-name="OrgSrcBlock"><text:span text:style-name="OrgSrcPhpKeyword">if</text:span><text:s/><text:span text:style-name="OrgSrcRainbowDelimitersDepth1Face">(</text:span><text:span text:style-name="OrgSrcPhp$thisSigil">$</text:span><text:span text:style-name="OrgSrcPhp$this">this</text:span><text:span text:style-name="OrgSrcRainbowDelimitersDepth1Face">)</text:span><text:s/><text:span text:style-name="OrgSrcRainbowDelimitersDepth1Face">{</text:span></text:p>

<text:p text:style-name="OrgSrcBlock"><text:s/><text:s/><text:s/><text:s/><text:span text:style-name="OrgSrcPhpVariableSigil">$</text:span><text:span text:style-name="OrgSrcPhpVariableName">that</text:span>;</text:p>

<text:p text:style-name="OrgSrcBlockLastLine"><text:span text:style-name="OrgSrcRainbowDelimitersDepth1Face">}</text:span></text:p>
```
![screenshot-odt](https://user-images.githubusercontent.com/507994/103355917-cdf43d00-4aaf-11eb-9b52-93efdf9a476e.png)

**Comment by credmp** [comment]
Thanks! I did not know that, but I guess it makes sense.

**Comment by jgm** [comment]
@credmp you are very much focused on one output target (latex with `--listings`).  If that were all we needed to worry about, this would be uncontroversial and easy.  The hesitation is because we might want to make org captions work well in a variety of output formats.  There are also other input formats that may allow captions to be specified for code blocks.

Probably the simplest way to handle this, *for now*, is to use the `caption` attribute.  (The limitation in formatting may not be a big issue, but I can imagine, for example, wanting to use tex math in a caption, or monospace font.)  But this may not be the most durable way to handle code block captions across formats.

**Comment by credmp** [comment]
That is very true, as this is my use case for pandoc indeed. From my point of view I compare it to markdown, which is of course a very limited view. Thank you for your insights!

**Comment by tarleb** [comment]
You can use the below Lua filter to get the result you expect. It is somewhat awkward looking, so we may still want to change the structure returned by pandoc.

``` lua
function Div (div)
  local label = div.content[1]
  if not label or not label.content then return nil end
  local label_span = label.content[1]
  if label_span and label_span.classes:includes 'label' then
    local codeblock = div.content[2]
    if codeblock.t == 'CodeBlock' then
      codeblock.attributes.caption = pandoc.utils.stringify(label)
      return codeblock
    end
  end
end
```

Save the above to a file and pass that file to pandoc via `--lua-filter`.

**Comment by tarleb** [comment]
I have changed the internal representation to make it easier to match on with a filter. The updated Lua filter looks like this:

```lua
function Div (div)
  if not div.classes:includes 'captioned-content' then return end
  local caption = div.content[1]
  local codeblock = div.content[2]
  if caption and codeblock
      and caption.t == 'Div'
      and codeblock.t == 'CodeBlock'
      and caption.classes:includes 'caption' then
    codeblock.attributes.caption = pandoc.utils.stringify(caption)
    return codeblock
  end
end
```
