### ISSUE TITLE
docx: unreadable content error for nested tables

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#6983]
When writing nested tables (where the inner tables have captions) with the docx writer, I see this error when opening the document in MS Word v16.44 on OS X:

<img width="420" alt="Screen Shot 2020-12-26 at 5 56 46 AM" src="https://user-images.githubusercontent.com/104391/103150144-330e0280-473f-11eb-8b84-d6145a5d3c67.png">

This is the minimal markdown which produced the error (note that it occurs with our without a header on the outer table):

```markdown
+---------------+
| | Col1 |      |
| |------|      |
| | X    |      |
|               | 
| :Cap1         |
+---------------+
```

Note that if I remove the `:` caption prefix from the inner table the error no longer occurs:

```markdown
+---------------+
| | Col1 |      |
| |------|      |
| | X    |      |
|               | 
| Cap1          |
+---------------+
```

The issue appears to be unrelated to the changes in the docx writer introduced in https://github.com/jgm/pandoc/pull/6941 as the same error occurs in both pandoc 2.11.2 and pandoc 2.11.3.

Here is the underlying `document.xml` generated by pandoc 2.11.2:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
  <w:body>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title"/>
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">Tables</w:t>
      </w:r>
    </w:p>
    <w:tbl>
      <w:tblPr>
        <w:tblStyle w:val="Table"/>
        <w:tblW w:type="pct" w:w="1111.111111111111"/>
        <w:tblLook w:firstRow="0" w:lastRow="0" w:firstColumn="0" w:lastColumn="0" w:noHBand="0" w:noVBand="0"/>
      </w:tblPr>
      <w:tblGrid>
        <w:gridCol w:w="1760"/>
      </w:tblGrid>
      <w:tr>
        <w:tc>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="TableCaption"/>
              <w:jc w:val="left"/>
            </w:pPr>
            <w:r>
              <w:t xml:space="preserve">Cap1</w:t>
            </w:r>
          </w:p>
          <w:tbl>
            <w:tblPr>
              <w:tblStyle w:val="Table"/>
              <w:tblW w:type="pct" w:w="0.0"/>
              <w:tblLook w:firstRow="1" w:lastRow="0" w:firstColumn="0" w:lastColumn="0" w:noHBand="0" w:noVBand="0"/>
              <w:tblCaption w:val="Cap1"/>
            </w:tblPr>
            <w:tblGrid/>
            <w:tr>
              <w:trPr>
                <w:cnfStyle w:firstRow="1"/>
              </w:trPr>
              <w:tc>
                <w:tcPr>
                  <w:tcBorders>
                    <w:bottom w:val="single"/>
                  </w:tcBorders>
                  <w:vAlign w:val="bottom"/>
                </w:tcPr>
                <w:p>
                  <w:pPr>
                    <w:pStyle w:val="Compact"/>
                    <w:jc w:val="left"/>
                    <w:jc w:val="left"/>
                  </w:pPr>
                  <w:r>
                    <w:t xml:space="preserve">Col1</w:t>
                  </w:r>
                </w:p>
              </w:tc>
            </w:tr>
            <w:tr>
              <w:tc>
                <w:p>
                  <w:pPr>
                    <w:pStyle w:val="Compact"/>
                    <w:jc w:val="left"/>
                    <w:jc w:val="left"/>
                  </w:pPr>
                  <w:r>
                    <w:t xml:space="preserve">X</w:t>
                  </w:r>
                </w:p>
              </w:tc>
            </w:tr>
          </w:tbl>
        </w:tc>
      </w:tr>
    </w:tbl>
    <w:sectPr/>
  </w:body>
</w:document>
```

**Comment by jgm** [comment]
Does removing the single line
```
              <w:tblCaption w:val="Cap1"/>
```
in the inner table fix the problem?
That would be helpful to know...though I'm not sure why that should make a difference.

**Comment by jjallaire** [comment]
No that doesn't seem to make any difference.

Here is the diff when going from the version that works to the version that doesn't:

<img width="1001" alt="Screen Shot 2020-12-26 at 7 07 11 PM" src="https://user-images.githubusercontent.com/104391/103161300-9f274f80-47ad-11eb-9ae9-534200ac0c9d.png">

**Comment by jgm** [comment]
So, there are three differences I can see;

1.  The w:tblCaption line
2. The relative position of the caption paragraph (before vs after the table)
3. The use of a TableCaption style in that paragraph

Which of these makes the difference between working and not working?

**Comment by jjallaire** [comment]
It looks like it's the relative position. Making this change results in a valid document:

<img width="1002" alt="Screen Shot 2020-12-28 at 9 08 28 AM" src="https://user-images.githubusercontent.com/104391/103219656-4f02d700-48ec-11eb-934b-99e3c7e8bb91.png">

**Comment by jgm** [comment]
In typography, table captions are typically placed above tables (vs figures, where captions are placed below).  Pandoc tries to respect that. If we moved the paragraph below the table we'd be changing the output.

What if we simply omitted captions in nested tables? Are they actually needed?

**Comment by jjallaire** [comment]
Bizarrely, I have found another workaround. If I insert the same openxml (a zero sized text frame) previously used to create a phantom vertical space between tables (to prevent them from being merged together) then the document works:

```xml
<w:p>
  <w:pPr>
    <w:framePr w:w="0" w:h="0" w:vAnchor="margin" w:hAnchor="margin" w:xAlign="right" w:yAlign="top"/>
  </w:pPr>
</w:p>
```

The diff is:

<img width="995" alt="Screen Shot 2020-12-28 at 1 42 32 PM" src="https://user-images.githubusercontent.com/104391/103236302-8edcb500-4912-11eb-9f0d-80d074efcf96.png">

(basically just insert the zero sized text frame right after the nested table)

That though might be too much voodoo to be considered reliable (although it seems like when dealing w/ openxml you do encounter strange boundary conditions like this which have no other resolution).

In terms of excluding the caption entirely, an alternative to this might be to locate it below for a nested table (as this is how the `subfig` and `subcaption` packages handle captions for nested latex tables, so arguably consistent w/ latex typography standards):

<img width="385" alt="Screen Shot 2020-12-28 at 1 46 49 PM" src="https://user-images.githubusercontent.com/104391/103236542-26da9e80-4913-11eb-84da-80355b2fc06f.png">

**Comment by jjallaire** [comment]
I've discovered that it's enough to just stick an empty paragraph below the table (which also appears to occupy no vertical space in the document):

<img width="996" alt="Screen Shot 2020-12-28 at 4 36 27 PM" src="https://user-images.githubusercontent.com/104391/103244436-03bbe900-492b-11eb-917c-c631eb3c30f4.png">

**Comment by jgm** [comment]
So, to make sure I understand, it would suffice to insert an empty paragraph after each table that occurs nested in another table?

**Comment by Matthew2011877** [comment]
What do you mean  an empty coloumn



Richard

**Comment by Matthew2011877** [comment]
Really starting to understand now man

**Comment by jjallaire** [comment]
Yes, by inserting this openxml the document opened up fine (and it did not appear there was additional vertical space occupied by the empty paragraph):

```xml
<w:p>
</w:p>
```

**Comment by jgm** [comment]
See #4953

**Comment by jgm** [comment]
This code (already in the writer) should add an empty p at the end of a table cell if that cell does not contain a p:
``` haskell
  -- Table cells require a <w:p> element, even an empty one!
  -- Not in the spec but in Word 2007, 2010. See #4953.
  let cellToOpenXML (al, cell) = do
        es <- withParaProp (alignmentFor al) $ blocksToOpenXML opts cell
        return $ if any (\e -> qName (elName e) == "p") (onlyElems es)
           then es
           else es ++ [Elem $ mknode "w:p" [] ()]
```

**Comment by jgm** [comment]
I guess this code isn't triggered here because the caption is a p.  I wonder if we should simply check to see if the LAST element is a p, and insert an empty p otherwise?

**Comment by jgm** [comment]
OK, try it with the fix I just pushed.

**Comment by jjallaire** [comment]
That does indeed resolve it for the example case! I have one more scenario I want to test with and will report back on that tomorrow.

**Comment by jjallaire** [comment]
There is at least one case where this change results in additional padding at the bottom of a cell (i.e. `<w:p/>` not strictly required for a valid document that nonetheless occupies vertical space). 

For this markdown (rendered by pandoc w/o the change):

```markdown
+-------------------+
| ::: {#elephant}   |
| Elephant          |
| :::               |
+-------------------+
```

We get the following openxml:

```xml
<w:tr>
  <w:tc>
    <w:bookmarkStart w:id="20" w:name="elephant"/>
    <w:p>
      <w:pPr>
        <w:jc w:val="left"/>
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">Elephant</w:t>
      </w:r>
    </w:p>
    <w:bookmarkEnd w:id="20"/>
  </w:tc>
</w:tr>
```

And the following rendered docx:

<img width="187" alt="Screen Shot 2020-12-29 at 6 32 41 AM" src="https://user-images.githubusercontent.com/104391/103280997-b9288400-499f-11eb-81f2-f4872e0136e6.png">

With the patch we get this openxml:

```xml
<w:tr>
  <w:tc>
    <w:bookmarkStart w:id="20" w:name="elephant"/>
    <w:p>
      <w:pPr>
        <w:jc w:val="left"/>
      </w:pPr>
      <w:r>
        <w:t xml:space="preserve">Elephant</w:t>
      </w:r>
    </w:p>
    <w:bookmarkEnd w:id="20"/>
    <w:p/>
  </w:tc>
</w:tr>
```

And this rendered docx:

<img width="187" alt="Screen Shot 2020-12-29 at 6 35 29 AM" src="https://user-images.githubusercontent.com/104391/103281135-10c6ef80-49a0-11eb-9a3f-c120868279ac.png">

So it looks like a div resulting in a wrapping bookmark and containing a trailing paragraph also qualifies as "valid". 

It's noteworthy that in this case (but not the case of a table) we see extra vertical space generated. Who knows why.

**Comment by jgm** [comment]
I'll reopen to tweak this further.

**Comment by jgm** [comment]
Try with the latest.

**Comment by jjallaire** [comment]
That does the trick, thanks!
