### ISSUE TITLE
Handle col/rowspans in mediawiki tables

### ISSUE THREAD

**Issue by Dolu89** [jgm/pandoc#6992]
Hello,
I discovered a problem on the converter mediawiki to gfm (and all markdown destination)
It cuts off everything after the colspan
Pandoc version (ubuntu 20.04 LTS) 
```
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

**Source mediawiki**
``` mediawiki
Block template creation can be influenced by various parameters:
{| class="wikitable"
!colspan=4|template request
|-
! Key !! Required !! Type !! Description
|-
| capabilities || No || Array of Strings || SHOULD contain a list of the following, to indicate client-side support: [[#Optional: Long Polling|"longpoll"]], "coinbasetxn", "coinbasevalue", [[bip-0023.mediawiki#Block Proposal|"proposal"]], [[bip-0023.mediawiki#Logical Services|"serverlist"]], "workid", and any of the [[bip-0023.mediawiki#Mutations|mutations]]
|-
| mode || No || String || MUST be "template" or omitted
|}
```
**Result of mediawiki**
![Capture d’écran de 2020-12-30 10-26-05](https://user-images.githubusercontent.com/4184590/103342349-95416d00-4a89-11eb-8deb-4e88cac09fa4.png)

I run this command to transform my mediawiki file to a md file
`pandoc -f mediawiki -t gfm ./mediawiki-file.mediawiki -o ./gfm-file.md`

**Result provided by pandoc (gfm)**
``` markdown
Block template creation can be influenced by various parameters:

| template request |
| ---------------- |
| Key              |
| capabilities     |
| mode             |
```
**Result of gfm**
![Capture d’écran de 2020-12-30 10-29-44](https://user-images.githubusercontent.com/4184590/103342538-06812000-4a8a-11eb-8fb3-7bb1a8ade6ee.png)

**Comment by jgm** [comment]
Until recently pandoc could not represent col/rowspans in tables.
This has changed in the basic types, but we haven't updated all the readers and writers yet.

**Comment by Dolu89** [comment]
Hi, I was just wondering if there are any updates on this issue and its resolution timeline.
Thanks!
