### ISSUE TITLE
Table header not converted properly

### ISSUE THREAD

**Issue by Barsonax** [jgm/pandoc#6994]
I noticed that a table header is now put inside the table instead of above. In a previous version this was not the case.
https://pandoc.org/try/?text=%3Ctable+class%3D%22table%22%3E%0A++++%3Ctbody%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Cth%3EName%3C%2Fth%3E%0A++++++++++++%3Cth%3ERequired%2FOptional%3C%2Fth%3E%0A++++++++++++%3Cth%3EDefault+value%3C%2Fth%3E%0A++++++++++++%3Cth%3EComment%3C%2Fth%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EAll+devices%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EID+of+the+device+group%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3ETrue%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EIndication+whether+current+values+of+the+first+two+sensors+must+be+returned.%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EByStatus%3C%2Ftd%3E%0A++++++++++++%3Ctd%3ESort+order.+Allowed+values+are+ByStatus+and+Alphabetical.%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EAll+Filter+by+status.%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EAllowed+values+are+All%2C+Errors%2C+ErrorsAndWarnings%2C+NoData%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EItemsOnly+Filter+groups+or+devices.%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EAllowed+values+are+All%2C+GroupsOnly%2C+ItemsOnly%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3E0%3C%2Ftd%3E%0A++++++++++++%3Ctd+rowspan%3D%222%22%3ESkip%2FTake+are+used+in+conjunction+with+each+other+to+determine+the+%E2%80%9Cpage%E2%80%9D+of+requested+data.%0A++++++++++++%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3E10%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++++++%3Ctr%3E%0A++++++++++++%3Ctd+%2F%3E%0A++++++++++++%3Ctd%3EOptional%3C%2Ftd%3E%0A++++++++++++%3Ctd%3ELast24Hours%3C%2Ftd%3E%0A++++++++++++%3Ctd%3EThe+period+to+be+used+to+calculate+the+Uptime+percentage.+See+for+details.%3C%2Ftd%3E%0A++++++++%3C%2Ftr%3E%0A++++%3C%2Ftbody%3E%0A%3C%2Ftable%3E&from=html&to=gfm&standalone=0

Also when converting this back to html using pandoc the `<th>` is now a `<td>`.

```
PS C:\git> pandoc --version
pandoc.exe 2.11.3.2
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1
User data directory: C:\Users\damric\AppData\Roaming\pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by Barsonax** [comment]
I noticed the html was actually not correct as the `<th>` should be put inside a `<thead>` tag instead of the `<tbody>` tag.

**Comment by tarleb** [comment]
We had to find a compromise between backwards compatibility and support for more detailed tables. You can restore the automatic recognition of the header row by removing the `<tbody>` tag. We assume that, if that tag is present, no autodetection is necessary.
