### ISSUE TITLE
table line height increase in 2.11.3

### ISSUE THREAD

**Issue by quite** [jgm/pandoc#6996]
Going from 2.11.1.1 to 2.11.3, the line height of the following pipe_table increased unexpectedly. It looks pretty bad, especially on tables with more lines.

This is on a fresh Arch Linux, running pre-compiled pandoc-bin from the AUR, texlive-core 2020.57066-1. I can see table handling has undergone an overhaul...

```
*foobar*|*n*
:------------------------|-----:
`bazbar`|`60`
```

![2 11 1 1](https://user-images.githubusercontent.com/488679/103436646-4da01a00-4c1e-11eb-9468-430284854cf9.png)
![2 11 3](https://user-images.githubusercontent.com/488679/103436649-50027400-4c1e-11eb-9c44-a71b8b15f731.png)

(quick-n-dirty crops...)

**Comment by tarleb** [comment]
LaTeX produced by 2.11.1.1:

```latex
\begin{longtable}[]{@{}lr@{}}
\toprule
\emph{foobar} & \emph{n}\tabularnewline
\midrule
\endhead
\texttt{bazbar} & \texttt{60}\tabularnewline
\bottomrule
\end{longtable}
```

LaTeX produced by 2.11.3:

```latex
\begin{longtable}[]{@{}lr@{}}
\toprule
\emph{foobar} & \emph{n} \\ \addlinespace
\midrule
\endhead
\texttt{bazbar} & \texttt{60} \\ \addlinespace
\bottomrule
\end{longtable}
```

**Comment by jgm** [comment]
```
commit b5b5ef92cbb48a709e8de861d64db29516daf815
Author: John MacFarlane <jgm@berkeley.edu>
Date:   Sun Nov 22 10:54:42 2020 -0800

    LaTeX writer: Improve table spacing.
    
    + Remove the `\strut` that was added at the end of minipage
      environments in cells.
    
    + Replace `\tabularnewline` with `\\ \addlinespace`.
    
    Closes #6842, closes #6860.
```
The suggestion to replace `\tabularnewline` with `\\ \addlinespace` came from https://tex.stackexchange.com/questions/571329/minipage-in-table-has-strange-inter-row-spacing (Mico's answer), but I may have misinterpreted it, because now I see the command at issue was `\tabularnewline[12pt]` which may be requesting more space.

**Comment by jgm** [comment]
I guess we just need to decide what looks best.  Here's what it looks like currently (with `\addlinespace`):
<img width="625" alt="Screen Shot 2021-01-01 at 10 46 37 AM" src="https://user-images.githubusercontent.com/3044/103444618-c4d5ae00-4c1e-11eb-843b-5a1961066f05.png">

And here's what it looks like if we remove the `\addlinespace`:

<img width="684" alt="Screen Shot 2021-01-01 at 10 46 53 AM" src="https://user-images.githubusercontent.com/3044/103444622-d028d980-4c1e-11eb-8b8f-4de4cd05421b.png">

**Comment by quite** [comment]
The latter is better to me, especially because it has even vertical spacing above and below each row ("padding"). That's a table for me. I also like that said spacing is not very big.

Having a less dense table (still evenly spaced) could be an option, a user preference, but not the default.
