### ISSUE TITLE
LaTeX environments as a Div?

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#6997]
In parsing LaTeX environments without `raw_tex` extension, pandoc currently tries to parse the environment's contents and just skips the begin and end tag (with a warning).

Proposal: instead of doing this, parse the contents as before but put them in a Div with class = the environment name.  (We probably still want the warning, though, to inform the user that the formatting normally associated with the environment is not being applied.)

Do the same for unknown LaTeX commands, but with Spans rather than Divs.

See pandoc-discuss thread "[LaTeX → RST] Export environments into directives".

**Comment by jgm** [comment]
OK, I think this should be done just with environments.  There are too many commands whose contents should not be treated as textual; skipping them when `raw_tex` is disabled (as we currently do) seems the best approach.

**Comment by dbitouze** [comment]
Many thanks!
