### ISSUE TITLE
Pandoc can not handle filename with white space on linux (even though spaces are escaped in bash)

### ISSUE THREAD

**Issue by federerfanatic** [jgm/pandoc#6999]
Asking a question?
Please use the pandoc-discuss mailing list instead:
https://groups.google.com/forum/#!forum/pandoc-discuss
This tracker is for bug reports and enhancement requests.

pandoc --version
pandoc 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/nafdef/.local/share/pandoc or /home/nafdef/.pandoc

If one saves the page from chrome using CrtlS it saves the result as: The mathematician who helped to reshape physics.html (note the spaces) and associated files as The mathematician who helped to reshape physics_files. 

Then if one runs pandoc -f html -t epub -s -i The mathematician\ who\ helped\ to\ reshape\ physics.html and outputs it to The mathematician\ who\ helped\ to\ reshape\ physics.epub one gets:
pandoc: The: openBinaryFile: does not exist (No such file or directory)

I.e. whitespace is NOT being escaped even though Bash does this when I do a tab complete.

HOWEVER, if one surrounds the filenames with single quotes ' it works.

**Comment by tarleb** [comment]
Looks like there's a backslash missing after the second `The`.

**Comment by federerfanatic** [comment]
> Looks like there's a backslash missing after the second `The`.

Actually that's a typo. I just did the test again and made sure it was there. Basically the problem
is it's the first escaped whitespace that is NOT recognized. Proving my assertion :-)

**Comment by tarleb** [comment]
Please post the full command you are using and double check that all spaces are properly escaped. This does not look like a pandoc problem.

**Comment by federerfanatic** [comment]
Using Brave browser:
1. Goto URL: https://www.nature.com/articles/d41586-020-02297-2
2. Ctrl+S, that is, save (by the way trying to retrieve the data via the website using pandoc directly does nothing)
3. Result is:
drwx------   2 nafdef nafdef        32 Jan  2 10:20 The mathematician who helped to reshape physics_files
drwxr-xr-x   5 nafdef nafdef       170 Jan  2 10:20 .
-rw-rw-r--   1 nafdef nafdef    246205 Jan  2 10:20 The mathematician who helped to reshape physics.html

Then one runs pandoc --verbose -f html -t epub -s -i The\ mathematician\ who\ helped\ to\ reshape\ physics.html -o A.epub 

result is: pandoc: The: openBinaryFile: does not exist (No such file or directory)

I made a point of the output file NOT having the whitespace but only the input files.

As I noted if instead one runs:
pandoc  -f html -t epub -s -i 'The\ mathematician\ who\ helped\ to\ reshape\ physics.html' -o A.epub

it works, i.e. it is not enough to escape the whitespace but single quoting it in bash works.

**Comment by jgm** [comment]
Here's what I observe.
```
% cat >"The dog is tired.txt"
hi
% cat The\ dog\ is\ tired.txt 
hi
% pandoc The\ dog\ is\ tired.txt
<p>hi</p>
 % pandoc --verbose -t epub -s -i The\ dog\ is\ tired.txt -o A.epub
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'The dog is tired' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
% pandoc --verbose -f html -t epub -s -i The\ dog\ is\ tired.html -o A.epub
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'The dog is tired' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
```
That all seems to work fine.  Do you see different results with these simple tests?  By the way, `-i` does nothing for epub output. It is for specifying "incremental" behavior in slide shows.

**Comment by jgm** [comment]
I also tried with your exact instructions.  I did not observe the problem, either on macOS with zsh or linux (debian stable) with bash.  (I used Firefox rather than Brave.)  Note that I was testing with the latest pandoc release.  You might try upgrading to see if that helps.

**Comment by federerfanatic** [comment]
It does seem to be something I am doing. I have a fairly sophisticated
bashrc file

set -o yields (bash shell)
set -o
allexport       off
braceexpand     on
emacs           off
errexit         off
errtrace       on
functrace       on
hashall         on
histexpand     on
history         on
ignoreeof       off
interactive-comments on
keyword         off
monitor         on
noclobber       off
noexec         off
noglob         off
nolog           off
notify         off
nounset         off
onecmd         off
physical       off
pipefail       off
posix           off
privileged     off
verbose         off
vi             on
xtrace         off




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by federerfanatic** [comment]
Ok. Standard Bashrc as setup in a new account on Ubuntu WORKS OK. so this
would seem to confirm that I have something
weird. going on. I will try strace perhaps.



--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by federerfanatic** [comment]
Confirming myself that openBinary is a Haskell function call. Was wondering
if it had something to do with linux system call.



--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by tarleb** [comment]
Thank you for keeping us updated. It seems the issue has been resolved, hence closing...
