### ISSUE TITLE
Support html named anchors refs

### ISSUE THREAD

**Issue by gmccullo** [jgm/pandoc#7000]
When converting markdown to epub, cross-references to named locations only work if the location is named using pandoc-specific syntax. But html named anchors are valid markdown code and should be supported. This works:

Doc 1:

```
[]{#foobar} Foobars are good.
```

Doc 2:

```
Fubar. See [Foobar](#foobar).
```

This should also work:

Doc 1:

```
<a id="foobar"><a> Foobars are good.
```

Doc 2:

```
Fubar. See [Foobar](#foobar).
```

This comes up, for example, when you have a large file in markdown that you break up into smaller html files in the epub. So that cross-refs that are in the same file in markdown are in different files in the epub.

**Comment by jgm** [comment]
I assume the backslashes in these code samples aren't intended, and `I'd` should be `id`?

Anyway, the main difference here is that `[]{#foobar}` is  (pandoc) markdown syntax, while `<a id="foobar">` is raw HTML. Pandoc has a policy of parsing  raw HTML as `RawBlock` or `RawInline` elements in the AST (thus, this will not be parsed as a native Span element with an identifier).  This policy is pretty well engrained -- it has its roots in original Markdown behavior of passing through raw HTML unchanged, and changing it (e.g. by parsing the HTML) would produce unexpected changes for many users.  For example, some people rely on the present behavior, which allows them to include both raw HTML (for HTML targets) and raw LaTeX (for LaTeX targets), without worrying about getting duplicated content.

**Comment by gmccullo** [comment]
(Fixed the typos.)

I'm probably not following exactly what you mean, but it seems to me the html "<a id="foobar"><a>" would not be altered in the output. Instead what would change in the output is how "[Foobar](#foobar)" is transformed?

**Comment by jgm** [comment]
>  Instead what would change in the output is how "[Foobar](#foobar)" is transformed?

I see.  We currently have a function `fixInternalReferences` which adjusts the references after the document is split into chapters.  This uses a table of references constructed by `extractLinkURL`.  Currently, `extractLinkURL` traverses the AST and finds identifiers on Spans, Divs, and Headers.  That ought at least to be expanded to include other elements that can now have identifiers (Links, Images, Tables).   What you are suggesting is that we also include identifiers in raw HTML elements.  This could be done by tokenizing the raw HTML using tagsoup and extracting the identifier attributes.  I'll reopen this, then.
