### ISSUE TITLE
Support explicit identifiers on toc items.

### ISSUE THREAD

**Issue by gmccullo** [jgm/pandoc#7001]
I want a way to reliably apply CSS styles to individual items of the TOC. 

Use case: the index of a book might have alphabetical subsections A–Z. To make it easy for the reader to jump to individual sections I want those sections to be in the TOC. But to make it compact I want to style those individual items as inline blocks. So imagine a TOC that looks like this:

```
Prologue
...
Chapter 32
    Where I Went
    What I Did
    How I Lived
Postscript
Index
    A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
```

If I could define a CSS selector to target the "Index" TOC item I could change the list style for the "A–Z" links. TOC items have IDs but they're auto-generated, so they could change. I want a way to specify the ID of an individual TOC item.

**Comment by jgm** [comment]
You can manually specify the identifier for a section (such as Index).  Suppose it's `index`.  Then the TOC entry "Index" will have an `<a href="#index">`.  Can't you select this in CSS using
``` css
a[href="#index"]
```

**Comment by gmccullo** [comment]
Good call. Don't know how I missed that.

**Comment by jgm** [comment]
I'll close this, then, since there's a relatively easy solution.

**Comment by gmccullo** [comment]
I'm getting around to working on this again. But I don't see it working the way you suggested. I added an ID to the header I want to target: "head-appendices". But here's what I get in the TOC:

```html
<a 
    href="javascript:void(0)" 
    data-osjsyjidtwtikolbksz9yd="{&quot;name&quot;: &quot;EPUB/text/ch223.xhtml&quot;, &quot;frag&quot;: &quot;head-appendices&quot;}">
    Appendices
</a>
```

The href is just "javascript:void(0)". The actual ID is in the data attribute.

**Comment by jgm** [comment]
This doesn't look the toc generated by pandoc.  If you're generating it some other way, then pandoc isn't really relevant here.

**Comment by gmccullo** [comment]
Yup you're right. I was just peaking at the source generated by the calibre ebook reader. I didn't realize it was different from the xhtml in the epub itself. Doh!

**Comment by gmccullo** [comment]
Of course the problem with this is that I still can't use your proposed solution to target the nav node I want to style.

However note that the epub nav ID _is_ preserved in the viewer nav. So _if_ the custom ID _was_ applied to the nav link, then I could successfully target it with a css # selector.
