### ISSUE TITLE
Grid and multiline tables not working in 2.11.3.2 (pdf)

### ISSUE THREAD

**Issue by gnpan** [jgm/pandoc#7002]
Just updated to pandoc version 2.11.3.2 and any grid or multiline tables give an error producing PDF. Simple or pipe tables are OK. 
MWE:
File test.txt:
```
-------------------------------------------------------------
 Centered   Default           Right Left
  Header    Aligned         Aligned Aligned
----------- ------- --------------- -------------------------
   First    row                12.0 Example of a row that
                                    spans multiple lines.

  Second    row                 5.0 Here's another one. Note
                                    the blank line between
                                    rows.
-------------------------------------------------------------

Table: Here's the caption. It, too, may span
multiple lines.

```
Command:
```
pandoc -o test.pdf test.txt
```
Result:
```
Error producing PDF.
! Undefined control sequence.
<argument> @{} >{\centering \arraybackslash 
                                            }p{(\columnwidth - 6\tabcolsep )...
l.70 ...umnwidth - 6\tabcolsep) * \real{0.36}}@{}}
```

**Comment by tarleb** [comment]
I cannot reproduce this. Could you be using a custom LaTeX template unintentionally? If so, please try adding `\usepackage{array}` to the preamble.

**Comment by gnpan** [comment]
Ah yes, although I was not calling a custom template, there was an old default.latex file lurking in my .pandoc folder, so I assume it was picking this up. I deleted it and all is well.
Thanks!

**Comment by mirh** [comment]
See https://github.com/ismayc/thesisdown/issues/122#issuecomment-771855855 for the precise culprit

**Comment by neuged** [comment]
Combining the link provided by @mirh and the comment by @tarleb (thank you both!)  I needed to add `array` as well as `calc` to my template, to make grid tables work as before, e.g.:

```latex
\usepackage{array,calc}
```
