### ISSUE TITLE
LaTeX reader gets confused by filecontents environment

### ISSUE THREAD

**Issue by dbitouze** [jgm/pandoc#7003]
# Context
- `pandoc` 2.11.3.2
- Compiled with `pandoc-types` 1.22, `texmath` 0.12.1, `skylighting` 0.10.2, `citeproc` 0.3.0.3, `ipynb` 0.1.0.1

# Bug
The following `test.tex`, when compiled with `(pdf)latex` outputs two listings.

```latex
\documentclass{article}
\usepackage{listings}

\lstset{basicstyle=\ttfamily}

\begin{filecontents*}[overwrite]{example.tex}
\documentclass{article}
\begin{document}
\section{Bar}
This a Bar section
\end{document}
\end{filecontents*}

\begin{document}

\section{With lstlisting environment}

\begin{lstlisting}
\documentclass{article}
\begin{document}
\section{Foo}
This a Foo section
\end{document}
\end{lstlisting}

\section{With lstinputlisting command}

\lstinputlisting{example.tex}
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/103483545-40cf2200-4de8-11eb-9b82-8779044e8396.png)

But with:

`pandoc -o test.rst test.tex --listings`

the resulting `test.rst` file ignores the first listing and interprets the second one:

```rst
Bar
===

This a Bar section
```

**Comment by jgm** [comment]
Let's try to break this down to something simpler.
```
 % pandoc -f latex -t rst -s
\begin{lstlisting}
\documentclass{article}
\begin{document}
\section{Foo}
This a Foo section
\end{document}
\end{lstlisting}
^D
::

   \documentclass{article}
   \begin{document}
   \section{Foo}
   This a Foo section
   \end{document}
```
So pandoc seems to correctly translate a lstlisting environment to rst.
The other also seems to work:
```
% pandoc -f latex -t rst -s
\lstinputlisting{example.tex}
.. code:: latex

   \documentclass{article}
   \begin{document}
   \section{Foo}
   This a Foo section
   \end{document}
```

Removing the `filecontents` environment makes your sample work.  So that seems to be interfering somehow.

Note: `--listings` only affects the LaTeX writer, not the reader.

**Comment by jgm** [comment]
The issue is this:  the latex reader doesn't currently know anything about the `filecontents` environment, and it gets confused because it tries to parse the contents and finds the `\end{document}` (I'm guessing).  Solution would be to implement `filecontents` somehow (perhaps we can store the contents in state for use in include statements later in the code).  As a workaround, you can remove the filecontents environment or temporarily redefine it as a no-op.

**Comment by dbitouze** [comment]
>Let's try to break this down to something simpler.
> [...]

Okay.

> The other also seems to work:
> 
> ```
> % pandoc -f latex -t rst -s
> \lstinputlisting{example.tex}
> .. code:: latex
> 
>    \documentclass{article}
>    \begin{document}
>    \section{Foo}
>    This a Foo section
>    \end{document}
> ```

Strange, I don't observe this:

```bash
$ echo "\documentclass{article}
\begin{document}
\section{Foo}
This a Foo section
\end{document}" > example.tex
$ pandoc -f latex -t rst -s <<< "\lstinputlisting{example.tex}"
[WARNING] Could not load include file 'example.tex' at line 1 column 17
.. code:: latex
```

**Comment by dbitouze** [comment]
> The issue is this: the latex reader doesn't currently know anything about the `filecontents` environment, and it gets confused because it tries to parse the contents and finds the `\end{document}` (I'm guessing).

Okay. 

Since `pandoc` is not troubled by `\end{document}` in the `lstlisting` environment, I guess it should be possible to make the `filecontents` environment happy with it as well. It would be very welcome, especially now that `filecontents` is in the LaTeX kernel. The same could happen with the `fancyvrb`'s `VerbatimOut` environment which behaves similarly.

> Solution would be to implement `filecontents` somehow (perhaps we can store the contents in state for use in include statements later in the code).

Would be nice!

> As a workaround, you can remove the filecontents environment
Unfortunately necessary in my use case.

>  or temporarily redefine it as a no-op.

Sorry, I don't see what you mean here: do you mean at the `pandoc` level (with a filter?)?

**Comment by jgm** [comment]
I mean that, before converting the document, you could add a redefinition of the `filecontents*` environment to a no-op; pandoc will interpret the renewenvironment and this will cause it to ignore this instead of getting confused.

**Comment by dbitouze** [comment]
> I mean that, before converting the document, you could add a redefinition of the `filecontents*` environment to a no-op; pandoc will interpret the renewenvironment and this will cause it to ignore this instead of getting confused.

Well, not very handy in my use case, since I'd have to manage about a thousand files that, at the beginning of the workflow, need the normal definition of `filecontents*` (and/or `VerbatimOut`) environment.

BTW, have you an idea about:
```bash
$ pandoc -f latex -t rst -s <<< "\lstinputlisting{example.tex}"
[WARNING] Could not load include file 'example.tex' at line 1 column 17
.. code:: latex
```

**Comment by jgm** [comment]
All I can say is that `\lstinputlisting` works fine for me. I don't know why it didn't work for you.

**Comment by jgm** [comment]
OK, filecontents is now supported!

**Comment by dbitouze** [comment]
Many thanks! 

And sorry for this but: would it be possible to extend this feature to the `VerbatimOut` environment provided by the `fancyvrb` package?

**Comment by jgm** [comment]
If you're using `VerbatimOut` because you actually want to create a file, note that pandoc won't do that.  The contents are just stored internally.  If you're using it to do the same thing `filecontents` does, then you should be able to work around this by adding

```
\renewenvironment{VerbatimOut}{filecontents}
```
to the beginning of the body.  If that's sufficient, we could also change pandoc so it treats `VerbatimOut` just like `filecontents`.
