### ISSUE TITLE
Option to enable Babel's shorthand

### ISSUE THREAD

**Issue by SG-phimeca** [jgm/pandoc#7004]
Babel shorthands are disabled in the latex default template in order to avoid some side-effects.
I would rather deal with those side-effects than change the way I input punctuation (I write in French).
Would it be possible to add an option for re-enabling babel shorthands?

The new way of diabling shorthands (#6817) makes it harder to re-enable it with a monkey patch without using a custom template.

pandoc 2.11.3.2
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1

**Comment by jgm** [comment]
Probably this is a wont-fix, but perhaps @lygamac has some ideas about how we might make this easier for you.

**Comment by lygamac** [comment]
Maybe adding
```
\let\languageshorthands\LanguageShortHands
```
to your header file might help. This undoes the redefinition. As no extra option are passed in babel package, `shorthands` are enabled by default.

**Comment by SG-phimeca** [comment]
Thanks for the suggestion @lygamac. Unfortunately the code in the header is inserted *before* the paragraph that disable the shorthands, namely:
    
    % get rid of language-specific shorthands (see #6817):
     \let\LanguageShortHands\languageshorthands
     \def\languageshorthands#1{}

This is what I meant by “The new way of diabling shorthands (#6817) makes it harder to re-enable it”

**Comment by lygamac** [comment]
Try
```
\AtBeginDocument{\let\languageshorthands\LanguageShortHands}
```

**Comment by SG-phimeca** [comment]
Nice, it works. I did not knew about \AtBeginDocument

**Comment by jgm** [comment]
I'll close this. Good workaround!
