### ISSUE TITLE
Request: default defaults file

### ISSUE THREAD

**Issue by cysouw** [jgm/pandoc#7007]
The possibility to have defaults-files makes Pandoc-life so much better, IMO! However, it might be even better if there would be a default for this option. Alike to the option `--write`, which defaults to `--write=html`. I would suggest that `--defaults` has a default execution of `--defaults=defaults.yaml`.

This would mean that when I put a file `defaults.yaml` in a place that Pandoc can find (typically in the same director as my md-files), then I can run Pandoc with only the command `pandoc`, nothing else needed!

The effect would be a bit like `make` that executes a `Makefile`...

Is this an obvious idea, or am I missing some security/usage problem?

**Comment by jgm** [comment]
I'm not keen on the idea, because it would change the behavior of `pandoc` in a way that could quite possibly break lots of existing workflows.  I'd prefer to keep requiring defaults explicitly; that makes it really clear from the command line what the inputs are.
