### ISSUE TITLE
Markdown to Docx, table's first row, the columns's valign is bottom

### ISSUE THREAD

**Issue by Gowa2017** [jgm/pandoc#7008]
pandoc -v
pandoc 2.11.3.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.2,
citeproc 0.3.0.1, ipynb 0.1.0.1
User data directory: /Users/me/.local/share/pandoc or /Users/me/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

Source md file is:
```
| 测试                                                     | 测试结果 |
| ------------------------------------------------------------ | ---- |
| !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd| 通过 |

```

convert command:
```
pandoc -f markdown -t docx -o 1.docx 1.md
```

Output is:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/33367355/103857486-914cc500-50f1-11eb-9463-af6a26bdaf2c.png">

My custom reference.docx defined a table style named 'Table', the table in output docx xml code is:

```
_TableStyle('Table') id: 4522813232
<w:tbl xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
  <w:tblPr>
    <w:tblStyle w:val="Table"/>
    <w:tblW w:type="pct" w:w="5000.0"/>
    <w:tblLook w:firstRow="1" w:lastRow="0" w:firstColumn="0" w:lastColumn="0" w:noHBand="0" w:noVBand="0"/>
  </w:tblPr>
  <w:tblGrid>
    <w:gridCol w:w="7425"/>
    <w:gridCol w:w="495"/>
  </w:tblGrid>
  <w:tr>
    <w:trPr>
      <w:cnfStyle w:firstRow="1"/>
    </w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcBorders>
          <w:bottom w:val="single"/>
        </w:tcBorders>
        <w:vAlign w:val="bottom"/>
      </w:tcPr>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Compact"/>
          <w:jc w:val="left"/>
        </w:pPr>
        <w:r>
          <w:t xml:space="preserve">测试</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcBorders>
          <w:bottom w:val="single"/>
        </w:tcBorders>
        <w:vAlign w:val="bottom"/>
      </w:tcPr>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Compact"/>
          <w:jc w:val="left"/>
        </w:pPr>
        <w:r>
          <w:t xml:space="preserve">测试结果</w:t>
        </w:r>
      </w:p>
    </w:tc>
  </w:tr>
  <w:tr>
    <w:tc>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Compact"/>
          <w:jc w:val="left"/>
        </w:pPr>
        <w:r>
          <w:t xml:space="preserve">!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!dafdafdfadfadfadafd</w:t>
        </w:r>
      </w:p>
    </w:tc>
    <w:tc>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Compact"/>
          <w:jc w:val="left"/>
        </w:pPr>
        <w:r>
          <w:t xml:space="preserve">通过</w:t>
        </w:r>
      </w:p>
    </w:tc>
  </w:tr>
</w:tbl>
```

So, where the `      <w:tcPr>
        <w:tcBorders>
          <w:bottom w:val="single"/>
        </w:tcBorders>
        <w:vAlign w:val="bottom"/>
      </w:tcPr>` come from.

**Comment by jgm** [comment]
docx writer, line 1029:
``` haskell
  let borderProps = Elem $ mknode "w:tcPr" []
                    [ mknode "w:tcBorders" []
                      $ mknode "w:bottom" [("w:val","single")] ()
                    , mknode "w:vAlign" [("w:val","bottom")] () ]
```
I checked with git blame, and this has been there since 2012 when the docx writer was first added.  Would `top` alignment be a better default?  Or maybe we can omit w:vAlign altogether and let this be controlled by style?

**Comment by agusmba** [comment]
> Or maybe we can omit w:vAlign altogether and let this be controlled by style?

If this works, I always prefer being able to tweak things with styles (just my 2c).

**Comment by Gowa2017** [comment]
I prefer to it controled by style.

**Comment by jgm** [comment]
I don't know if it will work; we will have to test.

**Comment by jgm** [comment]
OK, now looking at the code a bit more, I see that this attribute is only put on header rows of the table.  The idea is that you'd typically want these to be bottom-aligned rather than top-aligned.  The attribute is not put on other rows of the table.

We could perhaps instead attach a style which could then be changed.  But we need some kind of hook here because this only applies to header rows, not to every cell of the table.

**Comment by agusmba** [comment]
> We could perhaps instead attach a style which could then be changed. 

Wouldn't header rows be styleable via our regular *Table* style?

![image](https://user-images.githubusercontent.com/3104020/103984628-c0157a80-5187-11eb-8919-001fd7ec34bb.png)

**Comment by agusmba** [comment]
Possibly a simmilar thing happens with the black horizontal row below the header. It's hardcoded in pandoc, so if you have a different hrow in your style, it is lost, unless you manually select your table in Word and re-apply the *Table* style.

Ideally these defaults should go into the default *Table* style instead of being hardcoded.

**Comment by jgm** [comment]
Agreed about putting these things in the style.  I took a quick look, but it's complicated figuring out how the table styling works.  If someone else wants to take this on, go ahead!

**Comment by Gowa2017** [comment]
According to the [openofficexml document.](http://officeopenxml.com/WPstyleTableStylesCond.php)This is a table style named  `Conditional Formatting`, we can use it to format different region of a table. Like a tables's 

- band1Horz - The formatting applies to odd numbered groupings of rows
- band1Vert - The formatting applies to odd numbered groupings of columns
- band2Horz - The formatting applies to even numbered groupings of rows
- band2Vert - The formatting applies to even numbered groupings of columns
- firstCol - The formatting applies to the first column
- firstRow - The formatting applies to the first row
- lastCol - The formatting applies to the last column
- lastRow - The formatting applies to the last row
- neCell - The formatting applies to the top right cell
- nwCell - The formatting applies to the top left cell
- seCell - The formatting applies to the bottom right cell
- swCell - The formatting applies to the bottom left cell
- wholeTable - The formatting applies to the whole table

So, In MS Word, we can custom a table style, and define some conditional format,to this issue, we define a style apply to `Header row`, that's all.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/33367355/104125687-549ff880-5393-11eb-8414-2f05d2474e5f.png">

**Comment by jgm** [comment]
> we define a style apply to Header row, that's all.

What kind of style, though?  That wasn't immediately evident to me.  Currently in the docx writer we deal with `pStyle` and `rStyle`, but neither seems appropriate for a header row?

**Comment by jgm** [comment]
Oh, I guess the style applies to the whole table.
``` xml

<w:tbl>
<w:tblPr>
<w:tblStyle w:val="TestTableStyle"/>
</w:tblPr>
</w:tbl>
```

**Comment by jgm** [comment]
So, if I'm understanding correctly, we would need something like a `TableWithHeader` style that inherits from `Table` and adds some conditional formatting for the first column.

I'm still a bit reluctant to take this approach, because I'm not sure how well it would generalize to the new table features, which allow: (a) column headers, (b) multiple table bodies, each with its own header.

**Comment by Gowa2017** [comment]
> > we define a style apply to Header row, that's all.
> 
> What kind of style, though? That wasn't immediately evident to me. Currently in the docx writer we deal with `pStyle` and `rStyle`, but neither seems appropriate for a header row?

Like this:

```xml
<w:tblStylePr w:type="firstRow">
<w:rPr>
<w:b/>
</w:rPr>
<w:tcPr>
<w:shd w:val="clear" w:color="auto" w:fill="ED1C24"/>
</w:tcPr>
</w:tblStylePr>
```

This is a  conditional formatting style only apply to the tables's firstrow.

**Comment by agusmba** [comment]
> So, if I'm understanding correctly, we would need something like a TableWithHeader style that inherits from Table and adds some conditional formatting for the first column.

I would implement pandoc's default table styling within the already used "Table" style, trying to keep it simple.
For instance I don't believe pandoc currently styles the first column, etc.
IIRC, we would only need to style the header row (bold text, draw the bottom border) and the whole table (for top and bottom border).

Then each user can further tweak the "Table" style to suit their needs.

As a heads up, we will run into another issue, which is good since it means we are taking forward steps: In  https://github.com/jgm/pandoc/issues/3275#issuecomment-448262352 we see that first and last columns are always selected by docx generated by pandoc. Since this is not always desired, until we can indicate this in source markdown, pandoc's *default* Table shouldn't style the first and last columns. But this is a discussion for the future after this one is implemented.

**Comment by jgm** [comment]
> IIRC, we would only need to style the header row (bold text, draw the bottom border) and the whole table (for top and bottom border).

Right, but how do you know whether the first row is a header or just a regular row?  Not all pandoc tables have headers.  We would need to draw this distinction with a distinct Style, it seems to me.

The same applies to column headers (not currently implemented but on the todo list):  how do you know whether the first cell in each row is a header cell?

Bottom line is that conditional formatting can't make these distinctions.  If we use conditional formatting as suggested, then we have to make ALL of these distinctions in the styles. And then you're talking about styles like TableWithHeaderAndTwoCellsRowHeaders.  I don't think the multiple table bodies case (with intermediate headers) could be handled at all this way.

**Comment by jgm** [comment]
> As a heads up, we will run into another issue, which is good since it means we are taking forward steps: In #3275 (comment) we see that first and last columns are always selected by docx generated by pandoc. Since this is not always desired, until we can indicate this in source markdown, pandoc's default Table shouldn't style the first and last columns.

That sounds like an orthogonal issue. If you can suggest a specific revision to the current styles, please submit a PR.

**Comment by agusmba** [comment]
> Right, but how do you know whether the first row is a header or just a regular row? Not all pandoc tables have headers. We would need to draw this distinction with a distinct Style, it seems to me.

I'm thinking about a first iteration where we keep pandoc's current functionality, except changing the hardcoded styling for docx tables and implementing them in the *Table* style (I'm not sure calling it conditional is accurate).

Therefore, if pandoc's AST can currently know whether the first row is a header or just a regular row, the new approach would know also, wouldn't it?

The *Table* style can define extra styling for when the table is marked as having a first row (that doesn't mean it will be applied always). I think currently all tables are marked as having a first row. If we want to correctly support headerless tables, we would need to mark the docx table as being headerless. (See this link for a couple of possible ways of doing it: https://stackoverflow.com/a/23299762)

**Comment by jgm** [comment]
Oh, nice, I didn't know about this.  For reference, here's the relevant part of the spec.

<img width="779" alt="Screen Shot 2021-01-12 at 9 02 25 AM" src="https://user-images.githubusercontent.com/3044/104347018-f834fa00-54b4-11eb-8f70-2f5bf7e52bdb.png">

**Comment by jgm** [comment]
Now looking at the writer, I see that we DO set the firstRow attribute in tblLook.  Since we're targeting compatibility with Word 2007, this is probably a mistake; we should presumably use val instead with the hex code?  But oddly I've never seen this rejected as invalid.

**Comment by jgm** [comment]
Also worth considering https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_cnfStyle_topic_ID0E6YMQ.html which looks like it might give a way to apply these conditional formatting properties to arbitrary cells of the table?

**Comment by jgm** [comment]
OK, I made this change, please test!

**Comment by jgm** [comment]
To be explicit, the header row is still bottom-aligned by default, but you can now change that in the style; it is no longer hard-coded.

**Comment by agusmba** [comment]
Just tested the [nighly build](https://github.com/jgm/pandoc/actions/runs/482261870) and it seems to work beatifully.
I haven't tested it thoroughly, but the issue I had with the hardcoded line below the header row is gone, so Thanks!!!

See before (hardcoded black line):
![image](https://user-images.githubusercontent.com/3104020/104436896-71545000-558e-11eb-8474-1c7703916597.png)

And now (blue line in the Table style):
![image](https://user-images.githubusercontent.com/3104020/104436959-8630e380-558e-11eb-857c-3eb509de31be.png)

@Gowa2017 could you test your issue tweaking your *Table* style and see if it works?
