### ISSUE TITLE
Problem with cyrillic alphabet

### ISSUE THREAD

**Issue by cinomen** [jgm/pandoc#7010]
Hello,
this is my first post in this repository. Pandoc is very useful software, but i would like to report a fault in
its behaviour. It can not operate with files names, written in cyrillic alphabet - copying, saving or converting such files.
Is there any work-around in this direction ?
Thanks in advance.

**Comment by tarleb** [comment]
Hi @cinomen, please help us by providing additional information:
- What's the shortest command we could use to reproduce the issue?
- Which operating system are you using?
- What's the output of `pandoc --version`?
- If you are on mac or Linux, please report the output of `locale`.

**Comment by cinomen** [comment]
Hello, it is my fault. 
The problem wasn't because of cyrillic alphabet. It concerns files names, consisted of more than 1 word, separated by interval.
Pandoc 1.19.2.1: 
For example see below:
pandoc чан он.epub -o сон году.fb2
pandoc: чан: openBinaryFile: does not exist (No such file or directory)

So, i suggest pandoc only handles single files names ?

**Comment by mb21** [comment]
If your filename has spaces in it you need to use the quoting mechanism of your shell, e.g. `"file name"`.
