### ISSUE TITLE
Asciidoc does not generate table of contents

### ISSUE THREAD

**Issue by timo-a** [jgm/pandoc#7011]
The asciidoc template has a variable `toc` but the output does not show a table of contents.
I believe this is a regression as it is mentioned as working here: https://matthewsetter.com/convert-markdown-to-asciidoc-withpandoc/  
input.md
```
# h1

## h2.a

foo

## h2.b

ba
```

commands I tried
```
pandoc -f markdown -t asciidoc --template=default -V toc input.md
pandoc --toc -s -f markdown -t asciidoc input.md
pandoc --toc -s -f markdown -t asciidoc --template=default input.md
```

actual output:
```
== h1

=== h2.a

foo

=== h2.b

ba
```

expected: `:toc:` ~as first line~ under the first headline.

**Comment by jgm** [comment]
In the default asciidoc template, the part that includes `toc` is included in a big `if(titleblock)`, which only gets triggered if we have an asciidoc title block.

Whoever wrote this (possibly me) did so in the belief that `:toc:` only works with a title block.  Is this false?  (Also need to check with both asciidoc and asciidoctor)

**Comment by timo-a** [comment]
The problem described above is for both asciidoc and asciidoctor. In the following I will use asciidoc(tor) to talk about both of them. 

Oh, I guess I didn't look closely enough at the templates,

`pandoc -f markdown -t asciidoc(tor) --template=default -V titleblock -V toc input.md`

does produce:

```
= 
:toc:

== h1

=== h2.a

foo

=== h2.b

ba
```

But I don't think this is very intuitive. `:toc:` and other attributes can only exist in a titleblock, so as a user I don't expect that I have to specify `titleblock` as well. By specifying `:toc:` or `:author:`, ... my intentions are clear and pandoc should simply generate the titleblock as well. Moreover, from a user perspective I see no point in a `titleblock` variable at all, as I only need a titleblock when I want it to hold a `title` or other attributes.

If it is not technically possible to go without `titleblock`, I would appreciate at least a `Variables for Asciidoc(tor)` section under https://pandoc.org/MANUAL.html#templates to manage expectations.

(The titleblock seems to be the same for asciidoc and asciidoctor: a level 0 headline followed by attributes followed by a blank line)

**Comment by jgm** [comment]
You don't have to specify `-Vtitleblock`.  If you provide a title/author, it will be set automatically.

**Comment by timo-a** [comment]
I cannot reproduce this with `pandoc 2.11.3.2`. For input2.md:
```
content
```
With `-Vtitleblock` (same for `asciidoc`):
```
$ pandoc -f markdown -t asciidoctor --template=default -Vtitleblock -Vtitle=mytitle -Vauthor=me input2.md
= mytitle
me

content
```
but without `-Vtitleblock`:
```
$ pandoc -f markdown -t asciidoctor --template=default -Vtitle=mytitle -Vauthor=me input2.md
content
```

(Same results with `-t asciidoc`, same results with just one of title, author)

**Comment by jgm** [comment]
You need the title in the metadata. Setting the variable isn't enough.  The writer determines whether there is a title block from the metadata and constructs the title block accordingly.

**Comment by timo-a** [comment]
`pandoc -f markdown -t asciidoctor --template=default -Vtitle=mytitle -Mauthor=me input2.md` works indeed, Thank you!
