### ISSUE TITLE
Fix JATS citations and references

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#7016]
Pandoc contains a special jats.csl to create properly formatted JATS references via pandoc-citeproc. This is no longer supported, and citations are misformatted.

The old method produced [`<element-citation>`](https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/element-citation.html), so styling and presentation of citations was left to the JATS reader. It would be great if we could produce [`<mixed-citation>`](https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/mixed-citation.html) elements, as element order and punctuation can be taken from the CSL. I suspect that simple mixed-citation elements are also very easy to produce.

I'd also like to look into tagging the components of a `<mixed-citation>`, but I think I need help to get started. If I understand correctly, then a good first step would be to define a new type and provide a `CiteprocOutput` instance. Is that correct? I guess we'd still have to find a way to integrate that in pandoc's processing pipeline.

**Comment by jgm** [comment]
Could you say more about the problem?  If it's a problem with citeproc, it could perhaps be fixed there.

**Comment by jgm** [comment]
Can you give an example of the sort of output you'd like to produce?

**Comment by tarleb** [comment]
The issue is that pandoc-citeproc supported a mechanism that allowed the generation of raw JATS XML via a CSL style file. We still have `data/jats.csl` for this, and it is still used as the default when producing JATS. As a result, citations look like this:

    <xref alt="{{jats}}&lt;xref ref-type=&quot;bibr&quot; rid=&quot;{{/jats}}{{jats}}ref-{{/jats}}1{{jats}}&quot;&gt;{{/jats}}1{{jats}}&lt;/xref&gt;{{/jats}}" rid="ref-Upper_writers_1974">{{jats}}&lt;xref
  ref-type=&quot;bibr&quot;
  rid=&quot;{{/jats}}{{jats}}ref-{{/jats}}1{{jats}}&quot;&gt;{{/jats}}1{{jats}}&lt;/xref&gt;{{/jats}}</xref>

The references section used to look nice, but I think in-text citations never fully worked in JATS; I wrote some fairly complex hacks to get good results with pandoc-scholar, and always wanted to port some of the mechanics back into pandoc. I just didn't get around to it.

I don't think this needs fixing in citeproc, but in the writer. I'll see if I can get back basic support, i.e. citations that are nicely formatted but not tagged otherwise. Tagging will be more interesting, and I'll probably need help there.

This website gives good examples of what I'd like pandoc to produce eventually: https://www.mulberrytech.com/JATS/JATS-Cites-Samples.html

**Comment by jgm** [comment]
OK, this is a bit complex. I do think some intervention on the citeproc side will be needed.

In pandoc-citeproc we implemented a hackish fix that allowed you to put `{{jats}}XYZ{{/jats}}` in a prefix or suffix and it would be emitted as raw JATS.  This allowed you to emit XML tags.  For the code that does this, see (in pandoc-citeproc) Text.CSL.Eval.Output, pRaw.

I never really liked this, but it worked.  I guess I didn't port this over to citeproc.  I could probably do that, but I like the idea of finding a cleaner solution.

However, defining a CiteprocOutput instance won't be sufficient. One option would be to add a top-level function to Citeproc that return the raw Output structure instead of rendering it. This structure includes some Tag elements, which will tell you the type and id of the citation, which parts are names (and what the corresponding Name structure is), what parts are dates (and what the corresponding Date structure is), what name lists are author, editor, etc., and what is a locator.  That would give you a bit more information for tagging. It may not be enough, though.  It doesn't tell you which parts of the formatted name correspond to the surname and given name, for example.   It doesn't distinguish volume and issue. Etc.

On the other hand, if JATS will just accept a big untagged string, that should be easy, and in that case you could use any unmodified style with JATS.  It should be easy, too, to find things like DOIs (which will be links) and give them special treatment.

**Comment by tarleb** [comment]
> On the other hand, if JATS will just accept a big untagged string, that should be easy, and in that case you could use any unmodified style with JATS.

I created #7018 for this, it tackles the primary objective of creating valid JATS.

My secondary goal is to produce output which renders well in the [eLife Lens reader](https://lens.elifesciences.org/). I had assumed that `<mixed-citation>` would render well, but that's not generally the case. However, `<element-citation>` works. For me, it would be great to have a function `Pandoc -> [Reference]` available in Lua, then the rest could happen in a filter. But maybe we could turn is into an extension for JATS?

**Comment by jgm** [comment]
> it would be great to have a function `Pandoc -> [Reference]` available in Lua

I'll see if I can provide this.

**Comment by jgm** [comment]
I think making it a JATS extension probably makes sense.

**Comment by jgm** [comment]
The one slightly awkward thing about making it a jats extension is that we currently *always* parse `element-citation` in the jats reader. Should that be changed so that it is just ignored if the extension is not set?  That seems a bit strange, but maybe.  What would the default setting of the extension be, on or off?

**Comment by jgm** [comment]
By the way, you now have the function you need, `getReferences`, from T.P.Citeproc.
You can safely pass in Nothing for the locale parameter.

**Comment by tarleb** [comment]
Fixed.

**Comment by gabestein** [comment]
Hello - we're trying to follow this chain over at PubPub, where a legacy import has given us lots of papers with raw text citations (e.g., `Doe, Jane, "Title," 2017`) that we need to represent in a JATS `mixed-element` field. The old `{{jats}}` workaround seems like it would have worked for us.

Is there another way to accomplish the same with the fix implemented in #7018? We're having a tiny bit of trouble following how it was implemented if so.

**Comment by tarleb** [comment]
Not sure I fully understand: could you post a tiny example document and command you are using?

It should be possible to get the desired output by putting the whole citation string into the `title` of a reference item, but I might misunderstand the details here.

**Comment by gabestein** [comment]
Thank you, that works great.

But, with my apologies for switching gears, now I'm wondering why that doesn't produce an `article-title` element in JATS, which is what we had assumed would happen if we overloaded a field. In cases where we do have structured citation information from the user, it seems it would be best to produce JATS citations with semantic tags, which is what we used to see prior to a recent upgrade to pandoc 2.14.2. Is the ability to create structured citations in JATS from, e.g., CSL-JSON, no longer available?

**Comment by tarleb** [comment]
Great, thanks.

As it currently stands pandoc can produce either mixed-citations that follow the selected CSL but are not semantically tagged, or element citations when called with `-t jats+element_citations`. Having both, CSL and semantic tagging, would currently require postprocessing with XSLT or similar.

**Comment by gabestein** [comment]
Thanks, that makes sense. I think that means we'll basically have to look and see if any of the citations in a document are raw text, and if so, use `-t jats` across the document. If all are bibtex, we'll use `-t jats+element_citations`.

**Comment by tarleb** [comment]
We should be moving this discussion to the [pandoc-discuss mailing list](https://groups.google.com/forum/#!forum/pandoc-discuss)

There might be a simpler way, but you could copy all plaintext citations in a `bare-refs` metadata field and then use a filter to post-process the result of `--citeproc`. Assuming you can pass in metadata which looks like this

``` yaml
---
references:
- id: foo
  title: this will be replaced
# map from reference IDs to the plaintext citation
bare-refs:
  foo: Citation that will show up in the output
---
```

you could then use a Lua filter to fix the citations.

``` lua
local stringify = pandoc.utils.stringify

function get_bare_refs (meta)
  bare_refs = meta['bare-refs']
end

function replace_bare_citations (refs)
  -- only act on div containing the bibliography
  if refs.identifier ~= 'refs' then return nil end

  for i, refdiv in ipairs(refs.content) do
    local id = refdiv.identifier:gsub('^ref%-', '')
    -- find bare reference entry for this reference
    local bare = bare_refs and bare_refs[id]
    if bare then
      refdiv.content = {pandoc.Para(bare)}
    end
  end
  return refs
end

return {
  {Meta = get_bare_refs},
  {Div = replace_bare_citations},
}
```

But let's move this to the list or to a new issue.

**Comment by gabestein** [comment]
Thanks very much. We'll take a look, and if we need to discuss further, I'll start a new list thread.

**Comment by fredguth** [comment]
Is it possible to produce `<mixed-citation>` and `<elements-citation>` together?
Scielo xml format uses that.
