### ISSUE TITLE
Headline levels are mapped impractically to Asciidoc

### ISSUE THREAD

**Issue by timo-a** [jgm/pandoc#7017]
Headlines in Markdown and HTML start at level 1: `#^L`, `<hL>`  
In Asciidoc they start at level 0: `=^(L+1)`  and Pandoc translates level `L` to `L` reserving level 0 for the document header generated by the `titleblock` variable.
This is causing me some trouble because I want to translate a number of markdown documents to asciidoctor and the headlines are all "downgraded" and topped with a new level 0 headline.

input:
```
# My headline

content
```

command:
```
pandoc -f markdown -t asciidoctor --template=default (-V titleblock) -V toc  inputHeadlineMapping.md
```
(I don't want to create a titleblock but as of now it is the only way to have `:toc:` written out)

The expected output would be:
```
= My headline
:toc:

content
```
The highest possible markdown headline (level 1) is translated to the highest possible asciidoctor headline (level 0) and the attributes are put under it.

The actual output however is:
```
= 
:toc:

== My headline

content
```
A level 0 headline is created as part of the document header (I could specify a title with `-Vtitle="new title"`, in fact for proper rendering I have to provide a title for the generated level 0 stub) and the attributes are put under there. The existing headlines are not downgraded because of `-V titleblock`! Without it, the headlines would still be translated from level `L` to `L`, the first two lines would simply not be there.

Weirdly, I cannot fix the headline levels with a filter, asciidoc writer seems to just start at level 1 anyway.  

I think that there is nothing special about asciidoc(tor)'s level 0 heading and that 
- a native `Header 1` should just be written out as an asciidoc(tor) level 0 header
- header variables such as `toc`, `title`, `author` should be written under a user provided header (of asciidoc level 0) if one exists.

**Comment by jgm** [comment]
My understanding is that the standard practice for asciidoc is to have the title in a level-1 heading, and top-level sections level-2.  In a Pandoc document, the title is represented by title in metadata, and level-1 headings are top-level sections.  So the current behavior is, I believe, a good one, and it has been pandoc's behavior for a long time, so changing now would probably cause many complaints.

In your case you lack a `title` in metadata, but you're manually enabling the `titleblock` template variable (*not recommended* -- that variable is set automatically by the writer when appropriate).  That is why you're getting strange output.

**Comment by timo-a** [comment]
I have found a way to fix the headline levels to my liking in a second pass with sed, but for the record I would not complain if the asciidoc writer's behaviour was changed so that markdown '#' becomes '='.
Also I would like to point out that the asciidoctor binary when converting asciidoc to html, translates ```==``` into `<h2>`¹, whereas pandoc currently translates `<h2>` into `===`.


¹https://asciidoctor.org/docs/asciidoc-writers-guide/#section-titles the info box

**Comment by jgm** [comment]
> whereas pandoc currently translates `<h2>` into `===`.

You can work around that by using `--shift-heading-level-by=-1` when conventing from HTML.
