### ISSUE TITLE
HTML reader duplicates author

### ISSUE THREAD

**Issue by praffeck** [jgm/pandoc#7020]
Unlike `<h1 class="title">`, `<p class="author">` is not ignored by the HTML reader, leading to potential duplicates.
Consider the following example input:
```
---
author: Author Name
title: Title
---

Section 1
=========

Some content.
```
Executing `cat input | pandoc -s -f markdown -t html | pandoc -s -f html -t markdown` yields:
```
---
author: Author Name
generator: pandoc
title: Title
viewport: width=device-width, initial-scale=1.0, user-scalable=yes
---

Author Name

# Section 1

Some content.
```

I'd expect the HTML reader to ignore `class="author"` in the same way as `class="title"`.

Pandoc version:
```
pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2, citeproc 0.3.0.3, ipynb 0.1.0.1
```

**Comment by tarleb** [comment]
A change was just pushed which will keep both the title and header, so I think this issue no longer applies in its current form.

How about we modify the reader to parse `<header>` as a `Div`? Then one could use a filter to remove it, matching on its `id`.

**Comment by tarleb** [comment]
I pushed 0794862aacdb5d28616dadc3d681a63c36251212 which implements the change of treating `<header>` elements like `<div>` elements. You now can use the following Lua filter to remove the full pandoc-generated header block.

```lua
function Div (div)
  return div.identifier == 'title-block-header' and {} or nil
end
```
