### ISSUE TITLE
Western fonts cannot be changed in the output docx

### ISSUE THREAD

**Issue by TomBener** [jgm/pandoc#7022]
I use Pandoc 2.11.3.2 on macOS 11.1.

When the `lang` is set as `zh-CN` in yaml block:

```yaml
lang: zh-CN
```

Then run the command:

```sh
$ pandoc -C input.md -o main.docx 
```
The western fonts in the output `main.docx` is the same as the Chinese fonts `宋体` like the screen below. In addition, it seems the western fonts are frozen which can’t be changed, although the default fonts in the template of Pandoc for western fonts are `Calibri` and `Cambria`.

![CleanShot 2021-01-12 at 15 02 06@2x](https://user-images.githubusercontent.com/49151155/104281247-2f70ce80-54e8-11eb-93c0-e5f7f9424488.png)

If the `lang: zh-CN` is removed, the issue will disappear, but some other problems emerge. For example, the Chinese quotation marks `“”` and `‘’` are set as western fonts, which should be avoided.

So I'd like the western fonts are with different fonts from Chinese fonts `宋体`. Is it possible when `lang: zh-CN` is added or other solutions? Thank you!

**Comment by jgm** [comment]
I don't know. To my knowledge, we don't do anything to change the font depending on the `lang`.
You might have a look at `data/docx/word/styles.xml` in this repository and let us know if anything there seems wrong.

**Comment by TomBener** [comment]
After nearly 18 months, I’ve tried to look into this issue again. Sorry for the long time…

---

With the option `--metadata lang=zh-CN`, i.e. `pandoc main.md -o main.docx --metadata lang=zh-CN`, there will be two changes in the output document compared to the default command `pandoc main.md -o main.docx`.

1. The property `w:val` for [specifying Latin Languages](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.languages?view=openxml-2.8.1#properties) were changed from `en-US` to `zh-CN` in `word/styles.xml`.
2. `<dc:language>zh-CN</dc:language>` was added in `docProps/core.xml`.

The first change is the cause for this issue, as the Chinese language is _not_ the Latin Language but the **East Asian Language**.

And why the western font (Latin font) cannot be changed after `--metadata lang=zh-CN` was added here? Because all texts are regarded as the Chinese language in Word. However, typical fonts for instance, `Calibri` and `Cambria` in the default template are unavailable for Chinese. If you apply a font like [LXGW WenKai](https://github.com/lxgw/LxgwWenKai), it will work as expected.

For a general docx document created by hand in Microsoft Word, the language properties are set as below:

```xml
<lang w:val="en-US" w:eastAsia="zh-CN" w:bidi="ar-SA" />
```

While the the Pandoc’s default ouput is:

```xml
<lang w:val="zh-CN" w:eastAsia="en-US" w:bidi="ar-SA" />
```

As a consequence, I think when the option `--metadata lang=zh-CN` is added, the property `w:eastAsia` should be specified as `zh-CN`, while the property `w:val` remains unchanged. I’m not sure what potential problems will appear if this property changes, but for fixing this issue, it might be taken into account.

**Comment by jgm** [comment]
This suggests that we should determine whether the language is an East Asian language in `addLang` and maybe `getTextProps`, modifying `w:val` or `w:eastAsia` depending on the answer.  I'd like to be more convinced that this is right (e.g. with documentation) and wouldn't have other bad effects.  We'd also need a way to select East Asian languages.  I guess we could simply hard-code a list of langs, but I don't know what that list should be.

**Comment by TomBener** [comment]
East Asian languages, also known as CJK, according to [Microsoft](https://docs.microsoft.com/en-us/windows/win32/tablet/factoids-for-east-asian-languages),  are defined as Chinese (Simplified), Chinese (Traditional), Japanese and Korean.

In the list of [BCP 47](https://www.techonthenet.com/js/language_tags.php), these language tags are included:

- `zh-CN`  Chinese (Simplified), China
- `zh-HK`  Chinese (Traditional), Hond Kong
- `zh-TW`  Chinese (Traditional), Taiwan
- `jp-JP`  Japanese, Japan
- `ko-KR` Korean, Republic of Korea

However, `zh-HK` is not include in [Microsoft Office 2016](https://docs.microsoft.com/en-us/deployoffice/office2016/language-identifiers-and-optionstate-id-values-in-office-2016#language-identifiers) and [Windows](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows?view=windows-11#language-packs).

This might be a reference for the list of langs.

**Comment by jgm** [comment]
Okay, thanks for diagnosing this.  I've pushed a fix that seems to work, but more testing would be helpful. A nightly with this change should be available within 24 hours.

**Comment by jgm** [comment]
I'm not sure if citeproc offers a way to use different locale-dependent quoting styles for entries in different languages.  @denismaier do you know?
(Have you est the `language` field in the CSL JSON bibliography entries?)

**Comment by TomBener** [comment]
> Have you set the `language` field in the CSL JSON bibliography entries?

Nope. My bibliography file was exported as BibLaTeX from [Better BibTeX for Zotero](https://github.com/retorquere/zotero-better-bibtex). The language entry was not exported.

**Comment by denismaier** [comment]
Vanilla CSL does not support this. There's an extended variant [CSL-M](https://citeproc-js.readthedocs.io/en/latest/csl-m/)  that supports that kind of stuff, and a lot more.
