### ISSUE TITLE
Markdown->Revealjs: web sandbox and local version give different results

### ISSUE THREAD

**Issue by ale66** [jgm/pandoc#7026]
Hello John, hello everybody.

I normally make my slides on Windows 10 with Markdown->pandoc->html+revealjs with a local pandoc installation I maintain with Chocolatey;
this is what I see:

```bash
C:\Program Files\cmder>choco upgrade pandoc
Chocolatey v0.10.15
Upgrading the following packages:
pandoc
By upgrading you accept licenses for the packages.
pandoc v2.11.3.2 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

However, then I type:

```bash
C:\Program Files\cmder>pandoc --version
pandoc 2.2.3.2
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Default user data directory: C:\Users\ale\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

So, is it 2.11.3.2 or 2.2.3.2?

Then, the creation of html/revealjs presentations:

```bash
C:\Program Files\cmder>pandoc --standalone --from markdown --to revealjs test.md -o test.html
```

fails miserably: the HTML output does not load properly on Firefox.
However, if I feed the same Markdown source to the pandoc sandbox on the web and it works exactly as expected.
Is it a chocolatey distribution issue?

**Comment by jgm** [comment]
Probably you have two versions installed, and the older one is first in your executable search path.  Uninstall the older one.

**Comment by jgm** [comment]
Oh, actually, the answer is right in the output you pasted:
```
Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```
There was an error, apparently.

**Comment by ale66** [comment]
Thanks John, I replicated the installation on a different computer with newer Win10 version and it works. 
I apologise for the false alarm.
Thanks.
