### ISSUE TITLE
min and max not converted from .docx to .tex

### ISSUE THREAD

**Issue by skromnibog** [jgm/pandoc#7029]
When converting simple equation with min from .docx to .tex, the min doesn't appear. Instead only \operatorname{}

pandoc version 2.2.3.2
command line: pandoc -o example_1.tex example_1.docx

example input:
[example_1.docx](https://github.com/jgm/pandoc/files/5815354/example_1.docx)

produced output:
\[x = \operatorname{}\left( 0,1 \right)\]

**Comment by jgm** [comment]
Current release of pandoc gives this output:
```
\[x = \min_{}\left( 0,1 \right)\]
```
Upgrade!

**Comment by skromnibog** [comment]
The problem was that I have Anaconda in path before newly installed pandoc and Anaconda has old version of pandoc (2.2.3.2).
