### ISSUE TITLE
Option for wrapping block codes with minipages (LaTeX)

### ISSUE THREAD

**Issue by aviramsegal** [jgm/pandoc#703]
Curretnly block codes are able to split between pages. for preventing it it is possible to wrap it with a minipage:

\begin{minipage}{linewidth}
\begin{listings}
some code
\end{listings}
\end{minipage}

I downloaded the sources and added it manually for now, I tried doing something more general to suggest as a pull request but Haskell kicked me to the curve.

I hope you will be kind enough to add it, it should be very simple

**Comment by wladston** [comment]
Can anyone explain how can I use that code with pandoc to get the desired result?
