### ISSUE TITLE
Converting open bracket from .docx to .tex works, but the converted .tex cannot be converted back to .docx

### ISSUE THREAD

**Issue by skromnibog** [jgm/pandoc#7030]
pandoc version 2.2.3.2

To reproduce run:

pandoc -o example_2.tex example_2.docx

with the following file:
[example_2.docx](https://github.com/jgm/pandoc/files/5815398/example_2.docx)

then run:

pandoc -o example_2_from_tex.docx example_2.tex

Reported error is "unexpected eof".

The produced tex file:

\[x = \left\{ \begin{matrix}
0 & ,y \geq 0 \\
1 & ,y < 0 \\
\end{matrix} \right.\ \]

Removing "\right.\ " makes the conversion from .tex to .docx work.

**Comment by mb21** [comment]
Can you try with the newest pandoc version?

**Comment by jgm** [comment]
This works fine with the latest pandoc. Upgrade!

**Comment by skromnibog** [comment]
The problem was that I have Anaconda in path before newly installed pandoc and Anaconda has old version of pandoc (2.2.3.2).
