### ISSUE TITLE
The extension backtick_code_blocks is not supported for gfm

### ISSUE THREAD

**Issue by zspitz** [jgm/pandoc#7033]
Using pandoc 2.11.3.2, the following command line:

```none
pandoc -f docx -t gfm+backtick_code_blocks -o dlr-overview.md dlr-overview.docx
```

reports:

```none
The extension backtick_code_blocks is not supported for gfm
```

The `fenced_code_blocks` extension gives the same error.

GFM supports both backticks and tildes for [fenced code blocks](https://github.github.com/gfm/#fenced-code-blocks).

**Comment by zspitz** [comment]
It's possible to force backtick code blocks with `gfm`  by specifying the language name as the first class in the code attribute. The following:

```csharp
var visitor = new DelegateVisitor();
visitor.Add((CodeBlock codeBlock) => 
    codeBlock with
    {
        Attr = Attr.Empty with
        {
            Classes = "csharp".Yield().ToImmutableList()
        }
    };
```

will produce code blocks like this:

    ```csharp
    var x = 5;
    ```

From the [docs](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes):

> If the `fenced_code_attributes extension` is disabled, but input contains class attribute(s) for the code block, the first class attribute will be printed after the opening fence as a bare word.

**Comment by jgm** [comment]
The reason the extension isn't valid for `gfm` is that this that `gfm` is built as a set of extensions on `commonmark` and this is a *core* feature of `commonmark`.  As a core feature it can't be turned off.  We don't allow extensions unless the feature can be turned both on and off.

**Comment by zspitz** [comment]
So what am I to do if I'm outputting to `gfm` or `commonmark` and I want to use fenced blocks without specifying the language?

It's admittedly a stylistic preference, but is there some sort of philosophical objection to handling this scenario?

**Comment by jgm** [comment]
You can't do this (indeed, you can't do it with `markdown` output either).  Having an extension for backtick code blocks wouldn't help.  What you'd need to do is to *turn off* indented code blocks, but that's a core feature of markdown and commonmark.

The writer uses indented blocks when there are no attributes, even if fenced syntax is available.  That's a semi-arbitrary choice, and it could be changed, but either way people will complain.

**Comment by jgm** [comment]
See #5280

**Comment by jgm** [comment]
We might consider changing the default output for commonmark/gfm to use fenced code blocks always (which is what `cmark -t commonmark` does).  But this would be better discussed first on pandoc-discuss.

**Comment by zspitz** [comment]
FWIW I'm not sure that the default should be changed. I also don't need an option to change the behavior, as I can workaround my specific issue by setting the language.

**Comment by jgm** [comment]
Note that you can also use `default` for the language if you want it to render with no highlighting.
