### ISSUE TITLE
Markdown strange list behaviour

### ISSUE THREAD

**Issue by Y3cWxaL0Z95j** [jgm/pandoc#7037]
pandoc -v pandoc 2.11.3.2 Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2, citeproc 0.3.0.3, ipynb 0.1.0.1

MyMakdown.md contains

```
-   My
-   UnOrdered
-   list

Some text
```

If I run `cat MyMakdown.md | pandoc -f markdown -t markdown` the result is OK. But if my file is (a list followed by code):

```
-   My
-   UnOrdered
-   list

    Some text
```

the result is

```
-   My

-   UnOrdered

-   list

    Some text
```

The list is not any more "tight". I would expect a tight list followed by code-text.

**Comment by jgm** [comment]
This is correct behavior.  (This is how you include a second paragraph under a list item.)  If you want a list followed by code, use a fenced code block or separate the two elements with an HTML comment:
```
-   one
-   two

<!-- end list -->

    code
```
