### ISSUE TITLE
A few explanations for '--self-contained' argument ?

### ISSUE THREAD

**Issue by cinomen** [jgm/pandoc#7038]
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4

I am trying to create HTML file, using '--self-contained'', but experienced some difficulties.

Example:
pandoc --self-contained -o html "http://www.dr-hoiby.com/" (simple web-page with little text and pictures)
pandoc: Cannot decode byte '\xe9': Data.Text.Internal.Encoding.Fusion.streamUtf8
: Invalid UTF-8 stream
^What does it mean this error message ?

pandoc --self-contained -o html "https://pandoc.org"
I only receive html output file, listed as source code instead of typical browser view...?
Is it this the real intention of this command or iam misunderstanding something...?

I would like to receive a full single html file (from web based soure) for furthur editing to e-book output.
What would be the correct syntax in this case ?

Could you give an example for the use of "data:" argument ?

Thanks in advance

**Comment by jgm** [comment]
Please direct questions to the pandoc-discuss mailing list. This is not the place for questions.

A couple hints (but if these don't suffice, don't post here, go to pandoc-discuss).
See `-o` in the manual. It doesn't do what you seem to think it does.
For the invalid UTF-8 stream, see the manual under Character Encoding.
And note that your version of pandoc is quite old; you might consider using a more recent version.
