### ISSUE TITLE
rst-writer fails to include image

### ISSUE THREAD

**Issue by markus-oehme-pg40** [jgm/pandoc#7039]
I stumbled upon the following problem where pandoc correctly extracts an image but then does not include it in the output document. Taking the following input (note that the image file should be supplied separately):
```
<!DOCTYPE html>
<html>
    <head>
        <title>Title</title>
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
      <span class="something">
        <img src="cats.jpg">
      </span>
    </body>
</html>

```
the invocation
``pandoc -f html -t rst --extract-media=extract input.html -o output.rst`` creates an empty file. Omitting the ``class`` attribute of the span fixes the issue and causes the output to contain the image reference. In all cases the image is extracted. Using a different writer (e.g. latex) does not show the same problem.

I'm using the Fedora package which reports the following version information:
```
$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: [snip]
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by mb21** [comment]
Can you try the latest pandoc version?

**Comment by jgm** [comment]
Thanks for reporting. I can confirm this happens with the latest version too.  It is an issue with the RST writer, not the HTML reader.
Minimal repro, native -> rst.
```
 % pandoc -f native -t rst
[Para [Span ("",["something"],[]) [Image ("",[],[]) [] ("cats.jpg","")]]]
^D
```
Interestingly, if you leave out the class on the span, it works:
```
 % pandoc -f native -t rst
[Para [Span ("",[],[]) [Image ("",[],[]) [] ("cats.jpg","")]]]
^D
|image1|

.. |image1| image:: cats.jpg
```

**Comment by jgm** [comment]
Experimenting in the repl shows:
```
λ> transformInlines [Span ("",["something"],[]) [Image ("",[],[]) [] ("cats.jpg","")]]
[]
```

**Comment by jgm** [comment]
Culprit seems to be `flatten`:
```
λ> concatMap flatten [Span ("",["something"],[]) [Image ("",[],[]) [] ("cats.jpg","")]]
[Span ("",["something"],[]) []]
```
used in l. 425.

**Comment by jgm** [comment]
For background on this see #4368.

**Comment by jgm** [comment]
```
λ> flatten $ Span ("",["something"],[]) [Image ("",[],[]) [] ("cats.jpg","")]
[Span ("",["something"],[]) []]
```

**Comment by jgm** [comment]
I've made a small change to `flatten` that should fix this particular issue.

**Comment by markus-oehme-pg40** [comment]
Wow, that was a quick fix. :)

Let me express my gratitude for everybody making pandoc possible, it's a really cool piece of technology. Thanks a lot!
