### ISSUE TITLE
Correct BCP47 tag in lang doesn't work but incorrect one does work when producing PDF from md with latex template

### ISSUE THREAD

**Issue by CLRafaelR** [jgm/pandoc#7047]
The section of [Language variables](https://pandoc.org/MANUAL.html#language-variables) states that the variable of `lang` key in the YAML section is based on BCP47. However, some correct tags do not work when producing a PDF file from a md file via pandoc with pandoc's [default.latex](https://github.com/jgm/pandoc/blob/3f9eee473dfa4eca7001cfe9ec57399de7a28e4a/data/templates/default.latex#L331) template.

Let's consider the tag of Japanese language as an example. Since its correct BCP47 tag is `ja`, I set `lang: ja` in the YAML section. However, this caused the following error hindering the document generation:

```bash
Error producing PDF.
! Argument of \str_uppercase:n has an extra }.
<inserted text>
                \par
l.64   \setotherlanguage[]{}
```

However, I replace `ja` with `jp` (Regional Code for Japan, so it's incorrect tag for the Japanese language, in a strict sense), I can get the PDF I want.

Would you have any idea about why this is happening, or would you mind adding some notes that some tags of BCP47 might not work and that regional tags might work for `lang` key to the MANUAL?

# MWE

## test-lang.md

    ---
    #lang: ja  ## Correct BCP47 tag for Japanese language, NOT WORKABLE for pandoc
    lang: jp   ## INCORRECT BCP47 tag for Japanese language, workable for pandoc
    
    ## Japanese font setting
    header-includes: |
      \usepackage{zxjatype}
      \setCJKmainfont{SourceHanSansJP-Medium.otf}
    ---
    
    こんにちは世界！
    
    ::: {lang=jp}
    > こんにちは世界！
    :::

## Bash command

```bash
pandoc test-lang.md --pdf-engine=xelatex -o test-lang.pdf --template=my/path/to/template.tex
```

**Comment by mb21** [comment]
Seems we should simply add a line here: https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L1523

**Comment by CLRafaelR** [comment]
Sounds great. Amending that line will saves those who write in Japanese language!

**Comment by jgm** [comment]
Agreed. @mb21 do you want to submit a PR?
