### ISSUE TITLE
Can not open ICML or parse files produced by pandoc in InDesign or InCopy 2021

### ISSUE THREAD

**Issue by tetov** [jgm/pandoc#7057]
Placing or opening ICML files using InDesign/InCopy 2021 doesn't work for me. By looking at the [ICML spec](https://wwwimages.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/idml/idml-specification.pdf) linked in the source code I've tested to add more tags which made the files openable, but without content in either program.

An image of no content (haha):
![image](https://user-images.githubusercontent.com/14882117/106154887-60a3fc80-6180-11eb-8cc5-aaff8a8c8cd8.png)

Both InDesign and InCopy show 16.0.1 x64 in the "About x" window
```
$ pandoc --version
pandoc 2.11.3
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.2, ipynb 0.1.0.1
User data directory: /home/tetov/.local/share/pandoc or /home/tetov/.pandoc
[..]
```

## To reproduce

input.txt
```
test
```

Command
```
pandoc input.txt -t icml output.icml
```

Actual output.icml
```xml
<ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Paragraph">
  <CharacterStyleRange AppliedCharacterStyle="$ID/NormalCharacterStyle">
    <Content>test</Content>
  </CharacterStyleRange>
</ParagraphStyleRange>
```

Openable output.icml
```xml
<?xml version="1.0"?>
<?aid style="50" type="snippet" readerVersion="7.0" featureSet="513" product="7.0(292)" ?>
<?aid SnippetType="InCopyInterchange"?>
<Document DOMVersion="7.0" Self="d">
  <Story>
    <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Paragraph">
      <CharacterStyleRange AppliedCharacterStyle="$ID/NormalCharacterStyle">
        <Content>test</Content>
      </CharacterStyleRange>
    </ParagraphStyleRange>
  </Story>
</Document>
```
All new lines are needed from my testing. If I comment out third line InCopy and InDesign crashes.

**Comment by mb21** [comment]
you need to add the `--standalone` flag..

**Comment by tetov** [comment]
@mb21 Thank you, life saver! I've read those instructions, only problem is that that was years ago.
