### ISSUE TITLE
Circular defaults file reference in 'command/defaults7.yaml

### ISSUE THREAD

**Issue by danse** [jgm/pandoc#7061]
The error appeared in the continuous integration tests for #7059 but seems unrelated to those changes. `defaults7.yaml` actually includes `defaults6.yaml` in a circular reference, something which should work thanks to #6924. It's also not clear to me why the error was triggered just with a specific Linux version

**Comment by jgm** [comment]
The tests pass, right?  An error *message* is generated, but the test is testing to make sure that that happens.

I think the error you're seeing in CI is not related to this.  It's related to #6674 and is a known intermittent issue.

**Comment by danse** [comment]
Oops sorry, the tests were failing with `Test suite test-pandoc: FAIL` and i wasn't sure about what caused the error status. Thanks for the clarification
