### ISSUE TITLE
RST reader fails on csv-table header with $ as a delimiter

### ISSUE THREAD

**Issue by taleinat** [jgm/pandoc#7064]
Minimal breaking input:
```rst
.. csv-table:: Changes
    :header: "Version", "Date", "Description"
    :widths: 15, 15, 70
    :delim: $

    0.1.0 $ 18/02/2013 $ Initial Release
```

Command line:
```Shell
cat tmp.rst | pandoc --from=rst --to=html
```

I'm not sure whether the above is correct reStructredText input, but docutils renders it correctly, as can be seen on [the PyPI.org project page for this version](https://pypi.org/project/UnittestRandGenState/0.1.4/).

---

The problem seems to be with the handling of the `:header:` directive - removing it leads to successful, correct parsing.

Replacing the commas (`,`) with dollar-signs (`$`) also works:
```rst
    :header: "Version"$ "Date"$ "Description"
```

... but not with a space before the dollar-signs:
```rst
    :header: "Version" $ "Date" $ "Description"
```

---

Tested with pandoc versions:
* 2.11.4
* 2.11.1

References:
* Source: The `info.description` field of [the JSON for UnittestRandGenState v0.1.4 on PyPI.org](https://pypi.org/pypi/UnittestRandGenState/0.1.4/json)

**Comment by jgm** [comment]
OK, looks like in RST you have to use commas as delimiters in the `header` attribute, even if you're setting the delimiter to something else.
