### ISSUE TITLE
Pandoc stuck when using --citeproc with csl

### ISSUE THREAD

**Issue by ehapmgs** [jgm/pandoc#7065]
I am trying to convert from jats to docx using the following command line

`pandoc --standalone --from=jats --to=docx --csl=path --output test.docx test.xml --citeproc`

And it looks like the command gets stuck for a reason

Here are the test XML and the CSL I am using

[Archive.zip](https://github.com/jgm/pandoc/files/5900000/Archive.zip)

pandoc version

`pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1`

**Comment by jgm** [comment]
I believe this is the same issue as #7060 which should be fixed by commit a9adb2964862fd8074cf9dfdcb8248d3a13665c5.
I can confirm that the current dev version of pandoc does not hang on this input.
Pending a new release, you could grab the latest nightly build.
