### ISSUE TITLE
`\framebreak` is inserted into a `block` environment when producing beamer slides with markdown's `###` header

### ISSUE THREAD

**Issue by CLRafaelR** [jgm/pandoc#7072]
I am trying to produce beamer slides with `{.allowframebreaks}` and `\framebreak` with pandoc ver `2.11.3.2`. However, `\framebreak` is inserted into a `block` environment of LaTeX when producing beamer slides with markdown's `###` header.

`###` of Markdown is rendered in a `block` environment of LaTeX (`\begin{block}...\end{block}`) when producing beamer slides. I would like to break a frame to separate the two blocks, as follows:

### Input

```markdown
## slide {.allowframebreaks}

### block 1

text 1

\framebreak

### block 2

text 2
```

However, the two blocks are not separated, as shown in the following screen capture.

![image](https://user-images.githubusercontent.com/42314553/106728316-aadd2000-664f-11eb-860a-39a4a657c13f.png)

This happens because when the above input is rendered in a LaTeX file, the `\framebreak` command wrongly comes into the block environment in the LaTeX file, as follows;

### Undesireble LaTeX output

```latex
\begin{frame}[allowframebreaks]{Blocks with \texttt{allowframebreaks}}
\protect\hypertarget{blocks-with-allowframebreaks}{}
\begin{block}{Block 1}
\protect\hypertarget{block-1}{}
text 1

\framebreak %%% This \framebreak should not precede \end{block} %%%
\end{block}

\begin{block}{Block 2}
\protect\hypertarget{block-2}{}
text 2
\end{block}
\end{frame}
```

Is there any way to correct this behaviour and get the following right result?

### Desireble LaTeX output

```latex
\begin{frame}[allowframebreaks]{Blocks with \texttt{allowframebreaks}}
\protect\hypertarget{blocks-with-allowframebreaks}{}
\begin{block}{Block 1}
\protect\hypertarget{block-1}{}
text 1

\end{block}

\framebreak %%% \framebreak should always follow \end{block} %%%

\begin{block}{Block 2}
\protect\hypertarget{block-2}{}
text 2
\end{block}
\end{frame}
```

# MWE

## test-beamer.md

<pre lang="markdown"><code>
---
title: "Untitled"
author: "CLRR"
date: "2021/2/3"
---

## Plain texts with `allowframebreaks` {.allowframebreaks}

text 1

\framebreak

text 2

### Block 1

`###` of Markdown is rendered in `\begin{block}...\end{block}` when producing beamer slides.

text 1

\framebreak

### Block 2

text 2
</code></pre>

## LaTeX (Beamer) code

Generated via `pandoc -t beamer -f markdown test-beamer.md`

```latex
\begin{frame}[allowframebreaks]{Plain texts with
\texttt{allowframebreaks}}
\protect\hypertarget{plain-texts-with-allowframebreaks}{}
text 1

\framebreak

text 2
\end{frame}

\begin{frame}[fragile,allowframebreaks]{Blocks with
\texttt{allowframebreaks}}
\protect\hypertarget{blocks-with-allowframebreaks}{}
\begin{block}{Block 1}
\protect\hypertarget{block-1}{}
\texttt{\#\#\#} of Markdown is rendered in
\texttt{\textbackslash{}begin\{block\}...\textbackslash{}end\{block\}}
when producing beamer slides.

text 1

\framebreak  %%% This \framebreak should not precede \end{block} %%%
\end{block}

\begin{block}{Block 2}
\protect\hypertarget{block-2}{}
text 2
\end{block}
\end{frame}
```

**Comment by mb21** [comment]
I didn't check the details.. but is the title structure conforming to https://pandoc.org/MANUAL.html#structuring-the-slide-show ?

**Comment by CLRafaelR** [comment]
Yes, I think so.

**Comment by tarleb** [comment]
I don't think this is possible right now. As a workaround, you can use `\pagebreak` instead of `framebreak` to get the desired pdf output. The hack relies on beamer to automatically create framebreaks if an "allowframebreaks" slide becomes too full.

**Comment by CLRafaelR** [comment]
@tarleb 
The fenced divs with `block` and `###` header below the slide level go perfectly well! Thank you for your suggestion. 

I close this thread.
