### ISSUE TITLE
No spacing between large numbers and subsection names in TOC in PDF/LaTeX

### ISSUE THREAD

**Issue by beejjorgensen** [jgm/pandoc#7074]
When the section numbers get long, I'm getting this output packed together in the TOC:

![numbered-toc](https://user-images.githubusercontent.com/312455/106771584-f7930d80-65f3-11eb-9611-2f1ebf3efce8.png)

Built with pandoc 2.11.2:

`pandoc -o foo.pdf --number-sections --toc foo.md`

Source and PDF:

[markdown_pdf.zip](https://github.com/jgm/pandoc/files/5919686/markdown_pdf.zip)

Any workarounds?

**Comment by jgm** [comment]
This spacing is done automatically by latex.  But here's how to adjust it.  Include this in your header-includes:
```
\usepackage{tocloft}
\setlength\cftsubsecnumwidth{4em}
```

**Comment by beejjorgensen** [comment]
Actually that was the next level down, but this worked for me:

```
\setlength{\cftsecnumwidth}{3em}
```

Cheers!
