### ISSUE TITLE
pandoc outputs wrong dokuwiki with HTML tags

### ISSUE THREAD

**Issue by Hecmay** [jgm/pandoc#7075]
Hi, I am using pandoc 2.2.1

```shell
$ pandoc --versionpandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

I was trying to convert markdown to dokuwiki using pandoc. But I noticed that the output dokuwiki has a lot of HTML tags, which cannot be rendered by the dokuwiki page. For example, if I feed this into pandoc (please remove the \escape before the ``` code block indicator)

```
## Title
- **How**: test
- **Why**: second
- **Connect**: text
   words
   /```python
   # Comment

   import os
   /```
```

Here is the output 

```shell
$ pandoc -f markdown -t dokuwiki test.md 
===== Title =====

<HTML><ul></HTML>
<HTML><li></HTML><HTML><p></HTML>**How**: test<HTML></p></HTML><HTML></li></HTML>
<HTML><li></HTML><HTML><p></HTML>**Why**: second ''%%python   import numpy%%''<HTML></p></HTML><HTML></li></HTML>
<HTML><li></HTML><HTML><p></HTML>**Connect**: text words ```python # Comment<HTML></p></HTML>
<HTML><p></HTML>import os ```<HTML></p></HTML><HTML></li></HTML><HTML></ul></HTML>
```

**Comment by Hecmay** [comment]
It seems that if I remove the code blocks, pandoc would give correct output.

**Comment by jgm** [comment]
Pandoc falls back to using raw HTML (using the dokuwiki HTML tag syntax) when dokuwiki syntax is too limited to render a list properly. In this case you have a list with multiple paragraphs ina single list item, which can't be done in native dokuwiki.

**Comment by jgm** [comment]
Your input and output are confusing.  With `-f markdown`, you need a blank line before the code block.  If I add that,
````
## Title
- **How**: test
- **Why**: second
- **Connect**: text
   words

   ```python
   # Comment

   import os
   ```
````
then with `pandoc -f markdown -t dokuwiki` I get
```
===== Title =====

  * **How**: test
  * **Why**: second
  * **Connect**: text words<code python>
# Comment

import os
</code>
```
with the latest pandoc version.  Try upgrading?

**Comment by tarleb** [comment]
It seems that the issue has been fixed, thus closing. Please reopen if this is incorrect.
