### ISSUE TITLE
Include only parts of a file

### ISSUE THREAD

**Issue by phmarek** [jgm/pandoc#7076]
The org-mode feature to use the _result_ of some sources (`:export both`, `:export output`, etc.) isn't available in pandoc (yeah, I'm not sure about that because of security, too).

In `RST`, there are `start-line` and `end-line` options; org-mode has `range-begin` and `range-end`(eg. https://github.com/MatthewZMD/.emacs.d/blob/master/init.org#modification), these are not supported by pandoc yet.

Is there a way to have only parts of a file inserted (and highlighted), perhaps via patterns and not only line numbers? If that needs an external shell call I'd be happy enough.

Thanks a lot!

**Comment by phmarek** [comment]
Calling an external script might a more robust variant, because including parts based on an existing cross-reference is more exact than using RegExes.

**Comment by tarleb** [comment]
I think this may be a duplicate of #6466. The Org manual [doesn't mention](https://orgmode.org/manual/Include-Files.html#Include-Files), `range-begin` or `range-end` is this a custom addition?

You are right that calling external code is out of scope for pandoc (for multiple reasons, one of them security). The `:export both` and `:export output` settings *are* supported in that they produce the expected result if the code block as been executed by org-mode before, i.e., if there's a `#+RESULT` after the block.

**Comment by phmarek** [comment]
I didn't see it in the org-mode documentation either, just stumbled upon it in quite a few places.

The link above is one, here's another: https://emacs.stackexchange.com/questions/64/how-to-auto-calculate-the-begin-and-end-lines-when-including-source-files-in-org?rq=1

Well, perhaps I should write me a vim macro (or perl script) to re-create the `#+RESULT` blocks...
Can I include the result from an external file as well? That would be much easier to integrate into a `Makefile` pipeline.

**Comment by tarleb** [comment]
Maybe that's old syntax that has been replaced with `:lines`. I don't want to add support for undocumented features, so I'm closing this in favor of #6466.

You could write a (Lua) [filter](https://pandoc.org/filters.html) to execute the scripts as done by [Stencila](https://github.com/stencila/) or my dormant/defunct [rundoc](https://github.com/tarleb/rundoc).
