### ISSUE TITLE
md -> pdf: link-citations hypertarget in wrong position

### ISSUE THREAD

**Issue by priiduonu** [jgm/pandoc#7078]
When `link-citations: true`, clicking on the citation link scrolls the PDF viewer just below the first row of the bibliography record. It seems to be caused by inserting the `\leavevmode` command before the `\hypertarget`, causing the hypertarget appear on the baseline.

When I use the following in `header-includes`:

```
\AtBeginEnvironment {cslreferences}{\renewcommand{\leavevmode}{\relax}}
```
everything works as it should.

```
pandoc 2.9.2.1
pandoc-citeproc 0.17.0.1
```
Command used:

```
pandoc --filter pandoc-citeproc testcite.md --standalone -o testcite.pdf
```
Attached the sample file `testcite.md` (remove `.txt` from the filename).

[testcite.md.txt](https://github.com/jgm/pandoc/files/5931948/testcite.md.txt)

**Comment by jgm** [comment]
I felt sure we wouldn't have added the `\leavevmode` without a reason.
This is the background I've found so far:
https://github.com/jgm/pandoc/issues/2704

**Comment by jgm** [comment]
```
commit 46135ac8758c4fbb9dfe676b1462463f5476bbff
Author: John MacFarlane <jgm@berkeley.edu>
Date:   Thu Mar 2 12:13:20 2017 +0100

    LaTeX writer: add `\leavevmode` before hypertarget at start of paragraph.
    
    Closes #2704 (formatting problems in beamer citations).
    
    See
    http://tex.stackexchange.com/questions/22852/function-and-usage-of-leavevmode

```

**Comment by priiduonu** [comment]
Can You test if the sample file works OK for You? Maybe it is the LaTeX itself that acts differently now, see
https://tex.stackexchange.com/a/468934/132610

**Comment by jgm** [comment]
I'm willing to take your word for it that your sample works fine.  But the original issue had to do with beamer, not straight LaTeX output, so that's what needs to be tested (see #2704).

**Comment by priiduonu** [comment]
It seems if you set `link-citations: true` in the sample provided in #2704, you get the same incorrect result with hypertargets (one line off) as I described in my first comment, although the visible output remains the same (and as one would expect).

**Comment by jgm** [comment]
The question is whether removing the `\leavevmode` off works with the case in #2704.
(That was the case that motivated adding it in the first place.)

**Comment by priiduonu** [comment]
Well, adding the `\leavvmode` seems to cause problem with hypertarget offset with both beamer and article `documentclass`.

**Comment by jgm** [comment]
Yes, I understand that.  But `\leavevmode` was added for a reason, described in #2704. What we need to know is whether that it is still needed for that reason.

**Comment by priiduonu** [comment]
Tried with the latest (2.11.4) pandoc today, `leavevmode` still needed, otherwise beamer output will suffer.

However, wrapping the `hypertarget` in `\vadjust pre{...}` seems to fix the hypertarget offset problem, got the hint from here:
https://tex.stackexchange.com/questions/258409/manually-added-hypertargets-are-shifted-by-one-line-in-pdf

**Comment by jgm** [comment]
The SO post says that `\vadjust pre` works for pdftex.  I'm assuming from that that it doesn't work for xetex or luatex?

**Comment by jgm** [comment]
Another possible solution would be to add the `leavevmode` *only* in beamer, if it's only needed there.

**Comment by priiduonu** [comment]
> The SO post says that `\vadjust pre` works for pdftex. I'm assuming from that that it doesn't work for xetex or luatex?

It does work for xetex and luatex (I've tested with xelatex), see
https://tex.stackexchange.com/questions/325450/jumping-to-hypertarget-in-a-longtable-lands-too-low-in-the-row/330130#330130

**Comment by priiduonu** [comment]
I would suggest leaving `leavevmode` as is, because it is needed in beamer output and it influences the formatting of the bibliography while wrapping the `hypertarget` in `\vadjust pre{...}` to overcome the offset problem.

**Comment by jgm** [comment]
Done, thanks for the information!
