### ISSUE TITLE
ePubs no longer recognized by other apps

### ISSUE THREAD

**Issue by deejf** [jgm/pandoc#7081]
As far as I can tell, the latest update to Pandoc has broken the ePubs it generates, for two out of the three software packages where I use them. This is an issue as I'm a writer and I also publish public domain texts, and Pandoc is a major part of my workflow for generating ebooks.

The program that will open them is Sigil, in the version that is current on Fedora at the moment (I'm reasonably sure it's an old version). The programs that give me "Error! Unsupported Format" are [Calibre (5.1.10)](https://github.com/kovidgoyal/calibre/) and [(Android) Book Reader (1.13.26)](https://gitlab.com/axet/android-book-reader/). Calibre will let me get in and monkey with the text, but the YAML metadata is utterly lost. Book Reader simply gives the error and won't even load them. I have now tried this with five different files.

Sigil claims that the ePubs validate, but obviously there is _something_ wrong, or they would read by the other two standard pieces of software.

Sorry that I can't point to anything more technical and precise to help find the problem but, again, I'm a writer and editor, not a programmer. But I seriously *need* Pandoc to work.

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc. and in your case you could also provide the version that still works)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**.

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by tarleb** [comment]
The following would be important for us to narrow the problem down: can you create ebooks from documents that contain just

- a single paragraph,
- a code block, or
- a table.

Also, can you find out which version you used before?

**Comment by deejf** [comment]
In order:

* pandoc 2.9.2.1

As for what version still works, it's whatever version ran through the fedora repos earlier than that.

* The exact command line used:

    pandoc -o 'title PROOF.epub' 'title.md' -c ./iktp-standard.css --epub-chapter-level=3 --epub-cover-image='Proof Cover.jpg'

* The exact input used is typically a novel-length Markdown file, headed by a Pandoc-style YAML metadata block. I can post one of the ones that failed if you like, but I'm not sure an 80,000 word western or even a 20,000 word space opera novella will be all that much help. Outside of the metadata block and the public domain statement I put up front, the heaviest formatting is usually chapter headings and italics tags. A few westerns have some verse in them that I set off seperately, but I don' think that was the case for any of the recent ones.

* The output received: again, I can share, if github allows one to attach files. An ePub file that will open in Sigil, but not in the other two programs detailed above.

* The output I expected instead: an ePub that works in Calibre, and FBReader or Bookreader, just like I have been getting for the past five years or so.

Let me see what I can get by stripping down one of the novellas.

**Comment by deejf** [comment]
I owe an apology. It was *not* Pandoc causing the problem, it now seems. Opening in Sigil, and making and saving any changes at all, is (somehow) what mucked everything up, despite Sigil not having changed in quite a long time. 

I'm sorry, it didn't even occur to me that opening a file to make sure it opened, making a small tweak (e.g., putting in a page break so the Public Domain/copyright page would be a separate page) and saving it would be the source of the issue. Again, it's what I've been doing for five years or so, and Sigil hasn't updated while Pandoc has, so I went with what had changed as the source of the problem.

**Comment by tarleb** [comment]
Thanks for the feedback. Maybe inserting the page break can be automated? Feel free to ask about this on pandoc-discuss. (And maybe [this](https://github.com/pandoc/lua-filters/tree/master/pagebreak) is of interest to you?)
