### ISSUE TITLE
option to put list of tables and list of figures at the bottom of the document

### ISSUE THREAD

**Issue by Fabioni** [jgm/pandoc#7082]

**Comment by mb21** [comment]
Thank you for submitting a bug report. However, we cannot improve pandoc or help you unless you give us all of the following information:

* the pandoc version (check using `pandoc -v` and try to reproduce the bug with the latest released version of pandoc, or even better: the development version or [nightly build](https://github.com/pandoc-extras/pandoc-nightly).)
* the exact command line used
* the exact input used
* the output received
* the output you expected instead

A small test case (just a few lines) is ideal.  If your input is large, try to whittle it down to a **minimum working example**. (For binary input formats like docx, you should attach the minimum sample file.)

Finally, ask questions on [pandoc-discuss](http://groups.google.com/group/pandoc-discuss) and read the [User's Guide](http://pandoc.org/MANUAL.html).

**Comment by Fabioni** [comment]
Hey, this is not a bug report, it is a enhancement requests. And it is about the data/templates/default.latex file.

**Comment by tarleb** [comment]
Just to make sure I understand things correctly: what you'd like is to update the template such that it contains

``` latex
$if(lof)$
$if(lo-bottom)$
$else$
\listoffigures
$endif$
$endif$

$-- ...
$body$
$-- ...

$if(lof)$
$if(lo-bottom)$
\listoffigures
$endif$
$endif$
```

We generally try to avoid a proliferation of variables, and it is possible to handle this via a custom template. I'm afraid it's out of scope for these reasons.

**Comment by jgm** [comment]
I'd say this sort of thing is exactly why we offer the ability to use custom templates.  The default template is already complex enough. It makes certain decisions you may not like, but you can always make slight changes and use `--template`. I do this all the time.
