### ISSUE TITLE
Including an _ in a latex environment causes pandoc to ignore entire environment

### ISSUE THREAD

**Issue by leduythuccs** [jgm/pandoc#7083]
When an underscore (_) is found inside an environment, instead of raising an error, pandoc ignores it completely without any message.

My example input:  
```tex
a
\begin{itemize}
    \item b_c
    \item d
\end{itemize}
e
```

My expected: pandoc will raise an error (because `b_c` is invalid). 

Output: 
```
a

e
```

If I move `b_c` outside of the `itemize`, like: 

```tex
a
b_c
\begin{itemize}
    \item d
\end{itemize}
e
```
It will raise an error as expected:
```
Error at "source" (line 2, column 2):
unexpected Tok "source" (line 2, column 2) Symbol "_"
expecting end of input
b_c
 ^
```

The command I used: `pandoc test.tex -o test.md -f latex -t markdown`
My pandoc version:
```
pandoc 2.11.3.2
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1
```

I found this open issue [#4473 ](https://github.com/jgm/pandoc/issues/4473) but I'm not sure whether it relates to my problem.

**Comment by jgm** [comment]
Note that if you run with `--verbose`, you'll get the message
```
[INFO] Skipped '\begin{itemize}
      \item b_c
      \item d
  \end{itemize}' at line 4 column 16
```

If you use `-f latex+raw_tex`, the environment will be parsed as raw tex, which will be passed through to markdown unchanged.  This is probably what you want in this case.

Note that the `a_b` in your itemize environment will cause an error if you try to run LaTeX on it.
The `_` must be escaped if it's not in math mode.
