### ISSUE TITLE
Path to image cover got wrong when converting markdown to EPUB

### ISSUE THREAD

**Issue by Neoteus** [jgm/pandoc#7090]
# Version

pandoc.exe 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2

# Issue

Path I write in YAML block:

```YAML
cover-image: comic/愛聖天使ラブメアリー~悪性受胎~愛聖天使LoveMary惡性受胎/惡性受胎的單行本/1_001.jpg
```

But pandoc returns:

```text
pandoc: comic/€LoveMary€/€/1_001.jpg: openBinaryFile: does not exist (No such file or directory)
```

And here's the command I use:

```bat
pandoc --toc -o book.epub input.md
```

If I delete the line of cover image, the conversion succeeds. And all of other books didn't meet this problem.
If it's because the path contains too many characters?

# Example

- input markdown
- css
- 3 images, including cover
- expected output EPUB

[example.zip](https://github.com/jgm/pandoc/files/5943204/example.zip)

**Comment by jgm** [comment]
It would be helpful to know what OS you're using. Also, could you please try the latest version of pandoc? The version you're using is quite old.

**Comment by Neoteus** [comment]
My OS is Windows 10.

I update pandoc to 2.11, but still not solve the problem.

Some of the cover image path strings lost all Japanese or Chinese characters, while most others didn't meet this problem.

**Comment by jgm** [comment]
Note that the file will be sought relative to the working directory (the directory from which you run pandoc), not relative to the directory containing the markdown file (if it's different).  I say this in case that's the issue.

**Comment by jgm** [comment]
Also, if you're on Windows, try setting your shell to use UTF-8 encoding.
```
chcp 65001
```
then run pandoc

**Comment by mb21** [comment]
I could actually reproduce this with on macOS with the folder structure in the attached zip... but didn't have time to debug much...

**Comment by tarleb** [comment]
Thank you for your patience, @Neoteus. The problem are the tilde `~` characters in the filename. The YAML field is first read as a Markdown string; that Markdown field is then converted back into a plain string later. Tilde characters are used to indicate subscript, so pandoc treats the `cover-image` field as if it was this HTML: `comic/愛聖天使ラブメアリー<sub>悪性受胎</sub>愛聖天使LoveMary惡性受胎/惡性受胎的單行本/1_001.jpg`. The tildes are lost in translation while going back and forth between formatted and unformatted text.

The solution is therefore to prevent the interpretation of tildes as markup by escape them with a backslash:

    cover-image: 'comic/愛聖天使ラブメアリー\~悪性受胎\~愛聖天使LoveMary惡性受胎/惡性受胎的單行本/1_001.jpg'
