### ISSUE TITLE
--link-citations creates multiple links for a single entry

### ISSUE THREAD

**Issue by pletcher** [jgm/pandoc#7094]
I encountered this bug when trying to figure out a way to go back and forth from Pandoc's markdown to docx. The main barrier has been citations, and internal links seemed to provide enough information to write a filter that could parse the docx link and convert it back into markdown citation syntax. (Maybe I'm wrong there -- this is just exploratory.)

But `--metadata link-citations=true` creates two links for inline citations, one for the author's/authors' name(s) and one for the year. The parens aren't included in. I'd expect the output to produce just one link including all parts of the citation. (I omitted page numbers/subrefs here, but they should be part of the link if they're included too, right?)

Pandoc version: 2.11.2

## Example:

```markdown
---
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for
    deoxyribose nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
---

Inline citation in default (Chicago author-date) style: @WatsonCrick1953.
```

## Command

```sh
$ pandoc --from markdown --to docx --citeproc --metadata link-citations=true -o example.docx --standalone -i example.md
```

## Expected output

```xml
<!-- including only the relevant elements -->
      <w:hyperlink w:anchor="ref-WatsonCrick1953">
        <w:r>
          <w:rPr>
            <w:rStyle w:val="Hyperlink" />
          </w:rPr>
          <w:t xml:space="preserve">Watson and Crick (1953)</w:t>
        </w:r>
      </w:hyperlink>
<!-- ... -->
```

## Actual output

```xml
<!-- including only the relevant elements -->
<w:hyperlink w:anchor="ref-WatsonCrick1953">
        <w:r>
          <w:rPr>
            <w:rStyle w:val="Hyperlink" />
          </w:rPr>
          <w:t xml:space="preserve">Watson and Crick</w:t>
        </w:r>
      </w:hyperlink>
      <w:r>
        <w:t xml:space="preserve"> </w:t>
      </w:r>
      <w:r>
        <w:t xml:space="preserve">(</w:t>
      </w:r>
      <w:hyperlink w:anchor="ref-WatsonCrick1953">
        <w:r>
          <w:rPr>
            <w:rStyle w:val="Hyperlink" />
          </w:rPr>
          <w:t xml:space="preserve">1953</w:t>
        </w:r>
      </w:hyperlink>
<!-- ... -->
```

**Comment by jgm** [comment]
Note first that this is an author-in-text citation. citeproc represents this internally as a sequence of two citations, first an "author-only" and then a "suppress-author."  We could change citeproc so that it doesn't link author-only citations; I think that would be reasonable.

The parentheses aren't included because a single citation may contain multiple items which link to different parts of the bibliography. So we just link the parts specific to each entry.

**Comment by pletcher** [comment]
Thanks for the clarification! That all makes sense. I'll close this issue, because this seems like the desired behavior.
