### ISSUE TITLE
jira reader : output empty if input is preceded by two newlines

### ISSUE THREAD

**Issue by iodbh** [jgm/pandoc#7095]
Hi, and thanks for the amazing job you're doing with Pandoc !

I am running into an issue where an image is stripped from html output when preceded by 2 newlines in jira input data.

(edit: I realized after creating the issue that it is not only images being stripped, but the entire content - see example 4 below.)

I am running pandoc 2.11.4.

## example 1 : no newline (works as expected)

**input (in file `test.jira`):**

```
!filename.png!
```

**command line :**  `pandoc -f jira -t html test.jira`

**output :** 

```
<p><img src="filename.png" /></p>
```

## example 2 : 1 leading newline (works as expected)

**input (in file `test2.jira`):**

```

!filename.png!
```

(notice one leading empty line in this file)

**command line :**  `pandoc -f jira -t html test2.jira`

**output :** 

```
<p><br />
<img src="filename.png" /></p>
```

## example 3 : 2 leading newlines (this is where the issue is)

**input (in file `test3.jira`):**

```


!filename.png!
```

(notice two leading empty lines in this file)

**command line :**  `pandoc -f jira -t html test3.jira`

**output :** 

```

```

(output is a single empty line)

## example 4 : 2 leading newlines and some text (issue also present)

**input (in file `test4.jira`):**

```


Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

(notice two leading empty lines in this file)

**command line :**  `pandoc -f jira -t html test4.jira`

**output :** 

```

```

(output is a single empty line)

**Comment by jgm** [comment]
@tarleb this may have to do with the jira-wiki-markup library.

**Comment by tarleb** [comment]
Yes, I found there bug there. The parser does not skip blank lines at the beginning of the input. I'll fix it.

**Comment by jgm** [comment]
We could alternatively have the pandoc reader strip leading space, whichever you prefer.
