### ISSUE TITLE
Problem with fenced_code_attributes with commonmark

### ISSUE THREAD

**Issue by wch** [jgm/pandoc#7097]
I was trying to use `commonmark+fenced_code_attributes` and `gfm+fenced_code_attributes` with one of the examples from the manual, but it didn't work -- the attributes like `.haskell` would get lost in the output:

```bash
cat << EOF | pandoc -f commonmark+fenced_code_attributes -t native
~~~~ {#mycode .haskell .numberLines startFrom="100"}
qsort []     = []
qsort (x:xs) = qsort (filter (< x) xs) ++ [x] ++
               qsort (filter (>= x) xs)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
EOF
```

The result:

```haskell
[CodeBlock ("",["{#mycode"],[]) "qsort []     = []\nqsort (x:xs) = qsort (filter (< x) xs) ++ [x] ++\n               qsort (filter (>= x) xs)"]
```

I ended up spending an embarrassingly long time trying to figure out what was wrong, and finally discovered that it was because `commonmark` and `gfm` have `-fenced_code_attributes`:

```
$ pandoc --list-extensions=commonmark
-ascii_identifiers
-autolink_bare_uris
-bracketed_spans
-definition_lists
-east_asian_line_breaks
-emoji
-fancy_lists
-fenced_code_attributes
-fenced_divs
-footnotes
-gfm_auto_identifiers
-hard_line_breaks
-implicit_figures
-implicit_header_references
-pipe_tables
-raw_attribute
+raw_html
-raw_tex
-smart
-strikeout
-subscript
-superscript
-task_lists
-tex_math_dollars
-attributes
-sourcepos
```

So when I used `+fenced_code_attributes`, it was silently being ignored. It would be much friendlier behavior to either print an error message in this situation, or allow `+fenced_code_attributes` to override the setting in `commonmark`.

**Comment by jgm** [comment]
When this prints `-fenced_code_attributes`, it means that this extension will affect the format, and that it is set to disabled by default.  So `+fenced_code_attributes` *should* work.
Looks like `+fenced_code_attributes+attributes` does work.
(And also `+attributes` by itself).  I need to look into this.
