### ISSUE TITLE
ungraceful exit from iframe "Invalid URL"

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#7099]
From [mailing list](https://groups.google.com/g/pandoc-discuss/c/UKzk5Gr0MDY).

I'm trying to convert this webpage, but pandoc throws an exception -- even when I run it on a saved local version. Any idea why, or if I could have it to ignore the exception and proceed?

```
╭─reagle@hom ~/joseph/2021/02
╰─➤  pandoc -f html -t markdown http://midgardediting.blogspot.com/2013/12/blog-post_23.html  1 ↵
Could not fetch
InvalidUrlException "" "Invalid URL"
```

```
pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1
User data directory: /Users/reagle/.local/share/pandoc or /Users/reagle/.pandoc
```

**Comment by mb21** [comment]
Minimal repro:

    echo '<iframe src="" />' | pandoc -f html -t native
