### ISSUE TITLE
Epub-import into kindle previewer crashes on incomplete links (URLs)

### ISSUE THREAD

**Issue by abrey66** [jgm/pandoc#7100]
## BUGREPORT:

Chocolatey v0.10.15
pandoc 2.11.4 [Approved]
pandoc-crossref 0.3.4.1 [Approved] Downloads cached for licensed users
MarkdownMonster.Portable 1.26 [Approved]
MarkdownMonster 1.26.2 [Approved] Downloads cached for licensed users

kindle previewer / importer 3.50.0

## input:
```
---
title: The Digital Ape
toc-title: Contents
subtitle:
author: Andreas Brey
---

# A digital fairytale {#begin-of-text}

QUOTE: Georg Wilhelm Friedrich Hegel <br/>**Phänomenologie des Geistes (1807)**

: Vorrede, … \[sie\] scheint bei einer philosophischen Schrift nicht nur überflüssig,
 sondern um der Natur der Sache willen, sogar unpassend und zweckwidrig zu sein. 
 (~ A philosophical introduction seems to be redundant, wrong and counter-productive)
 [www.deutschestextarchiv.de](www.deutschestextarchiv.de/book/view/hegel_phaenomenologie_1807?p=16)

```
## output / behaviour:
```
    Opening the epub-file with the kindle previewer (incl. kindlegen) leads to an import-crash
   (and request to upload the incompatible epub)
    
```
see also attached screenshot

![2021-02-15 kindle previwer crash on epub import](https://user-images.githubusercontent.com/16462525/107921455-d379e980-6f6e-11eb-8662-ed8a58240ca4.png)

## Links / URL have to be complete:
```
A [mylabel](www.asite.com) will crash the importer

```

Workaround
```
A [mylabel](https://www.asite.com) works 

```
Additionally I validate with a prefilter-script for this and other kindle-specific requirements.

## Update documentation:
```
https://pandoc.org/epub.html is outdated
kindlegen does not exist anymore, it was replaced by the kindle previwer (and importer)
https://kdp.amazon.com/de_DE/help/topic/G202131170

```
I would be happy to provide here (and at other locations) updates to the core documentation. How is the process? Pull-requests for documentation?

Thanks for consideration. Have a good day!

Andreas (German IT-guy)

**Comment by mb21** [comment]
> Links / URL have to be complete

hm.. I suppose we could fix up links in pandoc's EPUB writer... then again, there might be other things that are hard do detect and which kindle previewer doesn't like either... question: is the epub at least valid? can you test it here? http://validator.idpf.org/

> I would be happy to provide here (and at other locations) updates to the core documentation. How is the process? Pull-requests for documentation?

That would be welcome! You can make a pull by editing this file: https://github.com/jgm/pandoc/blob/master/doc/epub.md

**Comment by abrey66** [comment]
thank you for the fast reply. 
The validator output is here: 

```
EPUB Validator (beta)
Results

Detected version: EPUB 3.0.1

Results: Congratulations! No problems were found in EN02.epub.

Validated using EPUBCheck version 4.1.1.
```

This was my pandoc call of the snippet above: 

```
$ pandoc EN02.md -f markdown -t epub3 -s -o EN02.epub
```

Ok, I promise to improve docs this week.

**Comment by abrey66** [comment]
One addition: 
After import the kindle previewer (importer) provide a beta-version quality check, in order to enable book-publishing on Amazon. 
Here the check even complains about an URL within plain text. Examplel my text www.a-website.com my text.
This leads to the following WARNING: 

`
Navigation,"Invalid External Link","Your book has an external link that does not work: xxxxxxx On the website www.system-human-crowd.com and xxxxx","56","Please update a valid external URL. To learn more, see section ""External Link Guidelines"" in Kindle Publishing Guidelines,  or refer to the eBook Manuscript Formatting Guide on Amazon KDP if your book is in Microsoft Word format"
`
The other warnings refer to invalid CSS-settings and can be easily fixed.

**Comment by jgm** [comment]
This doesn't seem to be a bug in pandoc. Pandoc is faithfully creating a link with the URL you supply. You aren't supplying a full absolute URL, and without that URL won't work -- not just in kindlegen but anywhere (you'll see the same problem if you create HTML or docx for example)  -- so you need to fix that in the source.

**Comment by abrey66** [comment]
I agree, especially when you read the external link policies of Amazon ebooks. 
Here however a "normal" user is mildly surprised that in case (1) the importer crashes with no error indication whatsoever, and in case (2) even dot-seperated text (like in math-books) like www.www.www (i.e. no URL) leads to a doc that can be opened (1) but cannot be published (2).

Example of file that can be opened but not published: 

```
## here providing dot-separated strings lead to an URL-assumption

This in turn leads to a rejection to publish the uploaded epub as a kindle-book (mobi,kf8).

here is my www.www.www proof.
```

**Comment by mb21** [comment]
huh, but that's not a link so should be fine? what about marking it up as a code span?

    
here is my `www.www.www` proof.

**Comment by abrey66** [comment]
ok for (2), but do we have to recommend this for every 'dot-seperated' list? You could rather put spaces, especially if you want to achieve the same CSS-format in text and 'list'. 
Do you know what the trigger is? The www or 3 to X items in the a.b.c.d.e string?

**Comment by jgm** [comment]
There is nothing wrong with a link like
```
<a href="www.www.www">hi there</a>
```
But it will link to a file `www.www.www` relative to the local root (and in this case there isn't one, so the link doesn't point anywhere).
