### ISSUE TITLE
Feature request: support for org-mode :ignore: tag

### ISSUE THREAD

**Issue by olivierestsage** [jgm/pandoc#7102]
Using the ox-extra package of Emacs org-mode, one can add the `:ignore:` tag to a headline. This differs from `:noexport:`, which Pandoc already supports, in that it merely prevents the _headline_ itself from being exported. So for example I could have:

```
* Headline 1 :ignore: 
Some text
```

And then when exporting, "Some text" would be exported, but not "Headline 1." 

This feature is very useful for writers, since it allows one to maintain an invisible outline of the text in the org file, but then have this "scaffolding" be omitted from the exported file. Could support for this feature ever be added to Pandoc's handling of org-mode?

(Either way, thank you to everyone involved in making and maintaining Pandoc. It is simply amazing!)

**Comment by tarleb** [comment]
I try to avoid adding support for non-default extensions. But the feature you are looking for can be added via a short [Lua filter](https://pandoc.org/lua-filters.html):

``` lua
function Header (h)
  local ignore = false
  pandoc.walk_block(h, {
    Span = function (s)
      ignore = ignore or s.attributes['tag-name'] == 'ignore'
    end
  })
  return ignore and {} or nil
end
```

Write the filter to file `ox-ignore.lua` and pass it to pandoc via the `--lua-filter=ox-ignore.lua` parameter.

**Comment by olivierestsage** [comment]
Wow, that works beautifully. Thank you so much for taking the time to come up with this solution and explain how to apply it!

**Comment by tarleb** [comment]
No problem, happy to hear that it works!
