### ISSUE TITLE
Building a binary by customize modules from source?

### ISSUE THREAD

**Issue by greyovo** [jgm/pandoc#7106]
I am new to Haskell and Lua. I am wondering if it's possible to build binaries from source by choosing part of the "modules" (e.g. Markdown reader and Word writer...) in order to minimize the size of the pandoc, since I want to use them in my c# projects.

If the answer is yes, how could I accomplish that? It would be nice for any instructions. 

Sorry to bother you but Google Group is banned by my FireFox, so I have to discuss here :)

**Comment by tarleb** [comment]
It would be possible, but quite a lot of work to reduce the executable size by manually disabling all unwanted code. But even then, the resulting binary would still be rather large.

Quoting myself from a [thread on pandoc-discuss](https://groups.google.com/g/pandoc-discuss/c/ab9bWsk0-EI/m/4dhDK_lhBAAJ):

> The question usually arises with the idea of using pandoc for Markdown
> parsing, outputting various other formats. Many large parsers, like
> those for LaTeX and HTML, are dependencies of the Markdown reader, so
> they cannot be removed. The most commonly used writers are also some of
> the most complex, so there is not that much to gain there either.
>
> [I tried this and] I seem to remember that, even after removing a significant amount of
> functionality, I still achieved only a meager 20% reduction in binary
> size. More aggressive pruning should be able to squeeze out some more
> percentage points, but the binary will never really be "small".

**Comment by greyovo** [comment]
Thanks a lot. I am planning to package pandoc in .7z and unpack it while installing. Hope it would works.
Thanks again.

**Comment by jgm** [comment]
@tarleb this reminds me of #6215 which I think is still something we should think about.

**Comment by tarleb** [comment]
Wholeheartedly agree. Maybe I can allocate some time for this next month.
