### ISSUE TITLE
using block quotations inside line blocks

### ISSUE THREAD

**Issue by CircleCode** [jgm/pandoc#7107]
According to [line blocks doc](https://pandoc.org/MANUAL.html#line-blocks)  :

> The division into lines will be preserved in the output, as will any leading spaces; **otherwise, the lines will be formatted as Markdown**.

So I expected the following snippet to produce a block quotation and an indented block quotation.

Otherwise, maybe the doc should mention than only inline markdown is applied, and block formatting is not applied?

```
some normal text

| some text in line blocks
| 
| > This text is
| > expected to be rendered
| > as a _block quotation_
| 
|   > This text is
|   > expected to be rendered
|   > as an indented _block quotation_
```
Produced output:
```
some normal text

some text in line blocks

> This text is
> expected to be rendered
> as a block quotation

  > This text is
  > expected to be rendered
  > as an indented block quotation
```

**Comment by jgm** [comment]
Correct, only inline formatting is allowed in line blocks.
I'll update the manual.
