### ISSUE TITLE
Failing csv-table with double quotes in literal inline block

### ISSUE THREAD

**Issue by PiotrZierhoffer** [jgm/pandoc#7112]
Pandoc version:

```
pandoc 2.11.3
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1
```

Calling `pandoc file.rst` fails if I have a `csv-table` with an inline literal that contains a double quote. 

I did not find any indication of this being illegal.

Sensible example:

```
.. csv-table::

   setting, ``echo PATH="path"``
```

Output:
```
Error at "csv" (line 1, column 22):
unexpected '"'
expecting ",", "\r", "\n", white space or end of input
```

Actual minimal example:

```
.. csv-table::

   ``"``
```

**Comment by jgm** [comment]
Looks like a bug in Text.Pandoc.CSV.
Will fix.
