### ISSUE TITLE
Compilation of beamer presentation fails with pandoc 2.11.4 if the title of a BibTeX entry contains a space at the end

### ISSUE THREAD

**Issue by ChrisWaloszek** [jgm/pandoc#7114]
In a `beamer` presentation generated with R-markdown, Pandoc 2.11.4 does not allow me to compile BibTeX references, which contain (by accident) a space " " at the end of the title of a BibTeX entry.

# MWE

    ---
    output:
      bookdown::pdf_book:
        base_format: rmarkdown::beamer_presentation
        slide_level: 2
        keep_tex: true
    bibliography:
    - ../mybib.bib
    ---

With entry in bibtex file:

    @article{CITEKEY, 
    title = {{Publication title }}, 
    author = {Author Name},
    ...
    year = {2021}
    }

The issue did not occur when using pandoc 2.9.2.1.

**Comment by jgm** [comment]
I can't reproduce the problem using
```
pandoc -t beamer -o my.pdf --bibliography yourbib.bib
# Slide

@CITEKEY

# Refs
^D
```
Please give a simple way to reproduce. (With just pandoc, not rmarkdown.)

**Comment by ChrisWaloszek** [comment]
@jgm based on your test, it looks rather like a `rmarkdown` issue then or is maybe rooted at its interplay with `LaTex beamer` (since the issue does not seem to appear when compiling to other `rmarkdown` output formats, like a bookdown book).
