### ISSUE TITLE
openBinaryFile: does not exist for symlinked filter exectuable

### ISSUE THREAD

**Issue by Konfekt** [jgm/pandoc#7120]
Calling `pandoc --filter=filter`with a filter `filter` which is a symlink in `$PATH` to an executable, `pandoc` complains that `openBinaryFile: does not exist`. Could this symlink be resolved prior to the check for a binary file?

**Comment by jgm** [comment]
I can't reproduce this (macos). It seemed to work fine for me. What OS are you using?  Exact instructions for reproducing?

**Comment by Konfekt** [comment]
I am using Linux, Opensuse 15.2. There is a symlink `pandoc-crossref` in `~/bin` in `$PATH`  to an executable binary `pandoc-crossref` elsewhere. `pandoc  --filter=pandoc-crossref --from test.md --to test.html` for a markdown file `test.md` gives the error message `openBinaryFile: does not exist`.

**Comment by jgm** [comment]
Strange.  That's more or less what I tried.

**Comment by jgm** [comment]
Can anyone else reproduce this?

**Comment by tarleb** [comment]
I tried on Ubuntu 20.04, but couldn't reproduce this either. @Konfekt, can you try with a dummy filter?

```sh
#!/bin/sh
command -v pandoc-crossref 1>&2 # for debugging
cat - | pandoc-crossref --pipe
```

**Comment by Konfekt** [comment]
I am sorry. Thank you for all the help and please pardon the noise. I can no longer reproduce this issue. The symlink now works fine. If it points to a non-executable file, then pandoc correctly complains about a missing executable for the filter. I will close the issue for now.
