### ISSUE TITLE
Markdown feature: generalize abbreviations to not require periods & handle multi-word abbrevs

### ISSUE THREAD

**Issue by gwern** [jgm/pandoc#7124]
Pandoc by default adds non-breaking spaces to preserve titles and other abbreviations when line-breaking, such as "Mr.&nbsp;So-and-so", to avoid linebreaking like "Mr. \n So-and-so". This would be desirable for other abbreviations which are multi-word or period-less---such as the (ultra-common, typically present dozens or hundreds of times in almost all papers) "et al" citation style which is an abbreviation for the Latin _et alii_, for the same reason (it's nicer for citations to move en bloc rather than be split 'Foo \n et al 2020'. For "et al", one would want to handle `Foo et al 2020`,  `Foo et al (2020)`, `Foo et al. 2020`, `Foo _et al_ 2020`, & `Foo _et al._ 2020` (which I believe covers most of the usual variants). Right now, this happens frequently on gwern.net and my typography [has been](https://twitter.com/thaurelia/status/1367450435003555840) criticized for letting citations carelessly linebreak. (I am currently munging the raw HTML because doing a Pandoc filter for this is way harder.)

Unfortunately, the current abbreviation parser apparently cannot handle spaces or period-less abbreviations, matching only `[a-Z]\.` as it were, and so cannot handle any of these; at best, one could add 'al.' and remove just 1 possible linebreak from just 1 variant. ('Foo et al. 2020' could still linebreak at 'Foo et' and 'et al.'.) Generalizing would help other issues like  #3641 (eg 'G. E. Moore').

This is best done with the existing abbreviation facility. "Use citeproc" is not a solution here. I do not know how or if citeproc handles this; but even if it did insert nonbreaking spaces as appropriate, I have many reasons to not use citeproc and it would be absurd overkill to add such a dependency & rewrite my entire corpus of several million words to fix a linebreaking issue, and having don all that, it wouldn't handle all of the *other* possible abbreviations. It is also quite difficult to solve this as a Pandoc filter because Pandoc insists on splitting the `Str` and inserting `Space`, so you cannot simply `walk` over `Str` elements to do a quick regexp search-and-replace (you would need some entirely different iteration pattern which would iterate internally, fusing+pattern-matching `Space`/`Str` sequences... Or something. Just splitting apart `Str` elements and fusing them back together in a subsequent `walk` is quite hard enough when I do that to add smallcaps! It's very unfortunate just how hard it is to do a simple string search-and-replace as a Pandoc filter, and that should probably be its own thing in Text.Pandoc.Walk.)

**Comment by jgm** [comment]
It's partly a performance issue.  Right now we only need to check the abbreviations map when we parse something ending in a period.  Allowing multiword and non-period abbreviations would likely slow things down by quite a lot.

**Comment by jgm** [comment]
I tested and actually we can allow no-period abbreviations without a measurable performance penalty.  Spaces would be harder.

**Comment by jgm** [comment]
> it would be absurd overkill to add such a dependency

Citeproc is no longer an additional dependency.  It is now built into pandoc (the library and executable).  It would certainly require some work to switch, but it might save time in the future.

**Comment by jgm** [comment]
I relaxed the period requirement but after looking into it a bit, I'm not going to allow abbrevs with spaces.

Writing a filter for this is not really very hard.  There's a walk instance for `[Inline]`, so you just need something like

```hs
walk go
 where
 go [] = []
 go (Str "et":Space:Str "al":xs) = Str "et\160al":xs
 go (x:xs) = x : go xs
```

**Comment by gwern** [comment]
I'd expect the performance impact to be minimal. If there is one thing you can do efficiently on a modern computer, it's run a regex automaton over a string. Adding or removing a literal period won't meaningfully affect the cycles-per-character throughput or how far forward the automaton can jump, not compared to everything else going on in Haskell/Pandoc.

Anyway, aside from 'et al', after a little poking, there's also: "loc. cit.", "op. cit.", "S. Rept.", "S. Res.", "nem. con.", "per cent.", "per pro.", "ad. nat. delt.", "An. Sal.", "et ux.", "et vir.", "in litt.", "f. sp.", "in coll.", "sp. nov.", "inter alios", "per mille". I have seen all of these in legal or academic publications at least once before (aside from the two Senate ones), and some are still quite common (loc/op in legal or textual studies, ux/vir in legal papers or obits, and some of them in biology/taxonomy).

(I also noticed that journal names are frequently abbreviated in a similar style like "J. Bio. Res.", but I didn't see any mention of them avoiding linebreaks and I'd guess perhaps in bibliographies there's just not enough space to avoid breaking journal titles. But I could be wrong there, in which case there are a lot of space-separated abbreviations indeed.)

> There's a walk instance for [Inline], so you just need something like

I didn't know that, but it's not too helpful to me because that's still very hard for most uses. A single fixed buggy\* match may be simple to write, but how would you write a *regexp* replacement for that? The Space elements screw with any sort of walk. (And I've found that if you *expand* the AST by adding elements in the walk, things get buggy fast; this has forced me to use Spans and Divs as wrappers just to keep the Pandoc AST the same 'shape' overall.)

\* Note that you don't handle `_et al_` or `_et al.` in your example, you only handle `et al`/`et al.`, so it's incomplete. You also fail to insert two non-breaks, before the 'et' and after the 'al', which means that it'll linebreak anyway at the author & year, and if you try to fix that bug, you can't get away with the `:xs` trick of ignoring after the 'l'. The packing into a single Str element may also surprise any downstream code which assumes that it'll be Space-separated - a mistake I've made already...

> It would certainly require some work to switch, but it might save time in the future.

Nah, it'd be a mess. For references, I have something much better than citeproc: my annotation popup system for fulltext links. (If you haven't seen it in action recently, try mousing on a Wikipedia link on gwern.net sometime - we just got fully-recursive WP popups working.)

**Comment by jgm** [comment]
The ones with a period after each component like "loc. cit." can already be handled just fine: just put each component on a separate line in your abbrevs file.

With "inter alios" I don't think it would be bad to break the line between the words, personally.

For using `walk` on `[Inline] -> [Inline]`; well, don't use regexes, just pattern match:
```
go (Space:Str "et":Space:Str "al":Space:xs) = Str "\160et\160al\160" : go xs
```
Anyway, this kind of thing is not that hard. You'd need another line to handle the variant with punctuation instead of a space at the end, or you could do that with a pattern guard.  (The italicized version will automatically be handled because walk walks the AST.)

**Comment by jgm** [comment]
I guess what you desire would be something like the following:
before parsing any inline element, pandoc would attempt a regex match on the remaining input stream.  If the match succeeds, the matched portion would be consumed and a Str would be parsed with the results of applying a substitution to the matched content.  That would be a lot of regex matching; one would have to measure the performance impact.  Also, currently pandoc doesn't depend on any regex libraries :).

**Comment by jgm** [comment]
I tried an experiment with the regex match idea.  Benchmark:
```
 1279% slower than baseline
```
So yes, there's a pretty big performance impact.

**Comment by gwern** [comment]
> The ones with a period after each component like "loc. cit." can already be handled just fine: just put each component on a separate line in your abbrevs file.

There are words, and thus sentences, that end in 'loc' and 'cit'. ('bloc', 'Ziploc', 'deficit', 'elicit', 'explicit', 'illicit', 'implicit', 'licit'...)

> Anyway, this kind of thing is not that hard.

The entire point of having regexps, instead of writing out a list of literal matches, is that it is that hard. You need an indefinite number of literal matches to match most regexps, they can't be written down as a simple pattern match. The et al examples are about as simple as they can be, and you're still reaching for multiple lines and pattern guards.

What are you going to do for a *real* regexp? It may be best to rule them out of scope for the abbrev functionality, but that still leaves people doing regexp rewrites for all sorts of other reasons high and dry. It's definitely frustrating to reflect how much time I've wasted because of these Space insertions. (It even manages to be a PITA just running examples in ghci because it causes type errors when it clashes with the Space from Data.Char! Eventually had to specifically hide that import in my ghci config so it'd stop getting in the way every time I was debugging something.)

Given that there is apparently a mechanical 1:1 correspondence between a Str with spaces in it and a [Str,Space,Str...] equivalent and that any writer which needs the Space version can thus extract the Space version from the Str version of the AST that the user expects, what exactly is the point of all this Space stuff, anyway? Why does the AST *have* to have this? If it was in Str form, then the user would be able to walk exactly as they'd expect, the abbrevs would be trivial to expand to regexps if necessary, the performance impact would be non-existent (no need for some sort of speculative incremental regexp parsing), and so on.

**Comment by jgm** [comment]
I would not have used Space if I were doing it now.  But changing that now would be a big breaking change in the entire code base and probably many third party tools which interact with pandoc.

**Comment by jgm** [comment]
But here's what you could do to simulate a Space-less AST in your filters.
Create a function like (untested) 

``` hs
walkWithoutSpace :: (Inline -> Inline) -> Pandoc -> Pandoc
walkWithoutSpace f = walk (respace . map f . despace)

despace :: [Inline] -> [Inline]
despace [] = []
despace (Space : Str t : xs) = despace (Str (" " <> t) : xs)
despace (Str t : Space : xs) = despace (Str (t <> " ") : xs)
despace (Str t1 : Str t2 : xs) = despace (Str (t1 <> t2) : xs)
despace (x:xs) = x : despace xs

respace :: [Inline] -> [Inline]
respace [] = []
respace (Str t : xs) = B.toList (B.text t) ++ respace xs
respace (x:xs) = x : respace xs

-- B is Text.Pandoc.Builder
```

Then you can do
``` hs
walkWithoutSpace go
 where
   go (Str " et al") = Str "\160et\160al"
  go x = x
```

**Comment by jgm** [comment]
Though it would probably be more performant to go the other way:  create a function that takes a `(Text, Text)` pair and turns it into an `[Inline] -> [Inline]`, and then just use normal `walk`.

``` hs
textTransform :: (Text, Text) -> [Inline] -> [Inline]
textTransform (from, to) = -- fun exercise?
```
