### ISSUE TITLE
Google Colab installing Pandoc version from 2017 (1.19)

### ISSUE THREAD

**Issue by FowadIjaz** [jgm/pandoc#7126]
Describe the current behavior:
When installing pandoc on google colab, version 1.19.2.4 is installed, which is a release from 2017.

Describe the expected behavior:
The latest Release, which is 2.11, should have been installed. Specifying the version number gives:
`
ERROR: Could not find a version that satisfies the requirement pandoc==2.11 ( from versions: listOfVersions)`

Installing Pandoc on my local version with pip gives the proper latest version

The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

Link (not screenshot!) to a minimal, public, self-contained notebook that
reproduces this issue (click the Share button, then Get Shareable Link):
https://colab.research.google.com/drive/1_9D0MyqRQx1VOgp7YEK9ZviNzbThRkBF?usp=sharing

**Comment by jgm** [comment]
This isn't an issue with pandoc itself, but with google colab (whatever that is), so you should report it there.
