### ISSUE TITLE
Org writer wrap can cause spurious enumerated list in org reader.

### ISSUE THREAD

**Issue by cgevans** [jgm/pandoc#7132]
When a line in input (presumably any input, though I found it using markdown) has a number followed by a full stop in certain columns around the wrap column, and is wrapped by the org writer, the resulting output, when read by the org reader, will have a spurious enumerated list item.  The following self-contained shell command demonstrates the problem, so long as columns and wrap have their default values:

```sh
echo "- This line has exactly the wrong number of characters before the number 5." \
| pandoc -f markdown -t org \
| pandoc -f org -t markdown
```
results in output:

```markdown
-   This line has exactly the wrong number of characters before the
    number
    1.
```

I've found this in 2.12 and 2.9.2.1.

**Comment by tarleb** [comment]
Thanks for the report.
