### ISSUE TITLE
rst comments consume following indented block

### ISSUE THREAD

**Issue by Quantum-cross** [jgm/pandoc#7134]
It seems that pandoc doesn't know when to end an `rst` comment.

The specification for a comment is here: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#comments

It is stated in the section on [empty comments](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#empty-comments) that an empty comment can be used to separate two indented block quotes, or a block quote after an indented list, but this doesn't seem to be working.

Input:

```rst
This is a paragraph.

    This is a block quote.

..

    This should be a second block quote.
```

Command: `pandoc -o html <input.rst>`

Output:

```html
<p>This is a paragraph.</p>
<blockquote>
<p>This is a block quote.</p>
</blockquote>
```

Expected output:

```html
<p>This is a paragraph.</p>
<blockquote>
<p>This is a block quote.</p>
</blockquote>
<blockquote>
<p>This should be a second block quote.</p>
</blockquote>
```

Versions:

```
pandoc 2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.5
```
and
```
>> docker run --rm pandoc/latex:latest --version
pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1
```

**Comment by jgm** [comment]
Here's the part that we're missing:

> Empty Comments. An explicit markup start followed by a blank line and nothing else (apart from whitespace) is an "empty comment". It serves to terminate a preceding construct, and does not consume any indented text following

**Comment by Quantum-cross** [comment]
@jgm But I put an empty comment in my input example, and the second block quote was consumed, no?

**Comment by jgm** [comment]
@Quantum-cross Right, I fixed the bug...see the linked commit.
Did I fix it wrong?

**Comment by Quantum-cross** [comment]
OH I'm sorry I didn't see the commit! Thanks!
