### ISSUE TITLE
default.yaml input-files format issues

### ISSUE THREAD

**Issue by thar0x29a** [jgm/pandoc#7140]
I want to report something that I consider as Bug. 

It is impossible to mix various input types inside of the default.yaml witch I use as general dictionary about my project. F.e. this will fail:
```yaml
input-files:
  - 01-Introduction.md
  - 02-Developing-for-the-Swan.md
  - 03-Graphics.md
  - Appendix-Ports.dokuwiki
```

Even though that the command line would accept .dokuwiki without the `-f format` parameter given, it will be parsed as markdown by now. Simply because the first input file had this format. At least thats my assumption.

**Comment by jgm** [comment]
It's not a bug.  Pandoc converts from one input format to one output format.
There can be multiple input files, but they must be of the same format.

**Comment by tarleb** [comment]
The [include-files](https://github.com/pandoc/lua-filters/tree/master/include-files) Lua filter may come in handy if input files with different formats must be combined.
