### ISSUE TITLE
Docx table 

### ISSUE THREAD

**Issue by twiggler** [jgm/pandoc#7141]
Pandoc version:  2.11.3.2

[broken table.zip](https://github.com/jgm/pandoc/files/6123803/broken.table.zip)

Command: `pandoc --output --to docx reference-doc=custom-reference.docx broken\ table.html`

This produces an invalid docx according to the Open XML Productivity Tool: 
![image](https://user-images.githubusercontent.com/12800443/110806290-34e95b80-8282-11eb-8546-c4a31310be1a.png)

The error is in 
/w:document[1]/w:body[1]/w:tbl[1]/w:tblPr[1]/w:tblW[1]: attribute main:w has invalid value 0.0 The string is not a valid 'Int32' value.

Although Word renders the table ok, I cannot postprocess the document using docx4j.

**Comment by tarleb** [comment]
Fixed in eed18d2
