### ISSUE TITLE
Jira-Reader: Emoticon recognition sometimes leads to empty result

### ISSUE THREAD

**Issue by harmathy** [jgm/pandoc#7143]
Pandoc-Version: 2.11.4 and 2.12

The recognition of Emoticons works, if sanding alone or prefixed with arbitrary characters. However appending letter yields an empty result. When appending whitespace or numbers the output is as expected.

```
$ echo ":D" | pandoc -f jira   
<p>😃</p>
$ echo "C:D" | pandoc -f jira 
<p>C😃</p>
$ echo "C:DE" | pandoc -f jira

$ echo "(/)" | pandoc -f jira
<p>✔</p>
$ echo "A(/) D" | pandoc -f jira 
<p>A✔ D</p>
$ echo "(/)A" | pandoc -f jira

$ echo "A(/)1" | pandoc -f jira 
<p>A✔1</p>
```

In Jira the following

```
:D
C:D
C:DE
(/)
A(/) D
(/)A
A(/)1
```

would be rendered as

```
😃
C😃
C:DE
✔
A✔ D
(/)A
A(/)1
```

In particular `C:DE` would be rendered as plain text.

**Comment by tarleb** [comment]
Thanks for the report.

**Comment by harmathy** [comment]
Thanks for fixing this so quickly!
