### ISSUE TITLE
Metadata from defaults file has very different structure than the same in document header

### ISSUE THREAD

**Issue by gabindu** [jgm/pandoc#7149]
When embedding metadata in a defaults file (under `metadata:`), certain strings end up as a `MetaString` object - whereas the same data defined in the header of a markdown document ends up as `MetaInline`.

When pulling this metadata out in a (python) filter (in fact, this came up for me with using [pandoc-latex-environment](https://github.com/chdemko/pandoc-latex-environment)), using `stringify` works correctly on the `MetaInline` objects, but not on `MetaString` (it returns an empty string), thereby making the filter inoperational.

I've worked around the issue by hardcoding a test for `MetaString` and pulling out the string directly, but it seems to me `stringify` should do this itself.

(Tested with pandoc 2.11 and 2.12, and pandoc-latex-environment 1.1.6.)

**Comment by tarleb** [comment]
Ah, you are using Python, not Lua filters? Python filters have their own repo, the issue should probably be moved there: https://github.com/jgm/pandocfilters.

**Comment by gabindu** [comment]
oops, indeed, you are of course correct, I should have looked at `pandocfilters.py` first.

But, by looking at that, I now better understand the issue, and I believe it is independent of the filter language used: The problem rather arises with the way _metadata is treated differently when coming from the document header as opposed to from a defaults file_. Let me explain more in detail:

Here is a minimal working example with the kind of metadata I need, first directly embedded in the document header (**Case 1**):
```
pandoc-latex-environment:
  noteblock: [note, remark]
```
When sending this through pandoc, it produces the following native AST structure:
```
Pandoc (Meta {unMeta = fromList [("pandoc-latex-environment",MetaMap (fromList [("noteblock",MetaList [MetaInlines [Str "note"],MetaInlines [Str "remark"]])]))]})
```

But when the same metadata is put in a `defaults.yaml` file like this (**Case 2**):
```
metadata:
  pandoc-latex-environment:
    noteblock: [note, remark]
```
it ends up in AST as:
```
pandoc (Meta {unMeta = fromList [("pandoc-latex-environment",MetaMap (fromList [("noteblock",MetaList [MetaString "note",MetaString "remark"])]))]})
```

In both cases, we have a `MetaList` object associated to the "noteblock", but the structure of its content is very different in the two cases:
- in Case 1:  a list of `MetaInlines` objects, each of which contains a **list** of one single `Str` object (where the actual string part is the actual content, after the `Str` type declaration), so one item in the list has the form `MetaInlines [Str "note"]`
- in Case 2: a list of `MetaString` objects, each of which simply has a string as content (no list), so one item of the list has the form `MetaString "note"`.

This means that a filter (no matter the language used, LUA or python) has to deal with these two situations very differently, which I believe to be an unnecessary complication (and rather surprising for the uninitiated, like myself):

In the specific case of using `pandocfilters.py`, applying the `stringify` function to the content of each element of the `MetaList` works correctly in Case 1, but not in Case 2: But looking at the code of `stringify`, I'm not sure it should be changed - rather I think it would make more sense to unify the two cases and have them return at least the same overall structure of data.

There probably are deeper reasons behind all this than my very limited (or rather nonexistant) understanding of pandoc's inner workings allow me to grasp - but I do feel that this is an unnecessary complication which just causes lots of confusion and awkward workarounds. For my specific use, I did find a relatively easy workaround (see my PR for `pandoc-latex-enviroment`), but I can only imagine how many other people will fall into this trap, not realizing where the problem lies...

**Comment by jgm** [comment]
Deeper reason is this:  when we're parsing the defaults file, or command line arguments, we don't know what the input format is going to be. So in these contexts the metadata is parsed as strings rather than e.g. as Markdown.
See the manual under `--metadata`: "Values will be parsed as YAML boolean or string values."
Or the commented example under "Default Files":
```
# metadata values specified here are parsed as literal
# string text, not markdown:
metadata:
```

**Comment by gabindu** [comment]
ok, I understand that. But would it be possible to just slightly change the structure of how the data is returned to avoid case distinctions?

Something like
```MetaMap (fromList [("noteblock",MetaList [MetaInlines [MetaString "note"],MetaInlines [MetaString "remark"])]```
instead of 
```MetaMap (fromList [("noteblock",MetaList [MetaString "note",MetaString "remark"])]```

I apologize if I think about this too naively, but it seems to me that this would still have the same content, but match the structure of what's returned for document-embedded metadata.

**Comment by jgm** [comment]
```
MetaInlines [MetaString "note"]
```
This would be a type error.  `MetaInlines` constructor takes `[Inline]`.

**Comment by gabindu** [comment]
Then I'm confused about why for document-embedded metadata the result is:
```MetaMap (fromList [("noteblock",MetaList [MetaInlines [Str "note"],MetaInlines [Str "remark"]])])```

**Comment by gabindu** [comment]
(thanks for taking the time explaining this, by the way - I'm just trying to understand the different behaviour in these two situations.)

**Comment by jgm** [comment]
Have a look at the types defined here:
https://hackage.haskell.org/package/pandoc-types-1.22/docs/Text-Pandoc-Definition.html
Haskell is a strongly typed language, so there are certain things that can fit into certain slots.
The `MetaInlines` constructor combines with `[Inline]` to yield a `MetaValue`.
But the `MetaString` constructor combinse with `Text` to yield a `MetaValue`.

**Comment by gabindu** [comment]
Ok, thanks for explaining all that. I guess I was hoping that this was all just a design choice which could be changed to uniformize the two situations more.

What would you suggest should be done about this then?  It seems unfortunate to me to leave the distinction between the two cases to the final filter.

Maybe introduce a new abstraction layer in the filter-interface (`pandocfilters.py` in my case), to return the same results no matter where the metadata came from? Or does something like that already exist and I just wasn't aware of it?

**Comment by jgm** [comment]
You want something like `lookupMetaString` in Text.Pandoc.Writers.Shared.

**Comment by gabindu** [comment]
ah, but that doesn't seem to exist (yet) in `pandocfilters.py`, which started this whole chase. In any case, I do have a working workaround for my personal use right now - I just thought this might be worth escalating for the future for other people - but I understand if you deem this unnecessary or impossible. Thanks again for taking the time to look into this.

**Comment by jgm** [comment]
It's certainly not impossible to write a python function that does this -- but I'm not going to do it.  (And I barely maintain pythonfilters.py -- you might look at the more full-featured panflute project.)
