### ISSUE TITLE
Bibliography metadata using a URL with parameter

### ISSUE THREAD

**Issue by Pusnow** [jgm/pandoc#7151]
### Pandoc version
```
$ pandoc -v                                                                               
pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1
User data directory: /Users/pusnow/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

### Problem

[DBLP](https://dblp.uni-trier.de/) offers three  versions of a BibTeX file (standard, condensed, with crossref).
They can be selected by adding `param` (e.g. `https://dblp.uni-trier.de/rec/conf/nsdi/MelletteDGMSP20.bib?param=0` ).
However, pandoc does not understand URLs with parameters, even if they have valid file extensions.

#### With `param` (Not OK)

```
$ pandoc --bibliography=https://dblp.uni-trier.de/rec/conf/nsdi/MelletteDGMSP20.bib?param=0  --citeproc README.md
Could not determine bibliography format for https://dblp.uni-trier.de/rec/conf/nsdi/MelletteDGMSP20.bib?param=0
```

#### Without `param` (OK)

```
$ pandoc --bibliography=https://dblp.uni-trier.de/rec/conf/nsdi/MelletteDGMSP20.bib --citeproc README.md
<p><span class="citation" data-cites="DBLP:conf/nsdi/MelletteDGMSP20">(Mellette et al. 2020)</span></p>
<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-DBLP:conf/nsdi/MelletteDGMSP20" class="csl-entry" role="doc-biblioentry">
Mellette, William M., Rajdeep Das, Yibo Guo, Rob McGuinness, Alex C. Snoeren, and George Porter. 2020. <span>“Expanding Across Time to Deliver Bandwidth Efficiency and Low Latency.”</span> In <em>17th <span>USENIX</span> Symposium on Networked Systems Design and Implementation, <span>NSDI</span> 2020, Santa Clara, CA, USA, February 25-27, 2020</em>, edited by Ranjita Bhagwan and George Porter, 1–18. <span>USENIX</span> Association. <a href="https://www.usenix.org/conference/nsdi20/presentation/mellette">https://www.usenix.org/conference/nsdi20/presentation/mellette</a>.
</div>
</div>
```

**Comment by jgm** [comment]
Workaround: use `https://dblp.uni-trier.de/rec/conf/nsdi/MelletteDGMSP20.bib?param=0&type=.bib`.  As long as the whole URL ends with `.bib`, pandoc will be able to determine its type.

We could think about having pandoc strip off any parameters before looking for the extension, but this should work.

**Comment by mb21** [comment]
In this case, the server even correctly responds with:

    Content-Type: application/x-bibtex

so the actual right thing would be to look at that HTTP header...

**Comment by tillgrallert** [comment]
I have the same issue trying to read a bibliography directly from Zotero through the [Zotero API](https://www.zotero.org/support/dev/web_api/v3/start). One of the output formats is CSL JSON, which works great with Pandora and Citeproc. However, URLs such as ` https://api.zotero.org/groups/904125/items?v=3&q=صحافة&format=csljson` result in the above error. I have searched through the manual but did not find a way to explicitly specify the input format for the bibliography.

**Comment by jgm** [comment]
@tillgrallert As a workaround, you might try added `&type=.json` to the end of the URL and see if that helps.

**Comment by jgm** [comment]
Actually @tillgrallert I see now that the response from that URL is not a JSON array (which pandoc expects) but an object whose `items` property is the array we want. I'll change pandoc to allow this too.

**Comment by tillgrallert** [comment]
Dear @jgm thanks for this quick fix!
