### ISSUE TITLE
Escaping characters in YAML metadata causes the metadata block to be interpreted as a table 

### ISSUE THREAD

**Issue by badumont** [jgm/pandoc#7152]
With pandoc 2.11.4, when a character is escaped in a YAML metadata value, the whole metadata block is turned into a table.

A simple, contrived example:
```
$ pandoc -s -t native  <<< '
---
title: "Writing emphasis in Markdown like \*this\*"
---
'
Pandoc (Meta {unMeta = fromList []})
[Table ("",[],[]) (Caption Nothing
 [])
 [(AlignDefault,ColWidthDefault)]
 (TableHead ("",[],[])
 [])
 [(TableBody ("",[],[]) (RowHeadColumns 0)
  []
  [Row ("",[],[])
   [Cell ("",[],[]) AlignDefault (RowSpan 1) (ColSpan 1)
    [Plain [Str "title:",Space,Quoted DoubleQuote [Str "Writing",Space,Str "emphasis",Space,Str "in",Space,Str "Markdown",Space,Str "like",Space,Str "*this*"]]]]])]
 (TableFoot ("",[],[])
 [])]
```

A more complex, real-world example:
```
$ pandoc -s -t native  <<< '
---
title: "The \string command in TeX"
---
'
Pandoc (Meta {unMeta = fromList []})
[Table ("",[],[]) (Caption Nothing
 [])
 [(AlignDefault,ColWidthDefault)]
 (TableHead ("",[],[])
 [])
 [(TableBody ("",[],[]) (RowHeadColumns 0)
  []
  [Row ("",[],[])
   [Cell ("",[],[]) AlignDefault (RowSpan 1) (ColSpan 1)
    [Plain [Str "title:",Space,Quoted DoubleQuote [Str "The",Space,RawInline (Format "tex") "\\string ",Str "command",Space,Str "in",Space,Str "TeX"]]]]])]
 (TableFoot ("",[],[])
 [])]
```

```
$ pandoc -s -t native  <<< '
---
title: "The \\string command in TeX"
---
'
Pandoc (Meta {unMeta = fromList [("title",MetaInlines [Str "The",Space,RawInline (Format "tex") "\\string ",Str "command",Space,Str "in",Space,Str "TeX"])]})
[]
```
(Causes "\string" to be stripped in formats other than *tex.)

```
$ pandoc -s -t native  <<< '
---
title: "The \\\string command in TeX"
---
'
Pandoc (Meta {unMeta = fromList []})
[Table ("",[],[]) (Caption Nothing
 [])
 [(AlignDefault,ColWidthDefault)]
 (TableHead ("",[],[])
 [])
 [(TableBody ("",[],[]) (RowHeadColumns 0)
  []
  [Row ("",[],[])
   [Cell ("",[],[]) AlignDefault (RowSpan 1) (ColSpan 1)
    [Plain [Str "title:",Space,Quoted DoubleQuote [Str "The",Space,Str "\\",RawInline (Format "tex") "\\string ",Str "command",Space,Str "in",Space,Str "TeX"]]]]])]
 (TableFoot ("",[],[])
 [])]
```

**Comment by tarleb** [comment]
What you are seeing is due to the interaction of Markdown and YAML. At a high level, what happens is

1. Pandoc tries to read the input as YAML, but YAML parsing fails (see below for why).
2. Pandoc falls back to parsing the input as a Markdown block, thus producing a table.

Now the reason that YAML parsing fails is that a backslash is used for escape sequences like `\t` for a tab and `\n` for a newline. However, `\*` and `\s` are invalid escape sequences, so the input is not valid YAML. You can test this with a YAML validator, e.g. [here](https://yamlvalidator.com/).

Therefore, the solution is to use *two* backslashes to escape Markdown characters in YAML, or *four* if you need to escape a backslash as you in the real-world example.

**Comment by badumont** [comment]
Thanks a lot! I know that the manual already contains the sentence "YAML escaping rules must be followed", but maybe adding something like "backslash escapes must be double-escaped" and illustrating it in the example below could help?

**Comment by jgm** [comment]
YAML escaping rules are actually pretty complex, but maybe we could link to the right part of the YAML text or something more instructional?

**Comment by agusmba** [comment]
https://yaml.org/spec/1.2/spec.html#id2776092 ?

> Note that escape sequences are only interpreted in double-quoted scalars. In all other scalar styles, the “\” character has no special meaning and non-printable characters are not available.
