### ISSUE TITLE
JSON parse error: Error in $: Failed reading: satisfy. Expecting object key at 'anchor:anchorname}'

### ISSUE THREAD

**Issue by shapel** [jgm/pandoc#7157]
Hello 
First of all thanks for the greate tool!

Below you can find examples of failed behavior
* pandoc version: 2.12
* command:
`echo "{anchor:anchorname}" | pandoc -f jira -f json`
fail with `JSON parse error: Error in $: Failed reading: satisfy. Expecting object key at 'anchor:anchorname}'`

But other output formats work well (like `echo "{anchor:anchorname}" | pandoc -f jira -f html`).

**Comment by mb21** [comment]
you have a typo in your example: `pandoc -f jira -f json` should be `pandoc -f jira -t json`

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
