### ISSUE TITLE
Pandoc is missing a LaTeX run with biblatex

### ISSUE THREAD

**Issue by adnion** [jgm/pandoc#7158]
#### Error
```
Warning message:
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please rerun LaTeX.
```

#### Biblatex issue
"So I don't think this is primarily a biblatex issue. pandoc should simply run XeLaTeX the required number of times."
https://github.com/plk/biblatex/issues/1109#issuecomment-802116941

#### Steps to reproduce (from above issue)
I minimized the code to 2 short files:
index.Rmd https://dpaste.org/tC0b
book.bib https://dpaste.org/GHKA
Save both files into an empty directory
start R and run `bookdown::render_book('index.Rmd', 'bookdown::pdf_book')`

Thank you

**Comment by jgm** [comment]
It's helpful if you can give a reproducible case that doesn't involve other software than pandoc.  I don't even have R installed.  And if we are running other software, then it's hard to know for sure if the issue is in pandoc.

**Comment by jgm** [comment]
In fact, it can't be a pandoc issue. Pandoc doesn't run biblatex at all in producing a PDF.  So I'd report this to RStudio or whoever it is who is responsible for bookdown.
