### ISSUE TITLE
Typo in the Pandoc Lua filters documentation

### ISSUE THREAD

**Issue by Polirecyliente** [jgm/pandoc#7159]
In the Pandoc Lua filters documentation available at https://pandoc.org/lua-filters.html, it says:

> "The return of a filter function must one of the following:"

Which is wrong, it should read:

> "The return of a filter function must be one of the following:"

The missing verb is "be", which is necessary in that place to say that the following 3 returns of a filter function, are the valid ones.

**Comment by jgm** [comment]
Thanks. If you want, you can easily create a pull request by editing
https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md
(click the edit button, then make your change, and there's a convenient button at the bottom to create a new branch for a PR).

**Comment by Polirecyliente** [comment]
Thanks to @TatianaPorras aka La Tats xD ... next time I'll just send the Pull Request directly.
