### ISSUE TITLE
Lists in beamer presentations are incremental by default

### ISSUE THREAD

**Issue by nluetts** [jgm/pandoc#7160]
When I convert a Markdown document to a PDF presentation via pdflatex and the `-t beamer` argument, the bullet point lists in the generated PDF are not displayed all at once but incrementally. That is, something like this

```markdown
# My presentation

- first point
- second point
```
is translated into a PDF with two slides, the first one only showing "first point", when I do:

```
pandoc -t beamer -i minimal.md -s -o slides.pdf --pdf-engine pdflatex
```

According to the pandoc docs, lists should be displayed all at once by default:

> `-i, --incremental`
> Make list items in slide shows display incrementally (one by one). **The default is for lists to be displayed all at once.**

This is the behavior I want.

I know that I can use divs like that:

```markdown
# My presentation

::: nonincremental
- first point
- second point
:::
```

to force the list elements to be displayed all at once, but I do not want to include this extra text everywhere in my Markdown document. I would rather have it like it is described in the docs, since there does not seem to be a way to switch off the incremental list behavior using a command line argument.

My pandoc version:
```
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```
My pdflatex version:
```
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
[...]
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```

My beamer version:
```
beamer 2019/09/29 v3.57
```
Thanks! (And thank you for the all-mighty Pandoc :smile:)

**Comment by jgm** [comment]
I can't reproduce this with pandoc 2.12.
Try upgrading?

**Comment by nluetts** [comment]
Thanks for the prompt answer. I fell for `apt` not upgrading (pandoc 2.5 seems to be the latest version in the official repositories for Linux Mint --- I am using Linux Mint 20.1).

I downloaded the latest .deb and installed it. Now `pandoc --version` yields:
```
pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1
```

Unfortunately, that did not solve the problem. My PDF still has two slides ...

**Comment by jgm** [comment]
What's the full command you're using?

**Comment by jgm** [comment]
Oh, I see you gave it above. You're using `-i`.  That's what causes this.
Drop the `-i` and you'll get the default behavior.

**Comment by jgm** [comment]
You quoted the docs for `-i` but seem to have misunderstood them:

> Make list items in slide shows display incrementally (one by one). The default is for lists to be displayed all at once.

`-i` creates a non-default behavior, where lists display incrementally.  The default (i.e., non-`-i`) behavior is what you want.

**Comment by nluetts** [comment]
My my, you are right, I misused the `-i` flag :roll_eyes:. Not because I misunderstood the docs, but because I was instinctively trying to use the `ffmpeg` way of defining input and output, where `-i` defines the input file and `-o` the output file (I was using `ffmpeg` not long ago). I was blind to the double (and wrong) use of `-i` here.

It works now, thank you very much for making me see my mistake.
