### ISSUE TITLE
Using default HTML template and getting openBinaryFile error in Pandoc V2.12

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#7164]
I first create a new default.html template, then try to pass it to Pandoc:

```
pandoc -D html > $HOME/Desktop/default.html
pandoc --template=$HOME/Desktop/default.html
```

I get this error:

```
pandoc: /Users/ian/Desktop/styles.html: openBinaryFile: does not exist (No such file or directory)
```

It is treating $styles.html()$ as a real file:

```
   <style>
       $styles.html()$
   </style>
```

❯ pandoc --version
pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1
User data directory: /Users/ian/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

**Comment by jgm** [comment]
Hm.  The manual says

> If a partial is not found in the directory of the template, it will also be sought in the templates subdirectory of the user data directory.

It doesn't say explicitly that, if the partial is not found there either, it will be taken from the default data files -- but that is a reasonable expectation, and that is how it *should* work.

**Comment by jgm** [comment]
Is this a regression?  Can you confirm different behavior in earlier pandoc versions that have partials?

**Comment by jgm** [comment]
OK, should now be fixed.

**Comment by iandol** [comment]
Thanks Jon, I'm sorry but I didn't remember seeing this in a previous version, but didn't confirm it was a regression. My minimal test case above used the default html template without any other customisation, and your fallback solution should cover this case 👍🏽
