### ISSUE TITLE
HTML writer should use an ordered list for table of contents

### ISSUE THREAD

**Issue by benjamin-hodgson** [jgm/pandoc#7166]
Currently the HTML writer outputs a `ul` for the table of contents. I'd like to suggest changing it to output an `ol` instead. `ol` is significantly better markup for a table of contents (being naturally ordered) and makes for better compatibility with screen readers and such.

Concretely it looks like this would be as straightforward as changing
https://github.com/jgm/pandoc/blob/c389211e2f678d9327cd2c008d54a1e438f07a07/src/Text/Pandoc/Writers/HTML.hs#L442
to
```haskell
    BulletList l@(_:_) -> Just <$> blockToHtml opts' (OrderedList l)
```

**Comment by jgm** [comment]
The reason we don't do this is that the numbers provided by the ol may clash with the section numbering  (e.g. 1.2.1) added by pandoc with `--number-sections`.
