### ISSUE TITLE
Allow HTML TOC generation on the fly, without using standalone page

### ISSUE THREAD

**Issue by vatonbero** [jgm/pandoc#7169]
Hi all,

I am using pandoc version `2.11` and i was wondering is it planned or drafted option to create table of contents (TOC) on HTML pages while exporting only body and not whole standalone page, with `<HEAD>`, `<HTML>` etc? At the moment, we have to use `-s` (standalone) for exporting TOC on HTML pages but that is not ideal because `-s` creates fully standalone page in HTML.

This is not ideal because if you are piping some contents through pandoc and you expect only HTML without headers, footers and everything outside body, you will get double headers and footers.

Example:
```
some_random_command_producing_and_filtering_markdown | pandoc -s --toc --toc-depth=6 --from=markdown --to=html5
```

This will produce HTML file only as pandoc intended and it will include <HEAD> in HTML. I guess this can be done on the fly by using `$body$` var (??) where you can get only everything between `<BODY>` and `</BODY>` but i found no ways to do that inline.

**Comment by mb21** [comment]
You can use a [custom template](https://pandoc.org/MANUAL.html#templates)...

**Comment by vatonbero** [comment]
> You can use a [custom template](https://pandoc.org/MANUAL.html#templates)...

Thank you for this. It is less ideal since you have to prepare something in advance, in this case template, instead of just calling the command.

**Comment by jgm** [comment]
This is a really simple customization, though. Create a template withtoc.html
```
<nav id="$idprefix$TOC" role="doc-toc">
$if(toc-title)$
<h2 id="$idprefix$toc-title">$toc-title$</h2>
$endif$
$table-of-contents$
</nav>
$body$
```
and put it in your user data directory.  Then you just have to say `pandoc --template withtoc -t html`.
