### ISSUE TITLE
Support toc-title in revealjs

### ISSUE THREAD

**Issue by fkohrt** [jgm/pandoc#7170]
Among other HTML formats, the HTML5 template includes the content of `toc-title` as heading:

https://github.com/jgm/pandoc/blob/99e1b67b74ddcbf7ffc8add640493f73471cf50a/data/templates/default.html5#L54-L61

Is there any reason against doing something similar for `revealjs`? Otherwise there's only an untitled slide containing the TOC, which doesn't look appealing.

**Comment by jgm** [comment]
Yes I think we could do the same for `revealjs`.

**Comment by fkohrt** [comment]
Done. Wasn't sure about the heading level, but went for `h2` as with `html5`. I also copied the `nav`, but in a separate commit in case you'd rather not have this in there.
