### ISSUE TITLE
Exporting from DocBook to PDF or HTML: no equations rendered

### ISSUE THREAD

**Issue by dourouc05** [jgm/pandoc#7173]
When generating DocBook documents with maths in equations (written in MathML), the math content is lost during the conversion when some specific namespace prefixes are used (or even with inline prefixes). Currently, Pandoc has no problems with this form (wherever `mml` is defined): 

```xml
    <informalequation>
        <alt role='tex'>1+2</alt>
        <mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML">
            <mml:mrow>
                <mml:mrow><mml:mn>1</mml:mn><mml:mo>+</mml:mo><mml:mn>2</mml:mn>
                </mml:mrow>
            </mml:mrow>
        </mml:math>
    </informalequation>
```

However, when the prefix is `m` or simply inline (directly with `xmlns`), Pandoc no more recognises the math: 

```xml
    <informalequation>
        <alt role='tex'>1+2</alt>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <mrow>
                <mrow><mn>1</mn><mo>+</mo><mn>2</mn>
                </mrow>
            </mrow>
        </math>
    </informalequation>
```

```xml
    <informalequation>
        <alt role='tex'>1+2</alt>
        <m:math>
            <m:mrow>
                <m:mrow><m:mn>1</m:mn><m:mo>+</m:mo><m:mn>2</m:mn>
                </m:mrow>
            </m:mrow>
        </m:math>
    </informalequation>
```

Ideally, Pandoc should understand the `xmlns` directives and decide if it's MathML based on the namespace that is being prefixed.

I am attaching five test cases with different ways the name spaces are handled in XML in general (including complete examples of which I show excerpts above):

[DocBook.zip](https://github.com/jgm/pandoc/files/6185940/DocBook.zip)
[HTML.zip](https://github.com/jgm/pandoc/files/6185941/HTML.zip)

Here is my version of Pandoc: 

```
PS C:\Users\Thibaut\AppData\Local\Pandoc> pandoc -v
pandoc.exe 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1
User data directory: C:\Users\Thibaut\AppData\Roaming\pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by mb21** [comment]
Can reproduce with newest version in [try pandoc](https://pandoc.org/try/?text=++++%3Cinformalequation%3E%0A++++++++%3Calt+role%3D%27tex%27%3E1%2B2%3C%2Falt%3E%0A++++++++%3Cmath+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1998%2FMath%2FMathML%22%3E%0A++++++++++++%3Cmrow%3E%0A++++++++++++++++%3Cmrow%3E%3Cmn%3E1%3C%2Fmn%3E%3Cmo%3E%2B%3C%2Fmo%3E%3Cmn%3E2%3C%2Fmn%3E%0A++++++++++++++++%3C%2Fmrow%3E%0A++++++++++++%3C%2Fmrow%3E%0A++++++++%3C%2Fmath%3E%0A++++%3C%2Finformalequation%3E&from=docbook&to=native&standalone=0)

**Comment by jgm** [comment]
Thanks for the excellent report!
