### ISSUE TITLE
Underscore inside URL inside LaTeX \caption cause LaTeX commands to be escaped

### ISSUE THREAD

**Issue by rgaiacs** [jgm/pandoc#7175]
Consider the following minimal working example:

```
$ cat mwe.md
\begin{figure}

{\centering \includegraphics{pressure-1} 

}

\caption{ https://github.com/foobar}(\#fig:pressure)
\end{figure}
```

When converting the Markdown file to LaTeX, Pandoc will  produce

```
$ pandoc --from markdown --to latex mwe.md
\begin{figure}

{\centering \includegraphics{pressure-1} 

}

\caption{ https://github.com/foobar}(\#fig:pressure)
\end{figure}
```

The output is as expected. Let's change `https://github.com/foobar` to `https://github.com/foo_bar` and see how Pandoc will handle the change:

```
$ cat mwe.md
\begin{figure}

{\centering \includegraphics{pressure-1} 

}

\caption{ https://github.com/foo_bar}(\#fig:pressure)
\end{figure}
$ pandoc --from markdown --to latex mwe.md
\textbackslash begin\{figure\}

\{\centering \includegraphics{pressure-1}

\}

\textbackslash caption\{ https://github.com/foo\_bar\}(\#fig:pressure)
\textbackslash end\{figure\}
```

The underscore, `_`, in the URL is responsible for Pandoc to escape all the special LaTeX annotation.

I encounter this bug when I included the address of one Wikipedia article that had `_`. From [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Linking_to_Wikipedia):

> Links for articles which have spaces in their titles replace those spaces with underscores; for Top Cat, for example, the URL is https://en.wikipedia.org/wiki/Top_Cat

**Comment by jgm** [comment]
Is this a bug? If you try to compile this with LaTeX, it will complain in exactly the same place pandoc does ; `_` outside of math mode (or other special environments) needs to be escaped.  So pandoc is behaving quite properly.

For better results, use `\url{https://github.com/foobar}` in your caption.
