### ISSUE TITLE
metadata support for letter postscript

### ISSUE THREAD

**Issue by brainchild0** [jgm/pandoc#7178]
Requested is a convention for placing postscript text, for formatting a letter, in metadata, as well as possibly related text, such as a post-postscript. Such convention might be analogous to the current handling of text for an abstract in articles and books.

A basic implementation of the request would be simply to process a new metadata field called `postscript`.

**Comment by tarleb** [comment]
I'd say that this a relatively specialized use-case and hence the responsibility of templates like [pandoc-letter](https://github.com/aaronwolen/pandoc-letter) and [pandoc-letter-din5008](https://github.com/benedictdudel/pandoc-letter-din5008).

We generally try to prevent the proliferation of variables -- so with that in mind, I'm closing this.
