### ISSUE TITLE
Quotation mark conversion not working when quote mark is followed by another character

### ISSUE THREAD

**Issue by tamas-ferenci** [jgm/pandoc#7190]
Here is a minimal reproducible example:

```
„a" and „b"
```

is correctly converted to

```
„a" and „b"
```

by `pandoc -f markdown -t latex`. However

```
„a", „b"
```

gets converted to

```
„a``, „b''
```

i.e., the conversion is derailed by the comma. (Actually, it seems that by any character, `„a"x „b"` has the same problem.)

**Comment by tarleb** [comment]
Here is how pandoc parses the two examples:

``` haskell
[Para [Str "\8222a\"",Space,Str "and",Space,Str "\8222b\""]
,Para [Str "\8222a",Quoted DoubleQuote [Str ",",Space,Str "\8222b"]]]
```

So in the second case, pandoc treats the "normal" `"` characters as delimiters for quoted text. To prevent this from happening, one can use a backslash escape to force the literal handling of a character:

    „a\", „b\"

You could also disable the smart handling of quotes with `-f markdown-smart` or try to use `-f commonmark_x`, which is a lot like `markdown`, but doesn't support smart quotes.

**Comment by jgm** [comment]
To echo this: if you're entering unicode quote characters directly, especially for a non-English quoting style, then you probably want to disable `smart`.

PS. `commonmark_x` does support `smart` by default, though you can disable it there too.  Or use basic `commonmark`.

**Comment by tarleb** [comment]
Oh, right. I had made a mistake while testing. Thanks for the correction.

**Comment by jgm** [comment]
One possible improvement might be to change the "open double quote" recognizer so that it isn't triggered when the open quote is followed by a comma, period, semicolon, colon, question mark, or exclamation point.  But what if someone wants to write
```
There are several punctuation marks to watch out for: ",", ".", and ";" are especially problematic.
```
It may be that this issue requires no action and can be closed.

**Comment by tamas-ferenci** [comment]
Thank you very much! While it could be really a - minor - improvement, your suggestion with escaping works, and also, I realized, that we could simply write `„a”, „b”` which also works. Thanks again!
