### ISSUE TITLE
pandoc does not recognize latex control sequence \ket

### ISSUE THREAD

**Issue by piggypiggy** [jgm/pandoc#7192]
minimal example:

`\documentclass{article}`
`\usepackage{braket}`
`\begin{document}`
`$\ket{0}$`
`\end{document} `

I use pandoc to generate .docx file from .tex file:
`pandoc z.tex -o z.docx`
or
`pandoc z.tex -o z.docx --pdf-engine xelatex`

Pandoc says:
> [WARNING] Could not convert TeX math '\ket{0}', rendering as TeX:
  \ket{0}
       ^
  unexpected control sequence \ket
  expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace

In z.docx, pandoc does not produce ket notation `|0>` but `$\ket{0}$`.

I downloaded pandoc-2.13-windows-x86_64.msi then installed it.
> pandoc -v
pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1

**Comment by jgm** [comment]
We can't support every LaTeX package out there; we try to support some of the most common ones, but for anything outside that, you can always include a macro definition and pandoc will interpret it.

**Comment by piggypiggy** [comment]
`\def\ket#1{|{#1}\rangle}` looks good. Thank you.
