### ISSUE TITLE
role attribute in DocBook <phrase> elements not picked up

### ISSUE THREAD

**Issue by bigsmoke** [jgm/pandoc#7195]
pandoc 2.13  doesn't pick up `role` attributes from `<phrase>` elements. Looking at [`DocBook.hs` line 1076](https://github.com/jgm/pandoc/blob/40da6c402beb64e47838254c04228098129165df/src/Text/Pandoc/Readers/DocBook.hs#L1076) it appears to my non-Haskell-savvy brain that pandoc wrongly looks for a `<phrase class>` instead of the `<phrase role>` attribute.

Gentle reminder: DocBook generally uses `role` where for example HTML uses `class`.

Thank you for this great product, by the way!

**Comment by jgm** [comment]
Sure, I'll make the change. Pinging @mboes (#6438) to make sure there's nothing I'm overlooking.

**Comment by Thoma5** [comment]
@jgm if phrase is already picked up and now even the role attribute, isn't this a step towards the solution of #3657?

**Comment by bigsmoke** [comment]
Thanks a lot for addressing this, and so quickly too! 😄

**Comment by de103252** [comment]
Quite new to Pandoc and to Haskell, so bear with me. I am trying to apply a custom paragraph style for Docbook block elements that have a role attribute. For inline elements such as "phrase", this works: I can intercept the Span and can add the custom style (as soon as I have grokked Lua, that is).

For block elements, however, it does not work. The parseMixed function does not care about the Docbook "role" attribute, as far as I can tell without really understanding the Haskell code.
If it did work, it would in fact solve https://github.com/jgm/pandoc/issues/3657, I believe?! The problem addressed there is precisely the one I am trying to solve myself.

Thanks!

**Comment by jgm** [comment]
If there is a particular block-level element for which you'd like `role` to be parsed as `class`, we could do that, provided the corresponding pandoc Block element actually has a slot for attributes. (Only some do.)
Div is a generic block container that can take attributes, so if there were something like `<div>` in docbook, which would be like `<phrase>` but for block-level content, we could implement this for that.

In any case best to request this in a new issue (with a pointer to this one).

**Comment by de103252** [comment]
Thanks @jgm for the quick reply. Actually, my Docbook in turn is the output of AsciiDoctor so I don't have freedom in choosing the elements. In my case, I'm dealing with a simpara element, which is "A paragraph that contains only text and inline markup, no block elements."
Not being Haskell savvy, I don't yet grok what you mean by "the corresponding pandoc Block element actually has a slot for attributes". Anyway, I will open a new issue as suggested, in the hope I can phrase it in a way that makes sense.
