### ISSUE TITLE
creating self-contained HTML messes with layout in v2.12, but not in v2.10

### ISSUE THREAD

**Issue by leraman** [jgm/pandoc#7197]
Using `pandoc x.html --output y.html --from markdown --self-contained` transforms x.html to self-contained y.html with the exact same layout in v2.10. In v2.12 however,  the content of y.html seems 'compressed' towards the center instead of spread across the page width (screenshots below). I'm guessing this is a bug?

Thanks!

Lennart

![Screenshot 2021-04-02 at 12 22 16](https://user-images.githubusercontent.com/15171833/113407696-1de3e800-93ae-11eb-9f82-e539d682a37c.png)
![Screenshot 2021-04-02 at 12 15 09](https://user-images.githubusercontent.com/15171833/113407697-1f151500-93ae-11eb-9d1a-989379d1957b.png)

**Comment by mb21** [comment]
Hard to say what's going on without having the input file... (or better, a minimal reproducible example)
But if `x.html` is you input file... why do you use `--from markdown`?

**Comment by leraman** [comment]
I'm not sure, but without `--from markdown` the output is empty. Might be markdown format in reality. Anyway, the non-self-contained input files are included in attachment (both should be unzipped). I'm using:

`pandoc hopla.html --from markdown --self-contained --output hopla-sc.html`

Thanks for your help!

Lennart

[hopla_files.zip](https://github.com/jgm/pandoc/files/6249920/hopla_files.zip)
[hopla.html.zip](https://github.com/jgm/pandoc/files/6249930/hopla.html.zip)

**Comment by jgm** [comment]
It could be because of the changes in the default CSS.
Try with `--css` and pandoc's old default CSS?

**Comment by leraman** [comment]
I've no idea what's going on, but apparently, providing an empty file with `--css` solves the issue.

**Comment by leraman** [comment]
I've no idea what's going on, but apparently, adding `-css` with an empty file fixes my issue

**Comment by jgm** [comment]
The new default CSS added in pandoc 2.12 specifies a maximum text width, which could be responsible for what you're seeing. In any case, the thing to do is to modify a copy of the default CSS, removing the features you don't want, and pass that in with `--css`.

**Comment by hftf** [comment]
Out of curiosity, would it be possible to start using a GitHub label for any issues related to the new default CSS (since 2.12)? I was doing some research on its impact.

**Comment by mb21** [comment]
@hftf could do that... or probably you're going to find most with the [tag combination `format:HTML` and `templates`](https://github.com/jgm/pandoc/issues?q=is%3Aissue+label%3Aformat%3AHTML+label%3Atemplates)

**Comment by hftf** [comment]
@mb21 Thanks, that is helpful!
