### ISSUE TITLE
Option --print-default-data-file does not find the referenced docx file

### ISSUE THREAD

**Issue by castella-hb** [jgm/pandoc#7204]
### Pandoc version
> pandoc 2.13
> Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
> citeproc 0.3.0.9, ipynb 0.1.0.1

### OS version
> macOS version 11.2.3

### Error message when using the command
>pandoc -o custom-reference.docx --print-default-data-file=my-reference-template.docx --resource-path=.
>Could not find data file my-reference-template.docx

### Comments
- pandoc was invoked in the working directory where the my-reference-template.docx is also located
- The original docx template file my-reference-template.docx contains macros that cannot be deleted
- The conversion from HTML to docx using the original docx template file my-reference-template.docx works in general:
> pandoc --reference-doc my-reference-template.docx -o index.docx index.html --log=pandoc.html2docx.log

**Comment by jgm** [comment]
This option is for printing *default* data files, i.e., those that come with pandoc itself.
It isn't for printing custom data files like `my-reference-template.docx`.
