### ISSUE TITLE
apostrophe's within citations

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#7206]
In author-year citations, it'd be nice to be able to include apostrophes like this:

> as well as @Sanger2014hwc's interest in...

instead of needing to:

> as well as Sanger's [-@Sanger2014hwc] interest in...

**Comment by jgm** [comment]
Note: This is specifically for the author-in-text form.

**Comment by jgm** [comment]
You can now do (in the dev version) `@{Sanger2014hwc}'s interest.`
I think this resolves this issue, so closing.

**Comment by reagle** [comment]
Curly brackets in citations!? Looks like a big change. I'm excited to see and thanks for the feature.

**Comment by reagle** [comment]
BTW: see #6026 .

**Comment by reagle** [comment]
Hi, this might be buggy yet on 2.14.0.2 (issues #7206 & #6026).

First, I expect the apostrophe to be on the last last name. Also, if there's another apostrophe in the sentence, the smart punctuation is backwards.

https://reagle.org/joseph/2016/04/min-eg/cite-apostrophe.md ->

https://reagle.org/joseph/2016/04/min-eg/cite-apostrophe.html

**Comment by jgm** [comment]
Open new issues for these if you like. Here it will just be forgotten.
