### ISSUE TITLE
Markdown writer swallows non-breaking spaces

### ISSUE THREAD

**Issue by khenriks** [jgm/pandoc#7207]
I use pandoc to create man pages, which display 2 spaces after periods when viewed in my terminal. This does not work for names like "A. B. Lastname", and so I use a non-breaking space (`\ `) instead of a normal space to suppress this. However, the markdown writer does not preserve these non-breaking spaces. This means pandoc does not pass through such files (read then write) cleanly.

Input:
```
A.\ B.\ Lastname
```

Command: `pandoc -f markdown -t markdown input.md`

Expected output:
```
A.\ B.\ Lastname
```

Actual output:
```
A. B. Lastname
```

This is with pandoc version 2.13, and I believe has also been present in previous versions.

**Comment by jgm** [comment]
Are you sure you don't have a UTF-8 nonbreaking space there?
This shows that nonbreaking spaces are correctly round-tripped through markdown:
```
% pandoc -f native -t markdown | pandoc -f markdown -t native
[Para [Str "A.\160B.\160Last"]]
[Para [Str "A.\160B.\160Last"]]
```

**Comment by khenriks** [comment]
Oh, actually you are completely right. The output is a unicode non-breaking space. Is there any way to make it emit that `\ ` again on the output?

**Comment by jgm** [comment]
Sorry, no. You could pipe it through sed or something.
This could also be done using a Lua filter that intercepts Str elements containing `'\160'` and emits a RawInline.
