### ISSUE TITLE
gfm writer emits HTML entities instead of escaped punctuation

### ISSUE THREAD

**Issue by khenriks** [jgm/pandoc#7208]
To write punctuation characters, the gfm writer seems to be using HTML entities (e.g. `&gt;`) instead of a native markdown construction like `\>`. Per [the spec](https://github.github.com/gfm/#backslash-escapes), these backslash escaped constructions are supported, and it seems like it would be better to use a native markdown representation.

Input:
```
some \< text \>
```

Command: `pandoc -f gfm -t gfm input.md`

Expected output:
```
some \< text \>
```

Actual output:
```
some &lt; text &gt;
```

This is present in pandoc 2.13, and this specific behavior changed in d6b7b1d.

**Comment by khenriks** [comment]
Based on a bit of investigation, it appears that this output is governed by the `all_symbols_escapable` extension: https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/Markdown/Inline.hs#L50

It appears that configuring that extension for gfm was disabled in 3a22fbd on the basis that it is always enabled and cannot be disabled, but that appears not to be the case.

**Comment by jgm** [comment]
It's true that it can't be enabled/disabled, but we need the writer to act as if it's enabled. This should be an easy fix.
