### ISSUE TITLE
Some HTML tables with <th> Mangled in Pandoc Markdown > HTML Conversion

### ISSUE THREAD

**Issue by dubsarGimillu** [jgm/pandoc#7209]
I use pandoc to wrap front matter and end matter around contents coded in HTML + YAML and saved as a markdown file.  Some HTML tables in markdown files with <th> tags are mangled on conversion to plain HTML.  

**Example:** 
garments.md follows

```
---
title: Garments
author: Hannibal Barca
lang: en
---

this is a paragraph coded in markdown

<table>
	<tr>
		<th>Garment</th>
		<th>Layers</th>
		<th>Weight</th>
		<th>Made</th>
		<th>Source</th>
	</tr>
	<tr>
		<td>a garment</td>
    		<td>some layers</td>
    		<td>M</td>
    		<td>2×?</td>
    		<td>a source</td>

    	<tr>
    		<td>another garment</td>
    		<td>other layers</td>
    		<td>L</td>
    		<td>1×</td>
    		<td>another source</td>
    	</tr>
</table>`

```
`pandoc garments.md -s -o garments.html`

garments.html follows (I snip everything outside the body tag since we can't attach HTML files):
```
...
<body>
<header id="title-block-header">
<h1 class="title">Garments</h1>
<p class="author">Hannibal Barca</p>
</header>
<p>this is a paragraph coded in markdown</p>
<table>
<tr>
<th>
Garment
</th>
<th>
Layers
</th>
<th>
Weight
</th>
<th>
Made
</th>
<th>
Source
</th>
</tr>
<tr>
<td>
a garment
</td>
<pre><code>&lt;td&gt;some layers&lt;/td&gt;
        &lt;td&gt;M&lt;/td&gt;
        &lt;td&gt;2×?&lt;/td&gt;
        &lt;td&gt;a source&lt;/td&gt;

    &lt;tr&gt;
        &lt;td&gt;another garment&lt;/td&gt;
        &lt;td&gt;other layers&lt;/td&gt;
        &lt;td&gt;L&lt;/td&gt;
        &lt;td&gt;1×&lt;/td&gt;
        &lt;td&gt;another source&lt;/td&gt;
    &lt;/tr&gt;</code></pre>
</table>
</body>
...
```

I double-checked by wrapping the table in just enough tags to make a valid HTML 5 document, and it renders appropriately in Firefox.

Since markdown is a superset of HTML (["For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags."](https://daringfireball.net/projects/markdown/syntax#html)), this does not meet the [specification in the Pandoc User's Guide](https://pandoc.org/MANUAL.html#description) that "conversions from pandoc’s Markdown to all formats aspire to be perfect."  I understand that implementing the whole HTML 5 specification could be challenging, but simple x by y tables should be handled.

I am using pandoc 2.11.4 on Ubuntu 20.04.2 LTS

I cannot use the google group for discussion as it requires logging in with a google account.  If there is another way of having HTML + metadata in one file which gets wrapped in header and footer boilerplate, that would be a workaround.  Markdown is not very useful for my use case.

**Comment by tarleb** [comment]
What happens here is that pandoc treats part of the table as code block because it is indented by more than four spaces. Try with `--from markdown-markdown_in_html_blocks`.

> I cannot use the google group for discussion as it requires logging in with a google account.

Google doesn't explain this prominently, but it's possible to join the mailinglist by sending a mail to <pandoc-discuss+subscribe@googlegroups.com>.

**Comment by jgm** [comment]
If you want to use "strict" Markdown (close to Gruber's original spec, without pandoc extensions), you can use `-f markdown_strict`, and then the table will come through unharmed.

**Comment by dubsarGimillu** [comment]
Adding the --from option seems to fix the build.  I will try that method of subscribing to the mailing list.

Markdown seems like a really odd specification!  Apparently lots of software supports it organically now but its not hard or ugly to wrap basic HTML tags around text.
