### ISSUE TITLE
JATS writer: better treatment of spans

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc#7211]
@tarleb 
As a follow up on the [discussion on the mailing list](https://groups.google.com/g/pandoc-discuss/c/-XLD7QjOtAA), I'd like to repeat here that `<milestone-start` and `milestone-end` may not be the best choice for spans. My vote would be to go with `named-content` elements. Another fitting element could be `styled-content`, but this is more about visual styling, whereas `named-content` should preserve the semantics better.

**Comment by tarleb** [comment]
To add to this: we produce invalid "articleauthoring" documents because of this, as that tag set does not contain `<milestone-start>` and `<milestone-end>`. (I didn't notice that I was looking at that tag set, which is why I wrongly claimed those tags wouldn't be in JATS 1.2.)

**Comment by denismaier** [comment]
I guess it's because those `milestone` elements are used to tag information that does not into the xml tree structure. (Say, layout information crossing paragraph boundaries...)

**Comment by denismaier** [comment]
Thanks @tarleb

**Comment by tarleb** [comment]
Reopening: `<named-content>` elements must always be given a `content-type` attribute.

**Comment by denismaier** [comment]
Content-type comes from the class of the span, right? We could add a default class if none is specified. But that wouldn't be ideal as well, I guess. What about something like this: a span is either a named-content, or, if there's no content-type attribute, it should be a styled-content instead. That would more or less correspond to the distinction made in the tag library.

**Comment by tarleb** [comment]
Would it be reasonable to use the span's first class as content-type if the attribute is otherwise undefined? This would allow to write

    [Escherichia coli]{.species}

in Markdown to get the following JATS output:

    <named-content content-type="species">Escherichia coli</named-content>

**Comment by denismaier** [comment]
Yes. Makes sense. But what if we don't have a class at all?

**Comment by tarleb** [comment]
Denis Maier ***@***.***> writes:

> Yes. Makes sense. But what if we don't have a class at all?

I've been thinking about using `<target>` in cases where the only
attribute would be `id`, but that would be a bit of a pain as `target`
cannot contain links.

So I think we should follow your proposal and fall back to a
styled-content element in that case.

**Comment by denismaier** [comment]
Thanks!
