### ISSUE TITLE
Unable to create empty lines when converting from .tex to .docx

### ISSUE THREAD

**Issue by julianbarg** [jgm/pandoc#7212]
Various ways for creating vertical space are not preserved when converting from latex to .docx. I am using Ubuntu 20.04 with:
pandoc 2.5. Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7.

Here is a minimal working example to show some of the various ways that do not work when converting from latex to .docx but do work when compiling the latex document to pdf:

```
\documentclass{article}

\begin{document}

	foo

	foo\\

	foo\\\\

	foo\newline

	foo\linebreak

	foo

	\vspace{10cm}

	foo

	\vskip 10cm

	foo

\end{document}
```

**Comment by jgm** [comment]
That's not a bug. Pandoc is designed to translate document structure, not formatting details.
See the beginning of the manual.
