### ISSUE TITLE
Win10 OS, unable to use pandoc on Bash or zsh.

### ISSUE THREAD

**Issue by YeArnfOru** [jgm/pandoc#7213]
Hello,
I've downloaded the msi file, and installed it. 
When I open the terminal on Win10. I could use pandoc as command.

But, after I tapped bash or zsh, to turn in the shell.  It said command "pandoc" not found.

**Comment by jgm** [comment]
Please ask questions like this on the pandoc-discuss google group/mailing list; this tracker is for bug reports.

**Comment by YeArnfOru** [comment]
Dear John,

My problem is solved. It seems like my defailt shell ain’t bash or zsh. I’ve tried by apt installing pandoc.
I just wandder this prolem is not exist on the other PC. Anyway, it works now.

Thanks,
Haoyang.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: John ***@***.***>
发送时间: 2021年4月8日 14:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [jgm/pandoc] Win10 OS, unable to use pandoc on Bash or zsh. (#7213)


Closed #7213<https://github.com/jgm/pandoc/issues/7213>.

―
