### ISSUE TITLE
pandoc 2.12(and newer) fails to parse markdown table with wide charactor.

### ISSUE THREAD

**Issue by sugitach** [jgm/pandoc#7214]
t.md
```
+------------+----------+------------------+
|日本語      | の文字列 | words in english |
+------------+----------+------------------+
|abc defghij | def      | xyz              |
+------------+----------+------------------+
```

run in pandoc 2.11.4
```
% pandoc t.md -f markdown -t html5 
<table style="width:60%;">
<colgroup>
<col style="width: 18%" />
<col style="width: 15%" />
<col style="width: 26%" />
</colgroup>
<tbody>
<tr class="odd">
<td>日本語</td>
<td>の文字列</td>
<td>words in english</td>
</tr>
<tr class="even">
<td>abc defghij</td>
<td>def</td>
<td>xyz</td>
</tr>
</tbody>
</table>
```

and then, run in pandoc 2.13 (same as 2.12)
```
% pandoc t.md -f markdown -t html5
<table style="width:60%;">
<colgroup>
<col style="width: 18%" />
<col style="width: 15%" />
<col style="width: 26%" />
</colgroup>
<tbody>
<tr class="odd">
<td>日本語 | の文</td>
<td>字列 | words</td>
<td>in english</td>
</tr>
<tr class="even">
<td>abc defghij</td>
<td>def</td>
<td>xyz</td>
</tr>
</tbody>
</table>
```

same issue has in multiline table.

**Comment by tarleb** [comment]
It seems that pandoc no longer checks character widths, treating each character as having a width of 1.

So the below works, but looks weird:

``` markdown
+------------+----------+------------------+
|日本語         | の文字列     | words in english |
+------------+----------+------------------+
|abc defghij | def      | xyz              |
+------------+----------+------------------+
```

**Comment by jgm** [comment]
I don't recall removing checks for character widths.
Can you see a change that would have done this?

**Comment by tarleb** [comment]
Oh, right. I assumed from the title that this wasn't the case before, but the behavior goes back to at least version 2.6. Would it make sense to re-use the char-width code from doclayout in the table parser?

**Comment by jgm** [comment]
Pandoc has paid attention to char widths for a long time.
The code for this was mostly exported to doclayout when that was factored out.

**Comment by jgm** [comment]
Grepping the changelog I found this
```
--- DEPRECATED: can be removed when splitStringByIndices is
-splitAt' :: Int -> [Char] -> ([Char],[Char])
-splitAt' _ []          = ([],[])
-splitAt' n xs | n <= 0 = ([],xs)
-splitAt' n (x:xs)      = (x:ys,zs)
-  where (ys,zs) = splitAt' (n - charWidth x) xs
```
Looks like our old splitting routines paid attention to charWidth, but this disappeared in the upgrade to Text?

**Comment by jgm** [comment]
Yeah, that's what happened.  Someone (maybe me?) swapped out our custom `splitAt'`, which *did* take into account character widths, for the standard `Data.Text.splitAt` function.
