### ISSUE TITLE
Smart quotes not generated in some cases

### ISSUE THREAD

**Issue by calliecameron** [jgm/pandoc#7216]
```
$ cat test.md
"This is some text in quotes. Another paragraph by the same speaker follows. The first paragraph should have no close quote.

"The second paragraph should have open and close quotes."

| "Open quote on this line,
| Close quote on the next line."
| "Quotes on the same line."

$ pandoc --to=latex test.md
"This is some text in quotes. Another paragraph by the same speaker
follows. The first paragraph should have no close quote.

``The second paragraph should have open and close quotes.''

"Open quote on this line,\\
Close quote on the next line."\\
``Quotes on the same line.''
```

Pandoc version 2.11.4.

In the first case, the `"` at the beginning of the first line should be converted to ``` `` ```. Having no closing quote at the end of a paragraph when another paragraph by the same speaker follows is a standard pattern, https://en.wikipedia.org/wiki/Quotation_marks_in_English.

In the second case, using a line block e.g. for poetry, I'd expect the quotes on the first and second lines to be converted to opening and closing quotes respectively.

E.g. I'd expect the full output to be:

```
``This is some text in quotes. Another paragraph by the same speaker
follows. The first paragraph should have no close quote.

``The second paragraph should have open and close quotes.''

``Open quote on this line,\\
Close quote on the next line.''\\
``Quotes on the same line.''
```

I'm guessing the conversion doesn't happen because the quotes are unmatched on the same line. One way around this would be to convert an unmatched quote at the beginning of a line to an opening quote, and an unmatched quote at the end of a line to a closing quote.

**Comment by CallumCameron** [comment]
Currently I work around this by putting literal curly quotes in the markdown file.

**Comment by jgm** [comment]
Second part is a duplicate of #2103 I think.
First part has also been reported before.  You'll see that `-f commonmark+smart` (or `gfm+smart`) will give you the open quote on the first paragraph.  We could think about tweaking the regular `markdown` reader to do the same.

**Comment by kravlost** [comment]
> We could think about tweaking the regular `markdown` reader to do the same.

Yes, please. I've been stuck in LaTeX instead of Markdown because of this. I wish I'd known that `commonmark+smart` and `gfm+smart` support it.

**Comment by kravlost** [comment]
@jgm  Please reopen this issue for single quotes. Neither commonmark+smart nor gfm+smart handle single quotes correctly in this situation.

```
# Title

John said, 'This is the first paragraph.

'This is the second.

'This is the third.'
```

produces

```
\section{Title}

John said, 'This is the first paragraph.

'This is the second.

`This is the third.'
```

**Comment by jgm** [comment]
Single quotes are more difficult because the apostrophe can come in a variety of places, and because our parsers can't "look back" in the stream.  If we could look back, then using a left single quote when the `'` occurs after a space or newline would be sensible.

**Comment by kravlost** [comment]
I'm getting around it by running a regex replacing `^'` with a backtick on the generated Latex file but it would be good if it could be handled directly.

**Comment by DarkTyger** [comment]
Given:

``` md
John said, 'This is the first paragraph.

'This is the second.

'This is the third.'
```

[KeenQuotes](https://whitemagicsoftware.com/keenquotes/?apos=quote)  produces:

```
John said, ‘This is the first paragraph.

‘This is the second.

‘This is the third.’
```

@jgm is correct, single straight quotes are difficult.

A multi-pass [algorithm](https://stackoverflow.com/a/73466438/59087) can curl most situations.
