### ISSUE TITLE
Behaviour of 'indent' in PDF output is inconsistent

### ISSUE THREAD

**Issue by CallumCameron** [jgm/pandoc#7217]
Pandoc 2.11.4.

```
$ cat test.md
First paragraph before a section.

Second paragraph before a section.

# Section 1

First paragraph in a section.

Second paragraph in a section.

$ pandoc --variable=indent -o test.pdf test.md
```

![pandoc](https://user-images.githubusercontent.com/1798307/114164530-b38df300-992b-11eb-816e-321da8e310a5.png)

When text is in a section, the first paragraph has no indent, and following paragraphs have indents. When text is before any section, all paragraphs have indents. I'd expect the text outside the section to behave the same as inside the section, i.e. the first paragraph has no indent. Text outside a section would be used in documents that don't have any sections, e.g. a short story.

Currently I work around this by modifying the 'body' line in the default latex template as follows:

```
$if(starts-with-text)$\noindent{}$endif$$body$
```

...and manually setting `--variable=starts-with-text` for documents that need it. It seems like the `\noindent` needs to be on the same line as the start of `body`, so setting it using header-includes didn't work.

It would be great if this case could be detected and handled automatically.

**Comment by jgm** [comment]
This is a LaTeX default, nothing we're doing specially.
You can probably customize it with a command in the LaTeX template; I don't know how offhand, but you could try asking on a TeX forum.
