### ISSUE TITLE
Convert HTML <pre><code lang="lang"> to Mardown ```lang

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [jgm/pandoc#7221]
I'd like to have `pandoc` convert 
```
<pre><code class="language-erlang">func () -> a + b. 
```
(or similar) to

    ```erlang
    func () -> a + b.
    ```

I've searched the doc.s and tried the online tool, but can't figure out how to do it (I'm assuming `pandoc` doesn't do it, actually). I'm using `pandoc --from html --to 'markdown_strict' file.html -o FILE.md`. I'm willing to pull request to add this, I just need a pointer on where to start.

Thanks.

**Comment by mb21** [comment]
seems you need to put the class on the pre tag:

    echo '<pre class="erlang"><code>a + b</code></pre>' | pandoc -f html -t markdown

outputs:

    ``` {.erlang}
    a + b
    ```

**Comment by jgm** [comment]
I think this would be a reasonable change to the HTML reader.

**Comment by paulo-ferraz-oliveira** [comment]
If I understand correctly, there's a possible output already (which you mention), but since it doesn't _conform to expectation_ you'd be OK with a pull request (?). If so, I'd propose `<code class="language-<lang>">`. Is this acceptable?

**Comment by tarleb** [comment]
A PR would be welcome! What I think would need to be done is to change the `pCodeBlock` parser mentioned by @mb21. This function creates a `CodeBlock` element used by pandoc to represent block-level code (i.e., as opposed to inline code). The parser should not only take the attributes from the `<pre>` element, but also from the `<code>` element, and merge those into one set of attributes for the final `CodeBlock`.

This would not solve your problem entirely yet, but the change would make it *possible* to solve it with pandoc -- the `<code>` attributes are currently ignored. One would still have to write a short filter (for example a [Lua filter](https://pandoc.org/lua-filters.html)) to replace the class `language-erlang` with just `erlang`. But the filter could be as short as

``` lua
function CodeBlock(cb)
  cb.classes = cb.classes:map(function(c) return c:gsub('^language%-', '') end)
  return cb
end
```

**Comment by jgm** [comment]
Or we could just have the HTML reader strip off the `language-` -- so everything would work out of the box.
I don't see any reason not to do this (at least in the case where there are no classes on the `pre` element).

**Comment by paulo-ferraz-oliveira** [comment]
Oh, I just gathered that `echo '<pre class="erlang"><code>a + b</code></pre>' | pandoc -f html -t markdown_strict` produces
```
a + b
```
Since this is the flavour I'm using (`markdown_strict`: "original unextended Markdown") does it make sense to change it to output the ` elements, still?

The alternative would be for me to understand how much of a difference would `gfm` make to `markdown_strict`.

Also, I could implement it (or try to) for `markdown`, but then would have to understand the differences between that one and the `_strict` "variant" also.

**Comment by paulo-ferraz-oliveira** [comment]
In the end, I decided to go with `gfm` and a few tweaks here and there.
I'll close this issue, which will probably be a good future reference if somebody falls into the same pit.

Thank you for all the help and guidance.

**Comment by tarleb** [comment]
I'm reopening this because I believe that the mechanics could really be improved. It seems like a good first issue, maybe somebody else would like to give it a try.

**Comment by 0xdevalias** [comment]
> I'm reopening this because I believe that the parser could really be improved.

Created a follow up issue for this, as it seems the implementation in https://github.com/jgm/pandoc/commit/1843a8793a9043a45c8c427b06f100461889d7ef didn't match the proposal in https://github.com/jgm/pandoc/issues/7221#issuecomment-818015681; and causes issues still:

- https://github.com/jgm/pandoc/issues/11701
