### ISSUE TITLE
SQL syntax highlighting ignores MERGE, WITH and SERIALIZABLE

### ISSUE THREAD

**Issue by r0polach** [jgm/pandoc#7222]
SQL syntax highlighting ignores (does not make bold) keywords MERGE, WITH and SERIALIZED in the following markdown file (saved as "sqlhlproblem.md")

~~~
# SQL samles

MERGE sample listing:

```sql
MERGE foreign_export_output WITH (SERIALIZABLE) AS t
USING (
  SELECT dt, foreign_id, val
  FROM mq
) AS u(dt, tn, val)
ON t.DateTimeMark = u.dt AND t.TagName = u.tn
WHEN MATCHED THEN
UPDATE SET t.Value = u.val
WHEN NOT MATCHED THEN
INSERT (DateTimeMark, TagName, Value)
VALUES (u.dt, u.tn, u.val);
```
~~~

when processed to a PDF by:

```
pandoc sqlhlproblem.md -o sqlhlproblem_out.pdf -f markdown --listings
```

Also, when I download KDE XML syntax file (where keywords MERGE, WITH and SERIALIZED are clearly included
(see file sql.xml from [sql.xml.zip](https://github.com/jgm/pandoc/files/6298577/sql.xml.zip)) and I use it with pandoc like

```
pandoc sqlhlproblem.md -o sqlhlproblem_out.pdf -f markdown --listings --syntax-definition=sql.xml
```

it still does not highlight (bold) these keywords.

**Comment by jgm** [comment]
What does `pandoc --version` say?
In any case, this is an issue for the skylighting library, so moving it there.

**Comment by jgm** [comment]
Ah wait, never mind!  You're using `--listings`.  That delegates all highlighting to the LaTeX listings package, so we can't do anything about that. If you want to use the native pandoc KDE-derived highlighting, don't use the `--listings` option.
