### ISSUE TITLE
JATS writer: getting rid of superfluous <p specific-use="wrapper"> elements

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc#7227]
@tarleb As discussed, the jats writer wraps `disp-quote` elements in `p` elements with `@specific-use="wrapper"`. While this is needed in some cases (like under a `list-item`), that is not necessary in most cases (like when the `disp-quote` is directly under the `body` or a `sec` element). Would be great if that could be adjusted.

**Comment by tarleb** [comment]
Looks like this has been changed due to #7041. Sharing `wrappedBlocksToJATS` with the JATS.Table submodule should allow to solve this.

**Comment by denismaier** [comment]
Wow, that was quick! Thanks!
