### ISSUE TITLE
Biblatex bibliography file with underscores

### ISSUE THREAD

**Issue by sdbbs** [jgm/pandoc#7229]
This seems to have already been mentioned in https://github.com/jgm/pandoc/issues/1661, albeit not very clearly:

> For LaTeX: bad idea to escape underscores in file names (was doing some independent testing).

... so I thought I should report it separately. I use:

```
$ pandoc --version
pandoc.exe 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1
```

Consider the following `mwe.md`:

```
---
title: My minimal working example
author: John Doe
numbersections: true    # else pandoc-crossref references are missing
link-citations: true
linkcolor: red
...

# Introduction { #sec:intro }

Hello world

# Contents

As it is mentioned in section [@sec:intro], Pandoc is great [@bib:pandoc].

```

... and the following `my_mwe_bibliography.bib` .bib file, with underscores in the file name:

```bib
@misc{bib:pandoc,
  title = {Pandoc: A Universal Document Converter},
  howpublished = {http://johnmacfarlane.net/pandoc},
}

```

If we build from the command line using the built-in `citeproc`, it seems to pass fine:

```
$ pandoc -F pandoc-crossref --citeproc --bibliography=my_mwe_bibliography.bib --pdf-engine=xelatex mwe.md -o mwe.pdf

$ pandoc -F pandoc-crossref --citeproc --bibliography=my_mwe_bibliography.bib --pdf-engine=xelatex mwe.md -s -o mwe.tex && grep bib mwe.tex
(\protect\hyperlink{ref-bib:pandoc}{{``Pandoc: A Universal Document
\leavevmode\hypertarget{ref-bib:pandoc}{}%

```

Since we just use --citeproc above, there are not many references to "bib" in the `.tex` file. However, the bib file is found, and if we look at the PDF:

![image](https://user-images.githubusercontent.com/48317456/115148028-0bc8a180-a05e-11eb-9638-a96e5c3ef699.png)

... the citation is there, and all seems to look good.

However, if I try to use biblatex instead, no errors are directly reported:

```
$ pandoc -F pandoc-crossref --biblatex --bibliography=my_mwe_bibliography.bib --pdf-engine=xelatex mwe.md -o mwe.pdf

$ pandoc -F pandoc-crossref --biblatex --bibliography=my_mwe_bibliography.bib --pdf-engine=xelatex mwe.md -s -o mwe.tex && grep bib mwe.tex
\usepackage[]{biblatex}
\addbibresource{my\_mwe\_bibliography.bib}
\autocite{bib:pandoc}.
\printbibliography
```

... but if we look at the PDF:

![image](https://user-images.githubusercontent.com/48317456/115148130-7e398180-a05e-11eb-8a59-2353647dbebe.png)

... the citation is clearly missing.

So, I tried looking at the verbose output:

```
$ pandoc --verbose -F pandoc-crossref --biblatex --bibliography=my_mwe_bibliography.bib --pdf-engine=xelatex mwe.md -o mwe.pdf 2>&1 | grep -i 'warn\|err'
xelatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "c:/msys64/tmp/tex2pdf.-ee22084aee304d9e" "C:/msys64/tmp/tex2pdf.-ee22084aee304d9e/input.tex"
\PassOptionsToPackage{unicode}{hyperref}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/hyperref.sty
(c:/bin/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/pd1enc.def)
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/puenc.def)
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/hxetex.def
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/nameref.sty
Package hyperref Warning: Rerun to get /PageLabels entry.
LaTeX Warning: Reference `sec:intro' on page 1 undefined on input line 108.
LaTeX Warning: Citation 'bib:pandoc' on page 1 undefined on input line 109.
LaTeX Warning: Empty bibliography on input line 111.
LaTeX Warning: There were undefined references.
LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
Package biblatex Warning: Please (re)run Biber on the file:
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/hyperref.sty
(c:/bin/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/pd1enc.def)
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/puenc.def)
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/hxetex.def
(c:/bin/texlive/2020/texmf-dist/tex/latex/hyperref/nameref.sty
LaTeX Warning: Citation 'bib:pandoc' on page 1 undefined on input line 109.
LaTeX Warning: Empty bibliography on input line 111.
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please (re)run Biber on the file:
```

So, LaTeX has seen only "Empty bibliography", and it is likely because in `\addbibresource{my\_mwe\_bibliography.bib}` LaTeX has seen a filename with escaped underscores.

I get the same output if I put all settings in a YAML file:

```yaml
pdf-engine: xelatex
citeproc: true  # do I need to have this here for biblatex?
#biblatex: true  # Unknown option "biblatex"
cite-method: biblatex
bibliography: my_mwe_bibliography.bib
filters:
- pandoc-crossref
- citeproc
```

... and call with:

```
$ pandoc --defaults=mwe.yaml mwe.md -o mwe.pdf
[WARNING] Citeproc: citation sec:intro not found
```

... except I get extra warning (though now that I wrote this, this is likely just due to enabling citeproc - which I'm not sure if it is needed, because there is no `biblatex` YAML option).

**Comment by sdbbs** [comment]
Just wanted to note, I get the same results as above for:

    pandoc --verbose -F pandoc-crossref --biblatex --bibliography=my_mwe_bibliography.bib --pdf-engine=xelatex mwe.md -o mwe.pdf 2>&1 | grep -i 'warn\|err'

... also with latest pandoc;

```
$ pandoc --version
pandoc.exe 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1
....
```

**Comment by jgm** [comment]
I don't think the underscores are an issue.  Try creating a standalone tex file
```
pandoc -F pandoc-crossref --biblatex --bibliography=my_mwe_bibliography.bib mwe.md -s -o mwe.tex
```
Then compile it manually
```
pdflatex mwe
biber mwe
pdflatex mwe
pdflatex mwe
```
That works for me.  Note that you need multiple latex runs when you use bibtex or biblatex.  Pandoc won't do that for you when you specify pdf output.  If you want to use `--biblatex` or `--natbib`, then you must use pandoc to create a tex file and then process it yourself -- OR, you can try using mklatex as your pdf engine, with suitable options.

**Comment by sdbbs** [comment]
Many thanks, @jgm:

>  If you want to use `--biblatex` or `--natbib`, then you **must** use pandoc to create a **tex file** and then **process it yourself**

Emphasis mine - that was the part that I was missing; I was otherwise persuaded that also for `biblatex`, `pandoc` would take care of everything, just like it does for `citeproc`!

Since the workflow is intended to be different for `biblatex`, then there is no issue, and I can close this.

Thanks again for the help!
