### ISSUE TITLE
Smart quotes not handled properly

### ISSUE THREAD

**Issue by kravlost** [jgm/pandoc#7243]
Using Pandoc 2.13.

In English, if quoted speech runs into a second paragraph, the first paragraph doesn't have close quotes:

```
# Title

John said, "This is the first paragraph.

"This is the second."
```

If I convert this to text with smart quotes, using

`pandoc -f markdown+smart -t plain .\smart-quotes.md -o sq.txt`

the first paragraph's open quotes aren't converted properly:

```
Title

John said, "This is the first paragraph.

“This is the second.”
```

**Comment by alerque** [comment]
I ran into this before and thought I reported it ... or maybe just found another issue. I forget what the resolution was. Did you search closed issues and/or the discussion list?

**Comment by jgm** [comment]
Dup of #7216 which is itself the dup of another issue.

**Comment by kravlost** [comment]
Sorry I missed the dup.
