### ISSUE TITLE
Identifiers missing for internal hyperlinks in ConTeXt output

### ISSUE THREAD

**Issue by badumont** [jgm/pandoc#7246]
As of pandoc 2.13, the following command:

```
pandoc -t context <<< '[Some text]{#identifier}'
```

produces `Some text` instead of `\reference[identifier]{}Some text`.

**Comment by ousia** [comment]
Sorry for the delayed reply, but if `[Some text]{#identifier}` gives `<span id="identifier">Some text</span>`, why ConTeXt output isn’t `\reference[identifier]{Some text}`?

To see the difference:

``` tex
  \setupinteraction[state=start]
  \enabledirectives[references.border]
  \starttext
  \startTEXpage[offset=2em, pagestate=start]
  \reference[identifier]{Some text}
  \reference[identify]{}Some text
  \about[identifier]
  % \about[identify]
  \stopTEXpage
  \stoptext
```

I’m afraid that with `\reference[identify]{}`, invoking `\about[identify]` breaks compilation.

Just in case it helps.

**Comment by ousia** [comment]
Sorry, @tarleb, I have just realized that you weren’t participating in the issue.

**Comment by tarleb** [comment]
I seem to remember that I tried the alternative, but didn't like it for reason which I no longer remember. Feel free to open a new issue for the proposed change.

**Comment by ousia** [comment]
@tarleb, I don’t use ConTeXt output with pandoc (I feed ConTeXt with HTML sources), so this isn’t a problem for me.

If you saw a problem for the code I proposed, leaving this as it is now is fine for me.

**Comment by badumont** [comment]
> Sorry for the delayed reply, but if [Some text]{#identifier} gives <span id=
> "identifier">Some text</span>, why ConTeXt output isn’t \reference[identifier]
> {Some text}?
>

Because the second argument of \reference is not the content of the span,
but the output of the \about command.

\starttext

First: \reference[first]{the first animal}panda.

Second: \reference[second]{the second animal}koala.

Deliver \about[first] first!

\stoptext

**Comment by ousia** [comment]
@badumont, many thanks for your reply.

This makes sense to me now.
