### ISSUE TITLE
Make body’s max-width configurable in HTML output

### ISSUE THREAD

**Issue by fabschurt** [jgm/pandoc#7247]
Hello :wave:

As you know, for standalone documents, the HTML writer includes the content of the [data/templates/styles.html](https://github.com/jgm/pandoc/blob/master/data/templates/styles.html) partial in the `<head>` section of the HTML document. This partial is partly configurable via metadata variables, but I think it’s too bad that we can’t configure the `body.max-width` CSS rule, especially given that it’s particularly narrow as it is (in my opinion), and it may not fit all use cases.

I’m willing to put some work into this, but I wanted to check the relevance of this enhancement.

So, what’s your opinion about this?

**Comment by jgm** [comment]
I don't know, maybe @mb21 (defaults CSS author) has an opinion.  It's true that a lot of other things are configurable.

**Comment by fabschurt** [comment]
> It's true that a lot of other things are configurable.

Yes! That being said, I understand that this change could be seen as bloat, but I really wanted to propose it because in my opinion it's really the only drawback of the default CSS rules which are otherwise pretty awesome 👌

I guess this narrow main column is mostly fine when viewing the document in a web browser, but I think it's a lot more awkward once converted to PDF (via the `--pdf-engine` option), with the `wkhtmltopdf` engine for example (LaTeX-based engines are not affected if I remember correctly, as they rework the whole document layout).

Maybe, instead of making this CSS property configurable, it could be set to a wider value instead, something around `75%`. I don't know what the most general use case would be here.

**Comment by jgm** [comment]
I would think that if you're converting to PDF, you'd want to use your own custom CSS anyway, tailored for print output.

**Comment by tarleb** [comment]
Not a general solution, but if you are using Markdown input, then you
can change the width by adding the CSS to Markdown, like so:

```{=html}
<style>body{max-width:75%;}</style>
```

**Comment by mb21** [comment]
The current value is `max-width: 36em` (`em so that if you increase the font-size this will increase as well). This results in roughly 80 characters per line, which is already a bit more [than generally recommended for readability](https://baymard.com/blog/line-length-readability) of longer texts.

I think we discussed things like that at length: https://groups.google.com/g/pandoc-discuss/c/1oCCbois1G4

But other than that, I don't have any objections to making that configurable, beyond opening a pandora's box making every value configurable... but not sure that's an argument that really holds.

---

> I would think that if you're converting to PDF, you'd want to use your own custom CSS anyway, tailored for print output.

Well, we do have [some print-specific CSS rules](https://github.com/jgm/pandoc/blob/master/data/templates/styles.html#L27)...

**Comment by mb21** [comment]
@tarleb yes, or:

```
---
header-includes: |-
  <style>
  body{ max-width: 75%; }
  </style>
---
```

**Comment by fabschurt** [comment]
> I would think that if you're converting to PDF, you'd want to use your own custom CSS anyway, tailored for print output.

Well, the default CSS + configurable variables system are very fine by me actually :slightly_smiling_face: (Well, except for this default max-width.) But I get your point.

> beyond opening a pandora's box making every value configurable... but not sure that's an argument that really holds.

I think, on the contrary, that it totally holds :+1: That’s why I was raising concerns about bloat earlier.

Let’s close this, as it seems to be out of scope in the end, and moreover @tarleb and @mb21 mentioned some very acceptable workarounds that I’ll gladly use.

Thanks for your time :slightly_smiling_face:
