### ISSUE TITLE
Header with period will vanish in Docx to HTML conversion

### ISSUE THREAD

**Issue by archonic** [jgm/pandoc#7250]
I'm using Pandoc 2.8.0.1 through the pandoc/latex Docker image.

The attached file has a header with a period in it. Converting it to HTML will have the header vanish.

[Period in the header.docx](https://github.com/jgm/pandoc/files/6388357/Period.in.the.header.docx)

**Comment by jgm** [comment]
It doesn't vanish.  Because this header is marked as the title, it's parsed as the title in metadata.  You should see it if you convert to HTML with the `-s` option (standalone).
In fragment mode (without `-s`) metadata isn't rendered.
