### ISSUE TITLE
Underscore in linked text not parsed correctly for orgmode.

### ISSUE THREAD

**Issue by gitonthescene** [jgm/pandoc#7251]
Using pandoc 2.13:

``` sh
$ pandoc --version
pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1
...
$
```

When rendering a link with an underscore in it this is rendered improperly.

``` sh
$ cat /tmp/test.org 
[[https://flask.palletsprojects.com/en/0.12.x/config/][SERVER_NAME]]
$ pandoc /tmp/test.org -f org -t markdown -s
[SERVER~NAME~](https://flask.palletsprojects.com/en/0.12.x/config/)
$
```

Using the Emacs exporter, I get the following:

``` sh
 [SERVER\_NAME](https://flask.palletsprojects.com/en/0.12.x/config/)
```

I browsed the other issues and didn't see this being reported.

**Comment by gitonthescene** [comment]
FWIW, here's a sample of various combinations using the emacs exporter:

The following:

``` txt
[[https://example.org][SERVER_NAME]]

[[https://example.org][SERVER_NAME_]]

[[https://example.org][_SERVER_NAME]]

[[https://example.org][_SERVER_NAME_]]
```

is exported as

``` txt
[SERVER\_NAME](https://example.org)

[SERVER\_NAME\_](https://example.org)

[\_SERVER\_NAME](https://example.org)

[<span class="underline">SERVER\_NAME</span>](https://example.org)
```

So it looks like it's translated as an `underline` only when it both begins and ends with an underscore, but never as a ~strike through~.

**Comment by tarleb** [comment]
Both the ox-html and ox-latex exporter agree with pandoc's interpretation of the input:

``` latex
\href{https://flask.palletsprojects.com/en/0.12.x/config/}{SERVER\textsubscript{NAME}}
```
``` html
<a href="https://flask.palletsprojects.com/en/0.12.x/config/">SERVER<sub>NAME</sub></a>
```

I don't have a Markdown exporter handy to try, but it seems to be the odd one out. So I think pandoc is doing the right thing.

**Comment by tarleb** [comment]
Just to make sure: what's does <kbd>M-x eval-expression</kbd> give you for `org-export-with-sub-superscripts`? If it's `nil`, then that's the issue. You can add `#+OPTIONS: ^:nil` at the top of the input file to force pandoc into ignoring sub- and superscripts.

**Comment by gitonthescene** [comment]
Thanks for the suggestion.  That seemed to do the trick.  Here's what I get:

```sh
$ pandoc /tmp/test.org -f org -t markdown -s           
[SERVER_NAME](https://example.org)

[SERVER_NAME\_](https://example.org)

[\_SERVER_NAME](https://example.org)

[[SERVER_NAME]{.ul}](https://example.org)
$
```

Also, I see now that I probably want markdown_strict as an output and that the `~NAME~` output is not strikethrough but rather the pandoc [subscript extension](https://pandoc.org/MANUAL.html#superscripts-and-subscripts).

**Comment by tarleb** [comment]
Great! Closing now, but feel free to reopen if you run into related issues.
