### ISSUE TITLE
Inline TeX not put on own line with Org export

### ISSUE THREAD

**Issue by tecosaur** [jgm/pandoc#7252]
Pandoc 2.13

If I have a `.md` file with the following content
```md
A maths environment follows
\begin{align*}
  x &= 1 \\ y &= 2
\end{align*}
Here is some standard text.
```

I can tell from `pandoc -f markdown -t texinfo` that the TeX block is interpreted as TeX.
```texinfo
A maths environment follows @tex
\begin{align*}
  x &= 1 \\ y &= 2
\end{align*}
@end tex Here is some standard text.
```

However, when I export to Org, pandoc creates an incorrect/invalid document:
```org
A maths environment follows \begin{align*}
  x &= 1 \\ y &= 2
\end{align*} Here is some standard text.
```

Org supports inline TeX with `\begin{} .... \end{blocks}`, however, `\begin` must be on its own line
> Environments of any kind. The only requirement is that the ‘\begin’ statement appears on a new line, preceded by only whitespace. [[https://orgmode.org/manual/LaTeX-fragments.html](https://orgmode.org/manual/LaTeX-fragments.html)]

i.e.

```org
A maths environment follows
\begin{align*}
  x &= 1 \\ y &= 2
\end{align*}
Here is some standard text.
```

I imagine this is a small tweak, but I'm not quite sure what. Hence an issue rather than a PR :slightly_smiling_face:

**Comment by jgm** [comment]
This gets parsed as a `RawInline` rather than a `RawBlock`, because it's one of those tex math environments that can occur in inline contexts.  I'm sure the org writer creates a line break before `RawBlock`s, but not before `RawInline`s.  One solution would be for the writer to check to see if a `RawInline "tex"` (or "latex") starts with `\begin`.

**Comment by tecosaur** [comment]
How does this look? If it looks good I'll make a quick PR
```hs
inlineToOrg il@(RawInline f str)
  | elem f ["tex", "latex"] && T.isPrefixOf "\\begin" str =
    return $ "\n" <> literal str <> "\n"
  | isRawFormat f = return $ literal str
  | otherwise     = do
      report $ InlineNotRendered il
      return empty
 ```

**Comment by jgm** [comment]
That would do the trick.
I'd suggest using `cr` instead of "\n" (it avoids double line breaks).
