### ISSUE TITLE
Support for chrome (and chromium) as PDF engines

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#7261]
The Chrome and Chromium web browsers support printing of websites through the command line, e.g.

    chromium --headless --print-to-pdf=OUTFILE.pdf  WEBSITE

It would be nice if pandoc allowed to generate PDFs through HTML by having `chrome` and `chromium` available as PDF engines.

There isn't much documentation on command line options, but the devtools interface has many more options. Maybe we can make use of them somehow. https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF

**Comment by tarleb** [comment]
Maybe a counter-argument, taken from chrome's man page:

> Google  Chrome  has  hundreds  of  undocumented command-line flags that are added and removed at the whim of the developers.

But this has been supported now for 4 years, so it appears to be reasonably stable.

**Comment by tarleb** [comment]
Closing again, because making the PDF look reasonably nice seems to be non-trivial, see, e.g., the [chrome-headless-render-pdf npm package](https://github.com/Szpadel/chrome-headless-render-pdf). Maybe adding support for a wrapper like [`pagedjs-cli`](https://www.pagedjs.org/documentation/02-getting-started-with-paged-js/) would be a better time investment.

**Comment by mb21** [comment]
I've been wondering about this as well! And I'm still a bit surprised that there's no official (or at least commonly used) command-line wrapper around that use-case of chromium (analogous to wkhtmltopdf). The closest thing I could find was [puppeteer-cli](https://github.com/JarvusInnovations/puppeteer-cli), which is a wrapper around the [puppeteer](https://www.npmjs.com/package/puppeteer). Puppeteer is a node.js package and seems to be the most commonly used way to access Chromium over the DevTools Protocol, and seems to be fairly stable. We could of course also try to call that protocol directly from Haskell, but probably not the right approach. I'd rather just add another `--pdf-engine` option.

Note that pagedjs, is a different beast. It's a JavaScript library, meant to run in a browser, that's basically a polyfill for CSS specs for paged media that so far no browser has implemented yet thoroughly. (I've added it to [PanWriter](https://github.com/mb21/panwriter#about-css-for-print) for the paginated preview and it works 'okay'...)

**Comment by tarleb** [comment]
There is a also a `pagedjs-cli` package on npm, which provides a convenient interface to go from HTML to PDF.

    pagedjs-cli input.html -o output.pdf

I tried it on the manual, and as you say, it's not perfect but quite nice already.

**Comment by mb21** [comment]
Right, so while [puppeteer-cli](https://github.com/JarvusInnovations/puppeteer-cli) runs chromium directly on the input html/css, [pagedjs-cli](https://gitlab.pagedmedia.org/tools/pagedjs-cli) also injects the paged.js javascript and puts in divs etc. to do the pagination... 

Neither package seems to have gained widespread adoption (yet), so it's a bit hard to justify adding either one to pandoc as a `--pdf-engine` option... or what to you think?

**Comment by tarleb** [comment]
I just found #6126, which is probably a better placeholder than this issue. I'll add a comment about pagedjs there.
