### ISSUE TITLE
Markdown to Pdf (via latex). Minimal custom template breaks if markdown file contains a list.

### ISSUE THREAD

**Issue by JohnLukeBentley** [jgm/pandoc#7265]
Following a procedure analogous to that detailed in #7264 I've found that if my --from markdown file contains a list, and I'm using a (minimal) custom template, I have to guard against this such that my minimal custom template is now

```latex
\documentclass{article}
$if(title)$
\title{$title$}
$endif$

% Must use to prevent a pandoc bug, where all headers are unconditionally
% inserted with a \hypertarget command See:
% https://github.com/jgm/pandoc/issues/7264
\usepackage{hyperref}

% Avoid pandoc bug when there are lists in the body. 
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

\begin{document}
\maketitle
$body$
\end{document}
```

That is, when the markdown --from file contains a list pandoc will insert a `\tightlist` into the intermediate tex (latex) file, as follows ....

```
\begin{itemize}
\tightlist
\item
  List item one.
\item
  List item two.
```

I suggest that pandoc conditionally insert, into the intermediate .tex (latex) file, `\tightlist` only if it has been defined in the .latex template header. (I'm not clear if \tightlist is a command is ultimately defined in a latex package). That is, so in a minimal custom template we don't need to guard against `\tightlist` being inserted. 

Edit: added "into the intermediate .tex (latex) file" and ".latex template" into last paragraph.

**Comment by tarleb** [comment]
See discussion in #7264.

**Comment by tarleb** [comment]
Workaround for everyone adamant to not define `\tightlist`: this can be done replacing all `Plain` elements in a list with `Para`s. E.g., using a Lua filter:

``` lua
function loosen(list)
  for i, blks in ipairs(list.content) do
    if #blks == 1 and blks[1] and blks[1].t == 'Plain' then
      list.content[i] = {pandoc.Para(blks[1].content)}
    end
  end
  return list
end
BulletList = loosen
OrderedList = loosen
```
