### ISSUE TITLE
Annote field deleted converting from .yaml/.json to .bib

### ISSUE THREAD

**Issue by jkorb** [jgm/pandoc#7266]
Hello! 

I'm converting bibliographies back and forth between formats for a little project and noticed something odd. My bibliographies contain annotations, which are preserved if I convert from .bib to .yaml or .json (via `pandoc test.bib -s -f biblatex -t markdown` e.g.) but not when converting back to .bib. The annotations appear to be preserved fine converting between .yaml and .json.

Not sure if this is a bug or expected behavior, but both according to the BibLaTeX docs on CTAN and the CSL docs, `annote` is a valid field.

Here's an MWE:

one.bib

``` 
@article{id,
     annote = "annotation"
}
```
converts via `pandoc one.bib -s -f biblatex -t markdown` to:

```
---
nocite: "[@*]"
references:
- annote: annotation
  id: id
  type: article-journal
---
```

But converting the previous code (as `two.yaml`) via `pandoc two.yaml -s -f markdown -t biblatex` outputs:

```
@article{id,
}
```
Here's the beginning of my `pandoc -v`:

```
pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylight 0.10.5.1, citeproc 0.3.0.9, ipynb 0.1.0.1
```

**Comment by jgm** [comment]
Possibly we just need to add "annote" to the list of recognized fields at line 129 of T.P.Citeproc.BibTeX (untested).
