### ISSUE TITLE
A better way to transform Note, Warning blocks in rst to markdown

### ISSUE THREAD

**Issue by cathaysia** [jgm/pandoc#7268]
emm, sorry, the mailing is blocked at my area.

for rst , if we have such rst a block:

```rst

... note::

   this is a note block
```

if trans it as :

```md

> Note
> 
> this is a note block.
```

preview:

> Note
> 
> this is a note block

but for now, the code is :

```md
::: {.note}
::: {.title}
Note
:::
this is a note block
:::
```

No markdown support this almost :( 
I must reformat it by hand.

**Comment by tarleb** [comment]
Out of curiosity: could you try if you can subscribe by sending a mail to <pandoc-discuss+subscribe@googlegroups.com>?

As for the question:  you could use a [Lua filter](https://pandoc.org/lua-filter.html) to convert the top-level Div into a BlockQuote. Roughly (untested):

``` lua
function Div (div)
  if div.classes:includes 'note' then
    -- convert div to block quote
    return pandoc.BlockQuote(div.content)
  else
    -- unwrap all other divs
    return div.content
  end
end
```

**Comment by jgm** [comment]
Actually, an easier solution is just to turn off the markdown extensions you don't want or use another packaged markdown variant.

For example,
```
% pandoc -f rst -t gfm
.. note::

   this is a note
^D
<div class="note">

<div class="title">

Note

</div>

this is a note

</div>
```
Or
```
% pandoc -f rst -t markdown-native_divs-fenced_divs-raw_html
.. note::

   this is a note
^D

Note

this is a note
```
Or use `-t markdown_strict`.  Many options here.

**Comment by cathaysia** [comment]
> 
> 
> Actually, an easier solution is just to turn off the markdown extensions you don't want or use another packaged markdown variant.
> 
> For example,
> 
> ```
> % pandoc -f rst -t gfm
> .. note::
> 
>    this is a note
> ^D
> <div class="note">
> 
> <div class="title">
> 
> Note
> 
> </div>
> 
> this is a note
> 
> </div>
> ```
> 
> Or
> 
> ```
> % pandoc -f rst -t markdown-native_divs-fenced_divs-raw_html
> .. note::
> 
>    this is a note
> ^D
> 
> Note
> 
> this is a note
> ```
> 
> Or use `-t markdown_strict`. Many options here.

HAHA, thanks very much. It's all I want :)
