### ISSUE TITLE
Error producing PDF. - issue in converting docx

### ISSUE THREAD

**Issue by pavamana1123** [jgm/pandoc#7270]
> pandoc --version
pandoc.exe 2.13

I just installed pandoc on my Windows 10 machine and I am trying to convert a docx fie to pdf

> pandoc test.docx -o test.pdf
Error producing PDF.

What's wrong with this. It should have just worked straight away.

**Comment by tarleb** [comment]
Is this the full error message? Can you give us more information? E.g., what's the input file, and did you install MiKTeX on your system as suggested [here](https://pandoc.org/installing.html)?

**Comment by tarleb** [comment]
This cannot be answered unless additional information is provided. Closing until then.
