### ISSUE TITLE
By default, use Microsoft's native styles when converting to Word

### ISSUE THREAD

**Issue by arencambre** [jgm/pandoc#7275]
Currently, conversions to Word by default have considerable stylistic differences from Word's built-in defaults. Examples include use of serifed fonts, different font selections, horizontal alignment of certain headings, and more.

Under the premise that Microsoft's default styles are thoughtfully made and clean, please consider using Microsoft's default Word styles unless the user specifies otherwise.

Note that this is not a support request for how to apply my own styles. I can do it with the `reference_docx` switch. It's complexity I'd like to avoid. This is more of a "use good defaults" request.

That said, I acknowledge that in #5820 and elsewhere, I infer that pandoc's premise might have originally been specialized on research publications. This is a great tool, and I would still suggest thinking about the tool's universal applicability. If it is meant as a universal tool, then generally adhering to default norms would be a good to consider. In this case, when creating Word documents, the default styles used by Microsoft in blank, new documents would be great.

**Comment by alerque** [comment]
> Under the premise that Microsoft's default styles are thoughtfully made and clean

Really? That's your argument? Have you *seen* what the inside of a default DOCX file looks like? Have you *seen* how much legacy cruft they drag along not because it is thoughtful or clean but because somebody thought it was a good idea in 1984?

I could see an argument for having an out of the box style that closely matches the defaults, but those defaults don't cover all the classes that Pandoc creates, don't well match similar classes in other formats, and don't make it clear that the way to edit styles would be by editing the style definitions, not reformatting each item.

**Comment by arencambre** [comment]
> Have you seen what the inside of a default DOCX file looks like?

I hear you, but I am not asking for implementing legacy cruft. I am asking for a starting point of pandoc's Word conversation to have the same styles as Word does natively.

> ...those defaults don't cover all the classes that Pandoc creates...

The `reference_docx` switch can still be used to compel different styles. I am asking for a starting point that is closer to Word's default styles.

Non-exhaustive list of ways to get the default closer to Word-native styles:

* Heading 1 style switches to Calibri Light font, not boldfaced.
* Title style becomes left-aligned, black, not boldfaced, and switches to Calibri Light
* Body text uses Calibri 11 pt.

**Comment by jgm** [comment]
I'd be interested to hear what people think about this, for or against. Perhaps people could register their opinions by using the reactions button:  thumbs-up if you're in favor of modifying pandoc's defaults to be close to out-of-the-box Word styles, thumbs-down if you'd rather keep things as they are.

**Comment by arencambre** [comment]
> What version of Word's "standards" are your talking about?

Great question. I wish there was a written standard, but I can't find one. In lieu of that, I suggest the standard is the styling you get if you start with a vanilla document on the current version of Word as it comes with Office 365.

**Comment by cagix** [comment]
I'd support the idea as it is very convenient for users. However, it would mean that Pandoc would have to chase after a (not (well) documented?) "standard" again and again ... For me as a user, the possibility of specifying my own Word file with my own style definitions as a reference is actually quite sufficient ...

**Comment by agusmba** [comment]
I don't have a strong opinion either way (keep the current default or try to mimic word's default more), since I have hacked my own so-so working reference doc to tweak them.
I feel it would be nicer being able to define your own list levels, by editing your reference doc, as we discussed in #4321 but that's a lot more complicated.

**Comment by kravlost** [comment]
[Microsoft are looking to move away from Calibri](https://www.microsoft.com/en-us/microsoft-365/blog/2021/04/28/beyond-calibri-finding-microsofts-next-default-font/) as the default font in office, so defaulting to Calibri may be premature.

**Comment by arencambre** [comment]
@kravlost you're correct on the potential font change. We should continue progress on this issue as any font change is a way off.

If pandoc adopts a custom of "use Word's native styling by default for pandoc Word conversions", then it will be procedurally easy to adjust in the future. The current native Word styling convention is quite a few years old, so like it or not, it has created a custom, so there is value in adopting it.

**Comment by tarleb** [comment]
The ad-hoc voting seems to indicate that ⅓ are in favor of this change, with ⅔ against. Based on this, I'm closing this issue.

However, this does not rule out smaller-scale changes to the reference doc. Those would still be considered.
