### ISSUE TITLE
Bibtex urls containing a%CC%88 '¨'-character gives 'Undefined control sequence. \GenericError' when converting to latex

### ISSUE THREAD

**Issue by d0rf3n** [jgm/pandoc#7277]
When trying to add a citation to the following bibtex entry the url somehow
'
```
@Online{testkey,
  author       = {testauthor},
  date         = {2021},
  title        = {testtitle},
  url          = {https://www.skolverket.se/download/18.7f8c152b177d982455e156e/1616170952319/Ja%CC%88mfo%CC%88relsedok_Matematik_gy_Slutversion_tillga%CC%88nglig_NY.pdf}
}
```

Here the 'ä' is encoded as an 'a' with a suffix '¨', even though it can be written as a single 'ä', in which case it works. Some for i¨and such.

Only if you paste in the above url in most environments it show up as: `https://www.skolverket.se/download/18.7f8c152b177d982455e156e/1616170952319/Jämförelsedok_Matematik_gy_Slutversion_tillgänglig_NY.pdf`

The full error:
```
stderr: Error producing PDF.
! Undefined control sequence.
\GenericError  ...                                
                                                    #4  \errhelp \@err@     ...
l.1325 ...55e156e/1616170952319/Jämförelsedok}


exec error: Error: Command failed: "pandoc" "c:\Users\d0rf3n\Drive\_SKOLA\12 VT 2021\Examensarbete\Rapporten\thesis.md" -o "c:\Users\d0rf3n\Drive\_SKOLA\12 VT 2021\Examensarbete\Rapporten\thesis.pdf" -F pandoc-include -F pandoc-crossref --lua-filter=section-crossref.lua --citeproc
Error producing PDF.
! Undefined control sequence.
\GenericError  ...                                
                                                    #4  \errhelp \@err@     ...
l.1325 ...55e156e/1616170952319/Jämförelsedok}
```

I have no idea if any other similar characters create the same problem. I solved it by replacing the compound letters with the single versions, but since they are invisible unless you paste them in something like notepad, it took me a while to figure out what was going wrong.

My thought is that they are interpreted incorrectly along the way towards Latex and gives some latex error that pandoc doesn't understand?

EDIT: Fixed URL

**Comment by jgm** [comment]
Can you give the exact command you're using when you get this error?
Also pandoc version.

**Comment by jgm** [comment]
Also, can you try with `--pdf-engine=xelatex`?

**Comment by d0rf3n** [comment]
> Can you give the exact command you're using when you get this error?
> Also pandoc version.

Of course, my bad.

Version:  `2.13`
Command: `pandoc test.md --citeproc -o test.pdf`
Testfiles: https://drive.google.com/file/d/1OT3TmuE6znTsVVnqaVooP6CNseDRNM0S/view?usp=sharing

> Also, can you try with `--pdf-engine=xelatex`?

That actually works, no errors. I'm guessing the default uses pdflatex?

PS. I don't need help to get this to work (easy fix just change the troublesome letters in my case), just wanted to lift an error that I stumbled upon and that wasn't obvious on what was wrong.

**Comment by jgm** [comment]
The default is pdflatex; if you have anything non-ascii, you want to use xelatex.
(Normally pandoc will detect the non-ascii characters and give you a helpful message, but in this case they're buried under percent encoding I suppose.)

**Comment by d0rf3n** [comment]
Thanks for the information. I don't know if this is something that almost never happens or if someone thinks it should be looked at.

If you don't think this is a issue, feel free to close the issue imo.
