### ISSUE TITLE
Beamer alertblock and exampleblock usage

### ISSUE THREAD

**Issue by MrSauna** [jgm/pandoc#7278]
This is an enchantment request.

`pandoc 2.13`  

I want an easy way to use beamer's alertblock and exampleblock.

I'm using pandoc \w `pandoc -t beamer slides.md -o slides.pdf`

The special blocks can be used with latex like  
```
\begin{exampleblock}{example}
text in example
\end{exampleblock}

\begin{alertblock}{alert}
text in alert
\end{alertblock}
```
resulting in  
![image](https://user-images.githubusercontent.com/17645731/118098364-79a58600-b3dc-11eb-81f2-9990a06f3a1d.png)

I'm suggesting either syntax like
```
::: exampleblock
#### block title

text in block
:::
```
or
```
#### block title {.example}

text in block
```
or similar to ease the use of these special formatted blocks.

**Comment by cagix** [comment]
i'd love to see this in pandoc, too. 

maybe this could be provided in a more general way:
```
::: xxx
...
:::
```
could be translated into `\begin{xxx} ... \end{xxx}`.

---

however, you can achive this using a simple lua filter:

```lua
function Div(el)
    if  el.classes[1] and  el.classes[1] == "xxx" then
        return {pandoc.RawBlock("latex", "\\begin{xxx}")} .. el.content .. {pandoc.RawBlock("latex", "\\end{xxx}")}
    end
end
```

have a look at https://github.com/cagix/pandoc-lecture/blob/master/filters/tex.lua :)

**Comment by mb21** [comment]
Sounds a bit like #2106 ?

**Comment by cagix** [comment]
yeah, this topic comes up again and again :)

**Comment by cagix** [comment]
I can't find the discussion right now. But there was a longer discussion on this very topic earlier. The problem was IIRC that you could run into LaTeX problems if you simply translated all divs and spans into corresponding LaTeX environments or commands and the respective definitions were not available. Pandoc can't guarantee that, though. If I remember correctly, this is exactly the reason why the request was rejected earlier.

**Comment by MrSauna** [comment]
I'm a novice pandoc user so I don't know how to proceed but I have two points

1.

pandoc manual:

> CUSTOM STYLES
       Custom styles can be used in the docx and ICML formats.

which is used in the example like  

```
::: {custom-style="Poetry"}
| A Bird came down the Walk---
| He did not know I saw---
:::
```

which could be used for this purpose BUT

2.

I feel like alertblock and exampleblock are fundamental to beamer so they should get special handling for example with the 
```
::: alertblock
#### Alert
alert text
:::
```
... syntax

**Comment by cagix** [comment]
@MrSauna  You could paste the snippet above into a text file and replace the "xxx" with "alertblock", and add an option to your call to pandoc: `-L <yourfile>` ... This should do the trick :)

**Comment by MrSauna** [comment]
with divfilter.lua
```
function Div(el)
    if  el.classes[1] and  el.classes[1] == "alertblock" then
        return {pandoc.RawBlock("latex", "\\begin{alertblock}")} .. el.content .. {pandoc.RawBlock("latex", "\\end{alertblock}")}
    end
end
```

the script breaks with
```
::: alertblock
### alerttitle
alert text
:::
```
with the output 
```
Error producing PDF.
! LaTeX Error: \begin{block} on input line 109 ended by \end{alertblock}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.109 \end{frame}
```
it doesn't like inner beamer blocks apparently and

```
::: alertblock
alert text
:::
```

without the third level title its not really interesting because the title holds the colored part of the block

**Comment by MrSauna** [comment]
Oh right it's a two argument begin command
`\begin{alertblock}{<the actual title>}`
so this whole problem is a bit more complicated

**Comment by cagix** [comment]
right, sorry, overlooked this in your original comment. so you could work with something like `::: {.alert title="my title"} ... :::`.
the filter would need to select the attributes too, .i.e. something like (not tested):

```lua
function Div(el)
    if  el.classes[1] and  el.classes[1] == "alertblock" then
        return {pandoc.RawBlock("latex", "\\begin{alertblock}{" + el.attributes["title"] + "}")} .. el.content .. {pandoc.RawBlock("latex", "\\end{alertblock}")}
    end
end
```

**Comment by MrSauna** [comment]
> right, sorry, overlooked this in your original comment. so you could work with something like
> 
> ```
> ::: {.alertblock title="my title"} 
> ... 
> :::
> ```
> 
> the filter would need to select the attributes too, i.e. something like (not tested):
> 
> ```lua
> function Div(el)
>     if  el.classes[1] and  el.classes[1] == "alertblock" then
>         return {pandoc.RawBlock("latex", "\\begin{alertblock}{" .. el.attributes["title"] .. "}")} .. el.content .. {pandoc.RawBlock("latex", "\\end{alertblock}")}
>     end
> end
> ```

Thats worse than writing latex in my opinion. It requires non trivial non standard syntax and a filter. Kinda beats the whole purpose :)

**Comment by cagix** [comment]
well, thats pandoc-markdown syntax :)  

you could achieve something similar by using designated header levels, which are usually not used in beamer slides. but then you would tie an header level to a certain block, e.g. h3 for alert blocks and h4 for example blocks ... thats also non standard syntax (maybe more readable) and you'd need a simple filter as well ...

**Comment by tarleb** [comment]
More verbose filter, less verbose syntax:

``` lua
function Div (div)
  if div.classes[1] == 'section' and div.classes[2] == 'alertblock' then
    div.content[1] = pandoc.Plain(
      {pandoc.RawInline('tex', '\\begin{alertblock}{')} ..
      div.content[1].content ..   -- heading content
      {pandoc.RawInline('tex', '}')}
    )
    div.content:insert(pandoc.RawBlock('tex', '\\end{alertblock}'))
    return div
  end
end

function Pandoc (doc)
  doc.blocks = pandoc.utils.make_sections(false, 1, doc.blocks)
  return doc
end

return {
  {Pandoc = Pandoc},
  {Div = Div},
}
```

Use with

    ### Watch our {.alertblock}

    Everything in this section ends up in the alertblock.

**Comment by MrSauna** [comment]
That flattens sections with source like this
```
---
theme: Warsaw
title: testing123
---

# first section

## first slide

lkasjdf

### testalert {.alertblock}

text in alert

## second slide

second slide test


# second section

## first slide of second section

sample text
```


looks like this with filter 
![image](https://user-images.githubusercontent.com/17645731/118177491-6e357780-b43b-11eb-9b92-431d7a66e0c1.png)

sections should look like this (without filter)

![image](https://user-images.githubusercontent.com/17645731/118177576-8ad1af80-b43b-11eb-8a1d-bda372509133.png)

**Comment by jgm** [comment]
I think supporting a syntax like
```
#### block title {.example}

text in block

#### block title {.alert}

text in block
```
would make sense. After all, we already support "blocks," with headings > slide level, so why not add support for the specific kinds of blocks beamer has?  It should be quite easy.

**Comment by jgm** [comment]
> This is an enchantment request.

Sorry, we are not wizards!

**Comment by tarleb** [comment]
The filter was missing a "re-flattening" step, here's the updated code:

``` lua
function render_alertblock (div)
  if div.classes[1] == 'section' and div.classes[2] == 'alertblock' then
    div.content[1] = pandoc.Plain(
      {pandoc.RawInline('tex', '\\begin{alertblock}{')} ..
      div.content[1].content ..   -- heading content
      {pandoc.RawInline('tex', '}')}
    )
    div.content:insert(pandoc.RawBlock('tex', '\\end{alertblock}'))
    return div
  end
end

function Pandoc (doc)
  doc.blocks = pandoc.utils.make_sections(false, 1, doc.blocks)
  return doc
end

--- Remove remaining section divs
local function flatten_sections (div)
  if div.classes[1] ~= 'section' then
    return nil
  end
  local header = div.content[1]
  if not header or header.t ~= 'Header' then
    return div.content
  else
    header.identifier = div.identifier
    header.attributes.number = nil
    div.content[1] = header
    return div.content
  end
end

return {
  {Pandoc = Pandoc},
  {Div = render_alertblock},
  {Div = flatten_sections}
}
```
