### ISSUE TITLE
Checksum of the pandoc installer package

### ISSUE THREAD

**Issue by chchen-stanford** [jgm/pandoc#7279]
Do you publish the checksum of the pandoc installer package somewhere? I am specifically interested in pandoc-2.13-macOS.pkg. There is a checksum in the homebrew formula, but it is for pandoc-2.13.tar.gz. 

More generally, how do I ensure the integrity of an downloaded pandoc installer?

**Comment by jgm** [comment]
The macOS package is signed with my Apple developer key and notarized by Apple.

**Comment by chchen-stanford** [comment]
Thanks for the information.
