### ISSUE TITLE
{=latex} raw_attribute extension inserts unwanted paragraph breaks around the LaTeX.

### ISSUE THREAD

**Issue by krivit** [jgm/pandoc#7281]
# Steps to reproduce:

1. Construct a file, e.g., `raw_latex.md`, with the following contents:

        Precedes raw LaTeX
        ```{=latex}
        {Raw \LaTeX}
        ```
        Follows raw LaTeX
2. Execute `pandoc raw_latex.md -o raw_latex.tex`.

In both LaTeX and Markdown, a paragraph is ended by a blank line; therefore the user's intent is that of the text here be a part of the same paragraph.

# Expected result:

A file (e.g., `raw_latex.tex`) with the following contents:
```
Precedes raw LaTeX
{Raw \LaTeX}
Follows raw LaTeX
```
or even
```
Precedes raw LaTeX{Raw \LaTeX}Follows raw LaTeX
```
in order to avoid inserting whitespace space where the user did not intend it.

# Actual result:
```
Precedes raw LaTeX

{Raw \LaTeX}

Follows raw LaTeX
```

That is, paragraph breaks have been added around the raw LaTeX.

As far as I can tell, there is no way to prevent that.

# Version
I am getting this on Debian Linux, with
```
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
```

**Comment by krivit** [comment]
My apologies; contrary to what I had written in an earlier version of this ticket, using the inline form, i.e.,
```
`{Raw \LaTeX}`{=latex}
```
is a way around the issue. I still think the current behaviour is a bit surprising to the user and, also, means that there is no way for packages such as `knitr` to avoid inserting paragraph breaks (as opposed to, say, line breaks) between text and code and output chunks.

**Comment by tarleb** [comment]
I've had the same issue, and this has also been requested [before](https://groups.google.com/g/pandoc-discuss/c/SSIKl8VcuUU/m/SpemV6fCCAAJ).The R Markdown folks faced this as well and are using a workaround in their Lua filters, see [here](https://github.com/rstudio/rmarkdown/blob/master/inst/rmarkdown/lua/latex-div.lua#L50-L59).

**Comment by tarleb** [comment]
This is mostly the same as #7111; closing in favor of that issue.
