### ISSUE TITLE
"Exponential" runtime with an (invalid) markdown image-link-like syntax

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#7283]
Running with the following markdown with pandoc 2.13 on macOS:

```markdown
![0[(../../link0.svg){width=100%}
![1[(../../link1.svg){width=100%}
![2[(../../link2.svg){width=100%}
![3[(../../link3.svg){width=100%}
![4[(../../link4.svg){width=100%}
![5[(../../link5.svg){width=100%}
![6[(../../link6.svg){width=100%}
![7[(../../link7.svg){width=100%}
![8[(../../link8.svg){width=100%}
![9[(../../link9.svg){width=100%}
```

It takes forever to finish. If we shorten the list it will finish much faster.

Sorry the title wasn't very specific.

Edit: it is the wrong image-link-like syntax that makes this so slow. The `../..` does makes things worse, but the `[...[(...` is the problem.

**Comment by tarleb** [comment]
Probably related to #1735.

**Comment by jgm** [comment]
Closing in favor of #1735 (and recopying example there).
If you need linear run time guarantees, I suggest you use commonmark.
