### ISSUE TITLE
Issues with line breaks in tables with multiple paragraphs in ms pdf format

### ISSUE THREAD

**Issue by BaardBouvet** [jgm/pandoc#7288]
pandoc 2.13 and groff 1.22.3-10 (Ubuntu 18.04)

The following input
```
.. list-table:: 
   :widths: 50 50 
   :header-rows: 1

   * - Left
     - Right
   * - Long text that should be easy to break up into multiple lines
     - Another long text that should be easy to break up into multiple lines

       Bar
```

gives the following error
```
$ pandoc test.rst -t ms -o test.pdf
warning: file `<standard input>', around line 81:
  table wider than line width
```

And the long text does not appear to be broken up as it should. The text overflows outside the PDF page. This works with the latex pdf-engine.

**Comment by jgm** [comment]
I see the issue.  We get
```
	T{
.PP
Another long text that should be easy to break up into multiple lines
.PP
Bar
T}
```
and the .PP macro resets the line length.
(If you take out the paragraph macros here, you'll get wrapping.)

See https://lists.gnu.org/archive/html/groff/2011-08/msg00021.html

This seems to work okay, and maybe it could be the basis of  a solution:
```
.TS
delim(@@) tab(	);
lw(35.0n) lw(35.0n).
T{
Left
T}	T{
Right
T}
_
T{
.nr LLold \n[LL]
.ll 34.0n
.nr LL 34.0n
.PP
Long text that should be easy to break up into multiple lines
T}	T{
.nr LLold \n[LL]
.ll 34.0n
.nr LL 34.0n
.LP
Another long text that should be easy to break up into multiple lines
.PP
Bar
T}
.TE
```
Here the `.ll` and `.nr` macros adjust the line width.

**Comment by jgm** [comment]
I think it could work to do
```
.nr LLold \n[LL]
```
before the table, then
```
.nr LL 34.0n
```
at the beginning of each table cell (where 34.0n stands in for whatever the column width is, as determined at the beginning of the table by .lw).
Finally, at the end of the table,
```
.nr LL \n[LLold]
```
to reset the line length to what it was before.

**Comment by BaardBouvet** [comment]
I'm also wondering why it uses .PP and not .LP for the table cell content. I didn't expect it to be indented here.

**Comment by jgm** [comment]
As in the LaTeX default, the typographical style we're going for is a nonindented paragraph at the beginning of a section, followed by indented ones.  LP is non-indented, PP indented.
