### ISSUE TITLE
pandoc doesn't build for macOS Big Sur (= macOS 11) with the Apple M1 chip

### ISSUE THREAD

**Issue by kkbt** [jgm/pandoc#7294]
pandoc doesn't build for macOS Big Sur (= macOS 11) with the Apple M1 chip.

Details are reported here:

[https://github.com/Homebrew/formulae.brew.sh/issues/467](https://github.com/Homebrew/formulae.brew.sh/issues/467)

**Comment by tarleb** [comment]
Closing as a duplicate of #6960.
