### ISSUE TITLE
default.latex. Move metadata variables - title, author, date, etc - above $header-includes$?

### ISSUE THREAD

**Issue by JohnLukeBentley** [jgm/pandoc#7295]
I suggest/request that in default.latex the basic metadata variables - title, author, date, etc. - be moved above `$header-includes$`. (I generally use the practice of putting these soon after \documentclass, mimicking what's generally done when working with html).

The motivation is to be able to reference those metadata variables in one's included header code. In my case I'm wanting to put some of these in custom margins.

If the suggestion seems right I suppose all of the following from default.latex would warrant being moved up.

```
$if(title)$
\title{$title$$if(thanks)$\thanks{$thanks$}$endif$}
$endif$
$if(subtitle)$
$if(beamer)$
$else$
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
$endif$
\subtitle{$subtitle$}
$endif$
\author{$for(author)$$author$$sep$ \and $endfor$}
\date{$date$}
```

**Comment by jgm** [comment]
I think that would be fine.

**Comment by JohnLukeBentley** [comment]
Your commit tests fine at my end. Thanks very much!

**Comment by jgm** [comment]
I should have known better than to mess with this!  See #7362.  Perhaps the best approach will be to move the metadata bits immediately before header-includes.  However, I do like having this material in a conspicuous location, either at the beginning or the end of the preamble, so I'm not sure.

**Comment by gitphilip** [comment]
Hi!

For me this update seems to create an issue if I want to include the fontawesome package in the metadata yaml.
In particular, I load fontawesome in the header (I think there is no other way, or?) and want to use the mail icon in the author field already (when using beamer). Previously this worked, but now it seems that moving the metadata before the header causes this issue. More precisely, this doesn't work:

```yaml
author: | 
 | \textbf{My name}
 | \scriptsize \faEnvelope{} \href{mailto:mail@mail.com}{mail@mail.com} \normalsize
```
I load fontawesome via an external header file (I already checked `header-includes` does also not work):

`--include-in-header=../resources/slides_header.tex`

So is there a workaround for this issue, or will it persist and require me to manually change the template?

**Comment by jgm** [comment]
This is like the problem in #7362, but (I think) without a workaround.
@JohnLukeBentley can you comment?
We have a tension here:

- some people want title, author, etc. below header-includes so that code in the header-includes can reference this metadata
- others want the reverse order, to use macros defined in the header-includes in the title, author, etc.

I don't know if there's a way of satisfying both desires.

**Comment by JohnLukeBentley** [comment]
@jpg. Incidentally you might have slightly mis-described the tension ...

* some people want title, author, etc. *above* header-includes so that code in the header-includes can reference this metadata [My original motivation]
* others want the reverse order, to use macros defined in the header-includes in the title, author, etc. (so title, author, etc. is *below* header-includes). [@gitphilip's motivation].

... but, anyway, there does seem to be the tension you allude to.

On an initial thinking before bed time ... 

@gitphilip looks to have a legitimate need (I was not previously aware of the possibility of putting complex code in author, title, etc): referencing `\faEnvelope{}` in author coming *after* the package from which it comes (fontawsome), desirably declared in a `header-includes`.

This does seem to be irreconcilable. That is, we can't make `header-includes` satisfy both needs.

One thing that comes to mind is to resurrect a prior suggestion we discussed somewhere, to have multiple (at least two but probably three) includes in the header. e.g. `header-includes-top` (above author, title, etc but below `\documentclass`); `header-includes-bottom` (before `\begin{document}`; `header-includes-middle`. With `header-includes` mapping to one of these for backwards compatibility (probably `header-includes-middle`).

**Comment by anghyflawn** [comment]
I ran into a different problem but ended up googling my way to this discussion and I think offering some additional sites for `header-includes` might be the way to go. My problem was that I was trying to customize biblatex output (using e.g. `\renewbibmacro`). These commands need to go into the preamble (so `\AtBeginDocument` in a `header-include`d file does not work) but `header-includes` is above biblatex, so there is no good place for them to go.
