### ISSUE TITLE
writeOpenDocument, the API, emits <text:p>...</text:p> for a `Plain` block, which it shouldn't

### ISSUE THREAD

**Issue by kjambunathan** [jgm/pandoc#7298]
**writeOpenDocument, the API, emits <text:p>...</text:p> for a `Plain` block, which it shouldn't**

Haddoc documentation for `data Block`,  with  `Plain` value constructor says

> Plain [Inline] | Plain text, not a paragraph

Given this, it seems,  that surrounding `Plain` within a `<text:p>...</text:p>` tags appear as a bug.  The relevant line of interest where this happens is: https://github.com/jgm/pandoc/blob/fa23effe2567183ec424feda55f507e27f50f7c8/src/Text/Pandoc/Writers/OpenDocument.hs#L378.  

Here is a sample session from within ghci.  Note that `writeHtmlString` doesn't emit paragraph tag, but `writeOpenDocument` does.

```
λ> fragment
[Str "Brandom",Space,Str "(",Str "1994",Str ")"]

λ> writeHtmlString  def (Pandoc nullMeta [Plain fragment])
"Brandom (1994)"

λ> writeOpenDocument def (Pandoc nullMeta [Plain fragment])
"<text:p text:style-name=\"Text_20_body\">Brandom (1994)</text:p>"

```

Background info, 

This is flagged as an issue in `org-citeproc`. See 
See https://github.com/wyleyr/org-citeproc/blob/97a9b543bf133e0c81807da748b4c38e549ecd83/org-citeproc.hs#L304. 

The inline comment in `org-citeproc` says 

> we can't just use Pandoc's ODT writer directly here,
> because it wraps Plain blocks in <text:p> tags.  This breaks our
> extraction mechanism for individual citations and the bibliography
> on the Org side.  We don't want to produce a complete ODT document,
> but rather identifiable fragments that can be inserted into an ODT
> document by Org;

`org-citeproc` is around 6 years old.  And it no longer compiles cleanly against recent versions of pandoc etc.  So, I had to use the stack's `resolver: lts-3.0`.  These are the versions against which `org-citeproc` is compiled against.  Even though the bug is identified against an old version of Pandoc, the bug _exists_ in recent versions of Pandoc as well.

```
~/src/org-citeproc$ stack ls dependencies | grep pandoc

pandoc 1.15.0.6
pandoc-citeproc 0.7.3
pandoc-types 1.12.4.5
```

**Comment by kjambunathan** [comment]
> writeOpenDocument, the API, emits text:p...</text:p> for a Plain block, which it shouldn't


Here is a minimal working example.  Note that the HTML exporter exports a fragment, but the opendocument exporter emits a paragraph.  The behaiour of HTML exporter is right, and the behaviour of opendocument exporter is a buggy.


```
~$ pandoc --version 
pandoc 2.10
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
```

```
~$ echo '[Plain [Str "Brandom",Space,Str "(",Str "1994",Str ")"]]' | pandoc -f native -t opendocument
<text:p text:style-name="Text_20_body">Brandom (1994)</text:p>


```
~$ echo '[Plain [Str "Brandom",Space,Str "(",Str "1994",Str ")"]]' | pandoc -f native -t html
Brandom (1994)
```

```
~$ echo '[Plain [Str "Brandom",Space,Str "(",Str "1994",Str ")"]]' | pandoc -f native -t rtf
{\pard \ql \f0 \sa0 \li0 \fi0 Brandom (1994)\par}
```

**Comment by tarleb** [comment]
See also #7262, which is basically the same issue for docx.

I'm not entirely convinced that this is a bug. Can you describe why this behavior leads to problems for you?

**Comment by kjambunathan** [comment]
> Can you describe why this behavior leads to problems for you?

`org-citeproc` uses `Plain` to typeset citations.  

I have mentioned `org-citeproc` in my original report.  You may want to re-read it if you are interested in it. 

(Think of `org-citeproc` as roughly equivalent to the most recenet `citeproc`executable culled out from `pandoc-citeproc`, but with ODT support.   A sample CLI session at the end of this report will tell you what `org-citeproc` does.  `org-citeproc` much like `citeproc` will genrate ciation  fragments in any given format which will be interpolated in to other export engines like Emacs Orgmode exporter.




>  I'm not entirely convinced that this is a bug. 

**The key thing to note is that it tries to generate a ODT XML fragment as opposed to a ODT document.  `Plain` helps with generating XML fragments.**

`Plain` can be sneaked in only by library writers who generate their own AST or manipulate the Pandoc's AST with their own filters.  This  is one of the reasons why you haven't seen much reports wrt `Plain`.   This is also the reason why the suggested changes will not affect the larger population.

You have 3 independent reports: one from me, the other from https://github.com/jgm/pandoc/issues/7262.  The third one is from the `org-citeproc` author himself.

-------

This is what `org-citeproc` does.  Think of it as a older cousin of `citation`,

```
~/src/org-citeproc/tests$ cat bug.org
Some great ideas occur in books, such as @Brandom1994.
```

```
~/src/org-citeproc/tests$ cat input1.json
[
  {
    "citationItems": [
      {
        "id": "Brandom1994",
        "author-in-text": true
      }
    ]
  }
]
```

```
~/src/org-citeproc/tests$ org-citeproc native input1.json chicago-author-date.csl testdoc.bib
[Plain [Cite [Citation {citationId = "Brandom1994", citationPrefix = [], citationSuffix = [], citationMode = AuthorInText, citationNoteNum = 0, citationHash = 1}] [Str "Brandom",Space,Str "(",Str "1994",Str ")"],Str "////\n"]
,Plain [Str "====\n"]
,Div ("",["references"],[]) [Div ("ref-Brandom1994",[],[]) [Para [Str "Brandom",Str ",",Space,Str "Robert",Str ".",Space,Str "1994",Str ".",Space,Emph [Str "Making",Space,Str "It",Space,Str "Explicit"],Str ".",Space,Str "Harvard",Space,Str "University",Space,Str "Press",Str "."]]]]
```

```
~/src/org-citeproc/tests$ org-citeproc odt input1.json chicago-author-date.csl testdoc.bib
<text:p text:style-name="Text_20_body">Brandom (1994)</text:p>////
====
<text:p text:style-name="Text_20_body">Brandom, Robert. 1994. <text:span text:style-name="T1">Making</text:span><text:span text:style-name="T2"> </text:span><text:span text:style-name="T3">It</text:span><text:span text:style-name="T4"> </text:span><text:span text:style-name="T5">Explicit</text:span>. Harvard University Press.</text:p>
~/src/org-citeproc/tests$ org-citeproc html input1.json chicago-author-date.csl testdoc.bib
<span class="citation">Brandom (1994)</span>////
====
<div class="references"><div id="ref-Brandom1994"><p>Brandom, Robert. 1994. <em>Making It Explicit</em>. Harvard University Press.</p></div></div>
```



```
~/src/org-citeproc/tests$ org-citeproc odt input1.json chicago-author-date.csl testdoc.bib
<text:p text:style-name="Text_20_body">Brandom (1994)</text:p>////
====
<text:p text:style-name="Text_20_body">Brandom, Robert. 1994. <text:span text:style-name="T1">Making</text:span><text:span text:style-name="T2"> </text:span><text:span text:style-name="T3">It</text:span><text:span text:style-name="T4"> </text:span><text:span text:style-name="T5">Explicit</text:span>. Harvard University Press.</text:p>
```

**Comment by tarleb** [comment]
> Plain can be sneaked in only by library writers who generate their own AST or manipulate the Pandoc's AST with their own filters. This is one of the reasons why you haven't seen much reports wrt Plain. This is also the reason why the suggested changes will not affect the larger population.

This is not correct, as you can see by running `echo 'hi' | pandoc -f html -t native`.

**Comment by kjambunathan** [comment]
> > Plain can be sneaked in only by library writers who generate their own AST or manipulate the Pandoc's AST with their own filters. This is one of the reasons why you haven't seen much reports wrt Plain. This is also the reason why the suggested changes will not affect the larger population.
> 
> This is not correct, as you can see by running `echo 'hi' | pandoc -f html -t native`.

Ok.

I am only interesed in the ODT exporter,  accessed via  `writeOpenDocument` API.

How about make `Plain` emit inline XML fragments when it is NOT generating a standalone ODT dcoument.   

(If `writerStandalone` is not the right option,  I would very much appreciate a new option which I can use to change the behaviour of the `writeOpenDocument` API.)

WriterOptions
  { writerStandalone = False,
   .... 
  }

**Comment by kjambunathan** [comment]
Yet another option would be to a new Value constructo, say Plain'--Plain Prime--which achieves the desired result. 

This new value constructor could be a secret, undocumented stuff.  This will be a strict `Plain` as intended.

**Comment by tarleb** [comment]
I'm very sympathetic to the idea in general, and I agree that API access to just the inline rendering would be nice. The challenge is to get this right and consistent across all supported writers.

Special handling for *plain* when not writing a standalone document might be problematic due to the additional complexity and possibly inconsistent behavior that would ensue. Amending pandoc's AST is not really an option unfortunately, as that has immense ripple effects throughout the library.

**Comment by jgm** [comment]
I agree that, in principle, it would be better not to have the OpenDocument rendering of Plain include `p` tags.  However, they are currently necessary to produce valid OpenDocument given the sorts of constructs pandoc's parsers produce.  (Plain is used, for example, in "tight" lists.)

It may be possible to rewrite the ODT and Docx writers so that Plain omits the `p` tags, but there would have to be compensating adjustments elsewhere to avoid producing invalid XML.  It might be tricky to get it right.   Adding a new constructor would be a breaking change and require changes in the entire pandoc ecosystem.

So let me give you an alternate, easy solution:  just have your third-party tool strip off the tags with a regex substitution.

**Comment by kjambunathan** [comment]
> it would be better not to have the OpenDocument rendering of Plain include p tags

We were replying to each other.  So, this suggestion might have been missed.  So, I am replaying it.

How about a new value constructor `PlainPrime`

```
data Block
    = Plain [Inline]
    | PlainPrime [Inline]  <------ This has strict inline semantics

```

Pandoc's parser wouldn't generate `PlainPrime` i.e., it would continue to use `Plain` as it always has been.  The `PlainPrime` will be for people like me or that other person who want strict inline, non-para like export semantics. `PlainPrime` would be used by people who hand-craft their AST or build sneak in a Block here and there for further customization.

**Comment by jgm** [comment]
To repeat myself:

> Adding a new constructor would be a breaking change and require changes in the entire pandoc ecosystem.

Adding a new constructor is one of the most time-consuming changes, because all of the code that uses these types must be updated (hundreds of modules). It also has the potential to break anything that depends on the current pandoc API (e.g. pattern matches will become incomplete).

**Comment by jgm** [comment]
As noted in the other issue, an easier solution would be to export a function that writes inline content.

**Comment by tarleb** [comment]
Closing in favor of #7262 as to avoid a parallel discussion of essentially the same issue.
