### ISSUE TITLE
After merge markdown files into one, the format is absent

### ISSUE THREAD

**Issue by starsareintherose** [jgm/pandoc#7300]
```
pandoc *.md > test.md
pandoc --citeproc --csl test.csl --bibliography test.bib test.md -o test.docx
```
then, no format is present. All is plain text. No Italic format and no headings format.
Here are my version
```
pandoc --version
pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.3.0.9, ipynb 0.1.0.1
User data directory: /home/guoyi/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
The first line `pandoc *.md > test.md` will create an HTML file called `test.md`.  That's not what you want.  If you want markdown output, use `-t markdown > test.md` or `-o test.md`.  But if your intent is to concatenate all the md files, you can just do
```
pandoc --citeproc --csl test.csl --bibliography test.bib *.md -o test.docx
```

**Comment by starsareintherose** [comment]
Sorry, but if I run `pandoc --citeproc --csl test.csl --bibliography test.bib *.md -o test.docx` all the notes will not be converted to docx file but the first note.

**Comment by jgm** [comment]
I'm sorry, I don't understand. If you want to upload files sufficient to reproduce the issue, go ahead.
