### ISSUE TITLE
LaTeX export (and PDF generation) fail because of Babel

### ISSUE THREAD

**Issue by jggouvea** [jgm/pandoc#7301]
Pandoc version:  pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.3.0.9, ipynb 0.1.0.1

OS: Arch Linux current

Whenever I expor my file to LaTeX compilation fails because Pandoc writes the code "pt-BR" for document options and Babel options, but Babel expects "brazil" or "brazilian" instead of "pt-BR". My metadata is correctly set lang: "brazil" (with or without quotes the result is the same). It occurs both with a metadata file and with embedded yaml metadata.

I haved added a "sed" replacement step before final compilation and that solves the problem, but should not be necessary.

**Comment by mb21** [comment]
You should set `lang: 'pt-BR'` in your metadata. Pandoc will convert it to the right thing... also make sure you're using the latest LaTeX version...

**Comment by tarleb** [comment]
See also  #2953, but I think Arch should not be affected by this.
