### ISSUE TITLE
A bug with unusual inputs

### ISSUE THREAD

**Issue by just-franco** [jgm/pandoc#7302]
- Pandoc version:
```
pandoc.exe 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1
```

- Command line: **Git Bash**.
- Command: `pandoc -s filename.tex -o filename.html`.

### It seems they are unusual inputs:
![image](https://user-images.githubusercontent.com/83378025/118857806-d4445380-b8ae-11eb-8cf0-6787888d062c.png)
### Whose output does not fit:
![image](https://user-images.githubusercontent.com/83378025/118858230-4d43ab00-b8af-11eb-9803-3c3826ee59ea.png)

**Comment by jgm** [comment]
Pandoc knows nothing of the CCSXML environment.
(It can't possibly aspire to handling every package on CTAN.)
So this is out of scope.
