### ISSUE TITLE
Not able to use ${.} to refer to files relative to directory of defaults file.

### ISSUE THREAD

**Issue by sww1235** [jgm/pandoc#7303]
Pandoc version 2.11.4 and 2.10.X (didn't noticed what version it was before I upgraded in an attempt to fix these issues)

I have a defaults file at the root of my project directory that refers to files within sub-directories of the project directory. See example directory tree below:

```
proj-dir/
   - defaults.yaml
   - templates
       - main.html5
   - body-includes
       - header.html
       - navbar.html
       - footer.html
```
When adding the `templates` and `body-includes` directories to the `resource-path` option in the default list, I could not use the `${.}` variable expansion as explained in the user manual section on default files. In short, the following did not work in `defaults.yaml`:

```yaml
resource-path: 
  - .
  - ${.}/body-includes/
  - ${.}/templates/
```
where as the following did:

```yaml
resource-path:
  - .
  - ./body-includes/
  - ./templates/
```
I believe this issue also appears in other parts of the defaults file as I ran into some missing file issues earlier that I resolved using resource path instead, but I really noticed it when I was messing around with resource path.

Thank you

**Comment by jgm** [comment]
This feature (`${.}`) was only added in version 2.12.  See the changelog.
