### ISSUE TITLE
New Table format 'list-table' - feature request(/discussion)

### ISSUE THREAD

**Issue by hoijui** [jgm/pandoc#7305]
To be included in pandoc-markdown, or to all the markdown flavors, as an extension.

The general idea is, to use nested lists in succession,
plus an indicator that it is a table, and optionally whether there is a header row.
In the example below, I use one `|` in front of the list(s) to indicate that it is a table,
and a second (optional) `|` to indicate that there is a header row.
This is certainly not optimal, but I care more about the data part here.

```markdown
||
* header - col1
  * header - col2
    * header - col3
      * header - col4
* row1 -col1
  * row1 -col2
    * row1 -col3
      * row1 -col4
* row2 -col1
  * row2 -col2
    * row2 -col3
      * row2 -col4
```

the same in an other format:

```markdown
| header - col1 | header - col2 | header - col3 | header - col4 |
| -- | -- | -- | -- |
| row1 -col1 | row1 -col2 | row1 -col3 | row1 -col4 |
| row2 -col1 | row2 -col2 | row2 -col3 | row2 -col4 |
```

rendered:

| header - col1 | header - col2 | header - col3 | header - col4 |
| -- | -- | -- | -- |
| row1 -col1 | row1 -col2 | row1 -col3 | row1 -col4 |
| row2 -col1 | row2 -col2 | row2 -col3 | row2 -col4 |

## Supposed Benefits

* not so long lines
* more complex cell content is possible then in other formats
* if the `list-table` format is not supported, the data gets rendered as lists
* in larger tables: more easy to understand which column one is currently looking at/easier to find the column one is looking for
* not too hard to implement, which also makes spreading the format to other code bases less work

Feedback please!

**Comment by jgm** [comment]
I think that if we did add a list-table feature, it would be wise to emulate the list table format in reST.
This uses nested lists: outer is rows, inner is columns.

**Comment by hoijui** [comment]
Ahhh.. I guess that is better, yes!

[reST list tables](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html#list-table-directive)

```
.. list-table:: Title
   :widths: 25 25 50
   :header-rows: 1

   * - Heading row 1, column 1
     - Heading row 1, column 2
     - Heading row 1, column 3
   * - Row 1, column 1
     -
     - Row 1, column 3
   * - Row 2, column 1
     - Row 2, column 2
     - Row 2, column 3
```

How would you indicate that a (list-)table is coming, and whether there is a header-row (and possibly other met-data, like in the example above)?

**Comment by hoijui** [comment]
is it possible to write one extension like this, and use it for all markdown formats in pandoc?

**Comment by mb21** [comment]
While I see this being very useful in some situations, it's not in the spirit of markdown. From https://pandoc.org/MANUAL.html#philosophy

> Markdown is designed to be easy to write, and, even more importantly, easy to read:
>
>>    A Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions. – John Gruber

But you can wrap this in a code block and write a custom lua filter (which maybe would even call pandoc's rst reader to parse this).

**Comment by hoijui** [comment]
hmmmm that is true, though in my understand that would imply. not to use tables at all, because none of the table formats I know is easy to read and edit in plain text, except with super minimal tables. That is probably also why the original markdown did not have table support.
This list-table improves a lot on the editing part, and for big tables, it makes it easier to read the content, but it of course does not look like a table, and finding the cell one is interested in is not trivial.. one has to count the header columns up ot the header one is interested in, and then has to count the same amount in the row of data one is interested in.
... Which suggests to (optionally?) allow using numbered instead of unnumbered lists, to get rid of this counting.

PS: My original proposal could be seen as a quite twisted, 45 degree tilted table. ;-)

**Comment by mb21** [comment]
> none of the Markdown table formats I know is easy to read and edit in plain text

I'd say most of them are easy to read but not edit :)

**Comment by hoijui** [comment]
yes true, if there are few columns, and little content in the cells, and without extra stuff like links that blow line-lenght up a lot, they are easy to read. And maybe, that is how all of them should be, and one should use some other format then markdown, for bigger tables.
I do not have a good solution for markdown + non-simplistic tabular-data yet.

**Comment by mb21** [comment]
Well, you can use reference links and place the URL outside the table. But for really big tables, I tend to use csv files and the [pandoc-placetable filter](https://github.com/mb21/pandoc-placetable/), although I'll need to update that for the new pandoc table format...

**Comment by hoijui** [comment]
Ahh yeah, two good options, thanks!
The place-table filter sounds good, especially "There's an option to enable parsing of inline markdown."

**Comment by jgm** [comment]
It would be fairly easy to write a Lua filter that implements the list table syntax.  Just put the list in a specially marked Div, e.g.
```
::: {.list-table}
   * - Heading row 1, column 1
     - Heading row 1, column 2
     - Heading row 1, column 3
   * - Row 1, column 1
     -
     - Row 1, column 3
   * - Row 2, column 1
     - Row 2, column 2
     - Row 2, column 3
:::
```
and then write a Lua filter that takes this Div and converts its contents to a Table.  Maybe someone has already done this, but it wouldn't be especially difficult.

**Comment by hoijui** [comment]
would that still render fine (as a list, without the `:::` stuff), if the Lua filter was not present?

**Comment by jgm** [comment]
The `:::` fence is a pandoc-markdown feature, so it wouldn't render fine in GitHub for example.
However, you could also use HTML div syntax, which pandoc will interpret as a native Div but GitHub will pass through (provided you have blank lines aronud the open and close).
```
<div class="list-table">

   * - Heading row 1, column 1
     - Heading row 1, column 2
     - Heading row 1, column 3
   * - Row 1, column 1
     -
     - Row 1, column 3
   * - Row 2, column 1
     - Row 2, column 2
     - Row 2, column 3

</div>
```

**Comment by hoijui** [comment]
Ahhhh cool, bought!

So if I (or someone else) finds time, this sounds like a cool approach to develop, in case the CSV include and reference links don;t cut it.
Thanks a lot you two! :-)

**Comment by not-my-profile** [comment]
@hoijui FYI I wrote such a lua filter: https://github.com/pandoc/lua-filters/tree/master/list-table
