### ISSUE TITLE
Go beyond \section when using --shift-heading-level-by=-1

### ISSUE THREAD

**Issue by Fnuxus** [jgm/pandoc#7309]
I frequently use this command for converting mediawiki-encoded text:

`pandoc input.txt -f mediawiki -t latex -o output.tex`

The output is included in a scrbook class book project.

**Problem:** pandoc converts _=heading=_ to _\section_, but I need it to be _\chapter_ instead. 

If I change the input to this:

`pandoc input.txt -f mediawiki -t latex --shift-heading-level-by=-1 -o output.tex`

the _=heading=_ encoding loses its encoding altogether.

**Expected behaviour:** If  _--shift-heading-level-by=-1_ ist used, _=heading=_ should be converted to _\chapter_, _--shift-heading-level-by=-2_ should be converted to _\part_.

**Comment by tarleb** [comment]
Checkout `--top-level-division=chapter`, that should solve the problem.
