### ISSUE TITLE
Switch default branch name to `main`

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#7315]
The name "main" has replace "master" and has become the new default in git and on GitHub. It is therefore used in other pandoc-related repos, e.g., unicode-collation, hslua. Having to remember which name the main branch has is cumbersome, and it complicates helper scripts that need to refer to the main branch. I propose to switch to *main* for consistency.

**Comment by jgm** [comment]
I don't have strong opinions about this.  If we wanted to change this, how would we do it?

**Comment by jgm** [comment]
I think that the benefits of consistency may be outweighed by the fact that, if we changed this, all current repositories that interact with pandoc would break (since they point to master).

**Comment by tarleb** [comment]
The default branch can be changed under :gear: Settings > Branches and then :pen: on the default branch name. The local repo must be updated with

    git branch -m master <BRANCH>
    git fetch origin
    git branch -u origin/<BRANCH> <BRANCH>

There are also some links in INSTALLING.md, text in CONTRIBUTING.md, and code in Makefile that would require adjusting.

As for external repos, pandoc/dockerfiles comes to mind. Which others would we need to update?

**Comment by jgm** [comment]
> As for external repos, pandoc/dockerfiles comes to mind. Which others would we need to update?

What I mean is that anyone who has checked out this repository will find that it is broken when they try to do `git pull`. And it won't be obvious how to fix.

**Comment by tarleb** [comment]
I see, that's true. There is a GitHub Action called "[Mirror Branch](https://github.com/marketplace/actions/mirror-branch)" which allows keep the old branch updated for a while (or indefinitely). I'd be happy to create a PR if that's an option.

**Comment by apreshill** [comment]
Some good support here:

https://github.com/github/renaming

Notably, renaming a branch will:

- Re-target any open pull requests
- Update any draft releases based on the branch
- Move any branch protection rules that explicitly reference the old name
- Update the branch used to build GitHub Pages, if applicable
- Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
- Show a notice to contributors who `git push` to the old branch
- Redirect web requests for the old branch name to the new branch name
- Return a "Moved Permanently" response in API requests for the old branch name

Learn more about [renaming a branch](https://docs.github.com/github/administering-a-repository/renaming-a-branch).

**Comment by jgm** [comment]
I'm pulling the trigger on this.  They give the following guidance for updating your local environment:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
