### ISSUE TITLE
Incorrect column widths / text off page, for table containing math

### ISSUE THREAD

**Issue by rwijtvliet** [jgm/pandoc#7317]
This table

```
| Profit-at-risk (gas) | |
|:---|:---|
|For modelling | $\Delta rmp_{par gas} = \underbrace{-qu_0 \cdot \Delta pu_L - (\Delta qo_L + \Delta qo_S) \cdot (pu_0 + \Delta pu_L - po_0) - qu_L \cdot \Delta pu_S}_{\text{indirect}} \  \underbrace{- \Delta qo_S \cdot \Delta pu_S}_{\text{direct}}$ |
| (idealised) | $\Delta rmp_{par gas} = \underbrace{- \Delta qo_S \cdot (pu_L - po_0)}_{\text{indirect}} \ \underbrace{-\Delta qo_S \cdot \Delta pu_S}_{\text{direct}}$ |
```

is rendered like this in pdf:

![grafik](https://user-images.githubusercontent.com/4106013/119658665-b5553c80-be2d-11eb-957a-ce4333d04f24.png)

That can't be right. Let me know if there is anything I can do to help in finding the bug.

Here are my versions:

pandoc.exe 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1

**Comment by mb21** [comment]
This seems mostly like a LaTeX question... please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!
