### ISSUE TITLE
Bug: --metadata-file argument not recognized last version pandoc

### ISSUE THREAD

**Issue by leilaicruz** [jgm/pandoc#7318]
Hello all, 

I get this output from `pandoc --version` :
pandoc  2.2.3.2 Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2

My bug is that I am unable to replicate the book pdf from [Pandoc book template repo](https://github.com/wikiti/pandoc-book-template) due to the following error: `Unknown option --metadata-file.`
Also when I list all the arguments for pandoc : `pandoc --help` I do not see this argument. I am really sure I have an outdated version of Pandoc , however I have download the .deb file from the last release and install it in my Ubuntu 18.04 using :
`sudo dpkg -i pandoc-2.13-1-amd64.deb ` , so I should have the most updated version , isn't? 

can you help me to pinpoint where is the flaw?  thanks!

**Comment by mb21** [comment]
If `pandoc --version` doesn't print out 2.13, you don't have the lastest. Try `which pandoc` to see where the binary you have is located...

For future questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by leilaicruz** [comment]
thanks :)  But I had the same  issue as the same pointed out here https://askubuntu.com/questions/1084723/issues-installing-pandoc-2-3-1-in-ubuntu-18-04-1 , that I can not get rid of the old pandoc , do you have perhaps an idea about how to resolve this?

**Comment by leilaicruz** [comment]
I solved it by updating all packages from conda 
`conda update --all`

thanks!
