### ISSUE TITLE
Integrate third party BBCode writers in pandoc upstream.

### ISSUE THREAD

**Issue by wiki-me** [jgm/pandoc#7327]
[This](https://github.com/lilydjwg/2bbcode) is the code in question 

I also opened an [issue]( https://github.com/lilydjwg/2bbcode/issues/5) with the third party repository mentioning why I think this is good for pandoc (besides making the writers more discoverable). 

Bbcode is very useful, if I want to write a long forum post I can write it in markdown or ODT (that have good editors), and then convert it to bbcode and then post it.

**Comment by jgm** [comment]
We don't include lua writers in the main pandoc source code.
A Haskell version could be considered.
