### ISSUE TITLE
[bug][Docx Writer]table caption style wrong in newest pandoc 2.14

### ISSUE THREAD

**Issue by ilcpm** [jgm/pandoc#7328]
In pandoc 2.13, the table caption has a Style named `Table Caption`

We use this markdown table to get a table in Docx with a caption centering aligned (the number in the front of caption is created by our filter, ignore it)

```markdown
| 第一列 |  第2列   | 第$x$列 |
| :----- | :------: | ------: |
| 左对齐 | 居中对齐 |  右对齐 |
| 数字   |   1231   |    4654 |
| 空     |   sum    |       - |

: 这里是表头\sc{}English Table Title {#tbl:test}
```

![image](https://user-images.githubusercontent.com/36830343/120067265-2ce4cf00-c0ad-11eb-97ce-82475eda587a.png)

---

But in pandoc 2.14, we fond that table caption no longer apply the style

![image](https://user-images.githubusercontent.com/36830343/120067378-dcba3c80-c0ad-11eb-95c9-c9fa058dd54c.png)

The style `Table Caption` is still there but not applied to the table caption, while `Compact` was applied.

**Comment by ilcpm** [comment]
Besides, can pandoc support Word's table style syntax? I fond some issues mentioned this feature long times ago.

Maybe pandoc can recognize the `{}` after the table caption as we do now

```markdown
: table caption {#test .custom-style="table style"}
```

means a table with a tag "test" and table style "table style"

---

And, how about support column spans and row spans in markdown so users won't need a filter to do that?

**Comment by jgm** [comment]
@tarleb - Was this an intended effect of your docx writer changes, or an inadvertent regression?

**Comment by tarleb** [comment]
Definitely a regression. Puzzles me a little, as I don't remember changing the caption handling.
I'm taking a short break and will take a look in about a week.

**Comment by jgm** [comment]
I think I see the issue; I'll push a fix.
