### ISSUE TITLE
2.14.0 Regression: GFM Markdown document with YAML metadata block results in empty $body$

### ISSUE THREAD

**Issue by jessepav** [jgm/pandoc#7339]
For instance,

**test.md**
```
---
title: Test
---

Hi
```

`pandoc -t html -s -f gfm -o test.html test.md` results in an empty document body, while `pandoc -t html -s -f markdown -o test.html test.md` correctly says Hi.

v2.13.0 did not exhibit this problem.

**Comment by jgm** [comment]
How strange!  It's not clear why this would have changed, but I'll look into it.
