### ISSUE TITLE
Lua filter throwing syntax error for unknown reason.

### ISSUE THREAD

**Issue by jvdoorn** [jgm/pandoc#7341]
I wanted to use the [`math2svg` filter](https://github.com/pandoc/lua-filters/tree/master/math2svg) but it gave an error. As a test I tried a simple test filter (`test.lua`) to determine if the error is with Pandoc or the `math2svg` filter. The test filter consists of a simple `print('Hello World!')`, which runs fine in Lua but when Pandoc tries to run the filter it gives syntax errors for some reason. I thus conclude that there is probably something wrong with Pandoc (or I'm missing something). See the attached terminal output. The file `proposal.tex` renders fine with `pdflatex` and throws no errors or warning when rendering with Pandoc.

```
$ pandoc --mathml proposal.tex > /dev/null
$ pandoc --mathml --filter='test.lua' proposal.tex > /dev/null
/Users/julian/.local/share/pandoc/filters/test.lua: line 1: syntax error near unexpected token `'Hello World!''
/Users/julian/.local/share/pandoc/filters/test.lua: line 1: `print('Hello World!')'
Error running filter /Users/julian/.local/share/pandoc/filters/test.lua:
Filter returned error status 2
$ cat ~/.local/share/pandoc/filters/test.lua 
print('Hello World!')
$ lua ~/.local/share/pandoc/filters/test.lua 
Hello World!
$ lua -v
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
$ pandoc -v
pandoc 2.14
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4, ipynb 0.1.0.1
User data directory: /Users/julian/.local/share/pandoc
```

I'm running on macOS 11.2.3 with Pandoc 2.14. I have not been able to find any resources or similar issues. Could you help me out here? Is there a way I can run my script directly using the bundled Lua interpreter or tell Pandoc to use my system Lua interpreter? That way we can determine if Lua is the issue.

**Comment by jgm** [comment]
Use `--lua-filter` not `--filter` for lua filters.
`--filter` is for JSON filters.
