### ISSUE TITLE
width attributes is ignored on fenced divs 

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#7342]
This follows a question on https://groups.google.com/g/pandoc-discuss/c/mU6-z1EO_XQ/m/Es2IPg8mAgAJ

Using Pandoc 2.14, `width` is not kept when added as attributes in fenced divs

````powershell
❯ pandoc -t html
::: {#hello .greeting .message width=40%}
Hello **world**!
:::
^Z
<div id="hello" class="greeting message">
<p>Hello <strong>world</strong>!</p>
</div>
````
It seems it should has for height
````powershell
❯ pandoc -t html
::: {#hello .greeting .message height=40%}
Hello **world**!
:::
^Z
<div id="hello" class="greeting message" height="40%">
<p>Hello <strong>world</strong>!</p>
</div>
````

from HTML to Markdown conversion, it is kept 
````powershell
❯ pandoc -f html -t markdown
<div id="hello" class="greeting message" width="40%">
</div>
^Z
::: {#hello .greeting .message width="40%"}
:::
````

**Comment by jgm** [comment]
I closed this by making `width` work the way `height` currently does -- but having second thoughts, because neither is a valid attribute on a div.  Perhaps we should always do what we currently do for `width` if the `column` class  is present: produce a style attribute with a width?  (Ditto for height?)

**Comment by jgm** [comment]
The way it works now, anything that isn't a valid HTML5 attribute name gets `data-` prepended.  But of course, that ignores the fact that some attributes are only valid on certain elements.  We could try to improve this.

**Comment by mb21** [comment]
I'd probably try to keep this as simple and predictable from a user perspective as possible.

- width and height should behave the same way, and are only processed when on an image element or when the column class is present.
- prepending `data-` was done to produce valid HTML output (and more importantly, XHTML), which makes somewhat sense. But then again, really not sure it's worth keeping up with all the different attributes on different elements... and there's a lot of invalid HTML out there that works just fine in all browsers.

**Comment by jgm** [comment]
All right, I guess the consensus is that it's okay to close this without further changes.
