### ISSUE TITLE
Empty header emitted instead of no header for headless table in markdown

### ISSUE THREAD

**Issue by eugene55** [jgm/pandoc#7343]
It looks like commit c0d8b186d142eb5e9f845de0a4ebcadd04c32dce introduced regression caused empty header to appear for headless table.
Noticed it when updated my 2.11.3 installation to 2.11.4
Issue can be reproduced using test file from the project, [test/pipe-tables.txt](https://github.com/jgm/pandoc/blob/master/test/pipe-tables.txt)
Command line: pandoc test/pipe-tables.txt -o test/pipe-tables.pdf -f markdown
Resulting pdf file will have empty header for "Headerless table without caption" scenario

**Comment by jgm** [comment]
That commit didn't introduce the problem -- it *solved* the problem (but only for grid tables). You are pointing out that a similar problem arises for pipe tables.

**Comment by jgm** [comment]
The manual says:

> The header cannot be omitted.  To simulate a headerless table, include a header with blank cells.

One could interpret that as meaning that you can't *really* get a headerless table using pipe table syntax, but you can come close by using a blank header.  I believe that's how I interpreted it when I wrote it, anyway.

**Comment by jgm** [comment]
Interestingly, there is a difference here between the HTML writer and the LaTeX writer. The HTML writer actually does produce a headerless table (apparently assuming that if all the header cells are empty, no header is really wanted), while the LaTeX writer produces the empty header.  The ms writer behaves like the HTML writer.  Haven't checked all the others.

**Comment by jgm** [comment]
Writer behavior with this pipe table:

HTML: headerless
LaTeX: empty header
ConTeXt: headerless
Ms: headerless
RST: headerless
Markdown: headerless
Docbook: headerless
mediawiki: headerless

**Comment by eugene55** [comment]
Right, and LaTeX writer produced headerless table in 2.11.3
