### ISSUE TITLE
--extract-media output incorrect image paths, pictures not sequence-numbered.

### ISSUE THREAD

**Issue by noisnemid** [jgm/pandoc#7345]
# Pandoc Version

```
pandoc 2.14
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4, ipynb 0.1.0.1
User data directory: /home/xxx/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

```

# Environment
OS = Archlinux Up-to-date

# Expected Results

```
pandoc test.docx -o test.rst --extract-media=.

ls -R

.:
media  test.docx  test.rst

./media:
image1.png


cat test.rst

HEADLINE
========

TEXT-PARAGRAH

PICTURE

|image0|

.. |image0| image:: ./media/image1.png
   :width: 2.50972in
   :height: 1.77014in

```

# Actual Results-1

## Command

```
pandoc test.docx -o test.rst --extract-media=.
```

## Files
```
test.docx
test.rst
10bacc7a07650d7fccd4a9cdf9047f1f6e5e6695.png
```

Output doc (test.rst):
```
HEADLINE
========

TEXT-PARAGRAH

PICTURE

.. image:: 10bacc7a07650d7fccd4a9cdf9047f1f6e5e6695.png
   :width: 2.50972in
   :height: 1.77014in


```

# Actual Results-2

## Command

```
pandoc test.docx -o test.rst --extract-media=./media
```

## Files

```
test.docx
test.rst
media/10bacc7a07650d7fccd4a9cdf9047f1f6e5e6695.png
```

Output doc (test.rst)

```
HEADLINE
========

TEXT-PARAGRAH

PICTURE

.. image:: 10bacc7a07650d7fccd4a9cdf9047f1f6e5e6695.png
   :width: 2.50972in
   :height: 1.77014in


```

# Sample docx file

[test.docx](https://github.com/jgm/pandoc/files/6589656/test.docx)

# Bug Description

I tested the command under windows 10 via an old versioned pandoc (v 2.7.3), whose output is usually the result I have got for a long time as the  'Expected Results' shows.

After some updates recently, the results seem incorrect.

The output path is different, and the paths of the pictures of image-directives in rst, and markdown are both incorrect.

What's more, in Windows' old versioned pandoc, the filename of images are automatically sequenced numbers.

**Comment by jgm** [comment]
I think I've fixed this, but lots of informal testing would be helpful!
A nightly should be available by tomorrow.

**Comment by noisnemid** [comment]
Thanks so much!!!
