### ISSUE TITLE
svg image in markdown does not convert to pdf output anymore

### ISSUE THREAD

**Issue by lmunch** [jgm/pandoc#7348]
Consider a markdown file (test.md) containing an svg file:

`![some svg](example.svg)`

With pandoc 2.13 (pandoc-2.13-1-amd64.deb) the following works:

$ pandoc test.md -o test.pdf

With pandoc 2.14.0.1 (pandoc-2.14.0.1-1-amd64.deb) I get:

Error reading SVG:Error opening file /home/me/docs/d931051d2de8841d06da4438841d4007d66dbce7.svg: No such file or directory

[WARNING] Could not convert image d931051d2de8841d06da4438841d4007d66dbce7.svg: conversion from SVG failed
Error producing PDF.
! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.70 ...1051d2de8841d06da4438841d4007d66dbce7.svg}

**Comment by jgm** [comment]
Dup of #7344 - this is fixed in master.
