### ISSUE TITLE
Underlined text does not get wrapped in PDF output

### ISSUE THREAD

**Issue by frederik-elwert** [jgm/pandoc#7351]
When outputting underlined text in LaTeX, pandoc uses the `\underline{}` command. This has the known problem of preventing line breaks: https://tex.stackexchange.com/questions/9550/why-does-underlined-text-not-get-wrapped-once-it-hits-the-end-of-a-line

An easy fix would be to replace `\underline{}` with `\ul` from the package `soul`. This would mean an additional package, but `soul` is a quite common one exactly for this reason.

**Comment by jgm** [comment]
`soul` isn't in Debian's texlive-latex-recommended, which I usually use as a benchmark for "easily available packages."  So I'm a bit hesitant.  Also, you can always include-in-header something like
```
\usepackage{soul}
\renewcommand{\underline}[1]{\ul{#1}}
```
wouldn't this work?

**Comment by frederik-elwert** [comment]
Yes, I understand the hesitation.

I guess the LaTeX snippet would work, though I don’t know if there are any implications in redefining `\underline{}`. I fixed this for our purposes with a small lua filter. But I also think this is a significant drawback in pandoc’s behaviour, as currently Underline behaves very differently from other inline classes, and it requires knowledge of LaTeX to fix this.

So yes, I agree there are ways to work around it, but I’m not sure about the tradeoff between the additional dependency and better default functionality.

**Comment by jgm** [comment]
I'm not sure either.  I'm pretty tempted just to depend on soul.
We could even do it conditionally, in two different ways:

1.  We could include `\usepackage{soul}` in the template only if Underline elements occur in the document, or
2. We could do something like

```
\IfFileExists{soul.sty}{\usepackage{soul}}{\def\ul\underline}
```

**Comment by frederik-elwert** [comment]
Sounds reasonable. I guess I'd slightly be in favor of solution 2, because it still enables basic underline in the rare cases where soul is not available. And it might be less complex code-wise. But I'm really no expert.

**Comment by jgm** [comment]
I think the main difference is that, for people who don't already have soul installed, with 1), compilation will fail with a message that soul is not installed, whereas with 2) it will succeed but the underlining won't wrap.  Don't know which is better.

**Comment by frederik-elwert** [comment]
You're right, I probably didn't think this through. It might be better to always depend on soul when needed to guarantee consistent output.

**Comment by jgm** [comment]
I found a solution, using ulem instead of soul. We already use ulem for strikeout, and it's in debian's texlive-latex-recommended.
