### ISSUE TITLE
Cannot use images in subdirectory due to path resolution changes in pandoc 2.14

### ISSUE THREAD

**Issue by tzok** [jgm/pandoc#7359]
I am using pandoc 2.14.0.1.

Here is the directory structure:
```
mwe/
├── images
│   └── example.svg
└── input.md
```

Here is the content of `mwe/input.md`:
```markdown
# Slide

![](images/example.svg)
```

Here is the output of `pandoc -t beamer input.md -o output.pdf` executed in working directory `mwe`:
```
Error reading SVG:Error opening file /tmp/mwe/3aaf1b55541674b85a881d64440fdec2f8b34b29.svg: No such file or directory

[WARNING] Could not convert image 3aaf1b55541674b85a881d64440fdec2f8b34b29.svg: conversion from SVG failed
Error producing PDF.
! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.111 \end{frame}
```

I tried running `pandoc -f markdown+rebase_relative_paths -t beamer input.md -o output.pdf`, but I get the same error message.

The presented directory structure is what I use in all my pandoc projects. I have a Makefile in the top directory and all my input files reference files in `images/` subdirectory. How can I get pandoc back to accept this directory structure?

---

It all works in 2.13:
```
docker run -it --rm --volume $(pwd):/data pandoc/latex:2.13 -t beamer -o output.pdf input.md
```

And it breaks in 2.14:
```
docker run -it --rm --volume $(pwd):/data pandoc/latex:2.14 -t beamer -o output.pdf input.md
```

**Comment by jgm** [comment]
Dup of #7344?
Try a nightly, as this is fixed in master.

**Comment by tzok** [comment]
I confirm that it is fixed in the nightly build. Sorry I did not find the duplicated issue in the first place.
