### ISSUE TITLE
invalid docx when generating tables with no header rows

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#7369]
Starting in pandoc 2.14, when creating a table with no headers from within a Lua filter and targeting the `docx` format,  an invalid docx file is created.  When header rows are included, the docx is valid.

Sample docx files from 2.13 and 2.14 are attached. Starting with pandoc 2.14, the following additional xml is included which appears to be the culprit (removing this from the document.xml file and re-zipping it results in a valid docx file):

```
<w:tr>
  <w:trPr>
    <w:tblHeader w:val="true"/>
  </w:trPr>
</w:tr>
```

To reproduce, you can use the following command on the contents of files below:

```bash
pandoc test.md --to docx -o test.docx --lua-filter simpletable.lua
```

**test.md**

```markdown
:::{.simpletable}
:::
```

**simpletable.lua**

```lua
Div = function(el)
  local caption = "Overview"
  local aligns = {pandoc.AlignDefault, pandoc.AlignDefault}
  local widths = {0, 0} -- let pandoc determine col widths
  local headers = {}
  local rows = {
    {{pandoc.Plain "Haskell"}, {pandoc.Plain "static"}},
    {{pandoc.Plain "Lua"}, {pandoc.Plain "Dynamic"}},
  }
  local simple_table = pandoc.SimpleTable(
    caption,
    aligns,
    widths,
    headers,
    rows
  )

  local tbl = pandoc.utils.from_simple_table(simple_table)

  el.content:insert(tbl)
  return el
end
```

Changing `local headers = {}` to this results in a valid docx:

```lua
local headers = {{pandoc.Plain ""}, {pandoc.Plain ""}}
```

Output generated by pandoc 2.13 and 2.14 also attached for reference.

[output - 2.13.docx](https://github.com/jgm/pandoc/files/6627225/output.-.2.13.docx)
[output - 2.14.docx](https://github.com/jgm/pandoc/files/6627226/output.-.2.14.docx)

**Comment by jgm** [comment]
@tarleb Can you see what is happening here?

**Comment by tarleb** [comment]
We currently check whether the header contains a row, but we should probably check whether all header rows are empty. I'm looking into it now.

**Comment by tarleb** [comment]
It were two bugs coming together: one was bad handling of table headers in the `from_simple_table` Lua function, the other the mentioned problem in the Docx table writer. Both should be fixed now.

**Comment by jjallaire** [comment]
Excellent, thanks!
