### ISSUE TITLE
Conversion MD->PDF containing svg image fails due to "wrong" file name

### ISSUE THREAD

**Issue by OleBae** [jgm/pandoc#7373]
Have the following small markdown file inptest.md: 
```
## MQTT APC Topic tree 

![MQTT Topic Tree](apc-topic-tree.svg)

`<ProviderName>`s in bold above. 
```
When I run
```
oab@OLEANDERS-PC:/mnt/c/Users/OleAnders/dev/SpecTest/apc$ pandoc --pdf-engine=xelatex -o test.pdf inptest.md
Error reading SVG:Error opening file /mnt/c/Users/OleAnders/dev/SpecTest/apc/926b717f17f6916cb5de46bdba0a2dfc8f1ece10.svg: No such file or directory

[WARNING] Could not convert image 926b717f17f6916cb5de46bdba0a2dfc8f1ece10.svg: conversion from SVG failed
xelatex not found. Please select a different --pdf-engine or install xelatex
```
Note: this is without xelatex in path, but if it is in path it still fails, just after producing some addtional xelatex errors. 

If I do `cp apc-topic-tree.svg 926b717f17f6916cb5de46bdba0a2dfc8f1ece10.svg` (with xelatex in path) then the conversion works fine and produces the expected test.pdf.

If I replace the svg image with a pgn things work fine "out of the box". 

So it seems to me that either a copy that should have happened didn't, or the file name becomes mangled along the way. 

Note: converting to html works fine, but in that case the svg is used directly(?), so it would not involve the codepath the error happens on regardless?

This is on a Ubuntu 20.04 under WSL2. 

Running latests version of pandoc
```
oab@OLEANDERS-PC:/mnt/c/Users/OleAnders/dev/SpecTest/apc$ pandoc --version
pandoc 2.14.0.1
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
```
xelatex is also an install of latests
```
oab@OLEANDERS-PC:/mnt/c/Users/OleAnders/dev/SpecTest/apc$ /usr/local/texlive/2021/bin/x86_64-linux/xelatex --version
XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021)
```
but since error happens even without xelatex in path, I am guessing that doesn't matter.

**Comment by jgm** [comment]
Did you search closed issues?

**Comment by jgm** [comment]
https://github.com/jgm/pandoc/issues?q=is%3Aissue+is%3Aclosed+svg

**Comment by OleBae** [comment]
I did look at the existing issues, but obviously messed that up. Sorry for  the extra ticket, and thanks for pre-fixing my bug report! :-)

**Comment by jgm** [comment]
No problem!
