### ISSUE TITLE
Images not extracted from docx if target is absolute URI

### ISSUE THREAD

**Issue by lklein53** [jgm/pandoc#7374]
Hi together,

Today I noticed, while converting a docx file to a markdown file, that pandoc ignores images in docx files when the reference path is an absolute path. 
I used the following command `pandoc --verbose --extract-media=/word/media -s test.docx -t markdown -o output.md` with pandoc version 2.5 on linux.

For example
`  <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="/word/media/image1.jpeg" Id="rId6"/>
`
will lead to the image not beeing extracted.
Whereas 
`  <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.jpeg" Id="rId6"/>
`
works fine.
From https://github.com/OfficeDev/Open-XML-SDK/issues/59#issuecomment-251775759 it seems like both absolute URI and relative path should both be correct for the Target attribute. Is this a known limitation ?

Thanks and kind regards,
Lars

**Comment by jgm** [comment]
It would be helpful if you could upload a docx that we could use to reproduce the issue.

**Comment by lklein53** [comment]
Hi,
Thanks for your quick reply.
Please find the working and broken docx files attached.

[broken.docx](https://github.com/jgm/pandoc/files/6640990/broken.docx)
[working.docx](https://github.com/jgm/pandoc/files/6640997/working.docx)

**Comment by jgm** [comment]
Thanks, I think it should be fixed.

**Comment by lklein53** [comment]
Great. Thanks a lot
