### ISSUE TITLE
Can't force raw html tables in markdown

### ISSUE THREAD

**Issue by benabel** [jgm/pandoc#7375]
As commented [here](https://github.com/jgm/pandoc/commit/7c2dd0359b8ece3df91af81338274008c0740a69#commitcomment-52071851). It seems that table without blocks are always rendered  as pipe_tables even if the extension is disabled on the writer.

     pandoc --from markdown  to gfm-pipe_tables

Render simple tabkes(without blocks) as:

    pandoc --from markdown  to gfm

When disabling pipe_tables tables should be rendered as html I think.

**Comment by benabel** [comment]
It works with pandoc markdown writer: `--to markdown-grid_tables-multiline_tables-pipe_tables-simple_tables` render all tables as `html`.

**Comment by jgm** [comment]
I think this is a legitimate issue -- even if it works properly with `-t markdown`, it ought to work with `-t gfm-pipe_tables` and `-t commonmark_x-pipe_tables` too.

**Comment by benabel** [comment]
@jgm thank you very much for this fix.

**Comment by gusbemacbe** [comment]
@jgm 

And [`colspan`](https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown)?
