### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [jgm/pandoc#7380]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by jgm** [comment]
Please contact the maintainer listed in
https://github.com/jgm/pandoc/blob/master/pandoc.cabal
We can add a SECURITY.md.

**Comment by JamieSlome** [comment]
@jgm - if you could also create a `SECURITY.md` with a contactable e-mail that would be great!

**Comment by jgm** [comment]
Done.
