### ISSUE TITLE
Pandoc Conversion Failed Error 61 for HTML Docs

### ISSUE THREAD

**Issue by Stephonomon** [jgm/pandoc#7381]
I'm trying to run the simple script below, but getting an error when linking out to any *.css file located on the internet. It works fine if there is a local *.css file.

```---
title: "Testing"
output:
    html_document:
        css: https://gist.githubusercontent.com/eirikbakke/1059266/raw/d81dba46c76169c2b253de0baed790677883c221/gistfile1.css

        #css: bootstrap.min.css
---


```{r setup, include=FALSE}

```

Error is
```Could not fetch https:/gist.githubusercontent.com/eirikbakke/1059266/raw/d81dba46c76169c2b253de0baed790677883c221/gistfile1.css
InvalidUrlException "https:/gist.githubusercontent.com/eirikbakke/1059266/raw/d81dba46c76169c2b253de0baed790677883c221/gistfile1.css" "URL must be absolute"
Error: pandoc document conversion failed with error 61
Execution halted
```

**Pandoc version?**
Pandoc version is ‘2.14.0.2’, Windows 10, R verson 4.1

**Comment by Stephonomon** [comment]
I believe discussed and possibly solved here. https://github.com/rstudio/rmarkdown/issues/2163

**Comment by jgm** [comment]
OK, this is interesting. The URL reported in the error message only has one `/`, so it' sinvalid. But in your metadata it has two...

**Comment by jgm** [comment]
so if I understand correctly, it turned out to be an rstudio error, not pandoc.

**Comment by Stephonomon** [comment]
Yup, RMarkdown.
