### ISSUE TITLE
Pandoc image sizing when converting from Jupyter notebook to LaTeX

### ISSUE THREAD

**Issue by b-trav** [jgm/pandoc#7386]
I am attempting to use `pandoc` to convert a Jupyter Notebook into a readable pdf.
I have read the [pandoc manual](https://pandoc.org/MANUAL.html#images) section regarding images.
Unfortunately the `ipynb` to `pdf` does not appear to be working as expected.

```bash
pandoc --version
```

gives

```
pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1
```

I am running Ubuntu 20.04 
(also occurs at <https://pandoc.org/try>)

Here is an image, where I would like to specify the width

![Image Caption](test_image.png){ width=1cm }
![test_image](https://user-images.githubusercontent.com/16848340/122333852-55087500-cf6b-11eb-9466-73253926bc5f.png)

Running:

```bash
pandoc -s -o README.tex README.md
pdflatex README.tex
```

gives:

```latex
\begin{figure}
\centering
\includegraphics[width=1cm,height=\textheight]{test_image.png}
\caption{Image Caption}
\end{figure}
```

However, if I put 

```markdown
![Image Caption](test_image.png){ width=1cm }
```

in a markdown cell in a notebook, and run

```bash
pandoc --from ipynb -s -o Pandoc_problems.tex Pandoc_problems.ipynb
pdflatex Pandoc_problems.tex
```

I get:

```latex
\includegraphics{test_image.png}\{ width=1cm \}
```

Instead, I would like to get an `\includegraphics[width=1cm,height=\textheight]` as above.

**Explain the problem.**
Include the exact command line you used and all inputs necessary to reproduce the issue.  Please create as minimal an example as possible, to help the maintainers isolate the problem.  Explain the output you received and how it differs from what you expected.

**Pandoc version?**
What version of pandoc are you using, on what OS?

**Comment by jgm** [comment]
> if I put exactly this text in a markdown cell in a notebook

Do you mean you're putting the LaTeX snippet in a markdown cell?
Does Jupyter allow this?  Does it display it as an image?

When converting markdown in ipynb notebooks, pandoc uses a specific set of extensions, and these don't include the `raw_tex` extension that allows you to pass through raw tex blocks.  (You could try with `-f ipynb+raw_tex`).

**Comment by b-trav** [comment]
Hi @jgm, thanks for the prompt response. I have now clarified my issue above. Sorry for the confusion. Summary: 

In a plain markdown file

```markdown
![Image Caption](test_image.png){ width=1cm }
```

gives

```latex
\includegraphics[width=1cm,height=\textheight]{test_image.png}
```

as expected. In a markdown cell in a Jupyter notebook, it gives:

```latex
\includegraphics{test_image.png}\{ width=1cm \}
```

**Comment by jgm** [comment]
Try with `-f ipynb+link_attributes`.
`link_attributes` is disabled by default for ipynb, because (as far as I know) Jupyter's built in markdown processing doesn't support it.  So if you use this syntax it won't render properly in Jupyter.  If I'm wrong about this, though, we can change the default.

**Comment by b-trav** [comment]
Thank you @jgm, this solved my problem. :+1: 

I understand why you turned this off by default, because it does not render properly in Jupyter, but for me, the pdf is more important than the browser at times, so now I can easily have figures that are the correct size in the pdf.
