### ISSUE TITLE
Add an option to call a post-processor when conversion is finished.

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc#7390]
Default files have gone a long way to remove custom wrapper scripts for calling Pandoc (thank you for that). But I often find myself calling some post-processor or other, typically to minify a file or to do some PDF post-processing with Ghostscript. So an option `--post-processor` to call a system command once conversion is finished strikes me as useful. It might be a good idea for that option to support an `${OUTPUT}` placeholder that is replaced with the name of the output file, but since that option would be intended for the use in default files at any rate, this doesn't strike me as necessary. I'm aware that the utility of such an option is insubstantial, but am still proposing it because it would add little complexity to the code and would, as far as I can say, seem to be little work to implement.

**Comment by jgm** [comment]
This is really the job of the shell.   I don't think it belongs in pandoc.

**Comment by alerque** [comment]
This is the job of either a shell or a build system. There are lots of options for both of those, but this would be a regression as far as the Unix philosophy of doing one thing well. A option like this would break pipelines and confuse build systems for those of us that actually use them, as well as introduce a plethora of issues that the above category of tooling takes care of in various ways but is not trivial to deal with. Having to deal with path management for filters and latex classes etc. is bad enough. Trying to expand outside of A→B conversion would make that worse.

**Comment by odkr** [comment]
Fair enough.
