### ISSUE TITLE
\footcite in input causes parantheses in footnote

### ISSUE THREAD

**Issue by Quintus** [jgm/pandoc#7394]
Given this input LaTeX file:

~~~~~~~ latex
\documentclass[a4paper,ngerman,11pt]{scrartcl}
\usepackage{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[backend=biber,style=verbose-note]{biblatex}

\addbibresource{bibliography.bib}

\begin{document}
\title{Test}
\author{Max Mustermann}
\date{\today}
\maketitle{}
\pagestyle{empty}\thispagestyle{empty}

Dies ist ein Test\footcite[214]{wandt2014ges-sv}.

\end{document}
~~~~~~~

where `bibliography.bib` looks like this:

~~~~~ bibtex
@Book{wandt2014ges-sv,
author       = {Manfred Wandt},
title        = {Gesetzliche Schuldverhältnisse},
shorttitle = {Gesetzl SV},
year      = {2014},
edition   = {6},
publisher = {Franz Vahlen},
location  = {München}}
~~~~~

processing the document with

~~~~~~~~~~
pandoc result.md -C --bibliography=bibliography.bib --csl=juristische-schulung.csl -o result.html
~~~~~~~~~~

where you can find `juristische-schulung.csl` [over here](https://github.com/citation-style-language/styles/blob/master/juristische-schulung.csl) results in the rendered footnote looking as follows:

~~~~~~~~~
1. (Wandt, Gesetzl SV, 6. Aufl. (2014), 214).↩︎
~~~~~~~~~

These parantheses are not mandated by the CSL style and I did not yet see footnotes wrapped in parantheses. I searched around in the tracker and to me it looks as if #6828 looks very similar. However, in that ticket markdown is used as the input format and it is explained one should not use `[]` around the citation within a footnote. Since the input format here is LaTeX, such advise cannot be applied here. I think pandoc should figure out on itself that `\footcite` should not render parantheses since it will always result in footnote-style citations.

Replacing `\footcite` with `\cite` or `\autocite` gives the expected output of

~~~~~~~~~
1.  Wandt, Gesetzl SV, 6. Aufl. (2014), 214↩︎
~~~~~~~~~

Pandoc version:

~~~~~
$ pandoc --version
pandoc 2.14.0.2
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4.0.1, ipynb 0.1.0.1
User data directory: /home/quintus/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
~~~~~

This is on Debian 10 amd64.

**Comment by Quintus** [comment]
> processing the document with

The command given in the OP had a typo in the file name. Since I was in parallel investigating with #7395 it has the md file. Of course, the command given is

~~~~~
pandoc test.tex -C --bibliography=bibliography.bib --csl=juristische-schulung.csl -o result.html
~~~~~

Obviously this does not change the outcome.

> Replacing \footcite with \cite or \autocite gives the expected output of

I found that replacing `\footcite` with `\cite` or `\autocite` will omit the trailing point in the footnote, which is not what I want in this case. Only `\footcite` sets the point, but then also has the parantheses.

**Comment by jgm** [comment]
Diagnosis: the parens are added by notesInParens in T.P.Citeproc.
They shouldn't be added in this case, looking into it.

**Comment by jgm** [comment]
Oh yes, I see now. Since this is a note style, the citation is formatted as a note -- and pandoc has a general routine that avoids notes inside notes by putting them in parentheses.

I still think this is needed in general, but we can avoid it in the special case where the note contains nothing but a single citation.
