### ISSUE TITLE
regression: codeblock attributes not preserved by markdown writer

### ISSUE THREAD

**Issue by dsteurer** [jgm/pandoc#7397]
The markdown writer in the latest release (pandoc 2.14.0.2) omits in some cases attributes of codeblocks.
Earlier versions (at least pandoc 2.12) preserve the attributes correctly. 
(Unfortunately, I don't know which version introduced this regression.)

# Example

Input:

```
~~~~ { .haskell startFrom="100"}
qsort []     = []
qsort (x:xs) = qsort (filter (< x) xs) ++ [x] ++
               qsort (filter (>= x) xs)
~~~~
```

Output of `pandoc -t markdown`: 

```
~~~~ haskell
qsort []     = []
qsort (x:xs) = qsort (filter (< x) xs) ++ [x] ++
               qsort (filter (>= x) xs)
~~~~
```

Expected output: same as input

In this example, the attributes are correctly preserved if another class or an identifier is added to the attributes.

**Comment by jgm** [comment]
Probably due to https://github.com/jgm/pandoc/pull/7242

**Comment by dsteurer** [comment]
Thank you for the quick response!
