### ISSUE TITLE
markdown+autolink_bare_uris includes trailing & in email address

### ISSUE THREAD

**Issue by madduck** [jgm/pandoc#7398]
Using Pandoc 2.9.2.1 on Debian unstable, I discovered a problem wherein Pandoc inaccurately consumes a trailing `&` character into an email address:

```
% echo "&lt;mailbox@example.org&gt;" | pandoc -f markdown+autolink_bare_uris -t html
<p>&lt;<a href="mailto:mailbox@example.org%3E" class="email">mailbox@example.org&gt;</a>;</p>
```

While a trailing `?` may start a query string, a `>` character, or the string `&gt;` as in the above cannot be part of a valid email address, and so should not be included. In fact, as you can see, Pandoc does seem to get quite confused really, as it

1. seems to regard the `&gt;` as part of the email address
2. HTML-decodes the entity for the purpose of base64-encoding it for the `href` attribute
3. duplicates the final semicolon after the rendered link.

Instead of the above, the correct output would be:

```
<p>&lt;<a href="mailto:mailbox@example.org" class="email">mailbox@example.org</a>&gt;</p>
```

**Comment by jgm** [comment]
> only includes the base64-encoded & character in the href attribute;

Note: `%3E` encodes `>`, not `&`.

**Comment by madduck** [comment]
> Note: `%3E` encodes `>`, not `&`.

Thanks, I've edited the issue text accordingly.

**Comment by madduck** [comment]
Thank you @jgm. What a turnaround! ;)
