### ISSUE TITLE
xelatex broken with eps image files

### ISSUE THREAD

**Issue by pandichef** [jgm/pandoc#7399]
**Explain the problem.**
Say I have a markdown file called `mytemplate.md` with the following EPS image:
`![Hello](my_image.eps)`

This works fine on Windows 10:
`pandoc mytemplate.md --pdf-engine xelatex -o output.pdf`

However, on Ubuntu 20.04 (via WSL2 on Windows2), I get this error (follow by many more lines of errors):
`xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.`

When I save the image in `pdf` format (from matplotlib), the error goes away.  It's a decent solution, but the EPS images that I produce on Windows 10 come out much nicer.

**Pandoc version?**
pandoc v2.14.0.2

**Comment by mb21** [comment]
This then seems to be a problem with the xelatex installation on your ubuntu box...
