### ISSUE TITLE
German Image Caption: "Abbildung" in Article, "Figure" in Slides

### ISSUE THREAD

**Issue by patrickbucher** [jgm/pandoc#7408]
**Versions**:

- OS: Arch Linux (current as of 2021-06-25)
- pandoc: 2.14.0.2
- texlive-core: 2021.58710-2
- texlive-bin: 2021.58686-3

```bash
$ pandoc --version
pandoc 2.14.0.2
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,                                                         
citeproc 0.4.0.1, ipynb 0.1.0.1
```

**Example**:

`source.md` (using `lena.png` from https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png):

```markdown
---
title: Image Caption
author: Patrick Bucher
---

# Image

![Image Caption](lena.png){height=80%}

```

Building `article.pdf` and `slides.pdf`:

```bash
$ pandoc --pdf-engine=xelatex -V lang=de source.md -o article.pdf
$ pandoc --pdf-engine=xelatex -t beamer -V lang=de source.md -o slides.pdf
```
Results:

[article.pdf](https://github.com/jgm/pandoc/files/6715658/article.pdf)
[slides.pdf](https://github.com/jgm/pandoc/files/6715659/slides.pdf)

I know it worked before with similar settings a year ago.

In `article.pdf`, the caption starts with "Abbildung" (correct in German), but in `slides.pdf`, the caption starts with "Figure" (which is English).

**Comment by jgm** [comment]
Sorry, I can't reproduce this. I get Abbildung when creating a beamer document with this command line.
texlive 2020, though -- maybe something changed in beamer itself?

**Comment by patrickbucher** [comment]
You're right, it's not a pandoc issue, it happens with texlive itself. Sorry, forgot to check the manual process. I need to get in touch with the KOMAScript guys, I guess...
