### ISSUE TITLE
Underscore in bib results in a non display issue

### ISSUE THREAD

**Issue by Hu1buerger** [jgm/pandoc#7411]
Using pandoc with `--filter pandoc-citeproc` and an included .bib file

where the bibfile contains an entry 

```
@misc{
    ref,
    [some other rendered fields like title and year],
    publisher={twitter.com/user_name/123456}
}
```

# Expected 
the reference that is embedded into the output aka pdf contains the link.

# What happens
The link is not included into the rendering.

If the underscore is removed from the link the file contains the link. But as son as a link contains an undersore it dosnt get rendered and or included into the file.

# Pandoc version

```
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /root/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

```
pandoc-citeproc 0.15.0.1
```

Running on WSL

**Comment by jgm** [comment]
What does this bibtex file do when you use it directly with LaTeX?
Normally `_` isn't allowed unescaped outside of math mode.

**Comment by jgm** [comment]
Also, please note that you're using very old versions.
Pandoc is on 2.14.x, and citeproc support is now built in, so pandoc-citeproc isn't need.d Try upgrading.

**Comment by Hu1buerger** [comment]
@jgm I don't know how latex is handling the underscore in bibtex source.

I also did try to upgrade the version is the newest version available on WSL2 with ubuntu.

**Comment by Hu1buerger** [comment]
I did also reproduce this issue with pandoc 2.14.0.3 on MacOS

**Comment by jgm** [comment]
The question is whether this is a legit *bibtex* file of the sort that you could process using bibtex and pdflatex.  If it's not - if the underscore is going to cause an error here - then pandoc is right not to like it.

I just tried it, with a bit fuller example, and indeed, pdflatex fails on this:
```
! Missing $ inserted.
<inserted text> 
                $
l.11 \newblock twitter.com/user_
                                name/123456, Cambridge, 2000.
? 
```

So, bottom line is that this unescaped `_` is not legal in the bibtex file.
