### ISSUE TITLE
Dokuwiki output: List elements with double line breaks fall back to HTML

### ISSUE THREAD

**Issue by joneuhauser** [jgm/pandoc#7413]
Consider the following Pandoc Markdown:
```
-   This is the first item

-   This is an item

    with a double line break
```

Converting it with `pandoc file.txt -f markdown -t dokuwiki -o output.txt`

results in

```
<HTML><ul></HTML>
<HTML><li></HTML><HTML><p></HTML>This is the first item<HTML></p></HTML><HTML></li></HTML>
<HTML><li></HTML><HTML><p></HTML>This is an item<HTML></p></HTML>
<HTML><p></HTML>with a double line break<HTML></p></HTML><HTML></li></HTML><HTML></ul></HTML>
```
which is overly complicated, because [Dokuwiki's docs](https://www.dokuwiki.org/faq:lists) state that the following is recommended in this case (resulting in an output very similar to Pandoc's markdown): 

```
  * This is the first item
  * This is an item \\ \\ with a double line break
```
which renders like this in native Dokuwiki:
![grafik](https://user-images.githubusercontent.com/12698538/123559427-4193b000-d79c-11eb-8a92-a184b058e859.png)

Since allowing HTML in Dokuwiki is a potential security problem, I'd expect Pandoc to try to convert as much as possible without relying on native HTML tags.

Note: The file I'm originally starting from is a LaTeX file with a double line break in a list item, but the issue is reproducible with Pandoc's markdown format as well.

Pandoc version: 
```
pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1

Ubuntu 20.04
```

**Comment by jgm** [comment]
Semantically, a paragraph with internal hard line breaks is different from two paragraphs. So the output you're recommending would change the meaning.

**Comment by xrat** [comment]
Please note that the use of HTML in DokuWiki is strongly discourage since [DokuWiki v2023-04-04 "Jack Jackrum"](https://www.dokuwiki.org/changes#release_2023-04-04b_jack_jackrum):

> The options to embed HTML and PHP have been **completely removed** for security reasons

**Comment by jgm** [comment]
@xrat that is good to know.  What we should probably do is make dokuwiki output sensitive to the `raw_html` extension, and turn this OFF by default.

However, this would require finding some sensible alternative to use in lists with complex block-level content.  Is there anything in current dokuwiki that would be the equivalent of, for example, the markdown list item

```
1.  this is a paragraph.

   another.

   > and a block quote

   ```ruby
    and.some.code()
   ```

   - and a nested list here
   - with more items
 ```

Any pandoc writer has to render this *somehow*.  Currently we fall back to raw HTML in such cases for dokuwiki.  What is the alternative?

**Comment by xrat** [comment]
> However, this would require finding some sensible alternative to use in lists with complex block-level content. 
> Is there anything in current dokuwiki that would be the equivalent of, for example, the markdown list item

**No**, not in core DokuWiki without syntax extensions/plugins. Cf. [wiki:syntax [DokuWiki]](https://www.dokuwiki.org/wiki:syntax#lists). There is even a FAQ "Multiline List Items" in [faq:lists [DokuWiki]](https://www.dokuwiki.org/faq%3Alists#multiline_list_items): "The list syntax expects you to put each item in a single line".

The following DokuWiki extensions/plugins are worth mentioning in this context:

* [adhoctags](https://www.dokuwiki.org/plugin:adhoctags): Allows selected HTML tags (whitelist approach)
* [htmlok](https://www.dokuwiki.org/plugin:htmlok): Allows all HTML, discouraged for security reasons
* [wrap](https://www.dokuwiki.org/plugin:wrap): Allows to "wrap wiki text inside containers (divs or spans)"

To somewhat illustrate the situation, here are best effort renditions of your example except for the fact that I am using a 2-line blockquote:

**Core DokuWiki list syntax** (all on 1 line with the exception of `<code>` blocks):

``` dokuwiki
  - this is a paragraph.\\ \\ another.\\ \\ > and a\\ > block quote\\ \\ <code ruby>
     and.some.code()
</code>
    - and a nested list here
    - with more items
```

which is rendered as

``` html
<li class="level1 node"><div class="li"> this is a paragraph.<br>
<br>
another.<br>
<br>
&gt; and a<br>
&gt; block quote<br>
<br>
<pre class="code ruby">     and.some.code()</pre>
</div>
<ol>
<li class="level2"><div class="li"> and a nested list here</div></li>
<li class="level2"><div class="li"> with more items</div></li>
</ol>
</li>
```

**DokuWiki list syntax with [wrap extension](https://www.dokuwiki.org/plugin:wrap)**:

``` dokuwiki
  - this is a paragraph \\ <WRAP>

another

> and a
> block quote

<code ruby>
     and.some.code()
</code>

  - and a nested list here
  - with more items
</WRAP>
```

renders as

``` html
<li class="level1"><div class="li"> this is a paragraph <br>
<div class="plugin_wrap">
<p>another</p>
<blockquote><div class="no">
 and a<br>
 block quote</div></blockquote>
<pre class="code ruby">     and.some.code()</pre>
<ol>
<li class="level1"><div class="li"> and a nested list here</div></li>
<li class="level1"><div class="li"> with more items</div></li>
</ol>
</div></div>
</li>
```

**Comment by jgm** [comment]
The WRAP extension looks like it might be the best approach.  Is that in wide use?

**Comment by xrat** [comment]
DokuWiki collects voluntary statistics. According to this data the [wrap extension](https://www.dokuwiki.org/plugin:wrap) is actually the most popular one. Cf. the table at [plugins [DokuWiki]](https://www.dokuwiki.org/plugins?pluginsort=^c#extension__table) accessed just now (not counting the "upgrade" plugin for obvious reasons)

**Comment by jgm** [comment]
One more question about WRAP.  Can you instead do this?
```
  - <WRAP>
this is a paragraph

another

> and a
> block quote

<code ruby>
     and.some.code()
</code>

  - and a nested list here
  - with more items
</WRAP>
```
That would be more uniform and easier to generate.

**Comment by xrat** [comment]
I fully agree. And I have good news: It works.

``` html
<ol>
<li class="level1"><div class="li"> <div class="plugin_wrap">
<p>this is a paragraph</p>
<p>another</p>
<blockquote><div class="no">
 and a<br>
 block quote</div></blockquote>
<pre class="code ruby">     and.some.code()</pre>
<ol>
<li class="level1"><div class="li"> and a nested list here</div></li>
<li class="level1"><div class="li"> with more items</div></li>
</ol>
</div></div>
</li>
</ol>
```

(I've removed some NLs to make the code more compact, e.g. before `</p>` and `</li>`.)

**Comment by jgm** [comment]
Can it handle nested cases, where you have another `<WRAP>..</WRAP>` in the inner list?

**Comment by xrat** [comment]
Yes.
