### ISSUE TITLE
How much memory is needed to convert a 12MB markdown file into EPUB?

### ISSUE THREAD

**Issue by imrek** [jgm/pandoc#7419]
I have 12 MB markdown input files with very simple markdown, basically plain text. 
I'm trying to run `pandoc +RTS -M2048m -RTS -o output.epub input.md` but after a few minutes I get

```
pandoc: Heap exhausted;
pandoc: Current maximum heap size is 2147483648 bytes (2048 MB).
pandoc: Use `+RTS -M<size>' to increase it.
```

How much RAM do I need? 32GB? 64GB? It's a 12MB input file.

**Comment by mb21** [comment]
What pandoc version and can you post the input file?

But yes, pandoc has potential to improve memory management... you may have better luck with `-f commonmark`...
