### ISSUE TITLE
HTML tag <table> in Markdown source will not be converted to DOCX table

### ISSUE THREAD

**Issue by skystar0227** [jgm/pandoc#7420]
I found that table is converted as plain text when converting a Markdown file including raw html tag `<table>` to docx.

```bash
echo '<table><tr><th>A</th><th>B</th></tr><tr><td>1</td><td>2</td></tr></table>' | pandoc -f markdown -o table.docx
```
[table.docx](https://github.com/jgm/pandoc/files/6743937/table.docx)

I expect that raw html table in Markdown is converted into docx table.

I saw this behavior with Pandoc 2.14.0.3 on Windows 10.

Known restriction? or my fault? I have not been able to find any hints from user's guide and previous issues.

**Comment by jgm** [comment]
Raw HTML is passed through as raw HTML, in formats that accept it.  (It is not parsed and converted to the output format.)

Use a native markdown table if you want a docx table.

**Comment by skystar0227** [comment]
Thank you for comment. I have made sense that this is one of restriction.

I use sometime raw html tag `<table>` to describe complicated table not able to written in native table syntax, such as using colspan and/or rowspan, although I know that more expressional new syntax is coming soon.

Currently, my workaround may help someone's same needs:

```bash
echo '<table><tr><th>A</th><th>B</th></tr><tr><td>1</td><td>2</td></tr></table>' | pandoc -f markdown -t html | pandoc -f html -o table.docx
```

**Comment by jgm** [comment]
We could have taken the path of converting raw HTML to other formats, but now that the treatment of raw HTML is pretty well standardized, I wouldn't dare change it.
