### ISSUE TITLE
code blocks rendered in Safari with additional blank line

### ISSUE THREAD

**Issue by aronatkins** [jgm/pandoc#7423]
**Explain the problem.**

Given the Markdown file:

````markdown
---
title: "code block newline"
---

``` {.dockerfile}
RUN curl -fsSL -O https://cdn.rstudio.com/r/${R_DISTRIBUTION}/pkgs/${R_INSTALLER} && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -f -y ./${R_INSTALLER} && \
    rm ${R_INSTALLER} && \
    rm -rf /var/lib/apt/lists/*
```
````

Rendered as:

```bash
pandoc --self-contained newline.md -o newline.html
```

Safari renders this code as:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/362187/124127003-3c0ec200-da49-11eb-8748-9d7602c65921.png">

This appears to happen with any code block lines that overflow the visible region and would need scrolling.

With the addition of the CSS:

```yaml
header-includes: |
  <style>
  pre > code.sourceCode {
    word-wrap: normal;
  }
  </style>
```

Safari renders this code without the additional newline.

<img width="765" alt="image" src="https://user-images.githubusercontent.com/362187/124127119-5779cd00-da49-11eb-92e3-48dac38dbc8c.png">

This workaround is suggested here: https://stackoverflow.com/a/56961220

**Pandoc version?**

2.14.0.3 on macOS 11.4

**Comment by jgm** [comment]
I'm not seeing this behavior.
Here's what it looks like in Safari (rendering with `-s --highlight-style=espresso` so that the code block has a dark background and you can see its boundaries).

<img width="841" alt="Screen Shot 2021-07-01 at 11 05 07 AM" src="https://user-images.githubusercontent.com/3044/124170389-35d61100-da5c-11eb-9056-6354eb5d0d64.png">

And without `-s`:

<img width="719" alt="Screen Shot 2021-07-01 at 11 05 43 AM" src="https://user-images.githubusercontent.com/3044/124170451-49817780-da5c-11eb-80c7-0c52009a96b2.png">

This looks fine.  Do you see something different?  Can you upload a screen shot?

**Comment by jgm** [comment]
Note that if I resize the browser window so that the lines overflow the edge, I still don't get an extra line.

**Comment by aronatkins** [comment]
@jgm The screenshot with the espresso style has the additional blank line I was trying to point out. There is a line of space between the `curl` line and the `export` line.

Running with:

```bash
pandoc -s --highlight-style=espresso newline.md -o newline.html
```

I see the same presentation you included, with the line of space between the `curl` line and `export` line.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/362187/124177048-b48f7600-da7d-11eb-9125-e16172138392.png">

The blank lines are more obvious in other examples, such as:

````markdown
``` {.default}
The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.
The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.
```
````

When rendered with `-s` and espresso highlighting, you get:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/362187/124177470-4b5c3280-da7e-11eb-9be3-de64af23e003.png">

The text region is scrollable to the left and right, but there is a line of space between each line.

Here is that same text rendered with my CSS suggestion:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/362187/124177580-6f1f7880-da7e-11eb-8bb7-0e624d266699.png">

**Comment by aronatkins** [comment]
To restate: The additional line is rendered by Safari immediately after the long-line. Apologies if it accidentally seemed like I was suggesting that there was a trailing line of whitespace.

**Comment by jgm** [comment]
Oh, I get it now. I was assuming it was a blank line at the end.

**Comment by jgm** [comment]
Seems to be a Safari quirk; it doesn't happen on Firefox or Chrome.
Changing the default CSS as follows (adding `word-wrap`) seems to fix it, as you say:
```
    pre code {
      padding: 0;
      overflow: visible;
      word-wrap: normal;
    }
```
@mb21 are there any reasons not to update the default template accordingly?

**Comment by mb21** [comment]
we have [`word-wrap: break-word;` on body](https://github.com/jgm/pandoc/blob/master/data/templates/styles.html#L17), which I think I added to prevent horizontal scroll on smaller screen if you have really long words (like URLs). `pre code` seems to inherit this `word-wrap` setting which indeed doesn't seem to do any good, as we have `overflow: visible` on it anyway... so yes, seems like a good change!

btw. from https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap:

> The property was originally a nonstandard and unprefixed Microsoft extension called word-wrap, and was implemented by most browsers with the same name. It has since been renamed to overflow-wrap, with word-wrap being an alias.

so we might want to switch to the new name... every browser except IE understands that now.
