### ISSUE TITLE
Added leading whitespace in code blocks when converting to HTML

### ISSUE THREAD

**Issue by tfaughnan** [jgm/pandoc#7426]
Given the following example input, `test.md`:

```
---
title: test
---

~~~
def f(x):
    return x ** 2
print(f(3))
~~~
```

And the following HTML template, `template.html`:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>$title$</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
$for(css)$
  <link rel="stylesheet" href="assets/$css$" />
$endfor$
</head>
<body>
    $body$
</body>
</html>
```

I convert to HTML with the command
`pandoc -s  --template=template.html -f markdown -t html test.md -o test.html`

The HTML (rendered here with Chromium 91) has undesired indents on all but the first line of the code block:
![with-template](https://user-images.githubusercontent.com/47096018/124342471-37a1f080-db92-11eb-8741-9937755110fd.png).

This is because the HTML that pandoc produced has extra leading whitespace inside the `<pre>` tag:

```
...
    <pre><code>def f(x):
        return x ** 2
    print(f(3))</code></pre>
...
```

However, if run the command `pandoc -s  -f markdown -t html test.md -o test.html` (same as before, sans my template),
the HTML (again rendered with Chromium 91) does _not_ have the indents. I.e., it is correct:
![without-template](https://user-images.githubusercontent.com/47096018/124342679-9ddb4300-db93-11eb-92c7-d5dced5fda87.png)

And sure enough the HTML that pandoc produced this time does _not_ have extra leading whitespace inside the `<pre>` tag:

```
...
<pre><code>def f(x):
    return x ** 2
print(f(3))</code></pre>
...
```

It seems to me that the issue lies in the generation of the HTML file. Maybe some CSS or JS could make it look better,
but I think this would be better addressed when the HTML is generated rather than when it's displayed in a browser.

__So how can one use a custom HTML template and avoid the added leading whitespace inside the `pre` tag?__

For reference, I am using pandoc 2.14.0.2 on Arch Linux.
Thanks in advance :)

**Comment by jgm** [comment]
The solution is not to indent `$body$` in your template.
If you do indent it, all the content will be indented, so you'll get this extra unwanted space in your code block.
From the manual:

> If a variable occurs by itself on a line, preceded by whitespace
and not followed by further text or directives on the same line,
and the variable's value contains multiple lines, it will be
nested automatically.

**Comment by tfaughnan** [comment]
Ah that makes sense -- thanks for the clarification!
