### ISSUE TITLE
<indexterm> support in DocBook reader?

### ISSUE THREAD

**Issue by bigsmoke** [jgm/pandoc#7427]
The documentation within the DocBook reader [suggests](https://github.com/jgm/pandoc/blob/c8ab8bccf25ad01b9a98b2e59c84c151c5b0c371/src/Text/Pandoc/Readers/DocBook.hs#L211) that `<indexterm>` is supported. However, when I have `<indexterm>` elements, they are interpreted as just any regular old phrase.

Here's an example of 2 index terms in a DocBook source fragment:

```
<primary>IM</primary>
</indexterm>
<indexterm>
<primary>Instant Messaging</primary>
</indexterm>
```

These turn up in the JSON AST without anything to hook on for a filter:

```
{"t":"Str","c":"IM"},{"t":"SoftBreak"},{"t":"Str","c":"Instant"},{"t":"Space"},{"t":"Str","c":"Messaging"}
```

I'm using Pandoc to convert DocBook into LaTeX, and it works surprisingly well (except for a few Lua filters I had to write). `<indexterm>` support is, for now, the one missing piece. If you're interested to have this supported and not interested in implementing this (this being open source and all and you being free to spend your time as you please), I'll consider submitting a patch request.

**Comment by jgm** [comment]
Sure, I think a PR would be welcome -- presumably putting the index terms in spans with attributes, so they can be dealt with by a filter.
