### ISSUE TITLE
SVG file not found issue on Windows

### ISSUE THREAD

**Issue by jdutant** [jgm/pandoc#7431]
Bug #7344 (duplicates #7348, #7350, #7359, #7373) is solved for MacOS/Linux with version 12.14.0.3 but persists on Windows. The new path-handling code seems to call rsvg-convert on a wrong path to SVG files. 

# Bug

Run `pandoc -s test.md -o test.pdf` in a folder with a svg file `Diagram1.svg` and the following `test.md`:

```markdown
![Example diagram](Diagram1.svg)
```

On MacOS the output is produced correctly. On Win (with `rsvg-convert` installed) we get the error:

```
[WARNING] Could not convert image ./tex2pdf.-bbcd86b3e141c2a4\Diagram1.svg: conversion from SVG failed
```

~~An empty test.pdf file is produced~~ **EDIT** No pdf file is produced. A temp working directory `/tex2pdf.-bbcd86b3e141c2a4\` is left in the folder. It contains a copy of the original svg file, `Diagram1.svg`, an empty PDF file `Diagram1.pdf`, and `input.aux` and `input.log`. The latter is the LaTeX log we get within the Pandoc log in `--verbose` mode.

If you convert the SVG file to PNG or PDF, place it in the same folder, and replace `Diagram1.svg` with `Diagram1.pdf` or `Diagram1.png` in markdown, the PDF generation works fine on Windows.

# Workaround

As a temporary workaround I use Inkscape to convert the .svg to .pdf beforehand, and link to the .pdf versions in the markdown instead. 

# Versions

On MacOS and Windows:

pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1

MacOS: rsvg-convert version 2.50.4
Win: rsvg-convert version 2.40.20
 
# Details

Below is a comparison of Pandoc's `--verbose` logs on MacOS and Win (I've just replaced my user folders with %USERNAME% and the like where appropriate). In summary, Pandoc copies the original SVG file in a temp working directory `tex2pdf-<HASH>`, calls `rsvg-convert`, but seems to pass it a wrong path for the svg file, though the correct path to the temporary working directory for stdout. For if you call rvsg-convert with: 

```bash
svg-convert wrongpath/Diagram1.svg > rightpath/Diagram1.pdf
```

and there is no file at `wrongpath/Diagram1.svg`, but `rightpath` correctly points out to the temp working directory, what you will get is:

* a message `Error reading SVG:Error opening file: No such file or directory` in stderror
* a empty PDF file `Diagram1.pdf` in the temp working directory.

Which is exactly the error I get. So Pandoc seems to pass an incorrect path for `wrongpath` in the command above but the correct path to the temp working directory for `rightpath` (or it's calling rsvg-convert with this directory as pwd). 

One thing to note: the logs below mention the path `./tex2pdf.-1e0ad2b9dc7e1974\Diagram1.svg`. As it mixes two types of directory separator I wondered whether this was the source of the bug. But it turns out that this is fine in Windows. If you run commands like the following from the source directory (which itself contains Pandoc's temp working directory `./tex2pdf.-1e0ad2b9dc7e1974\`), you do get a converted PDF file:

```bash
rsvg-convert ./tex2pdf.-1e0ad2b9dc7e1974\Diagram1.svg > Diagram-test.pdf
rsvg-convert "./tex2pdf.-1e0ad2b9dc7e1974\Diagram1.svg" > Diagram-test.pdf
```
So that path isn't the source of the bug, provided it's used from the right folder. 

One thing that *may* be the problem is that in the MacOS log I see absolute paths throughout, not relative ones like the one above. 

## Windows log

```
[INFO] Loaded Diagram1.svg from Diagram1.svg
Error reading SVG:Error opening file: No such file or directory

[WARNING] Could not convert image ./tex2pdf.-1e0ad2b9dc7e1974\Diagram1.svg: conversion from SVG failed
[makePDF] temp dir:
./tex2pdf.-1e0ad2b9dc7e1974
[makePDF] Command line:
pdflatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "./tex2pdf.-1e0ad2b9dc7e1974" "./tex2pdf.-1e0ad2b9dc7e1974/input.tex"

[makePDF] Relevant environment variables:
("TEXINPUTS","./tex2pdf.-1e0ad2b9dc7e1974;")
("TEXMFOUTPUT","./tex2pdf.-1e0ad2b9dc7e1974")

[makePDF] Source:
```
... TeX source here. relevant line, l.74:
```
\includegraphics{./tex2pdf.-1e0ad2b9dc7e1974/Diagram1.svg}
```
...
```
\end{document}

[makePDF] Run #1
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.6.28)
entering extended mode
(tex2pdf.-1e0ad2b9dc7e1974/input.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-06-18>
(C:\Users\%USERNAME%\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
```
...
standard TeX log loading packages up to:
...
```
 (C:\Users\%USERNAME%\AppData\Roaming\MiKTeX\tex/latex/microtype\mt-msa.cfg)
(C:\Users\%USERNAME%\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsb.fd)
 (C:\Users\%USERNAME%\AppData\Roaming\MiKTeX\tex/latex/microtype\mt-msb.cfg)

! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.74 ...{./tex2pdf.-1e0ad2b9dc7e1974/Diagram1.svg}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on "C:\Users\%USERNAME%\%MARKDOWN-SOURCE-PATH%\tex2pdf.-1e0ad2b9dc7e1974\input.log".

[makePDF] Run #2
```
... exactly identical to Run `#1`, ends with:

```
 (C:\Users\Golden Mole\AppData\Roaming\MiKTeX\tex/latex/microtype\mt-msb.cfg)

! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.74 ...{./tex2pdf.-1e0ad2b9dc7e1974/Diagram1.svg}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on "C:\Users\%USERNAME%\%MARKDOWN-SOURCE-PATH%\tex2pdf.-1e0ad2b9dc7e1974\input.log".

Error producing PDF.
! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.74 ...{./tex2pdf.-1e0ad2b9dc7e1974/Diagram1.svg}
```

End result: an empty (zero-byte) PDF file in the source's folder. A leftover temporary working directory containing `input.log` (the LaTeX log above), `input.aux`, a copy of the original `Diagram1.svg`, an empty PDF `Diagram.pdf`. 

## MacOS log

```
[INFO] Loaded Diagram1.svg from Diagram1.svg
[makePDF] temp dir:
/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead6e8e
[makePDF] Command line:
pdflatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead6e8e" "/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead6e8e/input.tex"

[makePDF] Relevant environment variables:
("TEXINPUTS","/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead6e8e:")
("TEXMFOUTPUT","/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead6e8e")
("TMPDIR","/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/")
("LANG","en_GB.UTF-8")
("SHELL","/bin/zsh")
("HOME","/Users/%HOME%")
("PATH","/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin")
("PWD","/Users/%USERNAME%\%MARKDOWN-SOURCE-PATH%")

[makePDF] Source:
```
... TeX source here ... relevant line, l. 74:
```
\includegraphics{/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead6e8e/Diagram1.pdf}
```
...
```
[makePDF] Run #1
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode

(/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead
6e8e/input.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/article.cls
```
... normal LaTeX log ... ends with:
```
(/usr/local/texlive/2021/texmf-dist/tex/latex/microtype/mt-msa.cfg)
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsfonts/umsb.fd)
(/usr/local/texlive/2021/texmf-dist/tex/latex/microtype/mt-msb.cfg) [1{/usr/loc
al/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map} </private/var/fol
ders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead6e8e/Diagram1.pdf
>]
(/private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2pdf.-44676666dead
6e8e/input.aux) ){/usr/local/texlive/2021/texmf-dist/fonts/enc/dvips/lm/lm-ec.e
nc}</usr/local/texlive/2021/texmf-dist/fonts/type1/public/lm/lmr10.pfb></usr/lo
cal/texlive/2021/texmf-dist/fonts/type1/public/lm/lmr12.pfb></usr/local/texlive
/2021/texmf-dist/fonts/type1/public/lm/lmr17.pfb>
Output written on /private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/tex2
pdf.-44676666dead6e8e/input.pdf (1 page, 82224 bytes).
Transcript written on /private/var/folders/j2/zp5ggjhx12xccgy5_wx32tfw0000gp/T/
tex2pdf.-44676666dead6e8e/input.log.

[makePDF] Run #2
```
... exactly identical to run `#1`...

**Comment by jgm** [comment]
I've pushed what might be a fix -- but not having Windows handy, I can't test.
Can you test it?

**Comment by jdutant** [comment]
Thanks! I'll give it a shot tomorrow (never complied pandoc from source, I'll see how that goes on Win).

**Comment by jgm** [comment]
By tomorrow there should be a Windows nightly available.

**Comment by jdutant** [comment]
Thanks, much easier. Unfortunately I still get an error, albeit a slightly different one. I downloaded the nightly build, renamed it `pandoc2.exe` to make sure I was running it and not my installed version. Running `pandoc2 --verbose -s test.md -o test.pdf` I get the same log as before (below).

A question in case we do more tests and I want to build pandoc before the nightly arrives: I cloned the repo, installed `stack` and ran `stack setup`. Am I right that if I run `stack install ----flag pandoc:embed_data_files` it will compile a binary in the same folder, that I can test without touching at my release binary or my path?

A minor edit to the inital bug report: I said an empty output pdf file was created, but as the log indicates, no PDF file is created for the main markdown source. (There's only the empty pdf file Diagram1.pdf in the temp working directory.) This is true for the release build and the nightly build.

# Log

```
[INFO] Loaded Diagram1.svg from Diagram1.svg
Error reading SVG:Error opening file: No such file or directory

[WARNING] Could not convert image ./tex2pdf.-5d0dcd8ef86850be\Diagram1.svg: conversion from SVG failed
[makePDF] temp dir:
./tex2pdf.-5d0dcd8ef86850be
[makePDF] Command line:
pdflatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "./tex2pdf.-5d0dcd8ef86850be" "./tex2pdf.-5d0dcd8ef86850be/input.tex"

[makePDF] Relevant environment variables:
("TEXINPUTS","./tex2pdf.-5d0dcd8ef86850be;")
("TEXMFOUTPUT","./tex2pdf.-5d0dcd8ef86850be")

[makePDF] Source:
```
Follows the TeX source with line 76:
```
\includegraphics{./tex2pdf.-5d0dcd8ef86850be/Diagram1.svg}
```
Then the two LaTeX logs that end with:
```
(C:\Users\%USER%\AppData\Local\Programs\MiKTeX\tex/latex/amsfonts\umsb.fd)
 (C:\Users\%USER%\AppData\Roaming\MiKTeX\tex/latex/microtype\mt-msb.cfg)

! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.76 ...{./tex2pdf.-5d0dcd8ef86850be/Diagram1.svg}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on "C:\Users\%USER%%PATHTOSOURCE%\tex2pdf.-5d0dcd8ef86850be\input.log".
```
And the final Pandoc error message:
```
Error producing PDF.
! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.76 ...{./tex2pdf.-5d0dcd8ef86850be/Diagram1.svg}
```

**Comment by jgm** [comment]
> Am I right that if I run stack install ----flag pandoc:embed_data_files it will compile a binary in the same folder, that I can test without touching at my release binary or my path?

You don't need to set the flag explicitly, as it's true by default in stack.yaml.
`stack install` will put the binary in `~/.local/bin`.
You can do `stack build` which will just build it locally.
To run the locally built pandoc, you can either examine the path (which will be output in the build log) and run the binary directly, or you can use
```
stack exec pandoc -- -f markdown -t epub etc.
```
Note the `--` before the options.

**Comment by jgm** [comment]
Can you test directly with `rsvg-convert` on Windows?
Maybe it is expecting unix-style paths.
Try it with both windows paths and unix (forward-slash) paths.

**Comment by jgm** [comment]
The command pandoc is running is something like
```
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o path/to/output.pdf path/to/input.svg
```

**Comment by jdutant** [comment]
Looks like anything goes! I'm trying this on the `CMD` shell. I've put my source file in `input\sub` (sub-sub folder relative to pwd) and I'm placing outputs in `output\sub`. Later I renamed `input` and `output` with names like Pandoc's temp folder to see whether that generates an error. I've tried Unix and Win path separators, mixing them, adding `./`, doubling the separator, mixing them. I never got an error: all 16 pdf output files are properly generated. If I pass a non-existent location to the output parameter I do get an `Error writing PDF` message (whether the input exists or not); if I pass an non-existent location to the input parameter  I do get the `Error reading SVG: Error opening file: no such file or directory` message. But I didn't get either with any of the commands below, in the `CMD` shell.

```
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o output/sub/output.pdf input/sub/Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o output\sub\output2.pdf input\sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o ./output\sub\output3.pdf ./input\sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o .\output\sub\output4.pdf .\input\sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o ./output\sub/output5.pdf ./input\sub/Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o .\output/sub\output6.pdf .\input/sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o o2p.-cd8e\sub\output7.pdf i2p.-5d0c\sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o ./o2p.-cd8e\sub\output8.pdf ./i2p.-5d0c\sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o ./o2p.-cd8e/sub/output9.pdf ./i2p.-5d0c/sub/Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o "./o2p.-cd8e/sub/output10.pdf" "./i2p.-5d0c/sub/Diagram1.svg"
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o "./o2p.-cd8e\sub\output11.pdf" ".\i2p.-5d0c\sub\Diagram1.svg"
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o "./o2p.-cd8e/sub\output12.pdf" "./i2p.-5d0c/sub\Diagram1.svg"
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o ".\o2p.-cd8e/sub\output13.pdf" ".\i2p.-5d0c/sub\Diagram1.svg"
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o o2p.-cd8e\sub\output14.pdf i2p.-5d0c\\sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o o2p.-cd8e\sub\output15.pdf .\\i2p.-5d0c\\sub\Diagram1.svg
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o o2p.-cd8e\sub\output16.pdf .//i2p.-5d0c//sub\Diagram1.svg
```

**Comment by jgm** [comment]
Hm, can you try
```
pandoc test.md --extract-media=./tex2pdf.-bbcd86b3e141c2a4
```

**Comment by jdutant** [comment]
I tried with the stable and the latest nightly, the results are the same: the folder is created with a copy of the SVG and the log is:

```
[INFO] Loaded Diagram1.svg from Diagram1.svg
<figure>
<img src="./tex2pdf.-bbcd86b3e141c2a4\Diagram1.svg" alt="Diagram 1. Trajectory of the ball." /><figcaption aria-hidden="true">Diagram 1. Trajectory of the ball.</figcaption>
</figure>
```

**Comment by jgm** [comment]
I pushed a change that may help -- can you try?

**Comment by jdutant** [comment]
Tried with nightly (includes https://github.com/jgm/pandoc/commit/477a67061f06827b7e807319404cc277a417e9d0) but no luck, sorry! I get the same output log on Win with stable and nightly:

```
[INFO] Loaded image.svg from image.svg
Error reading SVG:Error opening file: No such file or directory

[WARNING] Could not convert image ./tex2pdf.-20ce6154e22abd27/image.svg: conversion from SVG failed
[makePDF] temp dir:
./tex2pdf.-20ce6154e22abd27
```

NB, I've renamed the test svg file `image.svg`, otherwise all is the same. I double checked that the same files process correctly on MacOS.  I've double-checked that on Win the stable and nightly process the markdown file well when we link instead to a image.pdf generated with `rsvg-convert -f pdf` on Win.

In case that would help: if you wanted to do a branch of Pandoc that logs everything it does around the rsvg-convert step I'd be happy to compile it, run it and get you the log.

**Comment by jgm** [comment]
Hm.  If you create a directory called `tex2pdf.-20ce6154e22abd27` and put image.svg there, then try to convert with
```
rsvg-convert -f pdf -a --dpi-x 92 --dpi-y 92 -o ./tex2pdf.-20ce6154e22abd27/output.pdf ./tex2pdf.-20ce6154e22abd27/input.svg
```
does that work?  Wondering if maybe there's a problem with the `.` in the directory name.

**Comment by jdutant** [comment]
That's it! I got a `Error reading SVG:Error opening file: No such file or directory`.

**Comment by jgm** [comment]
OK, can you try compiling the issue7431 branch ?  I've added some logging that may shed light.

**Comment by jdutant** [comment]
Thanks, here is the resulting log. It looks like the temp folder name is duplicated in `svgIn`!

```bash
pandoc.exe" -s test.md -o test.pdf --verbose 2> test.log
```

Verbose log:

```
[INFO] Loaded Diagram1.svg from Diagram1.svg
[("tmpdir","./tex2pdf.-e2c94a066d641fcc"),("fname","./tex2pdf.-e2c94a066d641fcc/Diagram1.svg")]
Error reading SVG:Error opening file: No such file or directory

[("dpi","96"),("pdfOut","tex2pdf.-e2c94a066d641fcc\\Diagram1.pdf"),("svgIn","tex2pdf.-e2c94a066d641fcc\\tex2pdf.-e2c94a066d641fcc\\Diagram1.svg")]
("stdout","")
[WARNING] Could not convert image ./tex2pdf.-e2c94a066d641fcc/Diagram1.svg: conversion from SVG failed
[makePDF] temp dir:
./tex2pdf.-e2c94a066d641fcc
[makePDF] Command line:
pdflatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "./tex2pdf.-e2c94a066d641fcc" "./tex2pdf.-e2c94a066d641fcc/input.tex"

[makePDF] Relevant environment variables:
("TEXINPUTS","./tex2pdf.-e2c94a066d641fcc;")
("TEXMFOUTPUT","./tex2pdf.-e2c94a066d641fcc")

[makePDF] Source:
```

**Comment by jgm** [comment]
Aha!

**Comment by jgm** [comment]
Thanks for your help in diagnosing this.
