### ISSUE TITLE
Bullet symbols of nested list are not converted correctly when exporting from Org-mode to Markdown

### ISSUE THREAD

**Issue by taquangtrung** [jgm/pandoc#7432]
Hi,

When using Pandoc (version 2.14.0.3), I notice that the bullet symbols of nested list items are not exported correctly.

For example, given then the input file in the Org-mode format `test.org`:

  ```org
  * Section
  ** Subsection
   - List 1
   - List 2
     + Sub-list A
     + Sub-list B
  ```

After running Pandoc: `pandoc -f org -t gfm test.org` to convert it into the Markdown format, the output file:

   ```markdown
   # Section
   ## Subsection
   -   List 1
   -   List 2
       -   Sub-list A                   // Expect that the bullet symbol is `+`
       -   Sub-list B
   ```

Here, the bullet of the sub-list is `-`, while the original bullet is `+`.

Do you think that this is a bug or is there any way to properly convert the bullet symbols?

Thank you!

**Comment by agusmba** [comment]
AFAIK pandoc does not preserve that kind of formatting. Probably not a bug.

**Comment by jgm** [comment]
No, we only parse and reproduce the abstract structure; concrete aspects like this are not in scope.

**Comment by taquangtrung** [comment]
Thank you for the explanation!
