### ISSUE TITLE
Weird bug where characters following an implicit raw latex environment are omitted by pandoc

### ISSUE THREAD

**Issue by HAL2000-human** [jgm/pandoc#7434]
The issue arises when you use the fact, that LaTeX commands are detected as raw Latex in most cases. Take the following MWE:
```markdown
\begin{proof}
\newcommand{\x}{\left.\right.}
\x
\end{proof}

1234567890abcdefghi
```
When converting to native AST using pandoc 2.14.0.3 I get:
```haskell
[RawBlock (Format "tex") "\\begin{proof}\n\\newcommand{\\x}{\\left.\\right.}\n\\left.\\right.\n\\end{proof}"
,Para [Str "0abcdefghi"]]
```
So the characters `123456789` are missing. Notably this seems to ignore the characters in the source before parsing them, because if you  happen to have a heading there, it simply gets ignored:
```markdown
\begin{proof}
\newcommand{\x}{\left.\right.}
\x
\end{proof}

# 1234567890abcdefghi

```
turn into
```haskell
[RawBlock (Format "tex") "\\begin{proof}\n\\newcommand{\\x}{\\left.\\right.}\n\\left.\\right.\n\\end{proof}"
,Para [Str "890abcdefghi"]]
```

Also, if you explicitly state that the latex portion is latex, the problem vanishes:
`````markdown
```{=latex}
\begin{proof}
\newcommand{\x}{\left.\right.}
\x
\end{proof}
```

1234567890abcdefghi
`````
turns into
```haskell
[RawBlock (Format "latex") "\\begin{proof}\n\\newcommand{\\x}{\\left.\\right.}\n\\x\n\\end{proof}"
,Para [Str "1234567890abcdefghi"]]
```

I suspect some sort of problem that arises in conjunction with pandoc trying to parse the `\newcommand` in case it is used elsewhere, but my Haskell-skills are far to few to check, sadly.

Also, the usage of `\left` seems to be necessary for the bug to occur.

**Pandoc version?**
```
pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1
```
I am running pandoc on Debian in WSL2 on Windows 10. I also checked on https://pandoc.org/try.

**Comment by jgm** [comment]
I'm not able to reproduce this.
See try pandoc:
<https://pandoc.org/try/?text=%5Cbegin%7Bproof%7D%0A%5Cnewcommand%7B%5Cx%7D%7B%5Cleft.%5Cright.%7D%0A%5Cx%0A%5Cend%7Bproof%7D%0A%0A1234567890abcdefghi%0A&from=latex&to=native&standalone=0>

Perhaps it's some odd Windows or WSL thing?

**Comment by jgm** [comment]
Oh sorry!  You're converting from markdown, not latex, of course.
I can reproduce.

**Comment by HAL2000-human** [comment]
Oh, sorry, I did not specify this. I converted form markdown: https://pandoc.org/try/?text=%5Cbegin%7Bproof%7D%0A%5Cnewcommand%7B%5Cx%7D%7B%5Cleft.%5Cright.%7D%0A%5Cx%0A%5Cend%7Bproof%7D%0A%0A1234567890abcdefghi%0A&from=markdown&to=native&standalone=0

**Comment by jgm** [comment]
Probably the issue lies in `rawLaTeXParser` in T.P.Readers.LaTeX.Parsing.
It has to do some gnarly converting between strings and tokenized tex, dealing also with macro expansion.
Probably the macros are the issue; if you try with `markdown-latex_macros` it will work.

**Comment by jgm** [comment]
After we parse the tex tokens, we have to figure out how many characters of the textual input to consume.
Looks like we do this by examining the tokens output of `withRaw`, but this is going to be problematic when macros increase the length of the tokens. I think that's what is happening here.
I'm not sure why we aren't just consulting the source location info in the tex tokens; I vaguely remember there was a reason, but that's worth a try.
