### ISSUE TITLE
Clarify error meassage(s)

### ISSUE THREAD

**Issue by moapwr** [jgm/pandoc#7439]
Just got surprised with a very ambiguous error message:

$ pandoc --pdf-engine=wkhtmltopdf -f html -t pdf -o "$out"
pdf-engine wkhtmltopdf is not compatible with output format pdf

**Comment by jgm** [comment]
That's a surprising message indeed, and we might want to tweak it.

Orginally we didn't allow `-t pdf` at all -- you had to do `-t latex` or `-t html` and then use an appropriate pdf-engine for the format you chose.

So many people were doing `-t pdf` that we started allowing (but it defaults to latex).

**Comment by jgm** [comment]
Wait, what pandoc version are you using? I can't reproduce this with recent versions. I suspect this issue has been fixed for quite a while.
