### ISSUE TITLE
\cline in LaTeX results gives unexpected conversion to HTML5

### ISSUE THREAD

**Issue by leenamurgai** [jgm/pandoc#7442]
Using the online converter --from LaTeX --to HTML5
```
\begin{table}[h!]
\begin{tabular}{|c|c|c|c|c|}
\cline{2-5}
\multicolumn{2}{c|}{} & \multicolumn{2}{c|}{Ground Truth} & \multirow[b]{2}{*}{Metric} \\
\end{tabular}
\end{table}
```
gives
```
<table>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;" colspan="2">Ground Truth</td>
<td style="text-align: center;">Metric</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
```
while
```
\begin{table}[h!]
\begin{tabular}{|c|c|c|c|c|}
\cline{2-5}
\multicolumn{2}{c|}{} & \multicolumn{2}{c|}{Ground Truth} & \multirow[b]{2}{*}{Metric} \\
\end{tabular}
\end{table}
```
gives
```
<table>
<tbody>
<tr class="odd">
<td style="text-align: center;" colspan="2"></td>
<td style="text-align: center;" colspan="2">Ground Truth</td>
<td style="text-align: center;">Metric</td>
</tr>
</tbody>
</table>
```
Using ```\cline{2-5}``` instead of ```\hline``` in LaTeX result in a missing ``` colspan="2"``` in the first cell.

**Comment by jgm** [comment]
Pandoc's LaTeX parser currently doesn't recognize cline.
I can fix that easily enough (though the easy fix won't give you the actual line; it will just fix this colspan issue).

**Comment by leenamurgai** [comment]
Awesome! I'm less bothered about the actual line, there are usually ways around that. It's more important that table data doesn't disappear in translation because \multicolumn doesn't translate :)

Thank you @mb21  and @jgm!
