### ISSUE TITLE
Import issue in Ghostwriter 1.7.4

### ISSUE THREAD

**Issue by AuroraMartell** [jgm/pandoc#7445]
I'm working on a document in Ghostwriter 1.7.4 with Pandoc installed, but whenever I try to live preview my document, it throws me this error:

_Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information._

How do I fix this?

**Comment by jgm** [comment]
This is an issue for ghostwriter, not pandoc, so report it there.
Ghostwriter is assuming an older pandoc version, apparently.
