### ISSUE TITLE
Failing citeproc tests

### ISSUE THREAD

**Issue by hololeap** [jgm/pandoc#7449]
I'm getting a couple failing tests when I try to build `pandoc-2.14.1` (`ghc-8.10.5` `citeproc-0.4.1`) in Gentoo.

I'm not sure, but it could be related to jgm/citeproc/issues/81

```
    pandoc-citeproc-320.md
      #1:                                                            FAIL (0.63s)
        --- test/command/pandoc-citeproc-320.md
        +++ pandoc --citeproc -t markdown-citations
        +   4 n.d.; Villa-Lobos, n.d.; Villafuerte, n.d.).
        -   4 n.d.; Villafuerte, n.d.; Villa-Lobos, n.d.).
        +   9 Foo (Saint-Gaudens, n.d.; Saint-Saëns, n.d.; Sainte-Beuve, n.d.; San
        -   9 Foo (Sainte-Beuve, n.d.; Saint-Gaudens, n.d.; Saint-Saëns, n.d.; San
        -  85 ::: {#ref-itemC1 .csl-entry}
        -  86 Sainte-Beuve, C.-A. (n.d.).
        -  87 :::
        -  88 
        +  93 ::: {#ref-itemC1 .csl-entry}
        +  94 Sainte-Beuve, C.-A. (n.d.).
        +  95 :::
        +  96 
        + 117 ::: {#ref-itemA14 .csl-entry}
        + 118 Villa-Lobos, J. (n.d.).
        + 119 :::
        + 120 
        - 120 
        - 121 ::: {#ref-itemA14 .csl-entry}
        - 122 Villa-Lobos, J. (n.d.).
        - 124 :::
```

```
    pandoc-citeproc-31.md
      #1:                                                            FAIL (0.56s)
        --- test/command/pandoc-citeproc-31.md
        +++ pandoc --citeproc -t markdown-citations
        +   4 ::: {#ref-item2 .csl-entry}
        +   5 'Second Title'
        +   6 :::
        +   7 
        -   8 
        -   9 ::: {#ref-item2 .csl-entry}
        -  10 'Second Title'
        -  12 :::
```

**Comment by jgm** [comment]
Interesting.  We build on linux in CI and do not get these test failures there.
These look like sorting differences.
My guess is that they stem from different default locales?
What does `echo $LANG` say on your gentoo system?

**Comment by hololeap** [comment]
`en_US.utf8`

**Comment by hololeap** [comment]
`locale`:

```
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME=en_CA
LC_COLLATE=C
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by hololeap** [comment]
I did find this chart with all the default locales for virtual environments. Maybe it will help?
https://github.com/actions/virtual-environments/issues/3120#issuecomment-815492874

**Comment by jgm** [comment]
That's not the issue, then; I have the same locally.

**Comment by jgm** [comment]
What flags are you using?  Are you using `icu` by chance in compiling citeproc?

**Comment by hololeap** [comment]
Yes, the `icu` flag is enabled by default and I didn't turn it off. I tried recompiling with `LC_COLLATE=C.UTF-8` and it didn't make a difference. It could be a discrepancy with another library. The state of Gentoo's repos most likely doesn't match what you have for `stack`. I'm trying to develop the latest version of `pandoc` and deps as Gentoo packages, and it should mirror the way you would compile by hand pretty closely, but we don't have a set list of dependency versions like `stack` provides. Let me know if there's any more info I can give you.

**Comment by hololeap** [comment]
I have `icu` turned on and `executable` turned off.

**Comment by felixonmars** [comment]
I have tried to enable `-ficu` for citeproc on Arch, and many test failures come within citeproc's test suite: https://github.com/jgm/citeproc/issues/83

I then proceeded to build pandoc with `-ficu` enabled citeproc, and reproduced exactly the same failures as you reported here.

**Comment by hololeap** [comment]
@felixonmars Confirmed. I rebuilt citeproc with the `icu` flag disabled and all of the pandoc tests passed after rebuilding it.

**Comment by jgm** [comment]
I've made some changes in citeproc that should fix this.
You can try compiling pandoc against commit citeproc commit 0a6917013bee93832f637d4eb8ad667872273914
Note that the behavior seems to differ with different icu versions...

**Comment by felixonmars** [comment]
I can confirm that https://github.com/jgm/citeproc/commit/50d14d938c883a8835550933df4004050b0b3902 fixed both libraries' tests. Thanks!

**Comment by hololeap** [comment]
This also worked for me as well. Closing.
