### ISSUE TITLE
arraystretch affects author block

### ISSUE THREAD

**Issue by a-kohout** [jgm/pandoc#7452]
arraystretch defined in header-includes to add table row spacing affects author block when rendering pdf.
It does not affect subtitle or date blocks and happens with or without --pdf-engine=xelatex.

pandoc: 2.14.1
OS: macOS 11.4

test.md:
```
---
lang: en-US
title: Test title
subtitle: |
  Subtitle line 1\
  Subtitle line 2
author: |
  Author line 1\
  Author line 2
date: |
  Date line 1\
  Date line 2
header-includes: |
  \renewcommand{\arraystretch}{1.4}
---

# Test heading

Some text

| col1  | col2  |
|:----- |:----- |
| test1 | test2 |
| test1 | test2 |
```

Render:
```
pandoc test.md -o test.pdf
```
![image](https://user-images.githubusercontent.com/26367956/126571888-945b55d9-12c9-4aa5-bf8c-554c9c17a8a6.png)

**Comment by jgm** [comment]
Weird. The generated tex is just
```
\subtitle{Subtitle line 1\\
Subtitle line 2}
\author{Author line 1\\
Author line 2}
\date{Date line 1\\
Date line 2}
```
So this must have to do with the internal implementation of `\author` or `\maketitle`.

**Comment by jgm** [comment]
Anyway, I don't see this as a pandoc bug.  It is a LaTeX quirk; you're using raw LaTeX.
I would suggest doing it this way:
```
\usepackage{etoolbox}
\BeforeBeginEnvironment{longtable}{\renewcommand{\arraystretch}{1.4}}
```
(untested)

**Comment by a-kohout** [comment]
That works perfectly.
Thanks!
