### ISSUE TITLE
Leading whitespace is removed from inline verbatim

### ISSUE THREAD

**Issue by pck1980** [jgm/pandoc#7457]
**Explain the problem.**
I just found out that both leading and trailing whitespace seems to be removed from inline verbatim text (tested with beamer and HTML output).
So, for example ``Hello`                   World` `` renders as `HelloWorld`
Is this behavior intended? I would have expected that all whitespace inside verbatim text is preserved.

**Pandoc version?**
2.14.1 on macOS

**Comment by mb21** [comment]
I can reproduce: https://pandoc.org/try/?text=Hello%60+World%60&from=markdown&to=&standalone=0

While it does the expected thing with the commonmark reader...

**Comment by jgm** [comment]
Yes, it's intended.  The vast majority of Markdown implementations have always behaved this way:
<https://johnmacfarlane.net/babelmark2/?normalize=1&text=%60+hi%60%0A>

Commonmark recently adopted a more subtle rule that allows leading whitespace in some cases (see <https://spec.commonmark.org/0.30/#code-spans>), but pandoc's markdown reader predates this by quite a lot.
