### ISSUE TITLE
rebase_relative_paths fails when tabbed

### ISSUE THREAD

**Issue by parthi2929** [jgm/pandoc#7464]
### Explain the problem.
When image link is tabbed, `rebase_relative_paths` is not executed so the reference fails in image. 

### Simple Example
_Folder Structure:_
**bug01**
* 01
  * assets
    * image01.png
  * 01_chap.md
* out
  * test.pdf
* tools
  * md2pdf.sh
* README.md

The `01_chap.md` refers to image in `assets` folder in same `01` folder. The pandoc script is run at root folder `bug01`. The idea is, later I may have folders like `02`,`03`, etc. each containing markdown files and each with own assets folder. This is why rebase extension is perfect fit, so when pandoc runs at one folder above, I can re base the image links. This works fine as long as there is no tab like below. 

```
![](assets/image01.png)
```

But if I have a tabbed on image link, (within a list/unlist structure), rebasing does not happen. Below one simply fails.  

```
    ![](assets/image01.png)
```

The script, located in tools folder is concisely as below (generalized in `md2pdf.sh` script file).

```
cd "./"
pandoc \
    --pdf-engine=xelatex \
    -f markdown+rebase_relative_paths \
    -o "./out/test.pdf" \
     "**/*.md" \
```

**Pandoc version?**
pandoc.exe 2.14.0.3

**Example Attachment:**  
[bug01.zip](https://github.com/jgm/pandoc/files/6898067/bug01.zip)

**Comment by jgm** [comment]
I don't understand what you mean by "tabbed" here.
Can you give a *minimal* example that shows the problem?  As small as possible.

**Comment by jgm** [comment]
If I understand correctly, you're saying that when the image link occurs nested in a list item, the relative path rebasing doesn't happen.

**Comment by jgm** [comment]
I have been able to reproduce this.  Looking into it.

**Comment by jgm** [comment]
OK, I see what is happening here.

The markdown reader currently parses list items by parsing the raw list item contents, then parsing this using parseFromString. But source positions aren't properly recorded when we do this, so we lose the fact that this is in the `01` subdirectory.

The commonmark reader uses a better strategy, and this bug doesn't appear with it (or `commonmark_x` or `gfm` which are both based on it).

I'll see if we can't improve the markdown reader.

**Comment by parthi2929** [comment]
@jgm but this issue is closed, so will this bugfix for markdown reader be planned?

**Comment by jgm** [comment]
The fix is already committed to the repository (see above).
It will be in the next release.
