### ISSUE TITLE
Turn translation of BCP 47 language specifications into babel/polyglossia specifications into a pipe

### ISSUE THREAD

**Issue by dmkaplan2000** [jgm/pandoc#7465]
**Describe your proposed improvement and the problem it solves.**

I recently created a custom pandoc template for creating a scientific article and I had a problem that I wanted to include multiple abstracts in different languages in the YAML header. This required me to specify the language of each abstract. The problem is that I couldn't specify the languages using BCP47 format as babel does not accept this when loading a language (later, when using a language, babel can use BCP47 specifications, but not at the loading stage as far as I can tell). This forced me to specify the overall language of the document in BCP47, but specify the language of the abstracts in babel/polyglossia format, which is inconsistent and confusing.

The solution that I see is to turn the internal code that is used to translate `lang` into `babel-lang` and `polyglossia-lang` into pipes. This would make the translation available for arbitrary fields. It would also allow one to put in the default pandoc latex template `$lang/babel$` instead of using `$babel-lang$`, which would eliminate a "magic variable" and make it explicit what variable is responsible for a given piece of information.

**Describe alternatives you've considered.**

I believe polyglossia can handle BCP47 specifications throughout, so the pipe may not be obligatory, though it would seem from the default `template.tex` that the internal translation already used also creates `polyglossia-lang.options` as a function of `lang`. If so then the pipe would still be useful.

For babel, the only other solution I could see would be to specify the abstract languages twice - once in the `otherlangs` field and once in the `abstract` field I created. In addition to being redundant, it does not seem that the `otherlangs` field is automatically translated into `babel-otherlangs` as is done for the `lang` field (at least it didn't work for me - this may happen when `otherlangs` is automatically generated from divs and spans in the document, but it didn't work when I specified `otherlangs` by hand), yet another reason to have a pipe.

**Comment by jgm** [comment]
Pipes are defined in a separate library, jgm/doctemplates.  These pipes seem too special-purpose for that general purpose package.  Also, we wouldn't be able to use the code from pandoc that converts between language formats.

You could perhaps use a filter to set a variable based on `lang`?
