### ISSUE TITLE
Can't specify the path of input file

### ISSUE THREAD

**Issue by wongyah** [jgm/pandoc#7470]
**Explain the problem.**

> I am asking a question here, because I can't access to the pandoc-discuss mailing list from China. Sorry for this!

I want to convert Markdown to HTML in PowerShell, but I always get an error when I tried to specify a path for the input file.

The directory structure looks like this:

- rootDir
  - subDir1
    - file.md
  - subDir2
    - convert.ps1

In the "convert.ps1", I thought the blow command will work, but it doesn't.

```
pandoc rootDir/subDir1/file.md -s -o rootDir/subDir1/output.html --template md.html
```

Actually, I use absolute paths in my PowerShell script. But it always output nothing. As long as I put the "file.md" and the "convert.ps1" in the same folder, and run the "convert.ps1" with their directory as the prompt, the output will be correct.

I am a novice, didn't find any solution by searching. How can I use this command in PowerShell to complete the conversion?

**Pandoc version?**
Pandoc 2.14.1

**Comment by jgm** [comment]
From what directory are you running convert.ps1?

**Comment by wongyah** [comment]
I added subDir2 (the folder of convert.ps1) to the environment variable "Path". 

Most often, I run it in the rootDir which represent the root folder of a workplace in VS code. I possibly run it in any folder, this is why I use absolute paths in the script.

**Comment by wongyah** [comment]
I added subDir2 (the folder of convert.ps1) to the environment variable "Path". 

Most often, I run it in the rootDir which represent the root folder of a workplace in VS code. I possibly run it in any folder, this is why I use absolute paths in the script.

**Comment by jgm** [comment]
I'm a bit confused, because you say you use absolute paths in the script, but the command you give has relative paths.  What is the actual script?

I know nothing about PowerShell, I'm afraid, so I don't know how relative paths in scripts are supposed to work.

**Comment by wongyah** [comment]
Well, the pandoc command in my previous description is just an example, not the real path I used in my PowerShell script. Things are a little complicated, but I will try to explain.

# Purpose

I use the PowerShell script to automatically format my blogs on WeChat Official Accounts Platform, a popular blog system in China.

This platform can use inline style (CSS) only. Both internal and external style sheets aren't allowed to to be used. Some of HTML elements aren't allowed to use too, such as \<h1-h6>, \<div>...

I write my blog in Markdown within VS Code. So I need two steps to convert my Markdown file to ready-to-release blog with a good look:

1. Convert Markdown to bare HTML (without any CSS style). I am using VS Code plugin "Markdown All in One" to manually do this conversion now, because seems "Markdown All in One" can't be used in command line.
2. Transform bare HTML to HTML with inline CSS styles. I am using Xalan (XSLT) command in PowerShell script to do this transformation now.

That is to say, now I want to find a tool to do the Step 1 in command line, and the command can be added to PowerShell script and run correctly from any folder.

# My PowerShell script

## PowerShell script:

```ps
# $file is the absolute file path (parameter) received from the command line when the PowerShell script to be executed. 
param ($file)
$folder = ($file | split-path)
$basename = (get-item $file).basename

# $xslFolder is where my XSLT files are.
$xslFolder = "E:/PublicAccount/XSLT_Transform/publicAccountTemplate"

# Make sure every self closing HTML tag has a backslash in it, which is requested by XML file (Xalan). Otherwise, an error always occur.
(get-content -path $file -encoding utf8 -raw) `
  -replace '<head>(\w|\W)*?</head>', '' `
  -replace '<((area|base|br|col|command|embed|hr|img|input|keygen|link|meta|param|source|track|wbr).*?[^\/]?)>', '<$1 />' |
out-file $xslFolder/markdown.xml

# Xalan command, convert bare HTML to styled HTML.
java org.apache.xalan.xslt.Process -in $xslFolder/markdown.xml -xsl $xslFolder/common.xsl -out $folder\$basename-formatted.html
```

## Command to run the PowerShell script

This is the commands I run in command line (actually I use powershell in VS Code):

```
PS E:\PublicAccount> docsimpo.ps1 -file e:\PublicAccount\tutorial\characterClass.html
```

## Key Points:

1. The absolute path in the command (following "-file") will become the value of the variable $file in the PowerShell script. It is always an absolute path which is created automatically when I drag the file from the Explorer of VS Code to the command line.
2. "E:\PublicAccount>" is the directory I run the PowerShell script most often, because It is the default prompt when I start a new terminal in this workspace (in VS Code).
3. The variable $file can only accept a .html file now. It will be wonderful If I can input a .md file, and don't need a .html file as an intermediate file.

# My expectation to pandoc

I thought I could use a command similar to the xalan one to complete the md-to-html conversion. But I didn't find a way to specify the input file path in the Pandoc command.

Thank you very much!

**Comment by jgm** [comment]
This script doesn't invoke pandoc at all, as far as I can see.

**Comment by wongyah** [comment]
@jgm Did you really read and understand the case?

Pandoc doesn't work as I expect till now. I can test it seperately before add it to my script, can't I?

**Comment by wongyah** [comment]
@jgm Did you really read and understand the case?

Pandoc doesn't work as I expect till now. I can test it seperately before add it to my script, can't I?

**Comment by wongyah** [comment]
Because pandoc doesn’t work as I expect  in this case till now. I should test it separately before add it to my script, right?

Sent from Mail for Windows 10

**Comment by wongyah** [comment]
Finally, I solved this problem with powershell.

```powershell

param ($file)

$folder = ($file | split-path)
$basename = (get-item $file).basename

$xslFolder = "E:/PublicAccount/XSLT_Transform/publicAccountTemplate"

$currentDir = Get-Location
Set-Location -Path $folder

pandoc -f markdown -t html -s -o output.html --template md.html --metadata title="$basename" $file
java org.apache.xalan.xslt.Process -in output.html -xsl $xslFolder/common-pandoc.xsl -out $folder\$basename-formatted.html

Invoke-item "$basename-formatted.html"

Set-Location -path $currentDir
"Transformation completed.`nFile path: $folder\$basename-formatted.html"
```

But it will be much more convenient if pandoc can specify the input path and output path in its command, just like what xalan command does.

**Comment by wongyah** [comment]
Finally, I solved this problem with powershell.

```powershell

param ($file)

$folder = ($file | split-path)
$basename = (get-item $file).basename

$xslFolder = "E:/PublicAccount/XSLT_Transform/publicAccountTemplate"

$currentDir = Get-Location
Set-Location -Path $folder

pandoc -f markdown -t html -s -o output.html --template md.html --metadata title="$basename" $file
java org.apache.xalan.xslt.Process -in output.html -xsl $xslFolder/common-pandoc.xsl -out $folder\$basename-formatted.html

Invoke-item "$basename-formatted.html"

Set-Location -path $currentDir
"Transformation completed.`nFile path: $folder\$basename-formatted.html"
```

But it will be much more convenient if pandoc can specify the input path and output path in its command, just like what xalan command does.

**Comment by jgm** [comment]
I never understood the issue you were having.  Pandoc certainly does allow you to specify paths for the input and output files.  If this is not working for you, you need to give a sample pandoc command that does not work, explaining the details of the environment and the result you got.  Just a single pandoc command -- not a complicated shell script.  That will isolate the problem, if there is one.

**Comment by wongyah** [comment]
@jgm I run a command with absolute path again. it did work. Sorry!

I checked the command history, possibly I didn't found the correct output file before. This makes me thought that pandoc maybe can't specify a path. 

This sentence "Pandoc certainly does allow you to specify paths for the input and output files." is really helpful, thank you!
