### ISSUE TITLE
error message report

### ISSUE THREAD

**Issue by tulipper** [jgm/pandoc#7472]
**Explain the problem.**
I'm using this command line to convert  to a word file. 
`pandoc pantext.tex --filter pandoc-crossref --bibliography=MyCollection.bib -o mydoc.docx`
The tex file can be compiled successfully by xelatex, but error occurs in pandoc: 
`Error at "pantext.tex" (line 617, column 14):
expecting \end{table}
\bottomrule`
I checked the tex file at line 617:
616: \bottomrule
617: \end{tabular}
618: \end{table}

what can I do to deal with the error?

**Pandoc version?**
pandoc 2.14.0.3 
pandoc-crossref v0.3.12.0 git commit fafa28db9912461b65f0c454bde84c304ac68e98 (HEAD) built with Pandoc v2.14.0.3, pandoc-types v1.22 and GHC 8.10.5
win 10

**Comment by mb21** [comment]
Can you post a minimal reproducible example of that input file?

**Comment by tulipper** [comment]
Thank you, it is solved. Probably because of the nested tables.
