### ISSUE TITLE
rst figure options are applied to image only

### ISSUE THREAD

**Issue by quytelda** [jgm/pandoc#7473]
**Explain the problem.**
When converting a reStructuredText `figure` directive to HTML, options like `figclass` and `align` are only applied to the image and not the entire figure in the output. Based on the [reference documentation](https://docutils.sourceforge.io/docs/ref/rst/directives.html#figure) for `figure`, I think these options are intended to apply to the entire figure.

For example, if I run the following command:
```
$ pandoc --from=rst --to=html5 <<EOF
.. figure:: example.img
   :figclass: foobar

   This is a caption.
EOF
```
I would expect the output to be:
```
<figure class="foobar">
<img src="example.img" alt="This is a caption." /><figcaption aria-hidden="true">This is a caption.</figcaption>
</figure>
```
Instead, I get the following, where the `class=foobar` attribute is part of the `img` tag.
```
<figure>
<img src="example.img" class="foobar" alt="This is a caption." /><figcaption aria-hidden="true">This is a caption.</figcaption>
</figure>
```

This issue causes the image and caption to get separated if the CSS stylesheet tries using something like `float` to align the figure.

**Pandoc version?**
I can reproduce this issue with the current development version (git) and pandoc 2.14.0.2 (pacman version: 2.14.0.2-2).
My OS is Arch Linux.

**Comment by argent0** [comment]
Tangentially I'm working on [adding](https://github.com/tarleb/pandoc/discussions/27) explicit figure representation in pandoc. It doesn't yet work on RST though.

**Comment by jgm** [comment]
Currently figures are just represented as images in a paragraph, so there isn't anywhere else to add the attributes. This will change when Figure gets added with  @argent0's work.

**Comment by quytelda** [comment]
Great, that's good to know.

Let me know if there's anything I can do to help with that. I'm not really familiar with this codebase, but I've got some time and I enjoy working with Haskell.

**Comment by tarleb** [comment]
This is now fixed for `figclasses`, but not for `align`.
