### ISSUE TITLE
LaTeX \input causes an error

### ISSUE THREAD

**Issue by fedeinthemix** [jgm/pandoc#7474]
I'm using pandoc 2.14.1. I have a LaTeX document that I would like to convert to HTML. The target document is large, hence I organize pictures in subfolders. I generate some graphics with `xfig` which permits to render text in images with LaTeX. To do that it generates 2 files: one with text in a LeTeX `picture` environment (from the `graphicx` package) and another with the rest. To use it you `\include` the first. Here's a stripped down example

```LaTeX
\documentclass[a4paper]{article}

\usepackage{color}
\usepackage{graphicx}
\usepackage{amsmath}
\graphicspath{{./images/}}

\newcommand{\vr}[1]{\ensuremath{#1}}

\begin{document}

\section{Introduction}
\label{sec:introduction}

In this document we present \ldots carrying an homogeneous current $I$
(see Fig.~\ref{fig:magnetic_dipole_geometry}).

\begin{figure}[ht]
  \centering{}
  \input{images/magnetic_dipole_geometry.pspdftex}
  %\includegraphics{images/magnetic_dipole_geometry_pspdftex.pdf}
  \caption{Circular current loop of radius $R$, carrying a current
    $I$.}
  \label{fig:magnetic_dipole_geometry}
\end{figure}

Charge conservation is implied in Maxwell's equations (see
Eq.~(\ref{eq:charge})).

\section{Maxwell Equations}
\label{sec:maxwell}

In Sec.~\ref{sec:introduction} we described the geometry of the
problem at hand. In this section we solve
\begin{equation}
  \label{eq:charge}
  \nabla \cdot D = \rho
\end{equation}

This is a reference to the above Eq.~\eqref{eq:charge}.

\end{document}
``` 
When I try to convert the file with `pandoc -f latex -t html --resource-path=images:. -o test2.html test2.tex ` I get the following error:

```bash
Error at "test2.tex" (line 18, column 1):
unexpected \begin
expecting \end{document}
\begin{figure}[ht]
^
```

If I try importing the graphics only part pandoc doesn't produce errors (commented `\includegraphics`).

The file that I import with `\input` is

```LaTeX
\begin{picture}(0,0)%
\includegraphics{magnetic_dipole_geometry_pspdftex}%
\end{picture}%
\setlength{\unitlength}{4144sp}%
%
\begingroup\makeatletter\ifx\SetFigFont\undefined%
\gdef\SetFigFont#1#2#3#4#5{%
  \reset@font\fontsize{#1}{#2pt}%
  \fontfamily{#3}\fontseries{#4}\fontshape{#5}%
  \selectfont}%
\fi\endgroup%
\begin{picture}(3540,1449)(1831,-3298)
\put(4321,-2671){\makebox(0,0)[lb]{\smash{{\SetFigFont{11}{13.2}{\familydefault}{\mddefault}{\updefault}{\color[rgb]{0,0,0}$\phi$}%
}}}}
\put(3421,-3166){\makebox(0,0)[lb]{\smash{{\SetFigFont{11}{13.2}{\familydefault}{\mddefault}{\updefault}{\color[rgb]{0,0,0}$I$}%
}}}}
\put(3691,-2446){\makebox(0,0)[lb]{\smash{{\SetFigFont{11}{13.2}{\familydefault}{\mddefault}{\updefault}{\color[rgb]{0,0,0}$\theta$}%
}}}}
\put(2926,-2671){\makebox(0,0)[lb]{\smash{{\SetFigFont{11}{13.2}{\familydefault}{\mddefault}{\updefault}{\color[rgb]{0,0,0}$R$}%
}}}}
\put(4681,-2041){\makebox(0,0)[lb]{\smash{{\SetFigFont{11}{13.2}{\familydefault}{\mddefault}{\updefault}{\color[rgb]{0,0,0}$\vr{r}$}%
}}}}
\end{picture}%
```

This is the text part of the picture and includes an `\inglucegraphics` command to import the rest. Note that the filename in the latter doesn't include the name of the subdirectory. In LaTeX this is solved by putting `\graphicspath{{./images/}}` in the preamble.

Is there a way to ignore `picture`environments and the `\begingroup` part so as to avoid errors and get the image part of the picture?

**Comment by jgm** [comment]
I think the issue is with `\gdef`, which pandoc doesn't understand (and I'd never even heard of til now).  IF you change it to `\def` pandoc might make it through.

We should support `\edef` and `\gdef` and `\xdef`:
https://tex.stackexchange.com/questions/353138/what-are-the-differences-between-def-edef-gdef-and-xdef

**Comment by jgm** [comment]
To ignore the picture environment, you can just redefine it earlier in your document:
```
\renewenvironment{picture}{}{}
```

**Comment by fedeinthemix** [comment]
You are right: If I replace `\gdef` by `\def` `pandoc` makes it through without errors.
