### ISSUE TITLE
[FR] Enable `slide_level` to be 0 for presentations to use only horizontal rules as slide separators

### ISSUE THREAD

**Issue by apreshill** [jgm/pandoc#7476]
Hello!

I've been working with various Pandoc presentation formats, and really appreciate the consistency in APIs across formats. The particular formats I'm most familiar with are HTML (via revealjs) and PowerPoint. 

One source of friction and confusion for users is how slides get carved up (documented here: https://pandoc.org/MANUAL.html#structuring-the-slide-show). I like the option to have Pandoc be smart about creating new slides based on the header-level hierarchy. However, this can be a challenge if you are collaborating on slides with others who are less familiar with Pandoc slide syntax, as it can be hard to explain.

## Problem: 

In the docs, it states that "A horizontal rule always starts a new slide." This is true! But it would be great to have a setting where "A horizontal rule only starts a new slide" so that a person reading the source can clearly see all the slide breaks without needing to render. 

As noted in the docs, a work-around is to just use level-1 headings for all each slide and set the `slide_level` option to 1. However, for users writing to PowerPoint, this means that we are unable to use 1 out of our 4 Pandoc-supported layout slides (the "Section Header" layout). For example, this text:

```
---

# if slide level = 2, this is a section header

But if slide level = 1, it is a plain slide

---
```

Renders as this with slide level set to 2:

<img width="1152" alt="Screen Shot 2021-08-05 at 2 30 35 PM" src="https://user-images.githubusercontent.com/12160301/128423923-254a70c4-cf85-4056-a9f2-f74d3638ea16.png">

But this with slide level set to 1:
<img width="1152" alt="Screen Shot 2021-08-05 at 2 30 02 PM" src="https://user-images.githubusercontent.com/12160301/128423943-ff62188c-5b67-4ea1-a4b7-077200f14099.png">

## Proposal

Allow users to indicate that they wish to use `---` as the slide separator by enabling`slide-level = 0` as an option (currently it must be > 0). In this case, the behavior would be to only separate slides separated by an explicit `---`. This makes the source easier to read because I can easily see individual slides as I edit, and it makes it easier for me to collaborate without needing to explain headers. 

Possibly related issues pointing to similar slide level usability concerns:

https://github.com/jgm/pandoc/issues/3460

https://github.com/rstudio/rmarkdown/issues/1490

https://github.com/jgm/pandoc/issues/2157

**Comment by jgm** [comment]
This seems reasonable and required minimal changes.
Please let me know if any issues appear in testing with various slide formats.

**Comment by zareami10** [comment]
> This seems reasonable and required minimal changes. Please let me know if any issues appear in testing with various slide formats.

When setting slide level to 0 I would expect something like `--- {background-color="black"}` working as we have no slide headers, but it does not. Any alternative solution?

**Comment by jgm** [comment]
You can't put attributes on a horizontal rule.
Maybe you can use a fenced div, though?
