### ISSUE TITLE
PowerPoint output: slides immediately following an hr (`---`) are interpreted as tables

### ISSUE THREAD

**Issue by apreshill** [jgm/pandoc#7477]
**Explain the problem.**
If you have a slide separator (a horizontal rule) immediately followed by any text (plain text or any level text header), the slide content is read as a table.

To reproduce the problem:

```
---
## Slide title right after separator

Some words

---

## Slide title with blank line after separator

Some words
```

Renders:

<img width="451" alt="Screen Shot 2021-08-06 at 12 35 21 PM" src="https://user-images.githubusercontent.com/12160301/128563566-a76b5e2c-4897-4075-a1fd-6c4952577294.png">

**Pandoc version?**
Pandoc version: 2.14.1
Mac OS Catalina 10.15.7

**Comment by jgm** [comment]
This is in fact a valid multiline table in pandoc's markdown:
```
---
## Slide title right after separator

Some words

---
```
Solution: put a blank line after your horizontal rule.
