### ISSUE TITLE
Use of "underline" class isn't documented

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#7484]
I discovered by accident that the `underline` class causes a span to be parsed as an `Underline`. However I don't see any mention of this in the manual, e.g., in <https://pandoc.org/MANUAL.html#inline-formatting>.

I'm using pandoc 2.14.1 on an M1 Mac running macOS Big Sur 11.4.

```
% pandoc --from=markdown --to=native <<END
> [underline]{.underline}
> END
[Para [Underline [Str "underline"]]]
```

**Comment by jgm** [comment]
I'd suggest we add a section documenting this, probably right next to the existing section "Small Caps."

**Comment by wlupton** [comment]
Do you like PRs for the manual? If so, happy to oblige.
