### ISSUE TITLE
Citeproc processes citations in unused metadata variables

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#7485]
Citeproc seems to process citations in metadata variables.

Naively, I'd expect it to process only `Pandoc.blocks` (not `Pandoc.meta`).

I'm using pandoc 2.14.1 on an M1 Mac running macOS Big Sur 11.4.

```
% pandoc --citeproc <<END
> ---
> myVar: '@RFC1234'
> ...
> END
[WARNING] Citeproc: citation RFC1234 not found
```

**Comment by jgm** [comment]
Well, suppose you have an `abstract` field in your metadata. Wouldn't you want citations to be processed there?

**Comment by wlupton** [comment]
OK, so I guess the point is that the template might reference such variables (populated from the metadata) directly, is that correct? So they have to be processed. I hadn't considered that.

I forget the exact situation that prompted creating this issue, but I think I must have had a boilerplate metadata variable that contained a citation but was never used in the document (I have a macro expansion filter). Not a problem. Thanks!
