### ISSUE TITLE
Pandoc on Microsoft Azure gives getAppUserDataDirectory error

### ISSUE THREAD

**Issue by cricrazy** [jgm/pandoc#7486]
Hello All, I am trying to run Pandoc on MS Azure environment to create HTML report from markdown file. The Pandoc command is real simple one. 

> pandoc test.md -o test.html

But I get the following error. 

> pandoc: getAppUserDataDirectory:sHGetFolderPath: illegal operation (unsupported operation)

It seems to me that MS Azure has Windows 10 sort of environment. I even tried to set up `XDG_DATA_HOME` or `XDG_DATA_DIRS`, but it still gives the same error. 

Can you someone please help?

**Comment by jgm** [comment]
I don't do Windows much, so I'm not sure.  But note that you can explicitly specify the user data directory using `--data-dir=DIR`; this might help.

**Comment by cricrazy** [comment]
@jgm what does `--data-dir` do?

I am using this batch file to convert the file. 

> @ECHO ON
> pandoc test.md -o test.html
> EXIT

**Comment by jgm** [comment]
Just as I said, it allows you to explicitly specify the user data directory (which normally defaults to XDG_DATA_HOME).
I don't know if this would help but you can try it (even just adding `--data-dir=.`).

**Comment by cricrazy** [comment]
@jgm thank you. I added this and it worked. Thank you so much. 

> pandoc final.md -o final.html --data-dir=.
