### ISSUE TITLE
Preserving attribute order in lua writers (and filters)

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#7489]
Issue #7487 mentioned that [lua attributes](https://pandoc.org/lua-filters.html#type-attributes) are unordered, so custom writers can't preserve the original attribute order.

I think it's desirable for attributes to be output in a predictable (and repeatable) order. For example, you might want to compare the results of successive runs. Ideally the original order would be preserved.

There appear to be two possibilities:
* As noted by @tarleb, wait for the #7191 new lua marshalling methods and see whether they will permit the attribute order to be preserved
* Sort them, probably ignoring case and perhaps in three groups: (a) "id" and any other "first" attributes, (b) element-specific "known" attributes (e.g., image height and width), (c) the rest (which would include all the "data-xxx" attributes)

As a variant of the first approach, would it be possible also to provide `ipairs()` access in the original order? I don't think that would break `pairs()` access? Doesn't [`Attr`](https://pandoc.org/lua-filters.html#type-attr) already do something similar?

**Comment by wlupton** [comment]
As noted in #7487, I realised that the writer needs to handle attribute `data-` prefixes, so it has to know the standard attributes for each element. This could be hard-coded in the lua or could a utility function supply this info?

**Comment by jgm** [comment]
On the ipairs question I need to defer to @tarleb.

**Comment by tarleb** [comment]
We are now using a special structure which still behaves like a normal map, but actually guarantees that `pairs` will return the elements in the correct order. The individual key-value pairs can be accessed through numerical indices, but this should rarely be necessary.
