### ISSUE TITLE
support -native_numbering for docx

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#7499]
Now that docx has native figure numbering in pandoc 2.14.1 (https://github.com/jgm/pandoc/commit/a3d745e48560a55d9a9ea9fa43ffdd5a8b84987f) I think it would be appropriate to implement support for the `native_numbering` extension for docx. 

The motivation here is identical to the scenario that led to this being implemented for odt (https://github.com/jgm/pandoc/pull/5765): when there is another cross-reference manager in play that is doing numbering this leads to output like this:

![Screen Shot 2021-08-15 at 3 23 46 PM](https://user-images.githubusercontent.com/104391/129490007-9812773c-882b-45af-aadc-bdbbfea7a031.png)

So we need a way to disable the `native_numbering` (as exists for ODT) to prevent this from happening. Not to re-hash old ground but I'm also unsure whether this should be enabled by default given that this will break the output (as above) for existing third-party cross reference filters.

We might think it enough to stipulate that pandoc is now handling this so external crossref handlers shouldn't (as is done with LaTeX now), but filters like pandoc-crossref, bookdown, quarto, etc. have accumulated lots of advanced functionality including subfigure refs and chapter based refs (e.g. "Figure 5.3b") as well as options to control the figure caption text, etc. These options all exist for LaTeX so it's fine to let them be handled within the format. However, they don't exist (or expressions of them don't exist in pandoc markdown) for other formats so external crossref handlers are required. If pandoc "takes over" figure numbering and doesn't implement these other features it essentially breaks the external crossref handlers.

If the ship has sailed on enabling this by default then I'd at a minimum request allowing e.g. `to: docx-native_numbering` to turn it off. Without this pandoc-crossref, bookdown, quarto, etc. actually cannot produce correct output for the more advanced scenarios (i.e. for simple non chapter based figures w/o subfigures we could just let pandoc do the numbering, but as soon as the user wants to use chapters, subfigures, etc. the output will be incorrect)

**Comment by jgm** [comment]
That makes sense.  I think it should be enabled by default as it is for ODT, for consistency if nothing else.

**Comment by jgm** [comment]
Oh wait, it's NOT enabled by default for ODT.
Well, since the numbering feature was introduced very recently, I think we could disable it by default, for consistency.

**Comment by jjallaire** [comment]
Thanks, I think it's great that Pandoc is doing more for figure/table numbering but there will always be users that want something more closely approximating LaTeX references in other formats -- allowing the external cross ref managers to provide this while progressively enhancing the core capabilities is a good way to split the difference.

**Comment by dev-guy** [comment]
Here are two example table of contents field codes to use that are compatible with openxml produced by pandoc-crossref. These can be selected in the Word UI by specifying either "TableCaption" or "ImageCaption" depending the type of list that you want. The default settings in the Word UI don't work because those look for fields with SEQ in their contents.

Tables:
```
TOC \h \z \a \t "TableCaption"
```

Figures/Images:
```
TOC \h \z \a \t "ImageCaption"
```
