### ISSUE TITLE
download remote images in converting markdown to latex/pdf

### ISSUE THREAD

**Issue by cboettig** [jgm/pandoc#750]
Markdown (or possibly html) files with remote images cannot be directly converted to pdfs.  As the `--self-contained` option already supports downloading of image files, perhaps a similar trick could be used to download and store local images for embedding in the latex or pdf document?

**Comment by puterleat** [comment]
This problem seems to have reappeared, at least in version 1.16.0.2.  This example again illustrates: 

 pandoc -s http://www.haskell.org/platform/ -o out.rtf

**Comment by jgm** [comment]
The problem is that we can only embed raster images in
RTF, and these images are SVG.

+++ puterleat [Sep 20 16 00:50 ]:

**Comment by puterleat** [comment]
I don't think it's just an SVG issue though, e.g.:

pandoc -s http://oldschool.runescape.com -o out.rtf

**Comment by jgm** [comment]
That works fine.  Are you looking at it in OSX's TextEdit by
chance?  That does not show images.  Try opening it in Word
or LibreOffice or something.

If you look at out.rtf in an editor, you'll see the data for
the images.

+++ puterleat [Sep 20 16 01:33 ]:

**Comment by Lambik** [comment]
Hi,

I don't know if this is related, or if I'm hijacking this thread, but I just installed pandoc from ubuntu's apt-get, and tried this command:

    pandoc -s --toc -o test.epub -r html 'http://www.squidi.net/three/entry.php?id=1'

The output does not contain the images. Maybe because they are relative (like `<img src='set01/img/entry001-illusion.gif' alt='[illusion.gif]'>`)?

The errors I see are:

```
pandoc: Could not find media `poster/poster001.png', skipping...
pandoc: Could not find media `set01/img/entry001-illusion.gif', skipping...
(and so on for the other images)
```

I've tried adding the `--self-contained` option, but that doesn't seem to work (probably because it's epub output).

Is this related? (and is there a solution?)

**Comment by jgm** [comment]
Not directly related.  I'd suggest opening a new issue.
Pandoc can handle relative links, but I think it's doing
it wrong in this case.

+++ Tom Muylle [Sep 20 16 06:21 ]:

**Comment by Lambik** [comment]
Thanks, sorry for the hijack

**Comment by rushi-deshmukh** [comment]
I am facing the same issue while converting the html file to the rtf using the pandoc-1.18.
I am getting red coloured text instead of the image.
