### ISSUE TITLE
markdown to docx -- some figures do not appear when reference docx contains an image in header

### ISSUE THREAD

**Issue by hallieswan** [jgm/pandoc#7503]
## Problem

When converting markdown to docx, some figures do not appear in the docx when the reference docx contains an image in the header. If an image is not included in the reference docx header, all figures appear in the final docx. 

How I can include an image in the header of the reference docx and include all plots in the final Word docx? Also posted on [stackoverflow](https://stackoverflow.com/questions/68778211/rmarkdown-to-docx-some-figures-do-not-appear-when-reference-docx-contains-an).

### Exact command line used

  ```
  pandoc \
  minimal_example.md \
  --to docx \
  --from markdown \
  --output minimal_example.docx \
  --reference-doc custom-reference.docx
  ```

### Exact input used

  1. minimal_example.md
  ```
  ![](minimal_example_files/figure-docx/plots-1.png)
  ![](minimal_example_files/figure-docx/plots-2.png)
  ![](minimal_example_files/figure-docx/plots-3.png)
  ![](minimal_example_files/figure-docx/plots-4.png)
  ![](minimal_example_files/figure-docx/plots-5.png)
  ```
  2. custom-reference.docx
     1. get a copy of the default reference.docx, as described in the User's Guide:
        ```
        pandoc -o custom-reference.docx --print-default-data-file reference.docx
        ```
     2. add an image in the header, such as the [GitHub logo](https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png)
  3. plots  
   ![plots-1](https://user-images.githubusercontent.com/26949006/129642591-b7be2ad6-9c04-482c-988a-daa874c774c7.png) ![plots-2](https://user-images.githubusercontent.com/26949006/129642614-76de0aa4-a254-4b77-9f31-3e0e593662dc.png) ![plots-3](https://user-images.githubusercontent.com/26949006/129642616-18d1c202-8ff1-4507-8d17-a093e7b8e8de.png) ![plots-4](https://user-images.githubusercontent.com/26949006/129642617-23f0d67f-0519-486d-9e56-51b943fdcd13.png) ![plots-5](https://user-images.githubusercontent.com/26949006/129642618-f09a1c33-1bad-4e9d-a026-e2c69924220a.png)

### Output received

The final docx includes 4 figures, instead of 5 figures.

   <img width="532" alt="image" src="https://user-images.githubusercontent.com/26949006/129639579-7cac03a7-ddd6-4d50-be03-9dbd8eb0b740.png">

### Output expected

The final docx should include all 5 figures and the image in the header.
   
   <img width="533" alt="image" src="https://user-images.githubusercontent.com/26949006/129639985-de3695b9-5bab-4845-aafd-3ef5b57436b9.png">

## Pandoc version?

- Pandoc version 2.14.1
- macOS Big Sur 11.4
- Microsoft Word for Mac 16.52

**Comment by jgm** [comment]
Can you upload the reference.docx you're using?

**Comment by hallieswan** [comment]
Happy to -- I've attached it here. Let me know if you need anything else!
[custom-reference.docx](https://github.com/jgm/pandoc/files/7001405/custom-reference.docx)

**Comment by jgm** [comment]
Odd, I'm not able to reproduce this in my own testing.
Perhaps you could upload or link to a zip file with *everything* needed to reproduce the issue?

**Comment by hallieswan** [comment]
Strange! Okay, I've attached a zip file. Let me know if there are any other files you'd like me to include.
[minimal_example.zip](https://github.com/jgm/pandoc/files/7001687/minimal_example.zip)

**Comment by jgm** [comment]
Tested with your case and got five images in the figure...
Are you sure you're running the latest pandoc and not an older version?

**Comment by hallieswan** [comment]
Just double checked my version -- I believe it's the latest. Sounds like it might be an issue on my end, I'll keep looking into it. Thanks for testing it out on your end!
![image](https://user-images.githubusercontent.com/26949006/129789436-a441671f-3ddb-435b-af1a-0566d94d0ca6.png)

**Comment by hallieswan** [comment]
My coworker was able to reproduce the issue (macOS 11.5.1, Microsoft Word for Mac 16.52). Do you mind sharing what version of Word you're using? I'm wondering if that could be part of our problem

**Comment by jgm** [comment]
Word for Mac 16.3.3
macOS 11.4

**Comment by jgm** [comment]
<img width="775" alt="Screen Shot 2021-08-18 at 10 14 03 AM" src="https://user-images.githubusercontent.com/3044/129942602-72fd0212-0064-436d-a569-27d72439f96f.png">

**Comment by jgm** [comment]
Upgraded to 16.33. Still 5 images.

**Comment by hallieswan** [comment]
Looks like it's a probably an issue with our Word configuration. Thank you for all of your help and time!
