### ISSUE TITLE
Command erased when using \let with a \newcommand in latex

### ISSUE THREAD

**Issue by diseraluca** [jgm/pandoc#7504]
I'm trying to convert some latex code that has a structure similar to the following example:

```latex
\newcommand{\newname}[1]{\textbf{#1}}
\let\command=\newname

\command{some text}
```

Trying to convert this with `pandoc -t native -f latex file.tex` results in an empty AST.

If the code is changed to alias the command directly then it is correctly read. 
For example:

```latex
\let\command=\textbf

\command{some text}
```

I've tried with a few different combinations of commands and it seems consistent.

I would expect the two version to be completely equivalent.

Tested on:
```
pandoc 2.14.0.2
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4.0.1, ipynb 0.1.0.1
```

On an Archlinux system.

**Comment by jgm** [comment]
With current master, we get
```
% pandoc -f latex -t native
\newcommand{\newname}[1]{\textbf{#1}}
\let\command=\newname

\command{some text}
^D
[Para [Strong [Str "some",Space,Str "text"]]]
```
So I think this was fixed in my recent changes to the LaTeX parser.
