### ISSUE TITLE
Pandoc fails to extract image from docx

### ISSUE THREAD

**Issue by SandyChapman** [jgm/pandoc#7511]
Pandoc is failing to extract images from my docx file. This may be related to #5640, I'm not sure. The key difference is that I've built a very simple docx file using Office 365, not a 3rd party tool.

Input: https://docs.google.com/document/d/1bb3Uu9eDsAz38HzTrEgJKW1OU9gJe6xx/edit?usp=sharing&ouid=104287861616242981339&rtpof=true&sd=true

I execute pandoc using

    pandoc --extract-media=. pandoc_extract_failure.docx -o output.md

or

    pandoc --extract-media=. pandoc_extract_failure.docx -o output.html

In either case, it successfully converts the text, but the images are not extracted and there are no img tags in the output.

**Pandoc version?**

        ➤ pandoc -v
        pandoc 2.14.0.3
        Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
        citeproc 0.4.0.1, ipynb 0.1.0.1
        User data directory: /Users/schapman/.local/share/pandoc
        Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
        This is free software; see the source for copying conditions. There is no
        warranty, not even for merchantability or fitness for a particular purpose.

**Comment by jgm** [comment]
I can confirm with latest pandoc.  The docx container contains the image as media/image.png, and document.xml refers to it thus:
``` xml
<w:drawing>
<wp:inline wp14:editId="21B59604" wp14:anchorId="30969BE8" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing">
<wp:extent cx="2695575" cy="1438275" />
<wp:effectExtent l="0" t="0" r="0" b="0" />
<wp:docPr id="941710934" name="" title="" />
<wp:cNvGraphicFramePr>
<a:graphicFrameLocks noChangeAspect="1" />
</wp:cNvGraphicFramePr>
<a:graphic>
<a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
<pic:pic>
<pic:nvPicPr>
<pic:cNvPr id="0" name="" />
<pic:cNvPicPr />
</pic:nvPicPr>
<pic:blipFill>
<a:blip r:embed="R7206bc1ec185490b">
<a:extLst>
<a:ext uri="{28A0092B-C50C-407E-A947-70E740481C1C}" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
<a14:useLocalDpi val="0" />
</a:ext>
</a:extLst>
</a:blip>
<a:stretch>
<a:fillRect />
</a:stretch>
</pic:blipFill>
<pic:spPr>
<a:xfrm>
<a:off x="0" y="0" />
<a:ext cx="2695575" cy="1438275" />
</a:xfrm><a:prstGeom prst="rect">
<a:avLst />
</a:prstGeom>
</pic:spPr>
</pic:pic>
</a:graphicData>
</a:graphic>
</wp:inline>
</w:drawing>
```
Also, `_rels/document.xml.rels` has
``` xml
<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="/media/image.png" Id="R7206bc1ec185490b" /></Relationships>
```

@jkr this seems to be a way of including image that the docx reader doesn't currently handle.

**Comment by jgm** [comment]
Ah, I think this bug is occuring when in the rels file the Target is specified with a leading `/`.

**Comment by jgm** [comment]
An even more important difference: in this file, the media is in `media/`, where normally it's in `word/media/` (and that's where the docx reader assumes it will be).

**Comment by SandyChapman** [comment]
@jgm Thanks for the quick turnaround! It is much appreciated.

**Comment by aeb-dev** [comment]
probably this bug still happening
[test.docx](https://github.com/jgm/pandoc/files/7980376/test.docx)
g

I checked file content and it is the same problem I believe

**Comment by tarleb** [comment]
@aeb-dev please try with the latest pandoc version. Best to open a new issue if the problem persists.
