### ISSUE TITLE
include directive with :literal: otpion do nothing

### ISSUE THREAD

**Issue by Guitouu31** [jgm/pandoc#7513]
Using pandoc 1.14.1.

.. include:: my_file.txt
   :literal:

The file content is not included. It works if :literal: option is removed (but content is interpreted/not raw).

**Comment by jgm** [comment]
You don't say what format this concerns.  RST I assume?

**Comment by jgm** [comment]
Note: `:literal:` as implemented has different semantics from `:code:`.
The latter inserts the file as a code block.
The former inserts it as *raw RST* (which won't appear in formats other than RST).
I can see now that this was based on a misunderstanding of what "literal block" means.

**Comment by Guitouu31** [comment]
Yes it concerns RST format.
Sorry for that misunderstanding, I shall use :code: instead of :literal: ...

**Comment by jgm** [comment]
No, it's not a misunderstanding on your part; pandoc implemented this badly, but it should be fixed now in MASTER.
