### ISSUE TITLE
Some pandoc lua modules are pre-loaded; others are not

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#7524]
With pandoc 2.14.1 it seems that, of the lua modules documented at <https://pandoc.org/lua-filters.html>, most but not all are preloaded. In particular, the `pandoc.path` module appears not to be preloaded (and must be explicitly required). This behavior should be documented (or fixed if it's unintentional).

```
pandoc	        table: 0x7f9453408840
pandoc.utils	table: 0x7f9453408fa0
pandoc.mediabag	table: 0x7f9453513380
pandoc.List	table: 0x7f9453512c10
pandoc.path	nil
pandoc.system	table: 0x7f9453513810
pandoc.types	table: 0x7f94534089c0
```

**Comment by jgm** [comment]
I believe it's intentional, but maybe @tarleb can comment further.

**Comment by wlupton** [comment]
I realised that we never continued this conversation. @tarleb?

**Comment by tarleb** [comment]
I can't remember if this was intentional, but I can't think of any reason against preloading `path`. I'll make the change.

**Comment by s6mike** [comment]
I don't have pandoc.path pre-loaded either, I want to require it for use in my lua filter, and I can't get it right.

I've tried:
`local path = require 'pandoc.path'`
`local path = require 'path'`

and both throw error: `module 'pandoc.path' not found:`.

Any suggestions? I'm new to pandoc filters so I'm probably missing something obvious, but googling has not helped me.

Using pandoc 2.9.2.1, lua 5.3

**Comment by tarleb** [comment]
The module `pandoc.path` was added in version 2.12; the only option is to install a newer pandoc version.

**Comment by s6mike** [comment]
Aha! Thanks.

Sadly debian bullseye (which is the latest stable version) only supports pandoc up to 2.9.2.1. I think there are ways around this, but they sound complicated. So I'll look for an alternative to using the path module.

**Comment by tarleb** [comment]
We provide statically compiled binaries (so they don't depend on any system libraries) for all releases. They are even packed up as Debian `.deb` packages. Try this in your terminal:

```
wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
sudo dpkg -i pandoc-2.18-1-amd64.deb
```
