### ISSUE TITLE
Pandoc doesn't respect --toc-depth for --number-sections

### ISSUE THREAD

**Issue by todd-a-jacobs** [jgm/pandoc#753]
When using pandoc 1.10.1, pandoc doesn't visually differentiate between header levels three and four (or presumably deeper). To work around that, I attempted to number sections to show the heirarchy of lower-level headers, but pandoc only uses _x.y.z_ to number headers regardless of the value of _toc-depth_.

The expectation is that `--toc-depth=5` would result in:

```
# Foo
## Bar
### Baz
#### Quux
```

rendering quux as `1.1.1.1 Quux` instead of leaving it entirely bare.

**Comment by phelps-sg** [comment]
This also happens with html output.  I have opened a new issue #6459 documenting this.
