### ISSUE TITLE
vadjust pre does not get parsed by LaTeX reader

### ISSUE THREAD

**Issue by luerhard** [jgm/pandoc#7531]
**Explain the problem.**
I am running a pipeline to produce documents with pandoc as:
1. convert markdown to tex with pandoc
2. convert tex to docx with pandoc (and tex to pdf with pdflatex)

I use `citeproc` and `link-citations: true`.

When i create the pdf with pdflatex, everything looks fine, but in `\vadjust pre` in the link citations do not seem to work with the docx writer.

from this base latex:

```latex
\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-baayen2008}{}}%
Baayen, R. H. (2008). \emph{Analyzing linguistic data. {A} practical
introduction to statistics using {R}} (1. publ.). {Cambridge University
Press}.

\leavevmode\vadjust pre{\hypertarget{ref-jones2016}{}}%
Jones, S. E. (2016). \emph{Roberto {Busa}, {S}. {J}., And the
{Emergence} of {Humanities Computing}. {The Priest} and the {Punched
Cards}}. {Routledge}.

\end{CSLReferences}
``` 

the resulting references in docx are:
![image](https://user-images.githubusercontent.com/24412608/131326213-541a7862-7f70-4fe5-9f24-9a7cd76f2387.png)

This behavior is the same with the odt writer.

**Pandoc version?**
I am using pandoc 2.14.2 on Ubuntu.

**Comment by jgm** [comment]
1. We need to teach the LaTeX reader about the `CSLReferences` environment (which should gobble the two parameters)
2.  and about the `\vadjust` command -- basically we just need to gobble a `pre` after it if there is one.

**Comment by jgm** [comment]
@luerhard why are you doing this way?  You could just go directly from markdown to docx using pandoc.
This would be more reliable.

**Comment by luerhard** [comment]
Mainly because i want to be able to write latex commands in my markdown document. Also, that way I only have one pipeline to worry about and can manually adjust the latex file if necessary.

I have to convert to latex before pdf anyway to get stuff like the letter-numbered appendices anyway, so I figured it is easier and better to maintain one single intermediary file with two outputs instead of two completely separate conversions.
