### ISSUE TITLE
Header/footer of docx specifically not showing

### ISSUE THREAD

**Issue by bickibird** [jgm/pandoc#7533]
Hi,

I've been running an R script to render an rmarkdown document (using option parsing in the command line in a conda environment).

In my r script I have the following render function which refers to a custom-reference.docx that I created using pandoc (I referred to this [guide](https://pandoc.org/MANUAL.html#options-affecting-specific-writers)).

```
library(rmarkdown)
library(optparse)
library(officedown)

render("rmarkdown_test.Rmd",
    rdocx_document(reference_docx = "custom-reference.docx")
```

I also refer to the custom-reference.docx in the yaml header of my rmarkdown file:

```
output:
  officedown::rdocx_document:
    reference_docx: "custom-reference.docx"

```

In my custom-reference.docx, I have added images to the header and page numbers to the footer, as well as modifying the styles. However, when I render the rmarkdown file and produce a word docx, the headers and footers are blank, whilst all the styles (headings, fonts etc) within the body of the word docx match what I've customised in the custom-reference.docx.

In my conda environment I have:

pandoc 2.14.2
r-knitr 1.33
r-officedown 0.2.2
r-officer 0.3.18
r-rmarkdown 2.10

(with r and conda-forge as channels)

I'm using 64-bit OS Windows 10.

After some reading I'm wondering if this is a pandoc issue (see similar issue [here](https://github.com/rstudio/rmarkdown/issues/226)).

Does anyone know why the header/footer would be specifically blank in my word docx after rendering the rmarkdown file which seems to successfully read the custom-reference.docx?

**Comment by jgm** [comment]
If you can put together a zip file with everything needed to reproduce this using just pandoc (not rmarkdown), then we can have a look. Otherwise it's hard to tell what might be going on.  I know that headers and footers (including those with images) work.

**Comment by mb21** [comment]
Closing for lack of information.
