### ISSUE TITLE
Error with \vadjust when loading luatexja package

### ISSUE THREAD

**Issue by nrth901** [jgm/pandoc#7534]
Using CJK fonts with LuaLaTeX, following error occurred when producing PDF via LaTeX since pandoc version 2.12, applied this commit: https://github.com/jgm/pandoc/commit/53cf8295a4825297f78e20b6ce73d2da8fd7ef84

```
Error producing PDF.
! Missing } inserted.
<inserted text>
}
l.842 \end{CSLReferences}
```
If I removed `\vadjust pre` from the reference list, PDF was created successfully.

This error seems to be caused by the luatexja package redefining `\vadjust`, documented here: [The LuaTeX-ja package (jaist.ac.jp)](http://ftp.jaist.ac.jp/pub/CTAN/macros/luatex/generic/luatexja/doc/luatexja-en.pdf)
To avoid this error, I changed CSLReferences environment in the LaTeX templates as follows and it worked.

https://github.com/jgm/pandoc/blob/0617d3a88bb1f84622b8a94bd3366c7c8c9e8f8a/data/templates/default.latex#L355-L366
to
```
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% prevent redefinition by luatexja
  \let\origvadjust\vadjust
  % don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
```
Note that you have to define \origvadjust in advance before luatexja package is loaded: `\let\origvadjust\vadjust`

I hope you find this information helpful and applicable.

**Comment by jgm** [comment]
I don't know. We could work around this in the way you describe, at the cost of making the template more complicated.  On the other hand, it seems reckless for the luatexja package to redefine a tex primitive in ways that might break other packages...and certainly one might expect that a package that does this won't be compatible with other things.

**Comment by jgm** [comment]
I'm tempted to think we should keep the default template as simple as possible, users who use this luatexja can always use a custom template.

**Comment by nrth901** [comment]
Thank you for your comment.
I agree that the template should be simpler, so I will withdraw the proposal.
I just hope it helps those who had the same problem.
