### ISSUE TITLE
Converting from html to mediawiki doesn't work with many tables

### ISSUE THREAD

**Issue by bpsib** [jgm/pandoc#7537]
**Explain the problem.**
I can't get it to work at all at converting certain html tables to mediawiki. I have tried everything to try and get it to work on the tables at [List of line-up changes on Sky (UK and Ireland) in 2021 HTML.txt](https://github.com/jgm/pandoc/files/7095041/List.of.line-up.changes.on.Sky.UK.and.Ireland.in.2021.HTML.txt) but all I get is lists rather than tables.

Command I have tried: `pandoc "List of line-up changes on Sky (UK and Ireland) in 2021 HTML.htm" -f html -t mediawiki -o "List of line-up changes on Sky (UK and Ireland) in 2021 MediaWiki.txt"`

**Pandoc version?**
pandoc 1.19.2.4 on Ubuntu 18.04

**Comment by mb21** [comment]
Can you try with the latest pandoc version? Please see https://pandoc.org/installing.html

**Comment by bpsib** [comment]
I have just tried the latest version and it sort of works. But all the formatting is stripped out.

**Comment by mb21** [comment]
great!

well, from https://pandoc.org/MANUAL.html

> Because pandoc’s intermediate representation of a document is less expressive than many of the formats it converts between, one should not expect perfect conversions between every format and every other. Pandoc attempts to preserve the structural elements of a document, but not formatting details such as margin size.

**Comment by bpsib** [comment]
So it's no good at all for me.
