### ISSUE TITLE
Output language not set correctly

### ISSUE THREAD

**Issue by pck1980** [jgm/pandoc#7539]
pandoc version 2.14.2
macOS 11.5.2 (M1)

I just realized that in a PDF a built with pandoc, images are labeled "Figure X", instead of the desired German "Abbildung X".
I checked some PDFs built a few months ago  and found that images where correctly labeled with "Abbildung X", but it also changes to "Figure X" as soon as I rebuild seem.
A (simlified) version of my build command is
`pandoc -s -t beamer --pdf-engine=xelatex -o slides.pdf -V lang=de slides.md`

I can't remember to have changed the build command, but of course, lots of other things changed in the past months, including an update from MacTeX 2020 to MacTeX 2021.

If I make pandoc produce LaTeX output instead of a pdf, the file I attached is created (extension changed to .txt).
[slides.txt](https://github.com/jgm/pandoc/files/7097511/slides.txt)

**Comment by jgm** [comment]
Please give us a small markdown input that can be used to reproduce the issue with the command line you give.

And could you try with `--metadata lang=de` or `-Mlang=de` instead of `-V`?  `-V` just sets a template variable, where `-M` sets a metadata field that is part of the AST. This may make a difference.

**Comment by pck1980** [comment]
I attached a small example to this posting.
The alternative options unfortunately don't solve the problem, the figure is still labeled "Figure".
[Example.zip](https://github.com/jgm/pandoc/files/7108342/Example.zip)

I tried the following commands with the example:

`pandoc -s -t beamer --pdf-engine=xelatex -o slides.pdf -V lang=de slides.md`        
`pandoc -s -t beamer --pdf-engine=xelatex -o slides.pdf -Mlang=de slides.md`
`pandoc -s -t beamer --pdf-engine=xelatex -o slides.pdf --metadata lang=de slides.md`

**Comment by jgm** [comment]
Strange, this is evidently sensitive to the pdf-engine.  With `--pdf-engine=xelatex -Mlang=de`, I get `Figure`, but with `--pdf-engine=pdflatex` or `--pdf-engine=lualatex`, I get `Abbildung`.

**Comment by jgm** [comment]
Note the following (produced by the tex writer with default template):
```
\ifXeTeX
  % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[]{german}
\else
  \usepackage[main=ngerman]{babel}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\fi
```
xetex uses polyglossia; the others use babel.  So the figure name isn't adjusting properly when polyglossia is used.
Do you see anything wrong here?

**Comment by jgm** [comment]
Putting `\selectlanguage{german}` right after `\setmainlanguage[]{german}` seems to work.
It's unclear to me, though, why this should be necessary.

**Comment by pck1980** [comment]
Thank you for further investigating this issue. I'm afraid I don't know enough about language settings in LaTeX to know if anything might be wrong with the template. Back in times when I wrote LaTeX by myself, I always used babel, but never XeTeX, I think.

I tried to build with older versions of the default template, including the one from the end of October 2020, but the problem persists.
So I guess it has something to do with the transition from MacTeX 2020 to MacTeX 2021 earlier this year.
Switching to LuaTeX is a applicable workaround, even though XeTeX seems to be faster.

**Comment by jgm** [comment]
If we can get a minimal example using just xelatex and a tex file, we could post on the tex stack exchange to see if anyone can explain what is happening. It could be a bug in polyglossia, or more likely some strange interaction with beamer.

**Comment by jgm** [comment]
Okay, I whittled it down to something minimal, and now it seems to work (Abbildung).
```
\documentclass[
  ngerman
]{beamer}
\usepackage{amsmath,amssymb}
\usepackage{unicode-math}
\defaultfontfeatures{Scale=MatchLowercase}
\defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\usetheme[]{metropolis}
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
\usepackage{polyglossia}
\setmainlanguage[]{german}

\title{Testfolien}
\author{Author}
\date{03.08.2021}

\begin{document}
\frame{\titlepage}

\hypertarget{der-titel}{%
\section{Der Titel}\label{der-titel}}

\begin{frame}{Eine Folie}
\begin{figure}
\centering
IMAGE
\caption{Ein buntes Bild}
\end{figure}
\end{frame}

\end{document}
```
So, apparently something else we have in the template is interacting with this.

**Comment by jgm** [comment]
OK, this is *really* weird. If you add `ignorenonframetext` to `ngerman` in the documentclass options in the above minimal tex file, then you get `Figure` instead of `Abbildung`.

**Comment by jgm** [comment]
Just to sum up:  this is specific to xelatex, and only happens with texlive 2021, not texlive 2020.

**Comment by gnpan** [comment]
A temporary solution is to use the caption package, i.e. add something like this to the yaml header:

```
header-includes:
  - \usepackage[font=small,labelfont=bf,figurename=Abbildung]{caption}
```

**Comment by jgm** [comment]
Reported this issue on beamer's bug tracker.  It does seem like an upstream issue, not something pandoc is doing wrong.

**Comment by jgm** [comment]
Another workaround may be adding `\selectlanguage{german}` to your input file.

**Comment by samcarter** [comment]
even with xelatex, I would no longer use polyglossia. Babel is much better maintained.

**Comment by jgm** [comment]
@samcarter Interesting. I honestly can't remember why the default template has this conditional (using polyglossia for xetex and babel otherwise). It goes back many years. Was there previously a reason to do it this way?  Or does it have something to do with support for non-European languages?

**Comment by samcarter** [comment]
@jgm A couple of years ago, babel was more or less on hiatus and did not work with new engines like xelatex. Back then the advice was to use polyglossia for such cases, but now the situation is pretty much revered.

**Comment by samcarter** [comment]
@jgm a related discussion from a couple of days ago: https://chat.stackexchange.com/transcript/message/59070629#59070629

**Comment by jgm** [comment]
Looks like beamer is being fixed upstream. If you find that your tex installation is affected by this, the workaround is to put the following declaration in your LaTeX preamble (you can include it in `header-includes` in the document's metadata or use `--include-in-header`):
```
\DeclareHookRule{begindocument/end}{beamer}{after}{polyglossia}
```

**Comment by jgm** [comment]
I've opened up a PR #7562 to change to using babel rather than polyglossia with xelatex.
This needs more testing and comment.
But this issue can be closed, I think.
