### ISSUE TITLE
4th level headers do not render as a block in PDF output

### ISSUE THREAD

**Issue by todd-a-jacobs** [jgm/pandoc#754]
Given input like the following:

```
#### <em>Level-4 Header</em>

Content
```

pandoc 1.10.1 will create a run-on paragraph when creating a PDF file. In other words, it renders like:

> **Level-4 Header**  Content

This remains true regardless of the specific inline markup used. It is also true even if the inline HTML is taken out and a CSS file used instead. For example, this CSS provides the exact same results as above:

```
h4{font-variant:small-caps;}
```

Expected behavior is that pandoc will respect both inline formatting directives and CSS styling when creating PDF files. If not, the proper way to format nested headings should be explicitly documented somewhere.

**Comment by chrissound** [comment]
I think a solution for this can be found here: https://stackoverflow.com/questions/21198025/pandoc-generation-of-pdf-from-markdown-4th-header-is-rendered-differently/57481097#comment106593857_57481097
