### ISSUE TITLE
docx writer: re-use image/table id in caption

### ISSUE THREAD

**Issue by tstenner** [jgm/pandoc#7551]
The `native_numbering` extension currently adds a native figure number to images and tables. As part of it, the whole figure is wrapped in a bookmark named after the image ID and the caption is wrapped in two bookmarks `#_Ref<some number>` and `#figX` where `X` is a consecutive number.

In order to insert the number of a figure, a field like `<w:fldSimple w:instr=" REF _Ref_superfig "><w:r><w:t>Placeholder</w:t></w:r></w:fldSimple>` can be added to the text. For this, it'd be great if the name of the caption bookmark could be deduced from the figure id, e.g. `#superfig` for the whole figure and `#ref_superfig` or `#caption_superfig` for just the caption.

For reference, `![Testfigure](image.png){#superfig}` produces something like this:

```
      <w:bookmarkStart w:id="0" w:name="superfig"/>                                          <- bookmark #superfig start
      <w:r>        <w:drawing> [..] </w:drawing>      </w:r>
      <w:bookmarkEnd w:id="0"/>
    </w:p>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="ImageCaption"/>
      </w:pPr>
      <w:bookmarkStart w:id="1" w:name="_Ref81908698"/>                                      <- bookmark reference number start
      <w:bookmarkStart w:id="2" w:name="fig1"/>                                              <- bookmark #figX start
      <w:r>        <w:t>Figure </w:t>      </w:r>
      <w:r>        <w:fldChar w:fldCharType="begin"/>      </w:r>
      <w:r>        <w:instrText xml:space="preserve">SEQ Figure \* ARABIC </w:instrText>      </w:r>
      <w:r>        <w:fldChar w:fldCharType="separate"/>      </w:r>
      <w:r>        <w:t>1</w:t>      </w:r>
      <w:r>        <w:fldChar w:fldCharType="end"/>      </w:r>
      <w:bookmarkEnd w:id="1"/>
      <w:r>        <w:t xml:space="preserve">: </w:t>      </w:r>
      <w:bookmarkEnd w:id="2"/>
      <w:r>        <w:t>Testfigure</w:t>      </w:r>
    </w:p>
  [..]
```

**Comment by jgm** [comment]
I'm not sure I understand the proposal -- can you give a diff between the actual output (above) and what you'd hope for?

**Comment by tstenner** [comment]
The current captions are just numbered, bug without counting the figures / tables it's hard to insert references to them.

``` patch
@@ -2,7 +2,7 @@
<w:bookmarkStart w:id="0" w:name="superfig"/>
 <w:r><w:drawing> [..] </w:drawing></w:r>
 <w:bookmarkEnd w:id="0"/>
 <w:bookmarkStart w:id="1" w:name="_Ref81908698"/>
-<w:bookmarkStart w:id="2" w:name="fig1"/>
+<w:bookmarkStart w:id="2" w:name="ref_superfig"/>
 <w:r><w:t>Figure</w:t></w:r>
 <w:r><w:fldChar w:fldCharType="begin"/></w:r>
 [...]
<w:bookmarkEnd w:id="1"/>
+<w:bookmarkEnd w:id="2"/>
<w:r><w:t xml:space="preserve">: </w:t></w:r>
-<w:bookmarkEnd w:id="2"/>
```

That way, a filter can easily transform `as seen in @fig:superfig` to `as seen in <w:fldSimple w:instr=" REF ref_superfig "><w:r><w:t>Figure X</w:t></w:r></w:fldSimple>` so the `Figure X` is updated whenever a figure is added / removed.
