### ISSUE TITLE
Corner case: Wrong parsing of bullet list item starting with number with period

### ISSUE THREAD

**Issue by Delanii** [jgm/pandoc#7557]
This issue is created per discussion on pandoc mailing list here: https://groups.google.com/g/pandoc-discuss/c/PFxuPB_oHbA

**Explain the problem.**

Recently I have hit upon a corner case which (I guess) wasnt probably thought off. If you have bullet list item like so:

```{org}
- 11. and 12. 09. meeting
```

converting to docx with: `pandoc -o test.docx test.org` yields this:

```{docx}
- and 12. 09. meeting
```

with native pandoc representation:

```{native}
[BulletList [[OrderedList (1,DefaultStyle,DefaultDelim) [[Plain [Str "and",Space,Str "12.",Space,Str "09.",Space,Str "meeting"]]]]]]
```

Which is for me little baffling -- There should be bullet list, that contatins only ordered list starting with 1??

Converting the same text with markdown:

```{md}
- 11. and 12. 09. meeting
```

makes different result

```{docx}
11. and 12. 09. meeting
```

where "11." is custom number started ordered list.

The pandoc native output corresponds with that.

```{native}
[BulletList [[OrderedList (11,Decimal,Period) [[Plain [Str "and",Space,Str "12.",Space,Str "09.",Space,Str "meeting"]]]]]]
```

I think that is issue on the side of readers -- at least on side of org reader and markdown reader. None of them interprets given text as one item of bullet list. Instead, they are omitting first number (org) or making it custom ordered list start. That can be perfectly seen when converting to tex:

```{org}
- 11. and 12. 09. meeting
```

```{tex}
\begin{itemize}
\item
  \begin{enumerate}
  \tightlist
  \item
    and 12. 09. meeting
  \end{enumerate}
\end{itemize}
```

and

```{md}
- 11. and 12. 09. meeting
```

```{tex}
\begin{itemize}
\item
  \begin{enumerate}
  \def\labelenumi{\arabic{enumi}.}
  \setcounter{enumi}{10}
  \tightlist
  \item
    and 12. 09. meeting
  \end{enumerate}
\end{itemize}
```

I guess that fix could be as follows:

Org reader: Item in bullet list is started by "-", "+" or "*" (I believe those are hardcoded in org, other markers are no longer customizable and recognized by org) and ended by 1 or more linebreaks directly followed by another bullet list mark. Anything between that is list of inlines.

Markdown reader: Item in bullet list is started by "-" and ended by 1 or more linebreaks directly followed by another dash (I believe that is in accordance with markdown specification and with pandoc syntax specification).

The rules for nesting or not afffeced by this, since in org mode nesting requires changing the bullet marker (or changing indentation, but I am not sure if that is also accepted) and markdown requires indentation change.

I have basic understanding of Haskell syntax, and I am slowly progressing through pandoc types definitions and csv reader, but I still dont think I would be able to do the outlined changes. However, I can try, if anybody would agree to proposed solutions.

Thank you for reading through this, hopefully it is not too long.

**Pandoc version?**
Pandoc 2.10.1 on Windows
Native outputs tested in current Try pandoc, which is 2.14.2

**Comment by jgm** [comment]
I think the docx writer could do better in rendering
```
[BulletList [[OrderedList (1,DefaultStyle,DefaultDelim) [[Plain [Str "and",Space,Str "12.",Space,Str "09.",Space,Str "meeting"]]]]]]
```
but that's not the main issue.

The main issue is that the org reader should (apparently) not allow a list to be the initial content of a list item.  (Need to confirm this with Emacs)

**Comment by jgm** [comment]
Looks like org only accepts a para or plain at the beginning of a list item. Should be a simple change.

**Comment by Delanii** [comment]
I think the same applies for markdown too, not only org mode. Would the, practically same fix, be reasonable for markdown reader?

**Comment by jgm** [comment]
No, because the majority of classic markdown implementations do allow lists to start at the beginning of a list item.  See <https://johnmacfarlane.net/babelmark2/?normalize=1&text=-+11.+and+12.+09.+meeting%0A%0A>.  Note that commonmark gives better results in this case.  You may wish to use pandoc's commonmark or gfm or commonmark_x as an input format instead of markdown.
