### ISSUE TITLE
Extend argument parsing in LaTeX reader

### ISSUE THREAD

**Issue by matze** [jgm/pandoc#758]
This Markdown snippet

```
# Test
* \visible<1-2>{Point 1}
* \visible<2->{Point 2}
```

produces this Beamer fragment

```
\begin{frame}\frametitle{Test}

\begin{itemize}
\item
  \visible\textless{}1-2\textgreater{}\{Point 1\}
\item
  \visible\textless{}2-\textgreater{}\{Point 2\}
\end{itemize}
\end{frame}
```

rendering the `\visible` command useless. I am seeing this problem with Ubuntu 12.04's pandoc 1.9.1.1 but the Changelog does not indicate that this has been fixed in a recent release.

**Comment by jgm** [comment]
The LaTeX reader has now been changed to handle these arguments.
