### ISSUE TITLE
[raw_tex] Do not ignore inline LaTeX when converting from pandoc markdown to html 

### ISSUE THREAD

**Issue by GoBigorGoHome** [jgm/pandoc#7587]
**Describe your proposed improvement and the problem it solves.**
From pandoc manual for the `raw_tex` extension:
> Inline LaTeX is ignored in output formats other than Markdown, LaTeX, Emacs Org mode, and ConTeXt.

MathJax can be configured to process LaTeX environments, `\ref`, `\eqref` outside of  math delimiters (see http://docs.mathjax.org/en/latest/options/input/tex.html#the-configuration-block). The `raw_tex` extension allows one to write raw LaTeX environments and commands ("raw" means outside of math delimiters), thus works well with the aforementioned feature of MathJax. However, when the output format is html (where MathJax works), inline LaTeX commands, including `\ref` and `\eqref`, are ignored. I think it's better if `raw_tex` did not ignore inline LaTeX commands for html output format, or at least make this behavior configurable.

On the other hand, if `raw_tex` is disabled, we can still write raw LaTeX environments for MathJax to process but then we often have to backslash-escape the backslash symbol, which is even worse.

**Describe alternatives you've considered.**

Put `\ref` and `\eqref` inside math delimiters `$$`, which is not desirable.

**Comment by jgm** [comment]
They are not exactly ignored:
```
% pandoc -f latex -t html+raw_tex
hi \ref{foo}
^D
<p>hi <a href="#oo" data-reference-type="ref" data-reference="foo">[foo]</a></p>
```
In fact they are parsed as (native)
```

```
[ Para
  [ Link
    ( "", [], [ ( "reference-type", "ref" ), ( "reference", "foo" ) ] )
    [ Str "[foo]" ]
    ( "#foo", "" )
  ]
]
```
so one could write a filter to intercept links like this and reconstruct the original `\ref` command.

That's a suggested workaround, anyway.  It's still worth considering modifying the code to simply pass `\ref` and `\eqref` commands through as raw tex when `raw_tex` is enabled. I think that makes sense, but it's a bit hard to anticipate how current workflows based on the current behavior might break...

**Comment by GoBigorGoHome** [comment]
> They are not exactly ignored:
> ```
> % pandoc -f latex -t html+raw_tex
> hi \ref{foo}
> ^D
> <p>hi <a href="#oo" data-reference-type="ref" data-reference="foo">[foo]</a></p>
> ```

I am sorry I did not mention that the issue is about converting from pandoc markdown to html.
```
> pandoc -f markdown -t html
abcd \ref{e} abcd
^Z
<p>abcd  abcd</p>
```

**Comment by jgm** [comment]
OK, that helps.  Here's the relevant code in the HTML writer for RawInline:
```hs
     if (f == Format "latex" || f == Format "tex") &&
                allowsMathEnvironments (writerHTMLMathMethod opts) &&
                isMathEnvironment str          
                then inlineToHtml opts $ Math DisplayMath str            
                else do                               
                  report $ InlineNotRendered inline      
                  return mempty  
```
We could do something similar for eq and eqref commands (maybe only MathJax supports these?).

**Comment by jgm** [comment]
I've done this -- try it out and let me know if it works.

**Comment by ickc** [comment]
I just tried this. Works like a charm.

I remember proposing something like this backward: like mapping `$\eqref{...}$` to `\eqref{...}` when outputting to LaTeX. I wish I thought about this solution years ago.

**Comment by ickc** [comment]
@jgm, sorry, upon more testing, I found that with

```md
Simple quote \eqref{eqx} here.
```

when running

```bash
pandoc temp.md --mathjax
```

would results in

```html
<p>Simple quote <span class="math display">\[\eqref{eqx}\]</span> here.</p>
```

shouldn't it be `<p>Simple quote <span class="math inline">\(\eqref{eqx}\)</span> here.</p>` instead?

**Comment by jgm** [comment]
Oh, I'll fix that.

**Comment by jgm** [comment]
Fixed.

**Comment by jgm** [comment]
commit f0a6eb913d7ace9de720539efb8984ea00ac82db (I got the wrong issue number in the message)

**Comment by ickc** [comment]
Thanks! It has no problem now from my limited testing.
