### ISSUE TITLE
Empty table with header generated as paragraphs  HTML ----> DOCX

### ISSUE THREAD

**Issue by twiggler** [jgm/pandoc#7589]
**Explain the problem.**
A table with a single header row and an empty body is translated to paragraphs with the columns names. 
Expected: An empty table with a header. 

[Desktop.zip](https://github.com/jgm/pandoc/files/7215818/Desktop.zip)

command: pandoc --output --to docx reference-doc=custom-reference.docx report-14962970001494587488.html

**Pandoc version?**
pandoc.exe 2.14.2 windows
[Desktop.zip](https://github.com/jgm/pandoc/files/7215818/Desktop.zip)

**Comment by jgm** [comment]
Simpler to see it this way:
```
% pandoc -f html -t native
  <table> 
   <thead> 
    <tr> 
     <th>experience</th> 
     <th>expertise</th> 
     <th>paradigms</th> 
     <th>haskell</th> 
     <th>name</th> 
     <th>image</th> 
    </tr> 
   </thead> 
   <tbody></tbody> 
  </table> 
^D
[ Plain
  [ Str "experience" ]
, Plain
  [ Str "expertise" ]
, Plain
  [ Str "paradigms" ]
, Plain
  [ Str "haskell" ]
, Plain
  [ Str "name" ]
, Plain
  [ Str "image" ]
]
```
