### ISSUE TITLE
Export pandoc's file name extension map

### ISSUE THREAD

**Issue by lassik** [jgm/pandoc#7590]
**Describe your proposed improvement and the problem it solves.**

Pandoc contains a table mapping file name extensions to file formats in [`FormatHeuristics.hs`](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/App/FormatHeuristics.hs), but doesn't seem to export it. Could an official, exported mapping be added?

**Describe alternatives you've considered.**

We currently [maintain our own mapping in `pandoc-tar`](https://github.com/lassik/pandoc-tar/blob/master/Extensions.hs). Our mapping is bidirectional; it would be nice if the official one were as well.

**Comment by jgm** [comment]
Seems reasonable to me. I'll take a look at this when I have a chance.

**Comment by mhwombat** [comment]
Likewise, [pandoc-plot](https://github.com/LaurentRDC/pandoc-plot/blob/master/src/Text/Pandoc/Filter/Plot/Clean.hs) has to maintain a copy of the mapping because it's not exported. And I will have to maintain a mapping for a project I'm currently working on.

**Comment by mhwombat** [comment]
Pull request https://github.com/jgm/pandoc/pull/8693 will export the mapping. However, it doesn't make the mapping bidirectional as @lassik suggested.

**Comment by mhwombat** [comment]
@LaurentRDC this issue may be of interest for pandoc-plot if it would allow you to eliminate the duplicate code in https://github.com/LaurentRDC/pandoc-plot/blob/master/src/Text/Pandoc/Filter/Plot/Clean.hs.
