### ISSUE TITLE
"Library" lowercased on BibLaTeX to CSL JSON conversion

### ISSUE THREAD

**Issue by Amphiboly** [jgm/pandoc#7591]
As the title says, each occurrence of the term "Library" in a BibLaTeX series name is converted to a collection-title with "library" in its stead. MWE:

> ╰─► pandoc -f biblatex -t csljson
@book{xx, title="abc", author="def", series={{Library Sibrary Library}}, date=1999}
^Z
[
  {
    "author": [
      {
        "family": "def"
      }
    ],
    "collection-title": "library Sibrary library",
    "id": "xx",
    "issued": {
      "date-parts": [
        [
          1999
        ]
      ]
    },
    "title": "Abc",
    "type": "book"
  }
]

**Comment by jgm** [comment]
Even weirder: this affects collection-title but not title.
