### ISSUE TITLE
epub:type attribute in epub2

### ISSUE THREAD

**Issue by cursosatb** [jgm/pandoc#7592]
Pandoc sets the epub:type attribute in body tag for epub2, when in fact this attribute is not compatible with epub2 because it's [version 3 specific](https://www.w3.org/publishing/epub3/epub-contentdocs.html#sec-epub-type-attribute).

More info: https://support.google.com/books/partner/answer/3316879?hl=en

Version: tested on 2.5

**Comment by jgm** [comment]
That's a pretty old version.  Cursory testing with the latest version seems to show that the problem has already been fixed.
Try installing the latest (see Releases on this site) and report back?

**Comment by cursosatb** [comment]
ok, thanks very much
