### ISSUE TITLE
markdown rendered as dl/dt/dd

### ISSUE THREAD

**Issue by gmccullo** [jgm/pandoc#7594]
Here's the markdown:

```md
<div class="epigraph verse closeup">

<span style="margin-left: 6em;">… Picassio,</span>

Who cuts so fine a form of manliness,

So well endowed in leg and mind and dress.

~ Picassio

</div>
```

Which I generate as an epub. And this bit gets rendered as this html:

```html
<div class="epigraph verse closeup">
	<p><span style="margin-left: 6em;">… Picassio,</span></p>
	<p>Who cuts so fine a form of manliness,</p>
	<dl>
		<dt>So well endowed in leg and mind and dress.</dt>
		<dd>
			<p>Picassio</p>
		</dd>
	</dl>
</div>
```

However the markdown does not seem to match the format required for a definition list as given in the pandoc manual:

```
Term 1
  ~ Definition 1
```

There's no space before the tilde, and there's a blank line between the tilde line (rendered as the dd) and the line that precedes it (rendered as the dt).

**Comment by jgm** [comment]
Interesting! This looks like a regression.

**Comment by jgm** [comment]
Minimal test cases:
```
% pandoc                            
a 

: b

<dl>
<dt>a</dt>
<dd><p>b</p>
</dd>
```
```
% pandoc
a

~ b

<dl>
<dt>a</dt>
<dd><p>b</p>
</dd>
</dl>
```

**Comment by jgm** [comment]
Hm.  I'm seeing this behavior back (at least) to 1.19.2.1, so if it's a regression it's a very old one!

**Comment by jgm** [comment]
Line 946 of the Markdown reader has
```hs
try (count remaining (char ' ')) <|> string "\t" <|> many1 spaceChar
```
Here the last clause will kick even if there's just one space after the initial marker.  It looks as if this was added intentionally at some point -- will try to track down why.

**Comment by jgm** [comment]
Sure enough!  We've had this behavior since 2015.
See commit d3544dc6f7a2386c4a68a85110f322b50332cfbe and #2087.
So, we just need to update the documentation.

**Comment by jgm** [comment]
Note that you cn backslash-escape the `~` to avoid this behavior when you don't want it.
