### ISSUE TITLE
[pptx output] Image does not appear within two-column layout

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#7595]
In pptx output, image does not appear within two-column layout.

Tested with Pandoc v2.14.2 on Windows.

## Reproducible Markdown

``` markdown

# Test

:::::::::::::: {.columns}
::: {.column}

## Input

![Keyboard and mouse](https://cdn.pixabay.com/photo/2015/09/09/21/38/keyboard-933568_1280.jpg)

:::
::: {.column}

## Output

![Monitor](https://cdn.pixabay.com/photo/2016/10/16/16/33/dual-screen-1745705_1280.png)

:::
::::::::::::::
```

**Comment by jgm** [comment]
This works fine with the dev version, so the issue may have already been fixed.
Try a nightly.

**Comment by mb21** [comment]
This should be fixed in the latest release, please reopen if not.
