### ISSUE TITLE
EML email format (high compatibility email client HTML)

### ISSUE THREAD

**Issue by Sarke** [jgm/pandoc#7596]
**Describe your proposed improvement and the problem it solves.**
There is a very distinctive HTML flavor that plagues developers: email client compatible HTML.  It's usually built without (or with very little) CSS and usually does the layout using `<table>` tags.  There's no standard, so email clients like Outlook, Gmail, Thunderbird, iPhone, etc, will support different features.  The "standard" approach is to only use the lowest common denominator features.

This is also a very common use-case, to create rich marketing emails and newsletters that both look good but especially look right on most email clients.

**Describe alternatives you've considered.**
I'm not aware of any other writers, outside of the proprietary templates from companies like MailChimp and such.

**Comment by jgm** [comment]
Are there particular things about pandoc's HTML output that make it unsuitable for this purpose? If so, it would be helpful to be specific.

**Comment by aubertc** [comment]
This would be amazing, but I'm not sure it would be very easy, nor that pandoc is the right tool for that.

Quoting [premailer](https://www.graphicxtreme.com/premailer/): 

> For the best HTML e-mail delivery results, CSS should be inline. This is a huge pain and a simple newsletter becomes un-managable very quickly. This script is our solution.
> 
>     CSS styles are converted to inline style attributes
>     Checks style and link[rel=stylesheet] tags and preserves existing inline attributes
>     Relative paths are converted to absolute paths
>     Checks links in href, src and CSS url('')
>     CSS properties are checked against e-mail client capabilities (Based on the [Email Standards Project’s guides](http://www.email-standards.org/))
>     A plain text version is created

There is [an active github repo](https://github.com/peterbe/premailer) that takes care of the "in-linining the ccs", but the "transform everything into tables" seems _very hard_ to automate, in my opinion.

**Comment by mb21** [comment]
There shouldn't be anything specific to pandoc's HTML output that causes Email clients trouble, as it barely contains any formatting. If you want a custom layout for HTML emails, then yes, you'll need to use a custom template that will layout your header/footer with tables. But that's out-of-scope to include in pandoc out of the box as it will vary widely by which layout you want.

[EML](https://www.loc.gov/preservation/digital/formats/fdd/fdd000388.shtml) is also the file extension used by Outlook Express for files in the [Internet Message Format (RFC 5322)](https://datatracker.ietf.org/doc/html/rfc5322). (I believe MBOX is another container format for the same.) But I don't see the use-case for having a pandoc writer for that format. Usually, you'd want to send the HTML pandoc generated as an email, not store it in a file that Outlook could read.

**Comment by aubertc** [comment]
I believe you can close this issue indeed.
