### ISSUE TITLE
Some H3 headers not recognized when exporting from .md to .pdf

### ISSUE THREAD

**Issue by daanrongen** [jgm/pandoc#7598]
**Explain the problem.**

In my markdown document I have a lot of H1, H2 and H3 headers. Almost all of these headers are parsed correctly when exporting the document to .pdf format, except for one (or sometimes two) headers that are H3.

Example:

```
### Data Augmentation ###

The neural network needs approximately 5.000 embeddings per category in order to make good predictions. To automate the generation of embeddings and to enlargen the dataset, data augmentation is applied as follows: 
```

The .pdf export renders all the headers accordingly, except for one, which is rendered as a body text with `### Data Augmentation ###` as copy.

The command I'm using to export to .pdf is:

```
pandoc --citeproc pandoc/document.md pandoc/meta.yml -o document.pdf
```

**Pandoc version?**
pandoc 2.14.2
Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.11, citeproc 0.5, ipynb 0.1.0.1

**Comment by alerque** [comment]
The error is in your input. You have a Unicode non-breaking space (`U+00A0`) in your header after the hash marks before the "D" of "Data". Change that to a space to be a valid markdown header syntax.
