### ISSUE TITLE
Frontispiece as part of frontmatter for epub

### ISSUE THREAD

**Issue by kleinbottle** [jgm/pandoc#7600]
The `frontispiece` often comes right after the cover, or in some cases, the `halftitlepage` in conventional books as part of the `frontmatter`.

I would like to suggest including it  so that it may be invoked as ` {epub:type=frontispiece}`

Associated with this is the query "how to get it to work?" because usually, the frontispiece does not take a (chapter) heading and is usually only an image (with caption) on its own.

If it is too much hassle, perhaps one could fudge it somehow with an empty dummy chapter, although I am not sure how.

**Comment by jgm** [comment]
Should we just add `frontispiece` to the table recorded here?
https://pandoc.org/MANUAL.html#the-epubtype-attribute

**Comment by kleinbottle** [comment]
@jgm: Yes indeed! That was my intention.

I do not know if there is a way to have an _invisible chapter name_ as well for this case.

**Comment by jgm** [comment]
If you do

```
# {epub:type=frontispiece}

![](yourimage.jpg)
```
then you won't get a chapter heading. Is that what you mean by invisible chapter name?

**Comment by kleinbottle** [comment]
Yes. The image has its own page without a heading but with a caption.

Only one more question: will it show up in the TOC as Frontispiece by 
virtue of the tag?

Chandra

**Comment by jgm** [comment]
Try it and let me know.
And if it does, and you don't want it to, try adding `.unlisted` to the attributes.
