### ISSUE TITLE
Pass through <index> elements from DocBook sources

### ISSUE THREAD

**Issue by bigsmoke** [jgm/pandoc#7608]
`<index>` elements are currently ignored. However, when going from DocBook to LaTeX to print, this may be very necessary (and indeed is in my own publication pipeline.

`<index>` is kept in the AST when reading DocBook.

**Comment by jgm** [comment]
Just wondering why this would be useful...  Going to LaTeX, wouldn't you need the page numbers to be correct, and how is that done?

**Comment by bigsmoke** [comment]
> Just wondering why this would be useful... Going to LaTeX, wouldn't you need the page numbers to be correct, and how is that done?

In my pipeline, I only use the DocBook `<index>` as a placeholder to later put a `\printindex` LaTeX command there using a Lua filter.

**Comment by jgm** [comment]
Ah, I see.

**Comment by bigsmoke** [comment]
I do realize that this is pretty much an edge cage and will 100% understand it if the linked PR is not accepted.

**Comment by bigsmoke** [comment]
The main reason I did it this way is because I generate the DocBook from Asciidoc. For Asciidoc, this is the way to indicate that you want an index placed there. It just goes to show that sometimes it's difficult to map semantics between different formats.

**Comment by jgm** [comment]
So, if I understand correctly, the docbook produced from asciidoc will just contain an index element without any contents?  (That's probably an unusual case.)

**Comment by bigsmoke** [comment]
> So, if I understand correctly, the docbook produced from asciidoc will just contain an index element without any contents? (That's probably an unusual case.)

That's correct. And it'd be easy enough for me to put the `\printindex` in the LaTeX template instead of a filter.

By the way: this issue is almost entirely unrelated to issue  #7427.

**Comment by jgm** [comment]
One option would be to insert the section with identifier, but skip parsing the index element's children. (In that case you couldn't use sectWith, which parses the contents; you'd just use headerWith.)
But in making this decision I'd want to know more about what normal docbook files contain in the index element, and what our parser would do with this content.

**Comment by bigsmoke** [comment]
It is actually rare to have an `<index>` in DocBook documents, because, normally, the index would be auto-generated based on `<indexterm>`s encountered in the document. Having discussed this with you, I think it would be best to close this present issue as well as refuse the linked PR.
