### ISSUE TITLE
Create fillable pdf

### ISSUE THREAD

**Issue by catap** [jgm/pandoc#7610]
**Describe your proposed improvement and the problem it solves.**

Introduce a way to create a fillable PDF.

**Describe alternatives you've considered.**

Right now you can do it inside latex like:
```
\documentclass{article}

\usepackage{hyperref}

\begin{document}

\begin{Form
\begin{tabular}{l}
    \TextField{Name} \\\\
    \TextField{Surname} \\\\
    \TextField{Address} \\
\end{tabular}
\end{Form}


\end{document}
```

**Comment by jgm** [comment]
You can just insert the literal LaTeX in markdown:

````
```{=latex}
\begin{Form
\begin{tabular}{l}
    \TextField{Name} \\\\
    \TextField{Surname} \\\\
    \TextField{Address} \\
\end{tabular}
\end{Form}
```
````

A next step might be writing a Lua filter that converts `Str "{{Name}}"` to `RawInline "latex" "\TextField{Name}".  Then you could simple do

```
Name: {{Name}}
etc.
```

**Comment by catap** [comment]
@jgm I guess I haven't got your idea. Can I ask you to share an example as `.md` file?

**Comment by jgm** [comment]
Try inserting this into your .md file:
````
```{=latex}
\begin{Form
\begin{tabular}{l}
    \TextField{Name} \\\\
    \TextField{Surname} \\\\
    \TextField{Address} \\
\end{tabular}
\end{Form}
```
````
and then convert to PDF as usual.

**Comment by catap** [comment]
got it
