### ISSUE TITLE
Extra-space between fenced code block start and attributes

### ISSUE THREAD

**Issue by kdeldycke** [jgm/pandoc#7616]
Here is a collection of fenced code blocks in Markdown:

``````shell-session
$ cat ./fenced-code-block-attributes.md

```shell-session
cp --help
```

``` shell-session
cp --help
```

```{.shell-session}
cp --help
```

``` {.shell-session}
cp --help
```
``````

To normalize the style of their attributes, I ran pandoc:
``````shell-session
$ pandoc ./fenced-code-block-attributes.md --to=markdown

``` shell-session
cp --help
```

``` shell-session
cp --help
```

``` shell-session
cp --help
```

``` shell-session
cp --help
```
``````

Notice how each code block header gets normalized to `` ``` shell-session ``, i.e. a triple-quote followed by a space then by the language attribute.

I think this is a bug, and I expect the extra space to not be there.

For reference I use the latest pandoc on macOS Big Sur:
```shell-session
$ pandoc --version
pandoc 2.14.2
Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.11,
citeproc 0.5, ipynb 0.1.0.1
```

**Comment by jgm** [comment]
Why is it a bug?  The space is allowed and (I think) looks nicer.

**Comment by jgm** [comment]
No problem.
