### ISSUE TITLE
References in markdown links and spans parsed as citations

### ISSUE THREAD

**Issue by knuesel** [jgm/pandoc#7632]
For example:

```
pandoc -t native
(@a) First case

[link to (@a)](url)
```

gives

```
[ OrderedList
    ( 1 , Example , TwoParens )
    [ [ Plain [ Str "First" , Space , Str "case" ] ] ]
, Para
    [ Cite
        [ Citation
            { citationId = "a"
            , citationPrefix =
                [ Str "link" , Space , Str "to" , Space , Str "(" ]
            , citationSuffix = [ Str ")" ]
            , citationMode = NormalCitation
            , citationNoteNum = 1
            , citationHash = 0
            }
        ]
        [ Str "[link" , Space , Str "to" , Space , Str "(@a)]" ]
    , Str "(url)"
    ]
]
```

The same occurs with spans, e.g. with 

```
(@a) First case

[span with (@a)]{}
```

It seems to me the `[...](...)` and `[...]{...}` semantics should have priority over the citation semantics.

There is also a problem with pandoc-crossref that might be related. Example:

```
pandoc -F pandoc-crossref -t native
# Title {#sec:title}

[text (@sec:title)]{}
[ Header 1 ( "sec:title" , [] , [] ) [ Str "Title" ]
, Para [ Str "text" , Space , Str "(" , Space , Str "1){}" ]
]
```

so we get the string `text ( 1){}`, instead of `text (sec. 1)` inside a span.

Reproduced with pandoc master (465c28d) on Pop OS based on Ubuntu 21.04.

**Comment by jgm** [comment]
One nagging worry about  the fix:  with this fix, `[@foo]{.class}` will never be parsed as a normal citation.  (It will be parsed as a span containing an author-in-text citation.) That's fine with pandoc's markdown as it stands, but if we ever port over the `attributes` extension (now possible with commonmark), authors will expect to be able to add attributes to normal citations.  Not sure how to handle this.  There may be a better fix.
