### ISSUE TITLE
Error on reading tex files.

### ISSUE THREAD

**Issue by magicknight** [jgm/pandoc#7646]
Hi,
Thank you for developing this awesome software. 
I wanna report an error about converting a tex file to a html file.  The tex file is attached here.

**Explain the problem.**

```
pandoc -s --mathjax -o test.html paper.tex

Error at "source" (line 1, column 1):
unexpected Tok "paper.tex" (line 1, column 1) (CtrlSeq "documentclass") "\\documentclass"
expecting end of input
```

[1812.11788v1.zip](https://github.com/jgm/pandoc/files/7447373/1812.11788v1.zip)

**Pandoc version?**
What version of pandoc are you using, on what OS?

```
pandoc -v

pandoc 2.15
Compiled with pandoc-types 1.22.1, texmath 0.12.3.2, skylighting 0.12,
citeproc 0.6, ipynb 0.1.0.2
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
Pandoc is having trouble parsing cpvr.sty -- not surprisingly, as it uses a lot of low level tex.
The cure is to simply comment out the line `\usepackage{cpvr.sty}` in your paper.tex; then pandoc will produce a result.  (Of course, macros defined in cpvr.sty may not work properly, but hopefully you'll get something that's close.)

**Comment by magicknight** [comment]
I see. Thank you for the answer!
