### ISSUE TITLE
Lua filters:  Link content does not work as it used to

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#7647]
I noticed this in generating the pandoc man page (make -B man/pandoc.1), a process which uses a Lua filter (man/manfilter.lua).  But the issue can be seen as follows:
```
% cat t.lua
function Link(el)
  return el.content
end
% echo '[link](url)' | pandoc -L t.lua
<p><a href="url">link</a></p>
```
Previously this would have produced just "link" (and no URL).  (I think this is a regression introduced in 2.15, but still present in current HEAD.)

@tarleb

**Comment by jgm** [comment]
Note that there's even an example like this in the lua filters documentation.

**Comment by tarleb** [comment]
Yikes. :frowning_face:
