### ISSUE TITLE
More convenient syntax for writing poetry

### ISSUE THREAD

**Issue by memeplex** [jgm/pandoc#7648]
**Describe your proposed improvement and the problem it solves.**

pandoc supports keeping line breaks and indentation by preceding each line with a `|`. For already written poetry this syntax does the job, prefixing each line just once is an easy edition task in any decent editor. But for poetry being written it's too inconvenient, since the author often reorganizes the content in different shapes. One can argue that the author should add the `|`s at the end, but the process is not that linear and may involve intermediate steps of critically previewing formatted output as well as presenting the WIP to other people in order to gather feedback.

I would like to have a syntax like the verse block in org-mode that doesn't require extra decorations that get in the way of creative work, specially for poetry which explores possible *shapes* of the text.

I don't write poetry myself but the request is motivated by an objection made by a friend of mine who I'm trying to convince to use pandoc for his writing chores.

I like this syntax:

```
::: verse
...
:::
```

although the fact that the content of the fenced div is not parsed as markdown in this case may be against some rule that I don't know.

**Describe alternatives you've considered.**

I've developed a preprocessor that replaces indentation and line breaks so that they are preserved inside a LaTeX verse environment. Unfortunately it's not possible to do this in a filter since at that stage some of the required whitespace has already been discarded by the parser. I'm not using a proper parser for my preprocessor, just simple regex substitution. The preprocessor supports a syntax similar to the fenced divs proposed above, but it's of course unaware of its syntactical surrounding.

I believe that using fenced code blocks and writing a filter instead may be an option, although the default syntax highlighting that many (likely most) editors use for fenced code blocks dissuades me from even trying.

Including a verse environment in raw LaTeX is another option, but not really more convenient than the `|` prefix that motivates this request.

**Comment by jgm** [comment]
I am not too inclined to act on this, since we already provide a *pretty* convenient way to write poetry, namely line blocks.  To the extent that this proposal has merit, an exactly similar argument could be made to provide an alternative to side-marked block quotes.  Note, also, that a design principle of pandoc is to avoid using English words to mark syntactic constructions.

**Comment by memeplex** [comment]
Ok, fair enough. I've been developing my preprocessor further and I realize there are some subtle issues, for example line blocks add struts for vertical spacing but the verse environment marks the end of stanzas in a different, more specific, way and also provides other refinements. For now I'm content with a preprocessor that prefixes each line of the poem with `| ` and wraps the environment inside `::: verse ... :::`, then a filter replaces that with `\begin{verse}...\end{verse}` in the LaTeX case. For the preprocessor I ended up using jinja2 which also solves other problems like file inclusion, conditional output, etc. In order to keep the surface syntax simple I replace `,,, name ... ,,,` with `{% filter name %} ... {% endfilter %}` and also, for inlines, `,{...|name}` with `{{"""..."""|name}}`. This is a very interesting solution, because I not only get a proper grammar and parser instead of regex hacks, but also handy preprocessing constructs, while still keeping the syntax clean by doing a couple of upfront naive substitutions. The little experiment of formatting poetry ended up in a powerful more general approach and I'm somewhat less interested in the original issue now.

**Comment by jgm** [comment]
Great. Yes, a preprocessor + pandoc is an interesting combination!
