### ISSUE TITLE
LaTeX to EPUB math stuff missing

### ISSUE THREAD

**Issue by DavidGriffith** [jgm/pandoc#765]
I'm not sure how far it goes, but at least "\frac{x}{y}" will be passed through unchanged to the output EPUB document.

```
\documentclass[12pt]{book}
\begin{document}
$\sqrt{x}$

$\sum_{i=1}^{10} t_i$

$\frac{x}{y}$
\end{document}
```

**Comment by njamescouk** [comment]
In the context of latex -> html translations, this may be good enough:

file fractions.latex

	\documentclass{article}

	\begin{document}
	\begin{tabular}[]{ r r r r r r r r }
	to the power & $^{^-1}$ & $^{^-2}$ & $^{^-3}$ & $^{^-4}$ & $^{^-5}$ & $^{^-6}$ & \ldots{}\\[.5em]
	2 & $\frac{1}{2}$ & $\frac{1}{4}$ & $\frac{1}{8}$ & $\frac{1}{16}$ & $\frac{1}{32}$ & $\frac{1}{64}$ & \ldots{}\\[1em]
	3 & $\frac{1}{3}$ & $\frac{1}{9}$ & $\frac{1}{27}$ & $\frac{1}{81}$ & $\frac{1}{243}$ & $\frac{1}{729}$ &\\[1ex]
	\ldots{} & & & & & &\\[2ex]
	10 & $\frac{1}{10}$ & $\frac{1}{100}$ & $\frac{1}{1000}$ & \ldots{} & & &\\
	\end{tabular}
	\end{document}

Now do a simple minded transformation like so:

	    pandoc -s -t html5 -f latex -o fractions.html fractions.latex

	    sed s/$\\frac{/^<sup^>/  fractions.html > tmp.html
	    sed s#}{#^</sup^>/^<sub^>#  tmp.html > fractions.html
	    sed s#}\$#^</sub^>#  fractions.html > tmp.html
	    mv tmp.html fractions.html
