### ISSUE TITLE
Lua: MetaList no longer a table in v2.16

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#7650]
I believe that this is expected based on my understanding of the changes made to Lua filters in v2.16, but I think it is pretty likely to break existing filters. For example, for this filter `metalist.lua`:

```lua
Pandoc = function(el)
  local list = pandoc.MetaList({})
  list:insert("item")
end
```

This works without error in Pandoc 2.14.2, however for Pandoc 2.16 we get:

```bash
$ echo "hello" | pandoc --to native --lua-filter metalist.lua 
Error running filter metalist.lua:
metalist.lua:5: attempt to call a nil value (method 'insert')
stack traceback:
        metalist.lua:5: in function 'Pandoc'
```

The Lua filter docs imply that `List` will be a Lua table (https://pandoc.org/lua-filters.html#type-list) so it seems like there will be some amount of this sort of code in the wild.

If this part of parcel of the performance improvements and necessary breakage of existing filters that's fine, but just wanted you to know in the case that this was unintentional.

**Comment by jjallaire** [comment]
Note that that the following equivalent code does work in Pandoc 2.16:

```lua
Pandoc = function(el)
  local list = pandoc.MetaList({})
  table.insert(list, "item")
end
```

Calling `tostring()` on the `list` also indicates that it is in fact a `table`, but calling `list:insert` directly no longer works.

**Comment by jgm** [comment]
@tarleb can clarify this

**Comment by tarleb** [comment]
Sorry, I removed one line too many during a cleanup. Pushing a fix now.
