### ISSUE TITLE
Lua: Attempt on insert content into Header fails in v2.16

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#7651]
For this filter `header.lua`:

```lua
Header = function(el)
  el.content:insert(pandoc.Str("text"))
  return el
end
```

I see this error in v2.16:

```bash
$ echo "# hello" | pandoc --to native --lua-filter header.lua 
Error running filter header.lua:
header.lua:4: attempt to index a nil value (field 'content')
stack traceback:
        header.lua:4: in function 'Header'
```

Whereas this works without error in Pandoc v2.14.2

**Comment by tarleb** [comment]
That was an oversight on my part, fixed via 759aa5095101351bc2e4d2c4629df945b743e7db. See also #7652.

**Comment by jjallaire** [comment]
Thanks! With that fix + migrating away from uses of `:new` all of our tests are now passing w/ pandoc `master`.

**Comment by tarleb** [comment]
That's good to hear. Thanks for testing and sorry for the inconvenience.
