### ISSUE TITLE
Docx reader: over-eager block quote recognition

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#7655]
The following document has a style in which paragraphs after the first paragraph are indented on the first line.  Pandoc treats all these subsequent paragraphs as block quotes.

[Lorem Ipsum.docx](https://github.com/jgm/pandoc/files/7463606/Lorem.Ipsum.docx)

**Comment by jgm** [comment]
I suspect this is a regression due to #7606 because I can't reproduce with pandoc 2.14.2.

**Comment by Duonganh68pro** [comment]
OK you
