### ISSUE TITLE
pandoc --columns not function in sub files

### ISSUE THREAD

**Issue by ajeep8** [jgm/pandoc#7656]
If these's a pipe table in main.md file, it will wrap lines only when line content length >72.
so if the line content lenght is long but <=72, pandoc to pdf, the table will expand far to pdf page right and can not see all the content.

I can walk around this problem using:
```
pandoc --columns=10 main.md -o main.pdf
```
(set columns a very small value than 72) the pipe table line will wrap even the line content<=72.

But, if the pipe table is in sub files, this trick will not function.

I test 3 filters:
[lua-filters](https://github.com/pandoc/lua-filters):include-files.lua: sub file pipe table only wrap when pipe table line content >80, even I set --columns=10
[panda.lua](https://github.com/CDSoft/panda): same as include-files.lua
[pandoc-include](https://github.com/DCsunset/pandoc-include): sub file pipe table only wrap when pipe table line content >72, even I set --columns=10

I didn't find any process for columns or table in these 3 filter source code, so maybe bug in pandoc? I'm using pandoc 2.14.2

**Comment by jgm** [comment]
This is basically the same issue as pandoc/lua-filters#195, no?
As noted there, the underlying issue is that pandoc.read (which these filters use to parse the contents of the subfiles) doesn't take reader options.  That could be changed, I imagine, but @tarleb could comment further.

One more reason a native support for includes in markdown would be nice, see #553.

**Comment by tarleb** [comment]
We could, as a first step, allow to use the values from the `PANDOC_READER_OPTIONS ` global in `read`, but the global is read-only.  Adding a constructor for a read- and writeable object, which would make it possible to use options different from default/global options, would be a little more work, but not hard either.

**Comment by jgm** [comment]
Here's a thought.  We have From/ToJSON instances for ReaderOptions and all the derivative types it uses.  Couldn't you piggy-back on those?  That is: add Text.Pandoc.Lua.Marsrhaling.Value for aeson Value, and then use the To/FromJSON instances to convert to and from Value.  That gives you "free" bidirectional marshalling that is guaranteed to match up with the JSON marshalling.

**Comment by tarleb** [comment]
We did that for our first Lua filters draft implementation, and it worked reasonably well IIRC. I still have [hslua-aeson](https://hackage.haskell.org/package/hslua-aeson) lying around for this purpose, but it doesn't support aeson 2.0 yet. It would be helpful to marshal Extensions, I think. I'll give it a go again.

**Comment by ajeep8** [comment]
Sorry to disturb you, I'm not familiar with the github dev progress.
I see you had update some codes, and release to 2.16.2, but this bug is still there. 

My env:
- pandoc 2.16.2
- include-files.lua # seem not update
- columns: 10  # in defaults yaml file
- pipe table with long row but &lt; 72 in sub.md (main.md include it)

**Comment by tarleb** [comment]
I've updated the filter. Try it in combination with the latest pandoc
nightly.
