### ISSUE TITLE
Lua filters: notes on v2.16.1 differences

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#7657]
All my filters are now working fine with 2.16.1, but I wanted to list a few things that I've noticed, some of which might be unintentional. I'm happy to create new issues for anything that might result in a future change. I'm also happy to contribute to the best of my ability (which sadly doesn't include Haskell programming).

## Userdata pairs() include 'tag', nil values and functions

I noticed that the attributes returned by pairs() include `tag`, several `nil` values (for attributes that don't necessarily apply to the element type) and various functions. It's easy to ignore them, but I wondered whether it was intentional.

```
Text
```
```
function Para(para)
    for n, v in pairs(para) do
        io.stderr:write(n .. ' ' .. tostring(v) .. '\n')
    end
end
```
```
% pandoc para.md -L pairs.lua
attr nil
bodies nil
caption nil
colspecs nil
content table: 0x7fd29960ad20
foot nil
format nil
head nil
level nil
listAttributes nil
tag Para
text nil
clone function: 0x7fd299413140
show function: 0x7fd2994132c0
<p>Text</p>
```

## Missing argument error messages

Omitting the `src` argument from the `Image()` constructor gives a strange `string expected, got string` message:

```
![](Cat.png){#id .class width=420}
```
```
function Image(image)
    local new_image = pandoc.Image(image.caption)
end
```
```
% pandoc image.md -L image.lua
Error running filter image.lua:
string expected, got string
	while retrieving function argument src
	while retrieving arguments for function Image
```

Pandoc 2.14.1 (presumably unintentionally?) permits this:
```
% pandoc-2.14.1 image.md -L image.lua
<p><img src="Cat.png" id="id" class="class" width="420" /></p>
```

Don't get me wrong: it's great that the error is caught and reported.

## AttributeList constructor (and constructor docs in general)

The 2.15 release notes mention `AttributeList()` but I didn't see any info on how to use it.

More generally, I feel that the lua constructor documentation is rather sparse. Compare [pandoc.Image](https://pandoc.org/lua-filters.html#type-image), which states the data type of each field, with [pandoc.Image()](https://pandoc.org/lua-filters.html#pandoc.image), which is quite vague. For example, I think that `caption` can in fact be either a string or a list of `Inline`s?

**Comment by tarleb** [comment]
Thanks, it's a relieve to know that things are working ok again.

The `pairs` behavior is a bug, at least with regard to the inclusion of `nil` values. Having object methods in there was intentional, but I hadn't thought about pandoc when I wrote that code. Maybe this is a mistake, too? Please raise a new issue, either here or at https://github.com/hslua/hslua/.

I plan to generate the constructor documentation from the Haskell code, and to make the docs accessible from within the Lua interpreter. It's probably worth a separate issue, too.

**Comment by wlupton** [comment]
Thanks. I'll raise issues as requested. What about item 2 "_Missing argument error messages_"?

**Comment by tarleb** [comment]
I had missed that somehow. Definitely a bug in hslua. I'll raise one there.

**Comment by wlupton** [comment]
OK, I think that all the issues raised here are now covered in their own tickets, so I'll close this one.
