### ISSUE TITLE
[Enhancement] Search $XDG_DATA_HOME for lua filters/packages

### ISSUE THREAD

**Issue by pbsds** [jgm/pandoc#7659]
Trying to include the lua filter `pandocker/svgbob.lua` filter from [`pandocker-lua-filters`](https://github.com/pandocker/pandocker-lua-filters) (installed via `pip` with `--user`), which in turn [requires](https://github.com/pandocker/pandocker-lua-filters/blob/5a05a28bb6dc0d7c0c1bedfe0bcb4502750cd54b/lua/svgbob.lua#L11) a `pandocker/utils.lua`, gives me the following error:

```
/home/pbsds/.local/share/lua/5.3/pandocker/svgbob.lua:11: module 'pandocker.utils' not found:
	pandocker.utilsis not one of pandoc's default packages
	no field package.preload['pandocker.utils']
	no file '/usr/share/lua/5.3/pandocker/utils.lua'
	no file '/usr/share/lua/5.3/pandocker/utils/init.lua'
	no file '/usr/lib/lua/5.3/pandocker/utils.lua'
	no file '/usr/lib/lua/5.3/pandocker/utils/init.lua'
	no file './pandocker/utils.lua'
	no file './pandocker/utils/init.lua'
	no file '/usr/lib/lua/5.3/pandocker/utils.so'
	no file '/usr/lib/lua/5.3/loadall.so'
	no file './pandocker/utils.so'
	no file '/usr/lib/lua/5.3/pandocker.so'
	no file '/usr/lib/lua/5.3/loadall.so'
	no file './pandocker.so'
```

Noticeably absent is user directories like `~/.local/share/lua/5.3`.
I prefer not to install `pip`/github packages system-wide.
As such i request that pandoc also search the `$XDG_DATA_HOME` defined by the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) or `~/.local/share` if the variable is unset.

# Pandoc version:

    pbsds@bjarte ~$ pandoc --version
    pandoc 2.14.1
    Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.11,
    citeproc 0.4.1, ipynb 0.1.0.1
    User data directory: /home/pbsds/.local/share/pandoc

**Comment by pbsds** [comment]
Followup: i added a symlink in `.local/share/pandoc/filters`:

```
$ pwd
/home/pbsds/.local/share/pandoc/filters
$ ls -l pandocker
lrwxrwxrwx 1 pbsds pbsds 42 nov.   3 14:38 pandocker -> /home/pbsds/.local/share/lua/5.3/pandocker
```

which allows me to load the `pandocker/svgbob.lua` filter without using a absolute path, but it fails to find its dependency `pandocker/utils.lua`:

```
Error running filter /home/pbsds/.local/share/pandoc/filters/pandocker/svgbob.lua:
...e/pbsds/.local/share/pandoc/filters/pandocker/svgbob.lua:11: module 'pandocker.utils' not found:
	pandocker.utilsis not one of pandoc's default packages
	no field package.preload['pandocker.utils']
	no file '/usr/share/lua/5.3/pandocker/utils.lua'
	no file '/usr/share/lua/5.3/pandocker/utils/init.lua'
	no file '/usr/lib/lua/5.3/pandocker/utils.lua'
	no file '/usr/lib/lua/5.3/pandocker/utils/init.lua'
	no file './pandocker/utils.lua'
	no file './pandocker/utils/init.lua'
	no file '/usr/lib/lua/5.3/pandocker/utils.so'
	no file '/usr/lib/lua/5.3/loadall.so'
	no file './pandocker/utils.so'
	no file '/usr/lib/lua/5.3/pandocker.so'
	no file '/usr/lib/lua/5.3/loadall.so'
	no file './pandocker.so'
```

**Comment by jgm** [comment]
I think this is just the default Lua search path, not something pandoc sets.
Can't you change it in the normal way by setting an environment variable?
