### ISSUE TITLE
Lua filters: Userdata pairs() include 'tag', nil values and functions

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#7661]
Note: This has been spawned from #7657, to which @tarleb commented:

> The pairs behavior is a bug, at least with regard to the inclusion of nil values. Having object methods in there was intentional, but I hadn't thought about pandoc when I wrote that code. Maybe this is a mistake, too?

----

I noticed that the attributes returned by pairs() include `tag`, several `nil` values (for attributes that don't necessarily apply to the element type) and various functions. It's easy to ignore them, but I wondered whether it was intentional.

```
Text
```
```
function Para(para)
    for n, v in pairs(para) do
        io.stderr:write(n .. ' ' .. tostring(v) .. '\n')
    end
end
```
```
% pandoc para.md -L pairs.lua
attr nil
bodies nil
caption nil
colspecs nil
content table: 0x7fd29960ad20
foot nil
format nil
head nil
level nil
listAttributes nil
tag Para
text nil
clone function: 0x7fd299413140
show function: 0x7fd2994132c0
<p>Text</p>
```

**Comment by tarleb** [comment]
I've pushed a fix that omits all absent (i.e., nil-valued) properties. Having the functions listed seems neutral or even beneficial, so I'd like to keep that. Unless, of course, this causes problems somehow.

**Comment by wlupton** [comment]
Sounds good. Thanks.
