### ISSUE TITLE
There is something strange with quotes (`("_") text ("-")`) conversion

### ISSUE THREAD

**Issue by N0rbert** [jgm/pandoc#7666]
**Explain the problem.**

Below is the minimal markdown document:

```
cat <<EOF > q.md
Fragment of the document with ("_") text ("-").
EOF
```
Really it is a fragment of real document with the same syntaxed paragraph.

I convert it to HTML using the following command:

```
pandoc q.md -o q.html
```

I get different results with different versions of pandoc:

* pandoc 1.19.2.4

      $ pandoc q.md -o q.html; cat q.html
      <p>Fragment of the document with (&quot;_&quot;) text (&quot;-&quot;).</p>

* pandoc 2.3.1

      $ pandoc q.md -o q.html; cat q.html
      <p>Fragment of the document with (&quot;_“) text (”-&quot;).</p>

* pandoc 2.11.4

      $ pandoc q.md -o q.html; cat q.html
      <p>Fragment of the document with ("_“) text (”-").</p>

* pandoc 2.14.0.3

      $ pandoc q.md -o q.html; cat q.html 
      <p>Fragment of the document with (“_“) text (”-“).</p>

* pandoc 2.16.1

      $ pandoc q.md -o q.html; cat q.html
      <p>Fragment of the document with (“_“) text (”-“).</p>

In the above output I find only one as correct one - pandoc 1.19.2.4. 

**Pandoc version?**
Many, see above. OS is Ubuntu MATE 18.04.6 LTS.

Notes:

1. I have discovered this while comparing resulting documents of RMarkdown/bookdown book with different pandoc versions; other options remain the same.
1. If needed, `hexdump -C q.md` is below:

       00000000  46 72 61 67 6d 65 6e 74  20 6f 66 20 74 68 65 20  |Fragment of the |
       00000010  64 6f 63 75 6d 65 6e 74  20 77 69 74 68 20 28 22  |document with ("|
       00000020  5f 22 29 20 74 65 78 74  20 28 22 2d 22 29 2e 0a  |_") text ("-")..|
       00000030

**Comment by jgm** [comment]
Why isn't the pandoc 2.16.1 output correct?  Using `--ascii` so we don't need to visually distinguish the open/close quotes:
```
% pandoc -t html --ascii
"_" "-"
<p>&#x201C;_&#x201D; &#x201C;-&#x201D;</p>
```
201C and 201D are the left and right double quote characters.

**Comment by jgm** [comment]
Btw, if you don't want "smart" quotes at all, but just want `&quot;`, then use `-f markdown-smart`.

**Comment by N0rbert** [comment]
Really I do not want to break my current Rmd workflow. Default pandoc call from RStudio is the following:

```
/usr/bin/pandoc +RTS -K512m -RTS q.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output q.html --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --wrap preserve --variable bs3=TRUE --standalone --section-divs --template /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --number-sections --variable theme=bootstrap --include-in-header /tmp/RtmpJ9JegN/rmarkdown-str501c300d7b73.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
```
I do not see *markdown-smart* here. Also I can't understand why we do not have for &qout; in the HTML output as it was with pandoc 1.19.2.4 .

Try to pass smart, breaks it:

```
---
site: bookdown::bookdown_site
output:
  bookdown::html_document2:
    pandoc_args: -f markdown-smart
---

Fragment of the document with ("_") text ("-").
```

```
processing file: q.Rmd
  |......................................................................| 100%
  ordinary text without R code


output file: q.knit.md

/usr/bin/pandoc +RTS -K512m -RTS q.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output q.html --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --wrap preserve '-f markdown-smart' --variable bs3=TRUE --standalone --section-divs --template /home/username/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --number-sections --variable theme=bootstrap --include-in-header /tmp/RtmpTjmrpm/rmarkdown-str528c75f68a24.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
Unknown input format  markdown
Error: pandoc document conversion failed with error 21
Execution halted
```

By the ways thanks for  your great project and current recommendation.

**Comment by jgm** [comment]
Not an rstudio or bookdown expert . But you could try with
```
output:
  bookdown::html_document2:
    pandoc_args: '-fmarkdown-smart'
```
(no space).  If that doesn't work, backslash-escaping any `"` character will cause it to be treated literally (and not as a curly quote).
As for the difference, `smart` became the default a long time back.
