### ISSUE TITLE
epub convertion help

### ISSUE THREAD

**Issue by jaan143** [jgm/pandoc#7681]
Dear All friends
i am converting markdown to epub file using pandoc but there is a lot of image file name bellow every image which i want to remove. image file name looks like this
image-BK7ECN82.jpg
image-DOTWYQYC.jpg
image-ZTFX0VRX.jpg

kindly help me to remove these image file names from epub file

2. can i select word and make auto bold that word ? e.g my file have a lot of chapters and i want that every chapter heading should be bold and little bigger font size than normal text

3. is it possible that my table of contents which is showing in start of my book make clickable ?

thank you

**Comment by mb21** [comment]
For questions, please use the [pandoc-discuss mailing list](https://groups.google.com/d/forum/pandoc-discuss) instead of this issue tracker. Thanks!

**Comment by jaan143** [comment]
@mb21  Dear 
i have posted my issue there sins 4 days but no one is reply me there

**Comment by jgm** [comment]
I suspect nobody replied because the question wasn't clear enough.
Why don't you post a sample of your markdown input on the mailing list, so we can see exactly what you're doing.
