### ISSUE TITLE
Link section-titles to the section level

### ISSUE THREAD

**Issue by Louson** [jgm/pandoc#7685]
Probably linked to #2144

Instead of a boolean, could we define a level for the beamer's variable *section-titles* ?

If 0, it would be equivalent to the present false
If -1, it would be equivalent to the present default true
If n, it would enable “title pages” for new sections till level n

If n is greater than the slide level, I guess it should be equivalent to -1

**Comment by mb21** [comment]
Perhaps you're looking for the[--slide-level option](https://pandoc.org/MANUAL.html#option--slide-level)?

**Comment by Louson** [comment]
No, it's independent.

Example: I have a slide level equal to 4 but I want title pages only up to level 2 headers.

Btw, somehow I created this issue without the tag enhancement. Can you update it ?

**Comment by tarleb** [comment]
@Louson could you add a little example input and the desired output? It's not entirely clear to me what the option should do.

**Comment by Louson** [comment]
Sure. Let's take the following example using slide-level=4:

``` markdown
# title

## subsection

### subsubsection 1

#### frame 1

Slide text 1

#### frame 2

Slide text 2

### subsubsection 2

#### frame 3

Slide text 3
```

With the option `section-titles`, I can only set if I want or not section titles. But I can't configure how deep this should be.

Suppose I want title slides for subsubsections. It would be nice if I can set section-titles=3.

**Comment by tarleb** [comment]
Thanks for the clarification. However, I'm still a bit fuzzy on the details. Would the `subsection` show at some point when setting `section-titles=3`, or just `subsubsection `? I'm trying to understand, as I think there might be other solutions to get the result you want. Due to the way variables and pandoc's templating language works, it would be difficult to control this via the value of a variable.

E.g., is this closer to what you need?

    pandoc --shift-heading-level-by=-1 --slide-level=3 ...

**Comment by Louson** [comment]
Indeed, I just understood this can be done by modifying the template where section-titles is defined. It's probably better to keep some flexibility.
Thanks for the clarifications
