### ISSUE TITLE
Windows "Path" environment variable incorrectly set to ";C:/Users/..." instead of "C:/Users/..." when there is no previous value to append to.

### ISSUE THREAD

**Issue by password123123123** [jgm/pandoc#7688]
**Explain the problem.**
Windows "Path" environment variable incorrectly set to ";C:/Users/..." instead of "C:/Users/..." when there is no previous value to append to. So you OS can't find pandoc binary. Removing semicolon from solves problem.

**Pandoc version?**
Win x64, latest pandoc

**Comment by jgm** [comment]
Where do you see pandoc setting the PATH environment variable?
I don't see any code that is doing this.

**Comment by mb21** [comment]
This may be a bug in a third-party script that installs pandoc on windows. Closing until we get more info.
