### ISSUE TITLE
.tex to .docx – issues with itemizing (enumerating)

### ISSUE THREAD

**Issue by ballII** [jgm/pandoc#7689]
**Explain the problem.**
.tex source code: https://www.overleaf.com/read/jgwnszzhftjc
pandoc's .docx output:
![image](https://user-images.githubusercontent.com/7100993/141661692-4df8a8c3-1194-4820-ab50-3f9821bf2072.png)
The .docx output has the sentence "extra line after equation" incorrectly itemized as number "2".

**Pandoc version?**
pandoc 2.16.1 on macOS 10.15.7

**Comment by jgm** [comment]
Input sufficient to reproduce with `pandoc -f latex -t docx`:
```
\begin{enumerate} 
\item test 
\[ \mathbf{A}=1 \] 
extra line after equation 
\end{enumerate} 
```

**Comment by jgm** [comment]
The function `fixDisplayMath` converts the paragraph containing display math to this:
```

[ BulletList
    [ [ Div
          ( "" , [ "math" ] , [] )
          [ Para [ Str "test" ]
          , Para [ Math DisplayMath "\\mathbf{A}=1" ]
          , Para [ Str "extra line after equation" ]
          ]
      ]
    ]
]
```
I note that pandoc does not create the extra list item if the Div is removed:
```
[ BulletList
    [ [ Para [ Str "test" ]
      , Para [ Math DisplayMath "\\mathbf{A}=1" ]
      , Para [ Str "extra line after equation" ]
      ]
    ]
]
```

**Comment by jgm** [comment]
This shows that the underlying problem is not about math, specifically, but about how style information for list paragraphs is propagated inside Divs.
```
% pandoc -f native -o my.docx
[ BulletList
    [ [ Div
          ( "" , [] , [] ) [ Para [ Str "one" ] , Para [ Str "two" ] ]
      ]
    ]
]
```
wrongly gives two list items.

**Comment by jgm** [comment]
The underlying problem is at l. 982 of the docx writer:
```hs
  first'' <- withNumId numid $ blockToOpenXML opts first'
```
If `first'` is a Div containing multiple blocks, this leads to all of them getting the same numid, which makes them separate list items.  (A different numid is needed for continuation paragraphs.)
