### ISSUE TITLE
Typo in extension name in documentation

### ISSUE THREAD

**Issue by Natsec** [jgm/pandoc#7690]
Using pandoc 2.16.1 on Windows, after reading the user guide, when launching pandoc with the `--from markdown+short_subsuperscript` option, I got the following error message :
```
unexpected end of input
Unknown extension: short_subsuperscript
```

Turns out there is a typo in the documentation, the source code refer to it by `short_subsuperscripts` (with a `s`), but the `man/pandoc.1` and `MANUAL.txt` files use `short_subsuperscript` to refer to it.

A simple search `subsuperscript([^s])` and replace with `subsuperscripts$1` in vscode should do the trick.

**Comment by jgm** [comment]
Thanks!

**Comment by Natsec** [comment]
Hello,
`man/pandoc.1` should also be modified.
(I don't know if I can do the pull requests myself because I already have a private repo named pandoc).

**Comment by tarleb** [comment]
Thanks for noticing. The man page is regenerated from the MANUAL.txt before each release, but not between releases. No need to update it now.

**Comment by Natsec** [comment]
All right :)
