### ISSUE TITLE
Support `\left<\right>` in latex inputs

### ISSUE THREAD

**Issue by anntzer** [jgm/pandoc#7694]
**Describe your proposed improvement and the problem it solves.**

LaTeX allows one to write `\left<\right>` as shorter aliases for `\left\langle\right\langle`, additionally not requiring spaces after `<` and `>` (see e.g. https://tex.stackexchange.com/questions/47078/difference-between-langle-and/47085#47085).  However, pandoc (as of 2.16) does not recognize the short forms.  It would be nice if it did.

**Describe alternatives you've considered.**

Typing `\langle\rangle` is slightly more tedious, although search/replace is not too bad.

**Comment by jgm** [comment]
This is taken care of by https://github.com/jgm/texmath/pull/182
The next release of pandoc will compile against a new version of texmath that includes this change.

**Comment by jgm** [comment]
Or you can try a nightly tomorrow.
