### ISSUE TITLE
MediaWiki writer: anchors of references should be created

### ISSUE THREAD

**Issue by wp-seth** [jgm/pandoc#7697]
### input file
subpage1.rst
```rst
.. _refsubpage1:

heading
-------

ref to top of this section: `refsubpage1`_.
```

### command
`pandoc -f rst -t mediawiki subpage1.rst`
### output
```
= heading =

ref to top of this section: [[#refsubpage1|refsubpage1]].
```
### expected output
```
<span id="refsubpage1"></span>
= heading =

ref to top of this section: [[#refsubpage1|refsubpage1]].
```

or even

```
= heading =

ref to top of this section: [[#heading|refsubpage1]].
```
because after the anchor definition there's a heading (which includes an anchor by default).

### version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5

and (currently) 2.14.2 at [pandoc.com/try](https://pandoc.org/try/?text=..+_refsubpage1%3A%0A%0Aheading%0A-------%0A%0Aref+to+top+of+this+section%3A+%60refsubpage1%60_.%0A&from=rst&to=mediawiki&standalone=0)

**Comment by jgm** [comment]
Turns out this is an issue in the RST reader, not the MediaWiki writer.
You can verify this by doing `-f rst -t native`; no trace of the anchor can be found.

**Comment by jgm** [comment]
I take that back!  The RST reader actually adds `refsubpage1` as an identifier of the header, and links to that.

**Comment by jgm** [comment]
So, here's the underlying issue:
```
% pandoc -f native -t mediawiki
Header 1 ( "refsubpage1" , [] , [] ) [ Str "heading" ]
^D
= heading =
```
The identifier is lost without a trace.
