### ISSUE TITLE
RST reader: links from included files to references of other included files

### ISSUE THREAD

**Issue by wp-seth** [jgm/pandoc#7698]
(i searched the issues, the mailing list and the change log, but could not see the problem being discussed or fixed.)

sorry in advance, if that is no bug, but just wrong usage.

## input files
given three files
1. test.rst
```rst
.. include:: subpage1.rst
.. include:: subpage2.rst
```

2. subpage1.rst
```rst
.. _refsubpage1:

heading
-------

ref to top of this section: `refsubpage1`_.
```

3. subpage2.rst
```rst
ref to other subpage: `refsubpage1`_.
```

## using command

`pandoc -f rst -t mediawiki test.rst`

## result

```
[WARNING] Reference not found for 'refsubpage1' at subpage1.rst line 6 column 43
[WARNING] Reference not found for 'refsubpage1' at subpage2.rst line 1 column 37
= heading =

ref to top of this section: [[|refsubpage1]].

ref to other subpage: [[|refsubpage1]].
```
## expected result
```wikitext
<span id="refsubpage1"></span>
= heading =

ref to top of this section: [[#refsubpage1|refsubpage1]].

ref to other subpage: [[#refsubpage1|refsubpage1]].
```
or even

```wikitext
= heading =

ref to top of this section: [[#heading|refsubpage1]].

ref to other subpage: [[#heading|refsubpage1]].
```
because after the anchor definition there's a heading (which includes an anchor by default).

see #7697 for this additional bug in MediaWiki writer.

## pandoc version
```
$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
[...]
```
(debian 11)

**Comment by jgm** [comment]
I believe this is the same issue as #4160.

To reiterate what I said there:

> The RST parser does a two-step parse, grabbing references first and
then parsing.  Processing of include directives takes place
in the second step, so the references defined in other
files aren't available.  This isn't a good design; we should
really change the reader to use the F monad, as the Markdown
reader does, and do a single pass.  This would be a bit of
work.

**Comment by mb21** [comment]
Closing in favour of #4160
