### ISSUE TITLE
Add pandoc.text() to Lua API?

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#7709]
Could we export pandoc.text, wrapping Text.Pandoc.Builder.text?
(A simple way to convert a string to a sequence of Str and Space elements.)
@tarleb

**Comment by tarleb** [comment]
Sure! We'd probably need a different name though, as `pandoc.text` is already populated by the `text` module. Maybe `pandoc.utils.text` would do?

We could change the way strings are handled in situations where they are passed to functions that expect a list of inline values. I believe filter breakage would be minimal. The `pandoc.utils.text` function would then be equivalent to `local text = function(s) return pandoc.Emph(s).content end`.

Currently a plain string `s` is treated as `{pandoc.Str(s)}` when passed to a function that expects inlines. It should have been designed differently right from the start, but the old architecture had made that difficult.

**Comment by jgm** [comment]
Actually, I love the idea of using the text constructor for plain strings; that would be by far the most convenient thing.
Is that impossible?
