### ISSUE TITLE
 Pipe tables with blanks does not break lines 

### ISSUE THREAD

**Issue by Louson** [jgm/pandoc#7713]
If I consider the table :

```
| aaaaaaaaaaaa | bbbbb | ccccccccccc                                                       |
| ---          | ---   | ---                                                               |
|              |       | cccccccccc cccccccccc cccccccccc cccccccccc cccccccccc cccccccccc |
```

The resulted table won't break the long line because the total line's width (65) does not exceed the column width (72).

Is is not exactly a bug because that is what the manual says:
> if no lines are wider than column width, then cell contents will not be wrapped, and the cells will be sized to their contents

However, the table width exceeds the frame size. Do you think it is possible to check the sum of each column's maximum width (here 12+5+65 = 82) ?

**Comment by jgm** [comment]
That makes sense.
