### ISSUE TITLE
Some valid attributes are dropped from HTML to Markdown conversion 

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#7714]
This happens with links for example where `target` is a valid attributes. (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)

```r
> echo "<a href='https://example.com' target='_blank'>https://example.com<a>" | pandoc --to markdown --from html
<https://example.com>
```

```
> echo "<a href='https://example.com' target='_blank'>Example site<a>" | pandoc --to markdown --from html
[Example site](https://example.com)
```

It is not lost when using Markdown to Markdown for example (probably thanks to https://github.com/jgm/pandoc/issues/7692)

````
echo "[https://example.com](https://example.com){target='_blank'}" | pandoc --to markdown
[https://example.com](https://example.com){target="_blank"}
````

This was tested with last pandoc 2.16.2 and last nigttly build (from 79e6f8db13ef8f0db6da8fe4e17b7626fe6ef3e9)

**Comment by cderv** [comment]
Oh it is probably this same issue : https://github.com/jgm/pandoc/issues/6970

Sorry for the duplicate if it is.

**Comment by jgm** [comment]
Yes it's a dup.
