### ISSUE TITLE
`raw_attribute` not working with command line / default file `header-includes`.

### ISSUE THREAD

**Issue by GregorySchwartz** [jgm/pandoc#7717]
**Explain the problem.**
```
printf "# Test\nTesting" > test.md
pandoc --variable "header-includes":"\renewcommand{\familydefault}{\sfdefault}" -o test.pdf test.md  # Works
pandoc --variable "header-includes":"`\renewcommand{\familydefault}{\sfdefault}`{=latex}" -o test.pdf test.md  # Does not work
```

The `raw_attribute` feature does not appear to work on the command line, as I would expect the second and third lines of the above code to have the same output. Furthermore, this extends to the `--defaults` file as well -- having the

```
variables:
  header-includes: 
    - |
      ```{=latex}
      latex-specific-lines
      ``` 
```

does not work as intended, as that entire header will be included in, for instance, plain text output where if that `header-includes` was in the file metadata yaml instead, it would behave as expected.

**Pandoc version?**
`pandoc 2.14.0.3` on `NixOS`.

**Comment by jgm** [comment]
`--variable` just sets a template variable, and resolution of the template occurs after parsing, so the variable is treated as a plain literal string, not parsed as Markdown.  (Similarly, values from `--metadata` are treated as plain strings.)

The same applies when you set the variable in a defaults file.

So this is working as advertised; you just had a misconception about how it should work.

**Comment by GregorySchwartz** [comment]
Ah, so headers must be in a separate file as in `include-in-header` only then as a "template", or in the metadata yaml block.
