### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#7721]
Unclear why, but 3692a1d..c5287e9 broke my PKGBUILD for `pandoc`.
Bumping the lower bound in `pandoc.cabal` for `pandoc-lua-marshal` to `0.1.0.1`
fixed it, though, so I suspect the CI and my PKGBUILD test different workflows.

My PKGBUILD essentially runs
```bash
stack setup
stack build \
    --install-ghc \
    --ghc-options='-fdiagnostics-color=always' \
    --flag 'pandoc:embed_data_files' \
    --fast
```
in a sandbox. Unclear why it ignores `stack.yaml`, which was correctly updated
in c5287e9, but at least it caught the missing version bump.

Also, for future bisectability, would've been better to reorder those commits so the version bump in c5287e9 occured first, before the commits assuming that dependency.

**Comment by jgm** [comment]
I've added the lower bound in pandoc.cabal, which you said fixed the issue. Let us know if it isn't fixed.  I have no idea why your build ignores stack.yaml, though.

**Comment by hseg** [comment]
OK, thanks!
Will be on the road until Thursday, probably won't be able to test until then

**Comment by hseg** [comment]
OK, can confirm this fixed it.
