### ISSUE TITLE
Docx conversion to markdown adds double line breaks for each new line / paragraph

### ISSUE THREAD

**Issue by GitMurf** [jgm/pandoc#7725]
I feel like this is a simple issue but have spent days trying to figure this out. I have a word doc like below with simply multiple lines and I convert it to markdown and it ends up adding double line breaks. I want my markdown file to look just like my word doc from a line break perspective. Is this possible?

Here is the command I am running: `pandoc.exe -s test.docx -t markdown -o "new1.md" --markdown-headings=atx`

![image](https://user-images.githubusercontent.com/64155612/144352825-1a2b9780-576e-4457-8936-132b7b554368.png)

**Comment by GitMurf** [comment]
Here is a good example where the first two lines do not have an empty line break between them and I'd like the markdown result to also not have an empty line break.

Whereas the second one has an empty line break in the word doc and then correctly has one in the markdown file. The markdown results of both sets of lines has the same result with an extra line break between each line, but I do NOT want the extra line break in the first scenario.

![image](https://user-images.githubusercontent.com/64155612/144354942-6b7b002a-72ee-46ef-bcd3-0d4d639db1a6.png)

**Comment by jgm** [comment]
I assume there are paragraph breaks between these lines.  (If you "show formatting" on word, you should see a paragraph symbol.)

In Markdown, paragraph breaks are indicated by blank lines.  So there is no way to preserve the semantics without the blank lines.

**Comment by GitMurf** [comment]
@jgm thanks for the quick response! Yes you are correct they are all paragraph breaks. See below screenshot with the symbols on. But ultimately I guess my question and what I want is for each paragraph break to be treated like a single line break. And then if I have a double paragraph break like my second set of lines with an empty line in word, then I want that reflectected in markdown.

Is there any way to essentially turn Paragraph breaks into just line breaks? I spent hours trying to figure out options with writing filters and it looks like the stdinput coming from the docx is already converted to just paragraphs for all of these and I have no way of knowing whether there were two paragraphs in a row or whether just a single paragarph (no double Enter pressed). Does this mean a Filter won't help because pandoc has already translated from work to your pandoc AST by the time the Filter applies to it?

Lastly is this something that could be handled with LUA / a custom reader? Is there a way to tap into the default DOCX reader so that I can simply turn all Paragraph breaks into regular line breaks and respect whether the word doc has multiple paragaph breaks in a row and turn those each into regular line breaks? It is SUPER important for the way my Word docs are setup and the way I do my markdown to be able to keep these paragraph breaks honored like regular line breaks.

Thanks a ton!!

![image](https://user-images.githubusercontent.com/64155612/144472915-5954b856-3812-41c9-b0b3-da08f6d0b899.png)

**Comment by GitMurf** [comment]
To confirm this is what I would hope to see as output in my markdown output file:

```
And then again here with
More below it

And then again here with

More below it
```

**Comment by GitMurf** [comment]
I guess one question I have that would really help is I have tried all of the following to no success... are any of these viable options to turn Word doc paragraph breaks into single line breaks?

1) I have tried using a DOCX reference document to figure out how to make paragraph breaks be treated as regular line breaks but doesn't seem like reference docs can we used when converting FROM docx and only applies when converting TO docx?

2) I have tried templates but that doesn't do the trick because the Docx is already translated to Pandoc AST which means the paragraph breaks are already "converted" and have lost the relationship to whether there are two or more Paragraph breaks in a row. So at that point I cannot convert myself paragraphs to regular line breaks because everything will be treated as just a simple single paragraph break and so won't know different between true paragph where I hit enter twice in Word doc, versus a multi line block of text where I just have a single Enter/new line key between each line.

3) I tried filters but think the same problem exists as item 2 above where the Docx is already converted to AST which means the line breaks / paragraph breaks have not been preserved as it doesn't show an empty paragraph went there were multiple paragraph breaks (multiple Enter keys in a row).

4) Do I need to create a custom Reader with LUA to do my own interpretation of the Word doc? https://pandoc.org/custom-readers.html ... I assume this would be a nightmare if not impossible for me to do. The only option I could see if being able to start from or tap into the Docx reader and just add my own customization to preserve all the Paragraph Breaks and turn them into line breaks and preserve if I have 4 paragraph breaks in a row for example.

I know this is a lot but hopefully I am conveying my issues / goals with what I am trying to do. At the end of the day I just want the following for example from word to be translated into a text file (markdown) with all the line breaks respected. I understand this isn't "true" markdown because you can't have multiple empty line breaks but I have reasons to where I need to preserve all the empty white space and line breaks.

![image](https://user-images.githubusercontent.com/64155612/144477232-87bf7438-1736-4af6-b54d-ec87ffde7e7b.png)

And want/neeed it to end up in markdown / plain text like this:

```
Here is a line
Here is another line immediately after it (multi line block)

Here is what normally is considered a new paragraph.





Here are several new line breaks that I want to preserve above.
```

**Comment by GitMurf** [comment]
@jgm curious if you can point me to the location of the code base where the DOCX reader / translation is?

At a high level, does Pandoc just extract the docx and then more or less parse the `document.xml` when converting it to Pandoc AST?

![image](https://user-images.githubusercontent.com/64155612/144490026-02aeba01-c115-45b4-9fd0-836849e5912d.png)

**Comment by GitMurf** [comment]
Ok the simpler "question" is whether there is anyway I can do similar to what find and replace in word can do with replacing Paragraph breaks `^p` with line breaks `^l` before Pandoc does its conversion / translation of the Docx to its AST?

![image](https://user-images.githubusercontent.com/64155612/144495859-905d1422-a929-46d5-b99f-d4776d98b86e.png)

**Comment by GitMurf** [comment]
Ok ultimately I think I have figured out how to contextually and visually explain exactly what I want and need. I want Pandoc to take a Word docx like the first screenshot below and with the Reader BEFORE it does any of its translations to AST I'd like it to replace all the Paragraph breaks `^p` with Line breaks `^l` one for one so that it looks like the second screenshot which then at the end of the day should end up like the third screenshot once Pandoc converts it to Markdown.

![image](https://user-images.githubusercontent.com/64155612/144496690-f613972a-ca98-4279-9d0d-be26070a73cf.png)

![image](https://user-images.githubusercontent.com/64155612/144496701-a26c8f4c-7a7f-4479-b81c-f31ac189905c.png)

![image](https://user-images.githubusercontent.com/64155612/144497049-f41c7bd3-6822-4215-8dd1-ec4fdea6b44b.png)

**Comment by jgm** [comment]
Now you're talking about a docx -> docx preprocessing step. This is out of scope for pandoc.
Pandoc is doing its job properly with this input.

**Comment by sneko** [comment]
In my case I was fine with modifying the source document, so just for other people looking for information:

In LibreOffice (probably same for others), using `Enter` will be a new paragraph whereas `Shift + Enter` will be in a new line in the same paragraph.

Once you know that, everything's good 👍

**Comment by aaronpenne** [comment]
fwiw on mac/linux I get around this by piping the pandoc output into grep in one shot like:
`pandoc -f docx -t input.docx --wrap=none --markdown-headings=atx | grep -v '^$' > output.md`
