### ISSUE TITLE
ipynb reader/writer preserves id

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#7728]
MWE:

Input:

```json
# demo.ipynb 
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0cdcfa5f-2369-40be-bebb-c68668370c54",
   "metadata": {},
   "source": [
    "demo"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "all39-defaults",
   "language": "python",
   "name": "all39-defaults"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

run

```bash
pandoc -s demo.ipynb --to ipynb
```

output:

```json
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "demo"
   ]
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "language_info": {
   "name": "python",
   "nbconvert_exporter": "python",
   "file_extension": ".py",
   "pygments_lexer": "ipython3",
   "mimetype": "text/x-python",
   "version": "3.9.5",
   "codemirror_mode": {
    "name": "ipython",
    "version": "3"
   }
  },
  "kernelspec": {
   "name": "all39-defaults",
   "display_name": "all39-defaults",
   "language": "python"
  }
 }
}
```

Note that `"id": "0cdcfa5f-2369-40be-bebb-c68668370c54"` disappears.

This id is added somewhat recently. Without this info, a ipynb written by pandoc and later run by other jupyter ecosystem app would recreate a different id. (later versions of apps in the jupyter ecosystem would preserve this id rather than generating a new one every rerun.) Hence the gif diff would be quite noisy.

So the feature request is to preserve this id in the ipynb reader and writer.

Another minor point is the `"version": 3` becomes `"version": "3"`, but it hasn't cause any problem to me.

**Comment by jgm** [comment]
Is this addition of `"id"` part of a new version of the format?  It still says "version": 3.  Was Nb3 silently changed, or was `"id"` there all along and we didn't support it?

**Comment by ickc** [comment]
This issue has more info on it: https://github.com/jupyterlab/jupyterlab/issues/9729

In particular, it references [this proposal ](https://jupyter.org/enhancement-proposals/62-cell-id/cell-id.html).

Those issues mentioned the feature is added in format 4.5, corresponding to the following from above:

```json
 "nbformat": 4,
 "nbformat_minor": 5
```

**Comment by jgm** [comment]
> Cell ids

> Since the 4.5 schema release, all cells have an id field which must be a string of length 1-64 with alphanumeric, -, and _ as legal characters to use. These ids must be unique to any given Notebook following the nbformat spec.

```
"id": {
    "description": "A str field representing the identifier of this particular cell.",
    "type": "string",
    "pattern": "^[a-zA-Z0-9-_]+$",
    "minLength": 1,
    "maxLength": 64
}
```

**Comment by jgm** [comment]
First step will be to support this in jgm/ipynb for Nb4.
I think maybe the most sensible way to do this is to add a field to the Cell record
```
  cellId :: Maybe UUID
```
So if the "id" field is missing we'll get a Nothing.

We could have pandoc create UUIDs for cells when producing ipynb documents, if they are not explicitly specified.

**Comment by ickc** [comment]
Note to self:



> > Cell ids
> 
> > Since the 4.5 schema release, all cells have an id field which must be a string of length 1-64 with alphanumeric, -, and _ as legal characters to use. These ids must be unique to any given Notebook following the nbformat spec.
> 
> ```
> "id": {
>     "description": "A str field representing the identifier of this particular cell.",
>     "type": "string",
>     "pattern": "^[a-zA-Z0-9-_]+$",
>     "minLength": 1,
>     "maxLength": 64
> }
> ```

is from <https://nbformat.readthedocs.io/en/latest/format_description.html#cell-ids>

Also I'm confused between the nbformat version and schema version. Note that nbformat doesn't have version 4.5 and latest version is 5.1, but the latest schema is version 4.5, which can be found in <https://github.com/jupyter/nbformat/tree/master/nbformat/v4>.
