### ISSUE TITLE
Apostrophe in Headings Escaped as `[cq]` in PDF Table of Contents

### ISSUE THREAD

**Issue by matttproud** [jgm/pandoc#7731]
**Explain the problem.**

In the generated table of contents for PDF documents using the `pdfroff` engine, an apostrophe (`'`) is rendered as the ROFF escaping of `[cq]`.  To reproduce:

```shell
$ cat defect.md
# Introduction
This is an introduction.

## The City's Context in My Life

It was very important.

$ pandoc --pdf-engine pdfroff defect.md -o defect.pdf
```

This is rendered as such in `evince`:

![image](https://user-images.githubusercontent.com/46149/144833089-afe9a7c7-a4bd-435e-9067-d8c01499599b.png)

**Pandoc version?**
```shell
$ pandoc -v
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/mtp/.local/share/pandoc or /home/mtp/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Debian 11.1.

**Comment by jgm** [comment]
Confirmed with latest pandoc.

**Comment by jgm** [comment]
The ms writer produces:
```
.SH 2
The City\[cq]s Context in My Life
.pdfhref O 2 "The City\[cq]s Context in My Life"
.pdfhref M "the-citys-context-in-my-life"
```
The second line `.pdfhref O` should be changed so that no roff syntax (such as `[cq]`) is used.
