### ISSUE TITLE
ipynb writer: ordering sort by keys

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#7733]
Currently, the ipynb writer writes dictionary keys in arbitrary order (which also seems to be platform dependent), which has these implications:

- using old style testing via `Old.hs` may fails depending on platforms, see #7563, in particular in this build: https://github.com/jgm/pandoc/runs/4438646583
- has cosmetic issues when round-trip from ipynb to ipynb, where diff are generated when the keys are shuffled. (This is not important though.)

Also, note that nbformat while does not require keys to be sorted, their reference implementation does sort the keys:

https://github.com/jupyter/nbformat/blob/adac744f7f2c81b96f9baa225fdf323e44046eac/nbformat/v4/nbjson.py#L48-L56

Edit: while sort by keys would be nice, perhaps a deterministic ordering suffices.

**Comment by jgm** [comment]
https://stackoverflow.com/questions/37865388/haskell-generating-json-with-aeson-gives-incorrect-order-of-fields
is useful here

**Comment by jgm** [comment]
I'm hoping this issue is handled by commit 51142c6803cab7486dbe962f274174d246e571aa
but this could use testing.

**Comment by ickc** [comment]
test build at https://github.com/jgm/pandoc/runs/4450661407?check_suite_focus=true shows that the key ordering is still depending on platform/compiler.

**Comment by ickc** [comment]
This is solved by

- 8215ca0
- https://github.com/jgm/ipynb/commit/00246af10885c2ad4413ace4f69a7e6c88297a08
- 9cbea69

As demonstrated in build https://github.com/jgm/pandoc/runs/4477648113
