### ISSUE TITLE
Regression with markdown images with alt text `_`

### ISSUE THREAD

**Issue by rg-software** [jgm/pandoc#7738]
I am using pandoc to generate a self-contained HTML page from a source markdown like this:

```shell
pandoc -f markdown -t html myfile.md --self-contained --css=mycss.css -o myfile.html 
```

It worked perfectly on pandoc versions up to 2.16. Updating to 2.16.2 broke HTML generation. This new version simply leaves markdown placeholders like `![_](myimage.png)` without any changes.

**Comment by jgm** [comment]
This has nothing to do with `--self-contained`.  The issue is with images with alt text `_`:
```
% pandoc
![_](url.png)
<p>![_](url.png)</p>
```

**Comment by jgm** [comment]
If I had to guess, I'd guess it has to do with this item in pandoc 2.16.2 changelog:

>  * Markdown reader: Improve `inlinesInBalancedBrackets`.

**Comment by jgm** [comment]
Yes, pinned it down with bisection to commit fa83246d7de8527bbf59dfac9636a42ede185194

**Comment by jgm** [comment]
I'll just revert that commit.
