### ISSUE TITLE
Enhance styles in reference.docx

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#774]
It would be good to define styles for
- Code blocks (note:  the `SourceCode` style is used for code blocks, but the style is not defined in `styles.xml`.  Also, the `VerbatimChar` font style is used; perhaps better to define the font in the `SourceCode` style.
- Table headers
- Table body

**Comment by ryangray** [comment]
I think it would also be useful to give figure-style image paragraphs their own styles (the captions already have their own style). This way, they could be defined in the reference.docx as centered, for example, as well as setting the style to "keep with next" so the caption stays with it.

**Comment by mb21** [comment]
Not sure if this is resolved now. Seems like we have more things now in https://github.com/jgm/pandoc/blob/master/data/docx/word/styles.xml

**Comment by jgm** [comment]
Yes, this is an ancient issue. Let's close this and if anything is still needed, it can come up again.
