### ISSUE TITLE
Docx writer default table style, not editable.

### ISSUE THREAD

**Issue by RoanB** [jgm/pandoc#7746]
Hey,  

From what I understood, the docx writer for pandoc uses the table style: 'table1' from the reference file.
In word, it seems that this name is now reserved and we can not update this style, so with recent versions of word we can not update the table style that pandoc uses. I found a "solution" by editing the xml of the reference file, but this is not ideal and on saving a generated word document I now get errors on my tables. 

Would it be possible to change the default table style the docx writer uses?

**Comment by jgm** [comment]
Pandoc uses the style "Table".

**Comment by tarleb** [comment]
It appears that this was resolved. Closing.
