### ISSUE TITLE
Table in the markdown file converted by pandoc

### ISSUE THREAD

**Issue by starsareintherose** [jgm/pandoc#7755]
**Explain the problem.**
this table format is not recognized
```
  -------------- -------------
   hh             single
  h              short
  l              long
  ll             long long
  L              long double
  -------------- -------------
```
**Pandoc version?**

```
pandoc -v
pandoc 2.14.1
Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.11,
citeproc 0.4.1, ipynb 0.1.0.1
```

**Comment by tarleb** [comment]
Please provide the full command you are using. Running `pandoc -f markdown` on the above snippet yields the correct output for me.

**Comment by starsareintherose** [comment]
`pandoc -f makrdown -t markdown -o markdown.md markdown.md`

**Comment by starsareintherose** [comment]
the input markdown should be like this
```
 | 
-- | --
hh | 单个字节
h | short
l | long
ll | long long
L | long double
```

**Comment by tarleb** [comment]
I'm not sure I understand. The Markdown in the last comment works as well when used as input.

I assume the problem is that the table shown in the first comment is not recognized by some Markdown implementations. You may want to try GitHub Flavored Markdown (`--from=gfm`), which produces

```
|     |             |
|-----|-------------|
| hh  | 单个字节    |
| h   | short       |
| l   | long        |
| ll  | long long   |
| L   | long double |
```

Or did I misunderstand the issue?

**Comment by starsareintherose** [comment]
I try to use `pandoc -f makrdown -t markdown --from=gfm -o IO.md IO.md`
but it produce table like this
```

  ------ --------------
  flag   含义
  \*     跳过
  数字   最大字符数
  hh     char
  h      short
  l      long, double
  ll     long long
  L      long double
  ------ --------------
```
instead of what you show

**Comment by starsareintherose** [comment]
Also html convert to markdown shown similar situlation
```
pandoc -f html -t markdown -o IO.md IO.html 
```
the IO.html is IO.html.md attached, because HTML are not allowed to upload.
[IO.html.md](https://github.com/jgm/pandoc/files/7738151/IO.html.md)
[IO.md](https://github.com/jgm/pandoc/files/7738152/IO.md)

**Comment by jgm** [comment]
Those are "simple tables" (see the manual).
If you want pipe tables, use `-t gfm` or `-t markdown-simple_tables-grid_tables-multiline_tables`
