### ISSUE TITLE
convert html to markdown , illegal tag in the table.

### ISSUE THREAD

**Issue by ChitaGideon** [jgm/pandoc#7759]
**Explain the problem.**

`pandoc --from html --to gfm`

```
<table>

	<tr>
		<td><span>1</span></td>
		<td>
			<p><span>3</span></p>
			<p><span>4</span></p>
			<p><span>5</span></p>
		</td>
	</tr>
</table>
```

[padoc try example](https://pandoc.org/try/?text=%3Ctable%3E%0A%0A%09%3Ctr%3E%0A%09%09%3Ctd%3E%3Cspan%3E1%3C%2Fspan%3E%3C%2Ftd%3E%0A%09%09%3Ctd%3E%0A%09%09%09%3Cp%3E%3Cspan%3E3%3C%2Fspan%3E%3C%2Fp%3E%0A%09%09%09%3Cp%3E%3Cspan%3E4%3C%2Fspan%3E%3C%2Fp%3E%0A%09%09%09%3Cp%3E%3Cspan%3E5%3C%2Fspan%3E%3C%2Fp%3E%0A%09%09%09%3Cbr%3E%0A%09%09%3C%2Ftd%3E%0A%09%3C%2Ftr%3E%0A%0A%0A%3C%2Ftable%3E&from=html&to=gfm&standalone=0)

it seems that `p`tag in the `tr` ,that make some trouble.

tag `p` is illegal here, and I expect that ignoring the tag `p` could be better than the whole table ？

**Pandoc version?**
```
pandoc 2.16.2
Compiled with pandoc-types 1.22.1, texmath 0.12.3.2, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2

```

**Comment by jgm** [comment]
The issue here is that gfm only allows pipe tables, and these can't take multiple paragraphs in a cell (no line breaks allowed).  Hence we fall back to an HTML table, which is the only way to represent this in gfm.
