### ISSUE TITLE
Nested Markdown lists not converting to Latex properly

### ISSUE THREAD

**Issue by Zuline** [jgm/pandoc#776]
The following code (Pandoc 1.9.4.2):

```
1. **Focus**

    - **Review** your Master List

    - **Prepare** for any meetings

    - **Populate your Daily List** with the priorities for today

1. **Do** your tasks

1. **Update your Inbox** as tasks come in

1. **End of Day Review**
```

Should convert to a nicely nested list. It does in other conversions. However in converting to Latex it converts to this:

```
\begin{enumerate}[1.]
\item
 \textbf{Focus}
  \begin{itemize}
  \item
    \textbf{Review} your Master List
  \item
    \textbf{Prepare} for any meetings
  \item
     \textbf{Populate your Daily List} with the priorities for today
  \end{itemize}
\item
  \textbf{Do} your tasks
\item
  \textbf{Update your Inbox} as tasks come in
\item
  \textbf{End of Day Review}
\end{enumerate}
```

That in turn generates the following kind of errors. This one for the third line of that code:

```
l.34   \textbf
          {Focus}

 ./testapa6.tex:37: LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
```

That in turn generates this output which of course is not what was desired by the Markdown.

![Untitled](https://f.cloud.github.com/assets/3588284/219926/6b251ebc-854e-11e2-9b7d-eca534ae10cf.png)

Am I asking too much or is this an issue?

This issue is fixed in 1.10.1 for .docx and is much improved in Latex however the nested list items are not nested although the numbering is fixed and the errors don't throw.

Close it?

**Comment by MikeRussellMcK** [comment]
Zuline, I'm currently having the same problem - did you ever find a solution?
