### ISSUE TITLE
PDF conversion doesn't work on Windows

### ISSUE THREAD

**Issue by anta40** [jgm/pandoc#777]
I'm using 32-bit Windows 7 Pro (pandoc 1.10.1 and texlive 2012 already installed in available in PATH).

This is the directory used for testing purpose:
C:\Users\CSL-NB-064\Desktop\testing\

First I'd like to convert markdown to PDF:
pandoc README -o README.pdf

Here's the output:
C:\Users\CSL-NB-064\Desktop\testing>pandoc README -o README.pdf
pandoc: Error producing PDF from TeX source.
! I can't find file `C:/Users/CSL-NB'.
<to be read again>
                   \protect
<_> C:/Users/CSL-NB~
                    1/AppData/Local/Temp/tex2pdf24728/input.tex
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<to be read again>
                   \protect
<_> C:/Users/CSL-NB~
                    1/AppData/Local/Temp/tex2pdf24728/input.tex
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on C:\Users\CSL-NB~1\AppData\Local\Temp\tex2pdf24728/texput.
log.

And later I'd like to create a Beamer slide show:
pandoc -t beamer SLIDES -o SLIDES.pdf

And this is the output:
pandoc: Error producing PDF from TeX source.
! I can't find file `C:/Users/CSL-NB'.
<to be read again>
                   \protect
<_> C:/Users/CSL-NB~
                    1/AppData/Local/Temp/tex2pdf29912/input.tex
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<to be read again>
                   \protect
<_> C:/Users/CSL-NB~
                    1/AppData/Local/Temp/tex2pdf29912/input.tex
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on C:\Users\CSL-NB~1\AppData\Local\Temp\tex2pdf29912/texput.
log.

This message: "I can't find file `C:/Users/CSL-NB" suggests that pandoc doesn't read it properly. I assume this is a bug.

**Comment by nealkruis** [comment]
I can reproduce this on a 64-bit windows 7 machine. Everything was working with xelatex version 2.4, but when I updated to 2.6 I got the same error:

    pandoc: Error producing PDF from TeX source.
    ! I can't find file `C:/Users/NATHAN'.
    <to be read again>
                       \protect
    <*> C:/Users/NATHAN~
                        1/AppData/Local/Temp/tex2pdf3312/input.tex
    Please type another input file name
    ! Emergency stop.
    <to be read again>
                       \protect
    <*> C:/Users/NATHAN~
                        1/AppData/Local/Temp/tex2pdf3312/input.tex
    No pages of output.
    Transcript written on C:/Users/NATHAN~1/AppData/Local/Temp/tex2pdf3312/texput.l
    og.

**Comment by mb21** [comment]
Closing this really old issue. Please reopen if you can reproduce with the newest pandoc.
