### ISSUE TITLE
Not all images exported when using "--extract-media" with some .docx files

### ISSUE THREAD

**Issue by maxklebron** [jgm/pandoc#7786]
**Issue Description**
When testing v2.16.2 of pandoc on Windows I observed some .docx files do not have all of their images exported when using the `--extract-media` command line argument (when converting to the `.md` format). Instead a subset of images are exported. For example, in a simple test .docx file (attached to this issue) only 1 image is exported, but there are several in the document.

**Details to recreate**
This can be recreated by running the following command using v2.16.2 of pandoc on Windows Server 2012 R2:

    pandoc.exe -s --extract-media . -o out.md test.docx

The sample `.docx` file to recreate this is available here: [test.docx.zip](https://github.com/jgm/pandoc/files/7794896/test.docx.zip)

**Further details**

* Original .docx (saved from MS Word v16.56 on OS X)

    <img width="720" alt="Screenshot 2021-12-30 at 23 27 28" src="https://user-images.githubusercontent.com/96893191/147794333-0d4619c6-cc17-46b4-9e55-aa5ec1a8a09a.png">

* Generated .md file (from Pandoc)

    <img width="1025" alt="Screenshot 2021-12-30 at 23 33 23" src="https://user-images.githubusercontent.com/96893191/147794443-487696d1-0113-4561-a80a-c4b55af9a5bc.png">

* Unzipped .docx file directory structure (with 10x media files visible)

    <img width="458" alt="Screenshot 2021-12-30 at 23 32 10" src="https://user-images.githubusercontent.com/96893191/147794641-0f474149-7e38-4f0e-866d-8828bf6946bd.png">

**Comment by jgm** [comment]
I think the issue here is that there are several pic:pic elements inside one w:drawing element; our parser is just taking the first...

**Comment by maxklebron** [comment]
@jgm Thanks for the pointer on this.

I'm not so familiar with the underlying `.docx` markup, but from the WYSIWYG frontend of MS Word this seems like a fairly normal thing to be able to do, so could potentially be a common scenario for `.docx` files?

How feasible do you think it might be to extend the parser to cope with multiple pic:pic elements?
