### ISSUE TITLE
include-files.lua sub.md URL image bug

### ISSUE THREAD

**Issue by ajeep8** [jgm/pandoc#7787]
I didn't find how to submit a bug issue in lua-filters, I had ever submitted an issue in lua-filters project but no response. Should I submit here?

https://github.com/pandoc/lua-filters/issues/194

**Comment by jgm** [comment]
No, this isn't the bug tracker for lua-filters.
If you submitted there, it is the right place.  You won't necessarily get a response because it's just a collection of filters written by different people, most of whom don't monitor the repository. You could try contacting the author directly.
