### ISSUE TITLE
tildes in markdown link text and description are broken

### ISSUE THREAD

**Issue by smlavine** [jgm/pandoc#7791]
Given the following input file ```smaller.md```:
```
Tilde in link, and tilde in destination: [~smlavine](https://sr.ht/~smlavine)

Tilde in link, and two tildes in destination: [~smlavine](https://sr.ht/~test/~ing)
```

The command ```pandoc < smaller.md``` produces the following output:
```
<p>Tilde in link, and tilde in destination: [<sub>smlavine](https://sr.ht/</sub>smlavine)</p>
<p>Tilde in link, and two tildes in destination: [<sub>smlavine](https://sr.ht/</sub>test/~ing)</p>
```

This is the expected output (and the output if ```-f commonmark``` is specified):
```
<p>Tilde in link, and tilde in destination: <a href="https://sr.ht/~smlavine">~smlavine</a></p>
<p>Tilde in link, and two tildes in destination: <a href="https://sr.ht/~test/~ing">~smlavine</a></p>
```

I am using pandoc version 2.16.2. ```pandoc -v``` produces the following output:
```
pandoc 2.16.2
Compiled with pandoc-types 1.22.1, texmath 0.12.3.2, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2
User data directory: /home/sebastian/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

I am on Arch Linux. ```pandoc``` is installed from the pandoc-bin AUR package.

**Comment by jgm** [comment]
Commonmark specifies that `[...]` has higher precedence than other indicators of inline structure (like `~...~`).  But pandoc's Mardkown reader has always just used a "first wins" method, so when it encounters `~` it will try to parse a subscript...

I don't know if this is really a bug; it's an issue that was unresolved in the original Markdown syntax description.  Pandoc's Mardkown parser resolves it one way; commonmark another, arguably better way.

In any case you can simply backslash-escape the `~` in the description.

**Comment by smlavine** [comment]
Thanks for the response. Seems like it would be worth fixing but I don't have the time to work on it. I'll be sure to specify ```-f commonmark``` from now on.
