### ISSUE TITLE
md to html: --katex does not automatially add in "\[ \]" around content while --mathjax does

### ISSUE THREAD

**Issue by duy-nguyen-com** [jgm/pandoc#7792]
## Goal: Converting md to html with katex support
When converting md to html with katex, it does not automatically put in "\[ \]" around content; it does not render content. However with --mathjax, it automatically puts in "\[ \]" and renders. I am rendering using katex.

---
With --katex flag:
`pandoc file.md -o file.html --katex --template html.template`

file.md
`$$ \int_{3}^3 = 0 $$`

output:
`<p><span class="math display"> \int_{3}^3 = 0 </span></p>`
![image](https://user-images.githubusercontent.com/55438165/147866852-b5416e69-e05b-4e6d-acdc-d963f3c34bf4.png)

---
With --mathjax flag:
`pandoc file.md -o file.html --mathjax --template html.template`

file.md
`$$ \int_{3}^3 = 0 $$`

output
`<p><span class="math display">\[ \int_{3}^3 = 0 \]</span></p>`

![image](https://user-images.githubusercontent.com/55438165/147866864-57e1d808-38f0-453e-8eee-540c1cbd9bca.png)
## Addtional info
version pandoc 2.9.2.1
html.template adds in the katex style sheet and scripts

**Comment by jgm** [comment]
This isn't a bug.  This approach works perfectly with katex, as long as katex is used in the way it is in the default HTML template:
```html
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];         
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,   
    macros: macros,
    fleqn: false               
   });      
}}});
  </script>
  <link rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css" />
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
```

**Comment by jgm** [comment]
You may be using the "auto-render extension" in your custom template.
This parses the document to find math.  We use a different approach because it is faster; it doesn't require parsing text elements because all of the math is guaranted to be in specially marked spans.

**Comment by jgm** [comment]
Sorry, it's not in the default template that this code is added, but in the HTML writer itself.
The default template contains 
```
$if(math)$
  $math$
$endif$
```
and you must include this in your custom template (rather than explicitly linking to katex).  Hope that clears things up!

**Comment by duy-nguyen-com** [comment]
Thank you so much, I think that I had removed it from the template since I thought this was causing the issue, but forgot to add it back in to debug.
