### ISSUE TITLE
Development version of Pandoc no longer reports types of metadata elements

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc#7796]
The development version (commit 60fc05e2ce2dc4b0191ee98daccf301a065e2dae) does not report the type of metadata elements.

Given a Lua filter `print-metadata-type.lua`:

```Lua
function Meta (meta)
    for _, v in pairs(meta) do print(v.tag) end
end
```

calling

```sh
pandoc -L print-metadata-type.lua <<EOF
---
key: value
...
EOF
```

prints:

> MetaInlines

However, running the same command with the current development version of Pandoc prints:

> nil

@njbart has discovered this behaviour when he tried (and [failed](https://github.com/odkr/pandoc-zotxt.lua/issues/7)) to use `nocite` with the current development version of `pandoc-zotxt.lua`.

Thanks a lot for looking into this!

**Comment by jgm** [comment]
I think @tarleb can clarify the changes that were made.

**Comment by jgm** [comment]
I think 3692a1d1e83703fbf235214f2838cd92683c625c is the relevant commit.

**Comment by tarleb** [comment]
That's the consequence of a recent change that, I believe, makes metadata handling a little nicer. It does away with special types for metadata, which is what you are seeing. See dev version of the docs should give some insights: https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md#metavalue-type-metavalue

For an example of how to to handle this gracefully, see the following patch, which added compatibility for the upcoming version to a filter: https://github.com/pandoc/lua-filters/commit/23f2238816f218690cb80e7e6e148b180a08d707

**Comment by odkr** [comment]
Thanks for the quick reply and the pointers! 😃

I suspect that change has been discussed on the mailing list already? Do you still take feedback? It's just that it appears to me that it'd be cleaner and more useful if `pandoc.utils.type` returned `nil` and an error message if its argument is not a Pandoc type, rather than the Lua type. That would make it simpler to test whether a value is of a Pandoc data type. Also, aren't leading double underscores in metavalue names a namespace that is reserved for Lua's own metavalues? Why not stick to `name`?

**Comment by tarleb** [comment]
Bringing this up on pandoc-discuss is a good point, we haven't done that yet.

Can you give an example of where a modified `pandoc.utils.type` would be useful?

The use of the `__name` variable is as intended by Lua: see the Lua manual for `luaL_newmetatable` and `tostring`. Double-underscore names often give special behavior, but are not reserved (contrary to singles underscore uppercase names, which should not be used).

**Comment by odkr** [comment]
> Can you give an example of where a modified `pandoc.utils.type` would be useful?

Off the top of my head, functions that convert between different data types. Suppose, I have a function `numberify` that converts values of arbitrary types to numbers, if possible.

Compare:

```Lua
do    
    local function elem_numberify (e)
        return tonumber(pandoc.utils.stringify(e))
    end
    
    local fs = {
        number = function (...) return ... end,
	string = tonumber,
	Inline = elem_numberify,
	Block = elem_numberify,
	Meta = elem_numberify
    }

    function numberify (v)
        local t = pandoc.utils.type(v)
	local f = fs[t]
	if not f then return nil, t .. ': unconvertable type' end
	local n = f(v)
	if not n then return nil, v .. ': not a number' end
        return n
    end
end
```

to

```Lua
do    
    local function elem_numberify (e)
        return tonumber(pandoc.utils.stringify(e))
    end

    function numberify (v)
	local n
	local t = pandoc.utils.type(v)
	if t and t ~= 'List' then
	    n = elem_numberify(v)
        else
	    t = type(v)
	    if t == 'number' then
                return v
	    elseif t == 'string' then
                n = tostring(v)
	    else
                return nil, t .. ': unconvertable type'
	    end
	end
	if not n then return nil, v .. ': not a number' end
	return n
    end
end
```

The second implementation strikes me as simpler.

It would also be useful to be able to distinguish between AST elements and other data types. `type` could return higher-order types, too:

```Lua
> pandoc.utils.type(pandoc.Str '')
Inline    AstElement
> -- Or:
Str    Inline    AstElement    Type
> pandoc.utils.type(pandoc.List())
List    Type
> pandoc.utils.type ''
nil    not of a Pandoc type
```

Then the second implementation could be made future-proof by:

```Lua
function numberify (v)
    local n
    local t, st = pandoc.utils.type(v)
    if t and st == 'AstElement' then
        n = elem_numberify(v)
    else
        -- [...]
    end
    return n
end
```

Doing similar future-proofing would be harder with the first implementation, though that's a rather academic argument, admittedly.

It appears to me that a `type` function that works for Lua's *and* Pandoc's types is most useful if a piece of code expects values of types of both kinds, but such pieces of code are also the ones that would profit the most from being able to distinguish between plain Lua values and Pandoc AST elements easily; after all, they behave quite differently.

Come to think of it, what about:

```Lua
> pandoc.utils.type ''
string
> pandoc.utils.type(pandoc.Str '')
userdata    Str    Inline    AstElement    Type
```

**Comment by tarleb** [comment]
Interesting points and ideas.

What's funny is that I, personally, like the first version of `numberify` better and find it easier to read. For what it's worth: all pandoc types contain at least one upper-case letter in their name, so the following is guaranteed to work the way you prefer:

``` lua
function pandoctype (obj)
  return pandoc.utils.type(obj):match '^[a-z]*$'
end
```

The multi-return-value idea is something I'll keep in mind. We no longer have the `AstElement` type-hierarchy, it was an implementation detail of our previous marshaling method. But getting `Inline   Str` as return values from `pandoc.utils.type(pandoc.Str'') might make sense.

**Comment by odkr** [comment]
> What's funny is that I, personally, like the first version of `numberify` better and find it easier to read.

Oh, I agree that the first version is more beautiful, it's just not simpler ;-).

> The multi-return-value idea is something I'll keep in mind. We no longer have the `AstElement` type-hierarchy, it was an implementation detail of our previous marshaling method. But getting `Inline Str` as return values from `pandoc.utils.type(pandoc.Str'') might make sense.

I see. But some way to distinguish between AST elements and values of other Pandoc types would be useful, I think.

**Comment by tarleb** [comment]
> Oh, I agree that the first version is more beautiful, it's just not simpler ;-).

Fair. :smile: 

> But some way to distinguish between AST elements and values of other Pandoc types would be useful, I think.

I didn't have a use-case for that yet, but I'm not opposed either. The [pandoc-lua-marshal](https://github.com/pandoc/pandoc-lua-marshal) repo has all the relevant code in case you'd like to take a look.

**Comment by odkr** [comment]
> The [pandoc-lua-marshal](https://github.com/pandoc/pandoc-lua-marshal) repo has all the relevant code in case you'd like to take a look.

Thanks a lot for the invitation. But I'm afraid my Haskell is rusty. I tried to get into it some years ago, but never had a good enough reason and the time to actually use it. So, err, don't expect a PR anytime soon ;-).
