### ISSUE TITLE
asciidoc checklists

### ISSUE THREAD

**Issue by arcnmx** [jgm/pandoc#7798]
**Explain the problem.**

Converting the following:

```bash
pandoc -f gfm -t asciidoctor <<EOF
- [ ] a
- [x] b
EOF
```
produces:

```asciidoc
* ☐ a
* ☒ b
```

instead of using the checklist syntax ([see asciidoctor docs](https://docs.asciidoctor.org/asciidoc/latest/lists/checklist/)):

```asciidoctor
* [ ] a
* [x] b
```

This seems related to [the recently fixed org-mode reader/writer support for a similar feature](https://github.com/jgm/pandoc/pull/7098).

**Pandoc version?**

pandoc 2.14.0.3, NixOS

**Comment by jgm** [comment]
Yes, if someone wants to implement this change to the AsciiDoc writer, the code needed should be very similar to the changes to the Org writer linked above.

**Comment by tarleb** [comment]
Fixed in #7832.

**Comment by arcnmx** [comment]
Hm, is `* [X]` equivalent to the documented `* [x]` or `* [*]`?
As far as I can tell, asciidoctor does not recognize the former (which appears to be what was implemented) as a checklist.

**Comment by tarleb** [comment]
Well, that's an issue then. @ricnorr, do you have time to look into this?

**Comment by jgm** [comment]
I can fix this, it's a simple fix.
