### ISSUE TITLE
docbook reader not sensitive to compact list spacing

### ISSUE THREAD

**Issue by arcnmx** [jgm/pandoc#7799]
**Explain the problem.**

When I was [testing checklists](https://github.com/jgm/pandoc/issues/7798), I found that the following:

```bash
pandoc -f gfm -t docbook <<EOF | pandoc -f docbook -t gfm
- a
- b
EOF
```

produces a list with extra spacing between elements:
```markdown
- a

- b
```

... despite the generated docbook containing `<itemizedlist spacing="compact">`.

(I'm also curious if `spacing="normal"` is distinct from no `spacing` whatsoever, since it has no default according to the docs? It feels odd to default to the wide spacing in markdown output, but maybe that's just me.)

**Pandoc version?**
pandoc 2.14.0.3, NixOS

**Comment by jgm** [comment]
The gfm writer does output compact lists.
The problem is that when you convert to docbook, you get `<paragraph>` elements, and this gets interpreted as loose lists.

**Comment by jgm** [comment]
That is, docbook doesn't have a distinction btw compact and loose lists, so this gets lost.

**Comment by arcnmx** [comment]
> That is, docbook doesn't have a distinction btw compact and loose lists, so this gets lost.

The two gfm snippets above do produce distinct output though, when run through `pandoc -f gfm -t docbook`. The initial example conveys that it was a compact list:

```docbook
<itemizedlist spacing="compact">
  <listitem><para>a</para></listitem>
  <listitem><para>b</para></listitem>
</itemizedlist>
```

and the second loose version currently produces:

```docbook
<itemizedlist>
  <listitem><para>a</para></listitem>
  <listitem><para>b</para></listitem>
</itemizedlist>
```

So it seems reasonable that the docbook reader (and thus the gfm writer) would be able to distinguish them, no?

(It's also worth noting that [asciidoctor struggles with list spacing on github for semi-related reasons](https://github.com/asciidoctor/asciidoctor/issues/1087), because of how its output of `<li><p>` interacts with github's css?)

**Comment by jgm** [comment]
Oh, in that case, this looks like an issue with the docbook reader.
```
% pandoc -f docbook -t native
<itemizedlist spacing="compact">
  <listitem><para>a</para></listitem>
  <listitem><para>b</para></listitem>
</itemizedlist>
[ BulletList [ [ Para [ Str "a" ] ] , [ Para [ Str "b" ] ] ]
]
```
should be `Plain` rather than `Para`.
