### ISSUE TITLE
Clarify ambiguous "standard Markdown" in the MANUAL

### ISSUE THREAD

**Issue by not-my-profile** [jgm/pandoc#7802]
The [MANUAL](https://pandoc.org/MANUAL.html) refers to Gruber's Markdown as "standard Markdown" which might confuse people who think of the CommonMark standard when hearing "standard Markdown".

To avoid this ambiguity we could replace all occurrences of "standard Markdown" in the MANUAL with "Gruber's Markdown".

**Comment by alerque** [comment]
Anybody that knows "Gruber" is going to understand the scene pretty well already. I grant that using "standard" is getting more and more confusing as time goes on asd fewer implementations stick to the original sketch, but perhaps just describing it a little bit more directly would help avoid the confusion with CommonMark and help newcomers understand the scene. I propose refering it it as "original generic markdown". Perhaps on the first mention it could be "Gruber's original".

**Comment by not-my-profile** [comment]
Searching Google for "original generic markdown" doesn't yield a single result: I don't think we should invent new terminology but I'd be fine with "original Markdown".

**Comment by jgm** [comment]
"Original Markdown" perhaps?
"Classic"?

**Comment by tarleb** [comment]
+1 for "original Markdown"
