### ISSUE TITLE
Convert definition lists in `doc/lua-filters.md` into tables?

### ISSUE THREAD

**Issue by not-my-profile** [jgm/pandoc#7807]
The Lua Filters API is currently documented in `doc/lua-filters.md` like:

```markdown
### CodeBlock {#type-codeblock}

Block of code.

Values of this type can be created with the
[`pandoc.CodeBlock`](#pandoc.codeblock) constructor.

Fields:

`text`
:   code string (string)

`attr`
:   element attributes ([Attr])

`identifier`
:   alias for `attr.identifier` (string)

`classes`
:   alias for `attr.classes` ([List] of strings)

`attributes`
:   alias for `attr.attributes` ([Attributes])

`tag`, `t`
:   the literal `CodeBlock` (string)
```

which https://pandoc.org/lua-filters.html displays as:

![image](https://user-images.githubusercontent.com/73739153/148344235-3451abc4-860d-43af-b086-7f6e2fc32bec.png)

I would personally find it more readable if the fields were formatted as a table instead, so:

```markdown
### CodeBlock {#type-codeblock}

Block of code.

Values of this type can be created with the
[`pandoc.CodeBlock`](#pandoc.codeblock) constructor.

: Fields

------------  --------------------------------------------
`text`        code string (string)
`attr`        element attributes ([Attr])
`identifier`  alias for `attr.identifier` (string)
`classes`     alias for `attr.classes` ([List] of strings)
`attributes`  alias for `attr.attributes` ([Attributes])
`tag`, `t`    the literal `CodeBlock` (string)
------------  --------------------------------------------
```

![image](https://user-images.githubusercontent.com/73739153/148344853-f44f3f0e-a098-4071-adb7-25f6ff798091.png)

I find it easier to read and the gained compactness would also help making the 20 meter long page (according to `document.body.scrollHeight`) less unwieldy. To clarify I suggest this conversion only for the Fields & Parameters definition lists, outer definition lists would remain, e.g:

| Before | After |
| -- | -- |
|![image](https://user-images.githubusercontent.com/73739153/148345966-3c13011e-af14-44d2-9500-99516a0c04b2.png)|!![image](https://user-images.githubusercontent.com/73739153/148346473-b87a9268-3b97-4328-98eb-043f02644bcb.png)

What do you think?

**Comment by jgm** [comment]
I believe this documentation is currently auto-generated from the code.  @tarleb would be able to comment further, and also on whether it would be feasible/better to use table.  I agree with you aesthetically, though it's not a big difference.

**Comment by tarleb** [comment]
Parts of it were auto-generated, others are hand-written (because it was quicker; my hslua tooling needs more work). The current structure is modeled after both the pandoc manual and the output of ldoc ([example](https://lunarmodules.github.io/Penlight/libraries/pl.pretty.html)). I'm not sure if tables are really better here; if length is a problem, then guess I'd rather split the document into more pages or add a navigation sidebar.

**Comment by not-my-profile** [comment]
>if length is a problem, then guess I'd rather split the document into more pages or add a navigation sidebar.

I guess what bothers me is that it's quite much wasted vertical screen real estate ... splitting it up into more pages wouldn't change that.

**Comment by jgm** [comment]
@not-my-profile I think that tables would be good if everything were auto-generated, but if they have to be written by hand, it's easier to deal with definition lists.  (Though I suppose we could use a filter in producing the HTML that converts definition lists to tables; in this case the markdown source wouldn't need to change, but we'd want to be sure that we really want ALL definition lists to become tables.)

**Comment by jgm** [comment]
It might also be possible to get a more compact output by changing the CSS for definition lists...

**Comment by not-my-profile** [comment]
> but we'd want to be sure that we really want ALL definition lists to become tables.

There's nothing stopping us from making a "smart filter" that only converts definition lists if they are preceded by a paragraph containing the text "Parameters:" or "Fields:".

**Comment by jgm** [comment]
Note that tabular output looks good when the terms (dt) are all about the same width.  When you have a definition list where some of the terms are much longer than others, tabular output is not pleasing, since the definition (dd part) gets squashed into an overly narrow column.

For a CSS solution, this works
```
dl:before,
dl:after {
    display: table;
    content: "";
    line-height: 0;
}
dl dt {
  float: left;
  width: 160px;
  clear: left;
  text-align: left;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
dl dd {
  margin-left: 180px;
}
```
but the "term" column is too narrow for many of the dls in lua-filters.md.  One could try restricting it to sections of the document where parameters are given, and/or increasing the width of the left column.

**Comment by jgm** [comment]
<img width="821" alt="Screen Shot 2022-01-06 at 11 27 25 AM" src="https://user-images.githubusercontent.com/3044/148439877-4e538497-8065-4c06-9e9d-82e1053fa452.png">

This is how it looks with the above CSS.

**Comment by jgm** [comment]
However, in some dls content is cut off:

<img width="825" alt="Screen Shot 2022-01-06 at 11 28 08 AM" src="https://user-images.githubusercontent.com/3044/148439965-d8456539-3831-4938-aa1f-75f93c542475.png">

**Comment by jgm** [comment]
If (a) we had a class attribute on a parent of all the dls that are just parameter lists, and (b) we were sure that all parameter names would fit into the fixed width, we could use this solution.

**Comment by not-my-profile** [comment]
>However, in some dls content is cut off:

A better CSS approach is to use flexbox:

```css
dl {
  display: flex;
  flex-wrap: wrap;
}
dt {
  width: 33%;
}
dd {
  margin-left: auto;
  width: 66%;
}
```

**Comment by jgm** [comment]
That works well; I've added it temporarily at
https://pandoc.org/lua-filters.html
@tarleb what do you think?

One question is whether some of the columns will overlap on mobile phone sizes, and whether anything can be done to prevent this.  (Adding min-width didn't work well.)

**Comment by not-my-profile** [comment]
>whether anything can be done to prevent this

You can use a media query to only activate the CSS for browsers of a certain width, e.g:

```css
@media (min-width: 600px) {
   /* put the CSS in here */
}
```

**Comment by jgm** [comment]
Great!  I wasn't able to get this to work, though.
Have you tested it?  Maybe you could propose a CSS chunk that will look good?

**Comment by tarleb** [comment]
Oh, that *does* look nice! I'm in favor.

**Comment by not-my-profile** [comment]
The problem is that this also targets the outer definition lists we should keep as definition lists:

https://pandoc.org/lua-filters.html#element-components-1

![image](https://user-images.githubusercontent.com/73739153/148442645-6155378e-e247-447d-b725-0b8158fcf8d6.png)

**Comment by tarleb** [comment]
I just noticed the same. Those should be headings, really.

**Comment by not-my-profile** [comment]
That would certainly solve this problem.

**Comment by not-my-profile** [comment]
>I've added it temporarily at https://pandoc.org/lua-filters.html

@jgm You might want to disable that again until the definition terms that are currently overlapping are changed to headings (because right now the official doc looks broken like in the above screenshot).

**Comment by jgm** [comment]
@tarleb what is involved in changing these outer definition lists to headings? Are these auto-generated or can we just modify lua-filters.doc?

**Comment by tarleb** [comment]
Those were generated from `data/pandoc.lua`. The file is gone now, so we can safely modify the text in the document.

**Comment by tarleb** [comment]
I've written new code to auto-generate module documentation: [render-docs.lua](https://github.com/hslua/hslua/blob/generate-module-docs/tools/render-docs.lua). Use like this: `pandoc -L render-docs --metadata=target=pandoc.system <<< ''`. I may try to switch to that in the future.

Personally, I think the CSS approach might be better than using tables in markdown.

**Comment by jgm** [comment]
Sure, CSS approach seems fine.  I like the autogenerated docs idea.  If it works, why not switch to it?

**Comment by tarleb** [comment]
OK, will do. The sources and actual docs are probably very out-of-sync, so I'll start with that. I also expect to find some cases where the generator will need more tuning, but should all be very doable.

**Comment by allefeld** [comment]
I'm regularly running into the same problem when using Pandoc, not for documentation necessarily but for my own text.

Basically, I tend to use definition lists for two different purposes: 1) "definitions" are longer text, possibly with multiple paragraphs, and the "terms" functions as a mini-heading, 2) for a list of brief descriptions, table-like, probably closer to the original intention.

I've come up with the following: I wrote a Lua filter which checks definition lists, and if all definitions are Plain AST elements, it wraps the whole definition list in a Div AST element with class `compactdef`:

```lua
-- mark compact definition lists
function DefinitionList(elem)
  -- Determine whether the definition list contains only Plain definitions
  -- (i.e. its contents are not wrapped in Para elements)
  local allplain = true
  for _, item in pairs(elem.content) do     -- different terms
    for _, definition in pairs(item[2]) do  -- different definitions
      allplain = allplain and (definition[1].tag == "Plain")
    end
  end
  -- If so, wrap the definition list in a Div element with class "compactdef."
  -- This is styled by CSS for a more compact, bullet-list-like layout.
  if allplain then
    return pandoc.Div(elem, pandoc.Attr("", {"compactdef"}, {}))
  else
    return elem
  end
end
```

I then use `grid` CSS to format the list table-like:

```css
div.compactdef dl {
  display: grid;
  grid-template-columns: min-content auto;
  column-gap: 1rem;
  row-gap: 0px;
}

div.compactdef dt {
  grid-column: 1;
}

div.compactdef  dd {
  grid-column: 2;
  margin: 0px;
}
```

Result:
![image](https://github.com/jgm/pandoc/assets/1738353/b9b352f1-406e-4d28-8bbf-fe63426bcda1)

__Two questions:__

- The one thing I dislike about this is the wrapper Div; I'd rather have the class on the DefinitionList element. However, it appears that [DefinitionList objects](https://pandoc.org/lua-filters.html#type-definitionlist) do not support classes?

- Maybe the rule I described above could be adopted for Pandoc in general? Basically, compact definition lists would be represented in HTML as `<dl class="compact">`.

**Comment by jgm** [comment]
I've updated the CSS on the site to use tabular flexbox when there are at least 1024 pixels.  So, closing this.
