### ISSUE TITLE
Class attribute inconsistency between markdown and commonmark_x

### ISSUE THREAD

**Issue by gpoore** [jgm/pandoc#7809]
`markdown` allows class attributes like `.some.class`, but `commonmark_x` doesn't recognize this as a class due to the internal period.

This is for Pandoc `2.16.2`.

Example file `attr.md`:
``````
```{.some.class key=value}
code
```
``````
Output of `pandoc -f markdown -t native ./attr.md`:
```
[ CodeBlock
    ( "" , [ "some.class" ] , [ ( "key" , "value" ) ] ) "code"
]
```
Output of `pandoc -f commonmark_x -t native ./attr.md`:
```
[ CodeBlock ( "" , [ "{.some.class" ] , [] ) "code" ]
```
I use class names with internal periods a lot as a way to namespace classes that are used for filter-type operations on the AST.

**Comment by jgm** [comment]
True. commonmark-extensions defines
```
    id_attribute <- '#' letter (alphanum | '-' | '_' | ':' | '.')*
    class_attribute <- '.' letter (alphanum | '-' | '_')*
```
but pandoc's markdown parser uses the same parser for id attributes and class attributes (so, `:` and `.` are allowed).

I can't now recall why I made the class parser in commonmark-extensions more restrictive.  But my guess is that I was looking at
https://www.w3.org/TR/CSS21/syndata.html#characters

> "In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. "

I think it's a sensible move to tie the class syntax to the CSS spec, so if anything we should tighten up the behavior of pandoc's markdown parser to exclude internal periods.  (I'm hesitant to do so, though, because this could break things.)

**Comment by gpoore** [comment]
Restricting the class names definitely makes sense from an HTML output perspective. My only concern with that is whether it unnecessarily limits other output formats that interpret the `.class` syntax differently, such as setting a key to a default (potentially non-boolean) value. But if the attribute syntax is intended to map directly to HTML, it would make sense to base it on the CSS spec.

In my case, I'm using the classes as a way to tag AST nodes for filter processing, so they aren't really classes and never make it into the final document (regardless of output format). I can work around this by using a more verbose key-value syntax...that will complicate and slow down converting from `markdown` to `commonmark_x`, but should be doable.

Regardless of whether it's possible to make `markdown` and `commonmark_x` behave the same way in this case, I'm looking forward to doing a lot more with `commonmark_x` in the future. It's great to be able to use CommonMark without having to give up all of the Pandoc extensions.

**Comment by jgm** [comment]
Okay, I'll close this, then.
You could always use `_` or `-` instead of `.`.
