### ISSUE TITLE
Org writer: some issues and possible improvements with lists

### ISSUE THREAD

**Issue by lucasvreis** [jgm/pandoc#7810]
Hi, while writing tests for a org writer PR about lists I found a few corner cases related to newlines that are not handled very well. So I am filing this issue to keep a record of them.
1. This one is actually a bug since it generates invalid org ([see this observation](https://github.com/jgm/pandoc/issues/7557#issuecomment-917047836)): the org file
	```org
	- 
	  #+begin_example
	    aa
	  #+end_example
	- test
	```
	"round trips" (`--from org --to org`) to
	```org
	- #+begin_example
	  aa
	  #+end_example
	
	 - test
	```
	which is not valid org as jgm noted (only plain or para should appear on the bullet line).
2. This next one is also present in RST (the code was copied I guess): when a list item is empty, space is added after the item so that
	  ```
	  - a
	  - 
	  - a
	  - a
	  ``` 
	  "round trips" (`--from org --to org`) to
	  ```
	  -  a
	  -  
	  
	  -  a
	  -  a
	  ```
	
3. This is a suggestion that I think is related to item 2: currently, nested lists (even "tight" ones) are written with unnecessary newlines around them, like so:
	  ```
	  -  a
	  
	     -  b
	     -  b
	  
	  -  a
	  -  a
	  ```
	  maybe it is possible to write without such newlines (like the markdown writer).

**Comment by jgm** [comment]
On 3:  the code contains a comment that says

>   -- ensure that sublists have preceding blank line

but I have no idea why (I didn't write this writer).  It seems to me that this is not necessary at all in org.

**Comment by jgm** [comment]
I believe I've now fixed all three issues.
