### ISSUE TITLE
Incorrect language alias for Punjabi/Panjabi language

### ISSUE THREAD

**Issue by thekalinga** [jgm/pandoc#7814]
**Explain the problem.**
The correct language alias for the language Punjabi/Panjabi `pa` is `punjabi`. But pandoc incorrectly maps `pa` to `panjabi` instead

`pa` to be mapped p**u**njabi instead of p**a**njabi (a single character change)

We can find this out from multiple places

1. https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/likely_subtags.html#pa
2. https://github.com/latex3/babel/blob/main/locale/pa/babel-pa.ini
3. https://ctan.asis.ai/macros/latex/required/babel/base/babel.pdf

When I searched for it in pandoc repo

https://github.com/jgm/pandoc/search?q=panjabi

I see the wrong alias is being declared in two different files. I think in both places it has to be renamed to `punjabi`

**Pandoc version?**:
Using via docker. Image used: `pandoc/latex:2.16.2`

**Comment by jgm** [comment]
Thanks for the report!

**Comment by mb21** [comment]
Both [wikipedia](https://en.wikipedia.org/wiki/Punjabi_language) and [Britannica](https://www.britannica.com/topic/Punjabi-language) say both spellings are in use. But our mappings are to/from LaTeX babel package, so if they switched over to Punjabi, we should indeed do so as well.
