### ISSUE TITLE
figures with captions created in filters don't display the caption in ms word output

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#7817]
Consider this document `caption.md`:

```markdown
![foo](https://placekitten.com/350/300)
```

And this filter `caption.lua`:

```lua
Image = function(image)
   image.caption:insert("bar")
   return image
end
```

If I run this input through the `opendocument` writer we get the expected output:

```bash
$ pandoc caption.md --to opendocument --lua-filter caption.lua
<text:p text:style-name="FigureWithCaption"><draw:frame draw:name="img1"><draw:image xlink:href="https://placekitten.com/350/300" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" /></draw:frame></text:p>
<text:p text:style-name="FigureCaption">foobar</text:p>
```

However if I modify the image to start with no caption at all:

```markdown
![](https://placekitten.com/350/300)
```

Then running the conversion results in a plain image (no `FigureWithCaption`) without the "bar" caption that was inserted by `caption.lua`:

```bash
$ pandoc caption.md --to opendocument --lua-filter caption.lua
<text:p text:style-name="Text_20_body"><draw:frame draw:name="img1"><draw:image xlink:href="https://placekitten.com/350/300" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" /></draw:frame></text:p>
```

This with Pandoc 2.16.2 running on Mac OS 10.15.5

**Comment by jgm** [comment]
This is intended behavior:  see the docs for the `implicit_figures` extension.

> An image with **nonempty** alt text, occurring by itself in a       
paragraph, will be rendered as a figure with a caption.  The    
image's alt text will be used as the caption.

**Comment by jgm** [comment]
Oh, sorry, I see now why this is confusing.  You're thinking that after the filter makes the alt text nonempty, the image should render as a figure.  The reason it doesn't is an undocumented convention that's a bit of a kludge.  The markdown reader will mark images that should turn into figures with a `fig:` prefix in the title.  What your filter needs to do is to add a title to the image with prefix `fig:` -- this could just be the string `fig:`.

**Comment by jgm** [comment]
I know, this isn't great.  When we get a proper Figure element added, we'll be able to dispense with this.

**Comment by jjallaire** [comment]
Thanks! Yes, adding the `fig:` prefix to the title does indeed result in a proper figure.

The scenario is that we are supporting un-captioned subfigures (so e.g. the subcaption "(a)" is automatically provided as  the caption by the filter)
