### ISSUE TITLE
DocBook 4.5 with <code>..</code> or <literal>...</literal> tags and line breaks / spaces

### ISSUE THREAD

**Issue by jcurl** [jgm/pandoc#7821]
**Problem**: When converting a docbook 4.5 document, that I've created using XML Mind Editor as a book to PDF (see my [commit](https://github.com/jcurl/RJCP.DLL.CodeQuality/commit/5bb76982795752f93b072635c77a7516c0bec7cd)), the resulting PDF takes spaces literally, while DocBook conversion tools do not.

I've tried replacing `<literal>...</literal>` with `<code>...</code>` without effect.

I'd like to ask this great project if anyone knows how I can configure formatting of code to allow wrapping of lines and ignore multiple spaces, which XXE inserts in the raw text. I'd like to avoid where possible modifying the document by hand, as XXE will "automatically" put back the new lines.

I'm wondering if this is a bug (difference in other tools, subjective), and how I might customize this behaviour.

**Version**: I'm using the version of pandoc that comes with Ubuntu 20.04 via the apt-install package.
```
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/jason/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Reproducibility**: See the DocBook at output at [GitHub](https://github.com/jcurl/RJCP.DLL.CodeQuality/tree/feature/dotnet-494/doc/build/AccessorBestPractices), e.g. page 11, 12, 18.

**Attempts to Solve**:
- I didn't find anything in Google that I could use. Most documentation is about markdown conversion.
- Changed `literal` to `code` and it didn't help
- Tried looking for something that I could add to my metadata file, but alas, no luck (yet).

Again, thank you for the wonderful project.

**Comment by jgm** [comment]
In this case the input looks like
```xml
        <listitem>
          <para><literal>object InvokeStatic(PrivateType type, string
          methodName, params object[] args);</literal></para>
        </listitem>
```
and pandoc is taking the indentation to be spaces in the code content.  I'm not a DocBook expert, and it could well be that consecutive spaces in this context can be collapsed, but I'd like to find that in the documentation before I change pandoc's behavior.  I don't see anything about it here: https://tdg.docbook.org/tdg/4.5/literal.html

**Comment by jcurl** [comment]
Thank you for the fast reply. Would a comparison with the official stylesheets help?

**Comment by jcurl** [comment]
I also see that while the link to literal indicates nothing, this link https://tdg.docbook.org/tdg/4.5/literallayout.html could be construed that literal collapses spaces, while literallayout shouldn't. Hence, literal should collapse.

**Comment by jgm** [comment]
This is plausible to me.  I'd feel better about it if I could see that whatever the most standard docbook toolchain is does this.  But I don't know anything about docbook tooling ; can you check this for me?

**Comment by jgm** [comment]
Yes, the official stylesheets would help me!

**Comment by jcurl** [comment]
This is the [out.pdf](https://github.com/jgm/pandoc/files/7841417/out.pdf).

To do this, I installed xsltproc on ubuntu, java, and I have a downloaded version of the official docbook 4.5 XSL files (docbook-xsl-1.79.1).

```cmd
xsltproc ~/Downloads/docbook45/docbook-xsl-1.79.1/fo/docbook.xsl ./AccessorBaseBestPractices.xml > out.fo
op out.fo out.pdf
```

You'll see that the output is properly wrapped.

**Comment by jgm** [comment]
Note that there are two issues here, which I think are separate:

1.  Should the internal spaces be collapsed?  (yes, apparently)
2. Should the code span wrap if it exceeds line length?

1 is a reader issue.  2 concerns writers in the various possible target formats, and so it's really out of scope for this issue.

**Comment by jcurl** [comment]
Yes, I do think both apply, that (1) should collapse, and (2) should also wrap as in the "fo" output in the PDF for one very long line. But doesn't markdown also have a case that `a very long line in these quotes would also wrap`?

**Comment by jgm** [comment]
I think it will wrap, but you'll have to try it out.
A nightly should be available by tomorrow.

**Comment by jcurl** [comment]
That's awesomely fast.

**Comment by jcurl** [comment]
Tested, the result doesn't wrap.
