### ISSUE TITLE
No wrap with #7821 integrated

### ISSUE THREAD

**Issue by jcurl** [jgm/pandoc#7824]
**Explain the problem.**
With the fix applied by https://github.com/jgm/pandoc/issues/7821, it is observable that whitespaces are no longer literally applied when converting DocBook 4.5 to PDF via the TeX engine.

A secondary effect, as noted in https://github.com/jgm/pandoc/issues/7821, is that the `<literal>...</literal>` doesn't wrap. When comparing with the original FOP output into PDF, it does wrap.

See the repository at [commit](https://github.com/jcurl/RJCP.DLL.CodeQuality/commit/5bb76982795752f93b072635c77a7516c0bec7cd).

The build was done with

```cmd
$ cd doc
$ mkdir build
$ cmake -DPANDOC_EXECUTABLE=/home/jason/.cabal/bin/pandoc ..
$ make
```

**Pandoc version?**
This was tested on Ubuntu 20.04, following the instructions at https://github.com/jgm/pandoc/blob/master/INSTALL.md, installing and updating cabal, to then run the version of pandoc

```
pandoc 2.16.2
Compiled with pandoc-types 1.22.1, texmath 0.12.3.3, skylighting 0.12.1,
citeproc 0.6, ipynb 0.2
User data directory: /home/jason/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Specifically built from this commit

```
$ git log -1
commit a25e79b5bef9a55c076351d1321675e26513f8ac (HEAD -> master, origin/master, origin/HEAD)
Author: John MacFarlane <jgm@berkeley.edu>
Date:   Mon Jan 10 11:47:55 2022 -0800

    DocBook reader: Collapse internal spaces in literal...
    
    and other similar tags.  This seems to accord with what
    the docbook toolchain does.
    
    Closes #7821.
```

**Comment by jgm** [comment]
I don't understand the issue.  Just tried `pandoc -f docbook best.xml -o best.pdf` and here's how it looks:
<img width="434" alt="Screen Shot 2022-01-10 at 1 47 56 PM" src="https://user-images.githubusercontent.com/3044/148844634-42e66d55-debe-452b-a60f-79686cfef487.png">
Looks wrapped to me!

**Comment by jgm** [comment]
Perhaps you can give very explicit instructions, including a *minimal* input sample sufficient to generate the issue, and a screenshot of the output you're getting.

**Comment by jgm** [comment]
Note that code in *code blocks* (as opposed to inline code) will not wrap.
Wrapping in that context can be very confusing, and not really possible to achieve when you're generating the PDF via LaTeX; it's better to adjust the source so wrapping is not needed, or adjust your latex template so that a smaller font or narrower margin is used.
Alternatively you could generate the PDF via html and wkhtmltopdf with CSS adjustments.

**Comment by jcurl** [comment]
My apologies that I didn't attach the PDF output. Here it is based on the commit of your change:
[AccessorBaseBestPractices.pdf](https://github.com/jgm/pandoc/files/7842105/AccessorBaseBestPractices.pdf)

You're example shows a difference! Now if I use the command you give, this is the PDF output: 
[out.pdf](https://github.com/jgm/pandoc/files/7842114/out.pdf) - looks good.

I'll investigate further on my side if:
a) My scripts are working and really using the pandoc that I build from your repo; or
b) What the command line I'm doing that can reproduce the problem.

Thank you very much for taking your time, and especially so fast.

**Comment by jcurl** [comment]
This was my error in how I renewed a command. I'm closing this as it's my bug. Lots of thanks.
