### ISSUE TITLE
reveal.js `r-strech` not working

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#7829]
Following #5965, pandoc 2.17 moved to support reveal's `r-stretch` attribute. However, it still does not work for maximizing the vertical height of an element/image.

[`r-stretch`](https://revealjs.com/layout/#stretch) requires:
1. there be only a single decorated element, that is:
2. a descendent of the `section` element.

pandoc 2.17 creates the following structure where both the `p` and the `img` are decorated with `r-stretch`.

```html
<section id="local-html-r-stretch" class="slide level2">
<h2>Local, html &amp; r-stretch</h2>
<p class="r-stretch">
<img data-src="media/nounproject-dog.png" class="r-stretch"/>
</p>
</section>
```
Placing the attribute exclusively on `p` simply maximizes the blank space and `img` stays its original size. Placing the attribute exclusively on `img` does nothing because it is constrained by a non-stretch `p` of typical height.

The only thing that works is that `img` is a child of `section`, as such:

```html
<section id="local-html-r-stretch" class="slide level2">
<h2>Local, html &amp; r-stretch</h2>
<img data-src="media/nounproject-dog.png" class="r-stretch"/>
</section>
```
Is it possible for pandoc to generate this?

**Comment by jgm** [comment]
What command are you using? Are you sure you're running the latest version?
Here's what I see:
```
 % pandoc -t revealjs
![test](img.jpg){.r-stretch}
<section class="slide level6">

<img data-src="img.jpg" title="fig:" class="r-stretch" alt="test" />
</section>
```

**Comment by reagle** [comment]
My apologies. I did not have the attribute on the image in the markdown, though that makes most sense and that's where it is in revealjs.
