### ISSUE TITLE
Blank newlines not persevered when converting to docx from readme

### ISSUE THREAD

**Issue by caseygoodricher** [jgm/pandoc#7836]
When converting from markdown to docx blank newlines are not preserved. For example in markdown:
```
This is a test
Another Test

There should be a newline between this line and "Another Test"


There should be two newlines above this text
```

Convert the markdown file to docx `pandoc -s test.md -o test.docx -t docx`. The resulting output only keeps paragraph newlines from my understanding. Removing empty paragraphs:
![Screen Shot 2022-01-15 at 16 43 10](https://user-images.githubusercontent.com/40069043/149639661-14188754-f18f-4515-9058-6a57fbd775ba.png)

Expected output where the single blank and double blank newlines are preserved:
![Screen Shot 2022-01-15 at 16 47 56](https://user-images.githubusercontent.com/40069043/149639670-15bce870-7cc0-4720-ac9f-08db6673021a.png)

Reading through the documentation the following extension `empty_paragraphs` should resolve my problem. But this extension has no visible affect. Command that was used to convert:
```
pandoc -s test.md -o test.docx -t docx+empty_paragraphs
```

I tested some with html and was able to get newlines using `<w:br/><w:br/>` - allows for a blank newline as expected but that'd force me to convert markdown to html then parse the html and add `<w:br/>` where needed & finally convert to docx

Pandoc version:
```
pandoc 2.17
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.1,
citeproc 0.6.0.1, ipynb 0.2
```

**Comment by jgm** [comment]
This is just a matter of the style your docx is using.  You can use `--reference-doc` (see the manual) to specify a different style.  (modify the Normal style by adding some "space after", and your paragraphs will be more separated, as you seem to want.)

**Comment by jgm** [comment]
Also, note that pandoc is only concerned with structure, not with details of formatting (see beginning of the manual).  There is no difference between one and two blank lines between paragraphs in markdown source; the meaning is the same, namely "we have two paragraphs here."

**Comment by caseygoodricher** [comment]
Hello

I added paragraph spacing & used the reference-doc parameter. All but the paragraph spacing was copied over. Any ideas?

= = =

Then following that question why does HTML to DOCX using `<w:br/><w:br/>` allow for blank space newlines ? Why can't markdown -> docx allow for blank space newlines?

Thanks!

**Comment by jgm** [comment]
You can do something like
```
hi

\

\

there
```

What you have to understand is that blank lines in markdown are just paragraph separators. If you want something corresponding to `<br>` in HTML, you need to use an escaped newline in pandoc's markdown, as above.

**Comment by agusmba** [comment]
> I added paragraph spacing & used the reference-doc parameter. All but the paragraph spacing was copied over. Any ideas?

I've never had problems with paragraph spacing using a modified reference-doc. Did you modify the correct styles in your reference document? Remember that modifying paragraphs directly in the reference doc won't work, you need to modify the styles.

**Comment by caseygoodricher** [comment]
Thank you all for the help. I was able to do what @jgm said

Converted a DOCX to markdown replaced certain newlines to be escaped newlines and converted back to DOCX
