### ISSUE TITLE
Consider editing repository setings to remove "Packages" section

### ISSUE THREAD

**Issue by matkoniecz** [jgm/pandoc#7837]
"Packages No packages published" is displayed right now, fortunately this pointless section can be removed.

Edit repo page config to remove it (cog next to the description).

I am not making a PR as it is defined in proprietary github settings, not in a git repository - and I have no rights to modify repo settings.

![Peek 2020-10-25 09-10](https://user-images.githubusercontent.com/899988/97102018-3a168700-16a2-11eb-8c18-7bd9a88922eb.gif)

-----------

BTW, I just got to http://reasonableapproximation.net/2021/03/30/command-line-grammar-of-graphics.html in my TODO list and I must say that I quite like the idea. I will definitely try it once I need a graph. (or is it a chart? I forgot the difference again)

**Comment by matkoniecz** [comment]
> added the bug label now

Sorry, some template added it despite replacing the entire text. It is not really a bug.

**Comment by jgm** [comment]
Done ,thanks!
