### ISSUE TITLE
Hackage documentation went missing

### ISSUE THREAD

**Issue by davidpomerenke** [jgm/pandoc#7839]
**Explain the problem.**
The list of modules on https://hackage.haskell.org/package/pandoc does no longer consist of links. 
Links from the Pandoc homepage like https://hackage.haskell.org/package/pandoc/docs/Text-Pandoc-Class.html (found on https://pandoc.org/using-the-pandoc-api.html) are also broken. 
Hence it seems like none of the API documentation is accessible.

**Pandoc version?**
Since 2.17. 
Documentation for earlier versions is still accessible on Hackage by selecting the respective version in the right-hand panel.

**Comment by jgm** [comment]
This happens quite frequently; usually the documentation appears eventually. It's a problem on hackage's side, but their build logs don't show why the build failed...  I can try to manually build and upload the documentation.

**Comment by jgm** [comment]
I tried the manual approach here:
https://hackage.haskell.org/upload
But it failed with
```
haddock: internal error: /Users/jgm/.cabal/store/ghc-9.0.2/Glb-0.10.2-341d2a3c/share/doc/html/doc-index.json: openBinaryFile: does not exist (No such file or directory)
```
I'm not really sure why.  (This doesn't have anything to do with pandoc specifically.)

**Comment by davidpomerenke** [comment]
Thank you for the information, and thank you for trying the manual approach! :)

**Comment by jgm** [comment]
Let's leave it open; I'd still like to find some solution.

**Comment by jgm** [comment]
After trying again a few times, I got it to work -- not sure what changed!

**Comment by jgm** [comment]
I commented out `--enable-doc` but I don't know if that's what did it.
