### ISSUE TITLE
getXdgDirectory:sHGetFolderPath: illegal operation (unsupported operation)

### ISSUE THREAD

**Issue by lucazav** [jgm/pandoc#7842]
I'm running the following SQL script in SQL Server 2017:

```
EXEC sp_execute_external_script
	  @language = N'R'
	, @script = N'system("\"C:/Program Files/RStudio/bin/pandoc/pandoc.exe\" --version")'
```

and I'm getting the following error:

> STDERR message(s) from external script: 
> pandoc.exe: getXdgDirectory:sHGetFolderPath: illegal operation (unsupported operation)

I suppose there is still an issue like [this one](https://github.com/jgm/pandoc/issues/3241), as if I run the system call from the R terminal, I get the correct result:

> system("\"C:/Program Files/RStudio/bin/pandoc/pandoc.exe\" --version")
>
> pandoc.exe 2.14.0.3
> Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.2,
> citeproc 0.4.0.1, ipynb 0.1.0.1
> User data directory: C:\Users\zavarellal\AppData\Roaming\pandoc
> Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
> This is free software; see the source for copying conditions. There is no
> warranty, not even for merchantability or fitness for a particular purpose.

I'm getting the same error even if I invoke the latest version of Pandoc from SQL Server:

> EXEC sp_execute_external_script
> 	  @language = N'R'
> 	, @script = N'system("\"C:/Program Files/Pandoc/pandoc.exe\" --version")'

If I run the same system call from the R terminal all still works like a charm:

> system("\"C:/Program Files/Pandoc/pandoc.exe\" --version")
>
> pandoc.exe 2.17.0.1
> Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.1,
> citeproc 0.6.0.1, ipynb 0.2
> User data directory: C:\Users\zavarellal\AppData\Roaming\pandoc
> Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
> This is free software; see the source for copying conditions. There is no
> warranty, not even for merchantability or fitness for a particular purpose.

**Comment by jgm** [comment]
Sorry, I don't know anything about the environment within sql server.
Is the HOME environment variable undefined, perhaps?

**Comment by lucazav** [comment]
I think that 

> "the Haskel functions (https://hackage.haskell.org/package/directory-1.0.0.3/docs/src/System-Directory.html) and subsequently the win32 libraries that Haskell uses cannot 'find' that directory. This is happening, because the user that run the R Script (thus calling the pandoc.exe) is not a 'real' user. With the SQL Server 2016, introduced trusted launchpad, which decided which worker user (from a worker pool) will execute the R script." (cit. [this issue](https://github.com/jgm/pandoc/issues/3241)).

So, it could be enough to catch the error into the _getXdgDirectory:sHGetFolderPath_ function and return an empty string to show as "User data directory".

**Comment by jgm** [comment]
We wouldn't want to set the user data directory to an empty string.  We could change the type of `defaultUserDataDir` to return Just a directory or Nothing, and then return Nothing when the error is trapped.  It would be a breaking API change.

**Comment by jgm** [comment]
Or, without a breaking API change, we could do the error trapping at the point where we call `defaultUserDataDir`.  That may make better sense.
That happens in three places:

- src/Text/Pandoc/App/CommandLineOptions.hs
- src/Text/Pandoc/App/Opt.hs
- src/Text/Pandoc/App.hs

**Comment by jgm** [comment]
Well, to be honest, since this happens in three places it's probably best to bite the bullet and just change the function.  Then we only have to do the trapping in one place.

**Comment by jgm** [comment]
This change should fix the issue.

**Comment by jgm** [comment]
Testing welcome!

**Comment by jgm** [comment]
Sorry, pushed to wrong branch. Will fix.
