### ISSUE TITLE
New pipe table line width calculations yield some unnatural column widths

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#7847]
The change in pipe table line width detection calculation (https://github.com/jgm/pandoc/commit/79e6f8db13ef8f0db6da8fe4e17b7626fe6ef3e9) can lead to some sub-optional HTML output, especially when there are hyperlinks in one of the columns. For example, consider this markdown:

```markdown
| JATS Element                                                                                    | Description                      |
|-------------------------------------------------------------------------------------------------|----------------------------------|
| [`<given-names>`](https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/given-names.html) | All given names of a person.     |
| [`<contrib>`](https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/contrib.html)         | Information about a contributor. |
```

When rendered to HTML the following `<colgroup>` tag is emitted:

```html
<colgroup>
   <col style="width: 74%" />
   <col style="width: 25%" />
</colgroup>
```

Which results in the following display:

![Screen Shot 2022-01-18 at 12 16 09 PM](https://user-images.githubusercontent.com/104391/149986099-ee0c932d-5498-448e-94a1-99ae38910b55.png)

As the page gets narrower the problem exacerbates:

![Screen Shot 2022-01-18 at 12 18 13 PM](https://user-images.githubusercontent.com/104391/149986384-7ec022cf-8190-4b08-9258-1dca13d17366.png)

**Comment by jgm** [comment]
What authors who use pipe tables have to recognize is that, if their table extends beyond the column set by `--columns` (default 72 I think), then they are in charge of determining the relative widths by adjusting the widths of the `---` separators.  This is much more predictable than before the change, since before the change you couldn't tell from the source whether the table was going to get explicit column widths based on the separators.  So, I still think it's a worthwhile change.  And the solution is quite easy:
```
| JATS Element                                                                                    | Description                      |
|--------------------------|-----------------------------------------------------------------|
| [`<given-names>`](https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/given-names.html) | All given names of a person.     |
| [`<contrib>`](https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/contrib.html)         | Information about a contributor. |
```

**Comment by jjallaire** [comment]
Okay, the new behavior does seem better specified and less surprising. 

My particular concern here is partly driven by the fact that we have a visual editor for Pandoc markdown that edits the JSON representation of the AST and then uses Pandoc to serialize it to and from markdown. So for this scenario the user can't manually tweak the markdown `---` separators. They _can_ however size the columns in the visual editor however the pipe table writer doesn't seem to respect the AST column widths (i.e. it doesn't emit markdown like your example above). 

Consider my original table example (`table.md`) rendered w/ `pipe_tables` and the following Lua filter `colwidths.lua` that forces the column widths to 0.3 and 0.7:

```lua
function Table(tbl)
  tbl = pandoc.utils.to_simple_table(tbl)
  tbl.widths = { 0.3, 0.7 }
  return pandoc.utils.from_simple_table(tbl)
end
```

```bash
$ quarto table.md --lua-filter colwidths.lua --to markdown_strict+pipe_tables
| JATS Element                                                                                    | Description                      |
|-------------------------------------------------------------------------------------------------|----------------------------------|
| [`<given-names>`](https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/given-names.html) | All given names of a person.     |
| [`<contrib>`](https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/contrib.html)         | Information about a contributor. |
```

It would be great if the 0.3 and 0.7 column widths were reflected in the widths of the `---`  separators.

Note that if I do the same render to `grid_tables` the text representation does indeed reflect the column widths:

```bash
 $ pandoc table.md --lua-filter colwidths.lua --to markdown_strict+grid_tables
+--------------------+-------------------------------------------------+
| JATS Element       | Description                                     |
+====================+=================================================+
| [`<gi              | All given names of a person.                    |
| ven-names>`](https |                                                 |
| ://jats.nlm.nih.go |                                                 |
| v/publishing/tag-l |                                                 |
| ibrary/1.2/element |                                                 |
| /given-names.html) |                                                 |
+--------------------+-------------------------------------------------+
| [`<contrib>`](h    | Information about a contributor.                |
| ttps://jats.nlm.ni |                                                 |
| h.gov/publishing/t |                                                 |
| ag-library/1.2/ele |                                                 |
| ment/contrib.html) |                                                 |
+--------------------+-------------------------------------------------+

```

**Comment by jgm** [comment]
Simple tables by definition don't have (nonzero) column widths, so that may be the issue if you're using `from_simple_table`?
I'd have to check on how that works.

**Comment by jgm** [comment]
You're right, the markdown writer doesn't take account of widths in writing pipe tables.  If that changed, would this work for you?

**Comment by jjallaire** [comment]
Yes, if the pipe table writer reflected the column widths in the AST that would indeed fix things!

**Comment by jgm** [comment]
OK, I think this *might* be fixed by the commit I just pushed.
But it's somewhat fiddly getting the widths calculated by the reader and writer to match up (esp. with rounding from non-integers).  Real-world testing will be helpful, but I think this should at least be an improvement.

**Comment by jjallaire** [comment]
Okay, that's excellent! Thank you :-)
