### ISSUE TITLE
Div in a list

### ISSUE THREAD

**Issue by Eloitor** [jgm/pandoc#7852]
**Explain the problem.**

Fenced divs inside a list do not work. For comparison, this works for code blocks. Here's a mwe:

```
1. Test

    ```test
    My test
    ```

    third paragraph
```

Using `pandoc mwe.md` produces

```
<ol type="1">
<li><p>Test</p>
<pre class="test"><code>My test</code></pre>
<p>third paragraph</p></li>
</ol>
```

but the following

```
::: test
div
:::

1. Test

    ::: test
    My test
    :::

    third paragraph
```
produces
```
<div class="test">
<p>div</p>
</div>
<ol type="1">
<li><p>Test</p>
<p>::: test My test :::</p>
<p>third paragraph</p></li>
</ol>
```

Note that the div inside the the list is ignored.

**Pandoc version?**
What version of pandoc are you using, on what OS?
2.14.2 on linux

**Comment by kysko** [comment]
you indented 4 spaces: must be indented properly. From the [User Guide](subsequent paragraphs must be preceded by a blank line and indented to line up with the first non-space content after the list marker) (my emphasis):

> subsequent paragraphs must be preceded by a blank line
> and ***indented to line up with the first non-space content after the list marker***

In your case, 3 spaces:
```
1. Test

   ::: test
   My test
   :::

   third paragraph
```
which produces (in the 2.17.0.1 demo, but was also valid from long before):
```
<ol type="1">
<li><p>Test</p>
<div class="test">
<p>My test</p>
</div>
<p>third paragraph</p></li>
</ol>
```

**Comment by Eloitor** [comment]
Ok thanks, I didn't know that the indent must match the first non-white character. I thought that the amount of indent was irrelevant (after reading the documentation not very carefully)...
