### ISSUE TITLE
[bug] Raw html in native div ::: not working

### ISSUE THREAD

**Issue by gabyx** [jgm/pandoc#7854]
I am using (with v.2.16)

```shell
echo ":::{#special}

<hr class="myruler"/>

:::" | pandoc -f markdown+fenced_divs+fenced_code_attributes+raw_html -t native
```

```shell
[Para [Str ":::",Space,Str "{#special}"]
,RawBlock (Format "html") "<hr/>"
,Para [Str ":::"]]
```

Is that intended (not parsing the ":::"). I don't find anythin in the docs saying otherwise?
Possible bug?

**Comment by gabyx** [comment]
Ok: Definitely a bug:

Using `<hr class="myruler"></hr>` works.

`<hr class="myruler"/>` does not...

**Comment by jgm** [comment]
Can't reproduce.  I'm seeing this:
```
% pandoc -t native
:::{#special}

<hr class="myruler"/>

:::
^D
[ Div
    ( "special" , [] , [] )
    [ RawBlock (Format "html") "<hr class=\"myruler\"/>" ]
]
```

**Comment by tarleb** [comment]
I couldn't reproduce this either, even when using the input and pandoc command given in the report. Could this be a weird interaction with the shell? E.g., the quotes around `myruler` are removed, as they are interpreted as string delimiters by the shell.

**Comment by gabyx** [comment]
I try to investigate further.

**Comment by gabyx** [comment]
Yes, thanks. Sorry for the issue. Its really quoting. I tried to MWE from investigating a similar bug/issue.
I reopen when its maybe clear. This issue is closed so far.
