### ISSUE TITLE
stringify duplicates citation text

### ISSUE THREAD

**Issue by not-my-profile** [jgm/pandoc#7855]
**Explain the problem.**

```
$ printf '[foo bar baz @cite]' | pandoc -L <(echo function Block(x) return pandoc.utils.stringify(x) end)
foo bar baz[foo bar baz @cite]
```

**Pandoc version?**
pandoc 2.17.0.1 on Linux

**Comment by jgm** [comment]
If you do `pandoc -t native`, you'll see that the AST contains
``` haskell
[ Para
    [ Cite
        [ Citation
            { citationId = "cite"
            , citationPrefix =
                [ Str "foo" , Space , Str "bar" , Space , Str "baz" ]
            , citationSuffix = []
            , citationMode = NormalCitation
            , citationNoteNum = 1
            , citationHash = 0
            }
        ]
        [ Str "[foo"
        , Space
        , Str "bar"
        , Space
        , Str "baz"
        , Space
        , Str "@cite]"
        ]
    ]
]
```
in which structure there are actually two inline lists with "foo bar baz..." (one the citationPrefix field, the other the second argument of the Cite constructor).

In fact this has nothing to do with Lua and can be reproduced using Haskell:
```haskell
Prelude Text.Pandoc.Builder Text.Pandoc.Shared Text.Pandoc Data.Text> stringify  [Para [Cite [Citation {citationId = "cite", citationPrefix = [Str "foo",Space,Str "bar"], citationSuffix = [], citationMode = NormalCitation, citationNoteNum = 1, citationHash = 0}] [Str "[foo",Space,Str "bar",Space,Str "@cite]"]]]
"foo bar[foo bar @cite]"
```

The question, then, is whether `stringify` should be modified so it doesn't recurse into the `[Inline]` fields of the `Citation` elements.

**Comment by jgm** [comment]
Actually the work is done by `query` from `T.P.Walk`.
But rather than modifying `query`, we could add `deCitation` to the `walk (deNote . deQuote)` in the def of `stringify`.  `deCitation` would simply null out the first parameter of the `Cite` constructor, leaving only the fallback.
