### ISSUE TITLE
:::notes div works with beamer, need to update documentation

### ISSUE THREAD

**Issue by folofjc** [jgm/pandoc#7856]
**Explain the problem.**
The pandoc manual [here](https://pandoc.org/MANUAL.html#speaker-notes) states that speaker notes work with powerpoint and reveal.js. However, pandoc also translates them into beamer, so should update the manual to show that they work in beamer.

For context, see [this discussion](https://groups.google.com/g/pandoc-discuss/c/mK2k59mtD5k/m/J2gbtmm5AgAJ).

For completeness, what pandoc does is convert the content of the div block into a `\note{....}` command in LaTeX beamer.

**Pandoc version?**
2.11.2 on Ubuntu 20.04 LTS

**Comment by KorigamiK** [comment]
is this already added? how can i enable notes for beamer slides?

**Comment by jgm** [comment]
see the manual under "Speaker notes."

**Comment by KorigamiK** [comment]
> see the manual under "Speaker notes."

I did but couldn't figure out what I'm supposed to do here.

I'm using the latest template from this repo
https://github.com/jgm/pandoc-templates/blob/8bfff6dee20f49102d85c3b6212eece42ffe842b/default.beamer#L4 but it doesn't seem to handle the notes

**Comment by jgm** [comment]
Are you using a recent version of pandoc?
