### ISSUE TITLE
Line breaks inside <code>...</code> elements with HTML autowrap enabled

### ISSUE THREAD

**Issue by mtov** [jgm/pandoc#7858]
In pandoc 2.17.0.1, it seems autowrap is turned on by default for html output.

However, this generates undesirable line breaks when the wrapping occurs inside a `<code>` section used in the middle of a paragraph.

Therefore, I'm wondering if it might be possible to avoid automatic line breaks being inserted between `<code>` tags.

(context: I faced this problem in a markdown document, where in a paragraph I mention: `cd directory-name`. And now pandoc is inserting a line breaking after `cd`).

Thanks!

**Comment by mb21** [comment]
You're only talking about inline code elements, right? There is no `<pre` in the HTML output? If so, that's unlikely to be related to the line-break changes as whitespace is non-semantic in HTML (with the exception of inside `pre` elements).

But you could apply some CSS like:

```css
p code {
  white-space: nowrap;
}
```

**Comment by mtov** [comment]
Thanks for the answer, mb21!

I applied the CSS you suggested and it worked!

(it seems the problem is somehow caused by the CSS framework I´m using: minicss).

**Comment by jgm** [comment]
As it turns out, we have
```
code{white-space: pre-wrap;}
```
in the default template.  So you're right, we need to add some code to ensure that line breaks aren't inserted in HTML code during wrapping.

**Comment by jgm** [comment]
relevant commits
14b8aa8c93766f98a6e0bc9ff04f14962a888f4f
and from the old pandoc-templates repo
9601cc502644458c7ddf71394f8e4be74c464420
```
commit 9601cc502644458c7ddf71394f8e4be74c464420
Author: John MacFarlane <fiddlosopher@gmail.com>
Date:   Fri Jan 4 23:01:14 2013 -0800

    Added css to preserve space in <code> tags.
    
    Thanks to Dirk Laurie.
```
So it seems that this goes back to 2013, prompted by:
https://groups.google.com/g/pandoc-discuss/c/89lwtb8RcRA/m/Pa3YywlCay8J
