### ISSUE TITLE
Inconsistent user directory searches

### ISSUE THREAD

**Issue by evenbrenden** [jgm/pandoc#7861]
Consider the following directory layout:
```
├── datadir
│   └── templates
│       └── my-templates
│           └── my-template.html
│   └── defaults
├── my-template.html
├── my-defaults.yaml
```

Standing at the root of this layout, `pandoc --data-dir=datadir --defaults=../../my-defaults.yaml` will load `my-defaults.yaml` from outside of the user directory `$DATADIR`. This might be the case for other file types too.

On the other hand, `pandoc --data-dir=datadir --template=../../my-template.html` will not load `my-template.html`. Neither will `pandoc --data-dir=datadir --template=my-templates/my-template.html`. Templates loaded from under `$DATADIR` must lie in `$DATADIR/templates` and may not lie in subdirectories of `$DATADIR/templates`. This might be the case for other file types too.

This is inconsistent and pandoc should either:

- Allow any files to be loaded outside of `$DATADIR`.
- Only allow files in a set subdirectory of `$DATADIR` to be loaded.
- Only allow files in subdirectories of a set subdirectory of `$DATADIR` to be loaded.

Here, "a set subdirectory" could be `./`, depending on the file type.

Related: https://github.com/jgm/pandoc/issues/5987

pandoc 2.14.0.3 on NixOS

**Comment by evenbrenden** [comment]
In my opinion, users do not generally want to specify files relative to, but outside of `$DATADIR`, and in case they do it is probably by mistake.

Whatever is decided, remember to update `using-the-pandoc-api.md`.

**Comment by evenbrenden** [comment]
@jgm Thoughts? Just allowing files in a single directory under `$DATADIR` (no subdirectories) is a simple take, usage-wise. Depends on whether or not it makes sense for users to make hierarchies inside those directories for any of the file types.

**Comment by jgm** [comment]
I think it is okay to allow subdirectories inside these directories, but we should disallow escaping above `$DATADIR` via `..`.
This will also require modification to `readDataFile`, I think.
an easy algorithm would be:  if the path is absolute or contains any `..` or `.` path components, then just look in the local directory, and don't worry about looking in datadir.

**Comment by evenbrenden** [comment]
Yeah, we could use `makeCanonical` and then check for leading `..`s. Will need to make an additional change for templates (where `takeFileName` is applied to the path before it's passed to `readFile`).

**Comment by jgm** [comment]
If we fix `readDataFile` then shouldn't that automatically fix the template-fetching code, which calls that function?

**Comment by evenbrenden** [comment]
In `Templates.hs`, the filename is extracted from the path before calling `readDataFile`:
```
-- see #5987 on reason for takeFileName
readDataFile ("templates" </> takeFileName tp
```
So no reading outside of `$DATADIR`, but also no subdirectories allowed. As the comment says, this was introduced because of https://github.com/jgm/pandoc/issues/5987. I'm not sure if there would be a regression if we changed it back.

**Comment by jgm** [comment]
Oh right.  We should probably keep that in the case of templates.

**Comment by evenbrenden** [comment]
I see, so just change `readDataFile` then? The issue was initially about different behavior for templates and other files, but I agree that being able to read outside of the `$DATADIR` is a minor issue in itself.

**Comment by jgm** [comment]
If you think there's a good reason to allow searching of subdirectories of templates when we go to datadir, then you need to dive into #5987 and see if there's another way around the problem we solved there.
My default position would be to stay with the solution we had for that issue, but if there's a better one I'd consider it.

**Comment by evenbrenden** [comment]
Alright. Since this issue is about different behaviour for different files, I'll close it as a non-issue.

I'll look into changing `readDataFile` and `readMetadataFile` as discussed.
