### ISSUE TITLE
Missing beamer frame options

### ISSUE THREAD

**Issue by samcarter** [jgm/pandoc#7869]
The beamer frame options `s` and `squeeze` seem to be missing from this list:  

https://github.com/jgm/pandoc/blob/52b78b10c81e99926d560bc383938006be3b0458/src/Text/Pandoc/Writers/LaTeX.hs#L286-L289

It would also be nice if users could use their custom defined frame options or, if freeform text is not possible, at least add a few spare options like `usera`, `userb`, `userc` ?  (example where this would have been nice to have https://stackoverflow.com/a/58644762/2777074)

**Comment by jgm** [comment]
I have a better idea: I'll allow you to use `frameoptions="..."` to put whatever you want in there.

**Comment by samcarter** [comment]
@jgm Perfect!
