### ISSUE TITLE
Documentation inconsistencies between command line and defaults files

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#7873]
This is a separate issue (as requested by jgm) for a problem mentioned in https://github.com/jgm/pandoc/issues/5990#issuecomment-1013615102:

There are a few inconsistencies between the documentation of command line options and of defaults file entries:

- There are two command line options without apparent defaults file equivalent: `--sandbox` and `--no-check-certificate`.

- There is a command line option whose defaults file equivalent is mentioned, but which is not documented itself: `--trace`. It is listed by `pandoc --help` though.

**Comment by jgm** [comment]
- [ ] add defaults file support for `sandbox` (and document)
- [ ] add defaults file support for `no-check-certificate` (or maybe `check-certificate`) (and document)
- [ ] add documentation for `--trace`
