### ISSUE TITLE
MacOS Install does not appear in Applications

### ISSUE THREAD

**Issue by mikeritter** [jgm/pandoc#7876]
Running BigSur

I downloaded and installed from latest .pkg

Then uninstalled installer

But Pandoc is not in Applications

**Comment by jgm** [comment]
That's right.  It's a command-line tool, not a GUI tool.
See https://pandoc.org/getting-started.html

**Comment by mb21** [comment]
You can try e.g. [PanWriter](https://www.panwriter), a GUI-wrapper I developed...

**Comment by mikeritter** [comment]
`pandoc` is available via terminal with no GUI
