### ISSUE TITLE
Pandoc fails to extract image from docx

### ISSUE THREAD

**Issue by aeb-dev** [jgm/pandoc#7881]
**Explain the problem.**
[Include the exact command line you used and all inputs necessary to reproduce the issue.  Please create as minimal an example as possible, to help the maintainers isolate the problem.  Explain the output you received and how it differs from what you expected.](https://github.com/jgm/pandoc/issues/7511)
This issue persists

Example file 
[test.docx](https://github.com/jgm/pandoc/files/7980522/test.docx)

**Pandoc version?**
What version of pandoc are you using, on what OS?
pandoc.exe 2.17.1.1
Windows 10

**Comment by tarleb** [comment]
I cannot reproduce this with the given example. `pandoc test.docx --extract-media=media` adds the image to folder `media`, as expected.

**Comment by aeb-dev** [comment]
This is the command I am using:

pandoc --toc --self-contained --extract-media ./Docs -s -o README.md -f docx -t gfm+gfm_auto_identifiers ./Docs/test.docx

Command generates the md file without failing or giving any warning etc.

**Comment by tarleb** [comment]
This works for me as well. What is it that you expect to happen, and what is happening instead?

**Comment by jgm** [comment]
Note that `--self-contained` does not work with markdown output (only HTML).

**Comment by aeb-dev** [comment]
@tarleb I do not see the image when I render markdown. Also I do not see any extracted image. I should be able see extracted images under Docs/media

@jgm I removed it does not change the output

**Comment by aeb-dev** [comment]
I made couple of more tests. The first example file is downloaded from web word. I created the same example on desktop word and when I run the same command it works as expected.

Here is file created by desktop version
[test2.docx](https://github.com/jgm/pandoc/files/7981498/test2.docx)

**Comment by aeb-dev** [comment]
Test

<img src="./Docs//media/image.png"
style="width:2.89583in;height:2.51042in" />

test

Pandoc generates the above markdown file for the first example file. Please check the `src` attribute of `img` element

**Comment by jgm** [comment]
With your original test.docx, I just tried this with 2.17.1.1 and got:

```
Test

<img src="./Docs/4403abea626ca1620ed5a0e21c8a2253440788d0.png"
style="width:2.89583in;height:2.51042in" />

test
```
The file is present in Docs.  Everything looks good.
I wonder if you're actually running an old version?

**Comment by aeb-dev** [comment]
This is the output for `pandoc -v`
![image](https://user-images.githubusercontent.com/11612804/152112982-a7b09622-d2fd-4461-aada-9cef53afe390.png)

Why is the file name so different?
Also are you guys on Wİndows?

**Comment by jgm** [comment]
No, I'm not on Windows; this is likely a subtle issue about Windows paths.

**Comment by jgm** [comment]
With your test2.docx, if I just do
```
pandoc test2.docx --extract-media=foo
```
then I get
```
<p>test</p>
<p><img src="fo/media/image1.png"
style="width:2.89583in;height:2.51042in" /></p>
<p>test</p>
```
and we find `image1.png` in `fo/media`.
Can you try with that simple experiment?  I want to rule out issues arising from the fact that the source file is in a subdirectory.  (That is likely why we got the SHA1 hash above; pandoc tries to preserve original path names when extracting media, but when it encounters `..` it does not do this for security reasons.)

**Comment by aeb-dev** [comment]
test2.docx works correct already on me whether subdirectory or not. I tried test.docx with the following command
```
pandoc test.docx --extract-media=foo
```

I get the following output:
```
<p>Test</p>
<p><img src="foo//media/image.png"
style="width:2.89583in;height:2.51042in" /></p>
<p>test</p>
```

**Comment by jgm** [comment]
Oh, sorry, I misunderstood.  I understand now that your real issue is with test.docx.

**Comment by aeb-dev** [comment]
No worries. I am not a native speaker so it could be my writing :)

Do you need any information from me to identify the problem?

My guess is `foo//media` that double slash is the problem

**Comment by jgm** [comment]
I need to get myself a Windows VM to debug this on.

**Comment by jgm** [comment]
I just pushed a change that may fix the double `/`.  If you could test, that would be great. If you don't have a Haskell toolchain, you can wait for the Windows nightly to be built.

**Comment by aeb-dev** [comment]
I can test on my computer with nightly but your last commit failed

**Comment by jgm** [comment]
I noticed something about test.docx and test2.docx.
In test.docx, in word/_rels/document.xml.rels  we have
```
<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="/media/image.png" Id="R7ec72d0878e54e71" />
```
Note the leading `/` on the Target.
In test2.docx we have a relative path instead, `"media/image1.png"`.
The leading `/` is the reason I'm getting a SHA1 hash filename on recent pandoc: pandoc is interpreting it as an absolute path.  It's probably also the reason for the doubled `//`.
So I think my last commit was irrelevant, and I'll revert it.

**Comment by jgm** [comment]
This answers the question why Windows pandoc isn't using the SHA1 hash.
```
Prelude System.FilePath.Windows> isRelative "/media/image.png"
True
Prelude System.FilePath.Posix> isRelative "/media/image.png"
False
```

**Comment by aeb-dev** [comment]
That leading / was my initial thought as well. That is why I referred to this issue https://github.com/jgm/pandoc/issues/7511

```
Prelude System.FilePath.Windows> isRelative "/media/image.png"
True
```
This is also very strange. As a person who develops on Windows. I am pretty sure that, that is not relative.

**Comment by jgm** [comment]
Well I think I can see how to fix this now!

**Comment by jgm** [comment]
OK, this still needs testing on your end, but I suspect it will fix the problem.

**Comment by aeb-dev** [comment]
It is working.

As a side not, when I run `pandoc test.docx --extract-media=foo` command, normally it was creating a `media` folder automatically under `foo`. Currently it does not do this. It does not matter for me, just fyi.

You can see the behavior difference by testing test.docx and test2.docx. test.docx puts images under foo, test2.docx puts images under foo/media

**Comment by jgm** [comment]
> normally it was creating a media folder automatically under foo. Currently it does not do this. It does not matter for me, just fyi.

When we use a path based on a sha1 hash, as in this case, it won't have a subdirectory.  You only get the subdirectory when we're preserving the original path in the docx container. So this is expected.  Glad it's working!
