### ISSUE TITLE
Spurious paragraph breaks before and after LaTeX {subequations} maths environment

### ISSUE THREAD

**Issue by krivit** [jgm/pandoc#7883]
I had an issue in Rmarkdown which I ultimately tracked down to Pandoc.

# To reproduce

1. Construct the following Markdown file, e.g., `testfile.md`:
    ```md
    Text before equations.
    \begin{subequations}
    \begin{align}
    a\\
    b
    \end{align}
    \end{subequations}
    Text after equations.
    
    Text before equations.
    \begin{align}
    a\\
    b
    \end{align}
    Text after equations.
    ```
2. Run `pandoc testfile.md -o testfile.tex`.

# Expected result

The following LaTeX file:
```tex
Text before equations. \begin{subequations}
\begin{align}
a\\
b
\end{align}
\end{subequations} Text after equations.

Text before equations. \begin{align}
a\\
b
\end{align} Text after equations.
```
# Actual result

```tex
Text before equations.

\begin{subequations}
\begin{align}
a\\
b
\end{align}
\end{subequations}

Text after equations.

Text before equations. \begin{align}
a\\
b
\end{align} Text after equations.
```
Thus, spurious paragraph breaks are created before `\begin{subequations}` and after `\end{subequations}` but not so with the `align` environment.

# Workaround

For now, this can be worked around by replacing `\begin{subequations}` and `\end{subequations}` with LaTeX macros:
```tex
\def\bse{\begin{subequations}}
\def\ese{\end{subequations}}
```

# Notes

From keyword searching through the source code, I suspect that at least a part of the fix would be to add `"subequations"` to the list below. However, I know neither Haskell nor Pandoc's internals, so I don't know what else is involved.

https://github.com/jgm/pandoc/blob/a6fa3df1146f7aee4e3bfa4cf506ab44e38ecb35/src/Text/Pandoc/Writers/HTML.hs#L1652-L1679

**Comment by jgm** [comment]
Right, currently pandoc doesn't know subequations.
What package defines this?

**Comment by krivit** [comment]
The package `amsmath` defines it and others. The [Short Math Guide](http://tug.ctan.org/info/short-math-guide/short-math-guide.pdf) is a good reference.
