### ISSUE TITLE
Issue when changing webtex url to new url

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#7888]
It seems there is an issue with some of the url that can be used with `webtex`
Following the doc in https://editor.codecogs.com/docs/ there are several formats that can be used and it seems the url is now of the format `https://latex.codecogs.com /type.format?LaTeX` where 
* where type is a graphical format like `png` or `svg`
* format defined how the rendered image is downloaded like `image` or `json`
* and LaTeX is LaTeX markup that is used to define an equation.

However, those url does not seem to work

````sh
$ pandoc -t html --webtex https://latex.codecogs.com/png.image?
pandoc: Cannot decode byte '\x89': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
$pandoc -t html --webtex https://latex.codecogs.com/svg.image?
pandoc: Cannot decode byte '\x89': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
$ pandoc -t html --webtex https://latex.codecogs.com/gif.image?
pandoc: Cannot decode byte '\x89': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
````

Pandoc is using url `https://latex.codecogs.com/png.latex?` and this one works.  But [Manual](https://pandoc.org/MANUAL.html#math-rendering-in-html) documents that svg url can be used `https://latex.codecogs.com/svg.latex?` but same issue

````sh
$ pandoc -t html --webtex https://latex.codecogs.com/svg.latex?
pandoc: Cannot decode byte '\x89': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
````

is `https://latex.codecogs.com/png.latex` a special service only supported with Pandoc ? 

Seems like an issue though as other url should be supported from what I understand.

**Comment by cderv** [comment]
Ok sorry. I did not tested with the last pandoc - issue is different now  

````sh
pandoc -t html --webtex https://latex.codecogs.com/svg.latex?
[WARNING] https://latex.codecogs.com/svg.latex? is not UTF-8 encoded: falling back to latin1.
‰PNG  IHDRzþ9:
pHYs
    
     ÒÝ~üËIDATh?íZ}hUev;ÛZwk^¯Ê¦C-KB04ØFD+¨Ü…¡$b)××,A§°™±X£,ûK••A*Âœúc²´%Ì¥l:çÚ½w÷Ëí~toüž»÷xî½gÛ{.ÇÚýøÁáœ{žó&gt;ïóù{ßs¶¼Áû"ZE9d2Æ”É$ŸÈ¥9£qÒ’íÈ(Z?+£Ù?Œ‚¯½‘Æê?b—r?%È%:K?R¢#×.Òè¦&gt;&amp;~èÈö¦”TŒtnŽ&amp;ÿÎ×Á›¨üì:Ê+¶e[ìÒ
†;:Ðó?šd 2q_è×Î'ô ÿS…t¢Ý-õ¼
                            „þJNLãkRº‚GúcÆoØÃÝ]xÿ£IÏ
ÀÊ’¥Ümö¯›¹óE€8HXfÝVÃM¤ÿÑº§É²ÐJó??¢k
T[®«áMRV–±^è—Æ¹÷¿Có&gt;éŒ1ÜB+¹öì%ëæ]TÚú,kìgk96·ÛÅãFj×Ó-soWÙÍ ;®h½çhÁáïy\¢ÿF!•èð…ŸÉ×ztÆç‚Ç/I½n
ê^ä8O‡—F·nNz¦hÍ
žùEÒ0pëƒ51]÷®æsè?^Uænnçb²5ïž’’µÔ]òÂ[;˜r`d??–ëù·¹ëP4(âÙˆ?Õ¾N
À¹+öåI÷AïþCmR®‚¾@OJÕR–WÆÉþqzøŒþÖg(tèrÐ¦ºË¿§ŠÏ'»ù¬-Ø€n
                                                         õ&amp;ÉÄF‹&amp;÷`(KiìÛ‚–‰T?b&gt;Ø©e³1m¢Ñ™c¯·êÊ°n¢Ûô€éÓ½n‰5…’÷"^ßQúâKL?¼yÑÐ™,@Ç(
wÛÝÚ5G^‰M]
             ñ;¶¶ªÝÊ‹U)(·è™Õ\øCK«Éb/Qe·­«ãÇÒƒ?•H
````

but it seems that it is because the `=` is not set after `--webtex`. Adding makes it work 
````sh
$ pandoc -t html --webtex=https://latex.codecogs.com/svg.image?
$$
x + y
$$
<p><img style="vertical-align:middle"
src="https://latex.codecogs.com/svg.image?%5Cdisplaystyle%20%0Ax%20%2B%20y%0A"
alt="
x + y
" title="
x + y
" class="math display" /></p>
````

It seems the `=` is necessary with this argument and I just copy pasted the example in https://pandoc.org/MANUAL.html#math-rendering-in-html which does not have a `=`. 

I was under the impression that `=` was not necessary between `--args value` for arguments in Pandoc CLI but it seems math method requires it. 

So problably no issue here after all. 

Looking into this however shows that Pandoc is using a special undocumented url ending in `.latex` where it seems other url are now used. 

anyway, feel free to close. Sorry for the noise

**Comment by jgm** [comment]
Use this form:
```
pandoc -t html --webtex='https://latex.codecogs.com/png.image?'
```
Since `--webtex` takes an *optional* argument, you need the `=`.  Also, quote it so your shell doesn't try to interpret `?` as a wildcard.

**Comment by cderv** [comment]
> takes an optional argument, you need the =.

That was the part I was missing. Thank you. 

> Also, quote it so your shell doesn't try to interpret ? as a wildcard.

Thanks for the advice. I modified it.
