### ISSUE TITLE
Cannot create PDF when using a custom writer

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#7898]
Pandoc checks that the target format matches the chosen PDF generator and refuses to produce a PDF if they mismatch. A custom writer will never match, even if the writer produces a variant of the supported format.

Possible solutions:

1. Disable format checking when going through a custom writer. This seems like the easiest solution.
2. Expose `makePDF` to Lua so writers can do the conversion themselves. It would require significantly more effort, but may be the cleaner solution.
3. Leave as is, and document the need for a  separate compilation steps when going through custom writers. Inconvenient, but probably still okay.

Not sure what's best here.

**Comment by jgm** [comment]
Not sure either.  I think I'd be okay with 1 though, and it's pretty easy.
