### ISSUE TITLE
[Latex] \today does not do anything

### ISSUE THREAD

**Issue by MuntashirAkon** [jgm/pandoc#7905]
**Explain the problem.**
Latex has a special `\today` command to print today's date, and it is not outputting anything in the HTML format. This command can be very useful for serving documentations via a CI, for example.

Current workaround is to create a placeholder for a date and replace it with the date generated by other means (e.g. UNIX `date`).

**Pandoc version?**
```
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
```

**Comment by jgm** [comment]
This is by design.  Pandoc allows you to include raw LaTeX in markdown, but it gets passed through only to LaTeX, not to HTML, which wouldn't know what to do with it.
You could use a Lua filter to find this bit of raw HTML in the AST and replace it with the date.

**Comment by jgm** [comment]
Sorry, I assumed your source was markdown, not LaTeX; you didn't say.
If the source is LaTeX, then we could consider parsing `\today` as a date.

**Comment by jgm** [comment]
```
 % pandoc -f latex -t native -s
\date{\today}
Pandoc
  Meta { unMeta = fromList [ ( "date" , MetaInlines [] ) ] }
  []

% pandoc -f latex+raw_tex -t native -s
\date{\today}
Pandoc
  Meta
    { unMeta =
        fromList
          [ ( "date"
            , MetaInlines [ RawInline (Format "latex") "\\today" ]
            )
          ]
    }
  []
```

**Comment by jgm** [comment]
We could think about changing the first output above to
```
Pandoc
  Meta { unMeta = fromList [ ( "date" , MetaInlines [Str "2014-04-04"] ) ] }
  []
```
Of course there's the question what date format to use.  We don't have awareness of localized date formats, so it's probably best just to use something like YYYY-mm-dd, even though this is a bit different from what you'd get in LaTeX.
We have a function in PandocMonad to getZonedTime, so this is feasible.
We could keep the second behavior above in the case where the `raw_tex` extension is enabled.

**Comment by MuntashirAkon** [comment]
I think Latex uses dots rather than hyphens. But it's still better than producing nothing at all.

**Comment by jgm** [comment]
The format LaTeX uses depends on your locale.  When I use `\today` I get "February 10, 2022".  Duplicating this locale-dependent behavior is probably too much trouble, though.

**Comment by tarleb** [comment]
Aside: there's an example in the Lua filters docs that adds a (localized) date: https://pandoc.org/lua-filters.html#setting-the-date-in-the-metadata
