### ISSUE TITLE
[HTML] Add option to display SVG images as an object rather than an image

### ISSUE THREAD

**Issue by MuntashirAkon** [jgm/pandoc#7906]
**Describe your proposed improvement and the problem it solves.**
Currently SVG images are loaded using the `img` tag which does not let users select the contents of the image. Consider adding the option to display them via the `object` tag so that they can be selected.

**Describe alternatives you've considered.**
Used a script to replace `<img src=` with `<object data=`.

**Comment by jgm** [comment]
In addition to this change you'd also need `type="svg+xml"` on the object element, correct?

I tried it in Safari and still could not select parts of the image (if that's what you mean).

**Comment by jgm** [comment]
Ah, maybe by "select" you mean e.g. via JavaScript?

**Comment by jgm** [comment]
Note that if you're targeting HTML, you can always just include the raw `<object data=...>` in your markdown source.
If your source isn't markdown, it's possible to use a filter to change certain Images into RawBlocks.

**Comment by MuntashirAkon** [comment]
> In addition to this change you'd also need `type="svg+xml"` on the object element, correct?

Yes. But only the `data` field is mandatory, I believe.

> I tried it in Safari and still could not select parts of the image (if that's what you mean).

Say you have created a SVG file containing some texts and you want your users to select the texts (similar to what we can do in a Latex PDF) or even interact with it like it is a part of the HTML file (SVG supports hyperlinks, for example), you either directly include the SVG file in your file or load it as an `object`. If you use the `img` tag, you can only view the contents and not interact with it. I apologise if I couldn't explain it earlier.

All in all, you can implement this feature in two ways:
1. Load the SVG file via `object`. The problem with this approach is that you cannot forward links to the HTML file where it is being loaded. Say you wrote an article and wanted to refer to a section of the article in an SVG file (via the `#` anchors), it wouldn't work this way.
2. Paste the whole content of the SVG file instead of just loading it via `object`. The situation above works in this case.

I think both have valid use-cases and should not be very difficult to implement (but hey, that's only my speculations).

**Comment by mb21** [comment]
yes, the output you want for 1. is:

```html
<object data="myfile.svg" type="image/svg+xml"></object>
```

Currently, for either 1. or 2. you can write [raw HTML](https://pandoc.org/MANUAL.html#raw-htmltex) inside your markdown, or write a [lua filter](https://pandoc.org/lua-filters.html) to change the document AST.

If this a popular request, we could add an extension to the HTML writer...

**Comment by jgm** [comment]
I assume there are reasons not to *always* use `<object>` instead of `<img>` for svg?

**Comment by mb21** [comment]
> I assume there are reasons not to _always_ use `<object>` instead of `<img>` for svg?

for one, you cannot add an `alt` text in `<object`. for another, I think the [sizing of the element](https://stackoverflow.com/questions/644896/how-do-i-scale-a-stubborn-svg-embedded-with-the-object-tag) behaves differently.

**Comment by jgm** [comment]
At this point I'm not sure I'd recommend any change to pandoc.

- It's already possible to include raw `<object>` tags in markdown and pass them through to HTML.
- One can also use a simple filter to change images with svg src to raw html `<object>` elements.

One could envision an extension or something that globally changes the way svgs are handled, but that adds complexity to the code to allow us to do something we can already do fairly simply...

**Comment by tarleb** [comment]
> I assume there are reasons not to _always_ use `<object>` instead of `<img>` for svg?

As noted by @MuntashirAkon, including an SVG as `object` will run the embedded scripts. There are security implications to this, which is why I'd strongly prefer to stick to `<img>`.

**Comment by MuntashirAkon** [comment]
> for one, you cannot add an `alt` text in `<object`. for another, I think the [sizing of the element](https://stackoverflow.com/questions/644896/how-do-i-scale-a-stubborn-svg-embedded-with-the-object-tag) behaves differently.

Scaling issue could be handled by the issuer. Use of `img` and `object` has far reaching consequences in mobile devices with SVG in `img` not being displayed at all. While it may be possible to create a Lua script (because Markdown is not an option) to do exactly what I want, this also raises the question of the platform-independence of Pandoc. Example:

| SVG in `img` tag not working in Android WebView |  SVG in `object` tag works
| --- | ---
| ![Screenshot_20220211-001201_AM_Debug](https://user-images.githubusercontent.com/8176128/153470700-05fbdf14-3ae4-4431-b9cd-16a380aacf76.png) | ![Screenshot_20220211-002537_AM_Debug](https://user-images.githubusercontent.com/8176128/153473000-f3d649de-6050-416b-bf6c-18ef1ab2598d.png)

Anyway, since I've apparently learned Lua and implemented a Lua filter within 2 hours to handle my case, I shall not proceed further on this. Thanks for pointing me to the lua-filter page though, it was very helpful. But I wish there are more examples on Inlines present there because I haven't understand how to add a `List` of inlines as the children of another inline.

**Comment by mb21** [comment]
regarding the Android screenshot: either the path to the image is wrong, or it's a reaaaaly old version: https://caniuse.com/svg-img

**Comment by MuntashirAkon** [comment]
> regarding the Android screenshot: either the path to the image is wrong, or it's a reaaaaly old version: https://caniuse.com/svg-img

It's the Android WebView (as mentioned just above the screenshots), not Chromium/GeckoView. WebView implementation is similar to Chromium's with some limitations such as above.

Anyway, I have modified `Image` to return a `object` instead of `img` using a Lua script like you have suggested earlier in order to meet my needs. So, I see no point of going further with this.
