### ISSUE TITLE
Can't extend CSS for body element in my document.

### ISSUE THREAD

**Issue by awa5114** [jgm/pandoc#7911]
**Explain the problem.**
The [docs](https://pandoc.org/MANUAL.html#variables-for-html) show the following example for extending CSS for one document:
```
---
header-includes: |
  <style>
  blockquote {
    font-style: italic;
  }
  tr.even {
    background-color: #f0f0f0;
  }
  td, th {
    padding: 0.5em 2em 0.5em 0.5em;
  }
  tbody {
    border-bottom: none;
  }
  </style>
---
```

Since I would like to modify the `max-width` parameter for my body element, I tried the following:

```
---
title: Notes
fontsize: 12pt
header-includes: |
<style>body {max-width: 70em}<\style>
---
```

This had no impact on the `max-width` and my body element still shows `36em` in chrome browser.

**Pandoc version?**
What version of pandoc are you using, on what OS?
2.16.2 on Windows 10

**Comment by jgm** [comment]
It should work if you follow the formatting of the example:
```
---
header-includes: |
  <style>
  body {
     max-width: 72em;
  }
  </style>
---
```
Note the indentation.
