### ISSUE TITLE
single column Markdown pipe table rendered by GFM and PHP fails under Pandoc

### ISSUE THREAD

**Issue by vassudanagunta** [jgm/pandoc#7919]
**Explain the problem.**

Pandoc fails to render the following markdown as a table: 

~~~~~~~
single column table | 
------------------- | 
item 1              |
item 2              |
~~~~~~~

As can be seen directly below as well as [in Babelmark 3](https://babelmark.github.io/?text=single+column+table+%7C+%0A-------------------+%7C+%0Aitem+1++++++++++++++%7C%0Aitem+2++++++++++++++%7C), this is rendered as a table by GFM, PHP Markdown Extra, and many others.

> single column table | 
> ------------------- | 
> item 1              |
> item 2              |

Pandoc *does* render the following form as a table:

~~~~~~~~
| single column table 
| ------------------- 
| item 1             
| item 2              
~~~~~~~~

**Pandoc version?**
Pandoc 2.17.1, the current version on pandoc.org/try

**Comment by jgm** [comment]
I see this in the code of the Markdown reader:
```hs
  -- surrounding pipes needed for a one-column table:
  guard $ not (length cells == 1 && not openPipe)
```
My guess is that this was put here for a reason!  But what?

**Comment by mb21** [comment]
@vassudanagunta this should be fixed when using `pandoc -f gfm` in the next pandoc release...

**Comment by vassudanagunta** [comment]
It wasn't affecting me directly but I thought you'd want to fix this. I only discovered it as I run the same input cases through Pandoc, GFM and my project to test compatibility.

@jgm @mb21 would a report of significant behavioral differences between Pandoc and GFM be useful to you?

**Comment by mb21** [comment]
The long-term plan is for what is currently `commonmark_x` to replace the current implementation of pandoc's markdown...

perhaps we should mention that in https://pandoc.org/MANUAL.html#markdown-variants ?

**Comment by jgm** [comment]
> @jgm @mb21 would a report of significant behavioral differences between Pandoc and GFM be useful to you?

Sure, but be sure you're comparing `pandoc -f gfm` behavior, not `pandoc -f markdown` which uses a different parser.

**Comment by vassudanagunta** [comment]
OK, sounds like you're not interested in differences between `-f markdown` and GFM, but only those between `-f gfm` and GFM. Makes sense. 

But what about `commonmark_x`?  Is it essentially CommonMark + the same extensions used for `-f markdown`, making it a strict superset of CommonMark but not of GFM? Some of the GFM-overlapping extensions (e.g. pipe tables) behave differently from GFM, and in my opinion better than GFM, so I'm not suggesting being a superset of GFM is the best thing.

If there's no quick answer and this should be a discussion, I can move this to the Pandoc forum.

**Comment by jgm** [comment]
`commonmark_x` is a superset of GFM in our implementation.

**Comment by vassudanagunta** [comment]
> `commonmark_x` is a superset of GFM in our implementation.

I couldn't find that documented anywhere. I think that's important to make clear, both for user expectations as well as to gate bug reports, whether it is "contractually" a strict superset. I don't know if I should be filling bug reports for differences in `pipe_table` behavior, for example.

**Comment by jgm** [comment]
Well, I spoke too soon.  It's not quite a superset, because in `gfm` 'autolink_bare_uris` is enabled, but `commonmark_x` doesn't turn this on by default.  Both `gfm` and `commonmark_x` are defined as a set of extensions over `commonmark`; you can see which extensions are enabled by doing:
```
pandoc --list-extensions=gfm
pandoc --list-extensions=commonmark_x
```
