### ISSUE TITLE
Markdown writer produces numeric identifiers

### ISSUE THREAD

**Issue by dsanson** [jgm/pandoc#7920]
As I understand it, pandoc's markdown requires any id specified using the `[]{#id}` syntax to start with a letter. So this is not valid markdown:

    [example]{#1}

But this is valid markdown:
 
    [example]{id=1}
 
The markdown reader respects this restriction:

    pandoc -f markdown -t html
    [example]{#1}^D
    <p>[example]{#1}</p>

    pandoc -f markdown -t html
    [example]{id=1}^D
    <p><span id="1">example</span></p>  

But the markdown writer does not:

    pandoc -f html -t markdown
    <p><span id="1">example</span></p>^D                                                      
    [example]{#1}

As a result, the markdown writer generates markdown that the markdown reader refuses to process correctly:
 
    pandoc -f markdown -t markdown
    []{id=1}^D
    []{#1}

See: <https://pandoc.org/try/?text=%5B%5D%7Bid%3D1%7D&from=markdown&to=markdown&standalone=0>

    pandoc -f markdown -t markdown
    []{#1}^D
    \[\]{#1}

See: <https://pandoc.org/try/?text=%5B%5D%7B%231%7D&from=markdown&to=markdown&standalone=0>

I would just avoid numeric ids, but I ran into this when using the track-changes feature. When generating markdown from docx using track-changes, the markdown writer generates comment spans with numeric ids using the `[]{id=1}` syntax. But applying `pandoc -f markdown -t markdown` then breaks all the comments, by transforming them into the `[]{#1}` syntax.

**Comment by dsanson** [comment]
I'm not sure what the writer should do.

I see now that behind the scenes, it's the docx *reader* that is doing something funky: it puts the "id" into the AST as an attribute instead of as the element id. That's why the markdown writer, when converting from docx, uses the attribute format (`[]{id=0}`) instead of the id format (`[]{#0}`). But then if that markdown is fed back to the markdown *reader*, it recognizes the 'id' as the element id. So it is only at that stage that we've got, in the AST, an element with a numeric id. So that's the stage where the writer needs to decide what to do with a numeric id.

So I guess one proposal would be that readers, when they notice that an id is numeric, treat it as an attribute rather than an element id. That way, writers would never need to process an AST element with a numeric id. But really, at that point, you'd just be codifying a runaround to the policy that ids can't be numeric.

So yeah, I don't know!

(Happily, it is easy enough to "fix" broken markdown with something like `sed 's/{#/{id=/g'`.)

**Comment by jgm** [comment]
A case could be made for relaxing the restriction on identifiers (must start with a letter). XML identifiers need to start with a letter, but HTML5 identifiers do not, nor do LaTeX labels (I think).

**Comment by reagle** [comment]
Does pandoc have an obligation to produce well-formed/valid output? If so, might it change the ID based on the format (e.g., prepending a letter to an ID for XML)? Or ought it provide a warning on the terminal? Or is it simply user beware? Personally, I'm okay to see this restriction relaxed as I rarely use an XML-based format.

**Comment by reagle** [comment]
The break that @dsanson notes when round-tripping content is irritating, so I'm in favor of relaxing the constraint on reading markdown to the extent that the incongruity is resolved. 

I'm not sure about the XML writers though. You could:
1. generate ill-formed XML with bad IDs, or
2. fix the IDs by dropping first numerical characters as is done with `auto-identifiers`.

I slightly lean toward option-2, though option-1 is "least surprising" in that things an XML parser should warn/error and things are not quietly changed.

**Comment by jgm** [comment]
Note also that commonmark_x already allows identifiers to start with a number.

**Comment by jgm** [comment]
OK, removing the restriction in the reader.
