### ISSUE TITLE
Include part of `highlighting-macros` code in template

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#7923]
While trying to customize the styling of code blocks in LaTeX output, I was at first extremely confused where the `Highlighting` and `Shaded` environments come from. I then found that there is LaTeX code which is not explicitly in the template, but inserted via a template variable `highlighting-macros`. E.g. with `highlight-style: tango`, this variable expands to

````latex
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
...
````

followed by a long list of further `\newcommand{\XyzTok}`. This implementation strikes me as contrary to the idea of user-customizable templates.

Of course, full "templatization" is hard in this case due to the complexity of the information transferred from the skylighting library to the LaTeX code; it would need variables `highlighting-shadecolor`, `highlighting-alertcolor`, `highlighting-alertbold`, `highlighting-alertitalic`,  `highlighting-annotationcolor`, `highlighting-annotationbold`, `highlighting-annotationtitalic`, etc. etc.

I therefore propose a semi-templatization, which puts into the template the code

````latex
$if(highlighting-macros)$
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
$highlighting-macros$
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
$endif$
````

where `highlighting-macros` now only expands to those LaTeX commands which are different between highlight styles:

````latex
\definecolor{shadecolor}{RGB}{248,248,248}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
...
````

This way, the implementation becomes a bit more transparent (possibly sparing others my confusion), and at least part of the code becomes customizable (e.g. by including `fontsize=\small` among the parameters of the `Highlighting` definition).

On a related note, I'm wondering why this code uses the `color` package, while in other places in the default template the `xcolor` package is used.

**Comment by jgm** [comment]
The chunk of latex that is inserted is produced by the skylighting library, and intended to include everything you need.  So splitting it this way would be awkward.  And I actually don't see the problem.

If you want a smaller font size, I think this customization is achievable using etoolbox commands.  (AtBeginEnvironment, etc.)

As for xcolor vs color, I'm not sure.  Maybe we should change this in skylighting?  I don't have a good sense for the difference between these.
