### ISSUE TITLE
request for an option for ignoring math equations in markdown

### ISSUE THREAD

**Issue by anti-destiny** [jgm/pandoc#7925]
**Describe your proposed improvement and the problem it solves.**
When export a markdown file with equations to HTML  without `--mathjax`, pandoc produces warning information like this 
```
[WARNING] Could not convert TeX math '...
...
...
...
  ', rendering as TeX
```
and it continues to process the equations in a weird way. 
![image](https://user-images.githubusercontent.com/24856363/154424916-326d15ca-0f7c-4d2b-9a9d-381644e21eff.png)

However, what I actually want is to keep the equations unchanged, so I can do some post-process on them. 

So, I suggest adding an option like "--ignore-math" or "--ignore-latex" when exporting HTML files for pandoc. 

**Describe alternatives you've considered.**
I have not found an alternative solution yet.

**Comment by tarleb** [comment]
Possible alternative: use a [Lua filter](https://pandoc.org/lua-filters.html) to handle the math elements the way you want. Example (untested):

``` lua
function Math (m)
  return pandoc.RawInline('html', m.text)
end
```

Save the above to a file name `raw-math.lua` and pass that file to pandoc via the `--lua-filter` command line parameter.

**Comment by jgm** [comment]
Why not just use `--mathjax`?  The tex will be passed through unchanged, though it will be put in spans and LaTeX delimiters will be used instead of `$`.
If you don't want the mathjax script to be inserted in the header, you can add `-V math=''` to the command line.

**Comment by anti-destiny** [comment]
> Why not just use `--mathjax`? The tex will be passed through unchanged, though it will be put in spans and LaTeX delimiters will be used instead of `$`. If you don't want the mathjax script to be inserted in the header, you can add `-V math=''` to the command line.

This solution exactly meets my requirements. 

> Possible alternative: use a [Lua filter](https://pandoc.org/lua-filters.html) to handle the math elements the way you want. Example (untested):
> 
> ```lua
> function Math (m)
>   return pandoc.RawInline('html', m.text)
> end
> ```
> 
> Save the above to a file name `raw-math.lua` and pass that file to pandoc via the `--lua-filter` command line parameter.

I have not tried lua filters yet. But I think this solution is also promising. 

Thank you for your help!
