### ISSUE TITLE
Blank PDF document generated for Chinese Markdown

### ISSUE THREAD

**Issue by ghost** [jgm/pandoc#793]
I'm trying to generate a PDF document from a markdown formatted text in UTF-8 Chinese:

```
# 中國的故事

網站為澳大利亞國立大學的中華全球研究中心主辦。其宗旨為：瞭解、蒐羅、分析和傳播關於中國種種有份量的敘述。凡是有建樹和研究價值的資訊和闡述，此網站將對之力求兼容並包。

    無論源於黨政官方的、大眾媒體的、民間大眾的、思想知識界的、網民微博族的、甚至不入主流的敘述，均可在我們《中國的故事》適當地亮相。
```

I run the command `pandoc -o test.pdf test.markdown` and get a blank PDF document as a result.

**Comment by tarvos21** [comment]
`-V mainfont='Adobe Ming Std` does not works, too. I have installed MacTex, where can I find the fonts that are supported by Pandoc on Mac?
Thanks a lot!

**Comment by tarvos21** [comment]
Done.
I open the "Font Book" app on Mac, and search for "Chinese", there are some fonts available in the macOS system that I can add to the command.
Great, thanks for creating pandoc!

**Comment by jdhao** [comment]
If you are using Windows or Linux, this [post](https://jdhao.github.io/2017/05/13/guide-on-how-to-use-chinese-with-matplotlib/) will help you to find Chinese font in your system.
