### ISSUE TITLE
Enforce compilation against Lua 5.4

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#7931]
Package builders currently have the choice between compiling pandoc against Lua 5.3 (by constraining hslua to version 2.1) or against the new Lua 5.4.

It might make sense at some point in time to ensure that pandoc always ships with Lua 5.4. The step should happen no sooner that Apr 21, which is when the next Ubuntu LTS will be released. Ubuntu "jammy" will come with Lua 5.4.

See also the discussion #7929.

**Comment by jgm** [comment]
It would be nice if `pandoc --version` printed the Lua version packaged with hslua, in addition to the hslua version. Is there a way to query this programatically?

**Comment by alerque** [comment]
I've done it in the past by looking at `package.path` (or more specifically noticing by filter dependencies dies without being able to `require()` something and that shows the `package.path` used. The Lua version is in there. But I would hope there was an easier way, and yes having `--version` print it out would be great.

**Comment by tarleb** [comment]
I think this should do (untested):

```haskell
lua_version <- HsLua.run (HsLua.openlibs *> HsLua.getglobal "_VERSION" *> HsLua.peek HsLua.top)
```

The version is available as a C macro in `lua.h`, so there should be a simpler way. I'm creating an issue for that in HsLua.

**Comment by jgm** [comment]
I realize that I built the release binaries for 2.18 with default flags, hence with Lua 5.4.
So we jumped the gun a bit, but it's close enough to April 21 that I think it's fine.
