### ISSUE TITLE
[LaTeX] "%" in the \verb comand are interpreted as comments.

### ISSUE THREAD

**Issue by sumi35** [jgm/pandoc#7939]
**problem**
This problem occurs when converting LaTeX.
If I convert the following text, the "%" in the \verb command are interpreted as a comment.

`\hbox{\verb|\begin{minipage}[t]%|}`

How to execute
`pandoc --from=latex --to=json "sample.tex" `

**Comment by mb21** [comment]
Have you tried in the latest pandoc version? e.g. https://pandoc.org/try/?text=%5Chbox%7B%5Cverb%7C%5Cbegin%7Bminipage%7D%5Bt%5D%25%7C%7D&from=latex&to=native&standalone=0

**Comment by jgm** [comment]
This appears to work correctly in recent versions; you just need to upgrade.

**Comment by sumi35** [comment]
I updated to version 12.17.1.1, but it did not solve the problem.
I will share the file that I actually used for the conversion.

I tried to convert, but got the following error.
```
pandoc --from=latex --to=json "jsample.tex" 
Error at "jsample.tex" (line 8, column 2):
unexpected end of input
```

[jsample.zip](https://github.com/jgm/pandoc/files/8150913/jsample.zip)

**Comment by jgm** [comment]
OK, what's going on in your document is that it first defines `|` as `\verb|`:
```
\def\|{\verb|}
```
so that the `%` in the following line is not a comment but a verbatim `%`:
```tex
\hbox{\|\begin{minipage}[t]%|}
```
Pandoc understands that when you write
```tex
\hbox{\verb|\begin{minipage}[t]%|}
```
but not with the defined `\|`, apparently.

**Comment by jgm** [comment]
Actually it's more complex than that.  The defined `\|` normally works fine, but there's some kind of interaction with the `\vbox`.
```
\def\|{\verb|}
\vbox{
\hbox{\|\begin{minipage}[t]%|}
}
```
yields the error, but
```
\def\|{\verb|}
\vbox{
\hbox{\|\begin{minipage}[t]%|}
}
```
works perfectly.

**Comment by jgm** [comment]
Pushed a change that fixes this.

**Comment by jgm** [comment]
I don't know when the next release will come out.  You can grab a [nightly](https://github.com/jgm/pandoc/actions/workflows/nightly.yml), though.
