### ISSUE TITLE
$ symbol in Display Math

### ISSUE THREAD

**Issue by PassionPenguin** [jgm/pandoc#7942]
**Explain the problem.**

I've made a filter to convert Math into svg with lua + latex + dvisvgm, and since latex cannot recognize CJK chars in either mhchem or chemfig, i have to quote these chars with \text{}, but since this is a math-mode control sequence, i have to quote it with $$ again...

Now with the quoted latex code it works in latex parser, but rise a new problem: pandoc seems to parse inline-math first than display-math, causing the whole latex code not parsed and the output is like this:

```html
<p>$$ \ce{<span
class="math inline">$\underset{\ce{CO2}}{\ce{6[1C]}}$</span> + 6[5C]
-&gt; <span
class="math inline">$\underset{\text{3-磷酸甘油酸}}{\ce{12[3C]}}$</span>}\
\ce{12[3C] -&gt;[ATP] <span
class="math inline">$\underset{\text{1,3-二磷酸甘油酸}}{\ce{12[3C]}}$</span>}\
\ce{12[3C] -&gt;[NaDPH] <span
class="math inline">$\underset{\text{3-磷酸甘油醛/二羟丙酮磷酸}}{\ce{12[3C]}}$</span>}\
\ce{<span
class="math inline">$\underset{3-磷酸甘油醛}{\ce{2[3C]}}$</span>
-&gt;[\text{酶}] <span
class="math inline">$\underset{\text{葡萄糖}}{\ce{1[6C]}}$</span>}\
\ce{10[3C] -&gt;[\text{酶}][ATP] 6[5C]} $$</p>
```

**Reproduce**

tmp.md:

```markdown
$$
\ce{$\underset{\ce{CO2}}{\ce{6[1C]}}$ + 6[5C] -> $\underset{\text{3-磷酸甘油酸}}{\ce{12[3C]}}$}\\
\ce{12[3C] ->[ATP] $\underset{\text{1,3-二磷酸甘油酸}}{\ce{12[3C]}}$}\\
\ce{12[3C] ->[NaDPH] $\underset{\text{3-磷酸甘油醛/二羟丙酮磷酸}}{\ce{12[3C]}}$}\\
\ce{$\underset{3-磷酸甘油醛}{\ce{2[3C]}}$ ->[\text{酶}] $\underset{\text{葡萄糖}}{\ce{1[6C]}}$}\\
\ce{10[3C] ->[\text{酶}][ATP] 6[5C]}
$$
```

shell command:

```sh
pandoc --lua-filter=filters\texsvg.lua -s 'tmp.md' -o tmp.html -f commonmark_x
```

**Pandoc version?**
pandoc.exe 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
User data directory: C:\Users\Hoarfroster\AppData\Roaming\pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

**Comment by PassionPenguin** [comment]
> 

it's actually mhchem's control sequence `\ce`...

---

Thanks for your answer~

I have another reproducable case as following:

tmp.md

```markdown
$$
\begin{align}
This is $\text{Hello World}$
\end{align}
$$
```

sh

```sh
pandoc --lua-filter=filters\texsvg.lua -s 'tmp.md' -o tmp.html -f commonmark_x
```

tmp.html

```html
...
<p>$$ \begin{align} This is <span class="math inline">Hello World</span>
\end{align} $$</p>
...
```

**Comment by PassionPenguin** [comment]
if there's no $ in double-$ like this, then it will be treated as DisplayMath well...

```markdown
$$
\begin{align}
This is Hello World
\end{align}
$$
```
```html
<p><span class="math display">$$
\begin{align}
This is Hello World
\end{align}
$$</span></p>
```

$ is needed in several packages(chemfig, mhchem) ever since they donot support non-ascii? chars and i have to use math-mode \text{} or other stuff to quote those chars...

currently i have to change all these code to CodeBlock, which is really a big stuff

**Comment by jgm** [comment]
This isn't valid LaTeX, though:
```tex
$$
\begin{align}
This is $\text{Hello World}$
\end{align}
$$
```
Try that with pdflatex.
Even if you remove the `$$`s it is not valid.

**Comment by PassionPenguin** [comment]
> ```
> \begin{align}
> This is $\text{Hello World}$
> \end{align}
> ```

sorry for that wrong example....

anyway $ in \ce or \chemfig directly is valid for latex but not in pandoc.

**Comment by PassionPenguin** [comment]
I found something interesting:

markdown:

```md
$$
\schemestart
\chemfig{*6([0,.5]------)} \arrow{->[$\text{Hello}$]}
\schemestop
$$
```

| sh 1 | sh 2 |
| --- | --- |
| pandoc -s tmp.md -o tmp.html | pandoc -s tmp.md -o tmp.html -f commonmark_x |
| math-display | math-inline |

##### sh 1

```html
<p><span class="math display">$$
\schemestart
\chemfig{*6([0,.5]------)} \arrow{-&gt;[$\text{Hello}$]}
\schemestop
$$</span></p>
```

##### sh 2

```html
<p>$$ \schemestart \chemfig{*6([0,.5]——)} \arrow{-&gt;[<span
class="math inline">Hello</span>]} \schemestop $$</p>
```

what cause the problem?

---

the code above is valid latex as expanded:


```latex
\documentclass[12pt,preview]{standalone}
\usepackage{ctex}
\usepackage[version=4]{mhchem}
\usepackage{chemfig}
\usepackage[libertine]{newtxmath}

\begin{document}
\begin{preview}
\title{Hello World}
\author{Hoarfroster}


\schemestart
\chemfig{*6([0,.5]------)} \arrow{->[$\text{Hello}$]}
\schemestop

\end{preview}
\end{document}
```

**Comment by jgm** [comment]
See #6668 and give the filter there a try.

**Comment by jgm** [comment]
OK, now I understand your issue better.  The `markdown` reader doesn't cause the problem, it's just `commonmark` with the `tex_math_dollars` extension.  The following cases illustrate the problem:
```
% pandoc -f commonmark+tex_math_dollars -t native
$$
\text{Hi $x$}
$$
^D
[ Para
    [ Str "$$"
    , SoftBreak
    , Str "\\text{Hi"
    , Space
    , Math InlineMath "x"
    , Str "}"
    , SoftBreak
    , Str "$$"
    ]
]
```
```
% pandoc -f commonmark+tex_math_dollars -t native
$$
\text{Hi}
$$
^D
[ Para [ Math DisplayMath "\n\\text{Hi}\n" ] ]
```

**Comment by jgm** [comment]
I'm going to transfer this to commonmark-hs, because that's where the issue lies.

**Comment by jgm** [comment]
I've added a fix for this in commonmark-extensions, but it's not perfect.  Looking back at pandoc's LaTeX reader, I see that we have code that counts groupings:
```hs

dollarsMath :: PandocMonad m => LP m Inlines
dollarsMath = do
  symbol '$'
  display <- option False (True <$ symbol '$')
  (do contents <- try $ untokenize <$> pDollarsMath 0
      if display
         then mathDisplay contents <$ symbol '$'
         else return $ mathInline contents)
   <|> (guard display >> return (mathInline ""))

-- Int is number of embedded groupings
pDollarsMath :: PandocMonad m => Int -> LP m [Tok]
pDollarsMath n = do
  tk@(Tok _ toktype t) <- anyTok
  case toktype of
       Symbol | t == "$"
              , n == 0 -> return []
              | t == "\\" -> do
                  tk' <- anyTok
                  (tk :) . (tk' :) <$> pDollarsMath n
              | t == "{" -> (tk :) <$> pDollarsMath (n+1)
              | t == "}" ->
                if n > 0
                then (tk :) <$> pDollarsMath (n-1)
                else mzero
       _ -> (tk :) <$> pDollarsMath n
```
This could be ported over to commonmark-hs.

**Comment by PassionPenguin** [comment]
> OK, now I understand your issue better. The `markdown` reader doesn't cause the problem, it's just `commonmark` with the `tex_math_dollars` extension. The following cases illustrate the problem:
> 
> ```
> % pandoc -f commonmark+tex_math_dollars -t native
> $$
> \text{Hi $x$}
> $$
> ^D
> [ Para
>     [ Str "$$"
>     , SoftBreak
>     , Str "\\text{Hi"
>     , Space
>     , Math InlineMath "x"
>     , Str "}"
>     , SoftBreak
>     , Str "$$"
>     ]
> ]
> ```
> 
> ```
> % pandoc -f commonmark+tex_math_dollars -t native
> $$
> \text{Hi}
> $$
> ^D
> [ Para [ Math DisplayMath "\n\\text{Hi}\n" ] ]
> ```

That‘s it...thx for addressing the problem~
