### ISSUE TITLE
RAM usage reaches 100% when converting a 300 MB RTF document

### ISSUE THREAD

**Issue by mush42** [jgm/pandoc#7943]
Hello,

The title says it all.

When using pandoc to convert a large (300 MB) RTF document, to html or markdown, RAM usage reaches 100% causing the system to freeze indefinitely.

The content of the RTF document is in Arabic language, and it has been converted from docx to RTF using MS Word 2019.

I'm using pandoc-2.17.1.1-windows-x86_64 on a Windows 10 machine with 8 GB of RAM and Intel Core i7 processor.

Best

**Comment by mush42** [comment]
I think there is a memory leak when processing RTF documents.
Even if the document has been converted from .docx to rtf using pandoc, amounting to about 37 MB, pandoc eats up all of the RAM causing the system to freeze.

Best

**Comment by jgm** [comment]
Thanks for the report.  There's not much we can do, though, without a sample document that allows us to reproduce the issue.
See https://pandoc.org/faqs.html#pandoc-sometimes-uses-too-much-memory.-how-can-i-limit-the-memory-used-by-pandoc if you just want to make sure pandoc gets killed before it eats too much memory.

**Comment by jgm** [comment]
If you can upload a sample document, we can test further.

**Comment by mush42** [comment]
Hello @jgm 

Here is a document that causes the issue:
[Arabian_nights.zip](https://github.com/jgm/pandoc/files/8147332/Arabian_nights.zip)


Best
Musharraf

**Comment by jgm** [comment]
I can't open this RTF successfully with either TextEdit on macOS or Microsoft Word.
Is it even a valid RTF?  RTF files should begin with something like this
```
{\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 \fmodern Courier;}}
```
but this one doesn't.

**Comment by mush42** [comment]
Hello @jgm ,

Just to make the point, I tried to convert an Arabic language EPUB to RTF using pandoc, and the result was the file I uploaded.

I'm sorry for the mistake.

The original file I was talking about is too large to be attached here (about 65 MB when compressed. I don't know how to provide it!

**Comment by mush42** [comment]
Hello @jgm 

Here is the original .docx document. You can convert it to rtf using either word or pandoc.

The resulting document is the one which causes the issue.
[sample_document.docx](https://github.com/jgm/pandoc/files/8147404/sample_document.docx)

Best
Musharraf

**Comment by jgm** [comment]
If you use pandoc to create an RTF, you must use `-s` or you'll jjust get an RTF fragment, not a self-standing document.

**Comment by jgm** [comment]
After
```
pandoc sample_document.docx -s -t rtf -o sample_document.rtf
```
my computer takes about 30 seconds to convert the document back to docx.  That's not too bad, considering that this is a 36M document.  One reason the document is so long is that all of the characters need to be encoded as unicode escape sequences, so one Arabic letter can take 6-7 ASCII characters to encode.

**Comment by mush42** [comment]
@jgm 
What about RAM usage?

**Comment by jgm** [comment]
I've made a few changes that get the max residency down to 1.2G, that's some improvement...

**Comment by jgm** [comment]
And now down to 772MB.

**Comment by jgm** [comment]
I think with these improvements, performance is now acceptable.
Memory usage proportional to the size of input is not out of line with other pandoc readers.
