### ISSUE TITLE
"Unable to load picture" but image is there among other that work

### ISSUE THREAD

**Issue by Ombrelin** [jgm/pandoc#7947]
**Explain the problem.**

I have a markdown document with multiple images, which are all stored in the same folder. For a reason I dont understand, one of this image throws the following error when compiling to PDF with pandoc : 

> ! Unable to load picture or PDF file 'C:/Users/arsen/AppData/Local/Temp/tex2pdf
> .-29e3f237d2b4d819/images/ca_flutter.png'.
> <to be read again>
 >                  }
> l.766 ....-29e3f237d2b4d819/images/ca_flutter.png}

But this image is among all the other images of the doc in an image folder next to the markdown doc : 

![image](https://user-images.githubusercontent.com/47502331/156918554-b80acec7-7abc-471a-8567-be5377e829f4.png)

This is an example of image that works : 

```md
![Clean Architecture](images/clean_architecture.png)
```

and this is the one image which does not work : 

```md
![Clean Architecture Flutter](images/ca_flutter.png)
```

The problem is with this image because if I remove it the doc compiles without problem.

This is the command I'm using : 

```bash
pandoc -f markdown "rapport.md" --highlight-style "C:\Users\arsen\Nextcloud\Markdown\builtin-zenburn.theme" -V mainfont:"Segoe UI" -V geometry:a4paper -V geometry:margin=1.5cm --pdf-engine=xelatex --toc -o "rapport.pdf" --filter pandoc-plantuml
```

**Pandoc version?**

OS : Windows 11

pandoc.exe 2.14.2
Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.11,
citeproc 0.5, ipynb 0.1.0.1

**Comment by jgm** [comment]
Very strange, I don't know what would cause this, but maybe latex doesn't like something about this png?
(That particular message is coming from latex, not pandoc.)
Try with `--pdf-engine=latexmk --pdf-engine-opt=-outdir=tmp`, maybe?  Then you could go into tmp afterwards and try to figure out what is going on.

**Comment by jgm** [comment]
Also run with `--verbose` to see if there are any clues there.

**Comment by Ombrelin** [comment]
Yeah after a long time browsing latex issues I just saved the image with paint .NET and it finally worked. Guess something in the image was rejected by latex. Anyway it's an issue with latex and not pandoc, sorry for bothering you with it !
