### ISSUE TITLE
Trailing spaces within quotes

### ISSUE THREAD

**Issue by jonkri** [jgm/pandoc#7948]
**Explain the problem.**

Pandoc seems to remove trailing spaces within quotes.

```
$ pandoc 
"Hello " and "World!"
```

The above command produces the following markup:

```
<p>“Hello” and “World!”</p>
```

Note that there is no space before the second quote in “Hello”.

**Pandoc version?**

2.14.2, Arch Linux

**Comment by jgm** [comment]
Pandoc's markdown reader does some space normalizing in inline containers like Emph, and apparently also Quoted.  I suppose we could change this, but is there a legitimate reason why you'd want the space before the closing "?

Note that if you use `-f commonmark` the space will be preserved, but not smart quotes.
With `-f commonmark+smart` the space will be preserved and the quotes will both be open quotes.

**Comment by jonkri** [comment]
Thanks for your reply, @jgm!

> is there a legitimate reason why you'd want the space before the closing "?

I don't know if it's legitimate or not. I instructed students to combine "Hello " and "World!" as part of a programming assignment.

If we're not sure on how to proceed, perhaps it's better to leave it as it is.

I could work around the removal of the space by replacing the space with `&nbsp;`, which perhaps is better anyway, so that the quote is guaranteed not to wrap.

> Note that if you use `-f commonmark` the space will be preserved, but not smart quotes.

I do appreciate the smart quotes. :slightly_smiling_face:

**Comment by jgm** [comment]
Generally if you're talking about computer code, you should be enclosing it in backticks:
```
`"Hello " + "world"`
```

**Comment by jonkri** [comment]
Oh, yeah, thanks. I wasn't trying to communicate code, semantically, though, I don't think. That bit was for the students to figure out. :slightly_smiling_face:

**Comment by mb21** [comment]
So nothing to change in pandoc, right? Closing this then..
