### ISSUE TITLE
Spurious warning when citeproc operates on URLs containing at sign ("@")

### ISSUE THREAD

**Issue by phlummox** [jgm/pandoc#7952]
When pandoc is run with the '`--citeproc`' switch to process citations, and the citation is for a web page whose URL contains an at ('`@`') symbol (say, `https://foo.com/@bar`), pandoc prints a warning like the following:

```
[WARNING] Citeproc: citation bar not found
```

But this seems incorrect; pandoc shouldn't be processing the content of valid references' valid URLs and treating them as citations. From my understanding of [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986), '`@`' is a permissible character when it appears in the "path" portion of an HTTP or HTTPS URL, and per [this StackOverflow answer][stackoverflow], %-encoding the `@` symbol would be incorrect - the two URLs `https://foo.com/@bar` and `https://foo.com/%40bar` are not identical.

(One example of a website where nearly all URLs contain '`@`' symbols is [medium.com](https://medium.com/) - see the URLs of articles listed under, say, https://medium.com/tag/programming, for example.)

[stackoverflow]: https://stackoverflow.com/questions/36922192/must-and-40-be-treated-equivalently-in-url-paths

## Steps to reproduce

Create the following markdown file "`in.md`":

```markdown
---
title: test document
reference-section-title: "References"
references: [{"id":"ONeil2019",
              "type":"webpage",
              "title":"Chelonian functional programmers — beware mutation!",
              "container-title":"Medium",
              "URL":"https://medium.com/@apriloneil/beware-mutation",
              "author":[{"family":"O'Neil","given":"April"}],
              "issued":{"date-parts":[[2019,1,6]]},
              "accessed":{"date-parts":[[2022,3,9]]}}]
---
In this essay, I will critique advice on functional programming [@ONeil2019].
```

Then run, say:

```
pandoc -t latex -o out.tex  --citeproc in.md
```

(Actually  I think any output format will give the same result.)

### Expected result

"`out.tex`" should be created with no warning. As far as I can tell, "`in.md`" is valid Pandoc markdown, the YAML block is valid YAML, and the URL `https://medium.com/@apriloneil/beware-mutation` is a valid URL.

### Actual result

The following warning is displayed:

```
[WARNING] Citeproc: citation apriloneil/beware-mutation not found
```

### Comments

It's possible to get rid of the warning by changing one line of the input file to

```
              "URL":"https://medium.com/\\@apriloneil/beware-mutation",
```

but the problem is that the metadata now asserts that the URL is `https://medium.com/\@apriloneil/beware-mutation`, which just isn't true (it couldn't be a valid URL in any case, since the backslash is an unsafe character and should be percent encoded).

Large documents might have dozens of references containing "`@`" symbols in the URL (e.g. generated from a Zotero or Mendeley repository) - in this case, the warnings result in needlessly noisy output, and getting the author to preprocess the references before pandoc sees them in order to add backslashes doesn't seem right (since the references are, in fact, 100% correct).

### Pandoc version

```
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/arran/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
Or, if you want the URI to come across as regular text, not a link, you can backslash-escape the `@` symbol or put the whole URI in code backticks.
