### ISSUE TITLE
Problem with custom Latex environment inside of custom list environment items

### ISSUE THREAD

**Issue by abenthy** [jgm/pandoc#7953]
Hello, I'm trying to read a Latex document in Pandoc with the following structure:
```
\documentclass{article}

\newenvironment{myenumerate}{\begin{enumerate}}{\end{enumerate}}
\newenvironment{myenvironment}{}{}

\begin{document}

\begin{myenumerate}
\item{foo\begin{myenvironment}bar\end{myenvironment}}
\end{myenumerate}

\end{document}
```
Pandoc v. 2.17.1.1 (`pandoc -t json example.tex`) gives me the following error
```
Error at "example.tex" (line 13, column 2):
unexpected end of input
expecting \end{enumerate}

 ^
```
The document compiles without errors with pdflatex.

What I have tried / observed:
- The problem seems to be somehow related to the curly brackets after `\item`. If I replace `\item{...}` by `\item...` it works (I don't know why).
- If I remove the text `foo`, it works (again, I don't know why).
- Replacing myenumerate by a list defined with `\newlist` from the enumitem package doesn't fix the error.
- If I replace the usage of myenumerate with the standard enumerate environment, it works.
- If I replace `\begin{myenvironment}bar\end{myenvironment}` with `\begin{center}bar\end{center}`, it works.

Does someone know what cause the problem here? I have a document that uses custom lists like above that I would like to convert with Pandoc, if possible without changes to the document. However, changes to the macro definitions would be no problem as a fix for me.

Thanks for your fantastic work on parsing Latex by the way, most of my documents work great!

**Comment by jgm** [comment]
More experiments:
```
% pandoc -f latex -t native
\newenvironment{x}{}{}
{foo\begin{x}bar\end{x}}
^D
Error at (line 2, column 24):
unexpected Tok (line 2, column 24) Symbol "}"
expecting end of input
{foo\begin{x}bar\end{x}}
                       ^
```
```
% pandoc -f latex -t native
{foo\begin{x}bar\end{x}}
^D
[ Para [ Str "foo" ]
, Div ( "" , [ "x" ] , [] ) [ Para [ Str "bar" ] ]
]
```
```
% pandoc -f latex -t native
\newenvironment{x}{}{}
^D
foo\begin{x}bar\end{x}
[ Para [ Str "foobar" ] ]
```
```
 % pandoc -f latex -t native
\newenvironment{x}{}{}
{\begin{x}bar\end{x}}
^D
[ Para [ Span ( "" , [] , [] ) [ Str "bar" ] ] ]
```

**Comment by jgm** [comment]
Even smaller:
```
{foo\bgroup bar\egroup }
```
which is how pandoc expands the environment
yields
```
Error at (line 1, column 24):
unexpected Tok (line 1, column 24) Symbol "}"
expecting end of input
{foo\bgroup bar\egroup }
```

**Comment by jgm** [comment]
However this is fine!
```
\bgroup foo\bgroup bar \egroup\egroup
```
