### ISSUE TITLE
Setting urlcolor in metadata escapes [] and {}

### ISSUE THREAD

**Issue by neilmayhew** [jgm/pandoc#7955]
**Explain the problem.**

In `metadata.yml`:
```yaml
urlcolor: "[HTML]{8c1c54}"
```

In `output.tex`:
```tex
  urlcolor={{[}HTML{]}\{8c1c54\}},
```

On command line:
```bash
--variable urlcolor="[HTML]{8c1c54}"
```

In `output.tex`:
```tex
  urlcolor={[HTML]{8c1c54}},
```

**Pandoc version?**
pandoc 2.17.1.1 static binary on Linux

**Comment by jgm** [comment]
Metadata is treated as string content and the strings are escaped in the output format (here latex).
So, this is working just as documented, and is not a bug.

Variables are interpolated directly into templates (so they are not escaped).  That is why you see this difference.

If you want to specify this in a separate file, one option would be to use a defaults file (see `--defaults`) which includes both a `metadata` field and a `variables` field.

**Comment by neilmayhew** [comment]
Thanks. I'll try the defaults approach.

I can see the conceptual difference between metadata and variables. However, the situation is definitely confusing for non-experts.
