### ISSUE TITLE
Excalidraw integration

### ISSUE THREAD

**Issue by papojari** [jgm/pandoc#7966]
**Describe your proposed improvement and the problem it solves.**

Sometimes I want to have a drawing of something in my markdown document. Excalidraw can concert to SVG vor PNG but thats extra steps as I'd have to convert the excalidraw file to svg and also have to put the svg link into markdown. If pandoc would do this for me that'd be great and I wouldn't have to keep two files around.

**Describe alternatives you've considered.**

**Comment by mb21** [comment]
Pretty sure you can write a [lua filter](https://pandoc.org/lua-filters.html) to do that...

**Comment by tarleb** [comment]
I agree with Mauro here, this is best solved with a filter. Built-in excalidraw support is out of scope for pandoc.

**Comment by tarleb** [comment]
Please do feel free to ask if you have questions about how filters are useful here. The [pandoc-discuss](https://groups.google.com/g/pandoc-discuss) mailing list is full of knowledgeable people who like to help with this kind of thing.
