### ISSUE TITLE
add an option to `processCitations` to put the processed references into the metadata  under a key to inserted in a template later

### ISSUE THREAD

**Issue by andrewufrank** [jgm/pandoc#7969]
**Describe your proposed improvement and the problem it solves.**
I use processCitations from Pandoc.Text.Citeproc from a Haskell program to produce HTML code, which is later merged with a template (using `renderTemplate`). 

It seems unfortunate, that the references produced with `processCitations` are immediately  inserted in the text - with limited choice of the header, header style etc. It would be useful if the rendered references were available in the meta data (under a key). This would allow then to insert the references in the template using the key under a heading set in the template. 

**Describe alternatives you've considered.**
It would be possible to achieve this using `citeproc`, but breaking the `processCitations` in an option which returns the processed citations separately and the 'full service' solution currently given would allow more flexibility in the inclusion of the processed references. 

Thank you for considering!

**Comment by jgm** [comment]
You mean the bibliography, I assume.

See the documentation: you can insert a div with id `refs` anywhere in your document (even in metadata), and the references will be placed there.

```
::: {#refs}
:::
```

**Comment by jgm** [comment]
No, not in the template.  In the document itself.
Div is one of the constructors for a pandoc Block element.

**Comment by jgm** [comment]
If you want to do it in the template, you can do that by making sure that the Pandoc document you pass to `processCitations` contains a metadata field, say `refs`, whose content is `MetaBlocks [Div ("refs",[],[]) []]`.
`processCitations` will (I think!) insert the bibliography into this Div element.  You can then use `$refs$` in your template.  (However, I'm not totally sure it will work if this div is in the metadata; I'd have to check the code.  If it doesn't, we can probably modify `processCitations` so that it will work.)

**Comment by andrewufrank** [comment]
I will try this and hope I understand the details... Thank you for the help!

**Comment by jgm** [comment]
OK, looked at the code. Currently we only do `insertRefs` on the body of the document, so what I outlined above won't work.  But I think we could change the code easily enough so that it would work.

**Comment by jgm** [comment]
OK, the code currently in HEAD will allow you to what I described.

**Comment by andrewufrank** [comment]
thank you - i will try. sounded a bit complicated. will take a day or two. thank you!

**Comment by andrewufrank** [comment]
It took a while, but finally I built a filter to extract the "refs" and it worked; thank you for the suggestion!
