### ISSUE TITLE
Epub: supress title_page.xhtml when no title block is present

### ISSUE THREAD

**Issue by thomas-galvin** [jgm/pandoc#797]
When generating an ePub, title_page.xhtml shows up as an empty page if no title block is present. When the resulting ePub is opened, the first page is blank, which could be confusing to some readers. Rather than an empty page, the title page should be suppressed altogether if no title block is present.

**Comment by Mazarin07** [comment]
Sorry, 12 years have passed, and I still have the same damned issue. 
Calibre also generates title_page.xhtml, but without arbitrarily inserting an extra unnecessary page at the very beginning of my ebook. I have a nicely designed cover page, so pandoc inserting an ugly extra page  (showing only the tile, the author and the publisher)  there is uncivilized.

**Comment by jgm** [comment]
In recent versions of pandoc we have the `--epub-title-page=false` option that allows you to prevent title_page.xhtml from being generated at all.

**Comment by Mazarin07** [comment]
> In recent versions of pandoc we have the `--epub-title-page=false` option that allows you to prevent title_page.xhtml from being generated at all.

Thank you, jgm!
I have switched to ebooklib library, which is more simple to use and handle (isn’t flawless, either, but I was able to fix them).
