### ISSUE TITLE
ODT-writer: No space after inline equation

### ISSUE THREAD

**Issue by LarsH** [jgm/pandoc#7970]
The ODT writer does not add a space after inline equations.

Example file:

```markdown
# Test

This is a test sentence with an equation $f(x)=\sqrt{x}$ and text afterwards.
```

Running `pandoc example.md -o example.odt` yields an ODT that looks like this:
![image](https://user-images.githubusercontent.com/1294050/158788131-215ddb13-d739-4f29-b8c4-c820df1b98a6.png)

whereas `pandoc example.md -o example.docx` gives

![image](https://user-images.githubusercontent.com/1294050/158788214-294ef276-7860-4321-a4c1-e39e43ea9e50.png)

The missing space in the ODT does not look nice, I would expect it to be a space there.

**Pandoc version?**

```
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.2, texmath 0.12.4, skylighting 0.12.3,
citeproc 0.6.0.1, ipynb 0.2, hslua 2.2.0
```

**Comment by jgm** [comment]
If you inspect the contents of the ODT, you'll see that there is indeed a space:
```xml
<text:p text:style-name="First_20_paragraph">This is a test sentence with an equation <draw:frame draw:style-name="fr1" text:anchor-type="as-char"><draw:object xlink:href="Formula-0/" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" /></draw:frame> and text afterwards.</text:p>
```
And in fact I see a space when I view it with Libre Office:

<img width="647" alt="Screen Shot 2022-03-17 at 8 06 08 AM" src="https://user-images.githubusercontent.com/3044/158832789-a9840513-deec-4a47-bd52-516114a07609.png">

The space does not appear when I view it with Microsoft Word.  So I wonder if this is actually a problem with Word?

**Comment by jgm** [comment]
Unless there's a specific idea about how pandoc's output is wrong, I'll assume this is a bug in Word's odt import and close this.
