### ISSUE TITLE
operatorname* fails for docx output

### ISSUE THREAD

**Issue by allefeld** [jgm/pandoc#7972]
The math equation `$\operatorname*{arg\,max}_x f(x)$` fails when converting to docx:

````
[WARNING] Could not convert TeX math \operatorname*{arg\,max}_x f(x, y), rendering as TeX:
  atorname*{arg\,max}_x f(x, y)
                     ^
  unexpected "_"
  expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace
````

The starred version of `operatorname` allows to set limits, which I here use to indicate with respect to which variable the position of the maximum is to be determined.

The same equation works with LaTeX output as well as HTML with MathJax.

**Pandoc version?**
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
Debian 11.2

**Comment by jgm** [comment]
This is essentially the same issue as https://github.com/jgm/texmath/issues/147
Currently texmath only takes a plain string in operatorname, and thus fails when you try to include the `\,`.
It would be good to fix this, but since there's already an issue for this I'll close this one.

**Comment by jgm** [comment]
This is fixed now in the dev version.

**Comment by allefeld** [comment]
Thanks! I assumed it was related to the subscript, because the error message points at the underscore.
