### ISSUE TITLE
tab delimited csv as input

### ISSUE THREAD

**Issue by dbojan** [jgm/pandoc#7974]
Hello.
Pandoc can convert coma separated file (csv) to docx, or to markdown, but not tab separated one.
Any chance of adding option to specify delimiter like tab, or pipe,  with csv as input file?

Or if possible, other specified character, like ";" ?

Thanks.

**Comment by alerque** [comment]
Tab separated files are known as TSV.

CSV itself has pretty fixed rules, but it is quite common to see ad-hoc variations in the wild. Some are just apps making up their own stuff, some are mistakes. Either way I highly recommend normalizing all incoming CSV (or TSV) content using robust tooling like the tools from [`csvkit`](https://csvkit.readthedocs.io/en/latest/) as a first step, then passing the normalized spec compliant data for further processing whether with Pandoc or other tools.

**Comment by dbojan** [comment]
So there is no way to open TSV with pandoc?

**Comment by tarleb** [comment]
Currently not, no. I'm not sure there should be. On one hand, tsv is an exceptionally simple format, has it's [own MIME type `text/tab-separated-values`](https://www.iana.org/assignments/media-types/text/tab-separated-values), and would not be difficult to support. OTOH, even simple code can be bloat. Also, tsv is not clearly defined (unlike CSV, which has RFC 4180), which can lead to confusion and unexpected behavior. There are plenty of converters, no need to add another.

I lean towards not supporting it, but the ultimate decision will be that made by @jgm.

**Comment by jgm** [comment]
It's pretty easy to do, so I think I'll make a tsv reader available, using the spec linked to.

**Comment by dbojan** [comment]
Hi.
Is this implemented in the latest release?
Thanks.

**Comment by jgm** [comment]
No -- you can always find information on releases here; https://pandoc.org/releases.html
