### ISSUE TITLE
csv to spreadsheet (excel or open document spreadsheet )

### ISSUE THREAD

**Issue by dbojan** [jgm/pandoc#7975]
Hi.
Would it be possible to add spreadsheet output format (xlsx or ods), for csv files?
Just csv data to simple xlsx table.

Thanks.

**Comment by alerque** [comment]
Why use Pandoc for this? Pandoc is a swiss army knife for *documents*, but spreadsheets are more akin to databases than documents. There are lots of command line utilities (in several languages, Python, C++, etc) that can convert CSV to XLS or ODS that have options for handling different data types, headers, sheets, formula expansion, etc. I don't think this can of worms belongs in Pandoc at all.

**Comment by jgm** [comment]
Since spreadsheet programs can all open CSV files (and save the results in other formats), this doesn't seem worth the trouble.

**Comment by alerque** [comment]
It does make me curious what the *perceived* need for this is coming from. It keeps coming up and I really don't understand what the workflow is that people can't ingest CSV on one end, can't output XLSX on the other, and don't run across any of the existing tooling for handling data like this and reach for `pandoc` in the first place.
