### ISSUE TITLE
Improve handling of spacing before ":;!?" when lang=fr

### ISSUE THREAD

**Issue by anntzer** [jgm/pandoc#7976]
**Describe your proposed improvement and the problem it solves.**

Typography rules for the French language state that a thin nonbreaking space should be used before the so-called "high punctuation characters", ":;!?" (more precisely, some rulesets, but not all, state that ":" should be preceded by a fullwidth space).  See e.g. the TeX docs for babel-french (https://ctan.org/pkg/babel-french, search for "AutoSpacePunctuation") or https://en.wikipedia.org/wiki/Colon_(punctuation)#Spacing or (in French, sorry) https://fr.wikipedia.org/wiki/Ponctuation#Signes_de_ponctuation_occidentaux.

In TeX documents using babel-french, one can skip typing the space; babel automatically inserts it with the right width and non-breakingness (luatex is smart enough to not insert it if the following character is not a space, e.g. in `C:\A\Windows\Path` or in `10:55`).  Likewise, in French documents, Word automatically inserts a nonbreaking space before these punctuation signs when typed interactively, and if the space is already there it gets autoconverted to nonbreaking (I don't think it distinguishes between thin and full space, nor does it detect cases where the next character is not a space).  However, loading a Word file without the spaces doesn't add spaces automatically where needed.

It would be useful if pandoc could detect this case, and, when emitting docx (or html, for that matter), inserts the right missing space.

**Describe alternatives you've considered.**

Manually inserting nonbreaking thin spaces would be slightly tedious.

**Comment by jgm** [comment]
You're basically asking that we implement what babel-french does but for arbitrary output formats.

I think the best approach would be for you to use a filter that inserts a nonbreaking space before the colon character at the end of a Str element\.  Here's a simple Lua filter that would do this:
```lua
function Str(el)
  if el.text:match(":$") then
    el.text = el.text:sub(1,-2) .. utf8.char(160) .. ":"
    return el
  end
end
```
Save that as frenchpunct.lua and then use `--lua-filter frenchpunct.lua` on your command line.

**Comment by jgm** [comment]
(You can do something similar for the other punctuation nuances.)

**Comment by anntzer** [comment]
This seems like a good workaround, thanks for the suggestion!
