### ISSUE TITLE
\useshorthands broken since 2.12

### ISSUE THREAD

**Issue by unDocUMeantIt** [jgm/pandoc#7979]
**Background: `scrjura`**

I've been using pandoc to generate legal documents (markdown to PDF conversion) with the [scrjura](https://ctan.org/pkg/scrjura) LaTeX package. It features numbering of sentences with its `\Sentence` macro, it's recommended to define a shorthand in the preamble:

```LaTeX
\useshorthands{’}
\defineshorthand{’S}{\Sentence\ignorespaces}
```

So you can use `'S` at the beginning of sentences to have them numbered:

```LaTeX
'S This is the first sentence.
'S This is the second one.
```
This should turn out in the PDF as

```
¹This is the first sentence. ²This is the second one.
```
Using a template with the shorthand definition in its preamble and a hack to use sections as clauses used to work well in the past:

```LaTeX
\def\jurOn{%
\begin{contract}%
\let\section\Clause%
\let\subsection\SubClause%
}
\def\jurOff{%
\end{contract}%
}
```

**The issue**

However, I've just noticed that my documents can no longer be correctly converted after updating to pandoc 2.17, instead of numbered sentences I now see the actual `'S` shortands in the resulting PDFs. I've checked with various older versions to find out where this has stopped working: It still works with pandoc 2.11.4, but stopped working with pandoc 2.12 (Ubuntu 20.04).

**Workaround**

As a workaround I can use pandoc 2.17 to genrate a LaTeX file from the markdwon document and pdflatex to manually create the PDF, which also results in a correctly built document with the intended sentence numbering:

```
# no numbered senteces:
pandoc -r markdown input.md --template scrjura_template.latex -o output.pdf

# correctly numbered sentences:
pandoc -r markdown input.md --template scrjura_template.latex -o output.tex
pdflatex output.tex
```

**Comment by unDocUMeantIt** [comment]
thanks for getting back to me so fast!

i am already using a custom latex template that adds the shorthands described above. babel gets included with

```LaTeX
\usepackage[$for(babel-otherlangs)$$babel-otherlangs$,$endfor$main=$if(lang)$$babel-lang$$else$ngerman$endif$]{babel}
```

i've been using that same template with the various pandoc versions, and as i explained, the LaTeX code itself seems to come out ok, just not the PDF.

i've also had no problems with 2.11.3 or 2.11.4, they appear with pandoc 2.12. could it be a side effect related to the removal of `smart` that was added to the 2.12 release because of [this issue](https://github.com/jgm/citeproc/issues/54)?

**Comment by jgm** [comment]
If you're using a custom template, then it's really hard to say.
You'll have to give us a minimal reproducible example.

**Comment by unDocUMeantIt** [comment]
ok, no problem. first is the LaTeX template (scrjura_minimal.latex):

```LaTeX
\documentclass[ngerman,a4paper]{scrartcl}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage{scrjura} 
\usepackage{hyperref}

\useshorthands{'}
\defineshorthand{'S}{\Sentence\ignorespaces}
\defineshorthand{'.}{. \Sentence\ignorespaces}

\title{Test}
\author{Foo Bar}

\def\jurOn{%
\begin{contract}%
\let\section\Clause%
\let\subsection\SubClause%
}
\def\jurOff{%
\end{contract}%
}

\begin{document}
\maketitle
\thispagestyle{empty}

$body$

\end{document}
```

and here comes the markdown example (pandoc_minimal.md):

```markdown
\jurOn

# title=Example

'S This is the first sentence.
'S This is the second one.

'S First of second paragraph.
'S Second there.

This one stands alone should not be numbered.

\jurOff
```

with that, if i call

```
pandoc -r markdown pandoc_minimal.md --template scrjura_minimal.latex -o pandoc_minimal.pdf
```
since pandoc 2.12 i get this result:

![image](https://user-images.githubusercontent.com/1068974/160095747-c4c7f964-aa69-44d0-8a7a-f2e404c56f89.png)

but if instead i call

```
pandoc -r markdown pandoc_minimal.md --template scrjura_minimal.latex -o pandoc_minimal.tex && pdflatex pandoc_minimal.tex
```

i do still get the desired result also with pandoc >= 2.12:

![image](https://user-images.githubusercontent.com/1068974/160095838-5f8dd18b-c312-4ca9-95bd-f94634fe7e09.png)

**Comment by jgm** [comment]
Text.Pandoc.PDF, line 102:
```hs
        source <- writer opts{ writerExtensions = -- disable use of quote
                                  -- ligatures to avoid bad ligatures like ?`
                                  disableExtension Ext_smart
                                   (writerExtensions opts) } doc'
```
I suspect this is why this no longer works for you.

**Comment by jgm** [comment]
Commit that added this was 0f5c56dfb171e27745f4fe8530325223ecefe52a
Motivated by jgm/citeproc#54

**Comment by jgm** [comment]
I think that the best approach is for you to generate a tex file and process it yourself.  I don't see a good alternative fix to the issue mentioned above that would be as solid as this one.

**Comment by unDocUMeantIt** [comment]
i see, so it's actually the change i was suspecting to be responsible in my second post.

i found a more comfortable workaround, adding `\aliasshorthand` to the definition:

```LaTeX
\useshorthands{'}
\defineshorthand{'S}{\Sentence\ignorespaces}
\defineshorthand{'.}{. \Sentence\ignorespaces}
\aliasshorthand{'}{+}
```

this allows for also using `+S` in the markdown document instead of `'S`, while still working with `'S` in old documents + pdflatex (this shorthand definition is part of a *.sty file that is embedded in all my contract documents).

i hope people find this workaround when they run into the same issue, because the shorthands `'S` and `'.` as i have used them are part of the official KOMA script documentation for the scrjura package.
