### ISSUE TITLE
Table in Beamer output overrides \renewcommand on caption

### ISSUE THREAD

**Issue by Jmuccigr** [jgm/pandoc#7988]
**Explain the problem.**

Based on a [discussion](https://groups.google.com/g/pandoc-discuss/c/18sfveSHmLI) in the google group, I redefine a latex command in one of my Beamer outputs to avoid having a caption on images. So a simple markdown file and command looks like this:

```
> pandoc -t beamer -o Slides.pdf
---
header-includes: \renewcommand{\caption}[1]{}
title: Title
author: Author
date: March 25, 2022
...

![\ ](image.jpg)
```

The problem comes in when there's a table in the file. In that case, the images get captioned. For example

```
---
header-includes: \renewcommand{\caption}[1]{}
title: Title
author: Author
date: March 11, 2022
...

![\ ](Downloads/image.jpg)

-----

| table |
|:----:|
| cell |
```

If I output to tex using the `-s` switch, the difference between the two output tex files is (1) this bit up front:
```
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother
```

And (2) this bit for the slide with the table:

```
\begin{frame}
\begin{longtable}[]{@{}c@{}}
\toprule
table \\
\midrule
\endhead
cell \\
\bottomrule
\end{longtable}
\end{frame}
```

I don't know enough about latex to know what's happening.

**Pandoc version?**

pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2

**Comment by jgm** [comment]
I'm not sure either, but note that pandoc won't create a caption for images with empty alt text.
```
![](myimage.jpg)
```
Nor will it create a caption if the image is not alone in its paragraph, even if it's followed by just a nonbreaking space
```
![hello](myimage.jpg)\ 
```
Are any of these solutions adequate for you?
They seem more robust than what you're trying to do...

**Comment by Jmuccigr** [comment]
> I'm not sure either, but note that pandoc won't create a caption for images with empty alt text.
> 
> ```
> ![](myimage.jpg)
> ```
> 
> Nor will it create a caption if the image is not alone in its paragraph, even if it's followed by just a nonbreaking space
> 
> ```
> ![hello](myimage.jpg)\ 
> ```
> 
> Are any of these solutions adequate for you? They seem more robust than what you're trying to do...

The basic thing I'm trying to do is use the same markdown for both reveal and beamer presentations, and I want the caption in reveal (where I have it appear on a hover), but not in beamer. (Most of the time the caption is more than a space.) I rely on the implicit_figure to get the caption in reveal and on this little header-include to make it go away in beamer. I realize this might be an odd use case, but the issue with the table nevertheless seems buggy. If I have a trailing space, then that won't trip the implicit_figure. Also the reveal formatting is different because my reveal css affects `figure`, not `img`. 

Again, out of my depth here on the latex, but perhaps this is something with how beamer is implemented and not pandoc?

I script all this, so I can clean the comments out of the md before processing as beamer, but (again) this seems like buggy behavior.

**Comment by jgm** [comment]
I wouldn't say "buggy."  You're trying to redefine a standard LaTeX command and this may have delicate interactions with other packages.  Certainly it doesn't seem like a *pandoc* bug.

If you're scripting anyway, you might consider just using a Lua filter to clear out the caption on images when targeting beamer.

**Comment by Jmuccigr** [comment]
> Another approach might be using etoolbox:
> 
> ```
> \AtBeginEnvironment{figure}{\renewcommand{caption}[1]{}}
> ```
> 
> Something to try anyway...

OK, trying that as a header-include in the yaml, I get this error:

```
Error producing PDF.
! Missing control sequence inserted.
<inserted text> 
                \inaccessible 
l.128 \end{frame}
```

I'm also working on a filter to remove the captions in beamer. The following removes the caption text, but not the label, so there are a bunch of "Filter #" captions:

```{haskell}
function Image(img)
  img.caption = {}
  return {img}
end
```

**Comment by jgm** [comment]
Oh, interesting, maybe there is a bug here.
It looks like the LaTeX writer is matching using the new SimpleFigure pattern synonym.  And this matches even when the caption is empty, which it shouldn't do, I think!  (@argent0 @tarleb)

**Comment by jgm** [comment]
I don't know if this invariant can really be enforced in the pattern synonym, so probably we need to add guards in the writers.

**Comment by jgm** [comment]
Or maybe "empty caption is not a figure" thing should only be a description of parsing, and we can leave the writers alone.  Now that I think on it, I think that's how we were conceiving of it.  The `fig:` prefix in the title is what defines a SimpleFigure, and the parser adds this only if the caption is nonempty.

@Jmuccigr you can fix your filter by ensuring that it strip any `fig:` prefix from the image's title, in addition to making the caption empty.

**Comment by Jmuccigr** [comment]
Thanks for working on this.

Stripping the "fig:" will remove the caption completely, but it will also stop the image from being made into a figure in the first place and so loses the figure formatting (centered) which I want.

This header-include will remove caption **and** label and still keep the centering: `\captionsetup[figure]{labelformat=empty, textformat=empty}`

Ideally - to my mind - if a figure has an empty caption (or one that's purely whitespace), it would still be a figure, but have no caption at all. I'm not quite sure how to do this easily while keeping the current definition of implicit_figures, so this may be the best solution for that aspect.

To get back to the original issue though, this problem only occurs when there's a table in the markdown. No table, no labels. I think it's due to the invocation of `\usepackage{caption}` in the extra header material that gets included when there's a table and somehow overrides the header-include, even though that renewcommand occurs later in the file (again, out of my depth here on the latex):

This is the only change to the tex file, except for the actual frame containing the table.
```
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother
```

**Comment by jgm** [comment]
Why don't you look at the documentation for the captions package
https://mirror.mwt.me/ctan/macros/latex/contrib/caption/caption.pdf
Maybe there's something in there you could use?

**Comment by Jmuccigr** [comment]
> Why don't you look at the documentation for the captions package
> https://mirror.mwt.me/ctan/macros/latex/contrib/caption/caption.pdf
> Maybe there's something in there you could use?

That's where I got the idea for the header include, which I now find only works when there's a table, otherwise it generates an error. It does seem to work if I insert it into my beamer template right after the invocation of \caption in the table section:

```
$if(tables)$
\usepackage{longtable,booktabs,array}
$if(multirow)$
\usepackage{multirow}
$endif$
\usepackage{calc} % for calculating minipage widths
$if(beamer)$
\usepackage{caption}
\captionsetup[figure]{labelformat=empty, textformat=empty}
...
```

Then later on:

```
$if(beamer)$
\renewcommand{\caption}[1]{}
$else$
```

This takes care of both tables and no tables.
