### ISSUE TITLE
JATS XML ref-list citation information not read

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#7990]
Pandoc does not output citation information when reading JATS XML files.

STEPS TO REPRODUCE:
Generate two JATS XML files with citation info by doing
```
pandoc source.md -s --citeproc -f markdown -t jats+element_citations -o jats-element.xml
pandoc source.md -s --citeproc -f markdown -t jats -o jats-mixed.xml
```
with the markdown [source.md](https://github.com/jgm/pandoc/files/8356703/source.md) to generate a `jats-element.xml` and `jats-mixed.xml`. Then inspect the "references" objects output by
```
pandoc jats-mixed.xml -s --citeproc -f jats -t json
pandoc jats-element.xml -s --citeproc -f jats -t json
```
in the AST dumped as json. Might be convenient to pipe the outputs through
```
python -c 'import sys, json; print(json.load(sys.stdin)["meta"]["references"]["c"])'
```
The citation info read from jats-mixed.xml does not have any details about the reference. And for `jats-element.xml` it appears zero citation information was read.

WHAT EXPECTED:
Something like the references output from the markdown directly:
```
pandoc source.md -s --citeproc -f markdown -t json
```
with all the details about the citations.

**Pandoc version?**
Both versions 2.14.3 and 2.17.1.1 (on Fedora 35)

I've also tried outputing HTML with many different options but citations information in the input JATS XML never appears in the output.

**Comment by jgm** [comment]
There is code in the JATS reader to handle element-citation (not mixed-citation).
Can you directly upload a minimal sample JATS file we can test with (to spare me the trouble of generating a sources.md so I can follow your recipe above, and to make sure we're talking about exactly the same thing)?

**Comment by castedo** [comment]
Sure thing. Here's the XML file with [jats-element.xml.txt](https://github.com/jgm/pandoc/files/8357376/jats-element.xml.txt) element-citation.

Thank you!

It's interesting that some info is getting read for mixed-citation. So here's the XML file [jats-mixed.xml.txt](https://github.com/jgm/pandoc/files/8357382/jats-mixed.xml.txt) with mixed-citation that was generated from the same [source.md](https://github.com/jgm/pandoc/files/8356703/source.md).

**Comment by castedo** [comment]
For
```
pandoc jats-element.xml -s --citeproc -f jats -t json | python -c 'import sys, json; print(json.load(sys.stdin)["meta"]["references"]["c"])'
```
I get
```
[]
```
whereas if I read `jats-mixed.xml` instead of `jats-element.xml` then I get
```
[{'t': 'MetaMap', 'c': {'id': {'t': 'MetaInlines', 'c': [{'t': 'Str', 'c': 'ref-WatsonCrick1953'}]}}}]
```
and then reading from the source.md instead of XML I get a bunch of json with all the citation info.

**Comment by jgm** [comment]
Looks like you have doubly-nested ref-list for some reason?
```
<ref-list>
  <ref-list>
```
If you remove the doubled ref-list then it works.

**Comment by jgm** [comment]
If you produced this with pandoc, then the problem may actually lie with the JATS writer.

**Comment by jgm** [comment]
Yes, it was a bug in the writer - now fixed!

**Comment by castedo** [comment]
Thank you for debugging this so quickly!

Now I've got a quick fix with `sed` to get me going until I upgrade to the next version.

Pandoc rocks, thank you!
