### ISSUE TITLE
JATS writer not writing edition in ref-list

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#7993]
**REPRO STEPS**
Convert [has-edition.md](https://github.com/jgm/pandoc/files/8365283/has-edition.md) to jats xml:
```
pandoc -s -f markdown -t jats_publishing+element_citations --citeproc \
  < has-edition.md > out.xml
```

**EXPECTED**
`out.xml` with the contents of:
[has-edition.xml.txt](https://github.com/jgm/pandoc/files/8365293/has-edition.xml.txt)

**GOT**
`out.xml` missing the `<edition>` XML element inside [`<element-citation>`](https://jats.nlm.nih.gov/archiving/tag-library/0.4/n-3bw0.html)

**Pandoc version**
2.17.1.1 (and 2.14.0.3)

NOTES:
* [has-edition.xml.txt](https://github.com/jgm/pandoc/files/8365293/has-edition.xml.txt) has been manually adjusted to work as expected with [this recent fix](https://github.com/jgm/pandoc/commit/35350fac85f671079d4ce433263e15de646d55f9)
* [has-edition.md](https://github.com/jgm/pandoc/files/8365283/has-edition.md) was generated by pandoc from [has-edition.bib.txt](https://github.com/jgm/pandoc/files/8365340/has-edition.bib.txt) which in turn was generated by Zotero
* I am not hugely impacted by this but I did notice this info missing when migrating to a JATS XML based workflow

**Comment by tarleb** [comment]
Thanks for the report.
