### ISSUE TITLE
JATS reader not reading doi from citations in ref-list

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#7995]
**REPO STEPS**
With [orig.md](https://github.com/jgm/pandoc/files/8365600/orig.md)
```
cat orig.md \
  | pandoc -f markdown -s -t jats+element_citations --citeproc \
  | pandoc -f jats -s -t markdown \
  > roundtrip.md
```
**GOT**
[roundtrip.md](https://github.com/jgm/pandoc/files/8365604/roundtrip.md)

**EXPECTED**
The `doi` key:value to roundtrip. I wasn't expecting all the citation metadata to roundtrip, but the `doi` is a great identifier and renders the lack of other missing information not so important. But currently, with the lack of doi and other metadata like issue number, issn and pages, the lack of doi makes lookup more difficult.

**EXTRA BONUS**
Would be nice to have `issn`, `issue` and `pmid` also get read by the JATS reader since pandoc is already writing that info to JATS.

**Pandoc version**
2.17.1.1, but repo steps for version [with recent fix](https://github.com/jgm/pandoc/commit/35350fac85f671079d4ce433263e15de646d55f9)

**Comment by castedo** [comment]
That was fast! :+1: I'm looking forward to using the next version in more JATS work flows. Thank you!

**Comment by jgm** [comment]
A few more commits, and now your original example round-trips without loss.
