### ISSUE TITLE
pandoc conversion from latex has issues with \vspace

### ISSUE THREAD

**Issue by AndrewtheCanon** [jgm/pandoc#7996]
Heres the document I am trying to create:

```
\documentclass{article}
\begin{document}
\noindent
Hallo \\
How \\
Are \\
You?

xxxxx

\noindent
Hallo \\
How \\
Are \\
\vspace{15cm}You?


xxxxx
\end{document}
```

`pdflatex latex.tex` is able to correctly parse the document however `pandoc latex.tex -o latex.pdf` doesnt understand `\vspace{15cm}`.

Is there a reason why?

**Comment by jgm** [comment]
Yes - read the last paragraph of this section of the manual:
https://pandoc.org/MANUAL.html#description
There's nothing in the pandoc AST (structural representation of a document) that corresponds to `\vspace{15cm}`.
