### ISSUE TITLE
Latex writer: Longtable Undefined control sequence

### ISSUE THREAD

**Issue by SkryptX** [jgm/pandoc#8001]
There is a bug, which happens, if you start a table-cell with parentheses inside a `longtable`. Something like this will be produced by the Latex writer. This is a minimal failing example not directly from Pandoc, but the `longtable` is a product of Pandoc. Execute it with `latex`.

```
\documentclass{article}
\usepackage{longtable,booktabs}

\begin{document}
\begin{longtable}[]{@{}c@{}}
\toprule
(something in parentheses) \\
\midrule
\endhead
\bottomrule
\end{longtable}
\end{document}
```

This throws an error with "Undefined control sequence..." as described on Stackexchange: ["Undefined control sequence" on left parenthesis after midrule in longtable](https://tex.stackexchange.com/questions/228755/undefined-control-sequence-on-left-parenthesis-after-midrule-in-longtable).

In my opinion there is a simple fix with putting a `\relax` after `\midrule`, `\toprule` and maybe others, since you never have any arguments anyway. This would prevent that error from happening.

Pandoc version: 2.16.2

**Comment by jgm** [comment]
Test case
```
% pandoc -o table.pdf
| (hi) |
|------|
| oo   |
^D
```

**Comment by bollenn** [comment]
As commented in https://github.com/jgm/pandoc/commit/5f0bfd41a80aaf4d05c37357a317a6694ec338ec#commitcomment-72500256 the fix for this issue breaks the workarounds in https://github.com/jgm/pandoc/issues/7421#issuecomment-882497287, do you have any ideas on fixing this?

**Comment by Paladnix** [comment]
I used 2.19.2 and got () at first row after the midrule, how to deal?




> As commented in [5f0bfd4#commitcomment-72500256](https://github.com/jgm/pandoc/commit/5f0bfd41a80aaf4d05c37357a317a6694ec338ec#commitcomment-72500256) the fix for this issue breaks the workarounds in [#7421 (comment)](https://github.com/jgm/pandoc/issues/7421#issuecomment-882497287), do you have any ideas on fixing this?

I used 2.19.2 and got () at first row after the midrule, how to deal?
![image](https://github.com/user-attachments/assets/258d112f-4041-4058-ac80-aa8bdda1b05e)
