### ISSUE TITLE
Regression in +ascii_identifiers

### ISSUE THREAD

**Issue by alerque** [jgm/pandoc#8003]
In #5433 I reported that Turkish undotted-i (`ı`, U+0131) was not getting converted to the expected ascii equivalent. This was subsequently fixed in #5434.

At some point this regressed. It may have been some time ago, but at least testing now in 2.17.1.1 I get a dropped character again.

```console
# Actual
$ pandoc -f markdown+ascii_identifiers -t native
[ Header 1 ( "isk" , [] , [] ) [ Str "I\351\305k" ] ]

# Expected
$ pandoc -f markdown+ascii_identifiers -t native
[ Header 1 ( "isik" , [] , [] ) [ Str "I\351\305k" ] ]
```

**Comment by jgm** [comment]
Looks like the culprit is 052056289fc6f884a2a8799dacca64a16248a5c2

**Comment by jgm** [comment]
```
normalize NFD "\305"
"\305"
```
so we'll need to insert code to special-case this.

**Comment by alerque** [comment]
What `normalize` is in play here? Perhaps this is a fix that needs to be upstreamed somewhere, because it should be the *de facto* behavior for this case. Indeed some other tooling already does this properly, e.g. `iconv`:

```console
$ echo Işık | iconv -f utf-8 -t ascii//translit
Isik
```

**Comment by jgm** [comment]
From unicode-transforms -- this is just applying the unicode standard to decompose an accented glyph into its base character and accents.  In this case, the base character is the undotted i. So that is working fine.

**Comment by alerque** [comment]
Thanks for the fix! I was stuck on an aging version of Pandoc several major versions old for quite a while which explains most of why I didn't catch this earlier. It's nice to be up to date again.

The Turkish undotted i is truly unique in how troublesome it is — such a disastrous chain of alphabet design and encoding decisions...

That being said, it sounds like part of the issue is that *decompose*ing accented glyphs is only part of the equation. Admittedly it is the bulk of the work for most languages, but if the goal is to transliterate and downsample to arrive at an ascii representation just decomposing glyphs and taking the base part isn't enough. Not all languages have good transliteration schemes (and some have more than one), but for those that do it seems like Pandoc exposing a more robust ascii transliteration function would be useful for more than just this one use case.

**Comment by jgm** [comment]
Actually, I wish all alphabets were designed like the Turkish one.  Very rational.

I don't know how to create a more robust ascii transliteration function (one that handles even, e.g. Chinese).
Perhaps a separate Haskell package could be cerated for this purpose, if there are standard ways of doing it.
