### ISSUE TITLE
How to output as I returned in Lua without `\`

### ISSUE THREAD

**Issue by mokeyish** [jgm/pandoc#8004]
**Explain the problem.**
I write a filter as following:
`myfilter.lua`
```lua
function RawInline(el)
  if el.format == 'html' then
    return '<b>hehe</b>'
    -- return el.format
  else
    return el
  end
end
```

`input.md`
```md
<img src="·attachments/image-20220404092331571.png" alt="image-20220404092331571" style="zoom:50%;" />
```

Then execute command:
```shell
pandoc --lua-filter myfilter.lua  -t markdown -f markdown -o output.md input.md
```
The content in `output.md` is
```md
\<b\>hehe\</b\>
```

What I want is without the `\`
```md
<b\>hehe</b\>
```

**Pandoc version?**
pandoc.exe 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2

Windows

**Comment by tarleb** [comment]
Try with `pandoc.RawInline('<b>hehe</b>', 'html')`.

Further questions should best posted to the [pandoc-discuss](https://groups.google.com/g/pandoc-discuss), as we try to reserve this issue tracker for feature requests and bug reports.

**Comment by mokeyish** [comment]
@tarleb Thanks for your replying , but it not work. The output changed to 
```md
`<b>hehe</b>`{=html}
```

**Comment by mokeyish** [comment]
Thanks, it worked.
