### ISSUE TITLE
Caption format in custom-reference.docx Template doesn't work.

### ISSUE THREAD

**Issue by MarioZZJ** [jgm/pandoc#8009]
**Explain the problem.**
Following the [user's guide](https://pandoc.org/MANUAL.html), I got a copy of the default `reference.docx`: 
```shell
pandoc -o custom-reference.docx --print-default-data-file reference.docx
```
And I changed the formats in the `reference.docx`, and exe the command
```shell
pandoc --reference-doc ./custom-reference.docx ./main.md -o ./output.docx
```

However the format of table/image captions in the output docx turned out the default format, not what I defined, while other formats worked properly.

![Example](https://download.mariozzj.cn/img/picgo/202204081343350.png)

**Pandoc version?**
Version of Pandoc: pandoc.exe 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3, citeproc 0.7, ipynb 0.2, hslua 2.2.0

OS: Windows 11 Pro

**Comment by jgm** [comment]
Works fine for me.  Perhaps you don't have the right syntax for the caption, but it's hard to tell without seeing main.md. While you're at it, maybe you could upload your modified reference docx.

**Comment by MarioZZJ** [comment]
Thanks @jgm , I uploaded these files to the cloud, you can [download](https://download.mariozzj.cn/tmp/pandoc8009.zip) them and tell me what's wrong if you like:)

**Comment by jgm** [comment]
OK, it looks like you didn't really modify the "Table Caption" style in the custom-reference.docx. Instead, you simply highlighted "Table Caption" and changed its formatting. You actually have to modify the style, and then it will work.
Format -> Style -> select Table Caption -> Modify
then Save the document

**Comment by MarioZZJ** [comment]
@jgm thanks!
