### ISSUE TITLE
docbook (asciidoctor) task lists

### ISSUE THREAD

**Issue by arcnmx** [jgm/pandoc#8011]
**Explain the problem.**
asciidoctor has a [peculiar way of encoding check lists](https://github.com/asciidoctor/asciidoctor/blob/e497b9fcb06959311dd35d2bd6e11d29efe26f1f/lib/asciidoctor/converter/docbook5.rb#L460):

```
asciidoctor -b docbook5 - <<EOF | pandoc -f docbook -t native
* [ ] a
* [x] b
EOF
[ BulletList <itemizedlist mark="none">
    [ [ Para [ Str "\10063" , Space , Str "a" ] ] <listitem><simpara>&#10063; a</simpara></listitem>
    , [ Para [ Str "\10003" , Space , Str "b" ] ] <listitem><simpara>&#10003; b</simpara></listitem>
    ] </itemizedlist>
]
```

Which is distinct from what pandoc generally produces/expects:
```
pandoc -f gfm -t native <<EOF
- [ ] a
- [x] b
EOF
[ BulletList
    [ [ Plain [ Str "\9744" , Space , Str "a" ] ]
    , [ Plain [ Str "\9746" , Space , Str "b" ] ]
    ]
]
```

The following transforms therefore do not work as expected:

```
asciidoctor -b docbook5 - < example-from-above.adoc | pandoc -f docbook -t gfm
-   ❏ a

-   ✓ b
```

```
asciidoctor -b docbook5 - < example-from-above.adoc | pandoc -f docbook -t asciidoctor
* ❏ a
* ✓ b
```

It's not clear to me whether this is something that would be the [writer's responsibility](https://github.com/jgm/pandoc/blob/7fb74b74df705742001ca583c4070b29e61ea275/src/Text/Pandoc/Writers/AsciiDoc.hs#L355-L363) or if it would make more sense for the docbook reader to parse these?

```
pandoc --version
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.3, citeproc 0.6.0.1, ipynb 0.2
```

EDIT: also what's with the weird spacing on gfm lists after the hyphen?

**Comment by jgm** [comment]
Looks like asciidoctor is using boxes with shadows, where pandoc uses boxes without shadows.

We should be able to modify `taskListItemToAscii` to handle both variations.

**Comment by jgm** [comment]
> EDIT: also what's with the weird spacing on gfm lists after the hyphen?

Pandoc's markdown writer tries to produce markdown that will work with the widest range of processors, and some markdown processors historically have used the "4 space rule," requiring 4 space indent for sublists.  Given this, and the desire that sublists align with the content of the containing list, we just start all list content on 4-space boundaries.

In principle we could override this behavior for gfm/commonmark, since in that case the list nesting behavior is well defined.

**Comment by jgm** [comment]
And yes, the way we handle this currently it's the responsibility of the writer to detect these task lists and format them appropriately.  (Only a few formats have task lists, so in other cases we have a nice fallback behavior.)
