### ISSUE TITLE
Adding stuff after a level 1 title drastically changes the output in reveal.js

### ISSUE THREAD

**Issue by TheTrveAnthony** [jgm/pandoc#8012]
Hi, first of here is my current version : (I use manjaro)
```bash
  ~ $ pandoc --version 
pandoc 2.14.2 
Compiled with pandoc-types 1.22, texmath 0.12.3.2, skylighting 0.11, 
citeproc 0.6.0.1, ipynb 0.1.0.1 
```
Now my actual issue: I have been experimenting with markdown+pandoc+reveal.js and found out that adding a paragraph/list/image/level 3 to 6 title changes the WHOLE presentation, here is a quick example: 

This markdown file : 
```markdown
% Example
% Me and Myself

# A slide

# Another one

## A vertical slide

With some text in it

## Another vertical slide

* With
* A small
* List
``` 

outputs this html file : 
```html
<section id="title-slide">
  <h1 class="title">Example</h1>
  <p class="author">Me and Myself</p>
</section>

<section id="a-slide" class="title-slide slide level1">
<h1>A slide</h1>

</section>

<section>
<section id="another-one" class="title-slide slide level1">
<h1>Another one</h1>

</section>
<section id="a-vertical-slide" class="slide level2">
<h2>A vertical slide</h2>
<p>With some text in it</p>
</section>
<section id="another-vertical-slide" class="slide level2">
<h2>Another vertical slide</h2>
<ul>
<li class="fragment">With</li>
<li class="fragment">A small</li>
<li class="fragment">List</li>
</ul>
</section></section>
```
As you can see, each level 2 title generates a section which creates a vertical slide.
Now, when I add anything after any level 1 title, just like this : 

```markdown
% Example
% Me and Myself

# A slide
Hi, everybody !!!!

# Another one

## A vertical slide

With some text in it

## Another vertical slide

* With
* A small
* List
``` 
I get this output

```html
<section id="title-slide">
  <h1 class="title">Example</h1>
  <p class="author">Me and Myself</p>
</section>

<section id="a-slide" class="slide level1">
<h1>A slide</h1>
<p>Hi, everybody !!!!</p>
</section>
<section id="another-one" class="slide level1">
<h1>Another one</h1>
<h2 id="a-vertical-slide">A vertical slide</h2>
<p>With some text in it</p>
<h2 id="another-vertical-slide">Another vertical slide</h2>
<ul>
<li class="fragment">With</li>
<li class="fragment">A small</li>
<li class="fragment">List</li>
</ul>
</section>
```

If you look closely, the multiple sections are gone, there is only one section per slide, which produces terrible slides. Is it intended to be this way ?
I use this command to generate my slides (the same as in the demo page) : `pandoc -s --mathjax -i -t revealjs slides.md -o slides.html`

Thank you

**Comment by jgm** [comment]
See https://pandoc.org/MANUAL.html#structuring-the-slide-show
You may want to use the `--slide-level` option.

**Comment by TheTrveAnthony** [comment]
Thanks for your quick answer.
I added `--slide-level=2` and everything works great now, thanks a lot and thanks for this insane piece of software, really wish I discovered it earlier !
