### ISSUE TITLE
Cannot load local KaTeX directory without `=` in command line option

### ISSUE THREAD

**Issue by lwang2070** [jgm/pandoc#8013]
**Explain the problem.**
Pandoc cannot produce a self-contained HTML with command-line options as below:

```
pandoc --self-contained --katex dependecies/katex/ test.md -o test.html
```

It will produce the output:

```
pandoc: dependecies/katex/: openBinaryFile: inappropriate type (is a directory)
```

However, with simply one additional `=` sign, it works:

```
pandoc --self-contained --katex=dependecies/katex/ test.md -o test.html
```

Funny enough, this tiny bug ends up costing me 2 days to find the solution. (no sarcasm intended)

**Pandoc version?**
What version of pandoc are you using, on what OS?

Pandoc version:

```
$ pandoc -v
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /Users/a123/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

OS: OSX

```
$ uname -av
Darwin mba.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
```

**Comment by jgm** [comment]
The manual says the syntax is:
```
                        --katex[=URL]                                   
```
`--katex` has an *optional* argument, hence if there is an argument, the `=` is required to disambiguate it.

**Comment by jgm** [comment]
In other words, the `=` is needed because you can just say
```
pandoc --katex myfile.md
```
and here `myfile.md` is definitely not the argument for `--katex`.

**Comment by jgm** [comment]
Reading the manual can save days of work!

**Comment by lwang2070** [comment]
Ahh, I see the reason now. Thanks for your reply.

I think the problem is that the documentation has not been very consistent with its notations. For example, there is this option with an example in the doc:

```
-F PROGRAM, --filter=PROGRAM
pandoc --filter ./caps.py -t latex
```

Although `=` is used in the specification of the option, it is not necessary. Therefore I assumed that all options behave like this. May I suggest either use

```
-F PROGRAM, --filter[=]PROGRAM
```

to indicate that for this option `=` is optional, or add a short sentence for `--katex` option to notify people that `=` is compulsory?

Thanks again!

**Comment by jgm** [comment]
The information that `--katex` takes an *optional* argument, while `--filter` has a mandatory argument, is encoded in the manual:  `--filter=PROGRAM` vs `--katex[=URL]`.  What we don't say explicitly that would have helped you:

1. The `=` isn't needed for options that have  a *required* argument
2. The `=` can't be omitted with an *optional* argument.

I assumed these were standard conventions, but (1) may be idiosyncratic to the Haskell option parsing library I'm using.
I think (2) can be inferred, if you think about it, since without the `=` there would be an ambiguity.
But both of these things should probably be said somewhere.
