### ISSUE TITLE
Zotero citations with multiple input files

### ISSUE THREAD

**Issue by mathias-sm** [jgm/pandoc#8018]
First of all, thanks for the fantastic software, it's been so helpful, so many times!

The recent addition of reading zotero citations was really welcome for my use-cases. However, when converting two or more `docx` which include different Zotero citations, it seems the `citationId` aren't handled properly. See for example the two files [part1.docx](https://github.com/jgm/pandoc/files/8483682/part1.docx) and [part2.docx](https://github.com/jgm/pandoc/files/8483684/part2.docx), which can independently be read and work with `--citeproc` option, but when given together as input produce a warning and an incomplete output:

```bash
$ pandoc -s --from docx+citations part1.docx part2.docx  --citeproc -t plain
[WARNING] Citeproc: citation 309 not found


(309?)

(Fodor 1975)

Fodor, Jerry A. 1975. The Language of Thought. Vol. 5. Harvard

University Press.
```

The addition of the `--file-scope` flag does not seem to help.

**Comment by mathias-sm** [comment]
I just realized that this was, in fact, not related at all to the new Zotero reader, as I can reproduce this with these simple two markdown input files:

```markdown
---
references:
- author:
  - family: Chomsky
  id: 309
  title: Aspects of the Theory of Syntax
---

[@309]
```
and
```markdown
---
references:
- author:
  - family: Fodor
  id: 15
  title: The language of thought
---

[@15]
```

Which gives

```bash
$ pandoc tmp1.md tmp2.md --citeproc -t plain
[WARNING] Citeproc: citation 309 not found
(309?)

(Fodor, n.d.)

Fodor. n.d. “The Language of Thought.”
```

The title of this issue should be changed to reflect that, and maybe the issue can be closed — though my problem remains.

I guess as a fix I can extract the bibliographies from my `docx` files by using `-t bibtex` on each file in a `for f in *.md` loop, merge the resulting bibliographies, and give both files to `pandoc` with the merged bibliography given to `--bibliography`.  But this is not very straightforward and I don't know how robust the `citationId` is to this kind of hack...

**Comment by jgm** [comment]
This is because you have two metadata sections, each defining `references`; the first value for `references` is replaced by the second.

**Comment by mathias-sm** [comment]
Thanks, that makes sense. For the `markdown` version it's pretty transparent and I could see how to fix this, but if I need to merge several `docx` file with different `references` data, is there a way to merge them rather than replace the first one with the second one? In my case I imagine that different `references` sections are arbitrarily modified by Zotero across different files, in a way I barely have control over.

**Comment by jgm** [comment]
You might need a multi-step process.  First, extract a bibliography from each docx file using something like
```
pandoc -f mydoc.docx -t csljson -s -o mydoc.json
```
Then pass these in using `--bibliography` (which can be repeated) when you convert the docx files.

**Comment by mathias-sm** [comment]
Thanks, that's what I came up with so far. I am slightly worried about collisions of the `referenceId` when I merge the bibliographies, as I don't know how Zotero generates those — but maybe this is out of scope for this discussion.

**Comment by jgm** [comment]
I'll close this, then, but if you run into difficulties you can always get back to us.
