### ISSUE TITLE
Redundant Spans in Tables of Contents with self-linked headers

### ISSUE THREAD

**Issue by gwern** [jgm/pandoc#8020]
Pandoc generates redundant and unnecessary `<span>foo</span>` entries in Tables of Contents which are linked in order to make them clickable. eg

    # [foo](#foo)
    
    Bar
    
    # baz
    
    Quux.

will generate

	<nav id="TOC" role="doc-toc">
	<ul>
	<li><a href="#foo"><span>foo</span></a></li>
	<li><a href="#baz">baz</a></li>
	</ul>
	</nav>
	<h1 id="foo"><a href="#foo">foo</a></h1>
	<p>Bar</p>
	<h1 id="baz">baz</h1>
	<p>Quux.</p>

While spans with no attributes/classes/IDs like `<span>foo</span>` *can* be meaningful and employed in JS/CSS (I use a few myself, and so downstream tools like HTML Tidy cannot strip these automatically because it would break stuff), these are not such spans, and it is unlikely anyone would attempt to rely on them given that they are unexpected, undocumented anywhere I could find, and generated only for links in headers and no other kind of Inline I tried. The null spans turn out to be due to a hack in the code using the 'span wrapper trick' to return a `Inline` which is actually an `[Inline]`.

Specifically, they are generated by `sectionToListItem`, which to convert the Header's contents, defines `headerText' = addNumber $ walk (deLink . deNote) ils`; `deLink` tries to do `Inline -> Inline` but how when a Link actually has a payload of `[Inline]`...? Simple, it inserts that payload into a Span:

    ./src/Text/Pandoc/Shared.hs:405:deLink (Link _ ils _) = Span nullAttr ils

This, however, clutters the AST, wasting nodes, making it harder to read, and producing inconsistent structure (before they were all `li`, now they are `li.span` etc).

It would be good if the null spans could not be generated or cleaned up. Given that `headerText'` is simply going to be put into a `Link` as its `[Inline]` payload, there ought to be some way to skip the span wrapper trick. (I see two other uses of what looks like the span wrapper trick in the codebase; both the Citeproc and math uses look like they'd create null spans too.)

**Comment by mb21** [comment]
If you write:

    # [foo](#foo)

you're explicitly asking for a span, see https://pandoc.org/MANUAL.html#divs-and-spans

instead you want:

    # foo

or

    # foo {#customId}

**Comment by gwern** [comment]
No, I'm asking for (and successfully creating, as I have for years now on gwern.net) a link, not a span. A link is `[]()` (not `[]{}`), which is what is used there, and note the generated HTML contains hyperlinks in the headers themselves, with nary a span in sight - the only spans are the null spans in the ToC itself.  An ID would not create a clickable link, and if that was the intention, why does it create a null span with no id or attributes?

For further context, what triggers this issue at scale for me does not involve syntax issues at all (so cannot be "you're explicitly asking for a span", given that neither spans nor syntax are used) but a rewrite pass on the Pandoc AST with `walk` adding self-links to headers to make them, like many websites such as Wikipedia, right-clickable:

	-- | Make headers into links to themselves, so they can be clicked on or copy-pasted easily.
	headerSelflink :: Block -> Block
	headerSelflink (Header a (href,b,c) d) = Header a (href,b,c) [Link nullAttr d ("#"`T.append`href, "Link to section: § '"`T.append`inlinesToString(d)`T.append`"'")]
	headerSelflink x = x

**Comment by jgm** [comment]
I think the "span wrapper trick" was used for performance reasons: a walk on `Inline -> Inline` is going to be faster than one on `Inline -> [Inline]`.

**Comment by gwern** [comment]
I discovered it as about the only way to make unwrapping links work when Inlines were expected, and that fits this usecase, so that was probably it.

I also doubt it was for performance because I find it hard to imagine that this would ever make a measurable performance difference: even if you had documents with header self-links which would trigger `deLink` in the first place (rare, because Pandoc doesn't do it by default), the contents of a Link are going to be small, and there will be only a few of them per document. They will usually be a single Str, or a few Str/Spaces. Maybe the occasional Str inside an italics. Could even microbenchmarking detect the difference between `Inline -> Inline` and `Inline -> [Inline]` when there's maybe a dozen `[Inline]` with lengths under a dozen each?

**Comment by jgm** [comment]
> I also doubt it was for performance

I'm going to claim authorial privilege here, since I wrote the code, I think I know why I worte it that way. Whether it is a good reason is another question. But note that the general function being definde here could apply to links with very large contents.  Your application is not the only one.

**Comment by gwern** [comment]
The death-of-the-author applies doubly when it comes to obscure code with no documentation many years later (there is no mention of perf in the patch 3 years ago introducing it, `9f984ff26ac248a27212a37ab34754a2e9261e8c`, just expanding the API). I sometimes can't figure out a day later why I wrote something.

In any case, while it may have been for performance (it is unlikely it actually was for performance, or still is, given the lack of profiling then, or now), the only use here is cases where it cannot matter to performance, and as such, doesn't justify null spans. The null spans are either good or bad regardless.

**Comment by jgm** [comment]
I'm not going to invest a lot of time arguing about this, doing benchmarks, etc., given that the null spans are completely harmless.  I'm pretty sure that it's more performant in general for this function not to create lots of little lists and concatenate them together.
If the null spans really bother you, a three line Lua filter will suffice to eliminate them.

**Comment by jgm** [comment]
For reference, the commit that actually added this function (as opposed to just exporting it) is 0d83ce3bc4c68efa9d19f065a056d27d9b8ec56d

**Comment by gwern** [comment]
Null spans are not 'completely harmless'. As I said, they lead to inconsistent CSS which can vary confusingly based on something which is completely irrelevant to the final HTML or semantics of the document, and solely due to an undocumented choice Pandoc made for its internal convenience. They also lead to dozens or hundreds of unnecessary DOM elements in the final output, which must be processed every page load by every readers' JS/CSS forever. (A quick estimate of gwern.net pageviews since mid-2018 is >6 million pageviews with something like 8000/1000=8 sections per page so >48 million pageview-spans for just me; which is unfortunate when the layout processing is by far our largest performance bottleneck.) You may regard these as the lesser of evils here, but evil they are.

**Comment by jgm** [comment]
There you go; I hope your readers appreciate the microseconds of reduced latency this will give them!

**Comment by gwern** [comment]
Thanks. This will let me simplify my code a bit as well.

---

I just ran into what might be a related issue. Consider this case:

	# `Foo`{=html}
	
	bar
	
	# Baz
	
	quux

The section link for the second section will, obviously, be `#baz`. What is the section link of the first section? It's equally obviously `#foo`, because 'Foo' as HTML == 'Foo' as Markdown, and all HTML is Markdown. There is zero HTML or Markdown syntax in it. There are no italics, spans, links, or anything whatsoever. And it will render visibly exactly as if only `# Foo` had been written, and one expects the output to be identical. But that turns out to not be the case:

    <h1 id="section">Foo</h1>
    <p>bar</p>
    <h1 id="baz">Baz</h1>
    <p>quux</p>

It is actually `#section`! The ID apparently gets set in the AST and I guess the ID code sees the RawInline and doesn't even try to infer an ID but just gives up?

    [Header 1 ("section",[],[]) [RawInline (Format "html") "Foo"]
    ,Para [Str "bar"]
    ,Header 1 ("baz",[],[]) [Str "Baz"]
    ,Para [Str "quux"]]

This is bad for an enduser because now it matters to the final link targets, no matter that it means the same thing, whether (unbeknownst to them) it ever passed through a Raw node.

**Comment by gwern** [comment]
The problem is I am constructing the AST, so there is no simple way to 'just' set `{#foo}` when I have a snippet of HTML. How do I know what the ID 'would be' if it had been written by hand as Markdown without the RawInline wrapper? Pandoc handles the Markdown->ID conversion normally... Parse it into a Pandoc AST and unwrap the Block to get an [Inline] which can then be `inlinesToString`-ed to a String and then replicate the ID rules, I guess? Ah well.
