### ISSUE TITLE
changelog: wrong release date for pandoc 2.18: 2022-04-22 -> 2022-04-04

### ISSUE THREAD

**Issue by HenrikBengtsson** [jgm/pandoc#8023]
I noticed that https://github.com/jgm/pandoc/blob/master/changelog.md says:

```md
## pandoc 2.18 (2022-04-22)
```

As of writing, this is a future date.  From https://github.com/jgm/pandoc/releases/tag/2.18, it looks like this should be:

```md
## pandoc 2.18 (2022-04-04)
```

**Comment by alerque** [comment]
We from the future salute you all behind in the present.

**Comment by jgm** [comment]
Thanks, don't know why that happened!
