### ISSUE TITLE
Code blocks in the generated pdf files doesn't show up with monotype fonts

### ISSUE THREAD

**Issue by enkeyz** [jgm/pandoc#8025]
**Explain the problem.**
We're using the following shell file - https://github.com/quii/learn-go-with-tests/blob/main/build.books.sh - to generate pdf files from markdown, and the code blocks doesn't show up with monoface fonts.

You can find the pdf here: https://github.com/quii/learn-go-with-tests/releases

**Pandoc version?**
uppalabharath/pandoc-latex-cjk from docker

**Comment by jgm** [comment]
I can't see from a quick glance at this why you'd get those fonts.  But there's not enough information here. Evidently you're changing the default font somehow to a sans serif font, but I don't see anything on your command line that does this.

**Comment by jgm** [comment]
It's possible that this is done in the docker image you're using. In that case, you should direct your question there.
I don't see a pandoc bug.
