### ISSUE TITLE
Lang attributes on div/span are not working with the docx writer

### ISSUE THREAD

**Issue by bramd** [jgm/pandoc#8026]
**Explain the problem.**

When converting from markdown to docx, I expect the lang attributes on divs/spans to be converted in docx language changes, this should be done using the `<w:lang w:val="..."/>` if I understand the spec correctly.

Try the following command:

```
pandoc -s --metadata=lang:nl -o test.docx
Tekst in het Nederlands.
[Text in English]{lang=en}
```

**Pandoc version?**
pandoc 2.18                                                                                                                                                                                                      
Linux

**Comment by jgm** [comment]
Can you link to the relevant part of the spec?
Looks like we don't currently generate w:lang at all; the only reference to it in the code is in a place that overwrites the attributes on w:lang in the styles, if a `lang` is specified in the metadata.

**Comment by bramd** [comment]
Some documentation and an example is provided in Microsofts Office SDK: https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.languages?view=openxml-2.8.1

The element is described in section 17.3.2.20 of the ISO/IEC specification, which is available at: https://standards.iso.org/ittf/PubliclyAvailableStandards/c071691_ISO_IEC_29500-1_2016.zip

The simple version of it seems to be that you can use a `w:lang` element to specify another language for the run from then on. If not given, it will re-use the lang from the previous run element.

**Comment by bramd** [comment]
Just compiled from source and this works as expected, thanks for fixing.
