### ISSUE TITLE
[Latex] Support for `\includesvg`

### ISSUE THREAD

**Issue by MuntashirAkon** [jgm/pandoc#8027]
**Describe your proposed improvement and the problem it solves.**
`\includesvg` (of `svg` package) can be used to directly include SVG files within a TeX file. As far as I understand, this command works exactly like `\includegraphics` except that it converts the SVG file via a third-party commandline tool such as **inkscape**. However, since SVG is already supported via `\includegraphics` in Pandoc, this conversion process can be skipped.

**Describe alternatives you've considered.**
Including SVG images via `\includegraphics` works in Pandoc but not in pdflatex. As a result, it is not very convenient.

**PS:** I would be grateful if someone gives me a hint on how I can do this in Lua script for the time being.

**Comment by MuntashirAkon** [comment]
Related issue #7906

**Comment by jgm** [comment]
A workaround would be to add

`\def\includesvg\includegraphics`

to your LaTeX when you process it with pandoc.

**Comment by MuntashirAkon** [comment]
> when you process it with pandoc.

Is there any macro I can use to enable this behaviour specifically for Pandoc?

**Comment by jgm** [comment]
No.  You might be able to put this definition in a separate file, though, and include this on your command line prior to your tex file.

**Comment by MuntashirAkon** [comment]
> No. You might be able to put this definition in a separate file, though, and include this on your command line prior to your tex file.

Yeah, that's what I've decided to do if there were no other options. But you should consider it. `tex4ht`, for example, defines `\HCode` macro.

**Comment by jgm** [comment]
How does `\HCode` work?

**Comment by MuntashirAkon** [comment]
> How does `\HCode` work?

For example, you can choose not to display ToC in tex4ht by the following:

```tex
\ifdefined\HCode
    % Don't display table of contents for tex4ht
\else
    \tableofcontents
\fi
```

**Comment by jgm** [comment]
That's a nice idea. Actually, looks like we don't support `\ifdefined` yet, but we should try to.
It's a separate topic from this issue though, can you submit a new issue for that?
