### ISSUE TITLE
v2.18 DOCX writer splits up and re-arranges content when joining other DOCX files

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc#8031]
We are using Pandoc to pre-format and compile conference proceedings. One step in that process is to compile all submissions into a single DOCX file. When we tested that setup, we found that one of our input files was split up and its contents re-arrangend out-of-order in the output: its title and author were moved to the top of the output file, even though that input file in question was not the first one given on the command line; its remaining contents were placed in-order as expected. We expected for the contents of all files to be concatenated in the order the files were given on the commandline.

I was able to derive a minimal working example from that input file, which conists of a title, an author, and a paragraph only: [mwe.docx](https://github.com/jgm/pandoc/files/8531515/mwe.docx)

As far as we can tell, the content of the other files is immaterial. I have used this one for testing: [dummy.docx](https://github.com/jgm/pandoc/files/8531524/dummy.docx)
 
Given these two files, the behaviour can be reproduced by:

```sh
pandoc -o joined.docx dummy.docx mwe.docx
```

The resulting output file: [joined.docx](https://github.com/jgm/pandoc/files/8531534/joined.docx)

The behaviour only occurs if the input files are in DOCX or Pandoc's own JSON format.

We are using Pandoc v2.18 and were able to reproduce the issue on macOS v12.3.1 and Debian GNU/Linux v11.3.

**Comment by jgm** [comment]
A single pandoc document can only contain one (metadata) title and author list. The one from the second file is overwriting the one from the first, but the important point is that you can't have both.

One solution would be to make sure that you don't use the Title and Author styles in the input files; that will prevent these from being taken as document metadata.

**Comment by odkr** [comment]
Oh, I wasn't aware that Pandoc was *that* smart. I had suspected that Pandoc was using the document's metadata, but the input file didn't contain any, so I dismissed the thought. Thanks for the swift reply! I'll just throw out the metadata block with a Lua filter.
