### ISSUE TITLE
itemization and a custom Lua writer to convert markdown to LaTeX

### ISSUE THREAD

**Issue by awa5114** [jgm/pandoc#8032]
I am trying to make my own customized writer for LaTeX. In this writer, I’d like to be able to handle itemizations with nesting and write those properly to LaTeX’s itemize environment. Here’s what I have so far:

# Writer file custom_writer.lua

```
function Header(lev, s, attr)
    level_sequences = {
        "section",
        "subsection",
        "subsubsection",
        "subsubsubsection"
    }
    return string.format("\\%s{%s}", level_sequences[lev], s)
end

function Blocksep()
    return "\n\n"
end

function Para(s)
    return s.."\n\n"
end

function Str(s)
    return s
end

function Space()
    return " "
end

function BulletList(items)
    print("entering BulletList function")
    for i, item in pairs(items) do
        print(i, item)
    end
    return " "
end

function Plain(s)
    return s
end

function Doc(body, metadata, variables) 
    return body
end
```

# Markdown file test.md

```
# A section

## A subsection

- An item
    - A subitem
    - A subitem
- An item
```
# Question

Note the `print` statements in the `BulletList` function of my Lua file. To my surprise, when I compile using `pandoc test.md -t custom_writer.lua -o test.tex` I get the following output:

```
entering BulletList function
1    A subitem
2    A subitem
entering BulletList function
1    An item


2    An item
```

There are two things that strike me here:

- The nested list appears to be processed first, before the outer list. This seems counter-intuitive to me. I can’t think of an algorithm which would result in the correct LaTeX nesting if it goes inner to outer. Why does this occur? Can I get it so that it goes the other way round?
- Two blank lines are printed out between `1 An item` and `2 An item`. Where do these come from? I haven’t specified them anywhere in my Lua file.

**Comment by jgm** [comment]
Oh, I see you did post it there.  Closing this.

**Comment by awa5114** [comment]
@jgm are there any plans to move th Q&A to something more modern/easy to use than google groups? There are so many better options like Gitter, Slack or Githyb discussions...

**Comment by jgm** [comment]
I'm intrigued by GitHub discussions, but there are some advantages to the current setup:

1)  pandoc-discuss has a complete searchable history going back 15 years; we'd lose that
2) pandoc-discuss can be used as a standard old-fashioned email list -- in fact, that's how I prefer to use it -- and you don't need a Google account to use it that way.  GitHub discussions is great for people who have GitHub accounts, but I assume many pandoc users don't.
