### ISSUE TITLE
RIS input fails with more than one entry

### ISSUE THREAD

**Issue by bwiernik** [jgm/pandoc#8034]
**Explain the problem.**
I am trying to convert a RIS file to CSL JSON. The conversion works correctly if I have a single item in the RIS file. But fails at the second item if I have more than one.

Reprex:
```
pandoc test.ris.txt -f ris -s -t csljson
```

[test.ris.txt](https://github.com/jgm/pandoc/files/8541992/test.ris.txt)

Produces error:
```
Error at 'test.ris.txt' (line 55, column 1):
unexpected 'T'
expecting end of input
TY - JOUR
^
```

**Pandoc version?**
2.18

**Comment by jgm** [comment]
Two lines in this input are problematic for pandoc's parser.

- the blank line
- the line `DB -` (with no content)

If you remove those, it will work.
Presumably we should make the parser more forgiving.

**Comment by bwiernik** [comment]
Thanks. This came from Embase.

Blank lines between items seem pretty common in RIS files in my experience. I've not see many examples of RIS files with blank fields, but it seems like it would be safe to silently drop them if they occur.
