### ISSUE TITLE
gfm: line wrapping interaction with hard_line_breaks

### ISSUE THREAD

**Issue by arcnmx** [jgm/pandoc#8035]
**Explain the problem.**

Newlines generated due to `--wrap=auto` mangle the output when combined with `+hard_line_breaks`:

```bash
$ for i in {0..20}; do echo hello; done | pandoc -f gfm -t gfm+hard_line_breaks
hello hello hello hello hello hello hello hello hello hello hello hello
hello hello hello hello hello hello hello hello hello
$ for i in {0..20}; do echo hello; done | pandoc -f gfm -t markdown+hard_line_breaks
hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello
```

Using `--wrap=preserve` is even worse!

**Pandoc version?**

pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.3, citeproc 0.6.0.1, ipynb 0.2

EDIT: sorry, just realised my version is out of date - I'd appreciate if someone with 2.18 could let me know if this is no longer relevant

**Comment by jgm** [comment]
Still relevant with 2.18 - but now fixed in HEAD.
