### ISSUE TITLE
Handling of figure element within html5 

### ISSUE THREAD

**Issue by jjsarton** [jgm/pandoc#8038]
**Explain the problem.**

```
:::{.twoColumns}
![pict 1](pict1.jpg)
![pict 2](pict2.jpg)
:::
```
create the html5 code:
```
<div class="twoColumns">
 <p>
  <img ...>
 < img ...>
</p>
</div>
```
I expect to have:

```
<div class="twoColumns">
  <figure>
    ...
  </figure>
 <figure>
   ...
 </figure>
</div>
```
Not inserting an <p> Element, there is no paragraph here and using figure as generated as this is done if I don't use raw html or ::: is the right way.

**Pandoc version?**
What version of pandoc are you using, on what OS?
Linux:  version 2.14.0.3

**Comment by jgm** [comment]
Put a blank line between the two images.
According to the manual, only an image that is by itself in a paragraph will be treated as an implicit figure.
