### ISSUE TITLE
Author list at Zenodo

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#8046]
Hi, I noticed that the author list is gone in pandoc 2.18 on Zenodo, comparing

pandoc 2.17.1.1:
https://zenodo.org/record/5932785

pandoc 2.18:
https://zenodo.org/record/6412662

Is it intensional? Thanks.

**Comment by jgm** [comment]
I have no idea what zenodo is and I have nothing to do with it.
You should check with them.  nothing has changed on the pandoc side.

**Comment by ickc** [comment]
That is a surprise. I understand the author may not be able to take control of every down-stream distributions, like pandoc package in apt, etc.

But Zenodo associates a doi to a piece of software, so work in software can be cited. I'm not sure how common it is for non-author adding a package to Zenodo, but it seems odd.

E.g. in academic writing, it would be odd if you write the paper but the doi is not created by you and you have no idea how people can cite your work?

Would you consider in taking control of pandoc's Zenodo record?
