### ISSUE TITLE
Pandoc 2.14 incorrectly reversing smart quote direction when adjacent to parentheses

### ISSUE THREAD

**Issue by charukiewicz** [jgm/pandoc#8052]
**Explain the problem.**

I have a Hakyll (Haskell static site generator) project that uses Pandoc to generate .html files (using .html files as the initial content as well as the templates). The issue is that the smart quotes that are generated are facing the wrong direction when the quote is preceded by a parentheses.

**Input:**  `(<normal quote>some text<normal quote>)`

**Expected output:** `(<open smart quote>some text<close smart quote>)`

**Actual output:** `(<close smart quote>some text<close smart quote>)`

I originally posted this issue in the Hakyll repository (jaspervdj/hakyll#928) but was directed here after we isolated the problem to the version of `pandoc` specifically.

### Test 1 (Hakyll 4.14 vs Hakyll 4.15)

Here's an example of the issue (note that Hakyll 4.14 uses Pandoc 2.11, whereas Hakyll 4.15 used Pandoc 2.14):

![](https://user-images.githubusercontent.com/6189390/160223358-4758860b-42d1-4d0d-8ba5-fdeb2c11e640.png)

In case it isn't visible in the diff screenshot, here's the `pandoc 2.11` text:

```
Foxhound Systems, LLC (“we” or “us” or “our”)
```

and here's the `pandoc 2.14` text:

```
Foxhound Systems, LLC (”we” or “us” or “our”)
```

This is displayed on the page as:

![Screenshot from 2022-03-25 22-40-51](https://user-images.githubusercontent.com/6189390/160223419-97acc3b3-5030-4c00-a4ac-d4a0031f4d20.png)

### Test 2 (Hakyll 4.15, Pandoc 2.14.0.3 vs Hakyll 4.15, Pandoc 2.11)

Below is another example where everything was identical except `pandoc == 2.11` was added as a constraint to the .cabal file:
 
See screenshot below (red/top is `pandoc` version 2.14.0.3, bottom/green is with `pandoc == 2.11`).

![Screenshot from 2022-04-29 15-22-22](https://user-images.githubusercontent.com/6189390/166064028-b1b2f4a8-b728-4aee-ad80-3b8ce8046541.png)

**Pandoc version?**

Pandoc 2.14, Linux

**Comment by jgm** [comment]
It would be helpful if you could reproduce the problem just using pandoc. I was not able to (using pandoc 2.18, the latest version).
```
% pandoc
("hi")
^D
<p>(“hi”)</p>
```
That looks right.

**Comment by jgm** [comment]
If you don't have pandoc 2.18 installed, you can use the online [try pandoc](https://pandoc.org/try).

**Comment by wdscxsj** [comment]
Here is a somewhat related example (in Chinese) using [try pandoc](https://pandoc.org/try).

Markdown input:

```md
他说：“‘刺马’一案，**传言纷纷**。”
```

Expect output in plain text:

```
他说：“‘刺马’一案，传言纷纷。”
```

Actual output:

```
他说：“’刺马’一案，传言纷纷。”
```

With a slightly modified input:

```md
他说：“这‘刺马’一案，**传言纷纷**。”
```

, the output is correct:

```
他说：“这‘刺马’一案，传言纷纷。”
```

**Comment by jgm** [comment]
I have trouble seeing the difference: could you state verbally which quote gets changed and how?

**Comment by jgm** [comment]
Thanks!

**Comment by wdscxsj** [comment]
By the way, the "Compare Active File With..." command of VSCode is quite handy:

![Screenshot181](https://user-images.githubusercontent.com/863369/177290265-d0321861-8adc-4ac9-be8b-141672094db6.png)

**Comment by jgm** [comment]
Here's the root of the problem:
```
Prelude Data.Char> isAlphaNum '一'
True
```
The Haskell function `isAlphaNum` is classifying '一' as alphanumeric.  I assume this is a mistake?

**Comment by wdscxsj** [comment]
> The Haskell function `isAlphaNum` is classifying '一' as alphanumeric. I assume this is a mistake?

I don't think so. `他说：“‘刺马’案，**传言纷纷**。”` has the same issue, where `案` is not alphanumeric.

**Comment by jgm** [comment]
案 also has Unicode class Lo.
("other letter")

**Comment by wdscxsj** [comment]
Or, is there any way to keep the original quotes, i.e., don't make them straight?

**Comment by jgm** [comment]
`-f markdown-smart` will do it.

**Comment by tarleb** [comment]
It appears that the only other way to solve this was to localize Markdown for East Asian languages, which is likely out of scope. I'm closing this for now.
