### ISSUE TITLE
Bug: found character that cannot start any token

### ISSUE THREAD

**Issue by finisky** [jgm/pandoc#8056]
Pandoc version: 2.18, Ubuntu 20.04.4 LTS

I construct a minimum version `a.md` to reproduce the issue:

````markdown
begin.

---
first:
```
test
```

---

end
````

Run pandoc 2.18 (pandoc 2.14.0.3 works fine):

```shell
$ pandoc -f markdown -t html a.md
YAML parse exception at line 2, column 0,
while scanning for the next token:
found character that cannot start any token
```

Seems that the bug is around line 3~5: `---`, `:` and triple backtick cannot be appeared at the same time.

There are several ways to bypass the bug:

* Add a blank line after `---`:

````markdown
---

first:
```
````

* Remove or replace the `:`

````markdown
---
first.
```
````

* Remove the trailing `---`

````markdown
begin.

---
first:
```
test
```

end
````

**Comment by jgm** [comment]
The problem here is that
````
first:
```
test
```
````
is not valid YAML. (Try pasting iit into http://www.yamllint.com or another validator.)
The parse exception is reported relative to the beginning of the YAML section, so it refers to ` ``` `.
