### ISSUE TITLE
Release 2.18 is gone from releases list

### ISSUE THREAD

**Issue by marcaurele** [jgm/pandoc#8062]
The tag is present on `2.18` but the release list does not show that version `2.18`, and state `2.17.1.1` as the latest one. The `2.18` is available with its content when looking at the tag release list here: https://github.com/jgm/pandoc/releases/tag/2.18

:shrug:

**Comment by jgm** [comment]
Seems to be a bug on GitHub's end?  I didn't do anything to change this.

**Comment by jgm** [comment]
I created a ticket here:
https://support.github.com/ticket/personal/0/1621363

**Comment by jgm** [comment]
Seems to be fixed now.
