### ISSUE TITLE
Unexpected <p> element wrapper in unordered list items

### ISSUE THREAD

**Issue by springuper** [jgm/pandoc#8066]
**Explain the problem.**

In the previous versions of Pandoc, at least in Pandoc 2.5, the following markdown:

```markdown
<div style="display: flex; align-items: center;">
  <div style="flex: 3;">

* foo
* bar
* baz

  </div>
  <div style="flex: 1;">
    <img xxx />
  </div>
</div>
```

will generate html like this:

```html
<div style="display: flex; align-items: center;">
<div style="flex: 3;">
<ul>
<li>bar</li>
<li>foo</li>
<li><p>baz</p>
</div>
<div style="flex: 1;">
<img title="too few tasks" src="images/dev-process-too-much-stuff-waiting-for-review.png" width="100%" height="auto" />
</div></li>
</ul>
</div>
```

it doesn't look so right but the UI looks ok.

In the latest MacOS version, 2.18, we found the output changes to:

```html
<div style="display: flex; align-items: center;">
<div style="flex: 3;">
<ul>
<li><p>bar</p></li>
<li><p>foo</p></li>
<li><p>baz</p>
</div>
<div style="flex: 1;">
<img title="too few tasks" src="images/dev-process-too-much-stuff-waiting-for-review.png" width="100%" height="auto" />
</div></li>
</ul>
</div>
```

The UI doesn't look good any more.

In contrast, ordered list works well all the time:

[demo](https://pandoc.org/try/?text=list%3A%0A%0A%3Cdiv+style%3D%22display%3A+flex%3B+align-items%3A+center%3B%22%3E%0A++%3Cdiv+style%3D%22flex%3A+3%3B%22%3E%0A%0A1.+bar%0A2.+foo%0A3.+baz%0A%0A++%3C%2Fdiv%3E%0A++%3Cdiv+style%3D%22flex%3A+1%3B%22%3E%3Cimg+title%3D%22too+few+tasks%22+src%3D%22images%2Fdev-process-too-much-stuff-waiting-for-review.png%22+width%3D%22100%25%22+height%3D%22auto%22+%2F%3E%3C%2Fdiv%3E%0A%3C%2Fdiv%3E&from=markdown&to=html5&standalone=0)

**Pandoc version?**

```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /Users/shangchun/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```
I'm using MacOS 10.15.7.

**Comment by mb21** [comment]
Minimal repro:

```
<div>
* foo
* bar
* baz
  </div>
```

When removing the two spaces before the closing `</div>`, the list is correctly parsed as a tight list without paragraphs.

**Comment by jgm** [comment]
The way to work around this with `-f markdown` is to use a raw attribute.
````
```{=html}
<div style="display: flex; align-items: center;">
  <div style="flex: 3;">
```

* foo
* bar
* baz

```{=html}
  </div>
  <div style="flex: 1;">
    <img xxx />
  </div>
</div>
```
````

Alternatively, you can remove the indentation before the div tags.

**Comment by springuper** [comment]
Thank you so much, it works now!
