### ISSUE TITLE
Add snap package support

### ISSUE THREAD

**Issue by rsdoiel** [jgm/pandoc#8074]
**Describe your proposed improvement and the problem it solves.**

Installing a recent version of Pandoc on Debian/Ubuntu/Raspberry Pi systems as a package is a problem unless you're OK with installing from source. The snap package format provides support for installation of programs across various Linux distributions and even IoT devices. It'd be nice to support this, even just binary installs, via snap.

**Describe alternatives you've considered.**

Researchhacking (on GitHub) has a pandoc-snap implemented. It's basic, only installs from the released binaries. It'd be a starting point for distributing Pandoc officially as a snap. See https://github.com/researchhacking/pandoc-snap.

**Comment by jgm** [comment]
I don't know anything about this system.  It does sound useful, but I don't know what is involved in creating or distributing a snap.  I wouldn't want to add a lot to our current release burden.  If someone wants to create a prototype and let me know what I'd have to do to distribute it, I'd consider it.

**Comment by rsdoiel** [comment]
Thanks jgm. I'll see if I can work with researchhacking and come up with something useful.  Right now I am trying to grok a bit of haskell to understand the build issues as well as learning snapcraft myself.  All the best, Robert

**Comment by jgm** [comment]
We build our own binary releases (see Releases in this repo).
So presumably the snap would not need to do any Haskell building; it would just need to download the official binary release.

**Comment by rsdoiel** [comment]
Thank you, I'll continue working with researchhacking to build a pandoc snap that using this approach. Does save on getting the GHC environment just right. Cheers Robert
