### ISSUE TITLE
Figure not centered in PDF output when figure has no caption. 

### ISSUE THREAD

**Issue by jfab-123** [jgm/pandoc#8075]
**Explain the problem.**
I have the following markdown file: 
```pandoc
---
title: Test
---

This is a test image: 

![caption](test.png)

```
When I output to pdf, the image is converted to latex via a figure environment and thus is rendered in the center of the pdf. When I remove the caption and change the line to ```![](test.png)```, at first it appears the same but the image is no longer converted with a figure environment. The image appears to be centered just because its width is the same as the pdf width. 

I changed the ```default.latex``` template such that the images in pdf output have smaller width because I think they are too big for me. So in ```default.latex``` i have the following code: 

```latex
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=0.8\maxwidth,height=0.8\maxheight,keepaspectratio}
```

When my figures have a caption, this is not a problem because the figure environment centers the image and it looks just how I want it. This doesn't happen when I don't have a caption and the image is flushed to the left of the pdf. This happens because in the .tex file that is used to produce the pdf, no caption means a ```\includegraphics{...}``` is inserted instead of a figure environment. 

Here is a picture of my problem: 

Image with caption
![](https://user-images.githubusercontent.com/81712003/168646106-59b894bc-d7b4-44a9-b979-f301a34752ce.png)

Image with no caption: 
![](https://user-images.githubusercontent.com/81712003/168646226-3186722f-8135-40f0-b95c-53dada8adf2f.png)

**Pandoc version?**

OS: Arch linux
Version: pandoc 2.17.1.1

**Comment by jgm** [comment]
Trust me, there are people who don't want their images in figure environments.
