### ISSUE TITLE
Using "containsverbatim" instead of "fragile" in LaTeX frames

### ISSUE THREAD

**Issue by felixschulz385** [jgm/pandoc#8080]
> pandoc 2.17.1.1

I need to pass the option "containsverbatim" instead of "fragile" to a beamer frame. This currently appears not to be possible. This would allow me to print `\end{frame}` inside a LaTeX listing without it being falsely evaluated.

I would imagine it to work like:

```
# Heading {frameoptions="containsverbatim"}
```

Resulting in the following LaTeX code:

```
\begin{frame}[containsverbatim]{Heading}
...
\end{frame}
```

However, this currently results in:

```
\begin{frame}[fragile,containsverbatim]{Heading}
...
\end{frame}
```

which does not work because "fragile" and "containsverbatim" work mutually exclusive in LaTeX. Would it be possible to add a check like:

```
isNothing (lookup "containsverbatim" kvs)
```

when adding "fragile" to the `optionslist` in `src/Text/Pandoc/Writers/LaTeX.hs`?

i.e.:

```
let optionslist = ["fragile" | fragile
                               , isNothing (lookup "fragile" kvs)
                               , isNothing (lookup "containsverbatim" kvs)
                               , "fragile" `notElem` classes] ++
                               ...
```

**Comment by felixschulz385** [comment]
Thank you for your quick reply! My underlying problem has been discussed with the developers of beamer [here](https://tex.stackexchange.com/questions/73366/a-line-in-the-lstlisting-environment-cannot-start-with-endframe-in-a-beamer). It boils down to this .Rmd code:

````
---
output:
  beamer_presentation:
    pandoc_args: "--listings"
    latex_engine: lualatex
---

# Header

```
\end{frame}
```
````

which fails to compile and throws this error:

> ! Missing } inserted.
> <inserted text> 
> }
> l.105 \end{frame}

In the thread, two solutions to the problem are proposed on the side of LaTeX/beamer:

1) Placing the entire frame inside a box to hinder beamer from evaluating the call of `\end{frame}` inside a listing. This appears to be the preferred approach when writing the LaTeX yourself. However it appears to be hard to implement in pandoc (or at least I would think so).

2) Choosing to use the legacy `containsverbatim` instead of `fragile`. This appears to be an easier fix to implement. I however also understand that it is based on a solution that should not work, is in itself outdated and not documented by beamer (anymore).

What do you think? Is there a way to fix this issue on the side of the pandoc LaTeX-writer?

**Comment by jgm** [comment]
Yes, we can make `containsverbatim` work.

**Comment by felixschulz385** [comment]
Many thanks!
