### ISSUE TITLE
Guide to migrate from `pandoc-citeproc` API to `pandoc`/`citeproc` proper

### ISSUE THREAD

**Issue by andreasabel** [jgm/pandoc#8081]
`pandoc-citeproc` is retiring, but neither `citeproc` nor `pandoc` seem to replicate its API so they could be serve as a drop-in replacement.
I am wondering how to migrate from the `pandoc-citeproc` API.  Is there a migration guide or a tutorial?

Specifically, I wonder how to substitute for calls to `processCites`: https://hackage.haskell.org/package/pandoc-citeproc-0.17.0.2/docs/Text-CSL-Pandoc.html#v:processCites

The code I wish to migrate is given here:
- https://github.com/plfa/plfa.github.io/issues/649#issue-1241837603

**Comment by jgm** [comment]
`processCitations` from Text.Pandoc.Citeproc is just like `processCites'`.

We don't export anything that takes a Style as a parameter, like `processCites` did.  But if you need this, we might be able to export a suitable function from the things we already define.

**Comment by jgm** [comment]
In the code you linked, you're just parsing the style from a file.
So you could just add this as `csl` field in the document's metadata.
As for references, you can either specify `bibliography` in the metadata (and then it will read them from a file) or insert references in the `references` field of the document's metadata.

**Comment by tarleb** [comment]
The corresponding issue appears to be closed, so I'm assuming that the question has been answered. Please reopen if that is not the case.

**Comment by andreasabel** [comment]
> The corresponding issue appears to be closed, so I'm assuming that the question has been answered. Please reopen if that is not the case.

For me, the question is no longer relevant; so, yes, closing is fine.
