### ISSUE TITLE
Add the possibility to write custom readers in python

### ISSUE THREAD

**Issue by me-kell** [jgm/pandoc#8082]
As far as I understand it `Text.Pandoc.Readers.Custom` is the bridge to custom readers written in Lua.
I would be very helpful to have the possibility to write custom readers in python.

Maybe this feature request should be posted in pandocfilters?

**Comment by tarleb** [comment]
The feature would require that pandoc includes (or links) a python interpreter and hence out of scope.

I assume you also asked about this on StackOverflow, see [my answer there](https://stackoverflow.com/a/72330635/2425163)

**Comment by jgm** [comment]
If you just want to use some Python libraries in your reader, maybe you could try
https://github.com/bastibe/lunatic-python
