### ISSUE TITLE
Markdown FrontMatter parse problem when generating ePub

### ISSUE THREAD

**Issue by hoijui** [jgm/pandoc#8091]
Multi-line `title` is not recognized with `-t epub` or `-t epub3`,
but is successfully parsed and used when generating Latex/PDF.

pandoc 2.17.1.1 on debian testing

testing script:

```bash
#!/bin/sh

pandoc --version

echo
echo "This prints a warning:"
# [WARNING] This document format requires a nonempty <title> element.
echo '---
title: |
       | bla
---
' | pandoc -t epub -o /dev/null

echo
echo "This works fine (No warning):"
echo '---
title: bla
---
' | pandoc -t epub -o /dev/null

echo
echo "This works fine (No warning):"
echo '---
title: |
       | bla
---
' | pandoc -t latex -o /dev/null
```

output:

```
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/user/.pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

This prints a warning:
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to '-' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".

This works fine (No warning):

This works fine (No warning):
```

**Comment by mb21** [comment]
Can you try with the newest pandoc version? See https://pandoc.org/installing.html

**Comment by hoijui** [comment]
Just did, and same result:

```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /home/user/.pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

This prints a warning:
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to '-' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".

This works fine (No warning):

This works fine (No warning):
```

**Comment by mb21** [comment]
Thanks, ah... don't think that's a bug. If you run:

```
echo '--- 
title: |
       | bla
---
' | pandoc -t native -s
```

the output is:

```
Pandoc
  Meta
    { unMeta =
        fromList
          [ ( "title" , MetaBlocks [ LineBlock [ [ Str "bla" ] ] ] ) ]
    }
  []
```

as you can see, the YAML string is parsed as markdown, and then the second `|` is picked up as a [line block](https://pandoc.org/MANUAL.html#line-blocks).

What you seem to want is to use only one `|` to start the YAML block, then use normal markdown (indented by two spaces):

```
--- 
title: |
  first paragraph

  second paragraph
---
```

**Comment by hoijui** [comment]
Ahh... in my actual content, I was using Markdown (a link), which works fine for PDF, but yeah.. makes sense that epub does not support anything else then plain-text.

So that explains it, but how could we prevent others (probably including me in the future) to not run into this problem again?
Would it be possible to fail-fast somehow, e.g. if a markdown title is detected with epub as the output, raise an error and fail?

**Comment by mb21** [comment]
I think the EPUB writer attempts to `stringify` (from `Text.Pandoc.Shared`) the markdown text... but it's possible that in some cases this will lead to an empty string which will cause a warning...

**Comment by jgm** [comment]
The warning is actually coming from the HTML writer, which writes the pages.  The EPUB itself contains the title in its metadata.

But the HTML writer uses docTitle from T.P.Definition (pandoc-types), and that won't extract inlines from a LineBlock.

I don't know whether this is worth making any changes for.  In principle we could modify docTitle, or (easier) modify the HTML writer to use a different method for extracting the title (like the EPUB writer does).  But who is going to intentionally use a line block for the title?

**Comment by hoijui** [comment]
hehe :D
... you sain' me stupid or somethin? ;-) (no offense taken)

I just tried using the style mb21 suggested, and that generally works, except in my (more special) case, see issue #8095.

I don't know how I got the idea to use the line-block style, but as this was the main cause of my issue, and it seems unlikely others will use it, I am fine with closing this issue.
