### ISSUE TITLE
Pandoc spawns infinite instances before crashing

### ISSUE THREAD

**Issue by GrimJu** [jgm/pandoc#8093]
OS: Windows 10 21H2
Version: 2.18 according to chocolatey, I can't run `pandoc --version` 

This is probably a chocolatey bug but I decided to report it here anyway.
This may be a duplicate of #5646.

When running any pandoc command (even just `pandoc --version`) and infinite amount of pandoc shims spawn. It even crashes task manager and only stops when RAM (and maybe pagefile) are full and it decides to crash.

**Comment by GrimJu** [comment]
I just tested the Version from the github installer and everything works fine.
It's definitly a chocolatey issue.

**Comment by mb21** [comment]
> It's definitly a chocolatey issue.

thanks, then we'll close this issue...
