### ISSUE TITLE
markdown images without valid path targets are excluded from docx output

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#8099]
We are observing an issue with docx output whereby images must exist prior to calling Pandoc (or they are substituted with their description). This is likely by design but does interfere w/ some more dynamic rendering pipelines (described below).

Consider the following files:

```
elephant.png
subdir/doc.md
```

Where the content of `subdir/doc.md` is:

```
![](../elephant.png)
```

Rendering to docx as follows gives a warning:

```bash
$ pandoc subdir/doc.md --to docx --output doc.docx
[WARNING] Could not fetch resource ../elephant.png: replacing image with description
```

Note that this does not occur for other compound file formats like pdf and epub.

In the case of our application, we are appending together a bunch of .md files (which could be in various sub-directories) and have a Lua filter that fixes up all of the paths so that they are relative to the working directory where pandoc is called from. However, in the case of docx our filter never sees the path so fails to include the image. It would be terrific if docx would tolerate the missing file and allow the Lua filters to fix up the path.

The repro described above can be found at <https://github.com/jjallaire/docx-image-paths>

**Comment by jjallaire** [comment]
Note that there is something about the ".." in the path that triggers this behavior because if I move the `elephant.png` into `subdir` (and fix the image to be `![](elephant.png)`) then things work correctly.

**Comment by tarleb** [comment]
Maybe the `rebase_relative_paths` extension could help here (`--from=markdown+rebase_relative_paths`). That should tell pandoc to look for resources relative to the input document.

**Comment by jjallaire** [comment]
In our case though we are actually passing the markdown as one concatenated file (and passing that file on stdin) so I don't think `rebase_relative_paths` would work.

**Comment by jgm** [comment]
I'm not really understanding the problem.  docx rendering happens last, after filters, so how can the docx rendering mess up what you're trying to do with filters?

The message "replacing image with description" comes from `fillMediaBag`.  I guess we don't use that for PDF and EPUB output (probably mostly because these modules were written before we had a media bag).

If you're concatenating markdown files that live in different directories, then the information needed for relative path resolution is just going to be lost, isn't it?

**Comment by jjallaire** [comment]
The problem is that as a result of the file path not being resolved the `Image` is removed entirely from the AST (and replaced by a `Span` of class `image`). I updated the example repo with this filter:

```lua
function Pandoc(doc)
  print(pandoc.write(doc, "native"))
end
```

Re-running demonstrates the issue:

```bash
$ pandoc subdir/doc.md --to docx --output doc.docx --lua-filter filter.lua
[WARNING] Could not fetch resource ../elephant.png: replacing image with description
[ Para [ Span ( "" , [ "image" ] , [] ) [] ] ]
```

In terms of relative path resolution after combination, we inject our own metadata into the concatenated file that our lua filters use to do the fixups.

**Comment by jgm** [comment]
Ah yes.  This is coming from Text.Pandoc.App around line 313:
```hs
            >>=                                     
              (   (if not (optSandbox opts) &&
                      (isJust (optExtractMedia opts)
                       || writerNameBase == "docx") -- for fallback pngs
                      then fillMediaBag         
                      else return)
```
So the AST is being modified before the docx writer gets to it, and before filters are run.

**Comment by jgm** [comment]
The `writerNameBase == "docx"` condition was added in commit 51caa8b78d66ac81253766cc2c6916d39c14efc2
which explains the rationale.

**Comment by tarleb** [comment]
Alternatively we could expose the `fillMediaBag` function as `pandoc.mediabag.fill` and ask filter users to use that instead. It would be as simple as adding

```
return {
  { Pandoc = pandoc.mediabag.fill },
  -- other filters go here
}
```

**Comment by tarleb** [comment]
The idea is explored in #8104.

**Comment by rddaz2013** [comment]
The warning "markdown images without valid path targets are excluded" still exists not as an error but as a 'feature' when switching between Windows (no WSL) and Linux installation of quarto with a qmd source.

The "path" to the source file in the qmd is not interpreted operating system-specifically if the output file is a DOCX.

Latest quarto version.
