### ISSUE TITLE
Support for template/transclusion

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#81]
<pre>
http://plugins.jquery.com/project/markdown

## Transclusion

Transclusion is presenting the contents of one document (the referenced  
document) in another document (the referring document). You indicate a  
transclusion using a transclusion tag. The syntax for a transclusion tag  
is a path written between two curly braces as follows:

`{{mydocument.md}} -- convert and put mydocument.md in this document`
There are actually three different types of transclusions: standard  
transclusions, raw transclusions, and example transclusions.

A standard transclusion is specified as {{reference}}. The referenced  
document is processed as a normal Markdown document with all links and  
image references correctly resolved within the context (base and path)  
of the referenced document. Transitive transclusions are also resolved  
within the context of the referenced document. Recursive transclusions  
are checked and caught.

A raw transclusion is specified as {{!reference}}. The text from the  
referenced document replaces the transclusion tag but no further  
processing is performed. Raw transclusions are useful for simple text  
inclusion or for presenting source code between `&lt;pre&gt;...&lt;/pre&gt;` tags.  
Since transitive transclusions are not resolved, recursive transclusions  
are not checked. You can include a document within itself as raw text.

An example transclusion is specified as {{%reference}}. The initial %  
character is removed and the transclusion tag is left in place. This is  
useful when writing about transclusions as we are doing in this guide.

Google Code Info:
Issue #: 290
Author: rea...@gmail.com
Created On: 2011-03-15T13:46:00.000Z
Closed On: 
</pre>

**Comment by mb21** [comment]
Closing in favour of https://github.com/jgm/pandoc/issues/553
