### ISSUE TITLE
Mangled utf-8 chars (ΓÇÖ) on Windows with Asciidoctor output, but not markdown output.

### ISSUE THREAD

**Issue by dflock** [jgm/pandoc#8100]
**Explain the problem.**

When running pandoc 2.18 on Windows 10, it seems to mangle utf-8 characters when converting to asciidoctor. This does not happen on Linux.

For example:

Given this input file, `charenc.tex`:

```
Let’s try – it and you'll see.
```

so, for clarity that's these unicode chars:

```
Let(U+2019)s try (U+2013) it and you(U+0027)ll see.
```

You get mangled output if you ask to convert this to asciidcotor, but not if you convert to markdown:

```console
❯ pandoc --from=latex --to=asciidoctor .\charenc.tex
LetΓÇÖs try ΓÇô it and youΓÇÖll see.

❯ pandoc --from=latex --to=markdown .\charenc.tex
Let's try -- it and you'll see.
```

If found this issue converting latex files, but it doesn't seem to matter what the input file is. If you just copy that input file and process it as markdown, you get the same results:

```console
❯ copy .\charenc.tex charenc.md

❯ pandoc --from=markdown --to=asciidoctor .\charenc.md
LetΓÇÖs try ΓÇô it and youΓÇÖll see.

❯ pandoc --from=markdown--to=markdown .\charenc.tex
Let's try -- it and you'll see.
```

Here's a list I've coma across so far:

* ' (U+0027) -> ΓÇÖ
* ’ (U+2019) -> ΓÇÖ
* – (U+2013) -> ΓÇô

I think this _might_ be somehow console related? I get the same result in Powershell using Windows Terminal Preview, or even just plain old cmd.exe. I also get the same result if I pipe the output to a file.

However, if I save to a file directly, using `--output=`, then this doesn't happen - I get the original utf-8 chars in the output file. no mangling.

So maybe something to do with the console on Windows - but it's stange that this doesn't happen with `--to=markdown`, only `--to=asciidoctor`?

Actually, it looks like the markdown output is "ascii-fying" the – EN DASH (0x2013) into `--` - which the asciidoc output could/should also be doing, because asciidoc will transform `--` into an EN DASH on output. Same with the curly quotes. So maybe that's the bug here - that the asciidoctor output should do the same as the markdown output when it see's these unicode chars?

It's stange that this also happens with U+0027 - which is just an ASCII 27 apostrophe?

**Pandoc version?**
```console
❯ pandoc --version
pandoc.exe 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4

❯ Get-Winver

Name                           Value
----                           -----
DisplayVersion                 21H2
ProductName                    Windows 10 Enterprise
CurrentBuildNumber             19044
KeyName                        HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion
Version                        10.0.19044.0
VersionString                  Microsoft Windows NT 10.0.19044.0
OsVersion                      Microsoft Windows NT 10.0.19044.0
```

**Comment by jgm** [comment]
That's right:  since `smart` is enabled by default for markdown, pandoc will represent quotes and dashes with their ASCII equivalents.  So that explains why you get a different result with markdown.  As for the rest, you need to set up your console to handle UTF-8 encoding.  I'm not sure how to do that, but google "windows console UTF-8 encoding" and I'm sure you'll find help.

**Comment by tarleb** [comment]
It seems that the problem has been solved. Please reopen if this is not the case.
