### ISSUE TITLE
Lua: traverse = 'topdown' giving incorrect order

### ISSUE THREAD

**Issue by gpoore** [jgm/pandoc#8101]
I'm trying to create a filter using the great new `traverse` option (#7751, @tarleb), and have encountered a bug (or I'm misunderstanding the documentation). This is for `pandoc 2.18`.

Document `topdown.md`:
``````
```
block
```

`inline`

```
block
```

`inline`
``````

Filter `topdown.lua`:
```
counter = 0
traverse = 'topdown'

Code = function (elem)
    counter = counter + 1
    return pandoc.Code(tostring(counter))
end

CodeBlock = function (elem)
    counter = counter + 1
    elem.text = tostring(counter)
    return pandoc.CodeBlock(tostring(counter))
end
```

Output of `pandoc -f commonmark_x -t commonmark_x -L ./topdown.lua ./topdown.md`:
```
    3

`1`

    4

`2`
```
It looks like the nodes are being traversed by type (inline, then block) instead of by order in the document.

**Comment by tarleb** [comment]
Thanks for the report, that's a bug. I'm not sure yet why it happens, but you can work around it by using the filter to walk the Pandoc document.

``` lua
function Pandoc (doc)
  return doc:walk {
    traverse = 'topdown',
    CodeBlock = function (elem)
      print(elem.text)
    end,
    Code = function (elem)
      print(elem.text)
    end,
  }
end
```

I'm not sure yet why your version doesn't work the same way, but I believe it should.
