### ISSUE TITLE
Distinguish dash and star for bulletlist items in markdown

### ISSUE THREAD

**Issue by fxpar** [jgm/pandoc#8103]
A quiz in markdown can be created using - for wrong answers and * for correct answers.
Could AST include a way to tell if the bullet was with a dash or a star?

**Comment by jgm** [comment]
This is just one example of a whole host of similar things one might ask for (is emphasis made with `_` or `*`? how far is a list item indented?  how many backicks in the code block?)  Specifying all of these gives you a concrete syntax tree, not an abstract one.  So, it's out of scope for now.
