### ISSUE TITLE
Support for Markdown formatter: Prettier

### ISSUE THREAD

**Issue by lamyergeier** [jgm/pandoc#8105]
**Describe your proposed improvement and the problem it solves.**

I use [Prettier Code Formatter](https://prettier.io/) to format markdown. Everything is fine except: [[Ignoring Code · Prettier](https://prettier.io/docs/en/ignore.html)](https://prettier.io/docs/en/ignore.html), where `<!-- prettier-ignore-start -->` is messed up by pandoc. See the example

```bash
$ \cat Hello.md 
# Zero-knowledge proof[^1]

<!-- prettier-ignore-start -->

[^1]: [Zero-knowledge proof - Wikipedia][]

  [Zero-knowledge proof - Wikipedia]: https://en.wikipedia.org/wiki/Zero-knowledge_proof

<!-- prettier-ignore-end -->
```

```bash
$ cat Hello.md | pandoc --from=commonmark_x+raw_html --to=commonmark_x
      # Zero-knowledge proof[^1]

      ```{=html}
      <!-- prettier-ignore-start -->
      ```
      ```{=html}
      <!-- prettier-ignore-end -->
      ```
      
      [^1]: [Zero-knowledge proof -
          Wikipedia](https://en.wikipedia.org/wiki/Zero-knowledge_proof)
```

# Suggestions

What can I do to avoid auto block code addition`{=html}` around prettier comment lines?

**Comment by jgm** [comment]
You can disable the `raw_attribute` extension:
`pandoc -f markdown-raw_attribute`.

**Comment by lamyergeier** [comment]
@jgm On [[Roadmap · jgm/pandoc Wiki](https://github.com/jgm/pandoc/wiki/Roadmap)](https://github.com/jgm/pandoc/wiki/Roadmap), it is mentioned that `raw_attribute` is available with commonmark_x. So I used that:

```bash
$ cat 1.md
# Zero-knowledge proof

-   [Zero-knowledge proof - Wikipedia][]

------------------------------------------------------------------------


<!-- prettier-ignore-start -->

  [Zero-knowledge proof - Wikipedia]: https://en.wikipedia.org/wiki/Zero-knowledge_proof

<!-- prettier-ignore-end -->
```

```bash
$ pandoc -f commonmark_x-raw_attribute 1.md  -t commonmark_x-raw_attribute --reference-link
# Zero-knowledge proof

-   [Zero-knowledge proof - Wikipedia][]

------------------------------------------------------------------------

<!-- prettier-ignore-start -->

<!-- prettier-ignore-end -->

  [Zero-knowledge proof - Wikipedia]: https://en.wikipedia.org/wiki/Zero-knowledge_proof
```

The content of reference link was expected to be inside the prettier comment block! But we can see that it is not anymore!

Moreover why is there 2 blank space before the reference link. As per the commonmark spec the bottom link has no preceeding spaces!

**Comment by jgm** [comment]
When pandoc parses the document, it uses the reference link definition to determine the URL, but the location of the definition is not stored -- it is not part of the abstract syntax tree.  When you then write the document out as commonmark, using `--reference-links`, a new reference link is generated (by default, at the end of the document, but you can make it appear after a section or a block by using the `--reference-location` option).

Semantically, the two documents above are equivalent in markdown and commonmark.  Of course, they aren't equivalent in `prettier`, which introduces its own syntactic conventions not know to pandoc. But this is not a bug in pandoc.

**Comment by jgm** [comment]
You could write a script that does this.  It's not the kind of thing I'd want to build into pandoc.
