### ISSUE TITLE
pandoc fails to compile/install

### ISSUE THREAD

**Issue by mouse07410** [jgm/pandoc#8109]
**Explain the problem.**
Compilation of pandoc fails:
```
$ cabal install pandoc -w ghc-9.0.2 --overwrite-policy=always
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - Glob-0.10.2 (lib) (requires build)
 - HsYAML-0.2.1.1 (lib) (requires download & build)
 - SHA-1.6.4.4 (lib) (requires build)
 - bifunctors-5.5.12 (lib) (requires build)
 - base16-bytestring-1.0.2.0 (lib) (requires build)
 - base64-bytestring-1.2.1.0 (lib) (requires build)
 - basement-0.0.14 (lib) (requires build)
 - byteorder-1.0.4 (lib:byteorder) (requires build)
 - cabal-doctest-1.0.9 (lib) (requires build)
 .  .  .  .  .
Installing   http-client-tls-0.3.6.1 (lib)
Completed    http-client-tls-0.3.6.1 (lib)
Starting     pandoc-2.18 (lib)
Building     pandoc-2.18 (lib)

Failed to build pandoc-2.18.
Build log ( /Users/ur20980/.cabal/logs/ghc-9.0.2/pndc-2.18-4e5c5a6b.log ):
Configuring library for pandoc-2.18..
Preprocessing library for pandoc-2.18..
Building library for pandoc-2.18..
[  1 of 227] Compiling Paths_pandoc
[  2 of 227] Compiling Text.Pandoc.App.FormatHeuristics
[  3 of 227] Compiling Text.Pandoc.Asciify
[  4 of 227] Compiling Text.Pandoc.CSV
[  5 of 227] Compiling Text.Pandoc.Citeproc.CslJson
[  6 of 227] Compiling Text.Pandoc.Citeproc.Util
[  7 of 227] Compiling Text.Pandoc.Citeproc.Data
<command line>: dlopen(/Users/ur20980/.cabal/store/ghc-9.0.2/lib/libHShsl-bjctrnttn-2.2.0.1-3bae267a-ghc9.0.2.dylib, 0x0005): symbol not found in flat namespace '_lua_getuservalue'
cabal: Failed to build pandoc-2.18 (which is required by exe:pandoc from
pandoc-2.18). See the build log above for details.
```
And the content of the Build log ( /Users/ur20980/.cabal/logs/ghc-9.0.2/pndc-2.18-4e5c5a6b.log ):
```
Configuring library for pandoc-2.18..
Preprocessing library for pandoc-2.18..
Building library for pandoc-2.18..
[  1 of 227] Compiling Paths_pandoc
[  2 of 227] Compiling Text.Pandoc.App.FormatHeuristics
[  3 of 227] Compiling Text.Pandoc.Asciify
[  4 of 227] Compiling Text.Pandoc.CSV
[  5 of 227] Compiling Text.Pandoc.Citeproc.CslJson
[  6 of 227] Compiling Text.Pandoc.Citeproc.Util
[  7 of 227] Compiling Text.Pandoc.Citeproc.Data
<command line>: dlopen(/Users/ur20980/.cabal/store/ghc-9.0.2/lib/libHShsl-bjctrnttn-2.2.0.1-3bae267a-ghc9.0.2.dylib, 0x0005): symbol not found in flat namespace '_lua_getuservalue'
```

**Pandoc version?**
Attempting to install Pandoc-2.18 from Hackage on MacOS Monterey 12.4. Attempts fail exactly the same way with GHC-9.0.2 and GHC-8.10.7.

Currently installed and working pandoc:
```
$ pandoc -v
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /Users/ur20980/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
Not sure what is going on here.  I build regularly with cabal on Monterey.

I'd try the following: first, make sure you have up-to-date cabal.  (What cabal version are you using?)

Also, try with `-fembed_data_files`.

**Comment by mouse07410** [comment]
> What cabal version are you using?

```
$ ghcup list
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml as file /Users/ur20980/.ghcup/cache/ghcup-0.0.7.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   Tool  Version  Tags                      Notes      
✗  ghc   7.10.3   base-4.8.2.0                                                
.  .  .  .  .
✓  ghc   8.10.7   recommended,base-4.14.3.0 hls-powered
✗  ghc   9.0.1    base-4.15.0.0                        
✓  ghc   9.0.2    base-4.15.1.0             hls-powered
✗  ghc   9.2.1    base-4.16.0.0             hls-powered
✗  ghc   9.2.2    base-4.16.1.0             hls-powered
✔✔ ghc   9.2.3    latest,base-4.16.2.0                 
✗  cabal 2.4.1.0                                       
.  .  .  .  .
✗  cabal 3.6.0.0                                       
✔✔ cabal 3.6.2.0  latest,recommended                   
✗  hls   1.1.0                                         
.  .  .  .  .
✗  hls   1.6.1.0                                       
✔✔ hls   1.7.0.0  latest,recommended                   
✗  stack 2.5.1                                         
✗  stack 2.7.1                                         
✗  stack 2.7.3                                         
✔✔ stack 2.7.5    latest,recommended                   
✔✔ ghcup 0.1.17.8 latest,recommended
```

**Comment by mouse07410** [comment]
It looks like @tarleb pinpointed the problem, and adding `---flag lua53` proved a good workaround:
```
$ cabal install pandoc -w ghc-9.0.2 --overwrite-policy=always --flag lua53
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - pandoc-2.18 (lib) (requires build)
 - pandoc-2.18 (exe:pandoc) (requires build)
Starting     pandoc-2.18 (lib)
Building     pandoc-2.18 (lib)
Haddock      pandoc-2.18 (lib)
Installing   pandoc-2.18 (lib)
Completed    pandoc-2.18 (lib)
Starting     pandoc-2.18 (exe:pandoc)
Building     pandoc-2.18 (exe:pandoc)
Installing   pandoc-2.18 (exe:pandoc)
Completed    pandoc-2.18 (exe:pandoc)
Symlinking 'pandoc' to '/Users/ur20980/.cabal/bin/pandoc'
$ pandoc --version
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5.1, skylighting 0.12.3.1,
citeproc 0.7, ipynb 0.2, hslua 2.1.0
Scripting engine: Lua 5.3
User data directory: /Users/ur20980/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by mouse07410** [comment]
@jgm One thing more: could you tell me whether this workaround will be incorporated into the Pandoc code? Or would every user have to locate this issue and learn the workaround from it, in order to successfully install the current Pandoc?

**Comment by tarleb** [comment]
It would be good to understand more about the circumstances that led to this error. I'm not sure why this happened and I'm fairly surprised that it did. Was pandoc installed with the same mechanism before? Could this be a caching issue?

**Comment by tarleb** [comment]
My guess is that cabal reuses an object file that was compiled from Lua 5.3, but I'm stumped as to why it happens or how we can prevent it.

Does `cabal clean` help?

**Comment by mouse07410** [comment]
> Does `cabal clean` help?

Since I'm _not_ building from the master, but installing from Hackage - no it doesn't. There's nothing to clean, AFAIK.

**Comment by tarleb** [comment]
Ah right, you had mentioned that. You'd probably have to remove everything below `~/.cabal/store`. I'll try if I can somehow reproduce this locally.

**Comment by tarleb** [comment]
I wasn't able to reproduce the issue on Linux. I suspect that the problem is specific to Mac. Might be worth to bring it up with the cabal maintainers, but I don't think there's much we can do on our end.

**Comment by mouse07410** [comment]
I'm reasonably sure this problem has nothng to do with Cabal. Probably something with how Haskell deals with dynamic libraries.

BTW, try to replicate it on Linux with Cabal config enabling `dynamic-executable: True` and `shared: True`.

**Comment by mouse07410** [comment]
@tarleb please check above

**Comment by tarleb** [comment]
This still builds fine for me:

    cabal install pandoc --enable-shared --enable-executable-dynamic

I'll be happy to investigate this further when I can get my hands on a mac. For the time being, i.e., without any way for me to reproduce this, I stand by my assessment that this is not a problem solvable on our side.

The only remaining idea I have is to use an empty `LD_LIBRARY_PATH` and/or `DYLD_LIBRARY_PATH`, as in

    LD_LIBRARY_PATH='' cabal install pandoc

**Comment by mouse07410** [comment]
> `cabal install pandoc --enable-shared --enable-executable-dynamic`

This is **not** the same as setting the the attributes I mention in the `$HOME/.cabal/config` file. Could you please try that, on a clean setup (with no Pandoc-required packages already installed by your previous runs)?

**Comment by tarleb** [comment]
That's interesting. What's the difference?

I'd be curious to know why are seem to be so sure that this is not a cabal problem. That might make it easier for us, because then we'd know what to look for.

**Comment by mouse07410** [comment]
> That's interesting. What's the difference?

The difference is in how it handles other packages/dependencies. Discovered empirically. ;-)

Majority of Haskell installations statically compile and link libraries and executables. However, some keep it all dynamic. Usually, CI is only configured for static, so the maintainers don't even have a clue that something may be wrong. 

If I recall correctly, earlier Cabal simply ignored `--enable-executable-dynamic`, and since all the dependencies were built statically anyway, it didn't make much of a difference...

**Comment by tarleb** [comment]
> The difference is in how it handles other packages/dependencies.

Huh. If one works but the other doesn't, then that would give us a hint what to look for. Can you describe the difference so we know what to look for?

**Comment by mouse07410** [comment]
> Can you describe the difference so we know what to look for?

You're assuming more expertise in me than I think I have.

My conjecture is that the difference is - what (how many) packages are built statically, and what - dynamically.

But the best would be if you could run the test as I described on a clean Linux Haskell installation (with no pre-installed statically-built packages to muddy the water).

**Comment by mouse07410** [comment]
Ping? Were you able to run this on a clean Linux Haskell installation configured for dynamic builds?
