### ISSUE TITLE
LaTeX -> docx breaks with comment in last line of align environment

### ISSUE THREAD

**Issue by gerritzen** [jgm/pandoc#8122]
**Explain the problem.**
The environment
```
\begin{align}
  a &= b\\ % comment1
  c &= d   % comment2
\end{align}
```
compiles fine with pdflatex, but `pandoc -o foo.docx foo.tex` throws the error
```
[WARNING] Could not convert TeX math \begin{aligned}
    a &= b\\ % comment1
    c &= d   % comment2\end{aligned}, rendering as TeX:
  mment2\end{aligned}
                     ^
  unexpected eof
  expecting "&", "\\\\", white space or "\\end"
```
In markdown it becomes
```
$$\begin{aligned}
  a &= b\\ % comment1
  c &= d   % comment2\end{aligned}$$
```
so the `\end{aligned}$$` is commented out as well. In my opinion there should be a line break before `\end{aligned}`, regardless comments in the previous line.

**Pandoc version?**
What version of pandoc are you using, on what OS?
```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3.1,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
```
on Fedora 36 with TeXLive 2021 from the official repository.

**Comment by jgm** [comment]
This is really just about the LaTeX reader and doesn't have anything to do with docx specifically.
```
% pandoc -f latex -t native
\begin{align}
  a &= b\\ % comment1
  c &= d   % comment2
\end{align}
[ Para
    [ Math
        DisplayMath
        "\\begin{aligned}\n  a &= b\\\\ % comment1\n  c &= d   % comment2\\end{aligned}"
    ]
]
```
There is code in the reader to change the `align` environment to something that can go in a math context (hence `aligned`), and your case shows that it's broken.
