### ISSUE TITLE
Need a standard directory to store custom writers (both in user data and system wide)

### ISSUE THREAD

**Issue by chrisaga** [jgm/pandoc#8135]
Custom writers are powerful, especially the new style. So as we don't code a writer only for one document it would be nice to be able to store them in a directory and call them with only their filenames (equivalent to lua filters).

In addition it would allow us to take advantage of this undocumented feature : 
If the name of the custom writer starts the same as a template, the template is used and you don't need to clone it. For instance Pandoc uses default latex template when you run `pandoc -t latex-custom-writer.lua doc.md`

**Comment by tarleb** [comment]
We've added support for this just last week: https://github.com/jgm/pandoc/pull/8112
There is no official release with that code yet, but the latest [nightly build](https://github.com/jgm/pandoc/actions/runs/2523241734) should work.

I never realized that the template selector could be tricked like that. It should be considered a bug, even though I agree that it's quite convenient.

**Comment by jgm** [comment]
> For instance Pandoc uses default latex template when you run pandoc -t latex-custom-writer.lua doc.md

Oh yes, I can see why; everything after the `-` is stripped off as an extension when we determine the template name. I agree with @tarleb that this is unintended behavior and should be fixed.  #8137 tracks this.
