### ISSUE TITLE
Fix unintended behavior for template search with custom writer

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#8137]
As noted in #8135, if the writer is `latex-foo-bar.md`, the default latex template will be used (`-foo-bar.md` is stripped off as extensions when doing template search). This is unintended behavior and should be fixed.

**Comment by chrisaga** [comment]
Is there another way to use a standard template with a custom writer which looks like a legit use case ?
If not, should we consider having one before fixing this unwanted feature ?

**Comment by jgm** [comment]
You can specify the template explicitly using `--template=default.latex`, can't you?

**Comment by chrisaga** [comment]
Well ... I guess so. I must confess that after all these years, I am still confused by the way Pandoc manages its data files and configuration. Usually you have by order of priority:
1) User files and conf (`.local/share/whatever`)
2) System-wide files and conf (`/usr/share/whatever`)
3) Things which are hardcoded in the application

As far as I understand `default.latex` would be a mix of 2 and 3; i.e. hard-coded and behaving as if it was a file in some `/usr/share/pandoc` **but** not customizable system-wide.
Well this is another topic to be discussed, or not, elsewhere ...

**Comment by jgm** [comment]
It is customizable; you can add your own `default.latex` to the `templates` subdirectory of the user data directory.  And, if your version of pandoc is compiled without the `embed_data_files` flag, you can also substitute the version in `/usr/share/pandoc/templates`.

**Comment by chrisaga** [comment]
There still is an issue though !

The unintended behavior you are about to fix has a little brother: the default pdf engine.
`pandoc -t latex-foo-bar.lua -o sample.pdf sample.md` selects `pdflatex` as the pdf-engine.
with `-t mylatex-foo-bar.lua` it fails with `cannot produce pdf output from mylatex-hk-writer.lua`

Honestly it works so well that I love it. You are really sure it's unwanted ?
 :-D

**Comment by jgm** [comment]
On the pdf issue, see #7898.
All you need to do is explicitly specify `--pdf-engine=pdflatex`

**Comment by chrisaga** [comment]
Thanks @jgm all this makes me challenge pandoc's behaviors I was relying on.

My point with the pdf thing was to emphasis a probably unintended trick with the filter name similar to the template name one.
I suspected that fixing the behavior for template will fix the behavior for pdf engine too, so I didn't open a separate issue.

**Comment by jgm** [comment]
I'll have to check to see whether the two issues are interwoven in that way.  But both should be fixed, I think.
