### ISSUE TITLE
Markdown in Metadata is Dependent on Trailing Newline

### ISSUE THREAD

**Issue by Eisfunke** [jgm/pandoc#8143]
Consider this YAML metadata file:

```
test: "- foo\n- bar\n- baz"
```

It sets a metadata variable `test` to a Markdown list. Note that there is no final newline after the third element.

When I now call

```
pandoc -f markdown -t native --metadata-file test.yaml -s /dev/null
```

with `test.yaml` being the above metadata file, I receive the following result:

```
Pandoc
  Meta
    { unMeta =
        fromList
          [ ( "test"
            , MetaBlocks
                [ BulletList
                    [ [ Plain [ Str "foo" ] ]
                    , [ Plain [ Str "bar" ] ]
                    ]
                , Plain [ Str "-" , Space , Str "baz" ]
                ]
            )
          ]
    }
  []
```

The problem here is that the last bullet point wasn't parsed correctly as part of the bullet list.

However, when I instead use the following metadata file with the only difference being the added final newline in `test`:

```
test: "- foo\n- bar\n- baz\n"
```

I receive the following result:

```
Pandoc
  Meta
    { unMeta =
        fromList
          [ ( "test"
            , MetaBlocks
                [ BulletList
                    [ [ Plain [ Str "foo" ] ]
                    , [ Plain [ Str "bar" ] ]
                    , [ Plain [ Str "baz" ] ]
                    ]
                ]
            )
          ]
    }
  []
```

So with that final newline the list is parsed correctly.

This dependence on the final newline does not seem to be on purpose, as it is not happening for plain markdown conversions.

```
echo "- foo\n- bar\n- baz\n" | pandoc -f markdown -t native
echo "- foo\n- bar\n- baz" | pandoc -f markdown -t native
```

both return the same result:

```
[ BulletList
    [ [ Plain [ Str "foo" ] ]
    , [ Plain [ Str "bar" ] ]
    , [ Plain [ Str "baz" ] ]
    ]
]
```

I discovered this when working with JSON files returned by an API containing Markdown strings without trailing newlines.

**Pandoc version**

Pandoc 2.18 installed with stack on Arch Linux:

```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5.1, skylighting 0.12.3.1,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /home/nicolas/.local/share/pandoc
```

**Comment by jgm** [comment]
Indeed, there is arguably a bug, but not the one you think.
The manual stipulates that fields that are to be interpreted as block-level must end with a newline, and hence:

>  The pipe character (`|`) can be used to begin
an indented block that will be interpreted literally, without need for
escaping. This form is necessary when the field contains blank lines
or block-level formatting.

The code that enforces this wasn't as rigorous as it should be, so your "test" field got parsed as blocks rather than inlines, as intended.

The reason you see a difference in the body content is that pandoc always adds an extra newline to the body before parsing.

**Comment by Eisfunke** [comment]
I see, thanks for explaining! Makes sense.
