### ISSUE TITLE
word to md: adding numbers next to the # for section headers

### ISSUE THREAD

**Issue by Courvoisier13** [jgm/pandoc#8144]
I used Rstudio's pandoc with great success to transform a word file into md. The file had numbered section headers like this
1 Section
1.1 Sub Section
These were correctly getting translated into 
```
# Section
## Sub Section
```
Then I slightly modified the word file. Nothing in the structure of the heading of the word file changed. I also updated Rstudio (so it updated pandoc to 2.17), and now I am getting this:

```
1.  # Section
     1.  ## Sub Section
```
So I installed the standalone pandoc (2.18) and used that, but that did not help. And I can't go back to the version of the word file that was working fine to test.

Am I missing some option? I tried `--shift-heading-level-by=-1` but that didn't work.

Thank you

**Comment by tarleb** [comment]
Closing for now, but we can reopen once we have a reproducible example
