### ISSUE TITLE
Printing lua tables

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#8146]
Please refer to [this pandoc-discuss thread](https://groups.google.com/g/pandoc-discuss/c/uezr_sFkv8M/m/2H2kwJYLBwAJ) for background.

Since then I've refactored this code. For example:
* It's now all in a single `logging` module
* It includes logging functions such as `logging.info()`

I've attached the current code as [logging.lua.txt](https://github.com/jgm/pandoc/files/8967089/logging.lua.txt) but would be very happy to receive suggestions for changes (including documentation improvements!). I'd also be happy to create a PR (in which case I'd need to know where to put it).

I've recently updated all my lua scripts to work with pandoc 2.18, and I have tested this code with both pandoc 2.16.1 and 2.18.

**Comment by jgm** [comment]
@wlupton  Could you create a repository for this code, along with a README explaining what it is and how to use it?  Then we could simply link to that from the lua filters documentation. I think the script is too long to just include there verbatim, and then we'd also have to track changes.

**Comment by wlupton** [comment]
Will do. What would be the ideal license? MIT, like <https://github.com/pandoc/lua-filters/blob/master/LICENSE>?

**Comment by jgm** [comment]
I think the license is completely up to you; it doesn't affect our ability to link to it.  MIT is a good choice unless you want copyleft (in that case, GPL like pandoc?).

**Comment by wlupton** [comment]
Thanks. I've created <https://github.com/wlupton/pandoc-lua-logging> (with an MIT license). Comments and suggestions are welcome.

**Comment by jgm** [comment]
I added a paragraph to the lua-filters documentation. Let me know if you'd like it to be worded differently.

**Comment by wlupton** [comment]
That's great. Thanks!
