### ISSUE TITLE
Check/ensure correct line wrap in markdown to PDF

### ISSUE THREAD

**Issue by abdulbadii** [jgm/pandoc#8147]
**Describe your proposed improvement and the problem it solves.**
The line wrap in markdown to PDF feature is not entirely correct,
it won't do at least, but not limited to, any line within:

\```lua
\```

How to have that also automatically wrapped just like other lines get wrapped correctly?

https://github.com/bkaradzic/GENie/blob/master/docs/scripting-reference.md

**Comment by jgm** [comment]
See #4302, which explains why we don't break source code lines in latex/pdf output, and also offers several different workarounds.
