### ISSUE TITLE
html reader: does not support common usage of nested lists

### ISSUE THREAD

**Issue by hstock** [jgm/pandoc#8150]
I don't know, if both these styles of using nested lists in HTML are conforming to spec, however both styles are common.

This style is used for example in mails generated by Thunderbird and does not render correctly in pandoc:

```html 
<!-- file: nested-list1.html -->
<ul>
	<li>L1</li>
	<li>L2</li>
	<ul>
		<li>L3.1</li>
		<li>L3.2</li>
	</ul>
</ul>
```

```
~$ cat nested-list1.html | pandoc -f html -t markdown
L1

L2

-   L3.1
-   L3.2
```

This style works well with pandoc:

```html
<!-- file: nested-list2.html -->
<ul>
	<li>L1</li>
	<li>L2
	<ul>
		<li>L3.1</li>
		<li>L3.2</li>
	</ul></li>
</ul>
```

```
$ cat nested-list2.html | pandoc -f html -t markdown
-   L1
-   L2
    -   L3.1
    -   L3.2
```

It would be nice, if pandoc could render both styles as intended. (The expectation would be, to have both styles render the same in markdown output and other writers.)

**Comment by mb21** [comment]
Pretty sure, the first is invalid HTML... but yeah, could always try to make the pandoc HTML reader more forgiving...

**Comment by jgm** [comment]
So you should report this to Thunderbird as a bug!

**Comment by tarleb** [comment]
The HTML reader has this comment in its sources:

```
 -- note: if they have an <ol> or <ul> not in scope of a <li>,
 -- treat it as a list item, though it's not valid xhtml...
```

So I think the intention to allow it was there. It's a small change, so I'm going ahead and will add (restore?) support for this.

**Comment by hstock** [comment]
Thank you 💟
