### ISSUE TITLE
Revealjs format creates empty slide for null

### ISSUE THREAD

**Issue by PaulTheNeko** [jgm/pandoc#8155]
I would like to help fix this, though I don't have much experience with Haskell or Pandoc (and I'm not a good programmer yet). This is one of my first bug reports, which is why it's too verbose (if it is too verbose).

**Context (feel free to skip)**
I am trying to use [panda.lua] conditionals inside of a pandoc/revealjs presentation I'm making for fun.
```md
## Czym jest efekt uboczny?{.if lang="pl"}
## What is a side effect{.if lang="en"}
```

**Explain the problem.**
The revealjs writer creates an empty slide when encountering Null before a Header. This is a problem for me, because [panda.lua] replaces failing conditionals with Null. As I understand it, the writer should just ignore those nulls. Note this is only a problem for the very first Header, since each subsequent one actually should produce a new slide.

**To reproduce**
Using the following file (called e.g. null.native) as input
```haskell
[ Null
, Header
    2
    ( "header-after-null" , [] , [] )
    [ Str "Header"
    , Space
    , Str "after"
    , Space
    , Str "null"
    ]
]

```
run
```
pandoc -t revealjs --from native null.native -o test.html
```

**Actual result**
```html
<section class="slide level6">


</section>
<section id="header-after-null" class="title-slide slide level2">
<h2>Header after null</h2>

</section>

```

**Expected result**
Only one slide
```html
<section id="header-after-null" class="title-slide slide level2">
<h2>Header after null</h2>

</section>
```

**Pandoc version?**
```
$ pandoc --version
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.3,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/neko/.local/share/pandoc
```
On Void Linux (rolling release).
Also reproduced with https://pandoc.org/try/ and the latest [nightly].

[panda.lua]: https://github.com/CDSoft/panda
[nightly]: https://github.com/jgm/pandoc/actions/runs/2563447946

**Comment by jgm** [comment]
Thanks for the report. Better too verbose than not verbose enough. More information is always good!
