### ISSUE TITLE
To have no empty line between a list and the text above it

### ISSUE THREAD

**Issue by john-cj** [jgm/pandoc#8156]
Currently, there required to be an empty line between a list and the text above it.

```
// this will be converted into HTML as a list:

this is a list:

- list item 1
- list item 2

// sadly, this will be converted into HTML as a paragraph:

this is a list:
- list item 1
- list item 2
```

Because Markdown files are often read in raw form, having an option to get rid of that empty line would be great. It will be much easier to distinguish the text that is used as a title/label/introduction of a list from the "normal" text.

Here is a shopping list that is in turn consists of three unordred "labeled" lists:

```
Food
- Bananas
- Apples
- Bread

Drinks
- Orange juice
- Wine
- Whiskey
- Bloody Mary

Johnnie Walker or Jim Beam? And what about Bloody Mary? Maybe Mojito instead?

Johnnie and Jane's marriage
- Codex Seraphinianus
- That amazing flying and talking hadgehog
- Pistachio
```

"Johnnie Walker" and "Jim Beam" are whiskeys. "Bloody Mary" is a cocktail.

To make the shopping list above "converting-to-HTML-friendly", I will need to add an empty line above each list, and so this will take more vertical space and the shopping list itslef will be somewhat ambiguous:

```
Drinks

- Orange juice
- Wine
- Whiskey
- Bloody Mary

Johnnie Walker or Jim Beam? And what about Bloody Mary? Maybe Mojito instead?

Johnnie and Jane's marriage

- Codex Seraphinianus
- That amazing flying and talking hedgehog
- Pistachio
```

Of course, I don't really talk about a shopping list. I use Pandoc's Markdown for technical writing.

The same goes for other block elements, e.g. fenced code blocks.

**Comment by tarleb** [comment]
[CommonMark](https://commonmark.org) already uses that logic. These days, pandoc's CommonMark implementation offers almost all the features of pandoc's Markdown. Please try if `--from=commonmark_x` is sufficient for your needs.

**Comment by john-cj** [comment]
Thanks, tarleb. Unfortunately, I cannot test right now because my computer is quite old and there is 32-bit Windows 7 installed on it. So the last Pandoc version available for me is 2.9.2.1, and it seems it cannot convert from `commonmark_x`.

Using

```
pandoc test1.md -f commonmark_x -t html -s --toc -o test1.html
or
pandoc test1.md --from=commonmark_x -t html -s --toc -o test1.html
```

gives me an error `Unknown input format commonmark_x`. (Sure, I need to buy a newer computer.)

**Comment by john-cj** [comment]
@jgm Is it on the roadmap to make those empty lines optinal for Pandoc's Markdown as well, so that it will work with `--from markdown` and not only with `--from commonmark_x`?

**Comment by jgm** [comment]
No, I don't anticipate any changes to pandoc `markdown`.
Allowing no empty line actually causes a host of problems.
See #5 at https://johnmacfarlane.net/beyond-markdown.html

**Comment by john-cj** [comment]
Please, don't get me wrong, but what I see in \#5 is just a one singe problem. And although it is said in the article that

> [...] we faced a choice: either require a blank line between paragraph text and a following list, or allow lists to interrupt paragraphs, and risk accidental interpretation of paragraph text as a list. We took the first option to be off the table, since it is very common in Markdown to have tight sublists without a preceding blank line.

...CommonMark eventually switched to the second option.
