### ISSUE TITLE
search on pandoc.org with JavaScript is broken on Firefox

### ISSUE THREAD

**Issue by nbehrnd** [jgm/pandoc#8157]
**Explain the problem.**
This refers to accessing the project's [top level site](https://pandoc.org/).  If JavaScript is not enabled, the query next to the box «search» is redirected to duckduckgo; I'm fine with this.

However, with JavaScript permitted, the results of the search possibly are displayed in a transparent frame _on top_ of the page.  As documented by the screen photo below, it is not possible to read the suggested links, let alone to access them.

![2022-06-27_pandoc_search_frame](https://user-images.githubusercontent.com/19709084/175919286-1d32289d-d0c2-495f-bbd4-012275cdf926.png)

This observation is met both on Linux Debian 12/bookwork, branch testing with Firefox 91.10.0esr (64-bit); and ii) a live-USB session  of Linux Xubuntu 20.04.2 LTS focal fossa with an updated Firefox 101.0.1 (without any additional plug-ins, or extensions).

**Comment by jgm** [comment]
Odd, that's not what happens when I try disabling JavaScript in Safari and then using the search box. I get redirected to duck duck go, but not in a frame.

**Comment by jgm** [comment]
Sorry, I didn't read carefully enough.
Yes, the search results with JS (which are not generated by Duck Duck Go, but internally) appear in a frame on top of the content.
The frame should not be transparent (and it isn't when I test it with Safari).
But I can see the problem now, testing with Firefox.

**Comment by nbehrnd** [comment]
As an additional element of observation, a screen cast with Linux Xubuntu 20.04.2 LTS/focal fossa.  This runs the live .iso from the USB thumb drive.  After successful booting into the RAM of the computer, the only changes to the os wwew 1) an update of the version of Firefox to version 101.0.1 (64-bit) without addition of plug-ins/extensions, and 2) the installation of a [screen recorder](https://www.maartenbaert.be/simplescreenrecorder/) (version 0.3.11).  The conversion of .mp4 to .gif eventually uploaded here was relayed to [ezgif](https://ezgif.com/).

![pandoc_JS_Xubuntu_focal](https://user-images.githubusercontent.com/19709084/176876405-cac52172-18ca-490c-9990-ba51da6fe707.gif)

**Comment by jgm** [comment]
Btw, I just tried with Google Chrome, and like safari it does not make the frame transparent. So this seems specific to Firefox.

**Comment by jgm** [comment]
In CSS we have
```css
.modal.show {
  display: block;
  position: absolute;
  tabindex: 1;
  width: 90%;
  margin: auto;
  background: white;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}
```
The `background: white` ought to prevent it from having a transparent background.  I'm not sure why this isn't working on ff.

**Comment by jgm** [comment]
OK, I fixed the tabindex issue, but that wasn't it.  We still get a transparent box rather than one with an opaque white bacground, and the box doesn't scroll. These look like CSS implementation bugs in Firefox, but I'm not an expert.  Maybe someone with good CSS knowledge can help here.

**Comment by jgm** [comment]
Adding `z-index: 1` to the modal's CSS allows scrolling to work.
Background is still transparent, though.

**Comment by jgm** [comment]
Sorry, no, z-index fixes it completely.

**Comment by jgm** [comment]
The site seems to work properly now both in Safari and in Firefox.
Thanks for letting me know about the problem.

**Comment by nbehrnd** [comment]
Affirmative, the interaction with the web page in either way, _including_ JavaScript enabled works well, and the items on the new frame on top are accessible.  The issue is resolved successfully.

Misunderstandings between web pages including JavaScript and web browsers seem to be a recurrent problem.  The submission of addresses like `www.amazon.com`, or `https://www.bbc.com/` to a validator like the one by [w3c](https://validator.w3.org/) conveys «working often is considered as _good enough_».  This contrasts to the green light of «no errors, nor warnings» when submitting `https://pandoc.org/`.

Thank you.
