### ISSUE TITLE
Pandoc doesn't parse TeX figures unless they contain an image

### ISSUE THREAD

**Issue by jech** [jgm/pandoc#8165]
Consider the following TeX document:
```TeX
\documentclass{article}
\begin{document}
\begin{figure}[htb]
\begin{center}
Figure body
\end{center}
\caption{Figure caption}\label{fig1}
\end{figure}
See Figure~\ref{fig1} for details.
\end{document}
```
When converted to HTML, this gives:
```HTML
<div class="center">
<p>Figure body</p>
</div>
<p>See Figure <a href="#fig1" data-reference-type="ref"
data-reference="fig1">[fig1]</a> for details.</p>
```
Two issues:
  * the caption has disappeared;
  * the link points at a label that no longer exists.

**Comment by tarleb** [comment]
Thanks for the report. This is related to, and a direct consequence of, #3177; closing in favor of that issue. See the end of that thread for current progress.
