### ISSUE TITLE
Year wrongly appearing in subsequent citations 

### ISSUE THREAD

**Issue by mk-uc** [jgm/pandoc#8167]
I'm using the CSL chicago-fullnote-bibliography-short-title-subsequent with pandoc to render my citations. However, in subsequent citations of a text, it is adding the year to the citation where it shouldn't be. For example,

Smith, A Title, 2022, pg 10

It should just be:

Smith, A Title, pg 10

I tried using the regular chicago-fullnote-bibliography and that also added the year in strange places. Is there something wrong with the CSL file? my bibtex file? pandoc?

For reference, the bibtex looks simply like this:

[@Book{Smith2022,
author = {Smith, John}, 
title = {A Title}, 
publisher = {Northwestern University Press}, 
address = {Evanston}, 
year = {2022}, }

**Comment by jgm** [comment]
What does `pandoc --version` say?

**Comment by jgm** [comment]
You don't have another bibliography entry by Smith, so that the date would be needed for disambiguation?

**Comment by jgm** [comment]
Is it possible that Shortcuts uses a different environment, with a different PATH, so that you're running a different version of pandoc somewhere else on your file system?

**Comment by tarleb** [comment]
I'm closing this, as this appears to be fixed in recent versions, and the remaining issues are not specific to pandoc.

I don't know how to debug this further, but you might be able to get advise from forums such as apple.stackexchange.com or superuser.com.
