### ISSUE TITLE
backslash escapes are lost when converting markdown to markdown

### ISSUE THREAD

**Issue by milahu** [jgm/pandoc#8171]
**Explain the problem.**

similar to https://github.com/jgm/pandoc/issues/5695#issuecomment-523471811

> `\.` is an escape used to escape specific Markdown syntax and place a literal period

this is broken:

```
s=$(printf '1\. one\n2\. two\n3\. three\n'); echo in; echo "$s"; echo out; echo "$s" | pandoc -f gfm+hard_line_breaks -t markdown_strict 
in
1\. one
2\. two
3\. three
out
1\. one  
2. two  
3. three
```

expected: same output as input

could be related to the markdown flavors (github markdown vs strict markdown)
and/or could be related to the linebreak style (hard linebreaks vs soft linebreaks)

**Pandoc version?**

```
uname -sr
Linux 5.15.36

pandoc --version 
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.2, texmath 0.12.4, skylighting 0.12.3.1,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/user/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
This isn't a bug, really. Pandoc doesn't keep track of what characters are escaped in the input; that's not represented in the abstract syntax tree.  In this case pandoc adds an escape which suffices to prevent the content from being interpreted as a list.  The output is *semantically* equivalent to your desired output.

**Comment by milahu** [comment]
sorry for the noise

the problem was pandoc 2.5 (debian ...)

i said i have pandoc 2.17.1.1, but that was wrong
