### ISSUE TITLE
Help solve a rst to PDF conversion

### ISSUE THREAD

**Issue by abdulbadii** [jgm/pandoc#8172]
So sorry but can't help ask here as on 'Ask question' this's not given just attention

As I'm so noob in rst file how to solve a rst to PDF conversion in below failure that seems invoking many external references (if that say is true)

https://drive.google.com/file/d/1dWVKcAMpJoZNmCKsAnZMJ2sFeCurMwas/view?usp=sharing

```
[WARNING] Reference not found for 'Key "nimversion"' at manual.rst_chunk line 1 column 13
[WARNING] Reference not found for 'system' at manual.rst line 3929 column 12
[WARNING] Reference not found for 'Key "speed"' at manual.rst_chunk line 1 column 12
[WARNING] Reference not found for 'system' at manual.rst line 8050 column 21
Error producing PDF.
! Text line contains an invalid character.
l.1146 \NormalTok{manual\_of\_Nim/manual/^^@

```
Help contribute a nice idea leads to solution. Thanks before.

**Comment by jgm** [comment]
Just eyeballing this, I think the missing references may be due to something similar to #4160.
It looks like your document is organized into separate files using `include`.  Currently pandoc won't pick up on references defined in included files.  This is a known limitation of the RST reader.

**Comment by jgm** [comment]
Just pasting the included files in where the include directive is may do the trick.

The PDF generation issue may be something else.

**Comment by abdulbadii** [comment]
Problem now I'm nothing nil on .rst file.
What application can view it best?
This rst file in archive in link has grammar.txt what is it, it has include:: that refer to nonexistent `../rstcommont.rst` relative to the github tree directories in main coderepo
while the same file has a correct one `rstcommont.rst` relative to same
How to solve it ?

**Comment by abdulbadii** [comment]
Just have them being pasted, now result error/imperfection on some lines overrun the right alignment margin

How actually is the rst's width and margin alignment setting command to correctly have the max column number laid out, or that is determined implicitly by pandoc on the run when trying accomplishing  above by:
`pandoc -f rst -t pdf -o manual.pdf manual.rst`
?

improper line e.g:
`These keywords are also operators:
and or not xor shl shr div mod in notin is isnot of as from`.

... notin   <= longer than it
 
real doc being viewed:

`These keywords are also operators: and or not xor shl shr div mod in notin is isnot of as from.`

should be splitted/broken to:
```

These keywords are also operators: and or not xor shl shr div mod in notin   
is isnot of as from.
```

please show the logical way to solve correctly
