### ISSUE TITLE
Bad groff ms code generated by pandoc highlight styles

### ISSUE THREAD

**Issue by RobertGoulding** [jgm/pandoc#8175]
I am using Pandoc 2.18, on crostini on ChromeOS (i.e., Debian bullseye).

I was trying to pretty-print the groff standard macro code for my study, using pandoc. So, I prepared the -ms macros by creating a file ms.md, which contains the whole of groff's s.tmac file, in code delimiters (attached).

Then I created an -ms file by issuing the command:

`pandoc --highlight-style=monochrome -s -o ms-monochrome.ms ms.md`

I then processed this to pdf:

pdfroff -ms ms-monochrome.ms > ms-monochrome.pdf

This came up with the very weird error message:

"groff ms macros require groff extensions; aborting" -- weird because I was of course using groff with groff extensions!

A partial pdf was produced (attached along with the source). Trying this with another highlight style, kate, led to no errors, and a good pdf. (Also attached). One other highlight style, haddock, also failed, but this time sending groff into an infinite loop. By the way, I get not errors creating pdfs from ms.md via LaTeX, with any highlight style.

Here are the files:

[ms.md](https://github.com/jgm/pandoc/files/9087144/ms.md)
[ms-kate.pdf](https://github.com/jgm/pandoc/files/9087145/ms-kate.pdf)
[ms-monochrome.pdf](https://github.com/jgm/pandoc/files/9087146/ms-monochrome.pdf)
[ms-monochrome.ms.txt](https://github.com/jgm/pandoc/files/9087153/ms-monochrome.ms.txt)
[ms-kate.ms.txt](https://github.com/jgm/pandoc/files/9087154/ms-kate.ms.txt)

(I had to add .txt extension to the -ms files for github to accept them)

I brought this up on the groff bug list, as I thought it might be a problem with the groff -ms macros. The groff maintainer, Branden Robinson, tracked down the bug to faulty troff syntax that pandoc is generating. I attach his reply in full here:

I was able to reproduce your problem with the following command.

$ groff -ms -Tpdf ms-monochrome.ms >| m.pdf
groff ms macros require groff extensions; aborting

The first thing I did was to enable warnings.  I encourage everyone to
do this.  :)

$ groff -ww -ms -Tpdf ms-monochrome.ms -z
troff: ms-monochrome.ms:126: warning: macro '.' not defined
troff: ms-monochrome.ms:127: warning: missing closing delimiter
groff ms macros require groff extensions; aborting

This alone is enough to make me suspect a usage problem.

Here's what these lines look like.

$ sed -n '126,127p' ms-monochrome.ms
\*[FunctionTok ".."]
\*[FunctionTok ".if"]\*[StringTok " !"]\*[OtherTok "\[rs]n(.g"]\*[StringTok " "]\*[CharTok "\[rs]"]

Okay, that looks moderately hairy.  Whatever generated this is using
groff parameterized strings whose arguments are themselves exhibits of
groff syntax.  This strikes me as a good way to get into trouble; some
care will be required.

Evidently the "kate" and "monochrome" files define the `FunctionTok`
string differently.  How?

$ grep 'ds FunctionTok' *.ms
ms-kate.ms:.ds FunctionTok \\m[644a9b]\\$1\\m[]
ms-monochrome.ms:.ds FunctionTok \\$1

So "monochrone", which fails, simply returns the argument unprocessed,
whereas "kate" brackets it with color escapes.

Suddenly this looks like a familiar problem.  I play a hunch.

$ groff -ww -ms -Tpdf ms-monochrome-gbr.ms -z
troff: ms-monochrome-gbr.ms:142: warning: macro 'CH' not defined
troff: ms-monochrome-gbr.ms:2252: warning: macro 'pdfsync' not defined

We got further.  What did I do?

$ diff -u ms-monochrome.ms ms-monochrome-gbr.ms
--- ms-monochrome.ms    2022-07-08 19:58:25.396932753 -0500
+++ ms-monochrome-gbr.ms        2022-07-08 20:13:07.088864226 -0500
@@ -18,9 +18,9 @@
 .ds BaseNTok \\$1
 .ds FloatTok \\$1
 .ds ConstantTok \\$1
-.ds CharTok \\$1
+.ds CharTok \&\\$1
 .ds SpecialCharTok \\$1
-.ds StringTok \\$1
+.ds StringTok \&\\$1
 .ds VerbatimStringTok \\$1
 .ds SpecialStringTok \\$1
 .ds ImportTok \\$1
@@ -28,8 +28,8 @@
 .ds DocumentationTok \\f[CI]\\$1\\f[C]
 .ds AnnotationTok \\f[CI]\\$1\\f[C]
 .ds CommentVarTok \\f[CI]\\$1\\f[C]
-.ds OtherTok \\$1
-.ds FunctionTok \\$1
+.ds OtherTok \&\\$1
+.ds FunctionTok \&\\$1
 .ds VariableTok \\$1
 .ds ControlFlowTok \\f[CB]\\$1\\f[C]
 .ds OperatorTok \\$1

I prefixed each of these string definition with the non-printing input
break escape sequence[1] so that when these strings are interpolated at
the beginning of an input line (or as the consequent of a conditional
request like `if`, `el`, `while`, or `nop`), they won't be
misinterpreted if they start with a control character.

The remaining problems revealed by -ww to me appear to be unrelated.
Some stuff like ".rm CH" seems dubious.  It is better to give that
string an empty definition than to remove it.  I see use of non-groff
macros like `pdfsync`.  I assume they supply a definition of the last
somewhere.

Is pandoc is responsible for generating this output?  If so it sounds
like a bug report is in order.  They _really_ need to fix those string
definitions to start with `\&` unconditionally.  Those that already
start with `\f` or `\m` will escape the problem, but it's harmless and
might be a less intrusive change for their groff code generator to start
all of them with `\&` regardless.

Also, I think the generator should declare itself in a preamble comment.

If any pandoc hackers are monitoring this list, please speak up.  We can
help.

**Comment by jgm** [comment]
Thank you for the advice, @RobertGoulding !

**Comment by jgm** [comment]
> Also, I think the generator should declare itself in a preamble comment.

Done this.
