### ISSUE TITLE
Allow specifying Inkspace for svg conversion tool (as well as rsvg-convert)

### ISSUE THREAD

**Issue by fuhrmanator** [jgm/pandoc#8176]
**Describe your proposed improvement and the problem it solves.**

Some SVG files (those with certain foreignObject?) get (better) conversion to PDF (or other destinations) with Inkscape rather than rsvg-convert. It would be good to have a way to specify which SVG converter to use. 

**Describe alternatives you've considered.**

I've considered various filters (gists, python, hs), but they seem to be unmaintained by a community. 
ConTeXt apparently supports inkscape (if it's installed), but for my project I can't use ConTeXt.

**Comment by jgm** [comment]
What would be the command for converting on the command line via inkscape?

**Comment by fuhrmanator** [comment]
I'm not sure I understand the question, but I could suggest for pandoc:

```--svg-converter=CONVERTER```

`CONVERTER` is either `rsvg-convert` or `inkscape`

Or are you asking about how to convert with inkscape:

```inkscape --export-filename=sample.pdf sample.svg```

I believe the extension of the export filename determines the destination format (pdf, png, etc.) 

There is documtation [here](https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line#Export_files).

**Comment by jgm** [comment]
Is inkscape strictly better than rsvg-convert?  Or is it better in some cases and worse in others?  If it's strictly better, perhaps we could always use inkscape if available and fall back on rsvg-convert.  Then we wouldn't need a new option.

**Comment by tarleb** [comment]
For the necessary commands see the [respective function](https://github.com/pandoc/lua-filters/blob/master/diagram-generator/diagram-generator.lua#L147-L182) in the diagram-generator.lua filter. As can be seen there, the whole process is made more complex by having to check for the installed inkscape version, as the parameter names are not the same in v1 and v2.

**Comment by matclab** [comment]
If you arrived here because of some SVG produce by mermaid, you can get rid of the *foreignObjects* by adding `%%{init: {"flowchart": { "htmlLabels": false}} }%% ` before the `flowchart` or `graph` line to solve the problem

**Comment by alerque** [comment]
Regarding the original suggestion, `inkscape` continues to be problematic for scripted CLI usage. An unpredictable set of actions and/or input/output formats trigger the GUI to start and close even when running CLI actions, the options regarding bounding boxes (page, bleed, crop boxes, etc.) are not tested from the CLI before releases and regularly break, etc. I would suggest it is not well suited to baking into `pandoc`. Perhas allowing a custom converter command to be specified at runtime would serve the purpose for specific scenarios, but it is a relatively unstable target to try to bake in support for (speaking as someone who maintains baked in support for scripted use in `casile`).

**Comment by Foadsf** [comment]
@fuhrmanator I think an inherently better and more robust solution is to use headless Chromium based internet browsers, such as Google Chrome or Microsoft Edge, in headless mode to convert SVG to PDF. For example see [this post](https://superuser.com/a/1455109/588662). For example 

    msedge --headless --disable-gpu --print-to-pdf=<output-pdf-path> <input-svg-path>

**Comment by fuhrmanator** [comment]
Thanks @Foadsf ! That is super useful, and I've used headless Chrome in software testing pipelines. 

Now, how to make it work in the pandoc pipeline? I'm using tools like Quarto and it defaults to `rsvg-convert` which fails on many of my SVG files, the impetus for this issue.

**Comment by Foadsf** [comment]
I'm totally a fan of your proposal to let the user choose for their SVG converter, but yeah `rsvg-convert`, `CairoSVG`, Ghostscript, Inkscape,... all seem to have issues with SVGs generated with Mermaid CLI. So I suppose the starting point should be search Pandoc's code base and find the exact line(s) where it attempts to call `rsvg-convert` and then replace it with headless browsers. Try and error!

**Comment by jgm** [comment]
I don't want to reopen this issue, because I don't think inkscape is an improvement over rsvg-convert.  But headless chrome might be.  Feel free to open a new issue, including the command-line invocations that would work for both chrome and edge.  (I guess we could always see what is in the path - edge, chrome, chromium, rsvg-convert - and use the best available option.)

**Comment by fuhrmanator** [comment]
I was ready to open a new issue, and tried some conversions to verify the command-line info. But I got stuck because everything comes out in the PDF as US Letter size (I was able to turn off header/footer with `--no-pdf-header-footer`), which is definitely not good for my use cases. I verified in my SVG that my document size was constrained to the image (there's an `<svg width="500px" height="500px" viewBox="0 0 500 500" ...>` tag), but the PDF produced by `msedge` was still 8.5" x 11".

It seems edge/chrome/chromium doesn't have a command-line option to use the SVG's bounding box for the PDF page size. There are some work-arounds (see https://stackoverflow.com/questions/44970113/how-can-i-change-paper-size-in-headless-chrome-print-to-pdf/) if you put the SVG in an HTML document with a CSS setting of the bounding box, but that's seems overly complicated compared to how the other tools work. ChatGPT suggested creating a script that uses Puppeteer (nodejs), which also doesn't seem viable for a pandoc pipeline. 

@Foadsf did I miss something? Otherwise, without variable-sized PDF output, I can't see this as a good option.

**Comment by Foadsf** [comment]
@fuhrmanator I am no expert here, but I would say manually hardcoding the page/frame size, is not a the bets idea. According to [this comment](https://github.com/mermaid-js/mermaid/issues/2688#issuecomment-2400256070), Inkscape has the `--export-area-drawing` option to take care of that, and `mmdc` also has the `--pdfFit` which fits better to my use-case. 

TBH, I have not tested the headless browser idea much other than [this post](https://stackoverflow.com/a/78897582/4999991), but I think if we want to resolve these issues in a canonical way, we need to go upstream and open issues for `rsvg-convert`/`cairosvg`... another option is also to use Puppeteer which AFIK is used also by `mmdc` and the output PDFs seem fine.

**Comment by Foadsf** [comment]
@jgm please check [this simple Node.js script](https://gist.github.com/Foadsf/6e7db7504b7a90a44fef4f23fe36765d). feel free to just include it anywhere you need. More on this [here](https://superuser.com/a/1859471/588662).

**Comment by jgm** [comment]
@Foadsf this worked pretty well in my tests, but it produced a two-page PDF for a one-page SVG.

About the dependencies: I know nothing about 'puppeteer' - is this dependency something that would need to be installed?

**Comment by tarleb** [comment]
A past Haskell/Google Summer of Code project touched on this, [cdp-hs](https://github.com/arsalan0c/cdp-hs). It should be possible to use that instead of puppeteer.

**Comment by cesaryuan** [comment]
@jgm would it be worth considering `resvg` as the first choice before `rsvg-convert`/librsvg when Pandoc auto-detects an SVG converter?

The reason I ask is that it seems to fit the constraints discussed here better than the other alternatives:

- unlike Inkscape, it is explicitly usable as a headless CLI/library for rendering static SVG files, so it avoids the GUI/CLI instability concerns raised above;
- unlike a browser/Puppeteer-based route, it is a small standalone renderer with no heavyweight runtime dependency;
- compared with librsvg, its own SVG support test chart currently looks noticeably stronger: `resvg 0.45.1` passes 1520 tests vs `librsvg 2.58.0` passing 1168;
- it is implemented in Rust, has very little `unsafe`, and aims for reproducible output across platforms, which seems attractive for a Pandoc pipeline.

The chart from the resvg project makes the comparison pretty clear:

![resvg SVG support chart](https://raw.githubusercontent.com/linebender/resvg/main/.github/chart.svg)

Source: https://github.com/linebender/resvg/blob/main/.github/chart.svg

So maybe the default preference order could be something like `resvg` first, then `rsvg-convert` as fallback, at least for the output modes where `resvg` fits Pandoc's conversion path?

Would you prefer reopening this issue for that discussion, or should I open a new issue focused specifically on considering `resvg` and the SVG converter preference order?

**Comment by jgm** [comment]
Open #11729
