### ISSUE TITLE
Pass through `\passthrough`

### ISSUE THREAD

**Issue by dbitouze** [jgm/pandoc#8179]
**Describe your proposed improvement and the problem it solves.**
It would be nice to able to “pass through `\passthrough`” (BTW, I don't see the point of this command). Indeed, consider the following diverging chain:
```
$ cat tex.tex
\documentclass{article}
\usepackage{listings}
\begin{document}
A (La)TeX command: \lstinline|\textbf{}|.
\end{document}
$ pandoc -f latex -t rst tex.tex -o tex2rst.rst && cat tex2rst.rst
A (La)TeX command: ``\textbf{}``.
$ pandoc -f rst -t latex --listings tex2rst.rst -o tex2rst2tex.tex && cat tex2rst2tex.tex
A (La)TeX command: \passthrough{\lstinline!\\textbf\{\}!}.
$ pandoc -f latex -t rst --listings tex2rst2tex.tex -o tex2rst2tex2rst.rst && cat tex2rst2tex2rst.rst
A (La)TeX command: ``\\textbf\{\}``.
```
Obviously, what is expected here is:
1. the `tex2rst2tex.tex` file to be identical to (the relevant lines of) the first (starting) one (`tex.tex`):
   ```
   A (La)TeX command: \lstinline|\textbf{}|.
   ```
2.  the `tex2rst2tex2rst.rst` file to be identical to the second one (`tex2rst.rst`):
    ```
    A (La)TeX command: ``\textbf{}``.
    ```

**Comment by dbitouze** [comment]
BTW, no such a diverging chain when going from `reStructuredText` to:

1. `Markdown`:
```
$ cat rst.rst
A (La)TeX command: ``\textbf{}``.

.. code:: latex

   \textbf{Foo}
$ pandoc -t markdown -f rst rst.rst -o rst2md.md
$ pandoc -f markdown -t rst rst2md.md -o rst2md2rst.rst
$ diff rst.rst rst2md2rst.rst
$
```
2. `Org-mode`:
```
$ pandoc -t org -f rst rst.rst -o rst2org.org
$ pandoc -f org -t rst rst2org.org -o rst2org2rst.rst
$ diff rst.rst rst2org2rst.rst
$
```

**Comment by jgm** [comment]
For the motivation for `\passthrough` see #1629 and commit 730796ee314d42477fab216621b8e44539c94656
I think what we may need to fix here is support for `\passthrough` in the latex reader, added in 99e24cf18337b0b460005bf77e367783c34b75e7.

We need to unescape the characters `%{}\` inside passthrough.
