### ISSUE TITLE
reveal.js: move fade-* attributes from <span> to parent <p>

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#8180]
As discussed in hakimel/reveal.js/issues/3108

> As you can [see in this slide](https://reagle.org/joseph/talks/2014/exemplar.html#/fragment-styles-markdown) fragment styles `fade-up`, `fade-down`, `fade-left`, `fade-right` do not work when used on a `span` within a `p`.  All fragment styles do, and `p/span` is the structure used by pandoc.

@cderv notes "I don't think `transform` applies to `span`s".

In the reveal.js writer, could these attributes be used in the parental `p` instead?

pandoc 2.18 on macOS 12.4 21F79 arm64

**Comment by jgm** [comment]
I'm not sure I understand the problem.  Are you trying to apply these attributes to a whole paragraph?  In that case it would be more appropriate to put it in a fenced div with the attributes. Maybe that won't work either with reveal.js, but it's something you could try.

**Comment by reagle** [comment]
@cderv, yes, the simple case works in reveal.js. (In this case, we can also just drop the spans.)

    <p class="fragment fade-out"><span>fade-out</span></p>

When it comes to sibling/nesting, I don't know. If, as you say, `fade-up`, `fade-down`, `fade-left`, and `fade-right` use a transform function that don't work on spans *and* you want to do sibling/nesting transforms, that's an issue reveal.js would have to address. If it won't/can't be fixed, then my suggestion in pandoc is a hack so the simple case works. However...

@jgm, yes, your suggestion works and is a better approach then changing the writer. So I'll close the issue here on pandoc and leave the one on revealjs open.

    ::::{.fragment .fade-up}
    testing [jgm suggestion](https://github.com/jgm/pandoc/issues/8180#issuecomment-1185310886)
    ::::
