### ISSUE TITLE
Unicode char not set, when converting markdown to pdf

### ISSUE THREAD

**Issue by Finkman** [jgm/pandoc#8183]
## Explain the problem:

I'd like to convert a simple markdown table to pdf:

```md
| Restrictions |        |
| ------------ | ------ |
| **Minimum**  | &gt; 0 |
| **Maximum**  | &le; 1 |
```
To achieve that: i ran:
```
pandoc test.md -o test.pdf 
```
Pandoc generated latex code which caused an error on pdflatex:

```
Error producing PDF.
! LaTeX Error: Unicode character ≤ (U+2264)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.67 \textbf{Maximum} & ≤

```

### Pandoc

pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/fins/.local/share/pandoc or /home/fins/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

### pdflatex

pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)
kpathsea version 6.3.4/dev
Copyright 2021 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.03

### OS

Ubuntu 22.04

**Comment by jgm** [comment]
pdflatex is not designed for unicode. Use `--pdf-engine=xelatex` (or with your ancient version of pandoc, `--latex-engine=xelatex).  (IF you used a more recent version of pandoc, you would have gotten a message suggesting this.)

**Comment by johnshajiang** [comment]
I'm encountering the similar issue with the latest pandoc on my macOS 14.5.

```
% pandoc --version
pandoc 3.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /path/to/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**How to reproduce**

```
% cat test.md 
中文(Chinese)
```

```
% pandoc test.md -o test.pdf
Error producing PDF.
! LaTeX Error: Unicode character 中 (U+4E2D)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...
                                                  
l.58 中
```

```
% pandoc --pdf-engine=xelatex test.md -o test.pdf
[WARNING] Missing character: There is no 中 (U+4E2D) (U+4E2D) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no 文 (U+6587) (U+6587) in font [lmroman10-regular]:mapping=t
```

**Comment by tarleb** [comment]
@johnshajiang

You can either try

    pandoc -M CJKmainfont="Noto Serif CJK TC" ...

or, if your document is mostly English,

``` markdown
---
lang: en
babelfonts:
  chinese: "Noto Serif CJK TC"
---

[中文]{lang=zh}(Chinese)
```

Please refer for follow-up questions to the [Discussions](https://github.com/jgm/pandoc/discussions) forum.

**Comment by sylvaticus** [comment]
Hi I have the same issue, and by using `--pdf-engine=xelatex` at least the PDF compiles, but then I have the error (and missing chars in the document):

`[WARNING] Missing character: There is no ₂ (U+2082) (U+2082) in font [lmroman10-regular]:mapping=t`

**Comment by jgm** [comment]
The fix is to specify a `mainfont` that has the glyph.

**Comment by bpj** [comment]
If there are only a few characters missing this fixes the issue for any characters:

``` latex
% This requires XeLaTeX or LuaLaTeX as --pdf-engine
% and the newunicodechar package to be installed
\usepackage{newunicodechar}
% Use a font which has the glyph
\newfontfamily\cjkfont{Noto Serif CJK TC}
\newunicodechar{中}{{\cjkfont 中}} % Yes this works!
\newunicodechar{文}{{\cjkfont 文}}
```

I use if all the time with characters from Noto Sans Symbols and similar fonts.

Either save it to a file and include the file with the `-H filename.tex` option.
