### ISSUE TITLE
Exporting Markdown with \num to docx produces blank output

### ISSUE THREAD

**Issue by Benjamin-Lee** [jgm/pandoc#8186]
**Explain the problem.**

`\num{10e100}` produces no output when exporting to Word. I believe this is a bug because there's a commit merging this feature: 0a98648c1a64d382cdd577ecc1fc2245c6eb57e2

Example:

```
---
header-includes:
  - \usepackage{siunitx}
---

This is a big number: \num{10e100}.
```

PDF:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/13618205/179312520-6275c8ac-f672-4d9d-b29b-6bf0deb85138.png">

Word:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/13618205/179312560-08289b36-bd67-4484-b56a-64be5e4e72a3.png">

**Pandoc version?**
What version of pandoc are you using, on what OS?

```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /Users/BenjaminLee/.pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
The commit you mention adds support for siunitx macros to the LaTeX reader.  But you are not reading LaTeX, but Markdown.  The Markdown reader passes through LaTeX as raw LaTeX; it is not parsed by the LaTeX reader. Hence it does not get passed through to non-LaTeX formats like docx. This is all just as documented, and thus not a bug.

**Comment by jiucenglou** [comment]
> The commit you mention adds support for siunitx macros to the LaTeX reader. But you are not reading LaTeX, but Markdown. The Markdown reader passes through LaTeX as raw LaTeX; it is not parsed by the LaTeX reader. Hence it does not get passed through to non-LaTeX formats like docx. This is all just as documented, and thus not a bug.

Could you suggest whether it is possible to recognize siunitx in Markdown ?

**Comment by jgm** [comment]
Try this:
```
This is a big number: $\num{10e100}$.
```

Pandoc will recognize (some) sliunitx commands in math contexts.

**Comment by jiucenglou** [comment]
> Try this:
> 
> ```
> This is a big number: $\num{10e100}$.
> ```
> 
> Pandoc will recognize (some) sliunitx commands in math contexts.

Could the options to `\num` and `\qty` be supported in pandoc ? For example, the `\qty`  could be used as `\qty[parse-numbers = false,retain-explicit-plus]{+3.6 (=-13.8--17.4)}{\kilo\cal\per\mol}`.
