### ISSUE TITLE
`definition_lists` doesn't support multiple terms

### ISSUE THREAD

**Issue by ayushnix** [jgm/pandoc#8190]
**Explain the problem.**
The PHP Markdown Syntax Extra format describes [support for specifying multiple terms](https://michelf.ca/projects/php-markdown/extra/#def-list) using

```md
This is a sample file to showcase the pandoc `definition_lists` extension.

Term 1
Term 2
:   Definition a

Term 3
:   Definition b
```

However, when I execute 

```
pandoc --from commonmark+definition_lists --to html5 sample.md -o sample.html
```

I get

```html
<p>This is a sample file to showcase the pandoc
<code>definition_lists</code> extension.</p>
<dl>
<dt>Term 1 Term 2</dt>
<dd>
Definition a
</dd>
<dt>Term 3</dt>
<dd>
Definition b
</dd>
</dl>
```

`Term 1` and `Term 2` are wrapped in a single `<dt>`.

**Pandoc version?**
```
$ pandoc --version
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5.1, skylighting 0.12.3.1,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
User data directory: /home/proteus/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

$ uname -sro
Linux 5.18.12-arch1-1 GNU/Linux

$ cat /etc/os-release
NAME="Arch Linux"
```

**Comment by jgm** [comment]
That's right, pandoc's syntax is a bit different in this regard (the manual could make this clearer).
There are some reasons for this:

1.  in some output formats that have definition lists or the equivalent, you can't have multiple terms (e.g. LaTeX)
2. in general, sequences of inline elements in markdown can contain newlines which act like spaces; we preserve that behavior, allowing long terms to be hard-wrapped.
3. multiple terms can be simulated by including a hard break (e.g. backslash-newline) in the term
