### ISSUE TITLE
Multiple --csl arguments give bad error message

### ISSUE THREAD

**Issue by mgajda** [jgm/pandoc#8195]
**Explain the problem.**

If using `pandoc` within a build pipeline, one may mistakenly give two `--csl` arguments:

```
pandoc -s input.md --csl style1.csl --csl style2.csl -o output.pdf 
```

This will give a spurious error message when `pandoc` tries to find `style1.csl style2.csl` which is not a file.

The issue stems from the fact that [`Text.Pandoc.App.CommandLineOptions.addMeta`](https://github.com/jgm/pandoc/blob/e04ea99326261c1fa935971a864477ce4e4182b1/src/Text/Pandoc/App/CommandLineOptions.hs#L1090) tries to append data to the previous meta.
Unfortunately, [`--csl` option does not treat the input as a list of styles, instead merges it](https://github.com/jgm/pandoc/blob/e04ea99326261c1fa935971a864477ce4e4182b1/src/Text/Pandoc/App/CommandLineOptions.hs#L734).

Would it be more convenient to use separate `replaceMeta` (possibly with a warning when previous metadata was non-empty), or change parsing of meta only for CSL?

Currently [`Text.Pandoc.Citeproc.getStyle`](https://github.com/jgm/pandoc/blob/e04ea99326261c1fa935971a864477ce4e4182b1/src/Text/Pandoc/Citeproc.hs#L123) simply uses [`metaValueToText`]() before trying to read it as a full path.

**Pandoc version?**

```
$ pandoc --version
pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1
User data directory: /home/m/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```
This is Linux version.

**Comment by mgajda** [comment]
The issue stems from the fact that `Text.Pandoc.App.CommandLineOptions.addMeta` tries to append data to the previous meta.
Unfortunately, `--csl` option does not treat the input as a list of styles, instead merges it.

**Comment by jgm** [comment]
> Would it be more convenient to use separate replaceMeta (possibly with a warning when previous metadata was non-empty), or change parsing of meta only for CSL?

Yes, I think that's a good idea.  If you specify two `--csl` options, one should be ignored, with a warning.
Is this something you want to do a PR for?

**Comment by pt2121** [comment]
Can I take a stab at this?

**Comment by jgm** [comment]
Go for it!

**Comment by pt2121** [comment]
I am looking into this and wondering if we should 
- let the user run pandoc with a warning, 
- or not run it and show an error message.

Any opinions on this?
