### ISSUE TITLE
Faulty `.yaml` metadata gives no error message and misleading errors

### ISSUE THREAD

**Issue by mgajda** [jgm/pandoc#8196]
**Explain the problem.**

Having a duplicate field in `.yaml` metadata in the beginning of Markdown file results in ignoring the following metadata,
and frequently spurious errors because of silently ignored configuration in `header-includes` or `bibliography`.

`pandoc` should instead show the warning or error for the YAML metadata that points where the issue originates.

**Pandoc version?**

```
pandoc 2.14.0.3
Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.10.5.2,
citeproc 0.4.0.1, ipynb 0.1.0.1
User data directory: /home/m/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

OS:
```
$ uname -a
Linux xyp 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jgm** [comment]
You're using an older version of pandoc. Can you try with the latest? I get this:
```
% pandoc -t native -s
---
a: 2
b: 2
a: 3
c: 4
...
Pandoc
  Meta
    { unMeta =
        fromList
          [ ( "a" , MetaInlines [ Str "3" ] )
          , ( "b" , MetaInlines [ Str "2" ] )
          , ( "c" , MetaInlines [ Str "4" ] )
          ]
    }
  []

```
The second value for the duplicated key `a` is used; other keys are unaffected.

**Comment by jgm** [comment]
Many YAML parsing libraries, including the one we're using, don't raise an error in this case.

**Comment by mgajda** [comment]
So I understand that the confusing behaviour is to be maintained because of the bug in the YAML library?
Or is it that the bug should be reported upstream to the library authors?

**Comment by jgm** [comment]
You can report it if you like to the yaml library:
https://hackage.haskell.org/package/yaml
We can't do much about it if the yaml library doesn't raise an error.
