### ISSUE TITLE
hypersetup from header-includes is always overridden by the template (Pandoc 2.18 breaking change)

### ISSUE THREAD

**Issue by AndreyAkinshin** [jgm/pandoc#8198]
In Pandoc 2.17, it was possible to define `\hypersetup` in header-includes and get custom colors for links/citations/urls:
```tex
\usepackage{hyperref}
\definecolor{linkcolor}{rgb}{0.9,0,0}
\definecolor{citecolor}{rgb}{0,0.6,0}
\definecolor{urlcolor}{rgb}{0,0,1}
\hypersetup{
    colorlinks,
    linkcolor={linkcolor},
    citecolor={citecolor},
    urlcolor={urlcolor}
}
```
The LaTeX template also contained its own `\hypersetup` command, but it was defined before header-includes so that it was easy to override it.

In Pandoc 2.18, a breaking change was introduced (see f3fcdd52c8bc722862ea73958d41fe53ec03ec1d): the template `\hypersetup` command was moved near the end of preamble. Now it's placed after header-includes and overrides user-defined `\hypersetup` from header-includes. By default (`colorlinks` is `false`), it looks like this:

```tex
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
```

Thus, documents with user-defined colors via header-includes have colored references in Pandoc 2.17 and black references in Pandoc 2.18.

**Comment by jgm** [comment]
I see why this might create a problem, but there were good reasons for moving hyperref to the end, and we can't use `\hypersetup` until hyperref is loaded.  So, do you have a solution?

**Comment by AndreyAkinshin** [comment]
The problem can be resolved by omitting `hidelinks` in the template's `hypersetup`: in this case, the color settings from the first user-defined `hypersetup` will be used. However, we can't remove `hidelinks` by default because it would cause another breaking change (all the links will have colored borders which is the LaTeX default behavior). So, it would be nice to have an option to control this behavior. I would suggest introducing a new boolean option called `hidelinks` (the default value is `true`). It looks reasonable to use the following behavior:

* `colorlinks=false`, `hidelinks=false`: template's `hypersetup` doesn't include neither `colorlinks` nor `hidelinks`. This configuration allows the user to define its own color configuration in header-includes
* `colorlinks=false`, `hidelinks=true`: the current (Pandoc 2.18) default behavior, black links without colored borders are used
* `colorlinks=true`: template's `hypersetup` uses colored links, `hidelinks` is ignored

@jgm What do you think?

**Comment by jgm** [comment]
I like the basic idea but I think I'll go with `boxlinks` instead of `hidelinks` (with opposite behavior).

**Comment by jgm** [comment]
I've pushed a change that should help (you'd use `-Vboxlinks` together with your custom hypersetup). Let me know if this works.

By the way, why do you need color settings from a user-defined hypersetup?  Are there settings you can't control with pandoc's variables for colors?

**Comment by AndreyAkinshin** [comment]
> From the Solve-Everything-With-Lua Department: A custom writer can remove the hypersetup from the template, so your old code will work again. Use with pandoc --to=nohypersetup.lua ..., where nohypersetup.lua contains

@tarleb, thanks for the tip!

> I like the basic idea but I think I'll go with boxlinks instead of hidelinks (with opposite behavior).
> I've pushed a change that should help (you'd use -Vboxlinks together with your custom hypersetup). Let me know if this works.

@jgm, It works like a charm, thanks! (I have checked [Nightly 1007](https://github.com/jgm/pandoc/actions/runs/2745054560))

> By the way, why do you need color settings from a user-defined hypersetup? Are there settings you can't control with pandoc's variables for colors?

@jgm, I know that I can use predefined colors from `dvipsnames`, `svgnames`, and `x11names`. However, I would like to use custom RGB colors that are not covered by the above lists. The only way I know is to define a custom color via `\definecolor` and use it in `\hypersetup`.

It there a way to define a custom color using pandoc's variables?

**Comment by jgm** [comment]
Can't you simply use `\definecolor` in your header includes, and then pass the color names you define in through the usual pandoc variables?

**Comment by AndreyAkinshin** [comment]
> Can't you simply use `\definecolor` in your header includes, and then pass the color names you define in through the usual pandoc variables?

@jgm it works, thanks for another great tip!

**Comment by jtbayly** [comment]
Can somebody help me understand this a bit better, please?

I use Pandoc with a lot of books, and I have a standard preamble.tex that I use for all of them. I have the following code in my preamble.tex that used to color all my links our custom color:

```
% define link colors
\usepackage{hyperref}
\definecolor{perfectTeal}{RGB}{26, 169, 171}
\hypersetup{
    colorlinks=true,
    linkcolor=perfectTeal,
    filecolor=perfectTeal,
    urlcolor=perfectTeal,
}
```

Adding 'colorlinks: true' to my YAML makes the links show up, but the wrong (default) colors. 

Is the only way to get this working again to add the redundant and confusing 'boxlinks: true' to the YAML of each and every one of our books?

I try to keep all the configuration out of the books and in a separate file that is imported and used by each book. Then I can make a change in one place and have it reflected in every book.

**Comment by jgm** [comment]
it's tough to help without more details.  What pandoc version are you using?  And how are you including your preamble.tex -- are you using `--include-in-header`?  If you're not using the most recent release, please try again with that.

**Comment by jtbayly** [comment]
Sorry, I meant to say that I updated to 2.19.2. I'm using bookdown, which yes, uses --include-in-header to include the preamble.tex file.

As far as I can tell, the basic problem still remains as described in the title of this issue: "hypersetup from header-includes is always overridden by the template"

If the only way around that is to add boxlinks=true to my YAML, then that's what I'll do, I guess. But doesn't boxlinks=true mean that links should be boxed? And that's not what I want, so it's quite confusing that that's the only way I've found that allows me to both turn on and specify the colors for links. Hope this makes sense of what I'm seeing.

**Comment by jgm** [comment]
Why not follow the suggestion above?  Add
```
\definecolor{perfectTeal}{RGB}{26, 169, 171}
```
in your header-includes, and then just set
```
colorlinks: true
linkcolor: perfectTeal
filecolor: perfectTeal
etc.
```
in your variables or metadata?
That should work fine.

**Comment by jtbayly** [comment]
Two reasons. 

1. I either missed or didn't understand the details of what was suggested above. Your recent comment makes it quite clear that I don't *need* to use boxlinks as I thought. Thanks! However, am I correct that *is* the only way I can set the url colors in my preamble instead of elsewhere? Which leads to...
2. The other reason is that I try to do everything I can in the preamble.tex for PDF generation. This solution adds another place where things are happening in my codebase that affect the PDF output. I liked it better when I could just turn on colorlinks and customize it all right in my preamble. Nevertheless, as I said above, if this is the way it is, then I'll make do. 

This does make me wonder, though, why colorlinks isn't on by default?

Thanks for the tremendous software and all your work.
