### ISSUE TITLE
Allow multiline Markdown headers

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#82]
<pre>
It would be nice if pandoc markdown could allow multiline headers -- that is, multiline in the input, not necessarily in the output (though that could be controlled by a backslash or double-space). This can be an issue with chapter titles, which sometimes have subtitles, and go well beyond 80 characters.

For level 1 and 2 in setext style, the following syntax seems intuitive:

    Long Header Containing a Clever Title for This Section:
    An Overly Wordy Subtitle Explaining What the Clever Title Meant
    ===============================================================

(with an optional backslash after the colon)

Since pandoc breaks from Markdown.pl on requiring a blank line before a header, this wouldn't seem to introduce any new compatibility issues.

I'm not sure if there's an intuitive way in atx headers, though.

Not a huge deal on the writing end, since I can turn off auto-fill-mode for atx headers in emacs automatically, but it seems like it would be a win as far as readability goes.

Google Code Info:
Issue #: 289
Author: jesse.k....@gmail.com
Created On: 2011-02-17T15:22:47.000Z
Closed On: 
</pre>

**Comment by chronodm** [comment]
Was this closed because it's implemented, or because it's been decided that it won't be implemented?

**Comment by jgm** [comment]
Won't be implemented.

+++ chronodm [Aug 01 16 14:50 ]:

**Comment by anowlcalledjosh** [comment]
A note to anyone that happens upon this issue: the following appears to work (at least from Markdown to PDF via XeTeX).

```
# This is my \
  very long header
```

It looks like this in the table of contents:

![screenshot 2017-03-02 at 12 11 29 pm](https://cloud.githubusercontent.com/assets/9433472/23506692/6e819ba0-ff41-11e6-8ed3-c91f9b1a9c3a.png)

and this in the text:

![screenshot 2017-03-02 at 12 12 15 pm](https://cloud.githubusercontent.com/assets/9433472/23506704/801c0738-ff41-11e6-859a-85e1ed873baa.png)

It doesn't seem to matter if the second line is indented or not.
