### ISSUE TITLE
custom readers in DATADIR

### ISSUE THREAD

**Issue by TheCoder49** [jgm/pandoc#8203]
Maybe there is a way, but I couldn't find it.

It seems strange to me, that it is possible to refer to templates and filters in `$DATADIR` (`filters` and `templates` folders respectively), but there is no option to do the same with a custom lua reader.

I have to refer to it by the absolute or relative path.

Could it be made so one could refer to the reader by name directly, by putting it into `$DATADIR\readers` folder?

**Comment by tarleb** [comment]
This is available in the current development version, see #8112 and #8135.

**Comment by revolter** [comment]
Doesn't seem to work:

```sh
> ls ~/.local/share/pandoc/writers
rtf_trimmed.lua

> echo '_test_' | pandoc --from='markdown-smart' --to='rtf_trimmed.lua'
Error running Lua:
cannot open rtf_trimmed.lua: No such file or directory
```

**Comment by tarleb** [comment]
The folder name changed to `custom` in pandoc 3.
