### ISSUE TITLE
RST quotes second level lists

### ISSUE THREAD

**Issue by Timmmm** [jgm/pandoc#8206]
**Explain the problem.**

Consider this RST:

```
Foo

  - bar
```

Note the spaces before the `-`.

Sphinx interprets this as just a second level bullet item (with no first level one) (check [here](https://livesphinx.herokuapp.com/)).

Pandoc 2.18 interprets this as a block quote. It converts it to this markdown:

```
Foo

> -   bar
```

I feel kind of bad for reporting an RST issue since it's a terrible format but it's what I am working with... sorry!

**Pandoc version?**
2.18, Mac.

**Comment by jgm** [comment]
Well I tried this with docutils rst2html.py, which should be the gold standard for this format. Got:
```
<p>Foo</p>
<blockquote>
<ul class="simple">
<li>bar</li>
</ul>
</blockquote>
```
So I think pandoc's interpretation is correct.

Note: your online sphinx thing also shows a blockquote (view source); it's just not evident from the rendering.

**Comment by Timmmm** [comment]
Ah nice spot, sorry for the noise!
