### ISSUE TITLE
[docx reader]: checkbox field is not converted into other formats

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#8211]
In pandoc v2.18, checkbox field contained in docx file is not converted into other formats, such as markdown and html.

I am attaching a test file:

[checkbox_field.docx](https://github.com/jgm/pandoc/files/9237455/checkbox_field.docx)

``` bash
pandoc checkbox_field.docx -o output.md
```

**Comment by cijcij** [comment]
in case from other formats to docx, the checkbox also not handled correctly…… 

see: https://github.com/jgm/pandoc/issues/5198
