### ISSUE TITLE
Convert DOCX > Markdown inserts space after Y, F,

### ISSUE THREAD

**Issue by puremovic** [jgm/pandoc#8212]
**Explain the problem.**
`pandoc -s moonray.docx -t markdown_strict+simple_tables -o moonray.md`

Spaces after `f`, `v`, and other characters. Also inserts `&gt;` at start of a new line (exc first line).
**Example output:**
<pre>
Here are 2 equal time renders, the f irst with adaptiv e
> sampling of f , and the second with adaptiv e sampling swi tched on.
> Notice how the error is spread out more unif ormly in the second
> image, as well as how the f iref lies are attenuated.
</pre>

**Pandoc version?**
$ pandoc -v
pandoc.exe 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4

**Comment by jgm** [comment]
We can't possibly help without a sample docx to test with.
