### ISSUE TITLE
Backlink: remove "variation selection" character (U+FE0E)?

### ISSUE THREAD

**Issue by Iacobus1983** [jgm/pandoc#8213]
Recently, Kindle has started supporting epub format. I sent to kindle an epub generated with pandoc; near the backlink character, there was a strange sign, a sort of missing glyph. I inspected the html inside my epub, and discovered that, after the backlink character (U+21A9 : LEFTWARDS ARROW WITH HOOK), there is an invisible U+FE0E : VARIATION SELECTOR-15 [VS15] {text variation selector}. Is this character there with purpose? Or is it a bug? In the latter case, perhaps it can be removed from pandoc source code.

**Comment by jgm** [comment]
Yes, it has a purpose.  It forces a regular character front the font to be used.  Otherwise iOS (and perhaps other platforms) replaces the U+21A9 with a big emoji!

**Comment by tarleb** [comment]
For reference: #5469
