### ISSUE TITLE
gm conversion 

### ISSUE THREAD

**Issue by ahmadnassri** [jgm/pandoc#8214]
**Explain the problem.**

pandoc inserts spaces after list markers:

input: `in.md`

```
- a
  - b
- c
```

command:
```
pandoc \
  --output=out.md \
  --from=gfm \
  --to=gfm \
  --fail-if-warnings \
  --wrap=preserve \
  --reference-links \
  in.md
```

output: `out.md`
```
-   a
    -   b
-   c
```

**Pandoc version?**

`pandoc/minimal:2.18.0` docker image

**Comment by jgm** [comment]
Not a bug.  This is semantically equivalent.

**Comment by ahmadnassri** [comment]
is there anyway to control this behavior? change the spacing for lists?

**Comment by jgm** [comment]
Not without modifying the source code.
But you're in luck: the source code *was* modified recently.
See #8011.
You can try a nightly.
