### ISSUE TITLE
Markdown grid-tables parsing regression

### ISSUE THREAD

**Issue by kazalex** [jgm/pandoc#8216]
Markdown grid-table:
```.markdown
: Grid Table

+-----------------+:-:+
|Some text        |[text]{.class1 .class2 .class3}|
+-----------------+---+
|Some text        |[text]{.class1 .class2 .class3}|
+-----------------+---+
|Some text        |[text]{.class1 .class2 .class3}|
+-----------------+---+
```
Pandoc **2.18**, Linux amd64, HTML5 output:
```.html
<table style="width:31%;">
<caption>Grid Table</caption>
<colgroup>
<col style="width: 25%" />
<col style="width: 5%" />
</colgroup>
<tbody>
<tr class="odd">
<td>Some text</td>
<td style="text-align: center;"><span
class="class1 class2 class3">text</span></td>
</tr>
<tr class="even">
<td>Some text</td>
<td style="text-align: center;"><span
class="class1 class2 class3">text</span></td>
</tr>
<tr class="odd">
<td>Some text</td>
<td style="text-align: center;"><span
class="class1 class2 class3">text</span></td>
</tr>
</tbody>
</table>
```
Pandoc **2.19**, Linux amd64, HTML5 output:
```.html
<table style="width:25%;">
<caption>Grid Table</caption>
<colgroup>
<col style="width: 25%" />
</colgroup>
<tbody>
<tr class="odd">
<td>Some text</td>
</tr>
<tr class="even">
<td>Some text</td>
</tr>
<tr class="odd">
<td>Some text</td>
</tr>
</tbody>
</table>
```
Second column was lost.

---
Little suggestion concerning calculation width of columns. May be columns width calculation will more accured when will take only content symbols instead of all symbols (includes format/style specialization).

**Comment by jgm** [comment]
@tarleb can explain better why this change occurred and whether it was intended.
For what it's worth, I never would have regarded your table as a valid pipe table, since it doesn't line up properly. The parser may have parsed it as such, but you were relying on "undefined behavior."

**Comment by kazalex** [comment]
Other case. Invalid grid-table:
```.markdown
+------+---------+
| text | 1                     |
+------+-----------------------+
| text | 1                     |
+------+-----------------------+
```
Pandoc 2.19 console output:
```
pandoc: unassigned: (1,2)
CallStack (from HasCallStack):
  error, called at src/Text/GridTable/Trace.hs:424:19 in gridtables-0.0.2.0-216b266edda623c88c6ab1938a16bbc8c70b1ead6acc398f6ff199b845d0325d:Text.GridTable.Trace
```

**Comment by tarleb** [comment]
Thanks for the reports, I'll look into it. The crash with the invalid table is definitely an issue that'll need fixing, and the other could be supported more gracefully.

**Comment by tarleb** [comment]
The malformed tables are now handled more gracefully, but the behavior will remain different. Pandoc should probably raise warning in these cases. This requires additional changes in the gridtables library.

It would be nice to specify column widths explicitly, but we'll have to find a different way than the above. E.g., you could try to use a Lua filter that takes column widths from the attributes of a table-wrapping div.
