### ISSUE TITLE
Grid table to pdf: Text in cells spanning across multiple columns does not align correctly

### ISSUE THREAD

**Issue by gnpan** [jgm/pandoc#8218]
pandoc 2.19, macOS 12.5

In the following grid table the bottom 'abc' (r2) aligns as expected under the top one (r1) when converted to html, but not when converted to pdf:

```
+-----+-----+-----+-----+
|     | c1  | c2  | c3  |
+=====+:===:+:===:+:===:+
| r1  |     | abc |     |
+-----+-----+-----+-----+
| r2  | abc             |
+-----+-----+-----+-----+
```
pdf and html outputs attached. 

[latex_output.pdf](https://github.com/jgm/pandoc/files/9276901/latex_output.pdf)
[html_output.pdf](https://github.com/jgm/pandoc/files/9276902/html_output.pdf)
[grid_table.md](https://github.com/jgm/pandoc/files/9276905/grid_table.md)

**Comment by tarleb** [comment]
The row with the column-spanning cell looks like this in LaTeX:

``` latex
  r2 &
  \multicolumn{3}{>{\centering\arraybackslash}p{0.2500\columnwidth - 1\tabcolsep}@{}}{abc}\\
```

I can get the text to align by changing `- \1tabcolsep` to `+ 2.5\tabcolsep`. But I don't see why our calculations would be incorrect, or which formula would give the desired result.

**Comment by jgm** [comment]
I think this is the solution:

```
\multicolumn{3}{>{\centering\arraybackslash}p{((\columnwidth -
    6\tabcolsep) * \real{0.2500}) + 4\tabcolsep}@{}}{abc} \\
```

Let CS be the total space available for content, disregarding internal intercell spacing: that's `\columnwidth - 6\tapcolsep`, and that's the basis of the calculations in the heading.

When we have the large cell, we need to compute its width relative to CS, and then *add in* the four `\tabcolsep`s that are now available as extra content space. It won't work to try to subtract those `\tabcolsep`s before multiplying.

**Comment by jgm** [comment]
So the formula should be:

```
((\columnwidth - NUMCOLS\tabcolsep) * \real{COLWIDTHFRACTION}) +
  (2 * (COLSPAN - 1))\tabcolsep)
```
Note that when COLSPAN = 1, the last term is 0 as desired.

**Comment by tarleb** [comment]
AAAAAH yes 🤦 makes perfect sense now.

I'll fix it.

**Comment by tarleb** [comment]
I checked by using a `\cellcolor{blue!30}` prefix before the col definition (with `\usepackage[table]{xcolor}`) and got this:

![latex-multicol](https://user-images.githubusercontent.com/507994/183306142-05d8b4e8-c5ab-4d2e-9e42-008772a080b9.png)

Is this expected?

**Comment by jgm** [comment]
Looks good to me!

**Comment by tarleb** [comment]
I was irritated by the overflow to the right, but it makes sense of course (it's the `\tabcolsep`).

**Comment by jgm** [comment]
Oh, I didn't even notice the overflow!
Yes, that does look a bit odd.
Isn't there an issue out there already about this sort of thing (someone using xcolor with tables and getting funny results because of the way we do them?)

**Comment by jgm** [comment]
Here it is: https://github.com/jgm/pandoc/issues/7421
