### ISSUE TITLE
markdown -> LaTeX / PDF, use pygmentex instead of listing

### ISSUE THREAD

**Issue by evan0greenup** [jgm/pandoc#8221]
When converting markdown files with code blocks or inline code terms into PDF or LaTeX files, the current code highlight is not beautiful or expressive.

For use who install latexextra, it would be good to use `pygmentex` to make the code block very nice.

https://ctan.org/pkg/pygmentex?lang=en

**Comment by jgm** [comment]
We try not to depend on things in latexextra.

**Comment by jgm** [comment]
Nor would we want to depend on pygments being installed.

Note: the highlighting built into pandoc is configurable.  See `--highlight-style` in the manual. You can even write your own styles.
