### ISSUE TITLE
Uppercase alphabetic list markers not recognized

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc#8227]
It seems that uppercase letters aren't currently recognized as list markers, but the manual states that they should.

For this example:

```
This is converted to an ordered list:

a. first
b. second

This isn't:

A. first
B. second

But, I think it should...
```

I'm getting:

```html
<p>This is converted to an ordered list:</p>
<ol type="a">
<li>first</li>
<li>second</li>
</ol>
<p>This isnÔÇÖt:</p>
<p>A. first B. second</p>
<p>But, I think it shouldÔÇª</p>
```

**Comment by jgm** [comment]
This is as documented.  See the manual https://pandoc.org/MANUAL.html#extension-fancy_lists

> They must be separated from the text that follows by at least one space, and, if the list marker is a capital letter with a period, by at least two spaces.[1](https://pandoc.org/MANUAL.html#fn1)

and read footnote 1 for the motivation.
