### ISSUE TITLE
pandoc.path.make_relative sometimes incorrect when unsafe=true

### ISSUE THREAD

**Issue by dubiousjim** [jgm/pandoc#8228]
**Explain the problem.**

Inside a Lua filter:
```
local rel = pandoc.path.make_relative
print(rel("a/d", "a/b/c"), rel("a/d", "a/b/c", true))
```

prints:
> a/d    ../d/..

The first result is what I expected. The second result seems to be garbage? Expected `../../d`.

**Pandoc version?**
Mac OS, pandoc 2.19, custom cabal build with -flua53

**Comment by jgm** [comment]
I believe this has to do with hslua-module-path; @tarleb can comment further.

**Comment by tarleb** [comment]
@dubiousjim could you re-raise the issue at <https://github.com/hslua/hslua/issues/new>? GitHub doesn't allow to transfer issues across different projects.
