### ISSUE TITLE
Can "ofd" conversion be supported ?

### ISSUE THREAD

**Issue by xzxiaoshan** [jgm/pandoc#8229]
Ofd is a PDF like document format. Can you support the conversion of ofd file format.

**Comment by jgm** [comment]
If it is PDF-like, then it's out of scope.
Pandoc doesn't convert from PDF (which is more of a layout format), but only from structured document formats.

**Comment by tarleb** [comment]
A quick search didn't give any information about the format. Can you link to a description and definition?
