### ISSUE TITLE
Equivalent Pandoc Try and CLI commands yield different results and break colorlinks

### ISSUE THREAD

**Issue by and-viceversa** [jgm/pandoc#8230]
**Explain the problem.**
Pandoc Markdown -> PDF does not seem to honor `colorlinks urlcolor or linkcolor` as YAML header or `-V` CLI options.
```
brew install pandoc
brew install librsvg python homebrew/cask/basictex
pandoc -s in_file.md -o out.pdf
```
This yields properly functioning PDF URLs, but the coloration does not work.

The markdown (test copy from a popular repo):
```
---
author: John Doe
date: January 1, 2020
title: Sample Markdown to LaTeX+PDF with Pandoc
geometry:
- margin=1in
colorlinks: True
urlcolor: Blue
linkcolor: Blue
hidelinks: False
---

# ATT&CK® STIX Data

[MITRE ATT&CK](https://attack.mitre.org) is a globally-accessible knowledge base of adversary tactics and techniques based on real-world observations. The ATT&CK knowledge base is used as a foundation for the development of specific threat models and methodologies in the private sector, in government, and in the cybersecurity product and service community.

This repository contains the MITRE ATT&CK dataset represented in STIX 2.1 JSON collections. If you are looking for STIX 2.0 JSON representing ATT&CK, please see our [MITRE/CTI](https://github.com/mitre/cti) GitHub repository which contains the same dataset but in STIX 2.0 and without the collections features provided on this repository.
```

It's interesting, because the LATEX output from [Pandoc Try](https://pandoc.org/try/) and it's equivalent CLI output are different.

The Pandoc Try output for `pandoc --standalone --from gfm --to latex` _does not include_ the `\hypersetup{ ... hidelinks` flag.

The same command `pandoc --standalone --from gfm --to latex` on the CLI _does_ include `hidelinks`.

If I do like:
```
pandoc --standalone --from gfm --to latex in_file.md -o out.tex
# manual delete hidelinks from out.tex #
pdflatex out.tex
```

Then the PDF links color properly.

Apologies if this is clear to regular users - it seems issue worthy because equivalent Pandoc Try and CLI commands yield different results.

**Pandoc version?**
macOS Monterey 12.5 Intel
```
pandoc -v
pandoc 2.19
Compiled with pandoc-types 1.22.2, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /Users/dev/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by tarleb** [comment]
Thanks for the report. The issue has been raised before in #8226 and is already fixed in the development version.
