### ISSUE TITLE
No sensible way to bolden or color URLs

### ISSUE THREAD

**Issue by ctjlewis** [jgm/pandoc#8234]
It's impossible to configure this tool to build a markdown file with `urlcolor`, `linkcolor`, using `xcolor`, using `hyperref` and every other magic spell that exists to do something so simple.

At the very least, please build markdown files with sensible defaults. There are exactly 0 situations where someone wants their interactive hyperlink to look the exact same as every other piece of text, and this is a concept that goes back several decades.

**Comment by ctjlewis** [comment]
After trying about 6 different ways, I am generalizing this issue further as there is genuinely no sensible way to achieve this. I had a config using `hyperref` that worked a while ago, but now it does not.

After a certain point, you just have to accept the configuration standard is broken, and if a reasonable person cannot get a link to change colors after 10 tries, it's an indication that this is not generally accessible.

**Comment by ctjlewis** [comment]
oh nice it's actually just broken, very cool

https://github.com/jgm/pandoc/issues/8226

**Comment by ctjlewis** [comment]
just a broken release - closing in stern disappointment, extremely frustrating experience as a user to spend 45 minutes unsure what you're doing wrong

https://github.com/jgm/pandoc/issues/8226

**Comment by jgm** [comment]
I'm sorry about your frustrating experience. Next time, try a quick search of closed issues; you would have found #8226 right away.  We're going to try to put out a new release very soon.
