### ISSUE TITLE
<br> inserted when source contains multiple space at end of line

### ISSUE THREAD

**Issue by Jc-L** [jgm/pandoc#8238]
When converting from markdown to html, `pandoc` inserts an unexpected `<br>` tag when source line contains multiple trailing whitespaces.

Example of source file with `$` indicating end of lines to show trailing whitespaces:
```
$ cat -e  x.md
Some text$
$
> line1   with no space at the end$
> line2 with one space at the end $
> line3 with two space at the end  $
> line4 $
```

The output from `pandoc -o x.html x.md` is
```
<p>Some text</p>
<blockquote>
<p>line1 with no space at the end line2 with one space at the end line3
with two space at the end<br />
line4</p>
</blockquote>
```
The `<br />` tag should be present consistently.

Pandoc version 2.19.1 running on Windows 10.

**Pandoc version?**
What version of pandoc are you using, on what OS?

**Comment by tarleb** [comment]
Adding two trailing spaces is the default and most portable way to get a hard line break in Markdown.

If you dislike this kind of thing then maybe checkout [djot](https://djot.net/).
