### ISSUE TITLE
--embed-resources producing invalid data URI

### ISSUE THREAD

**Issue by soratobukuroneko** [jgm/pandoc#8239]
**Explain the problem.**
I have a SVG file that seems to be wrongly encoded with --embed-resources

`pandoc --from markdown --embed-resources --standalone test.md -o test.html`

```markdown
![test](input-example.abnf.svg)
```
[input-example.abnf.svg](https://github.com/jgm/pandoc/files/9390127/input-example.abnf.svg.txt)

output: [test.html](https://github.com/jgm/pandoc/files/9390098/test.html.txt)

**Pandoc version?**
pandoc 2.19.1
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4

Gentoo Linux

**Comment by jgm** [comment]
Possibly relevant changelog item:

```
  * Use base64 package instead of base64-bytestring. It is supposed to be
    faster and more standards-compliant.
```
We need to look into this further, thank you for reporting.  Have you tried with pandoc 2.19?

**Comment by jgm** [comment]
Follow-up:  can you explain why you think it is invalid?  When I open test.html with my browser, the images look correct.

**Comment by jgm** [comment]
Oh, interesting.  It renders fine in Safari, but not in Firefox or Chrome.
Chrome console says: net::ERR_INVALID_URL

According to base64.guru, the issue seems to be the `-` characters before newlines.

**Comment by jgm** [comment]
The problem is that I used the functions that generate base64url encoding, which is slightly different from standard base64.  I will revert this.

**Comment by soratobukuroneko** [comment]
I downgraded to 2.19. But with that version there is still an issue with the PDF output not showing that SVG.

**Comment by jgm** [comment]
The PDF issue is something else.  Probably the issue is that you don't have the software pandoc uses to convert svg to png for use in LaTeX.  You should see a warning message about this.

**Comment by soratobukuroneko** [comment]
Is that librsvg? I have it. I don't see any warning, only an info:
`[INFO] Loaded input-example.abnf.svg from input-example.abnf.svg`

**Comment by jgm** [comment]
I'm not sure.  Your document contains
```
\includegraphics{/tmp/.private/andrea/tex2pdf.-9691cc0a34f4a017/1115fb41c0096e58308c34b6368bf625d108f17b.pdf}
```
which suggests that pandoc has converted the svg to pdf and is including that.  If you can link to a full zip with everything needed for the conversion, I could try it out.

**Comment by soratobukuroneko** [comment]
Mea culpa. I must have done something wrong at first try, because the graphic is indeed included now
