### ISSUE TITLE
LaTeX reader: gobble parenthesized argument after toprule, midrule, bottomrule

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#8242]
To see the issue, `pandoc test/tables.latex -t markdown`.

Result (e.g.)
```

Simple table indented two spaces:

       () Right Left    Center  Default
  ------------- ------ -------- ---------
    () () Right Left    Center  Default
             () 12        12    12
            123 123      123    123
              1 1         1     1
             ()                 
```

**Comment by fabnicol** [comment]
FYI, this issue affects almost all tabular displays from LaTeX to most formats and so should be rated as severe.
My tests show that it appeared in between version 2.17.1.1 and 2.18.

**Comment by jgm** [comment]
It only affects uses of `\midrule` etc. that are followed by parenthesized arguments.
I don't know if these are common in the wild.
But pandoc started producing them in the version range you mention, so this definitely affects pandoc's parsing of its own LaTeX output.

**Comment by aubertc** [comment]
This bug occurs if yo u do things like 

```
\renewcommand{\toprule}{\specialrule{.5pt}{0pt}{0pt}(l{-.6em}r{-.6em})\rowcolor{gray!25}}
```

to resize / redefine the toprule.

**Comment by aubertc** [comment]
BTW, the solution to the problem I have mentioned, [as indicated here](https://github.com/jgm/pandoc/issues/8223#issuecomment-1212387294), is to use instead

```
\renewcommand{\toprule}[2]{\specialrule{.5pt}{0pt}{0pt}(l{-.6em}r{-.6em})\rowcolor{gray!25}} % We tweak the line under the header and color the cells in the header.
```
