### ISSUE TITLE
Feature Request: Simplify Output of Conversion to LaTeX

### ISSUE THREAD

**Issue by ocelotStride** [jgm/pandoc#8249]
Is it possible to add a command which outputs LaTeX without the additional "flare"

For example, I don't want `\tightlist`, I don't want `\def\labelenumi{\arabic{enumi}.}`, I don't want `\hypertarget{modelling-data}{%` and it's matching `\label{modelling-data}}`.

Is it possible to just output very simple latex with simple sections, subsection, itemise, and enumerate sections?

I've tried finding a way to do this but I'm starting to think there isn't. I even created my own custom.latex template and these options still show up

**Comment by jgm** [comment]
Changes in the template wouldn't affect this; the writer would have to be changed.
I'm sorry, it would add too much complexity (and therefore too many bugs) to the code to add configuration options for simpler output.
I'd suggest creating a custom Lua writer to produce the simple LaTeX you desire.
https://pandoc.org/custom-writers.html
