### ISSUE TITLE
Link Attrs: remove empty HTML classes as meaningless

### ISSUE THREAD

**Issue by gwern** [jgm/pandoc#8251]
Pandoc currently will generate link elements which have empty HTML classes (`class=""`). This is apparently technically valid HTML, but is undesirable: they have no usecase, are very surprising, cannot be read from Markdown or HTML when written as Markdown, can only be read as Markdown but not HTML when written as HTML, and yield stray garbage text when roundtripped due to the inconsistency. Empty classes should be removed by Pandoc.

---

While debugging our shiny new JavaScript dynamic lazy [transclusion feature](https://github.com/gwern/gwern.net/blob/master/js/transclude.js) (which speeds up site compiles dramatically by letting annotations be lazy-loads, allows for cross-page transclusions, and enable 'virtual pages' constructed out of other pages which would enable stuff like CYOA text games), I noted odd `{.}` text being appended to the end of links.

This turned out to be unrelated, and revealed by a quick debugging hack: while debugging the necessary link classes for transclusions, I had edited the `Link` element's Attr to read `("",[""],[])` instead of `nullAttr` or `("",[],[])`—not *quite* the same. The result was that links were then being compiled to Markdown as `[foo](https://bar.com){.}`, except then when parsed, `{.}` is *not* valid Pandoc Markdown for specifying a class (and nothing in the [link attribute docs](https://pandoc.org/MANUAL.html#extension-link_attributes) suggests it might be, as all examples are longer than just '.'), and gets treated as simply some mysteriously-appended plain text{.}:

~~~{.Bash}
 $ echo '[foo](https://bar.com){.}' | pandoc -f markdown -w html
<p><a href="https://bar.com">foo</a>{.}</p>
~~~

Pandoc is in general inconsistent about how to handle a "" class:

~~~{.Bash}
$ echo '<a href="https://example.com" class="">foo</a>' | pandoc -f html -w html
<a href="https://example.com">foo</a>
$ echo '<a href="https://example.com" class="">foo</a>' | pandoc -f markdown -w html
<p><a href="https://example.com" class="">foo</a></p>
$ echo '<a href="https://example.com" class="">foo</a>' | pandoc -f markdown -w markdown
`<a href="https://example.com" class="">`{=html}foo`</a>`{=html}
~~~

It will happily create elements with redundant multiple ""s:

~~~{.Haskell}
ghci> Link ("",["", "", ""],[]) [Str "foo"] ("https://example.com","")
Link ("",["","",""],[]) [Str "foo"] ("https://example.com","")
~~~

which is if anything even weirder (they, effectively, get concatenated by the default HTML space-separated class syntax, but the first class gets 'used up' and so _n_ empty classes turn into an empty string of length _n_−1...?):

~~~{.Bash}
$ echo 'Link ("",["","",""],[]) [Str "foo"] ("https://example.com","")' | pandoc -f native -w html
<a href="https://example.com" class="  ">foo</a>
~~~

Oh, and the non-empty elements and their order matters too:

~~~{.Bash}
$ echo 'Link ("",["","foo",""],[]) [Str "foo"] ("https://example.com","")' | pandoc -f native -w html
<a href="https://example.com" class=" foo ">foo</a>
$ echo 'Link ("",["","foo","","bar",""],[]) [Str "foo"] ("https://example.com","")' | pandoc -f native -w html
<a href="https://example.com" class=" foo  bar ">foo</a>
~~~

Bad.

---

To my surprise, an empty `class` or `class=""` is, [while debated](https://stackoverflow.com/questions/30748847/is-an-empty-class-attribute-valid-html), apparently legal HTML. I expect this would be a surprise to other Pandoc API users too, that passing in "" classes does anything.

However, no one in the discussion or links provides a valid usecase where one wants or needs such a confusing class, and I can't think of any—even the simplest use as a boolean or toggle would be a terrible idea because as soon as anyone or anything changes any class, it's now no longer a simple boolean (it's at least a tri-state toggle then: truly null or no class, an empty class, or a non-empty class; possibly quad-state or higher, depending on whether userland can distinguish `class` from `class=""`, as it presumably can just by inspecting the string form of the DOM, if nothing else).

So, I think this is another technically-legal-but-highly-undesirable HTML edge case which should be removed. (I also would suggest that possibly other formats, or the AST in general, should forbid empty classes in Attrs, although I'm not familiar enough with the other formats to say what might happen there. Maybe they already handle this in some way.)

**Comment by jgm** [comment]
Can you be more concise about the nature of the problem?

Is it a reader or writer issue, and with which format?

Can you give a simple example of the output you get for a given input and the output you would expect?

**Comment by gwern** [comment]
"Pandoc should remove the empty HTML classes it generates as they are meaningless and bad."

It is a writer issue (unless you decide it's actually a good thing, in which case it flips to a reader issue because Pandoc is emitting classes which it cannot then read). It is HTML specifically, but I would not be too surprised if there were other output formats where Pandoc would emit empty classes in attributes and these are either outright invalid or undesirable the same way the HTML empty classes are.

I gave several examples of bad outputs above. Pandoc should not be emitting classes like `class=""`, and it *definitely* should not be emitting classes like `class="   "` or `class=" foo   bar "` (note the multiple spaces). In all these cases, there should be no `class` at all, or in the foo/bar class examples, it should just be `class="bar foo"`.

**Comment by jgm** [comment]
Still not sure which case is supposed to be a problem.

```
$ echo '<a href="https://example.com" class="">foo</a>' | pandoc -f markdown -w html
<p><a href="https://example.com" class="">foo</a></p>
```
Pandoc just passes through raw HTML from markdown without modifying it, so this is desired behavior.

```
$ echo '<a href="https://example.com" class="">foo</a>' | pandoc -f markdown -w markdown
`<a href="https://example.com" class="">`{=html}foo`</a>`{=html}
```
Same thing here.
```
ghci> Link ("",["", "", ""],[]) [Str "foo"] ("https://example.com","")
Link ("",["","",""],[]) [Str "foo"] ("https://example.com","")
```
True, it's a shortcoming of the types that you can do this; ideally it would be excluded at the type level.  But how, in practice, is this causing a problem for you?  Are any actual pandoc readers creating empty classes in the AST?

**Comment by gwern** [comment]
> True, it's a shortcoming of the types that you can do this; ideally it would be excluded at the type level. But how, in practice, is this causing a problem for you?

I never said it was causing major problems, but it is still bad that Pandoc will happily generate, given input which is not obviously wrong, ASTs which are meaningless and it cannot read and which generate garbage text which has no apparent connection to its root cause way back at the AST level, confusing even people who have used the AST quite extensively & seen many odd interactions or roundtrips. And yes, it did cause me a problem; which is how I came to discover it in the first place, and I made a note that since this problem wasted my time in debugging and had no conceivable advantage or purpose and is a bad thing to do, that Pandoc should probably not do it and should get rid of this edge case, and I should take the time to write it up as a bug report, since it would be so easy to fix; and here we are. So, since it is a shortcoming that Pandoc will do this, whether at the type or value level, I suggest it be fixed.

**Comment by jgm** [comment]
>  Pandoc will happily generate, given input which is not obviously wrong, ASTs which are meaningless 

You haven't given a single example yet of an input (besides pandoc's own native of course) that generates this weird AST.  Does one of pandoc's readers generate it? If so, that could be a legitimate bug.  If it's only generable by specifying the AST directly, then this should be closed.  Sure, in an ideal world we'd have used a type for nonempty texts, but changing that now is not worth the effort and the pain it would cause in the whole ecosystem.

**Comment by gwern** [comment]
I don't see why it should be closed if one can 'only' generate a bad AST. String datatypes are notorious for empty string bugs and edge cases, and this is just another case, and shouldn't require an actual in-the-wild-right-this-second usecase any more than crashing on a 0::Int should require an example before it is fixed. Obviously it is a shortcoming and someone (besides me) has or is going to run into it at some point, unnecessarily; it is just too easy when string munging stuff to wind up with a whitespace-filled or null string at some point when a search-and-replace fails or a value is dropped or something. Nor will you necessarily ever hear of it when they do - the 1% rule applies to bug reports more than anything else, and they may simply debug & fix it directly, or hack around it. (As indeed I did before I decided to be a good doobie to spend time trying to make Pandoc more robust for future users.) But fixing edge-cases proactively when you find them and practicing defensive programming is how you get to reliable robust software, and I see no need to write apologetics for that.

And I never suggested changing the type, so why bring that up? I am well-aware that none of the AST types can be changed at this point. The type doesn't need to be changed, empty classes just need to be filtered out with a `filter (not . null)` call or however you like. This is zero pain and effort for the ecosystem (or, to the extent there was any, it would presumably give you your example), and would remove an edge-case.

**Comment by jgm** [comment]
>  I never suggested changing the type, so why bring that up?

```
ghci> Link ("",["", "", ""],[]) [Str "foo"] ("https://example.com","")
Link ("",["","",""],[]) [Str "foo"] ("https://example.com","")
```

The only way to prevent this ghci from giving this result is to change the type.

Yes, we could put a filter somewhere.  But where?  Are we going to add this code to every place in every writer where the attributes are used?  That's a ton of changes, and it's all for a pretty minor benefit, since the only way to generate the bad AST is to produce it programatically yourself.  One could add an AST traversal between the readers and writers, but there's a performance cost to that.  Not worth it, I'd say.  
\

**Comment by jgm** [comment]
PS. Feel free to submit a PR adding this filter to the place in the HTML writer where you think it should go.

**Comment by myfonj** [comment]
Side note

> ([…] depending on whether userland can distinguish `class` from `class=""`, as it presumably can just by inspecting the string form of the DOM, if nothing else)

No, conforming agents should not be able to tell `<el class>` and `<el class="">` apart in the resulting DOM, since:

> Empty attribute syntax
> [..] **The value is implicitly the empty string.**

-- https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
