### ISSUE TITLE
Unexpected ipynb output with footnotes

### ISSUE THREAD

**Issue by huangjunwen** [jgm/pandoc#8253]
**Explain the problem.**
I'm converting markdown to ipynb, here is a simplified example:

```shell
$ cat no-code.md
How to import a python package [^doc]

[^doc]: https://www.python.org/doc/

Text after footnote
$
$ pandoc -t ipynb no-code.md 
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "How to import a python package [1]\n",
    "\n",
    "Text after footnote\n",
    "\n",
    "[1] https://www.python.org/doc/"
   ],
   "id": "dd1d4b36-a08d-4b8a-a6eb-ffd85e2ddb84"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
```
This is correct that the footnote is placed at the end, but the following (with code cell):
```shell
$ cat has-code.md
How to import a python package [^doc]

[^doc]: https://www.python.org/doc/

~~~{.python .code}
import sys
~~~

Text after footnote
$
$ pandoc -t ipynb has-code.md 
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "How to import a python package [1]\n",
    "\n",
    "[1] https://www.python.org/doc/"
   ],
   "id": "e0546c3d-a11d-4c5d-9b23-6b4f5157cf31"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys"
   ],
   "id": "dfcdc813-a9e8-4372-9d0c-bec87b530cb5"
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Text after footnote"
   ],
   "id": "00888f2d-533a-4ed1-91b1-6d1a1e3216da"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
```
The footnote is placed before the code cell

**Pandoc version?**
pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4

OS: unbuntu 20.04

**Comment by ickc** [comment]
This is not a bug. The important point is where the footnote reference, not where the footnote is placed.

You can have some form of control using `--reference-location=block|section|document`.

Also note that your 2 examples are fundamentally very different as the first one is interpreted (correctly) as 1 single cell and the 2nd has 3 cells.

**Comment by huangjunwen** [comment]
Do you mean that since the two examples above are treated  different: as 1 section (or document) and 3 sections, and the footnote is placed at the end of the section where the footnote is referenced (both in the first section)?

**Comment by jgm** [comment]
The markdown document is divided into cells using the method described in the manual.
And then each cell is processed individually, so footnotes for the cell go at the end of the cell.
