### ISSUE TITLE
Support table footers in grid tables

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#8257]
This is a proposal for a non-standard extension to grid tables that would allow to add a footer. The approach would be to use a separator line containing `~` instead of `-` to mark the beginning of the table foot:

```
+------+-------+
| Item | Price |
+======+=======+
| Eggs | 5£    |
+------+-------+
| Spam | 3£    |
+~~~~~~+~~~~~~~+
| Sum  | 8£    |
+------+-------+
```

**Comment by jgm** [comment]
What about just using `=`?  If I recall correctly, we don't yet support multiple headers in a grid table, is that right?  If we did, there'd be some possibility of ambiguity, but it could perhaps be resolved as follows (table with subhead and foot, the foot is marked as such by the `==` row at the bottom):

```
+------+-------+
| Item | Price |
+======+=======+
| Eggs | 5£    |
+------+-------+
| Spam | 3£    |
+------+-------+
| Item | Price |
+======+=======+
| Ice  | 2£    |
+======+=======+
| Sum  | 9£    |
+======+=======+
```

**Comment by tarleb** [comment]
So a table foot would be marked by a `===` bottom separator, and would include all rows below the second-to-last such separator? That's definitely easier to identify visually,  `~` are very close to hyphens.

Another option could be to use a double row separator

```
+------+-------+
| Item | Price |
+======+=======+
| Eggs | 5£    |
+------+-------+
| Spam | 3£    |
+------+-------+
+------+-------+
| Sum  | 8£    |
+------+-------+
```

But that's a bit noisy when compared to

```
+------+-------+
| Item | Price |
+======+=======+
| Eggs | 5£    |
+------+-------+
| Spam | 3£    |
+======+=======+
| Sum  | 8£    |
+======+=======+
```

**Comment by jgm** [comment]
Not sure which of these I prefer.  The first "sets off" the footer nicely, but there's an ambiguity because it could be two consecutive tables. So probably the second is better. Both are better than the tildes, though.

**Comment by tarleb** [comment]
Tildes are out of the question then.

The advantage of two normal separators is that it's compatible with rst, which would interpret that syntax as an empty row. But we would also reserve that as separator for different body parts

```
+------+-------+
| Item | Price |
+======+=======+
| Eggs | 5£    |
+------+-------+
| Spam | 3£    |
+------+-------+
+------+-------+
| Item | Price |
+======+=======+
| Ice  | 2£    |
+======+=======+
| Sum  | 9£    |
+======+=======+
```

That way we could have intermediate heads with multiple rows.

**Comment by jgm** [comment]
Can you make explicit the structure you have in mind for the above table (e.g. with html)?

**Comment by tarleb** [comment]
I opened #8266 and added the expected HTML there.

I have implemented your syntax suggestion for table foot.

**Comment by jgm** [comment]
On table foots, two questions:

- Can you update MANUAL.txt and describe the syntax for table foots?
- What about the markdown writer?

**Comment by tarleb** [comment]
Generic writer support for grid tables is very much work in progress and not very far along yet, but I'm on it.

Somehow I managed to forget about the docs; will fix that promptly.
