### ISSUE TITLE
Strange behaviour while accessing images on local file system

### ISSUE THREAD

**Issue by dreamos82** [jgm/pandoc#8260]
I have the following scenario: 

- ProjectFolder/
    -  /Images/
        -  img.png
        -  img2.png
    -  Folder2
        -  File.md

Now in `Folder2\File.md` i have: 

```markdown
text
[My shiny image](/Images/img.png)
other text
[My shiny image 2](/Images/img2.png)
```

It has to be absolute because the files are stored on a github  repository and there the path is relative to the current directory.
 They are rendered as expected on github, but i'm aware that using pandoc the working dir is the main directory, not the file directory (and i'm compiling many markdown files when generating the single pdf) 

But it fails to open them when i use pandoc (because with pandoc the path should be relative to the ProjectFolder). I read about the --resource-path option of pandoc and it looked the solution to my issue: 

```
List of paths to search for images and other resources.
```

So i tried to use it with the following command: 

```
pandoc --toc --top-level-division=chapter -f markdown -t pdf README.md  ...othermarkdownfile....  pandoc.yaml -o notes.pdf --pdf-engine=pdflatex -N --resource-path=./
```

And i got the following error: 
```
pandoc: /Images/taskssequence.png: openBinaryFile: does not exist (No such file or directory)
```

Note that the images are 2, and i got the error only for one. But the most interesting thing is that both images are present in the final pdf. So i'm confused they should or shouldn't be present?. 

I think that using an absolute path in the markdown it is actually searching in the Root folder of my hard disk. But i wonder if there is a way to express an absolute path, forcing pandoc to consider the project directory as its root. 

**Pandoc version?**
2.9.2.1

**Comment by dreamos82** [comment]
Using `Unknown extension: rebase_relative_paths` i get the following error: 

```
Unknown extension: rebase_relative_paths
```

**Comment by jgm** [comment]
Your pandoc version may be too old.

**Comment by tarleb** [comment]
Closing in favor of #8272, which is essentially the same issue.
