### ISSUE TITLE
Allow resource-path to be specified in the YAML document header

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#8262]
I keep (symlinked) my bibliogrpahy file in my Pandoc data dir (I try to keep everything there). I would like to just write the file name when using `bibliography`. I cannot add `resource-path: .:/Users/ian/.local/share/pandoc/` to my YAML, or at least it seems not to be read:

```
▷ pandoc --citeproc --verbose 
---
title: Test
resource-path: '/Users/ian/.local/share/pandoc/'
bibliography: 'Core.json'
---

Some text [@siegel2015]. CTRL+D

File Core.json not found in resource path
```

Note: `/Users/ian/.local/share/pandoc/Core.json` is present and a valid file. I can of course specify from the command-line but I want my documents to be more self-contained (as they are not often run by pandoc directly). 

The "better" solution is to use `defaults` files, where there are ways to specify the data-dir and home folders and resource-path is valid. I understand that, but in some simple cases I just wanted the document with minimal dependencies on other files. I assume there is a technical reason for why resource-path cannot be specified in the document itself?

**Comment by jgm** [comment]
`resource-path` isn't metadata, it's a processing instructions.  Hence, it goes in defaults files, not metadata. 

(The reason `bibliography` can go in metadata, by the way, is that it is implemented as a metadata field. The `--bibliography` command line option just adds something to metadata.  This is a bit kludgy; it dates from the days when pandoc-citeproc was a JSON filter and thus had to get this information from metadata. Same for `csl`.)

**Comment by iandol** [comment]
OK, thanks for the explanation. I assume then being able to specify the resource-path in the YAML header is out-of-scope? If so I will close this. 

@jgm — out of interest is there a reason `csl` is searched for in the Pandoc data directory, but `bibliography` isn't? I would prefer it if Pandoc could look for files it uses (like the `bibliography` data) in the data directory as well as the working directory.

**Comment by iandol** [comment]
I suppose my brain inteprets `data` to include the data used to make the bibliography...

My general idea about the data directory is just to have some generic place where Pandoc can look when a file is missing that is required for a conversion. Put my JSON and CSL there and don't worry about having to use absolute paths to maximise portability...

**Comment by jgm** [comment]
Yes, I see why one might want this. I'm not sure.  You should search for an existing issue, though; I'm pretty sure there is one.

**Comment by iandol** [comment]
I searched for all open issues with `resource-path`:

https://github.com/jgm/pandoc/issues?q=is%3Aissue+is%3Aopen+resource-path 

The closest related item is this one:

https://github.com/jgm/pandoc/issues/5870

Which certainly would be one step forwards if it was implemented (as `resource-path` can be specified in a defaults file which could be specified in the document), but being able to specify `resource-path` directly would be one less step.

I also searched for `data-dir` and `bibliography` (searching for issues where data-dir would include the bibliography search path) but got no hits: https://github.com/jgm/pandoc/issues?q=is%3Aissue+is%3Aopen+data-dir+bibliography

**Comment by jgm** [comment]
I think I was thinking of
https://github.com/jgm/pandoc-citeproc/issues/150
which probably just got closed when pandoc-citeproc folded up.
You might open an issue in pandoc requesting this (searching for the bibliography in user data directory).
