### ISSUE TITLE
Conversion of umlauts does not work in Powershell-Core

### ISSUE THREAD

**Issue by philippseith** [jgm/pandoc#8265]
When invoked in pwsh  with `pandoc -f rtf -t plain .\Umlauts.rtf > .\Umlauts.txt`, pandox does not convert the umlauts correctly, even when the codepage is set with `chcp 437` to the default cmd codepage.
When invoked in cmd the file is converted correctly, even when the codepage is set to UTF8 with `chcp 65001`

### Input file:
[Umlauts_rename2rtf.txt](https://github.com/jgm/pandoc/files/9464011/Umlauts_rename2rtf.txt) (rename to Umlauts.rtf to reproduce the problem)

### Output files:
[Umlauts_Cmd.txt](https://github.com/jgm/pandoc/files/9464007/Umlauts_Cmd.txt)
[Umlauts_Pwsh.txt](https://github.com/jgm/pandoc/files/9464008/Umlauts_Pwsh.txt)

### Versions:
Pandoc: 2.19.2
PowerShell-Core: PowerShell 7.2.6 
OS:  Windows 10 21H2 (Build 19044.1889)

**Comment by jgm** [comment]
Try using the `-o Umlauts.txt` in pwsh instead of using the redirect `>`.  That way you can bypass the shell; pandoc will write the file directly.

I don't know enough about Windows to know why it might not work with shell redirection.  (You need to make sure the shell is using UTF-8.)

**Comment by philippseith** [comment]
With `-o` the output is correct.
Thank you!
