### ISSUE TITLE
Feature request: search for `python3` if `python` isn't there

### ISSUE THREAD

**Issue by cscheid** [jgm/pandoc#8268]
In macOS 12.3 and later, `python` is no longer available by default, which makes Python filters not work.

```
$ pandoc python-filter.qmd -f markdown --filter behead.py
Error running filter behead.py:
Could not find executable python

$ cat python-filter.qmd
---
title: Test Python Filter
---

## This is a test

## This should be em
```

I attempted to add "python3" to the /usr/bin/env line, to no avail:

```
$ cat behead.py
#!/usr/bin/env python3

"""
Pandoc filter to convert all level 2+ headings to paragraphs with
emphasized text.
"""

from pandocfilters import toJSONFilter, Emph, Para

def behead(key, value, format, meta):
  if key == 'Header' and value[0] >= 2:
    return Para([Emph(value[2])])

if __name__ == "__main__":
  toJSONFilter(behead)
```

Python3, on the other hand, _is_ available:

```
$ which python
python not found
$ file /usr/bin/python3
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64
- Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e
- Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

It'd be great to not to have python2 installed via homebrew, pyenv, etc.

**Comment by tarleb** [comment]
The cleanest solution would probably be to respect the filter's shebang line.

**Comment by tarleb** [comment]
On the other hand, that would require us to parse shell syntax, which should probably be avoided.

Workaround: users can make the filter script executable with `chmod +x behead.py`, in which case the `#!` line should work as expected.

**Comment by cscheid** [comment]
That workaround is good enough for us to go on. Thanks!

**Comment by jgm** [comment]
I think this is the cleanest solution anyway; your script, and not pandoc, should determine which python executable to use. So I'm inclined not to act further on this.

**Comment by cscheid** [comment]
I missed that on our test suite, I apologize. We had that script there with a shebang but bad permissions.

**Comment by tarleb** [comment]
@arbipher What output do you get for `ls -l filter/dot2tex-filter.py`? Note that the file must be executable; see above.
