### ISSUE TITLE
JATS Reader not reading URL from references

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#8270]
### REPO STEPS

Using pandoc 2.19.2 convert [has-url.xml.txt](https://github.com/jgm/pandoc/files/9472880/has-url.xml.txt) to markdown:
```
pandoc has-url.xml.txt -f jats -s -t markdown -o got-no-url.md
```

### GOT
[got-no-url.md](https://github.com/jgm/pandoc/files/9472887/got-no-url.md) which does not contain a url in the reference found in the XML.

### EXPECTED

Something like [has-url.md](https://github.com/jgm/pandoc/files/9472901/has-url.md) which contain the url. This markdown was generated by pandoc from the BibTex provided by Wikipedia:
```
@misc{ enwiki:1098461067,
  author = "{Wikipedia contributors}",                                      
  title = "Pandoc --- {Wikipedia}{,} The Free Encyclopedia",                
  year = "2022",
  url = "https://en.wikipedia.org/w/index.php?title=Pandoc&oldid=1098461067",  
  note = "[Online; accessed 1-September-2022]"
}
```
The has-url.xml.txt was also generated by pandoc from this BibTex.

Also note that something funky is happening with the author field. The `{}` around the author in the BibTex is getting converted into a literal string author name and then the JATS reader seems to not handle this. But I'm not affected by the author issue, just the URL issue. So it's only the URL issue which is causing an issue in my work flow.

**Comment by jgm** [comment]
See line 429ff in src/Text/Pandoc/Readers/JATS.hs.

We have to handle each bibliographic field manually, since JATS treats them differently. 
It should be straightforward to add url.
