### ISSUE TITLE
Write meta properties in lowercase when converting html to markdown

### ISSUE THREAD

**Issue by tbswork1** [jgm/pandoc#8274]
**Describe your proposed improvement and the problem it solves.**
Some software like mkdocs only recognizes lowercase property like `description`. But pandoc writes as `Description`. 

**Describe alternatives you've considered.**
batch processing the generated md with script but time-consuming.

**Comment by jgm** [comment]
One easier and faster alternative could be a Lua filter.

**Comment by tarleb** [comment]
``` lua
function Meta (meta)
  for k, v in pairs(meta) do
    meta[k] = nil
    meta[text.lower(k)] = v
  end
  return meta
end
```

Write it to a file, e.g., `lowercase-keys.lua`, and pass it to pandoc with `--lua-filter=lowercase-keys.lua`.

**Comment by tbswork1** [comment]
@tarleb 
the above code causes error `attempt to index a nil value (global 'text')` and is it safe to add new values in a table iteration?

**Comment by tarleb** [comment]
You're right, that's undefined behavior. Better:

```lua
function Meta (meta)
  local newmeta = {}
  for k, v in pairs(meta) do
    newmeta[pandoc.text.lower(k)] = v
  end
  return newmeta
end
```

**Comment by tbswork1** [comment]
Thanks!
