### ISSUE TITLE
`. . .` has an impact on non-slide HTML too when header is present

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#8281]
See this example: 
```powershell
> pandoc -t html
# test

test

. . .

test
^Z
<h1 id="test">test</h1>
<p>test</p>
<div class="incremental">
<p>test</p>
</div>
```

The `. . .` is converted to a `div` like with Slides. 

If no header, then it is shown in output. 
````powershell
pandoc -t html
test

. . .

test
^Z
<p>test</p>
<p>. . .</p>
<p>test</p>
````

It does not seem like something expected. If someone wants to add `. . .` in text, it would not show in HTML. 

This also causes confusion in context like https://github.com/quarto-dev/quarto-cli/issues/2302 where users are writing Revealjs slides, generating HTML without `. . .` but not seeing the hidden structure, and trying to convert to PDF but seeing `. . .` . In that case, it would break the usage from the users which benefit from current behavior. 

Pause should not be used outside of slides output maybe and adding a small Lua filter can help with that: 
````lua
Para = function(e)
  if (not FORMAT == "revealjs") or not FORMAT == "beamer" or not FORMAT == "pptx")) then
    if (e == pandoc.Para '. . .') then
      return {}
    end
  end
  return nil
end
````

Anyway, I thought it was worth reporting.

**Comment by tarleb** [comment]
It seems that this only happens if the section would be a title slide. A fix could be to add a `slideVariant == NoSlides` test to `if titleSlide` in line 840 of the HTML writer.

**Comment by jgm** [comment]
This happens because the test for `. . .` happens only when `blockToHtmlInner` matches a Div with "section" class.
See line 804 of the HTML writer.
When you don't add a section heading, there's no section div.

Not sure what the best fix is, but that's the issue I think.

**Comment by jgm** [comment]
I fixed it so it won't treat the `. . .` as a pause with `-t html`.
