### ISSUE TITLE
Unexpected behaviour when mixing `{-}` and an explicit header identifier

### ISSUE THREAD

**Issue by pcgaustad** [jgm/pandoc#8286]
Mixing `{-}` and explicit header identifiers leads to unexpected behaviour. No big deal, as one can always use `{.unnumbered}` instead. But it probably should be documented.

I have searched the issue tracker for similar issues and reproduces the issue on <https://pandoc.org/try>.

`test.md`:

```markdown
# Header 1 {#this-works .unnumbered}

# Header 2 {#this-doesnt-work} {-}

# Header 3 {-} {#this-also-doesnt-work}
```

```bash
$ pandoc test.md -t html
<h1 class="unnumbered" id="this-works">Header 1</h1>
<h1 class="unnumbered" id="header-2-this-doesnt-work">Header 2
{#this-doesnt-work}</h1>
<h1 id="this-also-doesnt-work">Header 3 {-}</h1>
```

This is also apparent in the native AST, i.e. not due to the HTML writer. I would expect headers 2 and 3 to be converted like header 1.

**Pandoc version?**

I'm running Pandoc in Ubuntu 22.04 (WSL).

```bash
$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /home/pga001/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by tarleb** [comment]
The `-` is part of the attribute specifier, and there can only be a single set of attributes per header. Try this instead:

``` markdown
# Header 4 {#this-works-too -}
```
