### ISSUE TITLE
Add `url` (and other fields) to bibtex output

### ISSUE THREAD

**Issue by reagle** [jgm/pandoc#8287]
I (sadly) learned that some ACM sigs are still using old school bibtex and bst style files. 

I know `url` wasn't include in [Patashnik][1], but it's been common since at least [2007][2]/[2008][3]. I *think* some of the major bsts can use it and `url` could be included in pandoc's bibtex output. **OR**, pandoc could follow some of the old ways of extending bibtex by making use of the `howpublished` and `note` fields:

    howpublished = "\url{https://www.nasa.gov/nh/pluto-the-other-red-planet}"
    note = "Accessed on 2022 Sep 09"

I expect this'll be a one off for me, so it'd be good to  have feedback from those who still use latex/bibtex and best know what's out there.

[1]: https://ctan.math.illinois.edu/biblio/bibtex/base/btxdoc.pdf
[2]: https://tug.org/pracjourn/2006-4/fenn/fenn.pdf
[3]: https://mirrors.rit.edu/CTAN/biblio/bibtex/contrib/doc/btxFAQ.pdf

**Comment by tarleb** [comment]
A good workaround might be to use `biblatex` output. If some fields cause issues, we could remove them with a Lua filter.

**Comment by reagle** [comment]
@tarleb, that's a possibility: the `date` field is the pain-point on using biblatex as bibtex. Bibtex needs year/month/day, other than that, I think most things are used or ignored.

**Comment by jgm** [comment]
`howpublished` might not be the best choice, though, in the case where a URL is provided in addition to regular journal identification. Or is `url` only used for web-only resources?

**Comment by reagle** [comment]
I was thinking of surveying the fields in the most popular BSTs or public bibtex databases, but that felt like too much work for a cruddy/ancient/ambiguous format I'd rather not bother with at all -- except for the need to make a conference submission. So I'm not sure.

Strict bibtex types also are as dated/limited as the fields, but I suspect most online resources are described as type `@misc` with a `url` field, whereas journals have type `@article` with  a `url`. (Biblatex has type `@online`.)
