### ISSUE TITLE
For Docbook table conversion with images to DOCX , use DOCX Field:INCLUDEPICTURE option on conversion

### ISSUE THREAD

**Issue by npiper** [jgm/pandoc#8289]
My source Docbook XML file Table row includes a URL reference to a country flag icon -a png 30x40px image.

When converting to DOCX no images are shown in the table though just the image metadata label. 

The original file is asciidoc that I have converted to Docbook using asciidoctor and produces the Docbook XML output below.

A way to correctly represent this would be to on the Docbook to DOCX conversion as an Insert Field command 'INCLUDEPICTURE {URL}' to show the picture in the table;

Source Docbook Row with URL Image reference:

```
<row>
<entry align="left" valign="top"><informalfigure>
<mediaobject>
<imageobject>
<imagedata fileref="https://flagcdn.com/w40/au.png" contentwidth="30px" contentdepth="40px"/>
</imageobject>
<textobject><phrase>Australia</phrase></textobject>
</mediaobject>
</informalfigure></entry>
<entry align="left" valign="top"><simpara>Australia</simpara></entry>
<entry align="left" valign="top"><simpara>22</simpara></entry>
</row>
<row>
```

Command:
```
pandoc --verbose --from docbook --to docx --extract-media=$(pwd)/DIST/images/extracts --output $(pwd)/DIST/docx/name.docx --reference-doc=$(pwd)/src/main/docx/DocbookStyles.docx $(pwd)/DIST/docbook/name.xml
```

Verbose output - shows it is ignoring these Docbook tags
```
INFO] Ignored element mediaobject
[INFO] Ignored element imageobject
[INFO] Ignored element imagedata
[INFO] Ignored element textobject
[INFO] Ignored element informalfigure
```

Screenshots attached of using the picture reference:

DOCX Word XML representation of the Flag icon once I've done the edit with the label usage:
```
<Relationship Id="rId10" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="https://flagcdn.com/40x30/ar.png" TargetMode="External"/>
```

**Describe your proposed improvement and the problem it solves.**

When in context of a Docbook `<row>` and an `<imageobject>` is identified with a URL reference, on a convert to DOCX use the Field feature and `INCLUDEPICTURE {URL}`

(Is this similar for converting Markdown with images inside a table row?)

Microsoft Reference:
https://support.microsoft.com/en-us/office/field-codes-includepicture-field-a3aac6dc-4e08-4d62-9aac-794279d02de9

**Describe alternatives you've considered.**

 I have tried various combinations of command line arguments to this but have not had desired result that reads the DOCBOOK image element.
 
 ```
 --extract-media=
 --reference-links
 --embed-resources
 --resource-path=...
 ```
 
 Screenshots:
 
<img width="564" alt="Screenshot 2022-09-10 at 10 37 55" src="https://user-images.githubusercontent.com/436314/189478707-ca554414-7e83-45e7-bbc0-7488244b428f.png">
<img width="375" alt="Screenshot 2022-09-10 at 10 38 45" src="https://user-images.githubusercontent.com/436314/189478715-ed9f7de5-7147-4b03-b6a0-aa125c614939.png">

**Comment by jgm** [comment]
Please say what pandoc version you're using.
I just tried your sample with the latest release and it works fine.

**Comment by npiper** [comment]
pandoc 2.11.2

**Comment by npiper** [comment]
Upgraded to 2.19 now and getting the correct result in output for this in DOCX and Markdown, thanks.

**Comment by tarleb** [comment]
Thanks for the update. Closing.
