### ISSUE TITLE
Bug with single line table conversion from `docx` to `markdown`

### ISSUE THREAD

**Issue by fsoedjede** [jgm/pandoc#8291]
## **Explain the problem.**

Hello,

I thnik I found an issue with table when there is only one line.

Using this docx file: [test.docx](https://github.com/jgm/pandoc/files/9542868/test.docx), I have this two cases

### Example 1

1. The command `pandoc --standalone --from=docx --to=markdown --output=test.md test.docx` produce:

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales
sapien lectus, pulvinar finibus ligula aliquam eget.

  -----------------------------------------------------------------------
  Lorem ipsum dolor sit amet,         Proin ut nibh diam. Orci varius
  consectetur adipiscing elit. Sed    natoque penatibus et magnis dis
  sodales sapien lectus, pulvinar     parturient montes, nascetur
  finibus ligula aliquam eget.        ridiculus mus. Integer volutpat
  Vivamus justo libero, pulvinar ut   eget est et accumsan. Aenean nisl
  urna eu, gravida rutrum nibh.       metus, blandit non rhoncus vitae,
                                      rutrum et justo. Duis viverra enim
                                      a est ornare pellentesque. Morbi
                                      efficitur elit ut consequat semper.
  ----------------------------------- -----------------------------------

  -----------------------------------------------------------------------

Cras leo felis, maximus ut nibh in, iaculis hendrerit tortor. Etiam
mauris metus, mattis eget leo ut, facilisis elementum odio.
```

2. The command `pandoc --from=markdown --to=latex --output=test.tex test.md` produce:

```latex
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales
sapien lectus, pulvinar finibus ligula aliquam eget.

\begin{longtable}[]{@{}l@{}}
\toprule()
\endhead
Lorem ipsum dolor sit amet, Proin ut nibh diam. Orci varius \\
consectetur adipiscing elit. Sed natoque penatibus et magnis dis \\
sodales sapien lectus, pulvinar parturient montes, nascetur \\
finibus ligula aliquam eget. ridiculus mus. Integer volutpat \\
Vivamus justo libero, pulvinar ut eget est et accumsan. Aenean nisl \\
urna eu, gravida rutrum nibh. metus, blandit non rhoncus vitae, \\
rutrum et justo. Duis viverra enim \\
a est ornare pellentesque. Morbi \\
efficitur elit ut consequat semper. \\
\bottomrule()
\end{longtable}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Cras leo felis, maximus ut nibh in, iaculis hendrerit tortor. Etiam
mauris metus, mattis eget leo ut, facilisis elementum odio.
```

3. **The problem**:

I have a rule appearing in the final PDF because of `\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}` which is not wat I would expect.

The result of the markdown output is not good. The first row must not be considered as the table head.

### Example 2

1. The command `pandoc --standalone --from=docx --to=markdown-multiline_tables --output=test.md test.docx` produce:

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales
sapien lectus, pulvinar finibus ligula aliquam eget.

+-----------------------------------+----------------------------------+
| Lorem ipsum dolor sit amet,       | Proin ut nibh diam. Orci varius  |
| consectetur adipiscing elit. Sed  | natoque penatibus et magnis dis  |
| sodales sapien lectus, pulvinar   | parturient montes, nascetur      |
| finibus ligula aliquam eget.      | ridiculus mus. Integer volutpat  |
| Vivamus justo libero, pulvinar ut | eget est et accumsan. Aenean     |
| urna eu, gravida rutrum nibh.     | nisl metus, blandit non rhoncus  |
|                                   | vitae, rutrum et justo. Duis     |
|                                   | viverra enim a est ornare        |
|                                   | pellentesque. Morbi efficitur    |
|                                   | elit ut consequat semper.        |
+===================================+==================================+
+-----------------------------------+----------------------------------+

Cras leo felis, maximus ut nibh in, iaculis hendrerit tortor. Etiam
mauris metus, mattis eget leo ut, facilisis elementum odio.
```

2. The command `pandoc --from=markdown --to=latex --output=test.tex test.md` produce:

```latex
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales
sapien lectus, pulvinar finibus ligula aliquam eget.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.5000}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.4861}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sodales
sapien lectus, pulvinar finibus ligula aliquam eget. Vivamus justo
libero, pulvinar ut urna eu, gravida rutrum nibh.
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Proin ut nibh diam. Orci varius natoque penatibus et magnis dis
parturient montes, nascetur ridiculus mus. Integer volutpat eget est et
accumsan. Aenean nisl metus, blandit non rhoncus vitae, rutrum et justo.
Duis viverra enim a est ornare pellentesque. Morbi efficitur elit ut
consequat semper.
\end{minipage} \\
\midrule()
\endhead
& \\
\bottomrule()
\end{longtable}

Cras leo felis, maximus ut nibh in, iaculis hendrerit tortor. Etiam
mauris metus, mattis eget leo ut, facilisis elementum odio.
```

3. **The problem**:

The single line is considered a the head, so I also have an unexpected rule at the end of the table.

### Question / Issue

It seems that pandoc always consider that the first line in docx table is the header.

Is it possible to have a table with only one line when converting `docx` to `markdown`?

How could I achieve that?

Thanks

## **Pandoc version?**

```
$ pandoc -v
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```

**Comment by tarleb** [comment]
Thanks for raising an issue @fsoedjede. Please upload the test.docx file, otherwise it is impossible to check what's happening here. You may have to rename the file to `test.zip` to get it past GitHub's content filter.

**Comment by fsoedjede** [comment]
@tarleb I've added the file in the description
Sorry, I forgot to add it

**Comment by jgm** [comment]
The way the docx reader identifies table rows is by looking for the w:firstRow attribute.  If this is set to 1 on the first row, it's treated as a header.  That's why the row is treated as a header row in your document.

I don't think there's an official ooxml markup for table headers; so we have to guess based on clues.  The guess will sometimes be wrong, but I'm not sure this is something that can be improved in general...

**Comment by fsoedjede** [comment]
@jgm thanks for the reply

If we consider "**Example 2**", I would not expect an empty line.
Maybe you could consider a special case when a table has only one line.

- When the table has only one line, the line is must be in the body and the head should be empty
- When the table has 2 or more lines, keep the current workflow

Can it be considered?

Thanks

**Comment by tarleb** [comment]
A header-only table does indeed not make much sense, but I'm not sure if we can rule out that someone may want exactly that.

In any case, we probably need something more sophisticated than what's currently implemented: one way to represent multiple header rows is to use multiple tables, as the spec requires unseparated tables to be merged. So a header-only table might actually be part of the following table.

**Comment by fsoedjede** [comment]
@tarleb I did not fully get your point. I will leave the discussion open until the more sophisticated way is implemented.

For now, I will try to implement the moving of the line from TableHead to TableBody with a Lua filter when converting from docx to markdown. With the structure of the native file it will not be too hard.

Thanks for your replies

**Comment by tarleb** [comment]
I believe the current behavior is *technically* correct, which is why I'm closing the issue here. But we might still be able to improve the docx writer, so I've opened #8299 to keep track of this.
