### ISSUE TITLE
Beamer section's title slide isn't generated with citeproc

### ISSUE THREAD

**Issue by serrabii** [jgm/pandoc#8294]
**Problem**
Using citeproc with beamer pdf output doesn't generate a slide for the section's title.

**Example**

- bug.md : 
```
---
title: Bug citeproc + beamer
bibliography: refs.bib
reference-section-title: References
slide-level: 2
theme: metropolis
---

# Bugged section

## slide 3

@Deng2019
```

- refs.bib : 
`@Article{Deng2019,}` 

- commands : 
`pandoc --citeproc -t beamer bug.md --pdf-engine=pdflatex -o bug.pdf` => No slide for section title
`pandoc -t beamer bug.md --pdf-engine=pdflatex -o bug.pdf` => Slide for section title is generated, but references are not generated.

**Pandoc version?**

pandoc 2.18
citeproc 0.7
macos

**Comment by jgm** [comment]
I suspect think what's happening is that the addition of the citations changes the "slide level," which defaults to the highest header level under which there is non-header content.

Try it with `--slide-level=2`.

**Comment by serrabii** [comment]
Many thanks for the quick response. Indeed using `--slide-level=2` fixed the issue. It seems that the `slide-level` in the metadata block is overriden by `--citeproc`.

**Comment by jgm** [comment]
> It seems that the slide-level in the metadata block is overriden by `--citeproc`.

No, it's not being overridden. You can't in general specify command-line options via things in the metadata block.
(You could use a defaults file, though.)  It's just that the addition of new content by `--citeproc` changes the calculation of the *default* slide level.
