### ISSUE TITLE
LaTeX \ref{} adds square brackets 2 times in markdown

### ISSUE THREAD

**Issue by Abhi-1U** [jgm/pandoc#8297]
**Explain the problem.**
When converting LaTeX cross-references like `\ref{fig:red}`  the equivalent markdown created has square brackets twice   
 `[\[ fig:red\]]`

a minimal example to reproduce 
```
pandoc -f latex -t markdown
LaTeX reference \ref{fig:red}

^Z
LaTeX reference [\[fig:red\]](#fig:red){reference-type="ref"
reference="fig:red"}
```
equivalent AST
```
pandoc -f latex -t native
LaTeX reference \ref{fig:red}

^Z
[ Para
    [ Str "LaTeX"
    , Space
    , Str "reference"
    , Space
    , Link
        ( ""
        , []
        , [ ( "reference-type" , "ref" )
          , ( "reference" , "fig:red" )
          ]
        )
        [ Str "[fig:red]" ]
        ( "#fig:red" , "" )
    ]
]
```
As we can see in the AST, `[ Str "[fig:red]" ]` is written as is with brackets. 
What could be the reason for such behaviour? is it a bug in the LaTeX reader or the way cross-references are handled in pandoc AST? 
Is there any existing extension or workaround which I could use to fix this?

**Pandoc version?**
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4

**Comment by jgm** [comment]
Not a bug.  This is just a link with the textual content
```
[fig:red]
```
The square brackets help you see that it's a stand in for a reference.
