### ISSUE TITLE
pandoc ignore different font converting docx to html

### ISSUE THREAD

**Issue by tbswork1** [jgm/pandoc#8301]
**Explain the problem.**
pandoc ignore different formatting (different font here) in word, either inline or in separate paragraph. For example, in the Word docx the `--output` is using different font, but the generated html uses same font for it as the surrounding text.
Optional argument `--output`
The command:
pandoc --extract-media=. --metadata title="User Manual" -s "man.docx" -c styles.css -t html --toc  -N -o manual.html

**Pandoc version?**
2.19

**Comment by tarleb** [comment]
This is expected behavior, CSS only works with HTML output. The docs hint at that by listing the option below "options affecting specific writers", but it is not clear which writers are meant in this case. I'll therefore keep this open as a potential documentation bug.

**Comment by jgm** [comment]
I already added something to the manual about how `--css` only affects HTML/EPUB.
So I think we can close this.

There isn't a way to extract font information from HTML and propagate it to docx.  Pandoc is only for converting structure, not details of formatting.

**Comment by tbswork1** [comment]
My problem is keeping simple style (italic) from docx to html, not the reverse. Is this problem solved?

**Comment by tarleb** [comment]
I'm not sure I understand. Can you post a minimal example, the actual output, and a description of the output you'd expect instead?
