### ISSUE TITLE
org mode to markdown citation key conversion not working?

### ISSUE THREAD

**Issue by uliw** [jgm/pandoc#8302]
Processing the following org-mode input file
```
some text cite:&long-2004-tecton-evolut
```
results in
```
some text [cite:&long-2004-tecton-evolut](cite:&long-2004-tecton-evolut)
```
The expected markdown syntax is
```
some text [@long-2004-tecton-evolut]
```
This happens on linux with
```
pandoc 2.18
Compiled with pandoc-types 1.22.2, texmath 0.12.5, skylighting 0.12.3,
citeproc 0.7, ipynb 0.2, hslua 2.2.0
Scripting engine: Lua 5.4
```
can this be customized?

**Comment by jgm** [comment]
What is the significance of the `&` in the org syntax?
It works if you remove this, so probably this is something we just need to teach the org parser about.

**Comment by uliw** [comment]
before org had a native citation capability, there was org-ref. Org-ref additionally supports cross-references and labels. Org-ref introduced the preceding & to differentiate org-ref citations from org-citations that use the @ sign.
I now realize that this is more of a nice-to-have feature. That being said, by allowing both symbols, the parser would instantly cover part of the org-ref syntax.

Here is a bit more background: 
https://github.com/jkitchin/org-ref/blob/master/org-ref.org#2021-version-2-vs-version-3

**Comment by jgm** [comment]
According to the manual we do support org-ref citations.
@tarleb may be able to comment further.

**Comment by uliw** [comment]
The & vs @ notation was a fairly recent change

**Comment by jgm** [comment]
OK, I will push a fix for this.

One other question, though:  should `cite:` give you a regular citation or an author-in-text citation? The current org-ref code in pandoc gives an author-in-text citation, but your example suggests otherwise.

**Comment by uliw** [comment]
since we only translate the citation key, the rendering of the citation should rely on the final output processor via citeproc etc.

**Comment by jgm** [comment]
Pandoc has to choose between a NormalCitation and AuthorInText modes.  These modes matter for how citeproc will handle the citation, and for rendering into Markdown.  Normal gives

`[@foo2000]`

and usually renders as something like "(Foo 2000)" while AuthorInText gives

`@foo2000`

and usually renders as something like "Foo (2000)".

**Comment by uliw** [comment]
ah I see. Not sure how complete the org-ref support is, but org-ref differentiates these through the respective cite keyword
```
cite:&long-2004-tecton-evolut - > @long-2004-tecton-evolut # also citet
citep:&long-2004-tecton-evolut  -> [@long-2004-tecton-evolut]
```
but then there is a long list of other cite keywords

https://github.com/jkitchin/org-ref/blob/master/org-ref.org#bibtex-users

Unless this is already supported, probably useful to include a pointer to https://github.com/jkitchin/org-ref/blob/master/org-ref.org#bibtex-users which will translate org-ref to native org citations
(I wasn't aware of this one)

**Comment by jgm** [comment]
OK, then pandoc's current behavior is correct. Case closed.
