### ISSUE TITLE
tex environments like equation, align, displaymath should be treated as blocks, because latex render them in this way

### ISSUE THREAD

**Issue by c-ding-0** [jgm/pandoc#8303]
Latex renders environments like equation, align, displaymath in display style, so I think pandoc should treat them as blocks.

**Comment by tarleb** [comment]
I don't think this is true. LaTeX indents the first line of a paragraph, but doesn't do that after those environments. Compare the output of

``` latex
\documentclass[]{article}
\begin{document}
Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam.
\begin{equation}E = m c ^2\end{equation}
Mauris mollis tincidunt felis.
\end{document}
```

and

``` latex
\documentclass[]{article}
\begin{document}
Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam.

Mauris mollis tincidunt felis.
\end{document}
```

Note the different identation of "Mauris".

**Comment by c-ding-0** [comment]
I mean these environemnts should be treated as RAW BLOCKs (not paragraphs) , while  pandoc treats them as raw inlines.

**Comment by c-ding-0** [comment]
> I don't think this is true. LaTeX indents the first line of a paragraph, but doesn't do that after those environments. Compare the output of
> 
> ```
> \documentclass[]{article}
> \begin{document}
> Pellentesque dapibus suscipit ligula. Donec posuere augue in quam. Etiam vel
> tortor sodales tellus ultricies commodo. Suspendisse potenti. Aenean in sem ac
> leo mollis blandit.
> \begin{equation}E = m c ^2\end{equation}
> Mauris mollis tincidunt felis.
> \end{document}
> ```
> 
> and
> 
> ```
> \documentclass[]{article}
> \begin{document}
> Pellentesque dapibus suscipit ligula. Donec posuere augue in quam. Etiam vel
> tortor sodales tellus ultricies commodo. Suspendisse potenti. Aenean in sem ac
> leo mollis blandit.
> 
> Mauris mollis tincidunt felis.
> \end{document}
> ```
> 
> Note the different identation of "Mauris".

I mean these environemnts should be treated as RAW BLOCKs (not paragraphs) , while  pandoc treats them as raw inlines.

**Comment by jgm** [comment]
LaTeX will accept this in places where pandoc expects inline content (e.g. headings, table captions).
And if they were treated as raw blocks, then as @tarleb has noted, the result would be that the following textual content was treated as a new paragraph rather than a continuation of the existing one.
