### ISSUE TITLE
enable line numbers using --indented-code-classes

### ISSUE THREAD

**Issue by mkettn** [jgm/pandoc#8306]
**Explain the problem.**

I think `--indented-code-classes` does not add the class to code blocks.

When I translate the file [test.md](https://github.com/jgm/pandoc/files/9600589/test.md) with the following command:

```shell
$ pandoc --from=markdown+backtick_code_blocks+fenced_code_blocks+fenced_code_attributes -s -o test.html --highlight-style=tango --indented-code-classes=numberLines test.md
```

I expect all code blocks in the output file test.md to have line numbers, since I used the indented-code-classes switch. But they dont get added, except for the last block where I explicitly added ".numberLines" in the source code.

**Pandoc version?**

What version of pandoc are you using, on what OS? (If it's not the latest release, please try with the latest release before reporting the issue.)

```
$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /home/mkettner/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

OS is Ubuntu 18.04

**Comment by jgm** [comment]
You're not using indented code blocks.  You're using fenced code blocks.  `--indented-code-classes` only affects *indented* code blocks.
