### ISSUE TITLE
Not display images in html from Markdown

### ISSUE THREAD

**Issue by oleg0406** [jgm/pandoc#8314]
I have a problem. I am using pandoc 2.19.1 on Arch linux. When generating a file from Markdown with the --embed-resources option in HTML, images are not displayed in the Google, Firefox browser

**Comment by tarleb** [comment]
Please add a reproducible example with sample input and the exact command line that was used. Otherwise it's impossible for us to know what's going on.

**Comment by oleg0406** [comment]
![image](https://user-images.githubusercontent.com/61734102/191990521-58ee5c74-b3c0-4ab8-99b8-1ea233dfe615.png)

Command:
```pandoc --embed-resources --file-scope --template ./templates/doc-template.html Test.md -o Test.html```

Directory tree:
├── images
│   ├── ritm-plot-block.png
├── templates  
│   |── doc-template.html
├── Test.md


Browser:

![image](https://user-images.githubusercontent.com/61734102/191990896-f09f9c38-adba-434f-9ad8-d432ded4abaf.png)

HTML Code:

![image](https://user-images.githubusercontent.com/61734102/191991211-ac05d752-fc02-4867-bf45-2164abec7dfe.png)

**Comment by tarleb** [comment]
Closing as not reproducible.
