### ISSUE TITLE
Missing languages have a bad failure mode for LaTeX/PDF output

### ISSUE THREAD

**Issue by Porges** [jgm/pandoc#8325]
**Explain the problem.**

I have a Markdown document with various languages used (via `<span lang="…">`). When I try to compile it to PDF I get a LaTeX error:

```console
$ pandoc input.md -o output.pdf
Error producing PDF.
! LaTeX Error: Command \text already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.86 ...ommand{\text}[2][]{\foreignlanguage{}{#2}}
```

I converted to `.tex` instead, and examined the document. If the language is not known then the `.tex` document attempts to redefine the `\text` command:

```latex
\ifxetex
  % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[]{english}
  \setotherlanguage[]{german}
  \setotherlanguage[]{danish}
  \setotherlanguage[]{dutch}
  \setotherlanguage[]{french}
  \setotherlanguage[]{magyar}
  \setotherlanguage[]{italian}
  \setotherlanguage[]{russian}
  \setotherlanguage[]{russian}
  \setotherlanguage[]{swedish}
  \setotherlanguage[]{icelandic}
  \setotherlanguage[]{}
  \setotherlanguage[]{}
  \setotherlanguage[]{}
\else
  \usepackage[shorthands=off,ngerman,danish,dutch,french,magyar,italian,russian,russian,swedish,icelandic,,,,main=english]{babel}
  \newcommand{\textgerman}[2][]{\foreignlanguage{ngerman}{#2}}
  \newenvironment{german}[2][]{\begin{otherlanguage}{ngerman}}{\end{otherlanguage}}
  \newcommand{\textdanish}[2][]{\foreignlanguage{danish}{#2}}
  \newenvironment{danish}[2][]{\begin{otherlanguage}{danish}}{\end{otherlanguage}}
  \newcommand{\textdutch}[2][]{\foreignlanguage{dutch}{#2}}
  \newenvironment{dutch}[2][]{\begin{otherlanguage}{dutch}}{\end{otherlanguage}}
  \newcommand{\textfrench}[2][]{\foreignlanguage{french}{#2}}
  \newenvironment{french}[2][]{\begin{otherlanguage}{french}}{\end{otherlanguage}}
  \newcommand{\textmagyar}[2][]{\foreignlanguage{magyar}{#2}}
  \newenvironment{magyar}[2][]{\begin{otherlanguage}{magyar}}{\end{otherlanguage}}
  \newcommand{\textitalian}[2][]{\foreignlanguage{italian}{#2}}
  \newenvironment{italian}[2][]{\begin{otherlanguage}{italian}}{\end{otherlanguage}}
  \newcommand{\textrussian}[2][]{\foreignlanguage{russian}{#2}}
  \newenvironment{russian}[2][]{\begin{otherlanguage}{russian}}{\end{otherlanguage}}
  \newcommand{\textswedish}[2][]{\foreignlanguage{swedish}{#2}}
  \newenvironment{swedish}[2][]{\begin{otherlanguage}{swedish}}{\end{otherlanguage}}
  \newcommand{\texticelandic}[2][]{\foreignlanguage{icelandic}{#2}}
  \newenvironment{icelandic}[2][]{\begin{otherlanguage}{icelandic}}{\end{otherlanguage}}
  \newcommand{\text}[2][]{\foreignlanguage{}{#2}}
  \newenvironment{}[2][]{\begin{otherlanguage}{}}{\end{otherlanguage}}
\fi
```

I would expect instead either no error (with no real support for the language) or a proper error about the language not being supported.

**Pandoc version?**
What version of pandoc are you using, on what OS? (If it's not the latest release, please try with the latest release before reporting the issue.)

```console
$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
```

**Comment by Porges** [comment]
Incidentally the languages I am trying to use are:

* Somali
* Sotho
* Swiss German

While there are no `.ldf` files for these languages, the Babel manual notes that (for Somali & Swiss German) they are supported via `.ini` files which can be loaded via `\babelprovide`. This would be a good extension.

**Comment by Porges** [comment]
A more robust solution might be to rely on Babel autoloading, since that can take BCP47 tags, which would also remove all the code in [`LaTeX/Lang.hs`](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX/Lang.hs)

**Comment by jgm** [comment]
Try using `lang="de-CH"` for Swiss German.  That should work (judging from the code anyway).  However, you're using quite an old version of pandoc, and there have been lots of changes in this area -- try the most recent version, 2.19.2.

> A more robust solution might be to rely on Babel autoloading, since that can take BCP47 tags, which would also remove all the code in [LaTeX/Lang.hs]

Yes, that is very tempting indeed.  I think that Babel support for BCP47 tags is a fairly recent addition, though, so that change might result in breakage for people who have older babels.  Do you happen to know, e.g, what the first version of texlive is with support for this in babel?

**Comment by jgm** [comment]
By the way, here is a demo of current pandoc support:

<https://pandoc.org/try/?params=%7B%22text%22%3A%22%5Bsomali%5D%7Blang%3Dso%7D%5Cn%5Cn%5Bsotho%5D%7Blang%3Dst%7D%5Cn%5Cn%5Bswiss+german%5D%7Blang%3Dde-CH%7D%5Cn%22%2C%22to%22%3A%22latex%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D>

**Comment by Porges** [comment]
> Try using `lang="de-CH"` for Swiss German. That should work (judging from the code anyway). However, you're using quite an old version of pandoc, and there have been lots of changes in this area -- try the most recent version, 2.19.2.

Wikipedia indicates that Swiss German (`gsw`) and German as spoken in Switzerland (`de-CH`) are different things, although this might not result in any differences at the `babel` level, and they can probably both use `swissgerman`.

> Yes, that is very tempting indeed. I think that Babel support for BCP47 tags is a fairly recent addition, though, so that change might result in breakage for people who have older babels. Do you happen to know, e.g, what the first version of texlive is with support for this in babel?

It was [added in 3.43](https://latex3.github.io/babel/news/whats-new-in-babel-3.43.html) in 2020. This was merged quickly into texlive, and it looks like it was included in the 2020 release.

**Comment by Porges** [comment]
Checking the version you linked to, it looks like `babelprovide` is already used. That's nice 🙂

**Comment by jgm** [comment]
If you want `swissgerman` instead of (modern) `nswissgerman`, then you can use `de-CH-1901`.

**Comment by jgm** [comment]
Link to documentation for BCP47 autoloading:
https://latex3.github.io/babel/news/whats-new-in-babel-3.43.html

**Comment by Porges** [comment]
Thanks for the quick fix!

**Comment by jbezos** [comment]
> Wikipedia indicates that [Swiss German](https://en.wikipedia.org/wiki/Swiss_German) (`gsw`) and [Standard German as spoken in Switzerland](https://en.wikipedia.org/wiki/Swiss_Standard_German) (`de-CH`) are different things, although this might not result in any differences at the `babel` level, and they can probably both use `swissgerman`.

I’d just like to confirm this statement. For both BCP47 and the Unicode CLDR, Swiss German isn‘t `de-CH` but `gsw`, which is a different language. As one of the aims of `babel` is to stick to those standards, in the `ini` files the `name.english` is set to ‘Swiss High German’ and ‘Swiss German’, respectively.

**Comment by jgm** [comment]
Currently we have:
``` hs
toBabel (Lang "de" _ (Just "CH") vars _ _)                                      
  | "1901" `elem` vars                  = Just "swissgerman"                    
  | otherwise                           = Just "nswissgerman"                   
toBabel (Lang "de" _ _ vars _ _)                                                
  | "1901" `elem` vars                  = Just "german"                         
  | otherwise                           = Just "ngerman"     
```
Should we be using `german` and `ngerman` for `de-CH` instead of `swissgerman`, and reserving `swissgerman` for `gsw`?

**Comment by jbezos** [comment]
I’m not sure how `pandoc` deals with languages, but the rule is, use `nswissgerman` if you are loading the `ldf` file for modern German as spoken in Switzerland, so I presume your settings are (currently) correct. It’s somewhat unfortunate the German style uses names incompatible with BCP47 and the CLDR, including `german`, which isn’t currently the option to be used for German with the `ldf` file (iir, it’s the only language with incompatible names, besides Serbian). I’m attempting the sort all that out, as I explain in [Locale naming](https://latex3.github.io/babel/guides/locale-naming.html). Feedback is most welcome.
