### ISSUE TITLE
Pandoc docx to markdown wrong output for hyperlinks

### ISSUE THREAD

**Issue by Corvalan** [jgm/pandoc#8328]
This is the pandoc output of two links:

[[Google]{.underline}](https://google.com)
[[Yahoo]{.underline}](https://yahoo.com)
[Underline]{.underline}

**Pandoc version 2.19.2**

**Comment by jgm** [comment]
There isn't enough here for us to understand the issue.  Please give full input you used to produce this output, and exact command line, and say what you expected instead and why.

**Comment by Corvalan** [comment]
[docx to md.zip](https://github.com/jgm/pandoc/files/9660567/docx.to.md.zip)

zipfile contains docx, a .bat file and the output file.

input docx file contains two simple links

bat file contains:

@echo OFF
FOR /r "." %%i IN (*.docx) DO pandoc -f docx -t markdown "%%~fi" -o "%%~dpni.md"
ECHO. Done. Press any key to terminate program
PAUSE>NUL

output .md file contains:

[[A link to google]{.underline}](https://google.com)

[[A link to yahoo]{.underline}](https://yahoo.com)


So the part {.underline} needs to be removed from the output.

**Comment by jgm** [comment]
This is valid pandoc markdown, which represents the fact that the text is underlined.
If you don't want this, you could try using `-t gfm` or `-t markdown_strict` or `-t commonmark`.
(Then you'll get `<u>` tags.)
