### ISSUE TITLE
docx to dokuwiki: wrong output with bullet lists and hyperlinks

### ISSUE THREAD

**Issue by Corvalan** [jgm/pandoc#8329]
Pandoc version 2.19.2

Here is the (wrong) output of docx to dokuwik format:

Bullet list:

<HTML><ul></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdf asdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdf asdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd fasdf asd<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>F asd fasdf<HTML></p></HTML>
<HTML></li></HTML><HTML></ul></HTML>

Multi-level bullet list:

<HTML><ul></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd fasdf asdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdf<HTML></p></HTML>

<HTML><ul></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>F a<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Sdf<HTML></p></HTML>

<HTML><ul></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdfasdfasd fasdf asdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdf<HTML></p></HTML>
<HTML></li></HTML><HTML></ul></HTML>
<HTML></li></HTML><HTML></ul></HTML>
<HTML></li></HTML><HTML></ul></HTML>

Numbered list:

<HTML><ol style="list-style-type: decimal;"></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd fa<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Sdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>F as<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Df<HTML></p></HTML>
<HTML></li></HTML><HTML></ol></HTML>

Multi-level numberered list:

<HTML><ol style="list-style-type: decimal;"></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd fasdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd<HTML></p></HTML>

<HTML><ol style="list-style-type: lower-alpha;"></HTML>
<HTML><li></HTML>> <HTML><p></HTML>F asd<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Fas df<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>asdfasdf<HTML></p></HTML>

<HTML><ol style="list-style-type: lower-roman;"></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asdf<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>Asd<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>asdf<HTML></p></HTML>
<HTML></li></HTML><HTML></ol></HTML>
<HTML></li></HTML><HTML></ol></HTML>
<HTML></li></HTML><HTML></ol></HTML>

Links

<HTML><ul></HTML>
<HTML><li></HTML>> <HTML><p></HTML>[[http://google.com|__http:%%//%%google.com__]]<HTML></p></HTML>
<HTML></li></HTML>
<HTML><li></HTML>> <HTML><p></HTML>[[https://google.com|__This is a link text__]]<HTML></p></HTML>
<HTML></li></HTML><HTML></ul></HTML>

[[https://google.com|__https:%%//%%google.com__]]

[[https://google.com|__This is also a link__]]

**Comment by jgm** [comment]
This isn't helpful without the docx you used as input, and full command line.
Also, please say exactly what is wrong with the output.

**Comment by jgm** [comment]
closing, not enough information.
