### ISSUE TITLE
Add support for Page Information and page numbers in TOC to RTF writer

### ISSUE THREAD

**Issue by bandel65** [jgm/pandoc#8336]
Page 49 of the RTF 1.9.1 specification provides a number of controls which can be used to govern page size, margins, facing page behavior, landscape pages, etc.  If these were specified, it would be feasible to determine which pages Headings (and Captions; see #8335) appear on.  This in turn would make it feasible to provide page numbers in the TOC (and LOF, LOT, if implemented; see  #8335) generated by the RTF writer.

**Comment by jgm** [comment]
No, I don't think it's feasible to calculate page numbers. That would require implementing a layout engine, essentially.
Out of scope.
