### ISSUE TITLE
pandoc --version with new package architecture

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#8339]
Since all the option parsing is done in `pandoc` itself, `pandoc --version` can't return the versions of `pandoc-cli`, `pandoc-server`, or `pandoc-lua` -- and presumably also not the Lua version used for the scripting engine.  Nor can it indicate whether the executable was compiled with/without Lua or server support.

This seems undesirable.  The only fix I can think of is a bit ugly, adding a parameter to `parseOptionsFromArgs`.

@tarleb any thoughts?

Another alternative would be to move the option-parsing code (T.P.App.CommandLineOptions) to pandoc-cli.  A drawback of this, though, would be that modifications to command line options would generally require touching both pandoc-cli and pandoc itself (T.P.App.Opt). Maybe that's okay?  Also, on this approach the option-parsing code wouldn't be exported by the `pandoc` library.  Of course, we could always add a library stanza to `pandoc-cli`, but I'd hoped to get away from executable/library packages.

**Comment by jgm** [comment]
Here's another approach we could take: pandoc-cli could simply scan the arguments for `-v` or `--version`. If it finds this, it could emit the version info and quit.  Otherwise, pass the arguments to `parseOptionsFromArgs`.
That is even simpler.

**Comment by jgm** [comment]
Actually, the Right Thing To Do is probably to put ALL the option parsing (including for `pandoc-lua` and `pandoc-cli`) in `pandoc-cli`.  Parse options into a data structure for CLI options, then set the Opt structure accordingly and pass it to pandoc.  If we used `optparse-applicative`, it has support for "modes" like `server` or `lua` with different sets of options.

**Comment by jgm** [comment]
I see now that we do have information about the scripting engine (because we pass this to convertWithOpts).
Maybe it's okay if we don't have information about server support.

**Comment by tarleb** [comment]
An `IncludedVersions` data type might not be the most elegant, but would probably work well for this and wouldn't require many changes.

**Comment by jgm** [comment]
New plan:

- put `texmath`, etc. in the build-depends for pandoc-cli (this way `VERSION_texmath` will be available)
- add `import Text.TeXMath ()` to pandoc.hs to avoid a warning about an unused package
- handle `--version` and `-v` in pandoc.hs
- construct version message to include flag settings for lua and server, and all relevant package versions
- move `nightly` flag from `pandoc` to `pandoc-cli` so the version suffix can be included

**Comment by jgm** [comment]
In the end I decided to just remove the dependency version information from `--version` output.
