### ISSUE TITLE
output to JATS XML not writing line break

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#8344]
STEPS:
```
printf 'foo\\\nbar' | pandoc --from markdown --to jats
```
EXPECTED:
```
<p>foo<break/>
bar</p>
```
GOT:
```
<p>foo
bar</p>
```

VERSION:
```
$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /home/castedo/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="36 (Container Image)"
```

COMMENTARY:
Expected the same output as
```
printf 'foo\\\nbar' | pandoc --from markdown --to html
```
but with `<break>` instead of `<br/>`.

Here's the JATS definition of `<break>`:
https://jats.nlm.nih.gov/archiving/tag-library/1.3/element/break.html

I hit this problem trying to get a line break inside a table (in an MD -> JATS -> PDF pipeline).

**Comment by jgm** [comment]
Have a look at
https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/break.html
which shows that `<break>` is restricted to a very few contexts (not including paragraphs).

**Comment by castedo** [comment]
Here's a more realistic example: [table-with-newlines.md.txt](https://github.com/jgm/pandoc/files/9691300/table-with-newlines.md.txt)
And closer to the actual case I've hit. And conforms to the spec.

Output to HTML has a `<br/>` in each table cell. Output to JATS has no `<break>`.

At the moment I'm having to work around this by having a huge raw passthrough
```
```{=jats}
<table-wrap>
<table>
...
```
and writing the full JATS XML inside my markdown source file.

**Comment by jgm** [comment]
No need for that. You can just include
```
`<break>`{=jats}
```
at the appropriate place in your table cell and it will pass through.

It's true that `<break>` is allowed in table cells, and a few other contexts. In principle we could keep track of the surrounding context in the writer and emit `<break>` only in these contexts.  If this seems worth doing, I could reopen the issue, but this workaround is pretty simple.

**Comment by jgm** [comment]
Or create a Lua filter that replaces LineBreak elements with raw JATS when the format is "jats".

**Comment by castedo** [comment]
Doh! :facepalm: Thanks for reminding me about the inline raw element syntax. That's a much better quick fix, and not too bad.

And thanks for the Lua filter example. If I find myself doing this often, I'll resort to the Lua filter.

**Comment by jgm** [comment]
Maybe I'll re-open this as a proposal to render LineBreak as `<break/>` when and only when it would be a direct child of a `<td>` or `<title>` element.  That's probably worth doing, if low priority.
