### ISSUE TITLE
Add djot.lua as custom writer example

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#8356]
The current writer example in `sample.lua` uses a classic writer. Since we are deprecating those, it would be nice to provide a better example.

Only downside I can think of: we'd probably have to update the file before each release to make sure it won't get out of date.

**Comment by jgm** [comment]
I'm not really sure we need to supply a custom writer, now that we have tutorials with examples on the website and in `docs/`. And I think djot-writer.lua is a bit complicated to serve as an example -- also, for purposes of an example, it's better to have a writer that implements a syntax people already know.  So I'm inclined to think we could just remove `sample.lua` (along with any references to it in the docs) and rely on the documentation.  We could link to djot-writer.lua in the documentation, too, as an additional example.

Another alternative would be just to modify `sample.lua` with the one-line change converting a classic writer to a new-style one, but that really doesn't give them an idea how to write  a new-style writer...
