### ISSUE TITLE
failure with simple valid json file as metadata file

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#8358]
Here's an interesting one!

REPO STEPS:
```
echo '{"a": "\n    z"}' > metadata.json
echo hi | pandoc --metadata-file metadata.json
```
RESULT:
```
Error at "metadata.json_chunk" (line 2, column 5):
unexpected end of input
```

VERSION:
```
$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```

COMMENTS:
I'm not directly affected by this and I can easily work around it. But by chance I came across a much more complicated variant of this simple test case. This issue could be very surprising in work flows where usually everything is working fine with text values with newlines and spaces in metadata, but then one day everything fails because the offending combination of newlines and spaces get hit.

**Comment by jgm** [comment]
The `jq` tool also fails on this, so I suspect it's invalid JSON:
```
% cat metadata.json| jq .
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 6
```
I think you want this instead:
```
{
  "a": "\n    z"
}
```
Use `\n` instead of a newline character (which echo produces when you use `\n`).

**Comment by castedo** [comment]
Nope, it's valid JSON. What you think I wanted is indeed what I wanted. But the echo command works fine. There are single quotes:
```
$ echo '{"a": "\n    z"}' | jq
{
  "a": "\n    z"
}
```
jq is happy and it's valid JSON.

**Comment by jgm** [comment]
Your system's echo apparently works differently from mine.

**Comment by jgm** [comment]
Pandoc is evidently thrown off by the value starting with a newline.
But why would you ever want/need this?  The values are parsed as Markdown, so the initial newline would just be ignored anyway.

**Comment by jgm** [comment]
We're using a yaml parsing library, and relying on "YAML is a superset of JSON."
I don't really understand why we're getting this error, since
```
---
"a": "
    z"
...
```
works fine.

**Comment by jgm** [comment]
Pandoc seems to want another newline after the `z`.
If you insert that, it works.
I still don't quite grasp why it fails without it.

**Comment by jgm** [comment]
With the newline, you get:
```
Pandoc
  Meta
    { unMeta =
        fromList
          [ ( "a" , MetaBlocks [ CodeBlock ( "" , [] , [] ) "z" ] ) ]
    }
  []
```
Is that what you wanted?

**Comment by castedo** [comment]
Oh, i don't actually have a real scenario. I first hit the bug with a string that was a bunch text with a some new lines in side and some spacing. Nothing crazy. And then I whittled it down to this simple repo case.
I could maybe some up with a realistic abstract scenario ... say somebody doing an abstract in json that is passed in a metadata file. But I'm actually not doing that personally.

**Comment by castedo** [comment]
I'm trying to find some of the long strings I started with that tickle this bug, but I think I'm might have deleted them already this afternoon. :facepalm:.

**Comment by castedo** [comment]
Let me know if you want me to cook up something more likely to actually be hit by a real scenario.

**Comment by jgm** [comment]
Another interesting data point:
```
% pandoc
---
"a": "\n    z"
...
<hr />
<p>“a”: “z” …</p>
```
which shows that with the `\n` character, it is not being recognized by the YAML parser.

It is not a problem with the YAMl parser, which can parse this directly:
```hs
ghci> decodeFileThrow "metadata.json" :: IO Value
Object (fromList [("a",String "\n    z")])
```
