### ISSUE TITLE
Custom class not applied well for custom heading (level > 6)

### ISSUE THREAD

**Issue by fsoedjede** [jgm/pandoc#8363]
**Explain the problem.**

When in markdown I add a custom heading with level 7, and I try to apply a custom class, the classes are not merged

Source: 
```markdown
### Titre 3 {#titre-3 .CPH03---Titre-3}

Lorem ipsum

###### Titre 6 {#titre-6 .CPH06---Titre-6}

####### Titre 7 {#titre-7 .CPH07---Titre-7}
```

Current result:

```html
<h3 class="CPH03---Titre-3" id="titre-3">Titre 3</h3>
<p>Lorem ipsum</p>
<h6 class="CPH06---Titre-6" id="titre-6">Titre 6</h6>
<p class="heading" class="CPH07---Titre-7" id="titre-7">Titre 7</p>
```

Expected result:
```html
<h3 class="CPH03---Titre-3" id="titre-3">Titre 3</h3>
<p>Lorem ipsum</p>
<h6 class="CPH06---Titre-6" id="titre-6">Titre 6</h6>
<p class="heading CPH07---Titre-7" id="titre-7">Titre 7</p>
```

Permalink to test: https://pandoc.org/try/?params=%7B%22text%22%3A%22%23%23%23+Titre+3+%7B%23titre-3+.CPH03---Titre-3%7D%5Cn%5CnLorem+ipsum%5Cn%5Cn%23%23%23%23%23%23+Titre+6+%7B%23titre-6+.CPH06---Titre-6%7D%5Cn%5Cn%23%23%23%23%23%23%23+Titre+7+%7B%23titre-7+.CPH07---Titre-7%7D%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D

Code responsible: https://github.com/jgm/pandoc/blob/2.19.2/src/Text/Pandoc/Writers/HTML.hs#L1012-L1014 (Sorry I couldn't help more. I don't yet understand Haskell to submit a resolving PR)

Test example to add in tests:
```
# Test case to valid the change is now ok
---
% pandoc -f markdown -t html
####### Foo {#foo .custom-class}
^D
<p class="heading custom-class" id="foo">Foo</p>
---
```

Currently I fix the issue using a lua filter

Thanks

**Pandoc version?**
What version of pandoc are you using, on what OS? (If it's not the latest release, please try with the latest release before reporting the issue.)
pandoc version 2.19.2

**Comment by jgm** [comment]
thanks for the good bug report!

**Comment by fsoedjede** [comment]
WoW the fix was really fast. Thanks.

With the value you provide with pandoc, it’s important we, the users, ease your task when we submit a bug or request a functionality by being exhaustive
