### ISSUE TITLE
Add `<title>References` to `<ref-list>` for references in JATS output

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#8364]
This feature request is to include a `<title>` in the `<ref-list>` that is generated for references. As of 2.19.2 it is not output.

For example, here's what pandoc generates:
```
<back>
  <ref-list>
    <ref id="ref-shannon_mathematical_1998">
      <element-citation publication-type="book">
      ...
      </element-citation>
    </ref>
  </ref-list>
</back>
```
whereas this is what an eLife XML file (#63435-v3) looks like:
```
<back>
  ...
  <ref-list>
    <title>References</title>
    <ref id="bib1">
      <element-citation publication-type="journal">
      ...
      </element-citation>
    </ref>
...
</back>
```

The pandoc command is the following:
```
pandoc input.md -s --to=jats+element_citations --citeproc --metadata link-citations=true
```
with the attached [input.md](https://github.com/jgm/pandoc/files/9742767/input.md.txt).

In addition to producing JATS XML that is more compatible with other JATS readers, I suspect this feature will also be useful for a separate pandoc JATS reading feature I'll submit separately.

I would tweak the JATS template if I could to get this functionality but the entire `<back>` element is generated from one `$back$` template variable.

**Comment by jgm** [comment]
Does it help if you put `reference-section-title` in your metadata?
(see the manual)

**Comment by castedo** [comment]
Good idea! I didn't know about that. But sadly it does not add the title into the `<back><ref-list>`, only the body.

**Comment by jgm** [comment]
Can you quote the xml more fully so I can see where it adds the title?

**Comment by castedo** [comment]
My pleasure!
```
...
<article ... >
...
  <body>
...
  </body>
  <back>
...
    <ref-list>
      <title>References</title>
      <ref id="bib1">
...
      </ref>
...
    </ref-list>
  </back>
...
</article>
```
The full XML in all its glory is here:
https://raw.githubusercontent.com/elifesciences/elife-article-xml/master/articles/elife-63435-v3.xml

**Comment by jgm** [comment]
I meant, where does pandoc currently add the title when you use `reference-section-title`?

**Comment by castedo** [comment]
With `reference-section-title: Referencias` added to input.md meta I get:
```
<article ... >
...
<body>
...
<sec id="bibliography">
  <title>Referencias</title>
</sec>
</body>
<back>
<ref-list>
  <ref id="ref-shannon_mathematical_1998">
    <element-citation publication-type="book">
...
      <isbn>978-0-252-72548-7 978-0-252-72546-3</isbn>
    </element-citation>
  </ref>
</ref-list>
</back>
</article>
```

**Comment by jgm** [comment]
Oh, yes, that's no good at all.

**Comment by castedo** [comment]
A quick update: I hack around this limitation in wrapper utilities of pandoc for generating JATS XML. After calling pandoc, I string replace `<ref-list>` in pandoc's XML output with `<ref-list><title>References</title>` An example of this hack in this this utility:

https://gitlab.com/castedo/jatex/-/blob/7b90d1eebf44e976d54d26c07437fc20fa6a87aa/jatex/__init__.py#L31

**Comment by castedo** [comment]
Oh bummer. @jgm That test case is beautiful, but it missed a regression bug with a heading in the input document:  #9017  Sorry!

**Comment by castedo** [comment]
This enhancement does not appear to be working for element citations, see #9021.
