### ISSUE TITLE
Output `References` heading when `<back><ref-list><title>References` in JATS input

### ISSUE THREAD

**Issue by castedo** [jgm/pandoc#8365]
This feature request is to take advantage of enhancement #8364 and the JATS XML that eLife produces (and I suspect many others).

eLife JATS XML (e.g. [1]) does not place a `References` title in an empty section at the end of the JATS body. I bet other JATS XML generators do not do this. But eLife JATS does have a `<title>References` inside the `<ref-list>` and this is what is described in pandoc enhancement #8364 .

The enhancement described here is to generate a heading title when there is a `<title>`  inside the `<ref-list>` (rather than requiring an empty section with title at the end of the JATS body).

[1] https://raw.githubusercontent.com/elifesciences/elife-article-xml/master/articles/elife-63435-v3.xml

**Comment by castedo** [comment]
I see now that this is very similar to `metadata: reference-section-title:` which I am using now.

One minor related issue is whether this enhancement (or reference-section-title for that matter) generates H1 vs H2 headings. Most folks only want H1 used for the doc title for search engine optimization and to conform with HTML spec recommendations. Would be nice if generated heading is H2 by default or makes use of `shift-heading-level-by`.

**Comment by castedo** [comment]
A quick update:
  I hack around this limitation in wrapper utilities for pandoc that generate JATS XML. After calling pandoc, I string replace "<ref-list>" in pandoc's XML output with "<ref-list><title>" ... An example of this hack in this this utility:

https://gitlab.com/castedo/jatex/-/blob/7b90d1eebf44e976d54d26c07437fc20fa6a87aa/jatex/__init__.py#L31

**Comment by kamoe** [comment]
This issue should now been solved by this recent fix here: https://github.com/jgm/pandoc/pull/8840
The level of H generated is the current section header +1.
