### ISSUE TITLE
Latex writer will use `lstinline` in section headers

### ISSUE THREAD

**Issue by pkazmier** [jgm/pandoc#838]
According to the good folks in #latex irc group, it seems that `lstinline` should not be used in a `\section{...}` definition. I could not generate a PDF from a markdown -> latex pandoc conversion because `lstline` was used. For example, I have markdown that looks like:

```
## `intel.lua`: Intel driver code
```

Perhaps when in a `\section`, instead of using `lstinline`, we use the standard `\texttt`?

If you try to reproduce, a small trivial example is not enough to make it crap out. Here is a slightly larger example where you can see it crap out: https://gist.github.com/pkazmier/5438644

**Comment by jgm** [comment]
This seems to have been fixed already.
```
% pandoc --listings -t latex
## `intel.lua`: Intel driver code
\hypertarget{intel.lua-intel-driver-code}{%
\subsection{\texorpdfstring{\texttt{intel.lua}: Intel driver
code}{intel.lua: Intel driver code}}\label{intel.lua-intel-driver-code}}
```
