### ISSUE TITLE
Curly quotes misparse when one quote in link but not its matched quote, yielding right/right quotes

### ISSUE THREAD

**Issue by gwern** [jgm/pandoc#8381]
Pandoc appears to have a bug where single quotation marks inside a link do not balance properly with their match if they are inside+outside, leading to ’typographic error quotes’; this does not occur with most of the ways one could write the single quotes, nor does it occur with the double quotes (which all act as expected), and I don't see anything about quotes inside links being forbidden in [the manual](https://pandoc.org/MANUAL.html#typography) so I guess this is an overlooked edge case.

---

	'foo'
	
	['foo'](http://example.com)
	
	'[foo](http://example.com)'
	
	['foo](http://example.com)'
	
	'[foo'](http://example.com)
	
	'foo bar'
	
	'[foo bar](http://example.com)'
	
	'[foo](http://example.com) [bar](http://example.com)'
	
	['foo](http://example.com) [bar](http://example.com)'
	
	['foo](http://example.com) [bar'](http://example.com)
	
	'[foo](http://example.com) [bar'](http://example.com)

    ↓

	$ xo | pandoc -f markdown+smart -w html
	<p>‘foo’</p>
	<p><a href="http://example.com">‘foo’</a></p>
	<p>‘<a href="http://example.com">foo</a>’</p>
	<p><a href="http://example.com">’foo</a>’</p>
	<p>’<a href="http://example.com">foo’</a></p>
	<p>‘foo bar’</p>
	<p>‘<a href="http://example.com">foo bar</a>’</p>
	<p>‘<a href="http://example.com">foo</a> <a
	href="http://example.com">bar</a>’</p>
	<p><a href="http://example.com">’foo</a> <a
	href="http://example.com">bar</a>’</p>
	<p><a href="http://example.com">’foo</a> <a
	href="http://example.com">bar’</a></p>
	<p>’<a href="http://example.com">foo</a> <a
	href="http://example.com">bar’</a></p>

![xwd-16659592121706666](https://user-images.githubusercontent.com/352559/196061405-84aea090-4e24-4609-ad73-4d3b67c57f8c.png)

This yields the incorrect `’foo’`, `’foo bar’`, `’foo bar’`, `’foo bar’`.

None of the double-quote version trigger the same behavior:

	"foo"
	
	["foo"](http://example.com)
	
	"[foo](http://example.com)"
	
	["foo](http://example.com)"
	
	"[foo"](http://example.com)
	
	"foo bar"
	
	"[foo bar](http://example.com)"
	
	"[foo](http://example.com) [bar](http://example.com)"
	
	["foo](http://example.com) [bar](http://example.com)"
	
	["foo](http://example.com) [bar"](http://example.com)
	
	"[foo](http://example.com) [bar"](http://example.com)
	
	↓
	
	<p>“foo”</p>
	<p><a href="http://example.com">“foo”</a></p>
	<p>“<a href="http://example.com">foo</a>”</p>
	<p><a href="http://example.com">“foo</a>”</p>
	<p>“<a href="http://example.com">foo”</a></p>
	<p>“foo bar”</p>
	<p>“<a href="http://example.com">foo bar</a>”</p>
	<p>“<a href="http://example.com">foo</a> <a
	href="http://example.com">bar</a>”</p>
	<p><a href="http://example.com">“foo</a> <a
	href="http://example.com">bar</a>”</p>
	<p><a href="http://example.com">“foo</a> <a
	href="http://example.com">bar”</a></p>
	<p>“<a href="http://example.com">foo</a> <a
	href="http://example.com">bar”</a></p>

![xwd-16659593801706964](https://user-images.githubusercontent.com/352559/196061472-cfe8e1f1-bffe-4d0f-a7c5-291a66667afd.png)

**Comment by jgm** [comment]
The documentation is already pretty long---we can't put everything in it.  But the contents of a link description are parsed as inlines, and quotes inside can't match quotes outside. You're probably getting different results with double quotes because unmatched quotes have different defaults for single and double.

I don't regard this as a bug.

**Comment by jgm** [comment]
Btw you can see this just from the types.  A Quoted element can be either inside or outside a Link description; it can't be part inside and part outside.
