### ISSUE TITLE
unexpected control sequence \\

### ISSUE THREAD

**Issue by jigaowan** [jgm/pandoc#8384]
try convert markdown with latex to epub

my markdown file:
```
### title

$$
1=1
\\
2=2
$$
```

command `pandoc -s -o demo.epub -t epub --mathml demo.md`

got 
```
[WARNING] Could not convert TeX math
  1=1
  \\
  2=2
  , rendering as TeX:
  \\
  ^
  unexpected control sequence \\
  expecting "%", "\\label", "\\tag", "\\nonumber" or whitespace
```

pandoc version
```
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```

**Comment by jgm** [comment]
What are you trying to do here?  If you think `\\` will create a line break, that is wrong.  Although this will compile with pdflatex, the result is
<img width="93" alt="Screen Shot 2022-10-17 at 7 19 41 PM" src="https://user-images.githubusercontent.com/3044/196320191-bcff71f0-505c-474d-a945-66ad1c21513f.png">

**Comment by jgm** [comment]
What you probably want is
```
$$
\begin{aligned}
1 &= 2 \\
2 &= 2
\end{aligned}
$$
```

**Comment by jigaowan** [comment]
my bad
is ok in another app so I misunderstood the latex
