### ISSUE TITLE
add --list-latex-packages to list all LaTeX dependencies

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#8386]
This feature request should functions similar to [--list-output-formats](https://pandoc.org/MANUAL.html#option--list-output-formats) and [--list-extensions](https://pandoc.org/MANUAL.html#option--list-extensions), but for listing LaTeX dependencies.

The source information is already available in documentation: https://pandoc.org/MANUAL.html#creating-a-pdf

So the feature request focuses more on a programable approach to obtain, and potentially, manipulate this down the pipes.

**Comment by ickc** [comment]
As far as I understand, the list to install those dependencies should be this list: https://github.com/ickc/bootstrapping-os-environments/blob/4d2ae0b992ab03b36885d1a3a7a4e9fc0668e0dd/common/tex.txt

A caveat is that some packages listed in the doc are in a bundle named differently. So IMO listing those names is more useful than those given in the manual (or may be provide both.)

**Comment by jgm** [comment]
I'm inclined not to do this.  With our other `--list-xxx` functions, we can guarantee programatically that the list is correct. With this, we'd just have to manually update the list.  And of course the list of dependencies depends on (a) what you're doing in your document, since some dependencies are included conditionally, and (b) what template you're using (if you're using a custom template, the list could be different).

**Comment by jgm** [comment]
I'm adding a pandoc lua script to `tools/` that will scan the default latex template and print package dependencies.  This can be run with `make latex-package-dependencies`, but this requires that you have the dev version of pandoc (first) in your path.

**Comment by jgm** [comment]
It produces this list:
```
multirow
listings
longtable
csquotes
ulem
upquote
parskip
caption
natbib
etoolbox
xeCJK
selnolig
amsmath
luatexja-fontspec
microtype
inputenc
geometry
luatexja-preset
graphicx
hyperref
fancyvrb
bookmark
array
fontenc
beamerarticle
textcomp
xurl
pgfpages
footnote
amssymb
footnotehyper
svg
xcolor
setspace
babel
calc
mathspec
lmodern
unicode-math
biblatex
iftex
booktabs
```

**Comment by jgm** [comment]
Not complete, though, because it doesn't include packages required by the highlighting macros -- these are dynamically inserted and can't be inspected at this point.
