### ISSUE TITLE
Why the output of ox-pandoc is different from using Pandoc CLI

### ISSUE THREAD

**Issue by aminevsaziz** [jgm/pandoc#8396]
recently i discovered these issues with ox-pandoc/pandoc, where the org buffer need to be exported to temporary org file using pandoc and then convert it again using pandoc CLI! this behavior in fact lead to loss of style information.
here an org example
```
* Text with custom style 
#+attr_html: :custom-style Sender
#+begin_text
Page 6
#+end_text

* other stuff
@@pandoc: <div custom-style="Sender">Page X</div>@@
```

running this org example using any ox-pandoc exporter in emac (e.g org-pandoc-export-to-markdown) will generate the following output:

```
---
author: Bla Bla
---

# Text with custom style

::: text
Page 6
:::

# other stuff

\<div custom-style=\"Sender\"\>Page X\</div\>
```

Suprisingly, using Pandoc CLI (e.g pandoc -f org -t markdown test.org -o test.md) show the following results:

```
# Text with custom style

::: {.text custom-style="Sender"}
Page 6
:::

# other stuff

` <div custom-style="Sender">Page X</div>`{=pandoc}
```
why cant we keep the the information regarding custom-style for example?

**Comment by jgm** [comment]
You'd have to ask the maintainers of ox-pandoc.  I don't know anything about how it works.

**Comment by tarleb** [comment]
See kawabata/ox-pandoc#51.
