### ISSUE TITLE
id=xxxxx seems to break toc generation from&to markdown

### ISSUE THREAD

**Issue by wizlee** [jgm/pandoc#8402]
## Summary
- Background
    - I am trying to generate TOC for jupyter notebook ipynb file. I am able to convert from ipynb into markdown by using `pandoc -f ipynb+raw_markdown -t markdown input.ipynb -o output.md`
    - However, I am stuck at trying to generate TOC from the markdown output of the notebook. 
    - The example below is my attempt to narrow down to the characters that I think are causing the incorrect TOC generation.
- [permalink to pandoc online](https://pandoc.org/try/?params=%7B%22text%22%3A%22%3A%3A%3A+%7B.cell+.markdown+id%3D%5C%226u8qXoeFGdqt%5C%22%7D%5Cn%23+Summary%5Cn%3E+Expand+to+see+summary%5Cn%5Cn%23%23+Overview+and+Explanation%5Cn%3A%3A%3A%5Cn%5Cn%23+Details%5Cn%5Cn%23%23+inner+1%5Cntext%5Cn%5Cn%23%23+inner+2%5Cn%5Cn%23%23%23+inner+inner+1%5Cn%5Cn%23%23+inner+3%5Cntext%5Cn%22%2C%22to%22%3A%22markdown%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Atrue%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D) that reproduces the issue.
- Alternatively, the exact command line that I used is `pandoc -s --to markdown -f markdown --toc -o toc.md output.md`
    - The input and output are shown below for convenience. 
    - Note the `::: {.cell .markdown id="6u8qXoeFGdqt"}` is converted to `::: {#6u8qXoeFGdqt .cell .markdown}` and the absent of the "Summary" header in the TOC

## System
- OS: Windows 10
- pandoc version:  2.19.2

## Sample input
```
::: {.cell .markdown id="6u8qXoeFGdqt"}
# Summary
> Expand to see summary

## Overview and Explanation
:::

# Details

## inner 1
text

## inner 2

### inner inner 1

## inner 3
text

```

## Sample Output
```
-   [Details](#details)
    -   [inner 1](#inner-1)
    -   [inner 2](#inner-2)
        -   [inner inner 1](#inner-inner-1)
    -   [inner 3](#inner-3)

::: {#6u8qXoeFGdqt .cell .markdown}
# Summary

> Expand to see summary

## Overview and Explanation
:::

# Details

## inner 1

text

## inner 2

### inner inner 1

## inner 3

text

```

**Comment by jgm** [comment]
Can you say what exactly is wrong with the output?

**Comment by jgm** [comment]
> the `::: {.cell .markdown id="6u8qXoeFGdqt"}` got modified into `::: {#6u8qXoeFGdqt .cell .markdown}`

This is because `#id` is our canonical syntax for identifiers.  Not a bug.

> The first set of headers are missing in the TOC

I'll look into this.

**Comment by jgm** [comment]
Here is the result of applying `makeSections` to this input.
```hs
[ Div
    ( "6u8qXoeFGdqt" , [ "cell" , "markdown" ] , [] )
    [ Div
        ( "summary" , [ "section" ] , [] )
        [ Header 1 ( "" , [] , [] ) [ Str "Summary" ]
        , BlockQuote
            [ Para
                [ Str "Expand"
                , Space
                , Str "to"
                , Space
                , Str "see"
                , Space
                , Str "summary"
                ]
            ]
        ]
    ]
, Div
    ( "details" , [ "section" ] , [] )
    [ Header 1 ( "" , [] , [] ) [ Str "Details" ] ]
]
```
`makeSections` provides the input to the function that creates the table of contents, so I record this here to aid diagnosis.

**Comment by jgm** [comment]
It's the double Div that is causing the problem.

**Comment by jgm** [comment]
I can't recall the reasoning on this, but there may have been an intentional decision not to include headers in Divs in the TOC, on the grounds that these are often asides or callouts.

**Comment by jgm** [comment]
Without the id attribute we get a single Div (and a TOC entry).
For an explanation of this behavior, see `makeSections` line 521:
```hs
    return $
      case inner of
            [Div divattr'@(dident',_,_) zs]
              | T.null dident || T.null dident' || dident == dident'
              -> Div (combineAttr divattr' divattr) zs : rest
            _ -> Div divattr inner : rest
```
In the original case the `inner` Div (an autogenerated section Div) has a different (autogenerated) id attribute than the enclosing one, so the guard fails and we get the double Div structure.  I believe the reason for this is that we need both identifiers (since either might be linked to). However, we could perhaps handle this case by moving the inner Div's identifier to the Header itself.

**Comment by wizlee** [comment]
> ... However, we could perhaps handle this case by moving the inner Div's identifier to the Header itself.

Thanks for the analysis so far! I am not familiar with Haskell so I am having difficulty reading the code and contributing directly.
To be frank, it only makes sense when I read the code with your explanation and needed much more time to read other relevant parts of the code. To others follow this conversation linked the [makeSections code here](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Shared.hs#L480). 


> This is because #id is our canonical syntax for identifiers. Not a bug.

Regarding this, will it cause problem later on when converting the markdown back to ipynb? I guess even if it did I can manually revert them or uses filter (which I am not familiar but should be able to hack one with time). However, if there's a workaround like enabling or disabling certain extensions that will be great.

**Comment by wizlee** [comment]
> Regarding this, will it cause problem later on when converting the markdown back to ipynb? I guess even if it did I can manually revert them or uses filter (which I am not familiar but should be able to hack one with time). However, if there's a workaround like enabling or disabling certain extensions that will be great.

I am testing your fix now by compiling pandoc from source. Is the fastest way compiling from source? My machine I am using now is quite ancient so are taking some time. I tried looking for a [published nightly build here](https://github.com/jgm/pandoc/actions/runs/3349318911/jobs/5549201195) but not able to find any.

**Comment by jgm** [comment]
> Regarding this, will it cause problem later on when converting the markdown back to ipynb?

No, it shouldn't.

>  Is the fastest way compiling from source? 

You can try a nightly build.  See actions -> nightly.
https://github.com/jgm/pandoc/actions/workflows/nightly.yml

**Comment by jgm** [comment]
By the way, I went with the second strategy above:

> we could tweak toTableOfContents so it can handle this double-Div structure.

**Comment by wizlee** [comment]
> You can try a nightly build. See actions -> nightly.
https://github.com/jgm/pandoc/actions/workflows/nightly.yml

The artifact for windows seems to be missing, maybe this is due to the final compilation failing for windows.
![image](https://user-images.githubusercontent.com/9842499/198814694-e55a9df6-8261-42ee-b421-e5487cd66916.png)

![image](https://user-images.githubusercontent.com/9842499/198814717-e9a3a214-a18c-4253-a5ad-3414c1fffb51.png)

**Comment by wizlee** [comment]
Update: 
- Completed compiling pandoc locally. 
- The TOC generation works now.
    - There are some other minor issues but I able able to quickly modify by hand now.
    - If the issues turned out to be valid will log a new issue.
- In the mean time, thanks for the quick fix!

**Comment by jgm** [comment]
Thanks for the heads-up about the nightly.
