### ISSUE TITLE
format control letter paper/ISO A4, pdf generation with -t ms

### ISSUE THREAD

**Issue by nbehrnd** [jgm/pandoc#8403]
I would like to convert some markdown files into .pdf.  Because the content does not contain illustrations, however snippets of code, e.g.

`# a principal header

This text is upright, or *italic*, may be **bold**, or contain some
`code`{.verbatim} in the line of question. Here and there, a snippet of
a language like Python e.g.,

``` python
for i in range(4):
    print(f"The counter is on {i}")
```

Words like Ägäis, öffentlich, üblich, école, polymères, août, garçon,
citroën, œil, cœur;`

the submission of the block above as file `minimal.md` to pandoc (2.19.2) in Linux Debian 12/bookworm with

```shell
pandoc minimal.md -o minimal.pdf -t ms
```

appears as suitable.

While `pdfinfo` (22.08.0) recognizes the .pdf written as created by groff (1.22.4), produced by ghostscript (9.56.1) in dimensions of US letter paper.

In addition to the functionality already provided, I would like to suggest a possibility to offer an export to ISO A4 which the current manual ([2022-08-22 Mon]) not yet mentions.

Alternatives ventured out so far to generate output in ISO A4 include:

+ based on the suggest on [stackoverflow](https://stackoverflow.com/questions/59594668/set-papersize-for-pandoc-with-pdfroff/59599709#59599709) 

```shell 
pandoc -V papersize=a4 --pdf-engine=pdfroff minimal.md -o minimal.pdf -t ms
```

+ based on the suggest on [issue 600](https://github.com/jgm/pandoc/issues/600) though addressing pdfLaTeX as pdf engine

```shell
pandoc --variable=geometry:a4paper minimal.md -o minimal.pdf -t ms
pandoc --variable=geometry:"a4paper" minimal.md -o minimal.pdf -t ms
pandoc -V geometry:a4paper minimal.md -o minimal.pdf -t ms
pandoc -V geometry:"a4paper" minimal.md -o minimal.pdf -t ms
pandoc -V papersize:"a4paper" minimal.md -o minimal.pdf -t ms
```
however the .pdf generated remains identified by `pdfinfo` as format `US letter paper`.

[minimal.md.zip](https://github.com/jgm/pandoc/files/9880730/minimal.md.zip)

**Comment by jgm** [comment]
OK, this seems to work:
```
pandoc -Vpapersize=a4 --pdf-engine-opt=-P-pa4 -t ms -o result.pdf
```
I will look into changing pandoc so that the `-P-pa4` is added automatically, but for now you can add it this way.

**Comment by jgm** [comment]
From `man groff`:
```
groff uses the command-line option -P
       to  pass  options to output devices; for example, the following selects
       A4 paper in landscape orientation for the PS device:

              groff -Tps -P-pa4 -P-l ...
```

**Comment by nbehrnd** [comment]
> I think what you're finding is that this isn't enough to produce an a4 pdf. Perhaps we also need special arguments for pdfroff.

I equally start to comprehend how the appearance may be tailored with the template files, too.  Thank you.
