### ISSUE TITLE
export to pdf with -ms, extension of sub/superscript indices

### ISSUE THREAD

**Issue by nbehrnd** [jgm/pandoc#8405]
Caveat:  I'm not sure if this can be adjusted in pandoc, or if addressing ghostcript were better.

For areas and volumes, I'm used to reach out for Alt + 2, or Alt + 3 to write e.g., 2 m², or 3 m³, respectively.  There is no apparent problem for pandoc to use such an input when generating a .pdf *via* groff

```shell
pandoc -Vpapersize=a4 --pdf-engine-opt=-P-pa4 -t ms -o result.pdf minimal.md
```

and want to suggest to extend the range available to `0123456789+-`.

It is observed the very same markdown input, e.g. as `test_unicode.md`

```
row 1: ? ? x² x³ ? ? ? ? ? ? ? ? ? ? ? ?

row 2: x⁰ xⁱ ? ? x⁴ x⁵ x⁶ x⁷ x⁸ x⁹ x⁺ x⁻ x⁼ x⁽ x⁾ xⁿ

row 3: x₀ x₁ x₂ x₃ x₄ x₅ x₆ x₇ x₈ x₉ x₊ x₋ x₌ x₍ x₎ ?

row 4: xₐ xₑ xₒ xₓ xₔ xₕ xₖ xₗ xₘ xₙ xₚ xₛ xₜ ? ? ?
```

yields a complete .pdf including the super/sub scripts when running 

```shell
$ pandoc -s test_unicode.md -o unicode_via_html.pdf -t html
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'test_unicode' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
Loading page (1/2)
Printing pages (2/2)                                               
Done                                                     
```

This contrasts to the initially intended approach with `-t ms`, where -- despite correct rendering of e.g., `äöüâé` -- only `x²` and `x³` pass well by the analogue request:

```shell
$ pandoc -Vpapersize=a4 --pdf-engine-opt=-P-pa4 -t ms test_unicode.md -o unicode_via_ms.pdf 
troff: <standard input>:108: warning: can't find special character 'u2070'
troff: <standard input>:108: warning: can't find special character 'u2071'
troff: <standard input>:110: warning: can't find special character 'u2074'
troff: <standard input>:110: warning: can't find special character 'u2075'
troff: <standard input>:110: warning: can't find special character 'u2076'
troff: <standard input>:110: warning: can't find special character 'u2077'
troff: <standard input>:110: warning: can't find special character 'u2078'
troff: <standard input>:110: warning: can't find special character 'u2079'
troff: <standard input>:110: warning: can't find special character 'u207A'
troff: <standard input>:110: warning: can't find special character 'u207B'
troff: <standard input>:110: warning: can't find special character 'u207C'
troff: <standard input>:110: warning: can't find special character 'u207D'
troff: <standard input>:110: warning: can't find special character 'u207E'
troff: <standard input>:110: warning: can't find special character 'u207F'
troff: <standard input>:112: warning: can't find special character 'u2080'
troff: <standard input>:112: warning: can't find special character 'u2081'
troff: <standard input>:112: warning: can't find special character 'u2082'
troff: <standard input>:112: warning: can't find special character 'u2083'
troff: <standard input>:112: warning: can't find special character 'u2084'
troff: <standard input>:112: warning: can't find special character 'u2085'
troff: <standard input>:112: warning: can't find special character 'u2086'
troff: <standard input>:112: warning: can't find special character 'u2087'
troff: <standard input>:112: warning: can't find special character 'u2088'
troff: <standard input>:112: warning: can't find special character 'u2089'
troff: <standard input>:112: warning: can't find special character 'u208A'
troff: <standard input>:112: warning: can't find special character 'u208B'
troff: <standard input>:112: warning: can't find special character 'u208C'
troff: <standard input>:112: warning: can't find special character 'u208D'
troff: <standard input>:112: warning: can't find special character 'u208E'
troff: <standard input>:114: warning: can't find special character 'u2090'
troff: <standard input>:114: warning: can't find special character 'u2091'
troff: <standard input>:114: warning: can't find special character 'u2092'
troff: <standard input>:114: warning: can't find special character 'u2093'
troff: <standard input>:114: warning: can't find special character 'u2094'
troff: <standard input>:114: warning: can't find special character 'u2095'
troff: <standard input>:114: warning: can't find special character 'u2096'
troff: <standard input>:114: warning: can't find special character 'u2097'
troff: <standard input>:114: warning: can't find special character 'u2098'
troff: <standard input>:114: warning: can't find special character 'u2099'
troff: <standard input>:114: warning: can't find special character 'u209A'
troff: <standard input>:114: warning: can't find special character 'u209B'
troff: <standard input>:114: warning: can't find special character 'u209C'
```

Their absentism equally is apparent when reading the .pdf e.g., with zathura (0.5.1), or atril (1.26.0).  So processing the very same input file may render the .pdf differently (only a few differences were marked):

![2022-10-28_pandoc_pdf_differences](https://user-images.githubusercontent.com/19709084/198605651-c9c62a60-1e98-4bfa-9581-ab145edb612b.png)

The sub- and superscripts were defined with the name schema the [Wikipedia entry](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Superscripts_and_subscripts_block) (left hand table) shows.  There was no call of any user defined  templates, the result is of only pandoc (2.19.2, .deb64 package obtained here from here); groff (1.22.4), and ghostscript (9.56.1) as provided by Linux Debian 12/bookworm (branch testing).  Because the primary aim is to use these as running indices, or to describe numerical ranges, in powers of ten, I suggest to provide access `0123456789+-` *outside* of an equation / math mode.

[2022-10-28_pandoc_pdf_differences.zip](https://github.com/jgm/pandoc/files/9888810/2022-10-28_pandoc_pdf_differences.zip)

**Comment by jgm** [comment]
The problem is just that the font being used by groff lacks glyphs for these characters.

I have not figured out how to use pdfroff with arbitrary fonts.  However, I did find this, which tells you how to convert a truetype font for use with groff:
https://docs.freebsd.org/doc/3.3-RELEASE/usr/share/doc/en/articles/fonts/c348.html
Let me know if you have any success.

**Comment by nbehrnd** [comment]
The concept suggested bears similarities to installing a font from the TeXCollection DVD/CTAN for LaTeX.  Additonal experimentation is required to achieve the wanted output.

The topic is appealing enough that e.g., Kurt Bond posted twice about the matter, [groff and install-font.sh and installing fonts for use in groff](https://tkurtbond.github.io/posts/2021/07/17/groff-and-install-fontsh-and-installing-fonts-for-use-in-groff/) ([2021-07-17 Sat 00:16], about Cormorant Garamond), and [install-font.sh - The simple approach](https://tkurtbond.github.io/posts/2021/07/17/install-fontsh-the-simple-approach/) ([2021-07-17 Sat 15:36], on the example of Lora).  The second was written after exchange with Peter Schafter providing an assisting shell script ([install-font.sh](https://www.schaffter.ca/mom/mom-06.html#install-font)).  In addition to the font file and this script, the freely available program [fontforge](https://en.wikipedia.org/wiki/FontForge) is necessary; Peter Schafter's script interacts with it in the background.

At first, I went to replicate the brief [video tutorial](https://www.youtube.com/watch?v=CzUHjtGBdZs) by Gavin Freeborn with a showcase for Donald Knuth's computer modern, regular/Roman font.  He eventually tests the installation with along the lines of input file `demo.ms` with groff

```
.fam cm \" set font family
.ft R \" set font type
Computer Modern:  Hello World
```

by 

```shell
groff -ms -Tpdf  demo.ms > demo.pdf
```

While this renders a new font available, it does not solve (yet) the question of the indices.  For my set up, Kurt Bond's second post about Lora is then easier because it is copying Schafter's script into the decompressed archive and run e.g., 

```shell
sudo bash ./install-font.sh -s Lora-BoldItalic.ttf 
```

and answer the relevant questions.  Early testing with support for utf-8

```shell
groff -ms -Kutf8 Tpdf  demo.ms > demo.pdf
```

however shows that neither one of the fonts is fully responsive to the Unicode definitions issued, and further search is necessary.

[2022-10-28_pandoc_ms_font_testing.zip](https://github.com/jgm/pandoc/files/9891463/2022-10-28_pandoc_ms_font_testing.zip)
