### ISSUE TITLE
OpenDocument file is only halfway converted

### ISSUE THREAD

**Issue by albbas** [jgm/pandoc#8409]
Only the text in the upper table is converted, the main part of the document is omitted. When I saved the file as a docx file (using LibreOffice), and converted that, the complete text appeared.

I tried converting the document like this: `pandoc aid_pressemelding_oversettelsesversjon.odt`
The Try pandoc site produced the same output.

pandoc version: 2.19.2, on Ubuntu 22.10

[aid_pressemelding_oversettelsesversjon.odt](https://github.com/jgm/pandoc/files/9910716/aid_pressemelding_oversettelsesversjon.odt)
[aid_pressemelding_oversettelsesversjon.docx](https://github.com/jgm/pandoc/files/9910720/aid_pressemelding_oversettelsesversjon.docx)

I have a bunch of other odt-files, and the conversion worked well on them.

**Comment by jgm** [comment]
I believe the problem is that this content is embedded in a text:section element, which the ODT reader doesn't seem to handle.  We need to add support for this to Text.Pandoc.Readers.ODT.ContentReader.
