### ISSUE TITLE
documents which default file keys cannot be specified in yaml metadata block

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#8413]
It seems like some keys allowed in defaults files are not read from the metadata block. The defaults files are documented extensively in the MANUAL, I think it would be useful to document what are read from the metadata block too.

Here are some example keys valid in defaults files but not read in YAML metadata block:

- css
- file-scope
- filters
- from
- mathjax
- number-sections
- pdf-engine
- top-level-division
- wrap

I guess one possible way to do it is to gather the doc of defaults files from MANUAL in a single YAML file, then using `pandoc --metadata-file=defaults.yaml -s -o dafaults.md` would produce a markdown file with a metadata block that has those unrecognized keys removed. So the diff in the keys would tell what are valid in metadata block or not.

**Comment by jgm** [comment]
As documented in the manual, metadata values are used to populate template variables. That's it.  **There are *no* metadata values that duplicate command line options.**  In some formats, a particular option might be implemented by just setting a template variable to trigger something in the template. But this is an implementation detail and not something you should rely on.

**Comment by ickc** [comment]
I think the documentation on this matter is unclear and scattered around.

E.g. take csl, the doc gave an example of `metadata:  csl: ieee.csl` in defaults file would work (as functionally equiv. to `--csl ieee.csl` on the cli), which seems to suggest in the YAML metadata block if one uses `csl: ieee.csl` it would works too. And empirically it seems to work in my test.

But may be I am misunderstanding, I don't see how `csl` as metadata would be used in template variables.

Following the same speculation, then may be `bibliography` and `citation-abbreviations` would have this behavior too.

**Comment by ickc** [comment]
Note to self: those 3 keys works in this way probably because `--citeproc` behave more like a filter, and that filter reads the "args" from the metadata. So the "pure pandoc" program still expects metadata as just template variables.

**Comment by jgm** [comment]
`--csl` simply adds `csl` to metadata, and `--bibliography` adds `bibliography`. So those are perhaps the exceptions.
We had to do it this way when pandoc-citeproc was a separate JSON filter, as it was the only way to communicate this information to pandoc-citeproc.  We wouldn't need to do it that way with `--citeproc`, but I kept it to avoid unnecessary breakage.
