### ISSUE TITLE
setting toc in YAML metadata block does nothing to HTML output

### ISSUE THREAD

**Issue by ickc** [jgm/pandoc#8414]
Create some headings with toc set to true:

```markdown
---
toc: true
...

# Testing TOC

avcabfagdsf

## 2nd level

sfgasdhguy
```

Then the following commands has a different outcome:

```bash
pandoc -s -o temp.html temp.md
pandoc -s -o temp.html temp.md --toc
```

The expectation is for pandoc recognize the toc metadata same as specifying `--toc`.

Reading the doc at [Pandoc - Pandoc User’s Guide](https://pandoc.org/MANUAL.html#variables-for-latex) however, it explicitly stated that `toc` is a "Variables for LaTeX". So this is not really a bug, but more like a feature request.

May relates to #8413.

**Comment by jgm** [comment]
Right, it's not a bug.  You can find a number of discussions of this in closed issues.
Metadata is for metadata, not processing instructions.  Use a defaults file for that.
