### ISSUE TITLE
Better error message when trying to use output-only format for input

### ISSUE THREAD

**Issue by lassik** [jgm/pandoc#8416]
**Describe your proposed improvement and the problem it solves.**

```
$ pandoc hello.adoc -t hello.html
Unknown input format asciidoc
```

Pandoc can write asciidoc, but cannot read it. It's confusing that the error message says the asciidoc format is "unknown" to pandoc. Could the message be altered to say "asciidoc is supported only as an output format, not for input" or something similar?

**Describe alternatives you've considered.**

Leave the error message as is.

**Comment by foursixnine** [comment]
I just created: https://github.com/jgm/pandoc/pull/10492 to improve the error message
