### ISSUE TITLE
Architectural change in ScriptingEngine

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#8417]
Suggestion:  Instead of the current interface
```hs
  , engineReadCustom :: forall m. (PandocMonad m, MonadIO m)
                     => FilePath -> m (Reader m, ExtensionsConfig)
    -- ^ Function to parse input into a 'Pandoc' document.

  , engineWriteCustom :: forall m. (PandocMonad m, MonadIO m)
                      => FilePath
                      -> m (Writer m, ExtensionsConfig, m (Template Text))
```
what about something like
```hs
  , engineLoadScript :: forall m . (PandocMonad m, MonadIO m)
       => FilePath -> m (ScriptComponents m)
```
where
```hs
data ScriptComponents m =
  ScriptComponents
  { scriptCustomReader :: Maybe (Reader m)
  , scriptCustomWriter :: Maybe (Writer m)
  , scriptTemplate :: Maybe Text  -- or Maybe (Template Text), depending on that decision
  , scriptExtensions :: Maybe ExtensionsConfig
  }
```

This would make things nicer for implementing `-D script.lua`, since we wouldn't need to try to read it as a reader and then again as a writer if that fails.  Similarly for implementing `--list-extensions script.lua`.

Also, I just realized that the current architecture for custom readers and writers makes it possible to combine a reader and writer in a single script (or am I wrong)?  Maybe this should be noted in the documentation.

@tarleb comments?

**Comment by tarleb** [comment]
That's elegant. I'm not sure yet, but I think I like this.

**Comment by jgm** [comment]
Alternatively we could have
```hs
data ScriptComponents =
  ScriptComponents
  { scriptCustomReader :: forall m. (PandocMonad m, MonadIO m) => Maybe (Reader m)
  , scriptCustomWriter :: forall m. (PandocMonad m, MonadIO m) => Maybe (Writer m)
  , scriptTemplate :: Maybe Text  -- or Maybe (Template Text), depending on that decision
  , scriptExtensions :: Maybe ExtensionsConfig
  }
```
Are there reasons to go one way or the other here?

**Comment by tarleb** [comment]
The parameterized version `data ScriptComponents m` seems a little nicer to me, but don't feel strongly about it.
