### ISSUE TITLE
CORS support in pandoc-server

### ISSUE THREAD

**Issue by mcdemarco** [jgm/pandoc#8427]
Pandoc-server lacks CORS support.  This is a bigger issue with the self-contained server than with the CGI version, since the CGI version can in principle run on the same webserver as the page making the request (making it not cross-origin), or possibly the webserver itself could add appropriate CORS headers.  But because the freestanding server will always be at least on a different port than the requesting page, requests to it will always be cross-origin, and fail a CORS check.

Most workarounds for CORS issues also fail because pandoc-server also does not respond to CORS preflight requests (OPTIONS).   However I did find one way to access pandoc-server cross-origin:  [starting Chrome with web security disabled](https://stackoverflow.com/a/58541689).

My request was a javascript fetch (POST) with headers `Accept: text/plain` and `Content-Type: application/json`.  My pandoc parameters varied, but all succeeded against a local CGI pandoc-server or from Chrome with no web security.

Here is an issue in another project about adding CORS support to a similar server:  https://github.com/haskell-servant/servant-swagger/issues/45

My pandoc version is 2.19.2 on MacOS 12.6.

**Comment by jgm** [comment]
Looks like the key point is
```hs
import Network.Wai.Middleware.Cors (simpleCors)

...
main = run port $ simpleCors $ app
```

**Comment by jgm** [comment]
I think I've now addressed this; try a nightly after tonight and let me know if it doesn't work.

**Comment by mcdemarco** [comment]
I'm getting the preflight response now, but the actual request is still blocked by CORS, probably for the reason described in [this comment](https://github.com/haskell-servant/servant-swagger/issues/45#issuecomment-234293401) from the other issue:  application/json is not one of the "simple" CORS content-types, so content-type needs to be added to the policy.  (Application/json seems to be required by pandoc-server for the conversion end point.)

Another thing about the simple policy is that it accepts all origins:

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST
```

Ideally for security there'd be some way to pass a more restricted origin list into pandoc-server, but I don't personally need that.  I'm not sure what would come security-wise of accepting all incoming content-types (or whether the code linked above actually does that); pandoc-server seems pretty picky about the wrong contents right now so maybe it would go on rejecting unwanted content-types regardless.

**Comment by jgm** [comment]
I will try the code in that comment.  In principle it's possible to specify a list of origins
https://hackage.haskell.org/package/wai-cors-0.2.7/docs/Network-Wai-Middleware-Cors.html
but we'd need a way to pass it in to pandoc-server, e.g. a new command-line argument.
Maybe best to keep it simple for now.

**Comment by jgm** [comment]
I've pushed the fix, please try it out. I don't know much about CORS.

**Comment by mcdemarco** [comment]
That did the trick, thank you!
