### ISSUE TITLE
Captions also below tables 

### ISSUE THREAD

**Issue by oliverguhr** [jgm/pandoc#8430]
Hello,
I am struggling to put my captions below the table. No matter where I place the caption in the markdown code, it will be rendered above the table. For academic writing, at least here in Germany putting the caption below the table is standard.

It looks like the placement of the caption has been hard coded to be above the table, as discussed in this [issue](https://github.com/jgm/pandoc/issues/138).

Is there any way to change this with pandoc or with latex format options?

Thanks a lot.

**Comment by oliverguhr** [comment]
Yes - #5116 could be a solution to this problem.

**Comment by tarleb** [comment]
Closing in favor of #5116.
