### ISSUE TITLE
Pandoc 2.19 epubs don't work on Kobo device

### ISSUE THREAD

**Issue by Zash** [jgm/pandoc#8435]
Starting with pandoc 2.19, epub files created with e.g. `echo hello | pandoc -f markdown -t epub -o hello.epub` don't work on my Kobo H2O device. When opening one, a single blank page is shown. In listings, title and author are shown with a black square as thumbnail.

Debian 11 using `pandoc-*-amd64.deb` from the Github releases page.

Apologies for the "screenshot", showing the results of my early attempt at bisect (by installing a different `.deb` and generating a new `.epub`):

![5f6fd8a6_lzLMlh76QF-_2MxeAD8Ijg](https://user-images.githubusercontent.com/197474/201385707-540c3529-a59c-497c-8456-b18ad55da6a9.jpg)

Unpacking the zip-epubs I observe that the main differences between 0.18 and 0.19 seems to be CSS, so I will investigate into whether reverting or removing any specific rule affects anything.

**Comment by jgm** [comment]
OK, let us know what you discover. It would also be worth running epubcheck on the epub.

**Comment by jgm** [comment]
See #8379 - I'm pretty sure it's the same issue.
In that case it has been fixed in master.
3666d79ae776ce4839262c9f9cbb9d76471d2eb0

**Comment by Zash** [comment]
Indeed, replacing those CSS flex bits appears to fix it, so a duplicate of https://github.com/jgm/pandoc/issues/8379 it is! Thanks for the quick response and sorry about the noise (especially the screen ... photo). I suppose I only looked at open issues, hence missing that one.
