### ISSUE TITLE
figcaptions with roman numerals interpreted as list markers 

### ISSUE THREAD

**Issue by gmccullo** [jgm/pandoc#8436]
Compiling markdown to epub. This markup:

```md
<figure class="borders">
<img src="Draco.png" />
<figcaption>II. Draco</figcaption>
</figure>
```

outputs this:

```html
<figure class="borders">
<img src="../media/file77.png" />
<figcaption>
<ol start="2" type="I">
<li>Draco
</figcaption>
</figure></li>
</ol>
```
This is both incorrect and invalid (overlapping tags). It should not be generating an unordered list at all. It should never under any circumstances generate invalid HTML.

If I remove the dot after "II" the output is OK. "III." or "IV." or "V." also has the same problem. However "I." does not.

Pandoc version:
```
pandoc.exe 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```

**Comment by jgm** [comment]
Pandoc's markdown includes the `markdown_in_html_blocks` extension.  That is why `II. Draco` is parsed as an ordered list.

A couple simple workarounds: 

1. Backslash-escape the period after `II` to defeat parsing as a list.
2. Disable the `markdown_in_html_blocks` extension:  `pandoc -f markdown-markdown_in_html_blocks`
3. (Preferred:) Use the "raw attribute" to indicate that this whole chunk of raw HTML is to be parsed as raw HTML, as a single unit:

````
```{=html}
<figure class="borders">
<img src="../media/file77.png" />
<figcaption>
<ol start="2" type="I">
<li>Draco
</figcaption>
</figure></li>
</ol>
```
````

As for invalid HTML: this is a consequence of the combination of (a) tag-level parsing of raw HTML and (b) allowing markdown inside HTML.  But the bottom line is that you should do one of the three things mentioned above.

**Comment by gmccullo** [comment]
Here's a test:

Input:

```md
<figure class="borders">
<img src="Draco.png" />
<figcaption>II. Draco</figcaption>
</figure>

<figure class="borders">
<img src="Draco.png" />
<figcaption>II\. Draco</figcaption>
</figure>

<figure class="borders">
<img src="Draco.png" />
<figcaption>
II. Draco
</figcaption>
</figure>

<figure class="borders">
<img src="Draco.png" />
<figcaption>
II\. Draco
</figcaption>
</figure>
```

Output (formatting added for readability):

```html
<figure class="borders">
	<img src="../media/file0.png" />
	<figcaption>
		<ol start="2" type="I">
			<li>Draco
	</figcaption>
</figure>
</li>
</ol>

<figure class="borders">
	<img src="../media/file0.png" />
	<figcaption>
		II. Draco
	</figcaption>
</figure>

<figure class="borders">
	<img src="../media/file0.png" />
	<figcaption>
		<ol start="2" type="I">
			<li>Draco</li>
		</ol>
	</figcaption>
</figure>

<figure class="borders">
	<img src="../media/file0.png" />
	<figcaption>
		II. Draco
	</figcaption>
</figure>
```

Only #1 produces invalid HTML. This should not be acceptable.

**Comment by tarleb** [comment]
I believe that everything here behaves as documented, so I'm closing this.

**Comment by gmccullo** [comment]
How can emitting invalid html not be considered a bug?

**Comment by jgm** [comment]
There is no way to guarantee that valid HTML will be emitted when raw HTML is allowed in markdown.  I could, for example, write

```
<p>
hello
</li>
```

If you do use raw HTML, then you need to understand how pandoc handles it, given the markdown extensions that are enabled, and take steps to avoid invalid output.  (I've outlined several ways to do that above.)

If you don't use raw HTML, then you can be sure that the output will be valid HTML.

**Comment by jgm** [comment]
I think we could probably tweak our parsing algorithm to give less surprising results in cases like this.  Where tags are used that *must* have a closing tag, we could keep a stack of open tags and stop markdown parsing when we hit a corresponding closing tag. We do something like this already for `<div>` to support `native_divs`.  But this won't avoid all such cases, because many HTML elements don't need to be closed.  And it would add a lot of extra complexity and probably cause new problems elsewhere.

In general, I think that the original Markdown idea of just letting raw HTML be included anywhere was not a good one, and I would like to transition to explicitly marked raw elements (`raw_attribute` extension).  So, given all the workarounds for this issue, I'm not inclined to put time into it now.

**Comment by gmccullo** [comment]
I would argue that if the input is valid, the output must be valid; if the input is invalid then throw an error rather than emit invalid output. Other ideas: have an option to enforce strict on html so all tags just be closed. Using html in markdown is important, and it's part of the spec: I wouldn't like to see custom pandoc code in the markup just to make html work. (Not sure if that's what you're suggesting.)

**Comment by gmccullo** [comment]
Here's a test with ```markdown_strict```: 

Input:

```md
<a id="party-map"></a><figure class="bottommargin">

![](party-map.png)

<figcaption>The Four Great Realms Of Quasisubstantial Space</figcaption>

</figure>
```
Output:
```html
<p><a id="party-map"></a><figure class="bottommargin"></p>
<p><img src="../media/file0.png" /></p>
<figcaption>The Four Great Realms Of Quasisubstantial Space</figcaption>
</figure>
```
Notice the overlapping ```figure``` and ```p``` tags. 

But this is fine using regular ```--from markdown```

**Comment by jgm** [comment]
`markdown_strict` follows Gruber's original specification, which states that HTML blocks must begin and end at the left margin and be separated from surrounding content by blanks:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

So,
```
<a id="party-map"></a>

<figure class="bottommargin">

![](party-map.png)

<figcaption>The Four Great Realms Of Quasisubstantial Space</figcaption>

</figure>
```
But of course, in Gruber's version (and with `mardkown_strict`) the contents of the block are *not* parsed as Markdown.

**Comment by gmccullo** [comment]
Either you edited your comment while I was replying or I can't read, but OK.

To sum up: 

1. I would love to use CommonMark (it's what I write in in vscode) except that an extension I want is unsupported.

2. The main issue here for me is that invalid HTML should never be emitted. _Throw an error._ Tracking down these invalid mark-ups is really a pain in the patoot, as granny used to say. I understand that parsing is hard — trust me: I had to write an HTML parser for work and I thought I'd lose my mind. My thought is that a way to make it feasible might be to have a strict option of some kind which would require all HTML tags to be closed (attributes to have quoted values, etc.). When that option is enabled then when the parser encounters a mismatched closing tag (the closing tag doesn't match the tag on the stack) it stops and throws.

**Comment by jgm** [comment]
This isn't going to happen in pandoc, but you can easily pipe the output through a validator of some kind if you want that check.

**Comment by gmccullo** [comment]
What are the prospects for making more extensions support CommonMark?

**Comment by jgm** [comment]
It will happen eventually.  It's just a matter of time constraints. There are a number of open issues for extensions at jgm/commonmark-hs.
