### ISSUE TITLE
Straight quotes are not converted to curly quotes in bibliographies 

### ISSUE THREAD

**Issue by TomBener** [jgm/pandoc#8441]
I was trying to convert Markdown to Word document with Pandoc 2.19.2 on macOS Ventura 13.0.1.

The cited content in `main.md`:

```markdown
Cite an article with straight quotes [@aguilera2014].
```

And the content of `@aguilera2014` in BibTeX file named `bibliography.bib`:

```bibtex
@article{aguilera2014,
  author = {Aguilera, Roberto F. and Radetzki, Marian},
  title = {The Shale Revolution: Global Gas and Oil Markets "Under Transformation"},
  journal = {Mineral Economics},
  volume = {26},
  number = {3},
  pages = {75-84},
  date = {2014-01-01},
  doi = {10.1007/s13563-013-0042-4},
}
```

Then run the command:

```shell
pandoc --citeproc --bibliography bibliography.bib main.md --output main.docx
```

The generated bibliography in the Word document:

```
Aguilera, Roberto F., and Marian Radetzki. 2014. “The Shale Revolution: Global Gas and Oil Markets "Under Transformation".” Mineral Economics 26 (3): 75–84. https://doi.org/10.1007/s13563-013-0042-4.
```

Here `"Under Transformation"` is unexpected, instead curly quotes are desired.

I also tried to add the APA CSL file, but it remained the same issue. Later I came up a workaround to resolve it by converting straight quotes to curly quotes before the conversion:

```shell
cat bibliography.bib | pandoc --wrap=preserve -t markdown-smart > bib.bib
```

However, this method has a side effect as it will escape special symbols like `[ ]`, which could destruct the content.

What I expect are:

1.  The straight quotes can be converted to curly quotes in the bibliography properly.
2. It’d be better to have an extension *only* convert straight quotes to curly quotes, instead of the current `smart` extension.

**Comment by tarleb** [comment]
Pandoc doesn't apply "smart quotes" to LaTeX input the way it does in Markdown, which is why the straight quotes are passed through verbatim. Use LaTeX syntax to get curly quotes:

``` biblatex
@article{aguilera2014,
  author = {Aguilera, Roberto F. and Radetzki, Marian},
  title = {The Shale Revolution: Global Gas and Oil Markets ``Under Transformation''},
  journal = {Mineral Economics},
  volume = {26},
  number = {3},
  pages = {75-84},
  date = {2014-01-01},
  doi = {10.1007/s13563-013-0042-4},
}
```

**Comment by jgm** [comment]
PS.  Use unicode curlies, or
```
``this style''
```

**Comment by TomBener** [comment]
Thanks! This works well.

However, considering that BibTeX file is not _only_ used for LaTeX. Instead, Word document can also be combined with BibTeX. Is it possible to convert straight quotes to general curly quotes when Pandoc detects that the output is not LaTeX?

My BibTeX file is exported by [Better BibTeX for Zotero](https://github.com/retorquere/zotero-better-bibtex), and I don’t want to edit it manually. It would be very convenient if Pandoc could convert to curly quotes `“” ‘’` when using BibTeX with DOCX.

**Comment by jgm** [comment]
If you don't like working with BibTeX, you could always export CSL JSON from Zotero...
Or you could use a markdown YAML bibliography.

**Comment by TomBener** [comment]
@jgm Thanks for your suggestion.

I have worked much with BibTeX, switching to CSL JSON is not preferable. And the `.bib` file is a big database containing all my references and also used for importing literature notes in [Obsidian](https://github.com/hans/obsidian-citation-plugin).

Following your guide, I will convert straight quotes to LaTeX-style quotes before conversion manually or on the command line.

Thanks again!

**Comment by TomBener** [comment]
> If you don't like working with BibTeX, you could always export CSL JSON from Zotero...
> Or you could use a markdown YAML bibliography.

Thanks for your suggestions. I'd like to know how to use CSL JSON in LaTeX? I converted Markdown to LaTeX without preamble, and then import it to a custom `main.tex` with the `\input{input.tex}` command. Is it possible to use CSL JSON directly in LaTeX (BibTeX or BibLaTeX)? Thanks in advance.
