### ISSUE TITLE
Strip out HTML comments completely in Markdown

### ISSUE THREAD

**Issue by TomBener** [jgm/pandoc#8443]
Pandoc version:

```
$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /Users/username/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Pandoc currently has an option `--strip-comments` to strip out HTML comments in the Markdown or Textile source. However, If HTML comments are within the paragraph, it will lead to an extra space.

4 lines source in Markdown named `test.md`:

```markdown
Some texts in Markdown,
<!-- this is a html comment in a new line -->
And another line of text.
End of the example.
```

Run the command:

```shell
pandoc --strip-comments test.md -o test.docx
```

The output in `test.docx`:

```
Some texts in Markdown,  And another line of text. End of the example.
```

It is noteworthy there are two spaces between `Markdown,` and `And`, which is not expected.

Trying to convert `test.md` to the native format:

```shell
pandoc --strip-comments -t native test.md
```

The output is like:

```
[ Para
    [ Str "Some"
    , Space
    , Str "texts"
    , Space
    , Str "in"
    , Space
    , Str "Markdown,"
    , SoftBreak
    , RawInline (Format "html") ""
    , SoftBreak
    , Str "And"
    , Space
    , Str "another"
    , Space
    , Str "line"
    , Space
    , Str "of"
    , Space
    , Str "text."
    , SoftBreak
    , Str "End"
    , Space
    , Str "of"
    , Space
    , Str "the"
    , Space
    , Str "example."
    ]
]
```

The HTML comment is still remained here.

I wonder is there any way to remove the HTML comments completely (including the line break symbol) to avoid an extra space between words? Thanks in advance.

**Comment by jgm** [comment]
You could use a Lua filter to search for these empty RawInline elements and remove a SoftBreak or Space immediately after.

**Comment by TomBener** [comment]
Sorry I have no idea how to write a Lua filter, could you please help me with that? @jgm

**Comment by jgm** [comment]
https://pandoc.org/lua-filters.html
and if you have questions, please ask on pandoc-discuss mailing list, not on the bug tracker.

**Comment by TomBener** [comment]
With the help of an [example](https://pandoc.org/lua-filters.html#remove-spaces-before-citations) in the page, I tried to write a Lua filter. It strips out the softbreak after the html comment, which can remove an extra space: 

```lua
local function strip_html_comments(ril, sob)
  return ril and ril.t == 'RawInline'
      and sob and sob.t == 'SoftBreak'
end

function Inlines(inlines)
  for i = #inlines - 1, 1, -1 do
    if strip_html_comments(inlines[i], inlines[i + 1]) then
      inlines:remove(i + 1)
    end
  end
  return inlines
end
```

Save it as `shsc.lua`, and use it as following:

```shell
pandoc --strip-comments -L shsc.lua -t native test.md
```

The output:

```
[ Para
    [ Str "Some"
    , Space
    , Str "texts"
    , Space
    , Str "in"
    , Space
    , Str "Markdown,"
    , SoftBreak
    , RawInline (Format "html") ""
    , Str "And"
    , Space
    , Str "another"
    , Space
    , Str "line"
    , Space
    , Str "of"
    , Space
    , Str "text."
    , SoftBreak
    , Str "End"
    , Space
    , Str "of"
    , Space
    , Str "the"
    , Space
    , Str "example."
    ]
]
```

For the `.docx` output, the option `--strip-comments` can be omitted.

Thanks again! @jgm
