### ISSUE TITLE
--embed-resources removes empty attribute values

### ISSUE THREAD

**Issue by khaveesh** [jgm/pandoc#8445]
Test case:

```
- [ ] test
```

Pandoc without `--embed-resources`:

```
<ul class="task-list">
<li><input type="checkbox" disabled="" />test</li>
</ul>
```

Pandoc with `--embed-resources`:

```
<ul class="task-list">
<li><input type="checkbox" disabled></input>test</li>
</ul>
```

The empty attribute value for disabled is being removed. This causes the following error in Safari: `Specification mandates value for attribute disabled`.

Happens with other attributes as well. For example:

```
[]{test=""}
```
produces `<p><span data-test></span></p>`

**Pandoc version?**
Both pandoc 2.19.2 on macOS & <https://pandoc.org/try>

**Comment by jgm** [comment]
Unfortunately this seems a feature of the tagsoup library which we use for parsing and rendering in the SelfContained module:
```hs
> renderTags $ parseTags "<input disabled=\"\"/>"
"<input disabled></input>"
```

It seems that this is valid HTML5:

https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

> The value is implicitly the empty string.

Are you using some other doctype?

**Comment by khaveesh** [comment]
The Safari error occurs if the file is saved with `xhtml` extension. No errors with `html` extension. It may be beneficial to stick to the stricter semantics of XML, like pandoc does for the non `--embed-resources` case.

**Comment by jgm** [comment]
The tagsoup library is for HTML5. We'd have to switch to something else.
A strict XML parser wouldn't be appropriate either, because we have to be able to handle non-XML HTML.

**Comment by khaveesh** [comment]
I have switched to producing non-standalone HTML documents in order to workaround this issue. Please close this issue if you feel it is out of scope.
