### ISSUE TITLE
Support for LaTeX \part*  (unnumbered)?

### ISSUE THREAD

**Issue by Iacobus1983** [jgm/pandoc#8447]
If I convert from LaTeX e.g. `\chapter*{My Title}`, or any lower section command in its starred form, I get an unnumbered heading. This seems not to happen with `\part*`. 

I wonder if there is a reason for such behavior, and, in case there isn't, if it could be implemented.

**Comment by jgm** [comment]
We don't really have a good structure into which to convert "parts."

With chapter we'll use a level-1 heading, because pandoc knows to treat these as chapters in books.

**Comment by Iacobus1983** [comment]
Thank you very much for replying. I see. I suppose that converting `\part` into `h1`, and then `\chapter`into `h2` is not convenient because in this case an epub splitted at chapter level would have html files starting with a `h2`. 

Still I don't see why dropping the "unnumbered" feature for `\part*`, which would be useful in some case. But I imagine that you know much better.

**Comment by jgm** [comment]
Yes, I think we could add the 'unnumbered' feature.
