### ISSUE TITLE
Unexpected handling of abbreviations

### ISSUE THREAD

**Issue by s1n** [jgm/pandoc#8450]
**Explain the problem.**
I am not entirely sure this is a bug but it definitely doesn't seem right and results in unexpected conversions some times. When converting Markdown to native, I found that pandoc produced an unusual `Str` concatenated element for certain strings.

```
Ltd. Hello Ltr. World e.g. Wat i.e. Huh g.t. wat?
```

results in the following native:

```
[ Para
    [ Str "Ltd.\160Hello"
    , Space
    , Str "Ltr."
    , Space
    , Str "World"
    , Space
    , Str "e.g.\160Wat"
    , Space
    , Str "i.e.\160Huh"
    , Space
    , Str "g.t."
    , Space
    , Str "wat?"
    ]
]
```

I haven't been able to determine what causes the usage of nested `\160`, it seems to only follow specific well known abbreviations. When I tested the exact same input on the Markdown-it online tester, it resulted in a normal string:

```
[
  {
    "type": "paragraph_open",
    "tag": "p",
    "attrs": null,
    "map": [
      0,
      1
    ],
    "nesting": 1,
    "level": 0,
    "children": null,
    "content": "",
    "markup": "",
    "info": "",
    "meta": null,
    "block": true,
    "hidden": false
  },
  {
    "type": "inline",
    "tag": "",
    "attrs": null,
    "map": [
      0,
      1
    ],
    "nesting": 0,
    "level": 1,
    "children": [
      {
        "type": "text",
        "tag": "",
        "attrs": null,
        "map": null,
        "nesting": 0,
        "level": 0,
        "children": null,
        "content": "Ltd. Hello Ltr. World e.g. Wat i.e. Huh g.t. wat?",
        "markup": "",
        "info": "",
        "meta": null,
        "block": false,
        "hidden": false
      }
    ],
    "content": "Ltd. Hello Ltr. World e.g. Wat i.e. Huh g.t. wat?",
    "markup": "",
    "info": "",
    "meta": null,
    "block": true,
    "hidden": false
  },
  {
    "type": "paragraph_close",
    "tag": "p",
    "attrs": null,
    "map": null,
    "nesting": -1,
    "level": 0,
    "children": null,
    "content": "",
    "markup": "",
    "info": "",
    "meta": null,
    "block": true,
    "hidden": false
  }
]
```

Note the string is a single block of content with no special spans or block treatment. I looked around and couldn't determine what would trigger this handling for only some strings like this. I checked the CommonMark and GFM specs and didn't see anything that should trigger this. The closest I've found are filters to handle abbreviations, such as [scokobro/pandoc-abbreviations](https://github.com/scokobro/pandoc-abbreviations).

Is this a bug, some weird edge case, or totally normal?

**Pandoc version?**
pandoc web tester (pandoc version 2.19.2)

**Comment by tarleb** [comment]
The [section about `--abbreviations`](https://pandoc.org/MANUAL.html#option--abbreviations) in pandoc's manual explains what's going on:

> **`--abbreviations=`_FILE_**
>
> Specifies a custom abbreviations file, with abbreviations one to a line. If this option is not specified, pandoc will read the data file abbreviations from the user data directory or fall back on a system default. To see the system default, use pandoc --print-default-data-file=abbreviations. The only use pandoc makes of this list is in the Markdown reader. Strings found in this list will be followed by a nonbreaking space, and the period will not produce sentence-ending space in formats like LaTeX. The strings may not contain spaces.

The easiest way to work around this is to call pandoc with `--abbreviations=/dev/null`.

**Comment by jgm** [comment]
This is designed to ensure good typography:  no line breaks after abbreviations, and no sentence-ending space after abbreviations.

**Comment by jgm** [comment]
You can always backslash-escape the period if you don't want this behavior in particular case.

As an alternative to `--abbreviations=/dev/null` on the command line, you could put an empty file called `abbreviations` in your pandoc user data directory.  (`pandoc --version` will tell you where this is, you may need to create it.)
