### ISSUE TITLE
pandoc 2.19.2 failed to build on arm Ventura

### ISSUE THREAD

**Issue by chenrui333** [jgm/pandoc#8457]
**Explain the problem.**
pandoc 2.19.2 failed to build on arm Ventura

```
packages invalid due to build failure: prtty-shw-1.10-28a981e9
CallStack (from HasCallStack):
  withMetadata, called at src/Distribution/Simple/Utils.hs:370:14 in Cbl-3.8.1.0-812b3c73:Distribution.Simple.Utils
Error: cabal: Failed to build pandoc-2.19.2 because it depends on
pandoc-2.19.2 which itself failed to build.
Failed to build pandoc-2.19.2 because it depends on pandoc-2.19.2 which itself
failed to build.
Failed to build prtty-shw-1.10-28a981e9. The build process segfaulted (i.e.
SIGSEGV).
```

**Pandoc version?**
pandoc 2.19.2
macOS: arm_ventura

full build log in here, https://gist.github.com/e4f56e29b853fa2ccf7e7c5345cd4c51
Server build log, https://github.com/Homebrew/homebrew-core/actions/runs/3561508444/jobs/5982478382

**Comment by jgm** [comment]
See https://gitlab.haskell.org/ghc/ghc/-/issues/21964

This is fixed in ghc 9.2.5.  homebrew should use that instead of 9.2.4. See
https://www.haskell.org/ghc/blog/20221107-ghc-9.2.5-released.html

Since this is not really a pandoc issue, I'll close this.
