### ISSUE TITLE
Support Internal Links for markdown

### ISSUE THREAD

**Issue by amarbota** [jgm/pandoc#8461]
## Use-case

Currently using obsidian to write my notes, instructions in markdown. 

If I want to compose a training in pptx and be able to share the slides I would like to prepare a training composed of multiple md files in one master md file and export it to a pptx.

Example: 

- /folder1/instruction1.md
- /folder2/instruction2.md
- /training/training1.md 

Content of training1.md
---
```
![](../folder1/instruction1.md)
![](../folder2/instruction2.md)
```

Export  training1.md using pandoc to pptx.

### Issue: 
once exported as pptx the pptx is corrupt and the presentation is empty. It does not export the embedded files

**Comment by jgm** [comment]
This is really about a syntax for transclusion (#553).
Closing as a duplicate.
