### ISSUE TITLE
Bussproofs prooftree environments and HTML vs LaTeX output

### ISSUE THREAD

**Issue by jdutant** [jgm/pandoc#8462]
MathJax can process LaTeX's bussproof package `prooftree` environment. However, there is no markdown that will work for both HTML and LaTeX output. 

* If `\begin{prooftree}...\end{prooftree}` is included as is in the markdown source, it's not passed at all to HTML output,
* If we enclose it within `$$...$$`, it is passed and MathJax displays it, but the LaTeX output crashes (because the environment shouldn't be included in display math).

MWE:

```bash
pandoc -s --mathjax source.md -o destination.html
pandoc -s source.md -o destination.pdf
```

``` markdown
---
title: Bussproof test
header-includes: |
---
$$\begin{prooftree}
  \AxiomC{$P\land Q$} \UnaryInfC{$Q$}
    \end{prooftree}$$

\begin{prooftree}
  \AxiomC{$P$} \UnaryInfC{$P\lor Q$}
    \end{prooftree}
```

The first is displayed in HTML but the PDF generation crashes. The second isn't passed to HTML at all, but would be printed correctly in the PDF.

Suggested fix (if workable): when `--mathjax` is on, the HTML writer picks raw prooftree envs and passes them within  `<span class="math display">`. 

Alternatively, the LaTeX writer could ensure that math display elements that only contain a prooftree env aren't wrapped with `\[...\]`, or that in general prooftree envs aren't wrapped within `\[...\]`, but that seems  harder and less principled.

**Comment by jgm** [comment]
For now you could work around this with a filter that behaves differently depending on the output format. But I think I can fix this easily.  The HTML writer is already aware of some math environments, and I should just be able to add this one.

**Comment by jgm** [comment]
With the change I've made, we get:
```
% pandoc -t latex
\begin{prooftree}
  \AxiomC{$P$} \UnaryInfC{$P\lor Q$}
    \end{prooftree}
^D
<span class="math display">\[\begin{prooftree}
  \AxiomC{$P$} \UnaryInfC{$P\lor Q$}
    \end{prooftree}\]</span>
% pandoc -t html --mathjax
\begin{prooftree}
  \AxiomC{$P$} \UnaryInfC{$P\lor Q$}
    \end{prooftree}
^D
<span class="math display">\[\begin{prooftree}
  \AxiomC{$P$} \UnaryInfC{$P\lor Q$}
    \end{prooftree}\]</span>
```
I think that's what you want.
