### ISSUE TITLE
Multiple input files using file-scope does not handle spaces in filenames

### ISSUE THREAD

**Issue by NicklasFranzen** [jgm/pandoc#8467]
**Explain the problem.**
I tried out the `--file-scope` changes for generating internal links when using multiple inputs implemented for #6384 but i seem to run into problems with filenames containing spaces where the markdown links to them contains the percent encoded space, %20. Here I expect the link to be just an anchor tag with the filename prefixed but its a the link as if it was not part of the input files.

`pandoc --wrap=preserve --file-scope "command/file 1.txt" "command/file 2.txt"`

input command/file 1.txt, this is  test/command/file1.txt but with the links and name containing a space
```markdown
# Zed

[foo]: bar

[foo]
and [Zed](#zed)
and [other Zed](command/file%202.txt#zed)
and [other file](command/file%202.txt)
and [foreign Zed](c.md#zed)
```

input command/file 2.txt, this is  test/command/file2.txt but with the links and name containing a space
```markdown
## Zed

[foo]: baz

[foo]
```

current output
```html
<div id="command__file-1.txt">
<h1 id="command__file-1.txt__zed">Zed</h1>
<p><a href="bar">foo</a>
and <a href="#command__file-1.txt__zed">Zed</a>
and <a href="command/file%202.txt#zed">other Zed</a>
and <a href="command/file%202.txt">other file</a>
and <a href="c.md#zed">foreign Zed</a></p>
</div>
<div id="command__file-2.txt">
<h2 id="command__file-2.txt__zed">Zed</h2>
<p><a href="baz">foo</a></p>
</div>
```

Here I expect some form of conversion of the %20 like in the `div` where space is replaced with `-`.
(The result is the same if I try to write the markdown links without the %20 and just use a space. )

I tried to write a test to demonstrate what I expected to happen.

test/command/6384-1.md
````
```
% pandoc --wrap=preserve --file-scope "command/file 1.txt" "command/file 2.txt"
^D
<div id="command__file-1.txt">
<h1 id="command__file-1.txt__zed">Zed</h1>
<p><a href="bar">foo</a>
and <a href="#command__file-1.txt__zed">Zed</a>
and <a href="#command__file-2.txt__zed">other Zed</a>
and <a href="#command__file-2.txt">other file</a>
and <a href="c.md#zed">foreign Zed</a></p>
</div>
<div id="command__file-2.txt">
<h2 id="command__file-2.txt__zed">Zed</h2>
<p><a href="baz">foo</a></p>
</div>
```
````

**Pandoc version?**
From git  master ed4bdd059cc6c4b8045b2c4c2c0f8b44d3faa3d6 on Ubuntu 22.04

**Comment by jgm** [comment]
Thanks - fixed I think.

**Comment by NicklasFranzen** [comment]
Tested on my original files and works perfectly, thanks!
