### ISSUE TITLE
Pandoc doesn't include MathJax CDN in HTML when document contains no math

### ISSUE THREAD

**Issue by rnwst** [jgm/pandoc#8469]
**Explain the problem.**

Currently, pandoc only includes the MathJax CDN in the HTML output when the document contains math. I am using a pandoc filter which injects math into a page which otherwise contains no math. Since pandoc does not include the MathJax CDN, this math isn't being rendered when the page is loaded (since MathJax never gets loaded). My initial expectation was that when the `--mathjax` option is passed to pandoc, it will include the MathJax CDN, no matter what. In particular, when the URL is specified according to `--mathjax=URL`, I most certainly expect the resulting HTML file to contain the MathJax URL that I have explicitly passed to pandoc.

Test command:
```shell
pandoc test.md -o test.html -f markdown -t html --mathjax --standalone
```
The resulting HTML file contains no link to the MathJax CDN.

test.md:
```markdown
---
title: A Test.
---

A document without math!
```

**Pandoc version?**
```shell
$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.4, skylighting 0.13.1.1,
citeproc 0.8.0.2, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```
OS: Linux

**Comment by jgm** [comment]
I did notice one flaw in the HTML writer: it doesn't set the "math" template variable when it renders raw LaTeX "math environments" (these are things, like the align environment, that shouldn't be enclosed in Math elements because in LaTeX they aren't valid in math mode).  I'll fix this, maybe that's your issue if you're using RawBlock/RawInline?

**Comment by rnwst** [comment]
Thank you @jgm for your quick response. I hadn't considered the use case of processing a large amount of files with the same options, and I agree that it is sensible to avoid unnecessary network activity. In my particular use case, the filter injects SVGs inside of `RawBlock`s, and those SVGs contain `<foreignObject>` elements, which contain math (in the format `\(math\)`), which is later rendered by MathJax. So it seems this is unrelated to the issue relating to "math environments" that you have just discovered. Can you think of a way to include the MathJax CDN (other than providing a custom HTML template)?

**Comment by jgm** [comment]
One option would be to set the `math` variable directly.
The template contains
```
$if(math)$
  $math$
$endif$
```
so you could use `--variable math="HTML code for mathjax link here"` on the command line or under `variables` in a defaults file.  Alternatively, use `header-includes` in metadata.

**Comment by rnwst** [comment]
Perfect, thanks!
