### ISSUE TITLE
Allow multiple stylesheets to be specified with --epub-stylesheet 

### ISSUE THREAD

**Issue by adiabatic** [jgm/pandoc#847]
I was hoping to put multiple stylesheets in my ePub file so that I can add in an ePub-only stylesheet to pair with a webpage-only stylesheet, but as it turns out, --epub-stylesheet doesn't quite work like --css. I tried the following, and italics, but not green text:

```
printf "# Level-One Heading\n\nThis text should be green and italicized.\n" > test.markdown
printf "html { color: green; }" > all.css
printf "html { font-style: italic; }" > ebook.css
pandoc --epub-stylesheet=all.css --epub-stylesheet=ebook.css -o test.epub test.markdown
unzip -d test.d test.epub
```

Evidently the only thing that goes into the ePub's stylesheet.css is the final file specified. Could this be fixed to allow multiple invocations like --css?

**Comment by cortopy** [comment]
+1

**Comment by jgm** [comment]
Closing in favor of #3472
