### ISSUE TITLE
markdown to HTML does not render unordered lists

### ISSUE THREAD

**Issue by LLyaudet** [jgm/pandoc#8474]
**Explain the problem.**
Hello,

I tried to convert the markdown here
https://raw.githubusercontent.com/LLyaudet/DecimalsRangeRegexpGenerator/main/README.md
to HTML with :
pandoc -f markdown README.md > README.html

But I don't obtain `<ul><li>blabla</li><ul>` in the HTML for the blocks with :
`- blabla` in the markdown

Github does extract unordered lists correctly:
https://github.com/LLyaudet/DecimalsRangeRegexpGenerator/blob/main/README.md
But I verified that I only use basic features of markdown in my file;
no GitHub extension, thus pandoc should handle it.

I tried changing:
`- blabla`
with
`* blabla`
but it did not work either.

**Pandoc version?**
I am using Pandoc version:
```
$ pandoc --version
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.2, texmath 0.12.4, skylighting 0.12.3.1,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/laurent/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose
```
on latest Ubuntu 22.10.
I also reproduced the bug here:
https://pandoc.org/try/

Thanks, best regards,
    Laurent Lyaudet

**Comment by tarleb** [comment]
Pandoc's Markdown requires a blank line before a list by default. You can enable the `lists_without_preceding_blankline` extension to work around this:

    pandoc --from=markdown-lists_without_preceding_blankline`

Alternatively, use commonmark, where this is the default

**Comment by LLyaudet** [comment]
Thank you very much Albert @tarleb :)
