### ISSUE TITLE
`--embed-resources` with `header-includes` can now result in unwanted `¶` characters

### ISSUE THREAD

**Issue by cpsievert** [jgm/pandoc#8475]
Consider the following `test.md` contents:

```md
---
title: Unwanted paragraph glyph
header-includes: |-
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
---

Hello World
```

Running the command `pandoc --from markdown --embed-resources --standalone test.md -o test.html` results in the following HTML result:

<img width="693" alt="Screen Shot 2022-12-06 at 5 29 30 PM" src="https://user-images.githubusercontent.com/1365941/206047682-33a3d027-062a-40f8-81e2-8acaf7eeeccb.png">

Interestingly, changing `|-` to `|` in the yaml gets rid of the `¶` character, but it seems  `|-` should also work, especially since it used to work on 2.18 and earlier with `--self-contained`

```shell
$ pandoc -v                                                                 
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
```

**Comment by jgm** [comment]
Use
```
header-includes: |
```
instead of `|-` if you are including block-level content (as you are in this case).
Otherwise pandoc will try to interpret the blocks as inlines, inserting the pilcrow between blocks.

**Comment by tarleb** [comment]
Maybe we should replace the pilcrow with a PARAGRAPH SEPARATOR   char
(U+2029) to make this less distracting.

**Comment by jgm** [comment]
Fine with me!

**Comment by indy-singh** [comment]
No idea why this didn't show up in Google search for me, but hopefully me saying "pandoc header includes line break" will help other people.

Cheers,
Indy
