### ISSUE TITLE
Custom style working on try pandoc page but not pandoc itself

### ISSUE THREAD

**Issue by DaegL** [jgm/pandoc#8476]
Hi all,

Something I'd like to report is that the bracket custom style does not work consistently. I have created a new custom style as follow:
::: {custom-style="Dynamic table"}
[Dynamic Table Code]
:::

I would like to convert the md file to docx, my aim is to create a style called "Dynamic table". 
However, when I use the following command 
`pandoc -o test.docx test.md --from markdown --to docx`
the entire text body was registered as text. Weirdly enough, when I copy the text at the try pandoc! page, the ouput of the docx successfully create a new "Dynamic table" style. 

I am not too sure what's wrong with that. 

Try Pandoc! page output:
![image](https://user-images.githubusercontent.com/14815126/206139029-b638e64f-323d-413b-a825-16a0032c26db.png)

Pandoc command output:
![image](https://user-images.githubusercontent.com/14815126/206139256-aedbd246-02eb-44a4-b0e0-f39b1c83f1f2.png)

Would really appreciate all your help. Thanks!

Daegal.

**Comment by tarleb** [comment]
One case where this might happen is an old pandoc version running locally.
Please post the output of `pandoc --version` and install a recent
version if possible: https://github.com/jgm/pandoc/releases/latest

**Comment by DaegL** [comment]
Hi Thanks for getting back to me!

This is the print screen for the pandoc version. Should be the latest? 

![image](https://user-images.githubusercontent.com/14815126/206150556-86dc72fc-bb5b-46a7-b55e-0fcc907f281b.png)

**Comment by tarleb** [comment]
Ah yes, that's the issue then. Pandoc version 1.19.2.4 is rather old (it
was released on Sep 10, 2017) and does not support the fenced div syntax
used in the snippet above. Pandoc version shipped with Linux
distributions tend to be a bit dated; relying on the system's package
manager is not always enough to get a recent enough version.

See https://pandoc.org/installing.html for more help on this issue.
