### ISSUE TITLE
classoption variable data is escaped (despite this being raw latex)

### ISSUE THREAD

**Issue by Animajosser** [jgm/pandoc#8478]
**Explain the problem.**
Options provided in the classoption variable are escaped like they are plain-text. This is clearly only used to supply raw latex. This makes it impossible to use slightly more complex arguments for documentclasses like `hyperref={pdfpagelabels=false}`.

Reproducable using the webapp:

Markdown to Beamer (Standalone)

input:
```
---
documentclass: beamer
classoption:
  - hyperref={pdfpagelabels=false}
...
```
actual output:
```
...
\documentclass[
  ignorenonframetext,
  hyperref=\{pdfpagelabels=false\}]{beamer}
...
```

expected output:
```
...
\documentclass[
  ignorenonframetext,
  hyperref={pdfpagelabels=false}]{beamer}
...
```

**Pandoc version?**
latest on https://pandoc.org/try/

**Comment by jgm** [comment]
Metadata fields are interpreted as markdown, and pandoc won't recognize
```
hyperref={pdfpagelabels=false}
```
as LaTeX, so you need to say
````
`hyperref={pdfpagelabels=false}`{=latex}
````
(see raw_attribute in manual)

**Comment by Animajosser** [comment]
That doesn't work:
YAML parse exception at line 3, column 4, while scanning for the next token: found character that cannot start any token

**Comment by Animajosser** [comment]
Nevermind. It should be done like this:
```
---
documentclass: beamer
classoption: "`hyperref={pdfpagelabels=false}`{=latex}"
...
```

**Comment by jgm** [comment]
Yes, sorry. Should have tested!
