### ISSUE TITLE
text between two display style formulas was removed

### ISSUE THREAD

**Issue by redstoneleo** [jgm/pandoc#8483]
**Explain the problem.**
Text between two display style formulas was removed, only formulas left.
Command：
`pandoc.exe aa.docx --self-contained --mathjax -o example35.html`
File:
[aa.docx](https://github.com/jgm/pandoc/files/10204060/aa.docx)

**Pandoc version?**
Latest version pandoc on win11.

**Comment by jgm** [comment]
Thanks for the report. It looks like here we have an oMathPara as a child of a w:p node.
This is legal OOXML, but it looks like the docx reader is expecting an oMathPara to be a block by itself, not in a paragraph.

T.P.Readers.Docx.Parse.hs line 704:
```haskell
elemToBodyPart :: NameSpaces -> Element -> D BodyPart
elemToBodyPart ns element
  | isElem ns "w" "p" element
  , (c:_) <- findChildrenByName ns "m" "oMathPara" element = do
      expsLst <- eitherToD $ readOMML $ showElement c
      return $ OMathPara expsLst
```
This code essentially throws away anything in the w:p besides the oMathPara.
It would be good to fix this -- @jkr do you see a good way to do that?

**Comment by jgm** [comment]
To clarify, oMathPara can be a child of w:p but it can also be a child of w:body -- so in pandoc terms, it can be used in either a "block" or an "inline" context.

We should recognize both of these.

**Comment by jgm** [comment]
OK, I think the fix was fairly straightforward. @jkr feel free to modify if this doesn't seem right.

**Comment by redstoneleo** [comment]
Thanks very much ! Any plan to give a new release ?

**Comment by jgm** [comment]
I expect there will be a new release in the next few weeks.
Til then you can use a nightly (after tonight anyway).

**Comment by redstoneleo** [comment]
where is the nightly ？

**Comment by jgm** [comment]
Actions / Nightly tab on left

**Comment by jgm** [comment]
Rebuilt: https://github.com/jgm/pandoc/actions/runs/3673742995
