### ISSUE TITLE
Provide a way to have unnumbered headings in Context (target and PDF engine)

### ISSUE THREAD

**Issue by vrilcode** [jgm/pandoc#8486]
If you have a Context document (target and PDF engine) with numbered headings, you need sometimes some unnumbered headings, which should also be listed in ToC (preface, appendix etc).

So it would be good to have a feature like mentioned in #1762 (to be more specific: like the outcome of this issue). The combination of feature `.unnumbered` and `.unlisted`, which already exist for Latex documents, is needed for Context as well. https://wiki.contextgarden.net/Titles gives an overview of Context commands for numbered and unnumbered headings.

At the moment, I don't see any workaround. Maybe a filter could rewrite certain headings.

**Comment by tarleb** [comment]
After looking at <https://wiki.contextgarden.net/Table_of_Contents#Explicitly_excluding_headings_from_the_ToC>, I believe that the best option would be to define a new heading types in the template:

```
\definehead[unlistedsubsection][subsection]
```

But there might be a better option.

**Comment by vrilcode** [comment]
Yes, I forgot that default unnumbered heading versions of Context don't appear in ToC (`\subject` and so on). But that could be a solution in case of `.unlisted`, which works the same way (`.unlisted` implies `.unnumbered` in Pandoc too, according to [#1762](https://github.com/jgm/pandoc/issues/1762#issuecomment-540644486)):
```tex
\title               % use instead of \chapter
\subject             % use instead of \section
\subsubject          % use instead of \subsection
\subsubsubject       % use instead of \subsubsection
\subsubsubsubject    % use instead of \subsubsubsection
\subsubsubsubsubject % use instead of \subsubsubsubsection
```
`\part` has no unnumbered counterpart in Context and is special in general. I don't think, that it need to be handled.

For `.unnumbered` only, probably new heading types, like you mentioned, need be to added to the Pandoc Context template:
```tex
\definehead[unnumberedchapter]            [chapter]            [number=no]
\definehead[unnumberedsection]            [section]            [number=no]
\definehead[unnumberedsubsection]         [subsection]         [number=no]
\definehead[unnumberedsubsubsection]      [subsubsection]      [number=no]
\definehead[unnumberedsubsubsubsection]   [subsubsubsection]   [number=no]
\definehead[unnumberedsubsubsubsubsection][subsubsubsubsection][number=no]
```
Which can be used then like:
```tex
\startunnumberedsubsection[title=This is an unnumbered subsection]
...
\stopunnumberedsubsection
```

So finally, Pandoc has to use three different heading commands of Context for documents with numbered sections in general.

**Comment by tarleb** [comment]
I forgot that we switched from `\startsection` to `\startsectionlevel` by default. Setting `--top-level-division=section` yields somewhat better results than the default, but, as you note above, unnumbered sections don't show up in the TOC.

**Comment by tarleb** [comment]
This should work: `unlisted` headings are given with `\starttitle`, `\startsubject` etc. Headings that are just `unnumbered` are given the two extra attributes `[number=no, incrementnumber=no]`. It's simple, doesn't require any extra definitions in the template, and should give the desired behavior.

**Comment by vrilcode** [comment]
@tarleb Awesome. Thank you!
