### ISSUE TITLE
Empty right-aligned paragraph Textile -> GFM causes crash

### ISSUE THREAD

**Issue by geckolinux** [jgm/pandoc#8487]
Hi there, I'm not sure if this is a bug in the `pandoc` binary or in `pandoc-ruby` , but in a Ruby script using `pandoc-ruby` I'm hitting an error with a script that is converting forum posts from Textile to GFM. This is the source text that is causing the problem:

```
Date: June 2022



p>. 

p=. Links:
```

And this is the error:
```
Error at "source" (line 20, column 1):
unexpected '\\n'
expecting block
p=. Links:
^
```

I get the same error with the same source text in https://pandoc.org/try as well, which is running the latest version of Pandoc.

Thanks for the help and for developing this useful utility.

**Comment by geckolinux** [comment]
Same sort of error with blank center-aligned paragraphs like this:
`p<>. `

**Comment by jgm** [comment]
Nothing to do with attributes; it's the empty paragraph:
```
p.
```
will also raise this error.

**Comment by geckolinux** [comment]
Thanks @jgm
