### ISSUE TITLE
`compileTemplate` not compatible with Pandoc* monads

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [jgm/pandoc#8489]
https://github.com/renjianxiongqi/pandoc/commit/f36b5b8a5db8479bcf98827c267840304403bdf0 exported a few functions from doctemplates,  including `Text.Pandoc.Templates.compileTemplate`, that were not made compatible with the pandoc monads PandocIO and PandocPure.

The commit message suggests:
```text
 To compile a template and allow partials to be found locally
    (either on the file system or via HTTP, in the event that
    the main template has an absolute URL), ue
    `runWithPartials (compileTemplate ...)`
```
but this was not explained in the documentation and seems to break form with the other exported template utility functions.

I suggest to update the api so that `compileTemplate` and ... so that they can be used without wrappers with the Pandoc* monads.

#5979

**Comment by jgm** [comment]
The wrappers have a purpose, explained in the commit message.
Sounds like what is needed here is just a bit more documentation in the haddocks for T.P.Template.
We could borrow from the commit message linked to above.
