### ISSUE TITLE
xml:lang deprecated in HTML

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [jgm/pandoc#8498]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:lang) the xml:lang has been deprecated.

That being the case it should probably be removed from the html templates.

**Comment by tarleb** [comment]
The linked page is for SVG, I couldn't find any such info for [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang). My understanding is that this attribute is important when using the output as XHTML and hence should not be removed.

**Comment by jgm** [comment]
It's there because we output polyglot HTML; this is particularly important for EPUB3 which needs xhtml.
