### ISSUE TITLE
Using U+2029 character as separator causes error with PDF conversion. 

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#8499]
Take this document with special `title`

````markdown
---
title: "\\vspace{-1in} Untitled"
author: "Johann Gutenberg"
date: "1455-12-16"
---

## Document begins

Lorem ipsum dolor sit amet
````

Using nightly version of Pandoc, we have the following issue 
````
> pandoc --to pdf -f markdown --standalone -o test.pdf test.md
Error producing PDF.
! LaTeX Error: Unicode character ÔÇ® (U+2029)
               not set up for use with LaTeX.

> pandoc --version
pandoc.exe 3.0-nightly-2022-12-19
````

With Pandoc 2.18, it was working correctly. Since Pandoc 2.19, there is a pilcrow character added (which was reported in https://github.com/rstudio/rmarkdown/issues/2437 and in Pandoc at https://github.com/jgm/pandoc/issues/8475

Report at #8475 lead to a change by @tarleb to use PARAGRAPH SEPARATOR to separate block in inlines (https://github.com/jgm/pandoc/commit/e0e60871458329679c81cf8c589199d4b52922f8). 

This now create the error above when converting with LaTeX . Unicode character U+2029 does not seem to be correctly handle in LaTeX.

**Comment by tarleb** [comment]
We could add this to the LaTeX template:

````
```{=latex}
\ifPDFTeX
  \DeclareUnicodeCharacter{2029}{ }
\else
  \catcode`^^^^2029=\active
  \protected\def ^^^^2029{ }
\fi
```

**Comment by cderv** [comment]
Yes this works ok 
````markdown
---
title: "\\vspace{-1in} Untitled"
author: "Johann Gutenberg"
date: "1455-12-16"
header-includes: |
  ```{=latex}
  \ifPDFTeX
    \DeclareUnicodeCharacter{2029}{ }
  \else
    \catcode`^^^^2029=\active
    \protected\def ^^^^2029{ }
  \fi
  ```
---

## Document begins

Lorem ipsum dolor sit amet
````

**Comment by jgm** [comment]
Alternatively, we could go back to the pilcrow, or use something else (just a newline)?
Note that in this case, the pilcrow is undesirable even if it can render as LaTeX; we don't want a literal pilcrow here.

Another workaround---tell pandoc explicitly that you want the vspace in an inline context. (Untested)
````
title: >
  `\vspace{-1in}`{=latex}Untitled
````

**Comment by tarleb** [comment]
I'll create PRs for both options and let you choose. Either option seems
fine to me. My preference is to keep the semantic clarity of the
PARAGRAPH SEPARATOR char, but simplicity seems important, too.
