### ISSUE TITLE
Multiline metadata to native conversion

### ISSUE THREAD

**Issue by fsoedjede** [jgm/pandoc#8502]
## Explain the problem.

I cannot pass a multiline metadata from json metadata file

### A. Successfull case:

With yaml metadata:

[Test case on try pandoc](https://pandoc.org/try/?params=%7B%22text%22%3A%22---%5Cntitle%3A+Lorem%5Cnlang%3A+fr%5Cnaddress%3A+%7C%5Cn+++1%2C+Avenue+des+Champs-%C3%89lys%C3%A9es%5Cn%5Cn+++75008+Paris%5Cn...%5Cn%5CnLorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.%5Cn%22%2C%22to%22%3A%22native%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

**The parameter `address` contains a `MetaBlocks` with two `Para`.**

### B. Failing case:

With json medadata.
On Try pandoc, passing json in the yaml metadata works but in my real usage, I want to use the option `--metadata-file`.

[Test case on try pandoc](https://pandoc.org/try/?params=%7B%22text%22%3A%22---%5Cn%7B%5Cn++++%5C%22title%5C%22%3A+%5C%22Lorem%5C%22%2C%5Cn++++%5C%22lang%5C%22%3A+%5C%22fr%5C%22%2C%5Cn++++%5C%22address%5C%22%3A+%5C%221%2C+Avenue+des+Champs-%C3%89lys%C3%A9es%5C%5Cn%5C%5Cn75008+Paris%5C%22%5Cn%7D%5Cn...%5Cn%5CnLorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.%5Cn%22%2C%22to%22%3A%22native%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

To test locally:

`properties.json`
```json
{
    "title": "Lorem",
    "lang": "fr",
    "address": "1, Avenue des Champs-Élysées\n\n75008 Paris"
}
```

`sample.md`
```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

Execute: `docker run --rm --volume "$(pwd):/data" pandoc/core:2.19 sample.md --metadata-file=properties.json --standalone --from=markdown --to=native --output=result.native`

**The result is the same as the on we have on try pandoc**

**The parameter `address` contains a `MetaInlines` instead of `MetaBlocks`.**

We also have `\182` which seams to represent a paragraph: https://www.codetable.net/decimal/182

### C. Comment

I've raised a related problem here: https://github.com/jgm/pandoc/issues/8404. I fixed it by applying the suggestion here: https://github.com/jgm/pandoc/issues/8404#issuecomment-1295151226

My end goal is to pass some parameters containing linebreak from json with `--metadata-file`.

## Pandoc version?

pandoc version 2.19.2

**Comment by tarleb** [comment]
Pandoc will treat meta values as blocks if they end with a newline. [Example](https://pandoc.org/try/?params=%7B%22text%22%3A%22---%5Cn%7B%5Cn++++%5C%22title%5C%22%3A+%5C%22Lorem%5C%22%2C%5Cn++++%5C%22lang%5C%22%3A+%5C%22fr%5C%22%2C%5Cn++++%5C%22address%5C%22%3A+%5C%221%2C+Avenue+des+Champs-%C3%89lys%C3%A9es%5C%5Cn%5C%5Cn75008+Paris%5C%22%5Cn%7D%5Cn...%5Cn%5CnLorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.%5Cn%22%2C%22to%22%3A%22native%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

**Comment by jgm** [comment]
Closing because @tarleb has answered this.  You just need to add a newline to the end of the JSON string literal.

**Comment by fsoedjede** [comment]
Thanks for the reply.
It solves my problem
