### ISSUE TITLE
Some SVGs render without text when targetting PDF

### ISSUE THREAD

**Issue by jakobkmar** [jgm/pandoc#8505]
**Explain the problem.**

Some SVGs will render without text when converting a document (for example a Markdown file) to PDF (in my case using pdflatex as the engine).

This does not affect all SVGs, but I encountered this issue *with several different SVGs* already.
[An example would be this SVG.](https://jakobk.de/files/pandoc/pandoc_svg_issue_repro.svg)

To **reproduce** the issue, use the SVG given above, and include it in a markdown file `repro.md` like this:
```markdown
![SVG Issue](pandoc_svg_issue_repro.svg) \
```
Then run `pandoc repro.md -o repro.pdf`

____

**Pandoc version?**

Reproduced on versions `2.14.0.3` (Fedora) and `2.19.2` (pandoc/latex Docker image).

____

**Possible cause**

I am not sure, but does pandoc only use https://gitlab.gnome.org/GNOME/librsvg/ for PDFs? Maybe it has an issue with some SVGs, resulting in the text to be missing?

___

**Related issues**

It seems like this issue is the root cause for some filters not working correctly, because their generated SVGs are missing text as well, for example:
- https://github.com/raghur/mermaid-filter/issues/66

**Comment by jgm** [comment]
See #8176

**Comment by tarleb** [comment]
Closing in favor of #8176.
