### ISSUE TITLE
Support for UTF-8 file names in Lua filters where command shell encoding differs

### ISSUE THREAD

**Issue by mjfs** [jgm/pandoc#8512]
If the command shell's default encoding is not UTF-8, there is currently no integrated way to open a file which has a UTF-8 encoded path/name via `Pandoc`'s `Lua` filter without using either external library or a lot of extra inline code.

This might be mostly a pain point on Windows, but there are many use cases where a robust and portable filter is needed (e.g. include files, special instructions, mapping tables, preprocessed resources). It would make it really convenient if `Pandoc` could handle necessary conversions via a helper function or some other equivalent method. 

This future could mean adding two `Lua` functions e.g.: `utf8_to_shell` and `shell_to_utf8` where `Pandoc` would recognize the encoding used by the shell (e.g. Windows 1250, 1252 or 65001) or encoding could be specified manually. Example of current and future use:

```lua

-- e.g. UTF-8 path_from_yaml_or_marked_span = testčžš.docx
-- 2 lines bellow will not work without conversion - cmd shell encoding is 1250

file = io.open(path_from_yaml_or_marked_span, 'rb')
pandoc_content = pandoc.read(file:read('*a'), "docx")

-- needed conversion from UTF-8 (e.g. such as https://stackoverflow.com/questions/70170504)
-- a helper function would allow for a relevant conversion

file = io.open(utf8_to_shell(path_from_yaml_or_marked_span), 'rb')
pandoc_content = pandoc.read(file:read('*a'), "docx")

```

**Comment by tarleb** [comment]
We could add a function `pandoc.text.toencoding` that allows to convert to other (partially system dependent) encodings.
Draft: https://github.com/hslua/hslua/pull/129/commits/8a79982adde3c858970b3a79ef444e1ad39f78d3

**Comment by mjfs** [comment]
@tarleb: That would do perfectly since it would cover the majority of use cases. Also, `pandoc.text` seems like the most appropriate placement. Thank you!

Two-way conversion would be helpful since it would also cover the usage of pandoc's pipe function, but one could always do a conversion of stdout before returning (e.g. on Windows either via chcp before the command or iconv after the command).

**Comment by tarleb** [comment]
Thanks for the feedback; I've added a `fromencoding` for good measure.
