### ISSUE TITLE
Short option for abbreviations

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#8523]
I miss a short option for `--abbreviations`.

The problem is that I can't use `abbreviations:` in a local defaults file if I also source a defaults file in the user data directory, so I have to type the rather long `--abbreviations` on the command line or use a Makefile, which usually is overkill when I am using defaults files anyway.

See also #8520

**Comment by jgm** [comment]
You can already abbreviate it to `--abbrev` (or any unambiguous prefix).

**Comment by bpj** [comment]
Didn't know that. I guess it is true of all options? Perl's Getopt::Long] enables that by default but I usually disable it as I find it confusing (I wish it were possible to get a list of the shortest unambiguous prefix for an/each option.)

**Comment by jgm** [comment]
Ah, but it is!
```
% pandoc --a 
option `--a' is ambiguous; could be one of:
    --ascii               
    --abbreviations=FILE  
    --atx-headers         
Try pandoc --help for more information.
```
