### ISSUE TITLE
Insert magic tex command for pdf-engine

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#8524]
When `pdf-engine` is set to `xelatex`, for example, it would be even nicer the following magic command can be auto inserted at the top of the tex output:

``` tex
% !TEX program = xelatex
```

This is useful when people directly edit and compile the produced tex file in tex editor that can understand these kinds of magic commands.

**Comment by jooyoungseo** [comment]
Other related tex magic commands: https://www.texdev.net/2011/03/24/texworks-magic-comments/ and http://transit.iut2.upmf-grenoble.fr/doc/texstudio/html/usermanual_en.html

**Comment by jgm** [comment]
Actually, pandoc does not produce different TeX depending on `--pdf-engine`; the TeX it produces is all designed to work with all the engines (it uses conditionals).

Nor does `--pdf-engine` do anything when you're producing tex output -- only pdf.
