### ISSUE TITLE
Source code listing on kindle has a large line spacing.

### ISSUE THREAD

**Issue by mister-goo** [jgm/pandoc#8528]
**Explain the problem.**
Converting from markdown to EPUB:
`pandoc --metadata title=t -f markdown -t epub -o t.epub t.md`

Open the EPUB with the Kindle Previewer, here is the screenshot:
![epub_kindle_pandoc_1](https://user-images.githubusercontent.com/100156123/210969663-7b4b2b38-054b-42e7-95a9-5d4e866314b6.jpg)

The source file:
````markdown

haha.

```c++
// code listing
void f() {
    foo();
    bar();
}
```

````

Anyone had success in producing readable coding books for kindle? The EPUB looks fine on the Calibre reader though.

I tried to add a CSS but it dosen't seem to work for kindle. (It works on the Calibre reader though.)

```css
pre, pre > code.sourceCode > span {
  line-height: 1.6 !important;
}
```

**Pandoc version?**
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4

**Comment by jgm** [comment]
I don't have a kindle to test on, but maybe you can help out.
The CSS that affects the source code will be embedded directly in the xhtml file for the relevant chapter. If you open up the epub container (it's a zip file so you can just unzip it) you should see files like EPUB/text/ch0001.xhtml.  Find one with code in it and you'll see a bunch of inline CSS in a style element in the head.  This comes from the skylighting library.  If you can see what changes there make a difference, it could help us to improve on kindle.

One odd thing I note is that there's a line
```
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
```
which is repeated later in a @media screen context.  You might start by removing one of them, and then try adjusting the line-height here.

**Comment by mister-goo** [comment]
I changed the `inline-block` to `inline` and the line spacing problem was gone. I don't have a kindle device either, I tested on the Kindle Previewer software.

**Comment by mister-goo** [comment]
I also noticed a new problem after fixing the line spacing, while using the Kindle Previewer software to emulate the kindle E-reader, the coding listing is not using monospace fonts. I tried to add `!import` to CSS but without luck. Not sure if this is a problem on real devices.

**Comment by dbaynard** [comment]
I'll take a look over the weekend.

From a skim of [HTML and CSS Tags Supported in Kindle Format 8](https://kdp.amazon.com/en_US/help/topic/GG5R7N649LECKP7U) and [Media Queries](https://kdp.amazon.com/en_US/help/topic/GR4KL488MXKPZ5BK), it looks like we can adjust `line-height`/`padding` for the relevant media queries.

Incidentally, the line numbering won't show up, as the `::before` and `::after` pseudo elements are not supported — this seems trickier (we may have to hard-code the numbering, again, for certain outputs).

The choice of `inline-block` ensures we have each line of code on a new line — but I'll need to confirm this.

> ```css
> pre, pre > code.sourceCode > span {
>   line-height: 1.6 !important;
> }
> ```

@mister-goo You tried reducing the line-height too, right?

**Comment by mister-goo** [comment]
> @mister-goo You tried reducing the line-height too, right?

Yeah, the `line-height` works now.

**Comment by dbaynard** [comment]
That's great! Would you please share the updated screenshot, and the value of the `line-height` that worked?

**Comment by mister-goo** [comment]
@dbaynard I'm still testing, changing the `line-height` work for the above test case, while having incomprehensible effects for more complicated markdown files.

**Comment by dbaynard** [comment]
I can reproduce this in the kindle preview but I don't expect it to affect devices. When I set `line-height` to `0`, it looks like a browser's `line-height` of 1, and there is no gap when highlighting the text. It is possible that there's an off-by-one error in the kindle previewer's interpretation of `line-height`. [Extra spacing between paragraphs on Kindle Previewer](https://www.kdpcommunity.com/s/question/0D5f400000FHXpoCAH/extra-spacing-between-paragraphs-on-kindle-previewer?language=en_US) discusses something that seems similar, and my reading is that it was an artefact of the preview process.

I have, in the past, created documents for kindle (indeed, documents containing code) and I don't remember seeing an issue; I do not have the time to check right now.

If you don't have access to an actual kindle to test on, I suggest you try the kindle app — if there's a problem there, then I’ll dig into extra detail.

**Comment by mister-goo** [comment]
I tried the kindle app on Android and Windows, and I didn't see the excess spacing.
I'll just ignore the Kindle Previewer for now.
