### ISSUE TITLE
Latex writer uses \includegraphics when \includesvg should be used instead (Jupyter to Tex)

### ISSUE THREAD

**Issue by playduck** [jgm/pandoc#8531]
## Steps to reproduce

1. Create a Jupyter Notebook:
```python
import matplotlib.pyplot as plt
%config InlineBackend.figure_formats = ['svg']

plt.plot([1,2,3,4])
plt.show()
```
This imports matplotlib, sets it's output to svg and plots a simple test figure.

2. Run and save the notebook (Jupyter should display the figure).

3. Convert the document to tex using pandoc by running:

```bash
pandoc --extract-media=./ --listings -o ./notebook.tex  ./notebook.ipynb
```

This creates the svg file (named with a random hash from juptyer) and the tex file successfully.
(The `--listings` options is just for readability of the tex output and can be omitted.)

The tex file is the following:
```latex
\begin{lstlisting}[language=Python]
import matplotlib.pyplot as plt
%config InlineBackend.figure_formats = ['svg']

plt.plot([1,2,3,4])
plt.show()
\end{lstlisting}

\includegraphics{./4c7c951c49070ad0289128d3bfbfae6501726af9.svg}
```

The provided svg file exists.
The problem is, that latex' `\includegraphics{}` cannot process svg images.
To do this the [latex svg package](https://www.ctan.org/pkg/svg) is required, which provides the `\includesvg{}` command.
This command should be used.
The expected output in this case is:
```latex
\includesvg{./4c7c951c49070ad0289128d3bfbfae6501726af9.svg}
```
(The -s options does not fix this and does not import the svg package.)

As far as I know the pandoc [latex writer is capable of providing this](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L989) functionality [based on the file extension](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L952).
However it does not seem to do so.

## Versions

```
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.4, skylighting 0.13.1.2,
citeproc 0.8.0.2, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4

Python 3.9.4
matplotlib==3.4.2

MacOs Ventura 13.0.1
```

**Comment by tarleb** [comment]
Thank you for the report. See also #8027 for a related issue. In fact, support for this was added to the development version (commit 1393037f4eb04ebad849d79b53a8b3e354aa0bdb), so I'm closing this as completed.
