### ISSUE TITLE
long yaml input overflows to a second line in output

### ISSUE THREAD

**Issue by BBBalls** [jgm/pandoc#8532]
If a yaml input is too long, the overflow is placed on a second line. This breaks the functionality of some outputs or generates unexpected outputs, depending on the circumstance.

In my circumstance I use a yaml field to populate a yaml field of an output to be interpreted by Jekyll. Outputting to second makes the yaml uninterpretable. I also use the same yaml field to to populate a header field, but the overflow text is output as a separate paragraph (not demonstrated in the example bellow).

command:
`pandoc -f markdown -t html 'test.md' --template='test_template.html' -o test_html.html`

test.md:
```
---
title: if the yaml input is too long the pandoc output will place the overflow onto a second line
---
```

test_template.html:
```
---
title: $title$
---

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
</head>
<body>
$if(title)$
<h1>$title$</h1>
$endif$

$if(title)$
### $title$
$endif$

</body>
</html>
```

test_html.html:
```
---
title: if the yaml input is too long the pandoc output will place the
overflow onto a second line
---

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>if the yaml input is too long the pandoc output will place the overflow onto a second line</title>
</head>
<body>
<h1>if the yaml input is too long the pandoc output will place the
overflow onto a second line</h1>

### if the yaml input is too long the pandoc output will place the
overflow onto a second line

</body>
</html>
```

pandoc 2.19.2
Arch Linux

**Comment by jgm** [comment]
See https://pandoc.org/MANUAL.html#pipes
What you want is the `nowrap` pipe.
Alternatively, just use `--wrap=none` on the command line.

**Comment by BBBalls** [comment]
Thank you.
