### ISSUE TITLE
HTML → texinfo: `<var>` within `<code>` not taken into account

### ISSUE THREAD

**Issue by lemzwerg** [jgm/pandoc#8534]
[version 2.19.2]

Consider the following minimum HTML input.

```html
<html>
foo <code>bar <var>baz</var> bar</code> foo
</html>
```

If processed with `pandoc -f html -t texinfo` I get the following output.

```texinfo
foo @code{bar }@code{baz}@code{ bar} foo
```

This should rather be

```texinfo
foo @code{bar @var{baz} bar} foo
```

instead.  Both Firefox and Chrome display 'baz' in code italic for the above HTML code, and Texinfo actually supports `@var` in `@code` just fine, too.

**Comment by jgm** [comment]
Pandoc parses this as
```
    , Code ( "" , [] , [] ) "bar "
    , Code ( "" , [ "variable" ] , [] ) "baz"
    , Code ( "" , [] , [] ) " bar"
```
So this would be a matter of teaching texinfo writer to render
```
    , Code ( "" , [ "variable" ] , [] ) "baz"
```
as `@code{@var{baz}}`.
This would get you
```
foo @code{bar }@code{@var{baz}}@code{ bar} foo
```
If that's objectionable, a further step could be added to consolidate adjacent code elements.

**Comment by lemzwerg** [comment]
IMHO,

```texinfo
foo @code{bar }@code{@var{baz}}@code{ bar} foo
```

is good enough since there is no other interaction that could interfere.

**Comment by lemzwerg** [comment]
Great, thanks!
