### ISSUE TITLE
Allow HTTPS URL for the `--reference-doc` option

### ISSUE THREAD

**Issue by djhurio** [jgm/pandoc#8535]
**Describe your proposed improvement and the problem it solves.**

Pandoc accepts HTTPS URLs for the `FILES`. However, HTTPS URL is not allowed for the `--reference-doc` option. For example, this works:

```
pandoc https://pandoc.org/demo/MANUAL.txt --reference-doc twocolumns.docx -o UsersGuide.docx
```

However, this example is failing with an error: _openBinaryFile: does not exist (No such file or directory)_

```
pandoc https://pandoc.org/demo/MANUAL.txt --reference-doc https://pandoc.org/demo/twocolumns.docx -o UsersGuide.docx
```

I would like to have an ability to specify the `--reference-doc` option with HTTPS URL. It would be useful for corporate environments where a common reverence document would be shared centrally via HTTPS.

**Describe alternatives you've considered.**

Alternative is to use a shared network drive or downloading a reference document locally.

**Comment by jgm** [comment]
I think this is just a matter of replacing `readFileLazy` with `fetchItem` in l. 137 of the Docx writer.
I have to think about whether there was a reason it wasn't allowed in the first place.

**Comment by djhurio** [comment]
Thanks a lot!

**Comment by sebastiansukstorf** [comment]
Hello @djhurio, did you solve the reference-doc with URL? I try to use a *.docx template from my GitHub repository with this command:

pandoc my-file.md -o my-file.docx --reference-doc https://github.com/mygithub/pandoc-reference-doc/blob/main/normseite.docx  --from=markdown+hard_line_breaks

But I receive the following error message: 

pandoc: Data.Binary.Get.runGet at position 4: Did not find end of central directory signature
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:345:5 in binary-0.8.9.1:Data.Binary.Get
 
Thanks for any help.

**Comment by djhurio** [comment]
Hello @sebastiansukstorf 

Yes, this has been fixed. For example, this works for me with the `pandoc` version 3.1.11.1:

```
pandoc https://pandoc.org/demo/MANUAL.txt --reference-doc https://pandoc.org/demo/twocolumns.docx -o UsersGuide.docx
```
