### ISSUE TITLE
Textile → GFM messes up bold links

### ISSUE THREAD

**Issue by geckolinux** [jgm/pandoc#8540]
Hi, with the latest Pandoc version this Textile -> Github Flavored Markdown conversion of a bold link is incorrect:

#### Original Textile:
`*Test "here":https://www.whatever.com/something/post/123*`

#### Rendered Textile:
![Screenshot from 2023-01-11 01-09-37](https://user-images.githubusercontent.com/2692138/211730630-e8298430-d928-4a7a-9071-57c7fde25f0c.png)

#### Pandoc converts:
`\*Test [here](https://www.whatever.com/something/post/123*)`

#### Proper Markdown would be:
`**Test [here](https://www.whatever.com/something/post/123)**`

**Comment by jgm** [comment]
Pandoc takes the final `*` to be part of the URL.
It would be helpful to know what rule textile uses to determine when the URL ends.

**Comment by geckolinux** [comment]
Hi @jgm thanks a lot for the reply.

Here's a link to the most common Textile PHP library that is used to parse Textile on most websites that support it, and specifically this appears to be where the link handling functions begin:
https://github.com/textile/php-textile/blob/master/src/Netcarver/Textile/Parser.php#L4066

**Comment by geckolinux** [comment]
Thanks very much!
