### ISSUE TITLE
Textile → GFM fails to convert a linked image

### ISSUE THREAD

**Issue by geckolinux** [jgm/pandoc#8541]
Hi, the latest version of Pandoc fails to convert a linked image from Textile to Github Flavored Markdown:

#### Original Textile:
`!https://wikimedia.org/static/images/project-logos/enwiki-2x.png!:https://wikimedia.org/static/images/project-logos/enwiki-2x.png`

#### HTML would be:
`<a href="https://wikimedia.org/static/images/project-logos/enwiki-2x.png"><img src="https://wikimedia.org/static/images/project-logos/enwiki-2x.png" alt=""/></a>`

#### Pandoc outputs:
`![](https://wikimedia.org/static/images/project-logos/enwiki-2x.png):https://wikimedia.org/static/images/project-logos/enwiki-2x.png`

#### Proper Markdown according to [this](https://www.codecademy.com/resources/docs/markdown/images) would be:
`[![](https://wikimedia.org/static/images/project-logos/enwiki-2x.png "")](https://wikimedia.org/static/images/project-logos/enwiki-2x.png)`

***Let's try that here on Github...***
[![](https://wikimedia.org/static/images/project-logos/enwiki-2x.png "")](https://wikimedia.org/static/images/project-logos/enwiki-2x.png)

**Comment by geckolinux** [comment]
Thanks a ton! Are there Linux binary builds based on Master anywhere? Or any suggestions on the best way to use this in a Debian Docker image?

**Comment by jgm** [comment]
There will be a nightly tomorrow (see under actions).

**Comment by geckolinux** [comment]
Awesome, thanks again.

**Comment by tarleb** [comment]
As for Docker: the `edge` tag on [pandoc/minimal] and [pandoc/core] images contain a recent version built from the main branch. These images are rebuilt twice a week.

[pandoc/minimal]: https://hub.docker.com/r/pandoc/minimal
[pandoc/core]: https://hub.docker.com/r/pandoc/core
