### ISSUE TITLE
The code listing font is not fixed-width

### ISSUE THREAD

**Issue by mister-goo** [jgm/pandoc#8543]
**Explain the problem.**
On Windows, the default font for code listing is "Lucida Console". The bold version of "Lucida Console" is wider than the normal one, causing misalignments.
I suggest replacing it with "Courier New", which is also commonly present on Windows.

The current font list: `font-family: Menlo, Monaco, 'Lucida Console', Consolas, monospace;`

**Pandoc version?**
Latest.

**Comment by jgm** [comment]
@mb21 what do you think?  I'm happy to change this, but I don't want to make a change that will make the default experience on Linux worse.  We could just go to `Menlo, Monaco, Consolas, monospace`.

**Comment by mb21** [comment]
I remember researching this a bit, and most blog posts recommending Lucida Console for Windows – and indeed it looks much nicer (to me) than Courier New. However, I didn't test this extensively on Windows, and don't remember anything about bold fonts. Maybe you can post some screenshots and say which version of Windows you're on?

**Comment by mister-goo** [comment]
Windows 10:

![lucida_console_bold](https://user-images.githubusercontent.com/100156123/212013435-6bddbb7e-695c-490a-a226-20470f64c7e9.png)

**Comment by agusmba** [comment]
> @mb21 what do you think? I'm happy to change this, but I don't want to make a change that will make the default experience on Linux worse. We could just go to `Menlo, Monaco, Consolas, monospace`.

I don't suffer this because I always use my own reference doc where Source Code style uses "Consolas". Another recent alternative for Windows would be Cascadia Code.
Anyway at least in Word I'm not seeing @mister-goo 's problem. Is this an html problem?

![image](https://user-images.githubusercontent.com/3104020/212017675-4119cf9a-61d5-4cfe-b9ec-31bdf3b36fa4.png)

**Comment by mister-goo** [comment]
> Anyway at least in Word I'm not seeing @mister-goo 's problem. Is this an html problem?

I can reproduce this on Wordpad, Chrome, Firefox, and IE, but not on Word 2003.

Seems that this also affects Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=42114

**Comment by agusmba** [comment]
Indeed, there is something funny with rendering Lucida Console in html (chrome) and WordPad (Windows 10 box):

![image](https://user-images.githubusercontent.com/3104020/212146677-c74616bd-6fe7-4772-a0e2-5892aac6ec19.png)

At least on the Windows side it would make sense to drop Lucida Console from the default chain, but as @jgm points out,  we shouldn't make the default experience on Linux worse.

**Comment by agusmba** [comment]
> @mb21 what do you think? I'm happy to change this, but I don't want to make a change that will make the default experience on Linux worse. We could just go to `Menlo, Monaco, Consolas, monospace`.

Or, maybe switch positions as in `Menlo, Monaco, Consolas, 'Lucida Console', monospace`, hoping that `Consolas` is not as widespread on Linux?

**Comment by jgm** [comment]
Is Consolas always present on Windows?

**Comment by agusmba** [comment]
> Is Consolas always present on Windows?

AFAIK yes. Also found this: https://learn.microsoft.com/en-us/typography/font-list/consolas#products-that-supply-this-font

**Comment by jgm** [comment]
Great, I'll just put Consolas before "Lucida Console" in the list.  That should allow "Lucida Console" to be selected on Linux machines that don't have Consolas, while preventing it from being used on Windows machines.

**Comment by jgm** [comment]
Alternatively we could introduce `codefont` and have
```
font-family: $if(codefont)$'$codefont$', $endif$monospace;
```

**Comment by jgm** [comment]
Actually, LaTeX already uses `monofont` , so we could use that.
I think I prefer this -- it goes with our trend of making the template more neutral.

**Comment by jgm** [comment]
Sorry, I see now that `monofont` is already in the HTML styles template; it's just a question of what we fall back to if it's not provided.  So I think this is fine.
