### ISSUE TITLE
Pandoc ignores --data-dir variable in command line

### ISSUE THREAD

**Issue by ekaterina-o** [jgm/pandoc#8544]
Pandoc ignores --data-dir variable in command line. I put a few markdown files into folder to merge them and wrote absolute folder path in command line, but pandoc doesn't see them.

```
C:\Users\Katrin>pandoc --data-dir=d:\Cloud\Dropbox\backup\notes\made_02 file1.md file2.md -s -o file.html
pandoc: file1.md: openBinaryFile: does not exist (No such file or directory)
```

Pandoc 2.19.2 Windows 7 64

**Comment by tarleb** [comment]
Hi Екатерина, this is a misunderstanding of what pandoc means with "data dir" and "data file". In the context of pandoc, those terms have a very specific meaning: "data dir" refers to the directory in which pandoc looks for templates and some configs, but not for input files. Pandoc expects the full filename as input, so either

    pandoc d:\Cloud\Dropbox\backup\notes\made_02\file1.md d:\Cloud\Dropbox\backup\notes\made_02\file2.md -s -o file.html

or switch directories first with

    cd d:\Cloud\Dropbox\backup\notes\made_02
    pandoc file1.md file2.md -s -o file.html

**Comment by tarleb** [comment]
Of course, we are always happy to improve the docs, so if you have a suggestion on how those could be phrased to be less confusing, please do let us know.

**Comment by ekaterina-o** [comment]
Is there no way to merge a few files without their full path? Your code with `cd` doesn't work either.

**Comment by tarleb** [comment]
I don't have Windows to test, so not sure why it's not working. Maybe try with a semicolon after the `cd DIR;`.

If you plan to run the command on the same inputs frequently, then you could think about using a defaults file like this:

```
input-files:
  - d:\Cloud\Dropbox\backup\notes\made_02\file1.md
  - d:\Cloud\Dropbox\backup\notes\made_02\file2.md
standalone: true
```

Save the above to `notes.yaml` and call pandoc with

    pandoc -d notes.yaml -o file.html
