### ISSUE TITLE
A variable for input folder

### ISSUE THREAD

**Issue by ekaterina-o** [jgm/pandoc#8546]
It's a pity there's no way to merge a few files without their full paths. It's complicated if there are many files and paths are long. It would be great to have a variable for input folder.

Something like this

```
pandoc input-dir=d:\Cloud\Dropbox\backup\notes\made_02 file1.md file2.md -s -o file.html
```

Instead of this

```
pandoc d:\Cloud\Dropbox\backup\notes\made_02\file1.md d:\Cloud\Dropbox\backup\notes\made_02\file2.md -s -o file.html
```

**Comment by jgm** [comment]
How about this?
```
cd d:\Cloud\Dropbox\backup\notes\made_02 && pandoc file1.md file2.md -o file.html && cd ..
```
Almost as concise, already works.

**Comment by ekaterina-o** [comment]
> ```
> cd d:\Cloud\Dropbox\backup\notes\made_02 && pandoc file1.md file2.md -o file.html && cd ..
> ```

Doesn't work.

**Comment by jgm** [comment]
What happens?  I'm sorry, maybe some of this doesn't work on Windows.

In any case, this seems to me to be a matter of shell scripting and not something that should be built into pandoc.

**Comment by ekaterina-o** [comment]
I found a solution by putting Pandoc code into a bat file with short ways relative to its folder.
