### ISSUE TITLE
preserve source doc pages in html output

### ISSUE THREAD

**Issue by andrisi** [jgm/pandoc#8549]
I'm converting from docx to html. The conversion works beautifully. I'm not familiar with the docx format, but if it has a concept of pages, so you know what content is on what page, then it would be useful in my use case to somehow preserve this information, so the html output contains some hints - like divs with pagenumber properties - to specify what page number the given block of content came from. The same for footnotes, so if docx links all footnotes to a specific page, it would be nice to preserve that infoprmation, so even tought the html output is freeflowing, and footnotes are inline, it specifies which page they came from, and perhaps can be put at the end of the document, or in a floating bubble, etc. - so something pageless and html specific. The same could be done for headers and footers of they're not the same on all pages. I see you remove them, and that is good for now. Thanks!

**Comment by tarleb** [comment]
Thank you for the proposal. Page numbers are not encoded in the docx format, and there isn't even a way to know if two successive paragraphs will end up on the same page unless the whole document is rendered. Rendering docx is out of scope for pandoc, which means that this feature is, too.
