### ISSUE TITLE
--natbib causes weird behaviour on files consisting of a single header

### ISSUE THREAD

**Issue by kirelagin** [jgm/pandoc#855]
```
kirrun@kirNote ~/tmp [1145]% cat test1.pd 
Hello
======
kirrun@kirNote ~/tmp [1146]% pandoc test1.pd -o test1.latex
kirrun@kirNote ~/tmp [1147]% cat test1.latex 
\section{Hello}
kirrun@kirNote ~/tmp [1148]% pandoc test1.pd -o test1.latex --natbib
kirrun@kirNote ~/tmp [1149]% cat test1.latex                        
                                              <--------- ???
kirrun@kirNote ~/tmp [1150]%
```

Nuff said!

All those are working fine:

```
kirrun@kirNote ~/tmp [1150]% cat test2.pd                        
Hello
======

world!
kirrun@kirNote ~/tmp [1151]% pandoc test2.pd -o test2.latex --natbib
kirrun@kirNote ~/tmp [1152]% cat test2.latex 
\section{Hello}

world!
kirrun@kirNote ~/tmp [1153]% cat test3.pd 
\section{Hello}
kirrun@kirNote ~/tmp [1154]% pandoc test3.pd -o test3.latex --natbib
kirrun@kirNote ~/tmp [1155]% cat test3.latex 
\section{Hello}
kirrun@kirNote ~/tmp [1156]% 
```

_P.S. It's not that I'm using `--natbib` without actual bibliography ;). Just a minimal example._

**Comment by Rufflewind** [comment]
> But do they?

Having a lone header at the end of a file can certainly happen while testing things :P 

I was working on a set of build scripts for a book and I was actually quite confused why I kept getting blank `.tex` files from Pandoc despite having a single chapter without any content.

I think this feature should probably be turned off if `--standalone` is not set.  I use `--natbib` to produce LaTeX *fragments* for `--include-before-body` and `--include-after-body`, so it doesn’t really make sense to assume the bibliography will necessarily follow them.
