### ISSUE TITLE
Can't install master version due to `digest` config failure: `pkg-config >=0.9.0 not found`

### ISSUE THREAD

**Issue by geckolinux** [jgm/pandoc#8550]
Hi there, I'm trying to install the latest master version from source, using the upstream version of `stack`. It fails with this error:

```
digest                           > Configuring digest-0.0.1.4...
digest                           > Cabal-simple_SvXsv1f__3.6.3.0_ghc-9.2.5: The program 'pkg-config' version
digest                           > >=0.9.0 is required but it could not be found.
```

I'm seeing the same error with `pkg-config` using `cabal` as well. Is there any possible workaround? Thanks a lot!

**Comment by jgm** [comment]
Hm, that seems to be due to this very recent change:

https://github.com/jkff/digest/commit/6850fade651db495ed4f6c6ab27fdfa18ddc108c

I think the workaround would be to install `pkg-config` with your package manager.
On macos you can `brew install pkg-config`  On debian `apt install pkg-config`. etc.

**Comment by geckolinux** [comment]
Works! That was too easy, I should have thought of that ;-)

Just to confirm, to create a relocatable binary with `stack` it's during the install stage?
`stack install --flag pandoc:embed_data_files` ?

**Comment by geckolinux** [comment]
Another question: Is it possible to compile pandoc for a lower glibc version? I need to use this binary inside a Debian 11 Docker container, and it has `GLIBC 2.31-13+deb11u5`. The relocatable binary doesn't work:

```
pandoc --version
./pandoc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./pandoc)
./pandoc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./pandoc)
./pandoc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./pandoc)

**Comment by jgm** [comment]
> Just to confirm, to create a relocatable binary with stack it's during the install stage?
`stack install --flag pandoc:embed_data_files` ?

Correct.

> Another question: Is it possible to compile pandoc for a lower glibc version? I need to use this binary inside a Debian 11 Docker container, and it has GLIBC 2.31-13+deb11u5. The relocatable binary doesn't work:

This is why we compile our release binary using alpine linux, statically linking in everything.  See the `debpkg` Makefile target to see how we do it.

**Comment by geckolinux** [comment]
I guess the more simple solution for me at the moment is just to compile it in a Debian 11 host.
