### ISSUE TITLE
When convert docx to md, table alignment is lost.

### ISSUE THREAD

**Issue by rhirano0715** [jgm/pandoc#8551]
When convert docx to md, table alignment is lost.
It is also lost when converted to html or pdf.
It seems to be docx reader issue.

Input(docx)
![Sample docx](https://user-images.githubusercontent.com/104247605/212501261-d018ee55-40aa-4f77-92d4-d3646fba33d1.png)

Output(md)

```md
Table

  -----------------------------------------------------------------------
  Default           Left              Center            Right
  ----------------- ----------------- ----------------- -----------------
  Row11             Row12             Row13             Row14

  Row21             Row22             Row23             Row24
  -----------------------------------------------------------------------
```

## for reproduce

- Version:  
  2.19.2 ( [pandoc/latex](https://hub.docker.com/r/pandoc/latex) )
- Command:  
    `pandoc Sample.docx -o Sample.md`
- Input:  
  [Sample.docx](https://github.com/jgm/pandoc/files/10419076/Sample.docx)
- Output:  
  [Sample.md](https://github.com/jgm/pandoc/files/10419077/Sample.md)

**Comment by jgm** [comment]
That's right.  Comment in code:

  - [-] Table (column widths and alignments not yet implemented)

**Comment by rhirano0715** [comment]
Sorry. I overlooked it.
