### ISSUE TITLE
Formatting problem with code blocks while exporting from Markdown to PDF

### ISSUE THREAD

**Issue by francesco-plt** [jgm/pandoc#8557]
Ubuntu latest (22.04.1), pandoc latest (2.19.2). If I export a Markdown file to PDF as follows:
```
$ file="xxx.md"
$ pandoc "$file" -o "$(basename "$file" .md).pdf"
```
The file compile correctly, and everything works as expect, with the exception of code blocks which look like they have formatting problems:
<img width="877" alt="Screenshot 2023-01-17 alle 15 54 10" src="https://user-images.githubusercontent.com/26849744/212931303-5571acfa-195b-43bc-878c-4007bd412dec.png">

Looks like it's a problem with pandoc, since I tried looking for wrap around / formatting settings to fix this issue to no avail.

**Comment by jgm** [comment]
What's the formatting problem here?  I see that there's a line that is too long for the page, is that it?

That's not considered a bug: we don't attempt to re-wrap code lines that don't fit.  Just change your source so that you have a shorter line.

**Comment by francesco-plt** [comment]
> What's the formatting problem here? I see that there's a line that is too long for the page, is that it?
> 
> That's not considered a bug: we don't attempt to re-wrap code lines that don't fit. Just change your source so that you have a shorter line.

So pandoc is not rewrapping at all? This is weird to me, because as you can see from the following image:
<img width="1213" alt="Screenshot 2023-01-17 alle 16 55 49" src="https://user-images.githubusercontent.com/26849744/212946506-24d8153b-102c-4ae3-a146-367d29b54119.png">
It looks like normal text paragraph are auto wrapped while code blocks are not.

**Comment by jgm** [comment]
> It looks like normal text paragraph are auto wrapped while code blocks are not.

Exactly, and that's by design.  Introducing a newline in normal text doesn't change the semantics, but introducing one in code does.
