### ISSUE TITLE
Failing to build pandoc 3.0 with cabal (or stack)

### ISSUE THREAD

**Issue by mjsteinbaugh** [jgm/pandoc#8560]
Hi, I'm running into build issues with the new pandoc 3.0 release with either `cabal` or `stack`. The previous 2.19.2 release builds correctly.

My current install script is here:
https://github.com/acidgenomics/koopa/blob/develop/lang/shell/bash/include/install/common/shared/pandoc.sh

```sh
cabal v2-update
cabal v2-install
```

```
  The package location 'pandoc-lua-engine' does not exist.
  The package location 'pandoc-server' does not exist.
  The package location 'pandoc-cli' does not exist.
```

Homebrew is also currently having the same build issue:
https://github.com/Homebrew/homebrew-core/pull/120967

Attempting `cabal build pandoc-cli` or `cabal install pandoc-cli` doesn't work either.

I'm taking a look at running tests (in `CONTRIBUTING.md`) but wanted to post this in case someone else has hit this and has a quick fix.

Related:
- https://github.com/jgm/pandoc/blob/main/CONTRIBUTING.md
- https://groups.google.com/g/pandoc-discuss/c/ig3mqfHKuvs

Best,
Mike

**Comment by tarleb** [comment]
Thanks for the report. Running `cabal install pandoc-cli` should have done it. Can you add more info on what "doesn't work" means in detail?

**Comment by mjsteinbaugh** [comment]
Hi @tarleb I'll rerun this later today with better logging and will get back to you. Thanks!

**Comment by jgm** [comment]
`cabal install` will only work from the source directory, and this should contain subdirectories for pandoc-lua-engine, pandoc-server, and pandoc-cli.  Does it?

`cabal install pandoc` ought to work fine outside of a source directory.  However, as noted in the release notes, and by @tarleb, you'll need `cabal install pandoc-cli` now if you want the CLI tool.

**Comment by mjsteinbaugh** [comment]
@jgm Yeah that's running inside the source directory on my machine -- I'll look into this more later this afternoon and get back to you

**Comment by mjsteinbaugh** [comment]
Ah think I figured it out, my install script was downloading from hackage.haskell.org instead of directly from GitHub. A similar approach is currently used by Homebrew, which is why that script is also now breaking:
https://github.com/Homebrew/homebrew-core/blob/84ac232a9b73a7cc182efaf1b708f6674d534487/Formula/pandoc.rb

Replace this:
https://hackage.haskell.org/package/pandoc-3.0/pandoc-3.0.tar.gz

With:
https://github.com/jgm/pandoc/archive/refs/tags/3.0.tar.gz

Haha thanks!

**Comment by tarleb** [comment]
That makes sense, thank you for keeping us updated. Would downloading pandoc-cli-3.0.tar.gz from hackage work?

**Comment by chenrui333** [comment]
I thought hackage artifact would be the same as github source archive, sounds like it is not?

**Comment by tarleb** [comment]
@chenrui333 We've modularized pandoc some more and therefore switched to a monorepo: the GitHub archive contains all packages in the repo (the base library `pandoc`, as well as `pandoc-lua-engine`, `pandoc-server`, and `pandoc-cli`) while the Hackage archive contains only the specific package.

**Comment by jgm** [comment]
@mjsteinbaugh I don't really understand why you'd want to download the tarball from Hackage and then cabal install it, when you can just `cabal update && cabal install pandoc-cli`?

@tarleb We should probably remove cabal.project and stack.yaml from `extra-source-files`.  It's because these are there that a build from the release tarball is failing.   Is there a reason for them to be there?

**Comment by jgm** [comment]
@chenrui333 The GitHub archive contains everything in the repository.  The Hackage tarball just contains things specified in pandoc.cabal (as source files, data files, or extra-source-files).

**Comment by mjsteinbaugh** [comment]
@jgm I'll try that instead and see if it works. Thanks!

**Comment by tarleb** [comment]
> We should probably remove cabal.project and stack.yaml from `extra-source-files`. It's because these are there that a build from the release tarball is failing. Is there a reason for them to be there?

Makes sense. I seem to remember that, at some point in the past, the CI built pandoc by creating an archive and then unpacking it to a new directory, thereby ensuring that all necessary files where included. That might have been the motivation to list them under `extra-source-files`.

**Comment by jgm** [comment]
Note: you need `pandoc-cli`, not just `pandoc`, if you want the command line tool.

**Comment by jgm** [comment]
I don't think very many people will build pandoc this way, by downloading the release tarball from Hackage and then doing `cabal install` inside it.  (Indeed, if they do, I think `cabal install` will now simply fail, because there's no executable.)

We could have a "release version" of cabal.project that removes the sub-packages, but I'm not convinced this is needed.

**Comment by jgm** [comment]
We do need to make sure that homebrew includes the flag in building pandoc...
since the way they were doing it before, it wouldn't have been necessary.

**Comment by jgm** [comment]
Including a cabal.project in the tarball for pandoc-cli would be a possibility, if you think this is an issue.

**Comment by tarleb** [comment]
It seems that this is best solved via documentation. Should I open a feature request for that?

**Comment by jgm** [comment]
Sure, go ahead.

**Comment by tarleb** [comment]
On second thought, after re-reading the instructions in `INSTALLmd`, I now think that the existing docs completely sufficient. Setting the flags is mentioned under "Custom cabal method".
