### ISSUE TITLE
Feature request: add ToC to all files when using `chunkedhtml` format

### ISSUE THREAD

**Issue by soapdog** [jgm/pandoc#8561]
**Describe your proposed improvement and the problem it solves.**

At the moment there is no easy way to add a table of contents to all files generated by pandoc when using _chunkedhtml_ output format. Custom templates with navigation sidebars can't be correctly filled in because the table of content related variables are not set for all files.

**Describe alternatives you've considered.**

I've seen in another issue — the one that requested chunkedhtml in the first place — that the developers were recommending creating an `<iframe>` and somehow including the toc from out-of-band file. That is not really how most sites work these days.

One could add some JS to fetch `sitemap.json` and assemble the toc but this sounds like a hack when the variables and code already exist, it is just not being exposed to all the files it is generating.

**Comment by jgm** [comment]
Actually, this is possible already, you just need to use a custom template.  Here's the diff against the default template:

```diff
@@ -83,14 +83,12 @@
 $endif$
 </header>
 $endif$
-$if(toc)$
 <nav id="$idprefix$TOC" role="doc-toc">
 $if(toc-title)$
 <h2 id="$idprefix$toc-title">$toc-title$</h2>
 $endif$
 $table-of-contents$
 </nav>
-$endif$
 $body$
 $for(include-after)$
 $include-after$
```

The `toc` variable is only set for certain files, but the `table-of-contents` variable is always set, so if you remove the check for `toc` it will put the TOC on every page.

**Comment by jgm** [comment]
You can even do this with the default template by using `-Vtoc=false`.

**Comment by jgm** [comment]
So,
```
pandoc MANUAL.txt -t chunkedhtml -Vtoc -o manual
```
will do what you want.

**Comment by soapdog** [comment]
Thanks a lot, I'll try it out. I didn't realise that `toc` and `table-of-contents` were set set in that way.
