### ISSUE TITLE
Powerpoint output : images not working anymore in pandoc 3.0

### ISSUE THREAD

**Issue by Ombrelin** [jgm/pandoc#8565]
**Explain the problem.**

When exporting my markdown to `.pptx` with Pandoc 2.19.2, images works and a present in the powerpoint. However, in 3.0, images do not show, only their caption.

Command used : 
```
pandoc -t pptx .\slideshow.md -o slideshow.pptx --reference-doc=template.potx
```

**Pandoc version?**
Problems occurs in 3.0. Everything fine in 2.19.2

**Comment by ba-tno** [comment]
I have the same issue and attached a folder with the following files:

[no-image-demo.zip](https://github.com/jgm/pandoc/files/10698053/no-image-demo.zip)

- example_files: folder with images included in markdown file
- example.md: minimal example markdown with 2 referenced images
- pandoc2.docx: result of running the following command with pandoc version `2.19.2`:  
    `pandoc --from=markdown .\example.md -o pandoc2.docx`
- pandoc2.pptx: result of running the following command with pandoc version `2.19.2`:  
    `pandoc --from=markdown .\example.md -o pandoc2.pptx`
- pandoc3.docx: result of running the following command with pandoc version `3.0.1`:  
    `pandoc --from=markdown .\example.md -o pandoc3.docx`
- pandoc3.pptx: result of running the following command with pandoc version `3.0.1`:  
   `pandoc --from=markdown .\example.md -o pandoc3.pptx`

As you can see the pptx and docx from version 2 look fine, the docx from version 3 looks fine, but the pptx from version 3 is missing images.

When I install [pandoc using conda](https://anaconda.org/conda-forge/pandoc), it uses version `2.19.2`:

```
> pandoc --version
pandoc.exe 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: C:\Users\asharib\AppData\Roaming\pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

If I download the [latest binary from Github](https://github.com/jgm/pandoc/releases/tag/3.0.1) I get `3.0.1`:

```
> pandoc --version
pandoc.exe 3.0.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: C:\Users\asharib\AppData\Roaming\pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

I'm on a Windows machine with Windows 10, Version 22H2, Build 19045.2486.

**Comment by jgm** [comment]
@tarleb any progress on this? We should fix this before releasing 3.1.

**Comment by tarleb** [comment]
Looking at it now, but I don't understand yet what's going wrong.

**Comment by jgm** [comment]
I couldn't see anything obvious either, just looking at the code.  Probably needs some tracing to figure it out!

**Comment by tarleb** [comment]
I found a solution, but only for simple (i.e., single-image) figures. I don't have a good enough understanding of pptx yet, so I can't offer a more general fix.
