### ISSUE TITLE
chunkedhtml error "URL must be absolute" even if image URL is absolute

### ISSUE THREAD

**Issue by PlainMartin** [jgm/pandoc#8567]
**Explain the problem.**

Converting a Markdown document containing an absolute URL image such as 

`![Diagram](https://pandoc.org/diagram.svgz)`

will work fine in standalone document, but breaks -t chunkedhtml with this error:

`pandoc -f markdown -t chunkedhtml -s chunked.md -o chunked`

`Could not fetch https:/pandoc.org/diagram.svgz`
`InvalidUrlException "https:/pandoc.org/diagram.svgz" "URL must be absolute"`

Note that one slash has been removed from the image URL in this error message: `https://` > `https:/`.

Chunking works as expected without images.

**Pandoc version?**

pandoc 3.0 / macOS

**Comment by jgm** [comment]
Closed by dacdd0a56e105777be607de0d415c63bad4954e6
