### ISSUE TITLE
3.0 doesnt show up in homebrew

### ISSUE THREAD

**Issue by tim-hilde** [jgm/pandoc#8568]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/44113468/213718532-7d727b9c-8150-47d4-8d41-5595d32502f6.png">

**Comment by tarleb** [comment]
Thanks for the report, but note that we do not control the homebrew packge. See [the homebrew issue](https://github.com/Homebrew/homebrew-core/pull/120967) for info on the holdup. TL;DR: a number of other packages need to be updated to work with pandoc 3.
