### ISSUE TITLE
Set common state when pandoc is used as a Lua interpreter

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#8569]
`pandoc lua` currently runs without any translations defined. These are defined in `configureCommonState` in Text.Pandoc.App.  Suggestion:  export `configureCommonState` and use it in `runLuaInterpreter` in pandoc-cli (before `runLua`, which will then inherit the common state that is configured).

For now we'd probably have to set the datadir parameter to the default (Nothing).

@tarleb any thoughts?

**Comment by jgm** [comment]
@tarleb I'd be happy to make the change if you think it's a good idea.  It's a fairly simple one.

**Comment by tarleb** [comment]
Seems like a good solution :+1:

**Comment by jgm** [comment]
On closer look, it doesn't work.  We don't have `Opt` in that context, so we don't have the data configureCommonState would need.

**Comment by jgm** [comment]
Proper solution is for the HTML writer to call `setTranslations`
