### ISSUE TITLE
Bug with custom Latex environments with arguments in pandoc 3.0

### ISSUE THREAD

**Issue by abenthy** [jgm/pandoc#8573]
**Description:** When defining a custom environment with arguments using ``\newenvironment``, the Latex reader in pandoc 3.0 fails.

**Minimal example:**
```latex
\newenvironment{myenv}[1]{}{}
\begin{myenv}{x}\end{myenv}
```

**Error message:**
```
Error at (line 2, column 17): unexpected Tok (line 2, column 17) (CtrlSeq "end") "\\end"
expecting end of input Could not parse arguments for endmyenv \begin{myenv}{x}\end{myenv} ^
```

**Pandoc Version**: 3.0 (at https://pandoc.org/try/)

**Note**: With Pandoc 2.18 on Windows, the above example works fine.

**Comment by jgm** [comment]
I can confirm that it works fine with 2.19.2, so this seems to be a regression in 3.0 specifically.
The only relevant change I can see is 488ad80a20e71db187291ec32fd96c85814bf848

And I can confirm that reverting that commit makes the problem go away.

So at least we can localize it -- I need to look into it more to diagnose the problem.
