### ISSUE TITLE
Types reported by `pandoc.utils.types` are inconsistent

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#8574]
Some types have a `pandoc` prefix, while others do not. This should be consistent, at least for AST types.

**Comment by tarleb** [comment]
We can't add a `pandoc` prefix to AST types that don't have them right now, it would break many filters.

Options:

- Remove the prefix in the names of all AST types, including `Row`. Downside: this adds more unprefixed entries in the Lua registry, increasing the risk of name collisions with other libraries.
- Add the prefix to all names, but change `pandoc.utils.types` so it reports the name without the prefix. Downside: names in error messages would differ from the type name reported by `pandoc.utils.types`.

**Comment by wlupton** [comment]
There's also the question of separators. Currently we have (for example):
*  `List` for `pandoc.List`
* `pandoc Xxx` for `pandoc.Row` etc.
* `HsLua.JSON.array`
