### ISSUE TITLE
Default HTML styles in Pandoc 3.0

### ISSUE THREAD

**Issue by ekaterina-o** [jgm/pandoc#8577]
**Explain the problem.**
Default styles for standalone HTML in Pandoc 3.0 on Windows 7 64 looks bad (small font size, Times New Roman) in compare with earlier ones (middle font-size, Georgia). Is this a bug or a meant change? I liked Pandoc for an easy way to get well looking HTML by default and now have to stay on older version.

**Pandoc version?**
3.0

**Comment by jgm** [comment]
It's an intended change.  See #8423.
You should be able to change the font and font-size by using the `mainfont` and `fontsize` variables, which you can set via metadata in the file or on the command line with `-V`.

**Comment by ekaterina-o** [comment]
It would be better if this was in release notes.

**Comment by jgm** [comment]
It is.

```
 * HTML template:

    + Remove default font size, line height and font family in
      default inline css (#8423). `mainfont`, `fontsize`,
      and `linestretch` can still be used as before; the only difference
      is that we no longer provide opinionated defaults.
      This commit also adds a `maxwidth` variable that sets `max-width`;
      if not set, 36em is used as a default.
```
