### ISSUE TITLE
[Request] Modules for stripping: classes, images, ids

### ISSUE THREAD

**Issue by fulldecent** [jgm/pandoc#8579]
I am using pandoc to quickly read an HTML file, strip out a bunch of crap and save to Markdown. Then I am feeding that to a neural network. So anything useless thing pandoc can strip saves me money.

Here is one page I'm reading: https://www.monarchbehavior.com/resources/

```sh
curl https://www.monarchbehavior.com/resources/ > page.html
```

Doing the obvious:

```sh
pandoc -o page.md -i page.html
```

produces inline SVG images, class names and other things that don't add to a semantic understanding of the page.

**Please add `-strip-images` `-strip-empty-divs` and other modules to strip a lot of this stuff.**

---

## Workaround

A sort of workaround is to converts from HTML to something else that pandoc can't fit extra crap into, then convert again from there to Markdown. As pandoc adds more features this approach will be less effective.

Use this to get all formats pandoc can use as an input AND an output:

```sh
pandoc --list-input-formats > informat
pandoc --list-output-formats > outformat
cat informat outformat | sort | uniq -d
cat informat outformat | sort | uniq -d > inoutformat
```

Then do double hop with:

```sh
for type in $(cat inoutformat); do pandoc --sandbox -t $type page.html | pandoc --sandbox -f $type -o two-step/$type.md; done
```

If `wc` is an approximate for token count (how neural networks are processed) here is the relative performance:

```
wc -w out*               
     962 out-commonmark.md
     954 out-docx.md
     998 out-haddock.md
    1303 out-json.md
     955 out-latex.md
    1303 out-markdown.md
    1003 out-markdown_mmd.md
     989 out-markdown_phpextra.md
    1002 out-markdown_strict.md
    1317 out-mediawiki.md
    1303 out-native.md
       0 out-opml.md
    1245 out-org.md
    1286 out-rst.md
    1291 out-textile.md
```

**Comment by jgm** [comment]
I would think that using `-t text` would give you the sort of output you want.
Alternatively, you could try `-t commonmark` or `-t markdown_strict`.

**Comment by jgm** [comment]
In any case, the bottom line here is that pandoc already provides you the flexibility to do this; we don't need a new module.

**Comment by fulldecent** [comment]
Thank you, updated issue to show workaround with `--list-input-formats` and `--list-output-formats`.

Using the `plain` output type loses headings and hyperlinks which are useful semantic information.

---

Here is another workaround. Output to the JSON AST format and then edit that. Translate into Markdown from there.

```sh
cat ast.json |
jq 'del(.. | select(type == "object" and .t == "Image"))' | # kill images
jq 'walk(if type == "object" and .t == "Div" then .c[0][0] = "" else . end)' | # kill div ID
jq 'walk(if type == "object" and .t == "Div" then .c[0][1] = [] else . end)' | # kill div classes
cat > ast2.json
```

This tries to remove images, IDs and class names (but only for `Div`s). This could be extended to all elements that should have stuff deleted. Also this now outputs the empty divs.

**Comment by fulldecent** [comment]
Got it, thank you. The Lua filter really helped. Now using:

```
pandoc --lua-filter noimage.lua -f html -t commonmark-raw_html-raw_attribute -o try8.md page.html
```

and this is definitely usable, thanks!
