### ISSUE TITLE
inline code attributes within tables causes error in beamer output

### ISSUE THREAD

**Issue by simonlau** [jgm/pandoc#858]
```markdown
# Title

## Slide

Keyword      Explanation 
---------------   ------------------------
`if`{.python}  Decision making
```

causes the following:

pandoc: Error producing PDF from TeX source.
! Paragraph ended before \FancyVerbGetVerb was complete.
<to be read again> 
                   \par 
l.451 \end{frame}

**Comment by jgm** [comment]
Fixed by 2633dc2f5e6bb86e349fa2f2f7292d497f255a8d
