### ISSUE TITLE
chunkedhtml – title not placed / available in chunks when using custom template

### ISSUE THREAD

**Issue by PlainMartin** [jgm/pandoc#8580]
Transforming a Markdown file to chunkedhtml with a custom template loses the document title in all chunks (except for the first). (The same may apply to other metadata as well, I haven’t checked yet.)

source.md:

~~~
---
title: Hello world
---

# Chapter 1

# Chapter 2

~~~

chunked-template.htm:

~~~
<!DOCTYPE html>
<html>
<head><title>$title$</title></head>
<body>
<h1 class="doctitle">$title$</h1>
$body$ 
</body>
</html>
~~~

With:

`-f Markdown -t chunkedhtml -s --template=chunked-template.htm source.md -o chunks`
 
Result in chunk `index.html`:

~~~
<title>Hello world</title>
[…]
<h1 class="doctitle">Hello world</h1>
~~~

Result in chunks `1-chapter-1.html` and `2-chapter-2.html`:

~~~
<title></title>
[…]
<h1 class="doctitle"></h1>
~~~

The title (based on the heading used for splitting) is retained and used correctly when the _default_ template (as displayed with `-D chunkedhtml`) is used, but I couldn’t find out why.

Oddly, a navigation section (using `previous.title` and `next.title`) in a custom template references the _next_ and _previous_ chunk titles correctly.

**Pandoc version**

3.0.1

**Comment by jgm** [comment]
> The title (based on the heading used for splitting) is retained and used correctly when the default template (as displayed with -D chunkedhtml) is used, but I couldn’t find out why.

Default template has:

```
  <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
```
Have you tried putting that in your template?

(`$title$` can't be used because it can in general contain formatting that won't work for the title element, so we generate a textual version `$pagetitle$`.)

**Comment by PlainMartin** [comment]
Argh! I should put on glasses before studying templates.  😶

$pagetitle$ works.

Perfect. Thank you so much!

Cheers,

Martin






Am 26.01.2023 um 18:15 schrieb John MacFarlane ***@***.***>:


The title (based on the heading used for splitting) is retained and used correctly when the default template (as displayed with -D chunkedhtml) is used, but I couldn’t find out why.

Default template has:

  <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
Have you tried putting that in your template?

($title$ can't be used because it can in general contain formatting that won't work for the title element, so we generate a textual version $pagetitle$.)
