### ISSUE TITLE
Textile → gfm: [/quote] tag wrapped into preceeding link

### ISSUE THREAD

**Issue by geckolinux** [jgm/pandoc#8582]
Hi, this bug happens with the latest released version of Pandoc on my server and in the Pandoc live demo.

## Original Textile:
```
[quote=Somebody]Something.

!https://example.com/something.jpeg! 

"Link text":https://example.com/something.pdf[/quote]
```

## Expected Textile→gfm:
```
[quote=Somebody]Something.

![](https://example.com/something.jpeg)

[Link text](https://example.com/something.pdf)[/quote]
```

## Pandoc converted Textile→gfm:
```
\[quote=Somebody\]Something.

![](https://example.com/something.jpeg)

[Link text](https://example.com/something.pdf[/quote])
```

**Comment by jgm** [comment]
Textile reader doesn't currently know anything about `[quote]`.

**Comment by geckolinux** [comment]
> Textile reader doesn't currently know anything about `[quote]`.

Right, I wouldn't expect it specifically handle `[quote]` . But it seems pretty safe to assume that the URL ends where a `[` begins, I'm pretty sure brackets aren't allowed in the URL spec.

**Comment by geckolinux** [comment]
Thanks very much!
