### ISSUE TITLE
Height and width attrs are added to the figure tag

### ISSUE THREAD

**Issue by piccolbo** [jgm/pandoc#8588]
The height and width attrs are added to the figure tag by pandoc.Figure. They shouldn't. Check https://github.com/pandoc/lua-filters/issues/261 for MRE. Reporting per jgm comment on that issue.

**Pandoc version?**

3.0.2 on macos ventura.

**Comment by tarleb** [comment]
This seems to be an issue with pandoc-crossref, thus closing here.

**Comment by piccolbo** [comment]
I removed the crossref from the MRE and indeed the problem went away.

**Comment by jgm** [comment]
Sorry, my mistake in directing the issue here!
