### ISSUE TITLE
commonmark doesn't support fancy list '#.' form

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#8591]
With commonmark_x, the fancy list '#.' form appears not to work. [Here's a pandoc try example.](https://pandoc.org/try/?params=%7B%22text%22%3A%22%23.+This%5Cn%23.+doesn%27t%5Cn%23.+work.%5Cn%5Cn1.+But%5Cn2.+this%5Cn3.+does.%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22commonmark_x%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

I think this is just a documentation issue, and that a note could be added to the manual (modeled on the note that already explains the YAML metadata block restrictions). I'd be happy to create a PR.

**Comment by jgm** [comment]
Yes, please!

**Comment by wlupton** [comment]
Please see PR #8772.
