### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by axinav** [jgm/pandoc#8596]
**Explain the problem.**
Ranger fm uses pandoc for preview ODT or ODS. There is a memory leak when the ranger tries to run a command "pandoc -s -t markdown -- /home/alex/test-pandoc/15-74-82уточнениВ2.ods" for some files
I tried running this command in the console and saw on htop that RAM was running out very quickly

**Pandoc version?**
pandoc 2.19.2-54

[15-74-82уточнениВ2.ods](https://github.com/jgm/pandoc/files/10561365/15-74-82.2.ods)

**Comment by jgm** [comment]
With this command, pandoc would be treating the `.ods` file as markdown (which it defaults to if you don't specify a known extension).  I imagine you want it to be reading it as odt?  (I don't know what ods is but I assume it's an alternative extension for odt?)

This probably explains why pandoc is bogging down; it's trying to parse a big binary file as markdown.

Try with `-f odt`.

**Comment by jgm** [comment]
I see, ods is open document spreadsheet. Pandoc doesn't support that format, sorry.
Yes, markdown parser will bog down on a binary file.  That is arguably a problem, but it's solved in the commonmark parser, and it's only a problem in practice when you feed it inappropriate input.  So, closing this.
