### ISSUE TITLE
Citeproc issue with @inproceedings

### ISSUE THREAD

**Issue by DOFfactory** [jgm/pandoc#8597]
Not sure whether this is related to #7678 and #8595, but when I run pandoc (v. 3.0.1) I am getting the following error:

> pandoc -t json bibliography.bib
> Error at "bibliography.bib" (line 33, column 1):
> unexpected '@'
> @inproceedings{proc-in-abdelnabby_use_2020,
> ^

In the `bibliography.bib` file on line 33 I do not see anything unusual:

>...
>   keywords     = {Scopus-zotero},
>  readstatus   = {skimmed},
>  shorttitle   = {SPAG5 as a Prognostic Biomarker and Chemotherapy Sensitivity Predictor in Breast Cancer},
>  timestamp    = {2020-12-27T20:55:30Z},
>}
>
>@InProceedings{proc-in-abdelnabby_use_2020,
>  author     = {Abdelnabby, M. and Awny, M.M. and Ezzat, M.O.},
> ...

**Comment by jgm** [comment]
Trailing comma after timestamp?

**Comment by DOFfactory** [comment]
Tried to delete, but it did not fix the error

**Comment by DOFfactory** [comment]
Downgrading to scoop v2.19.2 works interestingly...

**Comment by jgm** [comment]
It's hard to evaluate this without a sample I can test with.
Please upload or paste a minimal bibtex file that will produce the error.

**Comment by jgm** [comment]
Most likely the problem lies in something *before* the @inproceedings line.

**Comment by scokobro** [comment]
Maybe related - I have had bibliography problems too, not specifically with '@inproceedings' entries. I did some spade work on my bibtex file, attempting to convert it to csljson with `pandoc -f bibtex -t csljson -s  -o ./mybib-checks.json mybib.bib`, It turns out that a field containing a `%` (ie lots of fields with urls) cause it to fail.

For me, this fails to convert and gives an 'unexpected end of input' error:
```
@article{keyhere,
	annote = {},
	author = {Name,First},
	title = {Titlehere},
	url = {},
	year = {2023},
	n1 = {%}
    }
```

whereas, this is ok...
```
@article{keyhere,
	annote = {},
	author = {Name,First},
	title = {Titlehere},
	url = {},
	year = {2023},
	n1 = {X}
    }
```
Hope this helps.

**Comment by jgm** [comment]
```
@article{keyhere,
	annote = {},
	author = {Name,First},
	title = {Titlehere},
	url = {},
	year = {2023},
	n1 = {%}
    }
```

Have you tried this with bibtex or biber? Does it actually work?  I would have thought `%` would make the `}` a comment.

**Comment by scokobro** [comment]
Haven't tried with bibtex/biber, but I guess that's what happening, thus the failure? It looks like after the first % all the brackets look unbalanced and whatever follows looks like a massive run on line, thus the 'unexpected end of input'  error. This issue appeared after moving to pandoc3 -- I have been using the same bib file, with BibDesk, for several years and have never experienced this before. 

Of course I am totally guessing but it seems like pandoc/citeproc(?) was previously skilfully ignoring fields with %s... now it's noticing, and ('correctly'?) protesting. The old behaviour would be preferable, plenty of my bib entries have a field with a URL-encoded link in.

As a temporary solution I have resorted to using BibDesk to export a 'minimal bibtex' version of my file --- removes comments, URLs for linked files(prime source of % chars!), bibdesk cruft etc --- and using this.

**Comment by antonyeagle** [comment]
Just reporting same issue as @scokobro, bib desk .bib files with '%' occurring in the 'bdsk-url-1', etc., fields used to be handled fine and now give rise to errors after upgrading to pandoc 3. Bibdesk and citeproc can however handle urls without the percent encoding, so a less drastic workaround than opting for the minimal bibtex file is simply to globally replace e.g. `%2F` with `/`, etc.

**Comment by jgm** [comment]
Tried it.  bibtex actually does accept the unescaped % here, interesting.

**Comment by jgm** [comment]
In general you should escape your %s: `\%`.  The exception is in URL and DOI fields.
We can probably make pandoc's bibtex parsing more forgiving, though.

**Comment by jgm** [comment]
I suspect the commit I just pushed will fix the original issue, but let me know if it doesn't.
