### ISSUE TITLE
Provide a `pandoc.json` Lua JSON library

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#8605]
It would be great to have access to pandoc's JSON handlers. Part of this is that JSON support in Lua is slightly opinionated, as there is no default method to represent JSON `null` values: while some libraries use `nil`, others use special table values or C null pointers (as light userdata). Pandoc, when marshaling values via JSON, uses null pointers.

One of the advantages of shipping a JSON library would be that it would use the existing encoding method, avoiding potentially subtle bugs.

Proposed functions:

- `pandoc.json.encode`: converts the given Lua object to JSON. All pandoc *userdata* objects (blocks, inlines, etc) should result in their default JSON encoding. Objects with a `__tojson` metamethod would be encoded by invoking that function.
- `pandoc.json.decode`: the inverse function; tries to decode the JSON as AST element or \*Option value, but falls back to a normal Lua table if that's not possible.
- Field `pandoc.json.null` containing the null pointer as light userdata.

Cc: @cscheid

**Comment by tarleb** [comment]
Right, we can base this on Aeson.

(We could think about bundling cjson in the future, which would give better performance in the general "Lua table :left_right_arrow: JSON" case; but that'd most likely be overkill.)

**Comment by cscheid** [comment]
Thank you for considering this! To clarify the particular pain point, the table caption `Caption` object is finicky. Its standard JSON representation is an array whose first value is often `null`. Then, the emitted JSON will have an array (eg) `[null, "etc"]`. This is a bit annoying to handle in Lua if a library uses Lua `nil` to denote JSON `null`, because Lua style strongly discourages "sparse" integer-indexed tables (`ipairs` will behave strangely, etc).

In our case, this manifested as the json library quarto uses fails to correctly round-trip an empty table:

```lua
local foo = pandoc.read("<table><tr><td></td></tr></table>", "html")
local json_string = pandoc.write(foo, "json")
quarto.json.encode(quarto.json.decode(json_string)) -- the call to `encode` fails
```

**Comment by gpoore** [comment]
This would be very useful. I'm just about to release a VS Code extension that will provide HTML previews with scroll sync for any text-based Pandoc input format, and JSON support is the only area where I've had to look for external Lua libraries.

If I'm understanding the proposal correctly, the encode/decode functions would be focused on AST elements. If it doesn't add much complexity, it would also be helpful in filters to have general encoding/decoding functionality (perhaps with some type restrictions for simplicity). Maybe something like `pandoc.json.decode` for general decoding, and `pandoc.json.decodeAst` for AST elements.

**Comment by jgm** [comment]
I think @tarleb's proposal is that pandoc AST elements would be encoded using pandoc's JSON encoding, but other things (regular Lua tables for example) would still be encoded into JSON in a standard way.  (Similarly decoded.)

**Comment by tarleb** [comment]
Thanks for the feedback! My current approach is to have `decode` take a second parameter that would control AST element parsing. E.g.,

``` lua
pandoc.json.decode('{"t": "Space"}')
```

should create a `pandoc.Space()` uderdata element, while

``` lua
pandoc.json.decode('{"t": "Space"}', false)    -- or
pandoc.json.decode('{"t": "Space"}', {})
```

should result in a table with field `t`.

**Comment by gpoore** [comment]
@tarleb That sounds good! Having an optional argument that controls userdata vs plain table would do everything I need and avoid ambiguity about intended type for decoded data.
