### ISSUE TITLE
chunkedhtml: variables only applied on first page, then discarded / reset

### ISSUE THREAD

**Issue by PlainMartin** [jgm/pandoc#8620]
**Explain the problem.**

It seems that with output to [chunkedhtml](https://pandoc.org/MANUAL.html#chunked-html), variables as set…

1. in a YAML block in the Markdown source documents
2. YAML defaults files
3. on the command line 

…are only used on the first page (index.html) and then lost / reset, so it’s not possible to work with conditionals and metadata in a template.

I have created a simple test case, and doing this:

	pandoc
	--standalone
	--from=markdown
	--to=chunkedhtml
	--toc
	--split-level=2
	--template=chunking_test_template.htm
	--defaults=chunking_test_metadata.yml
	--metadata metavar1fromcommandline="value"
	chunking_test_source.md
	--output=chunking_test_output_folder

will use the variables (from the .md and .yml files and on the command line) on “index.html” only.

“--toc” is set on the command line, but no table of contents is placed on the pages following “index.html” (it is wrapped in a `$if(toc)$`conditional in the template, which seems to be reset/lost as well).

Please note that I may misunderstand (the limitations of) chunkedhtml.

Thank you for looking into this.

**Pandoc version?**

3.1
![chunking_test_results](https://user-images.githubusercontent.com/304187/218726119-aa8b468f-f532-450f-9fad-09d207f8d5ed.png)

**Comment by jgm** [comment]
I will look into this. You should be able to set a variable (e.g. `toc`) explicitly on the command line, e.g. `--variable toc`.

**Comment by PlainMartin** [comment]
Thank you for looking into this! I tried, and I can confirm that --variable on the command line *does* work. 

Header YAML block and YAML default file variables are still lost after “index.html”.

**Comment by jgm** [comment]
Here is why:
```hs
chunkToEntry :: PandocMonad m
             => WriterOptions -> Meta -> Chunk -> Chunk -> m Entry
chunkToEntry opts meta topChunk chunk = do
  html <- writeHtml5String opts' (Pandoc meta' blocks)
  epochtime <- floor <$> getPOSIXTime
  let htmlLBS = BL.fromStrict $ TE.encodeUtf8 html
  return $ toEntry (chunkPath chunk) epochtime htmlLBS
 where
  opts' = opts{ writerVariables =
                  addContextVars opts' topChunk chunk $ writerVariables opts }
  meta' = if chunk == topChunk
             then meta
             else Meta $ M.fromList [("pagetitle", MetaString
                                     (stringify $ chunkHeading chunk))]
  blocks = chunkContents chunk
```
See definition of `meta'`.  The metadata from the document is used in rendering the top chunk, but for the others we just use empty metadata + a pagetitle.  I think the reason for this was to avoid repeating the title, author, date, abstract, etc. on every section.  You certainly wouldn't want that.  Perhaps we could handle that another way though, e.g. by setting a special variable for the top chunk and having a conditional in the template for the title, author, etc. so that it only renders on the top chunk.

**Comment by PlainMartin** [comment]
Thank you for looking into this.

> I think the reason for this was to avoid repeating the title, author, date, abstract, etc. on every section. 

Which makes sense for many document types, I guess, but what I’m building (essentially a single source publishing solution for manuals) relies on a bazillion variables, so it falls apart when these are gone on page 2…

The Shell script loops through folder structures and copies multiple YAML files to the directory with the Markdown sources as required, so the alternative we have now (just putting everything on the command line) wouldn’t work.


￼


M.




Am 15.02.2023 um 18:24 schrieb John MacFarlane ***@***.***>:


Here is why:

chunkToEntry :: PandocMonad m
             => WriterOptions -> Meta -> Chunk -> Chunk -> m Entry
chunkToEntry opts meta topChunk chunk = do
  html <- writeHtml5String opts' (Pandoc meta' blocks)
  epochtime <- floor <$> getPOSIXTime
  let htmlLBS = BL.fromStrict $ TE.encodeUtf8 html
  return $ toEntry (chunkPath chunk) epochtime htmlLBS
 where
  opts' = opts{ writerVariables =
                  addContextVars opts' topChunk chunk $ writerVariables opts }
  meta' = if chunk == topChunk
             then meta
             else Meta $ M.fromList [("pagetitle", MetaString
                                     (stringify $ chunkHeading chunk))]
  blocks = chunkContents chunk
See definition of meta'. The metadata from the document is used in rendering the top chunk, but for the others we just use empty metadata + a pagetitle. I think the reason for this was to avoid repeating the title, author, date, abstract, etc. on every section. You certainly wouldn't want that. Perhaps we could handle that another way though, e.g. by setting a special variable for the top chunk and having a conditional in the template for the title, author, etc. so that it only renders on the top chunk.

**Comment by jgm** [comment]
This could use further testing, so try it out.

**Comment by PlainMartin** [comment]
> This could use further testing, so try it out.

I have now tested the nightly build with fairly complex templates and document sets, and everything seems to work fine. Looking forward to seeing this in the next release. 

Thank you! For what I’m planning, this is a major step forward.
