### ISSUE TITLE
Pandoc 3.1: Url fragment is not generated, when section heading only contain ascii characters (with markdown output)

### ISSUE THREAD

**Issue by lamyergeier** [jgm/pandoc#8624]
## Problem

- Works with html output

  ```bash
  $ echo "VariaLà " | sed -r -e 's/^/# /' | pandoc --from=markdown+auto_identifiers+ascii_identifiers --to=html
  <h1 id="variala">VariaLà</h1>
  ```
- Works with html output (only ascii input)
  
  ```bash
  $ echo "VariaL " | sed -r -e 's/^/# /' | pandoc --from=markdown+auto_identifiers+ascii_identifiers --to=html
  <h1 id="varial">VariaL</h1>
  ```

- Works with markdown output
  
  ```bash
  $ echo "VariaLà " | sed -r -e 's/^/# /' | pandoc --from=markdown+auto_identifiers+ascii_identifiers --to=markdown
  # VariaLà {#variala}
  ```

- Does not Works with markdown output (only ascii input)

  ```bash
  $ echo "VariaL " | sed -r -e 's/^/# /' | pandoc --from=markdown+auto_identifiers+ascii_identifiers --to=markdown
  # VariaL
  ````

## Expected output

-  Works with markdown output (only ascii input)

  ```bash
  $ echo "VariaL " | sed -r -e 's/^/# /' | pandoc --from=markdown+auto_identifiers+ascii_identifiers --to=markdown
  # VariaL {#varial}
  ````

## Software

**Pandoc version?**
On, Ubuntu 22.10

```bash
$ pandoc --version
pandoc 3.1
Features: +server +lua
Scripting engine: Lua 5.4
```

**Comment by jgm** [comment]
Actually, the identifier IS generated. You can see that with `-t native`:
```
% echo "VariaL " | sed -r -e 's/^/# /' | pandoc --from=markdown+auto_identifiers+ascii_identifiers --to=native 
[ Header 1 ( "varial" , [] , [] ) [ Str "VariaL" ] ]
```
It just isn't printed explicitly in markdown output.  Why?  Because by default markdown output includes the `auto_identifiers` extension.  Since `VariaL` is exactly the identifier that will be generated automatically from this input, pandoc sees that it is redundant to add `{#VariaL}` and omits it.

Not a bug, a feature!

**Comment by lamyergeier** [comment]
Is it possible to make pandoc print this redundant information (with some options or extensions)? 

I need this in the situation: 

> Sometimes when I refer to a section in another document, the url should contain the section fragment. 
> I explicitly write it down in the source markdown document next to the section heading to avoid any future confusion. 
> So I wanted pandoc to generate the fragments .

**Comment by tarleb** [comment]
```
% echo '# VariaL' | pandoc -f markdown+ascii_identifiers --to=markdown-auto_identifiers
# VariaL {#varial}
```
