### ISSUE TITLE
Update MathJax implementation to include required polyfill

### ISSUE THREAD

**Issue by ErroneousBosch** [jgm/pandoc#8625]
**Explain the problem.**
The current embed of MathJax 3 for standalone HTML does not work properly for rendering. This is because per the MathJax "getting started", they also require a polyfill: https://www.mathjax.org/#gettingstarted

The correct script tags should be:

```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Pandoc version?**
3.1

**Comment by jgm** [comment]
Thanks for pointing that out!
