### ISSUE TITLE
docbook xref to table

### ISSUE THREAD

**Issue by ciklysta** [jgm/pandoc#8626]
This bug is very similar to an already solved bug #8064.

When an _xref_ in a _docbook_  format source document points to a _table_, the text of the link is `table_title`, not the actual table title. The referenced closed issue solves the same problem, but only for a _figure_ element.

Affected versions: all

The solution is very similar to the referenced. Actually I have already prepared it, I can create a PR when you confirm it.

**Comment by jgm** [comment]
Yes a PR would be welcome. Should be quite similar to #8065
