### ISSUE TITLE
No localised double quotes in output

### ISSUE THREAD

**Issue by amigalemming** [jgm/pandoc#8632]
~~~~
$ cat test.md
"Hello World"
$ pandoc --standalone --variable=lang:de test.md --output=test.pdf
~~~~

The resulting PDF shows English double quotes, not German ones. Is this a bug or do I misunderstand documentation?

~~~~
$ pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.4, skylighting 0.13.1.1,
citeproc 0.8.0.2, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: ~/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
~~~~

**Comment by amigalemming** [comment]
Same with pandoc-3.1.

**Comment by tarleb** [comment]
Try with

    pandoc --variable=lang:de test.md --variable csquotes --output=test.pdf

**Comment by tarleb** [comment]
Or if you need support for more output formats, checkout <https://github.com/odkr/pandoc-quotes.lua>.

**Comment by amigalemming** [comment]
On Fri, 17 Feb 2023, Albert Krewinkel wrote:

> Or if you need support for more output formats, checkout 
> https://github.com/odkr/pandoc-quotes.lua.

I actually need RTF output.

csquotes works for me for PDF output.

**Comment by tarleb** [comment]
Great, closing then.

**Comment by amigalemming** [comment]
On Fri, 17 Feb 2023, Albert Krewinkel wrote:

> Great, closing then.

Not quite. The lua-script does not seem to have an effect for RTF output 
for me. Would it be sensible to have a solution without external scripts?

**Comment by amigalemming** [comment]
On Sat, 18 Feb 2023, amigalemming wrote:

> Not quite. The lua-script does not seem to have an effect for RTF output
> for me. Would it be sensible to have a solution without external scripts?

My quick hack for now is post-processing with regular expressions:

%.rtf:	%-eng.rtf
 	perl -p -e "s:\\u8220:\\u8222:g" $< | \
 	  perl -p -e "s:\\u8221:\\u8220:g" >$@

**Comment by tarleb** [comment]
Using `--metadata=lang:de` instead of `--variable` should do the trick, I think.

**Comment by amigalemming** [comment]
On Sat, 18 Feb 2023, Albert Krewinkel wrote:

> Using --metadata=lang:de instead of --variable should do the trick, I think.

I see. This one works for me:

%.rtf:	%.tex
 	pandoc --lua-filter ~/.local/share/pandoc/pandoc-quotes.lua --standalone --metadata lang:de --output=$@ $<
