### ISSUE TITLE
GitHub now supports LaTeX in three-tick code block syntax ```math

### ISSUE THREAD

**Issue by fasiha** [jgm/pandoc#8633]
GitHub [recently(?)](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-expressions-as-blocks) began rendering content inside <code>```math</code> code blocks as LaTeX equations, that is,
```md
```math
x = 1
``\
```
get rendered the same way as
```md
$$x = 1$$
```
Example:
```math
x = 1
```

However it appears that Pandoc's `gfm` doesn't handle this. I'm trying `pandoc -f gfm+tex_math_dollars --mathjax -s -t html5 -i issue.md -o issue.html` and the code block syntax is rendered in HTML as a plain code block.

I am experimenting with ```math syntax because GitHub won't typeset LaTeX inside double-dollar notation if it spans multiple lines. For example, below is GitHub's rendering of the following:
```md
$$
  x =
  2
$$
vs
```math
  x =
  3
``\
```

$$
  x =
  2
$$
vs
```math
  x =
  3
```

As you can see, it butchers the double-dollar multi-line equation but ```math is fine.

I know the risks of breaking with established patterns (like double-dollar signs, beautifully supported by LaTeX and Pandoc and many other tools for decades now) for syntax unilaterally introduced by Microsoft, which is why I am only tentatively experimenting with it.

A thousand apologies if this has been discussed before but I couldn't find it.

**Comment by jgm** [comment]
It's unfortunate that their implementation of $$ math has this limitation.

We can consider adding this, but in the mean time you can easy handle this with a short Lua filter that matches a CodeBlock with class `math` and replaces it with `Para [Math DisplayMath ((contents))]`.

**Comment by jgm** [comment]
Folding this into #9121 which also has the new inline math format.

**Comment by jgm** [comment]
$$
  x =
  2
$$
vs
```math
  x =
  3
```

**Comment by jgm** [comment]
Interestingly, adding a newline after the closing `$$` makes it work.
