### ISSUE TITLE
The table convert to beamer PDF has no bottom border

### ISSUE THREAD

**Issue by cyoki** [jgm/pandoc#8638]
First I use the latest version 3.1, and try to convert table

```
fruit| price
-----|-----:
apple|2.05
```

to beamer pdf, but the the generated table in pdf have no bottom boarder.

Then I use version 2.18 to test it again, the table in pdf works, so I think this is a bug.

and the extension tables in ["Pandoc Use's Guide"](https://pandoc.org/MANUAL.html#pandocs-markdown) do not work in version 3.1 when converted to beamer pdf, but they works in version 2.18

Thanks.

**Comment by jgm** [comment]
I can confirm there's a difference.  pandoc 2.19.2 gives us:
```
\begin{longtable}[]{@{}lr@{}}
\toprule()
fruit & price \\
\midrule()
\endhead
apple & 2.05 \\
\bottomrule()
\end{longtable}
```
but 3.1 gives
```
\begin{longtable}[]{@{}lr@{}}
\toprule\noalign{}
fruit & price \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
apple & 2.05 \\
\end{longtable}
```

**Comment by jgm** [comment]
Oddly, we get the same thing with `-t latex`, but with LaTeX we get a bottom border anyway.  Not sure yet why this difference, or why this changed.

**Comment by jgm** [comment]
Looking at changes since 2.19.2, this commit stands out as the possible culprit:  7b7a7d6742cb775b66aad59dd812916ba9530085

Relevant part of diff:
```diff
     $$ head'
     $$ "\\endhead"
-    $$ vcat rows'
+    $$ foot'
     $$ "\\bottomrule()"
+    $$ "\\endlastfoot"
+    $$ vcat rows'
     $$ "\\end{longtable}"
     $$ captNotes
     $$ notes
```

@tarleb can you have a look at this?

**Comment by tarleb** [comment]
Will do. This is rather puzzling.

**Comment by tarleb** [comment]
It looks like this issue results from the interaction of Beamer and longtable: https://tex.stackexchange.com/q/124939

The only option I see is to restore the previous table structure for beamer output. This will give incorrect results for multi-page tables, but it seems that this will be the case either way. Is there an alternative?

**Comment by jgm** [comment]
Oh, that's unfortunate.  Well, I can't think of a better alternative than the one you suggest.  It seems this will still allow tables to be broken between slides, but we won't get the header repeated on subsequent slides, correct?
