### ISSUE TITLE
Underscore in URI link in markdown can cause problems when converted to HTML

### ISSUE THREAD

**Issue by jackanory101** [jgm/pandoc#8642]
I have **local files in folders beginning with an underscore**. If I link to the file with simple link, eg

`<file:///c:\user\_files\file.txt>`

the link is converted into HTML correctly. 

However, if I use the same URI with more complex form of link in markdown, eg

`[my link](file:///c:\user\_files\file.txt)`

the **slash** before the underscore is removed, presumably because it's misinterpreted as an **escaped underscore**. 

It becomes

`<a href="file:///c:\user_files\file.txt">my link</a>`

Of course I could use unix-like forward slashes in URI but I like the fact I can copy file path in Windows (with windows-path backslash separators) and simply paste into markdown without the palaver of reversing the path separators, and browser doesn't mind.

**Comment by jgm** [comment]
We need backslash escapes to work in the URL part of a link, in general.
The only thing I can think of is that perhaps the form
```
[my link](<file:///c:\user\_files\file.txt>)
```
should disable backslash escapes, for consistency with autolinks like 
```
<file:///c:\user\_files\file.txt>
```
However, that's a potentially breaking change that I'd be very reluctant to make. (Similar issue in commonmark, which behaves like pandoc, so there a spec change would be required.)  We might end up making life easier for you at the cost of breaking links that previously worked for many other people.

**Comment by jackanory101** [comment]
I'm not concerned personally. Now I know the issue , it's not a big deal to reverse the path separators _in the case of underscores at the start of folder and file names_.

**Comment by jgm** [comment]
OK, let's close this then.
