### ISSUE TITLE
workaround for keeping `th` vs `td` information in a Table through html's table reader

### ISSUE THREAD

**Issue by cscheid** [jgm/pandoc#8647]
Pandoc (I tried 2.19.2 and 3.1) appears to not keep track of `th` vs `td` elements in table bodies.

Consider this example:

````
$ cat pandoc-tables-th.html
<table>
  <tr><td>1</td><td>2</td></tr>
  <tr><td>3</td><th>4</th></tr> <!-- note "th" here -->
</table>
$ pandoc pandoc-tables-th.html
<table>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>3</td>
<td>4</td>
</tr>
</tbody>
</table>
````

It seems that Pandoc has a specific opinion on how to support and emit `th` vs `td`. Using `th` in non-standard places is somewhat unusual HTML syntax, but is allowed [by the HTML spec](https://html.spec.whatwg.org/multipage/tables.html#the-th-element) and there's good reasons to support it. Specifically, when it comes to accessibility, `th` elements are treated differently by screen readers.

**Describe your proposed improvement and the problem it solves.**

It would be very useful to track the `th` information inside the Cell elements, so that `th`-in-body tables were possible to produce with Pandoc. (This comes up in quarto because we parse HTML tables and allow Lua filters to operate on the resulting AST.)

I think the simplest solution would be to enrich the Cell data type to carry `td` or `th` with it, and make it so that html formats emit those.

In addition, the current parser appears to ignore `colspan` attributes in `th` elements in the body:

```
$ cat pandoc-table-body-colspan.html
<table>
    <tr><td>1</td><td>2</td></tr>
    <tr><th colspan="2">a heading</th></tr>
</table>
$ pandoc pandoc-table-body-colspan.html
<table>
<tbody>
<tr class="odd">
<th>1</th>
<td>2</td>
</tr>
<tr class="even">
<th>a heading</th>
<td></td>
</tr>
</tbody>
</table>
```

Note how we lost the `colspan` in that entry. It doesn't make it to the AST node:

```
$ pandoc pandoc-table-body-colspan.html -t native
[ Table
    ( "" , [] , [] )
    (Caption Nothing [])
    [ ( AlignDefault , ColWidthDefault )
    , ( AlignDefault , ColWidthDefault )
    ]
    (TableHead ( "" , [] , [] ) [])
    [ TableBody
        ( "" , [] , [] )
        (RowHeadColumns 1)
        []
        [ Row
            ( "" , [] , [] )
            [ Cell
                ( "" , [] , [] )
                AlignDefault
                (RowSpan 1)
                (ColSpan 1)
                [ Plain [ Str "1" ] ]
            , Cell
                ( "" , [] , [] )
                AlignDefault
                (RowSpan 1)
                (ColSpan 1)
                [ Plain [ Str "2" ] ]
            ]
        , Row
            ( "" , [] , [] )
            [ Cell
                ( "" , [] , [] )
                AlignDefault
                (RowSpan 1)
                (ColSpan 1)
                [ Plain [ Str "a" , Space , Str "heading" ] ]
            , Cell
                ( "" , [] , [] ) AlignDefault (RowSpan 1) (ColSpan 1) []
            ]
        ]
    ]
    (TableFoot ( "" , [] , [] ) [])
]
```

Notably, `colspan` _is_ supported in the tablehead itself:

```
$ cat pandoc-table-head-colspan.html
<table>
    <tr><th colspan="2">a heading</th></tr>
    <tr><td>1</td><td>2</td></tr>
</table>
$ pandoc pandoc-table-head-colspan.html
[ Table
    ( "" , [] , [] )
    (Caption Nothing [])
    [ ( AlignDefault , ColWidthDefault )
    , ( AlignDefault , ColWidthDefault )
    ]
    (TableHead
       ( "" , [] , [] )
       [ Row
           ( "" , [] , [] )
           [ Cell
               ( "" , [] , [] )
               AlignDefault
               (RowSpan 1)
               (ColSpan 2)
               [ Plain [ Str "a" , Space , Str "heading" ] ]
           ]
       ])
    [ TableBody
        ( "" , [] , [] )
        (RowHeadColumns 0)
        []
        [ Row
            ( "" , [] , [] )
            [ Cell
                ( "" , [] , [] )
                AlignDefault
                (RowSpan 1)
                (ColSpan 1)
                [ Plain [ Str "1" ] ]
            , Cell
                ( "" , [] , [] )
                AlignDefault
                (RowSpan 1)
                (ColSpan 1)
                [ Plain [ Str "2" ] ]
            ]
        ]
    ]
    (TableFoot ( "" , [] , [] ) [])
]
```

**Describe alternatives you've considered.**

N/A

**Potential issues**

I think this might cause a slight bit of backwards incompatibility, because some Pandoc chooses to use th and td in ways that I don't quite understand. My proposed AST change would mean that for an HTML reader, there would be explicit `th` and `td` preservation. The other readers could emit a TH marker for the first cell of a row (or whatever is the relevant Pandoc logic), and so the table HTML output would still be preserved.

**Comment by jgm** [comment]
I think you've got to acknowledge the limitations described here:
https://pandoc.org/MANUAL.html#description

Pandoc has to support a wide variety of formats; for most of them, designating a random cell as a header is going to be senseless.

**Comment by jgm** [comment]
Note also that pandoc doesn't ignore colspans in headers. This works:
```
<table>
    <tr><th colspan="2">a heading</th></tr>
    <tr><td>1</td><td>2</td></tr>
</table>
```
But pandoc does expect the header to come at the beginning, or at least of the beginning of a tbody.  Try this:
``` html
<table>
<tbody>
    <tr><td>1</td><td>2</td></tr>
</tbody>
<tbody>
    <tr><th colspan="2">a heading</th></tr>
</tbody>
</table>
```

**Comment by cscheid** [comment]
> or at least of the beginning of a tbody.

Ah, fantastic! This should 100% work around our problem. The issue we're seeing is precisely in a `th` not in the first `tr` of the `tbody`. This is definitely something I can ask the upstream table authors to change this about the tables they emit.

Thank you so much, we'll document this on our side as well.

> Pandoc has to support a wide variety of formats

Just to record that I'm deeply sympathetic to this view (and more than a little in awe of the format list!). My suggestion was meant in an attempt to make the HTML reader more faithful to the HTML format, but I completely understand if that's not practical in the much broader context of Pandoc!

Thanks again.
