### ISSUE TITLE
Support Sphinx domain-specific roles

### ISSUE THREAD

**Issue by jpfeuffer** [jgm/pandoc#8653]
**Describe your proposed improvement and the problem it solves.**
Handle :py:class:`.~Foo` the same as any other role. Maybe with both py and class as attribute for HTML.

rst -> ipynb:
![image](https://user-images.githubusercontent.com/8102638/220985059-298d6643-4055-4ce0-bd9b-c87c009ec6bb.png)

At least the :py should be gone.
I have not tried directives in domains yet.

**Describe alternatives you've considered.**
I considered writing a custom filter but I don't have any idea how to capture these specific roles. I guess they would be Spans? But it seems like the parser does not even include the :py in the Span.

**Comment by jgm** [comment]
Is it possible to chain interpreted roles like this in RST, so that ``:py:class:`foo` `` adds both `py` and `class` roles?  I didn't know that and pandoc doesn't support it. Point me to the documentation for this?

**Comment by jpfeuffer** [comment]
It indeed seems to be a Sphinx-specific feature.

**Comment by jgm** [comment]
Do you mean that the `py` role is Sphinx-specific, or the chaining of roles?

**Comment by jpfeuffer** [comment]
I think the whole chaining is Sphinx-specific :(

**Comment by jpfeuffer** [comment]
It's not really a chaining of roles but the :py:class role can do something different than the :cpp:class: role

**Comment by jpfeuffer** [comment]
Is it forbidden according to docutils RST to have colons inside a role? Otherwise one could just interpret it as a different role name and use the furthest colon until a whitespace.

**Comment by jgm** [comment]
I don't know, you could check their documentation or experiment with rst2html.

**Comment by jpfeuffer** [comment]
From the specification:

```
A role name is a single word consisting of alphanumerics plus isolated internal hyphens, underscores, plus signs, colons, and periods; no whitespace or other characters are allowed. A role marker is either a prefix or a suffix to the interpreted text, whichever reads better; it's up to the author.
```

So, I feel like pandoc should create e.g. a Span with class py:class for the above-mentioned example, correct?

**Comment by jgm** [comment]
Yes, sounds like it should.
