### ISSUE TITLE
Support Antiword Formatted Text as a Means to Indirectly Support Importing Legacy MS Word .doc Files

### ISSUE THREAD

**Issue by jeffgazso** [jgm/pandoc#8654]
**Describe your proposed improvement and the problem it solves.**

Pandoc lacks an import filter for legacy MS Word `.doc` files. While the Office Open XML-based `.docx` standard long ago displaced it, there are still a great many old school MS Word files floating around the Internet that could be "liberated" into any format Pandoc supports.

Decades ago [Antiword](https://en.wikipedia.org/wiki/Antiword) solved this problem by extracting the raw unformatted text of MS Word documents. What's less well known is that antiword has its own markup format that preserved the formatting (to extent) of the underlying MS Word file. It's that format — antiword's own markup format — that I'm suggesting Pandoc support as an import filter. Antiword also has an XML output option, which could work as well, but I'm not sure I've ever used it and I'm hazy on how well it could be supported by pandoc.

As I'm sure you'll notice, antiword hasn't been under active development for some time, but it's still used in a number of places as an import filter even today. The most prominent example I can think of off the top of my head is [Scribus](https://en.wikipedia.org/wiki/Scribus), but I'm sure there are other examples.

**Describe alternatives you've considered.**

Converting `.doc` files to Pandoc's Markdown can already be done *indirectly* by means of LibreOffice, simply by converting the file to Open Document Text (`.odt`) and then leveraging pandoc to convert the `.odt` to the desired file format. But, this option is rather heavyweight and the combination of  Pandoc and antiword is lightweight. Further, it's probably more lossy with respect to formatting than it would be if antiword's markup was supported by Pandoc.

**Comment by jgm** [comment]
I'm not sure we need anything new for this.  I had success with
```
antiword -x db my.doc  | pandoc -f docbook 
```
We already support docbook, and `antiword -x db` produces that format.

**Comment by jgm** [comment]
By the way, this is good to know. I'll add it to the FAQs.

**Comment by jeffgazso** [comment]
@jgm, Thanks! 

I completely missed antiword's docbook support when I looked at the man page. You're right, this is definitely pandoc FAQ material; people can use this. Much appreciated.
