### ISSUE TITLE
pandoc loops when parsing org table

### ISSUE THREAD

**Issue by phmarek** [jgm/pandoc#8659]
** Problem **

When using `pandoc` to convert org-mode into PDF (via LaTeX), it seems to hang; it didn't proceed to calling `xelatex` after a few minutes CPU time, so I killed it via Ctrl-C.

```bash
pandoc -o xyz.pdf --default-image-extension=svg  --variable=... --extract-media ... --number-sections --toc  --pdf-engine=xelatex  --template=...   -f org <files...>
```

`top` said
```
  72915 user1     20   0  203,4g   2,9g  76744 R  93,8   9,2   1:31.57 2 pandoc -o ...
```
when I killed it.

Last think I added to my (admittedly largish) document was a table:

```org
+--------------------------------------------------+-------------+-------------+-----------+ 
|                                                  |             |             |         |
+:=================================================+============:+============:+==========:+ 
| a                                                |  b          | c           | d         |
+--------------------------------------------------+-------------+-------------+-----------+ 
```

When the header line gets fixed (too small last field expanded to correct size), =pandoc= (3.1) works as expected and proceeds to =xelatex= after a second or two.

**Pandoc version**
Happened with 2.19.2 and 3.1, on Debian testing.

**Comment by jgm** [comment]
I can confirm the bug. It has nothing to do with generating LaTeX; the issue is in parsing the above table in org mode.
@tarleb do you want to have a look?

**Comment by tarleb** [comment]
Thanks for the report.
