### ISSUE TITLE
Support LaTeX math in citations

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#866]
Currently math in the title of a bibtex citation is not parsed as math -- it comes across in HTML, for example, with the literal `$` characters.

Perhaps pandoc could make a pass through titles and just parse LaTeX math?

**Comment by mdekauwe** [comment]
Whilst this works when converting markdown to PDF, it doesn't for me when converting markdown to docx. For example if I had: "CO$_2$" then I get CO~2~ in my PDF but I get a weird square character between the O and the 2 in the docx file.

**Comment by jgm** [comment]
What version of pandoc?  Some issues with subscripts in docx
were fixed fairly recently.  I'd suggest using the latest
version if you aren't.

+++ Martin De Kauwe [Oct 31 16 20:42 ]:

**Comment by mdekauwe** [comment]
It is the latest version I think:

$ pandoc --version
pandoc 1.18

The latex generated PDF file is fine when the bibtex entry has {C}O$_2$ in the title, but not the docx.

**Comment by jgm** [comment]
--version should also say what version of texmath it was
compiled against, and this would be helpful to know

+++ Martin De Kauwe [Nov 01 16 02:28 ]:

**Comment by mdekauwe** [comment]
pandoc 1.18
Compiled with pandoc-types 1.17.0.4, **texmath 0.8.6.6**, highlighting-kate 0.6.3

Here is a screen print example:

<img width="752" alt="screen shot 2016-11-01 at 8 53 09 pm" src="https://cloud.githubusercontent.com/assets/278045/19885917/55950170-a075-11e6-8397-2adb75893f5c.png">

**Comment by jgm** [comment]
Can you attach or link to the docx?
I can't reproduce this.

**Comment by jgm** [comment]
Ah, I also wonder about the pandoc-citeproc version, and how
you compiled/obtained it?  Finally, what are you using to
look at the Word document?

+++ Martin De Kauwe [Nov 01 16 02:54 ]:

**Comment by mdekauwe** [comment]
I made a simple example that replicates it but it won't let me paste it here. I could email it?

I was looking at the document in MS Word.

$ pandoc-citeproc --version
pandoc-citeproc 0.10.2.1

**Comment by jgm** [comment]
If you just produce a docx using pandoc from the source

    $CO_2$

do you see the square?  My current speculation is that you may be using a version of pandoc-citeproc that was compiled against an earlier version of texmath, and this would be confirmed if you saw the square only with tex math in citations.

**Comment by jgm** [comment]
+++ Martin De Kauwe [Nov 01 16 04:17 ]:
>   I made a simple example that replicates it but it won't let me paste it
>   here. I could email it?

Sure, you can email me at jgm at berkeley dot edu.

>   I was looking at the document in MS Word.
>
>   $ pandoc-citeproc --version
>   pandoc-citeproc 0.10.2.1

IS this the version from the pandoc binary we provide, or
did you install it in some other way?

**Comment by mdekauwe** [comment]
I re-installed via the cabal example, e.g. 

cabal update
cabal install pandoc-citeproc
(which installed pandoc again)

I made sure I linked to this new version, but the issue hasn't gone away for me.
