### ISSUE TITLE
Images don't appear in groff ms output to pdf

### ISSUE THREAD

**Issue by RobertGoulding** [jgm/pandoc#8660]
When I process a markdown file with an image to pdf, using `groff -t ms -o text.pdf text.md`, instead of an image I just get a text in square brackets saying [IMAGE: (description)]. The identical document processed via LaTeX (using `groff -o text.pdf text.md`) includes the image.

I looked at the intermediate groff -ms file. That has the text [IMAGE: (description)] instead of `.PSPIC` requests.

Using pandoc 3.1, on crostini on a Chromebook.

In the attached files, the extension of the image filename has to be `.eps` for groff outout, `.png` for LaTeX.

[text_tex.pdf](https://github.com/jgm/pandoc/files/10855683/text_tex.pdf)
[text.md](https://github.com/jgm/pandoc/files/10855684/text.md)
[text_ms.pdf](https://github.com/jgm/pandoc/files/10855685/text_ms.pdf)

**Comment by jgm** [comment]
.PSPIC will be used if the image has extension .ps or .eps

**Comment by jgm** [comment]
You might try dropping the extension in your md file. Then generate an .eps and a .png version of each image, and use `--default-image-extensio=png` (or `eps`) depending on the format you're producing.

**Comment by dinesh-58** [comment]
Facing the same problem. The `--default-image-extension` flag doesn't work too. You can use `wkhtmltopdf` for now if you aren't using any groff syntax. 
```
pandoc md.md -o pdf.pdf --pdf-engine=wkhtmltopdf
```

**Comment by jgm** [comment]
What do you mean, the `--default-image-extension` doesn't work?
Are you creating an eps and png version of each image?

**Comment by jgm** [comment]
You should look at the intermediate tex file (use `--verbose` when creating pdf) to see what filename is being generated, and make sure the file can be found at that location (relative to the working directory, not relative to the file).

You can see that the option is working from a simple example:
```
$ pandoc --default-image-extension=eps -t latex
![image](images/foo)
\begin{figure}
\centering
\includegraphics{images/foo.eps}
\caption{image}
\end{figure}
```

**Comment by RobertGoulding** [comment]
The LaTeX output is
````
\begin{figure}
\centering
\includegraphics{images/6787-313-parabola-triangles.eps}
\caption{Diagram on {[}6787:313{]}}
\end{figure}
````
The ms output is:
````
[IMAGE: Diagram on [6787:313]]
````
That's with exactly the same command line, just changing `-t latex` to `-t ms`.

**Comment by jgm** [comment]
Ah. I see what is happening. With 3.1 we generate
```
[ Figure
    ( "" , [] , [] )
    (Caption Nothing [ Plain [ Str "moon" ] ])
    [ Plain
        [ Image
            ( "" , [] , [] ) [ Str "moon" ] ( "images/lalune.eps" , "" )
        ]
    ]
]
```
instead of a Para with an Image. The ms writer was never updated for this new expectation.

**Comment by jgm** [comment]
OK, I've merged a change that should fix this.

**Comment by RobertGoulding** [comment]
Thanks!

Robert Goulding
