### ISSUE TITLE
MathML is now supported by Chrome

### ISSUE THREAD

**Issue by daamien** [jgm/pandoc#8667]
The user guide says:

```
Note that currently only Firefox and Safari (and select e-book readers) natively support MathML.
```

it seems that Chrome has it too since january and Chrome 109:

https://www.igalia.com/2023/01/10/Igalia-Brings-MathML-Back-to-Chromium.html

Given that Firefox+Safari+Chrome represent 90% of the browsers marketshare, I suggest to remove the note above or to replace it by:

```
Note that MathML is supported natively by the main web browsers and select e-book readers.
```

I can submit a patch to either delete or modify this sentence.

**Comment by jgm** [comment]
I've done that, thanks.

One thought: should we now make mathml the default math mode for HTML output? (Instead of the current "faking it with unicode")
