### ISSUE TITLE
\newcommand and \xspace in Latex template adds a space before apostrophe (PDF output from Markdown)

### ISSUE THREAD

**Issue by mrego** [jgm/pandoc#8674]
**Explain the problem.**

Defining a new command using `\xspace` in a Latex template is adding an space before an apostrophe, it doesn't add it before a point, comma or exclamation mark for example.

This is the kind of command that causes issues:
```latex
\newcommand{\test}{Test\xspace}
```

The full details.
* `template.tex`:
```latex
\documentclass[a4paper]{article}
\usepackage{xspace}

\newcommand{\test}{Test\xspace}

\begin{document}

$body$

\end{document}
```
* `test.md`:
```
\test.

\test's foo.

\test bar.

\test, baz.

\test! wow.
```
* Command line:
```sh
pandoc --template=template.tex test.md -o test.pdf
```

Then in the `test.pdf` file that is created, you can see that the that it adds an extra space before the apostrophe:
![Screenshot of PDF rendered showing an extra space before the apostrophe](https://user-images.githubusercontent.com/11602/223421420-76c8a505-91a3-42d4-8a9a-24984d29d6f0.png)

If we inline the content of the `test.md` file into the `template.tex` and we convert from Latex to PDF the issue is gone (e.g. `pandoc template.tex -o test.pdf`).

**Pandoc version?**

* Version: pandoc 3.1.1
* OS: Debian 6.1.12-1

**Comment by jgm** [comment]
This looks like a tex issue rather than a pandoc issue.

When you convert directly to PDF, pandoc will use unicode characters for quotes and apostrophes, rather than ligatures (for reasons). So, your md is being converted to this tex:
```
\test’s foo.
```
Try running xelatex with this file:
```
\documentclass[a4paper]{article}
\usepackage{xspace}

\newcommand{\test}{Test\xspace}

\begin{document}

\test's foo.

\test’s foo.

\end{document}
```
and you'll see the extra space.  So, as far as I can see this is not really a pandoc issue. You can reproduce it with pure tex, and you should ask on a tex forum how it should be solved.

**Comment by jgm** [comment]
I assume the fundamental problem is that xspace does not support non-ascii characters.

**Comment by mrego** [comment]
Thank you very much for the quick reply. Feel free to close this as it seems the bug is in Latex directly. Sorry for the noise.

It seems than a potential workaround could be to avoid `\xspace` and do something like:
```latex
\newcommand{\test}{Test}
```

And then in Markdown do:
```md
\test{}'s foo.
```
