### ISSUE TITLE
Pandoc 3.1.1: Simple Jira Markup Wrongly Parsed as "Phantom Image" Reference (Mislead by Exklamation Mark in Input?)

### ISSUE THREAD

**Issue by gohrner** [jgm/pandoc#8680]
**Explain the problem.**

`pandoc -f jira -t markdown jira.txt`

with the following `jira.txt`:

```
*ACHTUNG:* Die autogenerierten Klassen dürfen NICHT durch Automatismen verändert werden! Sie sind vor Umformatierungen bereits geschützt durch den Kommentar {{// @formatter:off}} am Anfang jeder Datei. Diesen Kommentar muss die Formatter-Einstellung *zwingend* berücksichtigen!
```

produces the following output:

```markdown
**ACHTUNG:** Die autogenerierten Klassen dürfen NICHT durch Automatismen
verändert
werden![]( Sie sind vor Umformatierungen bereits geschützt durch den Kommentar {{// @formatter:off}} am Anfang jeder Datei. Diesen Kommentar muss die Formatter-Einstellung *zwingend* berücksichtigen)
```

In pandoc's "native" output, the wrong part looks as follows:

```javascript
    , Image
        ( "" , [] , [] )
        []
        ( " Sie sind vor Umformatierungen bereits gesch\252tzt durch den Kommentar {{// @formatter:off}} am Anfang jeder Datei. Diesen Kommentar muss die Formatter-Einstellung *zwingend* ber\252cksichtigen"
        , ""
        )
```

Note that Pandoc seems to have "invented" an "empty" image, where it took the rest of the line as the empty image's URL.
Also, the inline code / fixed-width section `// @formatter:off` was not parsed at all (which however may be a side effect of this part of the line being taken as an URL while it is none).

**Pandoc version?**
pandoc 3.1.1
Features: +server +lua
Scripting engine: Lua 5.4

Debian GNU/Linux

**Comment by tarleb** [comment]
The two exclamation marks do seem to be a problem for the parser. Unfortunately I no longer have access to any Jira system that still uses the old wiki syntax, so I can no longer reverse engineer the actual behaior. Could you try the following code and report the results of rendering with Jira?

```
a!foo.png!

b! foo.png!

c ! foo.png!

d!foo.png ! d

e!foo.png!e
```

**Comment by gohrner** [comment]
I tested it and pasted your test into the raw text editor.

None of it is rendered as a link:

![image](https://user-images.githubusercontent.com/26199042/224720781-46c34899-4063-4d86-953d-b2fa7d072141.png)

Also, a space following the exklamation mark causes Jira to not render it as a link, even if the actual file name starts with a space.

Here's my test content - don't be confused, I used above screenshot as an image attachment in Jira for this test, probably not the best idea I ever had...

![image](https://user-images.githubusercontent.com/26199042/224722016-ddffc5be-7c04-4b82-a9f2-994939bd47ba.png)

Here's the Jira source:

```
a!foo.png!

b! foo.png!

c ! foo.png!

d!foo.png ! d

e!foo.png!e

!screenshot-1.png!

 !screenshot-2.png|thumbnail! 

 !S c r e e n s h o t _20230313_144726.png|thumbnail! 

 ! S c r e e n s h o t _20230313_144726.png|thumbnail! 
```

**Comment by tarleb** [comment]
We now require the image URL to start with a non-space character. This seems sufficient to fix this, and the original text is now converted to

``` html
<p><strong>ACHTUNG:</strong> Die autogenerierten Klassen dürfen NICHT
durch Automatismen verändert werden! Sie sind vor Umformatierungen
bereits geschützt durch den Kommentar <code>// @formatter:off</code> am
Anfang jeder Datei. Diesen Kommentar muss die Formatter-Einstellung
<strong>zwingend</strong> berücksichtigen!</p>
```

**Comment by gohrner** [comment]
Sounds good - I will test as soon as a pandoc version with this fix is released.

**Comment by tarleb** [comment]
You can also [download a nightly build](https://github.com/tarleb/kb/blob/main/tips/100-download-a-nightly.md) tomorrow at noon (MEZ).

**Comment by tbussmann** [comment]
> Unfortunately I no longer have access to any Jira system that still uses the old wiki syntax, so I can no longer reverse engineer the actual parser.

just to let you know: the old wiki syntax is still available even on the Jira Cloud instances that usually use the new ADF Format via the (not yet deprecated) v2 API as documented [here](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-comments/#api-rest-api-2-issue-issueidorkey-comment-id-put). A simple commandline tool implementing that API and allowing to read/write comments in the wiki syntax is [jirae](https://github.com/codesoap/jirae)

**Comment by tarleb** [comment]
Thank you @tbussmann, that's very helpful to know.
