### ISSUE TITLE
PDF Reader

### ISSUE THREAD

**Issue by daviewales** [jgm/pandoc#8682]
**Describe your proposed improvement and the problem it solves.**

It would be nice to be able to convert PDF documents into a plain text form such as Markdown.
I'm aware this is a horrifyingly awful problem due to the way that PDF documents are structured.
But there are tools such as [pdfminer.six](https://pdfminersix.readthedocs.io/en/latest/topic/converting_pdf_to_text.html) and [Camelot](https://github.com/camelot-dev/camelot/) which have done some of this work already.

pdfminer.six can output a reasonable approximation of the PDF in HTML format.
It doesn't provide semantic structure (e.g. headings), but it does provide the font and font size for each extracted element.
This could be used with a heuristic to approximate heading structure. (Biggest font is h1, next biggest font is h2, etc.)

Camelot can extract tables.

Libre Office can also be used to convert from PDF.

    libreoffice --headless --convert-to docx *.pdf

**Describe alternatives you've considered.**

Using the above tools to convert to an intermediate format that pandoc understands, then piping to pandoc.

**Comment by jgm** [comment]
> pdfminer.six can output a reasonable approximation of the PDF in HTML format.

Perfect!  Then pipe its output through `pandoc -f html`.

I think this is out of scope for pandoc.  As you note, it's an awful problem, and yes, one can make progress on it, but it would add a lot of extra code and complexity to pandoc to build this in -- and to what end, if there's already a good external tool that does this?

**Comment by Enivex** [comment]
A naive question: Is this a simpler problem to solve if limited only to PDF/UA?

**Comment by jgm** [comment]
@Enivex I'm really not sure; perhaps tagging (if these variants require it) would allow structure to be extracted from a PDF more simply.  But I don't know the format well enough.
