### ISSUE TITLE
pandoc uses over 50 GB of RAM to convert a 6-page latex file to plain text

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [jgm/pandoc#8684]
Pandoc 3.1.1 on Windows 10 uses over 50 GB of RAM to convert a 6-page latex file to plain text. Also, it doesn't seem to terminate (I killed it after 30 minutes). Command used:

```
pandoc --to=plain --wrap=none eacl2017.tex > out.txt
```

Latex file: https://arxiv.org/e-print/1612.05251 (corresponding PDF: https://arxiv.org/pdf/1612.05251.pdf)

![image](https://user-images.githubusercontent.com/15331/224652140-7cc404e0-380f-411c-b40b-60264d20ab0c.png)

**Comment by jgm** [comment]
When I download that URL I get a binary file, not a LaTeX file.  That is probably the cause of the problem: pandoc is trying to parse a binary file as LaTeX.

**Comment by jgm** [comment]
Ah, I see that it's a gzipped tex file.

**Comment by jgm** [comment]
After unzipping, I get a tex file but it is quite unusual.
IT has content before the `\documentclass` command and pdflatex immediately raises an error when I try to process it.
Pandoc fails with this error:
```
Error at "8684.tex" (line 300, column 3):
unexpected #0
{ #0 'before.all :=
  ^
```
Can you directly upload your input eacl2017.tex?  I have a feeling this is not it.

**Comment by tarleb** [comment]
This appears stale, thus closing.
