### ISSUE TITLE
[markdown writer] figures output with `<figure>` tag instead of simple `implicit_fitures` format

### ISSUE THREAD

**Issue by VladimirAlexiev** [jgm/pandoc#8689]
**Explain the problem.**
I have org figures formatted like this:
```
cat test1.org
#+label: fig:bsdd-graphql-voyager-orig-detail
#+caption: Original bSDD GraphQL Schema: Detail of Classification and ClassificationProperty
[[./img/bsdd-graphql-voyager-Classification-ClassificationProperty.png]]
```
They are converted to markdown like that, using `<figure>` tags:
```
pandoc -t markdown+implicit_figures test1.org
<figure id="fig:bsdd-graphql-voyager-orig-detail">
<img
src="./img/bsdd-graphql-voyager-Classification-ClassificationProperty.png" />
<figcaption>Original bSDD GraphQL Schema: Detail of Classification and
ClassificationProperty</figcaption>
</figure>
```
But I'm asking for `+implicit_figures` so according to https://pandoc.org/MANUAL.html#extension-implicit_figures, shouldn't figures be emitted in a simpler way like this?
```
`![Original bSDD GraphQL Schema: Detail of Classification and
ClassificationProperty](./img/bsdd-graphql-voyager-Classification-ClassificationProperty.png)`
```

(This is a minor misfeature, or rather a question whether I can enforce the simpler output)

**Pandoc version?**
```
# pandoc -v
pandoc 3.1.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: C:\Users\Vladimir Alexiev\AppData\Roaming\pandoc
# uname
CYGWIN_NT-10.0
```

**Comment by jgm** [comment]
This looks like a bug; there is code that is intended to do this -- let me see if I can figure out the problem.

**Comment by jgm** [comment]
OK, the code has

```hs
  let combinedAlt alt = case capt of
        Caption Nothing [] -> if null alt
                              then Just [Str "image"]
                              else Just alt
        Caption Nothing [Plain captInlines]
          | captInlines == alt -> Just captInlines
        _ -> Nothing
```
and if this returns Nothing, it falls back to Figure.

Thus, if the caption of the Figure element doesn't match the image description of the enclosed Image, we fall back to using `<figure>` so that we don't lose information.

This is probably the wrong call; better in this case to stuff the image's description into an `alt` attribute and continue with implicit figures.

**Comment by jgm** [comment]
Alternatively the org reader could be taught to duplicate the caption in the image's description/alt text.


@tarleb do you have any thoughts on this?

**Comment by tarleb** [comment]
I agree and have relaxed the condition in the Markdown writer as suggested.

**Comment by VladimirAlexiev** [comment]
Both figure numbering solutions listed at https://pandoc.org/extras.html#numbering-and-cross-references require `+implicit-figures` :
- https://lierdakil.github.io/pandoc-crossref/#image-labels.
- https://github.com/tomduck/pandoc-fignos#markdown-syntax

@jgm @tarleb Wow, you guys are AMAZING!!!
When can we expect a release?

**Comment by tarleb** [comment]
There's no release schedule, but the change was just in time for the nightly build to pick it up. You can test the fix by downloading a version from here: https://github.com/jgm/pandoc/actions/runs/4413422589
