### ISSUE TITLE
Location of footnotes and references in slides (reveal.js)

### ISSUE THREAD

**Issue by kno10** [jgm/pandoc#8695]
Neither `--reference-location=block` nor `--reference-location=section` appear to have an effect with reveal.js output.
The references always appear at the end of the document, on a separate slide (that can also easily overflow).

In particular the footnotes are completely useless because of this; the hyperlinking does not appear to work with reveal.js.
The footnotes should go to the footer of the current slide, in my opinion!

But as I prefer the references on separate slides at the end of the document, I would also want to be able to control these two independently. Right now, the `--reference-location` parameter also controls the footnotes, at least according to the documentation (because it does not appear to work for me).

**Comment by jgm** [comment]
"References" here is about reference links, not citations, if that's what you're thinking of.

**Comment by jgm** [comment]
Currently we get this structure with `--reference-location=section`:
```html
<section class="slide level1">
slide
</section>
<section class="footnotes">
notes
</section>
```
I agree that instead we should have:
<section class="slide level1">
slide
<section class="footnotes">
notes
</section>
</section>
```

**Comment by jgm** [comment]
`--reference-location=block` does give you the footnotes in the slide, does it not?
It did when I tried.

**Comment by jgm** [comment]
Should maybe also put these in an `<aside>` for revealjs.

**Comment by kno10** [comment]
I didn't test footnotes specifically, but only the citations, as I assumed they are both supposed to behave the same here.
I did not realize this refers to reference-style links. I'll try again.

**Comment by kno10** [comment]
With footnotes instead of citations, it created a `section` as above.
But this `section` makes reveal.js put this on an extra slide.
So you have one slide with the text, and then another with the footnote only. Ouch.

I guess I will continue to write my footnotes as
```
text^1^

::: footer
^1^ note
:::
```

**Comment by jgm** [comment]
Yes, the fix I mentioned above would, if implemented, prevent the extra-slide problem for footnotes.

When you say "citations," do you mean the reference list (which we always put at the end), or individual citations? Are you using a footnote csl style?

**Comment by kno10** [comment]
Thank you!

For citations, I am using a reference list at the end, and that is also what I want to do, not footnotes.
But I sometimes have too many to fit on a single slide.

**Comment by jgm** [comment]
Perhaps you could open a separate issue for a way to automatically break up the citation list between slides.

Beamer can do this automatically, but I don't yet see any way to do it for revealjs.

**Comment by kno10** [comment]
That likely is an issue that would better be filed with reveal.js. But IMHO the solution will likely be to use CSS `overflow:scroll`. Oh, and linking to references did not work for me - but again, I believe this is up to reveal.js to handle, map anchor ids to show the proper slide client side.

**Comment by jgm** [comment]
If the anchors and links look right in the HTML, then it's probably a revealjs issue.

As for overflow:scroll, we could add that to the default template, I suppose?  Again, might be good for another issue.

**Comment by jmuheim** [comment]
For me, the back-linking of footnotes inside RevealJS works very well.

But the `--reference-location=section` doesn't seem to have an effect: footnotes still appear at the very end in a separate slide. I'm using Pandoc `3.6.3`. Any idea how to debug this?
