### ISSUE TITLE
Option to not use hyperref in LaTeX output

### ISSUE THREAD

**Issue by Martin1887** [jgm/pandoc#8698]
Some academic LaTeX templates forbid the use of the `hyperref` package (e.g. https://proceedings.aaai.org/info). It would be helpful an option to not use the `hyperref` package to get a correct output when using these templates.

The things to be changed I have found are:
- Load the package in the default template only if the option is not enabled.
- Remove `hypertarget` tags from headers.

Thanks and Regards.

**Comment by jgm** [comment]
You can remove the tags from the headers by ensuring that your headers don't have identifiers.

```
pandoc -f markdown-auto_identifiers -t latex
```

As for the template, you can always use a custom template...
Note that some other packages may load hyperref.

**Comment by Martin1887** [comment]
OK, I didn't know that hypertargets could be removed removing the identifiers of the headings. The issue can be closed then.


Thanks for the quick response!
