### ISSUE TITLE
Abstract has no title when converting markdown to docx

### ISSUE THREAD

**Issue by joezhouchenye** [jgm/pandoc#8702]
**Describe your proposed improvement and the problem it solves.**

Add a similarly option like `reference-section-title` to abstract section.

Here's the result that I would like to have.

![image](https://user-images.githubusercontent.com/59191277/225696506-8178b1b9-a4ce-4e06-8e8c-9e8c5609c6b5.png)

**Comment by jgm** [comment]
I made it use a localized term for "Abstract" (will depend on `lang`).  We could add the ability to override this using `abstract-title` if necessary, but maybe the localized term is enough?

**Comment by joezhouchenye** [comment]
What I mean is to add the "Abstract" title to the output `.docx` document.

Anyway, I use a VBA macro as a workaround:

```vba
Sub AbstractTitle()
    Dim i As Integer
    
    i = 0
    
    For Each para In ActiveDocument.Paragraphs
        i = i + 1
        If para.Style = "Abstract" Then
            ActiveDocument.Paragraphs.Add Range:=para.Range
            ActiveDocument.Paragraphs(i).Range.Text = "Abstract" & vbCr
            ActiveDocument.Paragraphs(i).Style = wdStyleHeading1
            Exit For
        End If
    Next
End Sub
```
From the Pandoc User's guide `abstract-title` is "title of abstract, currently used only in HTML and EPUB".

I have tried HTML output, but no abstract part is shown in the generated HTML file.

For latex, `abstract-title` doesn't work as well.

A workaround to use custom abstract title for latex is:

```yaml
header-includes:
  \renewcommand{\abstractname}{My Very Own Summary}
```

So far, I couldn't say this is a completed feature.

**Comment by jgm** [comment]
> What I mean is to add the "Abstract" title to the output .docx document.

Yes, and that's what it does now!

**Comment by jgm** [comment]
`abstract-title` could be implemented for docx and latex, if there's a reason to. (That is, if people really need the title of the abstract to be something different from "Abstract" as localized to their language.)  But this would be better made a separate issue.

**Comment by zero0n3** [comment]
Hello, could you add ad example in the documentation on how to use it? Because i'm trying but without success. Thanks

**Comment by joezhouchenye** [comment]
Have you updated pandoc to the latest version? It does add "Abstract" now, but the added "Abstract" has the same style as the abstract content which is not desired. I want the abstract to be bolded and center-aligned, so a macro in Word is still needed.

**Comment by zero0n3** [comment]
> 

yes I did the update and in fact now it adds Abstract to me at the beginning.
I usually use md to docx conversion.
In the files, at the top, I have this header (later used with the `yaml_metadata_block` extension)
```
---
lang: it-IT
abstract: "blah blah blah"
---
```
Meanwhile, the title "Abstract" is not translated according to the language and furthermore, even adding there, the variable
`abstract-title: 'some title'`
that value is not read and I still have the title "Abstract"
So where am I doing wrong?

**Comment by joezhouchenye** [comment]
> `abstract-title` could be implemented for docx and latex, if there's a reason to. (That is, if people really need the title of the abstract to be something different from "Abstract" as localized to their language.) But this would be better made a separate issue.

As mentioned above, `abstract-title` will have no effect in docx and cannot be translated automatically.

**Comment by zero0n3** [comment]
> > `abstract-title` could be implemented for docx and latex, if there's a reason to. (That is, if people really need the title of the abstract to be something different from "Abstract" as localized to their language.) But this would be better made a separate issue.
> 
> As mentioned above, `abstract-title` will have no effect in docx and cannot be translated automatically.

OK understood. Sorry, I misunderstood then and I thought it worked, at least the version translated into the language of the document, even on docx files
