### ISSUE TITLE
Support docbook `<part>`s

### ISSUE THREAD

**Issue by anarazel** [jgm/pandoc#8712]
Hi,

I tried to use docbook to translate postgres' documentation into other formats. That mostly works, but postgres' docs use `<part>`. There's two issues with that:
- links to parts end up named "part_title" (similarly, links to books end up as "book_title")
- the TOC hierarchy ends up flattened (parts and chapters in the same hierarchy), making the TOC way too long to be useful, because toc-depth doesn't work anymore.

The first is quite easy to fix. Adding a line for part and book to xrefTitleByElem) + tests. I didn't yet open that as a PR, because to test that I need to add a part to test/docbook-xref.docbook - and I am not sure you want to do that without actually supporting part?

The second issue looks harder to fix entirely - I guess chapters, sect$n's all need to shift their heading level by one if they are in a a part?

How incrementally can things like this be integrated? It seems to me, a good first step would be to wire up part, partintro, partinfo, without adjusting the heading levels? And then subsequently adjust those as well?

Regards,

Andres

**Comment by jgm** [comment]
OK, I've added support for part, but this needs testing.  Can you test using your existing file?
If it works properly we could add to the automated tests.

**Comment by anarazel** [comment]
That was fast - thanks!

>  Can you test using your existing file?
> If it works properly we could add to the automated tests.

Not as-is, it takes pandoc about a minute to process :). But I can extract the useful bits of structure...
