### ISSUE TITLE
monobackgroundcolor not affecting CodeBlock elements in html

### ISSUE THREAD

**Issue by awa5114** [jgm/pandoc#8719]
**Explain the problem.**

With test file `test.md`:

~~~
---
title: test
monobackgroundcolor: lightgrey
---

inline code `hello`
code block

```python
def f(x):
    return x
```
~~~

Run `pandoc -s --from markdown --to html test.md -o test.html`. The resulting html file only renders inline code with a background color. Code blocks remain transparent. 

**Pandoc version?**

pandoc 3.1

**Comment by tarleb** [comment]
Why do you think this should work? Best to use CSS for this.

**Comment by jgm** [comment]
Actually `monobackgroundcolor` does adjust the CSS for `code` in the default template.

I think that what is going on here is this:  your code blocks have a language specified, so pandoc is highlighting them using the highlighting style selected (or the default one). The style sets a background which will override what is set by `monobackgroundcolor`.  Of course you can change the style's background or just add some CSS after the inclusion of the highlighting style's CSS in the template.
