### ISSUE TITLE
mainfontoptions is ignored if a language variable is set

### ISSUE THREAD

**Issue by twebr** [jgm/pandoc#8721]
Since pandoc 3.0, the variable mainfontoptions is ignored if a language is set. 

Minimal working example: 

```md
---
lang: en
mainfont: Arno Pro
mainfontoptions:
- Numbers=OldStyle
---

Hello world 1234567890.
```

When running `pandoc "text.md" -o "text.pdf" --pdf-engine xelatex`, the numbers in the output are lining figures, not oldstyle figures as expected. **Crucially, removing `lang: en` from the metadata YAML block resolves the issue.**

The issue seems to be caused by [this commit](https://github.com/jgm/pandoc/commit/8a2418cc29fba8c4ee4c9dc232450ccbe494dea9), which causes the font to be set _twice_ in the intermediary tex format if a language is set: once with `\setmainfont` and once with `\babelfont`.

It seems to me that the issue could be resolved by passing the mainfontoptions to `\babelfont` as well, but I am not familiar enough with the codebase to submit a pull request myself.

I am using 3.1.1 to reproduce this issue, on macOS 12.6.3.

**Comment by jgm** [comment]
Thanks for reporting - I think this should fix it, but testing always welcome.
