### ISSUE TITLE
User data directory is displayed incorrectly for Windows

### ISSUE THREAD

**Issue by rkingett** [jgm/pandoc#8727]
everywhere, when using the `pandoc --version` command, and in the user manual, and all other help pages, the default user directory is typed like this.

User data directory: C:\Users\USERNAME\AppData\Roaming\pandoc

But this is incorrect, and has been incorrect for multiple versions now.

When installing Pandoc, either via WinGet or the EXE file provided on the page, the default install directory is actually this,

C:\Users\USERNAME\AppData\Local\Pandoc\.

Perhaps we could change the directory in the `pandoc --version` command and or change the installer to always install to the ROAMING appdata directory instead of the local one?

**Pandoc version?**

All versions after 3.

**Comment by jgm** [comment]
The user data directory isn't the directory to which the pandoc executable is installed.
Note also that the user data directory won't be created automatically; you need to create it if you want to use it.

**Comment by rkingett** [comment]
Okay. Now I understand better! I am sorry, the manual was not very clear to me. The users guide. Would it be possible to have the installer make this directory upon installation? It might ease onboarding for newer Pandoc users.

**Comment by jgm** [comment]
Well, our policy is not to create any files that the user didn't explicitly ask for.  However, it might be worth noting in the documentation that you may need to create the directory.

**Comment by rkingett** [comment]
Yes, mentioning it in the documentation would be the best thing to do, agreed!
