### ISSUE TITLE
Task lists styling doesn't work in reveal.js

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#8731]
Tasks lists like the below are rendered in a way that requires extra styling in HTML. The styles that pandoc adds are overridden by the reveal.js style, leading to an unpleasant look of task lists when placed on reveal.js slides.

``` markdown
$ pandoc -o tasklist.html -s -t revealjs
- [ ] this
- [ ] that
^D
```

See quarto-dev/quarto-cli#2834 for more details.

**Comment by jgm** [comment]
Would it work to put reveal styling before pandoc styling in the template?

**Comment by tarleb** [comment]
I forgot most of what I knew about CSS rule precedence, but I seem to remember that rules with a class always take precedent of those without a class, so it won't work, probably.
