### ISSUE TITLE
Alt text lost in LaTex to HTML conversion

### ISSUE THREAD

**Issue by wrightas** [jgm/pandoc#8743]
Hello, 
Thanks for all your work. I'm a user, not a developer and this is my first issue in GH.

## The problem

I want to create accessible versions of LaTeX documents using pandoc 3.1.1 (MacOS Ventura 13.2.1) to convert to HTML. My issue is similar to [issue #6095](https://github.com/jgm/pandoc/issues/6095), which concerns PDFs and uses now-depreciated packages. My example uses only LaTeX graphicx and concerns HTML output. Graphicx allows an "alt={Alt Text}" key value, however it is not translated into HTML by Pandoc. [Graphicx documentation](https://tug.ctan.org/macros/latex/required/graphics/graphicx.pdf) defines it as `\define@key{Gin}{alt}{}`.

Converting with [Tex4ht](https://github.com/michal-h21/make4ht) does add the alt text correctly (but is otherwise messy...).

## Latex source
```
\documentclass[12pt]{article}
\usepackage{pgfkeys}
\usepackage{graphicx}	
\begin{document}
Sample text
\begin{figure}[ht]
\begin{center}
\includegraphics[alt={Upside down painting},width=0.5\textwidth]{New_York_City_I.jpg}
\caption{New York City by Piet Mondrian (Wikipedia)}
\label{fig:Mondrian}
\end{center}
\end{figure}
\end{document}
```

## Command line:
`pandoc -s -t html5 AltTextTest.tex -o AltTextTestPandoc.html`

## Pandoc `<figure>` output
```
<figure id="fig:Mondrian">
   <div class="center">
   <img src="New_York_City_I.jpg" style="width:50.0%" />
   </div>
  <figcaption>New York City by Piet Mondrian (Wikipedia)</figcaption>
  </figure>
```

## Expected output

Using Tex4ht, `make4ht AltTextTest.tex`, gives the image tag `<img alt='Upside down painting' height='195' src='New_York_City_I.jpg' width='195' />`

I don't know enough about the underlying programs to identify the source of the difference between Pandoc and Tex4ht output. 

Including the built-in graphicx `\includegraphics\[alt={alt text}]{}` functionality would make it smoother and easier to create more accessible documents with Pandoc. Because this is standard functionality of a basic LaTeX package, I thought this was a "bug" rather than a "new feature" request, let me know if I'm off.
Thanks.

**Comment by michal-h21** [comment]
You can fix the image dimensions in TeX4ht conversion using one of tips in the [how-to section](https://www.kodymirus.cz/tex4ht-doc/Howto.html#change-image-size-and-resolution) of documentation. In general, it needs a special metadata file with dimensions for each image. You can produce it using the `ebb` command:

     $ ebb -x *.jpg

with this change, you should get correct height for your image. You can also use relative dimensions, as shown in the how-to.

**Comment by wrightas** [comment]
Thanks for taking this up so quickly @tarleb and for your helpful suggestion @michal-h21

**Comment by tarleb** [comment]
The reason that I haven't merged my patch yet is that my naïve implementation gets the conversion wrong when the alt text contains markup: `htlatex` converts converts `alt={\emph{important}}` to the HTML attribute `alt="important"`, but the proposed implementation keeps the markup as `alt="\emph{important}"`.  This is probably acceptable since alt should never contain markup, and there is no 100% clear definition of what *must* happen, but it strikes me as problematic. Cc @jgm.

**Comment by jgm** [comment]
It makes sense to me to stringify it so it doesn't have formatting (as htlatex seems to do).

**Comment by tarleb** [comment]
I think I'll need help with that: not sure how best to parse an attribute as markup.
