### ISSUE TITLE
Add support for `PDF` on `https://pandoc.org/try/`

### ISSUE THREAD

**Issue by eyJhb** [jgm/pandoc#8747]
**Describe your proposed improvement and the problem it solves.**
Adding output format `PDF` to https://pandoc.org/try/ would be really helpful :)

**Describe alternatives you've considered.**
Getting pandoc installed on Windows, but that seems less fun.

**Comment by alerque** [comment]
This is not a good idea from the standpoint of the website itself. PDF generation is not done by `pandoc` itself, it relies on calling 3rd party tools. There are several available backends, but no matter which one you use the website would need to be able to execute the tooling on the webserver. For most backends this, especially the default LaTeX one, this would been allowing arbitrary code execution. A document could be crafted that would trigger `laTeX` etc. to run arbitrary commands. Even in a sandbox environment that is a terrible idea as it opens the server up to all sorts of malicious use cases.

If you want an easy bundled way to get this use the Pandoc Docker images that have LaTeX bundled for PDF generation. There are also various package managers for Windows that have Pandoc available to ease the installation process. Pick one of those.

**Comment by alerque** [comment]
No, even without the extra garantees provioes by PandocPure, even. on the CLI locally converting LaTeX to HTML relies on in internal syntax interpreter and does not do so by running `latex` itself which is where arbitrary code could be executed.
