### ISSUE TITLE
Reveal JS Example appears broken

### ISSUE THREAD

**Issue by laughingbiscuit** [jgm/pandoc#8749]
**Explain the problem.**

Navigate to <https://pandoc.org/demo/example16d.html> ( the revealjs result of number 16 in <https://pandoc.org/demos.html> ) . The slides are not rendered correctly. The same problem persists when generated locally.

The issue looks similar to <https://github.com/jgm/pandoc/issues/6408> from a few years ago.

To replicate:
```
./pandoc/bin/pandoc -t revealjs -s -o index.html slides.md
```

Source markdown:
```
$ cat slides.md
% Eating Habits
% John Doe
% March 22, 2005

# In the morning

- Eat eggs
- Drink coffee

# In the evening

- Eat spaghetti
- Drink wine

# Conclusion

- And the answer is...
```
please note, i have removed the maths line, for simplicity

**Pandoc version?**

Latest GH binary

```
$ ./pandoc/bin/pandoc -v
pandoc 3.1.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by laughingbiscuit** [comment]
Looks like the css sources cannot be reached e.g. <https://unpkg.com/reveal.js@%5E4//dist/theme/black.css>

**Comment by laughingbiscuit** [comment]
not sure if this is a temporary outage on unpkg or if srcs should be switched to another cdn e.g. <https://cdnjs.com/libraries/reveal.js/4.4.0>

**Comment by laughingbiscuit** [comment]
Successful workaround using jsdelivr CDN: 
```
./pandoc/bin/pandoc -t revealjs -s -o index.html slides.md -V revealjs-url=https://cdn.jsdelivr.net/npm/reveal.js@4.4.0
```

**Comment by jgm** [comment]
looks like it was a temporary outage.

**Comment by markpatterson27** [comment]
The problem is there is a double `//` in the middle of the css and js URLs, when there should only be a single `/`. This is because the revealjs-url parameter ends in a `/` slash, but a `/` slash is also included in the `default.revealjs` template after the url parameter for each of the css and js sources.

I think the CDN sometimes ignores the double `//` and sometimes doesn't, which is why the slides sometimes work. It's not a CDN outage. The URL is wrong.

**Comment by jgm** [comment]
Interesting, I'd been under the equivalent that a `//` in a URL was harmless and acted like a `/`, but apparently that is not always the case.  We could fix this either by changing the default value for $revealjs-url$ (removing the trailing slash) or by removing the slash in the template.  The first choice seems much less likely to break things, do you agree?

**Comment by jgm** [comment]
Fixed this on the server too.

**Comment by markpatterson27** [comment]
> We could fix this either by changing the default value for revealjs − u r l  (removing the trailing slash)

`MANUAL.txt` will need to be updated as well as `HTML.hs`.

[`revealjs-url`](https://github.com/jgm/pandoc/blob/0f71b9e8c473c0edb1c0c7523e8ba2da890e8aa9/MANUAL.txt#L2867-L2869)

```
`revealjs-url`
:   base URL for reveal.js documents (defaults to
    `https://unpkg.com/reveal.js@^4/`)
```

I've been trying it out with the latest release, `reveal.js@^5.2.0`. I haven't noticed any problems (though I haven't done anything beyond checking my slides still render).

**Comment by jgm** [comment]
I'll fix the manual.
