### ISSUE TITLE
Incorrect invocation of typst compiler while converting to pdf

### ISSUE THREAD

**Issue by MichaelFraiman** [jgm/pandoc#8754]
Due to recent [changes](https://github.com/typst/typst/releases/tag/v0.1.0) in `typst`, the new syntax for the command to compile a document is `typst compile file.typ`, not `typst file.typ`.

Running `pandoc -s a.md --pdf-engine typst -o a.pdf` produces this error:

```
error: unrecognized subcommand './toPdfViaTempFile61034-0.html'

Usage: typst [OPTIONS] <COMMAND>
```

The file `a.md` is just

```
# Title

text

```

However, running

```
pandoc -s a.md -o a.typ
typst compile a.typ
```

works.

I am using Pandoc 3.1.2 on MacOS.

**Comment by jgm** [comment]
OK, I'll change that.

**Comment by mokeyish** [comment]
@jgm Hi, I use typst as pdf engine, but it doesn't seem to work, below is my conversion command.

Can't it be used like this?


```shell
pandoc -o test.pdf --pdf-engine=typst -t pdf .\test.md
```

test.md
```markdown
# Title

## Para one

123

## Para two
456
```
