### ISSUE TITLE
Typst writer references `#blockquote` without defining it.

### ISSUE THREAD

**Issue by archfrog** [jgm/pandoc#8756]
I tested out converting a large Word document to the newly supported Typst format.  Everything went well, as far as I have seen, except the Typst writer does not define `#blockquote`, which is uses in the generated Typst source code.

I first converted my document, which contains a numbered list of items, which causes `#blockquote` to appear, using this command:

```
pandoc foo.docx -o foo.typ
```

I then tried compiling the generated `foo.typ` using the most recent v0.1 of Typst:

```
typst compile foo.typ
```

This yielded this error message:

```
error: unknown variable
     ┌─ test.typ:3103:4
     │
3103 │ +  #blockquote[
     │     ^^^^^^^^^^
```

I temporarily solved it by adding this `let` statement at the top of the generated file:

```
#let blockquote = block
```

I'm using Pandoc v3.1.2 for Windows x64 and Typst v0.1 Windows x64.  I have attached a very small Word document that recreates the problem.

[NumberedList.docx](https://github.com/jgm/pandoc/files/11165862/NumberedList.docx)

**Comment by jgm** [comment]
Use `-s` to get a standalone document using the default template. This will define `blockquote`.
