### ISSUE TITLE
Markdown to RTF conversion incorrectly adds an EOF newline

### ISSUE THREAD

**Issue by revolter** [jgm/pandoc#8761]
**Explain the problem.**

Running

```sh
echo "_test_" | pandoc --standalone --from='markdown-smart' --to='rtf' | pbcopy
```

and pasting it in an editor that supports RTF (e.g. TextEdit, Mail), shows up like this:

```plaintext
test

```

instead of

```plaintext
test
```

**Pandoc version?**

```
pandoc 3.1.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/revolt/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

```
macOS Ventura 13.2 (22D49)
```

**Comment by jgm** [comment]
The RTF generated is
```
{\pard \ql \f0 \sa180 \li0 \fi0 {\i test}\par}
```
This specifies a paragraph with 180 twips of vertical space after it (which is what gives us space between paragraphs). So I don't consider this a bug.

**Comment by revolter** [comment]
```
_test_
```

is a line of Markdown text, so you'd also expect a line of RTF text.

```
_test_

```

are two lines of Markdown text, so you'd expect two lines of RTF text.

---

If I save the generated code to an `.rtf` file, and open it in TextEdit, it shows up as having two lines of text, not one line with some space after it:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/5748627/230552580-a035b134-516f-47dd-a48e-97613128899b.png">

If I manually delete it and save the file, it changes it to this:

```rtf
{\rtf1\ansi\ansicpg1252\cocoartf2708
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica-Oblique;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\vieww5380\viewh2380\viewkind0
\deftab720
\pard\pardeftab720\sa180\partightenfactor0

\f0\i\fs24 \cf0 test}
```

With these said, I still consider it a bug, and it looks like it is possible to fix it 🤔

**Comment by revolter** [comment]
Hmm, using it without `--standalone` causes
```rtf
{\pard \ql \f0 \sa0 \li0 \fi0 {\i test}\par}

```
to be directly pasted in the Mail app, instead of the italic RTF text "test". Notice the newline added at the end.

And, with `--standalone`, it's the same behaviour as not using the filter 🤔

**Comment by tarleb** [comment]
This is a good use-case for a [custom writer](https://pandoc.org/custom-writers). Use the below to remove the final paragraph terminator if the input is just a single paragraph.

``` lua
Template = pandoc.template.default 'rtf'
function Writer(doc, opts)
  local rtf = pandoc.write(doc, 'rtf', opts)
  return (#doc.blocks == 1 and doc.blocks[1].t == 'Para')
    and rtf:gsub('%\\par%f[^%w]', '')
    or rtf
end
```

I don't think the current behavior is a bug, nor does it require changes in the RTF writer. Thus closing.

**Comment by revolter** [comment]
I see... I don't know much about RTL and how it works 🤔

With this said, thank you both for taking the time to reply to me!

After testing that writer a bit, I noticed that, for 2 lines of text, it still added a newline, so I changed it to:

```lua
Template = pandoc.template.default 'rtf'

function Writer(doc, opts)
  local rtf = pandoc.write(doc, 'rtf', opts)

  return rtf:gsub('\\par(}\n})', '%1')
end
```

and it worked perfectly ❤️
