### ISSUE TITLE
Typst pdf-engine has extra parameter 'compile'

### ISSUE THREAD

**Issue by benjamineskola** [jgm/pandoc#8766]
**Explain the problem.**

When using Pandoc to generate a PDF via Typst, I get the error:

```
$ pandoc --pdf-engine -o test.pdf test.md
error: unexpected argument.
Error producing PDF.

for more information, try --help
```

On further investigation, this appears down to the parameters typst is being called with: pandoc's verbose output says

```
typst "compile" "./toPdfViaTempFile81228-0.html" "./toPdfViaTempFile81228-1.pdf"
```

But `typst --help` makes no mention of a `compile` subcommand.

Testing:

```
$ pandoc -o test.typ test.md

$ typst compile test.typ test.pdf
error: unexpected argument.

for more information, try --help

$ typst test.typ test.pdf

$
```
The latter succeeds without output.

Testing further, I created a wrapper script, named `typst` that removes the first argument and calls the real typst. Pandoc then worked and created correct PDF output via Typst.

Typst version is 23-03-28

**Pandoc version?**

Current HEAD (later than e89a3ed).

**Comment by mheinzel** [comment]
This has been changed in Typst recently, see #8754. So I think updating Typst should solve the problem.

Would have been nice if Typst had supported both variants for a while. Not sure, but I guess working around this issue on Pandoc's end is too much of a hassle?

**Comment by jgm** [comment]
Correct.  I'm not going to try to make it work with both versions.  Upgrade typst and you should be fine.
