### ISSUE TITLE
Unable to run pandoc

### ISSUE THREAD

**Issue by awelormro** [jgm/pandoc#8778]
**Explain the problem.**
I've installed pandoc in arch linux using pacman and installing pandoc-cli using the command `sudo pacman -S pandoc-cli`, the installation went succesful and without errors, but when I try to run pandoc to conver any file or just to test it, it shows the following error:

```
pandoc: error while loading shared libraries: libHShslua-classes-2.3.0-JeVSVZbMagbuc0D8DLXfK-ghc9.0.2.so: cannot open shared object file: No such file or directory
```

**Pandoc version?**
pandoc-cli-0.1-50-x86_64

**Comment by jgm** [comment]
This isn't a problem with pandoc; it's a problem with the packaging, so you should report it to whoever maintains this package for arch.

Apparently they are compiling with dynamic libraries (something we don't do with our own releases), and you are missing one of the libraries needed.  That's a packaging issue.

Alternatively you can grab a binary from our releases page, and bypass arch's packaging.

**Comment by tarleb** [comment]
There's also the `pandoc-bin` package on AUR, which avoids the large number of Haskell dependencies that the official package tries to pull in.

**Comment by awelormro** [comment]
Thanks for the advice of pandoc-bin, it works nice :)

**Comment by aditya-an1l** [comment]
`pandoc-bin` seems to be broken again. If anyone is facing trouble installing the pandoc-bin, try installing the `pandoc` package from using _yay_:

```bash
yay -Sy pandoc
```
