### ISSUE TITLE
Segfaults, "bus error: 10" and "killed: 9" on Apple Silicon

### ISSUE THREAD

**Issue by anthonynelzin** [jgm/pandoc#8779]
After upgrading to the latest release of Pandoc, I can’t compile my biggest book anymore. Any attempt fails, sometimes after a few seconds, sometimes after a few minutes, sometimes with a `bus error: 10`, sometimes with a `killed: 9` error, more rarely after a segfault. Absolutely nothing was changed in the contents of the book and the issued command:

```pandoc --output=_livre.epub COLOPHON.md AUTHOR.md README.md ${LIVRE[@]} CONTACT.md```

With `${LIVRE[@]}` being defined as `cat toc.md`. This book is rather large (close to 500 chapters and 1 000 images), but compiled just fine with previous versions of Pandoc. I can compile other books, and even this book excerpt (first few chapters), with the same setup.

For reference, here’s an excerpt of a console output after such an error:

```
Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [10877]

VM Region Info: 0x16b480000 is in 0x16b480000-0x16b484000;  bytes after start: 0  bytes before end: 16383
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                       16b3f8000-16b480000    [  544K] rw-/rwx SM=PRV  thread 4
--->  STACK GUARD                 16b480000-16b484000    [   16K] ---/rwx SM=NUL  ... for thread 5
      Stack                       16b484000-16b50c000    [  544K] rw-/rwx SM=PRV  thread 5
```

**Pandoc version?**

Pandoc 3.1.2 on macOS Ventura 13.3 and 13.3.1 on Apple Silicon (M1 and M2) with Lua 5.4.

**Comment by anthonynelzin** [comment]
FYI, I got the same result using Pandoc 3.1.1 and 3.1.2 on macOS Ventura on an M1 Ultra system.

**Comment by jgm** [comment]
@anthonynelzin 3.1.2 is the first version where we've provided Apple silicon packages.  So, if you were using pandoc before on Apple silicon, you either compiled it yourself, or installed using something like brew or nix, or you were using the intel package via Rosetta. Which was it?

@bgamari We're building these packages on cirrus.  (macos-monterey-base:latest)  We install ghc via  `brew install ghc`, which installs ghc 9.4.4.

**Comment by anthonynelzin** [comment]
@jgm I always install Pandoc using Homebrew.

**Comment by jgm** [comment]
Can you try with the binary package we produce
https://github.com/jgm/pandoc/releases
use either the arm64-macos zip or the pkg, and make sure your path is set so that this version is used and not the homebrew one.
It would be helpful to know if you see the same behavior.

**Comment by bgamari** [comment]
I strongly suspect that this may be due to [#22497](https://gitlab.haskell.org/ghc/ghc/-/issues/22497). This will be fixed in 9.4.5 which should be out shortly.

**Comment by tarleb** [comment]
Closing, as this appears to be an upstream issue that has been fixed.

**Comment by able8** [comment]
yeah, it worked on the first try using the arm64-macos 3.1.2 release. (Thanks!)
This fixes the following  "bus error  pandoc" error

```
[1]    8693 bus error  pandoc ...
```
