### ISSUE TITLE
PANDOC_SCRIPT_FILE for custom writer is the supplied --to value (not the actual path)

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#8781]
It appears that `PANDOC_SCRIPT_FILE` for custom writers (and presumably readers) is the supplied `--to` value (not the actual path). It would be nice if it were the actual path (the file might have been found in `data-dir/custom`) so it can be used for finding other files via relative paths.

```
% pandoc --version
pandoc 3.1.2
```
```
% cat data-dir/custom/writer.lua
io.stderr:write('PANDOC_SCRIPT_FILE ' .. PANDOC_SCRIPT_FILE .. '\n')
```
```
% pandoc --data-dir=data-dir empty.md --to writer.lua
PANDOC_SCRIPT_FILE writer.lua
writer.lua does not contain a custom writer
```

**Comment by tarleb** [comment]
Thanks, that was a typo in the code.
