### ISSUE TITLE
Invalid YAML value in `cs.yaml`

### ISSUE THREAD

**Issue by dragonstyle** [jgm/pandoc#8787]
**Explain the problem.**
The following results in a warning due to what I believe is an invalid YAML value in the translation file:

```
pandoc --from markdown --to html --metadata lang=cs <<< '## Hello'
```

**Output**
```
<h2 id="hello">Hello</h2>
[WARNING] Could not load translations for cs
  translations/cs.yaml: YAML parse exception at line 3, column 13:
  mapping values are not allowed in this context
[WARNING] The term Abstract has no translation defined
```

I believe the issue is caused by an invalid value in line 4 of the [translation file](https://github.com/jgm/pandoc/blob/main/data/translations/cs.yaml)

**Pandoc version?**
macOS 
pandoc 3.1.1

**Comment by ilovedata** [comment]
I have very similar problem with Korean.

```
Could not load translations for ko
  translations/ko.yaml: YAML parse exception at line 16, column 6:
```
I have looked at ko.yml file and find the last line is the below.

To: 수신:

The colon after 수신 may cause a warning...

**Comment by jgm** [comment]
Thanks, I removed the colon in the ko.yaml.
