### ISSUE TITLE
Highlighting (`mark` filter) does not work with beamer

### ISSUE THREAD

**Issue by mh4ckt3mh4ckt1c4s** [jgm/pandoc#8803]
**Explain the problem.**

When using the `mark` extension, output is correctly highlighted in pdf output (using LaTeX), but not when using beamer. This problem is also present without using the extension, when using the `mark` class described [here](https://pandoc.org/MANUAL.html#highlighting).

Content of the `test.md` file : 

```md
# Please highlight my test

This following text is highlighted : ==wow so shiny==

[Mark]{.mark}
```

Command and output using LaTeX : 

```bash
pandoc -i test.md -o test.pdf -f markdown+mark -t latex
```

Output : 

![image](https://user-images.githubusercontent.com/76600167/234225938-d2970fee-d27a-4dc4-a118-e09f4f882f7e.png)

Command and output using beamer : 

```bash
pandoc -i test.md -o test.pdf -f markdown+mark -t beamer
```

![image](https://user-images.githubusercontent.com/76600167/234226303-425236ad-1d59-49ec-8759-ae0f51bbb27f.png)

A potential solution for this could be here : https://tex.stackexchange.com/questions/41683/why-is-it-that-coloring-in-soul-in-beamer-is-not-visible 

**Pandoc version?**

Pandoc 3.0.1 on Archlinux

**Comment by jgm** [comment]
That looks like the right sort of solution. Do you want to propose a specific revision to the default template?

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Yep, I can do that.
