### ISSUE TITLE
JATS Reader: Odd behavior with list and block quotes when nested inside a paragraph

### ISSUE THREAD

**Issue by coryschires** [jgm/pandoc#8804]
## Background
This is a doozy and probably something y'all have encountered in the past – tho I could not find an issue so here we go...

In JATS, both `<list>` and `<disp-quote>` elements may be contained inside a `<p>`. In the context of a research article (and perhaps more broadly) this makes perfect sense: It's not uncommon / wrong for an article to include a block quote or list inside a paragraph (as distinct from _in between_ two paragraphs).

But HTML, for example, doesn't allow this (see https://stackoverflow.com/questions/70604379). Furthermore, Markdown doesn't have, afaik, any official (or even conventional) syntax for expressing this use case. In other words, HTML and MD have the same bias / limitation.

## Problem
This esoteric nonsense starts to matter when attempting to convert JATS to Markdown. Consider the following examples.

### Case 1: Block quotes
**Given** the following JATS:
```xml
<p>
  Case 1: Start of a paragraph
  <disp-quote>
    <p>My block quote</p>
  </disp-quote>
  End of a paragraph
</p>
```
**When** I run `pandoc -f jats -t markdown`
**Then** Pandoc produces the following Markdown
```markdown
Case 2: Start of a paragraph " My block quote " End of a paragraph
```

I can see Pandoc added some `"` marks, which suggests it's doing its best given the circumstances.

But, imho, it would better if Pandoc block-element-ified the nested block quote by instead producing the following Markdown:

```markdown
Case 2: Start of a paragraph

> My block quote

End of a paragraph
```

### Case 1: Lists
Likewise, I see similar behavior when dealing with a `<list>` nested inside `<p>`.

**Given** the following JATS:
```xml
<p>
  Case 2: Start of a paragraph
  <list list-type="bullet">
    <list-item>
      <label>&#8226;</label>
      <p>Red</p>
    </list-item>
    <list-item>
      <label>&#8226;</label>
      <p>Blue</p>
    </list-item>
  </list>
</p>
```
**When** I run `pandoc -f jats -t markdown`
**Then** Pandoc produces the following Markdown
```markdown
Case 2: Start of a paragraph • Red • Blue
```

And, again, I think it would be better if Pandoc instead produced:

```markdown
Example A: Start of a paragraph

-   Red
-   Blue
```

### Pandoc Version
```
pandoc 3.1
Features: +server +lua
Scripting engine: Lua 5.4
```

#### nested-block-quote.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article PUBLIC "-//NLM//DTD Journal Publishing DTD v3.0 20080202//EN" "journalpublishing3.dtd">
<article article-type="research-article" dtd-version="3.0" xml:lang="en" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">
  <body>
    <sec>
      <title>Nested Block Quote</title>
      <p>
        Case 1: Start of a paragraph
        <disp-quote>
          <p>My block quote</p>
        </disp-quote>
        End of a paragraph
      </p>
    </sec>
  </body>
</article>
```

#### nested-list.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article PUBLIC "-//NLM//DTD Journal Publishing DTD v3.0 20080202//EN" "journalpublishing3.dtd">
<article article-type="research-article" dtd-version="3.0" xml:lang="en" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">
  <body>
    <sec>
      <title>Nested list</title>
      <p>
        Case 2: Start of a paragraph
        <list list-type="bullet">
          <list-item>
            <label>&#8226;</label>
            <p>Red</p>
          </list-item>
          <list-item>
            <label>&#8226;</label>
            <p>Blue</p>
          </list-item>
        </list>
      </p>
    </sec>
  </body>
</article>
```

### Commands to reproduce
```bash
pandoc nested-block-quote.xml -f jats -t markdown -o nested-block-quote.md
pandoc nested-list.xml -f jats -t markdown -o nested-list.md
```

As always, thanks for your time and insight! Pandoc is such a great tool. :pray:

**Comment by kamoe** [comment]
I think the rootcause here is that Pandoc seems to assume JATS paragraphs `<p>` can only contain line elements (as opposed to block elements). I say this from observing the `isBlockElement` function, where in line elements are pretty much the same list of elements allowed inside a paragraph (as defined [in the JATS spec here](https://jats.nlm.nih.gov/archiving/tag-library/1.3/element/p.html)):

https://github.com/jgm/pandoc/blob/16f28ef5e945f3be14e05afb7d91f8adca18e49a/src/Text/Pandoc/Readers/JATS.hs#L117-L131

The question is, can paragraphs contain block elements in AST? (I do not know the answer, I'm asking openly as that is also of interest to me). If the answer is no, then not sure there is much to do here. But if AST supports p to include block content, then I suppose, there could be an exploration to change the lines above.

**Comment by kamoe** [comment]
Actually, @coryschires I just flagged this as a more general issue in https://github.com/jgm/pandoc/issues/8889.

**Comment by kamoe** [comment]
Closed as per solution to https://github.com/jgm/pandoc/issues/8889.
