### ISSUE TITLE
Spurious errors working with pandoc defaults file due to LSP

### ISSUE THREAD

**Issue by chrisgrieser** [jgm/pandoc#8809]
When using the yaml-lsp and working on a defaults file, you get a lot of spurious errors from the LSP:
![image](https://user-images.githubusercontent.com/73286100/234591662-f1533484-3b2b-4898-ba93-7bffd2fa7c5d.png)

these diagnostics are all completely false, since the defaults file is working fine. 

I did some digging and figured out that those are caused by an unfortunate chain of dependencies:
- the yaml-lsp generates diagnostics for yaml files based on the on schemas. 
- These schemas are sourced from the [schemastore](https://www.schemastore.org/). The schema store in turn sources (some) of their schemas from external providers.
- one such provider is ansible. In particular, the [ansible-lint repo](https://github.com/ansible/ansible-lint/issues/3341) hosts a schema for [ansible vars file](https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/schemas/vars.json). One of the patterns used to identify a file as ansible vars file is `"defaults/*.yml"`
- this pattern results in the yaml-lsp recognizing any yaml file located in a `defaults` subdirectory as an ansible file and applies its patterns there.

Now coincidentally, "defaults" is also exactly the name of the directory in your pandoc `--data-dir`, where your defaults files have to be stored when you do not keep them in your working directory:
> All options for document conversion, including input and output files, can be set using a defaults file. The file will be searched for first in the working directory, and then in the defaults subdirectory of the user data directory ([pandoc docs](https://pandoc.org/MANUAL.html#option--data-dir))

The result are spurious errors by the LSP, even if you do not work with ansible files at all. Annoyingly you also cannot work around as end user, since the yaml LSP does only allow to *change* schemas for a file, but does not allow you to *disable* schemas for a file: https://github.com/redhat-developer/yaml-language-server/issues/446

---

Since the problem lies somewhere in between yaml-ls, schemastore, ansible, and pandoc, I created corresponding issues as well, with no luck (for now):
- the ansible folks state that they use the file only for their test-suite. (which for whatever reason ended up being fed to the yaml-ls apparently?) They state that you (pandoc) should use a more specific naming convention/pattern for pandoc default files: https://github.com/ansible/ansible-lint/issues/3341
- the issue I created at the schemastore repo has resulted in any response yet: https://github.com/SchemaStore/schemastore/issues/2919
- at the yaml-ls repo, the bug report form strongly emphasizes that issues with schemas should not be reported there but rather at the schema provider

Note that while this problem is created by a convergence of decisions from multiple projects, the end result – the spurious errors – are not an edge case, they apparently appear for *all* pandoc user working with yaml defaults files and using the yaml-lsp.

---

**possible solutions I can think of**
- hope that the schema store might change something on their end
- creation of a schema for pandoc defaults files that can either be used manually or submitted to the schemastore
- changing the naming pattern/convention for pandoc default's files as the ansible people suggested

**Comment by jgm** [comment]
I don't see that this is a pandoc issue.  Not fair for these other things to associate the very generic `defaults/*.yml` specifically with ansible.  (Have you tried using a `.yaml` extension instead?)

If this really bothers you, you could work around it by creating another subdirectory with a different name, `mydefaults` say, and symlinking `defaults` to it.

**Comment by chrisgrieser** [comment]
> If this really bothers you, you could work around it by creating another subdirectory with a different name,`mydefaults` say, and symlinking defaults to it.

That's actually a good idea for a workaround, thanks! 

Nonetheless, I do think that the issue should be fixed by one of the involved repos, since it's making it hard to work with default files for everyone. (I am actually surprised that nobody reported this problem before me yet)

---

> I don't see that this is a pandoc issue. Not fair for these other things to associate the very generic `defaults/*.yml` specifically with ansible.

I fully agree. I also tried to explain that to the ansible people, but well, [they just said that pandoc should change its naming conventions](https://github.com/ansible/ansible-lint/issues/3341#issuecomment-1523397167). I fear that the nature of this problem being distributed among so many parties might result in a diffusion of responsibility, with nobody doing anything... 😕

Maybe the ansible folks or the schemastore folks are more willing to listen if a pandoc maintainer reports this issue rather than a random user like me?
- https://github.com/SchemaStore/schemastore/issues/2919
- https://github.com/ansible/ansible-lint/issues/3341
