### ISSUE TITLE
pandoc hangs on an org to html conversion

### ISSUE THREAD

**Issue by ju-sh** [jgm/pandoc#8811]
Was trying to convert this org file to html:
[in.gz](https://github.com/jgm/pandoc/files/11346502/in.gz)

I used this command:
`pandoc in.org -o out.html`

But pandoc's memory usage keeps expanding till it fills all available RAM and gets stuck.

Couldn't figure out why two `|` characters pose problem.

What could be going wrong here? Any idea?

 - Pandoc version:  2.17.1.1
(Couldn't get pandoc 3 running yet.)

**Comment by jgm** [comment]
The latest version has no trouble with this, so I suspect this can be closed.

**Comment by tarleb** [comment]
Possibly a duplicate of #8659.
