### ISSUE TITLE
Pandoc does not convert Docx' style "Intense Quote" properly

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#8832]
**Explain the problem.**
Docx style "Intense Quote" is not being handled the same as "Quote". It is being converted to a Paragraph when converting to HTML or Markdown.

**Pandoc version?**
Pandoc 3.1.2 on Debian

Microsoft Word (2021) Mac

**Screenshots**

![image](https://user-images.githubusercontent.com/3169264/236817602-99ace570-f49f-4b89-a8f9-5d60ec8e66cd.png)

![image](https://user-images.githubusercontent.com/3169264/236817639-5ba4fc4a-5b8d-40ae-93eb-5c01d2bcbf97.png)

---

See #8830

**Comment by jgm** [comment]
Closed by PR #8830
