### ISSUE TITLE
Document how to build .deb-files

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#8833]
**Describe your proposed improvement and the problem it solves.**

I would like to see documentation about building`.deb` files so I can build custom pandoc builds.

**Describe alternatives you've considered.**

Reverse-engineer CI-files

**Comment by jgm** [comment]
`make deb`
See the Makefile and `linux/make_artifacts.sh`

**Comment by StephanMeijer** [comment]
@jgm `make deb` is not a valid rule. I think you mean `make debpkg`. When using that, it misses `cabal update` in the `linux/make_artifacts.sh`. When I use `linux/make_artifacts.sh`, it fails on:

```
echo "Checking that the binary is statically linked..."
file "$ARTIFACTS/pandoc" | grep "statically linked"
```

**Comment by jgm** [comment]
This is designed to be used in an alpine container.
If you don't care about static linking, you can simply remove that check.
