### ISSUE TITLE
Makefile/make_artifacts.sh seem malfunctioning

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#8834]
See #8833

**Explain the problem.**

when using `make debpkg`, it seems to miss `cabal update` in `make_artifacts.sh` as it misses dependencies.

When using `make_artifacts.sh` on my host (Ubuntu), it fails on:

```
echo "Checking that the binary is statically linked..."
file "$ARTIFACTS/pandoc" | grep "statically linked"
```

When I update `make_artifacts.sh` to include `cabal update`, the container also fails on that.

**Pandoc version?**
Latest.

**Comment by jgm** [comment]
I forgot that we don't actually use `make debpkg` in CI any more.
See .cirrus.yml for what should be pretty clear instructions.

**Comment by jgm** [comment]
To get a static binary, you need to build pandoc in an alpine container (see .cirrus.yml for the one we use) and you need to use certain compilation flags. `make_artifacts.sh` presupposes that CABALOPTS and GHCOPTS are set properly, and .cirrus.yml will give you appropriate settings. If you don't want to use a container and don't care about having a static binary, just remove the check in `make_artifacts.sh`.

**Comment by StephanMeijer** [comment]
@jgm I attempted that, to take over the CABAL_OPTS and GHCOPTS from `.cirrus.yml`, but it has the same result.

I actually care about it having a static binary. I would like to build a `.deb` and install that specific`.deb` in my containers.

I will inject at the beginning of `make_artifacts.sh`:

```
CABALOPTS="-f-export-dynamic -fembed_data_files -fserver -flua --enable-executable-static -j4"
GHCOPTS="-j4 +RTS -A256m -RTS -split-sections -optc-Os -optl=-pthread"
```

After build, I will send you the results.

**Comment by StephanMeijer** [comment]
I will after running attempt it in an Alpine container (currently using my host Ubuntu).

**Comment by StephanMeijer** [comment]
@jgm The image used in `.cirrus.yml` is equivalent to the image used `make debpkg`. If I state the env vars used by `.cirrus.yml` in `make_artifacts.sh` and run `cabal update` in `make_artifacts.sh`, shouldn't that produce a non-dynamically linked binary? Currently it produces a dynamically linked one.

**Comment by StephanMeijer** [comment]
Fixed:

https://gitlab.com/toegang-voor-iedereen/build-pandoc
