### ISSUE TITLE
CJK quotation mark

### ISSUE THREAD

**Issue by jiucenglou** [jgm/pandoc#8839]
**Explain the problem.**
When there is CJK character in front, the beginning quote is not dealt with correctly.
However, when there is other CJK quotation mark in front, the beginning quote is dealt with correctly.

Can the beginning quote be fixed ? Many thanks !

```markdown
以上对应"hydroxo-oxo"、"oxo-oxo"的情况.
```

```bash
./pandoc test.md -s -o test.docx
```

![Screenshot 2023-05-09 180905](https://github.com/jgm/pandoc/assets/37147430/34650304-f4bb-4c12-bd4e-944257cedc37)

[test.docx](https://github.com/jgm/pandoc/files/11429827/test.docx)
[test.md](https://github.com/jgm/pandoc/files/11429831/test.md)

**Pandoc version?**
latest 3.1.2

**Comment by jiucenglou** [comment]
> We use heuristics for smart quotes, and these heuristics rely on whitespace between words. If you have concrete suggestions for how to extend the heuristics to this case, feel free to make them, but I think the most reliable solution is just to use unicode curly-quotes in your input when you're using CJK.

Thank you for your helpful comments ! I went on keeping space before the opening quote :D (and remove them in lua filter when convert to docx)

**Comment by wohenbushuang** [comment]
> the most reliable solution is just to use unicode curly-quotes in your input when you're using CJK.

However, the unicode curly-quotes will also be set as a English font family (half-width character) when converting into MS Word. I have wasted some time on this issue, and I'd like to share what I have found.

For example,

```md
<!-- test.md -->
中文“引号”测试

English "quotation" test
```
![image](https://github.com/jgm/pandoc/assets/15613184/2508c4b1-2815-463c-95fd-c0abcbd285bc)

```shell
pandoc test.md -o test.docx
```

![image](https://github.com/jgm/pandoc/assets/15613184/2a0a075f-d816-43e0-8a15-0d2182f301c2)

and you can see that the dumb quotes in the second line was changed to unicode curly-quotes, maybe the heuristics work I guess. But the quotation mark in the first line was also set as a English font family, which seems the same as in the second line.

## Solution

I've found a way to quickly resolve this issue manually. If you use Word 2013 or later, select the lines involved, then click the language panel in the bottom toolbar, and set them as Chinese. Besides, there exists other ways to solve the problem, such as using Word's replace function.

![image](https://github.com/jgm/pandoc/assets/15613184/e880e2b8-a5dd-4dd1-99fd-34f24c4ef9e1)

![image](https://github.com/jgm/pandoc/assets/15613184/670922b6-985b-4ce2-852a-1269e0a1d704)

Note that all selected quotation marks will be changed to a Chinese font family, which will be full-width characters. So if there is any quotation mark in English sentences, you need to deal with it manually.

## Reason
It seems that there is no individual full-width character for quotation marks in [Unicode](https://symbl.cc/en/search/?q=quotation). U+0022 is the dumb quote, and U+201C and U+201D are left and right double quotes, which are rendered as half-width and full-width characters in English and Chinese font families, respectively.

Further readings:
https://en.wikipedia.org/wiki/Quotation_mark#Summary_table_for_all_languages
https://www.zhihu.com/question/31424658 (in Chinese)

**Comment by SuibianP** [comment]
@jgm Maybe keep the original quotation mark if there is no space on either size so that `应"h` remains unchanged? Or do some simple matching to decide if it is opening or closing.
