### ISSUE TITLE
[FEAT] Windows EXE in separate files

### ISSUE THREAD

**Issue by Kochise** [jgm/pandoc#8842]
Hi,

instead to have a "statically linked" 130+ MiB file, could it be possible to have a lighter EXE with DLL files ?

Mostly for GitHub storage without LFS.

Regards.

**Comment by jgm** [comment]
It's possible, I believe, but we're not going to provide this.  You can compile pandoc yourself if you want this, but I'm sorry, I can't give you instructions because I don't use Windows.
