### ISSUE TITLE
Converter needed to convert asciidoc (adoc) files to latex and pdf

### ISSUE THREAD

**Issue by aksigkvgithub** [jgm/pandoc#8845]
Dear sir,

At present there is no converter to convert from asciidoc adoc file to LaTeX and from LaTeX toolchain to pdf.

I know that some people suggest using asciidoc to docbook to LaTeX to pdf or directly to pdf from docbook.

However, I have seen this. This approach doesn't work properly because equation numbers, page layout etc and many other formats get disturbed..

Asciidoctor people render their pdf too. But, their mathematical rendering process is too complex and unavailable to many, moreover many features after rendering are not up to the modern standards, more specifically in mathematical aspects, probably because they don't follow LaTeX toolchain..

I raised this at their forum. But since most of their developers are Ruby based they don't understand LaTeX based conversion toolchain.

Moreover, pandoc already converts to asciidoc from other formats.

If only pandoc accepts our request to develop an asciidoc (adoc)  to LaTeX and pdf converter, that will be a great boon to asciidoc users to have a nice LaTeX file and pdf with proper page setting etc.

Secondly if later pandoc decides to add the same converters to quarto too, then users of R along with that of asciidoc will also be greatly benefited.

I hope my request will be positively accepted by pandoc.

Thanking you all in anticipation.

With regards,

**Comment by tarleb** [comment]
Thank you for the kind request.

Please note that a native Asciidoc reader would not necessarily ensure that all Asciidoc features would be supported. Equation numbers and similar things are not part of pandoc's internal document representation, so they might still be lost. Supporting those would require changes in many parts of pandoc.

I'm closing this issue in favor of #1456, which covers the same topic. Please see there for more info.
