### ISSUE TITLE
Ubuntu 23.04 typesetting has no citeproc or pandoc-citeproc support

### ISSUE THREAD

**Issue by engines-wafu** [jgm/pandoc#8846]
Using pandoc in Ubuntu 23.04 and attempting to typeset using `--filter citeproc` or `--filter pandoc-citeproc`, e.g.:

`pandoc --from markdown+multiline_tables --template some_template.tex --pdf-engine=pdflatex --listings --number-sections --filter pandoc-citeproc --csl some_csl.csl input.md -o output.pdf`

Results in:

`Error running filter citeproc:`
`Could not find executable citeproc`

Or:

`[WARNING] Deprecated: pandoc-citeproc filter. Use --citeproc instead.`
`Error running filter pandoc-citeproc:`

Respectively. This workflow has been verified as valid for 22.03. No apt repository entries exist for either citeproc or pandoc-citeproc exist in the lunar repositories. Attempted to install the python3 variant or citeproc with no joy.

**Comment by engines-wafu** [comment]
This has been tried with the 23.04 apt build of pandoc and with release 3.1.2 installation package from this repo.

**Comment by jgm** [comment]
Use `--citeproc`, not `--filter citeproc`, as described in `man pandoc`.
