### ISSUE TITLE
Error when set pdf-engine to typst (Windows OS)

### ISSUE THREAD

**Issue by sevehub** [jgm/pandoc#8854]
On Windows OS (Command prompt)  I am getting the following error message when I set _typst_  as pdf-engine.
Example of a typical command line that reproduces the error:
` pandoc.exe --pdf-engine=typst typst.md -o typst.pdf   `    
Typical error:

```
error: unrecognized subcommand '.\toP2905.html'

Usage: typst [OPTIONS] <COMMAND>

For more information, try '--help'.
Error producing PDF.

```
**Pandoc version 3.1.2**
**Typst version 0.3.0**

**Comment by jgm** [comment]
See #8754

**Comment by jgm** [comment]
This is fixed in the dev version but not in the latest release.
As a workaround you could try `--pdf-engine-opt=compile`
