### ISSUE TITLE
dokuwiki->mediawiki: Headings starting with capital letter renders to an empty span section 

### ISSUE THREAD

**Issue by Aschroet** [jgm/pandoc#8855]
When converting from dokuwiki to mediawiki (_pandoc -f dokuwiki -t mediawiki_) one gets interesting results:

### Correct conversion for a heading with non-capitalized naming:

Input:
`====== test ======`

Output:
`= test =`

### Wrong conversion for a heading with capitalized naming:

Input:
`====== Test ======`

Output:
```
<span id="test"></span>
= Test =
```

Same holds for other levels of headings.

**Comment by jgm** [comment]
Yes, this is intentional.  The empty span gives you an anchor with the id of the section. It isn't necessary in the lowercase heading because mediawiki will in that case assign the same id implicitly.
Not a bug.

**Comment by Aschroet** [comment]
@jgm, thank you for the clarification.

Maybe i could somehow hijack this issue to ask another unclear conversation for lists. We got Dokuwiki text with an _item 1_ and two space indentation followed by an _item 1.1._ with three instead of four spaces. Dokuwiki itself properly renders the items to level one resp. two but pandoc cannot deal with _item 1.1_ leading to a  pre-section.

Input:
```
  * item 1
   * item 1.1
``` 

Output:
```
* item 1

<pre> * item 1.1
</pre>
```
Maybe this is not the fault of pandoc because the input is not following the specification. But maybe you have an idea how to format Dokuwiki text before using pandoc.

Thank you in advance.

**Comment by jgm** [comment]
This sounds like a bug in dokuwiki list parsing; can you report it in a separate issue?
