### ISSUE TITLE
Docx writer doesn't add bookmarks for figures

### ISSUE THREAD

**Issue by lierdakil** [jgm/pandoc#8862]
Docx writer creates bookmarks for divs, tables, etc, but evidently not figures. AFAICT, `wrapBookmark` is just missing from https://github.com/jgm/pandoc/blob/4a6950200ff148b44b38c20f015100bb4d7e5033/src/Text/Pandoc/Writers/Docx.hs#L1013

Additional context: this was reported in https://github.com/lierdakil/pandoc-crossref/issues/374, I've been meaning to open a PR, but frankly I forgot. I don't really have the time to do it right now either, so I figured I could at least open a bug report.

**Comment by FeralFlora** [comment]
What's the status of this issue?
