### ISSUE TITLE
dokuwiki->mediawiki: List parsing

### ISSUE THREAD

**Issue by Aschroet** [jgm/pandoc#8863]
When converting from dokuwiki to mediawiki (_pandoc -f dokuwiki -t mediawiki_) one gets unexpected results for lists. Example:

Input:
```
  * item 1
   * item 1.1
``` 

Actual output:
```
* item 1

<pre> * item 1.1
</pre>
```

Expected output:
```
* item 1
** item 1.1
```

Pandoc properly renders _item 1_, which is level one having two heading spaces. But it cannot deal with _item 1.1_, which is level two having three heading spaces. Per definition there should be four spaces for level two items but Dokuwiki itself can deal with it.

**Comment by jgm** [comment]
According to the dokuwiki sandbox (just tested), item 1.1 is parsed at level 1 in this example.
I will implement that behavior.
