### ISSUE TITLE
base64 image is not handled by pandoc from html to latex

### ISSUE THREAD

**Issue by etclub** [jgm/pandoc#8864]
I have quite a few base64 images in my html document. 
An example is attached (maybe you have to rename it from md to html, as html file is not allowed as attachment on github).
[doc.md](https://github.com/jgm/pandoc/files/11526308/doc.md)

Pandoc 3.1.2 seems not handle it right. It results in nothing without reporting error or warning.

BTW, if I convert it to pdf directly, it works fine. 
But I have to convert it to latex first to do some postprocessing before to pdf.
I am wondering if base64 images can still be handled right in this process.

**Comment by jgm** [comment]
If you specify `--verbose`, you will get a message indicating that the image is being skipped.

To get the image, you need to use `--extract-media=media`, and then pandoc will extract it into a file and produce an `includegraphics` command that refers to that file.

**Comment by etclub** [comment]
Thanks. It now handles the base64 images.
But I also have some local images in the document, say `img/local.png`.
Pandoc reports:
```
[WARNING] Could not fetch resource img/local.png: replacing image with description
```
And the local images are gone in resulting pdf.

**Comment by jgm** [comment]
I can't reproduce this. When I add a link to a local image to your test document, and process it with `pandoc doc.html -o doc.pdf`, both the encoded image and the image from the file system appear in the PDF.

**Comment by etclub** [comment]
Yes.
But I have to convert it to latex first to do some postprocessing before to pdf.
So please try `pandoc --extract-media=media doc.html -o doc.tex`
