### ISSUE TITLE
latex parsing: final item label in theorem environment applied to theorem rather than item

### ISSUE THREAD

**Issue by ultronozm** [jgm/pandoc#8872]
pandoc version 3.1.2 on macOS 12.6, "pandoc test.tex -o test.md"

Input:

```
\documentclass{amsart}
\newtheorem{theorem}{Theorem}
\begin{document}
\begin{theorem}\label{thm}
\begin{enumerate}
\item \label{item1} text1
\item \label{item2} text2
\item text3
\end{enumerate}
\end{theorem}
\end{document}
```

Output:

```
::: {#item2 .theorem}
**Theorem 1**. *[]{#thm label="thm"}*

1.  *[]{#item1 label="item1"} text1*

2.  *text2*

3.  *text3*
:::
```

Expected output:

```
::: {#thm .theorem}
**Theorem 1**.

1.  *[]{#item1 label="item1"} text1*

2.  *[]{#item2 label="item2"} text2*

3.  *text3*
:::
```

That is to say, the final item label is applied to the enclosing block rather than to the item.

I wasn't able to find related issues in github or pandoc-discuss.  I would be happy to try to understand this issue better.  Would Text/Pandoc/Readers/LaTeX.hs be the place to look?

**Comment by jgm** [comment]
T/P/Readers/LaTeX/Math.hs theoremEnvironment.

We currently do something fairly primitive.  When we encounter a label, we modify sLastLabel in state.  We then check this after parsing a theorem environment.
