### ISSUE TITLE
Bug on UBUNTU apt distribution

### ISSUE THREAD

**Issue by ppKrauss** [jgm/pandoc#8881]
All explained at https://stackoverflow.com/questions/61100045/how-to-install-stable-and-fresh-pandoc-on-ubuntu

PS: please, it is a real and  3 years-old problem, the bug-report was  viewed 3k times.

**Comment by jgm** [comment]
This should not be reported here.  We have nothing to do with Ubuntu packaging.

**Comment by ppKrauss** [comment]
please @jgm help to contact Ubuntu as a legitime software onwner. The problem persist and grows, see https://stackoverflow.com/q/61100045/287948  but we are users

**Comment by jgm** [comment]
Ubuntu just gets their packages from Debian.  I am in touch with the Debian maintainers. There are reasons why it's been hard to get pandoc updated there, but I'm pleased to report that pandoc 3.0.1 has now entered Debian testing.

I would recommend that Ubuntu users simply install the deb package from our releases page.  It will work on Ubuntu and it will be the latest version.
