### ISSUE TITLE
.sty for .tex template not found unless in the same directory as .md file and path contains space

### ISSUE THREAD

**Issue by universvm** [jgm/pandoc#8894]
**Explain the problem.**
Hi,

I have 3 files:

- prova.md
- academic.tex
- neurips.sty

If I place the style and markdown files in the same directory, I am able to output this PDF:

<img width="544" alt="Screenshot 2023-06-06 at 10 57 03" src="https://github.com/jgm/pandoc/assets/17524568/2a418326-963b-45c1-a5de-21abccb53245">

However, when they are not,I get the error:

```
Error producing PDF.
! LaTeX Error: File `neurips.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.11 ^^M
```
This is my minimal pandoc command:

```
pandoc -f markdown 
--resource-path="/Users/leo/Library/Mobile Documents/iCloud~md~obsidian/{REDACTED}/textemplate/" 
--template="academic.tex" -s -t pdf  "prova.md" --pdf-engine=pdflatex --output="prova.pdf"
```

Things that I've tried:

1. Adding a resource path
2. Placing the .sty file in the same path as the academic.tex
3. Adding `--include-in-header="/Users/leo/Library/Mobile Documents/iCloud~md~obsidian/{REDACTED}/textemplate/neurips.sty"`
4. Modifying the template with an absolute path in the usepackage

These are the files:

[templates.zip](https://github.com/jgm/pandoc/files/11663141/templates.zip)

The workarounds I have found:

1. keep the file in a path with no spaces. - This is not possible because the files are stored in iCloud with the `Mobile Documents` folder.
3. Append the path to TEXINPUTS. - Very clunky as we'd need to do this in a plugin.

**Pandoc version?**
MacOS

```
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13, citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /Users/leo/.local/share/pandoc

Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

```

**Comment by jgm** [comment]
Appending the path to TEXINPUTS seems the appropriate thing to do.

But I didn't understand the issue about spaces. Are you saying that resource-path works if and only if the path does not contain spaces?

**Comment by universvm** [comment]
Appending to TEXINPUTS is what we are looking into but it is a bit clunky from our code.  What is weird is that with the resource-path we can define the template.tex but not the style which is in the same folder as the template... 

` Are you saying that resource-path works if and only if the path does not contain spaces?`

Apologies, that's what I thought but it is not the case. If the latex template is modified so to take the stylefile path as such:

`\usepackage[final]{$stylefile$}`

and folder structure 

`folder 1`
- academic.tex
- neurips.sty

`folder2``
- paper.md


- If you use `folder1` you produce the PDF 

```
❯ pandoc -f markdown --embed-resources --standalone -s -o "/Users/leo/Desktop/newpaper.pdf" -t pdf  --resource-path="/Users/leo/Desktop/folder1" --template="academic.tex" "paper.md" -M stylefile="/Users/leo/Desktop/folder1/neurips"
```

- If you use `folder 1` you **cannot** produce the PDF:
```
❯ pandoc -f markdown --embed-resources --standalone -s -o "/Users/leo/Desktop/newpaper.pdf" -t pdf  --resource-path="/Users/leo/Desktop/folder 1" --template="academic.tex" "paper.md" -M stylefile="/Users/leo/Desktop/folder 1/neurips"
Error producing PDF.
! LaTeX Error: File `/Users/leo/Desktop/folder1/neurips.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.11 ^^M
```

- If you sanitise the path for the space as such, you get this other error:

```
❯ pandoc -f markdown --embed-resources --standalone -s -o "/Users/leo/Desktop/newpaper.pdf" -t pdf  --resource-path="/Users/leo/Desktop/folder 1" --template="academic.tex" "paper.md" -M stylefile="/Users/leo/Desktop/folder\ 1/neurips"
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=10000].
\curr@fontshape ->\f@encoding
                              /\f@family /\f@series /\f@shape
l.11

```

**Comment by jgm** [comment]
Can you whittle down the spacing issue to an extremely minimal test case and provide all the needed files (or ideally a zip file that can demonstrate it)?

The LaTeX reader uses TEXINPUTS as its input path for packages, not `--resource-path`.

**Comment by universvm** [comment]
Hi @jgm 

essentially it seems like latex cannot handle spaces when providing a path to the style as 

`\usepackage[final]{path/to/folder with space/style}`

But this works

`\usepackage[final]{path/to/folderwithspace/style}`

No amount of path sanitising worked so I just used the TEXINPUTS solution.

I kind of wished I could control the path of the style much like the `resource-path` but it does not seem possible as far as I understand.

Feel free to close the issue and thanks again for your help!
