### ISSUE TITLE
Mermaid functionality using script

### ISSUE THREAD

**Issue by maurerle** [jgm/pandoc#8897]
**Explain the problem.**

The question boils down to: Is there already a way to escape text inside my ::: block and have it handled raw?

Background:

Currently, there are multiple ways to integrate mermaid.js into a revealjs presentation with pandoc:

using a revealjs plugin: 
* https://github.com/ludwick/reveal.js-mermaid-plugin
* https://github.com/zjffun/reveal.js-mermaid-plugin

or a filter:
* https://github.com/raghur/mermaid-filter

Even though github markdown now supports Mermaidjs, it is unsupported in here rendering to `gfm` ([listed here](https://pandoc.org/MANUAL.html#markdown-variants))

----

Yet I want to integrate plain mermaid without prerendered svgs:

So I have a file `before.html`,
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.6.3/mermaid.min.js"></script>
```

which gets loaded through cli param: `--include-before before.html` or through `include-before-body: before.html` in the `-d pandoc.yml`

Then I add a div of class mermaid using:

```md
::: mermaid
graph LR;
    A-->B;
    click A callback "Tooltip for a callback"
    click B "http://www.github.com" "This is a tooltip for a link"
:::
```

And render my file using pandoc.
In the resulting index.html i see:

```html
<div class="mermaid">
<p>graph LR; A&#x2013;&gt;B; click A callback &#x201C;Tooltip for a callback&#x201D; click B
&#x201C;http://www.github.com&#x201D; &#x201C;This is a tooltip for a link&#x201D;</p>
</div>
```

but the final html should look like this:
```html
<h2 >Mermaid Test</h2>
<div class="mermaid">
graph LR;
    A-->B;
    click A callback "Tooltip for a callback"
    click B "http://www.github.com" "This is a tooltip for a link"
</div>
```

**Is there already a way to escape the text inside my ::: block?**

**Pandoc version?**
pandoc 2.18 on Debian 12

**Comment by jgm** [comment]
If you want everything to be passed through literally:
````
```{=html}
<div class="mermaid">
graph LR;
    A-->B;
    click A callback "Tooltip for a callback"
    click B "http://www.github.com" "This is a tooltip for a link"
</div>
```
````

**Comment by maurerle** [comment]
Thank you, I nearly had it, but had some unwanted <p> around left, your solution works great!

I think it would be great to have a switch for `$if(mermaid)$` which loads the script conditionally, so that one does not need to have the `before.html` and I would love to have something about it in some docs, because I struggled quite a long time with this.
Thats the easiest way to integrate mermaidjs into my presentation.

Would you include such a feature if i propose a PR?

**Comment by raphaelsetin** [comment]
### For whoever stumbles upon this, the following is what came up with that allowed my VS Code Mermaid plugins to remain working, in contrast to @jgm's [answer](https://github.com/jgm/pandoc/issues/8897#issuecomment-1583029088), which had broken my VS Code preview.

---

### Steps

1. Install the `panflute` Python library:
  ```shell
  pip install panflute
  ```
2. Create the following file -- `mermaid_filter.py` -- to do the filtering:
  ```python
  import panflute as pf

def mermaid_filter(element, doc):
  if isinstance(element, pf.CodeBlock) and 'mermaid' in element.classes:
    # Prepare the text to be HTML friendly, converting special HTML characters
    html_text = pf.stringify(element, newlines=True)  # This should maintain newlines

    # Encapsulate the Mermaid diagram in a div with class "mermaid"
    raw_html = f'<div class="mermaid">\n{html_text}\n</div>'

    # Return as a raw block that will not be processed further by Pandoc
    return pf.RawBlock(raw_html, format='html')

def main(doc=None):
  return pf.run_filter(mermaid_filter, doc=doc)

if __name__ == '__main__':
  main()
  ```
3. Create the following file -- `mermaid-html` -- for Pandoc to add it to the final HTML and thus include the Mermaid script there:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.0/mermaid.min.js"></script>
```
4. Call pandoc:
```shell
pandoc \
  -f commonmark_x \
  --embed-resources \
  --standalone \
  --toc \
  -c "my-styles.css" \
  -o "Final Document.html" \
  --metadata \
  title="Document Title" \
  --include-in-header "mermaid.html" \
  --filter python "mermaid_filter.py"
```

---

### With this solution, you can use Mermaid graphs in Markdown as you would expect, like:
<pre>
## Sequence Diagram Example

```mermaid
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
```

## Flowchart Example

```mermaid
flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```
</pre>

@maurerle You don't need anymore to do what @jgm explained [above](https://github.com/jgm/pandoc/issues/8897#issuecomment-1583029088).
