### ISSUE TITLE
Large HTML to EPUB causes pandoc 3.1.3 Killed/Bus Error/Segmentation Fault on Debian 11

### ISSUE THREAD

**Issue by RobertKosten** [jgm/pandoc#8899]
On a clean, up-to-date Debian 11 VM (QubesOS):

```
wget https://github.com/jgm/pandoc/releases/download/3.1.3/pandoc-3.1.3-linux-amd64.tar.gz
tar xzf pandoc-3.1.3-linux-amd64.tar.gz
wget https://www.php.net/distributions/manual/php_manual_en.html.gz
gzip -d php_manual_en.html.gz
./pandoc-3.1.3/bin/pandoc -f html -t epub -o php_manual_en.epub php_manual_en.html
```

Process runs fro a while, then gets `Killed`. The debian repo version of pandoc, 2.9.2.1, varies between `Bus Error` and `Segmentation Fault`). I can see that it simply consumes all available RAM+Swap, which surprises me, because, while the input is large (54MiB), it's not 16GiB large... And plain html ought to be an ideal source to generate epub. Am I running into a memory leak or is the internal representation really that large?

**Comment by jgm** [comment]
You're using an old version of pandoc.  I tried that file with the latest release and it took 82 seconds to convert, using 1.6G memory (M1 mac).  Could be that you've run into a performance bug that has been fixed since 2.9.2 -- we've fixed some exponential parsing bugs over the years, especially with badly formed HTML.

> plain html ought to be an ideal source to generate epub.

Well yes, but not via pandoc. Pandoc is going to parse the HTML into its internal format (a lossy conversion), and then write this out again as HTML in the EPUB.  The fact that the output uses HTML doesn't really make a difference, since the conversion always goes via a Pandoc intermediate structure.

**Comment by RobertKosten** [comment]
To report is on version 3.1.3, which  was released 3 days ago and is the newest available on github. I merely ran against the debian-packaged version (2.9.2.1) to confirm the issue has been present since at least then. I don't find it surprising you cannot reproduce it on a M1 mac; this is am x86_64 debian vm with a very different memory structure. I can *observe* it using up the 16GiB I provide before getting killed.

Since you can run that in 1.6GiB (which is still a lot, IMHO, even when keeping a tree of that in memory), I assume there is a memory leak in the x86_64 code which causes this 10+ times increase.

**Comment by jgm** [comment]
Sorry, I missed that you tried it with 3.1.3.
I will try to reproduce it on a debian x86_64 system I have.

**Comment by jgm** [comment]
I can reproduce it on the other machine.

This document contains some pretty funky HTML, which violates expectations pandoc has.  Example:

```html
<div class="refsect1 examples" id="refsect1-function.get-called-class-examples">
  <h3 class="title">Examples</h3>
  <p class="para">
   <div class="example" id="example-5116">
    <p><strong>Example #1 Using <span class="function"><strong>get_called_class()</strong></span></strong></p>
    <div class="example-contents">
     <div class="phpcode"><code>..snip...</code></div>
    </div>

    <div class="example-contents">
     <p>The above example will output:</p>
    </div>
    <div class="example-contents screen">
      <div class="cdata"><pre>
string(3) &quot;foo&quot;
string(3) &quot;bar&quot;
</pre>
      </div>
    </div>
   </div>
  </p>
 </div>
```
Here we have a `p` element that contains a `div` that contains another `p`, etc.  Pandoc assumes that `p` elements won't contain block-level content and is probably getting confused by this.  `htmltidy` also spits out about 10,000 warnings about "empty p elements."

**Comment by jgm** [comment]
As you can see, pandoc does a decent job handling this crazy HTML:
```native
[ Div
    ( "refsect1-function.get-called-class-examples"
    , [ "refsect1" , "examples" ]
    , []
    )
    [ Header
        3 ( "examples" , [ "title" ] , [] ) [ Str "Examples" ]
    , Div
        ( "example-5116" , [ "example" ] , [] )
        [ Para
            [ Strong
                [ Str "Example"
                , Space
                , Str "#1"
                , Space
                , Str "Using"
                , Space
                , Span
                    ( "" , [ "function" ] , [] )
                    [ Strong [ Str "get_called_class()" ] ]
                ]
            ]
        , Div
            ( "" , [ "example-contents" ] , [] )
            [ Div
                ( "" , [ "phpcode" ] , [] )
                [ Plain [ Code ( "" , [] , [] ) "..snip..." ] ]
            ]
        , Div
            ( "" , [ "example-contents" ] , [] )
            [ Para
                [ Str "The"
                , Space
                , Str "above"
                , Space
                , Str "example"
                , Space
                , Str "will"
                , Space
                , Str "output:"
                ]
            ]
        , Div
            ( "" , [ "example-contents" , "screen" ] , [] )
            [ Div
                ( "" , [ "cdata" ] , [] )
                [ CodeBlock
                    ( "" , [] , [] )
                    "string(3) \"foo\"\nstring(3) \"bar\""
                ]
            ]
        ]
    ]
]
```
but the parser isn't good enough to have linear behavior in such circumstances.

**Comment by jgm** [comment]
Indeed I think the HTML is invalid (it's supposed to be HTML 4): it says
```
<!ELEMENT P - O (%inline;)*            -- paragraph -->
```
which means that `<p>` can't have `<div>` or `<p>` beneath it.

**Comment by jgm** [comment]
I tried an experiment - converted the document to HTML using pandoc (thus cleaning up all the funky HTML). Even with this, conversion runs out of memory on the x86 system.

**Comment by mheinzel** [comment]
Have you tried running it with trace logging enabled to see if it's similar to https://github.com/jgm/pandoc/issues/8762?

**Comment by jgm** [comment]
Sounds like we have a diagnosis.
https://groups.google.com/g/pandoc-discuss/c/6TsOKtbkXTM/m/XPIKEAvxAQAJ
It's #8779

**Comment by jgm** [comment]
Note that homebrew packaging for pandoc seems to be broken as it uses an affected ghc version.  It would be worth an issue on their tracker to alert them of this.
