### ISSUE TITLE
Pandoc strucks during compilation of latex file with unexpected () at \begin{document}

### ISSUE THREAD

**Issue by Abdel5** [jgm/pandoc#8901]
Hi,

pan dock `3.13. ` strucks with error on latex file which compiles correctly on overleaf. 

`Error at "main.tex" (line 161, column 17):
unexpected ()
\begin{document}
                ^`

 Near given line 161 fragment is:

> % Disable hypernation [work]
> 
> 
> % Document start
> \begin{document}
> 
> \makenomenclature
> \include{nomenclature} 
> 

Similar problem was reported on superuser.com (https://superuser.com/questions/1773140/using-pandoc-to-convert-latex-into-plain-text-unexpected-begindocument)

**Comment by jgm** [comment]
This error usually occurs when pandoc gets confused parsing the document's preamble.
It's impossible to say more without seeing the actual document.

**Comment by Abdel5** [comment]
Hi jgm,

thanks for reply. Great idea of software.

The preamble that causes the error:
```

\documentclass[12pt,a4paper]{book}
\usepackage[utf8]{inputenc}
\usepackage{csquotes}
\usepackage[english,polish]{babel}
\usepackage[T1]{fontenc}
\usepackage[multiple]{footmisc}
\usepackage{import}
\usepackage{csquotes}
\usepackage{enumitem}
\usepackage{tabularx} 
\usepackage{xcolor}
\usepackage{parskip}
\usepackage{url}
\usepackage{graphicx}

\graphicspath{ {./0_img} }

% Fancy HF
\usepackage{fancyhdr} 
\fancyhf{}
% \cfoot{\thepage}
\renewcommand{\headrulewidth}{0pt}

\fancypagestyle{plain}{%
  \fancyhf{}%
}

% Nomenclature
\usepackage{nomencl}

% Bibliography
\usepackage[datamodel=ruling, style=authortitle-ibid, dashed=false]{biblatex}

\bibliography{Bibliografia/0_http.bib}
\bibliography{Bibliografia/0_oecd.bib}
\bibliography{Bibliografia/0_TSUE.bib}
\bibliography{Bibliografia/0_opinieZabezp.bib}
\bibliography{Bibliografia/0_radaPUO.bib}
\bibliography{Bibliografia/0_tk.bib}
\bibliography{Bibliografia/0_WSA.bib}
\bibliography{Bibliografia/0_NSA.bib}
\bibliography{Bibliografia/0_wyr.bib}
\bibliography{Bibliografia/bib_a.bib}
\bibliography{Bibliografia/bib_b.bib}
\bibliography{Bibliografia/bib_c.bib}
\bibliography{Bibliografia/bib_d.bib}
\bibliography{Bibliografia/bib_e.bib} 
\bibliography{Bibliografia/bib_f.bib}
 \bibliography{Bibliografia/bib_g.bib}
 \bibliography{Bibliografia/bib_h.bib}
\bibliography{Bibliografia/bib_i.bib} 
\bibliography{Bibliografia/bib_j.bib}
 \bibliography{Bibliografia/bib_s.bib}
 \bibliography{Bibliografia/bib_k.bib}
 \bibliography{Bibliografia/bib_kondej.bib}
\bibliography{Bibliografia/bib_l.bib}
\bibliography{Bibliografia/bib_n.bib}
\bibliography{Bibliografia/bib_m.bib} 
\bibliography{Bibliografia/bib_o.bib}
\bibliography{Bibliografia/bib_p.bib}
\bibliography{Bibliografia/bib_r.bib}
\bibliography{Bibliografia/bib_t.bib}
\bibliography{Bibliografia/bib_w.bib}
\bibliography{Bibliografia/bib_v.bib}
\bibliography{Bibliografia/bib_z.bib}

% Inicjały
\DeclareNameFormat{labelname}{%
  \ifnumless{\value{uniquename}}{2}
    {\usebibmacro{name:family-given}
       {\namepartfamily}
       {\namepartgiveni}
       {\namepartprefix}
       {\namepartsuffix}}
    {\usebibmacro{name:family-given}
      {\namepartfamily}
      {\namepartgiven}
      {\namepartprefix}
      {\namepartsuffix}}%
  \usebibmacro{name:andothers}}

\DeclareNameAlias{sortname}{family-given}

\DeclareDelimFormat{titleyeardelim}{\addcomma\space}

\renewbibmacro*{cite}{%
  \iffieldundef{shorthand}
    {\printnames{labelname}%
     \setunit*{\printdelim{nametitledelim}}%
     \usebibmacro{cite:title}%
     \setunit{\printdelim{titleyeardelim}}%
     \printdate}%
    {\usebibmacro{cite:shorthand}}}


% Dedykacja

\newenvironment{dedication}
  {\clearpage           % we want a new page
   \thispagestyle{empty}% no header and footer
   \vspace*{\stretch{1}}% some space at the top 
   \itshape             % the text is in italics
   \raggedleft          % flush to the right margin
  }
  {\par % end the paragraph
   \vspace{\stretch{3}} % space at bottom is three times that at the top
   \clearpage           % finish off the page
  }

% Rozdział nowy bez TOC
\makeatletter
\newcommand{\unchapter}[1]{%
  \begingroup
  \let\@makechapterhead\@gobble % make \@makechapterhead do nothing
  \chapter{#1}
  \endgroup
}
\makeatother

% Disable numbering in footnotes 
\counterwithout{footnote}{chapter}

% Document start
\begin{document}
```

The error:
`Error at "main.tex" (line 124, column 17):
unexpected ()
\begin{document}
                ^`

**Comment by jgm** [comment]
OK, the preamble is not the issue, I think. pandoc parses that fine.
I suspect the problem has to do with
```
\makenomenclature
\include{nomenclature}
```
which includes a file with tex commands.  You could try commenting out those lines.
In any case, the trick is to try to isolate the issue by commenting things out -- that will help in diagnosing it.

**Comment by Abdel5** [comment]
I was not able to track down the source error. Commenting lines did not help.

I found out a walk around by manually specifying .tex files and leaving main.tex alone.

**Comment by R-e-d-J** [comment]
Same problem...

`
pandoc forces.tex -o mydoc.docx
Error at "forces.tex" (line 6, column 17):
unexpected ()
\begin{document}
                               ^
`

And here's my code :
`
\documentclass[10pt,a4paper]{report}
\begin{document}

\tableofcontents

\input{./chap_introduction.tex}
\input{./chap_referentiel_force.tex}
\input{./chap_corps.tex}
\input{./chap_statique.tex}
\input{./chap_dynamique.tex}

\end{document}
`

**Comment by jgm** [comment]
It's probably an issue in one of the included files, but impossible to diagnose without having them too.

**Comment by dj-on-github** [comment]
I get the same problem on MacOS Sonoma 14.6.1 on X86. It I not doing on one book and it is on the other, with a very similar preamble. I'll try and bisect the differeces.

**Comment by LinqLover** [comment]
Same issue. I'm trying to convert my 90-page thesis, so this error message really does not make it easy to investigate which part of my latex sources the parser is handling incorrectly.
