### ISSUE TITLE
Converting from md to tex causes Pandoc to make wrong http-link

### ISSUE THREAD

**Issue by Stivi** [jgm/pandoc#8903]
this md link:

```
[0:00:25](https://www.youtube.com/watch?v=I2yVb_Tc2gs&t=25s)
```

has converted to this tex link:

```
\href{https://www.youtube.com/watch?v=I2yVb_Tc2gs\&t=25s}{0:00:25}
```
There was an unnecessary backslash in `\&t=25s`.

Expected:

```
\href{https://www.youtube.com/watch?v=I2yVb_Tc2gs&t=25s}{0:00:25}
```

**Pandoc version**

```
pandoc 3.1.3
```

**Comment by jgm** [comment]
Does the link still  work with the backslash?  (Is this an aesthetic issue or a functional one?)
