### ISSUE TITLE
Fenced code to HTML: specifying a language vs not doing that

### ISSUE THREAD

**Issue by notnotrandom** [jgm/pandoc#8905]
Pandoc version: 3.0.1 (Archlinux)
Command line used:

~~~
/usr/bin/pandoc -f markdown+autolink_bare_uris --wrap=none src.md -o dest.html
~~~

---

Suppose I have a fenced code block, *without* specifying the language, like so:

~~~~
~~~
source foo
~~~
~~~~

This yields the following HTML:

~~~{.html}
<pre><code>source foo</code></pre>
~~~

Now consider the same code block, but with the language specified:

~~~~{.bash}
~~~{.bash}
source foo
~~~
~~~~

The HTML is now:

~~~{.html}
<div class="sourceCode" id="cb1"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> foo</span></code></pre></div>
~~~

The relevant difference is that with a language specified, the `<pre><code></code></pre>` is wrapped around a div. One of the differences this causes, is when the content is longer than max width available, for the version with a div the browser will add an horizontal slider, whilst for the "div-less" version, it will not. It gets worse when using a different background color for code blocks: for the div-less version, the part that overflows will retain the original white background.

I suppose the proper fix would be to use a div in both scenarios. Does this make sense? Thank you in advance for your time.

**Comment by jgm** [comment]
You can use `default` as the language name to get "null" syntax highlighting; it will then be like other highlighted code blocks except for the colors.
