### ISSUE TITLE
Add cross-AST string modifications to Lua filters

### ISSUE THREAD

**Issue by CodeSandwich** [jgm/pandoc#8907]
## The problem

Sometimes filters need to modify the text content of the document. The content may be broken up into multiple `Str`s and `Space`s, parts of it may be deeply nested in styling `Inline` nodes like `Strong` or `Cite`, and the structure `Block` nodes like `Div` and `Para`. Navigating the AST to find and modify pieces of the content is cumbersome and tricky, IMHO just infeasible.

For example I was trying to trim off a `- ` prefix from each paragraph, but many of them had some styling. It was borderline impossible to do in a generic way, I've resorted to filtering `Para`s by their stringified representations and `walk`ing each matching `Para` for `Str`s and `Space`s and removing the first occurrence of each of them. That's a backward solution and I have no idea how a more complex pattern could be handled. Even a 2-letter pattern like `ab` could be a single `Str` or be split into two deep, complex branches of the AST.

## The solution

The AST already has a very useful `pandoc.utils.stringify` function that extracts the content into a flattened string. This representation could be used as a map for some cross-AST operations. The user could do all kinds of analysis and pattern matching to get the needed character indexes. They could then be used to:

- Delete part of the content. Based on the stringified representation the user picks a range of character indexes, and the content is removed from the AST. Some nodes only describe parts that are to be deleted, such nodes are removed. Some nodes describe content to be partially deleted, such nodes have their content modified to reflect the partial deletion.
- Insert text into the content. Based on the stringified representation the user picks an index where the text should be inserted and relevant nodes are added to the AST. The exact node describing the picked index is found, and either the text is added to it, neighbors are added to its parent to express the text, or both. The inserted text de-facto inherits all the styling and the encapsulating document structure from the character pointed by the index. It may be useful to accept a flag controlling whether text should be inserted before or after the index.

Replacements are infeasible, because the pattern may span across multiple nodes and it's unclear how to preserve the structure of the AST. The user is expected to perform deletions and insertions on their own to construct whatever behavior they desire.

## The alternatives

Writing such a tool as a library. It should be doable by iterating over all the nodes depth-first and counting the total stringified length of all the encountered nodes to find the node describing a given index. That wouldn't be very future-proof, the AST may get more node types. It probably wouldn't be used by many people either, unless a utility is right in Pandoc, many people will never hear about it or won't trust it enough to rely on it.

**Comment by tarleb** [comment]
This would could potentially be very useful, but I'm afraid this is too complex and out of scope for pandoc.
