### ISSUE TITLE
Unnumbered chapters have wrong chapter headers

### ISSUE THREAD

**Issue by mcnesium** [jgm/pandoc#8912]
The headers in chapters without numbers are wrong. When running pandoc with `--number-sections` but having [unnumbered](https://pandoc.org/MANUAL.html#extension-header_attributes) sections (using `{-}` class for its header) and then disabling the headers using `disable-header-and-footer`, the header of that shows the title of one chapter before.

The screenshot below shows the unnumbered "References" chapter with the header of the previous "Conclusions" chapter. I would expect the header say "References" as well.

Here is a (hopefully) minimal reproducible example:

`refs.bib`:

<details>

    @article{t1,
    title={Title 1},
    author={Author 1},
    year={2023}
    }
    @article{t2,
    title={Title 2},
    author={Author 2},
    year={2023}
    }
    @article{t3,
    title={Title 3},
    author={Author 3},
    year={2023}
    }
    @article{t4,
    title={Title 4},
    author={Author 4},
    year={2023}
    }
    @article{t5,
    title={Title 5},
    author={Author 5},
    year={2023}
    }
    @article{t6,
    title={Title 6},
    author={Author 6},
    year={2023}
    }
    @article{t7,
    title={Title 7},
    author={Author 7},
    year={2023}
    }
    @article{t8,
    title={Title 8},
    author={Author 8},
    year={2023}
    }
    @article{t9,
    title={Title 9},
    author={Author 9},
    year={2023}
    }
    @article{t10,
    title={Title 10},
    author={Author 10},
    year={2023}
    }
    @article{t11,
    title={Title 11},
    author={Author 11},
    year={2023}
    }
    @article{t12,
    title={Title 12},
    author={Author 12},
    year={2023}
    }
    @article{t13,
    title={Title 13},
    author={Author 13},
    year={2023}
    }
    @article{t14,
    title={Title 14},
    author={Author 14},
    year={2023}
    }
    @article{t15,
    title={Title 15},
    author={Author 15},
    year={2023}
    }
    @article{t16,
    title={Title 16},
    author={Author 16},
    year={2023}
    }
    @article{t17,
    title={Title 17},
    author={Author 17},
    year={2023}
    }
    @article{t18,
    title={Title 18},
    author={Author 18},
    year={2023}
    }
    @article{t19,
    title={Title 19},
    author={Author 19},
    year={2023}
    }
    @article{t20,
    title={Title 20},
    author={Author 20},
    year={2023}
    }
    @article{t21,
    title={Title 21},
    author={Author 21},
    year={2023}
    }
    @article{t22,
    title={Title 22},
    author={Author 22},
    year={2023}
    }
    @article{t23,
    title={Title 23},
    author={Author 23},
    year={2023}
    }
    @article{t24,
    title={Title 24},
    author={Author 24},
    year={2023}
    }
    @article{t25,
    title={Title 25},
    author={Author 25},
    year={2023}
    }
    @article{t26,
    title={Title 26},
    author={Author 26},
    year={2023}
    }
    @article{t27,
    title={Title 27},
    author={Author 27},
    year={2023}
    }
    @article{t28,
    title={Title 28},
    author={Author 28},
    year={2023}
    }
    @article{t29,
    title={Title 29},
    author={Author 29},
    year={2023}
    }
    @article{t30,
    title={Title 30},
    author={Author 30},
    year={2023}
    }
    @article{t31,
    title={Title 31},
    author={Author 31},
    year={2023}
    }
    @article{t32,
    title={Title 32},
    author={Author 32},
    year={2023}
    }
    @article{t33,
    title={Title 33},
    author={Author 33},
    year={2023}
    }
    @article{t34,
    title={Title 34},
    author={Author 34},
    year={2023}
    }
    @article{t35,
    title={Title 35},
    author={Author 35},
    year={2023}
    }
    @article{t36,
    title={Title 36},
    author={Author 36},
    year={2023}
    }
    @article{t37,
    title={Title 37},
    author={Author 37},
    year={2023}
    }
    @article{t38,
    title={Title 38},
    author={Author 38},
    year={2023}
    }
    @article{t39,
    title={Title 39},
    author={Author 39},
    year={2023}
    }
    @article{t40,
    title={Title 40},
    author={Author 40},
    year={2023}
    }
    
</details>

`main.md`:

<details>

    ---
    title: minimal example title
    bibliography: [refs.bib]
    ---
    
    
    # Conclusion {#sec:conclusion}
    
    Lorem ipsum dolor sit amet consectetur adipiscing, elit leo sagittis quam commodo et vulputate, posuere quisque tincidunt phasellus a. Mauris parturient interdum arcu feugiat mus, turpis molestie nisi vitae ac semper, ullamcorper curae blandit erat. Natoque mollis facilisis interdum proin sed ut praesent primis fringilla facilisi diam potenti, eget litora sem euismod nunc cras malesuada condimentum habitant vel class.
    
    Imperdiet egestas lobortis turpis varius aenean dapibus natoque conubia mollis, rhoncus euismod risus vulputate mattis morbi blandit dictumst augue justo, leo nostra vehicula tempor posuere in cubilia non. Praesent metus eleifend ornare ligula habitasse cum morbi tortor montes felis placerat enim fermentum egestas in, erat aliquam justo sem auctor tempus mollis nisi fringilla orci sociis conubia dignissim. Purus ante mauris lacus nisl pulvinar per maecenas tristique porta morbi sollicitudin, dictum consequat tempus placerat blandit quis tellus facilisis felis parturient, fames netus aliquam ullamcorper auctor platea est proin cras sed. Torquent tortor volutpat conubia ligula sollicitudin tempor luctus, curabitur in nullam interdum nascetur risus consequat, est nibh suspendisse lectus tellus cum.
    
    Pellentesque lobortis quam neque at leo mi tristique nullam, ornare volutpat aliquam magna condimentum venenatis libero, eros aptent lacus massa ad habitant dapibus. Nibh fusce sociis vehicula pretium ridiculus netus et tincidunt, integer egestas sodales rutrum scelerisque donec penatibus hac himenaeos, nam tristique gravida laoreet rhoncus suspendisse magna. Iaculis tortor litora diam nulla erat viverra, vitae aptent fringilla torquent justo molestie, interdum nisl tempor quisque congue. Elementum cursus at penatibus mus sem est gravida blandit porttitor, porta viverra suspendisse eget diam vestibulum turpis justo, sociosqu risus conubia sodales tortor per aliquet aptent.
    
    Habitant faucibus primis et mus morbi luctus quis, non volutpat nullam eros mattis fringilla curae arcu, vestibulum gravida eu rutrum cras a. Etiam lobortis egestas nibh massa senectus at, torquent tempus dictumst quisque vulputate, quam eu malesuada integer nec. Est turpis dignissim eleifend bibendum varius etiam iaculis pulvinar, habitant sem aenean habitasse at scelerisque venenatis aliquet sollicitudin, pharetra leo viverra enim rutrum sagittis erat. Molestie vitae duis cras pellentesque eu cum donec, nostra aptent praesent justo pretium vehicula habitant morbi, conubia porttitor semper lectus scelerisque condimentum.
    
    Massa metus placerat purus at sodales erat viverra tristique, ut blandit inceptos gravida semper lobortis fermentum, platea tortor morbi augue maecenas sed sollicitudin. Gravida pellentesque tincidunt tortor felis interdum venenatis proin dictumst, lobortis aliquet auctor ullamcorper ante ad posuere, commodo vel curabitur purus suspendisse accumsan vitae. Leo penatibus metus vehicula pellentesque potenti, posuere est fermentum tellus rutrum, enim quis accumsan mus.
    
    @t1
    @t2
    @t3
    @t4
    @t5
    @t6
    @t7
    @t8
    @t9
    @t10
    @t11
    @t12
    @t13
    @t14
    @t15
    @t16
    @t17
    @t18
    @t19
    @t20
    @t21
    @t22
    @t23
    @t24
    @t25
    @t26
    @t27
    @t28
    @t29
    @t30
    @t31
    @t32
    @t33
    @t34
    @t35
    @t36
    @t37
    @t38
    @t39
    @t40
    
    
    # References {-}
    

</details>

Run pandoc in latest extra image:

        docker run \
            --rm \
            --volume "$(pwd)":/data \
            --entrypoint "" \
            docker.io/pandoc/extra:latest \
            pandoc \
            --filter "pandoc-crossref" \
            --citeproc \
            --variable "book" \
            --top-level-division "chapter" \
            --table-of-contents --standalone \
            --number-sections \
            --metadata="disable-header-and-footer" \
            --output "test.pdf" \
            main.md
    
![Screenshot from 2023-06-19 16-26-11](https://github.com/jgm/pandoc/assets/476060/96e0e564-8ccc-44ad-ba1e-19cdb507e5c4)

**Comment by jgm** [comment]
Is this the same as #1632?

**Comment by jgm** [comment]
See especially https://github.com/jgm/pandoc/issues/1632#issuecomment-1243917034 and the Lua filter @tarleb provides as a woraround.  If you agree with his proposed fix, maybe you could comment on that issue and we can close this one?

**Comment by tarleb** [comment]
Closing in favor of #1632.
