### ISSUE TITLE
Typo in 5e381e at openURL changes behaviour

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#8918]
While reviewing https://github.com/jgm/pandoc/commit/5e381e3878b5da87ee7542f7e51c3c1a7fd84b89, noticed the the replacement of `T.takeWhile, T.dropWhile`
by `break` changed the delimiter between mimetype and contents from `,` to `.`,
which doesn't appear to be the intent? Also, I see the call to `unEscapeString`
is dropped, but judging by the rest of the patch I assume it's unnecessary now
we use `parseURI`?

**Comment by jgm** [comment]
Closed by 54561e9a6667b36a8452b01d2def9e3642013dd6

Thanks for noticing that!

You're right that unEscapeString isn't needed, because parseURI unescapes the path.

**Comment by jgm** [comment]
> because parseURI unescapes the path.

Well, I thought it did, but experimentation shows that it doesn't!
