### ISSUE TITLE
Export from Google Docs (Docx) converts paragraphs to `<mark>`-elements inside of `<p>`-elements

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#8923]
# Pandoc version

## Pandoc 3.1.2 under macOS (M1)

```
pandoc 3.1.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/steve/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

## Pandoc 3.1.2 under macOS (M1)

```
pandoc 3.1.4
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/steve/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

## Examples and reproduction

Previously we created documents using Google Docs. We are using some filters and templating which you can see [here](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/src).

We are running it with:

```
pandoc -s --quiet --from=docx --to=html \
    --output=test/<test-dir>/none/expected.html --template=src/template.html \
    test/<test-dir>/input.docx
```

### Examples from _before_ Google Docs changed their export functionality

<table>
<thead>
<tr>
<th>Example input</th>
<th>Example output (using filters as defined above)</th>
</tr>
</thead>

<tbody>
<tr>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/NLDOC-570-230412-happy-flow-wm-google-docs">NLDOC-570-230412-happy-flow-wm-google-docs</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/NLDOC-570-230412-happy-flow-wm-google-docs/none/expected.html">NLDOC-570-230412-happy-flow-wm-google-docs/none/expected.html</a>
</td>
<tr>

<tr>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-all-headings-and-header-footer-texts">google-docs-all-headings-and-header-footer-texts</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-all-headings-and-header-footer-texts/none/expected.html">google-docs-all-headings-and-header-footer-texts/none/expected.html</a>
</td>
<tr>

<tr>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-all-headings">google-docs-all-headings</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-all-headings/none/expected.html">google-docs-all-headings/none/expected.html</a>
</td>
<tr>

<tr>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-footnote-summary-table-horizontal-line">google-docs-footnote-summary-table-horizontal-line</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-footnote-summary-table-horizontal-line/none/expected.html">google-docs-footnote-summary-table-horizontal-line/none/expected.html</a>
</td>
<tr>
</tbody>
</table>

### Examples from _after_ Google Docs changed their export functionality

<table>
<thead>
<tr>
<th>Example input</th>
<th>Example output (using filters as defined above)</th>
</tr>
</thead>

<tbody>
<tr>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-title-subtitle-headings-image-lists-docx">google-docs-title-subtitle-headings-image-lists-docx</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/d240d39c56cdfa5fcda2709327cdce69d40a4b9a/test/google-docs-title-subtitle-headings-image-lists-docx/none/expected.html">google-docs-title-subtitle-headings-image-lists-docx/none/expected.html</a>
</td>
<tr>

</tbody>
</table>

## Explanation on examples

As you can see, what was previously converted by Pandoc as only `<p>` elements, seem now to contain `<mark>` elements.

**Comment by StephanMeijer** [comment]
Also tested on:

```
pandoc 3.1.4
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/steve/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
I'm not sure I understand.
Are you saying that docx files produced by google docs now use w:mark instead of w:p?
That isn't the case in my tests.

**Comment by StephanMeijer** [comment]
Well, Pandoc generates `<mark>` elements with text paragraphs instead of generating `<p>` elements. This uses to be `<p>` and on old exports from Google Docs it still does `<p>`, so Google Docs changed their export structure.

**Comment by jgm** [comment]
Sorry, I'm not following at all.  You said "conversion *from* google docs."  I assume you were talking about a difficulty using pandoc to *read* the docx produced by Google Docs when you Download -> docx.

Now it seems that you're talking about something pandoc *produces*, and it sounds as if you're talking about HTML output.  So I have no idea what the issue is.

Please state the issue as clearly and explicitly as possible, with detailed instructions for reproducing it.

**Comment by StephanMeijer** [comment]
@jgm Worked out extra details.

**Comment by jgm** [comment]
Thanks.  I think you can still do more to help isolate the problem. You're using a bunch of filters; try removing them one by one.  If you can reproduce the issue without ANY filters, that's best. If the issue only arises when you're using a particular filter, it would be really helpful to know which.

**Comment by StephanMeijer** [comment]
@jgm Output is currently generated using both specific filters and all filters, tomorrow I will update with output using no filters at all.

**Comment by StephanMeijer** [comment]
@jgm Updated description with containing examples without filter usage.

**Comment by StephanMeijer** [comment]
I can see the `<mark>` tags being inside the `<p>`-tags now. Still strange though.

**Comment by jgm** [comment]
I see that 
```xml
<w:highlight w:val="white"/>
```
is now in the run text properties (w:rPr).  That is why this is happening.  I'm not sure why Google adds those.

**Comment by StephanMeijer** [comment]
The ony thing I can think of is it starting first being in _Pageless_ mode, then switching to A4. You can see the document here: https://docs.google.com/document/d/1SnFBwmKTXP8ROriGy1LynX6PJDXoxfzxBNRRTCjIKww/edit?usp=sharing

**Comment by StephanMeijer** [comment]
<img width="285" alt="image" src="https://github.com/jgm/pandoc/assets/3169264/580d2cc5-8ccd-4c56-9901-b267167b2336">
I ineed see white markings. I don't know why this is added. This mystery is solved, so it seems.
