### ISSUE TITLE
Documentation needed: A simple example for a Pandoc Lua filter (plugin) processing Code Blocks?

### ISSUE THREAD

**Issue by sdbbs** [jgm/pandoc#8932]
Basically, I have seen this: https://github.com/jgm/pandoc/issues/656#issuecomment-20916488

> The general pattern for plugins, literate programming and reproducible research is to embed it in code sections with [fenced code blocks](http://johnmacfarlane.net/pandoc/README.html#fenced-code-blocks) attributes:
> 
> ````
> ```{.foo <options>}
> <body>
> ```
> ````
> 
> If `foo` (the name of the first class) is a known plugin, then options and body are passed to the plugin and the result is used by Pandoc. WIth Pandoc extension `inline_code_attributes` one can also use it inline. For instance one could use a plugin that includes othr markdown files:
> 
> ```
> `chapter1.md`{.include}
> ```
> 

I was wondering whether there was an existing Pandoc plugin/filter for this, and it turns out, there is - https://pandoc.org/lua-filters.html#converting-abc-code-to-music-notation

But then, I'm trying to make a simple example - and I cannot.

By analogy with above, I have this as `mdinclude.lua`:

```lua
print("mdinclude")

function CodeBlock(block)
  print("CodeBlock")
  if block.classes[1] == "mdinclude" then
    local path_to_include = block.text
    print("mdinclude path_to_include", path_to_include)
    return pandoc.Para{ {pandoc.Str("mdinclude")} }
  end
end
```

... and I have this as `test.md`:

````md
# hello

hello

```{.mdinclude options}
included.md
```
````

And. I run `pandoc` like this:

```none
$ pandoc --version
pandoc.exe 2.13 ...

$ pandoc --lua-filter=mdinclude.lua --from markdown+fenced_code_attributes+inline_code_attributes --toc test.md -o test.pdf
mdinclude
```

... as you can see in the terminal output, the Lua filter never even got to `function CodeBlock` to print `print("CodeBlock")`??!

It took me two goddamn hours to figure out that somehow `{.mdinclude options}` breaks the Lua filter, and the only things that works is JUST `{.mdinclude}` with no spaces inside; so this `test.md`

````md
# hello

hello

```{.mdinclude}
included.md
```
````

... results with:

```none
$ pandoc --lua-filter=mdinclude.lua --from markdown+fenced_code_attributes+inline_code_attributes --toc test.md -o test.pdf
mdinclude
CodeBlock
mdinclude path_to_include       included.md
```

And yet, when I open the PDF, it just has this:

![image](https://github.com/jgm/pandoc/assets/48317456/955e4839-f7e2-4a83-8a07-6eb0d4101717)

... I would have expected the word "mdinclude" to appear there (due to `return pandoc.Para{ {pandoc.Str("mdinclude")} }`)???!

So, can somebody please make an example of a Lua filter like this, that can transform code blocks in the context of "embed it in code sections with attributes":

* with exact .lua filter file
* with exact input .md file
* with exact `pandoc` command line that should be called
* with an expected PDF output

I would have loved to have made this example myself and not bothered developers, but I guess the documentation is already too complex, so finding the right stuff to make this work is difficult - and even it seems there are conflicting suggestions (i.e. use `{.foo <options>}` when it in fact breaks a Lua filter script)

**Comment by sdbbs** [comment]
OK, got it, finally:

`mdinclude.lua`

```lua
-- NOTE: must ONLY use ```{.mdinclude} for now to open code block; not ```{.mdinclude options} !!

local function read_file(path) -- https://stackoverflow.com/a/31857671/6197439
    local file = io.open(path, "rb") -- r read mode and b binary mode
    if not file then return nil end
    local content = file:read "*a" -- *a or *all reads the whole file
    file:close()
    return content
end


---------------------- MAIN ----

--~ print("mdinclude") -- ok

function CodeBlock(block)
  --print("CodeBlock")
  if block.classes[1] == "mdinclude" then
    local path_to_include = block.text
    print(string.format("mdinclude '%s'", path_to_include))
    local fileContent_str = read_file(path_to_include);
    local parsed_file = pandoc.read(fileContent_str)
    --print(fileContent_str)
    -- NOTE: MUST return .blocks here, to have the read file show up in output document!
    return parsed_file.blocks
  end
end
```

`test.md`

````md
# hello

hello

```{.mdinclude}
included.md
```
````

`included.md`

````md

From here on, we do some including ..

## Hello include

some inclusion stuff here ...

all done ...

````

Command line:

    pandoc --lua-filter=mdinclude.lua --from markdown+fenced_code_attributes+inline_code_attributes --toc test.md -o test.pdf

PDF output - shows the `included.md` is included as intended:

![image](https://github.com/jgm/pandoc/assets/48317456/62eda07e-7d8f-4d27-9cad-55a0486765f4)

.... though, it would be nice, if one could also read `{.foo <options>}`

**Comment by cagix** [comment]
> NOTE: must ONLY use `{.mdinclude}` for now to open code block; not `{.mdinclude options}`

Did you try something like `block.classes:includes 'mdinclude'` instead of `block.classes[1] == "mdinclude"`?
