### ISSUE TITLE
dead cross bookmark reference when convert from Latex to docx

### ISSUE THREAD

**Issue by wohenbushuang** [jgm/pandoc#8935]
**Explain the problem.**

Latex sample `pandoc.tex`: 
```latex
\documentclass[a4]{article}

\begin{document}

Dummy text here: 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu dolor a est placerat efficitur eu vestibulum tellus. Praesent eget augue at elit rhoncus semper. Curabitur hendrerit cursus maximus. Maecenas egestas tincidunt dolor, quis congue mauris faucibus nec. Phasellus quis velit at nisi laoreet consectetur.

Fig.~\ref{fig1}

Table.~\ref{tbl1}

Eq.~\eqref{eq1} (use \texttt{\textbackslash eqref}) or Eq.~\ref{eq1} (use \texttt{\textbackslash ref})

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{table}[htbp]
  \caption{The table 1.}\label{tbl1}
  \begin{tabular*}{\tblwidth}{lll}
    1 & 2 & 3 \\ % Table header row
    1 & A & B \\
    2 & A & B \\
    3 & A & B \\
  \end{tabular*}
\end{table}

\begin{figure}
  \includegraphics{https://pandoc.org/pandoc-cartoon.svgz}
  \caption{The figure 1.}
  \label{fig1}
\end{figure}

\begin{equation}
  \label{eq1}
  1+1=2
\end{equation}

\end{document}
```

Convert the Latex file to docx file and open it with MS Word.
The `Fig. 1` link is dead, and the cursor will go to the top of the document. Hover mouse on it and will show the link as `#fig1`.
The `Table 1` link works fine and will go to the table caption. Hover mouse on it and will show the link as `#tbl1`.

Furthermore, in MS Word `Referrence -> Citation -> Cross-reference` panel

* If use `pandoc pandoc.tex -o pandoc.docx`:
There is only `tbl1` in `bookmark` type.

![image](https://github.com/jgm/pandoc/assets/15613184/9db8413c-348e-4428-9318-f60e0ff606d7)

No item in `Figure` type.

![image](https://github.com/jgm/pandoc/assets/15613184/40c71ba5-4ebc-441d-bbb1-b857c126d23b)

* If use `pandoc pandoc.tex -o pandoc.docx -t docx+native_numbering`:
There are `ref_fig1`, `table1` and `tbl1` three items in `bookmark` type.

![image](https://github.com/jgm/pandoc/assets/15613184/055a20ac-c145-428a-9800-23447f35b3d2)

One `Figure1: The figure 1.` in `Figure` type.

![image](https://github.com/jgm/pandoc/assets/15613184/cde3ec75-2e54-4036-85b3-5833b1c15bc8)

---

BTW, I'm wondering how to refer equations, since they don't (and cannot) have captions?
![image](https://github.com/jgm/pandoc/assets/15613184/ce2547e4-1b5d-486a-b52c-5a6c007795b2)

**Pandoc version?**
Windows
```
pandoc 3.1.4
Features: +server +lua
Scripting engine: Lua 5.4
```

**Comment by jgm** [comment]
This is essentially the same as #8862 and has been fixed
