### ISSUE TITLE
Markdown: `e. g.` in a list parses as another item 

### ISSUE THREAD

**Issue by Bodigrim** [jgm/pandoc#8943]
**Explain the problem.**

Save this as `pandoc.md`:
```markdown
* Do something,
  e. g., this or that.
```

Run 
```html
$ pandoc -f markdown -t html pandoc.md
<ul>
<li>Do something,
<ol start="5" type="a">
<li>g., this or that</li>
</ol></li>
</ul>
```

The expected output is 
```html
<ul>
<li>Do something, e. g., this or that</li>
</ul>
```

Seems related to #8616, but in other direction.

**Pandoc version?**

Pandoc 3.1.4, also reproducible at https://pandoc.org/try/.

**Comment by jgm** [comment]
This is because `e.` is a valid list start marker.
The solution is to escape `e\. g.`

**Comment by jgm** [comment]
In any case, not a bug...
