### ISSUE TITLE
Gutters on margin specs not picked up from custom-reference.docx (HTML to .docx)

### ISSUE THREAD

**Issue by CompuJon** [jgm/pandoc#8946]
**Background:** The customer-reference.docx file is available to use as a style reference in producing a docx or ODT file. The PanDoc manual states: "The contents of the reference docx are ignored, but its stylesheets and document properties (including margins, page size, header, and footer) are used in the new docx. "

**The problem:** All style information and margins (margins are in MS Word's Page Setup) are indeed used for the docx file that is produced by Pandoc using the following command line:

`pandoc -o "GutterBug.docx" "GutterBug.html" --reference-doc=custom-reference.docx`

_However,_ the Gutter specification is not being carried over and is ignored.

**Why does this matter?** The "Gutter" specification provides an extra margin to allow for binding the document. The **Mirror margins** option in the **Page Setup** sets the Gutter to be on the left-hand side of odd-numbered pages and on the right-hand side of even-numbered pages.

In MS Word (latest versions in Microsoft Office 365), page margins are specified by selecting Layout/Margins/Custom Margins.

The following files are attached to reproduce the problem:

- Gutterbug.txt: A simple html to be converted into a .docx file. Change the filetype from .txt to .html (this reporting page would not let me attach an html file)
- Gutterbug.docx: The resulting MS Word .docx file. Check the Layout/Margins/Custom Margins in MS Word to see the **Page Setup** dialog box. A screen shot of that is also included (described below)
- custom-reference.docx: The MS Word file with the styles and margins customized. Again, check the Layout/Margins/Custom Margins in MS Word to see the **Page Setup** dialog box. A screen shot of that is also included (described below)
- Margins-in-custom-reference.jpeg: The Page Setup pop-up in the customized custom-reference.docx file. Note that the Gutter is set to 0.25 inches, and the option for **Multiple pages** is set to **Mirror margins**.
- Margins-in-Gutterbug-docx.jpeg: The Page Setup pop-up in the resulting Gutterbug.docx file. Note that the Gutter is set to 0.25 inches (this part works), but the option for **Multiple pages** is set to **Normal**. THIS IS THE BUG! The setting should be carried over into the resulting .docx file.

**Pandoc Version 3.1.4** on Windows 11 (all Windows updates are current).

[GutterBug.txt](https://github.com/jgm/pandoc/files/11996542/GutterBug.txt)
[GutterBug.docx](https://github.com/jgm/pandoc/files/11996546/GutterBug.docx)
[custom-reference.docx](https://github.com/jgm/pandoc/files/11996551/custom-reference.docx)
![Margins-in-custom-reference](https://github.com/jgm/pandoc/assets/139082002/656cfeaf-01e4-421b-8100-936930ba943c)
![Margins-in-GutterBug-docx](https://github.com/jgm/pandoc/assets/139082002/95af96b1-865f-4068-8da6-52859bc78061)

**Comment by jgm** [comment]
settings.xml in the reference docx has
```
<w:mirrorMargins/>
```
as a child of `w:settings`. That's not one of the settings we currently carry over, but I can change that easily.
