### ISSUE TITLE
Unnecessary lossy writing of LineBlock with --wrap=none in HTML

### ISSUE THREAD

**Issue by Dabsunter** [jgm/pandoc#8952]
## The problem

I don't really get why `--wrap=none` have an influence on HTML output of LineBlock

https://github.com/jgm/pandoc/blob/29c5afb305c32129db4e81cd489cd3bd2a14c2e9/src/Text/Pandoc/Writers/HTML.hs#L753-L758

As the documentation state, `--wrap` should *determine how text is wrapped in the output (the source code, not the rendered version)* ([source](https://pandoc.org/MANUAL.html#option--wrap)), but the upper code make a harmful distinction by not always writing a `<div class="line-block">`. That indeed prevent both CSS styling and Pandoc reader to correctly reconstruct a LineBlock in its AST from its own output, which is IMO not the intended effect of `--wrap`.

## Quick example

    dabs@david-popbook:~$ pandoc
    | line 
    | block
    <div class="line-block">line<br />
    block</div>

    dabs@david-popbook:~$ pandoc --wrap=none
    | line           
    | block
    <p>line<br />
    block</p>

    dabs@david-popbook:~$ pandoc | pandoc -fhtml -tnative
    | line
    | block
    [ LineBlock [ [ Str "line" ] , [ Str "block" ] ] ]

    dabs@david-popbook:~$ pandoc --wrap=none | pandoc -fhtml -tnative
    | line
    | block
    [ Para [ Str "line" , LineBreak , Str "block" ] ]

    dabs@david-popbook:~$ pandoc --version
    pandoc 3.1.4

**Comment by jgm** [comment]
Agreed, that's a bug, been there since 2016!
