### ISSUE TITLE
converting .docx to html skips some image numbers

### ISSUE THREAD

**Issue by KaptenLutman** [jgm/pandoc#8953]
I'm authoring docx files with Microsoft® Word for 365 MSO Version 2306 Build 16.0.16529.20100 32-bit on Windows 10 Pro 22H2 build 19045.3086 and would like to convert them to html using pandoc. The docx files have svg images (named `image<n>.svg`) imported into the upper row 1x2 tables (the second row is for the figure caption). Upon launching pandoc, the `.svg` images are converted to `image<n>.png` and stored in the `media` folder. I then replace the `.png` images with the original `.svg` images and do a global search and replace for `.png` to `.svg` in the html output file. However, some image numbers `<n>` are skipped by pandoc so I have to manually go through the HTML output and correct them. I'm using the following command in Windows and nothing is generated in the `log.txt` file except `[]`:
pandoc -s -t html5 -o output.html --log=log.txt -f docx+native_numbering+styles --verbose --css styles.css --mathjax --metadata title="METADATA" --metadata lang=en-UK input.docx

Pandoc v 3.1.5 on Windows

**Comment by jgm** [comment]
Would be handy to have a docx to test with.

**Comment by KaptenLutman** [comment]
My file is confidential so I replaced the text and figures with dummy content in the same format (JPG, SVG) and anonymized the file. Running the command above on this file resulted in different problems:
1. Only the first two figures are referenced in the html file and the numbering stays at 2 for figures after Fig.2.
2. Figure and section numbers are no longer rendered
3. Some non-italic math is rendered as italics in Mathjax (table entries). This was the case also before anonymization
[input.docx](https://github.com/jgm/pandoc/files/12048632/input.docx)

**Comment by jgm** [comment]
The numbers are represented in the docx as
```xml
            <w:fldSimple w:instr=" SEQ Figure \* ARABIC">
```
and pandoc doesn't (yet) attempt to resolve these calculated fields. 

> Only the first two figures are referenced in the html file and the numbering stays at 2 for figures after Fig.2.

I don't know what you're referring to here.  In the HTML I produce, I'm seeing references to Figure 3, Figure 4, etc., up to 7.

> Some non-italic math is rendered as italics in Mathjax (table entries).

There are some differences of opinion between Word and other renderers regarding the default font to use for math identifiers.

**Comment by KaptenLutman** [comment]
Well, here's the html output that I got (zipped because github doesn't accept uploading of html files. I manually added the following line after `</head>`:
`<link href='fonts/fonts.css' rel='stylesheet' type='text/css'>`
[output.zip](https://github.com/jgm/pandoc/files/12060019/output.zip)

In another docx2html conversion, figure numbers (`<chapter>.<number>`) were successfully rendered from fields like `{ STYLEREF 1 \s }.{ SEQ Figure \* ARABIC \s 1 }` but other numbered items, such as sections, were not. Until pandoc resolves calculated fields a workaround could be to define SEQ variables also for section headers.

**Comment by KaptenLutman** [comment]
Updated to v3.1.9 and Word's Figure numbering works now, provided that figures are pasted in the upper row of an 1x2 table and the caption moved to the lower row. Numbers are missing if just using Word's Insert Caption command without table. Although all figures are visible in the HTML output, the numbering of the actual files is strange. I have a document with 10 figures but the files are numbered 2,4,6,8,10,12,13,14,15,16. SVG is correctly copied now (not converted to PNG) - thanks for fixing this.

**Comment by KaptenLutman** [comment]
Since SVG figures are correctly copied to the media folder, this is no longer an issue. Even though the figure files are numbered wrongly, the links work and they are correctly numbered in the html rendering.
