### ISSUE TITLE
illegal instruction Win7 since 3.1.4

### ISSUE THREAD

**Issue by tigros** [jgm/pandoc#8955]
Hi,

The instruction is vmovdqa64 zmm0,zmmword ptr...

I guess some compile change?

**Comment by jgm** [comment]
Likely related to #8947

**Comment by jgm** [comment]
This is also an AVX instruction.

**Comment by jgm** [comment]
Did you try 3.1.3?  The other issue reported the problem for that version too. Pinning down the exact version range affected might help.

**Comment by jgm** [comment]
Ah, I wouldn't expect a version match necessarily, as the Windows releases are built with stack and use a different compiler and library versions.

stack.yaml changes possibly affecting the 3.1.4 build (but not 3.1.3):
June 22: move to crypton ecosystem
June 21: move to lts-21.0 for stack (ghc 9.4)

**Comment by tigros** [comment]
it's not the first time i've seen this sort of problem, they check the cpu ok but not windows version doh! and yes 3.1.3 works fine.

**Comment by jgm** [comment]
I've built a version of the pandoc 3.1.5 release using ghc 9.2.  Can you try it and see if you still get this issue?
See artifacts at
https://github.com/jgm/pandoc/actions/runs/5591572823

**Comment by tigros** [comment]
tested on a 460 MB epub and worked fine, thanks for all the effort!

**Comment by jgm** [comment]
Great!
