### ISSUE TITLE
crash when redirect input/output C#

### ISSUE THREAD

**Issue by tigros** [jgm/pandoc#8959]
Hi,

This isn't urgent or anything, since all I have to do is remove the 2 lines.

But it seems pandoc can crash when either RedirectStandardOutput or RedirectStandardInput is set to true.

It crashes with exit code 1 if anything is written to the console, fine if nothing written. 

The output file is not created.

Here's some sample C# code:

    Process pandocproc = new Process();
    pandocproc.StartInfo.FileName = "pandoc.exe";
    string embed = "";
    if (Path.GetExtension(fileName).ToUpper() == ".EPUB")
        embed = "--standalone --embed-resources ";
    pandocproc.StartInfo.Arguments = embed + "-o \"" + outfile + "\" \"" + fileName + "\"";
    pandocproc.StartInfo.RedirectStandardInput = true;    // this
    pandocproc.StartInfo.RedirectStandardOutput = true;   // and this
    pandocproc.StartInfo.UseShellExecute = false;
    pandocproc.StartInfo.CreateNoWindow = true;
    pandocproc.Start();
    pandocproc.WaitForExit();

Usually I set those just from copy/paste, sometimes I do need the output or even input, but not for pandoc.	

I've never had a program crash because of that, but i won't be copy pasting those 2 anymore!

I just tested on Windows 10 and it's fine, so only Windows 7 so far, even less urgent then..

**Comment by jgm** [comment]
Can you redirect stdin and stdout on the command line with `<` and `>`?

**Comment by tigros** [comment]
it doesn't crash but output is on the screen, the file is 0 bytes. Same on windows 10.

**Comment by jgm** [comment]
So if you do
```
pandoc > out.html < in.md
```
it will output to the screen?
(I'm assuming this kind of redirection is normally possible in Windows, which I don't use at all.)

**Comment by tigros** [comment]
Just realized the problem is related to .Net Reactor, a C# obfuscator, if run without it the 2 lines are ok.

Also when I tested yesterday I was just redirecting the output no input redirect, turns out the warnings are going to stderr, which is good, but to redirect them you have to use 2>.

Closed. thanks alot!
