### ISSUE TITLE
Markdown highlighting with ==text== not working for odt

### ISSUE THREAD

**Issue by Ratramnus** [jgm/pandoc#8960]
If I have a markdown file (test.md) with the following:

> This is a ==test==.

And then use:

`pandoc test.md -f markdown+mark -t odt -o test.odt`

The text "test" is not highlighted in test.odt.

(I'm using pandoc 3.1 on MacOS Ventura 13.4.1)

**Comment by jgm** [comment]
OpenDocument writer would need to be changed to handle
```
Span ( "" , [ "mark" ] , [] ) ils
```
by adding highlighting.

**Comment by Ratramnus** [comment]
Thank you for your response. Given my sheer ignorance, are you saying that at the moment pandoc doesn't handle "mark" highlighting for odt files?

**Comment by jgm** [comment]
Correct. I suspect the fix wolud not be too difficult. It requires looking up syntax for highlighting in OpenDocument format and adding a few lines to the OpenDocument writer.

**Comment by jgm** [comment]
Looks like LibreOffice uses a temporary style like this:
```xml
  <style:style style:name="T1" style:family="text">
   <style:text-properties fo:background-color="#ffff38" loext:char-shading-value="0"/>
  </style:style>
```
then in the body
```xml
     <text:p text:style-name="P1">Hi <text:span text:style-name="T1">there</text:span></text:p>
```
