### ISSUE TITLE
Cannot process image filename with special characters in wrong locale: "File ... not found in resource path"

### ISSUE THREAD

**Issue by sumpfralle** [jgm/pandoc#8961]
# How to reproduce

1. `echo '![](FooBär.png)' >with_umlauts.md`
1. `touch FooBär.png`
1. Processing with German locales works:
    ```shell
    $ LANG=de_DE.UTF-8 pandoc --quiet --self-contained with_umlauts.md >/dev/null
    ```
1. Processing with neutral locales fails:
    ```shell
    $ LANG= pandoc --quiet --self-contained with_umlauts.md >/dev/null
    File FooBär.png not found in resource path
    ```

According to `strace` it appears that `pandoc` does not even try to access the file. Thus, probably it just refuses to process the filename due to its special characters (while a neutral locale is active).

According to pandoc's manpage all inputs are expected to be `utf-8`. Thus, I would expect that the filename can be processed (independent of the current locale).

# Environment
```shell
$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
```

Running on Debian Bookworm (`amd64`).

Thank you for your time!

**Comment by jgm** [comment]
This is an ancient version of pandoc. I can't reproduce the issue on my system with the latest release.

**Comment by sumpfralle** [comment]
I tried it again with a more recent version of pandoc (v2.17) and it fails for me:
```
[temp]:/tmp/cdt-A6vuAi# echo '![](FooBär.png)' >with_umlauts.md
[temp]:/tmp/cdt-A6vuAi# touch FooBär.png
[temp]:/tmp/cdt-A6vuAi# LANG=de_DE.UTF-8 pandoc --quiet --self-contained with_umlauts.md >/dev/null
[temp]:/tmp/cdt-A6vuAi# LANG= pandoc --quiet --self-contained with_umlauts.md >/dev/null
File FooBär.png not found in resource path
[temp]:/tmp/cdt-A6vuAi# pandoc --version
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.2.1, texmath 0.12.4, skylighting 0.12.3.1,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/lars/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Maybe your environment differs from mine. What could it be?

**Comment by jgm** [comment]
Your "more recent" version is not the latest release (3.1.6.1). Try with that before reporting...after all, this was just fixed 3 weeks ago.
