### ISSUE TITLE
Add Supported PDF-Engine: texliveonfly

### ISSUE THREAD

**Issue by cochaviz** [jgm/pandoc#8962]
Currently, pandoc supports numerous PDF engines (pdflatex, luatex, etc.) to convert `.tex` documents to PDF. I would like to propose we add [texliveonfly](https://www.ctan.org/pkg/texliveonfly) to this list of supported engines. Apparently I'm not the first one to propose this idea (<https://groups.google.com/g/pandoc-discuss/c/X6JtBATTp18/m/yAqB1a-YBAAJ>), but there have not been any responses to the mentioned post. I could not find any other mentions of `texliveonly` in either the open or closed questions on GitHub.

### The idea

In short, texliveonfly is a wrapper for all the trusted pdf engines (that are already supported by pandoc) that installs missing packages on the fly. I understand that this is done by reading the output of the _actual_ pdf engine and searching the packages using `tlmgr`. 

Currently, pandoc awesomely provides some containerized versions of their software including the `pandoc-crossref` filter (<https://hub.docker.com/r/pandoc/latex> and <https://hub.docker.com/r/pandoc/extra>) which includes some, but not all possibly required latex packages. In line with this containerized workflow, it would be nice to be able to install packages  _on-the-fly_ to avoid bloating the Docker image.

This would not only make significant QoL improvements to anyone using these containers to build documents using pandoc, but it also means only the minimal latex image is necessary.

### Considerations

When running `tlmgr` to download `texliveonfly`, Fedora gave me some warnings that I should not directly use `tlmgr` to manage my packages. Therefore, I downloaded the file manually (<https://www.ctan.org/pkg/texliveonfly>) which worked nicely. Running the script itself did not give any warnings on either my Fedora machine, or the ubuntu-based docker container.

To be able to run the _script_, that is the python file that I downloaded manually, on the ubuntu docker container, I needed to change the `python` invocation in the shebang to `python3`. I modified the `pandoc/extra` docker container as such:

```Dockerfile
FROM pandoc/extra:latest-ubuntu

# packages for devcontainer
RUN apt-get update 
RUN apt-get install -y unzip

# install texliveonfly
RUN wget https://mirrors.ctan.org/support/texliveonfly.zip
RUN unzip texliveonfly.zip
RUN sed -i ' 1 s/python.*/python3/' texliveonfly/texliveonfly.py
RUN chmod +x texliveonfly/texliveonfly.py 
RUN mv texliveonfly/texliveonfly.py /usr/bin/texliveonfly
```

I have not yet tried using the `tlmgr` package to install `texliveonfly` on the docker container, but I will try to find a solution using tomorrow. 

> EDIT: Using `tlmgr`, the texliveonfly package can be downloaded without a problem. The `python` problem, however, still remains. 

> EDIT: Using the ubuntu package `python-is-python3`, the remaining problem can be resolved.

### Alternatives

From what I have considered, there  are two alternatives:

1. _Do not use on-the-fly installation of packages._ Personally, I use publisher templates quite a lot (`acmart`, `elsarticle`, etc.) and I work on different types of problems every month (the joy of being a student), meaning that often need different packages. While I could just install the `texlive-full` package (which I currently do), having to do this in a Docker container each time I need to rebuild it (for whatever reason) takes quite a lot of time.

2. _Use a custom wrapper to work with texliveonfly_. While this would most definitely work (actually, it already does because this is my current solution), I think having this supported by default in the provided docker containers would make an incredible improvement to QoL. It is in no way a _must_, but given the apparent easy of implementation and maintenance (I am absolutely _no_ haskell programmer, so please correct me if I'm wrong) it might be worth it.

**Comment by cochaviz** [comment]
If anyone is curious, this is my current workaround. I have made a wrapper for `texliveonfly` called `pandoc-texliveonfly.py`:

```Python
#!/usr/bin/env python3

import sys
import subprocess
import glob

def _set_extension_tex(filename: str) -> str:
    return ".".join(filename.split('.')[:-1] + ["tex"])

def _get_opt_value(option: str) -> str:
    try:
        return sys.argv[sys.argv.index(option) + 1]
    except ValueError:
        return ""

def _set_opt_value(option: str, value: str) -> list[str]:
    args = sys.argv
    args[args.index(option) + 1] = value
    return args

if __name__=="__main__":
    is_pdf = True

    if _get_opt_value("-t") == "pdf":
        argv =  _set_opt_value("-t", "tex")
        subprocess.run(["pandoc", "-s", *argv[1:]]) 
    elif ".pdf" in _get_opt_value("-o"):
        new_filename = _set_extension_tex(_get_opt_value("-o"))
        argv = _set_opt_value("-o", new_filename)
        print(argv)
        subprocess.run(["pandoc", "-s", *argv[1:]])
    elif ".pdf" in sys.argv[-1]:
        new_filename = _set_extension_tex(sys.argv[-1])
        subprocess.run(["pandoc", "-s", *sys.argv[1:-1], new_filename])
    else:
        is_pdf = False

    if is_pdf:
        subprocess.run(["texliveonfly", *glob.glob("*.tex")])
    else:
        subprocess.run(["pandoc", *sys.argv[1:]])
```

And a Dockerfile that is as follows:

```Dockerfile
FROM pandoc/extra:latest-ubuntu

# packages for devcontainer
RUN apt-get update 
RUN apt-get install -y python-is-python3

# install texliveonfly
RUN tlmgr install texliveonfly

# install wrapper for texliveonfly
COPY pandoc-texliveonfly.py /usr/bin/
RUN chmod +x /usr/bin/pandoc-texliveonfly.py

ENTRYPOINT [ "pandoc-texliveonfly.py" ]
```

**Comment by alerque** [comment]
How is `texliveonfly` different or better than `tectonic`?

c.f. https://github.com/pandoc/dockerfiles/issues/87

**Comment by cochaviz** [comment]
Now that I know about `tectonic`, in absolutely no way shape or form 😅 Thanks for letting me know about this progam! Will close this issue as my proposal is, indeed, redundant given this tool.
