### ISSUE TITLE
Markdown-in-HTML-in-Markdown produces invalid and undesirable HTML output with certain line break patterns inside `p` elements

### ISSUE THREAD

**Issue by squ1dd13** [jgm/pandoc#8963]
Hi. I've been really enjoying using pandoc – it's a fantastic piece of software. Thank you John and all the rest of you who've worked on it!

I've come across a problem with pandoc's handling of HTML within Markdown. To be more precise, the issue appears to be in pandoc's handling of Markdown in HTML *in Markdown*.

I'll demonstrate first.

Minimal example ([link](https://pandoc.org/try/?params=%7B%22text%22%3A%22%3Cp+style%3D%5C%22color%3A+green%3B%5C%22%3EThis+works+fine.%3C%2Fp%3E%5Cn%5Cn%3Cp+style%3D%5C%22color%3A+green%3B%5C%22%3ESo+does+this.%5Cn%3C%2Fp%3E%5Cn%5Cn%3Cp+style%3D%5C%22color%3A+green%3B%5C%22%3E%5CnAnd+this.%5Cn%3C%2Fp%3E%5Cn%5Cn%3Cp+style%3D%5C%22color%3A+green%3B%5C%22%3E%5Cn%5CnAnd+even+this.%5Cn%3C%2Fp%3E%5Cn%5Cn%3Cp+style%3D%5C%22color%3A+green%3B%5C%22%3E%5CnBut+this+doesn%27t.%5Cn%5Cn%3C%2Fp%3E%5Cn%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)):

```md
<p style="color: green;">This works fine.</p>
<p style="color: green;">So does this.
</p>
<p style="color: green;">
And this.
</p>
<p style="color: green;">

And even this.
</p>
<p style="color: green;">
But this doesn't.

</p>
```

Processing the above using

```sh
pandoc /tmp/bug.md -o /tmp/bug.html
```

and then viewing `bug.html` in a browser (Firefox in this case, but the same occurs in Chrome) yields this:

<img src="https://github.com/jgm/pandoc/assets/31861012/fb95d7b9-9682-405f-8609-3e77d47c53bc" width=50%>
<br><br>

The reason it doesn't work is because pandoc's output includes nested paragraph elements, which is [illegal](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1). The typical browser behaviour, as tested with Firefox and Chrome, appears to be to force the outer `p` to close by inserting a `</p>` before the opening inner `<p>`. The (now orphaned) outer `</p>` is then forcibly paired with a new `<p>` to produce valid HTML that can be rendered.

Specifically, for the last `p` in the example, pandoc wraps the inner text in `<p>...</p>`, and by the above procedure (or something which has the same effect as the above), that new `p` element ends up outside the styled `p`, so the final text does not have the green colour.*

Pandoc's output for the final block is this:

```html
<p style="color: green;">
<p>But this doesn’t.</p>
</p>
```

As this can't be rendered, what we actually see in a browser is this (copied from Firefox):

```html
<p style="color: green;">
</p>
<p>But this doesn’t.</p>
<p></p>
```

This appears to be a result of pandoc trying to interpret the inner text as Markdown: if we run exactly the same command but with `-f markdown-markdown_in_html_blocks`, we get the desired result:

<img src="https://github.com/jgm/pandoc/assets/31861012/5470a605-9a47-48d7-9037-edd448a00747" width=50%>
<br><br>

However, this is very limiting and is obviously not ideal.

I don't really know what the ideal behaviour would be, because there doesn't seem to be a solution that will work well in all cases. Disallow paragraph breaks inside `p`, perhaps? It might be annoying but it would prevent users from getting weird and confusing output. Besides, **full Markdown support isn't realistic inside `p` because it doesn't actually make sense** – arbitrary Markdown could have any number of paragraphs, but putting all that inside `p` is invalid. I'm not sure if there actually is a fix that would satisfy the hope that

> conversions from pandoc’s Markdown to all formats aspire to be perfect.

In the minimal example I provided, the issue wouldn't be present if pandoc wasn't trying to insert a paragraph in the last case – in other words, if all the cases were treated like the first few, that example wouldn't suffer from this issue. However, the wider and more fundamental issue would still remain, even if that example was fixed.

In my specific scenario (within my project), if I was writing the document by hand, I could just "fix" the spacing before giving it to pandoc. Unfortunately I'm not in control of what's being put into the HTML so I can't modify it (and the text I have coming in is Markdown, so I can't disable `markdown_in_html_blocks`).

*The same thing occurs without the inline CSS, but the result is less obvious (which is why I've used it for the primary examples). For various reasons this is still very problematic though. A simple case would be if I set vertical padding on all `p` elements using a style sheet (not inline):

<img src="https://github.com/jgm/pandoc/assets/31861012/8589e778-090a-4ec0-b90a-19bd1fb24fa3" width=30%>
<br>

Thus the extra `p` elements that result from the browser "fixing" pandoc's HTML are in themselves harmful.

### System details

```
pandoc 3.1.2
Features: +server +lua
Scripting engine: Lua 5.4
```

Note that the online demo I linked runs on 3.1.6, so this issue is present in both.

```
Manjaro Linux x86_64
5.15.120-1-MANJARO
```

Thanks

:)

**Comment by jgm** [comment]
I think pandoc is doing just what it's documented to do here.  It's interpreting what's between `<p>` and `</p>` as markdown.  When you have a blank line, it starts a new paragraph.  The raw HTML is opaque -- so pandoc doesn't distinguish one raw HTML tag (`<p>`) from another (e.g. `<div>`).

Note that we make no guarantees about emitting valid HTML when the user includes raw HTML.
