### ISSUE TITLE
auto download arm64 arch of MacOS but my computer is intel chip

### ISSUE THREAD

**Issue by rainydew** [jgm/pandoc#8964]
my computer: macbookPro 2019 (16inch), intel x86-64 chip
when i download pandoc via the green download button in official page, i found it download arm64 version automanticaly (cause failure to install)

expect result: download x86-64 version or let user to choose

**Comment by jgm** [comment]
Thanks - We can't autodetect this so I've just removed the OS detection feature and the button takes you to the GitHub releases page for the latest version.
