### ISSUE TITLE
chunkedhtml: --mathjax is not working properly

### ISSUE THREAD

**Issue by wolfganghammer** [jgm/pandoc#8967]
**Explain the problem.**
`pandoc -t chunkedhtml --mathjax` does not enable MathJax reliably in all chunks.

**Exact command:**
```
pandoc -t chunkedhtml -s --mathjax -o MathTest MathTest.md
```

**Contents of `MathTest.md`:**
```
# Chapter

Math: $y = \int_0^t u(t) dt$

## Section

Math: $y = \int_0^t u(t) dt$
```

**Pandoc version 3.1.4 through 3.1.6 (x86_64-macOS):**
The resulting HTML file `MathTest/1-chapter.html` is lacking the `<scipt>` element to include the MathJax code. Hence, the math formulae are rendered as plain text.

**Pandoc version 3.1.3 (x86_64-macOS):**
`MathTest/1-chapter.html` is created correctly.

**Further observation:**
When you change a heading to include math (e.g. `# Chapter $x$`), Pandoc 3.1.4 through 3.1.6 also include the MathJax script. This was likely broken in https://github.com/jgm/pandoc/commit/40dacad52581c785c022d42bf7117216dcfe915a to fix #8620. Notice that the test document in this issue does contain math in all headings.

**Comment by jgm** [comment]
I think that a workaround might be adding `-Vmath` to your command line.
