### ISSUE TITLE
ChunkedHTML output: error message for missing title although title is present and used

### ISSUE THREAD

**Issue by PlainMartin** [jgm/pandoc#8968]
**Explain the problem.**

Creating Chunked HTML output from “test.md” (which has a title tag in the metadata section)

	pandoc -s test.md --to chunkedhtml -o chunkedout  

…gives this error message:

	This document format requires a nonempty <title> element.
	Defaulting to 'test' as the title.
	To specify a title, use 'title' in metadata or --metadata title="...".

Now the chunked output is perfectly fine: “index.html” gets the source document title, the following documents use the headers at split level. So it seems this error shouldn’t be displayed. But maybe I’m missing something here.

I am using a wrapper / loop that processes and creates large document sets, so I get a lot of these “false alarms”, which makes it hard to spot actual errors.

Thank you for looking into this.

**Pandoc version?**
3.1.6

**Comment by jgm** [comment]
It looks as if c06b9ab33147cea8363961929dedbd97f754e5dc fixed this issue too.
