### ISSUE TITLE
SelfContained: wrong width and height computed from viewBox

### ISSUE THREAD

**Issue by nxn-4-wdf** [jgm/pandoc#8969]
**Explain the problem.**

This issue is my fault: I misinterpreted the values of `viewBox` in #8948. The [MDN documentation on viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) gives the correct interpretation:

> The value of the `viewBox` attribute is a list of four numbers: `min-x`, `min-y`, `width` and `height`.

Therefore, you can simplify the code on line 216 in `src/Text/Pandoc/SelfContained.hs`:

```haskell
    (Just (llx,lly,urx,ury), Nothing, Nothing) -> -- calculate width, height
        combinedAttrs ++
        [ ("width", tshow (floor urx - floor llx :: Int)) |
            isNothing (lookup "width" combinedAttrs) ] ++
        [ ("height", tshow (floor ury - floor lly :: Int)) |
            isNothing (lookup "height" combinedAttrs) ]
```

Parts ` - floor llx` and  ` - floor lly` must be removed.

Moreover, if the SVG creators specified non-integer values for width and height, I believe we should respect this choice, and write non-integer values, for example `viewBox="10 20 11.22 33.44"` implies `width="11.22" height="33.44"`. Browsers should have no issue with it.

**Pandoc version?**

Current version 3.1.6

**Comment by nxn-4-wdf** [comment]
Another improvement: when referring with `<svg>` and `<use>` to a previously-embedded SVG, the `viewBox` attribute from the source SVG should be copied into the target `<svg>` tag.

Reason is that it keeps the correct aspect ratio if the second SVG has different dimensions, as [explained on CSS Tricks](https://css-tricks.com/scale-svg/#aa-how-to-scale-svg-to-fit-within-a-certain-size-without-distorting-the-image)

Example from `/test/command/8948.md` : `<svg alt="minimal"><use href="#svg_7868854ffb8f30209cd0" /></svg>`
should be: `<svg alt="minimal" viewBox="-.333 -.333 480 150"><use href="#svg_7868854ffb8f30209cd0"/></svg>`

And: `<svg alt="minimal"><use href="#foo" /></svg>`
should be: `<svg alt="minimal" viewBox="-.333 -.333 480 150"><use href="#foo"/></svg>`

Note: I removed the unnecessary space before the closing `/>` too.

**Comment by nxn-4-wdf** [comment]
I did not find a CSS style for the SVG. The following should be OK:

```css
svg {
  height: auto;
  max-width: 100%;
}
```

Reason: `max-width` is the same as for `img`.
And `height: auto;` computes the correct height if not explicitly specified.

**Comment by jgm** [comment]
> Another improvement: when referring with <svg> and <use> to a previously-embedded SVG, the viewBox attribute from the source SVG should be copied into the target <svg> tag. Reason is that it keeps the correct aspect ratio if the second SVG has different dimensions...

I don't understand this one.
We'll only be using `<use>` if the two images point to the same svg file (or to files with identical contents).
In that case both svgs will have the same viewBox attribute and the same dimensions, no?

**Comment by jgm** [comment]
I'm also a bit confused about the width and height attributes. From my reading of the documentation of the svg element, these should have units -- e.g. `400px` not `400`.  So this is different from width and height on `img`, which are just numbers indicating pixels.  I think we need to do some conversion here.

**Comment by jgm** [comment]
Another thought: "The xmlns attribute is only required on the outermost svg element of SVG documents, or inside HTML documents with XML serialization. It is unnecessary for inner svg elements or inside HTML documents with HTML serialization."  Since we try to produce polyglot HTML that is also good XML, we should include it?

**Comment by jgm** [comment]
[This discussion](https://webmasters.stackexchange.com/questions/118335/) leads me to think that we should not calculate `width` and `height` attributes from the `viewBox`.

**Comment by nxn-4-wdf** [comment]
> I'm also a bit confused about the width and height attributes. From my reading of the documentation of the svg element, these should have units -- e.g. `400px` not `400`. So this is different from width and height on `img`, which are just numbers indicating pixels. I think we need to do some conversion here.

Just checked the SVG specification https://www.w3.org/TR/SVG/coords.html#Units

> If the width or height presentation attributes on the outermost svg element are in user units (i.e., no unit identifier has been provided), then the value is assumed to be equivalent to the same number of "px" units (see Units).

Therefore you do not need to specify `px`, because it is equivalent. Moreover [MDN svg](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg) states that width and height are of  [content type length](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#length), which is defined as: `length ::= <number> (<absolute-length> | <relative-length>)?`.

Number can be a real number (therefore you do not need to convert it with `floor` and `:: Int`) and the length unit is optional.

**Comment by nxn-4-wdf** [comment]
> Another thought: "The xmlns attribute is only required on the outermost svg element of SVG documents, or inside HTML documents with XML serialization. It is unnecessary for inner svg elements or inside HTML documents with HTML serialization." Since we try to produce polyglot HTML that is also good XML, we should include it?

Pandoc includes inline SVG only if output if HTML 5, correct ? And if I interpret the specs correctly, HTML5 includes not only the `svg` and `xlink` namespaces, but 6 others, for example `MathML`. See: https://infra.spec.whatwg.org/#namespaces

Then the `xmlns` attributes are definitely not required. Moreover, I found very clear explanations in the first two answers of: https://stackoverflow.com/questions/18467982/are-svg-parameters-such-as-xmlns-and-version-needed 

Therefore I trust that Pandoc will produce good HTML5 with this 😇

**Comment by frabjous** [comment]
If I understand right, this issue is not properly solved (or else I am having a very similar issue).

Consider this markdown:

```markdown
Here is my circle: ![small circle](smallcircle.svg).

Here is my circle again: ![small circle](smallcircle.svg).

```

If you process this with just `pandoc --standalone test.md -o test.html` so the svgs are not embedded you get a fairly normal looking document when viewed in a browser:

![circtest-no-embed](https://github.com/jgm/pandoc/assets/305948/bb3fd0ca-80b5-45cd-9a32-b5f33aab2b81)

If you process the same but embed the svgs with `pandoc --standalone --embed-resources test.md -o test.html` you get a completely different looking document, where the first circle swells to fill the space.

![circtest-with-embed](https://github.com/jgm/pandoc/assets/305948/4dfc5b9e-e1c4-42c8-a625-10d98373e1f9)

From what I can tell this is just because the first svg element references the second but does have have its own `height` and `width` attributes, and so swells to fill the remainder. Setting the viewBox is insufficient.

I'm attaching smallcircle.svg used for testing, but I've had this issue will all svgs.

![smallcircle](https://github.com/jgm/pandoc/assets/305948/6ff44982-1019-40bd-936e-c7c126a48a7c)

(Tested with pandoc 3.1.11.1 on linux x86_64, released Jan 2024.)

**Comment by jgm** [comment]
Why don't you open a new issue for this?
Otherwise we'll lose track.

**Comment by jgm** [comment]
ALso have a look at #9206 which is relevant.
And maybe also #9420

**Comment by frabjous** [comment]
> Why don't you open a new issue for this? Otherwise we'll lose track.

Done. See #9439. Thanks.
