### ISSUE TITLE
Troubleshooting 'wkhtmltopdf' Error when Using 'footer-html' Parameter with 'pandoc'

### ISSUE THREAD

**Issue by ConanZZ** [jgm/pandoc#8973]
**Explain the problem.**
I am using the PDF engine wkhtmltopdf to convert a given markdown file to PDF. When I use --pdf-engine-opt to pass the parameter "footer-html" to wkhtmltopdf, I always encounter the following error, regardless of whether I include the --enable-local-file-access option or not:
![image](https://github.com/jgm/pandoc/assets/19329479/61c3b08f-8a50-4421-8798-0d4bc49f0a5f)

My pandoc command line is as follows, and the input.md file, convert.css file, header.html file, and footer.html file involved are all in the same directory as pandoc.exe on the local machine.
` pandoc --pdf-engine=wkhtmltopdf -s --css=convert.css -f markdown -t pdf --pdf-engine-opt="--enable-local-file-access" --include-in-header=header.html --variable=margin-top=0in --variable=margin-bottom=0.333in --variable=margin-left=0in --variable=margin-right=0in --dpi=200 input.md -o test.pdf --pdf-engine-opt="footer-html footer.html"`
**Pandoc version?**
3.1.6

**Comment by jgm** [comment]
Try with
```
--pdf-engine-opt='--footer-html' --pdf-engine-opt='footer.html'
```
