### ISSUE TITLE
toJSONFilter no longer supports non-monad list result

### ISSUE THREAD

**Issue by elliottslaughter** [jgm/pandoc#8976]
I have been using the following filter on some of my documents. As of pandoc-types 1.23.0.1, this appears to no longer compile:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Text.Pandoc.Definition
import Text.Pandoc.JSON

-- This pass strips <span class="remove">...</span>.
removeSpan :: Inline -> [Inline]
removeSpan (Span (_, ["remove"], _) _) = []
removeSpan x = [x]

main :: IO ()
main = toJSONFilter removeSpan
```

Error:

```
my_filter.hs:11:8: error:
    • No instance for (ToJSONFilter IO (Inline -> [Inline]))
        arising from a use of ‘toJSONFilter’
        (maybe you haven't applied a function to enough arguments?)
    • In the expression: toJSONFilter removeSpan
      In an equation for ‘main’: main = toJSONFilter removeSpan
   |
11 | main = toJSONFilter removeSpan
   |        ^^^^^^^^^^^^
```

After staring a bit at the [documentation](https://hackage.haskell.org/package/pandoc-types-1.23.0.1/docs/Text-Pandoc-JSON.html) and [source code](https://hackage.haskell.org/package/pandoc-types-1.23.0.1/docs/src/Text.Pandoc.JSON.html#toJSONFilter) for `toJSONFilter`, I came to the conclusion that this form is no longer supported and I need to add the `IO` monad to unbreak it. And indeed, this works:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Text.Pandoc.Definition
import Text.Pandoc.JSON

-- This pass strips <span class="remove">...</span>.
removeSpan :: Inline -> IO [Inline]
removeSpan (Span (_, ["remove"], _) _) = return []
removeSpan x = return [x]

main :: IO ()
main = toJSONFilter removeSpan
```

It's not the most horrible change to need to make to my code, but it is (I think) a breaking change, and can cause users some needless effort, especially because the list form is not clearly demonstrated in the documentation of either the [filters page](https://pandoc.org/filters.html) or Hackage for [`toJSONFilter`](https://hackage.haskell.org/package/pandoc-types-1.23.0.1/docs/Text-Pandoc-JSON.html).

Versions, etc.:

```
$ pandoc --version
pandoc 3.1.4
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: .../pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

macOS 13.5

**Comment by jgm** [comment]
@KommuSoft may want to comment.

**Comment by jgm** [comment]
Ah, I think the problem was not @KommuSoft's commit but [my revision](https://github.com/jgm/pandoc-types/commit/183af9d9f1066be974ac55fd23a4c985999d3ce8).  Will fix.
