### ISSUE TITLE
`.odt` Reader does not handle attribute `text:continue-numbering` on lists.

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#8979]
# Explain the problem.

We have identified an issue where the conversion process from `.odt` to `.html` using both Microsoft Word and Google Docs does not correctly preserve the `start` attribute on ordered lists. This problem seems to be specific to the conversion from `.odt`, as the same conversion from `.docx` to `.html` correctly maintains the `start`-attribute when performed on identical documents.

## Expected Result:

The `start`-attribute on ordered lists should be preserved during the conversion from `.odt` to `.html`, similar to how it is preserved in the `.docx` to `.html` conversion.

## Actual Result:

The `start`-attribute on ordered lists is not preserved when converting from `.odt` to `.html`.

# Pandoc version

```
pandoc 3.1.6
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/steve/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

# Examples

<table>
<thead>
<tr>
<th>Testcase</th>
<th>Folder including input and output for <code>.docx</code></th>
<th>Output from <code>.docx</code></th>
<th>Folder including input and output for <code>.odt</code></th>
<th>Output from <code>.odt</code></th>
</tr>
</thead>
<tbody>

<tr>
<td>
Google Docs
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-google-docs-docx-lists-several-types?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-google-docs-docx-lists-several-types/none/expected.html?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-google-docs-odt-lists-several-types?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-google-docs-odt-lists-several-types/none/expected.html?ref_type=heads">Here.</a>
</td>
</tr>

<tr>
<td>
Microsoft word
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-microsoft-word-docx-lists-several-types?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-microsoft-word-docx-lists-several-types/none/expected.html?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-microsoft-word-odt-lists-several-types?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-microsoft-word-odt-lists-several-types/none/expected.html?ref_type=heads">Here.</a>
</td>
</tr>

</tbody>
</table>

# Commands used

    $ pandoc -s --quiet --from=docx --to=html --output=<output-path> --template=./src/template.html <input-path>
    $ pandoc -s --quiet --from=odt --to=html --output=<output-path> --template=./src/template.html <input-path>

**Comment by jgm** [comment]
Can we have a more focused example? A single odt containing just one list that starts at something other than 1, and is incorrectly converted?  I tried to create such an example with LibreOffice, and pandoc converted it correctly.

I also tried creating an example in Word and saving it as odt. Again, pandoc converted it correctly.

**Comment by StephanMeijer** [comment]
<img width="237" alt="image" src="https://github.com/jgm/pandoc/assets/3169264/f8b50611-d747-42f5-aa6e-00ad1cd8e3e9">

From Google Docs

----

`.docx`: [input.docx](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-google-docs-docx-list-from-two-text-in-between?ref_type=heads), output: [none/actual.html](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-google-docs-docx-list-from-two-text-in-between/none/expected.html?ref_type=heads)

`.odt`: [input.odt](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-google-docs-odt-list-from-two-text-in-between?ref_type=heads) output: [none/expected.html](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-google-docs-odt-list-from-two-text-in-between/none/expected.html)

**Comment by StephanMeijer** [comment]
I suspect it might be the `text:continue-numbering="true"` that is being ignored:

<img width="1569" alt="image" src="https://github.com/jgm/pandoc/assets/3169264/530754b3-4d1f-4a10-b651-c280be1fd5c3">

**Comment by StephanMeijer** [comment]
<img width="411" alt="image" src="https://github.com/jgm/pandoc/assets/3169264/9f2d7438-2770-49c2-9cd0-bd274c682980">

Libreoffice example

---

*`.docx`*:
- [input.docx](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-libroffice-docx-list-from-two-text-in-between?ref_type=heads)
- [none/expected.html](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-libroffice-docx-list-from-two-text-in-between/none/expected.html?ref_type=heads)

*`.odt`*:
- [input.odt](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-libreoffice-odt-list-from-two-text-in-between?ref_type=heads)
- [none/expected.html](https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-libreoffice-odt-list-from-two-text-in-between/none/expected.html?ref_type=heads)

**Comment by StephanMeijer** [comment]
Again in `.odt`:

<img width="945" alt="image" src="https://github.com/jgm/pandoc/assets/3169264/8e38323b-e2f9-4328-b819-709a2357ff09">

**Comment by jgm** [comment]
Yes,  believe the reader doesn't do anything with text:continue-numbering.  It does properly handle start numbers, though, so the title of this issue is a bit misleading.

**Comment by StephanMeijer** [comment]
@jgm I will change the title appropriately.
