### ISSUE TITLE
Inconsistent handling of headings in lists (`.odt`, `.docx` to `.html`)

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#8980]
# Explain the problem.

In the wild and wonderful world of our user base, we've discovered that some are pursuing rather unconventional practices with their word processors. A fondness for masquerading elements as headings, styled to regular text, has come to light. 

This situation presents an inconsistency when utilizing Pandoc for document conversion from Google Docs to `.html`. When converting from `.odt` to `.html`, Pandoc correctly adjusts these list-embedded headings, transforming them into regular text. However, when converting from `.docx` to `.html`, the same operation incorrectly converts the list items into headings.

## Expected Result:

The desired functionality is for headings embedded in list items to be consistently converted into regular text across all conversion pathways.

## Actual Result:

In the `.docx` to `.html` conversion process, the list items are instead being converted into headings. This is contrary to the behavior seen in the `.odt` to `.html` conversion process.

# Pandoc version

```
pandoc 3.1.6
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/steve/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

# Examples

<table>
<thead>
<tr>
<th>Testcase</th>
<th>Folder including input and output for <code>.docx</code></th>
<th>Output from <code>.docx</code></th>
<th>Folder including input and output for <code>.odt</code></th>
<th>Output from <code>.odt</code></th>
</tr>
</thead>
<tbody>

<tr>
<td>
Google Docs
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-google-drive-docx-headings-and-titles-in-list?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-google-drive-docx-headings-and-titles-in-list/none/expected.html?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/tree/master/test/NLDOC-765-google-drive-odt-headings-and-titles-in-list?ref_type=heads">Here.</a>
</td>
<td>
<a href="https://gitlab.com/toegang-voor-iedereen/pandoc-filters/-/blob/master/test/NLDOC-765-google-drive-odt-headings-and-titles-in-list/none/expected.html?ref_type=heads">Here.</a>
</td>
</tr>
</tbody>
</table>

# Commands used

    $ pandoc -s --quiet --from=docx --to=html --output=<output-path> --template=./src/template.html <input-path>
    $ pandoc -s --quiet --from=odt --to=html --output=<output-path> --template=./src/template.html <input-path>

**Comment by jgm** [comment]
> The desired functionality is for headings embedded in list items to be consistently converted into regular text across all conversion pathways.

Headings are allowed in list items in many of the formats we convert to/from.  Your best bet is to use a Lua filter to convert headings inside list items into regular paragraphs.  This is not difficult.

**Comment by StephanMeijer** [comment]
@jgm What can be the reason that the conversion of `.docx` and `.odt` differs?

**Comment by jgm** [comment]
I haven't looked, but the ODT reader has many quirks.

**Comment by jgm** [comment]
Actually what I'm seeing in my tests is that the odt reader does parse headings in lists, preserving the headings, while the docx reader does not. (Sort of the reverse of what you report.)

```
% cat > test.md
- # a
- b
% pandoc -o test.odt test.md
% pandoc -o test.docx test.md
% pandoc test.odt -t native
[ BulletList
    [ [ Header
          1
          ( "a" , [] , [] )
          [ Span ( "anchor" , [] , [] ) [] , Str "a" ]
      ]
    , [ Plain [ Str "b" ] ]
    ]
]
% pandoc test.docx -t native
[ Header 1 ( "a" , [] , [] ) [ Str "a" ]
, BulletList [ [ Plain [ Str "b" ] ] ]
]
```

This has to do with differences in structure between OOXML and OpenDocument XML.

**Comment by StephanMeijer** [comment]
@jgm Thanks for the feedback, shall we therefore close this ticket?

**Comment by StephanMeijer** [comment]
> Your best bet is to use a Lua filter to convert headings inside list items into regular paragraphs. This is not difficult.

@jgm Is this even possible? As the `<h2>` is not a child of `<ol>` or `<li>`?

**Comment by jgm** [comment]
Are you talking about
```
% cat > test.md
- # a
- b
% pandoc -o test.docx test.md
% pandoc test.docx -t native
[ Header 1 ( "a" , [] , [] ) [ Str "a" ]
, BulletList [ [ Plain [ Str "b" ] ] ]
]
```
Correct. In that case there is no way to handle it with a filter.  If you want to create an issue that focuses on this precise thing: that the docx reader parses a paragraph that is BOTH a list item and a heading (has heading style) as a simple heading, go ahead.  I'm not sure why it's done the way it is, but ooxml is a gnarly format to parse (not really hierarchical).
