### ISSUE TITLE
PDF compilation fails on italic text containing multiblock footnote

### ISSUE THREAD

**Issue by brandondyck** [jgm/pandoc#8982]
My markdown input, `test.markdown`, has an italicized sentence with a multiblock footnote in it:
```
_This sentence[^1] has a footnote._

[^1]: Here's a paragraph.
    
    Here's another paragraph.
```

When I convert it with `pandoc -o test.pdf test.markdown`, pdftex chokes on its input:
```
Error producing PDF.
! Paragraph ended before \text@command was complete.
<to be read again>
                   \par
l.60 ...e’s another paragraph.} has a footnote.}
```

Converting it to a .tex file with `pandoc -o test.tex test.markdown` gives the following:
```
\emph{This sentence}\footnote{Here's a paragraph.

  Here's another paragraph.} \emph{has a footnote.}
```

Pandoc creates the PDF properly if I remove either the italics or the second block of the footnote. For now I'm working around it by writing the first part as `_This sentence_[^1] _has a footnote._`

I'm using the following software:
- Pandoc 3.1.6
- Ubuntu 22.04.1 LTS on WSL2
- pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)

**Comment by ibayashi-hikaru** [comment]
I fixed this bug in this PR #9168. 
Can you take a look please?

Note: I'm new to the pandoc project.
