### ISSUE TITLE
Comments in frontmatter not handled properly when converting to PDF

### ISSUE THREAD

**Issue by beyarkay** [jgm/pandoc#8985]
**Explain the problem.**

This can be recreated with the following markdown ([try-pandoc link](https://pandoc.org/try/?params=%7B%22text%22%3A%22---%5Cnheader-includes%3A+%7C%5Cn++%5C%5Csetlength%7B%5C%5Ctabcolsep%7D%7B2pt%7D+%23+This+is+a+comment%5Cn++%5C%5Cusepackage%7Balgorithm%7D%5Cn---%5Cn%5Cn%23+Header%5Cn%5Cn-+list+item%5Cn-+list+item+2%22%2C%22to%22%3A%22latex%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)).

Including a comment in the YAML frontmatter makes pandoc upset:

```md
---
header-includes: |
  \setlength{\tabcolsep}{2pt} # This is a comment
  \usepackage{algorithm}
---

# Header

- list item
- list item 2
```

And then trying to compile the above into a PDF using pandoc:

```sh
$ pandoc bug.md -o bug.pdf
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.43 \setlength{\tabcolsep}{2pt} \#
```

I expected to be able to include comments in the YAML frontmatter, since comments are valid YAML.

The compiled `tex` file ends up escaping the `#`, but I'm guessing the better idea would be to replace the YAML comment with a LaTeX comment `%`?:

```
[...]
\setlength{\tabcolsep}{2pt} \# This is a comment

\usepackage{algorithm}
[...]
```

In my case, I'm writing my Masters and have many packages and custom commands, so being able to comment them would really help me keep track of what lines are accomplishing what.

**Pandoc version?**

I'm using 3.1.4 on MacOS 12.4, but this reproduces with try-pandoc so this issue has not been fixed (yet).
```
$ pandoc --version
pandoc 3.1.4
Features: +server +lua
Scripting engine: Lua 5.4
```

Happy to submit a PR for this bug if the dev team could point me roughly in the right direction. And thanks for such a useful tool!

**Comment by jgm** [comment]
That's not LaTeX syntax for a comment. LaTeX uses `%`, not `#`.

Note that when you use `|` for YAML block content, YAML comments can't be included; the whole thing is interpreted as a literal string.

**Comment by beyarkay** [comment]
Sorry! My YAML knowledge isn't as good as I thought.
