### ISSUE TITLE
Could pandoc.layout provide more control over where it wraps lines?

### ISSUE THREAD

**Issue by wlupton** [jgm/pandoc#8987]
I've been using a custom writer (based on a fork of https://github.com/lvignoli/typst-pandoc) to investigate richer Typst generation. I've been using `pandoc.layout` functions to generate the output but line wrapping can generate invalid Typst. The two cases that I've hit are:

* Leading `-`, which is taken as a bulleted list
* Leading `/`, which is taken as a term list

I could simply escape all hyphens and slashes but they aren't really special characters (they can usually be used unescaped) and this might cause other problems (I tried, and it does, because all metadata strings will be escaped, and this included a filename, for which Typst wasn't happy with an escaped hyphen... although I was able to work around that).

So I'm wondering whether `pandoc.layout` could know to avoid placing some characters at the beginning of a wrapped line (or know to escape such characters when they're wrapped to the beginning of a line).

Looking at the docs, I wonder whether `pandoc.layout.after_break()` can be used for this purpose, but I don't see how to use it (I tried a single call to `after_break("\\")` at the outer level but I don't think that can be correct).

**Comment by jgm** [comment]
`after_break` could work, yes.  `after_break("\\")` should include `\\` if and only if you're at the beginning of a line.  (But after indentation, I'm not sure.)

**Comment by wlupton** [comment]
Re `after_break()`, when would I use it? Oh, perhaps I wrap each wrapped `Doc` in it? I'd appreciate a quick example, and/or I can play with it tomorrow. Thanks.

**Comment by wlupton** [comment]
OK, I see. As you indicated, it can be thought of as a conditional escape, and it seems fine with indentation. Here's my text program (which could be more efficient). I'll close the issue.

after-break.lua
```
local logging = require 'logging'

local temp = logging.temp

local after_break = pandoc.layout.after_break
local concat = pandoc.layout.concat
local empty = pandoc.layout.empty
local nest = pandoc.layout.nest
local render = pandoc.layout.render
local space = pandoc.layout.space

local doc = empty

function Space()
    doc = concat { doc, space }
end

function Str(str)
    local text = str.text

    local text = empty
    for i = 1, #str.text do
        local char = str.text:sub(i, i)
        if char == '-' then
            text = concat { text, after_break("\\"), char }
        else
            text = concat { text, char }
        end
    end

    doc = concat { doc, text }
end

function Pandoc()
    local columns = PANDOC_WRITER_OPTIONS.columns
    local indent = math.floor(columns / 10)
    io.stdout:write(render(nest(doc, indent), columns + indent) .. '\n')
end
```

after-break.md
```
This is text - that might wrap - and if a hyphen wraps to the start of a line then it will be escaped.
```

output
```
% pandoc after-break.md -L after-break.lua -o after-break.html --columns 15
 This is text -
 that might wrap
 \- and if a
 hyphen wraps to
 the start of a
 line then it
 will be
 escaped.
```
```
% pandoc after-break.md -L after-break.lua -o after-break.html --columns 17
 This is text -
 that might wrap -
 and if a hyphen
 wraps to the
 start of a line
 then it will be
 escaped.
```
```
