### ISSUE TITLE
pandoc fails to build beamer document when downloading images

### ISSUE THREAD

**Issue by xihh87** [jgm/pandoc#8994]
When [building a beamer document](https://github.com/xihh87/reproduce-error/blob/85c01927b6cacfa67065442e55e40b46ad253581/makefile#L2-L8 )  (didn't test other outputs) using [a document containing an image URL](https://github.com/xihh87/reproduce-error/blob/main/image-not-loading.md?plain=1 ), pandoc fails:

```
[WARNING] Could not convert image /tmp/tex2pdf.-ad0e2b8b72877360/da39a3ee5e6b4b0d3255bfef95601890afd80709.so: Cannot load file
  Jpeg not enough bytes
  PNG not enough bytes
  Bitmap not enough bytes
  GIF not enough bytes
  HDR not enough bytes
  Tiff not enough bytes
  TGA not enough bytes
Error producing PDF.
! LaTeX Error: Unknown graphics extension: .so.
```

I made [a reproducible case](https://github.com/xihh87/reproduce-error/tree/main ) which fails on pandoc `2.11.3.1` and `3.1.6.1` (latest version as of report date).

I suspect the issue is downloading image, because [when using the downloaded image this works correctly](https://github.com/xihh87/reproduce-error/blob/this-works/image-not-loading.md?plain=1 ), even if [the image has a weird name](https://github.com/xihh87/reproduce-error/blob/name/image-not-loading.md?plain=1) or [no extension](https://github.com/xihh87/reproduce-error/blob/adcae6626947f49e96f88e9ec6e1d2023f1979e8/image-not-loading.md?plain=1 ).

This seems similar to [this problem reported on the mailing list](https://groups.google.com/g/pandoc-discuss/c/j4rNA3EzqFw/m/oV5szcr0eAAJ ).

The problem can be worked around by downloading the images, but that may not be ideal for some use cases.

Maybe some previous version did the right thing because I got the error when *rebuilding* some keynotes. However I did not bisected this error, nor have I found a working version.

**Comment by jgm** [comment]
When I try to fetch the image with `curl`, I get a message that I'm being redirected to `https://images.unsplash.com/photo-1579458342405-52d7d969e0d4?ixlib=rb-4.0.3&q=85&amp;fm=jpg&crop=entropy&cs=srgb&dl=aida-l-6y5iySR_UXc-unsplash.jpg&w=1920`.  Using that as the image URL in the markdown file, conversion to beamer works.

**Comment by jgm** [comment]
I thought the code we were using to download would follow redirects, but maybe not -- or maybe something changed in a dependent library?

**Comment by jgm** [comment]
Here's the Response object returned by our http request:  we're getting 405 "Not allowed". 
```hs
Response {responseStatus = Status {statusCode = 405, statusMessage = "Not allowed"}, responseVersion = HTTP/1.1, responseHeaders = [("Connection","close"),("Content-Length","0"),("Server","Varnish"),("Retry-After","0"),("Accept-Ranges","bytes"),("Date","Fri, 11 Aug 2023 06:02:53 GMT"),("Via","1.1 varnish"),("X-Served-By","cache-pao-kpao1770081-PAO"),("X-Cache","MISS"),("X-Cache-Hits","0"),("Set-Cookie","require_cookie_consent=false; Expires=Sat, 10 Aug 2024 06:02:53 GMT; path=/;")], responseBody = "", responseCookieJar = CJ {expose = [Cookie {cookie_name = "require_cookie_consent", cookie_value = "false", cookie_expiry_time = 3022-12-12 00:00:00 UTC, cookie_domain = "unsplash.com", cookie_path = "/", cookie_creation_time = 2023-08-11 06:02:53.516583 UTC, cookie_last_access_time = 2023-08-11 06:02:53.516583 UTC, cookie_persistent = False, cookie_host_only = True, cookie_secure_only = False, cookie_http_only = False}]}, responseClose' = ResponseClose, responseOriginalRequest = Request {
  host                 = "unsplash.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/photos/6y5iySR_UXc/download"
  queryString          = "?ixid=MnwxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNjYzMDg2MjU5&force=true&w=1920"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
}
```
Anyway, this seems to point to an issue with the server.  Perhaps it is configured in a way that rejects non-browser requests?

**Comment by xihh87** [comment]
So, maybe [supplying the user agent](https://pandoc.org/MANUAL.html#reading-from-the-web )  of my browser fixes this issue for me.

Thanks a lot.

I think we should close this issue because it's not really a pandoc's problem.

**Comment by xihh87** [comment]
If it's not too much problem, can you please point to a guide to debug the http request?

The `--verbose` flag didn't show the request for me, the `--log=test.log` did not create a file, and I [couldn't find](https://www.google.com/search?q=debug+pandoc+http+requests&sca_esv=556275851&hl=en&sxsrf=AB5stBjBp1JTNB0U92hiafbdTtvhHtrKQw%3A1691837726929&ei=HmXXZKKvOIrykPIP05S5wAM&ved=0ahUKEwiituzV-taAAxUKOUQIHVNKDjgQ4dUDCA4&uact=5&oq=debug+pandoc+http+requests&gs_lp=Egxnd3Mtd2l6LXNlcnAiGmRlYnVnIHBhbmRvYyBodHRwIHJlcXVlc3RzMgUQABiiBEixEVDtCFiwDXABeAGQAQCYAXugAegDqgEDMy4yuAEDyAEA-AEBwgIKEAAYRxjWBBiwA8ICBxAjGLACGCfiAwQYACBBiAYBkAYI&sclient=gws-wiz-serp ) [a guide](https://www.r-bloggers.com/2023/05/troubleshooting-pandoc-problems-as-an-r-user/ ) that shows how to debug the requests.

It may also be useful to show an error to the users explaining that pandoc couldn't download the resources when the request contains an error.

**Comment by jgm** [comment]
To get the above, I inserted a traceShowId into the code and recompiled....
