### ISSUE TITLE
line breaks in title, abstract etc. inserted in YAML header block

### ISSUE THREAD

**Issue by andrewufrank** [jgm/pandoc#9011]
**Explain the problem.**

I refer to this [post](https://groups.google.com/g/pandoc-discuss/c/YxK5YvmMMTw/m/PCrA5d0GBQAJ ) and found that the information is partially misleading. The issue of inserting line breaks in the YAML header in pandoc seems to be different from the regular YAML specs (I refer, for [example](https://yaml-multiline.info/), ).

Constructing a minimal example with a title and an abstract in a markdown shows that: 
- multiline literal blocks  are constructed with `|` and newlines must be inserted with `two blanks at the end of the line` - which is not conforming to the YAML convention of preserving newlines in  blocks in literal style. 
- multiline folded blocks: there seems not be a way to insert linebreaks.

 The issue seems to be in the `readMarkdown` function, which codes the linebreaks in the `literal style` block as `SoftBreak`; it should likely be `LineBreak` because it should be preserved according to YAML rules).  Only breaks forced with two spaces are coded as `LineBreak`.  

The follwing output shows the example markdown file, then the result from reading with readMarkdown.  Output produced for LaTeX and HTML translate the Pandoc Meta as expecte: LineBreaks as hard breaks, SoftBreaks as spaces. 

The code uses is attached at end. I used pandoc 3.1.6.1 (current) with GHC 9.4.5 on Linux bhutan 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux.
 
````
exampleText 
---
title: | 
    A literal block text with fixed breaks with two spaces   
    here and slash/ 
    here and  with backslash\
    here 
abstract: > 
    a folded block text with no fixed breaks
    but here one with two spaces forced    
    here

---

some text


result from readMarkdown Pandoc (Meta {unMeta = fromList [("abstract",MetaBlocks [Para [Str "a",Space,Str "folded",Space,Str "block",Space,Str "text",Space,Str "with",Space,Str "no",Space,Str "fixed",Space,Str "breaks",Space,Str "but",Space,Str "here",Space,Str "one",Space,Str "with",Space,Str "two",Space,Str "spaces",Space,Str "forced",Space,Str "here"]]),("title",MetaBlocks [Para [Str "A",Space,Str "literal",Space,Str "block",Space,Str "text",Space,Str "with",Space,Str "fixed",Space,Str "breaks",Space,Str "with",Space,Str "two",Space,Str "spaces",LineBreak,Str "here",Space,Str "and",Space,Str "slash/",SoftBreak,Str "here",Space,Str "and",Space,Str "with",Space,Str "backslash\\",SoftBreak,Str "here"]])]}) [Para [Str "some",Space,Str "text"]]
````

The code used is: 

````

      exampleText <-  callIO $ readFile "docs/doc1.md"
        putIOwords ["\nexampleText", s2t exampleText] 

        let  markdownOptions = Pandoc.def {
                    Pandoc.readerExtensions =
                         Pandoc.extensionsFromList
                                [ Pandoc.Ext_yaml_metadata_block      
                                ]
                }
        p1 <- unPandocM $  Pandoc.readMarkdown markdownOptions (s2t exampleText)

        putIOwords ["\nresult from readMarkdown", showT $  p1] 

````

**Comment by jgm** [comment]
As documented, text in YAML fields is parsed as Markdown. The same extensions are used as in parsing the document itself.  So, if you haven't specified the `+hard_line_breaks` extension, then the line breaks will be soft -- in the title just as anywhere else.

This doesn't go against the YAML spec.  We are parsing the YAML with a conformant parser; it delivers the raw text of the field (with newlines), and then we parse it as Markdown, treating newlines just like we do in general.

**Comment by andrewufrank** [comment]
Thank you for the explanation, it surprises me, but I see the logic. 

I found the parsing procedure you mention in the manual (which I did not remember), but do not see a rationale for the double parsing; why did you selects this double process and not parse the YAML only once and insert the result in the `pandoc meta`? 

Parsing twice makes it  difficult to control the presentation of, e.g., title and abstract. I have the impression that   'two spaces + newline'  in  a `literal  block`  is the only way to insert a linebreak?  To use a `literal block` seems to introduces `<p> ... </p> into HTML which then interacts with the `tufte html template`.

**Comment by jgm** [comment]
YAML parsing just gives you a string. We want a formatted document (since titles can contain emphasis, math, etc.), so we need to parse that as Markdown.

You could use a pandoc markdown line block for this (see the manual):
```
title: | 
  |  This title has a line break right
  | here 
```

**Comment by florisvdh** [comment]
Is it possible to achieve multiline rendering of a metadata key (for HTML output) when passing it on the commandline using `--metadata=KEY:VAL`?

Using these don't seem to work for HTML:

```
'--metadata=author:XXX

YYY'
```

```
'--metadata=author:|
|XXX
|YYY'
```
