### ISSUE TITLE
New writer for ANSI

### ISSUE THREAD

**Issue by ethanalker** [jgm/pandoc#9012]
**Describe your proposed improvement and the problem it solves.**
Adding an ANSI writer would allow simple formatting (bold, colors, etc) in the terminal and improve the viewing experience over plaintext for terminal output. My specific usecase is for viewing emails with formatting, as currently I may miss emphasis on important details due to the lack of bolding, and I could also see myself and others using this generally as a quick document viewer. 

I found [pandoc-ansi](https://github.com/sellout/pandoc-ansi/tree/master) on github, however it doesn't seem to be maintained. Official support could be a matter of extending this codebase. 

I imagine pandoc would try to determine terminal support from the environment, but it should be possible to override this with a command line option. It would also make sense to have the output essentially the same as plaintext, just with extra formatting, which could also simplify development by reusing code from the plaintext writer. 

**Describe alternatives you've considered.**
Viewing in the terminal is also possible by converting to roff ms and using `man` as a pager, however I don't think native ANSI support is unreasonable since it should be relatively simple to implement. Also, removing a translation layer could improve accuracy.

**Comment by jgm** [comment]
Also there's https://github.com/tarleb/ansi-terminal-writer which is more recent.

**Comment by silby** [comment]
Done in #9565
