### ISSUE TITLE
! Package soul Error: Reconstruction failed.

### ISSUE THREAD

**Issue by XiangyunHuang** [jgm/pandoc#9019]
## **Explain the problem.**

Here is a minimal example with a test file `test.md`, as follow

```markdown
---
documentclass: ctexart
classoption: 
 - fontset=fandol
---

~~删除线~~
```

Then I convert the `test.md` to pdf using pandoc. 

```bash
pandoc  --standalone  --pdf-engine=xelatex  test.md -t pdf -o test.pdf
```

The output from the above command.

```
Error producing PDF.
! Package soul Error: Reconstruction failed.

See the soul package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.59 \st{删除线}
```

Then I find out there are conflicts between soul and ctex when we use XeLaTeX engine.  https://github.com/ho-tex/soul/issues/9

## **Pandoc version?**

I tested it with Pandoc 3.1.1 and Pandoc 3.1.6.2.

**Comment by jgm** [comment]
See #9006.
`soul` used to have problems with UTF-8, but this has been fixed in the most recent versions.  I wonder if your problem would go away if you used the most recent texlive, or at least upgraded soul?

Unfortunately I can't test directly on your case because I don't have the right fontset.

**Comment by jgm** [comment]
If there is a deeper conflict between soul and ctex, I'm not sure that's something we can fix on the pandoc side...

**Comment by XiangyunHuang** [comment]
> Unfortunately I can't test directly on your case because I don't have the right fontset.

`fontset=fandol` is a classoption of ctexart documentclass, [fandol](https://ctan.org/pkg/fandol) is a LaTeX package. ctexart is a documentclass from [ctex](https://ctan.org/pkg/ctex) package.

I wonder if it is possible to adjust Pandoc's LaTeX template? if so, then we can use xeCJKfntef instead of soul when we use XeLaTeX engine.

**Comment by XiangyunHuang** [comment]
> If there is a deeper conflict between soul and ctex, I'm not sure that's something we can fix on the pandoc side...

I will contact ctex developers.

**Comment by XiangyunHuang** [comment]
Here is a similar problem from ctex forum https://github.com/CTeX-org/forum/issues/217 .
It uses xeCJKfntef's `\sout`  instead of soul's `\st` .

**Comment by jgm** [comment]
You can certainly use a custom LaTeX template (the manual explains how).
In your custom template you could define `\st` in terms of xeCJKfntef's `\sout`, and then pandoc's output should work properly with it.

**Comment by jgm** [comment]
If you get this working, we could consider whether there's a natural way to modify the default template.

**Comment by XiangyunHuang** [comment]
```tex
\documentclass[fontset=fandol]{ctexart}
\usepackage{xeCJKfntef}
\begin{document}
\sout{中文}  % Here are two CJK characters
\sout{Chinese}
\sout{中文Chinese}
\end{document}
```

```tex
\documentclass{article}
\usepackage{ctex}
\usepackage{xeCJKfntef}
\begin{document}
\sout{中文}  % Here are two CJK characters
\sout{Chinese}
\sout{中文Chinese}
\end{document}
```

Both two minimal examples give the same right output.

![](https://github.com/jgm/pandoc/assets/12031874/d500416c-c9ab-403a-9e25-40533d8a2838)

> You can certainly use a custom LaTeX template (the manual explains how).
In your custom template you could define \st in terms of xeCJKfntef's \sout, and then pandoc's output should work properly with it.

Yes. I can get this working by a custom LaTeX template. The only change is from Pandoc's LaTeX Template's Line 295-300

https://github.com/jgm/pandoc-templates/blob/dbb6d8824e4188246b1cd9df76d36ed3965ba2a0/default.latex#L295-L300

to

```tex
\ifLuaTeX
  \usepackage{luacolor}
  \usepackage[soul]{lua-ul}
\else
  \ifXeTeX
    \usepackage{xeCJKfntef}
    \newcommand{\st}[1]{\sout{#1}}
  \else
    \usepackage{soul}
  \fi
\fi
```

Then, the minimal example also works.

```
---
documentclass: ctexart
classoption: 
 - fontset=fandol
---

~~删除线~~
```

```
pandoc --standalone --template=template.latex --pdf-engine=xelatex  test.md -t pdf -o test.pdf
```

**Comment by jgm** [comment]
That would make all documents depend on xeCJKfntef which I'd like to avoid.
Perhaps it could be gated under
```
$if(CJKmainfont)$

$endif$
```
But even then I wonder whether xeCJKfntef is a package you can expect to be installed...?

Do I infer from this that there is no problem for Chinese when using lualatex?

**Comment by XiangyunHuang** [comment]
> Perhaps it could be gated under
>
>```
>$if(CJKmainfont)$
>
>$endif$
>```
>

LGTM, The following code works.

```tex
\ifLuaTeX
  \usepackage{luacolor}
  \usepackage[soul]{lua-ul}
\else
  \ifXeTeX
    $if(CJKmainfont)$
      \usepackage{xeCJKfntef}
      \newcommand{\st}[1]{\sout{#1}}
    $endif$
  \else
    \usepackage{soul}
  \fi
\fi
```


> But even then I wonder whether xeCJKfntef is a package you can expect to be installed...?

xeCJKfntef is sub package from xeCJK, if we install xeCJK, then xeCJKfntef will be installed automatically. Please see https://github.com/CTeX-org/ctex-kit/blob/3dbff76e1d364aa7f82edfbba9a6ff97d2fae2e6/xeCJK/xeCJK.dtx#L52

> Do I infer from this that there is no problem for Chinese when using lualatex?

Yes.

**Comment by jgm** [comment]
Probably we want
```
    $if(CJKmainfont)$
      \usepackage{xeCJKfntef}
      \newcommand{\st}[1]{\sout{#1}}
    $else$
      \usepackage{soul}
    $endif$
```

**Comment by XiangyunHuang** [comment]
That's better.
