### ISSUE TITLE
Release assets should not have version numbers in them

### ISSUE THREAD

**Issue by jetxr** [jgm/pandoc#9023]
**Explain the problem.**
Pandoc's [release assets](https://github.com/jgm/pandoc/releases) having version numbers in them prevents them from being downloaded with links of this format: https://github.com/jgm/pandoc/releases/latest/download/pandoc-amd64.deb

Other projects generally allow for directly downloading the latest release:
- https://github.com/docker/compose/releases/latest/download/docker-compose-linux-aarch64
- https://github.com/grafana/agent/releases/latest/download/agent-linux-amd64.zip

Having the version number in the file name is also redundant, because the the version number is already in the URL from the tag. So an older version can be directly linked like so: https://github.com/jgm/pandoc/releases/download/3.1.6/pandoc-amd64.deb

**Comment by alerque** [comment]
Release attests *should* have version numbers in them. The issue URL may distinguish them at download time, but later on disk they end up being non-unique. This creates problems for downstream use, whether the Windows user who has a couple copies of the MSI installer or the Linux distro packager that needs to store source tarballs.

There are other ways of getting a fixed URL to a "latest" version of something without making all the assets over time have non-unique names. The latter solution is sometimes preferred for *direct binary downloads for specific platforms*, but is usually not preferred for all release assets such as tar / zip archives.

**Comment by jgm** [comment]
I agree with @alerque.
I believe it should be possible to use the GitHub API to query the file names of the release assets for the latest release. So, with a bit of scripting you can get what you want.
