### ISSUE TITLE
Remove unnecessary reference to phrenology

### ISSUE THREAD

**Issue by wenkokke** [jgm/pandoc#9024]
The documentation for Lua filters contains an example which frames the long discredited pseudoscientific field of phrenology as legitimate:
https://github.com/jgm/pandoc/blob/87716265c105a53438c0ab2fd214af434afe514b/doc/lua-filters.md?plain=1#L610

I'd request we change the occupation of our fictional professor to a more tasteful one.

**Comment by jgm** [comment]
Hm, it's just meant as a lighthearted joke I believe.
If it offends people though I'm fine with changing it.

**Comment by wenkokke** [comment]
I'd suggest the legacy of phrenology is anything but lighthearted?
