### ISSUE TITLE
Markdown size attributes: `{style="width:2.0in;... ` instead of `{width="2.0in"`

### ISSUE THREAD

**Issue by andrzejQ** [jgm/pandoc#9032]
**Markdown size attributes: `{style="width:2.0in;... ` instead of `{width="2.0in"`**

Pandoc is a great program - especially for fans of simple files with markup format (which is me).

I often use the markdown format, e.g. in a jekyll blog or with a library [Markdig](https://github.com/lunet-io/markdig) (MarkdownPanel for Notepad++).

The curly brackets `{}` in a markdown expression `![](){}` or `[](){}` are generally interpreted as a set of attributes. The proposal as above would lead to even greater universality of "*.md" files produced by pandoc.

For example, after creating the file "width in inch.docx" with the command
`pandoc "tst0.md" -o "width in inch.docx"`

where "tst0.md":
````md
Pandoc
======

![CommonMark ico](https://avatars.githubusercontent.com/u/8661225?v=4)
````
And re-convert to *.md:  
`pandoc "width in inch.docx" -o "width in inch.docx.md" --extract-media=./img/`

we get the file "width in inch.docx.md":

````md
# Pandoc

![CommonMark ico](./img/media/rId20.png){width="2.0in" height="2.0in"}

CommonMark ico
````

If this ".md" file was converted using pandoc to ".html"  
`pandoc "width in inch.docx.md" -o "width in inch.html`  
then we get valid HTML with image attributes:
````html
<img src="./img/media/rId20.png" style="width:2in;height:2in" alt="CommonMark ico" />
````

But in other libraries image attributes are often explicitly rewritten, e.g. Markdig:
````html
<img src="./img/media/rId20.png" width="2.0in" height="2.0in" alt="CommonMark ico" />
````

And in this context, width and height can only be the number of pixels. Browsers simply ignore everything except the integer part, i.e. in this example, they display an image in the size of 2px x 2px.

If pandoc generated attributes ready for insertion into HTML without conversion, it would extend the universality of the markdown file, i.e. in the 3rd line "width in inch.docx.md" it could be:

````md
![CommonMark ico](./img/media/rId20.png){style="width:2.0in;height:2.0in"}
````

**Comment by jgm** [comment]
I don't want to do the conversion to a `style` attribute at the AST level, because that's HTML specific. This belongs in the HTML writer (where it is).
The problem you describe sounds like a problem with Markdig's HTML generation and could be reported there.

**Comment by andrzejQ** [comment]
Sorry for posting more comments on a closed ticket...

The simplicity of this approach
<https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/GenericAttributesSpecs.md>
qualifies it for inclusion as a practical standard.

**Comment by jgm** [comment]
The `attributes` extension (currently only possible with `commonmark` and derivatives like `gfm`) gives you the ability to attach attributes to any element in a similar way.
