### ISSUE TITLE
Adding a docx template causes pandoc.exe: Cannot decode byte '\xad': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

### ISSUE THREAD

**Issue by Code4SAFrankie** [jgm/pandoc#9033]
**Explain the problem.**
I download the docx template using:

`pandoc.exe -o custom-reference.docx --print-default-data-file reference.docx`

I change the First Paragraph style by changing the font to Arial

I then run the below which previously worked just fine without the `--template` but without the needed formatting:

`pandoc.exe --to=docx --from=html --output=c:\downloads\t.docx --template=D:\Work\custom-reference.docx c:\downloads\GCSPart1UTF8.html`

GCSPart1UTF8.html is definitely UTF8, but I now get the error:

`pandoc.exe: Cannot decode byte '\xad': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream`

Word does give me a Compatibility warning when saving saying: Tables will lose alternative-text information. This is weird since I'm saving a docx to a docx, not sure if a doc was accidentally included in the distribution.

**Pandoc version?**
pandoc.exe 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: C:\Users\User\AppData\Roaming\pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

**Comment by jgm** [comment]
With a reference-doc, you need to use `--reference-doc`, not `--template`.  What is happening here is that pandoc is trying to read the reference docx (a binary file) as a UTF-8 text file ( a template).

**Comment by Code4SAFrankie** [comment]
Thanks, that fixed it. It ignores table borders though.
