### ISSUE TITLE
`number-sections` ignored in YAML

### ISSUE THREAD

**Issue by palday** [jgm/pandoc#9036]
**Explain the problem.**
The `number-sections` YAML entry is ignored.

MWE:

```markdown
---
number-sections: true
---

# A

## B

text
```

Does not show section numbers for `pandoc mwe.md -o mwe.pdf` unless the `--number-sections` command-line flag is used.

**Pandoc version?**
What version of pandoc are you using, on what OS? (If it's not the latest release, please try with the latest release before reporting the issue.)

```zsh
% pandoc --version           
pandoc 3.1.6.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/palday/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
You're misunderstanding.  Metadata is for metadata, not program instructions.  See the documentation for `--defaults` for a way to include program instructions in a YAML file.
