### ISSUE TITLE
Add way to reference images (with captions)

### ISSUE THREAD

**Issue by akerbos** [jgm/pandoc#904]
We can specify images such that they [get a a caption](http://johnmacfarlane.net/pandoc/README.html#pictures-with-captions) which translates to a `figure` environment in the LaTeX target (which is in particular used for PDF export in gitit).

However, floating graphics are all but useless if you can not link/refer to it. Therefore, I suggest a syntax to enable (labelling and) referencing images (with captions).

**Comment by p3palazzo** [comment]
This hack is incompatible with pandoc-citeproc, which overrides every instance of @reference even when it is not inside brackets.
