### ISSUE TITLE
org reader creates uncalled for alphabetical lists out of initials

### ISSUE THREAD

**Issue by cacology** [jgm/pandoc#9041]
The org reader converts initials to lists.  E.g.

```
#+TITLE: Testing

* Testing

p. lower case

P. Upper Case
```

With `pandoc --from org --to native` or `pandoc -f org-fancy_lists -t native` produces

```
[ Header 1 ( "testing-1" , [] , [] ) [ Str "Testing" ]
, OrderedList
    ( 1 , DefaultStyle , DefaultDelim )
    [ [ Para [ Str "lower" , Space , Str "case" ] ]
    , [ Para [ Str "Upper" , Space , Str "Case" ] ]
    ]
]
```
[Link](https://pandoc.org/try/?params=%7B%22text%22%3A%22%23%2BTITLE%3A+Testing%5Cn%5Cn*+Testing%5Cn%5Cnp.+lower+case%5Cn%5CnP.+Upper+Case%22%2C%22to%22%3A%22native%22%2C%22from%22%3A%22org%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

But should produce:

```
[ Header 1 ( "testing-1" , [] , [] ) [ Str "Testing" ]
, Para
    [ Str "p." , Space , Str "lower" , Space , Str "case" ]
, Para
    [ Str "P." , Space , Str "Upper" , Space , Str "Case" ]
]
```
([Round trip fails too.](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5B+Header+1+%28+%5C%22testing-1%5C%22+%2C+%5B%5D+%2C+%5B%5D+%29+%5B+Str+%5C%22Testing%5C%22+%5D%5Cn%2C+Para%5Cn++++%5B+Str+%5C%22p.%5C%22+%2C+Space+%2C+Str+%5C%22lower%5C%22+%2C+Space+%2C+Str+%5C%22case%5C%22+%5D%5Cn%2C+Para%5Cn++++%5B+Str+%5C%22P.%5C%22+%2C+Space+%2C+Str+%5C%22Upper%5C%22+%2C+Space+%2C+Str+%5C%22Case%5C%22+%5D%5Cn%5D%22%2C%22to%22%3A%22org%22%2C%22from%22%3A%22native%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D))

The [manual](https://pandoc.org/MANUAL.html#extension-fancy_lists) explains that neither of these should be interpreted as lists and [footnote 1](https://pandoc.org/MANUAL.html#fn1) gives an example of why this behavior is undesirable.

Furthermore, default org-mode does not interpret either of these as list items. The example parses to:

```
[... lots of html]

<h2 id="orgc31374e"><span class="section-number-2">1.</span> Testing</h2>
<div class="outline-text-2" id="text-1">
<p>
p. lower case
</p>

<p>
P. Upper Case
</p>
</div>

[... more html]
```

**Reproduced with:** [https://pandoc.org/try](https://pandoc.org/try) and MacOS 13.5.1 with pandoc 3.1.6.2 (Features: +server +lua Scripting engine: Lua 5.4) via homebrew.

Respectfully submitted.

**Comment by jgm** [comment]
The manual you cite is for a pandoc markdown extension.  Org-mode is something different.
There we try to match what Emacs does, and emacs counts this as a list.

**Comment by cacology** [comment]
Understood, I'll open an issue describing the deviance from Emacs's behavior.
