### ISSUE TITLE
pandoc 3.1.7 with `link-citations: true` doesn't break lines in citations

### ISSUE THREAD

**Issue by jpcirrus** [jgm/pandoc#9050]
In pandoc 3.1.7 with the `citeproc` filter and output to pdf, if `link-citations: true` then the citations don't break at the right margin, which they do when `link-citations: false`, and did previously. This is due to `\protect\hyperlink{ref-}{text}` being replaced by `\citeproc{ref-}{text}` in the resolution of #9031 by 353177f.

This can be seen with this input file (`test-citations.md`):

```markdown
---
link-citations: true
references:
- id: moore2000
  type: article-journal
  title: Diabetes
  container-title: Diabetes
  page: 1-2
  volume: 50
  issue: 2
  author:
    - family: Moore
      given: M.Peter
    - family: Lunt
      given: Helen
  issued:
    date-parts:
      - - 2000
...

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do [@moore2000]
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt...
```

and compiling with:

```bash
pandoc -o test-citations.pdf --citeproc test-citations.md
```

With `link-citations: true`:

<img width="519" alt="image" src="https://github.com/jgm/pandoc/assets/39587/a7aa371a-ab2b-4439-aea5-a4fd209267b3">

and with `link-citations: false`:

<img width="490" alt="image" src="https://github.com/jgm/pandoc/assets/39587/042850f0-500f-468e-bf84-0d766664bbb0">

**Comment by jgm** [comment]
@u-fischer is there a way to fix this?

**Comment by jgm** [comment]
This https://tex.stackexchange.com/questions/2773/how-do-i-make-latex-push-long-citations-to-a-new-line suggests that we need
```
\usepackage[breaklinks=true]{hyperref}
\usepackage{breakcites}
```

**Comment by jgm** [comment]
I can confirm that this works. But I don't know how common a package `breakcites` is.
The [code](https://mirror.mwt.me/ctan/macros/latex/contrib/breakcites/breakcites.sty) is so short we could even include it verbatim in the template (though this would be ugly).

**Comment by u-fischer** [comment]
sorry can't test now, but something like `\let\@cite@ofmt\relax` or `\let\@cite@ofmt\@firstofone`  should be enough. There is no need to pass to hyperref `breaklinks=true`. There are no current driver where this is relevant anymore.

**Comment by jpcirrus** [comment]
@jgm, just to let you know that 353177f causes an issue with beamer, as `enumitem` clobbers beamer lists. I will open an issue tomorrow.

**Comment by jgm** [comment]
Sorry to hear about the beamer/enumitem incompatibility. Perhaps we can work around that by using lower-level commands to adjust the list instead?  What we need to control:

- hanging indent
- spacing between bibliography items
- control over list label

**Comment by cagix** [comment]
> @jgm, just to let you know that 353177f causes an issue with beamer, as `enumitem` clobbers beamer lists. I will open an issue tomorrow.

the mentioned related issue is #9053 (just for future reference).

**Comment by jgm** [comment]
@u-fischer I went with
```
\let\@cite@ofmt\@firstofone
```
and this seems to work (though I don't know the difference between it and the other option).

**Comment by u-fischer** [comment]
> (though I don't know the difference between it and the other option).

The grouping  will be slightly different, in one case `\@cite@ofmt{#1}` -> `\relax{#1}`, in the other `\@cite@ofmt{#1}` -> `#1`.
