### ISSUE TITLE
pandoc 3.1.7 with `citeproc` clobbers beamer lists

### ISSUE THREAD

**Issue by jpcirrus** [jgm/pandoc#9053]
In pandoc 3.1.7 with the `citeproc` filter and output to beamer, because the `CSLReferences` environment is now provided as a new itemize list using the `enumitem` package in the resolution of #9031 by 353177f, the beamer theme lists are clobbered due to issues using  `enumitem` with beamer: https://tex.stackexchange.com/search?q=beamer+enumitem

This can be seen with this input file (`csl-beamer.md`):

````markdown
---
aspectratio: 169
references:
- id: moore2000
  type: article-journal
  title: Diabetes in New Zealand
  container-title: Diabetes
  page: 1-2
  volume: 50
  issue: 2
  author:
    - family: Moore
      given: M.Peter
    - family: Lunt
      given: Helen
  issued:
    date-parts:
      - - 2000
- id: powers2015
  type: book
  title: Exercise physiology
  publisher: McGraw-Hill
  author:
    - family: Powers
      given: Scott K.
    - family: Howley
      given: Edward T.
  issued:
    date-parts:
      - - 2015
  publisher-place: 'New York, NY'
nocite: |
  @*
header-includes: |
  ```{=latex}
  \setlength{\cslentryspacing}{0ex}  % Use vertical not horizontal length
  \AtBeginEnvironment{CSLReferences}{% Format bibliography
    \bigskip \scriptsize \setlength{\parskip}{0ex}}
  ```
---

## Itemise {.t}

- apple
- banana
- cherry

## Bibliography {.t}
````

and compiling with:

```bash
pandoc -t beamer -o csl-beamer.pdf csl-beamer.md
```

gives:

<img width="827" alt="image" src="https://github.com/jgm/pandoc/assets/39587/709f5cc0-32bd-4a5e-89e3-5aa467b57459">

but, when adding `--citeproc` the labels (and more?) get clobbered:

```bash
pandoc -t beamer -o csl-beamer.pdf --citeproc csl-beamer.md
```

<img width="828" alt="image" src="https://github.com/jgm/pandoc/assets/39587/855d93fe-bd9b-4a76-816b-ed72a86fe667">

<img width="827" alt="image" src="https://github.com/jgm/pandoc/assets/39587/52cfe146-9860-4a8a-b3c1-2224a84ee07f">

**Comment by jgm** [comment]
Perhaps we can work around the incompatibility between enumitem and beamer by using lower-level commands to adjust the list instead? What we need to control:

- hanging indent
- spacing between bibliography items
- control over list label

**Comment by jgm** [comment]
Another option would be to roll back the use of `\cite` and `\bibitem`, and just use `\phantomsection`.

**Comment by jpcirrus** [comment]
For reference:

Now that the LaTeX bibliography is generated using `\bibitem`, in order to customise its formatting when using the `metropolis` theme the following needs to be incorporated in the input file:

````markdown
header-includes: |
  ```{=latex}
  \setbeamerfont{bibliography entry author}{size=}
  \setbeamerfont{bibliography entry location}{size=}
  \setbeamerfont{bibliography entry note}{size=}
  \setbeamerfont{bibliography entry title}{size=}
  ```
````

This is a `metropolis` specific issue.

Credit: https://tex.stackexchange.com/a/683540

**Comment by jgm** [comment]
@u-fischer any suggestions?

**Comment by jpcirrus** [comment]
I have got this working if in the template `default.latex` the following code:

```latex
\usepackage{enumitem}
\newlist{CSLReferences}{itemize}{1}
\setlist[CSLReferences]{label={},
  leftmargin=\cslhangindent,
  itemindent=-1\cslhangindent,
  parsep=\parskip,
  itemsep=\cslentryspacing}
```

is replaced by:

```latex
\newenvironment{CSLReferences}{%
  \begin{list}{}{%
    \setlength\leftmargin{\cslhangindent}
    \setlength\itemindent{-1\cslhangindent}
    \setlength\parsep{\parskip}
    \setlength\itemsep{\cslentryspacing}}
    \ignorespaces}{%
  \end{list}\par\ignorespacesafterend}
```

**Comment by jpcirrus** [comment]
In the previous `CSLReferences` environment, 2 options were passed (1=hanging-indent and 2=entry-spacing). Not sure if you would still rather use those to set these options.

**Comment by jgm** [comment]
@jpcirrus that looks promising.

- What does the `\ignorespaces` do, and `\ignorespacesafterend`?
- Going back to the old CSLReferences format with the two options might be a good idea (it would minimize disruptions for people with custom templates pre 3.1.7).  I'm not sure.

Want to create a PR?

**Comment by jgm** [comment]
I went ahead and implemented a version of this.
Further tweaks welcome but it works well in my testing so far.
