### ISSUE TITLE
Duplicated Table Labels in LaTeX Output When Using Footnotes in Captions with pandoc-crossref

### ISSUE THREAD

**Issue by TomBener** [jgm/pandoc#9054]
#### Issue Description:

When converting Markdown tables with footnotes in their captions to LaTeX using Pandoc 3.1.7 along with the `pandoc-crossref` filter, I observe that duplicated labels are generated in the LaTeX output. This issue seems to manifest specifically when the table caption includes both a footnote and a label for cross-referencing.

#### Steps to Reproduce:

1. Create a Markdown file with a table that includes a random caption, a footnote, and a label:

    ```markdown
    :Sample Caption for Table[^1] {#tbl:RandomLabel}
    ```

2. Run the following shell script to convert the Markdown file to LaTeX:

    ```bash
    #!/bin/bash

    BAK_FILES="your_markdown_files_here.md"

    pandoc \
    --filter pandoc-crossref \
    --metadata tblPrefix="Table" \
    --biblatex \
    --output output.tex \
    $BAK_FILES
    ```

3. Inspect the generated `output.tex` file.

#### Expected Result:

A single label should be generated for each table, e.g.,

```tex
\caption[Sample Caption for Table]{Sample Caption for Table\footnote{Footnote text here.}}\tabularnewline
```

#### Actual Result:

Duplicated labels are generated for the table.

```tex
\phantomsection\label{tbl:RandomLabel}
\caption[\label{tbl:RandomLabel}Sample Caption for Table]{\label{tbl:RandomLabel}Sample Caption for Table\footnote{Footnote text here.}}\tabularnewline
```

#### Workarounds:

1. Removing the footnote from the caption resolves the issue but is not always a feasible solution.
2. Manual post-processing using `sed` can be employed to remove the extra labels, but this is not an ideal solution.

#### Additional Context:

- Pandoc version: 3.1.7
- Filter: pandoc-crossref
- Operating System: macOS

Related issue #9022

**Comment by jpcirrus** [comment]
See #9045 and lierdakil/pandoc-crossref#402

**Comment by jgm** [comment]
Could you provide a complete markdown snippet that suffices to reproduce this?

**Comment by TomBener** [comment]
@jgm I've uploaded a [zip file](https://github.com/jgm/pandoc/files/12508291/test.zip) which contains the source Markdown and generated LaTeX `test.tex` and `native` output `test.txt`.

The source Markdown:

```md
# Sample Document

See [@tbl:RandomLabel] for more details.

| Year   | Wool   | Cotton |
| ------ | ------ | ------ |
| 2020   | 1,129  | 33     |
| 2021   | 1,915  | 137    |
| 2022   | 3,411  | 1,577  |
  :Sample Caption for Table[^1] {#tbl:RandomLabel}

[^1]: This is a footnote explaining the table.
```

The command used were as follows:

```sh
# LaTeX
pandoc -F pandoc-crossref test.md -o test.tex

# Native
pandoc -F pandoc-crossref test.md -t native -o test.txt
```

It is noted that `pandoc-crossref` is needed to generate the correct table label. And the duplicated table label was reproduced:

```tex
\section{Sample Document}\label{sample-document}

See tbl.~\ref{tbl:RandomLabel} for more details.

\phantomsection\label{tbl:RandomLabel}
\begin{longtable}[]{@{}lll@{}}
\caption[\label{tbl:RandomLabel}Sample Caption for
Table]{\label{tbl:RandomLabel}Sample Caption for
Table\footnote{This is a footnote explaining the table.}}\tabularnewline
\toprule\noalign{}
Year & Wool & Cotton \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Year & Wool & Cotton \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2020 & 1,129 & 33 \\
2021 & 1,915 & 137 \\
2022 & 3,411 & 1,577 \\
\end{longtable}
```

```
$ pandoc --version
pandoc 3.1.7
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/username/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

$ pandoc-crossref -v
pandoc-crossref v0.3.16.0 git commit UNKNOWN (UNKNOWN) built with Pandoc v3.1.7, pandoc-types v1.23.1 and GHC 9.4.4
```

**Comment by jgm** [comment]
OK, looks like pandoc-citeproc is putting the table in a Div with id "tbl:RandomLabel".
But I'm confused about how the `label` is getting in there.
If I do `pandoc -f native -t latex test.txt` on your native file, I get this, which only has one label (on the `\phantomsection`), and no label in the caption...
```
\section{Sample Document}\label{sample-document}

See tbl.~1 for more details.

\phantomsection\label{tbl:RandomLabel}
\begin{longtable}[]{@{}lll@{}}
\caption[Table 1: Sample Caption for Table]{Table 1: Sample Caption for
Table\footnote{This is a footnote explaining the table.}}\tabularnewline
\toprule\noalign{}
Year & Wool & Cotton \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Year & Wool & Cotton \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2020 & 1,129 & 33 \\
2021 & 1,915 & 137 \\
2022 & 3,411 & 1,577 \\
\end{longtable}
```

**Comment by TomBener** [comment]
Yes, you're correct. But if run the command with `pandoc-crossref`:

```sh
pandoc -F pandoc-crossref -f native -t latex test.txt -o test.tex
```

The duplicated table label emerges:

```diff
\section{Sample Document}\label{sample-document}

See tbl.~1 for more details.

\phantomsection\label{tbl:RandomLabel}
\begin{longtable}[]{@{}lll@{}}
- \caption[Table 1: Sample Caption for Table]{Table 1: Sample Caption for
- Table\footnote{This is a footnote explaining the table.}}\tabularnewline
+ \caption[\label{tbl:RandomLabel}Table 1: Sample Caption for
+ Table]{\label{tbl:RandomLabel}Table 1: Sample Caption for
+ Table\footnote{This is a footnote explaining the table.}}\tabularnewline
\toprule\noalign{}
Year & Wool & Cotton \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Year & Wool & Cotton \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2020 & 1,129 & 33 \\
2021 & 1,915 & 137 \\
2022 & 3,411 & 1,577 \\
\end{longtable}
```

But without `pandoc-crossref`, the table label cannot be generated as expected. What a paradox…

**Comment by jgm** [comment]
OK, what I wanted was the native output produced *after* pandoc-crossref is run.
(I thought that was what you'd given me, but apparently not?)

**Comment by TomBener** [comment]
Nope. Actually, the zip file above contains the native output from markdown with `pandoc-crossref` loaded:

```
pandoc -F pandoc-crossref test.md -t native -o test.txt
```

**Comment by jgm** [comment]
> Nope. Actually, the zip file above contains the native output from markdown with pandoc-crossref loaded:

If that's so, then `pandoc test.txt -f native -t latex` should produce the same thing that you get with `pandoc test.md -t latex -F pandoc-crossref`. Apparently it does not . That's why I'm puzzled.

**Comment by jgm** [comment]
In any case, I don't see this as a problem with pandoc itself.  Pandoc can't avoid label clashes when external filters add their own raw LaTeX.

**Comment by TomBener** [comment]
@jgm Yes. It’s indeed not an issue of pandoc. Thanks.
