### ISSUE TITLE
Typst writer: distinguish between "code context" and "content context"?

### ISSUE THREAD

**Issue by cscheid** [jgm/pandoc#9062]
Take the writer for [Image](https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/Typst.hs#L281-L285) values as a working example.

**Describe your proposed improvement and the problem it solves.**

If I understand the Typst writer correctly, the output it emits always assumes the Image node exists in "content context", where the invocation of a function call needs to be preceded by a `#`. It would be useful if the writer could respond to an attribute that elided the `#` (producing `image("img/test.jpg")` instead of `#image("img/test.jpg")`), so we could use its writer code to emit output that is expected to appear inside other code context. (A custom implementation of subfigures is the actual driver of this request).

**Describe alternatives you've considered.**

We can currently work around this in Quarto by "prerendering" all of the nodes in "code contexts" via calls to `pandoc.write()`, removing the leading `#` from the resulting string and putting the output in a RawBlock, but it would be nice to have this supported more directly; I think other users of the Pandoc writer would benefit as well.

EDIT: Maybe this isn't worth the trouble and it might be easier to just insist that all output emitted by Pandoc exists surrounded by `[...]` whenever appropriate.

**Comment by jgm** [comment]
I like that last suggestion!

Code context would be tricky to make work for everything, I think.

**Comment by cscheid** [comment]
Noted. Thanks for listening in any case!
