### ISSUE TITLE
Incorrect symbol when converting markdown to typst

### ISSUE THREAD

**Issue by ninpnin** [jgm/pandoc#9063]
When converting markdown to typst, the binomial symbol is turned into a division. So

```markdown
${n\choose k}$
```

is turned into a division with parenthesis

```typst
$lr((n / k))$
```

while it should be

```
$binom(n,k)$
```

i.e. the [binomial expression](https://typst.app/docs/reference/math/binom/)

The command to run is 
```bash
pandoc binom-test.md -o binom-test.typ -t typst
```

The same thing happens on pandoc 3.1.6.2 and in the online interface.

**Comment by jgm** [comment]
texmath parses this as
```
[ EDelimited
    "("
    ")"
    [ Right (EFraction NoLineFrac (EIdentifier "n") (EIdentifier "k"))
    ]
]
```
but the NoLineFrac is ignored by the typst writer, apparently.
