### ISSUE TITLE
Recommendations for Installing Pandoc and Pandoc Python Libraries

### ISSUE THREAD

**Issue by yoonghm** [jgm/pandoc#9071]
To get started with Pandoc and its Python libraries, follow the instructions provided at https://boisgera.github.io/pandoc/getting-started/:

```bash
conda install -c conda-forge pandoc
pip install --upgrade pandoc
```

However, there are some considerations and potential issues to be aware of:

1. The first command assumes that the user has the Anaconda distribution installed. If you are not using Anaconda, this step may not be suitable.
2. The second command may lead to confusion if users have both Anaconda distribution and standard Python installed. It's important to be aware of potential conflicts.
3. Users may already have a working Pandoc executable, but its version might not be compatible with the Pandoc Python libraries. This could lead to compatibility issues, depending on the order of appearance of the Pandoc executable in the `PATH` environment variable.

**Proposals**

1. Conda-forge package should includes the latest and supported Pandoc executable binary and Pandoc Python libraries. This option is ideal for users with the Anaconda distribution installed.
2. PyPI package should include the latest and supported Pandoc executable binary and Pandoc Python libraries. This is a suitable choice for users who have only Python installed without Anaconda.

All these software components are supported and contributed to by individual developers. I am not aware on where, who and how to synchronize this efforts.

**Comment by jgm** [comment]
These suggestions should go to the respective python repositories. We have nothing to do with Python packaging here.
