### ISSUE TITLE
Pandoc doesn't correctly render the LaTeX document with documentclass=uspatent into DOCX

### ISSUE THREAD

**Issue by yurivict** [jgm/pandoc#9076]
**Explain the problem.**
[This LaTeX document](https://people.freebsd.org/~yuri/pandoc-test-doc.tex) is rendered into [this PDF](https://people.freebsd.org/~yuri/pandoc-test-doc.pdf) by the LaTeX software.

However, when Pandoc renders the same LaTeX document into DOCX - [the document](https://people.freebsd.org/~yuri/pandoc-test-doc.docx) is produced that has many differences with the above PDF document.

Differences and problems:
1. The title page and the empty page after it are missing.
2. Paragraph labels are missing.
3. The LaTeX expression ```$1946 \isep 1947$``` fails to render.
4. All section titles are missing.
5. The words "What is claimed:" are missing.

**Additional info**
The ```uspatent``` LaTeX documentclass is widely used by people who create US Patent applications using the LaTeX syntax and software to render LaTeX documents into PDF.

However, the US Patent and Trademark Office is in the process to discontinue PDF submissions in favor of DOCX submissions, which in their opinion is easier to handle, and to reformat into the final US Patent document.

It is important to keep LaTeX users being able to submit US Patent applications. Pandoc is a major way to convert LaTeX into DOCX. However, due to the above issues Pandoc fails to properly render LaTeX documents with documentclass=uspatent.

**Pandoc version?**
3.1.8
FreeBSD 13.2

**Comment by jgm** [comment]
I think this is out of scope.  Pandoc can't possibly support all of the thousands of packages on CTAN, and targets core LaTeX + some of the most common packages.

You could very likely improve things by including simplified definitions of some of the macros used in this document class, perhaps in another file that you put on the command line before your main tex file.  In this way you could make the title page and section titles work, as well as things like `\WhatIsClaimed`. As for `\isep`, it isn't recognized by texmath, but you could provide your own definition using `\newcommand`.

**Comment by yurivict** [comment]
```\isep``` is defined in the document using ```\newcommand```.

**Comment by yurivict** [comment]
> Pandoc can't possibly support all of the thousands of packages on CTAN, and targets core LaTeX + some of the most common packages.

All TeX/LaTeX packages do is they define new commands through other commands. Eventually, when all commands are expanded and interpreted every LaTeX document would use a small set of basic TeX commands. Pandoc needs to interpret package- and user-defined commands and then execute all resulting basic commands. Pandoc shouldn't try to support them package by package and needs to do no extra work to support new LaTeX packages.

**Comment by jgm** [comment]
As for `\isep`, this works fine for me:
```
% pandoc -o my.docx
\newcommand{\isep}{\alpha}
$$1946 \isep 1947$$
^D
```
So I'm not sure why it isn't working for you.  If you'd like, you can share your definition of `\isep`.

**Comment by yurivict** [comment]
The definition of ```isep``` is in the linked LaTeX document above:
> \newcommand{\isep}{\mathrel{{.}\,{.}}\nobreak}

**Comment by yurivict** [comment]
The ```uspatent``` class definition is [here](https://github.com/PetePupalaikis/uspatent).

**Comment by yurivict** [comment]
This problem pains me because it is immeasurably more difficult to type in a document with complex formulas into MS Word or Google Docs compared to just writing it in LaTeX. When someone requires DOCX for such cases - this only causes a lot of difficulties.

**Comment by jgm** [comment]
I certainly emphasize with the pain of dealing with docx.

For the `\isep` it looks like jgm/texmath does not understand `\nobreak`, and that is the issue. You can work around it by providing a dummy definition.
```
\newcommand{\nobreak}{}
\newcommand{\isep}{\mathrel{{.},{.}}\nobreak}
$a \isep b$
```

**Comment by jgm** [comment]
I'm going to close this as out of scope, but hopefully some of the strategies I've outlined may help you to get at least a partial translation.
