### ISSUE TITLE
Markdown bullet list not getting properly converted to latex without leading empty line

### ISSUE THREAD

**Issue by kraktus** [jgm/pandoc#9079]
Hello, thank you for you work, I'm coming from https://github.com/jupyter/nbconvert/issues/917. I've searched quite extensively with keywords because given the nature of the bug I assume there's already an issue opened somewhere but couldn't find it.

The issue is that markdown bullet lists are not getting properly converted to latex.

`test.md`
```md
Sentence
*   foo
*   foo
```
`pandoc test.md -o test.tex`

`test.tex`
```tex
Sentence * foo * foo
```

Note that by adding an empty line in between, it works properly
```md
Sentence

*   foo
*   foo
```
turns to 
```tex
Sentence

\begin{itemize}
\tightlist
\item
  foo
\item
  foo
\end{itemize}
```

Version:
```
pandoc 3.1.7
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/solal/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by cagix** [comment]
if i remember correctly, in markdown an empty line must precede a list. however, pandoc can achieve the desired effect by using the extra option `lists_without_preceding_blankline`: could you please give `pandoc -f markdown+lists_without_preceding_blankline test.md -o test.tex` a try?

**Comment by kraktus** [comment]
It works as expected with the custom filter, thanks. I'm not sure which markdown spec pandoc is following but I haven't been aware of a markdown editor not rendering list without a space.

**Comment by cagix** [comment]
> It works as expected with the custom filter, thanks. I'm not sure which markdown spec pandoc is following but I haven't been aware of a markdown editor not rendering list without an empty line.

hmmm, in https://pandoc.org/MANUAL.html#block-content-in-list-items it reads "... include other lists. In this case the **preceding blank line is optional**. The nested ...". also there is https://pandoc.org/MANUAL.html#extension-lists_without_preceding_blankline. but i could not find any explicit statement about the requirement of blank lines preceding bullet lists ... then again, if you search for the term "blank" in the manual, pandoc requires a blank line before quite a lot of things (headings, blockquotes, fenced code blocks, ...), presumably to ensure correct parsing. so it's a very consistent behaviour :)

**Comment by jgm** [comment]
Yes, confirming that this all works as documented.
Depending on the other features you need, you may want to try `-f commonmark` or `-f gfm` or `-f commonmark_x`, which would allow this list also.

**Comment by jgm** [comment]
https://pandoc.org/MANUAL.html#extension-lists_without_preceding_blankline

Many implementations now allow a bullet list to start without a blank line before it, but John Gruber's original Markdown.pl did not; there was even a test case for this.
