### ISSUE TITLE
Pandoc does not escape underscores in title for latex output

### ISSUE THREAD

**Issue by FSatCorp** [jgm/pandoc#9091]
Hello alltogether,

I'm using pandoc 3.1.7

When converting a file to PDF (e.g. Markdown to pdf via xelatex) and use --variable=title: or --variable=title-meta: command line arguments, the given values get unalteredly inserted into the tex file.

If the given title contains underscores, this leads to errors like 
```
Error producing PDF.
! Missing $ inserted.
<inserted text>
                $
l.78
```

Instead, pandoc should escape underscores like it does inside the tex body (\\_)

To reproduce, you can use the following commands:
```
touch test.md
pandoc test.md  --variable="title:test_doc" -o test.pdf
```

Greetings

**Comment by jgm** [comment]
This isn't a bug, but [as documented](https://pandoc.org/MANUAL.html#interpolated-variables):  variables are inserted literally (as opposed to metadata values, which are formatted in the target format).
