### ISSUE TITLE
Multiline table cells with no line breaks

### ISSUE THREAD

**Issue by ptram** [jgm/pandoc#9094]
Hi,

I deal with big tables, with multiline cells. These are usually descriptions of parameters or features.

The current solution for multiline cells is to manually break lines. This is not handy in case of editing or translation (with translation tools identifying broken lines as separate paragraphs).

My humble proposal is to use something starting from the grid table syntax, but allowing adjacent cells to be written into subsequent paragraphs. So, a table like this:

<img width="615" alt="image" src="https://github.com/jgm/pandoc/assets/19186065/03e360ad-9656-433c-9271-f3b52d0270af">

could be written like this:

```
+---
This is the first column's header
And this is the second column's header, much better than the one you can see here in the left column
This is just a value, in the third column
+===|===|===:|

This is the first parameter
And here we go on and on explaining what it does, and what it would be better you, the inconsiderate user, don't do or touch to avoid messing things up.
100%

This is the second parameter. Anything follows.
...
+---

: Table caption {tbl-colwidths="[20,70,10" .striped]
```

If the compiler (for example, Quarto) allows for it, a set of configuration parameters between curly brackets could be attached to the table caption, as shown in the above example.

Paolo

**Comment by jgm** [comment]
This might help you:
https://github.com/pandoc/lua-filters/tree/master/list-table

**Comment by ptram** [comment]
> This might help you:

That's it! It's even more elegant than my idea.

The fact that the direct link point to a deprecated feature means that it will be removed, or superseded by something other?

**Comment by jgm** [comment]
It's a third-party filter.  You may need to maintain it yourself if the creator is not.

**Comment by ptram** [comment]
Thank you for adding list tables to the supported features. And your syntax is faster than the one in the old filter.
