### ISSUE TITLE
Table caption not respected on wrapper 

### ISSUE THREAD

**Issue by blackjyn** [jgm/pandoc#9101]
**Explain the problem.**

I tried to convert MD table with additional with custom wrapper classes so it matched the Bootstrap's responsive table cosntruct:

```markdown
::: {.table-responsive}
{.table}
| Expense Category     | Amount ($)  |
|----------------------|-------------|
| Rent                 | 1,200       |
| Utilities            | 200         |
| Groceries            | 400         |
| Transportation       | 150         |
| Dining Out           | 100         |
| Entertainment        | 50          |
| Miscellaneous        | 75          |
| Total Monthly Budget | 2,175       |
:::
```

Compile:
`pandoc -f commonmark_x+attributes tbl_responsive.md -s -c ../css/bootstrap.min.css -t html5 -o tbl_responsive.html`

However , when I add table caption it is not respected and rendered to just plain `<p/>` paragraph:
```markdown
::: {.table-responsive}
{.table}
| Expense Category     | Amount ($)  |
|----------------------|-------------|
| Rent                 | 1,200       |
| Utilities            | 200         |
| Groceries            | 400         |
| Transportation       | 150         |
| Dining Out           | 100         |
| Entertainment        | 50          |
| Miscellaneous        | 75          |
| Total Monthly Budget | 2,175       |

: Sample Data
:::
```
Help?

**Pandoc version?**

Version **pandoc 3.1.8**

**Comment by jgm** [comment]
Nothing to do with the wrapper. The issue is that commonmark's pipe_table extension doesn't support pandoc caption syntax...  So you won't get a caption even without the wrapper.

You could request this on jgm/commonmark-hs

**Comment by blackjyn** [comment]
I can confirm ,  this  markup renders correctly with caption

```markdown
| Expense Category     | Amount ($)  |
|----------------------|-------------|
| Rent                 | 1,200       |
| Utilities            | 200         |
| Groceries            | 400         |
| Transportation       | 150         |
| Dining Out           | 100         |
| Entertainment        | 50          |
| Miscellaneous        | 75          |
| Total Monthly Budget | 2,175       |

: Sample Data
```

**Comment by jgm** [comment]
> I can confirm , this markup renders correctly with caption

No it doesn't.  It will work with `-f markdown` but not with `-f commonmark_x+attributes`.

**Comment by blackjyn** [comment]
> > I can confirm , this markup renders correctly with caption
> 
> No it doesn't.  It will work with `-f markdown` but not with `-f commonmark_x+attributes`.
> 

Oh my bad. Thank you @jgm . I have re tested and indeed didn't work:

[Sample](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5Cn%7C+Expense+Category+++++%7C+Amount+%28%24%29++%7C%5Cn%7C----------------------%7C-------------%7C%5Cn%7C+Rent+++++++++++++++++%7C+1%2C200+++++++%7C%5Cn%7C+Utilities++++++++++++%7C+200+++++++++%7C%5Cn%7C+Groceries++++++++++++%7C+400+++++++++%7C%5Cn%7C+Transportation+++++++%7C+150+++++++++%7C%5Cn%7C+Dining+Out+++++++++++%7C+100+++++++++%7C%5Cn%7C+Entertainment++++++++%7C+50++++++++++%7C%5Cn%7C+Miscellaneous++++++++%7C+75++++++++++%7C%5Cn%7C+Total+Monthly+Budget+%7C+2%2C175+++++++%7C%5Cn%5Cn%3A+Sample+Data%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22commonmark_x%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)
