### ISSUE TITLE
Enable/disable uncommon readers/writers using Cabal flags

### ISSUE THREAD

**Issue by wenkokke** [jgm/pandoc#9103]
**Describe your proposed improvement and the problem it solves.**
Pandoc supports _many_ input and output formats, and as such the package has _many_ dependencies. My suggestion is to add a series of on-by-default flags to enable/disable some of the less common formats, in an effort to limit the number of dependencies when Pandoc is used as a library or for specific build pipelines.

**Comment by jgm** [comment]
I don't think this would really help much; most of the dependencies are brought in by core, not by the individual readers/writers.

And it goes against a standard policy that flags should not change the exposed API.
