### ISSUE TITLE
pandoc-lua-engine pandoc lowerbounds

### ISSUE THREAD

**Issue by juhp** [jgm/pandoc#9111]
From my testing:

pandoc-lua-engine >= 0.2.1 requires pandoc >= 3.1.4 to build (this is currently (only) reflected in a revision of 0.2.1.2)

So I would like to suggest bumping the pandoc lowerbound to 3.1.4 for all current pandoc-lua-engine >= 0.2.1

If you wish I can help make those revisions as a Hackage Trustee.

(In particular this came up since pandoc-3.1.3 is the last version of pandoc before the transition to crypton (which will first appear fully in Stackage LTS 22), and so pandoc-3.1.3 is dependent on pandoc-lua-engine-0.2.0.1)

(**editted** to drop the incorrect suggestion to change the pandoc upperbound for pandoc-lua-engine-0.2.0.1)

**Comment by juhp** [comment]
Hmm actually I am able to build pandoc-lua-engine-0.2.0.1 with pandoc-3.1.6, so what I wrote about 0.2.0.1 seems inaccurate.

**Comment by juhp** [comment]
This should avoid this compilation failure with pandoc-3.1.3:
```
Building library for pandoc-lua-engine-0.2.1..
:
src/Text/Pandoc/Lua/Init.hs:29:29: error:
    Module
    ‘Text.Pandoc.Logging’
    does not export
    ‘LogMessage(ScriptingWarning)’
   |
29 | import Text.Pandoc.Logging (LogMessage (ScriptingWarning))
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jgm** [comment]
No objections - please go ahead and make the revision.

**Comment by juhp** [comment]
Okay revisions made for pandoc-lua-engine [0.2.1.1](https://hackage.haskell.org/package/pandoc-lua-engine-0.2.1.1/revisions/) and [0.2.1](https://hackage.haskell.org/package/pandoc-lua-engine-0.2.1/revisions/)
