### ISSUE TITLE
Incompatibility between Pandoc 3.1.8 and Eisvogel 2.4.1 with citeproc

### ISSUE THREAD

**Issue by mfhepp** [jgm/pandoc#9124]
**Explain the problem.**
The popular Eisvogel template 2.4.1 does not work with Pandoc 3.1.8 with `citeproc`, likely due to the issues addressed in https://github.com/jgm/pandoc/commit/b7e1ce422c9a76dffe763a4d31e0952e415775cc.  

As soon as references are processed by `citeproc`, the resulting TeX does not compile (at least with `texlive-full` on Debian bookworm):

```
Error producing PDF.
! LaTeX Error: Something's wrong--perhaps a missing \item.
```

The exact details and a reproducible minimal example are given in https://github.com/Wandmalfarbe/pandoc-latex-template/issues/361.

**Pandoc version?**
Pandoc 3.1.8 on Debian Bookworm.

It is likely that the issue needs to be fixed at the side of the Eisvogel template, as the default Pandoc LaTeX template works fine.
This issue is mainly for saving people effort and loss of hair who are running into the same problem.

**Comment by jgm** [comment]
Closing because it's an eisvogel issue.
