### ISSUE TITLE
LaTeX to GFM fails at \@setsize

### ISSUE THREAD

**Issue by shreykshah** [jgm/pandoc#9126]
Command: `pandoc -s iclr2023_conference.tex -o "../2203.04450.md" -t gfm --verbose`, with file [iclr2023_conference.tex](https://privatebin.net/?78ec69420fae7d1c#GX9VqdLG8gAcaxXw1agJfd4WqLY9RrbYo1uimEzDUZu2)

This seems to fail on my local pandoc install but work on the online pandoc version. When I run with the `--verbose` flag, it runs until it outputs `[INFO] Skipped '\@setsize' at iclr2023_conference.tex line 72 column 1` repeatedly until I kill the process. I have replicated this issue without the `-t` flag, with multiple different files, and on Linux (pandoc-3.1.8-linux-amd64), all of which infinite loop at the `\@setsize` command.

Pandoc version 3.1.8 on MacOS installed via Homebrew.

**Comment by jgm** [comment]
Note that this document does not contain `\@setsize` anywhere.
It must be coming in through the style you're importing with
```
\usepackage{iclr2023_conference}
```
If you can upload iclr2023_conference.sty we can take a further look.
This also explains why it didn't happen on the web version, which didn't have access to this style.

Note: pandoc's latex parser is not designed to parse low-level TeX, of the sort that many sty files contain. So this is probably out of scope.  You can also try to avoid the entire problem by removing the style file from the working directory when you run pandoc.

**Comment by shreykshah** [comment]
I'm happy to try to remove the sty files. Is there any option to bypass the sty files for future reference? I imagine converting latex to markdown doesn't require the sty files at all.

**Comment by jgm** [comment]
You could try setting TEXINPUTS not to include the working directory.
e.g.
```
TEXINPUTS=/tmp/nonexistent pandoc -f latex etc.
```
You could also simply comment out the line that includes it.
