### ISSUE TITLE
CSS stylesheet data is set to text/plain instead of text/css

### ISSUE THREAD

**Issue by gregory-james-smith** [jgm/pandoc#9143]
### Problem

When converting from markdown to HTML and including a CSS stylesheet, the data in the `link` tag is set to `text/plain` instead of `text/css` and the stylesheet is not picked up.

### Recreate

I ran the following command which pulls the CSS stylesheet using a URL:

```
pandoc --standalone --embed-resource \
  --css=https://path/to/stylesheet.css \
  -f markdown+mark+emoji+wikilinks_title_after_pipe \
  -t html \
  --output=output.html \
  input.md
```

It generates the following line in the HTML output:

```
<link href="data:text/plain; charset=utf-8;charset=utf-8, ..." rel="stylesheet" />
```

But I think it should generate the following line in the HTML output:

```
<link href="data:text/css; charset=utf-8;charset=utf-8, ..." rel="stylesheet" />
```

If I manually make this change to the HTML file then the CSS stylesheet works.

### Versions

The code was run in GitHub actions on `ubuntu-22.04`. I had the same issue with docker image `pandoc/extra:3.0.1` and `pandoc/extra:3.1.1`.

**Comment by jgm** [comment]
Have you tried downloading the css file and specifying `--css local-file.css`?  Does that give you a different result?

If so, then I think one possible explanation is that the webserver that is serving the css file is serving it with mime type text/plain.  Pandoc will take the mime type from the HTTP response if one is present.

You could test that by doing a request and looking at the response headers.

**Comment by gregory-james-smith** [comment]
If I curl the URL, I can see that the header `content-type` is `text/plain; charset=utf-8`. It is a little annoying that I cannot just use a URL to a CSS file without also needing to set the headers for how the CSS file is being served. However I suppose this is consistent with using raw HTML so I understand why.

I have managed to work around the problem by creating a step in my GitHub action to curl the CSS file into a local file and then set the pandoc script to reference the path to this file. Using a local file sets the CSS file into the pandoc generated HTML file as a `<style>` tag and works as expected.

**Comment by jgm** [comment]
If this is a common thing -- serving CSS as text/plain -- we could look into an ad hoc exception.
