### ISSUE TITLE
Would it be possible to have a converter from .doc files to .md . It would be extraordinarily helpful, as this brilliant tool unfortunately does .docx but not .doc.

Thank you very much for your work!

### ISSUE THREAD

**Issue by Francois-Rolland** [jgm/pandoc#9146]
**Describe your proposed improvement and the problem it solves.**

**Describe alternatives you've considered.**

**Comment by jgm** [comment]
I learned today that there is a published spec for doc format: https://msopenspecs.azureedge.net/files/MS-DOC/%5bMS-DOC%5d.pdf
So in principle it could be done.

Nonetheless, this would just be an enormous amount of work to implement.  And it is easy to convert from doc -> docx using Word or a free alternative like LibreOffice.  So I really don't think this is worth the effort.
