### ISSUE TITLE
Language for "Page" in Zotero cite (docx -> md)

### ISSUE THREAD

**Issue by estedeahora** [jgm/pandoc#9148]
**Explain the problem.**
I encounter an issue when transforming a text from word (docx) to markdown (md), when the original document has cites with page numbers. The cites are created with Zotero Word for Windows Integration. The problem is that I need the page number prefix to be translated into Spanish (e.g. "página" or "p."), instead of English ("page"). In a previous [issue](https://github.com/jgm/pandoc/issues/9116#issuecomment-1746093026) I mentioned this behaviour, but it was suggested that I could solve it with `lang` filed . However, I am trying different values for this field (I tried `es-ES`, `es-MX`, `es`), but I can't get it to switch languages correctly. 

I share a minimal example document that reproduces the problem and the file with the metadata ([test.zip](https://github.com/jgm/pandoc/files/13046908/test.zip)). 

The code I use is as follows:

```
pandoc +RTS -K512m -RTS test.docx --to markdown --from docx+citations --output test.md --metadata-file=./test_meta.yaml -s --citeproc 
```

As I said in the other issue, I think this is something that can be solved with a filter, but perhaps it could be supported.

Thanks!

**Pandoc version?**
Pandoc 3.1.8

**Comment by jgm** [comment]
When you convert this to markdown you get
```
[@21909, page 23 ]
```
The "page 23" will be recognized as a page locator, but only if your metadata `lang` is English (`en`).  If it's Spanish, then pandoc will want to see `página` or just `p.`.

So, no, it won't work to have the locator use the English word `page` but set the `lang` to `es`.

**Comment by estedeahora** [comment]
OK. Now I understood the expected behaviour. To give context, my workflow is docx -> md -> (latex) -> pdf. I also use a custom csl (which incorporates the Spanish words directly). So, if I set the language to `en` and give this csl the result in the pdf is as I would expect (i.e.: "(Weber, 2002, p. 23)"). The problem is that now the pdf is set to English. I think the solution then is to use a filter that modifies this in the pass docx -> md. 

Thanks again for your work. Pandoc is simply brilliant (even if it sometimes gives me some headaches!).

**Comment by jgm** [comment]
I think this can now be closed.  I understand the problem but I don't see a clean solution.
