### ISSUE TITLE
Pandoc 3.1.8 - contrary to manual, raw attributes do not work for roff

### ISSUE THREAD

**Issue by odkr** [jgm/pandoc#9152]
I am writing a man page using Pandoc. However, Pandoc doesn't handle the indentation of the synopsis section the way I want, so I tried to include raw roff code (namely, `.IP \f[B]command\f[R] 8`). However, contrary to what the section "[Extension: raw_attribute](https://pandoc.org/MANUAL.html#extension-raw_attribute) of the manual suggests, Pandoc complains that raw attributes are supported neither for the *ms* nor for the *man* output format.

```
$ pandoc -fmarkdown -tman+raw_attribute /dev/null
The extension raw_attribute is not supported for man
$ pandoc -fmarkdown -tms+raw_attribute /dev/null
The extension raw_attribute is not supported for ms
```
I am using Pandoc 3.1.8 on macOS 14.0.

Thanks for looking into this.

**Comment by jgm** [comment]
`raw_attributes` is a markdown extension. You want:
```
pandoc -f markdown+raw_attributes -t man
```
But actually you don't need the `+raw_attributes` because it's enabled by default for `markdown`.

**Comment by odkr** [comment]
I thought I might have missed something. But I just couldn’t figure out what it was 🤦. Thanks for clearing that up!
