### ISSUE TITLE
citeproc not generating bibliography when declared as part of the YAML metadata

### ISSUE THREAD

**Issue by GarciaBarreiro** [jgm/pandoc#9157]
**Explain the problem.**

Adding `citeproc: true` to the YAML metadata of a MarkDown file does not generate a bibliography after executing `pandoc file.md -o file.pdf`, but executing `pandoc file.md -o file.pdf --citeproc` does and, as far as I know, the first option should also work.

**Pandoc version?**

I managed to reproduce this issue in the latest Pandoc version (3.1.8).

**Example**

Using `pandoc file.md -o file.pdf` on the simple test below just generates a PDF that says *test [@ id123]*, but adding the `--citeproc` option adds the bibliography.

```
---
references:
  - id: id123
    title: Some Title
    author: Some Guy
citeproc: true
---

test [@id123]
```

**Comment by jgm** [comment]
Not a bug.  `--citeproc` is a command line option, not something you can trigger via metadata.
You can, however, use a defaults file (see the manual).

**Comment by iandol** [comment]
@GarciaBarreiro — the ability to pass command-line flags as part of the YAML metadata has been a long-standing wish for some of us: #4627 which led to #5870 — defaults files currently still require a separate file and explicit command-line configuration, which #5870 may address…
