### ISSUE TITLE
\citeproc command still used when link-citations is true, but suppress-bibliograpy as been opt-in 

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#9163]
First reported at https://github.com/quarto-dev/quarto-cli/issues/7439

This happens since 3.1.7 

Take this example 
````markdown
---
title: test
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for
    deoxyribose nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
link-citations: true
suppress-bibliography: true
--- 

See @WatsonCrick1953 for additional discussion
````

````powershell
> pandoc -f markdown -t latex -s --citeproc -o test.pdf test.qmd
Error producing PDF.
! Undefined control sequence.
l.61 See Watson and Crick (\citeproc
````

This happens because the citation line is produced using the citation command even is `suppress-bibliography` is true. 
````latex
See Watson and Crick (\citeproc{ref-WatsonCrick1953}{1953}) for
````
But in that case the command definition is not inserted in template. 

Previously, 
````powershell 
pandoc -f markdown -t latex -s --citeproc -o test.tex test.qmd
````
it was producing this line instead 
```latex
See Watson and Crick (\protect\hyperlink{ref-WatsonCrick1953}{1953}) for
```

I recognized it is not that useful to set `link-citations: true` and `suppress-bibliography: true`, though it did not through that an error before. 

And this may be the hint of another type of issue maybe. 

Anyhow, this should probably be fixed by not emitting `\citeproc` when `csl-refs` variable will opt-out the command definition in the template
https://github.com/jgm/pandoc/blob/d3d0406515cb6aae6f43e60dfa37014bdd91e79c/data/templates/default.latex#L337-L341

Hope it helps

**Comment by jgm** [comment]
We can modify Citeproc so that the links are not added if suppress-bibliography is specified.

**Comment by jgm** [comment]
I suppose you could create the bibliography and use a subsequent Lua filter to remove it (remove the Div with id refs).
