### ISSUE TITLE
Add markdown+tex_math_single_backslash to try.pandoc

### ISSUE THREAD

**Issue by Kreijstal** [jgm/pandoc#9169]
**Describe your proposed improvement and the problem it solves.**
ChatGPT now prefers tex_math_single_backslash  rather than the usual \$ and \$$, maybe we should support that on the web interface?

**Describe alternatives you've considered.**
a regex that checks \( and \) lol

**Comment by jgm** [comment]
It's supposed to be AI; I say, let it figure out how to do the right thing if it wants to use pandoc.
