### ISSUE TITLE
Invalid link format between markdown and automatically generated one

### ISSUE THREAD

**Issue by FirelightFlagboy** [jgm/pandoc#9174]
**Explain the problem.**

1. I've the following markdown file:
   
   ```markdown
   - [foo \& bar](#foo--bar)

   # Foo & Bar

   foo and bar
   ```

2. I convert the markdown to either `typst` or `html`, I get the following outputs:

   Typst: 

   ```typst
   - #link(<foo--bar>)[foo & bar]

   = Foo & Bar
   <foo-bar>
   foo and bar
   ```

   Html:

   ```html
   <ul>
   <li><a href="#foo--bar">foo &amp; bar</a></li>
   </ul>
   <h1 id="foo-bar">Foo &amp; Bar</h1>
   <p>foo and bar</p>
   ```

   > Notice here the ID of the link for the section `Foo & Bar` is `foo-bar`.

I've a problem with markdown with a title that contain some _special_ characters (`&` in this case) where I want to create a Table Of Content (TOC).

In markdown the ID for the heading `Foo & Bar` is `foo--bar` (observed on `vscode` & `github`) so I've used that ID to create the TOC.

But when converting the markdown to either `typst` or `html` (I did not test other outputs format) the generated link ID differ from the markdown ID (`foo-bar` vs `foo--bar`).

I would expected that the generated ID to be the same to the markdown one (both using `foo--bar`).

**Pandoc version?**

Pandoc version:

```
pandoc 3.1.9
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /root/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Typst version: 0.9.0

OS: Alpine Linux 3.18.2

**Comment by jgm** [comment]
> In markdown the ID for the heading Foo & Bar is `foo--bar` (observed on vscode & github)

There is no single standard for generating automatic ids in markdown. Pandoc does it differently from GitHub by default, but if you use `-f gfm` or `-f markown+gfm_auto_identifiers`, GitHub's scheme will be used.

**Comment by FirelightFlagboy** [comment]
Thank you @jqm, using `markdown+gfm_auto_identifiers` does the trick (complete list of [markdown variant](https://pandoc.org/MANUAL.html#markdown-variants)).

So I will close this issue as it is resolved.
