### ISSUE TITLE
`latex` `description` list diverges with `latex` → `commonmark` → `latex`

### ISSUE THREAD

**Issue by dbitouze** [jgm/pandoc#9179]
**Explain the problem.**
The conversion of a description list from `latex`:

```latex
\documentclass{article}
\begin{document}
\begin{description}
\item[Term:] definition
\end{description}
\end{document}
```

to `commonmark` [gives](https://try.pandoc.org/?params=%7B%22text%22%3A%22%5C%5Cdocumentclass%7Barticle%7D%5Cn%5C%5Cbegin%7Bdocument%7D%5Cn%5C%5Cbegin%7Bdescription%7D%5Cn%5C%5Citem%5BTerm%3A%5D++definition%5Cn%5C%5Cend%7Bdescription%7D%5Cn%5C%5Cend%7Bdocument%7D%5Cn%22%2C%22to%22%3A%22commonmark%22%2C%22from%22%3A%22latex%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D):
```md
Term:  
definition
```

But the other way round [doesn't give](https://pandoc.org/try/?params=%7B%22text%22%3A%22Term%3A++%5Cndefinition%22%2C%22to%22%3A%22latex%22%2C%22from%22%3A%22commonmark%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D) the initial `latex` description list:
```latex
Term:\\
definition
```

**Pandoc version?**
- `pandoc` 3.19
- GNU/Linux

**Comment by jgm** [comment]
That's because commonmark doesn't have a dedicated syntax for description lists.

Try with `commonmark+definition_lists`.
