### ISSUE TITLE
HTML → org mode: <br> converted to '\\'

### ISSUE THREAD

**Issue by andruska** [jgm/pandoc#9180]
HTML is taken from Evernote ENEX export.

```
$ cat Test.html 
<div>Lorem ipsum dolor sit amet, consectetur
adipiscing elit</div>
<div><br></div>
<div>sed do eiusmod tempor incididunt</div>
<div>1. ut labore</div>
<div>2. et dolore</div>
<div><br></div>
<div>magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip</div>
<div><b><br></b></div>
<div><b>ex ea commodo consequat. Duis aute
irure</b> dolor in reprehenderit in voluptate velit esse cillum dolore
eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 
proident,</div>
<div><br></div>
<div>sunt in culpa qui officia deserunt 
mollit anim id est laborum.</div>
```

In browser it looks correctly like:
/---
Lorem ipsum dolor sit amet, consectetur adipiscing elit

sed do eiusmod tempor incididunt
1. ut labore
2. et dolore

magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip

**ex ea commodo consequat. Duis aute irure** dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,

sunt in culpa qui officia deserunt mollit anim id est laborum.
/---

`$ pandoc --wrap=none -f html+empty_paragraphs-native_divs-native_spans -t org -o Test.org Test.html`

```
$ cat Test.org 
Lorem ipsum dolor sit amet, consectetur adipiscing elit
\\
sed do eiusmod tempor incididunt
1. ut labore
2. et dolore
\\
magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
*\\
*
*ex ea commodo consequat. Duis aute irure* dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
\\
sunt in culpa qui officia deserunt mollit anim id est laborum.
```
I think, `\\` is not needed outside paragraph and at the beginning of the line.

**Comment by jgm** [comment]
Not needed in what sense? The input says to put a `<br>` here. It does not say that we have a new paragraph.  If we left the line blank it would signify a new paragraph, which is semantically different.

**Comment by andruska** [comment]
`Paragraphs are separated by at least one empty line. If you need to enforce a line break within a paragraph, use ‘\\’ at the end of a line.`
Original Reference: [Paragraphs The Org Manual](https://orgmode.org/manual/Paragraphs.html)

`<br>` in that HTML sample represents that required empty line that separates the paragraphs. Pandoc apparently interprets it as a paragraph (`<div>` block) whose only content is a line break (`<br>`) at the end of a empty line. In the context of org mode, the '\\\\' is redundant there.

**Comment by jgm** [comment]
Paragraphs in HTML are indicated with `<p>`.  If you use `<br>`, it means you want a line break *within* a paragraph.
