### ISSUE TITLE
Ordered task lists seem to work by mistake

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#9185]
```
1. [X] item
2. [ ] item
```

This will render as an ordered task list in docx and html, and an unordered task list in LaTeX/PDF.

I don't think we ever intended to support ordered task lists.  @tarleb do you recall any discussion of this?

In any case this feature should either be documented/improved or removed.

See: https://talk.commonmark.org/t/ordered-task-list/4532

**Comment by tarleb** [comment]
> @tarleb do you recall any discussion of this?

No, none comes to mind.

My preference would be to remove the feature.
