### ISSUE TITLE
Typst citations are failing

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#9188]
There have been some changes to citations and bibliographies in Typst (including CSL support that requires a new template, see #9186). At present trying convert from Pandoc markdown to Typst using Typst native citations results in the following error:

```
▶︎ pandoc -s --bibliography test.bib --to typst -o out.typ 
# Title

Some text [@siegel2015]. More text.

▶︎ typst compile out.typ
error: expected label, found string
   ┌─ out.typ:99:16
   │
99 │ Some text #cite("siegel2015"). More text.
   │                 ^^^^^^^^^^^^

Exception: typst exited with 1
```

The document bit looks like:

```typst
= Title
<title>
Some text #cite("siegel2015"). More text.

#bibliography("test.bib")
```

For #cite() to work according to https://typst.app/docs/reference/meta/cite/ it needs to be: `#cite(<siegel2015>)` or `#cite(label("siegel2015"))` — manually editing out.typ to that format and it compiles just fine.

At present citations still seem quite basic, no locators etc. so I suspect more will change but at least this small change will fix current conversions.

**Comment by jgm** [comment]
OK.  We don't yet officially support the latest version of typst -- I can't keep up with the changes there.  Do you happen to know if using `#cite(label("id"))` is backwards-compatible with typst 0.7?

**Comment by jgm** [comment]
I answered my own questions. The changelog for 0.9 says it's a breaking change that cite takes a label rather than a string.  And I saw your other PR for the template.

**Comment by iandol** [comment]
Yes, it is a breaking change, and indeed Typst is still a fast-moving target 🚅  

> The [cite](https://typst.app/docs/reference/meta/cite/) function now takes only a single label/key instead of allowing multiple. Adjacent citations are merged and formatted according to the citation style's rules automatically. This works both with the reference syntax and explicit calls to the cite function. (Breaking change)
https://typst.app/docs/changelog/

The other breaking change is the way multiple citations work, it seems you must pass `#cite(<label>)#cite(<label2>)`

**Comment by iandol** [comment]
Confirmed fixed in nightly, thanks @jgm!
