### ISSUE TITLE
[Bug] Markdown-> Typst: Does not support html img tags

### ISSUE THREAD

**Issue by nc-x** [jgm/pandoc#9190]
Input Markdown File: `t.md`
```
image 1

<img src="https://avatars.githubusercontent.com/u/43749640?v=4"/>

image 2

![](https://avatars.githubusercontent.com/u/43749640?v=4)
```

Pandoc Command: `pandoc -f gfm -t typst t.md -o t.typ`

Output Typst File `t.typ`:
```
image 1

image 2

#box(width: 420.0pt, image("https://avatars.githubusercontent.com/u/43749640?v=4"))
```

**Comment by jgm** [comment]
Raw HTML in markdown is parsed as just that -- raw HTML -- and passed through literally to formats that accept raw HTML. It is never parsed as a native element (here, Image) that could be converted to different formats.

Use native markdown image syntax if you want it to convert to other formats.

**Comment by nc-x** [comment]
1. the markdown is not handwritten. it is converted from html, and pandoc leaves the img tag as it is if it has attributes instead of converting it to markdown image syntax. is there any way to force the conversion here?
2. if the output format doesn't support html tags, is there a way to just add it there as text instead of silently skipping it?
3. is there a way to get warnings when element is being skipped?

[note: i have a filter for removing the image attributes for 1, and i also have a filter to convert RawInline/RawBlock html img tags to native image tags while converting from html to typst so i am looking for inbuilt pandoc ways here especially for 3]

**Comment by jgm** [comment]
> the markdown is not handwritten. it is converted from html, and pandoc leaves the img tag as it is if it has attributes instead of converting it to markdown image syntax. is there any way to force the conversion here?

`pandoc -f markdown` should convert images with attributes to native markdown with pandoc attribute syntax.  Perhaps you're using `-f gfm` -- gfm doesn't support a native attribute syntx.

> if the output format doesn't support html tags, is there a way to just add it there as text instead of silently skipping it?

You could use a simple Lua filter to match RawInline "html" elements and convert them to something else.  I guess you have that already?

> is there a way to get warnings when element is being skipped?

`--verbose`

**Comment by nc-x** [comment]
>  Perhaps you're using -f gfm -- gfm doesn't support a native attribute syntx.

Yes, I was using gfm, will try using markdown later and see if everything else works fine for my use case or not.

> You could use a simple Lua filter to match RawInline "html" elements and convert them to something else. I guess you have that already?

Yeah, i have a filter for this. My main use case for opening this issue was to simplify my pandoc build system which is pretty complicated at the moment due to limitations in support for different file formats in pandoc. For example, I have to do several intermediate translations (example: `html -> markdown/gfm` does not support `--embed-resources` so I have to do `html -> html -> markdown/gfm (translating to gfm does work now, although afaict github doesn't support displaying such images)` because html -> html does support `--embed-resources`), run `sed` to cleanup some of the intermediate outputs (a lot of which can technically be done through filters but i was trying to minimize that), and additionally use a few filters (because too much sed was ugly and unreadable). 

But i guess a lot of what i want is out of scope for Pandoc, so i will have to rethink how to simplify the setup.

`--verbose`

Thanks, will try using this.
