### ISSUE TITLE
inline math followed by digit doesn't render correctly `$x$1`

### ISSUE THREAD

**Issue by nschloe** [jgm/pandoc#9192]
Markdown:

```markdown
$a$ $x$1
```

```
pandoc a.md -o out.html --katex --standalone
```

Screenshot:

![screenshot_2023-11-15-120529](https://github.com/jgm/pandoc/assets/181628/565d7fd7-10cd-43fb-89d9-9b1db16bedee)

This is with

```
pandoc --version
```
```
pandoc 3.1.5
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/nschloe/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
This isn't a bug.  See [the manual](https://pandoc.org/MANUAL.html#extension-tex_math_dollars).

> The opening $ must have a non-space character immediately to its right, while the closing $ must have a non-space character immediately to its left, and must not be followed immediately by a digit.

This is to prevent unwanted capture of `$` used as a dollar sign in text.

**Comment by jgm** [comment]
You could insert a zero-width space between the `$` and the `1` to handle this case.

**Comment by nschloe** [comment]
Ah makes sense, thanks for the swift reply!
