### ISSUE TITLE
Make bibliographystyle configurable when using natlib

### ISSUE THREAD

**Issue by nougad** [jgm/pandoc#920]
only this small patch in default.latex:

```
--- a/default.latex
+++ b/default.latex
@@ -38,7 +38,11 @@ $if(geometry)$
 $endif$
 $if(natbib)$
 \usepackage{natbib}
-\bibliographystyle{plainnat}
+$if(biblio-style)$
+\bibliographystyle{$biblio-style$}
+$else$
+\bibliographystyle{plainnat}
+$endif$
 $endif$
 $if(biblatex)$
 \usepackage{biblatex}
```

**Comment by katrinleinweber** [comment]
Hello and thanks for implementing this! How does one now find out which `biblio-style` options pandoc offers? I tried some that are listed in [natbib's CTAN docu](http://ftp.uni-erlangen.de/ctan/macros/latex/contrib/natbib/natbib.pdf), but only the most basic ones were found.

**Comment by KurtPfeifle** [comment]
You may want to have a look at my GitHub repository where I keep my private
citation style testing suite:

   - https://github.com/KurtPfeifle/pandoc-csl-testing

However, it is *not* using natbib, but the Pandoc command line
parameters --csl=whatever-file.csl
--biblio=some-biblio.bib --filter=pandoc-citeproc.

CSL is for *Citation Style Language
<http://en.wikipedia.org/wiki/Citation_Style_Language>*. Here is a GitHub
repository containing more than 1200 different citation styles maintained
by citationstyles.org:

   - https://github.com/citation-style-language/styles-distribution

The README in my CSL testing repo provides hopefully clear instructions how
to get it all working. (If this is not the case for you, please let me know
where/how I can improve it.)

Alternatively you can see preview of the various CSL styles here:

   - https://www.zotero.org/styles/

Visit the Zotero site with a modern browser and hover with the mouse
pointer over a style’s name. A preview window will open after a few seconds
on top of your main browser window, showing how the style renders in HTML.
Pandoc’s output with PDF(Latex) is the same.

The method used by me, as I said, doesn’t use --natbib. I never looked into
--natbib after I got the --biblio=... --csl=... --filter=pandoc-citeproc
method work so nicely for me.
​

**Comment by katrinleinweber** [comment]
OK, thanks for the advice! Such a set-up is already working for me ;-) Natbib seemed to provide nicer hyperlinking of in-text citations to the reference list, but if that comes at the cost of style customisability, I'll stick to `--csl`.
