### ISSUE TITLE
Improper parsing of nested quotes

### ISSUE THREAD

**Issue by VulpineAmethyst** [jgm/pandoc#9211]
**Explain the problem.**
Using the sample file `nested-quotes.md`, whose contents are:
```markdown
---
title: Nested Quotes
---
This is a paragraph which "contains a "nested" quote sequence." Are spaces being consumed?
```
and using the command
```sh
$ pandoc -f markdown -t html -o nested-quotes.html nested-quotes.md
```
I see the following output:
```html
<p>This is a paragraph which “contains a”nested” quote sequence.” Are
spaces being consumed?</p>
```

**Pandoc version?**
pandoc 3.1.9 as shipped by Homebrew on macOS 13.4.1

**Comment by jgm** [comment]
It's a little easier to see the issue from this:
```
% pandoc -f markdown -t native
"contains a "nested" quote"
^D
[ Para
    [ Quoted DoubleQuote [ Str "contains" , Space , Str "a" ]
    , Str "nested\8221"
    , Space
    , Str "quote\8221"
    ]
]
```
Desired output would be:
```
[ Para
    [ Quoted DoubleQuote
      [ Str "contains" , Space , Str "a" , Space ,
        Quoted DoubleQuote [Str "nested"] , Space  , Str "quote" ]
    ]
]
```

**Comment by VulpineAmethyst** [comment]
This appears to be specifically a problem with the `smart` extension, as I observe with `markdown-smart` that the output doesn't consume whitespace. But yes, I would agree with that.

**Comment by VulpineAmethyst** [comment]
It's not specific to double-quotes, either: `'contains a 'nested' quote'
` produces ```
[ Para
    [ Quoted
        SingleQuote
        [ Str "contains"
        , Space
        , Str "a"
        , Space
        , Str "\8217nested"
        ]
    , Space
    , Str "quote\8217"
    ]
]
```

**Comment by jgm** [comment]
This goes back to a decision made in 2007, in commit 1645fb65e4a486de95f5375bcc029a139d4d8c45

**Comment by jgm** [comment]
It's not easy to fix this without messing up other cases, and because you're not supposed to nest quotes this way (you should put double quotes within single, and vice versa) I'm inclined to leave it as it is.

You can always use unicode curly quotes if you really want to nest double quotes directly within double quotes.

Note that this works fine:

```
'double "within single" quotes'

"single 'within double' quotes"
```
