### ISSUE TITLE
Pandoc doesn't see style sheet in the same directory as input file?

### ISSUE THREAD

**Issue by jsx97** [jgm/pandoc#9212]
I want to convert "input.md" to "output.html" using my own "style.css" which is in the same directory as the input file. Here's what I tried:

```
pandoc input.md -o output.htm -s --data-dir="./" --template="style.css" --toc=true
```

But Pandoc says "Could not find data file templates/style.css" so it seems like it is trying to find "style.css" somewhere else, despite I explicitly defined the current folder. Is it a bug or what?

**Comment by jgm** [comment]
Pandoc first looks for a template in the working directory, and only goes to data directory if it's not found there.  So it should find style.css if it's in the working directory.  Note that if it looks in the data directory, it will look in the templates subdirectory of the data directory -- hence if data-dir is `.`, it looks for `./templates/style.css`.

**Comment by jsx97** [comment]
And it seems to change the working dir, I need to use `curdit` in the document itself. But is it possible to set working directory from the command-line tool?

**Comment by jgm** [comment]
The working directory is just the directory from which you issue the pandoc command.  You can change it with `cd` of course, prior to running pandoc.

By the way: a css file will not work as a pandoc template.
Please see the manual under Templates.
