### ISSUE TITLE
Space is incorrectly considered non-breakable

### ISSUE THREAD

**Issue by schaeferpp** [jgm/pandoc#9213]
When parsing a markdown document containing a line like

`test c. {#foo}`

pandoc inserts a non-breakable space 0xa0 between the period and opening brace.

I tested the following document

    ```
    title: test
    ```
    
    test c. {#foo}
    
    
    col col
    --- ---
    a   b
    
    Table: c. {#bar}
    

With the following Lua filter:

    function Pandoc(doc)
        print(doc)
        return doc
    end

In both lines (table caption and paragraph), a single `Str "c.\160{#foo}"` respectively `Str "c.\160{#bar}"` is generated. This breaks the [tablenos](https://github.com/tomduck/pandoc-tablenos)  filter in some weird cases.

The pandoc command line used is:

    pandoc --lua-filter filter.lua -t latex -s -o test.tex test.md

Is this a bug or intended behaviour?

**Pandoc version**
I tested this with:

- $ pandoc --version
  pandoc 3.1.5
  Features: +server +lua
  Scripting engine: Lua 5.4
- $ pandoc --version
  pandoc 2.17.1.1
  Compiled with pandoc-types 1.22.2.1, texmath 0.12.4, skylighting 0.12.3.1,
  citeproc 0.6.0.1, ipynb 0.2
  User data directory: /home/ubuntu/.local/share/pandoc
  Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
  This is free software; see the source for copying conditions. There is no
  warranty, not even for merchantability or fitness for a particular purpose.

**Comment by jgm** [comment]
It's treating `c.` as an abbreviation. Pandoc tries to recognize abbreviations and inserts a nonbreaking space after, instead of a potentially sentence-ending space. This makes a difference for a number of output formats.

```
pandoc --print-default-data-file abbreviations 
```
will print the abbreviations.

Easiest way to defeat this is to backslash-escape the period.

**Comment by schaeferpp** [comment]
Incredible, thank you very much for your quick response. I really didn't think of an abbreviation feature.
