### ISSUE TITLE
[LaTeX] Allow `UpperAlpha` and `LowerAlpha` to accept values greater than 26

### ISSUE THREAD

**Issue by fsoedjede** [jgm/pandoc#9219]
## Describe your proposed improvement and the problem it solves.

Since the `\Alph` and `\alph` counter are represented alphabetically, more than 26 items will trigger an error. We can prevent this using the [alphalph](http://www.ctan.org/pkg/alphalph) package.

Used here: https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/LaTeX.hs#L499

Exemple: https://tex.stackexchange.com/questions/268615/does-subsections-have-limit-in-the-ieeetran-document-class

## Describe alternatives you've considered.

Change the structure of the document

**Comment by jgm** [comment]
I prefer to limit the number of package the default template relies on.  In this case, you could use a custom template that imports this package.

**Comment by fsoedjede** [comment]
@jgm I understand

Using a custom template, the current LaTeX will still generate `\Alph` and `\alph` where I want to have `\AlphAlph` and `\alphalph`.

Is there a way to change this without generating the complete latex output with a lua filter?

**Comment by jgm** [comment]
Can't you simply redefine the `\Alph` and `\alph` macros in the template?
