### ISSUE TITLE
Trivial docx writer does not work in combination with pandoc.mediabag

### ISSUE THREAD

**Issue by svenboulanger** [jgm/pandoc#9229]
I'm trying to combine a custom writer and a lua filter that adds images to the mediabag. For `docx` output it doesn't seem to work. I'm using pandoc 3.1.9.

The writer `writer.docx.lua` is a trivial use case:
```lua
function ByteStringWriter(doc, opts)
    return pandoc.write(doc, "docx", opts)
end
```

The filter `ref.lua` will add a single SVG image to the mediabag (other types of images also fail):
```lua
function Pandoc(p)
    pandoc.mediabag.insert("a.svg", "image/svg+xml", "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"100\" width=\"100\">\n  <circle cx=\"50\" cy=\"50\" r=\"40\" stroke=\"black\" stroke-width=\"3\" fill=\"red\"></circle>\n</svg>")
    return p
end
```

The markdown input file, `example_test.md`:
```md
![a.svg](a.svg)
```

The following line will export the image correctly to the DOCX:
```
pandoc example_test.md --lua-filter ref.lua -o example_test.docx
```

The following line will fail to find `a.svg`, and the image does not show up in the DOCX:
```
pandoc example_test.md --lua-filter ref.lua -t writer.docx.lua -o example_test.docx
```

Pandoc returns the following warning:
```
[WARNING] Could not fetch resource a.svg: PandocResourceNotFound "a.svg"
```

If the image exists on my drive, then the warning is not generated and the image can be found whether or not I use the trivial writer.
The expected behavior is that the trivial pandoc writer should behave identical to the default writer.

[edit] It looks to me like the mediabag is emptied if `pandoc.write` is used. If this is the intended behavior, then how can I keep the contents of the mediabag from previous filters?
[edit 2] I also tried listing the contents of the mediabag inside the custom writer, and it doesn't list my mediabag items when the ByteStringWriter is called. It appears that my mediabag gets lost when the custom writer gets invoked?

**Comment by jgm** [comment]
@tarleb is the expert on this - hopefully he can comment.

**Comment by jgm** [comment]
What happens when you read a docx with media and then use a trivial custom writer that just prints the media bag?  Do you then see media?

**Comment by jgm** [comment]
I'm asking that you read a docx (not md) that contains media, and see if the custom writer can see media in a media bag.  (I expect it won't, but I wanted to make sure.)  (Maybe you did this, but your last comments made me think you were reading md.)

**Comment by tarleb** [comment]
Thanks for the report. The root cause for this behavior is that, for various reasons, we load the custom writer long before we actually run it. But the mediabag is set when the file is loaded, so all later changes to the mediabag were not visible to the writer. I've created a PR that fixes this by updating the internal state of the Lua engine right before the `ByteStringWriter` function get's executed.

Note that a different issue remains: pandoc does not create fallback PNG images when using a custom writer, so using SVGs doesn't work as expected. The fallback PNGs would have to be generated by the custom writer.
