### ISSUE TITLE
metadata fields in --defaults override front matter metadata fields

### ISSUE THREAD

**Issue by sxlijin** [jgm/pandoc#9237]
Metadata from `--metadata-file` is overridden by front matter fields, as I expect, so I think that means it's probably a bug for metadata from `--defaults` to be overriding front matter fields.

Actual behavior:

```
$ ~/pandoc-3.1.9/bin/pandoc --defaults defaults.yaml --template template.html --from gfm --to html --standalone lorem-ipsum.md
<fizzbuzz>default fizz buzz</fizzbuzz>
<body><p>Lorem ipsum dolor sit amet.</p></body>
```

Expected behavior:

```
$ ~/pandoc-3.1.9/bin/pandoc --defaults defaults.yaml --template template.html --from gfm --to html --standalone lorem-ipsum.md
<fizzbuzz>front matter fizz buzz</fizzbuzz>
<body><p>Lorem ipsum dolor sit amet.</p></body>
```

Contents of the files are as follows:

* defaults.yaml

    ```
    metadata:
      fizzbuzz: default fizz buzz
    ```

* template.html

    ```
    <fizzbuzz>$fizzbuzz$</fizzbuzz>
    <body>$body$</body>
    ```

* lorem-ipsum.md

    ```
    ---
    fizzbuzz: front matter fizz buzz
    ...

    Lorem ipsum dolor sit amet.
    ```

Am on Ubuntu 22.04.3 LTS via WSL2.

**Comment by jgm** [comment]
I don't think it's a bug.  The idea of `--defaults` is that it behaves pretty much like the corresponding command line options -- and the `--metadata` option *does* override same-named metadata specified in the file.

**Comment by sxlijin** [comment]
Ah, OK, so this was just user error. Thanks!
