### ISSUE TITLE
Gladtex completely eliminating \begin\end environments

### ISSUE THREAD

**Issue by borsiemir** [jgm/pandoc#9238]
**Explain the problem.**
I have a mardown file test.md with the following content:

```md
---
title: Test
...

\begin{align*}
&a = b\\
&c = d
\end{align*}

$$
a = \begin{cases}
  c \\
  d
\end{cases}
$$
```

When I run **pandoc test.md -s --gladtex -o test.html** there is not error, however the body of test.html is:

```html
<body>
<header id="title-block-header">
<h1 class="title">Test</h1>
</header>
<p></p>
<p><eq env="displaymath">
a = \begin{cases}
  c \\
  d
\end{cases}
</eq></p>
</body>
```
In other words, the first \begin\end environment totally disappears, while the second one is okay. It seems that the second is okay because it is already in a displaymath with double dollars, sadly introducing the align* environment inside a displaymath causes a latex error.

I tried the raw_tex extension, since I thought the problem may come from not using it, however it changed nothing. Also, I tried to do the same with mathjax and it perfectly works, so the problem seems to be with the --gladtex flag.

**Pandoc version?**
pandoc 3.1.9 in Debian 12

Thank you for your attention.

**Comment by jgm** [comment]
gladtex only affects math sections, and the first thing here is parsed as raw tex, not math.  Raw tex is just omitted in HTML output, and gladtex has no effect on it.

Suggestion: use the `aligned` environment; it works within display math.
