### ISSUE TITLE
Use pre-push hook to avoid version desynchronization

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#9248]
Having committed https://github.com/jgm/pandoc/commit/35d44bb666fac8706231687c573650efd8b165e9, we now have 5 locations that need to be edited when cutting a new release. And while they appear in `RELEASE-CHECKLIST`, that still doesn't prevent mistakes from slipping through the cracks.
Automating either checking for consistency or the cutting of a new release would help avoid this problem. Below is a sketch of a script (to be placed in `.git/hooks/pre-push`) that would do the former:

```bash
#!/bin/bash

files=('pandoc-cli/pandoc-cli.cabal' 'pandoc.cabal')
files+=('changelog.md' 'pandoc-cli/man/pandoc.1')

gitver() {
    [ "$VERBOSE" ] && printf 'Latest tag: '
    git describe --tags --abbrev=0 "$1"
}
cabalver() { sed -n '/^version:/{s/[^0-9]*\([0-9][0-9.]*[0-9]\)/\1/;p}'; }
genver() {
    sed -n '/pandoc [0-9][0-9.]*/{s/.*pandoc \([0-9][0-9.]*[0-9]\).*/\1/;p;q}'
}
fileVers() {
    oid="$1"; shift
    for i in "$@"; do
        [ "$VERBOSE" ] && printf 'In %s: ' "$i"
        git show "$oid":"$i" | case "$i" in
            *.cabal) cabalver;;
            *) genver;;
        esac
    done
}
vers() { gitver "$1"; fileVers "$@"; }

zero=$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')

while read -r _ local_oid _ _
do
    # Not a deletion
    if ! [ "$local_oid" = "$zero" ]; then
        if [ "$(vers "$local_oid" "${files[@]}" | sort -u | wc -l)" -ne 1 ]
        then
            echo >&2 "Commit $local_oid has inconsistent version numbers:"
            VERBOSE=1 vers "$local_oid" "${files[@]}"
            exit 1
        fi
    fi
done

exit 0
```

**Comment by jgm** [comment]
I was thinking of adding something to the checks done by `make prerelease`.
I think I'd rather do that than add a git hook, because git hooks aren't reproduced when you clone the repository (I think), and I don't know if I'd want to require changelog and man pages to be updated at the same time as cabal versions.

Could this be adapted to fit into `make prerelease`?

**Comment by alerque** [comment]
As shell scripting goes that's some classy code. It doesn't look like it would be too hard to adapt to a `make` recipe, especially if `.ONESHELL:` is used. If not maybe in can be an auxiliary script and just called from recipe.

**Comment by jgm** [comment]
Putting all the prerelease checking in an external script is probably not a bad idea.

**Comment by jgm** [comment]
I've added some more automatic checks in `make prerelease`:
commit 708bfa5c2752b8c9c2158e34707459859974f7fe

**Comment by jgm** [comment]
And of course this uncovered the fact that I didn't regenerate pandoc-server and pandoc-lua man pages with the right version number!

**Comment by hseg** [comment]
> I was thinking of adding something to the checks done by `make prerelease`. I think I'd rather do that than add a git hook, because git hooks aren't reproduced when you clone the repository (I think), and I don't know if I'd want to require changelog and man pages to be updated at the same time as cabal versions.
> 
> Could this be adapted to fit into `make prerelease`?

Indeed, hooks don't get cloned along, this does indeed make more sense.
One thing that I don't see in 708bfa5 that was my actual motivation for pushing for this is making sure releases get tagged when `pandoc.cabal` is bumped -- it makes packaging that tiny bit easier to be able to assume the tag sensibly gives the version. (Other alternatives are to either grep for it in `pandoc.cabal` or to get cabal/stack to spit it out, but that's sufficiently fiddly and this seems a sufficiently small ask that I'd like to push the engineering burden back to you)
To substantiate my case, attached are 
[a simplified git history, showing just the tagged versions and when, based on `pandoc.cabal`, they should've been tagged](https://github.com/jgm/pandoc/files/13677185/tag-tree.txt)
[notes re the release history, including statistics](https://github.com/jgm/pandoc/files/13677183/notes.txt)
[number of commits between version bump and tag](https://github.com/jgm/pandoc/files/13677184/skips.txt)
Headline summary is that of 181 times `pandoc.cabal` had `version:` bumped (excluding 32 cases without an accompanying tagged release):
- 61 cases (33%) where the tag was within 1 commit of the bump
- 42 cases (23%) where the tag was between 10-99 commits after the bump
- 16 cases (8%) where the tag was more than 100 commits after the bump
Besides this, three lines of development were never merged back into main and yet got tagged releases on their branch (1.9.4.3-5, 1.13.2.1, 1.19.2.*), and one more was merged into main but had its tag off-main (2.0). Also, 1.11 and 2.11.0.2 seem to have had trouble with the release (requiring a rebase in the latter case), and might've benefitted from some history editing.

**Comment by jgm** [comment]
> making sure releases get tagged when pandoc.cabal is bumped 

I didn't want to do this, because the procedure I use is to:

- first, bump the version
- then do the release builds on the CI servers
- IF these succeed, tag the version and release
- IF they don't succeed, fix and try again

This requires being able to change the cabal version for tagging.

**Comment by jgm** [comment]
Note: my practice has not been to edit the main branch. (So, tags can't be deleted once created.)

**Comment by hseg** [comment]
> Note: my practice has not been to edit the main branch. (So, tags can't be deleted once created.)
This wouldn't be a problem for some of the cases I highlighted -- `git tag --no-merged main` lists all tags that aren't in the main branch, in particular `1.9.4.*,1.13.2.1,1.19.2.*,2.11.0.2`. Those could have been deleted, no?
Though the point was more that there seems to have been several instances where releases were cut from branches that weren't merged to `main`, which was unexpected.

> > making sure releases get tagged when pandoc.cabal is bumped
> 
> I didn't want to do this, because the procedure I use is to:
> 
> * first, bump the version
> * then do the release builds on the CI servers
> * IF these succeed, tag the version and release
> * IF they don't succeed, fix and try again
> 
> This requires being able to change the cabal version for tagging.

This doesn't explain the delay between bump and tagging, though -- I've noticed features being added in between several times. If this is just a matter of wanting to be able to continue working while the rc is building, perhaps the following could work:
- When decision is made to cut a release, split main into `rc` and `feature`
- Continue development on `feature` as needed
- On `rc`, bump version and run CI, fixing as necessary
- Once a working build has been produced and finalized, squash `rc` into a single release commit and tag it
- Rebase `feature` onto `rc`
- Merge `feature` into `main` (incidentally also including `rc`)
In particular, nothing gets tagged until the final working build has been made, and the release commit is atomic.

What do you think?

**Comment by jgm** [comment]
> This doesn't explain the delay between bump and tagging, though -- I've noticed features being added in between several times. 

Sometimes attempting to build the release version reveals problems that need to be fixed. And sometimes I've just decided to fix something else during this interval.  (Nobody is really harmed by this as far as I can see!  The important thing is that the tag gets added when the Hackage release is made.)

The method you outline may be a better way to go, in theory, but I don't think the current process is really problematic.

**Comment by hseg** [comment]
Fair enough. The one place this really rubs against me is that I'm maintaining the AUR packages for both the statically built nightlies for `pandoc` and  `pandoc-crossref`. The latter consistently breaks when pandoc bumps in version, and the build script for the former takes its version from the latest tag. It would be nice if I could assume the version reported by the tag matches the one reported by cabal.
However, I guess if that is too big an ask, I can use the approach I already use for `cabal-fmt`, and that I've seen used for `fanficfare`, of just tagging the version-bumping commit as `${ver}-rc`:
```bash
pkgver() {
git tag "$(awk -F' *: *' '$1 ~ /^[Vv]ersion/ { print $2 }' pandoc.cabal
git describe --long --tags --match '[0-9]*' | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}
```
