### ISSUE TITLE
Markdown extension for speaker notes

### ISSUE THREAD

**Issue by lccanon** [jgm/pandoc#925]
It would be useful to specify some text in a markdown file as hidden notes. This text could then be used as speaker notes for different presentation formats:
- beamer with `note{}`
- reveal.js with `aside` blocks
- impress.js (if it is eventually integrated as a writer) through [impress-console](https://github.com/regebro/impress-console) and the `notes` class
- docbook (related to Issue #354 which is already solved)

There are some solutions:
- the previous docbook issue (#354) proposes to begin a paragraph with `Note:`
- for reveal.js, it was [proposed](https://github.com/hakimel/reveal.js/pull/510) to put a line containing `[[[` before any note block and 2 or 3 empty lines after
- on [stackoverflow](http://meta.stackoverflow.com/questions/1191/add-markdown-support-for-hidden-until-you-click-text-aka-spoilers), each spoiler line must start with `>!` (even though, it poses a [problem](http://meta.tex.stackexchange.com/questions/790/do-we-want-the-spoiler-feature-turned-off) for Latex outputs)
- the School of Haskell Markdown uses `@@@` fences for hiding solutions (see Pull #832 and [this](https://www.fpcomplete.com/school/how-to-use-the-school-of-haskell/soh-markdown))

I think the first solution (`Note:`) is the one that is the most readable in plain text. There could be two ways to use it:

```
Note: This sentence is a simple note.

Note:
    This indented block is a note:
    - this is the first item of the note
    - this is the second item

    This is the last sentence of this note.
```

It may also be generalized as a solution for hiding content (`Hidden:` instead of `Note:`?) with a general option like `--include-hidden-notes` for generating output with the notes and no note by default. I could use such a mechanism in an educational context for generating questions with and without corrections (in this case, a pdf or latex writer could use a solution similar to what is provided by the `exam` class). It may also be related to Issue #254 if we consider that comments are hidden content that should not be present in the output by default.

The scope of a general mechanism may be too large, but it would be great to add speaker notes and to control their inclusions in the output presentations as I do not always distribute my notes (but this last inclusion feature may be only relevant in an education context).

**Comment by sjackman** [comment]
See http://pandoc.org/MANUAL.html#speaker-notes
