### ISSUE TITLE
What happened to pandoc-discuss?

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#9250]
Practically since this project began, we've had a mailing list on google groups (pandoc-discuss).
As of yesterday, it is no longer accessible.  What happened is that it got overrun with spam, and Google flagged the group with a "banned content warning."  I was able to log in as administrator, delete all the spam, ban the spammers, and turn on moderation to avoid the problem in the future. I have requested review and reinstatement from Google, but who knows how long that will take.

I'm hoping the group will be back soon, and at this point the purpose of this issue is just to let people know what is up.  If the group is not back soon, I will look into alternatives.

**Comment by p3palazzo** [comment]
GitHub now has a `discussions` feature built right into the repository, if Google fails.

**Comment by jgm** [comment]
I know.  That may be the best backup plan, and I know many people would prefer that interface.  But I'd rather not interrupt the continuity of a searchable discussion forum that goes back 15 years.  Google Groups also has the advantage that you don't need a GitHub account to ask a question.

Still, it irks me that Google has not yet responded.  I tried to use Google's "download your data" feature to download the full archive in mbox format, but it did not give me pandoc-discuss, even though I'm the owner.

**Comment by iandol** [comment]
It is crazy, that spam started to increase can be attributed to Google's failure to filter the spam in the first place, and then in response, it shuts down the whole group! Lets hope you can get the messages out. I checked Github discussions but it seems there is no mechanism to import messages from another source?

**Comment by nandac** [comment]
@jgm Do we have a way to access past messages from pandoc-discuss?

In addition, do we have an alternative or should we just use GitHub issues for now?

**Comment by jgm** [comment]
I'm going to open up GitHub discussions. If Google comes through and resurrects our old group, we'll need to decide whether to go back to it or continue with discussions, but knowing that this kind of thing can happen inclines me not to rely on Google.

**Comment by reagle** [comment]
I suspect Google is neglecting Google Groups and will ignore our query. (If the old messages are of value to folks, perhaps someone has a local archive that could be made available as static HTML?)

**Comment by tarleb** [comment]
My archives go back only to mid March 2018. Are there any good tools to publish this kind of archive?

**Comment by simonmichael** [comment]
I just discovered this via mastodon. I'm sorry this happened @jgm. Surely someone at google will eventually repair the pandoc googlegroup, but who knows when that might be.

You can recover a partial archive, at least, by pointing a newsreader like Thunderbird at NNTP server news.gmane.io, and subscribing to newsgroup gmane.text.pandoc. It seems to have all messages from 2010-05-20. I believe you can get them out of Thunderbird in mbox format, eg.

**Comment by badumont** [comment]
It seems to be possible to [import archives in mbox format into Mailman](https://docs.mailman3.org/projects/hyperkitty/en/latest/install.html). It documents importing Mailman 2.1 archives into Mailman 3, but I hope that it would work with any mbox files.

**Comment by tarleb** [comment]
Information provided by @pamoroso, [posted](https://fosstodon.org/@amoroso/111781751979929971) on Mastodon:

> Have you already tried posting to the Google Groups Help Community?
> [https://support.google.com/groups/community](https://support.google.com/groups/community)
>
> For some products it's possible to escalate issues to or get further assistance from Google. This is done by posting to the product's official help community so that some of the badged volunteers who can make escalations (any type of badge except for Bronze) notices.
> 
> The badged volunteers (Product Experts) may not be able to do much. The only way to find out is to post to the relevant help community.

**Comment by leahneukirchen** [comment]
I scraped an archive from gmane and put it online at https://inbox.vuxu.org/pandoc-discuss for now. This goes back to 2010-05-20.

I noticed some threads are broken due to missing Message-IDs, I'm not sure how complete the archive at gmane was.

If someone else has old messages to backfill, I'll gladly add them.

**Comment by simonmichael** [comment]
https://public-inbox.org/README.html eh.. interesting.

**Comment by jgm** [comment]
@leahneukirchen I have 68000 messages going back to 2007.  Let me know how to get them to you.

**Comment by leahneukirchen** [comment]
@jgm Upload them somewhere and tell me at leah@vuxu.org how to fetch them?

**Comment by jgm** [comment]
@tarleb I posted on the google help forum, we'll see if that helps.

**Comment by jgm** [comment]
I have found messages from 2007-2010 and @leahneukirchen has added them to the searchable archive here, which should now be pretty complete: <https://inbox.vuxu.org/pandoc-discuss>

**Comment by simonmichael** [comment]
Very cool. And one can point Thunderbird at inbox.vuxu.org and subscribe to vuxu.archive.pandoc-discuss. 

I believe you could also add the earlier messages to gmane (and update other metadata) at https://admin.gmane.io . Gmane is NNTP-only unlike inbox.vuxu.org, but it is a well known place for finding FOSS mail lists.

**Comment by simonmichael** [comment]
(Gmane admins might remove the recent spam too.)

If you don't mind me asking I'm curious how this happened - was the list left too open (new users allowed to post unmoderated) for too long ?

**Comment by jgm** [comment]
New users were always allowed to post unmoderated.  In the past, Google's spam filter would almost always catch spam and block it -- and often block a lot of genuine messages too, which I'd have to moderate myself.  I almost suspect they have decided to give up on Groups and turned off the spam filter intentionally. The spam in this case was obviously spam, easily detectable -- the sort of thing Google's email filter blocks all the time.

**Comment by simonmichael** [comment]
Interesting, thanks. I started seeing too much spam and had to turn on moderation a few years back.

**Comment by leahneukirchen** [comment]
@simonmichael note that inbox.vuxu.org is currently not subscribed (because I'm not sure the list is working?) but this can be done to make it receive the new messages too.

**Comment by leahneukirchen** [comment]
I can't mail `pandoc-discuss+subscribe@googlegroups.com` at least, ...

**Comment by hg2581** [comment]
What is the current status of this? Would it be possible to move to groups.io instead of googlegroups.com? Perhaps also upload old messages from googlegroups to groups.io?

**Comment by jgm** [comment]
I think the GitHub discussions approach is working well.  I'm not sure what the point of another change would be, and groups.io would cost $20/month, with the number of members we have.  We have an archive of the old messages on pandoc-discuss (see above).

**Comment by tarleb** [comment]
My one worry here is archiving, it would be nice if we could export the discussions if we ever need to.

On the other hand, pandoc using GitHub discussions is very convenient for projects like Quarto, which are using the same.

**Comment by jgm** [comment]
There is no official export API from Discussions, but there are some hacked up solutions here: https://github.com/orgs/community/discussions/3315
I figure we could export if we needed to.  (And maybe we should set up a script that does this on a regular basis.)

**Comment by hg2581** [comment]
I find a mailing list much more convenient since it allows you to see all questions and replies thus allowing the casual user to expand his/her knowledge of - in this case - how to efficiently use pandoc.  If the questions or the replies are not of interest to you, you simply delete the emails.

A forum, or similar, such as github, forces you to take the time to make the effort to visit the forum and thus makes information /less/ accessible for anyone - except those who have a strong interest in the project and thus probably visit the forum/github every day/often.

An RSS feed for the github discussions would ameliorate the above but I do not see that one exists? I would love to be proven wrong though.

**Comment by ant-222** [comment]
I think that mailing lists are ligher, simpler, cleaner, more convenient, more traditional, and more accessible means of communication than the bloated github web interface. It would be a great if the wonderful *Pandoc* maling lists were resurrected on a sounder basis than *Google Groups*, such as [`freelists.org`](https://freelists.org/) or another proper maling-list host.

**Comment by simonmichael** [comment]
Longevity of such hosts is a problem. They tend to disappear within about 10 years. The alternative is to take on a costly long term list hosting maintenance project which takes time away from other things. Google and Github have the appeal of being relatively long lived and easy to export from when the time comes.

**Comment by jgm** [comment]
> Google and Github have the appeal of being relatively long lived and easy to export from when the time comes.

This is what I'd always assumed, but it turned out not to be true. When Google froze our mailing list (and didn't reply to any of our requests to unfreeze it), it also made all the content inaccessible, even to the maintainers.

freelists does look like an interesting possibility. But now that discussions have gotten going on GitHub, I'm reluctant to change yet again...

**Comment by ant-222** [comment]
@simonmichael 

> (Now I've clicked past the giant cookie banner and seen freelists' featured 20-year age... You still can't be sure they'll be around in 10 years, but that's a good track record.)

Yes, the age of a service is a good predictor of its longetifity. The [Oracle mailing list](https://freelists.org/archive/oracle-l/) has been hosted there since 2004. Plus, the archives may be exported and reused on antoher host.

**Comment by hg2581** [comment]
On June 27, 2024 1:18:15 PM EDT, Anton Shepelev ***@***.***> wrote:
>I think that mailing lists are ligher, simpler, cleaner, more
>convenient, more traditional, and more accessible means of
>communication than the bloated github web interface. It would be a
>great if the wonderful *Pandoc* maling lists were resurrected on a
>sounder basis than *Google Groups*, such as
>[`freelists.org`](https://freelists.org/) or another proper maling-list
>host.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc/issues/9250#issuecomment-2195254393
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

Absolutely agree!

**Comment by ant-222** [comment]
@jgm , if you register and host your project on [GNU Savannah](https://savannah.gnu.org), their reliable mailing list service (via [`mailman`](https://www.gnu.org/software/mailman/) will be at your disposal. It is very reliable, and will probably exist as long as *GNU* itself exists. See if *Pandoc* satisfies their [hosting requirements](https://savannah.gnu.org/register/requirements.php).

**Comment by avidseeker** [comment]
https://sr.ht also offer an excellent interface for managing mailing lists. Alpine Linux hosts their mailing lists on a fork of sr.ht.

**Comment by ant-222** [comment]
@iandol [wrote](https://github.com/jgm/pandoc/issues/9250#issuecomment-2212907044):

> Pandoc is developed on Github, issues are managed here, 3rd party pandoc filters are mostly developed here, many templates are found here. Keeping discussions here makes a lot of sense.

Consider the accessibility: *Github* requires a modern browser with *JavaScript*—much less technologically accessible than the old, stable, open, and widely-supported e-mail. Consider the format: the QA structure if *GitHub* issues does not forster the sort of free-form discussion that mailinsg lists do. Even if development is to take place here, why not let users discuss Pandoc in a `pandoc-users` mailing list? Ironically *Github*'s Markdown is badly broken.

@avidseeker [wrote](https://github.com/jgm/pandoc/issues/9250#issuecomment-3711135453):

> https://sr.ht also offer an excellent interface for managing mailing lists. Alpine Linux hosts their mailing lists on a fork of sr.ht.

Not only that. *SourceHut* is a great platform for hosting open-source projects, offering a complete development infrastructure.

**Comment by jgm** [comment]
SourceHut does look appealing in many ways. I wonder how good their spam filtering is? That's very important for a big project.

**Comment by ant-222** [comment]
@jgm:

> SourceHut does look appealing in many ways. I wonder how good their spam filtering is? That's very important for a big project.

Considering how efficient they have been in [repelling LLM crawlers](https://status.sr.ht/issues/2025-03-17-git.sr.ht-llms/) and withstanding DDOS attacks from competitors, I should think their maling lists are well protected, but I have no direct experience of using a large project's list on *SourceHut*. I can persontally testify, however, to the high quality of their support.

Beware however, that after the web bloat of the more popular source forges, *SourceHut* may seem... unappealing to the more softcore part of the audience, what with the [e-mail-based workflow](https://drewdevault.com/2022/07/25/Code-review-with-aerc.html).

To most maintainers, *SourceHut* is a [paid service](https://man.sr.ht/billing-faq.md), although the cost is neglibible and negotiable (e.g. if you can't pay abroad from your country).

**Comment by ant-222** [comment]
I fear `sh.ht` cannot be used a maling-list host, because its mailing lists intended for discussions betwenn `sr.ht` members. According to the [posting instructions](https://man.sr.ht/lists.sr.ht/#posting), users send e-mail not to the general list address, but to a user-specific address on the list. Don't waste your time researching `sr.ht` for hosting a mailing list.

Update: I was [wrong](https://github.com/jgm/pandoc/issues/9250#issuecomment-3795364490).

**Comment by jgm** [comment]
I don't follow: the link says: "You may post to a list that you have posting permissions on by writing a plaintext email to ~user/list-name@lists.sr.ht.".  So, it sounds like you do post to a list (in this case, perhaps, it would be ~jgm/pandoc-discuss).  The username acts like a namespace as I'm understanding it.

**Comment by alerque** [comment]
> The username acts like a namespace as I'm understanding it.

Not exactly. It acts as an authentication mechanism. It verifies that *you* the `~user` are allowed to post, e.g. that `~jgm` is registered with write permissions to the list via `jgm@youremail.com` or whatever you are sending from.

As noted by @ant-222 to the best of my knowledge sr.ht is not a good general purpose mailing list solution as it requires users have a sourcehut account setup and that's more technical than many/most users expectations.

**Comment by ant-222** [comment]
@alerque

> to the best of my knowledge sr.ht is not a good general purpose mailing list solution as it requires users have a sourcehut account setup and that's more technical than many/most users expectations.

Indeed. A public-discussions mailling list shalt not require of participants any sort of «account» with a web service, but shalt offer its entire functionality over e-mail. There are both free ([freelists](https://www.freelists.org/), [Autistici](https://www.autistici.org/services/lists)[^1], [SourceForge](https://sourceforge.net/p/forge/documentation/Mailing%20Lists/)) and paid ([Mailmanhost](https://www.mailmanhost.com), [Mailmanlists](https://mailmanlists.net/)) services for hosting public mailing-lists.

Whereas commerical servcies offer both _Mailman2_ and _Mailman3_, free ones seem to prefer _Mailman3_—a complete rewrite of the classic mailer, with a JavaScript-based [web interface](https://lists.tildeverse.org/hyperkitty/list/institute@lists.tildeverse.org/thread/365UROQMTZRGLUZ2FBBNBAFB4EWHPCTS/) showing e-mails in a proportaions font. Of couser, a can still be [archived externally](https://marc.info/) or accessed over NNTP (read-write) via [Gmane](http://gmane.io/). Hmmm—*SourceForge* still provides *Mailman2*, which I am in the process of testing.

[^1]: They *will* host a mailing list for a Free-software project—I have confirmed.

**Comment by ant-222** [comment]
@jgm 

> I don't follow: the link says: "You may post to a list that you have posting permissions on by writing a plaintext email to ~user/[list-name@lists.sr.ht](mailto:list-name@lists.sr.ht).". So, it sounds like you do post to a list (in this case, perhaps, it would be ~jgm/pandoc-discuss). The username acts like a namespace as I'm understanding it.

I misunderstood the `sr.ht` approach and misinformed you. I have consulted their staff and invert my statement: the user prefix is indeed just a namespace, and their mailing lists can be made public. Beg pardon for the confusion! Feel free to create an `sr.ht` mailing list for *Pandoc*.

**Comment by ant-222** [comment]
I [wrote](https://github.com/jgm/pandoc/issues/9250#issuecomment-3775124625):

> Whereas commerical servcies offer both _Mailman2_ and _Mailman3_, free ones seem to prefer _Mailman3_—a complete rewrite of the classic mailer, with a JavaScript-based [web interface](https://lists.tildeverse.org/hyperkitty/list/institute@lists.tildeverse.org/thread/365UROQMTZRGLUZ2FBBNBAFB4EWHPCTS/) showing e-mails in a proportaions font. Of couser, a can still be [archived externally](https://marc.info/) or accessed over NNTP (read-write) via [Gmane](http://gmane.io/). Hmmm—_SourceForge_ still provides _Mailman2_, which I am in the process of testing.

For the record, I confirm that SourceForge offers [*Mailman2* hosting](https://sourceforge.net/p/forge/documentation/Mailing%20Lists/) for free, and that it actually works: one may create a project that has nothing in it but a single mailing list.
