### ISSUE TITLE
HTML Tables Not Working When Converting To Other File Types

### ISSUE THREAD

**Issue by EzraLaneFrogslayer** [jgm/pandoc#9251]
**Explain the problem.**
If I have html code that has a table in it, it will not show up in the pdf at all. If I run this html code is other places I get a table. But when I convert it to pdf using pandoc, I get a pdf with no table and three lines that each have "Item" written on them.

To recreate this, run with this command line:
`pandoc temp.html -f html -t pdf -o temp.pdf
`
And here is the code that is in temp.html:
```
<html lang="en">
    <style>
        .tbl { border-collapse: collapse;}
        .tbl th, .tbl td {  text-align: left; padding: 5px; border: solid 2px #CDCBCC; }
        .tbl th { background-color: #F0F0F0; }
    </style>
    <head>
        <table class="tbl" style="width:100%">
            <tr>
                <td>Item</td>
                <td></td>
            </tr>
            <tr>
                <td>Item</td>
                <td></td>
            </tr>
            <tr>
                <td>Item</td>
                <td></td>
            </tr>
            <tr>
                <td>Item</td>
                <td></td>
            </tr>
        </table>
    </head>
</html>
```

**Pandoc version**
I am currently using pandoc 3.1.9 on Mac OS

**Comment by jgm** [comment]
That's because the table is inside `<head>..</head>`. I think you want it in `<body>..</body>`.
Head is for styles, metadata, and things like that.

**Comment by jgm** [comment]
It renders as
<img width="101" alt="Screen Shot 2023-12-14 at 12 00 35 PM" src="https://github.com/jgm/pandoc/assets/3044/5454b047-8101-4c6c-8698-45ec673556cf">

That is proper rendering.  We don't use borders around tables, and you have no header line.
