### ISSUE TITLE
Regression issue between 3.1.9 and 3.1.10

### ISSUE THREAD

**Issue by mithunsridharan** [jgm/pandoc#9255]
Situation: I am using pandoc to generate PDF documents using Markdown files where the content is stored. I use a bespoke Latex template to format the output PDF.

Issue: pandoc correctly runs 2 times when using version 3.1.9 distribution. However, when using pandoc 3.1.10, it run only once. As a result, the PDF file does not generate the page numbers correctly, especially when using Latex package, lastpage.

Attached are the log files generated with 3.1.9 and 3.1.10.

The issue is consistent when using the distribution from pandoc website and homebrew.

Please share workarounds (if any) or a patch for the current release.

Thanks,
Mithun A. Sridharan

[3_1_9.log](https://github.com/jgm/pandoc/files/13685585/3_1_9.log)
[3_1_10.log](https://github.com/jgm/pandoc/files/13685586/3_1_10.log)

**Comment by jgm** [comment]
We run once because that is all that is necessary with the default template. If you use a custom template, you may need to handle the LaTeX running yourself. Most reliable method is to use `--pdf-engine=latekmk`.

**Comment by jgm** [comment]
I'll look into parsing the log file to figure out if we need additional runs; that should be more robust.

**Comment by samp1888** [comment]
Hi there completely new to pandoc, markdown, latex… only started 2 weeks ago; had my first document working and experienced the same issue as described apart from the fact that I do not use a custom template, well that said I am using Typora as I have literally no idea what I’m doing so could be a custom template if Typora does that by default (I haven’t changed this setting) . Anyway 3.1.9 page x of y was working; 3.1.10 not working, also new to GitHub so not sure how to use the fix any chance someone could help pls? Thanks

**Comment by jgm** [comment]
Use the workaround above with `--pdf-engine=latexmk`.
The next release of pandoc will avoid this problem.

**Comment by samp1888** [comment]
Thanks, got unlucky and looks like I need to install perl...

![image](https://github.com/jgm/pandoc/assets/153950817/ba196b94-aa93-434f-8aac-7c69a9311d6c)

**Comment by samp1888** [comment]
Working again, thatnks again for the help!
![image](https://github.com/jgm/pandoc/assets/153950817/455280b5-af41-4c86-b395-d27bfe72e326)

**Comment by mithunsridharan** [comment]
> Use the workaround above with `--pdf-engine=latexmk`. The next release of pandoc will avoid this problem.

I use a Makefile with the --pdf-engine=lualatex. Unfortunately, latexmk doesn't work with the template that I'm using.

The only thing that changed is the pandoc upgrade. From the logfile produced with 3.1.9, there's a re-run, but not with 3.1.10.

The command line invocation looks like this:

`pandoc Portfolio.md -o PDF/Portfolio.pdf --template=src/Portfolio.tex --pdf-engine=lualatex`

The .tex document contains variables to map the markdown variables to the final pdf document as described [here](https://pandoc.org/chunkedhtml-demo/6.2-variables.html). The .tex file uses a .cls file that contains the styling information to render the final PDF document.

I was wondering if there's a flag or workaround to force a re-run. Makefile re-runs don't seem to work with 3.1.10 as I suspect that the temp files are created fresh with each re-run.

For the moment, I've downgraded my pandoc version to 3.1.9 where this issue. 

Thanks!

**Comment by mithunsridharan** [comment]
This issue seems to be resolved with pandoc version 3.1.11 that I grabbed from GitHub. Thanks for the quick turnaround and fix @jgm Much appreciated!
