### ISSUE TITLE
Allow empty <title> element if using -M title=""

### ISSUE THREAD

**Issue by jsx97** [jgm/pandoc#9257]
In my work I prefer the title element of each of my "markdown-to-html" documents to be the same as the filename. (And I rename them often.)

For this, as long as I use `-s`, I use `-M title=" "` (I don't know any other workaround). For example:

```
pandoc input.md -o output.htm -s --toc=true -M title=" "
```

```
<title> </title>
```

This works, but why not allow us to use a more elegant construction without that space inside `<title>`?

```
pandoc input.md -o output.htm -s --toc=true -M title=""
```

```
<title></title>
```

**Comment by jgm** [comment]
Conditionals in templates like `$if(title)$` will not trigger if the variable is empty. That is why it works with a space but not without.

**Comment by jgm** [comment]
Note that if you don't specify title at all, pandoc will *default* to making the `<title>` element contain the filename!

**Comment by jsx97** [comment]
> Note that if you don't specify title at all, pandoc will default to making the `<title>` element contain the filename!

Yes, the only problem is that if I rename the html file later, its name will stay the same.
