### ISSUE TITLE
Pandoc can not convert equation surrounded by `$$`

### ISSUE THREAD

**Issue by PaleNeutron** [jgm/pandoc#9274]
I can not convert markdown syntax latex equation to pdf:

```markdown
# Equation Test

$$
\begin{align}
    g &= \int_a^b f(x)dx  \\
    a &= b + c
\end{align}
$$
```

pandoc failed with

```
Error producing PDF.
! Package amsmath Error: Erroneous nesting of equation structures;
(amsmath)                trying to recover with `aligned'.

See the amsmath package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.68 \end{align}
```

I know I can convert it if I remove `$$` from markdown but it is not the way other markdown tools support.

**Pandoc version?**
```
pandoc 3.1.11
Features: +server +lua
Scripting engine: Lua 5.4

Ubuntu 22.04
```

**Comment by jgm** [comment]
`\begin{align}..\end{align}` can't go in a LaTeX display math environment.  The error above is coming from LaTeX.

Used `\begin{aligned}..\end{aligned}` instead in this context.

**Comment by PaleNeutron** [comment]
> `\begin{align}..\end{align}` can't go in a LaTeX display math environment. The error above is coming from LaTeX.
> 
> Used `\begin{aligned}..\end{aligned}` instead in this context.

But this can not numbering it, If I use 

```
$$
\begin{equation}
\begin{aligned}
e & = mc^2
\end{aligned}
\end{equation}
$$
```

It also fails

**Comment by jgm** [comment]
Probably because markdown preview uses MathJax, which allows this, *even though it's invalid in LaTeX*.

**Comment by PaleNeutron** [comment]
I know pandoc translate `$$` to `\[`, but can there be any approach to fix the gap between `mathjax` and `latex` by pandoc?

For example, if pandoc detected any `\begin{equation}` or `\begin{align}` or other command, it will translate it to latex without `\[`.

**Comment by jgm** [comment]
```
\begin{equation}
\begin{aligned}
e & = mc^2
\end{aligned}
\end{equation}
```
will work fine in pandoc without the `$$`.  MathJax handles this perfectly as well. As I see it, the problem is with the markdown preview app you're using, which should support this too.

**Comment by PaleNeutron** [comment]
Thanks a lot.
