### ISSUE TITLE
Orgmode tables.el captions not working properly

### ISSUE THREAD

**Issue by awelormro** [jgm/pandoc#9279]
**Explain the problem.**
Hello there, I'm facing an issue to convert from orgmode to another formats, everything works flawlessly, except for the table.el tables, I tried using the following arranges:

```org
#+LABEL: tbl:Cosasexample
#+CAPTION: Cosas
+-------+-------+
| cosas | cosas |
| cosas | cosas |
+=======+=======+
| cosas | cosas |
| cosas | cosas |
| cosas | cosas |
| cosas | cosas |
+-------+-------+
```

when I'm trying to create the catpions, when I run `pandoc filename.org -t markdown` it results in:

```
\{=org\}
#+LABEL: tbl:Cosasexample

{=org}
#+CAPTION: Cosas
  ---------------
  cosas   cosas
  cosas   cosas
  ------- -------
  cosas   cosas
  cosas   cosas
  cosas   cosas
  cosas   cosas

  ---------------
```

I expected the standard markdown caption as a result, it also fails in docx and latex, thanks for your help :)

**Pandoc version?**
pandoc 3.1.6
Features: +server +lua
Scripting engine: Lua 5.4

**Comment by awelormro** [comment]
Sorry to bother again, I've seen the commit has been made yesterdaym and thank you, but I have a question to access to the patch, What kind of installation must I have to access it? Through hackage, cabal or similar? Pardon me, I haven't located the instructions in the documentation

**Comment by jgm** [comment]
Instructions here:

https://pandoc.org/installing.html#getting-the-pandoc-source-code

**Comment by awelormro** [comment]
thanks for the help, i've installed and it partially works, it reads captions, but it is not putting the labels for referencing, the expected behaviour is the regular table citation marks

Input:

```
#+LABEL: tbl:Cosasexample
#+CAPTION: Cosas
+-------+-------+
| cosas | cosas |
| cosas | cosas |
+=======+=======+
| cosas | cosas |
| cosas | cosas |
| cosas | cosas |
| cosas | cosas |
+-------+-------+
```

Expected output:

```
+-------+-------+
| cosas | cosas |
| cosas | cosas |
+=======+=======+
| cosas | cosas |
| cosas | cosas |
| cosas | cosas |
| cosas | cosas |
+-------+-------+
: Cosas {#tbl:Cosasexample}
```

**Comment by jgm** [comment]
Well, that's a markdown writer issue. Actually, currently there is no standard way of adding an identifier to the table itself.  Putting it at the end of the caption wouldn't be a bad approach (for now), at least when the table has a caption, but that's not a documented behavior.

**Comment by jgm** [comment]
I made this change.

**Comment by awelormro** [comment]
It works perfect! Now I can translate between these two filetypes, Thanks for all the effort and happy holidays!
