### ISSUE TITLE
Raw html from raw_attribute extension is passed to epub generation

### ISSUE THREAD

**Issue by Kile-Asmussen** [jgm/pandoc#9280]
Not sure if this is a bug, but at the very least it is undocumented that `raw_attribute` does not function as a conditional compilation tool, and that filters or external preprocessors must be used.

`test.md`:

``````````
---
title: Test book
author: Test author
...

# Chapter 1

```{=html}
<p>This should not appear in the EPUB.</p>
```

This should appear in the EPUB.
``````````

Command:

```
> pandoc test.md -t epub -o test-book.epub
```

 Expected behavior:
 
 The produced epub book contains only the latter paragraph.

Observed behavior:

The epub contains both paragraphs.

Pandoc and OS version:

```
> pandoc -v
pandoc 3.1.9
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/<redacted>/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
> uname -a
Linux <redacted> 6.1.68 #1-NixOS SMP PREEMPT_DYNAMIC <redacted> 2023 x86_64 GNU/Linux
```

**Comment by jgm** [comment]
Well, the epub writer will pass through both `html` and `epub` raw content, because epub chapters are just HTML files.  We could in principle make a distinction here, but it would be a breaking change and I'd rather not do that.

**Comment by jgm** [comment]
In a similar way, the markdown writer will pass through `html` raw content, because markdown allows raw HTML.

**Comment by Kile-Asmussen** [comment]
Fair enough. I've created a filter script to deal with it.

**Comment by 1Dbcj** [comment]
any chance you can share that filter script?
