### ISSUE TITLE
HTML table with rowspan to grid table

### ISSUE THREAD

**Issue by aborruso** [jgm/pandoc#9289]
Hi,
I have [this HTML table](https://gist.githubusercontent.com/aborruso/24ea1b429651e5079ea79449d06c1893/raw/3febcdc75d9c2cfcaf8d552e4139a8b592c9e2f5/input.html), and I want to convert it to grid table, maintaining its rowspan cells, to get something similar to

```
+---------------------+----------+
| Property            | Earth    |
+=============+=======+==========+
|             | min   | -89.2 °C |
| Temperature +-------+----------+
| 1961-1990   | mean  | 14 °C    |
|             +-------+----------+
|             | max   | 56.7 °C  |
+-------------+-------+----------+
```

But if I run `pandoc -s input.html -t markdown+grid_tables -o output.md` I do not have the rowspan in the output.
Is there a way to force to create it?

Thank you

**Comment by jgm** [comment]
The markdown writer doesn't yet support row or colspans.

**Comment by jgm** [comment]
This would be a great project for someone who wants to work on the pandoc code base!

**Comment by jgm** [comment]
Actually this is a dup of #6344 - closing in favor of that.
