### ISSUE TITLE
RTF conversion doesn't centre text

### ISSUE THREAD

**Issue by barnaclebarnes** [jgm/pandoc#929]
I have an HTML document which I converted to RTF using the following command:

`pandoc -s -o ~/Downloads/output.rtf ~/Downloads/resolution_remove_director.html`

The files can be found here - https://gist.github.com/barnaclebarnes/6112092

The RTF file will not render the text centred and I'm not sure how to mark up the document to make it so. It seems that it should since the source has the ability to write out centred text - http://hackage.haskell.org/packages/archive/pandoc/1.11.1/doc/html/src/Text-Pandoc-Writers-RTF.html.

Any ideas?

**Comment by surr** [comment]
The real problem here is hardcoded left alignment.

The issue with centering/adjusting could be solved by using RTF stylesheets.
Instead of generating ``` {\pard \ql \f0 \sa180 \li0 \fi0 Text\par} ``` pandoc may produce just ``` {\pard \s0 Text\par} ```. The '\s0' style could be defined in template as ```{\stylesheet{\s0 \ql \f0 \sa180 \li0 \fi0 Normal;}} ```.
This solution allows users to override default paragraph style.

**Comment by jgm** [comment]
+++ surr [Mar 02 15 01:45 ]:
>   The real problem here is hardcoded left alignment.
>
>   The issue with centering/adjusting could be solved by using RTF
>   stylesheets.
>   Instead of generating {\pard \ql \f0 \sa180 \li0 \fi0 Text\par} pandoc
>   may produce just {\pard \s0 Text\par}. The '\s0' style could be defined
>   in template as {\stylesheet{\s0 \ql \f0 \sa180 \li0 \fi0 Normal;}}.
>   This solution allows users to override default paragraph style.

I think it's probably a good idea to change things in this way.  But to be
thorough, we'd really need to define a whole set of styles,
not just for default paragraphs but for other kinds of
constructions.
