### ISSUE TITLE
Unable to join pandoc-discuss - Malicious Warning

### ISSUE THREAD

**Issue by lamyergeier** [jgm/pandoc#9298]
I am unable to join Pandoc discuss:

> pandoc-discuss has been identified as containing spam, malware, or other malicious content.
>
> For more information about content policies on Google Groups see our [Help Center article](https://support.google.com/groups/answer/141369?hl=en) on abuse and our [Terms of Service](https://policies.google.com/terms?hl=en).

![image](https://github.com/jgm/pandoc/assets/42092626/225137ac-7818-4ba2-84d9-e55bde211306)

**Comment by kysko** [comment]
https://github.com/jgm/pandoc/issues/9250
