### ISSUE TITLE
Support raw_attribute blocks in Typst output

### ISSUE THREAD

**Issue by rbdixon** [jgm/pandoc#9301]
The `raw_attribute` extension is not supported for PDF documents generated with Typst. Ideally, this extension would be supported so that, as with the other PDF engines (latex, beamer, ms, or html5), raw directives to control layout could be passed to the engine.

**Comment by jgm** [comment]
I'm not sure what you're asking.  A block in a markdown file marked like
````
``` {=typst}
xxx
```
````
will be passed through to typst.

Perhaps you could give complete instructions for reproducing the issue, and state the pandoc version.

**Comment by rbdixon** [comment]
Indeed it does. I'm not sure how I goofed on that. Sorry... and thank you!
