### ISSUE TITLE
Provide flag to ignore InvalidUrlException

### ISSUE THREAD

**Issue by Dialga** [jgm/pandoc#9302]
**Describe your proposed improvement and the problem it solves.**
Please provide a flag to ignore urls that cannot be fetched and continue. Currently I have blocked google tag manager in my hosts file, which triggers the InvalidUrlException error when I try to convert a page to html with pandoc. 
**Describe alternatives you've considered.**

**Comment by Dialga** [comment]
```
pandoc 'https://www.nzherald.co.nz/' -o nz.html
```
It's a webpage.

**Comment by tarleb** [comment]
One option to handle this would be to make `PANDOC_STATE.log` a read/write field in Lua filters. Users could then filter out all warnings which they have no interest in. This would also provide a solution for #9077.

**Comment by jgm** [comment]
@Dialga can you clarify? Is the issue just that you're getting a warning like
```
[WARNING] Could not fetch resource h:invalid@url: Could not fetch h:invalid@url
  InvalidUrlException "blah blah"
```
If so, note that you can quiet warnings with `--quiet`. Or is the issue that pandoc is exiting with an error when it can't find a resource?  I think we need more details.

**Comment by Dialga** [comment]
Yes that is the warning I'm getting.
My impression was that no file was being output because of that error. I have now found that a file is created.
