### ISSUE TITLE
Code formatting ignored and following text dropped for jira markup -> html5

### ISSUE THREAD

**Issue by bkline** [jgm/pandoc#9310]
**Explain the problem.**

The `{code}` markup in JIRA input is not handled correctly unless there is a newline immediately after the opening `{code}`.

For example, with the following input:

```
Blah, blah, blah:

{code:bash}$ ssh-keygen
$ ssh-copy-id [user@]hostname{code}

Yada, yada, yada.
```

... the output generated by the command:

```
pandoc --from jira --to html5 --no-highlight
```

is

```
<p>Blah, blah, blah:</p>
<p>{code:bash}$ ssh-keygen<br />
$ ssh-copy-id [user@]hostname</p>
```

Expected output:

```
<p>Blah, blah, blah:</p>
<pre class="bash"><code>$ ssh-keygen
$ ssh-copy-id [user@]hostname</code></pre>
<p>Yada, yada, yada.</p>
```

If a newline is inserted before the first `$` character then the generated output is correct. That newline is not required for correct rendering in JIRA itself, and the JIRA documentation has no statement that such a newline is required.

The bug is unaffected by the presence or absence of the language specifier after a colon (`{code}` _versus_ `{code:java}`).

**Pandoc version?**
Latest (version 3.1.11; reproduced on https://pandoc.org/try/).

**Comment by jgm** [comment]
This would have to be fixed in https://github.com/tarleb/jira-wiki-markup
Please report there.

**Comment by bkline** [comment]
Ah, I see. So this project is basically a plugin wrapper. Fair enough.

https://github.com/tarleb/jira-wiki-markup/issues/23

Thanks.

**Comment by jgm** [comment]
No, the project is not "basically a plugin wrapper."  It contains something like 100,000 lines of Haskell code. But for this particular reader the author  factored out the parser into a separate library.

**Comment by bkline** [comment]
OK, understood. Thanks for the clarification.
