### ISSUE TITLE
Unable to generate epub from large number of markdown files on Windows due to long filename issue

### ISSUE THREAD

**Issue by Haoyi-Han** [jgm/pandoc#9316]
**Description:**
When attempting to use `pandoc` to generate an epub book from a substantial number of markdown files, I encountered an error stating `FileNotFoundError: [WinError 206] The filename or extension is too long.` This issue obstructs the seamless generation of epub files from a large collection of markdown files.

**Reproduction Steps:**
Using the following Python code to simulate a folder containing numerous markdown files (very long paths or very large number) and a command script to execute the pandoc program.

```python
from pathlib import Path

# long arguments due to long paths
def mock_book_src(src_dir: Path) -> bool:
    num: int = 500
    md_filelist: list[Path] = [(src_dir / f"00000000_00000000_00000000_{i:09d}.md") for i in range(1, num + 1)]
    for idx, file_t in enumerate(md_filelist):
        with file_t.open("w", encoding="utf-8") as ft:
            ft.write(f"# Episode {idx + 1}\n\nThis is a test.\n")
    return True

# long arguments due to too many short paths
def mock_book_src2(src_dir: Path) -> bool:
    num: int = 50000
    md_filelist: list[Path] = [(src_dir / f"{i:05d}.md") for i in range(1, num + 1)]
    for idx, file_t in enumerate(md_filelist):
        with file_t.open("w", encoding="utf-8") as ft:
            ft.write(f"# Episode {idx + 1}\n\nThis is a test.\n")
    return True
```

```powershell
cd $MyBookFolder
ls *.md | pandoc --from=markdown --to=epub -o ./MyBook.epub
```

**Environment:**
- Operating System: Windows 11
- Pandoc Version: 3.1.11.1 and older pandoc 3.1.3

**Attempted Solutions:**
I have enabled the long path option in Windows regedit by navigating to "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" and setting "LongPathEnabled" to 1. However, this did not resolve the issue.

I understand that a potential workaround could involve merging files or batch renaming them to shorter names. Nevertheless, this is not a desirable solution as the book folder may undergo continuous updates, making manual intervention impractical.

**Search Result:**
I have explored existing issues but have not found any that provide an effective solution to this problem.

**Expectation:**
I hope to find a solution or a viable workaround that enables the pandoc command to handle a large number of files, potentially with long paths, to facilitate the seamless generation of epub books.

Thank you for your attention to this matter. Any assistance in resolving this issue would be greatly appreciated.

**Comment by jgm** [comment]
Can you upload the generated epubs so I can see what the paths look like?

**Comment by Haoyi-Han** [comment]
Thank you for your attention. I rechecked my problem and realised that it seems to be still relating to the excess of argument length in a terminal, instead of the program `pandoc` itself (which means pandoc is not launched due to terminal issue).

But I'd like that there be a solution for pandoc to handle a folder with large number of documents, after all this problem is probably originated from inconvenience for me to use pandoc for a directory of markdown documents. So as a workaround, pass all their paths to pandoc which may exceed the length limits (In Windows it is 32767 chars), and another workaround, the merge operation, may break the toc which could be built from original order and names of markdown documents. 

I'd appreciate it if there is a better way to do it. Thank you very much.

Here are modified reproducing codes for test:

```python
from pathlib import Path
import subprocess


def make_book(src_dir: Path, output_epub: Path):
    md_list: list[Path] = list(src_dir.rglob("*.md"))
    md_list.sort()

    pandoc_flags = [
        "--from=markdown",
        "--to=epub",
        "--metadata title='My Book'",
        f"-o {str(output_epub)}",
    ]

    pandoc_cmd = ["pandoc"] + list(map(str, md_list)) + pandoc_flags

    subprocess.run(args=pandoc_cmd)


def mock_book_src(src_dir: Path) -> bool:
    num: int = 500
    md_filelist: list[Path] = [
        (src_dir / f"00000000_00000000_00000000_{i:09d}.md") for i in range(1, num + 1)
    ]
    for idx, file_t in enumerate(md_filelist):
        with file_t.open("w", encoding="utf-8") as ft:
            ft.write(f"# Episode {idx + 1}\n\nThis is a test.\n")
    return True


def mock_book_src2(src_dir: Path) -> bool:
    num: int = 50000
    md_filelist: list[Path] = [(src_dir / f"{i:05d}.md") for i in range(1, num + 1)]
    for idx, file_t in enumerate(md_filelist):
        with file_t.open("w", encoding="utf-8") as ft:
            ft.write(f"# Episode {idx + 1}\n\nThis is a test.\n")
    return True


def clean_mock_book(src_dir: Path):
    md_filelist: list[Path] = list(src_dir.rglob("*.md"))
    for md_file in md_filelist:
        md_file.unlink()


if __name__ == "__main__":
    target_input_dir = Path("./MyBookSource")
    target_output_file = Path("./MyBook.epub")

    if target_input_dir.exists():
        clean_mock_book(target_input_dir)
    else:
        target_input_dir.mkdir()

    # mock_book_src(target_input_dir)
    mock_book_src2(target_input_dir)
    make_book(
        src_dir=target_input_dir,
        output_epub=target_output_file,
    )
    clean_mock_book(target_input_dir)
```

**Comment by jgm** [comment]
> Thank you for your attention. I rechecked my problem and realised that it seems to be still relating to the excess of argument length in a terminal, instead of the program pandoc itself (which means pandoc is not launched due to terminal issue).

OK, I don't think this needs any changes in pandoc, then.

In general, I don't think pandoc should be in the business of working around OS-level filename length restrictions.
