### ISSUE TITLE
Losing table classes in HTML to HTML conversion

### ISSUE THREAD

**Issue by dubsarGimillu** [jgm/pandoc#9320]
I run a static site generated from HTML fragments and Pandoc templates. I could keep HTML classes and ids on `table` and `td` elements when I generated a page in June 2022, but when I rebuild the same page today those attributes of the input HTML get erased in the output HTML. 

This is serious since users need the `id` attributes to navigate the parallel-text editions.

Tables with styling on a `colgroup` tag are mangled even more unpredictably  depending on the contents of each `td` and `th` in the table.

eg. running `pandoc test-parallel-text-input.html --from html+raw_html -o test-parallel-text-output.html`

on a valid HTML file containing the following lines (cannot quote because Github, can not attach because Github) 

```
    <table class="parallelText">
    <colgroup>
        <col style="width:50%" />
        <col style="width:50%" />
    </colgroup>
    <thead>
        <tr class="header">
            <th>Left</th>
            <th>Right</th>
        </tr>
    </thead>
    <tbody>
        <tr id="row-a">
            <td class="notEnglish">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mattis, nunc quis condimentum rutrum, dui lectus interdum nisi, quis pellentesque lorem ipsum quis est. Aliquam porttitor, erat eget scelerisque eleifend, est odio fringilla augue, eget auctor dui ligula id nibh.</td>
            <td>In mollis et libero non aliquet. In hac habitasse platea dictumst. Suspendisse eleifend metus a elit efficitur, ut consectetur mauris ornare. Nam aliquet egestas nunc eget convallis. Ut ac dolor quam. Integer venenatis, ex id tincidunt congue, nibh sem porttitor purus,</td>
        </tr>
        <tr id="row-c">
            <td class="notEnglish">ccccc</td>
            <td>ddddd</td>
        </tr>
    </tbody>
</table>
```
produces the following HTML fragment with attributes deleted from the table and td elements:

```<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>Left</th>
<th>Right</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mattis, nunc quis condimentum rutrum, dui lectus interdum nisi, quis pellentesque lorem ipsum quis est. Aliquam porttitor, erat eget scelerisque eleifend, est odio fringilla augue, eget auctor dui ligula id nibh.</td>
<td>In mollis et libero non aliquet. In hac habitasse platea dictumst. Suspendisse eleifend metus a elit efficitur, ut consectetur mauris ornare. Nam aliquet egestas nunc eget convallis. Ut ac dolor quam. Integer venenatis, ex id tincidunt congue, nibh sem porttitor purus,</td>
</tr>
<tr class="even">
<td>ccccc</td>
<td>ddddd</td>
</tr>
</tbody>
</table>
```
**Pandoc version?**
What version of pandoc are you using, on what OS? (If it's not the latest release, please try with the latest release before reporting the issue.)

**Pandoc version** pandoc 2.9.2.1 on Ubuntu

Previous discussion https://github.com/jgm/pandoc/discussions/9318

**Comment by jgm** [comment]
Oh, wait -- pandoc 2.9.2.1?  Released in March 2020?

Please try the latest version before submitting a bug report.

**Comment by dubsarGimillu** [comment]
> Oh, wait -- pandoc 2.9.2.1? Released in March 2020?
> 
> Please try the latest version before submitting a bug report.

Installing pandoc 3.1.11 seems to fix the problem.  I wonder if I installed pandoc on this box from an old repository rather than the latest `.deb`?
