### ISSUE TITLE
From HTML to Markdown. --strip-comments=false doesn't work?

### ISSUE THREAD

**Issue by jsx97** [jgm/pandoc#9322]
I have an HTML file, the first line of which is a comment, and I want to convert it to Markdown.

```
<!-- commment -->
<h1>heading</h1>
<p>body</p>
```

```
pandoc from.htm -o to.md --strip-comments=false
```

For some reason, the comment is nevertheless stripped, and the output is simply

```
# heading

body
```

instead of

```
<!-- comment -->

# heading

body
```

**Comment by jsx97** [comment]
Thanks. Interesting, when I use `-f html+raw_html`, it seems I don't even need `--strip-comments=false`. I can omit it or even replace it with `--strip-comments=true`. So it seems there is no need to use `--strip-comments` then?

**Comment by jgm** [comment]
`--strip-comments` is mainly useful when you're doing `-f markdown`, which enables the `raw_html` extension by default.
