### ISSUE TITLE
Don't emit unnecessary classes in HTML tables

### ISSUE THREAD

**Issue by ThomasSoeiro** [jgm/pandoc#9325]
It is currently not possible to prevent `pandoc` from adding attributes to the HTML output from a Markdown input (e.g. `.header`, `.odd`, `.even` in the ReprEx below). It is only possible to [drop attributes using filters](https://stackoverflow.com/q/53403041).

Since both the CommonMark and GitHub Flavored Markdown specs do not mention default attributes in HTML output, shouldn't this be opt-in by default? Or possible to opt-out at least?

# ReprEx

Using e.g. this input:

```
| foo | bar |
| --- | --- |
| baz | bim |
| baz | bim |
```

And converting to HTML using `pandoc --from gfm --to html5`, we get:

```html
<table>
<thead>
<tr class="header">
<th>foo</th>
<th>bar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>baz</td>
<td>bim</td>
</tr>
<tr class="even">
<td>baz</td>
<td>bim</td>
</tr>
</tbody>
</table>
```

**Comment by jgm** [comment]
These are harmless; just don't add CSS rules that do things with them.

I don't think adding the option to avoid these is worth the increase in complexity.

**Comment by jgm** [comment]
Agreed -- we could use something like table-header, even-row, odd-row.
Of course, it would be a backwards-incompatible change, so I'm not sure it's a good idea.

**Comment by ThomasSoeiro** [comment]
I just noticed the following in the html output:

```css
    header {
      margin-bottom: 4em;
      text-align: center;
    }
```

Shouldn't `header` be `.header`?

**Comment by jgm** [comment]
> My concern was for the sake of dropping "unecessary" classes to prevent name clashes since we can easely select .header using thead and .odd/even using variations of tbody tr:nth-child(2n).

This is true, though it wasn't in earlier versions of pandoc (when nth-child wasn't supported and we didn't put the header in thead!).

I think it might be worth stopping using these classes, and using the alternative you suggest instead.

**Comment by tarleb** [comment]
Could this be a "good first issue"?

**Comment by jgm** [comment]
Yes, it would be an easy one -- just have to change the HTML writer, the styles.html template, and some tests I think.

**Comment by ThomasSoeiro** [comment]
Could you point me to the HTML writer please?
(I'll have a look but I don't know Pandoc internals nor haskell...)

**Comment by jgm** [comment]
I think that if you can't find the HTML writer yourself, you're unlikely to be able to fix this issue, so I'll leave that as an exercise to the reader. :)

**Comment by gregdan3** [comment]
For what it's worth, I just ran into this issue- I was using the classname `header` and I didn't want or expect the class to be on every `thead`. I would've used a lua filter to omit it, but I can't find a way to remove classes via a filter- I suspect that's related to #684?

But uh, my use case is incredibly silly.
I'm building my site with Pandoc, and I want it to be able to render readably on the Nintendo DS Browser. That browser throws out CSS rules for elements it doesn't recognize, and it doesn't recognize any semantic html elements including `header`- it does recognize CSS rules for classes though, so I (reasonably I thought) assigned a class `header` to the element `header`, and then moved all my header style rules to that class. And that worked great, until I spotted every `thead` with its content squashed to the left. Anyway, I'll just rename my header for now. 

Funny enough, my silly usecase is exactly the one where I'd still want the odd/even/header classes to style, since I explicitly want to target older browsers that lack the CSS. 

I'm only familiar with pandoc as a user, not a dev, but why not shunt these classes into an extension rather than remove them entirely?

**Comment by bpj** [comment]
Can you give an example of your (markdown?) source? If I understand you correctly you are adding a class `.header` to your heading elements like

``````
## Heading {.header}
``````

which conflicts with the `header` class which Pandoc adds automatically to `<thead>` elements in HTML?

It does indeed seem like your options are

1.  to use another custom class name like `.heading`.[^1]
2.  to post-process your HTML removing the `header` class from `<thead>` elements.

Obviously 1 is the easier option if possible.

[^1]: A class `.heading` has the advantage of being terminologically correct: tables have headers but sections have *head**ing**s*. Pandoc calling its heading class `Header` is a misnomer (which it is too late to change!)

**Comment by bpj** [comment]
This minimal Lua filter will change the class on all "Header" elements.

``````lua
-- Predicate function to filter out 'header' class
local is_not_header_class = function(x)
  return 'header' ~= x
end

-- Global function to process heading elements
Header = function(head)
  -- -- Restrict to heading levels 2 through 4 (<h2>, <h3>, <h4>)
  -- if 2 > head.level or 4 < head.level then
  --   return nil -- leave unchanged
  -- end
  if head.classes:includes('header') then
    -- Make sure not to remove other classes!
    head.classes = head.classes:filter(is_not_header_class)
    head.classes:insert(1, 'heading')
    return head
  end
  -- Else leave unchanged
  return nil
end
``````

**Comment by gregdan3** [comment]
> If I understand you correctly you are adding a class .header to your heading elements

Ah, sorry, I'm adding a class to my `header` element, which is not one that pandoc emits. I'm substituting my generated markdown into an HTML template to make the base of every page, since there's a fair amount of web specific stuff that markdown doesn't want or need to do. 

My template, trimmed some:

```html
<!DOCTYPE HTML>
<html lang="en-US">
  <head>
    <!-- metadata -->
  </head>
  <div class="body">
    <div class="-header"> 
        <!-- initial page content -->
    </div>

    <div class="article">
      $for(include-before)$ $include-before$ $endfor$ $body$
      $for(include-after)$ $include-after$ $endfor$
    </div>

    <div class="footer">
        <!-- end of page content -->
    </div>

  </div>
</html>
```
Example page:

```md
---
title: test page!
date: 2024-05-30
author: gregdan3
description: a secret test page for all my formatting
---

# Tables

|     center aligned     | left aligned  | right aligned | default alignment |
| :--------------------: | :------------ | ------------: | ----------------- |
|        Item1.1         | Item2.1       |       Item3.1 | Item4.1           |
| **_bold italic item_** | Item2.2       |       Item3.2 | `mono item`       |
|        Item1.3         | **bold item** |       Item3.3 | Item4.3           |
|        Item1.4         | Item2.4       |       Item3.4 | Item4.4           |
```

Gluing these together:

```bash
cat pages/test.md | pandoc --lua-filter=pandoc/filters.lua --from=markdown+yaml_metadata_block+wikilinks_title_after_pipe-definition_lists-smart \
        --template=templates/default.html \
        --metadata="directory:test.md" \
        -o build/test.html
```

And the result:

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <!-- metadata -->
  </head>
  <div class="body">
    <div class="-header">
      <!-- initial page content -->
    </div>

    <div class="article">
       <h1 id="tables">Tables</h1>
<table>
<thead>
<tr class="header">
<th style="text-align: center;">center aligned</th>
<th style="text-align: left;">left aligned</th>
<th style="text-align: right;">right aligned</th>
<th>default alignment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Item1.1</td>
<td style="text-align: left;">Item2.1</td>
<td style="text-align: right;">Item3.1</td>
<td>Item4.1</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong><em>bold italic
item</em></strong></td>
<td style="text-align: left;">Item2.2</td>
<td style="text-align: right;">Item3.2</td>
<td><code>mono item</code></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Item1.3</td>
<td style="text-align: left;"><strong>bold item</strong></td>
<td style="text-align: right;">Item3.3</td>
<td>Item4.3</td>
</tr>
<tr class="even">
<td style="text-align: center;">Item1.4</td>
<td style="text-align: left;">Item2.4</td>
<td style="text-align: right;">Item3.4</td>
<td>Item4.4</td>
</tr>
</tbody>
</table>
      
    </div>

    <div class="footer">
      <!-- end of page content -->
    </div>
  </div>
</html>
```

Also, I was mistaken before; it was the first `tr` being given the class `header`, not `thead`.
