### ISSUE TITLE
Asymmetries between pandoc's markdown and commonmark

### ISSUE THREAD

**Issue by hseg** [jgm/pandoc#9329]
Playing with the various markdown flavors supported by pandoc, I noticed some unexpected differences in the convenience features between pandoc's markdown and commonmark that made passing between the two more annoying (one of which is "the feature doesn't exist in commonmark", forcing me into pandoc's markdown):
- Citations are only supported in pandoc's markdown
- The `#.` syntax for autonumbered fancy lists is only supported in pandoc's markdown
- Raw latex code isn't escaped in pandoc's markdown, but is in commonmark unless wrapped in code blocks
- Autowrapping nodes not supporting attributes in divs/spans if an attribute is attached anyway is only supported in commonmark

The first one is a dealbreaker, and forced me into pandoc's markdown, but the last one makes me really wish for commonmark. Could the gap be narrowed somewhat? My naive understanding before this was that the two dialects differed just in their default extension sets, but this is more than that.

At the very least, in cases where there is divergence, it'd be good if the reasoning for it were clearly articulated somewhere.

**Comment by jgm** [comment]
Entirely different parsers are used, and they use very different parsing strategies.

Citation support for commonmark-extensions has been a priority, but it's surprisingly nontrivial. You can look at the issue there for more context.

There's also an issue in this repository about allowing attributes to be added everywhere.

But I don't think there's much point in putting up an issue like this that just calls attention to these disparate issues, so I'll close this.

**Comment by hseg** [comment]
On Wed, Jan 10, 2024 at 02:16:37PM -0800, John MacFarlane wrote:
> Entirely different parsers are used, and they use very different parsing strategies.
> 
> Citation support for commonmark-extensions has been a priority, but it's surprisingly nontrivial. You can look at the issue there for more context.
> 
> There's also an issue in this repository about allowing attributes to be added everywhere.
> 
> But I don't think there's much point in putting up an issue like this that just calls attention to these disparate issues, so I'll close this.

Fair enough -- ticket wasn't well-thought out.
For future reference, the issues referred to are
https://talk.commonmark.org/t/cross-references-and-citations/4013
https://github.com/jgm/pandoc/issues/684
