### ISSUE TITLE
`--metadata-file=` argument has no effect

### ISSUE THREAD

**Issue by mTyETy** [jgm/pandoc#9330]
**Explain the problem.**
When the metadata is specified inside the markdown file, pandoc can work. In my case, I got the following output

```
 $ pandoc -f markdown --mathml
---
header-includes: |
  \newcommand{\Tau}{\mathcal{T}}
---
$\Tau$
^Z
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>𝒯</mi><annotation encoding="application/x-tex">\mathcal{T}</annotation></semantics></math></p>
```

But when the meta-data is written in a _**file**_ named `meta.yaml`, the metadata seems not received by pandoc at all.

```
 $ pandoc --metadata-file=meta.yaml -f markdown --mathml
$\Tau$
^Z
[WARNING] Could not convert TeX math \Tau, rendering as TeX:
  \Tau
      ^
  unexpected control sequence \Tau
  expecting "%", "\\label", "\\tag", "\\nonumber", whitespace or "\\allowbreak"
<p><span class="math inline">$\Tau$</span></p>
```
The content of `meta.yaml` is 
```yaml
header-includes: |
  \newcommand{\Tau}{\mathcal{T}}
```

I also tried for actual files using `pandoc file.md --metadata-file=meta.yaml -o file.html`. The same issue occurs. 

**Pandoc version?**
 ```
 $ pandoc -v
pandoc.exe 3.1.11.1
```

**Comment by jgm** [comment]
Yes, this is expected.  When the metadata is in the markdown file, the markdown parser has access to it.  When it's in an external file, it is added later, after the markdown parser has parsed the markdown file, so the parser doesn't have access to it.

**Comment by jgm** [comment]
Currently we do `mathInline >>= applyMacros` in the Markdown reader.

`applyMacros` uses `extractMacros` to extract the macro definitions from the parser state (it just retrieves them from the `stateMacros` field, which has been populated with the macro parsed from the metadata).

To change how this works, we'd have to completely change the way we handle `metadata-file`.

First, we'd have to parse the metadata file first, before running the Markdown parser.

Then, somehow we'd have to inject the information it has about macros into the parser state for the Markdown parser. There isn't a way to do this without significant architectural and API changes.

So, I think I'm going to consider this a no.  (Of course, anything is possible, but this would involve a lot of additional complexity which I'd like to avoid.)

**Comment by jgm** [comment]
Note: if you want to keep your metadata in a separate file, but still have the macros accessible when parsing your markdown content, just don't use `--metadata-file.` Instead, make sure the YAML in your metadata  file is enclosed in
```
---

...
```
and then pass this file as the first file argument, before your content file.

```
pandoc metadata.yaml content.md
```
Pandoc will just concatenate these and parse them together.

**Comment by jgm** [comment]
`--metadata-file` is only really useful when you're using the metadata with non-markdown source formats.
