### ISSUE TITLE
Internal link to a heading which itself is a web link

### ISSUE THREAD

**Issue by kleinbottle** [jgm/pandoc#936]
I want to create an internal link to a heading where the heading itself is a web link. Here is my MWE:

```
This is a link to [heading one](#heading-one).

This is a link to [heading two](#heading-two).

# Heading One

# [Heading Two][weblink]

[weblink]: www.example.com
```

The resulting HTML is:

```
<p>This is a link to <a href="#heading-one">heading one</a>.</p>
<p>This is a link to <a href="#heading-two">heading two</a>.</p>
<h1 id="heading-one">Heading One</h1>
<h1 id="heading-twoweblink"><a href="www.example.com">Heading Two</a></h1>

```

The second case should give an internal link with the same behaviour as the first.

**Comment by jgm** [comment]
I'm persuaded by the circularity argument.
I don't see anything we can do about this; I think it's just a case where you need to specify the id explicitly:
```
[Heading Two][weblink] {#heading-two}
```
