### ISSUE TITLE
Html to docx with inline styles

### ISSUE THREAD

**Issue by KaioSpa** [jgm/pandoc#9368]
Hey, I've been trying to figure this out, but it seems like there might be a bug in the html to docx conversion. Here's the situation:

I'm using a rich text editor where users input text, saved as HTML in the database. Users can customize the text, and I'm providing an option to save this data as a DOCX file. However, when the user used formatting, like this:

```
<p style="text-align: right;"><span style="font-size: 8pt;">Sample text</span></p>
```
it doesn't carry over when I convert it to DOCX using the following process:

```
$process = new Process([
    'pandoc',
    '--from',
    'html',
    '--to',
    'docx',
    '--mathml',
    $inputFilePath,
    '-o',
    $outputFilePath
]);
$process->run();
```
Is there a proble with the conversion? i couldnot find anything in the docs.
**Pandoc version?**
3.1.11.1

**Comment by jgm** [comment]
Font size details are ignored.
Please read the first few paragraphs of the user's guide.

**Comment by richingm** [comment]
@KaioSpa Excuse me, has this problem been resolved? If so, how was it resolved?

**Comment by richingm** [comment]
> Font size details are ignored. Please read the first few paragraphs of the user's guide.

Is this correct?  But it seems to have no effect.  

 pandoc --from html -f html+native_divs+native_spans+raw_html --to docx  -o x.docx

**Comment by KaioSpa** [comment]
> @KaioSpa Excuse me, has this problem been resolved? If so, how was it resolved?

It's jus how the API works... So, no.
