### ISSUE TITLE
pandoc does not set `<title>` despite emitting `Defaulting to '<basename>' as the title.`

### ISSUE THREAD

**Issue by ThomasSoeiro** [jgm/pandoc#9370]
When writing to a (custom) html template, pandoc does not set `<title>` despite emitting `Defaulting to '<basename>' as the title.`

However, I am glad with the current behaviour (i.e. warn that a title is needed + not setting the title + advice on how to set the title using pandoc). I think setting the title automatically would be too invasive (e.g. I want to set the title later using js).

template.html:

```
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
      $body$
  </body>
</html>
```

source file:

```
echo hello world > test.md
```

convert to html:

```
pandoc -f commonmark -t html5 --template=template.html test.md
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'test' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
      <p>hello world</p>
  </body>
</html>
```

```
pandoc -v
pandoc 3.1.11.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: C:\Users\A141800\AppData\Roaming\pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
The default template has this:
```
  <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
```
Do you have something similar in your custom template?  You need `$pagetitle$` not `$title$`.

**Comment by ThomasSoeiro** [comment]
It works as expected with `$pagetitle$`:

```
$ cat template.html 
<!DOCTYPE html>
<html>
  <head>
    <title>$pagetitle$</title>
  </head>
  <body>
      $body$
  </body>
</html>
``` 

```
pandoc -f commonmark -t html5 --template=template.html test.md
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'test' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
  </head>
  <body>
      <p>hello world</p>
  </body>
</html>
```

However, I want that pandoc do not set the title so I do not have `$pagetitle$` in my template on purpose. pandoc reports `Defaulting to '<basename>' as the title.` anyway. I think that this is misleading, hence the report.

---

I did not used the same machine (but should not make any difference):

```
$ pandoc -v
pandoc 3.1.3
Features: -server +lua
Scripting engine: Lua 5.4
User data directory: /home/manon/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
It's true that the warning is misleading if you're not using a template that uses `pagetitle`.  But currently pandoc doesn't have information about which variables a template includes, so there isn't a way to check.

It could be interesting to expose a function in jgm/doctemplates that would return a list of the variables in a template.  (This would be trivial to write.) We could then check to see if the template contains `pagetitle` before emitting the warning.

**Comment by ThomasSoeiro** [comment]
I have just noticed that we get a warning even if the `<title>` element is defined in the template. Perhaps this should be fixed as well?

template.html:

```
<!DOCTYPE html>
<html>
  <head>
    <title>The title is set!</title>
  </head>
  <body>
      $body$
  </body>
</html>
```

source file:

```
echo hello world > test.md
```

convert to html:

```
pandoc -f commonmark -t html5 --template=template.html test.md
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'test' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
<!DOCTYPE html>
<html>
  <head>
    <title>The title is set!</title>
  </head>
  <body>
      <p>hello world</p>
  </body>
</html>
```

```
pandoc -v
pandoc.exe 3.4
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: C:\Users\A141800\AppData\Roaming\pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
We would have to read and parse the template on every invocation.  Not worth it, in my opinion (performance price for every use just to deal with this one unusual use).  Just add a pagetitle to avoid the warning?

**Comment by ThomasSoeiro** [comment]
> We would have to read and parse the template on every invocation. Not worth it, in my opinion (performance price for every use just to deal with this one unusual use). Just add a pagetitle to avoid the warning?

I understand that it is not worth it. Yet, I do not want to add a variable that I do not need to silence a warning. Perhaps the warning could be reworded (e.g. state that it does not apply if `<title>` is already set).

> EDIT: checking the template for the presence of a pagetitle variable, as suggested above, would also help with this. That is why I am keeping this issue open, but it would need work in doctemplates.

Glad to hear that, but unfortunately I am not able to help...

Thanks!

**Comment by jgm** [comment]
The change to doctemplates should be easy; I'll make a note to work on that.
