### ISSUE TITLE
<ol> start Attribute not allowed in epub2

### ISSUE THREAD

**Issue by mementum** [jgm/pandoc#9380]
pandoc version: `3.1.11.1`

Source format: *markdown*
Target format: *epub2*

Example:

```
> b) hello
```
This will, surprisingly generate an `<ol start=2 ...>` which is not allowed in the `epub2` standard. The "surprise" here: the `b)` is inside a blockquote and should therefore, imho, not be touched.

Another example:

```
(C) 2024
```

This will also be interpreted as an ordered list and then `<ol start=3 ...>` will be generated. The leading `(` should actually be enough for the combination to not be treated as an ordered list.

Note: yes, one can escape as in `\)` and it will work.

**Comment by jgm** [comment]
Can you point to documentation on start not being allowed in epub 2?

**Comment by jgm** [comment]
PS. block quotes are not verbatim blocks. Their contents are interpreted as Markdown.

**Comment by jgm** [comment]
OK, I can see that epubcheck gives a validation error for this.  However, there seems to be no obvious alternative or workaround.

One important question is whether readers actually support the start attribute, despite it being invalid. If they do, then generating it may be better than the alternative of not generating it and changing the semantics.

If you simply want to prevent pandoc from generating a start attribute in your document, there are a couple of ways to do that.

In the case above, you apparently just want a literal `b)`, so you can escape the `)` to prevent it being parsed as a list:

```
> b\) hello
```

Alternatively, you can turn off "fancy lists" altogether (`-f markdown-fancy_lists`). However, `start` will still be generated if you write e.g.

````
> 2. hello
````

**Comment by mementum** [comment]
Thanks for the feedback. Escaping the parenthesis is what I already do, but this may be, frankly, difficult for other people to pinpoint.

The point is not the readers, but the self-publishing shops which will run a validation on the "epub", reject the file and spit out an error saying:

> attribute start is not allowed here [672,23] ch001

Not even actually giving an indication that the `<ol>` attribute is where this happens. For many users it will be a huge challenge, for starters, to understand that the `epub` file is actually a `zip` file and it the reported line and column may be manually inspected.

The only workaround I can personally imagine is:

  - To have an extension which disables generation of `<ol>` if `start` is going to be greater than 1.

Why:

  - I just need a hand to count number of occasions in which I have not started a list with `1.` or `a)` and I have written a couple of bibles.

The user of such an extension is probably looking for verbatim content in blockquotes or similar use cases.

Extension which could be called like this:

  - `-f markdown+no-start-lists`

As I don't speak Haskell, but can for sure appreciate the huge complexity `pandoc` has in the background, it is probably not worth the effort.

Thanks for everything in any case.

Let me close the issue with the comment. I guess it may be reopened if the extension idea is deemed worth at least 2 cents.

Best regards

**Comment by jgm** [comment]
> To have an extension which disables generation of `<ol>` if start is going to be greater than 1.

It would be quite bad to have a list simply disappear.

I think I'll just close this.
