### ISSUE TITLE
LaTeX > ePub toc.ncx & nav.xhtml : link wrong

### ISSUE THREAD

**Issue by sithscho** [jgm/pandoc#9383]
in LaTeX I use

\section{label}

in ePub this becomes

<a href="ch002.xhtml#label"

Problem is: 

In my ePub there are 3 sections created: ch001 ch002 and ch003.

The \section{label} is in ch002…

but in the toc.ncx and nav.xhtml the link is "ch001.xhtml#label"

It gehts the chapter file wrong. And thus the link gets an error for being not there… of course.

I think this is clearly a Bug to fix.

**Comment by jgm** [comment]
Can you provide a complete LaTeX sample that is sufficient to generate the bug, so we can test?

**Comment by jgm** [comment]
PS. I have seen similar things and would like to get to the bottom of this. But having a small input that allows us to reproduce the issue is key.

**Comment by sithscho** [comment]
Ok… I found the reason why this is happening:

in my book (like in any book) there is a part before the book really starts… consisting of information about the author, about the editor etc.

… this part obviously has no chapter heading… it only uses \section*{} to structure ist, but this is not meant to be in the table of contents anyway.

… and –perhaps– this chapter has the same 'name' as the main chapter (the content of the book)…

I assume that this is the reason for the errors, because everything is all right when I add a \chapter{} before this 'book information' part…

So one solution might be that pandoc does not include \section*{} and \subsection*{} headings as links… because they are not meant to be headings but just for structuring the text… (what the '*' clearly shows)… they don't appear in the LaTeX table of contents, so why should they appear in an ePub table of contents…

**Comment by sithscho** [comment]
… and a workaround seems to be…

… adding a \chapter{The Book} before any \section*{} or \subsection*{}… then the error vanishes…

… however… this is far from looking good…

**Comment by sithscho** [comment]
… ok… you can add a \chapter*{ } line… (with a <space> as chapter name…

… that does the trick…

**Comment by jgm** [comment]
I think I found and fixed the bug.
