### ISSUE TITLE
Wrapped lines shouldn't start with `/`

### ISSUE THREAD

**Issue by ntjess** [jgm/pandoc#9386]
```tex
\documentclass{article}
\begin{document}
A string of text that is long enough that after 73 chars that includes a / slash creates a newline
\end{document}
```

This produces the typst document
```typst
A string of text that is long enough that after 73 chars that includes a
/ slash creates a newline
```

But since `/` is the syntax for creating a [term list](https://typst.app/docs/reference/model/terms/), the following error occurs during typst compilation:
```console
expected colon
```

In short, `typst` conversions should not allow a new line of text to split on `/` unless that character is escaped.

**Comment by jgm** [comment]
Moving to pandoc -- typst-hs handles the parsing, not the rendering.

**Comment by ntjess** [comment]
Right, one way to resolve this situation is to resolve `/` as an escaped slash (`\/`) similar to how `(` and `=` are escaped at present. Though this _does_ create a lot of noise since in most cases an unescaped character is just fine

**Comment by jgm** [comment]
I will make it escape the / only when wrapped to the beginning of a line.

**Comment by jgm** [comment]
I will also reduce noise on ( and =
