### ISSUE TITLE
Figure size in `\linewidth` should be converted to `%`

### ISSUE THREAD

**Issue by ntjess** [jgm/pandoc#9388]
Pandoc successfully converts `textwidth` already, but the same logic should also apply to `linewidth`.

Currently, `\linewidth` is preserved leading to an error in converted documents:
```tex
\begin{figure}
\centering
\includegraphics[width=0.5\linewidth]{figures/placeholder}
\caption{Example figure}
\end{figure}
```

Converts to
```typst
#figure([#box(width: 0.5\linewidth, image("figures/placeholder"));],
  caption: [
    Example figure
  ]
)
```

**Comment by janosh** [comment]
perhaps worth mentioning `typst` somewhere in this issue for searchability
