### ISSUE TITLE
Markdown -> EPUB conversion preserves comments that are invalid in XHTML

### ISSUE THREAD

**Issue by AbeJellinek** [jgm/pandoc#9419]
**Explain the problem.**

Comments containing two hyphens in a row (`--`) or a triple-hyphen closing tag (`--->`) are [valid in HTML5](https://html.spec.whatwg.org/#comments) but [invalid in XML/XHTML](https://www.w3.org/TR/xml/#sec-comments). When a standards-compliant XHTML parser encounters a comment containing that character sequence, it generates a parser error and stops parsing the rest of the document. Pandoc currently preserves these invalid comments when outputting EPUB XHTML. The outputted EPUB causes a parser error in Apple Books and other reader software that requires valid XHTML, and content following the invalid comments is not displayed.

`book.md`:

```markdown
<!-- This comment will be preserved. -->

<!-- This comment -- invalid in XHTML because of the double hyphens and
     triple-hyphen closing tag -- will also be preserved. --->

This content will be lost in some reader software.
```

`$ pandoc book.md -o book.epub`

---

Generated XHTML (`EPUB/text/ch001.xhtml`):

```xhtml
<!-- This comment will be preserved. -->
<!-- This comment -- invalid in XHTML because of the double hyphens and
     triple-hyphen closing tag -- will also be preserved. --->
<p>This content will be lost in some reader software.</p>
```

Result when opened in Apple Books:

<img width="407" alt="image" src="https://github.com/jgm/pandoc/assets/1770299/4fbb9296-5aee-4e00-abab-747f716c9941">

EPUBCheck indicates a fatal parsing error:

```
Validating using EPUB version 3.3 rules.
ERROR(RSC-005): ./book.epub/EPUB/content.opf(8,14): Error while parsing file: element "metadata" incomplete; missing required element "dc:title"
ERROR(RSC-005): ./book.epub/EPUB/nav.xhtml(13,126): Error while parsing file: Anchors within nav elements must contain text
FATAL(RSC-016): ./book.epub/EPUB/text/ch001.xhtml(16,21): Fatal Error while parsing file: The string "--" is not permitted within comments.

Check finished with errors
Messages: 1 fatal / 2 errors / 0 warnings / 0 infos

EPUBCheck completed
```

**Pandoc version?**

pandoc 3.1.11.1, macOS Sonoma 14.2

**Comment by jgm** [comment]
Markdown allows raw HTML to be passed through verbatim. Comments are an instance of this. It is entirely up to the user to make sure that this raw HTML is valid. For example, if a user writes
```
<div notvalidattribute="xxx"></span>
```
this will be passed through, leading to problematic output.

Our policy all along has been to pass through raw HTML unchanged (as markdown has always done), and this applies to comments as well.

Hence:  the recommendation is that if you use raw HTML (including comments) in your markdown source, and you intend to produce epubs, make sure they're valid in the format you're targeting. Pandoc will not fix them for you, and in many cases it would be completely unclear *how* to  fix them.

**Comment by jgm** [comment]
By the way, the `--strip-comments` option may make sense for you in this case.

**Comment by jgm** [comment]
Another reliable way to comment something out in pandoc's markdown is to put `#` at the beginning of every line and then enclose it in `---` and `...` fences. It will then be interpreted as a YAML metadata section containing only YAML comments, and it will be *completely* omitted from the output.
