### ISSUE TITLE
Add a version of pandoc.system.list_directory that contains file metadata

### ISSUE THREAD

**Issue by tionis** [jgm/pandoc#9422]
I'd like to use Pandoc's embedded Lua interpreter for scripting around some Pandoc automatizations.
My goal is comparable with a Makefile, which compares modifications dates of files and their relation to each other to decide what to recompile/parse.
For this I would only need access to the last modification time of a file, but that's not possible with the current API without relying on external commands and parsing them, which is way too brittle.
So my suggestion would be to either add a second pandoc.system.list_directory_with_metadata function that contains the typical metadata of a file like modification time.
Alternatively a function like pandoc.system.stat and pandoc.system.lstat could also be exposed to get the metadata of a single file.

**Comment by tarleb** [comment]
I tend to think that this is out of scope for pandoc, but I'm not entirely sure. My usual suggestion would be to make use of a third-party Lua package like [lfs](https://github.com/lunarmodules/luafilesystem), but I'm aware that this might not always be possible.

Could you submit a feature request to [hslua](https://github.com/hslua/hslua/issues) so I won't forget? The first step would be to add such functions there, namely in the hslua-module-system package. Then, if the decision was made to include those functions in pandoc, it would just be a matter of adding a tiny bit of code [here](https://github.com/lunarmodules/luafilesystem).

**Comment by tionis** [comment]
@tarleb Thanks for looking into this, I created an issue over at hslua and linked it here.
