### ISSUE TITLE
Image Lua filter new bug?

### ISSUE THREAD

**Issue by ricopicone** [jgm/pandoc#9441]
### Discussed in https://github.com/jgm/pandoc/discussions/9440

<div type='discussions-op-text'>

<sup>Originally posted by **ricopicone** February  9, 2024</sup>
I recently upgraded to pandoc 3.1.11.1 and a trusty Lua filter (target: tex) started behaving strangely. I thought I'd ask if this is intended behavior here before reporting it as a bug. Essentially, when the `Image` filter runs, it wraps a generic figure environment around the custom version prescribed by the filter.

filter.lua:
```lua
function figurer(el)
  local caption = el.caption
  if caption==nil then
    caption = ""
  else
    caption = pandoc.Para(caption)
    local caption_doc = pandoc.Pandoc(caption)
    caption = pandoc.write(caption_doc,'latex')
  end
  local src = el.src
  local graphics_command = "\\includegraphics["
  local fig_begin = "\\begin{figure}[H]%\n" ..
      "\\centering\n"
  local fig_end = "\\end{figure}%\n"
  -- construct latex figure
  local fig_tex = fig_begin ..
    graphics_command.."]{"..src.."}\n\\figcaption{" ..
    el.attr.identifier.."}{" .. 
    caption.."}\n" .. 
    fig_end
  return pandoc.RawInline('latex', fig_tex)
end

function Image(el) 
  return figurer(el)
end

return {
  {Image = Image}
}
```

source.md:
```markdown
![A caption.](figures/fig.png){#fig:fig}
```

Makefile:
```makefile
index.tex: source.md filter.lua
	pandoc -f markdown --lua-filter filter.lua -o $@ $<
```

index.tex:
```latex
\begin{figure}
\centering
\begin{figure}[H]%
\centering
\includegraphics[]{figures/fig.png}
\figcaption{}{A caption.}
\end{figure}%
\caption{A caption.}\label{fig:fig}
\end{figure}
```

There are two problems: (1) the generic figure environment wrapped around the custom one and (2) the identifier is not getting properly passed to the filter (but it does get used in the generic outer environment). Help appreciated!</div>

**Comment by jgm** [comment]
Please don't open BOTH an issue and a discussion comment; one suffices.
