### ISSUE TITLE
Pandoc ignores empty lines when converting .docx to .tex

### ISSUE THREAD

**Issue by Photon89** [jgm/pandoc#9443]
**Explain the problem.**
I am trying to convert a fill in the blank script, which contains many vertical spaces to be filled in by the students, from .docx to .tex. However, pandoc ignores empty lines and thus the whole layout is not fitting any more, so I'd need to tediously restore the vertical spaces by hand, as the information is lost during conversion.

It would be great to have something like 

"empty line" in .docx -> `\vspace{1em}` in .tex

 or, even better, 

"n successive empty lines" in .docx -> `\vspace{n em}` in .tex.

Unfortunately, I cannot upload a .docx file as minimal example, but it is easy to check, just paste something like the following into an empty .docx file:

```
a





b
```

Pandoc's output will be:

```
a

b
```

I call pandoc simply by

```
pandoc test.docx -o output.tex
```

**Pandoc version?**
```
pandoc 3.1.11.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/photon/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by Photon89** [comment]
After reading the docs more thoroughly, I guess, what I need is the `empty_paragraphs` option for the LaTeX writer.

**Comment by Photon89** [comment]
Sorry to bother again, but as `empty_paragraphs` is currently not available for the LaTeX writer, as far as I can see, the issue is not yet solved for me! :smiley:

**Comment by jgm** [comment]
I assume you have tried `-f docx+empty_paragraphs -t latex`?

In any case, this isn't the kind of thing pandoc is meant to support. Read the first few paragraphs of the manual.  We try to capture structural elements of a text, not presentation details like this.

**Comment by Photon89** [comment]
@jgm Now I did, but it didn't have any effect, unfortunately... And `-t latex+empty_paragraphs` tells me

```The extension empty_paragraphs is not supported for latex```

> In any case, this isn't the kind of thing pandoc is meant to support. Read the first few paragraphs of the manual. We try to capture structural elements of a text, not presentation details like this.

But the `empty_paragraphs` option does exist for other formats, so why not for .tex as well? I just can't find anything better than pandoc for my use case, but the issue in question makes it really tough to continue with the generated .tex code...

**Comment by jgm** [comment]
I suppose we could consider enabling `empty_paragraphs` in latex output.
Representing it as `\vspace{1em}` is a bit unprincipled, but maybe useful.

**Comment by jgm** [comment]
Actually
```
\par{\hspace{0em}}
```
is a bit better; it will get the proper parskip and other spacing.

**Comment by jgm** [comment]
Better: `\hfill\par`

**Comment by Photon89** [comment]
Thanks a lot for the quick fix, I compiled the latest commit and it works very nicely! :smiley:
