### ISSUE TITLE
Broken typefaces in generated markdown due to spaces at the beginning/end

### ISSUE THREAD

**Issue by wsakernel** [jgm/pandoc#9445]
When converting from man to gfm, the roff snippet `\fB--c \fI<file>` produces the markdown snippet `**--c ***\<file\>*`. This will not work when adding it to a Github wiki because the space character after 'c' is not proper markdown according to my research. The asterisks closing boldface should be attached to the letter 'c', so it should be `**--c** *\<file\>*`. Note that the space is now after the asterisks closing boldface. I confirmed this also happens with "Try pandoc". The same problem exists with a space after the opening boldface as in `\fB --c \fI<file>` which will generate `** --c ***\<file\>*`.

**Comment by jgm** [comment]
I believe we currently have some code in other readers that works around this sort of thing.
```
% pandoc -f html -t native
a<i> hi </i>b
[ Plain
    [ Str "a" , Space , Emph [ Str "hi" ] , Space , Str "b" ]
]
```
The function that does this is `extractSpaces`:
https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Shared.hs#L327-L342

It should be a fairly simple matter to integrate this into the man reader.
For an example of its use in the HTML reader, see
https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Readers/HTML.hs#L910-L913

**Comment by wsakernel** [comment]
Wow, this was blazingly fast. Thank you very much!

Looking from the outside, I wonder a little that it got fixed in the reader. Because it means every reader needs to be aware of this problem. Since the issue stems from a semantic speciality of the markdown format, I would have expected a fix in the writer. But again, I don't know the big picture of pandoc.

**Comment by jgm** [comment]
Conceptually, you're right, it probably belongs in the writer.  I don't know why we've been doing it this way.  But markdown isn't the only format that needs this (most wiki/light markup formats do).
