### ISSUE TITLE
man writer: syntax highlighting

### ISSUE THREAD

**Issue by van-de-bugger** [jgm/pandoc#9446]
**Feature request:**

Since man format has ability to represent italic and bold, it would be nice if pandoc man writer does not ignore syntax highlighting completely, but uses available abilities.

**Background:**

`man-pages(7)` recommends:

>   When showing example shell sessions, user input should be formatted in bold, for example
>
>    $ **date**
>    Thu Jul  7 13:01:27 CEST 2016

I wrote a simple syntax definition file (`shell.xml`) to highlight user input in such examples and used fenced code blocks with `{.shell}` class, e.g.:

    ~~~ {.shell}
    $ date
    Thu Jul  7 13:01:27 CEST 2016
    ~~~

It works perfectly for HTML output, but in case of man output, user input is not highlighted with bold. Custom highlighting style (which uses only bold and italic and does not use colors) does not help, since highlighting is not supported for man output:

>   Currently highlighting is supported only for HTML, EPUB, Docx, Ms, and LaTeX/PDF output.

**Comment by jgm** [comment]
This should be possible.  The `highlight` function takes a formatter as parameter:
``` hs
          (FormatOptions -> [SourceLine] -> Doc Text)
```
So it's just a matter of defining this formatter for man.  Of course colors would just be ignored, but you could still get bold and italic.
