### ISSUE TITLE
Allow new lines in wikilink title.

### ISSUE THREAD

**Issue by urosmikanovic** [jgm/pandoc#9454]
Right now the wikilinks extensions do not support new lines within wikilinks titles.

This:
```
printf "Paragraph [[wikilink title with\nnewline|wikilink]] continued" | pandoc -f markdown+wikilinks_title_before_pipe
```

Produces this:
```
<p>Paragraph [[wikilink title with newline|wikilink]] continued</p>
```

(Note that the wikilink wasn't converted to an anchor tag.)

I would expect it to work the same as with regular links, where:
```
printf "Paragraph [link title with\nnewline](link) continued" | pandoc
```

Produces this:
```
<p>Paragraph <a href="link">link title with newline</a> continued</p>
```

**Comment by jgm** [comment]
Looks like this extension works properly for `commonmark`; so it's just the Markdown reader that needs adjusting.
