### ISSUE TITLE
--reference-location=section and --reference-location=block cause duplicate footnote section ids

### ISSUE THREAD

**Issue by van-de-bugger** [jgm/pandoc#9455]
$ pandoc --version
    pandoc 3.1.3
    Features: -server +lua
    Scripting engine: Lua 5.4
    User data directory: /home/liveuser/.local/share/pandoc
    Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
    This is free software; see the source for copying conditions. There is no
    warranty, not even for merchantability or fitness for a particular purpose.

    $ cat test.md 
    Header
    ======

    Section 1
    ---------

    Text^[note].

    Section 2
    ---------

    Another text^[another note].

    $ pandoc -t html --reference-location=section --wrap=preserve ./test.md 
    <h1 id="header">Header</h1>
    <h2 id="section-1">Section 1</h2>
    <p>Text<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
    <aside id="footnotes" class="footnotes footnotes-end-of-section" role="doc-endnotes">
    <hr />
    <ol>
    <li id="fn1"><p>note<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
    </ol>
    </aside>
    <h2 id="section-2">Section 2</h2>
    <p>Another text<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
    <aside id="footnotes" class="footnotes footnotes-end-of-section" role="doc-endnotes">
    <hr />
    <ol start="2">
    <li id="fn2"><p>another note<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
    </ol>
    </aside>

Note: pandoc generates two `aside` elements — that's ok, but both elements have the same `footnotes` id, which is definitely wrong — each id must be unique.

`--reference-location=block` causes the same problem.

**Comment by jgm** [comment]
Wasn't this just fixed yesterday in #8770  ?

**Comment by jgm** [comment]
Yeah, I think this one didn't have an associated issue. Anyway, closing. Will be fixed in next release.
