### ISSUE TITLE
pandoc fails to wrap math correctly when generating pptx in unusual places

### ISSUE THREAD

**Issue by aquohn** [jgm/pandoc#9465]
**Explain the problem.**
Pandoc's pptx output from markdown is not recognised by PowerPoint if math is put into the slide titles or table content. This can be reproduced on pandoc.org/try with
```
# Test

Table
-------
$x^2$
```

```
# $x^2$

Table
-------
$x^2$
```

Opening up the XML file suggests that `surroundWithMathAlternate` is not being called here, because the corresponding tags are missing. Adding the tags manually allows the XML to be parsed by Microsoft Edge (and by PowerPoint, even though it still asks to repair the presentation).

**Pandoc version?**
Reproduced on https://pandoc.org/try

**Comment by jgm** [comment]
There's a function surroundWithAlternate
https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/Powerpoint/Output.hs#L1262
that is supposed to do this.
It is called here:
https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/Powerpoint/Output.hs#L1338
Probably needs to be called somewhere else as well, but at the moment I don't see where; the pptx writer is not familiar to me.

**Comment by Konfekt** [comment]
Compiling a markdown table

```md
|                    |
|--------------|
| a $\to$ b |
```

to pptx produces a pptx file that Powerpoint (2010) must repair when opened.
Without the math `$\to$`, it opens fine
