### ISSUE TITLE
Invalid Typst output from demo ODT document

### ISSUE THREAD

**Issue by mathrick** [jgm/pandoc#9477]
**Explain the problem.**
Pandoc generates invalid Typst output when fed the [demo ODT document](https://pandoc.org/demo/example21.odt) from the webpage:

```
$ ./pandoc -f typst test.typ -o test.odt
$ typst compile test.typ

error: label `<extension-fancy_lists>` occurs multiple times in the document
     ┌─ test.typ:4957:1
     │
4957 │ #link(<extension-fancy_lists>)[Pandoc’s Markdown fancy lists] are also
     │  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: label `<option--reference-doc>` does not exist in the document
     ┌─ test.typ:8409:25
     │
8409 │ For pptx, you can use a #link(<option--reference-doc>)[reference doc] in
     │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: label `<option--reference-doc>` does not exist in the document
     ┌─ test.typ:8452:18
     │
8452 │ For pptx, pass a #link(<option--reference-doc>)[reference doc] with the
     │                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: label `<ext-styles>` does not exist in the document
     ┌─ test.typ:9155:17
     │
9155 │ By enabling the #link(<ext-styles>)[`styles` extension] in the docx
     │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: label `<extension--tagging>` does not exist in the document
     ┌─ test.typ:9292:1
     │
9292 │ #link(<extension--tagging>)[`tagging`] format extension to force markup
     │  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: label `<option--css>` does not exist in the document
     ┌─ test.typ:3433:5
     │
3433 │ use #link(<option--css>)[`--css`];, this variable is set to `true` by
     │      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: label `<option--katex>` does not exist in the document
     ┌─ test.typ:3543:12
     │
3543 │ when using #link(<option--katex>)[KaTeX];, you can render display math
     │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

[example21.odt](https://github.com/jgm/pandoc/files/14327435/example21.odt)

**Pandoc version?**
Tested using both `3.1.12.1` from official `.deb`, and `3.1.12.1-nightly-2024-02-18`. Typst compiler `0.10.0 (70ca0d25)`

**Comment by jgm** [comment]
As for the "does not exist in this document" this is because we add these links to the manual using a Lua filter when we produce the HTML version.  It's not a major cause for concern, because a normal ODT document wouldn't have internal links with no corresponding anchors.  Perhaps for this reason it's not idal as a demo.  But it's not an issue with the typst writer, which is accurately representing the internal links and labels that exist in the source document.

**Comment by mathrick** [comment]
So in other words, this is a problem with the source file (ie. `MANUAL.txt`) being faulty, and that is preserved into the ODT output?

**Comment by jgm** [comment]
Correct.  The source file contains internal links with no corresponding anchors (because we autogenerate the anchors when converting it to HTML, using filters).

**Comment by jgm** [comment]
It's not a *problem* with MANUAL.txt, which is intended to be processed in this way. But maybe it makes it less than ideal as an example in the demos.

**Comment by mathrick** [comment]
Thanks for clearing that up!
