### ISSUE TITLE
Pandoc can't roundtrip ODT -> Typst -> ODT, chokes on its own output

### ISSUE THREAD

**Issue by mathrick** [jgm/pandoc#9478]
Possibly related to #9477

**Explain the problem.**
Pandoc errors out when trying to roundtrip the [demo ODT file](https://pandoc.org/demo/example21.odt) from the webpage:
```
$ ./pandoc example21.odt -t typst | ./pandoc -f typst -o test.odt
(line 2380, column 2):
unexpected Elt {eltName = Identifier "list", eltPos = Just (line 2380, column 2), eltFields = fromList [(Identifier "children",VArray [VContent (fromList [])])]}
expecting end of input
Pattern match failure in 'do' block at src/Text/Pandoc/Readers/Typst.hs:108:26-33
```

**Pandoc version?**
Tested using both `3.1.12.1` and `3.1.12.1-nightly-2024-02-18`

**Comment by jgm** [comment]
This particular issue is an issue with the typst writer, which is producing
```
#strong[-]
```
for an emphasized `-` character; typst requires this to be escaped:
```
#strong[\-]
```
In a recent change we [tried to remove unnecessary escapes](https://github.com/jgm/pandoc/commit/b6ac32b1161eae21bbb9525415ed64d11adf7a54) but we didn't anticipate this particular case, hence the regression.

**Comment by mathrick** [comment]
Thanks for the quick turnaround!
