### ISSUE TITLE
add ListAttributes  support for BulletList

### ISSUE THREAD

**Issue by ilcpm** [jgm/pandoc#9480]
since we have ListAttributes for OrderedList:
```
OrderedList ListAttributes [[Block]]
type ListAttributes = (Int, ListNumberStyle, ListNumberDelim)
```

so why not add ListAttributes for BulletList? the api of BulletList is just barely like:

```
BulletList [[Block]]
```

---

in my project, I want to distinguish between `- ` list and `* ` list, so I can set different style on them, but I can't do that now.

**Comment by jgm** [comment]
In principle, this could be done, but we are very conservative about API changes affecting pandoc-types, as they cause breaking changes throughout the pandoc ecosystem.  If you like, you can make the request over at jgm/pandoc-types.
