### ISSUE TITLE
hard_line_breaks extension (already present for markdown) for djot writer

### ISSUE THREAD

**Issue by massifrg** [jgm/pandoc#9485]
The hard_line_breaks extension prevents a paragraph being broken into shorter lines by line breaks.

Those line breaks are good for reading and editing in markdown or djot, but they are a problem when you convert your docs into e.g. HTML.

You can already do that with markdown with `pandoc -t markdown+hard_line_breaks ...`.

It would be useful if you could write `pandoc -t djot+hard_line_breaks ...` too.

**Comment by jgm** [comment]
You can simply do `pandoc -t djot --wrap=preserve`.
