### ISSUE TITLE
HTML Reader: figure with table or image both has Image caption in result DOCX

### ISSUE THREAD

**Issue by sleepstream** [jgm/pandoc#9489]
**Explain the problem.**
Has html file
```
<figure data-xwiki-rendering-figure-type="table" data-xwiki-rendering-figure-style="block"><table><tr><th scope="col">Column header 1</th><th scope="col">Column header 2</th><th scope="col">Column header 3</th></tr><tr><td>Cell 1-1</td><td>Cell 2-1</td><td>Cell 3-1 + image <img src="[../../../../../../attachment/xwiki/Main/Instrumenty-adminov/Dannye-dlia-testirovaniia-platformy/Eksport-v-GOST_Testovaia-stranitsa/WebHome/1708065061160-589.png](https://avatars.mds.yandex.net/i?id=3c7f405bfdd49cd1508ca3a16e35487cc88f257e-5244793-images-thumbs&n=13)" id="I1708065061160-589.png" class="wikigeneratedid" alt="1708065061160-589.png"/></td></tr><tr><td>Cell 1-2</td><td>Cell 2-2</td><td>Cell 3-2</td></tr><tr><td>Cell 1-3</td><td>Cell 2-3</td><td>Cell 3-3</td></tr></table><figcaption><p><span id="tab_01"></span>&nbsp;Caption of table</p></figcaption></figure>
<figure class="image" style="width: 868px;"><img src="../../../../../../attachment/xwiki/Main/Instrumenty-adminov/Dannye-dlia-testirovaniia-platformy/Eksport-v-GOST_Testovaia-stranitsa/WebHome/image-20221225200959-1.png" id="pic_1-03-01" width="868" alt="image-20221225200959-1.png"/><figcaption><p>Image caption</p></figcaption></figure>
```

In code example we has **figure** with defined **figcaption**
One figure has image inside, another table

Try to convert this html to DOCX
`pandoc -s --metadata title="..." test.html --to docx+native_numbering -o output.docx`

In output receive both table and img caption - with style ImageCaption
![image](https://github.com/jgm/pandoc/assets/10279518/8dc40248-3b6f-4d7a-863c-f9d11cbe687d)

Expecting result:
Table has caption with style TableCaption;
Image has caption with style ImageCaption;

**Pandoc version?**
3.1.5

**Comment by jgm** [comment]
Anything in a Figure will get the sort of caption we apply to figures, which happens to have the name ImageCaption.

Remove the Table element from the Figure and you will get a TableCaption.

If you need to automate this, a Lua filter could probably do it quite easily. Just match on a Figure element that contains a Table element as its content, and replace it with the Table element.

**Comment by jgm** [comment]
We should probably rename ImageCaption to FigureCaption, but I think we may have used ImageCaption because it's a standard Word class name?

**Comment by sleepstream** [comment]
It's not good idea to use ImageCaption or FigureCaption for both table and image, because it has different title style:

Table 1:
Image 1: 

But now both has Image 1: Title;

If Use caption tag in table - pandoc convert it correctly, but table caption and table put inside one more table;

**Comment by sleepstream** [comment]
If convert MD to docx - image caption and table caption work correctly;

**Comment by sleepstream** [comment]
And if use only one type of caption - numbering will be not correct - table and images will be in the same numbering list;

**Comment by jgm** [comment]
The issue, again, is that your HTML document is putting the table inside a figure and using `figcaption` to attach the caption. So, pandoc treats this as a Figure, and gives it the kind of caption a figure gets, not the kind a table gets. This all seems fine. If you want a table caption, you need to use the proper HTML markup for that.

**Comment by sleepstream** [comment]
Thanks a lot!!!
Now it's worked!!!
Delete figure tag and it's work now correctly
