### ISSUE TITLE
Unexpected character `◻` when using `\newenvironment`

### ISSUE THREAD

**Issue by dmca-glasgow** [jgm/pandoc#9494]
**Explain the problem.**

Given the following LaTeX:

```latex
\documentclass{article}

\newenvironment{solution}{\begin{proof}[Solution]}{\end{proof}}

\begin{document}

\begin{solution}
Test solution
\end{solution}

\end{document}
```

When running the command:

```bash
pandoc --output test.md test.tex
```

The resulting Markdown appears to have gained a 'square' (`◻`) character at the end of the contents which I did not expect:

```md
::: proof
*Solution.* Test solution ◻
:::
```

I have tried recreating the .tex file to ensure there are no rogue special/hidden/zero-width characters in there.

Thanks.

**Pandoc version?**

pandoc 3.1.12
macOS 14.2.1

**Comment by jgm** [comment]
This comes from `addQed` here: https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Readers/LaTeX/Math.hs#L203-L226

If I recall correctly, this is intended to match LaTeX's own behavior with the proof environment.

**Comment by jgm** [comment]
This is what LaTeX does:
<img width="679" alt="Screen Shot 2024-02-22 at 11 24 24 PM" src="https://github.com/jgm/pandoc/assets/3044/e283984d-e41d-416d-826a-e28e3dd41f6c">

**Comment by jgm** [comment]
Incidentally, for your tex file to compile with latex, you need to add `\usepackage{amsmath,amsthm}`.
