### ISSUE TITLE
HTML writer with embedded resources wrongly displays the same image the second time

### ISSUE THREAD

**Issue by tzok** [jgm/pandoc#9498]
Minimal Markdown input:

```markdown
![](image.svg)

![](image.svg)
```

Command:

```
pandoc --standalone --embed-resources input.md -o input.html
```

In the output HTML there is:

```html
<p><svg ...><use href="#svg_XYZ" width="100%" height="100%" /></svg></p>

<p><svg id="svg_XYZ" width="W" height="H" ...></svg></p>
```

The first `<svg>` tag has a `<use>` tag inside with width and height set to 100% and not the actual width and height of the referenced image. This breaks the visual output, as one image is drawn bigger than the other.

I am using Pandoc 3.1.11.1

**Comment by jgm** [comment]
I believe this issue has been fixed in the most recent versions. Please try with the latest, 3.1.12.1.
