### ISSUE TITLE
wikilinks_title_after_pipe unexpected '2' Error mixed markdown and wikilinks

### ISSUE THREAD

**Issue by jfishe** [jgm/pandoc#9510]
**Explain the problem.**
Since v3.1.12, pandoc markdown extension wikilinks_title_after_pipe does not parse mixed wiki and markdown links.

```bash
printf 'Messina ([2007](#ref-TSTF-475-Ar1))\n\n([[#ref-TSTF-475-Ar1|2007]])' | 
pandoc \
  --from=markdown+wikilinks_title_after_pipe \
  --to=markdown 
```
**Error:**

```text
Error at (line 1, column 11):
unexpected '2'
Messina ([2007](#ref-TSTF-475-Ar1))
          ^
```

**Expected response:**

```text
Messina ([2007](#ref-TSTF-475-Ar1))

([2007](#ref-TSTF-475-Ar1 "wikilink"))
```

**Pandoc version?**

v3.1.3 - v3.1.11.1 produce the expected response. V3.1.12 - v3.1.12.1 produce the error.

**Comment by jgm** [comment]
This was already fixed - see #9481.
The fix will be in the next release.
