### ISSUE TITLE
Valid Word docx creates corrupted .docx when used as reference

### ISSUE THREAD

**Issue by chanchett-biolinq** [jgm/pandoc#9522]
Given this valid .docx file [minimum_repro.docx](https://github.com/jgm/pandoc/files/14425397/minimum_repro.docx) which opens in Word without issue and an empty .md file called `in.md`, running the command `pandoc in.md --reference-docx=minimum_repro.docx -oout.docx` results in an error when trying to open out.docx in Word.

```
Word found unreadable content in out.docx. Do you want to recover the contents of this document? If you trust the source of this document, click Yes.
```

Given that minimum_repro.docx is a valid Word document that can be opened without issue, I do not expect the output of pandoc to create a document with errors.

This issue does not occur when using other .docx files as a reference.

**Pandoc version?**
pandoc 3.1.12 thru 3.1.12.1-nightly-2024-02-27 have this issue.

pandoc 3.1.5 thru 3.1.11 do NOT have this issue.

**Comment by jgm** [comment]
We don't consider that a bug, necessarily -- pandoc makes certain assumptions about the reference doc that might not hold for arbitrary docx files. As the manual says:

> the reference docx should be a modified version of a docx file produced using pandoc. The contents of the reference docx are ignored, but its stylesheets and document properties (including margins, page size, header, and footer) are used in the new docx.

This particular document defines several headers and footers, for example, which pandoc doesn't expect.

**Comment by jgm** [comment]
Sorry, I just noticed your comment that this is a regression in 3.1.12. That gives us more to go on, so let's leave this open.

**Comment by jgm** [comment]
What would be really helpful is identifying the specific commit that introduces this issue.

Good candidates: 075cbb6419d542022ac62e0a0c075685b41a9276
c9bf4da74ffa21b4cf4b5fdfdcf02807db5dc5bd

**Comment by jgm** [comment]
I've experimentally determined that the commit that causes a problem is https://github.com/jgm/pandoc/commit/c9bf4da74ffa21b4cf4b5fdfdcf02807db5dc5bd

**Comment by jgm** [comment]
The change here only affects settings.xml.
So I tried this experiment:  I opened the corrupted file in Word, rescued it, saved it, and then inserted just the settings.xml from the recovered file into the original. It worked.
So it's an issue in settings.xml.

**Comment by jgm** [comment]
This seems to be the issue:
```xml
  <w:footnotePr>
    <w:footnote w:id="-1" />
    <w:footnote w:id="0" />
    <w:footnote w:id="1" />
  </w:footnotePr>
```

**Comment by jgm** [comment]
If I remove just this one line:
```xml
    <w:footnote w:id="1" />
```
then it opens.

**Comment by jgm** [comment]
Oddly though, that line is present in the reference docx, but it *can* be opened.

**Comment by jgm** [comment]
In the reference docx there is a footnotes.xml with 3 w:footnote elements, ids -1, 0, 1.
In the produced docx footnotes.xml only has 2 notes, ids 0 and -1.
