### ISSUE TITLE
Specify default files by extension

### ISSUE THREAD

**Issue by avidseeker** [jgm/pandoc#9528]
If `$XDG_DATA_HOME/pandoc/templates/default.latex` is created, Pandoc will use that files by default when using `pandoc in.md -o out.pdf` without having to explicitly specify `default.latex` in the command line.

However, this does not seem the case for "Default Files", where they had to be explicitly added to the command line: `pandoc -d latex in.md -o out.pdf`.

It would be handy to set a default file to be picked up automatically by Pandoc based on the extension, similar to the way it picks up template files without explicitly specifying them.

**Comment by avidseeker** [comment]
This is somewhat similar to https://github.com/jgm/pandoc/issues/1958, but instead of deducing the template to use from metadata, it is deduced from the file extension.

**Comment by jgm** [comment]
Default files can specify input and output files, so I don't think this makes sense conceptually.  Also it will be clearer if they have .yaml extension.
