### ISSUE TITLE
Request for Pandoc to support s390x architecture.

### ISSUE THREAD

**Issue by Aman-Surkar** [jgm/pandoc#9549]
I need pandoc for s390x so as to build jsonpatch where pandoc is a requirement.

**Comment by jgm** [comment]
Have you tried building pandoc on this architecture? If so, what problem did you run into?
If you're asking us to provide binaries for this architecture, then no, we won't do that.
It looks like Debian offers pandoc in this architecture.

**Comment by Aman-Surkar** [comment]
I tried building conda-forge/pandoc-feedstock and it gave me an error: `pandoc: cannot execute binary file: Exec format error`

**Comment by jgm** [comment]
We have nothing to do with pandoc-feedstock
