### ISSUE TITLE
TOC broken on epub3

### ISSUE THREAD

**Issue by pinusc** [jgm/pandoc#9560]
**Explain the problem.**

When generating an epub/epub3 file, the table of contents is broken; the generated TOC has broken links (linking each section either to non-existing positions, or to the page right after the TOC), and the epub metadata TOC/navigation (not sure if that's the proper nomenclature) is also generated but with incorrect links. 

I don't think this is quite the same bug as #9009, but a more generic version which presents itself even with the simplest one-file input.

To reproduce:
```shell
pandoc --standalone --toc --from markdown test.md -t epub -o test.epub
```

where `test.md` is a plain markdown file containing one `#section` with several `##subsection` filled with lorem ipsum text.
[Attached, the actual file I used](https://github.com/jgm/pandoc/files/14561964/test.md)

This bug does not present itself when exporting to epub2.

**Pandoc version?**
```
pandoc 3.1.12.2
Features: +server +lua
Scripting engine: Lua 5.4
```

**Comment by jgm** [comment]
I tried this. The resulting epub validated with epubcheck (after I added `-M title=Title` to ensure that it had a title).  I then opened the epub in iBooks, and both the built-in TOC navigation and the links in the generated TOC seemed to worked perfectly.

nav.xhtml has
```html
<nav epub:type="toc" role="doc-toc" id="toc"><h1 id="toc-title">title</h1><ol class="toc"><li id="toc-li-1"><a href="text/ch001.xhtml#section">Section</a><ol class="toc"><li id="toc-li-2"><a href="text/ch001.xhtml#subsection">Subsection</a></li><li id="toc-li-3"><a href="text/ch001.xhtml#subsection2">Subsection2</a></li><li id="toc-li-4"><a href="text/ch001.xhtml#subsection3">Subsection3</a></li><li id="toc-li-5"><a href="text/ch001.xhtml#subsection4">Subsection4</a></li><li id="toc-li-6"><a href="text/ch001.xhtml#subsection5">Subsection5</a></li><li id="toc-li-7"><a href="text/ch001.xhtml#subsection6">Subsection6</a></li></ol></li></ol></nav>
```
and all these links look correct to me.

toc.ncx has
```xml
  <navMap>
    <navPoint id="navPoint-0">
      <navLabel>
        <text>title</text>
      </navLabel>
      <content src="text/title_page.xhtml" />
    </navPoint>
    <navPoint id="navPoint-1">
      <navLabel>
        <text>Section</text>
      </navLabel>
      <content src="text/ch001.xhtml#section" />
      <navPoint id="navPoint-2">
        <navLabel>
          <text>Subsection</text>
        </navLabel>
        <content src="text/ch001.xhtml#subsection" />
      </navPoint>
      <navPoint id="navPoint-3">
        <navLabel>
          <text>Subsection2</text>
        </navLabel>
        <content src="text/ch001.xhtml#subsection2" />
      </navPoint>
      <navPoint id="navPoint-4">
        <navLabel>
          <text>Subsection3</text>
        </navLabel>
        <content src="text/ch001.xhtml#subsection3" />
      </navPoint>
      <navPoint id="navPoint-5">
        <navLabel>
          <text>Subsection4</text>
        </navLabel>
        <content src="text/ch001.xhtml#subsection4" />
      </navPoint>
      <navPoint id="navPoint-6">
        <navLabel>
          <text>Subsection5</text>
        </navLabel>
        <content src="text/ch001.xhtml#subsection5" />
      </navPoint>
      <navPoint id="navPoint-7">
        <navLabel>
          <text>Subsection6</text>
        </navLabel>
        <content src="text/ch001.xhtml#subsection6" />
      </navPoint>
    </navPoint>
  </navMap>
```
That too looks right. I see *no* problems here.  Perhaps you are accidentally using a different version of pandoc than you think you are?

**Comment by pinusc** [comment]
Whelp. Turns out this was a bug in my ebook reader (zathura with mupdf backend). Everything does indeed work as expected when opening in another editor... Sorry for wasting your time!
