### ISSUE TITLE
pandoc metadata "cover-image" doesn't recognize WebP image

### ISSUE THREAD

**Issue by selden** [jgm/pandoc#9561]
**Explain the problem.**
Problem:
pandoc metadata "cover-image" doesn't recognize WebP image. It should.

The command line

```
	pandoc test_webp.html -o test_webp.epub \
       --metadata cover-image="front_cover.webp"

```
generates the warning message

```
	[WARNING] Could not determine image size for front_cover.webp: could not determine image type

```
It'd be nice if the problem causing this warning could be fixed.

**Pandoc version?**
This warning is seen when using pandoc 3.1.12.2
under Windows 10 Pro x64 22H2 build 19045.4046
with Cygwin 3.5.1

The .webp image file was created using ImageMagick 7.0.10-61
with the command 
```
convert front_cover.jpg -resize 300x300 front_cover.webp

```
so I think the format of the WebP file itself is OK.

The resulting .epub document does show the cover page image when displayed using the epub reader provided with Calibre 7.6. which again suggests that the file format is OK.

The attached zip file contains the following files which can be used to reproduce the warning message.

test_webp.sh
test_webp.html
front_cover.webp

test_webp.epub
readme.txt

[test_webp.zip](https://github.com/jgm/pandoc/files/14564270/test_webp.zip)

**Comment by jgm** [comment]
We'd need a way to get the size information from the WebP file.
There's this:
https://hackage.haskell.org/package/webp
but the dependency on an external C library rules it out.

If there's an easy way to extract the size information we can just write some custom code for that, but the format seems rather complex.

Have you tried specifying explicit size information for your image? (Width and height attributes).  That might avoid the warning.

**Comment by selden** [comment]
I just now reread the pandoc documentation (to try to find out how to specify the image size) and discovered that there's an epub-specific version of the cover-image metadata declaration. When I replaced 
```
       --metadata cover-image="front_cover.webp"
```
by

```
       --metadata epub-cover-image="front_cover.webp"
```
the warning message went away.

It'd be nice if the image decoding routine used by the epub-cover-image metadata declaration could be incorporated into the generic cover-image metadata declaration.
