### ISSUE TITLE
md to typ error when @ in link text

### ISSUE THREAD

**Issue by gmankab** [jgm/pandoc#9566]
**Explain the problem.**
```shell
echo '[@username](https://t.me/username)' > test.md
pandoc test.md -o test.typ
cat test.typ
```

expected output: ` #link("https://t.me/username")[\@username]`

got output: `#link("https://t.me/username")[#cite("username")]`

if i copy output i got from pandoc to typst.app then it shows error "Expected label, found string"

if i copy output i expected then it works

**Pandoc version?**
3.1.8

os is fedora silverue with arch distrobox

**Comment by gmankab** [comment]
> If I put this in typst

this is markdown formatted text, it's not ment to be putted this in typst

it should be putted in .md file and converted to typst via pandoc

> You need to backslash escape the @

thank you, it fixed my problem, if i escape @ in .md file then it works as expected

but i think it should work even if @ is not escaped

if you disagree, feel free to close issue

**Comment by jgm** [comment]
In pandoc markdown `@foo` is a citation. You can disable this with `-f markdown-citations` (or use e.g. `-f gfm`).
