### ISSUE TITLE
MD to DOCX file conversion issue (bullet list)

### ISSUE THREAD

**Issue by ghiumiusliu-maxim** [jgm/pandoc#9570]
The bullet list is malformed after conversion

_**MD File segment:**_
Forwarding references allow a reference to bind to either an lvalue or rvalue depending on the type. Forwarding references follow the rules of _reference collapsing_:
* `T& &` becomes `T&`
* `T& &&` becomes `T&`
* `T&& &` becomes `T&`
* `T&& &&` becomes `T&&`

_**Output**_
Forwarding references allow a reference to bind to either an lvalue or rvalue depending on the type. Forwarding references follow the rules of reference collapsing: * T& & becomes T& * T& && becomes T& * T&& & becomes T& * T&& && becomes T&&

_**Command**_
pandoc -o readme.docx readme.md

_**IO data**_
input: [README.md](https://github.com/jgm/pandoc/files/14594612/README.md)
output: [readme.docx](https://github.com/jgm/pandoc/files/14594611/readme.docx)

_**Pandoc version**_
pandoc 3.1.12.2

Features: +server +lua
Scripting engine: Lua 5.4

Windows 11 Home
Version: 23H2
OS build: 22631.3296

**Comment by jgm** [comment]
I just commented on an almost identical issue you submitted.  Same comment here.
