### ISSUE TITLE
MD to DOCX conversion issue (links list)

### ISSUE THREAD

**Issue by ghiumiusliu-maxim** [jgm/pandoc#9571]
The links list is malformed after conversion

_**MD File segment:**_
C++20 includes the following new language features:
- [coroutines](#coroutines)
- [concepts](#concepts)
- [designated initializers](#designated-initializers)
- [template syntax for lambdas](#template-syntax-for-lambdas)
- [range-based for loop with initializer](#range-based-for-loop-with-initializer)
- [\[\[likely\]\] and \[\[unlikely\]\] attributes](#likely-and-unlikely-attributes)
- [deprecate implicit capture of this](#deprecate-implicit-capture-of-this)
- [class types in non-type template parameters](#class-types-in-non-type-template-parameters)
- [constexpr virtual functions](#constexpr-virtual-functions)
- [explicit(bool)](#explicitbool)
- [immediate functions](#immediate-functions)
- [using enum](#using-enum)
- [lambda capture of parameter pack](#lambda-capture-of-parameter-pack)
- [char8_t](#char8_t)
- [constinit](#constinit)

_**Output**_
C++20 includes the following new language features: - [coroutines](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#coroutines) - [concepts](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#concepts) - [designated initializers](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#designated-initializers) - [template syntax for lambdas](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#template-syntax-for-lambdas) - [range-based for loop with initializer](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#range-based-for-loop-with-initializer) - [[[likely]] and [[unlikely]] attributes](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#likely-and-unlikely-attributes) - [deprecate implicit capture of this](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#deprecate-implicit-capture-of-this) - [class types in non-type template parameters](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#Xd5fbc2131dd82a9d37874bb3feaf3c327a312e6) - [constexpr virtual functions](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#constexpr-virtual-functions) - [explicit(bool)](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#explicitbool) - [immediate functions](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#immediate-functions) - [using enum](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#using-enum) - [lambda capture of parameter pack](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#lambda-capture-of-parameter-pack) - [char8_t](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#char8_t) - [constinit](https://github.com/jgm/pandoc/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#constinit)

_**Command**_
pandoc -o readme.docx readme.md

_**IO data**_
input: [README.md](https://github.com/jgm/pandoc/files/14594612/README.md)
output: [readme.docx](https://github.com/jgm/pandoc/files/14594611/readme.docx)

_**Pandoc version**_
pandoc 3.1.12.2

Features: +server +lua
Scripting engine: Lua 5.4

Windows 11 Home
Version: 23H2
OS build: 22631.3296

**Comment by jgm** [comment]
In pandoc's markdown you need a blank line before the list.
(If you don't want this, you can use `-f commonmark` or `-f gfm` or `-f commonmark_x`.
