### ISSUE TITLE
Pandoc Markdown parses too much LaTeX as a raw environment

### ISSUE THREAD

**Issue by charmoniumQ** [jgm/pandoc#9579]
**Explain the problem.**

```
$ cat test.md
\begin{tabular}{p{2in}}
\end{tabular}

# Test

\begin{tabular}{p{2\linewidth}}
\end{tabular}

$ pandoc test.md --to=native
[ RawBlock
    (Format "tex")
    "\\begin{tabular}{p{2in}}\n\\end{tabular}\n\n# Test\n\n\\begin{tabular}{p{2\\linewidth}}\n\\end{tabular}"
]
```

However, switching the order of the tabular environments, removing any of the tabular environments, or changing `\linewidth` to `\textwidth` causes the correct parse, which should be:

```
[ RawBlock
    (Format "tex") "\\begin{tabular}{p{2in}}\n\\end{tabular}"
, Header 1 ( "test" , [] , [] ) [ Str "Test" ]
, RawBlock
    (Format "tex")
    "\\begin{tabular}{p{2\\textwidth}}\n\\end{tabular}"
]
```

**Pandoc version?**

```
$ pandoc --version
pandoc 3.1.11
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/sam/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

NixOS (if that matters)

Based on the description, I think this is distinct from [this issue](https://github.com/jgm/pandoc/issues/9517), because this issue is not about table elements.

**Comment by jgm** [comment]
I can reproduce this on the latest version too.  It's quite bizarre!

**Comment by jgm** [comment]
Processing this with `pandoc -f latex -t native` just yields one table, not two, and the intermediate stuff is ignored.  Similarly if you delete the `#`.

**Comment by jgm** [comment]
If you change the first `2in` to `2\linewidth`, it works, and if you change the second `2\linewidth` to `2in`, it works.

**Comment by jgm** [comment]
```
% pandoc -f latex -t native
\begin{tabular}{p{2in}}
\end{tabular}

Test

\begin{tabular}{p{2\linewidth}}
\end{tabular}
^D
[ Table
    ( "" , [] , [] )
    (Caption Nothing [])
    [ ( AlignLeft , ColWidthDefault ) ]
    (TableHead ( "" , [] , [] ) [])
    [ TableBody ( "" , [] , [] ) (RowHeadColumns 0) [] [] ]
    (TableFoot ( "" , [] , [] ) [])
]
```

**Comment by jgm** [comment]
Looking at the code, it seems that `colwidth` is currently set up only to handle cases like `2\linewidth`, and not `2in`.  I'm not sure exactly how to handle `2in`, because we don't have access to the linewidth in inches, but we could estimate I guess.

**Comment by jgm** [comment]
https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Readers/LaTeX/Table.hs#L89-L95

**Comment by charmoniumQ** [comment]
Should it not just pass through the latex code as a raw block?

**Comment by jgm** [comment]
Yes, that's the desired end result. But the Markdown reader is deferring to the LaTeX reader to parse the raw environment.  Something is going wrong there.

**Comment by jgm** [comment]
Also, as you can see above, this issue affects `-t latex` as well.
