### ISSUE TITLE
DOCX reader discards figure caption (regression)

### ISSUE THREAD

**Issue by frederik** [jgm/pandoc#9610]
## Problem description

The latest pandoc version(s) 3.1.12.3 (possibly .2) seems to drop figure captions from docx during import.
```
pandoc captions.docx -o test.json
```
Latest known version where it works: 3.1.12.1

## Reproduction

I am attaching a docx and two json outputs from: pandoc 3.1.12.1 and 3.1.12.3

here's the diff (only the caption is missing)
```
115,151d114
<         },
<         {
<             "t": "Para",
<             "c": [
<                 {
<                     "t": "Str",
<                     "c": "Figure"
<                 },
<                 {
<                     "t": "Space"
<                 },
<                 {
<                     "t": "Str",
<                     "c": "1"
<                 },
<                 {
<                     "t": "Space"
<                 },
<                 {
<                     "t": "Str",
<                     "c": "A"
<                 },
<                 {
<                     "t": "Space"
<                 },
<                 {
<                     "t": "Str",
<                     "c": "figure"
<                 },
<                 {
<                     "t": "Space"
<                 },
<                 {
<                     "t": "Str",
<                     "c": "caption"
<                 }
<             ]

```

[caption.docx](https://github.com/jgm/pandoc/files/14776309/caption.docx)
[test-latest.json](https://github.com/jgm/pandoc/files/14776303/test-latest.json)
[test-3-1-11.json](https://github.com/jgm/pandoc/files/14776304/test-3-1-11.json)

**Comment by jgm** [comment]
Probably due to one of these items from the .2 changelog:
```
  * Docx reader:

    + Ensure that table captions are counted (#9518).
    + Detect caption by style name not id (#9518).
      The styleId can change depending on the localization.
    + Avoid emitting empty paragraph where caption was.
```

**Comment by jgm** [comment]
Here's what I'm seeing:
```
% pandoc ~/Downloads/caption.docx -t native
[ Para
    [ Image
        ( ""
        , []
        , [ ( "width" , "6.268055555555556in" )
          , ( "height" , "2.5944444444444446in" )
          ]
        )
        [ Str "A"
        , Space
        , Str "screenshot"
        , Space
        , Str "of"
        , Space
        , Str "a"
        , Space
        , Str "web"
        , Space
        , Str "page"
        , SoftBreak
        , Str "Description"
        , Space
        , Str "automatically"
        , Space
        , Str "generated"
        ]
        ( "media/image1.png" , "" )
    ]
]
```
This is not being parsed as a Figure at all, which is a separate issue perhaps.

**Comment by jgm** [comment]
caption.docx has
```
<w:pStyle w:val="Caption"/>
```
then in doc.styles:
```
<w:style w:type="paragraph" w:styleId="Caption"><w:name w:val="caption"/>
```
so the caption name is `caption`. 

Note that changing the styleId to "ImageCaption" allows the caption to be parsed as a regular paragraph.

So, I think what is going on is this:  Pandoc identifies paragraphs with style 'caption' as table captions.  They are not emitted as regular paragraphs, but because we do not at this point have special handling for figures with captions, the result is that it gets dropped altogether.

Obviously not a great situation, but the fix would involve proper support for captioned images as Figure elements, which we've never had.
