### ISSUE TITLE
Typst: "partial" not found

### ISSUE THREAD

**Issue by MilesCranmer** [jgm/pandoc#9612]
In `main.typ`:

```typst
$partial$
```

This renders fine in typst. But when converting with pandoc:

```
> pandoc -s main.typ -o main.tex
"main.typ" (line 1, column 2):
Identifier "partial" not found
```

**Comment by jgm** [comment]
This is already fixed in HEAD, which brings typst symbol support up to 0.11.  The fix will be in the next release.  For now you could try a nightly.
