### ISSUE TITLE
Update ConTeXt writer to use new \setsmallcaps tag instead of \sc tag

### ISSUE THREAD

**Issue by cacology** [jgm/pandoc#9618]
The 2024 TeXLive update includes an updated ConTeXt that uses a more sophisticated OpenType mechanism for small caps. The use of `\sc` has been depreciated. Viz. [Wiki](https://wiki.contextgarden.net/Small_caps_and_other_styles) and lines 256-267 [Source](https://source.contextgarden.net/tex/context/base/mkiv/typo-cap.mkiv).

Right now `pandoc --from markdown --to context` [converts](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5BHello%5D%7B.smallcaps%7D%22%2C%22to%22%3A%22context%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D) `[Hello]{.smallcaps}` to `{\sc Hello}`

It should instead convert to

```
{\setsmallcaps Hello}
```

I believe the change is simple.  [This line](https://github.com/jgm/pandoc/blob/c29c18a0038b62718cf3133247177e3cb8ebf871/src/Text/Pandoc/Writers/ConTeXt.hs#L590) should be changed from:

```
inlineToConTeXt (SmallCaps lst) = highlightInlines "smallcaps" "\\sc" lst
```

To:

```
inlineToConTeXt (SmallCaps lst) = highlightInlines "smallcaps" "\\setsmallcaps" lst
```

**Pandoc version?**

pandoc 3.1.12.3 and pandoc.org/try both exhibit this behavior.

I don't quite know what other code might need to be changed along the way when changing this line.  If nothing, just say so and I'll be happy to make the pull request.

Respectfully submitted,

**Comment by jgm** [comment]
That should do it -- but you may find that the tests fail, in which case some tests may also need updating.  Go ahead and submit a PR!
