### ISSUE TITLE
Umlaut in image file name breaks PDF generation

### ISSUE THREAD

**Issue by ukoehler** [jgm/pandoc#9627]
When converting a PanDoc Markdown file into PDF I do get the following error:
`pandoc MetaData.md RecipeBook_de.md -s -H head.tex  --toc --toc-depth=2 --default-image-extension=pdf -o RecipeBook_de.pdf`

`pandoc: /home/ukoehler/NextCloudPi/Recipes/Hhnchenbrustfilets mit Senfkruste/full.jpg: openBinaryFile: invalid argument (invalid character)`

When converting to TeX first and using pdflatex to convert to PDF that does work fine.

The offending line of markdown:
`pandoc MetaData.md RecipeBook_de.md -s -H head.tex  --toc --toc-depth=2 --default-image-extension=pdf -o RecipeBook_de.tex`
`pdflatex RecipeBook_de.tex`
`![](/home/ukoehler/NextCloudPi/Recipes/Hähnchenbrustfilets mit Senfkruste/full.jpg){ width=50% }`

The created LaTeX code:
`\includegraphics[width=0.5\textwidth,height=\textheight]{/home/ukoehler/NextCloudPi/Recipes/Hähnchenbrustfilets mit Senfkruste/full.jpg}`

Generating Epub fails for the same reason.

That path is created by third party software and cannot easily be changed to one without Umlauts in it.

`pandoc -v      
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
`
running on Linux.

**Comment by jgm** [comment]
I'd suggest trying with a recent release of pandoc before reporting an issue. Your version is extremely old.  We offer binary releases (see Releases tab) that work on linux, which you can test with.

**Comment by ukoehler** [comment]
Ever so sorry. I run a complete update of the Linux distribution yesterday. KDE Neon is turning unusable. I will check update options for pandoc.

**Comment by jgm** [comment]
Most linux distros have old versions of pandoc. Hence the recommendation to test with the one we provide.

**Comment by ukoehler** [comment]
Works with latest version of pandoc.
