### ISSUE TITLE
When I set an ID for a heading in Org-Mode, the link to the heading from the table of content is wrong

### ISSUE THREAD

**Issue by teodorlu** [jgm/pandoc#9639]
**Explain the problem.**

It appears that the table of contents breaks when I set an ID for a heading with Org-Mode.

* The HTML-exported heading-element has the correct ID
* The table of contents links to the wrong ID.

Repro:

```
$ cat repro.org 
#+title: repro

* heading-name
:PROPERTIES:
:ID:       123abc
:END:
```

Expected: I can find `abc123` in _both_ the table of contents and in the document.

Actual: I can find _not_ find `abc123` in the table of contents, but I can find it in a h1 attribute. Also, the `h1` element gets two `id` attributes, I'm not sure if that is valid HTML.

```
$ pandoc repro.org -t html --standalone --toc > repro.html
$ tail -n 20 repro.html 
      font-size: inherit;
      width: 0.8em;
      margin: 0 0.8em 0.2em -1.6em;
      vertical-align: middle;
    }
    .display.math{display: block; text-align: center; margin: 0.5rem auto;}
  </style>
</head>
<body>
<header id="title-block-header">
<h1 class="title">repro</h1>
</header>
<nav id="TOC" role="doc-toc">
<ul>
<li><a href="#heading-name" id="toc-heading-name">heading-name</a></li>
</ul>
</nav>
<h1 id="123abc" id="heading-name">heading-name</h1>
</body>
</html>
```

**Pandoc version?**

arm64 macbook, Pandoc installed with Homebrew:

```
$ pandoc --version
pandoc 3.1.12.3
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/teodorlu/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

```
$ uname -a
Darwin Locomotive 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000 arm64
```

**Comment by jgm** [comment]
This explains it, I think:
```
% pandoc -f org -t native
#+title: repro

* heading-name
:PROPERTIES:
:ID:       123abc
:END:
^D
[ Header
    1
    ( "heading-name" , [] , [ ( "id" , "123abc" ) ] )
    [ Str "heading-name" ]
]
```

So, the org reader is adding an "id" to the part of the attributes triple that stores arbitrary key/value pairs, rather than modifying the first component of the triple, which is for the id.  (I know, suboptimal design, but hard to change now!)

This can be fixed by ensuring that the org reader handles an `id` properly.

**Comment by teodorlu** [comment]
Thank you! ❤️❤️❤️

**Comment by teodorlu** [comment]
After updating to `pandoc 3.1.13`, I can confirm that the problem has been solved for me. Thanks again!
