### ISSUE TITLE
Citeproc swallows variations of `pages`

### ISSUE THREAD

**Issue by wenkokke** [jgm/pandoc#9640]
**Explain the problem.**
Assume the following documents:
- `sample.md`:
  ```md
  ---
  bibliography: sample.bib
  ---
  
  We all love @BenjaminHornigold [pages 1-10].
  Wait, I mean @BenjaminHornigold [page 1-10].
  Wait, I mean @BenjaminHornigold [p.\ 1-10].
  Wait, I mean @BenjaminHornigold [poop deck 1-10].
  What about @BenjaminHornigold [on pages 1-10]?
  ```
- `sample.bib`:
  ```bibtex
  @book{BenjaminHornigold,
    author = {Benjamin Hornigold},
    title  = {A proof of Pirate ipsum},
    year   = {1680},
  }
  ```

Running the following command:
```bash
pandoc --citeproc sample.md -o sample.tex
```

Gives the following output:
```latex
We all love Hornigold (1680, 1--10). Wait, I mean Hornigold (1680,
1--10). Wait, I mean Hornigold (1680, 1--10). Wait, I mean Hornigold
(1680, poop deck 1-10). Wait, I mean Hornigold (1680, on pages 1-10).

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-BenjaminHornigold}
Hornigold, Benjamin. 1680. \emph{A Proof of Pirate Ipsum}.

\end{CSLReferences}
```

Citeproc swallows the prefixes `pages`, `page`, and `p.` in a manner that *has to be* intentional, but is, to the best of my reseasch, undocumented.

**Pandoc version?**
Running Pandoc 3.1.12.3 on macOS 13.

```
pandoc 3.1.12.3
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/keri/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jgm** [comment]
Yes, it's intentional but maybe needs to be documented in the pandoc manual.

CSL has a concept of a "locator" and "label." Pandoc will try to parse these from the citation suffix.  If the suffix starts with a recognized locator label (this is localized) like "pages" or "pp." then it will treat the following number range as a locator. Otherwise it's a plain suffix and just gets transmitted verbatim.

So, why is the label omitted in the output?  That's because your CSL style says to omit it.  If you try other styles, you may see that some of them include the label.

**Comment by wenkokke** [comment]
Is there a CSL I could use that simply preserves the citation prefixes and suffixes when rendering to TeX?

**Comment by jgm** [comment]
No, it's part of CSL to render the labels appropriately for the style.  (Perhaps using abbreviations, perhaps even in another language.)

There is a way, though, to indicate to pandoc that the whole thing is to be treated as a suffix and not a locator.  See https://pandoc.org/MANUAL.html#extension-citations
and in particular the example `[@smith{}, 99 years later]`.

**Comment by jgm** [comment]
I note that the behavior I described above IS documented at https://pandoc.org/MANUAL.html#extension-citations
So, closing this issue.
