### ISSUE TITLE
--toc-title no effect in docx

### ISSUE THREAD

**Issue by huggymann** [jgm/pandoc#9645]
**Explain the problem.**
Using the toc-title it does not have any effect. The title remains "Table of Contents"
`pandoc -f html html.html -o outdocx.docx --toc -V --toc-title="Inhaltsverzeichnis" -V mainlang=de --reference-doc=my-ref-doc.docx`

Screenshot shows the toc title:
![grafik](https://github.com/jgm/pandoc/assets/61777949/aab5223c-f590-4d1f-b05c-bfdc853ef297)

It is expected to change the toc-title. I tried also without the reference-doc , no changes. 

**Pandoc version?**
pandoc 3.1.13 (Ubuntu)
Features: +server +lua
Scripting engine: Lua 5.4

pandoc.exe 3.1.13 (Windows)
Features: +server +lua
Scripting engine: Lua 5.4

i tested both in ubuntu and windows 10

**Comment by jgm** [comment]
Syntax to set a variable would be
```
-V toc-title="Inhaltsverzeichnis"
```
You have an extra `--`.

**Comment by huggymann** [comment]
Thanks for the clarification. I changed it accordingly, but still no effect. I have a workaround now with metadata "toc-title" that works.
`pandoc -f html html.html -o output.docx --toc -V toc-title="Inhaltsverzeichnis" -V mainlang=de`

![grafik](https://github.com/jgm/pandoc/assets/61777949/7119ad0a-5675-4494-8026-602e5df16f28)

**Comment by jgm** [comment]
Yes, apparently in docx `-M toc-title=` works, but not `-V toc-title=`.
I'll document this.

**Comment by netkiller** [comment]
neo@netkiller neo % pandoc -f markdown -t docx --reference-doc=../template/template.dotx --toc --toc-depth=3  -M toc-title="目录" -M title="文档标题" -o test.docx test.md
