### ISSUE TITLE
Allow custom-style atttributes for inline elements in OpenDocument / ODT writer

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#9657]
In the manual it states that:

> Custom styles can be used in the docx and ICML formats - https://pandoc.org/MANUAL.html#custom-styles

And there is an open issue to add it for ODT: https://github.com/jgm/pandoc/issues/2106

However, for block-level div elements there is already support for `custom-style` for OpenDocument. This was added in commit https://github.com/jgm/pandoc/commit/a2ce28fa4d0e90fc2cd1e4d3a6d738005323164f — adding the custom-style to the XML element like so:

```markdown
::: {custom-style="Comment"}
Text here...
:::
```

```xml
<text:p text:style-name="Comment">Text here...</text:p>
```

For inline spans the property is identical, and so I suspect the code change should be straightforward:

```markdown
[Text here...]{custom-style="Strikethrough"}
```

```xml
<text:span text:style-name="Strikeout">Text here...</text:span>
```

@jgm suggested:

> I don't think it would be too hard to add support for inline custom-styles. We'd need to modify the TextStyle to have a constructor like Custom Text.

See the discussion https://github.com/jgm/pandoc/discussions/9656 for context.

**Comment by jgm** [comment]
This diff will do the trick:
```
diff --git a/src/Text/Pandoc/Writers/OpenDocument.hs b/src/Text/Pandoc/Writers/OpenDocument.hs
index ec7105a07..f7d8ce31d 100644
--- a/src/Text/Pandoc/Writers/OpenDocument.hs
+++ b/src/Text/Pandoc/Writers/OpenDocument.hs
@@ -660,8 +660,9 @@ inlineToOpenDocument o ils
                                                  , ("xlink:show"   , "embed" )
                                                  , ("xlink:actuate", "onLoad")]
       mkSpan attr xs =  do
-        let (ident,_,_) = attr
-            i = withLangFromAttr attr (inlinesToOpenDocument o xs)
+        let (ident,_,kvs) = attr
+            i = maybe id (withTextStyle . Custom) (lookup "custom-style" kvs)
+                . withLangFromAttr attr $ inlinesToOpenDocument o xs
             mkBookmarkedSpan b =
               if isEmpty b
                 then selfClosingBookmark ident
@@ -883,6 +884,7 @@ data TextStyle = Italic
                | SmallC
                | Pre
                | Language Lang
+               | Custom Text
                deriving ( Eq,Ord )
 
 textStyleAttr :: Map.Map Text Text
@@ -908,6 +910,8 @@ textStyleAttr m = \case
   Language lang ->
             Map.insert "fo:language" (langLanguage lang) .
             maybe id (Map.insert "fo:country") (langRegion lang) $ m
+  Custom sty ->
+            Map.insert "text:style-name" sty m
 
 withLangFromAttr :: PandocMonad m => Attr -> OD m a -> OD m a
 withLangFromAttr (_,_,kvs) action =
```

However, when I tested this with LibreOffice I couldn't find anything about the custom style.  I only saw information about paragraph styles, not character styles.  So I'm confused. Does LibreOffice actually support text:style-name on text:span?

(Note: our implementation puts the actual style in "automatic styles" so you'll need to use `-t opendocument -s` to actually see the effect of this change.)
