### ISSUE TITLE
Bullet point format not preserved

### ISSUE THREAD

**Issue by avidseeker** [jgm/pandoc#9663]
**Explain the problem.**
`input.md`
```
Here is a list:
* [One](https://avidseeker.github.io)
* [Two](https://github.com/jgm/pandoc)
```

```sh
$ pandoc -f commonmark -t commonmark --wrap=preserve --reference-links -i input.md
Here is a list:

- [One]
- [Two]

  [One]: https://avidseeker.github.io
  [Two]: https://github.com/jgm/pandoc
```

**Result**
* Bullet point format is changed
* Spacing between list header "Here is a list:" and the list is changed.

**Bonus**

Bonus question: as you can see, I'm trying to use pandoc to convert inline links to reference-style links. Is there a better way to do it?

Bonus feature-request: add an option `--reference-links=id` so that links converted have a numeric id (e.g: `[one][1]`). This makes it easier to change the text of the link without having to change the reference list.

**Pandoc version?**
pandoc 3.1.12.2

**Comment by jgm** [comment]
You should not expect the markdown writer to preserve aspects of your document that don't relate to its abstract structure.
