### ISSUE TITLE
Converting from RTF (using CJK characters) into Markdown causes CJK characters messed up

### ISSUE THREAD

**Issue by kenjiuno** [jgm/pandoc#9683]
**Explain the problem.**

Converting from RTF (using characters of Chinese, Japanese, and Korean languages) into Markdown causes CJK characters to be messed up.

`Hello! English and CJK.rtf` _(input)_

```rtf
{\rtf1\ansi\ansicpg932\deff0\nouicompat\deflang1033\deflangfe1041{\fonttbl{\f0\fnil\fcharset128 Arial Unicode MS;}{\f1\fnil\fcharset129 Arial Unicode MS;}}
{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
\pard\sa200\sl276\slmult1\f0\fs22\lang17 Hello! English and CJK\par
\u20320?\'8d\'44\'81\'49\par
\lang1041\'82\'b1\'82\'f1\'82\'c9\'82\'bf\'82\'cd\'81\'49\par
\f1\'be\'c8\'b3\'e7\'c7\'cf\'bc\'bc\'bf\'e4\f0\lang1033 !\lang17\par
}
 
```

Open this input with Windows Wordpad (`write.exe "Hello! English and CJK.rtf"`).

![2024-04-22_16h55_10](https://github.com/jgm/pandoc/assets/5955540/70b69715-e96c-485f-bc80-4e783b7d476f)

Command:

```bat
pandoc -o "Hello! English and CJK.md" "Hello! English and CJK.rtf"
```

`Hello! English and CJK.md` _(output)_

Actual

```md
Hello! English and CJK

你DI

‚±‚ñ‚É‚¿‚ÍI

¾È³çÇÏ¼¼¿ä!
```

Expected

```md
Hello! English and CJK

你好！

こんにちは！

안녕하세요!
```

**Pandoc version?**

Pandoc is `3.1.13` which is installed with `pandoc-3.1.13-windows-x86_64.msi`.

```
pandoc 3.1.13
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: C:\Users\KU\AppData\Roaming\pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

Using Windows 10 Pro, Japanese edition.

```
Microsoft Windows [Version 10.0.19045.4291]
```

**Comment by jgm** [comment]
We don't support `\ansicpg` and I think that may be the issue here.
Your document specifies code page 932, which is
https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)
for Japanese.

To improve pandoc, we'd need to page it sensitive to `\ansicpg` and implement lookup tables for various ANSI code pages.

**Comment by jgm** [comment]
Here is a code page 932 to unicode conversion:
https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP932.TXT
But note!  sequences like `\'82\'B1` map to 0x82B1, a two byte sequence.  This will require changes in how we handle things.

**Comment by jgm** [comment]
I've added some infrastructure to handle this, but the final piece will require an 8000 line lookup table for cp932.  This probably needs to be implemented as a separate library.

**Comment by jgm** [comment]
Aha, there is https://hackage.haskell.org/package/encoding-0.8.1
But it might be nice to avoid the transitive dependencies. We could, perhaps, just copy some code from the relevant module.

**Comment by kenjiuno** [comment]
Hi, thanks for investigating about this.

There is a big pitfall about this RTF.

This RTF mixes 2 code pages: `CP932` (a Japanese local charset aka Shift_JIS) and `CP949` (a Korean local charset) into one RTF.
`\ansicpg932` tells only about one of them.

While, 2 Chinese characters are represented as:
1. `你` as `\u20320?` (not available in `\ansicpg932`)
2. `好` as `\'8d\'44` (A CP932 character 0x8D44)

Perhaps `\fcharset128` and `\fcharset129` may indicate the difference.

![2024-04-23_06h55_13](https://github.com/jgm/pandoc/assets/5955540/03e40777-05b6-4a54-bd0f-29b16cda497a)

[Rich Text Format - Wikipedia](https://en.wikipedia.org/wiki/Rich_Text_Format)

---

Although I'm not good at RTF file specification so much, I have found the description from the documentation.

[[MS-OXRTFCP]: Informative References | Microsoft Learn](https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxrtfcp/85c0b884-a960-4d1a-874e-53eeee527ca6)

Page 14, `/ansicpgN` is described

![2024-04-23_07h07_14](https://github.com/jgm/pandoc/assets/5955540/4ff3408c-c600-426b-a5c5-9ee6fa6257d5)

Page 20, `/fcharsetN` is described

![2024-04-23_07h06_16](https://github.com/jgm/pandoc/assets/5955540/55c0b46f-1f94-4b1f-b4a3-bf83d64e04c7)

---

If this entire thing is too complex to handle, IMO it will be ok to display warning about usage of non-Unicode characters in RTF file instead. (It means that the user needs to convert all of the non-Unicode characters into Unicode characters with any tools that it can handle instead)

**Comment by jgm** [comment]
What a format!  Apparently we need to pay attention both to `ansicpgN` (specifies code page) and to `fcharsetN` (specifies a character set of a font in the font table).  I understand the former but not really the latter.  It seems that `\fcharset128 is Shift Jis and 129 is Hangul.  Does that mean it will work if I decode using code page 949 (Korean) for `\fcharset129`?  I'm unclear on the relation between fcharset and ansicpg.
Some helpful info here:
https://latex2rtf.sourceforge.net/rtfspec_6.html

**Comment by jgm** [comment]
So, I've figured out how to do the decoding.
What we need now is to implement language shifting with `\langN` and `\deflangN`.  Language shifts will need to induce a shift in the active code page, according to the table you've given above.

**Comment by jgm** [comment]
There's a list of standard language codes here
https://www.oreilly.com/library/view/rtf-pocket-guide/9781449302047/ch04.html
Maybe we can get by with those.

**Comment by jgm** [comment]
`\deflang` is for the *default* language.
`\deflangfe` is the default asian language.

**Comment by jgm** [comment]
OK, this is not going to work.  The encoding library doesn't even have the Korean code page. And it takes 7 minutes to compile and adds some new dependencies.  I'm taking your suggestion and just emitting a warning:
```
[WARNING] Unsupported code page 932. Text will likely be garbled.
Hello! English and CJK

你DI

‚±‚ñ‚É‚¿‚ÍI

¾È³çÇÏ¼¼¿ä!
```
