### ISSUE TITLE
While generating DOCX impossible to change header line to TOC "Table of Contents" to anything else.

### ISSUE THREAD

**Issue by belonesox** [jgm/pandoc#9687]
**Explain the problem.**
While generating DOCX impossible to change default TOC Title from `/src/Text/Pandoc/Writers/Docx/Types.hs` 

```haskell
      , stTocTitle       = [Str "Table of Contents"]
```

to anything else, specifying `lang` or even `-V toc-title` 

Sample file and run script attached.
[pandoc-toc-title-docx-bug.zip](https://github.com/jgm/pandoc/files/15074439/pandoc-toc-title-docx-bug.zip)

**Pandoc version?**

Pandoc built from sources, 
```
pandoc 3.1.12.3
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/stas/.local/share/pandoc
```

**Comment by jgm** [comment]
Hint: search closed issues.
https://github.com/jgm/pandoc/issues/9645
Does this help you?

**Comment by belonesox** [comment]
>Hint: search closed issues.

I searched, I swear.  
I even tried "-M toc-title", before switching to "-V ", but something wrong occured with my tests.
Looks like I am unlucky. :(

I confirm that 
```
 --toc -M toc-title="My Custom TOC Header" 
```
works for me now.

Thank you!
