### ISSUE TITLE
Compact (aka "Lazy") synatx for tables if converting to GitHub Flavored Markdown

### ISSUE THREAD

**Issue by jsx97** [jgm/pandoc#9696]
Currently, if converting from HTML to GitHub Flavored Markdown, table columns are always fine-aligned.

```
| one                  | two                       |
| -------------------- | ------------------------- |
| a very long sentence | a very very long sentence |
```

The problem is that if the cells are really wide, which is sometimes the case, and if line wrapping in the text editor is turned on, any well-aligned table looks horrifically ugly. Here is a real-life one from one article on the internet:

![image](https://github.com/jgm/pandoc/assets/129062294/f4aa5353-5662-4f79-9706-78c4855835d2)

If converted to GitHub Flavored Markdown, if line wrapping in the text editor is turned on, and if its window is, for example, about 100 columns width, it looks as follows:

![image](https://github.com/jgm/pandoc/assets/129062294/eaf14ae3-858b-4478-9590-8519c8679789)

I want to propose a solution, if the table width is greater than `COLUMNS`, to convert it using the compact, also known as "lazy" syntax, which should handle such cases. Here is how normal syntax is different from "lazy", and how  the real-life table from the above will look:

```
| Lorem ipsum     | Dolor sit amet |
| --------------- | -------------- |
| Dolor sit amet. | Lorem ipsum.   |
| Dolor sit amet. | Lorem ipsum.   |
```

```
| Lorem ipsum | Dolor sit amet |
| - | - |
|| Lorem ipsum. |
| Dolor sit amet. ||
```

![image](https://github.com/jgm/pandoc/assets/129062294/87b0bab5-f7d7-458d-8a2a-3878d487c104)

**Comment by jgm** [comment]
Closed by 49df8131a5069f24c60714aee617510978053cbc

(Only we use longer bars, `----` instead of `-`, so that all the alignment variants look good and are the same width: `:---`, `:--:`, etc.)

**Comment by jsx97** [comment]
Thanks a lot, John. It seems this comment is not in the main branch yet, right? (Because `brew upgrade pandoc` says `pandoc 3.1.13 already installed`.)

**Comment by jgm** [comment]
It's in main but not yet in a release. I imagine brew upgrade just installs the latest release.
