### ISSUE TITLE
LaTeX writer sets wrong/outdated locale name for polytonic Greek

### ISSUE THREAD

**Issue by ParkerRobb** [jgm/pandoc#9698]
## Explain the problem.

When specifying `lang: el-polyton` in a Markdown document, either in the metadata or in a div or span in the body, the LaTeX writer converts `el-polyton` to `polutonikogreek`. This is done by this line in `Lang.hs`:

https://github.com/jgm/pandoc/blob/f5c7d4dcf73d8259435ab44b072c719f52f00757/src/Text/Pandoc/Writers/LaTeX/Lang.hs#L36

Combined with the `default.latex` template, Pandoc produces this line in the LaTeX output:
```latex
\babelprovide[main,import]{polutonikogreek}
```

babel no longer recognizes `polutonikogreek` as a locale, so PDF compilation fails:

![Screenshot 2024-04-22 at 20 55 46](https://github.com/jgm/pandoc/assets/62605621/259fe29a-b336-4e2b-bf6c-1b5bd09ea0fc)

According to the [babel documentation](https://ctan.mirrors.hoobly.com/macros/latex/required/babel/base/babel.pdf) (p21), babel's locale name for `el-polyton` is now `polytonicgreek`. Manually replacing every instance of `polutonikogreek` with `polytonicgreek` in the LaTeX file fixes the problem and allows for successful PDF compilation.

## Pandoc version?

This is reproducible in the online Pandoc sandbox by entering the following as a Markdown document, and converting to LaTeX using `pandoc --from markdown --to latex --standalone --wrap=none --no-highlight`:
```md
---
lang: el-polyton
---
```

I discovered this on my desktop using Pandoc 3.1.12.2.

**Comment by ParkerRobb** [comment]
Changing this was discussed [here](https://github.com/jgm/pandoc/issues/2727#issuecomment-186134073) in the context of #2727 .

**Comment by jgm** [comment]
I'll change to polytonicgreek.

@adunning looping you in, in case you have further thoughts.
