### ISSUE TITLE
Markdown to Mediawiki: escaped asterisk is not escaped

### ISSUE THREAD

**Issue by vadcx** [jgm/pandoc#9700]
**Explain the problem.**

When converting Markdown -> Mediawiki, an escaped asterisk is not escaped in Mediawiki output, causing it to be interpreted as a formatting character in some cases, such as when starting on a line.

I don't know whether it's a problem on Markdown input or Mediawiki output side.

[Online pandoc link](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5C%5C%21%5C%5C%5C%22%5C%5C%23%5C%5C%24%5C%5C%25%5C%5C%26%5C%5C%27%5C%5C%28%5C%5C%29%5C%5C*%5C%5C%2B%5C%5C%2C%5C%5C-%5C%5C.%5C%5C%2F%5C%5C%3A%5C%5C%3B%5C%5C%3C%5C%5C%3D%5C%5C%3E%5C%5C%3F%5C%5C%40%5C%5C%5B%5C%5C%5C%5C%5C%5C%5D%5C%5C%5E%5C%5C_%5C%5C%60%5C%5C%7B%5C%5C%7C%5C%5C%7D%5C%5C%7E%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22markdown_strict%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

Command: `pandoc -f markdown -t mediawiki markdown-to-mediawiki-asterisk-bug.md -o -`

Input (markdown-to-mediawiki-asterisk-bug.md):
```
This is a normal sentence with a manual text footnote\*

\* The footnote explains why it couldn't just be inside parentheses

And the text continues. Although the "proper" footnote in Markdown has a different syntax.[^1]

[^1]: There's a reason I can never remember what all these different characters stand for.

End of text.
```

Output:

```
This is a normal sentence with a manual text footnote*

* The footnote explains why it couldn’t just be inside parentheses

And the text continues. Although the “proper” footnote in Markdown has a different syntax.<ref>There’s a reason I can never remember what all these different characters stand for.</ref>

End of text.

<references />
```

Will be displayed on MediaWiki as (it's **not** supposed to start a list!):

---

This is a normal sentence with a manual text footnote\*

* The footnote explains why it couldn’t just be inside parentheses

And the text continues. Although the “proper” footnote in Markdown has a different syntax.\[1\]

End of text.

\[1\]: There’s a reason I can never remember what all these different characters stand for.

---

I suppose it should've been enclosed in `<nowiki>` or something?

**Pandoc version?**

pandoc 3.1.8
Features: +server +lua
Scripting engine: Lua 5.4

**Comment by jgm** [comment]
It's an issue on the mediawiki writer side. The markdown reader correctly interprets `*` as a plain string, but the writer needs to add escaping in cases where something might be interpreted as a list.

**Comment by vadcx** [comment]
Thank you, jgm!
