### ISSUE TITLE
audodesk's .dfx support

### ISSUE THREAD

**Issue by kasperk81** [jgm/pandoc#9703]
i believe pandoc support for autodesk's .dfx -> .pdf would be a great enhancement!

spec: https://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf

**Comment by alerque** [comment]
This is wildly –hilariously– out of scope for Pandoc. DXF files are not documents, they are CAD / vector graphics. There would be nothing at all to convert into a document tree that corresponds to *any* of the other document formats.

PDF is in fact not exactly a document format either and Pandoc does not even create them! It only creates document formats that other helper programs (specifically typesetters) render into PDF, which is essentially an image format. A vector image format, but more an image format than a document format.

Rendering a DXF to a PDF is a reasonable operation to need to do and there are tools that can do it, but it isn't reasonable to do that with a *document* manipulation tool: this is pan*doc* not pan*image*, pan*format*, pan*draw*, etc.
