### ISSUE TITLE
Pandoc not identifying typst's #context feature

### ISSUE THREAD

**Issue by foodornt** [jgm/pandoc#9712]
**Explain the problem.**
```
$ pandoc main.typ -o mydoc.docx
"main.typ" (line 38, column 2):
"/home/bruh/.cache/typst/packages/preview/ilm/1.1.0/lib.typ" (line 159, column 21):
unexpected "{"
expecting "//", "/*", operator, "," or ")"
```
The code it's complaining about (It's part of an official recommended template):
```typ
  set page(
    footer: context { // It doesn't like the context here
      ...
    },
  )
```

**Pandoc version**
```
pandoc 3.1.13
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/marv/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```
Latest as of the time I'm posting this

**Comment by foodornt** [comment]
> `context` is one of several big holes in our existing support. You should be able to work around this by commenting out that code.

![image](https://github.com/jgm/pandoc/assets/40924367/b11c674f-0e8d-4f06-9eea-ed32a6691f64)
Unfortunately, it's necessary for the template to work
deleting it would mean removing page numbers and such

Could you perhaps point me to the issue number (if any) discussing these holes?

**Comment by jgm** [comment]
> deleting it would mean removing page numbers and such

Pandoc doesn't concern itself with page numbers and other formatting details anyway.  It just tries to extract and convert the document's structured content.

Indeed, we really *couldn't* support page numbers even if we wanted to invest the time, since there's no way to identify a page number without laying out the document on the page.  Many of the things `#context` supports are in this category.

**Comment by foodornt** [comment]
I get that page numbering isn't an objective of pandoc so I'm closing the issue

Thanks so much for the amazing utility, it's truely a time saver, keep it up!

**Comment by tribut** [comment]
Would it be possible to ignore context blocks instead of failing?
