### ISSUE TITLE
Markdown to PDF: natbib citations are rendered as [?]

### ISSUE THREAD

**Issue by pdehne** [jgm/pandoc#9714]
**Explain the problem.**

If a PDF is generated directly from Markdown with the command shown below, citations in the PDF are rendered as `[?]`.

```
pandoc example.md -s --natbib -o example.pdf
```

Please see my [pandoc-to-pdf](https://github.com/pdehne/pandoc-to-pdf) repo for a full example to reproduce the issues.

![screenshot-citations-not-rendered](https://github.com/jgm/pandoc/assets/1521198/ea6ade8b-a3a4-4a56-a5ba-236a2dc7d4ab)

Additionally, the abstract text is using indent without margins to separate paragraphs, while regular text will use no indent and margins instead. This may be a bug, I am not sure.

![screenshot-paragraph-rendering](https://github.com/jgm/pandoc/assets/1521198/9dbe8564-d59e-4175-a375-0eefdd2978a1)

If the PDF is generated in two steps like below, references are rendered correctly. Paragraphs in abstract and regular text are still rendered differently, though.

```
pandoc example.md -s --natbib -t latex -o example.tex
latexmk -pdf example.tex
```

**Pandoc version?**

3.1.3, Linux

**Comment by jgm** [comment]
Yes.  Because when you go straight to pdf with `--natbib`, pandoc doesn't run bibtex for you.
If you use `--natbib`, you need to go to standalone latex and run the latex and bibtex commands yourself.

As the manual says:

> `--natbib`
> Use [natbib](https://ctan.org/pkg/natbib) for citations in LaTeX output. This option is not for use with the [`--citeproc`](https://pandoc.org/MANUAL.html#option--citeproc) option or with PDF output. It is intended for use in producing a LaTeX file that can be processed with [bibtex](https://ctan.org/pkg/bibtex).

**Comment by pdehne** [comment]
I see, I overlooked that it explicetely says natbib is not for PDF, sorry about that. Just as an idea, if the system already provides the [latexmk](https://ctan.org/pkg/latexmk?lang=en) command, using it would make it possible to render directly to PDF.

**Comment by jgm** [comment]
Yes, you can use `--pdf-engine=latexmk`, and then it might take care of the bibtex step for you.  (You might need some additional `--pdf-engine-opt`)
