### ISSUE TITLE
export from google docs: lots of empty html comment inside clode blocks

### ISSUE THREAD

**Issue by sebastian-philipp** [jgm/pandoc#9723]
this docx was generated from google docs

![image](https://github.com/jgm/pandoc/assets/2574405/2e26690f-9915-431b-8233-b2d337762836)

[pandoc-empty-html-blocks.docx](https://github.com/jgm/pandoc/files/15218083/pandoc-empty-html-blocks.docx)

generate the md via: 

```
pandoc -o pandoc-empty-html-blocks.md pandoc-empty-html-blocks.docx
```
The pandoc-empty-html-blocks.md looks like so: 

    -   
    
    ```{=html}
    <!-- -->
    ```
    -   
Notice the empty html comment inside an html code block. 

pandoc 3.1.3

**Comment by jgm** [comment]
That's not a code block; it's a raw HTML block using the `raw_attribute` syntax (see manual).
So it's the equivalent of
```
<!-- -->
```

**Comment by jgm** [comment]
Pandoc will add an empty HTML comment between two separate bullet lists, in order to keep them from being treated as one list.  That is why it's there.  If you want the more compact form (without `raw_attribute`), you can specify `-t markdown-raw_attribute`.

**Comment by jgm** [comment]
In any case, this is not a bug.
