### ISSUE TITLE
Several bug with pandoc-xnos

### ISSUE THREAD

**Issue by unitscan** [jgm/pandoc#9735]
I'm looking for a method to export the numbering of sections, equations, figures and tables from a .tex file, and the pandoc-xnos package is right for me. Unfortunately, when I use this filter I get several error messages.

> Traceback (most recent call last):
>   File "C:\Logs\pandoc_eqnos.py", line 549, in <module>
>     main()
>   File "C:\Logs\pandoc_eqnos.py", line 512, in main
>     altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Logs\pandoc_eqnos.py", line 512, in <lambda>
>     altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
>                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Utente-XB\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandocfilters.py", line 128, in walk
>     res = action(item['t'],
>           ^^^^^^^^^^^^^^^^^
>   File "C:\Users\Utente-XB\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandocxnos\core.py", line 1150, in insert_secnos
>     _sec += 1
> TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
> Error running filter pandoc_eqnos.py:
> Filter returned error status 1

The prompt command is `pandoc --from latex+raw_tex --filter=pandoc_eqnos.py -s test.tex -o test.docx`, the .py filters is https://github.com/tomduck/pandoc-eqnos/blob/master/pandoc_eqnos.py and the .tex file is

```
\documentclass{article}
\usepackage{blindtext}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\usepackage{siunitx}
\DeclareSIUnit\angstrom{\text {A}}
 
\title{Sections and Chapters}
\author{Overleaf}
\date{\today}

\begin{document}
\maketitle
\section{Introduction}

This is the first section.

\begin{equation} E = mc^2 \end{equation}

Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
Etiam lobortis
facilisis sem. Nullam nec mi et neque pharetra sollicitudin. Praesent imperdiet mi nec ante. Donec ullamcorper, felis non sodales commodo, lectus velit ultrices augue, a dignissim nibh lectus placerat pede.
Vivamus nunc nunc, molestie ut, ultricies vel, semper in, velit.
Ut porttitor. Praesent in sapien.
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Duis fringilla tristique neque.
Sed interdum libero ut metus. Pellentesque placerat.
Nam rutrum augue a leo. Morbi sed elit sit amet ante lobortis sollicitudin. Praesent blandit blandit
mauris. Praesent lectus tellus, aliquet aliquam, luctus a, egestas a, turpis.
Mauris lacinia lorem sit amet ipsum. Nunc quis urna dictum turpis accumsan semper.

\section{Second Section}
This is the second section

\begin{center}
\begin{figure}
	\begin{tikzpicture}
		\begin{axis}[
			colorbar,
			colorbar style={
				title=$V$,
				ylabel=\unit{\kilo\cal} \unit{\mol^{-1}},
				ytick={0,50,100,150,200,250},
				xshift=1cm
			},
			xtick={1,2,3,4},xmin=1,xmax=4.5,
			ytick={1,2,3,4},ymin=1,ymax=4.5,
			ztick={0,50,100,150,200,250},zmin=0,zmax=250,
			xlabel={$r_{\mathrm{AB}}\hspace{3px}\left(\unit{\angstrom}\right)$},
			ylabel={$r_{\mathrm{BC}}\hspace{3px}\left(\unit{\angstrom}\right)$},
			zlabel={$V \hspace{3px} \left(\unit{\kilo\cal} \hspace{3px} \unit{\mol^{-1}}\right)$},
			% tick align=outside,
			zticklabel style={yshift=5pt},
			xticklabel style={xshift=5pt},
			x label style={yshift=0.25cm},
			y label style={yshift=0.5cm},
		]
			\addplot3 [surf,shader=flat,draw=black,domain=1:4.5,y domain=1:4.5] {(128*(1-exp(-(x-1.3)))^2)+(128*(1-exp(-(y-1.3)))^2)};
		\end{axis}
	\end{tikzpicture}
\caption{Sezione dell'ipersuperficie dell'energia potenziale per una generica molecola ABC}
\end{figure}
\end{center}

\end{document}
```
Running Pandock 3.1.13 on Windows 10

**Comment by jgm** [comment]
Please report this to the maintainer of pandoc-xnos.  We have nothing to do with that filter.
