### ISSUE TITLE
YAML parse exception...: did not find expected <document start>

### ISSUE THREAD

**Issue by iwelch** [jgm/pandoc#9746]
macos
pandoc 3.1.13
Features: +server +lua
Scripting engine: Lua 5.4

`pandoc -f markdown_mmd+yaml_metadata_block -t latex -s -o test.pdf < test.md`

on

```
---
title: "Hello"
author: "Ivo Welch"
---

hello

---
\footnotesize

## The Meaning of Climate Temperature Differences

For comparison, climate differences today are:

---
```

leads to

```
YAML parse exception at line 5, column 0:
did not find expected <document start>
```

small variations in the input file often do not.  not sure what is causing it (or how to sidestep it in a larger document).

**Comment by jgm** [comment]
Put a blank line between the `---` and `\footnotesize` if you intend it to be a horizontal rule and not the start of a YAML metadata scetion.

**Comment by iwelch** [comment]
thanks.  can there be YAML statements in the middle of a file?  I have never seen YAML beyond the first few lines of the markdown file.

**Comment by jgm** [comment]
Yes, they can occur anywhere (in pandoc's markdown variant).
