### ISSUE TITLE
Pandoc doesn't preserve "Don't expand character spaces on a line that ends with SHIFT+RETURN" setting from reference doc

### ISSUE THREAD

**Issue by timunrau** [jgm/pandoc#9767]
**Describe the issue:**
When converting HTML to DOCX, with a reference doc that has "Don't expand character spaces on a line that ends with SHIFT+RETURN" checked in Word options, the output document does not have that setting checked. I would like to see Pandoc preserve this setting in the output document if the reference document has it set.

**Pandoc version?**
2.9.2.1

**Comment by jgm** [comment]
Can you try with the latest pandoc version to make sure the issue is there?  Your version is quite old.

**Comment by timunrau** [comment]
Tried with pandoc 3.2 and it worked. Sorry for the inconvenience!
