### ISSUE TITLE
Using `\linewidth` instead when converting img/table to latex

### ISSUE THREAD

**Issue by zwz** [jgm/pandoc#9775]
**Describe your proposed improvement and the problem it solves.**
When converting img/table with percentage width (in html) to latex, pandoc uses `\textwidth` or `\columnwidth` now, like
```
\includegraphics[width=0.4908\textwidth]{test.png}
\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3333}}
  >{\centering\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3333}}
  >{\centering\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3333}}@{}}
...
```
It works perfect for most cases. 
But when the img/table is in enumerate environment with items indented, it stretches out at the left side, 
makes the text in the environment not so fluent and beautiful.

I googled and according to
1. https://tex.stackexchange.com/questions/16942/difference-between-textwidth-linewidth-and-hsize
2. https://tex.stackexchange.com/questions/124323/tabularx-within-the-enumerate-environment
3. https://tex.stackexchange.com/questions/250662/width-of-minipages-inside-enumerate-environments

it seems a good idea to use `\linewidth` instead.

**Comment by jgm** [comment]
Similar issues:
 (for images) https://github.com/jgm/pandoc/issues/9396
(for figures) https://github.com/jgm/pandoc/issues/9268

Also relevant:
https://github.com/jgm/pandoc/issues/9268
https://github.com/jgm/pandoc/issues/7475 (if we made this change, it might screw up some of the methods people have used to get full-width tables in two-column mode)

**Comment by jgm** [comment]
Current uses of `\textwidth`:

Image: https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/LaTeX.hs#L1071 
https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/LaTeX.hs#L1079

Column divs: https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/LaTeX/Util.hs#L238

Table uses `\colwidth`: https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/LaTeX/Table.hs#L152
https://github.com/jgm/pandoc/blob/main/src/Text/Pandoc/Writers/LaTeX/Table.hs#L152
