### ISSUE TITLE
Just a moment...Enable JavaScript and cookies to continue

### ISSUE THREAD

**Issue by futureflsl** [jgm/pandoc#9779]
pandoc -o output.docx https://xxxx can not convert to docx document,when docx opened,content is 
Just a moment...
Enable JavaScript and cookies to continue

**Comment by alerque** [comment]
Your input document appears to be a web app that needs a JavaScript engine just to figure out what text will get drawn. It isn't a document or even a page, it is an app.

**Comment by futureflsl** [comment]
pandoc -o output.docx https://blog.csdn.net/m0_74824051/article/details/133248433
like this url,converted document show content:
Just a moment...
Enable JavaScript and cookies to continue

**Comment by MohammadNft** [comment]
> pandoc -o output.docx https://xxxx can not convert to docx document,when docx opened,content is 
> Just a moment...
> Enable JavaScript and cookies to continue

[]()

**Comment by lordnik22** [comment]
Pandoc is the wrong tool for the job. These "websites" (rather apps) require a functioning browser and not just a http-call.

You may can get a working solution using a headless-browser (https://github.com/dhamaniasad/HeadlessBrowsers). Normally such apps are not meant to be scrapped else they would provide an endpoint.

It's advised to use official API or "export"-features of the site. Using a headless-browser is not a clean solution.
 
Steps to store a app-page:
1. Load the page in a headless browser
2. Wait for the app to render and "generate" the content
3. Store the page to file (similar to manually Save Page As...)
4. Let pandoc convert the file to the desired output format.
