### ISSUE TITLE
Comments with $-- do not work when output HTML

### ISSUE THREAD

**Issue by zineorg** [jgm/pandoc#9795]
I am trying to keep comments in the markdown files that are not processed in the final HTML. I use the $-- from the documentation, but I still get the lines with a long hyphen preceding them in the generated HTML.

$-- I'm a comment in one line.
$--I'm a comment in one line.

I get this:

$– I'm a comment in one line.

Why does this happen? I have tried with the latest version of pandoc, and the also with pandoc 2.9.2.1

**Comment by tarleb** [comment]
The `$--` syntax is for *templates*, not for Markdown input.

One can use HTML `<!-- comments -->` in Markdown. See also [this StackOverflow Q&A](https://stackoverflow.com/questions/4823468/comments-in-markdown).

**Comment by zineorg** [comment]
Thank you tarleb! This works just fine:

[//]: # (This may be the most platform independent comment)
