### ISSUE TITLE
Typst citations are unresponsive to csl style

### ISSUE THREAD

**Issue by aghaynes** [jgm/pandoc#9801]
**Describe your proposed improvement and the problem it solves.**

Typst citations are currently unresponsive to changes in the csl style applied. It seems that the csl is not taken from the yaml header and applied to the bibliography call...

```
#bibliography("references.bib", style: "nature")
```
Note that  `style: "nature.csl"` does not work - that results in an error.

Currently (well, version pandoc 3.2), the typ file just has

```
#bibliography("references.bib")
```

I'm compiling PDFs from quarto (v 1.5.37) qmd files, in case that's important.

**Describe alternatives you've considered.**

Editing the bibliography line to include the style and recompiling manually works...

**Comment by iandol** [comment]
Quarto uses **different metadata** and handles this differently to Pandoc, you should raise the issue with them, but basically for quarto, you can do this (if you want to use citeproc):

```yaml
csl: cell.csl
bibliography: bib.json
format:
  typst:
    citeproc: true
```

or if you want to use the native engine, set `citeproc` to false and add `bibliographystyle`.

---

For Pandoc, you can use `to: typst-citations` to disable the typst citation engine and then citeproc can use `csl`. For native citations you use `to: typst` and you can set **either** `csl` or `bibliographystyle`, as you can see from the typst template:

https://github.com/jgm/pandoc-templates/blob/master/default.typst#L93

So in all cases `csl: nature.csl` should work...

**Comment by aghaynes** [comment]
thanks @iandol. 

Using citeproc and csl does indeed work, or citeproc: false and bibliographystyle, (but not csl). 

I'll maybe follow up with quarto, as it doesnt seem to work as it's documented on their site...

**Comment by iandol** [comment]
You are using a pre-release version (V1.5x), and Typst is also undergoing significant changes, so I wouldn't expect a stable experience at the moment. But I think this is documented here:

https://quarto.org/docs/reference/formats/typst.html#references

| csl | Citation Style Language file to use for formatting references. |
| -- | -- |
| citeproc | Turn on built-in citation processing. To use this feature, you will need to have a document containing citations and a source of bibliographic data: either an external bibliography file or a list of references in the document’s YAML metadata. You can optionally also include a csl citation style file. |
| bibliographystyle | The bibliography style to use (e.g. #set bibliography(style: "apa")) when using typst built-in citation system (e.g when not citeproc: true). |

**Comment by aghaynes** [comment]
Yes, indeed. I commented on the issue at quarto and they're probably going to integrate the info into the main citations page, as they have done for latex.
Thanks for your thoughts @iandol :)
