### ISSUE TITLE
Please tag pandoc `3.2` to `3.2.0`

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#9810]
Having version `3.2.0` tagged as `3.2` causes package managers like [asdf](https://github.com/asdf-vm/asdf) not to find this version as it does not follow semantic versioning.

Please retag to `3.2.0` or add a new tag `3.2.0`.

**Comment by StephanMeijer** [comment]
Consistent with previous tags. So Pandoc consistently does not follow semantic versioning. Therefore closing here.

**Comment by tarleb** [comment]
Pandoc uses the [Haskell PVP Spec](https://pvp.haskell.org/).

**Comment by StephanMeijer** [comment]
@tarleb Interesting. Didn't know this exists. I put out a PR at the package manager that didn't follow HPVP but expects Semantic Versioning.
