### ISSUE TITLE
LaTeX Reader does not handle environment delimiters or block commands defined with a macro

### ISSUE THREAD

**Issue by timtylin** [jgm/pandoc#982]
This issue pertains to all versions up to current HEAD. Perhaps the most succinct example is with equations:

**Command**
`pandoc -f latex -t native --mathjax`

**Input**

``` latex
\newcommand{\BEQ}{\begin{equation}}
\newcommand{\EEQ}{\end{equation}}

\BEQ
y=x^2
\EEQ

\begin{equation}
y=x^2
\end{equation}
```

**output**

```
[Para [Str "y=x",Superscript [Str "2"]]
,Para [Math DisplayMath "y=x^2"]]
```

Considering that environment delimiters are usually prime candidates for macro shorthand, this is probably a genuine shortcoming. As far as I can tell, block commands have a similar problem.

I can try to fix this, but I'm not sure exactly how you would want to approach the problem. We can either:
1. monkey-patch all the individual parsers (and all `controlSeq "end"` calls) with a map to applyMacros.
2. bite the bullet and do multi-pass parsing, change `readLaTeX` to first resolve all macros on the input string, then do the usual parse.

**Comment by jgm** [comment]
This would also handle #934

**Comment by jgm** [comment]
Be sure to look at these related macro issues: #3236, #987, #2118, #1390

**Comment by jgm** [comment]
One issue with modifying the input stream is that you lose good source position information.
(If the macro adds lines, line numbers of errors will be misleading.)

**Comment by jgm** [comment]
I've got an idea for how to solve this, keeping source position info.

Instead of parsing a `[Char]`, we parse a stream of tokens (produced by a tokenizer).
```
data Tok = Tok (Line, Column) TokType Text
data TokType = CtrlSeq | Spaces | Newline | Symbol | Word
```
Then, when we expand a macro, tokenize the expansion and set the source position of each token to the source position of the original unexpanded macro.
