### ISSUE TITLE
Issue with `--metadata-file` Handling Multiline String Metadata in Pandoc 3.2-nightly-2024-05-30

### ISSUE THREAD

**Issue by TomBener** [jgm/pandoc#9828]
**Description:**

I encountered an issue with [Pandoc 3.2-nightly-2024-05-30](https://github.com/jgm/pandoc/actions/runs/9299004084) where using a `metadata.yml` file with multiline string metadata causes the generated `.docx` file to be corrupted and unopenable in MS Word.

**Steps to Reproduce:**

1. Create a Markdown file `test.md` with the following content:
    
```md
# Test document

This is a test document.
```

2. Create a metadata file `metadata.yml` with the following content:

```yaml
title: |
  This is the title
abstract: |
  This is the abstract. It can be multiple lines long.
  It can contain any characters, including "quotes" and 'apostrophes'.
```

3. Run the following Pandoc command to generate a `.docx` file:

```sh
pandoc test.md -o test.docx --metadata-file=metadata.yml
```

4. Attempt to open the generated `test.docx` file in MS Word.

**Expected Behavior:**

The `.docx` file should open normally in MS Word, displaying the document with the metadata title and abstract correctly applied.

**Actual Behavior:**

MS Word reports an error when attempting to open the `test.docx` file:

```
Word experienced an error trying to open the file.
Try these suggestions.
* Check the file permissions for the document or drive.
* Make sure there is sufficient free memory and disk space.
* Open the file with the Text Recovery converter.
(test.docx)
```

**Workaround:**

The issue does not occur if the `metadata.yml` file is modified to have single-line string metadata. For example:

```yaml
title: This is the title
abstract: |
  This is the abstract. It can be multiple lines long.
  It can contain any characters, including "quotes" and 'apostrophes'.
```

**Additional Information:**

- This issue does not occur with Pandoc 3.2.
- The issue is specific to the nightly build Pandoc 3.2-nightly-2024-05-30.

**System Information:**

- Pandoc version: 3.2-nightly-2024-05-30
- OS: macOS 14.5

---

[pandoc-3.2.docx](https://github.com/user-attachments/files/15509165/pandoc-3.2.docx)

[pandoc-3.2-nightly-2024-05-30.docx](https://github.com/user-attachments/files/15509167/pandoc-3.2-nightly-2024-05-30.docx)

**Comment by jgm** [comment]
Thanks.  I see the issue; we now end up with
```xml
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title" />
      </w:pPr>
      <w:p><w:pPr><w:pStyle w:val="BodyText" /></w:pPr><w:r><w:t xml:space="preserve">This</w:t></w:r><w:r><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">is</w:t></w:r><w:r><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">the</w:t></w:r><w:r><w:t xml:space="preserve"> </w:t></w:r><w:r><w:t xml:space="preserve">title</w:t></w:r></w:p>
    </w:p>
```
with a w:p inside a w:p.
