### ISSUE TITLE
Fenced block quotes

### ISSUE THREAD

**Issue by jsx97** [jgm/pandoc#9831]
Pandoc's Markdown already provides custom divs (`:::`), but having a dedicated syntax for large block quotes might be a good idea. The traditional block quote syntax (`>`), in my personal opinion, is only convenient if a block quote is not very large.

This is what I use for myself:

```
"""
Fenced block quote. 
"""
```

```
<blockquote>
  <p>Fenced block quote.</p>
</blockquote>
```

```
""""
"""
Nested fenced block quote.
"""

Fenced block quote.
""""
```

```
<blockquote>
  <blockquote>
    <p>Nested fenced block quote.</p>
  </blockquote>
  <p>Fenced block quote.</p>
</blockquote>
```

**Comment by jgm** [comment]
I'm not interested in introducing a new, incompatible block quote syntax at this point.
Any decent editor should be able to add the `>` to any size text.
