### ISSUE TITLE
Pandoc.List type in Lua filter causes incorrect JSON encoding

### ISSUE THREAD

**Issue by jeffvalk** [jgm/pandoc#9834]
### Description

Using the (very handy!) `pandoc.List` type in a Lua filter causes the value to be serialized by `pandoc.json` as a JSON object rather than an array.

To demonstrate, if you create the following filter as `test.lua`
```lua
function Pandoc(doc)
  local t1 = {"one", "two", "three"} -- two identical tables, indexed by integer
  local t2 = {"one", "two", "three"}

  pandoc.List(t2) -- make the second a List

  print(pandoc.json.encode(t1)) -- this serializes as a JSON array
  print(pandoc.json.encode(t2)) -- but this does not
  os.exit()
end
```
and run it
```sh
echo | pandoc -L test.lua
```
it outputs the following:
```
["one","two","three"]
{"1":"one","2":"two","3":"three"}
```
These two lines should be the same.

### Possible cause
The `pandoc.List` type adds an "__index" function to the metatable. Is this the culprit? (Perhaps using string indexes rather than numbers?)

### Version info
Tested on pandoc 3.1.13

**Comment by jgm** [comment]
@tarleb will know the answer to this.

**Comment by tarleb** [comment]
For a temporary fix, add this to your Lua code:

``` lua
debug.getregistry()['HsLua JSON array'] = getmetatable(pandoc.List{})
```

**Comment by jeffvalk** [comment]
Fantastic. Thanks @tarleb!

**Comment by bpj** [comment]
@tarleb isn't the value of `pandoc.List` also the metatable of an instance? It seems you can monkeypatch the metatable by `pandoc.List.somename = somefunction`! 😁

**Comment by tarleb** [comment]
Indeed, `pandoc.List == getmetatable(pandoc.List{})`, so the above could be shortened to 

``` lua
debug.getregistry()['HsLua JSON array'] = pandoc.List
```

And since we're talking about monkey-patching: that'd be an alternative workaround.

``` lua
pandoc.List.__tojson = function(list)
  return '[' .. table.concat(list:map(pandoc.json.encode), ',') .. ']'
end
```
