### ISSUE TITLE
Lua: add unique (and extend_unique?) methods to List

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc#9836]
**Suggestion**

Add a `unique` method to the List metatable.

Of course it would return a new list with any duplicate values removed.

**Rationale**

It would be extremely useful when adding to already existing classes. Basically you could say

``````lua
foo.classes = (foo.classes .. added_list):unique()
``````

(Hmm, perhaps an `extend_unique` method as well/instead! :-)

**Alternatives**

``````lua
local merged = foo.classes .. { }
for _, v in ipairs(added_list) do
  if not merged:includes(v) then
    merged:insert(v)
  end
end
foo.classes = merged
``````

of course I already have a function to do this in my little bag of helpers, but it would be nice to have it builtin. In fact I sometimes monkey patch the List metatable with my helper function but I feel guilty for it!

**Comment by tarleb** [comment]
One of the reasons that I've been avoiding a `unique` function is that uniqueness is related to equality, and equality can mean different things. Uniqueness of anything other than numbers and strings gets complicated quickly.

Using a pandoc example:

``` lua
print(pandoc.Space() == pandoc.Space())         -- true
print(rawequal(pandoc.Space(), pandoc.Space())) -- false
```

**Comment by bpj** [comment]
You could always ignore non-string/number values since the typical use case would probably with a list of class attributes.

FWIW my actual function uses a Lua table to track already seen values, so if Lua thinks that `val` already exists as a key in that table it is the same. That's about as strict a definition of equality as you can get in Lua. I pretty much only ever use it with class attributes, so I probably should change it to ignore non-string values!

**Comment by bpj** [comment]
So here is my updated function — in [MoonScript], which hopefully is easy to read if you ever have seen Lua, Python and CoffeeScript.[^1]

[^1]: `pdc` and `pdu` are shorthand aliases for the `pandoc` and `pandoc.utils` libraries.

  [MoonScript]: https://moonscript.org

``` moon
-- Get the unique string values in one or more lists as a new list
H.unique_strings = do
  import pack from table
  (... using nil) ->
    args = pack ...
    rv = pdc.List{}
    seen = {v,true for v in *rv when 'string' == pdu.type v}
    -- Append unique strings from the arguments
    for i=1,args.n
      unless nil == args[i] -- skip nils
        -- Make sure it is a list
        ok,got  = pcall pdc.List, args[i]
        unless ok -- if it isn't a list
          error "Failed to turn argument ##{i} into a List: #{got}"
        -- Loop over the values in this list
        for v in *got
          if 'string' == pdu.type v
            -- Add this value unless we remember it
            rv[#rv+1] = v unless seen[v]
            -- Remember this value
            seen[v] = true
    return rv
```

I’m pretty happy with this simplification!

**Comment by tarleb** [comment]
Here are two versions that have give good performance. The first one piggy-backs on `pandoc.List.filter` and should have a space and time complexity of O(n).

``` lua
local function seen_before (seen)
  return function (el)
    if seen[el] then
      return false
    else
      seen[el] = true
      return true
    end
  end
end

-- Usage:
print(list:filter(seen_before{}))
```

The second tests equality, but expects the list elements to be sortable, and returns them in sorted order. Space complexity is *O(n)* and time should be *O(n ⋅ log n)* (the complexity of `table.sort` being the defining factor).

``` lua
pandoc.List.unique = function(list)
  local copy = list:clone()
  copy:sort()
  local j = 1 -- next insert
  for i = 1, #copy do
    if copy[i] ~= copy[i+1] then
      copy[j] = copy[i]
      j = j + 1
    end
    if j < i + 1 then
      copy[i] = nil
    end
  end
  return copy
end

-- Usage:
print(list:unique())
```

Any algorithms that tests equality while preserving order would have complexity *O(n²)*.

I gave it some thought, but I'm just not comfortable adding a function that can have so many fundamentally different implementations, all of which might have their own use-case. Sorry.

**Comment by alerque** [comment]
As unsatisfactory as it might be I think this is the right call. It isn't that it can't be implemented, it's that it could be implemented in so many ways that will produce different results. I looked at one implementation of my own and it's different yet again than any of the 3 above because its use case was for a different scenario. I think this is one of those things that will always be wrong no matter how you do it, so it's probably better to make people pick their own implementation on a use-case-specific basis that provide a generic one and field constant bug reports.
