### ISSUE TITLE
Document with comment on Title puts comment in `<title>` when using standalone

### ISSUE THREAD

**Issue by StephanMeijer** [jgm/pandoc#9838]
**Explain the problem.**

Document with comment on Title will put content in `$pagetitle$`  and `$title$`

---

## Reproduction, example 1

Input document: 
[input.docx](https://github.com/user-attachments/files/15534834/input.docx)

Command: `pandoc -s --to=html --track-changes=all --template=tpl.html input.docx`

<details>

<summary>
Template (HTML) - `tpl.html`
</summary>

```
$if(pagetitle)$
  <meta name="pagetitle" content="$pagetitle$" />
$endif$
$if(title)$
  <meta name="title" content="$title$" />
$endif$
```

</details>

<details>

<summary>
Output (HTML)
</summary>

```html
  <meta name="pagetitle" content="XxxxxxxxTitle of document" />
  <meta name="title" content="<span class="comment-start" id="0"
data-author="Stephan Meijer"
data-date="2024-06-03T14:21:00Z">Xxxxxxxx</span>Title of document<span
class="comment-end" id="0"></span>" />
```

</details>

---

## Reproduction, example 2

Input document: 
[input.docx](https://github.com/user-attachments/files/15534834/input.docx)

Command: `pandoc -s --to=html --track-changes=all ./input.docx`

<details>

<summary>
Output (HTML)
</summary>

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>XxxxxxxxTitle of document</title>
  <style>
    html {
      color: #1a1a1a;
      background-color: #fdfdfd;
    }
    body {
      margin: 0 auto;
      max-width: 36em;
      padding-left: 50px;
      padding-right: 50px;
      padding-top: 50px;
      padding-bottom: 50px;
      hyphens: auto;
      overflow-wrap: break-word;
      text-rendering: optimizeLegibility;
      font-kerning: normal;
    }
    @media (max-width: 600px) {
      body {
        font-size: 0.9em;
        padding: 12px;
      }
      h1 {
        font-size: 1.8em;
      }
    }
    @media print {
      html {
        background-color: white;
      }
      body {
        background-color: transparent;
        color: black;
        font-size: 12pt;
      }
      p, h2, h3 {
        orphans: 3;
        widows: 3;
      }
      h2, h3, h4 {
        page-break-after: avoid;
      }
    }
    p {
      margin: 1em 0;
    }
    a {
      color: #1a1a1a;
    }
    a:visited {
      color: #1a1a1a;
    }
    img {
      max-width: 100%;
    }
    svg {
      height: auto;
      max-width: 100%;
    }
    h1, h2, h3, h4, h5, h6 {
      margin-top: 1.4em;
    }
    h5, h6 {
      font-size: 1em;
      font-style: italic;
    }
    h6 {
      font-weight: normal;
    }
    ol, ul {
      padding-left: 1.7em;
      margin-top: 1em;
    }
    li > ol, li > ul {
      margin-top: 0;
    }
    blockquote {
      margin: 1em 0 1em 1.7em;
      padding-left: 1em;
      border-left: 2px solid #e6e6e6;
      color: #606060;
    }
    code {
      font-family: Menlo, Monaco, Consolas, 'Lucida Console', monospace;
      font-size: 85%;
      margin: 0;
      hyphens: manual;
    }
    pre {
      margin: 1em 0;
      overflow: auto;
    }
    pre code {
      padding: 0;
      overflow: visible;
      overflow-wrap: normal;
    }
    .sourceCode {
     background-color: transparent;
     overflow: visible;
    }
    hr {
      background-color: #1a1a1a;
      border: none;
      height: 1px;
      margin: 1em 0;
    }
    table {
      margin: 1em 0;
      border-collapse: collapse;
      width: 100%;
      overflow-x: auto;
      display: block;
      font-variant-numeric: lining-nums tabular-nums;
    }
    table caption {
      margin-bottom: 0.75em;
    }
    tbody {
      margin-top: 0.5em;
      border-top: 1px solid #1a1a1a;
      border-bottom: 1px solid #1a1a1a;
    }
    th {
      border-top: 1px solid #1a1a1a;
      padding: 0.25em 0.5em 0.25em 0.5em;
    }
    td {
      padding: 0.125em 0.5em 0.25em 0.5em;
    }
    header {
      margin-bottom: 4em;
      text-align: center;
    }
    #TOC li {
      list-style: none;
    }
    #TOC ul {
      padding-left: 1.3em;
    }
    #TOC > ul {
      padding-left: 0;
    }
    #TOC a:not(:hover) {
      text-decoration: none;
    }
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    /* The extra [class] is a hack that increases specificity enough to
       override a similar rule in reveal.js */
    ul.task-list[class]{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      font-size: inherit;
      width: 0.8em;
      margin: 0 0.8em 0.2em -1.6em;
      vertical-align: middle;
    }
    .display.math{display: block; text-align: center; margin: 0.5rem auto;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<header id="title-block-header">
<h1 class="title"><span class="comment-start" id="0"
data-author="Stephan Meijer"
data-date="2024-06-03T14:21:00Z">Xxxxxxxx</span>Title of document<span
class="comment-end" id="0"></span></h1>
</header>
<p>Some text.</p>
<h1 id="heading-of-document">Heading of document</h1>
<p>Some other text.</p>
</body>
</html>
```

</details>

---

**Pandoc version?**

Issue on Pandoc 3.2 and Pandoc 3.1.8.

```
pandoc 3.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/steve/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by StephanMeijer** [comment]
Same behaviour for `$subtitle$`.

**Comment by jgm** [comment]
We downshift inline content to a plain text in generating `pagetitle` using `stringify`.
Since the comment is contained in a native Span, it will be converted.  We could modify `stringify` to ignore Spans with class `comment-start`, I suppose, but I'm a bit reluctant to do that, because someone might use such a class for their own purposes, outside the context of docx.Suggested workaround:  specify `pagetitle` directly with `-V`.

**Comment by StephanMeijer** [comment]
> We downshift inline content to a plain text in generating `pagetitle` using `stringify`. Since the comment is contained in a native Span, it will be converted. We could modify `stringify` to ignore Spans with class `comment-start`, I suppose, but I'm a bit reluctant to do that, because someone might use such a class for their own purposes, outside the context of docx.Suggested workaround: specify `pagetitle` directly with `-V`.

Using the workaround would be impossible in our situation. 

We do have a workaround ourselves (post-processing the HTML), but I could see this issue being potentially problematic for other users.

Would there be any long-term solution, such as calling functions in the template to filter out these things?

**Comment by jgm** [comment]
You can use a Lua filter to filter out Spans with comment-start class in the metadata, if you don't need them to be present in the HTML (but maybe you do).

**Comment by jgm** [comment]
I don't understand "impossible," though.  Surely it's *possible*.  For example, you can render the document using a template that just contains `$pagetitle$`, but without `--track-changes`.  Put this in an environment variable and then pass it into your next pandoc invocation (with `--track-changes`) as the value of `-V pagetitle=$PAGETITLE$`.  That's all easily scriptable.

**Comment by StephanMeijer** [comment]
> You can use a Lua filter to filter out Spans with comment-start class in the metadata, if you don't need them to be present in the HTML (but maybe you do).

We do need to have them in the HTML. Today we switched from a meta-value to the `<title>`-tag that allows to process this in our post-processor. Stripping out using a Pandoc filter would also be possible indeed for other users (we are moving away from Pandoc filters for other reasons).

> I don't understand "impossible," though. Surely it's _possible_. For example, you can render the document using a template that just contains `$pagetitle$`, but without `--track-changes`. Put this in an environment variable and then pass it into your next pandoc invocation (with `--track-changes`) as the value of `-V pagetitle=$PAGETITLE$`. That's all easily scriptable.

That would require us to be aware of the title of the document beforehand, correct?

**Comment by StephanMeijer** [comment]
P.S.: I narrowed down the issue at hand, as this is also occuring without templates when using standalone-mode.

**Comment by jgm** [comment]
> That would require us to be aware of the title of the document beforehand, correct?

No, because you can extract it from the document by writing the document using `-s --template=titleonly.html` where `titleonly.html` is just `$pagetitle$`.

**Comment by jgm** [comment]
Or use a template with contents `$meta-json$` and you'll get a JSON document containing all the metadata in rendered form.

**Comment by StephanMeijer** [comment]
> > That would require us to be aware of the title of the document beforehand, correct?
> 
> No, because you can extract it from the document by writing the document using `-s --template=titleonly.html` where `titleonly.html` is just `$pagetitle$`.

I'm not sure how it would actually help us. But anyway, for now we are set. Thanks for your help!
