### ISSUE TITLE
Regarding issues with converting Markdown using Pandoc

### ISSUE THREAD

**Issue by 190679163** [jgm/pandoc#9842]
I encountered the following issue while converting Markdown to DOCX.

```python
$$
\text{Classical complexity} = O(2^n) \\
\text{Quantum complexity} = O(2^{n/2})
$$
```
The bash instruction I use:

```python
pandoc input.md -f markdown_mmd+latex_macros+tex_math_single_backslash+gfm_auto_identifiers+fenced_code_blocks+angle_brackets_escapable+wikilinks_title_before_pipe+wikilinks_title_after_pipe+autolink_bare_uris+inline_code_attributes+line_blocks -o output.docx
```

The error message is displayed as follows:

```python
[WARNING] Could not convert TeX math
  \text{Classical complexity} = O(2^n)\\
  \text{Quantum complexity} = O(2^{n/2})
  , rendering as TeX:
  \text{Classical complexity} = O(2^n)\\
  ^
  unexpected control sequence \\
  expecting "%", "\\label", "\\tag", "\\nonumber", whitespace or "\\allowbreak"
```
Pandoc Version:
![image](https://github.com/jgm/pandoc/assets/73594087/a8ea63ba-1376-4249-9ecd-5fb0bbfa06d7)

**Comment by jgm** [comment]
You seem to be expecting the `\\` to work as a line break.  But it only does this in certain special tex environments, such as `aligned`.  Here it will not do that.  It appears that LaTeX just ignores it.  Running LaTeX on a file with this content gives:

<img width="547" alt="Screenshot 2024-06-04 at 8 05 10 AM" src="https://github.com/jgm/pandoc/assets/3044/60ad4a20-0154-4a28-8c8e-a71d8359a79d">

You probably want something like:

```
$$
\begin{aligned}
\text{Classical complexity} &= O(2^n) \\
\text{Quantum complexity} &= O(2^{n/2})
\end{aligned}
$$
```

**Comment by 190679163** [comment]
I am grateful for your patient guidance! your assistance has been immensely beneficial to me. Thank you once again!
