### ISSUE TITLE
How to use pandoc-server?

### ISSUE THREAD

**Issue by guanpengchn** [jgm/pandoc#9844]
I have installed pandoc. And run pandoc-server like this:

<img width="576" alt="image" src="https://github.com/jgm/pandoc/assets/13995641/03f01f8a-0036-4449-835f-71c7683fa7b6">

When I curl this port, there is nothing happened. Why?

<img width="566" alt="image" src="https://github.com/jgm/pandoc/assets/13995641/0db96e1e-9c76-42be-b55c-6b98b229e854">

I also try it on Linux server. But the same answer.

**Comment by tarleb** [comment]
Closing in favor of the discussion in #9843.
