### ISSUE TITLE
The command --toc-depth doesn't change the depth (md->pdf)

### ISSUE THREAD

**Issue by Thanatos0173** [jgm/pandoc#9861]
Reproducible steps :
1. Create a file with the content:
```markdown
---
title: Title
subtitle: Subtitle
lang: fr-FR
author: "Author"
theme: "Boadilla"
colortheme: "dolphin"
fonttheme: "structurebold"
aspectratio: 43
fontsize: 14pt
linkstyle: bold
---

# Section One

## Subsection One

Content

## Subsection Two

Content

# Section Two

## Subsection One

Content

## Subsection Two

Content

```

Compile using :

```shell
pandoc -t beamer --toc-depth=5 --toc  <file.md> -o <file.pdf>
```
Output:
The toc slide is :
1. Section One
3. Section Two
 
Expected:
The toc slide should be:
1. Section One
1.1. Subsection One
1.2. Subsection Two
2. Section Two
1.1. Subsection One
1.2. Subsection Two

Version :
```plain
pandoc 3.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/thanatos/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. 
Web: https://pandoc.orgThis is free software; see the source for copying conditions. There is nowarranty, not even for merchantability or fitness for a particular purpose.
```

OS :
Linux, Archcraft

**Comment by jgm** [comment]
default latex template has:
```
$if(beamer)$
\begin{frame}[allowframebreaks]
$if(toc-title)$
  \frametitle{$toc-title$}
$endif$
  \tableofcontents[hideallsubsections]
\end{frame}
$else$
{
$if(colorlinks)$
\hypersetup{linkcolor=$if(toccolor)$$toccolor$$else$$endif$}
$endif$
\setcounter{tocdepth}{$toc-depth$}
\tableofcontents
}
$endif$
```
So, the `\setcounter{tocdepth}{$toc-depth$}` is only set for latex output, not for beamer.
For beamer, we have the `[hideallsubsections]` option hard-coded.

I can't remember the rationale, if any, for these decisions.

**Comment by jgm** [comment]
One important thing to note: in your example, slide level = 2 (see the manual for this concept).  That means that the level-2 headings do *not* create subsections; they create *slides*.  So, even remove `[hideallsubsections]`, you'd only get the top level in your toc.

**Comment by jgm** [comment]
Perhaps a better test case is
```
---
title: Title
subtitle: Subtitle
lang: fr-FR
author: "Author"
theme: "Boadilla"
colortheme: "dolphin"
fonttheme: "structurebold"
aspectratio: 43
fontsize: 14pt
linkstyle: bold
---

# Section One

## Subsection One

### Slide

Content

## Subsection Two


### Another slide

Content

# Section Two

## Subsection One

### Slide title

Content

## Subsection Two

### Another slide title

Content

```

**Comment by jgm** [comment]
I think I'll change this so it uses `toc-depth` like the regular LaTeX template.

**Comment by Thanatos0173** [comment]
So, just to be sure, I can't change the way the toc is generated because I'm using beamer ?  Or do I need to change the default latex template to be able to show more information in the toc ?

**Comment by jgm** [comment]
You'd have to change the latex template, yes.  The commit noted above does this, so you can just grab the new template from there.

**Comment by Thanatos0173** [comment]
Ok, thank you very much !

**Comment by NMarkgraf** [comment]
Bad fix! This breaks all my coding, because I do not want subsections in toc. Beamer does not care about toc-dept. - So this might be a bad solution.

**Comment by jgm** [comment]
@NMarkgraf can you elaborate?  Setting `toc-depth` has no effect in beamer?
