### ISSUE TITLE
Beamer language

### ISSUE THREAD

**Issue by raffaem** [jgm/pandoc#9868]
**Explain the problem.**

Consider the following markdown file, which includes a `lang: it` metadata entry:
```
---
title: "My Title"
author: "This Author"
theme: Madrid
date: \today
toc: true
lang: it
---

# Section 1

## Slide 1

Lorem ipsum

## Slide 2

Doler sit amen
```

Compile it with:

```
pandoc --from markdown --to beamer --standalone main.md --output main.pdf
```

Section heading stays in English:
![image](https://github.com/jgm/pandoc/assets/54762742/cf465a68-049e-48b2-8d02-79ff2ad846b0)

To obtain section heading in the correct language, we need to pass the language as beamer option.

```
pandoc --from markdown --to beamer --standalone main.md --output main.tex
```

Replace the document class with:

```
\documentclass[
  ignorenonframetext,
  italian
]{beamer}
```

Now we have the section heading in the correct language

![image](https://github.com/jgm/pandoc/assets/54762742/2e225755-4739-423c-8459-de47e4566f6e)

**Pandoc version?**
What version of pandoc are you using, on what OS? (If it's not the latest release, please try with the latest release before reporting the issue.)

```
➜  pandoc --version
pandoc 3.1.13
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/raffaele/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

OS is Arch Linux

**Comment by jgm** [comment]
I'll fix this. In the mean time you should be able to work around it with
```
classoptions:
- italian
```
in your metadata.

**Comment by raffaem** [comment]
> I'll fix this. In the mean time you should be able to work around it with
> 
> ```
> classoptions:
> - italian
> ```
> 
> in your metadata.

Just to say that the proposed workaround based on the `classoptions` metadata tag doesn't work and nothing is put in the class options in the corresponding latex file

**Comment by raffaem** [comment]
ok it's `classoption` singular, not plural

**Comment by albersonmiranda** [comment]
Issue persists.
