### ISSUE TITLE
LaTeX Reader does not handle \newenvironment

### ISSUE THREAD

**Issue by lod** [jgm/pandoc#987]
Command

```
pandoc -f latex -t native
```

Input

```
\documentclass{article}
\newenvironment{flubble}{FOO}{BAR}
\begin{document}
   \begin{flubble}
   grr
   \end{flubble}
\end{document}
```

Output

```
[Para [Str "grr"]]
```

Expected Output (approximate)

```
[Para [Str "FOO",Space,Str "grr",Space,Str "BAR"]]
```

Tested with pandoc 1.12.
Expected output verified against pdfTeX 3.1415926-2.4-1.40.13 (TeX Live 2012/Debian)

Possibly related to issue #982

**Comment by bitemyapp** [comment]
Would dearly love this to work, if anyone cares. Having to sed my book before converting to epub/html from LaTeX sucks.
