### ISSUE TITLE
when converting from textile to other formats, percentage period percentage is not converted correctly

### ISSUE THREAD

**Issue by dbojan** [jgm/pandoc#9878]
**Explain the problem.**

When converting from textile markup to other formats, 'percentage period percentage'  is not converted correctly

text file named test.textile, containing text:
```
15%.
15%. 70%

15% %
```
gets converted to html:

```
<p>15%.<br />
15. 70</p>
<p>15% %</p>
</body>
</html>
```
second line is missing % signs

correct conversion would be:
```
<p>15%.<br />
15%. 70%</p>
<p>15% %</p>
</body>
</html>
```

if percentage period percentage (15%. 70%) is in the document it does not convert correctly, like it does on the https://textile-lang.com/

command line: pandoc.exe test.textile -s -o test.html

**Pandoc version?**
windows, pandoc.exe 3.2

**Comment by jgm** [comment]
Thanks for the report. Fix is on the way.

**Comment by dbojan** [comment]
Hello. This still does not convert properly to html in pandoc 3.5

output:
```
<p>15%.<br />
15. 70</p>
<p>15% %</p>
```

also some other examples:

```
63 %. -ok
63% ). 75 % -ok
63%) . In. - ok
63%. -not ok % followed by. and space, also second percentage sign is not displayed
63%). % -not ok
63%). 75 %  -not ok
```


```
<p>63 %. -ok</p>
<p>63% ). 75 % -ok</p>
<p>63%) . In. - ok</p>
<p>63. -not ok followed by. and space, also second percentage sign is
not displayed</p>
<p>63). -not ok</p>
<p>63). 75 -not ok</p>
```
