### ISSUE TITLE
pandoc does not honor the AsciiDoc page breaks or include::[] macros

### ISSUE THREAD

**Issue by todd-a-jacobs** [jgm/pandoc#988]
AsciiDoc defines `<<<` as a [page break](http://www.methods.co.nz/asciidoc/userguide.html#_page_breaks), but does not recognize the resulting DocBook markup of `<simpara><?asciidoc-pagebreak?></simpara>`. The DocBook XML is a necessary intermediate step for master documents that contain subdocuments, since pandoc doesn't (yet?) honor the `include::[]` macro for [combining separate documents](http://www.methods.co.nz/asciidoc/userguide.html#X90), either.

Running pandoc on a master document results in a bulleted list of  include statements. Running pandoc on AsciiDoc -> DocBook output results in the page breaks simply being ignored.

**Comment by tarikgraba** [comment]
@jgm In relation with #1934 can `<?asciidoc-pagebreak?>` support added to the DocBook reader?

**Comment by jgm** [comment]
You might add a note to #1934 about `<?asciidoc-pagebreak?>` if it's not there already.
