### ISSUE TITLE
accept crypton-connection-0.4

### ISSUE THREAD

**Issue by ysangkok** [jgm/pandoc#9886]
it would be nice to accept this new version of the dependency so stackage can upgrade, see

* https://github.com/commercialhaskell/stackage/issues/7425

**Comment by jgm** [comment]
Yes, the change is already in master, just not yet in a released version.

**Comment by ysangkok** [comment]
[changelog](https://hackage.haskell.org/package/pandoc-3.2.1/changelog) for v3.2.1 mentions crypton-connection, so it seems this has been completed, thank you, closing
