### ISSUE TITLE
`tex_math_dollars` appears to be not supported for ConTeXt

### ISSUE THREAD

**Issue by DasNaCl** [jgm/pandoc#9887]
Make an empty file called `x.md`. Then, run `pandoc` as follows:
```sh
pandoc --to context+tex_math_dollars "${FILE_SRC}" -o "${FILE_TEX}"
```
It will print:
```
The extension tex_math_dollars is not supported for context
``` 
Since the documentation for `tex_math_dollars` explicitly lists ConTeXt as a target, this error message is unexpected.
I'm running newest pandoc on Artix Linux

**Comment by jgm** [comment]
`tex_math_dollars` is a *markdown* extension which determines what is parsed as a math element. The part of the documentation that mentions ConTeXt is just about how math is rendered in ConTeXt. (In fact, it is rendered inside `$..$`.)  I'm not sure what you're trying to achieve, but I suspect you'll get what you want if you just omit the `+tex_math_dollars`.
