### ISSUE TITLE
Noisy Output: Could not create directory "plantuml-images"

### ISSUE THREAD

**Issue by lixueyi83** [jgm/pandoc#9895]
I am continue getting this noisy message, `Could not create directory "plantuml-images"`, when the `plantuml-images` folder was already created previously. 

Is it a bug? If not, how to silent that message? Thanks.

Eric

**Comment by lixueyi83** [comment]
This is the command I convert markdown to pdf
- **pandoc -s --pdf-engine=weasyprint --css=$HOME/.pandoc/css/pandoc.css --filter=pandoc-plantuml input.md -o output.pdf**

**Comment by tarleb** [comment]
It seems that these messages are emitted by the `pandoc-plantuml` filter, which belongs to a separate project. Please raise this issue there, as pandoc has no control over the logging actions of that filter.
