### ISSUE TITLE
MANUAL.txt incorrectly states that reference-links allows true/false

### ISSUE THREAD

**Issue by dfc** [jgm/pandoc#9919]
**Explain the problem.**

The `MANUAL.txt` file in `HEAD` says that `--reference-links` can be true or false. However it seems that `pandoc` does not allow an argument. 

```
pandoc --reference-links=false -t markdown MANUAL.txt 
option `--reference-links' doesn't allow an argument
Try pandoc --help for more information.
```

I'm sorry, I would submit a patch to the documentation but I am not sure what the correct behavior is.  

**Pandoc version?**

3.1.3

**Comment by jgm** [comment]
Works fine with 3.2.1.
Check the changelog to see when this feature was added?

**Comment by jgm** [comment]
Allowing boolean flags to take an optional argument is a new feature as of 3.1.5.
