### ISSUE TITLE
Markdown to epub horizontal lines not appearing

### ISSUE THREAD

**Issue by samwh1te** [jgm/pandoc#9924]
**Explain the problem.**
I'm trying to convert markdown to epub with horizontal lines, but they don't show.
```markdown
% Book title
% Book author
# Chapter 1
Hello

---

World
```
And `pandoc test.md -o test.epub` does't result in any horizontal lines in the epub. I'm viewing it with [Foliate](https://github.com/johnfactotum/foliate), which shows the horizontal line if I convert the same markdown file through CloudConvert.

**Pandoc version?**
pandoc 3.2.1 on Ubuntu 22.04

**Comment by johnblommers** [comment]
So I tweaked the test.md file thus:

```
---
title: Book title
author: Just Me
---

# Chapter 1

Hello

---

World

```

and converted it with Pandoc. Sure enough Foliate does not show the horizontal line. But that's on Foliate because Calibre's eBook viewer show it just fine as does Sigil

**Comment by samwh1te** [comment]
Ah, I should have had a look on different software. Thanks very much!
