### ISSUE TITLE
`--defaults` argument does not respect `--data-dir` argument

### ISSUE THREAD

**Issue by mboyea** [jgm/pandoc#9926]
# Issue Description

According to [https://pandoc.org/MANUAL.html#defaults-files](https://pandoc.org/MANUAL.html#defaults-files):
"Defaults files can be placed in the `defaults` subdirectory of the user data directory and used from any directory. For example, one could create a file specifying defaults for writing letters, save it as `letter.yaml` in the `defaults` subdirectory of the user data directory, and then invoke these defaults from any directory using `pandoc --defaults letter` or `pandoc -dletter`."

**Expected behavior:** When a user overrides the "user data directory" via the `--data-dir` argument, the `--defaults` argument should search that directory for its target file.

**Real behavior:** When a user overrides the "user data directory" via the `--data-dir` argument, the `--defaults` argument searches for its target file in the default "user data directory" instead of the one declared by the user.

## Steps to Reproduce

- `mkdir -p pandoc-test/data-dir/defaults`
- `mkdir -p pandoc-test/data-dir/templates`
- `printf '# a markdown file' > pandoc-test/afile.md`
- `printf 'template: atemplate' > pandoc-test/data-dir/defaults/adefault.yaml`
- `pandoc -D latex > pandoc-test/data-dir/templates/atemplate.latex`
- `pandoc pandoc-test/afile.md --output=pandoc-test/afile.pdf --defaults=adefault --data-dir=pandoc-test/data-dir`

## Pandoc Version

```
$ pandoc --version
pandoc.exe 3.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: C:\Users\mathew.boyea\AppData\Roaming\pandoc
```

Note: This has not been tested on Linux, just on Pandoc for Windows.

**Comment by jgm** [comment]
Switch the order of `--data-dir` and `--defaults` on the command line. These are processed in order, and you're only setting data-dir after defaults have already been processed.

**Comment by mboyea** [comment]
> Switch the order of `--data-dir` and `--defaults` on the command line. These are processed in order, and you're only setting data-dir after defaults have already been processed.

`pandoc pandoc-test/afile.md --output=pandoc-test/afile.pdf --defaults=adefault --data-dir=pandoc-test/data-dir`:

![image](https://github.com/jgm/pandoc/assets/68197922/8efeb3e7-3bb7-44c1-ae66-f76ae7aca085)

This was the solution. Thank you very much for your time.
