### ISSUE TITLE
LaTeX output from Markdown: lstlisting with custom language

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#993]
It seems that Pandoc does not pass the language tag from code block down to LaTeX source, if it does not know the source language name or thinks LaTeX does not know the language name. E.g., 

```
~~~~{.diff}
Something.
~~~~
```

produces just

```
\begin{lstlisting}
```

instead of

```
\begin{lstlisting}[language=diff]
```

But I can define the `diff` language style myself in header. Would it be possible for Pandoc to just generate `\begin{lstlisting}[language=diff]`?

**Comment by cpieringer** [comment]
@wilx Do you know how to transform listings in latex to htlm5 using pandoc?
