### ISSUE TITLE
Title from md to docx

### ISSUE THREAD

**Issue by mrkissinger** [jgm/pandoc#9934]
I upgraded to pandoc-3.2.1-1-amd64.deb on my Debian Linux.
I found the title in markdown("% title") didn't convert to style TITLE anymore, but style NORMAL instead.

I downgraded to pandoc-3.1.11.1-1-amd64.deb, it works fine.

Is it an issue?

**Comment by jgm** [comment]
I can't reproduce this.  pandoc 3.2.1 does attach the "Title" style to the title...

**Comment by iandol** [comment]
Pandoc V3.2.1 (installed via LinuxBrew) generates Title style in docx output for me too? Ubuntu 22.04.

**Comment by mrkissinger** [comment]
It caused by my reference file. But the file worked well on old versions of  pandoc. Can you help to check the files, please?

[test.tar.gz](https://github.com/user-attachments/files/16064102/test.tar.gz)

**Comment by iandol** [comment]
Your test.md renders fine on my machine with latest pandoc using the default reference.docx or my own custom.docx


```
> pandoc --reference-doc=custom.docx -o out.docx test.md
> open -a "LibreOffice.app" out.docx
```
<img width="690" alt="image" src="https://github.com/jgm/pandoc/assets/153905/d0c5d03d-270e-44f5-b7ed-0158ef483f55">

---

So the problem is your ref.docx — **interestingly** if I use your `ref.docx` but open the output with LibreOffice, your Title style works:

```
> pandoc --reference-doc=ref.docx -o out.docx test.md
> open -a "LibreOffice.app" out.docx
```
<img width="715" alt="image" src="https://github.com/jgm/pandoc/assets/153905/bc7d97e7-ea7b-49c0-96ea-e58e53688113"> 

[out.docx](https://github.com/user-attachments/files/16064489/out.docx) -- works in LibreOffice, fails in MS Word.

So there is a subtle issue that only affects your ref.docx with output only opened in Word. There were several recent changes I think to the Word writer, but you would need to pinpoint which exact Pandoc build this broke to help fix it. My only advice is to remake your ref.docx using the latest Pandoc reference.docx, any potential bug is subtle and may take time to track down.

**Comment by iandol** [comment]
The title XML with your ref.docx:

```
<w:p>
      <w:pPr>
        <w:pStyle w:val="Title" />
      </w:pPr>
      <w:r><w:rPr><w:rFonts w:hint="eastAsia" /></w:rPr><w:t xml:space="preserve">中文標題</w:t></w:r>
    </w:p>
```

And with the standard one:

```
<w:p>
      <w:pPr>
        <w:pStyle w:val="Title" />
      </w:pPr>
      <w:r><w:rPr><w:rFonts w:hint="eastAsia" /></w:rPr><w:t xml:space="preserve">中文標題</w:t></w:r>
    </w:p>
```

So the problem is not in the document XML itself, but the styles.xml

ref.docx:
```xml
<w:style w:styleId="24" w:type="paragraph"><w:name w:val="Title" /><w:basedOn w:val="1" /><w:next w:val="3" /><w:qFormat /><w:uiPriority w:val="0" /><w:pPr><w:keepNext /><w:keepLines /><w:spacing w:line="240" w:lineRule="auto" /><w:ind w:firstLine="0" w:firstLineChars="0" /><w:jc w:val="center" /></w:pPr><w:rPr><w:rFonts w:ascii="方正黑体_GBK" w:cstheme="majorBidi" w:eastAsia="黑体" w:hAnsi="方正黑体_GBK" /><w:b /><w:bCs /><w:color w:themeColor="text1" w:val="000000" /><w:sz w:val="48" /><w:szCs w:val="36" /><w14:textFill><w14:solidFill><w14:schemeClr w14:val="tx1" /></w14:solidFill></w14:textFill></w:rPr></w:style>
```

Default:

```xml
  <w:style w:styleId="Title" w:type="paragraph">
    <w:name w:val="Title" />
    <w:basedOn w:val="Normal" />
    <w:next w:val="BodyText" />
    <w:link w:val="TitleChar" />
    <w:uiPriority w:val="10" />
    <w:qFormat />
    <w:rsid w:val="00A10FD9" />
    <w:pPr>
      <w:spacing w:after="80" w:line="240" w:lineRule="auto" />
      <w:contextualSpacing />
      <w:jc w:val="center" />
    </w:pPr>
    <w:rPr>
      <w:rFonts w:asciiTheme="majorHAnsi" w:cstheme="majorBidi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" />
      <w:spacing w:val="-10" />
      <w:kern w:val="28" />
      <w:sz w:val="56" />
      <w:szCs w:val="56" />
    </w:rPr>
  </w:style>
```

**Comment by iandol** [comment]
And editing your ref.docx in LibreOffice (where latin and asian fonts are better managed and saving it and your ref.docx now generates working titles:

<img width="964" alt="image" src="https://github.com/jgm/pandoc/assets/153905/d9ff1b04-6a02-4fe7-b74f-38e1cd491f24">

[ref2.docx](https://github.com/user-attachments/files/16064980/ref2.docx)

Takehome: LibreOffice is a better Word than Word! 🤣

**Comment by jgm** [comment]
Might be interesting do a diff between styles.xml on ref.docx and ref2.docx.

**Comment by mrkissinger** [comment]
Thanks for your reply.

I downloaded from https://github.com/jgm/pandoc/releases/download/3.2.1/pandoc-3.2.1-1-amd64.deb, which caused my problem.

> So there is a subtle issue that only affects your ref.docx with output only opened in Word. There were several recent changes I think to the Word writer, but you would need to pinpoint which exact Pandoc build this broke to help fix it. My only advice is to remake your ref.docx using the latest Pandoc reference.docx, any potential bug is subtle and may take time to track down.

**Comment by iandol** [comment]
> I downloaded from https://github.com/jgm/pandoc/releases/download/3.2.1/pandoc-3.2.1-1-amd64.deb, which caused my problem.

Well you could roll back to an old pandoc, but isn't it just better to use the new reference.docx ([ref2.docx](https://github.com/user-attachments/files/16064980/ref2.docx)) instead? I also tried to edit ref.docx in Word, changing the Latin/Asian font for Title and it also works now: [ref3.docx](https://github.com/user-attachments/files/16075377/ref3.docx)

> Might be interesting do a diff between styles.xml on ref.docx and ref2.docx.

Comparing ref.docx and ref3.docx (the one created by MS Wors as to minimise and LO diffs)

[styles-compared.zip](https://github.com/user-attachments/files/16075368/styles-compared.zip)

Too many changes to appear obviously useful, but in general styles-old.xml uses `w:styleId="#"` - a numeric ID, and styles-new.xml uses names. I only changed the "Title" style but in fact every ID was changed to names so it seems that is what MS Word prefers.
