### ISSUE TITLE
`--metadata lang=ja-JP` has been expected to work for docx output as same as other East-Asian languages such as `zh-CN`

### ISSUE THREAD

**Issue by skystar0227** [jgm/pandoc#9938]
According to #7022, `pandoc main.md -o main.docx --metadata lang=zh-CN` currently outputs `<w:lang w:val="en-US" w:eastAsia="zh-CN" />` into main.docx, instead of  `<w:lang w:val="zh-CN" w:eastAsia="en-US" />`.
`--metadata lang=ja-JP` has been expected a same performance but not.

The following comment mentioned `jp-JP` as for Japanese but I think `ja-JP` is correct.
https://github.com/jgm/pandoc/issues/7022#issuecomment-1237576087

So my idea is `--metadata lang=ja-JP` would work as expected if `"jp"` was replaced with `"ja"` in the following line.
https://github.com/jgm/pandoc/blob/f1799505a9b83c0b292603a0584a04d69257ca90/src/Text/Pandoc/Writers/Docx.hs#L164

Thank you in advance for any help.

**Comment by jgm** [comment]
Sorry, that was just a mistake on our part. And there are a few other places in the code where we used `jp` instead of `ja`, which I've also fixed.

**Comment by TomBener** [comment]
Sorry for my previous spelling mistake. Happy to see the feedback and a quick fix.

**Comment by skystar0227** [comment]
@jgm Thank you very much for very quick fix!

@TomBener No worries, just a typo. I always appreciate your contributes leading to improvement for the East-Asian languages support.
