### ISSUE TITLE
pandoc 3.2.1 issue with input markdown images and latex output

### ISSUE THREAD

**Issue by gbonazzoli** [jgm/pandoc#9940]
Starting with version 3.2.1 the following command:

```
root@mediawiki# pandoc -s -o /tmp/Incident_WDC_WUH721818AL_2024-07-02.pdf --template eisvogel --pdf-engine xelatex  -f markdown+implicit_figures --listings /tmp/Incident_WDC_WUH721818AL_2024-07-02.md
```

outpus the following error:

```
Error producing PDF.
! Undefined control sequence.
l.478 \pandocbounded
```

It is probably dued to these images referenced by markdown file:

```
![Incident WDC WUH721818AL - Disk Failed.png](Incident WDC WUH721818AL - Disk Failed.png)

![Incident WDC WUH721818AL - Logs Su iDRAC.png](Incident WDC WUH721818AL - Logs Su iDRAC.png)
```
Pandoc version is:

```
root@mediawiki# pandoc --version
pandoc 3.2.1
Features: +server +lua
Scripting engine: Lua 5.4
```

with the following versions, the problem does not exist:

- pandoc-3.1.2-linux-amd64.tar.gz
- pandoc-3.1.6-linux-amd64.tar.gz
- pandoc-3.1.7-linux-amd64.tar.gz
- pandoc-3.1.8-linux-amd64.tar.gz
- pandoc-3.1.9-linux-amd64.tar.gz
- pandoc-3.1.11.1-linux-amd64.tar.gz
- pandoc-3.1.12.1-linux-amd64.tar.gz
- pandoc-3.1.12.2-linux-amd64.tar.gz
- pandoc-3.1.12.3-linux-amd64.tar.gz
- pandoc-3.1.13-linux-amd64.tar.gz
- pandoc-3.2-linux-amd64.tar.gz

**Comment by cagix** [comment]
this is an issue with eisvogel, not pandoc: https://github.com/Wandmalfarbe/pandoc-latex-template/issues/391
