### ISSUE TITLE
From TWiki to Markdown: Convert words in PascalCase to links

### ISSUE THREAD

**Issue by oraculix** [jgm/pandoc#9944]
**Describe your proposed improvement and the problem it solves.**

Internal WikiLinks are one of the most elementary features of a Wiki. While bracketed links are converted by pandoc, WikiLinks in PascalCase aren't implemented yet.
When converting a well-linked Wiki, this important information gets lost. I suggest to implement this for all paragraphs.

As discussed in #9941:

Example input:
```
This is a ClassicWikiLink.

This is an !EscapedWikiWord that must not be converted to a link.
```

Command line: `pandoc -f twiki -t markdown test.txt `

Expected output:
```
This is a [ClassicWikiLink](ClassicWikiLink).

This is an EscapedWikiWord that must not be converted to a link.
```

**Describe alternatives you've considered.**

My current workaround is a simple approach with `sed`, but that cannot substitute the parsing pandoc does. E.g., code blocks cannot be exempt from conversion with this method.

**Comment by jgm** [comment]
Fixed by commit 5604ca612
