### ISSUE TITLE
Skylighting JSON `my.theme` won't allow css variables?

### ISSUE THREAD

**Issue by badlydrawnrob** [jgm/pandoc#9951]
Apologies if this should be a request rather than a bug, but I thought it would be an easy thing to add a [CSS variable](https://developer.mozilla.org/en-US/docs/Web/CSS/var) to the Skylighting JSON theme. When I try to compile it, I get a `Could not read highlighting theme my.theme` error. I'm guessing it checks if it's a valid hex code?

```json
{
    "..."
    "text-styles": {
        "Alert": {
            "text-color": "var(--variable)",
            "background-color": null,
            "bold": false,
            "italic": false,
            "underline": false
        },
}
```

Current version `pandoc 3.2.1` on MacOS (Intel). This might be a handy feature, it might be a silly thing to try to do. I'd like to do something like this in my "[learn coding with anki tool](https://github.com/badlydrawnrob/anki)" to [easily change the colours](https://github.com/badlydrawnrob/anki/blob/1c08c32bb3034aad0adebf1c41e5103921fbedc1/source/style/partials/skylighting.less#L72).

I'm not sure how the HTML template `$styles.html()$` interops with Skylighting, so perhaps it's easier to just hardcode it as I'm doing now.

**Comment by jgm** [comment]
No, you can't use CSS here.  This data structure is format-agnostic; you can generate CSS from it, but this is not allowed in the `text-color` field.
