### ISSUE TITLE
Differentiate <em> produced by * from _

### ISSUE THREAD

**Issue by ag-eitilt** [jgm/pandoc#9965]
Yes, this is yet another entry into the perpetual debate, sorry.  The main thing differentiating my specific question is that I'm happy enough with the defaults staying as they are[^span] and relegating the `<i>`/`<b>` writing to a Lua filter, but I want to make that distinction via `*...*` being `<em>` and `_..._` being `<i>`[^four-way] -- Markdown allows distinct, if normally synonymous, syntax; I want to be able to make use of every tool it gives me.  In other words, this ticket is *specifically* asking for something like the `<em class="i">` support[^classes] mentioned in https://github.com/jgm/pandoc/issues/5263#issuecomment-487397486 for distinguishing the original punctuation.  All discussion of what should be the default, or what people's filters process each of these into is explicitly out of scope.

#684 would obviously solve that, but that's effectively stalled (and I understand why, no judgement meant) and is overkill for simply enabling filter-based handling of this.  I had been running my documents through a preprocessor, but that's proven prone to user error in forgetting to preprocess, and more critically means I have to write my own partial Markdown parser separately and hope it concurs with Pandoc's (and which quickly becomes much less "partial" when trying to handle hard-broken paragraphs, and tables, and...)  I've finally given up maintaining that and just patched the Markdown reader itself via my package manager:

```patch
--- _cabal_deps/pandoc-3.1.12.3/src/Text/Pandoc/Readers/Markdown.hs.orig        2001-09-09 01:46:40 UTC
+++ _cabal_deps/pandoc-3.1.12.3/src/Text/Pandoc/Readers/Markdown.hs
@@ -1672,10 +1672,12 @@ three c = do
 three :: PandocMonad m => Char -> MarkdownParser m (F Inlines)
 three c = do
   contents <- mconcat <$> many (notFollowedBy (ender c 1) >> inline)
-  (ender c 3 >> updateLastStrPos >> return (B.strong . B.emph <$> contents))
-    <|> (ender c 2 >> updateLastStrPos >> one c (B.strong <$> contents))
-    <|> (ender c 1 >> updateLastStrPos >> two c (B.emph <$> contents))
+  (ender c 3 >> updateLastStrPos >> return (charMarker . B.strong . charMarker . B.emph <$> contents))
+    <|> (ender c 2 >> updateLastStrPos >> one c (charMarker . B.strong <$> contents))
+    <|> (ender c 1 >> updateLastStrPos >> two c (charMarker . B.emph <$> contents))
     <|> return (return (B.str $ T.pack [c,c,c]) <> contents)
+    where charMarker | c == '_' = B.spanWith ("",[],[("data-md-char","_")])
+                     | otherwise = B.spanWith ("",[],[("data-md-char","*")])
 
 -- Parse inlines til you hit two c's, and emit strong.
 -- If you never do hit two cs, emit ** plus inlines parsed.
@@ -1683,8 +1685,10 @@ two c prefix' = do
 two c prefix' = do
   contents <- mconcat <$> many (try $ notFollowedBy (ender c 2) >> inline)
   (ender c 2 >> updateLastStrPos >>
-                return (B.strong <$> (prefix' <> contents)))
+                return (charMarker . B.strong <$> (prefix' <> contents)))
     <|> return (return (B.str $ T.pack [c,c]) <> (prefix' <> contents))
+    where charMarker | c == '_' = B.spanWith ("",[],[("data-md-char","_")])
+                     | otherwise = B.spanWith ("",[],[("data-md-char","*")])
 
 -- Parse inlines til you hit a c, and emit emph.
 -- If you never hit a c, emit * plus inlines parsed.
@@ -1694,8 +1698,10 @@ one c prefix' = do
                            <|> try (string [c,c] >>
                                     notFollowedBy (ender c 1) >>
                                     two c mempty) )
-  (ender c 1 >> updateLastStrPos >> return (B.emph <$> (prefix' <> contents)))
+  (ender c 1 >> updateLastStrPos >> return (charMarker . B.emph <$> (prefix' <> contents)))
     <|> return (return (B.str $ T.singleton c) <> (prefix' <> contents))
+    where charMarker | c == '_' = B.spanWith ("",[],[("data-md-char","_")])
+                     | otherwise = B.spanWith ("",[],[("data-md-char","*")])
 
 strongOrEmph :: PandocMonad m => MarkdownParser m (F Inlines)
 strongOrEmph =  enclosure '*' <|> enclosure '_'
```

That's still a bit rougher than I'd want to submit a PR for -- it would be nice to not risk introducing spans within spans, and I'd want to look through the other formats to see if they make a similar distinction Pandoc winds up collapsing (HTML is obvious) which will wind up needing a different attribute name/value -- but I wanted to see if something along these lines could wind up being accepted, or if it's just something I keep on my own machine.  It's much more dirty than actually putting the attribute on the `<em>` like was mentioned, but that's an AST change that I didn't want to get tangled up in for the sake of a quick fix (though would be willing to put in the effort for if we did decide to pull the trigger on a breaking change).

For completeness, my even dirtier Lua filter.  I don't actually make use of the `data-md-char="*"` alignment, but I know a lot of people are `_`-primary in their Markdown and may want the reverse, or even have something like both `_` being traditionally italicized and both `*` bold, and unless the attribute makes it onto the `Emph`/`Strong` directly, it's *much* harder to write a safe replacement that depends on the attribute being missing.

```lua
function Span(el)
	char = el.attributes['data-md-char']
	if char == nil then
		return el
	else
		el.attributes['data-md-char'] = nil
		hasOtherAttributes = false
		for _ in pairs(el.attributes) do
			hasOtherAttrbutes = true
		end
		if #el.classes == 0 and not hasOtherAttrbutes and el.identifier == '' then
			return deemphasize(el.content, char)
		else
			el.content = deemphasize(el.content, char)
			return el
		end
	end
end
function deemphasize(els, char)
	out = pandoc.List()
	for _, el in ipairs(els) do
		if el.t == 'Emph' and char == '_' then
			out:insert(pandoc.RawInline('html', '<b>'))
			out:extend(el.content)
			out:insert(pandoc.RawInline('html', '</b>'))
		elseif el.t == 'Strong' and char == '_' then
			out:insert(pandoc.RawInline('html', '<i>'))
			out:extend(el.content)
			out:insert(pandoc.RawInline('html', '</i>'))
		else
			out:insert(el)
		end
	end
	return out
end
```

[^span]: Modulo an added `<span>` in this particular implementation, but that's an implementation detail.  If we do go with this method as it is, we'd need a new extension to avoid breaking strict `p > em` CSS, or a broad deletion across the writers, or just assume that falls under the same backwards-incompatible major version bump.

[^four-way]: More or less.  As you can see from my filter, I actually have a much less typical alignment of syntax, but describing it and especially the *why* behind it would just make this this all unnecessarily confusing, so I've written what I imagine most people would be asking for everywhere but the Lua.  Certainly happy to explain, just not in the first post here.

[^classes]: Which is basically possible today through what I will admit is the *correct* way of marking `<i>` in Markdown: `[...]{.i .latin-name}`, as that is able to distinguish the semantic purpose of the element (Latin taxonomy is very different from a passage in Hindi, despite both being marked by `<i>`).  However, even just `[...]{.i}` is comparitively heavy-weight both by keystroke count and visually, and the whole point of writing Markdown is to avoid peppering documents with (too much) noisy markup.

**Comment by bpj** [comment]
As a workaround you can use `_*foo*_` and have a Lua filter look for Emph elements with another Emph element as only content, and similarly `__**bar**__` with nested Strong elements. Just use the nested construct for whichever of `<em>` and `<i>` you use least often. Or `[foo]{.i}` and `[bar]{.b}` and look for spans with the `i` and `b` classes, although that doesn't look quite as nice!

**Comment by ag-eitilt** [comment]
Given that the response to me saying that I have a working solution and did not want to introduce extra markup was to suggest a workaround relying on extra markup, I'm going to assume a PR along these lines isn't going to be accepted.  I'll keep this local, then, and if we ever get #684 implemented, specifically via an inline-AST implementation, I'll see about adapting this on top of that and pushing something up then.
