### ISSUE TITLE
Headers inside <div> tags do not appear in the table of contents (html, texinfo)

### ISSUE THREAD

**Issue by joostkremers** [jgm/pandoc#997]
As discussed in this thread:

https://groups.google.com/forum/#!topic/pandoc-discuss/ZOuYDaq3WcQ

headers that are inside `<div>` tags in Markdown input are not included in the table of contents. This happens at least in Texinfo and in HTML output (the latter with the `--toc` flag).

The issue is caused by the new handling of `<div>` tags in Markdown input, which are converted into `Div` elements, causing headers inside them to appear below the top level, while the relevant writers assume that headers are always at the top level.

In Pandoc 1.11, the following Markdown text:

```
% Title
% Author

<div id="main">

# Header 1

Text. Text.

# Header 2

Text. Text.

</div>
```

would yield HTML output in which the TOC appears _outside_ `<div id="main">`, which allowed the body of the text to be styled and placed separately from the TOC. For me, it would be preferable if this behaviour would be restored.

**Comment by LarsEKrueger** [comment]
It seems possible to resort the output of hierarchicalizeWithIds inside hierarchicalize. Would that have any undesirable consequences? If not, I would try to write a sorter and send a PR.

Also, would it hurt to make the matched pattern there from

```
hierarchicalizeWithIds ((Div ("",["references"],[])
                         (Header level (ident,classes,kvs) title' : xs)):ys) =
```

to something more general, i.e. allowing non-empty ids and checking if `references` is just one of the classes? This would allow to apply a style to a part of the generated HTML file.
