### ISSUE TITLE
Failing include does not lead to non zero exit code

### ISSUE THREAD

**Issue by janvlug** [jgm/pandoc#9972]
When an include fails, pandoc still returns 0 when exiting.

Take for example this file:
[example.md](https://github.com/user-attachments/files/16178838/example.md)

and execute this `pandoc` command:
```
pandoc --fail-if-warnings --lua-filter=include-files.lua example.md --output jan.html
```
This results in this messages in the terminal:
```
Cannot open file file_to_include.html | Skipping includes
```

However, the exit code is still 0 instead of an error code.

**Pandoc version?**
pandoc 3.1.3
Features: -server +lua
Scripting engine: Lua 5.4

**Comment by tarleb** [comment]
Please re-raise this issue with the project from where you've gotten the `include-files.lua` filter. The filter should use the `pandoc.log` module to raise the warning.
