### ISSUE TITLE
`--strip-comments` ignored for LaTeX to Markdown or HTML

### ISSUE THREAD

**Issue by LeaVerou** [jgm/pandoc#9989]
When converting from LaTeX to Markdown comments are not preserved no matter what I try, even with `--strip-comments=false`.
Same thing when converting LaTeX to HTML.

For example this LaTeX code:

```latex
Text % This is a comment
% More comments
More text
```

is converted to:

```md
Text More text
```

in Markdown and 

```html
<p>Text More text</p>
```

in HTML.

I wondered if it may be similar to #9322 but `-f latex+raw_tex` did not help.

**Comment by LeaVerou** [comment]
Thanks for explaining. In that case, I guess this is a feature request? 🙏🏼 `--strip-comments` is a generic enough name it can be used for more generic stripping or non-stripping of comments (and is the user expectation if they don’t read the docs super closely).

When authoring papers in LaTeX it’s common to comment out actual content to fit within conference page limits. This means I have to either lose that content or (what I did) spend days coding preprocessing and postprocessing pipelines outside of pandoc (which is very nontrivial because it's hard to find a token that a) won't be stripped and also b) won't interfere with anything else).

**Comment by jgm** [comment]
Well, a simple workaround is to comment out your code using a custom macro, `\comment{...}`, which you can define as follows:
```
\newcommand{\comment}[1]{}
```
Pandoc will pass this through if you specify `+raw_tex`.

**Comment by LeaVerou** [comment]
That would mean transforming the comments to use that custom macro, which is a similar amount of work as what I’m doing now (especially since I'll need to transform this back to comments on the other end of the conversion)...

Some more context about my use case may help. I’m using pandoc to process papers written over the course of a decade, so I can author my PhD thesis using Markdown + web technologies. I’m not authoring the LaTeX now so I can make different decisions about how to comment. I think commenting out content to temporarily remove it from view without completely deleting it is pretty common for all markup languages that support comments.

From an API design perspective, preserving comments follows the principle of least surprise. If comments on the output are undesirable, writing custom code to strip them is _far_ easier than writing custom code to preserve them by transforming them on both ends (though ideally `--strip-comments` should work with all formats).

Is the issue that the LaTeX parser pandoc is using doesn't preserve comments in the AST?

**Comment by jgm** [comment]
There is no dedicated Comment element in the pandoc AST. Hence, the only option for LaTeX comments would be to parse them as raw TeX.  But that would not play well with other parts of pandoc. For example, raw TeX elements are passed through verbatim to pandoc markdown output, but pandoc's markdown parser wouldn't recognize them as TeX (`%` just means `%`).

**Comment by LeaVerou** [comment]
I’m definitely missing a lot of the implementation details, but would adding a `Comment` node be an option? It seems more broadly useful, and individual parsers can opt-in to it gradually (if they don’t preserve comments, they simply don’t create Comment nodes).
